### ISSUE TITLE
Validation Fails with Controlled Components When Using FormContext

### ISSUE THREAD

**Issue by Alexander-Karsten** [react-hook-form/react-hook-form#1000]
Hello,
I am using Material UI and react-hook-form and have an issue with validation when using a form split across multiple components. I have created a Codesandbox which you can see below.

**To Reproduce**
Steps to reproduce the behaviour:
1. Visit the Codesandbox at https://codesandbox.io/s/objective-river-j7srv
2. Press "Add Phone"
3. Press "Save"
4. See that all required items have their errors shown
5. Enter a value into type on the new phone number that has appareared
6. See that the validation errors do not dissapear

**Codesandbox link**
https://codesandbox.io/s/objective-river-j7srv

**Expected behavior**
The errors should disappear when you enter a value

**Desktop (please complete the following information):**
 - OS: Elementary OS
 - Browser Chrome 
 - Version 4.8.2

**Additional context**
It may very well be that I am just using this library wrong, in that case I apologise and would gladly appreciate a pointer in the right direction. Thanks! :heart:

**Comment by Alexander-Karsten** [comment]
Upon further investigation it turns out I was not updating state correctly for the controlled component.
Apologies.

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report. Will take a look today.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/proud-pond-mqjf3

**Comment by bluebill1049** [comment]
`Controller` onChange expect you to return value, take a look at my CSB. :)

**Comment by bluebill1049** [comment]
have a read on the doc: https://react-hook-form.com/api#Controller

**Comment by Alexander-Karsten** [comment]
Thanks a lot @bluebill1049, really appreciate your answer and the hard work you've obviously put into this project.

I've had a play around a bit and also reading some more of the documentation I found out that I could make this work without managing any internal state in the `PhoneNumber` component, by passing `              inputRef={register({required: true})}` to the MUI `TextField` component and not using `Controller`at all. (Let me know if this doesn't make sense and you would like me to share an example)

Could you share which approach is more correct? It seems using `Controller` may be required for controlled inputs that do not provide a special parameter like `inputRef` as is the case with Material UI?

I have worked with Vue for a few years now but am very new to React, so this is all a lot to unpack for me, would appreciate some insight. Thanks!!

**Comment by bluebill1049** [comment]
> by passing inputRef={register({required: true})} to the MUI TextField component and not using Controllerat all. (Let me know if this doesn't make sense and you would like me to share an example)

Yes you can do that :)

I made Controller for dealing with external component, because not all external component expose `ref`. If you can get hold of the `ref`, you can use `register` natively.

**Comment by Alexander-Karsten** [comment]
Thank you so much @bluebill1049!
