### ISSUE TITLE
Controller expose if a field is required

### ISSUE THREAD

**Issue by lucapasquale** [react-hook-form/react-hook-form#10005]
**Is your feature request related to a problem? Please describe.**
I'm developing an ui library to be used in our internal application, and for that we are using `react-hook-form` with `zod` and `Material UI`. As part of this library, we created wrapper form item components that would style the item label, error message and etc.

We would also like to add a `*` next to the label of fields that are `required` by the form, so it can easily be seen by the user. Since we already use `zod`, we would like to only be able to declare if a form item is required once in the schema, and get that information back to the item on the `Controller`. That way we won't have the issue of the schema making a field required but forgetting to set it on the form item, or vice-versa.

**Describe the solution you'd like**
Add a `required: boolean` field to the `Controller.render.fieldState`, so my wrapper component would look like this:

```tsx
export function InputFormItem({ name, controller, label, ...inputProps }) {
	return (
		<Controller
		  name={name}
		  control={control}
		  render={({ field: { value, onChange }, fieldState }) => (
		    <FormField
				id={name}
				label={label}
				required={fieldState.required}
				error={fieldState.error?.message}
			>
		      <Input value={value} onChange={onChange} {...inputProps} />
		    </FormField>
		  )}
		/>
	);
}
```

Then, we can use it directly in our forms:

```ts
const schema = z.object({
	firstName: z.string().min(1),
	lastName: z.string().optional(),
})

const { control, handleSubmit } = useForm({
  resolver: zodResolver(schema),
});

<form>
	<InputFormItem
	  name="firstName"
	  control={control}
	  label="First Name"
	/>

	<InputFormItem
	  name="lastName"
	  control={control}
	  label="Last Name"
	/>
</form>
```

And it would show `First Name` as required, while `Last Name` would not.

**Describe alternatives you've considered**
The alternative that I have is to manually add the `required` prop to our form item components, and make sure that we are passing the right value depending on the `schema` used.

**Comment by Moshyfawn** [comment]
I'd even argue, these're are related #9461

**Comment by bluebill1049** [comment]
Yea would be great a common way to extract all the schema and we can potentially apply all the constraint API as well. @Moshyfawn Looks like GitHub cancel the sponsorship due to PayPal...  I will find an alternative way.

**Comment by Moshyfawn** [comment]
> Yea would be great a common way to extract all the schema and we can potentially apply all the constraint API as well

I've had multiple takes on this, but I don't like the API that comes out of it. That said, definitely worth looking into 💯

I've been experimenting with some validation API for that small form lib I try to work on and I might have something that can help shape the API for RHF.

> Looks like GitHub cancel the sponsorship due to PayPal... I will find an alternative way.

I appreciate it, Bill! Please, don't worry about it, it's all good 🖤

And, yea, the move to remove PayPal as an option for GH is mad, IMO!

**Comment by bluebill1049** [comment]
> And, yea, the move to remove PayPal as an option for GH is mad, IMO!

Yea, I was surprised to receive the email this morning.

**Comment by bluebill1049** [comment]
Yea... it sucks.
