### ISSUE TITLE
Example using reCAPTCHA

### ISSUE THREAD

**Issue by sliktrik** [react-hook-form/react-hook-form#1001]
Hi, just wondering if has used this with Google's reCAPTCHA and has an example?

**Comment by bluebill1049** [comment]
No, i haven't tried with that.  as long as the value readable from onChange then, i don't see a reason why it's not going to work tho.

**Comment by bluebill1049** [comment]
if anyone has an example feel free to post it here.

**Comment by shicholas** [comment]
A Captcha component:

```tsx
import {
  GoogleReCaptchaProvider,
  useGoogleReCaptcha
} from 'react-google-recaptcha-v3';
import { Button } from '@chakra-ui/core';
import React from 'react';

const CaptchaButton = ({ onVerifyCaptcha }) => {
  const { executeRecaptcha } = useGoogleReCaptcha();
  const clickHandler = async () => {
    if (!executeRecaptcha) {
      return;
    }

    const token = await executeRecaptcha('contact');

    onVerifyCaptcha(token);
  };

  return (
    <Button onClick={clickHandler}>
      Please validate you are a human.
    </Button>
  );
};

export const ReCaptcha = ({ onVerifyCaptcha }) => (
  <GoogleReCaptchaProvider
    reCaptchaKey="<YOUR_KEY>"
  >
    <CaptchaButton onVerifyCaptcha={onVerifyCaptcha} />
  </GoogleReCaptchaProvider>
);
```

And a form component:

```tsx
import { ReCaptcha, StringInput, Textarea } from '@forms/base';
import React, { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';

export const ContactForm = () => {
  const { handleSubmit, errors, formState, register, setValue } = useForm({
    mode: 'onChange'
  });
  const [isSubmitting, setIsSubmitting] = useState(false);

  const onSubmit = (values) => {
    setIsSubmitting(true);
    console.log(values);

    setIsSubmitting(false);
  };

  const onVerifyCaptcha = (token) => {
    setValue('captchaToken', token);
  };

  useEffect(() => {
    register({ name: 'captchaToken' }, { required: true });
  });

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <ReCaptcha onVerifyCaptcha={onVerifyCaptcha} />
      <button
        isLoading={isSubmitting}
        type="submit"
      >
        Send Message
      </button>
    </form>
  );
};
```

hope this helps!

**Comment by bluebill1049** [comment]
awesome thanks @shicholas for sharing.

**Comment by haripriyaaganesan** [comment]
> ```tsx
>   return (
>     <Button onClick={clickHandler}>
>       Please validate you are a human.
>     </Button>
>   );
> ```

How can I insert Recaptcha logo woth checkbox (I'm not a robot) instead of `<Button onClick={clickHandler}>
      Please validate you are a human.
    </Button>`

**Comment by bluebill1049** [comment]
> > ```tsx
> >   return (
> >     <Button onClick={clickHandler}>
> >       Please validate you are a human.
> >     </Button>
> >   );
> > ```
> 
> How can I insert Recaptcha logo woth checkbox (I'm not a robot) instead of `<Button onClick={clickHandler}> Please validate you are a human. </Button>`

can you please provide more context?

**Comment by tim1uphealth** [comment]
> ```tsx
> ```tsx
>   return (
>     <Button onClick={clickHandler}>
>       Please validate you are a human.
>     </Button>
>   );
> ```
> 
> 
> 
> How can I insert Recaptcha logo woth checkbox (I'm not a robot) instead of <Button onClick={clickHandler}> Please validate you are a human. </Button>
> 
> can you please provide more context?
> ```

Looking for an example that renders the traditional captcha checkbox input with the "I'm not a robot" label

**Comment by shicholas** [comment]
For v2 CAPTCHA, you should be able to implement that with https://react-hook-form.com/api#Controller

**Comment by itsMrAbhay** [comment]
Can someone please provide a v2 CAPTCHA example? Can't figure out how to validate with the Controller?

**Comment by tomliangg** [comment]
v2 captcha example (using react-recaptcha):
checkout the sandbox: https://codesandbox.io/s/react-hook-form-get-started-forked-m6tty?file=/src/index.js
checkout the site: https://m6tty.csb.app/

```javascript
import React from "react";
import ReactDOM from "react-dom";
import Recaptcha from "react-recaptcha";
import { useForm } from "react-hook-form";

import "./styles.css";

let recaptchaInstance;
const executeCaptcha = (e) => {
  e.preventDefault();
  recaptchaInstance.execute();
};

function App() {
  const { register, handleSubmit, errors } = useForm();
  const onSubmit = (data) => {
    console.log(data);
  }; // your form submit function which will invoke after successful validation

  return (
    <form>
      <label>Example</label>
      <input name="example" defaultValue="test" ref={register} />
      <label>ExampleRequired</label>
      <input
        name="exampleRequired"
        ref={register({ required: true, maxLength: 10 })}
      />
      {errors.exampleRequired && <p>This field is required</p>}
      <button type="submit" onClick={executeCaptcha}>
        Submit
      </button>
      <Recaptcha
        ref={(e) => (recaptchaInstance = e)}
        sitekey="6LdEiOEZAAAAALkNjecKwayqjmPyqcrgMW-mfNvk"
        size="invisible"
        verifyCallback={handleSubmit(onSubmit)}
      />
    </form>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by chtpl** [comment]
Just to make sure I understood the API correctly - it is necessary and secure to include the SITE key in the web UI, (_**not**_ the SECRET key), right?

**Comment by chtpl** [comment]
> A Captcha component:
> 
> ```tsx
> import {
>   GoogleReCaptchaProvider,
>   useGoogleReCaptcha
> } from 'react-google-recaptcha-v3';
> import { Button } from '@chakra-ui/core';
> import React from 'react';
> 
> const CaptchaButton = ({ onVerifyCaptcha }) => {
>   const { executeRecaptcha } = useGoogleReCaptcha();
>   const clickHandler = async () => {
>     if (!executeRecaptcha) {
>       return;
>     }
> 
>     const token = await executeRecaptcha('contact');
> 
>     onVerifyCaptcha(token);
>   };
> 
>   return (
>     <Button onClick={clickHandler}>
>       Please validate you are a human.
>     </Button>
>   );
> };
> 
> export const ReCaptcha = ({ onVerifyCaptcha }) => (
>   <GoogleReCaptchaProvider
>     reCaptchaKey="<YOUR_KEY>"
>   >
>     <CaptchaButton onVerifyCaptcha={onVerifyCaptcha} />
>   </GoogleReCaptchaProvider>
> );
> ```
> 
> And a form component:
> 
> ```tsx
> import { ReCaptcha, StringInput, Textarea } from '@forms/base';
> import React, { useEffect, useState } from 'react';
> import { useForm } from 'react-hook-form';
> 
> export const ContactForm = () => {
>   const { handleSubmit, errors, formState, register, setValue } = useForm({
>     mode: 'onChange'
>   });
>   const [isSubmitting, setIsSubmitting] = useState(false);
> 
>   const onSubmit = (values) => {
>     setIsSubmitting(true);
>     console.log(values);
> 
>     setIsSubmitting(false);
>   };
> 
>   const onVerifyCaptcha = (token) => {
>     setValue('captchaToken', token);
>   };
> 
>   useEffect(() => {
>     register({ name: 'captchaToken' }, { required: true });
>   });
> 
>   return (
>     <form onSubmit={handleSubmit(onSubmit)}>
>       <ReCaptcha onVerifyCaptcha={onVerifyCaptcha} />
>       <button
>         isLoading={isSubmitting}
>         type="submit"
>       >
>         Send Message
>       </button>
>     </form>
>   );
> };
> ```
> 
> hope this helps!

This was for Recaptcha v3, right?

**Comment by shicholas** [comment]
yes, it was.

**Comment by ManuDoni** [comment]
> v2 captcha example (using react-recaptcha):
> checkout the sandbox: https://codesandbox.io/s/react-hook-form-get-started-forked-m6tty?file=/src/index.js
> checkout the site: https://m6tty.csb.app/
> 
> ```js
> import React from "react";
> import ReactDOM from "react-dom";
> import Recaptcha from "react-recaptcha";
> import { useForm } from "react-hook-form";
> 
> import "./styles.css";
> 
> let recaptchaInstance;
> const executeCaptcha = (e) => {
>   e.preventDefault();
>   recaptchaInstance.execute();
> };
> 
> function App() {
>   const { register, handleSubmit, errors } = useForm();
>   const onSubmit = (data) => {
>     console.log(data);
>   }; // your form submit function which will invoke after successful validation
> 
>   return (
>     <form>
>       <label>Example</label>
>       <input name="example" defaultValue="test" ref={register} />
>       <label>ExampleRequired</label>
>       <input
>         name="exampleRequired"
>         ref={register({ required: true, maxLength: 10 })}
>       />
>       {errors.exampleRequired && <p>This field is required</p>}
>       <button type="submit" onClick={executeCaptcha}>
>         Submit
>       </button>
>       <Recaptcha
>         ref={(e) => (recaptchaInstance = e)}
>         sitekey="6LdEiOEZAAAAALkNjecKwayqjmPyqcrgMW-mfNvk"
>         size="invisible"
>         verifyCallback={handleSubmit(onSubmit)}
>       />
>     </form>
>   );
> }
> 
> const rootElement = document.getElementById("root");
> ReactDOM.render(<App />, rootElement);
> ```

This example doesn't send the recaptcha response token to the server on submit

**Comment by tomliangg** [comment]
Hi @ManuDoni. It's an unfortunate `react-recaptcha` bug which I don't think it will be fixed as the repo has been inactive for quite a while now. The problem is that the lib can't succuessfully load and recognize g-recaptcha consistently (I got it once in  every ~10 refreshes). I also experienced this problem but only in local dev environment not in production build though.

I made a new react recaptcha working demo using `react-hook-recaptcha`. Can you give this a try instead: https://codesandbox.io/s/userecaptcha-example-invisible-tr32u?file=/src/App.js


```jsx
import React from "react";
import { useRecaptcha } from "react-hook-recaptcha";
import "./styles.css";

const sitekey = "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"; // change to your site key
const containerId = "test-recaptcha"; // this id can be customized

export default function InvisibleCaptcha() {
  const successCallback = (response) => {
    const inputNameValue = document.querySelector("#name").value;
    alert(`Hello ${inputNameValue} \n Recaptcha Response is: ${response}`);
  };

  const { recaptchaLoaded, recaptchaWidget } = useRecaptcha({
    containerId,
    successCallback,
    sitekey,
    size: "invisible"
  });

  const executeCaptcha = (e) => {
    e.preventDefault();
    if (recaptchaWidget !== null) {
      window.grecaptcha.reset(recaptchaWidget);
      window.grecaptcha.execute(recaptchaWidget);
    }
  };

  return (
    <form onSubmit={executeCaptcha}>
      <h3>Enter a name and hit submit</h3>
      <label htmlFor="name">name:</label>
      <input
        type="text"
        id="name"
        name="name"
        style={{ marginRight: "10px" }}
      />
      <button disabled={!recaptchaLoaded} type="submit">
        Submit
      </button>
      <p>This form is protected by Invisible Recaptcha</p>
      <div id={containerId} />
    </form>
  );
}
```

**Comment by ManuDoni** [comment]
Thanks a lot, @tomliangg.
Using your library now the captcha always works.
I ended up creating this custom hook:
```
import React from "react";
import {useForm} from "react-hook-form";
import {useRecaptcha} from "react-hook-recaptcha";

const recaptchaContainerId = 'recaptcha-container';

const useFormWithRecaptcha = ({onSubmit, ...formConfig}) => {
    const formMethods = useForm(formConfig);

    const successCallback = (response) => {
        return formMethods.handleSubmit((data) => {
            //add recaptcha field to data
            return onSubmit({...data, "g-recaptcha-response": response});
        })()
    };

    const {recaptchaLoaded, recaptchaWidget} = useRecaptcha({
        containerId: recaptchaContainerId,
        sitekey: process.env.G_RECAPTCHA_PUBLIC_KEY,
        size: "invisible",
        successCallback,
    });

    const executeRecaptcha = (e) => {
        e.preventDefault();
        if (recaptchaWidget !== null) {
            window.grecaptcha.reset(recaptchaWidget);
            window.grecaptcha.execute(recaptchaWidget);
        }
    };

    const resetRecaptcha = () => {
        if (recaptchaWidget !== null) {
            window.grecaptcha.reset(recaptchaWidget);
        }
    };

    const recaptchaComponent = <div id={recaptchaContainerId}/>;

    return {...formMethods, recaptchaLoaded, recaptchaComponent, executeRecaptcha, resetRecaptcha};
}

export default useFormWithRecaptcha;
```

**Comment by ManuDoni** [comment]
Sad update: `react-hook-recaptcha` doesn't work if you read some states inside the submit callback.
That's because `successCallback` is assigned once when the recaptcha is rendered. So if a state value updates, `successCallback` still reads the old value

**Comment by tomliangg** [comment]
> Sad update: `react-hook-recaptcha` doesn't work if you read some states inside the submit callback.
> That's because `successCallback` is assigned once when the recaptcha is rendered. So if a state value updates, `successCallback` still reads the old value

Please see: https://github.com/tomliangg/react-hook-recaptcha/issues/1

**Comment by ManuDoni** [comment]
Now it works!
Here is an updated version of my custom hook `useFormWithRecaptcha`:
https://codesandbox.io/s/react-hook-form-and-react-hook-recaptcha-inside-a-custom-hook-w0qqn?file=/src/App.js

**Comment by mikestecker** [comment]
> Now it works!
> Here is an updated version of my custom hook `useFormWithRecaptcha`:
> https://codesandbox.io/s/react-hook-form-and-react-hook-recaptcha-inside-a-custom-hook-w0qqn?file=/src/App.js

Nice hook, can you possibly update it to work with SSR? I'm getting `ReferenceError: window is not defined` errors with NextJS

**Comment by ManuDoni** [comment]
Sorry but I don't know anything about SSR, I just started working with React

Il ven 14 mag 2021, 19:33 Mike Stecker ***@***.***> ha
scritto:

**Comment by shicholas** [comment]
@mikestecker for captcha you'd need logic to ensure `window` is defined. I don't think there's a way to run this server-side.

**Comment by KJ-tasktop** [comment]
> > Now it works!
> > Here is an updated version of my custom hook `useFormWithRecaptcha`:
> > https://codesandbox.io/s/react-hook-form-and-react-hook-recaptcha-inside-a-custom-hook-w0qqn?file=/src/App.js
> 
> Nice hook, can you possibly update it to work with SSR? I'm getting `ReferenceError: window is not defined` errors with NextJS

I haven't tested this in NextJS, but I have found this to be really helpful on a Gatsby site: 

`const windowGlobal = typeof window !== 'undefined' && window`

Then it's `windowGlobal.grecaptcha.whatever...`

**Comment by fcFn** [comment]
Thanks @ManuDoni, great work! However, I must note that it will present the challenge even if the form will fail validation afterwards which might not be desirable, so you might want to validate programmatically by using `trigger` before calling `execute`.

**Comment by balex777** [comment]
> 
> 
> Thanks @ManuDoni, great work! However, I must note that it will present the challenge even if the form will fail validation afterwards which might not be desirable, so you might want to validate programmatically by using `trigger` before calling `execute`.

Can you show example how to validate programmatically by using trigger before calling execute?

**Comment by balex777** [comment]
> ```tsx
> <ReCaptcha onVerifyCaptcha={onVerifyCaptcha} />
> ```

I am using TypeScript and its got error here `{ name: 'captchaToken' }` `Type '{ name: string; }' is not assignable to type '"captchaToken"'.` What should to fix it?

**Comment by fcFn** [comment]
> > Thanks @ManuDoni, great work! However, I must note that it will present the challenge even if the form will fail validation afterwards which might not be desirable, so you might want to validate programmatically by using `trigger` before calling `execute`.
> 
> Can you show example how to validate programmatically by using trigger before calling execute?

@balex777, you can do it like that:

```JavaScript
const executeRecaptcha = async (e) => {
    e.preventDefault()
    const isValid = await formMethodsRef.current.trigger()
    if (isValid && recaptchaWidget !== null) {
      window.grecaptcha.reset(recaptchaWidget)
      window.grecaptcha.execute(recaptchaWidget)
    }
}
```

**Comment by DennisKraaijeveld** [comment]
> > > Now it works!
> > > Here is an updated version of my custom hook `useFormWithRecaptcha`:
> > > https://codesandbox.io/s/react-hook-form-and-react-hook-recaptcha-inside-a-custom-hook-w0qqn?file=/src/App.js
> > 
> > 
> > Nice hook, can you possibly update it to work with SSR? I'm getting `ReferenceError: window is not defined` errors with NextJS
> 
> I haven't tested this in NextJS, but I have found this to be really helpful on a Gatsby site:
> 
> `const windowGlobal = typeof window !== 'undefined' && window`
> 
> Then it's `windowGlobal.grecaptcha.whatever...`

Did you manage to get react-hook-form working in combination with the react-hook-recaptcha example provided in this thread? I am having SSR problems

**Comment by Notaduck** [comment]
> > > > Now it works!
> > > > Here is an updated version of my custom hook `useFormWithRecaptcha`:
> > > > https://codesandbox.io/s/react-hook-form-and-react-hook-recaptcha-inside-a-custom-hook-w0qqn?file=/src/App.js
> > > 
> > > 
> > > Nice hook, can you possibly update it to work with SSR? I'm getting `ReferenceError: window is not defined` errors with NextJS
> > 
> > 
> > I haven't tested this in NextJS, but I have found this to be really helpful on a Gatsby site:
> > `const windowGlobal = typeof window !== 'undefined' && window`
> > Then it's `windowGlobal.grecaptcha.whatever...`
> 
> Did you manage to get react-hook-form working in combination with the react-hook-recaptcha example provided in this thread? I am having SSR problems

Do you still need the solution?

**Comment by snacksncode** [comment]
> > > > > Now it works!
> > > > > Here is an updated version of my custom hook `useFormWithRecaptcha`:
> > > > > https://codesandbox.io/s/react-hook-form-and-react-hook-recaptcha-inside-a-custom-hook-w0qqn?file=/src/App.js
> > > > 
> > > > 
> > > > Nice hook, can you possibly update it to work with SSR? I'm getting `ReferenceError: window is not defined` errors with NextJS
> > > 
> > > 
> > > I haven't tested this in NextJS, but I have found this to be really helpful on a Gatsby site:
> > > `const windowGlobal = typeof window !== 'undefined' && window`
> > > Then it's `windowGlobal.grecaptcha.whatever...`
> > 
> > 
> > Did you manage to get react-hook-form working in combination with the react-hook-recaptcha example provided in this thread? I am having SSR problems
> 
> Do you still need the solution?
yes please
