### ISSUE TITLE
issue: remove doesn't work on arrayField with nested objetcs v6

### ISSUE THREAD

**Issue by MedinaGitHub** [react-hook-form/react-hook-form#10015]
### Version Number

6.15.8

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-yw7oim?file=/src/index.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-yw7oim?file=/src/index.js
2. Click on delete nested
4. See error that deleted failed and to copy another value

Error disappears when we delete 	shouldUnregister: false,  so I thinks that error is related with shouldUnregister: false

### Expected behaviour

deleted value

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Hi @MedinaGitHub , is there any chance to consider migrating to v7? V6 is almost 2 years behind, and to this point, it most likely will be touched or worked again unless a security vulnerability is discovered.

**Comment by sharanyam123** [comment]
Hi,

I am also facing the issue with react-hook-form 'remove', but not in UI but while running test cases(jest) in argo workflow using docker file.

It was working fine before but facing issue from today. I am not able to reproduce the issue in local but getting it in argo workflow.

This is the issue:
```
<AccountForm /> › removePopup
    TypeError: Cannot read property 'next' of undefined
      288 |     if(obj?.id !== -1){
      289 |       response = await removeVmImage(props.accountId, obj?.id);
    > 290 |       response?.status === 204 && remove(index)
          |                                  ^
      291 |       const message = response?.status !== 204 ? {data: response?.detail , status : "error"} : {data:`${obj?.imageName} deleted
successfully`, status : "success"}
      292 |       props.handleSaveSnackbar(message)
      293 |     }
      at Object.isValid [as next] (../../node_modules/react-hook-form/src/utils/createSubject.ts:49:5)
      at Object.options [as _updateFieldArray] (../../node_modules/react-hook-form/src/logic/createFormControl.ts:232:29)
      at remove (../../node_modules/react-hook-form/src/useFieldArray.ts:206:5)
      at deleteVmImage (components/ProjectDetails/Account/AccountDetails/AccountForm/AccountForm.tsx:290:35)
```

versions:
`next`: 12.0.7
`react`:17.0.2
`react-hook-form`:7.28.0
`jest`:27.2.3

**Comment by sharanyam123** [comment]
Hi,

I am also facing the issue with react-hook-form useForm remove and 'reset' as of now. It was working fine before but facing issue from today.

This is the issue:

for test cases:

<AccountForm /> › removePopup
    TypeError: Cannot read property 'next' of undefined
      288 |     if(obj?.id !== -1){
      289 |       response = await removeVmImage(props.accountId, obj?.id);
    > 290 |       response?.status === 204 && remove(index)
          |                                  ^
      291 |       const message = response?.status !== 204 ? {data: response?.detail , status : "error"} : {data:`${obj?.imageName} deleted
successfully`, status : "success"}
      292 |       props.handleSaveSnackbar(message)
      293 |     }
      at Object.isValid [as next] (../../node_modules/react-hook-form/src/utils/createSubject.ts:49:5)
      at Object.options [as _updateFieldArray] (../../node_modules/react-hook-form/src/logic/createFormControl.ts:232:29)
      at remove (../../node_modules/react-hook-form/src/useFieldArray.ts:206:5)
      at deleteVmImage (components/ProjectDetails/Account/AccountDetails/AccountForm/AccountForm.tsx:290:35)
for UI: when we use remove or reset

image

versions:
next: 12.0.7
react:17.0.2
react-hook-form:7.28.0
jest:27.2.3

**Comment by MedinaGitHub** [comment]
Ok, thanks for your answer and your valuable time! =)
