### ISSUE TITLE
Field from `useWatch` causes infinite hook triggers.

### ISSUE THREAD

**Issue by DarryQueen** [react-hook-form/react-hook-form#10027]
### Version Number

7.39.4

### Codesandbox/Expo snack

https://codesandbox.io/s/mystifying-matan-pcr8lu

### Steps to reproduce

As of https://github.com/react-hook-form/react-hook-form/pull/9369, object fields that are watched by `useWatch` are cloned and referentially not equal per render (see [comment](https://github.com/react-hook-form/react-hook-form/pull/9369)). At worst, this causes infinite renders, and at best this can cause incorrect hook triggers.

### Expected behaviour

Objects returned by `useWatch` are referentially equal until some part of their value is updated.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/usewatch/

> useWatch's result is optimised for the render phase instead of useEffect's deps, to detect value updates you may want to use an external custom hook for value comparison.

**Comment by DarryQueen** [comment]
ACK. I will note that this is a little bit insidious, e.g. if I pass the result of `useWatch` as props a couple layers down and use either its value or one of its dereferenced values as a dep.

This also was only an issue as of https://github.com/react-hook-form/react-hook-form/pull/9369, so a lot of code bases will have some hunting to do.

**Comment by bluebill1049** [comment]
"insidious"? I am not sure I understand that word correctly. I have included that in the doc for both `watch` and `useWatch` APIs.

**Comment by DarryQueen** [comment]
I understand the theoretical limitations of `useWatch` and `watch`, but I'm saying this is a small nuance that could be overlooked. In our case, it definitely _was_. Is it high cost to make the output of `useWatch` referentially equal? It was before https://github.com/react-hook-form/react-hook-form/pull/9369 was merged.

**Comment by bluebill1049** [comment]
Did you see that PR was made for a fix?

**Comment by DarryQueen** [comment]
Saw the PR, thank you - I will test against our code base to see if it fixes.
Did not mean to come off as aggressive or overbearing, apologies if that was the case. Wanted to highlight how it affected our code base and the cost of changing.
