### ISSUE TITLE
react hook form throwing TypeError: Cannot read properties of undefined (reading 'next') ar remove and reset of useForm

### ISSUE THREAD

**Issue by sharanyam123** [react-hook-form/react-hook-form#10021]
Hi,
I am facing the issue with react-hook-form useForm 'remove' and 'reset' as of now. It was working fine before but facing issue from today.
Its throwing `TypeError: Cannot read properties of undefined (reading 'next')`
This is the issue:

**for test cases:**

```
<AccountForm /> › removePopup
    TypeError: Cannot read property 'next' of undefined
      288 |     if(obj?.id !== -1){
      289 |       response = await removeVmImage(props.accountId, obj?.id);
    > 290 |       response?.status === 204 && remove(index)
          |                                  ^
      291 |       const message = response?.status !== 204 ? {data: response?.detail , status : "error"} : {data:`${obj?.imageName} deleted
successfully`, status : "success"}
      292 |       props.handleSaveSnackbar(message)
      293 |     }
      at Object.isValid [as next] (../../node_modules/react-hook-form/src/utils/createSubject.ts:49:5)
      at Object.options [as _updateFieldArray] (../../node_modules/react-hook-form/src/logic/createFormControl.ts:232:29)
      at remove (../../node_modules/react-hook-form/src/useFieldArray.ts:206:5)
      at deleteVmImage (components/ProjectDetails/Account/AccountDetails/AccountForm/AccountForm.tsx:290:35)
```
**for UI: when we use remove or reset**

![image](https://user-images.githubusercontent.com/114973330/221805860-e73aa9d2-b59e-4f79-b499-472335a2bad8.png)

versions:
`next`: 12.0.7
`react`:17.0.2
`react-hook-form`:7.28.0

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by bluebill1049** [comment]
any update on this issue with a reproducible codesandbox and steps to reproduce?

**Comment by bluebill1049** [comment]
I have found the root cause and will patch this today, however, please consider following the issue template. This is helping me and everyone else who are using this software.

**Comment by florian-gierlichs** [comment]
Thank you for looking into it. I still get the error with the new patch version.

In my case, the form is in a modal. In case of an error in the form, where I close the modal and the component unmounts the error appears. So I guess there is some promise unhandled

**Comment by bluebill1049** [comment]
@florian-gierlichs would be good to reproduce it in a codesandbox, and happy to look into and fix that.

**Comment by maidi29** [comment]
@bluebill1049  thanks for fixing :) Is it possible to publish the new version in npm? There is still 7.43.3

**Comment by bluebill1049** [comment]
@maidi29 published 🤘

**Comment by florian-gierlichs** [comment]
@bluebill1049 nvm 7.43.4 seem to work nice.
thank you for your work buddy!

**Comment by MarcinJarowski** [comment]
Any tips on how to fix that without upgrading a version of RHF? I need to fix that in one place and I don't want to upgrade the whole environment.
