### ISSUE TITLE
useFieldArray with uncontrolled material ui fields does not work

### ISSUE THREAD

**Issue by johnolofsson** [react-hook-form/react-hook-form#1002]
**Describe the bug**
Using the `useFieldArray` hook in combination with Material UIs inputs (when uncontrolled) does not work in all circumstances, e.g. removing items from the field array.

**To Reproduce**
1. Go to the Codesandbox
2. Click on Append
3. Input something in to the new field
4. Submit and you will see that we get two items in the field array
5. Delete the first input
6. Submit and you will see that the array is empty, expected is to have one item (the appended input)

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-bdc5k

**Expected behavior**
It should be possible to remove items from the field array and still obtain the remaining ones on submit.

**Desktop (please complete the following information):**
 - OS: macOS Catalina (10.15.3)
 - Browser Chrome
 - Version 79.0.3945.130

**Additional information**
I commented out two options in the code sandbox that works. But I expect all three of them to work.

**Comment by bluebill1049** [comment]
prefer to use Controller for external component. 

`inputRef={register()}` will fix your problem. Have a read in the doc: https://react-hook-form.com/api/#useFieldArray in terms of register
