### ISSUE TITLE
issue: useFieldArray .update does not update all references through FormProvider

### ISSUE THREAD

**Issue by Medsestrun** [react-hook-form/react-hook-form#10034]
### Version Number

7.43.3

### Codesandbox/Expo snack

https://codesandbox.io/embed/confident-tristan-fbqytv?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce

1. Go to https://codesandbox.io/embed/confident-tristan-fbqytv?fontsize=14&hidenavigation=1&theme=dark
2. Verify that initial categoryIds are '1' in defaultValues for categories array
3. Go to ChildOne.tsx and see that on mount (useEffect with empty dependencies), it updates every element of categories to have categoryId = 2
4. On the result screen you see 2211, as categories for ChildOne got updated, while categories for ChildTwo not.

### Expected behaviour

As per this proposal https://github.com/react-hook-form/react-hook-form/discussions/5832 I understand that .update should update all references, not only reference on the current page.

### What browsers are you seeing the problem on?

Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
At the current scope, we don't support multiple useFieldArray to share the same field path name. Maybe this PR is what you after: https://github.com/react-hook-form/react-hook-form/pull/7544

**Comment by Medsestrun** [comment]
Hi, sorry for late response, just finished testing that PR and it works like a charm, any plans to merge it? At least types
