### ISSUE TITLE
TestCafe Invalid destructuring assignment target

### ISSUE THREAD

**Issue by DiogoBatista** [react-hook-form/react-hook-form#1003]
**Describe the bug**
We are using TestCafe to do our e2e tests and when we do a simple test we are getting a weird error. We would like to ask for your help on what this could mean. When we compile the app both in development and in production everything works fine but as soon as we try to start testing using testcafe, it doesn't let us proceed. Any idea what this could be?

**To Reproduce**
1. Go to https://github.com/DiogoBatista/react-hook-form-test-cafe
2. Clone it and install it
3. run `yarn start` 
4) run `yarn run e2e` in a separate terminal

**Expected behavior**
It shouldn't give an error on the react-hook-form library

**Screenshots**
<img width="1437" alt="Screenshot 2020-02-10 at 16 39 53" src="https://user-images.githubusercontent.com/8352927/74164693-6aa5b600-4c24-11ea-866e-ffef81e88c59.png">

```
import React from "react";
import logo from "./logo.svg";
import { useForm } from "react-hook-form";

import "./App.css";

const App = () => {
  const { control } = useForm();
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
};

export default App;

```

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser chrome
 - Version  80.0.3987.87

**Additional context**
Not sure what could be the error but it seems that the whole import of a hook is a problem. I know that this is could be related with the use of testcafe but your help would be much appreciated 🙏 
I created a simple repo with a CRA app and a simple testcafe test to demonstrate what I'm talking about.
Thank you for you support and keep up the good work!!

**Comment by rcambrj** [comment]
Working with @DiogoBatista here.

We've discovered that this only impacts the developer mode (`yarn start`) - that is, `yarn build` and serving the site will not suffer the same problem.

**Comment by bluebill1049** [comment]
That's really strange, i am using cypress for this lib and there wasn't an issue. can you click into the chunk and see which line is broken.

**Comment by DiogoBatista** [comment]
@bluebill1049 It points to line 35170 of the chunks

<img width="1203" alt="Screenshot 2020-02-11 at 09 50 21" src="https://user-images.githubusercontent.com/8352927/74222130-03cfdd80-4cb4-11ea-896b-74cd4890bfbc.png">

```
var swapArrayAt = (fields, indexA, indexB) => isArray(fields) && ([ __get$(fields,indexA),  __get$(fields,indexB)] = [ __get$(fields,indexB),  __get$(fields,indexA)]);
```

**Comment by bluebill1049** [comment]
thanks @DiogoBatista strange one. it's valid code.

**Comment by bluebill1049** [comment]
which browser you are running your automation?

**Comment by DiogoBatista** [comment]
Browser chrome
Version 80.0.3987.87

**Comment by bluebill1049** [comment]
wow that's super strange! that's latest chrome...

**Comment by lvwrence** [comment]
fyi, i got alerted to similar error on prod on latest chrome (Chrome 80.0.3987)

```
TypeError
Invalid attempt to spread non-iterable instance
```

at this line:

```
const { register, handleSubmit, errors } = useForm()
```

Also, it seems like user was using google translate on the page, so might be related to https://github.com/react-hook-form/react-hook-form/issues/985?

will try to repro locally.

btw, thanks for the library! it's super useful.

**Comment by bluebill1049** [comment]
interesting it's a different line of code as well.

**Comment by bluebill1049** [comment]
Just a quick follow up, did you guys find a reproducible example?

**Comment by rcambrj** [comment]
I seems as though [testcafe-hammerhead](https://github.com/DevExpress/testcafe-hammerhead) mangles javascripts in such a way that this code becomes invalid.

While browsing normally:
```
var swapArrayAt = (fields, indexA, indexB) => isArray(fields) &&
    ([fields[indexA], fields[indexB]] = [fields[indexB], fields[indexA]]);
```

But when mangled by testcafe:
```
var swapArrayAt = (fields, indexA, indexB) => isArray(fields) &&
    ([ __get$(fields,indexA),  __get$(fields,indexB)] = [ __get$(fields,indexB),  __get$(fields,indexA)]);
```
where `__get$` is defined at the top of the script by `testcafe-hammerhead`. As you might imagine, `__get$(fields,indexA)` is not a valid target for destructuring into.

Apologies for raising the alarm here, there's actually [already an issue raised with testcafe-hammerhead](https://github.com/DevExpress/testcafe-hammerhead/issues/642). I'll continue my investigation and contribute to their ticket if I find anything.

Recommend closing this, unless you would be happy to apply a workaround here along the lines of:
```
var swapArrayAt = (fields, indexA, indexB) => {
    if (!isArray(fields)) { return }
    fields[indexA] = fields[indexB];
    fields[indexB] = fields[indexA];
}

```
That would unblock our e2e tests, but as admitted, is not a long term solution (it'll happen again :D)

**Comment by bluebill1049** [comment]
Thanks for the update @rcambrj . I think I will leave that stuff with testcafe. 

@lvwrence what about your issue?

**Comment by lvwrence** [comment]
@bluebill1049 haven't been able to repro but I haven't seen the error again -- i'll keep an eye out but i'm fine with closing this for now as well

**Comment by Kryshtopenko** [comment]
Have the same issue.

**Comment by kritijain2269** [comment]
Having the same issue. Tried using build version as well but it didn't work.

**Comment by bluebill1049** [comment]
@Kryshtopenko @kritijain2269 can you guys follow up on the issue at testcafe-hammerhead? hopefully this will get resolved soon for you.

**Comment by Kryshtopenko** [comment]
Workaround.

1. **Install** **next** **dependencies** to your **project**:
`npm i -D @babel/core @babel/plugin-transform-runtime @babel/preset-env`

2. **Add**
`      {
        test: /\.(js)$/,
        exclude: [/node_modules\/(?!(react-hook-form)\/).*/],
        use: [
          {
            loader: "babel-loader"
          }
        ]
      },`
as **rule** to your **webpack.common.ts**.

3. **Create** _babel.config.json_
`{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": "commonjs"
      }
    ]
  ],
  "plugins": [
    [
      "@babel/plugin-transform-runtime"
    ]
  ]
}`

Enjoy.

**Comment by bluebill1049** [comment]
oh wow @Kryshtopenko! thank you for sharing the solution.
