### ISSUE TITLE
issue: setErrors are not persisted when using resolver

### ISSUE THREAD

**Issue by sebammon** [react-hook-form/react-hook-form#10042]
### Version Number

7.42.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-seterror-with-resolver-gs4nmp

### Steps to reproduce

1. Click on the "set custom error" button. A custom error message will be displayed.
2. When you click on submit, the custom error message is removed and the "firstName is required" error message is displayed.
3. If you enter some value in the firstName field and then click on submit, the form is accepted as valid, effectively ignoring the custom error.

### Expected behaviour

The expected behavior would be that using `setError(...)` to set an error on an unregistered input behaves the same when using a resolver. The [docs](https://react-hook-form.com/api/useform/seterror/) state:

> An error that is not associated with an input field will be persisted until cleared with clearErrors.

My expectation would be that custom errors (not registered to an input) also persist until the `clearErrors(...)` function is invoked. I would also expect that it stops the form from being submitted.

### What browsers are you seeing the problem on?

Chrome, Firefox, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> You can set a server or global error with root as the key. This type of error will not persist with each submission.

not with a global type of error, it was designed to solve server errors and other manual errors.

**Comment by sebammon** [comment]
I see that the codesandbox I initially shared used the `root` key which wasn't my intention. I've created two new codesandboxes below to illustrate what I mean.

I agree with what you're saying, that if you use `setError` with the `root` key, the error "will not persist with each submission". However if you use `setError('notRegisteredInput', { type: 'custom', message: 'custom message' });` then the error will persist until `clearErrors()` is invoked manually. It also doesn't allow the form to be submitted until the `notRegisteredInput` error has been cleared. This is also how it works in [this codesandbox](https://codesandbox.io/s/react-hook-form-v7-seterror-forked-mr55yh?file=/src/index.jsx).

What I've found is that the behavior described above does not hold when you use the `resolver` property of the `useForm` hook to validate a schema (with yup for example). I find that a bit strange. My expectation is that it would behave exactly the same, the only difference is that instead of specifying the validation on `register` function directly, it is defined in the schema of the `resolver`. Have a look at [this codesandbox](https://codesandbox.io/s/react-hook-form-validationschema-v7-forked-ov0ekj?file=/src/index.js). In this codesandbox you will see that the `customError` is not persisted until `clearErrors()` is called. The custom error gets removed whenever you click on the `submit` button.

**Comment by bluebill1049** [comment]
I have investigated this for schema, we will have to rely on what is returned by the schema. Eg if I aborted early for any existing custom error, this will lead to other form-related errors that will not be shown. I will address this in the document for clarification.
