### ISSUE TITLE
issue: Validation rules ignored under certain conditions (after being mounted and then unmounted it seems)

### ISSUE THREAD

**Issue by elieven** [react-hook-form/react-hook-form#10043]
### Version Number

7.43.3

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-validation-problems-when-unmounted-7fjwz0?file=%2Fsrc%2FApp.tsx

### Steps to reproduce

1. Go to codesandbox link
2. Open console
3. Click on submit
4. Notice there are errors
5. Click on tab 3
6. Click on submit
7. Notice that once again there are still errors
8. Click to any other tab
9. Click on submit
10. Validation is ignored and the form submits

### Expected behaviour

Expect the errors to still be there since the value of the input has not changed and the validation rules should be preventing the form from being submit just like they do when the input is initially not rendered and when it is rendered. Only on this unmount it seems to be ignored.

### What browsers are you seeing the problem on?

Firefox, Chrome, Edge

### Relevant log output

```shell
{}
{}
{cats: Object}
{cats: Object}
{cats: Object}
{cats: Object}
{cats: Object}
{cats: Object}
{name: "Jonathan", city: "London", cats: 0}
{}
{}
{}
{}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elieven** [comment]
I just noticed now with some more playing around but if after that erroneous successful submit that should not happen you click on submit again the validation seems to work again.

So to put it more clearly:
1. Go to codesandbox
2. Open console
3. Click on submit
4. Notice errors
5. Click on tab 3
6. Click on submit
7. Notice that there are still errors
8. Click on any other tab
9. Click submit
10. Notice that the form submits even though there have been no changes to data
11. Click on submit again
12. The errors appear again

**Comment by bluebill1049** [comment]
unmounted input will not be validated. We can consider to introduce a prop to config that, but the its by design that unmounted's validation will be skipped as it's not visible to the users.

**Comment by elieven** [comment]
Hmm. It does seem to validate even when unmounted until you mount it and unmount it again. And then it does not validate only that first time you submit and then it goes back to validating unmounted inputs. Or is it validating default values or something? Even then the behavior does not make sense to me.

**Comment by bluebill1049** [comment]
Related to this? https://react-hook-form.com/faqs/#Whyisdefaultvaluenotchangingcorrectlywithternaryoperator

**Comment by elieven** [comment]
I don't think so. I mean it really is very strange behavior. In another [codesandbox example](https://codesandbox.io/s/react-hook-form-validation-problems-when-unmounted-no-default-data-dvf810?file=%2Fsrc%2FApp.tsx) i removed default data for the field that should error and the behavior is the same.

So to update the steps:
1. Go to codesandbox link
2. Click on tab 3
3. Insert number lower than 1
4. Click on submit
5. Notice there is an error in console
6. Click on another tab
7. Notice that the form submits (no validation on unmounted inputs)
8. Click submit again
9. Notice that there is an error now (there is validation on unmounted input?)

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/222841707-c41e2dee-2928-4695-be73-c2f33f7dd11f.mov

can you share a video? if this persists use resolver which validate at the form level.

**Comment by bluebill1049** [comment]
I found out the issue... The Tab component actually re-renders and remounts all the tabs. :( which confused hook form, but yea try to use resolver, I think that's more suitable for your use case and components.

**Comment by bluebill1049** [comment]
![Screenshot 2023-03-04 at 9 25 31 am](https://user-images.githubusercontent.com/10513364/222842375-892baedf-8b8e-4d1f-932b-fc21349105e0.png)

**Comment by elieven** [comment]
Ah thanks, will look into it. Would love the ability to validate unmounted inputs as well since I think it is very needed and I also don't know why it is intended behavior not to validate them? Are those inputs not part of the form or is there some form creation / usage pattern I'm not aware of that wants this kind of behavior?

**Comment by bluebill1049** [comment]
react hook form tries to keep track of unmounted inputs, it's easier with build validators because it's field level. Schema validation will always validate the form level by default. I am not sure if it's possible for you to try another tab library to see if this can be resovled as well.

**Comment by elieven** [comment]
I'm unlikely to try something else under the time constrains as well as just how good this library is. As for making a PR I'm certain I'm not knowledgeable enough in programing in general or form libraries and even less in this one specifically to make an adequate feature like this so for now I'll have to rely on the kindness of others. Thanks a lot for all the help thus far and the work that went into this library that many of us use :)

**Comment by bluebill1049** [comment]
no worries, I will create a feature request for this and put into the project board for the future.
