### ISSUE TITLE
Controller doesn't re-render and sets field value to 'undefined'

### ISSUE THREAD

**Issue by N00mBus2000** [react-hook-form/react-hook-form#10048]
### Version Number

8.0.0-alpha.4

### Codesandbox/Expo snack

https://codesandbox.io/s/upbeat-bhabha-w7s1lf

### Steps to reproduce

1. select any checkbox
2. click on submit button
3. see:
`0: Object
params: Object
1: Object
apply: undefined`

Running on version 7.43.4, the value is set, but the type is represented as an array:
`0: Object
params: Array(2)
0: undefined
1: Object
apply: true`

### Expected behaviour

v8: value is set correctly;
or
v7: data type is represented correctly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/usecontroller/

> Important: Can not apply undefined to defaultValue or defaultValues at useForm.

> You need to either set defaultValue at the field-level or useForm's defaultValues. undefined is not a valid value.

> If your form will invoke reset with default values, you will need to provide useForm with defaultValues.
