### ISSUE TITLE
Using Conditional Components modifies nested fields of form values

### ISSUE THREAD

**Issue by MikeInCode** [react-hook-form/react-hook-form#1004]
**Describe the bug**
On input component unmount, form's nested fields modifies (removing keys with empty array)

**To Reproduce**
1. Click Submit btn and look up on object under the key "testing" (it has 2 empty arrays nested)
2. Type "bill" in first input field
3. Click Submit again
4. After disappearing second input, "testing" object lost all keys where were empty arrays before (in other word, it removes these keys)

**Codesandbox link**
https://codesandbox.io/s/react-hook-fom-unregister-controlled-component-4zfr8

**Expected behavior**
Nested object with key "testing" shouldn't changed

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/34603913/74180818-cc781700-4c48-11ea-9e9f-f0d8d5421f7e.png)
After (key3, key5 lost):
![image](https://user-images.githubusercontent.com/34603913/74180840-d863d900-4c48-11ea-8efc-58a4f431020c.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 79.0.3945.130

**Comment by bluebill1049** [comment]
u mean test object field is removed?

**Comment by MikeInCode** [comment]
> u mean test object field is removed?

no, test object removed and it's expected behavior. I mean object "testing" which were registered manually, lost key3 and key5 when second input ("test") onmounts

**Comment by bluebill1049** [comment]
oh, I see, but where are all the nested inputs? RHF probably stripe out those empty values inside (include []). I am happy to take a deep look into this, but let's have a proper nested fields form.

**Comment by MikeInCode** [comment]
Oh, I understand what you mean. In this case I'm using field value "testing" without inputs. Can we use such approach in RHF (value in RHF state without input field). In my case it useful to iterate over this object and render markup, by the way it can be modified via setValue from another components

**Comment by bluebill1049** [comment]
> These approach worked well in Formik, I can store in Formik state whatever I want, state for my text, object for futher render etc. Maybe problem what I'm tries to implement it in RHF

FYI: two libs using a completely different approach. have a read here:https://react-hook-form.com/faqs#ReactHookFormFormikorReduxForm

Sounds valid above :) I will take a look at the code base see if we can allow an empty array. can you update your CSB to include empty `string` and `object`. If i have a fix, i can test it out there.

**Comment by MikeInCode** [comment]
Already update. Add next cases: `null`, ` ""`,` undefined`, `{}`

**Comment by bluebill1049** [comment]
some more context for you to understand the reason. RHF embraces native input and tries to be aligned with native form behavior. 

For one moment, let's forget about React and the local state. if you are building a native form without any lib or framework, and try to achieve what you want above. You will have to use `<input type="hidden" />` for those extra fields which are not part of the form, and that's where RHF is coming from, data live inside the inputs and embrace native form behavior.

**Comment by MikeInCode** [comment]
I have same flow, maybe u can help me, and adviuse better approach using RHF.
I have form, with some fields, and link. (all this right now part of RHF)
When I click on link I see drawer with builtin standalone form with own validation (it used not only in this case)
Fillind drawer's form, and clicking submit a pass all values via setValue to main form (that's why I have object without inputs) 
That's my case)

**Comment by bluebill1049** [comment]
Let me take a look, see if we can support your case above :)

**Comment by MikeInCode** [comment]
> Let me take a look, see if we can support your case above :)

You want to see sandbox example?

**Comment by bluebill1049** [comment]
> > Let me take a look, see if we can support your case above :)
> 
> You want to see sandbox example?

I can work on the one u posted with the issue.

**Comment by MikeInCode** [comment]
Okay waiting...)

**Comment by bluebill1049** [comment]
hey @MikeInCode here is the improved version: https://codesandbox.io/s/react-hook-fom-unregister-controlled-component-7p84l

**Comment by MikeInCode** [comment]
> hey @MikeInCode here is the improved version: https://codesandbox.io/s/react-hook-fom-unregister-controlled-component-7p84l

Thank u!

**Comment by bluebill1049** [comment]
no worries :) we will release this in the next patch.
