### ISSUE TITLE
Issue: useFormState errors using fieldArray index doesn't return the selected index

### ISSUE THREAD

**Issue by viniarruda** [react-hook-form/react-hook-form#10065]
### Version Number

7.39.3

### Codesandbox/Expo snack

https://codesandbox.io/s/kind-stitch-bd8ru5

### Steps to reproduce

1. Click to submit button
2. Look to console

### Expected behaviour

When use `fieldArray.${index}` in `useFormState` name the idea is to return only errors that have in specific object in fieldArray index, but is returning all the errors.

Expected:

```jsx
const { errors } = useFormState({
  control,
  name: `fieldArray.${index}`
});

------
errors data:


errors: {
 name: {
  message: "required field"
  type: "required"
  ref: undefined
 }
}
```

Current:

```jsx
errors: {
 fieldArray: [{
   name: {
    message: "required field"
    type: "required"
    ref: undefined
   }
 }]
}

 ```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we don't change the returned shape of the errors object but only subscribe to the field name error state.

**Comment by viniarruda** [comment]
> we don't change the returned shape of the errors object but only subscribe to the field name error state.

I'm using the errors that return from useFormContext, but in a component that don't need all the errors, probably the better way is getting the errors for specific index passing the name in formState. What do you think?

**Comment by bluebill1049** [comment]
Not within the current scope @viniarruda it adds extra complexity for the type check.
