### ISSUE TITLE
Scrollable views with sticky footers - scroll errors into view

### ISSUE THREAD

**Issue by KATT** [react-hook-form/react-hook-form#10063]
Hey!

I have a scrollable view with a sticky footer, this means that when the input fails validation, the input that is focused can sometimes be covered by the footer.

How can I work around this? 😬 Is this something that should be part of RHF to handle or is it seen as out of scope?

[`Element.scrollIntoView()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) does work with this (if we use `block: 'center'`), but I think RHF only triggers `.focus()` which doesn't.

Suggestion: use `Element.scrollIntoView` when a validation fails

**Comment by Moshyfawn** [comment]
Hey, Alex!

Would solving it with [CSS `scroll-margin-top`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-top) suffice?

There're a few similar feature requests and we have #9944 on [the feature board](https://github.com/react-hook-form/react-hook-form/projects/1) which tells us that there's a demand to solve form input focus.

Our current API design doesn't necessarily allow us to solve it elegantly and [Element.scrollIntoView()](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) [options](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView#sect1) lack Safari support.

Definitely a valid feature request. Let's see of @bluebill1049 has other thoughts on the topic.

**Comment by bluebill1049** [comment]
I'd like to know what we can consider in the future, currently, you will have to use the ref from the errors object. 

proposed API would be `setFocus('name', { shouldScrollIntoView: boolean })`

**Comment by KATT** [comment]
The problem is that I don't know how to trigger scroll into view on validation errors - seems like RHF does something but I dont know of any `onError`-like callback

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/useform/handlesubmit/

> SubmitErrorHandler	(errors: Object, e?: Event) => Promise<void>	An error callback.

Currently, you can do it at the summit failure. Use the `errors` object.

**Comment by KATT** [comment]
What I want is to be able to get the first field that errors (in the order that they are registered if possible?), and `.scrollIntoView()` on that, but the above logic isn't sufficient as it has nested objects.

Is there a way to flatten the `FieldErrorsImpl`? I have nested objects (and a generic `<Form>`-helper thankfully so I can do this _once_).

I'd like something that that does

```ts
function flattenErrors<T extends Partial<FieldErrorsImpl<DeepRequired<T>>>>(obj: T) {
  const acc: Record<string, FieldError> = {};

  // [... unsure how to do this check]

  return acc;
}
```

**Comment by KATT** [comment]
This is where I got to right now?

```ts
function onError(errors) {
type RecursiveError =
  | {
      [key: string]: RecursiveError | undefined;
    }
  | FieldError
  | Array<FieldError | RecursiveError>;

function isFieldError(err: RecursiveError): err is FieldError {
  return (
    isObject(err) &&
    typeof err.type === 'string' &&
    'ref' in err
  );
}
function findFirstRef(err: RecursiveError): Ref | undefined {
  if (isFieldError(err)) {
    return err.ref;
  }
  for (const value of Object.values(err)) {
    if (value) {
      const ref = findFirstRef(value);
      if (ref) {
        return ref;
      }
    }
  }
  return undefined;
}
const firstRef = findFirstRef(errors as RecursiveError) as
  | HTMLInputElement
  | undefined;
````


I feel like this is something you do internally though, so feel like there's a nicer solution

**Comment by KATT** [comment]
Another way that would solve this more elegantly would be if we could override how the focus-API works in RHF, so if you have like an optional callback where you call `focus()`, you could call `opts?.focus?.(ref) ?? ref?.focus?.()`

**Comment by KATT** [comment]
Might just solve this by instead of doing another layout which doesn't do sticky... could do a flex container with a footer that is pushed to the bottom instead...

**Comment by bluebill1049** [comment]
Honestly, I wouldn't go with the code example you got above. 

> What I want is to be able to get the first field that errors (in the order that they are registered if possible?), and .scrollIntoView() on that, but the above logic isn't sufficient as it has nested objects.

Yea, I see your point due to nested, let's park this one for a bit, I think it's probably better for us to handle it with `setFocus` instead of those custom logic and make dev life a bit easier. I will move the feature request to the project board and move to pending. Once `Form` component is out of the way, I will start working on other features and possibly this one as well.

**Comment by bluebill1049** [comment]
You can track it in our feature board: https://github.com/react-hook-form/react-hook-form/projects/1#card-88409770
