### ISSUE TITLE
feat: useWatch with selector

### ISSUE THREAD

**Issue by davbrito** [react-hook-form/react-hook-form#10076]
**Is your feature request related to a problem? Please describe.**
Sometimes we want to watch a derived state from the form values. The most straightforward for doing that right now is to watch all the pieces and calculating the derived data on the render.

This has one big problem though. Lets say we have a field array and we want to watch for the sum of a property in particular, doing it that way would be something like:
```tsx
const products = watch("products")
const totalPrice = products.reduce((total, prod) => total + prod.price, 0)
```

This makes the component rerender on every change on one of the items of the array, even if the sum ends equal than the previous.

 

**Describe the solution you'd like**
A hook that allows to pass a selector for the form values so the component rerenders only on a change on the derived values.
This would allow some more complex patterns such as using reselect for advanced use cases.

For instance:
```tsx
const value = useWatch({
  control,
  select: formValues => /* get selected value */,
})
```

**Describe alternatives you've considered**
Currently you can use watch and an `useState+useEffect` or `useSyncExternalStore` for achieving that, but doing that on userland is somewhat complex.

I made myself a simple implementation which can serve to you as a base for making this feature.
Note that I used the `watch` function directly because I don't know the internals of the `control` and how could be implemented with it.
```tsx
import { useCallback, useRef } from "react";
import type {
  DeepPartial,
  FieldValues,
  UseFormGetValues,
  UseFormWatch,
} from "react-hook-form";
import { useFormContext } from "react-hook-form";
import { useSyncExternalStoreWithSelector } from "use-sync-external-store/shim/with-selector";

type Args<TFieldValues extends FieldValues, TData> =
  | [
      watch: UseFormWatch<TFieldValues>,
      getValues: UseFormGetValues<TFieldValues>,
      selector: (values: DeepPartial<TFieldValues>) => TData
    ]
  | [selector: (values: DeepPartial<TFieldValues>) => TData];

export default function useWatchSelector<
  TFieldValues extends FieldValues,
  TData
>(...args: Args<TFieldValues, TData>): TData {
  const context = useFormContext<TFieldValues>();

  const onlySelector = args.length === 1 || args[1] === undefined;

  const { watch, getValues } = onlySelector
    ? context
    : {
        watch: args[0],
        getValues: args[1],
      };

  const selector = (onlySelector ? args[0] : args[2]) as (
    values: DeepPartial<TFieldValues>
  ) => TData;

  const snapshot = useRef<DeepPartial<TFieldValues> | undefined>(undefined);

  return useSyncExternalStoreWithSelector(
    useCallback(
      (cb) => {
        const subscription = watch((values) => {
          snapshot.current = values;
          cb();
        });

        return () => {
          subscription.unsubscribe();
        };
      },
      [watch]
    ),
    useCallback(() => {
      if (snapshot.current === undefined) {
        return getValues() as DeepPartial<TFieldValues>;
      }
      return snapshot.current;
    }, [getValues]),
    null,
    selector
  );
}
```

Using that solution the example presented above could ve implemented like:
```tsx
const totalPrice = useWatchSelector(({products}) => products.reduce((total, prod) => total + prod.price, 0))
```
And it would only rerender if the totalPrices changes

**Comment by bluebill1049** [comment]
Take a look at this discussion: https://github.com/react-hook-form/react-hook-form/discussions/9957 I think it solve similar problem.

**Comment by davbrito** [comment]
> Take a look at this discussion: #9957 I think it solve similar problem. If its similar, I will mark this as duplicated and focus on the other one.

While it may look similar at first glance, it solves a different use case. There he wants to passively run a callback on changes and avoid completely any rerenders.
Whereas what I propose is a way to control what makes the component rerender by providing a selector.
