### ISSUE TITLE
Context in yup resolver is passed to yup schema but when submitHandler is called, the errors are not correctly passed to formState.

### ISSUE THREAD

**Issue by danielweil** [react-hook-form/react-hook-form#10074]
### Version Number

7.35.0

### Codesandbox/Expo snack

Will be providing one.

### Steps to reproduce

1. Create schema with nested inputs using when condition from yup
2. Try to access parent property inside when parameter
3. Value will be undefined.
4. Tries to use context in isValidSync, passing parent value.
5. Schema now receives values
6. handleSubmit is called, values go back to undefined and validation doesn't work

### Expected behaviour

1. Create schema with nested inputs using when condition from yup
2. Try to access parent property inside when parameter
3. Value will be undefined.
4. Tries to use context in isValidSync, passing parent value.
5. Schema now receives values
6. handleSubmit is called, values from context are still valid and validation works

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge
Thank you for the fast support. Love the project and use it a lot.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

Sorry for not presenting a codesandbox, but I think you already know what this is about:

https://github.com/react-hook-form/react-hook-form/issues/2222
https://github.com/react-hook-form/react-hook-form/discussions/9084

I am aware that passing context via useForm works, but what I am trying to do is access parent properties from schema inside nested when conditions, and I don't have these values when I call useForm, as they are inside the form state. Is there any better way to achieve this? It doesn't seem right the schema receive the context values correctly but validate function fails. Wasted a whole day trying to figure out the problem,

**Comment by danielweil** [comment]
Is there any way for submitHandler to use the context passed to yup or access state from inside the form itself?

**Comment by danielweil** [comment]
What I was thinking was maybe an option that allows formValues to be passed as a whole or partially as resolver's context.

![image](https://user-images.githubusercontent.com/44274213/224069119-717d1141-2a7b-4360-b2c4-dcd8e40f48ff.png)

That would help anyone using yup and nested validations.

**Comment by danielweil** [comment]
I never created pull requests to big projects like this. Do you think the feature is valid? How should I proceed?

**Comment by danielweil** [comment]
This was enought to make it work:

![image](https://user-images.githubusercontent.com/44274213/224108224-86329a44-52a1-49ca-8570-c7574c62ee7c.png)

![image](https://user-images.githubusercontent.com/44274213/224108411-f320422c-9a48-4e79-8ba8-e81ec26b630e.png)

**Comment by bluebill1049** [comment]
> I never created pull requests to big projects like this. Do you think the feature is valid? How should I proceed?

we are always welcome for PRs. What API are you proposing? 

> What I was thinking was maybe an option that allows formValues to be passed as a whole or partially as resolver's context.

`formValues` is already passed to the resolver.

**Comment by bluebill1049** [comment]
I think you can build a custom resolve to solve your problem, should be an easy one to get around. Probably not going to change the context at this stage, this would bring a breaking change unless we jump to a major version.

**Comment by danielweil** [comment]
Can you sugest how should I do that?

**Comment by danielweil** [comment]
Thank you for your help Bill. The custom resolver worked out!

**Comment by bluebill1049** [comment]
Awesome to hear!
