### ISSUE TITLE
isDirty is not sync in useController and useFormContext

### ISSUE THREAD

**Issue by xkomiks** [react-hook-form/react-hook-form#10073]
### Version Number

7.43.5

### Codesandbox/Expo snack

https://stackblitz.com/edit/react-ts-cp4xtf?file=App.tsx

### Steps to reproduce

1. Go to https://stackblitz.com/edit/react-ts-cp4xtf?file=App.tsx
2. Click on some checkbox
3. See at state logs in console and fact that it is not sync with each other

### Expected behaviour

I expect the state in all hooks to be synchronized

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Please double-check your example, it's not working on my end.
![Screenshot 2023-03-10 at 8 42 30 am](https://user-images.githubusercontent.com/10513364/224166744-c6329bbd-7d53-4b84-87b9-24d91e5c6b2b.png)

**Comment by zhulduz** [comment]
<img width="1213" alt="Screenshot 2023-03-10 at 06 43 37" src="https://user-images.githubusercontent.com/1921276/224218002-2e781a07-dfa3-47cc-bcd1-2db55dd357ad.png">

It is working on my side, but `isDirty` doesn't change in `useFormContext`.
I got the same problem with `usForm` hook. I use 7.43.3 version.

**Comment by bluebill1049** [comment]
![Screenshot 2023-03-10 at 2 57 30 pm](https://user-images.githubusercontent.com/10513364/224219770-6dd2f274-4353-4796-b339-4e7afaefbe79.png)

still empty for me.

**Comment by xkomiks** [comment]
@bluebill1049 check here

https://codesandbox.io/s/inspiring-bird-5lc43h?file=/src/App.js

**Comment by bluebill1049** [comment]
This issue is due to react strict mode which causes by `useEffect` to run twice, I will look for a solution, but here is the reason behind such behavior.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/useform/formstate/

> Make sure to provide all inputs' defaultValues at the useForm, so hook form can have a single source of truth to compare whether the form is dirty.

**Comment by xkomiks** [comment]
@bluebill1049 hmm, when i pass `defaultValues: { inputs: [] }` this started working correctly, it's not very obvious

**Comment by xkomiks** [comment]
Do you think this is normal behavior?

**Comment by bluebill1049** [comment]
Please refer to the doc as what i have pointed above.

**Comment by xkomiks** [comment]
Was it always like this?

**Comment by bluebill1049** [comment]
yes.
