### ISSUE TITLE
[React-Native] Auto validation problem on submit

### ISSUE THREAD

**Issue by enestasdemir** [react-hook-form/react-hook-form#1007]
**Describe the question?**
When I press the submit button with invalid fields (when the 'firstName' field is empty), it doesn't show the error field on screen and console says : `Possible Unhandled Promise Rejection (id: 0):
ReferenceError: Node is not defined
ReferenceError: Node is not defined
[...]`

What's wrong with my code? Can you help me about that?

**Screenshots**

<img width="608" alt="Screen Shot 2020-02-11 at 11 28 57" src="https://user-images.githubusercontent.com/36698348/74221057-426c9480-4cc2-11ea-9f24-1af3bbe17ae4.png">
<img width="528" alt="Screen Shot 2020-02-11 at 11 30 07" src="https://user-images.githubusercontent.com/36698348/74221062-45678500-4cc2-11ea-8e62-881a1c7d937f.png">

**Versions**
`
"react": "16.9.0",
"react-hook-form": "4.9.2",
"react-native": "0.61.5"
`

**Comment by bluebill1049** [comment]
can you try the following:

```
() => {
  handleSubmit(onSubmit)()
}
```

**Comment by bluebill1049** [comment]
it could be a bug which we introduced lately with isHTMLElement

FYI: @kotarella1110

**Comment by enestasdemir** [comment]
> can you try the following:
> 
> ```
> () => {
>   handleSubmit(onSubmit)()
> }
> ```

Thank you for your quick reply bu it's still not working.

**Comment by bluebill1049** [comment]
can you do a test on this beta version: react-hook-form@4.9.3-beta.1

**Comment by enestasdemir** [comment]
> can you do a test on this beta version: react-hook-form@4.9.3-beta.1

Still same :(

**Comment by bluebill1049** [comment]
still the same error?

**Comment by enestasdemir** [comment]
> still the same error?

Yes, still same error.

`
Possible Unhandled Promise Rejection (id: 0):
ReferenceError: Node is not defined
ReferenceError: Node is not defined ...
`

**Comment by bluebill1049** [comment]
https://snack.expo.io/@bluebill1049/react-hook-form-input 

looks like the beta is working for me. can you double check?

**Comment by bluebill1049** [comment]
hmmm i could be expo has a wrapper

**Comment by bluebill1049** [comment]
can you help test out this version: react-hook-form@4.9.3-beta.2

added type check.

```
import isObject from './isObject';
import { UNDEFINED } from '../constants';

export default (value: any): value is HTMLElement =>
  typeof Node !== UNDEFINED &&
  isObject(value) &&
  (value as any).nodeType === Node.ELEMENT_NODE;
```

**Comment by bluebill1049** [comment]
can someone verify 
`4.9.3-beta.2`
`4.9.3-beta.3`

I have tested on my android device both working.

**Comment by NicoleEtLui** [comment]
I had the same error than @enestasdemir, but its gone with `react-hook-form@4.9.3-beta.2` !

**Comment by bluebill1049** [comment]
hey @NicoleEtLui can you test out beta.3?

**Comment by NicoleEtLui** [comment]
Both `beta.2` and `beta.3` seems to work like a charm (ios and android simulators). 

* `react@16.12.0`
* `react-native@0.61.5` 

Thank you very much for the quick fix

**Comment by bluebill1049** [comment]
thank you very much for the verification. I will release the patch. @NicoleEtLui much apprecaited.

**Comment by enestasdemir** [comment]
It worked for me. Thank you so much 😊

**Comment by maxkalash** [comment]
The issue is still when I trying to do from.reset()
But adding isWeb to the condition resolved
`if (value && isWeb && HTMLElement(value.ref) && value.ref.closest) {`

"react": "^16.12.0",
"react-hook-form": "^4.9.3",
"react-native": "0.61.5",

**Comment by bluebill1049** [comment]
thanks @maxkalash

**Comment by bluebill1049** [comment]
by the way, next time please send a PR as you find the solution and should get you in the contributing list :)

**Comment by bluebill1049** [comment]
@maxkalash can you please take this beta: react-hook-form@4.9.4-beta.3

**Comment by maxkalash** [comment]
It worked for me! Thank very mach for the quick fix !
