### ISSUE TITLE
trigger with temporary values

### ISSUE THREAD

**Issue by Vishal1419** [react-hook-form/react-hook-form#10070]
**Is your feature request related to a problem? Please describe.**
I am assuming to use validation schema instead of inline validation.
Sometimes, you need fields on the form that does not want to interect directly with the form.

e.g.

Lets say you have a field named title in your form.

You are just displaying value of title in a paragraph like `<p>{title}</p>`, where title comes from watch like `const title = watch(title)`.

Also, assume that you have an edit button next to your title paragraph like:
```
const title = watch('title');
<p>{title}</p>
<button type="button" onClick={openDialog}>Edit</button>
```

On click of the button, you open a dialog which looks like:
```
<Dialog>
    <input name="title" .... />
    <button type="button" onClick={handleUpdateTitle}>Update</button>
    <button type="button" onClick={closeDialog}>Cancel</button>
</Dialog>
```

When you update the title from the dialog, it should change the value of title in form.
But in case if you click Cancel, no values should change in form.

We can use `useState` to maintain the value and onChange of title field inside dialog and everything should work just fine.

But if you want to validate title against the validation schema of form, even before you update the title in the form, then you cannot do that.

The scenario is:
 - I want to update title in the form on click of update button in dialog.
 - But before updating title in the form, I want to validate it against form's validation schema.

So, my `handleUpdate` method should look something like:
```
const [value, setValue] = useState('');

const handleChange = (event) => {
  setValue(event.target.value);
}

const handleUpdate = () => {
  // trigger will always return false because title is not yet updated in the form. I could have used setValue before calling trigger, but my intention is to just change the form value only when title is valid.
  const isValid = trigger('title'); 
  if (!isValid) return;
  setValue('title', value);
  closeDialog();
}

const handleCancel = () => {
  // TODO: clear validation errors before closing
  closeDialog();
}
```

**Describe the solution you'd like**
I think, the above problem can be solved if trigger function accepts an object with the shape like:
```
trigger({ name: Path<T>, valueToTestAgainst: PathValue<T, Path<T>> })
```

**Describe alternatives you've considered**
I do not have any alternative solution in my mind. But whatever I suggest is based on a real use case in my project.

**Additional context**
<img width="519" alt="image" src="https://user-images.githubusercontent.com/19953475/223954399-ad4aa1d3-c544-42a8-acd9-ff06517e7d81.png">

<img width="481" alt="image" src="https://user-images.githubusercontent.com/19953475/223954030-ca39ccde-0a81-47fc-a785-f68bf93a85f8.png">

**Comment by bluebill1049** [comment]
moving to feature board for upvotes
