### ISSUE TITLE
formState.isSubmitted false in validationResolver during the first submit

### ISSUE THREAD

**Issue by durchanek** [react-hook-form/react-hook-form#1008]
**Describe the bug**
Not 100% sure if this is a bug or not, but my understanding was that once submitted, `formState.isSubmitted` is instantly set to true. However when used in validationResolver, it is still false during the first submit.

**To Reproduce**
1. Open the sandbox link
2. Switch to the console tab
3. Submit the form twice.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-issubmitted-bug-6fvqi

**Expected behavior**
`formState.isSubmitted` is true during the first submit.

**Comment by durchanek** [comment]
Also apply to `formState.submitCount`, which is 0 in validationResolver during the first submit.

**Comment by durchanek** [comment]
Actually, I have just found out that both properties reset when there is a change in the form. Again, not sure if this is a bug or not, the documentation does not specify this, but fields a bit unexpected, especially for `submitCount`.

**Comment by bluebill1049** [comment]
your form is stuck at the schema validation because values are not returned.

https://codesandbox.io/s/react-hook-form-issubmitted-bug-6fvqi

**Comment by durchanek** [comment]
Not sure if I understand this right but if I change the returned values to the default values specified in docs,
```
return {
  values: {},
  errors: {},
};
```
the behaviour doesn't change. Moreover, even if the form is "stuck", this shouldn't apply to the first execution of the validationResolver? In short, is it correct that `formState.isSubmitted` is false during the first submit?

**Comment by bluebill1049** [comment]
can you take a look this example: https://codesandbox.io/s/react-hook-form-issubmitted-bug-c55y0

`formState.isSubmitted` start with `false` and set to `true` after `submit`

**Comment by durchanek** [comment]
That is correct, but when `formState.isSubmitted` is accessed from validationResolver, it is still `false` after the first submit and changes to `true` only after the second submit:

https://codesandbox.io/s/react-hook-form-issubmitted-bug-w3qsx

My expectation was it is set to true after submitting the form and before the validation.

**Comment by bluebill1049** [comment]
the current version doesn't support read formState inside the resolver, what's your usage inside the resolver instead of reading `formState` in the render.

**Comment by durchanek** [comment]
I have a form that combines regular uncontrolled form fields with Stripe form fields and use 
`formState` in validationResolver to mimic onSubmit validation behaviour of react-hook-forms for the Stripe fields. It should be possible to do this in render, just wasn't aware that `formState` is not supported inside the resolver as it seems like almost working :-)

**Comment by bluebill1049** [comment]
you can make it work by using `useRef`, similar as hoist a variable outside the component. i think working inside the render is probably better 👍

**Comment by durchanek** [comment]
I agree, this logic probably shouldn't go to the resolver. Thank you!
