### ISSUE TITLE
Get the input current value as the user types with Controller

### ISSUE THREAD

**Issue by fjuriolli** [react-hook-form/react-hook-form#1009]
I have a material UI TextField wrapped with a Controller.

I need to display the current input value as the user types, I tried with refs but I can't manage to get this working.

Am I doing something wrong?

Codesandbox: https://codesandbox.io/s/react-hook-form-rhfinput-3n3bi

**Comment by fjuriolli** [comment]
I can make it work with:

`const [input, setInput] = useState("");`

`<TextField`
     `fullWidth`
     `variant="outlined"`
     `placeholder="Give your event a title"`
     `value={input}`
     `onChange={(event) => setInput(event.currentTarget.value)}`
/>`

But I rather not use state in my component

**Comment by bluebill1049** [comment]
going to close this issue as it's in the doc 

https://react-hook-form.com/api#watch
