### ISSUE TITLE
Top-level `useFieldArray`

### ISSUE THREAD

**Issue by Faithfinder** [react-hook-form/react-hook-form#10098]
**Is your feature request related to a problem? Please describe.**
I have a form that is also a table (an array). `useFieldArray` is something to use, theoretically, but `name` is mandatory.

**Describe the solution you'd like**
I would like to be able to manage a form where the data type is an array. Accepting an empty string in `name` seems like a reasonable solution, though not sure how easily implemented.

**Describe alternatives you've considered**
It's fairly trivial to bypass by wrapping the array in an object.

**Comment by bluebill1049** [comment]
This is not possible at the current design scope.
