### ISSUE TITLE
Include validate's result in FieldError

### ISSUE THREAD

**Issue by Betree** [react-hook-form/react-hook-form#1010]
**Is your feature request related to a problem? Please describe.**

I am using a controlled component form through `Controller` that returns not a simple value, but a full object. More specifically, a payout method that has a type (paypal, bank account...etc) and associated data. It works great for handling the value, but I faced an issue with `validate`:

Because of the nature of this `PayoutMethod` controlled input, I need the errors to be described with a full object where each key is a subfield. Said with code, I expect the `errors` object from RHF to be something like:

```es6
const errors = { PayoutMethod: { type: 'validate', result: { email: 'Invalid email' } } }
```

**The problem is:** `validate` only allows you to return errors as strings or booleans so returning an object will not create an error.

<details>
<summary>The actual code to achieve this looks like that</summary>

`PayoutMethod.js`
```jsx
/** Use this function to validate the payout method */
export const validatePayoutMethod = payoutMethod => {
  const errors = {};

  if (payoutMethod.type === PayoutMethodType.PAYPAL) {
    const email = get(payoutMethod, 'data.email');
    if (!email) {
      set(errors, 'data.email', { type: 'required' });
    } else if (!isEmail(email)) {
      set(errors, 'data.email', { type: 'pattern' });
    }
  } else if (payoutMethod.type === PayoutMethodType.OTHER) {
    const content = get(payoutMethod, 'data.content');
    if (!content) {
      set(errors, 'data.content', { type: 'min' });
    }
  }

  return errors;
};
```

`MainForm.js`
```jsx
import { PayoutMethodForm, validatePayoutMethod } from './PayoutMethodForm'

// ...

const { control, errors } = useForm();
return (
  <form>
    <Controller
      name="PayoutMethod"
      control={control}
      defaultValue={payoutMethod}
      valueName="payoutMethod"
      as={<PayoutMethodForm errors={errors.PayoutMethod} />}
      rules={{
        required: true,
        validate: validatePayoutMethod,
      }}
    />
  </form>
)
```

</details>

**Describe the solution you'd like**

Proposal implementation: https://github.com/react-hook-form/react-hook-form/pull/1011. TLDR:
- Allow `ValidateResult` to be an object
- Include validation result (as returned by `validate`) in `FieldError`.

```ts
export type ValidateResult = string | boolean | object | undefined;

export type FieldError = {
  type: string;
  ref?: Ref;
  types?: MultipleFieldErrors;
  message?: string;
  isManual?: boolean;
  result?: ValidateResult; // <-- new
};
```

**Describe alternatives you've considered**

While researching solutions, I've also tried to recursively validate and format errors if `validate` returns an object. Turns out it was doing too much magic, so I went with something simpler and less opinionated.

**Comment by bluebill1049** [comment]
Thanks for the feature request and also a PR ❤️.

I can see the rational behind of this, however everything is about tradeoff. In my honest option, this complicate `validate` function, and i love the simplify of this lib and would love to keep it that way, if i can avoid extra payload or argument i would always try to do so. At the same time, the lib is purposed to make thing work for everyone, so i will leave a waiting for upvote for this feature for awhile and see what's the feedback from the community. 

I have similar requirement at my work project, what i did was just keep it simple with `useState` for the request/validation result, yet still let RHF know that field is `valid` or `invalid`.

**Comment by Betree** [comment]
I don't see how it complicates the validate function, the API didn't change it's just that your validator would now be allowed to return an object. No extra parameter involved here.

Simplicity is good, but extensibility is also required if we aim to provide a library that suits a variety of use cases. I'm totally open to discuss alternatives regarding the implementation, but I think that the use case I'm presenting here (being able to provide rich validation for a controlled field) is not too crazy.  Playing with useState instead of using the library to achieve that sounds like a hack around a missing feature. We've introduced RHF in our codebase to simplify the forms, if it instead adds complexity by forcing us to mix technics then we lose our bet.

**Comment by bluebill1049** [comment]
> I don't see how it complicates the validate function.

My concern is that we returning more data types from a simple `validate` function.  I designed `validate` function to serve single purpose return isValid or message, so does the rest of the other validators (min, max and etc), they either return `true/false` or `string` as message. It act as a validator instead of carry external result.

**Current behaviour** 

```
boolean > true | false
string > errorMessage
```

**After this feature**

As user will have to think three data type in while you working with validate function.

```
boolean > true | false
string > errorMessage
object > true | false | result
```

Again all of the above is from my perspective, i have left as waiting up vote and let the community decide if such feature is what everyone else are after.

**Comment by bluebill1049** [comment]
maybe an alternative solution would be using `validationResolver`, which allow you to craft your own errors object. 

https://react-hook-form.com/api#validationResolver

**Comment by bluebill1049** [comment]
hey team, please drop your thoughts as well if you have sometimes.

**Comment by github0013** [comment]
I assume `PayoutMethodForm` has at least email field and content field?
and you are throwing the whole form component to Controller, to let it validate the entire form?

If you had a Controller for each field in the form, things should just work fine? (without adding a new feature in the library)  I am not sure how complex your form is at this point.

```js
if (payoutMethod.type === PayoutMethodType.PAYPAL) {
...
} else if (payoutMethod.type === PayoutMethodType.OTHER) {
...
}
```

And this can be replaced with validationResolver?

**Comment by JeromeDeLeon** [comment]
Honestly, I don't use `validate` much but when I do, I only validate a specific field because that's the purpose of `register` to handle a single field for example, and attaching `validate` means validating that field only, no more no less. Returning an `object` that contains all errors from other fields defeat the purpose of validating the single field.

**Comment by Betree** [comment]
> I assume `PayoutMethodForm` has at least email field and content field?
> and you are throwing the whole form component to Controller, to let it validate the entire form?
> 
> If you had a `Controller` for each field in the form, things should just work fine? (without adding a new feature in the library) I am not sure how complex your form is at this point.
> 
> ```js
> if (payoutMethod.type === PayoutMethodType.PAYPAL) {
> ...
> } else if (payoutMethod.type === PayoutMethodType.OTHER) {
> ...
> }
> ```
> 
> And this can be replaced with validationResolver?

Thank you for proposing this solution. Using RHF inside this sub-form is something we got away from for multiple reasons (including https://github.com/react-hook-form/react-hook-form/issues/979 and strange behavior with `useFieldArray`).

Support for this would also make it possible to progressively transition to RHF by migrating some part of the forms, but maybe what's needed then is not `Controlled` component a something like `ControlledFields`.

> Honestly, I don't use validate much but when I do, I only validate a specific field because that's the purpose of register to handle a single field for example, and attaching validate means validating that field only, no more no less. Returning an object that contains all errors from other fields defeat the purpose of validating the single field.

I understand how this can create confusion around the `validate` function. I'll find another way to do this.
