### ISSUE TITLE
Type support for deep paths when registering inputs in split forms

### ISSUE THREAD

**Issue by e-compton** [react-hook-form/react-hook-form#10104]
**Is your feature request related to a problem? Please describe.**

I am trying to build a component that represents an object in the form data. By passing name and register in the props, then registering individual inputs for the paths within the object.

```
export type Data = {
  text: string;
  buttons: {
    type: 'web_url';
    title: string;
    url: string;
  }[];
};

export function Element<
  TFieldValues extends FieldValues,
  TPath extends FieldPathByValue<TFieldValues, Data>
>(props: {
  register: UseFormRegister<TFieldValues>;
  watch: UseFormWatch<TFieldValues>;
  name: TPath;
}): JSX.Element {
  return (
    <Layout>
        <textarea
          {...props.register(`${props.name}.text`)}
          placeholder="Title"
        />
<input
          type="hidden"
          value="web_url"
          {...props.register(`${props.name}.buttons.0.type`)}
        />
        <input
          {...props.register(`${props.name}.buttons.0.title`)}
          type="text"
          placeholder="Link Name"
        />
        <input
          {...props.register(`${props.name}.buttons.0.url`)}
          type="text"
          placeholder="Link URL"
        />
    </Layout>
  );
}
``` 

This works great at runtime and gives me really quite powerful components that know nothing about the rest of the form. However, when I switched to typescript to try and strongly type this the call to register is flagged with the following error:
```
Argument of type '`${TPath}.text`' is not assignable to parameter of type 'Path<TFieldValues>'.
```

It seems like there just isn't enough information for typescript compiler to realise that the subpath must exist within TFieldValues

**Describe the solution you'd like**

Ideally for the `watch()` and `register()` functions to understand these deeper paths exist and error only if I've entered a path that doesn't, but I'd settle for it to just not crash.

**Describe alternatives you've considered**

As you can see from the snippet above, I've attempted to follow the example here and constrain TPath so that it does exist. Perhaps there's a type solution that I'm just not seeing here?
https://react-hook-form.com/ts/#FieldPath

And finally, I could refactor my code so that this component is not generic, but instead directly imported an interface of the entire form state. But as I mentioned above, this seems like a really powerful way to decouple from that form state and it would be shame to have to like them all up.

**Additional context**

**Comment by bluebill1049** [comment]
something @felixschorer was trying to resolve https://github.com/react-hook-form/react-hook-form/pull/7387 but it got blocked by later version of TS 4.7^, we may re-look into it again.
