### ISSUE TITLE
issue: isDirty not set if defaultValues is a class object

### ISSUE THREAD

**Issue by gunta987** [react-hook-form/react-hook-form#10115]
### Version Number

7.43.1

### Codesandbox/Expo snack

https://codesandbox.io/s/cool-galois-9by9kq

### Steps to reproduce

1. Initialise defaultValues with a class object (e.g. new application())
2. register a field on the class object to an input. Change the value of the input
3. isDirty remains false. If the class object is spread into a new 'plain' object, i.e. { ...(new application()) } then isDirty behaves correctly

### Expected behaviour

class constructed objects to be treated the same as plain objects

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
not supported with `Class` object.
