### ISSUE TITLE
issue: watched value of a control field with default value is `undefined` at first time trigger conditional rendering

### ISSUE THREAD

**Issue by Hengry** [react-hook-form/react-hook-form#10117]
### Version Number

^7

### Codesandbox/Expo snack

https://codesandbox.io/s/blue-river-filtom?file=/src/App.tsx

### Steps to reproduce

1. Click on "open" button in the browser.
2. The console.log would show in the console tab.

### Expected behaviour

The result showed in console should be
```
firstName: a 
controllerInput: controller input
useControllerInput: useController input
```

### Relevant log output

```shell
firstName: a 
controllerInput: undefined
useControllerInput: useController input
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is the duplicated issue and the fix is already merged which is due to react strict mode.

**Comment by Hengry** [comment]
@bluebill1049 actually it's another issue. I've just try the latest version(7.43.7), while the issue still happens. I will add an another issue, thank you.
