### ISSUE TITLE
issue: Errors are not removed from object fields

### ISSUE THREAD

**Issue by Jamil-Bailony** [react-hook-form/react-hook-form#10110]
### Version Number

7.43.5

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-object-error-bug-d3eew0?file=/src/App.js

### Steps to reproduce

1. try to submit without setting name and selecting level, error is shown for name field and checkboxes goup
2. type any name, and select a level
3. name error is hidden while the `object` field error is still there

### Expected behaviour

object filed should be removed from `errors` object same as `text` field.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Jamil-Bailony** [comment]
related issue #9867

**Comment by bluebill1049** [comment]
This is the same issue that was reported and I am marking it as a design limitation.
