### ISSUE TITLE
Include validation params in FieldError

### ISSUE THREAD

**Issue by Betree** [react-hook-form/react-hook-form#1012]
**Is your feature request related to a problem? Please describe.**
I am building an internationalized form, and I'd like to translate RHF's errors. To do that, I'm relying on the `type` in `FieldError` (`min`, `required`...etc). This works, but I'd like to provide richer messages, for example with `min` I'd like to have something like:

`${fieldName} must be at least ${minLength} characters`

**Describe the solution you'd like**
What I need to achieve this is to have a new property like `validationParams` in `FieldError`:

```ts
export type FieldError = {
  type: string;
  ref?: Ref;
  types?: MultipleFieldErrors;
  message?: string;
  isManual?: boolean;
  validationArgs?: [any]; // <-- new
};
```

**Example errors:**

- Min

```es6
test: {
  type: 'min',
  message: '',
  validationParams: [1]
}
```

**Comment by bluebill1049** [comment]
hey @Betree thanks for the detailed feature request. personally i prefer to keep message as simple as possible (core idea of this lib) i would constructor the message inline.

**Comment by Betree** [comment]
You mean with a custom validate function that returns the properly formatted string right?

**Comment by bluebill1049** [comment]
I guess there are multiple ways I would tackle this.

1. validate function
2. <ErrorMessage /> component
3. write a switch function to display a corresponding error message.

**Comment by Betree** [comment]
The idea of adding the params to the error object was to leverage the ability to translate the native errors (`min`, `required`...etc) with the params that were given to them included in the message. The alternative is indeed to write your own `min`/`max` functions or to pass the parameters manually by other means. Both solutions are not great developer experience.

In our case it's not needed anymore, we're now using more basic messages so I'll close this.

**Comment by TimNZ** [comment]
@bluebill1049 hey mate. 
What's correct etiquette to revisit an issue? - comment in the original or create a new one?
I would just like the built-in validators e.g. minLength, to include the params in the errors object, not adjust the message.
Saves having to maintain validation definitions separately and do a lookup when processing errors.

e.g. currently:

```
errors: {
   category: {type: "required", message: "", ref: {…}}
   name: {
       message: ""
       ref: {name: "name", value: "ffsd"}
       type: "minLength"
   }
}
```

becomes:
```
errors: {
   category: {type: "required", message: "", ref: {…}}
   name: {
       message: ""
       ref: {name: "name", value: "ffsd"}
       type: "minLength",  
       args: 5 
   }
}
```

For:
```
register('name', { required: true, minLength: 5})
```

**Comment by bluebill1049** [comment]
> @bluebill1049 hey mate.
> What's correct etiquette to revisit an issue? - comment in the original or create a new one?
> I would just like the built-in validators e.g. minLength, to include the params in the errors object, not adjust the message.
> Saves having to maintain validation definitions separately and do a lookup when processing errors.
> 
> e.g. currently:
> 
> ```
> errors: {
>    category: {type: "required", message: "", ref: {…}}
>    name: {
>        message: ""
>        ref: {name: "name", value: "ffsd"}
>        type: "minLength"
>    }
> }
> ```
> 
> becomes:
> 
> ```
> errors: {
>    category: {type: "required", message: "", ref: {…}}
>    name: {
>        message: ""
>        ref: {name: "name", value: "ffsd"}
>        type: "minLength",  
>        args: 5 
>    }
> }
> ```
> 
> For:
> 
> ```
> register('name', { required: true, minLength: 5})
> ```

hey mate, API is under a proposal: https://github.com/react-hook-form/react-hook-form/issues/3950 and it's the project board: https://github.com/react-hook-form/react-hook-form/projects/1

**Comment by TimNZ** [comment]
Great, thanks.
Will try to remember to check for project boards on repos before posting.
