### ISSUE TITLE
'watch' function breaking  the  <Autocomplete> writing feature of https://material-ui.com/components/autocomplete/

### ISSUE THREAD

**Issue by JuanmaMenendez** [react-hook-form/react-hook-form#1013]
**Describe the bug**
To use the 'watch' function breaks the  <Autocomplete> writing feature of https://material-ui.com/components/autocomplete/

**To Reproduce**
1. Go to  https://codesandbox.io/s/material-demo-kh2x3
2. Try to write something in the <Autocomplete> component
3. Note: If you comment the line  let watchYes = watch("msa", "");   it will work

**Codesandbox link**
https://codesandbox.io/s/material-demo-kh2x3

**Comment by bluebill1049** [comment]
hey @JuanmaMenendez you may want to wrap autocomplete with our Controller component:

have a read on the following spectrum question.

https://spectrum.chat/react-hook-form/help/how-to-connect-to-autocomplete-in-material-ui~e8c40a4a-fee0-4d0b-8651-44111f973d9c

**Comment by JuanmaMenendez** [comment]
Yes, that fixed the issue. thanks @bluebill1049 

BWY not related to this issue but I want to recommend you change the name of the <Controller> method    **onChange**. Because my wrapped Component has his own **onChange** and it is different. Yours is used to modifying the returned value.

**Comment by bluebill1049** [comment]
any recommendation for the naming? @JuanmaMenendez

**Comment by JuanmaMenendez** [comment]
returnedValue or onReturn

**Comment by JuanmaMenendez** [comment]
onInternalReturn maybe, the most important is to be clear
