### ISSUE TITLE
issue: Array error does not update on a change if any of its fields have errors

### ISSUE THREAD

**Issue by kylemclean** [react-hook-form/react-hook-form#10139]
### Version Number

7.43.7

### Codesandbox/Expo snack

https://codesandbox.io/s/wispy-surf-znf62c?file=/src/App.tsx

### Steps to reproduce

1. Go to CodeSandbox.

2. Click "Submit" to start displaying validation errors on change.
![Screenshot from 2023-03-31 22-25-26](https://user-images.githubusercontent.com/8977964/229265526-7dec5de0-f42e-40a8-8e72-90c76ae03faf.png)

3. Click "Add" button to add an element to the array, causing the array length to be too long, and the error "Form error: Array must contain at most 3 element(s)" to correctly appear.
![Screenshot from 2023-03-31 22-25-39](https://user-images.githubusercontent.com/8977964/229265540-5bee5e5e-7815-48bd-9531-b1098fdcd04c.png)

4. Click "Remove" next to the newly-added element to remove it, causing the array length to be valid, thus causing the error to correctly disappear.
![Screenshot from 2023-03-31 22-25-44](https://user-images.githubusercontent.com/8977964/229265567-abde61fb-09fe-417b-abd1-26ff47670ad3.png)

5. Delete all of the text in one of the existing array elements, making it invalid and causing an error to correctly appear.
![Screenshot from 2023-03-31 22-25-56](https://user-images.githubusercontent.com/8977964/229265590-e28cf702-451a-4ab3-9ea6-baaa883b84b0.png)

6. Click the "Add" button again to add another element to the array.  
**INCORRECT BEHAVIOR:** even though the array length is no longer valid, the error from before, "Form error: Array must contain at most 3 element(s)", is **NOT** being displayed.
![Screenshot from 2023-03-31 22-26-14](https://user-images.githubusercontent.com/8977964/229265600-6ae9fcd9-2bdb-4324-867b-6e9426642ca2.png)

7. Click the "Submit" button, which causes the expected error "Form error: Array must contain at most 3 element(s)"  to correctly display.
![Screenshot from 2023-03-31 22-26-28](https://user-images.githubusercontent.com/8977964/229265646-2b57f838-233e-4890-b9a1-1bb77a6c1223.png)

8. Click "Remove" next to the newly-added element, causing the array length to be valid.  
**INCORRECT BEHAVIOR:** even though the array length is now valid, the error "Form error: Array must contain at most 3 element(s)" is still incorrectly being displayed.
![Screenshot from 2023-03-31 22-26-40](https://user-images.githubusercontent.com/8977964/229265676-56051c71-165e-4939-8c6c-f665927bf57e.png)

9. Click the "Submit" button, which causes the incorrect error "Form error: Array must contain at most 3 element(s)" to disappear.
![Screenshot from 2023-03-31 22-26-46](https://user-images.githubusercontent.com/8977964/229265708-8e679250-9eaf-44cc-9c0c-117d833d6ebd.png)

### Expected behaviour

On step 6, clicking the "Add" button should immediately display the error "Form error: Array must contain at most 3 element(s)" instead of requiring the form to be submitted to display it.

On step 8, clicking the "Remove" button should immediately hide the error "Form error: Array must contain at most 3 element(s)" instead of requiring the form to be submitted to hide it.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Array error will not get updated by `onChange` as hook form validation based on field level, each user action (append, prepend and etc.) do update the field array. You can always fallback to `trigger` to trigger field array level validation.

**Comment by kylemclean** [comment]
The issue I am describing is that appends and removes on the array are sometimes not revalidating the array. This appears to be a bug.

**Comment by bluebill1049** [comment]
Please do your own debugging: https://react-hook-form.com/api/useform/

```
resolver: async (data, context, options) => {
  // you can debug your validation schema here
  console.log('formData', data)
  console.log('validation result', await anyResolver(schema)(data, context, options))
  return anyResolver(schema)(data, context, options)
},
```

see if the validation schema return the correct output.  validation will always gets executed after each action: https://github.com/react-hook-form/react-hook-form/blob/master/src/useFieldArray.ts#L323-L361

**Comment by kylemclean** [comment]
I have now confirmed using the debug logging that the validation is executed and returns the correct output on steps 6 and 8, but the displayed error does not change until the form is submitted. The CodeSandbox link has been updated to include the debug logging.

The problem seems to be with [line 329 in `useFieldArray.ts`](https://github.com/react-hook-form/react-hook-form/blob/20d897b4d957e0e59692612c9339731199aaa985/src/useFieldArray.ts#L329). On steps 6 and 8, both `existingError` and `error` are truthy, causing the update to `control._formState.errors` to be skipped, and thus the error state is wrong.

**Comment by bluebill1049** [comment]
> The problem seems to be with [line 329 in useFieldArray.ts](https://github.com/react-hook-form/react-hook-form/blob/20d897b4d957e0e59692612c9339731199aaa985/src/useFieldArray.ts#L329). On steps 6 and 8, both existingError and error are truthy, causing the update to control._formState.errors to be skipped, and thus the error state is wrong.

thanks for looking close into this issue, could you debug further on this since you are already deep into the issue, and find out the root cause? If it's possible to send over a PR would be even greater.

**Comment by kylemclean** [comment]
I will see what I can do.

**Comment by bluebill1049** [comment]
<img width="865" alt="Screenshot 2023-03-31 at 8 13 55 am" src="https://user-images.githubusercontent.com/10513364/228966001-5452e2a2-4634-4c11-a068-a12740ee5d87.png">

just following up on this issue again, step 6 doesn't return any errors. I will have to revert the fix for now as it introduced a regression.

**Comment by abhinav2712** [comment]
better to use formik, literally solves every damn problem

**Comment by bluebill1049** [comment]
hey @kylemclean could you share more detail on the origin issue? I test above seems to work fine. I will look into it this weekend.

**Comment by kylemclean** [comment]
@bluebill1049
I have updated the issue with some screenshots that should more clearly illustrate the problem.

Please also see my comment on https://github.com/react-hook-form/react-hook-form/issues/10207#issuecomment-1491003579, which might help demonstrate why my PR #10150 resulted in #10207 appearing.
