### ISSUE TITLE
please add `replace` function to `useFieldArray` hook

### ISSUE THREAD

**Issue by kerosan** [react-hook-form/react-hook-form#1016]
there is no ability to `replace`/`update` item in field array  
if i use`remove` by index and `append` new one in one handler it doesn't work 

```
const { fields, append, prepend, remove, swap, move, insert } = useFieldArray(
    {
      control,
      name: "test"
    }
  );
```

**Comment by bluebill1049** [comment]
isn't that `setValue`?

**Comment by kerosan** [comment]
> isn't that `setValue`?
 i just tried with simple inputs but it looks awful
why dont use `replace(index, value)` hook ?  
https://codesandbox.io/s/react-hook-form-usefieldarray-q4yyo

**Comment by bluebill1049** [comment]
because setValue will support `nested objects` in the next build, making `replace` function redundant. https://github.com/react-hook-form/react-hook-form/issues/979

<img width="372" alt="Screen Shot 2020-02-12 at 10 12 42 pm" src="https://user-images.githubusercontent.com/10513364/74329917-cfa80a00-4de4-11ea-8e7a-60fcb1866e5d.png">

```
setValue('test[0]', {})
```

**Comment by kerosan** [comment]
oh, thx

**Comment by kerosan** [comment]
> because setValue will support `nested objects` in the next build, making `replace` function redundant. #979
> 
> <img alt="Screen Shot 2020-02-12 at 10 12 42 pm" width="372" src="https://user-images.githubusercontent.com/10513364/74329917-cfa80a00-4de4-11ea-8e7a-60fcb1866e5d.png">
> 
> ```
> setValue('test[0]', {})
> ```
maybe in future you could make shortcut for `setValue` 
`const replace = (index, value) => setValue(`${getNameOfFieldArray()}[${index}]`, value)`

**Comment by bluebill1049** [comment]
yea, great suggestion.

**Comment by tjlav5** [comment]
Hey @bluebill1049, it looks like this is marked as 'done' in your tracker, but I'm still unable to call `setValue('foo[0].bar', 123)`; doing so ends up adding a top-level entry in the form with the string `foo[0].bar` instead of `{foo: [{bar: 123}]}`. I'm on 5.1.1*. Thanks

**Comment by bluebill1049** [comment]
@tjlav5 send a codesandbox please

**Comment by tjlav5** [comment]
Ah sorry, false alarm. It turns out I wasn't registering each sub-component... `register('foo[0].bar');`, I only had `foo` registered. Thanks for following up so quickly and really digging your library. Cheers
