### ISSUE TITLE
issue: typescript inference failure on `error.<field_array>?.[index]` object for useFieldArray with useFormContext

### ISSUE THREAD

**Issue by jontmy** [react-hook-form/react-hook-form#10169]
### Version Number

7.43.7

### Codesandbox/Expo snack

https://codesandbox.io/s/crimson-darkness-kyegtx?file=/src/App.tsx

### Steps to reproduce

1. Create a Zod validation schema for a field array `tags` with default values.
```
// schema:
z.object({
  tags: z.array(
    z.object({
      value: z.string().nonempty("tag cannot be blank")
    })
  )
})

// default values:
tags: [{ value: "" }]
```
2. Pass the schema and default values to `useForm` for `resolver` and `defaultValues` respectively.
3. Create the field array `tags` using the `control` from a `useFormContext()`.
4. Attempt to access the error message, e.g. `errors.tags?.[index]?.value?.message` will yield the following TypeScript error, even though the validation error message will be displayed correctly.
```
Element implicitly has an 'any' type because expression of type 'number' can't be used to index type 'FieldError | Merge<FieldError, FieldErrorsImpl<any>>'.
  No index signature with a parameter of type 'number' was found on type 'FieldError | Merge<FieldError, FieldErrorsImpl<any>>'.
```

### Expected behaviour

When the field array is constructed via `useForm` instead of `useFormContext`, the TypeScript error does not occur.

In the CodeSandbox example I have created `FormWithContext` and `FormWithoutContext` to demonstrate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
You can provide a generic at useForm/useFormContext by inferring zod type.

```tsx
useForm<FormType>()
useFormContext <FormType>()
```

**Comment by jontmy** [comment]
Ah I see, thanks! I had tried that on the `useForm` before the `useFormContext`, but I hadn't thought about using the generic on `useFormContext` itself!
