### ISSUE TITLE
setValueAs for defaultValues

### ISSUE THREAD

**Issue by roxieharris** [react-hook-form/react-hook-form#10179]
**Is your feature request related to a problem? Please describe.**
I'm working on a settings form which populates with defaultValues from an API call, including an ISO datetime as a string. Elsewhere in my app I use .slice() and .replace() to format similar datetimes to be more human-readable. I want to use setValueAs to transform my string in the same manner, but it doesn't work for defaultValues.

**Describe the solution you'd like**
Some alternative to setValueAs which can be applied to defaultValues.

**Describe alternatives you've considered**

- _Changing the API to return the datetime in the format I'm using:_ I wouldn't have the complete time available to me, which is sometimes necessary in other parts of the app.
- _Using reset() in a useEffect() to setValueAs after form load:_ I saw this as a solution to someone else's problem, but it doesn't work for my purposes (or I just can't figure it out!)

**Comment by bluebill1049** [comment]
Could you provide a simple csb with your example usage? Let's see if there is any workaround.
