### ISSUE TITLE
useFieldArray with Controller does not work.

### ISSUE THREAD

**Issue by jarretrose** [react-hook-form/react-hook-form#1019]
**Describe the bug**
Inputs using the Controller wrapper cannot use the _remove_ or _insert_ methods.

**To Reproduce**
1. Go to [the below listed Codesandbox](https://codesandbox.io/s/react-hook-form-usefieldarraycontroller-93rzh).
1b. Make sure the react-hook-form dependency is at the latest stable release (4.9.3).
2. Click on "Delete" next to any input or "Remove." 
3. Open the console.
4. Error: **data.filter is not a function**.
5. Click on "Insert At."
6. Open the console.
7. Error: **data.slice is not a function or its return value is not iterable**.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarraycontroller-93rzh

**Expected behavior**
Expect the Controller wrapper to allow for use of all useFieldArray hook methods.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by bluebill1049** [comment]
Thanks i will take a look this issue.

**Comment by bluebill1049** [comment]
oops this one is not valid:
```
const { fields, append, prepend, remove, swap, move, insert } = useFieldArray(
    {
      control,
      name: "items"
    }
  );
```

check your name :)

**Comment by jarretrose** [comment]
Oh man, I'm so sorry! It turns out that I was having a separate issue in my
code, but one that was related to the name.

In my case, I have nested inputs like:

foo.bars[]

Prior to the most recent release, I was able to use "bars" as the unique
name. After the release, I needed to include "foo" as well.

Best,
Jarret

**Comment by bluebill1049** [comment]
No worries man 👍
