### ISSUE TITLE
issue: isDirty and dirtyFields are not marked as dirty on first submit of an array

### ISSUE THREAD

**Issue by garyThrels** [react-hook-form/react-hook-form#10198]
### Version Number

7.43.8

### Codesandbox/Expo snack

https://codesandbox.io/s/lucid-keller-jemidm

### Steps to reproduce

1. Go to https://codesandbox.io/s/lucid-keller-jemidm?
2. Open console logs
3. Mark the 'Dogs' checkbox as checked
4. Hit submit
5. In the console we see a log: `FormState: isDirty? false - dirty fields? {}`
6. Mark the 'Birds' checkbox as checked
7. Hit submit
8. In the console we see a log: `FormState: isDirty? true - dirty fields? {checkedBoxes: true}`

### Expected behaviour

After step 4. when hitting submit the first time the form should be marked as dirty, showing the log in step 8.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
FormState: isDirty? false - dirty fields? {}

FormState: isDirty? true - dirty fields? {checkedBoxes: true}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by garyThrels** [comment]
I tried looking a bit more into my issue to see what may be happening, from what I could gather when calling the `updateTouchAndDirty` method in the `createFormControl` script upon enabling a checkbox, the `_proxyFormState.isDirty` is set to false, then after clicking the checkbox to disable and enable it again, the  `_proxyFormState.isDirty` is set to `all` and the `shouldUpdateField` variable is then set to true, leading to the `isDirty` and `dirtyFields` to being updated.

I am new to the code of this library and couldn't spend more time on it and figure why `_proxyFormState` does this and what it is used for. Hope this helps

**Comment by Moshyfawn** [comment]
`formState` is [a `Proxy` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy): it's a React renders optimization measure, that requires you to "subscribe" to / read the specific form state value before it's "reactive".

To put it short: `formState.isDirty` doesn't give you the latest state value; do this instead
```js
const { formState } = useForm()
const { isDirty, dirtyFields } = formState

console.log(isDirty, dirtyFields) <-- Now you get the "up-to-date" values
```

Check out [the RHF `formState` docs](https://react-hook-form.com/api/useform/formstate/) to learn more
