### ISSUE TITLE
issue: allow empty string values in useFieldArray

### ISSUE THREAD

**Issue by ilteoood** [react-hook-form/react-hook-form#10200]
### Version Number

7.43.8

### Codesandbox/Expo snack

https://codesandbox.io/s/twilight-sound-9otb7b?file=/src/App.js

### Steps to reproduce

1. Look at the output message

### Expected behaviour

The length of the `fields` should be equal to the same as the provided data.
In other words, it should keep the empty values.

Note: it seems to be a regression introduced with version 7.22.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Field Array does **not** support **flat** field array _(non-object array items)_ as per [RHF `useFieldArray` docs](https://react-hook-form.com/api/usefieldarray/#rules)
