### ISSUE TITLE
Watch value for array field is not updating as expected

### ISSUE THREAD

**Issue by bcotrim** [react-hook-form/react-hook-form#1020]
**Describe the bug**
Watch value for array field is not updating as expected

**To Reproduce**
1. Click "Add Person"
2. Click "More Details" (Interests Field show up - expected)
3. Click "Add Person"
4. Click "More Details" (Interests Field doesn't show up - not expected)
5. Click "Add Person"
6. Interests Field now shows up on previous Person

**Codesandbox link**
https://codesandbox.io/s/brave-bouman-m5yvw

**Expected behavior**
Behaviour should be consistent

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - 79.0.3945.130 (Official Build) (64-bit)

**Comment by bluebill1049** [comment]
please help verify with this beta version: react-hook-form@4.9.4-beta.2

**Comment by bcotrim** [comment]
@bluebill1049 it appears to be fixed! Thank you

**Comment by bluebill1049** [comment]
thanks @bcotrim it will be in the next patch 👍
