### ISSUE TITLE
issue: `shouldUnregister: true` doens't work on `key` change

### ISSUE THREAD

**Issue by sshmyg** [react-hook-form/react-hook-form#10204]
### Version Number

7.43.8

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-get-started-forked-c7pvuk?file=/src/index.js:325-344

### Steps to reproduce

1. Open codebox link
2. Change text field from `test` to smth else
3. Select some different option in select field
4. Text field (unmount, mount) happens, because of key changing

### Expected behaviour

Text field should have default value from `useForm`, but it has value from p.2 👆
`watch` show right value, but `useController` returns wrong one.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
You can see it in console log 

console.log({
    wrong: field.value,
    right: fieldValueFromWatch,
  });
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Please use `unregister` for such use-case.

**Comment by sshmyg** [comment]
https://codesandbox.io/s/react-hook-form-get-started-forked-c7pvuk?file=/src/Field.js

It doesn't work either

**Comment by bluebill1049** [comment]
Did you unmount that component? If not then the register call will still occur inside that component. What's your use case with `key` prop change?

**Comment by bluebill1049** [comment]
Glad you sort it out, just Fyi change key is still going to make the component re-render and getting re-register again instead the controller, so if you want to truly unregister an input with unmount, you should remove that component all together.
