### ISSUE TITLE
reset issue 

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#1021]
Sure! Here's the dead simple version: 
https://codesandbox.io/s/react-hook-form-wizard-form-tj1n7

_Originally posted by @mikestopcontinues in https://github.com/react-hook-form/react-hook-form/issues/914#issuecomment-585470674_

**Comment by bluebill1049** [comment]
ok found reason why:

https://codesandbox.io/s/react-hook-form-wizard-form-5y7wi

type="reset" please use button instead.

**Comment by mikestopcontinues** [comment]
Yeesh! Thanks! :)
