### ISSUE TITLE
issue: TypeScript issue with formState.errors and fieldArray for discriminated union type

### ISSUE THREAD

**Issue by elieven** [react-hook-form/react-hook-form#10217]
### Version Number

7.43.8

### Codesandbox/Expo snack

https://codesandbox.io/s/blazing-sea-v8tgg3?file=%2Fsrc%2FApp.tsx

### Steps to reproduce

Nothing really... it's a TypeScript issue

### Expected behaviour

For typescript to know which type the error will be especially when it is allready checked which of the discriminated types the field is.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is a typescript limitation for the lib.

**Comment by elieven** [comment]
Any workaround or suggestion as to what to do about it? Again would hate to eat your time but i would love a very quick explanation as to how this works and why it can't be done.

**Comment by elieven** [comment]
Okay this is kind of hacky and I would certainly prefer a built in solution or that the errors would be aware of which error they are from the start but I have come up with this temporary [workaround](https://codesandbox.io/s/wispy-smoke-zynf4k?file=%2Fsrc%2FApp.tsx%3A246-247).

**Comment by arjunyel** [comment]
I just found out discriminated unions are getting removed from Zod https://github.com/colinhacks/zod/issues/2106
