### ISSUE TITLE
issue: isValid is false but errors is empty when using an invalid value (based on the validation) in defaultValues

### ISSUE THREAD

**Issue by therealtgd** [react-hook-form/react-hook-form#10229]
### Version Number

7.4.1

### Codesandbox/Expo snack

https://codesandbox.io/s/wandering-cache-w28s8l?file=/src/App.js

### Steps to reproduce

1. Go to the provided sandbox
2. See that the default value is set to an invalid value based on the yup scheme 
3. See that `isValid=false` and `errors={}`

### Expected behaviour

```
isValid=false
errors={name: {...}}
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Please upgrade to the latest version.
<img width="1370" alt="Screenshot 2023-04-06 at 7 43 45 am" src="https://user-images.githubusercontent.com/10513364/230218792-83032d87-9b5d-4696-87ac-bd372e9d4600.png">

**Comment by therealtgd** [comment]
Hi,
It is the same on the latest version. Here is the [code sandbox.](https://codesandbox.io/s/wandering-cache-w28s8l?file=/src/App.js)

**Comment by therealtgd** [comment]
> Please upgrade to the latest version. <img alt="Screenshot 2023-04-06 at 7 43 45 am" width="1370" src="https://user-images.githubusercontent.com/10513364/230218792-83032d87-9b5d-4696-87ac-bd372e9d4600.png">
Hi,
It is the same on the latest version. Here is the [code sandbox.](https://codesandbox.io/s/wandering-cache-w28s8l?file=/src/App.js)
