### ISSUE TITLE
[conditional rendering] unexpected behavior for rendering field values

### ISSUE THREAD

**Issue by d4ny0** [react-hook-form/react-hook-form#10226]
### Version Number

v7.43.8

### Codesandbox/Expo snack

https://codesandbox.io/s/trusting-marco-mrncyh?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/trusting-marco-mrncyh?file=/src/App.tsx  and see the initial value
<img width="552" alt="step1 - correct dogsname" src="https://user-images.githubusercontent.com/7263662/229787364-abdba2a1-26f0-4071-9534-44e645bb7b1b.png">
2. select "cat" in the pet dropdown, now the field "catsName" is rendered with defaultValue "kitty"<img width="557" alt="step2 - correct catsname" src="https://user-images.githubusercontent.com/7263662/229787360-8a4ac59a-fec6-4ed4-bcee-f54c51f46e17.png"> 

3. select "dog" again in the pet dropdown
4. Error: now the field "dogsName" is rendered with  the defaultValue from "catsName"
<img width="562" alt="step3 - wrong dogsname" src="https://user-images.githubusercontent.com/7263662/229787356-7a8c0e28-f0a1-4ad4-aa21-bbb24493dccf.png">

### Expected behaviour

the default values of the conditional rendered inputs should be displayed correctly.

Additional Info:

- the values are only wrong in the ui, in DevTools they are maintained correctly
<img width="569" alt="wrong ui - correct in devtools" src="https://user-images.githubusercontent.com/7263662/229787937-81dc1d75-7f2d-44a5-900f-90c7c9903a38.png">
- also if each of the inputs is called like `condition && input` it works as expected. I Included a functioning version as comment in line 62 of the App.tsx in the sandbox
  
  
<img width="818" alt="functioning version" src="https://user-images.githubusercontent.com/7263662/229788131-41c0eede-26e6-408a-853a-c92e71d86aa6.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Refer to this section: https://react-hook-form.com/faqs/#Whyisdefaultvaluenotchangingcorrectlywithternaryoperator if that's the root cause.

**Comment by devakrishna33** [comment]
@bluebill1049 @d4ny0 adding keys fixes this issue, I have added a working sandbox [here](https://codesandbox.io/s/xenodochial-fermat-cqcpyi?file=/src/App.tsx)

**Comment by bluebill1049** [comment]
thanks you @devakrishna33 👯
