### ISSUE TITLE
Passing type="password" to controller MUI textfield throws a warning.

### ISSUE THREAD

**Issue by TimothyStiles** [react-hook-form/react-hook-form#1022]
Just started playing around with react-hook-form and have been getting this weird warning every time I try to make a password field.
```jsx
          <Controller
            as={<TextField/>}
            control={control}
            variant="outlined"
            margin="normal"
            required
            fullWidth
            name="password"
            label="Password"
            type="password"
            id="password"
            autoComplete="current-password"
          />
```
![Screen Shot 2020-02-12 at 3 35 05 PM](https://user-images.githubusercontent.com/7042260/74387411-4fb27d80-4dad-11ea-8753-20262f1a9df0.png)

When I comment out `type="password"` the warning goes away.

```jsx
          <Controller
            as={<TextField/>}
            control={control}
            variant="outlined"
            margin="normal"
            required
            fullWidth
            name="password"
            label="Password"
            // type="password"
            id="password"
            autoComplete="current-password"
          />
```

Any idea what's happening here? Is there a way to flag this field as a password field without getting a warning? Other fields without password type seem to work fine.

Thanks.

**Comment by bluebill1049** [comment]
defaultValue: https://react-hook-form.com/api#Controller check out the doc  it's changing from uncontrolled to controlled.

**Comment by TimothyStiles** [comment]
That was exactly it. Thanks @bluebill1049.  I'll close the thread now. For anyone who stumbles upon this in the future here's the solution:

```jsx
          <Controller
            as={<TextField/>}
            control={control}
            variant="outlined"
            margin="normal"
            required
            fullWidth
            name="password"
            label="Password"
            type="password"
            id="password"
            autoComplete="current-password"
            // added default value
            defaultValue={{ value: '' }}
          />
```

**Comment by bluebill1049** [comment]
thanks for sharing answer too :) @TimothyStiles
