### ISSUE TITLE
watch not wokring in react 18, for RHF V6

### ISSUE THREAD

**Issue by cesarve77** [react-hook-form/react-hook-form#10236]
### Version Number

6.15.8

### Codesandbox/Expo snack

https://stackblitz.com/edit/react-ts-nsdahz?file=App.tsx,index.tsx

### Steps to reproduce

1. change the first input value
2. see the console logs
3. should change with every key pressed
4. nothing happens

### Expected behaviour

watch("example") rerender the function

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Please upgrade to v7, v6 is 2 years behind now.
