### ISSUE TITLE
In-docs voice/text chat 🤩

### ISSUE THREAD

**Issue by RajeshJ3** [react-hook-form/react-hook-form#10231]
### Problem description
I wanted to bring to your attention a challenge that new developers face when starting with React Hook Form. It can be quite complicated to understand all the different components and how they work together, leading to frustration and wasted time.

### Proposed solution
I have a solution that I believe could help. With **Browsemates**, experienced developers can connect with newer developers and provide guidance, tips, and answer questions.

Browsemates is a **website extension**, which connects people who are **browsing the same webpage** through voice and text mediums. This can not only help new developers get started more quickly, but it can also help build a **stronger community** around React Hook Form.

Learn more at [browsemates.com](https://www.browsemates.com/)

A few screenshots of how the extension will look like

<table>
  <tr>
    <td> <img src="https://user-images.githubusercontent.com/41537758/230118671-10c6b2bc-e383-4080-8346-239bec56c326.png"  alt="1"></td>
    <td><img src="https://user-images.githubusercontent.com/41537758/230118489-ccdd2e9e-9b4f-4ccf-b3cf-bde69caa1619.png" alt="2"></td>
   </tr> 
</table>

### Integration
Include the following script at the end of the `body` tag.

```html
<script
  src="https://tag.browsemates.com/tag.js?bmc-id=B-REACTHFORM"
  id="bmc-script"
></script>
```

---

### Pricing
Browsemates is **completely FREE for all open-source projects**

---

Thanks 

**Rajesh Joshi**
Software Engineer
**Browsemates**
[browsemates.com](https://www.browsemates.com/)

**Comment by Moshyfawn** [comment]
I don't think issues is a good place to advertise your products in.

P.S. avoid spamming other repositories and projects in the same way. There're better ways to promote your tools.
