### ISSUE TITLE
issue: append("")  is  not working as expected

### ISSUE THREAD

**Issue by d-ashokkumar** [react-hook-form/react-hook-form#10243]
### Version Number

7.43.8

### Codesandbox/Expo snack

https://stackblitz.com/edit/react-1f11av

### Steps to reproduce

1. Go to 'stackbliz link'
2. Click on 'add button twice or thrice'

### Expected behaviour

The values are not appended in the form twice/thrice depending upon the number of clicks

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devakrishna33** [comment]
@d-ashokkumar as given in the [documentation](https://react-hook-form.com/api/usefieldarray/), useFieldArray does not support flat field array. You can try adding your array values as an object, I have updated your sandbox with a potential solution, please check [here](https://react-vjqugv.stackblitz.io).

**Comment by bluebill1049** [comment]
thanks @devakrishna33 👍
