### ISSUE TITLE
Using nested components with FieldArrays, useArrayContext()

### ISSUE THREAD

**Issue by Dogacel** [react-hook-form/react-hook-form#1024]
**Is your feature request related to a problem? Please describe.**
When I am using nested structures inside fieldArrays I am passing methods of useFieldArray to children. It makes components look messed up.

**Describe the solution you'd like**
Like the useFormContext, I wish there was a <ArrayContext> and useArrayContext to handle those kinds of operations.

**Describe alternatives you've considered**
I've tried to use useFormContext and tried to call useFieldArray inside the nested component but it did not work. I think useFieldArray reinitialized the fieldArray so my app was unresponsive. If there was a substitute for that method, it can generate a lot cleaner code.

**Additional context**
None.

**Comment by bluebill1049** [comment]
provide a CSB for the issue plz.

**Comment by bluebill1049** [comment]
closing this issue, until codesandbox or example is supplied.

**Comment by Dogacel** [comment]
[CodeSandbox](https://codesandbox.io/s/long-bush-r2yg5?fontsize=14&hidenavigation=1&theme=dark)

Here is the proposed solution.

**Comment by bluebill1049** [comment]
thanks for the suggestion, not everyone is using FormContext. I am interested in this part

> I think useFieldArray reinitialized the fieldArray so my app was unresponsive

**Comment by bluebill1049** [comment]
unless you can provide a solid example of the issue above, I think we will move on with this.

**Comment by Dogacel** [comment]
> thanks for the suggestion, not everyone is using FormContext. I am interested in this part
> 
> > I think useFieldArray reinitialized the fieldArray so my app was unresponsive
> 
> do you have example for this?

[CodeSandbox](https://codesandbox.io/s/boring-worker-w6vlw)
I am trying to access the field array using controller I think this is not possible right now.

**Comment by bluebill1049** [comment]
what about this example with controller: https://codesandbox.io/s/react-hook-form-usefieldarray-controller-pppf3

**Comment by Dogacel** [comment]
> what about this example with controller: https://codesandbox.io/s/react-hook-form-usefieldarray-controller-pppf3

In this example there isn't an external component that tries to access the fieldArray's functions like in [this](https://codesandbox.io/s/boring-worker-w6vlw).

**Comment by bluebill1049** [comment]
The usage is really up to the developers.
