### ISSUE TITLE
Prevent form submission in the submit handler

### ISSUE THREAD

**Issue by gilbsgilbs** [react-hook-form/react-hook-form#1025]
**Is your feature request related to a problem? Please describe.**

The [documentation for `handleSubmit`](https://react-hook-form.com/api/#handleSubmit) indicates:

> Note: You can pass an async function for asynchronous validation.

However, this appears to be pretty unusable in the current state of RHF.

When performing extra validation in the submit handler, there are currently no way to prevent the update of the `formState`'s `isSubmitted` and `submitCount` properties. Therefore, you have to maintain a separate submission state outside of RHF, and RHF's `formState` becomes basically inconsistent with what user might expect. Even worse: calling `setError(…)` in the submit handler doesn't prevent the `formState` from updating `isSubmitted` and `submitCount` which could probably be considered as a bug.

Another downside of the current way submission works is when one want to wait for some event to happen before considering the form as submitted. For example, it's quite common for me to dispatch some action in the `handleSubmit` (e.g. call some API) and then wait for some promise to resolve (e.g. the API call was successful).

**Describe the solution you'd like**

The simplest solution I can imagine that would cover all my use-cases would be to allow the submit handler to return a boolean. Returning `false` in a submit handler would just prevent the update of `formState`'s `isSubmitted` and `submitCount` properties:

```js
async function handleSubmit(formData: any): boolean {
  const isConsistent = checkFormConsistency(formData);
  if (!isConsistent) return false;  // prevents isSubmitted and submitCount from updating

  dispatch(callApi(formData))
  await somePromise;

  return true; // this would be optional to avoid breaking changes
}
```

**Describe alternatives you've considered**

```js
async function handleSubmit(formData: any): boolean {
  // This should prevent isSubmitted and submitCount from updating
  setError("myField", "inconsistent", "This field is inconsistent with another field");
}
```

The two solutions are not exclusive IMO. I would expect both. Doing only the `setError` one however doesn't work if the form is not related to a specific field (e.g. error response from an API call).

WDYT?

**Comment by bluebill1049** [comment]
```
const mySubmit =(e) => {
  e.preventDefault();
  // do your early validation here

  handleSubit(() => {
    // do you stuff in here;
  })(e)
}

<form onSubmit={mySubmit}> 
</form>
```

what about this?

**Comment by gilbsgilbs** [comment]
But you loose the benefit from `async` validation if you do this, isn't it?

**Comment by bluebill1049** [comment]
what do you mean? 

```
const mySubmit = async (e) => {
  e.preventDefault();
  // do your early validation here
  await xxx;

  handleSubit(() => {
    // do you stuff in here;
  })(e)
}

<form onSubmit={mySubmit}> 
</form>
```

**Comment by gilbsgilbs** [comment]
That's an interesting solution. Thank you very much :+1: .

**Comment by gilbsgilbs** [comment]
Actually, there's still a downside with this approach unfortunately: the field-level validation happens only in `handleSubmit`. So you have to invoke `triggerValidation()` first, but that means field-level validation will be performed twice.

**Comment by gilbsgilbs** [comment]
And also, when doing this, the form will remain with `isSubmitting` to false during the whole validation. So you have to do the validation in `handleSubmit`.

**Comment by bluebill1049** [comment]
- `isSubmitted and submitCount` is irrelevant to whether a form is valid or not.
- if you would like to validate with a specific field against API, you can always use `validate` function as well.

**Comment by gilbsgilbs** [comment]
Thanks for responding!

> isSubmitted and submitCount is irrelevant to whether a form is valid or not.

Then for the sake of consistency, `isSubmitted` and `submitCount` should also update when there's a field-level error. This is not the case at the moment.

At the end of the day this is not that bad, but it just makes it more confusing to work with the form because you have to maintain your own "usable" state for `isSubmitting` and `isSubmitted` somewhere. That's really something I'd expect the library to do, especially when the doc indicates `handleSubmit` is a good place to perform extra-validation.

I may be wrong, but it seems to me that the first solution I described (return a boolean in `handleSubmit`) just seamlessly extends over the existing API. I'd like to understand why you're so refractory to it. I don't feel like it's such a profound change.

> if you would like to validate with a specific field against API, you can always use validate function as well

I know, but that's not my use-case. I'm just checking for global consistency which is not tied to a specific field.

Anyways, thanks for your time. Keep up the great work 💪

**Comment by bluebill1049** [comment]
> Then for the sake of consistency, isSubmitted and submitCount should also update when there's a field-level error. This is not the case at the moment.

It should only change during submission not the field level.

> I'd like to understand why you're so refractory to it. I don't feel like it's such a profound change.

I think what we having right now it's good for majority of the use case, and i like to keep it simple for everyone, if this was a project between us, i would go make the change right away.

**Comment by gilbsgilbs** [comment]
Fair enough. Thanks!

**Comment by bluebill1049** [comment]
Thank you for understanding @gilbsgilbs

**Comment by pfcodes** [comment]
Wouldn't this work?
```
<form
  onSubmit={(e) => {
    e.preventDefault()
    handleSubmit(onSubmit)()
  }}
>
  ...
</form>
```

**Comment by VictorPietro** [comment]
> what do you mean?
> 
> ```
> const mySubmit = async (e) => {
>   e.preventDefault();
>   // do your early validation here
>   await xxx;
> 
>   handleSubit(() => {
>     // do you stuff in here;
>   })(e)
> }
> 
> <form onSubmit={mySubmit}> 
> </form>
> ```

Hello @bluebill1049 thanks for the answer, I believe it worked for me. Would you mind explaining the (e) called in the end of "handleSubmit()" call, please? I've tried without the (e) and it did not work, but with the (e) it worked (reached my console.log). Here is my code.
```
const { register, handleSubmit, setError, formState } = useForm({
        resolver: yupResolver(createPageFormSchema)
    });
    
async function mySubmit(e: FormEvent) {
        e.preventDefault();

        await handleSubmit(handleLogin)(e);
    }

    async function handleLogin({ email, password }: LoginPageFormData) {
        const data = {
            email,
            password,
        }

        console.log(data);

        // await signIn(data);
    }
    
    ...
    
    <form onSubmit={mySubmit}>
```

**Comment by bluebill1049** [comment]
@VictorPietro it's a curry function: https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/createFormControl.ts#L1016

**Comment by ekaterina4952** [comment]
> what do you mean?
> 
> ```
> const mySubmit = async (e) => {
>   e.preventDefault();
>   // do your early validation here
>   await xxx;
> 
>   handleSubit(() => {
>     // do you stuff in here;
>   })(e)
> }
> 
> <form onSubmit={mySubmit}> 
> </form>
> ```

Hi @bluebill1049, Thanks for your answer. when I use this, it is not working. Below is my code
```

    const onSubmit = async (data) => {
        if (isObjEmpty(errors)) {
           await useJwt
                .login({phone, password})
                .then(res => {
                      //login
                    }
                })
                .catch(err => {
                    console.log(err)
                })
        }
    }
    const LoginSubmit = async (e) => {
        e.preventDefault()
        await handleSubmit(onSubmit)(e)
    }
    ...
    
    <form onSubmit={LoginSubmit }></form>
```
