### ISSUE TITLE
emptyAsUndefined

### ISSUE THREAD

**Issue by VivoCyber** [react-hook-form/react-hook-form#10253]
undefined for "" like valueAsNumber
emptyAsUndefined is so useFull for data validation like zod schema validator
i have some optional field that if it not undifind must has some rules. like phone can be optional but if it has value, the value  must be 10 character. in this case "" is not undifined but user dont enter any value and make field empty and give 10 character validation error

**Comment by crhistianramirez** [comment]
So you're asking for a conditional validation rule? Wouldn't this be more of a feature request on the Zod validation library side of things and not a concern of react-hook-form?

**Comment by bluebill1049** [comment]
perhaps you can just use `valueAs` instead, but `undefined` is a limitation because we support inline defaultValue and defaultValues, in which undefined is used to fallback to useForm defaultValues

**Comment by VivoCyber** [comment]
> So you're asking for a conditional validation rule? Wouldn't this be more of a feature request on the Zod validation library side of things and not a concern of react-hook-form?

hi 
i handle this with setValue in each optional field : 
(value)=> {
     if(value==="") return undefined;
     else return value;
}
but i think it can be  helpfull or pherhaps not :)
