### ISSUE TITLE
Removing a field array field breaks validation

### ISSUE THREAD

**Issue by tomas-c** [react-hook-form/react-hook-form#1026]
**Describe the bug**
When using useFieldArray, if you append a field with invalid value and subsequently remove it, then formState.isValid gets stuck with `false` value.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-dirty-state-with-empty-string-rle9z
2. Observe isValid=true
3. Append a field
4. Remove the appended field
5. Observe isValid=false

**Additional context**
 - Version 4.9.3

**Comment by tomas-c** [comment]
Just did more testing, this bug is not present in 4.8.2

**Comment by bluebill1049** [comment]
thanks @tomas-c will investigate into this.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-dirty-state-with-empty-string-wojle

please help test out this fix.
