### ISSUE TITLE
issue: Arrays in the form state inherit methods defined on Array.prototype

### ISSUE THREAD

**Issue by ioev** [react-hook-form/react-hook-form#10263]
### Version Number

7.37.0

### Codesandbox/Expo snack

https://codesandbox.io/s/runtime-breeze-u7xk2g?file=/src/App.js

### Steps to reproduce

1. Have some code somewhere else in the project that adds a method to Array.prototype
2. Put an Array into the form state
3. See how this prototype method becomes defined on the Array itself
4. Watch serialization attempts fail (like serializing values to push into the history)

I should note this behaviour started in version 7.37.0, and persists in the most recent version.

### Expected behaviour

1. New methods defined on the prototype should not be explicitly defined on the Arrays in the form state

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
This is the error when you try to put the values object into the history.

Failed to execute 'replaceState' on 'History': function () {
  return true;
} could not be cloned.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Thanks for the issue report. This sort of edge case I wouldn't have time or effort to look into, if this is a serious use case for your app, please ping the old version or fork the repo to amend or perhaps send a PR I will take a look at it.
