### ISSUE TITLE
A new public API for obtaining "fill status" of a form field

### ISSUE THREAD

**Issue by risenforces** [react-hook-form/react-hook-form#10270]
**Is your feature request related to a problem? Please describe.**

There is often a need to obtain the "fill status" of a form field, for example, to perform some visual effects. Here is an example of one such situation:

https://user-images.githubusercontent.com/35740512/232076719-0f1b607d-c681-4483-a81d-a01b022fec62.mp4

<br>

The first thing that comes to mind is to use `isDirty` / `formState.dirtyFields`. But this approach does not work in a situation where this field is not initially empty in `defaultValues`. In this case, the field will not be "dirty", but it will have a value. In the example above, if we rely on `dirtyFields`, the elements will simply overlap each other, and we will get a visual defect. Moreover, visually, the field will think that it has a value if the user erases the default value and leaves an empty string there.

Thus, it is also necessary to take `defaultValues` into account. After adding the check, the algorithm will be as follows:

1. Check if the field is initially empty.
2. The field is empty:
   2.1. Check the field in `formState.dirtyFields`. If it is "dirty", it means that it is not empty at the moment.
3. The field is not empty:
   3.1. Look at `formState.dirtyFields`. If the field is "dirty", it could mean that it is either empty or has any value different from the initial one. Based on this information, we cannot determine whether the field is currently empty.
   
So, in case of a non-empty default value, it is impossible to determine for sure whether the field is currently empty using `formState` and `defaultValues`.

**Describe the solution you'd like**

To solve the problem, I used `watch`, as `useWatch` is not suitable - it would cause many unnecessary re-renders, and I wanted to get a solution that triggers a re-render only if the "filled" state of the field has changed.

The final code looks like this:

```ts
function isNotEmpty<T>(object: T, path?: string): boolean {
  const value = get(object, path)
  if (typeof value === 'object') return Object.values(value).some(Boolean)
  return Boolean(value)
}

export function useFilled<
  TValues extends FieldValues,
  TPath extends FieldPath<TValues>
>(form: UseFormReturn<TValues>, path: TPath): boolean {
  const [defaultFilled] = useState(() =>
    isNotEmpty(form.formState.defaultValues, path)
  )

  const filledRef = useRef<boolean>(defaultFilled)
  const forceUpdate = useForceUpdate()

  useEffect(() => {
    const subscription = form.watch((values, info) => {
      if (!info.name?.startsWith(path)) return

      const isEmpty = isNotEmpty(values, path)

      if (isEmpty !== filledRef.current) {
        filledRef.current = isEmpty
        forceUpdate()
      }
    })

    return () => subscription.unsubscribe()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [path])

  return filledRef.current
}
```

Usage example:

```ts
const form = useForm(...)

const filled = useFilled(form, 'card.expiration.month')
```

I suggest adding something like that. As I see, it's possible to use internal `watch` from `control` to do the same. The problem is non-string fields (boolean for example), and I don't know how to deal with them, that's why I didn't open a pull request.

I hope that what I have described will help to add a similar API to the library, so that users do not have to write their own cumbersome logic using `watch`. Thanks!

**Comment by bluebill1049** [comment]
I don't think we will build this as part of our library, feel free to extend that functionality at your own app level.

**Comment by risenforces** [comment]
> I don't think we will build this as part of our library, feel free to extend that functionality at your own app level.

I'm sorry, but this is a terrible approach. Saving 100 bytes that creates inconsistency among projects, potential form bugs (because not everyone has the level of understanding to write such code).
