### ISSUE TITLE
`onBlur` in react-hook-form 4

### ISSUE THREAD

**Issue by shevchuk-digicode** [react-hook-form/react-hook-form#1027]
Thanks for the great framework! I have the next question: 

What happens with `onBlur` mode in `react-hook-form@4.0.0`? 

In version `react-hook-form@3.29.4` I'm able to trigger `errors` update by blurring the inputs - https://codesandbox.io/s/react-hook-form-defaultvalues-y4iq5?fontsize=14&hidenavigation=1&theme=dark
Also, after clicking on Submit the `errors` update even on changing the input value, that looks convenient.

Unfortunately, in `react-hook-form@4.0.0`, the `errors` don't update on input blurring. 
https://codesandbox.io/s/react-hook-form-defaultvalues-utgyb?fontsize=14&hidenavigation=1&theme=dark
In this mode, it only fires `validate` on blurring, but even I return `false` from `validate,` the `errors` don't update. 

BTW, is there some chance to show error on `onBlur` event?

**Comment by shevchuk-digicode** [comment]
I've updated the links, the first time they were incorrect. Sorry about that.

**Comment by stramel** [comment]
@shevchuk-digicode Can you provide the following:

- the steps that you are performing to generate the behavior in question
- the expected result and the actual result for each

I'm not quite sure what you're saying is the issue. At quick glance in the CSBs, they look to perform the same way.

**Comment by shevchuk-digicode** [comment]
Here is the simpler version of my second CSB - https://codesandbox.io/s/react-hook-form-defaultvalues-tfsyu?fontsize=14&hidenavigation=1&theme=dark

**Here I set**:
-  `onBlur` mode 
- `ref={register({required: true})}` - for both inputs
-  `useEffect` for `errors` object to debug in console the changing of its state

**My behavior**: 
- I focus on the first input 
- Press `tab` for blurring from the first input and focusing on the other one 

**My expectations**:
I expect that the `errors` object should change immediately and I will notice it in the console (because of `required` validation type of the inputs). This is the actual behavior in `react-hook-form@3.29.4` but I haven't found anything about it in breaking changes report of `@4.0.0` release.

**Actual result**:
The `errors` updates only after clicking on the submit button. The same as `onSubmit` mode.

**Comment by bluebill1049** [comment]
it is changing in the render, if you console log the errors.

**Comment by shevchuk-digicode** [comment]
@bluebill1049 Wow, it's even simplified my code) Thank you!
