### ISSUE TITLE
issue: Fields ids have never type

### ISSUE THREAD

**Issue by sarink** [react-hook-form/react-hook-form#10288]
### Version Number

7.43.5

### Codesandbox/Expo snack

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoUSWOAbzgFcBnJAMWCQBsATAQSigoAngBpGLVtDwBfONlwEi6GAFoAFhAgBrFZilly5GELBI4kqCABqKTgyRM4AXjrk47uKYhhOSAFxw-IJCADz0wNwBAHYMIABGSFCkcFEoIP5wTDBQwFEA5nDSAHwU0oZoEFFZcABySABuiRZ4LgAUAJTORa4ecBVV8PT92RCchc7ibFIhzTZ2DkUdFL391fSYHDyOsi7MbJt8AsKtQ5UjnGKp6QH4Xj5I+IXtbh6rWAcAktyOLhtc3wA6EAoMCtP48LpyA4AiLtZIAenhKQaiQA2gBdF7uIgwBhQKIpBicTilIA

### Steps to reproduce

```
import React from 'react';
import { useFieldArray, useForm } from 'react-hook-form';

type FormValues = {
    people: Array<{ id: number; name: string }>;
}

const NeverForm = () => {
    const { control } = useForm<FormValues>();
    const { fields } = useFieldArray({ control, name: 'people' })
    const fieldIds = fields.map(field => field.id); // never[]
    return null;
}
```

### Expected behaviour

`fieldIds` should be of type `number[]`.

It looks like the library is is overriding the original id with an autogenerated uid (so if you were, for example, trying to see a list of already selected people, the ids are lost). Passing a `keyName` of some key that doesn't exist in the dataset moves the autogenerated uid to that key, preserving it. Is this intentional?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Have you tried to change the `keyName`?

**Comment by sarink** [comment]
@bluebill1049 Yeah, I mentioned this in the original post:

> Passing a keyName of some key that doesn't exist in the dataset moves the autogenerated uid to that key, preserving it. Is this intentional?

**Comment by bluebill1049** [comment]
Because with uncontrolled input key name is required, which we are consider to rename to `key` instead of `id` in the next major version.

**Comment by sarink** [comment]
I would still advocate for a more collision-proof name, but, makes sense, thank you for the explanation!
