### ISSUE TITLE
issue: setValue doesn't trigger dirtyFields

### ISSUE THREAD

**Issue by mtt87** [react-hook-form/react-hook-form#10294]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-testing-pwjx9w?file=/src/App.tsx

### Steps to reproduce

I've added everything to the codesandbox.

## Main issue

I would expect that this code should trigger the `dirtyFields`.
At the moment it doesn't seem like it's triggering it, despite the fact that the input field has changed.

```ts
useEffect(() => {
  setTimeout(() => {
    setValue("field1", "potato");
  }, 3000);
}, [setValue]);
```

## Question to better understand

Shouldn't also the difference between the `defaultValues` and the `values` be the dirty fields?
In my example I'm expecting `field1` to be considered dirty because the default value is an empty string, and the current value is "test".

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/useform/setvalue/

`{ shouldDirty: true }`
