### ISSUE TITLE
Typescript: When useForm generic is not typed, the property 'message' doesn't exists in type FieldErrors[]

### ISSUE THREAD

**Issue by bpallares** [react-hook-form/react-hook-form#1030]
**Describe the bug**
This Issue is very similar to what it is described in #987, however, in this case, the `useForm` generic has no typings. 
  
**Codesandbox link**
https://codesandbox.io/s/charming-shaw-klux0?from-embed

**Expected behavior**
It should probably default to `any` if no types are passed

**Screenshots**
![IMG1](https://imgur.com/3wbzji2.jpg)
![IMG2](https://imgur.com/9KKjuMo.jpg)

@stramel

**Comment by stramel** [comment]
Seems related to #987 and my second point in #953.

@bluebill1049 I will see if I can get some time to address these issues.

**Comment by bluebill1049** [comment]
awesome thanks @stramel This is duplicated. let's tackle that in the other issue.

**Comment by stramel** [comment]
@bluebill1049 It isn't really duplicated but related. I'm fine with tracking it in the other issue just as long as we cover both scenarios.

**Comment by bluebill1049** [comment]
Oh if that’s the case that’s reopen it.

**Comment by bluebill1049** [comment]
nvm let's track on the same ticket as this is probably going to need help from @stramel
