### ISSUE TITLE
TypeScript: Types for ErrorMessage.As do not accept React.FC<> as valid input.

### ISSUE THREAD

**Issue by IronSean** [react-hook-form/react-hook-form#1031]
**Describe the bug**
The type definitions for the ErrorMessage components `as` prop no longer allow a component of type `React.FC` to be passed in. Instead it throws a type error.

**To Reproduce**
1. Pass a React.FC to the as paramater of `ErrorMessage`

**Codesandbox link**
https://codesandbox.io/s/pensive-platform-56byt

**Expected behavior**
Being able to pass in your own custom components should be possible with the ErrorMessage component.

**Screenshots**
![image](https://user-images.githubusercontent.com/1960190/74476568-f7987b80-4e7f-11ea-8d60-20bc6870c325.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Typescript: 3.7.5
 - VSCode

**Comment by bluebill1049** [comment]
hey @kotarella1110 you want to take a look this one?

**Comment by kotarella1110** [comment]
@bluebill1049 yes! i'll look into it.
