### ISSUE TITLE
issue: isDirty causes re-render of whole form when using useFieldArray

### ISSUE THREAD

**Issue by kiocosta** [react-hook-form/react-hook-form#10312]
### Version Number

5.11.15

### Codesandbox/Expo snack

https://codesandbox.io/s/gifted-gauss-mgzugi?file=/src/App.js

### Steps to reproduce

1. Open the sandbox
2. Click in any checkbox and notice an additional re-render when form changes from clean to dirty and vice-versa
3. This seems to happen only when using useFieldArray, I believe the problem may have to do with array reference changing.

### Expected behaviour

isDirty shouldn't trigger re-render of every form field, should it?
I have a form with 96 fields and this is causing some performance issue in my application

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Expected behaviour, if re-render at root is not desired, use `useFormState`
