### ISSUE TITLE
Ability to set undefined as the default value of an optional field which is of type File | undefined

### ISSUE THREAD

**Issue by danielmarcano** [react-hook-form/react-hook-form#10325]
**Is your feature request related to a problem? Please describe.**

I have encountered an issue regarding `defaultValues` of type `File`, and how to reset them.

When we set `File` as the default value of a controlled field, and then try to reset such field by passing `undefined` to its onChange handler, the field gets reset back to the original `File` default value, instead of becoming empty.

Here's a [codesandbox](https://codesandbox.io/s/awesome-hertz-88hhwb?file=/src/App.tsx:2276-2362) in which you can reproduce the issue.

I know that the [documentation](https://react-hook-form.com/api/useform/#defaultValues) of the `defaultValues` explains that:

"You should avoid providing undefined as a default value, as it conflicts with the default state of a controlled component."

Nonetheless, passing `null` to the `onChange`, **which does work**, forces us to change our types and our Yup's schema so that our form considers `null` a valid empty value, given that our field is optional.

So instead of doing this:

```ts
export type AvatarForm = {
  avatar?: File;
};

const formSchema: Yup.Schema<AvatarForm> = Yup.object().shape({
  avatar: Yup.mixed<File>(),
});
```

We would have to do this:

```ts
export type AvatarForm = {
  avatar?: File | null;
};

const formSchema: Yup.Schema<AvatarForm> = Yup.object().shape({
  avatar: Yup.mixed<File>().nullable(),
});
```

Which ties our types to a limitation of React Hook Form.

**Describe the solution you'd like**

I would like to be able to send `undefined` to a field whose original default value was a `File`, and that it becomes empty, as I don't want to use `null` since that value and type is only necessary due to this React Hook Form limitation.

**Describe alternatives you've considered**

The only alternative I have seen so far is to use `null`, although it is not desirable, since it forces me to modify my types with no added value or need other than to satisfy React Hook Form's defaultValues limitation.

**Additional context**

Even though I have stated that I would like this for fields whose original default value is of type `File`, I understand that this happens with any other fields and their original default values.

If we try to set them to `undefined`, they will be set back to their original default value, no matter whether it was of type `File` or not.

**Comment by bluebill1049** [comment]
This is a design limitation at the moment unless we completely remove inline defaultValue/defaultChecked support for all the custom hooks, which I think some users would find a pain to deal with. Personally, I would love to support undefined, but it's a community project now, so it would be a rather tricky decision to make. quick example reference: https://github.com/react-hook-form/react-hook-form/blob/master/src/useController.ts#L60

**Comment by danielmarcano** [comment]
Hi, @bluebill1049 thanks for such a fast response!

I understand it would be tricky to implement this... so, in short, using null is the only alternative in this case, right?

**Comment by bluebill1049** [comment]
Yes @danielmarcano unless we remove the inline defaultValue support for all the hooks.
