### ISSUE TITLE
issue: Nested field array not working properly

### ISSUE THREAD

**Issue by dd-jonas** [react-hook-form/react-hook-form#10335]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://stackblitz.com/edit/react-ts-vfrtmk?file=App.tsx

### Steps to reproduce

Two different flows that show what's wrong:

1. Open the Stackblitz reproduction
2. Delete the first section
3. Notice that some lines of the first deleted section are now on the second section.
 
or

1. Open the Stackblitz reproduction
2. Delete all lines of the first section
3. Delete the first section
4. Notice that the lines of the second section are gone as well (visually, the state still shows it)
5. Add a line to the section
6. Notice that the invisible line of step 4 is back, and there are now two lines

### Expected behaviour

Each section should keep their related lines.

I'm having a hard time debugging this, but I think it might be related to this part using the index of the array?

```
const lines = useFieldArray({
  control,
  name: `sections.${sectionIndex}.lines`,
});
```

Although I would expect this to work, as the lines should get the deleted if the parent section gets deleted. It seems that it sticks around somehow.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
```
const lines = useFieldArray({
  control,
  name: `sections.${sectionIndex}.lines`,
});
```

If you are expecting the latest value from useFeidlArray then it won't, use `watch` or `useWatch` API insetead.

**Comment by dd-jonas** [comment]
I'm not sure if I understand this. I added a `useWatch` call and used the watched lines in my loop (`watchLines.map` instead of `lines.fields.map`) but that doesn't seem to fix it.

https://stackblitz.com/edit/react-ts-dvagrz?file=App.tsx

**Comment by dd-jonas** [comment]
Figured out I was missing the key prop whoops. Still running into some error handling related issues, but that's not related to this one so I'll close it.
