### ISSUE TITLE
issue: `useFieldsArray` adding to parent

### ISSUE THREAD

**Issue by deskoh** [react-hook-form/react-hook-form#10339]
### Version Number

7

### Codesandbox/Expo snack

https://codesandbox.io/s/usefieldarray-promotion-ivq34u

### Steps to reproduce

1. Go to 'https://codesandbox.io/s/usefieldarray-promotion-ivq34u'
2. Click on 'Promote First Child' to move textbox `2` to parent
3. Textbox `2` is removed.
4. Click `Append Parent`. The 'promoted' child now then appears.

### Expected behaviour

Textbox `2` should appear after step 2.

The parent fields are not causing correct re-rendering when it is changed via another `append` or `update` from another `useFieldsArray` hook for the same name.

How do I force the parent to re-render?

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
```
remove(0);
const parent = getValues("test");
replaceParent([...parent, childToPromote]);
```

I don't think we support your current usage.
