### ISSUE TITLE
issue: Initialization and reset behaviors do not work properly when the root of the form fields is an array.

### ISSUE THREAD

**Issue by xxwwp** [react-hook-form/react-hook-form#10334]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/sleepy-bardeen-gh1itb

### Steps to reproduce

- Clicking the reset button does not work.
- The initial value is invalid.
- Clicking the reset button after entering data does not work.
- In the case of nested arrays, resetting may even set all registered fields to empty strings instead of deleting them. This sandbox cannot demonstrate that.

### Expected behaviour

- When `defaultValues` is provided as an array, `form.getValues()` should return an array, but currently it only returns an object.
- `form.reset()` works correctly when the parameter is an array.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Please use `useFieldArray` for such an operation and don't think we support such a key or input name as `0.xxx'

**Comment by xxwwp** [comment]
> Please use `useFieldArray` for such an operation and don't think we support such a key or input name as `0.xxx'

Translation:

So when the root of the form is an array, I can only set the form data to an object?

For example:

```tsx
interface Item {
  field: string;
  // other
}

interface Fields {
  root: Item[];
}

useForm<Fields>();
```

Also, I didn't express myself clearly enough. `useFieldArray` cannot meet the requirements of the scenario I described. I need to get data in `useEffect` and use `resetForm` to initialize the form. There are dynamic array structures in some deep child fields, and the form data type is similar to:

```tsx
interface Item {
  foo: string;
  childrenArrayField: string[]; // dynamic array
}

interface Field {
  root: Item[];
}
```

I need to dynamically add the `childrenArrayField` of a certain `Item` type field. However, `useFieldArray` does not support dynamic names, so I can only use `setValue` instead of `useFieldArray`.

**Comment by xxwwp** [comment]
> Please use `useFieldArray` for such an operation and don't think we support such a key or input name as `0.xxx'

So when the root of the form is an array, I can only set the form data to an object?

For example:

```tsx
interface Item {
  field: string;
  // other
}

interface Fields {
  root: Item[];
}

useForm<Fields>();
```

Also, I didn't express myself clearly enough. `useFieldArray` cannot meet the requirements of the scenario I described. I need to get data in `useEffect` and use `resetForm` to initialize the form. There are dynamic array structures in some deep child fields, and the form data type is similar to:

```tsx
interface Item {
  foo: string;
  childrenArrayField: string[]; // dynamic array
}

interface Field {
  root: Item[];
}
```

I need to dynamically add the `childrenArrayField` of a certain `Item` type field. However, `useFieldArray` does not support dynamic names, so I can only use `setValue` instead of `useFieldArray`.

**Comment by xxwwp** [comment]
> Please use `useFieldArray` for such an operation and don't think we support such a key or input name as `0.xxx'

So when the form root is an array, I can only take the option of setting the form's data as an object?

For example:

```tsx
interface Item {
  field: string.
  // other
}

interface Fields {
  root: Item[].
}

useForm<Fields>().
```

Also, I didn't express myself clearly enough, `useFieldArray` doesn't work for the scenario I described, I need to get the data asynchronously and execute `resetForm` to initialize the form with a deep sub-level dynamic array, and the form data type is similar to

```tsx
interface Item {
  foo: string.
  childrenArrayField: string[]; // dynamic array
}

interface Field {
  root: Item[].
}
```

I need to dynamically add a `childrenArrayField` for an `Item` type field, but `useFieldArray` doesn't support dynamic names, so I have to use `setValue` instead of `useFieldArray`.
