### ISSUE TITLE
issue: Field validation not working for controlled components used in `useFieldArray` 

### ISSUE THREAD

**Issue by razvanip** [react-hook-form/react-hook-form#10331]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-jcik9j?file=/src/index.js

### Steps to reproduce

1. Add 2 items
2. Click on Validate. Only last inserted item shows the validation error.
3. Second click on validate validates all fields

But if we `subscribe` with watch for changes `the array field` validations seems to be triggered for all items in the array.

### Expected behaviour

Should validate correctly

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks @hekatx in advance :)

**Comment by razvanip** [comment]
seems like `7.30.0`->. `7.31.0` introduced the bug, hope it help. I'll also try to have a look today.

Cloned and `7.44.0-rc.2` seems fine in `tests`

**Comment by razvanip** [comment]
@hekatx sorry missed your comment

**Comment by bluebill1049** [comment]
`7.44.0-rc.2` fixes the issue?

**Comment by razvanip** [comment]
> `7.44.0-rc.2` fixes the issue?

sorry, i cloned and did not saw the prev comment, and did not check the peer dep in the project for react `18`. But i think problems is still there.

Weird it works on 18 and not 16. Might `batching` have something to do with it ?

**Comment by nina-alin** [comment]
Same problem here, but i'm not sure if the issue is caused by react hook form itself or the usage with zod.

**Comment by bluebill1049** [comment]
looks like the latest code is working: https://codesandbox.io/s/react-hook-form-usefieldarray-forked-v89743?file=/src/index.js i forked the last commit from the repo
