### ISSUE TITLE
submit on blur without extra render 

### ISSUE THREAD

**Issue by yiminghe** [react-hook-form/react-hook-form#10340]
**Is your feature request related to a problem? Please describe.**
submit form when any of its input blurs

**Describe the solution you'd like**
current solution needs to modify internal state through control, it is better to provide some public apis

https://codesandbox.io/s/submit-on-blur-qkr7st

**Comment by yiminghe** [comment]
> curious to know what's the extra render brought to your app?

example updated.

check https://codesandbox.io/s/submit-on-blur-qkr7st?file=/src/App2.tsx

**Comment by bluebill1049** [comment]
Thanks for the example, what's hurting your app by that extra re-render?

**Comment by yiminghe** [comment]
> Thanks for the example, what's hurting your app by that extra re-render?

Just technical discussion, avoiding extra render is always a goal, is it not?

**Comment by bluebill1049** [comment]
I think we are trying to avoid constant re-render if possible not state update (re-render), especially trying to measure the performance impact before we go for the extreme. State update (re-render) is usually great. I will park to the feature request column in the project but most likely this feature will probably not going to be implmented.
