### ISSUE TITLE
issue: Controller rules don't get updated properly

### ISSUE THREAD

**Issue by TobiasKrahn** [react-hook-form/react-hook-form#10344]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/young-river-fqo0hs?file=/src/App.tsx

### Steps to reproduce

when changing the rules of a controller from 
```
{
  required: "field is required"
}
```
to 
```
{}
```
the required rule will still be active.
only changing it to 
```
{
  required: false
}
```
does work.

Steps in Codesandbox:
1. Uncheck the required checkbox
2. Click on the submit button
3. controller1 will still have a active required validation

### Expected behaviour

There shouldn't be a active rule after setting the rules to
```
{}
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
As expected, please use the value toggle instead. We saved quite a few bytes without supporting the omit.

**Comment by jerlam06** [comment]
@bluebill1049 Hi, I want to achieve the same thing, what is the value toggle thing you are talking about please?

**Comment by Moshyfawn** [comment]
> @bluebill1049 Hi, I want to achieve the same thing, what is the value toggle thing you are talking about please?

Simply update `required: true` to `required: false` instead of omitting the `rules` value
