### ISSUE TITLE
issue: setValue() doesn't seem to update when invoked just before handleSubmit

### ISSUE THREAD

**Issue by PraveenPeri** [react-hook-form/react-hook-form#10354]
### Version Number

7.26.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-controller-forked-tdwbko?file=/src/index.js

### Steps to reproduce

1. Go to the above sandbox
2. Click on 'Submit' button 
3. See that the field "numberFormat" is updated with a new value set via setValue() from inside the validate rule in the `<Controller/>` but the submit data still had the old data

### Expected behaviour

Expecting that handleSubmit() gets the updated value through setValue in the validate method. This might be non-typical use-case but we need to do something like this in our application. 

### What browsers are you seeing the problem on?

Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Could you please double-check your codesandbox and keep it minimal and focus on the issue?
![Screenshot 2023-04-28 at 1 22 28 pm](https://user-images.githubusercontent.com/10513364/235046818-b35c6383-8ec9-47e0-9fe4-6e47759b40e6.png)

**Comment by PraveenPeri** [comment]
Sorry about that! I fixed it now. However, I now realize this may not necessarily be an issue but a question. If I want to update value of a field from inside validate() function(or any other way) while the form is being submitted, is that possible? I know the question sounds bizarre but my use-case is that complex

**Comment by bluebill1049** [comment]
why not do a value transform inside validate function and `validate?

**Comment by PraveenPeri** [comment]
Could you elaborate with a code sample? How do you transform the value and update it in the handleSubmit?

**Comment by bluebill1049** [comment]
> Could you elaborate with a code sample? How do you transform the value and update it in the handleSubmit?

No, that's not possible.

**Comment by PraveenPeri** [comment]
Yeah, I figured that. I will try to think of what can be done in our code to workaround this. Thanks for your help!
