### ISSUE TITLE
watch('useFieldArrayName') not triggering for first row

### ISSUE THREAD

**Issue by AndreasZeiser** [react-hook-form/react-hook-form#1035]
**Describe the bug**
We use `watch('useFieldArrayName')` to watch for changes in the fields created by `useFieldArray`. Since `react-hook-form` version `4.8.1` `watch()` doesn't trigger for changes in the fields of the first row. It does trigger for changes after adding a second row.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-6psk5
2. Click on Add
3. Select Custom in the description field
4. Click again on Add
5. Now you should see a 2nd row. The first row contains now a custom field.
6. Select Custom in the description field of the 2nd row
7. You should now see the custom field in the 2nd row -> This should have been the expected behaviour for the first row.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-6psk5

**Expected behavior**
 `watch('useFieldArrayName')` should trigger for every change in the fields created by `useFieldArray`.

**Additional context**
In the Codesandbox linked above if you set the version of  `react-hook-form` to `4.8.0` it works as expected.

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report. please help verify the fix: https://codesandbox.io/s/react-hook-form-usefieldarray-jqptw

**Comment by bluebill1049** [comment]
Fix is merged: https://github.com/react-hook-form/react-hook-form/commit/4142c55fcf447b8f2d7f69e51d08f7dd8e282885

**Comment by AndreasZeiser** [comment]
Thank you for the fix! I can verify that the changes result into the expected behaviour.

**Comment by bluebill1049** [comment]
sweet thanks @AndreasZeiser will release the patch tmr.
