### ISSUE TITLE
issue: Checkboxes value turned into false without any trigger

### ISSUE THREAD

**Issue by gidgudgod** [react-hook-form/react-hook-form#10369]
### Version Number

7.39.2

### Codesandbox/Expo snack

https://codesandbox.io/s/checkbox-react-hook-form-bug-8m6d2s?file=/src/App.tsx

### Steps to reproduce

1. Go to [https://codesandbox.io/s/checkbox-react-hook-form-bug-8m6d2s?file=/src/App.tsx](url)
2. Play with the checkbox group
3. Bug: Checkbox group parent won't trigger its childs
4. Bug: In this sandbox the options comes from static data, but in my case the options data come from API so the first options state would be empty and then will be supplied with the data (so min 2x render). Idk why in my case the first page load show the wrong display of the checked boxes. And when I inspect with watch(), the values of the checkboxes all become false at the very last console.log(), even though the initial options value is not false.

So according to the sandbox, my main purpose is I'm trying to make a reuseable checkbox group component with react-hook-form that can render dynamic options. But turned out many bugs happened, I wonder if I did it correctly or not.
Please anybody help, big thanks :D

### Expected behaviour

Checkbox group working correctly with supplied initialValues, as well shows the correct checked display when interacting with it or when the page first load.

### What browsers are you seeing the problem on?

Firefox, Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Please provide a reasonable code sandbox related to your problem instead of dump a whole project with lots of side effect 
<img width="621" alt="Screenshot 2023-05-04 at 10 05 43 am" src="https://user-images.githubusercontent.com/10513364/236076603-2e4fc195-eebb-4a2f-9c5c-3ae70427f6b8.png">

**Comment by gidgudgod** [comment]
> Please provide a reasonable code sandbox related to your problem instead of dump a whole project with lots of side effect and remove irrelevant code as well. thanks <img alt="Screenshot 2023-05-04 at 10 05 43 am" width="621" src="https://user-images.githubusercontent.com/10513364/236076603-2e4fc195-eebb-4a2f-9c5c-3ae70427f6b8.png">

I've done a little clean up on my sand box, however I don't put my whole project there, in this sand box I already just take how I create the Checkbox Group and how I use it. 
And from your screenshot, that's how the checkbox group display indeterminate state depends on its child.

**Comment by bluebill1049** [comment]
I would build it differently, all those check-all or uncheck single checkboxes should be a component-level responsibility. React hook form's `Controller` or `useController` should be only there to collect and validate the value. If you can reproduce an codesandbox solo related to hook form `useController` or `Controller` behaviour then we can look into a fix.

**Comment by Chandan9898Kumar** [comment]
@gidgudgod  could you explain it better, might work on it

**Comment by Moshyfawn** [comment]
I'd argue, your `CheckboxGroup` implementation details shouldn't be tied into RHF. Take a look at how components like [MUI `Checkbox`](https://mui.com/material-ui/react-checkbox/#indeterminate) approach composing this API; the only "public" API is to **set** _(`value`)_ and **receive** _(`onChange`)_ you can easily connect to RHF `Controller`

**Comment by gidgudgod** [comment]
> I would build it differently, all those check-all or uncheck single checkboxes should be a component-level responsibility. React hook form's `Controller` or `useController` should be only there to collect and validate the value. If you can reproduce an codesandbox solo related to hook form `useController` or `Controller` behaviour then we can look into a fix.

As suggested from @bluebill1049 eventually I revamped my code to use Controller instead of using setValue to create my CheckboxGroup.
For now to create the CheckboxGroup I'm using MUI with RHF controller because it's easier to handle the indeterminate state, only downside is when customizing the style (limited but it's enough for now). Perhaps soon will try to combine vanilla input component with RHF controller (maybe anyone have a reference code to create this?), so I can fully customize the input style. Thank you so much for the help guys :D
