### ISSUE TITLE
issue: defaultValues not being cleared when calling remove from useFieldArray()

### ISSUE THREAD

**Issue by badams** [react-hook-form/react-hook-form#10371]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/awesome-leaf-4e4lwj?file=/src/App.tsx

### Steps to reproduce

1. Go to  [codesan](https://codesandbox.io/s/awesome-leaf-4e4lwj?file=/src/App.tsx)
2. Click on "Remove Alice" and "Remove Bob"
3. Click on "Add Person" two times
4. See that both people are pre-filled with the default data

### Expected behaviour

Would expect if I remove these rows from the form, then add new ones they should be blank, the only way I've found to override those default values is to provide values for each property like so:

```
append({name: "", age: 0})
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
<img width="961" alt="Screenshot 2023-05-04 at 9 28 24 pm" src="https://user-images.githubusercontent.com/10513364/236191290-a74b94ad-3564-4dae-9392-7a9c775f0fea.png">

Append input/inputs to the end of your fields and focus. The input value will be registered during this action.

Important: append data is required and not partial.

https://react-hook-form.com/api/usefieldarray/

**Comment by badams** [comment]
@bluebill1049 
I assume you are talking about the note `Important: append data is required and not partial.`,  from reading the documentation it's not clear what the implications of this mean, if my field type allows undefined properties I would have thought simply passing `{name: undefined, age: undefined}` or `{}` would work, but it leads to this behaviour

If this expected behavior, maybe the documentation could make this more clear, as its not very intuitive.
