### ISSUE TITLE
Set value of controlled component react-select using onCreateOption in fieldArray

### ISSUE THREAD

**Issue by hjaimee** [react-hook-form/react-hook-form#1037]
Hello,

I've been trying to set the value of my controlled component when using onCreateOption in a fieldArray. I am able to get it into my list of options but having trouble to set the value of this specific element.

**To Reproduce**
1. If you go to the React-Select element and type a new value
2. Click enter
3. The value will be set in the options but not in the input box.

I would like to be able to set the input (single value) when creating a new option. Please advise.

**Codesandbox link**

https://codesandbox.io/s/oncreateoption-react-hook-form-react-select-6yvqw

**Comment by bluebill1049** [comment]
you want to try `setValue` api at your handler?

**Comment by hjaimee** [comment]
Well I tried to sue setValue but this didn't work well. I couldn't find documentation on how to setValue when using fieldArrays, couldn't pass the appropriate key and value.

Basically I want to know how to achieve being able to create a new option, and that option being set in my input box? If you look at the codesandbox it creates the option, but I then I have to select the  element again and choose it from the options.

**Comment by bluebill1049** [comment]
Is this what you after? https://codesandbox.io/s/oncreateoption-react-hook-form-react-select-6yvqw

**Comment by hjaimee** [comment]
Is that the correct link or did you save your changes as I don't see anything different in the code and it's still not setting the value in the select input box.

**Comment by bluebill1049** [comment]
wrong link, try this one: https://codesandbox.io/s/oncreateoption-react-hook-form-react-select-6yvqw

**Comment by hjaimee** [comment]
Seems to be the same thing.

**Comment by bluebill1049** [comment]
something wrong with CSB today...

**Comment by bluebill1049** [comment]
what about this one: https://codesandbox.io/s/oncreateoption-react-hook-form-react-select-4uv18

**Comment by hjaimee** [comment]
Yes so the problem with that is I want to also see the this new option in the select dropdown, which is why I'm using the onCreateOption prop. The onCreateOption prop works well except it doesn't seem to set the select input value of my controlled component.

**Comment by bluebill1049** [comment]
why don't you do that inside onChange?

**Comment by hjaimee** [comment]
Well, I feel foolish, that works and not sure why I hadn't tried that first. Thanks for the feedback.

Great package btw, love react-hook-form
