### ISSUE TITLE
issue: `number` types in `select` fields cast to `string` types without type update

### ISSUE THREAD

**Issue by ajmcquilkin** [react-hook-form/react-hook-form#10378]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/damp-flower-9x0fd1?file=/src/App.tsx

### Steps to reproduce

1. Load Codesandbox
2. Change the value within the HTML `select` tag
3. Submit the form with the submit button
4. Check console to see that the `enumField` field changes from a `number` to a `string` while the data is always typed as a `FormInputType` type

### Expected behaviour

Thanks for your work on this project! I'm not sure exactly what the expected behavior for this should be, but as a user I would be expecting one of the following:

1. The form automatically converts the `string` type into a `number` internally (e.g., `parseInt`)
2. The form returns a modified type where the `number` field is a `string` (e.g., `{ enumField: string }`)
3. A compile error that tells the user why this use case is unsupported

I encountered this issue within Linux webview2, although this is not an option within the dropdown. I can replicate this within Firefox and Chromium.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
form updated: {enumField: 0}
form updated: {enumField: 0}
form updated: {enumField: "1"}
form updated: {enumField: "1"}
form updated: {enumField: "2"}
form updated: {enumField: "2"}
data {enumField: "2"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Native input will always return `string` by default, build a controlled component and wrapped with controller.
