### ISSUE TITLE
issue: 'Uncaught (in promise) TypeError: path.split is not a function' when validating nested Controller which name="name"

### ISSUE THREAD

**Issue by luania** [react-hook-form/react-hook-form#10372]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/hopeful-williams-gyrr8s?file=/src/App.js

### Steps to reproduce

just click on 'submit' button
<img width="259" alt="image" src="https://user-images.githubusercontent.com/5110993/236366478-09336dbc-48f1-41fa-a0ac-e46e1bb74844.png">

### Expected behaviour

can see 'user.name is a required field' after submit clicked

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Uncaught (in promise) TypeError: path.split is not a function
    at get (index.esm.mjs:69:1)
    at eval (index.esm.mjs:1994:1)
    at focusFieldBy (index.esm.mjs:542:1)
    at _focusError (index.esm.mjs:1994:1)
    at eval (index.esm.mjs:2023:1)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
We do not support nested `Controller` usage.
