### ISSUE TITLE
issue: validating rules in Controller doesn't apply correctly

### ISSUE THREAD

**Issue by evgeniyworkbel** [react-hook-form/react-hook-form#10390]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/rhf-rules-bug-kzltd1

### Some context info

I have a select with 2 options. Depending on its option it renders input for url / textarea. Each of inputs is wrapped in Controller with own validating rules. I'm going to serve value of this inputs in one field in react-hook-form state

### Steps to reproduce

1. Choose 'link' in select
2. Write any text in input below. Text except for valid url
3. Submit form
4. See error 'Invalid url'
5. Change select value to 'hint'
6. See plain text in input
7. Submit form
8. See the same error 'Invalid url'

### Expected behaviour

After changing select value, I expect that hook-form will validate input according to new rules

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

In React devtools I see that rules apply correctly: for 'link' select value - url validation, for 'hint' select value - text validation

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Same field rules don't get updated unless the field's unmounted. You can provide the `shouldUnregister: true` to `useForm` in order for the `Controller` to get re-registered.

**Comment by evgeniyworkbel** [comment]
> Same field rules don't get updated unless the field's unmounted. You can provide the `shouldUnregister: true` to `useForm` in order for the `Controller` to get re-registered.

yes, this is the solution. how does it get rid of value if user typed something? Now if user typed smth and switch select, the value is remained

**Comment by bluebill1049** [comment]
perhaps just write a dynamic `validate` function instead.

**Comment by sanduluca** [comment]
> > Same field rules don't get updated unless the field's unmounted. You can provide the `shouldUnregister: true` to `useForm` in order for the `Controller` to get re-registered.
> 
> yes, this is the solution. @Moshyfawn how does it get rid of value if user typed something? Now if user typed smth and switch select, the value is remained

This is because the value was copied to `formValues` and when new controller gets mounted it uses the value from `formValues` as default value. Here https://github.com/react-hook-form/react-hook-form/blob/master/src/useController.ts#L60-L64


Not sure if this is intended behaviour. Maybe @bluebill1049 can tell. Should not the value be cleaned when the `shouldUnregister` is true ? 
say here https://github.com/react-hook-form/react-hook-form/blob/master/src/useController.ts#L93-L99

**Comment by bluebill1049** [comment]
> This is because the value was copied to formValues and when new controller gets mounted it uses the value from formValues as default value. Here https://github.com/react-hook-form/react-hook-form/blob/master/src/useController.ts#L60-L64

Yes, expected for toggle input on and off conditionally. 

> Not sure if this is intended behaviour. Maybe @bluebill1049 can tell. Should not the value be cleaned when the shouldUnregister is true ?

Please refer to this issue: ✍️ close #10096 react strict mode with mounted field value (#10102), I am almost to certain `shouldUnregister: true` is troublesome and will be deprecated later on. use `unregister` at your own app level.

**Comment by sanduluca** [comment]
I got a little confused. I think `shouldUnregister` is a great feature, that should be enabled by default. More exactly there should be another option for keeping the value in the form state, say `keepValueOnUnregister`. I dont see use cases  where I would need a value from an 'unmounted'  component. I think a memory cleanup would be better default option (getting rid of unmounted component value, errors and rest).

Does having `shouldUnregister: true` and doing `unregister()` manually, makes double unregistration ? 


> Yes, expected for toggle input on and off conditionally.

As I said above, when you set `shouldUnregister: true` I expect that every thing about the field will be cleared. And will be better to have an option to keep the values between unregister and register for those `toggle input on and off conditionally`.

> use unregister at your own app level.

He cant use `unregister` because his toggle unregister one type of input and registers another. Using unregister in a useEffect can lead to a race condition. In his situation he needs to use `resetField` to clear everything when the `watchType` is changed

```tsx
  useEffect(() => {
    resetField("value");
  }, [watchType, resetField]);
```

**Comment by evgeniyworkbel** [comment]
#He cant use unregister because his toggle unregister one type of input and registers another. Using unregister in a useEffect can lead to a race condition. In his situation he needs to use resetField to clear everything when the watchType is changed

this solution only solves issue linked to cleaning typed value, not issue with applying rules correctly.

My solutiion is to extract and extend onChange event and inside of it unregister certain input:

```
<Controller
          name="type"
          control={control}
          render={({ field: { onChange, ...otherField }  }) => (
            <Select
              id="btnFunctionType"
              options={[
                {
                  label: "Link",
                  value: "link"
                },
                {
                  label: "Hint",
                  value: "hint"
                }
              ]}
              onChange={(v, opt) => {
                  onChange(v, opt);
                  unregister('value');
              }}
              {...otherField}
            />
          )}
        />
```

**Comment by xdebbie** [comment]
I am having the same issue after updating to the latest version. 

`shouldUnregister: true` did not work for me, so I just went back to the latest working version --> `7.41.1`. I have tested _all_ latest versions and it started breaking on `7.41.2`...

**Comment by bluebill1049** [comment]
> I am having the same issue after updating to the latest version.
> 
> `shouldUnregister: true` did not work for me, so I just went back to the latest working version --> `7.41.1`. I have tested _all_ latest versions and it started breaking on `7.41.2`...

https://github.com/react-hook-form/react-hook-form/releases/tag/v7.41.2 has no commit related to controller.

**Comment by bluebill1049** [comment]
Could you try this local version? https://codesandbox.io/s/rhf-rules-bug-forked-fp53no?file=/src/App.js

**Comment by bluebill1049** [comment]
any update on this issue? have you try the above codesandbox?

**Comment by ifndefdeadmau5** [comment]
> I got a little confused. I think `shouldUnregister` is a great feature, that should be enabled by default. More exactly there should be another option for keeping the value in the form state, say `keepValueOnUnregister`. I dont see use cases where I would need a value from an 'unmounted' component. I think a memory cleanup would be better default option (getting rid of unmounted component value, errors and rest).
> 
> Does having `shouldUnregister: true` and doing `unregister()` manually, makes double unregistration ?
> 
> > Yes, expected for toggle input on and off conditionally.
> 
> As I said above, when you set `shouldUnregister: true` I expect that every thing about the field will be cleared. And will be better to have an option to keep the values between unregister and register for those `toggle input on and off conditionally`.
> 
> > use unregister at your own app level.
> 
> He cant use `unregister` because his toggle unregister one type of input and registers another under the **same name**. Using unregister in a useEffect can lead to a race condition. In his situation he needs to use `resetField` to clear everything when the `watchType` is changed
> 
> ```tsx
>   useEffect(() => {
>     resetField("value");
>   }, [watchType, resetField]);
> ```

Can't agree more, obviously this whole turn back to the imperative API thing is ridiculous and really going plenty of steps backward. Now this update is breaking our whole existing application
