### ISSUE TITLE
Bug report: Cannot resolve dependency 'ts-polyfill/es2015-symbol' since v4.9.4

### ISSUE THREAD

**Issue by krnlde** [react-hook-form/react-hook-form#1039]
**Describe the bug**
After updating to `4.9.4` I immediatelly get this error on console:
```
×  [project_root]\node_modules\react-hook-form\dist\react-hook-form.ie11.js:7:8: Cannot resolve dependency 'ts-polyfill/es2015-symbol'
   5 | require('ts-polyfill');
   6 | require('ts-polyfill/es2015-iterable');
>  7 | require('ts-polyfill/es2015-symbol');
     |        ^
   8 | require('ts-polyfill/es2015-symbol-wellknown');
   9 | var React = require('react');
  10 |
```

**Additional context**
In my project I use the ie11 version of react-hook-form. This issue is probably related to the latest PR #1018

**Comment by bluebill1049** [comment]
@vova-bezhenar are you having a similar issue?

**Comment by kotarella1110** [comment]
I think the following lines need to be fixed.

https://github.com/react-hook-form/react-hook-form/blob/master/src/index.ie11.ts#L1-L4

```ts
import 'ts-polyfill';
import 'ts-polyfill/lib/es2015-iterable';
import 'ts-polyfill/lib/es2015-symbol';
import 'ts-polyfill/lib/es2015-symbol-wellknown';
```

**Comment by kotarella1110** [comment]
@vova-bezhenar By the way, why are you importing `ts-polyfill/lib/es2015-iterable` and `ts-polyfill/lib/es2015-symbol` and `ts-polyfill/lib/es2015-symbol-wellknown`? 
Is it no good importing only `ts-polyfill`?

> https://github.com/ryanelian/ts-polyfill
> <img width="903" alt="スクリーンショット 2020-02-17 10 11 13" src="https://user-images.githubusercontent.com/12913947/74616925-db415b00-516d-11ea-8e1d-5ae07982b5bb.png">

**Comment by bluebill1049** [comment]
worst case, we may need to revert that commit and patch this issue.

**Comment by kotarella1110** [comment]
> Also, we need to install [`ts-polyfill`](https://github.com/ryanelian/ts-polyfill) to use ie11 version of `react-hook-form`.
> If we want to bundle with `ts-polyfill`, we should remove it from `external` in rollup config.
> 
> https://github.com/react-hook-form/react-hook-form/blob/master/rollup.ie11.config.js#L14

@bluebill1049 `ts-polyfill` is [peer dependency](https://classic.yarnpkg.com/en/docs/dependency-types/#toc-peerdependencies). Is this within your expectation?
Also allow `ts-polyfill` to be included in the bundle?

**Comment by bluebill1049** [comment]
> Also allow ts-polyfill to be included in the bundle
hey @kotarella1110 we will not ship the lib with ts-polyfill bundle, i think we are better leave those to explain in the documentation. I will revert the commit tonight if i don't hear from @vova-bezhenar

**Comment by kotarella1110** [comment]
@bluebill1049 I agree with you 👍

**Comment by krnlde** [comment]
I agree too :)

**Comment by bluebill1049** [comment]
reverted :)

**Comment by vova-bezhenar** [comment]
@bluebill1049 Sorry for late response, yes these was a typo.
Over weekend I've checked that minimal list of polyfills to get 'react-hook-form' working on ie11 is just:
- 'ts-polyfill/lib/es2017-object';
- 'ts-polyfill/lib/es2015-promise';
Can we add these polyfills for ie11 build?

**Comment by krnlde** [comment]
We agreed on having these as `peerDependencies` so you'll have to add those to your project package.json

**Comment by bluebill1049** [comment]
hey @vova-bezhenar sorry to revert your change, but can we make it as what @krnlde suggested?

**Comment by dogusev** [comment]
@bluebill1049 
Actually `array.find` and `object.entries` makes the most pain.

I'd propose to update the code, to work without unsupported methods

Will it work for all?

**Comment by krnlde** [comment]
Mhm. Those methods improve the readability a lot. What's against including ts-polyfill in each project and leave the code as it is?

**Comment by dogusev** [comment]
@krnlde but they don't work in IE11 =)
Don't see the benefit of a pretty and readable, but not working code.

I'm pretty sure, that simple workaround, like additional method, which exposes the same result will not affect readability

**Comment by krnlde** [comment]
But but that's what polyfills there for?
