### ISSUE TITLE
issue: console error on setFocus function

### ISSUE THREAD

**Issue by AuthorProxy** [react-hook-form/react-hook-form#10392]
### Version Number

7.43.8

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-basic-forked-9wr1op?file=/src/index.js

### Steps to reproduce

1. Go to sandbox
2. Click on `select` label
3. See error

### Expected behaviour

There shouldn't be errors in console, if there are nothing to select just do nothing, like with booleans. I am working on inline editing and have the universal function that shows input and sets focus, selecting whenever it is possible, now it gives me console error on `select` fields, it would be mess to check which field should be selected or not.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
caught TypeError: elm.select is not a function
    at Object.select (useController.ts:144:1)
    at setFocus (createFormControl.ts:1235:1)
    at my-component.tsx:100:1
s
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
![Screenshot 2023-05-12 at 9 29 00 am](https://github.com/react-hook-form/react-hook-form/assets/10513364/ddf93426-7829-47c1-9ebb-d3ad0248715a)

Please check your csb, I couldn't find a select label.

**Comment by Moshyfawn** [comment]
@bluebill1049 I'm pretty sure they're talking about the "Is an developer?" label of the select element on line 60.

The error is due to the `setFocus` `shouldSelect` option usage on an element _(`select` in this case)_ that doesn't support [`.select()` method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select).

**Comment by Moshyfawn** [comment]
I'd argue, a runtime error like that is fine, as it would behave the same trying to call `.select()` on a `select` element in user-land

**Comment by bluebill1049** [comment]
thanks @Moshyfawn i will take a look at it 👍

**Comment by bluebill1049** [comment]
we will not swallow error with setFocus, if this is not desired the behaviour, you can add your own try and catch.

**Comment by hieunv1** [comment]
.
