### ISSUE TITLE
issue: shouldUnregister isn't working with resolver (yupResolver)

### ISSUE THREAD

**Issue by AntonyshynSerhii** [react-hook-form/react-hook-form#10394]
### Version Number

^7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/jovial-dew-yf0wiq?file=/src/App.tsx

### Steps to reproduce

1. Create a schema for yupResolver with 2 fields: 'product1' and 'product2'.
2. Create only 1 input and register it with 'product1'.
3. Click on submit button
4. In submit form data form you can see object with 2 fields: 'product1' and 'product2'

### Expected behaviour

I’m noticing that the resolver option seems to be overwriting the shouldUnregister option, even though they are supposed to be independent. I set shouldUnregister to true, but it is not taking effect, because when I trigger onSubmit function not only form registered fields are sent, but all fields that are in the schema. How I can avoid such behaviour? 

Has anyone else encountered this issue before, or have any suggestions on how to fix it? Or maybe it’s expected behaviour? Any help would be greatly appreciated. Thank you!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
I don't think resolvers ever worked in combination with `shouldUnregister: true`, but I can be wrong. @bluebill1049

**Comment by bluebill1049** [comment]
never support such usage, `shouldUnregister` was made to detect unmount input and remove the value from the submission.
