### ISSUE TITLE
issue: useFieldArray strips class properties from fields

### ISSUE THREAD

**Issue by paul-sachs** [react-hook-form/react-hook-form#10405]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-rules-forked-pyiufs?file=/src/index.js

### Steps to reproduce

1. Go to example
2. Click on "Append"
3. Notice the logs saying if the content returned by `useFieldArray` fields property satisfies "instanceof".

### Expected behaviour

The "fields" property should reflect the appended data without modification. This can be worked around with an additional `useController({ ... })` and using the returned value but that feels a little verbose.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
any chance to avoid `Class`?

**Comment by paul-sachs** [comment]
A little difficult. We serialize and deserialize our data using those classes. It's a little bit of a part of our company's jam.

**Comment by paul-sachs** [comment]
I kinda get it why the library adds the `id` field, but in my case, I know each field has a unique property and would like to opt out of the cloning.

**Comment by bluebill1049** [comment]
> I kinda get it why the library adds the id field, but in my case, I know each field has a unique property and would like to opt out of the cloning.

We do manipulate the object internally, so it's better to not mutate the original object. We may leave this as a design limitation.

**Comment by paul-sachs** [comment]
Yeah that's fair. I can get around with an extra `useController` on the same field which works fine, if clunky. Could we expose the original fields (unmodified) from `useFieldArray` as well? That way, I don't have to muck around with making another generic filled utility.

**Comment by bluebill1049** [comment]
`id` is probably the most important part for rendering correct inputs.

**Comment by paul-sachs** [comment]
Something seems to have broken my workaround for this. I had combined something like the following:

```tsx
const {
    field: { value: users },
  } = useController({
    name: "users",
    control,
    rules: {}
  });
  const { append: appendUser, remove: removeUser } = useFieldArray({
    control,
    name: "users",
  });
```

And iterated through the users for listing elements, but something between 7.44.3 at 7.51.0 broke this behaviour and they are no long synced. I understand why that might be the case, but this means that there's no way to use `useFieldArray` with class based objects. Nothing to do I guess, but just wanted to post in case someone else runs into this.
