### ISSUE TITLE
support string arrays or number arrays with append() 

### ISSUE THREAD

**Issue by nina-alin** [react-hook-form/react-hook-form#10406]
**Is your feature request related to a problem? Please describe.**

When working with arrays, i usually choose to use `useFieldArray()`. Unfortunately, the`append()` method currently only supports object arrays.  When the data is a `number` or a `string` array, working with `useFieldArray()` becomes more complicated than it is supposed to be. There's a trick here: https://stackoverflow.com/questions/71789910/react-hook-form-usefieldarray-for-an-array-of-strings-instead-of-objects
But it's frustating - and unmaintanable. 

**Describe the solution you'd like**
Make the `append()` method accept non-object arguments. 

For example : 

```
onClick{() => append(1)}
onClick{() => append("toto")}
onClick{() => append({"toto": "tata"})}
```

**Describe alternatives you've considered**
Create a new method for this specific use case. 

For example : 

```
onClick{() => appendNumber(1)}
onClick{() => appendString("toto")}
```

**Additional context**
I've never used `prepend()` or `insert()`, but the problem should be the same.

**Comment by bluebill1049** [comment]
This is a current design limitation. The key prop is essential for uncontrolled field array implementation, which we provide through object payload for each field array action.

**Comment by nina-alin** [comment]
Are they any recommanded alternatives for this limitation ?

**Comment by bluebill1049** [comment]
would i possible to do a mapping after the submission or form values?

**Comment by nina-alin** [comment]
It might seem logical to proceed that way, but that's not applicable in my case. I am building a complex form and fundamentally, I can't alter my onSubmit function.

I would be happy to share my code for further clarification, but unfortunately, I'm not allowed to do so as it's proprietary to my company.

If this is a design limitation and it can't be resolved, feel free to close this issue. However, I believe it would be beneficial to mention this issue and possible solutions in the documentation.

**Comment by bluebill1049** [comment]
> Does not support flat field array.

Is this what you refer to?

![Screenshot 2023-05-18 at 10 48 03 am](https://github.com/react-hook-form/react-hook-form/assets/10513364/5bd53f2b-5a6f-49c2-93a2-5b6ab9590eb1)
