### ISSUE TITLE
issue: `:invalid` pseudo selector not being triggered by form validation

### ISSUE THREAD

**Issue by LordZardeck** [react-hook-form/react-hook-form#10411]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/admiring-violet-6b6u8f?file=/src/App.tsx

### Steps to reproduce

1. Type in an invalid email address that is valid to native email input (example@localhost)
2. Note that validation error appears, but `:invalid` css styling NOT showing

### Expected behaviour

According to the docs for the `shouldUseNativeValidation` prop,

> This config will enable [browser native validation](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation). It will also enable CSS selectors :valid and:invalid making styling inputs easier. **_You can still use these selectors even when client-side validation is disabled._**

Maybe I'm misunderstanding, but this would seem to me that these selectors should be able to be used wether or not the props is enabled. I don't want to enable this prop, however, because I want my custom error styling, not the bubble popup the native browser shows.

<img width="509" alt="image" src="https://github.com/react-hook-form/react-hook-form/assets/1145989/1db28118-6afe-474a-b18d-728c433a82bb">

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Expected behaviour, only when you enable the native browser validation.

**Comment by LordZardeck** [comment]
> Expected behaviour, only when you enable the native browser validation.

The docs are a little confusing then, saying that "You can still use these selectors even when client-side validation is disabled". As far as I can test, you can't. So there's no way to utilize the `:invalid` selector and not have that popup window show?

**Comment by LordZardeck** [comment]
Essentially I want `react-hook-form` to validate my form with zod, and utilize the css selectors to create my own custom error message design. Are you saying this is not possible?

**Comment by bluebill1049** [comment]
No, you either let the runtime logic/schema take care of the validation or leave to the browser with `setCustomValidty` constraint API.
