### ISSUE TITLE
changing defaultValues used to work with data fetching

### ISSUE THREAD

**Issue by cztomsik** [react-hook-form/react-hook-form#1042]
**Describe the bug**
When `defaultValues` is initially set to `null` and then to a real data, an error is raised. In version 4.6.2 this worked fine.

**To Reproduce**
```
const { data, loading } = useGet('http://some-api/some/resource')
const form useForm({ defaultValues: data })

return data && <input name="foo" ref={form.register} />
```

Throws `Cannot read property 'foo' of null`

**Expected behavior**
In previous version this worked fine.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 79

**Comment by bluebill1049** [comment]
codesandbox example, please.

**Comment by cztomsik** [comment]
@bluebill1049 Here's codesandbox - try changing the version of react-hook-form
https://codesandbox.io/s/crazy-frost-4mf9f

**Comment by bluebill1049** [comment]
hey i am patching this issue, but please make sure you pass in defaultValue as {} not null

`const { register } = useForm({ defaultValues: data === null ? {} : data });`

**Comment by bluebill1049** [comment]
hey @cztomsik i think i find out the reason why i made the fix previously, please consider to use `reset()` API instead, the problem it creates with defaultValue get re-assigned each time is that cause infinite re-render due to `defaultValue` with `Object.is` comparison inside each re-render. unless we do a deep compare with the defaultValue object, which in my opinion is heavy and increase the package size.

**Comment by cztomsik** [comment]
yes, I can use `reset` and it's not that hard actually:

```
// used for both create/edit forms
// (haven't tried yet, I'm still on the old version)
const useEditForm(data) = {
  // null would cause issue but undefined should work fine I think
  // (if that didnt changed too)
  const form = useForm({ defaultValues: data || undefined })

  useEffect(() => {
    if (data) {
      form.reset(data)
    }
  }, [data])

  return form
}
```

But I thought that since this is such common scenario it might be covered - I'd say it's more common than `useFieldArray`, for example.

**Comment by bluebill1049** [comment]
> passing {} wouldn't help much, because that would fail for deeply nested fields.
you are right.

> But I thought that since this is such common scenario it might be covered - I'd say it's more common than useFieldArray, for example.

You are absolutely right, however, default value needs to be cached, maybe we can reinforce that in the website.

**Comment by cztomsik** [comment]
@bluebill1049 np with that, I rather thought about providing some hook (along what I've shown) in the package.

**Comment by bluebill1049** [comment]
thanks @cztomsik BTW: the cache `defaultValue` was actually trying to resolve a previous bug.

**Comment by s97712** [comment]
> hey @cztomsik i think i find out the reason why i made the fix previously, please consider to use `reset()` API instead, the problem it creates with defaultValue get re-assigned each time is that cause infinite re-render due to `defaultValue` with `Object.is` comparison inside each re-render. unless we do a deep compare with the defaultValue object, which in my opinion is heavy and increase the package size.

Consider support custom compare function? such as below usage: 
```ts
useForm({
  defaultValues,
  defaultValuesDiff: (a,b) => a == null && b != null
})

useForm({
  defaultValues,
  defaultValuesDiff: (a,b) => a.remote_data == null && b.remote_data != null
})

**Comment by bluebill1049** [comment]
> > hey @cztomsik i think i find out the reason why i made the fix previously, please consider to use `reset()` API instead, the problem it creates with defaultValue get re-assigned each time is that cause infinite re-render due to `defaultValue` with `Object.is` comparison inside each re-render. unless we do a deep compare with the defaultValue object, which in my opinion is heavy and increase the package size.
> 
> Consider support custom compare function? such as below usage:
> 
> ```ts
> useForm({
>   defaultValues,
>   defaultValuesDiff: (a,b) => a == null && b != null
> })
> 
> useForm({
>   defaultValues,
>   defaultValuesDiff: (a,b) => a.remote_data == null && b.remote_data != null
> })
> ```

thanks @s97712 you should use `reset()` instead for `defaultValues`, `defaultValues` get cached in the first render.
