### ISSUE TITLE
issue: `dirtyFields` is empty when upload different file

### ISSUE THREAD

**Issue by abdmmar** [react-hook-form/react-hook-form#10431]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/file-dirtyfields-fvu2rq?file=/src/App.js

### Steps to reproduce

1. Set defaultValues for `image` field on initial render
2. Change `image` value by uploading a new file
3. Submit form by clicking Submit button
4. `formState.dirtyFields` is empty

### Expected behaviour

1. Set defaultValues for `image` on initial render
2. Change file value by uploading a new file
3. Submit form by clicking Submit button
4. `formState.dirtyFields` should be `{image: true}`

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
data:  {image: FileList}
dirtyFields:  {}
isSameFile:  false
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abdmmar** [comment]
it might be not the best solution, but what if we comparing file by it's properties?

```

function isSameFile(file1, file2) {
  // Compare file sizes
  if (file1.size !== file2.size) {
    return false;
  }

  // Compare file names
  if (file1.name !== file2.name) {
    return false;
  }

  // Compare modification dates
  if (file1.lastModified !== file2.lastModified) {
    return false;
  }

  // Files are considered the same
  return true;
}
```

**Comment by bluebill1049** [comment]
Thanks for the suggestion, we probably wouldn't implement such with file object comparison.

**Comment by abdmmar** [comment]
Understandable, thank you for your consideration.
