### ISSUE TITLE
react-hook-form.com 404

### ISSUE THREAD

**Issue by shughes-uk** [react-hook-form/react-hook-form#10438]
### Version Number

-

### Codesandbox/Expo snack

-

### Steps to reproduce

https://react-hook-form.com/ currently is a blank page

### Expected behaviour

Docs!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
https://twitter.com/moshyfawn/status/1660494672643465217
