### ISSUE TITLE
[Feature Request] isActive property in fieldState, activeField property in formState

### ISSUE THREAD

**Issue by anru** [react-hook-form/react-hook-form#10435]
**Is your feature request related to a problem? Please describe.**

I have two fields. The first field is source for values for the second field by submitting first input values to backend and receiving response back. But second field should not get values by any logic from first field while second field is active (i.e. in a focused state).

I want to call field.onChange only if field is not active and there is backend response come, which was initiated from onChange handler from first field. Purpose here is let user edit second field without any interference if second field is active.

**Describe the solution you'd like**

```ts
if (!field.value && !field.isActive && suggestionHookResult.value) {
  field.onChange(suggestionHookResult.value);
}
```

**Describe alternatives you've considered**

Move that logic to onChange handler of first field, but I don't want any situations where is one field have write logic to another field.

**Additional context**

My form have a lot of business logic, and I want to keep any business logic related to field near to that field, as maximum as possible.

**Comment by Moshyfawn** [comment]
I'll look at this in the morning more, but it looks like a user-land use-case to solve atm.

**Comment by bluebill1049** [comment]
This would most likely to be a userland problem to solve at the moment.
