### ISSUE TITLE
Provide example with Masked Input + Custom Input.

### ISSUE THREAD

**Issue by dskiba** [react-hook-form/react-hook-form#1043]
Hello, first wanna thank you all guys for the react-hook-form, really interesting thing :) 

I am trying RHF with react-input-mask and custom input
 https://codesandbox.io/s/new-star-rzmfb

And there is one problem with a cursor on Safari(13). I have already created a pull request in react-input-mask. 

So if this issue with safari will be fixed, would you be interested in me to create a pull request with this example?

**Comment by dskiba** [comment]
fixed this issue 💃
good example: https://codesandbox.io/s/focused-kapitsa-n3u6c  
I should use react setState (or hook version) to chage value instead of setValues.

Now it works well and I can create a pull request with the contribution to examples sections if you are interested in it. 🤓

**Comment by bluebill1049** [comment]
That's awesome. would you like to spend a PR and add this example to our examples folder?

**Comment by bluebill1049** [comment]
can we do a version with Controller as well?

**Comment by dskiba** [comment]
Yeah, I will do a PR with this example and with a Controller version.

**Comment by bluebill1049** [comment]
Awesome thanks 👍❤️

**Comment by bluebill1049** [comment]
https://spectrum.chat/react-hook-form/help/how-to-do-parse-and-format~2c0224a1-f3df-4e8a-821b-ea5e51328a32

**Comment by bluebill1049** [comment]
I am going to close this issue, feel free to send PR @dskiba when you got the controller version ready :)
