### ISSUE TITLE
useWatch returns `never` as result for values specified with enum 

### ISSUE THREAD

**Issue by AlexKrupko** [react-hook-form/react-hook-form#10445]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/nifty-shape-yuwke4?file=/src/App.tsx

### Steps to reproduce

Hi there, 

`useWatch` returns correct field value but with `never` type if I use field values specified with enum prop. 
Please take a look at `dateFrom` variable type in my codesandbox example. 

![Screen Shot 2023-05-25 at 22 54 18](https://github.com/react-hook-form/react-hook-form/assets/5411244/6df27156-0251-4512-a7c5-3f5f88c88b35)

### Expected behaviour

`useWatch` should provide a proper type. 
At least I'm wondering what is wrong with that definition and how to make it to work properly.
Thanks  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
#8898

**Comment by Moshyfawn** [comment]
No problem, Alex!

**Comment by AlexKrupko** [comment]
Perhaps this will help someone. Replacing enum with const object solved my issue. `useWatch` provides a proper type in that case as there is no enum with its limitations - 
[https://codesandbox.io/s/unruffled-shadow-ge5qgv?file=/src/App.tsx](https://codesandbox.io/s/unruffled-shadow-ge5qgv?file=/src/App.tsx)
