### ISSUE TITLE
Access defaultValues in FormContext

### ISSUE THREAD

**Issue by antonbehaeghe** [react-hook-form/react-hook-form#1044]
Is there any way to access the defaultValues when using custom manually registered components in FormContext? Or do I have to set the defaultValues and then also pass them as props to my components where I can set them manually?

The docs only mention that it's not set automatically:

> Note: defaultValues doesn't auto populate with the manually registered input (eg: register({ name: 'test' })) because the manual register field does not provide the ref to React Hook Form.

**Comment by bluebill1049** [comment]
If you are using Controller, it should populate the default value.

**Comment by antonbehaeghe** [comment]
Not using Controller, just manually registering.

**Comment by bluebill1049** [comment]
No, we don't expose defaultValues.

**Comment by antonbehaeghe** [comment]
Alright thanks :) 
So the correct way to do it would be to set the defaultValues like in the codesandbox, and then explicitly pass the defaultValue to the CustomInput?

Is exposing the defaultValues in the FormContext something that could be added? Or are there reasons not to do it?

**Comment by bluebill1049** [comment]
you can create a context for the form. FormContext only expose RHF functions and have no plan to expose other attributes.

**Comment by qwen-3108** [comment]
For anyone who came across this issue, I'm passing and accessing the defaultValues via FormProvider like so:

`<FormProvider {...methods} defaultValues={defaultValues}>`

Then in my nested input
`const { defaultValues } = useFormContext();`

Codesandbox: https://codesandbox.io/s/react-hook-form-v6-form-context-forked-i28s5?file=/src/Test.js

**Comment by codeshifu** [comment]
If your defaultValues are derived from async values e.g.

```jsx
const defaultValues = useMemo(() => {
  email: user?.email
}, [user]);

const { register } = useForm({ defaultValues });
```

You (may) need to reset the fields for `useFormContext` to work properly
```jsx
const { reset } = useForm({ defaultValues });

useEffect(() => {
  reset(defaultValues);
}, [reset, defaultValues]);
```

**Comment by Moshyfawn** [comment]
It's advised to not pass unrelated to RHF own methods / values props via the built-in `FormProvider`. While it works in a JS code-base due to `FormProvider` just spreading the received props down as-is, the TS type does not support such usage + you run into issue you have to workaround, like the one above.

The correct usage would be to create your own custom `ContextProvider` and pass down whatever props you need. You can include the form methods as well, if you want.
