### ISSUE TITLE
feature: better integration with react router and remix Form and actions

### ISSUE THREAD

**Issue by okalil** [react-hook-form/react-hook-form#10442]
Form submissions are navigations, so it makes sense for the react router to support that, but its responsibility ends there. There are other form-related issues though, like validation and focus management, which is where react-hook-form fits in.

Regarding the submission event, I believe that a better alternative to `handleSubmit` would be to use the `trigger`, for example:
```jsx
const { trigger } = useForm()
const handleSubmit = async (e) => {
  const isValid = await trigger()
  if(!isValid) e.preventDefault()
}
return <Form onSubmit={handleSubmit} >
```
This way, the submit is only prevented if it is not valid.

Also, as these react router apis are used in Remix , which runs on the server, it would be interesting to allow setting initial errors for the useForm for progressive improvement when the js has not loaded yet when submitting the form:
``` jsx
const actionData = useActionData()
const form = useForm({ 
  defaultValues: actionData?.defaultValues, 
  errors: actionData?.errors
})
```
That could also be used to merge client errors with the errors returned from the api 

And it would be nice if react-hook-form exported a utility function to convert formData with dot notation to an object inside the action:
```js
import { parseFormData } from 'react-hook-form'
export const action = async ({ request }) => {
   const formData = await request.formData()
   const data = parseFormData(formData)
   // data has the same format as returned from getValues()
}
```

**Comment by AlemTuzlak** [comment]
Just to add this to the issue, I created a wrapper for remix around it:
https://github.com/Code-Forge-Net/remix-hook-form
So you can check the source code to get the idea on what it would mean and if it makes sense

**Comment by bluebill1049** [comment]
Nice one @AlemTuzlak 

new `<Form />` component would supply `formData`

```tsx
<Form onSubmit={( { formData } ) => {
}} />
```

in fact, you would be able to do the following 

```tsx
<Form action="/api" />
```

and react hook form would take care of the submission except for the navigation, which you can leverage `onSuccess`

```tsx
<Form action="/api" onSuccess={() => {
  // alert() or push()
}} />
```

We are probably not going to tightly couple or integrate with any framework such as remix, refine, nextjs, but provide a way to combine or have an enhanced library such as `remix-hook-form`.

**Comment by okalil** [comment]
> We are probably not going to tightly couple or integrate with any framework such as remix, refine, nextjs, but provide a way to combine or have an enhanced library such as `remix-hook-form`. RHF still would be client focused form library at this stage.

What I suggest is simply allowing set default errors + utility to parse values from a form data. That is not framework specific but would make usage with react router easier.

**Comment by bluebill1049** [comment]
>  utility to parse values from a form data

we are doing that.

>  allowing set default errors

you can use the `setError` API

**Comment by AlemTuzlak** [comment]
> Nice one @AlemTuzlak!
> 
> new `<Form />` component would supply `formData`
> 
> https://react-hook-form.com/docs/useform/form
> 
> ```tsx
> <Form 
>  onSubmit={( { formData } ) => {
>  }} 
> />
> ```
> 
> in fact, you would be able to do the following
> 
> ```tsx
> <Form action="/api" />
> ```
> 
> and react hook form would take care of the submission except for the navigation, which you can leverage `onSuccess`
> 
> ```tsx
> <Form action="/api" onSuccess={() => {
>   // alert() or push()
> }} />
> ```
> 
> We are probably not going to tightly couple or integrate with any framework such as remix, refine, nextjs, but provide a way to combine or have an enhanced library such as `remix-hook-form`. RHF still would be client focused form library at this stage.

Thank you @bluebill1049 
The form component looks very promising I might extend it as well for Remix. Awesome work and thank you for your feedback!
