### ISSUE TITLE
issue: validate does not receive formValues

### ISSUE THREAD

**Issue by unional** [react-hook-form/react-hook-form#10446]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/modest-edison-jgkfw0?file=/src/App.tsx

### Steps to reproduce

edit the input and submit.

Change input value to see the data changes.

### Expected behaviour

The `validate()` function should receive the `value` and `formValues` as described in the doc.

```ts
<input
  {...register("test", {
    validate: (value, formValues) => value === '1'
  })}
/>
```

The `formValues` is needed to perform more dynamic/complex validation.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Could you please use the latest version?

**Comment by Moshyfawn** [comment]
This feature is only available **since** [v7.42.0](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.42.0)

**Comment by unional** [comment]
Lastest is 7.43.9.

Do you mean `@next`?

**Comment by unional** [comment]
I see it works in the codesandbox. Will try again locally and close.

btw, the with error message example in the docs does not have this example.

**Comment by Moshyfawn** [comment]
> btw, the with error message example in the docs does not have this example.

It has a different API example with `formValues`
![image](https://github.com/react-hook-form/react-hook-form/assets/16290753/af0195ec-d138-4fbd-9a82-13603bfc44a0)

**Comment by unional** [comment]
Confirm with 7.43.9. thx for the quick response! 🏎️
