### ISSUE TITLE
Is there a way to force marking the form as dirty?

### ISSUE THREAD

**Issue by chris-fran** [react-hook-form/react-hook-form#1045]
**Describe the question?**
Is there a way to force the form as dirty?

**Additional context**
We're using the [Field Arrays](https://react-hook-form.com/advanced-usage#FieldArrays) **WITHOUT the useFieldArray hook** to hack adding values to the form. Code goes like this:

```jsx
<>
  {pills.map(pill => 
    <Pill {...pill} onClick={() => removePill(pill.id)} />
  }

  <select multiple values={pills.map(({ id }) => id)}>
    {pills.map(({ id }) =>
      <option key={id} value={id}>{id}</option>
    }
  </select>
</>
```
    
Our pill is custom made, and it's probably missing features before we can use the `Controller` api, so we went for this hack instead.

It works, removing a pill causes a re-render, but the only problem is that it won't make the form dirty. What options do I have?

**Comment by bluebill1049** [comment]
`setValue` can trigger the form to be dirty.

**Comment by chris-fran** [comment]
@bluebill1049 Thanks, just changed this hack for a mix of `register/unregister + setValue`
