### ISSUE TITLE
issue: Object.hasOwn is not a function

### ISSUE THREAD

**Issue by eladonline** [react-hook-form/react-hook-form#10455]
### Version Number

7.44.1

### Codesandbox/Expo snack

couldnt create working sandbox

### Steps to reproduce

since your latests update 
I started seeing errors in my tests,  mocha + jest + enzyme

![image](https://github.com/react-hook-form/react-hook-form/assets/20336964/8a58c724-6c6b-46d4-a5cb-f6725de1799a)

### Expected behaviour

tests pass

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
not related to this library.

**Comment by Moshyfawn** [comment]
Looks like the issue is related to a RHF change. There's #10456 with more details, so I'm gonna close this one as a duplicate instead

**Comment by Moshyfawn** [comment]
@eladonline this is fixed in [v7.44.2](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.44.2)
