### ISSUE TITLE
[React Native] Strange Error at render and/or submit 

### ISSUE THREAD

**Issue by firasrg** [react-hook-form/react-hook-form#10456]
### Version Number

7.44.1

### Codesandbox/Expo snack

https://snack.expo.dev/@frg1220/bug---react-hook-form-v7

## Steps
1. Open the Expo Snack link
2. Switch to Android emulator OR QR code to run on device
3. Render the form page
4. Get an error from React Native compiler

## Notes
- No errors on WEB platform. 
- Switching to version ``7.17.5``, solves the problem.

### Expected behaviour

I'm expecting to see the form running without any issues, do submission and apply normal validations.

### Relevant log output

```shell
TypeError: Object.hasOwn is not a function. (In 'Object.hasOwn(e, _r)', 'Object.hasOwn' is undefined)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Interesting, the error's the same as #10455

**Comment by Moshyfawn** [comment]
So, from what I can see on the surface, `Object.hasOwn` [was introduced](https://nodejs.org/en/blog/release/v16.9.0#objecthasown) in Node [v16.9.0](https://nodejs.org/en/blog/release/v16.9.0) and is used in RHF codebase.

What's weird is that the last "working" version was [v7.44.0-rc.1](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.44.0-rc.2) _(npm can't find v7.44.0-rc.1) for some reason; can't verify)_. I don't belive it contains any changes related to `Object.hasOwn` 🤔

**Comment by Moshyfawn** [comment]
Ah, OK, so [v7.44.0-rc.2](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.44.0-rc.2) **is** the version that introduced the `Object.hasOwn` method into the codebase.

@bluebill1049 do you want to set a new min required Node version to [v16.9.0](https://nodejs.org/en/blog/release/v16.9.0) or try to avoid it?

It is a major RHF version bump..

**Comment by Moshyfawn** [comment]
@firasrg you can downgrade to something like [v7.43.9](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.43.9) for now

**Comment by firasrg** [comment]
@Moshyfawn thank you so much for the reply 😃

Alright then

I have a good experience with React, do you think, that I can fix this issue?

**Comment by Moshyfawn** [comment]
> I have a good experience with React, do you think, that I can fix this issue?

Let's see what @bluebill1049 wants to do first and go from there

**Comment by bluebill1049** [comment]
@bluebill1049 which commit introduced that?

**Comment by bluebill1049** [comment]
Thank you @Moshyfawn 🙏 fixing it.

**Comment by Moshyfawn** [comment]
> @bluebill1049 which commit introduced that?

https://github.com/react-hook-form/react-hook-form/commit/d68ef91bc8ced492e51845083cb9e74acd7fa9a8

**Comment by ryota-murakami** [comment]
> So, from what I can see on the surface, `Object.hasOwn` [was introduced](https://nodejs.org/en/blog/release/v16.9.0#objecthasown) in Node [v16.9.0](https://nodejs.org/en/blog/release/v16.9.0) and is used in RHF codebase.
> 
> What's weird is that the last "working" version was [v7.44.0-rc.1](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.44.0-rc.1) _(npm can't find [v7.44.0-rc.2](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.44.0-rc.2)) for some reason; can't verify)_. I don't belive it contains any changes related to `Object.hasOwn` 🤔

I was surprised that Object.hasOwn was a relatively newly implemented method!

**Comment by bluebill1049** [comment]
I didn't know that as well @ryota-murakami 😂 we have been spoiled by babel for too long.

**Comment by ryota-murakami** [comment]
> I didn't know that as well @ryota-murakami 😂 we have been spoiled by babel for too long.

@bluebill1049 I agree with you!
I think that the current state of "runtime" is not good, and I would like to migrate to Deno as soon as possible and continue using React-Hook-Form there as well.

**Comment by eladonline** [comment]
I want to Note this was not happend to us only on the latests version 
it happend since the latests version we where working with 7.33.1 and also bump into this

**Comment by firasrg** [comment]
Hello ! 

Awesome! the issue is fixed quickly! I appreciate **your reactivity**. 😍
Now going to switch to [the new version](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.44.2)!

Enjoy your day
