### ISSUE TITLE
issue: Converts form data from object to array if the object keys are only numbers

### ISSUE THREAD

**Issue by AbdOfRahman** [react-hook-form/react-hook-form#10460]
### Version Number

7.44.2

### Codesandbox/Expo snack

https://codesandbox.io/p/github/AbdOfRahman/rhf-object-to-array-issue/master?file=/src/App.jsx

### Steps to reproduce

1. Go to '(https://codesandbox.io/p/github/AbdOfRahman/rhf-object-to-array-issue/master?file=/src/App.jsx)'
2. Enter some data for first form, then submit it, you will get the data as object in the console.
3. Enter some data for second form, then submit it, you will get the data as array in the console.
4. the thing is, because I used numbers as object keys in the second form, it directly converts it to array.

### Expected behaviour

I expect to get an object like this:
```
obj: {
    "0": { "input": "a" },
    "1": { "input": "b" },
    "2": { "input": "c" }
}
```
But I get: 
```
obj: [ { "input": "a" }, { "input": "b" }, { "input": "c" } ]
```

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Relevant log output

```shell
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Please have your own logic to convert to FormData, if the default behavior is not your desired output.
