### ISSUE TITLE
reset() should respect defaultChecked

### ISSUE THREAD

**Issue by AugustNagro** [react-hook-form/react-hook-form#1046]
It respects the defaultValue properties (eg, on an text input), but not for a checkbox.

**Comment by bluebill1049** [comment]
please provide a codesandbox for us to reproduce.

**Comment by AugustNagro** [comment]
Do you have an codesandbox template I can modify? Have never used before.

**Comment by bluebill1049** [comment]
I don't shouldn't be too hard to create one just with checkbox tho.

**Comment by AugustNagro** [comment]
The problem is that when a form is reset(), every component with a defaultValue has that property re-evaluated. However, defaultChecked is ignored, so that the checkboxes lose their data.

I am trying to create a codesandbox

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/happy-gauss-en8jy

**Comment by bluebill1049** [comment]
Going to close this issue, take a look at the example above.
