### ISSUE TITLE
useFieldArray: remove an item in a callback or after asynchronous code working wrong

### ISSUE THREAD

**Issue by hieusmiths** [react-hook-form/react-hook-form#10462]
### Version Number

7.24.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-elo8rg?file=/src/index.tsx:0-4511

### Steps to reproduce

1. Implement useFieldArray as normal
2. Implement field item component
3. Call removal item by index after calling to asynchronous successfully (I'm working on `onSuccess` callback of `react-query/useMutation` 

4. The fields value in useFieldArray are correctly but data on the UI and getValues are mismatch.

I'm using TextField in (Material UI mui@5.12.1) and use the bellow register pattern.

`<TextField
                inputProps={{
                    ...register(name),
                }}
 />`

Sample code for call `remove` of useFieldArray like a callback or after await 

``` TSX
const deleteItemAsync = (index) => {
        mutate(undefined, {
            onSuccess: () => {
                remove(index);
            },
        });
};

Or
 
 const deleteAsync = async (index) => {
    await delay(500);
    remove(index);
  };
```
Here is the image after deleting an item and data between fields in  and getValues is a mismatch

![image](https://github.com/react-hook-form/react-hook-form/assets/46733391/8ba119ab-b2b6-4ce1-a391-635ac790385f)

### Expected behaviour

getValues and fields in useFieldArray have same the value.

Data render on the UI is correct

### Relevant log output
I tried to use 7.25.1 for the code sandbox and It's working well :smile:  

And I tried this way for `7.24.0` and it's working well so Is it an official way to resolve this issue?
``` TSX
const [del, setDel] = useState(false);

const deleteAsync = async (index) => {
    await delay(500);
    setDel(true)
  };

React.useEffect(() => {
  if(del) remove(0);
}, [del, remove])
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I don't see the issue here. I am using the latest version instead of 7.24.0
<img width="1123" alt="Screenshot 2023-05-30 at 8 14 47 am" src="https://github.com/react-hook-form/react-hook-form/assets/10513364/c9dcfde0-81e0-497b-b886-a353d5516def">

**Comment by hieusmiths** [comment]
@bluebill1049 Yes, The problem won't happen on the latest version or greater than >  `7.25.1`

**Comment by hieusmiths** [comment]
The issue happens on version greater than `7.22.5` and less than `7.25.1`
cc: @bluebill1049 
Quick solution

``` TSX
const [del, setDel] = useState(false);

const deleteAsync = async (index) => {
    await delay(500);
    setDel(true)
  };

React.useEffect(() => {
  if(del) remove(0);
}, [del, remove])
```

**Comment by Moshyfawn** [comment]
We can't update the already released versions, so the only solution is to upgrade

**Comment by hieusmiths** [comment]
> We can't update the already released versions, so the only solution is to upgrade

Yes, I just provide a quick solution. Is it valid?

Of course, we still need to upgrade
