### ISSUE TITLE
issue: When `rules` supplied to `useFieldArray` return value of checkboxes becomes an array under certain conditions

### ISSUE THREAD

**Issue by mickyginger** [react-hook-form/react-hook-form#10475]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/laughing-mahavira-hdzg0j

### Steps to reproduce

1. Remove the checked item in the field array;
2. Add a new item;
3. Submit the form... the second item `featured` key is now an array, not a boolean.

### Expected behaviour

The form should always return an array of objects with `featured` set to a boolean value.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
{
  "items": [
    {
      "featured": false
    },
    {
      "featured": []
    },
    {
      "featured": false
    }
  ]
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is a very tricky situation. When you append a new checkbox, it will focus on the previous one which at runtime it would share the same input name before it gets unmounted, and it would trickily react hook form thinking it's a multiple select checkbox. 

eg

```tsx
name="single"
name="single"
name="single"
```

would turn the checkbox into an array of checkboxes, the current work around is just turn off the focus.

**Comment by bluebill1049** [comment]
ok find a work around but please turn off the focus for now.
