### ISSUE TITLE
issue: wrong types

### ISSUE THREAD

**Issue by joshribakoff-sm** [react-hook-form/react-hook-form#10470]
### Version Number

7.43.9

### Codesandbox/Expo snack

n/a

### Steps to reproduce

Define the TS type as a number (non nullable) and supply no default value:

```ts
    useForm<{foo: number}>({
      defaultValues: {}
   })
```

define a controller:

```
            <Controller
              control={control}
              name="foo"
              render={({ field: { onChange, value } }) => (
                <Input
                  onChange={(event) => {
                    onChange(parseInt(event.target.value));
                  }}
                  value={value.toString()}
                />
              )}
            />
```

crashes at runtime on `value.toString()` since `value` is NULL on mount, but the type does not catch it as the type is non nullable here.

### Expected behaviour

detect that it's NULL in the default value, expand the type in your render prop. Either that, or put a type error on the `defaultValues` I am supplying.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Please, provide a codesandbox

**Comment by joshribakoff-sm** [comment]
Just trying to help, I don't have time. Guess it can remain broken.

**Comment by Moshyfawn** [comment]
We also don't have time to re-create everyone's environments and use-cases, you gotta understand that too 😉

**Comment by joshribakoff-sm** [comment]
I think my report is pretty clear. Hope it helps.
