### ISSUE TITLE
issue: defaultValues using async function causes register name to be never

### ISSUE THREAD

**Issue by despin** [react-hook-form/react-hook-form#10480]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-async-defaultvalues-never-type-error-469u7n

### Steps to reproduce

1. Go to the codesandbox link.
2. Comment line 5 
3. Uncomment line 6
4. See error in lines 11 and 12, where the name param should be valid for "email" and "name", but instead TS throws a `'string' is not assignable for 'never'`

### Expected behaviour

I'm following [this example](https://www.react-hook-form.com/api/useform/#defaultValues:~:text=input%20change%20event.-,defaultValues,-%3A%20FieldValues%20%7C%20Promise) pretty step by step, and I think I should be able to use `"email"` or `"name"` as the field name parameter, but it only works in the sync example, not using an async function.

(If something of this issue is not entirely understandable, please let me know. English is not my first language)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
You will have to provide a generic type, we couldn't infer what's inside the async func. I did try and it wasn't working.

**Comment by despin** [comment]
Thanks! 

I tried the following and worked for me!

```typescript
import { useForm } from "react-hook-form";

const getDefaultValues = async () => ({ email: "", name: "" });

type DefaultValues = Partial<Awaited<ReturnType<typeof getDefaultValues>>>;

export default function DeclaredDataScreen() {
  const { register, handleSubmit } = useForm<DefaultValues>({
    defaultValues: getDefaultValues
  });

  return (
    <form onSubmit={handleSubmit(() => console.log("submit"))}>
      <input {...register("email")} />
      <input {...register("name")} />
    </form>
  );
}
```

I think it would be helpful if you could include something like on the documentation for people like me 😆

**Comment by despin** [comment]
Thanks! 

I tried the following, and worked for me!

```typescript
import { useForm } from "react-hook-form";

const getDefaultValues = async () => ({ email: "", name: "" });

type DefaultValues = Awaited<ReturnType<typeof getDefaultValues>>;

export default function DeclaredDataScreen() {
  const { register, handleSubmit } = useForm<DefaultValues>({
    defaultValues: getDefaultValues
  });

  return (
    <form onSubmit={handleSubmit(() => console.log("submit"))}>
      <input {...register("email")} />
      <input {...register("name")} />
    </form>
  );
}
```

I think it would be helpful if you could include something like on the documentation for people like me 😆
