### ISSUE TITLE
Allow error messages to be extendible objects

### ISSUE THREAD

**Issue by shaungrady** [react-hook-form/react-hook-form#10482]
**Is your feature request related to a problem? Please describe.**

I'm working in a project that requires internationalization (i18n) and makes use of [Yup](https://github.com/jquense/yup) for defining form schemas, field labels, and validation rules. Integration of Yup with RHF is being done with [@hookform/resolvers](https://github.com/react-hook-form/resolvers).

Yup produces field errors that are objects containing a lot of data; e.g., the field label (if defined), the path, [metadata](https://github.com/jquense/yup#schemametametadata-object-schema), and information about the validation rule that caused the error. This allows the error messages to be interpolated and translated at runtime. Here's an example of an error message for a number validation error for a number that exceeds the max limit: `"{{label}} must be less than or equal to {{max}}"`.

Given that [RHF error messages are typed as strings](https://github.com/react-hook-form/react-hook-form/blob/master/src/types/errors.ts#L5), this typing doesn't allow for Yup's error objects; however, Yup still produces them, and RHF still passes along Yup's error objects at runtime without issue.

**Describe the solution you'd like**

I'd like to modify the error [`Message`](https://github.com/react-hook-form/react-hook-form/blob/master/src/types/errors.ts#L5) type to be a union type with a new, empty interface; e.g.:

```patch
-export type Message = string;
+export interface CustomError {}
+export type Message = string | CustomError;
```

This would allow consumers of the library to create their own `react-hook-form.d.ts` definitions file to extend `CustomError` to fit their needs through declaration merging; e.g.:

```ts
import 'react-hook-form';

declare module 'react-hook-form' {
	export interface CustomError {
		label: string,
		path: string,
		// …
	}
}

```

**Describe alternatives you've considered**

I considered serializing errors before they are provided to RHF (`JSON.stringify`) and deserializing them when provided by RHF, but that exercise would be purely in service of RHF's defined types, given that RHF doesn't appear to touch error `Message` data.

**Comment by bluebill1049** [comment]
Would you like to send us a PR on this?

**Comment by shaungrady** [comment]
I'm working through getting approval from my employer to contribute, hope to be able to open a PR for this soon.
