### ISSUE TITLE
Field with comma-separated name doesn't work

### ISSUE THREAD

**Issue by AlexKrupko** [react-hook-form/react-hook-form#10481]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/amazing-wing-l9eucq?file=/src/App.tsx

### Steps to reproduce

Please check my codesandbox example. 
Field with comma separated name value works if we use it on the top level - `name1,name2`. 
But if we use it with nested field prefix, it doesn't work - `parent.name1,name2`

### Expected behaviour

Comma-separated field names should be acceptable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Doesn't support.

**Comment by AlexKrupko** [comment]
This is the easiest way just to say "Doesn't support" and close the ticket... 
These are customer configurable parameters and they can contain any characters in the name. We can't avoid it.
