### ISSUE TITLE
issue: target.validity no longer working

### ISSUE THREAD

**Issue by jamierytlewski** [react-hook-form/react-hook-form#10492]
### Version Number

7.44.3

### Codesandbox/Expo snack

https://codesandbox.io/s/polished-cherry-53qcfi?file=/src/App.tsx

### Steps to reproduce

1. Make sure you are viewing console.
2. Type in numbers
3. You should see false until you get to five numbers

### Expected behaviour

The expected behavior is that in 7.43.8 everything worked fine. I upgraded to 7.44.3 and it's broke. I tried a few different versions and even 7.44.0-rc.0

Looks like it broke sometime between 7.44.0-rc.1 and 7.44.0-rc3. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
I'm a bit confused as to how `shouldUseNativeValidation` and the new `progressive` prop should work together, but in [v7.44.0-next.0](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.44.0-next.0) the `progressive` prop was added replacing `shouldUseNativeValidation` in some places.

If you use
```jsx
useForm({
  progressive: true
})
```

you'll get the desired behaviour you're describing.

@bluebill1049 this is [the change](https://github.com/react-hook-form/react-hook-form/commit/edc4cec517eaf51fbaef1d173b9d57cd448ba554). Are we getting rid of `shouldUseNativeValidation` in favour of `progressive`?

**Comment by jamierytlewski** [comment]
@Moshyfawn thanks. But where is the progessive in the documentation? I see something here: 
<img width="447" alt="image" src="https://github.com/react-hook-form/react-hook-form/assets/695710/51dd61b4-f7f4-485f-b84c-68acd42cf40c">
But i'm not doing SSR. So, this is a bit misleading.

**Comment by Moshyfawn** [comment]
> @Moshyfawn thanks. But where is the progessive in the documentation? I see something here: <img alt="image" width="447" src="https://user-images.githubusercontent.com/695710/242953057-51dd61b4-f7f4-485f-b84c-68acd42cf40c.png"> But i'm not doing SSR. So, this is a bit misleading.

I understand. I'm almost on the same page as you on `progressive` as I missed this feature. You can use the option for your use-case for now. Let's see if Bill has more info
