### ISSUE TITLE
formArray

### ISSUE THREAD

**Issue by getsetgopi** [react-hook-form/react-hook-form#1049]
Please consider asking the question at our spectrum channel.

https://spectrum.chat/react-hook-form

**Just like fieldArray is there a way to get formArray?. A page can have multiple forms and need to get values from both the forms.**

**To Reproduce**

**Codesandbox link**
Include a codesandox will help us to investigate the issue quicker.

**Screenshots**

**Additional context**

**Comment by bluebill1049** [comment]
you can create separate sub-components and each with its own useForm.

Root Component  
- Form - with useForm
- Form - with useForm
- Form - with useForm
etc...
