### ISSUE TITLE
issue: register function don`t return options with shouldUseNativeValidation in 7.44.0 or later

### ISSUE THREAD

**Issue by FanManutd** [react-hook-form/react-hook-form#10504]
### Version Number

7.44.3

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-7-44-3-4vm9w2?file=/src/App.tsx

### Steps to reproduce

1. Go to CodeSandbox
2. Open console
3. Make sure the `register` function doesn't return passed properties `requried`, `min`, and any other

### Expected behaviour

In version 7.43.9 ([sandox here](https://codesandbox.io/s/react-hook-form-7-43-9-9n3vln?file=/src/App.tsx)) the function `register` with `shouldUseNativeValidation: true` option returned the passed parameters and I expected this behavior in my code. In 7.44.3 this is not the case. Why has it changed?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kotarella1110** [comment]
@bluebill1049 

It seems that the addition of the `progressive` option has resulted in the deletion of `shouldNativeValidation`...

https://github.com/react-hook-form/react-hook-form/blob/747ddcaef0a940a528e7e06d34afd144b924ebc1/src/logic/createFormControl.ts#L965

This appears to be an unintended change.
In any case, as this is a disruptive change, I believe the modification should be reverted.

**Comment by kotarella1110** [comment]
related:

- https://github.com/react-hook-form/react-hook-form/issues/10348
- https://github.com/react-hook-form/react-hook-form/commit/6eb85b738fd11718b375ff916c6eeab4cc703b38

**Comment by FanManutd** [comment]
> Sorry, I misunderstood the situation. This change was intended and not a breaking change. The implementation ensures that native validation correctly even without returning the option.

So, is this a bug or not? I updated the [sendbox](https://codesandbox.io/s/react-hook-form-7-44-3-4vm9w2?file=/src/App.tsx) to see that the properties are not being passed to input. The form is not submitted if the conditions are not met, but there are no native error messages either.

Also, the type of the `register` function indicates that it can return an object with options `required`, `disabled`, `min`, `max`, etc.

If version 7.44.3 behaves correctly in this case, does it mean that when the `shouldUseNativeValidation` option is enabled, parameters such as `disable`, `required`, etc. should be passed to bypass the `register` function

**Comment by bluebill1049** [comment]
There was a bug fix, please refer to the comment above.

**Comment by FanManutd** [comment]
> There was a bug fix, please refer to the comment above.

Ok, is it possible to get the default native error messages without passing a custom property `message`? [Now](https://codesandbox.io/s/react-hook-form-7-44-3-4vm9w2?file=/src/App.tsx:320-324) if I don't pass a `message` prop, no messages appear at all. 

Also, `UseFormRegisterReturn` type return `min`, `max`, `required` and other validate fields. 
https://github.com/react-hook-form/react-hook-form/blob/747ddcaef0a940a528e7e06d34afd144b924ebc1/src/types/form.ts#L166

At the same time, if a `disabled` prop is passed to the `register` function, it will be passed to the final input. I'm not sure how this SHOULD work, so I'm asking questions to see if I can get the default native messages.

**Comment by bluebill1049** [comment]
> At the same time, if a disabled prop is passed to the register function, it will be passed to the final input. I'm not sure how this SHOULD work, so I'm asking questions to see if I can get the default native messages.

`disabled` prop is not part of constraint API, hence it doesn't introduce a side effect to the validation issue report above (the original bug).

**Comment by Moshyfawn** [comment]
Just FYI related #10492

**Comment by roryf** [comment]
Just got stumped by this, only ended up here after looking through source code - far as I can tell the `progressive` prop is not documented anywhere. 👍🏻 on making it clear how this should behave, it seems like the `shouldUseNativeValidation` is essentially deprecated and meaningless in client-render context.
