### ISSUE TITLE
Multiple error messages per field

### ISSUE THREAD

**Issue by archfz** [react-hook-form/react-hook-form#1050]
**Is your feature request related to a problem? Please describe.**
Multiple error messages per field is not possible.

**Describe the solution you'd like**
Add support for multiple error messages per one field that would make is so that the ErrorMessage component actually renders multiple 'as' elements with those messages.

**Comment by bluebill1049** [comment]
please check `validateCriteriaMode`

**Comment by archfz** [comment]
I am using custom validation. I have checked the code of the ErrorMessage component and I do not see any logic there to display multiple errors in multiple dom elements. What am I missing?

**Comment by bluebill1049** [comment]
<img width="1079" alt="Screen Shot 2020-02-19 at 8 36 00 am" src="https://user-images.githubusercontent.com/10513364/74780046-e83b8700-52f2-11ea-9ce8-c13bb05a34d3.png">

**Comment by bluebill1049** [comment]
you can even show the errors' message yourself by the errors object

**Comment by archfz** [comment]
When I send my custom component to as , or infact any component I get all the errors displayed in a single instance of the that component. I am not sure what I am doing wrong. In the end I've created a custom component for rendering the errors. If this is possible with the react-hook-form ErrorMessage component it would be nice if the documentation had an example for displaying multiple messages.

**Comment by bluebill1049** [comment]
sounds good to me. @kotarella1110 you want to supply an example with ErrorMessage component with multiple errors? (when you have some free time)

**Comment by kotarella1110** [comment]
@bluebill1049 I will do!
@abihf This PR https://github.com/react-hook-form/react-hook-form/pull/750 contains a simple example.

**Comment by bluebill1049** [comment]
We can have the example on the website :) i can help with that

**Comment by kotarella1110** [comment]
@abihf added example to documentation for displaying multiple messages!
https://react-hook-form.com/api/#ErrorMessage
