### ISSUE TITLE
issue: The documentation page is broken

### ISSUE THREAD

**Issue by bnheise** [react-hook-form/react-hook-form#10509]
### Version Number

N/A

### Codesandbox/Expo snack

N/a

### Steps to reproduce

Click here and find the link is broken: https://react-hook-form.com/api#register
Many other pages are exhibiting the same problem.

### Expected behaviour

The page should work.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/documentation/issues/971
