### ISSUE TITLE
issue: Deeply nested value in fieldArray is not updated in the UI

### ISSUE THREAD

**Issue by ifrimsilviu-goosfraba** [react-hook-form/react-hook-form#10515]
### Version Number

7.43.5

### Codesandbox/Expo snack

https://codesandbox.io/s/react-17-forked-j2vsdl?file=/src/components/Example.js

### Steps to reproduce

1. Open the CodeSandbox.
2. See that the input fields have some default values at first.
3. Click on the "Change values" button.
4. The first field is updated with the new value, yet the second one is not, even if it has the same structure as the default value.

### Expected behaviour

Both fields should change their values in the UI, not only the first one.

I have further investigated and found out that `<Controller/>` uses `useWatch` internally, with the `exact` property hardcoded to `true`, as of this PR from February 2022: https://github.com/react-hook-form/react-hook-form/pull/7759.
I have also included 2 console logs that resemble that, with one that has `exact` matching, and one that doesn't. The latter is updated accordingly.

### What browsers are you seeing the problem on?

Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Expected behaviour `useController` target a single key name to isolate its re-render, you will have to build a component group component and hook with `useController` with object.

**Comment by ifrimsilviu-goosfraba** [comment]
Are you suggesting to leverage `useController` and handle the state on my own, like in this example from the docs?
![image](https://github.com/react-hook-form/react-hook-form/assets/124572274/f59f37f5-db9c-4f5c-96de-646d7471c5ae)
