### ISSUE TITLE
issue: `FormProvider` causes unnecessary rerenders

### ISSUE THREAD

**Issue by srmagura** [react-hook-form/react-hook-form#10512]
### Version Number

7.44.3

### Codesandbox/Expo snack

https://stackblitz.com/edit/stackblitz-starters-mjdjbn?file=src%2FApp.tsx

### Steps to reproduce

In the Stackblitz, click the button several times. You will notice that the subcomponent render count increases each time you click the button.

### Expected behaviour

The subcomponent render count stays at 1 when clicking the button. 

The subcomponent is memoized and has no props, so it will only rerender if it subscribes to a React context whose value has changed. The fact that it does rerender shows that the `HookFormContext` value changes on every render, even if nothing about the form has changed.

If you look at the source code, you will see that `FormProvider` passes a new object to `HookFormContext.Provider` on each render:

https://github.com/react-hook-form/react-hook-form/blob/747ddcaef0a940a528e7e06d34afd144b924ebc1/src/useFormContext.tsx#L83

In this line of code, `data` will be a new object each time the component renders, even if none of the props changed.

## How this problem is usually solved

When passing multiple properties through a React context, you almost always want to use `useMemo` like this:

```tsx
const MyProvider = ({ children }) => {
  // const a = ...
  // const b = ...

  const value = useMemo(() => ({ a, b }), [a, b])

  return (
    <MyContext.Provider value={value}>
      {children}
    </MyContext.Provider>
  );
}
```

`FormProvider` should do something similar to this to prevent the unecessary rerenders.

## Comment about the existing documentation

There is a [documentation section](https://react-hook-form.com/advanced-usage#FormProviderPerformance) about the performance of `FormProvider`, but the solution shown there requires a LOT of boilerplate and only partially solves the performance issue.

## P.S.

Thank you for this great library!

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Thanks for reporting this, I am going to putting as a feature request, not a very high priority at the moment. Tried few approaches either increase package size quite a bit or result in staled props.

**Comment by mariosantosdev** [comment]
I noticed that it happens just when I called the `clearErrors` from the `useFormContext`, but the `setValue` for example works normally!

**Comment by ivan-kleshnin** [comment]
Yes, `clearErrors` unconditionally resets the error object, even when called for a single field like `clearErrors("email")`. 
Which in turn triggers a cascade of rerenders 😨
