### ISSUE TITLE
issue: (TS) `defaultValues` type converts `unknown` index signature type to `{} | undefined`

### ISSUE THREAD

**Issue by jviall** [react-hook-form/react-hook-form#10519]
### Version Number

7.44.3

### Codesandbox/Expo snack

https://codesandbox.io/s/rhf-bug-modified-index-type-s4wkk7?file=/src/App.tsx

### Steps to reproduce

This is completely a Types related issue. The error is present in the given sandbox as it stands. I'm also open to the possibility that there's nothing RHF can really do to address it considering it involves the assertion of `unknown` types.

Given a form field with a object type with an `unknown` index signature, e.g.:
```
type Field = {
  value: string;
  [key: string]: unknown;
 }
type FormFields = {
  field: Field; 
}
```

Attempting to assign a value of type `Field` to the `useForm`'s `defaultValues` prop gives the error:
`Type 'unknown' is not assignable to type '{} | undefined'`

My guess this is due to the implementation of RHF's `DeepPartial` type, or something similar, which is assigning a type other than `unknown` to the index signature, and making assignments impossible.

### Expected behaviour

I'm not sure if it's reasonable to expect the error not to occur. Though I am theoretically assigning a valid value of a type to another instance of the same type, it makes sense to me that somewhere along the way the `unknown` type is getting asserted to be something else by a type-generic library. If that's the case, I'd appreciate recommendations on what best practice to adopt to avoid this error.

In my case, I'm creating a generic combobox input part of a react design library, with an options type just like the codesandbox has. Changing the type from `unknown` to `any` fixes it, and maybe that is the best practice for generic types exported from a library, but if there are other recommendations I'd appreciate any insight.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
![image](https://github.com/react-hook-form/react-hook-form/assets/10513364/46b97e21-2e4e-4f5c-bcab-ccc0b4923df5)

Tried to exclude `unknown` as part of `DeepPartial`, this create heaps type errors in the tests
