### ISSUE TITLE
Custom validate functions on radio inputs trigger only after submitting the form.

### ISSUE THREAD

**Issue by jossensei** [react-hook-form/react-hook-form#1051]
Hello,

When registering an input radio field group with a custom validate function (on each radio field), the validate function is called only if the form has been submitted once.
Besides, the function can be called twice (once on mouse down, and once on mouse up).

An example :
https://codesandbox.io/s/react-hook-form-radio-validate-owyl9

**Comment by bluebill1049** [comment]
only register validation to one of them. If you want validation to trigger on change, set mode to 'onChange'

**Comment by jossensei** [comment]
I've tried to register only the first radio, but then, the validation is not triggered when I select the other options. And it doesn't resolve the validation problem that validate is triggered only after a submit.
https://codesandbox.io/s/react-hook-form-radio-validate-owyl9

I've tried another approach by registering the radio with useEffect, it triggers the validate function, but I've problems applying default values, and change the input when I trigger a setValue. I guess it's because of a missing ref or something.
https://codesandbox.io/s/react-hook-form-radio-validate-useeffect-register-liybm

**Comment by bluebill1049** [comment]
use triggerValidation for the others without validation method.

**Comment by jossensei** [comment]
Sorry, I can't get it working the the ref register. I've tried with triggerValidation and setValue(..., true), but with no effect.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-radio-validate-f9vzl

I think we can close now, please consider ask question in our spectrum channel.

**Comment by jossensei** [comment]
Ok, thank you ! The validation function is still called three time :a frist time because the last check radio is unchecked, a second time because the clicked radio is checked and the validation is triggered by the
