### ISSUE TITLE
Allow Form Submit to propagate.

### ISSUE THREAD

**Issue by dannybster** [react-hook-form/react-hook-form#10522]
**Is your feature request related to a problem? Please describe.**
With the introduction of React Server Components, it would be nice to allow form submission to propagate, i.e. use all the brilliant logic for validation and display built into this library but allow form submission to navigate to the next page essentially.

**Describe the solution you'd like**
I've only spent a small amount of time looking into this, but I believe it could be as simple as allowing a 3rd option to be passed to handle submit that specifies whether `e.preventDefault` is called e.g:

```
  const handleSubmit: UseFormHandleSubmit<TFieldValues> =
    (onValid, onInvalid, preventDefault) => async (e) => {
      if (e && preventDefault) {
        e.preventDefault && e.preventDefault();
        e.persist && e.persist();
      }
```

That being said, there is likely information/context I'm missing such as moving this check so that `e.preventDefault` is always called in the validation error path.

**Describe alternatives you've considered**
POSTing the form body in onValid.

[Note] If it is as simple as above and you believe the change to be suitable for this library, I'd be happy to create a PR.

**Comment by bluebill1049** [comment]
We can consider that for the new `<Form />` component, but this would not be the default behavior.

**Comment by dannybster** [comment]
Gotya, thanks for the quick update.

FYI: I'm opting to use the router to "push" to my next component with the form data appended to the URL in the onValid function if that's any use as you consider how to support server components/actions.
