### ISSUE TITLE
Consider export utils functions

### ISSUE THREAD

**Issue by xiaoyu-tamu** [react-hook-form/react-hook-form#1052]
**Is your feature request related to a problem? Please describe.**

Sometime, when I need to build advanced input ( write customize controller ) , I have to copy paste utils function from logic folder, i.e. isMatchFieldArrayName, isNameInFieldArray etc. I wish we could export these functions and people don't need to duplicate code that already exist.

I tried to import from dist folder but it does not work, please correct me if I miss something.

**Describe the solution you'd like** 
export utils functions

**Comment by bluebill1049** [comment]
It's already under the todo list: https://github.com/react-hook-form/react-hook-form/projects/1

We will come to it :) take a look the board.

**Comment by xiaoyu-tamu** [comment]
TY
