### ISSUE TITLE
issue: onSubmit data get changed by validation schema

### ISSUE THREAD

**Issue by stefanoinf** [react-hook-form/react-hook-form#10538]
### Version Number

7.44.3

### Codesandbox/Expo snack

https://codesandbox.io/s/rhf-bug-onsubmit-validation-6tlh6j

### Steps to reproduce

1. Leave empty the input "Name"
2. Insert "06-14-2023" in the input "Date"
3. Click "Submit" button
4. Watch the console.log, the parameter `data` of onSubmit method, contains `null` in the "name" field, and `Date` object in the "date" field. As you can see, the data have been edited by the validationSchema.
5. Watch the console.log of `getValues()`, it contains the right values, the values that I entered in the form.

### Expected behaviour

The `data` parameter should contains:
```
name: "",
data: "06-14-2023"
```

but instead it contains :
```
date: Wed Jun 14 2023 00:00:00 GMT+0200 (Ora legale dell’Europa centrale)
name: null
```

Why does `data` parameter get transformed by validationSchema?

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
you can set it to `raw: true` at resolver, so we don't return what's returned by the schema.

**Comment by stefanoinf** [comment]
> you can set it to `raw: true` at resolver, so we don't return what's returned by the schema.

thank you for the answer, sorry but I don't understand how to pass `raw: true` to the resolver. I tried to add it in the object returned by `useYupValidationResolver` but it didn't work. On the documentation I can't find it

**Comment by bluebill1049** [comment]
> > you can set it to `raw: true` at resolver, so we don't return what's returned by the schema.
> 
> thank you for the answer, sorry but I don't understand how to pass `raw: true` to the resolver. I tried to add it in the object returned by `useYupValidationResolver` but it didn't work. On the documentation I can't find it

https://github.com/react-hook-form/resolvers/blob/master/yup/src/yup.ts#L57

**Comment by stefanoinf** [comment]
ok I understood, thanks.

If someone has the same problem and is looking for a solution, if you are using the custom `useYupValidationResolver` function like me, you have to change the return from this:
```
return {
    values,
    errors: {}
};
```

to this:
```
return {
    values: data,
    errors: {}
};
```
If you are using [hookform/resolvers](https://github.com/react-hook-form/resolvers) library (that you probably should), you have to pass the `raw: true` to the resolver function (https://github.com/react-hook-form/resolvers#api), if I'm not wrong, something like this:
`yupResolver(schema, undefined, { raw: true })`

Thank you @bluebill1049.
