### ISSUE TITLE
Controlled Inputs should conform to HTML spec by allowing disabled prop and not sending disabled fields to submit

### ISSUE THREAD

**Issue by OliverLeighC** [react-hook-form/react-hook-form#10550]
There have been a number of issues opened about this (both bugs and feature requests) but they have all been closed without resolution and it is still a pressing issue.

https://github.com/react-hook-form/react-hook-form/issues/2655
https://github.com/react-hook-form/react-hook-form/issues/9883
https://github.com/react-hook-form/react-hook-form/issues/2826 (marked as waiting for up-vote in 2022 but it's been locked as resolved)

**Is your feature request related to a problem? Please describe.**

Currently, if you are using the controller or `useController` hook there is no support for disabling fields. You can prevent the user from editing them by putting disabled on the input component itself, but the default value will still get sent to submit which goes against how disabled fields are supposed to work according to the HTML spec. 

Passing disabled to `rules` on `useController` would still include them in the submit payload but at least they are undefined instead of a valid form value like null, but the disabled prop is omitted from the rules type for `useController` so it's not supported in typescript. 

This is especially a problem if you are disabling fields based on user entitlements, because even if a user can't edit the field in the UI the field is still part of the submit payload so if we don't add an extra step to strip that payload of disabled fields it will cause an error because the user is unknowingly submitting fields they don't have update access to.

**Describe the solution you'd like**

Controlled fields should support being disabled, either through allowing the disabled property on rules in the useController hook, or through some other way.

**Describe alternatives you've considered**

Use the transform function on edit and create to omit disabled fields. This is not a great alternative because the function needs to first determine which inputs are disabled which is not straightforward, and then removing them from the payload get's complicated for more complex forms with array inputs and nested fields.

Create a custom useController hook that wraps around the existing one and overrides the typescript error about passing disabled to rules. 

Neither of these solutions are great, but they also are basically impossible if you are using a library like react-admin, that uses react-hook-forms under the hood. 
 
**Additional context**

This has been requested before both as a feature and a bug, but all issues have been closed without a resolution. If this is something you don't plan on ever supporting or don't have the capacity to work on it would be helpful to at least get some clarity on that. 

I would also be open to submitting a PR if I had more understanding of why it's not currently supported or why it was explicitly omitted from the rules prop on useController (were there issues that it caused?).

**Comment by bluebill1049** [comment]
thanks for your feature request. We are considering including this in the next major version, to include such a feature would definitely bring a breaking change to an existing codebase. We have to consider other things, such as when users use resolvers with schema. So I would suggest using unregister method for now to remove the value. In fact, react hook form store form values in its own state instead of the dom itself.
