### ISSUE TITLE
issue: UseFormReturn properties like watch and getValues are typed "Required" instead of "Partial"

### ISSUE THREAD

**Issue by TheBlue-1** [react-hook-form/react-hook-form#10557]
### Version Number

7.44.3

### Codesandbox/Expo snack

https://codesandbox.io/s/awesome-hooks-s997mv

### Steps to reproduce

1. Create a form with useForm and a type but dont set the values yet like:
```
const {watch} = useForm<SomeObjectType>({ values:undefined }) // SomeObjectType contains a string value "propertyName"
```
2. Watch a part of the object like:
```
const watched = watch("propertyName") // type of  watched is now string 
```
3. Log the value like: 
```
console.log(watched) // logs undefined
```

### Expected behaviour

I would expect watch to return `string | undefined` if the value couöd be undefined

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BatuhanW** [comment]
Added a comment here, I think this breaking change should've released with a major version or new parameter should be added to the end, not into the middle.

https://github.com/react-hook-form/react-hook-form/pull/10543/files#r1234169168

**Comment by bluebill1049** [comment]
Please adjust your type for now, we want to move away from spatial in the next major, so it's probably a good habit to include that in your type definition. Deep Partial/Partaila will hopefully get removed in the next major release.

```
type FormValues = {
  firstName?: string;
};
```
