### ISSUE TITLE
Dirty-checking doesn't seem to work when resetting with a class instance in newer versions

### ISSUE THREAD

**Issue by asplem** [react-hook-form/react-hook-form#10563]
### Version Number

7.43.9 (issue exists in 7.37.0 and up, but we're using 7.43.9)

### Codesandbox/Expo snack

https://codesandbox.io/s/frosty-dust-4nvtp3

### Steps to reproduce

I'm not 100% sure this is a bug or by design, but it seems to have been introduced in a later version, and it is giving us some headache.

Usecase: We have some data being loaded asynchronously, so we need to do `reset `in order to load the form with the default values when this is loaded. This data comes in the form of class instances (thanks to NSwag and issues with interfaces and Date types). In the current version of react-hook-form, calling `reset `with a class instance seems to break dirty checking.

See https://codesandbox.io/s/frosty-dust-4nvtp3 for the broken version. If you wait a second to load the data, then try to change a field, `isDirty `remains false.

It looks like this was broken in 7.37.0.

If this isn't considered a bug, is there anything we can do to make this work, aside from spreading out the instance with all of its children everywhere, to make it not be a class instance?

### Expected behaviour

See https://codesandbox.io/s/polished-dream-93c8sm for a version using react-hook-form version 7.36.1, which as far as I can tell is the last version that actually worked.

In this one, dirty checking more or less works, though it doesn't revert back to not dirty when you go back to the initial values (which would be fine in our usecase, but obviously not optimal).

### What browsers are you seeing the problem on?

Firefox, Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is a limitation, we couldn't do diffing with custom object, Class or file object.

**Comment by asplem** [comment]
Thanks for the quick response. That's unfortunate, but good to get quick confirmation that we'll have to work around it 👍
