### ISSUE TITLE
issue: resetField cannot set defaultValue to undefined

### ISSUE THREAD

**Issue by Mighty683** [react-hook-form/react-hook-form#10565]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/holy-bash-xvszr3?file=/src/App.tsx

### Steps to reproduce

1. Select on select 4
2. Click Reset field button
3. Field is reset to previous `defaultValue` which is 1

### Expected behaviour

Value of defaultValue of field is set to undefined but it's not changed

Workaround is to set on reset value to `null`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Hi, this is expected behaviour non-undefined value, this applies to all `defaultValue`. We check undefined values to fallback to defaulVaues or defaultValue. I will update doc on this as well.

**Comment by Mighty683** [comment]
Wouldn't it be better to check if `options.defaultValue` property exists and use it value no matter of what is it? Since you can set `defaultValues: { input: undefined }` with `useForm` hook I would expect that `undefined` is valid value for `defaultValue`

**Comment by bluebill1049** [comment]
If you can solve this: https://github.com/react-hook-form/react-hook-form/blob/master/src/useController.ts#L57-L64 then we can support it.

**Comment by Mighty683** [comment]
I will try then
