### ISSUE TITLE
[feature request] submit only dirty fields

### ISSUE THREAD

**Issue by tnyo43** [react-hook-form/react-hook-form#10569]
**Is your feature request related to a problem? Please describe.**

When creating form, especially in the HTTP PATCH request method, I want to make it as it submits values only in the dirty fields, 
As it has been already discussed in https://github.com/orgs/react-hook-form/discussions/1991, we can create a method to pick up the values only in the dirty fields ourselves. However, I would really appreciate if the library could provide this feature.

**Describe the solution you'd like**

**The usage**
Add option to `handleSubmit` of `useForm`, like `onlyDirtyFields`. Then, we can use this feature as like follows:
(I copied and edit the code from https://www.react-hook-form.com/get-started/#Integratingwithglobalstate)
```js
import { useForm } from "react-hook-form";

export default function App({ onSubmit }) {
  const { register, handleSubmit } = useForm();

  return (
    <form onSubmit={handleSubmit(onSubmit, undefined, { onlyDirtyFields: true })}> // <- HERE, the second argument is `onInvalid`
      <input defaultValue="test" {...register("example")} />
      <input {...register("exampleRequired", { required: true })} />      
      <input type="submit" />
    </form>
  );
}
```

**Implementation**
Before calling `onValid` callback, we may be able to update/modify `fieldValues`.
https://github.com/react-hook-form/react-hook-form/blob/a4be81f842ab31decf34cc4c5f4fa2ebf2d74c12/src/logic/createFormControl.ts#L1065

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bluebill1049** [comment]
You have the dirty fields why not just write a function to abstract value from getValues?

**Comment by tnyo43** [comment]
I do write such a function myself at the moment.
That means that I need to maintain it to work properly. Also, if I work with other repository, I need to write it for each of them.

I think this is very common use-case, so I hope RHF to support the feature.

**Comment by extrememito** [comment]
Yes please. We're using PATCH requests all the time. I would be nice to have correct body directly from the library. Currently we're implementing this behavior ourselves.
