### ISSUE TITLE
issue: validation is gone after run reset() fn in case with custom register inside useEffect()

### ISSUE THREAD

**Issue by vitaly-shaposhnik** [react-hook-form/react-hook-form#10566]
### Version Number

7.45.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-reset-issue-9mgzp4

### Steps to reproduce

1. Click submit button -> no submit, show validation error
2. Click reset button -> here we run reset() fn
3. Click submit button again -> form submitted, no validation

### Expected behaviour

reset() fn shouldn't break form validation

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`register` will need to be re-run after `reset`

**Comment by vitaly-shaposhnik** [comment]
We do re-register now by adding extra state, but it looks like a temporary solution.
Is it an issue in reset function or it's a normal behaviour? Is it possible to do that somehow under the hood?

**Comment by bluebill1049** [comment]
nope it's expected behaviour with reset API.

**Comment by vitaly-shaposhnik** [comment]
Thank you for your answers!
