### ISSUE TITLE
issue: Version 7.45.0 introduced type error while using @mui/material select

### ISSUE THREAD

**Issue by extrememito** [react-hook-form/react-hook-form#10574]
### Version Number

7.45.0

### Codesandbox/Expo snack

https://codesandbox.io/s/goofy-leaf-mzkwr4

### Steps to reproduce

Use Select component from @mui/material@5.x library. 
Integrations of the component via `useController `hook produce type error now.
`onChange` methods type signatures are not compatible now. Before the update 7.45.0 everything worked fine.
Error: 
`Type '(event: PathValue<T, Path<T>> | ChangeEvent<Element>) => void' is not assignable to type '(event: SelectChangeEvent<PathValue<T, Path<T>>>, child: ReactNode) => void'.
  Types of parameters 'event' and 'event' are incompatible.
    Type 'SelectChangeEvent<PathValue<T, Path<T>>>' is not assignable to type 'PathValue<T, Path<T>> | ChangeEvent<Element>'.
      Type 'Event & { target: { value: PathValue<T, Path<T>>; name: string; }; }' is not assignable to type 'PathValue<T, Path<T>> | ChangeEvent<Element>'.
        Type 'Event & { target: { value: PathValue<T, Path<T>>; name: string; }; }' is missing the following properties from type 'ChangeEvent<Element>': nativeEvent, isDefaultPrevented, isPropagationStopped, persistts(2322)`

### Expected behaviour

Compiles without typescript errors

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/pull/10342#issuecomment-1602258751
