### ISSUE TITLE
Select onChange handler picks up previous value

### ISSUE THREAD

**Issue by maithuy** [react-hook-form/react-hook-form#1057]
Hi,
I have a Select option element, that the pre-defined value is set from useEffect(). The problem I'm facing is the handleChange picks up the previous option value, it takes a second click on the dropdown to get the correct value.

```
const [selectedTrigger, setTrigger] = useState("");

useEffect(() => {
    setTrigger(typeof data.triggers !== "undefined" && data.triggers[0] !== undefined ? data.triggers[0].name : "");
  }, [data, selectedTrigger]);
```

```
const handleTriggerChange = (e: any) => {
    setTrigger(e.target.value);
  };
```

```
<FormGroup>
            <Label for="trigger">Trigger</Label>
            <select
              className="form-control"
              ref={register({ required: "This field is required" })}
              name="trigger"
              id="trigger"
              onChange={handleTriggerChange}
              value={selectedTrigger}
            >
              <option value="" disabled>
                Select
              </option>
              {triggers.map((trigger: any, index: any) => (
                <option key={index} value={trigger.name}>
                  {trigger.displayName}
                </option>
              ))}
            </select>
            <small className="form-text error text-danger pb-2">{errors.trigger && errors.trigger.message}</small>
</FormGroup>
```
Thanks.

**Comment by bluebill1049** [comment]
please provide a CSB.

**Comment by maithuy** [comment]
Hi,

After porting the code to CSB and loading data to the form with hard-coded data, everything seems to work fine and select dropdown renders very fast.

My guest is feeding data to the form with api calls cause the state updates slowness and hence the select responds very slowly and takes more than 1 click.

Please let me if you have any suggestions.

https://codesandbox.io/s/react-hook-form-basic-ytv6j

Thank you.

**Comment by bluebill1049** [comment]
I guess if this is caused by async data, why dont you disable the select until the data is ready?
