### ISSUE TITLE
issue: nested form rendered in portal submits parent form first

### ISSUE THREAD

**Issue by maxsbelt** [react-hook-form/react-hook-form#10573]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/beautiful-joji-6zddwp?file=/src/App.tsx

### Steps to reproduce

1. Open sandbox. There are 2 forms. In react context parent form contains nested form but in html they are located in different nodes (nested form is rendered in portal).
2. Click submit.

### Expected behaviour

Expected behaviour:
Nested form will be submitted, parent remains the same

Actual behaviour:
Parent form will be submitted, nested remains the same. Both handleSubmit callbacks are executed (see console output).

If you click second time submit button nested form will be submitted. Both handleSubmit callbacks are executed (see console output).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I don't think this is react hook form question instead you probably should post at React.

**Comment by maxsbelt** [comment]
I see, thanks for rely

**Comment by maxsbelt** [comment]
I was able to solve the issue on my side. I added `e.stopPropagation()` call before `handleSubmit`.

```jsx
import { createPortal } from "react-dom";
import { useForm } from "react-hook-form";
import "./styles.css";

const NestedForm = () => {
  const form = useForm();

  const handleSubmit = form.handleSubmit(() => {
    console.log("handle nested submit");
  });

  return (
    <form
      onSubmit={(e) => {
        e.stopPropagation();
        handleSubmit(e);
      }}
    >
      <button type="submit">Submit</button>
      <br />
      Nested form state:{" "}
      {form.formState.isSubmitted ? "submitted" : "not submitted"}
    </form>
  );
};

export default () => {
  const form = useForm();

  const handleSubmit = form.handleSubmit(() => {
    console.log("handle submit 1");
  });

  return (
    <form onSubmit={handleSubmit}>
      {createPortal(
        <NestedForm />,
        document.getElementById("portal") as HTMLDivElement
      )}
      Parent form state:{" "}
      {form.formState.isSubmitted ? "submitted" : "not submitted"}
    </form>
  );
};


```
