### ISSUE TITLE
Disable all form fields

### ISSUE THREAD

**Issue by sushmitg** [react-hook-form/react-hook-form#1058]
Hi, I'd like to request a feature for react-hook-form. I'd like a way to disable the entire form so that the user cannot interact with the form and change default values in fields. Something like passing a boolean value to useForm()'s options.

**Comment by bluebill1049** [comment]
Thanks for the features request. I don’t think we will implement such feature to be a part of this lib at this stage.

**Comment by ShahriarKh** [comment]
Why? This feature is useful in some cases, for example, when you want to block a specific IP or user from filling a form, but see it and know it exists.
