### ISSUE TITLE
issue: resetField does not work with undefined/null

### ISSUE THREAD

**Issue by michael-vasyliv** [react-hook-form/react-hook-form#10599]
### Version Number

7.45.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/romantic-wildflower-zvywrr?file=%2Fsrc%2FApp.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/p/sandbox/romantic-wildflower-zvywrr?file=%2Fsrc%2FApp.tsx%3A14%2C11
2. Enter value 123 into input
3. click on r**eset field undefined** or **reset field null** or **Set value undefined** or **Set value null** or **reset**
4. see value in input 123

**resetField** as well as **reset** does not work

How can I quickly reset a form (which contains 20 fields with different types: array, number, string, boolean) without specifying a value for each field? I want to have undefined in each field, how can I do that?

### Expected behaviour

reset or resetField should work with undefined or null

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://react-hook-form.com/docs/useform/resetfield

> Only support non undefined value.

**Comment by michael-vasyliv** [comment]
@bluebill1049 how about null?
