### ISSUE TITLE
Type issue: FieldError does not cover nested objects from formState.errors

### ISSUE THREAD

**Issue by jonrajavuori-academia** [react-hook-form/react-hook-form#10601]
### Version Number

7.45.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-fielderror-type-issue-xh6yvs?file=/src/App.tsx

### Steps to reproduce

1. Go to the Codesandbox repro.

Type issue:
1. Scroll to line 215 (`{getError(formState.errors?.contact)}`) and confirm that there's a type error.
1. Scroll up to alternate definition of getError on line 49 (`// Uncomment next lines to fix error:`). Comment the original definition and uncomment this one.
1. Confirm that the type error is resolved.

Functionality (which works with either version of getError):
1. Click 'Trigger validation'.
1. Note that 'Required' message appears for 'contact' error at bottom of form, from line 215.

### Expected behaviour

It is expected that the FieldError type would also cover form properties whose value is a nested object. This is expected for multiple reasons:
- When using the zod resolver to validate the form, it can return errors for nested objects. This is shown in the repro for the 'contact' property.
- The FieldError type is otherwise used to indicate an error for any property in the form state, including nested objects - for instance, it is the type for `error` in `{ fieldState: { error }` in the render method args of Controller, when the Controller name is pointing to a nested object.
- The FieldError type is seemingly the only external type available to cover any error in the form, to provide typing for a common error message function or view component as in this example. There is a workaround with UseFormStateReturn, as demonstrated in the repro, but this is awkward and does not seem like an intended path. This workaround could point to a possible implementation fix, however. (I did not yet attempt this.)

### What browsers are you seeing the problem on?

_Not applicable - Type error_

### Relevant log output

Type error in full:
```shell
(property) contact?: Merge<FieldError, FieldErrorsImpl<NonNullable<{
    type: "email";
    email: string;
} | {
    type: "phone";
    phoneType: NonNullable<"home" | "work">;
    phoneNumber: string;
} | undefined>>> | undefined
Argument of type 'Merge<FieldError, FieldErrorsImpl<NonNullable<{ type: "email"; email: string; } | { type: "phone"; phoneType: NonNullable<"home" | "work">; phoneNumber: string; } | undefined>>> | undefined' is not assignable to parameter of type 'FieldError | undefined'.
  Type 'Merge<FieldError, FieldErrorsImpl<NonNullable<{ type: "email"; email: string; } | { type: "phone"; phoneType: NonNullable<"home" | "work">; phoneNumber: string; } | undefined>>>' is not assignable to type 'FieldError'.
    Types of property 'type' are incompatible.
      Type 'FieldError | LiteralUnion<"value" | "onChange" | "onBlur" | "shouldUnregister" | "required" | "min" | "max" | "maxLength" | "minLength" | "validate" | "setValueAs" | "disabled" | "deps" | "pattern" | "valueAsNumber" | "valueAsDate", string> | undefined' is not assignable to type 'LiteralUnion<"value" | "onChange" | "onBlur" | "shouldUnregister" | "required" | "min" | "max" | "maxLength" | "minLength" | "validate" | "setValueAs" | "disabled" | "deps" | "pattern" | "valueAsNumber" | "valueAsDate", string>'.
        Type 'undefined' is not assignable to type 'LiteralUnion<"value" | "onChange" | "onBlur" | "shouldUnregister" | "required" | "min" | "max" | "maxLength" | "minLength" | "validate" | "setValueAs" | "disabled" | "deps" | "pattern" | "valueAsNumber" | "valueAsDate", string>'.ts(2345)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is an expected type and not cover with nested objects. We are not further complicating the type of support with FieldError. There are workarounds one of them as what you have provided in the CSB.

**Comment by CodyMan0** [comment]
@jonrajavuori-academia Hi, is it solved!? I am in the middle of this Type Error, so i wonder if you solve it! please let me know if you check
