### ISSUE TITLE
Form validation with required taking an object does not work

### ISSUE THREAD

**Issue by tkatariya** [react-hook-form/react-hook-form#1060]
**Describe the bug**
When we use object inside register to make field required, its value is not taken into consideration,

**To Reproduce**
1. create a form
2. try changing bold value from true to false - this does not work

 <form onSubmit={handleSubmit(onSubmit)}>
      <label>Example</label>
      <input name="example" defaultValue="test" ref={register} />
      <label>ExampleRequired</label>
      <input
        name="exampleRequired"
        ref={register({
          required: { value: **true**, message: "test" },
          maxLength: 10
        })}
      />
      {errors.exampleRequired && <p>This field is required</p>}
      <input type="submit" />
    </form>

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-get-started-0hiz9

**Expected behavior**
value should work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrom]

**Comment by bluebill1049** [comment]
I am confused here... what's the bug here.

**Comment by tkatariya** [comment]
When i make value to false, still it gives error

**Comment by kotarella1110** [comment]
@bluebill1049 We need to fix the following line of `validationField.ts`.

https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/validateField.ts#L78-L98

**Comment by bluebill1049** [comment]
thanks @kotarella1110. but I don't see a point set to `false`, what sort of use case you are having?

**Comment by kotarella1110** [comment]
@bluebill1049 Type
definition allows `ValidationOptionObject` as well as `string`.
I think need allow to only string, or fix the logic.

https://github.com/react-hook-form/react-hook-form/blob/master/src/types.ts#L79

```ts
export type ValidationOptions = Partial<{
  required: boolean | string | ValidationOptionObject<boolean>;
  min: ValidationOptionObject<number | string>;
  max: ValidationOptionObject<number | string>;
  maxLength: ValidationOptionObject<number | string>;
  minLength: ValidationOptionObject<number | string>;
  pattern: ValidationOptionObject<RegExp>;
  validate: Validate | Record<string, Validate>;
}>;
```

**Comment by bluebill1049** [comment]
let's fix the logic, you want to take a lead on this one @kotarella1110 ?

**Comment by kotarella1110** [comment]
@bluebill1049 yeah! i will do this!
