### ISSUE TITLE
issue: arrays are not valid defaultValues for useForm hook

### ISSUE THREAD

**Issue by ozzyfromspace** [react-hook-form/react-hook-form#10619]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/rhf-array-watch-demo-5kyznw?file=/src/App.tsx

### Steps to reproduce

1. Set an array as `defaultValues` in the useForm hook.
2. Watch the output value. You will get an empty array.

### Expected behaviour

The useForm hook should pass the array set in `defaultValues` to the watch function.

Note: types are inferred correctly, so the compiler will not complain.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`defualtValues` type should be Record<string, T> instead of Array

**Comment by ozzyfromspace** [comment]
@bluebill1049 I see. It seems the generic type of useForm is FieldValues, which allows Arrays. Check it. I see your point about only using Records for default values though, but if you don't, the typescript compiler doesn't complain. The generic isn't ruling out arrays (and will predict arraylike structures in watch and other functions).
