### ISSUE TITLE
issue: useController not updating errors when value is date object (works good in 7.34.0)

### ISSUE THREAD

**Issue by alfrsvn** [react-hook-form/react-hook-form#10616]
### Version Number

7.45.1

### Codesandbox/Expo snack

https://codesandbox.io/s/stupefied-snyder-cxhm7l

### Steps to reproduce

1. Go to sandbox.
2. Submit the form to show errors.
3. Click on "today" button.
4. "dob" field error persists.

### Expected behaviour

"dob" field error should disappear after clicking "today" button, as it happens with "name" field when typing something in it.

The example works as expected just by downgrading to 7.34.0.

### What browsers are you seeing the problem on?

Firefox, Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please use validate for custom validation, new Date() would not consider as empty.

**Comment by alfrsvn** [comment]
Thanks for your response @bluebill1049 but I fail to understand how it's not a bug when it's updating the form values correctly but not the `formState: { errors }`, as it does for the name field.

**Comment by leapful** [comment]
@alfrsvn 

You are setting Date object as field value for `dob` without using any input element. Normally, if using input element, Date object will be serialized in to a Date string and then validation on field state will be correct, but now is a Date object therefore the validation has been conflicted and produced unexpected result.

If you want to apply the correct way, just use Date string for on change value of field `dob`

Working demo: https://codesandbox.io/s/cranky-napier-ftxksk?file=/src/App.js

**Comment by alfrsvn** [comment]
Thanks for your response, @leapful.

I have a project using `react-datepicker`. It handles the dates like this.
RHF's own docs show an example like this also:
https://react-hook-form.com/docs/usecontroller/controller

Same demo but this time using `react-datepicker`:
https://codesandbox.io/s/gifted-lalande-cl96nr

If it's not a bug, maybe a warning or a new example is needed there, @bluebill1049.
