### ISSUE TITLE
issue: defining Type for custom root error using FieldError breaks VS Code Intellisense

### ISSUE THREAD

**Issue by miller-productions** [react-hook-form/react-hook-form#10620]
### Version Number

7.45

### Codesandbox/Expo snack

tbc

### Steps to reproduce

Just following Bill's example here
> 
```
// declare root error type is optional
useForm<FormValues & { root: { random: FieldError } }>()
```

_Originally posted by @bluebill1049 in https://github.com/react-hook-form/react-hook-form/discussions/9691#discussioncomment-4595757_

When I do this in VS Code, it seems to kill intellisense. I need to remove the addition of `& { root: { random: FieldError } }` and reload window in order to recover it.

It happens as soon as I define the custom key as type `FieldError`. If I type it as, say for example, `any` then there is no issue.

Steps... 

1. Using Typescript 5.1.3 in VS Code
2. Define a Type for a custom root error, e.g. `useForm<FormValues & { root: { random: FieldError } }>()`
3. Note - in VS Code, Intellisense just dies, it no longer provides suggestions in any files
4. Go back and change the value from FieldError to any e.g. `useForm<FormValues & { root: { random: any } }>()`
5. Run command in VS Code Developer: Reload Window, Intellisense is back

### Expected behaviour

No impact to VS Code Intellisense

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report even without CSB, i am not sure there is much we can improve here tho.

**Comment by miller-productions** [comment]
Understood and agreed, it's potentially very local. I'm trying a few other things like disabling all plugins etc to try and narrow down the cause.

**Comment by miller-productions** [comment]
@bluebill1049 , you don't have an easy to reach vanilla demo repo at-hand with RHF latest & TS already built-in do you? i.e. so I can quickly clone it and see if this issue is related to my specific project workspace or if it is more at the global level for me. No drama if you don't, I'll set one up. Just being opportunistic here in case you happened to have one.

**Comment by miller-productions** [comment]
Have cloned a completely different project repo, upgraded its dependencies to RHF@latest (7.45.1) and Typescript@latest (5.1.6).

Add the following `= useForm<UserInput & { root: { serverError: FieldError } }>({`

Yep, issue occurs there also.

OK, so not project-specific. Environment

**Comment by miller-productions** [comment]
Have been doing a bit of reading to see if other similar previous issues are relevant to this one.

e.g. https://github.com/microsoft/vscode/issues/176018  &  https://github.com/react-hook-form/react-hook-form/issues/4237

What do you think?

It is definitely related to the `FieldError` type. As soon as that gets introduced in this way `& { root: { serverError: FieldError } }`, the issue appears.

**Comment by bluebill1049** [comment]
Unfortunately, This would be a design limitation for the library. 🙏
