### ISSUE TITLE
issue: useForm hook is not typed correctly when using async default values

### ISSUE THREAD

**Issue by nick-keller** [react-hook-form/react-hook-form#10625]
### Version Number

7.45.1

### Codesandbox/Expo snack

https://codesandbox.io/s/reverent-pond-mqh73c?file=/src/App.tsx

### Steps to reproduce

Simply provide an async function as `defaultValues`.

For instance, `handleSubmit` is typed like so:
```ts
const handleSubmit: UseFormHandleSubmit<() => Promise<{
    firstName: string;
    lastName: string;
}>>
```

### Expected behaviour

I would expect `handleSubmit` to be typed like so:
```ts
const handleSubmit: UseFormHandleSubmit<{
    firstName: string;
    lastName: string;
}>
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by milhamm** [comment]
I would like to try fixing this issue

**Comment by bluebill1049** [comment]
thanks very much @milhamm i will review this soon.

**Comment by milhamm** [comment]
sure do @bluebill1049 thanks

**Comment by MohJaber93** [comment]
Hi I am facing this issue but with another aspect

The handleSubmit type looks like this:
```
const handleSubmit: (onValid: SubmitHandler<undefined>, onInvalid?: SubmitErrorHandler<{
    mainFields: ProfileDataType;
    additionalFields: InfoDataType;
}>) => (e?: BaseSyntheticEvent<object, any, any>) => Promise<...>
```

Expected behaviour

```
const handleSubmit: (onValid: SubmitHandler<{
    mainFields: ProfileDataType;
    additionalFields: InfoDataType;
}>, onInvalid?: SubmitErrorHandler<{
    mainFields: ProfileDataType;
    additionalFields: InfoDataType;
}>) => (e?: BaseSyntheticEvent<object, any, any>) => Promise<...>
```

BTW, am passing the type to the useForm hook like this:

```
const {
    register,
    control,
    reset,
    formState: { errors },
    handleSubmit,
  } = useForm<{ mainFields: ProfileDataType; additionalFields: InfoDataType }>({
    defaultValues: {
      mainFields: initialMainFields,
      additionalFields: {},
    },
  });
```
