### ISSUE TITLE
issue: focus to a checkbox input does not work

### ISSUE THREAD

**Issue by abrahamcalsin** [react-hook-form/react-hook-form#10647]
### Version Number

7.45.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-focus-vmswh6

### Steps to reproduce

1. Go to [Codesandbox](https://codesandbox.io/p/sandbox/react-hook-form-focus-vmswh6) attached
2. See error
3. See [README](https://codesandbox.io/p/sandbox/react-hook-form-focus-vmswh6?file=%2FREADME.md%3A6%2C1) file for detailed description of the issue and expected behavior

### Expected behaviour

The code should compile. See a detailed discussion in the [README](https://codesandbox.io/p/sandbox/react-hook-form-focus-vmswh6?file=%2FREADME.md%3A6%2C1), which is copy pasted below in the hidden section.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
`display: none` tells the browser to not focus the checkbox `input`

**Comment by Moshyfawn** [comment]
`display: none` tells the browser to not focus the checkbox `input`. It's nothing to do with how RHF handles your input.
