### ISSUE TITLE
Expose the element from Controller / useController

### ISSUE THREAD

**Issue by makranczizoltan** [react-hook-form/react-hook-form#10649]
Currently, when using `Controller` / `useController`, only a subset of the "native" element ref is returned as the `ref` property on `formErrors` when validation fails. Sometimes, it'd be useful to return the whole element, not just the ones available today (`focus`, `select`, `setCustomValidity` and `reportValidity`).

I can think of a couple of alternatives to solve this:
1. The library could just set the whole elment as the ref, or
2. Expose the element on a new field, next to the fields available today
Of course, this all could and should live behind a configuration setting in `useForm`.

The only alternative I see is a custom solution, which shares the refs, but that's extra code.

**Additional context**
Example use case: Instead of the built-in focus error mechanism (focus & instant page jump), I could do a smooth scroll to the first invalid element.

**Comment by bluebill1049** [comment]
We did try to expose this, however, this ended up bringing breaking change and incompatibility with component libraries such as MUI, very sad that we couldn't just leverage the actual input ref itself. I don't see we will change this anytime soon in the current version, even with breaking change would probably be brought a lot of inconvenience to existing usages. I am going to close this for now.

**Comment by makranczizoltan** [comment]
Hi @bluebill1049 , no worries, thanks for looking into it, it's always good to understand the why behind the decisions!
