### ISSUE TITLE
Field validation / navigation order is wrong when mixing controlled and uncontrolled fields

### ISSUE THREAD

**Issue by saevarb** [react-hook-form/react-hook-form#10650]
### Version Number

7.45.1

### Codesandbox/Expo snack

https://codesandbox.io/s/ecstatic-orla-gyq8pq?file=/src/App.tsx

### Steps to reproduce

1. Focus first field
2. Hit enter without typing anything
3. Observe that you are taken to the second field instead of staying in the first field, which is also invalid
4. Type something in second field, hit enter
5. You are now taken to the first field

### Expected behaviour

I expect the fields to be navigated in the order they appear in the DOM.

If I change the second field to be controlled like the other one, this problem goes away.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we wouldn't be able to guarantee the focus order with controller and naitve input register.
