### ISSUE TITLE
issue: FieldPathByValue does not narrow down names by matching the field type

### ISSUE THREAD

**Issue by uelibaumgartner** [react-hook-form/react-hook-form#10669]
### Version Number

7.45.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-typescript-forked-6h28z4

### Steps to reproduce

Use the codesandbox

OR

Try to use the sample code provided on
https://react-hook-form.com/ts#FieldPathByValue

### Expected behaviour

I would expect the component not to accept the inputs for names that do have the corresponding value type of boolean (e.g. productName or createdAt). Based on the documentation provided in the type definition of FieldPathByValue:

`Type which eagerly collects all paths through a fieldType that matches a give type
Example:
FieldPathByValue<{foo: {bar: number}, baz: number, bar: string}, number>
  = 'foo.bar' | 'baz'
@typeParam:
TValue - the value you want to match into each type`

However, it seems to accept any names that are defined within TFieldValues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatiasCiccone** [comment]
> I am currently also experiencing an error in connection with FieldPathByValue.
> 
> ```
> export const Component= <
>   TFieldValues extends FieldValues = FieldValues,
>   TName extends FieldPathByValue<
>     TFieldValues,
>     string
>   > = FieldPathByValue<TFieldValues, string>({
>   name, control, required
> }: UseControllerProps<TFieldValues, TName>) => {
> 
>   const {
>     field: { value, onChange },
>     fieldState: { error },
>   } = useController({ name, control, rules: { required } });
>  ...
> ```
> 
> Type of value is `(property) value: PathValue<TFieldValues, TName>` but in my opinion it should be string | undefined. Same with onChange. `onChange("test")` gives me the type Error `Argument of type 'string' is not assignable to parameter of type 'PathValue<TFieldValues, TName> | ChangeEvent<Element>'.`

I'm having the same issue with some generic inputs I have based on MUI Autocomplete and Checkbox
