### ISSUE TITLE
issue: `watch` no longer gets synced for registers with default value

### ISSUE THREAD

**Issue by akamfoad** [react-hook-form/react-hook-form#10667]
### Version Number

7.45.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-7-45-1-defaultvalue-sync-bug-jznfyz

### Steps to reproduce

1. Go to the form
2. Check first checkbox, it has `false` as the default value, you can't change it because **watch**ed value is not updated.
3. Check first checkbox, it has `undefined` as the default value, you can change it because **watch**ed value is updated. 

### Expected behaviour

Its expected the **`watch`** function of a registered input to get the freshest value of the input, regardless of the configurations and settings of the form or the registration, be the value option or others.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Relevant log output

```shell
No error is logged, the UI return value from **watch**ed input doesn't update.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leapful** [comment]
@akamfoad 

You are setting default value which is always a fixed value to `value` option of `register()` method so it always resets your current input value to default value.

<img width="999" alt="Screenshot 2023-07-13 at 11 42 55" src="https://github.com/react-hook-form/react-hook-form/assets/18494222/37d72142-7710-43cb-b227-3f470a744acf">

Could you please explain why you cannot use `defaultValues` from `useForm()` hook ? Just switch to `defaultValues` will solve the issue. 

Working demo: https://codesandbox.io/p/sandbox/react-hook-form-7-45-1-defaultvalue-sync-bug-forked-fnvzdd?file=%2Fsrc%2FApp.tsx%3A29%2C24

**Comment by akamfoad** [comment]
That is strange its like the first time I see this doc :(

The stranger thing is that, we have used that for the past 1.6 years and it was working as expected, the behavior changed only after 7.45.1 patch release.

But I guess its possible to use the defaultValues from the form as you said, thanks @leapful
