### ISSUE TITLE
issue: `<input type="email" />` prevents react-hook-form to fill `errors` object correctly

### ISSUE THREAD

**Issue by Skazio** [react-hook-form/react-hook-form#10679]
### Version Number

7.45.1

### Codesandbox/Expo snack

https://stackblitz.com/edit/stackblitz-starters-qvhg84?file=src%2FApp.tsx

### Steps to reproduce

1. Dont fill any fields
2. Click `submit`
3. *errors for `required `show*
4. Fill the `Type: email` field
5. *error for `pattern` shows*

But if you
1. Fill all fields (for instance with `z`)
2. Click `submit`
3. *no errors are shown*

### Expected behaviour

Regardless of if we fill the fields or not, we should be able to see the errors

And if you remove the last `div` (under the `{/* Remove me and it will work as intended */}` comment), you can now follow both of the paths described above and it will work as intended

So the error might be caused by the `<input type="email" />`

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
import * as React from 'react';
import './style.css';
import { useForm } from 'react-hook-form';

export default function App() {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm();

  console.log(errors);

  return (
    <form
      onSubmit={handleSubmit((data) => {
        console.log(data);
      })}
    >
      <div>
        <label htmlFor="text">Type: text</label>

        <input
          id="text"
          type="text"
          {...register('text', {
            required: 'required',
            pattern: { value: /a/, message: 'regex error' },
          })}
        />

        <p>{errors?.text?.message.toString()}</p>
      </div>

      <div>
        <label htmlFor="email1">Type: text</label>

        <input
          id="email1"
          type="text"
          {...register('email1', {
            required: 'required',
            pattern: { value: /a/, message: 'regex error' },
          })}
        />

        <p>{errors?.email1?.message.toString()}</p>
      </div>

      {/* Remove me and it will work as intended */}
      <div>
        <label htmlFor="email2">Type: email</label>

        <input
          type="email"
          {...register('email2', {
            required: 'required',
            pattern: { value: /a@b/, message: 'regex error' },
          })}
        />

        <p>{errors?.email2?.message.toString()}</p>
      </div>

      <button type="submit">Submit</button>
    </form>
  );
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form

- `novalidate`
