### ISSUE TITLE
get form value mapped by elementID instead of name on Submit

### ISSUE THREAD

**Issue by maithuy** [react-hook-form/react-hook-form#1067]
Hi,

I have a form that each form element (either input or select) that the 'name' is dynamically generated. 

On Submit event, the form values are mapped with element name, ie.
```
{
   fieldname1: "m", 
   fieldname2: "g", 
   fieldname3: "h", 
   fieldname4: "m", 
   fieldname5: "m"
}

```

Would it be possible mapping the value with id instead?

Thank you.

**Comment by bluebill1049** [comment]
can you please provide a codesandbox for this question?

**Comment by maithuy** [comment]
@bluebill1049 
Here's the CSB https://codesandbox.io/s/react-hook-form-basic-pvj9o

Thanks

**Comment by bluebill1049** [comment]
This is not a precise example and will take time for me to understand, can you produce a simpler version?

**Comment by bluebill1049** [comment]
I think I get it now, using `id` instead of `name` attribute is not workable for this library.
