### ISSUE TITLE
issue: Incorrect dirtyFields after remove field

### ISSUE THREAD

**Issue by exsens** [react-hook-form/react-hook-form#10687]
### Version Number

7.45.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-st2jck?file=/src/index.tsx

### Steps to reproduce

1. Default values with > 1 fields
2. Remove first field
3. All fields isDirty
![image](https://github.com/react-hook-form/react-hook-form/assets/57532190/05015c56-d58d-4bbc-aa14-fb17a68d1403)
![image](https://github.com/react-hook-form/react-hook-form/assets/57532190/32854ba7-64a3-42fc-a5ed-47b8f72984e1)

### Expected behaviour

After remove fields dirtyFields is empty or only dirty fields

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
yes, expected as defaultValues dirty fields updated via diffing with current defaultValues with form values.

**Comment by exsens** [comment]
I set async defaultValue, how me get current dirty state after removing?

**Comment by exsens** [comment]
> yes, expected as defaultValues dirty fields updated via diffing with current defaultValues with form values.

I set async defaultValue, how me get current dirty state after removing?
