### ISSUE TITLE
issue: Type changes in 7.45.1 were breaking; unclear how to fix

### ISSUE THREAD

**Issue by benj-dobs** [react-hook-form/react-hook-form#10683]
### Version Number

7.45.1

### Codesandbox/Expo snack

https://codesandbox.io/s/condescending-elion-mv2rvd?file=/src/ControlledSelect.tsx

### Steps to reproduce

1. Change the react-hook-form version to 7.45.1
2. There is a type error in ControlledSelect.tsx
3. Change the react-hook-form version to 7.44.3. 
4. There is no longer a type error in ControlledSelect.tsx, and the components behave as you would expect them to.

### Expected behaviour

There should not be a type error.

(Note that `Select.tsx` in this example is standing in for a more complex component that uses [Radix UI](https://www.radix-ui.com/docs/primitives/components/select).)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by benj-dobs** [comment]
Basically, because this has made the type checking stricter, it now causes errors where there didn't used to be errors. I can see how `useController` is supposed to work if its type parameters are known at the point of usage, but I'm not sure how it's possible to use it now in generic components.

**Comment by bluebill1049** [comment]
reverted.
