### ISSUE TITLE
Problems resetting Controller

### ISSUE THREAD

**Issue by stramel** [react-hook-form/react-hook-form#1069]
**Describe the bug**
There are a couple of issues here:

1. When `defaultValues` is NOT passed to the `useForm` hook, the `reset` method fails to reset `Controller` controlled components.
2. When `defaultValues` IS passed to the `useForm` hook, the `reset` method fails to reset `Controller` controlled components when passed `{}`.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-rhfinput-9l5m0

**Expected behavior**
I would expect the `reset` method to reset the `Controller` controlled components without the need for `defaultValues` and when passing `{}` to `reset`.

**Screenshots**
https://t.co/pyJuyD3SpF?amp=1

**Desktop (please complete the following information):**
 - OS: Windows, Mac OSX
 - Browser: Chrome
 - Version: 79

**Additional context**
- When `defaultValues` is passed and nothing is passed to `reset` it does work.
- When `defaultValues` is NOT passed, conditionally rendered `Controller`s DO properly reset.
- When `defaultValues` is passed and `reset` is called with `defaultValues` it DOES properly reset.

**Comment by vensauro** [comment]
I have this issue after update the lib to 4.9.8

**Comment by bluebill1049** [comment]
what's the issue?

**Comment by vensauro** [comment]
ops, i deleted the comment because was examining, sorry
with the defaultValue in prop, the TextField is not reseted

here is an sandbox: [example](https://codesandbox.io/s/confident-noyce-srny1)

**Comment by bluebill1049** [comment]
looks like it's working for me. @vensauro

**Comment by vensauro** [comment]
the second input in the sandbox is reseting?
on here this is not getting the value 'filedd'

**Comment by bluebill1049** [comment]
oh let me double check.

**Comment by vensauro** [comment]
![Screen record from 2020-02-24 20 58 47](https://user-images.githubusercontent.com/41435789/75201933-8fcc1580-5748-11ea-903f-c5c0a0ec7e44.gif)

**Comment by bluebill1049** [comment]
oh it's due to `defaultValue=""` can you set defaultValues instead? we made a proper fix now, inline `defaultValue` take priority over `defaultValues`

**Comment by vensauro** [comment]
yeah, i can do it, thanks for the answer ^^

**Comment by bluebill1049** [comment]
Welcome @vensauro
