### ISSUE TITLE
issue: `useController` Causes Watched FieldArray to Not Update

### ISSUE THREAD

**Issue by YTakahashii** [react-hook-form/react-hook-form#10692]
### Version Number

7.45.1 or higher

### Codesandbox/Expo snack

https://codesandbox.io/s/hook-form-represent-example-20230720-h4k9gg?file=/src/App.tsx

### Steps to reproduce

1. Open Codesandbox.
2. Click on the 'Edit Comics' button.
3. Click on the 'Append' button.
4. In the added input, type 'ONEPIECE'.
5. Click on the 'Submit' button.

### Expected behavior

The `watchComics` list should update to include both 'Naruto' and 'ONEPIECE', the same as the `FieldArray Comics` list.

### Actual behavior

Only the `FieldArray Comics` list updates. The `watchComics` list does not update.

### FYI
 * Version 7.45.0 or lower will correctly update `watchComics`.
 * Commenting out `useController` will update `watchComics` correctly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcmujica** [comment]
Same issue, stopped working after update

**Comment by Tsymalyi** [comment]
yes, some problem caught after update(

**Comment by Khailini** [comment]
Same Issue here.

**Comment by intpp** [comment]
I have the same problem. Up :)

**Comment by bluebill1049** [comment]
reverted the issue commit: 3ca17019c86535a331e32b465019ec25bbbf02fb

**Comment by YTakahashii** [comment]
@bluebill1049 
Thank you for your swift investigation and resolution. 🙌
