### ISSUE TITLE
issue: Controller render update previous values sometimes

### ISSUE THREAD

**Issue by mike667** [react-hook-form/react-hook-form#10696]
### Version Number

7.45.1

### Codesandbox/Expo snack

-

### Steps to reproduce

Hello, we use react-hook-form in out project. After updating to version 7.45.1 we have strange issues with our watch('fieldName') variables. We use it for conditional rendering another fields. I found this [pull request](https://github.com/react-hook-form/react-hook-form/pull/10586). We have custom form fields, which work inside Controller, now when controller update on each render looks like sometimes it override current form value by old value. We cannot remove Controller component and cannot fix that bug, because it set variable under hood. It also difficult to reproduce without our code base. Rollback to version 7.45.1  fixed that issue. Here is example component:

```
<Controller
      control={control}
      name={fieldName}
      render={({ field, formState: { errors } }) => {
        const { ref, value, onChange } = field;
        const error = path<FieldError>(fieldName.split("."), errors);

        return (
          <TextField
            ref={ref}
            label={label}
            value={value ? value : multiple ? [] : ""}
            onChange={onChange}
            multiple={multiple}
            disabled={disabled}
            error={!!error}
            helperText={error?.message}
          >
            {getCategoriesJSX(optionsByCategory, multiple, value)}
          </TextField>
        );
      }}
    />
```

### Expected behaviour

I don't know what this "update value on each Controller render" feature fixes. But it broke our functionality. I expect updating my form values only when I call onChange function. Could you help me with that?

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by leapful** [comment]
@mike667 

Please provide a codesandbox url to re-produce the issue. Only a part of your code implementation does not help to investigate the problem.
