### ISSUE TITLE
[useFieldArray] Improve the DX of register

### ISSUE THREAD

**Issue by stramel** [react-hook-form/react-hook-form#1070]
**Is your feature request related to a problem? Please describe.**
Pulling this improvement discussion out of the previous PRs and into an issue to easily track. See the bottom for related discussions and PRs.

Basically, you can't call `ref={register}` with `useFieldArray`. This is very counter-intuitive based on the fact that the library allows for this syntax in other components/hooks.

**Describe the solution you'd like**
Would like to be able to use `ref={register}`

**Describe alternatives you've considered**
Could remove that syntax entirely. In practice, I'm not sure how much it is used and is only saving a few characters `()`

**Additional context**
https://github.com/react-hook-form/react-hook-form/pull/896#discussion_r370429677
#916 

@kotarella1110 @bluebill1049

**Comment by bluebill1049** [comment]
Some background info around `ref` callback as i have spent quite bit time on the investigation.

```
const test = () => {}
ref={test} // will called twice mount/unmount 

ref={() => {}} // called each time with mount, unmount and remount
```

**Comment by kotarella1110** [comment]
@bluebill1049 Hmm... I don't think so.
The result of tried in example is as follows.

codesandbox: https://codesandbox.io/s/rhf-issues-1070-eeodn

```ts
const test1 = useCallback(() => {}, [])
const test2 = () => {}

ref={test1}    // will called twice mount/unmount
ref={test2}    // called each time with mount, unmount and remount
ref={() => {}} // called each time with mount, unmount and remount
```

**Comment by bluebill1049** [comment]
@kotarella1110 try that in a ‘map’

**Comment by kotarella1110** [comment]
@bluebill1049 Have you checked codesandbox?

**Comment by bluebill1049** [comment]
I did , thanks @kotarella1110 Give it a try with actual codebase, there is a route just for useFieldArray in the automation app: `yarn app:start`

**Comment by kotarella1110** [comment]
I think the difference between `ref={register}` and `ref={register()}` is whether we are using `useCallback`.

* `ref={regsiter}`:  passed to `ref` is `useCallback(registerFieldsRef, [defaultValuesRef.current, defaultRenderValuesRef.current])`
* `ref={regsiter()}`:  passed to `ref` is `registerFieldsRef`

```ts
ref={regsiter}   // will called twice mount/unmount
ref={regsiter()} // called each time with mount, unmount and remount
```
