### ISSUE TITLE
issue: Watch, shouldRegister true and StrictMode

### ISSUE THREAD

**Issue by AmitNeuhaus** [react-hook-form/react-hook-form#10700]
### Version Number

v7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/damp-https-qwfyj6?file=/src/index.js

### Steps to reproduce

Go to ['...'](https://codesandbox.io/s/damp-https-qwfyj6?file=/src/index.js)
disable strict mode.
When clicking checkbox the input does un-mounts and mounts accordingly and works expectedly when clicking submit.
However the watch api seems to miss the default value when the input does re-mount, even though input does have the correct in state and also appears in the data submission.
When adding the StrictMode again it seems like the watch api works as expected and does print the correct value after remount.

I guess i'm missing something with how strict mode is working under the hood but what should be expected in production when relying on the value from watch?

### Expected behaviour

Watch api should contain the default value after remounting on shouldUnregister : True.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
What's the issue in here: 
<img width="435" alt="image" src="https://github.com/react-hook-form/react-hook-form/assets/10513364/c0704ea7-037e-4a1f-bbe2-7995a0625cd7">
