### ISSUE TITLE
issue: No error returned in resolver when input is a radio

### ISSUE THREAD

**Issue by pom421** [react-hook-form/react-hook-form#10708]
### Version Number

7.45.2

### Codesandbox/Expo snack

https://codesandbox.io/s/bug-rhf-zod-radio-button-error-vntlxz?file=/src/TestForm.tsx

### Steps to reproduce

1. Go to code sandbox. Fill 5 to the result input. The radio below must be disabled.
2. Fill 4 now to the result input. The zod resolver find a problem, a custom error to the path "populationFavorable".
3. See error: the error of RHF is empty. However, the error returned by the resolver sees the error on populationFavorable. 

What I think, it's because the populationFavorable is a radio, there is not a unique ref for it. In fact, when the error in zod is affected to the result input, the error is returned in a ref. But it seems the resolver doesn't find any ref for radio button. Which is understandable because radio button has 2 refs. 
But how to handle these case? 

<img width="777" alt="image" src="https://github.com/react-hook-form/react-hook-form/assets/3749428/0f0d5a4a-f71a-4d9d-9791-e4ee2f0e61c4">

<img width="758" alt="image" src="https://github.com/react-hook-form/react-hook-form/assets/3749428/206e2dd6-c2b5-40a8-a2d7-647b2efa614a">

### Expected behaviour

At least, the errors returned by RHF should return the error, to give developer the opportunity to handle it programmatically, even if there is no associated ref. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pom421** [comment]
The problem is only present with onChange validation. In this case, RHF doesn't find the ref for the radio input. 

But when we submit, then the ref is found and the error is reachable in the render.

**Comment by pom421** [comment]
Also, the isValid is correctly set to false, when there is an error, even if the error object is empty.

**Comment by bluebill1049** [comment]
```tsx
resolver: async (data, context, options) => {
  // you can debug your validation schema here
  console.log("formData", data)
  console.log(
    "validation result",
    await anyResolver(schema)(data, context, options)
  )
  return anyResolver(schema)(data, context, options)
}```

you can use the above code to validate the issue.

**Comment by pom421** [comment]
Hi Bill. I already use this code to see what's happening, you can see it in the sandbox. 

And you see that there is an error returned in the resolver function, but not in the react component. I suppose that it's because there is no ref in the error message object. 

I use the onChange mode, so there should return an error in the component. However, it is only returned when I click on submit.

**Comment by bluebill1049** [comment]
> And you see that there is an error returned in the resolver function, but not in the react component. I suppose that it's because there is no ref in the error message object.

I think that would be the case.
