### ISSUE TITLE
issue: since v7.45.1 ReactDatePicker onChange does not affect validation

### ISSUE THREAD

**Issue by undefinederror** [react-hook-form/react-hook-form#10710]
### Version Number

7.45.1

### Codesandbox/Expo snack

https://stackblitz.com/edit/stackblitz-starters-yay4gw

### Steps to reproduce

v 7.45.1
1. Go to https://stackblitz.com/edit/stackblitz-starters-yay4gw
2. Click on Submit
3. Observe form state controls errors
4. Fill in "Text"
5. Observe form state `text` error disappear
6. Fill in "Calendar"
7. Observe form state `calendar` error does NOT disapper

v 7.45.0
1. Go to https://stackblitz.com/edit/stackblitz-starters-ee116c
2. Click on Submit
3. Observe form state controls errors
4. Fill in "Text"
5. Observe form state `text` error disappear
6. Fill in "Calendar"
7. Observe form state `calendar` error DOES disapper

### Expected behaviour

behaviour until 7.45.0 is what is to be expected

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Switch to the latest.

**Comment by undefinederror** [comment]
Latest is indeed the version where I encountered the issue. The problem has existed since v7.45.1. I have updated the repro https://stackblitz.com/edit/stackblitz-starters-yay4gw

Please reopen the issue.
