### ISSUE TITLE
issue: e.focus is not a function

### ISSUE THREAD

**Issue by thebat93** [react-hook-form/react-hook-form#10714]
### Version Number

7.45.2

### Codesandbox/Expo snack

https://codesandbox.io/s/beautiful-joji-lmy4gm?file=/src/App.tsx

### Steps to reproduce

1. Go to the sandbox
2. Click on Submit
3. See error `TypeError: e.focus is not a function`

### Expected behaviour

No error should throw.

The error reproduces when you register a custom form field with validation where ref defined with `useImperativeHandle` and doesn't have `focus` method.
I use DatePicker from RSuite and its ref doesn't have this method:
https://rsuitejs.com/components/date-picker/
https://github.com/rsuite/rsuite/blob/main/src/DatePicker/DatePicker.tsx#L251
https://github.com/rsuite/rsuite/blob/main/src/Picker/utils.ts#L650

The source of the issue is here:
https://github.com/react-hook-form/react-hook-form/blob/011fad503cc8d4543892f8e847b9bd58c1d9400f/src/useController.ts#L145

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
omit that ref in the first place which doesn't have focus event.
