### ISSUE TITLE
issue: useWatch return type is incorrect when providing the TFieldValues

### ISSUE THREAD

**Issue by csantos-nydig** [react-hook-form/react-hook-form#10716]
### Version Number

v1.2.0

### Codesandbox/Expo snack

https://codesandbox.io/s/lucid-taussig-lrcrr2?file=/src/App.tsx

### Steps to reproduce

1. Hover over the constants `age`, `age2`, `age3`, `age4` to be the different types

<img width="413" alt="Screenshot 2023-07-26 at 10 36 30 AM" src="https://github.com/react-hook-form/react-hook-form/assets/87080313/4ce5b4e8-582e-41c6-bb27-807880e4c7a9">

<img width="481" alt="Screenshot 2023-07-26 at 10 36 36 AM" src="https://github.com/react-hook-form/react-hook-form/assets/87080313/07fd3f10-f511-45aa-ab9e-1af650d8f548">

<img width="579" alt="Screenshot 2023-07-26 at 10 36 42 AM" src="https://github.com/react-hook-form/react-hook-form/assets/87080313/4ec9f9b4-3c14-4582-a0db-d12f80d11f7b">

<img width="545" alt="Screenshot 2023-07-26 at 10 36 49 AM" src="https://github.com/react-hook-form/react-hook-form/assets/87080313/a6014f18-d279-40eb-a37b-aefb30ac1e67">

2. Notice `age4` type is including the types for all fields

### Expected behaviour

I expect the return type to be of the correct type when I provide the `TFieldValues` to `useWatch` (`age4` in the Codesandbox should be of type `number`)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Additional context

- `age`: expected to return any because nothing is typed/inferred
- `age2` & `age3`: https://github.com/react-hook-form/react-hook-form/issues/4532#issuecomment-808607173 - It works when I provide the `control` (from `useForm` or from `useFormContext`)
- `age4`: https://github.com/react-hook-form/react-hook-form/issues/4532#issuecomment-810738583 - It doesn't work

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Not such type support at this stage.

**Comment by csantos-nydig** [comment]
Hey @bluebill1049 thanks for taking a look at this, just to triple check before I move forward with a different approach:

https://github.com/react-hook-form/react-hook-form/issues/4532#issuecomment-810738583

> ... for context API, I think you will have to use the generic at the useWatch.

This suggestion isn't correct then?
