### ISSUE TITLE
`useWatch<T>()` (parameterless) and  `watch` type from the `useFormContext` have different types

### ISSUE THREAD

**Issue by Zetxus** [react-hook-form/react-hook-form#10721]
Not quite sure whether to categorize this as a bug as it seems to me that this is a design decision, so I'll hold off on that for now.

Using `useWatch<T>()` (without providing any parameters) returns a deep partial unlike the `watch` type from `useFormContext`. This results in having to either cast the result to the non-partial value (`T`) or `@ts-ignore` the type in order to get my defined type instead of the deep partial one. 

I can't actually just use the `useFormContext#watch` because that results in infinite updates when I try to use it the same way I use `useWatch` and gives me performance issues so I've moved away from using it even though the typing there is what I need.

A possible workaround is to modify the data model and add a new level like so:

```ts
import { useWatch } from "react-hook-form";

type Form = {
  name: string;
  age: number;
};

type HelperText = {
  form: Form;
};

const data = useWatch<Form>();

const nonPartialData = useWatch<HelperText, 'form'>({ name: 'form' });

data.age; // number | undefined
data.name; // string | undefined

nonPartialData.age; // number
nonPartialData.name; // string
```

but that feels like a workaround. It would be nice to be able to use the non deep partial type just like useContext's watch does it, unless there's a reason for the type being like this and it would go against react-hook-form's intended design.

_Originally posted by @Zetxus in https://github.com/react-hook-form/react-hook-form/discussions/10610_

**Comment by PupoSDC** [comment]
Experiencing the same issue with `7.45.2`. 
<img width="551" alt="image" src="https://github.com/react-hook-form/react-hook-form/assets/9625304/0f590175-7f5e-4b55-bc48-40c3a9005322">
<img width="584" alt="image" src="https://github.com/react-hook-form/react-hook-form/assets/9625304/908c563a-ca7a-4b07-aa32-0455f9a61885">

**Comment by bluebill1049** [comment]
Please follow the issue template and resubmit an issue with TS playground or codesandbox.

**Comment by Zetxus** [comment]
@bluebill1049 Not sure what more you're going to see from a codesandbox but here's the new issue: https://github.com/react-hook-form/react-hook-form/issues/10734
