### ISSUE TITLE
issue: custom field using `<Controller/>` not focusing

### ISSUE THREAD

**Issue by ShaiGilboa** [react-hook-form/react-hook-form#10720]
### Version Number

7.25.3

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-controller-ts-forked-spzhsc?file=/package.json:369-375

### Steps to reproduce

1. Go to https://codesandbox.io/s/react-hook-form-v7-controller-ts-forked-spzhsc?file=/package.json:369-375
2. Click on button labelled: `set focus on Controller field`
   a. wrong input is being focused 
3. add at least 2 chars in input labelled: `uncontrolleredTextField`
  a. click on submit button (labelled `Submit`)
  b. controlled input is not being focused on, even though it is required, and appears in `errors` object

See error

### Expected behaviour

I might be wrong, and if I am then I apologize, but I think that the expected behaviour will be to have the controlled field focused on error.
if I am missing something, and you know where I can find the docs to explain, please send a link my way 😉 

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
missing input reference for hook form to call `focus`

**Comment by ShaiGilboa** [comment]
Thanks for the quick reply! 
and sorry for not understanding...
but this is taken from the example in the docs: https://www.react-hook-form.com/api/usecontroller/controller/
the code sandbox: https://codesandbox.io/s/react-hook-form-v6-controller-ts-jwyzw
it has the text input as: 
```jsx
          <section>
            <label>MUI TextField</label>
            <Controller
              render={({ field }) => <TextField {...field} />}
              name="TextField"
              control={control}
            />
          </section>
```

---
I thought that the `field` prop, coming in the `render` should have the `ref` for the input - and that that should be passed by spreading it as props, no?

thanks again for the assistance, and if this is not the correct place for these places I apologize. if you know of a place better suited please let me know :) 

have a great day!

**Comment by ShaiGilboa** [comment]
> missing input reference for hook form to call `focus`

Thanks for the quick reply! 
and sorry for not understanding...
but this is taken from the example in the docs: https://www.react-hook-form.com/api/usecontroller/controller/
the code sandbox: https://codesandbox.io/s/react-hook-form-v6-controller-ts-jwyzw (line 139)
it has the text input as: 
```jsx
          <section>
            <label>MUI TextField</label>
            <Controller
              render={({ field }) => <TextField {...field} />}
              name="TextField"
              control={control}
            />
          </section>
```

---
I thought that the `field` prop, coming in the `render` should have the `ref` for the input - and that that should be passed by spreading it as props, no?

thanks again for the assistance, and if this is not the correct place for these places I apologize. if you know of a place better suited please let me know :) 

have a great day!

**Comment by stretch0** [comment]
@ShaiGilboa, you're buttons are acting as "submit" buttons on your form. So when you click either of them, they are trying to submit your form. That coupled with `shouldFocusError: true` is causing the form to focus on the inputs with errors. This explains why when you click `set focus on Controller field` button, it is focusing on the `uncontrolleredTextField
` field. 

However, if you set your buttons to `type=button`, it stops it from trying to submit but there does still seem to be an issue with setting focus to the controlled text field which I can't yet understand why that's happening.

**Comment by ShaiGilboa** [comment]
@stretch0 thanks! (I updated the codesandbox to have `type="button`)
do we know if is this an issue in my implementation? or in the library?

**Comment by stretch0** [comment]
After further investigating, it seems like an issues specific to material UI (in your case the `<TextField />` component).

I have managed to get `setFocus` working with a plain HTML `<input />` element as you can see in this [sandbox here](https://codesandbox.io/s/react-hook-form-v7-controller-ts-forked-v49ymc?file=/src/index.tsx).

I am not familiar enough with the `react-hook-form` so open to somebody else to chime in but I suspect it's an issue with the props being passed down from the `Controller` component or it could be an issue on MUI's side with how the component is receiving the required props.

**Comment by stretch0** [comment]
I have just figured it out so I thought I would update for anybody else trying to get it working:

The issue stems from the `ref` not being passed to the input correctly in MUI. We need to pass `ref` in the `inputRef` prop of `<TextField />` and similar components  because we want the ref attached to the input and not the wrapping components.

Therefore, you have to do something like this:

```
<Controller
  name="controlledInput"
  control={control}
  render={({ field, ...rest }) => (
    <TextField 
      inputRef={field.ref}  // notice we map ref to inputRef
      name={field.name}
      value={field.value}
      onChange={field.onChange}
      onBlur={field.onBlur} 
    />
  )}
/>
```

I am explicitly passing the rest of the props in to avoid the ref getting assigned elsewhere. Doing something like this would cause our `field.ref` to be the reference for the `<TextField/>` component (the elements that wrap our input).

```
<Controller
  name="controlledInput"
  control={control}
  render={({ field, ...rest }) => (
    <TextField 
      inputRef={field.ref} 
      {...field} // avoid spreading like this
    />
  )}
/>
```

Maybe it's worth updating the react-form-hook docs to make this more clear? Happy to raise a PR if this is useful?
