### ISSUE TITLE
issue: useWatch<T>() (parameterless) and watch type from the useFormContext have different types

### ISSUE THREAD

**Issue by Zetxus** [react-hook-form/react-hook-form#10734]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/adoring-shadow-zgr3rd?file=/src/App.tsx

### Steps to reproduce

Recreated from https://github.com/react-hook-form/react-hook-form/issues/10721 using the template as the GitHub "new issue" from discussion functionality skips your templates. 

1. Go to Example1
2. See the types comparison between `useWatch<Form>()` and `useFormContext<Form>()`
3. Go to Example2
4. See the workaround that gets rid of the deep partial

Description:
Using `useWatch<T>()` (without providing any parameters) returns a deep partial unlike the watch type from `useFormContext`. This results in having to either cast the result to the non-partial value (`T`) or @ts-ignore the type in order to get my defined type instead of the deep partial one.

I can't actually just use the `useFormContext#watch` because that results in infinite updates when I try to use it the same way I use `useWatch` and gives me performance issues so I've moved away from using it even though the typing there is what I need.

You can see the `Example2` file for the usage of a nested property to avoid getting deep partials. 

### Expected behaviour

I expect that the types would be the same between the two. Unless it's some design decision for some specific case, to me it doesn't make sense for it to be a deep partial. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SebDelile** [comment]
Hello,
I ran into the same issue, thanks for the work around ! it does the job for now but a fix would be appreciate :)

the workaround doesn't work if you want to export only few properties from useWatch(), but in this case you can retype the propertys instead of typing useWatch : 

`const [foo, bar]: [FooType, BarType] = useWatch({ name: ['foo', 'bar'] });`

**Comment by Zetxus** [comment]
Hey @SebDelile sorry for the delayed response. 

I didn't actually consider using `as` because it kind of "forces" your type to comply by casting it. In my experience that usually results in other problems in the future. 

That's why I went with increasing the depth of the properties instead, but it would be cool if react-hook-form could handle this without the need to modify the original data format (as you mentioned that could be uncomfortable to work with).
