### ISSUE TITLE
value not getting set with <Controller> and setValue in its onChange

### ISSUE THREAD

**Issue by AditShah** [react-hook-form/react-hook-form#1074]
**Describe the bug**
When using Controller to wrap SelectBox, I use setValue in my onChange rather than returning the value, but value is not getting updated.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-controller-with-setvalue-exhwt

**Expected behavior**
Either value is returned or set manually, in both cases value should be updated.

**Comment by bluebill1049** [comment]
The codesandbox is broken, why you attach onChange with setValue? that's not the correct usage.

**Comment by AditShah** [comment]
Sorry for broken codesandbox, I have updated it. My question is it should work both ways because it serves same purpose. Can you please elaborate the difference between both approaches? 

Thank you for your time

**Comment by AditShah** [comment]
My use case: I want to listen to onChange of all formFields and make them call onChange passed to them in prop. Then there is some controlling logic in my FormContainer and then all values are set manually for all fields, but values were not getting updated. Can you please help me the with the correct approach for this use case?

**Comment by bluebill1049** [comment]
you can still attach onChange but just make sure you return the value

onChange={(e) => {
  // still can do your logic here
  return e.target.value;
}}
