### ISSUE TITLE
Validate and submit form by clicking on an external component

### ISSUE THREAD

**Issue by reginaldoddm** [react-hook-form/react-hook-form#1076]
How can I validate and submit a form by clicking on an external component?

In the example below the form is sent without going through validation.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-cbc8c

**Comment by bluebill1049** [comment]
`handleSubmit(onSubmit)()`

**Comment by reginaldoddm** [comment]
> `handleSubmit(onSubmit)()` should be your answer. let me know if this doesn't solve your problem :)
Thanks.
I need the event to be fired from a parent component

**Comment by bluebill1049** [comment]
consider move useForm to parent component :)
