### ISSUE TITLE
issue: `watch` with path traversal forgets nullishness

### ISSUE THREAD

**Issue by danielnixon** [react-hook-form/react-hook-form#10770]
### Version Number

7.45.4

### Codesandbox/Expo snack

https://codesandbox.io/s/red-river-6p7k2x?file=/src/App.tsx

### Steps to reproduce

1. Use `watch` with a nested path where an element higher in the tree can be null or undefined but the leaf can't, like `watch("a.b")`
2. Be using TypeScript (in strict mode), not plain JS
3. Use the value returned from `watch` without checking for null or undefined, which typechecks (compiles) happily

Example:

```ts
  type FormValues = {
    a?: {
      b: number;
    };
  };

  const { watch } = useForm<FormValues>();

  const bVal = watch("a.b"); // number
  const bValAsString = bVal.toString(); // Uncaught TypeError: bVal is undefined

  // Must use nullish traversal because a is possibly undefined
  const bVal2 = watch("a")?.b; // number | undefined
  const bVal2AsString = bVal2?.toString(); // no-op
```

### Expected behaviour

`const bVal = watch("a.b"); // number` should not "forget" that `a` could be undefined, so the returned type should be `number | undefined`, not `number`. In other words, it should behave like `a?.b`.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danielnixon** [comment]
Potentially a dupe of or related to:
* https://github.com/react-hook-form/react-hook-form/issues/10557
* https://github.com/react-hook-form/react-hook-form/issues/9919

**Comment by bluebill1049** [comment]
This is another issue replated to `deepPartial`, which we can't solve it until we remove that `deepPartial`, and make `defaultValues` none partial.
