### ISSUE TITLE
issue: Input field does not rerender when updating nested object

### ISSUE THREAD

**Issue by mkalafior** [react-hook-form/react-hook-form#10795]
### Version Number

7.45.4

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-sample-forked-vs2j58?file=/src/App.tsx

### Steps to reproduce

1. Go to the code sandbox
2. Click button with text "setValue set nested object" or "Controller + field.onChange"

### Expected behaviour

I expect inputs to be rendered with values set with `setValue` or Controller's `field.onChange` functions. Or Am I missing something? 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
- `onChange` is not !== `setValue`, onChange from controller belong to its own input name.
- when there is a root object input is registered and it's not possible to nested object

https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/createFormControl.ts#L643
