### ISSUE TITLE
Disabled flag for useController (<Controller />)

### ISSUE THREAD

**Issue by timsofteng** [react-hook-form/react-hook-form#10803]
Hello everyone. `register` method includes awesome `disabled` option which is exactly what I need in useController hook. How to achieve same behavior with useController or Conroller?

**Comment by bluebill1049** [comment]
we can consider including a disabled prop for the controller.

**Comment by timsofteng** [comment]
> we can consider including a disabled prop for the controller.

It would be great.

**Comment by timsofteng** [comment]
@bluebill1049 why did you close this issue?
Label says "closed as completed" but links doesn't follow the commit.
