### ISSUE TITLE
issue: `isDirty` is not updated after toggling `disabled` in `register()`

### ISSUE THREAD

**Issue by selimb** [react-hook-form/react-hook-form#10804]
### Version Number

7.45.4

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-disabled-dirty-m0d4xo

### Steps to reproduce

1. Check the "Disable (useForm)" checkbox. Notice the submit button becomes enabled, since the form is now dirty.
2. Uncheck the "Disable (useForm)" checkbox. The form is now theoretically clean, and yet RHF reports the form is dirty (submit button is still enabled).
3. In the "Name" input, append a dummy character and remove it, such that the input contains "initial". Now the form is clean.

### Expected behaviour

The form should not be dirty after step 2.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by selimb** [comment]
I also have a failing test that reproduces the bug: https://github.com/selimb/react-hook-form/blob/d2a5d9d9d95b2d9175d357e5d2ce7369cdaad879/src/__tests__/useForm/formState.test.tsx#L670

**Comment by PatrykKuniczak** [comment]
This bug still exists on the latest version, i using chrome on MacOS
