### ISSUE TITLE
Suppress validation for disabled input

### ISSUE THREAD

**Issue by maithuy** [react-hook-form/react-hook-form#1080]
Hi,

Is there a way to suppress the validation when the input field is disabled?

```
<input
    className="form-control"
    type="text"
    name={`action${j}`}
    id={param.name}
    onChange={e => setValue(e.target.name, e.target.value, true)}
    disabled={name !== selectedAction}
    ref={register({
         required: "This field is required",
         pattern: {
              value: new RegExp(param.regex),
              message: `${param.errorMessage}`
       })}
/>
```
Thank you.

**Comment by bluebill1049** [comment]
please consider leaving questions at our spectrum channel. Github issues are more for bugs and issue reports.

why not bring this logic {name !== selectedAction} into the validate as well.

**Comment by maithuy** [comment]
@bluebill1049 could you pin point on how to use the validate in the register?

**Comment by bluebill1049** [comment]
register({
  validate: value => value === 1
})

**Comment by maithuy** [comment]
@bluebill1049 Thanks so much for a quick response.

I've tried this and it works, it's kind of a manual fix, but it solves the problem I'm facing. I'll check out the api.

```
<input
      className="form-control"
      type="text"
      name={`trigger${j}`}
      id={param.name}
      onChange={e => setValue(e.target.name, e.target.value, true)}
      disabled={name !== selectedTrigger}
      ref={
          name !== selectedTrigger
          ? register
           : register({
                  required: "This field is required",
                  pattern: {
                        value: new RegExp(param.regex),
                         message: `${param.errorMessage}`
                   }
           })
      }
/>
```

**Comment by reintroducing** [comment]
@bluebill1049 I also ran into this just now and posed the question here with code samples: https://github.com/react-hook-form/react-hook-form/discussions/6823

What am I missing? Any help would be greatly appreciated.
