### ISSUE TITLE
Zod's .transform not affecting .getValues

### ISSUE THREAD

**Issue by andresespinosapc** [react-hook-form/react-hook-form#10802]
**Describe the bug**
When I use `.transform` in a Zod schema, the type of the output is the output of the transform, but the input is not actually transformed.

**To Reproduce**
1. Create a schema that uses a transform on a field
2. Compare the values of that field using the data got on `handleSubmit` with the one from `getValues()`

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-zod-resolver-example-forked-x9lqe1?file=/src/App.js

**Expected behavior**
The values should be the same. The values from `getValues()` should be transformed.

**Desktop (please complete the following information):**

- OS: macOS 13.3.1
- Browser Chrome
- Version 2.9.10

**Comment by jorisre** [comment]
@bluebill1049 When you have a moment to identify the issue 🤞🏻

**Comment by bluebill1049** [comment]
This is not possible, because getValues doesn't run the scheme which validate the entire form, while handleSubmit does and value is returned from the schema.

**Comment by juanvilladev** [comment]
If you want the transformed values, you could create a function that takes in the result of:
```
form.getValues()
```
Then use zod to parse the getValues() which will provide you the transformed output. 

If you want the types of the output version, you can use:
z.input and z.output instead of z.infer
