### ISSUE TITLE
issue: #4740 recommend to set a default value to undefined but https://react-hook-form.com/docs/useform#defaultValues says you should not

### ISSUE THREAD

**Issue by tibbe** [react-hook-form/react-hook-form#10801]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-dirty-y7x03?file=/src/App.tsx

### Steps to reproduce

See #4740 for actual code.

#4740 ends up recommending to set `undefined` in `defaultValues` to get `isDirty` to work correctly (in my case I call `resetField` on a field, which does end up with the form still reporting `isDirty` even though `dirtyFields` is empty) but https://react-hook-form.com/docs/useform#defaultValues recommends not setting `undefined` default values. Is there a way to square the two and have dirty checks work?

### Expected behaviour

If we have a field that can be `undefined` (e.g. the user can optionally select something from a list of items)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
That was 2021 post and we are at v7 at the moment. undefined is not supported, because we support both inline default value and defaultValues
