### ISSUE TITLE
4.9.8 break changes?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [react-hook-form/react-hook-form#1081]
**Describe the bug**
In 4.9.8, form default state will be override by Controller defaultValue, should we add this in the release note?

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-rhfinput-xqh38
2. Change react hook form version to 4.9.8
3. The input value become empty string

**Comment by bluebill1049** [comment]
I will patch this one. thanks for reporting.

**Comment by bluebill1049** [comment]
here is the fix: https://codesandbox.io/s/react-hook-form-rhfinput-08tik, please verify

**Comment by xiaoyu-tamu** [comment]
it works

**Comment by bluebill1049** [comment]
It looks like what we fixed was correct (after some testing). inline defaultValue will overwrite defaultValues. I will update the doc for such behavior, although I should probably have published as a minor update instead of a patch.

**Comment by xiaoyu-tamu** [comment]
That's what I thought. Probably it was a bug in my code. LOL. Your effort is appreciated

**Comment by bluebill1049** [comment]
@xiaoyu-tamu not your bug at all, it was a bug at our codebase.  🙏 I will update you when documentation is updated.

**Comment by bluebill1049** [comment]
<img width="907" alt="Screen Shot 2020-02-22 at 12 45 26 pm" src="https://user-images.githubusercontent.com/10513364/75084005-3d84cc00-5571-11ea-8aad-b9cea2155707.png">

let me know if this sounds ok?

**Comment by xiaoyu-tamu** [comment]
LGTM

**Comment by bluebill1049** [comment]
Deploying the update to website :)
