### ISSUE TITLE
Watch value of objects in an array

### ISSUE THREAD

**Issue by criscola** [react-hook-form/react-hook-form#10826]
**Is your feature request related to a problem? Please describe.**
My use case is the following: customer can have multiple addresses, but only one of them is the default one. User can insert as many addresses as necessary, each object has a switch control that is set to false (except the first one). When the use clicks the switch, the other switch set to true is then set to false. If the user removes the only address with switch set to true, the first address' switch is set to true if present.

I would like to not control the inputs or handle extra state.

**Describe the solution you'd like**
I would like to watch all elements of the array, or just some attributes in the array's objects.

**Describe alternatives you've considered**
I tried to use `watch()` to watch the field, but watch doesn't trigger when values are changed. I tried to use `useWatch`  which triggers both when the array is modified, and when any value in the address object is modified, but unfortunately it doesn't tell me what value triggered the change precisely. It would be great if I could configure `useWatch` to also tell me what exactly has changed (getting its `name` would be fine, since I can parse it to get the index of the array element), similarly to how the callback version of watch works. I also tried to combine `useWatch` and the callback version of watch to try to trigger the callback only when `useWatch`'s return triggers, to no avail (the callback always triggers).

**Additional context**
I apologize if there is a way to do this, I couldn't find it.

**Comment by Moshyfawn** [comment]
That said, notice how you have to update each field array item both on primary address change and address removal. Managing a "primary address" state can prove to be a better solution.
