### ISSUE TITLE
issue: useFieldArray name prop TypeScript error

### ISSUE THREAD

**Issue by danieldecsi** [react-hook-form/react-hook-form#10821]
### Version Number

7.37.0 (but it also exists in 7.43.9)

### Codesandbox/Expo snack

https://codesandbox.io/s/recursing-panna-pjfmxn

### Steps to reproduce

1. Create a form with `useForm` that has an array field
2. Use `useFieldArray` to manage that array field
3. The name prop of `useFieldArray` doesn't allow any value to be set, it reports this error instead: `Type 'string' is not assignable to type 'never'.ts(2322)`

### Expected behaviour

`useFieldArray`'s `name` prop should allow fields defined in `useForm`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danieldecsi** [comment]
I just realized if I use object as the array type instead of primitive values it works as intended. But it would be nice to have support for primitive values too.

**Comment by bluebill1049** [comment]
> I just realized if I use object as the array type instead of primitive values it works as intended. But it would be nice to have support for primitive values too.

it's a limitation with uncontrolled components.

**Comment by mhuggins** [comment]
I ran into this issue today too while getting started with react-hook-form, and discovering this issue is what helped me get past it.  It might be helpful to include this clarity in the docs. 😄
