### ISSUE TITLE
issue:  Object.keys(value).length == 0 is not triggering the required rule

### ISSUE THREAD

**Issue by simbahandiane** [react-hook-form/react-hook-form#10829]
### Version Number

7.26.1

### Codesandbox/Expo snack

No codesandbox available

### Expected behaviour

If the Object.keys(value).length == 0 and the required rule is true, it should trigger the required rule

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by simbahandiane** [comment]
Why is this marked as completed?

**Comment by Moshyfawn** [comment]
Because the issue neither has reproduction steps nor a reproducible codesandbox

**Comment by simbahandiane** [comment]
Here's the reproducible sandbox: https://codesandbox.io/s/controller-rules-forked-5wlpkm
