### ISSUE TITLE
issue: Invalid type for `watch` return value when used with async `defaultValues`

### ISSUE THREAD

**Issue by kamilkazmierczakMtab** [react-hook-form/react-hook-form#10837]
### Version Number

7.45.4

### Codesandbox/Expo snack

https://codesandbox.io/s/stupefied-pond-psqhvr?file=/src/App.tsx

### Steps to reproduce

1. Go to [Sandbox](https://codesandbox.io/s/stupefied-pond-psqhvr?file=/src/App.tsx)
2. See error

### Expected behaviour

TS correctly informs that `data` returned from `watch` can be of type `string[] | undefined` instead of `string[]`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Please provide a generic type at useform with async defaultValues.

**Comment by kamilkazmierczakMtab** [comment]
I'm not sure I fully understand that question (or is it answer?)
Type of data is correctly inferred by `useForm` to `FormValues` provided in a sandbox.
Problem is with `watch` return type that does not take into account that defaultValues are provided with delay (async) and will in most cases return undefined at first.
I don't think that passing some other type should be necessary since that could be inferred

**Comment by bluebill1049** [comment]
For async `defaultValues`, you will have to provide a generic type at `useForm`.

**Comment by kamilkazmierczakMtab** [comment]
Could you provide an example for my sandbox because for me it looks like that will remove all type inference that TS is giving me

**Comment by bluebill1049** [comment]
Couldn't infer with async default values.

**Comment by hornta** [comment]
I'm also hitting this issue. I had to change the typings for the inputs to be undefined: 

```ts
type Inputs = {
  name: string | undefined;
  description: string | undefined;
  period: { start: YearMonth; end: YearMonth } | undefined;
  basedOnPeriod: YearMonth | undefined;
};
```

**Comment by kamilkazmierczakMtab** [comment]
Changing types is not valid solution it is workaround due to invalid behavior of library and should not be used - types of data should not adjust to library
