### ISSUE TITLE
issue: First registered field doesn't get it's defaultValue back after unregister

### ISSUE THREAD

**Issue by teroko** [react-hook-form/react-hook-form#10830]
### Version Number

7.45.4

### Codesandbox/Expo snack

https://codesandbox.io/s/distracted-snyder-q78mxj

### Steps to reproduce

In sandbox just click toggle button twice to hide and show input fields. Second field recovers its defaultValue, first one doesnt.

### Expected behaviour

Both fields to show defaultValue after toggle

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Devanshi-Crypto** [comment]
I'd like to solve this, can you assign this to me please?

**Comment by Moshyfawn** [comment]
Most probably related to #10585.

[As mentioned in the linked issue](https://github.com/react-hook-form/react-hook-form/issues/10585#issuecomment-1605253277), the way to go about it would be to use the `unregister` form method at the app level _(as opposed to the component level)_. It's got to do with the React tree order of execution.

@Devanshi-Crypto you're free to look into it, but like I mentioned, chances are you'll need to deal with this limitation

**Comment by Devanshi-Crypto** [comment]
Oh cool

**Comment by lukasgebhard** [comment]
See here for more information on the issue: https://github.com/orgs/react-hook-form/discussions/10747
