### ISSUE TITLE
possibility to provide useFormContext the name for the path inside the main form

### ISSUE THREAD

**Issue by eladonline** [react-hook-form/react-hook-form#10834]
**Describe the solution you'd like**
I have form that holds 2 diff' forms but I need to use the same formContext, EX: 
`useForm({defaultValues:{a:{},b:{}}})`

now I want to use  the context in two files like this 

```
//file1.js
 const methods = useFormContext("a")
 
 //file2.js
 const methods = useFormContext("b")

```
as you see I specified the form key for each file to interact with

my solution for now is copying all methods but it doesnt looks good 

```
  const formMethods = useFormContext();

const createFormPath = name => {
    if (name) return `apiSecurity.${name}`;
    return "apiSecurity";
  };

  const getValues = name => formMethods.getValues(createFormPath(name));
  const unregister = name => formMethods.unregister(createFormPath(name));
  const register = name => formMethods.register(createFormPath(name));
  const setValue = name => formMethods.setValue(createFormPath(name));
  const resetField = name => formMethods.resetField(createFormPath(name));

  const { isValid } = formMethods.formState;

  const errors = formMethods.formState?.errors?.apiSecurity || {};

```

**Comment by Moshyfawn** [comment]
I don't think "combined forms" context is in the scope of RHF. You can create your own context(s) that take(s) multiple form instances under different names / multiple providers.

**Comment by eladonline** [comment]
I got you thanks for the suggestion (helps!)
But I still think it can help by changing seperted chunks in the form
like instead providing the whole path to the fields it can help you split the form handling

**Comment by bluebill1049** [comment]
Putting into pending feature request, chance of introduce into hook form is quite low.
