### ISSUE TITLE
issue: useWatch with name array and exact is behaving weird

### ISSUE THREAD

**Issue by kleinMaggus** [react-hook-form/react-hook-form#10836]
### Version Number

7.29.0 but can be reproduced with 7.45.4

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usewatch-exact-array-v7-29-0-j2pjx4?file=/src/index.js

### Steps to reproduce

Problem 1:
* Change "Str" value --> only useEffect with exact = false gets triggered

Problem 2:
* Change "Street" value --> useEffect with exact = false gets triggered because "street" startsWith "str"

### Expected behaviour

For Problem 1:
I expect that the useEffect where exact is true is also logging

For Problem 2:
None of the useEffects should trigger

We have a patched version for 7.29.0, where we updated the /src/logic/shouldSubscribeByName.ts method from:
```
import convertToArrayPayload from '../utils/convertToArrayPayload';

export default <T extends string | string[] | undefined>(
  name?: T,
  signalName?: string,
  exact?: boolean,
) =>
  exact && signalName
    ? name === signalName
    : !name ||
      !signalName ||
      name === signalName ||
      convertToArrayPayload(name).some(
        (currentName) =>
          currentName &&
          (currentName.startsWith(signalName) ||
            signalName.startsWith(currentName)),
      );
```
to:
```
import convertToArrayPayload from '../utils/convertToArrayPayload';

export default <T extends string | string[] | undefined>(
  name?: T,
  signalName?: string,
  exact?: boolean,
) =>
  !name ||
  !signalName ||
  name === signalName ||
  convertToArrayPayload(name).some(
    (currentName) =>
      currentName &&
      (exact
        ? currentName === signalName
        : currentName.startsWith(signalName) ||
          signalName.startsWith(currentName)),
  );
```
I want to clarify if this is an expected behaviour or not. We're always creating an array which is passed to useWatch and the name must exactly match. We don't want to create a patched version all the time, so maybe we can get this into the main release circle. If the solution above is wanted I can create a PR :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
related to this? https://github.com/react-hook-form/react-hook-form/pull/10707

**Comment by kleinMaggus** [comment]
Probably yes. Sorry, searched only for issues and not PRs.

**Comment by bluebill1049** [comment]
all good.
