### ISSUE TITLE
reset(formValues) can mutate the formValues argument

### ISSUE THREAD

**Issue by jgullstr** [react-hook-form/react-hook-form#10835]
### Version Number

7.45.4

### Codesandbox/Expo snack

https://codesandbox.io/s/boring-chatterjee-5rmspn?file=/src/Form.jsx

### Steps to reproduce

1. Open [sandbox](https://codesandbox.io/s/boring-chatterjee-5rmspn?file=/src/Form.jsx)
2. Watch as reset(defaultValues) in the effect mutates the constant defaultValues with values from emptyValues.

### Expected behaviour

Expected behaviour is that the form should be reset to use defaultValues. Instead, the defaultValues constant is overwritten with values from emptyValues.

The error only shows in StrictMode, but there is an execution path that under certain circumstances can mutate external data. The culprit here seems to be [createFormControl.ts row #1149](https://github.com/react-hook-form/react-hook-form/blob/5f3df1227c381a9127ab27f7d1d98a9cefee33d5/src/logic/createFormControl.ts#L1149C38-L1149C38), which assigns provided formValues object to an internal variable. Could cloned formValues be used here to make sure that nothing in the library can mutate the argument?

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
would you like to send a PR and provide some tests cases?

**Comment by jgullstr** [comment]
> would you like to send a PR and provide some tests cases?

[Done and done](https://github.com/react-hook-form/react-hook-form/pull/10847). I found a path that highlights the issue more clearly outside of StrictMode using reset() and resetField(). Check [this sandbox](https://codesandbox.io/s/dreamy-paper-259xzf?file=/src/Form.jsx). The added testcase is similar to the sandbox.

**Comment by bluebill1049** [comment]
Awesome 👍 thanks for the contribution. looking foward for more. 🙏
