### ISSUE TITLE
issue: clear null or undefined form fields

### ISSUE THREAD

**Issue by fabricioNavarrete95** [react-hook-form/react-hook-form#10831]
**Is your feature request related to a problem? Please describe.**
When using react hook form with the yup resolver the null, undefined values or empty strings are kept in the transformed and validated object of the form.

Example:
```json
{
  "email": "some@mail.com",
  "nickname": "",
  "password": "*****"
}
```

**Describe the solution you'd like**
You should be able to remove form object fields that are null values, empty strings or undefined values through a resolver option like `stripUnknow` but called something like `cleanObject` or something similar.

Example:

```js
const ... = useForm({ resolver: yupResolver(schema, { cleanObject: true }),
```

And that solves the problem of the first example, something like this:  (note that the `nickname` should not be present in the object)

```json
{
  "email": "some@mail.com",
  "password": "*****"
}
```

**Comment by fabricioNavarrete95** [comment]
**Note:** At the moment I have not found an existing solution, if this is already solved please leave me an example or a link to the documentation that solves this problem.

**Comment by bluebill1049** [comment]
> You should be able to remove form object fields that are null values, empty strings or undefined values through a resolver option like stripUnknow but called something like cleanObject or something similar.

native input would always preserve value as an empty string unless disabled, you can try with resolver with transform.

**Comment by eladonline** [comment]
I think it would be great to provide a method like `getCleandData` wich will return a clean form removing all nulls and undefineds
