### ISSUE TITLE
issue: When the input type is number, autofocus is making the form dirty though no input is changed. This is not happening when the input type is text.

### ISSUE THREAD

**Issue by AnushaChandanaMutyala** [react-hook-form/react-hook-form#10848]
### Version Number

6.0.8

### Codesandbox/Expo snack

https://codesandbox.io/s/cocky-hertz-2cj9jk?file=/src/App.js

### Steps to reproduce

1. Create an input field with type 'number'.
2. Turn on autofocus
3. Click anywhere on the form or screen.
4. Form is becoming dirty.

### Expected behaviour

Form shouldn't get dirty until the input field is changed.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
could you try out with v7?
