### ISSUE TITLE
issue: [resetField] has unexpected behavior when form is destroyed then recreated

### ISSUE THREAD

**Issue by crhistianramirez** [react-hook-form/react-hook-form#10842]
### Version Number

7.45.4

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-resetfield-bug-n6zgzk?file=/src/Form.js

### Steps to reproduce

1. Type a value into the field
2. Click "Hide form"
3. Try to delete all of the text from the field
4. Observe that on the final keystroke the value is reset to the value that was on the form before you clicked "Hide form" button

### Expected behaviour

I would expect the form to behave the way it does when it has not been destroyed/recreated given the fact that the form data/context has not been destroyed.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
missing defaultValues or it will fallback to the current form values

```
defaultValues: {
  firstName: ''
},
```
