### ISSUE TITLE
Using watch blocks form input

### ISSUE THREAD

**Issue by sidyes** [react-hook-form/react-hook-form#1084]
**Describe the bug**
I am using gatsby with typescript and react-hook-form.
It is working just fine but when I am using the `watch` functionality to conditionally render form elements it is not really working.

It seems that `watch`is somehow blocking the input and I cannot uncheck / untoggle (or whatever form element I use) anymore.

**To Reproduce**
Check out my sandbox link and click on "yes"

**Codesandbox link**
https://codesandbox.io/s/crazy-hopper-bxz0j?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
It should be possible to uncheck "yes" by clicking on "no".

**Screenshots**
see sandbox

I hope you can help me out here.

**Comment by amickael** [comment]
Can you please explain this? I'm having the same issue with input being blocked.
