### ISSUE TITLE
issue: useForm mode: "onTouched" triggers validation on onBlur also after initial onBlur validation

### ISSUE THREAD

**Issue by roeibit** [react-hook-form/react-hook-form#10856]
### Version Number

7.45.4

### Codesandbox/Expo snack

https://codesandbox.io/s/serene-pond-f7dsnj?file=/src/App.js

### Steps to reproduce

1. Fill some random value in available field.
2. Click outside the filed to trigger initial onBlur validation.
3. See that the Validation Counter is added by 1.
4. Focus the field again.
5. Click outside again and see that the Validation counter keeps on adding each onBlur click.

From the "onTouched" mode [docs ](https://react-hook-form.com/docs/useform#mode) - after the initial onBlur I expect validation only on "onChange" events, not also on "onBlur" without change.

### Expected behaviour

As in the [docs](https://react-hook-form.com/docs/useform#mode).

After inital "onBlur" validation is triggered only on "onChange".

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tmarkops** [comment]
Did you ever solve this issue? I currently have the same problem where my "onChangeText" logic is being executed when I unfocus (onBlur) from a field's TextInput.
