### ISSUE TITLE
[useFieldArray] React renders removed item

### ISSUE THREAD

**Issue by mikejav** [react-hook-form/react-hook-form#1085]
**Describe the bug**
When I use third party library that provides input component (e.g. @material-ui) if I have more than one field in dynamic array form, if I remove some "records" the renderer broke up (it seems like react try to render all "records" of the array form, but also the last removed one (see logs in console)).

**To Reproduce**
1. Go to life example: https://stackblitz.com/edit/react-dhbggp?file=index.js
2. click "+" three or more times
3. Remove penultimate item (by clicking trash icon)
4. Try to remove the last item (by clicking trash icon)
5. See error

**Codesandbox link**
https://stackblitz.com/edit/react-dhbggp?file=index.js

**Expected behavior**
The record that I removed should not be rendered.

**Screenshots**
![image](https://user-images.githubusercontent.com/25515470/75096434-d9c5c780-559f-11ea-9d64-e077d010e8fd.png)

**Desktop env:**
 - OS: Manjaro Linux
 - Browser: Firefox 73.0.1
 - Lib version: 4.9.8

**Additional context**
If you try to comment material's `TextField`s and uncomment raw HTML inputs or just comment TextField with `bar` name and uncomment its raw HTML substitute above it, the error is gone.

**Comment by xiaoyu-tamu** [comment]
use controller

```
      <Controller 
                control={control}
                name={`tests.[${index}].bar`}
                as={
                  <TextField
                  type={'text'}
                  label={'Bar'}
                  variant='outlined'
                  fullWidth
                />
              }/>

```

**Comment by bluebill1049** [comment]
For an external controlled component, please consider using Controller.

**Comment by mikejav** [comment]
This is what I overlooked in the documentation.
Thank you guys

**Comment by evgeniy-dainovich** [comment]
Just a short reminder for someone who find the same error.
I haven't added `Controller` as in this issue said, I use `Input` from `reactstrap` directly. But after reviewing a lot of issues I eventually checked that my attribute `name` was with extra dot in it.
```
name={`fields.[${index}].keyId`} // should be `fields[${index}].keyId`
```
Thanks to the authors for a great repo! :1st_place_medal: :rocket:

**Comment by bluebill1049** [comment]
my pleasure @evgeniy-dainovich we have an improvement coming this weekend for `useFieldArray` as well.

**Comment by bluebill1049** [comment]
you may want to install the dev tool as well: https://react-hook-form.com/dev-tools you can see what are the fields got registered next time.
