### ISSUE TITLE
Inconsistent re-render when initial state type are different

### ISSUE THREAD

**Issue by xiaoyu-tamu** [react-hook-form/react-hook-form#1086]
**Describe the bug**

When use watch in subcomponent,  looks like RHF re-render strategy are different.

* The first input ( number ) DONOT trigger re-render when input value same as original default state

* The second ( string ) and third ( boolean ) input trigger re-render when input value same as original default state

Which strategy is correct?

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/33362998/75099825-d1fc2800-558b-11ea-9f1a-b6d993bcb2a8.gif)

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-rhfinput-6ywbk
2. Enter and delete a character and notice the render count

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-rhfinput-6ywbk

**Comment by bluebill1049** [comment]
interesting... it's actually a bug, i souldn't re-render at all...
