### ISSUE TITLE
issue: setValue an empty array to a nested field doesn't trigger validation when shouldValidate is true

### ISSUE THREAD

**Issue by novakdan** [react-hook-form/react-hook-form#10862]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/dark-wave-y2zj85

### Steps to reproduce

I have a nested field and a custom component hooked to RHF via `useController`. The custom component has `string[]` as its value type. 

I need to set the value to `[]`. These are two ways that I tried.

a)
```tsx
setValue("item1.positions", [{ activities: [] }], {
   shouldValidate: true
});
```

b)
```tsx
setValue("item2.positions.0.activities", [], {
   shouldValidate: true
});
```
a) doesn't work well,
b) works as expected

There are two issues:
1. `useController` doesn't pick up on the state change because it has `exact` internally set to `true` by default without the option to set it. That is why the component doesn't even re-render upon the `setValue` call => I have found a solution to this - I'm using useWatch with `exact` set to `false`. 
2. `error` is not set. It is not just that `useController` doesn't cause the component to re-render (as I stated in my 1. point), the error isn't anywhere. I can even use `useFormState({ exact: false })` and it still doesn't show. 

I have been debugging the 2. issue for a long time and I may have found the reason in the `setValues` function.

```tsx
  const setValues = <
    T extends InternalFieldName,
    K extends SetFieldValue<TFieldValues>,
    U extends SetValueConfig,
  >(
    name: T,
    value: K,
    options: U,
  ) => {
    for (const fieldKey in value) {
      const fieldValue = value[fieldKey];
      const fieldName = `${name}.${fieldKey}`;
      const field = get(_fields, fieldName);

      (_names.array.has(name) ||
        !isPrimitive(fieldValue) ||
        (field && !field._f)) &&
      !isDateObject(fieldValue)
        ? setValues(fieldName, fieldValue, options)
        : setFieldValue(fieldName, fieldValue, options);
    }
  };
```

As it recursively goes through the field name, to parse through the name and use the correct value type, it encounters `[]` as the value and it never calls `setFieldValue`, because `[]` is not a primitive value. If the value to set was a primitive, this process wouldn't have been stopped in its tracks and it would have updated the value and `formState`. It doesn't register the error. I believe it would behave the same if I passed an empty object (to a different field of course) - as it isn't primitive either.

I have not found a solution for this issue. The only workaround was to call `trigger` immediately after setting the value. That works but I would like to avoid that.

### Expected behaviour

Empty array `[]` should be a valid value and it should correctly trigger validation when `shouldValidate` is set to `true`. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sungh0lim** [comment]
Hello, @bluebill1049. May i handle this issue? Please assign to me. I'll create PR.

**Comment by bluebill1049** [comment]
thank you @sungh0lim 🙏

**Comment by bluebill1049** [comment]
I don't think we will support this usage as this would further complicate the setValue logic, what i would recommend to use setValue within a loop instead and update your specific field value.
