### ISSUE TITLE
issue: Missing `disabled` functionality in `useForm`

### ISSUE THREAD

**Issue by mwskwong** [react-hook-form/react-hook-form#10877]
### Version Number

7.46.0

### Codesandbox/Expo snack

https://codesandbox.io/s/currying-rgb-2yvzyg?file=/src/App.tsx

### Steps to reproduce

Make use of `useForm` and add `disabled` prop as illustrated in https://github.com/react-hook-form/react-hook-form/releases/tag/v7.46.0-next.0

```ts
useForm({ disabled: true })
```

### Expected behaviour

The `disabled` prop is functional and has the corresponding TS type defined.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Not released yet. Would be mostly in the next one.

**Comment by mwskwong** [comment]
@bluebill1049 Just in case, the following is how the `disabled` prop is supposed to work in `7.46.0` right?

```tsx
const { control, formState: { isSubmitting } } = useForm();

<Controller
  name="name"
  control={control}
  disabled={isSubmitting}
  render={({ field: { disabled } }) => {
    console.log({ disabled, isSubmitting }); // disabled should = isSubmitting
    return <SomeComponent {...field}/>
  }}
/>;
``` 

Because the `console.log` suggests:  `{ disabled: undefined, isSubmitting: true }`. If that seems like a bug, I will create a separate issue for this.

**Comment by bluebill1049** [comment]
Seperate issue bug please, if you interested you can contribute to the issue as well, make the disabled prop optional. 

`disabeld?: boolean`
