### ISSUE TITLE
issue: yup resolver isValid returns false with no errors

### ISSUE THREAD

**Issue by kevincompton** [react-hook-form/react-hook-form#10872]
### Version Number

7.45.1

### Codesandbox/Expo snack

http://codesandboxlink.com

### Expected behaviour

This issue is widely documented with existing issues that have been closed for some reason, but this is a bug and a blocker for me.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
You could *at the very least* reference the closed you're referring to.

**Comment by Moshyfawn** [comment]
Please provide a reproduction
