### ISSUE TITLE
issue: While removing  a option from multiple options  in  useFieldArray  then the value of options below the removed one also sets to default value which is passed at the append time.

### ISSUE THREAD

**Issue by ajshrma** [react-hook-form/react-hook-form#10888]
### Version Number

7.42.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-fieldarray-bug-forked-924gmf?file=/src/FieldArray.js

### Expected behaviour

- Screenshot Of optionfields before removal of  any fieldOption
![image](https://github.com/react-hook-form/react-hook-form/assets/56355954/19c66e2f-8614-4444-b7aa-287114d4c84d)
- Screenshot of optionId and associated fieldOptionValue before removal
![image](https://github.com/react-hook-form/react-hook-form/assets/56355954/20531f34-12be-4eb7-9f2e-c8c1db42a028)

Incoming Result - AFTER REMOVAL OF ORDERID 1  HAVING VALUE 2 THE REMAINING ORDERID ARE (0,2,3) --VALUE--> (1,12,12)
Expected Result - AFTER REMOVAL OF ORDERID 1  HAVING VALUE 2 THE REMAINING ORDERID ARE (0,2,3) --VALUE--> (1,3,4) 

- Screenshot Of optionfields after removal of  fieldOption with orderId 1
  - Screenshot Of optionfields before removal of  any fieldOption
 ![image](https://github.com/react-hook-form/react-hook-form/assets/56355954/1f7f459a-106c-4316-9466-fb8630ff7b75)

  "Here the value of remaining options which are below orderId 1 are (12,12) because this is set as defaultvalue while apeend"
 ![image](https://github.com/react-hook-form/react-hook-form/assets/56355954/ec976d90-53b0-45b5-861e-251b56962888)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Can you please fix your codesandbox in order for us to be able to help you?
![rhf-csb-repro](https://github.com/react-hook-form/react-hook-form/assets/16290753/e8733482-cce1-4b0c-9ed0-9c8bd9af28a0)

**Comment by ajshrma** [comment]
Sure,Will find a better way to do that.
