### ISSUE TITLE
Locale support in validation

### ISSUE THREAD

**Issue by lubos-bistak** [react-hook-form/react-hook-form#10887]
Value "250,45" with validation rules "max: 250" is valid. As soon as i would change value to "250.45" validation will work properly and this value will be marked as invalid (there will be an error for this field).

I have checked documentation, but have not found any way, how to specify Locale or how to convert this "string" into a "number" for validation that min / max validation would work.

**Comment by bluebill1049** [comment]
thanks for the feature request, i think it's a bit out of scope at the moment. We will consider it if more similar request coming up.
