### ISSUE TITLE
issue: outdated CHANGELOG

### ISSUE THREAD

**Issue by danielrentz** [react-hook-form/react-hook-form#10880]
### Version Number

7.46

### Codesandbox/Expo snack

-

### Steps to reproduce

1. Go to [CHANGELOG.md](https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md)

### Expected behaviour

Info about v7.46

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
You can checkout [the `7.46.0` release notes](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.46.0) in the meantime
