### ISSUE TITLE
issue: useFieldsArray remove() then append() data remains from defaultValues

### ISSUE THREAD

**Issue by ericbaek** [react-hook-form/react-hook-form#10890]
### Version Number

7.46.1

### Codesandbox/Expo snack

https://codesandbox.io/s/calc-forked-g4dyh4?file=/src/App.tsx

### Steps to reproduce

1. Click on Delete for first field
2. Check that data is {} empty.
3. Click append
4. lastName value suddenly appears from default Values.

### Expected behaviour

I am not really certain that is a bug but maybe an expected behaviour.
Here is my perspective in that case. I think remove() should actually **remove** that value, and appending something **shouldn't be brining values back** that has previously been removed already.

And also, if that's expected and has no chance of being changed, is there a solution to avoid this problem without specifying entire value in defaultValues in append. For example, I just want to specify First name in append without last name.

I have been dealing this issue for a while; yet haven't found solution to it.
https://github.com/react-hook-form/react-hook-form/assets/43541203/bdf3764d-3ebd-4e9e-8f9d-c2baf944f134

### What browsers are you seeing the problem on?

Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
plz upgrade to v7.

**Comment by ericbaek** [comment]
> plz upgrade to v7.

ah... isn't 7.46.1 already v7?

**Comment by bluebill1049** [comment]
> > plz upgrade to v7.
> 
> ah... isn't 7.46.1 already v7? nvm, Just realised it was v6 in code sandbox. upgraded to v7, still same issue.

no, please check your csb again it's still incorrect syntax.

**Comment by ericbaek** [comment]
https://codesandbox.io/s/calc-forked-g4dyh4?file=/src/App.tsx

as you see here, if I don't specify certain part of the data while appending, previous data from default Values remain.
`<button type="button" onClick={() =>append({name: ""})}>`

if this isn't a bug, is there a different way to avoid this? 
![20230906 - calc (forked) - CodeSandbox (Arc)](https://github.com/react-hook-form/react-hook-form/assets/43541203/1e11884a-e2b2-460e-a82e-4da986314ef2)

**Comment by Moshyfawn** [comment]
[`useFieldArray` docs](https://react-hook-form.com/docs/usefieldarray)

> append data is required and **not partial**.

![rhf-append](https://github.com/react-hook-form/react-hook-form/assets/16290753/3b7d64db-3570-42b3-90bc-daccac23acb7)

**Comment by Moshyfawn** [comment]
To avoid it, you can specify empty field data like `"" <empty string>`, `null` etc

**Comment by dalmolinz** [comment]
> append data is required and not partial.

Hmmm, this sounds like a cop-out. What if all of my data is optional? I think whatever is passed to `append` should always be respected, and never merged with `defaultValues`.

A workaround I found was to use `resetField` just before `remove`. In the provided sandbox, that would be:

```typescript
onClick={() => {
  resetField(`cart.${index}`, { defaultValue: {} as any });
  remove(index);
}}
```

Note that resetting `defaultValues` you lose the ability to `reset` to the actual initial values, so it's not a perfect workaround.
