### ISSUE TITLE
issue: formState.dirtyFields does not update when using remove() from useFieldArray()

### ISSUE THREAD

**Issue by julullc** [react-hook-form/react-hook-form#10892]
### Version Number

7.46.1

### Codesandbox/Expo snack

https://codesandbox.io/s/interesting-swirles-x3dcwl?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/interesting-swirles-x3dcwl?file=/src/App.tsx
2. Click on "Remove Bob"
3. Click on "SUBMIT"
4. Check the console
5. The `formState.dirtyFields` is `{}`

### Expected behaviour

The `formState.dirtyFields` should be 
```
{
    "people": [
        { name: "Alice", age: 30 }
   ]
}
```
Because the list of people had changed and no longer matches `defaultValues`.

The idea is to put a gate in the `handleSubmit` only to send data to the backend to save if the form state is dirty.

Something along these lines: 
```
const onSubmit = (data: FormValues) => {
    if (formState.dirtyFields?.people) {
        savePeople(data.people);
    }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
You need to subscribe to the `dirtyFields` form state before it becomes reactive.

Please, check out [the `formState` docs](https://react-hook-form.com/docs/useform/formstate#rules) to learn more about this performance optimization.

**Comment by Moshyfawn** [comment]
You need to subscribe to the `dirtyFields` form state before it becomes reactive.

Please, check out [the `formState` docs](https://react-hook-form.com/docs/useform/formstate#rules) to learn more about this performance optimization.

```diff
- const { formState } = useForm()
+ const { formState: { dirtyFields } } = useForm()
```

or

```diff
- const { formState } = useForm()
+ const { formState } = formState
```

**Comment by julullc** [comment]
I am not quite sure how to do it when I use FormProvider.

Here is a bit more complete example:
```
  const form = useForm<GlobalSettingsData>({
    defaultValues: async () => fetchDefaultValues(setError, fontSettings),
  });

  return (
    <FormProvider {...form}>
      <form onSubmit={form.handleSubmit(async (data) => {
              if (form.formState.dirtyFields?.people) {
                  savePeople(data.people);
             }
      })}>
        {!error && (
          <GeneralSettingsForm />
        )}
      </form>
    </FormProvider>
  );
};
```

The `useFieldArray` is used deep inside `GeneralSettingsForm` component children.

Would I need to do it like so?
```
 const form = useForm<GlobalSettingsData>({
    defaultValues: async () => fetchDefaultValues(setError, fontSettings),
  });


 const { dirtyFields } = form.formState;
```

**Comment by julullc** [comment]
Doing it like so actualy worked:
```
const form = useForm<GlobalSettingsData>({
    defaultValues: async () => fetchDefaultValues(setError, fontSettings),
  });


 const { dirtyFields } = form.formState;
```

Did not help in what I was trying to accomplish in my extended example, though. But the original issue as reported is closed for sure.

Thanks!
