### ISSUE TITLE
Add a way to skip Contorller#commonTask getInputValue() call

### ISSUE THREAD

**Issue by xiaoyu-tamu** [react-hook-form/react-hook-form#1090]
**Is your feature request related to a problem? Please describe.**

When use Controller with custom input, If the value object is {id:1, value:"ABC"}, controller will set next value to "ABC" because getInputValue will try to get obj.value first. Should it be {id:1, value:"ABC"}? 

https://github.com/react-hook-form/react-hook-form/blob/master/src/controller.tsx#L59
and 
https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/getInputValue.ts#L13

**Describe the solution you'd like**

Maybe we should only call `getInputValue` if `value` is an `SyntheticEvent` object? Can we rely on constructor check?
```tsx
if (e.constructor.name === "SyntheticEvent" && e.type === "change") {
  console.log("input change event");
}
```

**Describe alternatives you've considered**

Or can we add an option to skip it?

**Comment by bluebill1049** [comment]
I think we can improve it by check if it's a input event (not just `SyntheticEvent`). You interested to send over a PR? Also I think it's better leave logic inside `getInputValue`.

**Comment by xiaoyu-tamu** [comment]
Sure, I'll give it a try

**Comment by bluebill1049** [comment]
awesome work on this: https://github.com/xiaoyu-tamu/material-ui-hook-form I left you a ⭐️ :)

**Comment by bluebill1049** [comment]
i need to include packages like this into the website...

**Comment by xiaoyu-tamu** [comment]
Thanks, It's still a WIP

**Comment by bluebill1049** [comment]
hey @xiaoyu-tamu 

> value object is {id:1, value:"ABC"},

you mean `{ target: {id:1, value:"ABC"} } ` isn't it correct to return `value`?

**Comment by bluebill1049** [comment]
i can see the pain for user with issue #1154

**Comment by bluebill1049** [comment]
This e.target.type check can be annoying. i am just wondering what's your use case to have `{ target: {id:1, value:"ABC"} }` shouldn't you just return `{id:1, value:"ABC"}`

**Comment by bluebill1049** [comment]
wait nvm i think my fix have a bug!

**Comment by s97712** [comment]
@bluebill1049 @xiaoyu-tamu 
Consider the following usage?

```ts
<TextField label="kind" name="kind"
    select
    inputRef={register({ required: true, handle: (raw)=> raw.value })}
/>
```

**Comment by bluebill1049** [comment]
@s97712 thanks :) you can pretty much do that in Controller

`<Controller name="test" onChange={e => parseInt(e.target.value, 10)} />`

**Comment by s97712** [comment]
> @s97712 thanks :) you can pretty much do that in Controller
> 
> `<Controller name="test" onChange={e => parseInt(e.target.value, 10)} />`

thanks :) The `Controller` is not very convenient, I hope there is a simpler and more convenient way
