### ISSUE TITLE
issue: Setting 'disabled' to false in input components crashes the app 

### ISSUE THREAD

**Issue by marit970** [react-hook-form/react-hook-form#10907]
### Version Number

7.46.1

### Codesandbox/Expo snack

https://github.com/marit970/react-disabled-bug

### Steps to reproduce

1. Check out the repo 
2. Set the disabled property of the TextInput to false

### Expected behaviour

After an update (to v.7.46.1) there is an issue with the 'disabled' property. The app crashes when setting the disabled property in react-admin input components to 'false'. (It works correctly when setting it to 'true' or 'undefined'). This issue appears in v.7.46.0 and v7.46.1 as well. (Also I am using the latest react-admin version 4.13.3).
![Bildschirmfoto von 2023-09-08 11-16-55](https://github.com/react-hook-form/react-hook-form/assets/43189340/0543b22a-98dc-4fac-8888-271b2efe30e9)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Interesting to note that what I assume is the field `name` path in `react-admin` contains an `undefined`

![rhf-ra-path](https://github.com/react-hook-form/react-hook-form/assets/16290753/b4828135-63b6-4f31-a831-0a3a339d5614)

**Comment by Moshyfawn** [comment]
I've not used `react-admin` in some time, so I don't remember all the intricacies of the API and how you're supposed to define your resources and their names.

I was able to reproduce the issue with a much lower RHF version; there's a chance your implementation's missing a resource name that's lead to an `undefined` in the field `name` path.

Consider checking out the `react-admin` docs to see of there's a resource definition missing.

**Comment by marit970** [comment]
@Moshyfawn Thank you, I will check it out

**Comment by tgundogdu** [comment]
I'm getting this error too. This error occured from RHF version 7.46.1. 

I debug the code and I got the error inside createFormControl.ts

This error occured in strict mode.

![image](https://github.com/marmelab/react-admin/assets/31204844/fdbe5d49-4aed-4b67-9269-10cf27a28d45)

inside createFormControl.ts
![image](https://github.com/marmelab/react-admin/assets/31204844/48d4668e-75ed-4094-9bab-68111f46ac69)

I hope this helpful

**Comment by marit970** [comment]
@Moshyfawn I noticed that removing strict mode solves the issue. It seems like the getter function itself is undefined on the second render. I guess resources.undefined is not a problem here because it works on the initial render.

**Comment by mysuf** [comment]
I think this is related to what I faced in #10908 when `defaultValue` is undefined. All clues lead to one specific commit.

**Comment by qpointsystems** [comment]
FWIW, removing strict mode did not resolve for me. Currently 'hard-coding' what used to be a more dynamic 'disabled' functionality in my components based on state in the parent until resolved. Clearly using syntax like **disabled={isDisabled**} was, for. me at least, the syntax that triggers issue.

**Comment by fzaninotto** [comment]
Hi, I see that this issue was labeled with "question", but to me it is clearly a bug (and a regression). Many users are experiencing this issue, so please consider it as worthy of a rapid fix.

**Comment by tcschiller** [comment]
Just chiming in to say, I've encountered this same problem with a rather complex form field. This release caused our unit tests to hang, and we can't move forward until it's patched. Thanks everyone for reporting this!

**Comment by Defrosted** [comment]
Seeing this as well. Setting the disabled attribute to `undefined` instead of `false` works when the field is not to be disabled. E.g. `disabled={someBoolean ? true : undefined}` is a working way of setting it.

**Comment by cyonder** [comment]
Came here to open a new issue for it but looks like it's already discovered.
