### ISSUE TITLE
issue: Appending with useFieldArray sets unrelated (!) fields to dirty.

### ISSUE THREAD

**Issue by Mario-Eis** [react-hook-form/react-hook-form#10904]
### Version Number

7.46.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-submit-only-dirty-fields-forked-tw4ftz

### Steps to reproduce

Check https://codesandbox.io/s/react-hook-form-submit-only-dirty-fields-forked-tw4ftz
Clicking to append an item to the bikes array, sets cars dirty.
I think this my be related to the whole story from https://github.com/react-hook-form/react-hook-form/issues/9599
But it does not only affect dirtyFields, it also sets isDirty on unrelated controller fields to true. Thats just wrong. 
And very unfortunate for our codebase. For now I am pretty stuck on handling this issue.

UPDATE: This seems not to be a problem with append, but with useFieldArray as a whole. Even when using setValues to update the array in the form, all fields get dirty as soon as useFieldArray is used on the modified array. When removing useFieldArray from the code, the behaviour seems to be kind of "normal". But then nothings gets dirty at all. Not even the modified array field.

### Expected behaviour

Cars should not have a dirty state, because of bikes.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mario-Eis** [comment]
I also tried to handle all array updates (append) with useController. While this seemed to work properly on the first impression, it turned out to have issues. With this method, as soon as a field is really dirty (touched by the user), updating the whole array with a new one (with an added entry), causes to reset all the dirty states inside the field array.

**Comment by bluebill1049** [comment]
This is expected behaviour, we are checking against defaultValues with each fields to mark dirty field true/false

**Comment by Mario-Eis** [comment]
But the defaultValues of Cars are untouched.

**Comment by Mario-Eis** [comment]
I updated the sandbox. It even stays dirty, when the appended value is removed again. That cant be correct.

**Comment by thomas-cruz** [comment]
Would love to hear an answer for this issue
