### ISSUE TITLE
issue: register onChange function handler is cached with same name.

### ISSUE THREAD

**Issue by kitloong** [react-hook-form/react-hook-form#10925]
### Version Number

7.46.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-adapting-existing-form-forked-r5jhq2?file=/src/index.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/react-hook-form-adapting-existing-form-forked-r5jhq2?file=/src/index.js
2. Open Console log
4. On "Expected" checkboxes, check the "Movie" checkbox
5. Check Console log, see `{id: 1, name: "Movie"}`
6. On "Actual" checkboxes, check the "Movie" checkbox
7. Check Console log, see `{id: 3, name: "Read"}`

### Expected behaviour

Should always print `{id: 1, name: "Movie"}`. 

register the same name on different inputs is a common case for checkbox and radio buttons.
I am not quite sure if this is a bug or a feature.
If it is a feature, please help us with the proper way for this scenario

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is expected behaviour register does cache register input name.

**Comment by kitloong** [comment]
Thank you @bluebill1049 , I will close this issue.

Meanwhile, I am leaving this for future reference to  describe the different behavior of react-hook-form `onChange`

```js
const hobbies = [
  { id: 1, name: "Movie"},
  { d: 2, name: "Travel"},
  { id: 3, name: "Read"},
];

// Without react-hook-form
{hobbies.map((hobby) => (
	<div key={hobby.id}>
		<span>{hobby.name}</span>
		<input
			type="checkbox"
			onChange={(e) => {
				console.log(hobby); // Output selected hobby
			}}
		/>
	</div>
))}

// With react-hook-form
{hobbies.map((hobby) => (
	<div key={hobby.id}>
		<span>{hobby.name}</span>
		<input
			type="checkbox"
			{...register("hobbies", {
				// Register with same name
				onChange: (e) => {
					console.log(hobby); // Cached, always {id: 3, name: "Read"} 
				}
			})}
		/>
	</div>
))}
```
