### ISSUE TITLE
useFieldArray Unexpected behaviour

### ISSUE THREAD

**Issue by zeljkoX** [react-hook-form/react-hook-form#1093]
Use case:

Depending on a previously selected form field(for example radio button) display additional fields.

For example:
When "isOrganization" is selected display input field for the organization name and when it is not selected display input fields for first name and last name.

I tried to implement this use case without useFieldArray but as the length of fields is not equal I was getting weird results from getValues. This is probably caused because of rules of hooks, they should be called in the same order.

After that, I tried to implement this with useFieldArray but it seems like remove is asynchronous and using append after it will add previous values from a remove.

What is the preferred way to implement this use case with react-hook-form?

An example is attached. Described behavior can be reproduced by clicking toggle button.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-4m4iz?fontsize=14&hidenavigation=1&theme=dark

**Comment by bluebill1049** [comment]
what about this approach: https://codesandbox.io/s/react-hook-form-usefieldarray-913gm

**Comment by zeljkoX** [comment]
Thank you for the quick response.

I have adopted my example to include your approach and it is working.


https://codesandbox.io/s/react-hook-form-usefieldarray-4m4iz?fontsize=14&hidenavigation=1&theme=dark
