### ISSUE TITLE
issue: diryFields type is different than expected output

### ISSUE THREAD

**Issue by Szorcu** [react-hook-form/react-hook-form#10934]
### Version Number

7.45.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-forms-wrong-dirtyfields-type-wsq2t5

### Steps to reproduce

1. Go to sandbox
2. Select different skill than skills field default value e.g. TS
3. Submit form - notice that dirty fields are printed with pattern `{[key: sting]: boolean}`
4. Hover over dirtyFields value - notice that declared type is `Partial<Readonly<{[x: string]: boolean | boolean[];}>>`

### Expected behaviour

I think it's because of deep partial, but if field has declared type like `number[]` or `string[]` then `dirtyFields` type should not change to `{[key: sting]: boolean | boolean[]}` and it should still be`{[key: sting]: boolean}`. Or maybe I am wrong and `dirtyFields` can have a `boolean[]` in this scenario?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
It's a current design limitation.
