### ISSUE TITLE
issue: append from useFieldArray dirties other fields

### ISSUE THREAD

**Issue by BunColak** [react-hook-form/react-hook-form#10931]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/bold-chatterjee-zq5kql?file=/src/App.tsx

### Steps to reproduce

Hi! Just encountered this behaviour. Not sure if this is intended, but I felt something was off.

1. Go to sandbox
2. Click on append
3. Dirty field should just include the array fields (name: demo2), but it includes the unrelated 'demo' field.

Thank you all for the effords! 

### Expected behaviour

I would expect dirtyFields to include only the demo2 field. 'demo' field has no relation with the 'demo2' field.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is expected behaviour/work as designed, dirty fields is updated via deep equal with defaultValues.

**Comment by BunColak** [comment]
But this happens even if you never touch the first input. `demo` input is a regular text input, and `demo2` is an array input. If you add a new item to demo2 it makes demo dirty as well. Even if it is not touched at all.

**Comment by thomas-cruz** [comment]
Not sure why dirtyFields for _existing_ fields get updated when **append** is called. Please explain @bluebill1049

**Comment by bluebill1049** [comment]
Because dirty fields are deep equaled again `defaultVlaues` has no relationship with `touched`

**Comment by rvisio** [comment]
Bump
