### ISSUE TITLE
issue: breaking change with controller disabled feature

### ISSUE THREAD

**Issue by davbrito** [react-hook-form/react-hook-form#10932]
### Version Number

7.46.1

### Codesandbox/Expo snack

https://codesandbox.io/s/nervous-leakey-vdz6hp

### Steps to reproduce

1. Add a controlled input with Controller
2. On the render of the Controller pass the "field" object as a spread
3. Add a "disabled" prop on the input before the field spread
4. See how disabled is passed as undefined to the component
5. See on the console how the field object has a "disabled" property with the value `undefined`
![image](https://github.com/react-hook-form/react-hook-form/assets/39559632/786b128f-9598-4652-b3db-929f1b5b855d)

### Expected behaviour

For backwards compatibility on the same major version, the field object should not have the disabled property when it is undefined. This way the code that passes a disabled prop directly to the controlled component won´t be affected by this change.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
What's breaking here? The prop itself is `undefined`. We are going to revert this change, the least we can do is update the change log.
