### ISSUE TITLE
issue: deepEqual does not work correctly with Set

### ISSUE THREAD

**Issue by cschwebk** [react-hook-form/react-hook-form#10946]
### Version Number

7.45.4

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/stupefied-shamir-ntrvhf?file=/src/__tests__/utils/deepEqual.test.ts:11,12

### Steps to reproduce

In the attached codesandbox, I have added a unit test for `deepEqual.ts` that compares two obviously different `Set` objects. Because `deepEqual` does not properly work with `Set` objects, the test now fails.

1. Open the codesandbox.
2. Run `pnpm test src/__tests__/utils/deepEqual.test.ts`, observe the failure.

### Expected behaviour

The newly added test case should pass, because the two provided `Set` objects are different.

### What browsers are you seeing the problem on?

Chrome. Will be the same in all browsers.

### Relevant log output

```shell
> react-hook-form@7.46.1 test /project/home/cschwebk/workspace
> jest --config ./scripts/jest/jest.config.js "src/__tests__/utils/deepEqual.test.ts"

 FAIL   Web  src/__tests__/utils/deepEqual.test.ts
  deepEqual
    ✕ should return false when two sets not match (5 ms)
    ✓ should return false when either type is primitive (1 ms)
    ✓ should return true when two sets matches (2 ms)
    ✓ should compare date time object valueOf (1 ms)

  ● deepEqual › should return false when two sets not match

    expect(received).toBeFalsy()

    Received: true

       7 |     ).toBeFalsy();
       8 |
    >  9 |     expect(deepEqual(new Set(['foo', 'bar']), new Set(['foo']))).toBeFalsy();
         |                                                                  ^
      10 |
      11 |     expect(
      12 |       deepEqual(

      at toBeFalsy (src/__tests__/utils/deepEqual.test.ts:9:66)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 3 passed, 4 total
Snapshots:   0 total
Time:        1.54 s
Ran all test suites matching /src\/__tests__\/utils\/deepEqual.test.ts/i.
 ELIFECYCLE  Test failed. See above for more details.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cschwebk** [comment]
The genesis of this issue is that we have a muilti-select combobox field in one of our forms that stores the value in a `Set`. Functionally things are ok, but the form's `isDirty` state does not get updated when the field's value changes because of the above issue with `deepEqual`. 

I looked into the code a bit, it seems like the `Set` is being treated the same way as a POJO because `typeof val === 'object'` is truthy for a `Set` in the `isObject.ts` file, but `Object.keys(val)` with a `Set` returns an `[]`.

**Comment by cschwebk** [comment]
Thanks for taking a look at this issue @bluebill1049, but I’m not sure what you mean by saying this is working as designed.

**Comment by bluebill1049** [comment]
it means we never designed it to support `Set`, `'Map`, `WeakMap`, custom object and ect.

**Comment by cschwebk** [comment]
Thanks for the confirmation. Is that limitation somewhere in the documentation? I've looked through it many times and don't recall seeing anything about limits on the supported types for the `value` of a field. Is there any interest in adding `Set` as a supported type for a field `value`?

**Comment by bluebill1049** [comment]
>  I've looked through it many times and don't recall seeing anything about limits on the supported types for the value of a field.

would you like to contribute or have any suggestion which section is suitable to include the limitation?

**Comment by bluebill1049** [comment]
We will consider supporting `Set` in the future update.
