### ISSUE TITLE
issue: validation error after reset form

### ISSUE THREAD

**Issue by ko22009** [react-hook-form/react-hook-form#10944]
### Version Number

7.45.4

### Codesandbox/Expo snack

https://codesandbox.io/s/wonderful-wescoff-j5nvv7?file=/src/App.js

### Steps to reproduce

1. input something
2. remove typed text
3. input something
4. submit
5. repeat 1 - 2 and see error validation on the second step.

### Expected behaviour

After resetting form, validation rules doesn't apply automatically bcz validation should be after press button.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ko22009** [comment]
I solved this issue:
`useEffect(() => {
    if (isSubmitSuccessful) reset();
  }, [isSubmitSuccessful, reset]);`

**Comment by Moshyfawn** [comment]
The default [`reValidateMode`](https://react-hook-form.com/docs/useform#reValidateMode) is set to `onChange`. You can set it to `onSubmit` to achieve your desired behavior.

**Comment by Moshyfawn** [comment]
The default [`reValidateMode`](https://react-hook-form.com/docs/useform#reValidateMode) is set to `onChange`. You can set it to `onSubmit` to achieve your desired behavior.
