### ISSUE TITLE
issue: watch called twice when setting value by setValue when using controlled input

### ISSUE THREAD

**Issue by jgradzki** [react-hook-form/react-hook-form#10959]
### Version Number

7.46.1

### Codesandbox/Expo snack

https://codesandbox.io/s/busy-cache-xqnnm5?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/busy-cache-xqnnm5?file=/src/App.tsx
2. Show editor console
3. Type one letter in input
4. See there is only one log in console (from watch())
5. Click Set Value button
6. See that there are not one but two new logs in console

### Expected behaviour

watch() callback should be fired only once when changing value by setValue (only one console.log per change in example)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jgradzki** [comment]
hmm, interesting, i also forked set value example and it seems that there this problem does not occur 
[https://codesandbox.io/s/react-hook-form-set-input-select-value-forked-4ry5sp?file=/src/index.js](https://codesandbox.io/s/react-hook-form-set-input-select-value-forked-4ry5sp?file=/src/index.js)

not sure whats the difference

**Comment by jgradzki** [comment]
ok, my bad. i have used button and forgot to set type="button" so the form was also submitting. 
I still have same problem in my application code and there is no button but I guess there must be something wrong on my end.
I'm closing this issue for now

**Comment by jgradzki** [comment]
ok, i found out that problem is when using controlled input, i have updated sandbox code.

I also found out that the problem is that when using controlled input additional next() function is executed in setFieldValue function:
![image](https://github.com/react-hook-form/react-hook-form/assets/888709/372cea88-41c3-4b6c-aad1-0a90f074998c)

**Comment by jgradzki** [comment]
@bluebill1049 Hi, I'm not sure why this isn't marked as bug, but could you maybe point some directions/thoughts so that maybe I could try to provide some solution(pr)?

only thanks to tests I know this `if` is for array/nested fields, but as person who doesn't know how this all works under the hood, it might take some time. Maybe I will be able to spare some time in near future to solve this problem(or at least try).

**Comment by bluebill1049** [comment]
watch callback never was designed to call exactly once, i don't think we will look into this for now. If this is an issue mabey consider to track your data at consumer level eg `onChange`
