### ISSUE TITLE
issue: watch and setValue methods don't return or set undefined values

### ISSUE THREAD

**Issue by nick-korolev** [react-hook-form/react-hook-form#10950]
### Version Number

7.27.1

### Codesandbox/Expo snack

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMBi0RwL5wBmUEuARFOgIYDGMAtABYQQDW9hOZA3AFC-AAdjHRRCtdHACS2KLgS84RYFFQwAclRDoAXHDVQhAcz55+6AB6RYcACbpxyADbxCyQXWARBcAIJgwAAoASkRFOBpvNUQ4RipBWyd0AGVkACMQYBgAGjgAdyoYGkZcjBgANSonZEkCAF4UDFkQAB4ZHAA+QIUlJXtHF0rq9FQ9Ht6lQhU1TW09d36hdFts8KU8VfXgvnDIwWip1Q0tSQaCosZAgHJDmZOr7f4lPejvAGEnYBpWOAaQ346YQmZSGNWut2O2iuuQWDiWtke6yeESi8DiCSSv1i8USKXSmRggUCtkKVFCdUB42eUQgSQAdE4IEZiaTEfhHuFKDBkFAfKZeEA

### Steps to reproduce

1. Go to '[link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMBi0RwL5wBmUEuARFOgIYDGMAtABYQQDW9hOZA3AFC-AAdjHRRCtdHACS2KLgS84RYFFQwAclRDoAXHDVQhAcz55+6AB6RYcACbpxyADbxCyQXWARBcAIJgwAAoASkRFOBpvNUQ4RipBWyd0AGVkACMQYBgAGjgAdyoYGkZcjBgANSonZEkCAF4UDFkQAB4ZHAA+QIUlJXtHF0rq9FQ9Ht6lQhU1TW09d36hdFts8KU8VfXgvnDIwWip1Q0tSQaCosZAgHJDmZOr7f4lPejvAGEnYBpWOAaQ346YQmZSGNWut2O2iuuQWDiWtke6yeESi8DiCSSv1i8USKXSmRggUCtkKVFCdUB42eUQgSQAdE4IEZiaTEfhHuFKDBkFAfKZeEA)'
2. Check type of 'firstName'
3. Check that you cannot pass undefined to setValue

### Expected behaviour

When using react-hook-form, I have encountered types inconsistency in watch and setValue methods when handling undefined values. Specifically, watch returns a string type only and does not return undefined. The same with setValue method (I can't pass undefined value). I assumed that all the form fields in the react-hook-form api were optional until the handleSubmit method was called.

If I make the interface fields optional, then handleSubmit will handle an incorrect type and I will have to use typeguards or assert in order to bring everything to the desired type

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Don't support undefined value.

**Comment by nikolay-emrikh-stenn** [comment]
@bluebill1049 
Since form interface (`IForm` in the example) represents the data in final, valid state and the defaultValues accept partial data — it's clear that before the form is submitted and validating form, `Partial<IForm> represents state of the form

Why does`watch` return the exact type (`string` in the example) if, for example, on the first render, `watch` will return `undefined` 100% of the time. It's incorrect type and can lead to huge bugs. Because of this, we have to trick the TS with `watch('field') as string | undefined`. Try to console.log and see in runtime yourself

**Comment by bluebill1049** [comment]
Undefined value is always been a limitation for controlled computer, to support is we will have to remove inline default value all together, if you have strong opinion or desire to make it work you can consider to contribute or even fork the repo and publish your own package. At the moment, you can consider this as design limitation.
