### ISSUE TITLE
Conditional validation does not work

### ISSUE THREAD

**Issue by alxvallejo** [react-hook-form/react-hook-form#10957]
### Version Number

7.46.1

### Codesandbox/Expo snack

https://codesandbox.io/s/rhf-conditional-validation-xdf9f4

### Steps to reproduce

Basically I need a phone number OR an email address.

I'm passing the required rule as a boolean dependent on a `watch` value of either the phone or the email field.

In writing out an email, the phone's required property is set to false. However, on submit, the error is re-populated to show that the phone is required.

### Expected behaviour

The expected behavior is that the form can submit and the errors object remains empty.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
you can write a validate function for this.

**Comment by alxvallejo** [comment]
Why should I have to? Shouldn't the required rule respect the boolean switch?

**Comment by bluebill1049** [comment]
because validation rules are cached except `validate` callback.

**Comment by alxvallejo** [comment]
Mmk. Good to know. Seems silly, but I won't ask.
