### ISSUE TITLE
issue: Appended field takes on the values of previously deleted field if initial value is set to undefined

### ISSUE THREAD

**Issue by jakehowlett93** [react-hook-form/react-hook-form#10979]
### Version Number

7.43.0

### Codesandbox/Expo snack

https://codesandbox.io/s/admiring-thunder-h32prn?file=/src/App.js

### Steps to reproduce

1. Delete the second field
2. Click add field

### Expected behaviour

I would expect add field to add a blank row with an empty name and surname.

Instead it adds a field with the name Bob which comes from the previously deleted field.

I believe this is to do with the default name field in blankRow being undefined, the surname field which defaults to an empty string behaves as expected

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://react-hook-form.com/docs/usefieldarray

<img width="965" alt="Screenshot 2023-09-28 at 10 10 18 pm" src="https://github.com/react-hook-form/react-hook-form/assets/10513364/8270a7ba-7460-41dd-a9b4-e05b5537e696">

> Important: append data is required and not partial.
