### ISSUE TITLE
issue: Error `can't access property "mount", r._f is undefined` is thrown when `remove` is called in a field array with controlled inputs

### ISSUE THREAD

**Issue by Valdas3** [react-hook-form/react-hook-form#10970]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-zls2hq?file=/src/index.js

### Steps to reproduce

1. Go to the sandbox.
2. Click on click on delete in the first row
3. See error: TypeError: can't access property "mount", r._f is undefined

### Expected behaviour

Should remove the first row without errors.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
18:23:36.393 React Router caught the following error during render TypeError: can't access property "mount", field._f is undefined
    updateMounted useController.ts:81
    useController useController.ts:97
    React 14
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    js scheduler.development.js:571
    js scheduler.development.js:633
    __require chunk-AC2VUBZ6.js:11
    js index.js:6
    __require chunk-AC2VUBZ6.js:11
    React 2
    __require chunk-AC2VUBZ6.js:11
    js React
    __require chunk-AC2VUBZ6.js:11
    <anonymous> Portal.js:2
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Valdas3** [comment]
> Wrong field array name composition
> 
> ```diff
> - const typeName = `test[${index}].type`;
> + const typeName = `test.${index}.type`;
> ```

@Moshyfawn, I have updated the sandbox link with the path syntax you suggested but that does not solve the issue. It can be reproduced in the same way.

**Comment by Moshyfawn** [comment]
> @Moshyfawn, I have updated the sandbox link with the path syntax you suggested but that does not solve the issue. It can be reproduced in the same way.

The reproduction you've linked in your OG post doesn't seem to be throwing the error anymore

https://github.com/react-hook-form/react-hook-form/assets/16290753/b8d52d05-04ce-44d5-9f69-daded44d502f

**Comment by Valdas3** [comment]
The bug does not appear if the second Delete button is clicked. It happens only if the first element is removed.

https://github.com/react-hook-form/react-hook-form/assets/9084046/3b1dace4-f2e2-4d88-b912-4f3c5ac1f299

**Comment by Moshyfawn** [comment]
My bad. Let me take a look

**Comment by Moshyfawn** [comment]
For anyone looking into this issue:

The field reference returned after removing the first row is a object of nested fields instead of a field reference `_f`, hence the error

```json
{
  "from": {
    "_f": {
      "ref": {},
      "name": "test.0.value.from",
      "mount": true,
      "value": "2023-09-25"
    }
  },
  "to": {
    "_f": {
      "ref": {},
      "name": "test.0.value.to",
      "mount": true,
      "value": "2023-09-25"
    }
  }
}
```

Expected

```json
{
  "_f": {
    "ref": {},
    "name": "test.1.value.from",
    "mount": true,
    "value": "2023-09-25"
  }
}
```
```json
{
  "_f": {
    "ref": {},
    "name": "test.1.value.to",
    "mount": true,
    "value": "2023-09-25"
  }
}
```

**Comment by bluebill1049** [comment]
I don't think we support variant shapes of data for field array 

```
default value: {
    test: [
      { type: "text", value: "text value" },
      { type: "date", value: { from: "2023-09-25", to: "2023-09-25" } }
    ]
  }
  ```

**Comment by Moshyfawn** [comment]
Yea, I thought so.. I can't come up with a valid usage example in this case

**Comment by bluebill1049** [comment]
thanks @Moshyfawn for the investigation 🙏 ❤️

**Comment by Valdas3** [comment]
Thanks for investigating. It could be useful to note this limitation in the docs. My use case is to have a form that allows to build a list of filters. Depending on the selected filter type, the filter value could have a different shape. For example, if a user selects a text filter type then he will be shown a single text field to enter the text value. If the date range filter is selected, then two date inputs would be shown instead, similar to how it is shown in the sandbox. One other filter type I am interested in is a multi-select where a user is able to select multiple values from a select input. In this case, the value shape would be an array. It seemed "natural" to use the `useFieldArray` hook for this where each array item could have a different shape. I wonder if there is a better alternative that you could suggest?
