### ISSUE TITLE
issue: async `defaultValues` inherently sets defaultValues to undefined on first render

### ISSUE THREAD

**Issue by jviall** [react-hook-form/react-hook-form#10977]
### Version Number

7.46.2

### Codesandbox/Expo snack

https://codesandbox.io/s/intelligent-rosalind-r4npxm

### Steps to reproduce

1. Open the linked sandbox, which sets the default value of the `firstName` registered text input via an `async` method
2. View the console
3. See that on the first render, the default value is `undefined`, and then later is `''` (empty string).
4. Though defaultValues are should not be initialized to `undefined`, the async behavior does so. This is problematic in that for controlled inputs, the field is switching from uncontrolled to controlled during the resolution of async default values

### Expected behaviour

I'm not sure what the expected behavior of the `defaultValues` prop should be, because I see how this would be hard to work around. Maybe this issue is more appropriate as a discussion question, but the current behavior also seems contradictory to how RHF typically works and the best practices that it encourages, hence why I'm reporting it as a bug.

Ideally, I'm looking for at least a recommended workaround which would prevent a controlled input from initially being interpreted as an uncontrolled input (due to the `value` being `undefined` on first render, and then changing to `''` on subsequent renders once `defaultValues` resolves)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
{firstName: undefined}
{firstName: undefined}
{firstName: ""}
{firstName: ""}
Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at exports.Controller (https://r4npxm.csb.app/node_modules/react-hook-form/dist/index.cjs.js:1:22179)
    at form
    at div
    at App (https://r4npxm.csb.app/src/App.tsx:19:34)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
A valid point! One solution is to establish the field's default value on the `Controller` component while waiting for the remote `defaultValues` to be retrieved.

```jsx
<Controller
  defaultValue=""
  control={control}
  name="firstName"
  render={({ field }) => <input {...field} placeholder="First Name" />}
/>
```

This issue does not apply to uncontrolled components demonstrated in your [reproduction codesandbox](https://codesandbox.io/s/intelligent-rosalind-r4npxm).

**Comment by jviall** [comment]
> This issue does not apply to uncontrolled components demonstrated in your [reproduction codesandbox](https://codesandbox.io/s/intelligent-rosalind-r4npxm).

Ah true, I've updated the sandbox to use `Controller`, which shows the issue more clearly since it outputs the React warning of switching from `Uncontrolled` to `Controlled`:

```
Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at exports.Controller (https://r4npxm.csb.app/node_modules/react-hook-form/dist/index.cjs.js:1:22179)
    at form
    at div
    at App (https://r4npxm.csb.app/src/App.tsx:19:34)
```

**Comment by jviall** [comment]
> One solution is to establish the field's default value on the `Controller` component while waiting for the remote `defaultValues` to be retrieved.

This does indeed work--if ya'll stance is to keep the current behavior as-is, it seems at least appropriate to add a note of this nuance in the documentation?

**Comment by bluebill1049** [comment]
yea, it's difficult in this scenario as we can't predict the value of that input before aysnc value is returned. It works well with uncontrolled, controlled you may want to go down with combine values with defaultValues

```tsx
const {values, isLoading} = useData()
useForm({
  defaultValues: {test: ''},
  values,
})
```

**Comment by kamilkazmierczakMtab** [comment]
Firstly in your sandbox you have another issue which is firstName being typed as string which is not true.
Due to the fact that it is async there is possibility (not in your exact case) that value will be undefined.
There was issue for that already but for some reason was ignored and closed https://github.com/react-hook-form/react-hook-form/issues/10837

**Comment by no-used** [comment]
```typescript
const {values: { test }, isLoading} = useData()

useForm({
  defaultValues: {test: ''},
  values,
})
```

@bluebill1049 is above code what you meant in this below comment right??

> yea, it's difficult in this scenario as we can't predict the value of that input before aysnc value is returned. It works well with uncontrolled, controlled you may want to go down with combine values with defaultValues
> 
> ```tsx
> const {values, isLoading} = useData()
> useForm({
>   defaultValues: {test: ''},
>   values,
> })
> ```
