### ISSUE TITLE
issue with clear array errors in FieldArray

### ISSUE THREAD

**Issue by DisaPadla** [react-hook-form/react-hook-form#1097]
When "errors" is empty the array is not been removed in "errors" object

1. remove value from the first input
2. submit button should be disabled
3. enter "10" to the first input
4. submit button still disabled
5. look at `console.log(errors);`. We still have an array in "errors" object

**Expected behavior**
submit button should be active

**Codesandbox link**
https://codesandbox.io/embed/react-hook-validate-trigger-sb1lj?fontsize=14&hidenavigation=1&theme=dark

**discussion on spectrum**
https://spectrum.chat/react-hook-form/help/strange-validation-behavior-for-fields-array~b6982a9b-25f3-4fc7-adf5-cd3e1f5a27f7

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-validate-trigger-sb1lj

**Comment by DisaPadla** [comment]
Another case which relates to this issue
https://spectrum.chat/react-hook-form/help/error-jumps-to-the-first-field-of-an-array~394e44a8-7cdd-4b3b-adf3-748ce444eca3

**Comment by bluebill1049** [comment]
please help testing on `4.9.9-beta.2`

**Comment by DisaPadla** [comment]
@bluebill1049 I found only 4.9.9-beta.1 on codesandbox. I could test on my own project

**Comment by bluebill1049** [comment]
hey @DisaPadla you can install this beta on the CSB :)

**Comment by DisaPadla** [comment]
@bluebill1049  look at this example
https://codesandbox.io/s/formstate-is-not-still-valid-after-removing-items-ycu19

1. Append two items
2. make "onBlur" for both new items
3. Remove second and third items

**Result**
`formState.isValid` is still false. `errors` object contains `test: [undefined]`

**Comment by bluebill1049** [comment]
aha awesome thanks!

**Comment by DisaPadla** [comment]
I didn't find anything else.

**Comment by bluebill1049** [comment]
Awesome thanks a lot, I will patch that issue tonight. ❤️

**Comment by bluebill1049** [comment]
patched: https://codesandbox.io/s/formstate-is-not-still-valid-after-removing-items-ewufu making PR for the fix now :)

**Comment by DisaPadla** [comment]
`formState.isValid` is still false. Is it okay?

**Comment by bluebill1049** [comment]
u sure? works for me: 
![Screen Shot 2020-02-27 at 8 19 46 pm](https://user-images.githubusercontent.com/10513364/75429850-89cf7200-599e-11ea-9f6a-77683d5b3446.png)

https://codesandbox.io/s/formstate-is-not-still-valid-after-removing-items-ewufu

try again, maybe i forgot to save.

**Comment by DisaPadla** [comment]
Oh, look at this case:
1. Append a second item
2. Append a third item
3. Make onBlur for the second item
4. Make onBlur for the third item
5. Click on Delete for the SECOND item
6. Click on Delete for the third item
`IsValid` is false

But if you replace 5 and 6 steps, like
5. Click on Delete for the THIRD item
6. Click on Delete for the second item
all looks good

**Comment by bluebill1049** [comment]
interesting... you are right

**Comment by bluebill1049** [comment]
sorted :) https://codesandbox.io/s/formstate-is-not-still-valid-after-removing-items-ewufu thanks a lot for your testing effort.

**Comment by DisaPadla** [comment]
looks good for me!

**Comment by bluebill1049** [comment]
awesome! thanks for the verification.
