### ISSUE TITLE
issue: field array value cannot be set in useEffect when values is provided via useForm

### ISSUE THREAD

**Issue by SihenZhang** [react-hook-form/react-hook-form#10976]
### Version Number

7.46.2

### Codesandbox/Expo snack

https://codesandbox.io/s/setvalueforfieldarray-mnfzpl?file=/src/App.js

### Steps to reproduce

1. Go to CodeSandbox
2. It can be seen that the value of `foo` (not a field array) is passed into `values` of `useForm`. And the value of `bar` (is a field array) is set using `setValue` in `useEffect`. However, `bar` is not displayed in the form.
3. Set the value of `bar` via `values` of `useForm` just like the code below and refresh the CodeSandbox. `bar` will be displayed in the form successfully and the value is that in `useEffect`. 
```javascript
const { control, register, setValue, handleSubmit } = useForm({
  values: {
    foo: "foo",
    bar: [{ firstName: 'a', lastName: 'b' }]
  }
});
```
4. Remove `values` in `useForm` and refresh the CodeSandbox. `bar` will also be displayed in the form successfully.

### Expected behaviour

`bar` value can be displayed in the form without step 3 or step 4.
This code worked normally in `7.44.3`, but broke in version `7.45.1` (`7.45.0` has a re-render bug so it is ignored). You can change the  `react-hook-form` version in CodeSandbox to confirm it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is due to `useEffect` execution order with `useFieldArray`. I think you can use reset API to workaround with this issue

```tsx
reset({
  bar: [{ firstName: "Bill", lastName: "Luo" }]
})
```

**Comment by SihenZhang** [comment]
Thanks for your prompt response and suggestion to use the `reset` API as a workaround. However, I am still puzzled about why my code doesn't work with the latest version although it worked perfectly in the previous version. It seems that there were no relevant changes mentioned in the changelog.

Could you provide some insight into what changes were made in `7.45.0/1` that could have affected the execution order of `useEffect` with `useFieldArray`? Understanding this could help me better adapt my code to future updates.

**Comment by bluebill1049** [comment]
I think the root cause is related to this PR: https://github.com/react-hook-form/react-hook-form/pull/10606/files, i am happy to update the change log.
