### ISSUE TITLE
issue: async defaultValues inherently sets serverdata it is not rendering in usefieldarray .Data is coming in getvalues but not in fields

### ISSUE THREAD

**Issue by NarenderDhamarlapally** [react-hook-form/react-hook-form#10983]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-async-values-jxsyj9?file=/src/index.js

### Steps to reproduce

1. Go to codesandbox
2. on first render data server data has two objects in an array but it showing only one .
3. when i remove default values it is working as expected but i want default values also . 
4. in getvalues it is showing two objects .But in fields in usefieldarray

### Expected behaviour

i want default values with Values .
serverData is not loaded in Values.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NarenderDhamarlapally** [comment]
serverData is not loaded in Values

**Comment by bluebill1049** [comment]
This is executive order related, if your values is static why not just put it under `defaultValues`?

**Comment by bluebill1049** [comment]
then just use `reset` api, if your app level

**Comment by NarenderDhamarlapally** [comment]
In my project overall I am using values for serverdata

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
