### ISSUE TITLE
Field array rearrangement preserves values from other fields

### ISSUE THREAD

**Issue by Skysplit** [react-hook-form/react-hook-form#1098]
**Describe the bug**
When rearranging set of fields, very often values from one field are stored or copied to another fields.

**To Reproduce**
Steps to reproduce the behavior - based on codesandbox
1. Add item to second section
2. Click `shuffle` (or move newly created item by yourself using drag&drop)
2. Click `values`
2. Check console log
2. Console shows `id: 4` for newly created value that shouldn't have id.

This is only one of the issues. If you try to play around with adding items, and draging items or sections around, you can see that values are going absolutely crazy and are copied/duplicated/misplaced all around.

Also additionnaly, if you have `defaultValues` set, removing item and adding it back again fills it up with default values, where it actually shouldn't (because we just removed this value, we don't need to have it back to default when adding it again)

**Codesandbox link**
https://codesandbox.io/s/kind-butterfly-6z4n9

**Expected behavior**
Inputs are preserved as they are in the item - without additional fields

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 79

**Comment by bluebill1049** [comment]
hey @Skysplit thanks for the detailed issue report, to be honest i haven't tried with drag and drop with useFieldArray. can you keep provide a simple example?

**Comment by bluebill1049** [comment]
I will put this one to the back log, currently we don't support drag and drop behaviour just yet and haven't tested with any lib as well.

**Comment by bluebill1049** [comment]
if you are reading this issue, if you are working with drag and drop/ virtual scroll. i will recommend not to register the input ref, rather register inputs at `useEffect` and update value with `setValue`.

here is an example and guide: https://react-hook-form.com/advanced-usage#Workingwithvirtualizedlist
