### ISSUE TITLE
Wrong name of an option in the doc

### ISSUE THREAD

**Issue by DZakh** [react-hook-form/react-hook-form#1100]
**Describe the bug**
The hook option `reValidateMode` in doc, in reality, is called just `mode`.

**To Reproduce**
1. Go to https://react-hook-form.com/api
2. Look for `reValidateMode`
3. Go to https://codesandbox.io/s/react-hook-form-errors-validatecriteriamode-all-5l2lm
4. Look for `mode`

**Additional context**
It was very difficult to debug :)

**Comment by bluebill1049** [comment]
what's the issue in here?
```
mode: 'onSubmit',
reValidateMode: 'onChange',
```

they r two seperate thing.

**Comment by DZakh** [comment]
> what's the issue in here?
> 
> ```
> mode: 'onSubmit',
> reValidateMode: 'onChange',
> ```
> 
> they r two seperate thing.

`revalidateMode` didn't work for me, compare to `mode`.

**Comment by DZakh** [comment]
Ah, sorry, I got it. `revalidateMode` works with errored fields. My fault.

**Comment by bluebill1049** [comment]
yep, all good :)
