### ISSUE TITLE
`required` validation breaks on disabled radio buttons

### ISSUE THREAD

**Issue by samuelstecher** [react-hook-form/react-hook-form#11001]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-disabled-radio-buttons-not-working-whsyjh?file=/src/App.js

### Steps to reproduce

Starting conditions:
- There is a radio group with multiple radio buttons.
- All of the radio buttons are disabled.
- There is a required validation passed for each radio button
- There is a default value provided for the group

Reproduction:
1. Click on submit

Possible workaround:
If the radio button with the set value is not disabled, the validation passes successfully.

### Expected behaviour

Since there is a default value set, I would expect the `required` validation to pass and the form be successfully submitted.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
disabled prop should be part of the register api

**Comment by samuelstecher** [comment]
@bluebill1049 if I add `disabled: true` to the `registerOptions` the validation doesn't fail anymore that's correct. However, I still get `{ example: undefined }` as data instead of `{ example: '2' }` as was passed as default.

Isn't that a bug?
