### ISSUE TITLE
issue: resetField/setValue not working

### ISSUE THREAD

**Issue by thany** [react-hook-form/react-hook-form#11003]
### Version Number

7.47.0

### Codesandbox/Expo snack

https://codesandbox.io/s/youthful-fire-5gkf7d?file=/src/App.tsx

### Steps to reproduce

1. Change field 2
2. Change field 1
3. Now empty field 1

### Expected behaviour

Field 2 should be cleared, because it's calling `resetField` on it. The same issue appears when I call `setValue` with an empty string on it.

I'm using `getValues` on field 1 as a `useEffect` depedency, and when that value becomes empty, it clears field 2. The documentation says you can't use `watch` for useEffect deps, so I guess I shouldn't. It really doess call either function, which is totally verifyable if you take the effort of putting a console.log there.

When adding a `watch('field1')` and *nothing else*, it suddenly starts working. I'm no expert, but that feels like a side-effect type of bug. 

If this is working as designed, then please change the design, innit 🙂
There shouldn't be any arbitrary restrictions or conditions when calling these funtions. If I need to reset the field, the field must be reset. That's basically all there is to it from my perspective. If for some reason `resetField` or `setValue` cannot do its job, I would expect an error to be thrown, so that at the very least I know *why* it cannot do what I'm asking.

For what it's worth, the documentation doesn't state any conditions that must be met, or any counter-conditions that mustn't be met, unless I'm missing something.

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thany** [comment]
And furthermore: after calling `resetField`, even with the watch, I find there's a difference between its `field.value` and the `watch('field2')`. The result of `getValues()` also reveals that `field2` gets deleted from the return object, and yet, a value remains in the `field` object in the controller.

So one of these I will have to consider unreliable 😟

**Comment by Moshyfawn** [comment]
Can you please share where you found that using the `watch` API should be avoided?

The `getValues` function doesn't subscribe your component to field value updates; it just retrieves the current values when executed. In your code, it runs on component re-render but doesn't trigger it.

```diff
- const field1Value = getValues("field1");
+ const field1Value = watch("field1");
```

**Comment by Moshyfawn** [comment]
> `resetField` doesn't work for any field that has an `undefined` default value

RHF does not allow using `undefined` as a default value for inputs in React because it could cause a mix-up between controlled and uncontrolled inputs.

**Comment by bluebill1049** [comment]
> If this is working as designed, then please change the design, innit 🙂

Alternatively, you can always fork the repo and adjust it to the way that suits your need and publish it. It's an open-source project.

**Comment by thany** [comment]
@Moshyfawn 

> Can you please share where you found that using the `watch` API should be avoided?

It's here: https://react-hook-form.com/docs/useform/watch

In the `RULES` block, last bullet point.

**Comment by ibovegar** [comment]
Having the same issue. 
resetField('foo') not working, i.e. value is not cleared. 
Calling reset() works.

**Comment by thany** [comment]
May I ask why this is 'not planned'?

**Comment by nichita-pasecinic** [comment]
I face the same issue `resetField` in a useEffect doesn't work, but `reset` API does
