### ISSUE TITLE
issue: updating a nested field doesn't update value for parent field

### ISSUE THREAD

**Issue by NullDivision** [react-hook-form/react-hook-form#11007]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/misty-lake-zvx9mn?file=/src/App.js

### Steps to reproduce

1. Have a nested object structure (eg. `{ parent: { child1: "child1"; child2: "child2" } }`)
2. Create a controller for field "parent" with a custom component using value.child1 as value
3. Create a controller for field "parent.child2"
4. Change input of "parent.child2" to "some-new-child2"
5. Change input of "parent" to "some-new-child1"

### Expected behaviour

`value` property for "parent" field is { child1: "some-new-child1", child2: "some-new-child2" }

### Relevant log output

```shell
parent value: {child1: "child1", child2: "child2"}
parent.child2 value: child2

// Intermediate change logs removed...
parent.child2 value: some-new-child2 
// Intermediate change logs removed...
parent value: {child1: "some-new-child1", child2: "child2"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Doesn't support such usage.
