### ISSUE TITLE
Lazily evaluate `FieldPath<TFieldValues>` for better TS performance when using `setValue`

### ISSUE THREAD

**Issue by jussisaurio** [react-hook-form/react-hook-form#11018]
**Is your feature request related to a problem? Please describe.**

Typechecking `setValue` invocations results in poor TS performance with `type UseFormSetValue` when `TFieldValues` is a complex type. This is especially noticeable as sluggish VSCode autocompletion times, but also in 'offline' compilation times.

The project I discovered this behavior in is closed source, so I'm -- for now -- unfortunately only including some screenshots of a TS performance traces captured using `tsc --generateTrace`, plus some rationale and code snippets.

**Performance trace**

This is how much time it takes to typecheck a single `setValue` call in this particular project (the type ID of the type in question points to `UseFormSetValue`:

---

<img width="234" alt="image" src="https://github.com/react-hook-form/react-hook-form/assets/22619982/efb62d3f-20f6-4d72-a7fd-e0a541a73a63">

---

I believe the culprit to be this line:
https://github.com/react-hook-form/react-hook-form/blob/0d565fcf944621f5510da4623129ffbd238f9530/src/types/form.ts#L529

My (perhaps unfounded) assumption is that the `extends` constraint results in the full union of `FieldPath<TFieldValues>` being eagerly evaluated every time. 

**Describe the solution you'd like**
I believe constraining `TFieldName` to just `string` would be an acceptable solution, because the type helpers `PathValue` and friends eventually will make conditional checks to narrow the type of `TFieldName` anyway. Constraining to `string` allows lazily evaluating whether the provided type parameter conforms to a valid path, and importantly -- terminating early when it either does or doesn't. Developer experience (`the type "foobar" is not assignable to "path | path.subpath | path.anotherPath ...."`) is preserved with a conditional check:

``` 
export type UseFormSetValue<TFieldValues extends FieldValues> = <
  TFieldName extends string,
>(
  name: FieldPathValue<TFieldValues, TFieldName> extends never
    ? FieldPath<TFieldValues> // <-- "the type "foobar" is not assignable to path | path.subpath | path.anotherPath ...."
    : TFieldName,
  value: FieldPathValue<TFieldValues, TFieldName>,
  options?: SetValueConfig,
) => void;
```

`PathValue` and `FieldPathValue` do not need to constrain `P` because they do conditional type checking wrt. `T` anyway and return `never` in error cases:

```
-export type PathValue<T, P extends Path<T> | ArrayPath<T>>
+export type PathValue<T, P extends string>

 export type FieldPathValue<
   TFieldValues extends FieldValues,
-  TFieldPath extends FieldPath<TFieldValues>,
+  TFieldPath extends string,
```

**Effect on performance**
These changes have the following effect -- here is the same type being checked after the changes:

---

<img width="220" alt="image" src="https://github.com/react-hook-form/react-hook-form/assets/22619982/e4720936-8eb1-4508-af69-57d27eb5f60a">

---

Subjective wall clock time of VSCode autocompletion is also improved. (Sorry, I can try to provide TSServer logs later if necessary...)

**Final thoughts**

I spent a lot of effort coming up with a solution that would help performance while not resulting in any UX changes, hopefully I haven't missed anything. Although the public types do change, so this might be considered a breaking change?

Linked a PR with the full diff to this issue.

Finally, I think a similar approach could be used for `useFieldArray` and others etc.

EDIT: oh, and this is totally not a "feature request", whoops 😂

**Comment by bluebill1049** [comment]
I think this is could be a breaking change and potentially break type check for register input name.

**Comment by marvinderksen** [comment]
I looking for a fix because I can reproduce the described issue. There are massive performance implications when providing the field name not directly as template literal to `getValues` or `setValue` but eg. as a received argument that is typed like the above mentioned. 
Consider anything like:
```ts
export const useProxy = <Path extends FieldPath<FormModel>>(
  fieldPath: Path
) => {
  const { getValues, setValue } = useFormContext<FormModel>();

  const proxy = {
    value: getValues(fieldPath),
    onChange: (e) => setValue<Path>(fieldPath, e.target.value)
  };

  return proxy ;
};
```
(this is extremely generalized ofc)

I'd be glad if this issue was reopened for the sake of a solution :)

**Comment by marvinderksen** [comment]
> I looking for a fix because I can reproduce the described issue. There are massive performance implications when providing the field name not directly as template literal to `getValues` or `setValue` but eg. as a received argument that is typed like the above mentioned. Consider anything like:
> 
> ```ts
> export const useProxy = <Path extends FieldPath<FormModel>>(
>   fieldPath: Path
> ) => {
>   const { getValues, setValue } = useFormContext<FormModel>();
> 
>   const proxy = {
>     value: getValues(fieldPath),
>     onChange: (e) => setValue<Path>(fieldPath, e.target.value)
>   };
> 
>   return proxy ;
> };
> ```
> 
> (this is extremely generalized ofc)
> 
> I'd be glad if this issue was reopened for the sake of a solution :)

Is #7387 an actual fix?
