### ISSUE TITLE
issue: incorrect isDirty values in formGroups

### ISSUE THREAD

**Issue by marit970** [react-hook-form/react-hook-form#11010]
### Version Number

7.47.0

### Codesandbox/Expo snack

https://github.com/marit970/react-hook-form-isDirty

### Steps to reproduce

1. Type something in one of the textInputs
2. Note that instead of the other field being disabled, both fields are disabled now

### Expected behaviour

In our use case, we are using multiple groupForms with inputs and want the other group/input to be disabled once the user has started to type something in one of the input fields. I have tried to reproduce this behaviour and created a minimal example with two fromGroups('name' and 'state') with a text input inside each group. When the user types something in the 'name'-field, the other one ('state') should be disabled. And the other way around, when typing something in 'state', 'name' should be disabled respectively. Instead of this, both fields are disabled when starting to type something in one of the fields because of incorrect isDirty values.       

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
follow the issue template and provide a codesandbox

**Comment by marit970** [comment]
@bluebill1049 Hi, I have updated the issue and added a codesandbox example. Could you please re-open the ticket?
