### ISSUE TITLE
Android TextInputs with watch:  The first written letter is deleted 

### ISSUE THREAD

**Issue by gongallego** [react-hook-form/react-hook-form#1101]
I want to change the style of my input when it has text or not. To see the value of the input I use the watch method. I have the problem that when I write some text in the input, the first letter I write is removed applying the old style, and after that, it changes the style, so the second letter I write looks with the new style. I have seen that the problem occurs only on Android devices

My code is: 
**Expo link**
https://snack.expo.io/@gongalo/error-on-watch-react

**Expected behavior**
I want to write in the input and have the style changed automatically without deleting any letters

**Smartphone (please complete the following information):**
 - OS: [e.g. Android 7.0]

**Comment by bluebill1049** [comment]
have you tried with Controller?

**Comment by gongallego** [comment]
Yes, but there I have the problem that in Android:
args[0].nativeEvent.text
is undefined

**Comment by bluebill1049** [comment]
what's inside of args[0]?

**Comment by gongallego** [comment]
were all fields, but initialized to undefined.

Anyway, I changed the inputs to Controller again, I deleted all the caches and it seems that the Controller works. I keep wondering why without the Controller is not running

**Comment by bluebill1049** [comment]
cool glad it's working then.

**Comment by bluebill1049** [comment]
i am going to close this as it's working for you now.
