### ISSUE TITLE
Required configuration as object not working as expected

### ISSUE THREAD

**Issue by antonbehaeghe** [react-hook-form/react-hook-form#1102]
When configuring the required value in a register function as an object, it's not working as expected. According to the documentation it can be a string, or an object with a value and a message. When configured as an object it is always required  even when the value is set to false.

`ref={methods.register({
            required: {
              value: false,
              message: "also required"
            }
          })}`

https://codesandbox.io/s/react-hook-fom-required-manual-register-52dsg

**Comment by bluebill1049** [comment]
Please use the latest version: https://codesandbox.io/s/react-hook-fom-required-manual-register-tp2tk as we have already patched this.
