### ISSUE TITLE
useFieldArray on append uses incorrect value if field can be undefined

### ISSUE THREAD

**Issue by wadeamaral** [react-hook-form/react-hook-form#11020]
### Version Number

7.46.1

### Codesandbox/Expo snack

https://codesandbox.io/s/usefieldarray-6r2xsr?file=/src/App.tsx

### Steps to reproduce

1. GetValues
2. Add new rows and notice correct values (field 2 is undefined)
3. Remove all rows
4. Add 3 rows (first 2 are incorrect - it is pulling the default values instead of undefined)

### Expected behaviour

Field 2 in codesandbox should be undefined always.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://react-hook-form.com/docs/usefieldarray

please refer to the doc



> Append input/inputs to the end of your fields and focus. The input value will be registered during this action.Important: append data is required and not partial.
