### ISSUE TITLE
issue: Reset() leads to submit

### ISSUE THREAD

**Issue by qt-inbolt** [react-hook-form/react-hook-form#11029]
### Version Number

7.47.0

### Codesandbox/Expo snack

Sorry no sandbox

### Steps to reproduce

I am sorry, I don't think I can reproduce the bug outside the context of my company's React application.

I made a reusable component input by using `useController`.

In the form component, I have const `reset` by destructuring `useForm`, and 2 `<button>` reset and submit in the `<form>`. I set `onClick={() => { reset() }}` for my reset button, but somehow it submits my form when I want to reset by clicking it. 

### Expected behaviour

The button reset inside the form should not submit the form but only reset the defaultValue of each input in the form.

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
type="button"
