### ISSUE TITLE
issue: TTransformedValues causing typescript error when used, and input/output zod schema validation is not woring correctly

### ISSUE THREAD

**Issue by darktasevski** [react-hook-form/react-hook-form#11023]
### Version Number

7.47.0

### Codesandbox/Expo snack

https://codesandbox.io/s/lucid-lewin-9l95dy?file=/src/App.tsx

### Steps to reproduce

1. Go to the shared Codesandbox link and wait for it to initialize
2. Pull up the Console view
3. Click on the Submit button
4. Observe that the form was not validated, no errors are reported, and seems to be submitted successfully
5. Observe Ts error in the `App.tsx`:

```
Type 'UseFormReturn<{ hasPerks: string | null; }, unknown, { hasPerks: string; }>' is not assignable to type 'UseFormReturn<{ hasPerks: string; }, unknown, { hasPerks: string; }>'.
  The types returned by 'watch()' are incompatible between these types.
    Type '{ hasPerks: string | null; }' is not assignable to type '{ hasPerks: string; }'.
```

### Expected behaviour

No Ts error and zod validation should fail as per output schema values.

If I'm not using this input/output schema correctly, so I'd much appreciate any suggestions. I would expect that the input schema would allow for the value to be a nullable string (InputSchema), but at the submit step it should be a non-nullable string (OutputSchema).

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Wekios** [comment]
Experienced this issue too

**Comment by KilianB** [comment]
Here is a simple reproducible example with `yup`. The handlers are correctly typed but the resolver needs to be cast to `any` in order to comply

````tsx
type Gender = 'male' | 'female';

interface TestFormSchema {
  name: string;
  gender: Gender | null;
}

const schema = yup.object({
  name: yup.string().required(),
  gender: yup.string<Gender>().defined().oneOf(['male', 'female']),
});

type OutputSchema = yup.InferType<typeof schema>;

export const TestForm = () => {
  const initialValue: TestFormSchema = {
    name: '',
    gender: null,
  };

  const { handleSubmit } = useForm<TestFormSchema, any, OutputSchema>({
    defaultValues: initialValue,
    resolver: yupResolver(schema) as any,
  });

  handleSubmit((values) => {
    //Correctly typed
    console.log(values);
  });
};
````

**Comment by demsey2** [comment]
not sure if that will help, but I had similar issues and the problem was tsconfig, I had to change to 
```
"strictNullChecks": true,
```

**Comment by ClementCornut** [comment]
Seems like TTransformedValues is'nt forwarded to UseFormProps who handle the resolver type. I haven't dig too far but I think the solution might be to do the same condition as the one in UseFormHandleSubmit

`export declare function useForm<TFieldValues extends FieldValues = FieldValues, TContext = any, TTransformedValues extends FieldValues | undefined = undefined>(props?: UseFormProps<TFieldValues, TContext>): UseFormReturn<TFieldValues, TContext, TTransformedValues>;`

`export type UseFormProps<TFieldValues extends FieldValues = FieldValues, TContext = any> = Partial<{
    ...
    resolver: Resolver<TFieldValues, TContext>;
    ...
}>;`

`Resolver<TTransformedValues extends FieldValues ? TTransformedValues : TFieldValues, TContext>`

**Comment by darktasevski** [comment]
> Seems like TTransformedValues is'nt forwarded to UseFormProps who handle the resolver type. I haven't dig too far but I think the solution might be to do the same condition as the one in UseFormHandleSubmit
> 
> `export declare function useForm<TFieldValues extends FieldValues = FieldValues, TContext = any, TTransformedValues extends FieldValues | undefined = undefined>(props?: UseFormProps<TFieldValues, TContext>): UseFormReturn<TFieldValues, TContext, TTransformedValues>;`
> 
> `export type UseFormProps<TFieldValues extends FieldValues = FieldValues, TContext = any> = Partial<{ ... resolver: Resolver<TFieldValues, TContext>; ... }>;`
> 
> `Resolver<TTransformedValues extends FieldValues ? TTransformedValues : TFieldValues, TContext>`

I tried to modify the package to forward the `TTransformedValues` where it should, but every change I made resulted in a bunch of different Ts errors, so I gave up 😞

**Comment by mildfuzz** [comment]
This could be related to this https://github.com/react-hook-form/react-hook-form/issues/11244

**Comment by mildfuzz** [comment]
I think this fixes it https://github.com/react-hook-form/react-hook-form/pull/11245

**Comment by bluebill1049** [comment]
thanks @mildfuzz
