### ISSUE TITLE
issue: Reset method, when use "values" parameter, it overwrites defaultValues

### ISSUE THREAD

**Issue by stefanoinf** [react-hook-form/react-hook-form#11039]
### Version Number

7.47.0

### Codesandbox/Expo snack

https://codesandbox.io/s/loving-ully-5kjjtf

### Steps to reproduce

1. Insert something in "Field 1" input
2. Press the button "Reset field 1". It will set that field to empty correctly
3. Now click on "Assign default values" button, it will assign "1" to the field 1
4. Now click the button "Reset field 1" again, but this time the field will remains to 1 because the default value has been overwritten to "1"

### Expected behaviour

I assign these values to defaultValues:

```
field1: "",
field2: ""
```

but when I call:

```
reset({
  field1: "1",
  field2: "2"
});
```

it will overwrites the defaultValues, so when I will call

`resetField("field1");`

it will set it to `1` and not to `""` as I would expect in the "defaultValues".

I know that a solution could be `setValue` instead of `reset`:
```
setValue("field1", "1");
setValue("field2", "2");
```
so it will not change the default values, but in my case, I have many many fields, and they are objects, so it will be very long, repetitive and unelegant to write:

```
setValue("mainField1.field1", obj.mainField1.field1);
setValue("mainField1.field2", obj.mainField1.field2);

setValue("mainField2.field1", obj.mainField2.field1);
setValue("mainField2.field2", obj.mainField2.field2);

...continue for so many fields
```

so I'd rather to simply set obj like this: `reset(obj)`

maybe we need something like `setValues` where you can pass an object and it will set the values to the form

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://react-hook-form.com/docs/useform/reset

`keepDefaultValues: true`
