### ISSUE TITLE
issue: formState.isValid always returns false at the initiation of component

### ISSUE THREAD

**Issue by qt-inbolt** [react-hook-form/react-hook-form#11030]
### Version Number

7.47.0

### Codesandbox/Expo snack

Sorry no sandbox

### Steps to reproduce

I am sorry, I don't think I can reproduce the bug outside the context of my company's React application.

I made a reusable component input by using `useController`.

In the form component, I use a custom hook `useKeyDown` to listen to the key `'Enter'`, when user presses the key `Enter`, method `handleSubmitFormWithoutData` is called. This permits user to have another way to submit the form beside clicking the button type `submit` inside the `<form>`. 

Here is the example:
`
const handleSubmitFormWithoutData = () => {
    if (formState.isValid) {
      props.submitData({
        name: getValues().name,
      })
    } else {
      trigger();
    }
  }
`
The first time I press `Enter`, `formState.isValid` always return false despite the defaultValue and the rule required, on the second time I press the key `Enter`, `formState.isValid` will return the "true" value (if the required fields are filled with the right pattern or not).

### Expected behaviour

On the first time I press Enter, `formState.isValid` should return the value correspond to the status of the form.

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
expected behavior.
