### ISSUE TITLE
Using an array of fields with yup for validation

### ISSUE THREAD

**Issue by zahir-koradia** [react-hook-form/react-hook-form#1105]
**Describe the bug**
When using yup for validating a form that has an array of nested shapes, the errors object for the array of fields doesn't have any way to identify which item in the array is invalid. 

It is possible that I am just using the errors object wrong here, in which case, it would be great to know the right way to do this.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-array-fields-yq0dm
2. Click on 'Add Friend' twice
3. Enter first name and last name only for the first friend
4. Click 'Submit Query'
5. Error message is shown for the first friend where the data is valid. Console has logged errors which only has friends as a list with no way to know which friend has a problem.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-array-fields-yq0dm

**Expected behavior**
There should be a way to know which field in the array has validation issues.

**Comment by bluebill1049** [comment]
I think the issue is reported here as well: https://github.com/react-hook-form/react-hook-form/issues/1097

**Comment by zahir-koradia** [comment]
Thanks Bill. I saw that issue, but wasn't quite sure if it's the same root cause. Please let me know if/when you would like me to test any changes.

**Comment by bluebill1049** [comment]
let's keep this issue, I will verify and release beta and get you guys to help on test the fix.

**Comment by bluebill1049** [comment]
can you please test on this beta for us? `4.9.9-beta.2`

**Comment by zahir-koradia** [comment]
The bug is fixed in this beta. Thank you so much for such a quick turn around.

**Comment by bluebill1049** [comment]
thanks @zahir-koradia for the testing. FYI: i still got one more bug to fix and we will release the minor version this weekend :)
