### ISSUE TITLE
issue: custom validation does not work when the response of the function is not a string or boolean

### ISSUE THREAD

**Issue by lauraBaakman** [react-hook-form/react-hook-form#11054]
### Version Number

7.44.0

### Codesandbox/Expo snack

https://codesandbox.io/s/throbbing-firefly-q7k6t6?file=/src/App.js

### Steps to reproduce

1. Click on 'Submit'
4. See only one error

### Expected behaviour

Expected both the error for the field 'firstName' and the field 'lastName to be shown. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
can't support JSX due to typescript support.
