### ISSUE TITLE
issue: FieldArray changes unique id when change field via update or setValue

### ISSUE THREAD

**Issue by dremedys** [react-hook-form/react-hook-form#11058]
### Version Number

7.47.0

### Codesandbox/Expo snack

https://codesandbox.io/s/exciting-paper-w274jp?file=/src/App.tsx

### Steps to reproduce

1. Create a form with fieldArray
2. Try to update using fieldArray.update() or setValue() to change existing fields field, like items[0].text

### Expected behaviour

field id stays the same AND other fields of field doesnt reset

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
expected behaviour, for uncontrolled inputs this is required.

**Comment by dremedys** [comment]
> expected behaviour, for uncontrolled inputs this is required.

so what can i do? When i update items[0].isRight via update or setValue, it resets items[0].name :(
