### ISSUE TITLE
issue: Lose focus after 1st character in 1st input if valid, lose focus after 1st character in last invalid input of form

### ISSUE THREAD

**Issue by qt-inbolt** [react-hook-form/react-hook-form#11079]
### Version Number

7.47.0

### Codesandbox/Expo snack

Sorry no sandbox

### Steps to reproduce

Sorry I cannot reproduce due to the complicated context of my company's application.
But here is the video about my issue:

[Screencast from 19-10-2023 19:20:15.webm](https://github.com/react-hook-form/react-hook-form/assets/126157738/6f970f4a-1222-43ee-bdb8-f44a7b077dad)

About my components, I have:
- `InputComponent` created with `useController`
- `FormComponent` created with `useForm` and has many `InputComponent`s inside, it passes the `control` to its `InputComponent`s
- `GeneralComponent` contains `FormComponent`

The `FormComponent` will send actively 2 methods to `GeneralComponent` via its props by 2 buttons, this means onChange of `InputComponent` doesnt affect anything at all and I dont use onChange.

I use an array of objects to map and create ReactNode which is the `InputComponent`.

When there are many invalid fields, I only lose focus after typing the 1st and the 2nd characters of the last invalid field.

### Expected behaviour

The input should not lose focus.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
I doubt there's an easy way for us to help you debug the problem without seeing the code.

The #1 cause of all focus issues is defining components within the body of another component. Try checking your codebase for component initialization such as

```jsx
function Form () {
  function Input () { // <-- this is the problem
    return <input />
  }

  return (
    <form>
      <Input />
    </form>
  )
}
```

**Comment by qt-inbolt** [comment]
> I doubt there's an easy way for us to help you debug the problem without seeing the code.
> 
> The number one cause of all focus issues is defining components within the body of another component. Try checking your codebase for component initialization such as
> 
> ```js
> function Form () {
>   function Input () { // <-- this is the problem
>     return <input />
>   }
> 
>   return (
>     <form>
>       <Input />
>     </form>
>   )
> }
> ```

Thank you, the mapping to create the ReactNodes (Inputs inside the form) seems to cause the bug. I had to type inputs manually to get rid of the bug.
