### ISSUE TITLE
issue: useController doesn't clear defaultValue when you call setValue

### ISSUE THREAD

**Issue by paprikati** [react-hook-form/react-hook-form#11075]
### Version Number

7.47.0

### Codesandbox/Expo snack

https://codesandbox.io/s/musing-mclaren-5j8x7y?file=/src/App.tsx

Same code is in a gist [here](https://gist.github.com/paprikati/82c58b025e3e7a0ce685e9e441f5970f)

### Steps to reproduce

1. Create a form and wrap it in a form provider
2. Instantiate a defaultValue for a form element that's got an object value (e.g. for a dropdown which stores something like {label: "A", value: "a"})
3. Call `setValue("path", undefined)` on that form element
4. watch("path") will correctly return undefined, but the `field.value` that comes from `useController` will still have the defaultValue.

### Expected behaviour

I should always get the same result from `watch("path")` and `useController({name: "path"}).field.value`

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> 

The value for the field. This argument is required and can not be undefined.
--


https://react-hook-form.com/docs/useform/setvalue

**Comment by paprikati** [comment]
@bluebill1049 if I want to clear out the value of this optional part of the form data, what should I be doing instead?
