### ISSUE TITLE
Using mode: 'onChange' does not trigger validation, but 'onBlur' works fine

### ISSUE THREAD

**Issue by mikeislearning** [react-hook-form/react-hook-form#1108]
**Describe the bug**

Whenever I set `mode: 'onChange'` it does not work as expected after I start typing into a form input field.
Putting anything into `reValidateMode` seems to have no impact

**To Reproduce**

1. Set mode to 'onChange' in the useForm declaration, and use the `Controller` component for all form fields in React Native
2. Ensure you're using `watch()`
3. Use a validationSchema like `yup`
4. As you type characters into the TextInput fields, it will not trigger

While the validation error message may change, it will never consistently clears the errors. 

**Expected behavior**

I want to be able to use `formState.isValid` to check whether the user can press the submit button as soon as the form is valid, but because `onChange` isn't working, I'm having to check each field manually on every rerender to determine whether or not the submit button should be disabled

**Versions**

- iOS 13.3
- React Native 0.61.2
- React-hook-form: 4.9.8
- yup 0.27.0
- Node 12.13

**Comment by bluebill1049** [comment]
can you please provide a codesandbox for this isseu?

**Comment by mikeislearning** [comment]
Actually I ended up solving my own issue

The problem was that I didn't set the 3rd parameter for the `setValue` to `true`. So it's all good

Thank you @bluebill1049  for your timely response!

**Comment by bluebill1049** [comment]
Cool awesome :) thanks for the update.

**Comment by vemundeldegard** [comment]
How did you solve this with the 3rd parameter to `true`? It does not work for me. I can see a rerender of the `useForm` methods, but the `handleSubmit` function is not triggered?

**Comment by bluebill1049** [comment]
Plz provide more context.

**Comment by johnmikel** [comment]
I agree, this post lacks context.
