### ISSUE TITLE
How can make OnChange in Controller return real type 👀

### ISSUE THREAD

**Issue by PeterChen1997** [react-hook-form/react-hook-form#11100]
**Is your feature request related to a problem? Please describe.**

https://github.com/orgs/react-hook-form/discussions/11097

**Describe the solution you'd like**

the onChange return the real value type 👀

**Describe alternatives you've considered**

none

**Additional context**

none

**Comment by Moshyfawn** [comment]
#10342

**Comment by bluebill1049** [comment]
Could be included in the next breaking change. or else everyone going to scream for the breaking.
