### ISSUE TITLE
issue: formState no longer updates when some inputs are disabled

### ISSUE THREAD

**Issue by jessypouliot98** [react-hook-form/react-hook-form#11106]
### Version Number

7.47

### Codesandbox/Expo snack

https://codesandbox.io/s/reverent-wilbur-l952z4?from-embed=&file=/src/App.js

### required things to trigger the issue

1. one or more inputs must have `{ disabled: true }` in their register options `register("foo", { disabled: true })`
2. `useForm()` has to have ran twice before the user tries to input anything. Otherwise the main issue doesn't trigger.

### Steps to reproduce

1. rerender the component to cause `useForm()` to run again (click the button on top of the page to do this in the codesandbox)
4. isDirty is initially false (expected)
5. edit an input
6. isDirty is not changed to true (unexpected) and component has not rerendered (unexpected)

### Expected behaviour

1. rerender the component to cause `useForm()` to run again (click the button on top of the page to do this in the codesandbox)
3. isDirty is initially false (expected)
4. edit an input
5. isDirty is changed to true and component will rerender

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cs25-esc** [comment]
could you please elaborate your issue?

**Comment by jessypouliot98** [comment]
> could you please elaborate your issue?

I updated the issue/codesandbox with a better description and exact way to trigger the issue

**Comment by jessypouliot98** [comment]
I've opened a PR with a jest test to reproduce this issue. This was difficult to figure out, but strictMode and a rerender must happen before updating the form to trigger the issue
