### ISSUE TITLE
Enhance get.ts to support complicated structure

### ISSUE THREAD

**Issue by Tocknicsu** [react-hook-form/react-hook-form#1110]
https://codesandbox.io/s/react-hook-form-unregister-bhdwm

Here is a minimum app. Due to legacy code, I have some field name looks like `["first.name"].test`. And `defaultValue` cannot fill value to it. However, `onSubmit` looks work fine. And my temporary solution is change the field name after download data from server then rename again before send to server.

I also trace some code, it looks like [logic/getDefaultValue.ts](https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/getDefaultValue.ts) use [utils/get.ts](https://github.com/react-hook-form/react-hook-form/blob/master/src/utils/get.ts) but [logic/transformToNestObject](https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/transformToNestObject.ts.ts) use [utils/set.ts](https://github.com/react-hook-form/react-hook-form/blob/master/src/utils/set.ts). They have different policy to parse string to path.

And I think it will be nice if `get.ts` use same way parse string as `set.ts`,

**Comment by bluebill1049** [comment]
is there a way for you to get around this issue without modify the lib?

**Comment by Tocknicsu** [comment]
Yes, the simplest way without modify the lib is changing the field name and then processing data one by one to fit origin format after submit.

**Comment by bluebill1049** [comment]
cool, you happy if we put this into the backlog and come back to it as it's not high priority as others.

**Comment by bluebill1049** [comment]
![Screen Shot 2020-02-28 at 11 27 02 am](https://user-images.githubusercontent.com/10513364/75499148-46681880-5a1d-11ea-9606-1ca03dbccf63.png)
added to our backlog
