### ISSUE TITLE
issue: Moving deeply nested field array leads to crash

### ISSUE THREAD

**Issue by vuggy17** [react-hook-form/react-hook-form#11114]
### Version Number

7.47

### Codesandbox/Expo snack

https://codesandbox.io/s/miniform-7htxhk

### Steps to reproduce

1. Click move up on the second field 

### Expected behaviour

Field is moved up and app not crash

### What browsers are you seeing the problem on?

Edge

### Relevant log output

```shell
TypeError: Cannot set properties of undefined (setting 'mount')
    at updateMounted (useController.ts:89:18)
    at useController.ts:110:11
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vuggy17** [comment]
Hello. any update on this?

**Comment by bluebill1049** [comment]
prepare a code sandbox without all the external dependency, with native input input. 
![Screenshot 2023-11-05 at 3 25 47 pm](https://github.com/react-hook-form/react-hook-form/assets/10513364/cfbbb324-4198-4bb3-9230-56290d568c4d)

**Comment by vuggy17** [comment]
I have prepared the sandbox, could you please take a look? [sandbox](https://codesandbox.io/s/miniform-forked-9ph787)

**Comment by vuggy17** [comment]
Could anyone take a look on this?

**Comment by bluebill1049** [comment]
thanks @Moshyfawn and this is another reason i asked for cleaner codesandbox without a hidden "gem" as such, changing time on the fly with the following will not work.

```
const input = useMemo(() => {
    if (type === "textInput")
      return <ControlledInput control={control} name={`${fieldName}.0.text`} />;
    if (type === "select")
      return <ControlledSelect control={control} name={fieldName} />;
  }, [control, fieldName, type]);
  ```

**Comment by vuggy17** [comment]
@bluebill1049 @Moshyfawn 
Thank you for taking your time to answer me 💯 
I think we can close this issue since I have found another way to swap inputs with different types (using fields from `useWatch`), but I remember that I could swap those inputs some days ago before I started to edit that sandbox. I'll tell you when I found it.

And thank you again for creating such a great library!
