### ISSUE TITLE
issue: Nested form inside MUI Dialog resets despite shouldUnregister = false

### ISSUE THREAD

**Issue by tombryden** [react-hook-form/react-hook-form#11113]
### Version Number

7.47.0

### Codesandbox/Expo snack

https://codesandbox.io/p/github/tombryden/RHF-Nested-Form-Bug/main

### Steps to reproduce

1. Click button 'Open Non-Nested Form Dialog'
2. Note 'Name' field set to 'Default'
3. Enter new value in the text field
4. Close dialog by clicking the background
5. Reopen the dialog by clicking 'Open Non-Nested Form Dialog' and note that the field is set to the inputted value from step 3
6. This is expected.. however, now click 'Open Nested Form Dialog' and repeat the above steps
7. Note how when reopening the dialog, the field is reset to the default value of 'Default'

Presumably the same behaviour will occur if you have a component that unmounts, and a form inside that component.

### Expected behaviour

Field value should remain set despite component unmounting.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
In your nested dialog form example, the `useForm` hook is being unmounted as it is a child component of the `Dialog`, which gets unmounted by default along with the rest of the `Dialog` `children`. As a result, the `useForm` hook cannot retain the form values if it is unmounted. Note that the `shouldUnregister` flag only determines whether the field value is retained if the input itself is unmounted, not the `useForm` hook.

Consider using the [MUI `Modal` `keepMounted` prop](https://mui.com/material-ui/react-modal/#performance) to prevent the `useForm` hook from unmounting alongside the other `Dialog` `children`, or store the form data externally and initialize the form on mount instead.

**Comment by tombryden** [comment]
Ahhh of course - thanks for the quick reply 👍
