### ISSUE TITLE
issue: useFieldArray `rules.validate` errors not updating on change

### ISSUE THREAD

**Issue by alfrsvn** [react-hook-form/react-hook-form#11125]
### Version Number

7.47.0

### Codesandbox/Expo snack

https://codesandbox.io/s/keen-water-jj9zss

### Steps to reproduce

1. Go to sandbox.
2. Click on submit to display errors.
3. Add an item.
4. See `required` error disappear correctly.
5. See `validate` error appear correctly.
6. Check the "Is active" checkbox.
7. See that `validate` error is still showing.

### Expected behaviour

`validate` error should be updated when `items` value changes, like it does for `required` error.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
rules validator for useFieldArray execute at per action level, eg `remove`

**Comment by alfrsvn** [comment]
@bluebill1049 is not executing for `update` and `replace`. Are those also out of scope?
