### ISSUE TITLE
issue: setValueAs not working as expected with reset

### ISSUE THREAD

**Issue by paulinfrancis** [react-hook-form/react-hook-form#11122]
### Version Number

`>= 7.12.1`. Initially discovered in `7.47.0`, and manually "bisected" my way back to `7.12.0` as the last known "good" version.

### Codesandbox/Expo snack

https://codesandbox.io/s/keen-gates-qztq29?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/keen-gates-qztq29?file=/src/App.tsx
2. Open console
3. `The specified value "Wed Nov 01 2023 14:18:39 GMT+0100 (Central European Standard Time)" does not conform to the required format, "yyyy-MM-dd"`.
4. Downgrade react hook form to v7.12.0 and observe that it no longer prints the error, and the correct value is set in the UI.

Forked the example from: https://github.com/react-hook-form/react-hook-form/issues/5627

### Expected behaviour

The transformed value is displayed in the UI, and no error messages are printed to the console.

### Relevant log output

```shell
The specified value "Wed Nov 01 2023 14:18:39 GMT+0100 (Central European Standard Time)" does not conform to the required format, "yyyy-MM-dd".
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I would suggest to follow the same in this exapmple: https://github.com/react-hook-form/react-hook-form/issues/6090

**Comment by paulinfrancis** [comment]
Thanks for the reply @bluebill1049!

To clarify, I'm not trying to supply a `Date` object. It's a string, but the format from the backend (`2023-11-01T20:37:03.7562555+00:00`) is not what the `date`/`datetime-local` inputs are expecting.

To remedy this, my initial idea was to use `setValueAs: formatISO8601ToDate,` in order to normalize the data.

```
const formatISO8601ToDateString = (iso1601: string | undefined | null) => {
    // 2023-11-01T20:37:03.7562555+00:00
    if (iso1601 && typeof iso1601 === 'string') {
        return format(parseISO(iso1601), 'dd-MM-yyyy'); // yields 2023-11-01
    }
    return '';
};
```

The obvious thing to do is to is to fix the data from the backend prior to feeding it to the form via `reset`, but I'm building a dynamic form based on JSON schema, so without parsing the schema, I can't determine if the properties in the payload are number, string, or string representing a date. Ideally I would like to be able to say in `register` for a a given input; format the string in a way that makes sense for `type="date"`.  Hope that makes sense, and sheds more light on what I am trying to achieve.

**Comment by bluebill1049** [comment]
setValueAs or setValue** will not update the input. it's intentional and fixes the existing bug.  please refer tot he test case which I posted above, `setValueAs` do not update input value, only produce value for submission data.

**Comment by paulinfrancis** [comment]
The tests themselves are not to be mistaken, and the behaviour clearly does what the tests assert.

My current understanding is that to get it to render correctly, my only option will be to fix the data that is fed into defaultData/reset.

This clearly isn't a bug, as I am trying to use the API incorrectly, but could an inbound transformation function be something to consider, as a counterpart for `setValueAs` that is used on submission?

**Comment by bluebill1049** [comment]
> This clearly isn't a bug, as I am trying to use the API incorrectly, but could an inbound transformation function be something to consider, as a counterpart for setValueAs that is used for submission data?

yea, we could consider that. The underneath implement would be pretty much a function wrap on top of `reset` API.

```
reset(transform(...))

useForm({
  defaultValues: transform(...)
})
```

In fact, you can probably extend the `useForm`.
