### ISSUE TITLE
useFieldArray non resetting errors

### ISSUE THREAD

**Issue by violabg** [react-hook-form/react-hook-form#1113]
Hi, I found a bug on useFieldArray related to errors.

basically if you track errors in an item of useFieldArray, even when the field is valid, the errors object it's not empty, but has an empty object at errors.test[1] level.
Only if I click the submit button the errors object is empty

this means that formState.isValid is never valid unless you click the submit button.

This is a problem for me because I want to use formState.isValid to disable/enable the submit button, so if it is always disable due to  formState.isValid been always false, I can't click it.

**To Reproduce**
https://codesandbox.io/s/react-hook-form-usefieldarray-tdehq

there are some console.log to demonstrate the problem.

**Comment by bluebill1049** [comment]
let's track in this ticket: https://github.com/react-hook-form/react-hook-form/issues/1097
