### ISSUE TITLE
issue: disabled field value is reset

### ISSUE THREAD

**Issue by glekner** [react-hook-form/react-hook-form#11145]
### Version Number

7.48.2

### Codesandbox/Expo snack

no need

### Steps to reproduce

1. Fill field with value
2. Disable `useForm`
3. field value is reset to undefined

### Expected behaviour

the value of field should remain.

here is the code that deletes it if i'm not mistaken - https://github.com/react-hook-form/react-hook-form/blob/cf714807c9d0d11966267959037bc91e93d212ee/src/logic/createFormControl.ts#L963-L967

Can I ask why is this happening?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Followed the web standard: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled

**Comment by glekner** [comment]
@bluebill1049 can we have a choice? this could be easily customizable with a prop. would happily make a PR

**Comment by lmexo** [comment]
@bluebill1049 I see this is standard but nevertheless I agree with @glekner. There are usecases where I want the users to show some data which is not modifiable but necessary for context. So why not just adding a flag to keep the data, if needed?

**Comment by Moshyfawn** [comment]
> There are usecases where I want the users to show some data which is not modifiable but necessary for context.

In this case, you can use a semantically correct HTML [`readOnly` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly).
