### ISSUE TITLE
issue: Controller's name type is not auto completing

### ISSUE THREAD

**Issue by Darren120** [react-hook-form/react-hook-form#11147]
### Version Number

7.46.2

### Codesandbox/Expo snack

https://codesandbox.io/s/beautiful-tharp-yyxktj?file=/src/App.tsx

### Steps to reproduce

1. Type in name
2. String interpolate array index
3. age doesn't give auto complete
4. but ts check is still working. just not having auto complete

I remember this was possible a few years back unless im going insane.

### Expected behaviour

"person.${index}. => age}
age should pop up as auto complete

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
work as expected with TS.

**Comment by Darren120** [comment]
> work as expected with TS.

are you saying you're getting the autocomplete? or its not a feature?
