### ISSUE TITLE
Validation in sub-components

### ISSUE THREAD

**Issue by thurfir** [react-hook-form/react-hook-form#1114]
Hi. To split a complex React + Redux component into smaller blocks and keep the validation working, I decided to create a root component, with a `<form>` + `const { register, handleSubmit } = useForm();` and to split the form's content into multiple sub-components. I'll then pass the `register` method to the sub-components to register my inputs.

This works if my sub-components are pure methods, however as soon as I connect my sub-component to Redux using connect(), the validation becomes erratic: the 1st submit validate, the 2nd fails, the 3th validate and so on. I'm guessing there is a by-ref issue with the hook's method?

```
const RootComponent = () => {
    const { register, handleSubmit, errors } = useForm();
    return (
               <form onSubmit={handleSubmit(onSubmit)}
                    <MySubComponent register={register} />
               </form>
    );
}
```

Works:
```
const MySubComponent = (props) => {
    const inputRef = props.register({ required: { value: true, message: "This is required" } });
    return (
        <Fragment>
            <input id="AAA" type="radio" name="testName" value="AAA" ref={inputRef} />
            <input id="BBB" type="radio" name="testName" value="BBB" ref={inputRef} />
        </Fragment>
    );
};
```

Fails every 2 submits:
```
const MySubComponent = connect()((props) => {
    const inputRef = props.register({ required: { value: true, message: "This is required" } });
    return (
        <Fragment>
            <input id="AAA" type="radio" name="testName" value="AAA" ref={inputRef} />
            <input id="BBB" type="radio" name="testName" value="BBB" ref={inputRef} />
        </Fragment>
    );
});
```

**Comment by bluebill1049** [comment]
can you provide a simple codesandbox?

**Comment by bluebill1049** [comment]
will reopen once CSB supplied
