### ISSUE TITLE
React-hook-form can not work well with uglify 

### ISSUE THREAD

**Issue by chriswang-** [react-hook-form/react-hook-form#1115]
React-hook-form can not work well with uglify ...
It seems uglify can not find the ES5 version. 
But others npm packages work well.

**Comment by bluebill1049** [comment]
This is the first time we hear such issue. I don't think this is related to the lib itself rather than the build pipeline.

**Comment by chriswang-** [comment]
Sorry, Maybe  It is not a problem, I am new front-end, 
I just switch the source code to :
import { useForm } from 'react-hook-form/dist/react-hook-form.ie11';

everything is ok now. But the import style is very strange compare to other libs. I dont known where is the matter that I am missing , Is it ok about this kinds of import ?

**Comment by bluebill1049** [comment]
that's correct.

**Comment by mattjis** [comment]
Doesn't work for me either! Unless importing like so: `import { useForm } from 'react-hook-form/dist/index.ie11'`.

**Comment by bluebill1049** [comment]
> Doesn't work for me either! Unless importing like so: `import { useForm } from 'react-hook-form/dist/index.ie11'`.

only ie version is es5
