### ISSUE TITLE
numbers provided as strings in watch and getValues

### ISSUE THREAD

**Issue by alaindresse** [react-hook-form/react-hook-form#1116]
**Describe the bug**
Watched fields and fields returned by getValues do not have the types from FormData. When there is a validation with yup, the submitted values do have the right types.

**To Reproduce**
1. Create a form with a text and a number field. Include some simple yup validation scheme.
2. In the onSubmit, log the values submitted, the values extracted using getValues, the values watched
4. See that the number field is indeed a number in the submitted form, a string in the other cases:
```
{
 "submitted": {
  "age": 52,
  "firstName": "Alain"
 },
 "watched": {
  "firstName": "Alain",
  "age": "52"
 },
 "values": {
  "firstName": "Alain",
  "age": "52"
 }
} 
```
**Codesandbox link**
https://codesandbox.io/s/react-hook-form-validationschema-8pxz9?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
submitted, values and watched to have the same types

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser : chrome
 - Version: 80.0.3987.122 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
none

**Comment by bluebill1049** [comment]
This is expected behaviour. Input value will be all get as `string` in react-hook-form.  we are not calling `valueAsNumber` in our code base to avoid `NaN` and other related issue.

**Comment by bluebill1049** [comment]
going to close this issue, feel free to follow up with more questions.

**Comment by D1plo1d** [comment]
@bluebill1049 On first glance I wonder if `type=number` inputs could be parsed by default without much risk of NAN.  If a `type=number` input cannot be misset by the user in the modern browser UIs the risk is only of an input being programmatically set to an invalid value. That feels like an edge case from my perspective atm but perhaps I'm not seeing the full picture.

The issue as I see it is that this causes onSubmit's to be less DRY. Right now my onSubmits look like:

```js
  const onSubmit = async (values) => {
    const parsedValues = {
      ...values,
      height: parseFloat(values.height),
      numberOfLegs: parseInt(values.numberOfLegs),
      homePlanetID: parseInt(values.homePlanetID),
    }
   // ...
}
```

Is there a possibility of a DRYer default for `type=number` in the future?

**Comment by bluebill1049** [comment]
hey @D1plo1d not at this stage, there is no such thing as input return `number` type, it's almost a misconception with the local state when using React. it only works with `valueAsNumbe`. https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement
