### ISSUE TITLE
Set select value to first option

### ISSUE THREAD

**Issue by antonbehaeghe** [react-hook-form/react-hook-form#1117]
Hey, I'm building a custom select component and I need to set the value to the first option on mount.
https://codesandbox.io/s/react-hook-fom-formcontext-rerender-scskb

When using a useEffect for this it causes an infinite loop because the options array updates every render. And the state change rerenders everything because it is in a FormContext.

How should I properly do this?

**Comment by bluebill1049** [comment]
That's because your options are not `memo`, why not use Controller.

**Comment by bluebill1049** [comment]
Also general questions please consider asking in our spectrum channel.

**Comment by antonbehaeghe** [comment]
I'm sorry if this isn't the correct platform for questions, I will move this to Spectrum then :)

**Comment by bluebill1049** [comment]
thanks @antonbehaeghe here is more for issues/bugs.
