### ISSUE TITLE
issue: reset form keeps fields with undefined, results in wrong isDirty

### ISSUE THREAD

**Issue by Hatzl** [react-hook-form/react-hook-form#11176]
### Version Number

7.48.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-controller-forked-3z9s5k?file=/src/index.js

### Steps to reproduce

1. Input text in textbox
2. Click on 'reset''
3. See isDirty is still true and form values are different to initial

Changing version to 7.48.1 or 8.0.0-alpha will result in the expected behavior.

### Expected behaviour

is dirty should be false and values should be "{}".

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrei-shoreline** [comment]
We experience a similar issue with all versions `>=7.48.0`. Version `7.47.0` works as expected

**Comment by Hatzl** [comment]
Maybe you can explain your "similar" issue or create a code sandbox?  My issue is only in 7.48.2. You can try on my codesandbox. Just change the version on the left side.

**Comment by bluebill1049** [comment]
please support a `defaultValues: {}` this is pretty much the same `undefined`.

expected:

```
defaultValues: {
  firstName: ''
}
```

**Comment by dingram94** [comment]
Does not solve the problem the form is dirty anyway
