### ISSUE TITLE
inputs with default values take a second or 2 to populate

### ISSUE THREAD

**Issue by Jared-Dahlke** [react-hook-form/react-hook-form#11185]
### Version Number

latest

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/condescending-bessie-vkhf9d?file=%2Fapp%2Fabout%2FForm.tsx%3A45%2C1

### Steps to reproduce

start from the index page, click on the 'about' link, notice how when the form loads it takes a second or 2 for the default values to populate.

### Expected behaviour

default values should be populated almost instantly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jared-Dahlke** [comment]
here is also a video of my app doing it

https://github.com/react-hook-form/react-hook-form/assets/32936978/d5e3ff6f-1cc4-4edc-83fb-4a7b69ee3466

**Comment by Moshyfawn** [comment]
It seems that the JS hydration process is causing the delay as the `MyForm` component runs on the client. Please correct me if I am wrong, @kotarella1110.

Depending on how complex your form is, @Jared-Dahlke, I suggest setting default values for the fields on the inputs. This will render the form with default values already set, allowing the user to see them right away.

Here's [an example codesandbox](https://codesandbox.io/p/sandbox/cool-resonance-97wqr4?file=%2Fapp%2Fabout%2FForm.tsx%3A45%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clotg24qu000c3b6f7yp3sv08%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clotg24qu00043b6fy0blydo0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clotg24qu00093b6f4vgs2mcu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clotg24qu000b3b6fofh55yt6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clotg24qu00043b6fy0blydo0%2522%253A%257B%2522id%2522%253A%2522clotg24qu00043b6fy0blydo0%2522%252C%2522activeTabId%2522%253A%2522clotg24qu00033b6fyepgtysu%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clotg24qu00033b6fyepgtysu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Fabout%252FForm.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Fabout%252Fpage.tsx%2522%252C%2522id%2522%253A%2522clotg57b300pf3b6f1f1o3c8s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clotg8oa9016i3b6fnl5cjo3i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522id%2522%253A%2522clotgag2l01v73b6fukisgtz1%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clotg24qu000b3b6fofh55yt6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clotg24qu000a3b6ff0x53pm7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252Fabout%2522%257D%255D%252C%2522id%2522%253A%2522clotg24qu000b3b6fofh55yt6%2522%252C%2522activeTabId%2522%253A%2522clotg24qu000a3b6ff0x53pm7%2522%257D%252C%2522clotg24qu00093b6f4vgs2mcu%2522%253A%257B%2522id%2522%253A%2522clotg24qu00093b6f4vgs2mcu%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clotg24qu00063b6flmr8s5rm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%252C%257B%2522id%2522%253A%2522clotg24qu00083b6fhofiabus%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522lint%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clotg96iv01k93b6f3rva1nnm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clotg96iv01k93b6f3rva1nnm%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report. You are right @Moshyfawn, your form component will need to be mounted first, and then react hook form will be to populated in the client side. 

```
  React.useEffect(() => {
    console.log('ready')
  }, [])
```

you can test it out with uesEffect at your app level. If you want your input value to be rendered from the server, then you can put inline defaultValue for your input.

**Comment by Jared-Dahlke** [comment]
this works. thank you!
