### ISSUE TITLE
Default values take a second or 2 to fill input

### ISSUE THREAD

**Issue by Jared-Dahlke** [react-hook-form/react-hook-form#11182]
This is pretty self explanatory. This is the only sketchy thing in my app. Is there some way to know when it's filled ? Or do I just need to set a loading screen for 2 seconds on page load ?

**Comment by Moshyfawn** [comment]
Can you elaborate on what is the expected behavior, feature? Or are you experiencing an unwanted delay, then we need a reproduction sandbox.

**Comment by Moshyfawn** [comment]
Duplicate of #11185
