### ISSUE TITLE
Error Validation Message Not Running well with Controller rules

### ISSUE THREAD

**Issue by gongallego** [react-hook-form/react-hook-form#1118]
**Describe the bug**
I want to validate a TextInput with a Controller and a function, the error happens but the message is "" so I can't display it in my app.

**To Reproduce**
A Valid CIF is: F3914998D
https://snack.expo.io/@gongalo/controllerinputrole

**Expected behavior**
I want to see a message that describes the validation error, 

**Smartphone:**
 - Android 7.0

**Comment by bluebill1049** [comment]
please read the documentation on `validate` function under the `register`.

https://react-hook-form.com/api#register

**Comment by gongallego** [comment]
But this is for an Input, not for a Controller, the Controller needs to be registered too?

**Comment by bluebill1049** [comment]
no.

```
rules={{
  required: 'Error en el CIF',
  validate: { value: validCIF}, // look up on how validte function works
}}
```

**Comment by gongallego** [comment]
Yes, but the error message is = "" instead of "Error en el CIF"

**Comment by bluebill1049** [comment]
<img width="1038" alt="Screen Shot 2020-02-28 at 11 07 14 pm" src="https://user-images.githubusercontent.com/10513364/75547477-118cad80-5a7f-11ea-9c57-e7507886082e.png">

please consider ask questions at our spectrum channel, issues for report bugs/issues
