### ISSUE TITLE
issue: `useFormState` subscribes to root form state instead selected fields

### ISSUE THREAD

**Issue by markkkkas** [react-hook-form/react-hook-form#11189]
### Version Number

7.48.2

### Codesandbox/Expo snack

https://codesandbox.io/s/intelligent-monad-lydpcl?file=/src/App.js

### Steps to reproduce

1. Click on 'Switch tab' button
2. Click again on 'Switch tab' button
3. Type any text into 'First Name' or 'Last Name'
4. Click on 'Switch tab' button
5. See console

### Expected behaviour

`isDirty` should be false, because `useFormState` is subscribed only to `groups.${i}.selected` fields

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`isDirty` will always check the entire form.

**Comment by markkkkas** [comment]
@bluebill1049 Thanks for quick reply, what is the purpose of subscribing to `name` then? I tried to destructure `dirtyFields`, unfortunately i also see that `firstName` or `lastName` is in the object as well.

**Comment by bluebill1049** [comment]
for individual fields state, `errors`, `dirtyFields`, `touchedFields`and getting notified isDirty at isolated component level instead global level.

**Comment by markkkkas** [comment]
@bluebill1049 So if i get all `dirtyFields` instead subscribed ones (with `name` property) is expected?

**Comment by bluebill1049** [comment]
> @bluebill1049 So if i get all `dirtyFields` instead subscribed ones (with `name` property) is expected?

yes

**Comment by markkkkas** [comment]
@bluebill1049 Thanks!
