### ISSUE TITLE
formState.isValid is always true

### ISSUE THREAD

**Issue by lazyd3v** [react-hook-form/react-hook-form#1119]
**Describe the bug**
`formState.isValid` is not being updated on field change if mode='onChange', Context, Controller and custom onChange event handler are used. If I remove custom onChange from Controller and pass onChange directly in the input, everything works fine

**Codesandbox link**
 https://codesandbox.io/s/xenodochial-silence-wy7p3

**Expected behavior**
When input value is changed from `test` to `t`, it should display:
1. `formState.isValid` is changed from true to false
2. `Object.keys(errors).length` is changed from 0 to 1
3. `value` is `t`

**Actual behaviour**
1. `formState.isValid` is always false
2. `Object.keys(errors).length` is always 0
3. `value` is `t`

**Comment by bluebill1049** [comment]
found issue:
```
onChange={([value]) => {
  return value[0];
}}
```
make sure you return string instead of array. 👍

**Comment by lazyd3v** [comment]
Aha, okay, thanks! I thought arguments in Controller's onChange doesn't wrap arguments in additional array. For example, if MyInput called onChange like `onChange({ value: 'foo' }, { bar: 'baz'})`, Controller's onChange would receive `{ value: 'foo' }` as first argument and `{ bar: 'baz' }` as second, but now onChange receives these arguments wrapped in array, so array destructuring `([ value ]) =>` destructure passed args, not the argument itself

I think it would be nice to add documentation regarding this and probably make fix in types. What do you think? I would love to make a PR

**Comment by lazyd3v** [comment]
From my point of view, it would be much nicer to pass arguments as arguments, without wrapping them into array, but it will break compatibility with older versions. So that's why I suggest to add documentation regarding this

**Comment by bluebill1049** [comment]
> From my point of view, it would be much nicer to pass arguments as arguments, without wrapping them into array, but it will break compatibility with older versions. So that's why I suggest to add documentation regarding this

That's was a mistake that I did in v4, which should have passed `arguments`. I wouldn't change this for v4 consider it's a breaking change, let's leave it to v5.

**Comment by bluebill1049** [comment]
also FYI for `arguments`, you will still need to use it as arguments[0]
