### ISSUE TITLE
Getting isDirty true after reset in last version

### ISSUE THREAD

**Issue by wilav-dev** [react-hook-form/react-hook-form#11192]
### Version Number

7.48.2

### Codesandbox/Expo snack

https://codesandbox.io/s/goofy-architecture-rcswdh?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/goofy-architecture-rcswdh?file=/src/App.js
2. Open console
3. Fill first name and submit (it calls reset)
4. See log, 1st log isDirty is false and 2nd log is true

It was working fine on v7.47.0

![Captura de pantalla 2023-11-14 a la(s) 14 00 46](https://github.com/react-hook-form/react-hook-form/assets/71793326/b51f9a73-1bc3-42a5-9e34-0266400cf28b)

### Expected behaviour

isDirty must be false after reset

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
You need to provide [non-`undefined` default values](https://react-hook-form.com/docs/useform#defaultValues:~:text=You%20should%20avoid%20providing%20undefined%20as%20a%20default%20value) in order for RHF to "calculate" the `isDirty` state.

```diff
- useForm()
+ useForm({ firstName: "" })

- reset()
+ reset({ firstName: "" })
```

A working [codesandbox](https://codesandbox.io/s/zen-tree-gx2v66?file=%2Fsrc%2FApp.js).

**Comment by wilav-dev** [comment]
thank you for your answer but my main concern is that my issue started on v7.48.2. It has been working up to v7.48.1.
Here is the same example but using 7.48.1:
https://codesandbox.io/s/festive-sara-634p4k

**Comment by wilav-dev** [comment]
@Moshyfawn any idea?

**Comment by joskaja** [comment]
Same issue on our side. It is working fine on version 7.48.1, but on 7.48.2 isDirty is kept true after form submit (without even calling reset). Also the dirtyFields is empty.

**Comment by wilav-dev** [comment]
Hello @bluebill1049 . Could you please explain me why it has been working until 7.48.1? Why reset need an object with empty values since 7.48.2? If possible I want to avoid declaring an object just for reset. Thank you!

**Comment by intayush** [comment]
@wilav-dev I've been facing the same issue, do you have some workaround/fix for this?

**Comment by wilav-dev** [comment]
No, the owner @bluebill1049 says that it's working as expected but it was not working this ways until the last version. my solution is using v7.48.1 and don't update to new versions

**Comment by andokai** [comment]
My solution has been to use `const isDirty = Object.keys(dirtyFields).length > 0;`.

**Comment by villesau** [comment]
I'm also puzzled what is the "works as designed" here. `reset({}, { keepValues: true, keepDirty: false });` resets isDirty for us from `7.48.2` onwards. I think isDirty should definitely become false with that?

**Comment by villesau** [comment]
Also, explicitly setting the default values does not help in our case. @bluebill1049 I think this issue is valid from `7.48.2` onwards and should be reopened.
