### ISSUE TITLE
Treat null as null instead of string "null"

### ISSUE THREAD

**Issue by AslanTaheri** [react-hook-form/react-hook-form#11211]
**Problem:** When populating the fields either with reset ( ) or using defaultValues with fetched data, if any value is null, React Hook Form treats it as string value 'null' and populates the word "null" in those fields.

**Describe the solution you'd like**
Null values be treated as null.

**Describe alternatives you've considered**
We are currently filtering out the null values before passing them on to RHF.

**Additional context**
![image](https://github.com/react-hook-form/react-hook-form/assets/123320141/06ca4541-6447-4a5a-8782-46556e25290b)

**Comment by Moshyfawn** [comment]
This doesn't seem right. Can you, please, create a minimal reproduction codesandbox with the issue you're having?

**Comment by bluebill1049** [comment]
input text will always be string, if you type "null" it will not translate to `null`
