### ISSUE TITLE
issue: when fieldArray has own rules the focus on append does not work

### ISSUE THREAD

**Issue by terragady** [react-hook-form/react-hook-form#11218]
### Version Number

7.48.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/calc-forked-yslhrt

### Steps to reproduce

https://codesandbox.io/p/sandbox/calc-forked-yslhrt

basically write rules for fieldArray destroy focus action when appending new item

I have check and it works with some previous versions but not with newest version.

### Expected behaviour

focus input when append

I need to validate that array has at least 1 element and I do not want to use external resolvers as this will just complicate types etc.

**Comment by bluebill1049** [comment]
works for me with the latest: https://codesandbox.io/p/sandbox/react-hook-form-usefieldarray-forked-gfw2kw?file=%2Fsrc%2Fstyles.css

**Comment by Moshyfawn** [comment]
It is the 'useFieldArray' `rules` option, @bluebill1049. Here's [a codesandbox](https://codesandbox.io/p/sandbox/react-hook-form-usefieldarray-forked-gfw2kw?file=%2Fsrc%2Fstyles.css&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpa9hepv00083b6f159mhsup%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpa9hepv00043b6fgwx5mqpl%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpa9hepv00053b6f5dwsd1t7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpa9hepv00073b6f9vjc1wky%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpa9hepv00043b6fgwx5mqpl%2522%253A%257B%2522id%2522%253A%2522clpa9hepv00043b6fgwx5mqpl%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpa9hepv00073b6f9vjc1wky%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpa9hepv00063b6flgh7x2x7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clpa9hepv00073b6f9vjc1wky%2522%252C%2522activeTabId%2522%253A%2522clpa9hepv00063b6flgh7x2x7%2522%257D%252C%2522clpa9hepv00053b6f5dwsd1t7%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpa9hepv00053b6f5dwsd1t7%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) with a field array that has the `rules` set up. Adding another field array item _(click 'Append')_ works, but the focus isn't not set on the first input of the new field array item.

**Comment by bluebill1049** [comment]
Got it, will take a look at it.

**Comment by Moshyfawn** [comment]
The new `iterateFieldsByAction` logic seems to overlook the field array's use-case, resulting in only the field name being returned, such as `firstName`, instead of the field array item name, such as `people.1.firstName`. Unfortunately, couldn't get both the field array and the rest of the places where this function's now used to work 😔
