### ISSUE TITLE
Controlled components do not get auto-focused on submit

### ISSUE THREAD

**Issue by wrporter** [react-hook-form/react-hook-form#1121]
**Describe the bug**
When using uncontrolled components, `handleSubmit` focuses the first invalid field in the form. Example screenshot:

![uncontrolled](https://user-images.githubusercontent.com/2702937/75596804-5993dc00-5a4f-11ea-88e9-f2fafd9b2c02.gif)

However, for controlled components using `<Controller>` the fields do not get focused. Example screenshot:

![controlled](https://user-images.githubusercontent.com/2702937/75596851-8811b700-5a4f-11ea-8624-2bc399184c00.gif)

**To Reproduce**
1. Use a controlled component with `<Controller>`
2. Trigger `handleSubmit`

**Codesandbox link**
https://codesandbox.io/s/beautiful-worker-22hi3

**Expected behavior**
Controlled components receive focus in the same way uncontrolled components do.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Browser Chrome
 - Version 80.0.3987.116 (Official Build) (64-bit)

**Comment by xiaoyu-tamu** [comment]
![image](https://user-images.githubusercontent.com/33362998/75599109-1ba2b200-5a67-11ea-8651-d603458e53bb.png)

Read the doc

**Comment by bluebill1049** [comment]
Thank you @xiaoyu-tamu

**Comment by wrporter** [comment]
@xiaoyu-tamu @bluebill1049 I'm sorry, the documentation alone is not completely helpful for this case. I cannot seem to come up with a case that works properly with React Hook Form in the Codesandbox I provided.

**Comment by bluebill1049** [comment]
@wrporter to be honest, it couldn't be clearer IMO, but feel free to improve the doc as it's open sourced as well.

> Note: Only **registered fields with a ref** will work. Manually registered inputs won't work. eg: register({ name: 'test' }) // doesn't work

Some good news for you, next update will support Controller as well. https://twitter.com/bluebill1049/status/1244429306639441924

**Comment by wrporter** [comment]
@bluebill1049 Ah, so this just is not supported at all with the `Controller` or "controlled" components at the moment? That would be useful to put in the docs, but if it's coming out, maybe that does not need to be added at all. Glad to see progress there!

**Comment by bluebill1049** [comment]
> Ah, so this just is not supported at all with the Controller or "controlled" components at the moment?

That's not precise as well, because you can do it yourself at useEffect as long as you get to hold of the errors and ref (controlled input).

```
useEffect(() => {
  if (errors.text) {
    this.input.ref.focus();
  }
}, [errors])
```

anyway, let's looking forward for the next update.
