### ISSUE TITLE
Handle onFormSubmit outside form component

### ISSUE THREAD

**Issue by ayepRahman** [react-hook-form/react-hook-form#1122]
Hi there, is there a way to handle form submission which button is outside the form component?

**Comment by xiaoyu-tamu** [comment]
You should try to search issues first...

**Comment by bluebill1049** [comment]
Please consider ask general question at our spectrum channel. Similar question is been asked multiple times. 


handlesubmit returns a callback, so just have to invoke it 

handleSumbit()()

**Comment by bluebill1049** [comment]
i will update the doc to reflect this as well, so we can avoid this get questioned as well 👍

**Comment by bluebill1049** [comment]
<img width="852" alt="Screen Shot 2020-02-29 at 6 05 43 pm" src="https://user-images.githubusercontent.com/10513364/75602953-22403080-5b1e-11ea-906e-6f0a995e8bdb.png">

let me know if this explains better.
