### ISSUE TITLE
issue: Root error is set only when submit button click (even on onBlur mode)

### ISSUE THREAD

**Issue by hadson172** [react-hook-form/react-hook-form#11220]
### Version Number

7.4.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/cool-frost-hvgwwk?file=%2Fsrc%2FApp.tsx%3A37%2C6

### Steps to reproduce

1. Go to https://codesandbox.io/p/sandbox/cool-frost-hvgwwk?file=%2Fsrc%2FApp.tsx%3A37%2C6
2. Type string in first field
3. Type string in second field
4. Check console, it seems that console.log present in .refine validator is triggered, (the form has state isValid=false) but validation message set to ['start'] is not there. Why?

### Expected behaviour

So when i have 
- mode: "`onBlur`"
- revalidateMode: "`onBlur`"

I would expect that errors contains error message from refine. Any ideas?

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Expected when it's not associated an actual field/input.

**Comment by hadson172** [comment]
Hi @bluebill1049 you mean this works as design ?
Why then the error is present when user clicks submit?

We have this use-case to display differently field errors and cross-fields error. The idea was to use it on the top object but it seems it doesnt work. Any advices how to approach such problem?

Thanks
