### ISSUE TITLE
issue: isDirty is not set on first action

### ISSUE THREAD

**Issue by maangs** [react-hook-form/react-hook-form#11225]
### Version Number

7.48.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/nervous-keldysh-t4z2m7

### Steps to reproduce

1. Go to https://codesandbox.io/p/sandbox/nervous-keldysh-t4z2m7
2. Open Dev tools - Console
3. Click on **one** checkbox
4. Click on Save
6. First log prints isDirty as false

### Expected behaviour

Expected isDirty to be true.

Workarounds:
Destruct formState makes it work as expected.

And if I print the value directly on the screen isDirty will have the correct value.
  `  <pre>{JSON.stringify(methods.formState.isDirty)}</pre>`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please debug this at your end there is not specific logic here, just a deep equal again your defaults value with form values.
