### ISSUE TITLE
useFieldArray doesn't remove radio button correctly

### ISSUE THREAD

**Issue by nari0shota** [react-hook-form/react-hook-form#1123]
I'm using useFieldArray to render radio buttons. It needs double click to remove radio button. I can't figure out how to remove radio button by single click.

Is there something wrong with my code?

**To Reproduce**
1. Open Codesandbox link
2. Click Delete Button(any button is ok)
3. Radio button is removed
4. Click Delete Button again (any button is ok)
5. Radio button is not removed
6. Click Delete Button again (any button is ok)
7. Radio button is removed 

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-3gd61

**Comment by bluebill1049** [comment]
Thanks for report this issue: https://codesandbox.io/s/react-hook-form-usefieldarray-r8vbh
