### ISSUE TITLE
 [issue: TextInput]: When I parsed to Number it trails zeros from the end

### ISSUE THREAD

**Issue by niralivasoya** [react-hook-form/react-hook-form#11232]
### Version Number

7.45.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/textinputnumber-cllg24?file=%2Fsrc%2FApp.js%3A14%2C1

### Steps to reproduce

This is my common reusable controller component for TextField. Here I want to parse values to Numbers, So Instead of parsing during data submission, I am parsing it here on the onChange function. 

This is my full code in Typescript:

```
interface TextInputProps<T extends FieldValues> extends FormControlProps {
    control: Control<T>;
    label: string;
    name: Path<T>;
    errors?: FieldErrors<T>;
    rows?: number;
    placeholder?: string;
    type?: string;
    defaultValue?: PathValue<T, Path<T>>;
    required?: boolean;
    sx?: object;
    disabled?: boolean;
    min?: number;
    max?: number;
    className?: string;
    customOnChangeFunction?: (value: any) => void;
    readOnly?: boolean;
    rules?: RegisterOptions;
    valueAsNumber?: boolean;
    helperText?: string;
    customError?: any;
}

const TextInput = <T extends FieldValues>({
    control,
    errors,
    label,
    name,
    rows = 0,
    type = 'text',
    sx,
    required,
    disabled,
    defaultValue,
    min,
    max,
    customOnChangeFunction,
    rules,
    className,
    readOnly = false,
    valueAsNumber,
    helperText,
    customError,
    ...rest
}: TextInputProps<T>) => {
    const props = rows ? { rows, multiline: true } : {};

    // Extract the error message for the specific field
    const fieldError = errors && errors[name];

    const [showPassword, setShowPassword] = useState(false);

    // Function to toggle the visibility of the password
    const handleClickShowPassword = () => {
        setShowPassword(!showPassword);
    };

    // Set min and max values for number type
    const inputProps: Record<string, number> = {};
    if (type === 'number') {
        if (min !== undefined) {
            inputProps.min = min;
        }
        if (max !== undefined) {
            inputProps.max = max;
        }
    }

    return (
        <FormControl fullWidth sx={{ ...sx }} className={className}>
            <Controller
                name={name}
                control={control}
                {...rest}
                rules={rules}
                defaultValue={defaultValue}
                render={({ field: { value, onChange, ref } }) => {
                    const handleChange = (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
                        if (customOnChangeFunction) {
                            customOnChangeFunction(event.target.value);
                        }
                        const inputValue = event.target.value;

                        if (valueAsNumber) {
                            // Handled NaN and empty string
                            if (inputValue === '') {
                                onChange('');
                            } else if (isNaN(Number(inputValue))) {
                                onChange('');
                            } else {
                                onChange(Number(inputValue));
                            }
                        } else {
                            onChange(event as ChangeEvent<HTMLInputElement>);
                        }
                    };

                    return (
                        <TextField
                            inputRef={ref}
                            {...props}
                            type={type === 'password' ? (showPassword ? 'text' : 'password') : type}
                            value={value ?? ''}
                            label={label}
                            onChange={handleChange}
                            placeholder={label}
                            error={Boolean(fieldError) || Boolean(customError)}
                            required={required}
                            disabled={disabled}
                            inputProps={inputProps}
                            // Add an icon button to the end of the text field
                            InputProps={{
                                endAdornment: type === 'password' && (
                                    <InputAdornment position='end'>
                                        <IconButton
                                            aria-label='toggle password visibility'
                                            onClick={handleClickShowPassword}
                                            edge='end'
                                        >
                                            {showPassword ? <VisibilityOff /> : <Visibility />}
                                        </IconButton>
                                    </InputAdornment>
                                ),
                                readOnly: readOnly,
                            }}
                        />
                    );
                }}
            />
            {(fieldError || customError) && (
                <FormHelperText sx={{ color: '#E31A1C', marginLeft: 0 }}>
                    {fieldError?.message as string} {customError?.message}
                </FormHelperText>
            )}
        </FormControl>
    );
};

export default TextInput;
```

### Expected behaviour

I passed one prop from the parent valueAsNumber, and based on it if it is true then parse it to Number otherwise consider it as Text. The issue here is that when I write something like `90.90000` it trails all the zeros and only sets the `90.9` as my field value. One more thing if I add any number after the zeroes like `90.900009`, then it sets the full number.

How can I fix it? Any suggestion or improvement in this? 

### Relevant log output

```shell
If the Input is 90.90000 then the output should be the same in number type. But currently, I get 90.9.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
The behaviour you're seeing is how [the `valueAsNumber` method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#valueasnumber) works due to how the WHATWG specs define [the valid floating-point number](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#valid-floating-point-number); RHF merely calls the Web API and doesn't alter any behaviours.

You can choose not to utilize the `valueAsNumber` method (https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#valueasnumber) and instead parse your input value utilizing [the `parseFloat` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat), or choose not to parse the string to a number altogether.

**Comment by niralivasoya** [comment]
Thank you @Moshyfawn, here I tried with the [parseFloat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat) and you can see here, that I typed 4.900 and it removes all the zeros at the end, I want all trailing zeros when I parse it.

<img width="813" alt="image" src="https://github.com/react-hook-form/react-hook-form/assets/32123446/723ba7ed-8f57-420b-ac12-79d73631152e">

**Comment by Moshyfawn** [comment]
> Thank you @Moshyfawn, here I tried with the [parseFloat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat) and you can see here, that I typed 4.900 and it removes all the zeros at the end. Can I have trailing zeros when I parse it?
> 
> <img alt="image" width="813" src="https://private-user-images.githubusercontent.com/32123446/285626123-723ba7ed-8f57-420b-ac12-79d73631152e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5Njc1NDQsIm5iZiI6MTcwMDk2NzI0NCwicGF0aCI6Ii8zMjEyMzQ0Ni8yODU2MjYxMjMtNzIzYmE3ZWQtOGY1Ny00MjBiLWFjMTItNzlkNzM2MzExNTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDAyNTQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZjk0NjkyZmFmNDUwNTM2ODYyNTE3MmI0NTQxNjdlZWM5YTZkMmNlYTBjNTlhZWZjYmM5YTA4NzdjODIzODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lk7_r-O1tYtXwVH9gQ881SIt7MVQtj7MSFgm03e9fLI">

You can utilize [the `toFixed` `Number` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed) to set the number of digits after the decimal point.

```js
parseFloat(event.target.value).toFixed(2)
```

However, keeping floating point numbers as `string` is generally the best approach when working with JS.
