### ISSUE TITLE
issue: when defaultValues is provided by an async function and shouldUnregister is true then defaultValues gets set to undefined from useController

### ISSUE THREAD

**Issue by intayush** [react-hook-form/react-hook-form#11242]
### Version Number

7.48.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/affectionate-solomon-xqzvt2?file=%2Fsrc%2Findex.js%3A16%2C11

### Steps to reproduce

Steps to reproduce

1. View the Codesandbox link and open the console.
2. Check the console,  the defaultValue for `lastName` is `undefned`, although the value provided is correct from the async defaultValues function.

### Expected behaviour

The defaultValues shouldn't get set to undefined when using `shouldUnregister` as `true` with the controlled component.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
only works for uncontrolled input with `reigster` API

**Comment by intayush** [comment]
We can use `values` also but `defaultValues` helps in checking for `dirtyFields` as well. I understand that not using `Controller` component and using register API instead will resolve the issue. But this still remains a hidden bug in useController I guess.

On line number 97 in `useController`, `control._options.defaultValues` is treated as an object although it can be a function as well.
<img width="717" alt="Screenshot 2023-11-29 at 8 56 57 PM" src="https://github.com/react-hook-form/react-hook-form/assets/16962332/825c145e-8631-47de-8af6-4ed0aab6de9c">

If we type check `control._options.defaultValues` and call it if it's a function then it fixes this issue.

Like this -

```
    const updateValues = (
      defaultValues: TFieldValues | DefaultValues<TFieldValues>,
    ) => {
      const value = cloneObject(get(defaultValues, name));
      set(control._defaultValues, name, value);
      if (isUndefined(get(control._formValues, name))) {
        set(control._formValues, name, value);
      }
    };

    updateMounted(name, true);

    if (_shouldUnregisterField) {
      if (isFunction(control._options.defaultValues)) {
        control._options.defaultValues().then((values) => {
          updateValues(values);
        });
      } else if (!!control._options.defaultValues) {
        updateValues(control._options.defaultValues);
      }
    }
```

Thoughts? @bluebill1049

**Comment by bluebill1049** [comment]
imagine if you have 50 controlled inputs with the approach above. it will send out 50 separate request to setup your defaultValue for each inputs.

**Comment by sudhiry** [comment]
in that case we should memoize the defaultValues after the function call.
