### ISSUE TITLE
Solid-JS Extension

### ISSUE THREAD

**Issue by qlaffont** [react-hook-form/react-hook-form#11243]
**Is your feature request related to a problem? Please describe.** + **Describe the solution you'd like**
I'm using this library quite a while and I love it. But currently i'm using SolidJS and I want to be able to use it with this new library very inspired by React.

**Comment by bluebill1049** [comment]
Yes, 100% i just need to find time to do it, which I am struggling to find at the moment, but I really want to. putting in the backlog for now.
