### ISSUE TITLE
issue: when using FieldArray and have error on field.root it is not possible to clear that error and it is revalidating itself

### ISSUE THREAD

**Issue by terragady** [react-hook-form/react-hook-form#11246]
### Version Number

7.48.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/calc-forked-yslhrt?file=%2Fsrc%2FApp.tsx%3A38%2C53

### Steps to reproduce

remove all fields
press submit
Error appears
you can clear it with the button (not specific)
append new item to array
remove it and the error is present without pressing submit

### Expected behaviour

Once the error is removed and reValidation is set to onSubmit it should not appear by itself. It should be also possible to clear root errors from fieldArrays.

It is not possible to 'clearErrors' with 'field.root' parameter so when you start typing in main input the error should dissapear, you can use clearError('field') but this will always clear errors when you type for whole array form.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
so this is an issue with not respect `reValidateMode: "onSubmit" mode right

**Comment by terragady** [comment]
yes I think so but not sure if directly connected to revalidateMode. There is lack of type for clearError of "field.root" or maybe there is a better way of validating the whole array? I have tried with resolver (yup) and if you specify there min 1 item in array it behaves same as above.

**Comment by bluebill1049** [comment]
> There is lack of type for clearError of "field.root" or maybe there is a better way of validating the whole array?

Do you mean the `clearError` API is missing type support?

**Comment by terragady** [comment]
no sure if type support or the error of `field.root` is not included at all. There is type for just `root` but not for fieldArray. In other words, it is not possible to clear root error in fieldArray when it is present.

**Comment by bluebill1049** [comment]
Please fix your validation: `value.length > 0 || "dsadas"`, that's the cause of the issue. It failed the validation.

**Comment by bluebill1049** [comment]
so the issue not with the submit button by the delete button which trigger the validation?

**Comment by terragady** [comment]
yes delete in this case but in general whenever the value is not valid it shows error regardless of setting revalidation to onSubmit. The other issue is not able to clear root error with function.

**Comment by bluebill1049** [comment]
With which function?

**Comment by terragady** [comment]
> With which function?

clearError()

**Comment by bluebill1049** [comment]
it works because you didn't have type button
`<button type="button" onClick={() => clearErrors("cart")}>`

**Comment by terragady** [comment]
yes this is correct but it will clear all errors from the whole array. This will not work:
` <button type="button" onClick={() => clearErrors("cart.root")}>`
to clear only root error but not errors from the whole array. For example you want to have at least 3 items in array and there are 2 and they have some errors and clearing errors on whole array is not what is preferred I think.

I would better keep revalidation all the time on root error because now there is no possibility to clear just root error and even if array is valid, error will stay unless you somehow revalidate manualy.
