### ISSUE TITLE
issue: controller uses its own default value

### ISSUE THREAD

**Issue by kevupton** [react-hook-form/react-hook-form#11247]
### Version Number

7.48.2

### Codesandbox/Expo snack

[CodeSandbox](https://codesandbox.io/p/sandbox/eager-sun-jt4df?file=%2Fpackage.json%3A11%2C30&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpkg0utw00063b6kuj2xoatl%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpkg0utw00023b6kb0e09dnb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpkg0utw00033b6kz4qfp301%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpkg0utw00053b6kl9efpl6e%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpkg0utw00023b6kb0e09dnb%2522%253A%257B%2522id%2522%253A%2522clpkg0utw00023b6kb0e09dnb%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpkg0utw00053b6kl9efpl6e%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpkg0utw00043b6kiook0eyv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clpkg0utw00053b6kl9efpl6e%2522%252C%2522activeTabId%2522%253A%2522clpkg0utw00043b6kiook0eyv%2522%257D%252C%2522clpkg0utw00033b6kz4qfp301%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpkg0utw00033b6kz4qfp301%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

useController seems to use the initial value of the input, which makes it impossible to set a value to undefined.

Some notes:
![image](https://github.com/react-hook-form/react-hook-form/assets/2093615/c97cd851-451e-4302-a3b7-3804b27860cd)
This useSubscribe doesnt seem to use the current reference next method, which is why it only has 1 default value ever.
The above is why it gets cached and never updates.

How come it sets the default value to the formValue?
![image](https://github.com/react-hook-form/react-hook-form/assets/2093615/103f79ee-87fc-4f21-8aff-a7ef7519e0db)
If the above change is made, then the input needs to change twice in order to be able to reset something to undefined.

### Expected behaviour

I would expect that useController resets to the default value on reset.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> Important: Can not apply undefined to defaultValue or defaultValues at useForm.

https://react-hook-form.com/docs/usecontroller

> 
The value for the field. This argument is required and can not be undefined.
--


https://react-hook-form.com/docs/useform/setvalue
