### ISSUE TITLE
issue: Watched fields that are disabled do not have the current value when enabled

### ISSUE THREAD

**Issue by viveleroi** [react-hook-form/react-hook-form#11258]
### Version Number

7.45.4

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-zod-resolver-example-forked-kkvdpr

### Steps to reproduce

1. Type a value into "Age" text input
2. Click the checkbox which will disable the input
3. See "Age: " text lose it's value since the value is now undefined
4. Click the checkbox again to "re-enable" the checkbox
5. See that "Age: " has no value yet the Age field has the value you originally entered

### Expected behaviour

It should show the current value again.

### Relevant log output

```shell
This was discussed in https://github.com/react-hook-form/react-hook-form/issues/7203 but the answers/solutions there do not satisfy the issue for me. Providing default values doesn't appear to change the issue.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dmateertf** [comment]
I'm having this same problem, and many other issues related to disabled fields. Wasn't having these problems on earlier version 7; there seems to have been some breaking change along the way. It seems like disabled fields in general are now unusable with react-hook-form. In some of the other issues related to this, there is an appeal to "following the HTML standard," but I'm not sure the standard is being interpreted correctly here. Yes, disabled inputs should not have their values **submitted** with the form, but that doesn't (IMO) demand that they have their values completely lost during the "working state" on the browser. This seems to be the behavior of the input element itself ... even when disabled, the "value" property still retains the (disabled) value.

**Comment by bluebill1049** [comment]
watch() or getValues() won't be able to predict what's in the render, hence it's going to be one render behind.

by toggle on that disable input, `getValues/watch` will return the current form values, then render kick which disable that input.

**Comment by viveleroi** [comment]
> by toggle on that disable input, getValues/watch will return the current form values, then render kick which disable that input

Sorry, I don't follow what you're saying

**Comment by viveleroi** [comment]
Can someone please explain how to fix this? I have no way to obtain the current value after a field becomes enabled again because it's value is always `undefined` in getValues. The codesandbox shows this error.

**Comment by joacub** [comment]
same here, this was intriduced after they are not watching disabled fields
