### ISSUE TITLE
Change in default values does not trigger validation

### ISSUE THREAD

**Issue by tommedema** [react-hook-form/react-hook-form#1125]
**Describe the bug**
I've described this in-context here:
https://app.usebubbles.com/74a31da3-c24d-4924-aec6-5912c22f42da

**Desktop (please complete the following information):**
https://www.whatsmybrowser.org/b/VJUHP

**Comment by bluebill1049** [comment]
pelase use `reset()`

**Comment by tommedema** [comment]
@bluebill1049 I don't understand. Where to call reset?

**Comment by bluebill1049** [comment]
can you provide a simple codesandbox for reproducing your issue?

**Comment by tommedema** [comment]
That'd take me a lot of time. Did you see my bubbles link? Everything should be there. If that's really not enough I'll need to make time to reproduce this in a codesandbox.

You can also comment in-context at https://app.usebubbles.com/74a31da3-c24d-4924-aec6-5912c22f42da

**Comment by bluebill1049** [comment]
I am taking a closer look at it now.

**Comment by bluebill1049** [comment]
two things form my observation without been be able to have a play with the code:

1. what's the reason mixed-use `defaultValues` with `defaultValue`?
2. minor: `watch` provides defaultValue as the second argument.

**Comment by tommedema** [comment]
1. I experienced bugs when I only provided it once; but I will test this again
2. I experienced bugs when I used watch's second argument; I'd have to test this again

re your question: they're two separate forms, they're independent except that when the first form is submitted it'll cause the second form's defaultName prop to be changed and therefore it should re-render with the new default name

**Comment by bluebill1049** [comment]
> re your question: they're two separate forms, they're independent except that when the first form is submitted it'll cause the second form's defaultName prop to be changed and therefore it should re-render with the new default name

can you try the following?

```
useEffect(() => {
  reset({
    defaultName,
  })
}, [defaultName])
```

**Comment by tommedema** [comment]
Hmm, that seems to be causing all kinds of side effects. You're right that this is probably not easily fixed.

I'll create a new issue when I've found the time to create a codesandbox. Thanks for your help so far

**Comment by bluebill1049** [comment]
I am looking forward for the issue with codesandbox as I am pretty sure we can find an easy solution for this.
