### ISSUE TITLE
Problem with Error Display demo (can't style error message)

### ISSUE THREAD

**Issue by zipzit** [react-hook-form/react-hook-form#1126]
**Describe the bug**
I'm unable to see any errors on the error display demo.  The actual errors display as black colored font on black background.  Not totally helpful in that form. 

**To Reproduce**
1. Go to https://react-hook-form.com/api/#errors
2. Click on Tab "First Error Detected"
3. Then Click on Pink Box "CodesAndBox"
4. That takes you to https://codesandbox.io/s/nrr4n9p8n4
5. Click immediately on Submit button.  That should generate numerous errors.  
6. At first glance you don't see any notifications of errors.  
7. Go to Styles.css file in the codesandbox.io screen.  
8. Change body background color to  #777   
9. Aha!  now I see it.    The error message is NOT in a `<p>` (paragraph) format, so it doesn't show up as red color, per Styles.css for `<p>`

**Codesandbox link**

 https://codesandbox.io/s/nrr4n9p8n4

**Expected behavior**
I was hoping I could inline style the error messages, per  `<p style={{ color: "red" }}>oops</p>`

**Screenshots**

![react-hook-form error oops](https://user-images.githubusercontent.com/4413134/75621353-dd30f400-5b47-11ea-9ba5-dba813d956a3.png)

**Desktop (please complete the following information):**
 - OS: [Win10 Home ver 1909]
 - Browser [chrome Version 80.0.3987.122 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**
N/A

**Additional context**

I don't mean to be unappreciative.  Many thanks to the team for the React-Hook-Form product!

**Comment by bluebill1049** [comment]
Thanks a lot for report this issue. https://codesandbox.io/s/nrr4n9p8n4 apologize for the codesandbox that wasn't updated.

**Comment by zipzit** [comment]
Whoa..  That was quick.  I figured out where I wanted to go... thought I'd share my test code here, for anybody else stuck.  


    <div className="form-group col-md-6">
        <label htmlFor="password">Password</label>
        <input
            type="password"
            placeholder="Password"
            className="form-control"
            name="password"
            id="password"
            ref={register({ required: true, minLength: 2 })}
        />
        {errors.password && errors.password.type === "required" && (
            <p style={{ color: "red" }}>Oops. Password Required.</p>
        )}
        {errors.password && errors.password.type === "minLength" && (
            <p style={{ color: "red" }}> Password should be at least 8 characters long.</p>
        )}
    </div>

**Comment by bluebill1049** [comment]
no worries. good luck with your react learning :)

**Comment by eyasinsabbir** [comment]
![ErrorMessageColor](https://user-images.githubusercontent.com/31186439/101188725-45d17200-3680-11eb-9014-0b726aa2b7b2.PNG)

Just change the span tag color
