### ISSUE TITLE
issue: TypeError: Cannot read properties of null (reading 'control') when using NextJS 14.0.3/14.0.4 with useController for customizing a phone input component

### ISSUE THREAD

**Issue by elanpang** [react-hook-form/react-hook-form#11279]
### Version Number

7.49.0

### Codesandbox/Expo snack

https://codesandbox.io/p/github/elanpang/nxjs-14-rhf-7-issue-1

### Steps to reproduce

just run `npm run build`, you will see the error.

Had tried customized some different 3rd-party components with rhf, got the same error.
In the beginning I didn't use FormProvider and useFormContext, but still have the same build error.

the build error point to below code:

<img width="1033" alt="image" src="https://github.com/react-hook-form/react-hook-form/assets/6789154/56b21c14-9aa0-40f7-87c7-71fc96a0ada2">

demo is here:
https://github.com/elanpang/nxjs-14-rhf-7-issue-1.git

Also did lots of research but no solution yet, below for ref:

https://github.com/orgs/react-hook-form/discussions/3894
https://github.com/orgs/react-hook-form/discussions/7942
https://github.com/orgs/react-hook-form/discussions/5150

https://stackoverflow.com/questions/68073330/react-hook-form-formprovider-not-working-when-using-it-from-internal-component-l
https://stackoverflow.com/questions/76373485/useformcontext-is-null-but-its-context-state-exist-how-can-i-get-it
https://stackoverflow.com/questions/71592559/formcontext-returns-null-inside-simpleform-on-local
https://stackoverflow.com/questions/68183638/react-how-to-mock-useformcontext-react-hook-form
https://stackoverflow.com/questions/73153264/useformcontext-inside-formprovider-is-null

### Expected behaviour

build pass

### Relevant log output

```shell
Generating static pages (0/7)  [=   ]TypeError: Cannot read properties of null (reading 'control')
       at useController (file:///.../nxjs-14-rhf-7-usecontroller-build-issue/node_modules/react-hook-form/dist/index.esm.mjs:395:47)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elanpang** [comment]
BTW, run `npm run dev`  works well

**Comment by AlexRebula** [comment]
How is this going? I am also seeing the same issue when trying to render the controlled component in Storybook.

My understanding for now, after putting a breakpoint on the line where the error happens is that there are multiple mounts happening and when that happens the control object is defined is defined as per below screenshot:

![image](https://github.com/react-hook-form/react-hook-form/assets/371709/aae32b02-a730-4dd0-a08f-e750878eb11f)

If I continue, the control object is undefined:

![image](https://github.com/react-hook-form/react-hook-form/assets/371709/d181b398-beec-4fc9-8d46-6e2bc6775893)

Not sure this will be of any help though.

Here is how I am using the Controller. I have a custom React component like this:

```
import React from "react";
import { ITextFieldProps } from "./TextField.interfaces";
import MUITextField from "@mui/material/TextField";

const TextField: React.FC<ITextFieldProps> = (props) => {
  return <MUITextField {...props} />;
};

export default TextField;
```

I am wrapping my TextField component in a Controller like this:

```
import React from "react";
import { Controller, FieldValues } from "react-hook-form";
import { IControlledTextFieldProps } from "./ControlledTextField.interfaces";
import { TextField, Text } from "@ciqs/ciqs-ui";
import { ERROR_MESSAGE_STYLES } from "./ControlledTextField.styles";

export const ControlledTextField = React.forwardRef<
  HTMLInputElement,
  IControlledTextFieldProps
>(({ name, control, rules, errors, errorMessage, label, ...rest }, ref) => {
  return (
    <Controller
      name={name}
      control={control}
      rules={rules}
      render={({ field }) => (
        <>
          <TextField {...field} label={label} ref={ref} {...rest} />
          {errors[name] && (
            <Text sx={ERROR_MESSAGE_STYLES}>
              {errorMessage || errors[name]?.message}
            </Text>
          )}
        </>
      )}
    />
  );
});

export default ControlledTextField;
```

This is how I am using the ControllerTextField component in StoryBook to reproduce the error:

```
import React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { useForm } from "react-hook-form";
import { ControlledTextField } from "./ControlledTextField.component";

const meta: Meta<typeof ControlledTextField> = {
  title: "Form/ControlledTextField",
  component: ControlledTextField,
  tags: ["autodocs"],
  parameters: {
    layout: "centered",
  },
};

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: "Default",
  },
  render: (args) => {
    const { control } = useForm({}); // useForm hook to get the control object
    return (
      <ControlledTextField
        name="example"
        control={control}
        {...args} // Spread any additional props passed via args
      />
    );
  },
};

```

These are my dependencies:
```
"dependencies": {
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@iconify/react": "^4.1.1",
    "@mui/icons-material": "^5.14.14",
    "@mui/material": "^5.14.14",
    "numeral": "^2.0.6",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.48.2",
    "react-lazy-load-image-component": "^1.6.0",
    "typescript": "^5.2.2"
  },
  "devDependencies": {
    "@babel/preset-env": "^7.23.2",
    "@babel/preset-react": "^7.22.15",
    "@babel/preset-typescript": "^7.23.2",
    "@esbuild/win32-x64": "^0.19.5",
    "@storybook/addon-essentials": "^7.5.1",
    "@storybook/addon-interactions": "^7.5.1",
    "@storybook/addon-links": "^7.5.1",
    "@storybook/addon-mdx-gfm": "^7.5.1",
    "@storybook/blocks": "^7.5.1",
    "@storybook/manager-api": "^7.5.1",
    "@storybook/react": "^7.5.1",
    "@storybook/react-webpack5": "^7.5.1",
    "@storybook/testing-library": "^0.2.2",
    "@storybook/theming": "^7.5.1",
    "file-loader": "^6.2.0",
    "storybook": "^7.5.1"
  },
```

**Comment by elanpang** [comment]
@AlexRebula Still no solution, but why the ticket is closed?
