### ISSUE TITLE
issue: latest version not compatible with node 16

### ISSUE THREAD

**Issue by Ahmed-Elswerky** [react-hook-form/react-hook-form#11281]
### Version Number

7.49.0

### Codesandbox/Expo snack

not able to build a sandbox with node 16 currently

### Steps to reproduce

1. install latest version in a react app
2. use node 16.20
3. try to build
4. See error `##[error]error react-hook-form@7.49.0: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.2"`

### Expected behaviour

error doesn't show

### Relevant log output

```shell
##[error]error react-hook-form@7.49.0: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.2"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luismarketgoo** [comment]
We have the same problem with node 16.20. I think the change of the minimum node version requirement is a breaking change.

**Comment by mrxsal** [comment]
What's the latest version of react-hook-form which is compatible with node 16.20?

**Comment by AXG25** [comment]
temporary solution (what worked for me): in your package.json you can fix version 7.48.n momentarily while they upload the patch that fixes the incompatibility

**Comment by Linuhusainnk** [comment]
"react-hook-form": "^7.37.0"

still have issues while deploying

**Comment by jacobsfletch** [comment]
Same here. I pinned to version `7.45.4` and it seems to be working again:

```json
"react-hook-form": "7.45.4",
```

**Comment by nathanhannig** [comment]
Agreed, this should have been versioned as a breaking change

**Comment by F3n67u** [comment]
Can we remove `engine` field before publishing?  This package is not node package. It should work whatever node version uses.

**Comment by Moshyfawn** [comment]
This is a valid concern. I've successfully run the test suite on Node versions as low as `12`. I would honestly consider dropping the engine version back to `12`.

As for removing the `engine' field: we use at least a couple of Node `10` features, including the `spread operator', which on the one hand, I doubt anyone is running a project lower than even `12`, but on the other hand, strictly specifying the lowest working version is always good.

**Comment by fulutas** [comment]
In my case this is what helped:

`yarn install --ignore-engines
`

**Comment by mayankav** [comment]
when shall we expect a fix?
