### ISSUE TITLE
issue: compare `useController` and `useWatch` when set value to undefined

### ISSUE THREAD

**Issue by dev-boku** [react-hook-form/react-hook-form#11286]
### Version Number

7.49.0

### Codesandbox/Expo snack

- [codesandbox link](https://codesandbox.io/p/sandbox/great-paper-deove?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq1v16eb00063b6htaeft2eu%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq1v16ea00023b6hz6md84i0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq1v16ea00033b6hn06uhnbp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq1v16fj000i3b6hdfqu6v4d%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq1v16ea00053b6h2b8krnsv%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq1v16ea00023b6hz6md84i0%2522%253A%257B%2522id%2522%253A%2522clq1v16ea00023b6hz6md84i0%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clq1v16ea00053b6h2b8krnsv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq1v16ea00043b6hpfxag7w4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clq1v16ea00053b6h2b8krnsv%2522%252C%2522activeTabId%2522%253A%2522clq1v16ea00043b6hpfxag7w4%2522%257D%252C%2522clq1v16ea00033b6hn06uhnbp%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clq1v16ea00033b6hn06uhnbp%2522%257D%252C%2522clq1v16fj000i3b6hdfqu6v4d%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SANDBOX_ONBOARDING%2522%252C%2522id%2522%253A%2522sandbox-onboarding%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522id%2522%253A%2522clq1v16fj000i3b6hdfqu6v4d%2522%252C%2522activeTabId%2522%253A%2522sandbox-onboarding%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Delete all values in InputNumber
2. See `Foo Value Preview` section

----

1. Click to reset button
2. See `Foo Value Preview` section

#### InputNumber Component Introduction and Issues

- This component is designed to convert the value of an input from a string type to a number type. 
- In scenarios where the input value is absent, the default is set to an empty string.  However, since an empty string cannot be directly converted to a number, we plan to use `undefined` in such cases.
- There is a noticeable inconsistency when setting the value to `undefined`, depending on whether it is accessed via `watch` or `field.value`. 
- For instance, if the value is set to 'undefined', the input element that uses `field.value` displays the default value instead. In contrast, accessing the value through `watch` results in `undefined`."

#### Expected behaviour

I thought the values of `foo` and `field.value` would be the same in the `Foo Value Preview` section.
But they were different.
Which is the correct action?

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> It should be assigned to the onChange prop of the input and value should not be undefined.

https://react-hook-form.com/docs/usecontroller

**Comment by dev-boku** [comment]
@bluebill1049 I was wondering which values to use for `useController` and `useWatch` in `InputNumber`

**Comment by dev-boku** [comment]
@bluebill1049 To me, it seems to be [the same issue](https://github.com/react-hook-form/react-hook-form/issues/9845) as the one discussed in the link below. Although useWatch is used within useController, the outcomes are different, and there appears to be a reason to use only useController
