### ISSUE TITLE
issue: Data of controlled components with the disabled prop disappears on subsequent submits

### ISSUE THREAD

**Issue by keirbhaltair** [react-hook-form/react-hook-form#11285]
### Version Number

7.49.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/intelligent-blackburn-8765x7?file=%2Fsrc%2FApp.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/p/sandbox/intelligent-blackburn-8765x7?file=%2Fsrc%2FApp.tsx
2. Click on Submit.
3. Data submitted through the handleSubmit method will be displayed below the button. Notice that both fields (firstName, lastName) appear.
4. Click on Submit again.
5. This time only firstName appears in the submitted data.
6. Click on the button "Toggle last name" twice.
7. Clicking on Submit two more times displays lastName only after the first time again.

In fact, when the disabled prop on the Controller component is always set to false, the same thing happens.

### Expected behaviour

The data returned by the handleSubmit method should be the same on subsequent form submits. It should contain data from all enabled fields, even controlled ones.

Version 7.48.2 behaved correctly in this scenario.

### What browsers are you seeing the problem on?

Firefox, Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is fixed in the latest commit.  https://github.com/react-hook-form/react-hook-form/issues/11276
