### ISSUE TITLE
issue: useFieldArray `TypeError: Cannot set properties of undefined (setting 'mount')`

### ISSUE THREAD

**Issue by Pryxs** [react-hook-form/react-hook-form#11297]
### Version Number

7.49.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-usefieldarray-error-lyhqyr?file=%2Fsrc%2FApp.js

### Steps to reproduce

1. Click on `move` button
2. See error

### Expected behaviour

In fact, i'm not sure. I read in the doc that useFieldArray 'Does not support flat field array.'. This meaning is a little unclear but if i'm not in this case I expect no error. 

In my searches I found an old issue about the same error (https://github.com/react-hook-form/react-hook-form/issues/5492). It seems to be similar. This patch was removed 2 months after its completion, but it still works perfectly with it. However, as I don't know how it works well, I'm not sure if it is really an issue or if I misunderstood something.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Doesn't support flat array, need to be object type.
