### ISSUE TITLE
issue: disabled prop on Controller set to false breaks validation.

### ISSUE THREAD

**Issue by IDrumsey** [react-hook-form/react-hook-form#11292]
### Version Number

7.49.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/sweet-zeh-w378ss

### Steps to reproduce

1. Go to the sandbox
2. Click on the input text box and then click off the input text box to blur. The error message should show.
3. Go to the Controller in the code and change the disabled prop from undefined to false.
4. Reload the sandbox window to reset the form
5. Click and type in the input text box and then click out of the text box. The error message shows even though it shouldn't.

### Expected behaviour

I'm assuming `disabled={false}` should work the same as `disabled={undefined}`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Could you test out the latest? 49.1

**Comment by IDrumsey** [comment]
As far as I can tell, the sandbox is using the latest which should be 7.49.1 and it's still broken. Did you roll that release right before I opened this issue lol?

**Comment by bluebill1049** [comment]
> I'm assuming disabled={false} should work the same as disabled={undefined}.

Yes

> Click and type in the input text box and then click out of the text box. The error message shows even though it shouldn't.

if disabled is undefined then the required is kicked hence show the error message right?

**Comment by jantimon** [comment]
we also saw problems with `disabled:false`

here is a sandbox with `7.49.1` which freezes on first render:
https://codesandbox.io/p/sandbox/disabled-false--react-hook-forms-controller-v4wtq7?file=%2Fsrc%2FApp.tsx%3A17%2C1

and I created a PR with a broken test: #11293 


![broken pipeline](https://github.com/react-hook-form/react-hook-form/assets/4113649/12415eb9-7a0c-4b0c-bc83-b57c0f3d3bea)

**Comment by ibrkljacic** [comment]
@bluebill1049 still persists in the latest (7.49.1). 
The field has "disabled: false" and still gets ommited from the values and fails in required.
![image](https://github.com/react-hook-form/react-hook-form/assets/25188547/3171e9b3-52f1-4c43-9170-cebf28676e16)
