### ISSUE TITLE
issue: not all `resetOptions` passed to `useForm` work

### ISSUE THREAD

**Issue by supervanya** [react-hook-form/react-hook-form#11302]
### Version Number

7.49.2

### Codesandbox/Expo snack

https://codesandbox.io/s/peaceful-gagarin-548ftl?file=/src/App.tsx

### Steps to reproduce

1. Open the sandbox
2. Make the form dirty by entering `first name`
3. Click `reset form` button
4. You can see the `isDirty` form state is no longer true

### Expected behaviour

I would expect the `isDirty` to remain true since I explicitly specified resetOptions:
```js
resetOptions: {
      keepDirty: true,
    }
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
This is using `resetOptions' incorrectly. The `resetOptions` property on `useForm` is the one that determines the behaviour of [the `values` API](https://react-hook-form.com/docs/useform#values) when updating values.

To achieve the desired behaviour, you want to pass the same `resetOptions` to the second [`reset` form method](https://react-hook-form.com/docs/useform/reset) argument:

```js
reset(defaultValues, { keepDirty: true, keepDirtyValues: true })
```

Here is [a working codesandbox](https://codesandbox.io/s/zen-sound-ggrddc?file=%2Fsrc%2FApp.tsx%3A395-416).
