### ISSUE TITLE
issue: useFieldArray

### ISSUE THREAD

**Issue by kuket15** [react-hook-form/react-hook-form#11306]
### Version Number

7.41.5

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-usefieldarray-forked-v6h5mf

### Steps to reproduce

Run the sandbox.

> Clear the content of the "invoice" input: OK
> Clear the content of any "row" input: IMPOSSIBLE (original value is shown instead)

### Expected behaviour

The "row" input should appear empty, the same way "invoice" input is empty.

The following snippet is meant to set the value linked to the input `undefined` instead of empty string:

```
     <Controller
        render={({ field: { onBlur, onChange, value } }) => (
          <input
            onBlur={onBlur}
            onChange={(e) => {
              const v = e.target.value;
              onChange(v.length === 0 ? undefined : v);
            }}
            value={value ?? ""}
          />
        )}
        name={`name`}
        control={control}
      />
```

It works well. Problem occurs when it's used in combination with `useFieldArray`.

It's impossible to clear the input. Am I doing something wrong or is this supposed to be a bug somehow?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> Does not support flat field array.

https://react-hook-form.com/docs/usefieldarray

**Comment by kuket15** [comment]
Thanks for your reply.

I was trying to replicate a minimal example of my issue without realizing flat field array isn't supported.

I've updated the sandbox in the original post (also reported [here](https://codesandbox.io/p/sandbox/react-hook-form-usefieldarray-forked-h4d6x6?file=%2Fsrc%2Findex.tsx)) getting rid of the flat array and the problem still persists.

As you can also see from the image below I tried to clear "Row 3" input. Sent values appears to be correct, but input still displays "Row 3" instead of an empty string.

![image](https://github.com/react-hook-form/react-hook-form/assets/17312077/6b124cfd-e95b-407f-9dab-ba54ad2f0e6a)
