### ISSUE TITLE
issue: PathFieldByValue bug for some state shapes

### ISSUE THREAD

**Issue by john-sanders-cookie** [react-hook-form/react-hook-form#11314]
### Version Number

7.49.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/fieldpathbyvalue-bug-jc5fwt

### Steps to reproduce

1. Open "src/index.ts"
2. Scroll to line 49 where "paths" is defined.

### Expected behaviour

There should be a TS error on line 49 since "escalations" isn't a path that points to a boolean value.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kuket15** [comment]
Don't know if it's strictly related to react-hook-form.

Problems come because you are using a enum as object key.

Below a minimal example showing it works as you expect using a string key:

```
import type { FieldPathByValue } from "react-hook-form";

enum Key {
  key1 = "k1",
}

type Type1 = {
  [Key.key1]: {
    x: boolean;
  }
};

type BooleanPaths1 = FieldPathByValue<Type1, boolean>;

export const paths1: BooleanPaths1[] = ["k1"]; // <-- No error

type Type2 = {
  ["k1"]: {
    x: boolean;
  }
};

type BooleanPaths2 = FieldPathByValue<Type2, boolean>;

export const paths2: BooleanPaths2[] = ["k1"]; // <-- Error
```

**Comment by john-sanders-cookie** [comment]
I've confirmed that the enum is the source of the issue.  If enums are used during the creation of the runtime object with the type, TS stays happy.  However, if the enum is used to define properties on the type, this issue occurs.

Interesting.  Not sure how often something like this comes up, so don't know if a documentation update is warranted.  However, based on the above, I agree that this isn't an issue with the library.
