### ISSUE TITLE
issue: useFieldArray

### ISSUE THREAD

**Issue by kuket15** [react-hook-form/react-hook-form#11318]
### Version Number

7.49.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-usefieldarray-forked-h4d6x6?file=%2Fsrc%2Findex.tsx

### Steps to reproduce

This is related to [#11306](https://github.com/react-hook-form/react-hook-form/issues/11306), closed due to a wrong example.

Run the sandbox.

> Clear the content of the "invoice" input: OK
> Clear the content of any "row" input: IMPOSSIBLE (original value is shown instead)

### Expected behaviour

The "row" input should appear empty, the same way the "invoice" input is empty.

The following snippet is meant to set the value linked to the input `undefined` instead of an empty string:

```
     <Controller
        render={({ field: { onBlur, onChange, value } }) => (
          <input
            onBlur={onBlur}
            onChange={(e) => {
              const v = e.target.value;
              onChange(v.length === 0 ? undefined : v);
            }}
            value={value ?? ""}
          />
        )}
        name={`name`}
        control={control}
      />
```

It works well. Problem occurs when it's used in combination with `useFieldArray`.

It's impossible to clear the input field. Sent values appear to be correct, but input still displays "Row 3" instead of an empty string.

![image](https://github.com/react-hook-form/react-hook-form/assets/17312077/9afccfbc-d5df-4d86-ae00-60a82878b978)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`onChange(v.length === 0 ? undefined : v);`

Do not support `undefined` value, please refer to the doc

**Comment by kuket15** [comment]
Thanks, closing this one
