### ISSUE TITLE
issue: useController.rules.pattern vs useForm.register.pattern

### ISSUE THREAD

**Issue by dev-boku** [react-hook-form/react-hook-form#11312]
### Version Number

7.49.2

### Codesandbox/Expo snack

[Codesandbox Link](https://codesandbox.io/p/sandbox/usecontroller-own-state-forked-h9cprl?file=%2Fsrc%2FApp.tsx%3A28%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqaae0vl00063b6hz9icz7e6%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqaae0vl00023b6hw2gu4qkj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqaae0vl00033b6hmd3l2kmp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqaae0wr000i3b6h41zzdn0f%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqaae0vl00053b6h1l0yxcg5%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqaae0vl00023b6hw2gu4qkj%2522%253A%257B%2522id%2522%253A%2522clqaae0vl00023b6hw2gu4qkj%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqamhevc00023b6h5eyaxprj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A28%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A28%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqamhevc00023b6h5eyaxprj%2522%257D%252C%2522clqaae0vl00053b6h1l0yxcg5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqaae0vl00043b6h5bimskg9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqaae0vl00053b6h1l0yxcg5%2522%252C%2522activeTabId%2522%253A%2522clqaae0vl00043b6h5bimskg9%2522%257D%252C%2522clqaae0vl00033b6hmd3l2kmp%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqaae0vl00033b6hmd3l2kmp%2522%257D%252C%2522clqaae0wr000i3b6h41zzdn0f%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SANDBOX_ONBOARDING%2522%252C%2522id%2522%253A%2522sandbox-onboarding%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522id%2522%253A%2522clqaae0wr000i3b6h41zzdn0f%2522%252C%2522activeTabId%2522%253A%2522sandbox-onboarding%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Go to src/App.tsx 
2. Input 10010 to test1, test2 input element
3. See error

### Expected behaviour

Error messages are supposed to appear on both the `test1` and `test2` input elements, but currently, they are only appearing on `test2`.

### What browsers are you seeing the problem on?

 While the pattern operates correctly when using the `register` function of useForm, it fails to function with `useController.rules.pattern`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
root cause: `field.onChange(parseInt(e.target.value, 10) || 0);`

**Comment by dev-boku** [comment]
> root cause: `field.onChange(parseInt(e.target.value, 10) || 0);`

@bluebill1049 Could you please explain a bit more specifically what the problem is?

**Comment by bluebill1049** [comment]
you have part the value into number instead of the original which is string

**Comment by dev-boku** [comment]
@bluebill1049 Ah, I understand now. So, does this mean that field.onChange should not be given a type other than string?

**Comment by dev-boku** [comment]
Below is an example of the type conversion I wished to perform. However, in this instance, does the pattern fail to function?

ref) https://react-hook-form.com/advanced-usage#TransformandParse
