### ISSUE TITLE
issue: isDirty stay blocked when a form is reset using a file object

### ISSUE THREAD

**Issue by jbdemonte** [react-hook-form/react-hook-form#11327]
### Version Number

7.49.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/hopeful-shannon-7ykptz?file=%2Fsrc%2FApp.tsx

### Steps to reproduce

1. Go to [codesandbox](https://codesandbox.io/p/sandbox/hopeful-shannon-7ykptz?file=%2Fsrc%2FApp.tsx)
2. Select a file 
3. Click on Reset (the current file is used as default value)
4. Select a new file
4. See error :  is dirty stay to false

### Expected behaviour

isDirty should become true when selecting a new file

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> File typed input will need to be managed at the app level due to the ability to cancel file selection and [FileList](https://developer.mozilla.org/en-US/docs/Web/API/FileList) object.

https://react-hook-form.com/docs/useform/formstate

**Comment by jbdemonte** [comment]
> > File typed input will need to be managed at the app level due to the ability to cancel file selection and [FileList](https://developer.mozilla.org/en-US/docs/Web/API/FileList) object.
> 
> https://react-hook-form.com/docs/useform/formstate

😓 Indeed, thank you and sorry I missed that point
