### ISSUE TITLE
issue: setValue fails when set to null

### ISSUE THREAD

**Issue by Sveshnikov-FA** [react-hook-form/react-hook-form#11334]
### Version Number

7.49.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-thing-33t9kl

### Steps to reproduce

1. Create form with one of the values set to an array of objects
2. Set value to null with shouldDirty on
3. Exception gets thrown

### Expected behaviour

The field gets set to null

I'm trying to set an array to null because the form only does shallow checks for difference between values, so if i delete one of the elements of a big array of objects, it's not going to render properly
Shortly after that setValue, I'm setting it to []

ShouldDirty is there because in our production code I reset the deleted field, removing it from dirtyFields;
If the only thing different in a form is a new element that i created and then deleted, dirtyFields should be empty, and so should be the block where i set the array to null

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'disabled')
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
don't support such usage.

**Comment by Sveshnikov-FA** [comment]
Well, that's a shame because it definitely used to be, at version 7.45.2
This also means the underlying issue i was trying to fix with this hack is not clearly solvable
Here, for example, is a quick reproduction:
https://codesandbox.io/p/sandbox/react-hook-form-thing-forked-4f7m5t
Click on the button "Hard Del", and then "Hard Get"

I'm removing one of the elements from the array, so i'm expecting it to show up in the dirtyFields i'm logging
And yet it isn't there

I tried looking around the issues and discussions here, and couldn't find anything related
If you could point me in the direction to fix this, that would be greatly appreciated
