### ISSUE TITLE
Pass form control object to submit function

### ISSUE THREAD

**Issue by mstanielewicz** [react-hook-form/react-hook-form#1133]
The problem I'm having is that currently we pass only form values and event to submit callback. Because of that we have to create a redundant function in form scope that do something like this:
```
const form = useForm();
const submit = (values, event) => submitForm({ values, event, form });
```

So we have to manually pass the form control to our submit callback that could be defined in other scope. We obviously can do some logic in submit that requires form functions and state to be available.

Of course the solution I did is valid, but requires us to pass it manually and create additional function that just passes the objects using closure. I think that it's so repeatable pattern that we could just pass the object automatically. Actually that is something that Formik does and I moved to react-hook-form from there and I was suprised I have to do it manually. I could work on implementation, if that's the feature we want to have in library.

Best wishes.

**Comment by bluebill1049** [comment]
what's the use case? also, can you create a CSB for this? i am not sure i am following 100% in this scenario.

**Comment by mstanielewicz** [comment]
In my current project we created submission functions that are defined separately and get all required things by dependency injection. Those function can do a lot of things, for example modify form data, set backend errors.

It basically looks like this:
```
const submitFn = async ({...some default injected services}, values, form) => {
  // some logic that includes getting some data from form, set errors etc
}

const submit = useFormSubmit(submitFn)

<form onSubmit={handleSubmit(submit)}>
```
Thanks to that we can nicely test the submit functions, by passing mocked injections.

It would be much easier is handleSubmit, that wraps submitFn automatically pass the form object.

**Comment by bluebill1049** [comment]
is `bind` an alternative option instead of changing the simple API?

**Comment by bluebill1049** [comment]
we are not going to change API for now.

**Comment by bluebill1049** [comment]
if others having a similar issue, feel free to comment and leave your suggestion.
