### ISSUE TITLE
setValue did not clear data

### ISSUE THREAD

**Issue by kiansenggoh** [react-hook-form/react-hook-form#1134]
Hi 
facing an issue on clearing of data using setValue.
Please use this sandbox as a demo.
https://codesandbox.io/s/bitter-platform-ljngi?fontsize=14&hidenavigation=1&theme=dark

steps to reproduce,

1. click "clear button"
2. expected: lastname, firstname, mobilenumber data are cleared.
3. click on developer No
4. expected: email field appear
5. click on developer Yes
6. expected: firstname, lastname and mobile appear
5. expected: lastname, firstname, mobilenumber data are cleared. But firstname and mobile was repopulated with previous value

**Comment by bluebill1049** [comment]
use reset if you want to reset the default value as well. RHF is based on uncontrolled.

https://react-hook-form.com/api#reset

**Comment by kiansenggoh** [comment]
Reset will also reset the formstate. Which I need the dirty status.

**Comment by bluebill1049** [comment]
using `useEffect` to clear the value?

**Comment by kiansenggoh** [comment]
Using useEffect seem like a backdoor to fix this. Is this because the component is been re-render thus setValue is not take effect?

**Comment by bluebill1049** [comment]
because react hook form is embraced uncontrolled inputs, so when the component gets re-mount their default value will get injected. unless you can make them invisible.

**Comment by bluebill1049** [comment]
maybe this PR will be useful in your use case: https://github.com/react-hook-form/react-hook-form/pull/1139

**Comment by kiansenggoh** [comment]
We will appreciate this change!!!

**Comment by kiansenggoh** [comment]
Hi i pulled the beta version, ("react-hook-form": "^4.10.2-beta.1",)
but the definition only allow one input.
![image](https://user-images.githubusercontent.com/56799988/75828849-be508d00-5de7-11ea-82c0-a6fede0b12b3.png)

**Comment by bluebill1049** [comment]
I have't released any beta version just yet, i will info you when i do

**Comment by bluebill1049** [comment]
keep an eye on that PR

**Comment by kiansenggoh** [comment]
okok thank you.

**Comment by kiansenggoh** [comment]
Hi just curious when will the PR be merged? Because we has quite a stories need this feature.

Also I tried to checkout that branch and import the whole project as local dependency. But it seem that the reset only accept one parameter.

**Comment by bluebill1049** [comment]
Hey @kiansenggoh it have a tag waiting for upvote, which means we need more users who up vote on the feature to make sure that there are needs out there.

I understand you need to get your work done: react-hook-form@4.10.2-beta.2

you can use this beta for now. I am not finished with that PR just yet, API may change as well. I am putting it up so people can vote for this feature.

**Comment by kiansenggoh** [comment]
Thank you very much i install the beta version
