### ISSUE TITLE
issue: reset method works differently with useEffect and useLayoutEffect

### ISSUE THREAD

**Issue by aputilouski** [react-hook-form/react-hook-form#11358]
### Version Number

7.49.2

### Codesandbox/Expo snack

https://codesandbox.io/p/devbox/react-hook-form-282f2d

### Steps to reproduce

1. Go to SecondTab.tsx
2. Click on Second tab
3. See that "controlled value" is empty

### Expected behaviour

Controlled value should be filled.
It works as expected if useEffect is used instead of useLayoutEffect.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
When using `useLayoutEffect` instead of `useEffect`, the order of execution changes, with the fields registration and update occurring after `useLayoutEffect` executes. It is recommended to use `useEffect` to reset your form.
