### ISSUE TITLE
when toggle between fields, data was set wrongly

### ISSUE THREAD

**Issue by kiansenggoh** [react-hook-form/react-hook-form#1135]
Hi
When i toggle to show different fields, one of the field was populated with wrong data,
Please use this sandbox to reproduce the error.
https://codesandbox.io/s/heuristic-heyrovsky-y3tp1?fontsize=14&hidenavigation=1&theme=dark

step to reproduce

1. click Developer No,
2. Expected: email field appear with empty value. but it was populated with "defaultValues lastname"

**Comment by bluebill1049** [comment]
duplicated: https://github.com/react-hook-form/react-hook-form/issues/1134
