### ISSUE TITLE
issue: useForm's values prop is too strictly defined in Typescript

### ISSUE THREAD

**Issue by CharlieWallace17** [react-hook-form/react-hook-form#11354]
### Version Number

7.49.2

### Codesandbox/Expo snack

https://codesandbox.io/p/devbox/h2f2p9?file=%2Fpackage.json%3A16%2C26-16%2C32

### Steps to reproduce

1. Go to App.tsx
2. Delete `@ts-ignore` comment
3. See compilation error as values prop does not match up with expected type of useForm schema.

### Expected behaviour

useForm's **values** prop should utilize `DeepPartial` in its type definition just like **defaultValues** currently does. The reason for this is, many times in our forms, a subset of a form's dynamic values need to be tracked in "values", while other fields in the form can be left as undefined. However, because "values" does not allow for partial types, users are forced to set meaningless and redundant defaults (e.g. name: undefined, title: "", etc). We think that, by allowing for more flexibility in the "values" type schema, it would make for a more DRY, concise developer experience. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
The `values` API is not intended to provide partial form values, but rather serves as an external state synchronization mechanism. You can still provide `defaultValues` while utilizing the `values` API, which is encouraged and in no way meaningless: the default field values may determine whether an input is controlled or uncontrolled, and are used to calculate the `isDirty` field and form states by comparing them to the current values.

**Comment by CharlieWallace17** [comment]
That makes sense!
 
In many of our forms, we know some values to put in the form - from other external data sources - but not all the values.  For those cases we use `values` - because `defaultValues` is not designed to be dynamic - to populate the known set of values in the form.
 
The following code sandbox demonstrates this concept. We are using an external data source to populate one of the initial values of the form, in this case, "Last Contact Date".

https://codesandbox.io/p/devbox/adoring-leakey-forked-3gp256?file=%2Fsrc%2FApp.tsx%3A57%2C1 
 
Since the update we are suggesting is merely a type change, it should not affect any current behavior, and in our opinion, would only enhance usability for users by allowing for partial types.
 
We can currently get around this by casting our `values` prop _as any_ although this is not ideal.

**Comment by Moshyfawn** [comment]
> In many of our forms, we know some values to put in the form - from other external data sources - but not all the values. For those cases we use `values` - because `defaultValues` is not designed to be dynamic - to populate the known set of values in the form.
> 
> The following code sandbox demonstrates this concept. We are using an external data source to populate one of the initial values of the form, in this case, "Last Contact Date".
> 
> https://codesandbox.io/p/devbox/adoring-leakey-forked-3gp256?file=%2Fsrc%2FApp.tsx%3A57%2C1

In the use-case described in your codesandbox, I believe that `values` is not the appropriate API to consider. There are a couple of factors to consider here. You can pass the partial data as `defaultValues` to your form component. Based on your example, the form is unmounted upon submission. Therefore, there is no need to reset or sync it with the external data source via the `values` API as it will be remounted with new `defaultValues` the next time the user wants to edit the data. Here's a visual representation of what I mean: [codesandbox](https://codesandbox.io/p/devbox/adoring-leakey-forked-nm7q4q?file=%2Fsrc%2FForm2.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqzichmz00093b6ex2ox6c9n%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqzichmy00033b6ecpyeag3c%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqzichmz00063b6eeb8i12yg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqzichmz00083b6eis1zf1wy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqzichmy00033b6ecpyeag3c%2522%253A%257B%2522id%2522%253A%2522clqzichmy00033b6ecpyeag3c%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clqzichmz00083b6eis1zf1wy%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqzichmz00073b6egj91419o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqzichmz00083b6eis1zf1wy%2522%252C%2522activeTabId%2522%253A%2522clqzichmz00073b6egj91419o%2522%257D%252C%2522clqzichmz00063b6eeb8i12yg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqzichmy00043b6eb79xrx1d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clqzichmy00053b6ekkoh1fve%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqwuar8d000oefedfj3ybxtv%2522%257D%255D%252C%2522id%2522%253A%2522clqzichmz00063b6eeb8i12yg%2522%252C%2522activeTabId%2522%253A%2522clqzichmy00043b6eb79xrx1d%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

> Since the update we are suggesting is merely a type change, it should not affect any current behavior, and in our opinion, would only enhance usability for users by allowing for partial types.

Changing the `values` type to partial would not be a simple modification as it contradicts the current API behavior. The `values` property is intended to be used as a controlled API to sync the form with external data sources, similar to how a `Controller` provides the source of truth for the current state of the form.

**Comment by CharlieWallace17** [comment]
Here is another example that may better illustrate why we cannot use `defaultValues`: https://codesandbox.io/p/devbox/2-form-example-forked-vxhyj3?file=%2Fsrc%2FForm2.tsx%3A64%2C48

In this case, we would like the initial value of _Date_ in our form to be dynamically populated to the _"Date" of the "Previous Contact" plus 7 days_. However, because we are using `defaultValues`, the original default date is provided to the form's "Date" field no matter what. This does not allow us to achieve our desired behavior.

>Changing the values type to partial would not be a simple modification as it contradicts the current API behavior. The values property is intended to be used as a controlled API to sync the form with external data sources, similar to how a Controller provides the source of truth for the current state of the form.

This would just be a type change and does not change API behavior. It just changes what we can load in from an external data source. The external data source would not necessarily provide _every_ value, and use `undefined` for those values that are unknown at the time. How would changing the type to not force a value for every field in the `values` prop hurt any use of the api?
