### ISSUE TITLE
React-Select losing value on screen

### ISSUE THREAD

**Issue by andre-a2net** [react-hook-form/react-hook-form#1136]
Hi,
I've tried the exemple below, but beside the submit value its ok, on the page, the Select doesn't show the current selected value.

https://react-hook-form.com/api#Controller

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-hookforminput-rzu9s
you refer to this?

**Comment by andre-a2net** [comment]
Yes, but I can't find the problem with the code extracted from your example:

https://codesandbox.io/s/amazing-aryabhata-3j3m8?fontsize=14&hidenavigation=1&theme=dark

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/zealous-haze-7h5c7

**Comment by bluebill1049** [comment]
looks like react-select changed their api.

**Comment by andre-a2net** [comment]
Perfect. It's working now!!! Thank you.
