### ISSUE TITLE
issue: `watch` returns `undefined` after calling `unregister` with `keepDefaultValue: true`

### ISSUE THREAD

**Issue by janhellar** [react-hook-form/react-hook-form#11363]
### Version Number

7.49.2

### Codesandbox/Expo snack

[Codesandbox link](https://codesandbox.io/p/github/janhellar/react-hook-forms-bug-example/main)

### Steps to reproduce

1. Go to [Codesandbox link](https://codesandbox.io/p/github/janhellar/react-hook-forms-bug-example/main)
2. Click on `unregister`
3. Click on `getValues`
4. See output below - `watch` returned `undefined` (while `getValues` returned correct value)

### Expected behaviour

When `unregister` is called for a name with `keepDefaultValue: true` option, `watch` for that name should return default value that was provided in `useForm` as [described in documentation](https://react-hook-form.com/docs/useform/unregister). Instead it returns `undefined`. (`getValues` returns correct value)

Example code snippet:

```typescript
  const { register, unregister, watch } = useForm({
    defaultValues: { example: "test" },
  });

  // this should return "test", but returns `undefined` instead (after `unregister` called)
  console.log(watch("example"));

  useEffect(() => {
    register("example");
  }, []);

  return (
    <button
      onClick={() => {
        unregister("example", {
          keepDefaultValue: true,
        });
      }}
    >
      unregister
    </button>
  );
```

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Relevant log output

```shell
watch "example" output: test
button "unregister" clicked
watch "example" output: undefined
button "getValues" clicked: test
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
`keepDefaultValue` is **used to keep the input's default value** to which the input can be [`reset`](https://react-hook-form.com/docs/useform/reset). This flag is **not used to reset the value of your input to its default value**. You may want to consider the [`resetField`](https://react-hook-form.com/docs/useform/resetfield) method instead.

**Comment by janhellar** [comment]
Ok, makes sense. Thanks for the explanation. Closing this issue.
