### ISSUE TITLE
[setValue | Controller] Setting value with dot notation of object field does not work

### ISSUE THREAD

**Issue by tjelvar-chromaway** [react-hook-form/react-hook-form#11362]
### Version Number

7.49.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-yup-resolver-ts-issue-c7423g?file=%2Fsrc%2FApp.tsx%3A39%2C48

### Steps to reproduce

In the codesandbox i've created minimal example of what i am trying to achieve. I use yup to create a minimal object schema and then i try to set the value of it in my controlled component with `setValue`.

1. Click the `set object value` and notice it works
2. Click the `set string value` and notice it does not update the value

### Expected behaviour

```typescript
setValue("objectField", { prop1: "value" }); // works
setValue("objectField.prop1", "value"); // does not work but i would expect it to
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
> setValue('nestedValue.test', 'updatedData'); // ❌ failed to find the relevant field
> setValue('nestedValue', { test: 'updatedData' } ); // ✅ setValue find input and update

This behaviour is [not supported](https://arc.net/l/quote/pkzfcctv).
