### ISSUE TITLE
issue: Incorrect `getValues()` after reset when `isValid` is destructured from formState

### ISSUE THREAD

**Issue by IanVS** [react-hook-form/react-hook-form#11368]
### Version Number

7.49.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/funny-kapitsa-j7vqmk

### Steps to reproduce

1. Go to reproduction
2. Add a new tag with the button, or remove the existing tag
3. Click the "reset" button
4. Notice that `getValues()` is different from what is rendered.

### Expected behaviour

I was confused why `getValues()` was returning something different from what the form was actually rendering, and narrowed it down to only happening when `isValid` is destructured from formState.  I need to use `reset` with `keepDirtyValues`, and it _almost_ works, except for resetting the value returned by `getValues()`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
> The difference between watch and getValues is that getValues will not trigger re-renders or subscribe to input changes.

`getValues` isn't designed to be called on render, as it's [just a getter](https://arc.net/l/quote/tquvgbmd) as opposed to a React value subscriber.

**Comment by Moshyfawn** [comment]
Consider using [`useWatch`](https://react-hook-form.com/docs/usewatch) / [`watch`](https://react-hook-form.com/docs/useform/watch) to subscribe your UI to field value updates.

**Comment by IanVS** [comment]
I don't really want to subscribe to the updates, though, I just want to have access to the latest values when render does happen to be called.

**Comment by IanVS** [comment]
And render is being called in this case, but `getValues()` is returning the incorrect value.  You can see that it works fine if `isValid` is commented out.

**Comment by IanVS** [comment]
I just checked, and `watch()` returns the incorrect value as well.

**Comment by Moshyfawn** [comment]
I understand this may be tedious, but could you please review [this codesandbox](https://codesandbox.io/p/devbox/admiring-jasper-8fctzf?embed=1&file=%2Fsrc%2FApp.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr53ddqk00073b6e2gnm8kgi%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr53ddqk00023b6epnsa5bdp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr53ddqk00043b6enr5qgpje%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr53ddqk00063b6e8gty0crx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr53ddqk00023b6epnsa5bdp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr53ddqj00013b6e0slb779q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clr53ddqk00023b6epnsa5bdp%2522%252C%2522activeTabId%2522%253A%2522clr53ddqj00013b6e0slb779q%2522%257D%252C%2522clr53ddqk00063b6e8gty0crx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr53ddqk00053b6e6eqydvii%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clr53ddqk00063b6e8gty0crx%2522%252C%2522activeTabId%2522%253A%2522clr53ddqk00053b6e6eqydvii%2522%257D%252C%2522clr53ddqk00043b6enr5qgpje%2522%253A%257B%2522id%2522%253A%2522clr53ddqk00043b6enr5qgpje%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr53ddqk00033b6ert6hey01%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr53ddqk00033b6ert6hey01%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) to identify any differences in core logic between my implementation and yours?

This will help us determine the cause of the issue you are experiencing. Currently, [my codesandbox](https://codesandbox.io/p/devbox/admiring-jasper-8fctzf?embed=1&file=%2Fsrc%2FApp.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr53ddqk00073b6e2gnm8kgi%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr53ddqk00023b6epnsa5bdp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr53ddqk00043b6enr5qgpje%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr53ddqk00063b6e8gty0crx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr53ddqk00023b6epnsa5bdp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr53ddqj00013b6e0slb779q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clr53ddqk00023b6epnsa5bdp%2522%252C%2522activeTabId%2522%253A%2522clr53ddqj00013b6e0slb779q%2522%257D%252C%2522clr53ddqk00063b6e8gty0crx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr53ddqk00053b6e6eqydvii%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clr53ddqk00063b6e8gty0crx%2522%252C%2522activeTabId%2522%253A%2522clr53ddqk00053b6e6eqydvii%2522%257D%252C%2522clr53ddqk00043b6enr5qgpje%2522%253A%257B%2522id%2522%253A%2522clr53ddqk00043b6enr5qgpje%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr53ddqk00033b6ert6hey01%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr53ddqk00033b6ert6hey01%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) is functioning as expected: the values displayed in the `code` element are not updated in real-time as the `'tags'` field values change, as `getValues` does not create a subscription. However, switching back to `watch` does correctly synchronize the displayed values.

**Comment by IanVS** [comment]
Thanks so much for taking a look, @Moshyfawn.  I've forked your sandbox to show the issue:

https://codesandbox.io/p/devbox/admiring-jasper-8fctzf

The difference is that I am using `keepDirtyValues`, not just `keepDirty`.  So, after changing tags, the "reset" button should basically do nothing to the form or the values logged to the console, but the console log is incorrect in this fork.

**Comment by bluebill1049** [comment]
@IanVS i couldn't reproduce the issue (with your steps), could you share a video?

**Comment by Moshyfawn** [comment]
> @IanVS I couldn't reproduce the issue (with your steps), could you share a video?

The codesandbox that Ian linked to is my codesandbox that I've shared with them. I've modified it again to suit Ian's use-case; you can now reproduce the problem.

Here's the screencast too. Note that after the form is reset, there is a re-render that forces the values to be logged, but they don't update to the values in the form. The above `tags` list in the app never changes from default values.

I've tracked it down to how [the `values` are composed](https://github.com/react-hook-form/react-hook-form/blob/75cab7f0a944770170e0773a19b5510d6c1884bb/src/logic/createFormControl.ts#L858C1-L861C7), possibly due to [how `_state.mount` is calculated](https://github.com/react-hook-form/react-hook-form/blob/75cab7f0a944770170e0773a19b5510d6c1884bb/src/logic/createFormControl.ts#L1252C1-L1253C1), where `_proxyFormState.isValid` equals `"all"` and we never pass `keepStateOptions.keepIsValid`, so [`_state.mount` is `false`](https://github.com/react-hook-form/react-hook-form/blob/75cab7f0a944770170e0773a19b5510d6c1884bb/src/logic/createFormControl.ts#L860C11-L860C23), hence no update.


https://github.com/react-hook-form/react-hook-form/assets/16290753/1a7c5462-813c-4d99-a280-d50eca074cc2

**Comment by bluebill1049** [comment]
you can resolve this issue with 

```tsx
reset(
  undefined,
  { keepDirty: true, keepDirtyValues: true },
)
```

**Comment by IanVS** [comment]
Thanks, but I do want to update the default values in my situation (and any non-dirty form values). Are you saying that this is working as intended?

**Comment by bluebill1049** [comment]
@IanVS is rather a difficult case when isValid is invoked because it will need to trigger revalidation after mounted, and the getValues return value is base mounted. I will take a look at it again after work.
