### ISSUE TITLE
Example/Documentation for using async validation with Controller

### ISSUE THREAD

**Issue by jdoklovic** [react-hook-form/react-hook-form#1137]
I have a MUI-based component that I need to use with <Controller />. I also need to use a custom async validator with this component.

currently I can't seem to put the bits together to figure out how to define the custom validator for this.

Any docs/examples would be helpful

**Comment by bluebill1049** [comment]
`validate` function?
<img width="874" alt="Screen Shot 2020-03-03 at 7 49 18 am" src="https://user-images.githubusercontent.com/10513364/75716543-8122c700-5d23-11ea-941b-d7ed45e98860.png">

you can pass that to rules props under controller.
