### ISSUE TITLE
issue: reset keepValues does not work

### ISSUE THREAD

**Issue by adriaanwm** [react-hook-form/react-hook-form#11372]
### Version Number

7.49.3

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/vibrant-vaughan-wszfpx?file=%2Fsrc%2FApp.js%3A30%2C14

### Steps to reproduce

1. Change any form input value, see the data change (tracked via watch)
2. Click on reset
3. See data is lost rather than keeping current values. Input fields correctly show current data.

### Expected behaviour

I'm expecting the watched data to remain the same after resetting since keepValues is true, I just want to clear the dirty state. Instead, it is removing the values. The input itself seems to keep the current value, but the watched data does not. 

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`reset(undefined, { keepValues: true });`

**Comment by adriaanwm** [comment]
@bluebill1049 with `reset(undefined, { keepValues: true });` the watch values are returned to the defaultValues when you click the reset button.

<img width="518" alt="Screenshot 2024-01-09 at 1 55 26 PM" src="https://github.com/react-hook-form/react-hook-form/assets/5009842/eb3ca685-8cf9-4ccc-b207-e08472d6af26">

**Comment by Moshyfawn** [comment]
@adriaanwm you're using [an old version](https://codesandbox.io/p/sandbox/vibrant-vaughan-wszfpx?file=%2Fsrc%2FApp.js%3A30%2C14&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr6r86wt00073b6eqliiiw9v%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr6r86wt00033b6ec0d4aebq%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr6r86wt00043b6eaqfmrcbm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr6r86wt00063b6evm3829so%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr6r86wt00033b6ec0d4aebq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr6r86wt00023b6ekbd4uka6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A30%252C%2522startColumn%2522%253A14%252C%2522endLineNumber%2522%253A30%252C%2522endColumn%2522%253A14%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr6r86wt00033b6ec0d4aebq%2522%252C%2522activeTabId%2522%253A%2522clr6r86wt00023b6ekbd4uka6%2522%257D%252C%2522clr6r86wt00063b6evm3829so%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr6r86wt00053b6e9h3wlpe2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clr6r86wt00063b6evm3829so%2522%252C%2522activeTabId%2522%253A%2522clr6r86wt00053b6e9h3wlpe2%2522%257D%252C%2522clr6r86wt00043b6eaqfmrcbm%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clr6r86wt00043b6eaqfmrcbm%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) of RHF backed into that sandbox.

```js
import { useForm } from "./src"
```

Updated to the latest version and import import `react-hook-form` package.

Check out this [working codesandbox](https://codesandbox.io/p/sandbox/happy-bohr-nl98n8?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr6wjtzv00063b6e60p24gh3%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr6wjtzv00023b6e2fb7amqp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr6wjtzv00033b6eidkyuukj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr6wjtzv00053b6ebjoz54s7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr6wjtzv00023b6e2fb7amqp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr6wjtzv00013b6eyxhsx0th%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522clr6wjtzv00023b6e2fb7amqp%2522%252C%2522activeTabId%2522%253A%2522clr6wjtzv00013b6eyxhsx0th%2522%257D%252C%2522clr6wjtzv00053b6ebjoz54s7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr6wjtzv00043b6eprwat8pl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clr6wjtzv00053b6ebjoz54s7%2522%252C%2522activeTabId%2522%253A%2522clr6wjtzv00043b6eprwat8pl%2522%257D%252C%2522clr6wjtzv00033b6eidkyuukj%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clr6wjtzv00033b6eidkyuukj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

**Comment by adriaanwm** [comment]
@Moshyfawn thanks, sorry about that

**Comment by Moshyfawn** [comment]
> @Moshyfawn thanks, sorry about that

No problem!
