### ISSUE TITLE
issue: disabled input is considered dirty

### ISSUE THREAD

**Issue by fzaninotto** [react-hook-form/react-hook-form#11388]
### Version Number

7.49.3

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/stupefied-brattain-xxy96r

### Steps to reproduce

1. Open the attached CodeSandbox
2. The first name field is disabled (with `register("firstName", { disabled: true })`)
3. Under the field, the form state on mount is shown: `isDirty: true`

### Expected behaviour

The form state shouldn't be dirty on mount.

I understand that in HTML, a `disabled` input isn't part of the form payload and isn't sent to the server. It makes sense that since #10805, react-hook-form sets the value of `disabled` fields to `undefined`. But in my opinion, this change shouldn't modify the `dirty` status. 

The rationale is as follows:

- The end user hasn't touched anything
- If they save the form, it shouldn't matter to the backend as it will send no value

In addition, this behavior is problematic because it makes it impossible to properly implement a warning when users leave a form with unsaved changes. If only one input is disabled, the warning will show up even though the user has changed nothing. 

The alternative suggested on https://react-hook-form.com/docs/useform/register#rules is to use `readOnly` instead of `disabled`. Indeed, browsers treat the two differently, and send the (unchanged) value for `readOnly` fields. But the read-only feature is half backed in most browsers, as they don't change the look and feel of the input. It appears to be active, but typing in the input doesn't change anything. As a user, I find it buggy. As a comparison, when using the `disabled` prop, browser inputs *look* read-only. A second drawback of readonly is that it's poorly documented or supported in most component frameworks (material-ui, for instance, doesn't support the `readOnly` tag on `<TextField>`). 

## Possible Solutions

- set `shouldDirty` to `false` when setting the value to `undefined` in `disabled` fields
- expose the `disabled` fields in the form state, so that we can exclude disabled fields from dirty check in user land
- revert #10805

This is a follow-up to #11055. This bug is creating concerns among react-admin users, who routinely combine `disabled` inputs with a dirty check on unmount to avoid losing data. 

https://github.com/marmelab/react-admin/issues/9498

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
It would rather be difficult for us to track the dirty state, as today the dirtiness of the form will do a deep queal against your form values. In order to achieve disabled input as not part of the dirty value, we will have to make that deep equal optional check again each disabled input value, which is not great for perf.
