### ISSUE TITLE
issue: state leaks between multiple useForm / control in single component

### ISSUE THREAD

**Issue by mnahkies** [react-hook-form/react-hook-form#11389]
### Version Number

7.49.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-bug-62sp59

### Steps to reproduce

**Context:** I'm building a login + MFA form, where I want the login form to be replaced with the MFA form after the server issues a MFA challenge. I will work around this by following the separate component approach (which I was probably going to do anyway), but I was surprised the first approach didn't work.

**Issue:** The codesandbox shows two scenarios:
- A single component `<Broken/>` which calls `useForm` twice and shows/hides inputs for each form based on "submitting" the first one
- Two components `<Form1>` / `<Form2>` that each call `useForm` once, and are swapped between in the wrapping `<App>` component

The first scenario doesn't work, because the `value` of the `field` returned by `useController` is seemingly read from `form1` even though the `control` passed to `useController` is the ones from `form2`.

The second scenario works fine.

I initially observed this on `expo` / `react-native` before putting together a web reproduction.

### Expected behaviour

State from `form1` should not leak into `form2`

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mnahkies** [comment]
So I think I've figured this out:
- This `useState` hook returns the state from the previous form control: https://github.com/react-hook-form/react-hook-form/blob/master/src/useWatch.ts#L184-L189
- If I include a `key="<fieldName>"` on the `<Input />` components then it works correctly

I guess that `react` is essentially re-using the `Input` component but with the new props for the `name`, `control`, etc when I swap the forms, and this is causing it to keep `useState` state from the previous props :thinking:

**Comment by Moshyfawn** [comment]
The behaviour you're experiencing is described [in this FAQ section](https://react-hook-form.com/faqs#Whyisdefaultvaluenotchangingcorrectlywithternaryoperator) of the RHF documentation.

**Comment by mnahkies** [comment]
Thanks - I thought I'd gone over the FAQ thoroughly, but clearly missed that :disappointed:
