### ISSUE TITLE
issue: dirtyFields is incorrect when reset() with `keepDefaultValues` and `keepDirtyValues`

### ISSUE THREAD

**Issue by IanVS** [react-hook-form/react-hook-form#11386]
### Version Number

7.49.3

### Codesandbox/Expo snack

https://codesandbox.io/p/github/IanVS/reproduction-keep-dirty-and-default/main

### Steps to reproduce

1. Go to  https://codesandbox.io/p/github/IanVS/reproduction-keep-dirty-and-default/main
2. Click on the first button ('Reset with keepDirtyValues')
3. Notice that the first field was updated, but is not considered dirty, even though it does not match the defaultValue
4. Click on the first button ('Reset')
5. This works correctly, the field is updated again, and now it is considered to be dirty

### Expected behaviour

Sorry, I've got another sneaky potential `keepDefaultValues` bug.

I think I should be able to update the value of non-dirty fields in the form without changing the defaultValue, and dirty tracking should continue to work correctly.

I did notice that controlled form elements work correctly as I expect, but not uncontrolled as shown in the reproduction.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IanVS** [comment]
I updated the reproduction to the vite-based one.  It might be a good idea to update the link in the issue template if possible.  The existing one links to a CSB with a pretty old version of react-hook-form, using an old create-react-app.

**Comment by IanVS** [comment]
I think I have a fix for this, I'll be submitting a PR shortly.

**Comment by bluebill1049** [comment]
Thanks for trying to fix with a PR @IanVS 🙏 I will take a look at it today.

**Comment by bluebill1049** [comment]
Did you change your CSB?

**Comment by IanVS** [comment]
Strange, I guess CSB doesn't automatically update if you sync with a repo?  Sorry about that.  I can't figure out how CSB is working, so here's the link to my repository instead: https://github.com/IanVS/reproduction-keep-dirty-and-default
