### ISSUE TITLE
issue: `dirtyFields` incorrect including unchanged fields after `useFieldArray` list updates

### ISSUE THREAD

**Issue by xanwerneck** [react-hook-form/react-hook-form#11402]
### Version Number

7.48.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-dirty-mnn32s

### Steps to reproduce

1. Go to the link
2. Click on `append`
3. It triggers the `dirtyFields` changes
4. The list includes unchanged fields - name, lastname, and document - as true

### Expected behaviour

`{"colors":[{"id":false,"label":false},{"id":false,"label":false},{"label":true}]}`
or
`{"colors":[{"id":false,"label":false},{"id":false,"label":false},{"label":true}],"nome":false, "last name":false,"document":false}`

#### Issue notes
The issue was detected in an upgrade attempt - from `7.18.1` to `7.47.0`
In the playground we can see the `dirtyFields` object in different versions - no keys, all keys - depending how form is going
The initial state presents an empty list.
Changes to input content correctly include the changed field in the dirty list.
Reverting the change does not update the list - except for fields included in the `defaultValues` list.
Append fills the dirty list with all fields

#### Preventing the problem from happening
We can avoid the problem by including all default values in the `useForm` initializer. Considering the size of the form and how deeply we define individual fields, it doesn't seem like a good choice. Furthermore, we intuitively tend to set field properties in their own scope rather than on the form.
A second alternative we tried was to create an internal `useFieldArray` hook that contains a list of fields - local state persistence.
And finally, another alternative we tried was to create an internal `Controller` by extending `useController` with a `set(control._defaultValues, name, value)` fallback call at component mount time. It populates the `defaultValues` with inline `defaultValue` making the dirty computation able to detect only changed fields.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is expected behaviour and a limitation,  dirty fields will always be measured against the defaultValues. This solves so many edge cases that have occurred over the years. plus inline defaultValue will always cause issues which we didn't include that in the doc.

> Important: Make sure to provide defaultValues at the useForm, so hook form can have a single source of truth to compare each field's dirtiness.

**Comment by hfsaito** [comment]
I can understand some of the project decisions, but there are some details that makes this an unexpected behavior IMO
- Appending a new a value in a field array trigger the dirty fields in another unrelated field
- There is also an inconsistency in dirty fields that sometimes the value `dirtyFields` omit the fields that are not dirty and sometimes it represent the fields as `{field: false}`

The dirtyFields could be set once the field is mounted
or not let the append function from array field triggering it and change a value that is not related to that field

**Comment by james-gough-op** [comment]
> * sometimes it represent the fields as `{field: false}`

Yea this is a big gotcha for an issue I just had to fix. You basically have to parse dirty fields now to check whether it has a `true` value rather than just receiving an object containing dirty key value pairs.
