### ISSUE TITLE
Make append and prepend methods able to work with multiple items at once

### ISSUE THREAD

**Issue by zju1** [react-hook-form/react-hook-form#11408]
There's a problem with adding multiple items to fieldArray at once. I'm using .forEach and append or prepend. But it works really bad when you work with big data that is larger thatn 4-5K items.

My suggestion is make these two method (append, prepend) like remove method. There's a possibility of removing multiple items at once. I think it is not hard to make append and prepend methods like that.

**Comment by Moshyfawn** [comment]
You can use [`replace'](https://arc.net/l/quote/hrbzneis) to compose your new field array based on your operations.

**Comment by bluebill1049** [comment]
it already does `(obj: object | object[], focusOptions) => void`
