### ISSUE TITLE
Allow to dynamically and responsively read current register options

### ISSUE THREAD

**Issue by devnull69** [react-hook-form/react-hook-form#11409]
**Is your feature request related to a problem? Please describe.**
I would like to be able to access (responsively) the current register options (like "is the field xy currently required") so that I can dynamically update my view the same way as watch("xy") allows.

**Describe the solution you'd like**
Everytime I set the register options of a field dynamically (e.g. `required: !!watch("fieldname")`) I'm lacking a means to responsively access the current register state of a field. So it would be very nice to have something like `watchRegisterState("fieldname").required` or similar, maybe to dynamically show an asterisk symbol next to the field label without the need to introduce and manually update additional state.

**Describe alternatives you've considered**
Currently I always have to introduce and properly update additional state values for each field. It would be great if hook form could manage this automatically

**Comment by bluebill1049** [comment]
you should have use `useState` to toggle the required, so you would have the ability to display the UI.

**Comment by devnull69** [comment]
Unfortunately, this doesn't work inside of useArrayFields, because `watch("arrayfield")` doesn't trigger the side effect whereas `watch("arrayfield.0.street")` for example does. Watch should also trigger for field array changes ...
