### ISSUE TITLE
useFieldArray remove method deletes checked radio input values

### ISSUE THREAD

**Issue by Amtron** [react-hook-form/react-hook-form#1140]
Im currently using useFieldArray to render an array of field sets which include checkbox and radio inputs. When I try to delete the field set using the 'remove(index)' method provided by useFieldArray the field set is correctly removed but all of the remaining  field set checkbox and radio inputs become unchecked.

I've updated to the latest release tonight which did fix another remove issue I was experiencing.

Example of form data before remove is called (focus on the variations; specifically the values):
![Screen Shot 2020-03-03 at 10 02 27 pm](https://user-images.githubusercontent.com/5695805/75769685-b5859a00-5d9a-11ea-94e4-ba7d280a2dd3.png)

In the image above you should see that variation at index 1 value is an array of 2 values and variation at index 2 is just "54"

Example of form data after remove is called (as above focus on the variations and the values):
![Screen Shot 2020-03-03 at 10 03 26 pm](https://user-images.githubusercontent.com/5695805/75769812-e4037500-5d9a-11ea-9bfd-cd5f6fbfa056.png)

In the image above you should see that I have removed the first variation and the last two are left (both checkbox inputs). You should also see that variation at index value has an array, but nothing is in it and variation at index 1 value is not empty string.

Please let me know what you think; I did notice that you made a PR recently to fix the remove method with radio and checkbox inputs #1140 ; maybe this is still a bug?

**Comment by bluebill1049** [comment]
provide a simple CSB plz.

**Comment by Amtron** [comment]
https://codesandbox.io/s/react-hook-form-usefieldarray-ii47o
1) On page load click "submit"
In the console you will see variations with an array of options which have values

2) delete the colour field at the top
In console you should see that the data object is now empty.

3) click submit again
The data object now has the remaining variation and it's value

**Comment by bluebill1049** [comment]
you calling `getValues` during `remove()` while the DOM is not been updated. Take a look my example below.

https://codesandbox.io/s/react-hook-form-usefieldarray-ii47o

**Comment by Amtron** [comment]
@bluebill1049 I can not see the difference in your example; it looks the same.

**Comment by bluebill1049** [comment]
Maybe I forgot the save... I will do thag

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-usefieldarray-ff9tq

**Comment by Amtron** [comment]
@bluebill1049 thanks for that. Can you give me a suggestion for how I could wait for remove to finish rendering. I've noticed that it doesn't actually trigger React.useEffect on it's when you call it; you have to change state for that to happen.

**Comment by bluebill1049** [comment]
did you check out the codesandbox with useEffect?

**Comment by Amtron** [comment]
@bluebill1049 Yes I did thanks for that. Still have the same issue though.

I've noticed that you've merged this PR #1173 👍 which looks like it might fix the issue; I'll test it out and let you know how it goes.

Thanks for your assistance.

**Comment by bluebill1049** [comment]
let me know. let's follow up in this issue: https://github.com/react-hook-form/react-hook-form/issues/1174

**Comment by Amtron** [comment]
I'm still having trouble with this; even after I've updated the version.

In my field array I have radio inputs and when I remove one of the fields from the array the values associated with the radio inputs disappear.

This is how I've implemented my input radio:

`     <input
             className='hide'
             type= 'radio'
             id={inputId}
             name={`${name}.value`}
             onChange={onChange}
             ref={register({})}
             value={4} />
`
@bluebill1049 any suggestions?

**Comment by bluebill1049** [comment]
can you provide a simple CSB for this? @Amtron

**Comment by Amtron** [comment]
@bluebill1049 so I found out what the issue was... I was using index as key to render the radio inputs 🤦‍♂ . All solved.

Thank you for the fast response and support.

**Comment by bluebill1049** [comment]
No worries at all. Glad it’s working
