### ISSUE TITLE
issue: data param in onValid in handleSubmit infers as any when TTransformedValues is a union type

### ISSUE THREAD

**Issue by Ar4ys** [react-hook-form/react-hook-form#11414]
### Version Number

7.49.3

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/youthful-chaplygin-4svfw9

### Steps to reproduce

1. Go to [CodeSandbox](https://codesandbox.io/p/sandbox/youthful-chaplygin-4svfw9)
2. Open `/src/App.tsx` file
3. In `useTTransformedValues` in `handleSubmit` (in line 9) you will see that:
    - `data` is inferred as any
    - as a result, TS shows an error: "Parameter 'data' implicitly has an 'any' type."

### Expected behaviour

`data` should be inferred as `Form` (i.e. union type) - the same as in `useOnlyTFieldValues` (line 14)

### Relevant log output

```shell
Parameter 'data' implicitly has an 'any' type.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ar4ys** [comment]
This issue happens because of [Distributive Conditional Types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types) feature in TypeScript. Specifically, because of how `TTransformedValues` is defined and used inside of `UseFormHandleSubmit`: [github permalink](https://github.com/react-hook-form/react-hook-form/blob/4c21b288744b3271e0ec3780d8d9cbccc2708665/src/types/form.ts#L628-L638).

There are two possible fixes I came up with:

1. Force TypeScript to avoid distributing conditional types "by surrounding each side of the `extends` keyword with square brackets" inside `UseFormHandleSubmit` (taken from [TypeScript Handbook#Distributive Conditional Types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types))
2. Replace current `UseFormHandleSubmit` implementation with the one that relies on [default values in generics](https://www.typescriptlang.org/docs/handbook/2/generics.html#generic-parameter-defaults):

```ts
// Proposed implementation of `UseFormHandleSubmit`
export type UseFormHandleSubmit<
  TFieldValues extends FieldValues,
  TTransformedValues extends FieldValues = TFieldValues,
> = (
  onValid: SubmitHandler<TTransformedValues>,
  onInvalid?: SubmitErrorHandler<TFieldValues>,
) => (e?: React.BaseSyntheticEvent) => Promise<void>;
```

The second solution should work in all use-cases, that current one covers without any drawbacks (at least I could not come up with any use-case that may break). As such I would like to create a PR with second fix applied, but as a safety measure I would like to know the reasoning behind current `TTransformedValues` and `UseFormHandleSubmit` implementation (maybe second fix actually breaks in some obscure edge case).

**Comment by bluebill1049** [comment]
> Replace current UseFormHandleSubmit implementation with the one that relies on [default values in generics](https://www.typescriptlang.org/docs/handbook/2/generics.html#generic-parameter-defaults):

Could you share a PR with the second approach?

**Comment by Ar4ys** [comment]
Here is PR #11420 with the second approach.
