### ISSUE TITLE
issue: `useFieldArray` unable to combine `remove` and `append` on the last element

### ISSUE THREAD

**Issue by nekear** [react-hook-form/react-hook-form#11415]
### Version Number

7.49.3

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/rhf-usefieldarray-bug-xwffhc

### Steps to reproduce

1. Initialize an array using useFieldArray;
2. Destructure `fields`, `remove`, and `append` from the array;
3. Render fields, extracting `value` and `index` for each item (optionally, display `value.id` to track internal changes);
4. Add a delete button for each item that will invoke `remove(index)`;
5. Optionally, add `append` to the deletion action when `index === 0` and `fields.length === 1` (but as per docs, it's not recommended to use `append` and `remove` simultaneously in the same render);
6. Alternatively, move `append` into a `useEffect` that triggers when `fields.length === 0`, ensuring there's always at least one element;
7. Try to delete the first element and you will see the issue.

### Expected behaviour

The code is meant to delete an array element when the "Delete" button is clicked and to append a new empty element if the deleted one was the last in the list; to always have something displayed to a user.

In my codesandbox project, there are 4 examples:
1. An approach that is not recommended by docs, where `append` and `remove` are used simultaneously within the same `onClick` event, along with a `Controller` for displaying the output;
2. Using, I assume, recommended approach with `append` moved to `useEffect` and `Controller` for output;
3. A similar method to the second example, with the distinction that the `Controller` is replaced with `register`.
4. Approach without predefined values in `useForm`. **Seems to not have any issues with deletion**.

> As far as I can tell, when the problem occurs, there are more re-renders than usual. Am I doing something wrong, or is this indeed a bug?

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> It's recommended to not stack actions one after another.

https://react-hook-form.com/docs/usefieldarray

**Comment by nekear** [comment]
The issue is present in all four examples I've shared, even though the last three do not involve **stacking actions**.

Moreover, I've just added a fifth example where append and remove are in separate `onClick` handlers. In theory, this should not cause any issues. However, in practice, if we manually `append({})` following the deletion of the last array element via `remove({})` - **with each action occurring in different re-renders and distinct `onClick` handlers** - the deleted value is unexpectedly "restored".

**Comment by nekear** [comment]
And as far as I see, if you enter any values into the first input of the **fifth example** and then delete this record and append an empty one after, the value from `defaultValues` is restored **instead** of the last value you typed.

This seems more like an issue with `defaultValues`, or even with any actions similar to `reset()`, which update the initial state.
