### ISSUE TITLE
getValues() returns an empty object after reset

### ISSUE THREAD

**Issue by maciejmyslinski** [react-hook-form/react-hook-form#1141]
**Describe the bug**
`getValues()` returns an empty object after reset instead of `defaultValues`. In contrast, `watch()` returns proper values. Looks that it is broken since `4.8.3-beta.1` (`4.8.2` works properly).

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-rhfinput-cv427
2. Click on `Reset form`.
4. See the console. The first object shows defaultValues (result of `watch()`) and the second object is empty (result of `getValues()`)

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-rhfinput-cv427

**Expected behavior**
`getValues()` should return default values after form reset.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version latest

**Comment by bluebill1049** [comment]
Reference: https://github.com/react-hook-form/react-hook-form/issues/967 why it's broken. Will investigate for a solution.

**Comment by bluebill1049** [comment]
verified not breaking #967 https://codesandbox.io/s/react-hook-form482-usefieldarray-z7lok
and fix this issue: https://codesandbox.io/s/react-hook-form-rhfinput-ripgg
