### ISSUE TITLE
watch does not trigger useEffect for field arrays

### ISSUE THREAD

**Issue by devnull69** [react-hook-form/react-hook-form#11412]
### Version Number

7.49.3

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/eager-lovelace-85c9lf?file=%2Fsrc%2FApp.tsx%3A48%2C1

### Steps to reproduce

When you look at the codesandbox example (looking at the developer tools console), you will see that every change in the EMAIL field will trigger the corresponding useEffect, whereas a change in the field array for addresses won't

This is a bug, as far as I can tell. Looks like you are mutating the original array rather than creating a new one with every change

### Expected behaviour

`watch("fieldarray")` should trigger useEffect on every change

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> watch result is optimised for render phase instead of useEffect's deps, to detect value update you may want to use an external custom hook for value comparison.

https://react-hook-form.com/docs/useform/watch
