### ISSUE TITLE
Package is not usable without pnpm

### ISSUE THREAD

**Issue by paulshryock** [react-hook-form/react-hook-form#11424]
### Version Number

7.49.3

### Codesandbox/Expo snack

x

### Steps to reproduce

```bash
npm install react-hook-form
```
Installation fails (see error output below).

### Expected behaviour

```bash
npm install react-hook-form
```
Package is installed.

---

## The problem

The change that caused pnpm to become a hard dependency for this package was introduced in pull request #11163.

Keep in mind that package.json's `engines` key applies to end users.

## The solution

Remove pnpm from package.json's `engines` key, so that it's no longer a hard dependency for end users.

### Relevant log output

```shell
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for react-hook-form@7.49.3: wanted: {"node": ">=18","pnpm":"8"} (current: {"node":"21.6.0","npm":"10.2.4"})
npm ERR! notsup Not compatible with your version of node/npm: react-hook-form@7.49.3
npm ERR! notsup Required:  {"node":">=18","pnpm":"8"}
npm ERR! notsup Actual:    {"npm":"10.2.4","node":"21.6.0"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Curious. It shouldn't have failed as it's not set as [engineStrict] (https://docs.npmjs.com/cli/v6/configuring-npm/package-json#enginestrict) 🤔
