### ISSUE TITLE
validationResolver breaks the form

### ISSUE THREAD

**Issue by maciejmyslinski** [react-hook-form/react-hook-form#1142]
**Describe the bug**
validationResolver breaks the form

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-validationresolver-zrmy0
2. Type something in the form
4. See the console. Only the first you typed is logged.

**Codesandbox link**
validationResolver breaks the form

**Expected behavior**
Every change to the input should be logged to the console. It works properly in `4.9.1` (you can change the version in the sandbox and see the difference).

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version latest

**Comment by bluebill1049** [comment]
this is not `onChange` mode.

**Comment by bluebill1049** [comment]
This issue is due to `validationContext`, it's been fixed and will be released with the patch soon: https://github.com/react-hook-form/react-hook-form/commit/71025f96ddf616518467bf740b322541612e81ae

**Comment by bluebill1049** [comment]
thanks for raising this issue.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-validationresolver-cq2rh
