### ISSUE TITLE
[useWatch] doesn't update value when you call reset

### ISSUE THREAD

**Issue by Anton-Schogolev** [react-hook-form/react-hook-form#11430]
### Version Number

latest

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/zen-mirzakhani-y7sfm5?file=%2Fsrc%2FApp.js%3A17%2C23

### Steps to reproduce

1. Go to [https://codesandbox.io/p/sandbox/zen-mirzakhani-y7sfm5?file=%2Fsrc%2FApp.js%3A17%2C23](url)
2. see that valueFromUseWatch and valueFromWatch are different

### Expected behaviour

useWatch with controll provided should behave the same way as watch from useForm

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> useWatch's execution order matters, which means if you update a form value before the subscription is in place, then the value updated will be ignored.


```
 const valueFromUseWatch = useWatch({
    name: "test",
    control: formMethods.control,
  });
  const valueFromWatch = formMethods.watch("test");

  useEffect(() => {
    formMethods.reset({
      description: "",
      test: "should see this",
    });
  }, [formMethods.reset]);
  ```

**Comment by Anton-Schogolev** [comment]
@bluebill1049 Then there is an error in documentation: [https://react-hook-form.com/docs/usewatch#:~:text=The%20only%20difference%20between%20useWatch%20and%20watch%20is%20at%20the%20root%20(useForm)%20level%20or%20the%20custom%20hook%20level%20update.](url)

It's not the only difference between them. It would probably be better to have the list of differences, instead of saying that they are basically the same.
