### ISSUE TITLE
watch & useWatch are breaking when using useFieldsArray with defaultValues

### ISSUE THREAD

**Issue by MaximeBernard** [react-hook-form/react-hook-form#11433]
### Version Number

7

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-v7-ts-usewatch-forked-cyw78k?file=%2Fsrc%2Findex.tsx%3A74%2C40

### Steps to reproduce

I have a weird issue that seems to come up in the recent weeks: the sum of my fieldsArray is set to 0 at first render.

When we tried to fix the bug, we tried `watch` instead of `useWatch` and it worked. Because I don't like magic, I tried to make a simple repro to report a bug. 

Thing is, I found a worse bug. Everything works fine until you specify `defaultValues` into `useForm`. 

Here's the first repro: https://codesandbox.io/p/sandbox/react-hook-form-v7-ts-usewatch-forked-cyw78k?file=%2Fsrc%2Findex.tsx%3A74%2C40

After re-reading the doc, I realized you mentioned `object` and I used `string`. So I tried with `object` instead but it doesn't change anything.

Here's the same repro with objects instead: https://codesandbox.io/s/react-hook-form-v7-ts-usewatch-forked-cmfjr6?file=/src/index.tsx

Notable weird behaviors:
- `watch` never works until you edit an input from one of the fields array
- `useWatch` works but default values get all erased once you edit on input of the fields array
- `defaultValues` doesn't display the default value of the fields array (probably related to `watch` issue
- `useWatch` doesn't behave the same inside a component (this one was even more unexpected)

### Expected behaviour

`defaultValues` should behave the same with or without. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
<img width="1201" alt="Screenshot 2024-01-25 at 7 56 28 am" src="https://github.com/react-hook-form/react-hook-form/assets/10513364/3deb4df7-9a63-404f-93e6-cfcb9fd6be6b">

using the wrong version of the library 

updated:
<img width="268" alt="Screenshot 2024-01-25 at 7 56 43 am" src="https://github.com/react-hook-form/react-hook-form/assets/10513364/2516b9e6-a978-4c5a-964d-ff6adcb360ab">

yours:
<img width="232" alt="Screenshot 2024-01-25 at 7 57 11 am" src="https://github.com/react-hook-form/react-hook-form/assets/10513364/cc4b2a22-69a1-4bc2-b767-79f6ee321fb5">

**Comment by MaximeBernard** [comment]
Thank you for noticing this 🙏 

I forked a codesandbox from the doc. You may want to update those with latest version to avoid future misleading issues.

Happy to help if it's easy ;)
