### ISSUE TITLE
issue: reset and immediate submit leads to validation error

### ISSUE THREAD

**Issue by okletstryit** [react-hook-form/react-hook-form#11444]
### Version Number

7.49.3

### Codesandbox/Expo snack

https://codesandbox.io/p/devbox/m7z6zl?file=%2Fsrc%2FApp.jsx%3A50%2C18

### Steps to reproduce

1. Go to ['...'](https://codesandbox.io/p/devbox/m7z6zl?file=%2Fsrc%2FApp.jsx%3A50%2C18)
2. Click on "Set name to Jack..." button
3. Form is submitted but it has validation error

### Expected behaviour

The form is not submitted as it has validation errors

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`type="button"`

**Comment by okletstryit** [comment]
@bluebill1049 
Thanks for the idea. Maybe I did not get it right

I changed the button to type="button" but it still behaves the same way 

https://codesandbox.io/p/devbox/m7z6zl?file=%2Fsrc%2FApp.jsx%3A41%2C9
