### ISSUE TITLE
issue: node >= 18 still identified as minimum required engine

### ISSUE THREAD

**Issue by silviapio** [react-hook-form/react-hook-form#11449]
### Version Number

7.49.3

### Codesandbox/Expo snack

not able to reproduce this in a sandbox

### Steps to reproduce

1. open a standard react application with typescript (vite)
2. use node v 16.20.2
3. install react-hook-form with `npm i "react-hook-form"`
4. see error in terminal
```(bash)
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'react-hook-form@7.49.3',
npm WARN EBADENGINE   required: { node: '>=18', pnpm: '8' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
```
5. open package.json in `node_modules/react-hook-form/` directory, it still says:
```(javascript)
  "engines": {
    "node": ">=18",
    "pnpm": "8"
  }
```

### Expected behaviour

npm should not give this error, and I would expect the downloaded package to include the correct minimum node version (I see 12.22 in this commit https://github.com/react-hook-form/react-hook-form/commit/f4c126f7312664a6699222bb49475429a06c1439 ) as this issue seems to have been fixed and closed in https://github.com/react-hook-form/react-hook-form/issues/11281

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by valenciaHQ** [comment]
Hi, we are having the same issue. Any idea of how to fix this meantime?

**Comment by Moshyfawn** [comment]
> Any idea of how to fix this meantime?

You may be able to pass [the `-f` flag](https://docs.npmjs.com/cli/v7/using-npm/config#force) to your npm install command if the hard engine requirement fails your install script.

**Comment by mayankav** [comment]
@bluebill1049 why is this issue closed? It still is a problem with the latest version

**Comment by Moshyfawn** [comment]
> @bluebill1049 why is this issue closed? are you tracking the issue elsewhere? It still is a problem with the latest version

https://github.com/react-hook-form/react-hook-form/issues/11449#issuecomment-1914581541

**Comment by bluebill1049** [comment]
@mayankav you tagged me here and also pinged me on Discord. Can you please stop doing that? I got the message and the comment has already been posted above. We are all engineers we should know better and be more considerate of each other, you have your deadline, and so does mine and @Moshyfawn's.

**Comment by mayankav** [comment]
> @mayankav you tagged me here and also pinged me on Discord. Can you please stop doing that? I got the message and the comment has already been posted above. We are all engineers we should know better and be more considerate of each other, you have your deadline, and so does mine and @Moshyfawn's.

sure man! I was just intrigued by the fact why would the issue be closed without a resolution. we shall wait

**Comment by silviapio** [comment]
@mayankav I just upgraded to latest (v50.0) and the issue is solved
