### ISSUE TITLE
issue: field dirty property set to true when add new nested field using useFieldArray()

### ISSUE THREAD

**Issue by bahaasamoudi** [react-hook-form/react-hook-form#11446]
### Version Number

7.49.3

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-usefieldarray-forked-2crc59?file=%2Fsrc%2Findex.tsx%3A57%2C17

### Steps to reproduce

1. Click on Append
2. Note that the li element style changes to yellow because the dirty for the new nested field set to true

### Expected behaviour

I expect the dirty not set to true (it should be false on the initial).
**Note**:  I faced also unexpected behavior with the other fields (all the fields dirty value set to true when using append)

### What browsers are you seeing the problem on?

Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Duplicate of #11396
