### ISSUE TITLE
Why dirtyFields not updating if i make any field dirty?

### ISSUE THREAD

**Issue by webdevmsk** [react-hook-form/react-hook-form#1146]
Why dirty fields not updating if I make any field dirty.

1. Go to https://codesandbox.io/s/7o2wrp86k6
2. Type into any field.
3. I expect `dirtyFields` to update with the field details.
4. Error: `dirtyFields` is always empty.

**Comment by bluebill1049** [comment]
it's a `Set`, look at your console.log

**Comment by bluebill1049** [comment]
<img width="912" alt="Screen Shot 2020-03-04 at 1 59 47 pm" src="https://user-images.githubusercontent.com/10513364/75840902-80238f80-5e20-11ea-816d-f4ca218d733e.png">

**Comment by webdevmsk** [comment]
Console is always logging {}.

Anyway to detect if a particular field got dirty?

**Comment by bluebill1049** [comment]
![Screen Shot 2020-03-04 at 3 44 13 pm](https://user-images.githubusercontent.com/10513364/75846022-0d6de080-5e2f-11ea-8977-cfa1d360dc86.png)

please double check your console.

**Comment by ErikAGriffin** [comment]
Hi I am experiencing this same behavior: the sandbox linked is always logging `{}`, dirtyFields never gets populated

**Comment by bluebill1049** [comment]
@ErikAGriffin please provide a codesandbox.

**Comment by ErikAGriffin** [comment]
The one linked at the top of this thread is producing this behavior for me.

https://github.com/bluebill1049

**Comment by frank7huysen** [comment]
[Sandbox](https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-2esrm)

I also found something interesting(I guess). When I try to access formState.dirtyFields in the onSubmit it returns an empty array.  See _scenario 1._

```
  const onSubmit = data => {
    console.log("dirtyFields:", [...formState.dirtyFields.values()]);
  };
```

However when I put a log statement in my Functional Component which logs dirtyFields during render then it works. See _Scenario 2_. 


### Scenario 1:
![2020-04-03 16 23 53](https://user-images.githubusercontent.com/23256085/78370921-98c1c980-75c7-11ea-8bd4-4093af504e94.gif)

### Scenario 2:
![2020-04-03 16 34 30](https://user-images.githubusercontent.com/23256085/78372035-10dcbf00-75c9-11ea-8ffa-4b0011ec0ed3.gif)

**Comment by ErikAGriffin** [comment]
@frank7huysen what exactly are you replacing the `console.log("test");` to get it to work in the sandbox you linked?

**Comment by frank7huysen** [comment]
> @frank7huysen what exactly are you replacing the `console.log("test");` to get it to work in the sandbox you linked?

change
`console.log('test')`
to
`console.log("render: ", [...formState.dirtyFields.values()]);`

**Comment by bluebill1049** [comment]
Yes it's due to Proxy: https://react-hook-form.com/api#formState 

also `dirtyFields` is a `Set`

<img width="941" alt="Screen Shot 2020-04-04 at 9 23 01 am" src="https://user-images.githubusercontent.com/10513364/78409642-e71da980-7655-11ea-88fe-f02ae6c9cf4d.png">

**Comment by ErikAGriffin** [comment]
@bluebill1049 Perhaps adding an example read and/or invocation to the documentation there to make that more clear?  I'm not exactly sure what "invoking" a Proxy would mean

**Comment by bluebill1049** [comment]
I agree! @ErikAGriffin want to contribute to the doc?

**Comment by ErikAGriffin** [comment]
@bluebill1049 I would like to, however I still don't understand how to invoke the proxy to get the data to show up properly. In that sandbox dirtyFields is still showing up as an empty object for me `{}`

If you post a quick example here I can edit the docs

**Comment by bluebill1049** [comment]
will do @ErikAGriffin which sandbox having the issue?

**Comment by ErikAGriffin** [comment]
So one thing that's happening is wrapping `formState.dirtyFields` in a `JSON.stringify` call outputs an empty object, even when it's working otherwise.

Here is an example where `formState.dirtyFields` is always returning an empty set for me.  It gets logged to the console when the Email field is blurred or the form is submitted.  So I'm not "invoking or reading it before render", which I'm not sure how to do:

https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-td0iq?file=/src/index.js

**Comment by bluebill1049** [comment]
@ErikAGriffin https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-4099d?file=/src/index.js
<img width="1108" alt="Screen Shot 2020-04-11 at 7 52 05 am" src="https://user-images.githubusercontent.com/10513364/79025522-5e5cbb80-7bc9-11ea-899e-82079196cc92.png">

**Comment by bluebill1049** [comment]
I think i need to find a better term to describe the invoke, people probably gets confused.

`const { dirty } = formState; // read the individual state `

instead of 

`return <div>{formState.dirty}</div>`

**Comment by bluebill1049** [comment]
i will upload an example today under the doc.

**Comment by bluebill1049** [comment]
<img width="1030" alt="Screen Shot 2020-04-11 at 2 21 54 pm" src="https://user-images.githubusercontent.com/10513364/79035232-d04ff780-7bff-11ea-8698-8227157cc3a0.png">

updated :)
