### ISSUE TITLE
issue: Form Validation Fails with Disabled Fields in Version > 7.48.2 using shadcn/ui with Form Component

### ISSUE THREAD

**Issue by NastykSwED** [react-hook-form/react-hook-form#11466]
### Version Number

7.50.0

### Codesandbox/Expo snack

https://codesandbox.io/p/devbox/shadcn-ui-bug-rhf-lj7ssz

### Steps to reproduce

1. Navigate to the App.tsx Component: Open the App.tsx file where the FormField component is used, specifically look for the instance where the disabled prop is applied.

2. Check for Pre-populated Value: Ensure that this FormField (for example, the one designated for the username) is pre-populated with a default value, such as "test". This setup mimics the scenario where a field is intended to display existing information but not allow modifications by the user.

3. Attempt Form Submission: Without making any changes to the pre-populated, disabled FormField, proceed to submit the form by clicking the submit button. The expectation here is to test the form's response to an attempt to submit with a disabled field that contains valid data.

4. Observe Validation Behavior: Upon submission, note that validations are erroneously triggered for the disabled FormField. This is unexpected because, given its disabled status, this field should be excluded from validation checks. The occurrence of validation suggests a misinterpretation of the field's intended state and validation requirements.

![1](https://github.com/react-hook-form/react-hook-form/assets/102027097/2ea08beb-94f6-4d82-90ba-bea2535e08d1)

6. Modify the useForm Hook Configuration: Return to the useForm hook setup and remove the values prop that pre-populates the form field. This action is aimed at observing the form's validation behavior in the absence of pre-defined values for disabled fields.

7. Re-evaluate Form Validity and Submission: With the values prop removed, attempt to submit the form again. You should now observe that the form is considered invalid, preventing submission. This behavior indicates a discrepancy in how the form validation logic handles disabled fields with versus without pre-populated values.
![2](https://github.com/react-hook-form/react-hook-form/assets/102027097/2f9b9278-5447-4b1e-a2f4-4a72883c20c2)
![3](https://github.com/react-hook-form/react-hook-form/assets/102027097/704bc733-5389-4122-bd91-713e2c0a3399)

### Expected behaviour

You should be able to submit the form if the values of the disabled inputs are correct.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Relevant log output

```shell
Reverting to version 7.48.2 works perfectly.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Potentially related to #11273

**Comment by bluebill1049** [comment]
disabled input will return `undefined`, this was an issue been fixed previously.

**Comment by Munhuggas** [comment]
> disabled input will return `undefined`, this was an issue been fixed previously.

@bluebill1049 Do you know which version introduced this bug? I have disabled field everywhere and would love to be able to revert to something stable while waiting for a fix.
