### ISSUE TITLE
issue: type safety not extended to register() method within subcomponents, pulled from useFormContext

### ISSUE THREAD

**Issue by owens-bbatte** [react-hook-form/react-hook-form#11467]
### Version Number

7.49.3

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/empty-glade-3hydfm?file=%2Fsrc%2FApp.tsx

### Steps to reproduce

Though this feels like a bug/oversight, I can acknowledge that this might be a limitation and could instead be a feature request. If this is a known (or unknown) limitation, I think calling this out in the documentation would be helpful though

1. Go to the [codesandbox example](https://codesandbox.io/p/sandbox/empty-glade-3hydfm?file=%2Fsrc%2FApp.tsx)
2. Open /src/App.tsx and notice the fields within the ISampleRHFFormComplex interface being used
3. Scroll down to the input trying to register() with the 'otherField1' name, and notice that there is a TS warning because "otherField1" doesn't match anything from our interface
4. Go to RHFSubPerson.tsx and notice the similar input with an invalid name being used, but no type safety extended into this context

### Expected behaviour

I'd expect that the register() method coming out of our useFormContext() would carry with it the same type safety from the parent component

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
There's no way for `useFormContext` to derive your form value type from another file without passing it as a generic.

```ts
useFormContext<ISampleRHFFormComplex>()
```

**Comment by owens-bbatte** [comment]
Of course - dumb question on my part, but thanks for clarifying. 

Definitely not a bug and shouldn't be a feature request. All good here.

**Comment by Moshyfawn** [comment]
A fair question and I'm glad I could help 👌
