### ISSUE TITLE
Can not trigger validation when show add new field

### ISSUE THREAD

**Issue by maxxiaobao** [react-hook-form/react-hook-form#1147]
**Describe the bug**
like title

**To Reproduce**
1. I set `isValid` mode is `onChange`
2. there two fileds on the page, and there are required, the first one depends the second one
3. when I cleared the second one,  then first one show, didn't triggered the first field error

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-reset-forces-all-fields-to-be-changed-xb66p

**Expected behavior**
trigger the first error as well when it show

Browser: chrom
version: 3.29.4

thanks!

**Comment by bluebill1049** [comment]
you should use `validate` function if the field is depend on the others. please refer to this example: https://spectrum.chat/react-hook-form/help/how-to-compare-password-fields~2ce64059-88a7-46a3-951d-4e3d556999d5

also i think your version is way behind.
