### ISSUE TITLE
conditional required field

### ISSUE THREAD

**Issue by iamrenzx** [react-hook-form/react-hook-form#1148]
I have this code it does not remove the required field if i checked and unchecked my checkbox. It still gives an error that it is a required field. What is the suggested solution for this one? 

```
const [checked, setChecked] = useState(false);

<TextField
   inputRef={checked ? register({ required: true }) : register}
   autoFocus
   error={!!errors.example}
   helperText={errors.example && 'Example Field Required'}
   margin="normal"
   id="example"
   name="example"
   onChange={handleExample}
   InputLabelProps={{
     shrink: true,
   }}
   label="Example Field"
   type="text"
   fullWidth
 /> 

```

**Comment by bluebill1049** [comment]
please consider asking question at our spectrum channel.

for your use case you will want to use `valdiate` 
```
validate: data =>  {
  //if (checked) ...
}
```

**Comment by lebreRafael** [comment]
I just did something similar without the validate. I only used the variable as the **required** value.

In this case it would be something like:

```
inputRef={register({ required: checked })}
```

@bluebill1049 Will I have some problem with this approach?

Just to let you know my scenario is: I need at least one of two fields to be filled.

**Comment by bluebill1049** [comment]
@lebreRafael I think you will with `reset` API, if you are using MUI, the label animation is not going pop up and down.
