### ISSUE TITLE
Hidden fields still take part in validation

### ISSUE THREAD

**Issue by ChristopherMeek** [react-hook-form/react-hook-form#11488]
### Version Number

7.x

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-watch-v7-ts-8et1d

### Steps to reproduce

1. Go to the codesandbox above (which is from the watch documentation)
2. Click show age
3. Enter an invalid age 
4. Click show age again
5. Click submit

### Expected behaviour

The submit should succeed as the age is no longer part of the form and therefore should not take part in validation.  If the current behaviour is by design, how should we turn validation on/off for optional inputs. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
you would need to unregister that input, or use shouldUnregister: true

**Comment by ChristopherMeek** [comment]
Thanks @bluebill1049 , I figured I was probably missing something
