### ISSUE TITLE
Watch on a field array element field is not always correct after removing another field array element

### ISSUE THREAD

**Issue by hdaljord** [react-hook-form/react-hook-form#1149]
**Describe the bug**
Watch on a field array element field is not always correct after removing another field array element

**To Reproduce**
Go to https://codesandbox.io/s/react-hook-form-usefieldarray-6x8hm-uvugi

The example is a form with two normal input fields and two radio buttons, and the element that looses its watched value is the radio button element.

1. Fill out Example 1. Notice the outputed value above, this is the value of watch(`inputListe[${index}].chosen`). chosen is either yes or no, depending on your choice.
2. Click Remove for Example 2. Now notice the field values for example 1:
	- First name and last name is kept as expected
	- Chosen (radio button) is now unset and the watched value of chosen has no value (but the value of field.chosen is kept

The behaviour is the same if you fill out example 2 and remove 1.
The value of watch is kept as expected when adding other elements.

**Codesandbox link**
The problem can be seen in https://codesandbox.io/s/react-hook-form-usefieldarray-6x8hm-uvugi

**Expected behavior**
I would expect the watched field value for element 1 to be kept unchanged when removing element 2 in the field array. 

**Screenshots**
The image below shows a screenshot from the linked codesandbox where I selected yes for element 1 and then removed element 2. The underlined value of the watched field value and the field.chosen differs, I would expect the watched value to be the same, not removed.
 
![fieldArrayWatch](https://user-images.githubusercontent.com/36953762/75859204-ddf0b100-5df9-11ea-92bc-ff71dde8a017.png)

**Desktop (please complete the following information):**
 - OS: RedHat Enterprise Linux 7.7
 - Browser: chrome 
 - Version 80.0.3987.122 (Official Build) (64-bit)
 
It is the same behaviour in Firefox Quantum 68.5.0esr (64-bit).

**Comment by bluebill1049** [comment]
<img width="951" alt="Screen Shot 2020-03-04 at 7 37 07 pm" src="https://user-images.githubusercontent.com/10513364/75860217-9137c500-5e4f-11ea-943f-71108878bdcd.png">

Take a look the last dot point on the doc for `useFieldArray`.

**Comment by hdaljord** [comment]
Thanks! That worked. I was confused by your other answer on the spectrum forum last week. 

It would be a good addition to the documentation to add a more complete example for field arrays.
