### ISSUE TITLE
Issue using DefaultValues

### ISSUE THREAD

**Issue by anthonyatp** [react-hook-form/react-hook-form#1150]
**Describe the bug**
I want to pre-populate a form using data from my redux store. Previously, if I refreshed the form page, the default values would be injected correctly.

Since upgrading to RHF v4.0+, If I refresh the form page, default values are not injected into inputs. But if I click out and back into the form page, the values are there.

Here's a basic code example:

**PersonalDetails.tsx**
```
const PersonalDetails = () => {
  const storedData = useSelector(
    (state: IStoreState) => state.personalDetails,
  );

  const methods = useForm({
    defaultValues: {
      personalDetails: storedData,
    },
  });

  const { handleSubmit } = methods;

if (storedData === undefined) {
    return <SkeletonLoading />
  } else {
    return (
      <FormContext {...methods}>
        <form onSubmit={handleSubmit(onSubmit)}>
          <InputString
            name={personalDetails.firstName}
            label="First name"
            required={true}
             />
                    <InputString
                      name={personalDetails.lastName}
                      label="Last name"
                      required={true}
                    />
              <button type="submit">Save</button>
          </form>
        </FormContext>
  }
```

**InputString.tsx**
```
const InputString = ( label, name, required, infoText ) => {
  const methods = useFormContext();
  return (
    <div>
      <Input
        name={name}
        type="string"
        register={methods.register({ required })}
        value={methods.watch(name)}
        onChange={event => methods.setValue(name, event.target.value)}
      />
    </div>
  );
};
```

Hopefully, this is enough information to understand why this is happening but let me know if you need more context.

Thanks!

**Comment by anthonyatp** [comment]
Current version is 4.10.1

I thought it be clearer to show you the issue:
![RHF bug](https://user-images.githubusercontent.com/42555665/75900506-eadec600-5e34-11ea-9667-06d39dbdd088.gif)

**Comment by bluebill1049** [comment]
<img width="943" alt="Screen Shot 2020-03-05 at 8 23 22 am" src="https://user-images.githubusercontent.com/10513364/75924184-97af5680-5eba-11ea-96ac-d396eaf088f9.png">
if `defaultValues` is not read on the initial load, you will need to use `reset({ defaultValues })` at useEffect. thanks for the detailed issue report.

**Comment by anthonyatp** [comment]
@bluebill1049 Exactly what I was looking for. Thanks for your help!

**Comment by bluebill1049** [comment]
no worries.

**Comment by azizur** [comment]
@bluebill1049, Thank you so much for this great package. Finding this absolutely essential to my current project.

I just started to use this package and still learning how to make most of this package. I got a quick question about your [comment](https://github.com/react-hook-form/react-hook-form/issues/1150#issuecomment-594853715).

>if `defaultValues` is not read on the initial load, you will need to use `reset({ defaultValues })` at useEffect. thanks for the detailed issue report.

Is there a particular reason the `defaultValues` is not read on the initial load?

I am asking this questions to learn and understand API design decisions being mades in this package. IMO, It seems counter intuitive to use `reset({ defaultValues })` to set initial field values.

**Comment by bluebill1049** [comment]
> Is there a particular reason the `defaultValues` is not read on the initial load?
> 
> I am asking this questions to learn and understand API design decisions being mades in this package. IMO, It seems counter intuitive to use `reset({ defaultValues })` to set initial field values.

I do agree `reset({ defaultValues })` is counter intuitive, here is the reason why and when you should use it.

`defaultValue` works well when your data is ready on the initial render, however sometimes defaultValue may come from API or delay, and that's when you should use `reset`, i understand it would be better to use an API to called `setValues`, but i didn't want to grow the amount API that user will have to remember and learn. That's the reason i have decided to reuse `reset`. Form RHF v1 till today, we haven't changed any of the primary API and try to keep it simple for most of our users.

hope above make sense.

**Comment by mdoelker** [comment]
Whew, a colleague and I spent way too much time figuring this out, and essentially only your remark here, @bluebill1049, shed some light on it. I'm still kinda baffled it only works like this.

In our case, we have some dependent form elements that only render when other form elements have a specific value. Without reset they just would not show up when the defaultValue already is one that they should render on. My expectation was that `watch` would eventually return the defaultValues.

Looking at how counter-intuitive the whole first-render experience is right now, having a dedicated section about this in the docs, hinting at the reset trick, would be very helpful to save people tons of time.

**Comment by bluebill1049** [comment]
I am sorry to hear that @mdoelker feel free to raise an issue on this on the website repo. I will add some more references either under FAQ or `reset` API.

**Comment by bluebill1049** [comment]
looks like the doc already mention about the reset API 
<img width="941" alt="Screen Shot 2020-04-30 at 10 27 19 pm" src="https://user-images.githubusercontent.com/10513364/80710210-d6b3fe00-8b31-11ea-8577-f98546ed2e7c.png">

**Comment by mdoelker** [comment]
True, although I don't think that it clears things up enough in this case. A FAQ entry would be good. I'd be happy to raise the issue as you suggested. Thanks!

**Comment by gabrielsanttana** [comment]
> looks like the doc already mention about the reset API
> <img alt="Screen Shot 2020-04-30 at 10 27 19 pm" width="941" src="https://user-images.githubusercontent.com/10513364/80710210-d6b3fe00-8b31-11ea-8577-f98546ed2e7c.png">

That's what I was looking for. The `defaultValues` argument passed to `useForm()` does not populate the input value, only the form value. So I had to populate it manually via the attribute `defaultValue` directly on the `<input />` tag. Is this the correct way to do so?

**Comment by bluebill1049** [comment]
no, @gabrielsanttana it should populate the inputs.

**Comment by gabrielsanttana** [comment]
> no, @gabrielsanttana it should populate the inputs.

You're right, it's probably something on the input abstraction that I'm using. Gonna check it up. Thank you!
