### ISSUE TITLE
🐞issue: Controlled component is broken (TS-only) with `TTransformedValues` generic value being used

### ISSUE THREAD

**Issue by xsjcTony** [react-hook-form/react-hook-form#11508]
### Version Number

7.50.1

### Codesandbox/Expo snack

https://stackblitz.com/edit/vitejs-vite-zu9h3d?file=src%2Fcomponents%2FControlledInput.tsx,src%2FApp.tsx&terminal=dev

### Steps to reproduce

1. Go to 'App.tsx'
2. See error

### Expected behaviour

It should not error.

First of all, I appreciate all your hard work💚
This seems a regression in #11420 @bluebill1049 

I've been using this controlled component pattern for ages, everything works smoothly before `7.50.1`, but breaks after.

I've provided a minimal reproduction of 2 react-hook-form versions below:

Comparison:
`v7.50.1`: https://stackblitz.com/edit/vitejs-vite-zu9h3d?file=src%2Fcomponents%2FControlledInput.tsx,src%2FApp.tsx&terminal=dev
`v7.49.3`: https://stackblitz.com/edit/vitejs-vite-ym12kg?file=src%2FApp.tsx,package.json&terminal=dev

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsjcTony** [comment]
https://github.com/react-hook-form/react-hook-form/pull/11420/files#r1460438108 This looks a bit weird to me, I don't find any benefits of adding the third generic to the `Control` type.
Maybe I'm missing something since I don't have much insight into this. I'll temporarily ping the version to `v7.49.3` to resolve the issue.
Cheers!

**Comment by bluebill1049** [comment]
I may just revert that original PR fix for now.

**Comment by bluebill1049** [comment]
reverted for now, will release in the next patch.

**Comment by mlabrum** [comment]
+1 hit this same issue.

I've now had to fix the dependency, any update on when this will be released?
