### ISSUE TITLE
Pattern validation fires when non-required input has `null` value

### ISSUE THREAD

**Issue by Smona** [react-hook-form/react-hook-form#1151]
**Describe the bug**
Today we had a really tough to debug issue due to an edge case where pattern validation will be applied to a non-required input with a value of `null`. It appears that browsers will coerce a null value to an empty string, so everything worked fine in the browser. But in our tests using jsdom, we were getting pattern validation errors when the initial value was empty. Looks like jsdom does not coerce the null value like browsers do.

While this isn't the fault of react-hook-form, adding a null check to the code determining whether to run pattern validation would save a lot of people like me a lot of headaches down the line. Assuming it doesn't break anything else.

**To Reproduce**
1. Write a test using jest and react-testing-library. The test should render a react-hook-form form with an input that has a pattern validation rule and `required != true`. The default value of the field should be null.
2. In the test, try to submit the form.
3. Examining form.errors or displaying the errors will show pattern validation feedback for the field, and submit will be prevented.

**Codesandbox link**
I can't include a Codesandbox, as this behavior only appears in jsdom :flushed: 

**Expected behavior**
I would expect pattern validation to be skipped when the value is null, like it is when the value is an empty string.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser jsdom
 - Version 14.1.0

**Comment by bluebill1049** [comment]
hi @Smona as much as I want to solve this problem for you, I am not a fan of introducing unnecessary code (just like how we try to avoid unnecessary re-render) into he lib just because some other dependency is firing issue, I would post an issue on their repo instead.

**Comment by Smona** [comment]
Ah, that is a good point. I'll report back if I learn anything relevant to this project :+1:

**Comment by bluebill1049** [comment]
sounds good to me thanks 👍
