### ISSUE TITLE
issue: reset() resets dirty values even though keepDirtyValues is set to true

### ISSUE THREAD

**Issue by bastibuck** [react-hook-form/react-hook-form#11514]
### Version Number

7.50.1

### Codesandbox/Expo snack
https://codesandbox.io/p/sandbox/condescending-forest-8wk8v2?file=%2Fsrc%2FApp.tsx%3A15%2C10

### Steps to reproduce

1. Go to the provided codesandbox example of a simple form that gets reset after some timeout (simulating a lazy load from an API)
2. Fill in a firstName before the 5s timeout
3. Watch the outputs of the dirtyFields, isDirty and current form values
4. After the timeout and the triggered reset() the firstName is reset even though `keepDirtyValues: true` is set (and the dirtyFields is also subscribed by destructuring it)

### Expected behaviour

The firstName field value should not be reset 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bastibuck** [comment]
It is totally possible that I am missing something. About the needed subscription of `dirtyFields` I read another issue https://github.com/react-hook-form/react-hook-form/issues/8341 which makes sense but doesn't solve my problem. 

So happy to hear that I am doing something wrong but it might be bug as well.

**Comment by bastibuck** [comment]
I also tried using `resetField()` in my current project to achieve the desired behaviour: load some data from an API and set this value as a new defaultState of my form for a certain field.

This also doesn't seem to work like I would read it from the docs https://react-hook-form.com/docs/useform/resetfield

I provided the new defaultValue for the field but it doesn't set neither the default nor the value.

I'm trying to set an array of objects, if that makes a difference

**Comment by bluebill1049** [comment]
i just tried your demo, keepDirtyValues should be it and it's working in your link as well. let me know what's the issue and I will take a look at it agian.

**Comment by bastibuck** [comment]
After the reset the input UI still shows the correct value. But the firstName in formValues is reset to it's default of `""` even though `keepDirtyValues` is set. 

Make sure to enter a firstName before the 5s timeout or reload the demo browser in case you passed the timeout.

Look at `Form values` rendering and "firstName" especially.


Initial state
```json
"firstName": ""
``` 


After manual update of input field
```json
"firstName": "Tyler"
``` 

After fake loading timeout
```json
"firstName": ""
```

(Other fields are correctly set to new default values)
