### ISSUE TITLE
issue: Value gets carry forward if I chnage the form field type with same name.

### ISSUE THREAD

**Issue by Karan-Rampal** [react-hook-form/react-hook-form#11528]
### Version Number

7.49.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/empty-react-project-forked-348qtf?file=%2Fsrc%2FmyForm.js%3A29%2C17

### Steps to reproduce

1. register an Input field
2. register the number input filed with the same name
3. the validations or value of the input field gets carried forward to the number input as well.

### Expected behaviour

The validations or values should not get carried forward with the change of input type with the same name.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
register name of that input should be unqiue.
