### ISSUE TITLE
Better support for custom form control component with auto validation support

### ISSUE THREAD

**Issue by JounQin** [react-hook-form/react-hook-form#11531]
**Is your feature request related to a problem? Please describe.**

Consider that I have a custom `FastCronForm` control component:

```tsx
<Controller
  name="fastCron"
  control={control}
  render={({ field }) => (
    <FastCronForm {...field} ref={fastCronRef} />
  )}
/>
```

`FastCronForm` can be complex form which takes `value: string` as input, but uses it own complex `FormModel` inside and transform the form model back into `string` in `onChange` prop.

In this case, validating `FastCronForm` manually is not supported natively in `react-hook-form` right now. So I'm using `forwardRef` + `useImperativeHandle` like:

```tsx
// FastCronForm
useImperativeHandle(
  ref,
  () => ({
    validate: trigger,
  }),
  [trigger],
);

// manual trigger validation
await fastCronRef?.validate()
```

**Describe the solution you'd like**

I notice this is already a `ref` property on `field`, what means we can already get inner form ref, so in my view we can have a consensus solution to run `validate` or other standard methods when outside form's `trigger` calls.

I don't know whether there is already something provided that I don't know yet.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by bluebill1049** [comment]
I am not sure if i follow the feature request. What's FastCronForm?

**Comment by JounQin** [comment]
@bluebill1049 Sorry for the confusion, it's only a demo complex form control component.

**Comment by bluebill1049** [comment]
so you want to use `trigger` within the Controller and that's the point of this feature request?

**Comment by JounQin** [comment]
@bluebill1049 Exactly.

**Comment by bluebill1049** [comment]
could you use `useFormContext`?

**Comment by JounQin** [comment]
@bluebill1049 Nope, the `FastCronForm` has its own form model structure, instead of same as the root form.

As I mentioned above:

> `FastCronForm` can be complex form which takes `value: string` as `prop`, but uses it own complex `FormModel` inside and transform the form model back into `string` in `onChange` prop.

**Comment by bluebill1049** [comment]
if it's trigger or hook based api, you will be able to call it anywhere soon in the next feature. still WIP

```trsx
const { trigger, register } = createFormControl()

register('test', { value: 'test' })

function App() {
  return <button onClick={trigger}>trigger</button>
}
```

**Comment by JounQin** [comment]
@bluebill1049 

I know I can do it manually, that is what I'm doing now, my point is that I hope that we can support it automatically just like native inputs.

**Comment by bluebill1049** [comment]
you know there is a rules prop, right?

```tsx
<Controller
  name="fastCron"
  control={control}
  rules={...}
  render={({ field }) => (
    <FastCronForm {...field} ref={fastCronRef} />
  )}
/>
```

**Comment by JounQin** [comment]
I know, and that still means I have to create a ref myself, and write

```
rules={{
  validate: nestedRef?.validate
}}
```

everywhere.

My proposal aims to make it a consensus because we've already have `field.ref`.
