### ISSUE TITLE
reset() API call not resetting form values using Material UI TextField controlled components

### ISSUE THREAD

**Issue by tsaockham** [react-hook-form/react-hook-form#1153]
**Describe the bug**
When calling the reset() API, the form fields are visually reset, but the data sent after a form post remains the old data even though new props are passed into the from component to seed the new default values.

**To Reproduce**
I've made a new sandbox to show the issue I was trying to solve (ref link below).

To recreate the issue, open the console and play around with the broken and fixed versions. Note that when you hit submit, the old values come, even though the fields in the form show the new values. When you do a keypress on any of the fields, that field alone will update, but the other fields will remain as the old ones. The reset API function visibly fixes the issues, but the data is still the old data.

Also, if you play around with the account options that have no name or no balance, you can see that the validation also does not reset in the broken form.

On the fixed version I loop over the values and run the API setValue against the incoming prop item, this fixes the issue.

**Codesandbox link**
 https://codesandbox.io/s/vigilant-mclean-ovywx

**Expected behavior**
The form should be reset, including all the validations and the data visible in the form fields should be sent on form post.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.3
 - Browser: Chrome/Firefox
 - Version: latest

**Smartphone (please complete the following information):**
N/A

**Additional context**
None.  Please let me know if I can clarify further.

**Comment by bluebill1049** [comment]
Please help to investigate by providing a simple and isolated version for this issue.

**Comment by tsaockham** [comment]
Sorry, I don't know if I can do a more isolated version of the issue.  It needs to have a component calling another with dynamic props to show the issue.  This version should be more simple than the one I submitted earlier.

**Comment by bluebill1049** [comment]
Ok, I will take a look tonight.

**Comment by bluebill1049** [comment]
without looking at your example, i have a feeling its due to async `defaulValues`, which you could try reset API during `useEffect`.

**Comment by bluebill1049** [comment]
also plz provide step by step on how to reproduce as well.

**Comment by xiaoyu-tamu** [comment]
https://codesandbox.io/s/sad-https-8hes9

BTW, This question is not related to Material UI.

**Comment by bluebill1049** [comment]
thanks @xiaoyu-tamu
