### ISSUE TITLE
issue: Return type of `watch(<string[]>)` is not inferred while `watch(<string>)` is

### ISSUE THREAD

**Issue by AriPerkkio** [react-hook-form/react-hook-form#11543]
### Version Number

7.50.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/epic-mirzakhani-9t6xc6

### Steps to reproduce

1. Open `App.tsx`
2. Hover on line 15 `name` and see how it has proper type. ✅ 
3. Hover on line 15 `list` and see how it has type `never`. ❌ 
4. Hover on line 17 `listWithProperTypes` and see how it has proper type. ✅ 

### Expected behaviour

`watch(<string[]>)` should infer types as good as `watch(<string>)` does. 

Typescript should not raise errors for this:

```ts
import { useForm } from "react-hook-form";

type FormValues = {
  name: "Type for name";
  list: { nestedList?: "Type for nested list"[] }[];
};

const { watch } = useForm<FormValues>();
const index = Math.random();

const [name, list] = watch(["name", `list.${index}.nestedList.0`]);
const listWithProperTypes = watch(`list.${index}.nestedList.0`);

// @ts-expect-error              <-- This raises error as `list` is `never` 😢 
list === "Should not be allowed";

// @ts-expect-error
name === "Name's type is correct";
// OK
name === "Type for name";

// @ts-expect-error
listWithProperTypes === "Should not be allowed";
// OK
listWithProperTypes === "Type for nested list";
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
work around: 
`const [name, list] = watch(["name", `list.${index}.nestedList.0` as `list.0.nestedList.0`]);`
