### ISSUE TITLE
4.10.1 not working with material-ui select properly.

### ISSUE THREAD

**Issue by NurbekGithub** [react-hook-form/react-hook-form#1154]
**Describe the bug**
4.10.1 not changing value and not showing in submit data value of MUI Select component with Controller
**To Reproduce**
1. Go to https://codesandbox.io/s/rhf-mui-select-zriox
2. try to change value of select component

**Codesandbox link**
https://codesandbox.io/s/rhf-mui-select-zriox

**Expected behavior**
value changes correctly
on submit alert its value

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser chrome
 - Version Version 80.0.3987.106 (Official Build) (64-bit)

**Additional context**
It works with version 4.9.8

**Comment by bluebill1049** [comment]
There is a fix made to read external component value: https://github.com/react-hook-form/react-hook-form/issues/1090

**Comment by bluebill1049** [comment]
you will need onChange method for non-standard event.

we look for `e.target.value` && `e.target.type` and MUI select missing `type`

**Comment by NurbekGithub** [comment]
Sorry, I didn't get it. Is this intended behavior?

Also onChange method of Controller is called with rather "strange" value. For now sticking with 4.9.8 version

**Comment by bluebill1049** [comment]
This is intended behaviour, to solve all issue with target event.

if an event is in a sharp of `{ value: 'test', id: 'test' }` it shouldn't be considered as a proper target to retrieve its value. the previous commit fix this problem, MUI select is return an event without `type`, so RHF can not read the `value` out it, so should you use `onChange` in Controller.

> Also onChange method of Controller is called with rather "strange" value. For now sticking with 4.9.8 version

you can stick that version. it's your choice.

**Comment by bluebill1049** [comment]
FYI @xiaoyu-tamu :)

**Comment by NurbekGithub** [comment]
ok. Thanks!

**Comment by bluebill1049** [comment]
hey @NurbekGithub your issue report is valid! sorry that was my bad, i am applying a fix.

**Comment by NurbekGithub** [comment]
Oh, I was just wondering why docs examples are not working. Happy to know that i can update now. Greate lib and awesome support. Thanks a lot! :star2:
