### ISSUE TITLE
[In <Contoller />'s render prop] Making param type of onChange method, more strict

### ISSUE THREAD

**Issue by nik32** [react-hook-form/react-hook-form#11551]
**Is your feature request related to a problem? Please describe.**
<img width="542" alt="image" src="https://github.com/react-hook-form/react-hook-form/assets/51018572/466ebc4b-2fbf-482c-abbf-e9f9e7de4042">
The type of `onChange` method (as shown in above image) is `any[]`. But if I have understood correctly... the value passed as param to`onChange` will be stored with react-hook-form. Like in above case the value passed to `onChange` would be stored in the `timeZone` field of the form. But if type of `timeZone` is string... shouldn't the `onChange` also accept only a string as a param? With `any[]` I am allowed to pass any value to the onChange and it gets stored with react-hook-form... and thus bugs occur at the run-time.  

**Describe the solution you'd like**
To infer the type of param (in onChange) based to the type of "name" prop in the `<Controller />` (like type of `name="timezone"` is defined as `string`... so onChange should also accept only `string` values)

**Comment by bluebill1049** [comment]
yea, we had that. I created a huge problem with all the external UI libraries.

**Comment by nik32** [comment]
Got it! So if it's not appropriate to implement this solution... you can close this issue. Thanks for your prompt response @bluebill1049!

**Comment by Moshyfawn** [comment]
Related #10342
