### ISSUE TITLE
issue: Disabled rule for inputs of a useFieldArray

### ISSUE THREAD

**Issue by tsiage** [react-hook-form/react-hook-form#11562]
### Version Number

7.50.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-usefieldarray-rules-forked-ty2dzg

### Steps to reproduce

1. Go to the sandbox link
2. Delete the first row
![image](https://github.com/react-hook-form/react-hook-form/assets/16155795/f9de1668-80c2-4035-b021-de22d69a034f)

4. All inputs become 1

![image](https://github.com/react-hook-form/react-hook-form/assets/16155795/cdd034ac-a6c6-4b16-b8de-2e3b291538be)

If the disabled property is removed from the input rules, it works as intended. The same happens if the rules are moved from the useFieldArray. Version 7.47.0 also works fine.

### Expected behaviour

Only the deleted row must be removed without affecting the rest data.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
> "Sandbox is not found"

**Comment by tsiage** [comment]
> > "Sandbox is not found"

fixed!

**Comment by bluebill1049** [comment]
it would difficult to impl just like shouldUnregister

**Comment by tsiage** [comment]
It seems that there is no such issue in version 7.47.0. Is it a design limitation introduced afterwards? The disabled prop for useForm maybe?
