### ISSUE TITLE
issue: useWatch triggered by form input with similar name.

### ISSUE THREAD

**Issue by jozzhart** [react-hook-form/react-hook-form#11561]
### Version Number

7.50.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/bold-fire-ty9ywq

### Steps to reproduce

1. Go to https://codesandbox.io/p/sandbox/bold-fire-ty9ywq
2. Type in in the 'First Name' input field
3. Watch is triggered and output written below input

### Expected behaviour

```
  const nameWatch = useWatch({
    control,
    name: ["firstName_shouldnt_trigger_multiple_times"],
  });
```

This watch shoudn't be triggered by typing in the 'firstName' input.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
```diff
 const nameWatch = useWatch({
   control,
+  exact: true,
   name: ["firstName_shouldnt_trigger_multiple_times"],
 });
```

**Comment by jozzhart** [comment]
Thanks @Moshyfawn , apologies for missing this in the docs.

Little surprised that the default is false.

**Comment by Moshyfawn** [comment]
> Little surprised that the default is false.

Just a little performance tweak.
