### ISSUE TITLE
validationResolver broken after version 4.9.3

### ISSUE THREAD

**Issue by Nagge** [react-hook-form/react-hook-form#1156]
Errors object in not containing error data when returning the object from validationResolver.

Changed the version of react-hook-form to 4.9.4 in example
https://codesandbox.io/s/react-hook-form-validationresolver-01uko

after that errors object is empty. If using version 4.9.3 it works like intended.

**Comment by bluebill1049** [comment]
what about `4.10.2-beta.2`? we made a fix couple days ago.

**Comment by Nagge** [comment]
Solved the problem, thank you

**Comment by bluebill1049** [comment]
awesome will release this weekend.
