### ISSUE TITLE
issue: `resetField` not retaining field state with `keep*`

### ISSUE THREAD

**Issue by jlarmstrongiv** [react-hook-form/react-hook-form#11571]
### Version Number

7.50.1

### Codesandbox/Expo snack

https://stackblitz.com/edit/vite-react-ts-txcz61?file=src%2FYouTubeForm.tsx

### Steps to reproduce

1. Go to https://stackblitz.com/edit/vite-react-ts-txcz61?file=src%2FYouTubeForm.tsx
2. Wait for install and browser preview to appear
3. Within five seconds, add any letter to the `username` field
4. Despite the field being dirty, the value is reset
5. If you miss the timing, just hit the refresh on the browser preview and try again

### Expected behaviour

When using 

```js
resetField('username', {
        keepDirty: true,
        defaultValue: 'wow',
        keepError: true,
        keepTouched: true,
      });
```

I would expect a dirty field to be retained, not overridden.

Related to https://github.com/react-hook-form/react-hook-form/issues/11003

Also, I was unable to create a codesandbox link, I hope stackblitz will suffice.  I really did try to get it working to no avail.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
at this stage, I don't think we have done `keepDirtyValue`, only reset have this `keepDirtyValues` option

**Comment by Moshyfawn** [comment]
The `keepDirty` flag keeps both the `dirtyFields` and `isDirty` form states, as opposed to deciding whether or not to reset the field value based on it's dirty state.

I would suggest retrieving the field's `isDirty` state via the [`getFieldState'](https://react-hook-form.com/docs/useform/getfieldstate) method and conditionally calling the `resetField' method instead.

**Comment by jlarmstrongiv** [comment]
Hmm, I suppose I never fully understood the difference between the two.  It sounds like:
- `keepDirtyValue` has not been implemented; however, 
- `keepDirty` should keep both the dirtyFields and isDirty form states

So it’s both a bug with `keepDirty` and a feature request for `keepDirtyValue`?

**Comment by Moshyfawn** [comment]
I didn't even realise that the form state is also reset, good catch. 

But no, it's my fault, I was looking at the wrong API: according to [the docs](https://react-hook-form.com/docs/useform/resetfield), the `keepDirty` option for the `resetField` method only keeps the `dirtyFields` state by design. 

> When set to true, dirtyFields will be retained.

I honestly don't think we've implemented the API for keeping both the dirty state of the form and the dirty values, which may become a feature request, although we may want to revisit this API.

**Comment by bluebill1049** [comment]
plz submit a feature request instead and we will consider to include.
