### ISSUE TITLE
issue: mutating any fieldArray in the form adds all the fields to 'dirtyFields'

### ISSUE THREAD

**Issue by NitzanSirota** [react-hook-form/react-hook-form#11583]
### Version Number

7.51.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/quizzical-aj-ny8t46?file=%2Fsrc%2FApp.js%3A16%2C21

### Steps to reproduce

1. change the primitive field
2. dirtyFields contains only `primitiveField1`
3. click `append` button
4. dirtyFields contains all of the form fields with false values

### Expected behaviour

1. change the primitive field
2. `dirtyFields` contains only `primitiveField1`
3. click `append` button
4. `dirtyFields` contains only `"array": [ { "firstName": false }, { "firstName": true } ]`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amuttsch** [comment]
Can you explain why this works as designed @bluebill1049 ? I stumbled across the same issue and expected that mutating a field array marks the exact field array as dirty, not my whole form. I also see this as a bug, we use the `dirtyFields` to partially update our data. With the field array marking everything as dirty, we would have to manually check every field if the value changes.

Would you consider opening this issue and change the behavior? Or at least update the documentation for `useFieldArray` to mention that it marks the whole form as dirty? Thank you!

**Comment by Moshyfawn** [comment]
> Can you explain why this works as designed @bluebill1049 ?

I believe this was the explanation: https://github.com/react-hook-form/react-hook-form/issues/11402#issuecomment-1894433724
