### ISSUE TITLE
multiple setValues not working on object array

### ISSUE THREAD

**Issue by github0013** [react-hook-form/react-hook-form#1158]
**Describe the bug**
giving an object array to a field by `setValue` does not do anything.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-setvalue-xf9vy
2. Click on `SETVALUE`
3. Nothing happens
4. Click on `RESET`, same value updates the same field

**Expected behavior**
setValue("fieldName", [{a: 1}]) should update the field.

**Comment by bluebill1049** [comment]
Thank you @github0013 will take a look this over the weekend.

**Comment by bluebill1049** [comment]
here is the fix: https://codesandbox.io/s/react-hook-form-usefieldarray-setvalue-tec5u PR is coming
