### ISSUE TITLE
Be able to provide custom event type when using setValue

### ISSUE THREAD

**Issue by IDrumsey** [react-hook-form/react-hook-form#11593]
**Is your feature request related to a problem? Please describe.**

Part duplicate of [this](https://github.com/react-hook-form/react-hook-form/issues/8048), but that was closed.

I need to run some functionality based on the type of event pushed when using `watch`. I'm using `setValue` and that triggers the watch, but the type of the event is `undefined`. I don't want it to be undefined cuz that's pretty generic and could potentially lead to the functionality running when not expected to.

**Describe the solution you'd like**

Being able to pass a custom event type when using `setValue` which will get picked up by `watch`

```typescript
setValue("myField", "newValue", {type: "my-custom-type"})

watch((data, {name, type}) => {
  if(type == "my-custom-type") {
    // do stuff
  }
})
```

**Comment by Moshyfawn** [comment]
What prevents you from running the logic in the event handler itself?

**Comment by IDrumsey** [comment]
> What prevents you from running the logic in the event handler itself?

Because I only want to run the event handler based on certain events and `setValue` just pushes undefined which is probably also pushed by other things, so that's not a good filter.

If you have an example, please provide :)

**Comment by bluebill1049** [comment]
yea, i would almost do it where you launch the setValue. it seems unnecessary at this stage.

**Comment by Moshyfawn** [comment]
> Because I only want to run the event handler based on certain events and `setValue` just pushes undefined which is probably also pushed by other things, so that's not a good filter.
 
When I say event handler, I don't mean a side effect based on state change, but rather the callback function provided to the even like `onChange={myChangeEventHandler}`. So in this case I'd put any additional logic inside `myChangeEventHandler`.
