### ISSUE TITLE
issue: `trigger` on specific field calls validation function on another field when using yup & yupResolver

### ISSUE THREAD

**Issue by tjelvar-chromaway** [react-hook-form/react-hook-form#11608]
### Version Number

^7

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/relaxed-meitner-r88t22?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clte8ekrj00063b6jyyzd3frn%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clte8ekrj00023b6j6tu2xlm5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clte8ekrj00033b6jkqp9u395%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clte8ekrj00053b6j5ntveg4f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B65.42617296263974%252C34.57382703736026%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clte8ekrj00023b6j6tu2xlm5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clte8ekri00013b6jdkogn4wq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Ftsconfig.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clte8rb9z00023b6jsxngr9yh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clte8ekrj00023b6j6tu2xlm5%2522%252C%2522activeTabId%2522%253A%2522clte8rb9z00023b6jsxngr9yh%2522%257D%252C%2522clte8ekrj00053b6j5ntveg4f%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clte8ekrj00043b6jyyhjntxs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clte8ekrj00053b6j5ntveg4f%2522%252C%2522activeTabId%2522%253A%2522clte8ekrj00043b6jyyhjntxs%2522%257D%252C%2522clte8ekrj00033b6jkqp9u395%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clte8ekrj00033b6jkqp9u395%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

Versions of yup and yup resolver
```
"yup": "1.4.0",
"@hookform/resolvers": "3.3.4"
```
1. Open browser console
2. Click the validate first name button and see that the prints from **both** the validation functions are logged to the console

### Expected behaviour

I would expect only the validation function of the field that has been targeted by `trigger` to execute

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
expected for schema validation. form values will always validate against the entire schema.

**Comment by Moshyfawn** [comment]
While the whole validation scheme is executed, you'll notice that the errors only appear for the specific fields that you triggered the validation for.

**Comment by tjelvar-chromaway** [comment]
> While the whole validation scheme is executed, you'll notice that the errors only appear for the specific fields that you triggered the validation for.

Why do we need to execute the whole validation scheme when we only want to trigger validation on a specific field of that schema?

**Comment by Moshyfawn** [comment]
> Why do we need to execute the whole validation scheme when we only want to trigger validation on a specific field of that schema?

While there are methods in certain validation libraries like [.validateAt](https://github.com/jquense/yup?tab=readme-ov-file#schemavalidateatpath-string-value-any-options-object-promiseinfertypeschema-validationerror) in Yup, the API specific to each validation library was not considered when the resolvers were first designed. Arguably, it can be implemented, but we never found a need for it with how RHF resolvers work.

**Comment by tjelvar-chromaway** [comment]
Okay i see

> Arguably, it can be implemented

imo, it would be an objective improvement that when validation is triggered on a specific field via `trigger` (or otherwise) validation should run **only** for that field (at least for the validation libraries that support it).

> but we never found a need for it with how RHF resolvers work.

In my particular situation i'm implementing some async validation functions in my yup schema and to have them all run when only one is needed feels wasteful. In my particular case, i have ways where i can lessen the impact of the additional async functions being called but in principle it feels wrong and also, imo, unexpected that validation functions for all fields run when only one is requested. 

What do you think? :)

**Comment by Moshyfawn** [comment]
> In my particular situation i'm implementing some async validation functions in my yup schema

This is does seem like a valid use-case for granular field validation, I agree. I'll look deeper into what other validation schema libraries provide for this, but no promises as of yet.
