### ISSUE TITLE
issue: form action does not trigger client side validation

### ISSUE THREAD

**Issue by slava-lu** [react-hook-form/react-hook-form#11610]
### Version Number

7.51.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/lively-sunset-4743mx

### Steps to reproduce

Using **Server Actions**  is now the official and recommended way we build forms in React (Next.js). Wrapping an action in onSubmit function is currently the workaround but does not look like a nice one. 
The validations we put in `register` function should be triggered by `<form action={formAction}>`
Currently it is not the case. 

### Expected behaviour

When using React Server Actions with `action` attribute the client side validation is still triggered. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
still wip

**Comment by Moshyfawn** [comment]
You can follow #11061
