### ISSUE TITLE
Improve TypeScript Generics Handling to Allow For Reusable Components

### ISSUE THREAD

**Issue by BrendanC23** [react-hook-form/react-hook-form#11617]
**Is your feature request related to a problem? Please describe.**
React Hook Form is the premier form library for React, and does a fantastic job at nearly everything. One of the biggest things it lacks is a straightforward way to make reusable, nested, generic components. 

In essence, it's currently difficult to define a component that takes a parameter of `UseFormReturn<PartialForm>` and pass in a form that has the properties of `PartialForm` (either at the top level or in a nested key).

For example (from item 1 below):

```ts
interface Address {
  street: string
  houseNumber: number
  city: string
  country: string
}

interface Person {
  name: string
  address: Address
}

interface Order {
  item: string
  shippingAddress: Address
}

interface OrderWithAddress {
  item: string
  street: string
  houseNumber: number
  city: string
  country: string
}
```

There is no way to create a component `function Address form({form}: {form: UseFormReturn<AddressForm>})` and then pass in either `UseFormReturn<Person>`,  `UseFormReturn<Order>`, or `UseFormReturn<OrderWithAddress>`.

Some of the work to handle reusable form components was done in [this PR](https://github.com/react-hook-form/react-hook-form/pull/5941) as part of a planned V8 release. However, it was reverted due to a TypeScript bug. That bug was fixed in [this PR](https://github.com/microsoft/TypeScript/pull/52997) that was part of TypeScript 5.3.

There was also [this PR](https://github.com/react-hook-form/react-hook-form/pull/6762) related to item 2 below, which had a fix for using generics with `Path`. It was also reverted.

What are the current plans to handle reusable form components? It's clear that there is a lot of interest in this from the community, and there have been discussions about it for many years. The TS issue that prevented the previous PR has been fixed. Is that something that can be looked at again?

**Describe the solution you'd like**
Ideally, [this PR](https://github.com/react-hook-form/react-hook-form/pull/5941) and [this issue](https://github.com/orgs/react-hook-form/discussions/7354) could get looked at again now that the TypeScript problems have been fixed. 

**Describe alternatives you've considered**
[This comment](https://github.com/orgs/react-hook-form/discussions/7354#discussioncomment-2786306) provides a userland solution with a `nestedForm` function, which works reasonably well. However, it can't handle objects with additional props (passing `nestedForm(OrderWithAddress)` to a component expecting`NestedForm<Address>`) due to `Path`'s inability to handle generics (see 2 below). As it isn't built in to the library, it is somewhat cumbersome.

**Additional context**
There have been many previous discussions asking about the same issue. Lots of people have run onto similar problems. Reusability and encapsulation are core programming/React principles, but there's not a great way to accomplish it with RHF.

1. [V8: Reusable components in TypeScript (using branded strings)](https://github.com/orgs/react-hook-form/discussions/7354)
2. [Path T can not handle generics](https://github.com/react-hook-form/react-hook-form/issues/6726)
3. [Nested Form Sections with Typesafe Typescript](https://github.com/orgs/react-hook-form/discussions/9345)
4. [Typescript: How to properly type setValue](https://github.com/orgs/react-hook-form/discussions/7246)
5. [Generic types with a Field component](https://github.com/orgs/react-hook-form/discussions/7948)
6. [Typescript: How can I use a generic type extending an interface](https://github.com/orgs/react-hook-form/discussions/9016)
7. [Reusable component with TypeScript generics](https://github.com/orgs/react-hook-form/discussions/8311)
8. [How to create generic type for Control, UseFormSetValue that work.](https://github.com/orgs/react-hook-form/discussions/10873)
9. [request: path name assertor or generator to match Path T](https://github.com/react-hook-form/react-hook-form/issues/9748)

**Comment by PFJoey** [comment]
We are also looking for a solution to this exact problem. Currently we are investigating other solutions as this starts to become a bottleneck in a lot of use cases.

Any reason why this is marked as pause?
