### ISSUE TITLE
Controller with useFieldArraym antd remove bug

### ISSUE THREAD

**Issue by youngje4284** [react-hook-form/react-hook-form#1161]
**Describe the bug**

Hello when i use Controller with useFieldArray, antd append and remove wrong work.
append => when i append field after remove, reappend removed object
remove => when i delete remove item  Irrespective of remove(index) always delete last element. ㅠㅠ

but I can't see that bug when Controller change to html input and ref register.

this library is the best what I've seen so far.  thanks you make this library.

**To Reproduce**

**Codesandbox link**
Include a codesandox will help us to investigate the issue quicker.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bluebill1049** [comment]
Please provide a codesandbox and fill up the reproduce steps.

**Comment by youngje4284** [comment]
ah... i notice this bug solution. set defaultValue column required... after i set defaultValue property in Controller this bug not appear

**Comment by youngje4284** [comment]
https://codesandbox.io/s/react-hook-form-usefieldarray-ods8f 

this !

**Comment by bluebill1049** [comment]
yes controller will need defaultValue.
