### ISSUE TITLE
issue: `isValidating` remains true by `triggering` form in a `useEffect`

### ISSUE THREAD

**Issue by adguernier** [react-hook-form/react-hook-form#11622]
### Version Number

7.51.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-pending-validating-tgsnvt

### Steps to reproduce

1. Go to the Codesandbox
2. Fill the `firstName` input
3. See that `isValid` is `false` and `isValidating` remains `true` 
4. Fill the `lastName` input
5. See that `isValid` becomes `true` but  `isValidating` remains `true`

### Expected behaviour

It happens since the [v7.51.0](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.51.0), might be introduced by #10657. In the previous version, `isValidating` became `false` after the validation process, which seems to make sense.

What seems to be causing this issue here is triggering validation in a `useEffect`, however, for technical reasons we need to do this in our project:
```ts
// in the <Toolbar> component
React.useEffect(() => {
  trigger();
}, []);
```

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks this should be fixed already: https://github.com/react-hook-form/react-hook-form/pull/11613 in th next release

**Comment by MariaTolstov** [comment]
It is fixed in the latest release when trigger() is used for all fields, but for a specific field ( trigger("fieldName") ) isValidating still returns true.

**Comment by bluebill1049** [comment]
> It is fixed in the latest release when trigger() is used for all fields, but for a specific field ( trigger("fieldName") ) isValidating still returns true.

create an issue with reproducible codesadnbox and steps to reproduce
