### ISSUE TITLE
FieldArray inner fields not updating values after reset

### ISSUE THREAD

**Issue by nfantagossi-asapp** [react-hook-form/react-hook-form#1163]
Please consider asking the question at our spectrum channel.

https://spectrum.chat/react-hook-form

**Describe the question?**

First of all, I wanted to thank you for creating this awesome library. I created a project a few months earlier, leave it there, and now that I came back to do some updates I'm amazed by the huge progress this library has made.

I'm not sure if this is a bug or it's by design, and I couldn't find any other issue for this specific problem.

When calling reset on the form to set a new state for the inputs, I've notice that the array field inputs doesn't behave as any other regular input. Regular inputs update their value automatically, but for field arrays you have to use  `defaultValue={field.value}` in order to get it to update.
I was hoping those field could behave just as the rest would.

**To Reproduce**
1. Go to [code sandbox](https://codesandbox.io/s/field-array-not-loading-values-from-reset-sc3bx)
2. Click on 'reset values' button

The field array get's populated with two inputs, as defined by the object passed to `reset`, but their values are empty.
The regular input outside the array works as expected.

**Codesandbox link**
Include a codesandox will help us to investigate the issue quicker.
https://codesandbox.io/s/field-array-not-loading-values-from-reset-sc3bx

**Screenshots**

**Additional context**

**Comment by bluebill1049** [comment]
hey @nfantagossi-asapp thanks <3. easy one you are missing `defaultValue`

**Comment by dariusz-acai** [comment]
Putting `defaultValues` object like below is not solving the problem. 
Still, nested array fields are not populated with new values when `reset` method invoked. 

```
  const formMethods = useForm({
    defaultValues: question,
  });

  const { fields, append, remove } = useFieldArray({
    control: formMethods.control,
    name: "options",
  });

  useEffect(() => {
    // BUG: nested options are not refreshed, only 
    formMethods.reset(question); 
  }, [question.id]);
```

Question objects looks as follow: 
``` 
  const question = {
    text: "Question",
    options: [{ name: "example 1", name: "example 2" }],
  };
```

**Comment by bluebill1049** [comment]
@dariusz-acai please provide a simple codesandbox around this potentail issue.

**Comment by dariusz-acai** [comment]
Code example: https://codesandbox.io/embed/field-array-not-loading-values-from-reset-2obup?fontsize=14&hidenavigation=1&theme=dark

**Comment by bluebill1049** [comment]
That's exactly what i said above, it's missing defaultValue: https://codesandbox.io/s/field-array-not-loading-values-from-reset-ghqce

**Comment by dariusz-acai** [comment]
Thank you for quick answer - right - it works, didn't get that we were talking about '`defaultValue`' in input field (focusing on `defaultValue` in `useFrom()`). Yet, I still having problem with my code and Material UI TextField component -  trying to reproduce - I will post it today.

**Comment by bluebill1049** [comment]
@dariusz-acai for questions please post at spectrum.
