### ISSUE TITLE
[React Native] After form submit is returned object with nested value

### ISSUE THREAD

**Issue by irekrog** [react-hook-form/react-hook-form#1165]
**Describe the bug**

_React Native_
From version 4.10.0 to latest version (now 5.0.0) after form submit is returned object with value:
`{ text: { value: 'lorem ipsum' } }`. Before 4.10.0 after submit returns `{ text: 'lorem ipsum' }`

Additionaly on Expo on "Web" tab after type just one letter we have `[object Object]`

**To Reproduce**
1. On Expo go to Android or iOS Tab (or just physical device with expo client)
2. Type some text ie: 'lorem ipsum'
3. Click on 'Submit'
4. Look at the console

**Expo links**
* before 4.10.0 https://snack.expo.io/@visterma_calypso/submit-good
* 4.10.0 https://snack.expo.io/@visterma_calypso/submit--bad
* latest (5.0.0) https://snack.expo.io/@visterma_calypso/submit-bad-latest

**Expected behavior**
Return `{ text: 'lorem ipsum' }` instead `{ text: { value: 'lorem ipsum' } }`

**Comment by bluebill1049** [comment]
hey from version 5, you can make `onChange` return simpler:

`const onChange = args => args[0].nativeEvent.text;`

**Comment by irekrog** [comment]
@bluebill1049 
thanks for quick response, after change `const onChange = args => args[0].nativeEvent.text` works now :)

**Comment by bluebill1049** [comment]
it was a bug which I introduced on the initial version, and I thought i fixed it on the latest V4, then I realize it's a broken change this morning...
