### ISSUE TITLE
How field array length check and field value check with yup and controller?

### ISSUE THREAD

**Issue by youngje4284** [react-hook-form/react-hook-form#1166]
**Describe the bug**
Hello how field array length check and field value check with yup and controller?
i make yup validator for field array length check and field row value length check.
but not apply at the same time, only array length check work. how can i fix it?

**To Reproduce**

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-setvalue-5mpq5

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bluebill1049** [comment]
hi, can you provide a codesandbox for this issue? Do you want to validate the array length?

**Comment by youngje4284** [comment]
i want to check array length and field value length check at the sametime. 
codesandbox link already input.

**Comment by bluebill1049** [comment]
please check your codesandbox next time, it's very confusing and not implemented correctly. here is the fixed version: 

https://codesandbox.io/s/react-hook-form-usefieldarray-setvalue-nq2so

take a look at this codesandbox, see if there are still issue with the validation.

**Comment by youngje4284** [comment]
this code only check array length check. i want to array length check and array value length check at the same time 

ex) 
```
Yup.object().shape({
  test: Yup.array()
    .min(1)
    .max(2)
    .of(
      Yup.object().shape({
        name: Yup.string().min(3)
      })
    )
});
```

upper validator maybe check length and array value name length check too
but this code only check length.

**Comment by bluebill1049** [comment]
<img width="556" alt="Screen Shot 2020-03-07 at 10 27 18 pm" src="https://user-images.githubusercontent.com/10513364/76142540-d4e63500-60c2-11ea-9619-cbbb6c7ed580.png">

isn't it checking the length?

**Comment by bluebill1049** [comment]
That's up to your schema validation. RHF return's what's yup returns.

**Comment by bluebill1049** [comment]
going to close this issue, you may want to ask the question at yup's repo
