### ISSUE TITLE
`watch([...])` no longer works

### ISSUE THREAD

**Issue by chungweileong94** [react-hook-form/react-hook-form#1167]
**Describe the bug**
I wanted to use `watch([...])` to watch multiple fields, however, after I updated from `v4.9.5` to `v5.0.0`, it no longer triggers the `watch` every time when the value changed.

But if I add the `watch()` before, it will works, which is kinda redundant. 

**To Reproduce**
1. Add multiple inputs
2. Use `watch([...])` to observe the values change

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-watch-multiple-bug-slmcb

**Expected behavior**
It will watch multiple selected fields

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge (Chromium)
 - Version 80.0.361.66

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-watch-multiple-bug-tljos

**Comment by chungweileong94** [comment]
@bluebill1049  Awesome, thanks!

**Comment by bluebill1049** [comment]
ty @chungweileong94 for report this issue 👍

**Comment by bluebill1049** [comment]
will release the patch tmr
