### ISSUE TITLE
issue: Removing from a field array does not unregister the field value correctly if the useForm's defaultValues has been set with a value

### ISSUE THREAD

**Issue by zjsng** [react-hook-form/react-hook-form#11688]
### Version Number

7.51.1

### Codesandbox/Expo snack

https://codesandbox.io/p/devbox/react-hook-form-usefieldarray-yprzdc

### Steps to reproduce

1. Click on the "Remove last" button twice.
2. Click on the "Append" button twice.
3. Check out the form values returned by `watch()` in the black box. The newly added values should have been all 10, however it still shows up as 20 for the 2nd element and 30 for the 3rd element.

### Expected behaviour

After removing then appending to the field array, the newly appended element should have a value of 10 as what was passed into the `append()` function. The `fields` returned by the `useFieldArray` hook does seem to display the correct value at first, but then it gets overridden when the field array updates.

### What browsers are you seeing the problem on?

Edge, Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
broken csb link

**Comment by zjsng** [comment]
> broken csb link

My bad, forgot to update the perms. Should be good now!

**Comment by bluebill1049** [comment]
thanks will check it out later.

**Comment by bluebill1049** [comment]
can you clean up your codesandbox, ideally just use native input to reproduce the issue. also the demo works as expect as well.

**Comment by zjsng** [comment]
I've updated the CodeSandbox to use the native inputs instead. 

As for the demo, what I meant was the value returned from the `watch()` function. After removing 2 elements, and then appending back another 2 elements, the values on these 2 new elements should have been what was passed into the `append()` function, which is an object `{ select: 10 }`. However, `watch()` shows that the new values are still `20` for the 2nd element, and `30` for the 3rd element.

**Comment by bluebill1049** [comment]
```tsx
import { useForm, useFieldArray, FormProvider } from "react-hook-form";

function App() {
  const { control, watch } = useForm({
    defaultValues: {
      textField: "",
      selectionArray: [{ select: '10' }, { select: '20' }, { select: '30' }],
    },
  });
  const { fields, append, remove } = useFieldArray({
    name: "selectionArray",
    shouldUnregister: true,
    control,
  });

  console.log(fields);
  console.log('watch', watch())

  const appendHandler = () => {
    append({ select: '10' });
  };

  const removeHandler = () => {
    const lastFieldIndex = fields.length - 1;
    remove(lastFieldIndex);
  };

  return (
    <form>
      <button type={"button"} onClick={appendHandler}>Append</button>
      <button type={"button"} onClick={removeHandler}>Remove last</button>
      <div>
        {fields.map((field, index) => (
          <input
            key={field.id}
            name={`selectionArray.${index}.select`}
            defaultValue={field.select}
          />
        ))}
      </div>
    </form>
  );
}

export default App;

```

working version, useFieldArary doesn't work with useForm shouldUnregister as it would conflict when input get unmountd.

**Comment by zjsng** [comment]
That works, thanks. Just wondering though, what happens if I need both the `shouldUnregister` on the form level and on the array field level?
