### ISSUE TITLE
issue: Files prepended to list are not indicated as 'dirty'

### ISSUE THREAD

**Issue by onionhammer** [react-hook-form/react-hook-form#11697]
### Version Number

7.43.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/frosty-drake-dlyt2l?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu020mvg0007356g347jpjg7%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu020mvg0003356g1z33t3v5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu020mvg0004356gbsmme2nt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu020mvg0006356gdn4rl1r7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu020mvg0003356g1z33t3v5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu020mvg0002356gdmtejn6x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clu020mvg0003356g1z33t3v5%2522%252C%2522activeTabId%2522%253A%2522clu020mvg0002356gdmtejn6x%2522%257D%252C%2522clu020mvg0006356gdn4rl1r7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu020mvg0005356gwv67aovn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu020mvg0006356gdn4rl1r7%2522%252C%2522activeTabId%2522%253A%2522clu020mvg0005356gwv67aovn%2522%257D%252C%2522clu020mvg0004356gbsmme2nt%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu020mvg0004356gbsmme2nt%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

1. Select a file in the 'Add file' input, you should see the first and only element as dirty below
2. Click "Submit", which resets the form (this is where the file would be uploaded to a server)
3. Select another file with the "Add file" input - this is calling **PREPEND** not **APPEND**

You can see from the result at this point that the 2nd item in the array is dirty, and the first item is NOT dirty, even though the opposite is true.

![image](https://github.com/react-hook-form/react-hook-form/assets/969938/ea5f0bb6-f0b8-4d8c-bb6e-26e4b72b4525)

### Expected behaviour

The first item in the array should be dirty, since the 2nd item is prepended to the form not appended.

### Relevant log output

```shell
NA
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://react-hook-form.com/docs/useform/formstate

> Do not support custom object, Class or File object.
