### ISSUE TITLE
issue: Nested form fields reflect as `isDirty` after reset

### ISSUE THREAD

**Issue by SangJunBak** [react-hook-form/react-hook-form#11690]
### Version Number

7.48.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/late-browser-nyllvc

### Steps to reproduce

1. Set `defaultValues` as an object with a nested array, call it `nestedArray`
2. `getFieldState("nestedArray").isDirty` should be false
3. Reset in a `useEffect` via:
```js
React.useEffect(() => {
    reset(DEFAULT_FORM_STATE, {
      keepDefaultValues: true,
      keepDirty: false,
    });
  }, [formState.isDirty]);
```
4. `getFieldState("nestedArray").isDirty` is now true but `formState.dirtyFields` is:
```js
{
  nestedArray: []
}
```
instead of an empty object

### Expected behaviour

There are two things that are expected:

1. `getFieldState("nestedArray").isDirty` in step 4 should be false 
2. `keepDirty:false` should just clear the `dirtyFields` object. Weirdly it works when you use `keepValues` instead of `keepDirtyValues`. 

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
{
    "formArray": [
        false,
        false
    ]
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`getFieldState` only get field by name, please refer to the doc.

**Comment by SangJunBak** [comment]
@bluebill1049 Ah sorry, I don't quite understand! `nestedArray` is the name of the field!
