### ISSUE TITLE
issue: submit button with the 'name' and 'value' properties does not function as expected.

### ISSUE THREAD

**Issue by Tilican** [react-hook-form/react-hook-form#11696]
### Version Number

^7.50.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/tender-borg-v9mf5w?file=%2Fsrc%2FApp.tsx

### Steps to reproduce

In a full HTML form, when I use button 1 or button 2, I get a different value for the key 'test' in console.

### Expected behaviour

Have a "extra" key on data handled by onSubmit but with the right value of the button clicked

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
use handleSubmit(callback) function's second argument to get the event.

`callback(data, event)`
