### ISSUE TITLE
Inside custom element: React-hook-form leads to "Invalid hook call"

### ISSUE THREAD

**Issue by secretlifeof** [react-hook-form/react-hook-form#1170]
**Describe the bug**
I am trying to use react-hook-form inside a **custom element**, but it errors with **"Invalid hook call..."** Inside the custom element I am using **Preact**. React-hook-form works with Preact/compat so that should not be the issue. I am using the custom element (fari-lari) inside a Nextjs project. Using useState, useCallback, useRef, useEffect hooks inside the custom element does not cause any errors.

**To Reproduce**
1. git clone https://github.com/secretlifeof/react-hook-form-ce-issue.git
2. git clone https://github.com/secretlifeof/react-hook-form-ce-issue-front.git
3. cd react-hook-form-ce-issue && yarn && yarn build && yarn link && cd ..
4. cd react-hook-form-ce-issue-front && yarn && yarn link farilari
5. yarn dev

**Codesandbox**
https://codesandbox.io/s/react-hook-form-invalid-hook-issue-mpi4i

**Expected behavior**
Using react-hook-form without errors. 

**Desktop (please complete the following information):**
 - OS: OsX
 - Browser: Chrome, Safari

"formik": "^2.1.4",
"goober": "^1.7.1",
"htm": "^3.0.3",
"preact": "^10.3.3",
"preact-custom-element": "^3.0.0",
 "react-hook-form": "^4.10.1"

Running npm ls react only returns Version 16.13 inside the Nextjs project. I am experiencing the same problem with the useFormik hook from Formik.

Has anybody experienced a similar problem?

**Comment by bluebill1049** [comment]
please provide a codesandbox for the issue.

**Comment by secretlifeof** [comment]
@bluebill1049 Yes off course.

Here it is:
https://codesandbox.io/s/react-hook-form-invalid-hook-issue-mpi4i

**Comment by bluebill1049** [comment]
This issue is not related to this lib:

```
×
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

**Comment by secretlifeof** [comment]
The problem does not occur when only using hooks. I have testet useEffect, useState, useCallback, useRef. It occurs when using **useForm** from react-hook-form. Do you have any suggestions? I also tried updating react-hook-form to version 5.0.1 without change.

**Comment by bluebill1049** [comment]
I have seen this issue before (not with this lib) which is basically what the react errors are. check if you have duplicated react or not invoke custom hook in the correct order.

**Comment by secretlifeof** [comment]
@bluebill1049 I do not mean to be impolite, but the **only** hook that is invoked is **useForm** from react-hook-form. React is not duplicated. As seen in the sandbox only 1 version is installed. Can you please reopen this issue until it is resolved?

**Comment by bluebill1049** [comment]
I am more than happy to solve issues related to the library as you can see I have done this in this past. Check issues logs. however this is not related to this library. I would recommend you to try out other hooks library and see if u can reproduce the same behaviour. If that’s the case, you can narrow down the issue.

**Comment by secretlifeof** [comment]
Thank you very much for your help. I will post an issue to Preact and see if they can help.
