### ISSUE TITLE
issue: useFieldArray fields member 'id' prop type broken if data specifies 'id' prop with type not string

### ISSUE THREAD

**Issue by cjp-psl** [react-hook-form/react-hook-form#11701]
### Version Number

7.51.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/distracted-hopper-hqjv5w

### Steps to reproduce

If useFieldArray targets a prop with a data type that includes an 'id' prop that is NOT of type 'string', the resulting field array members 'id' prop result type is 'never'

e.g.
```ts
type MyArrayItem ={ 
   id: number
   text: string
}

type MyForm = {
   arrayField: MyArrayItem[]
}

const { control } = useForm...

const { fields } = useFieldArray(control, 'arrayField')

const firstId = fields[0].id

//firstId type is 'never'!!
```

This can currently be worked around by using the 'keyName' option on useFieldArray to shift the RHF to use a different prop for the generated id, but that option is apparently due to be deprecated...

So ideally the type definition resolution needs fixing to support numeric ids, unless there is a pattern or other alternative approach that can be used (or keyName will remain an option).

Related discussion on keyName deprecation [here](https://github.com/orgs/react-hook-form/discussions/8935#discussioncomment-4002113)

### Expected behaviour

Id prop type matches original data type

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Would you mind updating your codesandbox: it's currently inaccessible.

**Comment by cjp-psl** [comment]
Apologies, link/permissions are updated now.

**Comment by bluebill1049** [comment]
use `keyName`
