### ISSUE TITLE
issue: Dirty fields not changing after values have been updated via the values prop in useForm.

### ISSUE THREAD

**Issue by manualy** [react-hook-form/react-hook-form#11709]
### Version Number

7.51.1

### Codesandbox/Expo snack

[CodeSandbox.io](https://codesandbox.io/p/sandbox/lucid-sound-932m9j?file=%2Fsrc%2FApp.tsx%3A18%2C18&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu2m3e970006356jjnhjbfxm%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu2m3e970002356jbxaznjgc%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu2m3e970003356j03jhihmu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu2m3e970005356j0uixde6m%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu2m3e970002356jbxaznjgc%2522%253A%257B%2522id%2522%253A%2522clu2m3e970002356jbxaznjgc%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu2m44s2004w356jpunodfh0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A18%252C%2522startColumn%2522%253A18%252C%2522endLineNumber%2522%253A18%252C%2522endColumn%2522%253A18%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clu2m44s2004w356jpunodfh0%2522%257D%252C%2522clu2m3e970005356j0uixde6m%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu2m3e970004356j4ntpithj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu2m3e970005356j0uixde6m%2522%252C%2522activeTabId%2522%253A%2522clu2m3e970004356j4ntpithj%2522%257D%252C%2522clu2m3e970003356j03jhihmu%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu2m3e970003356j03jhihmu%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Initialize useForm with defaultValues and values prop.
2. Logged defaultValues differ from form's values, yet the isDirty state isn't updated.

Additional bug!
1. Change the value of the input manually
2. Click the update value button
3. Value doesn't get updated.

### Expected behaviour

I've observed an inconsistency in the behavior of the `values` prop in relation to the `isTouched` and `isDirty` props, which seems puzzling considering that defaultProps support asynchronous values. The` setValue` API offers developers the ability to modify these props with `{shouldDirty: true, shouldTouch: true}`, yet it appears that changes to the values prop do not consistently affect them.

Additionally, I've encountered another issue with the `values` prop. When I modify the state of the data passed to `values`, it doesn't reflect the changes in the input fields, particularly after a user has manually altered the field.

This problem arises prominently in my case, where I'm working with a multi-step form and encountering difficulties with the skip button functionality. Ideally, the skip button should become available to the user when the form values deviate from the default ones. Could someone please provide guidance on how to address this issue?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
when `data` arrived, it will update `defaultValues` inside the control, this is expected behaviour and calling the reset function internally.
