### ISSUE TITLE
Controller value reset after remove

### ISSUE THREAD

**Issue by igo** [react-hook-form/react-hook-form#1172]
**Describe the bug**
Modified value of Controller in list (useFieldArray) is not preserved after calling `remove`

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-vqedy
2. Click on 'append'
3. Modify value of both inputs
4. Click 'delete' to remove one item
5. Changes in remaining input you made disappeared

**Expected behavior**
5. changes to input are preserved

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-usefieldarray-l40b9 fixed thanks for reporting.
