### ISSUE TITLE
issue: Changing nested defaultValues before rendering Controller causes error: Cannot set properties of undefined (setting 'mount')

### ISSUE THREAD

**Issue by CyanoFresh** [react-hook-form/react-hook-form#11729]
### Version Number

7.49.3

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/laughing-leaf-stpvl6

### Steps to reproduce

1. Go to codesandbox
2. Click on Nested checkbox
3. See error

### Expected behaviour

No error expected

Adding 
```
  useController({
    control,
    name: "name",
  });
```
to the component fixes the error. [Sandbox link](https://codesandbox.io/p/sandbox/laughing-leaf-forked-36w67w?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clua0qg5d00063b6k1dwuhree%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clua0qg5d00023b6ko4epsk6a%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clua0qg5d00033b6k7ti7htpp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clua0qg5d00053b6koce0x6t7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clua0qg5d00023b6ko4epsk6a%2522%253A%257B%2522id%2522%253A%2522clua0qg5d00023b6ko4epsk6a%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clua1d5xe00023b6kpn7dyl3w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A57%252C%2522startColumn%2522%253A22%252C%2522endLineNumber%2522%253A57%252C%2522endColumn%2522%253A22%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clua1d5xe00023b6kpn7dyl3w%2522%257D%252C%2522clua0qg5d00053b6koce0x6t7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clua0qg5d00043b6ke4ie0u3s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clua0qg5d00053b6koce0x6t7%2522%252C%2522activeTabId%2522%253A%2522clua0qg5d00043b6ke4ie0u3s%2522%257D%252C%2522clua0qg5d00033b6k7ti7htpp%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clua0qg5d00033b6k7ti7htpp%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

This issue is probably related to https://github.com/react-hook-form/react-hook-form/issues/5492
As I see the check for `_f` were removed, that's why error is throwing

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Uncaught TypeError: Cannot set properties of undefined (setting 'mount')
    at t (/node_modules/react-hook-form/dist/index.cjs.js:1:4068)
    at eval (/node_modules/react-hook-form/dist/index.cjs.js:1:4249)
    at safelyCallDestroy (/node_modules/react-dom/cjs/react-dom.development.js:22932:5)
    at commitHookEffectListUnmount (/node_modules/react-dom/cjs/react-dom.development.js:23100:11)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (/node_modules/react-dom/cjs/react-dom.development.js:25098:11)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (/node_modules/react-dom/cjs/react-dom.development.js:25048:5)
    at commitPassiveUnmountEffects_begin (/node_modules/react-dom/cjs/react-dom.development.js:24956:11)
    at commitPassiveUnmountEffects (/node_modules/react-dom/cjs/react-dom.development.js:24941:3)
    at flushPassiveEffectsImpl (/node_modules/react-dom/cjs/react-dom.development.js:27038:3)
    at flushPassiveEffects (/node_modules/react-dom/cjs/react-dom.development.js:26984:14)
    at eval (/node_modules/react-dom/cjs/react-dom.development.js:26769:9)
    at workLoop (/node_modules/scheduler/cjs/scheduler.development.js:266:34)
    at flushWork (/node_modules/scheduler/cjs/scheduler.development.js:239:14)
    at MessagePort.performWorkUntilDeadline (/node_modules/scheduler/cjs/scheduler.development.js:533:21)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
don't support such usage at this stage.
