### ISSUE TITLE
issue: Form fields become unresponsive after multiple submissions with reset

### ISSUE THREAD

**Issue by TakaoNarikawa** [react-hook-form/react-hook-form#11725]
### Version Number

7.51.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/unruffled-elgamal-zc2wt4?file=%2Fsrc%2FApp.tsx

### Steps to reproduce

1. Input some data into a form field.
2. Click the "Submit" button twice (the issue does not manifest after the first click).
3. Attempt to enter data into the input field again. The input will not reflect the new value.

### Expected behaviour

The form's input fields should remain responsive after any number of submit actions, allowing for continuous input and form operations without hindrance.

### Additional Context

The primary reason for calling reset(values) post-submission is to revert isDirty to false. The discovery that this issue does not occur in version 7.4.1 but does in 7.51.2 may help narrow down the changes leading to this behavior. 

Furthermore, it is important to note that this issue occurs specifically when control is passed as a prop to a component wrapped in `React.memo`. Additionally, this issue does not occur when using `reset(values, { keepValues: true })`.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
missing `defaultValues` or `defaultValue`

**Comment by JosephKav** [comment]
I'm also encountering this after upgrading from `7.50.1` to `7.51.*`. I didn't use `defaultValues` before but will have to look into using them now
