### ISSUE TITLE
issue: useFormContexts error object empty desipite validation invalidating the form

### ISSUE THREAD

**Issue by Tackgnol** [react-hook-form/react-hook-form#11731]
### Version Number

7.51.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/cool-lalande-8n2kxp

### Steps to reproduce

1. Go into the input
2. Type in more than 5 characters 
3. See console output
4. The formState is invalid, but the error object is empty. 

### Expected behaviour

The error object should be populated with the error message supplied in the validation object. 

Thru my investigations I noticed that if I update the change handler to 

```js
const handleChange = async (e) => {
  await trigger(fieldName)
  await onChange(e)
}
```
Where `onChange` and `trigger` come from `react-hook-form`. 
Then the errors object gets updated properly. 

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
validation errors focus on field level, while isValid will always trigger the entire form value.

**Comment by Tackgnol** [comment]
> validation errors focus on field level, while isValid will always trigger/return the entire form value.

So what you are saying is triggering the validation is a proper approach, or is there a different way to access this this validation error to show it in the `TextInput` ? I may have missed something in the docs, but I did go thru them multiple times :o.
