### ISSUE TITLE
issue: Dirty array fields get reset even though `keepDirtyFields: true`

### ISSUE THREAD

**Issue by szilard-dobai** [react-hook-form/react-hook-form#11748]
### Version Number

7.51.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/agitated-jepsen-43q6ln?file=%2Fsrc%2FApp.tsx

### Steps to reproduce

1. Change the "City" input
2. Change the first input under "People"
3. Click on "Trigger new data" button
4. See both inputs under "People" reset even though keepDirtyValues is set to true.

### Expected behaviour

All dirty fields should retain their values upon `values` update, however this only applies to the simple fields (in this case `"city"` of type `string`) but not to more complex ones (such as `"people"`, an array of objects).

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please read the doc and refer on how to use useFieldArray. there is not even a `register`

**Comment by szilard-dobai** [comment]
@bluebill1049 Thanks for replying, but unfortunately I'm still having problems understanding how you're supposed to be using these functions. Maybe my initial code sandbox example was oversimplified, but [this](https://codesandbox.io/p/sandbox/agitated-jepsen-43q6ln?file=%2Fsrc%2FApp.tsx) one is closer to what I'm actually trying to do.

In short, I want to display one single set of inputs at a time for each object inside my array field and the user can navigate through them using 'next'/'previous' buttons, as well as having a scrollable overview of the entire array on the side (omitted in the example).

How and when am I supposed to call `register`? Calling it once for the entire `"people"` array field (like in the example) acts as if the entire field becomes dirty once I type something in 1 single input even though I did not touch the others, meaning that clicking the `trigger new data` button doesn't update all expected members of the `"people"` array.

Calling `register(`people.${currentIndex}.name)` and destructuring the result in each `<input />` isn't really an option for me because I'm using custom and conditional components that aren't actually HTML inputs...
