### ISSUE TITLE
issue: [DRAFT] using the new version of the library crashes the App component

### ISSUE THREAD

**Issue by goatandsheep** [react-hook-form/react-hook-form#11742]
### Version Number

7.51.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/epic-dawn-vp4r7w?file=%2Fsrc%2FApp.tsx%3A31%2C32

### Steps to reproduce

We've been using the library with little to no issues and up until 7.50.1, everything was working fine. Since we tried upgrading to 7.51.2, any component where we're using `useFieldArray` crashes the whole component. I'm still working on the reproduction project, but I wanted to start the conversation.

### Expected behaviour

In 7.50.1 and before, it didn't crash the component.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
(WIP) Output component is undefined.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
any update on this issue?
