### ISSUE TITLE
v6 React Dependency Query

### ISSUE THREAD

**Issue by zthng** [react-hook-form/react-hook-form#11744]
**Is your feature request related to a problem? Please describe.**
My workplace uses react-hook-form v6, and the effort to migrate is too big. However, we have budgeted hours to migrate to React 18 instead.

**Describe the solution you'd like**
Allow and include React 18 as a dependency for v6.

**Describe alternatives you've considered**
Migrating to v7, however we have very complex forms and multiple teams working - some of which have other business priorities. As such, it is more difficult to migrate to react-hook-form v7 than it is to React 18.

**Comment by bluebill1049** [comment]
there will be issue with v6 with stict mode, don't think we will have time and effort to manage that.

**Comment by zthng** [comment]
@bluebill1049  - thank you for the swift reply! 

Could I perhaps ask for an example that would trigger such an issue?
