### ISSUE TITLE
Controller value reset after remove

### ISSUE THREAD

**Issue by vensauro** [react-hook-form/react-hook-form#1174]
**Describe the bug**
Modified value of Controller in list (`useFieldArray`) is not preserved after calling `remove`, when the component use a complex value, like objects  

**To Reproduce**
1. Go to [codesandbox](https://codesandbox.io/s/react-hook-form-usefieldarray-pvyj8)
2. Click on append
3. select an value in the select input, and an date in the date picker
4. click on remove in the first value of the `useFieldArray`
5. the values are gone
6. see in the console that the component received another value( empty string or undefined)

**Codesandbox link**
[codesandbox](https://codesandbox.io/s/react-hook-form-usefieldarray-pvyj8)

**Expected behavior**
don't lose values of the component

Obs: yes, this issue is similar to the issue #1172, but i am having this problem before, and this commit https://github.com/react-hook-form/react-hook-form/commit/1bfb7c10d6f09fc188c978eb4e9629af00d7b084 dont solved the problem

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-usefieldarray-u7rxf

if you have remove those `defaultValue` on the controller. it should work.

**Comment by vensauro** [comment]
it is expected to work, but continues not working, the diff is that the date component set the today date when receive undefined on value :/
(Uou, i have not seen that the item object have a default value, brilliant this)

**Comment by bluebill1049** [comment]
@vensauro it still having issue?

**Comment by vensauro** [comment]
yes :confused:

**Comment by bluebill1049** [comment]
what's not working? 

https://codesandbox.io/s/react-hook-form-usefieldarray-u7rxf

let me know which part and possible take a screenshoot as well. thanks

**Comment by Amtron** [comment]
I'm experiencing the same issue with values not being preserved.

**Comment by bluebill1049** [comment]
@Amtron can you take a look the CSB and let me know the steps to reproduce?

**Comment by Amtron** [comment]
1) click append
2) set the dropdown to something new on the new field array
3) set the date to 31st Mar (make sure to click 'OK' to set the date) on the new field array
While doing this check the console values; all the items date are undefined and if you check the '[Object]' it only has name, age and id attributes. I would expect at lease one of the field arrays to have a date because it was set.

4) click remove
You should notice that we still do not have any dates.

5) click submit
Check the submit object and the values are correct. This is unexpected behaviour.

**Comment by bluebill1049** [comment]
@Amtron i have removed the console.log for date, it's not implemented corrected from the original CSB.

**Comment by bluebill1049** [comment]
I have update the CSB again, the original CSB is very confusing to me...

**Comment by Amtron** [comment]
Which CSB are we using for this?

**Comment by bluebill1049** [comment]
This is mine: https://codesandbox.io/s/react-hook-form-usefieldarray-u7rxf

**Comment by Amtron** [comment]
1) set the date of the first field array
2) append new field array
check console - you should notice that although we set the date on the first field array in the data the date attribute is undefined

**Comment by bluebill1049** [comment]
because it's empty: 
```
defaultValues: {
      items: [
        {
          name: "",
          age: 10
        }
      ]
    }
```

MUI probably showing a default.

**Comment by vensauro** [comment]
Okay, i see that the CSB that i picked by template, use the name `test` in the `useFieldArray`, and when change this the date field works :+1:

**Comment by bluebill1049** [comment]
thanks for the update @vensauro

**Comment by vensauro** [comment]
i make some test using a custom component that accepts array as value and all worked nice, i suppose that the problem in the select is with the component or something with reference, thanks by the attention @bluebill1049

**Comment by bluebill1049** [comment]
my pleasure @vensauro feel free to follow up with more questions ❤️

**Comment by vensauro** [comment]
i don't see one example in the website using the `defaultValue` in `Controller` using the fields value like: `defaultValue={field.date}`, this has any more behavior? i can try make a PR (I'm not sure if i can do this, but I really want to help)

**Comment by bluebill1049** [comment]
🙏 you can submit a PR at our website repo! ❤️ if the doc is not having the correct example, feel free to update it and get your name on the contribution list 👍
