### ISSUE TITLE
After submitting form, any subsequent typing gives `Uncaught (in promise) TypeError: Cannot convert undefined or null to object` error

### ISSUE THREAD

**Issue by garyking** [react-hook-form/react-hook-form#1175]
Here's my code, in [this sandbox](https://codesandbox.io/s/recursing-rosalind-f7swd).

Submit the form (you need to type something in the second input box). Then type something in the second input box, after submission. There will be a console error of `Uncaught (in promise) TypeError: Cannot convert undefined or null to object`.

How can this be fixed? Or is this simply a bug of `react-hook-form`?

**Comment by bluebill1049** [comment]
i couldn't reproduce this issue with your CSB.

**Comment by garyking** [comment]
You sure? I was able to reproduce it in a private window. I've made a video below.

![react-hook-form error](https://user-images.githubusercontent.com/343940/76187132-ed317f00-61aa-11ea-9cb1-6d60d18a949d.gif)

**Comment by bluebill1049** [comment]
thanks patched: https://codesandbox.io/s/affectionate-dhawan-8xzgv

**Comment by garyking** [comment]
Thanks, it indeed seems to be fixed in your link.

Considering that this bug is new, I must be doing something in my code that is uncommon? Is there a better way to write my code, that would have avoided this bug completely?

**Comment by bluebill1049** [comment]
it's due to `name="example[1]"` which convert errors into array shape.

**Comment by Cold-A-Muse** [comment]
Upgrading tho version 5.0.3 worked for me as well. Thanks :)
