### ISSUE TITLE
issue: Problem with focus precedence

### ISSUE THREAD

**Issue by maazakn** [react-hook-form/react-hook-form#11756]
### Version Number

7.51.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/polished-resonance-pvx6y9?file=%2Fsrc%2FApp.tsx

### Steps to reproduce

1. Go to [Link](https://codesandbox.io/p/sandbox/polished-resonance-pvx6y9?file=%2Fsrc%2FApp.tsx)
2. Click on the 'Submit' button
3. See error

### Expected behaviour

I've noticed that react-hook-form doesn't trigger focus on fields in the correct order. I'm using both the Controller and register, but the field wrapped with the Controller is not prioritized for focus.

Let me know if there is any focus precedence or Controller and register will work in a different way.

Thanks...

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
yea we can't guarantee the focus order, first register first focus.

**Comment by maazakn** [comment]
@bluebill1049 In the example above, I used a controller first, and then I used register. My understanding is that fields using the register will maintain a separate focus queue (FIFO), and the controller will use a different one.
