### ISSUE TITLE
issue: (in my project only) infinite rerender when using errors from formState and errors in hook configuration 

### ISSUE THREAD

**Issue by MrOxMasTer** [react-hook-form/react-hook-form#11758]
### Version Number

7.51.2

### Codesandbox/Expo snack

https://github.com/MrOxMasTer/shopco/commit/db82dc69a55e704c663590811564ab63e3e2f0de

### Steps to reproduce

1. Go to 'http://localhost:3000/auth/signup'
2. Dev mode

### Expected behaviour

Shouldn't cause a re-rendering

I can't recreate the situation because I don't understand exactly what the problem is, so I'm showing my project.

Maybe it's because I'm using next.js, but I do not know.

form State and errors conflict in my configuration. And now I will give you screenshots from my project

![image](https://github.com/react-hook-form/react-hook-form/assets/59291123/4a92d564-3207-4d82-b95f-32538ab96f86)
![image](https://github.com/react-hook-form/react-hook-form/assets/59291123/375701e5-0525-4fe0-b6e1-e03d9416af33)

But as soon as I remove one of the fields. For example, in the configuration I comment, then all the errors disappear immediately
![image](https://github.com/react-hook-form/react-hook-form/assets/59291123/70669e4c-9841-466e-894c-792d88961e62)
![image](https://github.com/react-hook-form/react-hook-form/assets/59291123/3573b616-f1d1-4e71-a304-ed514aab9df0)

Even though I removed absolutely all fields from the form and everything that could do anything by leaving the hook, I still get the error
![image](https://github.com/react-hook-form/react-hook-form/assets/59291123/ddd8ccf9-23fe-48f5-bc4e-ac88adac0200)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please stop spamming issue here, if `errors` props doesn't work fo you, just use `setError` API plz, like i mention before `error` props will keep get update if you don't `memo` it.

**Comment by bluebill1049** [comment]
you can refer to the source code here: https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L130 hope this explains.

**Comment by MrOxMasTer** [comment]
> please stop spamming issue here, if `errors` props doesn't work fo you, just use `setError` API plz, like i mention before `error` props will keep get update if you don't `memo` it.

Spamming happens because you don't reply to old issues when I comment on your reply.

I am using 2 fields. I don't understand what it is about, but now realised it is about props.

Please write about it in the documentation that you need to memoise this object, because it is written in 4 lines about it.

It just seemed to me that this functionality should be implemented inside hook, and this way it looks strange

**Comment by bluebill1049** [comment]
> Spamming happens because you don't reply to old issues when I comment on your reply.

look, i don't own you anything. This is open source which i maintain for free with my free time.
