### ISSUE TITLE
issue: `useWatch` return value does not match `watch` when used with `useFieldArray`

### ISSUE THREAD

**Issue by razh** [react-hook-form/react-hook-form#11774]
### Version Number

7.51.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/usefieldarray-and-usewatch-kqnclm

### Steps to reproduce

1. Open up developer console.
2. Click **Append**.
3. There are two sets of `console.log` calls.

   ```tsx
   // First render after append
   watch {items: Array(1)}
   useWatch {items: Array(0)}

   // Second render
   watch {items: Array(1)}
   useWatch {items: Array(1)}
   ```

4. Select **Primitive** to watch a string field.
5. Type in `a`.
6. There's only one set of `console.log` calls.

   ```tsx
   watch {name: 'a'}
   useWatch {name: 'a'}
   ```

Field array|Primitive
:-|:-
![Screenshot 2024-04-11 at 12 24 56 PM](https://github.com/react-hook-form/react-hook-form/assets/240770/ff120e5f-1588-4f9f-a19e-ed5e20751296)|![Screenshot 2024-04-11 at 12 25 06 PM](https://github.com/react-hook-form/react-hook-form/assets/240770/6a60ad76-3432-491c-8264-82d7984a695c)

### Expected behaviour

`useWatch` should return the same value as `watch` in the first render after clicking **Append**.

When watching a primitive value instead of a field array, this behaves as expected.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
execution order matters with a hook, subscribe only gets fired at useEffect level.
