### ISSUE TITLE
Register options ignore required = false and minLength = 0

### ISSUE THREAD

**Issue by etc-tiago** [react-hook-form/react-hook-form#1177]
While using a form with more than 50 fields, I noticed that the react hook form ignores the `required: false` and points out an error like` min`.

My form input is
```ts
const ProfessionField: FC<ITextInput> = ({ error, value, register }) => {
    const name = 'profession';
    const type = 'text';
    const className = `input-form${error ? ' red' : ''}`;
    const placeholder = 'Profissão';
    return (
        <Fragment>
        <ErrorIndicator showError={error} />
        <label>{placeholder}</label>
        <input
            {...{
            name,
            type,
            className,
            placeholder,
            defaultValue: value,
            ...autocomplete,
            ref: register({ required: false, maxLenght: 32 }),
            }}
        />
        </Fragment>
    );
};
```
**Note**: 
- The `error` reported as a parameter is boolean and checks if the field informed has errors.
- The `register` is form-hook-form register

In the console:
<img width="424" alt="Captura de Tela 2020-03-09 às 08 20 11" src="https://user-images.githubusercontent.com/33164463/76208959-837f9800-61df-11ea-9aea-16aa6db590da.png">

**Comment by bluebill1049** [comment]
please supply a CSB for me to reproduce.

**Comment by etc-tiago** [comment]
While trying to reproduce an example, I realized that a validation by `validationSchema` had been applied, so it is not a bug but a duplicate of verification. I ask you to disregard this issue.
