### ISSUE TITLE
issue: useFieldArray fields is not updated when input changes

### ISSUE THREAD

**Issue by HamadTheIronside** [react-hook-form/react-hook-form#11788]
### Version Number

7.51.3

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/late-leftpad-snncpx

### Steps to reproduce

1. Open Codesandbox
2. Edit the inputs
3. You will see that value from watch is updated, but not the `fields` from useFieldArray.

### Expected behaviour

I expect to have `fields` from `useFieldArray` to have the same value as `watch` (excluding the key field). I saw that https://github.com/react-hook-form/react-hook-form/issues/1564 also mentioning this, it's been said that `setValue` doesn't trigger re-render and `watch` should have been used. In the example I provided, we see that even the component is re-rendering, `fields` still not updated with the latest value from the form.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
expected, if fields gets update you will have constant re-render while user update the input.
