### ISSUE TITLE
issue: useConroller creates empty objects for nested fields

### ISSUE THREAD

**Issue by andykog** [react-hook-form/react-hook-form#11789]
### Version Number

7.51.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/blissful-driscoll-jtn883

### Steps to reproduce

- Invoke `useController({name: 'some.nested.field'})`
- Check values in `form.getValues()`

Result: values contain `{some: {nested: {}}}`

### Expected behaviour

Invoking useController shouldn't modify form state unless received input from user

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
you should provide a `defaultValues` or `defaultValue` to start with for a controlled input.

https://react-hook-form.com/docs/usecontroller

<img width="940" alt="Screenshot 2024-04-19 at 10 14 30 am" src="https://github.com/react-hook-form/react-hook-form/assets/10513364/7d1f0c86-a618-421f-a2a2-3d0f9cad5350">
