### ISSUE TITLE
issue: validate rules shift errors

### ISSUE THREAD

**Issue by Kirdock** [react-hook-form/react-hook-form#11793]
### Version Number

7.51.3

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-18-typescript-forked-7kqrl4?file=%2Fsrc%2Findex.tsx

### Steps to reproduce

1. Go to my [Codesandbox example](https://codesandbox.io/p/sandbox/react-18-typescript-forked-7kqrl4?file=%2Fsrc%2Findex.tsx)
2. Click two times on "Add array element"
3. See that as intended a "had duplicates" error is shown
4. Select "1" in the dropdown
5. Clear the input
6. See that as intended the required error is shown
8. Click on "Add array element"
9. See the bug: The errors from element 1 shifted to element 0

If the "validate" rule of the array is removed, the shift of the errors does not occur.
Video:

https://github.com/react-hook-form/react-hook-form/assets/11599148/4da8e08d-5887-40a6-afce-fa523389653b

There is actually another bug in the sample I provided. As you can see on row 29-30 in `Form.tsx`, I added two state-updates as a workaround. The problem is, if the element changes right away, the next selected array element gets the values of the previous selected one.
Steps:
1. Comment out row 29 in Form.tsx
2. Click two times on "Add array element"
3. Select "1" in the dropdown
4. Change the value
5. Select "0" in the dropdown
6. See that the input field does not change

Video:

https://github.com/react-hook-form/react-hook-form/assets/11599148/7f342377-1aed-4089-8688-5a68385db6ef

### Expected behaviour

The errors don't shift

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
why there is no input registered?

**Comment by Kirdock** [comment]
the input is dynamically registered in the `Sidebar.tsx`

**Comment by Kirdock** [comment]
Any updates on this?

**Comment by JardelCheung** [comment]
@bluebill1049 Hello.
I recently submitted a pull request with this issue. When you have a moment, could you please review it? Your feedback would be greatly appreciated.

https://github.com/react-hook-form/react-hook-form/pull/12033#issuecomment-2178354661

**Comment by Kirdock** [comment]
Looks like this resolves the issue, thanks!
