### ISSUE TITLE
Issue: Error doesn't clear even when isValid state is 'true'

### ISSUE THREAD

**Issue by IdoBouskila** [react-hook-form/react-hook-form#11795]
### Version Number

7.51.3

### Codesandbox/Expo snack

https://stackblitz.com/edit/vitejs-vite-nofhit?file=src%2FApp.tsx

### Steps to reproduce

1. Type a number on `numberOne` field.
2. Go to  `numberTwo` field and type a number that is lower than `numberOne` and you will see an error message.
3. Go to `numberOne` field and type a number that is lower than `numerTwo`
4. The `isValid` state will now be `true`, but the error from step two won't go awaythe 

### Expected behaviour

I expect the errors to clear when the form `isValid` state is `true`

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
native input only return `string`, unless you `valueAsNumber`: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement

**Comment by IdoBouskila** [comment]
> native input only return `string`, unless you `valueAsNumber`: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement

Hey @bluebill1049 thanks for your reply,
It doesn't seem to be related to the issue. I already converted it to a number, but that is not the issue, the issue is about the validation when it is dependent on two fields, it only clears the error when the `onChange` event is triggered from the input that is the validation is registered inside even when the `isValid` form state is `true`.

**Comment by IdoBouskila** [comment]
@bluebill1049 Btw, Important to note: It makes sense that the validation only runs on the input where it's registered, but it's weird that `isValid` changes.

**Comment by IdoBouskila** [comment]
@bluebill1049 Hi, I would appreciate an answer 🙏🏼
