### ISSUE TITLE
issue: Controller rules.pattern doesn't apply new value without explicit undefined

### ISSUE THREAD

**Issue by PetrBorisov** [react-hook-form/react-hook-form#11796]
### Version Number

7.51.3

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/thirsty-goldstine-n9rfhv?file=%2Fsrc%2FApp.tsx

### Steps to reproduce

1. Go to [codesandbox example](https://codesandbox.io/p/sandbox/thirsty-goldstine-n9rfhv?file=%2Fsrc%2FApp.tsx)
2. Type "message" into input
3. Click "switch pattern" button
4. Type "message" into input
5. See error
<img width="242" alt="image" src="https://github.com/react-hook-form/react-hook-form/assets/4943388/e3942594-7f99-48c2-93d4-21abdaa0810a">

Problem here is that after click on "switch pattern" I start to provide `rules = {{ required: true }}` property to controller without any explicit `undefined` for rules.pattern and Controller use "cached" value from previous `rules` property value

---------------
Workaround 1
```
rules={{
  ...rulesToUse,
  pattern: rulesToUse.pattern,
}}
```
--------------
Workaround 2 
```
const rules2 = {
  // pattern: undefined,  <---- uncomment this line
  required: true,
};
```
--------------

P.S. I didn't try to catch same behaviour with `register({rules})` maybe it's not a Controller specific behaviour

### Expected behaviour

I expect that change of "rules" property will update rules.pattern property as well without explicit "undefined"

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please use `validate` function instead.

**Comment by PetrBorisov** [comment]
@bluebill1049  I know about workaround, but rules.pattern doesn't marked as deprecated and has this bug
