### ISSUE TITLE
How to run some code after handleSubmit executed?

### ISSUE THREAD

**Issue by Ding-Fan** [react-hook-form/react-hook-form#1180]
Please consider asking the question at our spectrum channel.

I've tried the spectrum channel chat and it keeps eating my messages and I don't know why. I'm so sad 😢

https://spectrum.chat/react-hook-form

**Describe the question?**
I'd like to show a toast with error message after `handleSubmit` executed. But I don't know how to "handle this event". Maybe we could have two callbacks arguments like `handleSubmit(resolved, rejected)` ?

**To Reproduce**
No need to reproduce.

**Codesandbox link**
Take this from [Examples - Register Error Messages](https://codesandbox.io/s/o766kp4z05) as an example.
https://codesandbox.io/s/o766kp4z05

**Screenshots**
No screenshots.

**Additional context**
#114 looks similar.

**Comment by bluebill1049** [comment]
```
const onSubmit = () => {
  // do your logic here
}

useEffect(() => {
  // do your logic here
}, [errors])

handleSubmit(onSubmit)
```

**Comment by iway1** [comment]
@bluebill1049 don't think this works anymore, seems that `errors` retains a stable reference between rerenders so it's not running the `useEffect` hook more than one time.

**Comment by bluebill1049** [comment]
`handleSubmit(onValid, onInvalid)` you can use the second callback
