### ISSUE TITLE
issue: watch not working as expected for nested components using useFormContext

### ISSUE THREAD

**Issue by ksmith173** [react-hook-form/react-hook-form#11813]
### Version Number

7.51.3

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/watch-test-kwvsn9

### Steps to reproduce

1. Load code sandbox
2. Note how "One is selected" is not visible under the drop down on page load.
3. Change package.json version of react-hook-forms to 7.50.1 (or access this cloned with the version pre-set https://codesandbox.io/p/sandbox/watch-test-forked-rg2shh)
4. Note how "One is selected" IS visible under the drop down on page load

### Expected behaviour

In version 7.50.1 and prior, the watch on a Controller wrapped input with its value set by setValue would trigger the form to re-render and show conditional items. After this version, this no longer happens.

The issue seems to be limited to nested components that are using useFormContext.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This due to exectuion order for the subscription to be setup. This PR should improve DX/UX on this, as the subscription can establish before component gets run: https://github.com/react-hook-form/react-hook-form/pull/11522
