### ISSUE TITLE
when formState dirty is true but dirtyfields and touched size is 0? 

### ISSUE THREAD

**Issue by youngje4284** [react-hook-form/react-hook-form#1183]
Please consider asking the question at our spectrum channel.

https://spectrum.chat/react-hook-form

i use formState dirty value for check form data changed.
but i check my formState value in google console after useFieldArray add . 
dirty value true but dirtyfields size 0 and after remove  my field array dirty value true yet.
so i want to know when formState dirty is true but dirtyfields and touched size is 0. 
thank you make this lib~ 

![image](https://user-images.githubusercontent.com/59639025/76306386-1fa5be00-630a-11ea-838f-5ef0dc7d32f9.png)

**To Reproduce**
click append value twice and delete twice dirty value is true yet.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-l6xcd?

**Screenshots**

**Additional context**

**Comment by bluebill1049** [comment]
please provide a CSB and make my life a bit easier.

**Comment by youngje4284** [comment]
@bluebill1049 code sandbox link append~

**Comment by bluebill1049** [comment]
working as expected, you were not using the lib instead the src folder.

**Comment by youngje4284** [comment]
@bluebill1049 hmm. can i know diff in src folder and lib ? my project this issue appear... (not sandbox my custom project)

**Comment by bluebill1049** [comment]
can you take a look at the CSB? https://codesandbox.io/s/react-hook-form-usefieldarray-8uxt5 see if you can reproduce there and write down the steps.

**Comment by youngje4284** [comment]
@bluebill1049  ok  https://codesandbox.io/s/react-hook-form-usefieldarray-3pk19 this sandbox link ! maybe two input make this situation

**Comment by bluebill1049** [comment]
I can see problem when `dirtyFields` not get removed in the `formState`. what's the other issue? Look at your console, instead of CSB console. touchedField is a `Set` not `object`

**Comment by youngje4284** [comment]
I'm curious is this not a bug? i think dirty value is false when if you add and delete field array. but dirty value is true yet

**Comment by bluebill1049** [comment]
> I'm curious is this not a bug? i think dirty value is false when if you add and delete field array. but dirty value is true yet

hmm... i think that should make form dirty to true cause you change the fields.

**Comment by youngje4284** [comment]
https://codesandbox.io/s/react-hook-form-usefieldarray-3pk19 
hmm this code sandbox add and delete field dirty true In spite of i not change field value

**Comment by bluebill1049** [comment]
i think that's expected, because your form/inputs are chnage and it is dirty now.

**Comment by bluebill1049** [comment]
> Dirty refers to the form field is modified.

**Comment by youngje4284** [comment]
https://codesandbox.io/s/react-hook-form-usefieldarray-8uxt5

hmm then this sandbox link dirty value true after add and delete once click.
but this sandbox link dirty value false after add and delete once click

**Comment by bluebill1049** [comment]
oh! you are right with your example looks like it's not working...

**Comment by bluebill1049** [comment]
actually this could be the reason: https://github.com/react-hook-form/react-hook-form/issues/1188 which i raised a bug last night.

**Comment by bluebill1049** [comment]
let's track this on that ticket then. @youngje4284
