### ISSUE TITLE
issue: setError does not work with ErrorMessage component

### ISSUE THREAD

**Issue by brunoll** [react-hook-form/react-hook-form#11838]
### Version Number

7.51.3

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/competent-artem-2j6hcj

### Steps to reproduce

1. Set the error in the handleSubmit

```
setError("password", { message: "test" });
```

2. Render the error message itself and then the ErrorMessage component for the same field

```
<div>
  {errors.password?.message}
  <ErrorMessage
    errors={errors}
    name="password"
    render={({ messages }) => {
      console.log(messages);
      return (
        messages &&
        Object.entries(messages).map(([type, message]) => (
          <div key={type}>{message}</div>
        ))
      );
    }}
  />
</div>
```

3. You will see that the error did set itself correct with {errors.password?.message} but in ErrorMessage nothing renders out and messages is undefined in the console

I'm trying to use ErrorMessage to display multiple messages from multiple setError calls from server validation I'm not sure how to do this but it seems to be a bug.

### Expected behaviour

ErrorMessage should display the error messages

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shawnlauzon** [comment]
The `message` field is always empty for me, and so displaying `message` does nothing. 

``` LOG  {"message": "", "ref": {"name": "email"}, "type": "required"}
 LOG  {"message": "", "ref": {"name": "email"}, "type": "required"}
 LOG  {"message": "", "ref": {"name": "password"}, "type": "required"}
 LOG  {"message": "", "ref": {"name": "email"}, "type": "required"}
 LOG  {"message": "", "ref": {"name": "password"}, "type": "minLength"}
 LOG  {"message": "", "ref": {"name": "email"}, "type": "required"}
 LOG  {"message": "", "ref": {"name": "password"}, "type": "minLength"}```
