### ISSUE TITLE
Allow JSX elements/React components to be returned as an error message

### ISSUE THREAD

**Issue by markhalliwell** [react-hook-form/react-hook-form#11837]
**Is your feature request related to a problem? Please describe.**

We have a async validation that checks for an existing entity and, if returned, needs to link (opens in new window) to that entity so the user can inspect it.

**Describe the solution you'd like**

To be able to return a JSX element/react component as an error message:
```ts
const checkForDuplicates = async () => {
  const duplicateEntity = await getEntity();

  return !duplicateEntity ? true : (
    <span>
        Duplicate entity: <a target="_blank" href={`/entity/${duplicateEntity.id}`}>{duplicateEntity.title}</a>
    </span>
  )
}
```

**Describe alternatives you've considered**

Currently, we're getting around this limitation by setting local state and passing this error message manually to the component, but it's far from ideal and adds a lot of (IMO, unnecessary) overhead:
```ts
const [duplicateEntity, setDuplicateEntity] = useState();

const checkForDuplicates = async () => {
  setDuplicateEntity(undefined);

  const entity = await getEntity();

  setDuplicateEntity(entity);

  return !entity;
}

const error = useMemo(() => {
    if (!duplicateEntity) {
        return;
    }

    return (
            <span>
    Duplicate entity: <a target="_blank" href={`/entity/${duplicateEntity.id}`}>{duplicateEntity.title}</a>
            </span>
        );
    }, [duplicateEntity]);


return (
    <Controller
        name="entity"
        rules={{
            validate: { checkForDuplicates },
        }}
        render={({
            field: { disabled, onBlur, onChange, value },
        } => (
            <TextField
                disabled={disabled}
                error={!!error}
                helperText={error}
                onBlur={onBlur}
                onChange={onChange}
                value={value}
            />
        )}
    />
)

```

**Additional context**

**Comment by rh-meowsa** [comment]
Also need this feature!! 🙏

**Comment by bluebill1049** [comment]
TS limitation and you probably can dig out previous discussion which has been closed.

**Comment by rh-meowsa** [comment]
> TS limitation and you probably can dig out previous discussion which has been closed.

What is the limitation? Can you share the link to the previous discussion @bluebill1049 ?

It's quite common to have CTA button in error messages these days.
