### ISSUE TITLE
issue: disabled property in useForm applied to Form Provider does not apply to all radio inputs

### ISSUE THREAD

**Issue by singhshemona** [react-hook-form/react-hook-form#11842]
### Version Number

7.51.3

### Codesandbox/Expo snack

[Link to Codesandbox](https://codesandbox.io/p/sandbox/radio-input-example-d5th5j?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvqlm9if00063b6hxu3skfpy%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvqlm9ie00023b6h2aehlmdb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvqlm9ie00033b6h8fp2zyxs%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvqlm9ie00053b6h3qge1zd9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvqlm9ie00023b6h2aehlmdb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvqlm9ie00013b6hyk0rqcw5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522clvqlm9ie00023b6h2aehlmdb%2522%252C%2522activeTabId%2522%253A%2522clvqlm9ie00013b6hyk0rqcw5%2522%257D%252C%2522clvqlm9ie00053b6h3qge1zd9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvqlm9ie00043b6hz7lsdku3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvqlm9ie00053b6h3qge1zd9%2522%252C%2522activeTabId%2522%253A%2522clvqlm9ie00043b6hz7lsdku3%2522%257D%252C%2522clvqlm9ie00033b6h8fp2zyxs%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvqlm9ie00033b6h8fp2zyxs%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Go to [Codesandbox link](https://codesandbox.io/p/sandbox/radio-input-example-d5th5j?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvqlm9if00063b6hxu3skfpy%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvqlm9ie00023b6h2aehlmdb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvqlm9ie00033b6h8fp2zyxs%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvqlm9ie00053b6h3qge1zd9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvqlm9ie00023b6h2aehlmdb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvqlm9ie00013b6hyk0rqcw5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522clvqlm9ie00023b6h2aehlmdb%2522%252C%2522activeTabId%2522%253A%2522clvqlm9ie00013b6hyk0rqcw5%2522%257D%252C%2522clvqlm9ie00053b6h3qge1zd9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvqlm9ie00043b6hz7lsdku3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvqlm9ie00053b6h3qge1zd9%2522%252C%2522activeTabId%2522%253A%2522clvqlm9ie00043b6hz7lsdku3%2522%257D%252C%2522clvqlm9ie00033b6h8fp2zyxs%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvqlm9ie00033b6h8fp2zyxs%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
2. Uncomment line 8 in App.tsx
3. Notice how only the first radio input gets disabled

### Expected behaviour

Both radio inputs should be disabled. 

From my understanding, this is happening because both radio inputs are registered with the same name so it only applies the disabled validation to the first one occurring with that name. However, grouped radio inputs are [supposed to share the same name and it's their id that differentiates them](https://www.w3schools.com/tags/att_input_type_radio.asp).

**This is my workaround for now:**

```
// Shared Form component

export const Form = <T extends FieldValues>({
    children,
    defaultValues,
    disabled,
    onSubmit,
}: FormProps<T>): JSX.Element {
    const methods = useForm<T>({
        defaultValues,
        mode: 'onChange',
        disabled,
    });

    const { handleSubmit, reset } = methods;

    useEffect(() => {
        reset(defaultValues);
    }, [JSON.stringify(defaultValues)]);

    return (
        <FormProvider {...methods}>
            <form onSubmit={onSubmit && handleSubmit(onSubmit)}>{children}</form>
        </FormProvider>
    );
};
```

```
// How Form is being used, where disabled state is set

export const Page = (): JSX.Element => {
    const canEdit = hasPermission(some_permissions_rule);

    return (
        <Form
                onSubmit={handleSubmit}
                defaultValues={irrigationControlSettings}
                disabled={!canEdit}
            >
                <SomeInputs canEdit={canEdit} />
                {canEdit && (
                    <FormActions />
                )}
          </Form>
    );
};
```

```
// SomeInputs.tsx, where I have to pass the disabled state into the radio inputs explicitly

type SomeInputsProps = {
    canEdit: boolean;
};

export const SomeInputs = ({ canEdit }: SomeInputsProps): JSX.Element => {
    const fruits = [
        {
            label:  'Orange',
            id: 'orange',
        },
        {
            label: 'Apple',
            id: 'apple',
        },
    ];

    return (
        <div>
            <RadioInput
                labelForAllInputs="Fruits"
                name="fruits"
                options={fruits}
                validationRules={!canEdit ? { disabled: true } : {}}
            />
           ...remaining form inputs
        </div>
    );
};


```

```
// RadioInput.tsx, uses a shared Input component

export const RadioInput = ({
    labelForAllInputs,
    options,
    name,
    validationRules
}): JSX.Element => {
    return (
        <div>
            <p>{labelForAllInputs}</p>}
            <div>
                {options.map((optionProps) => (
                    <Input
                        key={optionProps.id}
                        name={name}
                        type="radio"
                        validationRules={validationRules}
                        {...optionProps}
                    />
                ))}
            </div>
        </div>
    );
};
```

I've also tried the following:

1. Using the `disabled` property from `useFormState`
2. Using the Controller component

But neither worked. Might there be a better or suggested way for radio inputs to pick up on the whole form being set to disabled? I'd like to avoid having to pass down the `canEdit` prop all the way to the radio inputs, especially because I thought the purpose of setting the disabled state in the `FormProvider` was so that all the inputs could pick up on it and there would be no prop drilling needed.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by erashu212** [comment]
@singhshemona  May be this can help [link](https://codesandbox.io/p/devbox/38dpth?migrateFrom=mcltlk)
