### ISSUE TITLE
Controller component doesn't apply changed validation rules

### ISSUE THREAD

**Issue by levente-gal** [react-hook-form/react-hook-form#1184]
Using react-hook-form version 5.0.3 and having a component like:
```javascript
function MyComp(props) {
return (
    <form onSubmit={handleSubmit(data => console.log(data))}>
      <Controller
        as={<Select options={options} />}
        control={control}
        rules={{ required: props.doValidate ? 'This field is Required': false }}
        onChange={([selected]) => {
          // React Select return object instead of value for selection
          return { value: selected };
        }}
        name="reactSelect"
        defaultValue={{ value: 'chocolate' }}
      />

      <button>submit</button>
    </form>
  );
}
```
It doesn't recognise the changed validation rules.

Note that the validation rule is based on a property
**required**: **props.doValidate** ? **'This field is Required'** : **false**

After a bit of investigation in the code, the problem seems to be that it doesn't re-register the input because the *useEffect* which calls `registerField` has only the `name` property as dependency but it should also have the *validation rules* too

**Comment by bluebill1049** [comment]
i would recommend using `validate`. also provide a CSB.

**Comment by levente-gal** [comment]
[CSB](https://codesandbox.io/s/react-hook-form-rhfinput-i6sxg) for reproducing the issue.

There is a switch on the top of the page which is used to control the validation of the React select combo.

**Comment by bluebill1049** [comment]
> After a bit of investigation in the code, the problem seems to be that it doesn't re-register the input because the useEffect which calls registerField has only the name property as dependency but it should also have the validation rules too

want to submit a PR since you find the issue and solution.

**Comment by levente-gal** [comment]
I'll do PR ASAP.
