### ISSUE TITLE
issue: valueAsDate parses based on current timezone

### ISSUE THREAD

**Issue by abmagil** [react-hook-form/react-hook-form#11843]
### Version Number

7.51.3

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/validatedaterhf-zd738x?file=%2Fsrc%2FApp.js%3A21%2C46-23%2C11

### Steps to reproduce

0. Be on the East coast of the US
1. Go to https://codesandbox.io/p/sandbox/validatedaterhf-zd738x?file=%2Fsrc%2FApp.js%3A21%2C46-23%2C11. This is an standard date field being parsed via `valueAsDate`
2. Select a day in the date input and submit.
3. In the console, RHF logs the date that is has parsed- what is logged out is 4 hours before the start of the selected day (presumably because of time zones)

### Expected behaviour

I expected naive parsing of the string coming out of my input, agnostic of time zones- i.e. if the input shows `05/03/2024`, the date I get back will correspond to Midnight on May 3rd, 2024 in GMT. If that's too specific, I would instead expect the ability to configure timezone when I use `valueAsDate`

While the `datetime-local` input type exists, that has a UI that is time inclusive, which I can't show to my users.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
{date: Thu May 02 2024 20:00:00 GMT-0400 (Eastern Daylight Time)}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
this would be out of scope of this library. if valueAsDate doesn't works for your usecase, transform value at your app level.
