### ISSUE TITLE
issue: the `formState.errors`default type is incorrect

### ISSUE THREAD

**Issue by voinik** [react-hook-form/react-hook-form#11841]
### Version Number

7.51.3 (latest)

### Codesandbox/Expo snack

[CodeSandbox link](https://codesandbox.io/p/sandbox/rhf-generic-field-error-type-issue-yy862l?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvcsor2t00063b6gtxqzb8ll%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvcsor2t00023b6g4l0u4ode%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvcsor2t00033b6g6q3vjolx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvcsor2t00053b6gbz1rv5em%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B55.14329774872123%252C44.85670225127877%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvcsor2t00023b6g4l0u4ode%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvcsor2t00013b6gfwnzlm3y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvcsw9gf00023b6gzmiabdpk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A65%252C%2522startColumn%2522%253A34%252C%2522endLineNumber%2522%253A65%252C%2522endColumn%2522%253A34%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FForm.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvcsor2t00023b6g4l0u4ode%2522%252C%2522activeTabId%2522%253A%2522clvcsw9gf00023b6gzmiabdpk%2522%257D%252C%2522clvcsor2t00053b6gbz1rv5em%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvcsor2t00043b6gnm1r8yyw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvcsor2t00053b6gbz1rv5em%2522%252C%2522activeTabId%2522%253A%2522clvcsor2t00043b6gnm1r8yyw%2522%257D%252C%2522clvcsor2t00033b6g6q3vjolx%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvcsor2t00033b6g6q3vjolx%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

Check the source code of the CodeSandbox. 

But summarized: When you use `useFormContext()` without passing it a generic, then the RHF types don't know what fields the form has. 

When you extract `formState.errors` from the context, and try to access the errors for a field that is an **array**, you won't be able to index the error. So doing this gives you a type error:
```ts
const { formState } = useFormContext();
const e = formState.errors.files?.[0]?.message; // The types don't include a possible array type; no indexing allowed
console.log('e: ', e); // e: [{ message: '..' }] 
```
So `e` can be an array, as you can see in the log, but the default types don't think it can be.

### Expected behaviour

I expect the default error types to expect the error to be an array (with inside it an object with a `message` property), as well as just an object with a `message` property.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> But summarized: When you use useFormContext() without passing it a generic, then the RHF types don't know what fields the form has.

Pretty sure that's the limitation.
