### ISSUE TITLE
Update Form defaultValues after Redux inject using reset api

### ISSUE THREAD

**Issue by rnnyrk** [react-hook-form/react-hook-form#1185]
Hi there,

I want to use defaultValues coming from Redux within my Form. Although when I directly visit the url from my browser and there is no customer yet, the Form isn't filled correctly. So this screenshot shows the lifecycle:

<img width="790" alt="Screenshot 2020-03-10 at 14 35 57" src="https://user-images.githubusercontent.com/4519142/76317438-7dbbac80-62dc-11ea-8662-1b75c7de6d29.png">

At first the customer is `undefined`. The docs say that I should run the `reset` API when the defaultValues change to simulate the correct behaviour. This is my code:

```
  const dispatch = useDispatch();
  const customer = useSelector(customerSelector);

  const formMethods = useForm<i.Customer>({
    mode: 'onChange',
    defaultValues: mapCustomer(customer),
  });
  const { register, handleSubmit, reset } = formMethods;

  React.useEffect(() => {
    if (customer) {
      reset(mapCustomer(customer));
    }
  }, [customer]);
```

Although unfortunately nothing happens. How can I insert my Redux data in my Form correctly?

**Comment by nhuzaa** [comment]
You have to load the form after the mapCustomer(customer) is defined. may be add isCustomerLoading  flag on redux and based on that load the form

**Comment by bluebill1049** [comment]
could you please supply a CSB? it should worked.

**Comment by rnnyrk** [comment]
Hereby the CBS (https://codesandbox.io/s/keen-varahamihira-18k36). Although it works in this example I see it sometimes flashing and going back to empty values. Looks like it happens when editing the code. Maybe it has something to do with HMR. Gonna try my project in Production build to see if I encounter the same issue over there. Keep you posted.

**Comment by bluebill1049** [comment]
i tested the CSB: https://codesandbox.io/s/muddy-waterfall-z0ivh looks fine so far.

**Comment by rnnyrk** [comment]
@bluebill1049 Unfortunately I'm still not able to get the issue resolved. Gonna try tomorrow in production mode

**Comment by bluebill1049** [comment]
Ok I will keep an eye on this as I couldn’t reproduce this issue.

**Comment by rnnyrk** [comment]
Still no clue what caused the issue, but the same code works now.

**Comment by bluebill1049** [comment]
no worries @rnnyrk let me know if anything else i can help. i try my best.
