### ISSUE TITLE
Get started example `Adapting existing form` triggers error `register is not a function`

### ISSUE THREAD

**Issue by adriaanmeuris** [react-hook-form/react-hook-form#1186]
**Describe the bug**
The [example here](https://react-hook-form.com/get-started#Adaptingexistingform) triggers following error: `register is not a function`

**To Reproduce**

1. go to the [get started page, Adapting existing form](https://react-hook-form.com/get-started#Adaptingexistingform)
2. copy the code
3. paste into codesandbox
4. see error

**Codesandbox link**
https://codesandbox.io/s/bitter-river-zjtjr?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
Example works as expected

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 80

**Comment by bluebill1049** [comment]
my bad fixing.

**Comment by bluebill1049** [comment]
fixed thanks: https://codesandbox.io/s/adapting-existing-form-3mspt :)
