### ISSUE TITLE
issue: Select input doesnt work when there's "," and "." 

### ISSUE THREAD

**Issue by stivenm16** [react-hook-form/react-hook-form#11877]
### Version Number

7.51.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/staging-bird-rmmfjv?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clw0ojw5o00062v6jceg5lfr4%2522%252C%2522sizes%2522%253A%255Bnull%252Cnull%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clw0ojw5o00022v6j99tfwct0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clw0ojw5o00032v6jysysb7xg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clw0ojw5o00052v6jhzmrvuwx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B56.87901935038672%252C43.12098064961328%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clw0ojw5o00022v6j99tfwct0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw0ojw5n00012v6jl8frz3pz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clw0oldyp003q2v6jjbfq9j3y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A25%252C%2522startColumn%2522%253A70%252C%2522endLineNumber%2522%253A25%252C%2522endColumn%2522%253A70%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clw0ojw5o00022v6j99tfwct0%2522%252C%2522activeTabId%2522%253A%2522clw0oldyp003q2v6jjbfq9j3y%2522%257D%252C%2522clw0ojw5o00052v6jhzmrvuwx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw0ojw5o00042v6jt7n650og%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clw0ojw5o00052v6jhzmrvuwx%2522%252C%2522activeTabId%2522%253A%2522clw0ojw5o00042v6jt7n650og%2522%257D%252C%2522clw0ojw5o00032v6jysysb7xg%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clw0ojw5o00032v6jysysb7xg%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

The error happens when I try to write into the controller a name which includes "," and "." it doesnt happen if there's just one of those, netiher if there's just one period or one comma

### Expected behaviour

The select should render without any problem

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> name can neither start with a number nor use number as key name. Please avoid special characters as well.

https://react-hook-form.com/docs/useform/register
