### ISSUE TITLE
Dirty Fields not getting removed after deletion in useFieldArray

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#1188]
**Describe the bug**
Dirty fields are not removed after that field is getting removed.

**To Reproduce**
1. update the field
2. click delete
3. inspect console

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-3pk19

**Expected behavior**
Dirty Fields should be getting removed after deletion in useFieldArray

**Comment by bluebill1049** [comment]
@youngje4284 keep an eye on this one, i may need your help in terms of verify the fix.

**Comment by bluebill1049** [comment]
i found out the reason with your issue @youngje4284. it's due to default value:

https://codesandbox.io/s/react-hook-form-usefieldarray-jxm8f

default value have `number` instead of `string`. input return string and default `value` is `number`, so it's the reason why it's not working as expected.

**Comment by youngje4284** [comment]
wow. you're genius... thank you very much.

Is there any intention to fix this ? Or if i should not use number type and only use string type ?

**Comment by bluebill1049** [comment]
@youngje4284 i still have a PR for this issue which i have raised. i think you should keep them as string, so it match with what input returns (string)

**Comment by youngje4284** [comment]
I understand after your pr merged, i can use number type value  in field array.
but now i should to change number type to string. is this right?

**Comment by bluebill1049** [comment]
> I understand after your pr merged, i can use number type value in field array.
no, this PR will fix dirtyFields not getting removed

> but now i should to change number type to string. is this right 
you should convert default value from number to string, we are not going to do the convert inside the lib.

**Comment by youngje4284** [comment]
ok i got it thank you~

**Comment by youngje4284** [comment]
![image](https://user-images.githubusercontent.com/59639025/76387991-65669300-63ab-11ea-98b7-5d810258afcb.png)

I make check isFormDataChange this. because i use typescript and server get and post data type is number. so i think all number type to string convert for only this issue it is difficult. now is data change cheked works. thank you for help~

**Comment by bluebill1049** [comment]
pleasure to help @youngje4284

**Comment by kcunanan** [comment]
Hi @bluebill1049 ! I know this issue has been closed, but I was wondering if / when this bug fix will get released.

The `dirtyFields` are still not being updated when expected in the `formState` sandbox even though the sample is using the `latest`. Thanks!
https://codesandbox.io/s/7o2wrp86k6

**Comment by bluebill1049** [comment]
hey @kcunanan dirtyFields is a set, can you take a look at the dev console. let me know if that's fixed.

<img width="888" alt="Screen Shot 2020-03-24 at 11 20 39 am" src="https://user-images.githubusercontent.com/10513364/77375417-84105500-6dc1-11ea-8769-ed34942427ee.png">

**Comment by kcunanan** [comment]
Ah got it. Looks like the `console.log(JSON.stringify(formState.dirtyFields));` misled me 😅 

Thanks so much!

![image](https://user-images.githubusercontent.com/10050800/77375651-5e387100-6d2b-11ea-9507-de704b948555.png)

**Comment by bluebill1049** [comment]
no worries at all :) @kcunanan
