### ISSUE TITLE
issue: UseFormReturn Typescript Crash

### ISSUE THREAD

**Issue by JesusFTG** [react-hook-form/react-hook-form#11906]
### Version Number

7.51.4

### Codesandbox/Expo snack

<a target="_blank" href="https://codesandbox.io/p/sandbox/react-hook-form-useformreturn-ygmqc5" >Sandbox</a>

Note: When you open the sandbox, go to `Test` component and check how the TS server crashes...

You can experience this in VSCODE too

### Steps to reproduce

1. Create a wrapper component with `const {form} = useForm()` hook
2. Create an internal component with fieldValues receiving the UseFormReturn type

```
export function Test<T extends UseFormReturn<T>>({
  form,
}: {
  form: T extends UseFormReturn<T> ? UseFormReturn<T> : UseFormReturn<T>;
}) {
```

4. Check how Typescript server crashes and it doesn't load any type (stuck on loading...)
<img width="452" alt="image" src="https://github.com/react-hook-form/react-hook-form/assets/158451520/5353972e-e076-424d-b06e-fba9b30ba2f8">

### Expected behaviour

The UseFormReturn type shouldn't crash the TS server

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Doesn't work as a generate component.
