### ISSUE TITLE
issue: react-hook-form bundle is different from other packages

### ISSUE THREAD

**Issue by Sh031224** [react-hook-form/react-hook-form#11914]
### Version Number

7.51.4

### Codesandbox/Expo snack

https://github.com/Sh031224/react-hook-form-bundle

### Steps to reproduce

1. `git clone https://github.com/Sh031224/react-hook-form-bundle.git`
2. `cd react-hook-form-bundle`
3. `pnpm install && pnpm run dev`
4. Check React Dev tools > Components > Anonymous
5. source is `dist/index.cjs.js?:1`

### Expected behaviour

All packages must use esm.

### What browsers are you seeing the problem on?

If you look at the source section with the Components tool of the react dev tool, only react-hook-form uses the commonjs bundle.

I think this issue is related. https://github.com/react-hook-form/react-hook-form/issues/8281

Therefore, when creating a package that includes react-hook-form as a peer dependency, context problems occur because esm and cjs are viewed differently.

![스크린샷 2024-05-21 오후 7 23 15](https://github.com/react-hook-form/react-hook-form/assets/51149996/bab6b2cf-4222-4bf9-aeb5-64eb83856729)
![스크린샷 2024-05-21 오후 7 23 50](https://github.com/react-hook-form/react-hook-form/assets/51149996/02de9beb-3879-4f7a-bc5d-b0378734f955)
![스크린샷 2024-05-21 오후 7 24 16](https://github.com/react-hook-form/react-hook-form/assets/51149996/c8f847ca-821d-47b9-b3ff-e46195c6f88c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/blob/master/package.json#L5-L8

**Comment by Sh031224** [comment]
@bluebill1049 However, if I change the exports field in the local environment as follows, it works normally.


```diff
"exports": {
    "./package.json": "./package.json",
    ".": {
      "react-server": "./dist/react-server.esm.mjs",
-      "types": "./dist/index.d.ts",
-      "react-server": "./dist/react-server.esm.mjs",
-      "import": "./dist/index.esm.mjs",
-      "require": "./dist/index.cjs.js"
+      "import": {
+        "types": "./dist/index.d.ts",
+        "default": "./dist/index.esm.mjs"
+      },
+      "types": "./dist/index.d.ts",
+      "module": "./dist/index.esm.mjs",
+      "require": "./dist/index.cjs.js",
+      "default": "./dist/index.cjs.js"
    }
```

<img width="1255" alt="image" src="https://github.com/react-hook-form/react-hook-form/assets/51149996/d57b6547-0416-46fa-ab3c-4c91556deaeb">

```json
{
  "dependencies": {
    "react-hook-form": "file:./react-hook-form",
  },
}
```

I added the above example to the repository.

1. git clone https://github.com/Sh031224/react-hook-form-bundle.git
2. sh ./prepare.sh && pnpm run dev

**Comment by Sh031224** [comment]
https://webpack.js.org/guides/package-exports/#conditions

Because of support in webpack, it seems that module must also be added to the exports field.
