### ISSUE TITLE
Eslint plugin for react hook form

### ISSUE THREAD

**Issue by RabbitShare** [react-hook-form/react-hook-form#11918]
**Is your feature request related to a problem? Please describe.**
I am frustrated when rhf start using Proxy for subscribing api methods

**Describe the solution you'd like**
Eslint plugin with rules of react hook form

**Describe alternatives you've considered**
I find plugin but it unmaintained https://www.npmjs.com/package/eslint-plugin-react-hook-form

**Additional context**
Provides autofix suggestions to adhere to best practices.

1. Use destructuring assignment to access the properties of formState.
2. Avoid providing undefined as a default value, as it conflicts with the default state of a controlled component.
3. defaultValues are cached. To reset them, use the reset API. (it's better to provide jsdoc for this)
4. defaultValues will be included in the submission result by default. (it's better to provide jsdoc for this)
5. Avoid using custom objects with prototype methods, such as Moment or Luxon, as defaultValues.
6. name is required and unique (except for native radio and checkbox).
7. name cannot start with a number or use a number as a key name. Avoid special characters.

**Comment by bluebill1049** [comment]
I don't think have capacity at this stage moving to the back log hopefully someone else would create a new one or maintain the existing one.
