### ISSUE TITLE
formState.dirty updating doesn't work with useFieldArray and useFormContext

### ISSUE THREAD

**Issue by EkaterinaMozheiko** [react-hook-form/react-hook-form#1191]
Hi, I'm using useFormContext and useFieldArray at the same time. It seems that formState.dirty doesn't work correctly in this case - it isn't updated when I add or remove a field.

Check this out here: https://codesandbox.io/s/react-hook-form-usefieldarray-9z0ur

**Comment by bluebill1049** [comment]
This is a duplicated issue, please refer to this one: https://github.com/react-hook-form/react-hook-form/issues/1190
