### ISSUE TITLE
Input fields using useFieldArray are cleared after resetting form

### ISSUE THREAD

**Issue by susisu** [react-hook-form/react-hook-form#1192]
**Describe the bug**
After resetting form, input fields using `useFieldArray` are just cleared, not filled with new default values.
If inputs have `defaultValue` props as in [the example](https://codesandbox.io/s/react-hook-form-usefieldarray-vy8fv), the new values are filled as expected. Or is this an expected behavior and `defaultValue` props are required on inputs?

**To Reproduce**

1. Open the CodeSandbox below.
2. Click `reset` button.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-oosmt

**Expected behavior**
Input fields are filled with the new default values passed to the `reset` function.

**Desktop (please complete the following information):**
- OS: macOS 10.15.3
- Browser Chrome 81.0.4044.62 / Firefox 74.0

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-usefieldarray-9q7w7

**Comment by kotarella1110** [comment]
https://react-hook-form.com/api#useFieldArray

<img width="909" alt="スクリーンショット 2020-03-12 13 48 16" src="https://user-images.githubusercontent.com/12913947/76488288-5265c880-6468-11ea-902b-ede1cc700ce7.png">

**Comment by susisu** [comment]
> https://github.com/react-hook-form/react-hook-form/issues/1192#issuecomment-598005005

Oh, sorry. I missed it.

**Comment by bluebill1049** [comment]
all good :)
