### ISSUE TITLE
issue: updating number values is always marked as dirty even if the value is the same as the default one 

### ISSUE THREAD

**Issue by IzumiSy** [react-hook-form/react-hook-form#11928]
### Version Number

^7

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/brave-water-l6nnxp

### Steps to reproduce

1. Update "age" to 201
2. Update "age" to 200 (the default value of "age")
3. Click submit

### Expected behaviour

The result will be shown in console, but it should not be and the submit button should be disabled, because the values are the same as the default ones.

As for the string value (name) works as expected. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by keisuke-na** [comment]
The internal state of react-hook-form is held as a string. This is even if the defaultValue is a number, like 200.
If you pass the defaultValue as a string like "200", it will behave as intended.

**Comment by IzumiSy** [comment]
@keisuke-na 
I see, then do I need something like this?

```
<ControllerPlus<string, number>
  transform={{
    input: (value) =>
      isNaN(value) || value === 0 ? "" : value.toString(),
    output: (e) => {
      const output = parseInt(e.target.value, 10);
      return isNaN(output) ? 0 : output;
    }
  }}
  control={control}
  name="number"
  defaultValue=""
/>
```

**Comment by keisuke-na** [comment]
@IzumiSy 
Yes.
Or, You can just transform the data before submit it.

**Comment by IzumiSy** [comment]
Gotcha, this is not a bug and just my misunderstanding on the internal behaviour. Thanks!
