### ISSUE TITLE
issue: Keep Dirty on reset does not work

### ISSUE THREAD

**Issue by islami00** [react-hook-form/react-hook-form#11922]
### Version Number

7.48.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/boring-wood-q9kyqz?file=%2Fsrc%2FApp.tsx

### Steps to reproduce

1. Go to Name Input
2. Change the name
2. Click on reset
3. Open the devtools
4. See that dirtyFields is not retained

### Expected behaviour

DirtyFields should be retained when keepDirty is true on `reset` based on the docs:
> DirtyFields form state will remain, and isDirty will temporarily remain as the current state until further user's action.Important: this keep option doesn't reflect form input values but only dirty fields form state.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tomas1646** [comment]
The Codesandbox link isn't working: "Sandbox not found".

**Comment by islami00** [comment]
Should be visible now @tomas1646

**Comment by mrKorg** [comment]
@islami00 Thanks, you saved my time.
I found the same problem while updating the package.
isDirty started behaving differently after update when I use
`  useEffect(() => {
    if (isSubmitSuccessful) {
      reset({}, { keepValues: true });
    }
  }, [isSubmitSuccessful, reset]);`
