### ISSUE TITLE
issue: getFieldState().error type broken on nested FieldValues

### ISSUE THREAD

**Issue by elecdeer** [react-hook-form/react-hook-form#11927]
### Version Number

v7.51.5

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/issue-getfieldstate-error-type-broken-on-nested-fieldvalues-z3m5qy?file=%2Fsrc%2FApp.tsx%3A98%2C38

### Steps to reproduce

Due to the changes in #11831, the type of `getFieldState().error` for nested FieldValues has been broken. 

Please check Codesandbox.
In v7.51.4, the return type of `getFieldState("users.0.firstName", formState).error` was `FieldError | undefined`, but in v7.51.5, it has become `unknown`.
In runtime, when an error occurs, the value obtained from `getFieldState` is of type `FieldError`, so I think this type should be `FieldError`.

### Expected behaviour

There should not be a type error.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
reverted will release the patch soon: https://github.com/react-hook-form/react-hook-form/commit/927535bf87412b2baa91faefb4c7ded327126c2b
