### ISSUE TITLE
issue: Field with useController inside useFieldArray not update

### ISSUE THREAD

**Issue by andreyevyk** [react-hook-form/react-hook-form#11931]
### Version Number

7.51.5

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/naughty-poitras-m62j7v

### Steps to reproduce

1. Go to the codesandbox link
2. Click on 'Update Object'
3. The Fields stringified will update, but the Controlled Field will not

### Expected behaviour

The controlled Field must updates.
Before this [commit](https://github.com/react-hook-form/react-hook-form/commit/09d51cf70073efd296eac71981097efe47d83cf8), the controlled is updated when fields update. [Old version sandbox](https://codesandbox.io/p/sandbox/controlled-field-usefieldarray-forked-3qrq5n).

This happens due to the use of `exact: true`.
 

### What browsers are you seeing the problem on?

Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
not a valid use case, plz refer to the doc.

**Comment by intayush** [comment]
@bluebill1049 I'm facing a similar issue. Do you mean to say that the field array state is not supposed to be in sync with control by design? Would be helpful if you could expand a bit on it or point to the part of docs you have asked to refer. Thanks :)

**Comment by andreyevyk** [comment]
@bluebill1049 The usecontroller is not synchronized within a FieldArray, I didn't find this in the documentation, can you explain more?

**Comment by jmunozz** [comment]
Can you explain why this issue is not valid ? 
How am I supposed to update a field from within a FieldArray field ?
Doc mentions `update()` method and a classic `Controller`one: 
```
            <Controller
              render={({ field }) => <input {...field} />}
              name={`test.${index}.lastName`}
              control={control}
            />
            ```
