### ISSUE TITLE
issue: register does not set the disabled prop when form is disabled

### ISSUE THREAD

**Issue by RedHatter** [react-hook-form/react-hook-form#11934]
### Version Number

7.51.5

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/competent-kapitsa-ldzlj2?file=%2Fsrc%2FApp.tsx%3A22%2C15

### Steps to reproduce

1. Register a input component that makes use of the `disabled` prop
2. Pass `disabled: true` to `useForm`
4. Observe that the input component does not receive the `disabled` prop.

### Expected behaviour

I would expect the `register ` function to set the `disabled` prop the same way it does if disabled through a option like so `register('field', { disabled: true })`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
![Screenshot 2024-05-25 at 3 10 12 pm](https://github.com/react-hook-form/react-hook-form/assets/10513364/d5e3be6d-8df7-49ba-b2d3-c7b449f129e2)

working as expected.
