### ISSUE TITLE
issue: resetField nested field doesn`t reset state useFieldArray

### ISSUE THREAD

**Issue by Devisione** [react-hook-form/react-hook-form#11943]
### Version Number

7.51.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/naughty-zeh-yd9dfq

### Steps to reproduce

1. open editor
2. wait a second

### Expected behaviour

field is removed, because we are reset nested field array. if use useWatch we see is field empty array. but useFieldArray think he has a filled array.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
works only for field.

**Comment by Devisione** [comment]
how to solve nested object reset problem? in all cases everything works well except arrays!
