### ISSUE TITLE
Async validationResolver types are missing

### ISSUE THREAD

**Issue by hareacostica** [react-hook-form/react-hook-form#1194]
**Describe the bug**
Types for validation resolver restricts it to a sync method only, while it can be async as well.

**Codesandbox link (Required)**
https://codesandbox.io/s/async-validationresolver-types-rhf-wxls1

**Expected behavior**
ValidationResolver should allow async method as well.

**Comment by bluebill1049** [comment]
thanks @hareacostica you are right. will update that with the correct type.

**Comment by bluebill1049** [comment]
feel free to send a PR as well @hareacostica
