### ISSUE TITLE
issue: combining isValid and isDirty in useEffect deps array fire the effect twice

### ISSUE THREAD

**Issue by epignosisx** [react-hook-form/react-hook-form#11957]
### Version Number

7.51.5

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/nifty-architecture-w8w6gs?file=%2Fsrc%2FApp.tsx%3A24%2C14

### Steps to reproduce

I've noticed that when combining `isValid` and `isDirty` in useEffect, it fires the effect twice when typing the first character: First with isValid having the old value, then a second time with isValid with the new value. 

The same happens when deleting all characters: first `isValid: true`, then it will fire a second time with `isValid: false`.

```ts
export default function App() {
  const {
    formState: { isValid, isDirty },
    register,
  } = useForm<FormValues>({
    defaultValues: {
      firstName: "",
    },
  });

  React.useEffect(() => {
    console.log(JSON.stringify({ isValid, isDirty }));
  }, [isValid, isDirty]);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
        <input {...register("firstName", { required: true })} />
        <input type="submit" />
    </form>
  );
}
```

Here is a working repro:
https://codesandbox.io/p/sandbox/nifty-architecture-w8w6gs?file=%2Fsrc%2FApp.tsx%3A24%2C14

> [!TIP] 
> If the isDirty is removed from the useEffect, then it fires only once.

### Expected behaviour

I would expect the useEffect to fire only once with the latest value of isValid instead of first firing with the old value, then with the new value.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
expected, isValid is async
