### ISSUE TITLE
issue: Render loop when calling `getFieldState`

### ISSUE THREAD

**Issue by fzaninotto** [react-hook-form/react-hook-form#11954]
### Version Number

7.51.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/confident-lumiere-8ym9jc?file=%2Fsrc%2FApp.tsx%3A14%2C3

### Steps to reproduce

1. Go to the [CodeSandbox](https://codesandbox.io/p/sandbox/confident-lumiere-8ym9jc)
2. Open the console in the DevTools
3. Click on Save in the form
4. See the error: a lot of 'render input' lines

This shows that the input component has been rendered a lot. 

The problem appears with 7.51.1. Before that, it doesn't occur. 

### Expected behaviour

No rerender. 

Reproducible by commenting L14 in App.tsx. 

This is causing a series of performance issues in react-admin:

- https://github.com/marmelab/react-admin/issues/9885
- https://github.com/marmelab/react-admin/issues/9783

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
dead codesandbox link.

**Comment by IdoBouskila** [comment]
I had this problem too. I reverted to `7.45.4` and it's gone. I'll try to reproduce it today.

**Comment by fzaninotto** [comment]
Sorry for the dead link, I fixed the CodeSandbox sharing preferences and now it is accessible.
