### ISSUE TITLE
issue: setError used with shouldFocus doesn't set the focus properly

### ISSUE THREAD

**Issue by Pierre-Do** [react-hook-form/react-hook-form#11963]
### Version Number

7.51.5

### Codesandbox/Expo snack

https://github.com/Pierre-Do/set-error-focus

https://github.com/Pierre-Do/set-error-focus/blob/main/app/SetFocusOnError.tsx

### Steps to reproduce

Let's consider the following code:

```typescript
const { handleSubmit, setError, control, formState } = useForm<FormData>({
    defaultValues: {
      password: "",
    },
  });
  
  async function submit() {
    try {
      await asyncCall();
    } catch (e) {
      // Something goes wrong, we set the error manually on the field
      setError(
        "password",
        { message: "An error occurred" },
        { shouldFocus: true },
      );
    }
  }

  return (
    <form onSubmit={handleSubmit(submit)} className="flex gap-2 flex-col">
      <Controller
        name="password"
        control={control}
        disabled={formState.isSubmitting} // <-- The field is disabled whilst the form is being submitted
        render={({ field }) => <input {...field} />}
      />
      {formState.errors.password ? (
        <div className="text-red-500">{formState.errors.password.message}</div>
      ) : null}
      <button type="submit" disabled={formState.isSubmitting}>
        Submit
      </button>
    </form>
  );
```

1. Submit the form whilst disabling the input and the submit button
2. Something goes wrong on the server, the async call throws an error that we're catching in the `handleSubmit` handler
3. `setError` is used to map the error on the field, with `shouldFocus` enabled for a11y purposes
4. The focus is not set on the field

NOTE: If `setError` is wrapped in a `setTimeout` to push the operation at the end of the event loop, the focus is set properly. I've demoed this behavior in the [demo repo](https://github.com/Pierre-Do/set-error-focus/blob/main/app/SetFocusOnError.tsx)

If the `input` field isn't disabled whist the form is being submitted `setError` sets the focus as expected.

I acknowledge that focus handling with forms is a difficult problem, and that React doesn't make it easier to implement properly :wink: 

### Expected behaviour

The focus should be set on the field.

### What browsers are you seeing the problem on?

Tested with Chrome 25.0.6422.141 and Firefox 126.0.1 (Linux Mint)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Pierre-Do** [comment]
Thinking of it, this behavior might be related to the fact that my async handler is calling `setError` within the promise on which `isSubmitting`is based.

Therefore I'm trying to set the focus on a field that's disabled because `isSubmitting` is still true when `setError` is called, because `shouldFocus` sets the focus immediately.

**Comment by bluebill1049** [comment]
I think you will have to do it in `useEffect`, cause the `focus` would be run inside the onSubmit callback while the form hasn't been re-render to remove that disabled prop.
