### ISSUE TITLE
issue: trigger function / register deps - trigger re-render even if formState isn't updated

### ISSUE THREAD

**Issue by IdoBouskila** [react-hook-form/react-hook-form#11970]
### Version Number

7.51.5

### Codesandbox/Expo snack

https://stackblitz.com/edit/vitejs-vite-ye8m9c?file=src%2FApp.tsx

### Steps to reproduce

1. Go to the [demo](https://stackblitz.com/edit/vitejs-vite-ye8m9c?file=src%2FApp.tsx)
2. Open the browser console
3. Click on `validate form` button -> you'll see a "render" log, which is expected since `errors` is updated inside `formState`.
When you click validate again, you'll get another "render" log in the console, which might be unexpected because the formstate doesn't change at all.

### Expected behaviour

If the formState doesn't change, trigger shouldn't trigger render.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
We are reducing the amount of render, but that doesn't mean we will eliminate all of them.

**Comment by IdoBouskila** [comment]
> We are reducing the amount of render, but that doesn't mean we will eliminate all of them.
It's not about eliminating all of them. Some of the renders happen when nothing has changed in the state. I suspect it's updating the same state values, but with a different memory reference.

I will try look into that and send a PR if it works 👍🏼
