### ISSUE TITLE
useFieldArray issue around field register under useFormContext

### ISSUE THREAD

**Issue by susisu** [react-hook-form/react-hook-form#1198]
**Describe the bug**
When using `useFieldArray` combined with `FormContext` and `useFormContext`, after removing a filed, submitted data become empty.
If used without `FormContext` and `useFormContext`, it works correctly.

**To Reproduce**
See the CodeSandbox below.

1. Append a field.
2. Remove the field.
3. Submit.
4. Submitted data in console is empty (`{}`).

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-8qeuj

**Expected behavior**
The submitted data should contain one field (like `{ test: ["useFieldArray"] }`).

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Browser Chrome 81.0.4044.43 / Firefox 74.0

**Comment by bluebill1049** [comment]
going to close this issue, i have updated the doc to reflect this. https://github.com/react-hook-form/react-hook-form-website/commit/1557669e198fbe84f424d932a8e7f63f5c5bc9fb
