### ISSUE TITLE
how to use triggerValidation with useEffect

### ISSUE THREAD

**Issue by shoko-eguchi** [react-hook-form/react-hook-form#1199]
I want to run validation ckecks and display errors when the screen is initially displayed.
■what I use: react, react-hook-form, typescript
■detail:
there are multiple inputs to check.
Currently, no error is displayed unless 『setTimeout』is used.
isLoaded is true if data is fetched.
I think the timing of error display and readering is a problem.
I don't want to use setTimeout.
Do you know any ideas, please help.(enough information?)

```
function RootComponent (props) {

 useEffect(() => {
  setTimeout(() => {
   triggerValidation();
  }, 1000);
 }, [props.payload.isLoaded);

 const REQUIRED_VALIDATE = { required: { value: true, message: REQUIRED_MESSAGE } };
 const REGEX_NAME_NOT_EMPTY_VALIDATE = {
  pattern: { value: /\S+/, message: REQUIRED_MESSAGE },
 };

 return (
  <React.Fragment>
   <TextField error={!!errors.familyName} name="familyName"
    inputRef={register(
     required: REQUIRED_VALIDATE.required,
     pattern: REGEX_NAME_NOT_EMPTY_VALIDATE.pattern,
    )} />
    ・・・and more
  </React.Fragment>
 );
}
```

**Comment by bluebill1049** [comment]
can you provide a codesandbox?

**Comment by shoko-eguchi** [comment]
I'll try.

**Comment by bluebill1049** [comment]
by looking at the code, it's not going to working on the initial useEffect, because input hasn't been registered. that's why setTimeout worked.

**Comment by shoko-eguchi** [comment]
codeSandBox is in preparation, I'm sorry.
>input hasn't been registered.

I think so, too. I wish I could know a event like 『inputs is ready』.

**Comment by bluebill1049** [comment]
that's useEffect.

**Comment by shoko-eguchi** [comment]
oh, yes...I 'm confused

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/pedantic-bardeen-eiss8

**Comment by shoko-eguchi** [comment]
Thank you for replying.

**Comment by bluebill1049** [comment]
let me know if that solve the issue, we can re-open the issue if that's the solution.

**Comment by shoko-eguchi** [comment]
sorry, I did not solve.
I removed setTimeout and wrote like this↓
```
useEffect(() => {
 triggerValidation(['nameA', 'nameB',…])
}, []);
```

The rendering runs like infinity.

**Comment by bluebill1049** [comment]
take a look mine: https://codesandbox.io/s/pedantic-bardeen-eiss8

**Comment by shoko-eguchi** [comment]
triggervalidation was put in the second argument of useEffect.
Then triggervalidation no work(no error is displayed).

**Comment by bluebill1049** [comment]
@shoko-eguchi can you update this CSB: https://codesandbox.io/s/pedantic-bardeen-eiss8 and i will take a look again.

**Comment by shoko-eguchi** [comment]
Sorry, I'm late.CSB is ready.
（Thanks for preparing CSB, but it was js, so I made here↓）
https://codesandbox.io/s/runtime-grass-2185d

I want to set the data flowing from the store to the TextField and execute validation.
If I do not use setTimeout, rendering will be executed indefinitely.
**CSB sopped working when setTimeout was removed.**

**Comment by shoko-eguchi** [comment]
@bluebill1049 Sorry, I cannot reopen this issue, Can you reopen?

**Comment by kotarella1110** [comment]
@shoko-eguchi You should execute `triggerValidation` when the store changes.
Therefore, you need to provide the props received from the Store to the deps of useEffect.

```ts
useEffect(() => {
  triggerValidation();
}, [
  props.data.name,
  props.data.familyName,
  props.data.phoneNumber01,
  props.data.phoneNumber02
]);
```

**Comment by bluebill1049** [comment]
Thanks @kotarella1110 👍

**Comment by shoko-eguchi** [comment]
@kotarella1110 @bluebill1049 
could be run without using setTimeout.
Thank you very much.
