### ISSUE TITLE
Swapping elements for one reference causes corrupted state

### ISSUE THREAD

**Issue by astj** [react-hook-form/react-hook-form#1200]
**Describe the bug**
When unmouning one registered input and mounting another registered input at the same time and when they are both registered to the same reference, the newer one is not registered at first.
By triggering next rendering (by submitting the form or triggering rerender by "rerender" button at bottom of the page), the input seems to be registered.

**To Reproduce**
In codesandbox, 
1. Click on "change name"
2. text input appears without corresponding defaultValue ("john")
3. (optional) change the value of the input
4. Submit the form
    - empty `{}` is sent to console, regardless current value of the input (may changed at 3)
5. By submitting, the text input is filled with defaultValue ("john")

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-elements-swapping-dm6b3

**Expected behavior**
- At step 2, text input appears with their defaultValue ("john") filled
- At step 4, the value of the text input will be outputted to console as `{userName: "xxx"}`

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3（19D76）
 - Browser Safari, Chrome
 - Version Safari 13.0.5, Chrome 80.0.3987.132

**Comment by astj** [comment]
We imagine this is due to MutationObserver's asynchronous callback (ref: https://github.com/react-hook-form/react-hook-form/blob/master/src/utils/onDomRemove.ts#L8 ), like:
- Old input unmounted and new input mounted
- `unregister` for the oldone  and `register` for the new one runs
  - By `register` for New input, the input is registered for "userName"
- Callback of MutationObserver for the old one runs asynchronously
  - the callback removed reference for "userName", which is intended to the old one, but actually the new one
- The Callback itself does not trigger re-rendering, therefore first rendering ends here
- On the next rendering, `register` of the new input runs again, and the input is registered for "userName" again



But not yet confirmed exact reason.

**Comment by bluebill1049** [comment]
> We imagine this is due to MutationObserver's asynchronous callback (ref: https://github.com/react-hook-form/react-hook-form/blob/master/src/utils/onDomRemove.ts#L8 ), like:

Your assumption is correct. You probably can use `unregister` during `useEffect` to solve this issue.

**Comment by astj** [comment]
Thank you for quick response.

I understand it's expected behavior.  So I'm going to close this issue for now.
I might re-open this issue if I find any difficulties and/or feedbacks around this case.  Thank you again!

**Comment by bluebill1049** [comment]
yea ,no worries @astj another alternative solution would just have two of them on the screen and toggle the visibility.
