### ISSUE TITLE
Yup validation for Field arrays

### ISSUE THREAD

**Issue by kiansenggoh** [react-hook-form/react-hook-form#1201]
Hi

How do use yup with field array? Got any examples?

**Comment by bluebill1049** [comment]
do a search at spectrum: https://spectrum.chat/react-hook-form/help/how-to-validate-fields-when-using-usefieldarray~6fab8383-0feb-4f22-8d9d-2523c6d41582

**Comment by bluebill1049** [comment]
basically validate array of values :)
