### ISSUE TITLE
issue: Subscription to isValidating via useController causes quadratic amounts of re-renders on submit

### ISSUE THREAD

**Issue by andrewgreenh** [react-hook-form/react-hook-form#12012]
### Version Number

7.51.5

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/musing-wilson-4y3l84?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxeg0a2800063b6n7y8daw4b%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxeg0a2800023b6nq2elwmg9%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxeg0a2800033b6npnvmi7uv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxeg0a2800053b6nmoefbfgu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxeg0a2800023b6nq2elwmg9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxeg0a2800013b6ne0u18yyb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxeg16s7003d3b6nbasvsk4e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A31%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxeg0a2800023b6nq2elwmg9%2522%252C%2522activeTabId%2522%253A%2522clxeg16s7003d3b6nbasvsk4e%2522%257D%252C%2522clxeg0a2800053b6nmoefbfgu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxeg0a2800043b6nn4iwwjoe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxeg0a2800053b6nmoefbfgu%2522%252C%2522activeTabId%2522%253A%2522clxeg0a2800043b6nn4iwwjoe%2522%257D%252C%2522clxeg0a2800033b6npnvmi7uv%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxeg0a2800033b6npnvmi7uv%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

1. Click the submit button, see that Field component re-rendered 2 times when only one field is present
2. Click add field.
3. Click the submit button, see that Field component re-rendered 8 times
4. Click add field.
5. Click the submit button, see that Field component re-rendered 18 times

These steps showcase, that every field component that is subscribing to isValidating via useController is getting re-rendered **twice for every other field component that subscribes to isValidating**. So when N is the number of field component instances, the number of re-renders is N * N * 2 so that the following series is the result:
1. 2
2. 8
3. 18
4. 32
5. 50
6. ... 

### Expected behaviour

Not sure, how many re-renders should be required. I guess each field once, so N, maybe each field twice, so 2N?

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This one is probably hard to improve at least it's my limitation at the moment as hookform focuses on field validation, if each input has async validation it will get re-render with validating prop.

**Comment by andrewgreenh** [comment]
Can’t we somehow try to batch/dedupe the rerenders?

**Comment by andrewgreenh** [comment]
Ah, focus in the sense that it scrolls to the field that is validating and it happens in an order? So it goes through each field, sets the global invalidating to true, validates and sets the global isValidating to false and then it continues with the next field?
That would exactly explain the behavior. Maybe we should separate the validation field into two: one for the global process, that is set to true when field validation starts, and is set to false when all fields are done, and a fieldIsValidating that is only switched for the fields one at a time?

**Comment by bluebill1049** [comment]
as far as i know, it's not as simple as that, if you have multiple async await running at the field level, it would be difficult to batch track without complicating the library impl. As this would be a better tool with something like RXJS instead.
