### ISSUE TITLE
The new website has a security problem which stops me from seeing it

### ISSUE THREAD

**Issue by httpete** [react-hook-form/react-hook-form#12010]
### Version Number

latest

### Codesandbox/Expo snack

http://react-hook-form.com

### Steps to reproduce

Something is fishy with this graphic. Please remove it, I can't access the site.

https://www.beekai.com/marketing/logo/horizontal.svg

![image](https://github.com/react-hook-form/react-hook-form/assets/1200635/4e35b085-9d05-4d56-90e1-3618d33ee053)

### Expected behaviour

works

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
false report, https://www.beekai.com is the product that one of the bad users has used for bad acts and has been reported and removed from the platform.
