### ISSUE TITLE
issue: Fields dirty state is not updated when passing values to useForm since 7.51.0

### ISSUE THREAD

**Issue by djhi** [react-hook-form/react-hook-form#12024]
### Version Number

7.52.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/control-forked-stnhsf

### Steps to reproduce

1. Type anything in the only input
2. Note that `isDirty` stays `false`

This was first reported in #11794

### Expected behaviour

`isDirty` should be `true`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for the issue report, I am sorry to miss the previous issue replies. how come `isDirty` / `dirtyFields` are not subscribed?

**Comment by djhi** [comment]
Hi @bluebill1049! No need to be sorry, we appreciate your hard work :) I'm not sure I understand your question though. What do you mean by *not subscribed*? Does it mean we should only rely on the form state and get the field state from it?

**Comment by djhi** [comment]
I updated the sandbox to follow the documentation: https://react-hook-form.com/docs/useform/getfieldstate

It seems `isDirty` is not updated, only `isTouched` is.

**Comment by djhi** [comment]
Note: It seems it only happens when providing `values` to `useForm`

**Comment by bluebill1049** [comment]
> Note: It seems it only happens when providing `values` to `useForm`

I see, will take a look at this weekend. 

> thanks for the issue report, I am sorry to miss the previous issue replies. how come isDirty / dirtyFields are not subscribed?

this is what I mean, `formState: { isDirty }` by deconstruct the props, we can detect you are subscribed to `isDirty` and hence will enable the dirty computation and re-render

**Comment by djhi** [comment]
Unfortunately, I do subscribe to `isDirty` from the `formState` in my codesandbox and it doesn't fix the issue

**Comment by MattSchiller** [comment]
Chiming in to confirm this in my team's project as well. @djhi's sandbox & description encapsulates the issue perfectly.

If it helps for debugging, we went back to `v7.51.5` & the issue was not present.

Thanks for maintaining such a useful library!
