### ISSUE TITLE
Losing functionality on hot reload

### ISSUE THREAD

**Issue by grdnrt** [react-hook-form/react-hook-form#1203]
Hey! I'm really hooked up (no pun intended) by this library and I really want to use it in production. But there's a little issue that arise during development, which is that the inputs are not responding as expected whenever a change to the file is made and the page hot-realoads.

**Repro:**
I made a Codesandbox with [Gatsby](https://codesandbox.io/s/proud-hill-uio2x) (which is my use case), and just in case also tried it with [CRA](https://codesandbox.io/s/shy-currying-nx0tc) as well. The issue seems to appear in both environments.

The steps are:
- First go to the page, write something and hit enter. It should display the validation errors nicely.
- Now reload (completely) the page (Cmd + R or F5) or with the little reload button in Codesandbox.
- Without doing anything to the (now cleared) input, write something random on the file and save.
- It should hot reload with the new added text.
- Try to write something to trigger validation.
- It should display the errors as in step one, but it does not?

I'm new to the library so please point me if there is something missing in my implementation. Thank you!

**Comment by TheMoonDawg** [comment]
This happens to me as well. Would be cool to see it fixed, but refreshing my page to circumvent the issue isn't _terrible_, so I haven't been too bothered by it.

**Comment by bluebill1049** [comment]
hey @grdnrt & @TheMoonDawg. Thank you for checking out this lib and feedbacks. I think i should probably leave this answer on our FAQ page as well. This is actually expected behavior, let me explain :) 

React Hook Form embraces uncontrolled inputs while still give the performance enhancement with external controlled components by Controller. Your input example didn't work because there is no `defaultValue` or `defaultValues` at `useForm` for your inputs, and each re-render will reset the form state during hot re-load because they are not controlled, I don't believe this is a production behavior, I would recommend by doing a prod build by yourself. at the same time, i do understand this is probably not the best developer experience without knowing this. I will update the doc to reflect this.

here is a version with `defaultValue`: https://codesandbox.io/s/trusting-panini-k753y

**Comment by grdnrt** [comment]
Hey @bluebill1049! Thank you so much for the detailed response. I tried it again with the sandbox and it seems that the validation is still not working as expected.

As you can see, when we submit the form without any previous hot reload, this is logged: 

<img width="326" alt="Screen Shot 2020-03-15 at 14 01 35" src="https://user-images.githubusercontent.com/13141462/76706338-7d008d00-66c5-11ea-9973-53b0647299f1.png">

But if we reload the page, make a change to the file that triggers a hot reload, and we submit the form again, we get an empty array logged:

<img width="253" alt="Screen Shot 2020-03-15 at 14 06 09" src="https://user-images.githubusercontent.com/13141462/76706424-2051a200-66c6-11ea-8a70-2da60cc5b61f.png">

Even if we wrote the same text in the input as the first case when it triggers the validation

**Comment by bluebill1049** [comment]
we can improve this on dev env. i will investigate sometimes on it.

**Comment by bluebill1049** [comment]
This should fix it: https://codesandbox.io/s/trusting-panini-k753y

**Comment by bluebill1049** [comment]
I have isolated the root cause, hot re-load does trigger useEffect's callback (unsubscribe methods) which in react-hook-form we do a clean up with all the fields. as a solution for better DX, i may disable that clean up only in dev env.

https://codesandbox.io/s/trusting-panini-k753y

**Comment by grdnrt** [comment]
Awesome, that will be cool @bluebill1049. In the mean team I already started to implement it at work, thanks again!

**Comment by bluebill1049** [comment]
I will implement this soon and publish it over the weekend.

**Comment by grdnrt** [comment]
This is great! Thank you @bluebill1049  crazy fast!  🎉

**Comment by bluebill1049** [comment]
no worries @grdnrt i will publish it with everything else this weekend. Thanks for your support.

**Comment by TheMoonDawg** [comment]
Awesome to see! Thanks @bluebill1049 !

**Comment by bluebill1049** [comment]
No worries @TheMoonDawg 👍

**Comment by gfpacheco** [comment]
This is still an issue on React Native, should the solution work on native as well?
