### ISSUE TITLE
Submit the form outside the form (imperative submission)

### ISSUE THREAD

**Issue by bombillazo** [react-hook-form/react-hook-form#12030]
**Is your feature request related to a problem? Please describe.**

We've had use cases where we must submit a form using a button that is not inside the form's context, like from a modal or an external component.

Currently, one has to structure their components by wrapping items and buttons into the form context to gain access to the handleSubmit function and trigger it manually. This can be difficult to design and implement for complex Form components such as flows or other form setups and requires tightly coupling the UI to the Form scaffolding.

**Describe the solution you'd like**

Ideally, one can reference the form by `id` or use the form itself to call a `submit` function to trigger the submit instead of depending on the handleSubmit callback, which requires having the `onSubmit` function.

**Describe alternatives you've considered**

The only known alternatives are shared [here](https://github.com/react-hook-form/react-hook-form/issues/566#issuecomment-612328736): 

1. If you don't have access to the handleSubmit method. You can submit a form programmatically by passing a ref to the form DOM element and then dispatching a cancelable event. This will trigger the onSubmit handler via the RHF handleSubmit method:
```
formRef.current.dispatchEvent(new Event('submit', { cancelable: true }))
```

Handling refs isn't the ideal React solution as it is usually cumbersome, verbose, and not dev-friendly.

Another alternative is to have yet _another_ context to pass around a function that sets up the handleSubmit and onSubmit functions and can be used imperatively.

**Comment by maurer2** [comment]
Hello, wouldn't `formRef.current.requestSubmit()` also work as an alternative to `formRef.current.dispatchEvent(new Event('submit', { cancelable: true }))`?

**Comment by bombillazo** [comment]
@maurer2 I am not sure; I have not tried it. I made [this PR](https://github.com/react-hook-form/react-hook-form/pull/11801), which uses dispatchEvent and works great, and it was the only tested way to get it to work imperatively.
