### ISSUE TITLE
issue: Async defaultValues function overwrites values in React.StrictMode

### ISSUE THREAD

**Issue by xemle** [react-hook-form/react-hook-form#12036]
### Version Number

7.51.5

### Codesandbox/Expo snack

https://codesandbox.io/p/github/xemle/react-hook-form-async-defaultValues/main

### Steps to reproduce

For the Codesandbox:

1. The form field `isFirst` will have 3 different values
1. `undefined` on the initial load
2. `false` after one second by the faster second call of async `defaultValues` function
3. `true` at second 2 by the first call of async `defaultValues` function

#### Background

When using a async `defaultValues` function in `React.StrictMode` the `defaultValues` function is executed twice and the later resolve overwrites the form values. This can lead to invalid form values when values are updated between the calls.

While the controller is initiated only once by `useRef` in `useForm.ts`, the `_resetDefaultValues()` function is called twice and executes the `defaultValues` function. The `defaultValues` function returns just the a plain object the previous values are overwritten. Also the dirty, touch states are overwritten if not specified in the `resetOptions`

#### Workaround

`_resetDefaultValues()` calls `reset()` on resolve. By undocumented functionality of `reset(values)`, `values` can be also a function which receives the previous form values as argument. The async `defaultValues` function can return a function which checks if values are already set:

```
const methods = useForm({
  defaultValues: async () => {
    const values = await yourAsyncCall()
    return prev => Object.keys(prev).length ? prev : values
  },
  resetOptions: {
    keepTouched: true
  }
}
```

### Expected behaviour

If `defaultValues` is a function, it is only called once when the controller is created.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xemle** [comment]
Hi @bluebill1049 

I disagree with the decision of closing this issue. To my understanding this is a bug in the feature set of RHF. The bug appears in the dev mode while using React's strict mode, async default values and async validation with value overwrites.

Can you provide a statement why this bug is closed or how to avoid this behavior? Maybe we use RHF in a way which is not intended?

Please do not hesitate to ask open question of the If there is any further question regarding the bug or the solution.

**Comment by bluebill1049** [comment]
I have kept your PR here: https://github.com/react-hook-form/react-hook-form/pull/12304, if the async form values call will return two different values, then it's an issue with the promised return. I don't want to fight against the useEffect strict which allows useEffect to be run twice with the same outcome.

**Comment by xemle** [comment]
Thank you for the fast reply.

It is not an issue of the promise return.  Unfortunately the deep business logic details faded and can not recall our must have correctly. Somehow we need to know when the default value was called and update the form value. From my memory:

When using async defaultValues we are reacting the the form values after load. But since the defaultValue is called twice, our state gets mixed up. The goal was to identify form errors on browser page reloads (e.g. via shortcut key F5). So we split our validation in a frontend validation and frontend + backend validation. The form gets validated by frontend rules only once after the initial values were loaded to identify the form errors. This writing routine was called twice since the default values were set twice. Depending on the order of two server calls for default values and the frontend validation routine the form state was correct or incorrect. So the flag `formState.isLoading` was set to true while a 2nd call was still on the way. However `formState.isLoading` was only updated once and we could only react once.

Again: This is a blurry recap and might be the wrong direction but we had our motivation to do so.

I agree not fighting with strict mode. However, RHF uses useRef for the from controller to have only one even if useForm is called twice. So I do not understand why to avoid the 2nd call in one place (the form controller by useRef) but allow a 2nd call on another place (loading of default values). And loading of the default values is the responsibility of the controller but the controller does not take care if the default values are already in progress...

**Comment by bluebill1049** [comment]
Maybe I would recommend not using async `defaultValues` for your use case, it's probably easier to control that in your app level, with app level useEffect with `reset`.

**Comment by xemle** [comment]
OK. That would do the job. Thank you for that tip.

But why supporting async `defaultValues` then? I would recommend to have one way of doing things. I do not mind if it is `useEffect` + `reset` or async `defaultValues`. But the current state with async `defaultValues` is not safe for all cases.

Anyway. I do not want to start an emotional discussion. We can leave it as it is as "we have different opinions". 

RHF is still a great piece of software! Thank you for sharing and working on it! It is a pleasure.

**Comment by bluebill1049** [comment]
> Anyway. I do not want to start an emotional discussion. We can leave it as it is as "we have different opinions".

not at all, haha it's good feedback and discussion. I am still considering not killing the idea hence keep that PR open there.
