### ISSUE TITLE
Allow JSX to be returned as an error message

### ISSUE THREAD

**Issue by jur-ng** [react-hook-form/react-hook-form#12046]
**Is your feature request related to a problem? Please describe.**
When switching to Typescript we got errors for returning JSX elements as error message, we've been doing this for over a year and never had any issues with it. We require this behavior as we use react-i18n with a Translation component as we need translated error messages.

**Describe the solution you'd like**
It would nice if we can update the typings of Message:
```
export type Message = string;
-->
export type Message = string | JSX.element ( or ReactElement or ReactNode, whatever suits best) ;
```
As that type seems to be used everywhere we run into problems:
```
export type ValidateResult = Message | boolean | undefined;
```
```
required: Message | ValidationRule<boolean>;
```

**Describe alternatives you've considered**
We've tried overwriting the types ourselves in various ways but didn't manage to find a working solution. The only thing we can currently do is:
```                    
                    required: (
                        <Translation
                            keyName={"this-field-is-required"}
                            ns={"public.error"}
                        />
                    ) as unknown as string,
```
:(

**Additional context**
I found this issue which seems to be related: https://github.com/react-hook-form/react-hook-form/issues/11837
It is closed because of a TS limitation (?) without context. I don't see how we could not update the types, the behavior really seems to be supported. If for whatever reason this is truly not possible or not recommended could you please explain why?

**Comment by UsamaAshraf82** [comment]
+1 this can be really useful feature and it can make handleing much easier seems to be duable also and i think ReactNode as type output seem to be good

**Comment by damiaanh** [comment]
+1 this would be a nice feature, esp since it already works in normal js.

**Comment by bluebill1049** [comment]
This is a TS type limitation.  You can search for relevant issue/feature request.

**Comment by jur-ng** [comment]
> This is a TS type limitation.  You can search for relevant issue/feature request.

Yes I stated that I saw your reply to the linked issue before, and that I cannot find the relevant issues you are referring to. Could you explain why? Just closing this without any context does not help.
