### ISSUE TITLE
issue: useFieldArray fields state not refreshing

### ISSUE THREAD

**Issue by Legend999** [react-hook-form/react-hook-form#12049]
### Version Number

7.52.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/practical-poincare-jd84dt

### Steps to reproduce

1. Go to Codesandbox
2. Open console
3. Type in sth into TextInput
4. Click 'Add row'

### Expected behaviour

Created row should be filled with data from last row but is empty instead as useFieldArray doesn't refresh fields state until append/insert/remove

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 97vack** [comment]
You can use the new React Form Simple. Maybe you haven't heard of it yet, but you can use it to manage your form models and views. It is also very convenient for dynamic array processing. Documentation: [react-form-simple](https://easy-form.github.io/react-form-simple)
It has passed a lot of test verification and has been used to build hundreds of large form applications. It may be helpful to you.

**Comment by dzwiedziu-nkg** [comment]
I think it is not bug, it is optimization. Its work when you use watch instead useFieldArray to get last row value. Please try it:

```ts
[...]
  const { fields, append } = useFieldArray({
    control,
    name: "items",
  });

  fields2 = watch("items");

  const addNewRow = () => {
    const lastItem = fields2[fields.length - 1];
    console.log(lastItem);
    console.log(fields2);
    append({ ...lastItem });
  };
[...]
```

**Comment by bluebill1049** [comment]
> I think it is not bug, it is optimization. Its work when you use `watch` instead `useFieldArray` to get last row value. `watch` force to use refreshed state. Please try it:
> 
> ```ts
> [...]
>   const { fields, append } = useFieldArray({
>     control,
>     name: "items",
>   });
> 
>   fields2 = watch("items");
> 
>   const addNewRow = () => {
>     const lastItem = fields2[fields.length - 1];
>     console.log(lastItem);
>     console.log(fields2);
>     append({ ...lastItem });
>   };
> [...]
> ```

correct, `useFieldArray` doesn't re-render on each user interaction.
