### ISSUE TITLE
Trigger of the field in which the rules have changed

### ISSUE THREAD

**Issue by jullic** [react-hook-form/react-hook-form#12047]
Hi, thanks for the best library for working with forms

**Is your feature request related to a problem? Please describe.**

I use validation of the react-hook-form library itself via rules, and I would like to mention that this is the most convenient way of validation

I use react-hook-from on my project, and I have a recurring case study

Namely - conditional binding of fields depending on the contents of other fields

For example:

```ts
	const policyType = form.watch('policy.type');
	…
            <SelectPolicyType form={form} name='policy.type' />
            <FormInput
                rules={{
                    required: !!policyType,
                }}
                form={form}
                name='policy.number'
                label='Номер'
                disabled={!policyType}
            />
```

FormInput is a wrapper that utilizes the useController

```ts
import { useController } from 'react-hook-form';

import { useChangeRulesTrigger } from '@/shared/lib/hooks/useChangeRulesTrigger';

import { Input } from '../../@fields/Input';
import { IFieldInputProps } from './FormInput.props';

export const FormInput = <T extends Record<string, any>, S extends 'float' | 'int'>({ ...props }: IFieldInputProps<S, T>) => {
	const { name, rules, shouldUnregister, defaultValue, controlDisabled, form, ...otherProps } = props;
	const { control, chapterId } = form;
	const disabled = props.disabled || control._locked;

	const {
		field: { ref, ...fieldProps },
		fieldState: { error },
	} = useController({ control, name, rules, defaultValue, shouldUnregister, disabled: controlDisabled });
	useChangeRulesTrigger(form, name, rules, error);

	return (
		<Input
			required={!!rules?.required}
			error={error?.message}
			errorType={error?.type}
			{...otherProps}
			{...fieldProps}
			disabled={disabled}
		/>
	);
};
```

**Describe the solution you'd like**

With the current implementation of react-hook-form

When changing a field, the error is triggered only on the field that has been changed

But I think it would be convenient that in useController / \<Controller /> / register when changing "rules" the .trigger method would also trigger on the field where the "rules" were changed

Because otherwise you have to write something like this with even more overhead

```ts
useEffect(() => {
	const observer = form.watch((_, { name }) => {
		if (name === 'policy.type') {
			form.trigger('policy.number');
			form.trigger('policy.serial');
		}
	});
	return () => observer.unsubscribe();
}, []);
```

Or add an onChange handler to the field component (FormInput), which will do the same thing

---

In my implementation, I wrote a hook to check for changes to the "rules", and a subsequent trigger when a change occurs

This hook is used in each field component after useController (you could write a wrapper over useController)

```ts
import isEqualWith from 'lodash/isEqualWith';
import { useEffect, useState } from 'react';
import { FieldError, FieldPath, FieldValues, Path, RegisterOptions, UseFormReturn } from 'react-hook-form';

import { useEffectWithoutFirstRender } from './useEffectWithoutFirstRender';

export const useChangeRulesTrigger = <
	TFieldValues extends FieldValues = FieldValues,
	TContext = any,
	TTransformedValues extends FieldValues | undefined = undefined,
	TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>,
>(
	form: UseFormReturn<TFieldValues, TContext, TTransformedValues>,
	name: Path<TFieldValues>,
	rules?: Omit<RegisterOptions<TFieldValues, TName>, 'valueAsNumber' | 'valueAsDate' | 'setValueAs' | 'disabled'>,
	error?: FieldError | undefined,
) => {
	const [currentRules, setCurrentRules] = useState(rules);
	const [currentError, setCurrentError] = useState(error);

	useEffectWithoutFirstRender(() => {
		if (currentError) {
			form.trigger(name);
		}
	}, [currentRules, currentError]);

	useEffect(() => {
		const functionChecker = (objValue: any, othValue: any) => {
			if (typeof objValue === 'function' && typeof othValue === 'function' && objValue.toString() === othValue.toString()) {
				return true;
			}
		};
		if (!isEqualWith(currentRules, rules, functionChecker)) {
			setCurrentRules(rules);
		}
		if (!isEqualWith(currentError, error, functionChecker)) {
			setCurrentError(error);
		}
	}, [rules, error]);
};
```

There is a problem with functions and objects, if you pass them to the component without memoization, there will be an infinite re-rendering, it can be fixed by utilities, like the one I used from the library lodash, or do memoization

Is it possible to add similar functionality to the library?

Is it possible to make it an optional customization?

I think this is a fairly common case and many people would be comfortable including error trigger functions when changing rules

I made a small example of demonstrating the problem and solving it with a hook

The 'Last Name' field becomes mandatory only when the 'Name' field is non-empty

https://codesandbox.io/p/sandbox/rhf-required-djnmf3

**Describe alternatives you've considered**

I've tried using observers and input event handlers, but it's more convenient to have this logic happen "under the hood" when changing rules
I also tried to do something similar when using validation with zod, but it didn't work out well because I don't have a way to call the .trigger method in the validation scheme (maybe an additional functionality can be written).

**Comment by Cbridger-mywellabee** [comment]
I created a PR which adds the functionality to useForm and works for me with yup, its very quick and dirty and will need to be flesh out to be a proper feature. 

https://github.com/react-hook-form/react-hook-form/pull/12051
