### ISSUE TITLE
issue: getValidateError loses messages if an array is returned

### ISSUE THREAD

**Issue by doronrosenberg** [react-hook-form/react-hook-form#12058]
### Version Number

7.52.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/gracious-tom-c6nx5y

### Steps to reproduce

1. Go to the sandbox link
2. Press the submit button
3. Note that for lastName, no error is shown, while for firstName it is.  This is because lastName has a list of errors.

### Expected behaviour

The list of errors should be shown.

The cause of the bug is due to [getValidateError](https://github.com/react-hook-form/react-hook-form/blob/03f9d7278afce52ecd1fa3c8b2a5e9b8a82b7cd6/src/logic/getValidateError.ts#L5) supporting an array of strings (Message[]) but the isMessage check only supports [strings](https://github.com/react-hook-form/react-hook-form/blob/03f9d7278afce52ecd1fa3c8b2a5e9b8a82b7cd6/src/utils/isMessage.ts#L3) and not arrays of strings.  Therefore, the list of errors is lost and replaced with an empty string.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we don't support to return an array of string for error message.

**Comment by doronrosenberg** [comment]
Then shouldn't https://github.com/react-hook-form/react-hook-form/blob/5e92c1b5634bbcf18e3df14d173bced620f7392d/src/types/validator.ts#L20 to not include `Message[]`, as the typings suggest that it is supported.
