### ISSUE TITLE
feature request: attaching custom data to server errors

### ISSUE THREAD

**Issue by vera** [react-hook-form/react-hook-form#12059]
I'd like to use `setError` to manage errors returned by the server as described in the documentation:

"You can set a server or global error with root as the key. This type of error will not persist with each submission.

```
setError("root.serverError", {
  type: "400",
})
```
"
https://react-hook-form.com/docs/useform/seterror

When I do this, it would be nice if I could attach additional custom data to the error. For example:

```
setError("root.serverError", {
  type: "400",
  message: "Error message",
  custom: {
    customProp1: true,
    customProp2: "example"
  }
})
```

Actually, this already works, but it creates TypeScript errors because the error with the custom data attached does not match the `FieldError`/`FieldErrors` type defined by this library.

Is this intended usage of `setError` and would you consider changing the types to support this?

**Comment by maurer2** [comment]
Hello, I believe the new `errors` prop of the `useForm` hook, that was added recently (https://github.com/react-hook-form/react-hook-form/pull/11188) could be useful here. In order to use it, you need to create a state variable to store the backend errors that are passed to `useForm`. The validation errors that are returned from the backend, are stored in that state variable, which causes the component to rerender and show the latest error data for each field.
In order to have the error data for each field the request must return an object of type `FieldErrors` for the error messages.

Example error response'

```ts
fieldName1: {
    message: 'Error message for field 1',
    type: 'server' // not exactly sure about what to use here
  },
fieldName2: {
    message: 'Error message for field 2',
    type: 'server' // not exactly sure about what to use here
  }
```

Simplified example for form

```tsx
import { type FieldErrors } from 'react-hook-form';
import type { FormEvent } from 'react';

type TypeOfFormFields = {
// type of formFields, e.g.
}

const Form = () => {
  const [serverSideErrors, setServerSideErrors] = useState<FieldErrors<TypeOfFormFields>>({});
  const formMethods = useForm<TypeOfFormFields>({
    errors: serverSideErrors,
  });
  
  const onSubmit = async (formValues: TypeOfFormFields): Promise<void> => {
    const newServerSideErrors = await fetch('/url', formValues);

   // form has been submitted successful
   if (!newServerSideErrors) {
   // do something on success
   } else {   
    setServerSideErrors(newServerSideErrors);
  };
}

  const handleReset = (event: FormEvent<HTMLFormElement>): void => {
    event.preventDefault();

    // reset logic
    setServerSideErrors({});
  };

  return (
    <FormProvider {...formMethods}>
      <form onReset={handleReset} onSubmit={handleSubmit(onSubmit)}>
          // formfields
          <button type="reset">Reset</button>
          <button type="submit">Send</button>
      </form>
    </FormProvider>
  );
};
```

Cheers

**Comment by vera** [comment]
Thanks for your reply! I am not sure if I can use this. If I understand it correctly, the server errors I store must still be of type `FieldErrors`, so they can only contain `type` and `message`, no attached custom data.

To be precise, I would like to attach JSON data returned by the server to the error.

Is that possible somehow?

**Comment by nklhtv** [comment]
@vera I was looking into this too
How can i upvote?
If that does not go through i will be forced to stringify/parse that additional data into the `message` prop :(

**Comment by vera** [comment]
I have also solved it by stringifying/parsing my custom JSON into the `message` prop now. Not very pretty but it works
