### ISSUE TITLE
issue: Field array did note render item when it's empty string

### ISSUE THREAD

**Issue by ErBlack** [react-hook-form/react-hook-form#12053]
### Version Number

7.52.0

### Codesandbox/Expo snack

[Code example](https://codesandbox.io/p/sandbox/react-hook-form-field-array-bug-jvrd8j)

### Steps to reproduce

1. All fields after '' don't render
2. Add button with '' works only once (until some input to field)
3. Add button with stupid hack works kinda well

### Expected behaviour

Form work correctly with array of strings

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dzwiedziu-nkg** [comment]
It is the same problem: #12076 

The values retrieved by `useFieldArray` are wrapped by the `compact` function. This function cleans out falsey data (undefined, null, '', 0, false). I don't understand why they use this function in: https://github.com/react-hook-form/react-hook-form/blob/ee7b5883d029e084e433fdd873cac21dfff4a11e/src/logic/createFormControl.ts#L539
