### ISSUE TITLE
issue: validation error on submit using a required field and useFieldArray

### ISSUE THREAD

**Issue by ivanr-eb** [react-hook-form/react-hook-form#12065]
### Version Number

7.52.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/purple-glitter-fjmy3k

### Steps to reproduce

1. Open the console
2. Remove the first item clicking 'Delete' button.
3. Click on 'Submit' button.
4. See the validation error in the console:

<img width="731" alt="image" src="https://github.com/react-hook-form/react-hook-form/assets/162602760/b92378cc-e6c5-4e7a-bcc5-4e17d82cf3fc">

### Expected behaviour

There isn't any validation error in the form on submit.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Don't combine with actions 

> It's recommended to not stack actions one after another.

https://react-hook-form.com/docs/usefieldarray

```
useEffect(() => {
    trigger("test");
  }, [fields]);

const removeItem = (index: number) => {
  remove(index);
};
```

**Comment by ivanr-eb** [comment]
> Don't combine with actions
> 
> > It's recommended to not stack actions one after another.
> 
> https://react-hook-form.com/docs/usefieldarray
> 
> ```
> useEffect(() => {
>     trigger("test");
>   }, [fields]);
> 
> const removeItem = (index: number) => {
>   remove(index);
> };
> ```

Thank you so much @bluebill1049! we will test it!
