### ISSUE TITLE
issue: reset() and keepDirtyValues on dirty fields containing an array always resets the value

### ISSUE THREAD

**Issue by tibbe** [react-hook-form/react-hook-form#12097]
### Version Number

7.52.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-keepdirtyvalues-forked-l2h95t?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/react-keepdirtyvalues-forked-l2h95t?file=/src/App.js
2. Click on "Add row"
3. Click on "Start fetch"
4. Observe that after 3s the "users" field is reset to its default value (i.e. an empty array), despite being dirty (i.e. it contains one row) and have `keepDirtyValues` set.

### Expected behaviour

Fields containing array values should work with `keepDirtyValues`.

Note that this is a simplified example and I can't use `useFieldArray` in my real code as the field name is dynamic. (I'm building a form builder so all field names are dynamic and only known at runtime).

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artptr** [comment]
The issue is reproduced since 7.0.0
