### ISSUE TITLE
issue: dirtyFiedls type error

### ISSUE THREAD

**Issue by yoonminsang** [react-hook-form/react-hook-form#12091]
### Version Number

7.52.1(latest)

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-dirtyfields-mwn2z9?file=%2Fsrc%2FApp.tsx

### Steps to reproduce

1. Change input value
2. Click button

### Expected behaviour

`dirtyFields.todoList` type is `boolean[] | undefined`. But it isn't.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ploppy3** [comment]
I'm not sure to understand the issue because dirty fields are booleans, not respective input values.

**Comment by bluebill1049** [comment]
we are marking not dirty during iteration and it's causing more computation if we have to remove the root node. so keep this behaviour for now as it's the light without impact your app perf.
