### ISSUE TITLE
issue: Type of changes from useFieldArray-Functions are `undefined`

### ISSUE THREAD

**Issue by flokol120** [react-hook-form/react-hook-form#12107]
### Version Number

7.52.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-usefieldarray-rules-forked-4c2l3m

### Steps to reproduce

I added the following watch listener:
```js
React.useEffect(() => {
  const subscription = watch((values, { name, type }) => {
    console.log("values changed with type", type);
  });
  return subscription.unsubscribe;
}, [watch]);
```
1. Use any of the convenient functions of UseFieldArray that modify the form state (e. g. append, prepend, delete, ...)
2. Inspect the Dev-Console -> The type is always `undefined`

### Expected behaviour

I would have expected for the type to be `change`. If `undefined` is the intended type, feel free to close the issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we currently don't have that type for field array, only from the input level.

**Comment by flokol120** [comment]
@bluebill1049 Okay, so setting the change type to `"change"` would not be possible for now?

**Comment by bluebill1049** [comment]
hmmm i mean not sure it should be "change", some may argument is should be "append", "remove" and etc. so no plan to change that just yet.

**Comment by flokol120** [comment]
That would be even better. Currently I am detecting a reset of the form within the `watch` callback if the type is `undefined`. That way, changes from the useFieldArray are treated the same as a form reset, which is quite unfortunate.

**Comment by bluebill1049** [comment]
move to feature column for now, maybe we get to it later.
