### ISSUE TITLE
Correct way to set input defaults using controller

### ISSUE THREAD

**Issue by jtoliver** [react-hook-form/react-hook-form#1210]
**Describe the question?**

Long story short... I've built the form using a smart form ish pattern. I need to set defaultValues from redux state. I've tried to both setting defaultValues and useEffect/reset. On the actual input I've set `defaultValue=""` which overrides what defaultValues and reset has set. I figured I can use defaultValue on a input, so I wouldn't have write a function to figure out everything in defaultValues upfront. I have a very large form with nested inputs. Using watch on each component was unbearable. Any way to fix this. I'm thinking I have something setup incorrectly.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-controller-fbssm
2. 4th input should say Josh

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-fbssm

**Comment by bluebill1049** [comment]
I think this is what you want right? https://codesandbox.io/s/react-hook-form-controller-9pgbr

**Comment by bluebill1049** [comment]
![image](https://user-images.githubusercontent.com/10513364/76693758-ca2d3080-66be-11ea-9477-5d74b75886fb.png)

**Comment by jtoliver** [comment]
Yes, but i'm getting a "A component is changing an uncontrolled input of type text to be controlled" message because i'm using onChange. Which I need.

**Comment by jtoliver** [comment]
Also I appreciate the fast response. :)

**Comment by bluebill1049** [comment]
no worries, make sure you provide `defaultValues` for all the fields.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-controller-9pgbr

**Comment by bluebill1049** [comment]
i am going to close this issue, feel free to follow up with more questions (if my example above is not working for you).

**Comment by zenzjtech** [comment]
Hello, 
The code sandbox example is not working now, isn't it?

**Comment by bluebill1049** [comment]
@zenzjtech take a look this one instead: https://github.com/react-hook-form/react-hook-form/issues/1247

**Comment by zenzjtech** [comment]
Hi I've checked out the issue you mentioned.
I'm struggling with [react-number-format](https://www.npmjs.com/package/react-number-format). Could you please add an example with it also?

**Comment by bluebill1049** [comment]
@zenzjtech it's really simple https://codesandbox.io/s/react-hook-form-controller-079xx?file=/src/index.js

**Comment by zenzjtech** [comment]
Yes, I've figured out now! Sorry for the the obvious ignorance.
It seems for Controlled React-number-format, it's necessary to add the `name: value` of the field to `defaultValues`.
