### ISSUE TITLE
issue: useController with array as value does not update useFieldArray linked to same field

### ISSUE THREAD

**Issue by KarelVerschraegen** [react-hook-form/react-hook-form#12100]
### Version Number

7.52.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/magical-lichterman-dmdh4c?file=%2Fsrc%2FApp.tsx%3A11%2C6

### Steps to reproduce

# Preface
We are currently in the process of migrating over 450+ forms from react-final-form over to react-hook-form. We are approaching this issue with a gradual strategy that allows us to dynamically switch between form implementations to minimise global impact in case something were to go wrong.
```
<Form provider="react-hook-form | react-final-form"></Form>

const useField = () => {
  const isReactHookForm = ...

  return isReactHookForm ? useControllerReactHookForm : useFieldReactFinalForm;
}
```

This does somewhat prevent us from using react-hook-form as it was intended as we need to keep backwards compatibility with our current Form implementation and usage.

# Issue
We have multiple (react-final-form) `useField`s that subscribe to the same `name` from different components. 
In react-hook-form, we achieve a similar implementation by using multiple `useController`s that point to the same `name`. (Ideally, we would only have one `useController` per `name` and use `useWatch`...)

Some (react-final-form) `useField`s are used to change the value of `name` that point to an array value.
In react-hook-form, we have already noticed that multiple `useFieldArray`s with the same `name` operate independently of each other and updating one `useFieldArray` does not update the others. To keep backwards compatibility, we _do_ need to have this behaviour.

Our open questions are:
- Is it intended behaviour that multiple `useFieldArray`s do not update the others?
- Is it intended behaviour that a `useField` that points to an array does not update the `useFieldArray` with the same name?
- Is it intended behaviour that a `setValue` will notify all `useController` and `useFieldArray` with the same name?

In the CodeSandbox you'll see that:
- the `updateWithSetValue` notifies all subscribers.
- the `updateWithController` only notifies other `useController`s with the same name but does not notify `useFieldArray` with the same name
- the `updateWithFieldArray` does not notify other `useFieldArray`s but does notify other `useController`s

Sorry for somewhat abusing your library :(
Thank you!

### Expected behaviour

- Changing the value of a `useController` updates also notifies the `useFieldArray` with the same name.
- Changing one `useFieldArray` also notifies other `useFieldArray`s with the same name.

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is something we probably won't address at this stage, if this is important to support, I would suggest to keep using react-final-form. As it is an awesome form library as well.
