### ISSUE TITLE
issue: Reseting default values for array field marks it always as dirty

### ISSUE THREAD

**Issue by arkadiy93** [react-hook-form/react-hook-form#12118]
### Version Number

latest

### Codesandbox/Expo snack

[sandbox link](https://codesandbox.io/p/sandbox/react-hook-form-get-started-ts-forked-jp7mp9?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clysooj5i00063b6jchvv8jx9%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clysooj5i00023b6jg9nmyhqd%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clysooj5i00033b6j2wu718ft%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clysooj5i00053b6j26vswaf8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clysooj5i00023b6jg9nmyhqd%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clysooj5i00013b6jcimxxtf7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clysooj5i00023b6jg9nmyhqd%2522%252C%2522activeTabId%2522%253A%2522clysooj5i00013b6jcimxxtf7%2522%257D%252C%2522clysooj5i00053b6j26vswaf8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clysooj5i00043b6jo34muuhk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clysooj5i00053b6j26vswaf8%2522%252C%2522activeTabId%2522%253A%2522clysooj5i00043b6jo34muuhk%2522%257D%252C%2522clysooj5i00033b6j2wu718ft%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clysooj5i00033b6j2wu718ft%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Clicking on reset button one, marks the field as dirty. (reset)
2. Clicking on reset button two, does not mark the field as dirty. (setValue)

### Expected behaviour

I expect that in both cases the field won't get flagged as dirty.
`dirtyFields` in the log will also display shape:
```
{
  example:  [false]
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
as value match the original value `example: ["test"]`, hence not set isDirty to true.

**Comment by arkadiy93** [comment]
> as value match the original value `example: ["test"]`, hence not set isDirty to true.

exactly! But this is not whats actually happening. 
When you use the 
```
reset(
      {
        example: ["test"],
      },
      { keepDefaultValues: true }
    );
```
its getting flagged as dirty! Please click button reset one.

**Comment by arkadiy93** [comment]
@bluebill1049 please re-open as this is definitely not the expected behaviour.
