### ISSUE TITLE
clearing errors object when to return errors: {} from a resolver

### ISSUE THREAD

**Issue by github0013** [react-hook-form/react-hook-form#1211]
**Is your feature request related to a problem? Please describe.**

1. mode: onChange
2. use validationResolver
3. have errors in more than one inputs
4. validate all inputs by one of the inputs, and return `errors: {}` in the resolver

Currently `errors: {}` doesn't clear `const {errors} = userForm()` this errors object entirely.   resolver only updates the errors for the specific input you change.

**Describe the solution you'd like**

I would like to see `errors` object being cleared to `{}` by giving `errors: {}` from a resolver.

**Describe alternatives you've considered**
N/A

**Additional context**

https://codesandbox.io/s/react-hook-form-validationresolver-errors-j2iyu

**Comment by bluebill1049** [comment]
ok @github0013 i have completely my investigation. Short story, i think we will keep what we got for now. Let me explain the reason behind. Feel free to leave your thoughts as well. 

The way we trigger re-render is based on error appear/disappear: https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L563 which is one of the performance enhancement for this library. If error is persist there is no need to re-render, so does when an error gets resolved, and it's cheap to running against a single error at a time. We can invest into errors object comparison, but then it's not efficient at least with my estimation for now. 

let me know if this make sense.

**Comment by github0013** [comment]
Thank you for spending time on this.
One of the major reasons that we want to use this library against Formik is "performance."   So I guess if you don't feel comfortable, this should be the way.

It's just gonna a little gotcha we have to keep in mind when to use resolver.

**Comment by bluebill1049** [comment]
good point @github0013 i will re-open this issue and update the documentation.

**Comment by bluebill1049** [comment]
website updated.

**Comment by EitanElbaz** [comment]
Hi @bluebill1049 - thank you for this amazing library!

I've been using the YUP resolver which is mostly exactly what I need. Let me lay out a scenario which this decision makes really hard.

Imagine you have a sign up form and you have two fields, `password` and `password_confirmation`.

You want to check for stuff like min length, special characters, string match, etc.

The user enters a password into the `password` field which satisfies all but the criteria to match to the confirmation password (as it has not been filled yet).

User enters the confirmation password which passes all the checks AND matches the first password. Problem is that the `password` field still has an error assigned to it which says it doesn't match `password_confirmation`. If I just focus and blur on the `password` input, the error is cleared.

I know I can use stuff like `useWatch` and `useEffect` to manually clear the errors, but it feels like something we absolutely shouldn't need to do. Especially when the yup resolver returns an empty errors object.

Many thanks for the library once again. It has been a life saver, but I really do wish you could reconsider you decision.
