### ISSUE TITLE
issue: useFieldArray and Controller mix shows previous value

### ISSUE THREAD

**Issue by deepdawn0** [react-hook-form/react-hook-form#12111]
### Version Number

7.40.0, 7.52.1 (tested latest as well)

### Codesandbox/Expo snack

N/A

### Steps to reproduce

I'm really sorry that I couldn't reproduce the issue on codesandbox and I know that is annoying in such a project but I'd be glad to get a hint if you ever faced such a problem.

#### Screen Recording
![Peek 2024-07-17 15-18](https://github.com/user-attachments/assets/67294e4d-5714-43f2-b7a7-9887b6d3feb4)

The issue is that when removing the item and showing some "Empty state" and then adding a first item of empty strings I still see old value.

when console logging the `fields` value from the `useFieldArray` hook I see empty strings but the `<Controller/>` still point to the old value.

#### Code for the inputs
![image](https://github.com/user-attachments/assets/1febfd73-b67e-4b58-b857-b912848bef91)

#### Code for the wrapper with showing empty state / the components when needed
![image](https://github.com/user-attachments/assets/b008d440-0953-4314-ae1b-bfbd660f8328)

I added `defaultValue` to the Controller but it didn't resolve it. The only thing that resolves this is to add `shouldUnregister` to the controller to wipe off the old value when the inputs are unmounted but the issue is that if we unmount this form section then this prop will cause the data to erase so it's not reliable.

### Expected behaviour

To see empty strings as they're appended into the `onAddClick` of the `FormEmptyBlock` (Empty state)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jrojas-qventus** [comment]
Hello everyone, I am pleased to be using such a robust library.
I am going through the same stuff and I wanted to know if you might have an idea of why this is happening @bluebill1049.

Thanks a lot for the library. (:

**Comment by jrojas-qventus** [comment]
@deepdawn0 I managed to "solve" this by passing the default values of my fields.
In the documentation it says: _When you append, prepend, insert and update the field array, the obj can't be empty object rather need to supply all your input's defaultValues._

**Comment by giangtran8396** [comment]
Hello guys, any fixing because I got the same problem when try to delete and append
