### ISSUE TITLE
Feat: add a recursive depth limit to path (eager.d.ts)

### ISSUE THREAD

**Issue by PFJoey** [react-hook-form/react-hook-form#12110]
**Is your feature request related to a problem? Please describe.**

Adding complex nested types to React Hook Form will start an infinite deep type-check.

**Describe the solution you'd like**

Currently we have applied a patch to /dist/types/path/eager.d.ts where the PathInternal and ArrayPathImpl type is capped at X depth. 
This ensures that typescript does not crash.

Perhaps having this as a generic prop of useForm would be nice for everyone struggling with this.

**Describe alternatives you've considered**

**Additional context**

**Comment by vuggy17** [comment]
came to this when looking for any solution for TS type suggestion too slow while using with recursive nested class

**Comment by pax-k** [comment]
Yep, installing `react-hook-form` makes IntelliSense to hang infinitely in VSCode.

**Comment by sirwacheski** [comment]
> Yep, installing `react-hook-form@7.52.2` makes IntelliSense to hang infinitely in VSCode.

same

**Comment by bluebill1049** [comment]
let's track in here: https://github.com/react-hook-form/react-hook-form/issues/12110
