### ISSUE TITLE
issue: useEffect not triggering on value watched with useFieldArray 

### ISSUE THREAD

**Issue by CutiePi** [react-hook-form/react-hook-form#12117]
### Version Number

7.49.3

### Codesandbox/Expo snack

[code sandbox](https://codesandbox.io/p/sandbox/controlled-field-array-forked-5p3tr2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyt3bs7c00073b6jzz0c5svi%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyt3bs7c00033b6jq58awc0g%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyt3bs7c00043b6jadvucmz7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyt3bs7c00063b6j4f4777r0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyt3bs7c00033b6jq58awc0g%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyt3bs7c00023b6jbntffmti%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clyt3bs7c00033b6jq58awc0g%2522%252C%2522activeTabId%2522%253A%2522clyt3bs7c00023b6jbntffmti%2522%257D%252C%2522clyt3bs7c00063b6j4f4777r0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyt3bs7c00053b6jxne5nko2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clyt3bs7c00063b6j4f4777r0%2522%252C%2522activeTabId%2522%253A%2522clyt3bs7c00053b6jxne5nko2%2522%257D%252C%2522clyt3bs7c00043b6jadvucmz7%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clyt3bs7c00043b6jadvucmz7%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Setup a simple form
2. use field array
3. useEffect on watch of field array key when editing field within field array. 
4. useEffect not triggered

### Expected behaviour

`useEffect` should be triggered by the dependency when a value is edited.

It works on other versions, on this version it works on non-array fields.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexandermirzoyan** [comment]
According to the documentation for the [watch() API](https://www.react-hook-form.com/api/useform/watch/), seems you need to pass a callback function to the `watch()` function.

Maybe I am wrong, please let me know.

**Comment by bluebill1049** [comment]
> watch result is optimised for render phase instead of useEffect's deps, to detect value update you may want to use an external custom hook for value comparison.

https://react-hook-form.com/docs/useform/watch

**Comment by CutiePi** [comment]
> > watch result is optimised for render phase instead of useEffect's deps, to detect value update you may want to use an external custom hook for value comparison.
> 
> 
> 
> https://react-hook-form.com/docs/useform/watch

Yeah I had seen this. I was mostly wondering why it worked on the other version and not this one. 

Also, note watch worked on all other fields in my test, it exclusively doesn't work on the field arrays.
