### ISSUE TITLE
issue: The https://react-hook-form.com/ website is down

### ISSUE THREAD

**Issue by kildareflare** [react-hook-form/react-hook-form#12120]
### Version Number

V7

### Codesandbox/Expo snack

https://react-hook-form.com

### Steps to reproduce

1. Go to https://react-hook-form.com/get-started

### Expected behaviour

Page loads

Not a bug with the repo itself, but the linked website and thus related documentation is down

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
It's back now 👍
