### ISSUE TITLE
Validation gets triggered on blur even the mode was set to 'onChange'

### ISSUE THREAD

**Issue by rmlevangelio** [react-hook-form/react-hook-form#1213]
**Describe the bug**
Hi, I just found a bug with the onChange mode. Validation gets triggered on blur even the mode was set to `onChange`

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-controller-1wurt
2. Click on Uncontrolled input textbox (dont type anything)
3. Remove the focus
4. Error is shown 

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-1wurt

**Expected behavior**
Error should not be shown if the mode is `onChange` because the user doesn't perform any input changes. This should only happen if the mode is `onBlur`

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave
 - Browser: chrome
 - Version: 80.0

**Comment by rmlevangelio** [comment]
Actually, I think this behaviour is expected. If the mode was set to `onChange`, it should also trigger the `onBlur`. 

If this is the case, it’s the other way around.  The controlled component doesn’t trigger the validation if the the input has been focused and blurred without user input.

**Comment by bluebill1049** [comment]
`onChange` should only trigger validation `onChange`, this is a bug which i will fix for native input.

**Comment by rmlevangelio** [comment]
@bluebill1049 is it possible to use two modes? Like I want to use `onChange` plus `onBlur`?

**Comment by bluebill1049** [comment]
not this stage, you will have attach onBlur (triggerValidation) with onChange

**Comment by bluebill1049** [comment]
feel free to send a feature request, i can tag it for voting and keep it at the back log in the project.

**Comment by tommedema** [comment]
I have exactly the same issue and made a demo video here:

https://app.usebubbles.com/e502420e-c5bb-4106-b55d-1dfd316b7e69

**Comment by tommedema** [comment]
@bluebill1049 thanks for the fix but do you know how to install this? I tried:

```
yarn add 'git+ssh://git@github.com:react-hook-form/react-hook-form.git#d3bcfcb44cce770badf2780f83786d3a678b4ec1'
```

but Typescript cannot find the package: `Cannot find module 'react-hook-form'.ts(2307)`

**Comment by bluebill1049** [comment]
you want a beta version @tommedema?

**Comment by tommedema** [comment]
Yes, please @bluebill1049

**Comment by bluebill1049** [comment]
I will re-open this issue so i remind myself to publish a beta version.

**Comment by rmlevangelio** [comment]
@bluebill1049 I saw you released this already on 5.1.1 right?

**Comment by bluebill1049** [comment]
no, not really. i will have to release a beta version for this.

**Comment by bluebill1049** [comment]
`5.1.2-beta.1` here you go.

**Comment by tommedema** [comment]
Tested it just now and it seems to work well. Thanks!

**Comment by bluebill1049** [comment]
awesome thanks @tommedema
