### ISSUE TITLE
issue: [formState] Incorrect type of dirtyFields for lists and objects

### ISSUE THREAD

**Issue by islami00** [react-hook-form/react-hook-form#12139]
### Version Number

7.48.2

### Codesandbox/Expo snack

https://stackblitz.com/edit/vitejs-vite-ds1zad?file=src%2Fcomponents%2FTestFormTwo.tsx

### Steps to reproduce

1. Open the stackblitz repro
2. Click on an option under 'pick a fruit'
3. Click on `Sets object.furtherNested to true`
3. Notice the value of dirtyFields.list in the console is different from the type in the ide  when you hover on `methods.formState.dirtyFields`. It is closer to `ActualDirtyFields`

### Expected behaviour

The dirtyFields type should match what is expected at runtime

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
i think the same issue: https://github.com/react-hook-form/react-hook-form/issues/12091#issuecomment-2292469963

**Comment by islami00** [comment]
Hello @bluebill1049.  No, I don't think it is the same issue. The types for dirtyFields don't match the value in runtime.

Take the following form data:

```ts
const value = {
  test: { 
     nestedValue: "sth"
  }
}
```

Editing `test` with a `Controller` is expected to give the following `dirtyFields`.

```ts
type dirtyFields = {
  test: boolean | undefined
}
```

But the actual type in typescript is:

```ts
type dirtyFields = {
  test: { 
     nestedValue: boolean | undefined
  } | undefined
}
```

Which would lead to a type error in runtime when trying to access `dirtyFields.test?.nestedValue`
