### ISSUE TITLE
issue: subscribing to a nested field where the parent is null, results in a value in the submit

### ISSUE THREAD

**Issue by Sam-Persoon** [react-hook-form/react-hook-form#12146]
### Version Number

7.52.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-get-started-ts-forked-hkrpwq?file=%2Fpackage.json%3A16%2C25&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clz8etjim00062e69ji5ljxp5%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clz8etjim00022e69ju1710hl%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clz8etjim00032e698hg3x1si%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clz8etjim00052e69z921dumh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clz8etjim00022e69ju1710hl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz8etjim00012e697zonlafj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clz8gvvax00022e69hhflfoit%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A16%252C%2522startColumn%2522%253A25%252C%2522endLineNumber%2522%253A16%252C%2522endColumn%2522%253A25%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clz8etjim00022e69ju1710hl%2522%252C%2522activeTabId%2522%253A%2522clz8gvvax00022e69hhflfoit%2522%257D%252C%2522clz8etjim00052e69z921dumh%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz8etjim00042e69rkvqugl8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clz8etjim00052e69z921dumh%2522%252C%2522activeTabId%2522%253A%2522clz8etjim00042e69rkvqugl8%2522%257D%252C%2522clz8etjim00032e698hg3x1si%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clz8etjim00032e698hg3x1si%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

1. Gives values to `useForm`, for example ` { foo: null }`
2. Subscribe using `useController` on a child of `foo`, for example `useContoller({name: "foo.bar" })`
3. Submit or subscribe on the current form values
4. Both will have `{ foo: { bar: null } }` as data

### Expected behaviour

Some of the below for step 4:
- Both will have `{ foo: {} }` as data
- Both will have `{ foo: null }` as data
- Both will have `{ foo: { bar: undefined } }` as data

With the first option the most likely. Which is indeed the case for `"react-hook-form": "7.0.0"`. If you initialise your form with `{ foo: "test" }` the same case above will indeed give  `{ foo: {} }` in version `7.52.1`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sam-Persoon** [comment]
The issue seems to be introduced in version `7.41.0`

**Comment by bluebill1049** [comment]
This certainly makes the form value more complicated with `null` with object value. I would recommend providing object value instead. 

> The issue seems to be introduced in version 7.41.0

please refer to the release, I am sure it's related to one of the issue fix. Won't change to the current behavior at this stage.
