### ISSUE TITLE
react-select not working during onChange

### ISSUE THREAD

**Issue by kiansenggoh** [react-hook-form/react-hook-form#1214]
hi react-select onChange doesn't update the component properly. 
after the onChange's return, the react-select display blank.

using your documentation codesandbox url,
https://codesandbox.io/s/react-hook-form-controller-079xx

i added the following code to the react-select's Controller,
`onChange={([selected]) => {
          // React Select return object instead of value for selection
          return { value: selected };
        }}`

the react-select display is empty after i selected chocolate.
![image](https://user-images.githubusercontent.com/56799988/76704138-ddb5b700-6711-11ea-8312-3132fb890ffc.png)

**Comment by bluebill1049** [comment]
make sure you have the latest version: https://codesandbox.io/s/react-hook-form-controller-079xx

**Comment by skashi** [comment]
This is broken again in 6.x.x.

@bluebill1049 I used your link and could confirm it is working in 5.7.2 but not in 6.0.0 or 6.0.8

**Comment by bluebill1049** [comment]
@skashi please take a look at the doc for `render`, we have updated the API https://react-hook-form.com/api#Controller

**Comment by skashi** [comment]
Thanks @bluebill1049. `render` did work for me (and not using `as`).

Just a note, having a look at the API docs [link](https://react-hook-form.com/api#Controller) you posted it does claim to work with `as`:

> Controller will inject onChange, onBlur and value props into the component.

Maybe it was more of a confusion on my part

**Comment by bluebill1049** [comment]
> Thanks @bluebill1049. `render` did work for me (and not using `as`).
> 
> Just a note, having a look at the API docs [link](https://react-hook-form.com/api#Controller) you posted it does claim to work with `as`:
> 
> > Controller will inject onChange, onBlur and value props into the component.
> 
> Maybe it was more of a confusion on my part

hey @skashi with `as` prop we are pass down those props :( probably because react-select onChange is return an object instead an event.

**Comment by ozhanefemeral** [comment]
`onChange={([selected]) => selected}`

works for me.
