### ISSUE TITLE
issue: `useWatch` value changes on every re-render

### ISSUE THREAD

**Issue by JoseVSeb** [react-hook-form/react-hook-form#12152]
### Version Number

7.52.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/peaceful-ace-c78vv6

### Steps to reproduce

Just open the CodeSandbox link to see the issue in console. OR follow these steps:

1. watch fields using `useWatch` by not specifying `name` or by giving a list of names (more than one).
2. change a primitive value in form by depending on a reference value in `useEffect` (set the same value so that re render shouldn't trigger in the first place).
3. log reference value in a seperate `useEffect`
4. see the console for re render logs of reference value even if it never changed (infinite render).

### Expected behaviour

the watched reference value should not change on re render (unless the reference value changes in form) even if update is called on form. (issue is not observed in earlier versions, tested in 7.4)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by JoseVSeb** [comment]
this issue might be related to https://github.com/react-hook-form/react-hook-form/issues/11910 since this is likely a symptom of not following the rules of react.

**Comment by razh** [comment]
Previous discussion:

- https://github.com/react-hook-form/react-hook-form/pull/9369
- https://github.com/react-hook-form/react-hook-form/issues/10027

**Comment by JoseVSeb** [comment]
Well, this _is_ a violation of rules of react. Not the shadow clone, per se, but not properly accounting for what changed.
