### ISSUE TITLE
Unexpected dirtyFields Output When Using keepDefaultValues Option with reset

### ISSUE THREAD

**Issue by PavelTankovich** [react-hook-form/react-hook-form#12165]
### Version Number

7.31.0 - 7.52.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-issue-xfdpzq?file=/index.js

### Steps to reproduce

**This issue does not occur starting from version 7.31.0; in versions below, everything works correctly.**

1. Go to [Example](https://codesandbox.io/s/react-hook-form-issue-xfdpzq?file=/index.js)
2. Click on **Reset**
3. Look at console
4. In the console, we observe the output `dirtyFields {firstName: false, gender: Array(0)}`

### Expected behaviour

We expect `dirtyFields {firstName: false, gender: false}`. If we remove the `keepDefaultValues` option from `reset`, we get the expected behavior.  
As I understand, the problem is that `rhf` perceives an array of values for `Select` as an array of fields in this case, and the issue arises in the following location:
![image](https://github.com/user-attachments/assets/0ce77a88-5f8d-4748-8b56-c8110f60345f)

### Relevant log output

```shell
dirtyFields {firstName: false, gender: Array(0)}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
for "array" field it will be deep match against the `defaultValues`, we are not vomiting empty array at this stage, as this would require more computation, and it was a bug original which got fixed later on.

**Comment by PavelTankovich** [comment]
> for "array" field it will be deep match against the `defaultValues`, we are not vomiting empty array at this stage, as this would require more computation, and it was a bug original which got fixed later on.


Sorry, maybe I misunderstood your answer, please correct me if I am wrong.  
The problem is that `rhf` should return `true` or `false` in the value of the `dirtyFields` key, but it returns me an array of selected values. In my opinion this is not correct logic, especially in older versions everything works correctly.   
If we don't set `keepDefaultValues', the behaviour of dirtyFields remains correct. The problem only occurs when `keepDefaultValues` is used.  
Could you please tell me if you have looked at my example?
**Correct operation:**  
```
reset(getValues()) -> dirtyFields {firstName: false, gender: false}
```
**Wrong operation:**  
```
reset(getValues(), {.
  keepDefaultValues: true
}) -> dirtyFields {firstname: false, gender: Array(0)}
```  
Can you tell me how the second case study turned `false` into an array in `dirtyFields`?

**Comment by PavelTankovich** [comment]
@bluebill1049 You can downgrade the version as indicated in the description and observe the correct behavior of dirtyFields.
