### ISSUE TITLE
issue: Integer default value not working for radio inputs

### ISSUE THREAD

**Issue by bgirschig** [react-hook-form/react-hook-form#12172]
### Version Number

7.51.3

### Codesandbox/Expo snack

https://snack.expo.dev/NruvNEBuvvn_v5F0RLXdC

### Steps to reproduce

Open the [snack](https://snack.expo.dev/NruvNEBuvvn_v5F0RLXdC)

### Expected behaviour

**Expected**: The default value ("number 192") is selected on load
**Actual**: No value is selected
**"fix"**: cast the default value to a string

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Relevant log output

```shell
no logs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks very much for the PR, i would build a controlled component and wrapped with Controller. That's what controller was build for, for register radio input would be limited to string. again appreciate to look into this and provide a PR.
