### ISSUE TITLE
issue: isDirty doesn't work at the first time

### ISSUE THREAD

**Issue by dvlptuankiendo** [react-hook-form/react-hook-form#12195]
### Version Number

7.52.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/youthful-wiles-cm8cf6

### Steps to reproduce

type the text "1" to the input and immediately click the button "check", you can see the log that isDirty is false

### Expected behaviour

isDirty is surposed to be true

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kandabi-zorro** [comment]
Replicated on our project.

**Comment by palashk92** [comment]
Can't replicate it with `isDirty` either in the codesandbox example or in our project, but we're encountering a similar issue with `formState.isValid`

**Comment by dvlptuankiendo** [comment]
My current solutions is
1. wrap check function with useCallback to ensure it recreated on isDirty changes
 `const check = useCallback(
    (e) => {
      e.preventDefault();
      alert(formState.isDirty);
      console.log(formState.isDirty);
    },
    [formState.isDirty]
  );`
2. specifically select isDirty from formState
`const check = useCallback(
    (e) => {
      e.preventDefault();
      alert(formState.isDirty);
      console.log(formState.isDirty);
    },
    [formState.isDirty]
  );`

**Comment by marlonpp** [comment]
there is also a mismatch between `dirtyFields` and `isDirty`.
`isDirty = true` while `dirtyFields = {}`

**Comment by marlonpp** [comment]
@bluebill1049 I'm curious why this won't be fixed.
don't you see it as an issue?

**Comment by SikoraKam** [comment]
I also encountered this behavior. Fun fact, adding a `console.log(formhook.formstate.isDirty)` inside a component also helps
