### ISSUE TITLE
issue: Controller is re-rendering fields unnecessarily 

### ISSUE THREAD

**Issue by AmrAbdulrahman** [react-hook-form/react-hook-form#12198]
### Version Number

latest

### Codesandbox/Expo snack

[LINK](https://codesandbox.io/p/sandbox/react-hook-form-v7-form-context-forked-j6ykqp?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm01ckz6z00063b6ij6zrgwol%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm01ckz6z00023b6ilam68ofr%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm01ckz6z00033b6iscvwdlh4%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm01ckz6z00053b6iyciwnhvj%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm01ckz6z00023b6ilam68ofr%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm01ckz6z00013b6incjra9yt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522id%2522%253A%2522cm01ckz6z00023b6ilam68ofr%2522%252C%2522activeTabId%2522%253A%2522cm01ckz6z00013b6incjra9yt%2522%257D%252C%2522cm01ckz6z00053b6iyciwnhvj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm01ckz6z00043b6is9ttcplc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%255D%252C%2522id%2522%253A%2522cm01ckz6z00053b6iyciwnhvj%2522%252C%2522activeTabId%2522%253A%2522cm01ckz6z00043b6is9ttcplc%2522%257D%252C%2522cm01ckz6z00033b6iscvwdlh4%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm01ckz6z00033b6iscvwdlh4%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Start typing in 'field 1'
2. Observe `rendering field 1` and no `rendering field 2` (which is perfect ✅ )
3. Click on 'change parent state' button to change parent component internal state
4. The button only causes a re-render BUT doesn't affect the form's state _at all_.
5. Observe both fields of the forms being re-rendered for absolutely no reason.
6. We are developing pretty complex forms that contain 100+ fields, this needless rendering is making our form laggy and very slow.

### Expected behaviour

The `render()` prop of `Controller` should be aware of when to render and when to memoize the already rendered field.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gund** [comment]
The problem is actually within the RHF hooks like `useController` as they are causing the re-renders even if the leaf components are fully memoized and no props have changed - the hook itself is causing the rerender because of the root component rerendering and triggering a call to the `useForm` hook, even when there were no changes to the form state at all.

Original example did not showcase the memoization but here is the fork with full memoization of input component plus extra memo of the controllers as well just for a good measure: https://codesandbox.io/p/sandbox/react-hook-form-v7-form-context-forked-6np5h2?file=%2Fsrc%2Findex.js%3A22%2C12

If you see in the logs when you type in an input it only rerenders single input which is expected, but when you click the button it forces every input to rerender for no reason - nothing in the form has been changed. Just the fact that root component that contains the form hook was rerendered it triggers all other RHF hooks to rerender and making the entire form rerender.

This might seem like a subtle imperfection but if you consider big enough forms with couple of hundreds of questions any tiny update on the root level will cause a huuuge performance bottleneck and UI will just freeze for a few seconds (this is what we've been experiencing on the real project in production).

**Comment by 0215Arthur** [comment]
> The problem is actually within the RHF hooks like `useController` as they are causing the re-renders even if the leaf components are fully memoized and no props have changed - the hook itself is causing the rerender because of the root component rerendering and triggering a call to the `useForm` hook, even when there were no changes to the form state at all.
> 
> Original example did not showcase the memoization but here is the fork with full memoization of input component plus extra memo of the controllers as well just for a good measure: https://codesandbox.io/p/sandbox/react-hook-form-v7-form-context-forked-6np5h2?file=%2Fsrc%2Findex.js%3A22%2C12
> 
> If you see in the logs when you type in an input it only rerenders single input which is expected, but when you click the button it forces every input to rerender for no reason - nothing in the form has been changed. Just the fact that root component that contains the form hook was rerendered it triggers all other RHF hooks to rerender and making the entire form rerender.
> 
> This might seem like a subtle imperfection but if you consider big enough forms with couple of hundreds of questions any tiny update on the root level will cause a huuuge performance bottleneck and UI will just freeze for a few seconds (this is what we've been experiencing on the real project in production).
> 
> EDIT: What we've observed actually is that `useController` hook was returning new objects `field` and `fieldState` on those rerenders even when nothing really changed, and moreover callback props on `field` like `onChange` constantly change references too causing any memoization checks to fail and render for no reason. We were able to manually deconstruct these objects and by using techniques to stabilize changing callbacks we recreated a stable versions of those objects, thus preventing those useless rerenders. But of course it would be nice if this would be done natively by the library so we don't have to hack around like this.
> 
> Please let me know if you need any extra info to help resolve this.

Thanks for your analysis. So can you provide more examples to prevent the re-render?
Thank you very much.
