### ISSUE TITLE
issue: [React Native] React Hook Form causes the QuickType bar on iOS to flicker on every input

### ISSUE THREAD

**Issue by valtism** [react-hook-form/react-hook-form#12202]
### Version Number

7.52.1

### Codesandbox/Expo snack

https://snack.expo.dev/@prune_dev/rhf-password-flicker

### Steps to reproduce

1. Go to the Expo snack linked
2. Open snack on iOS using Expo Go by scanning the QR code
3. Tap the email input
4. Start typing
5. The QuickType bar (displaying `Passwords`) should flicker on each keypress

### Expected behaviour

The QuickType bar should not flicker on each keypress.

See this thread for more discussion: https://github.com/facebook/react-native/issues/39411 specifically https://github.com/facebook/react-native/issues/39411#issuecomment-1975092529 and below for discussion related to RHF

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I don't think this is related to this library.
