### ISSUE TITLE
issue: `useForm`’s `context` doesn’t update with new values

### ISSUE THREAD

**Issue by selrond** [react-hook-form/react-hook-form#12213]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/rhf-stale-context-49nfg3

### Steps to reproduce

1. Go to https://codesandbox.io/p/sandbox/rhf-stale-context-49nfg3
2. Open console
3. Click on Add context... buttons
4. Observe the context not updating regardless of the update method use

### Expected behaviour

Context should update, as [per docs](https://react-hook-form.com/docs/useform#context) it’s a mutable object.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
There is no such supported usage. Context doesn't trigger re-render only as payload to your resolver.

**Comment by selrond** [comment]
So the context only takes the initial value right?
