### ISSUE TITLE
feat: Add additional Types that do not include the ref in FieldValues

### ISSUE THREAD

**Issue by AlemTuzlak** [react-hook-form/react-hook-form#12214]
**Is your feature request related to a problem? Please describe.**
Yes, If you check this thread on `remix-hook-form` you can see the cause of the request:
https://github.com/forge42dev/remix-hook-form/issues/100#issuecomment-2312432560

**Describe the solution you'd like**
A different type, something like `FieldValuesNoRef` that keeps the ref out because when validators are used on the server there are no hooks.

**Describe alternatives you've considered**
Alternatives would be that I implement this type in `remix-hook-form` but I'd like to first know if there is a chance to get this from react-hook-form directly as I'd like to keep the wrapper around it minimal and this would be a great step towards the server-side form handling in react as refs can't be serialized from the server in any case so this is bound to come up at some point

**Comment by bluebill1049** [comment]
moving to pending feature request.
