### ISSUE TITLE
Clean dirty state after using setValue

### ISSUE THREAD

**Issue by lobopl** [react-hook-form/react-hook-form#1221]
I have big nested form that has multiple field that depend on different fields, everything works great, but I want to add feature blocking closing this big form if user made some changes (basically he needs to confirm this action). While user edit this form data is filled with reset for fields that are always visible and setValue for fields that are not always visible (because if user change logic to hide fields and again show hidden fields they has to be empty see my other question why https://github.com/react-hook-form/react-hook-form/issues/1041)

So naturally i wanted to use formState.dirty to show confirmation while user made some changes, but if i use setValue form automatically becomes dirty, is it possible to clean dirty state programatically?

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-043h0
2. Click on "SET VALUE" button
3. check printed console log containing formState.dirty

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-043h0

**Comment by bluebill1049** [comment]
we don't have anything manually to change formState such as dirty, but you can use `reset` as work around.

**Comment by lobopl** [comment]
Unfortunately i cannot use reset, because i cannot have some fields default values to be set but they have to get values set see https://github.com/react-hook-form/react-hook-form/issues/1041 i will try to work around this problem

**Comment by bluebill1049** [comment]
`reset(getValues())`?

**Comment by lobopl** [comment]
this will set default values so it will not work as i want

**Comment by bluebill1049** [comment]
get values the form and set the form values, and then reset the formState?

**Comment by alakarastrin** [comment]
> get values the form and set the form values, and then reset the formState?

we need to add some functionality to be able to reset formState values, that would be awesome!
I currently have a case where I setValue in the form after getting it from API when I change one of the inputs according to url. I rely upon dirty to check if the form has been touched by the user, but because of setValue it's dirty.
Trying to figure out the work around. Unfortunately, reset doesn't get the job done.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#reset OmitResetState
