### ISSUE TITLE
issue: error disappear once submit clicked

### ISSUE THREAD

**Issue by nkt** [react-hook-form/react-hook-form#12215]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/priceless-hellman-qycj6c
### Steps to reproduce

1. add effect which validates field value
2. call form.setError
3. click submit

### Expected behaviour

submit not happens

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
The validation would be measure against the rule you have set of your register input or schema.
