### ISSUE TITLE
Support `onChange` and `onBlur` mode at the same time

### ISSUE THREAD

**Issue by rmlevangelio** [react-hook-form/react-hook-form#1222]
**Is your feature request related to a problem? Please describe.**
The problem is what if I want my input to validate onBlur and onChange at the same time. 

**Describe the solution you'd like**
For instance, I want my field to validate right away after I remove focus on it (which is what `onBlur` is currently doing) plus when I input something on it, it will do also validate as well (which is what `onChange` was doing).

**Describe alternatives you've considered**
With the `mode` property, I think we can pass an array of available modes or just a string.

```js
useForm({
     mode: ['onChange', 'onBlur']
})
```

Sample:
![inputvalidation](https://user-images.githubusercontent.com/7041900/76738698-143d1180-67a6-11ea-8f99-147935df82b1.gif)

**Comment by bluebill1049** [comment]
thankrs @rmlevangelio  for the feature request. my suggestion: 

```
useForm({
     mode: 'all'
})
```

will leave this issue for awhile, before move into back log.

**Comment by rmlevangelio** [comment]
@bluebill1049 thanks !

**Comment by bluebill1049** [comment]
I will keep this issue open for another week, if the vote is under 50 then I will move to the backlog and working on it when I have time. 👍

**Comment by bluebill1049** [comment]
Going to close this issue now, but add it to my back log. This will be worked in the next couple weeks.

**Comment by bluebill1049** [comment]
will be shipped as part of V6

**Comment by rmlevangelio** [comment]
Thank you for this @bluebill1049 !
