### ISSUE TITLE
Using Controller with React-Nice-Dates datepicker

### ISSUE THREAD

**Issue by IWCollege-AaronBentley** [react-hook-form/react-hook-form#1223]
**Describe the bug**
I'm trying to use a date picker for selecting a booking date, using a yup schema for validation.

After selecting a date using [`react-nice-dates`](https://github.com/hernansartorio/react-nice-dates) date picker, the input value is not acknowledged and the field is marked as a validation error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to this [simplified CodeSandbox demo](https://codesandbox.io/s/blissful-star-ywd1v?fontsize=14&hidenavigation=1&theme=dark)
2. Click on the input to open the date picker,
3. Select a date
4. Attempt to submit the form
4. See validation error message

**Codesandbox link**
[Simplified CodeSandbox demo](https://codesandbox.io/s/blissful-star-ywd1v?fontsize=14&hidenavigation=1&theme=dark)

**Expected behavior**
The selected date value should be correctly identified as a valid input and therefore pass schema validation.

**Desktop**
 - OS: MacOS
 - Browser: I've tried in both Chrome & Safari
 - Version: Chrome (80.0.03987.132) & Safari (12.1.1)

**Additional context**
- I've included simplified versions of validation schema and date picker components I'm using
- From what I can gather, the `Controller` onChange event is never called 🤷‍♂️

**Comment by bluebill1049** [comment]
This is not a bug. can you wrap ReactNiceDatesPicker at Controller level and do a test.

**Comment by IWCollege-AaronBentley** [comment]
@bluebill1049 Thank you for the swift reply and apologies for my issue labelling error 🙏

I've forked my original demo to create an [updated CodeSandbox](https://codesandbox.io/s/react-hook-form-and-react-nice-dates-wyhhh?fontsize=14&hidenavigation=1&theme=dark) and simplified it further to wrap the date picker at controller level as instructed in your previous comment.

Unfortunately after testing this I'm experiencing the same issue, and I have that awful feeling that I've missed something trivial.

Thanks in advance,
Aaron.

**Comment by bluebill1049** [comment]
no worries :) here you go: https://codesandbox.io/s/react-hook-form-and-react-nice-dates-wrapped-at-controller-qogy4

because the external component is not following standard `onChange` and `value` props. 

have a read on the doc: https://react-hook-form.com/api#Controller where you can change the method and value name :)

**Comment by IWCollege-AaronBentley** [comment]
Thank you @bluebill1049, I really appreciate you taking the time to investigate this 😊 and can confirm everything is working as I initially intended. 🎉

I've been porting over all forms in my latest project to use `react-hook-form` and I must say the DX is sooooooo nice, I love the 'bring your own UI' approach, `yup` validation is nothing short of awesome and the render performance optimisations make me very happy 😍

Thanks again for all your work on this fantastic library 🤩

**Comment by bluebill1049** [comment]
Oh man you are too kind! Thank you very much for your feedback. To be honest i am so glad this lib is working for you, you are definitely my target audience who is nice, kind and appreciative!
