### ISSUE TITLE
issue: stale closure of register option onChange.

### ISSUE THREAD

**Issue by hailey-poppin** [react-hook-form/react-hook-form#12235]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/condescending-mopsa-66dxll?file=%2Fsrc%2FApp.tsx%3A31%2C22

### Steps to reproduce

1. Go to [code sandbox](https://codesandbox.io/p/sandbox/condescending-mopsa-66dxll?file=%2Fsrc%2FApp.tsx%3A31%2C22)
2. Click on radio A, B, C, D
3. Regardless of what you clicked, D was printed on the console.

https://github.com/user-attachments/assets/5a7f754a-9b57-4173-9008-1d903d93c672

### Expected behaviour

If you click A, A is displayed on the console.
If you click B, B is displayed on the console.
...

It looks like there is a stale closure. I wonder if it is the intended action. 
I know that you can approach and solve it with an `event`.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
if you could use e.target.value instead.
