### ISSUE TITLE
issue: setting `disabled` in `useForm` with `useFieldArray` immediately marks the field array as dirty

### ISSUE THREAD

**Issue by eugene-mohc** [react-hook-form/react-hook-form#12237]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-usefieldarray-forked-qdy98m

### Steps to reproduce

1. Go to sandbox
2. Open console
4. Notice that `isDirty` is `false` on first render and then immediately `true` on second render, even though nothing has been touched or changed in the form
5. Remove `disabled: true` from `useForm`
6. Notice that `isDirty` stays `false` and doesn't trigger a second render

### Expected behaviour

`isDirty` should stay `false` when using `disabled` in `useForm`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by desjoerd** [comment]
I think the same issue is also present when not using `useFieldArray`. I downgraded to `7.52.2` and my forms are not marked as dirty anymore.

We set the form to disabled while submitting the form. I don't know whether that's a good pattern?

**Comment by imarkc** [comment]
This happens also using Controller. Then emits an error
`Cannot update a component (`Form`) while rendering a different component (`Controller`). To locate the bad setState() call inside `Controller``

**Comment by lauri865** [comment]
Same issue - all custom components with useController marked as dirty post 7.53.0
