### ISSUE TITLE
prepend from useFieldArray loose values

### ISSUE THREAD

**Issue by vensauro** [react-hook-form/react-hook-form#1224]
**Describe the bug**
When i use the prepend function with the `Controller`, he looses the value in the second call to prepend.

**To Reproduce**
1. Go to [codesanbox example](https://codesandbox.io/s/react-hook-form-usefieldarray-u7rxf).
2. Set values to the form.
3. Click on prepend button.
4. Set values for the new inputs
5. Click again in prepend
6. See that the second row of inputs looses the value, and the fields logged in the console also don't have the values set

**Codesandbox link (Required)**
[codesanbox example](https://codesandbox.io/s/react-hook-form-usefieldarray-u7rxf)

**Expected behavior**
That the values continues, like the append function

**Desktop (please complete the following information):**
 - OS: [Os High sierra]
 - Browser: [chrome, firefox]
 - Version: latest for both

**Comment by mxcl** [comment]
I have a similar issue with `append` but it only happens for the values inserted into the form via `useForm({ defaultValues })`. Possibly the same issue since your Codesandbox does the same.

I‘m up to date.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-usefieldarray-u7rxf

**Comment by mxcl** [comment]
For others that might read this: My issue was I was setting the key in the wrong place.

Also I had `id` on my data already which possibly was the problem, you can get `useFieldArray` to use a different id for itself internally thus: `useFieldArray<Type>, 'idKeyName'>()`

**Comment by bluebill1049** [comment]
thanks for sharing this @mxcl
