### ISSUE TITLE
issue: useFieldArray does not work correctly when setting disabled in useForm

### ISSUE THREAD

**Issue by 052hide** [react-hook-form/react-hook-form#12249]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/cocky-elion-jhvh8f

### Steps to reproduce

1. Go to sandbox
2. Click on "Append Item" button several times
3. Not added to items

### Expected behaviour

addition of items correctly

---

- v7.52.2 does not have this problem
- It probably does not occur if disabled is not set

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by x539** [comment]
`disabled` for useForm is undocumented btw.

Not sure if this is related, but I had trubble with any registered-input field in combination with prefilled forms when using the `useForm({ disabled: TOGGLE_HERE })`.
I had to use the `register(.., {disabled: TOGGLE_HERE})` to make the form submit any values.

**Comment by bluebill1049** [comment]
already fixed at https://github.com/react-hook-form/react-hook-form/pull/12239

**Comment by 052hide** [comment]
The same problem occurs in v7.53.1.
