### ISSUE TITLE
issue: watch does not update when using isSubmitted of useController

### ISSUE THREAD

**Issue by sedenko93** [react-hook-form/react-hook-form#12247]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/9x6mwp

### Steps to reproduce

1. Go to https://codesandbox.io/p/sandbox/9x6mwp
2. Change the input value
3. Press the reset button
4. Change the input value
5. watch() is not updating the value anymore

https://github.com/user-attachments/assets/a75a25cb-5e99-4c54-867a-b657225cec95

To fix this issue a work around is using, useWatch instead of watch directly.

### Expected behaviour

After reset the result of watch is showing the correct value.

### What browsers are you seeing the problem on?

Haven't tested other browsers, but experiencing this in 
chrome Version 128.0.6613.120 (Official Build) (arm64)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/user-attachments/assets/d37f72ec-0b87-4365-a9dd-eda10e54ea0c

both working correctly.
