### ISSUE TITLE
issue: spyOn useForm not called from version 7.52.2 onwards

### ISSUE THREAD

**Issue by oyrad** [react-hook-form/react-hook-form#12248]
### Version Number

7.52.2

### Codesandbox/Expo snack

https://codesandbox.io/p/devbox/d8kpwr

### Steps to reproduce

Fork the sandbox to enter dev mode and gain access to the terminal.

1. Run `pnpm test`
2. Test fails with: 
  `Expected number of calls: >= 1
    Received number of calls:    0`
3. Change version to `7.52.1`
4. Run `pnpm test`
5. Test passes

### Expected behaviour

Test should pass on newer versions.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Please write a test and send a PR to our repo.
