### ISSUE TITLE
How can I trigger validation with a ref?

### ISSUE THREAD

**Issue by chris-fran** [react-hook-form/react-hook-form#1225]
### Description

I have a Material UI dialog with a Wizard/Funnel with multiple forms inside. Since Material Design demands the button to be on the bottom part of the dialog, there is no submit button inside any form.

```tsx
const Page() {
  const formRef = useRef<HTMLFormElement>();

  const onSubmit = (payload: FirstFormValues | SecondFormValues | ThirdFormValues) => {
    // code to save each form state
  }

  const onNextStep = () => {
    formRef.current!.submit();  // <-- this submit does not trigger validation, but a redirect

    setCurrentStep(currentStep => currentStep + 1);
  }

  return (
    <Dialog>
      <DialogContent>
        <Funnel ref={formRef} currentStep={currentStep} />
      </DialogContent>  
      <DialogActions>
        <Button onClick={handleNextStep}>Next</Button>
      </DialogActions>
    </Dialog>
  );
}


const Funnel = forwardRef<HTMLFormElement, Props>(({ onSubmit }, formRef) => {
  return (
    <> 
      {step === 0 && <FirstForm ref={formRef} onSubmit={onSubmit} />}
      {step === 1 && <SecondForm ref={formRef} onSubmit={onSubmit} />}
      {step === 2 && <ThirdForm ref={formRef} onSubmit={onSubmit} />}
    </>
  );
})

const FirstForm = forwardRef<HTMLFormElement, Props>(({ onSubmit }, formRef) => {
  const { handleSubmit, register } = useForm()

  return (
    <form ref={formRef} onSubmit={handleSubmit(onSubmit)}>
      <input type="submit" value="Just to test" />
    </form>
  );
})
```

Clicking on the "Just to test" button correctly triggers the validation on the form. However, the call `formRef.current!.submit()` causes a page refresh.

What's the right way of doing this?

**Comment by bluebill1049** [comment]
can we please try to post question at spectrum and supply with a CSB?

**Comment by chris-fran** [comment]
@bluebill1049 Sure thing. what does CSB stand for?

**Comment by bluebill1049** [comment]
codesandbox :) thans @chris-fran for understanding, i normally keep track for issues/bugs here and follow up questions at spectrum.

**Comment by chris-fran** [comment]
@bluebill1049 no problem, you always help me so the least I can do is make it easier for you. I'm REALLY grateful man :)  love this library

**Comment by chris-fran** [comment]
Posted it in here: https://spectrum.chat/react-hook-form/help/how-can-i-trigger-validation-with-a-ref~19f79408-773c-4d3e-a447-5c4a401349d7

**Comment by bluebill1049** [comment]
awesome thanks, i will take a look there.
