### ISSUE TITLE
Document validationResolver result

### ISSUE THREAD

**Issue by kyeotic** [react-hook-form/react-hook-form#1226]
The current documentation for `validationResolver` gives very little information on what the return/result value should look like. A complete example that does not rely on knowledge of external libraries like **joi** or **yup** would be very helpful.

Specifically

* What shape is `return.values`?
* What shape is `return.errors`?

**Comment by bluebill1049** [comment]
@kotarella1110 maybe you can help on improve the return type as well (if you got time) :)

**Comment by kotarella1110** [comment]
@bluebill1049 I will look into it after!

**Comment by bluebill1049** [comment]
thank you @kotarella1110 i can take care the doc afterwards 👍

**Comment by kyeotic** [comment]
@bluebill1049 I think [there might be an issue with this](https://github.com/react-hook-form/react-hook-form/pull/1239#discussion_r395101911)

**Comment by kotarella1110** [comment]
@kabriel What are the issue?

**Comment by kyeotic** [comment]
A validation function will need to return an object when there is a validation problem; a type error will stop typescript from compiling. How is a validation function supposed to return an error object if its a type error?
