### ISSUE TITLE
issue: setValue with undefined resets the inputfields text to defaultValue

### ISSUE THREAD

**Issue by oezbeyyf** [react-hook-form/react-hook-form#12264]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/qrcfrw

### Steps to reproduce

1. Go to https://codesandbox.io/p/sandbox/qrcfrw
2. Open the console
3. Change the value of the number-textfield
4. Press reset
5. See that the value in getValue is now "undefined" (console-log), but the input field shows the defaultValue (5)

### Expected behaviour

I expected the input to also be undefined (empty) after pressing "Reset" just as the apparent value of the form field seen in getValues.
If you change the reset button to set the value to anything else it works as expected. Only undefined seems to cause an issue.

### What browsers are you seeing the problem on?

Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oezbeyyf** [comment]
To give some additional information: I have seen the previous issue from 2021 #3922 which seems to have had the exact same problem as I do now. Though it has been marked as fixed for version 7. 

The codesandbox there uses register and useEffect. Though, because I use MUI components, I didn't go with register, as from my understanding that's primarily used for uncontrolled components (correct me if I am wrong). So maybe my approach is faulty? But I can't figure out where the issue lies.

**Comment by bluebill1049** [comment]
Doesn't support `undefined` refer to the doc: https://react-hook-form.com/docs/useform/setvalue
