### ISSUE TITLE
issue: setValue('XX', undefined) brings back some old value

### ISSUE THREAD

**Issue by terragady** [react-hook-form/react-hook-form#12277]
### Version Number

7.53.0

### Codesandbox/Expo snack

0

### Steps to reproduce

It is a pretty complex behaviour, I am using useQuery and passing data from useQuery to "values" as a reactive values. 
Then one of the field has to reset some others so in onChange I am doing setValue('otherfield', undefined) and also I am submitting some other query and modifying cache of the query which is used for reactive values.

Cache is correct, a watch for this field is correct at the beginning but when something rerenders on the page the value for "undefined" field is brought back somehow. Cache is still undefined and watch is changed to value showed in UI.

The problem is fixed when I use null or empty string, but some general rules and openAPi generator prevents me from using nulls in the projects and empty string is not an option because it is enum | undefined type. Definiately there is something wrong with that undefined value passed to setValue function. 

It is hard to reproduce it without sharing half of my project but maybe it is worth a try writing it here and maybe someone had similar problem already? :) 

### Expected behaviour

Keep undefined value in the form state

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://react-hook-form.com/docs/useform/setvalue 

> The value for the field. This argument is required and can not be undefined.

**Comment by Zzzdy-code** [comment]
I think setting the value to undefined is a very common requirement, (For example, a form item with a numeric field cannot be an empty string or null.)is there any other way to support setting the value to empty, or will setValue consider supporting undefined in the future? @bluebill1049

**Comment by terragady** [comment]
you need to do workarounds, i dont think it will ever support undefined but not sure why exactly :P

**Comment by Steveb599** [comment]
Have you found a workaround? I got the same issue, tried with reset & setValue and both don't work properly. bring back the defaultValue. I just want to reset a select and calendar lol

**Comment by terragady** [comment]
usign `null` works

**Comment by Steveb599** [comment]
> usign `null` works

but zod doesnt let me null values

**Comment by thanhnguyen0904** [comment]
> > usign `null` works
> 
> but zod doesnt let me null values

i had the same issue & found the temporary solustion: 
- declare string instead of number then parseInt later
- using controller to wrap the element

it works as expected, can't explain why though, maybe @bluebill1049 can help. I attacted 2 files with one working and the other not

<img width="480" alt="Screenshot 2024-11-29 at 19 20 48" src="https://github.com/user-attachments/assets/f0fec15a-2752-41d6-b1e1-27329a4603bc">
<img width="390" alt="Screenshot 2024-11-29 at 19 21 13" src="https://github.com/user-attachments/assets/b5054412-445f-4099-bb9c-97609fb9fbf2">

**Comment by terragady** [comment]
but you are not setting undefined or null but empty string, that always worked :)
