### ISSUE TITLE
issue: Input number field is passed as empty when a character is entered

### ISSUE THREAD

**Issue by stefanoinf** [react-hook-form/react-hook-form#12274]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/spring-fog-m9xf6r

### Steps to reproduce

1. Enter a letter in the input (e.g., insert "d").
2. Click the submit button.
3. You will receive the message "Year is required" instead of "Year is wrong."
4. Open the console and check the console.log of the "transform" function. The reason you're seeing "Year is required" instead of "Year is wrong" is because the "year" field is empty.

### Expected behaviour

I expected to see the message "Year is wrong." However, for some reason, the "year" field is being passed as empty so I get the "required" validation.

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
native input behaviour

**Comment by RaviTeja884781** [comment]
fdskhjhjsdafhgasdkhjfghjdas
