### ISSUE TITLE
issue: Fields state not updated when use FormProvider and useFormContext

### ISSUE THREAD

**Issue by n-filatov** [react-hook-form/react-hook-form#12273]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/939sgx

### Steps to reproduce

1. Click on "Change data"
2. Click on "Open new form"

### Expected behaviour

When i click "Change data" i will see update FormFoo data and Parent data

When i click on "Open new form" i will see FormBar instead of FormFoo and will see data that was updated by clicking on "Change data" in FormFoo

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oxwazz** [comment]
if i try your codesandbox only modify package.json, and then its work. i think you must update to the latest version of react-hook-form

![image](https://github.com/user-attachments/assets/2d7d9357-1ab6-409e-9ecf-bd97ba973e0f)
