### ISSUE TITLE
issue: Nested useFieldArrayControls duplicate

### ISSUE THREAD

**Issue by Avilaaiops** [react-hook-form/react-hook-form#12276]
### Version Number

7.51.4

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/3pghyr

### Steps to reproduce

1. Click on the `(+ Condition Group)` button to create a condition group
2. Inside the new condition group, create two or more nested condition groups by clicking the `(+ Condition Group (Nested))` button that appears inside the Condition Group created during step one.
3. Add Conditions inside of the Nested Condition Groups (Not the top level Condition Group created in step 1) by pressing the `(+ Condition)` button. Be sure to create Conditions in multiple Nested Condition Groups alternating between different Nested Condition Groups.
4. Each Condition created adds to a tally that increases the number of conditions in ALL Nested Condition Groups. These extra Conditions do not show up until you have pressed the (+Condition) button after subsequently having pressed that same button in another Nested Condition Group

### Expected behaviour

Conditions added to one Nested Condition group should not affect sibling Nested Condition Groups. Likewise, creating a second Condition Group after filling out the first creates the second with the same number of blank fields generated in the first.

It should be noted that the JSON created onSubmit does map the right fields to the JSON output.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Relevant log output

```shell
Nothing exciting, though I did log the indexes being passed to each condition to ensure that `conditionGroups.[${groupIndex}].conditionGroupsNested.[${nestedGroupIndex}].conditions.[${index}].key` is being accurately passed to each created condition.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JardelCheung** [comment]
Change it will be fine.
<img width="624" alt="image" src="https://github.com/user-attachments/assets/1a5c2e05-72a3-4667-9f16-807f13e864da">

**Comment by bluebill1049** [comment]
thank you @JardelCheung that's correct.
![Screenshot 2024-09-28 at 12 16 49 PM](https://github.com/user-attachments/assets/aabe58e9-1f3b-4890-97e4-da99012b228a)

https://react-hook-form.com/docs/usefieldarray
