### ISSUE TITLE
issue: FormData returned by Form component lists fields that have been deleted

### ISSUE THREAD

**Issue by marcohamersma** [react-hook-form/react-hook-form#12291]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/damp-snow-td7pff

### Steps to reproduce

1. Create a form that uses `useFieldArray`, add some mockup fields as default values
2. Call remove on one of the fields
3. Submit the form using the new `Form` component
4. The FormData still contains entries for the deleted form, just with its contents set to "undefined"

This might be related to some of the options I'm using in my code (e.g. `keyName`), so check out the codesandbox for that.

### Expected behaviour

After removing a field, the previous field should no longer be present in the `FormData`

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChrisKulesza** [comment]
This is not a bug. In the example, another state was introduced in the form of a useState. This runs parallel to the RHF state and does not necessarily have the content of the RHF state.

Remove the useState and access the form state directly via the useForm hook. See Sandbox

[Sandbox](https://codesandbox.io/p/sandbox/wonderful-booth-tzf5xh)

**Comment by marcohamersma** [comment]
The `formState` object you're referring to in your sandbox is behaving correctly and wasn't the problem in the first place. I am trying to use the `formData` generated by the Form component, that one has the buggy behaviour. I only added the `useState` hook to print out the results of the `formData` so you wouldn't have to open the browser console to see what I mean. I realise now that was a distraction. 

I've forked the sandbox so you can [see the issue in the console](https://codesandbox.io/p/sandbox/form-component-bug-forked-5hfkrc). 

<img width="443" alt="image" src="https://github.com/user-attachments/assets/146c3d07-55bc-4a38-9ae6-aa463a9ea3a7">

**Comment by NedelinaN** [comment]
I have the same problem

@bluebill1049 have you solved the issue?
I have updated the package to the latest version, but I still get deleted fields from `formData`
