### ISSUE TITLE
issue: when using zod for date validation, an error object is not created on change, even though the mode is set to "onChange”

### ISSUE THREAD

**Issue by crypt0box** [react-hook-form/react-hook-form#12294]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/hrl8xk?file=%2Fsrc%2FApp.tsx%3A62%2C1

### Steps to reproduce

1. Go to https://codesandbox.io/p/sandbox/hrl8xk?file=%2Fsrc%2FApp.tsx%3A62%2C1
2. Enter "aaa" in the text field.
3. Confirm that the validation message does not appear, even though the `mode` is set to `onChange`.

### Expected behaviour

Ensure that a validation error message is immediately displayed when a string that cannot be converted to a date is entered in the text field.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crypt0box** [comment]
The cause of the bug is due to the changes in https://github.com/react-hook-form/react-hook-form/pull/12185. When the value of `fieldValue` and `get(_formValues, name, fieldValue)` is `Invalid Date`, `===` evaluates to true, but `deepEqual(fieldValue, get(_formValues, name, fieldValue))` evaluates to false, preventing the errors object from being created in the subsequent process.

**Comment by bluebill1049** [comment]
can you update your CSB?

**Comment by crypt0box** [comment]
@bluebill1049 
sorry, I have just updated CSB.

**Comment by bluebill1049** [comment]
Just double check, how come there is no defaultValues in your CSB?
