### ISSUE TITLE
issue: The value of a disabled field is reset to undefined

### ISSUE THREAD

**Issue by kuznetsovgm** [react-hook-form/react-hook-form#12303]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/t8kd8g

### Steps to reproduce

1. set a default value for the disabled field
2. submit a form or change the value of any field

### Expected behaviour

the value of the disabled field will be equal to the default value

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
disabled field value is undefined
```

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
disabled field will return `undefined`.
