### ISSUE TITLE
issue: Control is dirty on mount if disabled prop is specified

### ISSUE THREAD

**Issue by AlexKrupko** [react-hook-form/react-hook-form#12302]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/reset-field-forked-xkwvmr?workspaceId=8ab69168-c1a1-4152-8dd9-c96a62056f3b

### Steps to reproduce

Control has dirty state on mount if `disable` prop is specified for `useController` hook (or `useForm`).

```ts
const { field, fieldState } = useController({
    name: "test",
    defaultValue: "",
    disabled: false,
});

console.log(fieldState.isDirty); // true
```

### Expected behaviour

`isDirty` flag should be false until the value actually changes 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Form value will be set to `undefined` when set to disabled, which lead to formValues not match defaultValues. Current limitation,
