### ISSUE TITLE
Value returned by watch doesn't change when typing for array fields

### ISSUE THREAD

**Issue by pvdlg** [react-hook-form/react-hook-form#1231]
**Describe the bug**

When generating fields from an array(similar to https://react-hook-form.com/advanced-usage#FieldArrays) and using `watch` to detect a change the value retuned by watch doesn't change as the user type in the field.

The name of the field is generated as `field.${item.id}` and watch is called with `watch('field')`.

This used to work in version 4.9.8 and stopped working in 4.9.9-beta.1.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-field-bug-watch-array-fields-bkdj5
2. Type some text in the input field
3. Message "new field value" appears in the console
4. Change the react-hook-form dependency to 4.9.9-beta.1 or above
5. Type some text in the field
6. Nothing is logged in the console

**Codesandbox link (Required)**
Working version (4.9.8): Go to https://codesandbox.io/s/react-hook-form-field-bug-watch-array-fields-bkdj5
Version with issue (4.9.9-beta.1): http://codesandbox.io/s/react-hook-form-field-bug-watch-array-fields-s2qyo 

**Expected behavior**
The watched value should be updated as it used to be in 4.9.8

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#useFieldArray

<img width="937" alt="Screen Shot 2020-03-17 at 5 26 08 pm" src="https://user-images.githubusercontent.com/10513364/76828164-6e0c0d00-6874-11ea-80e8-64efe8c29748.png">

I think this is in the docs.

**Comment by bluebill1049** [comment]
I will take a look your example later as well.
