### ISSUE TITLE
issue: reset() not setting form values after version release

### ISSUE THREAD

**Issue by adriano-tirloni** [react-hook-form/react-hook-form#12315]
### Version Number

7.51.4

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/f7w5hn

### Steps to reproduce

1. Go to 'https://codesandbox.io/p/sandbox/f7w5hn'
2. Open Preview tab with console, reload the preview tab. Check console logs.
3. Open package.json, change version from 7.51.3 to 7.51.4, save, repeat step 2.
4. Check console log

### Expected behaviour

This change https://github.com/react-hook-form/react-hook-form/pull/11779/files, altered the behaviour of useForm().reset() function.

We use the reset function in order to update the form values with async fetched data, I created a small sandbox to test it and as you can see on the screenshots below instead of setting the forms value it is now creating a new empty object on which many controlled computed fields start failing because the form value do not have the expected structure anymore.

(In the sandbox I'm using effects to mimic this async behaviour.)

**On 7.51.3**
![image](https://github.com/user-attachments/assets/60df55a7-c2ca-4825-8f9b-70e367833f8a)

**On 7.51.4**
![image](https://github.com/user-attachments/assets/e92576e0-eaf8-43e5-a4df-6b09ec143750)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MalabarFront** [comment]
I'm also facing this issue, after updating to 7.53.0 from 7.51.2.

**Comment by bluebill1049** [comment]
related issue: https://github.com/react-hook-form/react-hook-form/issues/11778 for the original fix. after resetting the form will need the next useEffect to get the updated form values. workaround `reset(.., {keepDirtyValues: true})`
