### ISSUE TITLE
issue: watch breaks rules of react (compiler) – "hook names must start with use"

### ISSUE THREAD

**Issue by lauri865** [react-hook-form/react-hook-form#12310]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://stackblitz.com/edit/vitejs-vite-gy3dhb?file=src%2FFix.tsx

### Steps to reproduce

1. Go to the [Stackblitz repro](https://stackblitz.com/edit/vitejs-vite-gy3dhb?file=src%2FFix.tsx)
2. Type in the above field - watch is not reactive
3. Type in the below field - watch is reactive (the function is the same, just aliased as useWatch)

### Expected behaviour

`watch` returned by useForm and useFormContext is by all intents and purposes a hook. By not following the naming rules, the reactivity is lost after React Compiler works its magic. The rules of hooks state:
> Hook names must start with use followed by a capital letter

As you notice in the repro, I'm calling the very same function – one with `watch`, the other one aliased as `useWatch`, so it's not about functionality.

This repro only seems to only work with `useController` though.

---

I would suggest returning both `useWatch` and `watch` from the hooks, and adding a future deprecation notice for `watch`, and warning that it's not compatible with react-compiler.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
track here: https://github.com/react-hook-form/react-hook-form/issues/12298
