### ISSUE TITLE
issue: Fields become read-only when using combination of features

### ISSUE THREAD

**Issue by user72356** [react-hook-form/react-hook-form#12325]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/summer-bush-8chj6s

### Steps to reproduce

1. Go to the linked CodeSandbox.
2. Try to modify the text in the field.
3. You can't.

### Expected behaviour

I should be able to modify the text in the field, such as adding or deleting characters. 

Instead, the specific combination of using defaultValues, reset, FormProvider, Controller and having the form element under a sub-component appears to trigger a bug of making the fields read-only.

This happens only when the reset supplies the same values as were provided in defaultValues. If I reset to a different value there is no problem.

Obviously this is a minimal example where the above combination makes no sense. The real project is a complex form where this configuration is necessary/desirable.

### What browsers are you seeing the problem on?

Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Please refer to the following example, you should send the input value instead of the event.

```
<input
  value={value}
  onChange={(e) => onChange(e.target.value)}
  onBlur={onBlur}
/>
```

**Comment by user72356** [comment]
Did you try you fix before closing this issue? It doesn't work at all. Furthermore, the documentation shows the same usage as me and the onChange function signature indicates it takes the event, not the value.
