### ISSUE TITLE
issue: exported type FormStateProxy - errors is boolean

### ISSUE THREAD

**Issue by eardenercruk** [react-hook-form/react-hook-form#12320]
### Version Number

7.53.0

### Codesandbox/Expo snack

n/a

### Steps to reproduce

`react-hook-form/dist/types/form.d.ts` exports

```ts
export type FormStateProxy<TFieldValues extends FieldValues = FieldValues> = {
    isDirty: boolean;
    isValidating: boolean;
    dirtyFields: FieldNamesMarkedBoolean<TFieldValues>;
    touchedFields: FieldNamesMarkedBoolean<TFieldValues>;
    validatingFields: FieldNamesMarkedBoolean<TFieldValues>;
    errors: boolean;
    isValid: boolean;
};
```

### Expected behaviour

Should be `FieldErrors<TFieldValues>` according to [documentation](https://react-hook-form.com/ts)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
it's different, you shouldn't have to use this type.
