### ISSUE TITLE
issue: setting a value as an object changes its reference

### ISSUE THREAD

**Issue by PiotrSkrzynski88** [react-hook-form/react-hook-form#12321]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/y895dp

### Steps to reproduce

1. Navigate to this [CodeSandbox](https://codesandbox.io/p/sandbox/y895dp).
2. Click on the toggle buttons.
3. Observe that the version integrated with **react-hook-form** does not function as expected because **ToggleButtonGroup** relies on reference comparison when handling values. However, it works correctly with regular React state.

### Expected behaviour

I wonder if **react-hook-form** could be more transparent when handling object values. When I set an object, I would hope to receive the same reference back. It seems that the issue may arise from react-hook-form treating the object as shorthand for setting multiple values. In this specific case, my goal is to set an object as a single value, rather than multiple form values.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShyneADL** [comment]
Please assign this task to me.

**Comment by andreev-artem** [comment]
Same issue for a Select implementation using Controller. Some debug:
1. [onChange calls _subjects.values.next](https://github.com/react-hook-form/react-hook-form/blob/09a9a495ec8374cbce00e6006026069150a2e3e7/src/logic/createFormControl.ts#L754) with original value
2. [useWatch calls updateValue using cloneObject](https://github.com/react-hook-form/react-hook-form/blob/09a9a495ec8374cbce00e6006026069150a2e3e7/src/useWatch.ts#L171)
3. [cloneObject makes shallow copy of plain object](https://github.com/react-hook-form/react-hook-form/blob/09a9a495ec8374cbce00e6006026069150a2e3e7/src/utils/cloneObject.ts#L24)

**Comment by bluebill1049** [comment]
It would be rather difficult at this stage, eg `set('whatever.deep.deep.deep.deep', 'value')`
