### ISSUE TITLE
Util func to get nested error state or flatten the errors

### ISSUE THREAD

**Issue by sourabhv** [react-hook-form/react-hook-form#12336]
**Is your feature request related to a problem? Please describe.**

I had nested state in my joi schema and realized the `errors` dict does not match the `name` passed to the controller, which is confusing and unexpected.

**Describe the solution you'd like**
Either 

- Add a new field called `refErrors` or something which is a map of refName to error
- Or add a util function to flatten the errors by ref name
- or a util function to get nested error in `errors` dict

**Additional context**

Right now I am using this the third option

```ts
import { FieldError, FieldErrors } from 'react-hook-form';

export function getError<T>(errors: FieldErrors<T>, refName: string) {
  const keys = refName.split('.');
  let error = errors;

  for (let i = 0; i < keys.length; i++) {
    if (error[keys[i] as keyof T]) {
      error = error[keys[i] as keyof T] as FieldErrors<T>;
    } else {
      return null;
    }
  }

  const err = error as unknown as FieldError;

  if (!err || err.ref.name !== refName) {
    return null;
  }

  return err;
}
```

**Comment by hossein25** [comment]
You can use this approach
`
import { get, DeepMap, FieldError, FieldValues } from "react-hook-form";

function getFieldErrors(path: string, errors: DeepMap<FieldValues, FieldError>) {
  if (!path) return null;
  if (!errors) return null;
  const fieldErrors = get(errors, path);
  if (!fieldErrors) return null;
  return fieldErrors;
}
`
