### ISSUE TITLE
Using ternary operator causes the fields to get incorrect defaultValue

### ISSUE THREAD

**Issue by wenchonglee** [react-hook-form/react-hook-form#1234]
Hey,
First off, thanks for open sourcing this library, I really appreciate it.

I encountered this issue that I'm not sure if it should be solved by the library, or if it can just be documented.

**Codesandbox link (Required)**
https://codesandbox.io/s/loving-dew-7i24k

**To Reproduce**
1. Toggle the switch
2. Get an error

In the sandbox, you will see that I have a ternary operator that switches between 2 input fields (using controllers).
The first input field expects an array, while the other expects an object. An error is thrown when you toggle between the 2 fields because React doesn't seem to rerender with the correct `defaultValue`.

I managed to solve it by either:

1. Giving each of the controllers a key prop (Uncomment them and refresh the sandbox to fix it)
2. Using the `&&` operator instead of ternary. This causes the controllers to unmount completely instead of rerendering.

I think you can solve #1135 the same way.

Again, I'm not sure if you think the responsibility is on react-hook-form.
If not, thanks again for writing this library :)

**Comment by bluebill1049** [comment]
I will update doc on this one in a FAQ.

**Comment by bluebill1049** [comment]
Thanks for the kind words. ❤️ I find it hard to documented this down, do you have any suggestion? the two components that you are toggling with having different data shape and probably internal structure as well, which is lead to the confusing with defaultValues been mismatch. It's specific to a particular component as well. The error is fired on that external component as well, if you change to native input and the error goes aways. Let me know if you have good suggestion to write them down, more than happy to introduce them into the doc.

**Comment by wenchonglee** [comment]
I would help you document this but I'm not sure I understand well enough yet.

Can you explain what do you mean by changing to native input? 
I updated the codesandbox to use what I think you meant by native input, but the problem is still there. https://codesandbox.io/s/loving-dew-7i24k

When you toggle the switch, you can see that `input1` always retain the defaultValue of `input2`.
In the ternary between `input3` and `input4` below, it works as intended because keys were given to them.

I know this has to do with React's reconciliation algorithm, but I think my understanding is not good enough to explain it properly yet. I think [Kent explains this well](https://kentcdodds.com/blog/understanding-reacts-key-prop)

Personally, I wasn't sure if this problem should be solved by react-hook-form, but if you think it shouldn't, then maybe we could add to the FAQ page. Perhaps something like "Why is my default value not changing correctly?" and having the content about reconciliation like Kent did in his blog.

**Comment by bluebill1049** [comment]
> I updated the codesandbox to use what I think you meant by native input, but the problem is still there. https://codesandbox.io/s/loving-dew-7i24k

I meant toggle your example with native input.

> When you toggle the switch, you can see that input1 always retain the defaultValue of input2.
> In the ternary between input3 and input4 below, it works as intended because keys were given to them.

You are right :)

> Personally, I wasn't sure if this problem should be solved by react-hook-form, but if you think it shouldn't, then maybe we could add to the FAQ page. Perhaps something like "Why is my default value not changing correctly?" and having the content about reconciliation like Kent did in his blog.

Sounds good, i will use that as title and extend with description and context.

**Comment by wenchonglee** [comment]
> Sounds good, i will use that as title and extend with description and context.

Great, thanks for the clarifications :)

**Comment by bluebill1049** [comment]
> React Hook Form doesn't control your entire form and inputs, which is the reason why React wouldn't recognise the actual input that has been exchanged or swopped. As a solution, you can resolve this problem by giving a unique `key` prop to your input. You can also read more about the key props from this article written by Kent C. Dodds.

let me know if you think it make sense and feel free to adjust and add your words too. thanks

**Comment by wenchonglee** [comment]
I think it's fine, but maybe adding an example would help?

> React Hook Form doesn't control your entire form and inputs, which is the reason why React wouldn't recognise the actual input that has been exchanged or swopped. **An example of this happening is when you use a ternary operator to conditionally switch between input fields.** As a solution, you can resolve this problem by giving a unique key prop to your input. You can also read more about the key props from this article written by Kent C. Dodds.

Here's a trimmed down example of my codesandbox, you could edit it to your liking and add it if you want.

```
import React from "react";
import { useForm } from "react-hook-form";

export default function App() {
  const defaultValues = {
    checked: false,
    input1: "input1",
    input2: "input2",
    input3: "input3",
    input4: "input4"
  };

  const { watch, register } = useForm({ defaultValues });
  const watchChecked = watch("checked");

  return (
    <div className="App">
      <input ref={register} name="checked" type="checkbox" />

      Without Keys, the default value will not change:
      {watchChecked ? (
        <input ref={register} name="input1" type="text" />
      ) : (
        <input ref={register} name="input2" type="text" />
      )}
  
      With Keys, the default value changes correctly:
      {watchChecked ? (
        <input ref={register} name="input3" type="text" key="key1" />
      ) : (
        <input ref={register} name="input4" type="text" key="key2" />
      )}
    </div>
  );
}
```

Cheers!

**Comment by bluebill1049** [comment]
> I think it's fine, but maybe adding an example would help?
> 
> > React Hook Form doesn't control your entire form and inputs, which is the reason why React wouldn't recognise the actual input that has been exchanged or swopped. **An example of this happening is when you use a ternary operator to conditionally switch between input fields.** As a solution, you can resolve this problem by giving a unique key prop to your input. You can also read more about the key props from this article written by Kent C. Dodds.
> 
> Here's a trimmed down example of my codesandbox, you could edit it to your liking and add it if you want.
> 
> ```
> import React from "react";
> import { useForm } from "react-hook-form";
> 
> export default function App() {
>   const defaultValues = {
>     checked: false,
>     input1: "input1",
>     input2: "input2",
>     input3: "input3",
>     input4: "input4"
>   };
> 
>   const { watch, register } = useForm({ defaultValues });
>   const watchChecked = watch("checked");
> 
>   return (
>     <div className="App">
>       <input ref={register} name="checked" type="checkbox" />
> 
>       Without Keys, the default value will not change:
>       {watchChecked ? (
>         <input ref={register} name="input1" type="text" />
>       ) : (
>         <input ref={register} name="input2" type="text" />
>       )}
>   
>       With Keys, the default value changes correctly:
>       {watchChecked ? (
>         <input ref={register} name="input3" type="text" key="key1" />
>       ) : (
>         <input ref={register} name="input4" type="text" key="key2" />
>       )}
>     </div>
>   );
> }
> ```
> 
> Cheers!

awesome thanks will add your example as well :)

**Comment by bluebill1049** [comment]
thank you for your contribution, website is updated. :)
