### ISSUE TITLE
issue: Controller render `field.value` becomes unsynchronized after remounting

### ISSUE THREAD

**Issue by lutzseverino** [react-hook-form/react-hook-form#12341]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/nqxrwd

### Steps to reproduce

1. Open dialog, input new value, test "Reset" and "Set to Hello World". All works as intended.
2. Close dialog, open back up again. Test "Reset", only `control._formValues.dialogField` resets, `control._fields.dialogField?._f.value` does NOT reset and shows old value and `field.value` provided by the `render` prop also displays an old value.
3. Click "Set to Hello World", see both `_formValues` and `_fields` update accordingly.
4. Click "Reset" once again and see how `_fields` somehow remembers the value set on the previous dialog close and `_formValues` update correctly.

Video showcase:
https://github.com/user-attachments/assets/9a5de662-a328-41c2-8b79-6d72486336d3

### Expected behaviour

The value from the last dialog closure should not be remembered, `resetValue` should... reset the value regardless the situation.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lutzseverino** [comment]
Found this [related discussion](https://github.com/orgs/react-hook-form/discussions/10663#discussion-5393053) from July of 2023.

**Comment by bluebill1049** [comment]
> The value from the last dialog closure should not be remembered, resetValue should... reset the value regardless the situation.

Nah hook form by default doesn't remove value after unmount unless use `shouldUnregister`, with react 19 maybe we can introduce more state unmount remove value as now ref has callback support.

**Comment by 1cedsoda** [comment]
> Nah hook form by default doesn't remove value after unmount unless use `shouldUnregister`, with react 19 maybe we can introduce more state unmount remove value as now ref will have callback support for unmont.

Using `shouldUnregister` fixed my synchronization issues after using `form.reset()`.
