### ISSUE TITLE
issue: fieldArray fields are restored after being removed

### ISSUE THREAD

**Issue by osama1403** [react-hook-form/react-hook-form#12350]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/cranky-darkness-z9wcwl?workspaceId=b4117147-d6d0-4b94-8425-5a52d1fdd512

### Steps to reproduce

1. Click on show
2. Append multiple fields
3. remove some
4. Click show again to hide
 removed fields are being restored.

### Expected behaviour

removed elements shouldn't be restored.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nayounsang** [comment]
Hi. I want to write test about this for those trying to solve this PR.
Can I proceed?

**Comment by osama1403** [comment]
> Hi. I want to write test about this for those trying to solve this PR. Can I proceed? Maybe, this is intended when `shouldUnregister` is `true`.

Go ahead.
I don't think it is intended since it works fine when the "fieldArray" isn't in a nested separate component.

**Comment by NarenderDhamarlapally** [comment]
{ shouldUnregister: true }

remove this it is working as expected

**Comment by osama1403** [comment]
> { shouldUnregister: true }
> 
> remove this it is working as expected

Yes, but then the form keeps the values of the fields and submits them.
should unregister deletes the values of fields when they unmount.

**Comment by nayounsang** [comment]
Hi. This is test code for debugging.
```typescript
  it('should remove fields in the unregistered form', () => {
    const Nested = () => {
      const { control } = useFormContext();
      const { fields, append, remove } = useFieldArray({
        control: control,
        name: 'contacts',
      });
      return (
        <div className="nested">
          <div className="btns">
            <button
              type="button"
              onClick={() => {
                append({ name: '', value: '' });
              }}
            >
              Append
            </button>
            <button
              type="button"
              onClick={() => {
                remove(fields.length - 1);
              }}
            >
              Remove Last
            </button>
          </div>

          {fields.map((field, idx) => {
            return (
              <div className="contact-inputs" key={field.id}>
                {/* Name */}
                <Controller
                  control={control}
                  name={`contacts.${idx}.name` as const}
                  render={({ field }: { field: any }) => (
                    <input type="text" {...field} />
                  )}
                />
                <Controller
                  control={control}
                  name={`contacts.${idx}.phone` as const}
                  rules={{
                    required: 'this field is required',
                    pattern: {
                      value: /^\d{10}$/,
                      message: 'phone must be 10 digits',
                    },
                  }}
                  render={({ field }: { field: any }) => (
                    <input type="text" {...field} />
                  )}
                />
              </div>
            );
          })}
        </div>
      );
    };

    const Component = () => {
      const form = useForm({ shouldUnregister: true });
      const [show, setShow] = useState(false);

      const submit = () => {};

      return (
        <div>
          <FormProvider {...form}>
            <form onSubmit={form.handleSubmit(submit)} className={'mygrid'}>
              <div className="btns">
                <button
                  type="button"
                  onClick={() => {
                    setShow((p) => !p);
                  }}
                >
                  show
                </button>
                <button>submit</button>
              </div>
              {show && <Nested />}
            </form>
          </FormProvider>
        </div>
      );
    };
    render(<Component />);

    const showButton = screen.getByText('show');
    fireEvent.click(showButton);

    const appendButton = screen.getByText('Append');
    fireEvent.click(appendButton);
    fireEvent.click(appendButton);
    fireEvent.click(appendButton);
    fireEvent.click(appendButton);
    const addedInputFields = screen.getAllByRole('textbox');
    expect(addedInputFields).toHaveLength(8); // PASS

    const removeButton = screen.getByText('Remove Last');
    fireEvent.click(removeButton);
    fireEvent.click(removeButton);
    const removedInputFields = screen.getAllByRole('textbox');
    expect(removedInputFields).toHaveLength(4); // PASS

    fireEvent.click(showButton);
    fireEvent.click(showButton);
    const finalInputFields = screen.getAllByRole('textbox');
    expect(finalInputFields).toHaveLength(4); // FAIL
  });
```
This is a testing implementation of the logic of this issue.
However, based on other tests, it seems inconsistent and not fit for purpose, so I won't post a PR.
This is because append triggers a re-render, but remove does not.
I think I'll need some help after this.

**Comment by endrits079** [comment]
+1, I was using DataGridPro from "@mui" as rows I provided the fields, when I was removing a field DataGridPro throwing an error about all rows should have an "id" when I checked what was happening the deleted field is added back without the id property, but the issue is happening only after you delete the 2nd item,
demo:
https://codesandbox.io/p/sandbox/dv48jd

**Comment by Chthol1y** [comment]
> +1, I was using DataGridPro from "@mui" as rows I provided the fields, when I was removing a field DataGridPro throwing an error about all rows should have an "id" when I checked what was happening the deleted field is added back without the id property, but the issue is happening only after you delete the 2nd item, demo: https://codesandbox.io/p/sandbox/dv48jd

I had the same problem and wanted to know if you solved it yet i😥

**Comment by endrits079** [comment]
> > +1, I was using DataGridPro from "@mui" as rows I provided the fields, when I was removing a field DataGridPro throwing an error about all rows should have an "id" when I checked what was happening the deleted field is added back without the id property, but the issue is happening only after you delete the 2nd item, demo: https://codesandbox.io/p/sandbox/dv48jd
> 
> I had the same problem and wanted to know if you solved it yet i😥

Nope, if you checked my implementation I was using renderCell to render Input components but it was apparently an issue with the DataGrid because using it outside Grid was working fine. I used another approach where I was using onProcessRow callbacks to then update form state, one down side is that I had to move validation on submit. So I don't know what your implementation is but that was not that straight forward

**Comment by Chthol1y** [comment]
> > > +1, I was using DataGridPro from "@mui" as rows I provided the fields, when I was removing a field DataGridPro throwing an error about all rows should have an "id" when I checked what was happening the deleted field is added back without the id property, but the issue is happening only after you delete the 2nd item, demo: https://codesandbox.io/p/sandbox/dv48jd+1，我使用“”中的 DataGridPro 作为我提供的字段的行，当我删除字段时，DataGridPro 抛出有关所有行的错误都应该有一个“id”当我检查发生了什么时，已删除的字段被添加回来，但没有 id 属性，但问题仅在您删除第 2 项后发生， 演示：https://codesandbox.io/p/sandbox/dv48jd
> > 
> > 
> > I had the same problem and wanted to know if you solved it yet i😥我遇到了同样的问题，想知道你是否解决了它😥
> 
> Nope, if you checked my implementation I was using renderCell to render Input components but it was apparently an issue with the DataGrid because using it outside Grid was working fine. I used another approach where I was using onProcessRow callbacks to then update form state, one down side is that I had to move validation on submit. So I don't know what your implementation is but that was not that straight forward不，如果您检查我的实现，我正在使用 renderCell 来渲染输入组件，但这显然是 DataGrid 的问题，因为在 Grid 之外使用它工作正常。我使用了另一种方法，即使用 onProcessRow 回调来更新表单状态，一个缺点是我必须在提交时移动验证。所以我不知道你的实现是什么，但那并不是那么简单

I've run into roughly the same situation, I didn't want to use the editing features of the DataGrid and switched to RHF, and now it looks like I'll have to do it the old-fashioned way, using mui's base Table component

**Comment by bluebill1049** [comment]
```
const App = () => {
  const form = useForm({
    defaultValues: {
      contacts: [],
    },
  });
  const [show, setShow] = useState(false);

  const submit = (v: any) => {
    console.log(v);
  };

  console.log(form.watch());

  return (
    <div>
      <Headers />
      <FormProvider {...form}>
        <form onSubmit={form.handleSubmit(submit)} className={"mygrid"}>
          <div className="btns">
            <button
              type="button"
              onClick={() => {
                setShow((p) => !p);
              }}
            >
              show
            </button>
            <button>submit</button>
          </div>
          {show && <Nested />}
        </form>
      </FormProvider>
    </div>
  );
};

export default App;

const Nested = () => {
  const { control } = useFormContext();
  const { fields, append, remove } = useFieldArray({
    control: control,
    name: "contacts",
    shouldUnregister: true,
  });
  return (
    <div className="nested">
      <div className="btns">
        <button
          type="button"
          onClick={() => {
            append({ name: "", value: "" });
          }}
        >
          Append
        </button>
        <button
          type="button"
          onClick={() => {
            remove(fields.length - 1);
          }}
        >
          Remove Last
        </button>
      </div>

      {fields.map((field, idx) => {
        return (
          <div className="contact-inputs" key={field.id}>
            {/* Name */}
            <Controller
              control={control}
              name={`contacts.${idx}.name` as const}
              render={({ field }: { field: any }) => (
                <input type="text" {...field} />
              )}
            />
            <Controller
              control={control}
              name={`contacts.${idx}.phone` as const}
              rules={{
                required: "this field is required",
                pattern: {
                  value: /^\d{10}$/,
                  message: "phone must be 10 digits",
                },
              }}
              render={({ field }: { field: any }) => (
                <input type="text" {...field} />
              )}
            />
          </div>
        );
      })}
    </div>
  );
};
```

This should resolve the issue.
