### ISSUE TITLE
Problem with PrimeReact component and Controller

### ISSUE THREAD

**Issue by dattebayorob** [react-hook-form/react-hook-form#1235]
**Describe the bug**
Using the PrimeReact component SelectButton with booleans as value, the selected fallback to the component doesnt work.
I dont thing this is a primereact bug, since using the component directly works ( Case sample on the codesandbox above too )

**Codesandbox link (Required)**
https://codesandbox.io/s/elegant-chebyshev-3u0rs

**Expected behavior**
In the code sandebox, The first buttons uses booleans a value
the second one uses a string 
the third show the correct behavior when using boolean as value options.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Chrome and Firefox
 - Version last versions

**Comment by bluebill1049** [comment]
It's not a bug with the Controller, it's probably just about the value that you return. I will take a look at it.

**Comment by dattebayorob** [comment]
Thanks!
The problem happens when a boolean is returned.

**Comment by dattebayorob** [comment]
For now I'm mapping the property to numeric values ( 0 and 1 ) kkkk

**Comment by bluebill1049** [comment]
I see the reason why, we transform boolean value into `checked` attribute which is following the standard checkbox, while PrimeReact only access value. unfortunately, for now you will have to stick with string.

**Comment by dattebayorob** [comment]
Ok, thanks anyway. For now I will use a proxy to convert booleans to string

**Comment by bluebill1049** [comment]
cool, thanks for update.

**Comment by dattebayorob** [comment]
For someone with this problem, I 'solved' in my proxy checking if the prop checked is passed to the component 
```
 const value = props.checked !== undefined ? props.checked : props.value
```

**Comment by bluebill1049** [comment]
thanks @dattebayorob for sharing solution.
