### ISSUE TITLE
Update values in useFieldArray from outside form

### ISSUE THREAD

**Issue by rnnyrk** [react-hook-form/react-hook-form#1236]
Hi,

I'm not sure if I'm doing something wrong, or that I've found a bug. 
Within my project I'm using a `useFieldArray` which contains categories. I can insert a category from a modal. This works fine. But when I try to update the value of this category nothing happens when I use `setValue`, or the `fields` are removed when I reset the values baesd on `getValues()` because the categories aren't an array yet, but save as `categories[0].title: "test"`.

You can find my simplified use case over here: https://codesandbox.io/s/old-glitter-wffzq
Only works for one value now because I'd hardcode the index in `handleUpdate`

How to update a value correctly from outside the form?
Thanks in advance for your help!

**Comment by bluebill1049** [comment]
can you do a simple version (remove all the complexity and redux)? keep it simple and it helps me as well.

**Comment by rnnyrk** [comment]
@bluebill1049 Although I don't think it should matter I'd clean up the example. Hopefully this helps ;)

**Comment by bluebill1049** [comment]
thank you @rnnyrk it's just a bit easier for me to take a look tonight.

**Comment by bluebill1049** [comment]
taking a look now, sorry for the delay...

**Comment by bluebill1049** [comment]
I am not to sure about the context of having input hidden, but i did it with just a normal input: https://codesandbox.io/s/purple-http-6mhyy

**Comment by rnnyrk** [comment]
@bluebill1049 No worries about being a but later. We're all human haha :) 

Taken from your example;
![Uploading Screenshot 2020-03-20 at 11.59.23.png…]()

You can see the input value being updated, but the logs and the "test" behind the the input still showing the old value. 

My use case is that I add a category of `useFieldArray` from within a modal. Then the category title isn't shown in an input, but as title of a block. 

<img width="724" alt="Screenshot 2020-03-20 at 12 03 23" src="https://user-images.githubusercontent.com/4519142/77158257-3f27ae00-6aa3-11ea-9a1a-9dd23f049d8b.png">

So the red circle is the title from the `useFieldArray`, but to actually save the value (and the order) within the `useFieldArray` I use a hidden input. I use hidden inputs because I have to send the values to my backend

So my code looks like:

```
      {fields.map((field, index) => {
        return (
          <EditionsCategory key={`edition_category_${index}`}>
            <Input
              name={`categories[${index}].title`}
              type="hidden"
              defaultValue={field.title || undefined}
              register={register()}
              noFieldset
            />
            <Input
              name={`categories[${index}].order`}
              type="hidden"
              defaultValue={index}
              register={register()}
              noFieldset
            />

            <EditionsCategoryHeader
              title={field.title}
              handleDelete={() => handleDeleteCategory(index)}
              handleEdit={() => handleEditCategory(field.title, index)}
              handleMove={(direction) => handleMoveCategory(direction, index)}
              handleSelect={handleSelect}
            />
            <EditableTable
              columns={memoHeaderCustomCategory}
              data={[]}
              newRowForm={AddCustomCategoryForm}
            />
          </EditionsCategory>
        );
      })}
```

The green circle opens a modal to edit the title value which is prefilled within the modal. When I save the edit modal the `handleUpdate` from the codesandbox is triggered. But as seen in both codesandbox examples the `field.title` isn't updated correctly. 

Hope you understand my use case and issue now :)

**Comment by bluebill1049** [comment]
can you please reupload the image above (not found)?

**Comment by bluebill1049** [comment]
for your use case, wouldn't it be easier just a form in the modal and each form submit inject data into a local state?

```
const [data, setDate] = useState()

<Model>
  <form/>
</Model>

<List data={data} />
```

**Comment by rnnyrk** [comment]
Re-uploaded the photo. Hmm indeed might be able to solve it with localstate. But since I use a `useFieldArray` I have to create local state for every title in the field array. Have to refactor some stuff to make it easy to manage. I'll come back at you later today, thanks for the help so far.

**Comment by bluebill1049** [comment]
yea, I prefer simple solutions, because your use case is more like a form and submit into the store and display.

**Comment by bluebill1049** [comment]
if you want the above example to work (which I do not recommend) is using `watch`, I still prefer the simple solution which I proposed.

**Comment by bluebill1049** [comment]
hey @rnnyrk just a quick follow up on this, how did you go with it?

**Comment by rnnyrk** [comment]
Sorry for the late response. I did manage to fix it by using the `watch` methods provided by `useForm`, In my opinion this was the most simple fix for the use case.

**Comment by bluebill1049** [comment]
awesome. glad it's working for you now. thanks for the update.
