### ISSUE TITLE
Component wrapped under <Controller> not being autoselected(focused) after validation error

### ISSUE THREAD

**Issue by JuanmaMenendez** [react-hook-form/react-hook-form#1237]
**Describe the bug**
After a submit, the corresponding validation error is properly detected but the Component wrapped under \<Controller\> not being autoselected(focused).

**To Reproduce**
1. Go to https://codesandbox.io/s/mui-autocomplete-with-react-hook-form-ljttt
2. Click on 'Get Country Code' button

**Codesandbox link (Required)**
https://codesandbox.io/s/mui-autocomplete-with-react-hook-form-ljttt

**Expected behavior**
After the error, the <Autoselect> Component should be autofocused in order the user selects a proper value

**Comment by bluebill1049** [comment]
This is expected. I will need to include this in the doc. Because the external controlled component doesn't guarantee to provide ref.

**Comment by JuanmaMenendez** [comment]
@bluebill1049 don't you think that behavior will affect the user experience? I am pretty sure it will.

Do you have any workaround? 

Thanks for your answer and time

**Comment by bluebill1049** [comment]
> @bluebill1049 don't you think that behavior will affect the user experience? I am pretty sure it 
will.

@JuanmaMenendez This is not a problem for this lib. In fact react hook form is trying to  improve the experience for the user when you are using native inputs (because ref is exposed and we can focus on the error input). How can we guarantee external lib provide the correct ref?  eg: AntD's input ref is an `object` which contains all thoughts of data.

As workaround: you will have to hold the ref of those external component and focus them at your app level.

**Comment by JuanmaMenendez** [comment]
can you please show us a code example of the workaround, maybe this codepen can be used as reference https://codesandbox.io/s/mui-autocomplete-with-react-hook-form-ljttt it uses material UI

I believed Controller always had access to the internal ref, I don't know how it has access to the internal values if is not through the ref.

PS: I really love your library and appreciate your support

**Comment by bluebill1049** [comment]
> I believed Controller always had access to the internal ref, I don't know how it has access to the internal values if is not through the ref.

No, we actually don't. It's just wrapper component which render the external component.

Here is the idea and example:

```
export default function App() {
  const inputRef = useRef();
  const { control, handleSubmit, watch, errors } = useForm({});

  useEffect(() => {
    if (errors.test) {
      inputRef.current.focus();
    }
  })

  return (
    <form onSubmit={handleSubmit(data => console.log(data))}>
      <Controller as={<ExternalInput ref={inputRef} />} name="test" control={control} />
      <button>Submit</button>
    </form>
  );
}
```

**Comment by bluebill1049** [comment]
also this what i am going to update on the FAQ, let me know if this make sense or things you would like to improve. i am supply with an example as well:

>           <p>
>             React Hook Form will focus on the native input automatically when
>             the user is submitting the form. However, it's difficult to predict
>             an external controlled component's <code>ref</code>. As a
>             workaround, you can trigger the external component's focus event or
>             manually focus on the external controlled component (if you can get
>             the actual input <code>ref</code>).
>           </p>

**Comment by JuanmaMenendez** [comment]
I think an explanation a little more practical for non expert people could be something like:

"After a validation error, **React Hook Form** will automatically focus on the invalids elements of which have their proper **ref**, like the native inputs (eg: **\<input type="text"\>**) or some 3rd party Components that correctly export his **ref** (eg: from MUI **<TextField name="zipcode"  inputRef={register({required: 'Field Required'})}** />)

However, for some 3rd party controlled Components like **\<Autocomplete\>** from MUI or **\<XX\>** from AntD) it's very difficult to predict his <code>ref</code> because the formats changes, so **React Hook Form** will properly detect the validation error but will not be able to automatically focus that kind of Components.

As a workaround, after the validation error, you can manually focus on the 3rd party controlled Component (if you can get the actual internal input <code>ref</code>), for example:

code example here.... "

**Comment by JuanmaMenendez** [comment]
One thing I want to add to the debate for future users who have this kind of situation is that it is possible to disable the "autofocus on error" feature for all the form. Maybe this behavior will bring a better user experience in some cases.

You just need to call **useForm** with **{submitFocusError: false}**

`const { handleSubmit, register, control, errors, watch} = useForm({submitFocusError: false});`

**Comment by bluebill1049** [comment]
awesome thanks @JuanmaMenendez, we can include that message in the description as well.

**Comment by bluebill1049** [comment]
thank you for your contribution, website is updated.

**Comment by JuanmaMenendez** [comment]
**UPDATE**

Now, It is possible to autofocus the Controller wrapped component on error.

See:

https://github.com/react-hook-form/react-hook-form/pull/1296
https://codesandbox.io/s/react-hook-form-controller-test-out-ref-7imfk

PS: Be sure to update your RHF version
