### ISSUE TITLE
issue: UI not refreshing after validation trigger

### ISSUE THREAD

**Issue by maniekpl00** [react-hook-form/react-hook-form#12376]
### Version Number

7.52.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/clever-phoebe-gsxx7s?workspaceId=e3d19873-74be-401c-9ed5-b17a082e3cec

### Steps to reproduce

1. Click `Submit` to trigger validation
2. See error that user name require `Minimum 4 chars`
3. Disable field by unchecking `Enable user` 

### Expected behaviour

After updating to version 7.52.2, the validation error message for 'Minimum 4 Characters' does not clear as expected. 

Previously, the UI would refresh correctly after manually triggering validation based on another field, but this functionality has been disrupted in the latest version. 
Calling `trigger` require now to put `exact` field name to have refreshed UI, which is inconvenient when field has a lot of input forms inside. 

It can be related to changes inside useController, that useFormState use `exact` prop now.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maniekpl00** [comment]
It seems when I wrap field name into array ```trigger([`users.${index}`])``` it to re-trigger the entire form state it works. But question is if it was intentional and even if yes, this release broke old API  😃

**Comment by bluebill1049** [comment]
trigger will need exact name as always, unless you want to trigger the entire form with empty payload.
