### ISSUE TITLE
issue: watch is not called when appending first item to Field Array

### ISSUE THREAD

**Issue by mksawic** [react-hook-form/react-hook-form#12370]
### Version Number

7.53.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/watch-not-called-qy5l9z

### Steps to reproduce

In our project, we just upgraded from `7.53.0` to `7.53.1` and our unit tests failed.
It turned out that the callback inside `watch` was not triggered for the first call to the `append` method coming from `useFieldArray`.
Inside the watch callback, we synchronize with the Redux store and check this synchronization in tests.
This problem did not occur for the previous version of the package. 
I also noticed that removing the `watch` method from `deps array` in useEffect fixes this problem, however according to the [documentation](https://react-hook-form.com/docs/useform/watch) this method should remain in the array if we don't want to trigger re-renders.

### Expected behaviour

Watch callback should be called even after first call of append method.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by OlegDev1** [comment]
When I delete `watch` from `deps array` nothing changes, i still have one initial log and then two logs once i append an item. Can you please give another example?

**Comment by mksawic** [comment]
@OlegDev1 Can you check it now please? I've refactor it a little (for example extracting an `addItem` method). 
Now in console output I can see that this issue is back
<img width="1685" alt="image" src="https://github.com/user-attachments/assets/9d841e3d-f6ed-4e83-b7af-67775acf7405">

**Comment by OlegDev1** [comment]
@mksawic  Thank you for clarification. I guess this commit can cause the issue https://github.com/react-hook-form/react-hook-form/commit/67de1a4bde2441feea66c3707ce83512ab230e88. It was introduced in version `7.53.1`

**Comment by OlegDev1** [comment]
I have noticed that on the first append, `watch` changes triggering `useEffect` cleanup function. It resubscribes to watch. That's why deleting `watch` from the dependencies is a workaround for this bug, but it should be fixed

**Comment by OlegDev1** [comment]
After deleting this part of the code, more specifically the `bind` method, everything works as expected. I have debugged for a while, but still do not understand how it can be fixed. After the first append, this useEffect is not called, because formState hasn't changed, so it shouldn't change the reference, but it seems like it still changes it somehow, causing this bug. Any thoughts?
https://github.com/react-hook-form/react-hook-form/blob/79964dc6ead20652dbe7e32d4b54558cd7dd4c97/src/useForm.ts#L157-L161

**Comment by bluebill1049** [comment]
> After deleting this part of the code, more specifically the `bind` method, everything works as expected. I have debugged for a while, but still do not understand how it can be fixed. After the first append, this useEffect is not called, because formState hasn't changed, so it shouldn't change the reference of `watch`, but it seems like it still changes it somehow, causing this bug. Any thoughts @bluebill1049?
> 
> https://github.com/react-hook-form/react-hook-form/blob/79964dc6ead20652dbe7e32d4b54558cd7dd4c97/src/useForm.ts#L157-L161

let me revert back for now.

**Comment by bluebill1049** [comment]
It would be good to add a test case if anything is keen to contribute

**Comment by mksawic** [comment]
@OlegDev1 @bluebill1049 Thanks for resolving this issue :) Cheers

**Comment by OlegDev1** [comment]
@mksawic you are welcome. If anything, feel free to email
