### ISSUE TITLE
issue: Errors is always empty

### ISSUE THREAD

**Issue by delyan-peev** [react-hook-form/react-hook-form#12374]
### Version Number

7.53.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/naughty-wu-kvwt6d?workspaceId=628a40f2-3630-474d-9d81-d89db965fed3

### Steps to reproduce

Can someone explain why isValid in the provided CSB goes correctly from false to true, but errors are always empty, even though my revalidateMode is onChange?

This makes it extremely hard to communicate to users what exactly about a form is invalid, so they can fix it pre-submission.

I've tested it with both a zodResolver and a custom one. Nothing seems to work as expected.

### Expected behaviour

formState.errors should represent the actual state of the errors form

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JardelCheung** [comment]
mode                    Validation strategy before submitting behaviour.
reValidateMode    Validation strategy after submitting behaviour.

![image](https://github.com/user-attachments/assets/80f7b7be-7411-46ed-97d3-9a4fd021b232)


refer : https://react-hook-form.com/docs/useform#reValidateMode

**Comment by delyan-peev** [comment]
Ah, RTFM. Thanks! Closing this.
