### ISSUE TITLE
Implementation of triggerValidation() causes TypeScript warning

### ISSUE THREAD

**Issue by don-motorefi** [react-hook-form/react-hook-form#1238]
**Describe the bug**
The type definition for triggerValidation() shows that it returns a Promise.  If the Promise isn't handled in the calling code - as shown in the docs example - then this causes a TS warning when checking Promise via eslint:
```
    triggerValidation: (payload?: FieldName<FormValues> | FieldName<FormValues>[] | string, shouldRender?: boolean) => Promise<boolean>;
Promises must be handled appropriately eslint(@typescript-eslint/no-floating-promises)
```

**To Reproduce**
1. Add the eslint rule noted above.
2. Call `triggerValidation()` without handling the Promise, as documented in https://react-hook-form.com/api#triggerValidation
3. Note that the TS warning above will be caused.

**Expected behavior**
The documentation doesn't give any indication that `triggerValidation` should need to be handled as a Promise, or what the return value of the Promise would be used for.  If the existing validations will be triggered, then their side-effects should be triggered as well - like updating the Errors object - so there shouldn't be many cases when special-case code would be needed after manually triggering the validation.  So, if we don't need to subscribe to a Promise, this shouldn't cause a warning.

**Comment by bluebill1049** [comment]
`triggerValidation` return a promise because user still subscribe to the validation result and does some action upon it. however, you can still omit such behaviour, i think the type is correct for what it returns and it's intension.
