### ISSUE TITLE
Return boolean from setFocus to allow for retries

### ISSUE THREAD

**Issue by danilofuchs** [react-hook-form/react-hook-form#12382]
**Is your feature request related to a problem? Please describe.**
When triggering `setFocus` on a form that opens after a transition, I must add a `setTimeout` to make sure the input is registered. However, the timeout amount is arbitrary, and may be different in test environments, or reduced motion

**Describe the solution you'd like**
`setFocus` could return `false` if it was unable to focus, and we implement retries in userland

**Describe alternatives you've considered**
- react-hook-form could retry focus automatically
- setFocus could throw if unable to find element (breaking change, and annoying behavior)
- Method to check if field is registered (maybe `getFieldState().isRegistered`?)

**Comment by bluebill1049** [comment]
instead bake into function, maybe we should consider to return mounted for this function: https://react-hook-form.com/docs/useform/getfieldstate
