### ISSUE TITLE
issue: FieldError is not correct on nested fields inside controller

### ISSUE THREAD

**Issue by IdoBouskila** [react-hook-form/react-hook-form#12388]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://stackblitz.com/edit/react-hook-form-error-type?file=src%2FApp.tsx

### Steps to reproduce

1. Open the provided reproduction code.
2. Look at the structure of the scheme.
3. See line 48, you will notice that the type of `error` in the Controller is different from the type at run time.

### Expected behaviour

In my opinion, the type of *error* should match the type in runtime.
It is important to note that I know that we won't have to put several fields under the same Controller most of the time, instead, we will define one per field.
I came across this in an edge issue that I was messing with and it doesn't seem right to me.
WDYT? 🤔

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I think we will take the bites on this one as a design limitation without further complicated the existing type for useController.
