### ISSUE TITLE
issue: Form State subscribed to through `useController` not causing re-renders on update

### ISSUE THREAD

**Issue by Scott-Z-IRC** [react-hook-form/react-hook-form#12381]
### Version Number

7.53.1

### Codesandbox/Expo snack

https://stackblitz.com/edit/vitejs-vite-9ud1h9?file=src%2Fcomponents%2Fenditable-input.tsx,src%2Fcomponents%2Fform.tsx

### Steps to reproduce

useController hook not causing re-render when form state changes.  
1. Open app link
2. Presented with form with 4 fields
3. Open Console
4. Edit 1 of the fields
5. When editing the field, only that field logs "is form dirty". 
6. All `editable-input` fields are subscribed to changes in form state via the `useController` hook. 

### Expected behaviour

Since all fields are subscribed to `formState` accessed through the `useController` hook, I would expect all 4 form fields to re-render when `isDirty` changes for the form. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rrrrrrrrrrrocky** [comment]
Me too...

**Comment by JardelCheung** [comment]
https://github.com/react-hook-form/react-hook-form/blob/09a9a495ec8374cbce00e6006026069150a2e3e7/src/__tests__/useController.test.tsx#L32
https://github.com/react-hook-form/react-hook-form/blob/09a9a495ec8374cbce00e6006026069150a2e3e7/src/useController.ts#L70-L71

The source code does not support this issue.
Looking forward to this too.(subscribe to all inputs' formState update.)

**Comment by bluebill1049** [comment]
Yea, you will have to `useFormState` or `useFormContext`
