### ISSUE TITLE
issue: field value empty in submit data when having dynamic disabled in useForm

### ISSUE THREAD

**Issue by nothumbee** [react-hook-form/react-hook-form#12398]
### Version Number

7.53.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/kgxnwq

### Steps to reproduce

1. Go to the sandbox
2. Click on Set editable button
3. Fill in the required field
4. Submit the form
5. See console - the first field (has default value) is empty in submit data
6. Also try to edit the first field and submit again, the value is still empty

### Expected behaviour

the first field will have correct value in submit data and it will be possible to edit correctly when using dynamic disabled prop on the whole form

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pepakriz** [comment]
I can confirm the same error in our codebase. Downgrading to 7.52.2 solved the problem.

**Comment by bluebill1049** [comment]
additional issue the form shouldn't be able to submit if the form is disabled too.
