### ISSUE TITLE
Change a manually registered field from an action

### ISSUE THREAD

**Issue by IngenieroLata** [react-hook-form/react-hook-form#1240]
I'm working on a react native app. And have the case where one field is changed by some action. I'm manually registering the fields since the Controller won't work as its a custom component. But when I invoke the `setValue` doesn't visually change the controls and I know it's because I'm using an internal state but haven't found a way to access the form values by listening something. Here is a light example (without the date picker. Couldn't make it run in the snack)

**To Reproduce**
1. Go to https://snack.expo.io/@ingenierolata/set-values
2. Click on 'Set User'
3. See the controls didn't change its visible value
4. Click on 'Submit'
5. Open the logs and see the form state is updated.

**Codesandbox link (Required)**
https://snack.expo.io/@ingenierolata/set-values

**Additional context**
By using the Controlled component I could make work the `TextInput` but not a DatePicker. But sometimes throws an error regarding the value being an object instead of a string. It only happens in the device.

**Comment by bluebill1049** [comment]
> By using the Controlled component I could make work the TextInput but not a DatePicker. But sometimes throws an error regarding the value being an object instead of a string. It only happens in the device.

because you are not return the correct data for the input. Just like the error message says: it's expecting an object instead a string.

**Comment by bluebill1049** [comment]
I have also replied you at spectrum as well.

**Comment by IngenieroLata** [comment]
@bluebill1049 So the only way to visually control a component is by the `Controller`? For a Manually registered field there is no way to trigger the same behavior when calling `setValue`?

**Comment by bluebill1049** [comment]
> @bluebill1049 So the only way to visually control a component is by the `Controller`? For a Manually registered field there is no way to trigger the same behavior when calling `setValue`?

otherwise you will have to use `watch()`.

```
const value = watch('yourInput')

useEffect(() => {
  setValue('yourInput', 'test')
})

<TextInput value={value} name="yourInput" />
```

**Comment by IngenieroLata** [comment]
Oh yes! It worked. My real problem is not the TextInput but DateTimeControl as it doesn't have a visual input with value prop to be accessed from a ref. So basically a hook that handles the registration process and listens for its own value in case of an external change will make it for any weird custom field component. Something like this

```typescript 
import { useState, useEffect } from 'react'
import { useFormContext } from 'react-hook-form'
import get from 'lodash/get'

export const useControl = (name, validateRule, fallbackDefaultValue = '') => {
  const {
    register,
    unregister,
    watch,
    setValue,
    control: { defaultValuesRef },
  } = useFormContext()
  const defaultValue = get(defaultValuesRef.current, name, fallbackDefaultValue)
  const [innerValue, setInnerValue] = useState(defaultValue)

  const value = watch(name)

  useEffect(() => {
    if (value !== innerValue) {
      setInnerValue(value)
    }
  }, [value, innerValue, setInnerValue])

  useEffect(() => {
    register({ name }, validateRule)

    return () => {
      unregister(name)
    }
  }, [register])

  const onChange = text => {
    setInnerValue(text)
    setValue(name, text, true)
  }

  return {
    onChange,
    viewValue: innerValue,
  }
}


```

**Comment by bluebill1049** [comment]
cool glad it's working for you. 👍 thanks for sharing the code too.
