### ISSUE TITLE
issue: Warning: Cannot update a component while rendering a different component.

### ISSUE THREAD

**Issue by Wendystraite** [react-hook-form/react-hook-form#12400]
### Version Number

7.53.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-render-error-usecontroller-2-f29fdq

### Steps to reproduce

1. Go to https://codesandbox.io/p/sandbox/react-hook-form-render-error-usecontroller-2-f29fdq
2. Click on the submit button
3. Wait 500ms
4. See error in console

Other way to reproduce the bug :
1. Go to the same codesandbox https://codesandbox.io/p/sandbox/react-hook-form-render-error-usecontroller-2-f29fdq
2. Open "MyFormProvider.tsx"
3. Comment the lines 34 to 39
4. Uncomment the line 47
5. Reload the app
6. See error in console at start

### Relevant informations

For the bug to appear you need :
- A controlled field using `useController`
- Both `isValidating` and `isValid` from a component using `useFormState`

### Expected behaviour

Not seeing the warning

### What browsers are you seeing the problem on?

Chrome, Edge

### Relevant log output

```shell
onSubmit {foo: ''}
onSubmit {foo: ''}
onSubmit finished {foo: ''}
onSubmit finished {foo: ''}
 Warning: Cannot update a component (`IsValidating`) while rendering a different component (`MyControlledTextField`). To locate the bad setState() call inside `MyControlledTextField`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at MyControlledTextField (https://f29fdq.csb.app/src/MyFormContent.tsx:26:5)
    at MyFormContent
    at exports.FormProvider (https://f29fdq.csb.app/node_modules/react-hook-form/dist/index.cjs.js:1:24805)
    at form
    at MyFormProvider (https://f29fdq.csb.app/src/MyFormProvider.tsx:16:5)
    at App
console.<computed> @ index.js:9
p @ preview-protocol.js:57
console.<computed> @ index.js:9
printWarning @ 
error @ 
warnAboutRenderPhaseUpdatesInDEV @ 
scheduleUpdateOnFiber @ 
dispatchSetState @ 
next @ 
next @ 
T @ 
R @ 
O @ 
U @ 
oe @ 
R @ 
MyControlledTextField @ 
renderWithHooks @ 
updateFunctionComponent @ 
beginWork @ 
beginWork$1 @ 
performUnitOfWork @ 
workLoopSync @ 
renderRootSync @ 
performConcurrentWorkOnRoot @ 
workLoop @ 
flushWork @ 
performWorkUntilDeadline @ 
 Warning: Cannot update a component (`IsValidating`) while rendering a different component (`MyControlledTextField`). To locate the bad setState() call inside `MyControlledTextField`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at MyControlledTextField (https://f29fdq.csb.app/src/MyFormContent.tsx:26:5)
    at MyFormContent
    at exports.FormProvider (https://f29fdq.csb.app/node_modules/react-hook-form/dist/index.cjs.js:1:24805)
    at form
    at MyFormProvider (https://f29fdq.csb.app/src/MyFormProvider.tsx:16:5)
    at App
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Wendystraite** [comment]
I don't have the time right now to investigate further, but if someone has the same use case as I do, I've commented some code in the codesandbox to avoid the bug. You have to move the triggering code below the `useForm` call.

In my initial investigation, something seemes to happen when calling `control.register` inside the `useController` hook's render method.
This call lead to `updateValidAndValue` being triggered inside the form control, which then causes a re-render of the component using `useForm`.

**Comment by jochenschmich-aeberle** [comment]
I'm facing the exact same issue:

This happens when I want to add a Component that should show all of the errors in the Form at form level.

**Comment by SaintPepsi** [comment]
See https://github.com/react-hook-form/react-hook-form/issues/12518#issuecomment-2586001615
