### ISSUE TITLE
issue: useFieldArray does not work correctly when setting disabled in useForm

### ISSUE THREAD

**Issue by 052hide** [react-hook-form/react-hook-form#12407]
### Version Number

7.53.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/cool-paper-32mxml?workspaceId=3a4ca9db-0b86-4678-90ae-b21ed8bdd8d6

### Steps to reproduce

https://github.com/react-hook-form/react-hook-form/issues/12249

1. Go to sandbox
2. Click on "Append Item" button several times
3. Not added to items

### Expected behaviour

addition of items correctly

---

- v7.52.2 does not have this problem
- It probably does not occur if disabled is not set

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by OlegDev1** [comment]
The issue was caused by changes to either `createFormControl`, `hasPromiseValidation` or `iterateFieldsByAction` in version 7.53.0. https://github.com/react-hook-form/react-hook-form/compare/v7.52.2...v7.53.0

**Comment by Avilaaiops** [comment]
Thanks @OlegDev1 I will try updating the package and see if that works.
