### ISSUE TITLE
Error message keep showing on pattern validation

### ISSUE THREAD

**Issue by asjamsuri** [react-hook-form/react-hook-form#1241]
**Describe the bug**
Error message keep showing on focus/blur conditions even if in valid conditions.
FYI, I'm using pattern validation. Am I doing it wrong?

**To Reproduce**
1. Go to [https://g18sm.csb.app/](https://g18sm.csb.app/)
2. Do complete the 4-digit PIN, and it should be a valid value.
3. Repeat: Focus, Blur, Focus, Blur, and etc.
4. The error message will keep showing and hiding.

**Codesandbox link (Required)**
[https://codesandbox.io/s/react-hook-form-error-message-issue-g18sm](https://codesandbox.io/s/react-hook-form-error-message-issue-g18sm)

**Expected behavior**
The error message shouldn't be shown.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 78.0.3904.108 (Official Build) (64-bit)

Thanks in advance!

**Comment by bluebill1049** [comment]
please validate your own regex. https://regex101.com/

**Comment by asjamsuri** [comment]
Ah. I'm so sorry about that.
Thank you for your fast response.
I've fixed my regex and it worked perfectly!

**Comment by bluebill1049** [comment]
no worries :) glad you work it out. <3
