### ISSUE TITLE
issue: useForm shouldn't return the same object - react-complier/memo issue

### ISSUE THREAD

**Issue by mfazekas** [react-hook-form/react-hook-form#12423]
### Version Number

7.53.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/thirsty-keller-zdcy4q

### Steps to reproduce

1. Open https://codesandbox.io/p/sandbox/thirsty-keller-zdcy4q
2. Enter something to age  like 999
3. See that no validation error is shown

Or see 
https://next-15-form-git-main-miklosfazekas.vercel.app

Which has 3 forms:
1. Default ShadCN form - [src](https://github.com/mfazekas/next-15-form/blob/main/app/profile-form.tsx)
2. Default ShadCN form with react compiler disabled - [src](https://github.com/mfazekas/next-15-form/blob/main/app/profile-form-no-rc.tsx)
3. Default ShadCN form and forcing new object form form  - [src](https://github.com/mfazekas/next-15-form/blob/main/app/profile-form-workaround.tsx)

<img width="390" alt="image" src="https://github.com/user-attachments/assets/54568fd9-da37-4153-8b36-ce8ae71a21a3">

### Expected behaviour

Validation error should be shown

### What browsers are you seeing the problem on?

Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stropitek** [comment]
Should this be reopened since the fix was reverted in https://github.com/react-hook-form/react-hook-form/releases/tag/v7.54.1 ?
