### ISSUE TITLE
Checkbox checked state should change when clicking on associated label

### ISSUE THREAD

**Issue by borderistheocean** [react-hook-form/react-hook-form#12435]
**Problem description**
We're working on some modifications to a web app and from a usability point of view it would make sense if a user was able to tap on checkbox labels to toggle their checked state. Checkboxes generally are quite small and in vanilla HTML [as shown on W3](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_checkbox) tapping or clicking on an associated label does change the checkbox state which doesn't happen on forms created in react-hook-form

**The solution**
It would be good to have labels that alter the checkbox state when clicked or tapped.

**Alternatives considered**
One way to get around this is to add key and click event listeners to the label element but this has been tested is proving to be unreliable when the checkbox is a required field - no error is shown when manually setting the value of the checkbox to false for instance. There is the issue of us adding events on non-interactable elements which eslint does not like.

**Additional context**
Using version 7.19.5, tried latest 7.53.2 version and the result was the same

**Comment by ShyneADL** [comment]
Assign this task to me please

**Comment by bluebill1049** [comment]
what does this feature got to do with react hook form?

**Comment by borderistheocean** [comment]
So I think this functionality should be standard, this is how checkbox labels work in pure in HTML

**Comment by borderistheocean** [comment]
Turns out we weren't using the id tag on the <input> element, ignore this
