### ISSUE TITLE
issue: `useController`/`<Controller />` don't react to updates of nested values

### ISSUE THREAD

**Issue by ipanasenko** [react-hook-form/react-hook-form#12436]
### Version Number

7.53.2

### Codesandbox/Expo snack

`useController`: https://codesandbox.io/p/sandbox/rhf-array-forked-zxwfvg
`<Controller />`: https://codesandbox.io/p/sandbox/rhf-array-forked-y46hcj

### Steps to reproduce

1. Click "Update nested value" button
2. Expected: both numbers should change
    Actual: only nested number changes

### Expected behaviour

Both numbers should change. `useController` should provide an updated object, if any nested part of it changes.
`useWatch` works fine with this case. Adding `useWatch` next to `useContoller` makes object to be up-to-date.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShyneADL** [comment]
please assign this issue to me

**Comment by ipanasenko** [comment]
Wdym good use case? 
We had a bug in production because of this non-obvious behaviour. Totally expected this to work

**Comment by ipanasenko** [comment]
Right now we had to create a custom hook that uses both `useWatch` + `useController` to fix this bug. And we wrote a custom eslint rule to avoid using `useController` directly from `react-hook-form`. This is less than ideal, I have to say 😐
```ts
import {
  Controller as RHFController,
  useController as useRHFController,
  useWatch,
} from 'react-hook-form';

export const useController: typeof useRHFController = (props) => {
  useWatch(props);
  return useRHFController(props);
};

export const Controller: typeof RHFController = (props) => {
  useWatch(props);
  return <RHFController {...props} />;
};

```
