### ISSUE TITLE
Optimize FormProvider Rendering with use-context-selector

### ISSUE THREAD

**Issue by marcocondrache** [react-hook-form/react-hook-form#12430]
### Problem Statement
The current implementation of FormProvider can trigger unnecessary re-renders in components that consume the context, even when the specific context values they rely on haven't changed. This can impact performance, particularly in complex forms with many components.

### Proposed Solution
Refactor the internal usage of React context within FormProvider to use the [use-context-selector](https://www.npmjs.com/package/use-context-selector) library. This library provides fine-grained control over context value selection, effectively reducing the number of re-renders by isolating updates to only the necessary consumers.

The approach aligns with the proposed feature in [React RFC #119](https://github.com/reactjs/rfcs/pull/119) and ensures compatibility with existing React versions.

### Contribution
If this proposal is deemed suitable, I am willing to work on and submit a PR to implement the change.

**Comment by bluebill1049** [comment]
This PR may just address this issue, probably can skip use context API: https://github.com/react-hook-form/react-hook-form/pull/11522

**Comment by bluebill1049** [comment]
Put into progress, will use that PR as solution for now.
