### ISSUE TITLE
issue: handleSubmit callback typing expects defined values, but disabling a field gives undefined on submit

### ISSUE THREAD

**Issue by Qwennnnnnn** [react-hook-form/react-hook-form#12447]
### Version Number

7.51.4

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-disabled-inputs-oihxx

### Steps to reproduce

1. Create FormValues type with non-undefined fields (for example: `string`)
2. Disable the associated field
3. Submit
4. The value given in the handleSubmit callback is undefined ([see here ](https://react-hook-form.com/docs/useform/register) : >disabled input will result in an undefined form value)
But the typing only expects defined values (in our example: string). So, no error is raised by Typescript

### Expected behaviour

The typing of the handleSubmit callback warns you that values can be undefined, and that possibility should be handled.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by terragady** [comment]
shouldn't you update to newest version before opening new issue? :)

**Comment by bluebill1049** [comment]
```
 <fieldset disabled>
  <input {...register("lastName")} placeholder="First Name" />
</fieldset>
```

not possible with runtime vs type check
