### ISSUE TITLE
Higher level support for email validation and maybe other validations

### ISSUE THREAD

**Issue by davidnewcomb** [react-hook-form/react-hook-form#12441]
**Is your feature request related to a problem? Please describe.**
Kind of. I've been going through your closed bug list and there are plenty of requirements for it. The project supports other html attributes like minLength but the support for handling email address fields is not great.

**Describe the solution you'd like**
```
<input {...register('email', { required: true, email: true })} />
```
or
```
<input {...register('emailConform', { required: true, pattern: {value: 'email', message: 'bad email address'}} )} />
<input {...register('emailConform', { required: false, pattern: 'email')} />
```
I think I prefer option 1 for simplicity value but option 2 would probably fit into your ecosystem better. It could be extended in some way via 3rd party plugins/addons for commonly used validators without having to get into `yup` or similar. e.g.
```
const {register, validatorRegistration} = useForm()
validatorRegistration.add('partnumber', /[asd]-[123]/)
<input {...register('emailConform', { required: false, pattern: 'partnumber')} />
```
That kind of thing. Now that I've written it out, I like option 2 better!

**Describe alternatives you've considered**
There are plenty of issues related to people using `type="email"` and then complaining that the browser takes over and they can't add a nice error message in the same way as the other fields.
There are plenty of people trying to validate an email address and wondering what the correct regular expression is for it.

**Additional context**
This is a case for D.R.Y. Everyone has to implement boiler plate validation of email addresses. that everyone has to include in all their projects or it could be included once in your project and used everywhere.

Option 2 would simplify and reduce copying regular expressions and validation rules all over the place.

**Comment by davidnewcomb** [comment]
Just saw you have a `resolver` that makes plugging in `yup` kind of easy and they have validators for email addresses and custom types. I guess I just wanted to make it easier for myself without having to learn another package as email address is so commonly used and yet it's not really supported in a simple way.

**Comment by bluebill1049** [comment]
I think this is something we won't bake into the lib. thanks for the feature request.
