### ISSUE TITLE
onSubmit does not work outside material-ui Dialog

### ISSUE THREAD

**Issue by keemor** [react-hook-form/react-hook-form#1244]
Hi :smiley:

**Describe the bug**
onSubmit does not work outside material-ui Dialog
if I put `<form>` inside Dialog, onSubmit works, but Submit button is not always visible

**To Reproduce**
1. Open dialog
2. Press Add button

**Codesandbox link (Required)**
[https://codesandbox.io/s/react-hook-form-material-ui-3pukk](https://codesandbox.io/s/react-hook-form-material-ui-3pukk)

**Expected behavior**
Working onSubmit :)

**Version**
    "@material-ui/core": "4.8.1",
    "primereact": "3.1.4",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-hook-form": "4.2.2",
    "react-scripts": "2.1.8"

**Comment by xiaoyu-tamu** [comment]
Pass handleSubmit to Button. I believe this question been asked couple times

**Comment by xiaoyu-tamu** [comment]
Pass handleSubmit to Button as onClick handler. I believe this question been asked couple times.

**Comment by xiaoyu-tamu** [comment]
This is material-ui question, not react-hook-form, you should ask it in their repo.



If you form is outside Dialog, you can use 
```
          <Button onClick={onSubmit}>
            Add Should always be visible
          </Button>
```
if form is inside Dialog, you can add
```
<Dialog>
  <form style={{ display:'flex',flexDirection:'column' }}>
  </form>
</Dialog>
```

**Comment by bluebill1049** [comment]
thank you for your help @xiaoyu-tamu  <3
