### ISSUE TITLE
issue: form watcher is not triggered on focus/blur events

### ISSUE THREAD

**Issue by drico** [react-hook-form/react-hook-form#12448]
### Version Number

7.53.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/shy-dust-s36pp3

### Steps to reproduce

Focus the field, write a character, unfocus the field.
You'll see in the logs that there is no log for "focus" / "blur" events. Only "change" event triggers the watcher

### Expected behaviour

The watcher callback should also be triggered on focus/blur with appropriate EventType.
Currently, only the "change" EventType triggers the watcher

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
only `change` event at the moment. it's expected.
