### ISSUE TITLE
issue: Calling remove of useFieldArray does not set correct default value when disabled is false in useForm

### ISSUE THREAD

**Issue by thomas-saueressig** [react-hook-form/react-hook-form#12457]
### Version Number

7.45.4

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-bug-forked-nmq5f2

### Steps to reproduce

Follow the steps below in the provided codesandbox. The form is using `useFieldArray` with a default value that has 2 items in it. Also, the `disabled` option in `useForm` is set to `false`. The code is a slighty modified version of the [useFieldArray example (FOCUS NAME/INDEX)](https://react-hook-form.com/docs/usefieldarray) of the docs. I have added a delete button and set the disabled option.

1. Delete the second item by clicking the "delete" button next to it
2. Add a second item by clicking "append"
3. Second item is pre-filled with value "2"

Alternatively
1. Add an item at the top of the list by clicking "prepend"
2. The newly added item is pre-filled with value "1"

Now change the `disabled` value from `false` to `undefined` and everything works as expected.

### Expected behaviour

When the `disabled` option of useForm is `false`, is should behave the same as when it is `undefined`:

1. Delete the second item by clicking the "delete" button next to it
2. Add a second item by clicking "append"
3. Second item is **not** pre-filled

Alternatively
1. Add an item at the top of the list by clicking "prepend"
2. The newly added item is **not** pre-filled

When using `undefined` instead of `false`, everything works as expected.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
fixed in the latest
