### ISSUE TITLE
issue: `isSubmitted` is reset when `values` are changed

### ISSUE THREAD

**Issue by pgsandstrom** [react-hook-form/react-hook-form#12450]
### Version Number

7.53.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/elated-elgamal-shhrqw?workspaceId=137e9b7f-aa8c-45a4-8adc-d339ddab01a9

### Steps to reproduce

1. Click "submit"
2. Notice how "is submitted" is set to yes
3. Click "change values"
4. Notice how "is submitted" is set to no
5. Even weirder, repeating the steps without refreshing will NOT result in the same reset happening.

### Expected behaviour

Documentation for "isSubmitted" reads as following:

> Set to true after the form is submitted. Will remain true until the reset method is invoked.

But it seems to reset more often.

https://react-hook-form.com/docs/useform/formstate

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
```
// options to config the behaviour
// eg: I want to keep user interacted/dirty value and not remove any user errors
useForm({
  values,
  resetOptions: {
    keepDirtyValues: true, // user-interacted input will be retained
    keepErrors: true, // input errors will be retained with value update
    keepIsSubmitted: true
  },
})
```

https://react-hook-form.com/docs/useform#resetOptions

you can leverage the resetOptions props

**Comment by pgsandstrom** [comment]
But what is it that actually happens in this scenario? Is the form "reset" when values change? I cant find a good explanation in the documentation.
