### ISSUE TITLE
Optimizing form reset

### ISSUE THREAD

**Issue by aqeelat** [react-hook-form/react-hook-form#12454]
https://github.com/react-hook-form/react-hook-form/blob/5db95c93b701ec98ec43ffd8b04efe8016b928dd/src/logic/createFormControl.ts#L1256-L1259
This section can be optimized to:
```   
    const values = isEmptyObject(formValues) ? _defaultValues : cloneObject(formValues);
```
The current version stores a bunch of consts that might not be used.

I can open a PR for this change.

**Comment by bluebill1049** [comment]
sounds good, PR welcome.
