### ISSUE TITLE
Why require a separate `keyName` rather than use provided `id`?

### ISSUE THREAD

**Issue by AndrewSouthpaw** [react-hook-form/react-hook-form#1245]
This question relates to #964 ...

@bluebill1049 can you say more about the reasoning for setting a different `keyName` rather than using the existing `id` if provided? It seems reasonable to assume that the `id` would be unique, and if that's the case then why use a separate generated key at all?

I imagine there's some inner workings of the library that I'm not understanding, so I thought I'd check in. It seems like a leaky abstraction to require knowledge that `useFieldArray` will overwrite `id` in your data.

Thoughts?

(Also, love the library BTW, great work so far. I'm hoping to be able to adopt it within our team as we ramp up the use of React forms instead of Rails forms. Turns out react-hook-form perfectly fits the bill of reducing all the clutter of event handlers. Thank you! 🙏 )

**Comment by bluebill1049** [comment]
aha, I forgot to updated the docs! my bad...

we have a new prop called `KeyName` which you can rename `id` to other stuff if `id` was used for your submit.

`id` is really a unique id for `key` attribute, bcause there are cases when user use `id` as actual field name, hence introduced `keyName` to enabled rename.

```
{
  control,
  name,
  keyName = 'id' as KeyName,
}
```

```
useFieldArray({
  control,
  name: 'test',
  keyName: 'bill',
})

{fields.map(field => <div key={field.bill} />)}
```

**Comment by bluebill1049** [comment]
doc is updated.

**Comment by bluebill1049** [comment]
going to close this issue, feel free to follow up with more questions.

**Comment by AndrewSouthpaw** [comment]
Hi @bluebill1049 , thanks for the response.

I'm familiar with the option for `keyName`. My question is this: why overwrite the `id` attribute in the first place?

It seems reasonable to use a provided `id` if there is one. It could be stated as an invariant that the `id` attribute if provided is expected to be unique. That way, the code reads much more naturally.

As it stays, I have to use this `keyName` attribute in order to divert the generated key into a useless place, since the id on my data works perfectly well.

**Comment by bluebill1049** [comment]
hey @AndrewSouthpaw for uncontrolled inputs, RHF will need unique id(key) for each input/div/row, hence the `id` was introduced and later on i realise that it will overwrite or ignore user's actual input field which named as `id` and hence introduced the `keyName`. hopefully this answers your question, it's always bit tricky to explain offline. let me know if this answers your question.

**Comment by AndrewSouthpaw** [comment]
Not quite. I've put together a PR to make my suggestion more concrete. I hope it's helpful. 😄

**Comment by bluebill1049** [comment]
oh cool thanks I will take a look there. thanks @AndrewSouthpaw
