### ISSUE TITLE
issue: Object with numerics keys are transofmed into array

### ISSUE THREAD

**Issue by mbaumanndev** [react-hook-form/react-hook-form#12465]
### Version Number

7.54.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/eloquent-margulis-6rnth9?workspaceId=ws_DqR43QvHXgiX1tm2hnvQLz

### Steps to reproduce

1. Go to the code sandbox
2. Fill the fields
3. Submit the form
4. The logged value is an array instead of an object

### Expected behaviour

When providing object with numeric keys, the form submit should preserve the object and not transform it to an array.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we use the index number to convert into array.

https://react-hook-form.com/docs/useform/register

> To produce an array of fields, input names should be followed by a dot and number. For example: test.0.data

**Comment by mbaumanndev** [comment]
It cannot be considered to be part of a v8 ?
