### ISSUE TITLE
issue: setValue triggers rerender of components that should be rerendered

### ISSUE THREAD

**Issue by layerok** [react-hook-form/react-hook-form#12479]
### Version Number

7.54.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/ecstatic-wind-cd8j4f?workspaceId=ws_AMJMMM2hbHEp4ig5KUDLRD

### Steps to reproduce

1. Go to sandbox
2. Click on 'reset' button
3. Open console
4. Type anything in any input inside the form
5. See in the console that `Description` and `Title` component rerendered, when only one component should be rerendered, either `Description` or `Title`

I don't know why, but this bug only happens if there is DevTool component on a page. If I remove `DevTool`, then this bug doesn't occur.

### Expected behaviour

setValue should trigger update only of components that watch for field value that was updated. Adding `DevTool` component on page shouldn't change this behaviour

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
expected render caused by the devtool

**Comment by layerok** [comment]
I don't understand why everything works as expected before resetting the form. There are no unnecessary rerenders. After resetting the form `setValue` triggers rerender of the whole form. Something seems wrong here.

https://github.com/user-attachments/assets/1a0ea0d2-b1ff-4645-8481-77ba65f359d8

**Comment by layerok** [comment]
And what is interesting. Editing value of the input that was registered using `register` method fixes the bug. `Sorting` is such a field in the video below.

https://github.com/user-attachments/assets/d7a284ca-5a92-41f9-bdf6-11b10ea2e8cc

**Comment by layerok** [comment]
I think this bug is significant because it causes the application to behave differently in development mode vs production mode

**Comment by layerok** [comment]
I simplified example even more. if I remove proxyToObject inside useExportControlToExtension then the bug doesn't occur

<img width="506" alt="image" src="https://github.com/user-attachments/assets/4ebd569d-6e51-4ef2-a0ac-b4940ce6507d" />
