### ISSUE TITLE
issue: First input field using Controller is not registered correctly when shouldUnregister is true in react 19

### ISSUE THREAD

**Issue by steoiv** [react-hook-form/react-hook-form#12478]
### Version Number

7.54.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/lingering-mountain-c5d8w8

### Steps to reproduce

1. Go to [Codesandbox example](https://codesandbox.io/p/sandbox/lingering-mountain-c5d8w8)
2. Click on heading "Form bug"
3. Tab into the first input field. Start typing. This shows the error: the value of the field is not updated
4. Tab to the next field. Type something. This field is updated.
5. Submit the form. The first field is not included in the data, even though it is set to required

Here is a screen recording that shows the bug:
https://github.com/user-attachments/assets/2d10e444-b9bf-4bfb-a2cc-416ccd6057be

The error disappears if shouldUnregister is set to false.

This error is not present when using react 18. Codesandbox with the same example as above, using react 18:
https://codesandbox.io/p/sandbox/thirsty-stitch-rdpm33?workspaceId=ws_3PPsxDcrfcTpU3S2y8TuKY

### Expected behaviour

Both fields should be registered and updated.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Not a prod bug, only due to strict mode.
