### ISSUE TITLE
👓 Provide more Controller examples

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#1247]
Hi Guys,

It's good to receive feedback from the community as the `Controller` needs more examples. Here is the list I got. please contribute if you have more examples to add.

Please fork this codesandbox and include your example.
https://codesandbox.io/s/react-hook-form-controller-079xx

- [x] MUI
- [x] React-Select
- [x] react-datepicker

**Comment by bluebill1049** [comment]
I am closing this issue, but it's pinned on the issues page.

**Comment by nigelthinksprint** [comment]
I cannot express how useful those examples are for controlled MUI examples especially the slider.

**Comment by bluebill1049** [comment]
Glad it helped! @nigelthinksprint feel free to suggest others or add more if you can :)

**Comment by nigelthinksprint** [comment]
https://codesandbox.io/s/react-hook-form-controller-ue527 added multiple select. Quite obvious but missing :)

**Comment by bluebill1049** [comment]
Thanks @nigelthinksprint 👍

**Comment by keemor** [comment]
Added Checkbox with FormControlLabel

https://codesandbox.io/s/react-hook-form-controller-sudii

**Comment by bluebill1049** [comment]
Thanks @keemor

**Comment by Leocete** [comment]
@bluebill1049, as I understood it is obligatory to set a `defaultValue` in the Controlled MUI Autocomplete component. 
Why it can't be set to an empty object? I want `defaultValue` to be nothing at the beginning, so the user can choose what  they want to select.
A link to the sandbox: https://codesandbox.io/s/react-hook-form-controller-fdmry?fontsize=14&hidenavigation=1&theme=dark

**Comment by bluebill1049** [comment]
> https://codesandbox.io/s/react-hook-form-controller-fdmry?fontsize=14&hidenavigation=1&theme=dark

you can supply empty object except `undefined`
