### ISSUE TITLE
Enable declarationMap: true in tsconfig when publish build

### ISSUE THREAD

**Issue by sisisin** [react-hook-form/react-hook-form#1250]
Sometime I want to refer to library's implementation.

Now, react-hook-form has only `.d.ts` files. So I need to look for implementation in source code.

If enable `declarationMap: true`, TypeScript generates a sourcemap for each corresponding `.d.ts` file.
This makes happy me when source code reading

**Comment by bluebill1049** [comment]
> This makes happy me when source code reading

LOL, we will make you happy then. you want to send a PR for this?

**Comment by bluebill1049** [comment]
FYI @kotarella1110 you have any objection?

**Comment by kotarella1110** [comment]
i have no objection 👍👍👍

**Comment by bluebill1049** [comment]
I am going to close this issue, and leave the PR running for upvotes from the community: https://github.com/react-hook-form/react-hook-form/pull/1253
