### ISSUE TITLE
Allow for different error type or cast the error type from validationResolver 

### ISSUE THREAD

**Issue by morawskiOZ** [react-hook-form/react-hook-form#1252]
**Is your feature request related to a problem? Please describe.**
I want to use a more complicated error interface than just `{ message: string }`. In my example it is 
```
message: {
  key: string
}
```
I need it to be explicit for other developers that it is in fact a key that needs to be transformed in a message (i18n).

**Describe the solution you'd like**
Either allow to pass another interface than `FormData` or cast the type from `validationResolver` error return value type.

**Describe alternatives you've considered**
Using a simple structure of errors with just string

What do you think? Doable, worth effort? How hard on scale 1-10, so I know if I can help with PR.

**Comment by bluebill1049** [comment]
is it possible to bake your error message inside the `validationResolver` depend on lang?

**Comment by morawskiOZ** [comment]
> is it possible to bake your error message inside the `validationResolver` depend on lang?

Thanks for your replay. Good idea and I gave it a try but the problem is that we use the same validation logic and interfaces (I don't want it to diverge) on the server-side where I don't have access to i18n functionality and always have to return the key for FE to read and translate.  For now, I will simplify the interface to just
`message:  string`

It is hard for me to say is this feature really needed or our project is the only one which would benefit from it and therefore not worth the effort. Please decide and close it if needed.

**Comment by bluebill1049** [comment]
> It is hard for me to say is this feature really needed or our project is the only one which would benefit from it and therefore not worth the effort. Please decide and close it if needed.

thanks for understanding, I will close this issue for now and add this feature request to our backlog anyhow.
