### ISSUE TITLE
Controller with react-input-mask

### ISSUE THREAD

**Issue by jonatasfl** [react-hook-form/react-hook-form#1255]
**Describe the question?**
When I use react-input-mask component inside a Controller, the **defaultValue** doesn't work after an API call to fill the masked input. All other input works fine.

Also when I type into masked input, I see this message on console:

> Warning: A component is changing an uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component.

**To Reproduce**
1. Go to [https://codesandbox.io/s/react-hook-form-with-inputmask-o5nd8](https://codesandbox.io/s/react-hook-form-with-inputmask-o5nd8)
2. Click on 'Console'
3. Type numbers in the last input

**Codesandbox link (Required)**
[https://codesandbox.io/s/react-hook-form-with-inputmask-o5nd8](https://codesandbox.io/s/react-hook-form-with-inputmask-o5nd8)

**Additional context**
I've tried with react-text-mask too and same occurs

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-with-inputmask-d4fvd

**Comment by jonatasfl** [comment]
@bluebill1049 It`s work! Thank you so much!

**Comment by sprayone** [comment]
Please, help me. Sorry for my english.
I'm trying use react-hook-form with Input mask, but, without sucess.

<Controller
                                                    as={InputMask}
                                                    control={control}
                                                    className="form-control"
                                                    id="cpf"
                                                    maxLength="11"
                                                    value={cpf}
                                                    placeholder=""
                                                    name="cpf"
                                                    mask="999.999.999-99"
                                                    alwaysShowMask
                                                    ref={register({
                                                        required: "Entre com seu CPF",
                                                        pattern: {
                                                            value: /\d{3}\d{3}\d{3}\d{2}$/i,
                                                            message: "Entre com um CPF válido",
                                                        }
                                                    })}
                                                    onChange={e => setCpf(e.target.value)}
                                                    
                                            />
                                            <label for="cpf">CPF*</label>
                                            {errors.cpf && <p className="error">{errors.cpf.message}</p>}

**Comment by bluebill1049** [comment]
Take a look at the doc, there are codesadnboxes for v5 and v6 which have mask input. (Controller section)

**Comment by meshellun** [comment]
![image](https://user-images.githubusercontent.com/51411780/88931113-06ae9280-d242-11ea-859a-dc34f3aa1065.png)
Hi Looking at the codesandbox example linked in this issue, there seems to be a Warning when using a InputMask with a Controller. Is there a way to overcome that warning?

**Comment by bluebill1049** [comment]
@meshellun why those defaultValue been comment out?

**Comment by meshellun** [comment]
@bluebill1049  Oh! That was in this example ttps://codesandbox.io/s/react-hook-form-with-inputmask-d4fvd before I even touched it. I believe the defaultValue was commented out so that the placeholder for InputMask shows up like 000.000-000-00, but that should be an easy fix moving forward. (Setting defaultValue to what we want the placeholder to be). Thanks! 
![image](https://user-images.githubusercontent.com/51411780/89038213-89e4ec80-d305-11ea-8d6f-c712cb157d0f.png)

**Comment by Nemmo** [comment]
Hi folks, @bluebill1049 

How can I set up input mask with an array of masks?

**Comment by bluebill1049** [comment]
> @bluebill1049 Oh! That was in this example ttps://codesandbox.io/s/react-hook-form-with-inputmask-d4fvd before I even touched it. I believe the defaultValue was commented out so that the placeholder for InputMask shows up like 000.000-000-00, but that should be an easy fix moving forward. (Setting defaultValue to what we want the placeholder to be). Thanks!
> ![image](https://user-images.githubusercontent.com/51411780/89038213-89e4ec80-d305-11ea-8d6f-c712cb157d0f.png)

have you seen this example: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r

**Comment by bluebill1049** [comment]
> Hi folks, @bluebill1049
> 
> How can I set up input mask with an array of masks?

useFieldArray?

**Comment by shoxton** [comment]
In case anyone else had issues on reseting fields with react-input-mask, you just need to add a `defaultValue=""` prop to `<Controller />`
