### ISSUE TITLE
Missing documentation for FormContext

### ISSUE THREAD

**Issue by javidjamae** [react-hook-form/react-hook-form#1257]
**Describe the bug**
Several places in the documentation link to `FormContext` using the URL `https://react-hook-form.com/api/#FormContext`, but there is no anchor or section in the API documentation for FormContext. 

**To Reproduce**
1. Go to `https://react-hook-form.com/api/#FormContext`
2. The API docs load and the page remains at the top as no anchor or section with an id of `FormContext` exists.

**Codesandbox link (Required)**
N/A

**Expected behavior**
Add a section to the documentation that describes what FormContext is and how it works. Looking around in the getting started and API docs, there are quite a few references to `FormContext` but nothing that explains the basic principles of what it is and how it works. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**

**Comment by bluebill1049** [comment]
thanks. fixed.
