### ISSUE TITLE
Missing FormContext warning

### ISSUE THREAD

**Issue by sorxrob** [react-hook-form/react-hook-form#1261]
Hello, I am using ionic with react and I am getting `Missing FormContext` every time I type in any input.

1. Just type anything in the email field in the sandbox provided

https://codesandbox.io/s/ionic-react-list-eiekh

![Screen Shot 2020-03-22 at 1 54 44 PM](https://user-images.githubusercontent.com/13049130/77243424-ceb89280-6c44-11ea-8a88-f6f56d1b46a5.png)

 - OS: Catalina
 - Browser: Chrome
 - Version: 80.0.3987.149

**Comment by bluebill1049** [comment]
@kotarella1110 that's what i was referred to.  remember that commit.

**Comment by bluebill1049** [comment]
i will remove this warning completely for now until we have a good solution for this. i will add a task into the project todo column as well.

**Comment by bluebill1049** [comment]
thanks @sorxrob i will release a patch in a sec.

**Comment by sorxrob** [comment]
Thanks! That was fast.

**Comment by kotarella1110** [comment]
@bluebill1049 Sorry. My fix was wrong.
This should call `useFormContext` only if the `control` prop was not passed to the `Controller` component.
I can fix this right away.

**Comment by bluebill1049** [comment]
no worries at all @kotarella1110 take your time with it. we can release the fix next weekend.

**Comment by kotarella1110** [comment]
Thanks. I create a PR to fix this tonight.

**Comment by kotarella1110** [comment]
I tried to fix this, but it seems difficult to fix due to the [rules of Hooks](https://reactjs.org/docs/hooks-rules.html).

<img width="761" alt="スクリーンショット 2020-03-22 21 34 32" src="https://user-images.githubusercontent.com/12913947/77249916-ce8db680-6c87-11ea-9988-d1422227323a.png">

**Comment by bluebill1049** [comment]
yes correct @kotarella1110 let's park this for now :)

**Comment by colin-h** [comment]
+1 here. Also seeing lots of warnings even though I am passing control to `useFieldArray`.

```javascript
 const { fields, append, remove } = useFieldArray({
    control,
    name,
  })
```

![Screen Shot 2020-07-02 at 11 21 47 AM](https://user-images.githubusercontent.com/5582627/86385671-3de74f00-bc56-11ea-9457-747e0becf174.png)

**Comment by bluebill1049** [comment]
> +1 here. Also seeing lots of warnings even though I am passing control to `useFieldArray`.
> 
> ```js
>  const { fields, append, remove } = useFieldArray({
>     control,
>     name,
>   })
> ```
> 
> ![Screen Shot 2020-07-02 at 11 21 47 AM](https://user-images.githubusercontent.com/5582627/86385671-3de74f00-bc56-11ea-9457-747e0becf174.png)

which version? and need a codesandbox to reproduce te problem too.
