### ISSUE TITLE
Changing radio options dynamically leads to exception

### ISSUE THREAD

**Issue by raulfelix** [react-hook-form/react-hook-form#1262]
**Describe the bug**

**To Reproduce**
1. Go to https://codesandbox.io/s/boring-rhodes-14pu2
2. Change the dropdown 3 times
3. You will see exception
4. Looks like the issue relates to a dynamic list of radio options.

**Codesandbox link (Required)**
https://codesandbox.io/s/boring-rhodes-14pu2

**Expected behavior**
No exception

**Desktop (please complete the following information):**
 - OS: mac OS
 - Browsers: All (but found in chrome)

**Comment by bluebill1049** [comment]
thanks @raulfelix will investigate on this issue.

**Comment by bluebill1049** [comment]
The fix will be released in the next patch. thanks
