### ISSUE TITLE
get data from submit?

### ISSUE THREAD

**Issue by kiansenggoh** [react-hook-form/react-hook-form#1264]
hi

scenario here: 
when user submit a form. it go thru Yup validation.
possible to get data similar to handleSubmit without validation?

because i want to allow user to save draft. so save draft can have incomplete form.

i tried to use getValues() and watch. but the data return is flat. 

any idea how where can i get the data?

**Comment by bluebill1049** [comment]
please follow the template to provide a CSB, this should work with `watch`

**Comment by kiansenggoh** [comment]
i am sorry what is CSB?
got example?

**Comment by kiansenggoh** [comment]
i got it,

watch({
            nest: true
        })
