### ISSUE TITLE
Bug then ant update new versio, Can't detect Radio Group change

### ISSUE THREAD

**Issue by hieusmiths** [react-hook-form/react-hook-form#1265]
**Describe the bug**

**To Reproduce**

Bug appear then Antdesign release new version.
When me using Radio Group then submit data return Event attributes of radio group.

I fixed it by this way

           <Controller
              control={control}
              as={
                <Radio.Group>
                  <Radio value={1}>A</Radio>
                  <Radio value={2}>B</Radio>
                  <Radio value={3}>C</Radio>
                  <Radio value={4}>D</Radio>
                </Radio.Group>
              }
              name="RadioGroup"
              onChange={([e]) => {
                console.log(e.target.value)
                return e.target.value;
              }}
            />
Thank so much.

**Comment by bluebill1049** [comment]
@hieusmiths so you find the solution for the problem. do you still need my help?

**Comment by bluebill1049** [comment]
I guess you are trying to help by sharing example here. so thank you :)

**Comment by flycj** [comment]
I also encountered this problem, how do you solve it? @hieusmiths

**Comment by vytcus** [comment]
I'm having similar problems with connecting ant design Radio.Group to RHF. Tried it with registering as uncontrolled components.
Here's the CodeSandbox: [https://codesandbox.io/s/eager-lake-csw3r?file=/src/App.tsx](url)

**Comment by bluebill1049** [comment]
> https://codesandbox.io/s/eager-lake-csw3r?file=/src/App.tsx

@vytcus use render props instead of as, assign those prop value.

**Comment by vytcus** [comment]
Could you maybe try editing the example I sent? I tried using render props in the sandbox and it still isn't working :/
Maybe I'm connecting it wrong?
