### ISSUE TITLE
Allow React components to be returned as `validate` rule error message

### ISSUE THREAD

**Issue by starmatt** [react-hook-form/react-hook-form#1266]
Hello,

**Is your feature request related to a problem? Please describe.**
My issue is that the `validate` method only allows to return a `bool` or a `string`, and returning a React component will not validate as an error. Being able to set a React component as an error message would allow for more complex and useful (UI-wise) error handling.
As an example, consider a password input with a dynamic rule checking for its constraints (required characters, length, etc.). The `validate` method works very well with this kind of complex rule checks, but I would also like to be able to give instant feedback as the user types a password, via a react component instead of a string.

I would also like to point out that setting a component as an error message in the other validation methods works (I tried with `pattern`) (
```js
register({
    pattern({
        value: /regex/,
        message: component
    }),
})
```
).

**Describe the solution you'd like**
I'd like the `validate` method to accept a React component as a possible return type, to be handled as a message error. 

**Describe alternatives you've considered**
None.

**Additional context**
To give you a more concrete example, here is a condensed snippet of what I am trying to do:

```js
register({
    validate: customValidate, 
})
```

```js
customValidate: value => {
    const constraints = {
        hasMinLen: value.length >= 8,
        hasUppercase: /([A-Z]+)/.test(value),
        hasLowercase: /([a-z]+)/.test(value),
        hasNumber: /([0-9]+)/.test(value),
    };

     return (
         Object.values(constraints).every(constraint => constraint) || (
            <span>
                Le mot de passe doit contenir au moins:
                <div className="tags">
                    {!constraints.hasMinLen && (
                        <span className="tag is-danger">8 caractères</span>
                    )}
                    {!constraints.hasLowercase && (
                        <span className="tag is-danger">1 minuscule</span>
                    )}
                    {!constraints.hasUppercase && (
                        <span className="tag is-danger">1 majuscule</span>
                    )}
                    {!constraints.hasNumber && (
                        <span className="tag is-danger">1 chiffre</span>
                    )}
                </div>
            </span>
         )
    );
}
```

Thank you very much for your attention!

**Comment by bluebill1049** [comment]
I think you are referring to this component: https://react-hook-form.com/api#ErrorMessage

**Comment by starmatt** [comment]
Hello, thanks for your answer!

I've already checked this component out but it's really not what I'm looking for, I already have an error component used to render the react-hook-form error messages, and it doesn't help with the `validate` function not behaving like the other validation functions. I still wouldn't be able to a associate a specific React component when I need to for specific rules.

Sorry if I'm not being quite clear. Please tell me if you need more informations.

**Comment by bluebill1049** [comment]
thanks @starmatt for the clarification. however, at the stage, we don't plan to support JSX for the message unless there are more demands from the community. I will tag it as waiting for votes.

**Comment by starmatt** [comment]
That's fine, thanks.

Although, as I said before, it's already possible to set JSX in the `message` key of the object returned by  `maxLength`, `pattern`, etc, except for `validate` (I understand, to be fair, that it doesn't work exactly like the other ones). So you do support it to an extent even if it's not intentional ;)

Stay safe and have a good day.

**Comment by bluebill1049** [comment]
oh really? @starmatt can you provide an example. it's not intentional for sure. however, if that's the case, it may as well as make it consistent.

**Comment by starmatt** [comment]
Here's a codebox example: https://codesandbox.io/s/nervous-khayyam-r6i40
I took time to test all the functions, and it works with JSX only for functions that return a `value/message` object.

**Comment by kotarella1110** [comment]
Haha. this is interesting behavior 👀

@starmatt There is something I want to confirm.

> I still wouldn't be able to a associate a specific React component when I need to for specific rules.

In what cases can this be considered?
You can wrap the ErrorMessage component using `as` prop.

**Comment by starmatt** [comment]
True, but I already have my own error rendering component built into my input components, and using yours still wouldn't allow me to do something like the example in my first post 🙂

**Comment by kotarella1110** [comment]
@starmatt How about this?

```ts
register({
  validate: {
    hasMinLen: value => value.length >= 8 || "8 caractères",
    hasUppercase: value => /([A-Z]+)/.test(value) || "1 minuscule",
    hasLowercase: value => /([a-z]+)/.test(value) || "1 majuscule",
    hasNumber: value => /([0-9]+)/.test(value) || "1 chiffre"
  }
})
```

```ts
<ErrorMessage name="test" errors={errors}>
  {({ messages }) =>
    messages && (
      <span>
        Le mot de passe doit contenir au moins:
        <div className="tags">
          {Object.entries(messages).map(([type, message]) => (
            <span key={type} className="tag is-danger">
              {message}
            </span>
          ))}
        </div>
      </span>
    )
  }
</ErrorMessage>
```

codesandbox: https://codesandbox.io/s/react-hook-form-issue-1266-9t2z4

**Comment by kotarella1110** [comment]
@bluebill1049 Why did you remove the vote waiting tag? Should we support this feature?

**Comment by bluebill1049** [comment]
@kotarella1110 I think we don't need vote for this one anymore. we should support it due to consistency. I didn't want to remove JSX due to existing functionality because it will be a breaking change.

**Comment by bluebill1049** [comment]
are you interested to take on this one? @kotarella1110 otherwise i will be looking into this over the weekend. I don't think we are in rush w

**Comment by kotarella1110** [comment]
@bluebill1049 I will try this! Thanks 👍

**Comment by bluebill1049** [comment]
FYI `validateField.ts` is the one you want to take a look at.

**Comment by starmatt** [comment]
That was quick! Thanks a lot @kotarella1110 and @bluebill1049 

I'm eager to use this in my app, how can I pull this version via `yarn` or `npm`? I tried upgrading the package (I'm on `5.1.3`), but I don't seem to be able to use the feature. Or should I wait for you to update the package with a new version?

Thanks again!

**Comment by kotarella1110** [comment]
@starmatt This feature is not yet released. Perhaps it will be released by a few days.

**Comment by starmatt** [comment]
That's what I thought, thanks for your work and understanding!
