### ISSUE TITLE
DX with useFieldArray in terms of defaultValue/defaultValues

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#1267]
Original issue can be found here https://github.com/react-hook-form/react-hook-form/issues/1254#issuecomment-602154995_

The discovery is the following,

**Problem**

- remove item from Array Field will result staled value in the input (if `defaultValue` is not supplied at native input / `Controller`)
- the problem is due to when `defaultValue` not supplied, `defaultValues` from `useForm` will `register` value into the input.

here is a reproduce-able CSB from @xiaoyu-tamu 

> I add an **age field** and **change input to `<Controller />`**. Please notice, the bug only occur when **age field** not have **defaultValue**.

To reproduce, 
1. Append new row
2. remove second row (useFieldArray2)

The new row have age 2 (staled value)

https://codesandbox.io/s/react-hook-form-usefieldarray-3-ix34q

**Suggestion:**

1) maybe we should mutate the `defaultValues` after form finish renders `input` & `value`. The only problem is when you want to reset the form, you will probably have to supply `defaultValues` (eg: `reset({ test: 'test' })`), because the `defaultValues` will be mutated by the time. Honestly, i think that would probably be a better DX than asking the user to supply `defaultValue`. Cons: mutate `defaultValues` is not the best.

2) always ask the user to supply defaultValue when working with `useFieldArray`. This is actually applied to native input as well. 

let me know what you think. 🤔another suggestion welcome as well.

FYI: @JeromeDeLeon @kotarella1110 @stramel

_Originally posted by @bluebill1049 in https://github.com/react-hook-form/react-hook-form/issues/1254#issuecomment-602154995_

**Comment by bluebill1049** [comment]
@kotarella1110 @JeromeDeLeon @stramel can you guys kindly give your opinion about this?

**Comment by JeromeDeLeon** [comment]
I'm getting accustomed on using `defaultValue` for every input and for many users, a sudden shift would cost them to change the `reset` in case they didn't supply the `defaultValue`; however, I agree with you that using `reset` makes it great DX because default value use case is for default value only if that makes sense.

**Comment by JeromeDeLeon** [comment]
Are there any implications for mutating `defaultValue` aside from `reset`?

**Comment by bluebill1049** [comment]
> Are there any implications for mutating `defaultValue` aside from `reset`?

Thanks for your feedback :) as right now, we can only mutate defaultValues via `reset`.

**Comment by JeromeDeLeon** [comment]
Thanks for also doing this amid of this crisis. ☺️ Take Care 😇

**Comment by bluebill1049** [comment]
> I'm getting accustomed on using `defaultValue` for every input and for many users, a sudden shift would cost them to change the `reset` in case they didn't supply the `defaultValue`; however, I agree with you that using `reset` makes it great DX because default value use case is for default value only if that makes sense.

Yea, i do worry about mutate the `defaultValues` when user delete rows. We can also deep clone a copy of the defaultValues and kept two of them, but then things get more complicated to maintain. so maybe enforce user to provide default value is a better solution here.

**Comment by JeromeDeLeon** [comment]
Things get too complicated then. I suggest we stick with enforcing `defaultValue` as to avoid changing too much of the use case of this lib.

**Comment by kotarella1110** [comment]
@bluebill1049 Isn't this solved by using the [`delete` operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete) to delete `fields` array value along with the array index?

**Comment by bluebill1049** [comment]
@kotarella1110 the problem is when a new item gets mounted (delete row and add it back), the `defaultValues` in useForm will register input with `defaultValue`. we actually don't manipulate `defaultValues.

**Comment by bluebill1049** [comment]
<img width="720" alt="Screen Shot 2020-03-25 at 12 22 59 pm" src="https://user-images.githubusercontent.com/10513364/77491981-6a3f4280-6e93-11ea-90d5-87c70884dd91.png">

Looks like we already mention that in the doc, maybe need to emphasis it better.

**Comment by bluebill1049** [comment]
I think i will include reset inside the useFiledArray example, this should make things a bit more clearer for everyone.

**Comment by bluebill1049** [comment]
going to close this discussion: 

1. the doc does mention the default value
2. I have update the code example to include both Controller and Native input with reset

**Comment by bluebill1049** [comment]
thank you @JeromeDeLeon & @kotarella1110 's input.
