### ISSUE TITLE
react hooks form with custom input first removes error and then we can type

### ISSUE THREAD

**Issue by Atiqullah-Naemi** [react-hook-form/react-hook-form#1270]
when the form field shows error message and I want to try to type, when it reaches the point to clear the    error first it clear the error and then I am able to type.
please check this [sandbox](https://codesandbox.io/s/boring-violet-e4l25), click inside a field and then click outside it to produce the error and now try to type something for example (**1111**), the problem is that you have to press 1 six times to achieve **1111**, I couldn't find how to solve it.
any help please?

**Comment by bluebill1049** [comment]
I am not clear on what i can help in here, can you explain a bit more? also you are using an old version of RHF too.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/faqs#Whyisfirstkeystrokeisnotworking 

i think this is what you after.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/romantic-pasteur-kckjz
