### ISSUE TITLE
React hook form return object when use onChange custom library

### ISSUE THREAD

**Issue by hieusmiths** [react-hook-form/react-hook-form#1271]
**Describe the bug**

**To Reproduce**
 I'm using React HF, normal i using by this way:

    <Controller
        as={TextField}
        name="firstName"
        control={control}
        defaultValue=""
      />
Okey it's work.

But then Ant update all component use with additional onChange with Controller it return object.
Select and Input, Radio faile

Thanks team, keep hard working.

I still code bug util update of React Hook Form.

**Comment by bluebill1049** [comment]
hey @hieusmiths do you have a codesandbox for this?

**Comment by hieusmiths** [comment]
Sorry, i checked code demo and fix it by example.
But i remember it working, Magic :).
Thank so  much

**Comment by bluebill1049** [comment]
aha all good :)
