### ISSUE TITLE
"TypeError: Destructured parameter is undefined" caused by holes (undefined values) in RHF's underlying options array for dynamically generated lists of radio buttons that change.

### ISSUE THREAD

**Issue by dwoodwardgb** [react-hook-form/react-hook-form#1274]
**Describe the bug**
"TypeError: Destructured parameter is undefined" caused by holes (undefined values) in RHF's underlying options array for dynamically generated lists of radio buttons that change.

**To Reproduce**
1. Go to the code sandbox link
2. Click on the "Toggle" button (this will change the dynamic list of radios being rendered)
4. See error, inspecting / debugging will reveal the "holes" in the options array that is being destructured by RHF.

**Codesandbox link (Required)**
https://codesandbox.io/s/bold-austin-kp9i8

**Expected behavior**
RHF should be able to handle dyanmic lists of radio buttons that change.

**Desktop (please complete the following information):**
 - OS: OSX Catalina
 - Browser: Firefox
 - Version 72.0.2

**Comment by bluebill1049** [comment]
thanks for reporting this issue. I have patched the problem: https://github.com/react-hook-form/react-hook-form/issues/1262 will release it soon.
