### ISSUE TITLE
Remove( number[] ) - doesn't remove every 3rd field.

### ISSUE THREAD

**Issue by MichaelCheglow** [react-hook-form/react-hook-form#1278]
**Describe the bug**
Remove( number[] ) - doesn't remove every 1 + 2n field.

**To Reproduce**
1. Click on button 'Remove all fields'
2. See that 3, 5, 7 and 9 fields have not been deleted. 

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-fb7k4

**Expected behavior**
2. See empty form without fields.

**Comment by bluebill1049** [comment]
thanks @MichaelCheglow looks like there is a bug with remove array of items.

**Comment by bluebill1049** [comment]
patched: https://codesandbox.io/s/react-hook-form-usefieldarray-tuw9s
