### ISSUE TITLE
use Watch() as invoke to server request function

### ISSUE THREAD

**Issue by ahmadkam2** [react-hook-form/react-hook-form#1280]
Im using react-hook-form to as a filter for showing list items.
It has multiple items and I do not want to use submit button to send my server request.
server request must sent after every change in form items data.
when I use Watch() to send server request in some items that have text inputs,
server request function invokes once for every input, but 
i want to send server request after onBlur inputs.
Am i in right way to using Watch in my project?
OR Watch usage is just for rendering options
Thank you

**Comment by kerosan** [comment]
you can use onChange with debounce https://codesandbox.io/s/usedebounce-v5gli

**Comment by bluebill1049** [comment]
Thanks @kerosan <3

**Comment by ahmadkam2** [comment]
Thanks for comment.
One of my problems solved debounce.
another problem is in initialization of form items and setting initial values for them.
In this case client send multiple server request.
I have six custom Select component (using controller), six input numbers and six checkboxes
in my form.
also watch triggered twice for checkbox action (one for press click button and second for releasing 
click button using mouse)
Can you help me to do this?
Thank you

**Comment by bluebill1049** [comment]
First of all, I would appreciate if you can follow the template of asking questions or reporting issue here. It helps me and you.

for initial values: take a look this section. https://react-hook-form.com/api#reset

**Comment by ahmadkam2** [comment]
Im confused to use watch OR onChange function to update my data from server on form data
changes, And Im start to hooks recently.
I start coding using watch and faced with this problems and ask this question to find out best way

**Comment by bluebill1049** [comment]
That's cool. follow the template next time: https://github.com/react-hook-form/react-hook-form/blob/master/.github/ISSUE_TEMPLATE/question.md so we can answer your question easier too.
