### ISSUE TITLE
Password and Confirm Password field validation using validationSchema

### ISSUE THREAD

**Issue by Vishal1419** [react-hook-form/react-hook-form#1282]
@bluebill1049 Can you show an example of password and confirm-password using validationSchema?

I am doing my validation like this:
```
const validationSchema = yup.object().shape({
    newPassword: yup.string()
      .required('New Password is required'),
    confirmPassword: yup.string()
      .required('Confirm Password is required')
      .oneOf([yup.ref('password'), null], 'Passwords does not match'),
  });
```
For this scenario, please fire validations **onChange** or **onBlur**.

At first sight, everything looks fine. But if you follow this order, then you can see problems:
1. Input "abcde" in newPassword field.
2. Input "abcdf" in confirmPassword field. (It will throw error: Passwords does not match)
3. Change newPassword to "abcdf"

Actual result: confirmPassword will still have errors.
Expected result from user perspective: confirmPassword should not have any error as of now.

Can you please check it?

**Comment by bluebill1049** [comment]
if you want the other field to be re-validated as well, you can use `triggerValidation`.

**Comment by Vishal1419** [comment]
@bluebill1049 Thank you for the quick response. I have called triggerValidation on onBlur as well as on onChange. That works perfectly. Thank you again.

**Comment by brunobraga95** [comment]
@Vishal1419 can you share a working example?

**Comment by Vishal1419** [comment]
@brunobraga95 Thanks for reaching out to me.

you can get triggerValidation from useForm like this:
```
const { triggerValidation } = useForm();
```

And then in your input you can trigger the validation on change like this:
```
<input
    ...some props...
    onChange={() => { triggerValidation('confirmPassword'); }}
/>
```

Please feel free to ask if you have any other problems. Thanks.
