### ISSUE TITLE
react hook form watch action multiple form checkboxs and select

### ISSUE THREAD

**Issue by ahmadkam2** [react-hook-form/react-hook-form#1283]
This is my question link in spectrum chat 

https://spectrum.chat/aqyol/general/react-form-hook-watch-invoke-multiple~9782e0aa-949f-40c7-b36c-a2b684c786b8

**Im using react form hook watch to send server request on form data changes
I have custom Select, input and checkboxes in my form.
when i click on checkbox, watch function invoke two times (one form press mouse click and other for releasing it)
and send two server requests.
also in custom selects, watch invokes server request when setting default values in select components,
How can i avoid this problem?**

**Comment by bluebill1049** [comment]
i will answer there.

**Comment by bluebill1049** [comment]
can you ask that question at react hook form specturm? one easy way to do it just attach onChange with debounce.
