### ISSUE TITLE
Validation schema library

### ISSUE THREAD

**Issue by devdpontes** [react-hook-form/react-hook-form#1284]
Are there any plans to add support for a different validation schema library, other than yup or joi?

The good thing about react-hook-form is no dependencies, but as soon as yup is added, it adds a load of lodash code to my bundle.

Any possibility of using something like superstruct with no dependencies and very small (4.5 kB gzipped)?

**Comment by bluebill1049** [comment]
yep totally agree. take a look this: https://react-hook-form.com/advanced-usage#CustomHookwithValidationResolver we already support any external validation schema.

**Comment by devdpontes** [comment]
Sorry, totally missed that in the docs. Thanks for the quick reply. Keep up the good work!
