### ISSUE TITLE
Avoid reset of default values after submit

### ISSUE THREAD

**Issue by emilium** [react-hook-form/react-hook-form#1285]
Is it possible to avoid reset of default values after submit?

Currently all fields are filled correctly by passing defaultValue, but right after submit everything is cleared and all inputs fields are empty. This is correct behaviour. But is it possible somehow to keep them.

`const { register, handleSubmit, control, errors} = useForm({  defaultValues: props.defaultValues });
  const onSubmit = data => {
    data.IsDefault = isDefault;
    formSubmit(data);
  }`

**Comment by bluebill1049** [comment]
please follow our temple for asking a question...

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/kw7z2q2n15 no we don't reset inputs.

**Comment by ingeniousambivert** [comment]
@emilium I have a similar problem. Did you manage to fix it?

**Comment by emilium** [comment]
@ingeniousambivert I decided to not use `useForm({ defaultValues: props.defaultValues }` but just a state from useContext to handle defaultValues.

**Comment by PyYoshi** [comment]
Try to set shouldUnregister=false in options. Maybe fix this problem.
https://react-hook-form.com/api#useForm

**Comment by mateosantosdev** [comment]
I have the same problem, setting shouldUnregister to _false_ is **not working**.

Any idea how to solve this ?

**Comment by bluebill1049** [comment]
> I have the same problem, setting shouldUnregister to _false_ is **not working**.
> 
> Any idea how to solve this ?

can you share a codesandbox?

**Comment by brennancheung** [comment]
Material-UI `TextField` seems to get cleared out each time I submit even with `shouldUnregister: false`.  This does not happen on plain HTML `input` fields.  I am not using a defaultValue for any of the fields.

**Comment by bluebill1049** [comment]
> Material-UI `TextField` seems to get cleared out each time I submit even with `shouldUnregister: false`. This does not happen on plain HTML `input` fields. I am not using a defaultValue for any of the fields.
> 
> Update: switching to `<Controller>` solved the problem.

yeah, stick with `Controller` with external controller input. We may have a custom hook come up for `Controller` as well: https://github.com/react-hook-form/react-hook-form/discussions/3487

**Comment by lastmaj** [comment]
@brennancheung I am facing the same issue, while working with Material-UI's `TextField`. I am using `<Controller>` with default values, and `shouldUnregister: false` did not solve my problem.
