### ISSUE TITLE
Type 'NestDataObject<T, FieldError> | undefined' is not assignable to type 'NestDataObject<T, FieldError>'

### ISSUE THREAD

**Issue by ziishaned** [react-hook-form/react-hook-form#1286]
**Codesandbox link (Required)**

https://codesandbox.io/s/ecstatic-currying-orynw

**Expected behavior**

`FieldErrors` typing should accept the interface without any errors.

**Comment by bluebill1049** [comment]
why not just keep thing simple: https://codesandbox.io/s/ecstatic-currying-orynw

**Comment by ziishaned** [comment]
> why not just keep thing simple: https://codesandbox.io/s/ecstatic-currying-orynw

@bluebill1049 can you please explain what do you mean by that because I am still getting the same error in your Codesandbox link

**Comment by bluebill1049** [comment]
shit i didn't save...

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/small-grass-1p798

**Comment by devme1** [comment]
@bluebill1049 correct me if I am wrong `FieldErrors` is a generic interface that accepts the interface of an object. By this, you will be able to access the `message` key on all the passed object items interface.

**Comment by devme1** [comment]
@bluebill1049 can you please tell me what will be the type of `userErrors` variable

```ts
import * as React from "react";
import { useForm, FieldErrors } from "react-hook-form";

interface IUser {
  lastName: string;
  firstName: string;
}

interface IForm {
  users: IUser[];
}

function App() {
  const { register, errors, handleSubmit } = useForm<IForm>();

  const { fields, append, remove } = useFieldArray();

  const onSubmit = (data: any) => {
    console.log(data);
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      {fields.map((field: IUser, index: number) => {
        const userErrors: FieldErrors<IUser> = errors?.users[index];

        return (
          <div key={index}>
            <input name={`users[${index}].firstName`} ref={register} />
            {userErrors.firstName && <p>{userErrors.firstName}</p>}
            <input name={`users[${index}].lastName`} ref={register} />
            {userErrors.lastName && <p>{userErrors.lastName}</p>}
          </div>
        );
      })}

      <button type="submit">Submit</button>
    </form>
  );
}

const rootElement = document.getElementById("root");
render(<App />, rootElement);
```

**Comment by bluebill1049** [comment]
@kotarella1110 you want to help on this one?

**Comment by kotarella1110** [comment]
@bluebill1049 I'll look into this 👍

**Comment by kotarella1110** [comment]
@ziishaned This isn't a bug. You should define the type as follows:

```ts
const inputErrors = errors.inputs;
// or
const inputErrors: FieldErrors<IInputs | undefined> = errors.inputs;
// or
const inputErrors: FieldErrors<IInputs> | undefined = errors.inputs;
```

**Comment by bluebill1049** [comment]
I think we can close this one. feel free to follow up with more questions.

**Comment by ziishaned** [comment]
@kotarella1110 I think it would be better to handle `undefined` inside `react-hook-form` typing

**Comment by kotarella1110** [comment]
@ziishaned `FieldErrors` is a type of [`errors`](https://react-hook-form.com/api/#errors) object.
The keys in the `errors` object would be `undefined`, but the `errors` object itself cannot be `undefined`.
If form is no error, the `errors` object will be `{}`.
