### ISSUE TITLE
useFieldArray with nested input component won't update

### ISSUE THREAD

**Issue by sirgwain** [react-hook-form/react-hook-form#1287]
**Describe the bug**
When using a FieldArray with <input/> components inside nested wrapper components, the field value does not update.

Am I missing some argument or concept to make my nested inputs work as expected?

```javascript

  // Some Wrapper component
  const InputWrapper = ({ index, item }) => {
    return (
      <input
        name={`test[${index}].name`}
        ref={register()}
        defaultValue={item.name}
      />
    );
  };

  return (
    <>
      <ul>
        {fields.map((item, index) => {
          return (
            <li key={item.id}>
              <InputWrapper item={item} index={index} />
              <button type="button" onClick={() => remove(index)}>
                Delete
              </button>
            </li>
          );
        })}
      </ul>
...
```

**To Reproduce**
1. Update "useFieldArray" text input to "use FieldArray updated"
2. Click submit
3. Observe that field is reset
4. Submit has the proper values on the first submit, but subsequent submits never update

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-qgng1

**Expected behavior**
Nesting the <input> should behave the same as putting the input in the same component with the {fields.map()} call.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari/Chrome
 - Version Safari 13.0.5, Chrome 80.0.3987.149

**Comment by bluebill1049** [comment]
This is due to an understanding of JS closure: https://codesandbox.io/s/react-hook-form-usefieldarray-0tewz you can use React.useMemo or move Child component outside.

**Comment by sirgwain** [comment]
Thank you for the quick response! That fixed my problem. I didn't realize inlining components would cause an issue like that.

**Comment by bluebill1049** [comment]
no worries @sirgwain it's basically JS closure. follow my suggestion above you can avoid this type of issue.
