### ISSUE TITLE
Remove on field array does not remove nested field array values

### ISSUE THREAD

**Issue by paulhan221** [react-hook-form/react-hook-form#1288]
**Describe the bug**
- Removing field array value doesn't remove its nested field array values

**To Reproduce**
1. remove `useFieldArray2` value
2. click append
3. notice removed field's nested field values `field11` and `field22` display instead of empty fields 

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-2z9yg

**Expected behavior**
- removing a field array should remove it's nested field array values

**Comment by bluebill1049** [comment]
Thanks for the issue report. You have had to remove it yourself as well, there is no magic to remove nested field array items.

**Comment by bluebill1049** [comment]
here is an updated version: https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-x7btr
