### ISSUE TITLE
Validate function on Select element causes onChange value to be set to old value

### ISSUE THREAD

**Issue by mojarrahp** [react-hook-form/react-hook-form#1289]
**Describe the bug**
When using a custom `validate` function on a Select element, which normally uses local state to update its value using the `onChange` event, upon selecting a different option, the new value does not update if RHF first calls its `validate` function.

**To Reproduce**
1. Go to https://codesandbox.io/s/select-validate-5lxqq
2. The Select's default value is invalid. Click on Submit to trigger validation.
3. The validation occurs and Error message appears
4. Try to select a valid option.
5. Notice that `validate` happens, but then `onChange` still has the same value as before in `e.target.value`, as if somehow validate prevented the default behavior. Notice that this only happens once, after you try to select another option again, this time it works. Also notice that this issue does not happen if the form isn't being validated, if you never click on Submit, the onChange works fine and you can select any option without issues.

**Codesandbox link (Required)**
https://codesandbox.io/s/select-validate-5lxqq

**Expected behavior**
When using `validate` in a Select element, a user should be able to select any option from the Select element at any time, even if the new option is invalid.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser Chrome Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by bluebill1049** [comment]
why are we mixed uncontrolled with controlled? What's the usage?

This is what i expected when using this lib.

```
<select
        name="age"
        ref={register({
          validate: v => {
            console.log("validating", v);
            return v !== "50";
          }
        })}
      >
```

**Comment by mojarrahp** [comment]
Hey @bluebill1049 thanks for your reply.

So are you saying RHF doesn't support react controlled components?

The usage is I always use Select elements in react in _controlled mode_ how it is suggested in their docs (https://reactjs.org/docs/forms.html#the-select-tag). If I try to use it in the _uncontrolled_ way by adding the `selected` attribute on the option tag then React gives this warning:

`Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.`

Is there any way I can keep using the Select element in a _controlled way_ and still hook it up with RHF and use its `validate` function for custom validations on it?

Thanks,

BTW, I love RHF, awesome library, great job.

**Comment by bluebill1049** [comment]
@mojarrahp we support Controlled component, but i think you have to pick your choice during usage.

- <input ref={register} name="test" /> -> watch() API
https://react-hook-form.com/api#watch

- for Controlled 
  1. using Controller https://react-hook-form.com/api#Controller
  2. custom reigster

```
useEffect({
  register('test');
}, [register])

<input value="test" onChange={(e) => {setValue('test', e.target.value)}} />
```

hope above make sense.
