### ISSUE TITLE
watch('useFieldArrayName') returns wrong values

### ISSUE THREAD

**Issue by h-sakano** [react-hook-form/react-hook-form#1290]
**Describe the bug**

`watch('useFieldArrayName')` returns default values instead of the ones in the input fields under certain conditions.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-jzlh7
2. Click on 'append'.
3. Modify input field values in the 2nd row.
4. `watch('test')` returns values correctly.
5. Click on 'append' again.
6. `watch('test')` returns default values instead of current value.
    - Note: The values in the input fields are not changed.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-jzlh7

**Expected behavior**

`watch('fieldArrayField')` always returns current values in the input fields.

**Comment by h-sakano** [comment]
I found the same problem as `append` occurred in `prepend`, `insert` and `reset`.

**Comment by bluebill1049** [comment]
here is the fix preview: https://codesandbox.io/s/react-hook-form-usefieldarray-rwwji

**Comment by bluebill1049** [comment]
The incoming PR will fix this bug and also allow you watch individual field array item instead of whole.

**Comment by h-sakano** [comment]
> here is the fix preview: https://codesandbox.io/s/react-hook-form-usefieldarray-rwwji

Excellent!!
It seems to be working very well.

**Comment by bluebill1049** [comment]
Thank you for testing! 👨🏻‍💻
