### ISSUE TITLE
How do I perform a POST request only when form is validated?

### ISSUE THREAD

**Issue by EliranGooner** [react-hook-form/react-hook-form#1292]
I want to create a contact form using FlexyForm in my Gatsby project in order to send the info by email. The setup for it is very simple and you just need to add to a normal ```form``` HTML tag - ``` method="post" action="https://www.flexyform.com/f/flexyformkey" ```

So I had a form like this that was functioning and then I wanted to add form validation so I used react-hook-form and the validation works great but after validating it doesn't make the post request to FlexyForm.

I fill the form to satisfy the validation and hit send button but other than logging the register to the console nothing happens. Without react-hook-form it usually redirects me to wherever I set FlexyForm to redirect after receiving data.

sandbox: https://codesandbox.io/s/nervous-pine-o2z5m
(^^ it doesn't include the key for obvious reasons)

I'm quite new to React and Gatsby so it might be something obvious I'm missing.

**Comment by bluebill1049** [comment]
Welcome to React.

I haven't got much time to looking into your example. i think this is what you after

```
const onSubmit = () => {
  fetch(url, {
    method: 'post',
    headers: {
      "Content-type": "https://www.flexyform.com/f/flexyformkey"
    },
    body: 'foo=bar&lorem=ipsum'
  })
})
}

handleSubmit(onSubmit)
```

**Comment by EliranGooner** [comment]
@bluebill1049 

Thank you for the quick response but I do I have a few questions about your suggestion.
1. Isn't the onSubmit function supposed to receive data parameter (the input) to send inside the body to FlexyForm?
2. What is the ```url ``` variable you referenced in the beginning of the ```fetch```?  Isn't it supposed to be the url  you wrote in the ```Content-type``` header?
3. Why do I need the ```content-type``` header?

**Comment by bluebill1049** [comment]
I am going to close this issue because there are mostly generic questions for javascript fetch. You can read more about fetch in this doc: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

1. once form is valid you will get data from handleSubmit and then you can send them off to your API end point
2 - 3. read the fetch doc

**Comment by EliranGooner** [comment]
> I am going to close this issue because there are mostly generic questions for javascript fetch. You can read more about fetch in this doc: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
> 
> 1. once form is valid you will get data from handleSubmit and then you can send them off to your API end point
> 
> 2 - 3. read the fetch doc

I read the docs and still can't find a way to stop CORS to throw an error

**Comment by AlexeyMatskevich** [comment]
In order to use the form you just need not to intercept the event on the form
Instead, intercept the event on the submit button.
Unfortunately this will not work when clicked Enter in fields.
```jsx
...
function onSubmit () {
   document.forms[0].submit()
}
return(
...
  <form action={props.url} method='post'>
...
     <input type='submit' onClick={handleSubmit(onSubmit)}/>
  </form>
)
```

**Comment by ErikAGriffin** [comment]
Expanding on Alexey Matskevich's answer, you can have the generic `<form action="url" method="post">` work when the user clicks enter as well.  Simply attach the event to the onSubmit handler of the form element

```javascript

const formRef = React.useRef();

function onSubmit () {
   formRef.current.submit();
}

return(

  <form ref={formRef} onSubmit={handleSubmit(onSubmit)} action={props.url} method='post'>
  ...
     <input type='submit' />
  </form>
)
```
