### ISSUE TITLE
add support to parse a list from a `textarea`

### ISSUE THREAD

**Issue by bodokaiser** [react-hook-form/react-hook-form#1297]
**Is your feature request related to a problem? Please describe.**

I want to upload a list of e.g. emails. I don't want to [`useFieldArray`][1] because it does not allow for copy-and-paste.

**Describe the solution you'd like**

According to https://github.com/jquense/yup/issues/564, one can use `Yup.transform` to cast between types, e.g.

```javascript
const validationSchema = Yup.object().shape({
  email: Yup.array()
    .transform(function(value, originalValue) {
      if (this.isType(value) && value !== null) {
        return value;
      }
      return originalValue ? originalValue.split(/[\s,]+/) : [];
    })
    .of(Yup.string().email(({ value }) => `${value} is not a valid email`)),
});
```

So one could move the parsing into a `yup` transform. That said, it is not clear how to transform back to a string value. Perhaps, the `yup` transform is only executed once `onSubmit`.

**Describe alternatives you've considered**

* [`useFieldArray`][1]
* `<CustomInput />` that handles mapping from `string` to `string[]`
* File upload of `.csv`, `.xlsx`, i.e. move the complexity to the back-end

[1]: https://react-hook-form.com/advanced-usage#FieldArrays

**Comment by bluebill1049** [comment]
what's this feature have to do with this form validation lib?

**Comment by bodokaiser** [comment]
> what's this feature have to do with this form validation lib? This sounds like parsing lib's task.

Do you understand the user problem behind the issue (upload of multiple items over a `<textarea>`)?
How would you solve this problem? Do you have an example?

I know several parsing libraries, e.g. [papaparse][2] but I don't see how they would integrate into the usual `react-hook-form` workflow. Of course, one always could move such logic into `onSubmit`.

[2]: https://www.papaparse.com

**Comment by bluebill1049** [comment]
> Do you understand the user problem behind the issue (upload of multiple items over a `<textarea>`)?
> How would you solve this problem? Do you have an example?

I don't, not with what you have provided above. I am not a mind reader just yet. Why your questions sounds like it's my problem to solve? I am happy to offer my help as I have already built a package for everyone for building forms...

> I know several parsing libraries, e.g. papaparse but I don't see how they would integrate into the usual react-hook-form workflow. Of course, one always could move such logic into onSubmit.

Good, then I think it's a good idea to do you parsing inside submit or onChagne.

**Comment by bodokaiser** [comment]
`react-hook-form` already elegantly [supports masked inputs](https://github.com/react-hook-form/react-hook-form/blob/master/examples/customMaskedInput.tsx). 

I would love to see `react-hook-form` support a value life cycle. See, for example, [redux-form][3].

If you didn't consider a value lifecycle feature so far for `react-hook-form`, maybe because its implementation is difficult or it solves problems you consider too specific, then I suggest we close this issue and I will do the parsing inside `onSubmit`.

[3]: https://redux-form.com/6.5.0/docs/valuelifecycle.md/

**Comment by bluebill1049** [comment]
thanks @bodokaiser this is a much better context for me. I will take a look and let you know.

**Comment by bluebill1049** [comment]
Redux form value life cycle is pretty cool, however that's also one of the reasons why its package size getting close to `27kb`. I think it's trying to do too many things in a lib (my personal opinion). I don't think we will implement a similar feature. However, I do see your concerns that you probably want to parse/fomat/normolize you input, so instead have you consider using `Controller` and return parse `value`?

```
<Controller 
  name="test"
  onChange={(e) => {
    return parseValue(e.target.value)
  }}
/>
```

If the above solution is not working, then it's a bug we should fix.

**Comment by bodokaiser** [comment]
I agree 100% with you!

I created a [codesandbox][1
[1]: https://codesandbox.io/s/react-hook-form-custom-input-3vicw

**Comment by bluebill1049** [comment]
Thanks for the CSB i will take a look.

**Comment by bluebill1049** [comment]
try this: https://codesandbox.io/s/react-hook-form-custom-input-zvxmr

I had to propagate `arguments` through the Controller, `[...arguments]` and hence they are `array`, we can probably improve that in the long turn and convert it back to `Object`.

**Comment by bodokaiser** [comment]
Thank you!

I updated `parseValue` in the [codesandbox][1] and noticed that:

1. If you `submit` the form with the default value, `parseValue` is not executed.
2. If you trigger an `onChange` event inside `<textarea>`, the values changes to `react@hook-form.com,info@example.com`. I guess you use somewhere `value.join(",")` inside `react-hook-form` to convert array values back to strings.

[1]: https://codesandbox.io/s/react-hook-form-custom-input-4ocps

**Comment by bluebill1049** [comment]
> 1. If you submit the form with the default value, parseValue is not executed.

 ✅probably need to get default value to the right format

> 2. If you trigger an onChange event inside <textarea>, the values changes to react@hook-form.com,info@example.com. I guess you use somewhere value.join(",") inside react-hook-form to convert array values back to strings.

we actually don't do anything, i will take a look your CSB.

**Comment by bluebill1049** [comment]
Is this what we expected for submit data?

<img width="595" alt="Screen Shot 2020-03-30 at 4 52 39 pm" src="https://user-images.githubusercontent.com/10513364/77879780-e75d2400-72a6-11ea-9d7b-4396116e5426.png">

**Comment by bodokaiser** [comment]
> Is this what we expected for submit data?
> 
> <img alt="Screen Shot 2020-03-30 at 4 52 39 pm" width="595" src="https://user-images.githubusercontent.com/10513364/77879780-e75d2400-72a6-11ea-9d7b-4396116e5426.png">

Yes, exactly 🥳. What did you change?

**Comment by bluebill1049** [comment]
lol that's your example... don't use alert

**Comment by bodokaiser** [comment]
> ✅probably need to get default value to the right format

Yep, I updated the [codesandbox].

> lol that's your example... don't use alert

I cannot replicate this. Every time I press enter it inserts a comma in the text field.

I believe at some point there has to be a conversion from an `Array` to a string via `.join(",")`. Let me check if I find something in the source code of `react-hook-form`.

[1]: https://codesandbox.io/s/react-hook-form-custom-input-4ocps

**Comment by bodokaiser** [comment]
I believe an `isArray(value)` is responsible, e.g. [here](https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L456).

So in theory, one needs to distinguish between the two cases:

1. Multiple input elements with `name="attr[0]"` (current behaviour)
2. Single input element

That said, this might involve too many changes for a very specific use case.

**Comment by bluebill1049** [comment]
hmmm, I don't think what you have pointed out has to do with this output. let me try it out.

**Comment by bluebill1049** [comment]
> I cannot replicate this. Every time I press enter it inserts a comma in the text field.
that's actually correct behavior for Textarea. Try with simple controlled component you will get that.

**Comment by bluebill1049** [comment]
here is an example: https://codesandbox.io/s/react-hook-form-custom-input-9qc9g i think if you can get `ParseTextarea` component working as expected then it will all work for you

**Comment by bodokaiser** [comment]
Great man! I changed one last part on the formatting side that removes the commas. In addition, I added a `yup` validation schema:

https://codesandbox.io/s/react-hook-form-custom-input-q1elq

Do you think we can add this to the `examples`? If you like I could prepare a PR.

**Comment by bluebill1049** [comment]
wow! this works like a charm! 👏Yeah, let's get this boy into the example folder.

What would be a good name for this example for use-case? 

Small suggestion: I would remove yup validation for in your CSB and stay focus on the solution.

**Comment by bluebill1049** [comment]
I guess this is for value parsing right?

**Comment by bluebill1049** [comment]
Hows> Parse input value?

**Comment by bodokaiser** [comment]
What about "parse and format input value" or "value lifecycle" (a la redux-form)?

I got the validation working in the [codesandbox](https://codesandbox.io/s/react-hook-form-custom-input-q1elq).
Because it's not 100% obvious (at least for me) that one can use `yup.array()` in this case and that one has to format `errors.emails`, I would prefer to include `yup`. That said it's your call. Maybe it's clear for others.

**Comment by bluebill1049** [comment]
Parse and format input value - sounds great!

> Because it's not 100% obvious (at least for me) that one can use yup.array() in this case and that one has to format errors.emails, I would prefer to include yup. That said it's your call. Maybe it's clear for others.

Thanks, @bodokaiser I think if the user wants to check out validation, then they can check out the validation example. in my eyes, it's better to stay focused and minimum. 👍

**Comment by bodokaiser** [comment]
Thank you too very much and stay safe!

**Comment by bluebill1049** [comment]
> Thank you too very much and stay safe!

you too mate :)

**Comment by bluebill1049** [comment]
I am going to close this issue, feel free to send a PR whenever you are ready. thanks a lot.

**Comment by omgoshjosh** [comment]
This project is great!

Personally, I think this particular example would be nice to have somewhere in the docs in addition to the great example in the code snippets in the repository.

It could live as another example in the control section, or maybe just be mentioned as another possible use case for the control function and Controller component.

Reading the docs, one might not think (at least I didn't think) to roll your own controlled component since it's just an example using external libraries like material UI and React Datepicker.

For real though, this project and issue are a perfect example of high quality open source development.

Congrats and thanks! Let's keep it going.

**Comment by bluebill1049** [comment]
@omgoshjosh 👍 it's in the example folder. thanks for the kind words.
