### ISSUE TITLE
Possibility of triggering validation for all fields at once

### ISSUE THREAD

**Issue by FatehAK** [react-hook-form/react-hook-form#1298]
Is it possible to trigger validation for fields at once? Currently, I have to pass each field I want to validate to triggerValidate(''). Is it possible to trigger validation programmatically for the all fields without using the form element?

**Comment by bluebill1049** [comment]
I will update the doc: https://react-hook-form.com/api#triggerValidation

try that triggerValidate()

**Comment by bluebill1049** [comment]
updated.

**Comment by FatehAK** [comment]
Cool. Thanks
