### ISSUE TITLE
the display order of the error messages is wrong

### ISSUE THREAD

**Issue by pmg1989** [react-hook-form/react-hook-form#1299]
**Is your feature request related to a problem? Please describe.**
Can you provide an array of errors to make it easier to display error messages in Toast or dialog mode? When I use dialog to display, if there are multiple inputs and I trigger one of them, the display order of the error messages is wrong

**Describe the solution you'd like**
`const { errors } = useForm<FormFields>()`
`alert(errors[0].message)`
or
`const { error } = useForm<FormFields>()`
`alert(error.message)`

**Describe alternatives you've considered**
`const { errors } = useForm<FormFields>()`
`alert(Object.values(errors)[0]?.message)`

**Comment by bluebill1049** [comment]
follow our template and provide a codesandbox plz
