### ISSUE TITLE
Some `watch` usage broken by change introduced in #1034

### ISSUE THREAD

**Issue by johncalvinroberts** [react-hook-form/react-hook-form#1300]
**Describe the question?**
Hi, Bill! Not sure if I should label this as a question or a bug...near impossible for us to reproduce the issue in a codesandbox, so labelling as question.

We're migrating to latest `react-hook-form` from a v3.x version, and some of our usage of `watch` has been broken by latest changes in latest. 

We've narrowed it down to 1205cd372699db4cb2237b9082be5d5235bd2c21 as the commit that introduced the breakage.

Basically: 
* We have multiple `FormContext` mounted as children of one component, multiple `useForms` happening at the same time
* if we `watch` some deeply nested **controlled** fields, the fields cannot be updated. In other words, cannot type in the input, the value is bound and won't update.
* logging `getValues()` -> logs the updated (expected) value

Through some trial and error debugging, we've found particularly this line https://github.com/react-hook-form/react-hook-form/blob/1205cd372699db4cb2237b9082be5d5235bd2c21/src/useForm.ts#L579

If we change the dependency array here to just `[rerender]`, the bug is not reproducible. Do you

My apologies for creating this issue, you deserve GH discussions for this repo. Can move this to spectrum if needed. **Question is**: is there anything you are are aware of that would cause this update to create this breakage?

**To Reproduce**

**Codesandbox link (Required)**
Include a codesandox will help us to investigate the issue quicker.

**Screenshots**

**Additional context**

**Comment by bluebill1049** [comment]
hey, @jasondibenedetto that's all good ❤️and thanks for doing the investigating over the codebase. However, it would be pretty hard for me to debug this without a reproducible CSB, (not try to avoid the problem) which I am pretty sure there is some change should get things running smoothly again. Hopefully, if you can provide a CSB for to continue with the investigation.

**Comment by bluebill1049** [comment]
what's your `watch` usage like? and what are you watching?

**Comment by johncalvinroberts** [comment]
I don't even know how to begin describing our `watch` usage, other than "heavily". I'll close this for now, kind of unfair without CSB. If I can reproduce w/ CSB I'll reopen.

Thanks again for your quick response and hard work @bluebill1049

**Comment by bluebill1049** [comment]
@johncalvinroberts keep me updated with this issue. just so you know, you got my support on this. if something is not working expected, I will jump in and fix it ASAP.

cheers
bill
