### ISSUE TITLE
validationResolver is refreshed when changed

### ISSUE THREAD

**Issue by Nickman87** [react-hook-form/react-hook-form#1302]
**Describe the bug**
I have a validation schema, that is dependent on data that is loading. So I initialise the hookForm as soon as I can, but after a while, the validation schema changes (this could also be because of some user input for example, but is automatic in my case.

I had the same issue when using the old (deprecated) validationSchema and thought it might have been solved if I switched to the new validationResolver, which was not the case.

**To Reproduce**
1. create a hookForm with a validationResolver
2. replace the resolver after it has rendered
3. run the validations

**Codesandbox link (Required)**
Sample is here, I just replace the resolver after 2 seconds, and it keeps using the old one:
https://codesandbox.io/s/react-hook-form-validationresolver-ke2fo

**Expected behavior**
When I change the validation schema, of the validationResolver, it should always use the newest version in all validations.

**Desktop:**
 - OS: OSX
 - Browser Chrome
 - Version Latest

**Comment by Nickman87** [comment]
It also seems to just _not work_ at all some times... In the same sanbox, sometimes I get no error when I press submit, even though it should always produce an error.

**Comment by bluebill1049** [comment]
That's expected @Nickman87, we cache validation schema and resolver. if you want to change resolver you can toggle the logic in same the function.

**Comment by Nickman87** [comment]
Ok, I can manage that with the resolver solution.
I noticed that in my sandbox, when you do a full page reload, the validation does not work, only after doing an internal refresh (in the sandbox browser page). That does not seem like a correct flow?

**Comment by bluebill1049** [comment]
> Also, it might be usefull to add to the documentation which properties are cached, and which cause a reflow?

Yes, sure feel free to provide your suggestion or send a PR as well.

i notice in your example you are doing a curry, i think you want to send data via `validationContext`.

similar question here as well: https://spectrum.chat/react-hook-form/help/useformcontext-and-errors~41a32449-970d-4094-82e2-e4d2564fc64e

**Comment by bluebill1049** [comment]
just a quick follow up here, how did you go with the issue?

**Comment by Nickman87** [comment]
@bluebill1049 Thanks for the feedback, I have not yet had a chance to revisit my code to implement a workaround.
I will probably get around to doing this by the end of the week and will post back here!

**Comment by bluebill1049** [comment]
awesome @Nickman87 looking forward for your feedback :)

**Comment by bluebill1049** [comment]
going to close this issue for now. feel free to follow this up tho.

**Comment by Nickman87** [comment]
I solved the issue and my validations are now working perfectly.
Using a ref inside my resolver creation I got the effect that I wanted:

```
import { useCallback, useRef } from "react";

export function useYupValidationResolver(validationSchema) {
  const schema = useRef();
  schema.current = validationSchema;

  return useCallback(async (data) => {
    try {
      const values = await schema.current.validate(data, {
        abortEarly: false,
      });
      return {
        values,
        errors: {},
      };
    } catch (errors) {
      return {
        values: {},
        errors: errors.inner.reduce(
          (allErrors, currentError) => ({
            ...allErrors,
            [currentError.path]: {
              type: currentError.type ?? "validation",
              message: currentError.message,
            },
          }),
          {}
        ),
      };
    }
  }, []);
}
```

At first I thought I could use the resolverContext to pass in my schema, but this property is also cached apparently :).

**Comment by bluebill1049** [comment]
hmmm good point @Nickman87 thanks for the update. let me take a look why i am caching the context.

**Comment by bluebill1049** [comment]
oh i see, why i did that... if i am not caching that variable, then the user will need to provide a memorised version of it which is annoying in terms of DX. however it should worked with validationContext when you are changing them with each render. do you have a CSB to demonstrate the issue?

**Comment by Nickman87** [comment]
The ref never gets updated, so it will not pass on the new context value?
https://github.com/react-hook-form/react-hook-form/blob/96468de91c73dd8b562d6f81e0501d26d468e896/src/useForm.ts#L108

Here is a sandbox: https://codesandbox.io/s/react-hook-form-validationresolver-ke2fo

It should print out "It works" after about 2 seconds when you press the submit button.
I understand the reasoning of caching the data for the users, but it does provide less flexibility.
Also, it seems like the validationContextRef is never used as a "dependency" of any hooks, so it will not trigger any side effect to just keep track of the new value every render?
You could still put it inside the ref every time, like I did in my solution :).

**Comment by bluebill1049** [comment]
thanks, @Nickman87 agree with above, I will investigate for a better solution.

**Comment by Nickman87** [comment]
Keep up the awesomeness in the the library! :)

**Comment by bluebill1049** [comment]
thanks @Nickman87 find the fix. will create a PR for it.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-validationresolver-kr991
