### ISSUE TITLE
 how to not allow the user to enter any special characters in input

### ISSUE THREAD

**Issue by MatheusLuiz2000** [react-hook-form/react-hook-form#1303]
Hey Guys,

I using React Hook Form in the version 5.1.1 and i have some problem. In the documentation, i didn't found any solution for that. I need do not register in the input values if the value typed by the user in is special character.

So, my input only accepts numbers(type="password") and if the user typed some another character like "AMNCS" or "@$@$!", the input not shows the values and not register.

How can i do that? I tried if onChange and return false. i tried with the validation but the validation accept the user TYPED in the input the incorrect value.

I tried this but not work 

```
<InputCampos
type="password"
label="Senha"
name="senha"
ref={register({ required: true, pattern: /^0|[1-9]\d*$/ })}
min="6"
maxLength="6"
erro={errors.senha ? errors.senha.message : ''}
/>

In the component


export const InputCampos = React.forwardRef((props, ref) => {
  return (
    <InputContainer className="input-group">
      <label
        htmlFor={props.name}
        error={props.erro ? 'erro' : ''}
        className="label"
      >
        {props.label}
      </label>
      <input
        className="input-style"
        error={props.erro ? 'erro' : ''}
        name={props.name}
        {...props}
        ref={ref}
      />
      <small>{props.erro ? `${props.erro}` : ''}</small>
    </InputContainer>
  );
});

  const { register, handleSubmit, errors } = useForm();
```

**Comment by bluebill1049** [comment]
This is what you after: https://github.com/sanniassin/react-input-mask not RHF

**Comment by bluebill1049** [comment]
here is an example with cleave.js https://codesandbox.io/s/react-hook-form-date-field-y7xp2?from-embed
