### ISSUE TITLE
Pattern validation not working like in HTML forms

### ISSUE THREAD

**Issue by pmowrer** [react-hook-form/react-hook-form#1304]
**Describe the bug**
According to the docs, this library aims to "[align] with the existing HTML standard for form validation." Given this, I expected the library's `pattern` validation to work the same as regular HTML validation, but unless I'm missing something (in which case forgive me), it doesn't appear to be the case.

**To Reproduce**
1. `register` an input and pass `pattern: /\w+/` as the validation.
2. Enter `*abc` into the input.
3. Validate.

**Actual behavior**
The input value is valid.

**Expected behavior**
The input value should be invalid.

In regular HTML forms, the input value must fully match the `pattern` regexp to be valid. In `react-hook-form`, it appears it only needs to be a partial match to be valid.

**Codesandbox link (Required)**
https://codesandbox.io/s/pedantic-taussig-bqg3j

1. Observe that the vanilla HTML input is **invalid** for the input `*abc`.
2. Type `*` into the `react-hook-form` input and observe it is **invalid**.
3. Type `*abc` into the `react-hook-form` input and observe it is **valid**.

**Other**
First of all, great library! I enjoy the fresh take!

I was surprised to see that when using the HTML standard validators in `register`, they aren't actually applied as attributes to the input (i.e. I expected to see the `pattern` attribute on the input). What's the point of adopting an API based on the HTML standard validators if they aren't applied in an HTML standard way? Just curious.

**Comment by bluebill1049** [comment]
Thanks @pmowrer for the issue report.

> I was surprised to see that when using the HTML standard validators in register, they aren't actually applied as attributes to the input (i.e. I expected to see the pattern attribute on the input). What's the point of adopting an API based on the HTML standard validators if they aren't applied in an HTML standard way? Just curious.

It's by design, we are not only support HTML inputs. The lib supports external controlled component, React Native and etc.

<img width="252" alt="Screen Shot 2020-03-31 at 12 03 20 pm" src="https://user-images.githubusercontent.com/10513364/77976073-a36e2b80-7347-11ea-912d-780bf781c52a.png">

we are using regex with `test` API in the lib, for proper regex, you will have to do the following

`/^\w+$/.test('@asd')`

hope above make sense.

**Comment by pmowrer** [comment]
Sorry to say I'm still confused. When you say "our constraint based validation API", I'm supposed to take away that this is a custom validation API and I shouldn't expect things to work like in HTML? But you also use the term "HTML standard" and say that library "[aligns] with the existing HTML standard for form validation" (as quoted above). The list of built-in validators is the exact same as the HTML standard validators. Why wouldn't I expect it to work like HTML? This is obviously confusing. If the library doesn't adhere 100% to the standard, then what's the point?

**Comment by bluebill1049** [comment]
again... another aggressive people in the community. 
I guess you are right :) There is no point, you can stop using the lib it's as simple as that.
