### ISSUE TITLE
option for defaultValues at form to override defaultValue at field

### ISSUE THREAD

**Issue by b-bunhak** [react-hook-form/react-hook-form#1305]
It would be very useful for me if it was possible to use the defaultValue from the field but also be able to override this value when data comes in from the api and passed into the form hook. This used to be how the Controller worked in an earlier version but as of the latest version that no longer is the case.

**Comment by bluebill1049** [comment]
take a look this: https://react-hook-form.com/api#reset

**Comment by b-bunhak** [comment]
thanks for answering so quickly. I know about the reset. It's a bit complicated for me to explain what i'm trying to do but i will try. I want to be able to pass in a defaultValue at the field value and also be able to use the reset api. If I pass in a defaultValue to the field, when i reset even if i pass in a new value it get reset to the field defaultValue.

**Comment by b-bunhak** [comment]
I would like to have an inline defaultValue and also be able to reset to a new value with the reset api.

**Comment by bluebill1049** [comment]
Is this work for you?

```
reset({
  ...getValues(),
  yourValue: 'test'
})
```

**Comment by b-bunhak** [comment]
I made a sandbox to try to explain. 
https://codesandbox.io/s/recursing-bose-e95oq
Regular ref with defaultValue resets with new value but controller with defaultValue does not. I need to set to set a defaultValue on the controller and the later be able to reset it to a new value. In the docs it says that the inline defaultValue overwrites the form defaultValues but it would be very helpful to me if it was possible to add a configuration to change this.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/red-snowflake-f0udg

**Comment by b-bunhak** [comment]
I made reusable form components. These components are used in some forms that start empty and also in other forms that start with values. Since all fields need an initial values in order to not get the uncontrolled component error I set the defaultValue as "", false, or null depending on the type of component on these reusable components. This is useful so I don't have to repeat having to set all my forms to an empty state when they don't have an initial value. I hope that makes some sense.

**Comment by bluebill1049** [comment]
you can give default value as empty right?

**Comment by b-bunhak** [comment]
Yes this works but it's what i'm trying to avoid. Using it this way I am forced to write out every field and the empty value for every form, I have a lot of forms :/. If I am able to set the defaultValue on the controller as empty and overwrite that value with the reset api later then I don't need to write out everything all the time and can use my reusable components.

**Comment by bluebill1049** [comment]
last option is probably using `setValue`, if that's working for you, then i don't think there is an alternative for this lib.

**Comment by b-bunhak** [comment]
I think it's possible or me to hack something together with setValue but it's a bit messy, i'm still testing it. Thanks

**Comment by b-bunhak** [comment]
Would you be open to adding an option to controller component for what i am trying to do? I can write it if you are open to the idea.

**Comment by bluebill1049** [comment]
> Would you be open to adding an option to controller component for what i am trying to do? I can write it if you are open to the idea.

Thanks, but for now i don't think we want to introduce more complexity the API.

**Comment by b-bunhak** [comment]
Well, you have broken my heart bill. Thanks for the lib. I really like it. 4.9.7 is the last version that works the way I need it will stay there :/

**Comment by bluebill1049** [comment]
@b-bunhak you are saying version 4.9.7 is working as what you expected? can you show me a CSB? in case i am missing something here.

**Comment by b-bunhak** [comment]
Okay I made a sandbox to try and show my use case, it's a but messy but hopefully you understand.
This is on version 4.9.7 working how i need it to
https://codesandbox.io/s/charming-herschel-8i8tm

This is on latest version not working for me
https://codesandbox.io/s/vigilant-cray-nqgjy

On the 4.9.7 version you can see that it loads the initial values in the form but in the latest it does not.

**Comment by b-bunhak** [comment]
I was reading the library source and this commit 1d201d2ed066350a6f186ff7358441213c95d48c was when it stopped working the way I would like it to. It seems like it was an intentional choice by you guys but it would be incredible for me if there was an option to have same functionality as 4.9.7 in the newest version.

**Comment by bluebill1049** [comment]
that fix was a bug fix. i added the following code into your example, it's working again. 

```
useEffect(() => {
  setValue(name, 'test'); //'test' should be your value
}, [setValue, name])
```

**Comment by b-bunhak** [comment]
The problem with setValue is that it is difficult to use with many fields at once and also the docs say it sets touched and dirty to true, I was looking for a proper reset. The only way to get what I need to work is by having an option to turn that "fix" off, letting the form default overwrite the inline default. Other than that from what I've seen there is no other way to do what I want. Thats okay, It's working as you intend it. I'm sad now that my form isn't working but I'll think of another way to do things in the future. Thanks again. Great lib.

**Comment by bluebill1049** [comment]
I will take another look before closing this issue. hopefully i can find a solution. if not then i will close this. at least give it a try.

**Comment by b-bunhak** [comment]
Alright, I will try making my app work with setValue in the meantime. Thank you very much.

**Comment by bluebill1049** [comment]
just a thought: 

any chance to remove `defaultValue=""` and always compose a `defaultValues` for your form?

**Comment by vensauro** [comment]
You can set default initial value at component level:
```js
function Input({ value = '', onChange }) {
	return (
		<InputFromLibThatNotHaveRef value={value} onChange={onChange} />
	)
}
```

**Comment by vensauro** [comment]
Or use a function that transform a object(key: value) to a array with the type of the `setValue`: 
setValue type:
```ts
(Record<Name, any>[], shouldValidate?: boolean) => void
```
Example:
```js 
setValue(toEntriesObjects({ key1: value1, key2: value2 }))
```
toEntriesObjects function:
```ts
export function toEntriesObjects<T>(object: T) {
  return Object.entries(object).map(([key, value]) => ({ [key]: value })) as Array<{ [key in keyof T]: T[key] }>;
}
```


but the best way to do that is with: https://github.com/react-hook-form/react-hook-form/issues/1305#issuecomment-606419950 + https://github.com/react-hook-form/react-hook-form/issues/1305#issuecomment-606645853

**Comment by b-bunhak** [comment]
> You can set default initial value at component level:
> 
> ```js
> function Input({ value = '', onChange }) {
> 	return (
> 		<InputFromLibThatNotHaveRef value={value} onChange={onChange} />
> 	)
> }
> ```

@vensauro Yes! This works, exactly what I need. It seems obvious now that you said it but I don't think I would have thought of it. Thank you very much! Helped me a lot.

**Comment by b-bunhak** [comment]
also thanks @bluebill1049 for spending time helping me out and of course for the lib

**Comment by bluebill1049** [comment]
Thanks @b-bunhak I do as much as i can here :) thanks @vensauro for saving the day! <3

**Comment by bluebill1049** [comment]
Thanks @b-bunhak for your sponsorship. I really appreciated that, and totally didn't expect that as well. I know you have set it to private and i can't reach you via an email. so i will write the message here and delete it. Thank you very much for your support and kindness. ❤️
