### ISSUE TITLE
latest tag is missing in npm registry

### ISSUE THREAD

**Issue by arojunior** [react-hook-form/react-hook-form#1306]
**Describe the bug**
The tag `latest` is missing in releases list / npm registry

**To Reproduce**
1. `npm install react-hook-form`

**Screenshots**
`npm ERR! 404  'react-hook-form@latest' is not in the npm registry.`

I had to use `npm install react-hook-form@5.2.0` to install the latest version.

**Comment by bluebill1049** [comment]
Thanks for the issue report. looks like everything is working as expected here. which version of npm do you have?

<img width="653" alt="Screen Shot 2020-04-01 at 8 48 55 am" src="https://user-images.githubusercontent.com/10513364/78078299-a45d9680-73f5-11ea-8802-a2f64d9a3d2d.png">

<img width="773" alt="Screen Shot 2020-04-01 at 8 48 24 am" src="https://user-images.githubusercontent.com/10513364/78078261-91e35d00-73f5-11ea-8f5c-446ea48d9358.png">
