### ISSUE TITLE
Help with defaultValue and Call API using useEffect

### ISSUE THREAD

**Issue by MatheusLuiz2000** [react-hook-form/react-hook-form#1307]
Hey guys!! I am back and i sorry to make a lot of questions here but i am new using react-hook-form and react so.

I'm doing a API call and receving the results correctly but when i pass the values to my Component, the defaultValue is not set correctly but with i write a console.log in props.defaultValue, i recive the value correctly!

This is my code.

Here I make a call API and return the values correctly.
```
  const [informacoesCliente, setInformacoesCliente] = useState([]);
  async function buscaClientes() {
    const buscaDadosCliente = await listaDadosCliente();
    if (buscaDadosCliente.status === 200) {
      setInformacoesCliente(buscaDadosCliente.data);
      console.log('dsadsa');
    }

  useEffect(() => {
    buscaClientes();
  }, [])
  }
```
//Aqui está minha chamada do form

```
  const { register, handleSubmit, errors, control } = useForm({
    validationSchema: DadosCadastraisSchema,
  });
```
//Here i call my component input with the values

```
<InputCampos
type="text"
label="Nome Fantasia"
name="fantasia"
control={control}
defaultValue={
  informacoesCliente ? informacoesCliente.fantasia : ''
}
ref={register({ required: true })}
erro={errors.fantasia ? errors.fantasia.message : ''}
/>
```

//Here is my component input with the values and props(Using Cleave lib to mask things);

```
export const InputCampos = React.forwardRef((props, ref) => {
  return (
    <InputContainer className="input-group">
      <label
        htmlFor={props.name}
        error={props.erro ? 'erro' : ''}
        className="label"
      >
        {props.label}
      </label>
      <Controller
        name={props.name}
        {...props}
        ref={ref}
        control={props.control}
        as={<Cleave options={{}} value={props.defaultValue} />}
      />
      <small>{props.erro ? `${props.erro}` : ''}</small>
    </InputContainer>
  );
});
```

And when a console.log the props.defaultValue comes in the first time "undefined" but in the others call return the correctly values.

Thanks for the attention!

**Comment by bluebill1049** [comment]
hey @MatheusLuiz2000 any change to provide a simple codesandbox? I haven't read everything above just, but a simple codesandbox will help me to provide a solution for you.

**Comment by MatheusLuiz2000** [comment]
Hey bill! Thanks for help!

Here is https://codesandbox.io/embed/sparkling-framework-ldq76?fontsize=14&hidenavigation=1&theme=dark

You can look that i am setting a defaultvalue and when i submit the form, the validation understand that the input don't have the value that shows in input... can you help me?

**Comment by bluebill1049** [comment]
no worries @MatheusLuiz2000 i will take a look for you during my lunch break.

**Comment by bluebill1049** [comment]
oops mistake...

if your data is coming async, you can use `reset({ defaultValues })`.

**Comment by bluebill1049** [comment]
Take a look this example: https://codesandbox.io/s/vigorous-shannon-hwngn

**Comment by MatheusLuiz2000** [comment]
Omg Bill! You are amazing man, i spend all my time yesterday in this, thank you soo much!

**Comment by bluebill1049** [comment]
That's all good @MatheusLuiz2000 👍  next time when you stuck for long, feel free to send a question on Spectrum.

**Comment by jeevanelton** [comment]
can you tell me how to reset multiple fields
