### ISSUE TITLE
Reset with defaults does not behave like setValue when working with array fields

### ISSUE THREAD

**Issue by StarpTech** [react-hook-form/react-hook-form#1309]
**Describe the bug**
Calling `reset({ foo: ['bar'] })` won't update the array field with `'bar'` but clear the field.

1. Click 3 times on `Add Control`
2. Click on `Reset with defaults`
3. Fields are not updated!

**To Reproduce**

https://codesandbox.io/s/react-hook-form-watch-gmm6v

**Comment by bluebill1049** [comment]
Going to close this issue now, feel free to follow up with more questions.
