### ISSUE TITLE
Can't prefill (setValue) values for conditional fields

### ISSUE THREAD

**Issue by StarpTech** [react-hook-form/react-hook-form#1310]
**Describe the bug**

1. Click on `Add control`
2. Click on `Reset with defaults`
3. The text input is filled with `a`
4. Click two times on `Add control`
5. The new text input fields are still empty.

**Expectation**

I expect that the values are stored even when the controls don't exist in order to restore the form state when conditional fields are added. This would be consistent with the behavior of `useForm({ defaultValues })`

In case of `useForm({ defaultValues })` it works but this not applicable because my data is not available at that point in time.

**To Reproduce**

https://codesandbox.io/s/react-hook-form-watch-tbezd

**Comment by bluebill1049** [comment]
thanks for the issue report.

- setValue: only can set value which have been registered
- you may want to consider to use field array

**Comment by bluebill1049** [comment]
I think you what you after is a way to append, remove and reset items dynamically. feel free to correct me if i am wrong :) that's why i was thinking field array probably will be a better fit for your use case:

https://react-hook-form.com/api#useFieldArray

**Comment by StarpTech** [comment]
Thanks, I will check it.

**Comment by StarpTech** [comment]
Hi @bluebill1049 `useFieldArray` works great :+1: thank you. One hint: According to the docs the option `control` is optional but it was required otherwise I will get an exception.

**Comment by bluebill1049** [comment]
if you are using FormContext, then it's optional. 👍

**Comment by StarpTech** [comment]
That's confusing :smile: because `optional` is on the line of the parameter.

**Comment by bluebill1049** [comment]
`control, // control props comes from useForm (optional: if you are using FormContext)`

feel free to submit a PR to adjust that.
