### ISSUE TITLE
Can't infer the exact control when working with errors on array fields

### ISSUE THREAD

**Issue by StarpTech** [react-hook-form/react-hook-form#1311]
**Describe the bug**

This is an example of the error of an array field. How should I conclude to a specific control? Using the index would be very hard.

```js
Object {numberInput: Array[2]}
	numberInput: Array[2]
	0: Object
	1: Object
```

**Expectation**

I expect that error looks like this:

```js
Object {numberInput: Array[2]}
	numberInput: Object {
      'numberInput[0]' : ...
	  'numberInput[1]' : ...
	}
```

**To Reproduce**

1. Click two times on `Add control`
2. Submit Form
3. See console output

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-watch-4hhpe

**Comment by bluebill1049** [comment]
Thanks @StarpTech for the issue report, we don't have any plan to change our errors object shape for now. thanks for your suggestion tho.

**Comment by StarpTech** [comment]
How do you deal with that?

**Comment by bluebill1049** [comment]
@StarpTech in the original release, i had flat error object, i love it, but a lot of people complained about the type support, and hence why moved to v4 with the nested object shape to have better support for TS.

Flat one
`errors['test[0]']`

Now: 
`errors.test[0]`

**Comment by StarpTech** [comment]
The solution is fine when you track the identity of each control in a single place but as soon as you deal with many losely coupled components it becomes very hard to maintain because the component don't know its own index.

**Comment by StarpTech** [comment]
Is there a chance to add another field to the error object to indentify the field from point of view of the control ? e.g

```
errors.arrayControl.error1.name: "arrayControl[0]"
```

**Comment by bluebill1049** [comment]
sorry @StarpTech it's not in the current scope.
