### ISSUE TITLE
Add an active field in formState

### ISSUE THREAD

**Issue by havengoer** [react-hook-form/react-hook-form#1312]
**Is your feature request related to a problem? Please describe.**
I'm in the process of rewriting our various Redux Forms to React Hooks Form, which has been a painless experience so far (props to the team!).

The issue I've come across with is the lack of `active` state for the fields. `formState` provides a lot of context, and the methods `onBlur` and `onFocus` has been enabled me to continue with my work, but it just seems to be clunky.

**Describe the solution you'd like**
It'll be nice to add data in the `formState` to indicate which field is active.

**Describe alternatives you've considered**
The alternative solution I've come up with is to store the the active field using `useState`. I then change the value based on the field's `onBlur` and `onFocus`.

Thanks!

**Comment by bluebill1049** [comment]
hey @havengoer thanks for the feature request. I think we can track this pretty easy with `onFocus` on each fields for now. I will attach a waiting for votes for this feature too.

**Comment by bluebill1049** [comment]
here is relevant feature request: https://github.com/react-hook-form/react-hook-form/issues/808 i think both user have redux-form background.

**Comment by havengoer** [comment]
And thanks for the prompt response as well, @bluebill1049. And you're right, `onFocus` paired on `onBlurred` is enough to solve my issues and become a work-around for Redux's active state fields.

**Comment by bluebill1049** [comment]
thanks @havengoer for the update 👍
