### ISSUE TITLE
is there a way to set specific fields to revalidate onSubmit while other revalidate onChange?

### ISSUE THREAD

**Issue by yec** [react-hook-form/react-hook-form#1313]
is there a way to set specific fields to revalidate onSubmit while other revalidate onChange?

**Comment by bluebill1049** [comment]
not a very clear question....

is this what you after? https://react-hook-form.com/api#triggerValidation

**Comment by yec** [comment]
almost the inverse of that. i want to pause onChange validation on some fields until whole form is submitted. i don't want the whole form to be revalidate onSubmit

**Comment by bluebill1049** [comment]
then you should write logic in side your `validate` function

**Comment by yec** [comment]
thanks. how can the validate function know if it was triggered by onSubmit or onChange?

**Comment by bluebill1049** [comment]
This is very specific case, i guess you can use isSubmitted, or have a state update when user click on the submit button.

**Comment by yec** [comment]
anyway i did this for now. will force the form to be reValidateMode onSubmit

```
			<ConnectForm>
				{({ control, errors }) => {
					if (reValidateMode && reValidateMode === 'onSubmit') {
						control.reValidateMode.isReValidateOnSubmit = true;
					}

					return (
						<Controller
							as={component}
							control={control}
							name={name}
							defaultValue={defaultValue}
							rules={rules}
							{...rest}
						/>
					);
				}}
			</ConnectForm>
```

**Comment by bluebill1049** [comment]
cool glad you worked it out youself.

**Comment by yec** [comment]
found another solution using submitCount, its much better.

**Comment by bluebill1049** [comment]
oh awesome! i forgot about that...
