### ISSUE TITLE
FieldArray add does not populate initial values 

### ISSUE THREAD

**Issue by eimerreis** [react-hook-form/react-hook-form#1314]
**Describe the bug**
I tried to create a table, where it's possible to add a new row, using the `useFieldArray` hook. For values coming into my component via props, this works fine.
Unfortunately, when I try to use the `append` method, and pass in a new object with some default values, the app breaks, because it seems like the object that I just passed to the `append` method is `undefined`.

I'm just guessing around that potentially, I'm using a weird combination of `ValidationSchema` + `defaultValues` + `useFieldArray` + `Controller`, which might be not what the lib is meant to handle.

**To Reproduce**
1. Go to this [Codesandbox](https://codesandbox.io/s/react-hook-form-issue-ltcgr)
2. Click on the 'Add' button in the upper right corner
3. See error

**Extended Weird Behaviour**
1. Click on the 'delete' button on the existing entry in the table
2. Clicking on 'add' will now populate the values from the license you just deleted
3. Clicking on 'add' a 2nd time, will crash the app like before.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-issue-ltcgr

**Expected behavior**
When clicking 'Add' a new entry should appear at the end of the table with default values populated.

**Desktop (please complete the following information):**
 - OS: mac OS Mojave 10.14.2
 - Browser Chrome
 - Version 80.0.3987.149

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report @eimerreis any chance you can provide a smaller and simpler codesandbox just to reveal the issue?

**Comment by eimerreis** [comment]
Wow! I'm buzzed you replied within 3 minutes 🚀 💪 . 
I removed unnecessary stuff from the codesandbox. https://codesandbox.io/s/react-hook-form-issue-ltcgr

**Comment by bluebill1049** [comment]
sweet. thanks i am working on a fix for the lib, i will take a look at your code soon. ❤️

**Comment by bluebill1049** [comment]
Is this what you after? https://codesandbox.io/s/react-hook-form-issue-c234n

**Comment by bluebill1049** [comment]
you can change the keyName by the way: https://react-hook-form.com/api#useFieldArray

**Comment by eimerreis** [comment]
I will adapt my app's code. Seems like this is what I looked for.

Will give you feedback once I put this into my code

**Comment by bluebill1049** [comment]
no worries :) let me know. how did you go.

**Comment by eimerreis** [comment]
Works as you suggested! 👍 

Remove also didn't work properly but we managed to fix this by having a look at #1208

**Comment by amirofy2002** [comment]
try using ref=_{register()}_
you missing =>  ()

**Comment by bluebill1049** [comment]
yea that's important @amirofy2002 thanks :)
