### ISSUE TITLE
Reset multiple input file does not work as excepted

### ISSUE THREAD

**Issue by opeah** [react-hook-form/react-hook-form#1316]
Hi @bluebill1049 

**Describe the bug**
Got a strange behavior when I have 2 or more file inputs and I want to reset one of these.
When I hit "reset" all file inputs are reseted.
```
reset({ ...getValues(), avatar: undefined })
```

**To Reproduce**
1. Create 2 file inputs
2. Reset one of these with reset function
3. All file inputs are reseted

**Codesandbox link (Required)**
https://codesandbox.io/s/icy-darkness-x90ec

**Expected behavior**
I excepted only the field with the name I passed into the reset function is reset.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.3
 - Browser: Chrome
 - Version: 83

**Comment by bluebill1049** [comment]
This is a tricky one. I would recommend not using `reset()` with input files. 

We are using native form HTML `reset` inside the hook, the moment its get invoked all input file reference will get removed. 

i would recommend the following: 

1. to use `setValue` to reset other fields. 
2. deep clone what's `getValues()` returns (i haven't tried that)

**Comment by bluebill1049** [comment]
Thanks for understanding @opeah and raise the issue. closing this issue now.

**Comment by opeah** [comment]
Thans @bluebill1049, will try this and keep you update.
