### ISSUE TITLE
Changing element and keeping the name don't get submitted

### ISSUE THREAD

**Issue by TiagoSousa26** [react-hook-form/react-hook-form#1317]
**Describe the bug**
Changing the type of the element and keeping the `name` doesn't show on the submitted values.
I have a field that depends on a condition to be an `input` or a `select` but it still has the same `name` it's only a different type. If I submit after changing the type of the element it's doesn't show on the submitted values.
Probably this is happening because it gets a different `ref` I guess...

**To Reproduce**
Steps to reproduce the behaviour:
1. Click "Add friend"
2. Add content to the fields
3. Click "Change Type"
4. Click "Submit"
4. Check the console and see that is missing the "lastName"
5. Click "Add friend"
6. Fill the fields
7. Click "Submit"
8. Check the console and it still doesn't have the one field on the first object but it has on the second object

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-array-fields-6uhre

**Expected behaviour**
After changing the type of the element and submitting it should appear on the values after submitting.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 80.0.3987.149

**Comment by bluebill1049** [comment]
have a read this FAQ: https://react-hook-form.com/faqs#Whyisdefaultvaluenotchangingcorrectlywithternaryoperator this will help.

**Comment by TiagoSousa26** [comment]
I did another sandbox with that example https://codesandbox.io/s/react-hook-form-faq-toggle-fields-ingvf
Now it gets the default value but doesn't get submitted. The only way is to give him a different `name` but it's the only way or I am missing something?
I also updated the first example to have keys and have the same behaviour.

**Comment by bluebill1049** [comment]
@TiagoSousa26 oh sorry i think i miss looked at your question. If you want the same name, then you will have to invoke `unregister` yourself (before the toggle).

**Comment by TiagoSousa26** [comment]
It worked thanks.
