### ISSUE TITLE
Validation errors don't appear

### ISSUE THREAD

**Issue by raunofreiberg** [react-hook-form/react-hook-form#1319]
**Describe the bug**
Validation errors don't appear when typing into the field. This is the minimal example provided in the README. I was hoping that validation would be possible when filling in the form, not only when submitting?

**Codesandbox link (Required)**
https://codesandbox.io/s/infallible-ritchie-q8ty0

**Expected behavior**
Validation errors should appear.

**Comment by raunofreiberg** [comment]
Okay. I found that `mode` is what I'm looking for: https://react-hook-form.com/api#useForm

Although, as a first time user of this library, I found it quite misleading when the Form Builder example had `onChange` validation, whereas by default `useForm` provides `onSubmit` validation 🙂

**Comment by raunofreiberg** [comment]
Also, with `mode: onChange`, is it possible to have validation errors appear when the user touches the field and blurs (would want to show that it is required)?

**Comment by bluebill1049** [comment]
Please take a look the form state: https://react-hook-form.com/api#formState
