### ISSUE TITLE
Can't watch nested fields when objects are returned from component inside Controller

### ISSUE THREAD

**Issue by neopostmodern** [react-hook-form/react-hook-form#1320]
**Describe the bug**
When a component inside a `Controller` returns an object to `onChange` the data gets stored correctly, but the properties of this object can't be watched.

**To Reproduce**
1. Go to https://kv7cv.csb.app/
2. Edit the field named "native" and observe how it updates when it's watched
3. Edit the field named "nested"
4. If watching a property of 'nested' directly, it doesn't update – only if watching the entire nested object and then selecting a sub-property (which is AFAIC very inefficient, plus annoying code)

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-kv7cv

**Desktop**
 - OS: macOS
 - Browser: Chrome
 - Version: 80
*not tested in other browsers / on other platforms but seems very unlikely to be related*

**Additional context**
I want to build large, nested forms which need to be re-composable and often repeat themselves. I've therefore tried to separate individual components. I'd like to be interoperable with other form system (maybe someone needs these components in a non-react-hook-form project) so I don't want to pass RHF specifics around. Using `Controller` and `onChange` to return large chunks seemed like a good solution for this.

Related: https://github.com/react-hook-form/react-hook-form/issues/314 (wasn't resolved but I think this behaviour has actually been fixed since; just watching the parent object isn't good enough in my scenario since the parent object might have ~hundreds of properties I don't want to watch)

**Comment by bluebill1049** [comment]
`watch` can only subscribe to the input which is registered. The component inside your controller is not `reigstered`. That's why it's not working. We don't support and simply can't make it work for such usage.

**Comment by neopostmodern** [comment]
Okay – that's of course bad for me, but understandable. Are you aware of any good workarounds for this (besides simply watching the parent object)?

**Comment by bluebill1049** [comment]
consider build a custom controlled component (which contains your nested inputs) and wrapped with Controller.

`<Controller as={CustomComponent} name="test" />`

`CustomComponent` will return a nested object as return data.

**Comment by neopostmodern** [comment]
Sure, that's what I've been doing (and getting and submitting the data works completely find) – the question is how to efficiently (without unnecessaries re-render because an unrelated property changed) watch properties of the nested component.
E.g. say the `CustomComponent` you define above returns an object with an ID field and then also dozens of other properties, some of which are maybe arrays et cetera – how can I make sure I only re-render when ID field of CustomComponent (i.e. `test.ID`) changed and not any other component.

I understand and respect it's not within the scope of this project, I just wondered whether you were aware of any good workaround?

**Comment by bluebill1049** [comment]
thanks for understanding. let's continue the discussion here or perhaps send a question at spectrum.
Controller will isolate re-render within, so I don't think you have to worry about your root/form gets re-rendered. Ideally, you should have each input registered separately, but I understand this must be your requirement. The idea is basically to build your component like react-select, and let the Controller isolate the re-render within.
