### ISSUE TITLE
Provide more granular control of when validation gets triggered

### ISSUE THREAD

**Issue by wrporter** [react-hook-form/react-hook-form#1321]
**Is your feature request related to a problem? Please describe.**
There are currently 3 `mode`s for triggering validation on a form: `onSubmit`, `onBlur`, and `onChange`. It is a common best practice in UX to perform validation onChange with a debounce period (something like 400 milliseconds) as well as onBlur, therefore providing the user with timely feedback. This is currently not possible with the limited controls for when to perform validation.

**Describe the solution you'd like**
Perhaps the `mode` can also be a function that allows the consumer to configure when the validation should occur.

**Comment by bluebill1049** [comment]
>  It is a common best practice in UX to perform validation onChange with a debounce period (something like 400 milliseconds) as well as onBlur, therefore providing the user with timely feedback. 

Do you have a reference for that?

At the stage, we are not looking for a change for `mode`.

**Comment by wrporter** [comment]
@bluebill1049 Here below a few resources. Based on research, it is best to have a combination of validation triggers:

1. When the form is submitted (`onSubmit`).
2. When the user leaves a field (`onBlur`).
3. A delay after the user has stopped typing (`onChange` with a delay -- research shows that good delays range between 400 milliseconds to 1 second).

From [UX Planet](https://uxplanet.org/designing-more-efficient-forms-assistance-and-validation-f26a5241199d):

> Users dislike when they go through the process of filling out a form only to find out at submission, that they’ve made an error. The right time to inform about the success/failure of provided data is right after the user has submitted the information. Real-time inline validation immediately informs users about the correctness of provided data. This approach allows users to correct the errors they make faster without having to wait until they press the submit button to see the errors.

> However avoid validating on each keystroke because in most cases you simply cannot validate until someone has finished typing their answer.

From [designmodo](https://designmodo.com/ux-form-validation/):

> Inline form validation that immediately informs users about the correctness of provided data results in an increase in the conversion rate.

From [designer Andrew Burton](https://medium.com/@andrew.burton/form-validation-best-practices-8e3bec7d0549):

>  the most commonly used moments to display validation are, instantly, and once a page has been submitted.

> When using instant validation display messages after the user has input answers [with a delay]

From a [Baymard Institute UX Research Article](https://baymard.com/blog/inline-form-validation):

> For most field types, the validity may be checked once the user leaves the field (by binding to the onblur event of the field).

From a [UX design series sponsored by Adobe](https://www.smashingmagazine.com/2018/08/best-practices-for-mobile-form-design/):

> The time at which you choose to display an error message is vital. Seeing an error message only after pressing the submit button might frustrate users. Don’t wait until users finish the form; provide feedback as data is being entered.

> Use inline validation with real-time feedback. This validation instantly tells people whether the information they’ve typed is compatible with the form’s requirements. In 2009, [Luke Wroblewski tested inline validation](https://alistapart.com/article/inline-validation-in-web-forms/) against post-submission validation and found the following results for the inline version:
> - 22% increase in success rate,
> - 22% decrease in errors made,
> - 31% increase in satisfaction rating,
> - 42% decrease in completion times,
> - 47% decrease in the number of eye fixations.

> Don’t validate after each character typed.
This approach not only increases the number of unnecessary validation attempts, but it also frustrates users (because users will likely see error messages before they have completed the field). Ideally, inline validation messages should appear around 500 to 1000 milliseconds after the user has stopped typing or after they’ve moved to the next field.

**Comment by bluebill1049** [comment]
That's some really useful information. I will take a read on it and consider the change. thanks.

**Comment by theghostbel** [comment]
Do you know working examples that implement triggering validation when "stopped typing"?

**Comment by bluebill1049** [comment]
I think we probably don't need an additional `mode` here. rather a new attribute to delay the error message from showing before the user completes their input.

eg

```tsx
useForm({
  delayUserError: 500,
})
```
