### ISSUE TITLE
github issue template can include links to CSB boilerplate / templates

### ISSUE THREAD

**Issue by ilovett** [react-hook-form/react-hook-form#1323]
**Is your feature request related to a problem? Please describe.**
When creating an issue, would be nice to make it easier to describe the issue with a codesandbox link directly in the template.

**Describe the solution you'd like**
Add a link to a basic CSB form with all boilerplate setup, or perhaps a link to a list of different boilerplate templates to choose from EG: controlled vs. uncontrolled vs. field array vs. wizard

**Comment by bluebill1049** [comment]
Awesome idea!
