### ISSUE TITLE
In validateCriteriaMode: "all" and mode: "onChange" errors do not refresh correctly

### ISSUE THREAD

**Issue by gzdunek** [react-hook-form/react-hook-form#1325]
**Describe the bug**
In validateCriteriaMode: "all" and mode: "onChange" errors do not refresh correctly.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-errormessage-multiple-error-messages-3651q
2. Click on on input field in browser
3. Type "1234g" into input
4. Only "This input exceed maxLength" error is visible. 
5. Click on Submit button.
6. Now "This input is number only" error is also visible.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-errormessage-multiple-error-messages-3651q

**Expected behavior**
Errors should appear automatically after setting validateCriteriaMode: "all" and mode: "onChange".

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser:  #Chrome
 - Version 80

**Additional context**
If you place watch(); in component body validation works correctly.

**Similar to**
#903

**Comment by bluebill1049** [comment]
There is no issue around this one.
try `123g`

- maxLength is 3 
- and pattern is number only.

**Comment by bluebill1049** [comment]
sorry for the back and forwards. issue confirmed.

**Comment by bluebill1049** [comment]
fixed: https://codesandbox.io/s/react-hook-form-errormessage-multiple-error-messages-0e909
