### ISSUE TITLE
Controlled input passed as a render fn is blurred if it's watched

### ISSUE THREAD

**Issue by sanohin** [react-hook-form/react-hook-form#1331]
**Describe the bug**
If you use Controller and pass a render function to `as` property, and `watch` for this field, the input will be blurred while typing.

**To Reproduce**
1. Focus first field
2. Type a char
3. Observe the input is blurred

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-get-started-tj2cs

**Expected behavior**
Expected the field not to be blurred like the second field in codesandbox.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome 80
 - Version: 5.2.0

**Comment by bluebill1049** [comment]
Thanks for the issue report. We don't support such usage as render props at the moment.
