### ISSUE TITLE
Watch does not return default value

### ISSUE THREAD

**Issue by sanohin** [react-hook-form/react-hook-form#1332]
**Describe the bug**
`watch` function does not return the default value passed to a component.

**To Reproduce**
1. Create a component with some default value
2. Watch the field
3. Observe that default value is not returned (component is not updated)

**Codesandbox link (Required)**
I forked an example from here https://react-hook-form.com/advanced-usage#ConditionalControlledComponent and just added default value:

**https://codesandbox.io/s/react-hook-form-get-started-elj60**

**Expected behavior**
Expected to return default value as well, not only to update on value change. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome 80
 - Version: 5.2.0

**Comment by bluebill1049** [comment]
thanks for the issue report. but please read the doc https://react-hook-form.com/api#watch
the first two dot points.

**Comment by bluebill1049** [comment]
> sir, when I have defaultValues and defaultValue, doc says it shud return defaultValue if provided over defaultValueS, but this not the case on render useEffect is still using defaultValueS

Honestly, I would suggest using either not all. In the future major version, we may consider depreciate or remove the inline `defautlVaue`
