### ISSUE TITLE
nested field array `remove` at index out of sync

### ISSUE THREAD

**Issue by ilovett** [react-hook-form/react-hook-form#1334]
**Describe the bug**

`remove(lastIndex)` doesnt seem to remove the expected field created with `useFieldArray` -- not sure if its due to examples nested array.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-template-7iwer
2. In set 0, click append twice
3. Edit set at index 1
4. Click "Remove @ 2"
5. Observe index 1 removed

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-usefieldarray-template-7iwer

**Expected behavior**

Index 2 removed

**Screenshots**

![2020-04-03 11 53 52](https://user-images.githubusercontent.com/1776100/78395272-065aff00-75a2-11ea-99ab-1b48811a24f7.gif)

**Desktop (please complete the following information):**

osx chrome 80.0.3987.149

the item does have `key={field.id}`

**Comment by bluebill1049** [comment]
hey @ilovett I think there is a fix coming for this already. Take a look this CSB: 
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-x7btr

**Comment by ilovett** [comment]
@bluebill1049 I took that CSB and switched to hardcoded by removing use of `FieldArray`, defining `name` in parent but still using `NestedFieldArray` with useFieldArray:

https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-dedmh

But I am unable to reproduce!  So it must be a bug in my CSB.

**Comment by bluebill1049** [comment]
aha because my CSB have the latest code. all good i will release the update today 🥂
