### ISSUE TITLE
mode: 'onBlur' does not trigger validation for required radio inputs

### ISSUE THREAD

**Issue by ErikAGriffin** [react-hook-form/react-hook-form#1335]
**Describe the bug**
When using the 'onBlur' mode for the form, the formState does not become valid until all fields have been blurred and without errors.  Radio inputs are not triggering validation when they are blurred or selected, unless 'onChange' mode is used which is altogether different.

Now, this would not always be a problem because a required radio input is clear in that if it is not selected and the user submits a form, the submission also triggers validation for the radio field and shows errors.

However in my specific use case the Submit button is disabled until the form is valid.  However the form never becomes valid because clicking the radio inputs doesn't trigger their validation.  The only way around this is to manually attach an onClick method to the inputs and `triggerValidation`.  However this should be unnecessary.

**To Reproduce**
[Visit this Sandbox](https://codesandbox.io/s/react-hook-radio-validation-elm1p)
All fields are required. Button is disabled until `formState.isValid`

1. Fill in all fields
2. Select a radio option
3. Try to submit form

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-radio-validation-elm1p

**Expected behavior**
Selecting the a radio option in onBlur mode should trigger validation for that field.

**Screenshots**
![image](https://user-images.githubusercontent.com/10357979/78397414-6bb4ed00-75ae-11ea-9e7f-71357616ddb5.png)

**Desktop (please complete the following information):**
 - Browser Chrome

**Comment by bluebill1049** [comment]
hey @ErikAGriffin that's expected behavior. you have to click and blur to trigger the validation.

**Comment by ErikAGriffin** [comment]
That would be fine, then one would only have to add the onClick handler to radio elements that appear last in a form.

However clicking then blurring still does not trigger the validation. See the attached Sandbox @bluebill1049

**Comment by bluebill1049** [comment]
> However clicking then blurring still does not trigger the validation. See the attached Sandbox @bluebill1049

Oh! really? i will take a look

**Comment by bluebill1049** [comment]
works for me, which browser are you on?

**Comment by ErikAGriffin** [comment]
Hmm apologies now works for me too.. but wasn't doing so in development.  I can look to see what's different between my environment and the sandbox I created

**Comment by ErikAGriffin** [comment]
For anyone visiting this post in the future, make sure when styling your custom radio/checkbox inputs that you are not hiding the actual `input` element with `visibility: hidden;` or `display: none;`

Instead set the opacity to zero and the blurring of the radio element will still be triggered

**Comment by bluebill1049** [comment]
Thanks @ErikAGriffin I have made an improvement on toggle registration, you may want to take a look at the latest version. Doing ref compare now :)
