### ISSUE TITLE
keystroke lagging

### ISSUE THREAD

**Issue by ahmdtalat** [react-hook-form/react-hook-form#1340]
Please consider asking the question at our spectrum channel.

https://spectrum.chat/react-hook-form

**After submitting the form, trying to resolve the issues, the first keystroke is not responding.**

**To Reproduce**
1. Go to a form.
2. Click Submit with empty fields.
3. when you enter a value, the first keystroke on a keyboard does not take action.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/faqs#Whyisfirstkeystrokeisnotworking
