### ISSUE TITLE
Lint task isn't checking `.tsx` files, and `controller.tsx` has exhaustive-deps issues.

### ISSUE THREAD

**Issue by threehams** [react-hook-form/react-hook-form#1341]
**Describe the bug**
The `lint:check` task in package.json is missing the .tsx extension. Because of this, there are unreported errors in controller.tsx for the exhaustive-deps rule.

The fixes are simple enough, but I don't feel confident making the changes necessary, as I don't know if the library (or some users) are relying on some of the current behavior. Dependencies can be stale in production in some cases.

**To Reproduce**
1. Run `yarn lint:check`
2. Run `npx eslint ./src/controller.tsx`

**Codesandbox link (Required)**
Sorry, this one's dev only and not present in the final build.

**Expected behavior**
The lint task checks all files, and no issues are reported.

**Comment by bluebill1049** [comment]
good one! thanks @threehams i will fix this one today.

**Comment by bluebill1049** [comment]
There will be no breaking change for the fix.
