### ISSUE TITLE
Unified structure for fieldArray items

### ISSUE THREAD

**Issue by jgullstr** [react-hook-form/react-hook-form#1344]
**Is your feature request related to a problem? Please describe.**
Currently, field array items have different structures depending on value type. In appendId(), the generated key is added as a property to the actual value if it is an object, otherwise a new object with separate properties for value and key is used. The first method causes conflicts if the key already exists in the original value, which is mitigated by useFieldArrays "fieldKey" parameter. The defaultValue for "flat" fields is now found in _item.value_ while in object fields its _item_ itself, which can be confusing.

**Describe the solution you'd like**
Use the second structure for both objects and non-objects, ie:

`{ key /* generated field key */ , value /* default value, object or not */ } = item`

Then, there would be no need for the fieldKey parameter, and the structure for all types of field array values would be identical and easier to reason about.

**Additional context**
This would be a breaking change, but might be something to consider for next major version.

**Comment by bluebill1049** [comment]
thanks @jgullstr can you provide some code example?

**Comment by jgullstr** [comment]
@bluebill1049 Thanks for your quick reply, hopefully this makes clear what I'm thinking:

#### Current implementation, array of objects.
```es6
function App() {
  const { register, handleSubmit, control } = useForm({
    defaultValues: {
      test: [{ id: "Bill" }]
    }
  });

  const { fields } = useFieldArray({ control, name: "test", fieldKey: "somethingElse" });
  const onSubmit = data => console.log("data", data);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      {fields.map((item, index) => ( // item = { id: "Bill", somethingElse: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx }
        <input
          key={item.somethingElse}
          name={`test[${index}].id`}
          defaultValue={item.id}
          ref={register()}
        />
      ))}
      <input type="submit" />
    </form>
  );
}
```
#### Current implementation, array of inputs.
```es6
function App() {
  const { register, handleSubmit, control } = useForm({
    defaultValues: {
      test: ["Bill"]
    }
  });

  const { fields } = useFieldArray({
    control,
    name: "test",
  });
  const onSubmit = data => console.log("data", data);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      {fields.map(({ id, value }, index) => { // id = xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx, value="Bill"
        return (
          <input
            key={id}
            name={`test[${index}]`}
            defaultValue={value}
            ref={register()}
          />
        );
      })}
      <input type="submit" />
    </form>
  );
}
```

#### What I would prefer, array of objects.
```es6
function App() {
  const { register, handleSubmit, control } = useForm({
    defaultValues: {
      test: [{ id: "Bill" }]
    }
  });

  const { fields } = useFieldArray({
    control,
    name: "test"
  }); // No fieldKey needed
  const onSubmit = data => console.log("data", data);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      {fields.map(({ id, value }, index) => ( // id = xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx, value = { id: "Bill" }
        <input
          key={id} // fieldKey never needs to change, easier to use. Identical to how array of flat inputs work now.
          name={`test[${index}].id`}
          defaultValue={value.id}
          ref={register()}
        />
      ))}
      <input type="submit" />
    </form>
  );
}
```

**Comment by bluebill1049** [comment]
Thanks. make sense now. will take consideration of the next major version. 👍
