### ISSUE TITLE
useFieldArray: TypeError: data.slice is not a function

### ISSUE THREAD

**Issue by dominikzogg** [react-hook-form/react-hook-form#1348]
**Describe the bug**
 All multiple elements (useFieldArray) and remove them, the first work, but the second click leads to the following error message:

```
TypeError: data.slice is not a function
removeAt
node_modules/react-hook-form/dist/react-hook-form.es.js:1438
```

**To Reproduce**
1. Create a form with useFieldArray
2. append({})
3. append({})
4. remove(1)
5. remove(0)

https://codesandbox.io/s/react-hook-form-usefieldarray-1qmyt
https://github.com/chubbyphp/petstore-react/blob/tailwind-css/src/Component/Form/PetForm.tsx

**Expected behavior**
Element gets removed without any issue.

**Desktop (please complete the following information):**
 - OS Ubuntu 19.10
 - Browser Firefox
 - Version 74

**Comment by bluebill1049** [comment]
<img width="726" alt="Screen Shot 2020-04-06 at 7 32 22 am" src="https://user-images.githubusercontent.com/10513364/78510490-c893eb80-77d8-11ea-9ec6-bbeb96547552.png">

follow the temple plz.

**Comment by dominikzogg** [comment]
done, works in the sandbox, the same form...

**Comment by bluebill1049** [comment]
hey @dominikzogg thanks for the update. are you using the same version?

**Comment by dominikzogg** [comment]
@bluebill1049 now its also failing, good catch

**Comment by bluebill1049** [comment]
so which one is working and failing?

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#useFieldArray

i think it's due to this:

`register={register()}`

**Comment by dominikzogg** [comment]
the one with the original dependencies (documentation) worked, the one with my (more up2date) onces, does not

**Comment by dominikzogg** [comment]
thats the issue, any idea, why this worked in the older version?

**Comment by bluebill1049** [comment]
It's safer this way, the order version we doing a comparison inside.

**Comment by Bharateshwar** [comment]
Hi, I'm facing the same issue , data.splice is not a function. 
I'm using material ui's TetField with useFiledArray ... so I had to use control from useForm(). ... so as per my knowledge there's no way to pass register() ... help please?

**Comment by bluebill1049** [comment]
are you using Controller @Bharateshwar ?

**Comment by Bharateshwar** [comment]
Yes I am

**Comment by bluebill1049** [comment]
share a codesandbox with your problem and keep it simple.

**Comment by Bharateshwar** [comment]
can u have a look at this .. and tell me if there's a problem in this?
`{fields.map((locationInput, index) => {

                return (<Controller as={TextField} control={control} name={`ServiceProviderAddress[${index}]`} key={locationInput.id}        
                    
                    InputProps={{
                        endAdornment: <InputAdornment position="end">
                            <IconButton onClick={() => {
                                remove(index)
                            }}>
                                <BackspaceIcon color="error" />
                            </IconButton>
                        </InputAdornment>,
                    }}
                />)

            })}`

**Comment by bluebill1049** [comment]
What's this InputProps? looks fine to me except without `defaultValue`.

**Comment by Bharateshwar** [comment]
InputProps .. just a kinda prop that comes with TextField from material-ui .. and even with defaultvalue the error is there ... 

I've created a new issue .. #1450 please have a look at the sandbox over there

**Comment by bhojakRahul13** [comment]
Unhandled Rejection (TypeError): displayCompanyData.slice(...).take is not a function 

import React, { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Container, Col, Table } from "react-bootstrap";
import axios from "axios";

import {
  companyData,
  filterCompanyAction,
  selectAllCompanyAction,
  selectCompanyAction,
} from "../store/action/companyDataAction";

import _ from "lodash";

const CompanyTable = () => {
  const dispatch = useDispatch();
  const [status, setStatus] = useState("");
  const displayCompanyData = useSelector((state) => state.company.compnameData);
  const [paginated, setPaginated] = useState();
  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 10;

  useEffect(() => {
    const loadCompanyDatas = async () => {
      const { data } = await axios.get(
        "https://random-data-api.com/api/company/random_company?size=100"
      );
      const CompanyData = data.map((item) => ({
        isSelected: false,
        ...item,
      }));
      setPaginated(_(displayCompanyData.slice(0).take(pageSize).value));
      dispatch(companyData(CompanyData));
    };

    loadCompanyDatas();
  }, []);
  console.log("paginatedData=======", paginated);

  const pageCount = displayCompanyData
    ? Math.ceil(displayCompanyData.length / pageSize)
    : 0;

  if (pageCount === 1) return null;
  const pages = _.range(1, pageCount + 1);

  const HandleCheckAll = () => {
    dispatch(selectAllCompanyAction());
  };

  const HandleSingleCheck = (id) => {
    dispatch(selectCompanyAction(id));
  };

  const handleChangeDropdwon = async (event) => {
    await setStatus(event.target.value);
    // dispatch(filterCompanyAction({ status: event.target.value }));

    // dispatch(setClaimsUnfetchedaction());
  };

  const pagination = (pageNo) => {
    setCurrentPage(pageNo);
    const startIndex = (pageNo - 1) * pageSize;
    const paginatedDatas = _(displayCompanyData)
      .slice(startIndex)
      .take(pageSize).value;
    setPaginated(paginatedDatas);
  };
  return (
    <>
      <div>
        <Container fluid style={{ margin: 0 }}>
          <Col style={{ textAlign: "end", height: 50, marginTop: 12 }}>
            <select
              style={{ height: 30 }}
              value={status}
              onChange={handleChangeDropdwon}
            >
              <option default value="">
                Search Type
              </option>
              <option value="All">All</option>
              <option value="Business_Name">Business Name</option>
              <option value="EmployeIdentificationNumber">
                employee Identification Number
              </option>{" "}
              <option value="Address">Address</option>
              <option value="Industry">Industry</option>
            </select>
          </Col>
        </Container>
        <Container fluid style={{ margin: 0, padding: 0, height: "434px" }}>
          <Table
            style={{ height: "500px" }}
            className="company-table"
            size="sm"
            striped
            bordered
            hover
            responsive
          >
            <thead>
              <tr>
                <th width="3%" style={{ textAlign: "center" }}>
                  <input
                    type="checkbox"
                    id="checkboxAll"
                    onClick={HandleCheckAll}
                  />
                </th>

                <th width="25%">Full Name</th>
                <th width="20%">Employee Identification Number</th>
                <th>Type</th>
                <th width="14%"> Phone Number</th>
                <th>Full Address </th>
              </tr>
            </thead>

            <tbody>
              {displayCompanyData?.map((company, index) => {
                return (
                  <tr key={index}>
                    <td style={{ textAlign: "center", paddingTop: 20 }}>
                      <input
                        type="checkbox"
                        checked={company.isSelected}
                        onClick={(e) => HandleSingleCheck(company.id)}
                      />
                    </td>

                    <td style={{ display: "flex" }}>
                      <img
                        src={company.logo}
                        alt="Avatar"
                        rouing="true"
                        style={{
                          verticalAlign: "middle",
                          width: 30,
                          height: 30,
                          marginRight: 12,
                          textAlign: "center",
                          marginTop: 12,
                          borderRadius: "50%",
                        }}
                      />
                      <p>
                        <span>{company.business_name}</span>
                        <br />
                        <span>{company.industry}</span>
                      </p>
                    </td>

                    <td>{company.employee_identification_number}</td>
                    <td>{company.type}</td>
                    <td>{company.phone_number}</td>
                    <td>{company.full_address}</td>
                  </tr>
                );
              })}
            </tbody>
          </Table>
          <nav className="d-flex justify-content-left mt-4 ml-3">
            <ul className="pagination">
              {pages.map((page, index) => (
                <li
                  className={
                    page === currentPage ? "page-item active " : "page-item"
                  }
                  key={index}
                >
                  <p
                    className="page-link"
                    onClick={(e) => {
                      pagination(page);
                    }}
                  >
                    {page}
                  </p>
                </li>
              ))}
            </ul>
          </nav>
        </Container>
        <Container></Container>
      </div>
    </>
  );
};

export default CompanyTable;
``
