### ISSUE TITLE
triggerValidation bug

### ISSUE THREAD

**Issue by ArtemAstakhov** [react-hook-form/react-hook-form#1349]
**Describe the bug**
triggerValidation method doesn't validate fields if payload is undefined

**To Reproduce**
1. reset invalid fields with new valid values
2. triggerValidation

https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-9kk6p

**Expected behavior**
triggerValidation() validates fields as triggerValidation([...propertiesArray])

**Desktop (please complete the following information)**
MacOS 10.15.2
Chrome
80.0.3987.163

**Comment by bluebill1049** [comment]
your inputs haven't even hit render with register 

https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-e69s3

**Comment by ArtemAstakhov** [comment]
@bluebill1049 oh, I got it. How would you recommend to wait for all fields register to do this trick with reset and validate dynamic data?  Except setTimeout

**Comment by bluebill1049** [comment]
you can use setValue instead: https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-e69s3
