### ISSUE TITLE
What is the best practice to update internal logic of controlled component ?

### ISSUE THREAD

**Issue by gamegee** [react-hook-form/react-hook-form#1350]
**What is the best practice to update internal logic of controlled component ?**  

I would like to update some internal component logic based on the "controlled" value.  

I can get this value using `getValues` from `control`, but of course the component is no re-rendered on control changes. I would like to know what is the best practices to add such internal logic with `react-hook-form`  

Is there a way without using `watch` ?

**[Sandbox link](https://codesandbox.io/s/react-hook-form-useform-template-lpv0b)**   

**Info on code snippet :**  

I would like to re-compute the function `isChecked` when the controlled value change.
The function `isChecked` is responsible to disable checkboxes when the number of checked is higher than the `minSelected` value

**Comment by bluebill1049** [comment]
I would build a component to host those internal logic within and let the `Controller` to collect the data.

https://react-hook-form.com/api#Controller
