### ISSUE TITLE
My onChange using react hook form and Cleavee returns [SyntheticEvent]

### ISSUE THREAD

**Issue by MatheusLuiz2000** [react-hook-form/react-hook-form#1352]
Hey!!

I trying to recive the value of input with the onChange but always return with a SyntheticEvent, i am using the control (React Hook Form).

here is my SandBox to check the error...

Thanks for help!! <3

https://codesandbox.io/s/hardcore-tu-6x9t5?from-embed

**Comment by bluebill1049** [comment]
take a look this thread: https://spectrum.chat/react-hook-form/help/cant-get-rhf-to-work-with-material-ui-ans-cleave-js~df5e60fa-b008-48c4-89eb-0e75e23a932a

**Comment by MatheusLuiz2000** [comment]
Bill, i'am sorry but i didn't understand how can this thread can help my problem, because the solution of the this problem is use Controller of React-Hook-Form, but in the example of CodeSandBox, i already using and the onChange returns "Synthetic Event"... Can you have some example with Controller and onChange that not return error of Synthetic Event?

**Comment by bluebill1049** [comment]
Yeah, you should use `Controller`

**Comment by MatheusLuiz2000** [comment]
But bill, in my example i am using Controller, you can see here

https://codesandbox.io/s/hardcore-tu-6x9t5?from-embed.

In the file InputController, you can see that i am using Controller with a custom Input but the onChange don't works..

**Comment by bluebill1049** [comment]
That's not a Controller.

```
<InputCampos
        type="text"
        label="Razão Social"
        name="razao_social"
        control={control}
        onChange={testeChange}
        defaultValue={informacoesCliente ? informacoesCliente.razao_social : ""}
        opcoes={{
          delimiter: ""
        }}
        ref={register({ required: true })}
        erro={errors.razao_social ? errors.razao_social.message : ""}
      />
```

This is: https://react-hook-form.com/api#Controller

**Comment by MatheusLuiz2000** [comment]
But bill, i am using like a component, i remember that i show you how i did that in another issue that i have.. In the link of CodeSandBox is in the file "InputComponent.js"

```
<InputContainer className="input-group">
  <label
    htmlFor={props.name}
    error={props.erro ? "erro" : ""}
    className="label"
  >
    {props.label}
  </label>
  <Controller
    name={props.name}
    control={props.control}
    valueName={props.defaultValue}
    {...props}
    as={
      <Cleave
        erro_ativo={props.erro ? "ativo" : "inativo"}
        value={props.defaultValue}
        options={props.opcoes}
      />
    }
  />
  <small>{props.erro ? `${props.erro}` : ""}</small>
</InputContainer>
```

**Comment by bluebill1049** [comment]
can you update your codesandbox to use Controller first and we can go from there? what you had above in the code is on the right track.

**Comment by MatheusLuiz2000** [comment]
I update the code to Controller App.js and return the same synthethic event error.

Here the link:

https://codesandbox.io/s/angry-bash-n2xuw?file=/src/App.js

Thanks so much for the attention

**Comment by bluebill1049** [comment]
actually check out this one: https://codesandbox.io/s/morning-sunset-8n3sx

**Comment by MatheusLuiz2000** [comment]
AAAAAH, thanks a lot! It's work! I pass in the Cleave Component this code:

```
            onChange={e => {
              e.persist();
              onChange(e);
            }}
```

And works! But with 1 specfic problem! When i pass onChangename={name of input} and onChange, the Controller don't pick the news values, always continue the default
