### ISSUE TITLE
Get current input name with focus

### ISSUE THREAD

**Issue by Simply1993** [react-hook-form/react-hook-form#1357]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when can't get current input name with focus :)

**Describe the solution you'd like**
I'll be happy if you can add input name with current focus in formState. It help us for paste copied text in needed input field.

**Comment by Simply1993** [comment]
Or if I have way for get current input name with focus now, then can you tell me pls about it.

**Comment by bluebill1049** [comment]
you can vote thumb up on this issue if that's what you after as well.

https://github.com/react-hook-form/react-hook-form/issues/1312

**Comment by Simply1993** [comment]
Ops, thanks you.
Sure, I vote for it.
