### ISSUE TITLE
Yup conditional fields, useFieldArray is not updating

### ISSUE THREAD

**Issue by deebov** [react-hook-form/react-hook-form#1358]
**Describe the bug**
I have a couple of issues. 
1. useFieldArray is not working well with yup. 
I have a yup schema like this:

```javascript
  name: yup
    .array()
    .of(
      yup
        .string()
        .min(3, 'Company name is too short - should at be 3 chars minimum')
        .required(),
    )
    .max(3),
```
( Array of string that's 3 charaacters minimum )
If you debug the error you can see that errors of this field does not update well. Most of the time it gets updated after submitting the form

2. You need to type in several times  to update the value of Chakra UI NumberInputField 
If you scroll down a little there're two number inputs.

3. I get an undefined error upon submitting the form without filling the conditional fields which are not rendered.
here's the schema code for the conditional fields
```javascript
  hasBusinessAddress: yup.string().oneOf(["NO", "YES"]),
  address: yup.object().shape({
    line1: yup.string().when("hasBusinessAddress", {
      is: "YES",
      then: yup.string().required()
    }),
    line2: yup.string(),
    zipcode: yup.string().when("hasBusinessAddress", {
      is: "YES",
      then: yup.string().required()
    }),
    state: yup.string().when("hasBusinessAddress", {
      is: "YES",
      then: yup.string().required()
    }),
    country: yup.string().when("hasBusinessAddress", {
      is: "YES",
      then: yup.string().required()
    })
  })
```

**Codesandbox link (Required)**
https://codesandbox.io/s/vigorous-mccarthy-ro7e2?file=/src/schema.tsx:950-1527

**Desktop (please complete the following information):**
 - OS:  macOs Catalina 10.15.3
 - Browser: chrome
 - Version: 80.0.3987.149

**Additional context**
Also, I noticed that in errors don't get updated very well. e.g. you can check the errors with the yup schema

**Comment by bluebill1049** [comment]
can you please break the codesandbox into seperate issue? it's easier for me identify the problem.

**Comment by bluebill1049** [comment]
2. You need to type in several times to update the value of Chakra UI NumberInputField
If you scroll down a little there're two number inputs.

could be due to this: https://react-hook-form.com/faqs#Whyisfirstkeystrokeisnotworking

**Comment by bluebill1049** [comment]
In terms of Yup validation, we don't do anything special rather than just handle the data to Yup for validation. i will double check the validation schema.

**Comment by deebov** [comment]
> can you please break the codesandbox into seperate issue? it's easier for me identify the problem.

noted. doing it right now

**Comment by bluebill1049** [comment]
thanks a lot 👍

**Comment by deebov** [comment]
> thanks a lot 👍

for the first issue https://codesandbox.io/s/vigorous-mendel-ksxtn?file=/src/App.tsx

**Comment by bluebill1049** [comment]
> > thanks a lot 👍
> 
> for the first issue https://codesandbox.io/s/vigorous-mendel-ksxtn?file=/src/App.tsx

the submit date looks valid, can you get the data and valid against your schema.

**Comment by deebov** [comment]
for the second issue https://codesandbox.io/s/silly-shockley-nbrs0?file=/src/App.tsx

here, type once then focus out then focus in and try to type in

**Comment by deebov** [comment]
> > > thanks a lot 👍
> > 
> > 
> > for the first issue https://codesandbox.io/s/vigorous-mendel-ksxtn?file=/src/App.tsx
> 
> the submit date looks valid, can you get the data and valid against your schema?
> 
> <img alt="Screen Shot 2020-04-07 at 9 03 46 pm" width="687" src="https://user-images.githubusercontent.com/10513364/78662167-4bb95c80-7913-11ea-9cb1-9bd2094bfa00.png">
> 
> <img alt="Screen Shot 2020-04-07 at 9 03 39 pm" width="611" src="https://user-images.githubusercontent.com/10513364/78662177-4eb44d00-7913-11ea-9a96-6e9cfc190c9d.png">

![image](https://user-images.githubusercontent.com/28673719/78662539-03d20f80-78ea-11ea-83cd-dd4b301aef23.png)

name string must be 3 chars minimum. so in this case it still shows it as invalid

**Comment by bluebill1049** [comment]
> for the second issue https://codesandbox.io/s/silly-shockley-nbrs0?file=/src/App.tsx
> 
> here, type once then focus out then focus in and try to type in

I don't think this is a problem around RHF, but you can use Controller to solve this problem. https://react-hook-form.com/api#Controller

**Comment by deebov** [comment]
for the third issue https://codesandbox.io/s/adoring-haibt-uoojm?file=/src/schema.tsx

**Comment by bluebill1049** [comment]
> https://codesandbox.io/s/adoring-haibt-uoojm?file=/src/schema.tsx

can you remove those extra code please?

**Comment by deebov** [comment]
> > https://codesandbox.io/s/adoring-haibt-uoojm?file=/src/schema.tsx
> 
> can you remove those extra code please?

sorry, what exactly do you mean ? i think there's no extra code

**Comment by bluebill1049** [comment]
> > > https://codesandbox.io/s/adoring-haibt-uoojm?file=/src/schema.tsx
> > 
> > 
> > can you remove those extra code please?
> 
> sorry, what exactly do you mean ? i think there's no extra code

what i meant: https://codesandbox.io/s/delicate-https-on2v8?file=/src/App.tsx:905-925

**Comment by bluebill1049** [comment]
issue 3: is somewhere around your schema: https://codesandbox.io/s/delicate-https-on2v8?file=/src/App.tsx

**Comment by bluebill1049** [comment]
I will create an seperate issue on issue 1, will looking into and fix accordingly.

**Comment by deebov** [comment]
thank you very much

**Comment by bluebill1049** [comment]
thanks a lot @deebov for raising this bug: https://github.com/react-hook-form/react-hook-form/issues/1359

**Comment by bluebill1049** [comment]
let me know how did you go with the 

- Schema problem.
- Controller -> for number input

**Comment by deebov** [comment]
if solved the schema problem by adding `$` prefix like this:
```
    zipcode: yup.string().when('$hasBusinessAddress', {
      is: 'YES',
      then: yup.string().required(),
    }),
```

**Comment by bluebill1049** [comment]
here is the updated version for issue1: https://codesandbox.io/s/recursing-beaver-f64qt will release in the next patch.

**Comment by bluebill1049** [comment]
for issue 2: i think you may want to raise an issue at chakra-ui, or consider use Controller.

**Comment by deebov** [comment]
> https://codesandbox.io/s/recursing-beaver-f64qt

thank you. when do you plan to release it ?

**Comment by bluebill1049** [comment]
release happen over the weekend, cause i can't do much doing the weekday (have work to do) if you are in a hurry, i can always release a beta version for you

**Comment by deebov** [comment]
ah no. it's fine. we can wait until the weekend. thank you
