### ISSUE TITLE
`useArrayForm` should (allow to) return empty array as value

### ISSUE THREAD

**Issue by neopostmodern** [react-hook-form/react-hook-form#1362]
**Is your feature request related to a problem? Please describe.**
I have a lot of array fields in my form which are allowed to be empty (0 items). But the backend expects them to be empty arrays (`[]`), while RHF removes the field if it has 0 items.

**Describe the solution you'd like**
Ideally the usage of `useArrayField` would always and automatically set the field to `[]` when empty. If this is a downside for others / breaking, it would be nice to have an option for this.

**Describe alternatives you've considered**
I've tried to set a default value, but it didn't work.
```
    defaultValues: {
      name: "Peter",
      friends: []
    }
```

**Additional context**
Demo: https://pbyp0.csb.app/ ([Edit here](https://codesandbox.io/s/react-hook-form-usefieldarray-pbyp0?file=/src/index.tsx))
- hit `Submit` without adding a friend and the submitted value is `{ "name": "Peter" }` (I'd like `{ "name": "Peter", "friends": [] }` instead)
- add a friend, hit `Submit`, and the submitted value is `{ "name": "Peter", "friends": [ { "name": "Paul" } ] }` (as expected)
- hit `Delete` to remove the friend again and the submitted value is `{ "name": "Peter" }` (I'd like `{ "name": "Peter", "friends": [] }` instead)

**Comment by bluebill1049** [comment]
what about do a `useEffect` and `append` an empty filed.

**Comment by neopostmodern** [comment]
Do you mean like this? https://codesandbox.io/s/react-hook-form-usefieldarray-16y5u?file=/src/index.tsx:567-602
If yes, than it's not really suitable since it will show an empty input and then validation will fail on it. (Or put differently `[] != [{}]`)

**Comment by bluebill1049** [comment]
if that's not working out, then you probably have to do that on handleSubmit with a map function.

**Comment by neopostmodern** [comment]
Okay, that's unfortunate. Is there any way to get a list of registered `useFieldArray`s so I dynamically iterate over it in the `handleSubmit`?

**Comment by bluebill1049** [comment]
react hook form embrace uncontrolled input, and form state live inside inputs and that's why we have the ability to improve your form performance without re-render the entire form. At the same time, the form data's source of truth lives in the inputs as well. i believe this is consistent and correct behaviour for this lib.

**Comment by Yama-Tomo** [comment]
@bluebill1049 
I'm facing a similar problem.
I think it's unsafe to implement in typescript if the argument passed to `handleSubmit` is not included keys.

codesandbox: https://codesandbox.io/s/react-hook-form-usefieldarray-wjzx3
This code causes a runtime error if you click the send button when `friends` is empty.
(Unfortunately, the compiler does not output errors)

I think the property types in the argument passed to the `handleSubmit` should be nullable if array or, return an empty array passed as defaultValues.

Is there any other way?

**Comment by bluebill1049** [comment]
@Yama-Tomo V6 is coming this week: https://react-hook-form-website-git-v6.bluebill1049.now.sh/ts#SubmitHandler This should help.

**Comment by Yama-Tomo** [comment]
Thank you for response.

I think if you use array fields, it's a pain to use `SubmitHandler` every time since they are of a different type than `FormValues`.
Also It's not safe to say that it's up to the developer to use `SubmitHandler` or not.


For example, change the array type property of the data argument of `SubmitHandlers` to nullable using conditional type. etc...
Do you plan to support it with this package?

**Comment by bluebill1049** [comment]
>SubmitHandlers to nullable using conditional type
@Yama-Tomo can you give more detail on this one above?

CC: @kotarella1110

**Comment by Yama-Tomo** [comment]
@bluebill1049 Create a utility type that makes  only array nullable like this.

```typescript
type KnownKeyOf<T> = {
  [P in keyof T]: string extends P ? never : number extends P ? never : P;
} extends { [_ in keyof T]: infer Value }
  ? Value
  : never;

type KnownKeyValueOf<T> = Pick<T, KnownKeyOf<T>>;

type NotNullArrayTypePropertyNames<T> = {
  [P in keyof T]-?: T[P] extends Array<any> ? P : never;
} extends { [_ in keyof T]: infer Value }
  ? Value
  : never;

type ToNullableArrayProperties<T> = Partial<Pick<T, NotNullArrayTypePropertyNames<T>>>;
type PickNotArrayProperties<T> = Omit<T, NotNullArrayTypePropertyNames<T>>;

export type NullableArrayProperties<T> = ToNullableArrayProperties<KnownKeyValueOf<T>> &
  PickNotArrayProperties<KnownKeyValueOf<T>> &
  Omit<T, KnownKeyOf<T>>; // for { [key: string]: any }, { [key: number]: any }
```

usage

```typescript
type Result1 = NullableArrayProperties<{ foo: string; bar?: Array<number>; baz: Array<string> }>;
// Result1 => { foo: string; bar?: number; baz?: Array<string> }

// with `{ [key: string]: any }` signature
type Result2 = NullableArrayProperties<{
  foo: string;
  bar?: Array<number>;
  baz: Array<string>;
  [key: string]: any;
}>;
// Result2 => { foo: string; bar?: number; baz?: Array<string>; [key: string]: any }
````

Wrap to `UnpackNestedValue<TFieldValues>` with NullableArrayProperties.

https://github.com/react-hook-form/react-hook-form/blob/a5709440eb2e6a908110aea9ed473772ded5686a/src/types/form.ts#L51

　
Create a PR if needed 👍

**Comment by bluebill1049** [comment]
@Yama-Tomo please create a PR and let @kotarella1110 review. thanks

**Comment by kotarella1110** [comment]
If you want to use useFieldArray to empty `defaultValues`, you can work around this issue by making the FormValue property optional:

```ts
type FormValues = {
  name: string;
  nested?: {
    friends?: { name: string }[];
  };
};
```

[Codesandbox](https://codesandbox.io/s/react-hook-form-usefieldarray-7ci05)
