### ISSUE TITLE
isSubmitting does not update <Button loading={formState.isSubmitting}>

### ISSUE THREAD

**Issue by aress31** [react-hook-form/react-hook-form#1363]
**Describe the bug**
I have an issue with `formState.isSubmitting`.

I am using `controlled` fields and a `<Button>` component from the `react-native-elements` library that accepts a `loading` propriety to automatically change the style of the `<Button>` with a loading spinner.

However, although the value of `formState.isSubmitting` seems to be set to `true` when calling `handleSubmit` (I have traced its value with `console.log()`) the `<Button>` style does not change during the form submission.

**Codesandbox link (Required)**
I could not generate a sandbox for this issue but here is a snippet describing the issue:
```javascript
import React from "react";
import { useForm, Controller } from "react-hook-form";
import { KeyboardAvoidingView, View } from "react-native";
import { Button, Input } from "react-native-elements";

export default () => {
  const { handleSubmit, errors, control, formState } = useForm();
  const onSubmit = (data)=> {
    console.log(formState );
  };

  return (
    <View
      style={{
        alignSelf: "center",
        height: "100%",
        width: "100%"
      }}
    >
      <View
        style={{
          flex: 2,
          justifyContent: "center"
        }}
      >
        <KeyboardAvoidingView style={{ marginBottom: 16 }}>
          <Controller
            as={Input}
            autoCapitalize="none"
            autoCompleteType="email"
            containerStyle={{ marginBottom: 12 }}
            control={control}
            errorMessage={errors.email && errors.email.message}
            keyboardType="email-address"
            name="email"
            placeholder="Email Address"
            rules={{
              pattern: {
                message: "The email address format is invalid.",
                value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
              },
              required: {
                message: "This field is required.",
                value: true
              }
            }}
            onChange={args => args[0].nativeEvent.text}
          />
          <Button
            disabled={!formState.isValid}
            loading={formState.isSubmitting}
            title="RESET PASSWORD"
            type="solid"
            onPress={handleSubmit(onSubmit)}
          />
        </KeyboardAvoidingView>
      </View>
    </View>
  );
};
```

**Expected behavior**
On form submission, the value of `formState.isSubmitting` should be set to `true` and the style for the `<Button loading={formState.isSubmitting}>` from `react-native-elements` should get updated with the spinner.

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android R

**Comment by bluebill1049** [comment]
`const { handleSubmit, errors, control, formState: { isSubmitting } } = useForm();`

https://react-hook-form.com/api#formState

I think you miss the Proxy part which is in the doc.

**Comment by aress31** [comment]
@bluebill1049 thanks for your answer, indeed the documentation states that `Proxy` needs to get invoked or read before render to enable state update.

However, I am not sure how to use `Proxy` together with `react hook form`. Could you be kind enough to provide a working code snippet? And maybe adding it to the official documentation would help other people too.

**Comment by bluebill1049** [comment]
just read the value before the render, so RHF detects that you are reading those state and hence triggering re-render. the goal was try to avoid unnecessary calculation and re-render.

eg

`const { handleSubmit, errors, control, formState: { isSubmitting } } = useForm();`

instead of doing inside the `render`.

**Comment by aress31** [comment]
@bluebill1049 so I basically need to wrap `const { handleSubmit, errors, control, formState: { isSubmitting } } = useForm();` within a `useEffect()`. Again could you be kind enough to provide a minimal working code? :)

**Comment by bluebill1049** [comment]
not really with useEffect:

```
function Test() {
  const { handleSubmit, errors, control, formState: { isSubmitting } } = useForm();

  return {
    <div>{isSubmitting}</div>
  }
}

```

**Comment by aress31** [comment]
It is still not updating my `<Button>` component, I added this function to validate that `isSubmitting` is effectively set to `true` on a submit action:

```javascript
  React.useEffect(() => {
    console.log(`isSubmitting: ${isSubmitting}`);
  }, [isSubmitting]); 
```

and this is the console output:
```javascript
Running application on sdk_gphone_x86.
isSubmitting: false
isSubmitting: true
```
So the issue here I guess it is that the component does not get `rerendered` since, as far as I understand, RHF has been implemented in a way to avoid unnecessary rerenders, is there any workaround this?

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-useform-template-5e6tz?file=/src/index.js

**Comment by mixail-novikov** [comment]
@aress31 are you sure return Promise from onSubmit function? Or maybe API request is too fast, and you didn't notice the loading indicator? Try this snippet for a test.

```
const onSubmit = data => {
    return new Promise((resolve) => {
      setTimeout(() => resolve(), 1000);
    });
  };
```

**Comment by sgobotta** [comment]
Hi, I I've just ran into `react-hook-form` while looking for form libraries for my react-native application. Just like @aress31 I couldn't make the submit function work, probably because we're not even using a `<form>` element, though the `Controller` usage and form validation seems to be working fine, I'm pretty satisfied with it. Regarding the `handleSubmit` thing, I've tried a few workarounds but I can't get around it. This is maybe out of the scope of this issue, even this library, which (correct me if I'm wrong) it's not meant to be used in react-native applications. Anyway, this is an [**expo snack**](https://snack.expo.io/@wasabi/react-hook-form-snack) of the form I'm running tests on: `handleSubmit` doesn't seem to be answering the callback.

**Comment by JeromeDeLeon** [comment]
> @aress31 are you sure return Promise from onSubmit function? Or maybe API request is too fast, and you didn't notice the loading indicator? Try this snippet for a test.
> 
> ```
> const onSubmit = data => {
>     return new Promise((resolve) => {
>       setTimeout(() => resolve(), 1000);
>     });
>   };
> ```

Chiming in, using the suggestion @mixail-novikov works and that you made a mistake by passing `false` to `disabled` prop instead of `formState.isSubmitting`

```js
<Button
  disabled={false}
  onPress={handleSubmit(onSubmit)}
  title="RESET PASSWORD"
/>
```

I also tried the expo you provided @sgobotta and managed to get it worked with above solution.

**Comment by JeromeDeLeon** [comment]
```jsx
// submit handler
const onSubmit = data => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve();
    }, 3000);
  });
}

// submit button
<Button
  disabled={formState.isSubmitting}
  onPress={handleSubmit(onSubmit)}
  title="RESET PASSWORD"
/>
```

**Comment by sgobotta** [comment]
> ```js-jsx
> // submit handler
> const onSubmit = data => {
>   return new Promise((resolve) => {
>     setTimeout(() => {
>       resolve();
>     }, 3000);
>   });
> }
> 
> // submit button
> <Button
>   disabled={formState.isSubmitting}
>   onPress={handleSubmit(onSubmit)}
>   title="RESET PASSWORD"
> />
> ```

The code you shared does make sense, really, and I've used it in the example. But still, for some reason I can't get the timeout hooked during the submit action in the expo snack :grimacing:

**Comment by bluebill1049** [comment]
@sgobotta here you go: https://snack.expo.io/@bluebill1049/react-hook-form-snack

**Comment by bluebill1049** [comment]
Closing this issue as i have provided both CSB and Expo snack examples. feel free to follow up with more questions.

**Comment by aress31** [comment]
@bluebill1049, @mixail-novikov and @JeromeDeLeon thanks for your help, indeed the API fetch was just way to fast to appear on the screen but with the timer example I could see that the code is working as it should.

**Comment by bluebill1049** [comment]
awesome, glad it's working now.

**Comment by Lemaro86** [comment]
Just move your form into separate file - I got this error very often. 
Reason in lifecycle of FC

**Comment by nvmnghia** [comment]
> @aress31 are you sure return Promise from onSubmit function? Or maybe API request is too fast, and you didn't notice the loading indicator? Try this snippet for a test.
> 
> ```
> const onSubmit = data => {
>     return new Promise((resolve) => {
>       setTimeout(() => resolve(), 1000);
>     });
>   };
> ```

This should be mentioned in `formState.isSubmitting` docs.
