### ISSUE TITLE
Not working with @material-ui/pickers again

### ISSUE THREAD

**Issue by slykar** [react-hook-form/react-hook-form#1364]
I took an example from #373. It's not working with Material UI anymore.

Original example: https://codesandbox.io/s/vigorous-jones-pyee5
New react-hook-form version: https://codesandbox.io/s/exciting-lichterman-urx6g

The values are not updating for some reason.

**Comment by bluebill1049** [comment]
check your version. It's a major version upgrade from 3 -> 5. take a look Controller onChagne.

https://codesandbox.io/s/react-hook-form-controller-079xx
