### ISSUE TITLE
useFieldArray with remove action lead to watch return empty array on initial render

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#1366]
useFieldArray with remove action return empty array

codesandbox: 
https://codesandbox.io/s/issue-usefieldarray-watch-broken-v532-beta1-bwovf?file=/src/App.js

**steps:** 

1. click on remove 
2. inspect console

_Originally posted by @bluebill1049 in https://github.com/react-hook-form/react-hook-form/issues/1336#issuecomment-610665697_

**Comment by brayanL** [comment]
is there a solution?

**Comment by bluebill1049** [comment]
@brayanL this is already patched, will be in the next release
