### ISSUE TITLE
react-select in useFieldArray first element gets cleared 

### ISSUE THREAD

**Issue by deebov** [react-hook-form/react-hook-form#1369]
**Describe the bug**
if you remove any element below the first element then the first element gets cleared

**To Reproduce**
1. append a couple of select elements
2. remove any element below the first select input

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-hgu15?file=/src/index.js

**Comment by bluebill1049** [comment]
I think you are missing default value.

**Comment by deebov** [comment]
`defaultValues: { natureOfBusiness: [""] }`

**Comment by deebov** [comment]
but it's really odd. `defaultInputValue` set the default value. but I don;t want the first element get back to the default value when an element is removed

**Comment by bluebill1049** [comment]
you can try it out here with Controller: https://codesandbox.io/s/react-hook-form-usefieldarray-vy8fv

**Comment by deebov** [comment]
sorry, I think everything is clear in this CSB https://codesandbox.io/s/react-hook-form-controller-hgu15?file=/src/index.js
I am using Controller, with default value, with useFieldArray, no extra code

**Comment by deebov** [comment]
i noticed that react-relect returns an object instead of a value

**Comment by bluebill1049** [comment]
ha no worries, i am in a middle of work. otherwise probably can spot the issue for you.
