### ISSUE TITLE
How to handle Password fields? 

### ISSUE THREAD

**Issue by stephaniie2** [react-hook-form/react-hook-form#137]
**Describe the bug**
How to handle Password fields to check if value is same? 

**To Reproduce**
1. Input - PasswordOne = "secret"
2. Input - PasswordTwo = "secret"
3. Click on "Submit" - how to check that both inputs has same value?

**Expected behavior**
Password inputs show errors if either value doesn't match

**Comment by kilburn** [comment]
There are several ways to do this:

1. Capture the first password using `watch` into a `useRef` and then use that in the validation function for the second password.
    - [Using react-hook-form's "standard" validation](https://codesandbox.io/embed/react-hook-form-password-match-check-standard-validation-eo6en)
    - [Using native validation](https://codesandbox.io/embed/react-hook-form-native-validation-56h9c)

2. Use `validationSchema` with `yup` or similar.

3. It should be possible with an async `onSubmit` function too, but I haven't been able to make that work.

**Comment by bluebill1049** [comment]
thanks, @kilburn for the reply.

@stephaniie2 if you using standard validation, it's pretty easy.

```
const { register, watch } = useForm();

<input name="password1" ref={register} />
<input name="password2" ref={register({
  validate: (value) => {
    return value === watch('password1'); // value is from password2 and watch will return value from password1
  }
})} />
```
hope this make sense.

**Comment by bluebill1049** [comment]
hi @stephaniie2 how did you go with this question?

**Comment by bluebill1049** [comment]
going to close this issue, feel free to re-open and ask more questions.

**Comment by castiglionipaolo** [comment]
Hi @bluebill1049,

i tried the same exercise using controlled component (Controller and material UI textfield ) but it does not work. // the password do not match as password is undefined
 
here the example:
https://codesandbox.io/s/react-hook-form-password-match-check-controller-validation-sky3v

is it a bug or a missing feature or am I doing something wrong?
Thanks,
Paolo

**Comment by bluebill1049** [comment]
hi @castiglionipaolo can you fix your codesandbox first?

**Comment by castiglionipaolo** [comment]
> hi @castiglionipaolo can you fix your codesandbox first?

sure.

**Comment by castiglionipaolo** [comment]
> hi @castiglionipaolo can you fix your codesandbox first?

@Hi @bluebill1049 I fixed the codesandbox example.
Thanks

**Comment by bluebill1049** [comment]
here you go https://codesandbox.io/s/react-hook-form-password-match-check-controller-validation-w9o4g :)

**Comment by vaibhavdhawan** [comment]
Thanks Bill. 
Just tried the example. Console shows a warning - trying to change from uncontrolled to controlled?
I have seen the warning quite a few number of times when using MUI textfields , havent been able to pin point the reason.

**Comment by bluebill1049** [comment]
@vaibhavdhawan plz read the doc https://react-hook-form.com/api#useFieldArray about defaultValue

**Comment by eliezerbs9** [comment]
@bluebill1049 
Your answer solved my problem.
Thanks man :)

**Comment by NickToye** [comment]
Sorry to re-awaken this one but I'm struggling to get this to work.

What am I doing wrong?

[](https://codesandbox.io/s/reverent-mayer-4pbv5?file=/src/App.js)

I've verified with the console that my value and the one I'm watching are different yet it returns a true for the validation.

**Comment by reenan** [comment]
@bluebill1049 sorry to hijack this thread, but I'm facing one small detail with this example https://codesandbox.io/s/react-hook-form-password-match-check-controller-validation-w9o4g

Let's say you enter on "password" "12345678" and on "confirm password" you enter "123456789". It will show the invalid message, now if you focus on the "password" and add the "9" to it, the "confirm password" will still show the invalid message even though the values now match. Is there any way to overcome this and have a real-time update on both fields?

<img width="482" alt="Screenshot 2020-11-11 at 16 57 26" src="https://user-images.githubusercontent.com/13966837/98834003-fd3ae600-243e-11eb-8b3c-e5f7108a9d90.png">

**Comment by bluebill1049** [comment]
@reenan you can use trigger() to trigger the validation.

**Comment by reenan** [comment]
> @reenan you can use trigger() to trigger the validation. (I mean to trigger the input which contains the validation to check both input matches)

sorry, I should have specified a bit better, I'm using the "smart components" structure exposed via a dependency, meaning I don't have direct access to methods. I appreciate the answer Bill, I'll check what I can do there :)

**Comment by wildfrontend** [comment]
it is can be.wraper a function to split register object out component? 

like : https://codesandbox.io/s/react-hook-form-password-match-check-standard-validation-forked-nmbn2?file=/src/index.js

i find it look like not a good idea

**Comment by bluebill1049** [comment]
> it is can be.wraper a function to split register object out component?
> 
> like : https://codesandbox.io/s/react-hook-form-password-match-check-standard-validation-forked-nmbn2?file=/src/index.js
> 
> i find it look like not a good idea

if it works, why not :)

**Comment by Shelagh-Lewins** [comment]
Just in case anybody else is unsure how to use "trigger", this is how I revalidate the password repeat when the password field is updated (extending the Material UI  sandbox [https://codesandbox.io/s/react-hook-form-password-match-check-controller-validation-w9o4g?file=/src/index.js:802-817](https://codesandbox.io/s/react-hook-form-password-match-check-controller-validation-w9o4g?file=/src/index.js:802-817)).

```
const { errors, handleSubmit, control, getValues, trigger } = useForm({});

<Controller
        name="password"
        control={control}
        rules={{
            required: "You must specify a password",
            'validate': (value) => {
	        trigger('password_repeat');
                return true;
	    },
        }}
        as={<TextField name="password" type="password" variant="outlined" />}
 />
```
