### ISSUE TITLE
Type definition for watch method should support returning non-string values

### ISSUE THREAD

**Issue by lukevella** [react-hook-form/react-hook-form#1371]
**Is your feature request related to a problem? Please describe.**
Current type definition for watch is:

```ts
watch<T extends FieldName<FormValues>>(field: T & string, defaultValue?: string): FormValues[T]
```

However limiting `defaultValue` to just `string` results in false positive ts errors. For example if working with a checkbox, I would want to do:

```ts
const isEnabled = watch("myCheckbox", true)
// results in ts error because true is not a string
```

**Describe the solution you'd like**
I propose changing this to:

```ts
watch<T extends keyof FormValues>(field: T, defaultValue?: FormValues[T]): FormValues[T]
```

Reasons:
* Allows us to pass non-string values as `defaultValue` without getting ts errors.
* Ensures greater type safety since `field` will need to be an existing key in `FormValues`.
* Ensures that `defaultValue` is a valid type based on the given `field`.
* Falls back gracefully to looser types if `FormValues` is not explicitly defined.

**Comment by bluebill1049** [comment]
Thanks @lukevella for the awesome suggestion. I think we running into this problem before, because `watch` do support nest object and make types pretty hard to do:

eg:

`watch('test.firstName')`

but i agree `defaultValue` shouldn't be just `string`.

**Comment by bluebill1049** [comment]
hey @kotarella1110 i guess for now we wouldn't have a good solution to type this right? 

eg:
`watch('yourDetails.firstName')`

**Comment by bluebill1049** [comment]
what i can fix is default value not only support `string` tho.

**Comment by kotarella1110** [comment]
I will look into this later!

**Comment by bluebill1049** [comment]
oh cool thanks @kotarella1110 🙏

**Comment by lukevella** [comment]
Perhaps you can consider adding a new override:

```ts
watch<T extends keyof FormValues>(field: T, defaultValue?: FormValues[T]): FormValues[T]
watch<T extends unknown>(field: { path: string }, defaultValue?: T): T
```

Usage:

```ts
const firstName = watch<string>({ path: "test.firstName" }) // needs explicit type, otherwise it is unknown
const isEnabled = watch("isEnabled") // type can be inferred automatically
```

The idea here is that we need a way to distinguish between a path and a field name.

I appreciate that this is a breaking change. So alternatively this can be switched so that it doesn't break existing code.

```ts
watch<T extends keyof FormValues>(field: { name: T }, defaultValue?: FormValues[T]): FormValues[T]
watch<T extends unknown>(field: string, defaultValue?: T): T
```

**Comment by bluebill1049** [comment]
Thanks a lot for your suggestion and contribution @lukevella 🙏 hopefully we don't have to introduce a breaking change (if we can avoid).
