### ISSUE TITLE
do should make setValue trigger validation.

### ISSUE THREAD

**Issue by hieusmiths** [react-hook-form/react-hook-form#1374]
**Is your feature request related to a problem? Please describe.**
1. Make form with validateSchema.
2. Manip form then submit form and errors appear.
3. Make data and setValue.
4. setValue success but error not hidden.
5. Click submit button and all thing as well
> When setValue must check data and clear or set error.

Thank you read my issue.

**Comment by bluebill1049** [comment]
Please follow the template to have a codeSandBox.

**Comment by hieusmiths** [comment]
> Please follow the template to have a codeSandBox.
I fixed it by your register thank you.

Can you helpe me problem.
Now i'm make form and i deciced sparator n form. 
So i must onClick parent and use React forward ref to access children component method like below:

useImperativeHandle(ref, () => {
	return {
		onSubmit: () => handleSubmit(onSubmit)()
	}
});
It return promise, okey then i use async await but it return undefined and onSubmit func i returned data.
Data's onSubmit func well.

Thank lee.

**Comment by bluebill1049** [comment]
you can use context to hoist handleSubmit method.

handleSubmit()()

**Comment by hieusmiths** [comment]
> you can use context to hoist handleSubmit method.
> 
> handleSubmit()()
I make form have about 50 <-> 70 field so i devide 4 form then group it into main comtainer.

hmm, maybe i must use redux or use contextAPI.
Thank you a lot. Bluebill.

**Comment by bluebill1049** [comment]
you can use react context API, you don't even need redux.

**Comment by hieusmiths** [comment]
> you can use react context API, you don't even need redux.
Yes, i decice use React context Clean every thing.
You are sflash :)

**Comment by gino8080** [comment]
can you please post a working example using Context to call submit from the parent? 
thank you
