### ISSUE TITLE
Resetting form while field array is hidden shows strange behavior

### ISSUE THREAD

**Issue by susisu** [react-hook-form/react-hook-form#1375]
**Describe the bug**
When resetting a form while field array is hidden, the fields are not reset correctly and have wrong values.

**To Reproduce**
1. Open the codesandbox below
2. Click `Show form` button
3. Click `Hide form` button
4. Click `Reset` button
5. Click `Show form` button again

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-sd6d6?file=/src/index.js

**Expected behavior**
After the step 5, I expected the form had two fields `John Doe` and `Bill Luo`, but it has only one field `John Luo`.
When the form is submitted, only `Jon Doe` is sent.

After resetting again or if reset before step 2, it works fine.

It worked as expected in react-hook-form < 5.3.0.

It will work if I put `useFieldArray` outside of `MyForm` component
https://codesandbox.io/s/react-hook-form-usefieldarray-d31rv?file=/src/index.js
but actually I want to separate components using `FormContext`, without  passing methods in props.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Browser Chrome
 - Version 81.0.4044.92

**Comment by susisu** [comment]
Wow, I checked out 5.4.0 beta and the issue is fixed.
Thank you!

**Comment by bluebill1049** [comment]
wow you are speedy, i just released a beta version... ! thank you for testing.
