### ISSUE TITLE
Is it possible to disable enter key press to submit the form ? 

### ISSUE THREAD

**Issue by raphaelnoguier** [react-hook-form/react-hook-form#1378]
**To Reproduce**
1. Create a form without submit button
2. Type enter
3. If you don't have a submit button there is an error

Do we have an option to disable this, because i handle my submit by another button not on the <form> ? 

Thanks :)

**Comment by bluebill1049** [comment]
try: formState: isValid and set your form mode to `onChange`

**Comment by raphaelnoguier** [comment]
Even with the onChange method i still get this error when pressing enter : 

`Uncaught TypeError: Cannot read property 'type' of undefined
  at HTMLFormElement.formKeydownListener `

**Comment by bluebill1049** [comment]
reproduce in a codesandbox we can go from there.

**Comment by raphaelnoguier** [comment]
Here you go : https://codesandbox.io/s/youthful-greider-69jp4
 To see the error open the browser devtools and type enter on the form :)

**Comment by bluebill1049** [comment]
where is the formState and mode 'onChange'? your demo works as well. please spend sometimes in here: https://react-hook-form.com/api i have put down a lot of my time for documentation.

**Comment by bluebill1049** [comment]
<img width="724" alt="Screen Shot 2020-04-09 at 10 47 53 pm" src="https://user-images.githubusercontent.com/10513364/78896683-2fa0f100-7ab4-11ea-8978-a14267130e60.png">

there is no error.

**Comment by raphaelnoguier** [comment]
Check the browser console not the CSB console you'll get the error

**Comment by raphaelnoguier** [comment]
This is the error :
<img width="854" alt="Capture d’écran 2020-04-09 à 14 50 47" src="https://user-images.githubusercontent.com/22751073/78896847-81745780-7a71-11ea-80fb-8a1528e9355d.png">

**Comment by bluebill1049** [comment]
please take a look the error message: this is not error message from `react-hook-form`.

**Comment by raphaelnoguier** [comment]
Wow, i just realise that this come from the Chrome plugin Lastpass, i'm really ... Thanks anyway !

**Comment by bluebill1049** [comment]
no worries.
