### ISSUE TITLE
`getValues` function doesn't return new values after updating a field for the second time

### ISSUE THREAD

**Issue by Petka17** [react-hook-form/react-hook-form#1381]
**Describe the bug**
`getValues` function doesn't return new values after updating a field for the second time.

**To Reproduce**
1. Go to https://codesandbox.io/s/wizardly-dew-fzwvj
2. Enter "abc" string into the second field and click outside of this field
3. Data in the object from `getValues` will show the updated value ("abc")
4. Enter "abcde" string into the second field and click outside of this field
5. Data in the object from `getValues` will show the previous value ("abc")
6. Enter "abcdefg" string into the second field and click outside of this field
7. Data in the object from `getValues` will show the updated value ("abcdefg")
8. Enter "abcdefgh" string into the second field and click outside of this field
9. Data in the object from `getValues` will show the old value ("abcdefg")

**Expected behavior**
After blur event, getValues should return correct values.

If you uncomment onBlur prop where the `triggerValidation` function is called (without parameters) then `getValues` will return correct values.

**Additional context**
I tried to implement autosave logic. I found an idea for the implementation in this issue #539

**Comment by bluebill1049** [comment]
I haven't looked at it close, but i think you are after watch() instead of getValues()

**Comment by Petka17** [comment]
Thank you for the quick response. 
I need to receive updated value only on blur event (after a user finished typing), that's why I don't use `watch()` which triggers rerendering on each keystroke.

**Comment by bluebill1049** [comment]
`getValues()` doesn't trigger re-render, it only reads what's on the form, if you need to read what's on the form then you should attach onBlur event on your inputs.
