### ISSUE TITLE
Document and support Enzyme testing (preferably without .getDOMNode()) 

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [react-hook-form/react-hook-form#1382]
**Describe the bug**
Hi, thanks so much for this great library! 💐 

There are a few issues (#183, #532, #585) and Spectrum chats ([link with resolution](https://spectrum.chat/react-hook-form/help/rhf-and-setting-values-on-a-select-in-a-test~5b9b1c29-aa01-443d-9e68-3e3e7533d86f), [link](https://spectrum.chat/react-hook-form/help/enzyme-testing-examples~ead11135-424c-4b2b-aa39-ce533052751b)) that mention difficulties using Enzyme preference for using `@testing-library/react` to test react-hook-form, but nothing that actually indicates Enzyme works for testing this library. I haven't been able to get it to work.

**Resolution**
Edit: adding this in to make it clear that this works for me:

```tsx
const element = wrapper.find('select[data-testid="a"]')
element.getDOMNode().value = 'foo'
element.getDOMNode().dispatchEvent(new Event('input'))
```

**To Reproduce**
See test output from the Codesandbox link.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-enzyme-testing-example-5tn7i
Note that there's a seeming bug in codesandbox that shows this test as giving a 5 second timeout, but it works locally. 🤷  https://github.com/codesandbox/codesandbox-client/issues/946

**Expected behavior**
The form should have been submitted with `{ LastName: "Horray!" }`. The [link with resolution](https://spectrum.chat/react-hook-form/help/rhf-and-setting-values-on-a-select-in-a-test~5b9b1c29-aa01-443d-9e68-3e3e7533d86f) is a pretty unusual way of doing things: we generally shouldn't have to reach into mounted components' DOM nodes. One of two things must be true, I think:

* It is a bug somewhere that the normal Enzyme `simulate` events don't trigger an input change
* That `getDOMNode()` way of doing tests is the recommended approach and should be documented somewhere

**Screenshots**
It was submitted, but with `LastName: ""`
![Screenshot showing the form submitted with default values](https://user-images.githubusercontent.com/3335181/78939205-b1c3f200-7a81-11ea-99e7-687a8ff0758d.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: Safari

**Additional context**

Oh, and I would _love_ to use testing-library/react as mentioned, but this is on a project that's stuck on Enzyme. 😛

**Comment by bluebill1049** [comment]
hey @JoshuaKGoldberg thanks for the issue report. i haven't use enzyme for a quite a long time, i will attach a help needed tag. hopefully someone can help out.

**Comment by bluebill1049** [comment]
hmm, it's been 11 days and look like not many people using enzyme these days, I am going to close this issue and leave this help wanted tag there. hopefully, someone can answer this issue.

**Comment by JoshuaKGoldberg** [comment]
@bluebill1049 I'm confused about the open/close strategy for issues here. Does closing the issue and keeping the tag on mean you're still accepting PRs? What's the difference between open and closed?

Either way, would you mind leaving it open? My workaround works so if nobody else gets to it I can write up these docs soon.

...and there are [lots](https://www.reactiongifs.us/wp-content/uploads/2013/08/dozens_of_us_arrested_development.gif)! of Enzyme users (we're just too embarrassed to mention it out loud normally). 😢

**Comment by bluebill1049** [comment]
@JoshuaKGoldberg I try to maintain the issues logs here, as you have seen i have left this issue for 2 weeks plus and there is no one provide a solution. I am happy to open this issue for another 2 weeks but it creates noise for me to concentrate and maintain the log and certainly I don't want this to be leave on the issue log forever if no one or someone provide a solution. Also even it's closed someone still can add their solution as well, that happens a lot of time. hope for you understanding 🙏
