### ISSUE TITLE
react hook form FormControlLabel problem in conditional rendering

### ISSUE THREAD

**Issue by ahmadkam2** [react-hook-form/react-hook-form#1386]
Im using watch to conditional rendering some checkbox items in my form.
items condional rendering works correctly, But form submitting data not have
new showing items.

**Screenshots**

![Screenshot from 2020-04-10 16-56-42](https://user-images.githubusercontent.com/53652173/78990733-73dfd000-7b4c-11ea-8bad-47fdfb3fa0a6.png)
 when watchAdsType changes, items array changes and rendered options will be changed.
But I get the initial items names in form submit data

**Comment by bluebill1049** [comment]
where r the keys?

https://react-hook-form.com/faqs#Whyisdefaultvaluenotchangingcorrectlywithternaryoperator

**Comment by ahmadkam2** [comment]
Thank you @bluebill1049 
I added key like this in my code
![image](https://user-images.githubusercontent.com/53652173/78992039-a0491b80-7b4f-11ea-91b3-6d15864f3f50.png)

But in submit data in first state i got correct data but, in changing options
I dont get correct data.
I mean that data contains some items values and dont containe all showing items values.
In my options array, I have some options in multiple rendering states and i pass string number
as key to elements that its values are not repetitive

**Comment by bluebill1049** [comment]
can you make a simple codesandbox for this issue?  key should be on the col, you should even get a react warning without `key`.

**Comment by ahmadkam2** [comment]
I fixed the issue by removing <Col> element in my code.
But, how can i use Col element in my code?

**Comment by bluebill1049** [comment]
put the key on the Col

**Comment by ahmadkam2** [comment]
Thank you @bluebill1049
