### ISSUE TITLE
How is order preserved when using multiple validators?

### ISSUE THREAD

**Issue by StarpTech** [react-hook-form/react-hook-form#1387]
When I use multiple validators how is the order preserved? I don't want to request the API when the error can be caught earlier. This works but I'm not sure if it is reliable.

```js
ref={form.register({
    required: true,
    minLength: 3,
    pattern: /^[a-zA-Z0-9]+$/,
    validate: handleUsernameValidation
})}
```
I need it in the order as defined.

**Comment by bluebill1049** [comment]
we don't support this at the moment and there is a ticket on the project already.  for such behaviour you can use 

```
validate: {
  required: () => {}, 
  minLenght: () => {}
}
```

**Comment by StarpTech** [comment]
I don't understand your example. I'm talking about different predefined validators + custom validators. Could you also reference the issue before closing my request?

**Comment by bluebill1049** [comment]
<img width="390" alt="Screen Shot 2020-04-11 at 8 09 02 am" src="https://user-images.githubusercontent.com/10513364/79026323-bac0da80-7bcb-11ea-8115-ddce747a0315.png">

Yes, that's what i meant we don't support pre-defined validators order. I have added a waiting for upvote, if i see a lot of people want for this feature then will reopen and investigate for solution.

**Comment by StarpTech** [comment]
I described it as a bug not a feature. In my opinion the use case is very common. The fix could be very easy e.g by using an array structure or a sort key.

**Comment by bluebill1049** [comment]
1. you didn't follow the issue template as bug or feature request. i can't play read the mind in here.
2. you can easily say each feature is easy is to implement and it takes time for someone to work on.

**Comment by StarpTech** [comment]
If you don't understand it then say it so I will explain. The issue description and example are straight to the point and a reproduction is hard.

I said it is easy because I thought about it a while and it's all about using an ordered data structure.

I like that approach but I have a concrete issue, objects property order can't be guaranteed across js engines \ serialization. Therefore I can't ensure the same customer experience on all devices.

**Comment by StarpTech** [comment]
At least for browser with Es2015 it should be no problem:

> Current Language Spec (since ES2015) insertion order is preserved, except in the case of keys that parse as integers (eg "7" or "99"), where behavior varies between browsers. For example, Chrome/V8 does not respect insertion order when the keys are parse as numeric.

If you generate your forms dynamically e.g by serialization process you should take care of it.

**Comment by bluebill1049** [comment]
There is a reason why we set up template so we can read and understand quickly, we don't have time to ask each one of you what's this and that, our time is as precious as yours. by following the rule/template, you can help us and yourself. 

React Hook Form's Github issue is not a product support line, this repo is maintained and built by someone who is passionate about contribution to the whole community, If you have problem or issue we am more than happy to help and assist, i didn't close your issue instead putting in a feature pending column, we have many features to implement and the priority is not dictated by your or anyone rather from everyone's needs and vote.

As for today, the alternative solution before i get to work on this will be use the validate function

```
validate: {
  required: () => {},
  min: () => {}
}
```

**Comment by StarpTech** [comment]
> There is a reason why we set up template so we can read and understand quickly, we don't have time to ask each one of you what's this and that, our time is as precious as yours. by following the rule/template, you can help us and yourself.

> React Hook Form's Github issue is not a product support line, this repo is maintained and built by someone who is passionate about contribution to the whole community, If you have problem or issue we r more than happy to help and assist, i didn't close your issue instead putting in a feature pending column, we have many features to implement and the priority is not dictated by your or anyone rather from everyone's needs and vote.

Instead of wasting so much energy why you don't ask what you need to fully understand the issue? I'm 100% aware that this is opensource. I provide my help to fix this issue. You are not alone.

**Comment by bluebill1049** [comment]
> Instead of wasting so much energy why you don't ask what you need to fully understand the issue? 

I understand this is a feature request from the moment the issue was open, because i already have a ticket in my backlog. This is not a bug, because it's been implemented this way.

> I'm 100% aware that this is opensource. I provide my help to fix this issue. You are not alone.

awesome. we are on the same boat then.

> What's the difference between this and my example? This is still an object.

because in the lib, it's map through the validate object:

`for (const [key, validateFunction] of Object.entries(validate)) {`

To conclude: 

This feature will be implemented and it's in the pipeline and its driven by demand (already give you a screenshot).

**Comment by StarpTech** [comment]
Wouldn't it help to outline an RFC here? What's your solution? Perhaps we can align us here and give everybody the power to work on it.

> because in the lib, it's map through the validate object:
for (const [key, validateFunction] of Object.entries(validate)) {

This has the same issue. When iterating through an object the order is not guaranteed. As a developer, I would like to define that order explicitly.

**Comment by StarpTech** [comment]
Something like this

```js
ref={form.register([
    { required: true },
    { minLength: 3 },
    { pattern: /^[a-zA-Z0-9]+$/ },
    { validate: handleUsernameValidation }
])}
```

**Comment by bluebill1049** [comment]
> This has the same issue. When iterating through an object the order is not guaranteed. As a developer, I would like to define that order explicitly.

pretty sure the order is guaranteed: 

<img width="570" alt="Screen Shot 2020-04-11 at 7 27 07 pm" src="https://user-images.githubusercontent.com/10513364/79040235-7e709700-7c2a-11ea-9818-c77078f87cfe.png">

**Comment by StarpTech** [comment]
Try this only to name an odd example:

```js
const test1 = {  a: 1, 1: 'a'  };
Object.entries(test1)
```

But the biggest point is if you generate that structure by an external system like API. The serialization process will never guarantee an order.

**Comment by StarpTech** [comment]
Here https://www.stefanjudis.com/today-i-learned/property-order-is-predictable-in-javascript-objects-since-es2015/ this is a good article. It outlines that IE11 is not supported.

**Comment by bluebill1049** [comment]
> Try this only to name an odd example:
> 
> ```js
> const test1 = {  a: 1, 1: 'a'  };
> Object.entries(test1)
> ```
> 
> But the biggest point is if you generate that structure by an external system like API. The serialization process will never guarantee an order.

You have a good point there, but our input name doesn't contain numbers (string only). This is probably a edge case for this lib.

**Comment by StarpTech** [comment]
Here https://www.stefanjudis.com/today-i-learned/property-order-is-predictable-in-javascript-objects-since-es2015/ this is a good article. It outlines that IE11 is not supported.

**Comment by bluebill1049** [comment]
Yea that's the article that i read as well.

**Comment by bluebill1049** [comment]
What's your strategy for dealing this?

**Comment by StarpTech** [comment]
Supporting additionally an array-like data structure.

**Comment by bluebill1049** [comment]
> Supporting additionally an array-like data structure.

Ok, thanks noted.

**Comment by kaykhan** [comment]
Any updates on this? I also have the usecase where i would need to prioritise the rules
