### ISSUE TITLE
useFieldArray remove operation cause a crash

### ISSUE THREAD

**Issue by bravedongdong** [react-hook-form/react-hook-form#1394]
**Describe the bug**
In deep ArrayFields, removing an index will cause an unexpected error, fieldsRef.current points the upper scope

**To Reproduce**
1. to examples: https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-x7btr
2. change defaultValues
 ```
const defaultValues = {
  test: [
    {
      name: "useFieldArray1",
      nestedArray: [{ field1: "field1", field2: "field2" }]
    },
    {
      name: "useFieldArray2",
      nestedArray: [{ field1: "field1", field2: "field2" }]
    },
    {
      name: "useFieldArray3",
      nestedArray: [{ field1: "field1", field2: "field2" }]
    }
  ]
};
```
3. delete test[1]
4. delete test[1].nestedArray[1]

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-x7btr

**Comment by bluebill1049** [comment]
```
delete test[1]
delete test[1].nestedArray[1]
```

where is test[1] && delete test[1].nestedArray[1]?

**Comment by bravedongdong** [comment]
> ```
> delete test[1]
> delete test[1].nestedArray[1]
> ```
> 
> where is test[1] && delete test[1].nestedArray[1]?

it means DOM operation, see the sandbox when step2 has been saved

**Comment by bluebill1049** [comment]
sorry deleted my message, testing now.

**Comment by bluebill1049** [comment]
thanks, reproduced the issue.

**Comment by bluebill1049** [comment]
patched will be go into the next release.
