### ISSUE TITLE
Custom form shape

### ISSUE THREAD

**Issue by KVtofan** [react-hook-form/react-hook-form#1401]
Hello, 
is it possible to register a custom form shape?

for the current moment, if I register input with name="custom.first" in the form on submit I'll receive the { ..., custom: { first: 'value' } }

Question: Is it possible to create the next shape: array of objects with { name: 'input name', value: 'input value' }

I need a way to register some inputs like this to achieve in the final form the next result:
{ ..., custom: [
    { name: 'first', value: 'firstInputValue' },
    { name: 'second', value: 'secondInputValue' },
] } 

Thanks!

**Comment by bluebill1049** [comment]
hey, sorry we don't support such usage. you have to register input and set it values during input change or manually invoke `setValue`
