### ISSUE TITLE
input does not get cleared on unmount in field array

### ISSUE THREAD

**Issue by deebov** [react-hook-form/react-hook-form#1402]
**Describe the bug**
I have a conditional input. and its value doesn't get cleared when the input is removed from the components tree

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-zypxe?file=/src/index.js
2. Click on Submit and open the console
3. Uncheck the checkbox and click on Submit
4. Take a look at the console

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-zypxe?file=/src/index.js

**Comment by bluebill1049** [comment]
you have to use `clearError` API for this to work at the moment.

**Comment by bluebill1049** [comment]
I did a closer look at this issue, sorry to info that we are not going to support such usage as in fact, the latest version won't even work with your code at all.

https://github.com/react-hook-form/react-hook-form/issues/1402

here is an alternative solution: https://codesandbox.io/s/react-hook-form-usefieldarray-9tn39?file=/src/index.js
