### ISSUE TITLE
Expose Controller rules as types

### ISSUE THREAD

**Issue by paambaati** [react-hook-form/react-hook-form#1403]
**Is your feature request related to a problem? Please describe.**
I'm building a lot of custom components that heavily use `<Controller>`, and I often times have to expose `rules` as a prop on the component. Since `Controller.rules` isn't exposed as a `Type`, I end up having to duplicate them. It would be lovely if `rules` is also exported a a type.

**Describe the solution you'd like**
Export nested types as top level types. For example, the below types —

```typescript
export type ControlType = {
	name: string;
	rules: { /* ... */ };
	// ....
}
```

can be rewritten as  —

```typescript
export type ControlRulesType = {
    // ...
};

export type ControlType = {
	name: string;
	rules: ControlRulesType;
	// ....
};
```
**Describe alternatives you've considered**
1. Publish my own types to DefinitelyTyped? But that won't work well if the library ships its own definitions.

**Comment by bluebill1049** [comment]
is this what you after?

https://github.com/react-hook-form/react-hook-form/blob/master/src/types.ts#L124

**Comment by paambaati** [comment]
Yep, that’s the one. Thanks, must’ve missed it.
