### ISSUE TITLE
I have tried to use Input field with type="file" but it's not working 

### ISSUE THREAD

**Issue by Shahzad6077** [react-hook-form/react-hook-form#1406]
Please consider asking the question at our spectrum channel.

https://spectrum.chat/react-hook-form

**Describe the question?**

**To Reproduce**

**Codesandbox link (Required)**
Include a codesandox will help us to investigate the issue quicker.

- [useForm](https://codesandbox.io/s/react-hook-form-useform-template-lsm61) Template
- [useFieldArray](https://codesandbox.io/s/react-hook-form-usefieldarray-template-q0jek) Template
- [Controller](https://codesandbox.io/s/react-hook-form-controller-template-yu0z5) Template

**Screenshots**

**Additional context**

**Comment by bluebill1049** [comment]
follow the template and provide more details.
