### ISSUE TITLE
Nested Array Fields still work incorrectly when removing items

### ISSUE THREAD

**Issue by stanislav-bilanenko** [react-hook-form/react-hook-form#1408]
**Describe the bug**
I'm creating nested array fields using `useFieldArray` and `Controller`. I'm trying to add few top-level items, then nested-level items. And then to remove some of them. Some of values are reset to defaults. So seems like it works incorrectly.

**To Reproduce**
1. Go to provided CSB example
2. Click on append, fill name input
3. Click on appendNested, fill name input
4. Click on top-level append again and delete it.
5. Nested input of first append has been reset.

**Codesandbox link (Required)**
https://codesandbox.io/s/blue-star-w0kyz

**Expected behavior**
Values shoudn't reset to defaults after removing some items from field array.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 80.0.3987.163
 - react-hook-form version: 5.4.1

**Comment by bluebill1049** [comment]
can you take a look at this example: https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-x7btr?file=/src/index.js? I couldn't reproduce the issue, I will take a look at your example after dinner.

**Comment by stanislav-bilanenko** [comment]
@bluebill1049 Your example works correctly, but it doesn't use `Controller`. Please consider using it during reproducing.

**Comment by bluebill1049** [comment]
Thanks @stanislav-bilanenko you are right, it's due to Controller.

https://codesandbox.io/s/frosty-williams-h8cy4?file=/src/src/controller.tsx

**Comment by stanislav-bilanenko** [comment]
Thank you! 🙂👍Gonna test

**Comment by deebov** [comment]
hey i am getting the same issue. i am using version `5.4.2`. when do you plan to release the fix ?

**Comment by bluebill1049** [comment]
@deebov This weekend will do.

**Comment by kayuapi** [comment]
> Thanks @stanislav-bilanenko you are right, it's due to Controller.
> 
> https://codesandbox.io/s/frosty-williams-h8cy4?file=/src/src/controller.tsx

Encountered problem with deleting the fields. Steps to reproduce:
1. click on append and fill in the name input
2. click on append to generate a new name input but this time not filling it in
3. delete the empty name input generated in step 2
4. delete the name input in step 1

get the following error:
TypeError
data.slice is not a function

**Comment by bluebill1049** [comment]
@kabriel use an officially and updated CSB from the doc. https://react-hook-form.com/api#Controller

**Comment by kayuapi** [comment]
> @kabriel use an officially and updated CSB from the doc. https://react-hook-form.com/api#Controller

It works! Thanks!

**Comment by baninaveen** [comment]
When I am trying to remove from nestedarray it get this error `TypeError: Cannot assign to read only property '1' of object '[object Array]'`

I was append values from modal after close the modal. It only works in parent array but it does not work in nestedarray
