### ISSUE TITLE
How to show toat notif to user when onSubmit not valid.

### ISSUE THREAD

**Issue by hieusmiths** [react-hook-form/react-hook-form#1410]
Step 1: Enter form
Step 2: User click and me run onSubmit.
Step 3: Form error and i want show toat.

I think handle by ref  call function look like:

handleMiddlewar () => {
if ( isValid || ....) show;
buttonRef.current.click():
}
Must it not possble, cause is we will met many other case .

Thank reply me.

**Comment by bluebill1049** [comment]
I will reopen once you can provide some more details about this question above.

**Comment by hieusmiths** [comment]
> I will reopen once you can provide some more details about this question above.

I updated demonstrate with code-sandbox. Thank you

**Comment by bluebill1049** [comment]
oh @hieusmiths you can do this
```
useEffect(() => {
  if (Object.keys(errors).length > 0) {
    // show your error message
  }
}, [errors])
```

**Comment by hieusmiths** [comment]
> oh @hieusmiths you can do this
> 
> ```
> useEffect(() => {
>   if (Object.keys(errors).length > 0) {
>     // show your error message
>   }
> }, [errors])
> ```
Wow so good, yesterday i check and saw errors change when user manip.
How to you can prevent re-render when errors change.

**Comment by bluebill1049** [comment]
you will have to keep a state if the pop up is already there then.

**Comment by hieusmiths** [comment]
> you will have to keep a state if the pop up is already there then.

did you using mutable for errors when user change and using immuable for errors when submit ?

**Comment by bluebill1049** [comment]
mutable errors.

**Comment by hieusmiths** [comment]
> mutable errors.

:V like me think 💯
