### ISSUE TITLE
Remove Field Array on Control Input Causes value to disappear.

### ISSUE THREAD

**Issue by adithep** [react-hook-form/react-hook-form#1411]
**Describe the bug**
Using field array, with Controller. By removing an index, causing value of all index above it to disappear.

**To Reproduce**
1. Click on 'Add'
2. Enter value '1'
3. Click on 'Add'
4. Enter value '2'
5. Click on 'Add'
6. Enter value '3'
7. Click on 'Remove', next to value '2'
8. See the value '1' disappear, and only '3' remains.

**Codesandbox link (Required)**
https://codesandbox.io/s/infallible-sound-0luwh?file=/src/ar.js

**Expected behavior**
Value '1' remains in the first input box.

**Comment by bluebill1049** [comment]
Thanks for reporting : ) we have an issue for it already: https://github.com/react-hook-form/react-hook-form/issues/1408

**Comment by bluebill1049** [comment]
actually is' due to defaultValue=""

**Comment by bluebill1049** [comment]
not relevant to the other issue.
