### ISSUE TITLE
support type conversion

### ISSUE THREAD

**Issue by pwelter34** [react-hook-form/react-hook-form#1414]
**Is your feature request related to a problem? Please describe.**

This library is very useful so far.  However, I keep running into issues with values being in the wrong type, everything is a string.  My backend API expects the json to be formatted for the correct type, ie numbers without quotes, booleans as true/false.  Yup has some support for conversion, but it doesn't deal with empty strings, which is the default react requires for an input without a value.  

**Describe the solution you'd like**

solution i'd like to see is to be able to specify a data type on register.  

```
register({ name: 'age', type: 'number' }, { required: true, min: 8 })
```

provide a method for custom conversion

```
register({ 
    name: 'age', 
    convert: (value) => parseFloat(value) 
}, { 
    required: true, 
    min: 8 
})
```

**Describe alternatives you've considered**

I've tried using Yup, but it doesn't support empty strings.

**Additional context**

**Comment by bluebill1049** [comment]
Take a look this example: https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-furtc?file=/src/index.tsx

https://github.com/react-hook-form/react-hook-form/tree/master/examples

**Comment by bluebill1049** [comment]
Thanks for your suggestion, at the moment we don't have plan to change register syntax and you can use Controller to parse value.

**Comment by martpie** [comment]
I would like to add that using a `type="text"` for a number is definitely a common pattern: https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/

I guess we will have to use custom validators for now.

**Comment by akmalhakimi1991** [comment]
@bluebill1049 Doesn't seem to work:
https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-forked-u32bu?file=/src/index.tsx

Did I miss anything?

**Comment by bluebill1049** [comment]
> @bluebill1049 Doesn't seem to work:
> https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-forked-u32bu?file=/src/index.tsx
> 
> Did I miss anything?

https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-furtc

**Comment by akmalhakimi1991** [comment]
@bluebill1049 Seems like it only works for the default value. If I change the input to a new value, I got string instead:
![Capture](https://user-images.githubusercontent.com/10990690/93160188-67d2ec80-f742-11ea-93c0-8a771411ef60.JPG)  
  
Or did I understand this wrongly?

**Comment by bluebill1049** [comment]
> @bluebill1049 Seems like it only works for the default value. If I change the input to a new value, I got string instead:
> ![Capture](https://user-images.githubusercontent.com/10990690/93160188-67d2ec80-f742-11ea-93c0-8a771411ef60.JPG)
> 
> Or did I understand this wrongly?

I have updated the example: https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-furtc?file=/src/index.tsx

**Comment by akmalhakimi1991** [comment]
> I have updated the example: https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-furtc?file=/src/index.tsx

Thanks!
