### ISSUE TITLE
No error on parent object 

### ISSUE THREAD

**Issue by aslupik** [react-hook-form/react-hook-form#1416]
**Describe the bug**
If you have a validation rule on a parent object, the error is not available via `useForm` until you submit the form.

**To Reproduce**

- Type a string in the first field
- Type a longer string in the second field
- Click outside the field

**Expected behavior:**
`useForm` updates `errors` with the parent error. We see an error in the form that should say "user rule is not met"

**Observed behavior: **
No error.

**Codesandbox link (Required)**
https://codesandbox.io/s/zealous-microservice-bcj3w?file=/src/App.js

**Screenshots**
![image](https://user-images.githubusercontent.com/54040692/79248271-9c681280-7e49-11ea-8eca-7c8ea71b1aba.png)

After clicking submit, the error does appear.

I tried running the validation manually in a `useEffect` by calling `getValues()`, and then I do get the errors. Then I could store the errors myself via `useState`, but it means I cannot rely on `useForm` to provide me with all the form errors.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 80

**Comment by bluebill1049** [comment]
This is by design, validation only triggers by a field at a time, if you want the other field to show an error, you can use `triggerValidaiton`.

**Comment by aslupik** [comment]
I see, so I can use `triggerValidation` passing in the field name of the parent and that will trigger validation at that specific level. That seems to work, thank you very much.
