### ISSUE TITLE
Need to have setTouched methods

### ISSUE THREAD

**Issue by Vandell63** [react-hook-form/react-hook-form#1418]
**Is your feature request related to a problem? Please describe.**
I need to set touched to any field i want in context of custom register, i can't update the touch prop. 
I saw some post on it. But in my case i would like to show an error message only when user touch at least one time the field.

**Describe the solution you'd like**
Maybe create a method like `setTouched` to update the form state touch props. As the setValue

**Describe alternatives you've considered**
Nothing i found.

**Additional context**
Example here. The field 'lastName' is register in custom way. The first field get the touch event, not the second one. Am i doing a mistake ?
https://codesandbox.io/embed/react-hook-form-typescript-664fb?fontsize=14&hidenavigation=1&theme=dark

And like ever thx for this awesome project. This project was needed and i'm happy that you made it. Keep this way :).
Best regards

**Comment by bluebill1049** [comment]
use `setValue`

**Comment by Vandell63** [comment]
Oh wait. You are super fast. Thx :) . I use it on line 72 is it the wrong way ?

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#formState formState is wrapped with Proxy, so you need to read them before render.

**Comment by Vandell63** [comment]
Ok i did it now in code. But it keep the same issue when 'onBlur' from the input 'lastName' don't trigger the new touch state for 'lastName' to `true`. Sry if i misunderstood something here

**Comment by bluebill1049** [comment]
hey @Vandell63 no worries, why don't you use `Controller` and let it do it for you?

**Comment by leventeszmolka** [comment]
Hi,

It seems that on controlled inputs `touched` still gets triggered `onChange` and not `onBlur`.

**Comment by sandroweb** [comment]
> use `setValue` it will set touched to true.

Sorry, but not work for me.

I set `setValue` inside of useEffect to validate the initial value, loaded of API. The `formState.touched` are always empty. Only when I touched manually in the field, the `formState.touched` is fill.

**Comment by bluebill1049** [comment]
@sandroweb we don't have set touched to true with `setVaue`.

**Comment by sandroweb** [comment]
> we don't have set touched to true with `setVaue`. The statement that i made above is incorrect.

Ok, well, how I set forced a field touched?

**Comment by flybayer** [comment]
I also need a way to set a value to touched. Actually, what I really want is all fields to automatically be touched on submit.

**Comment by bluebill1049** [comment]
thanks @sandroweb & @flybayer for your feedback, perhaps we should consider

`setValue('firstName', 'value', { shouldTouch: true })`

**Comment by bluebill1049** [comment]
@flybayer any chance to use `isSubmitted` state?

**Comment by flybayer** [comment]
Maybe a spoke too soon. I was checking `touched` to conditionally show validation errors, but looks like the library essentially does that so I don't have to check `touched`

**Comment by andrwo** [comment]
Hi @bluebill1049 , this was marked as done on Sep 4 (able to manually set touched for a particular field). Can I check how it is done?

Can't find it anywhere in the docs, and Typescript defs does not have signature for : setValue('firstName', 'value', { shouldTouch: true })

Thanks so much!

**Comment by bluebill1049** [comment]
> Hi @bluebill1049 , this was marked as done on Sep 4 (able to manually set touched for a particular field). Can I check how it is done?
> 
> Can't find it anywhere in the docs, and Typescript defs does not have signature for : setValue('firstName', 'value', { shouldTouch: true })
> 
> Thanks so much!

Pretty sure we have that in the doc and type definition.

**Comment by codeshifu** [comment]
> > Hi @bluebill1049 , this was marked as done on Sep 4 (able to manually set touched for a particular field). Can I check how it is done?
> > Can't find it anywhere in the docs, and Typescript defs does not have signature for : setValue('firstName', 'value', { shouldTouch: true })
> > Thanks so much!
> 
> Pretty sure we have that in the doc and type definition.

No. Can't find in the doc as well & there isn't a type definition for it. Can you point to a link where we can find this?

**Comment by codeshifu** [comment]
What I'm currently doing is using lodash `set` function to update (mutate) the formState

i.e.

```
set(formState.touched, `${name}`, true)
```

where `name` is the input field name

**Comment by cdaz5** [comment]
@bluebill1049 im not sure if my specific use case is irregular and thus no reason to care/support (totally understand if thats how you feel), but the situation i'm running into is i'm manually doing a `trigger` call for a specific part of my form inside an `onClick` for a button (its not a submit type button).  The issue is manually calling trigger doesn't cause the invalid fields to be marked as touched, and thus my error messages don't appear  since we only show then if `touched && error`, so either having a trigger call mark the fields as touched (or having a similar signature to `setValue` i.e. `trigger(field | fields, markTouched: boolean)` or having a `setTouch` function would be greatly appreciated.  I realize there are a few workarounds outside of this, im just merely presenting a use case for `setTouch` as its own function rather than done as a part of the `setValue` which i have no reason to call.

**Comment by qwen-3108** [comment]
Hi @bluebill1049 thanks for the awesome library.

I agree with many others that an independent `setTouched` would be useful.

An example where `setValue` won't work is file input. As seen from the [sandbox](https://codesandbox.io/s/react-hook-form-setvalue-wvmzm?file=/src/App.js), the touch state of the input does not update when `setValue` is called, but updates when a user select a file.

Hope you'll consider adding it! :)

**Comment by OJIEG65** [comment]
Any update about setTouched functionality when using setValue ? :) 
  setValue('name', value, {touched: true}); ?

**Comment by ganijon-dev** [comment]
Any update about setTouched functionality when using setValue ? :)
setValue('name', value, {touched: true}); ?
@bluebill1049

**Comment by bluebill1049** [comment]
> Any update about setTouched functionality? :)
> In formik there is hook which is setTouched and it is very useful hook because in the case if you want to show check icon
> 
> @bluebill1049

https://github.com/react-hook-form/react-hook-form/pull/5181

**Comment by alextenb** [comment]
Perhaps the trigger() method could accept an argument to setTouched? This is important to me, as sometimes we populate our form with data supplied from other sources, and I would like to alert users that they need to fix the data before they can submit it to our system.
