### ISSUE TITLE
Typings for `errors` and `validationResolver` are very restrictive

### ISSUE THREAD

**Issue by neopostmodern** [react-hook-form/react-hook-form#1421]
**Is your feature request related to a problem? Please describe.**
Both `errors` and `validationResolver` make strong assumptions about the format of the errors (when using TypeScript, of course).
The project page says it supports a variety of validation libraries (none of which I use) or custom validation. I partially rely on `ajv` and partially write my own validation. In both cases I use completely flat errors (e.g. `{ "cases[0].caseData.profileInformation.age": "should be a number" }`), which is incompatible with the typings enforced by the library.
So I feel like (at least with TypeScript) it does not actually support using custom validation. Or is there a technical reason why errors need to be shaped a certain way? AFAIC errors are created and consumed by user-code only and the library only passes it around?

**Describe the solution you'd like**
I think it would be good to allow a third, optional type being passed to `useForm` which indicates the error object shape. It could default to the current type (which seems to work fine for a variety of use cases).

**Describe alternatives you've considered**
I've resorted to using a bunch of `as any` casts and sometimes tricking the TypeScript compiler by combining untyped objects with not using the dot notation (which is bad style in the end), e.g.
```
  const errors = {}
  if (!values.caseSetId) {
    // eslint-disable-next-line dot-notation
    errors['caseSetId'] = 'Select a case set'
  }
```
But this doesn't work when I want to put an error on an array field. It will always want an array of errors, which IMHO doesn't make sense if I simply want to say "Please add at least one X"

**Comment by bluebill1049** [comment]
can you provide an example in a codesandbox? FYI @kotarella1110

**Comment by Nvveen** [comment]
I am having similar problems while using fp-ts and io-ts.
https://codesandbox.io/s/react-x1vly?file=/src/App.tsx

**Comment by bluebill1049** [comment]
I am assigning this issue to @kotarella1110 please take a look whenever you got a chance 🙏

**Comment by kotarella1110** [comment]
@bluebill1049 I will look into this later 👍

**Comment by wrakky** [comment]
I've just run into a similar issue trying to type my form with a [Material-UI Multiple Select](https://material-ui.com/components/selects/#multiple-select) field

Brief example and full codesandbox is below:
```ts
interface Values {
  multiSelect: string[];
}
...
const { errors } = useForm<Values>();
const multiSelectError = errors.multiSelect?.message // Property 'message' does not exist on type 'FieldError[]'.
```
https://codesandbox.io/s/focused-napier-hiwvc?file=/src/App.tsx

The `errors` typing seems to assume any array values are always multiple fields whereas in my case it's a single field with an array for it's value.

**Comment by levrik** [comment]
I'm also currently hitting the issue mentioned by @wrakky.
This really needs a fix!

**Comment by kotarella1110** [comment]
> https://github.com/react-hook-form/react-hook-form/issues/1421#issuecomment-614483053

Unfortunately, It is no way in TypeScript to recognize that it is any array value.
Because we supported nest object since v4 as follows:

```tsx
type FormValues = {
  nested: {
    object: {
      key: string;
    };
    array: number[];
  };
}

const { register, errors } = useForm<FormValues>();

errors.nested?.object?.key?.message // no error
errors.nested?.array?.[0]?.message // no error
errors.nested?.array?.[0]?.message // no error

<input name="nested.object.key" ref={register({ required: 'required' })} />
<input name="nested.object.array[0]" ref={register({ required: 'required' })} />
<input name="nested.object.array[1]" ref={register({ required: 'required' })} />
```

If expected the field name to be `nested.object` and the field value to be `{ key: string }`, TypeScript would not be able to recognize `{ key: string }` as the field value.
We have a headache on this...
If TypeScript solves this issue https://github.com/microsoft/TypeScript/issues/12754, we can define the perfect type.

You can use `any[]` to to avoid this problem as follows:

```ts
interface Values {
  multiSelect: any[];
}
```

Or, we may need to revisit the creation of an external utility type to identify the value of the field I previously proposed https://github.com/react-hook-form/react-hook-form/issues/987#issuecomment-587256304.

```ts
interface IServicio {
  multiple: FormValue<string[]>;
}
```

Related:

* Issue
  * https://github.com/react-hook-form/react-hook-form/issues/987
* PR
  * https://github.com/react-hook-form/react-hook-form/pull/1182
  * https://github.com/react-hook-form/react-hook-form/pull/1178

**Comment by bluebill1049** [comment]
Follow up on this issue, we going to update the doc to include more TS examples and have a section under the Advance page to state some of the limitations and reasons behind.

**Comment by neopostmodern** [comment]
Thanks for the consideration. As far as I understood this, it still does not solve the usage of flat error objects, such as the above mentioned example of `{ cases[0].caseData.profileInformation.age": "should be a number" }` (or `{ cases[0].caseData.profileInformation.age": { message: "should be a number" } }` if that makes a difference).
I think there will always be cases where the error type simply can't be deduced from the form value type (and I wonder whether if there is a technical reason to bind the two together?)

**Comment by bluebill1049** [comment]
> I think there will always be cases where the error type simply can't be deduced from the form value type (and I wonder whether if there is a technical reason to bind the two together?)

That's a good point, which I agree that there are cases that form `values` that don't represent form `errors`.

However, there is a cost with this approach that separates them as well, which means you will need to declare both `form` and `error` types. Ideally, form values should always associated with errors, by separating form value and error, it also repetition and disjoint type system for this lib. I don't have a good solution in my head right now, open for other suggestions as well.

**Comment by neopostmodern** [comment]
I'm not sure if this is implementable with the current typings, but I'd assume that it should be possible to add a third, optional type to `useForm`? 

Currently it's `useForm<FormDataType, ValidationContextType = void>` and the error shape is deduced from from the `FormDataType` with a mechanism I'd for simplicity dub `FancyAutoGeneration`. I'd propose amending it to `useForm<FormDataType, ValidationContextType = void, ErrorType = FancyAutoGeneration<FormDataType>>`. 

It wouldn't break for current users (by making the default be what it is right now) but would allow users in need (such as me) to take on the additional effort and specify a custom error type (which for complex, flat errors might be as simple as `{ [errorPath: string]: string }` since there won't be a way to generate an exhaustive type anyway).

**Comment by bluebill1049** [comment]
After discussion with @kotarella1110 (our TS custodian) we both agree to introduce another generic (third) for `error` type is not trivial and also not intuitive to new/existing users as well. We probably will have to use `any` for situation when form value is not having a 1 to 1 relationship with error. However, if you have a strong opinion about this third generic, we are open to PR as well, and happy to take a look at it.

**Comment by bluebill1049** [comment]
hey, @stramel can we please get your take on this one as well?

**Comment by neopostmodern** [comment]
I unfortunately don't have the time to create a PR right now (I guess understanding all the effort you have put into your typing so far would be non-trivial), but will try to do so in the near future.
As per `any` – would you switch the default error type to `any`, or leave it as is and force users who use a different error type to use `any` to bypass the restrictions?

**Comment by kotarella1110** [comment]
> https://github.com/react-hook-form/react-hook-form/issues/1421#issuecomment-614647486
>
> Or, we may need to reconsider the creation of an external utility type to identify the value of the field I previously proposed [#987 (comment)](https://github.com/react-hook-form/react-hook-form/issues/987#issuecomment-587256304).
> 
> ```ts
> interface Values {
>   multiSelect: FormValue<string[]>;
> }
> ```

@neopostmodern If the suggested `FormValue` is created, do you think this problem is solved?

**Comment by bluebill1049** [comment]
we will try to resolve this issue at v6: https://github.com/react-hook-form/react-hook-form/issues/1461

**Comment by bluebill1049** [comment]
In the meantime, have u considers to use ErrorMessage component?

**Comment by bluebill1049** [comment]
@kotarella1110 's new feature will be released for the next major version and help solve this problem.
