### ISSUE TITLE
Deferring Script / Chunking

### ISSUE THREAD

**Issue by robmarshall** [react-hook-form/react-hook-form#1422]
As this package is wrapped completely around the form component that I am building, is there any way to split the JS script away from the component and defer its loading until after page render?

I am trying to reduce my page load as much as possible, and the JS behind the form is not critical for page load.

Any thoughts?

**Comment by bluebill1049** [comment]
can you provide a bit more context? if your page doesn't contain `react-hook-form`, it should get code-split.

**Comment by robmarshall** [comment]
This may be more of a Webpack thing, now I think about it.

As an example, I have a homepage and the very first element on it is the form. I want the HTML of the form to load - this has been managed via SSR. But I want the react-hook-form code to be split and deferred. Rather than being seen as essential and loading immediately.

**Comment by bluebill1049** [comment]
yea, i think you want to post this question at Webpack.
