### ISSUE TITLE
When submitting - code

### ISSUE THREAD

**Issue by majweb** [react-hook-form/react-hook-form#1423]
How works isSubmitting??

https://codesandbox.io/s/react-hook-form-password-match-check-standard-validation-jvhum?file=/index.js

**Comment by bluebill1049** [comment]
where is handleSubmit? https://react-hook-form.com/api#handleSubmit

**Comment by majweb** [comment]
ok updated
https://codesandbox.io/s/react-hook-form-password-match-check-standard-validation-9k59p

**Comment by bluebill1049** [comment]
![Uploading Screen Shot 2020-04-16 at 8.14.14 am.png…]()
