### ISSUE TITLE
Wrong cursor position after trimming email field

### ISSUE THREAD

**Issue by asaturov-b** [react-hook-form/react-hook-form#1424]
**Describe the bug**
Using input[type=email] with Controller causes wrong cursor position after trim.
Fields created with input[type=email] and ref has no same problem.

**To Reproduce**
1. Create a field using Controller and input[type=email].
2. Enter one or more spaces in the empty field.
3. Enter any other non-space character.
4. Now field value is trimmed, but cursor is in the start position, though it should be in the end.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controlled-mixed-with-uncontrolled-8484b?file=/src/index.js

**Expected behavior**
Cursor position should be in the end position of field after trimming.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4 Catalina
 - Browser: Chrome
 - Version:  80.0.3987.163

**Comment by bluebill1049** [comment]
i don't see any `trim` code?

**Comment by asaturov-b** [comment]
Maybe the problem is not in trim.
I've just noticed that when you enter some spaces in beginning of empty field (like i've described above), control.setValue function is not firing. It's called only when you enter non-space character.
Maybe there is some problem in onChange handler?

**Comment by bluebill1049** [comment]
that's not even the correct usage.

**Comment by bluebill1049** [comment]
can you have a read here: https://react-hook-form.com/api#Controller? 

why are you `merge` control with `setValue`?
