### ISSUE TITLE
Adding an async validator delays synchronous validators from clearing error state

### ISSUE THREAD

**Issue by martdavidson** [react-hook-form/react-hook-form#1427]
**Describe the bug**
Registering a single async validator makes synchronous errors clear only _after_ the async validator resolves.

**To Reproduce**

`mode` is `onChange`.

```
const registerDisplayNameRule = register({
    minLength: {
      value: 4,
      message: 'The display name must be at least 4 characters in length.',
    },
    required: 'The display name is required.',
    validate: {
      unique: debounce(checkForUserWithSameDisplayName, 400),
    },
  })
```

`minLength` will trigger as soon as you start typing, and show the error synchronously. Once you type past 4 characters, I'd expect the error message to disappear immediately, but it only disappears once `unique` resolves.

If you remove the `validate` object, that's the behaviour.

**Expected behavior**
Expect synchronous validating errors to clear immediately when they're no longer an error.

**Comment by bluebill1049** [comment]
> minLength will trigger as soon as you start typing, and show the error synchronously.

That depends on your validation mode, and you can combine something like touched to avoid the error gets appeared right away.

have you considered moving all the validation into the validate function?

**Comment by martdavidson** [comment]
Hey Bill, yes, I did consider moving everything into validate, I'll try that.

The issue here wasn't that the error appears right away, it's that it doesn't disappear until all validators have resolved.

**Comment by bluebill1049** [comment]
> The issue here wasn't that the error appears right away, it's that it doesn't disappear until all validators have resolved.

This is expected behavior, otherwise, the user will see an error appear, disappear and reappear.

**Comment by martdavidson** [comment]
If that's expected, then that's fine, but it seems like a bad user experience to not get feedback on the synchronous validation right away. If I type more than 4 characters, I have to wait until the unique username check resolves before the minLength error goes away, which doesn't really feel good.

**Comment by bluebill1049** [comment]
Personally i disagree with the statement above, but if that's the behavior that your app expected, you can always leave that async one outside of register and attach a onChange to `triggerValidation`, which means you still get instant feedback and there will be another async validation coming later on.
