### ISSUE TITLE
With "revalidation on change", validation is not triggered, if field becomes valid and then invalid

### ISSUE THREAD

**Issue by mfal** [react-hook-form/react-hook-form#1430]
**Describe the bug**
Given revalidation mode is set to "onChange" and your text field is in an invalid state. Now when you correct your input, the shown validation error disappears. Now when you go on changing your input and make it invalid again, the validation is not triggered and no validation error is shown.

**To Reproduce**
1. Go to 'https://codesandbox.io/s/react-hook-form-validation-onblur-3yxvp'
2. Focus the "Username" field
3. Tab to next field -> Username shows error message
4. Tab back to "Username"
5. Enter "Bill" -> Error disappears
6. Type further -> the maxLength validation does trigger an error

**Expected behavior**
I would expect that input validation does not stop, after once the input becomes valid, when revalidation mode is set to "onChange".

![validation](https://user-images.githubusercontent.com/4696750/79493308-988ee880-8021-11ea-9467-8322cf68dea3.gif)

**Comment by bluebill1049** [comment]
ok this one is actually valid, because it's only triggering validation onBlur, and correct them onChange. 

-> onBlur (error)
-> onChange (clear error) doesn't trigger error to appear.
-> (only) onBlur will trigger error
