### ISSUE TITLE
Can it handle huge form

### ISSUE THREAD

**Issue by sakalx** [react-hook-form/react-hook-form#1431]
We have form with **100+** different fields `[text, checkbox, select, etc...]`

is there can be some issues to handle all these fields with `one hook` ?

or it will better create a `several hooks` and use `triggerValidation` and `getValues` to collect data for submitting.

Thanks!

**Comment by bluebill1049** [comment]
One custom hook will do, one of the reasons I did this hook is so it can handle large form, or perhaps even 1000+ fields https://react-hook-form.com/advanced-usage#Workingwithvirtualizedlist
