### ISSUE TITLE
MUI Checkbox data is not appearing when firing the handleSubmit function

### ISSUE THREAD

**Issue by azemetre** [react-hook-form/react-hook-form#1433]
**Describe the question?**

Using RHF `<Controller />` I am able to use 3rd party MUI components in my login form, however the `<Checkbox />` data is not appearing when the handleSubmit function is fired.

I don't believe I am adding or changing the boolean values for the checkbox. Kinda lost at what I should be doing in the `<Controller />` for the checkbox.

**To Reproduce**
1. In the email input write: `test@example.com
2. In the password input write: '123'
3. Click the remember-me checkbox
4. Click the Login button

**Codesandbox link (Required)**

https://codesandbox.io/s/trusting-mirzakhani-qi7uo

**Additional context**
The Controller for the Checkbox is wrapped in another MUI component `<FormControlLabel />`:

```javascript
<Controller
   as={
    	<FormControlLabel
			control={
                <Checkbox
                  name="remember-me"
                  checked={checkedRemember}
                  onChange={e => handleChange(e)}
                  id="remember-me"
                />
           }
           label="remember-me"
           aria-labelledby="remember-me"
        />
    }
	name="rememberMe"
	control={control}
/>
```

Is it possible I am not using nested controls properly? The `<FormControlLabel />` is used to add the label text 'remember-me' to the checkbox component

**Comment by azemetre** [comment]
Was able to resolve my issue by not using `<FormControlLabel />` from MUI and use a native html label instead. Only have the RHF `<Controller />` wrapping the MUI `<Checkbox />` now and everything is working as expected.

Still curious if it's possible to use nested controls or if it's recommended to not attempt this.

**Comment by bluebill1049** [comment]
can you take a look this example in the doc?
https://react-hook-form.com/api#Controller
https://codesandbox.io/s/react-hook-form-controller-079xx

**Comment by h-sakano** [comment]
`Controller` should be placed at `control` property of `FormControlLabel` component like below code.

```tsx
<FormControlLabel
  control={
    <Controller
      as={<Checkbox color="primary" {...props} />}
      control={control}
      defaultValue={defaultValue}
      name={name}
    />
  }
  label={label}
  labelPlacement={labelPracement}
/>
```

**Comment by h-sakano** [comment]
I wrote an example in Codesandbox:

https://codesandbox.io/s/modest-voice-f1ubn

**Comment by bluebill1049** [comment]
amazing! thank you @h-sakano

**Comment by bluebill1049** [comment]
we can safely close this one with @h-sakano 's help! thank you!

**Comment by braginteractive** [comment]
@h-sakano @bluebill1049 only problem with that solution is you can't set the default checked value?
