### ISSUE TITLE
Some internal states of a form are not cleared even after calling `reset`

### ISSUE THREAD

**Issue by ekawatani** [react-hook-form/react-hook-form#1434]
**Describe the bug**
Originally reported at Spectrum [here](https://spectrum.chat/react-hook-form/help/clearing-the-internal-states-of-a-form-after-submitting~e2a4c88e-7704-4363-a4eb-45442170bb11).

Before submitting a form, the input fields are validated on submit. This works as expected, but after submitting a form, focusing on any input fields of the same form trigger validations automatically even after calling `reset`. The expected behavior is that after submitting the form, the internal states of the form should reset without calling `reset`, and validations should only be triggered on the next submit.

**To Reproduce**
1. Go to this [CodeSandbox](https://codesandbox.io/s/nrr4n9p8n4). This is taken directly from the documentation [here](https://react-hook-form.com/api/#errors).
2. Fill in all input fields correctly.
3. Submit the form.
4. Focus on the first field, and clear the content.

**Expected behavior**
Expected: The validation error should not be shown.
Actual: The validation error is shown. This still happens after calling `reset` after submit.

**Screenshots**
N/A

**Desktop (please complete the following information):**
All browsers and OS

**Smartphone (please complete the following information):**
All devices

**Comment by bluebill1049** [comment]
aha i see the reason why because after the form is submitted, the form state `isSubmitted` stay still and hence form validation still respect that the form is been submitted. I think this behavior is correct and no change should be made, invoke reset() after the form is submitted should resolve the problem. Let me know if this make sense, I will include this information in the `formState` doc.

**Comment by bluebill1049** [comment]
<img width="909" alt="Screen Shot 2020-04-18 at 5 26 15 pm" src="https://user-images.githubusercontent.com/10513364/79631058-ba12e000-8199-11ea-9c77-608c616fdaf1.png">

The website will be updated will the above information.

**Comment by ekawatani** [comment]
@bluebill1049 

Hmm, it doesn't work even if I call reset after submitting the form as I mentioned originally at Spectrum. If that resets, then I'm fine with it, of course. If you try it in the CodeSandbox I pasted in the Spectrum chat, it still triggers validations.

**Comment by bluebill1049** [comment]
thanks @ekawatani i see the problem now.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-errors-zck8b?file=/src/index.js

**Comment by bluebill1049** [comment]
or using useEffect to check errors is empty and isSubmitted count > 0, then invoke reset()

**Comment by ekawatani** [comment]
Ah! I see the issue. So, the `reset` function resets the form states as well. I didn't realize that properly, but it's actually in the documentation. Thanks, I think this issue can be closed.

**Comment by bluebill1049** [comment]
thanks for reporting this issue @ekawatani 👍

**Comment by ejose19** [comment]
@bluebill1049 Is there any other way than a setTimeout inside the onSubmit function? Using the "useEffect" solution is not that direct since you may depend on conditional logic inside of the onSubmit function, and the useEffect may clear the form even if that's not desired (ie, BAD_REQUEST from server).

**Comment by bluebill1049** [comment]
what do you mean @ejose19 ?

**Comment by ejose19** [comment]
@bluebill1049 see this [sanbox](https://codesandbox.io/s/vigilant-sanderson-ppmu7?file=/src/App.tsx) for an example.

Suppose I want to reset the form conditionally (in this case, a promise inside a try/catch), if I use the useEffect in your example, I get a reset even if the promise rejected (which is not what I want). If you comment the useEffect and uncomment the setTimeout inside the onSubmit function, the behaviour is the correct one, reset only gets called promise resolved.

What I mentioned is that it would be nice to have an option to disable the override handleSubmit is doing so a reset inside it will be the one that persist.

**Comment by bluebill1049** [comment]
> @bluebill1049 see this [sanbox](https://codesandbox.io/s/vigilant-sanderson-ppmu7?file=/src/App.tsx) for an example.
> 
> Suppose I want to reset the form conditionally (in this case, a promise inside a try/catch), if I use the useEffect in your example, I get a reset even if the promise rejected (which is not what I want). If you comment the useEffect and uncomment the setTimeout inside the onSubmit function, the behaviour is the correct one, reset only gets called if promise resolved.
> 
> What I mentioned is that it would be nice to have an option to disable the override handleSubmit is doing so a reset inside onSubmit will be the one that persist.

why are you doing reset at `useEffect` (curious)? why not just doing it in `onSubmit`?

**Comment by ejose19** [comment]
> https://codesandbox.io/s/react-hook-form-errors-zck8b?file=/src/index.js

Taken from your example.

If I do in ```onSubmit``` without a setTimeout, then the reset does nothing (as you previosly said, it gets overriden by handleSubmit)

**Comment by bluebill1049** [comment]
@ejose19 https://codesandbox.io/s/react-hook-form-errors-zck8b?file=/src/index.js?

**Comment by ejose19** [comment]
@bluebill1049 add a ```console.log(isSubmitted)```, submit the form and you will see it remains true.

**Comment by bluebill1049** [comment]
oh oops, I remember now... yes you will need `useEffect`

**Comment by ejose19** [comment]
@bluebill1049 I'm using setTimeout in ```onSubmit```, ```useEffect``` sadly is not flexible enough (like in the example, where I reset dynamically based on the result of a promise in ```onSubmit```). If there's no other solution that that one I will keep using it. Thanks!

**Comment by bluebill1049** [comment]
Thanks @ejose19, I think use setTimeout for now, until we figure out something better.
