### ISSUE TITLE
Dirty FormsState gets 'forgotten' when using Observable

### ISSUE THREAD

**Issue by ahrnee** [react-hook-form/react-hook-form#1437]
**Describe the bug**
The `dirty` state of a form is not successfully retrieved when formState is accessed in an observable subscription handler (unlike the `dirtyFields` value, which seems correct). An example is provided below.

**To Reproduce**
1. Change text in the single text field
2. View on screen information for 'Dirty' and 'Dirty Fields' and observe values reflect form changes as expected
3. Click button 1
4. View console log, and observe values on screen reflect form changes as expected
5. Click button 2
6. View console log, and observe:  `dirty` does not reflect value as expected (should be true, but is false), while `dirtyFields` does

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-external-click-handling-example-with-rxjs-bwumg?file=/src/index.js

**Expected behavior**
Ideally, the `dirty` form state would be correctly retrieved when formState when formState is accessed in an observable subscription handler. Or, at least, I would expect consistent behavior between the 'dirty' and `dirrtyFields` values (either both successfully retrieve in this scenario, or both do not)

**Screenshots**
![image](https://user-images.githubusercontent.com/39815557/79541690-2995ac00-8082-11ea-9389-8e5cdbca87ca.png)

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome
 - Version: 80.0.3987.163 

**Additional Comments**
This is the first issue I have posted, so I also wanted to also add some praise for this fantastic library. It is a pleasure to use, and the API design, implementation, documentation, and community responsiveness are as good as I have seen. Really nice job, and thanks!

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report and description, this really helps a lot for us. 🙏

**Comment by bluebill1049** [comment]
I think the problem it's due to `useEffect` missing dep and callback without `useCallback` as well. More of JS closure problem.

https://codesandbox.io/s/react-hook-form-external-click-handling-example-with-rxjs-y6ycg?file=/src/index.js

**Comment by ahrnee** [comment]
I think I have [solved](https://codesandbox.io/s/react-hook-form-external-click-handling-example-with-rxjs-with-useref-mkmb1?file=/src/index.js) this issue - and it was with my code. 

@bluebill1049 - thanks for your reply and code example. While this solved the original problem, it created another: a new subscription was created to the observable every single time the component updated (just click the button multiple times and view the console log to see the problem with this)

The root of the issue was that the 'dirty' variable was captured in a closure when useEffect first ran. The solution was to store the value in a ref object (See [this codesandbox](https://codesandbox.io/s/react-hook-form-external-click-handling-example-with-rxjs-with-useref-mkmb1?file=/src/index.js) for working solution)

The reason this works (and the reason dirtyFields always worked), is because the referenced object (on the heap) is _not_ captured in a closure, and so the it's current value is used each time the onSubmit method is run.
