### ISSUE TITLE
Control and React Select with multi value

### ISSUE THREAD

**Issue by claudioquaglia** [react-hook-form/react-hook-form#1440]
**Describe the bug**
When the Control component wraps the `react-select` component with `isMulti` prop seems that value will not be set to the form. When submit the form the field is undefined. And error validations rules seems be ignored.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select more than one option from select
2. click submit
3. Look at the console

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-4el6m?file=/src/index.js

**Expected behaviour**
See as selected values the array of string set with `setValue` function.

**Comment by bluebill1049** [comment]
incorrect usage: `onChange={([selected]) => onHandleChange(selected)}`

you are meant to return the data from `onChange`

https://react-hook-form.com/api#Controller

**Comment by claudioquaglia** [comment]
my fault I've missed the return data... thank's for your help.
