### ISSUE TITLE
useForm.ts - process is not defined

### ISSUE THREAD

**Issue by leonidez** [react-hook-form/react-hook-form#1441]
**Describe the bug**

I am toggling the rendering of a form based on a state value in a wrapper component like this:

```
export default () => {
  const [showSuccess, setShowSuccess] = useState(false)

  return (
    <div>
      {!showSuccess ? (
        <Form onSuccess={() => setShowSuccess(true)} />
      ) : (
        <FormSuccess onDismiss={() => setShowSuccess(false)} /> 
      )}
    </div>
  )
}
```

When the Form unmounts I get an error `process is not defined` in my console and my `FormSuccess` component does not render correctly because of it. I've traced the reference to process back to this line: https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L1177

Is there a need to check if we're in production for this one effect? I don't see any other reference to process anywhere else in this repo except in the `useForm` tests.

When I remove the line my component works as expected.

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-useform-template-kkk1g

Note: the codesandbox link shows a working version 

**React Hook Form Version**
`"react-hook-form": "^5.4.2",`

**Expected behavior**

Toggling rendering of the form should proceed without errors.

**Comment by bluebill1049** [comment]
This was made for not reset field during hot reload. Do you have a reproducible example?

**Comment by leonidez** [comment]
Thank you for the quick reply!

I don't have a reproducible version right now, but I can tell you that the build process for the app I'm working on is nonstandard. We're installed react-hook-form in our app via npm and we're creating a bundle by referring to this specific file:

node_modules/react-hook-form/dist/react-hook-form.umd.js

That's how i'm able to access your lib on the frontend. 

I'm not used to seeing a reference to `process` in umd builds, I see other libs creating separate files for dev and prod. Are you able to do anything like that, or maybe guard the `process` reference so that it doesn't fail if not defined? Thanks again.

**Comment by bluebill1049** [comment]
take a look at this beta: react-hook-form@5.4.3-beta.1 let me know if this fix your problem.

**Comment by bluebill1049** [comment]
did you have a chance to test the beta version?

**Comment by leonidez** [comment]
hello @bluebill1049 and thank you for reaching out again! i was able to use the umd file as-is from the current version by modifying our build process slightly, similar to the replace that you're doing in the commit referenced above.

Thanks again for the quick responses and the resolution. It's good to see lib authors committed to their projects and gives a lot of confidence in choosing this package. Take care 👍

**Comment by bluebill1049** [comment]
hey @leonidez 👍  I closed the issue because the code has been merged. can you do a double check if this works for you `react-hook-form@5.4.3-beta.1` before I release the real version?

**Comment by leonidez** [comment]
Sure, I can take a look this weekend. Will let you know.

**Comment by bluebill1049** [comment]
thanks @leonidez

**Comment by leonidez** [comment]
Thank you @bluebill1049 this worked! I just updated to the latest react-hook-form and I was able to remove the workaround code from my build process. Thanks again! 👍

**Comment by bluebill1049** [comment]
awesome thanks for the confirmation.

**Comment by spaceaardvark** [comment]
This fixed the UMD build, but the ES6 modules build still checks for proces.env.NODE_ENV. I'm using it in the browser which now supports ES6 modules. Should I create a new issue?

**Comment by bluebill1049** [comment]
yes, we should remove that @spaceaardvark
