### ISSUE TITLE
register() required/validate{} do not work for controlled inputs (e.g. React Select)

### ISSUE THREAD

**Issue by cliffordp** [react-hook-form/react-hook-form#1443]
**Describe the bug**
If I give React Select 3 options and the _value_ of 2 of the 3 would fail validation (getting the selected option's `value` prop), the form validation should fail.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-controller-uopfc?file=/src/index.js

**Expected behavior**

**Video**
3:30 video demonstrating the bugs/questions: https://share.getcloudapp.com/OAubRG9g

**Comment by bluebill1049** [comment]
incorrect usage: you are combining `Controller` with `register`

https://codesandbox.io/s/react-hook-form-controller-079xx

**Comment by cliffordp** [comment]
Oh my! I thought coding at 1am was supposed to make me better? lol

btw, the sandbox link was wrong.
This is the relevant (and now working) one:
https://codesandbox.io/s/react-hook-form-react-select-controller-with-custom-validation-59dud?file=/src/index.js

**Comment by bluebill1049** [comment]
aha no worries at all mate, did you get it working?

**Comment by cliffordp** [comment]
all good. ty again!
