### ISSUE TITLE
[typescript]type error, when set `control` props to `Controller` component;

### ISSUE THREAD

**Issue by BetaGo** [react-hook-form/react-hook-form#1446]
**Describe the bug**
in the latest version; use with typescript, if declare form data type use `interface`,  will get a type error, when set `control` props to `Controller` component;

**To Reproduce**
see the example in Codesandbox as line 25

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-nsmib

**Expected behavior**
no type error

**Comment by bluebill1049** [comment]
Thanks, @BetaGo. @kotarella1110 you want to take a look at this one?

**Comment by bluebill1049** [comment]
looks like its due to the `getValues()` type improvement.

**Comment by bluebill1049** [comment]
worth to mention when I switched to `type` instead of `interface` and it's working.

**Comment by kotarella1110** [comment]
I will look into this from now on.

**Comment by bluebill1049** [comment]
Thanks, @kotarella1110 (no rush) I changed to `type` and it's working...
