### ISSUE TITLE
using reset as dependency of useEffect

### ISSUE THREAD

**Issue by saeedPadyab** [react-hook-form/react-hook-form#1451]
I have created a fully dynamic form that i had to use useFormContext to handle components. one of the components is react-select which it is customized and the question here is that after resetting the form by reset(), i need to clear the selected items of select input.
I need to know how the components can understand user has clicked reset() ?

i need something like this : 
```
 React.useEffect(() => {
    selectFieldRef.current.select.clearValue();
  }, [reset]);
```

**Comment by fakhrad** [comment]
Same issue here! please help

**Comment by bluebill1049** [comment]
can you create a codesandbox?

**Comment by bluebill1049** [comment]
will re-open once more context and codesandbox is supplied.
