### ISSUE TITLE
[Controller] isNotFieldArray is not updated properly

### ISSUE THREAD

**Issue by deebov** [react-hook-form/react-hook-form#1453]
**Describe the bug**
I've been getting weird issues because of this bug. I opened an [issue](https://github.com/react-hook-form/react-hook-form/issues/1369) but it didn't get resolved so I decided to get my hands dirty 😅
Controller uses `useMemo` to calculate `isNotFieldArray`. But since the `useMemo` receives a ref as a dependency that does not guarantee that the functions inside `useMemo` will be triggered whenever the ref changes. https://github.com/facebook/react/issues/15164#issuecomment-474833861 I would be happy to provide a more detailed code but I cannot get into `node_modules` in CodeSandbox. But putting `console.log(isNotFieldArray, isNameInFieldArray(fieldArrayNamesRef.current, name), name)` after `isNotFieldArray` is defined would clearly show the problem ( if you are using `Controller` inside `fieldArray` ). What I came up with is to replace `fieldArrayNamesRef` with `fieldArrayNamesRef.current.size` in the deps list here https://github.com/react-hook-form/react-hook-form/blob/master/src/controller.tsx#L56

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-controller-jsgm6
2. Select `Strawberry` as a value for the first input
3. Append another input
4. Remove the input you've just added
5. The value of the first input get resetted

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-jsgm6

**Comment by bluebill1049** [comment]
oh, cool @deebov thanks for the investigation. would like you like to send a PR if you have a solution?

**Comment by deebov** [comment]
> oh, cool @deebov thanks for the investigation. would like you like to send a PR if you have a solution?

sure!

**Comment by bluebill1049** [comment]
thanks a lot @deebov if you are having issues, I will be your fallback so no stress about it.

**Comment by deebov** [comment]
@bluebill1049 would you give a little explanation about this part of the code https://github.com/react-hook-form/react-hook-form/blob/4c865d35465b2d8f4e855c5285c4bc25ae2fe45c/src/controller.tsx#L118

![image](https://user-images.githubusercontent.com/28673719/79720826-bfd40700-82fa-11ea-9d95-205d596aa8e0.png)

`registerField` gets called twice on component mount. but basically, [this useEffect block](https://github.com/react-hook-form/react-hook-form/blob/4c865d35465b2d8f4e855c5285c4bc25ae2fe45c/src/controller.tsx#L128) may not be necessary because we already including `registerField` in the deps list of the useEffect block above and calling `registerField`

**Comment by bluebill1049** [comment]
SSR :(

**Comment by bluebill1049** [comment]
you are right!

**Comment by deebov** [comment]
one more thing, why we don't unregister a controller if it is in fieldArray ?
![image](https://user-images.githubusercontent.com/28673719/79724034-4a6b3500-8300-11ea-8654-559fe47b7004.png)

**Comment by bluebill1049** [comment]
because it's been taking care inside `useFieldArray` when delete, insert and shuffle the array.

**Comment by deebov** [comment]
i have a case where a controller is a required field in fieldArray. when you remove a field of fieldArray that required controller does not get removed from the `fields` array which prevents form submission

**Comment by deebov** [comment]
but when I disabled  `if(isNotFieldArray)` the issue disappeared

**Comment by bluebill1049** [comment]
right... let's submit it a PR see if automation cries about it.

**Comment by bluebill1049** [comment]
i am testing it now by running the automation locally.

**Comment by deebov** [comment]
yeah. i am preparing the PR

**Comment by deebov** [comment]
hey @bluebill1049 I had some troubles with the automation. I got two errors from the `useFieldArray` test case

**Comment by bluebill1049** [comment]
No worries I can take over and look at it @deebov 🙏

**Comment by bluebill1049** [comment]
i will commit on your branch :)

**Comment by deebov** [comment]
thank you )

**Comment by bluebill1049** [comment]
I guess i can test out in your codesandbox above right? @deebov

**Comment by deebov** [comment]
yeah

**Comment by bluebill1049** [comment]
aha, this is not a bug lol, you can add a default value it should fix it. https://codesandbox.io/s/react-hook-form-controller-2xyig?file=/src/index.js i will still merge your PR tho, there are some improvement there.

**Comment by deebov** [comment]
Yes this is what I am talking about 😂 

> To Reproduce
>
> Go to https://codesandbox.io/s/react-hook-form-controller-jsgm6
> Select Strawberry as a value for the first input
> Append another input
> Remove the input you've just added
> The value of the first input get deserted **the default value**

**Comment by deebov** [comment]
I want to prevent the first input value from getting reset to the default value when I remove sibling inputs

**Comment by bluebill1049** [comment]
> I want to prevent the first input value from getting reset to the default value when I remove sibling inputs

I don't see what's happening in my codesandbox above. nothing gets reset.

**Comment by deebov** [comment]
> > I want to prevent the first input value from getting reset to the default value when I remove sibling inputs
> 
> I don't see that's happening in my codesandbox above. nothing gets reset.

ohh, I see. so you set default value to `field` `defaultValue={field}` I didn't know about this

**Comment by bluebill1049** [comment]
I will update the doc to emphasize this.

**Comment by deebov** [comment]
thanks )

**Comment by bluebill1049** [comment]
Thank you for your contribution @deebov

**Comment by bluebill1049** [comment]
`<p>
              make sure to set <code>defaultValue</code> when you want to set default value, remove
              or reset with inputs.
            </p>`

hows this sounds?

**Comment by deebov** [comment]
i think we need to make it clear that the default value should be `field` element of `fieldArray` 
`<p> make sure to set <code>defaultValue</code> to <code>field</code> of <code>fields</code> when you want to set default value, remove or reset with inputs. </p>`
or
`<p> make sure to set <code>defaultValue</code> to <code>fields[index]</code> when you want to set default value, remove or reset with inputs. </p>`

**Comment by bluebill1049** [comment]
updated doc and codesandbox example :)
