### ISSUE TITLE
Submitting a form twice to get fields.

### ISSUE THREAD

**Issue by c0d3x** [react-hook-form/react-hook-form#1455]
When I submit my form I have to push submit button two times to get the values.
Is this because I show hide fields with the index of the parent?
Do I need to re-render the form in some way when I show the input fields?

Here is a code-sandbox of the problem, select a radio button then hit submit.
It works at random every second time or so:

https://codesandbox.io/s/react-hook-form-radio-array-with-inputs-c4v3b?file=/src/index.js

**Comment by bluebill1049** [comment]
Try to give those fields with unique names: https://react-hook-form.com/faqs#Whyisdefaultvaluenotchangingcorrectlywithternaryoperator

**Comment by bluebill1049** [comment]
Take a look at this version: https://codesandbox.io/s/react-hook-form-radio-array-with-inputs-y1dsc?file=/src/index.js
