### ISSUE TITLE
Values being cleared for Controller when using useFieldArray and calling remove inside useEffect

### ISSUE THREAD

**Issue by chead2344** [react-hook-form/react-hook-form#1456]
**Describe the bug**
Firstly, thanks so much for your work on this library, It's awesome!

I have a form that calls `remove` from `useFieldArray` when certain conditions are met. This happens by watching the array values and calling `remove` within a `useEffect` hook when said conditions are met. However, when doing so, the value in the first field is cleared. 

**To Reproduce**
1. Go to https://codesandbox.io/s/jolly-wright-3t04t?file=/src/App.js
2. Enter a value in the input
3. Click 'Append'
4. Add another value
5. Click 'Append'
6. Observe that the first value is cleared

**Codesandbox link (Required)**
https://codesandbox.io/s/jolly-wright-3t04t?file=/src/App.js

**Expected behavior**
The value should be maintained.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: 80.0.3987.163

**Comment by bluebill1049** [comment]
missing defaultValue: https://codesandbox.io/s/lucid-thunder-nzltw?file=/src/App.js
