### ISSUE TITLE
Validate Material UI Autocomplete

### ISSUE THREAD

**Issue by manualva7** [react-hook-form/react-hook-form#1457]
This is my current Autocomplete field:

```
<Autocomplete
            autoComplete
            disableClearable={!value.value && true}
            options={selects[props.selectGroup][props.name]}
            onChange={handleOnChange}
            getOptionLabel={(option) => option.label}
            renderOption={(option) => (
                <React.Fragment>
                    {option.label}
                </React.Fragment>
            )}
            renderInput={(params) =>
                <><TextField
                    error={props.error}
                    fullWidth
                    name={props.name}
                    {...params}
                    label={props.label}
                    variant="outlined"
                    inputProps={{
                        ...params.inputProps,
                        style: {height: 35, padding: 0},
                    }}
                    helperText={props.helperText}
                />
                    {console.log(params.inputProps.ref)}</>
            }
        />
```

inputProps is already defined there. if I spread props.inputProps after params.inputProps, my props.inputProps will overwrite the ref property already defined inside params and this will break the field. Any suggestions?

**Comment by bluebill1049** [comment]
provide a codesandbox plz and follow our template for a question.

**Comment by manualva7** [comment]
This is Material UI with labs installed. I can't just "create a sandbox". Is there a way I can register a field bypassing inputprops? Maybe just using store?

**Comment by manualva7** [comment]
https://codesandbox.io/s/affectionate-cori-6ov9d?file=/src/AutoCompleteField.js

**Comment by manualva7** [comment]
Sorry guys I don't know how to use sandbox. https://codesandbox.io/s/affectionate-cori-6ov9d?file=/src/AutoCompleteField.js

**Comment by bluebill1049** [comment]
Take a look at this example: https://codesandbox.io/s/react-hook-form-controller-079xx?file=/src/MuiAutoComplete.js by using Controller. 

Then you can just add prop: rules as required.

https://react-hook-form.com/api#Controller

**Comment by manualva7** [comment]
That doesn't seem to work

**Comment by bluebill1049** [comment]
here is a working version: https://codesandbox.io/s/react-hook-form-controller-2c52i?file=/src/MuiAutoComplete.js:799-806

**Comment by manualva7** [comment]
Thanks man! That worked. It was tricky because I had to wrap the TextField component instead of the whole Autocomplete component. Keep up the good work. 💪💪💪

For whoever gets stuck as I did, this is the final code. control has to be passed from parent since it must live with the rest of the useForm elements.

```
<Autocomplete
            autoComplete
            options={selects[selectGroup][name]}
            onChange={handleOnChange}
            getOptionLabel={(option) => option.label}
            renderOption={(option) => (
                <React.Fragment>
                    {option.label}
                </React.Fragment>
            )}
            renderInput={(params) =>
                <Controller
                    as={
                        <TextField
                            error={error}
                            fullWidth
                            name={name}
                            {...params}
                            label={label}
                            variant="outlined"
                            inputProps={{
                                ...params.inputProps,
                                style: {height: 35, padding: 0},
                            }}
                            helperText={helperText}
                        />
                    }
                    name={name}
                    rules={{
                        required: 'Required field'
                    }}
                    control={control}
                />
            }
        />
```

**Comment by manualva7** [comment]
CORRECTION!

Wrapping Controller over TextField doesn't work. Here is the working example:

```
<Controller
            as={
                <Autocomplete
                    autoComplete
                    options={selects[selectGroup][name]}
                    onChange={handleOnChange}
                    getOptionLabel={(option) => option.label}
                    renderOption={(option) => (
                        <React.Fragment>
                            {option.label}
                        </React.Fragment>
                    )}
                    renderInput={(params) =>

                        <TextField
                            error={error}
                            fullWidth
                            {...params}
                            label={label}
                            variant="outlined"
                            inputProps={{
                                ...params.inputProps,
                                style: {height: 35, padding: 0},
                            }}
                            helperText={helperText}
                        />
                    }
                />}
            name={name}
            rules={{required: 'Required field'}}
            onInput={(selected) => {
                return selected;
            }}
            control={control}
            value={advertiser[name]}
        />
```

**Comment by bluebill1049** [comment]
Thanks for sharing the solution.

**Comment by achyutjhunjhunwala** [comment]
@bluebill1049 @manualva7 Hi Guys,
Thanks for all the inputs above.

I tried whatever solution you provided, but for me, I have a multiline Autocomplete.
The moment I try to edit the AutoComplete Textbox, it breaks badly

Codesanbox Link for your reference
https://codesandbox.io/s/material-demo-fcijs?file=/demo.js

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/1629 (duplicated question above)

**Comment by bmaclean** [comment]
@manualva7 in your working example, are you using RHF's `setValue` in the `handleOnChange` callback? Do you get a warning for changing from uncontrolled to controlled value state?

**Comment by bluebill1049** [comment]
> @manualva7 in your working example, are you using RHF's `setValue` in the `handleOnChange` callback? Do you get a warning for changing from uncontrolled to controlled value state?

@bmaclean using Controller, take a look the doc and there is an example there as well.

**Comment by manualva7** [comment]
@bmaclean not really sure if I answer your question, but I’ve had that issue with other components. It happens when you don’t initiate state. I don’t think it’s a RHF issue, might be wrong. A bit more info might be helpful. Maybe paste your whole code here.

**Comment by Biz-e-Services** [comment]
Hi Manualva7
I used your CORRECTED code sample and it works perfectly. The only issue I'm having is its not saving to my state machine. saves as 
`"safetyInvestigation": [0]`

... any ideas on this? Is it to do with me not including the "value={advertiser[name]}" if so can you show me the code that refers to "advertiser[name]"?

**Comment by manualva7** [comment]
@Biz-e-Services by the time I built this, advertiser was how I built state:

- `const [advertiser, setAdvertiser] = useState()`

`name` is passed as a prop. So the autocomplete's name is dynamic. advertiser[name] calls the state of that key. name is the name of the field. Hope that helps.

**Comment by Biz-e-Services** [comment]
Thanks Manuel. So in effect this would/should not prevent me saving to state using rhf 6.8x?

Sent from my SAMSUNG Galaxy S6 on the Telstra Mobile Network
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ryana** [comment]
This example is no longer working: https://codesandbox.io/s/react-hook-form-controller-2c52i?file=/src/MuiAutoComplete.js:799-806

![image](https://user-images.githubusercontent.com/16389/118862890-78240400-b89b-11eb-8d17-02b596d6f634.png)

I am similarly getting a `props.render is not a function` when trying to do this locally running version 7.4.1

**Comment by Leshe4ka** [comment]
> This example is no longer working: https://codesandbox.io/s/react-hook-form-controller-2c52i?file=/src/MuiAutoComplete.js:799-806
> 
> ![image](https://user-images.githubusercontent.com/16389/118862890-78240400-b89b-11eb-8d17-02b596d6f634.png)
> 
> I am similarly getting a `props.render is not a function` when trying to do this locally running version 7.4.1

Same problem. Finding a solution to validate MUI Autocomplete with version 7.6.6

**Comment by Leshe4ka** [comment]
> This example is no longer working: https://codesandbox.io/s/react-hook-form-controller-2c52i?file=/src/MuiAutoComplete.js:799-806
> 
> ![image](https://user-images.githubusercontent.com/16389/118862890-78240400-b89b-11eb-8d17-02b596d6f634.png)
> 
> I am similarly getting a `props.render is not a function` when trying to do this locally running version 7.4.1

The same problem. I am looking for a solution to validate MUI autocomplete with version 7.6.6
