### ISSUE TITLE
[React Native] Proxy doesn't exist

### ISSUE THREAD

**Issue by beqramo** [react-hook-form/react-hook-form#1462]
After updating on react native 62.2 it throws an error that proxy doesn't exist

**Comment by bluebill1049** [comment]
what's 62.2? which version of RHF?

**Comment by beqramo** [comment]
> what's 62.2? which version of RHF?

**Comment by bluebill1049** [comment]
Can you take a screenshot of the error log?

**Comment by bluebill1049** [comment]
we are trying to detect Proxy. https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L122

**Comment by irekrog** [comment]
Same here

react-native: 0.61.5
react-hook-form: 5.5.2

> ReferenceError: Property 'Proxy' doesn't exist


> useForm
> react-hook.form.js:1328:36

and on the 1328 line is this:
```
formStateProxyRef.current = new Proxy(formState, {
        get: (obj, prop) => {
            if (prop in obj) {
                readFormStateRef.current[prop] = true;
                return obj[prop];
            }
            return {};
        },
    });
```

**Comment by bluebill1049** [comment]
thanks @irekrog can you do a quick test with this beta version: `5.5.3-beta.3`

**Comment by irekrog** [comment]
@bluebill1049 

It works fine now with `5.5.3-beta.3` :)
