### ISSUE TITLE
Validation errors with undefined paths get added as "undefined" key to "errors"

### ISSUE THREAD

**Issue by micaww** [react-hook-form/react-hook-form#1464]
**Describe the bug**
If you have any errors in your schema that have undefined paths, they will get added to the "errors" output with a path of "undefined". Having multiple of these scenarios, such as when using the `test` method on yup, they will overwrite each other in the error output.

**To Reproduce**
1. Create a form with a validation schema that has a failing test.
2. Check the "errors" output after submitting the form and you will see an "undefined" property with the error that was thrown from that test.

**CodeSandbox link (Required)**
https://codesandbox.io/s/heuristic-cray-9e1nt

**Expected behavior**
Errors that have undefined paths should not be added to the "errors" output. If test errors are needed in the output, the test function should return `this.createError` with a defined path. (this currently works)

I will be glad to submit a PR for this if that would help.

**Comment by bluebill1049** [comment]
This should fix it: https://codesandbox.io/s/bold-bush-0ig15?file=/src/src/logic/validateWithSchema.ts
