### ISSUE TITLE
Updating validation errors with a controlled component (Material UI)

### ISSUE THREAD

**Issue by Sebastian-** [react-hook-form/react-hook-form#1472]
**Describe the question?**
How do you update validation errors when using a controlled component (Material UI <TextView select />)? 

**Codesandbox link (Required)**
[Code Sandbox](https://codesandbox.io/s/goofy-chandrasekhar-yntsw?file=/src/App.js)

**To Reproduce**
1. Submit form without a selection -> "Required" error message is displayed
2. Make a selection -> Error message persists instead of disappearing
3. Submitting the form sends the data and clears the error

I've looked through past issues and tried incorporating their solutions into my code, but neither have worked so far. 
[Issue #404](https://github.com/react-hook-form/react-hook-form/issues/404)
[Issue #242](https://github.com/react-hook-form/react-hook-form/issues/242)

I've also tried using the Controller wrapper, but encountered similar behavior.

Any advice would be greatly appreciated!

**Comment by bluebill1049** [comment]
Take a look at this example: https://codesandbox.io/s/react-hook-form-controller-2c52i?file=/src/index.js

**Comment by Sebastian-** [comment]
Thanks! The sandbox was really useful in narrowing things down, The problem was that I didn't pass the Controller's props onto my component 😓
