### ISSUE TITLE
Autocomplete and RFH Controller

### ISSUE THREAD

**Issue by iamrenzx** [react-hook-form/react-hook-form#1473]
Hi i have a problem with regards to MUI autocomplete and RFH Controller. I want to return the second controller to null if the value changes on the first controller. I tried to `setValues('secondCountry',null)` but it doesn't change the value inside the field.

Created codesandbox here:
https://codesandbox.io/s/suspicious-tereshkova-nhtme?file=/src/App.js:0-1434

**Comment by bluebill1049** [comment]
Take a look examples here: https://github.com/react-hook-form/react-hook-form/issues/1247

**Comment by bluebill1049** [comment]
it's optional because you need to either supply at useForm defaultValues or defaultValue. you need to supply a default value, just like how you need a default state for controlled component.

**Comment by bluebill1049** [comment]
<img width="985" alt="Screen Shot 2020-04-22 at 5 18 34 pm" src="https://user-images.githubusercontent.com/10513364/79952148-4fc1ae80-84bd-11ea-9117-805c323f2991.png">

https://react-hook-form.com/api#Controller
