### ISSUE TITLE
First typed latter does not trigger after errors have been shown in Redux

### ISSUE THREAD

**Issue by Demonell** [react-hook-form/react-hook-form#1476]
**Describe the bug**
First typed latter does not trigger after errors have been shown. Error appears only when using Redux and manually control value of input.

**To Reproduce**
1. Press sumbit button. Error text appear.
2. Try to type any latter to Input.
3. On first press error message will dissapear but latter will not be typed.
4. Latter will be typed only on 2nd press.

**Codesandbox link (Required)**
https://codesandbox.io/s/typescript-redux-lotlr?file=/src/index.tsx

**Expected behavior**
Latter will be typed on first press.

**Desktop (please complete the following information):**
 - Browser Chrome

**Comment by bluebill1049** [comment]
you are mixing uncontrolled with controlled:

https://react-hook-form.com/faqs#Whyisfirstkeystrokeisnotworking
