### ISSUE TITLE
setValue  have bug in lastest vsesion

### ISSUE THREAD

**Issue by Louis-Chen** [react-hook-form/react-hook-form#1477]
this demo working in 5.1.3
i try to use setValue to update value but i did not  working 

Demo code
https://codesandbox.io/s/dreamy-tdd-kbvc4?file=/src/Form.js

**Comment by bluebill1049** [comment]
hey @Louis-Chen can you write the steps to reproduce this issue?

**Comment by Louis-Chen** [comment]
i use two way to set field value

if  i input value in field , and submit , react-hook-form cant get field value

another way is change value by setValue , submit form will get field value but input value not changed

**Comment by bluebill1049** [comment]
what's the steps to produce the issue with the above code sandbox? so i can see the bug and fix if there is one.

**Comment by bluebill1049** [comment]
it's working for me: https://codesandbox.io/s/react-hook-form-553-bug-oimsb

**Comment by Louis-Chen** [comment]
maybe demo in my desktop will be clear,

this is v.5.5.3 screen capture
![react-hook-form 5 53](https://user-images.githubusercontent.com/20965813/80064673-2eb79700-856b-11ea-8b71-57aa53661f91.gif)

and this is use in v.5.1.3 version
![react-hook-form 5 1 3](https://user-images.githubusercontent.com/20965813/80064760-6e7e7e80-856b-11ea-8d01-859d71613d2d.gif)

demo code 
https://codesandbox.io/s/react-hook-form-553-bug-lt7i3?file=/src/Form.js

**Comment by bluebill1049** [comment]
oh i see the issue now.

**Comment by bluebill1049** [comment]
wait, you register again with a custom register which overwrites it.

**Comment by bluebill1049** [comment]
remove that `useEffect`.

**Comment by bluebill1049** [comment]
by register again with the same name without `ref`, you are wiping the `ref` inside the hook.

**Comment by Louis-Chen** [comment]
oh ok  i see ,thanks, this issue can close

**Comment by bluebill1049** [comment]
awesome! thanks for raising this issue and clarify the concern.
