### ISSUE TITLE
TypeScript Controller value force me to use optional? in my type

### ISSUE THREAD

**Issue by marrkeri** [react-hook-form/react-hook-form#1478]
**Describe the bug**
I am using Controller and my custom Textfield which props contains value as string - not nullable/undefined. <Controller /> is underlined with this message
Property 'value' is missing in type '{ name: string; as: FC<TextboxType>; }' but required in type 'Pick<TextboxType, "value">'.ts(2741)

**To Reproduce**
1. I have this only one value test
```
type FormState = {
  test: string;
};
```
it is not nullable

2. useForm looks like this
```
const { handleSubmit } = useForm<FormState>({
    defaultValues: {
      test: "asdf"
    }
  });
```

3. Controller is using my custom field
```
<Controller name="test" as={Textbox} />
```
```
type TextboxType = {
  value: string;
  onChange: (value: string) => void;
};
const Textbox: React.FC<TextboxType> = ({ value, onChange }) => {
  return <input value={value} onChange={e => onChange(e.target.value)} />;
};
```
4. If value is optional error dissapear
```
type TextboxType = {
  value?: string;
  onChange: (value: string) => void;
};
```

**Codesandbox link (Required)**
https://codesandbox.io/s/elated-resonance-4v52r?file=/src/App.tsx

**Expected behavior**
TypeScript should not complain.

**Screenshots**
![image](https://user-images.githubusercontent.com/39760343/80039719-bc0dd380-84f8-11ea-8468-c9c713854201.png)
![image](https://user-images.githubusercontent.com/39760343/80039764-d2b42a80-84f8-11ea-9296-469407767c29.png)

**Comment by bluebill1049** [comment]
`control` is optional, because it will either read from the props or `context`, so conclusion you will need `control` props

**Comment by bluebill1049** [comment]
<img width="1002" alt="Screen Shot 2020-04-23 at 9 35 07 am" src="https://user-images.githubusercontent.com/10513364/80043686-bdb1b880-8545-11ea-83af-5855196a0a36.png">

**Comment by bluebill1049** [comment]
let me know if this makes sense, or perhaps you have a better suggestion to improve the docs.

**Comment by marrkeri** [comment]
I am sorry I have forgotten control={control} when I prepared demo, but it is same.
https://codesandbox.io/s/cocky-bose-iuee2

![image](https://user-images.githubusercontent.com/39760343/80068647-462d5a80-8540-11ea-8973-10e4a31a39b1.png)

I have also tried to use context but it is same (with and without control prop):
![image](https://user-images.githubusercontent.com/39760343/80069162-3104fb80-8541-11ea-80fb-ed103f3391c6.png)

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/admiring-dubinsky-s7bb8

because your Input component required a `value` prop

**Comment by marrkeri** [comment]
Thank you for quick response, but is there any way how to use Textbox instead of input with type checked. I have used ControllerProps but this doesn't help

![image](https://user-images.githubusercontent.com/39760343/80070020-9ad1d500-8542-11ea-9681-d7eeced4a9c0.png)

only if I use ControllerProps<any> but then value: any

**Comment by bluebill1049** [comment]
what about this: https://codesandbox.io/s/admiring-dubinsky-s7bb8?file=/src/App.tsx?

**Comment by marrkeri** [comment]
Finally I have found the way. Is it the way how you would use it?

![image](https://user-images.githubusercontent.com/39760343/80071607-38c69f00-8545-11ea-8ef2-082469ba6f36.png)

**Comment by marrkeri** [comment]
Just not sure why value is any instead of string, but it can be consumed by mu custom components. 
![image](https://user-images.githubusercontent.com/39760343/80071851-9e1a9000-8545-11ea-8190-a80af08e04d1.png)

**Comment by bluebill1049** [comment]
> Just not sure why value is any instead of string, but it can be consumed by my custom components.
> ![image](https://user-images.githubusercontent.com/39760343/80071851-9e1a9000-8545-11ea-8190-a80af08e04d1.png)

because the external components can return other types: number, object and etc.

i did this instead:

`as={<Textbox value="" onChange={() => {}} />}`

**Comment by marrkeri** [comment]
Great thank you for your time, finally I have got it. Awesome support and of course lib.

**Comment by bluebill1049** [comment]
anytime @marrkeri 👍
