### ISSUE TITLE
Problems with setValue()

### ISSUE THREAD

**Issue by rvision** [react-hook-form/react-hook-form#1481]
**Describe the bug**
setValue doesn't set the array values properly in "react-hook-form": "^5.5.3",

**To Reproduce**
A lot of versions react-hook-form were released in last couple of days, so I don't know if this is some version specific, but after updating it doesn't work as it was day before.
If I try to submit invalid form, errors are displayed properly, but when I select any department (data from <DepartmentEmployeesPicker /> is passed correctly), it clears the error, but I cannot submit because there are no data set for this array. I also tried to use clearError, but that doesn't work also.

`setValue('departments', data.departments, true);`

**Expected behavior**
It should update array of values.

```
const schema = yup.object().shape({
	departments: yup
		.array()
		.ensure()
		.min(1, 'At least 1 department selected is required')
});

const { control, register, formState, handleSubmit, errors, clearError, setError, getValues, setValue } = useForm({
	defaultValues: model,
	validationSchema: schema,
	submitFocusError: true,
});

register({ name: 'departments' });
register({ name: 'employees' });

<DepartmentEmployeesPicker
	checkedDepartments={model.departments}
	checkedEmployees={model.employees}
	hasError={errors && errors.departments}
	onChange={data => {
		setValue('departments', data.departments, true);
		setValue('employees', data.employees);
	}}
/>
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by bluebill1049** [comment]
you should put those 

register({ name: 'departments' });
register({ name: 'employees' });

inside a useEffect, otherwise each render will re-register a new input into hook form.

**Comment by rvision** [comment]
Wow :)

Thanks a lot, that exactly was the issue.

**Comment by robmarshall** [comment]
This just helped me. Thanks all!
