### ISSUE TITLE
watch() returns undefined when trying to pass object as defaultValue

### ISSUE THREAD

**Issue by alekseykarpenko** [react-hook-form/react-hook-form#1482]
**Describe the bug**
`watch()` returns `undefined` when trying to pass object as `defaultValue` (second param). Object as value required for some controlled inputs, e.g. `react-select`

**To Reproduce**
```js
const country = watch('country', profileData.country)
console.log(country); // -> "Ukraine"
// -- or --
const country = watch('country', { label: profileData.country, value: profileData.country })
console.log(country); // -> undefined
```

**Codesandbox link (Required)**
https://codesandbox.io/embed/react-hook-form-controller-0bjid?file=/src/index.js

**Expected behavior**
`watch()` should return correct value if object was passed as `defaultValue`

**Desktop:**
 - OS: MacOS
 - Browser: Chrome
 - Version 80

**Additional context**
```json
"dependencies": {
    "react": "^16.13.1",
    "react-hook-form": "^5.3.1",
  },
```

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/commit/4117816bc5ee0801be12dd3ebaaabb6ff78cec8c

just merged
