### ISSUE TITLE
Slow input change when using formState

### ISSUE THREAD

**Issue by lapico** [react-hook-form/react-hook-form#1488]
I just want to report a something strange I've seen using the library.

**Bug**: when clicking / focusing different inputs, I had to wait several seconds before the validation to be triggered and focus to be changed to the new field.

**Solution** : Strangely what solved this was to put `register()` calls in an effect (rather than in the fields `ref` prop).

Tested on a Redmi Android device.

Using :
"react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
"react-hook-form": "5.0.3"
"expo": "^37.0.0"
"proxy-polyfill": "^0.3.1"
...

The code needed validation with custom error messages, formState, controlled & uncontrolled components (picker, masked input, ...).

Below a simplified version of the code. Same code with `register` calls inside `ref` props would be slow. When commenting the use of formState, input change would be fast again.

With this complexity, I was not sure what worked and what didn't but my guess reading other issues was maybe it's something with Proxy on react native, or maybe a bad use of controlled components...

```javascript
import React, {useState, useMemo, useEffect} from 'react';
import {View} from 'react-native';
import {HelperText} from 'react-native-paper';
import {useForm} from 'react-hook-form';
import * as yup from 'yup';
import IMask from 'imask';
import Picker from '../../components/Picker';
import TextField from '../../components/TextField';
import Button from '../../components/Button';
import {useAccount} from '../../contexts/Account';

const Form = () => {
  const {profile = {}, profileApi} = useAccount();
  const [input, setInput] = useState(
    profile.input ? profile.input : null
  );

  const items = useMemo(
    () => [
      {label: 'none', value: '-'},
      {label: 'item1', value: '1'},
      {label: 'item2', value: '2'},
    ],
    []
  );

  const test1 = (value) => value !== '-';
  const test2 = (value) => value !== '!';
  const test3 = (value) => value !== '?';

  const schema = useMemo(
    () =>
      yup.object({
        picker: yup.string().test({
          test: test1,
          message: "required",
        }),
        maskedInput: yup
          .string()
          .test({test: test2, message: "message1"})
          .test({test: test3, message: "message2"}),
      }),
    []
  );

  const {register, setValue, watch, handleSubmit, errors, formState} = useForm({
    mode: 'onChange',
    defaultValues: {
      picker: profile.picker ?? items[0].value
    },
    validationSchema: schema,
  });

  useEffect(() => {
    register({name: 'picker'});
    register({name: 'maskedInput'});
  }, []);

  const valid = formState.isValid;

  const onSubmit = async (data) => {
    try {
      const result = await API.update(data);
    } catch (e) {
      console.log({error: e});
    }
  };

  return (
    <View>
      <Picker
        value={watch('picker')}
        setValue={(value) => setValue('picker', value, true)}
        items={items}
      />
      <HelperText type="error">
        {errors['picker'].message}
      </HelperText>
      <TextInput
        value={input}
        defaultValue={watch('maskedInput')}
        setValue={(value) => {
          const b = mask.resolve(value);
          setValue('maskedInput', b, true);
          setInput(b);
        }}
      />
      <HelperText type="error">
        {errors['maskedInput'].message}
      </HelperText>
      <Button onPress={handleSubmit(onSubmit)} disabled={!valid}>
        Submit
      </Button>
    </View>
  );
};

export default Form;
```

**Comment by bluebill1049** [comment]
Yes, `useEffect` is the right place to do it, and plus you can use `Controller` as well. I probably should update some of the examples in the doc.

**Comment by lapico** [comment]
Yes react native examples (using yup validation schema, controlled / uncontrolled components, ...)  would be great.

Thanks !

**Comment by bluebill1049** [comment]
i will take a look now.

**Comment by bluebill1049** [comment]
where is it?

**Comment by lapico** [comment]
where is what ?

**Comment by bluebill1049** [comment]
oh you mean to give an example! sorry misunderstood.

**Comment by lapico** [comment]
Would you recommend using Controller when using React Native, is it better ?

**Comment by bluebill1049** [comment]
`Controller` is better if you can get hold of the `focus` ref. This is a web example: https://codesandbox.io/s/react-hook-form-controller-auto-focus-5tru5 but you can get the idea.

**Comment by lapico** [comment]
Thanks. I like the simplicity without Controller (like in the code sample above), I hope there is no performance hit using this approach. It's not clear when and why to use Controller versus custom register...

**Comment by bluebill1049** [comment]
What you have above is probably the cheapest in terms of perf.

`Controller`

- when you want to reset an input
- when you want to focus on an input which has an error
- when you working with external lib

**Comment by vladshcherbin** [comment]
A section explaining when it's better to use register or Controller for web/react-native would be great, especially for newcomers. Still don't get it 😥

**Comment by bluebill1049** [comment]
`Controller` is basically doing the register inside :( they r the same thing except `Controller` is a wrapper and does a bit more for you. @vladshcherbin

**Comment by bluebill1049** [comment]
@vladshcherbin are you working on `native` or `web`?

**Comment by vladshcherbin** [comment]
@bluebill1049 web

**Comment by bluebill1049** [comment]
@vladshcherbin imagine when you working with `react-select`, `mui` and `and` with `Controller` it can take care of those registration for you as a wrapper.

**Comment by bluebill1049** [comment]
@lapico I have updated the validate schema section to include a react native example :) going to close the issue now :) feel free to follow up with more questions.

**Comment by manongguard** [comment]
I am also experiencing this using a Controller. How do we go about it ?

**Comment by bluebill1049** [comment]
> I am also experiencing this using a Controller. How do we go about it ?

It shouldn't tho, re-render is completely isolated at the Controller level, can you share a codesandbox?

**Comment by manongguard** [comment]
This is one of the Controller controlled input that I got.

```javascript
const renderTextInput = ({onChange, onBlur, value, ...rest}) => (
    <TextInput
      placeholder={placeholder}
      style={styles.input}
      {...rest}
      value={value}
      onChangeText={(onChangeValue) => onChange(onChangeValue)}
      defaultValue={value}
      autoCapitalize={type ? 'none' : 'words'}
      keyboardType={type ? type : 'default'}
      editable={defaultValue ? false : !isDisable}
    />
  );

  const getRules = () => {
    if (isRequired) {
      return {required: 'This is required'};
    }
  };

  return (
    <>
      <Text style={styles.label}>
        {label}
        {isRequired && <Text style={styles.required}>*</Text>}
      </Text>
      <Controller
        rules={getRules()}
        name={name}
        control={control}
        render={renderTextInput}
        defaultValue={''}
      />
    </>
  );
```

**Comment by bluebill1049** [comment]
@manongguard looks about right to me. it shouldn't be slowing down the app tho, maybe worth reproducing that in an expo sandbox.

**Comment by manongguard** [comment]
> @manongguard looks about right to me. it shouldn't be slowing down the app tho, maybe worth reproducing that in an expo sandbox.

Its fast when its only few (4-10 textinputs) but if I multiplied this to 20 or more, delays are noticeable.

**Comment by bluebill1049** [comment]
> > @manongguard looks about right to me. it shouldn't be slowing down the app tho, maybe worth reproducing that in an expo sandbox.
> 
> Its fast when its only few (4-10 textinputs) but if I multiplied this to 20 or more, delays are noticeable.

you need to reproduce that. this is not an issue with this codesandbox: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r
