### ISSUE TITLE
Controller causes "Cannot read property 'split' of undefined" 

### ISSUE THREAD

**Issue by powah** [react-hook-form/react-hook-form#1489]
**Describe the bug**
Exception occurs if default value for a field is provided via `useForm`'s `defaultValues`. 

**To Reproduce**
1. Visit codesandbox link provided below
2. See error

**Codesandbox link (Required)**

- [CodeSandbox](https://codesandbox.io/s/react-hook-form-controller-template-l7z8w) for reproducing

**Comment by bluebill1049** [comment]
read the doc, you are missing the name.

**Comment by h0jeZvgoxFepBQ2C** [comment]
You are right, but it would be cool if you could show a nicer error message!

**Comment by ItaloSa** [comment]
I agree with @h0jeZvgoxFepBQ2C. I spent a lot of my time figuring out what I suppose to do until find this issue.
