### ISSUE TITLE
Controller defaultValue prop does not override form defaultValues

### ISSUE THREAD

**Issue by powah** [react-hook-form/react-hook-form#1490]
**Describe the bug**
As documentation about `Controller` prop `defaultValue` states: 

> Note: when provided, this take priority over useForm defaultValues for given key.

but it appears it's not the case (please check provided CodeSandox link)

**Codesandbox link (Required)**

- [CodeSandbox link](https://codesandbox.io/s/react-hook-form-controller-bi819) to reproduce

**Comment by bluebill1049** [comment]
updated. thanks
