### ISSUE TITLE
Inconsistent behaviour on React Native after v5.5.2

### ISSUE THREAD

**Issue by priyankpat** [react-hook-form/react-hook-form#1494]
**Describe the bug**
There are 2 inconsistent behaviours that i've noticed with the release of 5.5.2.
1. When the field is required and **true** parameter is passed in with setValue function:
- It does not submit the form, rather it throws required error.

2. When the field is required and **true** parameter is not passed in with setValue function:
- It submits the form with correct value once and then throws required error for the next submit request.

**To Reproduce for behaviour 1**
1. Go to https://snack.expo.io/0iiyQffdS
2. Enter first/last name for example 1
3. Press submit
4. Throws required error

**To Reproduce for behaviour 2**
1. Go to https://snack.expo.io/0iiyQffdS
2. Enter first/last name for example 2
3. Press submit
4. Alert is displayed of JSON values
5. Press submit again
6. Throws required error

**Codesandbox link (Required)**
https://snack.expo.io/0iiyQffdS

**Expected behavior**
Shows alert with correct values populated in a JSON on every submit attempt.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 81

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 9
 - Browser: chrome
 - Version: 74

**Additional context**
This behaviour is only happening post 5.5.2 release.

**Comment by bluebill1049** [comment]
@priyankpat Please register those fields in the `useEffect`, and let me know if this issue still persists. I will need to update the video on the website.

**Comment by priyankpat** [comment]
@bluebill1049 using [useEffect](https://snack.expo.io/6L6BNVphh) hook seems to have solved the problem. Thanks for the pointer! Closing this issue.

**Comment by MartinCerny-awin** [comment]
@priyankpat Could you please share how you fixed the issue? Thanks

**Comment by bluebill1049** [comment]
@MartinCerny-awin 
```
useEffect(() => {
  register('name')
}, [register])
```
