### ISSUE TITLE
Efficient subscription to field value changes 

### ISSUE THREAD

**Issue by GrigoryanSasun** [react-hook-form/react-hook-form#1495]
**Is your feature request related to a problem? Please describe.**

Hey everyone. First of all, I would like to thank all of you for putting a great amount of effort to create this library! I really love how simple yet effective `react-hook-form` is!

One of the issues that I have noticed is that using `watch` to listen to field value changes results in unnecessary re-renders. Consider the example [here](https://codesandbox.io/s/pensive-breeze-w1955?file=/src/Field.js).

I have created a `Field` wrapper for text inputs. The code inside the `Field` component watches the field value changes for fields defined by `fieldsToWatch` prop. In the `App.js` file, I have defined 5 fields. `Field2` is watching for `Field1` value changes. 

The issue is that if the `Field1` value is changed, ALL `Field` wrappers are re-rendered (I have added a console log in the render method to check that).

I found out that that this happens because field value changes alter the `watch` function reference which in turn results in a re-render.

This is a serious limitation and will cause performance issues for large forms.
I have created a [sandbox](https://codesandbox.io/s/affectionate-waterfall-j3b6g?file=/src/App.js) with 1000 fields which demonstrates the issue (just try to change the value for `Field1` and notice the overall lag).

Ideally, when `Field1` value is changed, we would want to re-render only `Field1` and `Field2` if there is a dependency between them.

**Describe the solution you'd like**
One of the solutions would be to provide a `subscribe` function which accepts the list of fields to watch for and a callback which is executed with the whole form data when any of the fields provided in the first argument is changed. The `subscribe` function returns an `unSubscribe` function which should be called when the consumer is no longer interested in listening to field value changes. From the consumer's standpoint, the code looks like this:

```
const { subscribe } = useFormContext();
React.useEffect(() => {
 const unSubscribe = subscribe(['field1', 'field2'], (formData) => {
      // Called when either field1 or field2 is changed.
 } 
 return unSubscribe; 
}, [subscribe])
``` 

This could be implemented by maintaining a subscription Map. `Map`'s keys are the field ids of the fields that we are watching for and the values are `Set`s which contain the callbacks which should be executed when the field is changed. When a field value is changed, we retrieve the callbacks which are registered for that field and execute each one of them by passing the whole form data to the callback.

**Describe alternatives you've considered**
I haven't considered any alternatives yet.

**Additional context**
We are using `react-hook-form` to efficiently render large forms in our application. Fields might have dependencies on other fields (e.g. disable a field depending on other field's value, make a field required depending on other field's value, etc). We would really like to help to improve the performance of the library. In fact, we have already implemented the solution that I have suggested above in one of our packages to support dependent fields in an efficient manner. I will be happy to open an MR with the necessary changes.

**Comment by bluebill1049** [comment]
Hey @GrigoryanSasun 

Thanks for your detailed feature request. This is exactly what we are trying to solve at this stage, in fact we have a ticket on our V6 board for this, so I will probably close this issue (feature request). Here is the insight of our implementation, nothing is confirmed and still under investigation stage.

```
function IsolateRender() { 
  // `useWatch` will unsubscribe to the change when it's getting unmounted
  const { test } = useWatch({
    control, 
    name: 'test' // this argument is the same as watch API
  });

  return <p>{test}</p>
}
```

Let me know your thoughts on this implementation/api.

**Comment by GrigoryanSasun** [comment]
Hey @bluebill1049  

Thanks for the quick response. This is exactly what I am looking for. Also, are you considering to implement a similar API for error subscription? It seems that the `errors` object contains all the error forms and will force unnecessary re-renders, too.

**Comment by bluebill1049** [comment]
No, I don’t think so.

**Comment by bluebill1049** [comment]
going to close this issue, you can keep an eye on the progress of V6: https://github.com/react-hook-form/react-hook-form/pull/1471

**Comment by powah** [comment]
I encountered the same issue with `errors` and wanted to ask the same as @GrigoryanSasun did. @bluebill1049 why watchable `errors` isn't a consideration? Errors are needed deeply and trigger FormContext rerender quite often and I don't see the other easy way to retrieve them. Any advice here?
