### ISSUE TITLE
The value of file input is reset on second render in versions >= 5.5.2

### ISSUE THREAD

**Issue by ahce** [react-hook-form/react-hook-form#1496]
**Describe the bug**

When the file is selected, on first render the value is ok, but in second render the it's reset.

![image](https://user-images.githubusercontent.com/12452003/80297453-0e493180-8751-11ea-908c-489d68a6f914.png)

**To Reproduce**

1. Select file
2. Check the console log
3. Try again with version 5.5.1

**Codesandbox link**
- https://codesandbox.io/s/react-hook-form-file-bug-x1hzp

**Expected behavior**

v5.5.1 behavior.

![image](https://user-images.githubusercontent.com/12452003/80297485-510b0980-8751-11ea-98c3-155ca565bf5b.png)

**Desktop:**
 - OS: Windows 10
 - Browser chrome
 - Version 81

**Comment by bluebill1049** [comment]
The problem is due to register gets re-run each render: 
correct usage: https://codesandbox.io/s/react-hook-form-file-bug-m83qr
or register at `useEffect`

**Comment by ahce** [comment]
> The problem is due to register gets re-run each render:
> correct usage: https://codesandbox.io/s/react-hook-form-file-bug-m83qr
> or register at `useEffect(...)`

Thanks!, register on mount effect works!
