### ISSUE TITLE
Add possibility to constantly revalidate touched field on change

### ISSUE THREAD

**Issue by vladshcherbin** [react-hook-form/react-hook-form#1498]
**Is your feature request related to a problem? Please describe.**
At first, I thought it's a bug, however after reading docs a few times I believe it's intended. When `mode: 'onBlur'` and `reValidateMode: 'onChange'` field validation works like this:

validation for field using yup, required, min 3
- enter input text
- on blur it's validated, error added
- after you change input text, it's revalidated until error is gone
- when error is gone, input text is not revalidated on change until it's not blurred and has error

So, if a user inputs `aa`, he will receive min length error. When he changes value to `aaa`, the error is gone. Now he hits backspace so the value is again `aa` and no error appears until blur again.

I find this confusing to user.

**Describe the solution you'd like**
I would like to be able to revalidate touched input field, no matter has it error or not. So it's not *revalidate on change until you have error*, but a true *always revalidate on change*.

**Describe alternatives you've considered**
Current behavior is confusing to user, so I don't consider it.

**Additional context**

Here is my codesandbox with test:

https://codesandbox.io/s/gracious-elgamal-i2jjq?file=/src/App.js

react-hook-form 5.6.0

**Comment by bluebill1049** [comment]
Thanks for your request feature, however, I don't think at this stage we will need more mode or methods to trigger validation, consider the validation in this lib is quite flexible, `mode` `reValidateMode` and if those don't work for you then you can switch to manually `triggerValidation` the validation and combined with `formState`.

**Comment by vladshcherbin** [comment]
@bluebill1049 setting manually such validation requires more work and is provided by default in other form libraries for a long time, that's why I was asking for same kind of validation here. Are you really sure it's not possible to add it as a new value in `reValidateMode` or something? 😢

**Comment by vladshcherbin** [comment]
Actually, `mode: 'onChange'` kinda works this way, my bad 🤔

**Comment by bluebill1049** [comment]
> Actually, `mode: 'onChange'` kinda works this way, my bad 🤔

That's whats I thought as well and perhaps combined with touched fields.

**Comment by vladshcherbin** [comment]
@bluebill1049 yeah, after second look found related issues https://github.com/react-hook-form/react-hook-form/issues/1430, https://github.com/react-hook-form/react-hook-form/issues/1321. However, I also need this: https://github.com/react-hook-form/react-hook-form/issues/1222, so it validates in all modes.

Thank you for such quick response and suggestions, looking forward to see `all` mode or multiple ones.

❤️

**Comment by bluebill1049** [comment]
working on the next major version at the moment will put #1222  on the next todo 👍
