### ISSUE TITLE
Problems with Field Array when used with react-beautiful-dnd

### ISSUE THREAD

**Issue by FatehAK** [react-hook-form/react-hook-form#1500]
**Describe the bug**
I am facing an issue with Field Arrays when the used alongside with the react-beautiful-dnd. I am trying to achieve drag and drop with the Field Array. But there is an issue that while dragging and dropping the field key of a Controller component within the field array is removed.

**To Reproduce**
1. Go to 'https://codesandbox.io/s/modern-shape-6v9d6?file=/src/App.js'
2. Drag first point down to the second point
3. Click on the debug button which calls getValues()
4. You can see that the 0th element of the Field Array has lost the `Address` key which is Controller Component

**Codesandbox link (Required)**
https://codesandbox.io/s/modern-shape-6v9d6?file=/src/App.js

**Expected behavior**
Field key of Controller component should not get removed after drag and drop completed.

**Additional context**

**Comment by bluebill1049** [comment]
I would recommend not to use `useFieldArray` with drag and drop task, take a look this example with custom register: https://react-hook-form.com/advanced-usage#Workingwithvirtualizedlist

**Comment by FatehAK** [comment]
It seems to work fine with uncontrolled components. Its just the Controller component that has this issue when used with Field Array.  How do you use custom register for a Controller component?

**Comment by bluebill1049** [comment]
> How do you use custom register for a Controller component?

as building your own Field Array, but register input inside of `useEffect` so it's like a virtual input.

**Comment by bluebill1049** [comment]
also, your CSB is broken as well, but it will be tricky to get it working with external D&D libs.

**Comment by FatehAK** [comment]
Updated the CSB Link : https://codesandbox.io/s/modern-shape-6v9d6?file=/src/App.js
Damn that's too bad useFieldArray seems so nifty.

**Comment by bluebill1049** [comment]
I will take a look at it anyhow @FatehAK, but it's an external dependency so it probably won't work nicely.

**Comment by FatehAK** [comment]
Thanks for the prompt replies @bluebill1049 I understand. I will look into it further

**Comment by FatehAK** [comment]
I think DnD clashes with the Controller components, it works perfectly fine when uncontrolled (when using a simple input component). I've been at this for hours can you help me with the sandbox on this. Thanks

**Comment by FatehAK** [comment]
On further investigation, I found that this is isn't a DnD issue at all. There is an issue with the `swap` and `move` methods calling them to swap the fields and then calling getValues() later on button click seems to afffect the Controller components(their key is removed) and then key gets added back on any subsequent field change. 
Please checkout this sandbox: 
https://codesandbox.io/s/magical-meninsky-s0y70?file=/src/Panel.js
I've removed all DnD related code to focus on just that.
To demonstrate please enter values in the two fields and click on `swap`. Then click on `debug` to print the values, you can see that the `Address` key is lost on the 0th element

**Comment by bluebill1049** [comment]
oh, nice! interesting found I haven't got time to looking into it yet, happy for you to drive the fix too. questions: why it's working for uncontrolled?

**Comment by FatehAK** [comment]
Exactly swap/move work fine for uncontrolled inputs. I don't get it either. Can you have a looksie when you got time?

**Comment by bluebill1049** [comment]
What're the steps to reproduce the issue in your codesandbox above? @FatehAK

**Comment by FatehAK** [comment]
1) Enter values in the first text field for both points (1 & 2)
2) Click on the `Swap` CTA
3) Click on `Debug` CTA
4) Check console you can see that the 0th element in the FieldArray `BookingPoints` doesn't have the `Address` key on it

**Comment by bluebill1049** [comment]
Try this CSB: https://codesandbox.io/s/romantic-kare-igm7u?file=/src/src/controller.tsx

**Comment by FatehAK** [comment]
Works fine!! Was that a bug? Can you describe what happened?

**Comment by bluebill1049** [comment]
@FatehAK I am still working on it.

**Comment by FatehAK** [comment]
Thanks @bluebill1049 for your time on this. Found another issue in your CSB where the `Address` key of the Controller component doesn't show up. To reproduce:
1. Directly click on the `Swap` CTA without entering and touching any of the fields.
2. Click on the `Debug` CTA
3. View console you can see that the `Address` key lost on 0th element same as before

**Comment by bluebill1049** [comment]
that's all good @FatehAK thanks for testing too: https://codesandbox.io/s/romantic-kare-igm7u?file=/src/App.js let me know if this solve the problem.

**Comment by FatehAK** [comment]
Just tested works well and above issue seems to be resolved as well. Awesome @bluebill1049. Will there be a beta or something which I can use?

**Comment by bluebill1049** [comment]
@FatehAK i will release a beta version for you.

**Comment by bluebill1049** [comment]
`5.6.1-beta.1`

**Comment by FatehAK** [comment]
Thanks @bluebill1049  much appreciated.
