### ISSUE TITLE
Anyone else confused by the form builder?

### ISSUE THREAD

**Issue by dandv** [react-hook-form/react-hook-form#1504]
**Is your feature request related to a problem? Please describe.**
I've just learned about this library and was happy to see it has a [form builder](https://react-hook-form.com/form-builder). I went to that page, and... was confused for several minutes. I've used tons of form builders before, when making survey and using other component libraries. But this one, confused the heck out of me :)

**Describe the solution you'd like**
It took me a good minute or two to realize where the confusion came from - there was no form preview! Initially I thought the form was the middle column, but that didn't match with the fields on the left? Then I figured the middle column lets you *create* fields, but where do you put them? And where do you drag fields from the left column?

**Describe alternatives you've considered**
Here are some intuitive form builders you can check out right away:
* https://codepen.io/travist/full/xVyMjo/ - interactive open-source form builder from [formio.js](https://github.com/formio/formio#form-building--rendering-demo)
* https://www.formstack.com/ppc/online-forms - commercial form builder, see the video on the landing page

**Additional thoughts**
Would be interesting to see the bounce rate on the form builder page, or run a free test on https://usabilityhub.com/ to see how many users never manage to build the form they want.

**Comment by bluebill1049** [comment]
Thanks for your effort to drop your complaints about the builder page, this is a form lib consider the builder as a bonus.

**Comment by dandv** [comment]
I was just providing some suggestions, feel free to ignore them :)

And thanks for the great library! I like it much more than formik and others.

**Comment by bluebill1049** [comment]
Thanks for your suggestion. I will improve the builder after lib's next major version.
