### ISSUE TITLE
Error shows only after first attempt to submit

### ISSUE THREAD

**Issue by john-law** [react-hook-form/react-hook-form#1505]
### Preamble
Thank you for this library. I'm just experimenting but it seems amazing. Also: great Docs/Website.

### Bug Description
Error only shows after a first attempt to submit the form. After an attempt to submit (i.e. clicking 'Save' independently of whether it's valid or not) it works as expected.

### Basic Reproducible Example

[Link to Codesandbox](https://codesandbox.io/s/determined-currying-mj972?file=/src/App.js)

Attaching the code here for convenience:
```javascript
import React from "react";
import "./styles.css";
import { useForm } from "react-hook-form";

export default function App() {
  const { handleSubmit, register, errors } = useForm();

  const onSubmit = data => {
    console.log(data);
  };

  return (
    <div className="App">
      <form onSubmit={handleSubmit(onSubmit)}>
        <input
          name="name"
          type="text"
          ref={register({
            required: "Please provide a name"
          })}
        />
        {errors.name && errors.name.message}

        <input name="description" type="text" ref={register} />

        <button type="submit">Save</button>
      </form>
    </div>
  );
}
```
### Demonstration
![issue](https://user-images.githubusercontent.com/42075519/80319435-19ab6400-8808-11ea-8835-3472efedf715.gif)

### Expected Behavior
I would expect the error message to show after going from the first field (which is required) to the second field i.e. when 'name' is set to 'touched'.

**System:**
 - OS: MacOS
 - Browser: Firefox v75.0
 - Version: 5.6.0

**Comment by bluebill1049** [comment]
you want to switch the mode to `onChange`

**Comment by john-law** [comment]
Thank you for the response. I don't necessarily want to have the `onChange` event listeners attached from the beginning, I wanted the error after the field is touched, which even with `onChange` mode won't work.

I reckon I could work around this maybe by using `formState()` perhaps, but I thought this was the default behavior from the example in the 'Form Builder', i.e., if I "skip" the first field I get an error feedback, which I get now from your response and going trough the examples in the repo might not the expected behavior.

What do you recommend to implement this? Check for changes in the `touched` state and use it to trigger validation in the touched field?

**Unrelated**
As I was going trough the API Docs, I noticed two very tiny typos (in bold):

> Validation will trigger on the change event with each input, and lead to multiple re-renders. Warning: this often comes with a significant impact on **performances**. [should be singular]

> Reason: optional chaining is getting widely adopted and allows better support for types**..** [should only have one period]

**Comment by bluebill1049** [comment]
I think you can still fire those errors with `onChange` but have a condition with formState's touched.

**Comment by john-law** [comment]
As clarified, the reported issue is the expected behavior. Issue closed.
