### ISSUE TITLE
Custom Validation on a single field?

### ISSUE THREAD

**Issue by IPWright83** [react-hook-form/react-hook-form#1506]
I'm not sure if I'm finding the docs confusing or whether it's not possible/documented.

I want to run some custom validation, which I believe I can do with a `customResolver`. However I only want to do this for some custom fields, the majority of the fields I'm using the built in validation works fine. Is it possible to achieve this as I can only see it being done at the `useForm` level which applies to all fields?

**Comment by bluebill1049** [comment]
you have to use either build in or validation resolver/schema.
