### ISSUE TITLE
[TS] Types of property 'setError' are incompatible.

### ISSUE THREAD

**Issue by kyle-mccarthy** [react-hook-form/react-hook-form#1507]
**Describe the bug**
This is a ts typings related bug. If the default values contain an array, types of setError are incompatible. This happens when tsconfig has strict set to false, in strict mode the TS error doesn't occur.

```
Type '{ children: Element; register<Element extends FieldElement<MyFormValues> = FieldElement<MyFormValues>>(): (ref: Element) => void; register<Element extends FieldElement<...> = FieldElement<...>>(validationOptions: Partial<...>): (ref: Element) => void; register(name: string, validationOptions?: Partial<...>): void; r...' is not assignable to type 'FormContextValues<MyFormValues | Record<string, unknown>>'.
  Types of property 'setError' are incompatible.
...
```

**Codesandbox link (Required)**
https://codesandbox.io/s/strange-flower-bs6u3?file=/src/MyForm.tsx

**Comment by bluebill1049** [comment]
@kotarella1110 could you please take a look this one?

**Comment by kotarella1110** [comment]
I will look into this.
