### ISSUE TITLE
watch function not updating when user enters value in watching field

### ISSUE THREAD

**Issue by rajpraful** [react-hook-form/react-hook-form#1511]
Assume we are using watch function to validate two fields 'password' and 'repeat password' and repeat password has a validation that its value should be same as a watch(password).

When the user enters wrong password in 'repeat password' and clicks 'submit', an error message is displayed. After seeing the error message, if the user changes the value of 'password' to match with 'repeat password', the error message is still displayed even though passwords are matching now.

So, the watch function(in 'repeat password') is not updating the watching field value when the focus is on watching field (password).

1. enter '12345678' in 'password' field and '123456789' in 'repeat password' field.
2. click on 'Submit' and observe the error message displayed
3. change the value in 'password' field to '123456789'
4. Observe error message is still displayed
5. Click on 'repeat password' field and click outside the form
6. Observe that error message is now gone

- https://codesandbox.io/s/react-hook-form-password-match-check-standard-validation-eo6en?from-embed

**Expected behavior**
When the value changes in field 'A;, validating of other fields which are watching field 'A' should run

**Desktop (please complete the following information):**
 - OS: windows 8.1
 - Browser chrome
 - Version 80

![2020-04-27_13-45-14](https://user-images.githubusercontent.com/50992602/80349756-566d6e80-888d-11ea-92c2-9c8af94931b9.gif)

**Comment by bluebill1049** [comment]
can you please test on a later version? this is version 3 and we on v5 plus.

**Comment by bluebill1049** [comment]
also, pay attention to the validation mode as well, currently, it's `onSubmit` by default.

**Comment by rajpraful** [comment]
@bluebill1049 Tried on version 4.7.2 with latest onSubmit method, still no luck

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-password-match-check-standard-validation-tgm4k?file=/src/index.js

**Comment by rajpraful** [comment]
@bluebill1049 tried in above link you sent 
![2020-04-27_14-23-16](https://user-images.githubusercontent.com/50992602/80353258-bb779300-8892-11ea-8056-8d5d7015d941.gif)

**Comment by bluebill1049** [comment]
the validation is attached to the field 2

**Comment by bluebill1049** [comment]
how did you with this? i don't think there is an issue with `watch` as what the issue named.

**Comment by bluebill1049** [comment]
perhaps you want to `triggerValidation` on input 2 while at input 1?
