### ISSUE TITLE
Infer handleSubmit argument from validation

### ISSUE THREAD

**Issue by outerlook** [react-hook-form/react-hook-form#1514]
Hi!

I frequently double check types, if I consider our validation resolver / yup schema is checking before running handleSubmit.

Consider an review to be sent to server, I will try to explain with a type code snippet, tell me if this isn't explained enough please.

```
type Review = {
  description?: string;
  score?:  1 | 2 | 3 | 4 | 5
}
type ValidatedReview = Required<Review>
type validateReviewFunction = (v: Review) => ValidatedReview

type submitMethodAsIs = (v: Review) => void
type submitMethodIThinkReallyHappens = (v: ValidatedReview) => void
```

it could be infered using `Yup.InferType` if schema provided, or from validation resolver if provided, or as is if none provided.

What do you think, is it compatible? Do you see any downside on this?

Thanks for your work, it is incredible.

**Comment by kotarella1110** [comment]
@outerlook Could you provide codesandbox and explain it to me in a little more detail?
If use `Yup.InferType`, we need to add yup to peerDeps. We don't want to do this.

**Comment by outerlook** [comment]
Sure! I will do this tomorow, ok? 

About yup, I've read you are planning to stop directly supporting, but that's not an issue, I just used it as an example.

 The important part is to pass the resulting type of the validation, and not the initial form values, as we're sure fields marked as required on validation should be non nullable... right?

**Comment by kotarella1110** [comment]
@outerlook No rush. Take your time 👍

**Comment by outerlook** [comment]
Here it is! 

I didn't implement anything except submit handling to keep it to the point.
https://codesandbox.io/s/ts-react-hook-form-validated-submit-1w15e?file=/src/App.tsx
Does this clarify my question?

I know currently it doesn't make me do wrong things in my code, but it leads to unnecessary checks before sending to server, if type could be infered the resulting schema from validation resolver, it would solve this...

It is simple to check for few values, but starts to become a problem with more properties and more forms in an app, as we would have to check twice (by definining a validation schema, and between submitting form and sending to server)

Thanks in advance!
*Just used yup for simplifying codesandbox.

**Comment by kotarella1110** [comment]
@outerlook Why is `score` optional?
`defaultValues` ​​properties are all optional (`DeepPartial<Review>`), so it is unnecessary to do `score` optional.
What about fixing it as follows?

```ts
type Review = {
  description: string;
  score: 1 | 2 | 3 | 4 | 5;
};
const initialValues = { description: "", score: undefined };
```

[CodeSandbox](https://codesandbox.io/s/ts-react-hook-form-validated-submit-bvv1m?file=/src/App.tsx)

**Comment by outerlook** [comment]
Yes, it does solve! Thanks for that, and sorry for misreading this. 

Since I migrated my forms to use RHF I thought it behaves the same way on initial values, then I didn't see it.

I think there's no issue, then! Thanks again
