### ISSUE TITLE
Reset not working since v5.4.0

### ISSUE THREAD

**Issue by rasgo-cc** [react-hook-form/react-hook-form#1516]
**Describe the bug**
Looks like the reset stopped working since 5.4.0 (or more specifically since 5.3.2-beta1, as tested on CSB)

**To Reproduce**

https://codesandbox.io/s/react-hook-form-reset-t5py7?file=/src/App.js
Switch the version of `react-hook-form`. 

**Expected behavior**
The reset works at least on 5.2.0 (version I was using, before upgrading to 5.6.0).

**Comment by bluebill1049** [comment]
<img width="923" alt="Screen Shot 2020-04-28 at 8 55 09 am" src="https://user-images.githubusercontent.com/10513364/80428765-fd094c00-892d-11ea-991c-bb3f8a11abf8.png">
