### ISSUE TITLE
Errors only get cleared after async handleSubmit call has ended

### ISSUE THREAD

**Issue by svenlombaert** [react-hook-form/react-hook-form#1518]
**Describe the bug**
When clicking the submit button, the form only calls the handleSubmit when it has no errors. My handleSubmit callback is an async function which does an api request. The errors variable, returned from useForm only gets cleared after my callback is finished

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-onsubmit-await-eesr6?file=/src/App.js
2. Click on 'submit' with blank fields
3. See the errors
4. Fill in form correctly
5. Errors get cleared after Promise has resolved

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-onsubmit-await-eesr6?file=/src/App.js

**Expected behavior**
Since the handleSubmit callback only gets triggered when the form is valid, I would think the errors are cleared before submitting

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: latest iOS
 - Version: ^5.4.2 of react-hook-form

**Comment by bluebill1049** [comment]
`setValue("name", e.currentTarget.value, true)` otherwise validation is not going to be triggered 
https://react-hook-form.com/api#setValue

**Comment by svenlombaert** [comment]
But that is not what I want, nor my problem. I want my validation only to be triggered when submitting, so that's fine as is. I just want my errors to be cleared when the form is valid, BEFORE it's doing the onSubmit callback, and not after it. Since the callback only gets executed when the form is valid, that would be the logical order?

**Comment by bluebill1049** [comment]
This is expected behavior for this lib:

-> nothing fill
-> send
-> handleSubmit 
-> Errors

------

-> fill form
-> send
-> handleSubmit
-> pass
-> invoke onSubmit.

**Comment by svenlombaert** [comment]
Okay, I'll clear them manually then with clearError. Thanks

**Comment by bluebill1049** [comment]
hmmm, i do see your concern here because errors should be cleared after validation is valid. let me think about it.

**Comment by svenlombaert** [comment]
Well, for me that would be the logical flow indeed, re-render before the onSubmit happens.
