### ISSUE TITLE
unexpected result of getValues on a single field with defaultValues

### ISSUE THREAD

**Issue by gaetano-guerriero** [react-hook-form/react-hook-form#1519]
**Describe the bug**
Calling `getValues()` on a single field doesn't always return the same value
that would be contained in the getValues() response with no arguments.
**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-useform-template-1dk5o
2. Look at the console statements

**Expected behavior**
I would expect this to always be true:
`getValues().name === getValues('name')`

Instead the values are different on the first render.

**Comment by CyanoFresh** [comment]
wow faced this issue and pushed a fix 4 hours ago
Can you release, please?

**Comment by bluebill1049** [comment]
I can't release a proper version, cause I work in the day time and won't be able to do any hotfix if something goes wrong, but happy to release a beta for you.
