### ISSUE TITLE
FormState Proxy is incomplete and crashes Jest snapshot serializer

### ISSUE THREAD

**Issue by Photonios** [react-hook-form/react-hook-form#1520]
**Describe the bug**
The `Proxy` object returned for `formState` is incomplete. It returns `{}` for any unknown property which breaks expected behaviour in applications.

An example where this is hugely problematic is in [Jest](https://jestjs.io/) snapshots. Various snapshot serializers match on the `formState` object when trying to serialize is because they believe that the object has the property they need. Tests end up crashing. This is the sympton I experienced after I upgraded `react-hook-form` to the latest version.

Here's an example that demonstrates the unexpected behaviour:

```
const proxy = new Proxy({ a: 1 }, {
    get: (obj, prop) {
          if (prop in obj) {
              return obj[prop];
          }

          return {};
    },
});

console.log(proxy.bla); // prints `{}`, which should be `undefined`
console.log('bla' in proxy);` // prints true, which should be false
```

**To Reproduce**
1. Create a Jest snapshot test using `useForm()`:

```
import React from 'react';
import { useForm } from 'react-hook-form';
import ShallowRenderer from 'react-test-renderer/shallow';

test('that it works', () => {
        const OtherComponent = () => null;

        const Component =  () => {
             const form = useForm();
             return <OtherComponent form={form} />;
        };

        const renderer = new ShallowRenderer();
        renderer.render(<Component />);
        expect(renderer.getRenderOutput()).toMatchSnapshot(); // this will crash
});
```

**Expected behavior**
The Proxy object should implement [the trap for the `in` operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/has) and return `undefined` for unknown properties.

**Additional context**
One could argue this is a bug in the Jest snapshot serializer and that it should detect this kind of behaviour. However, one the fundamental concepts behind Proxy objects is that they cannot easily be detected and behave like normal objects. The `formState` proxy object not behaving as a normal object deviates from that concept.

**Workaround**
For anyone experiencing the same problem, I've temporarily installed a custom Jest serializer that detects proxy objects and clones them into normal objects:

```
import util from 'util';
import { cloneDeep } from 'lodash';

class ProxyObjectSerializer {
    test(value) {
        return util.types.isProxy(value);
    }

    print(value, serialize) {
        return serialize(cloneDeep(value));
    }
}

expect.addSnapshotSerializer(new ProxyObjectSerializer());
```

**Comment by bluebill1049** [comment]
Thanks for the detailed issue. 

why should it return `undefined`? FormState default is `{}`

**Comment by Photonios** [comment]
See the first example. When the formState object is passed to somewhere and something tries to access an unknown property, it should get `undefined`.

```
const form = useForm();
console.log(form.formState.hahaha)
```

At the moment, the sample above will log `{}` which is inconsistent with how things work if the proxy _is not used_. In which case the sample above logs `undefined`.

The point is that although the default form state is `{}`, the default value for unknown attributed _on the form state_ should be `undefined`.

**Comment by bluebill1049** [comment]
Thanks @Photonios Question: what's the reason to read attributes other than what we listed (formState)?

**Comment by Photonios** [comment]
https://github.com/facebook/jest/blob/d425a49bd575e7167bc786f3c4f2833589091fa1/packages/jest-snapshot/src/mock_serializer.ts#L45

See the sample of a Jest snapshot test I gave in the "To Reproduce" section. In that case we're creating a test for a React component that passes the entire form object down to another component as a prop.

In the test, we render using React's test renderer and try to snapshot the output. The component tree is going to be serialized by Jest. It'll go over all the nodes in the tree and generate a representation of the tree to save it as a snapshot. This includes going over all the props and serializing them as well.

When serializing the props, it'll encounter the `form` prop and try to serialize it. Jest serializes objects by passing the object to all registered serializer. Each serializer has a `test` function which returns whether they're able to serialize the specified value.

One of the default, built-in serializers is the serializer for mock functions. It determines whether something is a mock function by checking for the existence of the `_isMockFunction` property: https://github.com/facebook/jest/blob/d425a49bd575e7167bc786f3c4f2833589091fa1/packages/jest-snapshot/src/mock_serializer.ts#L45

When Jest is trying to serialize the component tree, it'll eventually try to serialize the props and pass the formState object to each serializer to see if it matches. In this case, the mock serializer I linked will matches because it thinks the form state object has a `_isMockFunction` property. It'll try to serialize it and crashes because the form state object is _not a mock function_.

This sounds like an edge case and it can also be fixed by changing Jest to check if `_isMockFunction` is `true` instead of truthy. Although this would work, it's kind of strange to do this considering that the default behavior for objects in JS is to return `undefined` for unknown properties. The assumption Jest makes here is not surprising at all and it is quite a common one.

I am afraid that isn't just Jest that gets bitten by this issue. There are plenty of other serializers, debugging tools etc out there that make such assumptions and react-hook-form breaks this very common assumption by returning `{}` for unknown properties. The Proxy should behave as a proxy for the underlying object as much as possible so that whoever receives the form state as an object does not have to account for this and can treat it like any other object, Proxy or not.

**Comment by bluebill1049** [comment]
Thanks for your detailed explanation, I do get the idea because the nature of JS `object`. however, this is specific for this lib use case. I don't think it's a bug, rather intended to be. I have also released a beta with what you suggested, it doesn't really solve the test failure.

**Comment by Photonios** [comment]
Another good reason to fix is the fact that behavior is inconsistent between using react-hook-form in an environment in which `Proxy` is available and in an environment where it is. If `Proxy` is not available, `react-hook-form` returns the `formState` as a normal object. In which case `form.formState.HELLO` returns `undefined`.

> I don't think it's a bug, rather intended to be.

Why is it intended to be like this? What practical purpose does it serve?

> it doesn't really solve the test failure.

It does. The codesandbox link you posted in a comment on the PR I opened: https://codesandbox.io/s/strange-shirley-pdrhr?file=/src/app.test.js

The sandbox is a poor example because the `Proxy` does not get activated. `window.Proxy` is `undefined`. Which proofs my point. Behaviour changes depending on whether the Proxy is used or not. With a quick trick, we can demonstrate that the test fails when using react-hook-from v5.6.0:

https://codesandbox.io/s/elastic-khorana-2o27t?file=/src/app.test.js

If we try the same thing with the beta you released, it passes:

https://codesandbox.io/s/eloquent-night-q0wcb?file=/src/app.test.js

> however, this is specific for this lib use case.

Even if it is, there's still good motivation to fix it. Jest is almost the de-factor standard when it comes to testing React components. It is very widespread. react-hook-form suddenly breaking compatibility with it is reason enough to fix it IMHO. Then there's also the issue of inconsistency in behaviour depending on whether Proxy is used or not.

**Comment by bluebill1049** [comment]
> The sandbox is a poor example because the Proxy does not get activated. window.Proxy is undefined. Which proves my point. Behaviour changes depending on whether the Proxy is used or not. With a quick trick, we can demonstrate that the test fails when using react-hook-from v5.6.0:

That example is what you posted above.

**Comment by bluebill1049** [comment]
> Why is it intended to be like this? What practical purpose does it serve?

because why would you access formState with other attributes then what the lib support in the first place? adding a proxy layer was try to reduce the re-render which the user may not subscribe to, if the proxy is the issue, just turn it out or mock it return `undeinfed`.  I do appreciate your detailed issue and PR to resolve this issue, I am just not sold with the extra check `has`.

**Comment by bluebill1049** [comment]
@JeromeDeLeon @kotarella1110 @stramel maybe it's worth to get your opinion on this as well.

**Comment by Photonios** [comment]
> That example is what you posted above.

Which triggers the failure if you run it in a plain Node.js environment. The codesandbox environment assumes the web, but fails to properly emulate it.

https://github.com/Photonios/react-hook-form-proxy-snapshot-failure

Here's an example repository that uses the exact example I provided. Cloning it and running the tests with `yarn jest` makes it fail. If you upgrade `react-hook-form` to `v5.6.0-beta.2` (which includes my fix). It works.

> > because why would you access formState with other attributes then what the lib supported in the first place?

You don't usually. However, the `formState` object might be passed to libraries, or code that is just part of your application that do not know it's a form state object and simply treat it like any other object. 

> I am just not sold with the extra check has.

The `has` hook is not required to make this work. It makes the implementation more complete and predictable though. I could remove it from the PR if that makes the change a deal breaker.

> if the proxy is the issue, just turn it out or mock it return undeinfed

Isn't it strange that a user would have to jump through hoops to get their tests working with react-hook-form ? At the very least, this would deserve a mention in the README.

**Comment by bluebill1049** [comment]
> You don't usually. However, the formState object might be passed to libraries, or code that is just part of your application that do not know it's a form state object and simply treat it like any other object.

I agree with above, but why it should access the right `formState`, you shouldn't do `formState.wahtever` in the first place.

> Isn't it strange that a user would have to jump through hoops to get their tests working with react-hook-form ? At the very least, this would deserve a mention in the README.

I agree, but this is first time that someone report issue around proxy with testing. I never had any issuing testing with `react-testing-library`

I am not killing your suggestion and purposely, most of the replies are in my own opinion. let the team members have their say as well.

**Comment by kotarella1110** [comment]
> https://github.com/react-hook-form/react-hook-form/issues/1520#issuecomment-621082501
> Another good reason to fix is the fact that behavior is inconsistent between using react-hook-form in an environment in which `Proxy` is available and in an environment where it is. If `Proxy` is not available, `react-hook-form` returns the `formState` as a normal object. In which case `form.formState.HELLO` returns `undefined`.

@bluebill1049 I agree with this opinion.
I think should be consistent behavior between environments where a proxy is available and use of react-hook-form in an environment where it is available.
What are your concerns when fixed this ?

**Comment by bluebill1049** [comment]
@kotarella1110 so my concern about: why to fix something is fundamentally wrong with the usage. 
I am not comfortable doing an extra check when it's not necessary.  

https://github.com/react-hook-form/react-hook-form/pull/1531/files#diff-a022cc055e49d2a0542ef4e2f4648587R1249

You can easily increase the lib size and perf when you take over all those extra checks inside react-hook-form. 

`register(21231231)` 

So should we place a catch for incorrect usage here as well? The list can go on and that's also why we had typescript support as well, to give users better DX so they don't do things that the lib doesn't support. We don't support `formState.otherStuff`, if your code is trying to access things outside of `formState`, we don't want to add an extra check. 

unless more users report this as an issue or see people upvote that PR, I don't think it's necessary for the "fix".

**Comment by bluebill1049** [comment]
I will lave this issue open for sometimes, and let's hear what's the community/users' feedback. Over time, if a lot of people encounter the issue with this `proxy`, then we will merge the PR (or at least improve that PR so it's not running each hook's invoke).

**Comment by Photonios** [comment]
As I've mentioned in another comment, I am up for removing the extra `has` trap I added in my PR and just returning `undefined` for unknown objects.

I understand your concerns with adding bloat for an edge case.

That would make the change a one liner. If not for the sake of fixing Jest snapshots, then for the sake of making the behaviour consistent between with/without proxy.

I'll update my PR to remove the extra `has` trap.

**Comment by bluebill1049** [comment]
now that's much better! my concern is over. Thanks for understanding, because 99% of users' probably won't need this fix. The same thing that I talked to @kotarella1110 if I can save 0.01% of perf for 99% users I will defend for them.
