### ISSUE TITLE
FormArray validation

### ISSUE THREAD

**Issue by R0nd** [react-hook-form/react-hook-form#1522]
**Is your feature request related to a problem? Please describe.**
Correct me if I'm wrong, but currently there is no way to validate a FormArray (require it to be non-empty, validate for min/max length etc). Requiring a non-empty array is a very common use case.

**Describe the solution you'd like**
FormArray should act more like a FormValue, with validation options and its own name.

**Comment by bluebill1049** [comment]
pretty sure you can with `validate` function.

**Comment by R0nd** [comment]
There's no `validate` in the documented `useFieldArray` signature:
>useFieldArray: ({ control?: any, name: string, keyName?: string = 'id' }) => object

**Comment by bluebill1049** [comment]
I think i miss your question, you want to validate the entire field array. you will have to do that at your app-level, we don't have validation in terms of size, you can check at the `handleSubmit` and `setError`.
