### ISSUE TITLE
Watch on FieldArray returns default values when emptied

### ISSUE THREAD

**Issue by R0nd** [react-hook-form/react-hook-form#1523]
**Describe the bug**
When using watch on a form with FieldArray populated with default values, watch returns those default values when all FieldArray items are removed by user.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-template-0m0ce?file=/src/index.js
2. Click on 'Append'
3. Remove all items with 'Delete'
4. Results in console

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-0m0ce?file=/src/index.js

**Expected behavior**
After appending new items, watch should return the new form values. This works as expected.
After removing all items, watch should return `{test:[]}`. Actual behavior: watch returns default values instead.

**Comment by bluebill1049** [comment]
what's expected behavior for `watch()`.

**Comment by R0nd** [comment]
The documented behavior for `watch()` is, quote:

>When defaultValue is not defined, the first render of watch will return undefined because it is called before register, but you can set the defaultValue as the second argument to return value.
>However, if defaultValues was initialised in useForm as argument, then the **first render** will return what's provided in defaultValues.

I don't think it should return default values on subsequent renders when user interaction made them undefined.

**Comment by bluebill1049** [comment]
we used to bake dirty logic inside the `watch`, this introduced unwanted side-effect, as for now, you will have to leverage form state `dirty`

**Comment by bluebill1049** [comment]
`watch('test', formState.isDirty ? '' : undefined)`;
