### ISSUE TITLE
<Controller> with onFocus erroneously reregisters itself

### ISSUE THREAD

**Issue by donocode** [react-hook-form/react-hook-form#1525]
**Describe the bug**
When using a <Controller> component with an onFocus callback it reregisters itself after validation failure (or if focused in react dev tools)

**To Reproduce**
1. Go to codesandbox link
2. Type some text in FirstName and click submit (don't add text to LastName)
3. See how the FirstName was reset
4. See how you can no longer type in FirstName

**Codesandbox link (Required)**

https://codesandbox.io/s/controller-issue-6gr5t?file=/src/index.js

**Expected behavior**
Having an onFocus callback should not cause the input to reregister on validation failure

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX High Sierra
 - Browser: Chrome
 - Version: 81.0.4044.113

**Additional context**
The reregistering problem will also occur if you focus the Controller in react dev tools. If you have multiple Controllers in the form with onFocus callbacks then they will all exhibit the same behaviour

**Comment by JeromeDeLeon** [comment]
The reason for this is because your forgot to memoize your function.

In [Line 107 of Controller](https://github.com/react-hook-form/react-hook-form/blob/bfecd5ba76e6f746fbd7d699240533e83ebae9f5/src/controller.tsx#L107), notice that the `onFocus` is part of `useCallback`'s dependencies of `registerField`.

**Comment by JeromeDeLeon** [comment]
@bluebill1049, should we handle it inside or let user defines it?

**Comment by bluebill1049** [comment]
wow, awesome find! @JeromeDeLeon it's awesome to see you are taking over the `Controller` component! I think we should memo in the lib.
