### ISSUE TITLE
Nested falsy defaultValues are undefined when using watch()

### ISSUE THREAD

**Issue by smably** [react-hook-form/react-hook-form#1526]
**Describe the bug**
Falsy values nested inside `defaultValues` are returned as `undefined` by `watch()` on the initial render.

**To Reproduce**
1. Pass a falsy nested value to `useForm` in `defaultValues`
2. Add a `watch()` on the path to the nested value
3. On initial render, watched value is `undefined` instead of the actual default value

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-bug-in-watch-with-nested-falsy-values-pgtvp

**Expected behavior**
The [docs](https://react-hook-form.com/api#watch) say:
> if `defaultValues` was initialised in `useForm` as argument, then the first render will return what's provided in `defaultValues`

This works as expected with top-level keys inside `defaultValues`, but nested values are broken as described above.

**Screenshots**
See CodeSandbox link. :)

**Desktop (please complete the following information):**
 - OS: Any OS :)
 - Browser: Any browser :)
 - Version: n/a

**Comment by smably** [comment]
Thank you so much for the quick fix. Fantastic library! ❤️

**Comment by bluebill1049** [comment]
thanks @smably i will release the patch over the weekend.
