### ISSUE TITLE
Is there any way to set defaultValue after useForm?

### ISSUE THREAD

**Issue by GapMAX** [react-hook-form/react-hook-form#1528]
I have to use setValue in controlled, but is fussy to set defaultValues in useForm in my customComponent, if there is a way to set default value like register({name : "field1", value : "test1"}) would be cool.

**Comment by bluebill1049** [comment]
```
useForm({
  defaultValues: {...}
})
```

**Comment by GapMAX** [comment]
> ```
> useForm({
>   defaultValues: {...}
> })
> ```
Is there any other way to set defaultValues ?

**Comment by bluebill1049** [comment]
<input defaultValue="test" />

**Comment by GapMAX** [comment]
> `<input defaultValue="test" />`

thanks for your reply, but i have to set default value for controlled component, and i have to use setValue in component, so defaultValue props and Controller doesn't suit my case. In a word, i want to set default value in filed level without using `<Controller/>` and `useForm({defaultValues : {}})`

**Comment by bluebill1049** [comment]
```
<input defaultValue="" name="test" ref={register} /> // don't attach onChagne

setVale('test', 'test')
```

**Comment by bluebill1049** [comment]
if above still doesn't make sense, create a simple CodeSandbox i can take a look.

**Comment by GapMAX** [comment]
https://codesandbox.io/s/material-demo-9m1uv?file=/demo.js

I want to set default value in demo.js while not in App.js

**Comment by bluebill1049** [comment]
do a `useEffect` after `register` and then `setValue`

**Comment by GapMAX** [comment]
> do a `useEffect` after `register` and then `setValue`. To be honest, you are doing the hard way with this lib. React Hook Form embrace uncontrolled input, but yes you can still build as controlled but it's not pretty.

I have already try setValue after register, it may cause error. Use React hook form in controlled is really not pretty, but sometimes I have to use controlled component to do something.

**Comment by bluebill1049** [comment]
That's true, and that's the reason why I made Controller, but then you don't want to use it.

**Comment by GapMAX** [comment]
I refactor my component use Controller, it works find, Thank you again. This lib is cool !!

**Comment by bluebill1049** [comment]
Awesome! @GapMAX great to hear that.
