### ISSUE TITLE
setValue on useFieldArray not updating whole object

### ISSUE THREAD

**Issue by themre** [react-hook-form/react-hook-form#1529]
Hi,
First I'm very grateful for such a wonderful library and how much effort you put in resolving all the issues! I tried to find a solution and not bother you but in the end I had to post an issue/question. 
I was working on this demo: https://codesandbox.io/s/react-hook-form-usefieldarray-n993y?file=/src/index.js

Here I used `clear` button to clear certain field in array. However I bumped into issues
First thing: If you click `clear` button it will clear input field. However if you click some other field, it will reset previously cleared input field. Do I need to watch all items and then used this to clear them?
Second: I have a large object which I want to set value. But I don't use all fields and thus they won't appear in my callback submit. How can I merge everything with my full object and always have updated object? I don't want to use some sort of merge util function from lodash or something else.

Thanks!

**Comment by bluebill1049** [comment]
I have only read half o the issue, man thanks for your understanding 🙏 i will read the rest of them after dinner. 👍

**Comment by themre** [comment]
Oh please, enjoy the dinner, I can't believe you reply so quickly! Really thanks for taking time!

**Comment by bluebill1049** [comment]
what about this? https://codesandbox.io/s/react-hook-form-usefieldarray-5d4g0

**Comment by themre** [comment]
Yes, this works perfectly. But how do I set whole object if I want to either start with new one (all empty values) or replace whole object with some starting values? Especially if it's a nested object.

**Comment by bluebill1049** [comment]
reset?

**Comment by themre** [comment]
Yes, reset works, but I need to always use `defaultValue` otherwise the input will be empty:
https://codesandbox.io/s/react-hook-form-usefieldarray-wxwf7?file=/src/index.js

I also added `additionalField` into nest subfield of the resetall button. When I submit, I don't have this field. Is there a way to have also untracked fields?

**Comment by bluebill1049** [comment]
you will need to use `defaultValue` for input for `useFieldArray`.

**Comment by bluebill1049** [comment]
> I also added additionalField into nest subfield of the resetall button. When I submit, I don't have this field. Is there a way to have also untracked fields

I need better context for above.

**Comment by themre** [comment]
for the nested example:
```
reset({
              test: [
                {
                  name: "reseted",
                  additionalField: "field1"
                }
              ]
            })
```
this `additionalField` if it's not tracked, it will get lots. So the only way is to merge each element with onSubmit, right?

**Comment by bluebill1049** [comment]
> for the nested example:
> 
> ```
> reset({
>               test: [
>                 {
>                   name: "reseted",
>                   additionalField: "field1"
>                 }
>               ]
>             })
> ```
> 
> this `additionalField` gets lost if it's not tracked. So the only way is to merge each element with onSubmit, right?

which `additionalField` will get lost if it's not tracked. `tracked` means `registered`?

**Comment by themre** [comment]
I mean I won't get it in the onSubmit. I will only get fields that are in the form. Maybe this is intended, but usually I put whole object into a form and update only some fields and have whole object updated throughout the form.

**Comment by bluebill1049** [comment]
> I will only get fields that are in the form.

Yes, basically input gets `registered`

**Comment by bluebill1049** [comment]
> I mean I won't get it in the onSubmit. I will only get fields that are in the form. Maybe this is intended, but usually I put whole object into a form and update only some fields and have whole object updated throughout the form.

yes, that's controlled form, where you have local `state` host the entire form. React Hook Form embrace how native form's behavior.

**Comment by themre** [comment]
Yes, makes sense. It's a mind shift from usualy React way :) Thanks for all the help, you sure made a lot of things more clear! I will close this since there are no bugs and just my misunderstanding.

**Comment by bluebill1049** [comment]
No worries @themre feel free to follow up with questions. You can send questions at Spectrum as well. 👍
