### ISSUE TITLE
Strange behavior when using `validationResolver` for array field

### ISSUE THREAD

**Issue by hendra-foo** [react-hook-form/react-hook-form#1530]
I'm running into some strange behavior in `errors` object when using `validationResolver`, sometimes it show `highlight: [Error]` sometimes `highlight[0]: Error` and sometimes both

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-get-started-8nvu9
2. Don't do any changes and directly click the submit btn. Open console and `errors` object will be like `highlight[0]: Error`
3. Now type anything in highlight textbox then remove all text in textbox. now `errors` object will have duplicate highlight error: `highlight[0]: Error` and `highlight: [Error]`

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-get-started-8nvu9

Is this a bug? or something wrong with my resolver code?
Sorry for bad english

**Comment by hendra-foo** [comment]
hi, sorry for bothering you, but i just solved this issue by modifying my resolver code to support array path such as `foo[x]` so there is no duplicate keys / strange behavior anymore.
but i think this behavior can occur again in object path such as `foo.x` and so i need to re-modify my resolver code again.

does by changing the resolver code is the best practices? or you can provide your solution to solve this issue?

here the sandbox link: https://codesandbox.io/s/react-hook-form-get-started-5ofjr

**Comment by bluebill1049** [comment]
hey @hendra-foo you want to take a look at this resolver?

https://github.com/react-hook-form/react-hook-form-resolvers

what we doing for v6.

**Comment by hendra-foo** [comment]
okay, i just installed the package, and there is only a file named package.json inside the package directory. looks like i'm gonna stick with my solution for now.

can't wait to look for the React hook form v6 updates :).

Thanks for the help. gonna close this issue
