### ISSUE TITLE
Separate field errors and form value types

### ISSUE THREAD

**Issue by jamil-alisgandarov** [react-hook-form/react-hook-form#1536]
1) Why errors can not be accessed by passing controller name?
2) Why type of `errors` is same as form values, where form values can be similar but have different type. As you can see from the example below, value of the `mcc` field is `IMCC`. But the field name is `mcc`. So if I want to access errors of `mcc` field, it will return an error just because `errors` and `formValues` are sharing same type passed from `useForm`.

````typescript
interface IMCC {
  code: string,
  value: string,
}

type FormData = {
  mcc: IMCC;
  input: string;
};
````

**Comment by kotarella1110** [comment]
@jamil-alisgandarov I created `NestedValue` in this PR (https://github.com/react-hook-form/react-hook-form/pull/1503) to solve this.
This PR has already been merged and will be released in v6.

```ts
interface IMCC {
  code: string,
  value: string,
}

type FormData = {
  mcc: NestedValue<IMCC>;
  input: string;
};

errors.mcc.message // no type error
```

**Comment by jamil-alisgandarov** [comment]
Thanks!!

**Comment by jamil-alisgandarov** [comment]
@kotarella1110 When are you planning to release?)

**Comment by kotarella1110** [comment]
@jamil-alisgandarov For now, the release date hasn't been set, but we can release v6 as early as next month.
We are working hard every day to release v6 🏃 
You can use [ErrorMessage component](https://react-hook-form.com/api#ErrorMessage) until v6 released.
