### ISSUE TITLE
Yup validation does not work when min, max props are added to input element 

### ISSUE THREAD

**Issue by dreamofi** [react-hook-form/react-hook-form#1539]
**Describe the bug**
When min, max props are added to an input element, Yup validation custom message is not showed, errors object is blank. Instead, an error message is showed in the form of a tooltip. It seems that native html5 validation is not overridden by Yup.

**To Reproduce**
1. Create Yup schema with custom validation message
2. Add min, max props to input element (type Number)
3. Type in a number larger than the set max value into the form
4. Click on submit
5. The div of Yup validation message does not appear, instead an error message is showed in the form of a tooltip when submit

**Codesandbox link:**
- [codesandbox](https://codesandbox.io/s/react-hook-form-validationschema-p6swe?file=/src/index.js)

**Expected behavior**
Yup validation message is showed

**Screenshots**
[screenshot](https://imgur.com/a/EsH7I7l)

**Desktop (please complete the following information):**
 - OS: Linux (Mx Linux 19.3 - Debian Buster)
 - Browser: Firefox 75, 76, Chromium 78

**Comment by bluebill1049** [comment]
That's native HTML behavior, place your validation inside your schema and display those error message.

**Comment by dreamofi** [comment]
@bluebill1049 : I did put the validation inside the schema. By adding min and max to input element, what I wanted to do was to limit the number range when an user click on the increase/decrease arrow. Without them, the value in the input form can be larger than the maximum value and smaller than the minimum value.
Is it possible to do that without adding the min/max props directly into input element? In addition, before switching to React-hook-form, I used Formik and it did take over the native html validation.

Currently it seems that sandboxes is down in my location, so here is the code for the example:

```
import React from "react";
import ReactDOM from "react-dom";
import { useForm } from "react-hook-form";
import * as yup from "yup";

import "./styles.css";

const SignupSchema = yup.object().shape({
  age: yup
    .number("Must be number")
    .required("Is required")
    .positive()
    .integer()
    .min(0, "Min is 0")
    .max(22, "max is 20")
});

function App() {
  const { register, handleSubmit, errors } = useForm({
    validationSchema: SignupSchema
  });
  const onSubmit = data => {
    alert(JSON.stringify(data));
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <div>
        <label>Age</label>
        <input type="number" min="0" max="20" name="age" ref={register} />
        {errors.age && <p>{errors.age.message}</p>}
      </div>
      <input type="submit" />
    </form>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by bluebill1049** [comment]
The above looks legit to me, it's better to leave the validation in the schema if you don't want the native input to pop up.

**Comment by dreamofi** [comment]
After reading this closed [issue](https://github.com/react-hook-form/react-hook-form/issues/354), I realized that adding noValidate attribute was what I need to do.
Thank you @bluebill1049 for your support!

**Comment by trancongdung12** [comment]
@dreamofi  thanks. It work good

**Comment by trancongdung12** [comment]
@dreamofi  thanks. It work good
