### ISSUE TITLE
defaultValues for radio inputs does not set formState.isValid

### ISSUE THREAD

**Issue by ErikAGriffin** [react-hook-form/react-hook-form#1540]
**Describe the bug**
When using the `defaultValues` param of the `useForm` function, one expects all fields passed a value to be filled in and for the form to be valid if all required fields are thus filled.

When using defaultValues with text inputs, this is the case: `formState.isValid` is true.  However when using the defaultValues of radio inputs:  formState.isValid returns false, even though a radio option is showing as selected.

**To Reproduce**
1. Visit [this sandbox](https://codesandbox.io/s/react-hook-radio-default-vales-vkqet?file=/src/App.js)
2. Reload the page
3. The `formState` is not valid, but defaultValues has selected a radio option in the only required field

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-radio-default-vales-vkqet?file=/src/App.js

**Expected behavior**
`defaultValues` causes `formState.isValid` to be true if all required fields have values.

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Chrome

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#formState

We have a proxy around fromState: :)

https://codesandbox.io/s/react-hook-radio-default-vales-w8wmv

**Comment by bluebill1049** [comment]
closing now :) feel free to follow up with questions.

**Comment by ErikAGriffin** [comment]
@bluebill1049 I'm confused, I see you invoked the proxy by using `const { isValid } = formState;`, however on page reload the form is still disabled in the modified sandbox you linked

**Comment by bluebill1049** [comment]
oops... I may have interacted with the form. It's a bug then...

**Comment by bluebill1049** [comment]
Will take a look at this issue soon.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-radio-default-vales-6e96v?file=/src/App.js

ok @ErikAGriffin for radio input you can only leave the validation to the last ratio input, otherwise react hook form will get confused with the validation since they all share the same name. I will include this on the website.

**Comment by ErikAGriffin** [comment]
I see, though I would consider this a workaround or a not ideal solution for long term maintenance.

Requiring the `{required: true}` register to _only_ be present on the last input make the use of `formState.isValid`+`defaultValues`+`radio inputs` very brittle.  A developer may come along and add a new radio input to the end with or without a `{required: true}` register, and it would cause the `defaultValues` setting `formState.isValid` correctly to break.

**Comment by bluebill1049** [comment]
Thanks @ErikAGriffin I couldn't agree more, it's a challenge for me at the moment because the same `name` attribute the share among inputs. This can be a workaround but would require quite a bit of extra code and increase the complexity of isValid check. Feel free to take a look at the register function and maybe you would have a smarter way of check valid, i will place this one in my backlog to take a look again.

**Comment by ErikAGriffin** [comment]
@bluebill1049 I'll have to to brush up on some Typescript as the syntax is new for me.  Is there any documentation / guidance on the codebase?  Not exactly sure where to begin poking around

**Comment by bluebill1049** [comment]
Thanks @ErikAGriffin 👍 

we don't have guidance on the codebase just yet, which I should do sometimes...

but if you have time you can take a look here:

Entry:
https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L833

Validation part:
https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L916
