### ISSUE TITLE
onSubmit removes my `id` (or other custom properties) from it's defaultValues

### ISSUE THREAD

**Issue by shiralizadeh** [react-hook-form/react-hook-form#1543]
I'm passing a series of values as my `defaultValues` to the `useForm({ defaultValues })`.

![image](https://user-images.githubusercontent.com/9346771/80712703-9d669880-8b07-11ea-81d8-34cd65f6d620.png)

After submitting my form, the result is my form values without `id` property.

![image](https://user-images.githubusercontent.com/9346771/80712813-bff8b180-8b07-11ea-912e-dfca033b43aa.png)

[CodeSandBox](https://codesandbox.io/s/react-hook-form-controller-0l267)

How can I prevent this from happening?

**Comment by bluebill1049** [comment]
store that id in a `<input type="hidden" />`

building forms with RHF is pretty close to native form, only inputs gets registered will be a part of the submitted data.
