### ISSUE TITLE
Cannot read property 'ref' of undefined in conditional controlled component

### ISSUE THREAD

**Issue by javialon26** [react-hook-form/react-hook-form#1551]
**Describe the bug**
I'm showing a set of inputs type radio conditionally and I get the "Cannot read property 'ref' of undefined" error.

**To Reproduce**
1. Select "Mrs" in title select, then select "Dr" and again "Mrs".

**Codesandbox link (Required)**
https://codesandbox.io/s/kind-hooks-m5pz7?file=/src/App.js

**Expected behavior**
Change the rendered content without an error.

**Desktop (please complete the following information):**
 - OS: macOs Catalina
 - Browser: Chrome
 - Version: Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by bluebill1049** [comment]
Have a read here: https://react-hook-form.com/faqs#Whyisdefaultvaluenotchangingcorrectlywithternaryoperator you can leverage react `key` attribute.

**Comment by javialon26** [comment]
Hi @bluebill1049, thank you for your response. After reading the article I did some tests and the error persists.

The example in the FAQS is using input type text, the same example with type radio fails, I'm using uniques refs but the same error happens, maybe it is an issue with radios.

I updated the example here:
https://codesandbox.io/s/green-sun-vei8w?file=/src/App.js

Thank you

**Comment by bluebill1049** [comment]
Thanks @javialon26 i am patching this bug. thanks for reporting: https://codesandbox.io/s/polished-architecture-dt2ir?file=/src/App.js
