### ISSUE TITLE
Validation not registering all of a sudden version 4.10.1 to 5.6.1

### ISSUE THREAD

**Issue by danmight** [react-hook-form/react-hook-form#1554]
**Describe the bug**
I upgraded from 4.10.1 to 5.6.1 and my validation requirements in "register" don't work. The form submits even though certain fields are marked as required or needing a regular expression.

An example of a field I have is below. I'm using material UI. If I try to submit this form on version 4.10.1 with a blank field I get the expected error that stops the submission and tells me the field is required. If I upgrade to 5.6.1 the form submits without error when I leave this field blank.

If I downgrade it works fine again, so there appears to be something between the versions.

```
<Controller 
                label="Client First Name"
                name='clientFirstName'
                id='clientFirstName' 
                defaultValue={client.clientFirstName === undefined ? '' : client.clientFirstName}
                variant='outlined'
                margin='dense'
                fullWidth
                error={errors.clientFirstName !== undefined}
                control={control}
                as={<TextField inputRef={register({ required: true})}/>} 
              />
              {errors.clientFirstName && <Typography variant='caption' color='error'>Client first name is required.</Typography>}
```
I did some further troubleshooting and if I add this useEffect hook, I can get 5.6.1 to work. All set loading does is a a <LinearProgress/> to the top of the form. It seems like something needs to trigger a re-render of the form to get the validation requirements to get set.

```
useEffect(() => {
  setLoading(true)
  setTimeout(function(){setLoading(false) }, 1000);
}, [])
```

**Expected behavior**
If I try to submit a form with "required: true" I should be stopped.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser chrome
 - Version Version 81.0.4044.129

**Comment by bluebill1049** [comment]
Hi @DanielPopOut i don't think you are having the correct usage:

```diff
-<Controller 
-  error={errors.clientFirstName !== undefined}
-  control={control}
-  as={<TextField inputRef={register({ required: true})}/>} 
-/>
+<Controller 
+  error={errors.clientFirstName !== undefined}
+  control={control}
+  as={TextField} 
+  rules={{ required: true}}
/>
```

controller should take care the registration and validation should be using the `rules` props.

**Comment by DanielPopOut** [comment]
@bluebill1049  You pingged the wrong person in last message.
It's for you @danmight ;-)

**Comment by bluebill1049** [comment]
oh crap... sorry...
