### ISSUE TITLE
Cannot get correct value of radio input on handleSubmit

### ISSUE THREAD

**Issue by hmtri1011** [react-hook-form/react-hook-form#1557]
**Describe the bug**
input element that wrapped in Controller cannot get correct value, it is always empty.

**To Reproduce**
1. Go to sandbox link
2. Check on 2 radio inputs and click submit
3. See data on the console

**Codesandbox link (Required)**
https://codesandbox.io/s/dreamy-lovelace-vyzei?file=/src/App.js:0-562

**Comment by devrnt** [comment]
In this use case should not use `Controller`. Just use `register` on the `<input type="radio" />` field.
https://codesandbox.io/s/eloquent-cache-6m59s

**Comment by bluebill1049** [comment]
Thanks @devrnt you are right. if you are want to use Controller, then you should build a wrapper to host all your radio inputs inside and let the controller collect the values.

**Comment by hmtri1011** [comment]
Hi, in my case I use Controller because I have a custom input and I don't want to forwardRef so I dont use register.

Back to my example, you guys can see, the problem is when we use Controller and wrap an input radio element (Custom or original HTLM5 input), the value is always missing, you guys can check in the elements tab on devtools as well.

I'm not sure if we miss something or this is correct behaviour. Thank agains!

**Comment by bluebill1049** [comment]
<img width="921" alt="Screen Shot 2020-05-04 at 10 41 54 am" src="https://user-images.githubusercontent.com/10513364/80930037-e2cee280-8df3-11ea-8e85-10f6e8c578c0.png">

Like I mentioned above if you have multiple inputs as radio have the same name, then it wouldn't work with a controller, unless you build a wrapper for your radio inputs. However, register works with native input, but that's not an option for you, so i will recommend building a wrapper for your input radio as group. Take a look this example for MUI: https://codesandbox.io/s/react-hook-form-controller-079xx
