### ISSUE TITLE
[ts] FormContext - types of property 'setError' are incompatible.

### ISSUE THREAD

**Issue by kyle-mccarthy** [react-hook-form/react-hook-form#1559]
**Describe the bug**

Types of property setError are incompatible for array values. I thought that #1509 fixed this, so it is probably regression.

**To Reproduce**
1. Create a form where one of the default values is an array.
2. Pass the form to FormContext
3. TS error

**Codesandbox link (Required)**
https://codesandbox.io/s/immutable-shape-x34v9?file=/src/App.tsx

**Expected behavior**
FormContext should accept property with array values

**Comment by kotarella1110** [comment]
oh… sorry.
I will look into tonight.

**Comment by bluebill1049** [comment]
Thanks a lot @kotarella1110 🙏
