### ISSUE TITLE
getPath(...).flat is not a function

### ISSUE THREAD

**Issue by kiansenggoh** [react-hook-form/react-hook-form#1560]
**Describe the bug**
getPath(...).flat is not a function

only get this error when running Jest unit testing for fieldArray.
trying to migrate from 5.2.0 to 5.3.0

see below screenshot.

![image](https://user-images.githubusercontent.com/56799988/80937445-c6d53c00-8e07-11ea-9558-d27687ec656d.png)

**Comment by bluebill1049** [comment]
please upgrade your Jest to latest, old jest didn't support `Array.flat`.

**Comment by kiansenggoh** [comment]
thank u so much. :)
update the jest library and include core-js:3.6.5
