### ISSUE TITLE
getting child useFieldArray to render when using append on parent useFiledArray

### ISSUE THREAD

**Issue by Amtron** [react-hook-form/react-hook-form#1561]
I have a group of fields (parent group) which contain another group of fields (child group); the user is able to append and remove fields from each group (the parent group and the child group). I'm having difficulties getting the child filed to render when using append on the parent group. 

I'm able to use remove of the parent group without any problems but when it comes to append the children of the parent do not render. I've checked the parent fields and the data is correct.

Is there a way to get the children to render after I append from the parent?

**Comment by bluebill1049** [comment]
Can u provide a simple codesandbox to produce this problem?

**Comment by Amtron** [comment]
Before append:

![Screen Shot 2020-05-04 at 5 31 00 pm](https://user-images.githubusercontent.com/5695805/80944597-488b9080-8e2d-11ea-9ae9-7135c8079ffe.png)

See how the first group has "Colour" and "Image Select"

After append:

![Screen Shot 2020-05-04 at 5 36 14 pm](https://user-images.githubusercontent.com/5695805/80944841-c94a8c80-8e2d-11ea-8f84-f643d881c6d5.png)

After append the second group does not contain an children from the child useFieldArray. I've checked the parent group files and the children appear in the data.

**Comment by bluebill1049** [comment]
This doesn’t help me to investigate into the problem.

**Comment by bluebill1049** [comment]
Please follow our issue template by provide a codesandbox to reproduce the issue or question.

**Comment by Amtron** [comment]
Please see code example:

https://codesandbox.io/s/react-hook-form-nested-fields-lgy5j?file=/src/index.js

Click add group; you should see that the "friends" do not get rendered.

**Comment by bluebill1049** [comment]
oh, I see your problem now. Let me explain, each `useFieldArray` is actually having its own scope and own field array when you append parent `useFieldArray`, your child `useFieldArray` is not aware of that, for child `useFieldArray` to append, you will have to invoke the child `useFieldArray`'s append method.  There are a few ways to resolve this:

1. use Context so you can invoke child useFieldArray's append method
2. pass child `prop` to parent: https://stackoverflow.com/questions/22639534/pass-props-to-parent-component-in-react-js
3. use `useEffect` to trigger `append` at `child` useFieldArray

**Comment by s3341458** [comment]
sorry @bluebill1049 when you say "Context", did you refers to "FormContext" or "React Context API"

**Comment by bluebill1049** [comment]
React Context API @s3341458

**Comment by bluebill1049** [comment]
option 4:

invoke two `useFieldArray` in the same component, for child component pass methods down as props.

```
const parent = useFieldArray();
const child = useFieldArray();
```

**Comment by Amtron** [comment]
@bluebill1049 thanks for the help 👍

**Comment by bluebill1049** [comment]
welcome as usual @Amtron :)

**Comment by aloneszjl** [comment]
I also encountered this problem. My form is render by jsonschema.
And I'm not sure what fields are in the nested array
Is there a good solution?
@bluebill1049

**Comment by mjcarnaje** [comment]
> oh, I see your problem now. Let me explain, each `useFieldArray` is actually having its own scope and own field array when you append parent `useFieldArray`, your child `useFieldArray` is not aware of that, for child `useFieldArray` to append, you will have to invoke the child `useFieldArray`'s append method. There are a few ways to resolve this:
> 
> 1. use Context so you can invoke child useFieldArray's append method
> 2. pass child `prop` to parent: https://stackoverflow.com/questions/22639534/pass-props-to-parent-component-in-react-js
> 3. use `useEffect` to trigger `append` at `child` useFieldArray

when I use useEffect, it automatically focus to the child's input, What is the better approach to avoid this sir?

**Comment by bluebill1049** [comment]
> > oh, I see your problem now. Let me explain, each `useFieldArray` is actually having its own scope and own field array when you append parent `useFieldArray`, your child `useFieldArray` is not aware of that, for child `useFieldArray` to append, you will have to invoke the child `useFieldArray`'s append method. There are a few ways to resolve this:
> > 
> > 1. use Context so you can invoke child useFieldArray's append method
> > 2. pass child `prop` to parent: https://stackoverflow.com/questions/22639534/pass-props-to-parent-component-in-react-js
> > 3. use `useEffect` to trigger `append` at `child` useFieldArray
> 
> when I use useEffect, it automatically focus to the child's input, What is the better approach to avoid this sir?

`shouldFocus: boolean = true`

<img width="401" alt="Screen Shot 2020-11-25 at 4 47 56 pm" src="https://user-images.githubusercontent.com/10513364/100188264-fa132000-2f3d-11eb-8857-56b509f50ba0.png">

`append({} , false)`

**Comment by mjcarnaje** [comment]
> > > oh, I see your problem now. Let me explain, each `useFieldArray` is actually having its own scope and own field array when you append parent `useFieldArray`, your child `useFieldArray` is not aware of that, for child `useFieldArray` to append, you will have to invoke the child `useFieldArray`'s append method. There are a few ways to resolve this:
> > > 
> > > 1. use Context so you can invoke child useFieldArray's append method
> > > 2. pass child `prop` to parent: https://stackoverflow.com/questions/22639534/pass-props-to-parent-component-in-react-js
> > > 3. use `useEffect` to trigger `append` at `child` useFieldArray
> > 
> > 
> > when I use useEffect, it automatically focus to the child's input, What is the better approach to avoid this sir?
> 
> `shouldFocus: boolean = true`
> 
> <img alt="Screen Shot 2020-11-25 at 4 47 56 pm" width="401" src="https://user-images.githubusercontent.com/10513364/100188264-fa132000-2f3d-11eb-8857-56b509f50ba0.png">
> 
> `append({} , false)`

Thank you so much sir, btw good work!!

**Comment by bluebill1049** [comment]
> > > > oh, I see your problem now. Let me explain, each `useFieldArray` is actually having its own scope and own field array when you append parent `useFieldArray`, your child `useFieldArray` is not aware of that, for child `useFieldArray` to append, you will have to invoke the child `useFieldArray`'s append method. There are a few ways to resolve this:
> > > > 
> > > > 1. use Context so you can invoke child useFieldArray's append method
> > > > 2. pass child `prop` to parent: https://stackoverflow.com/questions/22639534/pass-props-to-parent-component-in-react-js
> > > > 3. use `useEffect` to trigger `append` at `child` useFieldArray
> > > 
> > > 
> > > when I use useEffect, it automatically focus to the child's input, What is the better approach to avoid this sir?
> > 
> > 
> > `shouldFocus: boolean = true`
> > <img alt="Screen Shot 2020-11-25 at 4 47 56 pm" width="401" src="https://user-images.githubusercontent.com/10513364/100188264-fa132000-2f3d-11eb-8857-56b509f50ba0.png">
> > `append({} , false)`
> 
> Thank you so much sir, btw good work!!

No worries 👍 glad its working out for you.
