### ISSUE TITLE
setValue does not work

### ISSUE THREAD

**Issue by flaff** [react-hook-form/react-hook-form#1566]
**Describe the bug**
It seems that `setValue` does nothing. From both context and `useForm` itself

**To Reproduce**
1. Use `setValue` in a change handler of an input (or probably anywhere)
2. `setValue` does not set the value when called

**Codesandbox link (Required)**
- [useForm/useFormContext](https://codesandbox.io/s/react-hook-form-useform-template-rgmyp) sandbox

**Expected behavior**
`setValue` should set a value

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.4
 - Browser Chrome
 - Version 84

**Additional context:**
- It seemed to be working fine before 5.6.0
- removing `useCallback` makes no difference
- using it directly from `useForm` makes no difference

**Comment by bluebill1049** [comment]
please read the doc on setValue: https://react-hook-form.com/api#setValue and `register`.

https://react-hook-form.com/get-started

**Comment by bluebill1049** [comment]
closing, for now, feel free to ask more questions.
