### ISSUE TITLE
Watch() on an array not updating when calling setValue

### ISSUE THREAD

**Issue by raulfelix** [react-hook-form/react-hook-form#1568]
**Describe the question?**
Not sure if this is a bug.

Custom input registered and the value is being watched.
When calling `setValue()` with an array of objects the watched value is not updated.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-useform-template-5lynl?file=/src/custom-field.js
2. Try the form out by entering a value and pressing the button
3. This will push an item onto an array and call `setValue`
4. Expecting the watched value to update and re-render the component

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-5lynl?file=/src/custom-field.js

**Comment by bluebill1049** [comment]
hey @raulfelix i think your CSB is not completed.

**Comment by raulfelix** [comment]
🤦🏽‍♂️I will get back to you. I recreated the CSB and now the issue is not happening

**Comment by bluebill1049** [comment]
no worries mate :) have a good night.

**Comment by raulfelix** [comment]
Lets close this one @bluebill1049 I cannot repeat my issue

**Comment by bluebill1049** [comment]
no worries 👍 feel free to re-open if you find the way to reproduce.
