### ISSUE TITLE
remove from useFieldArray doesn't work correctly

### ISSUE THREAD

**Issue by dorsharon** [react-hook-form/react-hook-form#1571]
Please consider asking the question at our spectrum channel.

https://spectrum.chat/react-hook-form

**Describe the question?**

**To Reproduce**
1. use `useFieldArray`
2. Append new members
3. `remove`ing doesn't work as expected, deletes other members than the one needed

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-zs0lp

**Additional context**
I couldn't replicate my issue as I experienced it, but I also had an issue where `remove`ing a member would completely wipe my array

**Comment by jaminhaber** [comment]
I was actually about to post this same issue.

```
export const FieldArray = ({ name }: MultiProps) => {
  const { getValues } = useFormContext();
  const { fields, append, remove } = useFieldArray({ name });

  const curriedRemove = (index: number) => () => {
    console.log(getValues());
    console.log("REMOVING")
    remove(index);
    console.log(getValues());
  };

  return (
    <View>
      {/* gets props from context */}
      {fields.map((item, index) => (
        <Input />
      ))}
    </View>
  );
};
```
Result
<img width="584" alt="Screen Shot 2020-05-05 at 11 15 12 AM" src="https://user-images.githubusercontent.com/2616400/81082782-bd100f00-8ec1-11ea-8be4-258841fdcfc2.png">

**Comment by jaminhaber** [comment]
CSB: https://codesandbox.io/s/react-hook-form-usefieldarray-fqgxd?fontsize=14&hidenavigation=1&theme=dark

**Comment by bluebill1049** [comment]
thanks @dorsharon where is the defaultValue? and why comment it out in the codesandbox?

**Comment by dorsharon** [comment]
Sorry, I pasted the wrong sandbox link, I'll update a new one shortly

**Comment by dorsharon** [comment]
Please look at this CSB:
https://codesandbox.io/s/react-hook-form-usefieldarray-glhss?file=/src/index.js

I've used `defaultValue` in all inputs, but remove simply seems to clear all array entirely or something

**Comment by bluebill1049** [comment]
it's the same codesandbox.

**Comment by bluebill1049** [comment]
<img width="563" alt="Screen Shot 2020-05-06 at 5 09 23 pm" src="https://user-images.githubusercontent.com/10513364/81146805-5885aa80-8fbc-11ea-8208-5b5a66c3e47b.png">

**Comment by dorsharon** [comment]
try now
https://codesandbox.io/s/react-hook-form-usefieldarray-glhss?file=/src/index.js

**Comment by bluebill1049** [comment]
please at least use a proper version: https://codesandbox.io/s/react-hook-form-usefieldarray-ycych?file=/src/index.js

**Comment by dorsharon** [comment]
Sorry, I'm not the greatest with codesandbox, did you change anything other than getting the lib dependency?
I'm using 5.6.1 and still getting a behavior like the last CSB I posted

**Comment by bluebill1049** [comment]
the example you provided wasn't even using a proper version, it was just loading from an src folder. did you take a look the example which i had above? is it working for you, i tested and it's working fo me.

if it's not working, then list the steps the reproduce the problem.

**Comment by dorsharon** [comment]
For some reason, changing the dep like u did fixes the CSB, but my own code still fails, and I can't seem to put my finger on a difference.

@jaminhaber, could you perhaps post your codesandbox?

**Comment by bluebill1049** [comment]
@dorsharon can you take a screenshot of your usage? see if can help there.

**Comment by dorsharon** [comment]
Thank you for being so responsive!

I have a form for creating an array of floors like so:
![image](https://user-images.githubusercontent.com/23096334/81172574-2b7acd00-8fa7-11ea-9cfe-cc3ae1744d72.png)

With each floor having fields like so:
![image](https://user-images.githubusercontent.com/23096334/81172619-3fbeca00-8fa7-11ea-8128-6677d20a595a.png)

Once I try to remove one of the floors I've added, I get my whole array wiped like so:
before:
![image](https://user-images.githubusercontent.com/23096334/81172701-65e46a00-8fa7-11ea-98c8-6d268dd1219b.png)

after:
![image](https://user-images.githubusercontent.com/23096334/81172718-6ed53b80-8fa7-11ea-8bc9-6b450573ae89.png)

**Comment by bluebill1049** [comment]
can you take a screenshot of your code around the `map`? and your delete.

**Comment by bluebill1049** [comment]
also can you copy parts of my code and test in your environment as well.

**Comment by atinder** [comment]
I am facing the same issue with nesred form.
When I add defaultValue to all the elements, it works fine.
Otherwise removing and index creates wrong data.

**Comment by bluebill1049** [comment]
@atinder provide a codesandbox plz keep it simple and focus

**Comment by atinder** [comment]
sure, l'll try to replicate in CSB. Give me some time

**Comment by atinder** [comment]
https://codesandbox.io/s/react-hook-form-usefieldarray-y3srp?file=/src/index.js

@bluebill1049

**Comment by bluebill1049** [comment]
can you double-check your input name?
```
<Controller
                name={`fields[${index}].name`}
                defaultValue={item.name}
                control={control}
                as={"input"}
              />
              <button
                onClick={() => {
                  remove(index);
                }}
              >
                REMOVE
              </button>
              <li>
                <NestedField
                  control={control}
                  register={register}
                  namePrefix={`experiment.fields[${index}].list`}
                />
              </li>
              ))}
```

Take a look at this example: https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-x7btr

**Comment by atinder** [comment]
Thanks for quick revert. the field array name was a typo.
Somehow it works in CDB but not local. I follow your example more closely and get back if I still face issues.

**Comment by bluebill1049** [comment]
> Thanks for quick revert. the field array name was a typo.
> Somehow it works in CDB but not local. I follow your example more closely and get back if I still face issues.
> Do you think `name: "experiment.fields"` may be the cause of issue? The object has more depth in my case.

maybe try to follow the CSB example, see if you can achieve similarly?

**Comment by changyeamoon** [comment]
@bluebill1049 whats up~ I think I love your library? Haven't fully decided yet, but its def fun. 

I'm having the same issue. heres a CSB - https://codesandbox.io/s/react-hook-form-field-array-append-remove-df816?file=/src/index.js

append some fields and assign different values and see the remove removing random ones.  Any ideas?

**Comment by bluebill1049** [comment]
> @bluebill1049 whats up~ I think I love your library? Haven't fully decided yet, but its def fun.
> 
> v. 6.8.0
> 
> I'm having the same issue. heres a CSB - https://codesandbox.io/s/react-hook-form-field-array-append-remove-df816?file=/src/index.js
> 
> append some fields and assign different values and see the remove, removing random ones. Any ideas?

<img width="974" alt="Screen Shot 2020-09-11 at 3 25 28 pm" src="https://user-images.githubusercontent.com/10513364/92866573-07dafe00-f443-11ea-89c9-f46b4e498aca.png">

make sure you go through the doc with the important note, i think you are missing the `id`

**Comment by changyeamoon** [comment]
@bluebill1049 wow, that was it. Thanks for the thorough documentation. mustve missed it.
