### ISSUE TITLE
Callback when form is invalid

### ISSUE THREAD

**Issue by feclist** [react-hook-form/react-hook-form#1574]
**Is your feature request related to a problem? Please describe.**
We are running into this problem where we need to have some side effect triggered when a form is invalidated. Now we've tried getting to that point by two methods:
1. Writing a useEffect that listens for the `errors` object to change. This doesn't consistently work as only the first invalidation triggers this effect not any subsequent validations where the errors don't change.
2. using setError on the custom `validate` function in register. It seems that once all these functions have run (and some/all of them return false) all the errors set in validation are overridden by the internal error type of `validation`
EDIT: 3. I got it to work using the following hook below. By listening to the `errors` and `formState.submitCount` I know when a new submit happened. 
```tsx
const { register, handleSubmit, errors, setValue, formState } = useForm()

useEffect(() => {
  // Trigger callback when there's errors
  if (Object.keys(errors).length !== 0) {
    onInvalid()
  }
}, [JSON.stringify(errors), formState.submitCount])
```

**Describe the solution you'd like**
It would be great to have `handleSubmit` to take two functions one callback for a successful submit and a second argument for a validation error callback. Something that looks like: `handleSubmit(successCallback: function, invalidCallback: function)`. This would give more flexibility to the user when the user wants to rely on the internal validation, but does need to have a side effect triggered once validation fails. 

**Describe alternatives you've considered**
The three alternatives listed above is what we've come up with. The third one did get me the desired result, but even though this works it would still be better to have a direct callback instead of an inferred one.

**Additional context**
If anything remains unclear I can elaborate :)

**Comment by bluebill1049** [comment]
Thanks a lot for you suggestion :) I will leave for my backlog and attach waiting up vote tag.

**Comment by zelucena** [comment]
This should be very useful. I use a state to temporarily disable my submit buttons so the user can't trigger more than one request at a time. 
I got the function `useYupValidationResolver` from the docs at V5 but I also manually added the following to the catch segment:
`
if (typeof handleErrors === 'function') {
    handleErrors(errors);
}
`

**Comment by bluebill1049** [comment]
@zelucena this is already shipped.

**Comment by Asrover** [comment]
```
useEffect(() => {
     if (formState.isSubmitted && !formState.isValid) {
         // Error callback
     }
 }, [formState.submitCount])
```
