### ISSUE TITLE
Yup schema re-validation does not remove error on dependent select fields

### ISSUE THREAD

**Issue by nfabredev** [react-hook-form/react-hook-form#1575]
Hi everyone, decided to open an issue as i thought you might not get notification from the [closed issue where i commented](https://github.com/react-hook-form/react-hook-form/issues/440#issuecomment-624067523)

### Describe the bug
When using .when() or a test which checks the parent value with yup, and reValidateMode is "onChange" ( by default ), only the select that is changed has its error removed, even if changing its selected option affects the validity of other fields. This is related to #440 which has been fixed [here](https://github.com/MikeAmelung/react-hook-form/commit/e72e3edc6625a15a9032d5cea5202d24e1e0928c) but in my use case with html select elements this doesn't work.

**Describe the bug**
Using `when` OR `test` with `this.parent` to have a 'either field' type of validation, it is not possible to clear errors on field A when changing the value of field B in such a way that both fields are valid.

**To Reproduce**
1. Go to any of the two Codesandbox
2. Click on 'Submit', both validation errors will appear ( you can check the console too )
3. Change one of the select, only one validation error will disappear, **the form is still invalid**
Click submit, this somehow trigger a revalidation and successfully submits the form. The form is valid and the remaining error is cleared.

**Codesandbox link (Required)**
- [with when](https://codesandbox.io/s/react-hook-form-select-validation-onchange-with-when-vrty2?file=/src/index.js)
- [with test](https://codesandbox.io/s/react-hook-form-validation-onchange-with-test-mbt7i)

**Expected behavior**
Both errors should be cleared when changing a field both validations depends on.

**Desktop (please complete the following information):**
 - OS: macOs 10.15.4
 - Browser Chrome 81.0.4044.129 (Official Build) (64-bit)

**Comment by bluebill1049** [comment]
I think i understand the problem. I will take a look at the examples tonight.
react hook form only focus a single input at a time, for depend input, you will have to use `triggerValidation`. This is done by design to a limited amount of re-render which will trigger by the lib.

**Comment by nfabredev** [comment]
Thanks for very quick response. My personal use case has been solved by triggering the validation as you proposed, so as far as i'm concerned this issue can be considered solved 👍

However I'm not sure why you would need to do that with `<select>` tags and not with inputs as [shown here](https://codesandbox.io/s/react-hook-form-validation-onchange-70qtf).

**Comment by bluebill1049** [comment]
hey @nfabredev no worries.

> However I'm not sure why you would need to do that with <select> tags and not with inputs as shown here.

can you provide some more context and steps to reproduce for this one?

i don't see a select tag in your example.

**Comment by nfabredev** [comment]
Both the sandbox i linked to use select tags with options, and need to use `triggerValidation ` to work unlike this other example that use [text input](https://codesandbox.io/s/react-hook-form-validation-onchange-70qtf)

**Comment by pnicholspf** [comment]
I'm facing the same issue as the OP (even with text fields).

I also noticed this [codesandbox](https://codesandbox.io/s/react-hook-form-validation-onchange-70qtf) is working as expected, but it's using a much older RHF version: `3.26.5` whereas your 2 examples are using `5.6.1`.

`3.28.9` seems to be the version where this stopped working:
https://github.com/react-hook-form/react-hook-form/releases/tag/v3.28.9

**Comment by bluebill1049** [comment]
@pnicholspf any change to upgrade?

**Comment by pnicholspf** [comment]
@bluebill1049 Sorry, what I meant is that when we upgrade to a more recent version, then it stops working as expected (validation does not remove error on dependant fields).  I've created 4 codesandbox with different versions:

 - [3.28.8](https://codesandbox.io/s/react-hook-form-validation-onchange-3288-84iuj) works as expected 
 - [3.28.9](https://codesandbox.io/s/react-hook-form-validation-onchange-3289-qez61) doesn't work anymore 
 - [5.6.1](https://codesandbox.io/s/react-hook-form-validation-onchange-561-pk0dh) doesn't work - same version as in @nfabredev example
 - [6.0.5](https://codesandbox.io/s/react-hook-form-validation-onchange-605-mqcnc) doesn't work - latest version using resolver

So it appears that between `3.28.8` and `3.28.9` and for all versions since, something as changed in the way validation works for dependant fields.

**Comment by bluebill1049** [comment]
> @bluebill1049 Sorry, what I meant is that when we upgrade to a more recent version, then it stops working as expected (validation does not remove error on dependant fields). I've created 4 codesandbox with different versions:
> 
> * [3.28.8](https://codesandbox.io/s/react-hook-form-validation-onchange-3288-84iuj) works as expected
> * [3.28.9](https://codesandbox.io/s/react-hook-form-validation-onchange-3289-qez61) doesn't work anymore
> * [5.6.1](https://codesandbox.io/s/react-hook-form-validation-onchange-561-pk0dh) doesn't work - same version as in @nfabredev example
> * [6.0.5](https://codesandbox.io/s/react-hook-form-validation-onchange-605-mqcnc) doesn't work - latest version using resolver
> 
> So it appears that between `3.28.8` and `3.28.9` and for all versions since, something as changed in the way validation works for dependant fields.

hey @Photonios thanks for the detailed report and codesandbox, for dependant fields you will need to use `trigger` now, we only focus one field at a time to improve perf, so we can when to trigger a re-render or not.
