### ISSUE TITLE
Document Array Validation

### ISSUE THREAD

**Issue by kyeotic** [react-hook-form/react-hook-form#1579]
The documentations for [validation-resolver](https://react-hook-form.com/api#validationResolver) says it works with external libraries, but provides no examples of how to return an `errors` object without those libraries. I am especially interested in what the `errors` object needs to look like for errors on array fields.

**Describe the solution you'd like**
Examples that do not depend on external Libraries like Joi

**Comment by bluebill1049** [comment]
V6 will have support with Joi

https://github.com/react-hook-form/react-hook-form-resolvers

you can have a read the source code as well :) feel free to ask questions.

**Comment by kyeotic** [comment]
So joi is a requirement? I figured there would be a way to do validation without another library.

**Comment by bluebill1049** [comment]
No, it's not requirement.  sorry, I have confused you. you can build your own custom schema.

**Comment by bluebill1049** [comment]
as long as you return { values, errors } from the resolvers, i guess your question is around the type of Errors.

```
export type FieldError = {
  type: string;
  types?: MultipleFieldErrors;
  message?: Message;
};
```
