### ISSUE TITLE
How to store form values on unmount of a component?

### ISSUE THREAD

**Issue by FatehAK** [react-hook-form/react-hook-form#1581]
**Describe the question?**
Hey Bill, so I am trying to store form values to redux on unmount of a component (i.e As the component unmounts I call the getValues() method and then I dispatch a redux action with the values) but the problem here is getValues() always seems to return the defaults. Any way to go about this? How do you get all form values on unmount?

**Comment by bluebill1049** [comment]
please provide a codesandbox.

**Comment by bdmason** [comment]
You probably need a cleanup method inside useEffect: https://reactjs.org/docs/hooks-effect.html#effects-with-cleanup

**Comment by FatehAK** [comment]
It's exactly this issue https://github.com/react-hook-form/react-hook-form/issues/494. The solution given here works. But @bluebill1049 is there a better solution? If not please close this issue. Thanks

**Comment by bluebill1049** [comment]
i will go with useEffect :)
