### ISSUE TITLE
Data structure not consistent from watch() to handleSubmit() - intentional?

### ISSUE THREAD

**Issue by colemars** [react-hook-form/react-hook-form#1582]
When you have some field with a nested structure(array or object), the obj structure returned from `watch()` is different than the final `data` object structure passed from `handleSubmit`. 

Specifically, the `watch()` obj structure is flat..
```
`obj[nested][here]`: value,
`obj[nested[there]`: value
```
or
```
'arr[0]': val,
'arr[1]' val
```
 whereas `data` is nested.

```
obj: {nested: {here: val, there: val}};
arr: [val, val];
```

Is this intentional/inevitable? Haven't run into issues bc of it, and it kind of makes sense - but seems like a potential inconsistency and bother having to write some sort of recursion if you want to consistently consume the data prior to submit.

**Comment by bluebill1049** [comment]
`watch({nest: true})`

V6 will be nest by default :)

**Comment by colemars** [comment]
ty!

**Comment by bluebill1049** [comment]
all good, we are fixing this on the next major version, so you won't have to worry about that.
