### ISSUE TITLE
Watch is not getting values property on Edge (Component is not rendered again)

### ISSUE THREAD

**Issue by chepitoco** [react-hook-form/react-hook-form#1583]
**Describe the bug**
I'm trying to figure out why **watch** is not getting the select value when it's changed by the user, re-render is updated only after OnBlur event happens,  that behavior is just happening on Edge Browser. (For Chrome, FF, Safari it is working as I expected).  When I change the select value this dispatch a new render of the component in almost all browser except EDGE :( 

**To Reproduce**

1. Create a form with a Select (it is a select component created with React.forwardRef), 
2. Use watch to observe if the value change (Just EDGE) and the component is re-rendered

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-watch-not-working-edge-jhu1k

**Expected behavior**
The component should be re-rendered just with the onChange event.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: EDGE
 - Version 42.17134.1.0

**Comment by bluebill1049** [comment]
CSB doesn't even load at my PC's EDGE...

**Comment by bluebill1049** [comment]
damn IE/Edge doesn't support input event...
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event#Browser_compatibility

**Comment by bluebill1049** [comment]
can you please test this on your EDGE?

https://codesandbox.io/s/react-hook-form-watch-not-working-edge-9ufs6?file=/src/App.js

**Comment by chepitoco** [comment]
@bluebill1049  I wasn't able to see https://codesandbox.io/s/react-hook-form-watch-not-working-edge-9ufs6?file=/src/App.js working on my Edge, here the error in my edge console

![edge-not-loading-sandbox](https://user-images.githubusercontent.com/15802694/81309024-1ace6380-9048-11ea-927f-5319f3c8a5c6.png)

However I download the zip from your codesandbox url and I ran the project locally and the select is having the same strange behavior with onchange event, the watch is not detecting the onchage event and of course the component is not re-rendered.
Here my test on chrome and Edge 

**Debug on Chrome:**
![Debug-local-chrome](https://user-images.githubusercontent.com/15802694/81310286-85cc6a00-9049-11ea-8f06-0ef86d193010.gif)

**Debug on Edge:**
![Debug-local-edge](https://user-images.githubusercontent.com/15802694/81310365-9b419400-9049-11ea-8f29-e7a862a31d07.gif)

**Comment by chepitoco** [comment]
@bluebill1049 I've tested your code locally and I found the reason why your last fix doesn't work yet, It is regarding the element.type values, Here my comments abut your validation https://github.com/react-hook-form/react-hook-form/commit/8218583c74ceac31e8874e60a69dfc819502a2df

Your are very close to solve it. :)

**Comment by bluebill1049** [comment]
> @bluebill1049 I've tested your code locally and I found the reason why your last fix doesn't work yet, It is regarding the element.type values, Here my comments about your validation [8218583](https://github.com/react-hook-form/react-hook-form/commit/8218583c74ceac31e8874e60a69dfc819502a2df)
> 
> Your are very close to solve it. :)

oh lord, where is the web standard...

**Comment by bluebill1049** [comment]
updated: https://codesandbox.io/s/react-hook-form-watch-not-working-edge-9ufs6?file=/src/App.js

**Comment by chepitoco** [comment]
@bluebill1049  That is working on Edge..

**Comment by bluebill1049** [comment]
finally!

**Comment by chepitoco** [comment]
@bluebill1049  Thanks a lot!

**Comment by bluebill1049** [comment]
I will release the patch soon after (real) work :)
