### ISSUE TITLE
add support for flat name for dot notation

### ISSUE THREAD

**Issue by ilovett** [react-hook-form/react-hook-form#1584]
**Is your feature request related to a problem? Please describe.**

To avoid mapping between form and api requests, sometimes I want my key as a flat string with dot notation, and not to be automatically converted to nested objects.

**Describe the solution you'd like**

To trigger or avoid automatically parsing or nesting dot notation in `name`, use some way to tell parser to ignore nesting the dot notation, perhaps wrap with quotes:

```jsx
name="\"object.nested.db.filter.status.value\""
error={errors["\"object.nested.db.filter.status.value\""]}
helperText={errors["\"object.nested.db.filter.status.value\""]?.message}
```

*EDIT: Use escaped double quotes to show how it would work better.*

The dot notation could ignore automatically nesting because it contains or starts and ends with quotes `'` or `"`.

**Describe alternatives you've considered**

I see that `getValues` will return the flat key, but it doesn't feel right, I'd like to use normal submit handler if possible, but maybe I'm not seeing the right way to use it in this case.

**Comment by bluebill1049** [comment]
hey, @ilovett we had flat error object in v3, however, it's not Type compatible so we moved to nested object. I think you may have to use `get` from lodash.

**Comment by bluebill1049** [comment]
also a side note, we did consider to reproduce flat error object as well, but then it conflicts the type and make thing a lot more difficult too.

**Comment by ilovett** [comment]
Is that the `NestDataObject` type?  How does it infer from the `.` if there is a child vs. not treating the key as a string?

**Comment by bluebill1049** [comment]
I don't think we will support a flat error object, anything '.' inside the string will be converted into the `object`. `NestDataObject` was made to support when `values` and `errors` is not matching the data type.  @kotarella1110 the author can explain further here.

**Comment by kotarella1110** [comment]
@ilovett Thanks for your suggestion.
Because TS cannot parse the string literal type, this suggestion can cause to the following type error:

```ts
// This works
const { getValues, errors } = useForm<{
  "'object.nested.db.filter.status.value'": string;
}>();

name="'object.nested.db.filter.status.value'"
errors["'object.nested.db.filter.status.value'"]
getValues("'object.nested.db.filter.status.value'")

// This doesn't work
const { getValues, errors } = useForm<{
  "'object.nested.db.filter.status.value'": string;
}>();

name='"object.nested.db.filter.status.value"'
errors['"object.nested.db.filter.status.value"'] // It works in JS, but it's a type error in TS
getValues('"object.nested.db.filter.status.value"') // It works in JS, but it's a type error in TS
```

**Comment by ilovett** [comment]
Thanks @kotarella1110 .  The types do indeed pass, however the parsed values sent to `onSubmit` is parsed with the `'` prepended on first key, and appended to last key -- returns values like

```json
{ "\"object": { "nested": { "db": { "filter": { "status": { "value\"": "good" }}}}}}
```

It would be cool if instead of nesting, first checks if it's a string if it contains `'` (or some other way of telling RHF not to automatically `transformToNestObject`) and returns flat:

```
{ "object.nested.db.filter.status.value": "good" }
```

Not sure if thats very intuitive or maybe too hacky even.  I am just going to close this ticket.
