### ISSUE TITLE
Touched state gets triggered incorrectly on controlled inputs

### ISSUE THREAD

**Issue by leventeszmolka** [react-hook-form/react-hook-form#1588]
**Describe the bug**
On controlled inputs `touched` state gets triggered by `onChange` and not `onBlur`.

**Codesandbox link (Required)**
https://codesandbox.io/s/wispy-smoke-50v9s?file=/src/App.js

**Expected behavior**
The `touched` state change should get triggered by `onBlur`.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/nostalgic-northcutt-xlty2?file=/src/App.js

**Comment by leventeszmolka** [comment]
@bluebill1049 Many thanks for the quick response, it looks great on my side.
