### ISSUE TITLE
New update break types for Control component

### ISSUE THREAD

**Issue by iamchathu** [react-hook-form/react-hook-form#1591]
**Describe the bug**
I updated `react-hook-form` from `5.6.1` to `5.6.2`. After that typescript build get fails for Controller components 

```
Type 'Control<FormData>' is not assignable to type 'Control<Record<string, any>>'.
  The types returned by 'getValues(...)' are incompatible between these types.
    Type 'FormData' is not assignable to type 'Record<string, unknown>'.
      Index signature is missing in type 'FormData'.  TS2322
```

**To Reproduce**
See codesandbox

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-ts-bug-m8lyk?file=/src/index.tsx

**Expected behavior**
Control should use specified Type.

**Comment by kotarella1110** [comment]
I will fix tonight.

**Comment by bluebill1049** [comment]
thanks a lot @kotarella1110

**Comment by bluebill1049** [comment]
@kotarella1110 don't force yourself to fix it tonight. take it easy, do whenever you are free 🙏 thanks a lot.

**Comment by iamchathu** [comment]
Thanks a lot @kotarella1110 @bluebill1049

**Comment by kotarella1110** [comment]
@iamchathu I will fix this, but changing it from interface to type works with `v5.6.2`.

**Comment by iamchathu** [comment]
Thank you @kotarella1110

**Comment by alexeikaratai** [comment]
any update? when it will be fix ?

**Comment by bluebill1049** [comment]
doing it now @alexeikaratai
