### ISSUE TITLE
Validation is inconsistent with mode: "onBlur"

### ISSUE THREAD

**Issue by NishantGurung93** [react-hook-form/react-hook-form#1594]
**Describe the bug**
When repetitively focusing on and out of input field, the error state returned from validation is inconsistent. 

**To Reproduce**
1. Type any valid value in last name i.e. Tommy
2. Click on and out of input field to trigger onBlur 
3. Observe that the error state changes despite there being no change in the input value

**Codesandbox link (Required)**
Include a codesandox will help us to investigate the issue quicker.
https://codesandbox.io/s/react-hook-form-useform-template-e7jhu

**Expected behavior**
Given a valid input, the error state should stay unchanged no matter how many times onBlur is triggered. 

**Screenshots**
![](https://media.giphy.com/media/H7ICwsFrPNAEDYZNTl/giphy.gif)

Another screencap with mode and reValidateMode both set to "onBlur"
https://giphy.com/gifs/m9wAnUx7QJUHMWxVbT/html5

**Desktop (please complete the following information):**
 - Mac Mojave 10.14.6
 - Firefox Developer Edition 76.0.b7

**Comment by bluebill1049** [comment]
you want to take a look at `reValidateMode`

**Comment by NishantGurung93** [comment]
I believe reValidateMode matters only when it hits an error state, as it decides when to validate the input field again from an invalid state to a valid state.

The behaviour I'm seeing is that a valid input gets changed from a valid state into an invalid state just by focusing in and out of the field. 

https://codesandbox.io/s/react-hook-form-useform-template-tzyln?file=/src/index.js
Nevertheless, the issue still exists when using `reVaildateMode : "onBlur"`

**Comment by bluebill1049** [comment]
> I believe reValidateMode matters only when it hits an error state, as it decides when to validate the input field again from an invalid state to a valid state.
> 
> The behaviour I'm seeing is that a valid input gets changed from a valid state into an invalid state just by focusing in and out of the field.
> 
> https://codesandbox.io/s/react-hook-form-useform-template-tzyln?file=/src/index.js
> Nevertheless, the issue still exists when using `reVaildateMode : "onBlur"`

I can't reproduce. can you take a screen capture?

**Comment by NishantGurung93** [comment]
Yes, here it is. This one is from https://codesandbox.io/s/react-hook-form-useform-template-tzyln?file=/src/index.js with `mode` and `reValidateMode` both set to `onBlur`

https://giphy.com/gifs/m9wAnUx7QJUHMWxVbT/html5

**Comment by bluebill1049** [comment]
Thanks 👍  very strange issue.

**Comment by NishantGurung93** [comment]
I think it has to do with the pattern being applied. 

When I remove the pattern, the issue seems to subside. I hope this helps

**Comment by bluebill1049** [comment]
it is pattern related...

**Comment by bluebill1049** [comment]
it's due to 

`/^[-A-Za-zÀ-ÖØ-ʒͰ-ͳͶ-ͷͻ-ͽvΑ-Ͽἀ-ῼЀ-ӿễấ ']+-?[\sA-Za-zÀ-ÖØ-ʒͰ-ͳͶ-ͷͻ-ͽvΑ-Ͽἀ-ῼЀ-ӿễấ ']*$/g`

I think I remember now `/g` will keep append regex.

**Comment by bluebill1049** [comment]
https://stackoverflow.com/questions/1520800/why-does-a-regexp-with-global-flag-give-wrong-results

**Comment by NishantGurung93** [comment]
Great spot, removing the global tag does seem to fix the issue. Thank you :)

**Comment by bluebill1049** [comment]
I think i remember reading a post about this `/g`, regex will cache or append somehow, I can't find the post anymore.

**Comment by bluebill1049** [comment]
https://medium.com/@nikjohn/regex-test-returns-alternating-results-bd9a1ae42cdd
