### ISSUE TITLE
Default values not set in Material UI Autocomplete

### ISSUE THREAD

**Issue by joejordan** [react-hook-form/react-hook-form#1596]
**Describe the bug**
Default value is not set in Material UI's Autocomplete (which is internally a MUI TextField component).

**To Reproduce**
1. Create a form with a Material UI Autocomplete component
2. Provide useForm a defaultValues object that includes a value for Autocomplete
3. Load the form and the default value is not selected

**Codesandbox link (Required)**
- https://codesandbox.io/s/bold-sunset-umfcs?file=/src/App.js

**Expected behavior**
The default value should be set in the MUI autocomplete control

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by steelersd** [comment]
[Controller](https://react-hook-form.com/api#Controller) might be what you need.

Maybe a starting point https://codesandbox.io/s/vibrant-framework-i3e5d?file=/src/App.js

**Comment by bluebill1049** [comment]
Yes, please use controller for component doesn't expose ref.
