### ISSUE TITLE
Sharing refs doesn't work in TypeScript

### ISSUE THREAD

**Issue by jgonera** [react-hook-form/react-hook-form#1597]
**Describe the bug**
I'm trying to follow https://react-hook-form.com/faqs/#Howtosharerefusage but it won't compile in TypeScript.

**To Reproduce**
Try to compile the code from the Codesandbox below.

You'll get the following errors:

```typescript
register(ref, { required: true });
```

```
No overload matches this call.
  Overload 1 of 4, '(name: "name", validationOptions?: Partial<{ required: string | boolean | ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<...>)> | ValidationValueMessage<...>; ... 5 more ...; validate: Validate | Record<...>; }> | undefined): void', gave the following error.
    Argument of type 'HTMLInputElement | null' is not assignable to parameter of type '"name"'.
      Type 'null' is not assignable to type '"name"'.
  Overload 2 of 4, '(ref: FieldElement<{ name: string; }>, validationOptions?: Partial<{ required: string | boolean | ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<...>)> | ValidationValueMessage<...>; ... 5 more ...; validate: Validate | Record<...>; }> | undefined): void', gave the following error.
    Argument of type 'HTMLInputElement | null' is not assignable to parameter of type 'FieldElement<{ name: string; }>'.
      Type 'null' is not assignable to type 'FieldElement<{ name: string; }>'.
```

```typescript
inputRef.current = ref;
```
```
Cannot assign to 'current' because it is a read-only property.
```

**Codesandbox link (Required)**
I'm not sure how to configure Codesandbox for TypeScript but this is the code:
https://codesandbox.io/s/react-hook-form-useform-template-inuhg?file=/src/index.tsx

**Expected behavior**
It should compile.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Relevant package versions:
```
react@16.13.1
react-hook-form@5.6.1
typescript@3.8.3 
```

**Comment by jgonera** [comment]
It seems I just didn't know how to do it. https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31065#issuecomment-446425911 helped.

You have to do:

```typescript
const inputRef = useRef<HTMLInputElement | null>(null);

return (
  <input
    name="something"
    ref={(ref) => {
      if (ref) {
        register(ref, { required: true });
        inputRef.current = ref;
      }
    }}
  />
);
```
 />

I guess the docs don't really have TypeScript examples but maybe that's worth a mention?

Also, are the types wrong or is `if (ref)` a good idea for the JS version too?

**Comment by bluebill1049** [comment]
nice, you want to help and add the TS version on the doc?
