### ISSUE TITLE
formatter property Controller component

### ISSUE THREAD

**Issue by alpersogukpinar** [react-hook-form/react-hook-form#1600]
**Is your feature request related to a problem? Please describe.**
For some cases, I need to store different format or type of value in form than value passed to inner component. For example, I want to store date value in form within datetime format, but I need to pass moment type value to AntDesign DatePicker component. 
Using Controller's onChange prop I can convert value to Datetime format and store it in form values, but I don't have a place to convert Datetime value back to moment format before passing it to inner DatePicker component.
Another similar scenario may be for input components; I can parse data in Controller's onChange prop and store number in form values and need to pass a formatted string to inner input component.

**Describe the solution you'd like**
We can add a formatter prop to Controller component, If it is set, value can be formatted or converted before passed to inner component.
**Describe alternatives you've considered**
formatter prop accepts a format function like ` function(value: any): any`
**Additional context**
Proposed changed in controller.tsx to format value before passing it to inner component
![image](https://user-images.githubusercontent.com/8727187/81413093-8a7a4680-914d-11ea-99ff-8a37bd8a7600.png)

**Comment by bluebill1049** [comment]
take a look at this: https://github.com/react-hook-form/react-hook-form/blob/master/examples/parseFormatInputValues.tsx

https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-furtc

in the examples folder: https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-furtc

**Comment by alpersogukpinar** [comment]
Thanks for your quick response and additional Parse component seems to work for my case, but don't you think formatter prop would be a simpler solution.

**Comment by bluebill1049** [comment]
👍 Perper to avoid additional props at this stage, probably will include more information at the doc instead.

**Comment by angus-kablamo** [comment]
For what it's worth I came here looking for exactly this option. I'm not sure why you would supply a prop to override what the input value is parsed as with `onChange`, but no corresponding prop to format the value that's passed back to the input. The alternative example is more unwieldy than a simple formatValue function.
