### ISSUE TITLE
How do I access all array field values in validate callback?

### ISSUE THREAD

**Issue by paambaati** [react-hook-form/react-hook-form#1602]
**Describe the question?**

**To Reproduce**
1. Create a form that has field arrays (i.e. fields with same name + an array index).
2. Use `ref=register()` with a custom `validate` callback.
3. Try to validate the array, but get access to only each individual value in the callback.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-array-field-validate-callback-z0lxm?file=/src/App.js

**Additional context**
I'm trying to build a custom component that has multiple inputs (say `input1`, `input2` and `input3`) inside it. I've created them as a field array so RHF can easily use/validate them. I want to validate the value using some logic like this - 

```javascript
isValid = (value1 + value2 + value3) > 0 
```

Here's what I've tried for validating this so far —

1. Writing a custom Yup method and using `validationSchema`. But this would mean I have to write the schema for the rest of my form - today it has many inputs with most of them having simple rules (like `required`), so they're using only `ref={register({required: true})}`. Plus `yup` is overkill for a one-off validation.

2. Writing a custom `validationResolver`. This too means writing rules for every single field.

3. The linked CodeSandbox approach is the simplest for me, but it doesn't exactly work for my use-case.

Is there a way to get all 3 inputs (i.e. all field array values) inside the `validate` callback? That, or a way to mix `validationSchema`/`validationResolver` with rules already on the form.

**Comment by bluebill1049** [comment]
`getValues()`

**Comment by paambaati** [comment]
Ah, I'm really sorry for having overlooked that. I can confirm this works; thanks a lot!

**Comment by bluebill1049** [comment]
> Ah, I'm really sorry for having overlooked that. I can confirm this works; thanks a lot!

Hey @paambaati don't be sorry at all :) we all miss reading docs sometimes... have a good weekend.
