### ISSUE TITLE
reValidateMode: nested field change does not trigger parent validation

### ISSUE THREAD

**Issue by arthurRbr** [react-hook-form/react-hook-form#1603]
Hello,

I have an array that requires at least one value.

When a child input defined with `name={colors[${index}]} ` is updated, it triggers the validation of the child field, but not the validation of the parent array. 

Here is [a minimal repro](https://codesandbox.io/s/react-hook-form-validationschema-zsu78?file=/src/index.js) (I know I could define multiple checkboxes with the same name, but my real world case does not allow it.)

Thanks for this amazing lib!

**Comment by bluebill1049** [comment]
can you provide steps to reproduce? if it depends on validation, you may need to use `triggerValidation`.

**Comment by arthurRbr** [comment]
You can reproduce with [this repro ](https://codesandbox.io/s/react-hook-form-validationschema-zsu78?file=/src/index.js):
- submit the form, validation works, errors are properly set
- modify the `colors` array by selecting a checkbox, the array error is not removed, although `reValidateMode: true`, meaning the array validation was not triggered
- submit again, now the error goes away, meaning the array was validated this time

**Comment by bluebill1049** [comment]
@arthurRbr your codesandbox is v4? can you double-check with the latest?

**Comment by arthurRbr** [comment]
Yes the issue also happens with 5.6.3

**Comment by bluebill1049** [comment]
```
{["red", "yellow", "green"].map((color, index) => (
        <div key={index}>
          <label>{color}</label>
          <input
            name={`colors`}
            value={color}
            type="checkbox"
            ref={register}
          />
        </div>
      ))}
```

please take a look above for the fix.
