### ISSUE TITLE
input not touched until after clicking off of active button

### ISSUE THREAD

**Issue by ThahaShahzad** [react-hook-form/react-hook-form#1604]
defaultValues : {
item_type: ''
item_choices: [
        { choice: '', correct: 0 },
        { choice: '', correct: 0 },
        { choice: '', correct: 0 },
        { choice: '', correct: 0 }
      ]
}

i have a input that's rendered on start for item type, i have a component setup to then render the item choices input once the item_type is touched but its only touched once you click off the select input.

![image](https://user-images.githubusercontent.com/61521512/81476190-1768e280-91d6-11ea-9236-298175f4899e.png)

the select input have the blue acitve state when clicked but it doesnt get touched untill you click again anywhere on the screen

**Comment by bluebill1049** [comment]
please follow our issue/question template.

**Comment by bluebill1049** [comment]
will reopen until more context is supplied and follow our issue template.
