### ISSUE TITLE
formState does not seem to work properly in onChange mode and with a validate custom function

### ISSUE THREAD

**Issue by matteoscurati** [react-hook-form/react-hook-form#1607]
**Describe the bug**
My goal is that the submit button is enabled only if there are no errors in the form. The form consists of three checkboxes. At least one of the checkboxes must be true. If I select one of the checkboxes, the validation works correctly, but formState.isValid remains false. formState.isValid appears to change randomly by clicking on the form.

**To Reproduce**
1. Open Codesandbox
2. Try to click on checkboxes

**Codesandbox link (Required)**
https://codesandbox.io/s/checkbox-validation-8muf9

**Expected behavior**
If I select at least one checkbox, the submit button must be enabled.

**Screenshots**
![2020-05-10 16 53 46](https://user-images.githubusercontent.com/1284304/81502549-f17b3500-92de-11ea-85ca-b393eb9b80e6.gif)

**Desktop (please complete the following information):**
 - OS: iOS
 - Brave
 - Version 1.8.90 Chromium: 81.0.4044.129 (Official Build) (64-bit)

**Comment by bluebill1049** [comment]
because each checkbox has been assigned with individual validation if you check all of them then the validation pass.

1) create a wrapper component like MUI and use controller:
https://codesandbox.io/s/react-hook-form-controller-079xx

2) trigger validation to fire for the other two checkboxes.
