### ISSUE TITLE
handleSubmit possibility to catch when validation fails

### ISSUE THREAD

**Issue by gcourtemanche** [react-hook-form/react-hook-form#1614]
**Is your feature request related to a problem? Please describe.**
I'm using snackbars to show errors to the user and I need to create them one time when the validation fails. I can't rely on the `errors` object like when you show the error as text next to your field. I'm using `triggerValidation` at the moment, but it doesn't handle the focus on html elements.

**Describe the solution you'd like**
If it's possible that `handleSubmit` returns `Promise<boolean>` like with `triggerValidation`, it will solve my problem.

**Describe alternatives you've considered**
The best solution I have so far, but the focus is not 100% working and it's hacky.

`handleSubmit` override:
```
  const handleSubmit: FormContextValues<FormValues>['handleSubmit'] = (
    callback
  ) => async (event) => {
    event?.preventDefault();

    const isValid = await form.triggerValidation();

    if (isValid) {
	  const data = form.getValues();
      try {
        await callback(data);
      } catch (err) {
        // Log unexpected errors from your callback function
      }
    } else {
      Object.values(form.errors).forEach((error) => {
        const { message } = error as FieldError;
        errorSnackbar(message);
      });
    }
  };
```

In my form fields component:
```
  const { name } = props;
  const { errors } = useFormContext();

  const firstError = Object.keys(errors)[0];
  const errorsString = Object.keys(errors).toString();

    // Doesn't work when submitting 2 times with the same errors because errorsString doesn't change
  useEffect(() => {
    if (firstError === name) {
      elementRef.current.focus();
    }
  }, [firstError, errorsString]); 
```

**Additional context**

**Comment by bluebill1049** [comment]
you can upvote on this issue: https://github.com/react-hook-form/react-hook-form/issues/1574

**Comment by jpodpro** [comment]
has this been resolved? i cannot believe there would be no non-hack way to respond to an invalid form!

**Comment by bluebill1049** [comment]
@jpodpro take back your shitty comment, nobody is making open source to listen bullshit like that.

**Comment by jpodpro** [comment]
@bluebill1049 apologies man, didn't mean to come off as such. just very surprised with all the features that this isn't supported. i take this as a no.

**Comment by bluebill1049** [comment]
> @bluebill1049 apologies man, didn't mean to come off as such. just very surprised with all the features that this isn't supported. i take this as a no.

We all work here for **free** for everyone, so the moment you sounds like a BOSS is already wrong. Be appreciative and respect for each other. This feature is top on the board, and mostly like will be working on once all the bugs have been resolved for the next feature. as for now, you will have to use `errors` object (not the best).
