### ISSUE TITLE
Request to add 🏎 Downshift examples

### ISSUE THREAD

**Issue by paambaati** [react-hook-form/react-hook-form#1616]
**Is your feature request related to a problem? Please describe.**
[Downshift](https://github.com/downshift-js/downshift) is a fantastic library for creating WAI-ARIA compliant lightweight dropdown/combobox components, but is quite difficult to integrate properly with react-hook-form. It would be nice if there were a few examples that show how to implement Downshift + RHF.

**Describe the solution you'd like**
A few examples that show how to use Downshift with RHF including validation would be very helpful to developers trying to use these 2 packages.

**Describe alternatives you've considered**
I've struggled for days at this point to get them working correctly, but I still can't. I've tried `<Controller>`, using `setValues()` to force set values on the Downshift component, everything - nothing seems to work. For now, I'm contemplating using `react-select` as it has first-party examples.

**Comment by bluebill1049** [comment]
can you supply a simple base (codesandbox) for Downshift, I never really used it before, but I will give it a try.

**Comment by paambaati** [comment]
Here's a few examples —

1. https://codesandbox.io/s/github/kentcdodds/downshift-examples
2. https://codesandbox.io/s/simple-downshift-with-getrootprops-example-24s13
3. https://codesandbox.io/s/github/kentcdodds/downshift-examples/tree/master/?module=/src/other-examples/gmail/index.js&moduleview=1&file=/src/other-examples/gmail/index.js

**Comment by bluebill1049** [comment]
donwshift have been included in the example: https://codesandbox.io/s/react-hook-form-controller-079xx?file=/src/DonwShift.js

**Comment by JReinhold** [comment]
I hooked up Downshift with React Hook Form last week, it works pretty good. I can share my work, however it is quite specific to my use case (combobox, multiselect, etc.) and as there are many ways to use downshift, it probably needs to be simplified a bit.

But for now, here's the important parts of my code. The `MultiCombobox` component is a raw Downshift component that functions as a combobox with multi select. I then have the `MultiComboboxField` component, which wraps the `MultiCombobox` component to "glue" it into an RHF form. The important parts to look for, are `selectedItems` and `onSelectedItemsChange`, that gets passed to the useMultiSelect` hook.

```typescript

interface MultiComboboxProps<ItemType> extends StyleProps {
  label: string;
  items: ItemType[];
  itemToString: (item: ItemType) => string;
  itemToKey: (item: ItemType) => string;
  selectedItemToString?: (item: ItemType) => string;
  useComboboxProps?: UseComboboxProps<ItemType>;
  useMultipleSelectionProps?: UseMultipleSelectionProps<ItemType>;
}

/**
 * A general purpose combobox component for multiple selections. If you intend on using it in a form, you should import the MultiComboboxField component instead (from below)
 *
 * required props:
 * - label: the label of the field
 * - items: an array of items that the user should be able to choose from. these can be on any form, and this will determine the type (ItemType) for the other props
 * - itemToString: a function that converts a single item to a string. the string will be shown in the dropdown, and will be used for filtering the search
 * - itemToKey: a function used to extract a unique key for each item. is only used to uniquely tell the items apart, is not shown to the user
 *
 * optional props:
 * - useComboboxProps: any overrides you want to make to change the internal behavior of the combobox. see https://github.com/downshift-js/downshift/tree/master/src/hooks/useCombobox
 * - useMultipleSelectionProps: any overrides you want to make to change the internal behavior of the multiselection logic. see https://github.com/downshift-js/downshift/tree/master/src/hooks/useMultipleSelection
 */
export const MultiCombobox = <ItemType,>({
  label,
  items,
  itemToString,
  itemToKey,
  useMultipleSelectionProps,
  useComboboxProps,
  rootSx,
}: PropsWithChildren<MultiComboboxProps<ItemType>>): ReactElement => {
  // the value of the input field is managed in this state
  const [inputValue, setInputValue] = useState('');

  const {
    getSelectedItemProps,
    getDropdownProps,
    addSelectedItem,
    removeSelectedItem,
    selectedItems,
  } = useMultipleSelection<ItemType>({
    itemToString,
    ...useMultipleSelectionProps,
  });

  const getFilteredItems = (itemsToFilter: ItemType[]): ItemType[] => {
    if (inputValue.length === 0) {
      return itemsToFilter;
    }
    return itemsToFilter.filter((item) =>
      itemToString(item).toLowerCase().includes(inputValue.toLowerCase())
    );
  };

  const {
    isOpen,
    getToggleButtonProps,
    getLabelProps,
    getMenuProps,
    getInputProps,
    getComboboxProps,
    highlightedIndex,
    getItemProps,
    selectItem,
  } = useCombobox({
    inputValue,
    items: getFilteredItems(items),
    itemToString,
    // typings are wrong
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    onStateChange: ({ type, selectedItem, inputValue: newInputValue }: any) => {
      // this function is called whenever there is any state changes in the combobox
      // we switch on the type passed, to only react to the specific changes we care about
      switch (type) {
        case useCombobox.stateChangeTypes.InputChange:
          setInputValue(newInputValue as string);
          break;
        case useCombobox.stateChangeTypes.InputKeyDownEnter:
        case useCombobox.stateChangeTypes.ItemClick: {
          // in this case, an item is selected either using 'Enter' or mouse click
          if (!selectedItem) {
            break;
          }
          // toggle the selection of the item, by either removing it or adding
          if (selectedItems.includes(selectedItem)) {
            removeSelectedItem(selectedItem);
          } else {
            addSelectedItem(selectedItem);
          }
          // set the internal selection state of the combobox, I'm not quite sure why this is needed, but it solves a few interaction issues.
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          selectItem(null as any);
          setInputValue('');
          break;
        }
        case useCombobox.stateChangeTypes.InputBlur: {
          // clear input field on blur
          setInputValue('');
          break;
        }
        default:
          break;
      }
    },
    stateReducer: (state, { type, changes }) => {
      // this reducer is used to modify the internal state of the useCombobox hook, before the change gets dispatched to other handlers
      switch (type) {
        case useCombobox.stateChangeTypes.FunctionSelectItem:
        case useCombobox.stateChangeTypes.InputKeyDownEnter:
        case useCombobox.stateChangeTypes.ItemClick:
          // keep menu open when selecting an item
          return {
            ...changes,
            isOpen: state.isOpen, // keep old isOpen state
            highlightedIndex: state.highlightedIndex, // keep old highlightedIndex state
          };
        default:
          return changes;
      }
    },
    ...useComboboxProps,
  });


  //... render the actual component tree of the combobox here, as usual with downshift
};

/**
 * A wrapper around the MultiCombobox component that can be used to automatically tie it in with a form powered by react-hook-form
 * Remember to pass the 'control' prop, if the form is not wrapped with a FormContext
 *
 * props:
 * - name: the name of the field in the form (not to confuse with 'label')
 * - control (optional): if the form is not wrapped in a FormContext, pass a control method from the useForm hook
 * - ... any other props are passed on down to the Combobox component
 */
interface FormMultiComboboxProps<ItemType> extends MultiComboboxProps<ItemType>, StyleProps {
  name: string;
  control?: FormContextValues['control'];
}

export const MultiComboboxField = <ItemType,>({
  name,
  control,
  ...props
}: PropsWithChildren<MultiComboboxFieldProps<ItemType>>): ReactElement => (
  <Controller
    control={control}
    as={(controllerProps) => (
      <MultiCombobox
        {...props}
        useMultipleSelectionProps={{
          selectedItems: controllerProps.value ?? [],
          onSelectedItemsChange: ({ selectedItems }) => controllerProps.onChange(selectedItems),
        }}
      />
    )}
    name={name}
  />
);
```

**Comment by bluebill1049** [comment]
Thanks for sharing @JReinhold

**Comment by sarbazx** [comment]
> `donwshift` has been included in the example: https://codesandbox.io/s/react-hook-form-controller-079xx?file=/src/DonwShift.js

Hi, how to reset Downshift to initial state? given example does not reset downshift, it is still selected. @bluebill1049

**Comment by bluebill1049** [comment]
> > `donwshift` has been included in the example: https://codesandbox.io/s/react-hook-form-controller-079xx?file=/src/DonwShift.js
> 
> Hi, how to reset Downshift to initial state? given example does not reset downshift, it is still selected. @bluebill1049

have a play with the new `render` prop, it shouldn't be too hard.

**Comment by eltoro** [comment]
Is it possible to use useComboBox from DownShift in the same way? I get undefined as the value using the above example with useComboBox.

**Comment by bluebill1049** [comment]
@sarbazx the csb is been updated.

**Comment by Losses** [comment]
> The csb is been updated.

@bluebill1049 The reset in the csb didn't work on my machine……

![rhf](https://user-images.githubusercontent.com/1384036/103116740-6e0e2880-46a2-11eb-8248-0630118d838a.gif)

**Comment by colemars** [comment]
If you don't want it to be a Controlled input just forward the ref and pass it like so:

```tsx
  <input {...getInputProps({ ref })} />
```

Downshift will handle composing the refs

**Comment by 0xhjohnson** [comment]
> If you don't want it to be a Controlled input just forward the ref and pass it like so:
> 
> ```tsx
>   <input name={name} {...getInputProps({ ref })} />
> ```
> 
> Downshift will handle composing the refs

This is all I needed but with v7 it is slightly modified:
```tsx
  <input name={name} {...getInputProps({ ...register(name)})} />
```

**Comment by mirshko** [comment]
Does anyone have a simple downshift react-hook-form example that uses the https://github.com/downshift-js/downshift/tree/master/src/hooks/useCombobox api?

**Comment by karrui** [comment]
> Does anyone have a simple downshift react-hook-form example that uses the https://github.com/downshift-js/downshift/tree/master/src/hooks/useCombobox api, and allows input outside of the downshift item results?

I wouldn't call the implementation simple, but I just finished writing a custom SingleSelect component with ChakraUI and react-hook-form [here](https://github.com/opengovsg/FormSG/tree/form-v2/develop/frontend/src/components/Dropdown/SingleSelect)

**Comment by punkpeye** [comment]
```tsx
<input name={name} {...getInputProps({ ...register(name)})} />
```

`defaultValues` do not work with this pattern.

**Comment by punkpeye** [comment]
Feels hacky, but I was able to workaround this by setting `setValue` (from `react-hook-form`) _and_ setting `setInputValue` from Downshift.

```ts
useEffect(() => {
  if (router.query.query) {
    setValue("searchQuery", String(router.query.query));
    setInputValue(String(router.query.query));
  }
}, []);
```

**Comment by punkpeye** [comment]
This was a real PITA, but this finally worked:

```ts
const { ref: inputRef, ...input } = register("searchQuery", {
  required: true,
});

const searchQueryInputProps = {
  ref: (event: HTMLInputElement) => {
    inputRef(event);

    caretInputRef.current = event;
  },
  ...omit(
    omit(
      getInputProps(
        {
          ...input,
        },
        {
          suppressRefError: true,
        }
      ),
      "ref"
    ),
    "value"
  ),
};
```
