### ISSUE TITLE
Custom value using Controller and react-select

### ISSUE THREAD

**Issue by YassienW** [react-hook-form/react-hook-form#1620]
I am using a Controller with react-select. Normally react-select is given a set of option objects each with a value property and a label property. 

```javascript
const countries = [
  { label: "USA", value: "US" },
  { label: "Germany", value: "DE" },
  { label: "Australia", value: "AU" }
]
```

On change the selected value should be set to the option object itself.

```javascript
value={{ label: "USA", value: "US" }} onChange={ ([option]) => option }
```

In my case, i want to set the form value to the value property instead of the whole option object.
```javascript
value={ countries.find((o) => o.value === getValues("residence")) } 
onChange={ ([option]) => option.value }
```
Using the value prop like so on the Controller element doesn't seem to work

Below is a codesandbox link for more clarity

https://codesandbox.io/s/controller-with-react-select-nk621?file=/src/index.js

Any idea on how to achieve this with the Controller element?

**Comment by bluebill1049** [comment]
you will have to build a wrapper around react-select, or you can take a look at `downShift` as well which gives you the option to customise the return data.

**Comment by YassienW** [comment]
I built a simple wrapper around react-select which did the job, thank you for the quick response.

**Comment by bluebill1049** [comment]
awesome to hear @YassienW

**Comment by YassienW** [comment]
Below is the code in-case anyone ever needs it

```javascript
import React from "react";
import Select from "react-select";

export default function BetterSelect({options, value, getOptionValue, ...rest}) {
    return (
        <Select options={options} getOptionValue={getOptionValue} {...rest}
                value={options.find((option) => getOptionValue? getOptionValue(option): option.value === value)}/>
    );
}
```

**Comment by s-mahdi** [comment]
**LAZY METHOD**
There is a little trick to do so.
I've done this by passing the value to an `Object` and get the `value` in `handleSubmit` function.
here is an example:
```typescript
const onSubmit = handleSubmit(async (variables) => {
  variables = {
    ...variables,
   yourVariable: Object(variables.yourVariable).value,
  };
// ... rest of logic
}
```

**Comment by scottyeung** [comment]
> **LAZY METHOD**
> There is a little trick to do so.
> I've done this by passing the value to an `Object` and get the `value` in `handleSubmit` function.
> here is an example:
> 
> ```ts
> const onSubmit = handleSubmit(async (variables) => {
>   variables = {
>     ...variables,
>    yourVariable: Object(variables.yourVariable).value,
>   };
> // ... rest of logic
> }
> ```

It really worked! You saved my life during UAT!

**Comment by wasiqkhan** [comment]
This worked for me
```
<Controller
        render={({ field: { onChange, label } }) => (
          <Select
            getOptionValue={option=>option.value}
            options={[
              { value: "chocolate", label: "Chocolate" },
              { value: "strawberry", label: "Strawberry" },
              { value: "vanilla", label: "Vanilla" }
            ]}
            onChange={(e) => {
              // onChange's arg will send value into hook form
              onChange(e.value);
            }}
          />
        )}
        name="select"
        control={control}
        defaultValue={null}
      />
```

**Comment by Bartyee** [comment]
Hi
Can I dynamically use reset or setvalue in this case? I mean set id: 4 for example
