### ISSUE TITLE
Multiple useFieldArrays for the same array for different views only saves the last one

### ISSUE THREAD

**Issue by sirgwain** [react-hook-form/react-hook-form#1621]
**Describe the bug**
I am using a form to edit a Grandparent with children and grandchildren. I have a separate "view" allowing you to edit just a list of grandchildren.

The grandparent looks like this:

```javascript
const grandParent = {
  name: "Grandpa",
  children: [
    {
      name: "Child1",
      children: [
        {
          name: "Grandchild1"
        },
        {
          name: "Grandchild2"
        }
      ]
    },
    {
      name: "Child2",
      children: [
        {
          name: "Grandchild3"
        }
      ]
    }
  ]
};
```

If I change the name of Grandchild3 in the "All Grandchildren" view, it saves but does not update Grandchild3 in Child2's Grandchildren view. Also, if I change the name of GrandChild3 in the Child's Grandchildren view it doesn't save, it only uses the "All Grandchildren" view value.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-nested-nested-kxbxh?file=/src/index.js
2. Update Child2 -> Grandchild3 to Grandchild4
3. Click Save
4. See that All Grandchildren -> Grandchild3 is not updated
5. See that Child2 -> Grandchild3 is reset to whatever it started with.
6. Update All Grandchildren -> Grandchild3 to Grandchild4
7. Click Save
8. See that Child2 -> Grandchild3 is not updated

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-nested-kxbxh?file=/src/index.js

**Expected behavior**
It'd be great if wherever you made the change, it were reflected on all places referencing that form path. I'm not sure this is supported.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser Safari
 - Version:  13.1 (15609.1.20.111.8)

**Additional context**

**Comment by bluebill1049** [comment]
I don't think `useFieldArray` will play nicely with what you above, for RHF input `name` need to be unique, and the example above has two instances of `useFieldArray` which share with the same name.

**Comment by sirgwain** [comment]
Alright, thanks for the feedback. Can you think of any workaround to support multiple views into the same object on a form?

**Comment by bluebill1049** [comment]
you will probably need a different set of Field Array with a different group name.
