### ISSUE TITLE
Setvalue Select MUI

### ISSUE THREAD

**Issue by john182** [react-hook-form/react-hook-form#1623]
**Describe the bug**
setValue("object".{name:'teste'}) notworking

**To Reproduce**
Open codesandbox
Click button set value

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-zufdl?file=/src/index.js

**Expected behavior**
set value Select.age

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-controller-9ovo0?file=/src/index.js

**Comment by john182** [comment]
I'm using materialUI and not ReactSelect

**Comment by bluebill1049** [comment]
then it's even easier than... https://codesandbox.io/s/react-hook-form-controller-9ovo0?file=/src/index.js you should really spend sometimes on the doc, rather just send thing as a bug when it's working because you didn't read the doc.

**Comment by john182** [comment]
![image](https://user-images.githubusercontent.com/10438644/81759439-1d431a00-949b-11ea-9648-68b6a9dd9892.png)


I'm reading the documentation, but I'm applying it here in my project and it's not happening as in the examples

**Comment by bluebill1049** [comment]
Try this:

`onClick={() => setValue("Select", {age:10})}` This should worked as well.

**Comment by john182** [comment]
My project is more or less like this, I have a button to change and a select button to change the values ​​according to the example:

https://codesandbox.io/s/react-hook-form-controller-tftlj?file=/src/index.js

**Comment by bluebill1049** [comment]
That's the correct usage as Controller. can you convert it into Controller?

**Comment by bluebill1049** [comment]
let me know how did you go after convert to controller.

**Comment by john182** [comment]
I'll test it as a controller, and give feedback

**Comment by john182** [comment]
I made the change as requested, where I set values ​​for the options according to age, but it didn't happen as expected.

https://codesandbox.io/s/react-hook-form-controller-tftlj?file=/src/index.js

**Comment by bluebill1049** [comment]
can you do some comparison against the example? because in the CSB is working, you maybe missing something (minor)

**Comment by john182** [comment]
For me when I change the value of the Change SelectMUIt or click the setvalue button it does not change the value of the
MUI Select and also the value of
MUI Select is not being initialized

https://codesandbox.io/s/react-hook-form-controller-tftlj?file=/src/index.js

**Comment by bluebill1049** [comment]
Take a look this example: https://github.com/react-hook-form/react-hook-form/blob/master/examples/parseFormatInputValues.tsx

**Comment by YummyTi** [comment]
with [Mantine.dev UI ](https://mantine.dev/core/select/) setValue is not working, Bug!

**Comment by mizanmahi** [comment]
> Take a look this example: https://github.com/react-hook-form/react-hook-form/blob/master/examples/parseFormatInputValues.tsx

Link is broken !
