### ISSUE TITLE
Controlled input cant type after submit with errors

### ISSUE THREAD

**Issue by mr-moto** [react-hook-form/react-hook-form#1625]
**Describe the bug**
In my case I am using a controlled text input to check if the value is a number, if its not a number it doesnt change the state.
Im not sure if this is intended or if I missed something but if I submit the form without filling in anything and there is a validation error, the first key down value doesnt register and the backspace before the last text will not register ( need to hit backspace twice )

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controlled-input-v6h13?file=/src/index.js

Cheers!

**Comment by bluebill1049** [comment]
you are mixing controlled with uncontrolled.

https://react-hook-form.com/faqs#Whyisfirstkeystrokeisnotworking

if you need to use controllers, then register at `useEffect` and simply user `setValue` to update the input value.

**Comment by mr-moto** [comment]
ahh I totally missed that FAQ, thanks for pointing that out!

Ive updated the codesandbox to reflect the changes but im not sure if this would be the most optimal way set the value.

**Comment by bluebill1049** [comment]
hey @mr-moto you could use the `Controller` as well :) 

https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-furtc

lots of examples here: https://github.com/react-hook-form/react-hook-form/tree/master/examples
