### ISSUE TITLE
Touched data lost since version 5.6.0, when ref is not used

### ISSUE THREAD

**Issue by kevinveiga** [react-hook-form/react-hook-form#1628]
**Describe the bug**
Since version 5.6.0 touched data is not working, when ref is not used

**Comment by bluebill1049** [comment]
follow the template for reporting issue.

**Comment by gersmann** [comment]
@kevinveiga same problem here. did you figure out a solution to this?

**Comment by kevinveiga** [comment]
@gersmann I change version to 5.5.3

**Comment by gersmann** [comment]
@kevinveiga found the issue, at least for me, needed to do the registration inside useEffect in newer releases.
