### ISSUE TITLE
Material UI Multiline Autocomplete Component breaks with React-Hook-Form

### ISSUE THREAD

**Issue by achyutjhunjhunwala** [react-hook-form/react-hook-form#1629]
**Describe the bug**
I have an issue where the Multiline Autocomplete works perfectly fine, but the moment I incorporate it with react-hook-form, the form is able to load data, but the change event breaks

**To Reproduce**
1. Go to sandbox link below
2. You have 2 Material UI Autocomplete boxes. 1st one is with react-hook-form, 2nd one is without
2. Try to edit something in both. 2nd one works fine
4. 1st one will have error

**Codesandbox link (Required)**
https://codesandbox.io/s/material-demo-fcijs?file=/demo.js

**Expected behavior**
The application should not break with the on-change event.

**Additional context**
I am pretty sure I am doing something wrong, but I could not find any such example on the Docs as well. Would be grateful if this can be fixed

**Comment by bluebill1049** [comment]
hey take a look at https://react-hook-form.com/api#Controller

there is a CSB host a lot MUI examples: https://codesandbox.io/s/react-hook-form-controller-079xx

**Comment by achyutjhunjhunwala** [comment]
@bluebill1049  Thanks for pointing to the sandbox URL.
I was able to fix the issue. The only thing I was missing was the ```onChange``` event.

I added it and now it works.

I am trying to configure ```required``` validation for this object but somehow it does not fire on the Textbox. Can you please help here

https://codesandbox.io/s/material-demo-fcijs?file=/demo.js

**Comment by bluebill1049** [comment]
`rules={{ required: true }}`

**Comment by achyutjhunjhunwala** [comment]
Hi @bluebill1049 I actually tried that, looks like my sandbox did not update
https://codesandbox.io/s/material-demo-fcijs?file=/demo.js

I have added this 
```rules={{required: 'Required field'}}``` at `Controller` level
I even tried

```rules={{required: true}}``` at `Controller` level

But still doesn't give me a Red on the Input Box

**Comment by bluebill1049** [comment]
please have a read over the validation section under `register`, because you are returning item in the array, you will need to use validate function to check the length.

https://codesandbox.io/s/material-react-hook-form-yjvp0?file=/demo.js

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#register

**Comment by achyutjhunjhunwala** [comment]
Super Thanks @bluebill1049 
I have added validation error text message also for Autocomplete.

Anyone who comes to this issue, please refer the code sandbox link for implementation

https://codesandbox.io/s/material-demo-fcijs?file=/demo.js

**Comment by Camsteack** [comment]
Sorry to highjack the thread but it seemed related to my problem. The sandbox above doesn't work with the latest version of react hook form, I am getting ```(intermediate value)(intermediate value)(intermediate value).filter is not a function```

Here is the link which is the same as above with just the version updated https://codesandbox.io/s/material-react-hook-form-wxxu5

Is there anything I need to change to have it working with the latest react hook form ?

**Comment by bluebill1049** [comment]
> Sorry to hijack the thread but it seemed related to my problem. The sandbox above doesn't work with the latest version of react hook form, I am getting `(intermediate value)(intermediate value)(intermediate value).filter is not a function`
> 
> Here is the link which is the same as above with just the version updated https://codesandbox.io/s/material-react-hook-form-wxxu5
> 
> Is there anything I need to change to have it working with the latest react hook form ?

yes, take a look at the doc for `Controller`, we have introduced `render` prop. there is an codesandbox example too.

**Comment by Camsteack** [comment]
Hi @bluebill1049, it works great thanks for the quick reply

**Comment by publicaccount365** [comment]
> Hi @bluebill1049, it works great thanks for the quick reply

please share your solution.
I using version 6.0.8
how to set value?

**Comment by bluebill1049** [comment]
there is an example in the doc: https://react-hook-form.com/api#Controller
https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r

**Comment by vishaldhudum** [comment]
> please have a read over the validation section under `register`, because you are returning item in the array, you will need to use validate function to check the length.
> 
> https://codesandbox.io/s/material-react-hook-form-yjvp0?file=/demo.js

I have updated your example for v6.8.3, but 
1. when I click on Save button without values I get validation error => that works fine
2. but when I select a value after the above error, then the error should get removed => that's not working

refer code
https://codesandbox.io/s/material-react-hook-form-forked-x3s59?file=/demo.js

**Comment by bluebill1049** [comment]
> > please have a read over the validation section under `register`, because you are returning item in the array, you will need to use validate function to check the length.
> > https://codesandbox.io/s/material-react-hook-form-yjvp0?file=/demo.js
> 
> I have updated your example for v6.8.3, but
> 
> 1. when I click on Save button without values I get validation error => that works fine
> 2. but when I select a value after the above error, then the error should get removed => that's not working
> 3. Also on save button click the value is not submitted
> 
> refer code
> https://codesandbox.io/s/material-react-hook-form-forked-x3s59?file=/demo.js

Go the the doc: https://react-hook-form.com/api#Controller

there is an official CSB with autocompete.

**Comment by vishaldhudum** [comment]
I have checked the autocomplete below example but as soon as I enable multiple selection, it breaks plus doesn't have any example with validation for autocomplete.

example:
https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r?file=/src/MuiAutoComplete.js

**Comment by bluebill1049** [comment]
> https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r?file=/src/MuiAutoComplete.js

check MUi's doc on their props, you may need to wire them up instead of spread the props as i did, eg <Checkbox /> example.
