### ISSUE TITLE
Is there a way to validate just one field without submitting form?

### ISSUE THREAD

**Issue by manualva7** [react-hook-form/react-hook-form#1630]
I'm currently working with an async react-select that will compare an entered email to a list of emails in the db to compare and see if the email is already in use.

I've searched google and in the react-hook-form docs and haven't seen anything relevant. 

Is it possible to validate a field programmatically?

**Comment by sakalx** [comment]
https://react-hook-form.com/api#triggerValidation

**Comment by manualva7** [comment]
Thanks. I'll look into it.

**Comment by bluebill1049** [comment]
@sakalx thanks :) you got it .
