### ISSUE TITLE
errors inferred type is incorrect when using yup notRequired

### ISSUE THREAD

**Issue by tafelito** [react-hook-form/react-hook-form#1631]
Having a schema like this

```js
const schema = yup.object().shape({
smtpInfo: yup
    .object({
      host: yup.string().required(),
      port: yup.string().required(),
      user: yup.string().required(),
      password: yup.string().required(),
      secure: yup.boolean(),
    }).notRequired()
```

when inferring the form data type 

`type FormData = yup.InferType<typeof schema>;`

the errors type returning from
```js
const { handleSubmit, errors, formState, register, reset, watch } = useForm<
    FormData
  >({
    validationSchema: schema,
  });
```

is incorrect

`errors.smtpInfo` returns a `FieldError | undefined` whereas removing the notRequired from the schema it returns a `NestDataObject<{...}, FieldError>  | undefined`

**Expected behavior**
The returned type should still be the nested object with all the fields, since it could be undefined one can add a check for that.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/1514

**Comment by tafelito** [comment]
Maybe I didn't explain my  self correctly but I don't think the issues are related. 

The issue I have is with the errors object not correctly inferring the types from the schema when any of the fields has a notRequired or nullable

The values types in the handleSubmit are correct.

**Comment by bluebill1049** [comment]
I don't think we are supporting schema type `infer` on V5, @kotarella1110 will this be solved on V6?

**Comment by tafelito** [comment]
here's a demo just in case you wanna see what I meant

https://codesandbox.io/s/ts-react-hook-form-validated-submit-xqfj9?file=/src/App.tsx

**Comment by kotarella1110** [comment]
> I don't think we are supporting schema type `infer` on V5, @kotarella1110 will this be solved on V6?

Yes. This will be fixed in V6. 
https://codesandbox.io/s/ts-react-hook-form-validated-submit-5yoj7?file=/src/App.tsx

@bluebill1049 Should I apply this fix to V5?

**Comment by bluebill1049** [comment]
> > I don't think we are supporting schema type `infer` on V5, @kotarella1110 will this be solved on V6?
> 
> Yes. This will be fixed in V6.
> https://codesandbox.io/s/ts-react-hook-form-validated-submit-5yoj7?file=/src/App.tsx
> 
> @bluebill1049 Should I apply this fix to V5?

awesome! no, let's roll this out in V6. 👍

**Comment by bluebill1049** [comment]
I will close this issue, let's reopen if this is still an issue at v6. we should be able to release rc version this or next week.

**Comment by tafelito** [comment]
@bluebill1049 just updated to v6 and the nested object error is not an issue anymore but there is still an issue when the type is an array of nested fields

So if you have something like
```js
field: yup.array(yup.object({....}).required()
``` 

and you try to do 

```js
errors?.field?.message
```

you will get `Property 'message' does not exist on type '(DeepMap<object & { value: string; }, FieldError> | undefined)[]'.`

**Comment by bluebill1049** [comment]
@kotarella1110 can you please take a look at this one?

**Comment by kotarella1110** [comment]
@tafelito You cannot use `yup.InferType` if it contains object or array value in `FormData`.
You have to define the type yourself using `NestedValue`.

```ts
import { NestedValue } from 'react-hook-form';

type FormData = {
    smtpInfo?: {
        host: string;
        port: number;
    } | undefined;
    description: string;
    testObject: NestedValue<{
        test: string;
    }>;
}
```

**Comment by tafelito** [comment]
OK so I guess I will have to do a mix between the 2 😕. Something Like this

```js
type FormData = yup.InferType<typeof validationSchema> & {
  smtpInfo?:
    | {
        host: string;
        port: number;
      }
    | undefined;
  testObject: NestedValue<{
    test: string;
  }>;
};
```

Thanks @kotarella1110 for the response

**Comment by krish-dev** [comment]
I'm using version `6.0.8` I have a very simple login form that does not have a nested object or array. However, I'm getting the same error

```
Type 'InnerInferType<Shape<object | undefined, { email: string; password: string; }>>' does not satisfy the constraint 'Record<string, any>'.
  Type 'undefined' is not assignable to type 'Record<string, any>'.
```
![Screenshot 2020-07-22 at 3 22 48 PM](https://user-images.githubusercontent.com/7298557/88162888-87accf00-cc2f-11ea-8d4d-d4a30728447f.png)


Here is my simple login form code.

```typescript
import React from 'react';
import {useForm} from 'react-hook-form';
import {yupResolver} from '@hookform/resolvers';
import * as yup from 'yup';

const loginSchema = yup.object().shape({
  email: yup.string().defined().email(),
  password: yup.string().defined(),
});

const initialValues = {email: '', password: ''};

type LoginInput = yup.InferType<typeof loginSchema>;

const LoginForm = () => {
  const {register, handleSubmit} = useForm<LoginInput>({
    defaultValues: initialValues,
    resolver: yupResolver(loginSchema),
  });

  const onSubmit = (data: LoginInput) => {
    console.log(data);
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <label>Email</label>
      <input type="email" name="email" ref={register} />
      <label>Password</label>
      <input type="password" name="password" ref={register} />
      <input type="submit" />
    </form>
  );
};

export default LoginForm;

```

**Comment by KyllianV** [comment]
@krish-dev It seems to be a problem with the last "@types/yup" version.

**Comment by krish-dev** [comment]
> @krish-dev It seems to be a problem with the last "@types/yup" version.

@KyllianV I'm using `0.29.3` version of `@type/yup`

**Comment by KyllianV** [comment]
@krish-dev The last version working is `0.28.3`

**Comment by krish-dev** [comment]
@KyllianV Thanks. `@type/yup` `0.28.3` is working.

**Comment by tafelito** [comment]
@bluebill1049 this is still an issue with `yup` version `0.29.3`. I'm not sure what the issue is tho
