### ISSUE TITLE
Yup validation, state is stale.

### ISSUE THREAD

**Issue by kiansenggoh** [react-hook-form/react-hook-form#1632]
Hi 
below is the codesandbox for your reference.
[https://codesandbox.io/s/react-hook-form-usefieldarray-rik8q?file=/src/index.js](https://codesandbox.io/s/react-hook-form-usefieldarray-rik8q?file=/src/index.js
)

after the form is loaded, useEffect update the state to "world". but when fieldArray validation triggers, the state in the testFirstName is stale, "hello"

**Comment by bluebill1049** [comment]
Please follow our issue template, can you imagine if I provide this little information and ask you to solve an issue.

**Comment by kiansenggoh** [comment]
sorry about it.

**Describe the bug**
after useEffect update the state, the yup validation scheme still reading the old state.
[https://codesandbox.io/s/react-hook-form-usefieldarray-rik8q?file=/src/index.js](https://codesandbox.io/s/react-hook-form-usefieldarray-rik8q?file=/src/index.js
)
**To Reproduce**
Steps to reproduce the behavior:
1. Open the above URL
2. focus on the fieldArray, either Bill or Luo
3. blur it
4. look at the console log.
5. u will see that the state in the testFirstName function is stale.

**Codesandbox link (Required)**
[https://codesandbox.io/s/react-hook-form-usefieldarray-rik8q?file=/src/index.js](https://codesandbox.io/s/react-hook-form-usefieldarray-rik8q?file=/src/index.js
)

**Expected behavior**
state in the testFirstName should be the same as updated by the setState in the useEffect at line 101

**Screenshots**
u can see that the console log the state is toggling 
![image](https://user-images.githubusercontent.com/56799988/82018106-27d9fb00-96b7-11ea-937a-ce2f8b9b4059.png)

**Comment by bluebill1049** [comment]
awesome! thank you i will take a look @kiansenggoh

**Comment by bluebill1049** [comment]
oh i see, what you are doing here, you will need to use validationResolver and combined with Context, we cache validation schema inside react hook form.

**Comment by Gabrieltay** [comment]
> oh i see, what you are doing here, you will need to use validationResolver and combined with Context, we cache validation schema inside react hook form.
Are you referring to FormContext?

**Comment by kiansenggoh** [comment]
U mean to use formContext? Where should we use formContext? Can give example? Or could u fix the code sandbox? 
For our sceanrio what we got is redux value stale.

**Comment by bluebill1049** [comment]
sorry I meant `validationContext`. take a look at the https://react-hook-form.com/api useForm section.

**Comment by bluebill1049** [comment]
Take a look at this CSB: https://codesandbox.io/s/react-hook-form-validationresolver-b3phr

**Comment by kiansenggoh** [comment]
Hi @bluebill1049, thanks for the tip now working perfectly :)

BTW we also found that if we use <Controller as={<input />}> the state is update to date.
why is controlled and uncontrolled has that difference?

**Comment by bluebill1049** [comment]
> BTW we also found that if we use <Controller as={}> the state is update to date.
> why is controlled and uncontrolled has that difference?

can you provide more detail above?

**Comment by kiansenggoh** [comment]
Hi @bluebill1049,

you just change from uncontrolled to controlled using controller. 
see the image below.
then u repeat the "Reproduce Steps" from above post
u will see that the state correct.

![image](https://user-images.githubusercontent.com/56799988/82106315-ab94f580-9752-11ea-9de7-70b65207c8ce.png)

**Comment by bluebill1049** [comment]
hey @kiansenggoh I don't see cached value in the console, there will be the difference between register with ref and controller. 

1. register with ref: state live inside the input itself
2. register with controller: state live inside the controller

the custom hook will collect data from both of them.

**Comment by kiansenggoh** [comment]
Thank u
