### ISSUE TITLE
S2339: Property 'message' does not exist on type 'FieldError[]'

### ISSUE THREAD

**Issue by Motoxpro** [react-hook-form/react-hook-form#1633]
**Describe the bug**
Typescript error when field is of array type
`S2339: Property 'message' does not exist on type 'FieldError[]'`

**To Reproduce**
1. Define an array type `sanction: string[];`
2. Try to access the error `helperText={errors.sanction?.message}`

I know this has been an issue for awhile, just wondering if there are some steps to take to remedy it.

**Comment by bluebill1049** [comment]
This will be improved on V6 :)

**Comment by bluebill1049** [comment]
Take a look this PR: https://github.com/react-hook-form/react-hook-form/pulls 

`NestedValue` is what @kotarella1110 introduced to solve this problem. feel free to asking him questions around this new type.

**Comment by Motoxpro** [comment]
Thanks @bluebill1049 ! Awesome work as always! 

Sorry if it is posted somewhere obvious, but is there a timeline for V6? No rush, just curious :)

**Comment by bluebill1049** [comment]
RC version should be shipped in this or next week.

**Comment by hui21109** [comment]
still happens in v6, can you help with that? 
also for the "type" property,
for an array field xxx.
when I want to get errors.xxx?.type
shows `Property 'type' does not exist on type '(FieldError | undefined)[]'.`
