### ISSUE TITLE
Disable/remove reValidate on successful form submission

### ISSUE THREAD

**Issue by mr-moto** [react-hook-form/react-hook-form#1635]
**Describe the bug**
referencing the discussion on spectrum:
https://spectrum.chat/react-hook-form/help/disable-revalidate-after-a-successful-form-submission~c0917959-6364-46e8-a198-bbce8a5f3726

**To Reproduce**
1. input something in the field
2. click submit
3. focus the field
4. click outside(onblur) the field OR type something and delete everything
5. reValidate is still active

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-reset-form-ooltn?file=/src/index.js

**Expected behavior**
reValidate should not be active after a successful form submission

**Comment by bluebill1049** [comment]
Got it, please take a look at the codesandbox inside:
https://codesandbox.io/s/react-hook-form-reset-form-m8vly?file=/src/index.js

because `handleSubmit` is setting `isSubmitted` after invoke `callback`.

**Comment by bluebill1049** [comment]
I will post this answer at spectrum as well.

**Comment by mr-moto** [comment]
@bluebill1049 
just found a small bug in the codesandbox.
Clicking submit will show the error message only for a split second before disappearing.

since `handlesubmit` is setting `isSubmitted` after `callback`, `isSubmitted` is set to true which in turn triggers the `useEffect` and resets all errors.

to fix, just add a state to let the `useEffect` know to reset
https://codesandbox.io/s/react-hook-form-reset-form-trno4?file=/src/index.js

**Comment by bluebill1049** [comment]
good one @mr-moto what about this? https://codesandbox.io/s/react-hook-form-reset-form-m8vly?file=/src/index.js

**Comment by mr-moto** [comment]
even better :)
