### ISSUE TITLE
HomePage form example

### ISSUE THREAD

**Issue by vitaliemiron** [react-hook-form/react-hook-form#1637]
Can you provide an example with form on your home page?
I want to build a form which will reValidate input if user completed but user changes his mind and decided to remove few letters.

This don't work if use mode ,,onBlur" that I need too. 

![2020-05-15 18 40 33](https://user-images.githubusercontent.com/45145592/82069204-a779c100-96db-11ea-9e7d-861cac951310.gif)

**Comment by bluebill1049** [comment]
please learn the lib and read the doc. it's pretty easy to achieve.
