### ISSUE TITLE
FieldArray with Controller field values reused after remove

### ISSUE THREAD

**Issue by esjs** [react-hook-form/react-hook-form#1638]
**Describe the bug**
I've noticed that with latest version 5.7.2 at this moment fields with Controller restore previous values when used inside fieldArray.

**To Reproduce**
1. If we have predefined set of fieldArray
2. We remove them
3. We add new fields using append
4. Fields that use Controller restore previous state

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-v9d9p?file=/src/index.js

**Expected behavior**
Field shouldn't be able to restore previous value if row has unique ID.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.4 
 - Browser Chrome 
 - Version  81.0.4044.138

**Comment by bluebill1049** [comment]
`append({});` please change to your data shape.

eg:
`append({ firstName: "appendBill", lastName: "appendLuo" });`

**Comment by esjs** [comment]
Well, how can I know which information will be inserted into fields ahead of time? 
Or should I add empty value for each field? Doesn't it look strange to you?

**Comment by bluebill1049** [comment]
> Well, how can I know which information will be inserted into fields ahead of time?

That's your application's requirement, and you should know.

> Or should I add empty value for each field? 

yes

> Doesn't it look strange to you?

no

**Comment by esjs** [comment]
Well, it does, but I thought that since fieldArray has unique key for each record it can uniquely distinguish records and not reuse previous values. If it's not the case, I'll add empty initial values, no problem with this.
Looks like I misunderstood  usage of id property.
Thanks for clarification!

**Comment by bluebill1049** [comment]
all good @esjs :) I think it's a little bit of mental shift from controlled to uncontrolled. The key was made so react wouldn't accidentally overwrite inputs, since we don't have local state to "chain" up the inputs.
