### ISSUE TITLE
Preset Regexes

### ISSUE THREAD

**Issue by aress31** [react-hook-form/react-hook-form#1640]
Hi,

In order to make this library even more powerful and easy to use I suggest exposing a few preset regexes for form validation, fields I can think of are:
- email address
- name
- phone number
- password - with different level of complexity
- message

Exposing these ready to use regexes (maintained by the community) in addition to the option of setting our own regexes could be a nice addition.

Looking forward to hear your feedback on the idea.

**Comment by bluebill1049** [comment]
sounds like a great idea :) probably a simple readme will do, happy for you to drive this and link to the readme or gist file.

**Comment by bluebill1049** [comment]
I am going to close this issue, feel free to leave the gist/github location and i will follow up to update the doc to include them.
