### ISSUE TITLE
Netlify Form Integration

### ISSUE THREAD

**Issue by aress31** [react-hook-form/react-hook-form#1641]
**Describe the bug**
I use Netlify server-less forms alongside the `Material-UI lib`. My form uses `Controlled children` but there is an issue with the fact that `Netlify` requires the following field to process the form - this field is not a `Controlled child`:

`<input name="form-name" type="hidden" value="contact" />`

**Codesandbox link (Required)**
This is code snippet illustrates the issue:

```js
<form onSubmit={handleSubmit(onSubmit)}>
  <input name="form-name" type="hidden" value="contact" />
  <Controller
    required
    as={TextField}
    autoComplete="name"
    control={control}
    error={errors.name}
    helperText={errors.name && errors.name.message}
    label="Your name"
    name="name"
    placeholder="Joe Bloggs"
    rules={{
      pattern: {
        message: "The name format is invalid.",
        value: /^[a-z ,.'-]+$/i,
      },
      required: {
        message: "This field is required.",
        value: true,
      },
    }}
    type="text"
    variant="standard"
  />
  <Button disabled={!isValid || isSubmitting} type="submit" variant="outlined">
    Send to us
  </Button>
</form>;
```

**Expected behavior**
A workaround to remove the console error, and ideally adding a site note to the official HRF doc to help people avoiding this issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/11601622/82122481-dc455100-978b-11ea-8170-7da7b16e738c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: Version 81.0.4044.138 (Official Build) (64-bit)

**EDIT:** After more digging I am not sure the error message comes from this Netlify field, it seems it comes more from the `Material-UI` integration. The relevant stack trace:
```
Warning: A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
    in input (created by ForwardRef(InputBase))
    in div (created by ForwardRef(InputBase))
    in ForwardRef(InputBase) (created by WithStyles(ForwardRef(InputBase)))
    in WithStyles(ForwardRef(InputBase)) (created by ForwardRef(Input))
    in ForwardRef(Input) (created by WithStyles(ForwardRef(Input)))
    in WithStyles(ForwardRef(Input)) (created by ForwardRef(TextField))
    in div (created by ForwardRef(FormControl))
    in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
    in WithStyles(ForwardRef(FormControl)) (created by ForwardRef(TextField))
    in ForwardRef(TextField) (created by WithStyles(ForwardRef(TextField)))
    in WithStyles(ForwardRef(TextField)) (created by Controller)
    in Controller (at Form.jsx:100)
    in form (at Form.jsx:98)
```

**Comment by vensauro** [comment]
have you passed a defaultValues for the `TextField` ?

**Comment by aress31** [comment]
@vensauro no I haven't I'll try to do that later to see if it fixes the issue.

**Comment by bluebill1049** [comment]
yes @vensauro :) you are right. thank you

missing `defaultValue` at `controller`.

**Comment by aress31** [comment]
I can confirm that it did solve my issue, thanks @vensauro and @bluebill1049!

**Comment by CikaDraza** [comment]
@arres31 can you paste here code. How you solve this. What is defaultValue in your Hook

**Comment by vensauro** [comment]
> @arres31 can you paste here code. How you solve this. What is defaultValue in your Hook

```js
useForm({
  defaultValues: {
	fullname: ''
  }
})
```
or
```js
<Controller
  name="fullname"
  control={control}
  render={...}
  defaultValue=""
/>
```
or
```js
useController({
  name: 'fullname',
  control,
  defaultValue: ''
})
```
