### ISSUE TITLE
React does not recognize the `nodeRef` prop on a DOM element.

### ISSUE THREAD

**Issue by giovanniantonaccio** [react-hook-form/react-hook-form#1642]
**Question**
Hello, I'm trying to integrate @material-ui/pickers with react-hook-form Controller.

I created a DateField component to hide this integration and everything seems to work perfectly fine, except for the warning in the image below. The `Controller` is forwarding a prop called `nodeRef` to `Transition` component on `MuiDatePicker`.

The warning shows up when the user clicks to show the modal.

Is there anything that can be done to avoid it?

The versions of the lib that I'm using are:
"@date-io/date-fns": "1.3.13",
"@material-ui/core": "4.9.14",
"@material-ui/pickers": "3.2.9",
"date-fns": "2.13.0",

**To Reproduce**
1. Click to open the datefield picker modal
2. Loot at the console

**Codesandbox link**
https://codesandbox.io/s/datefield-hook-form-5necc?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/8068067/82130706-ca6baa00-979b-11ea-9c95-0fa38621faca.png)

**Comment by bluebill1049** [comment]
I have very little clue on this one after investigation, maybe wrapper Controller around this component which passes `nodeRef`?

**Comment by giovanniantonaccio** [comment]
Thanks for the quick reply @bluebill1049, but I didn't understand your answer. Are you referring to react-hook-form Controller?

**Comment by bluebill1049** [comment]
yes @giovanniantonaccio i have no idea where is that nodeRef coming from. maybe u need to use Controller outside the scope of this nodeRef prop.

**Comment by giovanniantonaccio** [comment]
@bluebill1049 I removed everything from react-hook-form and left just @material-ui/pickers on my test. The problem still persists, so it seems to be a problem related just to @material-ui/pickers.

I opened an issue on their repository: https://github.com/mui-org/material-ui-pickers/issues/1790

Thansk for your help!

**Comment by bluebill1049** [comment]
haha, I did wonder where is that coming from 👍 all good. hope you get a solution soon.
