### ISSUE TITLE
Force Button rerender when isSubmitting

### ISSUE THREAD

**Issue by aress31** [react-hook-form/react-hook-form#1645]
**Describe the question?**
I have form created with the `Material-UI lib`, when my form is submitting I would like to set the `Button` state to `disabled`. However, the `Button` does not get re-rendered when the `isSubmitting` value changes - should not that trigger a re-render in a similar way than `React.useState()`?

**Codesandbox link (Required)**
```js
const {
  control,
  handleSubmit,
  errors,
  formState: { isSubmitting, isValid },
} = useForm({
  defaultValues: {
    "form-name": "contact",
    name: "",
  },
  mode: "onChange",
});

return (
  <form noValidate onSubmit={handleSubmit(onSubmit)}>
    <Controller as="input" control={control} name="form-name" type="hidden" />
    <Controller
      required
      InputLabelProps={{
        shrink: true,
      }}
      as={TextField}
      autoComplete="name"
      control={control}
      error={Boolean(errors.name)}
      helperText={errors.name && errors.name.message}
      label="Your name"
      name="name"
      rules={{
        pattern: {
          message: "The name format is invalid.",
          value: /^[a-z ,.'-]+$/i,
        },
        required: {
          message: "This field is required.",
          value: true,
        },
      }}
      type="text"
    />
    <Button
      disabled={!isValid || isSubmitting}
      type="submit"
    >
      Send
    </Button>
  </form>
);
```

**Comment by bluebill1049** [comment]
1. try to do a console log and double-check if the value is not changing.
2. provide a codesandbox to reproduce the problem and I will investigate

**Comment by aress31** [comment]
@bluebill1049  sure this is the sandbox - I am not familiar with sandbox so not sure how to share my sandbox link:
- https://codesandbox.io/s/react-hook-form-controller-template-yrtdc?file=/src/index.js

**Comment by bluebill1049** [comment]
`isSubmitting` should be placed outside the onSubmit function: 

https://codesandbox.io/s/react-hook-form-controller-template-wxurd?file=/src/index.js
