### ISSUE TITLE
How do I keep initial/default values up to date if a RHF input is unmounted?

### ISSUE THREAD

**Issue by Motoxpro** [react-hook-form/react-hook-form#1647]
**Describe the question?**
How do I keep initial/default values up to date if RHF is unmounted?

**To Reproduce**
1. Open the Popover
2. Set a new text value and click "Submit"
3. Click "ReRender" to see the outputs in the console and confirm it has set
4. Close the popover (click outside) and re open it to see a stale initial value 

**Codesandbox link (Required)**
https://codesandbox.io/s/rhf-dcit5?file=/demo.tsx

**Additional context**
This is a simulation of data getting sent to the server and the popover need needing to display the most recent data in the text field when the user opens it again.
Normally "dataFromServer" would be passed down from props and the "Submit" would be a graphql request but the exact same thing happens in both situations.

Thanks!!

**Comment by bluebill1049** [comment]
I would use `reset` API to update the `defaultValues`.

**Comment by Motoxpro** [comment]
Thank you @bluebill1049 !

1. Would I be able to just use `reset()` in the `handlePopoverClose` method? or would I need to pass in the values?

2. this would be ideal. Is there anyway to pass up the `handleSubmit` method from the child to the parent? i.e. all the RHF logic is inside the popover but the submit needs to happen outside the popover.

**Comment by bluebill1049** [comment]
> Thank you @bluebill1049 !
> 
> 1. Would I be able to just use `reset()` in the `handlePopoverClose` method? or would I need to pass in the values?
> 2. this would be ideal. Is there anyway to pass up the `handleSubmit` method from the child to the parent? i.e. all the RHF logic is inside the popover but the submit needs to happen outside the popover.

1. 
```
reset({
  ..getValues(),
  yourValue: 'test
})
```

2. i was thinking of building a separate form and update your value into your external store.

**Comment by Motoxpro** [comment]
@bluebill1049 

1. Gotcha. 

2. I'm sorry, I don't understand. :(

**Comment by bluebill1049** [comment]
> @bluebill1049
> 
> 1. Gotcha.
> 2. I'm sorry, I don't understand. :(

2.
```
<form>
  {...your main form}
</form>

<Popup>
  <form>
    {...your main form}
  </form>
</Popup>
```

separate forms.

**Comment by Motoxpro** [comment]
Ugh, Right. Thank you so much for your time!
