### ISSUE TITLE
Multi page  form - validation error

### ISSUE THREAD

**Issue by AlinDev** [react-hook-form/react-hook-form#1649]
**Describe the bug**
When I have the form split into multiple screens on a React Native app,  the validation only gets triggered for the first and  last field,of the form

**To Reproduce**
1. Go to field F.Name 
2. Enter some text (true will appear under the text input)
3. Go to field F.Name 
5. Enter some text  (!no message appears under the text input)
6. Go to the next tab(bottom tab)
7. Go to field Email
5. Enter some text  (!no message appears under the text input)
6. Go to the next tab(bottom tab)
7. Go to field Number
5. Enter some text  (true appears under the text input)
4. navigate back, and all fields have their validation triggered

**Codesandbox link (Required)**
Include a code sandbox that will help us to investigate the issue quicker.
 I used snacks.expo.io, hope it is ok:

https://snack.expo.io/@alindev/issue-react-hook-form

**Expected behavior**
After each text change in any of the TextInput either true or false will appear under it, signaling the validation trigger and re-rendering 
 
**Desktop (please complete the following information):**
 - OS: MAC OS  
**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS8.1 

**Additional context**

Hope you can help.
Thanks,
Alin

**Comment by bluebill1049** [comment]
hey, the problem is that you are sharing the same hook instance, you should have `useForm` on each page. :) let me know if this helps.

**Comment by bluebill1049** [comment]
you may want to watch this vidoe: https://www.youtube.com/watch?v=CeAkxVwsyMU it's web-based but should share the idea.
