### ISSUE TITLE
Required rule accepts all white space string

### ISSUE THREAD

**Issue by janjanarnaldo** [react-hook-form/react-hook-form#1650]
**Describe the question?**
I just have a simple question, how do we handle a required input that should also trap all empty spaces?

**To Reproduce**
Create an input with required rule, put empty spaces and submit the form. It treats the input as valid.

**Comment by bluebill1049** [comment]
`validate: (value) => { return !!value.trim()}`

should works with validate function above.

**Comment by breytex** [comment]
Hey!
Sorry for re-opening.
I have the feeling that this needs a first-level-feature.

In 90% of use cases of `required: true`, it just feels wrong to allow spaces, semantically.
If you would have to use `validate` for every time you need to trap spaces, this would make the `required` feature obsolete. 
I actually wrote a wrapper around the hook which injects a `validate: (value) => { return !!value.trim()}` every time I set `required:true` across the entire project.

Is there room for discussing that as a setting for the main hook?
Something like `{ trapSpacesForRequiredFields:true }` ?

**Comment by bluebill1049** [comment]
> Hey!
> Sorry for re-opening.
> I have the feeling that this needs a first-level-feature.
> 
> In 90% of use cases of `required: true`, it just feels wrong to allow spaces, semantically.
> If you would have to use `validate` for every time you need to trap spaces, this would make the `required` feature obsolete.
> I actually wrote a wrapper around the hook which injects a `validate: (value) => { return !!value.trim()}` every time I set `required:true` across the entire project.
> 
> Is there room for discussing that as a setting for the main hook?
> Something like `{ trapSpacesForRequiredFields:true }` ?

hey @breytex,

The origin is by following the HTML standard :) I would suggest writing a custom validate method, so you can always reuse it.

```tsx
const trapSpacesForRequiredFields =  (value) => !!value.trim();

validate: {
  trapSpacesForRequiredFields,
}

validate: trapSpacesForRequiredFields

```

**Comment by gmwill934** [comment]
I am trying the following but it is not working, is there another approach to this?

`validate: (value: string) => !!value.trim() || 'no whitespaces.',`

**Comment by bluebill1049** [comment]
> I am trying the following but it is not working, is there another approach to this?
> 
> `validate: (value: string) => !!value.trim() || 'no whitespaces.',`

do a if and else with some debugging.

**Comment by SimonSelg** [comment]
> If you would have to use `validate` for every time you need to trap spaces, this would make the `required` feature obsolete.
> I actually wrote a wrapper around the hook which injects a `validate: (value) => { return !!value.trim()}` every time I set `required:true` across the entire project. 

I wrote such a wrapper to. It wraps the `formMethods`, `useController` and `Controller`. I'll post the code here in order to save someone who runs into the same problem the effort in the future.

```typescript
import {
  UseFormRegister,
  UseFormReturn,
  Path,
  FieldValues,
  Controller,
  useController,
  ControllerProps,
  FieldPath,
  UseControllerProps,
  UseControllerReturn
} from 'react-hook-form'
import { useCallback } from 'react'

/* This file wraps react-hook-form to consider inputs that only contain whitespaces as empty, in the case were
the input validation is set to "required".
 */

const trapSpacesForRequiredFields = <T>(value: T): true | string =>
  typeof value === 'string'
    ? value.trim().length > 0 || 'error message here'
    : true

type Rules = NonNullable<UseControllerProps['rules']>
type Validation = Pick<Rules, 'required' | 'validate'> | undefined

const injectWhitespaceValidation = <T extends Validation>(rules: T): T => {
  if (!rules?.required) return rules
  if (!rules.validate)
    return {
      ...rules,
      validate: trapSpacesForRequiredFields
    }

  const original =
    typeof rules.validate === 'function'
      ? { default: rules.validate }
      : rules.validate

  return {
    ...rules,
    validate: {
      ...original,
      whitespaces: trapSpacesForRequiredFields
    }
  }
}

type OptionsWithValidation = { rules?: Validation }
const injectValidationIntoOptions = <T extends OptionsWithValidation>(
  options: T
): T => {
  const rules = injectWhitespaceValidation(options.rules)
  return options.rules === rules ? options : { ...options, rules }
}

// wraps the formMethods to add whitespace validation
export const useWrapFormToConsiderWhitespacesAsEmpty = <T>(
  formMethods: UseFormReturn<T>
): UseFormReturn<T> => {
  const { register } = formMethods
  const wrappedRegister: UseFormRegister<T> = useCallback(
    (name, options) => {
      const wrappedOptions = injectWhitespaceValidation(options)
      return register(name, wrappedOptions)
    },
    [register]
  )

  return {
    ...formMethods,
    register: wrappedRegister
  }
}

// wraps the Controller to add whitespace handling
export const WrappedWhitespaceValidatingController = <
  TFieldValues extends FieldValues = FieldValues,
  TName extends Path<TFieldValues> = Path<TFieldValues>
>(
  props: ControllerProps<TFieldValues, TName>
): ReturnType<typeof Controller> => {
  const wrappedProps = injectValidationIntoOptions(props)
  return Controller<TFieldValues, TName>(wrappedProps)
}

// wraps useController to add whitespace handling
export const useWrappedWhitespaceValidatingController = <
  TFieldValues extends FieldValues = FieldValues,
  TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>
>(
  props: UseControllerProps<TFieldValues, TName>
): UseControllerReturn<TFieldValues, TName> => {
  const wrappedProps = injectValidationIntoOptions(props)
  return useController<TFieldValues, TName>(wrappedProps)
}
```

**Comment by SimonSelg** [comment]
@bluebill1049, what do you think about adding a section of "community recipes" (or something similar) somewhere to the project? This code does not need to go into the project itself (since it can be added with this little wrapper), but I think quite a few people could use this. And maybe there is more instances of similar problems/solutions.

**Comment by bluebill1049** [comment]
sounds like a fantastic idea @SimonSelg 👍

**Comment by SimonSelg** [comment]
Cool! Should I open a PR for that or would you prefer to do that @bluebill1049? Anyhow, feel free to include the snippet above in such a section.

**Comment by konradSlazyk** [comment]
I just realized that 

> > If you would have to use `validate` for every time you need to trap spaces, this would make the `required` feature obsolete.
> > I actually wrote a wrapper around the hook which injects a `validate: (value) => { return !!value.trim()}` every time I set `required:true` across the entire project.
> 
> I wrote such a wrapper too. It wraps the return value of `useForm` to not accept fields with white-spaces only as valid, if "required: true" is specified for said field. I'll post the code here in order to save someone who runs into the same problem the effort in the future.
> 
> Usage:
> 
> ```ts
> // somewhere in your component
> const methodsOriginal = useForm<FormValues>()
> const methods = useWrapFormToConsiderWhitespacesAsEmpty(methodsOriginal)
> ```
> 
> It works for all three APIs which can be used to register form fields: `useControler`, `Controller` and `register`.
> 
> Implementation of the `useWrapFormToConsiderWhitespacesAsEmpty` hook:
> 
> ```ts
> import { UseFormRegister, UseFormReturn } from 'react-hook-form'
> import { useCallback, useMemo } from 'react'
> 
> const validateNotWhitespaceOnly = <T>(value: T): true | string =>
>   typeof value === 'string'
>     ? value.trim().length > 0 || 'error message here'
>     : true
> 
> /* this hook wraps the return value of react-hook-form's useForm to
> consider inputs that only contain whitespaces as empty, in the case where
> the input validation is set to "required".
>  */
> export const useWrapFormToConsiderWhitespacesAsEmpty = <T>(
>   formMethods: UseFormReturn<T>
> ): UseFormReturn<T> => {
>   const { register } = formMethods
>   const wrappedRegister: UseFormRegister<T> = useCallback(
>     (name, options) => {
>       // we only need to inject the whitespace validation if options.required = true
>       if (!options || !options.required) return register(name, options)
> 
>       // inject whitespace validation into the rules
>       const originalValidationRules =
>         typeof options.validate === 'function'
>           ? { default: options.validate }
>           : options.validate
> 
>       const wrappedOptions = {
>         ...options,
>         validate: {
>           ...originalValidationRules,
>           whitespaces: validateNotWhitespaceOnly
>         }
>       }
>       return register(name, wrappedOptions)
>     },
>     [register]
>   )
> 
>   // register is inside control too, we need to add our wrapped version there in
>   // order to make sure Controller and useController work correctly. Avoid to create
>   // a new object every time by using useMemo
>   const control = useMemo(
>     () => ({
>       ...formMethods.control,
>       register: wrappedRegister
>     }),
>     [formMethods.control, wrappedRegister]
>   )
> 
>   return {
>     ...formMethods,
>     register: wrappedRegister,
>     control
>   }
> }
> ```
> 
> Tests for the `useWrapFormToConsiderWhitespacesAsEmpty` hook
> Here are tests for the useWrapFormToConsiderWhitespacesAsEmpty hook:
> 
> ```ts
> import React from 'react'
> 
> import {
>   useForm,
>   Controller,
>   useController,
>   UseFormReturn
> } from 'react-hook-form'
> import { fireEvent, render } from '@testing-library/react'
> 
> import { useWrapFormToConsiderWhitespacesAsEmpty } from './form'
> 
> const VALIDATION_ERROR = 'Validation Error'
> type FormValues = {
>   demo: string
> }
> 
> // extracted into a hook to avoid code duplication, using this inside a hook is not needed for the functionality
> const useTestForm = (): UseFormReturn<FormValues> => {
>   const methods = useForm<FormValues>({
>     mode: 'onChange',
>     defaultValues: { demo: '' }
>   })
>   return useWrapFormToConsiderWhitespacesAsEmpty(methods)
> }
> 
> /* we need to verify that the wrapper behaves correctly for all three ways of
>  * registering a field. We do that by defining one test component for each API.
>  * We then run the tests on all three components */
> 
> // common interface for all test components
> type TestForm = React.FunctionComponent<{
>   required: boolean
> }>
> 
> // a form which wires up its input with the "require" api
> const TestFormRegister: TestForm = ({ required }) => {
>   const methods = useTestForm()
>   return (
>     <form>
>       <input {...methods.register('demo', { required })} />
>       {methods.formState.errors.demo && <p>{VALIDATION_ERROR}</p>}
>     </form>
>   )
> }
> 
> // a form which wires up its input with the "Controller" api
> const TestFormController: TestForm = ({ required }) => {
>   const methods = useTestForm()
>   return (
>     <form>
>       <Controller
>         name="demo"
>         control={methods.control}
>         rules={{ required }}
>         render={({ field, fieldState }) => (
>           <>
>             <input {...field} />
>             {fieldState.error && <p>{VALIDATION_ERROR}</p>}
>           </>
>         )}
>       />
>     </form>
>   )
> }
> 
> // a form which wires up its input with the "useController" api
> const TestFormUseController: TestForm = ({ required }) => {
>   const methods = useTestForm()
>   const { field, fieldState } = useController({
>     name: 'demo',
>     rules: { required },
>     control: methods.control
>   })
>   return (
>     <form>
>       <input {...field} />
>       {fieldState.error && <p>{VALIDATION_ERROR}</p>}
>     </form>
>   )
> }
> 
> describe('whitespace-aware react-hook-form wrapper', () => {
>   const table: Array<[string, TestForm]> = [
>     ['register', TestFormRegister],
>     ['Controller', TestFormController],
>     ['useController', TestFormUseController]
>   ]
> 
>   it.each(table)(
>     'accepts whitespaces for "required: false" when using "%s" api',
>     // eslint-disable-next-line @typescript-eslint/naming-convention
>     (_, Component) => {
>       const result = render(<Component required={false} />)
>       const input = result.getByRole('textbox')
>       fireEvent.change(input, { target: { value: ' ' } })
>       expect(result.queryByText(VALIDATION_ERROR)).not.toBeInTheDocument()
>     }
>   )
>   it.each(table)(
>     'rejects whitespaces for "required: true" when using "%s" api',
>     // eslint-disable-next-line @typescript-eslint/naming-convention
>     async (_, Component) => {
>       const result = render(<Component required={true} />)
>       const input = result.getByRole('textbox')
>       fireEvent.change(input, { target: { value: '\t ' } })
>       await waitFor(() => undefined)
>       expect(result.getByText(VALIDATION_ERROR)).toBeInTheDocument()
>     }
>   )
> })
> ```
> 
> Edit: Now simplified and even shorted.

Hey, I've noticed something fishy in the solution. After implementing your code in my project I thought everything works correct. It properly detects all whitespaces, react hook form also register fields correctly but when I used mui select component with the help of Controller ---> render, I've noticed there is no visual change in all elements that use Controller approach. Values are properly registered by react hook form but i couldn't see the change. I started investigating the problem and noticed that cloning the object by using spread operator or `Object.assign` doesn't copy all getters and setters of source object. There is a new feature in ECMAScript 2017 that allows you to copy objects with information for all properties of the given object including the information about getters and setters.

`Object.getOwnPropertyDescriptors()`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptors

After testing a bit I came up with this improved solution:

```
const newFormMethods = useMemo(() => {
    const fullCopyObj = Object.defineProperties(
      formMethods,
      Object.getOwnPropertyDescriptors({ register: wrappedRegister }),
    )

    Object.defineProperties(
      fullCopyObj.control,
      Object.getOwnPropertyDescriptors({ register: wrappedRegister }),
    )
    return fullCopyObj
  }, [wrappedRegister, formMethods])
```

**Comment by andylacko** [comment]
## This is super simple solution with 🪄 lodash magic

Create your own strategy, where to put this code, I have component `From`, and it is used in every form. This is invoked before submit

```typescript
import { cloneDeepWith } from 'lodash-es'
```

...code continues...

```typescript
  // inside Form.tsx component
  
  const preSubmit = (formValues: object) => {
    // scrollToErrors()
    const trimmedFormValues = cloneDeepWith(formValues, p =>
      typeof p === 'string' ? p.trim() : undefined
    )
    onSubmit(trimmedFormValues)
  }
```

don't forget to add something like this to your form component 

```jsx
<form {...props} onSubmit={formHook.handleSubmit(preSubmit)} />
```
<br /><br />


### FREE scrollToErrors() function

Also shipping for FREE 💸 this scroll to error function, use your own for error class selector, I am using MUI, you can see there

```javascript
export default (): void => {
  setTimeout(
    () =>
      document.querySelector('.Mui-error')?.scrollIntoView({ behavior: 'smooth', block: 'center' }),
    0
  )
}

```
