### ISSUE TITLE
Settting state in useEffect sets formstate.isvalid to false

### ISSUE THREAD

**Issue by kancharla-sandeep** [react-hook-form/react-hook-form#1652]
I have the created a form with contolled inputs. Setting state in useEffect causes formstate.isvalid to false. I have the following code:

  `
const LoginFormForm = (props) => {

const [state,setState]=useState(false)

   useEffect(()=>{
    setState(true)
},[])

    const { handleSubmit, errors, control, formState } = useForm({
        defaultValues: { email: "xxxx@yyy.in", password: "xxxxxxxx" },
        mode: "onChange"
    });

    return (
        <div className="LoginForm__main-container">
            <form
                className="LoginForm__form"
                noValidate
                onSubmit={handleSubmit(props.onSubmit)}
            >
                <div className="LoginForm__form-group">
                    <CustomInput
                        id="email"
                        data-testid="email"
                        label={t("emailAddress")}
                        name="email"
                        errors={errors}
                        autoFocus
                        InputProps={{
                            className: "input"
                        }}
                        control={control}
                        rules={{
                            required: "emailRequired",
                            pattern: {
                                value: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
                                message: 'validEmailtxt',
                            },
                        }}
                    />
                </div>
                <div className="LoginForm__form-group">
                    <CustomInput
                        id="password"
                        name="password"
                        label={t("password")}
                        type={!state.showPassword ? "password" : "text"}
                        data-testid="password"
                        errors={errors}
                        autoComplete="current-password"
                        control={control}
                        onCopy={e => { e.preventDefault() }}
                        onPaste={e => { e.preventDefault() }}
                        rules={{
                            required: 'passwordIsRequired',
                        }}
                        InputProps={{
                            endAdornment: (
                                <InputAdornment position="end">
                                    <IconButton
                                    >
                                    </IconButton>
                                </InputAdornment>
                            ),
                            className: "input"
                        }}
                    />
                </div>
            </form>
            <div className="LoginForm__remember_forot_sec">
                <FormControlLabel
                    control={
                        <Checkbox
                            checked={state.checked}
                            data-testid="remember-me"
                            inputProps={{ 'data-testid': `remember-me` }}
                            onChange={props.handleChangeRember}
                            name="checkedA"
                        />
                    }
                    label={t("rememberMe")}
                />
                <Button
                    data-testid="handle-forgot-password"
                    onClick={props.handleForgotPassword}
                    className="LoginForm__link-lables"
                >
                    {t("forgotPassword")}
                </Button>
            </div>
            <Button
                type="submit"
                className="LoginForm__btn_submit"
                id="sign-in-btn"
                data-testid="sign-in-btn"
                disabled={!formState.isValid}
            >
                {t("signIn")}
            </Button>
        </div>
    );
};
export default LoginFormForm;
`

Note: commenting setstate in useEffect does not set formstate.isvalid to false

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#formState

**Important: formState is wrapped with Proxy to improve render performance, so make sure you invoke or read it before render in order to enable the state update. This reduces re-render feature only applies to the Web platform due to a lack of support on Proxy at React Native.**

**Comment by eduludi** [comment]
@bluebill1049 I read that in the docs, what does that exactly mean? Can be used in React Native?

**Comment by bluebill1049** [comment]
You can use `formState` in Web/React Native. We are using `Proxy` to optimize re-render, so if you are not reading `isValid` then we are skipping all the validation logic and potential unnecessary re-render which will occur. For RN you will need a Proxy polyfill to enable this feature.

**Comment by eduludi** [comment]
@bluebill1049 Ok. Thanks!

**Comment by eduludi** [comment]
How to add Proxy support to React Native: https://github.com/react-hook-form/react-hook-form/issues/1379#issuecomment-613170952
