### ISSUE TITLE
Add context method to trigger submission

### ISSUE THREAD

**Issue by amsul** [react-hook-form/react-hook-form#1655]
**Is your feature request related to a problem? Please describe.**
Currently, there's no way to submit the form, other than using a button with `type=submit` triggering the form's submit event handler.

This prevents us from being able to programmatically submit a form when a fixed length field is filled out.

**Describe the solution you'd like**
It would be convenient to have a `triggerSubmit` method in the form context (similar to the `triggerValidation` method).

My current workaround is to do something like this:

```tsx
const triggerSubmit = handleSubmit(onSubmit)

return (
  <TriggerSubmitProvider value={triggerSubmit}>
    <form onSubmit={triggerSubmit}>{children}</form>
  </TriggerSubmitProvider>
)
```

**Comment by bluebill1049** [comment]
handleSubmit(onSumbit)()

you can even use `handleSubmit` on a button as well.

**Comment by amsul** [comment]
I understand that we can do this. The concern I'm laying out here is that deeply nested components will not have access to `onSubmit` unless we manually pass it in a new context value.

**Comment by amsul** [comment]
It would be useful to be able to do this:

```tsx
const { triggerSubmit } = useFormContext()
```

**Comment by bluebill1049** [comment]
```
const { handleSubmit } = useFormContext()
handleSubmit(onSubmit)()
```

will do, and we don't have plan to introduce more API.

**Comment by ericbiewener** [comment]
I agree with @amsul -- the ability to conveniently trigger a submission would be a nice addition. I am therefore providing my own form context in order to augment the values provided by `useFormContext()` with `triggerSubmit: () => handleSubmit(onSubmit)()`
