### ISSUE TITLE
Add multi-step/wizard form example to Examples

### ISSUE THREAD

**Issue by dandv** [react-hook-form/react-hook-form#1657]
I saw [the multi-step video](https://react-hook-form.com/advanced-usage#WizardFormFunnel) and it's gret!

Would be nice to add [that example](https://codesandbox.io/s/form-wizard-pages-kkg7m) to the [list of examples](https://github.com/react-hook-form/react-hook-form/tree/master/examples#examples).

PS: congrats on 1000 closed issues! :tada: :confetti_ball: 

![image](https://user-images.githubusercontent.com/33569/82397940-731d4200-9a06-11ea-9ea9-c239202d462e.png)

**Comment by bluebill1049** [comment]
Thanks, @dandv that's a great suggestion. will do!

**Comment by dandv** [comment]
Thanks! BTW there's a small typo in the codesandbox in Step1 and Step2, "onSubit".

**Comment by bluebill1049** [comment]
oh thanks will sort it out.
