### ISSUE TITLE
register(e, opts) does not allowed by TS types, although it works.

### ISSUE THREAD

**Issue by astj** [react-hook-form/react-hook-form#1659]
**Describe the bug**
As described in FAQ (https://react-hook-form.com/faqs#Howtosharerefusage), react-hook-form accepts following form of `register`.

```jsx
      <input name="lastName" ref={(e) => {
        // register's first argument is ref, and second is validation rules
        register(e, { required: true })
      }} />
```

Yes this works fine with js, but Type declaration of `register` does not allow this form.

**To Reproduce**
Confirm JS works by following:
1. Open the sandbox (JS Version)
2. Submit
3. Validation failed due to LastName is empty
4. Input some short text (like "me") in LastName
5. Submit
6. Validation passes and see submitted values in Console log

Confirm TS compilation fails, though it works by following:
1. Open the sandbox (TS Version)
2. See TS compilation failing at L24
3. Submit
4. Validation failed due to LastName is empty
5. Input some short text (like "me") in LastName
6. Submit
7. Validation passes and see submitted values in Console log

**Codesandbox link (Required)**

JavaScript version: https://codesandbox.io/s/react-hook-form-register-82npi?file=/src/index.js
TypeScript version: https://codesandbox.io/s/react-hook-form-register-with-typescript-pm3zv?file=/src/index.tsx

**Expected behavior**
TS compiler does not emit compile error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser Safari
 - Version 13.1

**Additional context**
- Confirmed with following versions of react-hook-form:
  - 5.7.2, 5.6.0: fails
  - 5.0.2, 5.1.0, 5.3.0, 5.5.0: passes
- maybe this is due to #1487

**Comment by bluebill1049** [comment]
here you go:

https://codesandbox.io/s/react-hook-form-register-with-typescript-mh464?file=/src/index.tsx

**Comment by astj** [comment]
Thank you for very quick response!

Yes the suggested change makes typecheck pass, but actually `ref` callback will be invoked both with Element and `null`. (with Element on mount, with `null` on unmount). So the callback function should accept both `Element` and `null` as the argument `e` . (And in some cases, someone might want to include some cleanup code in that `ref` callback.)

Therefore I don't want to downcast `e` as `HTMLInputElement`, and want `register` to accept `register(e: Element | null, validationOptions: ValidationOptions)`.  I'm happy if those circumstances are considered.

Note that I'm changing our production code to use `e => { register({ ... })(e) }` as alternative, so this question does not affect our project updating from 5.0.2 to latest.

**Comment by bluebill1049** [comment]
@kotarella1110 do you have any object change the following:

```
function register<TFieldElement extends FieldElement<TFieldValues>>(
    ref: (TFieldElement | null), // with null
    validationOptions?: ValidationOptions,
  ): void;
```

**Comment by bluebill1049** [comment]
actually no, we do need the first argument to be not `null`. That's where we getting the input `name`, so yes `e => { register({ ... })(e) }` is valid alternative usage. I am going to close this issue.

**Comment by astj** [comment]
Understand. Thank you for kind answer!

**Comment by kotarella1110** [comment]
> @kotarella1110 do you have any objection with the following change:
> 
> ```
> function register<TFieldElement extends FieldElement<TFieldValues>>(
>     ref: (TFieldElement | null), // with null
>     validationOptions?: ValidationOptions,
>   ): void;
> ```

@bluebill1049 no objection! we should fix this.

**Comment by bluebill1049** [comment]
actually `register(null, {})` will do nothing at the function level, but type level we can accept that @kotarella1110 any thoughts?

**Comment by kotarella1110** [comment]
yes. it will don nothing. we should accept `null` for type.
If it is `null`, it should be unregister, but since it is unregistered by mutationWatcher, I think that we don't need to do nothing.

**Comment by bluebill1049** [comment]
sounds good to me @kotarella1110.
