### ISSUE TITLE
How to reference errors when i'm programatically are rendering components

### ISSUE THREAD

**Issue by Jsramosra** [react-hook-form/react-hook-form#1662]
I got a code like this
```
const ExampleForm= ({ data,}) => { 
const { handleSubmit, register, reset, errors, control} = useForm();
return (

    <form onSubmit={handleSubmit(onSubmit)} className={classes.root}>
       <IterateFormData datos={data} regis={register} err={errors} control={control}/>
 </form>

  );
};
```

That renders inputs depending of the data that i'm recieving from props. and im using nombreVariable as the input name, but when i'm referencing the name of the input to validate errors i'm not getting anything at all, the register is working.

```
const IterateFormData = ({ datos, regis, err, control }) => {
 let tamanio = data.length > 4? 3 : data.length === 3? 4 : data.length === 2? 6 : 3
  
  for (let i = 0; i < data.length; i++) {
    let info = [];
    let nombreVariable = `${data[i].nombreAtributo}-${data[i].idAtributo}`;

    if (data[i].predefinido === "t") {
 info.push(
            <Grid item xs={tamanio}>
              <TextField
                variant="outlined"
                error={err.nombreVariable? true : false}
                color="secondary"
                type="date"
                name={nombreVariable}
                label={`${data[i].nombreAtributo}*`}
                inputRef={regis({required: true})}
                helperText={err.nombreVariable && "Campo requerido"}
                InputLabelProps={{
                  shrink: true,
                }}
              />
            </Grid>
          );
}
```

I'm correctly doing the reference of the errors or there is another way to achieve this?

**Comment by bluebill1049** [comment]
sounds like you are doing `useFieldArray`? have you looked at that.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#useFieldArray

**Comment by Jsramosra** [comment]
No, I haven't, let me check.
I see. There's one thing that I don't get at all, if the data I'm iterating is on props, how do I make the `useFieldArray` Fields reference my props array, and besides the change in the `ref={register()}` I'll still use the errors from the `useForm()` by the reference of control?

**Comment by bluebill1049** [comment]
for updated the entire field array, you can use `reset` API.

**Comment by Jsramosra** [comment]
No, no, I didn't mean that hahaha. 
I meant that I saw that `useFieldArray` has a property `Fields` that's is the one in the example that is doing the map function, if the data I need to iterate is the one that I received from props, is there a way to use my data.

Maybe I don't get how that `Fields` property works.

**Comment by Jsramosra** [comment]
Forget what I just said, I got it now.
I don't think that might work for my case, from my server request I'm bringing to my data to the component that is the one that I'm iterating and therefore validating the type of the input in the first render.

I controlled some inputs like `select` that material-ui doesn't provide support for the `inputRef` property. And in the `IterateFormData` as a component I'm passing the register, the errors and the control to save them in the `useForm`  someway, the `register` is working, if it is required it don't allow me to submit the form, but when the input is trying to validate the `errors` property there's no change or message displayed.

**Comment by bluebill1049** [comment]
> I controlled some inputs like select that material-ui doesn't provide support for the inputRef property.

use Controller. https://react-hook-form.com/api#Controller

**Comment by Jsramosra** [comment]
Yup, that's what I did with that components

**Comment by bluebill1049** [comment]
Do you have a simple CSB i can take a look? keep it simple and don't just dumb the entire code.

**Comment by Jsramosra** [comment]
[https://codesandbox.io/s/friendly-lake-ukdeh](url)  here

**Comment by bluebill1049** [comment]
wrong link.

**Comment by Jsramosra** [comment]
Try again https://codesandbox.io/s/friendly-lake-ukdeh?file=/src/App.js

**Comment by bluebill1049** [comment]
again it's broken CSB.

**Comment by Jsramosra** [comment]
This will do, sorry.
https://codesandbox.io/s/friendly-lake-ukdeh?file=/src/App.js

**Comment by bluebill1049** [comment]
i see what you try to do here now, you want to build a generator for a form base on a config?

**Comment by Jsramosra** [comment]
Yes, kinda, the data is my "configuration" to build the form.

**Comment by bluebill1049** [comment]
you want to take a look at this repo? https://github.com/vtex/react-hook-form-jsonschema

**Comment by Jsramosra** [comment]
Yes, i think it might do the work, thank you.
Is there a way to validate required of the inputs when onsubmit like when we do it with useForm()?

**Comment by bluebill1049** [comment]
> Is there a way to validate required of the inputs when onsubmit like when we do it with useForm()?

i don't get the question.

**Comment by Jsramosra** [comment]
By validate i mean like `ref={register({required:true})`  and verify if is there any `errors` on some input.

**Comment by bluebill1049** [comment]
`ref={register({required:true})` only check if the field is empty. it related to `errors` object only after the input failed validation.

**Comment by Jsramosra** [comment]
I solve it at the end by handling the errors as an array, so inside my loop where i create my fields i just reference them by errors[inputName], and a MUI native select do the work pretty well.

**Comment by bluebill1049** [comment]
awesome @Jsramosra please share some code snippet if you can, this will help others.

**Comment by Jsramosra** [comment]
https://codesandbox.io/s/react-hook-form-mui-iterate-json-properties-jm0zi?file=/src/App.js 
This is a little code example, hope i get into the point c:
