### ISSUE TITLE
Masked input does not work when using watch from useForm hook

### ISSUE THREAD

**Issue by mitchconquer** [react-hook-form/react-hook-form#1664]
**Describe the bug**
When using the `watch` method from the `useForm` hook, masked inputs no longer seem to function.

**To Reproduce**
Please see this [code sandbox](https://codesandbox.io/s/empty-tree-cfl8t?file=/src/App.js) for an example.

Try typing in the input in the preview and the masked input works as expected.

1. Start from the [Custom Masked Input](https://codesandbox.io/s/trusting-agnesi-rdi5m)
2. Grab the `watch` from the useForm hook
3. Call watch and do something with the output

Note: There is a strange behavior in CodeSandbox and I'm not sure it's related. If you make a change to the code, for example below, the input starts working (until you hit the "refresh" button on the preview browser. Then it no longer works. That may be related to codesandbox.io, I'm not sure.

```javascript
const values = watch("maskedInputTel");

// edit the above line to look like this and the input in the preview browser works again as long as you don't refresh
const values = watch();
```

**Codesandbox link (Required)**
👉 [codesandbox example](https://codesandbox.io/s/empty-tree-cfl8t?file=/src/App.js)

**Expected behavior**
I would expect the masked input to work even if I am using watch. 

**Screenshots**
Demo of the issue

![react-hook-form-issue](https://user-images.githubusercontent.com/7675922/82520713-aa105800-9ad9-11ea-915e-3f679dbb6cff.gif)

**Desktop (please complete the following information):**
 - OS: OSX Catalina 10.15.4 (19E287)
 - Browser: Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**Additional context**
Perhaps I am using watch wrong? I am trying to get the form values as they are filled out so that I can update the form completion progress for the user.

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report. I would use Controller for masking input if you want to watch its value. 

Take a look at this CSB: https://codesandbox.io/s/react-hook-form-controller-pghi8?file=/src/index.js

**Comment by mitchconquer** [comment]
Thanks I'll give it a try! 🙏
