### ISSUE TITLE
Add some tests to ensure number of renders

### ISSUE THREAD

**Issue by stramel** [react-hook-form/react-hook-form#167]
One of the big things we are claiming is limiting the number of renders that we are triggering. It would be good to add some tests around this so that we don't accidentally break this in the future. 

I think we could use something like this to achieve this kind of testing. https://github.com/bvaughn/jest-react-profiler

**Comment by barrymay** [comment]
Sounds great - we should always keep in mind the occasional re-render for good reason is not a big deal, but I totally agree it's something you want to monitor.

**Comment by stramel** [comment]
Relates to #26

**Comment by bluebill1049** [comment]
yea I am going to working on that :) this one is on my todo list first https://github.com/react-hook-form/react-hook-form/issues/205

**Comment by stramel** [comment]
No worries! Just going through the issues. Wish I had time to write these right now.

**Comment by bluebill1049** [comment]
@stramel it's actually difficult to write test with `jest-react-profiler` :( because useForm trigger re-render external. I tried a couple examples without luck, you want to take a quite a look and see what you can get out of it and then I can continue the work.

**Comment by bluebill1049** [comment]
instead of jest-react-profiler, I have used automation to capture the re-render counts. you can run

`yarn start:app` and `yarn cypress:open` to see the number re-render to be matched.
