### ISSUE TITLE
[Feature Request] v6 It would be nice to use resolver and register validation rule together.

### ISSUE THREAD

**Issue by xiaoyu-tamu** [react-hook-form/react-hook-form#1674]
**Is your feature request related to a problem? Please describe.**

It would be nice to use resolver and register validation rule together.

My use case will be use `resolver` to validate array field is not empty and do async validation, and use `register rules` to validate required, min, max etc. 

**Describe the solution you'd like**

```ts
 const form = useForm<FormValues>({
    resolver: async (data) => {
      if (!data.items || data.items.length === 0) {
        const items: {}[] = [];
        items[-1] = { type: 'required', message: 'At least one product should selected.' };
        return {
          values: {},
          errors: { items: items },
        };
      }
      return { values: {}, errors: {} };
    },
  });


<div>
        <ErrorMessage
          name="items[-1]"
          as={<div />}
          errors={control.errorsRef.current || {}}
        />

        {itemsFieldArray.fields.map((field, index) => (
           // Field just a wrapper around Controller
            <Field
              required
              min={0}
              name={`items[${index}].qty`}
              control={control}
            />
        ))}
</div>
```

**Describe alternatives you've considered**

Currently, I did array validation in handleSubmit callback.

**Additional context**
BTW, I really like the useWatch hook introduced in v6

**Comment by bluebill1049** [comment]
Thanks @xiaoyu-tamu This was been considered and investigated, but it difficult to implement and decided to keep as it is.
