### ISSUE TITLE
MUI Checkbox and Switch within Controller don't work as expected without default values.

### ISSUE THREAD

**Issue by mradenovic** [react-hook-form/react-hook-form#1675]
**Describe the bug**
If a default value is not provided for MUI Checkbox or Switch, the component will return empty string as value on submit.

**To Reproduce**
1. Go to [sandbox example](https://codesandbox.io/s/react-hook-form-controller-d76q8)
2. Click on `Submit`
```console
{}
```
3. Check the checkbox and the switch and click on `Submit` again.
```console
{
  "Checkbox": "",
  "switch": ""
}
```
4. Uncoment `defaultValues` (lines 25-27).
```js
const defaultValues = {
  TextField: "",
  Checkbox: false,
  switch: false,
};
```
5. repeat step 3.
```console
{
  "Checkbox": true,
  "TextField": "",
  "switch": true
}
```

**Codesandbox link (Required)**
The sandbox example is a stripped down version of  [example](https://codesandbox.io/s/react-hook-form-controller-079xx) from [Controlled input](https://react-hook-form.com/get-started#ControlledInput).

https://codesandbox.io/s/react-hook-form-controller-d76q8

**Expected behavior**
Both MUI Checkbox and Switch should return `bool` values even if default values were not set.

**Desktop (please complete the following information):**
 - OS: Chrome OS
 - Browser: Chrome
 - Version: 81

**Comment by bluebill1049** [comment]
This is expected, if no defaultValue is provided, Controller will return `string/boolean` depend on the input type.

**Comment by mradenovic** [comment]
@bluebill1049 I appreciate the quick response. I might have not explained this well. The input type of the component in question is a checkbox. However, both `Checkbox` and `Switch` will return the empty string `""`, no matter what is chosen.

> This is expected, if no defaultValue is provided, Controller will return string/boolean depend on the input type.

I would expect the Controller to return to return a string `"true"` or `"false"` respectively.

```jsx
  <section>
    <label>MUI Checkbox</label>
    <Controller
      as={Checkbox}
      name="Checkbox"
      type="checkbox"
      control={control}
    />
  </section>

  <section>
    <label>MUI TextField</label>
    <Controller as={TextField} name="TextField" control={control} />
  </section>

  <section>
    <label>MUI Switch</label>
    <Controller
      as={Switch}
      type="checkbox"
      name="switch"
      control={control}
    />
  </section>
</div>
```

**Comment by bluebill1049** [comment]
> @bluebill1049 I appreciate the quick response. I might have not explained this well. The input type of the component in question is a checkbox. However, both `Checkbox` and `Switch` will return the empty string `""`, no matter what is chosen.
> 
> > This is expected, if no defaultValue is provided, Controller will return string/boolean depend on the input type.
> 
> I would expect the Controller to return to return a string `"true"` or `"false"` respectively.
> 
> ```js-jsx
>   <section>
>     <label>MUI Checkbox</label>
>     <Controller
>       as={Checkbox}
>       name="Checkbox"
>       type="checkbox"
>       control={control}
>     />
>   </section>
> 
>   <section>
>     <label>MUI TextField</label>
>     <Controller as={TextField} name="TextField" control={control} />
>   </section>
> 
>   <section>
>     <label>MUI Switch</label>
>     <Controller
>       as={Switch}
>       type="checkbox"
>       name="switch"
>       control={control}
>     />
>   </section>
> </div>
> ```

oh I see, you will need to provide a defaultValue as `boolean`, otherwise Controller wouldn't know this is a checkbox or input.

**Comment by bluebill1049** [comment]
we detect if this is a checkbox by the initial value.

**Comment by mradenovic** [comment]
Would it be possible/reasonable to detect if it is a checkbox by type passed to it? I see in examples that type is passed to `Controller`.

**Comment by bluebill1049** [comment]
> Would it be possible/reasonable to detect if it is a checkbox by type passed to it? I see in examples that type is passed to `Controller`.

no, that's the thing. we can't guarantee by type, some of the checkbox (non MIUI) return string...
