### ISSUE TITLE
Support React Fast Refresh

### ISSUE THREAD

**Issue by jizusun** [react-hook-form/react-hook-form#1680]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bluebill1049** [comment]
https://www.youtube.com/watch?v=ZG3xZP0SXYs This youtuber is already using RHF with fast refresh.

**Comment by prsnnami** [comment]
Facing the same issue currently ever since CRA v4. RHF breaks after a hot reload and needs a full page reload to work again. Wasn't sure whether it would be better to comment here or open a new issue. 

Anyways, minimal replication of the issue: [Codesandbox](https://codesandbox.io/s/broken-frog-0x7p6?file=/src/App.js)

**Comment by bluebill1049** [comment]
what are the steps to reproduce @prsnnami ?

**Comment by prsnnami** [comment]
@bluebill1049 I just forked a CRA v4 code sandbox and added RHF and a single input form. That codesandbox link was as minimal as i could get it to be. Listing in Points , the steps in my project on my local device were

1. Start a new CRA app 
2. Add RHF and made a single input form

Works as long as Fast refresh does not trigger. After that a full reload of the page is required. What happens is the the values in the submit handler only returns an empty object.

**Comment by bluebill1049** [comment]
Thanks, @prsnnami I will fix the issue when new inputs are added but will need a refresh when inputs are removed from the component.

**Comment by prsnnami** [comment]
Thanks @bluebill1049 , I'm not sure you got the issue reading your message. Its not necessarily the issue that full refresh is required when an input is added. The behavior I'm getting at is it is currently requiring full refresh when anything is changed and fast refresh is triggered, not just inputs in the form.

**Comment by bluebill1049** [comment]
> Thanks @bluebill1049 , I'm not sure you got the issue reading your message. Its not necessarily the issue that full refresh is required when an input is added. The behavior I'm getting at is it is currently requiring full refresh when anything is changed and fast refresh is triggered, not just inputs in the form.

That will be improved :)

**Comment by ixartz** [comment]
Hi @bluebill1049 thank you for improving this library, it helps me a lot.
I have an issue with the Fast Refresh and it still doesn't work well.
Here is my workflow: I do a fast refresh on my form after changing it but it seems 'isSubmitSuccessful' doesn't work after a fast refresh.

Sorry I didn't have the time to investigate more today, so I don't know if other things also doesn't work. For your information, I'm on the latest version: "react-hook-form": "^6.11.5",

**Comment by ixartz** [comment]
> Hi @bluebill1049 thank you for improving this library, it helps me a lot.
> I have an issue with the Fast Refresh and it still doesn't work well.
> Here is my workflow: I do a fast refresh on my form after changing it but it seems 'isSubmitSuccessful' doesn't work after a fast refresh.
> 
> Sorry I didn't have the time to investigate more today, so I don't know if other things also doesn't work. For your information, I'm on the latest version: "react-hook-form": "^6.11.5",

Sorry it's not isSubmitSuccessful but isSubmitting

**Comment by bluebill1049** [comment]
> Hi @bluebill1049 thank you for improving this library, it helps me a lot.
> I have an issue with the Fast Refresh and it still doesn't work well.
> Here is my workflow: I do a fast refresh on my form after changing it but it seems 'isSubmitSuccessful' doesn't work after a fast refresh.
> 
> Sorry I didn't have the time to investigate more today, so I don't know if other things also doesn't work. For your information, I'm on the latest version: "react-hook-form": "^6.11.5",

can you supply a CSB? I will investigate for a potential solution for a fix.

**Comment by ejose19** [comment]
@bluebill1049 Hello, I also noticed this, it's easily noticeable with ```useFieldArray```, I don't know if CSB already uses fast refresh but the issue is reproducible there, so I guess they do support FR or this is a bigger issue. Here's the [sandbox](https://codesandbox.io/s/magical-pine-x8mw1?file=/src/App.tsx)

To reproduce:
- Toggle checkboxs/change input to notice watch is working as expected
- Change ```CHANGE_ME_FOR_FAST_REFRESH``` value to any other string
- After the "Fast Refresh", toggle checkboxs/change input again and notice watch is no longer working

**Comment by bluebill1049** [comment]
> @bluebill1049 Hello, I also noticed this with `useFieldArray`, I don't know if CSB already uses fast refresh but the issue is reproducible there, so I guess they do support FR or this is a bigger issue. Here's the [sandbox](https://codesandbox.io/s/magical-pine-x8mw1?file=/src/App.tsx)
> 
> To reproduce:
> 
> * Toggle checkboxs/change input to notice watch is working as expected
> * Change `CHANGE_ME_FOR_FAST_REFRESH` value to any other string
> * After the "Fast Refresh", toggle checkboxs/change input again and notice watch is no longer working

Thanks, @ejose19 we can improve this on the dev build: https://codesandbox.io/s/icy-paper-llptf?file=/src/App.tsx

**Comment by ejose19** [comment]
@bluebill1049 I found the issue to appear at [v6.11.1](https://github.com/react-hook-form/react-hook-form/releases/tag/v6.11.1), versions before that works as expected.

**Comment by bluebill1049** [comment]
Thanks @ejose19 can you test if this beta: `react-hook-form@6.12.1-beta.2` fix the issue above?

**Comment by ejose19** [comment]
@bluebill1049 No difference, watch is not triggering after FR.

**Comment by bluebill1049** [comment]
Thanks @ejose19 fixed: https://codesandbox.io/s/icy-paper-llptf?file=/src/App.tsx

**Comment by ejose19** [comment]
@bluebill1049 Yes, that seems to make it work again.

**Comment by ejose19** [comment]
@bluebill1049 Seems the issue is not yet resolved, as it's not behaving correctly. Here's another [sandbox](https://codesandbox.io/s/gallant-keller-d44tc?file=/src/Items.tsx)

Do this to reproduce:
1. Uncheck any item
2. Edit ```CHANGE_ME``` variable to trigger a FR
3. Notice how the row becomes visible again, but the checkbox is still unselected
4. If you change any form value, ```watch``` output becomes correct again

Notes:
-  ```watch``` is returning ```defaultValues``` after FR
- ```useWatch``` preserves the values before the FR, but doesn't trigger anymore after FR
- ```getValues``` is reporting an empty object after FR, so the real issue is affecting multiple methods (and the root issue is probably the one causing ```watch``` to resort to ```defaultValues```

**Comment by bluebill1049** [comment]
> @bluebill1049 Seems the issue is not yet resolved, as it's not behaving correctly. Here's another [sandbox](https://codesandbox.io/s/gallant-keller-d44tc?file=/src/Items.tsx)
> 
> Do this to reproduce:
> 
> 1. Uncheck any item
> 2. Edit `CHANGE_ME` variable to trigger a FR
> 3. Notice how the row becomes visible again, but the checkbox is still unselected
> 4. If you change any form value, `watch` output becomes correct again
> 
> Notes:
> 
> * `watch` is returning `defaultValues` after FR
> * `useWatch` preserves the values before the FR, but doesn't trigger anymore after FR
> * `getValues` is reporting an empty object after FR, so the real issue is affecting multiple methods (and the root issue is probably the one causing `watch` to resort to `defaultValues`

Does this fix the issue? https://codesandbox.io/s/distracted-lewin-prqrn?file=/src/Items.tsx

**Comment by ejose19** [comment]
@bluebill1049 Yes, looks like that version has all the points covered.

**Comment by bluebill1049** [comment]
> @bluebill1049 Yes, looks like that version has all the points covered.

Thanks, i will patch this in the next release.

**Comment by ixartz** [comment]
@bluebill1049 Thank for your fix and sorry for this late response.

The issue is still doesn't work for isSubmitSuccessful, submitCount, errors.exampleRequired, isSubmitting, etc. maybe more are affected.

Here is the code: https://codesandbox.io/s/bold-surf-jm8vu?file=/src/App.tsx

Before a fast refresh, isSubmitSuccessful, submitCount, errors.exampleRequired, isSubmitting are in correct state.
For example, for submitCount, each time I click on submit, the counter increase correctly.

But after a fast refresh, the submitCount variable doesn't change anymore.

**Comment by bluebill1049** [comment]
> @bluebill1049 Thank for your fix and sorry for this late response.
> 
> The issue is still doesn't work for isSubmitSuccessful, submitCount, errors.exampleRequired, isSubmitting, etc. maybe more are affected.
> 
> Here is the code: https://codesandbox.io/s/bold-surf-jm8vu?file=/src/App.tsx
> 
> Before a fast refresh, isSubmitSuccessful, submitCount, errors.exampleRequired, isSubmitting are in correct state.
> For example, for submitCount, each time I click on submit, the counter increase correctly.
> 
> But after a fast refresh, the submitCount variable doesn't change anymore.

can you try with the latest? works for me here.

**Comment by ixartz** [comment]
Hi @bluebill1049 , I confirm it works on codesanbox. But, when I've tested on Next JS, it doesn't work as expected. You can find a empty project with only react hook form at this location: https://github.com/ixartz/next-js-react-hook-form-fast-refresh and I'm using the latest version: https://github.com/ixartz/next-js-react-hook-form-fast-refresh/blob/main/package.json#L14

Here is where you can find the example file: https://github.com/ixartz/next-js-react-hook-form-fast-refresh/blob/main/pages/index.tsx#L9

I confirm it definitively works better than before.
Before your patch,  `onSubmit` wasn't triggered after a fast refresh.

**Comment by Cerberus** [comment]
My component does not re-render when try to typing after save.

This is my workaround by creating a custom function.

```ts
// at src/module/form/index.ts
import * as ReactHookForm from 'react-hook-form'

export * from 'react-hook-form'

// @ts-ignore override watch type
export const useForm: typeof ReactHookForm.useForm = (param) => {
  const form = ReactHookForm.useForm(param)
  const { control } = form
  useCustomWatch = (name: string | string[]) =>
    // @ts-ignore props type Mismatched
    ReactHookForm.useWatch({ control, name })
  // @ts-ignore override watch type
  return { ...form, watch: useCustomWatch }
}
```
Then change module path.
```ts
// from this
import { Controller, useForm } from 'react-form-hook'
// to this
import { Controller, useForm } from 'modules/form'
```

And now it work like a charm 🎉 

The new `useForm` is perfect compatible. Nothing changed for parameters.

Hope it helps you : )

info: `"react-hook-form": "^6.14.1", "react-refresh": "0.9.0"`

**Comment by bluebill1049** [comment]
Thanks' everyone's for input. we are improving that in v7 and it will get resolved soon.
