### ISSUE TITLE
watch() doesn't work with React Fast Refresh

### ISSUE THREAD

**Issue by smably** [react-hook-form/react-hook-form#1683]
**Describe the bug**
`watch()` stops updating after React Fast Refresh page updates. This is particularly noticeable on Next.js projects, which have React Fast Refresh built in since version 9.4.

**To Reproduce**
1. Clone this repo: https://github.com/smably/rhf-fast-refresh-bug
2. Run `yarn && yarn dev`.
3. Type in the text field, notice that the watched value changes below the text input.
4. Make any change to `pages/index.js` and save.
5. Type in the text field, notice that the watched value no longer changes.

**Codesandbox link (Required)**
CodeSandbox support for Next.js apps is not great, so I would recommend cloning the demo repo and trying it locally. Here's a link anyway if you want to try it:
https://codesandbox.io/s/rhf-fast-refresh-bug-zr0cj?file=/pages/index.js

**Expected behavior**
I'd expect that `watch()` would continue to track changes to the text field after a Fast Refresh update.

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Comment by vvo** [comment]
Just want to say: I had issues in Next.js v9.4 too with `dirty` no more updating when JS would be updated in editor. With 55fd8ba872ac3fba44f2d1ffa03024732a1bfb77 and `@next` tag this is now working well, thanks 👍
