### ISSUE TITLE
Yup with RHF validating optional fields even when empty.

### ISSUE THREAD

**Issue by gauravkrp** [react-hook-form/react-hook-form#1691]
**Describe the bug**
I'm using RHF and Yup schema.
I've a form where I've few optional fields (not required). 
Optional Fields should not be validated when empty and **should be validated only when not empty**.
`
const yupSchema = Yup.object().shape({
    firstName: Yup.string()
      .required('Please provide your first name!')
      .min(3, 'Is that a real name?')
      .max(35, 'Your name seems to be too long.'),
    lastName: Yup.string()
      //.min(3, 'Is that a real name?')
      .max(35, 'Your name seems to be too long.'),
    email: Yup.string()
      .required("Please tell us your email.")
      .email("Please enter a valid email."),
})`
Although if I do the following (commenting min in lastName), it works but I don't want users to insert 1 or 2 characters in last name.

`...
    lastName: Yup.string()
      //.min(3, 'Is that a real name?')
      .max(35, 'Your name seems to be too long.'),
    ...`

**To Reproduce**
See the CodeSandBox

**Codesandbox link (Required)**
https://codesandbox.io/s/young-resonance-kvkw3

**Expected behavior**
Optional Fields should not be validated when empty and **should be validated only when not empty**.
I've used [Formik ](https://jaredpalmer.com/formik/docs/overview) before and not faced this issue with formik.

**Screenshots**

![image](https://user-images.githubusercontent.com/12250556/82791409-57dd8700-9e8b-11ea-8d71-f8de701e9d0c.png)

**Desktop (please complete the following information):**
- Nextjs 9.4.2
- RHF 5.7.2
- yup 0.29

**Comment by bluebill1049** [comment]
This is a schema related question, we don't have any magic rather let yup validate the data. please test your schema with unit test and see if anything is wrong. by default RHF will supply an empty string for each input just like native inputs.

**Comment by gauravkrp** [comment]
> This is a schema related question, we don't have any magic rather let yup validate the data. please test your schema with unit test and see if anything is wrong. by default RHF will supply an empty string for each input just like native inputs.

Ya Bill, I ran unit test with my schema and it returned false. Though I still wonder how Formik handled this special case of optional validation. And for the same example, I've put a codesandbox with formik -  https://codesandbox.io/s/fervent-voice-fevr6?file=/src/App.js

**Comment by bluebill1049** [comment]
> Ya Bill, I ran unit test with my schema and it returned false. Though I still wonder how Formik handled this special case of optional validation. And for the same example, I've put a codesandbox with formik - https://codesandbox.io/s/fervent-voice-fevr6?file=/src/App.js

That's not going to be my expert area.

**Comment by bluebill1049** [comment]
However, I do suspect because they may return `undefined/null` for an empty field.

**Comment by gauravkrp** [comment]
@bluebill1049 Please raise this as a feature request for RHF also. 
Optional Fields should not be validated when empty.

**Comment by bluebill1049** [comment]
This is as expected behavior and we have follow HTML standard for default input value since V1 till today. There is no plan to move away from this. 

**Potential Solutions:**

1. adjust your schema to evaluate the empty string.
2. use `Controller` to parse input value: https://github.com/react-hook-form/react-hook-form/blob/master/examples/parseFormatInputValues.tsx

**Comment by gauravkrp** [comment]
> This is as expected behavior and we have follow HTML standard for default input value since V1 till today. There is no plan to move away from this.
> 
> **Potential Solutions:**
> 
> 1. adjust your schema to evaluate the empty string.
> 2. use `Controller` to parse input value: https://github.com/react-hook-form/react-hook-form/blob/master/examples/parseFormatInputValues.tsx

Yes @bluebill1049  Definitely I will adjust my schema for extra validations for empty fields as I am not going back to Formik. RHF is faster, smaller and does very less re-rendering.

**Comment by bluebill1049** [comment]
Thanks for understanding. ❤️ 

Everything moves and changes, HTML standard remain the same. I think by doing so, we are setting us in the long run. Make sure to check out `Controller` (if you haven't): https://react-hook-form.com/api#Controller This will help you from working with external controlled input and parse input's value type.
