### ISSUE TITLE
Set validation mode on a per-element basis

### ISSUE THREAD

**Issue by joejordan** [react-hook-form/react-hook-form#1692]
**Is your feature request related to a problem? Please describe.**
When filling the last field in a form with mode setting 'onBlur', my "Submit" button is disabled until I tab out of the form, so the element after the "Submit" button is selected, and then immediately after the Submit button is enabled, so the user has to shift-tab+enter or click to save the form.

**Describe the solution you'd like**
I would like the option to set the mode option on a per-element basis. So for example on the last field, I could set the mode as onChange after the contents of the field meet a certain criteria. (In my case, the last field is a zipCode, so I would like to start validating onChange once the field reaches 5 characters long).

**Describe alternatives you've considered**
I've considered using mode: 'onChange', but this doesn't facilitate an ideal user experience for the rest of the fields on my form. I think a finer-grained approach would work better.

**Comment by bluebill1049** [comment]
you can use `trigger` with `onChange` at the last item.

**Comment by joejordan** [comment]
> 
> 
> you can use `trigger` with `onChange` at the last item.

Thanks for the tip @bluebill1049 that worked.
