### ISSUE TITLE
validationContext is not working for validation schema

### ISSUE THREAD

**Issue by michal-samluk** [react-hook-form/react-hook-form#1700]
Here's the codesanbox: 
https://codesandbox.io/s/react-hook-form-validationschema-zmifd?file=/src/index.js

It seems that `5.7.2` version should support it, but it does not work. https://github.com/react-hook-form/react-hook-form/blob/v5.7.2/src/logic/validateWithSchema.ts#L79

**Comment by iDuuck** [comment]
You didn't fill out the bug reporting template, however, here is a working CodeSandbox:

https://codesandbox.io/s/react-hook-form-validationschema-7h0m2?file=/src/index.js

The declaration of the context shouldn't include the dollar (`$`) sign. It should be a simple object, which can then be conceived by the `when` method of `yup`. [See an example of this here](https://github.com/jquense/yup#mixedwhenkeys-string--arraystring-builder-object--value-schema-schema-schema).

**Comment by michal-samluk** [comment]
Thank you :)
