### ISSUE TITLE
`type="email"` field triggers browser validation, instead of library validation

### ISSUE THREAD

**Issue by visualcookie** [react-hook-form/react-hook-form#1701]
**Describe the bug**
I experienced an issue with HTML5 types on `<input />` fields, especially `type="email"` is a boomer there, as it triggers the native browser validation message instead of the custom validation set in the `register()`.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-validation-issues-5num5?file=/src/index.js

*(Enter something, that is not an email to the email field and hit the submit button)*

**Expected behavior**
Should trigger the validation from the `register()` and not the native one.

**Screenshots**
How it looks then using `type="email"`:

<img width="560" alt="image" src="https://user-images.githubusercontent.com/1857554/82827267-2e7a2680-9e9e-11ea-918e-86e81a77c000.png">

How it looks without it (this is how it should also look with the `type` applied):

<img width="560" alt="image" src="https://user-images.githubusercontent.com/1857554/82827285-3cc84280-9e9e-11ea-95d4-2cd3942fb763.png">

**Additional context**
Problem happens everywhere, no matter what OS or Browser. I think it's really important to use these types on input fields, because when you visit the website with your Smartphone, your keyboard layout will match the one setup by the type definition.

**Comment by iDuuck** [comment]
As far as I know, there is no possibility to hinder the browser, but with `novalidate` (or the equivalent `noValidate` for React elements).

**Comment by bluebill1049** [comment]
Thanks, @iDuuck that's correct.
