### ISSUE TITLE
 insert method of useFieldArray does not behave as expected

### ISSUE THREAD

**Issue by LoicHa** [react-hook-form/react-hook-form#1702]
**Describe the bug**

I need to clone a line , so i used the insert method with a dynamic index
When i use this button with no change made on the inputs , the insert works perfectly 
However when I edit any input and use this button , the new line does not reflect the good values

I made a codesandbox to reproduce it

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-kht7y?file=/src/index.js
2. Change "Arnold" for "Willis"
3. Click on "clone"
4. See "Arnold", not "Willis" for the added line

**Expected behavior**
Clone with changed made on inputs

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 81.0

**Additional context**

Maybe this is due to a mutating state ?

**Comment by bluebill1049** [comment]
you want to use `getValues()` instead of `item`.

**Comment by LoicHa** [comment]
Sorry @bluebill1049 , i reoppned it since i did not find any solution to fix my issue , i updated the example with the latestversion of react-hook-form (6.11.0) , and eddited the code to use getValues() on a clone function,

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-clb1e?file=/src/index.js

I am maybe dumb and there is something obvious in the code that render this behaviour or some mutation mistake ? , but when i click on clone the wrong line is cloned , it's always the last one who is cloned
