### ISSUE TITLE
errors object typing for File input seems to be invalid

### ISSUE THREAD

**Issue by vatosarmat** [react-hook-form/react-hook-form#1703]
**Describe the bug**
file input error type is not `FieldError` but `NestDataObject<File, FieldError>` so it is impossible to get `message` property
`Property 'message' does not exist on type 'NestDataObject<File, FieldError>'`

**To Reproduce**
Create a form with a file input, pass values type as generic to `useForm`, see error

**Codesandbox link (Required)**
https://codesandbox.io/s/quizzical-bartik-obls5?file=/src/App.tsx

**Comment by bluebill1049** [comment]
I think it's FileList that we return: 

https://codesandbox.io/s/elated-neumann-yfsro?file=/src/App.tsx

FYI: @kotarella1110

**Comment by vatosarmat** [comment]
Thanks for reply and sorry for my unawareness about `FileList`

I would like to crop avatar before actual upload. But `FileList` is immutable, so I can not replace original file with cropped one in `validate`. Then how can I do that?
https://codesandbox.io/s/quizzical-bartik-obls5?file=/src/App.tsx

**Comment by bluebill1049** [comment]
Interesting one, why do you want to crop inside validate function?

**Comment by vatosarmat** [comment]
In `validate` I also validate that file is actually an image and that it has acceptable size. 
There is no `transform` option in `register`, so I guess values transformations assumed to be done in `onChange` and `validate`

**Comment by bluebill1049** [comment]
> Thanks for reply and sorry for my unawareness about `FileList`
> 
> I would like to crop avatar before actual upload. But `FileList` is immutable, so I can not replace original file with cropped one in `validate`. Then how can I do that?
> https://codesandbox.io/s/quizzical-bartik-obls5?file=/src/App.tsx

I am not sure how to manipulate FIleList (not expert on that), maybe ask a question at StackOverflow?

**Comment by vatosarmat** [comment]
Well, I think there is nothing to expert in, `FileList` is  just immutable by design :slightly_smiling_face:
I've managed to achieve my goals using `register({type:'custom'})` But I encountered another issue:  `reset`, which I use to reset text field values, also deletes values of custom registered fields. Isn't it a bug? I guessed it should ignore them or use initial default value, passed to `useForm`
https://codesandbox.io/s/quizzical-bartik-obls5?file=/src/App.tsx

**Comment by bluebill1049** [comment]
can you provide steps to reproduce?

**Comment by vatosarmat** [comment]
Codesandbox -  https://codesandbox.io/s/quizzical-bartik-obls5?file=/src/App.tsx
Custom registered input set to {file: null} in useForm defaultValue
Click reset - {file:null} disappears from getValues()

**Comment by bluebill1049** [comment]
That's expected, it's resetting the entire form with `value` that you provided instead of merging with form values.
