### ISSUE TITLE
V6: Message type requires a cast to string when used on a string only field.

### ISSUE THREAD

**Issue by stramel** [react-hook-form/react-hook-form#1713]
**Describe the bug**
This is more of an annoyance with the typing. This requires all props that you feed `errors.fieldName?.message` into to support both `string` and `ReactElement` or always require a cast to the correct typing.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-s2687?file=/src/index.tsx

**Expected behavior**
Not to have to cast every usage of an error message

**Screenshots**
![image](https://user-images.githubusercontent.com/855184/83059034-e9c9c900-a01e-11ea-9f8f-a120a522e223.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 81

**Comment by bluebill1049** [comment]
@stramel do you have a solution in mind?

**Comment by stramel** [comment]
I don't have a solution in mind. I will try to think of some solutions

**Comment by bdrobinson** [comment]
[The docs for `errors`](https://react-hook-form.com/api#errors) state that it's always a string rather than `string | React.ReactElement`. Which is correct – the docs or the typings? A simple `string` sounds like the correct API to me.

I can see two potential fixes. Either to change https://github.com/react-hook-form/react-hook-form/blob/a5709440eb2e6a908110aea9ed473772ded5686a/src/types/form.ts#L96 to just be `type Message = string`. Or if there are other parts of the API that *do* allow the message to be `string | React.ReactElement`, then to change the typing on `FieldError` (etc) from `message?: Message` to `message?: string` <https://github.com/react-hook-form/react-hook-form/blob/a5709440eb2e6a908110aea9ed473772ded5686a/src/types/form.ts#L131>.

**Comment by kotarella1110** [comment]
document is incorrect.
I supported React.ReactElement as well as string in this PR (https://github.com/react-hook-form/react-hook-form/pull/1275).

**Comment by bluebill1049** [comment]
Do we still have problem with this issue if we already support `string` & `ReactElement`?

**Comment by kotarella1110** [comment]
We still have this problem.
I think there is no solution for this issue.

We need to use cast or typeguard.

```ts
let errorMessage: string;
// cast
errorMessage = errors.fieldName?.message as string;
// typeguard
errorMessage = typeof errors.fieldName?.message === 'string' ? errors.fieldName?.message : '';
```

[TypeScript Playground](https://www.typescriptlang.org/play/#code/CYUwxgNghgTiAEEQBd4CMBc8DOyYEsA7Ac3gB95CBXAWzRBgG4AoJVKLXAklqeAXnQsA9MPhgouZn0Fp4knHiLERY5AE8ADiGJVYwaQPgbtAewBm6Af0EByLstvwA-Fay3bjIA)

**Comment by bluebill1049** [comment]
hey @stramel, do you have any solution in mind?

**Comment by bluebill1049** [comment]
if this is something we can't fix, I will include that in the FAQ section.

**Comment by bluebill1049** [comment]
I guess the only solution is to strictly only allow `string` 🤔 @kotarella1110 @stramel

**Comment by bluebill1049** [comment]
keep things transparent here, we have the following options

1) string only avoid TS issue
2) still support string/jsx and leave note in the FAQ 

@kotarella1110 is investigating a solution for both string and JSX, if there is no solution we will cast a vote to decide.

**Comment by bluebill1049** [comment]
here is the vote on Twitter: https://twitter.com/HookForm/status/1270492651905626112

**Comment by bluebill1049** [comment]
<img width="591" alt="Screen Shot 2020-06-11 at 10 39 15 am" src="https://user-images.githubusercontent.com/10513364/84332253-ce8abc00-abcf-11ea-852a-ba2be156c746.png">

The result indicates people prefer type-safe (TS developers) but there are still quite a lot of users who rely on JSX.

**Comment by bluebill1049** [comment]
The proposal is:

- TS users: strict string (TS users will have to stick with `string`)
- JS users: string / JSX (logic remain in the code to support JSX)

**Comment by stramel** [comment]
Do we need to leave the logic in the code? or can we just treat the value as the message if it isn't `=== true`? Both string and react element should be fine to just pass through.

**Comment by bluebill1049** [comment]
> Both string and react element should be fine to just pass through.

Agree, sorry that was what I meant. we just remove the JSX from type definition and return anything other than boolean.

**Comment by bluebill1049** [comment]
Maybe we should reconsider remove `ErrorMessage` as well because `ErrorMessage` supports JSX and it's confusing. honestly with optional chaining ErrorMessage is so easy to deal with just raw JS.

**Comment by bluebill1049** [comment]
above sync with https://github.com/react-hook-form/react-hook-form/issues/1840

**Comment by sonhanguyen** [comment]
Probably not the right issue but error type should not be predetermined (`any`). I'm having issue right now when I have a validator function that can return/throw an instances of custom error types. React-hook-form kind of expect me to give it a `string` instead. A string is never a good error type in my opinion.

I also don't need a form state management library to know anything about rendering errors, I just need it to pass along the errors, what ever it is. The react component will do the job of interpreting the error to a message including intl support
