### ISSUE TITLE
useEffect handler for [errors] only called on initial render

### ISSUE THREAD

**Issue by TimNZ** [react-hook-form/react-hook-form#1715]
**Describe the bug**
I expect useEffect(() => {}, [errors]) to be called on change of errors content.
It is only called on initial render.

**To Reproduce**

https://codesandbox.io/s/react-hook-form-errors-uzpb5?file=/src/index.js
If I remove [errors] scope on useEffect, it is called on each re-render as expected.
Does the errors object need to be updated differently?

![image](https://user-images.githubusercontent.com/1051701/83077218-13402e80-a0cb-11ea-87e5-da6696aef69e.png)

**Comment by TimNZ** [comment]
Sorry forgot to save my changes on the Codesandbox fork with the console.log

**Comment by bluebill1049** [comment]
Just tested your CSB, it's working, right?

**Comment by TimNZ** [comment]
The CSB code runs - show the Console and you'll see the lack of useEffect console.log as per the screenshot.

**Comment by bluebill1049** [comment]
I can see the console log is updating when errors changing. (if that's what you refer to)

<img width="554" alt="Screen Shot 2020-05-28 at 8 42 33 am" src="https://user-images.githubusercontent.com/10513364/83079442-3533b400-a0bf-11ea-9a08-cf1fede0a761.png">

**Comment by bluebill1049** [comment]
I see what you mean now. we are memorizing the `errors` object. hmmm, maybe it's not a good idea to memorize it, what's your usage like?

**Comment by TimNZ** [comment]
I know this is not an efficient implementation as I re-render the entire form each time errors changes, but this is the code to test against - error for each item should be shown/hidden as appropriate.

```
export default function FastForm(props) {
  const { register, getValues, triggerValidation, errors, handleSubmit } = useForm({mode: props.mode});
  const [renderedItems, setRenderedItems] = useState(props.content.map(item => renderItem(item,0) ))
  function renderItem(item,depth = 0)
  {
    console.log('renderItem',item)
    let itemContent
    switch(item.type)
    {
      case 'input':
        itemContent = <input key={item.id} name={item.name} ref={register(item.register)} {...item.events}/>
        break
      case 'button':
        itemContent = <button key={item.id} type={item.mode}>{item.content}</button>
        break
    }
    return (
      <div>
        {itemContent}
        {errors[item.name] && <div key={`error_${item.id}`} className="error">{errors[item.name].message}</div>}
      </div>
    )
  }
  
  function onSubmit(...args)
  {
  }
  useEffect(() => {
    setRenderedItems(props.content.map(item => renderItem(item,0) ))
  },[errors])
  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      {renderedItems}
    </form>
  );
}

FastForm.defaultProps = {
  mode: 'onChange'
}
```

**Comment by TimNZ** [comment]
I have a renderItem function as I may support nested items

**Comment by bluebill1049** [comment]
> I have a renderItem function as I may support nested items

can you give more detail and context why errors are involved?

**Comment by TimNZ** [comment]
Example usage of FastForm:

```
import React, { useState, useRef } from "react";
import {useApp} from '@/app'
import FastForm from '@/components/Components/Forms/FastForm'
import {validators,sleep} from '@/utils'
import debounce  from 'lodash/debounce'
export default function SignIn(props) {
  const debouncedCheckEmailAvailable = debounce(async email => {
      if (validators.email(email))
      {
          console.log('valid email, doing check')
          await sleep(200)
      }
      else
          console.log('invalid email')

  })
  const checkEmailAvailable = e => {
    debouncedCheckEmailAvailable(e.target.value)
  }

  const FormDefinition = {
    mode: 'onChange',
    content: [
      { id:'email', type: 'input', label: 'email', name: 'email', register: { required: true, validate: v => validators.email(v) || 'not a valid email address'}, 
        events: { onChange: checkEmailAvailable }},
      { id: 'submit', type: 'button', mode: 'submit', content: 'Sign In'}
    ],
    layout: {

    },
    events: {

    }
  }

  return (
    <FastForm {...FormDefinition}/>
    
  )
} 
```

**Comment by bluebill1049** [comment]
> Example usage of FastForm:
> 
> ```
> import React, { useState, useRef } from "react";
> import {useApp} from '@/app'
> import FastForm from '@/components/Components/Forms/FastForm'
> import {validators,sleep} from '@/utils'
> import debounce  from 'lodash/debounce'
> export default function SignIn(props) {
>   const debouncedCheckEmailAvailable = debounce(async email => {
>       if (validators.email(email))
>       {
>           console.log('valid email, doing check')
>           await sleep(200)
>       }
>       else
>           console.log('invalid email')
> 
>   })
>   const checkEmailAvailable = e => {
>     debouncedCheckEmailAvailable(e.target.value)
>   }
> 
>   const FormDefinition = {
>     mode: 'onChange',
>     content: [
>       { id:'email', type: 'input', label: 'email', name: 'email', register: { required: true, validate: v => validators.email(v) || 'not a valid email address'}, 
>         events: { onChange: checkEmailAvailable }},
>       { id: 'submit', type: 'button', mode: 'submit', content: 'Sign In'}
>     ],
>     layout: {
> 
>     },
>     events: {
> 
>     }
>   }
> 
>   return (
>     <FastForm {...FormDefinition}/>
>     
>   )
> } 
> ```

I don't see `errors`?

**Comment by bluebill1049** [comment]
what's FastForm?

**Comment by TimNZ** [comment]
FastForm is the first code snippet - it's the react function using react-hook-form.

The 2nd code snippet is an example consuming the FastForm component.

It's no more complicated than that.

**Comment by bluebill1049** [comment]
shouldn't it be done like this:

```
export default function FastForm(props) {
  const {
    register,
    getValues,
    triggerValidation,
    errors,
    handleSubmit,
  } = useForm({ mode: props.mode });

  function renderItem(item, depth = 0) {
    console.log("renderItem", item);
    let itemContent;
    switch (item.type) {
      case "input":
        itemContent = (
          <input
            key={item.id}
            name={item.name}
            ref={register(item.register)}
            {...item.events}
          />
        );
        break;
      case "button":
        itemContent = (
          <button key={item.id} type={item.mode}>
            {item.content}
          </button>
        );
        break;
    }
    return (
      <div>
        {itemContent}
        {errors[item.name] && (
          <div key={`error_${item.id}`} className="error">
            {errors[item.name].message}
          </div>
        )}
      </div>
    );
  }

  function onSubmit(...args) {}

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      {props.content.map((item) => renderItem(item, 0))}
    </form>
  );
}

FastForm.defaultProps = {
  mode: "onChange",
};
```

**Comment by TimNZ** [comment]
Damn it - that's what I had originally, and it wasn't working, and now it does 😀 .

Most prob lost track of code changes, especially when I fixed 'mode = onChange' prop setting, likely after I was experimenting with useEffect.
Thanks.

Though I still think we need a way to trigger a func when errors change i.e. useEffect,
or a event handler func passed to useForm().

**Comment by TimNZ** [comment]
Ok I'll just close this now, this code works.
Thanks for getting me here.

```
  const { register, formState, getValues, triggerValidation, errors, handleSubmit } = useForm({mode: props.mode});
  const {isValid} = formState
  useEffect(() => {
    console.log('useEffect on isValid',errors)
  },[isValid])
```

**Comment by bluebill1049** [comment]
hey, @TimNZ thanks for your feedback, I think for `errors` object it's better to treat it at the render phase, rather after `useEffect`, I will keep an eye on this one if users encounter a similar issue.
