### ISSUE TITLE
Material UI Autocomplete with React Hook Controller Component cannot select item on first click

### ISSUE THREAD

**Issue by uncvrd** [react-hook-form/react-hook-form#1719]
**Describe the bug**
I am having some issues selecting items from a dropdown when using Material UI's `Autocomplete` component with RHF's `Controller` component. 

The issue I have is when I click on the input to select an item from the dropdown, the first attempt doesn't fill the input with the text I've selected, but the next time I try selecting an option, it works.

Something in the `Controller` component is causing issues because it works as expected when I take the `Autocomplete` out of the `Controller` element. I've noticed that if I `console.log()` inside the `Autocomplete`'s `getOptionSelected()` it logs out all the items when I click on the input, when it shouldn't. I've attached a codesandbox here that shows the broken `Autocomplete` using `Controller`

**To Reproduce**
1. Click on the input "Asynchronous", a dropdown will appear loaded from api
2. Click an option, nothing will show as selected
3. Click the input "Asynchronous" again, dropdown appears
4. Select an option, should work that time 

**Codesandbox link (Required)**
https://codesandbox.io/s/suspicious-bas-26gu3?file=/src/App.tsx

**Expected behavior**
I expect that the `Controller` element should not affect the function of the `Autocomplete`.

If you take out the `Autocomplete` component from the `Controller`, it will work as expected. Any thoughts as to why this is occurring? Thanks so much!

**Gif**
![Demo](https://media.giphy.com/media/dBlb9uxMRAdVIJp822/giphy.gif)

**Comment by bluebill1049** [comment]
please take a look at this example: https://codesandbox.io/s/react-hook-form-controller-079xx

**Comment by uncvrd** [comment]
@bluebill1049 thanks :) ok so I missed the fact that I needed to add `onChange={([, data]) => data}` on the `Controller`. I'll delve in to the source code a bit to see why adding that fixes things.

**Comment by bluebill1049** [comment]
no worries @uncvrd we are planning to introduce `render props` for Controller, so things will be more obvious and clearer.
