### ISSUE TITLE
Set watch in userForm() options

### ISSUE THREAD

**Issue by etc-tiago** [react-hook-form/react-hook-form#1721]
**Is your feature request related to a problem? Please describe.**
I see `watch` as an option that could be triggered as `useForm({watch: ['name'])`.

**Describe the solution you'd like**
Add the option to the types and start the option after building useForm().

**Describe alternatives you've considered**
The returned option `watch` could be kept as well, if it is possible of using it dynamically together.

**Comment by bluebill1049** [comment]
useWatch is coming on V6 which allow you to watch in component level, i don't think we have plan to introduce as what you suggested above. thanks tho.
