### ISSUE TITLE
Watch registered fields in nested form components doesn't work as expected

### ISSUE THREAD

**Issue by PwnMonkey13** [react-hook-form/react-hook-form#1724]
**Describe the bug**
I'm building a huge form and for the sake of clarity i'm splitting it in many nested components wherein `watch` function doesn't get my fields as expected

**To Reproduce**
1. Go to [https://codesandbox.io/s/modest-boyd-bqrqx](https://codesandbox.io/s/modest-boyd-bqrqx?file=/src/App.js)
2. Type `foo` and `bar` like placeholders tell you, submit
3. Only `foo` parapraph get rendered
4. Open console, click button, and see that both fields values get saved

**Expected behavior**
Both `foo` and `bar` conditions should be both exectuted

I can barely imagine i'm the first one facing this crazy stupid issue..

And, thank you Bill for your amazing work !! 
I'm definitly fond of this lib and can't wait for the v6 to be published :)

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/xenodochial-brook-cj6x7?file=/src/App.js

make sure you place your sub-component outside of the root component, otherwise each re-render it will create a new component.

**Comment by PwnMonkey13** [comment]
Indeed.
it was more a react question btw
thanks for your reactivity :)
