### ISSUE TITLE
Why do I re-render twice when execute handleSubmit

### ISSUE THREAD

**Issue by keiya01** [react-hook-form/react-hook-form#1725]
**Describe the bug**
When I executed handleSubmit function that was returned from useForm hook, re-render was run twice. re-render was executed before and after the callback was executed.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-useform-template-rl7ln?file=/src/index.js
2. Click on 'Submit' button.
3. Look at the 'render' that is output to the console.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-rl7ln?file=/src/index.js

**Expected behavior**
I expect it to be re-rendered only once.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome
 - Version: 83

**Comment by bluebill1049** [comment]
The first re-render is to clean errors on the page (we could do a check for empty error, but I think the benefit is little) if they are been corrected before going the `handelSubmit` callback.

**Comment by keiya01** [comment]
I understood. Thank you for teaching me so kindly.

**Comment by bluebill1049** [comment]
> I understood. Thank you for teaching me so kindly.

Pleasure! hope you find this lib useful 🙏

**Comment by artursopelnik** [comment]
+1
