### ISSUE TITLE
NestedValue not respected in errors v6 rc

### ISSUE THREAD

**Issue by donaldpipowitch** [react-hook-form/react-hook-form#1726]
**Describe the bug**
If I use `NestedValue` it isn't correctly represented in errors.

**To Reproduce**
See type error in line 41 in the Codesandbox link.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-typescript-hzrjh?file=/src/index.tsx

**Expected behavior**
No type error.

**Screenshots**
![image](https://user-images.githubusercontent.com/1152805/83222378-7b991980-a178-11ea-8838-c53554587d28.png)

**Desktop (please complete the following information):**
- not relevant

**Smartphone (please complete the following information):**
- not relevant

**Additional context**
Would be cool if the issue template would include links to TypeScript-based Codesandbox templates 😻

Thank you for the lib. I currently look for an alternative to formik.

Is there any reason why `NestedValue` is not _deep_ and added by default behind the scenes? :)

**Comment by bluebill1049** [comment]
Thanks for the issue @donaldpipowitch 
https://codesandbox.io/s/react-hook-form-typescript-xjfhd 
once the doc is out, I think it will make more sense, NestedValue is made for a single input which returns object/array data. FYI: @kotarella1110 

> Would be cool if the issue template would include links to TypeScript-based Codesandbox > 
> templates 😻

will do.

**Comment by donaldpipowitch** [comment]
Thank you for the quick help!

**Comment by bluebill1049** [comment]
> Thank you for the quick help!

np :)
