### ISSUE TITLE
Add type safety to handleSubmit data object

### ISSUE THREAD

**Issue by ertw** [react-hook-form/react-hook-form#1734]
**Is your feature request related to a problem? Please describe.**

In Typescript when I type my `useForm()` function with a `key: value` of `myNumVal: 42`, the data object that the `handleSubmit()` callback receives is typed the same way, with a number. However, this object actually has a type of `key: string`.

**Describe the solution you'd like**

I'd like the type system to tell me that I am passing the incorrect value.

**Describe alternatives you've considered**

Considering that converting between numbers / bools and strings can be problematic, I think the best thing to do is for me to always keep my values as strings. I just think it would be great if the type system could remind me if I'm trying to do something impossible.

**Additional context**

Here is an example of the code to reproduce this:
```typescript
const initialState = {
  myNumVal: 42
};

export const App: React.FC = () => {
  const { register, handleSubmit } = useForm<typeof initialState>();
  return (
    <form onSubmit={handleSubmit(data => console.log(data))}>
      <input
        defaultValue={initialState.myNumVal}
        ref={register}
        name="myNumVal"
        type="number"
      />
      <button type="submit">SUBMIT</button>
    </form>
  );
};
```

And here is a working example: https://codesandbox.io/s/my-app-wnb8x?file=/src/App.tsx:71-491

Note that the type of `data` passed to `console.log()` is `myNumVal: number`, when in reality, the object being passed in is `myNumVal: string`

**Comment by bluebill1049** [comment]
This is coming for the next major version of V6. @kotarella1110 👍

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/blob/master/src/types/index.ts

`SubmitHandler` take a look this type.

**Comment by kotarella1110** [comment]
@ertw You can use generics in v6.

```ts
handleSubmit<{ myNumVal: string }>(data => console.log(data))
```
