### ISSUE TITLE
Unexpected reset behavior

### ISSUE THREAD

**Issue by arikimolloy** [react-hook-form/react-hook-form#1752]
**Describe the bug**
When providing defaultValues to useForm and calling reset with an undefined field, the field does not get rendered and does not receive the undefined value, so does not change value.

**To Reproduce**
1. Click the "Reset with new values" button in the sandbox
2. Notice how reset is called with no middleInitial field, and the field does not change value.

**Codesandbox link (Required)**
https://codesandbox.io/s/modest-dawn-6d8l9

**Expected behavior**
undefined should be passed to the field rather than the previous value.

**Desktop (please complete the following information):**
 - OS: macOS Mojave (v10.14.6)
 - Browser: only tested in chrome
 - Version: latest

**Additional Info**
My use case is that I receive data externally from the server which may be missing fields from the object for null values or values with an empty string (to reduce request payload). So in the Codesandbox example, it's possible that I may get an object that does not have a middleInitial field even though the data on the server defines the field.
Possible object I receive:
`{ firstName: 'John', middleInitial: 'F', lastName: 'Doe'}`

Another possible object I receive:
`{ firstName: 'John', lastName: 'Doe'}`

So it seems like with the current behavior, my only option would be to "fill in" the missing values and give them empty strings, however this is extremely difficult (my example is extremely basic, the objects I receive can be very complex and hard to tell what fields I need to "fill in").

Let me know if more info is needed, thanks.

**Comment by bluebill1049** [comment]
This is expected behavior for `Controller`, please give the input a value eg: '' instead of `undefined.` for native input, we are invoking `.reset()` which will clear the entire form. however, with the controller, you will need to supply a value for the controller. the similar idea we need to have a `defaultValue` for the Controller.

**Comment by arikimolloy** [comment]
Thanks for the reply. Okay it looks like I can set them to `null` as well and reset works properly. Are there any consequences for passing fields in defaultValues which don't have corresponding inputs? I am dynamically generating fields and at the time of invoking `useForm` I have no way of knowing which fields will get generated.

So would passing this to defaultValues
`{ firstName: 'John', middleInitial: 'F', lastName: 'Doe'}` be an issue if I don't have a `middleInitial` field/input in the form?

Also one more question - since I am using the reset api (and therefore need to provide defaultValues at the useForm level), I don't need to pass defaultValue inline to Controller right?

**Comment by bluebill1049** [comment]
> Are there any consequences for passing fields in defaultValues which don't have corresponding inputs? I am dynamically generating fields and at the time of invoking `useForm` I have no way of knowing which fields will get generated.

You will have to generate those input into a `hidden` input, otherwise, data will be lost. it's important to think of native form while building with RHF. 

> Also one more question - since I am using the reset api (and therefore need to provide defaultValues at the useForm level), I don't need to pass defaultValue inline to Controller right?

That's correct. It's either.
