### ISSUE TITLE
Return ref for programmatic `register` call

### ISSUE THREAD

**Issue by m3fawner** [react-hook-form/react-hook-form#1753]
**Is your feature request related to a problem? Please describe.**
We are attempting to programmatically focus an input using a hook. In order to do this, we need the React ref of the underlying `input` to call focus on it. Since programmatically calling `register()` doesn't return anything, we end up needing to wrap the parent element in a div and assign a ref, then use a query selector to get the input itself.

**Describe the solution you'd like**
I would love if RHF's `register` could return the React ref that is used to listen to all of the events and such. That way, we can forward the ref to our styled-component and also programmatically reference it for `focus()`.

**Describe alternatives you've considered**
I believe we could also achieve this using the RHF `Controller`, but that feels overkill for our use case.

**Additional context**
```js
const RHFInput = ({ className, disabled, focus, error, ...props }) => {
    const inputWrapperRef = useFocusHook(focus);
    return (
        <div ref={inputWrapperRef}>
            <AdornedInput
                className={className}
                inputId={props.id || props.name}
                disabled={disabled}
                error={error}
                leftAdornment={props.leftText && <Adornment>{props.leftText}</Adornment>}
                rightAdornment={props.rightText && <Adornment>{props.rightText}</Adornment>}
                input={<Input {...props} ref={props.register} />}
            />
        </div>
    );
};
```

**Comment by bluebill1049** [comment]
Take a look this section: https://react-hook-form.com/faqs#Howtosharerefusage i think this is what you after.

**Comment by m3fawner** [comment]
Oh good gravy, right there in the docs. Sorry to have missed that.

Refactored the focus hook to take in the input ref worked like a charm.

Thanks for the quick response and direction! Appreciate it @bluebill1049

**Comment by bluebill1049** [comment]
no worries @m3fawner 👍
