### ISSUE TITLE
Function components cannot be given refs

### ISSUE THREAD

**Issue by Prathapkarumanchi** [react-hook-form/react-hook-form#1758]
**Describe the bug**

I tried to use the example provided in Doc's and I see the following error message.
Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

**Codesandbox link (Required)**
https://e3fml.csb.app/

**Used Example **
Example code provided after Video Tutorial.

**Comment by bluebill1049** [comment]
what's the issue?
