### ISSUE TITLE
Validate Email Top-Level Domains

### ISSUE THREAD

**Issue by BMariscal** [react-hook-form/react-hook-form#1767]
The email validation doesn't currently validate top-level domains. For instance, entering `hello@mail.commmmmmmmmmm`, in the `Email` field does not raise an error. 

![](https://i.ibb.co/yVYcFcP/react-hook-form.png)

**Describe the solution you'd like**

During email validation, check [top-level domains](https://www.npmjs.com/package/tlds).
https://github.com/react-hook-form/react-hook-form/blob/8a08a04f2741667a900feec5b2b873377abaed2b/examples/basicValidation.tsx#L37

**Describe alternatives you've considered**
Use https://www.npmjs.com/package/tlds in my project PLUS react-hook-form.

**Comment by bluebill1049** [comment]
The example was for demo and hence I keep the regex as simple as possible. you can find a more robust version here: https://emailregex.com/
