### ISSUE TITLE
Controller rules reset

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#1770]
_| create a new issue, so we don't notify and annoy others._

I changed the previous code as much as i could to simulate my real problem. 
Can you take a look? https://codesandbox.io/s/controller-rules-npe18?file=/src/App.tsx

As you can see, required erros appear even though the fields are not required in that moment.
Thats why i thought on re-registering both hour fields whenever the switched are toggled.
Thanks.

_Originally posted by @pedroguia in https://github.com/react-hook-form/react-hook-form/issues/1749#issuecomment-638512677_

**Comment by bluebill1049** [comment]
just like I suggested on the previous issue: just register the updated rules

https://codesandbox.io/s/controller-rules-mxxwg?file=/src/App.tsx:0-2919

```
register("startHour", { required: !value });
register("endHour", { required: !value });
```

**Comment by pedroguia** [comment]
Well, that solves the required problem but creates another one. If you toggle the "all day" switch after re registering, the values dont change anymore, they only change before registering. 

Thanks anyway for your help.

**Comment by bluebill1049** [comment]
> Well, that solves the required problem but creates another one. If you toggle the "all day" switch after re registering, the values dont change anymore, they only change before registering.
> 
> Thanks anyway for your help.

what do you mean all day and values don't change anymore?

**Comment by bluebill1049** [comment]
isn't that defined by your code `disabled={areHoursDisabled}`?

**Comment by pedroguia** [comment]
I mean toggling "allDay" should always set startHour to 00 and endHour to 23:59, even after setting periodic to true.
After registering startHour and endHour, like you did, toggling "allDay" does not update startHour and endHour anymore.

Maybe what im trying to do is just impossible.

**Comment by bluebill1049** [comment]
> I mean toggling "allDay" should always set startHour to 00 and endHour to 23:59, even after setting periodic to true.
> After registering startHour and endHour, like you did, toggling "allDay" does not update startHour and endHour anymore.
> 
> Maybe what im trying to do is just impossible.

from my end is working as expected, i don't think those input support 24hrs, as you can see its set to be 11:59 PM.

**Comment by pedroguia** [comment]
Can you please try:

1 -> refresh page -> toggle allday to true -> hours change? they should change.
2 ->refresh page -> toggle periodic to true -> toggle allday to true -> hours change? they should change, but they dont.

Thats what i mean, after setting periodic to true and registering startHour and endHour, they will never again change when you toggle allDay.

**Comment by bluebill1049** [comment]
what about this?

```
validate: value => {
  const { allDay, periodic } = watch();
  const areHoursRquired = !periodic && !allDay;
  return areHoursRquired && !!value;
}
```

**Comment by pedroguia** [comment]
If you toggle allDay you get a validation error, if you toggle periodic you get required errors.
I'll just remove required from starHour and endHour and proceed.

The thing is, if in the future i need dynamic required inputs i guess i'll this same error.

**Comment by bluebill1049** [comment]
> If you toggle allDay you get a validation error, if you toggle periodic you get required errors.
> I'll just remove required from starHour and endHour and proceed.
> 
> The thing is, if in the future i need dynamic required inputs i guess i'll this same error.

do you mean what I purposed above with `validate`?

**Comment by bluebill1049** [comment]
> If you toggle allDay you get a validation error, if you toggle periodic you get required errors.
> I'll just remove required from starHour and endHour and proceed.
> 
> The thing is, if in the future i need dynamic required inputs i guess i'll hit this same error.

also, you have considered schema validation as well.

**Comment by bluebill1049** [comment]
anyway i am tired and done for the day, will take a look again.

**Comment by pedroguia** [comment]
> > If you toggle allDay you get a validation error, if you toggle periodic you get required errors.
> > I'll just remove required from starHour and endHour and proceed.
> > The thing is, if in the future i need dynamic required inputs i guess i'll this same error.
> 
> do you mean what I purposed above with `validate`?

I tried what you purposed and was still getting errors, but now im not, idk if you changed something but i guess its working. i'll let some more.
