### ISSUE TITLE
Nested fields have been reseted when using "move" from "useFieldArray" on conditionnal render based on "watch"

### ISSUE THREAD

**Issue by Benjpoirier** [react-hook-form/react-hook-form#1773]
**Describe the real bug**
[To follow up this issue](https://github.com/react-hook-form/react-hook-form/issues/1765)

So the unexpected behavior:

In the example below, I have a form with 2 levels of "FieldArray".
There is a checkbox to allow us to add more text fields. (so the render of this component is conditional with the value of this checkbox using a "watch")
In case I have more than 2 items on the first level. When I move down the first item, my nested fields are reset
if I remove the watch based condition everything doing well.

Thx for your time :)

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-w7rcu

**Expected behavior**
When I move down the first field I should keep my nested fields

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac Catalina 10.15.5
 - Browser chrome
 - Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by bluebill1049** [comment]
Thanks for clarifying the issue. Because react hook form rely on inputs for storing the state, toggling the value with `watch` in `useFieldArray` does making thing harder. May I suggest to toggle the visibility instead of unmounting the inputs.

**Comment by Benjpoirier** [comment]
this is ofter the simplest solution who is the best! Thx for the suggestion 👍

**Comment by LoicHa** [comment]
I had the same issue with a modal box that handled useFieldArray fields.
I had to move the fields on a div that is not unmounted. Works fine now.

**Comment by bluebill1049** [comment]
Thanks @LoicHa I am going to update the doc to include this. In fact, here is a useful codesandbox: https://codesandbox.io/s/react-hook-form-conditional-inputs-c7n0r
