### ISSUE TITLE
Setting defaultValue to null on DatePicker wrapped by Controller turns "isValid" to false

### ISSUE THREAD

**Issue by MrBlue9** [react-hook-form/react-hook-form#1777]
**Describe the bug**
Using "defaultValue" = null on a DateField wrapped in Controller turns "isValid" in formState to "false".

**To Reproduce**
1. Open attached CodeSandbox
2. Submit button is disabled because "isValid" is false
3. Change `defaultValue={null}` on second Field to `defaultValue={new Date()}` and Submit button is not disabled anymore when loading form again

**Codesandbox link (Required)**
https://codesandbox.io/s/gallant-jang-cqm4d?file=/src/App.tsx

**Expected behavior**
One should be able to initialize the field without a preset Date.

**Additional context**
I can't wrap my head around if this is an issue with the MUI DatePicker or with react-hook-form itself. Because the "date of birth" field in my CSB should be optional, it should also be initialized without a value. But even after entering a value, isValid stays false.

Maybe someone can have a look at my CSB example and figure out what I'm doing wrong, because I tried so much but can't get it right somehow :(

**Comment by bluebill1049** [comment]
Please fix your CSB.

**Comment by MrBlue9** [comment]
Sorry for that, didn't get any errors when initially creating it.
Does it work for you now?

**Comment by bluebill1049** [comment]
What's the issue here? looks correct behavior for me.

**Comment by MrBlue9** [comment]
Should "isValid" not be true and the form therefore submittable because the field "date of birth" is not required?

**Comment by MrBlue9** [comment]
Oh, now I see it! My ternary operators for both validations on that field are messed up! I got it working now! Thank you!
