### ISSUE TITLE
Validation does not trigger until submit is invoked

### ISSUE THREAD

**Issue by Spaideri** [react-hook-form/react-hook-form#1784]
**Describe the bug**
Automatic validation starts to trigger only after submit is invoked.

Typing text to input fields does not update the errors object or formState.isValid property until I have tried to submit.

After clicking and trying to invoke submit all changes to input values are validated in real time. Seems like something is blocking the execution until submit.

I have used the exact Getting started example

**To Reproduce**
1. `npx create-react-app form-test`
2. `npm install react-hook-form`
3. Modify App.js 
```
import React from 'react';

import './App.css';
import { useForm } from "react-hook-form";

function App() {
  const { register, handleSubmit, watch, errors, formState } = useForm();
  const onSubmit = data => console.log('submit', data);

  console.log('exampleRequired', watch("exampleRequired")); // watch input value by passing the name of it
  console.log('formValid', formState.isValid);
  console.log('errors', errors);

  return (
    <div className="App">
      <form onSubmit={handleSubmit(onSubmit)}>
        <input name="example" defaultValue="test" ref={register} />
        <input name="exampleRequired" ref={register({ required: true })} />
        {errors.exampleRequired && <span>This field is required</span>}

        <input type="submit" />
      </form>
    </div>
  );
}

export default App;

```
4. `npm start`

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser [Chrome 83.0.4103.61]

Console output for typing 'a' into the text input and clicking submit. Causes awful many renders for some reason.
![image](https://user-images.githubusercontent.com/1118774/83859579-cdb4de80-a726-11ea-8327-8fbdd73b2b6a.png)

**Comment by bluebill1049** [comment]
can you please follow the temple by supply a codesandbox?

**Comment by Spaideri** [comment]
https://codesandbox.io/s/heuristic-hodgkin-tx37h?file=/src/App.js

**Comment by bluebill1049** [comment]
`mode` : https://react-hook-form.com/api

**Comment by Spaideri** [comment]
> `mode` : https://react-hook-form.com/api

Duh, solved. Thank you. 

I got confused with the
```
reValidateMode: 'onChange'
```

**Comment by bluebill1049** [comment]
> > `mode` : https://react-hook-form.com/api
> 
> Duh, solved. Thank you.
> 
> I got confused with the
> 
> ```
> reValidateMode: 'onChange'
> ```

all good! a simple one 👍
