### ISSUE TITLE
Custom Masked Input Example Not working

### ISSUE THREAD

**Issue by zeyuri** [react-hook-form/react-hook-form#1786]
The custom masked input example is not working

1. Go to [this ](https://github.com/react-hook-form/react-hook-form/blob/master/examples/customMaskedInput.tsx) example.
2. Copy and paste it anywhere and run it
3. You will se the error "react-input-mask: children must be a function"

[CodeSandBox](https://codesandbox.io/s/stoic-taussig-meyb8?file=/src/App.js)

**Comment by bluebill1049** [comment]
That's a version problem with `react-input-mask`: https://codesandbox.io/s/trusting-agnesi-rdi5m?file=/src/App.js

if you having issues, take a look at controller version at the examples folder.

**Comment by diogolessa** [comment]
Hi @bluebill1049 ,

I took a look at yout example and it looks fine when the form mode is default. But if you change its mode to `onChange`, then it doesn't work properly.. Looks like the input value is always one change behind.

Try filling the input to the end and start erasing: https://codesandbox.io/s/elastic-lovelace-uou3g

You'll see that when you start typing, or once you complete it and start erasing, it just updates on second keyboard hit. Is it a problem with `react-input-mask` itself? Do you know who can help?

Thanks!

**Comment by bluebill1049** [comment]
Hey @diogolessa, thanks for pointing that out, i will remove that example from the repo. I think make sense to focus on Controller as it's much easier: https://codesandbox.io/s/react-hook-form-controller-079xx take a look that CSB, there is a mask input there too.
