### ISSUE TITLE
useFieldArray not storing to form correct

### ISSUE THREAD

**Issue by donovanly** [react-hook-form/react-hook-form#1810]
**Describe the bug**
When using useArrayForm to create entries within useForm, the newly created array fields are not stored correctly, instead of being stored within an array, each new variable is stored independently from each other.

**To Reproduce**
https://codesandbox.io/s/react-hook-form-usefieldarray-p3k2l
I've added Dev tools to the original CSB provided https://react-hook-form.com/api#useFieldArray
As you press APPEND, the new variables are added as a top level form value

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-p3k2l

**Expected behavior**
After appending new names, each one would belong to the form array `test`.

watch("test") should equal the following array
`[
   {firstName: "Bill", lastName: "Luo:},
   {firstName: "appendBill", lastName: "appendLuo:},
]`

**Screenshots**
![image](https://user-images.githubusercontent.com/14261786/83991309-59429100-a91a-11ea-98a3-b0bf83afaa49.png)

**Comment by bluebill1049** [comment]
That's expected behavior for the current version. Next major version we will change to nested object data type by default. if you want to have nested input date `watch({ nest: true })`

**Comment by donovanly** [comment]
Great thanks for clarifying, this solves my problem! That specific flag wasn't obvious to me 😢

**Comment by bluebill1049** [comment]
> Great thanks for clarifying, this solves my problem! That specific flag wasn't obvious to me 😢

next version we are fixing this :)
