### ISSUE TITLE
Material UI Select throwing error

### ISSUE THREAD

**Issue by zszep** [react-hook-form/react-hook-form#1813]
When wrapping the Select Component with Controller I get this error (The NativeSelect Component from MUI works as expected.):
```
Material-UI: A component is changing the uncontrolled value state of Select to be controlled.
Elements should not switch from uncontrolled to controlled (or vice versa).
Decide between using a controlled or uncontrolled Select element for the lifetime of the component.
The nature of the state is determined during the first render, it's considered controlled if the value is not `undefined`.


```
My sample code is:
```
<FormControl >
                <InputLabel>Priority</InputLabel>
                <Controller
                  as={
                    <Select>
                     <MenuItem value="low">Low</MenuItem>
  <MenuItem value="high">High</MenuItem>

                    </Select>
                  }
                  name="priority"
                  native={false}
                  control={control}
                />
              </FormControl>
```

**Comment by bluebill1049** [comment]
you are missing `defaultValue` or `defaultValues` at `useForm `

**Comment by zszep** [comment]
Yes. This solves the problem. Maybe this should be documented as it is not very intuitive. NativeSelect does not need the defaultValue parameter and all the samples I could find use NativeSelect.

**Comment by bluebill1049** [comment]
<img width="900" alt="Screen Shot 2020-06-08 at 8 26 20 pm" src="https://user-images.githubusercontent.com/10513364/84020547-54d3b200-a9c6-11ea-8b8c-7cfb08548734.png">

**Comment by acrellin** [comment]
@bluebill1049 I'm also seeing this error even after setting `defaultValues` in `useForm` (version 5.7.2).

Here are the relevant parts of the code:

```jsx
  const initialFormState = {
    obj_id,
    instrument_id: "",
    start_date: new Date(),
    end_date: new Date(),
    filters: [],
    exposure_time: "",
    priority: ""
  };

  const { handleSubmit, register, getValues, control, errors, reset } = useForm({
    defaultValues: initialFormState
  });

  const handleSelectedInstrumentChange = (e) => {
    reset({
      ...initialFormState,
      instrument_id: e.target.value
    });
  };
```
...
```jsx
            <Controller
              as={(
                <Select labelId="instrumentSelectLabel">
                  {
                    instrumentList.map((instrument) => (
                      <MenuItem value={instrument.id} key={instrument.id}>
                        {instrument.name}
                      </MenuItem>
                    ))
                  }
                </Select>
              )}
              name="instrument_id"
              rules={{ required: true }}
              control={control}
              onChange={([e]) => handleSelectedInstrumentChange(e)}
            />
```

Everything works as expected, but I'm getting the Material-UI error message in the console: "Material-UI: A component is changing the uncontrolled value state of Select to be controlled. Elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled Select element for the lifetime of the component." 

What am I doing wrong? I still get the error when I pass `defaultValue=""` to the `Controller`.

Thanks in advance and thanks for the excellent package!

**Comment by bluebill1049** [comment]
hey @acrellin any chance to reproduce that in an isolated codesandbox? happy to investigate the reason why. I do suspect the `value` prop is named something different, in v6 its much easier with render prop.

**Comment by gregStevenard** [comment]
This is happening to me too. @acrellin have you been able to fix this ?
