### ISSUE TITLE
Form is not considered "dirty" when removing the last item in a nested array.

### ISSUE THREAD

**Issue by jonhaddow** [react-hook-form/react-hook-form#1815]
**Describe the bug**
When using a nested array (`prop.nestedProp`), the form state is not updated when the last item is removed.

**To Reproduce**
1. Go to Codesandbox lint
2. The first demo is a non-nested field array. Removing updates state.
3. The second demo is a nested field array. Removing *doesn't* updates state.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-f0uv2?file=/src/index.js

**Expected behavior**
I expect form state to be updated when using a field array for a nested property.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by bluebill1049** [comment]
This should have been resolved in the latest `6.0.0-rc.3`, can you try the latest `RC` version and let me know if that solves the problem.

**Comment by jonhaddow** [comment]
That doesn't seem to have solved the issue. I've updated the code sandbox with the latest.

**Comment by bluebill1049** [comment]
Thanks for picking up this bug:

https://codesandbox.io/s/react-hook-form-usefieldarray-gxzc5?file=/src/src/useFieldArray.ts

**Comment by jonhaddow** [comment]
Nice one! Thanks for the quick response and fix 👍

**Comment by bluebill1049** [comment]
Thanks for reporting those issues too. appreciated.
