### ISSUE TITLE
Enable Validation on Initilization

### ISSUE THREAD

**Issue by droruri** [react-hook-form/react-hook-form#1819]
**Is your feature request related to a problem? Please describe.**
The problem is repeating code.
If I would like to build many forms which will run validation on fields when the component is initializing, I will have to write the command "triggerValidation" under useEffect in each form separately. 

**Describe the solution you'd like**
A form mode which will run validations on initilization and on change

**Describe alternatives you've considered**
Right now the alternative is trigger validation by myself in every component like i mentioned before

**Additional context**
Attached the current solution (which I want you to make shorter)
![image](https://user-images.githubusercontent.com/14028859/84055859-1508cc80-a9be-11ea-9242-7ef908a71a24.png)

**Comment by bluebill1049** [comment]
Thanks for the feature request. I don't think there is anything wrong with `trigger`, but i will leave this to the community to decide.

**Comment by droruri** [comment]
So, that's the reccommend way to trigger validation on component initilization?
