### ISSUE TITLE
Server Side Rendering & Controllers: useLayoutEffect should only be used in components that render exclusively on the client. & Missing Types [^6.0.0-rc.3]

### ISSUE THREAD

**Issue by ItsWendell** [react-hook-form/react-hook-form#1821]
**Describe the bug**
Using version _6.0.0-rc.3_ together with NextJS 9.4.4, I'm experiencing the following warning in my terminal in development mode regarding useLayoutEffect:

> Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
>     in Controller (at leave-review/index.tsx:305)

_Related PR where this was introduced: https://github.com/react-hook-form/react-hook-form/pull/1789_

**To Reproduce**
1. Use NextJS for server-side rendering.
1. Use an 'advanced' controller `<Controller render={({ onChange, onBlur, value}) => ...} />`
3. See console warnings.

**Codesandbox link (Required)**
https://codesandbox.io/s/nextjs-ssr-react-hook-form-2m61v

**Expected behavior**
"useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes." - React

I don't think we can expect that everyone only uses React Hook Form in a non-ssr environment.

**Desktop (please complete the following information):**
 - OS: Fedora 32
 - Browser: Chrome / Firefox

**Comment by bluebill1049** [comment]
thanks for the issue report!
