### ISSUE TITLE
Expose a comparer function for setValue -> setDirty to deep compare arrays or objects

### ISSUE THREAD

**Issue by mike-jewell** [react-hook-form/react-hook-form#1829]
**Is your feature request related to a problem? Please describe.**
I am trying to migrate from Formik over to react-hook-form.  I have a checkbox list control which takes an array of { id: string, name: string } and apply it to the control.  I then use onChange on the Checkbox control to setValue on the form.  The problem I have is that I need to splice the value to force a rerender as if I change the value supplied from the Controller it modifies defaultValuesAtRenderRef which means the setDirty function returns false as the referenced array value is modified.  However when I splice the array, I get a new array reference and setDirty works correctly, except when I revert the form values via the input.  As I have spliced the array and created a new reference object, the compare always returns false from that point on.

**Describe the solution you'd like**
Would it be possible to pass a comparer (as I know not every scenario of object/array would be possible without something like lodash/deepEquals) and setDirty can use it to determine if the firld is dirty or not.

**Describe alternatives you've considered**
I can't think of any.  I have this checkbox example, which I know the model could be changed to do it differently, but my app uses arrays and objects dynamically for other functionality.  Currently in formik I would use lodash/deepEquals to solve this.

**Additional context**
Here is an example of what I am trying to do:

https://codesandbox.io/s/romantic-snow-u7qu2?file=/index.js

The problem I am having is ``` let isFieldDirty  = ....```  is a reference comparison for object/arrays.

``` javascript
    const setDirty = useCallback((name) => {
        if (!fieldsRef.current[name] ||
            (!readFormStateRef.current.dirty && !readFormStateRef.current.dirtyFields)) {
            return false;
        }
        let isFieldDirty = defaultValuesAtRenderRef.current[name] !==
            getFieldValue(fieldsRef.current, fieldsRef.current[name].ref);
        const isFieldArray = isNameInFieldArray(fieldArrayNamesRef.current, name);
        const previousDirtyFieldsLength = dirtyFieldsRef.current.size;
        if (isFieldArray) {
            const fieldArrayName = getFieldArrayParentName(name);
            isFieldDirty = getIsFieldsDifferent(getFieldValueByName(fieldsRef.current, fieldArrayName), get(defaultValuesRef.current, fieldArrayName));
        }
        const isDirtyChanged = (isFieldArray ? isDirtyRef.current : dirtyFieldsRef.current.has(name)) !==
            isFieldDirty;
        if (isFieldDirty) {
            dirtyFieldsRef.current.add(name);
        }
        else {
            dirtyFieldsRef.current.delete(name);
        }
        isDirtyRef.current = isFieldArray
            ? isFieldDirty
            : !!dirtyFieldsRef.current.size;
        return readFormStateRef.current.dirty
            ? isDirtyChanged
            : previousDirtyFieldsLength !== dirtyFieldsRef.current.size;
    }, []);
```

**Comment by bluebill1049** [comment]
Thanks for the feature request. I don't think we will implement this feature at this stage.

I would recommend doing an object compare aginst your default value.

`getValues()` compare with `defaultValues` during onChange.

**Comment by mike-jewell** [comment]
How can I effect the form state using this?

**Comment by bluebill1049** [comment]
> How can I effect the form state using this?

you can consider changing your custom component to `useFieldArray` so each input is tracked.

**Comment by mike-jewell** [comment]
Thanks for getting back to me so quick. I’ll have a read and see if I can apply that. Thanks again

**Comment by bluebill1049** [comment]
actually you can do the same with `useForm`,  why not break it into separate inputs?

**Comment by bluebill1049** [comment]
so it's easier to compare the input value as well, instead compare the object "deep compare:".

**Comment by bluebill1049** [comment]
eg:
``` 
<input type="checked" name="test[0]" />
<input type="checked" name="test[1]" />
<input type="checked" name="test[2]" />
```

is much easier to track `dirty` than a nested object.

**Comment by mike-jewell** [comment]
The problem I have is that my app creates dynamic forms from templates. The models can be complex and can be arrays of models. Changing the models and state need to be changed throughout so the deep compare on nested objects works for us. Converting all of them to x[0].y[0].z will be tough

**Comment by bluebill1049** [comment]
I see, take a look at useFieldArray to see if a valid option, otherwise you will have to do some manual work to maintain that dirty flag.

**Comment by mike-jewell** [comment]
I've had success modifying the state using useFieldArray, so thanks for the help.  Awesome library!

**Comment by bluebill1049** [comment]
awesome to hear @mike-jewell 👍

**Comment by mike-jewell** [comment]
Hi again.  I have been trying to get this working with useFieldArray and have had some success.  However I wanted to check if this is the correct way to do it?

https://codesandbox.io/s/dazzling-lalande-yx5mt?file=/index.js

The form data is modifying and submitting correctly, but the problem is that the dirty state isn't correct.  

1. If you edit the text box dirty is true.
1. If you check the checkbox number 3 dirty is true.
1. If you uncheck checkbox number 3 dirty is false.

This shouldn't happen as the textbox is still dirty.

Am I doing something wrong?  Thanks in advance.

**Comment by mike-jewell** [comment]
Hi again. I have been trying to get this working with useFieldArray and have had some success. However I wanted to check if this is the correct way to do it?

https://codesandbox.io/s/dazzling-lalande-yx5mt?file=/index.js

The form data is modifying and submitting correctly, but the problem is that the dirty state isn't correct.

    If you edit the text box dirty is true.
    If you check the checkbox number 3 dirty is true.
    If you uncheck checkbox number 3 dirty is false.

This shouldn't happen as the textbox is still dirty.

Am I doing something wrong? Thanks in advance.

**Comment by bluebill1049** [comment]
Thanks this is a bug.
