### ISSUE TITLE
Boolean RadioGroup defaults does not work 

### ISSUE THREAD

**Issue by ajaybeniwal** [react-hook-form/react-hook-form#1830]
**Describe the bug**
I have created a component to get the boolean values  instead of stings which work without any issue but defaultValues does not work

**To Reproduce**

**Codesandbox link (Required)**
https://codesandbox.io/s/tender-lalande-ffjtb

- [useForm](https://codesandbox.io/s/react-hook-form-useform-template-lsm61) Template
- [useFieldArray](https://codesandbox.io/s/react-hook-form-usefieldarray-template-q0jek) Template
- [Controller](https://codesandbox.io/s/react-hook-form-controller-template-yu0z5) Template

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bluebill1049** [comment]
You have supplied boolean, so it's checked instead of value: 
https://codesandbox.io/s/focused-allen-xr34z?file=/src/App.js
