### ISSUE TITLE
Using 'touched' does not trigger the validation at first submit

### ISSUE THREAD

**Issue by sajithneyo** [react-hook-form/react-hook-form#1831]
**Describe the bug**
Using 'touched' in combination with errors won't trigger validation

**To Reproduce**
1. Go to Codesandbox link
2. Switch to console
3. Add a character to the input field
4. Press submit (1st submit will show an empty error object) 
5. Press submit again (2nd submit will show the validation error)

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-error-1lton?file=/src/index.js'

**Expected behavior**
Validation should be triggered at the first submit click

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : chrome
 - Version: 83.0.4103.97

**Additional context**
- Removing `touched.password` triggers the validation at first submit
- Without entering any character (empty input) also triggers the validation (Please refresh before doing this)

Am I using `touched ` wrong?

**Comment by bluebill1049** [comment]
```
const handleError = () => {
    if (
      (errors.password && errors.password.type === "isValidPassword") ||
      touched.password
    ) {
      return (
        <>
          <div>err</div>
          <div>err</div>
        </>
      );
    }
  };
```

This component you had inside gets mount and unmount each time. consider to move it outside the root component.

**Comment by sajithneyo** [comment]
@bluebill1049 When I move the function bellow the button,
```
<button type="submit">Submit</button>
{handleError()}
```
it works. Even the current way works if I remove the `touched`. So why this strange behavior when using `touched `?

**Comment by bluebill1049** [comment]
nope, it shouldn't work.  like I state above, you should move your inner component to its own component and pass down props.

**Comment by sajithneyo** [comment]
@bluebill1049 I tried and it works like that! Btw i tried moving to a separate components and it does not work!

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-error-r3dj0?file=/src/index.js

**Comment by valoricDe** [comment]
When I have the rule `required: true` and I touch/blur a field. Shouldn't it add the required error to the errors object?
