### ISSUE TITLE
useFieldArray: validation not triggered when removing a field

### ISSUE THREAD

**Issue by lburgess** [react-hook-form/react-hook-form#1834]
**Describe the bug**
Given I have a field which contains invalid data
And all other fields contain valid data 
When I remove the field with invalid data
Then the formState should be valid (formState.isValid === true)

However, formState.isValid remains false

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-template-2ibm3?file=/src/index.js
2. Click on 'Append'
3. Notice formState.isValid: false
4. Edit the form input with the value 'appendBill' to be '' (empty)
5. Click on 'Delete' next to the input with 'appendLou' value
6. Notice formState.isValid: false, when it should be true

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-2ibm3?file=/src/index.js

**Expected behavior**
See steps to reproduce

**Screenshots**

![image](https://user-images.githubusercontent.com/54953/84276291-1525db00-ab2a-11ea-9e50-b0bc5b6af10a.png)

![image](https://user-images.githubusercontent.com/54953/84276322-21aa3380-ab2a-11ea-875a-690a208209d6.png)

![image](https://user-images.githubusercontent.com/54953/84276365-2ff84f80-ab2a-11ea-8191-a09fa02bfd59.png)

**Comment by bluebill1049** [comment]
can you use the latest version? The bug could have already been resolved. In fact, try 6.0.0-rc.3

**Comment by lburgess** [comment]
Thanks for the quick response Bill.  
The issue appears to exist in 6.0.0-rc.3 also.

**Comment by bluebill1049** [comment]
Thanks @lburgess i will take a look at it.

**Comment by bluebill1049** [comment]
Take a look this one: https://codesandbox.io/s/react-hook-form-usefieldarray-template-pbtc2

The problem is you are using `[firstName]` for object you should stick with `.` syntax so RHF can identify the input easier.

**Comment by lburgess** [comment]
Much appreciated - good to know.
 
It does (IMO) break with long established convention... but agree that it introduces unnecessary complexity when there is a practical approach which already works and given it is all handled by Javascript can do so without any real ramifications.

Thanks again for your help (and for react-hook-form in general for that matter - it is a joy to work with).

**Comment by bluebill1049** [comment]
Awesome to hear @lburgess 🙏 Thanks for your understanding as well.
