### ISSUE TITLE
Values disappear after route change

### ISSUE THREAD

**Issue by kacluk123** [react-hook-form/react-hook-form#1836]
So I have this component 

```
const Form = () => {
  const a = useForm()
  const b = useForm()
  const c = useForm()

  return (
    <Switch>
      <Route path='/step1'>
        <ComponentA form={a} />
      </Route>
      <Route path='/step2'>
        <ComponentB form={b} />
      </Route>
      <Route path='/step3'>
        <ComponentC form={c} />
      </Route>
    </Switch>
  )
}
```

And the problem is - for example if I fill step1 and go to step2 and after that when i'm back to step1 all the values are gone. Why form act like this? Forms objects are on top level so why values ​​disappear after route change? I saw the example of steps like form in docs but in dosen't  satisfy me, because it requires from user to click on button for the values to be saved.

**Comment by bluebill1049** [comment]
> I saw the example of steps like form in docs but in dosen't satisfy me, because it requires from user to click on button for the values to be saved.

It's not about you :) 

First of all, this is expected behavior for native forms, a form get unmounted and data will be removed. RHF store data inside input state. We embrace native input behavior.

however next version we will give users the option: https://twitter.com/bluebill1049/status/1270684496526893056

**Comment by bluebill1049** [comment]
here is a good resource on building a persist multiple steps form: https://www.youtube.com/watch?v=CeAkxVwsyMU
