### ISSUE TITLE
Extra `type` property on MUI checkbox Controller demo?

### ISSUE THREAD

**Issue by dandv** [react-hook-form/react-hook-form#1837]
I've copied the Checkbox example from https://codesandbox.io/s/react-hook-form-controller-079xx?file=/src/index.js:1718-1748 locally, upgraded to v6.0.0-rc3, and for the `type="checkbox"` prop I get a TypeScript error that

> Property 'type' does not exist on type 'IntrinsicAttributes & { name: string; as?: (props: CheckboxProps) => Element; rules?: Partial<{ required: string | boolean | ValidationValueMessage<boolean> | ReactElement<...>; ... 5 more ...; validate: Validate | Record<...>; }>; onFocus?: () => void; defaultValue?: unknown; control?: Control<...>; render?: (data:...'.

**Comment by bluebill1049** [comment]
do you have that codesandbox with that issue?

**Comment by dandv** [comment]
No, I copied locally the MUI Checkbox code from your sandbox linked above. This is the error I'm getting:

![image](https://user-images.githubusercontent.com/33569/84334569-87f17f00-ab47-11ea-95d9-75cf3f2e3d93.png)

```
$ npm ls typescript
blog@1.1.1 /home/dandv/blog
└── typescript@3.9.5
$ npm ls react-hook-form
blog@1.1.1 /home/dandv/blog
└── react-hook-form@6.0.0-rc.3 
```

**Comment by bluebill1049** [comment]
thanks @dandv we have a sperate codesandbox for V6. I will do a version with TS as well. This codesandbox will stay for v5 users.

**Comment by bluebill1049** [comment]
updated for TS: https://codesandbox.io/s/react-hook-form-v6-controller-ts-4dpm9

will be including that in the final v6 doc.
