### ISSUE TITLE
allow useContext instead of little-state-machine in multistep wizard form

### ISSUE THREAD

**Issue by JerryGoyal** [react-hook-form/react-hook-form#1838]
I'm new to this library and looking forward to implement multistep wizard form.  I was going through https://react-hook-form.com/advanced-usage#WizardFormFunnel and noticed the dependency of little-state-machine, and, now I have to understand one more library :(

Since react has made it easier to use [useContext()](https://reactjs.org/docs/hooks-reference.html#usecontext) after hooks and also recommends to use this for simple state management. Can't we use useContext() instead of relying on little-state-machine? 
Is there any significant benefit for using any external state management library over useContext() or LocalStorage/SessionStorage for multistep wizard forms? 

Sorry if I missed something.

**Comment by bluebill1049** [comment]
you can absolutely use `useContext()`. `little-state-machine` is an abstraction and make thing easier for you, but i would recommend you do the useContext and learn from it.

**Comment by JerryGoyal** [comment]
oh thanks for the info.. I'll try to implement with useContext(). I hope this shouldn't be complicated.
