### ISSUE TITLE
Why reupdate the root component when register watch in child component

### ISSUE THREAD

**Issue by Taymindis** [react-hook-form/react-hook-form#1839]
The root component reupdate when using watch in child component.

**To Reproduce**
1. Go to 'https://codesandbox.io/s/react-hook-form-set-inputselect-value-1b7pt?file=/src/index.js'
2. Click on 'set all values'
3. Scroll down to 'Console log'
4. Log reupdate from root

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-set-inputselect-value-1b7pt?file=/src/index.js

**Comment by bluebill1049** [comment]
This is expected behavior for `watch`, next version will have `useWatch` hook and you can isolate the watch.

**Comment by bluebill1049** [comment]
going to close this issue, feel free to follow up with questions. you can start to try out `useWatch` with 6.0.0-rc.3
