### ISSUE TITLE
V6: Remove `ErrorMessage` Component

### ISSUE THREAD

**Issue by stramel** [react-hook-form/react-hook-form#1840]
I'm proposing that we drop the `ErrorMessage` component.

The basis of the component is to grab the error message of a specific field and present that in a certain way normally using `as` or `render`.

```jsx
<ErrorMessage as="p" errors={errors} name="firstName" message="required!" />
```

The `as` or `render` props are essentially just wrapping a message (string/element). Wrapping a string/element in React is pretty trivial. So if we pull this out of the `ErrorMessage` component, we end up with something like this:

```jsx
<p>
	<ErrorMessage as="p" errors={errors} name="firstName" message="required!" />
<p>
```

After pulling out the wrapping component, the end-user has much more control over how the message is rendered. However, what are we left with? `ErrorMessage` is essentially just a getter for the `errors` object. With the optional chaining operator `?.`, this "getter" functionality is relatively trivial:

```jsx
<p>
	{errors?.firstName && 'required!'}
</p>
```

or 

```jsx
<p>
	{errors?.firstName?.message}
</p>
```

This again provides the end-user much more control over how they would like to render it. For example, if the user doesn't want to render the empty `<p>` tag if no error message:

```jsx
<>
	{errors?.firstName && <p>{errors.firstName.message}</p>}
</>
```

When it comes to handling multiple error messages, I believe that handling them via the `ErrorMessage` component almost complicates things more than just handling it outside.

```jsx
<ErrorMessage errors={errors} name="multipleErrorInput">
    {({ messages }) =>
        messages &&
		Object.entries(messages).map(([type, message]) => (
			<p key={type}>{message}</p>
		))
	}
</ErrorMessage>
```

vs 

```jsx
<>
	{errors?.multipleErrorInput?.types && Object.entries(messages).map(([type, message]) => (
		<p key={type}>{message}</p>
	))}
</>
```

By removing this, helper component, we could trim some size off our lib size without impacting the end-user experience of rendering errors.

Also, an end-user can still create this relatively simple abstraction that aligns closer to their needs if they wish. I have done this in previous projects that didn't have this abstraction and it worked out well.

Maybe we pull some of these non-critical helpers out into a separate library if people still feel there is value in us supporting them?

/cc @bluebill1049 @kotarella1110 @JeromeDeLeon

**Comment by bluebill1049** [comment]
I think i have to agree with this, we had a poll on this as well, but now I look at it, it does make sense to move out the core. If users is rely on ErrorMessage, they can still use @hookform/error-messge component. Sorry @kotarella1110 i wasted your effort on removing it out... :(

**Comment by kotarella1110** [comment]
@bluebill1049 Don't mind 👍 
I also agree to remove this.
I will do this if necessary.

**Comment by bluebill1049** [comment]
awesome! thanks for understanding @kotarella1110 we will move this component to error-message and publish under @hookform/error-message

**Comment by JeromeDeLeon** [comment]
I must say I agree with your statement and that its beneficial to the lib. Still great job for @kotarella1110 for starting it out and for the head start to create its own under suggestion of @bluebill1049 👍👍👍
