### ISSUE TITLE
Controller not re-validate since v6.rc2

### ISSUE THREAD

**Issue by xiaoyu-tamu** [react-hook-form/react-hook-form#1841]
**Describe the bug**
The Controller not respect reValidateMode since v6 rc-2

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-register-with-error-messages-rdgjw?file=/src/index.js
2. Click on submit

with Controller ( Bug )

3. type some chars in First Name 
4. The Error "this is a required" still visible

with Register ( Correct behavior )

3. type some chars in Last Name
4. The Error cleared

**Expected behavior**
The Controller should respect reValidateMode.

 
**Additional context**

tested on both v6.rc2 and rc3

**Comment by bluebill1049** [comment]
Thanks for the report. This is already fixed will be resolve on rc.4: https://codesandbox.io/s/react-hook-form-register-with-error-messages-tur5s?file=/src/index.js

**Comment by bluebill1049** [comment]
will publish rc.4 this weekend. 👍
