### ISSUE TITLE
Bug with dirty combined with useForm and useFieldArray

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#1843]
Hi again. I have been trying to get this working with useFieldArray and have had some success. However I wanted to check if this is the correct way to do it?

https://codesandbox.io/s/dazzling-lalande-yx5mt?file=/index.js

The form data is modifying and submitting correctly, but the problem is that the dirty state isn't correct.

    If you edit the text box dirty is true.
    If you check the checkbox number 3 dirty is true.
    If you uncheck checkbox number 3 dirty is false.

This shouldn't happen as the textbox is still dirty.

Am I doing something wrong? Thanks in advance.

_Originally posted by @mike-jewell in https://github.com/react-hook-form/react-hook-form/issues/1829#issuecomment-642498323_

**Comment by michalkvasnicak** [comment]
@bluebill1049 Could this be ported to 5.7.X?

**Comment by bluebill1049** [comment]
we actually change the data type from `Set` to `Object` in order to solve this issue. I think it's easier to migrate to v6, which will be released this week.

**Comment by michalkvasnicak** [comment]
@bluebill1049 I tried to migrate but there is no export of `ErrorMessageProps` type from `@hookform/error-message`. But I think it should be possible to import from `@hookform/error-message/types` or something like this. Or maybe you could export it directly from `index.ts`?

**Comment by bluebill1049** [comment]
We are tighting up TS types export, any chance you can copy into your app.

**Comment by michalkvasnicak** [comment]
Yes I can copy that but otherwise version 6 is for really breaking the app because we rely on types from `react-hook-form` as we have custom components and hooks. For now I solved this by directly import few types from `@hookform/error-message/dist/types`.
