### ISSUE TITLE
Version 6.0.0 rc-3 Getting Error render is not a function when using FormContext

### ISSUE THREAD

**Issue by Taymindis** [react-hook-form/react-hook-form#1845]
**Describe the bug**
This test happened on version 6.0.0 rc-3 

**To Reproduce**
1. Go to 'https://codesandbox.io/s/react-hook-form-set-inputselect-value-1b7pt?file=/src/index.js'
2. Error page

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-set-inputselect-value-1b7pt?file=/src/index.js

**Comment by bluebill1049** [comment]
Thanks for the testing 👍 `FormProvider` now :) try to follow the standard.

**Comment by Taymindis** [comment]
It works now. Thanks!

**Comment by cheriecheung** [comment]
I encountered the same problem and this is exactly the solution to it. thank you!
