### ISSUE TITLE
React-Select with custom onChange value does not show selected

### ISSUE THREAD

**Issue by berrybell** [react-hook-form/react-hook-form#1847]
**Describe the bug**
React-Select changes the value but does not show selected option when providing custom onChange return value that I would prefer.

**To Reproduce**
In codesandbox, select any value for both select controls and submit form. The results will be printed to console. The first control will show the selected option, but the second will not although from the console print we can see that the value is selected.

**Codesandbox link (Required)**
https://codesandbox.io/s/intelligent-beaver-3k3mj?file=/src/App.tsx

- [useForm](https://codesandbox.io/s/react-hook-form-useform-template-lsm61) Template
- [useFieldArray](https://codesandbox.io/s/react-hook-form-usefieldarray-template-q0jek) Template
- [Controller](https://codesandbox.io/s/react-hook-form-controller-template-yu0z5) Template

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version 77

**Comment by bluebill1049** [comment]
You will need to return value, that react-select is expected.

**Comment by keemor** [comment]
Hi @berrybell,
Did you manage to get it working?
