### ISSUE TITLE
Error `data.slice is not a function`

### ISSUE THREAD

**Issue by simonleclerc** [react-hook-form/react-hook-form#1848]
**Describe the bug**
When using an array field with the `useFieldArray` hook and the `remove` method combined with a specific error object (coming from validationResolver in the example) we have a `data.slice is not a function ` error in the `removeAt` function of the lib.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-fieldsarray-yup-validation-min-length-57qtb?file=/src/index.js:620-633 this is an example from `react-hook-form/examples`
2. Click on 'Add question'
3. Click on 'Add question' again
4. Click on 'Remove question' of second question
5. Click on 'Remove question' of first question
6. See the error:
![image](https://user-images.githubusercontent.com/2854986/84400226-13c7e180-ac02-11ea-99f8-d8616da52166.png)
7. The errors come from the fact that the errors object of the `validationResolver` has a key `message` that should be an array and not an object.
```
{"questions":{"message":"questions is a required field","type":"required"}}
```

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-fieldsarray-yup-validation-min-length-57qtb?file=/src/index.js:620-633

**Comment by bluebill1049** [comment]
In the doc, we mentioned that we don't support custom register for FieldArray. 
<img width="995" alt="Screen Shot 2020-06-12 at 8 48 23 am" src="https://user-images.githubusercontent.com/10513364/84446714-7d3f0300-ac89-11ea-9f64-81c99bbdee5c.png">
