### ISSUE TITLE
Errors object is empty when submit the form using DataPicker control

### ISSUE THREAD

**Issue by kvskranthikumar** [react-hook-form/react-hook-form#1849]
I am integrating the DatePicker control inside the forms and observed that when I submit the form the errors object is empty.

When I edit the DatePicker control with wrong data it shows the error -

![image](https://user-images.githubusercontent.com/12032164/84400840-2e10b800-ac20-11ea-8e91-82fbed2320b1.png)

As soon as I submit the form the error is gone and errors object is empty -

![image](https://user-images.githubusercontent.com/12032164/84401141-8d6ec800-ac20-11ea-84f9-2cb1fd9a553b.png)

The expected behavior should be to retain the errors until the user corrects them.

Here the code sandbox to recreate this  - https://codesandbox.io/s/hungry-euclid-mgod9?file=/src/App.jsx

If this is not the correct way, how can we solve this such that errors object is not empty even though we submit the form?

**Comment by bluebill1049** [comment]
Your usage is incorrect with those internal `setError` within Controller, i would recommend you have a read over the Controller section in the doc and take a look at the codesandbox example there as well.

**Comment by kvskranthikumar** [comment]
_"Your usage is incorrect with those internal setError within Controller"_ 
Please can you explain this a bit more?

I have read the documentation and I have seen the example you have shared, but that didn't help on how the errors will show for validation on the DataPickers control I mentioned in the example.

The document on the setError says that on an event we can add errors -
https://react-hook-form.com/api/#setError

I did the same in the example I shared through the code sandbox, but errors are getting empty on clicking Submit.

Can you please modify/update the code sandbox, if this is not the correct way of using. I am looking for a solution where errors are shown on the DatePickers controls when clicking on submit.

**Comment by bluebill1049** [comment]
please start from here: https://react-hook-form.com/get-started

start with building a simple form and understand how errors get triggered.

you shouldn't need to use `setError` at all for your usage. `error` should appear by user's action. 

`setError` API is made when the user fetches an API endpoint and lead to manually set an Error.

**Comment by kvskranthikumar** [comment]
I have read the get-started guide that's the reason I created a sample/example :)

All the examples I see in the documentation talk about validation on required/min/max but I want to set a custom error like "Date Is Invalid" on an action for a validation scenario. Is this not supported? 

In my example, I am manually setting the error, so what is the issue in that. Why the "errors" object has the data for the first time and then becomes empty on submitting the form.

Just point to documentation doesn't solve my problem.

**Comment by kvskranthikumar** [comment]
I took the example from the documentation -

https://codesandbox.io/s/react-hook-form-set-error-clear-error-rd7cj?file=/src/index.js

In this example also I can see that when a user edits the form we can see the error -

![image](https://user-images.githubusercontent.com/12032164/84490051-3d474280-acc0-11ea-9aa6-5363c2dc9625.png)

But when I submit the form, errors are lost.

![image](https://user-images.githubusercontent.com/12032164/84490309-9a42f880-acc0-11ea-9633-fa56be186097.png)

How can we retain the errors when the form is submitted?

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/kw7z2q2n15

**Comment by kvskranthikumar** [comment]
How to show custom errors other than the required/max/min, which are still shown when we click on submit.
Please point to a sample where we have custom errors for validations like the example below -

https://codesandbox.io/s/react-hook-form-set-error-clear-error-rd7cj?file=/src/index.js

**Comment by bluebill1049** [comment]
<img width="968" alt="Screen Shot 2020-06-12 at 10 54 42 pm" src="https://user-images.githubusercontent.com/10513364/84504690-b5812880-acff-11ea-8e08-67b12347dab3.png">
