### ISSUE TITLE
V6: useWatch not working for setValue as object

### ISSUE THREAD

**Issue by Taymindis** [react-hook-form/react-hook-form#1851]
**Describe the bug**
I am trying to get the result as JSON object and setValue to the label while using `useWatch`, but it's not working, if i change to watch as it is working.

**To Reproduce**
1. Go to 'https://codesandbox.io/s/react-hook-form-set-inputselect-value-21zkn?file=/src/index.js'
2. Click on 'set All Values'
3. only watch label changed value, useWatch didn't change

**Comment by bluebill1049** [comment]
I see the problem because you are using setValue with a nested object. `useWatch` is based on input `name` and that's why it's not recognizing it, I don't think we will support use case for the nested object with `useWatch`.  I will drop a note under the doc for this. 

alternative solution:

`setValue('aaa.bb', 'xxx')` will invoke `useWatch`

**Comment by bluebill1049** [comment]
nvm took a closer look, we can actually fix this. i will do that tonight.

**Comment by Taymindis** [comment]
Great Bill :)

If not, i will be struggling converting my resp object to json path array :(

Great you can fixed it.

Thanks!

**Comment by Taymindis** [comment]
Hi Bills, 

I have clone the master branch and tested locally, the issue seemed still existed.

**Comment by bluebill1049** [comment]
looks like the fix is only made for :
```
const v = useWatch({
    name: "bbb",
    control,
    defaultValue: "default data"
});
```

so for `setValue` you will have to convert `pathname`, `watch()` is working as expected because it triggers a re-render and running through the function.

**Comment by Taymindis** [comment]
Noted. I will implement in this way, assuming the end child is 2 level only. 

```jsx
function UseWatchNested({ name, defaultValue, isString = true, ...rest }) {
  const keynames = name.split('.');
  const k1 = keynames[0];
  const k2 = keynames[1];
  const v = {
    [k1]: useWatch({
      name: k1,
      defaultValue: k2 ? { [k2]: defaultValue } : defaultValue,
      ...rest
    })
  };
  const finalV = _.get(v, name);
  if (isString && typeof finalV !== 'string') {
    return null;
  }
  return finalV;
}

function MyLabelComponent(props) {
  const { register, control, unregister } = useFormContext();
  const { name = '' } = props;
  React.useEffect(() => {
    register({ name });
    return () => unregister(name); // unregister input after component unmount
  }, [register]);
  const v = UseWatchNested({ name, control, defaultValue: 'default value' });
  // console.log(name, v);
  return (
    <div style={{ wordWrap: 'break-word', color: 'black' }}>
      Use Watch:: {v}
    </div>
  );
}
```
