### ISSUE TITLE
onChange does not get triggered for form fields that are watched

### ISSUE THREAD

**Issue by mxshrestha** [react-hook-form/react-hook-form#1854]
**Describe the bug**
onChange event listener of form fields is not called when the form field is watched.

**To Reproduce**
Steps To reproduce:
1. Create a form with an input field with value attribute specified and onChange event handler registered
2. watch the input field
3. Change the value of the input field in the form 
Bug:
onChange event listener is not called.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-defaultvalues-od9z5
(Try changing firstname value)

**Expected behavior**
the onChange event listener is called 

**Screenshots**

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by bluebill1049** [comment]
you are mixing controlled with `register`. please read the doc and have correct usage.

**Comment by mxshrestha** [comment]
Thanks @bluebill1049 . That makes sense.
