### ISSUE TITLE
getValues("nested") returns default value rather than up-to-date value

### ISSUE THREAD

**Issue by aslupik** [react-hook-form/react-hook-form#1859]
**Describe the bug**
`getValues("nested")` returns the value passed in `defaultValues` rather than the current value.
Workaround: use `getValues({nest:true})["nested"]` instead.

e.g. if your structure is 
```
{ time: 
  { hour: number, minute: number } 
}
```

`getValues("time")` returns the initial value of time.hour and time.minute, not the current.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-get-form-values-2ottz?file=/src/index.js
2. Change the value in one of the fields
3. Click the button
4. Check console

**Expected behavior**
Both ways of getting the value should return the current value.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version: 83

**Comment by bluebill1049** [comment]
This expected behavior. 

```
getValues('fieldName') // get individual field input value
getValues({ nested: true })  //return entire form state but nested.
```

**Comment by aslupik** [comment]
I must say that this was surprising behavior to me and caused me quite a few hours of investigating before realizing what was going on. I would not have expected `getValues` to return stale values in any scenario.

Could you provide a rationale as to why `getValues("time")` would return stale values for nested fields?

**Comment by bluebill1049** [comment]
because there is no input named as `time`, it's not a lodash `get`.

**Comment by aslupik** [comment]
I see, at least that tells me when to get the entire state rather than rely on `getValues`. We have some pretty generic components that were getting the current value of fields as `getValues(path)`, but some of them had this issue and some didn't (depending on whether there were nested values or not). We'll just have to use the workaround instead since that works every time.

I think there's an argument to be made that if
 - I call getValues
 - it returns a value for a field
 - there's an up-to-date value for that field

Then it's a reasonable expectation that it would return that up-to-date value rather than a stale one. So if this is by design, I think there's an argument that it's a design bug. But I'll leave it to you.
