### ISSUE TITLE
onChange not firing on controlled input with failed validation

### ISSUE THREAD

**Issue by partyka1** [react-hook-form/react-hook-form#1860]
**Describe the bug**
Controlled inputs after failed validation don't fire onChange event.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-controlled-input-failed-validation-bug-zg0vz?file=/src/index.js (this is modified version to showcase an error of an example from your docs)
2. Fill input "Last Name"
3. Click Enter
4. Focus on "Last Name" input
5. Select all text and hit backspace

Text should be removed but it doesn't. 

If you remove all text hitting backspace, and try to write first character, it also doesn't fire. After first time bugs occurs, anytime if you are writing from 0-length string to 1-length string(or vice versa), onChange doesn't fire.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-controlled-input-failed-validation-bug-zg0vz?file=/src/index.js

**Expected behavior**
OnChange should fire, and input should represent actual state.

**Desktop:**
 - OS: macOS
 - Browser chrome, safari, opera; on firefox bug does not occur

**Comment by RRigueira** [comment]
+1 Having the same issue here.

**Comment by bluebill1049** [comment]
why are we mixing controlled with uncontrolled? Please read the doc on the get started page. 

- `<input ref={register} name="test" />` this is all you need for RHF
- if you need to work with controlled inputs. 
  1. use `Contoller`: https://react-hook-form.com/api#Controller
  2. custom register at useEffect and update value with `setValue`

**Comment by partyka1** [comment]
this is a use case for one of more complicated form in my app where I keep current state of inputs in MobX store, but want to have validation/submit flow processed by RHF, to be consistent with rest of the system, where forms are simpler and are handled by `Controller`

**Comment by bluebill1049** [comment]
then you should stick with `custom register`.

**Comment by bluebill1049** [comment]
or <input onChange={update to you store} ref={register} name="test" />

**Comment by partyka1** [comment]
That's how I'm doing, and that's how its done in the codesandbox I've(react state is used instead of MobX for demo purpose, but logic is the same). I've recorded video of the bug: first I input `luo`, submit, click cmd+a, backspace and text is not deleted, I try to write `luo` again but what I get is `luouo`
![RHF-error](https://user-images.githubusercontent.com/19314216/84554292-17955a00-ad0f-11ea-8147-a4e44889e81f.gif)

**Comment by bluebill1049** [comment]
`<input onChange={update to you store} ref={register} name="test" />`

please pay attention to above code snippet, it's uncontrolled.

<img width="440" alt="Screen Shot 2020-06-13 at 10 12 53 am" src="https://user-images.githubusercontent.com/10513364/84555096-73d39a80-ad5e-11ea-8674-604ee0c76f74.png">

**Comment by bluebill1049** [comment]
Take a look at my CSB: https://codesandbox.io/s/react-hook-form-controlled-input-failed-validation-bug-7ivnr?file=/src/index.js see if this make more sense.

**Comment by partyka1** [comment]
Thanks, 
read docs again, checked your demo and verified with my code, and it seems to be working. Docs don't make it clear that the place where you call `register` is tightly intertwined with controlled vs uncontrolled scenarios(I was sure just by supplying `value` and `onChange` it is considered controlled, as my custom controls where forwarding refs anyway). In my case moving `register` from `ref={register}` to inside `useEffect` solved the problem. 

**What can be done better?**
1. There is a check in `register` and warning is thrown if `ref.name` is not set on an input(useForm.ts#815), wouldn't it be possible to also throw ie `TypeError` if `ref.value`/`ref.onChange` is set when `register` is called from ref prop? If that configuration is unsupported/should never occur, it should throw an error, either statically checked, or runtime on dev. In my case/CSB demo wrong configuration manifested itself only in some cases, but mostly it was working fine.
2. `Controller` hides inside its implementation logic that could be useful while implementing your own controlled inputs, if it was exported/exposed in RHF API consistent UX could be provided across controlled/uncontrolled inputs.
3. If that's the case that you mustn't use register in `ref` if it's a controlled input, docs should clearly state that.

If I got anything wrong let me know, thanks!

**Comment by bluebill1049** [comment]
Thanks for your feedback. I am happy to see PR against those changes towards the doc. make sure you check out `v6` branch. Thanks. again your feedback is noted and appreciated.

**Comment by workteam123** [comment]
@partyka1 is there a CSB with your solution? I am using Controller as Material-ui Textfield.  I have removed the ref={registered} from textfield and created the ref in useEffect (using useHookWithRefCallback). I think I understand your solution but I still cannot get onChange to fire. Many thanks

**Comment by ejmendozao** [comment]
same problem

**Comment by mjza** [comment]
I had exactly same problem. I wanted to show a value from state and and also be able to update it when user change the value. just use `defaultValue` instead of `value`:

```js
         <input
            onChange={e => update(e.target.value)}
            defaultValue={state}
            name="lastName"
            placeholder="luo"
            ref={register({ required: true })}
          />
```

It works for me.

**Comment by mjza** [comment]
@partyka1 Can you share how you moved register to useEffect?

**Comment by mjza** [comment]
I found a work around for this issue. 

The key feature in my solution is to define the following 2 functions:

```js
onInputChange(event) {
    const { name, value } = event.target;
    let { formData } = this.state;
    formData[name] = value;
    this.setState(formData);
  }

 onInputValueChange(name, value) {
    let { formData } = this.state;
    formData[name] = value;
    this.setState(formData);
  }
```
One of the is normal `onChange` handler, and one other is for when the validation is running. In this case we need to call the second function each time that we do the validation. For this purpose we need to define a custom validation for the input. :

```
<input
      name="phone_number"
      ref={register({
                  required: false,
                  validate: (value) => {
                       const regex = new RegExp("^$|^\\+\\d{3,18}$", "gm");
                       const result = regex.test(value);
                       this.onInputValueChange("phone_number", value);
                          return result;
                        },
                  })}
       value={formData.phone_number}
       onChange={this.onInputChange}
/>
```

**Comment by ganeshGITTECH171** [comment]
@mjza , your solution works for me

**Comment by mjza** [comment]
@ganeshGITTECH171 It works only in version 6, in version 7 it does not work.

**Comment by mjza** [comment]
I upgraded to version 7 and the validation function does not receive the lates value, 

```jsx
<input
                      name="phone_number"
                      type="text"                      
                      {...register("phone_number", {
                        valueAsNumber: false,
                        validate: (value) => {
                          console.log("***" + value);
                          const regex = new RegExp("^$|^\\+\\d{3,18}$", "gm");
                          const result = regex.test(value);
                          this.onInputValueChange("phone_number", value);
                          return result;
                        },
                      })}
                      maxLength="19"
                      value={formData.phone_number}
                      onChange={this.onInputChange}
                    />
```
While `formData.phone_number` has value and it is shown in the view, but when I try to validate the form, what would be passed to the `validate` function in undefined. 

It happened in version "^7.6.2"

@bluebill1049, the code was working in version 6, why does it pass undefined to validate function now?

**Comment by mjza** [comment]
@bluebill1049 @partyka1 Can you reopen the issue? I didn't make a new issue as they are related.

**Comment by ganeshGITTECH171** [comment]
Yes @mjza Version 7 will not support this, even version 7.0.0 to latest is not working at all, I have try all versions.

**Comment by mjza** [comment]
@ganeshGITTECH171 Yes, I introduced new syntax based on the following page:

https://react-hook-form.com/migrate-v6-to-v7/

on the paper it must work, the problem is the value does not pass to the validate function, if the focus left the input, then the value would be updated and validate function will receive the correct value.

**Comment by mjza** [comment]
@bluebill1049 if we use hook the value is passed correctly, however, if we use class `undefined` would be passed. 

[https://codesandbox.io/s/react-hook-form-controlled-input-failed-validation-bug-forked-pk1h0?file=/src/index.js](https://codesandbox.io/s/react-hook-form-controlled-input-failed-validation-bug-forked-pk1h0?file=/src/index.js)

**Comment by mjza** [comment]
@bluebill1049 Strange! In sandbox I couldn't reproduce the error. 

https://codesandbox.io/s/react-hook-form-controlled-input-failed-validation-bug-forked-gxbh5?file=/src/index.js

I will investigate more and let you know.

**Comment by tonytkh** [comment]
Hi @mjza, I tried your workaround on V6. 

The problem with the input from 0-length is solved, but deleting the value from 1-length/Select all by hitting backspace still having problem. 

Do you have any idea ?

**Comment by mjza** [comment]
@tonytkh 

Here is my work around for version 7. 

https://codesandbox.io/s/agitated-chaplygin-mfk4x?file=/src/App.js

I don't recommend to use the old version as you will lose the new updates

**Comment by tonytkh** [comment]
@mjza 
Thanks for your code for version 7. 

Unfortunately, my project is still using version 6 and not going to upgrade it. 

I only able to fix the issue on first input, the issue still exist for the deleting....

**Comment by mjza** [comment]
@tonytkh

to be honest until last 2 weeks that I used version 6 I had no problem with the code that I have suggested former.

**Comment by tonytkh** [comment]
@mjza 
Yes, thanks for your code, it is a big help to me. 
Just that I'm curious why having problem on the delete..

Here is my observation:
1) enter first character after error message > it fire both **onInputChange** and **onInputValueChange**
2) delete last character/ all text with backspace> not firing both **onInputChange** and **onInputValueChange**
3) hit backspace again > it fire **onInputChange** only
