### ISSUE TITLE
Accessing validationSchema variable via the form instance

### ISSUE THREAD

**Issue by omerman** [react-hook-form/react-hook-form#1863]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't access the validation schema Im supplying when inside a component, using the form instance.

**Describe the solution you'd like**
I think the schema variable should be on the instance.

**Describe alternatives you've considered**
If not on the instance, maybe a possible context for it.

**Additional context**
![image](https://user-images.githubusercontent.com/6780529/84578246-445b7700-adcc-11ea-8fab-b76bd4ce45f3.png)

Thanks in advance, awesome lib!

**Comment by bluebill1049** [comment]
hey @omerman you should check out `validationResolver` if you need to have context, in fact in v6 which is going to release soon we are going forward with `resolver`.

**Comment by omerman** [comment]
Ok cool I'll check it out thank you!
