### ISSUE TITLE
trigger validation is not scrolling to the error

### ISSUE THREAD

**Issue by Muneem** [react-hook-form/react-hook-form#1865]
**Describe the bug**
triggerValidation is not scrolling to the error. If there is an error and we do trigger validation then an error is shown but it should be scrolled to that error

**To Reproduce**
https://codesandbox.io/s/react-hook-form-errors-j0695?file=/src/index.js
1) click on the button
2) Scroll to top it will show error

**Expected behavior**
It should scroll to error just as it is doing when user submits the form

**Comment by bluebill1049** [comment]
> **Describe the bug**
> triggerValidation is not scrolling to the error. If there is an error and we do trigger validation then an error is shown but it should be scrolled to that error
> 
> **To Reproduce**
> https://codesandbox.io/s/react-hook-form-errors-j0695?file=/src/index.js
> 
> 1. click on the button
> 2. Scroll to top it will show error
> 
> **Expected behavior**
> It should scroll to error just as it is doing when user submits the form

we only focus on an error at submitting. This is not the expected behavior. we didn't document such behavior as well.

**Comment by Muneem** [comment]
can we add that scrolling feature? Because i think so it should be added as there are many cases where user have to trigger validation and scroll should be there

**Comment by bluebill1049** [comment]
Don't think so, `trigger` is for trigger validation only. Focus on an error input should only occur at submission.

**Comment by bluebill1049** [comment]
going to close this issue now as we don't have a plan to support this feature. thanks for reporting tho.
