### ISSUE TITLE
useFieldArray, fields array can't have default data.

### ISSUE THREAD

**Issue by cmnstmntmn** [react-hook-form/react-hook-form#1870]
I have two components as part of a form

1. a parent component that is fetching some sort of data
2. and a child component that fetching some other data 

here's an example
https://codesandbox.io/s/react-hook-form-usefieldarray-template-4k4ti?file=/src/index.js:0-1554

the think is these comps are async, so i can't have default values all at once.

**Comment by bluebill1049** [comment]
you will have to use `reset` at `useEffect`

**Comment by cmnstmntmn** [comment]
@bluebill1049 hmm, i don't think i'm following you ..
i added `reset` https://codesandbox.io/s/react-hook-form-usefieldarray-template-4k4ti?file=/src/index.js

is reseting the form, but the fields still not appear.

**Comment by bluebill1049** [comment]
i mean `reset` with values. just like how `reset(values)` update all the default values.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#reset

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-usefieldarray-template-mxmuw

**Comment by cmnstmntmn** [comment]
@bluebill1049 right, but is there a way to reset only those fields not the entire state.
in you example `location` field is reseted

**Comment by bluebill1049** [comment]
combine with getValues()

**Comment by TonyVeigel** [comment]
@bluebill1049 

How do you propose using reset when firing off multiple calls at the same time and updating the default state? For instance:
`{ 
    name: "a"
    products: [] <-- async call
},
{ 
    name: "b"
    products: [] <-- async call
},
{ 
    name: "c"
    products: [] <-- async call
}`

You can run in to a race condition when setting the state via reset for multiple simultaneous calls. Our requirement is to load the form first and then load the products. So we make the call to get the initial form data, and then map through the fields and make calls to get the products. It's an anti pattern to make one call at a time, set the products, make the next call, etc... Unless I am missing something? Maybe setValue could contain a flag to update default state for said property.
