### ISSUE TITLE
Form validating and attempting submit on any button press, not just of type="submit"

### ISSUE THREAD

**Issue by StevenHarlow** [react-hook-form/react-hook-form#1873]
**Describe the bug**
When I click on a `<button>` from within the form tags it validates the inputs and attempts submit even if the type is not "submit" and the mode is set to default (or explicitly set) to 'onSubmit'

**To Reproduce**
Build a form with an extra `<button>` inside the form, without setting the type

**Expected behavior**
The form to not submit on a button click that isn't of the "submit" type

**Desktop (please complete the following information):**
- OS: macOS Catalina
- Chrome

**Comment by bluebill1049** [comment]
That's HTML standard and not related to this lib.
