### ISSUE TITLE
calling setError() on submit shows error, but is reset as element loses focus

### ISSUE THREAD

**Issue by 2DSharp** [react-hook-form/react-hook-form#1881]
**Describe the bug**
As I was trying to set server-side errors using `setError`, I tried setting it from `onSubmit`, however 
it works as expected in v4.0.0 (https://codesandbox.io/s/o7rxyym3q5?file=/src/index.js:429-850), but in the latest 5.7.2 version, the error is lost as soon as the element loses focus.

I am having to revert to 4.0.0 for getting proper error persistence behavior.

**To Reproduce**
1. Set the error on handleSubmit:
```
const onSubmit = handleSubmit(({username}) => {
        setError("username", "notMatch", "please choose a different username");

    });
```
2. Set the input field with a secondary client-side validation rule:
```
<input
            name="username"
            placeholder="username"
            ref={register({
              required: { value: true, message: "This field is required" }
            })}
  />
          {errors.username && <p>{errors.username.message}</p>}
```

**Codesandbox link (Required)**
Include a codesandox will help us to investigate the issue quicker.
[Codesandbox](https://codesandbox.io/s/vibrant-sea-hukji?file=/src/App.tsx)

**Expected behavior**
The error should persist as long as there is no change in the input value.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version 70.0.1

**Additional context**
This probably works with version 4.0.0, please check if it can be made to work with `5.7.2` with some workarounds.

**Comment by bluebill1049** [comment]
`setError` does not persist error by design, `error` should always against validation `rules`. the method `setError` was made for set error manually in the `handleSubmit`.  if we make setError persist, then user will have to manually remove error during submit, which is not ideal.

eg
```
onSubmit(() => {
  setError('test', 'test');
})

<input name="test" ref={register({ required: true }} />
```

which error should persist? it's conflicting and confusing.

**conclusion**  setError is what we documentamend as:
 
<img width="938" alt="Screen Shot 2020-06-17 at 8 35 24 am" src="https://user-images.githubusercontent.com/10513364/84834753-7e9b7180-b075-11ea-9801-a0a6f91b27ff.png">

**Comment by 2DSharp** [comment]
That's fair, but I don't really understand the point of losing the error message as soon as the field loses focus, even though it's violating only the server validation. Care to explain why that can't be solved? @bluebill1049

**Comment by 2DSharp** [comment]
Also can you show an example how the server side errors should be shown otherwise?

**Comment by bluebill1049** [comment]
because you are setError on an existing `field` and the reValidate mode will kick in and try to validate the input again, which leads to no error, and hence `error` is removed. I will do the following 

`setError('serverError', 'xxxx')`  so it's not associated to any of the field.

**Comment by bluebill1049** [comment]
options 2, you can add the server validation into the field and combined with `formState` `submitted` and validate against your API.

**Comment by bluebill1049** [comment]
we all addressing this issue: https://github.com/react-hook-form/react-hook-form/pull/1907 let me know your thoughts.

**Comment by alexbrebu** [comment]
Any workaround for this issue?

**Comment by NikolaStanisavljevic** [comment]
I'm looking for one too.
Have you found any maybe @alexbrebu  ?

**Comment by alexbrebu** [comment]
It worked for me in the end. The setError() does not work with 'onSubmit' mode so I needed to update my configuration when using useForm(). I used something like this:

```js
const { } = useForm<T>({
    resolver: yupResolver(validationSchema),
    defaultValues,
    mode: 'onChange',
    reValidateMode: 'onChange',
    criteriaMode: 'firstError',
    shouldFocusError: true,
    shouldUnregister: true,
  });
```

Then, when the response comes from the backend (where I do deeper validation on data), I do something like this:
```js
     if (e instanceof HttpUnprocessableEntity) {
        const { errorPayload } = e;
        if (errorPayload) {
          const { errors: backendErrors } = errorPayload.content as BackendContent;
          Object.keys(e).forEach((key) => {
            if (backendErrors[key]) {
              setError(key, backendErrors[key]);
            }
          });
        }
      }
```

So all the magic is here:

```js
              setError(key, backendErrors[key]);
```

P.S.: to have less processing in the frontend, I returned errors under the same format as `yup`

**Comment by alexbrebu** [comment]
@NikolaStanisavljevic

**Comment by NikolaStanisavljevic** [comment]
@alexbrebu That's great solution. Thank you very much for your help.
