### ISSUE TITLE
v6 useWatch nested fields feature suggestions / queries / request

### ISSUE THREAD

**Issue by alexbakerdev** [react-hook-form/react-hook-form#1888]
**Is your feature request related to a problem? Please describe.**
I've been using `useWatch`in a relatively complex form for the last week involving previewing combinations of values, and subsequent dropdown options based on previous inputs. Some of the values in the form are nested objects that are dynamically added and removed.

Here are a few situations that have caught me out:

1. useWatch doesn't get the initial value from the form, it just returns the user defined defaultValue, even if there is a defined value in the form
2. changing the name value passed to useWatch doesn't change what the watcher watches. ie

```
// if colorName changes the colorValue won't match the newly named field.
const colorValue = useWatch({ name: `color.${colorName}.value` ])
```
    
3. registering and unregistering of nested paths doesn't trigger updates on watches of their ancestors.
4. setting values to undefined doesn't tigger a watcher

**Describe the solution you'd like**
I've had a go at fixing each of these things and was wondeirng if they are something react-hook-form wants.

1. Ideally the watch returns the computed value of the field if it exists, without waiting for a change.
2. useWatch tears down its watchers and sets up new ones when its parameter changes, and immediately returns the correct value for the new watched path.

I've got a [small patch](https://github.com/alexbakerdev/react-hook-form/commit/b19a7f1324dd210c50a91401d121f7c424e9b985) that implements a non optimal version of this.

It causes an extra rerender by setting state in a useEffect. I think it could be refactored to do the work in the use effect directly in the hook using some refs. Which will avoid that extra render allowing the hook to return the initial getValues.

3. registering and unregistering fields should update watchers. Implementing this involved invoking renderWatchedInputs on register and unregister, and searching a bunch of field paths in renderWatchedInputs [like this](https://github.com/alexbakerdev/react-hook-form/commit/122e517d46727262bfb1d69a229d3f745e0b9e7a)

    - Implementing this made me wonder if it's sufficient for `watchFieldsHookRef[id]` to just keep track of the provided field names. This would mean [not adding it to that set when children are discovered](https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/assignWatchFields.ts#L37) since my change means those fields have to be searched twice (once for an exact match, once for a starts with).

4. This problem is least clear to me in terms of what the expected behaviour should be. Particularly how it interacts with unregistering nested fields. My implementation basically just deletes a bunch of code around handling an undefined value, it works for my use case but I'm not sure about RHF intentions around this https://github.com/alexbakerdev/react-hook-form/commit/3506c091a8dd9df7e54130e2110c780a8d969012.

I've grouped all these ideas together as these changes (with the possible exception of 4.) are my expected behaviour for watches of nested values.

Anyway, hope these rambling thoughts and ideas are helpful and am eager to dissect them further. I'd also be happy to contribute by refining my patches, adding tests and submitting some PRs if this is the direction RHF wants to go.

**Comment by bluebill1049** [comment]
Thanks @alexbakerdev i will take a look at those feedbacks. 👍

**Comment by bluebill1049** [comment]
I will address one point at a time, so be patient, please :) 

- useWatch doesn't get the initial value from the form, it just returns the user-defined defaultValue, even if there is a defined value in the form

`watch` or `useWatch` share the same functionality, which renders happens after the function invoke, and RHF is based on uncontrolled input, so reading input value is trigger before the render, so I would recommend using `defaultValue` or `defautValues`

**Comment by bluebill1049** [comment]
2️⃣ changing the name value passed to useWatch doesn't change what the watcher watches. ie

happy to see a PR if you have time :) we can release this post V6 as well.

**Comment by bluebill1049** [comment]
3️⃣ registering and unregistering of nested paths doesn't trigger updates on watches of their ancestors.

Can you give more detail on this? Ideally, we don't want to return undefined for input which is also associated with point 4.
In fact, we have a new feature: `shouldUnregister` which behave like Controlled input and input will not get `unregister` after unmount.

**Comment by bluebill1049** [comment]
4️⃣ setting values to undefined doesn't tigger a watcher

I don't think we should set `value` to undefined in the first place, as you know RHF tries to align with native input so it's better to stay away with `undefined` also it's a consistent behave across the lib.

**Comment by alexbakerdev** [comment]
Hey, thanks for getting back to me so quickly. I've tried to hack together a super conceited demo that demonstrates points 1️⃣ , 3️⃣, 4️⃣ 

[using rc4](https://codesandbox.io/s/rhf-watch-examples-v6rc4-zjksd)
[using my fork of rhf](https://codesandbox.io/s/rhf-watch-examples-xanderite-fork-decqy?file=/src/App.tsx)

These are identical other than using different versions of RHF, I realise that the example is a bit different to the docs examples but its mainly to illustrate my stumbling blocks when using dynamic nested values.

Mainly consists of a couple of fields with nested field names, and a dynamically registered and unregistered one. Then a couple of preview components that watch those values.

I'll follow you're lead and respond to each point separately.

**Comment by alexbakerdev** [comment]
1️⃣ I guess this makes sense, however it seems like in the example above there is some unexpected behaviour caused by this, there's no way for the preview components to show the fields that have been registered because of that render. Although I may be misunderstanding how to provide the default value to the watch? 

Perhaps the behaviour in my fork can be invoked with an optional parameter? or maybe a separate hook?

**Comment by alexbakerdev** [comment]
3️⃣ In the demo you can register and unregister a nested field dynamically. In my fork the watches of the ancestor 'colors' and the whole state are triggered by this change*. 

_*(I've actually just noticed that my unregister watch changes don't work in the demo's case, but I don't think it would be hard to add this to RHF)_

**Comment by alexbakerdev** [comment]
4️⃣ Whilst it makes total sense about avoiding undefined with native inputs, it sort of seems like the only way to deal with values that are objects, either dynamic nested values or more complex values (such as an object). 

I also understand not wanting to handle the latter case, however I've found the ability to use objects as values convenient.

**Comment by alexbakerdev** [comment]
One other consideration with 1️⃣  and 2️⃣  if the useWatch parameter changes, should it return the new value immediately? because if it doesn't then that seems like unexepected behaviour, but if it does its consistent with the first invocation of the hook. Again makes me think the solution might be another similar hook?

**Comment by bluebill1049** [comment]
> 1️⃣ I guess this makes sense, however it seems like in the example above there is some unexpected behaviour caused by this, there's no way for the preview components to show the fields that have been registered because of that render. Although I may be misunderstanding how to provide the default value to the watch?
> 
> Perhaps the behaviour in my fork can be invoked with an optional parameter? or maybe a separate hook? or... this is something you don't want, which is ok too.

The workaround is to provide `defaultValues` at useForm instead of inline `defaultValue`.

**Comment by bluebill1049** [comment]
> 3️⃣ In the demo you can register and unregister a nested field dynamically. In my fork the watches of the ancestor 'colors' and the whole state are triggered by this change*.
> 
> _*(I've actually just noticed that my unregister watch changes don't work in the demo's case, but I don't think it would be hard to add this to RHF)_

I guess this should apply to `watch` API as well, I believe we don't have that behavior for `watch` as well, Yes, if we can make it both work with `watch` and `useWatch` (without introducing too much logic and code, I do care about lib size quite a lot).

**Comment by bluebill1049** [comment]
> 4️⃣ Whilst it makes total sense about avoiding undefined with native inputs, it sort of seems like the only way to deal with values that are objects, either dynamic nested values or more complex values (such as an object).
> 
> I also understand not wanting to handle the latter case, however I've found the ability to use objects as values convenient.

it's a tradeoff the lib has to absorb. Can you work with `{}` with `object` at least it's empty and not empty?

**Comment by bluebill1049** [comment]
> Hey, thanks for getting back to me so quickly. I've tried to hack together a super contrived demo that demonstrates points 1️⃣ , 3️⃣, 4️⃣
> 
> [using rc4](https://codesandbox.io/s/rhf-watch-examples-v6rc4-zjksd)
> [using my fork of rhf](https://codesandbox.io/s/rhf-watch-examples-xanderite-fork-decqy?file=/src/App.tsx)
> 
> These are identical other than using different versions of RHF, I realise that the example is a bit different to the docs examples but its mainly to illustrate my stumbling blocks when using dynamic nested values.
> 
> Mainly consists of a couple of fields with nested field names, and a dynamically registered and unregistered one. Then a couple of preview components that watch those values.
> 
> I'll follow you're lead and respond to each point separately.

Would you be able to send a PR with this?

**Comment by bluebill1049** [comment]
> One other consideration with 1️⃣ and 2️⃣ if the useWatch parameter changes, should it return the new value immediately? because
> 
> * if it returns the value from the previous watch then that seems like unexepected behaviour, but
> * if it does return the new value its kind of inconsistent with the first invocation of the hook.
> 
> Again makes me think the solution might be another similar hook?

again this should be aligned with `watch` API, if we can make this work without too much logic or code <3.

**Comment by alexbakerdev** [comment]
Hey, ok, so sorry for the delay! (Also thanks again for your responses.) 

> The workaround is to provide defaultValues at useForm instead of inline defaultValue.

I'm struggling to solve this problem using default value. If I provide a default value on first render of the form the fourth color is defined when it isn't toggled on. If I change the default value when [toggling the fourth color](https://codesandbox.io/s/rhf-initial-value-logic-ry5x1?file=/src/App.tsx) it doesn't seem to update the default? 

Also I think this is even harder to deal with if the key name for color was dynamic? something `colors.${colorName}.value`

Luckily, I think the implementation of returning the initial value is extremely simple in the useWatch api, haven't looked deeply into the watch api though.

https://github.com/react-hook-form/react-hook-form/blob/3b5bd4107c420281a4689e1f40e8ccbee394690b/src/useWatch.ts#L65

to my patch
https://github.com/alexbakerdev/react-hook-form/blob/e58c9deb0a399c74cdfa3be391c69570dd0710f0/src/useWatch.ts#L72-L73

Though there is a way to optimise rerenders, which I might have a go at tomorrow at work.

**Comment by alexbakerdev** [comment]
> it's a tradeoff the lib has to absorb. Can you work with `{}` with `object` at least it's empty and not empty?

I agree this does sound like a good trade off, and I will do this in the future.

**Comment by keiya01** [comment]
Thank you very much for sending some issues. 

I think your issues can resolve by improving bugs that default values are not returned from ‘useWatch’.

To resolve this problem, your solution is make sense. But this solution occurs extra re-render. I think the way of resolving this problem just return value with ‘defaultValuesRef’ inside ‘control’.

**Comment by bluebill1049** [comment]
hi @alexbakerdev, any chance we could have a conclusion for this issue? I prefer to move on and leave the issue to keep hanging. I would tag this as a feature request and waiting for upvote and stash on our project board.

**Comment by alexbakerdev** [comment]
Hey sorry for the slow replies, I've been trying to get a working version of my suggested changes together into a PR. To be submitted soon. Tagging as a feature request sounds great, as my current fork is good enough for an interim solution.

**Comment by bluebill1049** [comment]
> Hey sorry for the slow replies, I've been trying to get a working version of my suggested changes together into a PR. To be submitted soon. Tagging as a feature request sounds great, as my current fork is good enough for an interim solution.

no worries, this is pinned on the project board, send the PR whenever you are ready. @keiya01 will take care of the reviewing and etc.
