### ISSUE TITLE
Validation skips a keyboard entry

### ISSUE THREAD

**Issue by vineethvijayan** [react-hook-form/react-hook-form#1892]
**Describe the bug**
I have an input 
`<input
                  type="text"
                  className="form-control"
                  id="points"
                  name="points"
                  placeholder='Points'
                  autoComplete="off"
                  onChange={(e) => setPointValue(e.target.value)}
                  value={pointValue}
                  ref={register({ required: true, pattern: /^\d{2,4}$/ })}
                ></input>`

Pretty standard input where it should only allow numbers ranging between 10 & 999.
This works fine but if the validation is triggered onSubmit then some of the keystrokes are not appearing in the input text field.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-useform-template-2d6u0
2. Click on 'Submit'
3. Error will trigger
4. Try to type 1234567890
5. it will only print 2456890 its missing 1,3,7

**Codesandbox link (Required)**
Include a codesandox will help us to investigate the issue quicker.
https://codesandbox.io/s/react-hook-form-useform-template-2d6u0

**Expected behavior**
I expect input field does not scrub any inputs I make. It should type 1234567890

**Screenshots**
![Screenshot 2020-06-17 at 3 17 48 PM](https://user-images.githubusercontent.com/6049347/84883047-b8886a00-b0ad-11ea-9aa4-75ddb804a003.png)

**Comment by bluebill1049** [comment]
Please read the doc, you are mixing controlled with uncontrolled (native) input

```
<input
        type="text"
        name="points"
        placeholder="Points"
        autoComplete="off"
        // onChange={e => setPointValue(e.target.value)} // definitely dont' need onChange
        value={pointValue} // why you need value
        ref={register({ required: true, pattern: /^\d{2,4}$/ })}
      />
`

**Comment by vineethvijayan** [comment]
I use the same form for adding the editing, so when I edit the form I want the value to be set.

**Comment by vineethvijayan** [comment]
@bluebill1049 there is a prop defaultValue that solves my issue, Thanks for the quick response.

**Comment by bluebill1049** [comment]
That's it! please spend sometimes in the doc. there is a lot of useful information. eg: you can use `useForm({ defaultVlaues: xxx })` as well

**Comment by vineethvijayan** [comment]
This poses a different issue I do have a dropdown and onChange I need to set the input value of the input text field. This used to work because I was using the state. Now since I am setting the default value this never changes on onChange of the dropdown (Once I do an initial edit on the text field)
