### ISSUE TITLE
Field value gets removed on validation

### ISSUE THREAD

**Issue by Alain00** [react-hook-form/react-hook-form#1895]
**Describe the bug**
When the form is submited after the validation the values gets removed one by one on each submit

**To Reproduce**
1. Fill the form with any values
2. Click on "Agregar"

**Codesandbox link (Required)**
https://snack.expo.io/0DmQB!XIO

**Expected behavior**
The validation process have finish with or errors or successfully, any way, the values must ramain intact

**Comment by bluebill1049** [comment]
![Uploading Screen Shot 2020-06-18 at 8.57.34 am.png…]()

**Comment by bluebill1049** [comment]
<img width="306" alt="Screen Shot 2020-06-18 at 8 58 02 am" src="https://user-images.githubusercontent.com/10513364/84958982-d1daf600-b141-11ea-8701-5033fe21b579.png">

**Comment by Alain00** [comment]
Yes, but why it says that is required if the value is there? 
if u log form.getValues on every re render you can see that the values are getting setted, but in the moment i call form.handleSubmit these values gets removed one by one and the validation fail.

**Comment by bluebill1049** [comment]
> @bluebill1049 yes, but why it says that is required if the value is there?
> if u log form.getValues on every re render you can see that the values are getting setted, but in the moment i call form.handleSubmit these values gets removed one by one and the validation fail.

// <TextInput ref={ref} {...props} /> 
i don't think TextInput expose `ref` with its value

Take a look this section: https://react-hook-form.com/get-started#ReactNative

**Comment by Alain00** [comment]
> > @bluebill1049 yes, but why it says that is required if the value is there?
> > if u log form.getValues on every re render you can see that the values are getting setted, but in the moment i call form.handleSubmit these values gets removed one by one and the validation fail.
> 
> // <TextInput ref={ref} {...props} />
> i don't think TextInput expose `ref` with its value
> 
> Take a look this section: https://react-hook-form.com/get-started#ReactNative

I'm not trying to assing a ref, i just call the register method inside a ref function, i've test it like in https://react-hook-form.com/get-started#ReactNative for custom register

```
React.useEffect(()=>{
      children.forEach(child => {
        register(
          { name: child.props.name },
          validation[child.props.name]
        );
      })
    }, [register, children, validation])
```

and got exactly the same result, when the form is submited the values gets removed, i've not tested yet with controller component

**Comment by bluebill1049** [comment]
ok if you using custom register, then you need to update the value right? `setValue` https://react-hook-form.com/api#setValue

**Comment by Alain00** [comment]
I'm updating the value, this is the code:
```
onChangeText: (v: string) => {
      setValue(child.props.name, v, true)
 }
```
Is in the file MyForm.js where all the MyInput components gets rebuilded with all the props needed to work with the form

**Comment by Alain00** [comment]
Please reopen the issue

**Comment by bluebill1049** [comment]
can you follow what's in the doc example tho? i am confused with the issue here.

**Comment by bluebill1049** [comment]
perhaps have a read this article as well, which maybe helpful: https://elazizi.com/forms-in-react-native-the-right-way

**Comment by Alain00** [comment]
I'd know what i've missing, maybe its not a problem with the lib, but the snack in the article have the same issue, check here https://snack.expo.io/@yjose/form-in-react-native,-the-right-way!-

**Comment by bluebill1049** [comment]
what's the problem? that's my missing part. This is your title: Field value gets removed on validation? so field value get removed each submit?

**Comment by Alain00** [comment]
Yes, imagine this are the form values:
```
{
  firstname: "jhon",
  lastname: "foo",
  age: 24
}
```
after the first call to `handleSubmit` the form values are:
```
{
  firstname: undefined, //so it's get undefined and the validation set an error if the field is required
  lastname: "foo",
  age: 24
}
```
after the second call to `handleSubmit`:
```
{
  firstname: undefined,
  lastname: undefined,
  age: 24
}
```
And so on

**Comment by bluebill1049** [comment]
<img width="1429" alt="Screen Shot 2020-06-19 at 8 53 27 am" src="https://user-images.githubusercontent.com/10513364/85079542-690b8080-b20a-11ea-8667-9725500cfcd9.png">

This is a V6 expo snack i can't reproduce the problem: https://snack.expo.io/@bluebill1049/react-hook-form-v6

**Comment by bluebill1049** [comment]
wait, I think know the reason why! if you using the custom register, please register at `useEffect()`

**Comment by Alain00** [comment]
The example in the docs works fine. Maybe it just happens by passing the useForm variables to another component and using it deeply, perhaps something with the rerender

**Comment by Alain00** [comment]
> wait, I think know the reason why! if you using the custom register, please register at `useEffect()`

yes i've already tested that, and no luck

**Comment by bluebill1049** [comment]
ok that's really strange, can you try this version `v6.0.0-rc.4`

**Comment by Alain00** [comment]
same result with the version `v6.0.0-rc.4`, i'm using now the `Controller` component and works like a charm
