### ISSUE TITLE
Request for typing on Controller name field

### ISSUE THREAD

**Issue by atwalg2** [react-hook-form/react-hook-form#1897]
**Is your feature request related to a problem? Please describe.**

This can likely be labeled an enhancement
Use Case: React Native using Typescript

Currently there is no nice way of ensuring the name properties in the form controller match the Form interface. I've used something like this previously on another form library (my own), and thought that it would be a nice addition to this library.

```
interface FormData {
  firstName?: string;
  lastName?: string;
}
export default function App() {
  const {control, handleSubmit, errors, triggerValidation} = useForm<FormData>();
  return (
    <View>
      <Controller
        as={TextInput}
        control={control}
        name="firstName" 
        onChange={(args) => args[0].nativeEvent.text}
        defaultValue=""
      />
```
**Describe the solution you'd like**
I would like to have it so I get code completion on the "name" property
This type could be inferred via the control={control} property which can already be assigned an interface for the form.

**Describe alternatives you've considered**
Wrapping all form values in a function that enforces the types

**Comment by bluebill1049** [comment]
It's working in progress: https://github.com/react-hook-form/typed-field
