### ISSUE TITLE
[SPIKE] Possibly simplify the API using form elements api

### ISSUE THREAD

**Issue by stramel** [react-hook-form/react-hook-form#190]
**Is your feature request related to a problem? Please describe.**
More of a research task into using the HTMLFormElement.elements API to handle the references. https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/elements

**Describe the solution you'd like**
We might be able to simplify by requiring a `ref` only to the `form` element. And adding additional `ref`s only where necessary. This _may_ help with maintaining a list of current inputs instead of our manual list of references.

**Additional context**
Just food for thought. Hoping to get your input @bluebill1049 and @barrymay

**Comment by bluebill1049** [comment]
oh yea, definitely will be looking into that

**Comment by bluebill1049** [comment]
we can auto collect any native input values from the form which have basic native validation.

```
<form ref={register}>
  <input required name="test" />
  <input max={2} name="test1" />
  <input name="test2" ref={register({ validate: () => {} })} />
</form>
```

**Comment by barrymay** [comment]
I was thinking of the same thing, since custom form components are important.  Maybe having a special linking reference in the custom component can just tie it in into the main form?

**Comment by stramel** [comment]
Hmmm, yeah, seems like it really falls apart on stuff like react-select. I'm not sure it is feasible with some of these custom controls.

**Comment by bluebill1049** [comment]
yea @stramel that was my only concern :)

**Comment by stramel** [comment]
I'm going to close this for now then. Thanks for taking a look!
