### ISSUE TITLE
onBlur is not triggered on controlled input field

### ISSUE THREAD

**Issue by Atralbus** [react-hook-form/react-hook-form#1901]
**Describe the bug**
`onBlur` function is not being called inside the field wrapped with Controller.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-controller-onblur-not-called-6qmzu
2. Type something on the input field.
3. Click outside to trigger `onBlur`.
4. No log in the console.

**Codesandbox link**
[![Edit React Hook Form - Controller onBlur not called](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-hook-form-controller-onblur-not-called-6qmzu?fontsize=14&hidenavigation=1&theme=dark)

**Expected behavior**
`onBlur` function should be called and we should be able to see the input in the console.

**Desktop:**
 - macOS Catalina
 - Chrome
 - v83

**Additional context**
This issue starts with the v5.6.3, if you switch to v5.6.2 in the codesandbox you can see that the `onBlur` is called.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-controller-onblur-not-called-3wk9y?file=/src/index.js

**Comment by Atralbus** [comment]
I didn't put it in the example but I want to trigger `onChange` inside the `onBlur`. In original `Creatable` component, new values only appended if the user presses <kbd>Enter</kbd>, I also want to be able to append the value when `onBlur` is triggered.

```typescript
onBlur={e => {
  const { value } = e.target
  if (value) {
    const prevValue = value || []
    onChange && onChange([...prevValue, value], {})
  }
}}
```

I was doing it by calling the `onChange` method passed by `Controller` inside a custom component. How can we achieve the same behaviour if we pass `onBlur` to Controller?

**Comment by bluebill1049** [comment]
you will need to wait for v6 which has render props. you can try it out with `v6.0.0-rc4`

```
<Controller
  control={control} 
  name="test" 
  render(({ onChange, onBlur, value }) => (
    <Input 
      onTextChange={onChange} 
      onTextBlur={onBlur} 
      textValue={value} 
    />
  ))
/>
```
