### ISSUE TITLE
Add ability to watch form values without re-rendering, supplying with callback for changes.

### ISSUE THREAD

**Issue by omerman** [react-hook-form/react-hook-form#1905]
**Is your feature request related to a problem? Please describe.**
Currently there is a watch method that triggers a re-render once values change,
but sometimes I dont need a re-render, I just want to do something with the watched values,
like save them to the server or something like that.

**Describe the solution you'd like**

I think there should be an additional functionality to the good old watch:
We will have something like this:
```
// The component scope is never re-rendered by useSpy's hook.
useSpy(myFormInstance, ['field1', 'field2'], ([field1Value, field2Value]) => {
// this function is called once watched field values changes.
});
```
The callback we supply to `useSpy` will be triggered for each change, the component will never re-render by the hook.

**Describe alternatives you've considered**
Currently I created a `FormSpy` component that always returns null and accepts a callback.
but it's a lame solution in comparison to the solution I'm suggesting

Again, best form state lib, thank you :)

**Comment by bluebill1049** [comment]
`useWatch` is coming for v6 :)

**Comment by omerman** [comment]
@bluebill1049 And can I pass useWatch a callback, meaning only the callback will be fired and no re-renders will occour?

**Comment by bluebill1049** [comment]
> @bluebill1049 And can I pass useWatch a callback, meaning only the callback will be fired and no re-renders will occour?

short answer no, it's not a callback. it's a custom hook that you can subscribe to input changes at child level without re-render at root/form. 

`const data = useWatch({ name: 'fieldName', control })`

**Comment by omerman** [comment]
But what I'm saying is that sometime I want to do it in the root level, and avoid re-renders.

Take this case for example.
In this example I will have to re-render the component because I want to simple execute an update
method (saveInServer)
```
const MyComponentWithForm = () => {
const myForm = useForm(...);

const watchedValues = useWatch(..);

useEffect(() => {
  saveInServer(watchedValues);
}, [watchedValues])


return <MyOtherUITree>...</MyOtherUITree>
}
```

Im suggesting this:
```
const MyComponentWithForm = () => {
const myForm = useForm(...);

// No re-renders, yey!
useWatch(.., (watchedValues) => {
saveInServer(watchedValues);
});
}

return <MyOtherUITree>...</MyOtherUITree>
```

**Comment by bluebill1049** [comment]
Thanks for your suggestion. I hear your point, but we are not going that direction for now.

**Comment by bluebill1049** [comment]
one altnerative in my head, which may help:

`<form onChange={() => saveYourStore(getValues())}></form>`

**Comment by omerman** [comment]
Ok I understand :)

Currently this is what I'm doing(for everyone else wanting this kind of behavior):

```
const MyFormCom = () => {
   const form = useForm(...);


   return (<UITree>...<FormSpy form={form} names={['field1', 'field2'] onChange={callback}}></UITree>)
}
```

```
import { FormContextValues, DeepPartial } from "react-hook-form";
import { useEffect, useRef } from "react";
import { usePrevious } from "base/hooks/usePrevious";
import { isShallowEquals } from "base/utils/methods";

export type FormSpyProps<
  Values,
  FieldsNames extends keyof Values = keyof Values
> = {
  form: FormContextValues<Values>;
  names?: ReadonlyArray<FieldsNames>;
  onChange: (spiedValues: DeepPartial<Pick<Values, FieldsNames>>) => void;
};

export const FormSpy = <Values, FieldsNames extends keyof Values>({
  form,
  names,
  onChange,
}: FormSpyProps<Values, FieldsNames>) => {
  const values = form.watch(names as any) as DeepPartial<
    Pick<Values, FieldsNames>
  >;

  const prevValues = usePrevious(values);

  useEffect(() => {
    if (prevValues !== undefined && !isShallowEquals(values, prevValues)) {
      onChange(values);
    }
  }, [prevValues, values, onChange]);

  return null;
};

```

**Comment by bluebill1049** [comment]
Thanks for sharing the solution. 🙏

**Comment by chase2981** [comment]
Wait, so you are telling me there's no way to subscribe to changes to a form as a whole or listen to changes from a parent component--so that we can call a function with the new/old values as params on any given input change--assuming you are using a multi-level nested form of sub-forms? And subscribing to form change events like that which actually call a callback instead of just returning the latest value at any given point isn't even on your guys' radar? How are are we even supposed to trigger anything on change then?

**Comment by chase2981** [comment]
Like I thought that was the whole cool part about your package over the competitors, is you guys are like a celery task except for frontend react forms and form inputs, allowing us to do stuff in the background without lagging all of our form inputs and without having to constantly battle re-rendering input lag. Like you guys built out this powerful, intuitive, easy to use, uncontrolled form event system which makes it a lot easier to deal with uncontrolled forms and it makes it so we don't have to roll our own or worry about the performance impact of a controlled form system. (For instance, one problem for us was one sub-form's mapping from db model to view model and back to domain model again was slowing down all the other sub-form's keypresses, etc, and that was just one of the issues of a controlled form) All that is honestly why my team recently chose your product over the competitors. But it's a little concerning to now find out that you guys don't even expose any of your awesome uncontrolled form event system to any form-change subscriptions or onChange callbacks. I figured you'd already have that or else it would be on your guys' radar at the very least. 

That would be like reactive forms in angular not even giving you the ability to subscribe to form state changes, which is just crazy to me.

**Comment by DarkSouls101** [comment]
Take a look at custom hook useWatch. I think that’s what you after.

**Comment by omerman** [comment]
@chase2981 Im sorry for the inappropriate place to comment this comment but.. In order to achieve the most professional efficient and scalable product that uses a form system with React.. just use react-final-form.

**Comment by chase2981** [comment]
I think I figured it out. I appreciate all your guys' feedback. So I just wanted to share this incase any lost souls find themselves here in the future.

Essentially if I understand everything correctly, `react-hook-form` doesn't expose a specific formState subscription callback hook because they anticipate you'll just use react's built in "watcher", aka useEffect, if you want to watch one of their variables and call a function whenever it changes, like so:

<img width="700" alt="Screen Shot 2020-11-15 at 10 28 33 PM" src="https://user-images.githubusercontent.com/10983569/99216123-11aa1600-2792-11eb-9760-a2643261d991.png">

Essentially they don't need to expose a hook which calls a function for you whenever something changes, because you can easily do it yourself given the variables they already expose to you.

However, it would have been nice had someone just said that a little more explicitly is all I'm saying. I'm still debating between react-hook-form and react-final-form, I think either one would work, we are actually already using react-final-form, but I've learned a ton about both libs the last few days and I think either one will work. I originally thought react-final-form was delaying our inputs but since digging into everything, I've found someone put a 2 second debounce on our shared TextField component, which could very well be the source of the problem. My teams destiny is still up in the air, but I hope this helps someone in the future at very least, someone who may be more used to the angular way of doing things.

Once again, thank you @omerman  and @DarkSouls101 for your guys' feedback.

https://codesandbox.io/s/cwg-mat-react-hook-form-adv-demo-forked-i54qz?file=/src/SmartForm.tsx

**Comment by bluebill1049** [comment]
> @chase2981 Im sorry for the inappropriate place to comment this comment but.. In order to achieve the most professional efficient and scalable product that uses a form system with React.. just use react-final-form.. it is the best solution, again, sorry.. I found out about them a couple of months back.. and no other library even comes close when you are looking at complex forms.

No worries at all, it's a tool at the end of the day. pick the "right" tool is all in your hands, and most importantly pick the tool that you can finish your work at 5, so you can happily go home.

**Comment by bluebill1049** [comment]
> I think I figured it out. I appreciate all your guys' feedback. So I just wanted to share this incase any lost souls find themselves here in the future.
> 
> Essentially if I understand everything correctly, `react-hook-form` doesn't expose a specific formState subscription callback hook because they anticipate you'll just use react's built in "watcher", aka useEffect, if you want to watch one of their variables and call a function whenever it changes, like so:
> 
> <img alt="Screen Shot 2020-11-15 at 10 28 33 PM" width="700" src="https://user-images.githubusercontent.com/10983569/99216123-11aa1600-2792-11eb-9760-a2643261d991.png">
> 
> Essentially they don't need to expose a hook which calls a function for you whenever something changes, because you can easily do it yourself given the variables they already expose to you.
> 
> However, it would have been nice had someone just said that a little more explicitly is all I'm saying. I'm still debating between react-hook-form and react-final-form, I think either one would work, we are actually already using react-final-form, but I've learned a ton about both libs the last few days and I think either one will work. I originally thought react-final-form was delaying our inputs but since digging into everything, I've found someone put a 2 second debounce on our shared TextField component, which could very well be the source of the problem. My teams destiny is still up in the air, but I hope this helps someone in the future at very least, someone who may be more used to the angular way of doing things.
> 
> Once again, thank you @omerman and @DarkSouls101 for your guys' feedback.
> 
> https://codesandbox.io/s/cwg-mat-react-hook-form-adv-demo-forked-i54qz?file=/src/SmartForm.tsx

Thanks @chase2981 all feedback welcome, let me know how can we explain or improve on this. I am more than happy to try to make it better and easier for everyone. also PR welcome for the doc as well. i think we have 99.99% of merging PR at the documentation lol.

**Comment by chase2981** [comment]
> Thanks @chase2981 all feedback welcome, let me know how can we explain or improve on this. I am more than happy to try to make it better and easier for everyone. also PR welcome for the doc as well. i think we have 99.99% of merging PR at the documentation lol.

Where would you suggest I add it to your docs site? Like what page? Should I include the latest version of my codesandbox as an example or what, etc? I'm happy to do so given a little more guidance. I really do feel react-hook-form could use a full-fledged real-world example. I'm planning on adding something similar to my team's private doc site anyways. thnx.

**Comment by kaisermann** [comment]
> `<form onChange={() => saveYourStore(getValues())}></form>`

Hey 👋  Is there a way to use this approach while checking some of the `formState`, like the `dirtyFields` prop? I have a form that is supposed to update infos on the backend for any change in its inputs. However, I'm trying to send only the fields that we changed. I can use an effect + watch(), but I would like to prevent those extra renders.

**Comment by bluebill1049** [comment]
> > `<form onChange={() => saveYourStore(getValues())}></form>`
> 
> Hey 👋 Is there a way to use this approach while checking some of the `formState`, like the `dirtyFields` prop? I have a form that is supposed to update infos on the backend for any change in its inputs. However, I'm trying to send only the fields that we changed. I can use an effect + watch(), but I would like to prevent those extra renders.

v7 will have `watch((data) => { console.log(data) })` should solve your problem. it's coming.

**Comment by s97712** [comment]
> > > `<form onChange={() => saveYourStore(getValues())}></form>`
> > 
> > 
> > Hey wave Is there a way to use this approach while checking some of the `formState`, like the `dirtyFields` prop? I have a form that is supposed to update infos on the backend for any change in its inputs. However, I'm trying to send only the fields that we changed. I can use an effect + watch(), but I would like to prevent those extra renders.
> 
> v7 will have `watch((data) => { console.log(data) })` should solve your problem. it's coming.

Has a way to watch single field? like `watch("filedName", (value) => { console.log(value) })`

**Comment by bluebill1049** [comment]
> > > > `<form onChange={() => saveYourStore(getValues())}></form>`
> > > 
> > > 
> > > Hey wave Is there a way to use this approach while checking some of the `formState`, like the `dirtyFields` prop? I have a form that is supposed to update infos on the backend for any change in its inputs. However, I'm trying to send only the fields that we changed. I can use an effect + watch(), but I would like to prevent those extra renders.
> > 
> > 
> > v7 will have `watch((data) => { console.log(data) })` should solve your problem. it's coming.
> 
> Has a way to watch single field? like `watch("filedName", (value) => { console.log(value) })`

you can pick the value inside.

**Comment by cdomigan** [comment]
So just to confirm: there is no way to subscribe to an individual value changing and perform imperative operations? 

I'm looking for the equivalent of `react-final-form`'s `registerField()` method:
```
useEffect(() => {
    return formRef.current.registerField(
      "urgent",
      ({ value }) => {
        // doSomething()
      },
      { value: true }
    );
  }, [formRef]);
```

**Comment by bluebill1049** [comment]
@cdomigan use a deep compare custom hook.

**Comment by B-Esmaili** [comment]
> Ah it looks like the second param of the `watch` callback is what I'm after:
> 
> ```
> useEffect(() => {
>   watch((values, {name, value}) => {
>     if (name === "myFieldToWatch") {
>         console.log("Field changed!", value);
>     }
>   });
> }, [watch]);
> ```

How about useWatch? does it support callback?

**Comment by micahbule** [comment]
> > > `<form onChange={() => saveYourStore(getValues())}></form>`
> > 
> > 
> > Hey wave Is there a way to use this approach while checking some of the `formState`, like the `dirtyFields` prop? I have a form that is supposed to update infos on the backend for any change in its inputs. However, I'm trying to send only the fields that we changed. I can use an effect + watch(), but I would like to prevent those extra renders.
> 
> v7 will have `watch((data) => { console.log(data) })` should solve your problem. it's coming.

Just wanted to point out that this `watch()`'s particular signature with a callback was introduced on v7 but is currently included in your v6 documentation. I tried to find the correct file to change and do a PR but can't find it. Also tried to find the CodeSandbox attached, but it seems to be in order. I don't know what's wrong. In any case, just a heads up as it is a bit misleading.

![erroneous-doc-v6](https://i.imgur.com/YbdBJAT.png)

**Comment by dpickett** [comment]
is there a plan to provide the callback syntax for the `useWatch` function? Thanks!
