### ISSUE TITLE
accessing fieldsArray from formContext in multiple places 

### ISSUE THREAD

**Issue by tafelito** [react-hook-form/react-hook-form#1909]
**Describe the bug**
I have a form that is divided in 2 sections

The 1 part has a few inputs. The second part is a dynamic form, where I can add or remove fields

The dynamic part is also divided in a few sections and the problem is that there are a few inputs that I need to show in both sections, and both sections can update the same field. This only works when using a Controller but not with the register and it only refreshes both values when you update the first input. If you write anything on the inner form, the main form field does not get updated

Also, when using watch for the fieldArray, it does not get the id used as default for every item

Here's a simple example of what I'm trying to do

https://codesandbox.io/s/react-hook-form-usefieldarray-template-mj7vm?file=/src/index.js

**Comment by bluebill1049** [comment]
We don't support this type of usage. why not create a separate `useFieldArray` or pass down the entire `fields` and all associated emthods.

**Comment by tafelito** [comment]
I cant' create a separate useFieldArray because some fields are shared btw the 2 forms.

Passing the fields as properties doesn't seem to work either, because you still have to register the input and access it in the inner form and that does work

I updated the example

**Comment by bluebill1049** [comment]
So you want to create duplicated `FieldArray` with exactly the same fields (name)? I am afraid this is not going to work because name needs to be unique in RHF. I couldn't think of a good solution in my head to fulfill your use case.

**Comment by tafelito** [comment]
I don't exactly need a duplicated `FieldArray` but I do want 2 fields with the same name but that's not the only issue I have. So here's the schema of my data

```js
{
  name: '',
  text: '',
  actions: {
    attachments: false
  },
  dynamic: {
    fields: {
      'field-1': {
        id: 'field-1',
        label: 'Legacy',
        type: 'text',
      },
      'field-2': {
        id: 'field-2',
        label: 'Name',
        type: 'db',
      },
      'field-3': {
        id: 'field-3',
        label: 'Date',
        type: 'date',
      },
      'field-4': {
        id: 'field-4',
        label: 'Div',
        type: 'combo',
        values: [
          { label: '', value: '' },
        ],
      },
    },
    rows: {
      'row-1': {
        id: 'row-1',
        title: 'Row 1',
        fieldsIds: ['field-1', 'field-2', 'field-3', 'field-4'],
      },
      'row-2': {
        id: 'row-2',
        title: 'Row 2',
        fieldsIds: [],
      },
      'row-3': {
        id: 'row-3',
        title: 'Row 3',
        fieldsIds: [],
      },
    },
    rowsOrder: ['row-1', 'row-2', 'row-3'],
  }
}
```

The first part of the data is shown in a main Form, and the dynamic part is in an inner form where I have all the fields. The fields are dynamic, so you can add or remove, and same with the rows. 
The label of the fields is the one I need to show in 2 different places.

When I created the example, instead of having the fields and the rows by id, I thought that maybe if I created 2 `FieldArray` it would allow me to solve this, since right now I can access the fields by their path, using `dynamic.fields.field-1.label` as the name

**Comment by bluebill1049** [comment]
> The label of the fields is the one I need to show in 2 different places.

Like I suggested above the same name is not going to work, unfortunately.

**Comment by bluebill1049** [comment]
> I don't exactly need a duplicated `FieldArray` but I do want 2 fields with the same name but that's not the only issue I have. So here's the schema of my data
> 
> ```js
> {
>   name: '',
>   text: '',
>   actions: {
>     attachments: false
>   },
>   dynamic: {
>     fields: {
>       'field-1': {
>         id: 'field-1',
>         label: 'Legacy',
>         type: 'text',
>       },
>       'field-2': {
>         id: 'field-2',
>         label: 'Name',
>         type: 'db',
>       },
>       'field-3': {
>         id: 'field-3',
>         label: 'Date',
>         type: 'date',
>       },
>       'field-4': {
>         id: 'field-4',
>         label: 'Div',
>         type: 'combo',
>         values: [
>           { label: '', value: '' },
>         ],
>       },
>     },
>     rows: {
>       'row-1': {
>         id: 'row-1',
>         title: 'Row 1',
>         fieldsIds: ['field-1', 'field-2', 'field-3', 'field-4'],
>       },
>       'row-2': {
>         id: 'row-2',
>         title: 'Row 2',
>         fieldsIds: [],
>       },
>       'row-3': {
>         id: 'row-3',
>         title: 'Row 3',
>         fieldsIds: [],
>       },
>     },
>     rowsOrder: ['row-1', 'row-2', 'row-3'],
>   }
> }
> ```
> 
> The first part of the data is shown in a main Form, and the dynamic part is in an inner form where I have all the fields. The fields are dynamic, so you can add or remove, and same with the rows.
> The label of the fields is the one I need to show in 2 different places.
> 
> When I created the example, instead of having the fields and the rows by id, I thought that maybe if I created 2 `FieldArray` it would allow me to solve this, since right now I can access the fields by their path, using `dynamic.fields.field-1.label` as the name

If two `useFieldArray` both point to the same input data, it's not going to work. `name` is unique in RHF.

**Comment by bluebill1049** [comment]
Hmmm.. unless two `useForm` instance, then you can have duplicated name.

**Comment by tafelito** [comment]
OK the 2 fields I can solve it in a different way, by either update manually with setValue in onChange or o Blur.
What about accessing the fields by the path? I couldn't find a way to do that either, I had to handle it manually too

**Comment by bluebill1049** [comment]
> What about accessing the fields by the path?

can you expand on this one?

**Comment by tafelito** [comment]
@bluebill1049 I thought that by using a deep nested name like `dynamic.fields.field-1.label` wasn't updating the correct values when having such a dynamic form, or when using a nested form through context. It doesn't seem to be the case anymore, but i will keep an eye o this since at some point it appeared that that wasn't working

**Comment by bluebill1049** [comment]
ok, I will close this issue now, as some of the things mentioned the lib couldn't cover anyhow (same name).
