### ISSUE TITLE
<Controller> doesn't inherit children types from "as" prop

### ISSUE THREAD

**Issue by atwalg2** [react-hook-form/react-hook-form#1910]
**Describe the bug**
Improper typing on Controller.tsx cause red line when you pass it children the wrapped component relies on.

**To Reproduce**
Add children to <Controller> 
when as={Picker} requires children to work correctly

**Codesandbox link (Required)**
React native doesn't work in Codesandbox??
```
import React, {Fragment} from 'react';
import {Text, View, TextInput, Button, Alert} from 'react-native';
import {useForm, Controller} from 'react-hook-form';
import {Picker} from '@react-native-community/picker';

interface FormData {
  firstName?: string;
  lastName?: string;
}
export default function App() {
  const {
    control,
    watch,
    errors,
  } = useForm<FormData>();

  return (
    <View>
      <Controller
        as={Picker}
        control={control}
        name="language"
        style={{height: 50, width: 100}}>
        <Picker.Item label="Java" value="java" />
        <Picker.Item label="JavaScript" value="js" />
      </Controller>
    </View>
  );
}
```

**Expected behavior**
Children should be cast as any or gain correct types from as={Component}

**Screenshots**
https://us-prod.asyncgw.teams.microsoft.com/v1/objects/0-eus-d3-714dede21abe11e50529e2c619a2c256/views/imgo
![image](https://user-images.githubusercontent.com/23143862/85051385-ab728600-b154-11ea-8a5d-529a59412181.png)

**Comment by atwalg2** [comment]
It seems the Picker component doesn't have children in it's typings.

Maybe the controller component should default to any if no typing exists for children?

**Comment by bluebill1049** [comment]
This is getting resolved by V6's render props.

`<Controller render={props => ...} />`
