### ISSUE TITLE
Default value not being set for async select options

### ISSUE THREAD

**Issue by jonsaich** [react-hook-form/react-hook-form#1914]
**Describe the bug**
Imagine this is an edit form and we're loading data from a server. I'm struggling to set the selected select option when the options are looped through and then added to the select.

**To Reproduce**
Look at the select - it doesn't have the default value.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-qy0s4

**Expected behavior**
**This should be selected** option to be selected

**Comment by bluebill1049** [comment]
use `reset()` API. 

<img width="980" alt="Screen Shot 2020-06-19 at 5 01 50 pm" src="https://user-images.githubusercontent.com/10513364/85105868-937f2d00-b24e-11ea-8bdd-23ed9d1ba4ab.png">
