### ISSUE TITLE
IE11 crashes on useDebounceCallback

### ISSUE THREAD

**Issue by sanderwapstra** [react-hook-form/react-hook-form#1916]
**Describe the bug**
I'm importing `react-hook-form` as `import { Controller, useForm } from 'react-hook-form/dist/react-hook-form.ie11';` but it still crashes on a arrow function in Internet Explorer 11. Are these helper functions not transpiled or am I doing something wrong? Thanks!

**Screenshots**
<img width="1329" alt="Screenshot 2020-06-19 at 09 53 51" src="https://user-images.githubusercontent.com/20322474/85110306-fb178700-b212-11ea-98c1-b6dd3d79e4ee.png">

**Additional context**
Using Laravel Mix (https://laravel-mix.com)

**Comment by bluebill1049** [comment]
hey @sanderwapstra that's not our source code :(

**Comment by sanderwapstra** [comment]
Hi @bluebill1049, sorry for taking your time! Was time for weekend I guess 😅
