### ISSUE TITLE
set initial vaules from pops to from and update vaules (Question)

### ISSUE THREAD

**Issue by rakanabdullah** [react-hook-form/react-hook-form#1917]
hi 

 thank you for this good  Library

I used in react native

i have data come from props and i set defaultValues for it :

const { getValues, setValue, handleSubmit, errors, register } = useForm(
        {
            defaultValues: {
                Schedule_Library_Name: props.Schedule_Library_Name ,//="testname"

            }
        }
    );

is work fine ones i want to update value 
the value not Change Because ("getValues("Schedule_Library_Name")")
 is not Change with the setValue is still take the  defaultValue
how i cant make Changeable with new value the come from setValue

Example for input :

 <FormInput
      labelName='Library_Name'
      onChangeText={text => { setValue("Schedule_Library_Name", text) }}
       errorTextInput={errors.Schedule_Library_Name}
       helperTextContent="errors.Schedule_Library_Name"
        value={getValues("Schedule_Library_Name")}
                />

**Comment by bluebill1049** [comment]
I think you want to use `reset` at `useEffect`

https://react-hook-form.com/api#reset

**Comment by rakanabdullah** [comment]
i try it but not work for my did you have an example in sandbox ?
