### ISSUE TITLE
Form state not valid when component is mounted

### ISSUE THREAD

**Issue by hugomassing** [react-hook-form/react-hook-form#1919]
**Describe the bug**
Hello, thanks for your awesome library, I love it!

I have a little bug when un-mounting and mounting components with `Controller`. When mounting a component, validation is triggered but it's not updating the `formState`.

**To Reproduce**
To reproduce you can click `tab 2` and then click `tab 1` again, `formState.isValid` is `false` when it was true just before. 

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-component-umounted-validation-iigsu

**Expected behavior**
`isValid` should be true when mounting a the component.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - Browser: Chrome
 - Version: 83

**Comment by bluebill1049** [comment]
I think the simplest solution here just toggles the visibility of those inputs. Is that a valid solution?

**Comment by hugomassing** [comment]
@bluebill1049 I think `triggerValidation` could work! Thanks

**Comment by bluebill1049** [comment]
closing this issue, feel free to reach out if not working and will re-open.
