### ISSUE TITLE
watch()[fieldName] !== watch(fieldName)

### ISSUE THREAD

**Issue by reverie** [react-hook-form/react-hook-form#1922]
**Describe the bug**
The documentation at https://react-hook-form.com/api#watch states that `watch()[fieldName]` and `watch(fieldName)` are equivalent.

**To Reproduce**
1. Create a new form of type `{foo?: string}` with a `defaultValues` of `{foo: '1'}`
2. Use a controlled react-number-format input with name "foo".
3. Delete default value from the input
4. `watch().foo` is `undefined`, while `watch('foo')` is `'1'`.

**Comment by bluebill1049** [comment]
can you please provide a codesandbox?

**Comment by reverie** [comment]
> can you please provide a codesandbox?

Sure. I used an `input` for convenience, which means we get an extraneous error about switching from controlled to uncontrolled, but note that some controlled components do accept `undefined` as a `value`.

https://codesandbox.io/s/react-hook-form-useform-template-tw7y8?file=/src/index.js

Delete the text in the input, observe console.log output: 123, undefined. Whereas the docs say that these values should match.

Loving rhf overall -- thank you!

**Comment by bluebill1049** [comment]
hey @AndrewSouthpaw thanks for the codesandbox.

```
<Controller
  as="input"
  name="foo"
  control={control}
  onChange={e => {
    return e[0].target.value || undefined; // why this is added?
  }}
/>
```

FYI: `Controller` doesn't allow `defaultValue` to be undefined, it's a required `prop`.

**Comment by reverie** [comment]
> hey @AndrewSouthpaw thanks for the codesandbox.
> 
> ```
> <Controller
>   as="input"
>   name="foo"
>   control={control}
>   onChange={e => {
>     return e[0].target.value || undefined; // why this is added?
>   }}
> />
> ```
> 
> FYI: `Controller` doesn't allow `defaultValue` to be `undefined`, it's a required `prop`.

It is listed as non-required in the documentation and typings.

**Comment by bluebill1049** [comment]
<img width="925" alt="Screen Shot 2020-06-20 at 3 42 10 pm" src="https://user-images.githubusercontent.com/10513364/85193518-9d676580-b30c-11ea-89cc-de43f0b04a8d.png">

Because it's either supply as inline `defaultValue` or at the `useForm` level which is `defaultValues`.

**Comment by bluebill1049** [comment]
Feel free to improve the doc if the wording is not precise (it's open-source as well).

**Comment by reverie** [comment]
> Feel free to improve the doc if the wording is not precise (it's open-source as well).

Ah, yeah, that’s clear in the docs. Note that the codesandbox does pass defaultValues to useForm.

**Comment by bluebill1049** [comment]
> > Feel free to improve the doc if the wording is not precise (it's open-source as well).
> 
> Ah, yeah, that’s clear in the docs. Note that the codesandbox does pass defaultValues to useForm.

Yes, that's why I was asking about this `undefined` return.

`return e[0].target.value || undefined; // why this is added?`

once default value is set, the rest of the logic is basically React.useState.

https://github.com/react-hook-form/react-hook-form/blob/master/src/controller.tsx#L57

**Comment by bluebill1049** [comment]
going to close this one, feel free to reopen if this does not resolve your question.

**Comment by reverie** [comment]
@bluebill1049 This is a bug report, not a question. :) Since you are a maintainer of the project, I'm not going to reopen if you don't think it's a bug. To me as a user it is surprising to run into a case where `watch()[fieldName] !== watch(fieldName)`. 

> once default value is set, the rest of the logic is basically React.useState.

Then why does `watch()` return the defaultValue in the sandbox example?

**Comment by bluebill1049** [comment]
Thanks for the reply, from the conversation above we are discussing i got confused with topics, and there is no follow up with my questions as well, so I thought it's resolved. 

are we discuss the problem with `watch()[fieldName] !== watch(fieldName)`

or 

```
onChange={e => {
  return e[0].target.value || undefined; // why this is added?
}}
```

I am happy to focus on one thing at a time. as I conclude the return `undefined` is not supported and incorrect usage.

**Comment by reverie** [comment]
> I am happy to focus on one thing at a time. as I conclude the return undefined is not supported and incorrect usage. let me know if that's the problem of the question or we can continue with the discussion.

That's clarifying. If `undefined` form field values are not supported, that answers my question completely. Thank you, and sorry for the erroneous bug report!

**Comment by bluebill1049** [comment]
> > I am happy to focus on one thing at a time. as I conclude the return undefined is not supported and incorrect usage. let me know if that's the problem of the question or we can continue with the discussion.
> 
> That's clarifying. If `undefined` form field values are not supported, that answers my question completely. Thank you, and sorry for the erroneous bug report!

👍  All good, sorry if you feel bad when I suddenly close your ticket, honestly I thought my reply answered your question. I am trying to maintain the issues logs here so I can focus just a couple of them, but when users still have a problem, I will always reopen or answering them even when they r closed too. Hope for your understanding. have a good one.

**Comment by reverie** [comment]
No worries at all. Thanks for a great library, it's a breath of fresh air.
