### ISSUE TITLE
touched not set on using reset() or setValue()

### ISSUE THREAD

**Issue by jovana** [react-hook-form/react-hook-form#1927]
**Describe the bug**
Loading data from API (async) an put it in the reset() function it does not set the fields to touched.
Also using setValue() (instead or together) does give the desired result.

**To Reproduce**
1. Go to https://codesandbox.io/s/fblif
2. After 1 second the value is loaded.
3. touched object is not changed.
4. If click on the field touched has been changed after click outside the box (onBlur).

**Codesandbox link (Required)**
https://fblif.csb.app/

**Expected behavior**
Setting the value's for the fields using reset() (preferred) or using setValue does not set the touched object to true.

**Desktop (please complete the following information):**
 - OS: MACOSX
 - Browser chrome 83  and safari 13

**Comment by bluebill1049** [comment]
Hi there, I think you have misunderstood `touched` means _it means the input has been blurred_. With reset() you are not touched any of the inputs.

**Comment by jovana** [comment]
Hey Bill,

Thx for your answer.
Okay sounds reasonable for the reset() function. 

But the documentation about setValue() stated clearly: ‘...touched is updated’ 

https://react-hook-form.com/api#setValue

In my case I need to lift the labels up if data has entered the form. I looking for a way to do this the moment data has loaded from api. 

Jo

**Comment by bluebill1049** [comment]
wow, that's a huge mistake! I will fix that ASAP. thanks

**Comment by bluebill1049** [comment]
what do you mean lift the label up?

**Comment by bluebill1049** [comment]
FYI: The doc has been patched.

**Comment by jovana** [comment]
> what do you mean lift the label up?

This is a design choice. The moment you enter something the lable goes out of the way:
<img width="504" alt="Schermafbeelding 2020-06-20 om 13 31 36" src="https://user-images.githubusercontent.com/645456/85200798-8c155d80-b2fa-11ea-8d72-db91450e2725.png">
<img width="514" alt="Schermafbeelding 2020-06-20 om 13 31 25" src="https://user-images.githubusercontent.com/645456/85200799-8d468a80-b2fa-11ea-93d9-b6df5cf52f0e.png">

**Comment by jovana** [comment]
Okay, but is there a method to have the touched properties changed programmatically?

**Comment by bluebill1049** [comment]
That looks like MUI, but why is it have to do with `touched`? the label should go up as long as there is a value in the text input.

**Comment by bluebill1049** [comment]
i think you may want to wrap your custom input with `Controller`.

**Comment by bluebill1049** [comment]
Take a look at this CSB for reference: https://codesandbox.io/s/react-hook-form-controller-079xx

**Comment by jovana** [comment]
Okay cool!
Thx for you advise. I have solved my case now not using touched property. 

Jo
