### ISSUE TITLE
Fields are not correctly monitored inside iFrames

### ISSUE THREAD

**Issue by Nickman87** [react-hook-form/react-hook-form#193]
**Describe the bug**
When loading my forms inside an iFrame (with a react portal!), my watches suddenly stopped working.
Tracing the code I ended up in the mutation observer that is used to see if a field is unmounted.
This method tries to check the entire tree to see if we end up in the current window, but the node tree stops at the iFrame level.

**To Reproduce**
I made a simple setup here to illustrate the issue: https://codesandbox.io/s/react-hook-form-iframe-portal-rkn9f

**Expected behavior**
I would expect the watch (and the rest of the library :)) to work correctly also when using a portal to inject my content into an iFrame. I think the mutation watcher should be made aware of this possibility and check for unmounting in another way.

**Screenshots**
![image](https://user-images.githubusercontent.com/870416/62607912-2ba64900-b8ff-11e9-9001-3f84329cf39d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**
I'm currently working this way because I want to make a wrapper around my entire application. This is an extreme example but I also have plans for another project and there the iFrame portal wrapping would be used to make sure no CSS styles get leaked into or outside of components (users would be able to define custom styling for smalles widgets.
Thus I don't think this is an extreme edgecase :)

**Comment by bluebill1049** [comment]
if you want to react hook form to work with external `iframe`, please use custom `register` instead `register` with ref.
```
useEffect(() => {
  register({ name: 'test' });
})
```

**Comment by Nickman87** [comment]
A component should not know where it is mounted...
This means every single component should be manually registered, all the time, just in case it might be mounted into an iFrame?

**Comment by bluebill1049** [comment]
why does every input need to live in an iframe? it's your use case... 

I only offer a solution if you need to do that in an iframe.

**Comment by Nickman87** [comment]
They don't that's the point :D.
Sometimes they are inside an iFrame, and other times they are not.

You could just change the isDetached method to check if the element you have is a document type and it would work just fine?
![image](https://user-images.githubusercontent.com/870416/62620841-9d3fc080-b91a-11e9-9243-f337258e2878.png)
Or something like this.

**Comment by bluebill1049** [comment]
can you send a PR on this issue? I and the core contributors can take a look at this.

**Comment by Nickman87** [comment]
Sure, I'll do some testing to see if it is stable and get back to you!

**Comment by bluebill1049** [comment]
I am testing the new change today, can you check as well?

`3.21.12-beta.1`

**Comment by bluebill1049** [comment]
tested and verified on my end.

**Comment by Nickman87** [comment]
I can test it tonight

**Comment by Nickman87** [comment]
Seems to solve my issue 👍

**Comment by bluebill1049** [comment]
going to publish the patch now thanks for confirming.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/releases/tag/v3.21.12 close this issue when ready

**Comment by zaferkadi** [comment]
@Nickman87 I think I'm currently facing a similar issue where some elements are rendered in a portal (modals, drawers, etc they all live in portals), and my fields are not tracking the changes, could you tell me how you solved your issue?

**Comment by bluebill1049** [comment]
> @Nickman87 I think I'm currently facing a similar issue where some elements are rendered in a portal (modals, drawers, etc they all live in portals), and my fields are not tracking the changes, could you tell me how you solved your issue?

1. build a separate `useForm` with `form` with the modal and store data in state lib or useState
2. use `shouldUnregister: false`

**Comment by zaferkadi** [comment]
Thanks @Nickman87, I wish I can share a CSB version of this, but I understand the premises of this.
I have added a new form with its own useForm plus shouldUnregister false, and they all live in a component which will be rendered in a portal, when I submit I see the data, so thats great.
But when I open the form again aka the portal, the data is not persisted in the fields, do I need to put it back somehow someway? I'm using useFieldArray as well.

**Comment by bluebill1049** [comment]
This potential issue is getting addressed in v7, where data will be persisted.

**Comment by zaferkadi** [comment]
Thanks @bluebill1049, I think I accidentally mentioned nick instead of you.

I have solved my problem by NOT using useFieldArray, and I kept my codebase the same without adding an extra form nor hoisting my state. I think I was too obsessed with using useFieldArray because the idea behind it was really cool that I forgot that I can still solve my array problem in a very basic way.
