### ISSUE TITLE
Validation does't work correctly using Controller and react-select 

### ISSUE THREAD

**Issue by tafelito** [react-hook-form/react-hook-form#1931]
**Describe the bug**
when using a react-select component with controller, the validation does not work properl when using `reValidateMode: 'onBlur'`

the select component is validating onBlur all the time, not only after the form was submitted. As i Understand, by using the `reValidateMode: 'onBlur'` makes the inputs validates onBlur instead of onChange. But the select is validating onBlur even when the form was not submitted

here's the codesandbox
https://codesandbox.io/s/react-hook-form-usefieldarray-template-mj7vm?file=/src/index.js

**Comment by bluebill1049** [comment]
can you provide a `codesandbox`? The one you have attached seems to be wrong.

**Comment by tafelito** [comment]
Try this one
https://codesandbox.io/s/react-hook-form-controller-kl3uq

**Comment by tafelito** [comment]
I'm amazed on how quick your response is in answering every issue and fixing them if needed. 👏👏

Thanks for you hard work!

**Comment by bluebill1049** [comment]
no worries @tafelito I try my best 🙉

**Comment by tafelito** [comment]
By the way, since the next version will deprecate valisationSchema, it would be great if somehow the validation resolver could tell what field is changing the value, specially after the a form is submitted and the validation occurs on the onChange event, to validate only the field that is changing and not the whole schema. I found that with complex schemas it can get very slow and you notice a lag while typing

**Comment by bluebill1049** [comment]
for schema it will be quite difficult to achieve, we do that for build-in validation tho.

**Comment by tafelito** [comment]
for schema yes, but what about for the resolver? There, if you get the field, one can decide to validate the whole schema of just the field

**Comment by tafelito** [comment]
@bluebill1049 are you going to release this on V6 or are you planning on release a patch for v5?

**Comment by bluebill1049** [comment]
hey @tafelito we going to release V6.

**Comment by jonasmarco** [comment]
Can anyone help me validate a select?

@bluebill1049 
@tafelito 
@evocateur 
@aaronjensen 

[CodeSandBox code](https://codesandbox.io/s/react-hook-form-react-select-d1y3zv)

**Comment by Moshyfawn** [comment]
> Can anyone help me validate?
> 
> @bluebill1049 @tafelito @evocateur @aaronjensen
> 
> [CodeSandBox code](https://codesandbox.io/s/react-hook-form-react-select-d1y3zv)

Care to elaborate?
