### ISSUE TITLE
Feature request: Get all unmounted form fields

### ISSUE THREAD

**Issue by paambaati** [react-hook-form/react-hook-form#1932]
**Is your feature request related to a problem? Please describe.**
A way to get all the unmounted form fields would be very useful. In v6, with the `shouldUnregister` set, after a few components have been unmounted, a way to access only those specifically is what I’m looking for.

This will be useful in conditional form fields where setting a certain input can show or hide other fields in the same form.

**Describe the solution you'd like**
Expose a `getUnmountedFields()` method.

**Describe alternatives you've considered**
Currently in v5, I manually keep track of all fields using `ref`s.

**Comment by bluebill1049** [comment]
Thanks @paambaati I think this should be tracked at your app level.

**Comment by bluebill1049** [comment]
I am going to close this issue and tagged with feature request, don't think we will implement this feature at the moment.
