### ISSUE TITLE
[v6 rc5] formState.isValid returning false for a valid form

### ISSUE THREAD

**Issue by piehouserat** [react-hook-form/react-hook-form#1934]
looks like a simple regression, was fine in rc4

sorry for lack of detail but should be easy for you to validate this

**Comment by bluebill1049** [comment]
can you please follow this with a codesandbox? i don't think we have an issue with `isValid`, otherwise our regression script would catch the problem.

**Comment by bluebill1049** [comment]
how to reproduce this issue? a codesandbox would really help.

**Comment by piehouserat** [comment]
yes, i hate creating them but here you go 😂 

https://codesandbox.io/s/optimistic-breeze-tv9bl?

the form initialises with a valid default state, the first time you hit the submit button `isValid` will be false, clicking the button a second time without changing anything `isValid` is now true and you will see an alert

**Comment by piehouserat** [comment]
thank you for creating this awesome library by the way!

**Comment by bluebill1049** [comment]
rc.4 and rc.5 having the same result.

**Comment by bluebill1049** [comment]
ok wait i see the problem now.

**Comment by bluebill1049** [comment]
This is expected behavior because you are on default mode which is onSubmit, isValid will only be true after submit. `isValid` is normally used for `onChagne` mode.

**Comment by piehouserat** [comment]
oh so basically i should change the mode to onChange then?

use case is that the form will typically load pre-populated and may be initially valid

onChange will solve this problem?

**Comment by bluebill1049** [comment]
correct: mode: 'onChange' will update `isValid`.
