### ISSUE TITLE
Validation with multiple validators is inconsistent given the same form data (using MUI's TextField)

### ISSUE THREAD

**Issue by malsioufi** [react-hook-form/react-hook-form#1938]
**Describe the bug**
The validation is inconsistent when multiple validators are used with a MUI component.
The error keeps triggering/disappearing on every change or submit as shown in the codesandbox example (locally even on blur).

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-controller-nlypq
2. Type '12345678' in the text field
3. Click on submit, it submits normally.
4. Click on submit again, it shows an error.
    Alternatively, delete 8, then type it again, and it will keep toggling the error on and off everytime you delete '8' and type it again.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-nlypq

**Expected behavior**
The validation should always give the same result given the same form data. Whether the validation runs onSubmit or onChange.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83

**Comment by bluebill1049** [comment]
change

`value: /^[0-9A-Fa-f]+$/g,` // global

to
 
`value: /^[0-9A-Fa-f]+$/,`

**Comment by malsioufi** [comment]
Thanks for your reply. It works! 

Should there be a warning for users to not use `g` in their patterns? Unless there is one already that I missed.
