### ISSUE TITLE
Controller does not change validation rules after the rules object change. (with MUI)

### ISSUE THREAD

**Issue by malsioufi** [react-hook-form/react-hook-form#1939]
**Describe the bug**
The Controller does not change validation rules after the rules object have changed.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-controller-w6l13
2. Type '1234567x' in the text field
3. Click on submit, it shows a validation error saying value must be hexadecimal.
4. Click on submit few times until Render Count is > 10 (shown in a white span on top right)
5. After Render Count is > 10, the rules object (shown below the submit button) changes, and the pattern validates numeric value instead of hexadecimal. However, the validation doesn't update accordingly, and it keeps using the initial rules passed to it.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-w6l13

**Expected behavior**
To change the validation rules when the passed rules have changed.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version 83

**Additional context**
I have scenarios where I want to change the rules of a TextField according to the value of another input (for example a radio button: •numeric •hexadecimal).

**Comment by bluebill1049** [comment]
This is already merged and will be released with V6: https://github.com/react-hook-form/react-hook-form/pull/1791, you can use v6.0.0-rc.5 for now
