### ISSUE TITLE
Access errors like it's possible for values with `useWatch`

### ISSUE THREAD

**Issue by moulinraphael** [react-hook-form/react-hook-form#1942]
First of all, thanks a lot about the lib, it's very useful and powerful :)

**Is your feature request related to a problem? Please describe.**
It seems not really simple to access to the field's error without passing `errors` throught components' props. For instance, I want to build a generic field which is used to display both input and error message. 

**Describe the solution you'd like**
It should be great to have access to a hook, for instance `useWatchError` in order to access a specific (or several) field's error(s). 

**Describe alternatives you've considered**
The solution I implemented is to pass `errors` to props of components from the main component declaring the form, until the field's component. 

Main
```
const { control, errors } = useForm();
return (<Child control={control} errors={errors} />};
```

Child
```
const name = 'fieldName';
return (
  <Controller
    name={name}
    as={<Field error={errors?.[name]}}
    rules={...}
    control={control}
  />
)
```

Field
```
return (
  <>
     <input />
     <div>{error}</div>
  </>
)
```

Maybe you have a better solution that I didn't think of...

**Comment by ghostd** [comment]
Hi,

[useFormContext](https://react-hook-form.com/api#useFormContext) could answer to your issue?

**Comment by bluebill1049** [comment]
also, you should take a look at the ErrorMessage too.

**Comment by moulinraphael** [comment]
Thanks @ghostd / @bluebill1049 , I'm using `FormProvider / useFormContext` now. 

However about the errors:
1. I notice that `shouldValidate` significantly reduces performance (~ with 400 watched field)
2. When a field is not valid and an error is added in `errors`, the whole form is rendered, is it possible to avoid this mechanism ?

**Comment by bluebill1049** [comment]
Hey @moulinraphael, we don't have such mechanism, `formState` include `errors` will both re-render at the form level.

**Comment by moulinraphael** [comment]
Ok and do you think such a mechanism (like values are managed) will be available in the future ?

**Comment by bluebill1049** [comment]
everything is possible, but it comes down to demand and solves a problem that most people are having. If there are a lot of people request for such a feature, I would consider otherwise I would probably skip to introduce such a feature.
