### ISSUE TITLE
`watch` / `getValues` don't return default value when it's defined in `Controller`

### ISSUE THREAD

**Issue by moulinraphael** [react-hook-form/react-hook-form#1943]
**Describe the bug**
When default values are defined using `useForm` then `watch` and `getValues` return correctly these values before any change on the inputs. However, when default values are define locally for each `Controller`, the default value of each input isn't returned, and value is `undefined`.

(Same thing with `register`, but it's not really a bug because the declaration of `defaultValue` it outside, however it would be great to specify the default value in the call of `register`)

**To Reproduce**
1. Create a `Controller` with `defaultValue` prop
2. Watch the value of this input
3. See that there is a value in the input but the string returned by `watch` is undefined

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-watch-z0bf0

**Expected behavior**
`watch` (and `useWatch`) and `getValues` returned the value specified in the `defaultValue` prop of `Controller`.

**Desktop (please complete the following information):**
 - OS: MacOS (15.15.5)
 - Browser: Chrome (83)

**Comment by bluebill1049** [comment]
<img width="923" alt="Screen Shot 2020-06-24 at 8 50 51 am" src="https://user-images.githubusercontent.com/10513364/85474307-d0a14180-b5f7-11ea-9195-25bdacf764d0.png">

please make sure it's either.

**Comment by moulinraphael** [comment]
Ok thanks @bluebill1049 :) 
It's a shame because it would be great to be able to fully declare a field (with its default value) anytime and anywhere :)
