### ISSUE TITLE
false positive for formState.isValid

### ISSUE THREAD

**Issue by kintz09** [react-hook-form/react-hook-form#1944]
**Describe the bug**
I don't know the cause, but my form is giving what I believe to be a false positive for `formState.isValid`. 

The form includes 3 text fields and 1 select:
1.) firstName (optional, max length)
2.) lastName (optional, max length)
3.) email (required, max length, and pattern)
4.) Select dropdown (required)

Mode: 'onBlur' (I've also tried with 'onChange')

There are no default values for the form (I did try with empty strings as default values as well which can be found in the code sandbox).

When the form initializes, isValid = true and isDirty = false. After touching a second input the form's state becomes `isValid = true` and `isDirty = true` even though the required fields haven't been touched and don't have any values. Is this expected?

I'm ultimately trying to enable the form's submit button once the form is valid.

**Codesandbox link (Required)**
https://codesandbox.io/s/dialog-isvalid-test-bk57r?file=/src/App.js

**To Reproduce**
1. Open the code sandbox
2. Select the button 'Add Member' to open the dialog with the form
3. Observe the FormData at the bottom of the dialog. Note the form is untouched, not dirty, but is valid.
4. Tab to the second field and observe that the form is now dirty and valid and the button has been enabled.
5. Tab to the email input and enter 'test.com' then shift tab to the previous input and observe that the validation is working. The form is now dirty and invalid.
6. Tab to email and add a proper email. Shift tab back to last name to observe the form becoming valid again. Note this is the case even though the other required field hasn't been touched and is empty.

**Expected behavior**
If a required field hasn't been filled, formState.isValid would be false.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Browsers: Firefox Developer 78.0b8, Chrome 83.0.4103.106

Let me know what else I can provide to help identify the cause of the issue.

**Comment by bluebill1049** [comment]
I have responded to you in the Spectrum as well. I would recommend you fix the `render` form issue, and provide an isolated form to reproduce the issue.

**Comment by bluebill1049** [comment]
answered and resolved here: https://spectrum.chat/react-hook-form/help/should-the-form-isvalid-property-be-false-when-a-required-field-is-empty~c68abcd6-d4c6-4961-9402-7f5d723639fd

**Comment by kintz09** [comment]
@bluebill1049 Thank you for such a quick response on Spectrum!

Your suggestion seems to have fixed my issue in the code sandbox example and in my actual project. Here's the links for other's to reference.

Original: https://codesandbox.io/s/dialog-isvalid-test-bk57r
Fixed: https://codesandbox.io/s/dialog-isvalid-test-1h6j3
