### ISSUE TITLE
setValue that doesn't effect formState.dirty

### ISSUE THREAD

**Issue by itamardavidyan** [react-hook-form/react-hook-form#1948]
In my react component I fetch data from the server -> then change the form values (with `setValue`) ->  then the `dirty` property change from `false` to `true`

Idea for solution:
extend `setValue` params to ->
```setValue(name: string, value: any, shouldValidate?: boolean, shouldEffectFormState?: boolean) => void```

Thanks.

**Comment by itamardavidyan** [comment]
Another option for solution:
`useForm` return `setFormState` that gives the ability to modify the formState

**Comment by bluebill1049** [comment]
This is getting addressed in V6: https://github.com/react-hook-form/react-hook-form/releases

**Comment by bluebill1049** [comment]
will release V6 early next week.

**Comment by itamardavidyan** [comment]
@bluebill1049 There is a method to change the defaultValues?

**Comment by bluebill1049** [comment]
> @bluebill1049 There is a method to change the defaultValues?

That's `reset(defaultValues)`
