### ISSUE TITLE
Checkbox is not checked for string default values

### ISSUE THREAD

**Issue by viniciusborges23** [react-hook-form/react-hook-form#1954]
When I set a default value for the checkbox as a string, it will not be checked on render. 

```
const defaultValues = {
  terms: "yes",
  categories: [null, "bar"]
};
```
Although, if you set as boolean it will work properly, but you will not be able to get the checkbox value on submit.

```
const defaultValues = {
  terms: true,
  categories: [null, true]
};
```

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-controller-g4sij

**Expected behavior**
I don't know if I'm missing something, but I would like to handle the checkbox as a string instead of boolean.

**Comment by bluebill1049** [comment]
I think you can find your answer here: https://stackoverflow.com/questions/61475234/material-ui-react-form-hook-multiple-checkboxes-default-selected

**Comment by viniciusborges23** [comment]
@bluebill1049 Yes, you are right. Thanks for your help.
