### ISSUE TITLE
Radio inputs do not work correctly with Control components

### ISSUE THREAD

**Issue by Stralos** [react-hook-form/react-hook-form#1964]
**Describe the bug**
When you have a controlled radio button inputs, clicking on any radio button but the last one sets the last radio button value to the currently selected radio buttons value. 

example:
If I have 3 controlled radio buttons with values: '1', '2', '3'.
I was to click on the radio button with value '3', my property inside the form data would have the value set to 3. Then if I were to click on a radio button of that has a value '2', and click back on the radio button of value '3', my property value would be set to value '2' not '3'.

**To Reproduce**
1. Click on Type 3 radio button
1. You will see that the current value of type is set to 3
2. Click on Type 1 radio button
3. You will see that the current value of type is set to 1
4. You will see that the current value of type is set to 3 (again)
5. You will see that the current value of type is set to 1 (it should be 3)

**Codesandbox link:**
https://codesandbox.io/s/elated-wozniak-72bnf?file=/src/App.js

**Expected behavior**
Clicking on any radio button should set the correct value in the form data.

**Screenshots**
A gif of showing the whole workflow and the bug: https://imgur.com/1Niske0

**Desktop (please complete the following information):**
 - OS: macOS Majove version 10.14.6
 - Browser chrome
 - Version 83.0.4103.116

**Additional context**
I saw that the HTML structure is being modified and the last radio button value is being changed when the user clicks on any of the radio buttons.

**Comment by bluebill1049** [comment]
Controller's name needs to be unique.

you will have to build a wrapper with radio input like MUI did: https://codesandbox.io/s/react-hook-form-controller-079xx

take a look at the example in above CSB link.

**Comment by Stralos** [comment]
You are correct. You can close the issue as it's a false bug report.
