### ISSUE TITLE
setValue bug?

### ISSUE THREAD

**Issue by anthonyatp** [react-hook-form/react-hook-form#1965]
Here is the expected behaviour of these inputs (working as of v5.4.2):

![RHF expected](https://user-images.githubusercontent.com/42555665/85760455-c2dbe100-b709-11ea-96ab-ccf0ff7a116b.gif)

However, after upgrading to version 5.5.3+, this is what happens:
![RHF bug](https://user-images.githubusercontent.com/42555665/85760522-d2f3c080-b709-11ea-8c0a-2ff7731004c1.gif)

I have a feeling this is something to do with the changes to `setValue`. v5.5.0 broke my setValue function - details about this were on this issue: https://github.com/react-hook-form/react-hook-form/issues/1465

And after this was fixed in v5.5.3, my inputs (shown above), seem to be broken.

**Codesandbox link**
I put together a similar set up in a codesandbox to replicate this bug:
https://codesandbox.io/s/react-hook-form-setvalue-bug-jb4wo?file=/src/InputRadio.tsx:964-969

Thank you in advance!

**Comment by bluebill1049** [comment]
please consider registering at `useEffect` with your use case

https://codesandbox.io/s/react-hook-form-setvalue-bug-tshpt?file=/src/InputRadio.tsx

**Comment by anthonyatp** [comment]
Perfect, thanks!

This is much better than having to include a hidden input element to register.
