### ISSUE TITLE
FormContext -> useFormContext -> "errors" undefined on callback execution

### ISSUE THREAD

**Issue by namrastanov** [react-hook-form/react-hook-form#1967]
Hello.
I actually don't know is it bug or I use it wrong way.

I have something like this:
```
<FormContext ...>
  <form>
    <FormInput ... />
  </form>
</FormContext>
```

in the FormInput I have something like this:
```
<FormField ... setIsFailed={setIsFailed}>
  <input ... className=<depend on isFailed()>
</FormField>
```

And finally in the FormField component I'm executing props.setIsFailed with the way of detecting "errors" depended on the name (I have complex enough name that is why I need to unify the way of detecting the error)

```
  const getError = () => {
    ....
    here the way how I'm getting error from "errors"
    ...
    return error;
  };

  useEffect(() => {
    if (!inited && props.setIsFailed) {

      props.setIsFailed(() => getError);

      setInited(true);
    }
  });
```

And sometime I have the empty "errors" in the "getError" when execute it's callback "isFailed" from FormInput component, but I see that at that moment there were errors on the field.

**Comment by bluebill1049** [comment]
please follow the issue template.
