### ISSUE TITLE
`handleSubmit` callback executes but `formState.isSubmitting` is still `false`

### ISSUE THREAD

**Issue by jannisg** [react-hook-form/react-hook-form#1969]
**Describe the bug**
We have conditional validation logic inside a `validate` function which changes fields to be required **only while submitting**.
In order to switch this around, I basically rely on the `isSubmitting` flag to inform the `required` state of the field validation function.

Here is a reduced `validate` function example (please see the Codesandbox though):
```js
const validate = value => {
    if (isSubmitting && !value.length) {
      return "This field is required";
    }
    return true;
  };
```

This means that:
- When **not** submitting, the field can be empty
- However, when submitting, if the field was left blank the field should be treated as required
- Using `isSubmitting` inside the `validate` function does not correctly fire during submission of the form

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-onsubmit-formstate-de-sync-whg42?file=/src/MyForm.js
2. Open the console to see the logs
3. Click the Submit button while leaving the input blank
4. See the issue where the validation function fires while `isSubmitting` is still `false` thus is not validating the blank value as an error

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-onsubmit-formstate-de-sync-whg42?file=/src/MyForm.js

**Screenshots**
The following shows the logging after clicking the "Submit" button.
![image](https://user-images.githubusercontent.com/109211/85806640-bd32d980-b7a3-11ea-8c7c-aef08fb72f46.png)

**Expected behavior**
1. When the `handleSubmit` function is triggered the `formState.isSubmitting` flag should be set to `true` so that conditional validation logic that uses `isSubmitting` to define its rules accurately validates the field.
2. Logic inside my `handleSubmit` callback should execute with the expectation that all validations or logic defined in my `onSubmit` handler run in context of `isSubmitting: true` until the `onSubmit` returns.

**Desktop (please complete the following information):**
 - OS: MacOS X 10.15.5
 - Browser: Chrome
 - Version 83.x

**Additional Information**
I realise this example seems really weird, why make a "required" field only sometimes required!?

The context for this rule is that we have a big form that is split across many tabs, each tab can be left blank and the form can submit simply ignoring blank tabs.

When the user is actively looking at the tab, then fields should be required OR if a tab has been modified (dirty fields inside) then the fields are also required.

BUT when the user encounters an API errors (client-side logic all okay, but API rejects the values submitted) the only way for a user to recover and submit the rest of the form (other tabs) is to clear the values from the field in which case the empty field is the desired state.

Hence why we end up with a validation logic where, the user can (and should) purposefully leave a field blank and this should **not** create a client side error. But if they submit the form and left the field they are seeing blank, then it is an error.

I hope that explains _why_ I need a field to be sometimes required but only during submit :)

**Comment by bluebill1049** [comment]
why are you logging those `formState` inside the onSubmit function? The `formState` is made for `render`, it lost the purpose inside the onSubmit function.

**Comment by bluebill1049** [comment]
I don't think in-build validation will work for your use case as well, you would need something customized which is more like validation `resolver`. The bug that you are reporting is by design, we don't invoke onSubmit unless all validation pass despite `formState` and reading `formState` inside onSubmit is not going to work out for you.

**Comment by jannisg** [comment]
Hmm, I see what you mean, but isn't the `validate` function part of the `render` loop so _should_ be able to access the `formState` values?

I mean if I write my `validate` fn as:
```js
const validate = useCallback((value) => {
   // ...
}, [formState.isSubmitting]);
```

Would this not ensure that the validate callback is reflecting the state of my render including the `isSubmitting` flag state?

Having just looked at the `validationResolver` docs, I am not entirely sure how I could feed the `isSubmitting` flag into that either, or are you suggesting I abandon the idea of using `formState.isSubmitting` entirely, write a custom resolver (removing all field level `validate` functions) and then fire this custom validation resolved _before_ I call `handleSubmit`?

Appreciate your quick reply :)

**Comment by bluebill1049** [comment]
I don't think there is a problem reading `formState` inside `validate`:
https://codesandbox.io/s/flamboyant-cloud-3ue0j?file=/src/App.tsx

also for `resovler`, you can inject `formState` into the `context`

**Comment by jannisg** [comment]
How would I pass `formState` as context to `resolver`?
Looking at the docs, it seems to be defined as part of `useForm` itself so `formState` isn't available yet?

```js
  // from the docs
  const { register, handleSubmit, errors } = useForm({
    validationResolver: resolver, // make sure to memorise callback or place it outside the component
    validationContext: { test: "test" }
  });
```

I'm guessing I would need to do something like this though this seems like it wouldn't work as I am feeding `formState` into `useForm` here:

```js
const { formState } = useForm({
  validationContext: formState,
});
```

Once i figure out how to build a resolver function and feed the `formState` into it, how would I set/hook into the `isSubmitting` state? It seems that even once this runs via the `resolver` function and not field-level `validate` functions, this would still be executed _before_ the `handleSubmit` function which sets `isSubmitting` to `true`?

**Comment by bluebill1049** [comment]
good point. you will have to do to something like this:

```
const formStateRef = useRef();
const { formState } = useForm({
  validationContext: formStateRef.current, 
});
formStateRef.current = formState;
```

which will start to work correctly on the second `render`.

**Comment by jannisg** [comment]
Right, that makes sense in terms of feeding it in, but wouldn't the `isSubmitting` still be `false`, given that the `resolver` would fire before `handleSubmit` sets `isSubmitting` to `true`?

**Comment by bluebill1049** [comment]
maybe it's much easier to maintain your own `isSubmitting` state then.

**Comment by jannisg** [comment]
Yea I think I might have to go that route. Appreciate the speedy replies on the matter :)
