### ISSUE TITLE
💈 Feature Requests

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#1981]
Any feature request will normally go through **waiting for upvotes** from the community and approved by the team members. You can refer to our [project board](https://github.com/react-hook-form/react-hook-form/projects/1) to check existing pending feature requests. The feature is ordered by votes so far. 

The following is a snapshot of our existing pending feature requests:
<img width="372" alt="Screen Shot 2020-06-28 at 1 17 36 pm" src="https://user-images.githubusercontent.com/10513364/85936849-bd68db80-b941-11ea-922e-2d32b0c7ab5f.png">

**Comment by Mendoza920** [comment]
I’m ready

**Comment by Mendoza920** [comment]
I don’t have any help and I did it all by myself. 
can u plz come down here.

**Comment by Mendoza920** [comment]
I don’t have any money and my kids are taking the 
Pain. Plz take my kids out the game.

**Comment by Mendoza920** [comment]
13862 Ponderosa St. apt. L
Santa Ana Ca. 92705

**Comment by Mendoza920** [comment]
Apt. N
