### ISSUE TITLE
we need a way to force form to not unregister specific inputs 

### ISSUE THREAD

**Issue by MHA15** [react-hook-form/react-hook-form#1982]
first of all thanks for your great library

**Is your feature request related to a problem? Please describe.**
I had started to use this library an I was so excited about it, but in two place I got have problem 
this library is work with prestructured forms very well but there are two cases that we got problem

first: as you know if we change react tree and add a parent to an specific element, react will remove it and create a new one, so when we have an input which might have a parent conditionally react will remove it and create another one again which cause to reregister that input inside formState and remove reset its value 
```js
function MyForm() {
   const {register} = useForm();

  const input = <input name="firstname" ref={register}/>;

   return (
      <form>
       {isDesktop ? <span>{input}</span> : input}
      </form>
   );

}
```
[codesandbox](https://codesandbox.io/s/frosty-bash-n0tfb?file=/src/App.tsx
)

second: sometimes we have a form with two or more steps which will get some input values in each steps and wants to submit it in the last step, in this case we want to remove `StepComponent` and its inputs from our dom tree but we want their value to not unregister from our form
```js

function MyForm() {
   const {register} = useForm();

  // Step1Component and Step1Component have some inputs in their body
  return (
   <form>
    {step == 0 && <Step1Component register={register} />} 
    {step == 1 && <Step2Component register={register} />}
   </form>
  );
}
```
[codesandbox](https://codesandbox.io/s/nice-villani-xvf13?file=/src/App.tsx)
 

**Describe the solution you'd like**
I have two solution for first problem and only one will work for second problem
1. register fields in `MyForm` component and never unregister them until `MyForm` unregister them  (works for both problems)
2. in problem one we are unregister a field with name X and register it immediately again with same name which can be handled internally to not reregistering a field with same  name

**Comment by bluebill1049** [comment]
Take a look `shouldUnregister` https://github.com/react-hook-form/react-hook-form/releases/tag/v6.0.0-rc.4, we are release V6 in the next couple days.

**Comment by MHA15** [comment]
> we are release V6 in the next couple days.

thank you for your great news



> Take a look `shouldUnregister` https://github.com/react-hook-form/react-hook-form/releases/tag/v6.0.0-rc.4

this `shouldUnregister` will affect all inputs , shouldn't we have some thing that let us prevent unregistering specific inputs?

**Comment by bluebill1049** [comment]
> > we are release V6 in the next couple days.
> 
> thank you for your great news
> 
> > Take a look `shouldUnregister` https://github.com/react-hook-form/react-hook-form/releases/tag/v6.0.0-rc.4
> 
> this `shouldUnregister` will affect all inputs , shouldn't we have some thing that let us prevent unregistering specific inputs?

no, then you should use `unregister` or store your input value in a state machine.

**Comment by MHA15** [comment]
thank you so much
