### ISSUE TITLE
What type to use? useFieldArray

### ISSUE THREAD

**Issue by natac13** [react-hook-form/react-hook-form#1986]
**Describe the bug**
I am trying to use `useFieldArray` with an array of primitive values (numbers). I am new to typescript and just cannot seem to figure out how to make the type error go away

**To Reproduce**
See this code sand box
https://codesandbox.io/s/react-hook-form-usefieldarray-f893z?file=/src/index.tsx

**Expected behavior**
To get the type error to clear

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-usefieldarray-rzfb8?file=/src/index.tsx

**Comment by natac13** [comment]
So it has to be an array of objects? not just an array of strings?

**Comment by bluebill1049** [comment]
> So it has to be an array of objects? not just an array of strings?

Yes.

**Comment by natac13** [comment]
Now I see that is perfect as react-hook-form gives me an id for free!

https://codesandbox.io/s/react-hook-form-usefieldarray-f893z?file=/src/index.tsx
