### ISSUE TITLE
setError with multiple fields

### ISSUE THREAD

**Issue by natac13** [react-hook-form/react-hook-form#1987]
**Describe the bug**
I cannot seem to get `setError` to set multiple field errors at once? I thought this was possible from these [docs](https://react-hook-form.com/api#setError).
But after reviewing [this commit](https://github.com/react-hook-form/react-hook-form/commit/acd62142578091ceea13eb6beb2f533533e0ac2d#diff-a022cc055e49d2a0542ef4e2f4648587L683-L700) and using this [CSB](https://codesandbox.io/s/react-hook-form-set-error-clear-error-og9nn?file=/src/index.js
) I do not think this is possible any more? True? Is there a reason why? The use case is receiving errors from the server and setting them all at once without multiple rerenders 

**To Reproduce**
https://codesandbox.io/s/react-hook-form-set-error-clear-error-og9nn?file=/src/index.js

**Expected behavior**
Set multiple errors as the docs state.

**Edit**
Can this happen? https://github.com/react-hook-form/react-hook-form/pull/1907#issuecomment-646369401

**Comment by bluebill1049** [comment]
you can still set multiple errors in V5, however in v6 we are fixing this confusing API, setError is made for set single error and not multiple, for multiple the API name should be `setErrors`. I would suggest using `.forEach` with `setError` after V6. This is documented in the migration guide.

**Comment by natac13** [comment]
Yeah I have pulled down the rc of 6 to start migrating from formik. Thanks for the clarification and great library.
