### ISSUE TITLE
Cleanup errors when component is being destroyed

### ISSUE THREAD

**Issue by crabkiller** [react-hook-form/react-hook-form#199]
https://codesandbox.io/s/react-hook-form-basic-qgeyx

My page contains a `Tab` which would trigger different components being rendered. When previous `Tab` trigger a validation and has some errors, now I switch to the another `Tab` my `errors` which is received from `useForm` remains the previous errors, so my validation can't be valid. I think the previous errors should be cleanup.

**Comment by bluebill1049** [comment]
Why not use `clearError` when you switch the tab? you can now call without argument and clear all errors `clearError()`

**Comment by crabkiller** [comment]
I will try this. Thank you. On the other hand, maybe `react-hook-form` should clear the corresponding errors when some component is destroyed?

**Comment by bluebill1049** [comment]
I agree, will patch that behavior.

**Comment by bluebill1049** [comment]
try this beta version: `3.21.12-beta.1` should resolve this issue. Let me know how it goes.

**Comment by bluebill1049** [comment]
This has been patched in the latest release.

**Comment by bluebill1049** [comment]
please close this issue once you verify.
