### ISSUE TITLE
Form's values get lost after hide / show form in render

### ISSUE THREAD

**Issue by kurdin** [react-hook-form/react-hook-form#1990]
**Describe the bug**
If I have Form with values and I want to show custom input to specify custom value and hide From, after Form shows in render it 's values get lost and you need to touch any control to see those values again. 

**To Reproduce**
1. load https://codesandbox.io/s/react-hook-form-set-inputselect-value-z87ce
2. in `Age group` select `+ add`. This hides Form element and show single input field where you can add custom age number. 
3. enter number `4` and press Enter
4. open console and see `formValues` is completely empty `Object {}`
5. scroll up and enter in input `First Name` anything, now in console `formValues` has form values
6. or press `submit` button and form has submit data even if `formValues` was empty after step 3

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-set-inputselect-value-z87ce

**Expected behavior**
`formValues` should not be empty

**Desktop (please complete the following information):**
macosx (latest), chrome (latest)

**Comment by bluebill1049** [comment]
That's expected behavior think about it when you building a native form without React's state, when input is removed its state will get lost as well. I think it's important to understand the rationale behind the design.

However, in v6 we do have the option to not lost input state after unmount, `shouldUnregister`: https://github.com/react-hook-form/react-hook-form/releases/tag/v6.0.0-rc.4

**Comment by kurdin** [comment]
@bluebill1049 Thank you for explaining. 
Yea, I understand why you have this pattern, so you can manipulate  final Form's state but adding/removing elements in render if needed, sure this can be useful in some cases. 

I do use `display: 'none'` workaround and it works as expected without losing `formValues` will try `shouldUnregister: false` as well, thanks for the tip.

Thanks again on doing a great job with `react-hook-form`, thank you for many useful features to covering all use cases. 👍

**Comment by bluebill1049** [comment]
@kurdin awesome to hear! thank you too 🙏

**Comment by kurdin** [comment]
@bluebill1049 sorry to reopen but I added ` shouldUnregister: false` to my example above and it seems like `formValues` still empty after Form shows and `setValue("ageGroup", val);` not working at all on line 26. This is definitely looks like a bug.

**Comment by bluebill1049** [comment]
can you share the steps to reproduce?

**Comment by bluebill1049** [comment]
just reproduced the issue: https://codesandbox.io/s/react-hook-form-set-inputselect-value-mcbx6?file=/src/index.js

patching it.

**Comment by bluebill1049** [comment]
This issue above needs some careful consideration, we will delay the release of this after V6.

**Comment by paulkarpenko** [comment]
@bluebill1049 I ran into this issue as well and made my own CodeSandbox before finding this thread 😂  https://codesandbox.io/s/serene-heisenberg-j2v4t — It happens for me on v5.7.2 and v6.0.0-rc.4 with `{ shouldUnregister: false }` Can you confirm this is the same issue as above? 

My team is working on a feature that requires displaying an always-updated `getValues()` object because our field array is in a modal that goes away and `display: none` is not an option. Can you recommend a temporary workaround while you're unable to patch?

Thank you and big props for the awesome library!

**Comment by bluebill1049** [comment]
hey @paulkarpenko take a look at this codesandbox for v5 https://codesandbox.io/s/react-hook-form-conditional-inputs-c7n0r.

with v6 `shouldUnregsiter` input value will remain even component gets unmounted, the question is should we support setValue, watch, getValues for unmounted inputs within the team. I will keep you guys updated.

**Comment by paulkarpenko** [comment]
Thank you for the prompt reply, @bluebill1049!

I don't believe this example captures my usecase because the `mail` field in the modal isn't part of the same form as the other fields. My modal form fields use the same context as the main form, and when the field array in the modal gets unmounted, I can no longer see the array values with `getValues()`

I've updated my example to show my issue more clearly: https://codesandbox.io/s/serene-heisenberg-j2v4t
If the array fields are hidden, and you reset them to a value, `getValues()` will not show the values after the next re-render.

**Comment by bluebill1049** [comment]
@paulkarpenko Thanks for the codesandbox, i think that's this PR https://github.com/react-hook-form/react-hook-form/pull/1994 try to fix.

**Comment by paulkarpenko** [comment]
@bluebill1049 Thank you! This commitment to the community is what makes this library one of the best I've used, hands down 🙏

**Comment by gabrielMoran23** [comment]
Hello i have the same problem, i dont want to use display:none, and  shouldUnregister doesn't work,

**Comment by bluebill1049** [comment]
> Hello i have the same problem, i dont want to use display:none, and shouldUnregister doesn't work,

share a codesandbox.

**Comment by gstcarv** [comment]
hello i'm also having the same problem. 
apparently `shouldUnregister: false` is not working in my case.

https://codesandbox.io/s/proud-pond-i5chn

just press **add** button on the **blacklist** tab, change the data and switch to the **contacts** tab.
when returning to the **blacklist** tab, the input data was lost, even using the `shouldUnregister` prop

(I could just remove `isLazy` property from `People.js`, but I don't as it would result in performance issues on larger forms)

**Comment by bluebill1049** [comment]
> hello i'm also having the same problem.
> apparently `shouldUnregister: false` is not working in my case.
> 
> https://codesandbox.io/s/proud-pond-i5chn
> 
> just press **add** button on the **blacklist** tab, change the data and switch to the **contacts** tab.
> when returning to the **blacklist** tab, the input data was lost, even using the `shouldUnregister` prop
> 
> (I could just remove `isLazy` property from `People.js`, but I don't as it would result in performance issues on larger forms)

Thanks for the CSB, by default, react hook form doesn't track input onChange by default for better performance, and hence toggle on and off doesn't show the latest input value. expect each field array action is tracked. however, you can work around this issue by letting hook form know that you want to track each change with `useWatch`. the following CSB demonstrates the behavior.

https://codesandbox.io/s/keen-brown-qybti?file=/src/App.js

**Comment by gstcarv** [comment]
> > hello i'm also having the same problem.
> > apparently `shouldUnregister: false` is not working in my case.
> > https://codesandbox.io/s/proud-pond-i5chn
> > just press **add** button on the **blacklist** tab, change the data and switch to the **contacts** tab.
> > when returning to the **blacklist** tab, the input data was lost, even using the `shouldUnregister` prop
> > (I could just remove `isLazy` property from `People.js`, but I don't as it would result in performance issues on larger forms)
> 
> Thanks for the CSB, by default, react hook form doesn't track input onChange by default for better performance, and hence toggle on and off doesn't show the latest input value. expect each field array action is tracked. however, you can work around this issue by letting hook form know that you want to track each change with `useWatch`. the following CSB demonstrates the behavior.
> 
> https://codesandbox.io/s/keen-brown-qybti?file=/src/App.js



> > hello i'm also having the same problem.
> > apparently `shouldUnregister: false` is not working in my case.
> > https://codesandbox.io/s/proud-pond-i5chn
> > just press **add** button on the **blacklist** tab, change the data and switch to the **contacts** tab.
> > when returning to the **blacklist** tab, the input data was lost, even using the `shouldUnregister` prop
> > (I could just remove `isLazy` property from `People.js`, but I don't as it would result in performance issues on larger forms)
> 
> Thanks for the CSB, by default, react hook form doesn't track input onChange by default for better performance, and hence toggle on and off doesn't show the latest input value. expect each field array action is tracked. however, you can work around this issue by letting hook form know that you want to track each change with `useWatch`. the following CSB demonstrates the behavior.
> 
> https://codesandbox.io/s/keen-brown-qybti?file=/src/App.js

If I'm correct, the scope of useWatch is limited to the component, right? In that case it wouldn't impact much on the performance of large forms. That's right?

**Comment by gstcarv** [comment]
> Thanks for the CSB, by default, react hook form doesn't track input onChange by default for better performance, and hence toggle on and off doesn't show the latest input value. expect each field array action is tracked. however, you can work around this issue by letting hook form know that you want to track each change with `useWatch`. the following CSB demonstrates the behavior.
> 
> https://codesandbox.io/s/keen-brown-qybti?file=/src/App.js

If I'm correct, the scope of useWatch is limited to the component, right? In that case it wouldn't impact much on the performance of large forms. That's right?

**Comment by bluebill1049** [comment]
@gstcarv i use useWatch for large and complex form, so the re-render is completely isolated.

**Comment by DAJAKMPM** [comment]
is there a way in v5 to disable the unregistering of the fields? since v5 does not have shouldUnregister property yet in useForm
