### ISSUE TITLE
useForm invokes validationResolver immediately in IE11

### ISSUE THREAD

**Issue by tonycassara** [react-hook-form/react-hook-form#1993]
**Describe the bug**
We define a hook `useForm({ validationResolver: (values) => console.log('hey', values) })` and see the that `validationResolver` is called immediately on load when using IE11 rollup config. This does not happen in Chrome or Firefox or Safari. This is producing undefined/null values in our case and breaking our application.

**To Reproduce**
1. Open the app in IE11 and use `import { useForm } from 'react-hook-form/dist/react-hook-form.ie11';`
2. Define a new form using `useForm({ validationResolver: (values) => console.log('hey', values) })`
3. Observe the page immediately invokes the `validationResolver`

**Codesandbox link (Required)**
I'm sorry but CodeSandbox doesn't seem to work in IE11 😞

**Expected behavior**
Validation is not run on initialization of `useForm`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: IE11
 - Version: Latest (Browserstack)

**Additional context**
We made a temporary workaround by returning early if the values object is full of only undefined/null properties:
```
if (Object.values(values).filter((val) => !!val).length === 0) {
  return { errors: {}, values };
}
```

**Comment by bluebill1049** [comment]
which version?

**Comment by bluebill1049** [comment]
going to close this issue for now until more details can be supplied to help investigate for IE problem.

**Comment by tonycassara** [comment]
IE11, latest react-hook-form. Not subscribed to formState. We removed the library because of this 😕

**Comment by bluebill1049** [comment]
> IE11, latest react-hook-form. Not subscribed to formState. We removed the library because of this 😕

Do you mean v6?

**Comment by frank-martinez-27** [comment]
This happens to me as well, any news on this issue?
