### ISSUE TITLE
triggerValidation(name) returns false even for correct value, if you use a yup validationSchema and there are other errors in form

### ISSUE THREAD

**Issue by abaerike** [react-hook-form/react-hook-form#1996]
Hi,
we are using react-hook-form with a yup validationSchema and encountered a Problem. If you have several inputs on your page and one of them has an error, all triggerValidation() requests will return false, even if you only send them for one specific field.

e.g: you habe firstname and surname. There is an error in firstname. If I now use triggerValidation(surname), it will return false, even if the value for surname is correct. It also (correctly) sets no error for surname.

CodeSandbox: https://codesandbox.io/s/react-hook-form-validationschema-3reg3?file=/src/index.js:426-442

click on "senden" to trigger errors, then change firstname and trigger validation on blur. You can see the different behaviour if you acitvate or deactivate 'validationSchema: SignupSchema' in line 20.

Is it possible to change that behaviour?

Thanks,
Anja

**Comment by bluebill1049** [comment]
Hey Anja, can you try with the latest version?

**Comment by abaerike** [comment]
Hi, I'm now on Version 6.0.0-rc.5 and changed everything depending on the breaking changes. Same error still occurs. Now with validate() and yupResolver.

**Comment by bluebill1049** [comment]
why there is a `ref={register({ required: true })}`, you can't combining with validation schema. you have to use either.

**Comment by abaerike** [comment]
This is just to show the error. In our form we only use the schema. In the Sandbox I just wanted to show the different behaviour of triggerValidation on usind schema or no schema.

**Comment by bluebill1049** [comment]
This looks correct to me: https://codesandbox.io/s/react-hook-form-validationschema-z05sr?file=/src/index.js

**Comment by abaerike** [comment]
@bluebill1049 No, it's not. Click on "senden" to provoke errors. Then enter firstname and blur on that input. You woll see in the console logs that triggerValidation('firstName') returns false. It should return true.
