### ISSUE TITLE
Using react-number-format within a controller throws 'TypeError: (intermediate value)(intermediate value).lastIndexOf is not a function'

### ISSUE THREAD

**Issue by nlrowe** [react-hook-form/react-hook-form#1997]
I have been using `Controller` and `NumberFormat` without issue with react-hook-form 4.9.6. I upgraded to v5.7.2 (it looks like the error was introduced in v4.10.0) to take advantage of a new feature and now the combination gives the following error on change:

'TypeError: (intermediate value)(intermediate value).lastIndexOf is not a function'

Code Sandbox: https://codesandbox.io/s/small-sunset-11kpe?file=/src/App.js

**To Reproduce**
1. Change field in code sandbox
2. Error shows in console

**Expected behavior**
No error occurs

**Comment by bluebill1049** [comment]
I think v6's render props should resolve this issue.

**Comment by bluebill1049** [comment]
Take a look here, worth to give a try : https://github.com/react-hook-form/react-hook-form/releases/tag/v6.0.0-rc.2

**Comment by nlrowe** [comment]
Thanks for the feedback! In the same application I do have some more complex implementations that I don't want to risk introducing bugs to. Is there something you would recommend in the mean time on v5? Preferably not reverting to manual management for the inputs?

**Comment by bluebill1049** [comment]
looks like you have a problem with the `register`, controller already takes care of the register, so you shouldn't need to do that again.

https://codesandbox.io/s/priceless-germain-mzkhn?file=/src/App.js
