### ISSUE TITLE
Form does not revalidate errored fields after trigger has been called

### ISSUE THREAD

**Issue by NathanWild** [react-hook-form/react-hook-form#2009]
**Describe the bug**
When calling `trigger()` on a form, any changes on errored inputs thereafter do not cause the form to revalidate and `errors` object is held with the previous errors.

Specifically setting `{ reValidateMode: "onChange" }` does not affect this either _(although this is the default according to the docs)_.

**To Reproduce**
1. Navigate to the codesandbox link.
2. Leave fields empty and hit the 'Trigger' button. The `errors` object should now be populated with the required fields.
3. Change the errored fields to values that will pass validation.
4. The form does not listen to these changes and does not revalidate. The `errors` object still contains the previous errors.
5. Once submitting the form, this then works as expected and changes are revalidated.

**Codesandbox link (Required)**
- https://codesandbox.io/s/react-hook-form-trigger-validation-f43k9?file=/src/index.js

**Expected behavior**
Upon calling `trigger()`, any further changes to the errored inputs should cause a revalidate to occur similarly to when submitting a form.

**Comment by bluebill1049** [comment]
This is expected behavior, `trigger` is not submitting the form. revalidate only kick in after submit.

**Comment by NathanWild** [comment]
> This is expected behavior, `trigger` is not submitting the form. revalidate only kick in after submit.

If this is the case the docs are slightly misleading, for `reValidateMode ` they state "This option allows you to configure when inputs with errors get re-validated (by default, validation is triggered during an input change.)"

I would expect based on this that the form would attempt to revalidate errored fields regardless of after submit or trigger.

**Comment by bluebill1049** [comment]
will add the key words **after submit**.

**Comment by bluebill1049** [comment]
patched the doc: https://github.com/react-hook-form/documentation/commit/26a7c208f3b85010e49f59aa83aa72924b4b8f4f
