### ISSUE TITLE
After submit, the scroll to error input has two behaviours (chrome and firefox/edge)

### ISSUE THREAD

**Issue by jmgirao** [react-hook-form/react-hook-form#2012]
**Describe the bug**
The scroll to error input has two behaviours:
In Chrome: The input error is all visible.
In Firefox/Edge: The input error is only visible <input> and not with label. The input error go to the top. offsetTop: 0

Maybe, the scroll approach between Chrome and Firefox/Edge is different.

**To Reproduce**
1. Click on Submit Button
2. See the first input error in Chrome and Firefox

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-errors-w909p

**Expected behavior**
The firefox and edge should follow Chrome behaviour.

**Desktop (please complete the following information):**
 - Browser: Firefox and Edge

**Comment by bluebill1049** [comment]
This is out of our control :(.

**Comment by SAGARACH65** [comment]
Hi @bluebill1049 . I was looking through the code for this. I noticed we were using `.focus()` on refs. How about using` .scrollIntoView()`?

I tried a mockup in sandbox for this.
`    this.ref.current.scrollIntoView({ behavior: 'smooth', block: 'start' });
`
This causes the scroll to work consistently in firefox and chrome. I think this has support for IE11 too

**Comment by bluebill1049** [comment]
Thanks @SAGARACH65, the only issue is that this behavior is not consistent between different browser, also it does conflict with focus. I would recommend you to disable `shouldFoucsError` and in the errors object you still have the input ref and scroll into the view.
