### ISSUE TITLE
Nested Field Array Not Moving Errors

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#2017]
**Describe the bug**
Nested Field Array Not Moving Errors
https://spectrum.chat/react-hook-form/help/nested-field-array-not-moving-errors~da833f41-0e19-4b32-adb8-f22feb97800a

https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-e616x?file=/src/nestedFieldArray.js.

**To reproduce the issue I am seeing:**
- Click 'Append Nested' twice
- Put a value into 'Sub Nested Array'[0] input
- Click in and out of 'Sub Nested Array'[1] input to trigger a blur error (input will have 'ERROR' in red under it)
- Click the 'Move Nested' button (hard coded to move 'Nested Array'[0] to 'Nested Array'[1])

**What happens:**
- 'Sub Nested Array' inputs swap
- 'Sub Nested Array'[1] error stays at 'Sub Nested Array'[1]

**What is expected:**
'Sub Nested Array'[1] error moves to 'Sub Nested Array'[0] as the value does
Any ideas on what I am doing wrong?

**Comment by nlrowe** [comment]
This fix works for the presented case. However, if you reverse the actions:
- Click 'Append Nested' twice
- Put a value into 'Sub Nested Array'[1] input
- Click in and out of 'Sub Nested Array'[0] input to trigger a blur error (input will have 'ERROR' in red under it)
- Click the 'Move Nested' button (hard coded to move 'Nested Array'[0] to 'Nested Array'[1])

The error stays on 'Sub Nested Array[0]'. Updated [codesandbox](https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-6sht8?file=/src/nestedFieldArray.js) to use v6.0.6.

**Comment by bluebill1049** [comment]
can you try this fix: https://github.com/react-hook-form/react-hook-form/issues/2257
