### ISSUE TITLE
Export `ValidationRules` type

### ISSUE THREAD

**Issue by MainAero** [react-hook-form/react-hook-form#2025]
Just updated to `v6` and recognized that the `ValidationRules` type is not exported anymore.
Any chance of exporting it again?

**Comment by MainAero** [comment]
Exporting types for `register` would be as well helpful.
I'm using kind of generic components where the register method is a render prop.

**Comment by jaypalexa** [comment]
As a temporary workaround, I am doing this...not sure it is the correct thing to do, but it made the squigglies go away:
```
import { ValidationRules } from 'react-hook-form/dist/types/form';
```

**Comment by ashernguyen** [comment]
I think it's really helpful to export all the types from `types/form`.  Especially when creating `Smart Form`

**Comment by bluebill1049** [comment]
shall we export `ValidationRules`? @kotarella1110 

@ashernguyen we are going to be more careful on what we export from V6, because anything we change in the type will lead to breaking changing, so better be careful and document the type that is exported.

**Comment by kotarella1110** [comment]
@bluebill1049 Let's export `ValidationRules` type.
Can I create this PR?

**Comment by bluebill1049** [comment]
sounds good @kotarella1110 I will update the doc as well to reflect this. 👍

**Comment by bluebill1049** [comment]
@MainAero what's your usage like? so i can add an example in the doc.

**Comment by ghostd** [comment]
I had the same problem and my usage is I dynamically build the rules from fetched data; so i need to type my "rules builder" function to return a `ValidationRule`

**Comment by bluebill1049** [comment]
can you share the code useage?

**Comment by ghostd** [comment]
Here is a simplified version:

```typescript
const buildRules = (intl: IntlShape, metaData: MetaData | undefined): ValidationRules => {
  const rules: ValidationRules = {
    required: intl.formatMessage({ id: 'errors.required' }),
  };

  if (!metaData) {
    return rules;
  }

  if (metaData.minLength) {
    rules.minLength = {
      value: metaData.minLength,
      message: intl.formatMessage(
        { id: 'errors.minLength' },
        {
          fieldName: metaData.label,
          minLength: metaData.minLength,
        }
      ),
    };
  }

  if (metaData.maxLength) {
    rules.maxLength = {
      value: metaData.maxLength,
      message: intl.formatMessage(
        { id: 'errors.maxLength' },
        {
          fieldName: metaData.label,
          minLength: metaData.maxLength,
        }
      ),
    };
  }

  if (metaData.format) {
    rules.pattern = {
      value: PATTERNS[metaData.format],
      message: intl.formatMessage(
        { id: 'errors.pattern' },
        {
          fieldName: metaData.label,
          patternDescription: intl.formatMessage({ id: `pattern-description.${metaData.format}` }),
        }
      ),
    };
  }

  return rules;
};

```
