### ISSUE TITLE
triggervalidation is not a function 

### ISSUE THREAD

**Issue by keeganstothert** [react-hook-form/react-hook-form#2028]
v6.0.0

`Uncaught (in promise) TypeError: triggerValidation is not a function`

[sandbox](https://codesandbox.io/s/lucid-pond-cj9xm?fontsize=14&hidenavigation=1&theme=dark)

the linked sandbox demonstrates the issue

**Comment by keeganstothert** [comment]
it looks like the documentation needs to be updated for v6.0.0 as the api seems to have changed from `triggerValidation` to `trigger`

**Comment by bluebill1049** [comment]
@keeganstothert take a look the doc, it's been updated :) do a hard refresh maybe.

**Comment by keeganstothert** [comment]
am i crazy or is it still showing triggerValidation?

<img width="1446" alt="Screen Shot 2020-07-03 at 9 21 24 AM" src="https://user-images.githubusercontent.com/3612936/86485853-11473c00-bd17-11ea-802e-b82ace2c8421.png">

**Comment by bluebill1049** [comment]
wow you are not, next time please send a PR like this. 👍
