### ISSUE TITLE
Disable/enable submit button

### ISSUE THREAD

**Issue by Hrommi** [react-hook-form/react-hook-form#203]
Hi.

I need disable submit button after form sending and enable button after user change value any inputs. I try use `isSubmitted`, but I don't now how reset this value.

Sorry for my English.

**Comment by bluebill1049** [comment]
hi @Hrommi reset the value? Do you mean the form values? https://react-hook-form.com/api#reset

**Comment by bluebill1049** [comment]
or you mean `isSubmitted` value?

**Comment by Hrommi** [comment]
@bluebill1049 look this solution: https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-95rt3

I add

`const [isSubmitted, setIsSubmitted] = useState(false);`

and

`
useEffect(() => {
  setIsSubmitted(false);
}, [watch("First name"), watch("Last name")]);
`

It's ok?

`reset` clears all fields, but I do not need to do this.

**Comment by bluebill1049** [comment]
your solution is fine :)

FYI: you can pass an argument for `reset` too
```
reset({
  'First name': 'any',
  'Last name': 'any',
})
```

**Comment by Hrommi** [comment]
Thanks.

I don't now how call `reset` after change input with the correct value.

**Comment by bluebill1049** [comment]
kk 👍
