### ISSUE TITLE
react-hook-form is not compatible with the latest react version, fails on FormContext

### ISSUE THREAD

**Issue by DevTomaszKrupa** [react-hook-form/react-hook-form#2030]
Hi.

I've updated packages in my project and found out that the react and react-hook-form are not compatible in versions:
react: 16.13.1 [newest]
react-hook-form: 6.0.0 [newest]

The app crashes when using the FormContext.

**To Reproduce**
Install the following packages and try to run the example from react-hook-form website (Advanced -> FormContext Performance)

**Codesandbox link (Required)**
https://codesandbox.io/s/purple-cloud-62xn0?fontsize=14&hidenavigation=1&theme=dark

**Comment by ctalvarez** [comment]
renamed FormContext to FormProvider 
[https://react-hook-form.com/migrate-v5-to-v6 ](url)

**Comment by DevTomaszKrupa** [comment]
Cool, it works, so the documentation is a bit confusing

**Comment by bluebill1049** [comment]
@DevTomaszKrupa can you point me where is the mistake, will get it updated.

**Comment by MHA15** [comment]
> @DevTomaszKrupa can you point me where is the mistake, will get it updated.

in [this](https://react-hook-form.com/advanced-usage#FormContextPerformance) part of docs it is using FormContext instead of FormProvider

**Comment by bluebill1049** [comment]
any chance to send a PR @MHA15 ?

**Comment by bluebill1049** [comment]
nvm I will sort it out myself 👍
