### ISSUE TITLE
[v6] - watch returns defaultValue after moving an item in a fieldArray

### ISSUE THREAD

**Issue by tafelito** [react-hook-form/react-hook-form#2031]
**Describe the bug**
Not sure if this is an error or is it by design. Having a `fieldArray`, when you move one of the items,  the watch for the FA first returns the default value of the array and then the updated value. I'm not sure why the watch runs twice, but if it does, shouldn't it return the latest value instead of the default?

**To Reproduce**
1. add 4 items to the list
2. move 1 item
3. see console log (it shows first the watch result with the initial value of the FA and then the updated value)

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-mnemu?file=/src/index.js

**Comment by bluebill1049** [comment]
This is by design when `useFieldArray` combined with `watch`, because `watch()` is invoked before re-render for Field Array,  when user delete an input it could be at the start, end, or in between, it's easier to flush out the fields in the memory and reshuffle all inputs position, however, this leads to empty fields in memory and watch can't find value to return and hence returned `default values`. So the second re-render for `watch` will be the correct results because all inputs have been successfully mounted and watch can retrieve the `values` now.

**Comment by tafelito** [comment]
The problem I have with that is for e.g., if you have an item on the list that is selected (meaning you have the index of an item in a state variable), and you show some details based on that item, then if you move it, when the first render happens, you might end up not having that item for a second, or maybe the wrong item, so you see a flash on the screen.
Since you try to previously solve this within the library, have you ever come up to a solution for something like that even if it's in userland?

**Comment by bluebill1049** [comment]
valid point. I think probably do a compare with `defaultValues` if equal just ignore that `render`.

**Comment by tafelito** [comment]
what do you mean by ignore the render? 
what if the FA is deep nested in the component tree? I would have to pass the defaullt values as a prop, since I don't think the `useFormContext` gets you the default values

**Comment by bluebill1049** [comment]
maybe try this: https://codesandbox.io/s/react-hook-form-usefieldarray-034no?file=/src/index.js

**Comment by tafelito** [comment]
if you have nested objects, you end up with an issue.

Try adding an element and write something on the input here
https://codesandbox.io/s/react-hook-form-usefieldarray-mnemu?file=/src/index.js

**Comment by bluebill1049** [comment]
what's the steps?

**Comment by tafelito** [comment]
1. append
2. write something on the input
3. look the error in the console

**Comment by bluebill1049** [comment]
<img width="676" alt="Screen Shot 2020-07-03 at 1 00 31 pm" src="https://user-images.githubusercontent.com/10513364/86427292-2dee6e80-bd2d-11ea-95dd-1371609f39b9.png">

This error? due to Controller without `defualtValue`? I will take a closer look after work.

**Comment by tafelito** [comment]
sorry you're right that error is because of the default value. But the error I meant was different. If you look the content of fields vs the watch, the fields when they are initially created have a `generatedId` but then, once the input is initialized, the generatedId is lost. In this example there is no error, but in my case, I'm using that id to look for the selected item, so if I use the fields as the default value, I don't have the `generatedId`

**Comment by bluebill1049** [comment]
can you keep track with your own ID?

**Comment by tafelito** [comment]
I tried to come up with an example as close as what I have as possible. So to reproduce the issue I'm having the steps are

1. Append a new item
2. Click on the recently appended item
3. Put some value in the input
3. Append 4 items more and repeat 2 & 3
4. Click on move.

**Comment by bluebill1049** [comment]
Thanks will take a look at it.

**Comment by bluebill1049** [comment]
sorry about the delay, too busy with things... looking now :(

**Comment by bluebill1049** [comment]
hmmm, I can see the flicking, that's not great, is that even you do that default value with `watch`?

**Comment by tafelito** [comment]
> hmmm, I can see the flicking, that's not great, is that even you do that default value with watch?

Yes, and the reason is that the fields variable from `useArrayFields` doesn't keep all the values. Only those that you added using append, insert, etc but not the values you modify with the `Controller` 

And even If I keep a reference of the previous values, and I use them as the default, when moving an item, the item is copied to a new index, but since I'm using the prev values as a default, then the new values will have the new item at the correct index, but also at the old position

So if I have something like this

```js
[
   0: {
    activities: {
      name: 'Football'
    },
    location: {
       state: "NY",
       city: 'New York'
    },
  },
  1: {
    activities: {
      name: 'Tennis'
    },
  },
  2: {
    activities: {...},
  },
  3: {
    activities: {...},
  },
]
```

and then you move index 0 to 1, you end up with this

```js
 [
   0: {
    activities: {
      name: 'Tennis'
    },
    location: {
       state: "NY",
       city: 'New York'
    },
  },
  1: {
    activities: {
      name: 'Football'
    },
    location: {
      state: "NY",
      city: 'New York'
   },
  },
  2: {
    activities: {...},
  },
  3: {
    activities: {...},
  },
]
```

To put you in context,  of what I'm doing is similar to a canvas board, like `trello`.

Another way I solved this before but I was trying to avoid, is to manually handle the values myself, using `getValues` and then `setValues`. But the problem with that approach is that there a lot of thing I have to handle my self, like validation, that I would get if I could use a field array

I'm not sure if it's possible, but I guess the only way I see this working is if either the fields property from the `useFieldArray` hook return all the values, or if the watch would always return the current value

**Comment by tafelito** [comment]
this is another approach that didn't work either

https://codesandbox.io/s/react-hook-form-usefieldarray-template-mj7vm?file=/src/index.js

**Comment by bluebill1049** [comment]
I did think about this last night, I give it try today, this may be a tricky one, because form state lives inside inputs.

**Comment by bluebill1049** [comment]
i got an idea, the problem is one of the render watch return defaultValue because inputs ref gets reset, how about cache previous `watch` value, and doing a delete in the previous value as watch default value.

```
const value = watch();
previousWatch.current = value

watch('test', deleteByIndex(previousWatch.current))
```

just an idea above.

**Comment by tafelito** [comment]
you mean something like this ? https://codesandbox.io/s/react-hook-form-usefieldarray-qmyp1?file=/src/index.js
Still does not work

Ideally, I think https://codesandbox.io/s/react-hook-form-usefieldarray-template-mj7vm?file=/src/index.js is way easier to implement but I'm not really sure why it doesn't work.

**Comment by bluebill1049** [comment]
I am still trying to find a better solution at lib level, will keep u posted.

**Comment by bluebill1049** [comment]
Try this version: https://codesandbox.io/s/react-hook-form-usefieldarray-034no?file=/src/index.js

**Comment by tafelito** [comment]
ok I tried with that version and the flickering does seem to be happening but I did notice 2 things.

1. Not all the values are preserved when I move an item. I added a react-select component and when you move an item, the value of the select is lost

2. If you add 2 items, update the name and select values of the item 1. Then do the same with the item 2. Then go back to item 1 and select any value from the select. You get `Warning: Can't perform a React state update on an unmounted component.`

Here's the updated codesanbox https://codesandbox.io/s/react-hook-form-usefieldarray-6e0bl?file=/src/index.js

**Comment by bluebill1049** [comment]
> 1. Not all the values are preserved when I move an item. I added a react-select component and when you move an item, the value of the select is lost. The fields object does actually carry this values, but the watch does not

Let's focus on one problem at a time, can you explain more on the above?

**Comment by tafelito** [comment]
I don't know If I can reproduce it using the simpler codesanbox that's why I created the other one. But I will try to. 
With this https://codesandbox.io/s/react-hook-form-usefieldarray-6e0bl?file=/src/index.js, you can reproduce it by doing

1.  Append 2 items
2. Click on the 1 one. Enter some text and select a value from the dropdown
3. Click on the 2 item. Enter some text and select a value from the dropdown
4. Click on move
5. Now click on the 2 item (1 before moving). You should see that the drawdown has no value

**Comment by bluebill1049** [comment]
> I don't know If I can reproduce it using the simpler codesanbox that's why I created the other one. But I will try to.
> With this https://codesandbox.io/s/react-hook-form-usefieldarray-6e0bl?file=/src/index.js, you can reproduce it by doing
> 
> 1. Append 2 items
> 2. Click on the 1 one. Enter some text and select a value from the dropdown
> 3. Click on the 2 item. Enter some text and select a value from the dropdown
> 4. Click on move
> 5. Now click on the 2 item (1 before moving). You should see that the drawdown has no value
> 
> EDIT: I just updated it. Instead of using a select I used 2 inputs. The issue and the steps to reproduce it are the same

Nice, thanks i will take a look tonight.

**Comment by bluebill1049** [comment]
Took a quick look, I think this problem is due to your component is getting unmounted, so in my PR fix, I am reading what's the in the form and try to pass down to the `fields`, in your case, because the inputs share between different section, which leads to inputs are unmounted and get form values to return only the presenter one.

**Comment by tafelito** [comment]
>  I am reading what's the in the form
What do you mean by that? Aren't the fields registered in the InnerForm part of the form?

The reason why they are unmounted is so I can update the default value of the inputs in the InnerForm, that's why I use a different key. If that's what you meant by that. 
I tried a different approach, where I I pass the fields to the InnerForm and only register the inputs there, instead of having 2 places with the same input but it's still the same thing

**Comment by bluebill1049** [comment]
> What do you mean by that? Aren't the fields registered in the InnerForm part of the form?

Basically if an input gets removed we unregister the input inside the hook as well.

**Comment by bluebill1049** [comment]
> I tried a different approach, where I I pass the fields to the InnerForm and only register the inputs there, instead of having 2 places with the same input but it's still the same thing

Have you try with the innerForm is always part of the input item? so they never get unmount, see if that resolve the problem.

**Comment by tafelito** [comment]
> Have you try with the innerForm is always part of the input item? so they never get unmount, see if that resolve the problem.
I'be happy to try it but I'm not sure what you mean by this. if you don't mind giving me a bit more details I will give it a try

**Comment by bluebill1049** [comment]
hey @tafelito sorry for not been clear above, (due to just wake up). I mean have those two inputs (which you used to store value) next to your click button and use CSS display to toggle the visibility. This will result in those two inputs always mounted and belong to each its own Field Array.

**Comment by tafelito** [comment]
@bluebill1049 no worries, we are completely in the opposite TZ, I'm bout to 😴

so the InnerForm actually doesn't really get unmounted, only when there is no selected item. But when you click on every item what I'm actually doing is changing the keys of the inputs and the reason I do that is to be able to refresh the values, otherwise the input won't update it's value

**Comment by bluebill1049** [comment]
```
<Controller
        // as={<input />}
        key={selectedId}
        render={({ value, onChange, onBlur }) => {
          // console.log("InnerForm -> value", value);
          return (
            <input
              value={value?.name || ""}
              onChange={e =>
                onChange({ generatedId: selectedId, name: e.target.value })
              }
              onBlur={onBlur}
            />
          );
        }}
        // as={<input />}
        name={`test[${selectedIndex}].country`} // the moment name is change, it will unmount innput.
        control={control}
        defaultValue={country?.name && country} // make sure to set up defaultValue
/>
```

Take a look at my comment above, that's the bit I was concerned about. I think i will still go ahead with the PR that I did, it's an improvement either way.

Also this is what i meant:
```
<div
                  style={{ color: "white" }}
                  onClick={() => setSelectedId(item.generatedId)}
                >
                  {/* {value?.name || "Select Country (Click here to edit)"} */}
                  Select Country (Click here to edit)

                  // input here so it's always there and toggles the visibility.
                </div>
```

**Comment by tafelito** [comment]
> the moment name is change, it will unmount innput.

If I don't specify a name then the input is not registered. If I set the same name for all inputs, then how do you know which index of the field array it belongs?

> make sure to set up defaultValue

The default value could be undefined the first time if the input has no value. You mean setting it as an empty string instead of undefined?

> input here so it's always there and toggles the visibility.

This part I'm confused, because the InnerForm is always visible as long as there is a selected id. Not sure what to do there 

@bluebill1049 If you ever have time and you don't mind it would be great if you can change the example with your suggestions. If you don't have the time I understand. As a workaround, I'm using `setValue`, `getValue` and manually registering an custom name with `useEffect` to handle this my self. Even tho it's not ideal, it does work but it has it's trade offs. That's the reason why I believe using a field array would be a better solution

**Comment by bluebill1049** [comment]
> @bluebill1049 If you ever have time and you don't mind it would be great if you can change the example with your suggestions. If you don't have the time I understand. As a workaround, I'm using `setValue`, `getValue` and manually registering a custom name with `useEffect` to handle this my self. Even tho it's not ideal, it does work but it has it's trade offs. That's the reason why I believe using a field array would be a better solution

I will give it a try :)

**Comment by bluebill1049** [comment]
This is what i meant: https://codesandbox.io/s/quirky-rain-9rbsj?file=/src/App.js

**Comment by tafelito** [comment]
First of all, thanks for taking the time to do it!!

I see what you were saying now. Even tho that works, for my specific use case, I think is still not working. 

And by not working I mean, when you move an item, you still lose the value of the watch. So what I did is, I created a slightly modified version of yours, but I moved the button to a Button component, where I use the useWatch to watch for the name value of the current index. I want to show the name as the text of the button

Here's the modified version
https://codesandbox.io/s/modern-tdd-j7uli

**Comment by tafelito** [comment]
Another thing I'm worried about that approach is when you have multiple fields on the InnerForm, and multiple fields, it can get out of control very quickly and also you still have all the components mounted in the DOM. I can't really tell how performant this could be but it does raise some questions

**Comment by bluebill1049** [comment]
This kind works: https://codesandbox.io/s/shy-waterfall-76sy8?file=/src/App.js

**Comment by tafelito** [comment]
it does! and actually my example does also work when I use ```useWatch({ name: `test[${index}].name`, control });``` instead of `useWatch({ name: 'test', control });` and then access the value by index.
I thought I tried that before with `watch` but I don't remember it working. Interesting. I'm glad is working and that we made some progress 😁 

I still need to figure out if by hiding the elements with css is going to work or if it could potentially be a performance issue. What are your thoughts on that?

Anyway, thanks @bluebill1049 for the help, for the quick response as always and for the amazing library!

**Comment by bluebill1049** [comment]
> I still need to figure out if by hiding the elements with css is going to work or if it could potentially be a performance issue. What are your thoughts on that?

I think CSS is the cheapest :) by the way, still going to merge that PR anyhow, it's an improvement for the lib.

**Comment by tafelito** [comment]
great! thanks!
