### ISSUE TITLE
TypeError: e.preventDefault is not a function

### ISSUE THREAD

**Issue by yahveh** [react-hook-form/react-hook-form#2037]
when i use `react-native-ui-lib` code:
```
<Button
  marginT-20
  label="Confirm"
  onPress={handleSubmit(onSubmit)}
  disabled={isSubmitting}>
  {isSubmitting ? <ActivityIndicator color="#fdfdfd" /> : null}
</Button>
```

error: 

```
TypeError: e.preventDefault is not a function. (In 'e.preventDefault()', 'e.preventDefault' is undefined)
```

i changed [useForm.ts#L903](https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L903)

```
    const handleSubmit = React.useCallback((callback) => async (e) => {
        if (e && e.preventDefault) { // add?
            e.preventDefault();
            e.persist();
        }
```

**Comment by bluebill1049** [comment]
`() => handleSubmit(onSubmit)()` will do

**Comment by yahveh** [comment]
@bluebill1049 thanks, i'll try this

**Comment by bluebill1049** [comment]
This should fix it. :)

**Comment by pke** [comment]
Then the docs are wrong. https://react-hook-form.com/get-started#ReactNative
Can we update those too?
The incorrect syntax is the one that looks better and should work though. The suggested fix adds to many indirections for my taste. Can't the implementation of `handleSubmit`not changed so it can be used as described in the docs?

**Comment by bluebill1049** [comment]
> Then the docs are wrong. https://react-hook-form.com/get-started#ReactNative
> Can we update those too?
> The incorrect syntax is the one that looks better and should work though. The suggested fix adds to many indirections for my taste. Can't the implementation of `handleSubmit`not changed so it can be used as described in the docs?

That's what i did in the expo snack, it didn't throw an error and keep the doc as it is: https://snack.expo.io/@bluebill1049/react-hook-form-v6

**Comment by pke** [comment]
Interesting. In non-expo RN app it throws this error the OP mentioned. Your fix solves this error but the signature is ugly. It shouldn't make a difference expo or not. Something we are missing here.

**Comment by bluebill1049** [comment]
> Interesting. In non-expo RN app it throws this error the OP mentioned. Your fix solves this error but the signature is ugly. It shouldn't make a difference expo or not. Something we are missing here.

Yea, I agree. Happy to do that extra check, just so we don't see this ugly syntax.

**Comment by bluebill1049** [comment]
@pke can you share a screenshot of the actual error screen before i merge this PR for the fix.

**Comment by bluebill1049** [comment]
and which version are you using with RN as well?

**Comment by pke** [comment]
```bash
npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
"react-hook-form": "6.0.1",
```
![Simulator Screen Shot - iPhone 11 - 2020-07-07 at 08 49 05](https://user-images.githubusercontent.com/164625/86730397-c5ee9f80-c02e-11ea-8687-3a09a9ca2d6d.png)

**Comment by pke** [comment]
Thanks!

You don't have an release-on-master merge GH action, do you? ;)

**Comment by bluebill1049** [comment]
> Thanks!
> 
> You don't have an release-on-master merge GH action, do you? ;)

I don't :( but we looking for a solution right now.

**Comment by pke** [comment]
there is GH action for NPM releases, its pretty easy to plugin.

I tried to use the current master for my project, however the way your package.json is setup it only works when distributed to npm. Bacause of the package files main entry pointing to a file that does not exist when the package was not built (index.js). So its hard to `yarn add react-hook-form/react-hook-form` at the moment.

**Comment by mjwvb** [comment]
I'm trying to use handleSubmit with onClick on a Button component, provided by "Framework7":
<Button onClick={handleSubmit(onSubmit)}>Submit</Button>

But then I get the following error:
Unhandled Rejection (TypeError): e.persist is not a function

This happens because the custom Button has the preventDefault function, but not the persist function.
It would be useful to also wrap the e.persist() call in an if statement, so handleSubmit can be used in these circumstances.

For now I have to use the workaround as mentioned by bluebill1049

**Comment by bluebill1049** [comment]
> I'm trying to use handleSubmit with onClick on a Button component, provided by "Framework7":
> `<Button onClick={handleSubmit(onSubmit)}>Submit</Button>`
> 
> But then I get the following error:
> Unhandled Rejection (TypeError): e.persist is not a function
> 
> This happens because the custom Button has the preventDefault function, but not the persist function.
> It would be useful to also wrap the e.persist() call in an if statement, so handleSubmit can be used in these circumstances.
> 
> For now I have to use the workaround as mentioned by bluebill1049

`<Button onClick={() => handleSubmit(onSubmit)()}>Submit</Button>`

**Comment by jrosto** [comment]
This happens when parentheses are omitted in  useForm  :        const{register,errors,handleSubmit} = useForm();  //if these last parentheses are omitted
