### ISSUE TITLE
Validation update problem

### ISSUE THREAD

**Issue by Sin-** [react-hook-form/react-hook-form#2048]
**Describe the bug**
The validation seems to have a problem updating itself.
If you set a field as required for example, and click submit first, you get the normal error 'Field is missing'.
Then if you fill the field up, and resubmit, you will still have an error showing up telling you the field is missing.

**To Reproduce**
I am currently using the lib in React Native, but this behavior is actually reproducible in the useForm codesandbox template you provide: [useForm](https://codesandbox.io/s/react-hook-form-useform-template-lsm61) Template
1. Try to submit directly without entering a lastname, the validation error shows up
2. Then, enter a lastname with more than 10 characters, the validation error appearing is "This field is required"

Same way, if you try to enter directly a Lastname with more than 10 characters, the validation error is "This field is required"

**Expected behavior**
The validation to update itself correctly 

**Screenshots**
I can provide a gif of the problem on React Native.
The problem here is worse because if I submit once without entering the firstname for example, I get the validation, but all subsequent submits are blocked with the same error, even if I provided a firstname.
![react-hook-form-gif](https://user-images.githubusercontent.com/11181821/86468764-63e52000-bd38-11ea-9232-7f5e8ba10fe2.gif)

**Smartphone (please complete the following information):**
 - Device: iPhone XR, iPhone simulator and Huawei P20 lite
 - OS: iOS 13.5 & Android 8.0

**Additional context**
"react": "16.11.0",
"react-native": "0.62.2",
"react-hook-form": "^6.0.0",

**Comment by bluebill1049** [comment]
you should console the `errors` object, it provides you with the types and you should assign error message accordingly.

**Comment by Sin-** [comment]
On first submit:
<img width="565" alt="Capture d’écran 2020-07-03 à 14 40 35" src="https://user-images.githubusercontent.com/11181821/86470201-39489680-bd3b-11ea-804e-e4295acb2f09.png">

This is normal.
Then when I enter the firstname, the errors become: 
<img width="556" alt="Capture d’écran 2020-07-03 à 14 41 48" src="https://user-images.githubusercontent.com/11181821/86470262-5da47300-bd3b-11ea-95e5-dff50945a851.png">

This is also good.
But when I submit the form with the firstname entered, the console.log gives me this:
<img width="570" alt="Capture d’écran 2020-07-03 à 14 42 52" src="https://user-images.githubusercontent.com/11181821/86470330-8462a980-bd3b-11ea-8f52-1d60347700d4.png">

This is not good I should not have a required error on the firstname field.
I use the firstname as example but this is reproducible for all fields. 
If I then fill every field up correctly and click on submit, here is the log: 
<img width="568" alt="Capture d’écran 2020-07-03 à 14 44 41" src="https://user-images.githubusercontent.com/11181821/86470490-d7d4f780-bd3b-11ea-8539-7b686e00cad1.png">

Which means even after correcting the input, I cannot submit.
The submit only works if I enter all fields correctly on the first try.
If one error appeared somewhere it's over, I cannot submit again even after correcting the field.

**Comment by bluebill1049** [comment]
are you using `Controller` or register at `useEffect`? This doesn't look right to me.

**Comment by Sin-** [comment]
I'm using useEffect to register and setValue.
I can provide some code to help:

Input.tsx:
```typescript
import * as React from 'react';
import {View, TextInput, TextInputProps} from 'react-native';

import {ThemeText as Text} from './helpers';
import styled from 'styled-components';
import colors from './colors';

interface InputProps extends TextInputProps {
  label?: string;
  error?: string;
  name?: string;
}

export default React.forwardRef<any, InputProps>(
  (props, ref): React.ReactElement => {
    const {label, error, name, ...inputProps} = props;

    return (
      <View>
        {label && <Text>{label}</Text>}
        <TextInput
          autoCapitalize="none"
          name={name}
          ref={ref}
          {...inputProps}
        />
        {error?.message && <ErrorText>{error.message}</ErrorText>}
      </View>
    );
  },
);

const ErrorText = styled(Text)`
  color: ${colors.red};
`;

```

Form.tsx: 

```typescript
import React, {useRef, useEffect} from 'react';
import {TextInput} from 'react-native';
interface ValidationMap {
  [key: string]: any;
}
interface ErrorMap {
  [key: string]: object | undefined;
}
interface Props {
  children: JSX.Element | JSX.Element[];
  register: ({name}: {name: string}, validation: any) => void;
  errors: ErrorMap;
  validation: ValidationMap;
  setValue: (name: string, value: string, validate?: boolean) => void;
  clearErrors: (name: string) => void;
}
export default ({
  register,
  errors,
  setValue,
  validation,
  children,
  clearErrors,
}: Props) => {
  const Inputs = useRef<Array<TextInput>>([]);
  useEffect(() => {
    (Array.isArray(children) ? [...children] : [children]).forEach((child) => {
      if (child.props.name)
        register({name: child.props.name}, validation[child.props.name]);
    });
  }, [register, children, validation]);
  return (
    <>
      {(Array.isArray(children) ? [...children] : [children]).map(
        (child, i) => {
          return child.props.name
            ? React.createElement(child.type, {
                ...{
                  ...child.props,
                  ref: (e: TextInput) => {
                    Inputs.current[i] = e;
                  },
                  onChangeText: (v: string) => {
                    setValue(child.props.name, v, true);
                    // clearErrors(child.props.name);
                  },
                  onSubmitEditing: () => {
                    Inputs.current[i + 1]
                      ? Inputs.current[i + 1].focus()
                      : Inputs.current[i].blur();
                  },
                  blurOnSubmit: false,
                  key: child.props.name,
                  error: errors[child.props.name],
                },
              })
            : child;
        },
      )}
    </>
  );
};

```

usage of Form and Input components:

```typescript
const {
    register,
    handleSubmit,
    setValue,
    errors,
    getValues,
    clearErrors,
  } = useForm();

const validation = {
    firstname: {required: {value: true, message: 'Firstname is required'}},
    lastname: {required: {value: true, message: 'Lastname is required'}},
    email: {
      required: {value: true, message: 'Email is required'},
      pattern: {
        value: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
        message: 'Invalid Email Format',
      },
    },
    password: {
      required: {value: true, message: 'Password is required'},
      minLength: {value: 6, message: 'Password must be at least 6 characters'},
    },
    confirmPassword: {
      validate: (value: string) =>
        value === getValues('password') || 'Passwords do not match',
    },
  };

const onSubmit = (data) => {
    console.log('Form data', data);
  };

return (
  <Form {...{register, setValue, validation, errors, clearErrors}}>
            <Input name="firstname" label={translate('Firstname')} />
            <Input name="lastname" label={translate('Lastname')} />
            <Input name="email" label={translate('Email')} />
            <Input
              secureTextEntry
              name="password"
              label={translate('Password')}
            />
            <Input
              secureTextEntry
              name="confirmPassword"
              label={translate('ConfirmPassword')}
            />
          </Form>
)
```

**Comment by bluebill1049** [comment]
make sure you test that `regsiter` is not keep re-regsiter inputs, because that's how it looks like right now.

**Comment by maxfrigge** [comment]
I am having a similar issue that seems related. Maybe it helps to better identify the problem.

In a list with `useFieldArray` we use `ref={register()}` as per docs. When you fill out the first set of fields, then add a new entry to the array and immediately remove it. The first set of fields fails validation as described above. When you submit again (without changing anything) the validation works as expected.

**Comment by Sin-** [comment]
Good call! 
eslint was forcing me to use `[register, children, validation]`as a dependency of my useEffect, so I only left register and now it seems that the inputs are not re-registered each time.
This eslint(react-hooks/exhaustive-deps) rule is quite annoying.
Thanks for the help!

**Comment by maxfrigge** [comment]
@bluebill1049  Das that mean would have to memoize the each `register()` call to prevent from reregistering on each render?

**Comment by Sin-** [comment]
@maxfrigge Just make sure your registers are called only once, for me it was restricting the dependency of my useEffect to only register and removing children

**Comment by maxfrigge** [comment]
@Sin-  I don't see a neat way to achieve this to be honest. It's not used in a hook, but as a ref property in a map function as part of a field array.

**Comment by Sin-** [comment]
I think you can indeed memoize your form component, if no props are changed while filling the form, it should work

**Comment by maxfrigge** [comment]
Will try when I find the time for. It would require a bit of refactoring.

**Comment by NitinMagdum** [comment]
https://www.carlrippon.com/react-hook-form-cross-field-validation/ 

https://codesandbox.io/s/react-hook-form-cross-field-validation-cqczn?file=/src/App.tsx

enter 5 and 4 submit it will show error message The highest score can't be less than the lowest score. correct behaviour but now change min from 5 to 3 still it shows error ----- how to update the error state
i think the erroes from useForm not getting updated or the validation is not happening on each value change 

could you suggest.
