### ISSUE TITLE
V6: Some types have been removed from export

### ISSUE THREAD

**Issue by JClackett** [react-hook-form/react-hook-form#2049]
**Describe the bug**
ManualFieldError has been removed from the export so I can't use in my app

**To Reproduce**
Try import ManualFieldError from "react-hook-form"

**Expected behavior**
import { ManualFieldError } from "react-hook-form" not to fail

**Screenshots**
<img width="627" alt="Screenshot 2020-07-03 at 14 29 37" src="https://user-images.githubusercontent.com/12549124/86469441-ad823a80-bd39-11ea-969d-83dd4a48ffb6.png">

**Comment by bluebill1049** [comment]
We stopped export all the types, for your reference here are the types that we exporting: https://react-hook-form.com/ts/

**Comment by jaypalexa** [comment]
@JClackett I am having to adjust to no-longer-exported types, too.  Not sure it is the correct approach, but something like this made similar errors go away for me:

```
import { ManualFieldError } from 'react-hook-form/dist/types/form';
```

**Comment by bluebill1049** [comment]
FieldError(ManualFieldError) will be exported in the next patch.
