### ISSUE TITLE
Get the values with the right data type

### ISSUE THREAD

**Issue by JeromeDeLeon** [react-hook-form/react-hook-form#205]
**Is your feature request related to a problem? Please describe.**
I find it troublesome to convert form values to the right data type.

**Describe the solution you'd like**
It would be better if it will be converted based on the type of the input or maybe the validationSchema (Yup) because I tried using `transform()` in Yup but seems not working. If we set the data type to date then the return value must be a Date object.

**Comment by bluebill1049** [comment]
can you try the latest version on this as well?

**Comment by JeromeDeLeon** [comment]
Here is the [codesandbox](https://codesandbox.io/s/react-hook-form-set-inputselect-value-4b41g?fontsize=14). I updated it on the latest one but still seems not to work. I specified the type of input to be a number but when I submitted the form, the age returned a string.

**Comment by bluebill1049** [comment]
@JeromeDeLeon I see, I think this one requires a bit of discussion. because native HTML input element actually always return `string` probably except `checkbox`. It's almost a misconception that input will actually return `number`.

**Comment by JeromeDeLeon** [comment]
yeah, but only do the parsing when using `getValues()` or `handleSubmit()` or else there would be a lot of changes if you parse it all the time.

**Comment by JeromeDeLeon** [comment]
since you are using ref, [HTMLInputElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement) already provided a solution using `valueAsNumber` and `valueAsDate`.

**Comment by bluebill1049** [comment]
oh cool! i didn't know `valueAsNumber` will take a look into it 👍

**Comment by JeromeDeLeon** [comment]
Hope it would be implemented. 😃 Thanks!

**Comment by bluebill1049** [comment]
I guess I can refer to the input` type` to determine `value` return.

eg

```
<input type="number" /> valueAsNumber
<input type="Date" /> valueAsDate
```

**Comment by JeromeDeLeon** [comment]
Yes, looks good to me.

**Comment by JeromeDeLeon** [comment]
For setting a value of `date` type, we can now rely on using `getById("bday").valueAsDate = new Date()` instead of using `YYYY-MM-DD` default format when using `getById("bday").value`.

So in the `else` statement of your `setFieldValue`, we can add another checking named `isDateInput()`

**Comment by bluebill1049** [comment]
Sounds good to me, I will sort out one at the time. Probably get u to test as well 👌🏻

**Comment by JeromeDeLeon** [comment]
Thanks. btw, I tried to empty string to `valueAsNumber` but turns out that it will be converted to number which resulted to 0 as empty value, so for setting value of number, `value` is enough 😄 .

**Comment by bluebill1049** [comment]
I found `valueAsNumber` is tricky because empty input result as `isNaN`

**Comment by JeromeDeLeon** [comment]
yes that's expected since we're returning a number so I think under the hood, the browser tries to parseFloat the string and parsing empty string will result to `NaN`.

```
const inp = parseFloat(inp);
return Number.isNaN(inp) ? "" : inp;
```

something like that or maybe change empty string to 0?

**Comment by JeromeDeLeon** [comment]
there's one more solution to this I think if you don't mind.

let `validationSchema` handle it so it would allow us to use `transform` method.

**Comment by bluebill1049** [comment]
> something like that or maybe change empty string to 0?

We can't set `''` to `0`, if you store in the global state and refresh the page and the input will be `<input value="0" />` instead of `<input value="" />`

**Comment by bluebill1049** [comment]
> let validationSchema handle it so it would allow us to use transform method.

That sounds good for schemaValidation. 

I will still be working on the `valueAsNumber` and `valueAsDate` for non schema validation, hope i can find a good solution.

**Comment by bluebill1049** [comment]
@JeromeDeLeon you want to provide an example for `validationSchema` with `transform` i would like to have that in the documentation website. maybe will be helpful for others :)

**Comment by JeromeDeLeon** [comment]
that would not be possible in the current state of the library because your returning an empty object `{ }` instead of a result from the validation using Yup

**Comment by bluebill1049** [comment]
Oh i see.

**Comment by JeromeDeLeon** [comment]
[Codesandbox](https://codesandbox.io/embed/react-hook-form-set-inputselect-value-4b41g)

**Comment by bluebill1049** [comment]
think I can work towards that. @JeromeDeLeon 

will add that to my todo.

**Comment by bluebill1049** [comment]
you want to raise another issue for this, so we can track this later.

**Comment by JeromeDeLeon** [comment]
Sorry, I'm don't have any experience when it comes to PR stuff, so I, instead just review your code.

**Comment by bluebill1049** [comment]
all good @JeromeDeLeon i will come back to that, i will sort out `valueAs` first

**Comment by bluebill1049** [comment]
This is what I am doing with number: 

```
if (type === 'number' && !isNaN(valueAsNumber)) {
  return valueAsNumber;
}

return value;
```

so it could be either `number | string`. if you place 0 in the input it will return `NaN`. 

To be honest I almost prefer it's always `string`. @stramel @barrymay what you guys thoughts? 

I had a look `valueAsDate` as well.

**Comment by stramel** [comment]
Hmmm that's tricky, what if we just give the ability to pass the parser? Default it to `value`, allowing opt-in to `valueAsNumber` or `valueAsDate`? 

I say it's tricky because of `type="time"` could use all 3.

**Comment by JeromeDeLeon** [comment]
> Hmmm that's tricky, what if we just give the ability to pass the parser? Default it to `value`, allowing opt-in to `valueAsNumber` or `valueAsDate`? Maybe something like `register({ parse: 'valueAsNumber' })`? Unless I'm misunderstanding what you are saying?
> 
> I say it's tricky because of `type="time"` could use all 3.

I didn't thought about the other time so I just said that only parse Date and Number type 😆 and the rest is just String

**Comment by bluebill1049** [comment]
hey @JeromeDeLeon can you please test out 3.21.16-beta.1  with yup transform?

**Comment by bluebill1049** [comment]
# NPM
npm install https://github.pika.dev/react-hook-form/react-hook-form/pr/209

# Yarn
yarn add https://github.pika.dev/react-hook-form/react-hook-form/pr/209

**Comment by JeromeDeLeon** [comment]
It works just fine. You just forgot to remove the `console.log("ahahah")` and `console.log('fieldErrors', fieldErrors);` that laughs at you every time you submit the form 😆

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/releases/tag/3.21.16 published let's close this issue for now. until we figure out a good solution for standard validation.

I still not sold with `register({ as })`, and don't have a good solution in my head just yet.

**Comment by JeromeDeLeon** [comment]
Yes, using `validationSchema` will do. Just suggested it because the old version didn't maximize the use of Yup so yeah for now, we can close this. Thanks 😁

**Comment by bluebill1049** [comment]
thanks @JeromeDeLeon I will keep in my todo list to improve non-yup usage.
