### ISSUE TITLE
isDirty and dirtyFields from formState is not synced

### ISSUE THREAD

**Issue by kayuapi** [react-hook-form/react-hook-form#2050]
**Describe the bug**
When an input element is removed from DOM, the dirtyFields is empty, but isDirty is still true. 

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-hxqur?file=/src/index.js

**Expected behavior**
Expect isDirty to be false when dirtyFields is empty.

**Comment by bluebill1049** [comment]
i was thinking this issue last night, i think the problem is not isDiryt, rather drityFields shouldn't be revmoed.

**Comment by bluebill1049** [comment]
question: @kotarella1110 @JeromeDeLeon @keiya01 @pmaier983 if an input gets removed should `dirtyFields` gets reset or gets removed? Think twice, I think they shouldn't be removed.

**Comment by bluebill1049** [comment]
maybe `shouldUnregister` should be the differentiated point, `shouldUnregister` to false then shouldn't remove and update `dirtyFields`.

**Comment by bluebill1049** [comment]
I think that makes sense, patching...

**Comment by xiaoyu-tamu** [comment]
@bluebill1049 

Just quick question related to isDirty. Do we need to read formState.isDirty in order to get up to date contorl.isDirtyRef.current value?

https://codesandbox.io/s/react-hook-form-useform-template-2yu0e?file=/src/index.js
```
  const { control } = useForm();

  // always false
  console.log(control.formState.isDirty);
```

```
  const { control,formState:{isDirty} } = useForm();

  // expected
  console.log(control.formState.isDirty);
```
