### ISSUE TITLE
Registering new field when form is invalid can make the form valid

### ISSUE THREAD

**Issue by bryannovoed** [react-hook-form/react-hook-form#2052]
**Describe the bug**
when the form is invalid and a new field is registered, the validation resolver is passed initial state, which may result in the form become incorrectly valid
i might be missing something since this library is very well thought out and i see the code that intentionally passes initial data when the form is invalid so please excuse me if i made a mistake

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-validationresolver-g7ett?file=/src/App.js
2. Click "Include username" checkbox to cause form to be in invalid state
3. Click "Toggle username field" to show username
4. See error - form is is valid state/validation is passed initial form data, causing the form to be incorrectly valid

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-validationresolver-g7ett?file=/src/App.js

**Expected behavior**
when registering new inputs when form is invalid, the form will be passed the current state(merged with initial state?)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version 83

**Comment by bluebill1049** [comment]
This is because your resolver didn't return an error when the new input is getting registered.

![Screen Shot 2020-07-04 at 6 43 29 pm](https://user-images.githubusercontent.com/10513364/86508802-42626200-be26-11ea-90de-fcd73436e1bb.png)

**Comment by bryannovoed** [comment]
@bluebill1049 
when registering a new input, the resolver is passed the defaultValues `{ includeUserName: false, initialStateData: true }` instead of the current values `{ includeUserName: true }`. so in this case, the resolver will not return any errors since the defaultValues are valid

**Comment by bluebill1049** [comment]
> @bluebill1049
> when registering a new input, the resolver is passed the defaultValues `{ includeUserName: false, initialStateData: true }` instead of the current values `{ includeUserName: true }`. so in this case, the resolver will not return any errors since the defaultValues are valid

The resolver first argument is basically `getValues` of the entire form, what do you mean "instead of the current values { includeUserName: true }"?

**Comment by bryannovoed** [comment]
hrm...sorry if I'm missing something here
> The resolver first argument is basically getValues of the entire form, what do you mean "instead of the current values { includeUserName: true }"?
yeah that's my expectations, but i'm seeing the defaultValues passed to the resolver instead of getValues equivalent when we add a new input

if you follow the steps above, after adding the input, you'll see something like
![Screen Shot 2020-07-06 at 5 42 28 PM](https://user-images.githubusercontent.com/8356554/86677371-6356be80-bfb0-11ea-83c7-b1d5ee0fbf0b.png)
where you can see that the validation resolver data is different than the getValues() data

**Comment by bluebill1049** [comment]
hmmm interesting... will take a deeper look on this issue.

**Comment by bluebill1049** [comment]
first problem is `getValues()`, it shouldn't be used like in your `codesandbox`, because getValues works after render, HookForm's form data lives in the input itself, which means after render.

**Comment by bluebill1049** [comment]
This will be patched under V6: https://codesandbox.io/s/react-hook-form-validationresolver-r2dzq?file=/src/src/useForm.ts
