### ISSUE TITLE
array field is not working properly

### ISSUE THREAD

**Issue by JeromeDeLeon** [react-hook-form/react-hook-form#206]
**Describe the bug**
I played around the example of array field provided in this repo.
* I tried to set a defaultValues but it didn't seem to work properly.
* `getValues({ nest: true })` did not also work. I don't know if `{ "people[0].firstName" :"" }` is the corrent outcome instead of `{ people: [ { firstName: "" } ] }`

[Here's the codesandbox](https://codesandbox.io/embed/react-hook-form-set-inputselect-value-4b41g)

**Expected behavior**
* defaultValues must work as expected
* better if the format of values is formatted properly rather than plain text

**Additional Context**
I'm just new to this library, so I don't know if there are already solutions to the problems/suggestions stated above.

**Comment by bluebill1049** [comment]
can you try the latest version? i think the example is using an old beta one.

**Comment by JeromeDeLeon** [comment]
Thanks 😄

**Comment by 5123095** [comment]
why array field defaultValues and submited value are not reciprocal?
[Here's the codesandbox](https://codesandbox.io/s/react-hook-form-defaultvalues-i011v)

**Comment by bluebill1049** [comment]
what do you mean @5123095?

`isDeveloper: ["b"]` is this one you mean?

**Comment by 5123095** [comment]
yes, \<input value="b" />  is not checked by default

**Comment by bluebill1049** [comment]
@5123095 `isDeveloper: [false, "b"]` you checked the first one

**Comment by 5123095** [comment]
default values from api not contain all values of options, i don't even know options length，what should i do in this case

**Comment by bluebill1049** [comment]
Use input name, developer[1]

**Comment by 5123095** [comment]
OK， Thank you very much

**Comment by bluebill1049** [comment]
Pleasure :)
