### ISSUE TITLE
formState Dirty working only when form submitted second time

### ISSUE THREAD

**Issue by ahmad-medhat** [react-hook-form/react-hook-form#2060]
**Describe the bug**
When the input is mounted and the user starts typing, the formState.dirty is false. If you start typing again, the formState.dirty becomes true!

**To Reproduce**
1. Go to to the following sandbox:
https://codesandbox.io/s/fervent-mayer-tutv8?file=/src/App.js
2. Start typing in the input and then click on 'Submit', you will notice in the console that the formState.dirty is false (it should be true according to my understanding)
3. Start typing again and click submit, the formState.dirty become true.

**Codesandbox link (Required)**
https://codesandbox.io/s/fervent-mayer-tutv8?file=/src/App.js

**Expected behavior**
The dirty state should be true from the first time if input value has changed. 

**Desktop:**
 - OS: macOS 10.15.5
 - Browser: Firefox
 - Version: 78.0.1 (64-bit)

**Additional context**
- I noticed this behavoir in the components that use Controller but I founded also in the uncontrolled components.
- My project is using v5.7.2 but the issue exists also in v6.0.1 as I tested it on codesandbox

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/xenodochial-http-0xsp0?file=/src/App.js
