### ISSUE TITLE
In react-native development, when the form is submitted, the first click does not respond, the second time it takes effect

### ISSUE THREAD

**Issue by tlqylzn** [react-hook-form/react-hook-form#2069]
**Describe the bug**
In react-native development, when the form is submitted, the first click does not respond, the second time it takes effect

**To Reproduce**
1. My test found that only when the outer layer of the form includes the ScrollView component, the first click to submit does not respond

2. I tried both the Controller and useEffect register methods, and both have this problem. If the Form package is the View component, this problem does not exist.

3. When the input box is not edited, whether it is View or ScrollView click Submit is normal console

**Expected behavior**
I hope that like the View component, it will always respond when clicked.

**Screenshots**
![image](https://user-images.githubusercontent.com/4860021/86525790-32965c80-bebe-11ea-916c-3ca3c18496c5.png)
![image](https://user-images.githubusercontent.com/4860021/86525736-ad12ac80-bebd-11ea-8967-0f27161d5259.png)

**Smartphone (please complete the following information):**
 - Device: iPhone11 simulator and iPhoneXS real machine
 - OS: iOS 13.5

**Additional context**
"react": "16.13.1",
"react-hook-form": "^6.0.1",
"react-native": "0.63.0-rc.1",

**Comment by bluebill1049** [comment]
can you reproduce this in a expo snack?

**Comment by tlqylzn** [comment]
@bluebill1049 
take a look this example: [https://snack.expo.io/@timtao/hookformtest](https://snack.expo.io/@timtao/hookformtest)

When the nickname is entered in the form, it will be printed after clicking the button twice，This problem will also be reproduced on the expo snack ios

**Comment by bluebill1049** [comment]
<img width="1590" alt="Screen Shot 2020-07-05 at 7 02 40 pm" src="https://user-images.githubusercontent.com/10513364/86529200-1ad8cb80-bef2-11ea-8138-39a82346bcf9.png">

make you place a console.log inside your onPress, make sure the `handleSubmit` function is invoked as well.

**Comment by tlqylzn** [comment]
It's strange, I just tried it. When I clicked the first time, "submit." was not printed. It was printed together with the second click. Is it the first click printed on your side?

**Comment by tlqylzn** [comment]
![image](https://user-images.githubusercontent.com/4860021/86529615-992e7100-bee4-11ea-88b9-dbd2a1bf3628.png)

My printing order is different from yours, the "submit." printed first, then the nickname printed later, yours is opposite to mine

I guess whether there is a relationship between ScrollView and Controller, which causes the first click event to fail, and the View component does not have this problem.

**Comment by bluebill1049** [comment]
can you see a console.log on your `onPress`?

**Comment by tlqylzn** [comment]
Does not console.log the first time onPress

**Comment by bluebill1049** [comment]
so the problem is the button is not been pressed for some reason.

**Comment by tlqylzn** [comment]
Yes, this problem is limited to the ScrollView component, the View component does not have this problem, it is very strange

**Comment by bluebill1049** [comment]
try to remove all hook from reference and test with only native elements see if this issue goes away.

**Comment by tlqylzn** [comment]
I know the reason. This problem also occurs when the hook-form is deleted. Check the react-native documentation. The ScrollView component needs to set the [keyboardShouldPersistTaps='always'](https://reactnative.dev/docs/scrollview#keyboardshouldpersisttaps) property. This problem is solved. Thank you again for your enthusiastic answer.
