### ISSUE TITLE
How to validate array of objects with Yup

### ISSUE THREAD

**Issue by JeromeDeLeon** [react-hook-form/react-hook-form#207]
**Describe the bug**
I tried creating a schema then injected it in `validationSchema` but when I submitted the form, the error shows that the array is required and that's because I inserted as `Yup.array().of().required()` so I removed it but then the form submitted successfully even though I set the `firstName` field as required and set a empty value.
[Codesandbox](https://codesandbox.io/embed/react-hook-form-set-inputselect-value-4b41g)

**Expected behavior**
It should work as expected and if no value for array `[]` then the validation for array must trigger like `required()`.

**Comment by JeromeDeLeon** [comment]
I replicate the code for validating schema and it was showing the expected output but when I injected it in the library and submitted the form, it shows the outer validation.

**Comment by bluebill1049** [comment]
thanks should be a simple patch.

**Comment by bluebill1049** [comment]
can you test out this beta version? `3.21.13-beta.1`

**Comment by JeromeDeLeon** [comment]
Thanks 😃 It's working now.

**Comment by bluebill1049** [comment]
thanks for report this issue, close ticket when ready :)
