### ISSUE TITLE
Types lost in version 6

### ISSUE THREAD

**Issue by eMarek** [react-hook-form/react-hook-form#2073]
**Describe the bug**
Not sure why, but there is bunch of TS types missing after I upgraded to version 6.

**To Reproduce**
This import line `import { FieldError } from 'react-hook-form'` produces:
> Module '"../../../node_modules/react-hook-form/dist"' has no exported member 'FieldError'.  TS2305

**Codesandbox link (Required)**
https://codesandbox.io/s/nervous-joliot-y1qnj?file=/src/App.tsx

**Expected behavior**
I would expect that everything from `node_modules/react-hook-form/dist/types/form.d.ts` would be ready to use. Turns out only certain types are exported: https://github.com/react-hook-form/react-hook-form/blob/master/src/types/index.ts

**Screenshots**
<img width="873" alt="Screenshot 2020-07-05 at 14 41 33" src="https://user-images.githubusercontent.com/311634/86532942-e18e6480-becd-11ea-9634-89d59a72d1e0.png">

**Desktop (please complete the following information):**
 - react-hook-form 6.0.1
 - TypeScript 3.9.4
 - Node v12.16.3
 - npm 6.14.4
- yarn 1.22.4
- MacOs 10.15.5

**Comment by xiaoyu-tamu** [comment]
Some of them renamed, some of them became private (you can still import from /dist/type)

**Comment by xiaoyu-tamu** [comment]
#2049

**Comment by eMarek** [comment]
All I see in that ticket is `We stopped export all the types` without any explanation. I would understand if certain types would not exist. But they are there, just not exported. Why?

**Comment by bluebill1049** [comment]
First of all, We are not complicating things here instead It's a decision made to treat type carefully to avoid breaking change to your codebase. We are also open to including more exposed types when necessary and documented on the website: `https://react-hook-form.com/ts`, happy to discuss the need to include this `FieldError` as well by supply your usage and reason.
FYI @kotarella1110

**Comment by eMarek** [comment]
There is usage example (or let's say it just a draft) here https://codesandbox.io/s/nervous-joliot-y1qnj?file=/src/App.tsx. Function `doSomethingWithErrors` accepts errors and processes them on a certain way. In order to validate incoming params with TypeScript I need `errors`' type which `useForm()` returns. A bit of reverse engineering brought me to the `DeepMap<Record<string, any>, FieldError>`. Not having this type exported forces me to look for a unwanted workarounds. I think that `DeepMap`, `FieldError` and some others types should be exported.

**Comment by pixelass** [comment]
@bluebill1049 If the types are not exported the components can't be used. This causes errors all over. For us this means we can't use `ErrorMessage, ValidationOptions`.. at all. 

Can you please explain why you think they are not needed and how to use them without the types?

**Comment by bluebill1049** [comment]
> @bluebill1049 If the types are not exported the components can't be used. This causes errors all over. For us this means we can't use `ErrorMessage, ValidationOptions`.. at all.
> 
> Can you please explain why you think they are not needed and how to use them without the types?

Can you explain what do you mean by can't use at all?

**Comment by jaypalexa** [comment]
FWIW, I have been bitten by this, too.  I have been using (and suggesting to others, probably incorrectly) something like the following `import` to bring in the form types no longer exposed via `index.d.ts`:

```
import { FieldError } from 'react-hook-form/dist/types/form';
```

I understand the desire to limit the exposure of things to minimize potential breaking changes, but I must say (from a consumer standpoint) that having all types exposed via `react-hook-form` feels more intuitive (and standard) than having to hunt around for and drill into `/dist/types` and `dist/types/form`.  Moreover, these types _are_ already exposed, so changes to them will still be breaking changes, regardless of where they live.

(@pixelass Also note that `ValidationOptions` appears to have been changed to `ValidationRules` (and is exposed via `index.d.ts`:

```
import { ValidationRules } from 'react-hook-form/dist/types';
```
)

**Comment by bluebill1049** [comment]
> FWIW, I have been bitten by this, too. I have been using (and suggesting to others, probably incorrectly) something like the following `import` to bring in the form types no longer exposed via `index.d.ts`:
> 
> ```
> import { FieldError } from 'react-hook-form/dist/types/form';
> ```
> 
> I understand the desire to limit the exposure of things to minimize potential breaking changes, but I must say (from a consumer standpoint) that having all types exposed via `react-hook-form` feels more intuitive (and standard) than having to hunt around for and drill into `/dist/types` and `dist/types/form`. Moreover, these types _are_ already exposed, so changes to them will still be breaking changes, regardless of where they live.
> 
> (@pixelass Also note that `ValidationOptions` appears to have been changed to `ValidationRules` (and is exposed via `index.d.ts`:
> 
> ```
> import { ValidationRules } from 'react-hook-form/dist/types';
> ```
> 
> )

Thanks @JayantDaruvuri for understanding, I agree with you 100% on this.  let's be patient no this, It's a matter of time that we conclude what are the types are necessary to expose to our consumers and document them down and not include breaking change in the future. It's **SO** easy for us to expose all, but this also open vulnerability to break your app by us, I am pretty sure we did that before. I will repeat again, we are open for expose more types as long as provide a rationale and good usage. The thinking behind is probably not that obvious, but trust me I care about the overall users experience and that's why building this lib and maintaining it every day.

**Comment by jaypalexa** [comment]
Yep, I do appreciate the consideration behind the given rationale, very much so.  Trying to protect from breaking changes is difficult and admirable.  However, because we are _still_ importing these underlying types via `/dist/types` and `/dist/types/form`, we are still just as vulnerable to breaking changes, no?

(Also, I don't have an elegant "solution" to this, so I feel bad to be appearing to be griping about it...sorry about that.  Personally, I am not importing a huge number of react-hook-form types, so this approach is good enough for me at the moment.)

**Comment by bluebill1049** [comment]
> Yep, I do appreciate the consideration behind the given rationale, very much so. Trying to protect from breaking changes is difficult and admirable. However, because we are _still_ importing these underlying types via `/dist/types` and `/dist/types/form`, we are still just as vulnerable to breaking changes, no?
> 
> (Also, I don't have an elegant "solution" to this, so I feel bad to be appearing to be griping about it...sorry about that. Personally, I am not importing a huge number of react-hook-form types, so this approach is good enough for me at the moment.)

If you would like to expose some of the types, let us know (with reason and example) we will discuss internally the lib **should**  those types, we will and open as well. Check out the last patch, it's exactly what we did.

**Comment by SatoAV** [comment]
For my use case, I use two types for custom Input components: `ValidationOptions` and `FieldError`

First one is needed to pass correct `valdationOptions` object to the component.
Second is used by an error parser function, which translates various error type into localized error messages.

I don't understand how change in a type would hurt more than having no type at all and have a possibility for poorly traceable errors, when some API signature changes. The benefit of a strongly typed environment is that I can instantly see any possible errors when upgrading, if some type constraints are not satisfied anymore.

**Comment by SatoAV** [comment]
Also, somehow, other types like return of `useForm` and `useFormContext` are lost in v6 😕 

![image](https://user-images.githubusercontent.com/1641218/86590082-888b0300-bf97-11ea-8b33-827fe4c4a2d9.png)

**Comment by bluebill1049** [comment]
so looks like in the thread, most users need `FieldError` and `ValidationOptions`.

**Comment by SatoAV** [comment]
I think the best solution is to simply export all types just like before.
It's how it is done in every other library, and it enables the usage of strong types for those who need it.

But if somehow this is too much against your concept, at least the exported functions and components should expose their types, because without it we can't havy any auto-completion of props or any type validation whatsoever.

**Comment by bluebill1049** [comment]
> But if somehow this is too much against your concept, at least the exported functions and components should expose their types, because without it we can't have any auto-completion of props or any type validation whatsoever.

👍 that's what we after.

**Comment by kotarella1110** [comment]
> Also, somehow, other types like return of `useForm` and `useFormContext` are lost in v6 😕
> 
> ![image](https://user-images.githubusercontent.com/1641218/86590082-888b0300-bf97-11ea-8b33-827fe4c4a2d9.png)

@SatoAV please provide codesandbox example.

**Comment by pixelass** [comment]
@bluebill1049 I don't understand why typings for components are not exported. This will always cause errors. If you don't export the typings, that's one thing but not providing the typings for exported components is a big issue.

The `ErrorMessage` typing is not exported so I get a typescript error.

**Comment by bluebill1049** [comment]
> @bluebill1049 I don't understand why typings for components are not exported. This will always cause errors. If you don't export the internal typings, that's one thing but not providing the typings for exported components/hooks/methods is a big issue.
> 
> The `ErrorMessage` typing e.g. is not exported so I get a typescript error.

Provide an example with the error.

**Comment by bluebill1049** [comment]
> The `ErrorMessage` typing e.g. is not exported so I get a typescript error.

ErrorMessage is a separate repo now, you can request the type to be exposed there.

**Comment by eMarek** [comment]
Thank you for your hard work @bluebill1049. I appreciate it. However I agree with others in this thread that all types should be exported. I kind of understand that you want to export only those which are documented. I suggest to document only those types which are crucial and export all so people can use them if they want. Thank you once again.

**Comment by elwynelwyn** [comment]
I really appreciate your concern for avoiding future breaking changes, however I don't think this approach is quite right. Conceptually, the types of the react-hook-form public API (e.g. everything returned from `useForm`) should be exported, so that consumers of those public functions and objects can correctly type their application when working with them. No issues with keeping some types internal - but only those types not exposed via the documented parts of react-hook-form, e.g. `useForm`.

I think if you wait for use-cases and add them back one-by-one as people request them, eventually you will be exporting them all anyway once all the non-mainstream uses of the library come through.

If you do prefer a case-by-case basis, I would like to make a case for `FieldErrors` to be available again. [The docs](https://react-hook-form.com/api/#errors) show them typed as `Record<string, Object>`, however if I try and type my function to accept that I get a type error:
https://codesandbox.io/s/bold-bouman-yk86j?file=/src/App.tsx
Now I could start defining better types for Object, look into a Record of Partial keyof MyFormValues etc - but I'm just essentially recreating (and maintaining) FieldErrors at this point.

A change to the shape of `errors` would be a breaking change - thus changing the `FieldErrors` types would be a matching breaking change (and correctly so). So by not-exporting FieldErrors you are not preventing future breaking changes, you are just moving that breaking change somewhere else in peoples code (or encouraging people to not correctly type their code).

**Comment by eithe** [comment]
First of all, react-hook-form is one of the most amazing libraries I have ever come across, and the attention to detail not only to the code, but also to the website and the documentation is truly a great achievement. It is a testimate to the hard work the people involved do, and I can't start to thank you enough (looking at you @bluebill1049) for what you provide to us for free.

Having said that, I believe the rationale behind not exporting types is flawed as also @elwynelwyn noted above. From that I have read above, the main argument is to avoid breaking changes to our code bases, but I believe the cost of that is introducing unforseen bugs in our code instead. One of the main reasons I use typescript is to minimize the sort of errors where third party libraries have breaking changes. Back in the days without typescript I would often need to run the solution/tests before noticing that some library x have changed the return type of some function, or have changed what they expect us to provide as an argument to a function. If I instead use the types provided from the library I can detect breaking changes early and easily at compile time.

Going back to react-hook-form if we start typing our own types for e.g. the _errors_ object (or as a last resort just use _any_ if you don't have the time to figure it all out yourself), we will quickly get out of sync with the library without the abilility to easily and quickly notice if react-hook-form updates it's types.

I hope you reconsider your decision, and at least (as others have noted) export types for all exported functions, arguments, hooks, components, props etc.

**Comment by pixelass** [comment]
>  Back in the days without typescript I would often need to run the solution/tests before noticing that some library x have changed the return type of some function

Usually versioning via [semver](https://semver.org/) should tell you about breaking changes and help to assume the impact an update will or might have.

**Comment by bluebill1049** [comment]
Thank you @eithe & @elwynelwyn feedback. I will bring this topic again into the team discussion.

**Comment by bluebill1049** [comment]
hey @eithe & @elwynelwyn, after discussion with the team members, we agreed to expose with all the types under the following condition.

1. official types will still be documented in the doc.
2. none official types will potentially lead to breaking change and usage is under developer's own risk.

I think this reasonable to make everyone happy again and at the same time having the awareness that undocumented type will potentially change through the release.

**Comment by pixelass** [comment]
@bluebill1049 Sounds reasonable. We're really happy about this decision and looking forward to new releases.
As this ties perfectly into our timeline I want to give you a big: 

### THANK YOU

**Comment by eMarek** [comment]
I am wondering how many people will land this page because of:

`'"../../../node_modules/react-hook-form/dist"' has no exported member named 'ValidationRules'. Did you mean 'ValidationRule'?ts(2724)`

Yeah, that type is now called `RegisterOptions`.

**Comment by bluebill1049** [comment]
> I am wondering how many people will land this page because of:
> 
> `'"../../../node_modules/react-hook-form/dist"' has no exported member named 'ValidationRules'. Did you mean 'ValidationRule'?ts(2724)`
> 
> Yeah, that type is now called `RegisterOptions`.

oh crap... I completely forgot about that in the doc and even in the changelog... I will sort this out.

**Comment by hin7141** [comment]
> I am wondering how many people will land this page because of:
> 
> `'"../../../node_modules/react-hook-form/dist"' has no exported member named 'ValidationRules'. Did you mean 'ValidationRule'?ts(2724)`
> 
> Yeah, that type is now called `RegisterOptions`.

This saves my day. Thank you sir. @eMarek

**Comment by wazcov** [comment]
Confused. I tried swapping it and get `TS2709: Cannot use namespace 'RegisterOptions' as a type.`

**Comment by bluebill1049** [comment]
> Confused. I tried swapping it and get `TS2709: Cannot use namespace 'RegisterOptions' as a type.`
> 
> I can see ValidationRules exported but my TS compiler complains that it isn't.
> 
> All since upgrading from 6.3.0 to 6.15.1. Any ideas welcome @hin7141 @bluebill1049

https://github.com/react-hook-form/react-hook-form/blob/master/src/types/validator.ts#L20

**Comment by AriaMoradpour** [comment]
Im also a bit confused now. from what i undrestand all of the types should now be available. but i am getting this error 

`'"react-hook-form/dist/types/form"' has no exported member named 'FieldValues'. Did you mean 'SetFieldValue'?`

I am using version 7.0.4.  

Any idea why this would be happening @bluebill1049 @hin7141

**Comment by eMarek** [comment]
Try this: `import { FieldValues } from 'react-hook-form'`
