### ISSUE TITLE
React Select onChange not working in v6

### ISSUE THREAD

**Issue by srid12** [react-hook-form/react-hook-form#2075]
**Describe the bug**
React Select onChange not working in v6

**To Reproduce**
1. Go to link
2. Click on IceCream Preference
3. Check Console

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-with-ui-library-ts-bim0q

**Expected behavior**
Console log should print hello

**Screenshots**

**Comment by bluebill1049** [comment]
We have removed many props in Controller and keep it a lot simpler with re-render props. Have a look the note here: https://github.com/react-hook-form/react-hook-form/releases/tag/v6.0.0-rc.2

**Comment by khanakia** [comment]
@bluebill1049 I just created an example based on v6 and passed the component to the RENDER props but still onChange is not triggering. It would be great if you can point out the issue what wrong i could be doing ? Here's the new sandbox link

https://codesandbox.io/s/react-hook-form-with-ui-library-ts-forked-uw506?file=/src/index.tsx

**Comment by bluebill1049** [comment]
`<Select onChange={(v) > onChange(v)}` react-select's argument is not standard `e.target.value` instead an object.

**Comment by khanakia** [comment]
@bluebill1049  Just updated the codesandbox again as you suggested but still onChange not triggering

**Comment by bluebill1049** [comment]
> @bluebill1049 Just updated the codesandbox again as you suggested but still onChange not triggering

it's working...

**Comment by khanakia** [comment]
@bluebill1049 I meant the `onChange` event not working it should alert HELLO

<img width="411" alt="Screenshot 2020-09-22 at 12 09 18 PM" src="https://user-images.githubusercontent.com/2174170/93850780-75e9b580-fccc-11ea-8fe7-a378d5a4c71e.png">

**Comment by bluebill1049** [comment]
> @bluebill1049 I meant the `onChange` event not working it should alert HELLO
> 
> <img alt="Screenshot 2020-09-22 at 12 09 18 PM" width="411" src="https://user-images.githubusercontent.com/2174170/93850780-75e9b580-fccc-11ea-8fe7-a378d5a4c71e.png">

that's not supported.

**Comment by bluebill1049** [comment]
use the onChange in the render props

**Comment by khanakia** [comment]
@bluebill1049 It's already under props as you can see in the CodeSandbox. So i am confused Controller should pass the onChange event to the Controlled Component.

**Comment by bluebill1049** [comment]
please refer to the v6 doc: https://react-hook-form.com/api#Controller @khanakia

**Comment by tsahnarExp** [comment]
This indeed does not work, the onChange event is not called when using render props. @khanakia did you find a solution for this?

**Comment by Abdulmoiz-Ahmer** [comment]
@bluebill1049 I think this is what it should be like:
<Controller
																			name={`quantity_type[${index}][${ind}]`}
																			control={control}
																			render={({
																				onChange,
																				onBlur,
																				value,
																				name,
																				ref
																			}) => (
																				<Select
																					labelId="demo-simple-select-outlined-label"
																					label="Quantity Type"
																					onChange={onChange}
																					onBlur={onBlur}
																					defaultValue={''}
																				>
																					<MenuItem value={'boxes'}>
																						Boxes
																					</MenuItem>
																					<MenuItem value={'cartons'}>
																						Cartons
																					</MenuItem>
																				</Select>
																			)}

																		/>
```
