### ISSUE TITLE
⌨️ V6: Type request 

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#2077]
We are limited to the amount of `Types` that the lib export because `types` should be treated as equally a code change. We prefer utility `types` live in your codebase and fewer `types` for the lib to be exported. If you would like us to export certain types. Please follow the steps below, we are happy to discuss and make the change. 

https://react-hook-form.com/ts

1. provide the reason the need to export the `type`
2. provide usage

**Comment by xiaoyu-tamu** [comment]
type : UseFormOption

1. Useful when encapsulate your own `Form` component or `useEnhancedForm`;

2. 
```
function useEnhanceForm(options:Type) {
   useForm({ shouldFocusError:true,  ...options,})
}

similar concept also apply to <Form />
```

**Comment by bluebill1049** [comment]
@kotarella1110 looks legit above for me :) let me know your thoughts.

**Comment by bluebill1049** [comment]
> type : UseFormOptions
> 
> 1. Useful when encapsulate your own `Form` component or `useEnhancedForm`;
> 
> ```
> function useEnhanceForm(options: UseFormOptions) {
>    useForm({ shouldFocusError:true,  ...options,})
> }
> ```
> 
> similar concept also apply to

can you robust your code example a bit?

**Comment by xiaoyu-tamu** [comment]
> > type : UseFormOptions
> > 
> > 1. Useful when encapsulate your own `Form` component or `useEnhancedForm`;
> > 
> > ```
> > function useEnhanceForm(options: UseFormOptions) {
> >    useForm({ shouldFocusError:true,  ...options,})
> > }
> > ```
> > 
> > 
> > similar concept also apply to
> 
> can you enhance your code example a bit (perhaps we can reuse that in the doc as well)?

Updated, I'm not a fan of custom resolve, part of useEnhancedForm is copied form doc just for demo purpose.

**Comment by kotarella1110** [comment]
@xiaoyu-tamu @bluebill1049 I think the type can be defined by the user.

```ts
type UseFormOptions = Parameters<typeof useForm>[0];
```

**Comment by bluebill1049** [comment]
good point! @kotarella1110

**Comment by xiaoyu-tamu** [comment]
> @xiaoyu-tamu @bluebill1049 I think the type can be defined by the user.
> 
> ```ts
> type UseFormOptions = Parameters<typeof useForm>[0];
> ```

Can this pass generic type variables to useForm?

**Comment by kotarella1110** [comment]
@xiaoyu-tamu It is impossible. We should export `UseFormOptions` 👍

**Comment by bluebill1049** [comment]
`UseFormOptions` has been included with the latest `patch`
