### ISSUE TITLE
Special input name takes too much time to render

### ISSUE THREAD

**Issue by g1geordie** [react-hook-form/react-hook-form#2079]
**Describe the bug**
The below rendering will take too much time when the input value is not valid.
```javascript
 <input name="entry.999999999" ref={register({
            required: true,
            pattern: {
              value:/^0[0-9]{9}$/,
              message: "not matched"
            }
          })}  />
```
error.entry is an array instead of an object, causing 999999999 loops at 
```javascript
objectRef.filter((data) => isObject(data) && !isEmptyObject(data))
```
https://github.com/react-hook-form/react-hook-form/blob/1441a0186b8eab5dccb8d85fddb129d6938b994e/src/utils/unset.ts#L48

**Comment by bluebill1049** [comment]
sorry, we don't support integer as `key` name.
