### ISSUE TITLE
Error while removing manual element

### ISSUE THREAD

**Issue by Nickman87** [react-hook-form/react-hook-form#208]
**Describe the bug**
I have a scenario where I manually register a component (see example: https://codesandbox.io/s/react-hook-form-watch-after-empty-defocus-ukknu) but when my app moves to a different view, it tries to unregister and throws an error because the fieldsRef mapping is empty at that time.

`removeEventListenerAndRef` is called from `unregister` with `undefined` as the `field` parameter. This method calls `findRemovedFieldAndRemoveListener` which tries to destructure the field parameter but it is undefined so it crashes.

**To Reproduce**
I tried to reproduce it in a contained scnario, but it seems to work just fine:
https://codesandbox.io/s/react-hook-form-watch-after-empty-defocus-ukknu

I don't know what is causing the crash in my application, but it's a more complicated stack with next.js and hot reloading, so probably something causes a delayed unregister or something like that.

**Expected behavior**
If a field no longer exists in the fieldsRef, the unregister method should just ignore it (as it also ignores double registrations.

**Additional context**
Not sure if this a long term issue and a good solution, but I think an extra null check would not be a bad thing?

**Comment by bluebill1049** [comment]
yea, i will take a look at thtat.

**Comment by bluebill1049** [comment]
do you have a screenshot of the error?

**Comment by bluebill1049** [comment]
you mind trying this beta `3.21.15-beta.1` see if you can still reproduce the error? and screenshot, please

**Comment by bluebill1049** [comment]
need a way to reproduce this issue

**Comment by bluebill1049** [comment]
join https://spectrum.chat/react-hook-form?tab=posts if you can have a chat on this issue

**Comment by Nickman87** [comment]
![image](https://user-images.githubusercontent.com/870416/62863418-08b5d380-bd09-11e9-93d3-8ca08c08f29a.png)

![image](https://user-images.githubusercontent.com/870416/62863426-0e131e00-bd09-11e9-9429-d7071436dc88.png)

![image](https://user-images.githubusercontent.com/870416/62863438-153a2c00-bd09-11e9-9fca-eee38dbd0f6f.png)

Hope these help :).

**Comment by bluebill1049** [comment]
`react-hook-form@3.21.15-beta.2` I have made a check before `unregister` can you try this beta? and let me know if it fix the issue.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/releases/tag/v3.21.15

**Comment by bluebill1049** [comment]
patched and released

**Comment by bluebill1049** [comment]
@Nickman87 you happy to close this one? or you still have concern or issue?

**Comment by Nickman87** [comment]
Seems to be working fine for me 👍
