### ISSUE TITLE
useWatch does not seem to be returning any value

### ISSUE THREAD

**Issue by pixel-mattp** [react-hook-form/react-hook-form#2081]
**Describe the bug**
I am trying to use `useWatch` in a component rather than `watch` to isolate re-render to this component only.  No matter what I try, however, it returns nothing.  Using `watch` function works fine and returns the value.

**To Reproduce**

CodeSandbox link below to replicate...

**Codesandbox link (Required)**
[Sanbox link here](https://codesandbox.io/s/sad-albattani-ovxbt)

**Expected behavior**
Value should be returned from the useWatch function.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser Latest Chrome

**Comment by bluebill1049** [comment]
Thanks this is bug with reset API not integrate with `useWatch` will patch this issue.

**Comment by bluebill1049** [comment]
Patched example: 

https://codesandbox.io/s/autumn-tree-cwg9b?file=/src/InnerComponent.jsx
