### ISSUE TITLE
checkbox not touched in Safari

### ISSUE THREAD

**Issue by pixelass** [react-hook-form/react-hook-form#2084]
**Describe the bug**
`formState.touched` is not working in Safari with checkbox

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-useform-template-n7nse?file=/src/index.js
2. Click on either checkbox
3. Checkbox is never touched

**Codesandbox link (Required)**
Include a codesandox will help us to investigate the issue quicker.

https://codesandbox.io/s/react-hook-form-useform-template-n7nse?file=/src/index.js

**Expected behavior**
Chrome and Safari should have the same behavior. Checkboxes should trigger `touched`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OS X 10.15.5 (19F101)
 - Browser Safari 3.1.1 (15609.2.9.1.2)
- React-hook-forms: v.5.7.1

**Additional context**

**Comment by bluebill1049** [comment]
This bug is related to a bug with safari: https://github.com/react-hook-form/react-hook-form/issues/1079
