### ISSUE TITLE
Rename dirtyFields to dirty or touched to touchedFields in formState for consistency

### ISSUE THREAD

**Issue by smashercosmo** [react-hook-form/react-hook-form#2086]
**Is your feature request related to a problem? Please describe.**
That's definitely a very minor thing, but perfectionist in me is bit frustrated by naming inconsistency for touched and dirty fields. 

**Describe the solution you'd like**
Rename dirtyFields to dirty or touched to touchedFields

**Comment by bluebill1049** [comment]
man, I wish you have told me 2 weeks before we released v6... it's too late now, will have to be the next major release...

**Comment by smashercosmo** [comment]
Yeah, we can do it in the next major release. Why closing then?  :)

**Comment by bluebill1049** [comment]
I am only keep issues open :) I have noted this down in the project board with this request.

**Comment by smashercosmo** [comment]
Alright 👍

**Comment by bluebill1049** [comment]
![Uploading Screen Shot 2020-07-06 at 9.10.08 pm.png…]()
FYI
