### ISSUE TITLE
Switch component validation does not update when passed

### ISSUE THREAD

**Issue by georgetudor93** [react-hook-form/react-hook-form#2090]
Hello, 
I've been stuck for a while validating a terms and conditions field. First i tried using checkbox but there were compatibility issue on iOS so i decided to use a Switch component from react-native-paper. 

The problem I am having now is that the switch validates only once on submit, then it only updates if validation is not passed. I've tried a lot of solutions so far but i just hit a dead end. 

Here is the code so far (with all fancy solutions aside):

export function etc ({ navigation })  {
    const { control, watch, handleSubmit, errors } = useForm({
        criteriaMode: "all",
    });

    const [checked, setChecked] = React.useState(false);

    const onSubmit = data => {
        Alert.alert(
        "Form Data",
        JSON.stringify(data)),
        navigation.navigate('Dashboard'),
        console.log(data)
    };
return (
     <Controller
                    control={control}
                    render={({ onValueChange, value }) =>(
                        <Switch  
                        value={checked}
                        onValueChange={() => checked ? setChecked(false) : setChecked(true)}
                        />
                    )}
                    name='terms'
                    rules={{validate: (value) => checked == true}}
                    defaultValue={checked}
               
                    
        /> 
        {errors?.terms?.types?.validate && <HelperText style={[defaultStyles.primaryFont]} type="error">You must agree with the terms and conditions</HelperText>}
);
};

**Comment by georgetudor93** [comment]
Finally found the issue. I was missing required: true

**Comment by georgetudor93** [comment]
Reopened... Although the validation updates when required is added, the 'required' condition does not validate the form for some reason. Back to square one :(

**Comment by bluebill1049** [comment]
please follow the template by supply a codesandbox with your problem.

**Comment by georgetudor93** [comment]
sorry it took so long. you can find the codesandbox here: https://codesandbox.io/s/react-hook-form-unregister-v6-epfbe?file=/App.js

**Comment by bluebill1049** [comment]
looks like you never pass the value back to hook form. you should use `onChange` from Controller's render prop.

**Comment by georgetudor93** [comment]
the switch only accepts onValueChange as prop

**Comment by bluebill1049** [comment]
that's fine then you do `onValueChange=() => {onChange(value)}`

**Comment by bluebill1049** [comment]
the idea is to give the value back to the Controller.

**Comment by georgetudor93** [comment]
I tried different methods but it seems to crash the Controller.

It's not loading the Component props on inspect and it leaves me with the following error:

Uncaught TypeError: Cannot read property 'current' of undefined
    at Object.useRef (react_devtools_backend.js:24)
    at useRef (react.development.js:1472)
    at Controller (index.esm.js:1697)
    at E (react_devtools_backend.js:24)
    at t.inspectHooksOfFiber (react_devtools_backend.js:24)
    at Be (react_devtools_backend.js:6)
    at Object.inspectElement (react_devtools_backend.js:6)
    at react_devtools_backend.js:6
    at t.value (react_devtools_backend.js:6)
    at react_devtools_backend.js:32
    at t (react_devtools_backend.js:8)

**Comment by bluebill1049** [comment]
```

<Controller
            control={control}
            render={({ onChange, value }) => (
              <Switch
                value={value}
                onValueChange={value => {
                  onChange(value);
                }}
              />
            )}
            name="terms"
            rules={{ required: true, validate: value => value === true }}
            defaultValue={false}
/>
``

Take a look above, that's how it should be.

**Comment by georgetudor93** [comment]
it doesn't seem to work neither for my project or codesandbox

**Comment by bluebill1049** [comment]
how is this going to work in codesandbox? it's react native? ok can you console.log what's value from onValueChange, make sure the correct value is assigned to onChange

**Comment by georgetudor93** [comment]
i added all the packs needed for codesandbox in order to make it work for react native. 
just played with the console.log for my value from onValueChange and it log's accordingly with the switch. the value seems to be returned as it should

**Comment by georgetudor93** [comment]
![FireShot Capture 031 - react-hook-form-unregister-v6 - CodeSandbox - codesandbox io](https://user-images.githubusercontent.com/22745266/86858688-d2740600-c0c9-11ea-8e8e-8c6dbaa41ce5.png)

**Comment by bluebill1049** [comment]
can you update that codesandbox? i can't see anything on the screen.

**Comment by georgetudor93** [comment]
you just need to click on this switch
![InkedFireShot Capture 034 - react-hook-form-unregister-v6 - CodeSandbox - codesandbox io_LI](https://user-images.githubusercontent.com/22745266/86859262-f126cc80-c0ca-11ea-865b-5faa90e4f1dc.jpg)

**Comment by bluebill1049** [comment]
<img width="1240" alt="Screen Shot 2020-07-08 at 10 35 56 am" src="https://user-images.githubusercontent.com/10513364/86859795-d07c6800-c106-11ea-8744-8314ccdb971a.png">

it's working for me.

**Comment by georgetudor93** [comment]
oh... stupid me, i get it now. 
my problem was that i was trying to use a custom value that wouldn't be passed back to the Controller even if it worked correctly.
i got so deep into this and ignored a basic thing that i already did for inputs because i didn't know exactly how to pass that onChange to onValueChange :)))

thanks for the support and fast response time man 🤝
