### ISSUE TITLE
[v6] Material-ui checkbox group examples don't work anymore with v6

### ISSUE THREAD

**Issue by harrisrobin** [react-hook-form/react-hook-form#2091]
**Describe the bug**
I'm trying to get a checkbox group using material-ui, none of the workarounds I've come across work in v6 anymore. I was able to use [this workaround](https://github.com/react-hook-form/react-hook-form/issues/584) in v5 but it completely broke in v6. I've tried a few things..

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-controller-template-bs2qq?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
A clear way of using checkboxes. In this case, I am expecting the unchecked items to be an empty string and the checked items to be the value.

I think it would be great if we had a working checkbox group example in the official docs.

This library is great, thanks again for all the hard work! Just missing a good checkbox group example, everything else works amazingly!

**Comment by bluebill1049** [comment]
Hey @harrisrobin, We have removed some of the props for `Controller`, take a look the change log: https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md use `render` prop instead.

**Comment by harrisrobin** [comment]
@bluebill1049 I still couldn't get a checkbox group example working. I tried to adapt the workaround with the render prop, but I can't seem to get it right :
https://codesandbox.io/s/react-hook-form-controller-template-lioo1?file=/src/index.js

Any help is greatly appreciated!

**Comment by pmaier983** [comment]
Hey @harrisrobin [This CodeSandbox](https://codesandbox.io/s/react-hook-form-v6-controller-24gcl) has a working example of MUI checkbox. For some additional help, I also messed with your example to show which checkbox was chosen by index (https://codesandbox.io/s/react-hook-form-controller-template-r2ihe). I hope this helps!

**Comment by harrisrobin** [comment]
@pmaier983 your tweaks to my CodeSandbox worked. Thank you! 

The CodeSandbox you linked to shows only one checkbox, but most people struggle with checkbox groups. I think it would be beneficial to have an example like that contributed to that CodeSandbox if it's linked to in the docs. I don't mind contributing to it, I would probably just do it the way you've done.

Cheers 🍻

**Comment by bluebill1049** [comment]
Thanks @pmaier983 ❤️
