### ISSUE TITLE
getValues() doesn't give the form default values

### ISSUE THREAD

**Issue by byildiz** [react-hook-form/react-hook-form#2095]
**Describe the bug**
getValues() doesn't give the default values of the form while watch() gives.

**To Reproduce**
Check out the console output of the below codesandbox link.

**Codesandbox link (Required)**
- [Example codesandbox](https://codesandbox.io/s/determined-carson-pkdr1)

**Expected behavior**
getValues() should give the same result with watch()

**Comment by bluebill1049** [comment]
`getVaues()` only works after all the inputs are mounted, so if you just calling it before the render is will not work. It's an API made to read the form value with an action.
