### ISSUE TITLE
"useWatch" along with "useFieldArray" that doesn't re-render all other elements in the array when only one of it is changed/touched?

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#2096]
Hello, is there a way to use "useWatch" along with "useFieldArray" that doesn't re-render all other elements in the array when only one of it is changed/touched?

_Originally posted by @ejose19 in https://github.com/react-hook-form/react-hook-form/discussions/2036_

**Comment by ejose19** [comment]
Shouldn't this be reopened? Or it was fixed?
