### ISSUE TITLE
Data field is removed after calling `reset()` from `useForm`

### ISSUE THREAD

**Issue by DieByMacro** [react-hook-form/react-hook-form#2098]
**Describe the bug**
Calling `reset` method exposed from `useForm`, either in submitting phase or manually function call, will remove (naive) field data.
E.g: 
`<input type="text" name="lastName" ref={register} />`

When registering with `required: false`, field won't be removed.
`<input type="text" name="thirdName" ref={register({ required: false })} />`

**This doesn't happen with `e.target.reset();`**

**To Reproduce**
Steps to reproduce the behavior: (console log opened already)
1. Go to [https://codesandbox.io/s/react-hook-form-reset-v6-ueumh?file=/src/index.js](https://codesandbox.io/s/react-hook-form-reset-v6-ueumh?file=/src/index.js)
2. Click **"Custom Reset Field Values & Errors"** button
3. Watch the data in `onSubmit`, `lastName` field is missing

**Codesandbox link (Required)**
Link reproduce: https://codesandbox.io/s/react-hook-form-reset-v6-ueumh?file=/src/index.js:746-754

**Expected behavior**
Data field should be kept with reseted value

**Screenshots**
![image](https://user-images.githubusercontent.com/610234/86726526-d6197580-c054-11ea-8879-8f919b85fde7.png)

**Comment by bluebill1049** [comment]
This is a similar issue with `useFieldArray` as well. There are two options

1. `reset({})`
2. `ref={register()}`

will update the doc to reflect this.

**Comment by bluebill1049** [comment]
This is patched for the website: https://github.com/react-hook-form/documentation/commit/b271f254f4a0435651c7bc02b16c45e575f195eb Thanks for the report.
