### ISSUE TITLE
Build 3.21.9-ie11 contains arrow functions

### ISSUE THREAD

**Issue by elswenson** [react-hook-form/react-hook-form#210]
**Describe the bug**
The latest -ie11 targeted build (3.21.9-ie11) contains arrow functions (It looks like a normal deploy? it doesn't look anything like the generated code in 3.21.4-ie11).

**To Reproduce**
1. Install `react-hook-form@3.21.9-ie11` using a node package manager (npm, yarn, etc)
2. Navigate to `node_modules/react-hook-form/dist/react-hook-form.js`

**Additional context**
I did check the package.json in node_modules/react-hook-form to make sure it contained the version 3.21.9-ie11 as expected.

**Comment by stramel** [comment]
@bluebill1049 I think we could improve the build process to build both the ie11 and modern build so we don't have to worry about this happening.

**Comment by bluebill1049** [comment]
@stramel curious on how can we do that?

**Comment by bluebill1049** [comment]
i will publish again with the latest (ie version)

**Comment by bluebill1049** [comment]
`react-hook-form@3.21.16-ie11` @elswenson

**Comment by elswenson** [comment]
Thank you!

**Comment by bluebill1049** [comment]
@elswenson please consider to support this repo by staring ⭐️ thank you in advance.
