### ISSUE TITLE
Form is submitted onChange when using downshift-js's Select with useFormContext and Controller

### ISSUE THREAD

**Issue by eckertalex** [react-hook-form/react-hook-form#2103]
**Describe the bug**
Form is submitted onChange of select when using downshift select with useFormContext and Controller

**To Reproduce**
1. Go to CodeSandbox link
2. Open CodeSandbox console
2. Open the select
3. Observe in console that the form was submitted'

**Codesandbox link (Required)**

- [CodeSandbox Link](https://codesandbox.io/s/react-hook-form-bug-u2bbv?file=/src/App.js)

**Expected behavior**
Form should not be submitted until the submit button was pressed

**Comment by bluebill1049** [comment]
hey, @erikras thanks for the issue report. This is HTML standard for a button, you should give the button a type otherwise it will be treated as `submit`.

**Comment by eckertalex** [comment]
OMG, I feel so stupid now. I didn't even think to check my implementation of Select.

Thanks for the help! Obviously, this issue can be closed.

**Comment by bluebill1049** [comment]
No worries at all, this got me many times as well. so we are not stupid... ❤️

**Comment by erikras** [comment]
LOL, autocomplete mention fail. But yes, I agree with your conclusion. 😄

**Comment by bluebill1049** [comment]
> LOL, autocomplete mention fail. But yes, I agree with your conclusion. 😄

omg, sorry about that... 🙏 I accidentally summon the boss...
