### ISSUE TITLE
Material UI Autocomplete not working on v6

### ISSUE THREAD

**Issue by MatiasCiccone** [react-hook-form/react-hook-form#2105]
**Describe the bug**
Material UI Autocomplete is not working on v6

**To Reproduce**
1. Go to [5.7.2 sandbox](https://codesandbox.io/s/react-hook-form-572-controller-material-ui-autocomplete-90imj) and check it is working
2. Go to [6.0.0 sandbox](https://codesandbox.io/s/react-hook-form-600-controller-material-ui-autocomplete-hyp4v) and check it is not working

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-572-controller-material-ui-autocomplete-90imj
https://codesandbox.io/s/react-hook-form-600-controller-material-ui-autocomplete-hyp4v

**Expected behavior**
Should work with v6

**Additional context**
May be related to this https://github.com/react-hook-form/react-hook-form/issues/2091

**Comment by ganlub** [comment]
I see that some props on for the `Controller` have been removed in favor of using the `render` prop.
I've made a fork of the examples' sandbox using instead the `render` prop on v6.0.1: https://codesandbox.io/s/react-hook-form-controller-601-j2df5

@bluebill1049 can you please update the original sandbox if this is how it should be done now?

**Comment by pmaier983** [comment]
The current go-to sandbox for MUI auto-complete (v6.0.1) is: https://codesandbox.io/s/react-hook-form-v6-controller-24gcl. This has auto-complete working! If you find a codeSandbox in the docs without a working MUI please link it to me!

**Comment by pmaier983** [comment]
@MatiasCiccone I believe ganlub correctly identified the issue. You must use the render prop in v6.0+. Your 6.0 Codesandbox is forked from a 5.7.2 version without accounting for the render prop change needed (per the [ChangeLogs](https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md)). Again, take a look at [This Codesandbox](https://codesandbox.io/s/react-hook-form-v6-controller-24gcl.) to see how to correctly implement MUI in 6.0. Thank you!

**Comment by bluebill1049** [comment]
Thanks @ganlub ❤️

**Comment by MatiasCiccone** [comment]
@pmaier983 I tried using it with render in my sandbox but I was using it wrong, glad @ganlub figured it out. Thanks for your time @pmaier983, @bluebill1049 and @ganlub

**Comment by xiaoyu-tamu** [comment]
v6 https://codesandbox.io/s/react-hook-form-v6-controller-24gcl
v5 https://codesandbox.io/s/react-hook-form-controller-079xx?file=/src/MuiAutoComplete.js

@bluebill1049 
@pmaier983 

Looks like v6  will re-render whole form form on every AutoCompete select?

**Comment by bluebill1049** [comment]
@xiaoyu-tamu looks like it's a bug.

**Comment by bluebill1049** [comment]
can you raise a bug? i will investigate the reason behind.

**Comment by xiaoyu-tamu** [comment]
@bluebill1049  Will do

**Comment by mcasteller** [comment]
Hi, I have one additional concern about this, is there a way to avoid having a default value. If we remove default autocomplete value in sandbox V6.0.0 example, then an uncontrolled/controlled component error arise at the time user picks an option.
And not having a default value is a very common use case I guess.
Please if you can let me know how to avoid that react error.
Plain MUI Autocomplete component does not throw that error, seems to be a react-form-hook interaction.

Thanks!

**Comment by bluebill1049** [comment]
> Hi, I have one additional concern about this, is there a way to avoid having a default value. If we remove default autocomplete value in sandbox V6.0.0 example, then an uncontrolled/controlled component error arise at the time user picks an option.
> And not having a default value is a very common use case I guess.
> Please if you can let me know how to avoid that react error.
> Plain MUI Autocomplete component does not throw that error, seems to be a react-form-hook interaction.
> 
> Thanks!

<img width="921" alt="Screen Shot 2020-07-08 at 9 40 25 pm" src="https://user-images.githubusercontent.com/10513364/86914402-a4430480-c163-11ea-98bb-082a37c6b50e.png">

**Comment by AlesMarz** [comment]
@mcasteller did you manage to resolve your issue?

I am not sure what to do with the answer of @bluebill1049 on your question.

**Comment by mcasteller** [comment]
Hi there, yes, based on @bluebill1049 notes I understand we must set up a default value four our form inputs. 

Our forms have like two states, one at the time we need to show some preload data, and the other one at the time we want a "clean" form without any data at all.

The preload data state it's easy to fulfill with default values, we just assign some of our data into `defaultValues` variable.

Our concern was about the empty form version, we will need to set an empty default data and that was fine for majority of fields.

But for MUI Autocomplete we had an uncontroller/controlled error. We figure out what was happening it was related to `defaultValue`. If you assign '' as autocomplete field default value, the MUI component takes '' as input and complains about it.

The solution was to pass 'null' as default value, that way:
1. we meet react-hook-form `defaultValues` requirement
2. we can deal with MUI autocomplete internal logic not to throw those render exceptions.

`const defaultValues = {
    currentAddress: state.address  || null
    },
`

Hope this to be clear enough.

**Comment by MatiasCiccone** [comment]
yes @mcasteller `null` will do the trick. Also, if anyone has a problem with an MUI Autocomplete with required rule and `multiple`. An empty array will make the form valid you should pass `null` to the `onChange` function if the array is empty.

**Comment by bluebill1049** [comment]
Thanks @mcasteller & @mat-jaworski for sharing solutions.

**Comment by gsandorx** [comment]
> yes @mcasteller `null` will do the trick. Also, if anyone has a problem with an MUI Autocomplete with required rule and `multiple`. An empty array will make the form valid you should pass `null` to the `onChange` function if the array is empty.

@MatiasCiccone do you have a working example, showcasing an Autocomplete "multiple" and a required rule?

**Comment by MatiasCiccone** [comment]
@gsandorx I don't have a live example but the code will be something like this:

```
<Controller
  name="name"
  rules={{ required: true }}
  control={control}
  render={({ onChange, ...props }) => (
    <Autocomplete
      {...props}
      options={options}
      renderInput={renderInput}
      onChange={(_event, data) => onChange(data.length ? data : null)}
      multiple
    />
  )}
/>
```
