### ISSUE TITLE
Radio Button issue

### ISSUE THREAD

**Issue by Aswinikumar02** [react-hook-form/react-hook-form#2109]
I have used 2 Radio Button inside controller. On initial load 1 radio button will be checked. 
Case 1 : If i submit without changing the radio option.it is taking as undefined.
Case 2 : when i want to select the next radio option both the radio is checked.

**Comment by pmaier983** [comment]
Hello Aswinikumar02 😄. Please create a [CodeSandbox](https://codesandbox.io/) detailing your issue so we can see whats going on. Thank you!
