### ISSUE TITLE
[REQ] Ability to return form and field level errors from submission 

### ISSUE THREAD

**Issue by stramel** [react-hook-form/react-hook-form#211]
**Is your feature request related to a problem? Please describe.**
This is a feature request for being able to pass the form errors from a submission.

**Describe the solution you'd like**
I would like to see the callback passed to `handleSubmit` be able to handle being returned an object of errors that could be merged into the existing `errors` object. Including a special case for an overall form-level error.

**Describe alternatives you've considered**
I tried manually implementing something like this and it requires a lot of work from the implementer's side.  

/cc @bluebill1049 @barrymay

**Comment by bluebill1049** [comment]
@stramel can you give some code example? I am not very clear in term os requirement 🤔

**Comment by stramel** [comment]
@bluebill1049 Here is some rough pseudo code.

```jsx
const { register, errors, handleSubmit } = useForm()

async function submit() {
	const response = await loginApi()
	if (response.errors) {
		return response.errors.password // 'Invalid Password'
	}
	// navigate
}


<form onSubmit={handleSubmit(submit)}>
	<input name="username" ref={ref} />
	{errors && errors.username}
	<input name="password" ref={ref} />
	{errors && errors.password} // This should display `'Invalid Password'`
</form>
```

Where the error response from the login call, would display in the `errors` object with the associated input name.

As for the form-level error, it would be similar but instead of an input name as the key in the object it would use something like `const FORM_ERROR = ''` and would be able to use it like...

```
{
	[FORM_ERROR]: 'Unexpected Error'
}
```

**Comment by bluebill1049** [comment]
can you use `setError`?

**Comment by stramel** [comment]
@bluebill1049 I think `setError` would work for the form-level error. Although, I like the DX of being able to return the object from the submission callback. Especially since in my case the submit function is coming from outside the function with the form.

**Comment by bluebill1049** [comment]
sure i can take a look at that

**Comment by bluebill1049** [comment]
@stramel basically, anything return from the `handleSubmit` will merge with errors? (am I on the right track?)

**Comment by stramel** [comment]
That's what I was thinking. If we want, it could be limited to registered fields.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/releases/tag/v3.21.17

**Comment by stramel** [comment]
Shoot forgot to mention that I didn't test how this worked with nested naming

**Comment by bluebill1049** [comment]
I think it's fine, it will just extend, right?

**Comment by bluebill1049** [comment]
if not i will patch it again, it's not been documented just yet. :) hidden api

**Comment by stramel** [comment]
Is the errors object nested or flat?

**Comment by JeromeDeLeon** [comment]
> @bluebill1049 I think `setError` would work for the form-level error. Although, I like the DX of being able to return the object from the submission callback. Especially since in my case the submit function is coming from outside the function with the form.
> 
> I think it would be a minimal addition to the `handleSubmit` with a good DX trade-off.

In my use case,
```
const submit = data => {
   callSubmit(data, {
    setErrors,
    reset,
    otherSetters
   }
}

<form onSubmit={handleSubmit(submit)>
...
</form>
```

**Comment by bluebill1049** [comment]
@JeromeDeLeon you reckon return errors will make your life bit easier?

**Comment by JeromeDeLeon** [comment]
I don't think so. I don't have any use case for it that want me to use the **return errors** feature cuz like I said, I came from `formik` that didn't have that. Maybe for others 👍

**Comment by stramel** [comment]
Hmm, I suppose I could build this out as a helper in my apps.

```js
const applySubmissionErrors = callback => data => {
	const response = await callback(data)
	if (response && response.errors) {
		Object.entries(response.errors).forEach(([name, error]) => {
			setError(name, error)
		})
	}
}
```

Just seems like it would be easier to have in the lib and a nice DX win.

@JeromeDeLeon What other setters are you passing? Would it be easier to remove the wrapping function and just return an error object?

**Comment by bluebill1049** [comment]
what's your thoughts on this @barrymay ?

**Comment by JeromeDeLeon** [comment]
@stramel, `setStatus` in `const [status, setStatus] = useState({ });` for other things I want to do in my form like successfully detecting if It successfully submitted or not.

**Comment by stramel** [comment]
@bluebill1049 WDYT about using this to ensure the same error object? instead of just spreading the errors? 

```
Object.entries(response.errors).forEach(([name, error]) => {
  setError(name, error)
})
```

**Comment by bluebill1049** [comment]
@stramel Yeah it's nice, what you had above. what if you want a completely different error just for server-side? with merge, I can have a serverside error, not the field level.

**Comment by stramel** [comment]
Hmm I'm not sure it will be as obvious to some developers that they will need to return 

```
{
	password: {
		message: 'error'
	}
}
```

Maybe we could just set the type differently manually? `setError(name, error, 'submissionError')`

**Comment by bluebill1049** [comment]
oh you are right about that! going to fix that! thanks

**Comment by bluebill1049** [comment]
```
errorsRef.current = Object.entries(errors).reduce(
          (previous, [key, value]) => ({
            ...previous,
            [key]: {
              type: isString(value) ? value : value.type,
              message: isString(value) ? value : value.message,
            },
          }),
          {},
        );
```
what abou this?

**Comment by stramel** [comment]
Not sure how important it is but we are still losing `ref` and `isManual`? But also, is it okay that we are moving error building out of the `setError` function?

**Comment by testarossaaaaa** [comment]
This is a great library, but a little criticism, the more Wishlist is implemented, the more difficult it is to maintain and develop the library, I paid attention to the number of bug fixes for the whole time. Also, in my case, errors are returned in a different format, it depends on the server, and it is easier for me to call SetError than to convert to a different format, in general, a very narrow case.

I like that the library is really small and has a unique approach to form control, I would not want it to become a Swiss knife. Maybe it’s better to have a Cookbook?

**Comment by bluebill1049** [comment]
` is it okay that we are moving error building out of the setError function?` what u mean?

**Comment by bluebill1049** [comment]
@testarossaaaaa very good point!

**Comment by bluebill1049** [comment]
@stramel maybe we just stick with `setError` for now?

**Comment by stramel** [comment]
@bluebill1049 You can revert that code for now and we can continue the discussion.

**Comment by bluebill1049** [comment]
Thanks for understanding @stramel

**Comment by bluebill1049** [comment]
@stramel you happy to close this one for now?

**Comment by stramel** [comment]
I'm not sold on closing this yet. While I agree that if we implement every single feature, it will become hard to maintain and add bloat. I hardly think that a few lines of code can be considered bloat especially for the use the usefulness of the feature.

**Comment by bluebill1049** [comment]
Yea no worries @stramel I don't think it's amount line of code we added in. It's more like we introduce a feature, which is not so easy to document it down. what if we want the function to return something else, not just errors, and why function return would be combined with errors object. it doesn't feel natural to me when I was doing it, but again I do see its value. Just the implementation need be right.

Happy to leave this open if others have a similar concern and better solution.

**Comment by bluebill1049** [comment]
@stramel are we going to keep this issue open?

**Comment by stramel** [comment]
@bluebill1049 I would like to see someway of easily merging errors into the fields. Maybe it's just a helper that we can export?

**Comment by bluebill1049** [comment]
which method do you think we should export?

**Comment by bluebill1049** [comment]
hey @stramel going to close this issue (it's been awhile) now until we have a proper plan and solution for this :)

**Comment by saprativa** [comment]
so what is the best way to do it? is there any solution?

**Comment by jamiehaywood** [comment]
I ended up writing a helper function to set errors:

```ts
import { ErrorOption, FieldName, FieldValues } from 'react-hook-form';
/**
 * A function that maps all API error responses to inputs using RHF `setError`
 * @param setError RHF set error function passed in as a callback
 * @param errors Errors object returned from the API
 */
export function setFormErrors<TFieldValues extends FieldValues = FieldValues>(
  setError: (name: FieldName<TFieldValues>, error: ErrorOption) => void,
  errors: Record<string, string>
) {
  for (const error in errors) {
    // TODO:  work out how to type this correctly! See https://github.com/react-hook-form/react-hook-form/discussions/3354
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    setError(error as any, {
      type: 'server',
      message: errors[error],
    });
  }
}
```

where our server errors take the shape of:

```
{
  errors:{
    property: "property error message here"
  }
}
```

The problem I'm having is giving the helper correct inferred types. Perhaps @bluebill1049 / @stramel would be able to help in this regard? It would be good to get some examples of helper snippets into the docs.


Thanks again @bluebill1049 for the awesome library! Have used it across 3 jobs already, and it's by far the best React from library!

**Comment by jamiehaywood** [comment]
and having just re-looked at this code, I've realised that typing the `setFormErrors` function above is futile, because TypeScript doesn't provide runtime type safety. Also where the types are provided by the library, just pull them in... doh! 🤦🏻‍♂️

Update to snippet from above:

```ts
import { UseFormMethods } from 'react-hook-form';
/**
 * A function that maps all API error responses to inputs using RHF `setError`
 * @param setError RHF set error function passed in as a callback
 * @param errors Errors object returned from the API
 */
export function setFormErrors(
  setError: UseFormMethods['setError'],
  errors: Record<string, string>
) {
  for (const error in errors) {
    setError(error, {
      type: 'server',
      message: errors[error],
    });
  }
}

```
