### ISSUE TITLE
Validation errors for multiple linked fields

### ISSUE THREAD

**Issue by asterikx** [react-hook-form/react-hook-form#2117]
**Is your feature request related to a problem? Please describe.**

I have a login form with two fields for username and password. For both fields I have set up basic regex validation, but, additionally, I need a way to display async validation errors returned by the server, e.g. wrong username/password combination.

I want to display an error status (red border) on both fields and a single error message below the form (it's best practice to not let the user know which of both fields is wrong). As soon as the user changes *one of the two* fields (`reValidateMode: 'onChange'`), the error status on *both* fields and the error message below the form should be removed.

The best solution I came up with is to call `setError()` for both fields. But by doing so I treat the error as two independent errors. The error state of both fields is not merged. The user, therefore, needs to edit both fields to be able to resubmit the form, even if he/she just mistyped the username. This isn't ideal.

<details>
<summary>
Solution (not ideal, requires user to change both fields)
</summary>

```tsx
export function SignIn() {
  const { signIn } = useUser();

  const { register, handleSubmit, errors, setError, formState } = useForm<SignInFormData>();
  const { isSubmitting } = formState;

  const onSignIn = handleSubmit(async ({ username, password }: SignInFormData) => {
    try {
      await signIn(username, password);
    } catch (err) {
      if (
        err.code === "UserNotFoundException" ||
        err.code === "NotAuthorizedException"
      ) {
        // user provided wrong username or password
        setError("username", { type: "incorrect" });
        setError("password", { type: "incorrect" });
      } else {
        // something went worng
      }
    }
  });

  return (
    <VStack as="form" onSubmit={onSignIn}>
      <FormControl isRequired isInvalid={!!errors.username}>
        <Input
          name="username"
          ref={register({
            required: true,
            pattern: {
              value: /^[A-Z0-9.%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i,
              message: "This email looks wrong.",
            },
          })}
        />
        {!(errors.username?.type === "incorrect") && (
          <FormErrorMessage>{errors.username?.message}</FormErrorMessage>
        )}
      </FormControl>
      <FormControl isRequired isInvalid={!!errors.password}>
        <Input
          name="password"
          type="password"
          ref={register({
            required: true,
            pattern: {
              value: COGNITO_REGEX,
              message: "This password looks wrong.",
            },
          })}
        />
        {!(errors.password?.type === "incorrect") && (
          <FormErrorMessage>{errors.password?.message}</FormErrorMessage>
        )}
      </FormControl>
      <FormControl
        mb={8}
        isInvalid={
          errors.username?.type === "incorrect" &&
          errors.password?.type === "incorrect"
        }
      >
        <FormErrorMessage>
          Wrong username or password.
        </FormErrorMessage>
      </FormControl>
      <Button isLoading={isSubmitting}>Sign in</Button>
    </VStack>
  );
}

```
</details>

**Describe the solution you'd like**

A global error status, which is reset according to 'reValidateMode' by any of the "linked" fields.

**Comment by bluebill1049** [comment]
I think those type of logic is better to sit at your app-level instead of the lib.

**Comment by asterikx** [comment]
I actually agree.

My specific case requires only a submit error state that is being reset by any change to any of the two fields (`username` and `password`).

An app-level solution could be using `watch` to watch all fields and reset the error state. Would you recommend such a solution (also considering performance)?

```ts
const [wrongUsernameOrPassword, setWrongUsernameOrPassword] = useState(false);
const { email, password } = watch(['email', 'password']);

useEffect(() => {
  setWrongUsernameOrPassword(false);
}, [email, password, setWrongUsernameOrPassword]);
```

**Comment by bluebill1049** [comment]
I think the solution above is fine, consider only two fields I think use watch is fine, just beware when your form gets larger.

**Comment by giovanicascaes** [comment]
I know this have been closed already, but using a Yup validation schema could not address the problem too?

**Comment by asterikx** [comment]
I don’t know Yup well enough. AFAIK it performs field-level (possibly async) validation. My use case requires form-level validation (combinations of fields). That validation state should be determined by the response returned from the server after submitting the form.

**Comment by iamandrewluca** [comment]
Here is an example for password match validate

```tsx
const password1 = watch('password1');
const password2MatchValidator: Validate = useCallback(
    password2 => password2 === password1 ? undefined : 'Passwords do not match',
    [password1],
);
const password2Rules = useMemo(
    () => ({ validate: password2MatchValidator }),
    [password2MatchValidator],
);

return (
  <React.Fragment>
    <input name="password1" ref={register} />
    <input name="password2" ref={register(password2Rules)} />
  </React.Fragment>
)
```

**Comment by iamandrewluca** [comment]
A solution would be to pass as second argument to validate function all fields of the form, and user can check this inside validator
