### ISSUE TITLE
Question: FormContext Types

### ISSUE THREAD

**Issue by dfmartin** [react-hook-form/react-hook-form#212]
I am new to react-hook-form.  Doing an evaluation.  

I notice that `useForm` takes a generic parameter to shape various aspects such as `errors`.  Makes it possible to do: 
```ts
const form = useForm<Person>()
const firstNameHasError = !!form.errors.firstName
// or
const name = form.getValues().firstName
// both provide intellisense and type checking.  However,

const form = useFormContext()
const name = form.getValues().firstName
//works but no intellisense or type checking
 
```

Was hoping to use the `useFormContext` so that the form can work across child components.  However, I am unable to provide a type to `useFormContext`.  

Am I missing something?  Is this something that will be coming?  Is it even possible?  Should I be looking at a different pattern?  Such as passing as a prop the object that comes off of `useForm`?

**Comment by stramel** [comment]
@dfmartin We are working to improve the typings. I will see what I can do to improve this in the short-term.

**Comment by bluebill1049** [comment]
I was about to reply haha, @stramel you beat me again.

**Comment by bluebill1049** [comment]
@dfmartin I would recommend using FormContext over props pass down, it can get a bit messy. However, if it's just one level then it's probably fine. but deep nested I would recommend to use FormContext.

**Comment by stramel** [comment]
I will have an update tonight. 👍
