### ISSUE TITLE
Controller conditional render error

### ISSUE THREAD

**Issue by cpprookie** [react-hook-form/react-hook-form#2125]
**Describe the bug**
Assume that we have a `Radio` component to set type.
```javascript
type === 1 
   ? <Controller as={ComponentA} control={control} name="a"> 
   : <Controller as={ComponentB} control={control} name="b">
```
When `type` changes to 2, `ComponentA` should unmount and `componentB` should remount and receive form field `b`'s value. However ComponentB just received form field `a`'s value in fact.

**Codesandbox link (Required)**
[codesandboxlink](https://codesandbox.io/s/goofy-framework-oo6yo?file=/src/App.tsx)

**To Reproduce**
1. type text in input2
2. switch to typeA
3. text not clear

**Expected behavior**
After type switched, mounted component should receive right value from corresponding registered field.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]
 - Version [6.0.2]

**Comment by bluebill1049** [comment]
have you tried with thsi: https://react-hook-form.com/faqs#Whyisdefaultvaluenotchangingcorrectlywithternaryoperator

**Comment by cpprookie** [comment]
Hi, bill, I add `key` prop on `Controller` props and it does work. Just like this
```javascript
{compType === 1 ? (
        <Controller
          name="input1"
          control={control}
          key="controller1"
          as={<Input placeholder="This is Input 1" />}
        />
      ) : (
        <Controller
          name="input2"
          control={control}
          key="controller2"
          as={<Input placeholder="This is Input 2" />}
        />
      )}
```
Is this the expected usage use key on `Controller`? I know that different keys will cause  whole sub virtual-dom tree's re-render. And my question is not about defaultValue but changed value so i don't know if it is expected behavior.

**Comment by bluebill1049** [comment]
Hey @cpprookie, change key is not only apply to `defautValue`, take a look this article: https://kentcdodds.com/blog/understanding-reacts-key-prop

**Comment by cpprookie** [comment]
Thanks @bluebill1049 , i will take a look on source code to understand more design pricinple.
