### ISSUE TITLE
version 6 typescript errors

### ISSUE THREAD

**Issue by ronaldruzicka** [react-hook-form/react-hook-form#2129]
**Describe the bug**
I'm using a generic type for my form which I'm generating based on some data. After updating to version 6 I started to have some typescript errors. 

Funny thing is, that the same code in Codesandbox has different type errors than code in my project 🤷‍♂️.

Error from codesandbox connected to `yupResolver`:
```
Argument of type '{ resolver: any; defaultValues: T; }' is not assignable to parameter of type 'Partial<{ mode: "onSubmit" | "onBlur" | "onChange"; reValidateMode: "onSubmit" | "onBlur" | "onChange"; defaultValues: DeepPartial<T>; validationSchema: any; validationResolver: ValidationResolver<...>; validationContext: object; submitFocusError: boolean; validateCriteriaMode: "firstError" | "all"; }>'.
  Object literal may only specify known properties, and 'resolver' does not exist in type 'Partial<{ mode: "onSubmit" | "onBlur" | "onChange"; reValidateMode: "onSubmit" | "onBlur" | "onChange"; defaultValues: DeepPartial<T>; validationSchema: any; validationResolver: ValidationResolver<...>; validationContext: object; submitFocusError: boolean; validateCriteriaMode: "firstError" | "all"; }>'.ts(2345)
```

Errors from my project are connected to generic type of `defaultData` and `handleSubmit`:

```
const { register, handleSubmit, errors, control } = useForm<T>({
    resolver: yupResolver(createSchema(data)),
    defaultValues: data, // error here
});
```
<img width="635" alt="Screenshot 2020-07-09 at 11 05 44" src="https://user-images.githubusercontent.com/20684387/87020950-dc366000-c1d4-11ea-9026-98cfa4a77fbb.png">

```
const handleSubmitForm = (values: T) => {
    onSubmit(values);
};
```
<img width="1159" alt="Screenshot 2020-07-09 at 11 07 45" src="https://user-images.githubusercontent.com/20684387/87020981-e5bfc800-c1d4-11ea-85a0-f0dfe1453108.png">

**To Reproduce**
1. Go to `Form.tsx`
2. See type error on resolver

**Codesandbox link (Required)**
- [codesandbox](https://codesandbox.io/s/react-hook-form-typescript-tetr9?file=/src/Form.tsx)

**Expected behavior**
Should not have type errors
**Additional context**
```
"@hookform/resolvers": "^0.0.5",
"react-hook-form": "^6.0.2",
"yup": "^0.29.1"
"@types/yup": "^0.29.3",
```

**Comment by bluebill1049** [comment]
Thanks for the bug report, however, I don't think we support this type of usage, can you confirm @kotarella1110?

**Comment by kotarella1110** [comment]
@ronaldruzicka Not a good idea, but you can avoid this type error by extends `any`.

```ts
export const Form = function<T extends any>({ data, onSubmit }: Props<T>) {
...
```

**Comment by charlie-barjel** [comment]
I'm also having a similar issue typing my defaultValues props, using a generic form.
(I based my code on the following example: https://react-hook-form.com/ts#UseFormMethods)

```Type 'TFormValues | undefined' is not assignable to type 'UnpackNestedValue<DeepPartial<TFormValues>> | undefined'.
  Type 'TFormValues' is not assignable to type 'UnpackNestedValue<DeepPartial<TFormValues>> | undefined'.
    Type 'Record<string, any>' is not assignable to type 'UnpackNestedValue<DeepPartial<TFormValues>>'.
      Type 'TFormValues' is not assignable to type 'UnpackNestedValue<DeepPartial<TFormValues>>'.
        Type 'Record<string, any>' is not assignable to type 'UnpackNestedValue<DeepPartial<TFormValues>>'.ts(2322)
```

What is the correct way to type my `defaultValues` which I pass into my form?

```
type FormProps<TFormValues> = {
  schema: ObjectSchema<object | undefined>;
  defaultValues?: TFormValues; // What should my type be here?
  onSubmit: SubmitHandler<TFormValues>;
  children: (methods: UseFormMethods<TFormValues>) => React.ReactNode;
};
```

```
const Form = <TFormValues extends Record<string, any> = Record<string, any>>({
  schema,
  defaultValues,
  onSubmit,
  children,
}: FormProps<TFormValues>) => {
  const methods = useForm<TFormValues>({
    mode: 'onSubmit',
    resolver: yupResolver(schema),
    defaultValues, // error here
  });
  return <form onSubmit={methods.handleSubmit(onSubmit)}>{children(methods)}</form>;
};
```

**Comment by kotarella1110** [comment]
@charlie-barjel you can use `UseFormOptions` type.

```ts
type FormProps<TFormValues> = {
  schema: yup.ObjectSchema<object | undefined>;
  defaultValues?: UseFormOptions<TFormValues>["defaultValues"];
  onSubmit: SubmitHandler<TFormValues>;
  children: (methods: UseFormMethods<TFormValues>) => React.ReactNode;
};
```

[codesansbox](https://codesandbox.io/s/react-hook-form-2129-tor3p)

**Comment by connelhooley** [comment]
Thanks Kotaro, that got my out of a pickle!

Is there a reason for this change in v6? The dev experience in v5 was much better imo. Using the type `UseFormOptions<TFormValues>["defaultValues"];` is not very intuitive, and unless someone finds this github issue I doubt they would try the fix mentioned above.

**Comment by devinrhode2** [comment]
I literally google'd my type error and found this thread, so that was pretty lucky! :+1:
I have a custom type name `FormValue` which is really just `string` but could be `number | boolean` in future.
```
Type 'Record<TFieldNames, FormValue>' is not assignable to type 'UnpackNestedValue<DeepPartial<Record<TFieldNames, FormValue>>>'
```

**Comment by devinrhode2** [comment]
If anyone doesn't mind writing a nice explanation around `UnpackNestedValue<DeepPartial<` that would be great. I'd imagine passing in the generic to `useForm<MyDataStructure>({..})` should help with this, but maybe this is too idealistic
