### ISSUE TITLE
Watched fields are not updated after hot reload

### ISSUE THREAD

**Issue by erlendfh** [react-hook-form/react-hook-form#2131]
**Describe the bug**
Watched fields are not updated after hot reload.

**To Reproduce**
1. Given something along the lines of:
```
const {watch, register} = useForm();
const email = watch("email");
return (<div><input name="email" ref={register()} />
Email: {email}</div>);
```

2. `Email: {email}` is updated to whatever value is entered in the input field. 
3. Edit the code to trigger hot reload
4. `Email: {email}` is no longer updated when editing `<input>`.

I've created a [code sandbox](https://codesandbox.io/s/fragrant-glitter-g48x0?file=/src/App.js) demonstrating the issue.

**Comment by bluebill1049** [comment]
you are using a `source` folder of the package.

**Comment by erlendfh** [comment]
Wow, that was quick. My bad, I forked the code sandbox on a previous hot reload related issue. I still have this issue locally, but it seems fixing the import fixes the sandbox, so back to the drawing board I guess, sorry for the disturbance.

**Comment by bluebill1049** [comment]
nah, that's all good. may i ask which version are you using?

**Comment by erlendfh** [comment]
I'm using 6.0.2. I'm using react-hook-form together with chakra-ui, and was having some trouble with getting chakra-ui Radio controls to work properly with RHF, so I wrapped it in a `<Controller render={...} />`. This seems to be what broke hot reload:

https://codesandbox.io/s/bold-snowflake-rzrr3?file=/src/App.js

I think I've now figured out my problem with using the radio controls from Chakra directly, so I'll just remove the Controller code, but there does seem to be an issue with `<Controller />` and HMR.

**Comment by bluebill1049** [comment]
```
    <Controller
        control={control}
        name="foobar"
        defaultValue="bar"
        render={({ onChange, value }) => (
          <div>
            <div>
              <label>
                <input
                  onChange={onChange}
                  ref={register()}
                  type="radio"
                  name="foobar"
                  value="foo"
                />{" "}
                Fooø
              </label>
            </div>
            <div>
              <label>
                <input
                  onChange={onChange}
                  ref={register()}
                  type="radio"
                  name="foobar"
                  value="bar"
                />{" "}
                bar
              </label>
            </div>
          </div>
        )}
      />
```

I this usage is incorrect tithe `Controller`, `Controller` is made to control input and does the registration. I probably don't need Controller, if you can register those inputs already.

**Comment by bluebill1049** [comment]
> You're right, those refs probably shouldn't be there. The issue still remains though, after hot reload the inputs are no longer triggering watches. After hot reload, `watchFieldsRef` only contains a single reference, to the field defined under "Plain Radio Group" in the sandbox.

Please update the CSB, i will take a look tmr. 👍

**Comment by erlendfh** [comment]
Thanks, https://codesandbox.io/s/bold-snowflake-rzrr3?file=/src/App.js should now be updated. I also added a watch / setValue combo, as Controller seems to rely on setValue under the hood, but my call to setValue() doesn't seem to trigger updates of watched fields even before hot reloading?

**Comment by darron1217** [comment]
watch() is still not working after hot reload on React Native.
(I'm using Controller like below)
```html
              <Controller
                name="target"
                control={control}
                rules={{required: true}}
                render={({value, onChange}) => (
                  <SegmentedControl
                    values={['One', 'Two']}
                    selectedIndex={value}
                    onChange={(e) =>
                      onChange(e.nativeEvent.selectedSegmentIndex)
                    }
                  />
                )}
              />
```
react-hook-form version is `6.13.1`

**Comment by bluebill1049** [comment]
> watch() is still not working after hot reload on React Native.
> (I'm using Controller like below)
> 
> ```
>               <Controller
>                 name="target"
>                 control={control}
>                 rules={{required: true}}
>                 render={({value, onChange}) => (
>                   <SegmentedControl
>                     values={['One', 'Two']}
>                     selectedIndex={value}
>                     onChange={(e) =>
>                       onChange(e.nativeEvent.selectedSegmentIndex)
>                     }
>                   />
>                 )}
>               />
> ```
> 
> react-hook-form version is `6.13.1`

This issue will get resolved on the next major version, it's RFC right now.
