### ISSUE TITLE
should ref value always be latest?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [react-hook-form/react-hook-form#2136]
**Describe the bug**

Just quick question related to `isDirty`. Do we need to read `formState.isDirty` in order to get up to date `contorl.isDirtyRef` value? I thought `ref.current` always reflect the latest value.

https://codesandbox.io/s/react-hook-form-useform-template-2yu0e?file=/src/index.js

```
  const { control } = useForm();

  // always false
  console.log(control.isDirtyRef.current);
```

```
  const { control,formState:{isDirty} } = useForm();

  // expected
  console.log(control.isDirtyRef.current);
```
**To Reproduce**
1. type on form 1 input
2. type on form 2 input
3. see html output
 
**Codesandbox link (Required)**
Include a codesandox will help us to investigate the issue quicker.
https://codesandbox.io/s/react-hook-form-useform-template-2yu0e?file=/src/index.js

**Comment by bluebill1049** [comment]
we wrap formState with proxy, you will have to read the dirty flag.

**Comment by xiaoyu-tamu** [comment]
Thanks
