### ISSUE TITLE
Rerender component in production build

### ISSUE THREAD

**Issue by kle-dev** [react-hook-form/react-hook-form#2137]
**Describe the bug**
In production build with a `<Controller as={Checkbox}>` there is no way to rerender the component when value of checkbox is changed -> for example to collapse a section when value of checkbox is checked or unchecked.

**To Reproduce**
Steps to reproduce the behavior: Build this component -> there is no rerender when value of checkbox is changed

```
import React, { useRef, useEffect } from 'react';
import { Controller, useFormContext } from 'react-hook-form';

import {
  Paper,
  Grid,
  FormControlLabel,
  Checkbox,
  Collapse,
} from '@material-ui/core';

const Project = () => {
  const { control, register, getValues } = useFormContext();

  const checkbox = useRef();

  useEffect(() => {
    console.log('rerender');
  }, [
    getValues('project.completed'),
    checkbox.current?.checked,
  ]);

  return (
    <Paper>
      <Grid item container>
        <Grid item xs={12}>
            <FormControlLabel
              control={
                <Controller
                  as={<Checkbox />}
                  name='project.completed'
                  inputRef={checkbox}
                  type='checkbox'
                  control={control}
                  ref={register}
                />
              }
            />
        </Grid>

        <Collapse in={!checkbox.current?.checked}>
          <p>Collapsed Text!</p>
        </Collapse>
      </Grid>
    </Paper>
  );
};

export default Project;
```

**Codesandbox link (Required)**
No Codesandbox possible since it is only in the production build: `npm run build`

**Expected behavior**
Rerender the component when value change. At least see the value is set to true or false in console.

-> In your Dev-Tools there is also no value shown for the checkbox (in dev mode)

**Comment by bluebill1049** [comment]
which version and codesandbox?

**Comment by kle-dev** [comment]
[![Edit agitated-hamilton-j6rp3](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/agitated-hamilton-j6rp3?fontsize=14&hidenavigation=1&theme=dark)

as you can see, the value of the checkbox will printed once when the component is loaded ... 

a) the value is not shown up in your devtools
b) value change did not trigger any rerender (as you can see the value of the checkbox is only printed once in the console)
c) in Production build (If you download the project and build it) there is also another behavior.

Thank you for any kind of help.

**Comment by bluebill1049** [comment]
a) <img width="646" alt="Screen Shot 2020-07-10 at 4 43 26 pm" src="https://user-images.githubusercontent.com/10513364/87124637-7b8a4e80-c2cc-11ea-805f-8b5763719c43.png">

b) the usage is wrong

```
<Controller render={(props) => <Checkbox {...props} onChange={(e) => props(e.target.checked)} />} control={control} />
```

you don't register controller, it does it for you.

**Comment by kle-dev** [comment]
thanks for fastest help ever. In the devtools I mean the value prop with true or false, I can only see Touched and Dirty. 

![image](https://user-images.githubusercontent.com/15832711/87125285-83c19a00-c28a-11ea-9f4c-ee155cca3c01.png)

Is this expected ?

**Comment by bluebill1049** [comment]
oh the dev tool have a bug and i haven't got time to fix it... :( https://github.com/react-hook-form/devtools/issues/40

**Comment by bluebill1049** [comment]
please track the other ticket for progress. 🙏
