### ISSUE TITLE
FormProvider

### ISSUE THREAD

**Issue by Mina-Amir** [react-hook-form/react-hook-form#2138]
**Describe the bug**
While working with FormProvider and the validate option for the inputs if an input had an error from the required parameter or from the validate parameter and then i fill the form with the required data the errors don't disappear

you can check what i mean in this codesandbox

https://codesandbox.io/s/react-hook-form-v6-form-context-v1uxy?file=/src/Test.js

**Expected behavior**
when the inputs pass all validation the errors disappear

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 83.0.4103.116

**Comment by bluebill1049** [comment]
`validate: value => /^\d*$/i.test(value)` make sure you don't use g (global)

**Comment by Mina-Amir** [comment]
> `validate: value => /^\d*$/i.test(value)` make sure you don't use g (global)

as you can see in the latest version of the library this doesn't fix the issue

adding a new sandbox as the other one use an old version of the library

https://codesandbox.io/s/react-hook-form-v6-form-context-v1uxy?file=/src/Test.js

**Comment by bluebill1049** [comment]
yea, but please look at the mode you have set to
```
{
    reValidateMode: "onSubmit",
    mode: "onSubmit"
}
```

both validation only kick in onSubmit

**Comment by Mina-Amir** [comment]
i don't know how this is a problem as it wan't a problem before with FormContext

**Comment by Mina-Amir** [comment]
as a workaround i set the reValidateMode to onBlur thanks for the advice
