### ISSUE TITLE
v6: Using Textfield within material-ui/pickers isn't working anymore

### ISSUE THREAD

**Issue by kle-dev** [react-hook-form/react-hook-form#2150]
**Describe the bug**
I'm using a Textfield within DateRangePicker working fine in v. 5. 

I had a default value and it was filled out in the TextField. Also the value was passed onSubmit. In v6 there is a different behavior:

1) the default value is not showing up 
2) the value is not submitted
3) the DevTools doesn't show any value attribute also not in TextField and so on...

seems as when it is not registered.

I created two sandboxes, one with v.5 (working) and one with v6 (not working):

## v5 (working)

[![Edit silent-lake-zkev8](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/silent-lake-zkev8?fontsize=14&hidenavigation=1&theme=dark)

## v6 (not working)
[![Edit confident-feynman-h4brc](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/confident-feynman-h4brc?fontsize=14&hidenavigation=1&theme=dark)

you can also see in the sandbox that in v.5 it was possible to write:

`const { begin, end } = getValues("project.date");`

and in v6 not.

may the value is not registered ? 

---

I've got also a question: does the FormProvider not pass any registered values to child components ? 

If I write `getValues()` in child component I got only the values for the current component, I think this was different in v.5 ?
In v5 I think I wrote `getValues()` in a child component I got all values of the form I think. Is that right ?

---

**To Reproduce**
Open sandbox and see the default value in the Textfield in v6 is empty and in v5 not
Open Dev Tools and see Value property in v5 is show up, in v6 not

**Additional context**
See versions in sandbox e.g. in @ latest chrome version

**Comment by bluebill1049** [comment]
1) `getValues().project.date`
2) getVlaues should work with Provider as well.

getValues() is return nested object data by default now.
