### ISSUE TITLE
[v6] `reset` stopped working with MUI Checkbox and Switch from 6.0.2 to 6.0.3

### ISSUE THREAD

**Issue by taschetto** [react-hook-form/react-hook-form#2151]
**Describe the bug**
Reset is not working with Material-UI's Checkbox and Switch components since 6.0.3. Using RHF DevTools you can see the underlying value is changing but it is not reflecting on UI.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-controller-m3oig
2. Ensure you're using react-hook-form 6.0.3
3. Mark the checkbox and toggle the switch
4. Click on "reset form"
5. Click on submit
6. See error. Values are correctly FALSE but the UI is still TRUE.
7. Change react-hook-form to 6.0.2 and repeat the process. You'll see the problem does not occur.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-m3oig

**Expected behavior**
UI should reflect value.

**Desktop:**
 - OS: Ubunt 18.04
 - Browser: Chrome
 - Version: 83.0.4103.97 (Official Build) (64-bit)

**Comment by bluebill1049** [comment]
This fixed was introduced by a bug report when a user using `boolean` value at the controller and it starts to inject `checked` prop, when the component is not `Checkbox` or need a `check` prop. Moving forward render is the way to go when the component is not accept value, onchange and onblur.

```
<Controller
  name="Checkbox"
  control={control}
  render={props => (
    <Checkbox
      onChange={e => props.onChange(e.target.checked)}
      checked={props.value}
     />
  )}
/>
```

<img width="935" alt="Screen Shot 2020-07-11 at 9 56 19 am" src="https://user-images.githubusercontent.com/10513364/87211431-c653a700-c35c-11ea-8046-5cd49d12dd38.png">

`as` will pass down three props `value, onChange, onBlur`

**Comment by jaypalexa** [comment]
I believe I am also experiencing this with a MUI [FormControlLabel](https://material-ui.com/api/form-control-label/)+[Checkbox](https://material-ui.com/components/checkboxes/) construct...but I could use some help figuring out how to change the following code to get it to work with `render` vs `as`.  I have tried a couple of different things, but I haven't figured out the correct place for the change.  Thoughts?:

```
export const CheckboxFormField: React.FC<CheckboxFormFieldProps> = ({disabled, fieldName, labelText, validationRules, value}) => {
  const { control, errors } = useFormContext();
  return (
    <Grid item xs={12} md>
      <Controller 
        control={control}
        name={fieldName} 
        rules={validationRules}
        as={
          <FormControlLabel
            label={labelText}
            control={<Checkbox
              color='primary'
              disabled={disabled}
              id={fieldName}
              name={fieldName} 
              value={value}
            />}
          />
        }
      />
      <FormHelperText id={`${fieldName}-helper-text`}>{errors[fieldName]?.message}</FormHelperText>
    </Grid>
  );
};
```

**Comment by primozs** [comment]
I dont see this working while migrating  to   "react-hook-form": "^6.0.4",

```
     <Controller
          name="elev"
          render={({ value, onChange }) => (
            <NumberField min={0} value={value} onChange={onChange} />
          )}
          control={control}
          onChange={createHandleOnChange('elev')}
        />
```
This is not working
how do I pass my custom onChange handler to Controller and then to Field?

**Comment by ahmadkam2** [comment]
@bluebill1049 using below code fix the reset issue, but can not change its value in form `getValues()` method
`<Controller
  name="Checkbox"
  control={control}
  render={props => (
    <Checkbox
      onChange={e => props.onChange(e.target.checked)}
      checked={props.value}
     />
  )}
/>`

**Comment by bluebill1049** [comment]
> <Controller name="Checkbox" control={control} render={props => ( <Checkbox onChange={e => props.onChange(e.target.checked)} checked={props.value} /> )} />

`<Controller name="Checkbox" control={control} render={props => ( <Checkbox value="test" onChange={e => props.onChange(e.target.checked)} checked={props.value} /> )} />` try this?

**Comment by bluebill1049** [comment]
> I dont see this working while migrating to "react-hook-form": "^6.0.4",
> 
> ```
>      <Controller
>           name="elev"
>           render={({ value, onChange }) => (
>             <NumberField min={0} value={value} onChange={onChange} />
>           )}
>           control={control}
>           onChange={createHandleOnChange('elev')}
>         />
> ```
> 
> This is not working
> how do I pass my custom onChange handler to Controller and then to Field?
> 
> This onChange "callback" since v6 looks like it turns things up side down? Or I am missing something?

do you have a codesndbox? what's numberInput props like?

**Comment by bluebill1049** [comment]
> > I dont see this working while migrating to "react-hook-form": "^6.0.4",
> > ```
> >      <Controller
> >           name="elev"
> >           render={({ value, onChange }) => (
> >             <NumberField min={0} value={value} onChange={onChange} />
> >           )}
> >           control={control}
> >           onChange={createHandleOnChange('elev')}
> >         />
> > ```
> > 
> > 
> > This is not working
> > how do I pass my custom onChange handler to Controller and then to Field?
> > This onChange "callback" since v6 looks like it turns things up side down? Or I am missing something?
> 
> do you have a codesndbox? what's NumberField props like? and why there is `onChange`?

**Comment by ahmadkam2** [comment]
@bluebill1049  What is difference between `as` and `render` props in controller.
when I pass render prop, I get this error
`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
`
and when I use `as` prop for controller, my problem not solved.

**Comment by bluebill1049** [comment]
> @bluebill1049
> Im using Checkbox from Material UI library.
> when I pass `render` prop, I get this error
> `Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. `
> and when I use `as` prop for controller, my problem not solved.
> 
> this is my code:
> `<Controller name="Checkbox" control={control} as={({ onChange, value }) => ( <Checkbox value="test" onChange={e => onChange(e.target.checked)} checked={value} /> )} />`

https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r

provide a codesandbox of your issue.

**Comment by primozs** [comment]
> > > I dont see this working while migrating to "react-hook-form": "^6.0.4",
> > > ```
> > >      <Controller
> > >           name="elev"
> > >           render={({ value, onChange }) => (
> > >             <NumberField min={0} value={value} onChange={onChange} />
> > >           )}
> > >           control={control}
> > >           onChange={createHandleOnChange('elev')}
> > >         />
> > > ```
> > > 
> > > 
> > > This is not working
> > > how do I pass my custom onChange handler to Controller and then to Field?
> > > This onChange "callback" since v6 looks like it turns things up side down? Or I am missing something?
> > 
> > 
> > do you have a codesndbox? what's NumberField props like?
> 
> ```
> <Controller
>           name="elev"
>           render={({ value, onChange }) => (
>             <NumberField min={0} value={value} onChange={(value) => {
>              onChange(value)
>              createHandleOnChange('elev') 
>             } />
>           )}
>           control={control}
>         />
> ```

It does not matter what the field is doing for existing users of the lib.
It matters what the handlers are doing and how they are made. The new controller in v6 is just overwriting onChange prop and is expected to be used as a callback. Or that you use your one setValue but this is defeating the purpose of Controller. For existing users if they had one handler creator function this is not even consistent with the normal registered field.

I can agree that using render prop can be nicer for api for 
onChangeName
onBlurName
valueName
and small change for existing users. But not "onChange" that is suppose to work the same as normal registered field. 

Together with 
- onChange = {([e]) => console.log(e)};
+ onChange = {(e) => console.log(e)};

it makes is super fun breaking changes with not clear benefit for the existing users.
Cheers

**Comment by bluebill1049** [comment]
Thanks for your feedback @primozs honestly I wish I could hear those feedback much easier during the RC versions which been running for months. This is not a complaint rather a regiment regret.

Now let's talk about the change and why we made such a decision.

**Why `render` prop appears in the first:**

1. typescript type error with `as`
2. more predictable results and knowing what are the props are passing down.

**Why we didn't keep `onChange` then?** 

The question can extend why don't we keep all the other `props`. This leads to much more of a confusion, the only reason `as` has been retained because users still want the simplicity if they don't' required to wire up the props. you can have a deep read on the PR here: https://github.com/react-hook-form/react-hook-form/pull/1711 it's not a decision made in one day instead through some deep discussion in the team and also posting a poll to get users' feedback.

**Conclusion:**
nobody likes change, so I do, but we are doing this for the right purpose and to make Controller easier (at least on our part). I am sorry to make you feel frustrated about this `render` or `onChange` breaking change, hopefully, you will see the reason behind all the change.

**Comment by primozs** [comment]
I understand but:
Controller is abstraction to do some things so every field does not have to do it. Now every field must do something that that Controller concept was made to do in the first place and it's its job. "Wire up". It seams like unnecessary change of api that might change again in the future.

**Comment by bluebill1049** [comment]
> I understand but:
> Controller is abstraction to do some things so every field does not have to do it. Now every field must do something that that Controller concept was made to do in the first place and it's its job. "Wire up". It seams like unnecessary change of api that might change again in the future.

I don't think we will change anything around `render`, the only possible change will probably pass down more `props`.
