### ISSUE TITLE
reValidateMode: 'onBlur' is not working as expected

### ISSUE THREAD

**Issue by mydesweb** [react-hook-form/react-hook-form#2153]
this is my setup 

useForm({
    mode: 'onSubmit',
    reValidateMode: 'onBlur',
    defaultValues: {
      email: '',
    },

**Describe the bug**
the revalidation is triggered after every change

**To Reproduce**
1. I submit the form with no errors (all validation rules get passed)
2. I come back to previous screen (in my case) and I start to edit the email field again, at this moment the reValidation will happen after each change and not only after onBlur event

**Expected behavior**
the reValidation should happen after onBlur or onSubmit event as per my config

**Comment by bluebill1049** [comment]
can you share a codesandbox?

**Comment by mydesweb** [comment]
@bluebill1049 here is the snack [https://snack.expo.io/@mydesweb/rn-hook-form?session_id=snack-session-YTcBGYmx4&preview=true&platform=web&iframeId=e4x1580adv&theme=light](https://snack.expo.io/@mydesweb/rn-hook-form?session_id=snack-session-YTcBGYmx4&preview=true&platform=web&iframeId=e4x1580adv&theme=light)

please follow these steps:

1. enter a valid email address like alex@domain.com then press Submit
2. edit the email field by removing the ".com" part , the new value will be example@domain -> now you will see a Validation error (here is the problem 1.1) because the revalidation is happening after onChange event and not onBlur 
3. make the email valid again by adding ".com" (here is problem 1.2) because the validation error is still present (not automatically removed)

**Comment by bluebill1049** [comment]
good one! thanks for the issue report.

**Comment by bluebill1049** [comment]
strange i just tested on my own: https://codesandbox.io/s/admiring-chandrasekhar-4yeo8?file=/src/App.js
it's working.

**Comment by bluebill1049** [comment]
ok, I see, it's after successful submission.

**Comment by mydesweb** [comment]
@bluebill1049 I'm happy you manage to see the bug and prepare a fix so far. Good job!
