### ISSUE TITLE
Move for field arrays no longer works

### ISSUE THREAD

**Issue by moofoo** [react-hook-form/react-hook-form#2160]
**Describe the bug**
move() does not move items in field array in 6.0.3 release

**To Reproduce**
1. Go to [https://codesandbox.io/s/react-hook-form-usefieldarray-template-ej3mh?file=/src/index.js](url)
2. Click on 'move' button

Just from trying out different versions, It seems like move() was last working in version 6.0.1

**Comment by bluebill1049** [comment]
dame it! thanks, i will patch this now...
