### ISSUE TITLE
Form general errors

### ISSUE THREAD

**Issue by ikibalnyi** [react-hook-form/react-hook-form#2169]
**Is your feature request related to a problem? Please describe.**
We need to keep form errors that are not related to fields.

**Describe the solution you'd like**
Would be nice to have it the following way:
```typescript
import { useForm, FormError } from 'react-hook-form'

const SignupForm = () => {
  const { formErrors, handleSubmit } = useForm();

  const onSubmit = handleSubmit(async (values) => {
    try {
      const { errors, data } = await signupUser(values);
      throw errors.map((error) => new FormError(error));
    } catch (errors) {
      throw Array.isArray(errors) ? errors : new FormError(errors);
    }
  });

  return (
    <form onSubmit={onSubmit}>
      ...
      {formErrors.map((error) => (
        <div style={{ color: 'red' }}>{error.message}</div>
      ))}
    </form>
  );
};
```

**Describe alternatives you've considered**
```typescript
// can't make it symbol as `set` from utils throws error trying to work with it as with string
export const FORM_ERROR = 'FORM_ERROR';

const SignupForm = () => {
  const methods = useForm();

  // have to wrap original handleSubmit and preliminarily clear errors
  // cause otherwise it fails validation before submit
  // P.S. symbol as key would solve this as it won't appear in a result of `Object.keys()` during validation
  const handleSubmit = useCallback(
    (e) => {
      methods.clearErrors(FORM_ERROR);

      return methods.handleSubmit(async (values) => {
        try {
          const { errors } = await signupUser(values);
          if (errors) throw errors;
        } catch (error) {
          const errors = Array.isArray(error)
            ? error
            : { type: 'submit_error', message: error.message };
          methods.setError(FORM_ERROR, {
            type: 'submit_error',
            message: error.message,
          });
        }
      })(e);
    },
    [methods.handleSubmit],
  );

  return (
    <form onSubmit={handleSubmit}>
      ...
      {methods.errors[FORM_ERROR].map((error) => (
        <div style={{ color: 'red' }}>{error.message}</div>
      ))}
    </form>
  );
};
```

**Comment by bluebill1049** [comment]
i believe this is already the case in v6.
https://react-hook-form.com/api#setError

**Comment by ikibalnyi** [comment]
Maybe I didn't get the alternatives section correctly. That's how I did it in the end. The question is more of, can we make specific errors not affecting the submit or can we allow passing symbols as error names, so that I don't need to wrap `handleSubmit` additionally.

**Comment by bluebill1049** [comment]
I see, I think those sort of logic is better to leave at your app-level than the lib itself.

**Comment by ikibalnyi** [comment]
Hm, okay. Could we maybe document that it's possible to set errors that are not related to fields and that they will affect form submission?
And also, it's actually not possible from typescript prospective:
```typescript
type FormData = { username: string };

const { setError } = useForm<FormData>();

setError('FORM_ERROR'); // 'FORM_ERROR' does not exist in fields
// have to do:
setError('FORM_ERROR' as FieldName<FormData>);
```
Maybe its types could be the following, so that we could keep track of possible field names and allow setting errors that are not related to fields
```typescript
setError(name: FieldName<TFieldValues> | string, error: ErrorOption): void;
```

**Comment by bluebill1049** [comment]
> Hm, okay. Could we maybe document that it's possible to set errors that are not related to fields and that they will affect form submission?
> And also, it's actually not possible from typescript prospective:
> 
> ```ts
> type FormData = { username: string };
> 
> const { setError } = useForm<FormData>();
> 
> setError('FORM_ERROR'); // 'FORM_ERROR' does not exist in fields
> // have to do:
> setError('FORM_ERROR' as FieldName<FormData>);
> ```
> 
> Maybe its types could be the following, so that we could keep track of possible field names and allow setting errors that are not related to fields
> 
> ```ts
> setError(name: FieldName<TFieldValues> | string, error: ErrorOption): void;
> ```

Thanks, I think this is already documented. I think I should leave a note, this is not applicable for typescript unless set `any`, extends `string` basically means losing the type.
<img width="710" alt="Screen Shot 2020-07-12 at 9 35 15 pm" src="https://user-images.githubusercontent.com/10513364/87245290-9523c580-c487-11ea-8ede-d3d87cde12b1.png">

**Comment by ikibalnyi** [comment]
Ah, true, sorry, missed that part.
Maybe `UseFormMethods` could accept a second generic which would define custom errors?
```typescript 
export declare type UseFormMethods<TFieldValues extends FieldValues = FieldValues, TCustomErrors = {}> = {
    // ...
    setError(name: FieldName<TFieldValues & TCustomErrors>, error: ErrorOption): void;
    clearErrors(name?: FieldName<TFieldValues & TCustomErrors> | FieldName<TFieldValues & TCustomErrors>[]): void;
    trigger(name?: FieldName<TFieldValues & TCustomErrors> | FieldName<TFieldValues & TCustomErrors>[]): Promise<boolean>;
    errors: FieldErrors<TFieldValues & TCustomErrors>;
};
```

**Comment by bluebill1049** [comment]
> Ah, true, sorry, missed that part.
> Maybe `UseFormMethods` could accept a second generic which would define custom errors?
> 
> ```ts
> export declare type UseFormMethods<TFieldValues extends FieldValues = FieldValues, TCustomErrors = {}> = {
>     // ...
>     setError(name: FieldName<TFieldValues & TCustomErrors>, error: ErrorOption): void;
>     clearErrors(name?: FieldName<TFieldValues & TCustomErrors> | FieldName<TFieldValues & TCustomErrors>[]): void;
>     trigger(name?: FieldName<TFieldValues & TCustomErrors> | FieldName<TFieldValues & TCustomErrors>[]): Promise<boolean>;
>     errors: FieldErrors<TFieldValues & TCustomErrors>;
> };
> ```

Thanks for this awesome idea, we will discuss in the team and probably not going to introduce that anytime soon. 

FYI @kotarella1110 @stramel

**Comment by bluebill1049** [comment]
why not just type that `input` as optional?

**Comment by ikibalnyi** [comment]
Good idea, handled it the following way:
```typescript
const FORM_ERROR = 'FORM_ERROR' as const;
type FormErrors = { [FORM_ERROR]?: never };
type FormData = { username: string };

const { setError } = useForm<FormData & FormErrors>();

setError(FORM_ERROR);
```
