### ISSUE TITLE
Validation with nested fields

### ISSUE THREAD

**Issue by ikibalnyi** [react-hook-form/react-hook-form#2170]
**Describe the bug**
When you set error for nested field it overwrites error object.
```js
setError('user', { message: 'error' });
setError('user.message', { message: 'error' });
```

**To Reproduce**
Just press submit from the codesandbox example. You can take a look at the error object in console.
Also if you uncomment line 15, it will throw an error that react can't handle objects.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-v6-usewatch-9w2g3?file=/src/index.js

**Expected behavior**
To have a possibility to work with nested fields validation.

**Comment by pmaier983** [comment]
This is an odd behavior, I'll take a look into it. For the time being avoid name nesting. thank you for pointing this out!

**Comment by bluebill1049** [comment]
oh, this is a tricky one! because the `message` is used for our error object.

**Comment by bluebill1049** [comment]
<img width="260" alt="Screen Shot 2020-07-12 at 10 39 50 am" src="https://user-images.githubusercontent.com/10513364/87236373-0fbef780-c42c-11ea-9ef2-0942e4fa64ed.png">

**Comment by bluebill1049** [comment]
<img width="466" alt="Screen Shot 2020-07-12 at 11 10 07 am" src="https://user-images.githubusercontent.com/10513364/87236751-40089500-c430-11ea-89ad-1a68ba20afcf.png">

I don't think we have a fix for it, rather document this down on the doc.

**Comment by bluebill1049** [comment]
<img width="924" alt="Screen Shot 2020-07-12 at 11 19 39 am" src="https://user-images.githubusercontent.com/10513364/87236861-962a0800-c431-11ea-9438-69a8fc1cbbed.png">

updating the doc.

**Comment by pmaier983** [comment]
Id like to get some more hands on experience with the core library, so if you spot any cool bugs you can spare, assign them to me!

**Comment by bluebill1049** [comment]
> Id like to get some more hands on experience with the core library, so if you spot any cool bugs you can spare, assign them to me!

That would be great. I will make sure do that.
