### ISSUE TITLE
Controller onChange

### ISSUE THREAD

**Issue by primozs** [react-hook-form/react-hook-form#2176]
This fixed was introduced by a bug report when a user using `boolean` value at the controller and it starts to inject `checked` prop, when the component is not `Checkbox` or need a `check` prop. Moving forward render is the way to go when the component is not accept value, onchange and onblur.

```
<Controller
  name="Checkbox"
  control={control}
  render={props => (
    <Checkbox
      onChange={e => props.onChange(e.target.checked)}
      checked={props.value}
     />
  )}
/>
```

<img width="935" alt="Screen Shot 2020-07-11 at 9 56 19 am" src="https://user-images.githubusercontent.com/10513364/87211431-c653a700-c35c-11ea-8046-5cd49d12dd38.png">

`as` will pass down three props `value, onChange, onBlur`

_Originally posted by @bluebill1049 in https://github.com/react-hook-form/react-hook-form/issues/2151#issuecomment-656946808_

I dont see this working while migrating  to   "react-hook-form": "^6.0.4",

```
     <Controller
          name="elev"
          render={({ value, onChange }) => (
            <NumberField min={0} value={value} onChange={onChange} />
          )}
          control={control}
          onChange={createHandleOnChange('elev')}
        />
```
This is not working
how do I pass my custom onChange handler to Controller and then to Field?

This  onChange "callback" since v6 looks like it turns things up side down? Or I am missing something?

**Comment by primozs** [comment]
```
  const onChange = (...event: any[]) =>
    setValue(name, commonTask(event), {
      shouldValidate: shouldValidate(),
      shouldDirty: true,
    });

  const props = {
    ...rest,
    onChange,
    onBlur,
    name,
    value,
  };

  return as
    ? React.isValidElement(as)
      ? React.cloneElement(as, props)
      : React.createElement(as as string, props)
    : render
    ? render({
        onChange,
        onBlur,
        value,
      })
    : null;
```

how is this suppose to be better api. what is it fixing?

**Comment by bluebill1049** [comment]
duplicated. let's focus on the other ticket.

**Comment by glebsts** [comment]
Excuse me, @bluebill1049 I am trying to find that "other ticket" due to which this is marked as duplicated, as I am also looking into onChange-related things. Can you please link exact ticket number, mb I will find something there? Github search doesn't give too much. Thank you.

**Comment by markcorrea** [comment]
Didn't find the other ticket refered as "duplicated", and I also am facing this issue. Anyone can provide the link to the duplicated one so I can follow the solution?

**Comment by bluebill1049** [comment]
hey @glebsts sorry for the late reply, here is the link: https://github.com/react-hook-form/react-hook-form/issues/2151#issuecomment-656946808 it's difficult to predict boolean value as checked input, it caused a bug when the user not intended to use a `checked` for a boolean value, please consider using `render` instead.
