### ISSUE TITLE
FormProvider is not exported 

### ISSUE THREAD

**Issue by ahmdtalat** [react-hook-form/react-hook-form#2177]
**Describe the bug**
FormProvider not exported from react-hook-form

**To Reproduce**
1. try to import FormProvider ad `import {FormProvider} from 'react-hook-form'`
2. run your application
3. app crash
4. See the error "Attempted import error: FormProvider is not exported from 'react-hook-form'"

**Comment by bluebill1049** [comment]
which version are you using?

5 is FormContext

**Comment by ahmdtalat** [comment]
@bluebill1049 
I'm using "react-hook-form": "^6.0.2"

**Comment by bluebill1049** [comment]
do you have a codesandbox for this issue?

**Comment by bluebill1049** [comment]
<img width="556" alt="Screen Shot 2020-07-13 at 9 55 06 am" src="https://user-images.githubusercontent.com/10513364/87259481-f6cb4a80-c4ee-11ea-8a21-c379d3a73cbb.png">

i can verify we are definitely exporting it.

**Comment by ahmdtalat** [comment]
I updated to 6.0.4 and now it works, thnks

**Comment by rilwis** [comment]
I got the same error on Windows:

```bash
"export 'FormProvider' was not found in 'react-hook-form'
```

However, it works on Mac OS X.

I'm using version 6.9.3.
