### ISSUE TITLE
RHF v6.0.4 package does not include same IE11 files - update documentation?

### ISSUE THREAD

**Issue by cliffordp** [react-hook-form/react-hook-form#2178]
**Describe the bug**

**To Reproduce**
I was using `"react-hook-form": "^5.4.2"`, then discovered this was outdated so upped the version to `"react-hook-form": "^6.0.4"`, then my build erred because the existing IE11 instructions at https://react-hook-form.com/faqs#BrowserSupport aren't for v6.

However, I do see some IE11 files in my installed package:

**Should the documentation be updated to use one of these other files?**

![image](https://user-images.githubusercontent.com/1812179/87267484-74f70500-c48d-11ea-8fc0-1f88027c7bee.png)

**Comment by bluebill1049** [comment]
index.ie11 :)

**Comment by cliffordp** [comment]
thx for confirming (and quickly!)

**Comment by bluebill1049** [comment]
👍
