### ISSUE TITLE
Unable to submit when non-registered field has error - Possible regression v5->v6

### ISSUE THREAD

**Issue by henry-young** [react-hook-form/react-hook-form#2180]
**Describe the bug**
I want to use a custom field to represent a global form error state (i.e. server response not related to field). 
If I submit the form and the form validation fails I expect that submitting the form again would trigger the onSubmit handler of the form.
What actually happens:
V5 - onSubmit handler gets called.
V6 - onSubmit handler does not get called.

**To Reproduce**
1. Go to v5 link
2. Open the console
3. Leave in the default form values, and click submit
4. Notice the error "FirstName is FirstName - please change it", and "I have been called" in the console
5. Change FirstName to anything else
6. Click submit again
7. Notice that the error has been dismissed, and "I have been called" has been logged in the console
8. Go to v6 link
9. Repeat steps 2-6
10. Notice that nothing has been logged to the console

**Codesandbox link (Required)**
Include a codesandox will help us to investigate the issue quicker.

https://codesandbox.io/s/react-hook-form-useform-template-ophgz (v5 - works)
https://codesandbox.io/s/react-hook-form-useform-template-85sre (v6 - does not work)

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Mac OSX 15.5 Catalina
 - Browser: Chrome
 - Version: 85

**Additional context**
It would be nice to have a way to support global form error state instead of relying on a useState hook.

**Comment by bluebill1049** [comment]
Thanks for the issue report, this change is intentional. have a look at the setError session for updated info.

https://react-hook-form.com/api#setError

**Comment by henry-young** [comment]
Sorry, I can't see where this particular issue is referenced in the setError documentation. The area of concern I am having is firing handleSubmit rather than setError. 

Given that the functionality has changed between major versions (and if others are relying on similar error logic) it might be worth mentioning this in v5->v6 migration guide?

**Comment by bluebill1049** [comment]
- This method will not persist with the associated input error if the input passes validation. 

That's the first dot point on the website, sure happy to see a PR to include that in the migration guide as well.

**Comment by henry-young** [comment]
Shouldn't the input pass validation if it no longer exists in the form? And likewise if the input never exists (as is the case with the example above)?
`_error` isn't a registered field, but I can still call `setError('_error', ...` and display a global message in the form somewhere using the errors object. 
Previously in v5 the form would submit and clear validation errors on `_error` if I were to use this method, whereas the functionality in v6 the form won't submit. 
I'd like to know if this behaviour is intended functionality?

**Comment by bluebill1049** [comment]
have a read here: https://github.com/react-hook-form/react-hook-form/issues/1881

**Comment by henry-young** [comment]
https://github.com/react-hook-form/react-hook-form/issues/1881#issuecomment-645315907 This method is what I'm trying to achieve, however I still cannot submit the form. 

https://github.com/react-hook-form/react-hook-form/pull/1907 Shows that an error will persist if the field isn't part of the form, and requires a manual call to `clearError`. 
This to me would mean the error persists, and `handleSubmit` won't fire because there is no validation to trigger that will clear `_error`.

I have found the following workaround which triggers revalidation by registering the input as a hidden field and allows me to submit the form.
```
<input name={"_error"} type={"hidden"} ref={register} />
```

https://codesandbox.io/s/react-hook-form-useform-template-g21qp

**Comment by bluebill1049** [comment]
That's pretty smart @henry-young, why not doing a `clearError` before `handleSubmit`?

**Comment by henry-young** [comment]
I suppose I could, but it would be more fiddly doing that for every form I'd like to upgrade that already uses the `_error` pattern. Copying and pasting `<input name={"_error"} type={"hidden"} ref={register} />` seems a much easier solution.
