### ISSUE TITLE
MaterialCheckBox breaks after upgrading to 6.x

### ISSUE THREAD

**Issue by iamchathu** [react-hook-form/react-hook-form#2181]
**Describe the bug**
Boolean field seems getting string value after the upgrade to v6

**To Reproduce**
Change react-hook-form to latest and click on checkbox.
Check the codesandbox sample.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-issue-ig797?file=/src/App.tsx

**Expected behavior**
If you change back the version to v5.7 it works as expected. Does get selected and return true/false.

**Additional context**
Seems `valueName`, `onChange` props has been removed.

**Comment by bluebill1049** [comment]
Take a look the example in this codesandbox: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r  under the doc: https://react-hook-form.com/api#Controller

**Comment by alexeikaratai** [comment]
The same problems with Antd. 
![image](https://user-images.githubusercontent.com/16285931/87297023-71589200-c510-11ea-9db9-ec9aacb9f5b4.png)

**Comment by bluebill1049** [comment]
@alexeikaratai please uses the `render` prop to assign those props.  example below: 

```
<Controller
  name="Checkbox"
  control={control}
  render={props => (
    <Checkbox
      onChange={e => props.onChange(e.target.checked)}
      checked={props.value}
    />
   )}
/>
```

**Comment by alexeikaratai** [comment]
I know, but i think it is very bad solution, use 2 callback for render.

**Comment by alexeikaratai** [comment]
looks not pretty

**Comment by iamchathu** [comment]
What are the benefits of this new introduced method. Previous versions code is much cleaner.

**Comment by mxcl** [comment]
The previous version was a nightmare to maintain I imagine, this stops them having to handle a myriad of variety in the world of components which would break every few seconds.

You may not like it, but reliable software of this quality is rare and they are making the right call.

**Comment by bluebill1049** [comment]
Thanks, @mxcl for understanding. It's hard to please all external component while we are burying more underneath logic to support them, I consider that harmful in the long run, with `render` it's much more transparent on what we try to pass down to your component and yet you can still use `as` for a simple component which doesn't need the manual wire up.
