### ISSUE TITLE
Cannot find module 'react-hook-form/dist/react-hook-form.ie11'

### ISSUE THREAD

**Issue by eqtrrobertlawson** [react-hook-form/react-hook-form#2186]
Hi all, Having an issue when I am trying to import the IE11 version of the module,

`Cannot find module 'react-hook-form/dist/react-hook-form.ie11'`

This is my import statement, am I missing something? I am using webpack.
`import React, { useState } from 'react';
import { useForm } from 'react-hook-form/dist/react-hook-form.ie11';`

Many thanks!

**Comment by bluebill1049** [comment]
`index.ie11` sorry about that, updating the doc now.
