### ISSUE TITLE
Feature: Group related inputs

### ISSUE THREAD

**Issue by KevinKelbie** [react-hook-form/react-hook-form#219]
My form is of an unknown length because inputs get added when user has more things to add. I would like to be able to group these inputs so that when the `onSubmit` function is called it returns an array.

Example:

     <Form onSubmit(handleSubmit(onSubmit))>
      <List name="people"> // New component
         <ListItem> // New Component
                First Name: <input type="text" name="first"><br>
                Last Name: <input type="text" name="last"><br>
         </ListItem>
      </List>
    </form> 

Output:

    people: [
        { first: "...", last: "..." },
        ...
    ]

A work around I'm using that isn't that great is just giving each name a unique name ```name={`name-${index}`}``` then parsing and grouping them in the `onSubmit` function.

**Comment by KevinKelbie** [comment]
Never mind I found it in the docs https://react-hook-form.com/api#register

**Comment by bluebill1049** [comment]
ha all good, nice!
