### ISSUE TITLE
Material-UI Autocomplete component breaks on version 6.0.0+

### ISSUE THREAD

**Issue by SamSverko** [react-hook-form/react-hook-form#2193]
**Describe the bug**
When using Material-UI's Autocomplete component with react-hook-form and you select a value, a type error occurs.

**To Reproduce**
1. Go to Codesandbox link A.
2. In the preview window, select the input field.
3. Make a selection from the drop down menu.
4. View the error on page or in the console.

**Error**
```
TypeError
undefined has no properties
```

**Codesandbox links**
A) [Broken version (react-hook-form@6.0.4)](https://codesandbox.io/s/material-ui-autocomplete--react-hook-form--error-7c4md)
B) [Working version (react-hook-form@5.7.2)](https://codesandbox.io/s/material-ui-autocomplete--react-hook-form--working-wfkiu)

**Expected behavior**
You can see a working version by visiting Codesandbox B.
The expected behavior is when you select a value from the Autocomplete drop down menu, that value would be populated into the input field.

**Desktop:**
 - **OS:** macOS Catalina 10.15.5
 - **Browser:** Firefox 78.0.2

**Comment by xiaoyu-tamu** [comment]
Does this help?https://github.com/react-hook-form/react-hook-form/issues/2105#issuecomment-655043014

**Comment by SamSverko** [comment]
That worked! Thank you!

Just for reference, this is the code change for the Autocomplete component:
```
// BROKEN

<Controller
  as={
    <Autocomplete
      getOptionLabel={(option: string) => option}
      options={courses}
      renderInput={(params) => (
        <TextField
          {...params}
          InputLabelProps={{ shrink: true }}
          label='courses'
          variant='standard'
        />
      )}
      renderOption={(option: string) => <span>{option}</span>}
    />
  }
  control={control}
  defaultValue={[]}
  multiple
  name='courses'
  onChange={([event, value]: any) => value}
/>
```

```
// WORKING

<Controller
  control={control}
  defaultValue={[]}
  name='courses'
  onChange={([event, value]: any) => value}
  render={({ onChange, ...props }) => (
    <Autocomplete
      getOptionLabel={(option: string) => option}
      multiple
      options={courses}
      renderInput={(params) => (
        <TextField
          {...params}
          InputLabelProps={{ shrink: true }}
          label='courses'
          variant='standard'
        />
      )}
      renderOption={(option: string) => (
        <span>{option}</span>
      )}
      onChange={(event, data) => onChange(data)}
    />
  )}
/>
```
