### ISSUE TITLE
Undo/Redo

### ISSUE THREAD

**Issue by petrbela** [react-hook-form/react-hook-form#2201]
**Is your feature request related to a problem? Please describe.**

Is there a recommended way to provide undo/redo functionality? I haven't been able to find any reference.

**Describe alternatives you've considered**

A workaround could be to wrap the whole form state in something like [useUndo](https://github.com/homerchen19/use-undo).

**Describe the solution you'd like**

There's been a [similar discussion over at Formik](https://github.com/formik/formik/issues/2339) and [FormikUndo](https://github.com/OoDeLally/formik-undo) looks like a reasonably simple and effective solution. Is there a plan to add an Undo component/functionality to RHF itself or should it rather be handled by a separate plugin/library?

**Comment by bluebill1049** [comment]
this can be an external custom hook to use the `getValue` with `reset`.

**Comment by rraczae** [comment]
Would you guys leverage `watch()` to achieve this? Thanks and happy new year! 🎆

**Comment by bluebill1049** [comment]
@rraczae happy new year! it's going to be tricky as watch only subscribe to the inputs update.

**Comment by rraczae** [comment]
@bluebill1049 thanks! I ended up running an interval every second, call getValues(), compare, update history. I’ll let you know how it goes.

cheers, rob
