### ISSUE TITLE
Uncontrolled components wrapped with Controller doesn't fire validation errors

### ISSUE THREAD

**Issue by giovanicascaes** [react-hook-form/react-hook-form#2202]
**Describe the bug**
When wrapping components with `Controller` and sending props to it by `render` validation errors won't be fired.

**To Reproduce**
1. create a form with a component managed by `Controller` and rule `required`
2. submit form

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-v6-clearerrors-m1ky0?file=/src/index.jsx

**Expected behavior**
The validation errors should be fired also for components wrapped in `Controller`

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1909
 - Browser: Brave
 - Version: 1.10.97

**Comment by bluebill1049** [comment]
There are a lot of things on that codesandbox, can make it simpler for me? if it's a bug with `validation` perhaps just a controller with rules to prove it's not working.

**Comment by bluebill1049** [comment]
I search the codebase can't even find `rules`, maybe i am missing something.

**Comment by giovanicascaes** [comment]
I'm sorry, my bad. I've not provided the rules to the controller. It is working correctly. 

Sorry about that, I'm closing the issue.

**Comment by bluebill1049** [comment]
that's all good @giovanicascaes glad it's work 👍

**Comment by giovanicascaes** [comment]
I knew I was not so crazy. It seems there is really an issue with validation. Take a look at the Codesandbox again (https://codesandbox.io/s/react-hook-form-v6-clearerrors-m1ky0?file=/src/index.jsx). The issue occurs when using Yup as resolver and validating fields using `yup.when` when these fields are rendered conditionally. If always rendering the fields or validating without using `yup.when` the issue does not occur (you can test this in the sandbox, just comment the code). It is a super specific issue and I naturally understand if you don't feel it is worth to fix and, if so, you can close this issue immediately.

**Comment by bluebill1049** [comment]
no worries, I am taking a look at it now.

**Comment by bluebill1049** [comment]
haha, you are not crazy that's for sure. oh I see the question now, react hook form only focus a single field at a time for validation and perf enhancement so we don't have to trigger re-render all the time during the validation phase, if you needed to depend fields to be validated, you can use `trigger` to trigger other field's validation. let me know if this answers your question, if not let me now we can discuss and look into further.

**Comment by giovanicascaes** [comment]
Do you mean that way: https://codesandbox.io/s/react-hook-form-v6-clearerrors-tx1t0?file=/src/index.jsx
?

It works exactly as I want, but I couldn't get checkboxes working.

**Comment by bluebill1049** [comment]
What do you mean checkboxes? I couldn't see them in your CSB.

**Comment by giovanicascaes** [comment]
My bad. Check the sandbox again, please.

**Comment by bluebill1049** [comment]
<img width="1347" alt="Screen Shot 2020-07-16 at 12 51 28 pm" src="https://user-images.githubusercontent.com/10513364/87620908-123e8b80-c763-11ea-87ab-a1a862aa686f.png">

still nothing :(

**Comment by giovanicascaes** [comment]
Sorry. I guess I've been too quick reviewing the sandbox. Triple checked this time, it is working as expected. Just let me know if `onChange` is the right place to place `trigger`.

**Comment by bluebill1049** [comment]
it's correct. 👍
