### ISSUE TITLE
Controlled field breaking after React.cloneElement() 

### ISSUE THREAD

**Issue by alexcracea** [react-hook-form/react-hook-form#2203]
**Describe the bug**
Whenever passing a controlled field through a `React.cloneElement()` the onChange event is breaking the field by quickly re-rendering it multiple times with an empty value and losing focus afterwards. Basically, from a user's perspective the field is immediately cleared and blurred after a type attempt. This is due to the fact that the `register` ref is somehow interfering with the way the component is set up.

**To Reproduce**
1. [Go to my sandbox demo](https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-f7o80?file=/src/index.js) and check out the field wrapping architecture.
2. Open console
3. Attempt to input something into the "First Name" field. 
4. Observe that the field is being reset immediately after typing a character, is constantly reset and blurred
5. Observe that the console logs are hinting the component firing multiple re-renders

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-f7o80?file=/src/index.js:686-689

**Expected behavior**
Performing a React.cloneElement() upon a controlled field should still allow the correct display and behavior of the controlled fields.

**Desktop:**
 - Device: MacBook Pro (Retina, 13-inch, Mid 2014)
 - OS: MacOS Mojave 10.14.6
 - Browser: Google Chrome v83.0.4103.116 (Official Build) (64-bit)
 - Version 6.0.4

**Additional context**
I accidentally found a weird workaround for this issue by forcing an extra useless prop to the list that would be added in all cases. You can check it out by uncommenting the useless prop in the sandbox example.

In case the architecture looks weird and uncommon - this architecture from my demo sandbox is a very tiny glimpse of a big field template architecture I've got on a project and it is absolutely necessary to keep it that way for styling purposes and reusability. And generally React.cloneElement is a broadly used tool that should be supported.

**Comment by bluebill1049** [comment]
This is strange usage, maybe you should consider using `Controller` instead, see if this can resolve the problem.
