### ISSUE TITLE
watch not using the defaultValues of the useForm

### ISSUE THREAD

**Issue by juanhenriquez** [react-hook-form/react-hook-form#221]
The `watch` method is not using the `defaultValues` specified in the `useForm` when it is called.
When you start to edit some of the registered fields, just then is when the `watch` starts to show some values, but if you don't edit an input/field, in the first render of the component the` watch` won't show anything.

```javascript
function App() {
  const { register, watch } = useForm({
    defaultValues: {
      textInput: "Default Text Input Value",
      showInputNumber: false,
      numberInput: 0
    }
  });

  const watchAllFields = watch();
  const watchShowInputNumber = watch("showInputNumber");
  const watchFields = watch(["showInputNumber", "notRegisteredField"]);

  // This should output { textInput: 'Default Text Input Value', showInputNumber: false, numberInput: 0 }
  // but for some reason it is just showing an empty object
  // even when the default values were specified when the useForm was created.
  console.log("watchAllFields", watchAllFields);

  // Same here, it should output { showInputNumber: false, notRegisteredField: unefined }
  // but instead it is just returning an object with undefined values.
  console.log("watchFields", watchFields);

  return (
    <form>
      <input
        type="text"
        name="textInput"
        ref={register({ required: true, maxLength: 50 })}
      />
      <input type="checkbox" name="showInputNumber" ref={register} />

      {watchShowInputNumber && (
        <input type="number" name="numberInput" ref={register({ min: 50 })} />
      )}
    </form>
  );
}
```

Heres is a live example of the issue in codesandbox: https://codesandbox.io/s/react-hook-form-watch-5933s

**Expected behavior**
When the component is rendered for the first time, the `watch` should use the `defaultValues` specified in the `useForm`. It should not wait for a field to be edited in order to start showing the `defaultValues`.

**Comment by bluebill1049** [comment]
Thanks for the codesandbox makes my life much easier, I am looking into the issue :)

**Comment by bluebill1049** [comment]
please help on verify the fix 3.21.19-beta.1

**Comment by juanhenriquez** [comment]
Yes, it works @bluebill1049 ! Thanks for looking into this so fast  🚀

**Comment by juanhenriquez** [comment]
Hey, just one more comment (I don't know if I should do it here)! I don't know if it is intended as it is or if it is a bug, but if you go to the same codesandbox example I've shared and you click on the checkbox in order to display the other hidden input of the form, you will notice that the `watch` will not include the value of the input that has just appeared when you clicked the checkbox.

So, in the first render the `console.log("watchAllFields", watchAllFields);` outputs:
```javascript
{ textInput: "Default Text Input Value", showInputNumber: false, numberInput: 0}
```
This is okay, but then if you click the checkbox making the `showInputNumber` true and showing the hidding input, the `watch` in the second render will look like this:
```javascript
{ textInput: "Default Text Input Value", showInputNumber: true } // The numberInput now is missing
```

So maybe the `watch` in the second render should have outputted:
```javascript
{ textInput: "Default Text Input Value", showInputNumber: false, numberInput: 0}
```
As the first render did, right? I think that would be a more predictable behavior.

**Comment by bluebill1049** [comment]
That's the correct behavior, the input has been removed from the tree and hence the reference gets removed too (so does the value)

**Comment by juanhenriquez** [comment]
Yes, but I'm meant when the inputs is shown (The input is in the tree), the `watch` is not showing the value of the input. I have to focus on the input or edit it so the `watch` can know the input is there. Sorry if I didn't explained myself right 😅

**Comment by bluebill1049** [comment]
oh, I see haha 😄 I can see why this is happening too.

It's the execution order.

when you call `watch()`; the element is not yet removed from `render` so data returned.

**Comment by bluebill1049** [comment]
going to close this issue, unless you have more questions
