### ISSUE TITLE
useFieldArray: Controller is rendered with wrong value after deletion

### ISSUE THREAD

**Issue by anhquande** [react-hook-form/react-hook-form#2210]
**Describe the bug**
Environment: useFieldArray() with Controller and Material-UI. 

**To Reproduce**
1. Go to 'https://codesandbox.io/s/magical-silence-xjlvb?file=/src/index.js'
2. Click on the first Delete Button
3. See error: row 'Alex' is still visible

**Codesandbox link (Required)**
https://codesandbox.io/s/magical-silence-xjlvb?file=/src/index.js

**Expected behavior**
row 'Alex' should be invisible
row 'Barbara' and row 'Candy' should be visible

**Desktop (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10
 - Browser Chrome Version 83.0.4103.116 (Official Build) (64-bit)
 - Version: react-hook-form: 6.0.5

**Additional context**
![screenshot-183](https://user-images.githubusercontent.com/4417654/87418919-e2607e00-c5d2-11ea-9f25-a1fd7efd68d4.png)
![screenshot-184](https://user-images.githubusercontent.com/4417654/87418923-e391ab00-c5d2-11ea-8905-abea1e6af3e1.png)

**Comment by bluebill1049** [comment]
Thanks for the issue report, however, where is controller's defaultValue or defaultVlaues at useForm?

**Comment by anhquande** [comment]
hi @bluebill1049 , 
thank you for your quick reply.

i tried to add the defaultValue and it works !

however it would be great if the Controller can set the default "defaultValue"=field.value

**Comment by bluebill1049** [comment]
@anhquande they are pretty uncontrolled so you will need to provide a `defaultValue`, just like those native inputs.
