### ISSUE TITLE
React-Select onChange() event not fired in v6

### ISSUE THREAD

**Issue by mmvcode** [react-hook-form/react-hook-form#2211]
**Describe the bug**
When trying to hook to the `onChange` event of the `react-select` library, the passed `onChange` prop does not fire. The same code works in `5.7.0`, but not in `6.0.4`
**To Reproduce**
1. Create a Controller with `react-select` and add an `onChange`  prop
2. Change the value in the select. The value is changed in the select and everything works as expected when submitted, but the `onChange` prop is ignored.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-w-react-select-z7x1v?file=/src/App.tsx

**Expected behavior**
The passed `onChange` function is called

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 78.0.2
 

**Additional context**
Works in react-hook-form 5.7.2, but not in 6.0.4

**Comment by bluebill1049** [comment]
please start using `render` take a look the example in the updated CSB under V6 doc: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r

**Comment by mmvcode** [comment]
Ok, thanks. It works with `render`

**Comment by jpodpro** [comment]
please consider updating the documentation as it specifically states that using `as` will inject `onChange` into the component. this does not work for me using mui's `DatePicker` which definitely accepts onChange when used directly.

**Comment by bluebill1049** [comment]
hey @jpodpro we do inject `onChange` into the component, with standard onChange `e.target.value`, perhaps DatePicker does not return with an event object? maybe we should emphasize that in the doc.

**Comment by jpodpro** [comment]
it's a bit convoluted but i was able to get it to work with this
```
                  <Controller
                    render={props => (
                      <DatePicker 
                        {...props}
                        inputVariant="outlined"
                        size="small"
                        label={t('recordKeeping.endDate.label')}
                        className={`editor-hoverable-input`}
                        onChange={e => {
                          props.onChange(e);
                          onChange();
                        }} 
                        format="MM/dd/yyyy"
                        helperText={t('recordKeeping.endDate.fieldInfo')}
                        clearable
                      />)
                    }                   
                    control={control}
                    name="dateRetired"
                    defaultValue={detailsFields.dateRetired}
                  />
```

**Comment by bluebill1049** [comment]
```
onChange={e => {
  props.onChange(e); // this means the data return from the date picker is not a standard event, instead probably just a string.
  onChange(); // why you need this?
}} 
```

**Comment by jpodpro** [comment]
as i mentioned above, the second `onChange` is my own method that tracks when the form is dirty.

**Comment by bluebill1049** [comment]
ok @jpodpro, i just did a quick try with only `as` it's working fine: https://codesandbox.io/s/dank-surf-bx9yr?file=/src/App.jsx

**Comment by jpodpro** [comment]
i think, because i'm trying to supply my own onChange, it is getting tangled with what react-hook-form needs to do. anyway i have it working, thanks.

**Comment by sparkian15** [comment]
Hey @jpodpro how did you get this working?

@bluebill1049 I have a component within controller using render. I added controller onchange in render for e.target.value  and I also have a custom onchange to handle something else. When I try to merge them it throws an error "cannot read property of undefined". I had it working before adding it within controller.

**Comment by bluebill1049** [comment]
> Hey @jpodpro how did you get this working?
> 
> @bluebill1049 I have a component within controller using render. I added controller onchange in render for e.target.value and I also have a custom onchange to handle something else. When I try to merge them it throws an error "cannot read property of undefined". I had it working before adding it within controller.

share a simple codesadnbox?

**Comment by jpodpro** [comment]
@sparkian15 you shoudl be able to do what i'm showing above. you just need to call the hook form `onChange` with the event and then you can do whatever else you want in the handler:

```
<Controller
  render={props => (
    <DatePicker 
      value={props.value}
      onChange={e => {
        props.onChange(e);
        yourCustomCodeHere();
      }} 
    />)
  }                   
  control={control}
  name="dateRetired"
  defaultValue={detailsFields.dateRetired}
/>
```
