### ISSUE TITLE
Broken checkbox in 6.0.3 (works in 6.0.2)

### ISSUE THREAD

**Issue by michalbundyra** [react-hook-form/react-hook-form#2214]
**Describe the bug**

I am expecting boolean value for checkbox - all works fine on 6.0.2 and previous, problem occurs since 6.0.3+.

**To Reproduce**
Please see Codesandbox link below.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-rhltk?file=/src/index.js
(this is working version - 6.0.2 - please change to 6.0.3 to notice that it's not working - checkbox is not checked, and on submit we got in console string value instead of boolean state of the checkbox)

**Expected behavior**

checkbox is checked when providing "true" as default value, also submitted value is boolean, not string.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari/Chrome
 - Version latest

**Comment by bluebill1049** [comment]
please take a look at this issue for detail: https://github.com/react-hook-form/react-hook-form/issues/2151
