### ISSUE TITLE
Controller doesn't work with react-datepicker in v6

### ISSUE THREAD

**Issue by damir-sirola** [react-hook-form/react-hook-form#2216]
**Describe the bug**
Controller doesn't work with react-datepicker in v6

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-controller-lprhd
1. Click on the field with label "React Datepicker"
1. Select any date
1. The date fills the input field correctly
1. Update react-hook-form library to v6.0+
1. Click on the field with label "React Datepicker"
1. Select any date
1. The input field doesn't get filled

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-lprhd

**Expected behavior**
Input field get's filled correctly as it does with v5.7.2

**Desktop (please complete the following information):**
- Any

**Comment by bluebill1049** [comment]
can you take a look at this codesandbox: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r it's under the doc.

**Comment by xmflsct** [comment]
@bluebill1049 The `ReactDatePicker` in your link doesn't work for me.

**Comment by bluebill1049** [comment]
@xmflsct fixed

**Comment by mateuszmaczynski** [comment]
I have this same problem, what have you done to fix it ?

**Comment by bluebill1049** [comment]
use `render` props, have a look the codesandbox in the doc
