### ISSUE TITLE
`getValues` returns an empty object when `defaultValues` is defined

### ISSUE THREAD

**Issue by tombertrand** [react-hook-form/react-hook-form#222]
**Describe the bug**
As the title describes.
On the second component render, every information gets populated properly from `getValues`.

**To Reproduce**
https://codesandbox.io/s/react-hook-form-form-context-ok4x6
From the url above looking at the console shows an empty object on the initial render.

**Expected behavior**
the form values are returned on the initial render. 

To explain a bit of context, I'm initializing from a set of data and showing different fields based on that data. Unfortunately the first render doesn't fulfil the conditions due to the empty object. I could always manually pass down the data but it seemed that the `getValues` api should be providing just that.

Thanks

**Comment by bluebill1049** [comment]
thanks for the detailed issue report. i am looking into it :)

**Comment by bluebill1049** [comment]
please help on verify the fix 3.21.19-beta.1

**Comment by tombertrand** [comment]
The fix works 👍 awesome lib btw!

**Comment by bluebill1049** [comment]
Thank you 🙏🏻 I will release this patch soon

**Comment by bluebill1049** [comment]
released please close this issue when you happy :)

**Comment by ilkerceng** [comment]
Hi @bluebill1049 
I have updated given example for the latest version of react-hook-form, [here](https://codesandbox.io/s/react-hook-form-form-context-forked-o3he9?file=/src/index.js:360-415), it still gets empty object. Thanks in advance.

**Comment by sslgeorge** [comment]
This issue still exists in 6.8.2

**Comment by bluebill1049** [comment]
hi guys, getValues no longer return defaultValues, you will have to use context to store and retrieve that. return `defautltValues` cause quite a bit issue in the past builds.

**Comment by simplenotezy** [comment]
@bluebill1049 Is this still the case?

**Comment by mrmos** [comment]
yes
