### ISSUE TITLE
reset doesn't update defaultValue for downshift

### ISSUE THREAD

**Issue by IreneIrene** [react-hook-form/react-hook-form#2221]
**Describe the bug**
reset doesn't update the downshift defaultValue 

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-controller-079xx?file=/src/DonwShift.js
2. Change the downshift field value (e.g. select 'pear')
3. Click the 'RESET FORM' button
4. See the downshift field value isn't reset

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-079xx?file=/src/index.js:1051-1058

**Expected behavior**
The default value is displayed in the downshift field

**Comment by bluebill1049** [comment]
This is not a bug, will get the example updated.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r?file=/src/index.js updated.

**Comment by IreneIrene** [comment]
@bluebill1049 , thank you
