### ISSUE TITLE
Ability to modify value before putting into form in the register()

### ISSUE THREAD

**Issue by onionhammer** [react-hook-form/react-hook-form#2224]
Currently it looks (AFAICT) like you need to use a `Controller` to modify a value before it goes into the form

For example:

```js
<input name="test" type="number" ref={register} />
```

The resulting json will be

```json
{
    "test": "5"
}
```

But if you want to modify the value before it goes into the JSON form it would be nice to have a way to santize the value in the register;

```js
<input name="test" type="number" ref={register({ onChange: v => +v.replace(/,/g,'') })} />
```

so that the resulting JSON is

```
{
   "test": 5
}
```

**Comment by bluebill1049** [comment]
Thanks for your suggestion, we don't have plan to change register API argument right now and it's preserved for validation only.

**Comment by onionhammer** [comment]
@bluebill1049 suggested idiomatic way to solve this?

**Comment by bluebill1049** [comment]
use `Controller` if you need to parse the value for now.

**Comment by bluebill1049** [comment]
The reason didn't want to introduce this `onChange` because register arguments are purely made for validation, also I did have to think about support `valueAsNumber` as well before, but it introduces `null` which is not great. so I think to leave parse and format at Controller seems to be reasonable for now.

**Comment by onionhammer** [comment]
@bluebill1049 I fully understand the argument that register should be kept purely as validation. I still think there could be a way to solve this that's less verbose than Controller, but not sure what form that would take, although nothing about the word `register` screams 'validation' to me.

What was the `valueAsNumber` idea you mentioned?

**Comment by bluebill1049** [comment]
> @bluebill1049 I fully understand the argument that register should be kept purely as validation. I still think there could be a way to solve this that's less verbose than Controller, but not sure what form that would take, although nothing about the word `register` screams 'validation' to me.
> 
> What was the `valueAsNumber` idea you mentioned?

`valueAsNumber`  https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement basically doing the parsing inside the lib, however this probably only going to work for native input as well, so it has its own constraint.

**Comment by bluebill1049** [comment]
`<Controller as={<input />} control={control} onChange={} />` is not the best but it kind give you the freedom instead bury the logic inside the `register` of hook form.
