### ISSUE TITLE
Wrapping AutoComplete Material UI breaks in versions above 5.7.2

### ISSUE THREAD

**Issue by jtiagodev** [react-hook-form/react-hook-form#2227]
**Describe the bug**
AutoComplete does not return the selected value properly when using Controller

**To Reproduce**
https://codesandbox.io/s/mui-autocomplete-with-react-hook-form-kwqjs?file=/src/App.js
Try using 5.7.2 and any version abiove and test the AutoComplete input behaviour / console.log

**Codesandbox link (Required)**
https://codesandbox.io/s/mui-autocomplete-with-react-hook-form-kwqjs?file=/src/App.js

Thanks

**Comment by bluebill1049** [comment]
please use `render` instead, there is an example under the doc.https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r
