### ISSUE TITLE
clearErrors is not a function

### ISSUE THREAD

**Issue by astritspanca** [react-hook-form/react-hook-form#2233]
I am trying to clear an error using **clearErrors** but i get an error: **clearErrors is not a function.**

I am using version **6.0.5**. I copied an example from documentation to make sure that l am not missing something but the issue persisted.

**Comment by bluebill1049** [comment]
Are you sure? https://codesandbox.io/s/react-hook-form-v6-clearerrors-887rh?file=/src/index.jsx can you reproduce this in a codesandbox?

**Comment by astritspanca** [comment]
**I just deleted and re-installed node_modules and now it works perfectly.** 

Sorry for the issue. Any way i can delete this?

**Comment by bluebill1049** [comment]
aha all good mate 👍 thank you

**Comment by MoshniyVasiya** [comment]
Guys , have the same problem and deleting with re-installing modules , did't help. Even in console this function returns undefined .
Have any suggestions?

**Comment by bluebill1049** [comment]
make sure you are using v6 @MoshniyVasiya

**Comment by MoshniyVasiya** [comment]
> make sure you are using v6 @MoshniyVasiya

@bluebill1049 thx dude, it helps.

**Comment by 007surajsinghnegi** [comment]
I am having the same issue of clearError is not a function and I am using the 6.14.2 version

**Comment by bluebill1049** [comment]
> I am having the same issue of clearError is not a function and I am using the 6.14.2 version

reproduce it in a codesandbox.

**Comment by mepearso** [comment]
I had the same problem. I was using `clearError` and getting `clearError is not a function`. I replaced it with `clearErrors` and it works. 😌
