### ISSUE TITLE
After reseting date input with undefined, onChange callback doesn't get triggered after selecting previously selected value

### ISSUE THREAD

**Issue by smashercosmo** [react-hook-form/react-hook-form#2237]
**Describe the bug**
Honestly I'm not 100% sure that this is a problem with react-hook-form, but looks like it.
After you reset date input with undefined, the onChange callback doesn't get triggered when selecting previously selected value.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-useform-template-6xxfr?file=/src/index.js
2. Select any date from date input
3. There will be alert with selected value
4. Click 'reset' button
5. Try to select previously selected date
6. onChange callback won't get triggered and you won't see the alert

**Expected behavior**
onChange callback should get triggered any time you select different value

**Comment by smashercosmo** [comment]
Forgot to mention: if you reset field with 'null', everything works.

**Comment by bluebill1049** [comment]
don't reset to undefined, you should do empty `string` for input. this is not an issue with this lib.

**Comment by smashercosmo** [comment]
Alright) Interesting though, that reseting to undefined works with other input types and with select field

**Comment by bluebill1049** [comment]
try an input with `e.target.value = undefined` and you will see what i meant

**Comment by smashercosmo** [comment]
Thanks :)

**Comment by smashercosmo** [comment]
Hey, @bluebill1049 , I've just realised one thing and want to ask you about it. You were saying that one shouldn't reset field to undefined. But, isn't it the same as not providing all fields in the default values object? I mean, imagine you have a form with three fields 'a', 'b' and 'c'. If you initialise this form with ```useForm({ defaultValues: { a: 'aa', b: 'bb' } })``` it's the same as initialising this form with ```useForm({ defaultValues: { a: 'aa', b: 'bb', c: undefined } })```. Or am I missing something?

**Comment by bluebill1049** [comment]
it will be an empty string by default, just like any native input.

**Comment by smashercosmo** [comment]
mmm... in what case it will be an empty string? Will 'c' be an empty string if I initialise form with ```{ a: 'aa', b: 'bb', c: undefined }```?
