### ISSUE TITLE
Potential regression with `watch`?

### ISSUE THREAD

**Issue by ghostd** [react-hook-form/react-hook-form#2239]
Hi,

I upgraded from 6.0.1 to 6.0.6 and i get this error:
```
TypeError: Cannot convert undefined or null to object
        at Function.entries (<anonymous>)
```

My code calls `watch` on a `Controller`ed field (a react-select component with **no options**). Since there is no options, the value seems to be `null`, which is passed to the `getPath` helper function. `null` is not an array, and the code seems calling `Object.entries` with null:
https://github.com/react-hook-form/react-hook-form/blob/09e35af1354e76e209f56a0fa7a43e0d85622d0f/src/utils/getPath.ts#L6-L20

**Comment by ghostd** [comment]
I downgraded to 6.0.5 and it works. My code only breaks with the version 6.0.6.

**Comment by bluebill1049** [comment]
can you reproduce in a codesandbox?

**Comment by bluebill1049** [comment]
Think i found the root cause, please supply a codesandbox if what i am thinking it's the case.

**Comment by ghostd** [comment]
The fix works for me, thanks.

**Comment by bluebill1049** [comment]
Thanks @ghostd for the verification, will release the patch soon.
