### ISSUE TITLE
checkboxes names using dot `.` notation and numbers to be returned as an object in the onSubmit callback

### ISSUE THREAD

**Issue by tombertrand** [react-hook-form/react-hook-form#224]
**Is your feature request related to a problem? Please describe.**
I'm trying to organize the return of the `onSubmit` callback from checkbox input and facing some issue.

shown there: https://codesandbox.io/s/react-hook-form-form-context-53gv0

<input type="checkbox" name="hey.1" ref={register} checked />
<input type="checkbox" name="hey.2" ref={register} checked />
<input type="checkbox" name="hey.3" ref={register} checked />
<input type="checkbox" name="hello[1]" ref={register} checked />
<input type="checkbox" name="hello[3]" ref={register} checked />
<input type="checkbox" name="hello[4]" ref={register} checked />
<input type="checkbox" name="hi.here" ref={register} checked />
<input type="checkbox" name="hi.there" ref={register} checked />
<input type="checkbox" name="hi.somewhere" ref={register} checked />

**Describe the solution you'd like**
I was expecting the returned object to be something like this:

```javascript
{
  hey: {
    1: "on',
    2: "on',
    3: "on',
  },
  hello: [undefined, "on", undefined, "on", "on"],
  hi: { // This object is correct
    'here': 'on',
    'there': 'on',
    'somewhere': 'on',
  },
}
```

**Describe alternatives you've considered**
I can always rename the keys to a format that would allow me to reconstruct that object

**Additional context**
I'm having a group of checkboxes with non-sequencial IDs, and would like to easily recuperate which item was checked when submitting the form.

```
[{
  id: 42,
  name: 'hi',
},
{
  id: 18,
  name: 'hey',
}
,{
  id: 100,
  name: 'hello',
}]
```

Thanks

Edit: forgot to mention to look at the console for -> `console.log("onSubmit", data);`

**Comment by bluebill1049** [comment]
Kk will take a look at that. What’s the result u getting?

**Comment by tombertrand** [comment]
Perhaps those screenshots can help understanding

![image](https://user-images.githubusercontent.com/19352322/63132139-162fbf80-bf8e-11e9-8601-580c55c0a916.png)

![image](https://user-images.githubusercontent.com/19352322/63132200-45dec780-bf8e-11e9-935f-459a52cf5d4c.png)

**Comment by stramel** [comment]
@tombertrand I think the parser is getting confused by the number key. If you change the first number key to a string value `hey.'1'` it will return the object you are expecting.

```
hey: {
	'1': 'on',
	2: 'on',
	3: 'on',
}
```

although, that might not exactly work if you are looking up by a number.

**Comment by tombertrand** [comment]
@stramel your solution just worked! thanks that will be a lot less code to transform to get those IDs back 👍

**Comment by bluebill1049** [comment]
yea. I think number key is the one confused the parse. 🙏 (probably not worth for me to scratch my head around to get the parsing fixed for this use case) 😅

**Comment by tombertrand** [comment]
yep, can close for now unless more people asks for it. ATM, it doesn't give quite the expected structure using `item.'1'`but there are ways to navigate around and reconstruct an object in the `onSubmit`.

**Comment by bluebill1049** [comment]
thanks @tombertrand 🙏
