### ISSUE TITLE
remove doesnt work on useFieldArray when reset has been done on form

### ISSUE THREAD

**Issue by poeticninja** [react-hook-form/react-hook-form#2240]
**Describe the bug**
Hello! I hope you are doing well!

The form does not remove the data but the UI elements are removed when using `useFieldArray` after a `reset` has been done on the form. If I provide the data as `defaultValues` instead of the reset, when I remove an item, it works as intended.

**To Reproduce**
1. After the form has loaded, hit submit.
2. You will see that there are 3 items in the array in the console log of the form data.
3. Delete an item and hit submit again and you will see 3 items still in the array in the console.log.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-cku66?file=/src/index.js

**Expected behavior**
I expect when the UI changes, I hit remove on an element, after I hit submit it reflects what is actually on the form.

**Additional context**
Originally I thought the `reset` was just like providing `defaultValues` to the form but it seems to act completely different. `reset` actually seems to register data differently with the form than using `defaultValues`

If I need to be more clear in my context let me know. Also, for some reason append and prepend do work, just not remove. Those only work after I call register after the reset.

**Comment by bluebill1049** [comment]
This is fixed on 6.0.6: https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-uiigf

Thanks for the reporting 👍

**Comment by poeticninja** [comment]
@bluebill1049 I went to the codesandbox that you created and it didnt work. I hit submit when the page loads, look at the console, and it shows 3 items. Remove an item, hit submit again, and look at the console and it still shoes 3 items. The UI is showing 2 but the form data is still 3.

**Comment by bluebill1049** [comment]
oh wow, you are right, how the hell it was working for me back then...

**Comment by bluebill1049** [comment]
oh shit, it didn't save and it's still on 6.0.5... 

https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-uiigf?file=/src/index.js

**Comment by bluebill1049** [comment]
sorry, I found a different bug tho. submit an empty form, I will investigate this problem.

<img width="1163" alt="Screen Shot 2020-07-16 at 3 08 38 pm" src="https://user-images.githubusercontent.com/10513364/87629363-3bb4e280-c776-11ea-984d-023440dc939f.png">

**Comment by poeticninja** [comment]
Thanks! I like what you are doing! I look forward to seeing this project be successful!

**Comment by bluebill1049** [comment]
fixed: https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-uiigf?file=/src/src/useForm.ts will have a patch on this soon.
