### ISSUE TITLE
UnpackNestedValue can't handle Date type properly

### ISSUE THREAD

**Issue by cnshenj** [react-hook-form/react-hook-form#2245]
**Describe the bug**
Usually this is a `onSubmit` that works:
```typescript
interface TData { name: string; }
const { handleSubmit } = useForm<TData>();
const onSubmit = (data: TData) => {};
handleSubmit(onSubmit)();
```
Without changing anything else. Just add a property to `TData` that is of type `Date`, TypeScript will throw an error.
```typescript
interface TData { name: string; date: Date; }
```

**To Reproduce**
See the error that is marked by TS compiler in CodeSandbox link.

**Codesandbox link (Required)**
[https://codesandbox.io/s/angry-beaver-tm68w?file=/src/App.tsx](https://codesandbox.io/s/angry-beaver-tm68w?file=/src/App.tsx)

**Expected behavior**
`onSubmit` is accepted by `handleSubmit`.

**Comment by kotarella1110** [comment]
@cnshenj Thanks for your feedback! I will look into this tonight.
