### ISSUE TITLE
FormContext is not exported

### ISSUE THREAD

**Issue by avet-m** [react-hook-form/react-hook-form#2253]
**Describe the bug**
FormContext not exported from react-hook-form
"version": "6.0.6"

Example:  https://react-hook-form.com/advanced-usage/#ConnectForm

**To Reproduce
Steps to reproduce the behavior:**

try to import FormProvider ad import {FormContext} from 'react-hook-form'

**Comment by bluebill1049** [comment]
FromProvider :) i will get that update.
