### ISSUE TITLE
[useFieldArray] validation does not work properly on append/remove

### ISSUE THREAD

**Issue by anthonycaron** [react-hook-form/react-hook-form#2257]
**Describe the bug**
When using `useFieldArray` and upon removal of one or many fields, the existing errors are not being removed from the validation.

**To Reproduce**
1. Go to the sandbox link below and change the number value to -1. You will see that this field has an error.
2. Delete this input by clicking on the "DELETE" button.
3. Add a new field by clicking on the "APPEND NESTED" button.

You will see that the error is still there.
Same test can be done with several fields in error.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-gy89e?from-embed

**Expected behavior**
The form should revalidate when an item is removed from the fields array and get rid of the errors that point to non existing items.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 83.0.4103.116 (Official Build) (64-bit)

**Additional context**
Tested in v5.7.2 and v6.0.6
For more details, I also explained the issue there: https://spectrum.chat/react-hook-form/help/how-to-trigger-validation-on-append-remove~c8b29049-01f1-4abf-998c-26af08b9c133?m=MTU5NDY0NzU4MjMxNA==

**Comment by bluebill1049** [comment]
can you verify the fix: https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-jl9ey?file=/src/index.js?

**Comment by anthonycaron** [comment]
@bluebill1049 It's looking good, thanks for your reactivity !
