### ISSUE TITLE
File upload types issue after upgrade to v6

### ISSUE THREAD

**Issue by iamchathu** [react-hook-form/react-hook-form#2258]
**Describe the bug**
`material-ui-dropzone` which was working with RHF `^5.7.2` version having types issues for onSubmit method.

**To Reproduce**
1. Check the error in codesandbox.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-issue-with-dropzone-t30w5?file=/src/App.tsx

**Expected behavior**
Accept defined interface types to onSubmit method .

**Additional context**
File Upload component.

**Comment by bluebill1049** [comment]
please use `FileList` type.

**Comment by iamchathu** [comment]
I updated to FileList type in Codesandbox. But still there is the issue.

```
Argument of type '(input: FormData) => void' is not assignable to parameter of type 'SubmitHandler<FormData>'.
  Types of parameters 'input' and 'data' are incompatible.
    Type '{ image: { [x: number]: { readonly lastModified: number; readonly name: string; readonly size: number; readonly type: string; arrayBuffer: {}; slice: {}; stream: {}; text: {}; }; readonly length: number; item: {}; }; }' is not assignable to type 'FormData'.
      The types of 'image.item' are incompatible between these types.
        Type '{}' is not assignable to type '(index: number) => File | null'.
          Type '{}' provides no match for the signature '(index: number): File | null'.
```

**Comment by bluebill1049** [comment]
what about this: import * as React from 'react';
import './styles.css';

import Button from '@material-ui/core/Button';
import Grid from '@material-ui/core/Grid';
import { useForm, Controller, SubmitHandler } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers';
import * as yup from 'yup';

import { DropzoneArea } from 'material-ui-dropzone';

interface FormData {
	image: FileList;
}

const schema = yup.object().shape({
	image: yup.array().required()
});

export default function App() {
	const { control, handleSubmit, formState } = useForm<FormData>({
		resolver: yupResolver(schema),
		defaultValues: {}
	});

	const onSubmit: SubmitHandler<FormData> = (input) => {
		console.log(input);
	};

	return (
		<div className="App">
			<h1>Material Form</h1>
			<form onSubmit={handleSubmit(onSubmit)} noValidate>
				<Grid container>
					<Grid item xs>
						<Controller
							as={DropzoneArea}
							name="image"
							filesLimit={1}
							showAlerts={['error']}
							acceptedFiles={['image/*']}
							maxFileSize={5000000}
							dropzoneText={'Drag and drop an image here or click, max 5MB'}
							control={control}
						/>
					</Grid>
				</Grid>
				<Button
					type="submit"
					fullWidth
					variant="contained"
					color="primary"
					disabled={formState.isSubmitting}
				>
					Checkout
				</Button>
			</form>
		</div>
	);
}

**Comment by bluebill1049** [comment]
update my CSB try again

**Comment by iamchathu** [comment]
https://codesandbox.io/s/react-hook-form-issue-with-dropzone-t30w5?file=/src/App.tsx

I Update CSB with the fix and the upload method. Still issue is there.

**Comment by Fakkio** [comment]
Same issue here, using FileList.
```
Argument of type '(values: INewTicketFormData) => void' is not assignable to parameter of type 'SubmitHandler<INewTicketFormData>'.
  Types of parameters 'values' and 'data' are incompatible.
    Type '{ user: string; version: string; os: string; browser: string; url: string; area: string; contractor?: string | undefined; title: string; description: string; attachment: { [x: number]: { readonly lastModified: number; ... 6 more ...; text: {}; }; readonly length: number; item: {}; }; }' is not assignable to type 'INewTicketFormData'.
      Types of property 'attachment' are incompatible.
        Property '[Symbol.iterator]' is missing in type '{ [x: number]: { readonly lastModified: number; readonly name: string; readonly size: number; readonly type: string; arrayBuffer: {}; slice: {}; stream: {}; text: {}; }; readonly length: number; item: {}; }' but required in type 'FileList'.  TS2345
```

**Comment by kotarella1110** [comment]
@Fakkio you can use `NestedValue` and `SubmitHandler` type.

```ts
interface FormData {
  image: NestedValue<File[]>;
}
...
const onSubmit: SubmitHandler<FormData> = (input) => {
  uploadImage('url', input.image[0]);
  console.log(input);
};
```

[codesandbox](https://codesandbox.io/s/react-hook-form-issue-with-dropzone-b6pll)

**Comment by bluebill1049** [comment]
> @Fakkio you can use `NestedValue` and `SubmitHandler` type.
> 
> ```ts
> interface FormData {
>   image: NestedValue<File[]>;
> }
> ...
> const onSubmit: SubmitHandler<FormData> = (input) => {
>   uploadImage('url', input.image[0]);
>   console.log(input);
> };
> ```
> 
> [codesandbox](https://codesandbox.io/s/react-hook-form-issue-with-dropzone-b6pll)

Thanks @kotarella1110 .
curious why `File[]` is not working for him? it's working in my codesandbox with `SubmitHandler`.

**Comment by kotarella1110** [comment]
@bluebill1049 The value type of the native input file is `FileList`.
Currently, `FileList` is supported, but `File[]` is not.

https://github.com/react-hook-form/react-hook-form/blob/4d6da895d031243ac122ebd9622cbc7e39b0219c/src/types/form.ts#L33-L39

**Comment by bluebill1049** [comment]
Thanks @kotarella1110 , make sense 👍

**Comment by iamchathu** [comment]
Thanks @kotarella1110

**Comment by Fakkio** [comment]
> @Fakkio you can use `NestedValue` and `SubmitHandler` type.
> 
> ```ts
> interface FormData {
>   image: NestedValue<File[]>;
> }
> ...
> const onSubmit: SubmitHandler<FormData> = (input) => {
>   uploadImage('url', input.image[0]);
>   console.log(input);
> };
> ```
> 
> [codesandbox](https://codesandbox.io/s/react-hook-form-issue-with-dropzone-b6pll)

it worked (even with FileLIst), thanks @kotarella1110!
