### ISSUE TITLE
ReactNative: useWatch problem with Hermes

### ISSUE THREAD

**Issue by avet-m** [react-hook-form/react-hook-form#2261]
"react-native": "0.61.5",
"react": "^16.13.1",
"react-hook-form": "^6.0.6",

**OS**: Android 
**JavaScript engine**: [Hermes](https://reactnative.dev/docs/hermes) 

When I try to use multiple **useWatch** with param **name**  in one component, getting error
![photo_2020-07-16 15 46 17](https://user-images.githubusercontent.com/16869204/87672533-cfd57880-c77b-11ea-9672-31efd49460df.jpeg)

Unfortunately I haven't found a way set up a snack with hermes, but code looks like code below  
https://snack.expo.io/5L4sMW5uC

And also I want to mention that the error doesn't occurred  when I use **useWatch** without **name** param

**Comment by bluebill1049** [comment]
can you try 6.0.5 i think we have a patch coming for htis.

**Comment by avet-m** [comment]
@bluebill1049 yes, it works with **v6.0.5**, thank you

**Comment by bluebill1049** [comment]
cool we have a patch will release it tmr 👍
