### ISSUE TITLE
watch/useWatch/getValues issue with conditionally rendered fields

### ISSUE THREAD

**Issue by giovanicascaes** [react-hook-form/react-hook-form#2262]
**Describe the bug**
After hiding and showing conditional fields their `watch` e `getValues` values are not retrieved on render. Values are available after some specific actions, like button clicks, though. This issue occur even with `shouldUnregister` option set `false`.

**To Reproduce**
1. input some value on conditionally rendered fields (User name)
2. toggle off these fields
3. toggle them on again
4. check messages on page ("User name is on watch" and "User name is on getValues") or check logs. Messages won't be rendered and `username` prop won't show on logs

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-v6-getvalues-jvmw6?file=/src/index.jsx:1004-1119

**Expected behavior**
It is expected that `username`'s value should be restored and returned by `watch` and `getValues` on toggle on user name field

**Desktop (please complete the following information):**
OS: Windows 10 Pro 1909
Browser: Brave
Version: 1.10.97

**Additional context**
Please, let me know if I missed something and this is not a bug, so I can move to Discussions.

**Comment by bluebill1049** [comment]
@pmaier983 few notes:

1. the codesandbox is using `rc` version, make sure you toggle to the latest patch version
2. potential is a misunderstanding between `watch` and component local `state`.

thanks for picking up this issue 👍

**Comment by bluebill1049** [comment]
@giovanicascaes can you provide more detail on the expectation? I don't understand clearly on the last dot point, `watch` is not the same as the local state, so if it will be one render behind what's input's value in the render, if that's the bug then it's expected, that's why we have a second argument for the default value.

**Comment by giovanicascaes** [comment]
Hm, I think I get your point. Let me quote the docs:

> When `defaultValue` is not defined, the first render of `watch` will return `undefined` because it is called before register, but you can set the defaultValue as the second argument.

That means when I remove a registered input from render and then attach it again `watch` will "reset" itself? If so how can I handle this and restore form field value?

Even so, it is weird, because even with default values, either in `useForm`'s args or `watch`'s args (check CSB again), form value is not restored. Maybe I'm missing something here.

**Comment by bluebill1049** [comment]
> That means when I remove a registered input from render and then attach it again `watch` will "reset" itself? If so how can I handle this and restore form field value?
> 
> Even so, it is weird, because even with default values, either in `useForm`'s args or `watch`'s args (check CSB again), form value is not restored. Maybe I'm missing something here.

the simplest way just toggle the visibility of that input.

> Answering your question the expectation is returning eg. "GrandmaCOBOL" in user name's input after toggle it off/on.

that's what i am seeing here (unless i am missing steps), can you change to latest patch instead of RC version?

**Comment by giovanicascaes** [comment]
> the simplest way just toggle the visibility of that input.

Yes, this was what I ended up doing.

> that's what i am seeing here (unless i am missing steps), can you change to latest patch instead of RC version?

Changed to latest version and it works correctly.

Thank you guys for your very quick replies and awesome work. Sorry for my mistake.
