### ISSUE TITLE
How to make validation to confirm password ()

### ISSUE THREAD

**Issue by muhawebmaster** [react-hook-form/react-hook-form#227]
**How to make validation to mutch checking 2 fields ?**

Method below work, but register: required and minLength works only onBlur..

```
<input type="text" name="newPassword" ref={register({ required: true, minLength: 8})}
onChange={e => {
    const value = e.target.value
    if (value !== password) return clearError("confirmPassword")
    setError("confirmPassword", "notMatch", "passwords not mutch")
}}
```
required autoFocus/>

Without mutch checking register: required and minLength work good.

`<input type="text" name="newPassword" ref={register({ required: true, minLength: 8})} placeholder="Новый пароль" required/>
`

In ( required: validate: (value) => value === password ) program not watch const password ..

`<input type="text" name="newPassword" ref={register({ validate: (value) => value === password })} placeholder="Новый пароль" required/>`

Who maked same validation to mutch checking fields ?

**Comment by bluebill1049** [comment]
```<input type="text" name="newPassword" ref={register({ validate: (value) => {
  return value === watch('password');
})} placeholder="Новый пароль" required/>```

it's closure, you need to move watch inside the function.

**Comment by muhawebmaster** [comment]
> ```
> <input type="text" name="newPassword" ref={register({
>   validate: (value) => value === watch('password')
> })} placeholder="Новый пароль" required/>
> ```
> 
> it's closure, you need to move watch inside the function.

I made const password = watch('password') and use password .. :)  watch('password') work perfect, Thanx! ))

**Comment by bluebill1049** [comment]
Great!

**Comment by bluebill1049** [comment]
If u find this lib useful, Please kindly leave a star to support this repo ⭐️

**Comment by bluebill1049** [comment]
close the issue when you ready too :) thanks

**Comment by dmt0** [comment]
In case someone else bumps into this. Using example above the error never showed up for me, I needed to do
```
<input type="text" name="newPassword" ref={register({
  validate: (value) => value === watch('password') || "Passwords don't match."
})} placeholder="Новый пароль" required/>
```

**Comment by bluebill1049** [comment]
> In case someone else bumps into this. Using example above the error never showed up for me, I needed to add the error message output to the validate function.
> 
> ```
> <input type="text" name="newPassword" ref={register({
>   validate: (value) => value === watch('password') || "Passwords don't match."
> })} placeholder="Новый пароль" required/>
> ```

getValues()?

**Comment by dmt0** [comment]
`watch` works fine, just needed to add the part after `||`. The snippet in my message above worked for me.

**Comment by bluebill1049** [comment]
> `watch` works fine, just needed to add the part after `||`. The snippet in my message above worked for me.

nice :) watch will subscribe the input changes, getValues() is cheaper to run.

**Comment by dmt0** [comment]
Nice! Pretty awesome lib, btw, liking it a lot!

**Comment by bluebill1049** [comment]
awesome to hear @dmt0 thanks for your support ❤️

**Comment by Andrewnt219** [comment]
> 
> 
> In case someone else bumps into this. Using example above the error never showed up for me, I needed to add the error message output to the validate function.
> 
> ```
> <input type="text" name="newPassword" ref={register({
>   validate: (value) => value === watch('password') || "Passwords don't match."
> })} placeholder="Новый пароль" required/>
> ```

You're my savior

**Comment by bluebill1049** [comment]
@Andrewnt219 use getValues

**Comment by sarah27h** [comment]
@bluebill1049 Thanks for this awesome lib I have a question when using `value !== getValues('password') && <span>Password fields don't match</span>` instead of `value === getValues('password') || <span>Password fields don't match</span>` it doesn't return form data after submitting. Why is that?

```
<div className="form-row">
            <span className="required-style">* </span>
            <input
              aria-label="Enter your password"
              aria-required="true"
              placeholder="Password"
              className="form-text"
              type="password"
              name="password"
              ref={register({
                required: 'Password required',
                minLength: { value: 8, message: 'Too short' }
              })}
            />
            {errors.password && <p>{errors.password.message}</p>}
          </div>

          <div className="form-row">
            <span className="required-style">* </span>
            <input
              aria-label="Enter your password to confirm"
              aria-required="true"
              placeholder="Confirm Password"
              className="form-text"
              type="password"
              name="confirm"
              ref={register({
                validate: value =>
                  // value is from confirm and watch will return value from password
                  value === getValues('password') || <span>Password fields don't match</span>,
                required: 'Password required',
                minLength: { value: 8, message: 'Too short' }
              })}
            />

            {errors.confirm && <p>{errors.confirm.message}</p>}
          </div>
```

**Comment by bluebill1049** [comment]
> @bluebill1049 Thanks for this awesome lib. I have a question when using `value !== getValues('password') && <span>Password fields don't match</span>` instead of `value === getValues('password') || <span>Password fields don't match</span>` it doesn't return form data after submitting. Why is that?
> 
> ```
> <div className="form-row">
>             <span className="required-style">* </span>
>             <input
>               aria-label="Enter your password"
>               aria-required="true"
>               placeholder="Password"
>               className="form-text"
>               type="password"
>               name="password"
>               ref={register({
>                 required: 'Password required',
>                 minLength: { value: 8, message: 'Too short' }
>               })}
>             />
>             {errors.password && <p>{errors.password.message}</p>}
>           </div>
> 
>           <div className="form-row">
>             <span className="required-style">* </span>
>             <input
>               aria-label="Enter your password to confirm"
>               aria-required="true"
>               placeholder="Confirm Password"
>               className="form-text"
>               type="password"
>               name="confirm"
>               ref={register({
>                 validate: value =>
>                   // value is from confirm and watch will return value from password
>                   value === getValues('password') || <span>Password fields don't match</span>,
>                 required: 'Password required',
>                 minLength: { value: 8, message: 'Too short' }
>               })}
>             />
> 
>             {errors.confirm && <p>{errors.confirm.message}</p>}
>           </div>
> ```

hi there :0 what do you mean not return during submitting?

**Comment by sarah27h** [comment]
I mean it doesn't return data const onSubmit = data => {
    console.log(data);
  };

**Comment by bluebill1049** [comment]
> I mean it doesn't return data after clicking signup button
> `const onSubmit = data => { console.log(data); };`

can you reproduce that in a codesandbox? happy to take a look at it.

**Comment by sarah27h** [comment]
https://codesandbox.io/s/crazy-noyce-j62c8?file=/src/App.js

**Comment by bluebill1049** [comment]
name is unique, you should have the other field a different name.

**Comment by sarah27h** [comment]
I gave first field name="password" and second one name="confirm".

**Comment by bluebill1049** [comment]
try `value === getValues('password')` first i think you combined with JSX is the issue

**Comment by sarah27h** [comment]
Yes it works without ` && <span>Password fields don't match</span>` part. How to display a message when fields are not matched?

**Comment by bluebill1049** [comment]
do the simple if and else first.

**Comment by bluebill1049** [comment]
if (xxx) return true 
else <jsx>

**Comment by sarah27h** [comment]
OK, thanks to a lot

**Comment by bluebill1049** [comment]
> OK, thanks to a lot. It works fine.

now you can investigate why it returns false with && and JSX 👍 step at a time :)

**Comment by sarah27h** [comment]
I think for this `value !== getValues('password') && <span>Password fields don't match</span>` if they are matched it will return false and this make form not valide so data didn't return. Is this correct?

**Comment by bluebill1049** [comment]
the statement you got, never returns `true` that's the problem.

consider this example in the doc: `validate: value => value !== "admin" || "Nice try!"` (home page of the doc)

**Comment by sarah27h** [comment]
I got it, thanks so much.

**Comment by bluebill1049** [comment]
np @sarah27h happy coding 👍

**Comment by EgoPingvina** [comment]
What is `register`?
I have an error: `'register' is not defined  no-undef `

**Comment by rubenzup** [comment]
isnt working with TypeScript :

```

Type 'UseFormRegisterReturn' is not assignable to type 'Ref<HTMLInputElement> | undefined'.
  Property 'current' is missing in type 'UseFormRegisterReturn' but required in type 'RefObject<HTMLInputElement>'.
```

**Comment by crashbell** [comment]
I found that yup is simpler and compatible with TypeScript: https://til.hashrocket.com/posts/vahuw4phan-check-the-password-confirmation-with-yup

**Comment by gugudev** [comment]
You can also put in the `rules` attribute of the `Controller` component:

```js
<Controller
  name='passwordConfirmation'
  rules={{
    required: 'Please input your password confirmation.',
    validate: value => value === watch('password') || "Passwords don't match."
  }}
/>
```

**Comment by KatuGT** [comment]
@nvh95 

Thank you!, it was really useful
could you help me with one thing? 
I dont know why but it does not show the error of password input
![image](https://user-images.githubusercontent.com/38865485/155892350-283ea0bb-f955-4e7d-898f-1339d3cf01a4.png)

```
       <input
             type="password"
             autoComplete="off"
             placeholder="Contraseña*"   
            name={passwordInput.name}
             onBlur={passwordInput.onBlur}
             ref={passwordInput.ref}
            onChange={async (e) => {
              await passwordInput.onChange(e);
              if (touchedFields.confirmPassword) {
                trigger("confirmPassword");
              }
            }}
          />

          {errorsB.passwordInput && (
            <span className="mensaje-error">
              {errorsB.passwordInput.message}
            </span>
          )}
```
 here is the rest of the complete code https://github.com/KatuGT/Proyecto-Final-FrontEnd/tree/registro-login
