### ISSUE TITLE
Material-UI controlled component error with checkbox, switch with FormControlLabel

### ISSUE THREAD

**Issue by rweller59** [react-hook-form/react-hook-form#2280]
I found this codesandbox example (https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r) when trying to understand how to onChange with material-ui checkboxes/switches. When modifying it to use FormControlLabel, I get an error 'A component is changing an uncontrolled input of type checkbox to be controlled'.

**To Reproduce**
1. forked original codesandbox
2. add FormControlLabel code with Switch (at line 134)
3. click on new switch ('Logger Active')

https://codesandbox.io/s/react-hook-form-v6-controller-4upb0

error:  Material-UI: A component is changing an uncontrolled SwitchBase to be controlled.

**Comment by pmaier983** [comment]
Hello rewller59. As is specified in the docs: [`Note: You need to either set defaultValue at the field-level or call useForm with defaultValues`](https://react-hook-form.com/api#Controller). We have had several bug issues similar to yours though, so I'll have to chat with bill about the possibility of adding the note to a more prominent position within the docs, or somehow removing this requirement all-together. 

Working Fork of our CodeSandbox: 
https://codesandbox.io/s/react-hook-form-v6-controller-9f9yc

**Comment by rweller59** [comment]
sorry about that. thanks

**Comment by bluebill1049** [comment]
Thanks @pmaier983 🚀
