### ISSUE TITLE
reValidateMode not triggering correctly in v6.0.5+

### ISSUE THREAD

**Issue by yngt** [react-hook-form/react-hook-form#2284]
**Describe the bug**
reValidateMode behaving incorrectly when mode="onBlur" and reValidateMode="onChange" in v6.0.5+. The revalidation occurs onBlur rather than onChange.

**To Reproduce**
1. Visit Codesandbox link.
2. Click into text field.
3. Click out of text field.
4. See expected "required" error.
5. Click into text field and start typing.
6. Error should be cleared, but it does not clear until field blur.
7. Change react-hook-form dependency version to 6.0.4 or below and run steps 1 -5 again to see expected behavior.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-v6-controller-xdt76

**Comment by bluebill1049** [comment]
can you try the latest patch?

**Comment by yngt** [comment]
6.0.8 you mean? Yes, same issue there.

**Comment by bluebill1049** [comment]
This is correct behavior, it was a bug before. `reValidateMode` only occurred after `submit`.

<img width="925" alt="Screen Shot 2020-07-20 at 9 40 04 am" src="https://user-images.githubusercontent.com/10513364/87887980-00aff900-ca6d-11ea-8c6e-cb8858e7b765.png">

for your behavior, you want to change to `onChange` and use `touched` form state.

**Comment by ynma** [comment]
Thank you. It works using the method you suggested.

**Comment by yngt** [comment]
Thank you. It works using the method you suggested.
