### ISSUE TITLE
Focus an input

### ISSUE THREAD

**Issue by jcze91** [react-hook-form/react-hook-form#230]
Hello, 
I want to focus via a button click an input looking like this : 
<Input   ref={register({ ... )}   name='name'    />

Usually, I call something like : input.current.focus() with input as a ref passed to the input.
But with the 'register({...}' taking place of my "usual" ref I don't known how to come with.

Thank you for your help

**Comment by bluebill1049** [comment]
Hi,

I have that in the FAQ

https://react-hook-form.com/faq

go to `How to share ref usage?`

**Comment by jcze91** [comment]
Thank you !

**Comment by bluebill1049** [comment]
please support this lib by leaving a star. thanks in advance 🙏

**Comment by markplindsay** [comment]
@bluebill1049, I love this library, thank you for it (I've already starred it).

The approach in the FAQ doesn't work in TypeScript since `ref.current` is read-only. This is how I solved the problem:

```ts
import React, { useEffect, useRef } from "react"
import useForm from "react-hook-form"

function App() {
  const { register, handleSubmit } = useForm()
  const firstNameRef = useRef<HTMLInputElement>(null)
  useEffect(() => {
    if (firstNameRef.current) {
      register(firstNameRef.current)
      firstNameRef.current.focus()
    }
  }, [])
  const onSubmit = data => alert(JSON.stringify(data))
  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input name="firstName" ref={firstNameRef} />
      <input name="lastName" ref={(e) => {
        // register's first argument is ref, and second is validation rules
        register(e, { required: true })
      }} />

      <button>Submit</button>
    </form>
  );
}
```

I'm sure there is a better/cleaner way than using `useEffect`, but it works for me! I hope this helps anyone who views this issue and uses TypeScript.

**Comment by bluebill1049** [comment]
@markplindsay nice one :) and thanks very much for staring 🙏 

curious to know why it's not working under FAQ
```
<input name="firstName" ref={(e) => {
        register(e)
        firstNameRef.current = e // you can still assign to your own ref
}} />
```

`firstNameRef` is under `useRef`.

let me know if that's not correct, i can always correct them :)

**Comment by markplindsay** [comment]
It's a TypeScript error that appears in the `firstNameRef.current = e` line, with `current` highlighted:

```
2540: Cannot assign to 'current' because it is a read-only property.
```

This is what it looks like in vim (my code):

![Screen Shot 2019-09-03 at 5 24 18 PM](https://user-images.githubusercontent.com/1211543/64177103-d282f400-ce6f-11e9-86c5-4d6e9d3439c3.png)

`ref` is a [`RefObject` interface](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1c92cef26e1a054b8367f56dd8d7c7f033804f49/types/react/index.d.ts#L79-L81). Its `current` property is `readonly`, so TypeScript won't let you assign anything to it.

**Comment by bluebill1049** [comment]
That’s really strange. That’s react API with ‘useRef’. You meant to assign value to it. https://reactjs.org/docs/hooks-reference.html#useref I will double check on this. Thanks will let u know 🤙🏻👌🏻

**Comment by bluebill1049** [comment]
```
import React, { useRef } from "react"
import useForm from "react-hook-form"

function App() {
  const { register, handleSubmit } = useForm()
  const firstNameRef = useRef<HTMLInputElement>()
  const onSubmit = data => alert(JSON.stringify(data))

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input name="firstName" ref={(e: HTMLInputElement) => {
        register(e)
        firstNameRef.current = e // you can still assign to your own ref
      }} />
      <input name="lastName" ref={(e) => {
        // register's first argument is ref, and second is validation rules
        register(e, { required: true })
      }} />

      <button>Submit</button>
    </form>
  );
}
```

@markplindsay this is the working version for Typescript :)

**Comment by sabahang** [comment]
Hi, I'm still getting this error with typescript: `Cannot assign to 'current' because it is a read-only property`

**Comment by cybervaldez** [comment]
FAQ page is returning a 404

**Comment by bluebill1049** [comment]
@cybervaldez https://react-hook-form.com/faqs

**Comment by seonghyeonkimm** [comment]
I have one more question. How can I use ref when using `Controller`?

**Comment by bluebill1049** [comment]
It’s a question for your controlled component . You can still use it’s ref even with controller

**Comment by dandv** [comment]
> @cybervaldez https://react-hook-form.com/faqs

Would help to update [the original comment](https://github.com/react-hook-form/react-hook-form/issues/230#issuecomment-522764265) linking to the FAQ, because I clicked on that one too :)

**Comment by liederivative** [comment]
In order to work with typescript you just need to include null ( useRef<HTMLInputElement | null> ) so the type will be mutable. 
Here's the deeper [explanation](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31065#issuecomment-446425911)

**Comment by jrbytes** [comment]
I have problem the implementation in my useEffect.
I implemented my input like this:
```javascript
<input
  type="text"
  name="name"
  value={name || ''}
  onChange={e => handleName(e.target.value)}
  ref={e => {
    register(e, {
      required: {
        value: true,
        message: 'É necessário renomear o projeto para atualizar',
      },
      max: 240,
      min: 1,
      maxLength: 240,
      pattern: {
        value: name,
      },
    })
    nameRef.current = e
  }}
  id={errors.name && errors.name.message ? 'form-error' : ''}
/>
{errors.name && <span>{errors.name.message}</span>}
```
And my useEffect with register(). But, i not have success. So, i implemented without.
```javascript
useEffect(() => {
    if (openModal) {
      setTimeout(() => {
        nameRef.current.focus()
      }, 100)
    }
  }, [openModal])
```
How you see, i implemented with state openModal for to identify when open. *But, i would to know why need of setTimeout*.

**Comment by hann-wego** [comment]
How do I access the ref if I use the Controller component?

**Comment by mordechaim** [comment]
You can always call `control.fieldRefs.current.myField.focus()`

**Comment by bluebill1049** [comment]
> You can always call `control.fieldsRef.current.myField.ref.focus()`

be careful on usage with control object, we may change data structure internally.

**Comment by mordechaim** [comment]
> be careful on usage with control object, we may change data structure internally.

Is there any other reliable way to get the ref pool?

**Comment by bluebill1049** [comment]
> > be careful on usage with control object, we may change data structure internally.
> 
> Is there any other reliable way to get the ref pool?

if you want to hold all `ref` for your input, I think it's better to do that at your app level.

**Comment by mordechaim** [comment]
I kinda feel it's a nice feature to have it accessible. 

Thanks for this great project anyway

**Comment by bluebill1049** [comment]
> I kinda feel it's a nice feature to have it accessible.
> 
> Thanks for this great project anyway

no worries, but we not changing the structure anytime soon, maybe in v7, just be mindful with it.

**Comment by tjolr** [comment]
Im trying to solve this exact problem in v7 with Typescript, but when following the guide here on "How to share ref usage?" i get the following errors: 


![image](https://user-images.githubusercontent.com/30324054/113938127-7544e680-97fa-11eb-8727-1dc409332812.png)

![image](https://user-images.githubusercontent.com/30324054/113937775-f64fae00-97f9-11eb-9b88-e3b2ba51d7d3.png)

useForm, useRef and register:
![image](https://user-images.githubusercontent.com/30324054/113938292-ade4c000-97fa-11eb-98f3-3ed1641f7db5.png)


Can you update the FAQ code to v7 with TS @bluebill1049?

**Comment by bluebill1049** [comment]
> Im trying to solve this exact problem in v7 with Typescript, but when following the guide on the FAQ "How to share ref usage?" i get the following errors:
> 
> ![image](https://user-images.githubusercontent.com/30324054/113938127-7544e680-97fa-11eb-8727-1dc409332812.png)
> 
> ![image](https://user-images.githubusercontent.com/30324054/113937775-f64fae00-97f9-11eb-9b88-e3b2ba51d7d3.png)
> 
> useForm, useRef and register:
> ![image](https://user-images.githubusercontent.com/30324054/113938292-ade4c000-97fa-11eb-98f3-3ed1641f7db5.png)
> 
> Can you update the FAQ code to v7 with TS @bluebill1049?
> 
> I really enjoy this library though 🤩

yea, sure can you raise an issue at the documenation? I will follow it up.

**Comment by LeonAvancini** [comment]
> ```
> import React, { useRef } from "react"
> import useForm from "react-hook-form"
> 
> function App() {
>   const { register, handleSubmit } = useForm()
>   const firstNameRef = useRef<HTMLInputElement>()
>   const onSubmit = data => alert(JSON.stringify(data))
> 
>   return (
>     <form onSubmit={handleSubmit(onSubmit)}>
>       <input name="firstName" ref={(e: HTMLInputElement) => {
>         register(e)
>         firstNameRef.current = e // you can still assign to your own ref
>       }} />
>       <input name="lastName" ref={(e) => {
>         // register's first argument is ref, and second is validation rules
>         register(e, { required: true })
>       }} />
> 
>       <button>Submit</button>
>     </form>
>   );
> }
> ```
> 
> @markplindsay this is the working version for Typescript :)

It's difficult to show this message when input are null? 
this worked before set ref value (bottom input is working perfectly, but this dont has a ref value).

![image](https://user-images.githubusercontent.com/50600921/117311576-af85c000-ae5a-11eb-9ddc-422c1744f429.png)

**Comment by piedpiper10** [comment]
I tried [https://www.react-hook-form.com/faq](https://www.react-hook-form.com/faq) for ref sharing I'm getting type error for this step  const { ref, ...rest } = register('firstName');
