### ISSUE TITLE
Invalid CHANGELOG.md

### ISSUE THREAD

**Issue by michalbundyra** [react-hook-form/react-hook-form#2301]
FIle https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md

contains release 6.0.3 twice with different dates:

```
[6.0.3] - 2020-07-17
...
[6.0.3] - 2020-07-10
...
```

Also, there is no any release notes for 6.0.4+ in that file. Not sure what is the purpose of that file as it is not updated, and all changes are noted with releases on github.

**Comment by bluebill1049** [comment]
There are not change, add, or remove those patch versions. that's why I didn't include them in the changelog.

**Comment by bluebill1049** [comment]
I will fix the version issue.
