### ISSUE TITLE
Watch and detach issues when using with react-frame-component

### ISSUE THREAD

**Issue by bilune** [react-hook-form/react-hook-form#2306]
Hi everyone!

**Describe the bug**
I'm having some issues when trying to use the library with [react-frame-component](https://github.com/ryanseddon/react-frame-component):

1. Watch/useWatch are not triggering rerender.

**To Reproduce**
Steps to reproduce first issue:
1. Toggle the first checkbox input (in the regular form it hides the second input, but in the iframe it doesn't work).

**Codesandbox link (Required)**
https://codesandbox.io/s/brave-wilson-kzkcd

**Expected behavior**
- watch and useWatch should trigger a rerender in the iframe.
- fields should be correctly detached when the input is removed from DOM.

**Screenshots**
![Kapture 2020-07-21 at 12 41 25](https://user-images.githubusercontent.com/47793253/88075748-9a4fd700-cb4f-11ea-8d41-5c69358e2c1a.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 83.0.4103.116

**Additional context**
I tried a solution on my local and I've already faced a similar issue which is that in some parts of the app there are comparisons of the type:
```js
element instanceof HTMLElement
```

returning true in a regular case, but false when is rendered inside the Iframe because 
```js
const iframe = document.getElementById('myframe')
window.HTMLElement === iframe.contentWindow.HTMLElement // returns false
```

Is there any plan to face this kind of issues?
Of course I can help making those changes but just wanted to know if is in the roadmap and you are planning to consider these kind of scenarios.

Thanks!

**Comment by bluebill1049** [comment]
hey @bilune, thanks for the issue report. I don't think we going to try to fix the issue with iFrame related for now. you can send a feature request and we will tag `waiting for an upvote`, if users have similar needs, however, I don't think this will be a trivial task. 

Temp solution for now:

1. try to use `Controller` to wrap your inputs.
2. or custom `register` at useEffect and update value with `setValue `
