### ISSUE TITLE
Provide and example with Ant forms

### ISSUE THREAD

**Issue by hrahimi270** [react-hook-form/react-hook-form#2307]
**Is your feature request related to a problem? Please describe.**
It's hard to integrate react-hook-form with Ant form. I think if there will be an example of how to accomplish, makes it easier.

**Describe the solution you'd like**
A simple example of a form with Ant Form components.
Also, maybe it's better to have an example with dynamic forms for API based forms (:

**Comment by bluebill1049** [comment]
can you provide some of the base components that you would like to see examples?

**Comment by hrahimi270** [comment]
I think [this example](https://ant.design/components/form/#components-form-demo-size) of Form contains most of the components.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r?file=/src/index.js 
updated, it's the one in the doc as well.

**Comment by hrahimi270** [comment]
My actual problem is, I don't know how to set the default value for controlled fields.
I've used the `defaultValues` prop in `useForm` hook. And passed the names equals to `defaultValues` object.
But, the initial form fields are empty.

**Comment by bluebill1049** [comment]
Take a look again and i have updated with all default values for the inputs, please spend sometimes with the doc with `Controller`, there are valuable information there and pretty sure show you how to set `defaultValues` with Controller.

<img width="1226" alt="Screen Shot 2020-07-22 at 7 07 02 pm" src="https://user-images.githubusercontent.com/10513364/88157775-88089280-cc4e-11ea-883e-2e6bd59081b9.png">
