### ISSUE TITLE
Setting default value

### ISSUE THREAD

**Issue by mrgazanfarli** [react-hook-form/react-hook-form#2308]
**Describe the bug**
When taking the form methods by using `useForm<Type>({ defaultValues: values })` , I cannot get values by using `getValues()`

**To Reproduce**
1. Get form methods from `useForm<Type>({ defaultValues: values })`
2. Use `<FormProvider {...formMethods}>{children}</FormProvider>` 
3. Get values from `useFormContext` inside a nested component
4. And the values will be `{}`

**Codesandbox link (Required)**
https://codesandbox.io/s/brave-wescoff-s8i8k

**Expected behavior**
`getValues()` method had to return default values as I had provided them

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome v84.0.4147.89

**Comment by nigarjafarr** [comment]
+
I am facing same issue while using last version react-hook-form

**Comment by bluebill1049** [comment]
hey guys, this is not a bug, but when you are using getValue during the render, its meant to retrieve inputs values?

**Comment by gilbarbara** [comment]
Hey,

I was using getValues with my Input component but apparently it's not working with 6.x.
Did it change? I couldn't find anything about this in the CHANGELOG.

**Comment by bluebill1049** [comment]
hey @gilbarbara can you sure a codesandbox?

**Comment by mrgazanfarli** [comment]
> hey guys, this is probably not a bug, but when you are using getValue during the render, its meant to retrieve inputs values?

yes, I just want to take values (at least default ones), but the method does not return them. It was OK with the 5.x versions. After upgrading the library, I observe this problem very often

**Comment by bluebill1049** [comment]
can you share your usage @mrgazanfarli?

**Comment by mrgazanfarli** [comment]
@bluebill1049 my usage scenario is the same as I wrote on codesandbox

**Comment by mrgazanfarli** [comment]
I use `useForm` and provide `defaultValues`, but I cannot get them. This is the simplest way of describing the problem :)

**Comment by bluebill1049** [comment]
looks like everyone is expected getValues to return defaultValues, we will sort it out then.

**Comment by mrgazanfarli** [comment]
> looks like everyone is expected getValues to return defaultValues, we will sort it out then.

If I use useForm and have no changes, then getValues should return the default values

**Comment by bluebill1049** [comment]
would you be able to take care of this one @keiya01?

**Comment by keiya01** [comment]
@bluebill1049 I can do it. I will check this issue.

**Comment by bluebill1049** [comment]
awesome! thanks heaps @keiya01 🙏

**Comment by bluebill1049** [comment]
@keiya01 if we can make `getFieldsValues` function return `defaultValues` as well will resolve this bug too: https://github.com/react-hook-form/react-hook-form/issues/2339

**Comment by bluebill1049** [comment]
I was thinking merge `defaultValues` with `unmountFieldsStateRef`.

**Comment by keiya01** [comment]
@bluebill1049 
I think so too. I will fix this issue tonight.

**Comment by bluebill1049** [comment]
> @bluebill1049
> I think so too. I will fix this issue tonight.

no rush at all, do whenever you are free. thanks, @keiya01 🌿

**Comment by bluebill1049** [comment]
will be published in the next patch.

**Comment by bluebill1049** [comment]
hey guys, just an FYI: `getValues` return `defaultVlaues` is actually causing quite a bit issue, we are considering to revert back that behavior. You will most likely have to manage the `defaultValues` yourself.

**Comment by mrgazanfarli** [comment]
@bluebill1049 one more question then. If I set defaultValues with `useForm` and then call getValues(), will I get the values I set as `defaultValues` ?

**Comment by bluebill1049** [comment]
nope, @mrgazanfarli sorry we revert back this change, this cause issue when all inputs get unregistered. it's better to manage that defautlValues in the app level by context or pass down props.

**Comment by bluebill1049** [comment]
`getValues` will strictly return what's in the form and those inputs get registered.

**Comment by mrgazanfarli** [comment]
@bluebill1049 got it. Thanks

**Comment by benswinburne** [comment]
In case it is useful, I've been getting around this by merging in the defaults with the current value by accessing the ref via control. It's not necessarily conventional but it works.

```
const formDefaults = form.control.defaultValuesRef.current;
const fieldValues = getValues(); // this includes defaultValue props on fields

const values = {
  ...formDefaults,
  ...fieldValues,
};
```

Obviously I'm just merging single depths here as I don't use any dot notation but you could just as easily use `values = deepmerge(...)` for example.

**Comment by bluebill1049** [comment]
Thanks for understanding guys. Trust me the decision that we made is to make the lib more predictable.

**Comment by luciorubeens** [comment]
Seems that `watch` is working as expected for `defaultValues`, so if you want to run it once:

```js
const [defaultValues] = React.useState(() => watch());
const values = getValues();
```

**Comment by joejordan** [comment]
Just wanted to comment that I've spent several hours trying to figure out why getValues() wasn't returning my form's defaultValues after they were set via an API call. Much like the original poster, I am using useContext to pass the entire result of useForm around to my sub-components. I thought maybe I had gone crazy and completely forgotten how to pass context around.

If this is the expected behavior from here on out, I would suggest updating the documentation for additional clarity, as this IMO diverts from the intuitive expectation that getValues() would return the values set via defaultValues() rather than null values when the form is untouched.

**Comment by bluebill1049** [comment]
> Just wanted to comment that I've spent several hours trying to figure out why getValues() wasn't returning my form's defaultValues after they were set via an API call. Much like the original poster, I am using useContext to pass the entire result of useForm around to my sub-components. I thought maybe I had gone crazy and completely forgotten how to pass context around.
> 
> If this is the expected behavior from here on out, I would suggest updating the documentation for additional clarity, as this IMO diverts from the intuitive expectation that getValues() would return the values set via defaultValues() rather than null values when the form is untouched.

sorry to hear that, any chance could you please send a PR to improve the doc?

**Comment by krisdover** [comment]
Like others have mentioned, not being able to use `getValues()` retrieve defaults on the initial render (before the form fields are registered) really caught me out. IMO getting access to default values on the initial render is critical behaviour for restoring any form which has a dynamic field layout based on inputted field values. I'm currently using the `control.defaultValuesRef.current` hack as a work-around but it feels so wrong accessing an undocumented internal API. I would use `watch` but I don't like that it causes a re-render on every field change. Maybe `control.defaultValuesRef` should be documented :)

**Comment by bluebill1049** [comment]
> Like others have mentioned, not being able to use `getValues()` retrieve defaults on the initial render (before the form fields are registered) really caught me out. IMO getting access to default values on the initial render is critical behaviour for restoring any form which has a dynamic field layout based on inputted field values. I'm currently using the `control.defaultValuesRef.current` hack as a work-around but it feels so wrong accessing an undocumented internal API. I would use `watch` but I don't like that it causes a re-render on every field change. Maybe `control.defaultValuesRef` should be included as part of the public API and documented :)

Thanks @krisdover I did make getValues to return default values, which creates quite a few expected issues. what about this option:

```
const defaultValues = {};

useForm({
  defaultValues.
})

// you can even store that object in the form context, so you can access it anywhere

```

**Comment by krisdover** [comment]
@bluebill1049 Yep, that's another option I guess 👍 
Btw. thanks for all the hard work on library. It's awesome. 🎉

**Comment by bluebill1049** [comment]
np @krisdover 🙏

**Comment by hollg** [comment]
@bluebill1049 

> // you can even store that object in the form context, so you can access it anywhere

I get a TypeScript error when trying to do this, because `defaultValues` doesn't exist on the `UseFormMethods` type. Is there some other way to add default values to the `FormProvider` that I'm not seeing? My code looks like this:

```ts
const defaultValues = {};

const formMethods = useForm({
  defaultValues.
})

return <FormProvider {...formMethods} defaultValues={defaultValues} > {/* ... */} </FormProvider>
```

Many thanks for the great library!

**Comment by bluebill1049** [comment]
> @bluebill1049 
> 
> > // you can even store that object in the form context, so you can access it anywhere
> 
> I get a TypeScript error when trying to do this, because `defaultValues` doesn't exist on the `UseFormMethods` type. Is there some other way to add default values to the `FormProvider` that I'm not seeing? My code looks like this:
> 
> ```ts
> const defaultValues = {};
> 
> const formMethods = useForm({
>   defaultValues.
> })
> 
> return <FormProvider {...formMethods} defaultValues={defaultValues} > {/* ... */} </FormProvider>
> ```
> 
> Many thanks for the great library!

Can u share a codesandbox?

**Comment by hollg** [comment]
@bluebill1049 absolutely: https://codesandbox.io/s/react-hook-form-defaults-bfokk

The TypeScript error is at line 19

**Comment by bluebill1049** [comment]
@hollg you are missing your generic at `useForm`.  https://react-hook-form.com/get-started#TypeScript

**Comment by hollg** [comment]
@bluebill1049 Ah yes you're right, but I've updated the codesandbox to include it and it doesn't fix the error: https://codesandbox.io/s/react-hook-form-defaults-bfokk

**Comment by bluebill1049** [comment]
spend some time in the doc, it will help :)

```tsx
import "./styles.css";
import { useForm, FormProvider, useFormContext } from "react-hook-form";

function NameInput() {
  return (
    <div>
      <label>Name</label>
      <input />
    </div>
  );
}

export default function App() {
  const defaultValues = { name: "Gary" };
  const formMethods = useForm<{ name: string }>({ defaultValues });

  return (
    <div className="App">
      <FormProvider {...formMethods}>
        <NameInput />
      </FormProvider>
    </div>
  );
}
```

**Comment by hollg** [comment]
@bluebill1049 Sorry, I think there might have been a miscommunication here. 

In your message that I originally quoted, you said: 
> you can even store that object in the form context, so you can access it anywhere

But doing that causes a TypeScript error, irrespective of whether I pass a generic type to `useForm`. You can see this in the updated codesandbox: https://codesandbox.io/s/react-hook-form-defaults-bfokk?file=/src/App.tsx 

Is there a working TypeScript example of default values being passed to `<FormProvider>`? Or is there another way to store the default values object in the form context? I couldn't find anything like that in the docs. Apologies if I missed something!
