### ISSUE TITLE
Enhancement request: `formState.dirty`

### ISSUE THREAD

**Issue by tombertrand** [react-hook-form/react-hook-form#231]
**Is your feature request related to a problem? Please describe.**
All of our forms will be listening to the `formState.dirty` value to show a disabled/enabled save button. The issue I'm currently having is for example I focus an input and blur, the form will be set to `dirty` while the value haven't changed. The same behaviour happens if my default value was "hi" then I set it to "hey" and changed back that value to "hi".

**Describe the solution you'd like**
I'd like that the `formState.dirty` property correspond to a check of `defaultValues` VS current values. If the object doesn't match then the property is set to `true`. That would allow the users to know if they need to save the form because they have changed something while focusing and blurring an input, nothing have changed.

**Describe alternatives you've considered**
Is this something I would need to implement on my side or would that be a useful feature enhancement to have on the library?

Thanks

**Comment by bluebill1049** [comment]
I will take a look at this.

**Comment by bluebill1049** [comment]
not finalized just yet, but would like to test out the beta: `3.22.1-beta.1`

I am still testing and writing more tests. let me know if you find issues, that would help me deliver this feature quicker :)

**Comment by tombertrand** [comment]
🦅On it!

**Comment by tombertrand** [comment]
perhaps an error on my part, but after updating to the latest version I'm getting new TS errors, do I have to define a data schema? 🤔 

![image](https://user-images.githubusercontent.com/19352322/63349458-75dcf080-c329-11e9-824b-177853773bfd.png)

**Comment by tombertrand** [comment]
Tested with input, select & checkboxes, works as expected 🎉

**Comment by tombertrand** [comment]
oh, perhaps we have forgot to reset dirty to` false` after the form is submitted?

**Comment by bluebill1049** [comment]
@tombertrand will do! thanks.  @stramel look the type improve! great work mate

**Comment by bluebill1049** [comment]
@tombertrand after submit if data still remain in the form, then the form should still consider as `dirty`. However, running reset should set `dirty` to `false`. FYI I am working on it, should be able to release this week :)

**Comment by bluebill1049** [comment]
looks like u just have to call `reset` after submit.

**Comment by bluebill1049** [comment]
it's merged, once @stramel finishes improve typing. I will release this patch :)

**Comment by tombertrand** [comment]
I'm facing a couple issues with `reset` after submitting. So I'm doing:

```javascript
reset(getValues()); // because can't reset the `dirty` state only, getValues else the form gets cleared
```

`reset(getValues());` does set every values but the ones containing `'`

```
{ // content of getValues()
  allItems: true, // -> sets correctly
  name: "hi",  // -> sets correctly
  item.'1': true,  // -> doesn't set
  item.'2': true,  // -> doesn't set
  ...
}
```

If I do `setValue("item.'1'", true);` after the reset, it sets the value correctly... 🤔

**Comment by bluebill1049** [comment]
I can look into reset problem.

**Comment by bluebill1049** [comment]
do you have a codesandbox with above issue?

**Comment by bluebill1049** [comment]
can you try this beta version? react-hook-form@3.22.2-beta.1 see if it solve your problem.

**Comment by tombertrand** [comment]
that latest release did fix the issue with keys containing `'` 👍 

so I ended up doing
```
saveItem(formData).then(({ data })=> {
  reset(data);
});
```

**Comment by bluebill1049** [comment]
I will release this patch soon.

**Comment by bluebill1049** [comment]
@tombertrand I will update you here once we release the patch, we are blocked by one of the type improvement, once that's sorted we will let it out :)
