### ISSUE TITLE
useWatch value become empty after delete field array item

### ISSUE THREAD

**Issue by xiaoyu-tamu** [react-hook-form/react-hook-form#2310]
**Describe the bug**

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-v6-usewatch-mjnow?file=/src/index.js
2. Click on append
3. Click on append
4. Click on delete
5. See JSON output

**Expected behavior**

it should preserve value same as `watch`

**Screenshots**
![image](https://user-images.githubusercontent.com/33362998/88115697-63dc8100-cb7c-11ea-8c7c-5bdbb16837b5.png)
![image](https://user-images.githubusercontent.com/33362998/88115710-69d26200-cb7c-11ea-9c54-7894efc03b98.png)

**Comment by bluebill1049** [comment]
you will have to do `watch('xxx', fields)` i am going to add a FAQ section for this.

**Comment by bluebill1049** [comment]
<img width="940" alt="Screen Shot 2020-07-23 at 6 40 49 pm" src="https://user-images.githubusercontent.com/10513364/88267339-0ed37300-cd14-11ea-8983-a9b7209aab44.png">

doc is updated under `useFieldArray`.

**Comment by xiaoyu-tamu** [comment]
Should we also mention use `watch` instead of `useWatch` under useWatch section?

**Comment by bluebill1049** [comment]
will do.

**Comment by bluebill1049** [comment]
@xiaoyu-tamu actually would you be able to adjust the doc? as you probably can describe better? you can leave it here or send a PR, i will get it updated.

**Comment by xiaoyu-tamu** [comment]
I would love to do, but I still don't understand why `useWatch` does not work for array field :-)

**Comment by bluebill1049** [comment]
oh wait, sorry i miss look the issue with watch API, i will take a look at it.
