### ISSUE TITLE
After upgrading to v6 field array value changes no longer persist after a drag and drop using React Beautiful DnD.

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#2312]
After upgrading to v6 field array value changes no longer persist after a drag and drop using React Beautiful DnD.

https://codesandbox.io/s/react-hook-form-usefieldarray-kit8r?file=/src/index.js

**Steps to Reproduce:**
1. Enter a value in the two inputs shown
2. Using the 'Drag Me' element drop one input into the place of the other

**Result:**
Data entered into both fields are reset to the default
**Expected Result:**
Data entered moves with the input

Switch React Hook Form version to 5.7.2 in the code sandbox and repeat the steps. The changed values move as expected.

Any idea what has changed?

_Originally posted by @nlrowe in https://github.com/react-hook-form/react-hook-form/discussions/2309_

**Comment by nlrowe** [comment]
Thank you Bill! Looks like this fix got merged, but has not been released. Any idea when the next version will go out?

**Comment by bluebill1049** [comment]
should come out in a couple days @nlrowe

**Comment by zjcwill** [comment]
when I use react-sortable-hoc to drag,   I meet the same question.

**Comment by bluebill1049** [comment]
@zjcwill do you have a codesandbox?

**Comment by nlrowe** [comment]
Hey Bill, I pulled this fix and it worked great for the drag and drop!

On testing the change further I have found another issue with persisting nested array values when you remove a parent array item. This issue also only occurs when drag and drop is in use. Using this [sandbox](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-mdq5k?file=/src/index.js:881-921) do the following:

1. Click 'Append Nested' to add a nested item to the outer array item
2. Change the input value to 'a'
3. Click 'Append' to add a new outer array item
4. Click 'Append Nested' to add a nested item
5. Change the input value to 'b'
6. Click 'Remove 0' to remove the first item of the outer array

**Result:**
The nested input value that was in the second outer array item ('b') is cleared

**Expected Result:**
The value remains 'b'

**Comment by bluebill1049** [comment]
not sure, this will play nicely with `useFieldArray`, because `key` is not using `item.id` at the root level.

<img width="584" alt="Screen Shot 2020-08-21 at 3 55 52 pm" src="https://user-images.githubusercontent.com/10513364/90857123-cbc5f780-e3c6-11ea-9927-dba9a2bbe882.png">

**Comment by nlrowe** [comment]
Good catch, looks like I had my keys mixed up!
