### ISSUE TITLE
Controller MUI Slider

### ISSUE THREAD

**Issue by LambdaMan2K** [react-hook-form/react-hook-form#2315]
hey thank you for sharing this awesome lib! so I found the following problem which might be caused of some changes to the api am not aware of but the following code works in v @5.5.1 and not in the latest V.
using "@material-ui/core": "^4.11.0"
` <Controller
            name="Slider"
            control={control}
            defaultValue={[0, 10]}
            onChange={([, value]) => value}
            as={<Slider valueLabelDisplay="auto" max={10} step={1} />}
          />`

**Comment by bluebill1049** [comment]
hey @LambdaMan2K take a look the example here: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r?file=/src/Mui.js:2175-2181

**Comment by LambdaMan2K** [comment]
Thx!

**Comment by sepsol** [comment]
The solution suggested above doesn't work anymore with `react-hook-form@7.5.3` and `@mui/material@5.2.7`.

I'm sharing my component in case anybody could point out if I'm doing something wrong here:
```jsx
import Slider from '@mui/material/Slider';
import { Controller, useForm } from 'react-hook-form';

const MARKS = [
  {
    value: 60,
    label: '60 SpO2',
  },
  {
    value: 65,
  },
  {
    value: 70,
  },
  {
    value: 75,
    label: '75 SpO2',
  },
  {
    value: 90,
    label: '90 SpO2',
  },
  {
    value: 100,
    label: '100 SpO2',
  },
];

function CustomSlider(name = 'rangeValues', min = 60, max = 100, step = null, marks = MARKS) {
  const hookForm = useForm({
    defaultValues: {
      [name]: [MARKS[1], MARKS[3]],
    },
  });

  return (
    <Controller
      control={hookForm.control}
      name={name}
      render={({ field }) => (
        <Slider
          {...field}
          onChange={(_, value) => field.onChange(value)}
          orientation="horizontal"
          aria-label="Oxygen Saturation Range"
          valueLabelDisplay="auto"
          min={min}
          max={max}
          step={step}
          marks={marks}
          disableSwap
        />
      )}
    />
  );
}

export default CustomSlider;
```

And here's the error I'm getting:
```err
TypeError: path.split is not a function
```

Thanks!
