### ISSUE TITLE
After the first submit returns an error, the subsequent submits are not called 

### ISSUE THREAD

**Issue by sefrem** [react-hook-form/react-hook-form#2317]
**Describe the bug**
I see that this issue has been submitted [before](https://github.com/react-hook-form/react-hook-form/issues/70)
I am using react-hook-form with create-react-app. After i  intentionally submit the form with errors, any subsequent handlesubmites don't fire till i reload the page. I'm using react-hook-form version 6.0.8. However, when i downgraded to the version 5.7.2, everything worked as expected.

**To Reproduce**
1. First try to login with wrong credentials
2. Then try to login with the correct ones 

**Codesandbox link (Required)**
Here is a [Codesandbox](https://codesandbox.io/s/react-hook-form-error-bug-h1cdr) link 

**Expected behavior**
Error disappears and form gets submitted

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83.0.4103.116

**Additional context**

**Comment by bluebill1049** [comment]
<img width="950" alt="Screen Shot 2020-07-22 at 6 11 43 pm" src="https://user-images.githubusercontent.com/10513364/88152045-cef28a00-cc46-11ea-8834-44dede7126ee.png">

`setError` on not associated input will require to invoke `clearErrors

**Comment by sefrem** [comment]
> `setError` on not associated input will require to invoke `clearErrors` to clear the error

I've tried that but if `handleSubmit` is not called at all, where to put `clearErrors`?

**Comment by bluebill1049** [comment]
```
<form className="auth" onSubmit={(e) => {
      clearErrors('auth');
      handleSubmit(onSubmit)(e)
    }}>
```

**Comment by sefrem** [comment]
Right.
BTW, as i updated back to the latest version, the issue was gone completely and everything works as expected even without `clearErrors`.
Thank you for you help and for this great lib.

**Comment by jamesleeht** [comment]
> ```
> <form className="auth" onSubmit={(e) => {
>       clearErrors('auth');
>       handleSubmit(onSubmit)(e)
>     }}>
> ```

Thanks for this. I think this should be put in the docs under clearErrors so people know how to invoke it on submit.
