### ISSUE TITLE
using example of FormProvider Performance will not able to trigger validation

### ISSUE THREAD

**Issue by stanleyyuenyiu** [react-hook-form/react-hook-form#2318]
according to the example of https://react-hook-form.com/advanced-usage/#FormProviderPerformance

if we put in some validation rules, when u click submit, you will not able to trigger the error, as it remember in memo

e.g

`const NestedInput = React.memo(
  (props) => (
    <>
<input name="test" ref={props.register({
    	required:"input.required"
    })} />
 {props.errors.test?.message}
</>
  ),
  (prevProps, nextProps) =>
    prevProps.formState.isDirty === nextProps.formState.isDirty
);

const Container = (props) => {
  const methods = useFormContext();
  return <NestedInput {...methods} {...props}/>;
}

`
and use it with useForm({mode: 'onBlur',  reValidateMode: 'onBlur'});

**Comment by stanleyyuenyiu** [comment]
Because by default formState.isDirty is false, 

and when u click submit without any value, it will false again, which memorised

unless u fill in somthing, make it to true, then u can go back to false when empty value

**Comment by bluebill1049** [comment]
send us a pr!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by stanleyyuenyiu** [comment]
@bluebill1049 sorry are you very angry? so you close the task? as it is an unresolved issue

**Comment by bluebill1049** [comment]
no, I am not angry. you already know the answer from the above statement, send us a PR then.

**Comment by stanleyyuenyiu** [comment]
huh? my question is how to resolve it? how do i know the answer? why not open it for everyone to dicuss?

**Comment by bluebill1049** [comment]
well go create a question at the discussion then, this section is for issues.

**Comment by stanleyyuenyiu** [comment]
> mark

yea, im using too strong language, sorry for that
