### ISSUE TITLE
getValues() returns an empty object after reset

### ISSUE THREAD

**Issue by smashercosmo** [react-hook-form/react-hook-form#2320]
**Describe the bug**
Seems like this issue is relevant again https://github.com/react-hook-form/react-hook-form/issues/1141

**To Reproduce**
1. Click 'Reset with reset fn' button
2. Check console output
https://codesandbox.io/s/react-hook-form-useform-template-pg564?file=/src/index.js

**Expected behavior**
If form is reset with values getValues function should return these values

**Comment by bluebill1049** [comment]
hey @smashercosmo this is the same as return default values from `getVaues()`.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2308

looks like everyone is expecting getValues to return defaultValues.

**Comment by smashercosmo** [comment]
Yeah, seems like the same issue

**Comment by smashercosmo** [comment]
@bluebill1049 this hasn't been fixed with latest release. You can check it in provided codesandbox.

**Comment by smashercosmo** [comment]
@bluebill1049 mind reopening this one?

**Comment by bluebill1049** [comment]
getValues is working as expected now, I don't think we need to reopen this issue.

<img width="1076" alt="Screen Shot 2020-07-28 at 10 43 27 pm" src="https://user-images.githubusercontent.com/10513364/88666690-c35e0200-d123-11ea-8817-c82335e777af.png">

**Comment by smashercosmo** [comment]
Really strange. I'm testing in the same sandbox and getting empty object when pressing "Reset with reset fn"

**Comment by smashercosmo** [comment]
Hm... maybe caching issue. It worked when I opened sandbox in incognito mode.

**Comment by MarianKmotorka** [comment]
It is broken once again on version 16.15.5

**Comment by daves28** [comment]
This is happening again on version 6.10.1.
`        reset({ name: 'hello' });
        console.log(`getValues()`, getValues());
        console.log(`watch()`, watch());`

result 
![image](https://user-images.githubusercontent.com/43623966/129367285-ac2574ed-4177-4b3c-96bf-ea07aa1ee49b.png)
