### ISSUE TITLE
Can not trigger handleSubmit outside form 

### ISSUE THREAD

**Issue by yogeshkotadiya** [react-hook-form/react-hook-form#2321]
**Describe the bug**

The `handleSubmit` method is not getting triggered if used outside of the form.
Although it works if we pass `handleSubmit` directly to SyntheticEvent.

```jsx
      <button
        onClick={handleSubmit(onSubmit)} // Works
      >
        Call Submit outside Form
      </button>

      <button
        onClick={() => {
          console.log("OnClick");
          handleSubmit(onSubmit); // Does not work
        }}
      >
        Call Submit outside Form
      </button>

```

**To Reproduce**
1. Create any simple form
2. Try calling `handleSubmit` method outside form

**Codesandbox link (Required)**
Include a codesandox will help us to investigate the issue quicker.

 [Sandbox](https://codesandbox.io/s/react-hook-form-useform-template-15x4h?file=/src/index.js)

**Expected behavior**
A Form `handleSubmit` should trigger regardless of where it's being called.

**Comment by bluebill1049** [comment]
`handleSubmit(onSubmit)()`

**Comment by pbizimis** [comment]
Hey @bluebill1049,
I am a bit late but maybe you can explain to me why your answer works? Thanks!
