### ISSUE TITLE
fields producing boolean values (radios or switch components) always invalid when `false`

### ISSUE THREAD

**Issue by colthreepv** [react-hook-form/react-hook-form#2323]
**Describe the bug**
on a field that has `required: true`, setting a boolean value makes the field valid only when is `true` (and invalid when it's `false`)

**Expected behavior**
the field should be invalid only when the value is `null || undefined`, if it is either `true || false` it's a valid boolean value

Culprit of this behaviour is this line:  
https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/validateField.ts#L80

It states that "if a value is boolean, must be True, otherwise it is invalid"

Why is this behaviour in place?

Using version: 5.7.2

**Comment by bluebill1049** [comment]
From memory, this is following HTML standard, as HTML inputs don't return null or undefined, happy to adjust if otherwise.

**Comment by colthreepv** [comment]
Ok, it seems consistent to not reinvent the wheel and just adopt HTML standards, inside my app I will worry about that converting some of those values back to boolean.

Thanks again

**Comment by hemadriDasari1990** [comment]
@bluebill1049 I'm having same issue. When field is required and its value is false the form is still in valid. Any solution that you can suggest to overcome this issue?

@colthreepv Can you please share your solution if you found working for you.

**Comment by hemadriDasari1990** [comment]
I overcome this issue by doing validations using validate function in rules

**Comment by michaelbrant** [comment]
@hemadriDasari1990 can you please share your solution?
