### ISSUE TITLE
Controller not working for Material UI slider component

### ISSUE THREAD

**Issue by btoro** [react-hook-form/react-hook-form#2327]
**Describe the bug**
Controller component not working for Material UI slider component. When value is changed on the controller, an error occurs:

" Received NaN for the `children` attribute. If this is expected, cast the value to a string."

**To Reproduce**
1. Go to [https://codesandbox.io/s/react-hook-form-controller-vj1o0]
2. Set react hooks version to 6.0.3 or higher
3. Scroll down to the slider
4. Try to change the value of the slider
4. See error in console

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-vj1o0

make sure you change reat hook version

**Expected behavior**
The value should change properly. 

**Desktop (please complete the following information):**
 - Ubuntu 18.0.2
 - Chrome
 - Version 83

**Comment by bluebill1049** [comment]
you are holding an outdated CSB: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r?file=/src/index.js

**Comment by btoro** [comment]
This CSB doesn't have examples with Material UI, and isn't very relevant.....
I'm trying to get this working with Material UI's slider..

**Comment by bluebill1049** [comment]
Are you serious.....?
<img width="1091" alt="Screen Shot 2020-07-23 at 9 16 12 am" src="https://user-images.githubusercontent.com/10513364/88238494-28010300-ccc5-11ea-9cc5-35e3f4558082.png">

**Comment by btoro** [comment]
You were correct, I saw the AntD example on first glace. My apologies to you @bluebill1049 .

**Comment by bluebill1049** [comment]
all good.
