### ISSUE TITLE
Error with form context and manually set errors

### ISSUE THREAD

**Issue by goaaron** [react-hook-form/react-hook-form#2329]
**Describe the bug**
I have some form inputs for which I render different error messages by setting keys on the errors.`inputName` field.

It looks kind of like this. And I use this to update the errors during input rather than at submit.
```
const InputComponent =() =>{
const { errors, setError, getValues } = useFormContext();

 const onInputChange = (e: React.SyntheticEvent) => {
    const validationErrors: Record<string, ValidateResult> = {};
    .
    .
    .
   setError('inputName', validationErrors);
}
.
.
.

<Controller
    onChange={([selected]) => {
            onInputChange(selected);
          }}/>
}
```
I've come across the other issue about this and learned that `setError` results don't persist. But beyond that.... when I press submit, my components for which I have a default `rules={{require:true}}` persist and the form values for my manually controlled error component become `undefined`.

After they have become `undefined`, they never get updated again to the values for `handleSubmit. Calling `setValue` also doesn't fix the problem. Essentially it becomes useless and I need to refresh the page. 

**Expected behavior**
I'm able to add and remove errors manually and have them persist through submissions. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: latest macos
 - Browser latest chrome

**Comment by bluebill1049** [comment]
which version and codesandbox?
