### ISSUE TITLE
Unregister doesn't clear validator

### ISSUE THREAD

**Issue by ndt94** [react-hook-form/react-hook-form#2330]
**Describe the bug**
Unregister doesn't clear validator

**To Reproduce**
1. Fill in First Name, Last Name
2. Click Submit => alert data include lastName value, firstName value
3. Click on Unregister Last Name
4. Clear input Last Name
5. Click on Submit => Nothing happen

**Codesandbox link (Required)**
Include a codesandox will help us to investigate the issue quicker.
https://codesandbox.io/s/react-hook-form-unregister-v6-f99wk?file=/src/index.js

**Expected behavior**
Alert data that should only have firstName value
Unregister should clear all current validator

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox Developer Edition v79.09b (64 bit)

**Comment by bluebill1049** [comment]
This is due to the next re-render, the input gets re-registered again. It's probably safe to remove the input from the `render`.

**Comment by ndt94** [comment]
can you elaborate how to fix it ? @bluebill1049

**Comment by bluebill1049** [comment]
@ndt94 it's easier just to unmount the input: https://codesandbox.io/s/react-hook-form-unregister-v6-98uxy?file=/src/index.js

**Comment by ndt94** [comment]
yeah this way is easier but doesn't seem to right, i expect the behavior as mentioned, and i don't want my input to be hidden, is there a way to add this as a feature?, I think it should be a feature

**Comment by bluebill1049** [comment]
@ndt94 you can use custom register at `useEffect` and `setValue`, otherwise you can have a flag in front of register to avoid the input gets re-registered again during another re-render.

**Comment by ndt94** [comment]
Actually i'm using `useEffect` and `setValue`, but it doesn't work, i will provide another sandbox, can you check it out later ? Meanwhile do you mind reopen this bug?

**Comment by ndt94** [comment]
@bluebill1049 here the example, idk why `isValid` doesn't work with custom register, if i remove disable props, the button can be submitted with both input value
https://codesandbox.io/s/react-hook-form-unregister-v6-um2uw?file=/src/index.js:1304-1333

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#setValue
`{ shouldValidate: true }`

**Comment by ndt94** [comment]
@bluebill1049 , i add that extra option and seem to work fine, guess you can close this bug now :+1:
