### ISSUE TITLE
validationSchema not working

### ISSUE THREAD

**Issue by stanleyyuenyiu** [react-hook-form/react-hook-form#2332]
i copy the same code https://github.com/react-hook-form/react-hook-form/blob/master/examples/validationSchema.tsx 
to my react app

while click submit, it pass the validation, seem validationSchema is not working

example : https://codesandbox.io/s/controller-rules-f8i1j?file=/src/App.tsx

"react-hook-form": "^6.0.8",
"yup": "0.29.1"

**Comment by bluebill1049** [comment]
oops that's for V5, going to get it updated.

**Comment by bluebill1049** [comment]
here is a working version for v5 anyhow; https://codesandbox.io/s/928po918qr

**Comment by stanleyyuenyiu** [comment]
so no longer support validationSchema ? 

and i saw this in readme
- remove `validationSchema` and embrace validation `resolver`

**Comment by stanleyyuenyiu** [comment]
yea i see the document using resolver
