### ISSUE TITLE
setValue()/reset() doesn't cause render inside Suspense

### ISSUE THREAD

**Issue by benswinburne** [react-hook-form/react-hook-form#2333]
**Describe the bug**
When setting default values from an async source as you've suggested by @bluebill1049 on Spectrum and on Github, the best way is to use reset or setValue. When the form is wrapped in <Suspense> and the values are retrieved asynchronously then passed to `setValue`, the form does not rerender.

**To Reproduce**
1. https://codesandbox.io/s/admiring-morse-oq796?file=/src/App.js
2. Observe the form field value says "flash of default" (the default value) instead of the value "from some API".
3. If you want to turn suspense off, change suspense: true to suspense: false in the code and refresh the sandbox (as changing the code causes hot reload to rerender the components.)
4. With suspense off, see "from some API" instead of "flash of default"

**Expected behavior**
The form fields to refresh after using setValue() or reset() inside a Suspense component.

**Comment by bluebill1049** [comment]
Thanks for the issue report and feature request, as `Suspense` and `concurrent mode` is not finalize just yet, we won't spend too much effort on this just yet. In the meantime, you can use the following: 

https://codesandbox.io/s/currying-cloud-d8e9f?file=/src/App.js

**Comment by benswinburne** [comment]
Thanks for providing a workaround Bill, much appreciated.

Whilst that works in a single use the initial values you've used are stored at the file level so that's shared for every use of the hook.

In the below example where the remote fetching belongs to a hook, the `let test` is scoped to the file so both forms share the same temporary store, but if i move it into the hook function scope it no longer works at all. I tried using a ref to use `myref.current` instead, and `test` scoped to the function but it didn't work.

Presumably the reason that your example works is because rhf is just keeping a reference to the `let test` object as its default values so when that changes it update the default value internally. I'd have assumed i could do this with a ref.current too as that's just a plain object.

I also tried setting values directly on the internal refs of RHF using `form.control.defaultValuesRef.current = mydata` (obviously unconventional)

And tried `form.control.reRender()` (also unconventional) which didn't do anything.

The only other way I've got it to work is wrap the form in a data fetching HOC, then don't render the form if the data isn't there and then render the form with the default data as a prop but that completely ruins the nice hook abstraction so any suggestions you may be able to point me at to make RHF rerender once i have set the data that'd be much appreciated.

Ideally if I can get that `let test` scoped to the function i'll be content for now I think but not sure how RHFs internals work in terms of the defaults/rerendering.

This CSB https://codesandbox.io/s/epic-grass-9mfft?file=/src/App.js shows a more up to date example where I'm using the hook twice (note this works but as they share `test` there's a potential race condition I believe?)

Thanks again.

**Comment by bluebill1049** [comment]
you can convert that let variable into useRef as well.

**Comment by benswinburne** [comment]
I'd tried using a ref but it doesn't appear to work. Any thoughts on why?

https://codesandbox.io/s/inspiring-feistel-hyz87?file=/src/App.js

It's exactly the same as the previous CSB but using `myRef.current` instead of the file scoped `let test`. I've been through this with a friend and neither of us are sure why this is the case and assume it's something to do with how RHF caches the defaults but not sure why a file level variable is different to a ref in that context.

Thanks again for your help/input, it's much appreciated.

**Comment by bluebill1049** [comment]
hmmm looks like ref solution doesn't work, the other alternative solution would be not having useQuery inside the form component and hoist it up to the parent component.

**Comment by benswinburne** [comment]
Yeah unfortunately the whole point is to create a hook where I can just set up a remote form with autosaving all in one place. As soon as I hoist part of the functionality it goes back to gluing bits together (this app has a _lot_ of forms too 😄 ). Probably going to have to make a HoC to group it together instead of a hook which is a bit of a shame but alas it is what it is as I'm stumped as to why a ref doesn't work.

Thanks for having a look.

**Comment by bluebill1049** [comment]
Yeah, it's a bit unfortunate, we will have a proper solution once suspense is finalized.

**Comment by Jack-Works** [comment]
Hi, I want to share some info about how to support concurrent mode with no bugs.

1. All state should be stored in the `useRef` of `useState` hooks.

```js
const someGlobalCache = new Map() // wrong
export function useMyHooks() {
    // do something with global cache
}
```

2. All states should be immutable (important!)

During the concurrent rendering, React will copy refs and states **by reference** (in my understanding). So any mutation will cause bugs in the concurrent mode.

```js
function useX() {
    const ref = useRef({})
    useEffect(() => {
        ref.current.xyz = 1 // Wrong!
        ref.current = { ...ref.current, xyz: 1 } // Safe
    })
}
```

3. It must compatible with the strict mode.

Hope that will help.
