### ISSUE TITLE
First party asynchronous default values api

### ISSUE THREAD

**Issue by benswinburne** [react-hook-form/react-hook-form#2335]
**Is your feature request related to a problem? Please describe.**

Asynchronous defaults are commonplace as they're often retrieved from storage when a UI is rendering

My use case is such that the UI presents some default values on checkboxes and radio buttons. If the user has never saved them before it doesn't matter, the consumer of these values has the same defaults elsewhere. If the users changes any of these values, the non default values are stored when changed. When the form is retrieved, defaults are set and the changed values are retrieved and set.

The reason the default value in [this example](https://codesandbox.io/s/festive-joliot-6r8k4?file=/src/App.js) is "flash of default" is because it the default value briefly flashes into the field while the asynchronous value is retrieved.

**Describe the solution you'd like**

Some sort of asynchronous defaults/suspense compatible api to set default values would be incredibly useful I think. Ideally one which is aware that it is setting defaults so it doesn't trigger changes on the form.

**Describe alternatives you've considered**

Obviously this is why I was trying to use <Suspense /> to try and prevent the rendering of the field until the remote data was ready so the user didn't see the default value, then the stored value.

I wonder if perhaps a function for the `defaultValues` config or `defaultValue` prop could be async and provide a means by which to tell react-hook-form that the values are async.

```
const { register, handleSubmit } = useForm({
  defaultValues: async () => ({field1: 'bar'}),
});
```

```
<input
  name="firstName"
  type="text"
  ref={register}
  defaultValue={async () => {
    return 'string'
  }}
/>
```

**Additional context**

The other problem with using `setValue` or `reset` to update the default values after the form has first rendered is that it causes watch() and useWatch() to trigger (as the fields have rightly changed), but they're actually technically the defaults. This has caused me issues with autosaving on change etc as I render defaults, get saved values and put them into the fields, watch notices it changes and it tries to save again so lots of refs and value comparisons etc has to happen around that to stop it trying to save the values it just retrieved!

Related https://github.com/react-hook-form/react-hook-form/issues/2333

**Comment by bluebill1049** [comment]
Thanks for the detailed feature request, I don't think we will implement such API for now, i will add a feature request and waiting for upvote for this issue.

**Comment by bluebill1049** [comment]
RFC: https://github.com/react-hook-form/react-hook-form/issues/2492
