### ISSUE TITLE
Ensure all values set in form are registered

### ISSUE THREAD

**Issue by pixel-mattp** [react-hook-form/react-hook-form#2349]
**Is your feature request related to a problem? Please describe.**
Not related to any problem

**Describe the solution you'd like**
When we receive a response from an API, we set the values of the form with the response.  
However, the only values that are sent back to the API (on a PUT for example) are the fields that you directly register in your form.

To send values back you are not directly using in your form, or use a value of a field, you have to manually register each one.  

So, for example, API response is this:

```
{
   first_name:  "Test",
   last_name:  "User",
   phone: 12345
} 
```

and the only fields you have in your form are `first_name` and `last_name` - only these 2 values are sent to the values of the form and not the entire response.

It would be great that you don't have to manually register every field just to have access to it's value.

**Describe alternatives you've considered**
Merge the values from the form and the values from the API before sending the form to an endpoint.

**Comment by bluebill1049** [comment]
i believe `shouldUnregister` probably is going to do the trick for you, otherwise you can still merge the data at the final submit without register those values.
