### ISSUE TITLE
useFieldArray keep value when appending after removing

### ISSUE THREAD

**Issue by danielnakamashi** [react-hook-form/react-hook-form#2350]
**Describe the bug**
In my `defaultValues`, I have an array of values that I want to render using `useFieldArray`. It render correctly, but when I remove the last item and append a new item (calling `append` without arguments), it renders with the value from defaultValue.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-template-e7x5l
2. Click on `delete` button from the second line
3. Click on `append` button
4. The controlled component get value from `defaultValues`

**Additional context**
Not sure if it's a bug or intentional

**Comment by bluebill1049** [comment]
i am confused, what's the error here?

**Comment by danielnakamashi** [comment]
Sorry, my bad. I updated the code at codesandbox.

**Comment by bluebill1049** [comment]
oh I see, append is required to have object(your data shape) argument.

**Comment by danielnakamashi** [comment]
Oh, ok. So it's not a bug. Thanks for fast reply!

**Comment by bluebill1049** [comment]
Thanks for the issue report anyhow 👍

**Comment by alisweid** [comment]
hello @bluebill1049  i am using useFieldArray, when appending normally everything works,but when trying to remove any populated form then appending, the new appended form is being populated by data from the removed form

**Comment by pstoica** [comment]
> 

I'm having the same issue. I believe it might be similar to https://github.com/react-hook-form/react-hook-form/issues/7935

Apologies, I don't have time to make a codesandbox yet. But I am using useFieldArray. It works with `register`, but not `<Controller />`.
