### ISSUE TITLE
Documentation on reset is ambigious (and typo!)

### ISSUE THREAD

**Issue by DamodarSojka** [react-hook-form/react-hook-form#2351]
Documentation on reset:
https://react-hook-form.com/api#reset
"Note: You will need to pass register() during reset to re-register input, or you can reset the form with with values. eg: reset({})."

1. I don't really understand how to "pass register() during reset"
2. I would emphasise more that just calling reset() simply won't work as the inputs won't be registered again (is there ever a need for such behaviour then?)
3. "with with values", probably with default values?
4. Did the behaviour changed between 5 and 6? I would say the new behaviour is unexpected, but I understand that there could be good reason for it

Let me know if I am missing something obvious here
Thanks in advance

**Comment by bluebill1049** [comment]
will get doc updated.
