### ISSUE TITLE
[useFieldArray] Errors validation should trigger when revalidate mode is on 'onChange'

### ISSUE THREAD

**Issue by Vandell63** [react-hook-form/react-hook-form#2369]
Hey how are you @bluebill1049 :) ?
**Describe the bug**
Simple, when i set the `reValidateMode` to `onChange` i expect the validation to trigger on any methods of `useFieldArray` methods.

**To Reproduce**
Yup schema with array of minimum 2.
Validate first the form.
Error happened that said we need 2 at least 2 items.
Click on append. The error still there.
Only when you click on Submit the message disappear.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-50nk4?file=/src/index.js

**Expected behavior**
As soon as i have 2 items in my array the error should disappear when i set `reValidateMode` to `onChange`.
Maybe i've misunderstood something here. 
As ever thx in advance :+1:

**Comment by Vandell63** [comment]
After investigate a bit more, it's not come from the use field array but more from any yup array validation, i continue

**Comment by bluebill1049** [comment]
hey @vadimshvetsov thanks for the issue report. hook form validation mode is actually focused on the inputs, the work around is easy to have 

`useEffect(() => { trigger('test') }, [trigger])`

now i did consider to bake the logic inside the `useFieldArray`, however this would be only applied to `resolver` level instead of build-in form validation, so i think leave at the field level is more consistent and i will update the doc to include this behavior, so users aware the work around.

**Comment by bluebill1049** [comment]
<img width="667" alt="Screen Shot 2020-07-27 at 10 24 24 am" src="https://user-images.githubusercontent.com/10513364/88493233-5cd9c680-cff3-11ea-9971-5c0d9734b803.png">

thinking about update this in the doc. let me know your thoughts.

**Comment by Vandell63** [comment]
thx @bluebill1049  so if i want to update any array errors from the `useFieldArray` methods like the append method. I have to  trigger the name of my array name right ? I will give a shot to the code sandbox that i provide. I'm back to you if it's enough clear to me and give you my thoughts about this :)

**Comment by bluebill1049** [comment]
thanks @Vandell63 👍

**Comment by Vandell63** [comment]
What you think about for every array methods like : `append("test", {shouldValidate: true, shouldFocus: true})` as you made for the `setValue`  ?  Does it seems relevant or am i out ?

**Comment by bluebill1049** [comment]
good idea! couple concerns here.

1. when validation is going to trigger? it's actually after mount 
2. probably a breaking change for the method

**Comment by Vandell63** [comment]
I did'nt know rhf enough to propose something relevant but maybe on every array method call we could trigger the validation if `shouldValidate` is set to true. And yes it could be a breaking change finally :/ . 
If we want to avoid the changes, does the `revalidateMode` set to `onChange` still consistent from what we expect when array have an error ?
With your example doc, the trigger will fire on every array form changes, so im pretty sure that we can propose something align with rhf'mindset for this case. 
I don't know if we should let it down for now, or if you want to go deeper in ?

**Comment by bluebill1049** [comment]
I think for now it's probably an easy option to watch the length of the array and trigger validation accordingly, we probably need a better or robust solution at useFieldArray level. It's important to cover both schema and build-in validator as well, just like TS and JS.

```
useFieldArray({
  // something validateLength in here
})
```

but probably going to be a separate feature later on once all the bugs and issues are more stable.

**Comment by Vandell63** [comment]
Oh right lets close this for now. Thx for your Time
