### ISSUE TITLE
[useFieldArray] filtering fields leads to unpredicted behavior

### ISSUE THREAD

**Issue by haagOS** [react-hook-form/react-hook-form#2371]
**Describe the bug**
I created a form with an array of elements. The form has multiple sections. Which element should be rendered in which section is defined by some condition. The useFieldArray hook has been used.

**To Reproduce**
1. Go to the codesandbox provided below
2. Click on the checkbox for "a@example.com"
3. Click submit
4. See console output

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-field-array-with-sections-kdwrw

**Expected behavior**
1. On submit all four elements of the form should be part of the submit data (actually 2)
2. The structure of the data should not change (actually: 'isSelected' suddenly appears to be an array)
3. The submit button should be disabled as soon as the original form state is restored (i.e. uncheck "a@example.com")

**Desktop:**
 - OS: Windows
 - Browser Chrome 
 - Version 84.0.4147.89

_To be honest I am not sure if this is a bug or a feature request._

**Comment by bluebill1049** [comment]
1. why key `id` is not used?
<img width="934" alt="Screen Shot 2020-07-27 at 9 51 59 am" src="https://user-images.githubusercontent.com/10513364/88492547-d622ea80-cfee-11ea-8143-221de14b9f72.png">

let's focus on one set to start with.
<img width="1231" alt="Screen Shot 2020-07-27 at 9 51 04 am" src="https://user-images.githubusercontent.com/10513364/88492526-be4b6680-cfee-11ea-86e3-53d119e994e2.png">

**Comment by haagOS** [comment]
@bluebill1049 thank you for replying that fast and for taking a deeper look at it.

to point 1) my fault - missed that one.

Though I just think how does that relate to the keyName of useFieldArray? The default there is 'id' but I set it to 'email'. Should 'id' still be used (i.e. **always**) as the key?

**Comment by bluebill1049** [comment]
@haagOS Yes, I think it's better to stick with the key that useFieldArray provided.

**Comment by haagOS** [comment]
Ok, I edited my codesandbox with the following changes:
1) I used `id` as the key for the field array and changed my data structure accordingly
2) I removed the `.filter()` and instead used a conditional render expression

[codesandbox - edited](https://codesandbox.io/s/react-hook-form-field-array-with-sections-edited-b7669)

Now the submit result is correct. However the `formState.isDirty` flag is broken. Even though `formState.dirtyFields` is an empty object the `formState.isDirty` flag remains true after the first change.

For the `isDirty` flag I could use a workaround of `formState.dirtyFields.users === undefined` which works as expected.

**Comment by bluebill1049** [comment]
hey, thanks for the update. can you try to `console.log(formState.isDirty)` before the render? we have a proxy around the formState to reduce re-render.

<img width="972" alt="Screen Shot 2020-07-28 at 11 21 17 am" src="https://user-images.githubusercontent.com/10513364/88608179-772fa500-d0c4-11ea-94a7-da9d93db88da.png">

**Comment by bluebill1049** [comment]
actually this could be a bug that @keiya01 already fixed https://github.com/react-hook-form/react-hook-form/pull/2368 going to publish it soon.

**Comment by haagOS** [comment]
Thanks for the reply.

I've updated the [codesandbox ](https://codesandbox.io/s/react-hook-form-field-array-with-sections-edited-b7669) accordingly.

I've defined two variables and print them before rendering:
- `isDirty = formState.isDirty`
- `isDirtyFix = formState.dirtyFields.users !== undefined`

Console output (uncheck then check 'c@example.com'):
![image](https://user-images.githubusercontent.com/10416517/88637097-03889a80-d0ba-11ea-9877-36b2481975e9.png)
So the issue with the `isDirty` flag remains.

Regarding the original question about filtering the field array (via `Array.prototype.filter()`): If this is not intended I suggest to add a note to the documentation of [useFieldArray ](https://github.com/react-hook-form/documentation/blob/1b8cf350c7983021de2df3ae9610a166eecc5412/src/data/en/api.tsx#L889)

**Comment by bluebill1049** [comment]
looks like there is an issue with the dirty, i will investigate the problem, but you should use a separate useFieldArray for the second FieldArray, instead reuse the same instance.

**Comment by bluebill1049** [comment]
<img width="411" alt="Screen Shot 2020-07-28 at 6 49 00 pm" src="https://user-images.githubusercontent.com/10513364/88641792-02c82680-d103-11ea-9bc9-2217256aba7d.png">

This is correct because your default value is miss match with your inputs on the screen.

1. use useFieldArray per FieldArray
2. your defaultValue should repent your inputs values

**Comment by haagOS** [comment]
Nice. this one did the trick: "useFieldArray per FieldArray".
Thank you very much and for your time!

Came up with the following working code now: [codesandbox](https://codesandbox.io/s/react-hook-form-field-array-with-sections-edited-2-ui51o?file=/src/App.tsx)

**Comment by bluebill1049** [comment]
nice glad it's working out for you, and thanks for the CSB which will help others.
