### ISSUE TITLE
5 -> 6 errors / missing migration guide

### ISSUE THREAD

**Issue by clehene** [react-hook-form/react-hook-form#2372]
Upon a quick look after upgrading from 5 to 6. There are several errors that don't show up anywhere in the release notes or documentation.

(at least) the following can't be found: 

* `FormContextValues`
* `FormContext`
* `ErrorMessage`
* `submitFocusError`

Is there a migration guide, or otherwise what's the recommended approach to upgrading?

**Comment by bluebill1049** [comment]
let's improve it: https://react-hook-form.com/migrate-v5-to-v6 but i think some of them already got covered.

**Comment by clehene** [comment]
I can't find the migration guide in the repo, but here are my changes 

Replaced type `FormContextValues` with `UseFormMethods`
```diff
-import { FormContextValues } from 'react-hook-form';
+import { UseFormMethods } from 'react-hook-form';
...
-} & Partial<Pick<FormContextValues, 'errors' | 'register'>>) => {
+} & Partial<Pick<UseFormMethods, 'errors' | 'register'>>) => {
```

`yarn add @hookform/error-message`

```diff
-import { ErrorMessage } from 'react-hook-form';
+import { ErrorMessage } from '@hookform/error-message';
```

Not sure about this one (I just removed the option)

``` diff
-    submitFocusError: true,
-    shouldFocusError: true,
```

**Comment by bluebill1049** [comment]
Thanks, will get them included tonight.

**Comment by bluebill1049** [comment]
<img width="1154" alt="Screen Shot 2020-07-27 at 9 29 10 am" src="https://user-images.githubusercontent.com/10513364/88492090-a1f9fa80-cfeb-11ea-8b54-6ba42433cd3d.png">

ErrorMessage is covered

**Comment by bluebill1049** [comment]
![Uploading Screen Shot 2020-07-27 at 9.29.31 am.png…]()

and setError

**Comment by bluebill1049** [comment]
in terms of TS, you can refer to this page: https://react-hook-form.com/ts as we only start to document them down from v6

**Comment by bluebill1049** [comment]
doc updated with the missing piece: submitFocusError. thanks 👍

**Comment by benjaminchevoor-instacart** [comment]
If you're coming in for react-hook-form 7, it looks like the new type name is `UseFormReturn`.

**Comment by bluebill1049** [comment]
refer to this page: https://react-hook-form.com/ts
