### ISSUE TITLE
Type 'TFieldName' cannot be used to index ty

### ISSUE THREAD

**Issue by kielvi** [react-hook-form/react-hook-form#2375]
Hi, I'm trying to use the react-hook-form, and after npm install package and import, I'm getting the following error:

TypeScript error in /Applications/MAMP/htdocs/brf-reset-senha/Service.Login/ClientApp/node_modules/react-hook-form/dist/types/form.d.ts(189,130):
Type 'TFieldName' cannot be used to index type 'UnpackNestedValue<TFieldValues>'.  TS2536

**Comment by simtechmedia** [comment]
I had the same issue when I upgraded from react-hook-form 4.x to 6.x.  It was because I was using typescript version 3.7.x, Upgrading resolved this issue. 

Hope this helps

**Comment by bluebill1049** [comment]
> I had the same issue when I upgraded from react-hook-form 4.x to 6.x. It was because I was using typescript version 3.7.x, Upgrading resolved this issue.
> 
> Hope this helps

Thank you 🙏
