### ISSUE TITLE
Issue with setError where it's only shown after 1ms timeout

### ISSUE THREAD

**Issue by rnnyrk** [react-hook-form/react-hook-form#2380]
Hi there,

Currenty I'm running into a strange issue / bug where an error added with `setError` will only be shown when I wrap it with a 1ms timeout. When I don't do that the error is removed immidiatly and I can't seem to understand or figure out why.

I've created a CodeSandbox which mimics my exact situation. Hope you can help out, or explain what I'm doing wrong or what I do misunderstand. 

https://codesandbox.io/s/react-hook-form-seterror-issue-lc8sg?file=/src/App.js

**Comment by bluebill1049** [comment]
can you reproduce this in an isolated env? there are so many dependency in the CSB.

**Comment by rnnyrk** [comment]
@bluebill1049 Tell me what I need to strip, because for me this is a pretty isolated env. I run into the issue with this exact scenario using a datepicker.

**Comment by bluebill1049** [comment]
can you reproduce this with just <input /> or plus with Controller? right now your DataPicker have a lot of sideEffects: https://codesandbox.io/s/react-hook-form-seterror-issue-lc8sg?file=/src/DatePicker/index.js

**Comment by rnnyrk** [comment]
@bluebill1049 I'd strip the DatePicker component for you to the minimum so the only effects are `react-hook-form` related. Is this enough for you? To be honest I think when I refactor the CodeSandbox example to be using a Controller we might miss the point of the bug, since this is not how I use it in my application? 🤔

**Comment by bluebill1049** [comment]
sounds good to me, as long as there are less logic in that component which are potential the root cause, as i don't think we have issue with setError, the code underneath is rather simple.

**Comment by rnnyrk** [comment]
So can you check if this is good for you @bluebill1049 ? https://codesandbox.io/s/react-hook-form-seterror-issue-lc8sg?file=/src/DatePicker/index.js

**Comment by bluebill1049** [comment]
The bug is on your second DatePick is try to remove the error, I am not sure where you remove the error, but you can try this demo and select the second date picker, and then first, it's always working. It's not a bug with setError.

https://codesandbox.io/s/react-hook-form-seterror-issue-t9dgt?file=/src/App.js

**Comment by bluebill1049** [comment]
<img width="617" alt="Screen Shot 2020-07-27 at 9 56 09 pm" src="https://user-images.githubusercontent.com/10513364/88539113-fcc73c80-d053-11ea-93db-f6e59945653a.png">
look around here.
