### ISSUE TITLE
Take default values from resolver schema

### ISSUE THREAD

**Issue by Satyam** [react-hook-form/react-hook-form#2384]
**Is your feature request related to a problem? Please describe.**

All three supported schema validators allow the declaration of default values for all its types.  See [Superstruct](https://github.com/ianstormtaylor/superstruct/blob/HEAD/docs/reference.md#defaulted), [Joi](https://hapi.dev/module/joi/api/?v=17.1.1#anydefaultvalue), [Yup](https://www.npmjs.com/package/yup#mixeddefaultvalue-any-schema)

They produce these values when the input is `undefined`.  It would be a good idea to support this feature, which would allow the definition of all aspects related to the form values to be defined in one place, instead of having separate definitions for `defaultValues` elsewhere.

**Describe the solution you'd like**

Upon calling `useForm`:

1. Call the resolver with the `values` argument set to `undefined`.  This will signal the resolver that the form is being initialized and the default values are being requested.   
2. The resolver should return the default values, when available, and no `errors`.
3. Get these default values from the schema merged and overridden with the `defaultValues` argument, if any.

For backward compatibility: 

* Wrap this call to the resolver in a `try-catch` block as many a resolver would fail upon getting `values=undefined` instead of an object.   In that case, it may be safely assumed the resolver is not prepared to provide `defaultValues`.
* If the resolver returns a non-empty `errors` object, ignore the values, as it may be assumed that the resolver is clueless.

**Describe alternatives you've considered**

I started loading `defaultValues` from the defaults of my schema manually, copy/pasting the same boilerplate over and over.  
Then I will defined my own version of `useForm` that does this automatically.

**Comment by bluebill1049** [comment]
hmmm, it's the same as `context`, personally I prefer single place for API. thanks for your feature request tho, keep it on the list.

**Comment by Satyam** [comment]
@bluebill1049  Are you sure your reply was meant for this issue?  What has `context` to do with the requested feature?  If so, please elaborate.  I'd love to know if it is so because I could use it and also, if so, it should be documented somehow.

**Comment by bluebill1049** [comment]
what I meant is you can supply 

`useForm({ context })`

or 

`yup({ context })`

but for the sake of consistency, we force the user to set at the `useForm` level.
