### ISSUE TITLE
[useFieldArray] `watch` does not return correct values when removing item

### ISSUE THREAD

**Issue by hthuong09** [react-hook-form/react-hook-form#2386]
**Describe the bug**
The data return by `watch` is different from the real data in `field` (item of `fields`) when removing item

**To Reproduce**
1. Go to https://codesandbox.io/s/lingering-shape-b00bs
2. Click on Toggle Use Entry Condition to On
3. Select Segment Type `Type 2`
4. Enter From and To date
5. Click on `Add More Entry Condition` 2 times
6. Open the console, clear all console
7. Click on [x] button of Condition 3
8. Click on [x] button of Condition 2
9. Look at the Condition 1
10. Segment Type is still Type 2 but Start and End were gone.

That was because this line: (src/ChallengeForm/EntryCondition/SegmentEntryCondtion/index.js#18)
```
const segmentKey = watch(`${fieldKey}.key`);
```
Returns `type1` instead of `type2`

**Expected behavior**
```
const segmentKey = watch(`${fieldKey}.key`);
```
Should return `type2`. From, and To input will still display.

**Additional context**
Also, sometimes `watch(``${fieldKey}.key``)` returns undefined even though the default value was given when appending. Is it expected behavior?

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report, for remove you can either use `useWatch` or `wach` API, but you will have to subscribe to the entire FieldArray.

**Comment by hthuong09** [comment]
Hi @bluebill1049 thanks for the fast reply.
I tried to update the example by subscribe to the entire `entryConditions` field.
https://codesandbox.io/s/lingering-shape-b00bs

When adding a new item, `entryCondtions[1]` give me undefined instead of default value that I appended.
`field` still gives the correct value though.
Should I fallback to `field` when `entryConditions[index]` gives me undefined?

**Comment by bluebill1049** [comment]
hey @hthuong09 I think this will solve the problem:

<img width="886" alt="Screen Shot 2020-07-28 at 1 05 05 pm" src="https://user-images.githubusercontent.com/10513364/88614373-f7f59d80-d0d2-11ea-8906-97dbcc51c267.png">

**Comment by hthuong09** [comment]
@bluebill1049 I already added the default fields, though!
![image](https://user-images.githubusercontent.com/8191266/88615503-4481ae80-d0bc-11ea-867f-39770234a681.png)

**Comment by bluebill1049** [comment]
sorry, honestly I didn't check your code, but look the size of your codesandbox, can you imagine if everyone submits an issue for me to analyze the whole app? at least you can tell me which file to look for it or provide an isolated codesandbox to reproduce the problem. 

<img width="384" alt="Screen Shot 2020-07-28 at 1 31 20 pm" src="https://user-images.githubusercontent.com/10513364/88616119-a18a5e00-d0d6-11ea-82f9-202a6ee990b5.png">

**Comment by hthuong09** [comment]
Sorry for the big codebase. I tried to split it from my main app but there was many common components.
As for the file, I think you could look at this file https://codesandbox.io/s/lingering-shape-b00bs?file=/src/ChallengeForm/EntryCondition/EntryCondition.js at 3 positions
1. Where I watch the `entryConditions` field, `line#55`
2. Where I use the watched `entryConditions` field, `line#72`
3. Where I append new item, `line#132`

Anyway, this issue is different from the one I submit, so I will investigate again fire another ticket if it still happens.
Thanks 🙏

**Comment by bluebill1049** [comment]
Thanks, @hthuong09 let me know the other issue as well, see if I can help it.
