### ISSUE TITLE
Validating Zero

### ISSUE THREAD

**Issue by sidonaldson** [react-hook-form/react-hook-form#239]
## Required validation triggers if my select returns number 0.

Setting custom validation rules don't trigger when using setValue if I pass it number 0

```
register(
            {
                name: 'myProp'
            },
            {
                 required: 'whoops'
             }
        );
```

This triggers if `setValue('myProp', 0, true);`

Additionally

```
register(
            {
                name: 'myProp'
            },
            {
                 required: 'whoops',
                 validate: (id: number) => {
                       return (id > -1 && id !== 999) || 'whoops';
                  }
             }
        );
```

 The validate function isn't even called if I use `setValue('myProp', 0, true);`

I would expect the validate function to run every time there is an update.
Also, how should 0 values be used? Selects might legitimately return the number 0. 

The ideal solution would be a property which allows 0 as valid?

A quick fix is to cast everything as strings :(

Any help is appreciated :)

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report. 

For your use case, I would recommend using validate without `required`.

I followed standard HTML validation for required where the input value is a string.

`<input name="test" value="0" />`

but we can make this work with `validate`

```
{
  validate: (value) => {
    return (value !== undefined)
  }
} 
```

**Comment by bluebill1049** [comment]
let me double-check the website and let you know, would love to see you in the contribution list! :)

**Comment by stramel** [comment]
Sorry 😅 don't know how that happened

**Comment by bluebill1049** [comment]
hahah

**Comment by bluebill1049** [comment]
I am going to close this issue for now, i will let you know what to update on documentation later on if you still interested :) 👍
