### ISSUE TITLE
Wizard Example not rendering

### ISSUE THREAD

**Issue by steinroe** [react-hook-form/react-hook-form#2394]
**Describe the bug**
[This example](https://react-hook-form.com/advanced-usage#WizardFormFunnel) in the docs throws an TypeError: getStore is not a function in code sandbox. I get the same error when reproducing it in my project.

**To Reproduce**
1. [Go to the example and open CodeSandbox](https://react-hook-form.com/advanced-usage#WizardFormFunnel)

**Codesandbox link (Required)**
[Direct Link](https://codesandbox.io/s/form-wizard-pages-kkg7m)

**Expected behavior**
Should work as presented in the example.

**Comment by bluebill1049** [comment]
here is a completed one: https://codesandbox.io/s/react-hook-form-wizard-form-complete-wb6gs it's the description of the video

**Comment by steinroe** [comment]
Thanks for the quick reply, but for me it also throws the error:

![Screenshot 2020-07-28 at 08 40 04](https://user-images.githubusercontent.com/19429600/88628267-f2d22780-d0ad-11ea-8c3a-ea881c6bf3ee.png)

**Comment by bluebill1049** [comment]
fork that codesandbox and work on top of it? perhaps some package versioning.
