### ISSUE TITLE
[useFieldArray] form is dirty when append and remove field

### ISSUE THREAD

**Issue by danielnakamashi** [react-hook-form/react-hook-form#2395]
**Describe the bug**
When I append a field and then remove it, the `formState.isDirty` is still `true`.

**To Reproduce**
1. Open console
2. Click on append button
3. Remove last field clicking on remove button
4. Check console and isDirty is still `true`

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-ktweo?file=/src/index.js

**Expected behavior**
`formState.isDirty` is `false` at the end of steps

**Additional context**
It doesn't happen in version 6.0.8

**Comment by bluebill1049** [comment]
I think we just patched with 6.1.1, can you verify the fix?

**Comment by danielnakamashi** [comment]
Looks like it's still happening 🙁

**Comment by tobiasAuzmendi** [comment]
It seems that this is still happening in the latest version ( 6.10.1 )

**Comment by bluebill1049** [comment]
@tobiasAuzmendi Do you have a `defaultValue` at `useForm`, next minor version will only rely on isDirty against what's in the form and default values. Can you also provide a CSB?
