### ISSUE TITLE
getValues return empty object in cleanup function after build

### ISSUE THREAD

**Issue by vukadinFE** [react-hook-form/react-hook-form#2399]
**Describe the bug**
`getValues()` return form values correctly in cleanup function while running app in dev mode, but same code always return an empty object in production, after `yarn build` (create-react-app)

**To Reproduce**
1. Go to https://codesandbox.io/s/pensive-wind-63goz
2. Enter some text in firstName and lastName fields
3. Click on "Step 2" link
4. See in console and confirm that there is an object (fields you entered in step1) returned form `getValues()` in cleanup function
5. Go to production version: https://csb-63goz.netlify.app
6. Repeat 2. and 3. step from this list
7. See in console and confirm that object returned from `getValues()` in cleanup function is empty

**Expected behavior**
Expected production to have same output as in development mode.

**Comment by bluebill1049** [comment]
can you update with the latest `patch`? and adding some more log inside the prod build and perhaps with source map as well.

**Comment by bluebill1049** [comment]
try `onClick` `getValues()` instead of `useEffect`?

**Comment by vukadinFE** [comment]
It's definitely working with onClick, but bug is from cleanup function in useEffect.

**Comment by bluebill1049** [comment]
don't think there is anything we can do at this lib level, except React. i suggest you use onClick for now.
