### ISSUE TITLE
Fix release 3.22.0

### ISSUE THREAD

**Issue by stramel** [react-hook-form/react-hook-form#240]
**Describe the bug**
Seems there is a problem with the build. I think reverting the `exports: 'named'` should fix it.

**Comment by bluebill1049** [comment]
what's the issue?

**Comment by bluebill1049** [comment]
release a fix now

**Comment by bluebill1049** [comment]
my bad i didn't check carefully before the release. i was testing an example and it was point to a local version of react hook form...

**Comment by stramel** [comment]
Sorry, it wasn't running in cjs environments from what I could tell. Will test the latest version now

**Comment by stramel** [comment]
Looks like 3.22.1 fixes it. Sorry for that! I should have verified it myself. Perhaps we can work on adding some automated checks for build verification?

**Comment by bluebill1049** [comment]
Yea I will look into that. no worries all good
