### ISSUE TITLE
Reset function resets form fields to empty values when 'values' argument is a memoized object

### ISSUE THREAD

**Issue by smashercosmo** [react-hook-form/react-hook-form#2400]
**Describe the bug**
Reset function resets form fields to empty values when 'values' argument is a memoized object.

**To Reproduce**
https://codesandbox.io/s/react-hook-form-useform-template-ktu9n?file=/src/index.js
1. Enter something in the input field
2. Press 'reset' button
3. Input field will be reset to empty string

**Expected behavior**
You should be able to use memoized values object when reseting form

**Comment by bluebill1049** [comment]
if you reset with the memorized value, then you will need to use `register()`, otherwise the register method won't know its dep is changed.

**Comment by smashercosmo** [comment]
Didn't quite understand the 'register' part. How would I use register while reseting the form?

**Comment by bluebill1049** [comment]
`<input name="FirstName" ref={register()} />`

**Comment by smashercosmo** [comment]
Oh, alright, thx
