### ISSUE TITLE
useFieldArray remove(index) is not refreshing formState.isValid

### ISSUE THREAD

**Issue by lascarayf** [react-hook-form/react-hook-form#2403]
The formState.isValid continues in "false" when remove items from a filedArray.

1. Go to Sandbox
2. Click on "Append" and the Submit button will be disabled
3. "Delete" second item.
4. Submit button continues disabled !!

[Codesandbox](https://codesandbox.io/s/formstate-is-not-still-valid-after-removing-items-eevbe)

**Expected behavior**
The submit button should be enabled (formState.isValid == true)

**Additional context**
I think it's related to this old ticket https://github.com/react-hook-form/react-hook-form/issues/1097

**Comment by bluebill1049** [comment]
please read the doc!!: https://react-hook-form.com/api#useFieldArray

https://codesandbox.io/s/formstate-is-not-still-valid-after-removing-items-by3e7?file=/src/App.js

1. miss defautValue
2. miss argument at append()

**Comment by lascarayf** [comment]
@bluebill1049 thanks for your answer. 

The example you gave me is not working either. With defautValue and argument at append() I have the same problem.

**Comment by bluebill1049** [comment]
are you sure?
