### ISSUE TITLE
`setValue()` does not blur and therefore `formState.isValid` is not usable

### ISSUE THREAD

**Issue by cliffordp** [react-hook-form/react-hook-form#2406]
**Describe the bug**
`setValue()` does not trigger _blur_ so `formState.isValid` isn't true even when `mode: blur`

But tabbing into (past) the field does make `formState.isValid` true.

**Codesandbox link (Required)**
https://codesandbox.io/s/rhf-react-select-setvalue-isvalid-g9dk2?file=/src/index.js was as close as I got but couldn't get it to actually hide the Submit Button based on `formState.isValid` even though it's working for my own project.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Edge
 - Version: 84.0.522.44

**Additional context**
I also tried:

* `<Controller ... rules={{ required: true }} ... as React Select ... />`
* `reValidateMode: 'all'`

FYI: docs site mentions `validateCriteriaMode` but that seems like it's maybe an outdated reference???

**Comment by bluebill1049** [comment]
think you miss this: setValue('xxx', { shouldValidate: true })

**Comment by bluebill1049** [comment]
aha you are right, your title is miss leading.

**Comment by cliffordp** [comment]
Thanks for the quick fix!

I didn't mean to be misleading; tried my best ;)

Any idea when it would make it to an npm release?

**Comment by cliffordp** [comment]
I see it's been release. Awesome!

**Comment by bluebill1049** [comment]
oops, too many notifications, I missed your last message... yes it's released.

**Comment by cliffordp** [comment]
@bluebill1049 Happens to me all too often.

Bummer... I changed NPM from `^6.1.2" to "^6.2.0" and it's still not working as expected...
1min demo video: https://share.getcloudapp.com/rRu7JPkQ

I have this setup:
```js
const { control, formState, handleSubmit, setValue, watch } = useForm( {
	mode: 'onBlur',
	reValidateMode: 'all',
} );
```

If there's a different set of args to send to useForm that _would_ make `formState.isValid` work as expected, please let me know.

**Comment by bluebill1049** [comment]
can you help me to reproduce that in a codesandbox? i will take a look at tonight.

**Comment by bluebill1049** [comment]
oh... I think i know why, reValidateMode doesn't support `all`...

**Comment by bluebill1049** [comment]
<img width="978" alt="Screen Shot 2020-07-31 at 1 55 41 pm" src="https://user-images.githubusercontent.com/10513364/88998491-8701f000-d335-11ea-8dac-b0ecc0d6ea96.png">

**Comment by cliffordp** [comment]
Ah, nice catch. I changed to this but still didn't work:
```js
mode: 'onBlur',
reValidateMode: 'onBlur',
```

The CSB I included in my initial message here was forked from https://github.com/react-hook-form/react-hook-form/discussions/2179

**Comment by bluebill1049** [comment]
do you have a codesandbox @cliffordp ?

**Comment by cliffordp** [comment]
OK, I polished up this ticket's CSB and was able to reproduce... _finally_ :)

Same link as before: https://codesandbox.io/s/rhf-react-select-setvalue-isvalid-g9dk2?file=/src/index.js

Notice that the value of the first React Select _does_ get filled (satisfying its Required rule) and then picking something manually for second React Select works for 2nd field but entire form's `formState.isValid` is not true until you manually touch (blur) the 1st field.

Thanks for the help. Bedtime for me...

**Comment by bluebill1049** [comment]
@cliffordp i think you miss the `shouldValidat: true`

setValue("MyReactSelect", { value: "1", label: "User ID#1" }, { shouldValidate: true }); 👍

**Comment by cliffordp** [comment]
omg, tyvm! it worked.

I reread https://react-hook-form.com/api#setValue and see it says "you _can_ set..." but I guess I thought _shouldn't it validate by default?_

Is there a reason not to? I get making it a param that can be controlled but why wouldn't the default behavior be that if I'm setting a value it should trigger validation checking.

Typing it out, I think I'm misunderstanding the parameter... "shouldValidate" means "force validating as true", not "should trigger validation checking", correct? Why? Why shouldn't setValue() trigger all the validation checking so I don't have to force-set as valid or not?

For example, if I set the value to something that satisfied "required: true", it should validate _even though it didn't blur._ But if I for some reason set it to `""` then validation would be false because the _required_ check fails.

So, to me, `setValue()` should trigger the "is valid?" checking _regardless of the useForm() params, but allow setValue's params to override this default behavior, such as `shouldCheck: false` (with a better name for the param).

Please share your feedback.

**Comment by bluebill1049** [comment]
Thanks for your feedback!

1. `setValue` does not validate the input by default is not **new**, it starts from the very first version. 
2. `setValue` should not validate input by default, it's extra functionality that users want to validate the input or set the field to dirty, they are an extension of the base's functionality. 
3. consistency, all of our API's default config start to be `false`.

**Conclusion:**

we will stay as it is, unfortunately, you will have to adapt to the current API until the next breaking change. please feels free to bring up this topic again next time. In fact, before V6's release, we asked the community to give feedback with the RC version (include with all the release notes), that was the perfect time to have those feedback.

**Comment by bluebill1049** [comment]
also if you have confusion around the doc, please send us a PR.
