### ISSUE TITLE
FormContext is not exported from react-hook-form in Version 6.1.2

### ISSUE THREAD

**Issue by jetro4u** [react-hook-form/react-hook-form#2409]
When using version 6.1.2, I was getting the error message: 
`Attempted import error: 'FormContext' is not exported from 'react-hook-form'.`

However, the old version 5.7.2 is working fine.

**Comment by bluebill1049** [comment]
`FromProvider`

**Comment by muhamad-rizki** [comment]
> `FormProvider` take a look this page:
> https://react-hook-form.com/migrate-v5-to-v6

![image](https://user-images.githubusercontent.com/15137312/102565031-37b73300-410f-11eb-906a-12ce9263b020.png)

I have followed this doc and FormContext.Consumer is not exported, I use react-hook-form v6.13.0

**Comment by bluebill1049** [comment]
> > `FormProvider` take a look this page:
> > https://react-hook-form.com/migrate-v5-to-v6
> 
> ![image](https://user-images.githubusercontent.com/15137312/102565031-37b73300-410f-11eb-906a-12ce9263b020.png)
> 
> I have followed this doc and FormContext.Consumer is not exported, I use react-hook-form v6.13.0

will patch this.

**Comment by rilwis** [comment]
I got the same error on Windows:

```bash
"export 'FormProvider' was not found in 'react-hook-form'
```

However, it works on Mac OS X.

I'm using version 6.9.3.

**Comment by ekawatani** [comment]
@bluebill1049 Is this fixed? I'm using 7.14.2, but I still don't see it exported.
