### ISSUE TITLE
Codesandbox not working for Wizard/Funnel example

### ISSUE THREAD

**Issue by asapkot2** [react-hook-form/react-hook-form#2413]
**Bug**
The Codesandbox example accompanying wizard/funnel example does not work and gives error " TypeError
getStore is not a function".

**To Reproduce**
1. Go to [react-hook-form api documentation](https://react-hook-form.com/)
2. Click on 'Advanced'
3. Scroll down to 'Wizard/Funnel
4. Click on Codesandbox example

**Codesandbox link (Required)**

- [wizard/funnel](https://codesandbox.io/s/form-wizard-pages-kkg7m)
![Screen Shot 2020-07-29 at 12 02 56](https://user-images.githubusercontent.com/16146375/88830365-76b20f80-d193-11ea-8791-bef579448a71.png)

**Expected behavior**
Expected the codesandbox link to work.

**Comment by bluebill1049** [comment]
make sure u use the latest little state machine: https://codesandbox.io/s/form-wizard-pages-kkg7m

**Comment by gukii** [comment]
Using the currently published example (same as the link above), throws an error:

```
TypeError
Cannot read property 'getItem' of null
getBrowserStoreData
https://kkg7m.csb.app/node_modules/little-state-machine/dist/little-state-machine.es.js:46:42
storeFactory
https://kkg7m.csb.app/node_modules/little-state-machine/dist/little-state-machine.es.js:55:15
createStore
https://kkg7m.csb.app/node_modules/little-state-machine/dist/little-state-machine.es.js:149:19
evaluate
/src/index.js:11:12
   8 | 
   9 | import "./styles.css";
  10 | 
> 11 | createStore({
     |            ^
  12 |   data: {}
  13 | });
  14 | 
```

**Comment by bluebill1049** [comment]
> Using the currently published example (same as the link above), throws an error:
> 
> ```
> TypeError
> Cannot read property 'getItem' of null
> getBrowserStoreData
> https://kkg7m.csb.app/node_modules/little-state-machine/dist/little-state-machine.es.js:46:42
> storeFactory
> https://kkg7m.csb.app/node_modules/little-state-machine/dist/little-state-machine.es.js:55:15
> createStore
> https://kkg7m.csb.app/node_modules/little-state-machine/dist/little-state-machine.es.js:149:19
> evaluate
> /src/index.js:11:12
>    8 | 
>    9 | import "./styles.css";
>   10 | 
> > 11 | createStore({
>      |            ^
>   12 |   data: {}
>   13 | });
>   14 | 
> ```

looks fine to me? https://codesandbox.io/s/form-wizard-pages-kkg7m

**Comment by msalahz** [comment]
This happens when devtools is added as you can see in the following sandbox
https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-forked-bh7x8?file=/src/index.js

I can reproduce it be uncommenting line four

**Comment by bluebill1049** [comment]
> This happens when devtools is added as you can see in the following sandbox
> https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-forked-bh7x8?file=/src/index.js
> 
> I can reproduce it be uncommenting line four

yes, we are fixing devtool with that re-render from the root of your app in V7.

**Comment by msalahz** [comment]
What is the road map for releasing V7?

**Comment by bluebill1049** [comment]
> What is the road map for releasing V7?

you can keep an eye on this discussion: https://github.com/react-hook-form/react-hook-form/discussions/3714 I am working it on my free time, so it's hard to give a release date, but you can to try out the alpha version right now. I haven't worked on devtool just yet, on my todo list.
