### ISSUE TITLE
checkbox conditional

### ISSUE THREAD

**Issue by Rddiazolivos** [react-hook-form/react-hook-form#2416]
**Describe the bug**
When i have one conditional checkbox and send the form, and then i change the option and the form render the equal checkbox, i get "Cannot read property 'ref' of undefined"

**To Reproduce**
1. Go to https://codesandbox.io/s/sad-clarke-w1ih8?file=/src/App.js
2. Click on mrs and click send
3. Click on dr and click send

**Comment by bluebill1049** [comment]
couldn't reproduce...

**Comment by Rddiazolivos** [comment]
https://codesandbox.io/s/sad-clarke-w1ih8?file=/src/App.js
1- Select the second option "Mrs", and click send
2- Select the four option "Dr"  and click send
3- see the error.
this only happens with checkboxs
![image](https://user-images.githubusercontent.com/31427094/88862407-4176e300-d1ce-11ea-8553-f17ba0065965.png)

**Comment by bluebill1049** [comment]
not valid, why `radio` and `checkbox` share the same name?

**Comment by bluebill1049** [comment]
<img width="580" alt="Screen Shot 2020-07-30 at 9 55 48 am" src="https://user-images.githubusercontent.com/10513364/88865293-d9b2ad80-d24a-11ea-991c-478431608cc9.png">
