### ISSUE TITLE
react-native typescript errors

### ISSUE THREAD

**Issue by djMax** [react-hook-form/react-hook-form#2419]
**Describe the bug**
Using the module in a react-native typescript project yields these errors:

[uno]
[uno]  $ tsc -p tsconfig.build.json
[uno]  ../../node_modules/react-hook-form/dist/types/form.d.ts(11,126): error TS2304: Cannot find name 'FileList'.
[uno]  ../../node_modules/react-hook-form/dist/types/form.d.ts(46,17): error TS2304: Cannot find name 'VoidFunction'.
[uno]  ../../node_modules/react-hook-form/dist/types/form.d.ts(47,24): error TS2304: Cannot find name 'Node'.
[uno]  ../../node_modules/react-hook-form/dist/types/form.d.ts(47,40): error TS2304: Cannot find name 'MutationObserverInit'.
[uno]  ../../node_modules/react-hook-form/dist/types/form.d.ts(115,15): error TS2304: Cannot find name 'HTMLOptionsCollection'.
[uno]  ../../node_modules/react-hook-form/dist/types/form.d.ts(116,13): error TS2304: Cannot find name 'FileList'.
[uno]  ../../node_modules/react-hook-form/dist/types/form.d.ts(117,13): error TS2304: Cannot find name 'VoidFunction'.
[uno]  ../../node_modules/react-hook-form/dist/types/form.d.ts(128,15): error TS2304: Cannot find name 'VoidFunction'.
[uno]  ../../node_modules/react-hook-form/dist/types/form.d.ts(149,71): error TS2304: Cannot find name 'VoidFunction'.
[uno]  ../../node_modules/react-hook-form/dist/types/utils.d.ts(14,103): error TS2304: Cannot find name 'FileList'.
[uno]  ../../node_modules/react-hook-form/dist/types/utils.d.ts(14,295): error TS2304: Cannot find name 'FileList'.
[uno]  ../../node_modules/react-hook-form/dist/types/utils.d.ts(16,103): error TS2304: Cannot find name 'FileList'.

**To Reproduce**
1. Install the project in a react-native typescript project
2. Add some usage of the module (assumedly any usage);

**Expected behavior**
Valid typescript compile

**Comment by bluebill1049** [comment]
need more context.

**Comment by djMax** [comment]
Understood, I'm going to try and make a simple example. But it seems like basically just compile errors in Typescript+React-native. Perhaps because these types are from some non-RN TS library (like the DOM)?

**Comment by bluebill1049** [comment]
I think it's your TS version.

**Comment by djMax** [comment]
3.9.7?

**Comment by djMax** [comment]
It very much seems like it's a missing dom library in tsc, but I don't use the dom since it's RN, and adding that causes other errors... I thought I could avoid it by not using Controller but it has crept back in through some type reference or other.

**Comment by djMax** [comment]
With latest I get a couple more.

```
../../node_modules/@hookform/resolvers/dist/superstruct.d.ts:3:94 - error TS2707: Generic type 'Struct<T, S>' requires between 1 and 2 type arguments.

3 export declare const superstructResolver: <TFieldValues extends Record<string, any>>(schema: Superstruct.Struct) => Resolver<TFieldValues, object>;
                                                                                               ~~~~~~~~~~~~~~~~~~

../../node_modules/react-hook-form/dist/types/form.d.ts:11:126 - error TS2304: Cannot find name 'FileList'.

11 export declare type UnpackNestedValue<T> = NonUndefined<T> extends NestedValue<infer U> ? U : NonUndefined<T> extends Date | FileList ? T : NonUndefined<T> extends object ? {
                                                                                                                                ~~~~~~~~

../../node_modules/react-hook-form/dist/types/form.d.ts:46:17 - error TS2304: Cannot find name 'VoidFunction'.

46     disconnect: VoidFunction;
                   ~~~~~~~~~~~~

../../node_modules/react-hook-form/dist/types/form.d.ts:47:24 - error TS2304: Cannot find name 'Node'.

47     observe?: (target: Node, options?: MutationObserverInit) => void;
                          ~~~~

../../node_modules/react-hook-form/dist/types/form.d.ts:47:40 - error TS2304: Cannot find name 'MutationObserverInit'.

47     observe?: (target: Node, options?: MutationObserverInit) => void;
                                          ~~~~~~~~~~~~~~~~~~~~

../../node_modules/react-hook-form/dist/types/form.d.ts:115:15 - error TS2304: Cannot find name 'HTMLOptionsCollection'.

115     options?: HTMLOptionsCollection;
                  ~~~~~~~~~~~~~~~~~~~~~

../../node_modules/react-hook-form/dist/types/form.d.ts:116:13 - error TS2304: Cannot find name 'FileList'.

116     files?: FileList | null;
                ~~~~~~~~

../../node_modules/react-hook-form/dist/types/form.d.ts:117:13 - error TS2304: Cannot find name 'VoidFunction'.

117     focus?: VoidFunction;
                ~~~~~~~~~~~~

../../node_modules/react-hook-form/dist/types/form.d.ts:128:15 - error TS2304: Cannot find name 'VoidFunction'.

128     reRender: VoidFunction;
                  ~~~~~~~~~~~~

../../node_modules/react-hook-form/dist/types/form.d.ts:150:71 - error TS2304: Cannot find name 'VoidFunction'.

150     resetFieldArrayFunctionRef: React.MutableRefObject<Record<string, VoidFunction>>;
                                                                          ~~~~~~~~~~~~

../../node_modules/react-hook-form/dist/types/utils.d.ts:14:103 - error TS2304: Cannot find name 'FileList'.

14     [K in keyof T]?: IsAny<T[K]> extends true ? any : NonUndefined<T[K]> extends NestedValue | Date | FileList ? TValue : NonUndefined<T[K]> extends object ? DeepMap<T[K], TValue> : NonUndefined<T[K]> extends Array<infer U> ? IsAny<U> extends true ? Array<any> : U extends NestedValue | Date | FileList ? Array<TValue> : U extends object ? Array<DeepMap<U, TValue>> : Array<TValue> : TValue;
                                                                                                         ~~~~~~~~

../../node_modules/react-hook-form/dist/types/utils.d.ts:14:295 - error TS2304: Cannot find name 'FileList'.

14     [K in keyof T]?: IsAny<T[K]> extends true ? any : NonUndefined<T[K]> extends NestedValue | Date | FileList ? TValue : NonUndefined<T[K]> extends object ? DeepMap<T[K], TValue> : NonUndefined<T[K]> extends Array<infer U> ? IsAny<U> extends true ? Array<any> : U extends NestedValue | Date | FileList ? Array<TValue> : U extends object ? Array<DeepMap<U, TValue>> : Array<TValue> : TValue;
                                                                                                                                                                                                                                                                                                         ~~~~~~~~

../../node_modules/react-hook-form/dist/types/utils.d.ts:16:103 - error TS2304: Cannot find name 'FileList'.

16 export declare type IsFlatObject<T extends object> = Extract<Exclude<T[keyof T], NestedValue | Date | FileList>, any[] | object> extends never ? true : false;
                                                                                                         ~~~~~~~~


Found 13 errors.```

**Comment by djMax** [comment]
These declarations in my own type files make the problem go away:

```
// Fix react-hook-form
type FileList = any;
type VoidFunction = () => void;
type Node = any;
type MutationObserverInit = any;
type HTMLOptionsCollection = any;

declare module 'superstruct' {
  export type Struct = any;
}
```

**Comment by bluebill1049** [comment]
hmmm interesting, @kotarella1110 do you have any clue on this one? the first time we having this issue.

**Comment by kotarella1110** [comment]
@djMax I think you have to add dom types to tsconfig.

```
{
   "compilerOptions": {
    "lib": [..., "dom"],
    ...
  }
  ...
}
```

**Comment by djMax** [comment]
But I’m in react-native. I don’t have the DOM. Lying to TS in that way seems to defeat the whole point of TS

**Comment by bluebill1049** [comment]
honestly, this lib is supporting both web and native, I guess you can either follow what you did and what @kotarella1110 suggested.

**Comment by kotarella1110** [comment]
I will investigate it 👍

**Comment by bluebill1049** [comment]
Thanks @kotarella1110 we probably can document this down in the doc, if there is no good/easy solution.

**Comment by djMax** [comment]
I understand the point about supporting both, but this seems to indicate some abstraction leakage of some sort because these methods won't actually work in RN for the most part. I can imagine it might be involved, so I get that it might not be fixed... At least there's a workaround.

**Comment by bluebill1049** [comment]
agreed, either a solution or walk around to be documented.

**Comment by bluebill1049** [comment]
@kotarella1110 if we don't have a good solution, perhaps we can update the doc and close this issue?

**Comment by kotarella1110** [comment]
@bluebill1049 Not a good solution, but here are the solutions:

1. Similar to [Unform](https://unform.dev/), provide two packages, [web and native](https://github.com/Rocketseat/unform/tree/master/packages).
2. Define types such as `FileList` and `Node` as RHF types.

**Comment by bluebill1049** [comment]
> @bluebill1049 Not a good solution, but here are the solutions:
> 
> 1. Similar to [Unform](https://unform.dev/), provide two packages, [web and native](https://github.com/Rocketseat/unform/tree/master/packages).
> 2. Define types such as `FileList` and `Node` as RHF types.

Ok, I think we will document these walk around above then. Thanks @kotarella1110 for the investigation.

**Comment by bluebill1049** [comment]
```
type FileList = any;
```

I think we can update internally to avoid the issue
```
type VoidFunction = () => void; // we can turn those into `() => void` which i will do
type MutationObserverInit = any;
type Node = any;
type HTMLOptionsCollection = any;
```

I think this is bug with resolver:
```ts
declare module 'superstruct' {
  export type Struct = any;
}
```

what do you think @kotarella1110?

**Comment by kotarella1110** [comment]
> @bluebill1049 Not a good solution, but here are the solutions:
> 
> 1. Similar to [Unform](https://unform.dev/), provide two packages, [web and native](https://github.com/Rocketseat/unform/tree/master/packages).
> 2. Define types such as `FileList` and `Node` as RHF types.

My suggestion 2 is to define the type internally as follows:

```ts
type VoidFunction = () => void;

interface File extends Blob {
    readonly lastModified: number;
    readonly name: string;
}

interface FileList {
    [Symbol.iterator](): IterableIterator<File>;
}
```

**Comment by bluebill1049** [comment]
and keep those as `any`?

```
type Node = any;
type MutationObserverInit = any;
type HTMLOptionsCollection = any;
```

**Comment by kotarella1110** [comment]
@bluebill1049 I will try to verify if those types can also be defined 👍

**Comment by bluebill1049** [comment]
Thanks a lot @kotarella1110 👍

**Comment by bluebill1049** [comment]
here is the backup plane: https://github.com/react-hook-form/documentation/pull/399 FYI @kotarella1110

**Comment by kotarella1110** [comment]
@djMax @bluebill1049 I found that I could solve this by creating `global.d.ts` file.
Only React Native will have empty DOM interfaces, but React will not be affected.
For details, please see this PR https://github.com/react-hook-form/react-hook-form/pull/2518.

**Comment by kotarella1110** [comment]
@djMax I think this will be resolved in v6.3.1, what about?

**Comment by bluebill1049** [comment]
Thanks for the follow-up @kotarella1110 🙏

**Comment by djMax** [comment]
Looks good!

**Comment by bluebill1049** [comment]
fanatic 🥇 thanks @djMax and @kotarella1110's amazing PR 🙉

**Comment by inferusvv** [comment]
Sooo, today is November and  I am facing this problem. How you fixed that?

> node_modules/react-hook-form/dist/types/fields.d.ts:5:23 - error TS2304: Cannot find name 'MutationObserver'.
> 
> 5     mutationWatcher?: MutationObserver;
>                         ~~~~~~~~~~~~~~~~
> 
> node_modules/react-hook-form/dist/types/fields.d.ts:15:15 - error TS2304: Cannot find name 'HTMLOptionsCollection'.
> 
> 15     options?: HTMLOptionsCollection;
>                  ~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/react-hook-form/dist/types/fields.d.ts:16:13 - error TS2304: Cannot find name 'FileList'.
> 
> 16     files?: FileList | null;
>                ~~~~~~~~
> 
> node_modules/react-hook-form/dist/types/form.d.ts:13:98 - error TS2304: Cannot find name 'FileList'.
> 
> 13 export declare type UnpackNestedValue<T> = T extends NestedValue<infer U> ? U : T extends Date | FileList ? T : T extends Record<string, unknown> ? {
>                                                                                                     ~~~~~~~~
> 
> node_modules/react-hook-form/dist/types/utils.d.ts:19:103 - error TS2304: Cannot find name 'FileList'.
> 
> 19     [K in keyof T]?: IsAny<T[K]> extends true ? any : NonUndefined<T[K]> extends NestedValue | Date | FileList ? TValue : NonUndefined<T[K]> extends object ? DeepMap<T[K], TValue> : NonUndefined<T[K]> extends Array<infer U> ? IsAny<U> extends true ? Array<any> : U extends NestedValue | Date | FileList ? Array<TValue> : U extends object ? Array<DeepMap<U, TValue>> : Array<TValue> : TValue;
>                                                                                                          ~~~~~~~~
> 
> node_modules/react-hook-form/dist/types/utils.d.ts:19:295 - error TS2304: Cannot find name 'FileList'.
> 
> 19     [K in keyof T]?: IsAny<T[K]> extends true ? any : NonUndefined<T[K]> extends NestedValue | Date | FileList ? TValue : NonUndefined<T[K]> extends object ? DeepMap<T[K], TValue> : NonUndefined<T[K]> extends Array<infer U> ? IsAny<U> extends true ? Array<any> : U extends NestedValue | Date | FileList ? Array<TValue> : U extends object ? Array<DeepMap<U, TValue>> : Array<TValue> : TValue;
>                                                                                                                                                                                                                                                                                                          ~~~~~~~~
> 
> node_modules/react-hook-form/dist/types/utils.d.ts:21:103 - error TS2304: Cannot find name 'FileList'.
> 
> 21 export declare type IsFlatObject<T extends object> = Extract<Exclude<T[keyof T], NestedValue | Date | FileList>, any[] | object> extends never ? true : false;
>                                                                                                          ~~~~~~~~
> 
> 
> Found 7 errors.

**Comment by msvargas** [comment]
For help anybody, to solve this, add skipLibCheck option in tsconfig.json

```json

{
	"compilerOptions": {
		"skipLibCheck": true,
....
}

```
