### ISSUE TITLE
使用material ui TextField select 无法获取数据

### ISSUE THREAD

**Issue by flycj** [react-hook-form/react-hook-form#242]
**Describe the bug**
请看这个链接
https://codesandbox.io/s/react-hook-form-custom-input-m1br1
在使用嵌套组件时， 提交后没有获取到数据
并且 在控制台 提示：Missing field name: [object Object]
我不知道怎么解决这个问题
可能抽空看下吗，感谢🙏

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-custom-input-45q3o

看一下我修改的代码， 问题出在 `inputRef`
take a look at my updated code, the problem is the `inputRef`

**Comment by bluebill1049** [comment]
wait let me update the codesandbox

**Comment by bluebill1049** [comment]
ready now

**Comment by bluebill1049** [comment]
hmmm after change province, city is not working... i will take a look into why.

**Comment by bluebill1049** [comment]
its working you have an outdated version of react hook form.

**Comment by flycj** [comment]
> its working you have an outdated version of react hook form.

不好意思啊，回复晚了，我刚才在我的开发环境中使用你的方式，但是遇到了另外一个问题
https://codesandbox.io/s/react-hook-form-custom-input-m1br1
你可以点击这个链接
当点击开始“提交按钮”时 ，表单显示， 再次点击按钮时 标签隐藏，此时 
```
inputRef={e => {
          console.log(e);
          return register(e.node, {
            required: "请选择市"
          });
        }}
```
这个inputRef函数中会因为 e 为 null 而报错

**Comment by flycj** [comment]
不好意思哦， 又遇到一个问题
当<input name="name=[]" ref={register} /> name 是多个input 标签时
此时提交数据 为{"telephone":{"":"123"},"name":{"":"234"}}
具体情况见链接
https://codesandbox.io/s/react-hook-form-custom-input-m1br1
但是我觉得正确的数据格式应是 {"telephone":["123","12"],"name":["123","23"]} 才对

**Comment by bluebill1049** [comment]
哦 没问题 我会看的。 到时候回答你 昨天晚了去睡觉了。

**Comment by bluebill1049** [comment]
> 关注下上面的问题 

哪一个问题？

**Comment by flycj** [comment]
> > 关注下上面的问题
> 
> 哪一个问题？

https://codesandbox.io/s/react-hook-form-custom-input-m1br1
你可以点击这个链接，我已经把问题还原了。点击两次 “提交按钮”  可发现问题

**Comment by bluebill1049** [comment]
看来是node 被删除的问题

if（e.node）？

**Comment by flycj** [comment]
> 看来是node 被删除的问题
> 
> if（e.node）？

是因为 e === null 导致的。 但是在你发的链接中
https://codesandbox.io/s/react-hook-form-custom-input-2uizv
没有出现e === null 的情况。
