### ISSUE TITLE
Caching issue, I think!

### ISSUE THREAD

**Issue by akiarostami** [react-hook-form/react-hook-form#2420]
**Describe the bug**

Please check the sandbox link below.

The way the code is, after each validation and submit, data goes back to defaultValues.
Try changing the code, or submitting an empty field (which is required). 

Resetting the form data on Submit fixes the issue (which is not the right way anyway), but validation issue stays the same.

**Codesandbox link (Required)**
- [useForm](https://codesandbox.io/s/react-hook-form-reset-v6-sc498?file=/src/index.js)

**Expected behavior**
Form values should not go back to the cache values and should stay the same.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: latest

**Comment by bluebill1049** [comment]
Steps to reproduce?

**Comment by akiarostami** [comment]
Just click on the Codesandbox link and enter any value in the input and submit. And then clear the input and submit.

**Comment by bluebill1049** [comment]
> Just click on the Codesandbox link and enter any value in the input and submit. And then clear the input and submit.

Yes? and what do you mean?

> Form values should not go back to the cache values and should stay the same.

**Comment by bluebill1049** [comment]
`e.target.reset();`

is already clear the form? why I need to clear the input?

**Comment by akiarostami** [comment]
I'm so sorry, apparently Codesandbox was showing the code I forked. 

Here's a new link:

https://codesandbox.io/s/recursing-pine-3fwxq?file=/src/index.js

There, you can see the input has a default value (set using "reset"). When I edit and submit, it goes back to the original value. Also, if there's an error (.e.g. input is empty), again, it goes back to the original value.

I believe in both cases, when I successfully submit and when there's an error, the value should not change.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/laughing-field-p8ijy?file=/src/index.js

because your `Form` component is an inner component, it gets re-render each time.

**Comment by akiarostami** [comment]
Thanks for the prompt reply.

The real app obviously is not as simple as this little page, and I have to use the form inside other components. 

Is there a solution for this? I tried using your FormProvider but didn't get anywhere.

**Comment by bluebill1049** [comment]
That's not a problem whether it's a big or small app, the problem is you have a component live inside your component before your render.

```
const Test = () => {
   const Component = () => {
     // you are mount and unmount this component each render.
   }
  
  return <Component />
}
```

to 

```
const Component = () => {

}

const Test = () => {
  
  return <Component />
}
```
