### ISSUE TITLE
Form builder does not show correct type attribute into code section after creating an input

### ISSUE THREAD

**Issue by PatrissolJuns** [react-hook-form/react-hook-form#2421]
**Describe the bug**
After entering the name and select the type, the result of the type attribute is generally **undefined**

**To Reproduce**
1. Go to https://react-hook-form.com/form-builder
2. Fill the form and press create button
3. Check the type attribute in the code section 

**Screenshots**
If applicable, add screenshots to help explain your problem.**Describe the bug**
After type name and select type, the result of the type attribute is generally **undefined**

**To Reproduce**
1. Go to https://react-hook-form.com/form-builder
2. Fill the form and press create button
3. Check the type attribute in the code section 
4. See error (undefined instead of text or even number) as shown bellow

**Screenshots**
Here's a gif recorded to have an idea of what I'm saying
[![form-builder-error.gif](https://i.postimg.cc/sxDzvGr0/form-builder-error.gif)](https://postimg.cc/xJ7hZCqK)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 83.

**Comment by bluebill1049** [comment]
sorry form build is not something we are prioritizing for this lib.

**Comment by PatrissolJuns** [comment]
I went there to visit and test the feature and I discovered the bug. My intend is not to use the form builder but to simply report you a bug about it. I'm already using the lib

**Comment by bluebill1049** [comment]
oh @PatrissolJuns thanks a lot, I will probably finally visit it once lib is solid. thanks for reporting.
