### ISSUE TITLE
inject errors or the specific field error to controller

### ISSUE THREAD

**Issue by mohammadameer** [react-hook-form/react-hook-form#2422]
**Is your feature request related to a problem? Please describe.**
i have a multistep form with over 43 fields now I need to add errors to all my fields as props

**Describe the solution you'd like**
inject errors or the specific field error to the controller.

**Comment by mohammadameer** [comment]
we are injecting onChange, onBlur, and value can we also inject the errors or the error specific to the field?

**Comment by bluebill1049** [comment]
This is major change, I will keep in the backlog, and get the user to upvote for a feature request.

**Comment by bluebill1049** [comment]
I think you, for now, you can take a look at `memo` and try to isolate that re-render: https://react-hook-form.com/advanced-usage#FormProviderPerformance

**Comment by mohammadameer** [comment]
can i work in this ?

**Comment by bluebill1049** [comment]
you can work on this because it's a large change because right now errors are triggering re-render at the root. what's your plan?

**Comment by mohammadameer** [comment]
I have not seen the source code yet 😅, I will start work on it if I face anything I will call you 😁

**Comment by bluebill1049** [comment]
steps in my head.

1. proxy around `errors` object so if users is not subscribed to the object, don't trigger re-render.
2. create a new custom hook `useFormState`, so you can subscribe to individual form state.

FYI: this is not a simple task...

**Comment by cvle** [comment]
Maybe related to https://github.com/react-hook-form/react-hook-form/issues/1942. I also love to see something like this.

**Comment by bluebill1049** [comment]
> **Is your feature request related to a problem? Please describe.**
> i have a multistep form with over 43 fields now I need to add errors to all my fields as props
> 
> **Describe the solution you'd like**
> inject errors or the specific field error to the controller.

hey is this what you after? https://react-hook-form.com/advanced-usage#ExtendController
