### ISSUE TITLE
<input name="name[]" ref={register} /> 数据不正确

### ISSUE THREAD

**Issue by flycj** [react-hook-form/react-hook-form#243]
**Describe the bug**
当<input name="name[]" ref={register} /> name 为这个形式时，浏览器默认在表单提交时是一个数组形式的数据.
但是当前提交表单显示的数据 为{"telephone":{"":"123"},"name":{"":"234"}}
具体情况见链接
https://codesandbox.io/s/react-hook-form-custom-input-m1br1

**Comment by stramel** [comment]
@flycj You need to specify an index in the array, like this. 

```
name="telephone[0]"
name="telephone[1]"
```

**Comment by flycj** [comment]
> @flycj You need to specify an index in the array, like this.
> 
> ```
> name="telephone[0]"
> name="telephone[1]"
> ```

Thank you very much.
I will try this way right away.

**Comment by flycj** [comment]
This way is really effective
I will close this issue
I wish you a happy life 🙏
