### ISSUE TITLE
React-select wrapped in Controller breaks handleChange

### ISSUE THREAD

**Issue by manualva7** [react-hook-form/react-hook-form#2433]
I'm trying to implement a Select All feature for my react-select field. I've already built this feature and it works without react-hook-form, but I can't accomplish this if the component is wrapped in Controller. I'm guessing the problem is Controller is overriding handleChange for the component inside of it. 

I've built a codesandbox with both scenarios: with controller and without controller.

https://codesandbox.io/s/gracious-flower-zu4mw?file=/src/App.js

I believe the issue could be solved if I would programmatically invoke an onChange on the Controller. I even tried to add a ref to the component, but it doesn't allow it. Any help is greatly appreciated.

**Comment by bluebill1049** [comment]
<img width="1282" alt="Screen Shot 2020-07-31 at 11 30 41 am" src="https://user-images.githubusercontent.com/10513364/88990422-45674a00-d321-11ea-8941-4c64b4e19414.png">

it's broken with your CSB.
