### ISSUE TITLE
Wrapping my react-select component with Controller breaks handleChange functionality for a Select All feature

### ISSUE THREAD

**Issue by manualva7** [react-hook-form/react-hook-form#2434]
I've managed to create some code to populate a react-select field with all the available options. It works, until I wrap it in Controller.

https://codesandbox.io/s/gracious-flower-zu4mw?file=/src/App.js

Since this method is depending on the handleChange inside the Select itself and Controller is overriding this event, it's not possible for me to do this unless I can programmatically invoke an onChange event on the Controller (it's what I believe, not sure if I can solve it like this.) 

Any help is greatly appreciated.

**Comment by bluebill1049** [comment]
you should use Controller with react-select which i believe it's working you, so what's the issue you try to solve?

**Comment by manualva7** [comment]
In the sandbox, the field wrapped inside Controller doesn't populate on clicking "Add all options" button

**Comment by bluebill1049** [comment]
can you take a look at this example codesandbox: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r see it helps.

**Comment by bluebill1049** [comment]
why are you rasing this an issue? let's continue the discussion at the discussion section.

**Comment by manualva7** [comment]
@bluebill1049 That's how you solve issues? By closing them without solution?

You have a great product and I love your help, but this is no way to deal with this.

**Comment by bluebill1049** [comment]
nope.

1. I didn't close an issue if this is an actual issue.
2. I have continued with my help in the discussion section if this is a real issue we can transfer this into an issue.

<img width="1106" alt="Screen Shot 2020-07-31 at 1 18 26 pm" src="https://user-images.githubusercontent.com/10513364/88996340-54a1c400-d330-11ea-9e71-681410516d7c.png">

**Comment by manualva7** [comment]
Yeah I didn't save that sandbox. But it works now. You can delete the first issue.

**Comment by bluebill1049** [comment]
please look at my codesandbox, your usage is wrong...
