### ISSUE TITLE
MUI Checkbox value is not updating

### ISSUE THREAD

**Issue by chetan316** [react-hook-form/react-hook-form#2435]
**Describe the bug**
When using Checkbox with MaterialUI, when I change the state of checkbox to true still it is showing the false value. Also instead of showing as boolean it is showing as string. I have faced the issue is with the latest version(6.2.0) of react-hook-form earlier it is working as expected.

**To Reproduce**
1. Check the checkbox to true
2. Click on Submit button and then check for value of checkbox.

**Codesandbox link (Required)**
It is same link shared on official docs
https://codesandbox.io/s/react-hook-form-v6-controller-24gcl?file=/src/index.jsxhttps://react-hook-form.com/api/#Controller

**Expected behavior**
The checkbox value should be true when checked and false when unchecked.

**Comment by bluebill1049** [comment]
may i know where did yo use this CSB? i will get it updated.

**Comment by chetan316** [comment]
> may i know where did yo use this CSB? i will get it updated.

Sorry, but I am not sure.
