### ISSUE TITLE
Nested values missing when submitting form, when using shouldUnregister: false

### ISSUE THREAD

**Issue by palcikaman** [react-hook-form/react-hook-form#2437]
**Describe the bug**
I'm using useForm with shouldUnregister: false, with nested values, and I only show one input at a time.
When I'm submitting the form with the first input rendered, only the first value will be in the values.
When I'm submitting the form with the second input rendered, only the second value will be in the values.
But when I'm submitting with none of the inputs rendered, all of them are in the values

**To Reproduce**
1. Go to the provided CodeSandbox example
2. Write 1 in the input.
3. Click next.
4. Write 2 in the input.
5. Click next.
6. Write 3 in the input.
7. Click Submit.
8. Check in console that only values.value3 is in the object.
9. Click next.
10. Click Submit.
11. Check in console that values has both value1, 2 and 3.

**Codesandbox link (Required)**
- [useForm](https://codesandbox.io/s/react-hook-form-basic-w6i9g?file=/src/index.js)

**Expected behavior**
Values should have value1, 2 and 3 even when an input is rendered.

**Desktop (please complete the following information):**
 - OS: Ubuntu, macOS
 - Browser: opera 70.0.3728.71, chrome 84.0.4147.105

**Comment by bluebill1049** [comment]
looks like a deep merge issue. thanks for report the bug.
