### ISSUE TITLE
Register not work with antd design inputs

### ISSUE THREAD

**Issue by Haqverdi** [react-hook-form/react-hook-form#245]
**Describe the bug**
Register function not working with antd design inputs, i tried all ways with ref, but not working.

**Comment by bluebill1049** [comment]
you have a codesandbox? i may add an example to the website soon

**Comment by Haqverdi** [comment]
Yes, i am adding link https://codesandbox.io/s/zen-dan-6zmyw
I just wanted to clarify one point, auto registration and validation does not work, you can only do manual methods, for example: 
`  const { register, watch, setValue } = useForm();

  const watchAll = watch();

  console.log(watchAll);

  // only working variant
  const onChange = e => setValue("form3", e.target.value);

  React.useEffect(() => {
    register({ name: "form3" });
  }, [register]);`

**Comment by bluebill1049** [comment]
what do you mean? I am very confused here. The link you shared has no ant design input.

**Comment by Haqverdi** [comment]
![image](https://user-images.githubusercontent.com/24776121/63495820-a65f8e80-c4d1-11e9-917f-594eda9cafe8.png)

**Comment by bluebill1049** [comment]
thanks, i am looking at it now

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/black-grass-yh9ph

looks like `watch` is not working with antd, I will raise a bug there see what's the reason for that.

**Comment by Haqverdi** [comment]
> https://codesandbox.io/s/black-grass-yh9ph
> 
> looks like `watch` is not working with antd, I will raise a bug there see what's the reason for that.

i will check, thanks for great library

**Comment by bluebill1049** [comment]
i have raised an issue there: https://github.com/ant-design/ant-design/issues/18411

**Comment by Haqverdi** [comment]
thanks for reply

**Comment by bluebill1049** [comment]
by the way, i found a workaround for now: https://codesandbox.io/s/elastic-ptolemy-cr5xz

when you using `watch` in antd, you always need to set a `value`

**Comment by Haqverdi** [comment]
i am tried it before, but in form edit mode it is problematic to set initial values and handle errors problematic too, when setValue error not cleared automatic
from one of components:
```const {
    register,
    errors,
    handleSubmit,
    setValue,
    clearError,
    watch,
  } = useForm();

  const structureWatch = watch('structure');
  const personInChargeWatch = watch('personInCharge');

  function handleFormSubmit(values) {
    createStock({
      ...values,
      lat: values.lat ? Number(values.lat).toFixed(2) : '',
      lng: values.lng ? Number(values.lng).toFixed(2) : '',
      area: values.area || '',
    });
  }
  // register inputs
  useLayoutEffect(() => {
    register({ name: 'name' }, { required: 'Bu dəyər boş olmamalıdır.' });
    register({ name: 'stockType' }, { required: 'Bu dəyər boş olmamalıdır.' });
    register({ name: 'structure' }, { required: 'Bu dəyər boş olmamalıdır.' });
    register(
      { name: 'personInCharge' },
      { required: 'Bu dəyər boş olmamalıdır.' }
    );
    register({ name: 'lat' });
    register({ name: 'lng' });
    register({ name: 'area' });
  }, []);``

and for edit hook
``
function onChange(name, value) {
    setValue(name, value);
    clearError(name);
  }

  function toggleHandle() {
    if (!editable) {
      values.forEach(item => {
        const { name, value, required = true } = item;
        register({ name }, { required });
        setValue(name, value);
      });
    } else {
      values.forEach(item => {
        const { name } = item;
        unregister(name);
      });
    }
    setState(!editable);`

**Comment by bluebill1049** [comment]
try `setValue(name, value, true);`

**Comment by Haqverdi** [comment]
additionally possible to implement the method for set complex values, example: object from api, maybe `setValue''S''`?)

**Comment by Haqverdi** [comment]
> try `setValue(name, value, true);` you can remove `clearError`. it should trigger validation after set value.

i will try, thanks)

**Comment by Haqverdi** [comment]
and impossible to set initial value, on manually register?

**Comment by bluebill1049** [comment]
you can't use `defaultValue` on the input?

for `regsitered` input, you can use the hook to initialised the default value. however, you are doing custom register, so probably not the case.
```
const { register } = useForm({
  defaultValues: {
    firstName: "bill",
    lastName: "luo",
    email: "bluebill1049@hotmail.com",
    pets: [ 'dog', 'cat' ]
  }
})
```

**Comment by Haqverdi** [comment]
this case difficult to implement when using same form for add and for edit, with add no problem, but when to try set values only after they arrived from api

**Comment by bluebill1049** [comment]
agree, if you had `ref` registered then `setValue` is the right api for the job.

**Comment by bluebill1049** [comment]
have the input `ref` registered will make things much easier by using this library

**Comment by Haqverdi** [comment]
yes when ref available and not wait data from api this library is great, thanks for your work

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/reverent-tdd-ztpd6

check out this example, the settimeout bit is like server request

**Comment by Haqverdi** [comment]
great idea, I will check, thanks a lot

**Comment by bluebill1049** [comment]
going to close this for now, unless you have other questions :)

**Comment by ilyakmet** [comment]
I really can't figure out what's going on! Where is the final solution for Ant Desig?


https://codesandbox.io/s/elastic-ptolemy-cr5xz – is 404 ERROR

**Comment by bluebill1049** [comment]
@ilyakmet have you tried use `Controller`

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#Controller

**Comment by ilyakmet** [comment]
OK @bluebill1049 

[RHFANT4](https://codesandbox.io/s/rhfant4-pzutp) - does't work
[RHFANT3](https://codesandbox.io/s/rfhant3-617f4) - work

Why?

**Comment by bluebill1049** [comment]
Obviously they made some breaking change @ilyakmet 

so after investigation: looks like it's their <Form /> component had some breaking change

https://codesandbox.io/s/rhfant4-5fu6c?file=/src/App.js

you may want to look into that.
