### ISSUE TITLE
useFieldArray: MUI TextField with ref loses its value

### ISSUE THREAD

**Issue by kayoh** [react-hook-form/react-hook-form#2452]
**Describe the bug**
useFieldArray: MUI TextField with ref loses its value.
<TextField inputRef={register} name="FirstName"/>

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-309s3
2. Click on first "DELETE" (next to "useFieldArray1")
3. Click"SUBMIT"
4. See values are missing.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-309s3

**Expected behavior**
Should keep values

**Screenshots**
<img width="861" alt="Screen Shot 2020-08-02 at 12 48 56 AM" src="https://user-images.githubusercontent.com/1515371/89118449-cc6c0d80-d45a-11ea-8018-4fecd02f18be.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#useFieldArray

i think you miss this:
<img width="943" alt="Screen Shot 2020-08-02 at 6 05 25 pm" src="https://user-images.githubusercontent.com/10513364/89118669-bf96fa80-d4ea-11ea-800b-f44e1249a8b1.png">

**Comment by kayoh** [comment]
No luck with `<TextField inputRef={register()}`

**Comment by bluebill1049** [comment]
<img width="865" alt="Screen Shot 2020-08-02 at 6 59 38 pm" src="https://user-images.githubusercontent.com/10513364/89119508-52876300-d4f2-11ea-9e7d-cb019fb9a515.png">

**Comment by kayoh** [comment]
thanks!
