### ISSUE TITLE
"Custom Hook with Resolver" example has invalid hook call error

### ISSUE THREAD

**Issue by manualva7** [react-hook-form/react-hook-form#2453]
https://codesandbox.io/s/stupefied-wilbur-ftvti?file=/src/App.js

Invalid hook call for example provided in react-hook-form documentation.

**Comment by bluebill1049** [comment]
which example?

**Comment by manualva7** [comment]
https://react-hook-form.com/advanced-usage#CustomHookwithResolver

**Comment by bluebill1049** [comment]
you need to create a form and use that custom hook inside.

**Comment by bluebill1049** [comment]
also this codesandbox s on v5 as well :( i will get it updated.

**Comment by bluebill1049** [comment]
by the way, thanks for the issue report @manualva7 perhaps next time you could follow the issue template? It will help me to sort out issue bit quicker :)

**Comment by bluebill1049** [comment]
here is a working CSB with v5: https://codesandbox.io/s/keen-saha-potl4?file=/src/App.js

**Comment by bluebill1049** [comment]
doc updated.

**Comment by manualva7** [comment]
Ok. thanks for the quick responses! I see it uses "ref={register}" so it's no good for me. We'll keep the discussion on https://github.com/react-hook-form/react-hook-form/discussions/2433#discussioncomment-45794

I'll build something on codesandbox this week and let you know what I'm thinking. I'll also let you know about all the issues I've encountered.
