### ISSUE TITLE
Custom types/classes passed into useForm get mangled

### ISSUE THREAD

**Issue by jgonera** [react-hook-form/react-hook-form#2466]
**Describe the bug**
Following advice from https://github.com/react-hook-form/react-hook-form/issues/1414 I tried using a controller to parse a string into a custom type. Unfortunately it seems that when I pass that type into `useForm` and later try to read the values in `handleSubmit`, the values are not of the same type. In the Codesandbox bellow I created a silly `Price` class with a custom getter to illustrate the problem. The getter is missing in the value passed to the `handleSubmit` callback.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-liv7m?file=/src/index.tsx:1093-1134

Wait a few seconds until `@types/react` loads and check the error on line 55. Codesandbox transpiles the code anyway but TypeScript with `strict: true` won't.

**Expected behavior**
The type of the value passed to the `handleSubmit` callback should be the same type as the one passed to `useForm`

**Comment by bluebill1049** [comment]
Don't type we support Class at the moment.

**Comment by kotarella1110** [comment]
@jgonera You can use `NestedValue` type.

```ts
interface FormData {
  FirstName: string;
  price: NestedValue<Price>;
}
```

CSB: https://codesandbox.io/s/react-hook-form-useform-template-5j08u

**Comment by jgonera** [comment]
Thank you! Is this gonna work in future or is just a coincidence resulting from the current implementation of `NestedValue`? If it's the former, should `NestedValue` be renamed to something broader (it wouldn't occur to me to try it out in this case just by looking at https://react-hook-form.com/ts#NestedValue)?

**Comment by bluebill1049** [comment]
What would be your suggestion?

**Comment by bluebill1049** [comment]
closing, you can leave your suggestion here.

**Comment by jgonera** [comment]
Maybe `ComplexValue` or something like that (I was looking for something opposite to a "primitive type")? "Complex" can sound kind of vague but I can't think of anything better. Maybe just add a note in https://react-hook-form.com/ts/#NestedValue for now saying that it can be also used for classes?

**Comment by bluebill1049** [comment]
would you like to send a PR for the doc @jgonera to have some improvement and clarification?

**Comment by jgonera** [comment]
I tried using this a bit more and the problem is that I have to duplicate types that I use elsewhere in the part of the code base that is not aware of `react-hook-form`. So for example I have an interface like this:

```typescript
interface Transaction {
  price: Decimal;
  quantity: Decimal;
}
```

And I can't use that type in `useForm`. I have to create a new type like this:

```typescript
interface TransactionFormData {
  price: NestedValue<Decimal>;
  quantity: NestedValue<Decimal>;
}
```

It's not a deal-breaker but an inconvenience. I suppose there's no way around it?

**Comment by kotarella1110** [comment]
@jgonera Sorry, you need to define a new type with `NestedValue` type if `Decimal` type is array or object.
Is `Decimal` type a Class?
For Classes, I can fix it so that you can define the type without using NestedValue.

**Comment by jgonera** [comment]
Yes, `Decimal` is a class. It would be really awesome if I could use it without `NestedValue`!

**Comment by jgonera** [comment]
Is there any way I could help with this?

**Comment by kotarella1110** [comment]
@jgonera Do you know how to determine a Class type by conditional type?
If it is possible then this issue can be solved.

https://twitter.com/kotarella1110/status/1291661194546176000

**Comment by jgonera** [comment]
Maybe another way would be to replace https://github.com/react-hook-form/react-hook-form/blob/90d03bc037e3b5f34b6a46df07b0bc8f100c6443/src/types/form.ts#L37 with `NonUndefined<T> extends Record<string, unknown>`?

**Comment by kotarella1110** [comment]
@jgonera Awesome! I will fix 👍

**Comment by cesarenaldi** [comment]
> @jgonera Do you know how to determine a Class type by conditional type? If it is possible then this issue can be solved.
> 
> https://twitter.com/kotarella1110/status/1291661194546176000

I've been having issues around this and custom types being mangled by the `NestedValue` during unpacking.

An alternative version of `UnpackNestedValue` could determine if an object is "constructable".

```ts
type Constructable = new (...args: any[]) => any;

type UnknownObject = Record<string, unknown>;

type UnpackNestedValue<T> = T extends Constructable
  ? T
  : T extends UnknownObject
  ? {
      [K in keyof T]: UnpackNestedValue<T[K]>;
    }
  : T;
```

For context at the time I am writing this (i.e. `react-hook-form@7.21.0`) `UnpackNestedValue` is defined as:
```ts
type UnpackNestedValue<T> = T extends NestedValue<infer U>
  ? U
  : T extends Date | FileList | File
  ? T
  : T extends object
  ? {
      [K in keyof T]: UnpackNestedValue<T[K]>;
    }
  : T;
```

Thoughts?
