### ISSUE TITLE
`watch` is not returning correct values with `defaultValue` argument provided

### ISSUE THREAD

**Issue by SatoAV** [react-hook-form/react-hook-form#2472]
**Describe the bug**
I have a checkbox-type component in my multi-step form, which uses `reset(values)` to restore the form state from higher-order state.
Inside a checkbox component I use `watch('name', false)` to trigger some effects when checkbox is changed.

If I reset the form with values from state, where my value is `true`, `watch` still returns `false`.
If I remove default value, then the value returned updates correctly, but this causes issues in my effects, so I still need this default value to be set.

I upgraded to v6.3.0, but it didn't change anything

**To Reproduce**
1. Open the sandbox below
2. Checkbox is checked by default. Notice that `watch` with default value returns false
3. When you check/uncheck the checkbox, both values get synchronized
4. If you then press the `Reset` button, you will see, that `watch` with default value returns wrong value again.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-gzmmu

**Expected behavior**
`watch` return values should be in sync with and without the `defaultValue`, when the value is set in the form.

**Comment by bluebill1049** [comment]
This is expected behavior, `watch` is called prior to the render, so it can't read what's in the render phase, that's why we had the defaultValue argument.

**Comment by SatoAV** [comment]
> This is expected behavior, watch is called prior to the render, so it can't read what's in the render phase, that's why we had the defaultValue argument.

Yes, that is clear, however, it doesn't get updated with the real value on consecutive renders.

**Comment by bluebill1049** [comment]
> Yes, that is clear, however, it doesn't get updated with the real value on consecutive renders.

<img width="635" alt="Screen Shot 2020-08-05 at 6 55 53 pm" src="https://user-images.githubusercontent.com/10513364/89392755-4b0fc600-d74d-11ea-8f40-ad6e31f12c18.png">
<img width="659" alt="Screen Shot 2020-08-05 at 6 55 50 pm" src="https://user-images.githubusercontent.com/10513364/89392776-519e3d80-d74d-11ea-8234-6af3e46bbb56.png">

**Comment by SatoAV** [comment]
My bad, disregard what I said about consecutive renders. The problem only occurs on initial renders, but still if my `defaultValues` are set, I'm expecting `watch` to return the already set default value from the form.

**Comment by bluebill1049** [comment]
<img width="1111" alt="Screen Shot 2020-08-05 at 9 09 23 pm" src="https://user-images.githubusercontent.com/10513364/89406081-f1fd5d80-d75f-11ea-860e-b027aaf686a1.png">

it's working as expected as well.

**Comment by Redskinsjo** [comment]
I have same error for defaultValues not returned by watch() on first render

**Comment by festusyuma** [comment]
Please Has anyone been able to solve this. I see this in the docs for setting a default value with watch, but when I try to do this, the default value gets ovewritten with undefined

![image](https://user-images.githubusercontent.com/15335292/187095560-a8dd37f3-2308-4091-85a7-11592247f00f.png)
![image](https://user-images.githubusercontent.com/15335292/187095566-d5671f94-28b9-4405-8919-563f179c7ab3.png)
![image](https://user-images.githubusercontent.com/15335292/187095580-07ab0bae-14a0-4d95-9e0a-93cd63587c0f.png)
