### ISSUE TITLE
Invalid React-Select fields don't focus on error

### ISSUE THREAD

**Issue by manualva7** [react-hook-form/react-hook-form#2475]
react-hook-form doesn't focus on react-select fields on error like it does with the other simple fields.

1. Go to https://codesandbox.io/s/elegant-silence-osn90?file=/src/App.js
2. Make sure all fields are empty. 
3. Click on submit.

The react-select field should be focused first. It doesn't even focus on error if you fill the other simple fields.

![Screen Shot 2020-08-04 at 12 59 57 PM](https://user-images.githubusercontent.com/41272874/89339124-7f528c00-d652-11ea-8da9-53d06eb0159e.png)
![Screen Shot 2020-08-04 at 1 00 05 PM](https://user-images.githubusercontent.com/41272874/89339120-7e215f00-d652-11ea-9684-61baf0d5b6ed.png)

Desktop:
macOS Mojave v 10.14.6

Browser:
Chrome v 84.0.4147.105

**Comment by bluebill1049** [comment]
This is not a bug and an issue with react hook form, react-select doesn't export `ref`. in order to focus it, you will need to use Controller's `onFocus` prop, basically, hook up the on focus behavior.

**Comment by manualva7** [comment]
@bluebill1049 

This has got to be new. react-selects are now focusable. I've searched this a few months back. 
https://react-select.com/advanced#accessing-internals

Just food for thought. If you'd like we can move this to discussions.

**Comment by bluebill1049** [comment]
@manualva7 we can continue the chat here no worries :) 

you just need to the following for react-select: https://codesandbox.io/s/react-hook-form-controllerautofocus-v6-eeo66 just wire up the onFocus prop in Controller 👍 let me know if this make sense.

**Comment by sepruda** [comment]
Looks like the `onFocus` prop on Controller has been removed, is there a new recommendation to make this work with `react-select`?

**Comment by bluebill1049** [comment]
> Looks like the `onFocus` prop on Controller has been removed, is there a new recommendation to make this work with `react-select`?

the `ref` is part of the field `object` now.
