### ISSUE TITLE
Keys (field names) in object returned by useWatch out of sync with fieldArray item indexes after performing swap, move, deletion etc

### ISSUE THREAD

**Issue by moofoo** [react-hook-form/react-hook-form#2476]
**Describe the bug**
Using useWatch on fields in a fieldArray, and useWatch is passed an array of names, so it's returning an object with the name paths as keys. The object's keys become out of sync with the fieldArray item indexes after performing swap, move, deletion operations.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-itdtt?file=/src/index.js
2. Open up console to see logs
3. Click swap
4. See error on page, and look in the log

**Expected behavior**
Object returned by useWatch should have correct keys (name paths) as per the item indexes of the fieldArray.

**Additional context**

This is kind of a hard to describe bug, so maybe pictures will help.

The example has two fields in a field array:
* A text input (Input), which is using useWatch to monitor...
* A checkbox input (RenderInput), which controls whether Input is rendered

When the page initially loads, it looks like this:
![fieldArray1](https://user-images.githubusercontent.com/13556/89342058-da42ae00-d667-11ea-9c3b-270fa9200c6b.png)

With this output in the console log:
![fieldArray3](https://user-images.githubusercontent.com/13556/89342099-e9296080-d667-11ea-8816-a987c9f675eb.png)

After clicking swap, the page looks like this, showing the problem - even though RenderInput is still checked for the top two swapped items, the Input fields are hidden (haven't been rendered), meaning they aren't reading the value of their respective RenderInput checkboxes correctly.
![fieldArray2](https://user-images.githubusercontent.com/13556/89342124-f34b5f00-d667-11ea-8556-4c09e27c3324.png)

With this in the console log, showing that the keys of the useWatch object are out of sync:
![fieldArray4](https://user-images.githubusercontent.com/13556/89342159-ffcfb780-d667-11ea-8cbb-4dd0b29f2336.png)

Note that 'watchedName' is what is being passed for 'name' to useWatch. So after the swap operation, even though 'test[0].renderInput' is being passed to useWatch, the object it returns has 'test[1].renderInput' for the key, which is obviously not right.

**Comment by bluebill1049** [comment]
I am confused with this example... I will try to reproduce this issue in my own codesandbox.

**Comment by bluebill1049** [comment]
Could you take a look at this codesandbox: https://codesandbox.io/s/react-hook-form-usefieldarray-tm9gh?file=/src/index.js? see if you can reproduce this issue?

**Comment by moofoo** [comment]
I think your codesandbox also shows the issue. 

I created a fork of yours with some minor changes (putting field indexes as the input texts and logging the render count) that make it easier to see whats going on: https://codesandbox.io/s/react-hook-form-usefieldarray-7kg3s?file=/src/index.js

Here is what the log shows after appending two items, everything is as it should be. That is, when 'test[0].firstname' is passed to useWatch, the object it returns has 'test[0].firstname' as the key, and so on for the others:
![example1](https://user-images.githubusercontent.com/13556/89369389-966d9a00-d6a3-11ea-91bd-6b5ec3055e7a.png)

And here's the log after hitting swap:
![example2](https://user-images.githubusercontent.com/13556/89369398-9e2d3e80-d6a3-11ea-89d2-393b1b9e12cf.png)

So you can see that for the swapped items, the passed in name and the key in the object returned by useWatch no longer match up. So you have ''test[1].firstName' passed to useWatch, but the object it returns has 'test[2].firstName' as they key, and similarly the useWatch call with 'test[2].firstName' for name returns an object with 'test[1].firstName' as the key. 

Note that the values returned by use watch are correct...just the keys are wrong. That is, you have useWatch returning an object, after the swap, with  'test[2].firstName' as the key and 3 as the value, but test[2].firstName does not actually equal 3, its value is 2.

Just talking about this behavior makes my head hurt! I hope that helps you understand the problem.

**Comment by bluebill1049** [comment]
> Just talking about this behavior makes my head hurt! I hope that helps you understand the problem.

I appreciated your detailed comment and the issue is when you watching an `array` of fields, but with above... it hurts your head, then you should go see a doctor because my head would be exploded try to investigate and resolve the issue...

**Comment by bluebill1049** [comment]
ok, this one did kill some of my brain cells...

TDLR:
use `useWatch({ name: 'test' })` to watch the entire Field Array.

https://codesandbox.io/s/react-hook-form-usefieldarray-tm9gh?file=/src/index.js

**Conclusion:**

Why this is happening, because you are watching specific array input, the problem is they never get unmounted during swap/move, and after input switch position or swap, their position gets updated, however, the reference still remains to be the old one, even though the name is updated each re-render. so if you want to watch the inputs when swap/move, it's safer and correct to watch the entire `FieldArray`.

**Comment by moofoo** [comment]
Ok, good to know. 

That won't work as a solution for my particular app, but I did make a workaround which seems to do the trick:

```
const watched = {};
const useWatchValues = Object.values(useWatch({ name: toWatch })); //toWatch is an array of field names
toWatch.forEach((name, index) => {
watched[name] = useWatchValues[index];
});
```

This ensures that the final 'watched' object has keys that match with the names in 'toWatch', which is needed in my app.

I thought that this wouldn't work initially because I believed object properties weren't in a reliable order, but apparently that's not true! [Property order is predictable in JavaScript objects since ES2015](https://www.stefanjudis.com/today-i-learned/property-order-is-predictable-in-javascript-objects-since-es2015/). Learn something new everyday!

Thank you for taking the time to work on this problem!

**Comment by bluebill1049** [comment]
awesome! glad that you find an alternative solution.
