### ISSUE TITLE
Behavior of formState is different when running on react native app vs when running on jest test

### ISSUE THREAD

**Issue by tingzhouu** [react-hook-form/react-hook-form#2479]
**Describe the bug**
Behavior of `formState` is different when running on react native app vs when running on jest test. Reproduced in version `6.3.0`.

**To Reproduce**
1. Create a React Native project.
2. Install `react-hook-form`, `@testing-library/react-native`, and `@testing-library/jest-native`.
3. Copy [example form implementation](https://www.react-hook-form.com/get-started/#ReactNative) into `App.js`.
4. Change `useForm` to use `onChange` mode. 
```
const {control, handleSubmit, errors, formState} = useForm({
  mode: 'onChange',
});
```
5. Add `<Text>` to display current form state.
```
<Text>
  {formState.isValid ? 'formState: "Valid"' : 'formState: "Invalid"'}
</Text>
```
6. Disable `<Button>` if formState is not valid
```
<Button
  disabled={!formState.isValid}
  accessibilityLabel="Submit Button"
  title="Submit"
  onPress={handleSubmit(onSubmit)}
/>
```
7. Replace `__tests__/App-test.js` with the below snippet.
```
import React from 'react';
import {render} from '@testing-library/react-native';
import App from '../App';

describe('checking formState.isValid', () => {
  it('should initialize with an invalid state', () => {
    const {getByText} = render(<App />);
    getByText('formState: "Invalid"');
  });

  it('should have a disabled submit button', () => {
    const {getByA11yLabel} = render(<App />);
    const submitButton = getByA11yLabel('Submit Button');
    expect(submitButton).toBeDisabled();
  });
});

```
5. Run test `yarn test`

**Github link**
As I encountered this issue in a React Native project, I'm providing a [link to the template repo](https://github.com/tingzhouu/rhf-formState-issue) created to reproduce the error.

**Expected behavior**
Both app and jest test should start off with `formState.isValid` as `false`. However, jest test starts off with `formState.isValid` as `true`.

**Screenshots**
Below is what happens in the react native app
![formState demo](https://user-images.githubusercontent.com/33824745/89371529-36640b80-d716-11ea-8b13-57fb324a4ceb.gif)

Below is what happens in the jest test
<img width="776" alt="formState test" src="https://user-images.githubusercontent.com/33824745/89371575-5f849c00-d716-11ea-9d54-8fe7dd296af9.png">

**Desktop (please complete the following information):**
- N/A as this is an issue in React Native

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max Simulator
 - OS: iOS 13.6

**Comment by bluebill1049** [comment]
Thanks for the very detailed issue report! This really helps. I will take a closer look tonight. 

FYI there will be a difference with `Proxy` in web.

isVaild is started from `true` because RHF is uncontrolled, and value can get validated at render phase.

**Comment by tingzhouu** [comment]
Welcome! As a FYI, I'm currently using version `6.0.1` in my own project where the tests are still passing. The tests started failing after I tried to upgrade.

This wasn't included it in the issue report as the tests would fail when using version `6.0.1` in the template repo.

**Comment by bluebill1049** [comment]
hey @keiya01 would you be able to help on this one while I am investigating the other bug? 🙏

**Comment by keiya01** [comment]
I think this issue is caused by async function. We are updating `formState.isValid` by async function. Therefore you should wrap `getByText` with `wait` method in `@testing-library/react-native`.  (link: https://www.native-testing-library.com/docs/api-async)

**Comment by tingzhouu** [comment]
Thank you for your time! I went to try out the proposed solution, referencing [this](https://callstack.github.io/react-native-testing-library/docs/api/#waitfor). Code snippet below.

```
it('should initialize with an invalid state', async () => {
  const {getByText} = render(<App />);

  // i'm not sure if doing this 1 second pause changes anything
  await new Promise((resolve) =>
    setTimeout(() => {
      resolve();
    }, 1000),
  );

  await waitFor(() => getByText('formState: "Invalid"'));
});
```

Unfortunately it still did not work, and I tried debugging the issue.

When running in app, the function `useForm` was called **twice** when using `mode: 'onChange'`. This suggests that the component re-renders once after mounting.

However, when running in jest test, `useForm` was only called **once**. Referencing [useForm](https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts), this is what's happening:

|   Render No.   |   validFieldsRef.current.size   |   fieldsWithValidationRef.current.size   |   isValidRef.current
|:----------:|:-------------:|:------:|:------:|
|   1   |   0   |   0   |   true   |
|   2   |   0   |   2 (because there are 2 fields)   |   false   |

```
if (!resolver) {
    isValidRef.current =
        validFieldsRef.current.size >= fieldsWithValidationRef.current.size &&
            isEmptyObject(errorsRef.current);
}
const formState = {
    ...
    isValid: isOnSubmit
        ? isSubmittedRef.current && isEmptyObject(errorsRef.current)
        : isValidRef.current,
};
```

At this point I'm stuck 😓 Anyone able to provide guidance on how to move forward?

**Comment by keiya01** [comment]
Is the following code used in App component as well ? 

```js
await new Promise((resolve) =>
  setTimeout(() => {
    resolve();
  }, 1000),
);
```

If you are using this, you can write test bellow.

```js
it('do something', () => {
  /* do something */

  jest.useFakeTimers();

  new Promise((resolve) =>
    setTimeout(() => {
      resolve();
    }, 1000),
  );

  jest.runOnlyPendingTimers();

  /* do something */
})
```

> When running in app, the function useForm was called twice when using mode: 'onChange'. This suggests that the component re-renders once after mounting.

`formState.isValid` is updated when input element is registered. Therefore first render is mounted component, second render is updated `formState.isValid`.

> However, when running in jest test, useForm was only called once.

Updating state need to be executed in `act`'s callback. And `formState.isValid` is updated by async function. That is, this problem is caused by updating state when waiting for finishing `Promise`.

**Comment by tingzhouu** [comment]
No, there's no `setTimeout` function used in [`<App />`](https://github.com/tingzhouu/rhf-formState-issue/blob/master/App.js). 

Below is my current test, where it waits a few seconds, then times out. The re-render doesn't occur.

```javascript
import React from 'react';
import App from '../App';

import {render, waitFor} from '@testing-library/react-native';

describe('checking formState.isValid', () => {
  it('should initialize with an invalid state', async () => {
    const {getByText} = render(<App />);
    await waitFor(() => getByText('formState: "Invalid"'));
  });
});
```

**Comment by keiya01** [comment]
Hmm, I have been success in my environment ...

**Comment by keiya01** [comment]
I understand. Probably this issue is caused by `window` object is undefined. We are checking if `window` is defined before field is registered.(https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L915)

We have solved similar [issue](https://github.com/react-hook-form/react-hook-form/discussions/2168). This issue might be helpful for you.

**Comment by tingzhouu** [comment]
It works now 🎉🎉🎉 My apologies for missing out on the documentation.

For anyone who comes across this, add `setup.js` in the root directory with the following snippet:

```
global.window = {};
global.window = global;
```

add `"<rootDir>/setup.js"` to `package.json` like this:
```
"jest": {
  "preset": "react-native",
  "setupFilesAfterEnv": [
    "@testing-library/jest-native/extend-expect",
    "<rootDir>/setup.js"
  ]
}
```

Have updated the [repo](https://github.com/tingzhouu/rhf-formState-issue) with the changes as well.

Thank you @keiya01 for your help!
