### ISSUE TITLE
Ability to check if a form is valid without having to display the errors/feedback on the UI

### ISSUE THREAD

**Issue by Chandu** [react-hook-form/react-hook-form#2481]
**Is your feature request related to a problem? Please describe.**
I use `trigger` method of the USeFormMethods to validate/identify if the form is valid or not.
This also updates the UI to display error messages/feedback on the form.
However there could be use cases where we just need to know if the form is valid or not without displaying any feedback/errors. (e.g: displaying form for the first time with pre-populated data from external source etc.) 

**Describe the solution you'd like**
The trigger method (or a net new method) can provide an option to let the developers specify if they want to display UI errors/feedback when the trigger is called with a default value to true for backward compatibility
For e.g. in the example @ the Codesandbox (linked below) when I press Validate button (in a practical scenario this need not be a user triggered event) the input box displayed the red border as it is invalid. Instead I would like to check if the if the form is valid/invalid without really displaying any errors.
 https://codesandbox.io/s/hopeful-water-1v6y9

**Describe alternatives you've considered**
One alernative I have used is to use the yup validator schema to check if the form data is valid using the `getValues` to get the model and then validate.
But since I am already configuring the RHF with my validator I think the way I am managing it now seems to be redudant/unnecessary code.

**Comment by bluebill1049** [comment]
I think it's probably easier to use `getValues()` and validate against your schema.

**Comment by Chandu** [comment]
@bluebill1049  Ok. Thanks.
