### ISSUE TITLE
react-hook-form/dist/index.ie11 needs polyfills

### ISSUE THREAD

**Issue by yhor1e** [react-hook-form/react-hook-form#2488]
**Describe the bug**

The `react-hook-form/dist/index.ie11` needs polyfills.
But according to #2468, `react-hook-form/dist/index.ie11` doesn't need polyfills.

> hmmm strange, ie11 build should work without other polyfills.

https://github.com/react-hook-form/react-hook-form/discussions/2468#discussioncomment-46369

**To Reproduce**
1. Go to 'https://yhor1e.github.io/sandbox-react-hook-form/current/' using Internet Explorer 11.
2. See errors on Developer Tools Console.

**Codesandbox link (Required)**
It seems Codesandbox doesn't work in Internet Explorer 11. 
So I reproduced in my repository.
* https://yhor1e.github.io/sandbox-react-hook-form/current/
* https://github.com/yhor1e/sandbox-react-hook-form

**Expected behavior**
The `react-hook-form/dist/index.ie11` works without polyfills.

**Screenshots**
![スクリーンショット 2020-08-06 2 51 38](https://user-images.githubusercontent.com/10266230/89447303-ba5ad980-d790-11ea-8667-0dac10934271.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Internet Explorer
 - Version 11

**Comment by bluebill1049** [comment]
merged will be released soon.

**Comment by bluebill1049** [comment]
hey @yhor1e the solution didn't work :( if you have any insight please assist, for now i will revert that change :(

**Comment by yhor1e** [comment]
@bluebill1049 

Sorry, I didn't notice this comment.
My opinion is as I've written in https://github.com/react-hook-form/react-hook-form/pull/2542#issuecomment-671662784.
