### ISSUE TITLE
useEffect callback doesn't gets triggered on errors change

### ISSUE THREAD

**Issue by afzaalahmad** [react-hook-form/react-hook-form#2490]
**Describe the bug**
useEffect with errors in the dependency array doesn't gets invoked with mode onChange.

**To Reproduce**
1. put errors in the dependency array of useEffect and log the errors inside

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-7olxo

**Expected behavior**
useEffect callback should get invoked whenever errors variable value changes.

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser: chrome
 - Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by bluebill1049** [comment]
`errors` should use them in the render, they don't need to go through `useEffect`. if you need to check certain errors you can do it without useEffect, it's expected behavior.

**Comment by afzaalahmad** [comment]
@bluebill1049 I have a controller form, and I pass errors through callback to the parent, that's why I need to put useEffect on the errors and pass the error value back to parent? So, solution to this problem?

**Comment by bluebill1049** [comment]
> @bluebill1049 I have a controlled form, and I pass errors through callback to the parent, that's why I need to put useEffect on the errors and pass the error value back to parent? So, solution to this problem?

happy to assist, do you have a codesandbox for the above use case?

**Comment by afzaalahmad** [comment]
@bluebill1049 here is the codesandbox https://codesandbox.io/s/react-hook-form-useform-template-7olxo
I need to pass the errors back to parent every errors object changes on the event `onChange`. useEffect runs on submit but not onChange.

**Comment by bluebill1049** [comment]
what about move `useForm` to your `parent` that would solve the problem right?

**Comment by afzaalahmad** [comment]
Actually I have three different forms under one parent without any button on all of them, so I used useFrom in three childs and pass errors of all forms to parents.

**Comment by bluebill1049** [comment]
you can use a state machine (redux) to pass into context, that should work.
```
<Context>
  <Form1>
  <Form2>
</Context>
```

store errors in the context.

**Comment by bluebill1049** [comment]
hey @afzaalahmad i found something cool today, this may works for you as well: https://github.com/theKashey/use-callback-ref

**Comment by afzaalahmad** [comment]
@bluebill1049 Thanks a lot for your effort. I really appreciate it. Though I did it using your first suggestion that is moving the form to the parent. I have looked into your suggested package, and its really cool :+1:
