### ISSUE TITLE
RFC: async defaultValues

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#2492]
## Summary

The current status of setting `defaultValues` from async data source is using `reset`:

```ts
useEffect(() => {
  reset({
     firstName: 'test',
  })
});
```

honestly, this is probably not a pretty and clean approach... a few weeks before we had a feature request regarding async `defaultValues`: https://github.com/react-hook-form/react-hook-form/issues/2335

## Proposal Solutions

1. `defaultValues` accept `Promise`, and promise will get resolve **after** `useEffect`, although I do the confusion with prop support both `object` and `Promise`.

```ts
useForm({
  defaultValues: async () => ({ firstName: 'test' })
  // defaultValues: new Promise()
})
```

happy to discuss more options on the table too.

**Comment by JeromeDeLeon** [comment]
With `async defaultValues`, we are expecting it to do any asynchronous task right? So what if you rely on something else to trigger the `defaultValues` fetching? Like props? How would would I do that? Still I would need to rely to this `reset` + `useEffect` convention. Correct me if I'm wrong with all my understanding because that's how I see it. It really feels to me that I would still need to comeback to that approach.

**Comment by pmaier983** [comment]
I think this is a great idea. During my day job we work with large data sets, and we have specific queries to get available data for dropdown fields. If this was implemented it would pave the way to have a loading indicator and then some dropdown field all built without a Controller. 

The Async Promise seems like the best way forward (to me).

**Comment by bluebill1049** [comment]
Thanks @JeromeDeLeon I think you can pass arguments into that Promise callback.
```
useForm({
  defaultValues: async (args) => {
    if (args.test) { return { data: 'test' }; }
  }
})
```

**Comment by JeromeDeLeon** [comment]
Got it so its's not just about the API or anything. That makes sense at least to that part 😃

**Comment by adhrinae** [comment]
Do we need to provide another state like `isDefaultValueLoading`? Because for the first time users cannot see default values until that promise is resolved.

**Comment by bluebill1049** [comment]
> Do we need to provide another state like `isDefaultValueLoading`? Because for the first time users cannot see default values until that promise is resolved.

Good point probably will leave the user to define that state. `isLoading`.

`useState(false)`

**Comment by kotarella1110** [comment]
> > Do we need to provide another state like `isDefaultValueLoading`? Because for the first time users cannot see default values until that promise is resolved.
> 
> Good point probably will leave the user to define that state. `isLoading`.
> 
> `useState(false)`

I don't think the user can set the isLoading state.

```ts
useForm({
  defaultValues: async () => {
    const result = await fetch("xxxxx").then(res => res.json());
    return result;
  }
})
```

**Comment by JeromeDeLeon** [comment]
You mean let the user define `useState` every time they will use `async defaulValues`? I think we should leverage that for users. just my opinion instead of letting the users define it every time

**Comment by keiya01** [comment]
```js
useForm({
  defaultValues: async (args) => {
    if (args.test) { return { data: 'test' }; }
  }
})
```

I think async function is invoked every render. By rendering, a lot of extra process is occurred.
Therefore I think we should provide other function that can invoke in `useEffect()`.

**Comment by JeromeDeLeon** [comment]
unless we wrapped it inside `useRef`, am I right @kotarella1110 ?

**Comment by kotarella1110** [comment]
> > Do we need to provide another state like `isDefaultValueLoading`? Because for the first time users cannot see default values until that promise is resolved.
> 
> Good point probably will leave the user to define that state. `isLoading`.
> 
> `useState(false)`

Is it possible to do the following?

```ts
useForm({
  defaultValues: async () => {
    const result = await fetch("xxxxx").then(res => res.json());
    return result;
  }
})
```

**Comment by JeromeDeLeon** [comment]
That's my question earlier, because what if you rely on something like `fetchById`?

**Comment by bluebill1049** [comment]
You can still display your form, and wait for the promise to resolved and inject to all the inputs. if you need to show a loading spinner. you can just do a `useState`.

**Comment by bluebill1049** [comment]
```
useForm({
  defaultValues: async () => {
    updateLoading(false)
    const result = await fetch("xxxxx").then(res => res.json());
    updateLoading(true)
    return result;
  }
})
```
that works?

**Comment by bluebill1049** [comment]
I guess `callback` is just one solution, open to better options.

**Comment by keiya01** [comment]
Does this case work ?

```
useForm({
  defaultValues: {
    test: async (args) => 'test'
  }
})
```

**Comment by JeromeDeLeon** [comment]
```js
const [isLoading, setLoading] = useState(false);

useEffect(() => {
  async function asyncFetch() {
    setLoading(false);
    const result = await fetch(`xxxxx/${id}`).then(res => res.json());
    setLoading(true);
    reset(result);
  }

  asyncFetch();
}, [reset, id]);
```

Isn't it the same as the one above?

**Comment by bluebill1049** [comment]
Take a look at this issue https://github.com/react-hook-form/react-hook-form/issues/2333 @JeromeDeLeon I think you will have some context.

**Comment by JeromeDeLeon** [comment]
Sure. Thanks @bluebill1049 sorry for just popping out my opinion and all.

**Comment by bluebill1049** [comment]
not at all @JeromeDeLeon 👍

**Comment by bluebill1049** [comment]
> Does this case work ?
> 
> ```
> useForm({
>   defaultValues: {
>     test: async (args) => 'test'
>   }
> })
> ```

That works too :) I think would be good to solve a form level, individual input can be solved by `setValue`.

**Comment by keiya01** [comment]
I think we should provide `setDefaultValues` method because callback solution make it complex when it is bellow 🤔

```js
useForm({
  defaultValues: {
    test: async (args) => {
      if (args.test) { 
        return { 
          data: 'test', 
          test:  {
            value: 'value'
          };
        } 
      }
      // ... some value or callback
    }
})
```

**Comment by bluebill1049** [comment]
or make `reset` API works with suspense: https://github.com/react-hook-form/react-hook-form/issues/2333

**Comment by JeromeDeLeon** [comment]
Is it not possible to work `setValue` and `reset` with `Suspense`?

**Comment by JeromeDeLeon** [comment]
> or make `reset` API works with suspense: #2333

:laughing: I didn't see this

**Comment by bluebill1049** [comment]
This: https://codesandbox.io/s/currying-cloud-d8e9f?file=/src/App.js

**Comment by smashercosmo** [comment]
I would just prefer form to always reinitialise when defaultValues change. Fetching default values asynchronously when initialising the form is less common scenario, than just using props.

This is more common
```js
function EditUser(props) {
  const { user } = props
  const form = useForm({ defaultValues: user })
}
```

than
```js
function EditUser(props) {
  const { userId } = props
  const form = useForm({ defaultValues: async () =>  fetch(`/api/user/${userId}`)})
}
```

**Comment by bluebill1049** [comment]
Hey, @smashercosmo that's how I designed when hook form started, however this doesn't work well with 

```
function EditUser(props) {
  const { user } = props
  const form = useForm({ defaultValues: { pureObject: 'xxx' } })
}
```

unless user is willing to `memo` their `defaultValues` (which is not great DX), otherwise react dep check is always going to fail and each re-render will result in update value again.

**Comment by bluebill1049** [comment]
I think we can conclude `const form = useForm({ defaultValues: async () =>  fetch(`/api/user/${userId}`)})` is not great solution :(

**Comment by smashercosmo** [comment]
> otherwise react dep check is always going to fail and each re-render will result in update value again

And what's exactly bad about it?

**Comment by bluebill1049** [comment]
It's not Controller form, `defaultValues` is meant to set up the initial form. If every renders update input values, it defeats the purpose.

**Comment by smashercosmo** [comment]
Maybe we could introduce another property - "values"? so "defaultValues" will still be memoized and "values" will reinit the form every time it changes?

**Comment by bluebill1049** [comment]
Thanks @smashercosmo that's one potential solution as well.

**Comment by adhrinae** [comment]
> Maybe we could introduce another property - "values"? so "defaultValues" will still be memoized and "values" will reinit the form every time it changes? 

Sounds like his suggestion is dropping the advantage of uncontrolled component, but we can provide the option that our users can choose. 🙂

**Comment by bluebill1049** [comment]
I think we will keep this issue open for another week and gather all the input and feedback for the feature request. Probably will not be worked on right away.

**Comment by bluebill1049** [comment]
another option and i think it's a better one.

```ts
const values = useMemo(() => values, [values]) // user will have to memo this values,

useForm({
  values,
})
```

internally we will check values gets changes

```
useEffect(() => {
  reset(values)
}, [values])
```

**Comment by zulaica** [comment]
Just commenting to say I would _love_ something to be implemented here. I just ran into issues with this today. 😅

**Comment by dfyz011** [comment]
Such a pain to work with big forms in React, waiting for some good approach. Thank you

**Comment by bluebill1049** [comment]
> Such a pain to work with big forms in React, waiting for some good approach. Thank you

what do you mean "such a pain"?

```
useEffect(() => {
  reseet(values)
}. [values])
```

if this is pain, seriously I don't know what you are working on... even when we introduce `value` purpose which i stated above, internally it will just do above and yes you will have to memo that `value`.

**Comment by bluebill1049** [comment]
> Such a pain to work with big forms in React, waiting for some good approach. Thank you

sorry, I think I miss read your message. I think what I purposed above is most likely going to be, and you will have to memorize `values`.

**Comment by jhonattansolartearanda** [comment]
This code in React Native, dont work.


`const {control, handleSubmit, errors} = useForm({
    defaultValues: async () => {
      return await prefsManager.getValue(enumerator.Url);
    },
  });`

**Comment by jhonattansolartearanda** [comment]
This code in React Native, dont work.

``  
const {control, handleSubmit, errors} = useForm(
{    defaultValues: async () => {
      return await prefsManager.getValue(enumerator.Url);
    },
  });
``

**Comment by bluebill1049** [comment]
> This code in React Native, dont work.
> 
> `const {control, handleSubmit, errors} = useForm({ defaultValues: async () => { return await prefsManager.getValue(enumerator.Url); }, });`

there is no such feature in the lib at the moment.

**Comment by vivek1996** [comment]
> another option and i think it's a better one.
> 
> ```ts
> useForm({
>   values: useMemo(() => values, [values]),
> })
> ```
> 
> internally we will check values gets changes
> 
> ```ts
> useEffect(() => {
>   reset(values)
> }, [values])
> ```


Hi, 
Thanks for the awesome library. 
So, this is the solution for setting the default values on async request?

**Comment by bluebill1049** [comment]
@vivek1996 right now yes, useEffect with reset

**Comment by beeirl** [comment]
@bluebill1049 I tried your suggested approach and called `reset()` in `useEffect` when I receive the async defaultValues. But this results in an infinite loop of `useEffect` for some reason. I've created a [minimalistic example](https://codesandbox.io/s/react-hook-form-get-started-forked-eoett?file=/src/index.js) to illustrate whats going on (in the example I don't use any type of async data, but the error stays the same)

**Comment by guicovred** [comment]
> another option and i think it's a better one.
> 
> ```ts
> useForm({
>   values: useMemo(() => values, [values]),
> })
> ```
> 
> internally we will check values gets changes
> 
> ```ts
> useEffect(() => {
>   reset(values)
> }, [values])
> ```

as I understand it, then 'values' would be just one more prop to pass, right?

I may be mixing things up, but for me it would make a lot of sense to get 'default values' asynchronously, it could have a `formState.isLoading` or something, (just like with `form.handleSubmit` & `formState.isSubmitting`).

It would be a good way for the child components knows if the form is still loading and display a skeleton component (especially if we are using `FormProvider`), in the same way that we already have `formState.isSubmitting` to disable a submit button for example.

Example: 

```ts
export default () => {
    const { formState, register } = useFormContext()

    return (
        {formState.isLoading 
             ? <Skeleton />
             : <input name="test" ref={register} />
        }
    )
}
```
Just with Suspense, I believe this would only be possible with a completely separate skeleton of entire page.

**Comment by vvo** [comment]
Small context, I came here because I am using https://swr.now.sh/ along with react-hook-form.
I am trying to wrap my mind around how to:
1. fetch data with swr (this I know how to do it)
2. solely use defaultValues with data coming from swr

The issue is that on first load the data will be "undefined" and then will become available. Example:

```js
  const { data } = useSWR("/api/user");

  const form = useForm({
    defaultValues: {
      name: user?.name
    },
  });
```

I hope this can help to find the right API for some sort of async defaultValues. Thanks!

**Comment by bluebill1049** [comment]
> Small context, I came here because I am using https://swr.now.sh/ along with react-hook-form.
> I am trying to wrap my mind around how to:
> 
> 1. fetch data with swr (this I know how to do it)
> 2. solely use defaultValues with data coming from swr
> 
> The issue is that on first load the data will be "undefined" and then will become available. Example:
> 
> ```js
>   const { data } = useSWR("/api/user");
> 
>   const form = useForm({
>     defaultValues: {
>       name: user?.name
>     },
>   });
> ```
> 
> I hope this can help to find the right API for some sort of async defaultValues. Thanks!

Thanks @vvo for the information. `defaultValues`is meant to set up `defaultValue` for each input, which is why it's cache the result, just like `<input defaultValue="xxx" />`. We will keep looking at this, probably not going to change `defaultValues`. behavior.

**Comment by vvo** [comment]
@bluebill1049 After posting the comment I realized that the best course of action, if I want to have defaultValues with the "right" data (= not undefined), is to wait to get the data to instantiate the form. This is definitely fine and I can show a skeleton while waiting for the data.

Thanks again for such a great lib

**Comment by vvo** [comment]
For anyone still coming here to learn how to have async defaultValues fields with react hook form, here's what I did following the author advice:

```jsx
function AsyncField() {
  const { register, reset, getValues } = useFormContext();
  const { asynchronousFieldValue } = useSomeAsynchronousDataHook();

  useEffect(() => {
    if (asynchronousFieldValue === undefined) {
      return; // loading
    }

    reset({
      ...getValues(),
      asynchronousFieldName: asynchronousFieldValue,
    });
  }, [reset, asynchronousFieldValue, getValues]);

  if (asynchronousFieldValue === undefined) return "Loading ...";

  return (
	<input
      type="text"
      defaultValue={asynchronousFieldValue}
      name="asynchronousFieldName"
      register={register}
      registerOptions={{ required: true }}
    />
  );
}
```

By using `...getValues()` you're able to reset all fields to the initial value while also adding your own asynchronous field value.

This way, isDirty will not be confused.

**Comment by bluebill1049** [comment]
Thank you @vvo very much for always sharing solutions here. ❤️

**Comment by antoinerousseau** [comment]
I'm using custom fields and a form provider. Had to add this to my Form for it to properly reset/populate when default values would change (data loading, or going from editing an object to creating a new one: same form but empty).

```ts
useEffect(() => {
  form.reset({ ...defaultValues } as DefaultValues<T>)
}, [defaultValues]) // eslint-disable-line react-hooks/exhaustive-deps
```

**Comment by diracs-delta** [comment]
The proposed solution to this has a gotcha: if you update the default value object, you are resetting the entire form to the default values. Obviously, you don't want to do this while a user is potentially entering data. Thus, any async default values should be resolved prior to initial render of the form, with a `loading` catch block like:

```
if (query.loading) {
  return <Loading />
}

return <Form />
```

This kind of sucks since, intuitively, changing the default values of a form should not reset the entire form state. However, after reading through the RFC comments, I honestly can't think of a better solution either.

**Comment by zeddz92** [comment]
If you already set the defaultValue for each input like this
```
<input {...register("lastName")} defaultValue={user?.lastName}/>
```

You can just call `reset()` on useEffect and it will detect the changes
```
  useEffect(() => {
    // update form inner state with default values after the user is fetched
    if (user) {
      reset();
    }
  }, [user]);
```

**Comment by antoinerousseau** [comment]
So, in the end, we have no easy way to update pristine default values after the form was mounted?
I though `reset(defaultValues, { keepDirty: true})` was the way to go but [apparently not...](https://github.com/react-hook-form/react-hook-form/discussions/6415)

**Comment by MilkiasTonji** [comment]
> 

Thank you very much!. This saved my day

**Comment by ScreamZ** [comment]
What's the best way to achieve this in 2022 ?

First I thought the best way is to not mount (and call useForm) as long data are not fetched.

**Comment by tiavina-mika** [comment]
I'm facing the same issue with `useForm`.

here is my code
```

...
 // LOAD DATA ON PAGE LOAD
 useEffect(() => {
    dispatch(getCurrentUser());
 }, [dispatch])
 
 ...
 const form = useForm<any>({
    defaultValues: {
      birthday: dayjs().subtract(18, 'year').toDate(),
      sex: 'Male',
      firstName: currentUser.firstName,
      lastName: currentUser.lastName,
    },
    resolver: zodResolver(signUpInfoSchema),
 });
```
 At first `currentUser `is `undefined`, then it will be loaded with async data,
 but the `useForm ``defaultValues `always get the first `undefined `data

**Comment by tiavina-mika** [comment]
here is my solution with useForm:

```
const loading = useSelector(getAppLoadingSelector);
const currentUser = useSelector(getUserUserSelector);

// LOAD DATA ON PAGE LOAD
useEffect(() => {
  dispatch(getCurrentUser());
}, [dispatch]);

const form = useForm<any>({
 // no need to define the default values here,
// we define it in a useEffect (below)
  resolver: zodResolver(signUpInfoSchema),
});

// LOAD FORM DEFAULT VALUES
useEffect(() => {
  const defaultValues = getProfileInitialValues(currentUser);
  form.reset(defaultValues);
}, [currentUser, form]);

if (loading) return null;

```

**Comment by cbdeveloper** [comment]
Any updates on this?

I don't like the `useEffect + reset` approach.

My current solution is to add a mid-level wrapper (to make sure async data is present).

And call the `useForm` hook one level down, where I'm sure async data is already present (because of the wrapper).
