### ISSUE TITLE
Rename watch to useWatch since this is a hook

### ISSUE THREAD

**Issue by finom** [react-hook-form/react-hook-form#2504]
Just a small improvement proposal. Since watch is a hook I propose to rename it to conventional useWatch.

```js
const { useWatch } = useForm();
const values = useWatch();
```

**Comment by bluebill1049** [comment]
thanks for the suggestion. we have https://react-hook-form.com/api#useWatch :)

**Comment by finom** [comment]
@bluebill1049 I understand, but why not to call it `useLocalWatch` or whatever you want but just using the `use` prefix?
