### ISSUE TITLE
Different behavior of register and register() after reset()

### ISSUE THREAD

**Issue by sunnyone** [react-hook-form/react-hook-form#2509]
**Describe the bug**
After calling reset(), fields that have register() and register behave differently.

**To Reproduce**
1. Create fields that have register() and register.
```
        <input name="field1" ref={register()} />
        <input name="field2" ref={register} />
```
2. Call reset()
```
  const onReset = useCallback((e) => {
    e.preventDefault();
    reset();
  }, [reset]);
```

3. Call getValues(). It returns only a value of field1.
```
  const onDump = useCallback((e) => {
    e.preventDefault();
    console.log("values");
    console.log(getValues());
  }, [getValues]);
```

**Codesandbox link (Required)**
https://codesandbox.io/s/zen-buck-ujt63?file=/src/App.js

**Expected behavior**
getValues() returns values of field1 and field2.

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04
- Browser: Firefox
- Version: 78

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report: 

![Screen Shot 2020-08-07 at 8 38 01 pm](https://user-images.githubusercontent.com/10513364/89637675-e5a70b00-d8ed-11ea-82c7-068d05ce6d3e.png)

when you invoke reset with empty argument, what happened

1. HTML `form.reset` kicked in
2. all field reference gets reset
3. however, input with `register` without `argument`, input ref will not get invoked again.

solutions

1. register()
2. reset({ withPayload })

**Comment by bluebill1049** [comment]
wow, i just figured out a way to work around this, potential can remove that note in the doc. as well.

https://codesandbox.io/s/heuristic-feistel-qxl8h?file=/src/App.js

**Comment by sunnyone** [comment]
Thanks. I didn't know that it's designed behavior. I'll use register() for a while.
