### ISSUE TITLE
watch() called with an array returns the defaultValues for falsy values

### ISSUE THREAD

**Issue by dkusano** [react-hook-form/react-hook-form#251]
When `watch()` is called with an array of field names, it returns the defaultValues for fields their values are empty string or `false`. It should returns empty values, not default values.

This behavior doesn't occurs when `watch()` is called with single field name or no arguments.

Here is an example code.
https://codesandbox.io/s/react-hook-form-watch-defaultvalues-ucp22

**Comment by bluebill1049** [comment]
> When watch() is called with an array of field names, it returns the defaultValues for fields their values are empty string or false.

This is the expected behavior.

The example you share they have the same output.

```
watch array: {"name":"default name","agree":true}

watch all: {"name":"default name","agree":true}
```

**Comment by dkusano** [comment]
I'm sorry I didn't make it clear enough.

In the example, when you input empty string and checkbox off, `watch(["name", "agree"])` and `watch()` behave different.

```
watch array: {"name":"default name","agree":true}

watch all: {"name":"","agree":false}
```

**Comment by bluebill1049** [comment]
thanks, I have patched the bug: you can test out in this beta version: `react-hook-form@3.22.2-beta.8`

**Comment by dkusano** [comment]
`react-hook-form@3.22.2-beta.8` works fine in my project. Thank you!

**Comment by bluebill1049** [comment]
Thanks we will release the patch soon.

**Comment by bluebill1049** [comment]
the patch has been released, please close this issue if works fine :)
