### ISSUE TITLE
remove in dynamically nested field arrays don't work correctly

### ISSUE THREAD

**Issue by paambaati** [react-hook-form/react-hook-form#2521]
**Describe the bug**
When I try to use multiple `useFieldArray`s nested inside a `useForm`, `remove(index)` doesn't remove the correct array item.

**To Reproduce**

1. Go to either of the CSB links.
2. Try clicking on one of the 'Delete XXX' buttons.
3. Notice how the fields removed aren't the ones that are supposed to be (this is evident from the button label and the last name field not matching).

**Codesandbox link**
v1 - https://codesandbox.io/s/react-hook-form-nested-usefieldarray-jqv4c?file=/src/index.js
v2 - https://codesandbox.io/s/react-hook-form-nested-usefieldarray-hjyxh?file=/src/index.js

**Expected behavior**
`remove(index)` should remove the correct field array item.

**Desktop (please complete the following information):**

- macOS Mojave 10.14.6
- Chrome
- Version 86.0.4221.4 (Official Build) dev (x86_64)

**Additional context**
1. I'm guessing I'm doing something wrong with either the `defaultValues` or how I'm initializing the nested `useFieldArray`, but I'm not sure what.
2. v1 of the CSB is a naive solution with nested hooks, while v2 fixes it by cleanly refactoring out inner hooks to own render functions.

**Comment by bluebill1049** [comment]
Thanks @paambaati for the detailed issue report. will take a look at it.

**Comment by bluebill1049** [comment]
hmmm, I think you should separate them into two components doing inside a `map`, I am not sure it will work well.

**Comment by paambaati** [comment]
@bluebill1049 Thanks for investigating this! I tried to create another version with 2 separate components like you suggested - https://codesandbox.io/s/react-hook-form-nested-usefieldarray-wyg2f?file=/src/index.js - and the problem persists.

Can you help me understand why this is happening, and if possible, suggest a better way of going about this?

**Comment by bluebill1049** [comment]
It was the dot 😭 

https://codesandbox.io/s/react-hook-form-nested-usefieldarray-ckk6n?file=/src/index.js

**Comment by paambaati** [comment]
![](https://media.tenor.com/images/5c735243bd7bf04b6bbe5c5b55b28b72/tenor.gif)

Thank you so much for figuring this out @bluebill1049, I'd have spent a few more hours on this before I'd realize this!

**Comment by bluebill1049** [comment]
that's all good mate! lol.

**Comment by canotech** [comment]
Here my  codesanbox [https://codesandbox.io/s/runtime-forest-gg6sq?file=/src/App.tsx](here)

**Comment by mrefaie** [comment]
@canotech You have to set the key prop on the root node of fields loop to {field.id}.
