### ISSUE TITLE
dirtyFields not registering field if data is set using setValue then deleted

### ISSUE THREAD

**Issue by bscaspar** [react-hook-form/react-hook-form#2522]
**Describe the bug**
`dirtyFields` does not return a field if `defaultValue` is an empty string then data is set with `setValue` then deleted by the user.

**To Reproduce**
[CSB](https://codesandbox.io/s/festive-mahavira-i83c2?file=/src/App.tsx)
1. Hit submit - `dirtyFields` = `Object {}`, expected
2. Delete a letter from the text field, hit submit - `dirtyFields` = `Object {name: true}`, expected
3. Delete all letters from the text field, hit submt - `dirtyFields` = `Object {}`, expect `Object {name: strue}`

**Expected Behavior**
`dirtyFields` should contain the field the user deleted data from. In the docs it's described as 'An object with the user-modified fields.' and the user has modified the field in this case. 

**Use Case**
Fetching data to set field values after render.

**Comment by bluebill1049** [comment]
Works as expected for me: https://codesandbox.io/s/hooks-form-controlled-e42cj?file=/src/App.tsx.

`setValue` doesn't trigger dirty. unless: setValue('name', 'value', { shouldDirty: true })

**Comment by bscaspar** [comment]
Once the form loads `setValue` populates the fields. If the user then deletes all the text, shouldn't `isDirty` be true? Even if `setValue` is not called with `{shouldDirty: true}`? That is not happening in the [CSB](https://codesandbox.io/s/hooks-form-controlled-09zfm?file=/src/App.tsx) (updated so `dirtyFields` is the only console log)

**Comment by bluebill1049** [comment]
the `defaultValues` remain the same.

**Comment by bscaspar** [comment]
I see, so that's by design? If the `defaultValues` remain the same then `isDirty = false`? If that's how it's designed then feel free to close, I thought that it would be a scenario when `isDirty` should be true. Easy enough to workaround anyway when using the `setValues` call.

**Comment by bluebill1049** [comment]
That's by correct, it's by design. `defautlValues` is the source of truth.
