### ISSUE TITLE
Warning and not fire event onChange Antd Design Checkbox Component

### ISSUE THREAD

**Issue by jmlopezo** [react-hook-form/react-hook-form#2535]
In last version (6.3.1) I get a warning when I use Antd Desing Checkbox component, also the onChange event is not fired.

"Warning: [antd: Checkbox] `value` is not a valid prop, do you mean `checked`?" 

```javascript
              <Controller
                as={<Checkbox>{item.label}</Checkbox>}
                name={item.key}
                onChange={([e]) => {
                  console.log(e);
                  return e.target.checked;
                }}
                type="checkbox"
                control={control}
              />
```

Works fine in 5.7.2 version.

**Comment by bluebill1049** [comment]
please use `render` prop for checkbox: https://react-hook-form.com/api#Controller

**Comment by jmlopezo** [comment]
Thanks, that's how it works, although I have to call another method inline.
