### ISSUE TITLE
Name with nested behaviour (using dot in name) causes dirtyFields to misbehave

### ISSUE THREAD

**Issue by kayuapi** [react-hook-form/react-hook-form#2538]
Name with nested behaviour (using dot in name) causes dirtyFields to misbehave

The CSB shows that in 'the name without nested', when type random text to make the field dirty, then remove the item, the dirtyFields is behaving as intended.

However in CSB  in 'the name with nested', when type random text to make the field dirty, then remove the item, the dirtyFields is not behaving as intended. Will expect the dirtyFields not be like the results of CSB in 'the name with nested'.

(the behaviour can be checked in console.log)
name with nested: https://codesandbox.io/s/react-hook-form-usefieldarray-template-wlx4i?file=/src/index.js
name without nested: https://codesandbox.io/s/react-hook-form-usefieldarray-template-hjdq4?file=/src/index.js

**Comment by hatchli** [comment]
I'm running in to this issue in v6.... our project is not able to upgrade to v7.

**Comment by xxxKOTxxx** [comment]
Any updates?
