### ISSUE TITLE
Allow array to be passed to pattern validation

### ISSUE THREAD

**Issue by Acidic9** [react-hook-form/react-hook-form#2540]
**Is your feature request related to a problem? Please describe.**
It is difficult to provide individual error messages when a complex regex pattern is provided.

**Describe the solution you'd like**
I would like to provide help messages when specific regex patterns are not matched.
Eg:
```jsx
ref={register({
  pattern: [
    {
      value: /(?=.*[a-z])/,
      message: 'The string must contain at least 1 lowercase alphabetical character',
    },
    {
      value: /(?=.*[A-Z])/,
      message: 'The string must contain at least 1 uppercase alphabetical character',
    },
    // ... and whatever else
  ]
})
```

**Describe alternatives you've considered**
I considered using the validate function callback to manually implement this logic.

```jsx
ref={register({
  validate: {
    lowerCaseAlphabetical: value => /(?=.*[a-z])/.test(value) && 'The string must contain at least 1 lowercase alphabetical character',
    upperCaseAlphabetical: value => /(?=.*[A-Z])/.test(value) && 'The string must contain at least 1 uppercase alphabetical character',
  }
})
```

**Additional context**
Blog post about checking password strength with regex:
https://www.thepolyglotdeveloper.com/2015/05/use-regex-to-test-password-strength-in-javascript/

**Comment by bluebill1049** [comment]
please use validation for complex validation logic or even consider schema validation.
