### ISSUE TITLE
IE11 bug in 6.3.1

### ISSUE THREAD

**Issue by c0d3x** [react-hook-form/react-hook-form#2541]
Module not found: Error: Can't resolve '@babel/runtime-corejs3/core-js/get-iterator-method' in '/node_modules/react-hook-form/dist'

**Comment by bluebill1049** [comment]
did you get a runtime error? can you supply a screenshot?

**Comment by c0d3x** [comment]
I just changed it back to 6.3.0, dont have the time to debug now. Just wanted to let you know.
All you have to do to is run **npm run build** and you get those error message as long as you use the IE11 version in your code.
`import { useForm } from 'react-hook-form/dist/index.ie11';`

**Comment by bluebill1049** [comment]
Thanks @c0d3x

**Comment by bluebill1049** [comment]
@kotarella1110 would you have any clue on this one: https://codesandbox.io/s/pedantic-mahavira-g1x6z?file=/src/App.js

**Comment by bluebill1049** [comment]
pretty sure, it's caused by this PR: https://github.com/react-hook-form/react-hook-form/commit/7ad6e082515aabe9a4021e1aab057576cf184dc3
