### ISSUE TITLE
Bring the old SetValue method signature

### ISSUE THREAD

**Issue by zelucena** [react-hook-form/react-hook-form#2544]
I read the new migration guide and I found the new way of writing setValue so verbose. The old one was very intuitive and concise.

```
- setValue([ { test: "1", }, { test1: "2", } ])
+ [ { name: 'test', value: 'data' } ].forEach(({ name, value }) => setValue(name, value))
```

What about providing a method called `setValues`, `setValueList` or something alike with the old signature and new piece of code underneath?
Sure thing I could do that myself and it should work, but I'd be relying on unofficial / unmantained layer of software on top of this version of this library. It seems very redundant to rewrite a forEach => setValue everywhere though.
I'm not complaining it would take me any long to refactor my project for it's not massive yet, but I assume it could potentially save a lot for others.

**Comment by bluebill1049** [comment]
> The old one was very intuitive and concise.

Yes, totally agree. I will ping this one on the feature request board, if many users want this feature, let's bring another separate API: `setValues`

**Comment by zelucena** [comment]
Thanks for your time

Em seg, 10 de ago de 2020 20:06, Bill <notifications@github.com> escreveu:

**Comment by bluebill1049** [comment]
hey @zelucena, i have a better idea. what about this?

```ts
setValue({
  test: {
    fiirstName: 'fiirstName',
    lastName: 'lastName',
  }
}, { exact: false })
```

so by default you need to set value by `exact`

```ts
[ { name: 'test', value: 'data' } ].forEach(({ name, value }) => setValue(name, value))
```

**Comment by zelucena** [comment]
Seems good to me

Em seg, 31 de ago de 2020 00:43, Bill <notifications@github.com> escreveu:

**Comment by ejose19** [comment]
@bluebill1049 does react-hook-form batches setValue running sequentially like in the forEach example? Or a "setValues" would be better performance wise?

**Comment by zelucena** [comment]
I wasnt even thinking of that when I made the point. I don't see how it
could be worse than O(n) but most times I won't bother anyway as I still
have not had a critical data mass to handle with setValues all at once

Em sáb, 5 de set de 2020 19:23, ejose19 <notifications@github.com> escreveu:

**Comment by bluebill1049** [comment]
> @bluebill1049 does react-hook-form batches setValue running sequentially like in the forEach example? Or a "setValues" would be better performance wise?

```
setValue('test', {
  fiirstName: 'fiirstName',
  lastName: 'lastName',
})
```

if your data is an object, then this is actually working right now at the latest (forgot to document it), but yes setValues would be better perf for batch.

**Comment by ejose19** [comment]
@bluebill1049 yes for object it's already working good, but I was talking more like sibling fields or even useFieldArray fields, those should benefit more from a batch update.

**Comment by bluebill1049** [comment]
> @bluebill1049 yes for object it's already working good, but I was talking more like sibling fields or even useFieldArray fields, those should benefit more from a batch update.

The update is coming: https://github.com/react-hook-form/react-hook-form/pull/2691
