### ISSUE TITLE
Hydrated dirtyFields object with data

### ISSUE THREAD

**Issue by josias-r** [react-hook-form/react-hook-form#2547]
**Is your feature request related to a problem? Please describe.**
I come from an example where we use a Form to PATCH data in a DB. This PATCH only required the modified/dirty data to be sent, of course. Currently, a dirtyData object needs to be built manually for every form which is inconvenient and probably not the most performant solution.

**Describe the solution you'd like**
It would be awesome if I could get an object of the dirtyFields from the hook (like what `watch()` does but only w/ the dirtyFields).
Here's the proposed syntax:
```
const { formState: { dirtyData } } = useForm(); // notice dirtyData instead of dirtyFields which is just an object of booleans
```

**Describe alternatives you've considered**
In most of the cases, it's enough to have it in the handleSubmit method though. So adding a parameter there could suffice too. So instead of adding a property to the hook, just add the dirtyData value to the handleSubmit parameters. This might be a bit more performant but it is less flexible.

**Additional context**
This is currently already possible by building the dirtyData object yourself, but it seems, but it requires to use watch first and it also probably not the most performant solution. I use the following workaround (typescript):

```
const { watch, formState: { dirtyFields } } = useForm();
// ...
const formData = watch();
const dirtyData: Partial<typeof formData> = {};
Object.entries(dirtyFields).forEach(dirtyField => {
   // here we hydrate the partial object created above
   dirtyData[dirtyField[0]] = data[dirtyField[0]];
});
```

**Comment by bluebill1049** [comment]
Thanks for the feature request @josias-r. I think this one is probably better to leave the logic at your App level.

**Comment by josias-r** [comment]
Hmm okay... I'm still curious about the mentality behind that. You don't give the devs an easy opportunity to PATCH dirty fields only. Should I consider patching all data from the form, is that what you expect people to do?
I'm asking because doing this every time is annoying (we have a lot of forms in our application) and maybe it's just overengineering. Otherwise, I will simply wrap the hook, since I have some other ideas to adjust it to our application needs.

**Comment by bluebill1049** [comment]
> You don't give the devs an easy opportunity to PATCH dirty fields only.

Sorry, if you felt this way. That's not our intention. Honestly, I can easily introduce such an API if this is a library that is consumed individually or just a personal project. it's important to make things work for developers and also keep things simple, minimal and elegant at lib level. 

> I'm asking because doing this every time is annoying (we have a lot of forms in our application) and maybe it's just overengineering.

I think we have already exposed `dirtyField` which you can map the dirty fields and build a function to map the fields. 

Lastly, if you have a strong opinion about this feature, we are happy to tag as a `feature request` and `waiting for upvote`, however, this will take time as well until the amount users who need such feature first then we will consider to include it.

I hope the above make sense. 🙏

**Comment by josias-r** [comment]
Hmm okay. No the `feature request` is not needed, since I'm the first one to ask for this, it's probably not something a lot of people need.
I'm wrapping the hook in a customized one (fully typed) and I will post my solution once it's finished (currently just fighting with passing the generic types down)

**Comment by bluebill1049** [comment]
That's awesome! thanks for sharing the solution. 👍

**Comment by josias-r** [comment]
Alright, the solution I came up with (I added multiple things):
```
import { useForm as useFormOriginal, ValidationRules } from "react-hook-form";
import {
  FieldValues,
  UseFormOptions,
  FieldName,
} from "react-hook-form/dist/types/form";

// props to hydrate to first param
type newFormParamProps = {
  // anAdditionalOptionAsAnExample?: string;
};

// type magic to add property to first param object
type hydratedFormParamProps<T1, T2 extends object = object> = UseFormOptions<
  T1,
  T2
> &
  newFormParamProps;

// hydrated useForm
function useForm<
  TFieldValues extends FieldValues = FieldValues,
  TContext extends object = object
>(origParams: hydratedFormParamProps<TFieldValues, TContext>) {
  const useFormState = useFormOriginal<TFieldValues, TContext>(origParams);

  // const anAdditionalOptionAsAnExample =
  //   origParams.anAdditionalOptionAsAnExample;

  const registerMany = (
    toRegister: { name: FieldName<TFieldValues>; rules?: ValidationRules }[],
  ) => {
    toRegister.forEach(registerData => {
      useFormState.register(registerData.name, registerData.rules);
    });
  };

  const formData = useFormState.watch();
  type DirtyData = Partial<typeof formData>;
  const dirtyData: DirtyData = {};
  Object.entries(useFormState.formState.dirtyFields).forEach(
    (dirtyField: [keyof DirtyData, DirtyData[keyof DirtyData]]) => {
      dirtyData[dirtyField[0]] = formData[dirtyField[0]];
    },
  );

  return {
    ...useFormState,
    registerMany: registerMany,
    formState: {
      ...useFormState.formState,
      dirtyData,
    },
  };
}

export default useForm;
```

This adds the feature talked about in this issue + another one, which is being able to register many custom fields at once.
Usage:
- the `formState` object now has an additional `dirtyData` prop instead of just `dirtyFields`
- the hook object also returns the `registerMany` method, which can be used to do something like this:
```
  registerMany([
    { name: "asimplefield" },
    {
      name: "arequiredfield",
      rules: {
        required: {
          value: true,
          message: t("Value is required and can't be empty"),
        },
      },
    },
  ]);
```
- commented out there is the `anAdditionalOptionAsAnExample` type and prop. I've set this up, so this customized hook can also add new options to the options object of your hook which intern can be accessed to to fun stuff

**Comment by josias-r** [comment]
@bluebill1049 I'm having a general problem with the watch method though, which also kinda breaks this customized hook. I will create a new issue and reference to this.

**Comment by josias-r** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2559

**Comment by josias-r** [comment]
Awesome, that was resolved quickly! Thanks for the great support. I updated the example. Make sure you wrap the `registerMany` inside a `useEffect` too for my example to work correctly.

**Comment by bluebill1049** [comment]
Thanks @josias-r
