### ISSUE TITLE
dirty and dirtyFields don't work as expected with a field array

### ISSUE THREAD

**Issue by DawidNazarko** [react-hook-form/react-hook-form#2548]
**Describe the bug**
`dirty` is true and `dirtyFields` is not empty object when I focus and blur a field from field array

**To Reproduce**

1. Click on a field with text `Click me then click outside`
2. Click outside of this field
4. In console is 
```
true
Set(1) {"test[0].name"}
```

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-yvycu?file=/src/index.js

**Expected behavior**
`dirty` is false and `dirtyFields` is empty object

**Version**
 5.7.2

**Comment by bluebill1049** [comment]
could you test out the latest version? it's probably been patched.

**Comment by DawidNazarko** [comment]
Sure. I switched to 6.3.2 and the result is `isDirty` true and `dirtyFields` is an empty object. So `isDirty` is still wrong.

**Comment by bluebill1049** [comment]
ok, i look at your description again, why focus and blur should change dirty to `true`?

**Comment by DawidNazarko** [comment]
I mean focusing and bluring a field causes `dirty` being set to `true` but I expect `false`.

**Comment by bluebill1049** [comment]
oh thanks! that's a bug.
