### ISSUE TITLE
Input type="number" || outputs string on submit

### ISSUE THREAD

**Issue by HadiSDev** [react-hook-form/react-hook-form#2550]
**Describe the bug**
Input type="number" seems to output a string value regardless of the type

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://codesandbox.io/s/react-hook-form-basic-forked-628hn?file=/src/index.js
2. Write a number in the number field.
3. Press submit
4. See in the alert that the field outputs a string instead of a number

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.
https://codesandbox.io/s/react-hook-form-basic-forked-628hn?file=/src/index.js

**Expected behaviour**

It should output {"number":222} and not {"number":"222"}

**Desktop (please complete the following information):**

- OS:  WIN 10
- Browser Chromium (Edge)
- Version: Idk

**Comment by bluebill1049** [comment]
This is expected behavior, naive input produce `string` at submitting unless use `valueAsNumber`.

**Solution:** 

https://github.com/react-hook-form/react-hook-form/tree/master/examples

https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-furtc
