### ISSUE TITLE
Do you have a reusable components/libs build with React Hook Form?

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#2552]
If you have built a reusable component or lib, let us know, we can include in the resource pages. I am planning to redesign the resource page to include more useful contents.

**Comment by gerardo-navarro** [comment]
@bluebill1049 Have you received any example of reusable component libs built with react-hook-form? I am building some internal forms with react-hook-form as consumable npm package. I am facing issues (https://github.com/react-hook-form/react-hook-form/issues/1170) when consuming this package and I would like see some example to learn from.

**Comment by bluebill1049** [comment]
hey @gerardo-navarro have a look at this section: https://react-hook-form.com/api#Controller
here is a CSB linke as well: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r

**Comment by AndrewOttavianoAbb** [comment]
@bluebill1049 does this mean that if we are using mui components and building a component library with a [reusable form component](https://react-hook-form.com/advanced-usage#SmartFormComponent), do we need to use the RHF Controller component?
