### ISSUE TITLE
formState.isValid should be undefined when mode is not onBlur or onChange

### ISSUE THREAD

**Issue by SharadKumar** [react-hook-form/react-hook-form#2556]
**Is your feature request related to a problem? Please describe.**
`formState.isValid` should be undefined when mode is not `onBlur` or `onChange`.

**Describe the solution you'd like**
Console warnings are displayed. Instead of documentation, I suppose this can be handled in code instead and forms will be able to handle it better too, when `isValid` is not applicable.

Unless, I've missed a point here.
https://react-hook-form.com/api#formState

**Comment by SharadKumar** [comment]
Okay, so I am trying to get optimal behaviour for the Submit button.

```jsx
<SubmitButton 
...
disabled={
        submitting ||
        !formState.isDirty ||
        (!formState.isValid && formState.submitCount > 0)
      }
/>
```

Use cases:
- Submit disabled when form is not dirty (since user may have `touched` but haven't changed anything)
- Submit should be disabled during the submit, hence `submitting` prop
- Submit should be enabled for default form mode 'onSubmit' unless it has been submitted and there are `errors`. At that time, I have `formState.isValid` false and `formState.submitCount` > 0. This works, but my console is flooded with warnings! Yes, I noted it in the documentation.

**Comment by bluebill1049** [comment]
can you please submit a codesandbox with your issue?

**Comment by SharadKumar** [comment]
Yes, please take note of warnings in the console and the intent of the config/behaviour desired for Submit button. If a different behavioural standard is recommended, please suggest.

https://y1qsn.csb.app/

**Comment by bluebill1049** [comment]
The warning is correct, you need to set `mode` to `onChange`

**Comment by SharadKumar** [comment]
Yes @bluebill1049 I understand that. However, the intent is to not fire validation before 1st submit. OnChange will compromise that behaviour afaik. Hence, I have kept default config as is (onSubmit).

I intent to leverage onSubmit, and then onwards onChange kicks in. In usability terms, a form should not throw error while user is first time typing an email address, for example. It is okay that form feedbacks onChange while user is correcting the mistake (after an attempt to submit).

**Comment by bluebill1049** [comment]
`isValid` only works with onChange and onBlur. onSubmit means validation will only kick in after `submit`, then there is no point to watch `isValid` value.

**Comment by SharadKumar** [comment]
Okay, I've implemented a workaround with formState.isSubmitted:
```js
className={`${
          errors[name] && form.isSubmitted
            ? 'is-invalid'
            : ''
        }`}
```

Thank you for the clarifications @bluebill1049
