### ISSUE TITLE
watch or useWatch glitched data with setValue (or maybe other reasons)

### ISSUE THREAD

**Issue by josias-r** [react-hook-form/react-hook-form#2559]
Using the watch or useWatch method has some glitch behaviour when used together with custom form fields (custom register & setValue).

it's pretty hard to explain, but it's easy to see what happens with an example, so here you go:
https://codesandbox.io/s/determined-torvalds-8qtr8?file=/src/Form.tsx

1. When the watch method happens "before" registering the fields, it seems to fire twice, but it has correct values. Clicking one seems to work, but as soon as you press the second one, the first field will get reset
2. When the watch method happens "after" registering, the formData does not update

**Comment by bluebill1049** [comment]
your `register` should be placed inside `useEffect`, otherwise the custom input gets re-register each render.

**Comment by josias-r** [comment]
Thanks!!
I updated the sandbox: https://codesandbox.io/s/dry-frost-m2x2c?file=/src/Form.tsx
I also had to make sure to only pass the register as a dependency for it to work.
Is this documented already? I must have overseen it in that case 🤔

**Comment by bluebill1049** [comment]
yes for the custom register, always put inside `useEffect`.

**Comment by josias-r** [comment]
@bluebill1049 One more question. Since it is inside useEffect, and the register method also is where you want to validate the fields. If the validation method listens to a local state variable, I will have to pass that variable to the useEffect dependencies, therefore, if that state changes,  the fields will get registered again, and the previous state of the form will get lost

**Comment by bluebill1049** [comment]
Do you have codesandbox example for above?

**Comment by josias-r** [comment]
Yup, extended the other one: https://codesandbox.io/s/dry-frost-m2x2c?file=/src/Form.tsx

**Comment by bluebill1049** [comment]
i see, yea that situation, you will have to use `useRef` or `getValues()` inside the validator.

**Comment by josias-r** [comment]
Hmm actually I tried wrapping the validation method inside a useRef and it didn't work for some reason. What do you mean w/ `getValues` though? It has nothing to do with the form values itself. The problem is that re-registering the fields will reset them back to the default values, and because there is a customState involved the useEffect/register will get triggered again when that state changes

**Comment by bluebill1049** [comment]
probably easier just turn that value into `<input type="hidden" name="xxx" ref={register(validate)} />`

**Comment by josias-r** [comment]
Hmm I tried using your idea in my more complex usage in our app. Unfortunately, this workaround is not an option.
This seems like a bug or an edge case that has been forgotten to be handled. Should I open a new issue for it?

I'm curious though, why allow the users to register multiple times? If a field is already registered and the method is called, shouldn't it be ignored? Currently, it seems to reset to the default value.

I've investigated this problem and looked at the source code of this hook too. It seems you are storing the fields inside one big fieldsRef when registering. A useRef will always have the state of variables when it got initialized. That means when you call `register`, the validation method is written fixed into the Ref and won't update until `register` is called again.
My question now is, why would you use the default values for fields, when `register` gets called again and it had a value previously? If that could be changed in the source code, the problem would be solved. Otherwise, the solution would get more complex, like removing the rules from the fieldsRef and only keep the values there or smth, so methods can get updated from outside

**Comment by bluebill1049** [comment]
> Hmm I tried using your idea in my more complex usage in our app. Unfortunately, this workaround is not an option.
> This seems like a bug or an edge case that has been forgotten to be handled. Should I open a new issue for it?

https://codesandbox.io/s/serverless-http-j807x?file=/src/Form.tsx
works for me 

> I'm curious though, why allow the users to register multiple times? If a field is already registered and the method is called, 
> shouldn't it be ignored? Currently, it seems to reset to the default value.

because if the user start to toggle the same input with the (`ref`), we don't want to re-register or potentially overwrite what's been registered, that's why we do a `ref` compare, see if they are the same reference.

**Comment by bluebill1049** [comment]
or you can try the following as well: 

```
useEffect(() => {
  register('test', validate: otherValue);
  return () => {
    unregister('test');
  }
}, [register, unregister, othervalue])
```

**Comment by josias-r** [comment]
Alright, I took some time again to try to get it to work with hidden inputs. Apologies, you were right, it does actually work this way.
Your example with the cleanup function did not seem to work. Anyways, I have a good solution now, thank you a lot for the help!

I still can't wrap my head around why the register on an input field ref does not reset the field values to the defaults, but using the useEffect syntax, it does. Is that what you meant with the `ref` comparison? Does it know that it does not need to register again, when the input ref is the same and that information is missing with the useEffect syntax? (I console logged inside the ref property to see whether the register is fired multiple times too and it is).

It's a bit confusing from a developing perspective, since all I can observe, is that the field values are getting reset to the defaults using the useEffect hook, but not if I use a hidden ref input field.

Nonetheless, thank you, my problems are now resolved!

**Comment by bluebill1049** [comment]
thanks for your feedback @josias-r 

my memory the problem is due to this:

`{toggle ? <input name="test" ref={reigster} /> : <input name="test" type="checkbox" ref={reigster} />}`

however, it does make sense not to register same input again and again. perhaps we can allow that to happen when input's `ref` is not supplied. I will think about this issue and let you know.

**Comment by josias-r** [comment]
@bluebill1049 Alright cool that sounds great! I won't steal more of your time then, thanks again 🙏🏻
