### ISSUE TITLE
Pattern validation doesn't work properly

### ISSUE THREAD

**Issue by manualva7** [react-hook-form/react-hook-form#2562]
**Describe the bug**
The docs describe how to use pattern, but pattern doesn't behave like html5 pattern validation

**To Reproduce**

1. Go to https://codesandbox.io/s/elegant-silence-osn90?file=/src/App.js
2. Type a letter and then type a number.
3. Click on Submit, no error.
4. Type a number and then type a letter.
5. The form will submit without errors.

**Codesandbox link (Required)**
https://codesandbox.io/s/elegant-silence-osn90?file=/src/App.js

**Expected behavior**
If there is a number anywhere inside that string, the field should return invalid.

**Screenshots**
![Screen Shot 2020-08-11 at 4 38 36 PM](https://user-images.githubusercontent.com/41272874/89959372-22764900-dbf1-11ea-9b0c-c09a1349befb.png)

**Desktop (please complete the following information):**

Mac OS Mojave 10.14.6
Chrome 84.0.4147.105

**Comment by bluebill1049** [comment]
Thanks @manualva7 can you please double check your CSB? it's using validate function.

**Comment by manualva7** [comment]
Sorry about that. I'm currently trying to figure it out so I'm playing with the options

**Comment by manualva7** [comment]
@bluebill1049 just found out the problem. If you want to only accept a-zA-Z you need to wrap the regex like so:
`/^[a-zA-Z]+$/`
instead of the one in the docs which is:
`/[A-Za-z]{3}/`
It's fixed now. Docs got me confused. 
https://codesandbox.io/s/elegant-silence-osn90?file=/src/App.js

**Comment by Ethaan** [comment]
One thing i noticed its that

```
<input
  name="example3"
  ref={register("name")}
  pattern="/^(https?:\/\/[^\s]+)+$/"
/>
```

wont work, it will always show value as invalid 

![Screen Shot 2021-06-23 at 17 52 42](https://user-images.githubusercontent.com/8289486/123177951-dd938380-d44b-11eb-8297-db2e55c5cdab.png)


and doing

```
<input
  name="example3"
  ref={register({
    pattern: { value: /^(https?:\/\/[^\s]+)+$/, message: "invalid" }
  })}
/>
```

and removing `<div>{errors.example3 && <span>errors.example3.message</span>}</div>`  will just focus the input but no popup its this intendeed?

Its there a way to have **RHF register + pattern HTML5 validation together?**

**Comment by bluebill1049** [comment]
can you provide a CSB? @Ethaan

**Comment by Ethaan** [comment]
@bluebill1049 https://codesandbox.io/s/relaxed-jepsen-ks58l?file=/src/App.js

**Comment by bluebill1049** [comment]
<img width="962" alt="Screen Shot 2021-06-24 at 9 27 17 am" src="https://user-images.githubusercontent.com/10513364/123180303-5fc48c00-d4ce-11eb-9ae8-d801450fa91c.png">

use this config above.

**Comment by Ethaan** [comment]
@bluebill1049 thanks

seems like its removed on `"react-hook-form": "^7.8.8",`?

ts throwing errors

**Comment by bluebill1049** [comment]
> @bluebill1049 thanks
> 
> seems like its removed on `"react-hook-form": "^7.8.8",`?
> 
> ts throwing errors

Use the latest version.
