### ISSUE TITLE
Cannot change form content and validation on the fly

### ISSUE THREAD

**Issue by sahanatroam** [react-hook-form/react-hook-form#2565]
**Describe the bug**
As a developer I want to create a wizard where at each step the content of the form + validation changes.
But even though the validation and content changes react hooks doesn't pick up the new validator

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-validationschema-forked-4nuwd?file=/src/index.js

**Expected behavior**
If you open the Codesandbox above, 
1. Enter a wrong URL in to website
2. Error is shown - this is good.
3. Now click on the toggle button.
4. In the new validation schema website is optional.
5. But you will still see the last validation schema is attached

**Comment by bluebill1049** [comment]
we don't support this usage, you will have to write your own` resolve` and combined with `context` to switch your schema.

**Comment by sahanatroam** [comment]
@bluebill1049 is there an example that I could follow ?

**Comment by sahanatroam** [comment]
Also why do you not support this usage ?

**Comment by bluebill1049** [comment]
Take a look at the `resolver` in the doc: 
<img width="931" alt="Screen Shot 2020-08-12 at 12 43 13 pm" src="https://user-images.githubusercontent.com/10513364/89969306-645aca00-dc99-11ea-8ab0-46c45e9be7f7.png">
<img width="962" alt="Screen Shot 2020-08-12 at 12 43 33 pm" src="https://user-images.githubusercontent.com/10513364/89969326-6fadf580-dc99-11ea-8c9c-1acf2e767ac5.png">

**Comment by sahanatroam** [comment]
Thanks @bluebill1049 
But may I know why this functionality is not supported ? Feels like it's a very valid use-case ?

**Comment by bluebill1049** [comment]
because we cache `resolver` inside the hook, the only way to inject value into your schema is through `context`.

**Comment by bluebill1049** [comment]
actually looking twice into the source code, spot the issue. will patch this.

**Comment by sahanatroam** [comment]
Thank you so much. Please do let me know if I could help at all.
