### ISSUE TITLE
Other react-select/async values lost inside a field array when 1 is removed

### ISSUE THREAD

**Issue by paambaati** [react-hook-form/react-hook-form#2567]
**Describe the bug**
When using a `useFieldArray` with a [`react-select/async`](https://react-select.com/home#async) component, when removing an array item, `react-select/async` components in other items also lose values.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-nested-usefieldarray-forked-uo0q3?file=/src/index.js
2. Change the color value for all rows to, say, `Red`.
3. Now delete any row.
4. Submit the form.
5. Notice that the form values printed don't have all `Red`. They've gone back to their default values.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-nested-usefieldarray-forked-uo0q3?file=/src/index.js

**Expected behavior**
On removing a row, the selected values for other instances should stick.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS macOS Mojave 10.14.6
- Browser Chrome
- Version 86.0.4221.4 (Official Build) dev (x86_64)

**Additional context**
1. I'm manually calling `setValue()` inside the select component's `onChange` event. With or without it, this issue still remains.
2. Passing `register` or `register()` to the `ref` of the select component makes no difference to this issue.

**Comment by bluebill1049** [comment]
make sure you are using `Controller` with `react-select`.

**Comment by paambaati** [comment]
Can confirm that using a `<Controller>` works - see updated CSB - https://codesandbox.io/s/react-hook-form-nested-usefieldarray-forked-uo0q3?file=/src/select-controller.tsx
