### ISSUE TITLE
unable to toggle checkbox wrapping <Controller>

### ISSUE THREAD

**Issue by thian4** [react-hook-form/react-hook-form#2572]
How to do use checkbox within a Controller component? I did this but it can't really toggle `true` and `false`:

```
<Controller
            as={({ onChange, value }) => (
              <div>
                <input type="checkbox" onChange={onChange} value={value} />
              </div>
            )}
            control={control}
            name="test"
          />
```

I created a demo, I can use the normal ref={register}

https://codesandbox.io/s/react-hook-form-v6-controller-forked-iyd1e?file=/src/index.jsx

**Comment by bluebill1049** [comment]
`checked`

**Comment by thian4** [comment]
changed to `checked`, can't toggle https://codesandbox.io/s/react-hook-form-v6-controller-forked-puq2u

**Comment by bluebill1049** [comment]
honestly, please send sometimes with the doc... the first example is a checkbox

https://codesandbox.io/s/react-hook-form-v6-controller-forked-kn5pq

https://react-hook-form.com/api#Controller

<img width="1025" alt="Screen Shot 2020-08-12 at 7 17 42 pm" src="https://user-images.githubusercontent.com/10513364/89998144-80c62900-dcd0-11ea-8967-1daaf8918436.png">
