### ISSUE TITLE
setValue not working as expected inside useEffect

### ISSUE THREAD

**Issue by matchatype** [react-hook-form/react-hook-form#2578]
**Describe the bug**
Using `setValue` to populate input fields on component mount doesn't set values as expected.

I'm using react-hook-form with BaseUI and controlled components. I have a modal that, when opened, presents a set of fields dynamically, and these fields should be populated with previously saved values, if present. The only way I was able to work around the issue, was by wrapping a `setTimeout` around the `setValue` calls.

**To Reproduce**
I reproduced the issue in a CodeSandbox, which is linked below 👇
The component `TestForm.js` shows the setup with the following workaround applied, so it is working:

```js
React.useEffect(() => {
    if (isOpen && activeFile.length) {
      const { title = "", assetType = [] } = files[activeFile];
      defaultValues = { title, assetType };
      setTimeout(() => {
        mapValues(defaultValues, (value, key) => setValue(key, value));
      });
    }
  }, [isOpen]);
```

**Codesandbox link (Required)**

Here is a link to a 👉 [reproduction of the issue](https://codesandbox.io/s/vigilant-satoshi-usd9t?file=/src/TestForm.js).

**Expected behavior**
Using `setValue` inside of `useEffect` hook to manually set field values should work like the following:

```js
React.useEffect(() => {
    if (isOpen && activeFile.length) {
      const { title = "", assetType = [] } = files[activeFile];
      defaultValues = { title, assetType };
      mapValues(defaultValues, (value, key) => setValue(key, value));
    }
  }, [isOpen]);
```

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report! love those 🖐️ hahaha

you can set `shouldUnregister:false` to get around this issue:

https://codesandbox.io/s/quiet-leaf-n83pe?file=/src/TestForm.js

the problem is because `setValue` needs input to be registered, the animation takes "time" for those inputs to be mounted, that's why `setTimeout` did the trick.

**Comment by matchatype** [comment]
Doh 🙄 I swear I tried that and didn't work, but now it does 🥳 Thank you 🙏

**Comment by brjadams** [comment]
how long does this timeout typically need to be?

**Comment by bluebill1049** [comment]
> how long does this timeout typically need to be?

don't think you need the setTimeout.

**Comment by brjadams** [comment]
`    useEffect(() =>{
        register({name: 'isVerified'})
        register({name: 'committeeType'})
        setValue("committeeType", "standing")

        async function getCommitteeList() {
            setCmteLoaded(false)
            setIsLoading(true)
            return await GetStandingCommittees()
        }

        if(!values.cmtes.length) {
            getCommitteeList().then(res => {
                setStateValues(prevState => ({
                    ...prevState,
                    cmtes: res,
                }));
                setCmteLoaded(true)
                setIsLoading(false)
                setValue('chamber', props.chamber)
                // setValue('selectedCmte', props.cmteLpid)
            });
        }
    }, [])`

whenever I try to setValue on the selectedCmte select box, it visually appears empty. However, if i touch another field the field immediately re-renders and I can see the correct item as selected from the box. I am unsure how to optimize the rendering here when setValue is only partially doing what I expect.

**Comment by bluebill1049** [comment]
> ```
>     useEffect(() =>{
>         register({name: 'isVerified'})
>         register({name: 'committeeType'})
>         setValue("committeeType", "standing")
> 
>         async function getCommitteeList() {
>             setCmteLoaded(false)
>             setIsLoading(true)
>             return await GetStandingCommittees()
>         }
> 
>         if(!values.cmtes.length) {
>             getCommitteeList().then(res => {
>                 setStateValues(prevState => ({
>                     ...prevState,
>                     cmtes: res,
>                 }));
>                 setCmteLoaded(true)
>                 setIsLoading(false)
>                 setValue('chamber', props.chamber)
>                 // setValue('selectedCmte', props.cmteLpid)
>             });
>         }
>     }, [])
> ```
> 
> whenever I try to setValue on the selectedCmte select box, it visually appears empty. However, if i touch another field the field immediately re-renders and I can see the correct item as selected from the box. I am unsure how to optimize the rendering here when setValue is only partially doing what I expect.

can you share a simple codesandbox? I can take a look at it.

**Comment by sulemankhalid128** [comment]
`useEffect(() => {
    if (isOpen && activeFile.length) {
      reset({ ...anyValue }); //value key is according to input name attribute
    }
  }, [isOpen]);`

**Comment by appasaheb4** [comment]
setValue("lab", user.defaultLab)

after error showing 
how to fix?

**Comment by cassianomon** [comment]
> 

Is there any way to do it with useFormContext?? As shouldUnregister is not available
