### ISSUE TITLE
Allow Multiple `pattern`'s for `register`

### ISSUE THREAD

**Issue by aequasi** [react-hook-form/react-hook-form#258]
**Is your feature request related to a problem? Please describe.**

Some fields can have multiple regex requirements. It would be very handy to be able to specify multiple patterns (and messages) that a field requires.

**Describe the solution you'd like**

You should be able to specify multiple patterns:

```
<input name="foo" ref={register({pattern: [{value: /A-Z/}, {value: /^B/}]})} />
```

**Describe alternatives you've considered**

The only alternative to this is to forgo the form's built in validation, and roll your own

**Additional context**

None.

**Comment by bluebill1049** [comment]
@stramel we do allow multiple error message with validate.

```
{
  validate: {
    test: (value) => value ==='test' && 'onMessage',
    test1: (value) => value === 'test1' && 'onMessage2' 
  }
}
```

@aequasi thanks for raising this issue, one of the primary goals is to stay close as HTML standard, basically how a pattern works in constraint API in HTML form. so for now, I think can use validate for such instance. :)

**Comment by bluebill1049** [comment]
@jlison yea we did discuss this feature, but it has its pro and cons (from lib perspective). for now, I will add this to the backlog and if more devs request it, then we will find a good solution for this.

**Comment by zazagag** [comment]
any updates?

**Comment by bluebill1049** [comment]
@zazagag I had a PR on multiple errors and was closed, i think you can pretty much work around with validate function

**Comment by zazagag** [comment]
@bluebill1049 thanks for reply. In our case we have to set errors dynamically through `setError` and, if I understood it right, it is impossible now to set several errors at the same time. So I'd like to know do you have any plan to add this functionality?

**Comment by bluebill1049** [comment]
@zazagag return multiple errors it's on my todo list, but I don't think it's on my priority list. Honestly, I would stick with `setError()` for now, you can set multiple different errors too.

```
validate: (a) => {
  if (a) {
    setError('xxx', )
  } else if (a > 1) {
     setError('1xxx', )
  } else if (a > 2) {
     setError('2xxx', )
  }

  return true;
}
```

**Comment by zazagag** [comment]
Yeah, but there is only one registered error in your example. I am about:
```
validate: (a) => {
  if (a) {
    setError('xxx', )
    setError('zzz', )
  } else  {
     setError('yyy', )
  }
  return true;
}
```
Anyway thanks.

**Comment by DarkSouls101** [comment]
Yea do that for now, thanks

**Comment by bluebill1049** [comment]
Yes @zazagag until we have a proper solution, plz do that for now

**Comment by speed1992** [comment]
For version 7, this worked for me:
  
            validate: {
                            hasAlphaNumeric: (value) => alphaNumbericRegEx.test(value) ? true : false,
                            hasNoSpaces: (value) => noSpacesRegEx.test(value) ? true : false
             }



            {errors.password && errors.password.type === "hasAlphaNumeric" && (
                <div>Password must have a number and alphabet</div>
            )}
            {errors.password && errors.password.type === "hasNoSpaces" && (
                <div>Password must not have spaces</div>
            )}

**Comment by ShaheerAhmed569** [comment]
> 

validate: {
                  format: ((value) => /^((\+92)?(0092)?(92)?(0)?)(3)([0-9]{2})((-?)|( ?))([0-9]{7})$/gm.test(value)) || 'Invalid format',
                  characters: ((value) => /^[0-9]/g.test(value)) ||
                  'Characters not allow'
                }

**Comment by ShaheerAhmed569** [comment]
> Based on your use-case, I would suggest using the `validate` option.
> 
> ```
> validate: {
>   hasSpecialChar: specialCharRegex.test,
>   hasNumbers: numbersRegex.test,
>   // ...
> }
> ```
> 
> then you can display your messages independently.
> 
> ```
> {errors.password && errors.password.type === 'hasSpecialChar' && 'Must have special chars'}
> {errors.password && errors.password.type === 'hasNumbers' && 'Must have numbers'}
> ```
> 
> https://codesandbox.io/s/8n937m64o9
> 
> Alternatively, you can return the message from the validation function.
> 
> ```
> hasSpecialChar: (value) => specialCharRegex.test(value) || 'Must have special chars'
> 
> // ...
> 
> {errors.password && errors.password.message}
> ```





validate: {
format: ((value) => /^((+92)?(0092)?(92)?(0)?)(3)([0-9]{2})((-?)|( ?))([0-9]{7})$/gm.test(value)) || 'Invalid format',
characters: ((value) => /^[0-9]/g.test(value)) || 'Characters not allow'
}

Its not work in material UI
WHY??
