### ISSUE TITLE
[Request for Feature] Support integer values for nested form field keys.

### ISSUE THREAD

**Issue by RookY2K** [react-hook-form/react-hook-form#2581]
**Describe the bug**
dirtyFields and isDirty are inconsistent with expected values. dirtyFields will zero out after blur and change events when there are still dirty fields. This is for version 6.3.3. This seems to only happen with nested fields with number properties. Nested Fields with string properties work as expected.

**To Reproduce**

1. Go to codesandbox linked below
1. Enter values into Left <span>#</span>1, Left <span>#</span>2
1. Validate that IsDirty === true
1. Delete value from Left <span>#</span>2

Additional repros are in codesandbox

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-dirty-repro-tedbi

**Expected behavior**
IsDirty should be true
Left DirtyFields should equal ['left.1']

**Desktop (please complete the following information):**

- OS: MacOS (10.15.4)
- Browser [Chrome, Firefox]
- Version [Chrome: 84.0, FF: 79.0]

**Comment by RookY2K** [comment]
I've tracked the problem down to this snippet:
```javascript
// src/utils/unset.ts - L45
if (
    currentPathsLength === index &&
    ((isObject(objectRef) && isEmptyObject(objectRef)) ||
      (isArray(objectRef) &&
        !objectRef.filter((data) => isObject(data) && !isEmptyObject(data))
          .length))
) {
    previousObjRef ? delete previousObjRef[item] : delete object[item];
}
```

objectRef is an array of boolean values representing `isDirty`. So it fails the `isObject` filter and results in the entire top level key from object... In the reproduction, that would be `left`. Looking to see if I can grok the purpose of the if statement. The naive fix is to verify that data isn't a boolean before deleting the key. But I don't have enough context into this project to be sure there are no unintended consequences of that check.

**Comment by bluebill1049** [comment]
Thanks, heaps for the issue report, investigation, and solution!

**Comment by bluebill1049** [comment]
Looking a quick look at your example, i don't think we support integer as `key` name.

**Comment by bluebill1049** [comment]
<img width="931" alt="Screen Shot 2020-08-13 at 9 46 20 am" src="https://user-images.githubusercontent.com/10513364/90078956-d8ed4180-dd49-11ea-926b-2d4d01d82bf7.png">
actually we do.

**Comment by bluebill1049** [comment]
I will try to reproduce the problem with correct `name` before assigning a bug as this issue 👍

**Comment by RookY2K** [comment]
The name doesn't start with an integer. The integer comes after the dot.

**Comment by DarkSouls101** [comment]
Yes, it’s the same case. You going to run into issue with key name as integer.

**Comment by bluebill1049** [comment]
> The name doesn't start with an integer. The integer comes after the dot.

Yes, integer for the key name is going to be an issue.

**Comment by RookY2K** [comment]
> > The name doesn't start with an integer. The integer comes after the dot.
> 
> Yes, integer for the key name is going to be an issue.

Fair enough. I'll at least argue that the documentation isn't clear in this regard. In my example `left.1` as the name prop does not violate the constraint that it cannot start with an integer. So we probably want to at least update the wording to be clearer. 

So it's obvious this isn't a bug, but can we change it to a Feature Request? My pull request solved the issue I was having and everything else seems to work as intended. I'll definitely admit that my understanding of all the edge cases is razor thin though. I'd be happy to help with any regression testing.

**Comment by bluebill1049** [comment]
Thanks @RookY2K I think we will go ahead and merge your PR (I will review the PR tonight), but probably still keep the doc as it is. I can't remember exactly when it will create an issue with an integer from memory, but it's probably there.

**Comment by bluebill1049** [comment]
merged. thanks for the PR 🙏

**Comment by karesztrk** [comment]
Hi guys. Can any of your recall the release that fixed the issue? I cannot find the matching PR. Although @RookY2K found it in `v6.3.3`...I'm still experiencing it in `v6.15.8`
