### ISSUE TITLE
TypeError: Incompatible receiver, Set required

### ISSUE THREAD

**Issue by krnlde** [react-hook-form/react-hook-form#2583]
**Describe the bug**
Starting from version `6.3.1` until the current version `6.3.3` I'm not able to use RHF in production. I use parcel-bundler to compile my project and when I start it it'll throw with the message `TypeError: Incompatible receiver, Set required`. It throws from the line https://github.com/react-hook-form/react-hook-form/blob/752d7efce18d6b2e26cbec7c9a1c24aa1ae5eb56/src/useForm.ts#L95

**To Reproduce**
Reproduction is real hard since I don't know what differs from the development runtime where it works as expected. But I use this alias to support IE11 out of the box:
```
  "alias": {
    "react-hook-form": "react-hook-form/dist/index.ie11.production.min.js"
  },
```

**Desktop (please complete the following information):**

- OS: Windows 10 Version 10.0.20185 Build 20185
- Browser: Chromium Edge Version 86.0.605.0

**Additional context**
Quick google says maybe this helps https://github.com/zloirock/core-js/issues/514#issuecomment-561118374

**Comment by bluebill1049** [comment]
can you try to install: `npm i @babel/runtime-corejs3`?

**Comment by krnlde** [comment]
I tried it and it didn't work. But I doubt it can work since I don't explicitly use a .babelrc. It's implicit inside parcel. Also RHF works in development and only doesn't when compiling for production.

**Comment by bluebill1049** [comment]
@kotarella1110 would you have clue on this one?

**Comment by krnlde** [comment]
The next clue is it really only breaks when calling useForm. So its probably not a compile time issue, but rather something "runtimey". Different Set polyfills maybe? I also polyfill that stuff, but in `6.3.0` and before it always worked.

**Comment by bluebill1049** [comment]
@kotarella1110 maybe we don't need this commit? https://github.com/react-hook-form/react-hook-form/commit/9718436ee668da9a49522803d3d490164878dd7f

**Comment by krnlde** [comment]
I'm pretty lost in this one, since its such an edge case. Also I hate IE.

Sorry guys :(

**Comment by bluebill1049** [comment]
nah, no worries @krnlde we will investigate this. 🙏 thanks for all the information.

**Comment by krnlde** [comment]
I tried to do a codesandbox on this one, but it just works :D dang it

**Comment by bluebill1049** [comment]
codesandbox would worked, because it's using the dev build.

**Comment by kotarella1110** [comment]
@krnlde @bluebill1049 I wil investigate this.

**Comment by krnlde** [comment]
yes, but I exported it as a zip and tried to `npm run build` it, which worked. So it's probably some kind of awkward setup of mine... I only can't find which. I don't have any dependency to babel, BUT I do use `"core-js": "3.6.5",` manually and have a `polyfill.js` file which requires `Set` via `import 'core-js/features/set';`.

**Comment by bluebill1049** [comment]
@kotarella1110 if we have a separate ts config, would that resolve this problem (form memory what you did with resolvers)?

**Comment by bluebill1049** [comment]
@krnlde can you please test this beta version: 6.5.2-beta.1

**Comment by krnlde** [comment]
Yes will do now

**Comment by krnlde** [comment]
Quick A/B test reveals `6.5.2-beta.1` works and `6.5.1` as expected doesn't. Great job man and thank you. This day next year IE will be history :)

❤️

**Comment by bluebill1049** [comment]
thanks very much @kotarella1110 🙏 and @krnlde's testing.
