### ISSUE TITLE
formState.isValid flips to true when one field is optional

### ISSUE THREAD

**Issue by sktt** [react-hook-form/react-hook-form#259]
**Describe the bug**
using mode: "onBlur" or "onChange", and one validated and one optional field, isValid flips to true as the first field successfully validates.

**To Reproduce**
1. go to https://codesandbox.io/s/lingering-sky-ycyb9
2. select the optional input
3. select the required input
4. observe formState.valid change!

**Expected behavior**
formState should not change

**Comment by sktt** [comment]
here's the repro, switch between the two inputs and see how it turns valid

https://codesandbox.io/s/lingering-sky-ycyb9

**Comment by sktt** [comment]
I'm pretty sure the issue comes from the check here https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L737

In this case we have 1 valid field (the optional one) and 1 validated field.

Btw, why is everything wrapped in useRef? :smile:

**Comment by sktt** [comment]
actually i think the problem lies here, the test passes when validation options are passed in the second argument. But i'm not sure if that's legacy api since it's not demonstrated in docs afaik.

https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L536-L540

**Comment by bluebill1049** [comment]
thanks for the PR! ❤️ I will take a look into this, if you figure out the fix please send a PR too 😄

**Comment by bluebill1049** [comment]
oops, you are right, it was supposed to be the second argument.

**Comment by sktt** [comment]
aahh so using it as second argument makes the test pass but breakes some other ones that look like this
![image](https://user-images.githubusercontent.com/1434608/63730658-8121a600-c86c-11e9-9cb9-92162bd91cf9.png)

**Comment by bluebill1049** [comment]
ha that's our bad on testing, let me fix this `inValid` issue first 😍

**Comment by bluebill1049** [comment]
@sktt please help on testing :) `react-hook-form@3.22.3-beta.1`

**Comment by sktt** [comment]
Testing, Seems to fix my original issue!

Now I see that isValid will not be true unless all fields also are touched! I'm not sure if its a bug though. Saw this because I have a dropdown which has the first value selected by default.

**Comment by sktt** [comment]
This one can be closed though! Thanks @bluebill1049 :)

**Comment by bluebill1049** [comment]
> Now I see that isValid will not be true unless all fields also are touched! I'm not sure if its a bug though. Saw this because I have a dropdown which has the first value selected by default.

Do you have a codesandbox for this? let's fix it properly for you :) happy to look into it and we do a release with all the fix tonight

**Comment by sktt** [comment]
here you go, should we make another issue?
https://codesandbox.io/s/cool-knuth-osvb3

**Comment by bluebill1049** [comment]
oh, I see the problem, let's raise a separate issue for this. I can look into that as well.

**Comment by bluebill1049** [comment]
I will merge the current PR for this issue.
