### ISSUE TITLE
Checkbox input conditionally rendered with same name holds an array value

### ISSUE THREAD

**Issue by SachaMPS** [react-hook-form/react-hook-form#2591]
**Describe the bug**
Checkbox inputs with the same name but rendered conditionally (e.g. due to different positions in a dynamic form) hold an array as soon as you switch between the views

**To Reproduce**

1. Go to 'https://codesandbox.io/s/react-hook-form-custom-input-forked-wup4k?fontsize=14&hidenavigation=1&theme=dark'
2. Click on 'Select View 2'
3. Click on 'Select View 1'
4. Click on 'submit'
4. See that some_value is an empty array

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

- [Example Sandbox](https://codesandbox.io/s/react-hook-form-custom-input-forked-wup4k?fontsize=14&hidenavigation=1)

**Expected behavior**
false instead of []

**Screenshots**
<img width="1582" alt="grafik" src="https://user-images.githubusercontent.com/305877/90155345-bc1d3200-dd7a-11ea-9659-83e069786c93.png">

**Comment by bluebill1049** [comment]
you after `shouldUnregiser`?

https://codesandbox.io/s/react-hook-form-custom-input-forked-4fneh

**Comment by SachaMPS** [comment]
Seems to make no difference and furthermore it can be that i want other fields to unregister...

The current use case ist that we have a contactWizzard which renders different fields based on the question. Sometimes we need the a textfield input for street name sometimes not. But always a "accept terms" checkbox.

**Comment by bluebill1049** [comment]
<img width="1338" alt="Screen Shot 2020-08-14 at 7 03 33 pm" src="https://user-images.githubusercontent.com/10513364/90233052-dcbfb780-de60-11ea-8aa6-4759906f01a4.png">

perhaps you want to consider just toggle the visibility of those inputs.

**Comment by bluebill1049** [comment]
ok, I read your description again, looks like I misunderstood. 

Yea, this is going to be a tricky one, because we are building a checkbox with the same name, by doing the toggle it will get registered again as another option. I would recommend using a different name to avoid this problem.

**Comment by bluebill1049** [comment]
you can give them a separate `key` to solve this problem.

https://codesandbox.io/s/react-hook-form-custom-input-forked-2gsro?file=/src/index.js
