### ISSUE TITLE
getValues() gives empty object on first 2 renders

### ISSUE THREAD

**Issue by ujjwalbishnoi** [react-hook-form/react-hook-form#2596]
**Describe the bug**

**To Reproduce**

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

- [useForm](https://codesandbox.io/s/react-hook-form-useform-template-lsm61) Template
- [useFieldArray](https://codesandbox.io/s/react-hook-form-usefieldarray-template-q0jek) Template
- [Controller](https://codesandbox.io/s/react-hook-form-controller-template-yu0z5) Template

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RavisaraDev** [comment]
This is happening to me too. I'm using React web version.

**Comment by harshvitra** [comment]
+1 

Once the value is set to something, even if I change my input the getValues data will not update my components unless anything cause re-render.

**Comment by bluebill1049** [comment]
> +1
> 
> Once the value is set to something, even if I change my input the getValues data will not update my components unless anything cause re-render.
> 
> @bluebill1049

getValues() is a static form value look up, it was never meant to subscribe for changes.
<img width="946" alt="Screen Shot 2020-10-27 at 7 10 34 pm" src="https://user-images.githubusercontent.com/10513364/97273978-1ca31200-1888-11eb-9352-9885af77c605.png">

**Comment by harshvitra** [comment]
> getValues() is a static form value look up, it was never meant to subscribe for changes.

I guess we all missed this part, thank you for the prompt reply.

**Comment by bluebill1049** [comment]
> > getValues() is a static form value look up, it was never meant to subscribe for changes.
> 
> I guess we all missed this part, thank you so much for the prompt reply.

np :)
