### ISSUE TITLE
Lost fields registered when using reset method

### ISSUE THREAD

**Issue by phanvantien270290** [react-hook-form/react-hook-form#2597]
**Describe the bug**
   I just want it to show the data to compare with the original data, but when I use the reset method some fields are lost, is there a way for it to always display the property even though it is empty?

**Codesandbox link (Required)**
- [example here](https://codesandbox.io/s/react-hook-form-useform-template-forked-bwzhb) Template

**Desktop (please complete the following information):**

- Version [6.3.3]

**Comment by bluebill1049** [comment]
`reset(getValues())`?
