### ISSUE TITLE
   reValidateMode: 'onChange' is not working on Controller React Native

### ISSUE THREAD

**Issue by areeb-hub** [react-hook-form/react-hook-form#2599]
**Describe the bug**
reValidateMode is not working using controller in react native 

**To Reproduce**

` <Controller rules={{required: true}} control={control} name="deliveredBy" render={({onChange}) => <CustomInput label={'Delivered by*'} onChangeText={value => onChange(value)} error={errors.deliveredBy} />} />
`

```
    "react": "16.11.0",
    "react-hook-form": "^6.3.3",
    "react-native": "0.62.2",

```

On Emulator Ipad Air 3rd Gen

**Comment by bluebill1049** [comment]
can you share expo snack?

**Comment by areeb-hub** [comment]
> can you share expo snack or codesandbox? Controller share the same logic web and RN.
@bluebill1049 
https://snack.expo.io/@areeb-hub/4592cd

**Comment by bluebill1049** [comment]
by the way, reValidateMode is by default, and your snack has errors.

**Comment by bluebill1049** [comment]
Take a look here: https://react-hook-form.com/get-started#ReactNative there is expo link as well.

**Comment by areeb-hub** [comment]
> Take a look here: https://react-hook-form.com/get-started#ReactNative there is expo link as well.

@bluebill1049 can you please check again https://snack.expo.io/@areeb-hub/trembling-juice-box , [Fixed]pkg issue

**Comment by bluebill1049** [comment]
i see your problem. `reValidateMode` is after submit.
<img width="985" alt="Screen Shot 2020-08-14 at 7 00 57 pm" src="https://user-images.githubusercontent.com/10513364/90232767-7e92d480-de60-11ea-8ae5-2b446230b751.png">

i think you want mode: 'onChange'

**Comment by areeb-hub** [comment]
> i see your problem. `reValidateMode` is after submit.
> <img alt="Screen Shot 2020-08-14 at 7 00 57 pm" width="985" src="https://user-images.githubusercontent.com/10513364/90232767-7e92d480-de60-11ea-8ae5-2b446230b751.png">
> 
> i think you want mode: 'onChange'

@bluebill1049 i'm sorry i missed that on doc and thank you for helping out.

https://github.com/react-hook-form/react-hook-form/issues/2599#issuecomment-673971794

**Comment by bluebill1049** [comment]
np :)
