### ISSUE TITLE
Reset does not reset the value in react-select after form submit (v6)

### ISSUE THREAD

**Issue by mg901** [react-hook-form/react-hook-form#2601]
**Bug**
Reset does not reset the value in react-select after form submit.

**To Reproduce**
I enter a value in input and select a value in react select, but after submitting the form, the value in react select is not cleared.

**Codesandbox link**
[example](https://codesandbox.io/s/react-hook-form-with-ui-library-forked-gc4g1?file=/src/index.js)

**Expected behavior**
After submitting the form, the value in react-select should be cleared

**Comment by bluebill1049** [comment]
you are missing some props: https://codesandbox.io/s/react-hook-form-with-ui-library-forked-ydckx?file=/src/index.js

**Comment by mg901** [comment]
@bluebill1049   Thank you very much for your prompt reply. Yes the fields are cleared, but I don't want to receive data from react select as {value: '', label: ""}. I only need value.

**Comment by bluebill1049** [comment]
sure, it's in the example folder :) https://github.com/react-hook-form/react-hook-form/tree/master/examples

https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-furtc

**Comment by mg901** [comment]
@bluebill1049 Thank you!)

**Comment by mg901** [comment]
@bluebill1049, your example is only suitable if the label and value are the same.
[see 68 string](https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-forked-xf018?file=/src/index.tsx). Is there a more elegant solution? Is it planned for the future?

**Comment by bluebill1049** [comment]
what do you try to achieve with react-select? maybe it's better to understand your requirement. as right now, i dont' plan to introduce more props for Controller.

**Comment by mg901** [comment]
@bluebill1049 I want to pick only value in react-select.

**Comment by bluebill1049** [comment]
u will have to do this: https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-forked-fc1bc?file=/src/index.tsx
