### ISSUE TITLE
Fields Arrays with validate if min fields

### ISSUE THREAD

**Issue by majweb** [react-hook-form/react-hook-form#2605]
I warmly welcome.
I am using FieldsArray.
This is an example from the documentation.
https://codesandbox.io/s/react-hook-form-fieldsarray-yup-validation-min-length-57qtb?file=/src/index.js:849-852

I have quit yup and want to use native validation.
The problem is validation and no error if no project is created.

My code
https://codesandbox.io/s/vigorous-almeida-ngp5r?fontsize=14&hidenavigation=1&theme=dark

I see the problem in useeffect but I can be wrong ..

**Comment by bluebill1049** [comment]
for minLength take a look at this example: 

https://github.com/react-hook-form/react-hook-form/tree/master/examples

`Field Array Min Length`

**Comment by majweb** [comment]
I added your link in my question

**Comment by bluebill1049** [comment]
is it working for u?

**Comment by majweb** [comment]
No

**Comment by bluebill1049** [comment]
what bout this example: https://codesandbox.io/s/react-hook-form-fieldsarray-yup-validation-min-length-forked-kb90b?file=/src/index.js?

**Comment by majweb** [comment]
how pass invalid className?

```
      <input
            ref={register()}
            name={`questions[${questionIndex}].text`}
            control={control}
            defaultValue=""
            className={`form-control ${`questions[${questionIndex}].size` ? "is-invalid" : ""}`}
          />
```

**Comment by bluebill1049** [comment]
that's looks right for individual error.
