### ISSUE TITLE
Reset values with Date merged incorrectly

### ISSUE THREAD

**Issue by pzs** [react-hook-form/react-hook-form#2609]
**Describe the bug**
Submit called with incorrect values, when reset was called previously and form value contains Date object.

**To Reproduce**

1. Go to https://codesandbox.io/s/vibrant-worker-wj4lq
2. Click on "reset"
3. Change date in the input field
4. Click on "Submit"
5. Observe console:
Actual: Date provided in reset method is displayed
Expected: Actual value of input field is displayed

**Codesandbox link (Required)**
https://codesandbox.io/s/vibrant-worker-wj4lq

**Expected behavior**
Actual value of input field is returned/displayed

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Firefox latest

**Additional context**
- `shouldUnregister`: false
- I observe this issue from 6.3.0; it was working in 6.2.0
- most likely utils/deepMerge merge Date objects incorrectly

**Comment by bluebill1049** [comment]
This is expected result as far as i can tell, it's what's MUI returned `value`.

**Comment by pzs** [comment]
I added a console.log to the "onChange" method inside MUI field. It is called with the correct date when you change the field, however submit returns the previous value (what was passed inside the reset method):

https://codesandbox.io/s/eloquent-dhawan-018cu?file=/index.js:900-936

**Comment by bluebill1049** [comment]
> I added a console.log to the "onChange" method inside MUI field (line 28). It is called with the correct date when you change the field, however submit returns the previous value (what was passed inside the reset method):
> 
> https://codesandbox.io/s/eloquent-dhawan-018cu?file=/index.js:900-936

steps to reproduce, i couldn't reproduce with your reported steps.

**Comment by pzs** [comment]
Steps are the same, please check this screen recording: https://streamable.com/eezwrp
Expected value in the console: Aug 01 (as it's in the field)
Actual value: Aug 15

**Comment by bluebill1049** [comment]
Thanks for the video! it helps.

**Comment by pzs** [comment]
Thanks for this quick fix and this library!
