### ISSUE TITLE
Reset form / SetValues, after submit in a ionic controlled components context

### ISSUE THREAD

**Issue by clementvp** [react-hook-form/react-hook-form#2611]
**Describe the bug**
Hello, I try to reset form after submit and validate my form. But i'm not able to do that.

I'm missing something?

**To Reproduce**

See the sandbox, i try to reset the email field with an empty string.

**Codesandbox link (Required)**

You can see a minimal sandbox [here](https://stackblitz.com/edit/ionic-react-hook-form-ujq2r7?file=src/App.tsx)

**Expected behavior**
The email field is cleared and value is "".

**Additional context**
Working with ionic 5 plus TS.
Working with controlled element.

Based on these article:
[here](https://dev.to/ionic/using-react-hook-form-with-ionic-react-components-update-1463)

RHF version is (according to my package.json : 6.3.0)

**Comment by bluebill1049** [comment]
please clean up your example, there are so many components and doesn't make my life easier to investigate this issue, from quick glance you are missing `value` prop at `Controller`.

**Comment by clementvp** [comment]
Sorry for the sloppy sandbox. You were right, i forgot to pass the value prop. Thx again. RHF is so great and so less painfull than others. Keep going ;)

**Comment by bluebill1049** [comment]
awesome, glad to hear :)
