### ISSUE TITLE
fields from useFieldArray with init values not working in 6.4.0 but in v. 5.7.2

### ISSUE THREAD

**Issue by kle-dev** [react-hook-form/react-hook-form#2614]
**Describe the bug**
I'm using `fields` from the `useFieldArray` method which is initialized with default values. 

However in v. 5.7.2 the default values are showing up **but not in v. 6.4.0**...

**To Reproduce**
Look in the Sandbox:

**v. 6.4.0 (not working)**
[![Edit recursing-cerf-sgk4m](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recursing-cerf-sgk4m?fontsize=14&hidenavigation=1&theme=dark)

**v. 5.7.2 (working)**
[![Edit epic-ride-3rxbk](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/epic-ride-3rxbk?fontsize=14&hidenavigation=1&theme=dark)

**Codesandbox link (Required)**
see above

**Expected behavior**
like in v. 5.7.2 show up init variables

**Comment by nghiepit** [comment]
I have the same issue.

From `6.3.0` and earlier work fine.

**Comment by kle-dev** [comment]
yes you're right, 6.3.0 and bellow...

thought first this would be an failure vom v. 5 to v. 6 but its a failure from v. 6.3.0 upwards

**Comment by bluebill1049** [comment]
it's working and you are missing `defaultValue`: https://codesandbox.io/s/xenodochial-galois-jn6gm?file=/src/Materials.js

**Comment by bluebill1049** [comment]
please use Controller as well for external controlled inputs.

**Comment by kle-dev** [comment]
hey, thanks for helping.

Thats a sandbox, sadly in my real project I can't pass the material down to the component like you did in your sandbox...

I tried it with a controller:
```
    <Controller
    name={`project.materials[${index}].manufacturer`}
    render={(props) => (
      <TextField
        {...props}
        defaultValue={props.value}
        label="manufacturer"
        multiline
        margin="normal"
        fullWidth
        required
        control={control}
        InputLabelProps={{ shrink: true }}
        inputRef={register({ required: true, maxLength: 75 })}
        inputProps={{ minLength: 1, maxLength: 20 }}
      />
      )}
    />
```

but I got 

```
ð Controller is missing `defaultValue` prop when using `useFieldArray`. 
    in Controller (at Material.js:9)
    in Material (at Materials.js:12)
    in Materials (at App.js:24)
    in App (at src/​index.js:9) 
```

I can't set the default value because I dont have it there while I can't pass material down...

here that example:
[![Edit loving-tdd-bvk4u](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/loving-tdd-bvk4u?fontsize=14&hidenavigation=1&theme=dark)

I don't unterstand why the old way is not working anymore since > v 6.3.0.

**Comment by bluebill1049** [comment]
```
<Controller
    name={`project.materials[${index}].manufacturer`}
    render={(props) => (
      <TextField
        {...props}
        defaultValue={props.value}
        label="manufacturer"
        multiline
        margin="normal"
        fullWidth
        required
        control={control}
        InputLabelProps={{ shrink: true }}
        inputRef={register({ required: true, maxLength: 75 })}
        inputProps={{ minLength: 1, maxLength: 20 }}
      />
      )}
    //defaultValue={xxxx} you are missing here
 />
```

we fixed a bug from 6.3.0 with nested input and delete with useFiedlArray, could you pass `materials` down as prop like what i did in the example?

**Comment by kle-dev** [comment]
as I already said, sadly no I can't pass it down ... may I can ... but that will change a lot of logic in my code with a lot of effort

**Comment by kle-dev** [comment]
in my edit text , sorry I edited it after I send it to you, may you only had read the email text

**Comment by kle-dev** [comment]
but if you say I must pass it down .. then I have to do it .. I think its a effort to fix it too ... I dont now weather it is expected behavior for you or not

**Comment by bluebill1049** [comment]
I would suggest staying 6.3.0 for now.

**Comment by bjarkehs** [comment]
@bluebill1049 is this expected behaviour or is it simply a missing feature?

**Comment by bluebill1049** [comment]
> @bluebill1049 is this expected behaviour or is it simply a missing feature?

It's expected behavior.

**Comment by bjarkehs** [comment]
> It's expected behavior.

My bad, I should have written: Is this intended behavior?

Because if it's intended behavior it creates a confusing API, where you think defaultValues can be provided to useForm and be available in useFieldArray inputs too. But as it right now you'll have to also pass the defaultValue in certain scenarios, even when defaultValues are provided in useForm.

This is especially a tedious API if you have nested inputs such as:
addresses[0].city

If you are editing a form with an input like this, then you have to pass it down. 😢

**Comment by bjarkehs** [comment]
Let me elaborate why I'm a little saddened by this design.

I'm currently working on a test gui, where I want to be able to reuse "input components", like an `AmountInput` which renders 2 inputs: currency and value. This component I'd love to be able to use as a single input: `account.balance` or in an array: `transactions[0].amount`.

If I want to support both scenarios I have to basically always provide a defaultValue and provide `register` as: `ref={register()}`. The latter I don't mind, but needing to provide a defaultValue makes the API a lot more cumbersome to work with.

**Comment by bluebill1049** [comment]
Thanks for the detail, but you will need to supply `defaultValue`. It's uncontrolled input and to avoid other related bugs.

**Comment by bjarkehs** [comment]
> Thanks for the detail, but you will need to supply `defaultValue`. It's uncontrolled input and to avoid other related bugs.

Fair enough. I guess I can just pass in an amount which can be undefined. If defaultValue is `undefined` and the input is not in a useFieldArray it will use the value in defaultValues provided with useForm, correct?

**Comment by bluebill1049** [comment]
> > Thanks for the detail, but you will need to supply `defaultValue`. It's uncontrolled input and to avoid other related bugs.
> 
> Fair enough. I guess I can just pass in an amount which can be undefined. If defaultValue is `undefined` and the input is not in a useFieldArray it will use the value in defaultValues provided with useForm, correct?

what about empty string `''`?

**Comment by bjarkehs** [comment]
> > > Thanks for the detail, but you will need to supply `defaultValue`. It's uncontrolled input and to avoid other related bugs.
> > 
> > 
> > Fair enough. I guess I can just pass in an amount which can be undefined. If defaultValue is `undefined` and the input is not in a useFieldArray it will use the value in defaultValues provided with useForm, correct?
> 
> what about empty string `''`?

I was thinking something like this: https://codesandbox.io/s/charming-golick-oz1oe?file=/src/Transactions.js

It seems to work. Then I can get around it by creating my own context with the defaultValues.

Thanks for a great library!
