### ISSUE TITLE
Two way data binding error

### ISSUE THREAD

**Issue by sureshdeepalh** [react-hook-form/react-hook-form#2623]
After submit the foerm I can get the error. But  when I'm doing the two way data binding first key entered letter not print on input field. Second key entered it will work. 
```
<FormGroup>
                    <FormLabel>User Name</FormLabel>
                    {errors.email ? <span>{errors.email.message}</span> : null}
                    <FormControl
                        ref={register({
                            required: {
                                value: true,
                                message: "Email is reqired",
                            },
                            pattern: {
                                value: /\S+@\S+\.\S+/,
                                message:
                                    "Entered value does not match email format",
                            },
                        })}
                        type="text"
                        name="email"
                        value={form.email}
                        onChange={handleChange}
                    />
                

> </FormGroup>
```
Here is the CodeSandbox link
https://codesandbox.io/s/peaceful-newton-f0sng?file=/src/App.js

**STEP TO GET THE ERROR**
1. Type letter and send the form (This will work properly)
2. Try to backspace letters, then issue you can see. **first  backspace key press letter will not erase**. And second backspace key press will erase letter.
3. After delete all letters try to enter a letter. **same issue first key press it will not apear**.

Is it bug???? 

Or any way to solve it on my side. please help.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/faqs#Whyisfirstkeystrokeisnotworking

Take a look at the FAQ above. Not a bug.

**Comment by sureshdeepalh** [comment]
Hi It may not a bug. but how can I change value from some other place. 
![image](https://user-images.githubusercontent.com/14823751/90353849-0ba67b00-e065-11ea-81d7-3ce9f234dd60.png)

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#watch

**Read the doc.**

**Comment by sureshdeepalh** [comment]
Thanx a lot @bluebill1049 
I fixed my requirement by using **setValue**
https://react-hook-form.com/api/#setValue
