### ISSUE TITLE
Eventlistener on Controller not working

### ISSUE THREAD

**Issue by Parrakh** [react-hook-form/react-hook-form#2629]
**Description:**

If i use any of the listener, e.g. onChange, onBlur, it doesn't work on <Controller />-elements. Form elements registered with the "register" function are fine. I use currently MaterialUI. 

**Reproduce:**

https://codesandbox.io/s/react-hook-form-v6-controller-forked-egfq6

I modified the current MaterialUI-Sandbox with a onBlur-function on the MaterialUI-Textfield. (MUI TextField)

`<Controller
          as={TextField}
          name="TextField"
          control={control}
          onBlur={() => console.log("blur")}
        />`

** Desktop:**

- OSX 10.15.6
- Chrome 84.0.4147.105

**Comment by bluebill1049** [comment]
use `render` props. https://react-hook-form.com/api/#Controller

**Comment by Parrakh** [comment]
Was the feature removed? I tried an old version and it works fine. Sandbox of version 5:

https://codesandbox.io/s/react-hook-form-controller-forked-ojtc7

**Comment by bluebill1049** [comment]
yes: https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md
