### ISSUE TITLE
Unexpected behaviour when using `reset()` with third party UI library

### ISSUE THREAD

**Issue by smhutch** [react-hook-form/react-hook-form#2637]
First off I want to say that I'm really enjoying this library, and that I'm not 100% sure if this is a bug, or if it's something I'm misunderstanding. 🙂

**Describe the bug**
I'm working on a form which has two "submit" buttons. One to "Save" and another to "Save and add another". The "Save" button is a regular button with `type=submit`, the other is a button with an `onClick` handler. When clicking on "Save and add another" I'm trying to reset the form, to allow users to quickly fill it out a second/third/etc time. The issue I'm encountering occurs when re-submitting after the first submission. During these additional submissions, I see either stale or invalid data in `formState`.

**To Reproduce**

1. View [this sandbox](https://codesandbox.io/s/condescending-sun-bt9gq?file=/src/App.js)
2. Open the console. The example logs the `formState` on submission.
3. Enter any values into the three inputs, submit the form. It works as expected. ✅
4. Submit it with "Save and add another". It submits the form and clears the inputs. ✅
5. Now **only** fill out the first and second inputs and re-submit (using either button).
6. ⚠️ **Issue 1** is that the `example2` value is not included in the `formState` within the submit handler.
7. ⚠️ **Issue 2** is that the `example3` value is stale. It's using the value filled out before calling `reset()` 

**Codesandbox link (Required)**
[Sandbox](https://codesandbox.io/s/condescending-sun-bt9gq?file=/src/App.js)

**Expected behavior**
After calling `reset()`, and submitting a second time, all form values are included in `formState`

**Desktop**

- OS: macOS Catalina
- Browser: FireFox
- Version v79

**Additional context**
In my example, I'm using two methods to work with the UI library we use ([Elastic Eui](https://elastic.github.io/eui/#/forms/form-controls)). In most forms, the following approach has been working well:

```jsx
<EuiFieldText inputRef={register({ required: true })} name="example2" />
```

Since this approach causes missing values when re-submitting, I tried to move to the `Controlled` approach:

```jsx
<Controller
    as={EuiFieldText}
    name="example3"
    control={control}
    defaultValue=""
    rules={{
    required: true
  }}
/>
```

Currently I am working around this by taking the following approach:

```diff
- reset()
+ setValue('fname', '')
+ setValue('lname', '')
+ setValue('email', '')
+ setValue('employeeId', '')
```

This seems to be working fine, but isn't ideal.

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report, for external component please use `Controller`. `inputRef` could be not reliable as native input's `ref`, it depends on the lib's implementation.

for `reset` you can supply values as an argument as well.
```
- reset()
+ reset({})
```

**Comment by smhutch** [comment]
Thanks for your quick response @bluebill1049. Looks like `inputRef` on the `EuiFieldText` was causing an unexpected side-effect.

I have updated my form to use `Controller`, and now a plain `reset()` is working as expected 🎉 . Some examples of my code in case anyone else stumbles on the same issue with Elastic.

```tsx
const { control, handleSubmit, errors, reset } = useForm({
    defaultValues: {
      fname: '',
      lname: '',
      email: '',
      employeeId: ''
    }
  });

// ...

// within JSX:
<Controller
  as={EuiFieldText}
  control={control}
  disabled={submitting}
  rules={validators.fname}
  isInvalid={!!errors.fname}
  name="fname"
/>
```

**Comment by bluebill1049** [comment]
awesome mate! thanks for sharing too.
