### ISSUE TITLE
Dynamic form fields rendering issue

### ISSUE THREAD

**Issue by rc-chandan** [react-hook-form/react-hook-form#2643]
**Describe the bug**
- I have a scenario where I want to render different input fields depending on the value user selects on a dropdown which is also part of the form.
- Even if input names completely change, this does not rerender the prop input fields.
- Might be some memoization and rerender logic issue in react-hook-form.

**To Reproduce**
1. Open this code sandbox link given below
1. Change the form type select field
1. Form data passed via props should reflect in the form fields rendered by react-hook-form and `getValues()` output.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-issue-2643-3rwuf

**Expected behavior**
On changing the form type, new fields from the given form data should be rendered by react-hook-form

**Screenshots**
![image](https://user-images.githubusercontent.com/10782742/90553421-fa1eb980-e1b1-11ea-9e0b-293f439e9e59.png)

**Desktop:**
- MacOS Catalina Version 10.15.5 (19F101)
- Edge Version 84.0.522.49 (Official build) (64-bit)

**Comment by bluebill1049** [comment]
give each input a unique key, have a read this section: https://react-hook-form.com/faqs#Whyisdefaultvaluenotchangingcorrectlywithternaryoperator
