### ISSUE TITLE
[FormState - DirtyFields/isDirty] Input type === 'number' causes dirtyFields to behave like "touched".

### ISSUE THREAD

**Issue by RookY2K** [react-hook-form/react-hook-form#2644]
**Describe the bug**
When using an input with type = 'number', any field that has a default value set via `useForm` parameters will show as dirty once focused and blurred. Empty number inputs and those with defaultValue set on the input behave as expected. 

**To Reproduce**

1. Get focus on a number input that had a default set via the useForm defaultValues parameter
2. Blur that component
3. See that isDirty is true and the just blurred input name is now in the dirtyFields object.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-forked-m2qth

**Expected behavior**
Unchanged input should result in isDirty being false and an empty dirtyFields object.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser [Chrome, Firefox]
- Version [C: 84.0.4147.125, FF: 79.0]

**Comment by RookY2K** [comment]
So, I figured out why this occurs.

In `useForm.ts` > `setDirty`

```javascript
const isFieldDirty =
        defaultValuesAtRenderRef.current[name] !==
        getFieldValue(fieldsRef, name, unmountFieldsStateRef);
```

defaultValuesAtRenderRef.current[name] will return as whatever the type used in the `defaultValues` parameter of `useForm`. Whereas `getFieldValue` will always return as a string. 

My guess is that this isn't an issue limited to `input[type="number"]` and in fact is a problem with `defaultValues` having a non-string value set for the `input` element. I'll be checking to confirm this before I update the issue title. 

The question becomes are we ok using loose equality in the above `isFieldDirty` check? I think the complexity added by trying to cast getFieldValue to the right type would be rather immense. 

I'm going to make the change and see how tests fair. We can discuss the merits of the change (or alternatives) here or in the PR.

**Comment by bluebill1049** [comment]
we only support native input to be "string" type. If you want to parse value: https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-furtc (in the examples folder)

**Comment by RookY2K** [comment]
Hmm, I 100% support the idea that the value for native inputs are of type "string" since that is how the actual input would work outside the framework of `react-hook-form`. I'm less sanguine about setting a default value via the `useForm` hook and it breaking dirty checks. 

It is well understood that you can set a value/default value for a native input with a "number" type but you will get a "string" type back in `onChange` callbacks or ref inspections. But you _are_ able to set those inputs with a "number" value/default value. The `defaultValues` parameter for `useForm` should work the same as the native input's `defaultValue`. 

_If_ we want to accept that inconsistency, we, at a minimum need to document that constraint. I couldn't find any mention of that limitation in the API, Advanced, or FAQ sections. I'd advocate going a step further and adding a development only console warning of a type mismatch between the defaultValue and fieldValue. I'd be happy to submit a PR for that if that's the chosen route.

Before accepting that we can't make things consistent, I'd ask that someone look at my PR: #2645. I'll fully admit that I don't have the context or domain knowledge to determine what edge cases may be broken by my proposed change. However, with my current understanding, I'm not seeing any obvious issues.

**Comment by bluebill1049** [comment]
> _If_ we want to accept that inconsistency, we, at a minimum need to document that constraint. I couldn't find any mention of that limitation in the API, Advanced, or FAQ sections. I'd advocate going a step further and adding a development only console warning of a type mismatch between the defaultValue and fieldValue. I'd be happy to submit a PR for that if that's the chosen route.

That's a great idea! let's work toward that. 

- improve documentation
- console.warn at development env.

> Before accepting that we can't make things consistent, I'd ask that someone look at my PR: #2645. I'll fully admit that I don't have the context or domain knowledge to determine what edge cases may be broken by my proposed change. However, with my current understanding, I'm not seeing any obvious issues.

I did look your PR :)

**Comment by RookY2K** [comment]
I'll put together something tomorrow for the console.warn.

**Comment by bluebill1049** [comment]
Yes, going to reject #2645

**Comment by bluebill1049** [comment]
before you start to prepare a PR, please wait for this PR to be merged: https://github.com/react-hook-form/react-hook-form/pull/2600 🙏

**Comment by RookY2K** [comment]
> Yes, going to reject #2645

As a learning opportunity, would you mind sharing your concerns? 

> before you start to prepare a PR, please wait for this PR to be merged: https://github.com/react-hook-form/react-hook-form/pull/2600 🙏 

Will do!

**Comment by bluebill1049** [comment]
> > Yes, going to reject #2645
> 
> As a learning opportunity, would you mind sharing your concerns?

We should be aligned with what our intension here if the lib decided to support only `string` with native input, it would be best not leave a backdoor.

**Comment by bluebill1049** [comment]
I will update the doc to emphasis this as well.

**Comment by bluebill1049** [comment]
<img width="898" alt="Screen Shot 2020-08-20 at 8 28 05 am" src="https://user-images.githubusercontent.com/10513364/90696111-13f9f280-e2bf-11ea-8f98-b89946b43d56.png">

Doc is updated.

**Comment by bluebill1049** [comment]
going to close this issue now, feel free to follow up with dev warning PRs or doc improvement, just be mindful that `Controller` doesn't have an issue with return type, only have native inputs. 👍
