### ISSUE TITLE
useWatch not update if defaultValue is setted and Form have defaultValues

### ISSUE THREAD

**Issue by saculbr** [react-hook-form/react-hook-form#2646]
**Describe the bug**
if a form created with defaultValues, and a useWatch hook subscribe to the field, and, the useWatch provide their own defaultValue property, the form value from the hook is not update after the render
```javascript
const { register, control, handleSubmit } = useForm<FormInputs>({
    defaultValues: {
      firstName: "Not the default Hook value"
    }
  });

const firstName = useWatch({
    control,
    name: "firstName",
    defaultValue: "default" // default value before the render <<<<<< **NOT updated after the render**
  });
```

```javascript
const { register, control, handleSubmit } = useForm<FormInputs>({
    defaultValues: {
      firstName: "Not the default Hook value"
    }
  });

// **UPDATED after the render**
const firstName = useWatch({
    control,
    name: "firstName",
    // defaultValue: "default" <<<<<< commented
  });
```

**Codesandbox link**
Include a codesandbox will help us to investigate the issue quicker.

- [Codesandbox with both form and hook with default values](https://codesandbox.io/s/youthful-voice-69gr2?file=/src/index.tsx)
- [Codesandbox without the hook defaultValue property](https://codesandbox.io/s/upbeat-hill-lw4rj?file=/src/index.tsx)

**Expected behavior**
Update the defaultValue of hook after the render, based on Form defaultValues

**Comment by bluebill1049** [comment]
`useWatch` defaultValue takes over `useForm` level

**Comment by saculbr** [comment]
oh thanks for the answer, it's a bit weird behavior

**Comment by bluebill1049** [comment]
you shouldn't need to define useWatch defaultValue if you have set up already at useForm level.

**Comment by saculbr** [comment]
Yep, but if I have defaultvalue at useForm level, I think that value from hook should be overridden by the useForm

**Comment by saculbr** [comment]
Only return the useWatch defaultValue if the field is undefined at useForm level
