### ISSUE TITLE
select input count as dirty even after return to the default value

### ISSUE THREAD

**Issue by itamardavidyan** [react-hook-form/react-hook-form#2648]
**Describe the bug**
When I init the form I pass to `useForm` `defaultsValues`, then I click on the select input and choose option (not the default value) and the formState get `isDirty=true` (good :+1: ) BUT then I click (again) on the select input and choose the default value from the select options but the formState still get `isDirty=true` (bad :-1: ) 

**Codesandbox link (Required)**
--> https://codesandbox.io/s/react-hook-form-select-input-bug-rdsh0

- OS: Ubuntu 20.04
- Browser: chrome

**Comment by bluebill1049** [comment]
HTML select produce `string`: defaultValues: { num: "2" }
