### ISSUE TITLE
per input validation mode

### ISSUE THREAD

**Issue by sktt** [react-hook-form/react-hook-form#265]
**Is your feature request related to a problem? Please describe.**
I want to trigger validation onChange to update isValid when checking checkbox or selecting a value in dropdown. But in general, ie text inputs I only want to validate onBlur, which is the normal case that i've provide to `useForm`.

**Describe the solution you'd like**
I imagine some kind of interface where we do `register({mode: onChange })` to input

**Describe alternatives you've considered**
I can possibly trigger onBlur programmatically onChange to update formState

**Comment by bluebill1049** [comment]
hey @sktt I did consider about such API before, but I didn't go for it. It does introduce more complicity to the code base and API. I would recommend using `onBlur` with `setValue('name', 'value', true)`

**Comment by bluebill1049** [comment]
hey @sktt , per input validation mode should occur at `onChange` `onBlur` level, I am going to close this issue for now for the sake of keeping API simple :) feel free to reopen or leave comments if you still have a concern or better suggestion/solution.
