### ISSUE TITLE
Copying array fields with nested array fields inside them

### ISSUE THREAD

**Issue by vangelov** [react-hook-form/react-hook-form#2650]
**Describe the bug**
If you're using a field array whose items in turn have another nested field array if you try to copy the top-level item the nested items are not copied.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-jfo96?file=/src/fieldArray.js
2. Click on the first 'Copy' button
3. Scroll down to the bottom and you can see the item is copied but not the nested items

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-jfo96?file=/src/fieldArray.js

**Expected behavior**
I'm not sure if this should work or not, but it seems that it should.

**Desktop:**

- OS: Mac OS X
- Browser Chrome
- Version 84.0.4147.105

**Additional context**
My use case is that I have a form which contains sub forms and in turn these sub forms can have items inside them. I need to be able to. copy the whole subform together with the nested items inside it.

**Comment by bluebill1049** [comment]
each useFieldArray hold its own reference, if you want to copy nested field array, then you need to nested field array's method.

**Comment by vangelov** [comment]
Can you please elaborate more on what you mean by 'you need to use nested field array's method.'

**Comment by bluebill1049** [comment]
```
const { append: parentAppend } = useFieldArray({})
const { append: childAppend } = useFieldArray({})

parentAppend({ })
childAppend({ })
```

@vangelov this is what i meant, it doesn't work with `append({ test:  [{ nested: [ ] }] }})`

**Comment by vangelov** [comment]
Thank you, but how will this solve the problem where the parent already has children?

In my situation I have a parent that has children. I want to copy the parent along with any children already belonging to it. 

I tried several apporaches but I just can't make it work.

**Comment by bluebill1049** [comment]
here is a working version with `reset()`, although append with the child should work as well, what I stated remains the same. each `useFeldArray` has it's own reference, it doesn't work with nested data like what you suggested above.

**Comment by vangelov** [comment]
Ah..I see now. Never thought that using reset will do the trick. Thank you very much for all your help and fast responses, really appreciated!

**Comment by bluebill1049** [comment]
no worries @vangelov 👍

**Comment by vangelov** [comment]
The only problem I see is with the 'isDirty' property. It does not get set 'true' when a parent is copied which makes sense as we're actually resetting the form. It can be manually set after the copy, but then what happens when you delete a parent item -- if it's the newly added isDirty should be false, but if it's the first one, it should stay true.

Do you think that it makes sense to add a 'copy(index)' method to the useField array that copies a parent item along with any children and updates the isDirty property correctly?

**Comment by bluebill1049** [comment]
have a look at the doc: https://react-hook-form.com/api#reset you can omit.

**Comment by vangelov** [comment]
Yes, but I want to set 'isDirty' to 'true' when a copy is made and then set it back to 'false' if the copy is deleted. But if the original was deleted it should stay 'true'.

**Comment by vangelov** [comment]
Essentially it should work the same way isDirty works for array fields when using append/remove

**Comment by vangelov** [comment]
The problem with adding  dirtyFields: true to reset in this case is that if isDirty is false before the copy is made it will stay false after the copy

**Comment by bluebill1049** [comment]
then going back to what I suggested early on separate `append`: https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-qjqde?file=/src/fieldArray.js

**Comment by vangelov** [comment]
Thank you, I'll try this approach

**Comment by vangelov** [comment]
This example works, but only with a single child item. If you have more than one, you need to call 'append' in the 'useEffect' hooks multiple times which does not work unfortunately.
