### ISSUE TITLE
Some default values are not included in the final data

### ISSUE THREAD

**Issue by SergeyWebDeveloper** [react-hook-form/react-hook-form#2651]
I beg your pardon for my stupid question, but when I set the default values to which the fields are not assigned, their values are not in the final data. Is this done on purpose?

Example - https://codesandbox.io/s/react-hook-form-reset-v6-forked-gbc6h?file=/src/index.js

In `onSubmit` I would like to wait for the next data:
```
{
	firstName: "value",
	lastName: "value",
	include: "1111",
    include2: "22222"
}
```
Thanks!

**Comment by saculbr** [comment]
By default, when an input is removed (or not rendered), React Hook Form uses detect that field and unregister the input(s).

However, you can set shouldUnregister to false to maintain the input state even when unmounting occurs or you dont want to render that field.

```javascript
  const { register, control, handleSubmit } = useForm({
    shouldUnregister: false
  });
```

**Comment by SergeyWebDeveloper** [comment]
@saculbr , I still don't understand how this can help me. I tried as you advised and did not get the values of the fields, which are specified in the default value.

**Comment by bluebill1049** [comment]
combine your default values at submit or put them into input type="hidden"
