### ISSUE TITLE
Setting shouldUnregister to false unregisters useFieldArray values

### ISSUE THREAD

**Issue by ZachMayry** [react-hook-form/react-hook-form#2652]
**Describe the bug**
When setting `shouldUnregister` on a form, `useFieldArray` still unregisters and clears all the values when it remounts.

**To Reproduce**

1. Go to codesandbox link
2. Click on append
3. Add a value
4. Click on unmount
5. Click on mount
6. See error

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-pgfif?file=/src/index.js

**Expected behavior**
Values entered in step 2 & 3 should be retained

**Desktop:**
MacOS
Firefox 80.0b7
Chrome 84.0.4147.125

**Comment by bluebill1049** [comment]
we are not supporting useFieldArray at the moment. It's on the todo list:
<img width="386" alt="Screen Shot 2020-08-20 at 7 51 34 am" src="https://user-images.githubusercontent.com/10513364/90693337-fa09e100-e2b9-11ea-8d8d-8c006159d500.png">
