### ISSUE TITLE
MUI KeyboardDatePicker inside Controller is returning +1 day

### ISSUE THREAD

**Issue by cargallo** [react-hook-form/react-hook-form#2653]
Hi, I detected a problem in my code. I'm using RHF with MUI date picker. It seems that the value returned in the submit of RHF is adding one day. I think it's related to timezones but then I was searching in slack and found this conversation. 

https://spectrum.chat/react-hook-form/help/material-ui-keyboard-datepicker-controller-onchange-and-default-value-issue~f236f08a-60d9-422d-b373-c31a36e9245f?authed=true

So I opened the code that @bluebill1049 put in there and it is happening there too.

You can test it here https://qsd8r.csb.app/, if you select a date from MUI component, then the submit returns +1 day. I'm from Buenos Aires, Argentina. The time zone here is -3. I don't know if that has something to do with it. 

It doesn't happen if I use KeyboardDatePicker outside Controller.

![image](https://user-images.githubusercontent.com/13320290/90702730-60631500-e262-11ea-876b-cd6b28ea6ea5.png)
![image](https://user-images.githubusercontent.com/13320290/90702746-6d800400-e262-11ea-901a-3160e8a2d466.png)

My code in **typescript**

```TSX
<Controller
                  as={
                    <KeyboardDatePicker
                      label="Fecha de Ingreso"
                      required
                      format="dd/MM/yyyy"
                      clearable
                      inputVariant="outlined"
                      error={!!errors.fechaIngreso}
                      onChange={() => { }}
                      value={() => { }}
                      helperText={errors.fechaIngreso && errors.fechaIngreso.message}
                    />
                  }
                  name="fechaIngreso"
                  control={control}
                />
```

**Comment by bluebill1049** [comment]
Thanks, @cargallo.

hmmm I don't think this is related to React Hook Form, we only get the value from the component and there is no parse/format in the code.

**Comment by cargallo** [comment]
I thought that at first but then I tested with momentjs and the same happened. Look at this example where I duplicate the MUI Date picker but outside controller. It's showing the correct date in alert inside onchange.

https://codesandbox.io/s/react-hook-form-v6-controller-forked-xrq7t?file=/src/Mui.js

**Comment by bluebill1049** [comment]
I don't know why this is an issue :( but render fix the problem: https://codesandbox.io/s/react-hook-form-v6-controller-forked-fm9bi?file=/src/Mui.js

**Comment by bluebill1049** [comment]
i will update the example as well.

**Comment by cargallo** [comment]
Hmmmm here I'm still seeing the date with +1 day in submit

**Comment by bluebill1049** [comment]
<img width="1073" alt="Screen Shot 2020-08-20 at 2 18 36 pm" src="https://user-images.githubusercontent.com/10513364/90716324-0c067680-e2f0-11ea-9316-8a404662c7c4.png">

<img width="732" alt="Screen Shot 2020-08-20 at 2 18 53 pm" src="https://user-images.githubusercontent.com/10513364/90716344-16c10b80-e2f0-11ea-9a1a-7b6066884c1b.png">

**Comment by cargallo** [comment]
@bluebill1049 I think the problem resides in time zone. You are at +11 so the day doesn't differ but I'm in -3 time zone it changes the date. Try changing your PC time zone to -3.

**Comment by bluebill1049** [comment]
if time zone related why its related with Controller, really strange stuff...

**Comment by bluebill1049** [comment]
<img width="1424" alt="Screen Shot 2020-08-20 at 4 42 48 am" src="https://user-images.githubusercontent.com/10513364/90717652-6d7c1480-e2f3-11ea-91dc-268ef2bfb51b.png">
![Uploading Screen Shot 2020-08-20 at 4.43.14 am.png…]()

are you using this example: https://codesandbox.io/s/react-hook-form-v6-controller-forked-fm9bi?file=/src/Mui.js?

**Comment by cargallo** [comment]
Sorry yesterday was very late here, I went sleep. Yes I'm using that example. I tested it again now I paste you the screens.

This is the alert inside controller. Note the 11 marked in red there. It's strange it should be 00 

![image](https://user-images.githubusercontent.com/13320290/90769090-0e53db00-e2c6-11ea-9fa6-ad091393a134.png)

This is the alert outside controller. Note that the controller is altering the value somehow, otherwise the two alert should show the same output.

![image](https://user-images.githubusercontent.com/13320290/90769139-2297d800-e2c6-11ea-8a57-2614cc7a0bfc.png)

This is the submit result of inside controller date picker. If the 11 red marked in the first image was a 00 as it should be, here the date would be 2014-08-01T00:00:00.000Z without that eleven. The eleven is added and then it's transforming the date from 00:00 AM to 00:11, so switched to next day.

![image](https://user-images.githubusercontent.com/13320290/90769191-380d0200-e2c6-11ea-902b-f0245a059f67.png)

I agree with you that this is really strange behaviour, but I think this is related to the way that controller is retrieving and setting value in the component. I inspected the controller code but can't figure out why this is happening.

**Comment by bluebill1049** [comment]
lol, it's all good. it's late here. would you like to try with `setValue`? see this issue is going away? I will take a look tmr morning.

**Comment by cargallo** [comment]
@bluebill1049 I found the problem. To initialize the default value of date picker (not datetimepicker), it has to be in this way (without hours, mins and seconds). For example, 

const defaultValues = {
    muiDatePicker1: new Date("2020-08-01T00:00:00"),
    muiDatePicker2: new Date(new Date().setHours(0, 0, 0))
}

In the sandbox where we were testing it was initialized this way 

MUIPicker: new Date("2014-08-18T21:11:54"),

That's where the 11 minutes came from, the ones that I marked in red. 

It seems that the Mui Date Picker try to take that time to ISO format, and when it does so, for example in my time zone it added 3 hours (I'm in -3 time zone), so it ended up being 2014-08-19T00:11:54

**Comment by bluebill1049** [comment]
holy shit! wow, great find...!

**Comment by bluebill1049** [comment]
update the CSB 👍 thanks a lot for the investigation @cargallo

**Comment by cargallo** [comment]
Glad to help! At first glance I knew RHF was going to be a great library. I updated the sandbox but it's forked in here:

https://codesandbox.io/s/react-hook-form-v6-controller-forked-2mt0z 

I don't know if you mean that. Regards,

**Comment by bluebill1049** [comment]
<img width="1246" alt="Screen Shot 2020-08-21 at 9 46 11 am" src="https://user-images.githubusercontent.com/10513364/90836599-27768d80-e393-11ea-80bc-a668f68bfff5.png">
Thanks @cargallo ❤️ , yes I have updated the example in the doc 👍

**Comment by mohitkhurana1812** [comment]
Hi @bluebill1049 ,
I am facing issue with keyboardDateTimepicker component while using with RHF v7. I am trying to insert a property in Datetime object in OnChange method of keyboardDateTimepicker. But while submitting form that property is not present in dateTime object inside handleSubmit function. However same is visible if we do getValues().
Can you please help if this has to do anything with react hook form?
