### ISSUE TITLE
Disabled input values appear in handleSubmit data.

### ISSUE THREAD

**Issue by adriantrunzo** [react-hook-form/react-hook-form#2655]
**Describe the bug**
Values for disabled inputs still appear in `handleSubmit` data.

**To Reproduce**

1. Create a form with a disabled input.
2. Submit the form and inspect the data passed to `handleSubmit`.
3. See the value for the disabled input.

**Codesandbox link (Required)**
https://codesandbox.io/s/sweet-morning-dzc1f

**Expected behavior**
Disabled input values do not appear in `handleSubmit` data.

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version latest

**Additional context**
https://github.com/react-hook-form/react-hook-form/discussions/2654

**Comment by bluebill1049** [comment]
This will be fixed in the next minor version release: https://codesandbox.io/s/naughty-sound-yugie?file=/src/App.js

**Comment by sergiohgz** [comment]
@bluebill1049 What is the purpose to remove a value from a registered field without unregister it? In fact, to be closer with native forms, a disabled input is always handled when submitting it (and developer have to control it in their submit function). What do you think about?

Thanks and awesome work 😉

**Comment by bluebill1049** [comment]
hey @sergiohgz take a look at this tweet: https://twitter.com/bluebill1049/status/1300231640392716288

There is a CSB in there as well, disabled input should be excluded from the final submit.

statckoverflow: https://stackoverflow.com/questions/1355728/values-of-disabled-inputs-will-not-be-submitted

**Comment by sergiohgz** [comment]
Thanks for the clarification @bluebill1049 ❤️

**Comment by ivnmood** [comment]
I have the same issue, it has not been corrected

**Comment by mihaisavezi** [comment]
> We don’t support disabled for controller, only native input. Controller host it’s own value from internal state. There is a feature request u can consider to up vote in the project board.

I'm sure there is a reasonable explanation for this. But from a library user perspective it is not. 

I don't expect `Controller` to make inputs behave fundamentally different than their native counterparts. 

Do you have any workarouand to prevent disabled inputs to be sent when being submitted ?

**Comment by karitakarmet** [comment]
@bluebill1049 Is this issue been fixed? You mentioned [here](https://github.com/react-hook-form/react-hook-form/issues/1080) that the latest release should include that if I understand correctly, but I'm still getting disabled values in submit. So not sure if I'm doing something wrong or it's not fixed.. 🙈

**Comment by bluebill1049** [comment]
> @bluebill1049 Is this issue been fixed? You mentioned [here](https://github.com/react-hook-form/react-hook-form/issues/1080) that the latest release should include that if I understand correctly, but I'm still getting disabled values in submit. So not sure if I'm doing something wrong or it's not fixed.. 🙈

can you share a codesandbox and which version are you using?

**Comment by karitakarmet** [comment]
> > @bluebill1049 Is this issue been fixed? You mentioned [here](https://github.com/react-hook-form/react-hook-form/issues/1080) that the latest release should include that if I understand correctly, but I'm still getting disabled values in submit. So not sure if I'm doing something wrong or it's not fixed.. 🙈
> 
> can you share a codesandbox and which version are you using?

CodeSandbox example here: https://codesandbox.io/s/clever-buck-99j60?file=/src/App.js
I am using the newest version 7.14.1.

**Comment by bluebill1049** [comment]
![Uploading Screen Shot 2021-08-31 at 9.03.17 pm.png…]()

**Comment by miniplus** [comment]
@bluebill1049 https://codesandbox.io/s/practical-goldwasser-h7h1n?file=/src/App.js
Seems to be returning true / false for me as well with 17.5.1.

![image](https://user-images.githubusercontent.com/1800310/132520635-dd0ac782-e9e7-4ad3-92dd-1a7c876fb2e2.png)

**Comment by filidorwiese** [comment]
Just to add to the confusion a bit, I was also expecting validation not to occur when a field is disabled. So for example if a field has `required: true` and has no value but is disabled, submission is not blocked by it.

However with the latest beta 7.15.2-beta.0 this does not seem to be the case:

https://codesandbox.io/s/rhf-disabled-inputs-fs4sv?file=/src/App.js

Am I wrong to expect this?

**Comment by bluebill1049** [comment]
@filidorwiese it should skip the validation.

**Comment by filidorwiese** [comment]
Thanks, I see what I did wrong there. Keep up the good work

**Comment by bluebill1049** [comment]
> Thanks, I see what I did wrong there. Keep up the good work

Thank you! no worries buddy.

**Comment by filidorwiese** [comment]
Quick follow-up question;

It seems that when using `control` from `useForm` to register a field - that the `rules.disabled` property is explicitly omitted in the type: https://github.com/react-hook-form/react-hook-form/blob/8ca71b286d4e9064df877a484a6a633c7cd33116/src/types/controller.ts#L36-L48

For example, this code:

```
export default function TextInput({ control, name, rules = {} }) {
  const { field } = useController({
    name,
    control,
    rules,
  });
  return (<input {...field} id={name} type='text' />);
}

const { control } = useForm({ defaultValues: { fieldA: '' }});
<TextInput control={control} name='fieldA' rules={{ required: true, disabled: true }} />
```
leads to this type error:

```
TS2322: Type '{ required: boolean; disabled: boolean; }' is not assignable to type 'Omit<Partial<{ required: string | ValidationRule<boolean>; min: ValidationRule<string | number>; max: ValidationRule<string | number>; ... 10 more ...; deps: string[]; }>, "disabled" | ... 2 more ... | "setValueAs">'.   Object literal may only specify known properties, and 'disabled' does not exist in type 'Omit<Partial<{ required: string | ValidationRule<boolean>; min: ValidationRule<string | number>; max: ValidationRule<string | number>; ... 10 more ...; deps: string[]; }>, "disabled" | ... 2 more ... | "setValueAs">'. 

controller.d.ts(19, 5): The expected type comes from property 'rules' which is declared here on type 'IntrinsicAttributes & UseControllerProps<any, string | `${number}`> & { label: string; type?: string | undefined; onChange?: ((v: string) => void) | undefined; onFocus?: (() => void) | undefined; }'
```

If I shouldn't put the `disabled` prop directly on the uncontrolled input, as you've shown me, how should I then set it when using `useController` instead of `register`? The same goes for `readOnly`, it's not available either.

Bug or PEBKAC?

**Comment by bluebill1049** [comment]
those props are made for `register` only, for controlled input please manage input state include disabled at your controlled input level. Controlled input should give you full access to your input value and disabled state.

**Comment by filidorwiese** [comment]
If anyone is looking for the solution:

**Comment by bluebill1049** [comment]
Thank you very much for sharing solutions @filidorwiese

**Comment by filidorwiese** [comment]
Final question, is there a performance penalty to using `useController` (as in my codesandbox example) vs using `register`? Do both methods result in uncontrolled inputs elements?

**Comment by bluebill1049** [comment]
> Final question, is there a performance penalty to using `useController` (as in my codesandbox example) vs using `register`? Do both methods result in uncontrolled inputs elements?

`useController` is really a sugar syntax for `register` but made for the controlled component. The difference is one is 

- register: uncontrolled
- controller/useController controlled

The similarity:

- both isolate re-render

**Comment by Goofsy** [comment]
Is it any way to disable input to prevent validate from Yup.js and prevent to send to handleSubmit using <Controller/>? Controller's rules do not accept "disabled".

**Comment by bluebill1049** [comment]
@Goofsy would you like to do some investigation into all variety of external controlled components? the reason it's been omitted was having concerns that it may not work for all components.

**Comment by Goofsy** [comment]
Ok, i will in a free time. So what is a recommanded way to disable input using <Controller/>?

**Comment by bluebill1049** [comment]
it dependency if your external controlled component does support `disabled` prop.

**Comment by Goofsy** [comment]
@bluebill1049  I'm using `<Controller />` which i render `<TextField />` from MUI.

**Comment by PraveenPeri** [comment]
> it dependency if your external controlled component does support `disabled` prop.

Given that we know if the underlying component supports 'disabled' prop, how can we add the prop to the <Controller /> in typescript? Any suggestions there?

**Comment by alesvojta** [comment]
Hi, came across this issue too, currently solving like this:

```ts
import {
  FieldPath,
  FieldValues,
  RegisterOptions,
  useController as _useController,
  UseControllerProps,
  UseControllerReturn
} from 'react-hook-form'

type CustomUseControllerProps<
  TFieldValues extends FieldValues = FieldValues,
  TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>
> = UseControllerProps<TFieldValues, TName> & {
  rules?: Omit<RegisterOptions<TFieldValues, TName>, 'valueAsNumber' | 'valueAsDate' | 'setValueAs'>
}

/**
 * Customized RHF useController hook.
 * @see https://github.com/react-hook-form/react-hook-form/issues/2655
 */
export function useController<
  TFieldValues extends FieldValues = FieldValues,
  TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>
>(props: CustomUseControllerProps<TFieldValues, TName>): UseControllerReturn<TFieldValues, TName> {
  return _useController(props)
}
```

**Comment by snake-345** [comment]
@bluebill1049 
So, as I understand if you want to not send disabled fields on submit you have to pass `{ rules:  { disabled: true } }` as property of `<Controller>` or `useControl()`. 

We can clearly see this is the way in liked shared solutions, right? But disabled is omitted from `rules` for `<Controller>`/`useControl`. 

Shouldn't you allow `disabled` then? Instead of jumping through the hoops(with `any`/`ts-ignore` or redeclaring types without omitted `disabled`) when you use typescript.
