### ISSUE TITLE
Documentation for TS ErrorMessage should be fixed.

### ISSUE THREAD

**Issue by misterflop** [react-hook-form/react-hook-form#2658]
**Describe the bug**

Docmuentation error in ErrorMessage usage.

**To Reproduce**

TS version of https://react-hook-form.com/api#ErrorMessage

2. Copy paste this example in the example code sandbox and you get that:

      <ErrorMessage errors={errors} name="singleErrorInput">
        {({ message }) => <p>{message}</p>}
      </ErrorMessage>

3. You get a type error on ErrorMessage:

https://codesandbox.io/s/react-hook-form-v6-ts-errormessage-error-in-ts-documentation-78yb3?file=/src/index.tsx

**Comment by bluebill1049** [comment]
updated.
