### ISSUE TITLE
Errors doesn't clear on change while using `onBlur` mode

### ISSUE THREAD

**Issue by sjsakib** [react-hook-form/react-hook-form#266]
**Describe the bug**
I'm not sure if this is a bug. But while using `onBlur` mode, errors don't clear when a field is changed like they do while using `onSubmit` mode. 

**To Reproduce**
[Here](https://codesandbox.io/s/peaceful-framework-rphl3?fontsize=14) is a recreation.

**Expected behavior**
I expect the errors to be cleared when the corresponding field changes.

**Comment by bluebill1049** [comment]
when you using `onBlur` mode, errors get re-evaluated `onBlur` as well at this stage. we may look into introducing `reValidateMode` later on.

**Comment by bluebill1049** [comment]
current work around will be use `setValue(name, value, true)` true `onChange` will trigger validation

**Comment by Tymek** [comment]
> we may look into introducing `reValidateMode` later on.

PR welcome?

**Comment by bluebill1049** [comment]
@Tymek PR definitely welcome. can you share some of the insight into how you going to implement it?

Some of my thoughts, at the moment `onSubmit` revalidate `onChange` and `onBlur` revalidate `onBlur`.

I was thinking to have `reValidateMode` to overwrite default behavior, so you can change `onSubmit` reValidate to `onBlur`, and `onBlur` revalidate to `onChange`

example:
```
useForm({
  mode: 'onSubmit',
  reValidateMode: 'onChange' | 'onBlur`
})
```

**Comment by bluebill1049** [comment]
hmmm... thinking over this issue at the shower, I think it's not a good idea with `reValidateMode`. because if you set to `onChange` and some field you would like to `onBlur` then it can't be overwritten. I think it's easier to leverage `onChange` and `onBlur`, and I can provide an example of how to trigger validation `onChange` for `blur` mode.

eg:
```
const { regsiter, errors, triggerValidation } = useForm({ mode: 'onBlur' });

<input name="test" ref={register({ required: true })} onChange={() => {
  if (e.target.type === 'change' && errors[e.target.name]} {
     triggerValidation({ name: e.target.name });
  }
}} />
```

you can easily turn `onChange` function into a reusable function.

**Comment by Tymek** [comment]
Is it possible to do this with `mode`? If `mode = "onChange"` can one of the inputs validate only `onSubmit`? For uncontrolled input `onChange={event => event.preventDefault()}` is too late.

**Comment by bluebill1049** [comment]
valid point @Tymek for that case, you probably have to do validation on submit level for that particular field.

```
const { register, handleSubmit } = useForm({ mode: 'onChange' });

const onSubmit = (data) => {
  if (data.test === 'xxx') setError('test', 'required');
}

<form onSubmit={handleSubmit(onSubmit)}>
  <input name="test" ref={register} />
</form>
```

**Comment by Tymek** [comment]
Adding validation events is OK, but changing/overriding validation event might be a bad pattern. In my work as codebase grows I'd probably end up with many events that are created and cancelled in unpredictable way. Also, `mode`s are not mutually exclusive.

Is something like this use case possible? Validation/revalidation events created in `useForm` cannot be prevented, but are optional.

``` js
const FormComponent = () => {
  const { register, validate, handleSubmit } = useForm({
    validate: ['onSubmit'], // breaking change, refactor of `mode`
    revalidate: ['onSubmit', 'onBlur'], // as in defaults
  })

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input type="text" name="name" ref={register} onChange={validate} />
      <input type="text" name="test" ref={register} onBlur={(event) => {
        console.log('blur. cancel maybe? any errors?');
        validate(event);
      }} />
    </form>
  )
}

```

I need some time to dive into code and make more educated guess.

**Comment by bluebill1049** [comment]
@barrymay @Tymek thanks guys, what about we make `revalidate` to `onChange` (any mode)?

**Comment by barrymay** [comment]
Yeah I think that would work

**Comment by bluebill1049** [comment]
let's go with that 🙏

**Comment by barrymay** [comment]
to be clear that would still **avoid** validating prior to the first submit if it's onSubmit?

**Comment by bluebill1049** [comment]
correct @barrymay, only for **reValidate** :)

**Comment by bluebill1049** [comment]
@Tymek FYI https://github.com/react-hook-form/react-hook-form/pull/273

**Comment by bluebill1049** [comment]
This will be released soon for a minor update

**Comment by nandorojo** [comment]
Hey @bluebill1049, thanks to you and everyone else for this awesome library.

I mentioned this on #283, but I figured it applied more here. 

How can I 1) **show** an error `onBlur`, and 2) **clear** an error `onChange`?

I tried this:

`useForm({ mode: 'onBlur', reValidateMode: 'onChange' })`

This is great for showing an error on blur, but it also only clears the error on blur, not on change. Is there something wrong with that implementation?

Code sample here: https://codesandbox.io/s/react-hook-form-get-started-forked-vkk9j?file=/src/index.js:0-748

**Comment by bluebill1049** [comment]
> Hey @bluebill1049, thanks to you and everyone else for this awesome library.
> 
> I mentioned this on #283, but I figured it applied more here.
> 
> How can I 1) **show** an error `onBlur`, and 2) **clear** an error `onChange`?
> 
> I tried this:
> 
> `useForm({ mode: 'onBlur', reValidateMode: 'onChange' })`
> 
> This is great for showing an error on blur, but it also only clears the error on blur, not on change. Is there something wrong with that implementation?
> 
> Code sample here: https://codesandbox.io/s/react-hook-form-get-started-forked-vkk9j?file=/src/index.js:0-748

you want to use mode: `onTouched`, reVliadateMode is for after submit

**Comment by lgriveras** [comment]
Hey @bluebill1049,
 
If we use onTouched, after the first clear of error, the input will start validating onChange as well. Isn't there any way to explicitly validate when onBlur and only clear (without validating) with onChange?

**Comment by bluebill1049** [comment]
> Hey @bluebill1049,
> 
> If we use onTouched, after the first clear of error, the input will start validating onChange as well. Isn't there any way to explicitly validate when onBlur and only clear (without validating) with onChange?
> 
> This is easily reproduced with a required field using onTouched. once you lose focus it will show the error, then when you input something it will get cleared, but if the user, without losing focus on that input again, removes the text, the required error will show up again

If that's not your desired behavior, I will suggest set to `onChagne` and show errors accordingly with `formState`: `touched` `dirtyFields`
