### ISSUE TITLE
Nested array value is overwritten.

### ISSUE THREAD

**Issue by SergeyWebDeveloper** [react-hook-form/react-hook-form#2662]
**Describe the bug**
Faced such a problem that my value is not being written to the application state, i.e. it is overwritten.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-v6-ts-setvalue-forked-95r9e?file=/src/index.tsx

**Expected behavior**
Getting value
```
{
	documents: [{
		firstName: 'value',
		lastName: 'value2',
		age: '11'
	}]
}
```
Thank!

**Comment by bluebill1049** [comment]
please send the questions to Discussion next time: https://codesandbox.io/s/react-hook-form-v6-ts-setvalue-forked-dxcdh

**Comment by SergeyWebDeveloper** [comment]
sorry for the stupid questions and thanks a lot for the help!

**Comment by bluebill1049** [comment]
no worries at all. happy to assist either way.
