### ISSUE TITLE
form field value as a plain object?

### ISSUE THREAD

**Issue by rpmonteiro** [react-hook-form/react-hook-form#267]
At the moment, if you want to keep a plain object as a value in the form, you have to serialize/deserialize it all the time:
```
*get*
JSON.parse(getValues().someKey))

*set*
setValue('someKey', JSON.stringify(object))
```

Are there any plans to support just having a plain object as some field values?

An example use-case would be a custom auto-complete component where the user selects some value from a dropdown, but we need to persist the entire object as the value for that field.

Thank you for any help you might provide! 👍

(congratulations on the library. It's a fantastic and useful piece of code :) )

**Comment by bluebill1049** [comment]
Thanks :) you can't do `setValue('test', { data: 'test' })` ?

**Comment by rpmonteiro** [comment]
No, it doesn't seem like it. I haven't investigated further, but it seems react-hook-form does a toString() on the value, because I get it back as "[object object]"

**Comment by bluebill1049** [comment]
oh ok, I will take a look at it. see if it will be an easy fix.

**Comment by bluebill1049** [comment]
what about his `setValue('test', { value : {test: 'test'}} `?

**Comment by bluebill1049** [comment]
it works for my example https://codesandbox.io/s/exciting-bush-q1qfo

you want to check it out?

**Comment by bluebill1049** [comment]
how did you go @rpmonteiro ?

**Comment by bluebill1049** [comment]
going to close this issue, feel free to reopen if you have more questions or issue is not resolved.

**Comment by rpmonteiro** [comment]
Sorry, I couldn't come to the PC for the past few days. Everything is working fine, thank you!
It was a silly oversight on my code that was causing that weird behaviour.

Thank you very much for your help! 👍

**Comment by bluebill1049** [comment]
no worries :)

**Comment by michalpalenkar** [comment]
I'm facing same problem, but codesandbox example is no longer works. Can you please provide some basic workaround how to solve it again? Thanks

**Comment by kyds3k** [comment]
I also am running into this - any update, @rpmonteiro @bluebill1049 ?

**Comment by ergunpp** [comment]
Hi, Can. you please update codesandbox example, it no longer works.

**Comment by bluebill1049** [comment]
here is an updated CSB: https://codesandbox.io/s/sparkling-haze-fl4wh?file=/src/App.js

**Comment by ergunpp** [comment]
Thank you.
How would you do this only the input value changes for a field?
I have an order form where multiple products and their quantities are entered in a field array. I need to run the useffect as in your sample only when the selected product changes. 
Thank you in advance,
