### ISSUE TITLE
Add dynamic fields based on number

### ISSUE THREAD

**Issue by charlesjavelona** [react-hook-form/react-hook-form#2687]
**Is your feature request related to a problem? Please describe.**
There's no clear way to dynamically render *N* number of fields based on user input. It's always append based on button clicks.

**Describe the solution you'd like**
When a user enters a number in a textfield the input fields dynamically displays. Example, if a user enters he/she needs 5 input fields for phone number, 5 input fields should appear. If the user then decides they only need 2. The input fields are reduced to 2.  

**Describe alternatives you've considered**
- Grab the fields values and manually enter the number of inputs the user needs. Trigger a render.
- Use useState instead.
- For loop append based on the number of user input. --> This one didn't work.

**Additional context**
<img width="666" alt="Screen Shot 2020-08-23 at 6 28 10 PM" src="https://user-images.githubusercontent.com/7959179/90990301-76c4e580-e56e-11ea-844b-451d570538a1.png">

**Comment by bluebill1049** [comment]
pretty sure that you after this: https://react-hook-form.com/api#useFieldArray

**Comment by charlesjavelona** [comment]
I'm currently using useFieldArray. Unless I'm doing something wrong. Append doesn't trigger multiple displays based on a number given. A manual push of a button is needed to trigger a render and it can only do it one at a time.

**Comment by bluebill1049** [comment]
have you tried `append([{}, {}])`, you can do a map with how many items inside.

**Comment by charlesjavelona** [comment]
I did. This works! Thank you for your help.
