### ISSUE TITLE
Sets `number` to `string` even though manually converting string to number in onChange handler

### ISSUE THREAD

**Issue by FrimJo** [react-hook-form/react-hook-form#2688]
**Describe the bug**
When registering an `input` with type `number` and hijacking the `onChange` handler with updating the `event.target.value` with `+event.target.value` (effectively converting the value string into a number)  i still get type `string` when submitting.

I've gotten sought result by using the `Controller` component and hijacking `onChange` handler (see Codesandbox link below).

**Codesandbox link (Required)**
[Codesandbox](https://codesandbox.io/s/zealous-tdd-078j9?file=/src/App.js) Template

**To Reproduce**

1. Enter number in firs input field
2. Save and see the result in the console, where `notWorking` property is of type `string`.
3. Enter number in second input field
4. Save and see the result in the console, where `working` property is of type `number`.

**Expected behavior**
I can understand that the default behaviour should be to submit the same value which the default event contains, which defaults to `string` even though type is set to `number`. But shouldn't `react-hook-form` return a `number` when I actively converts the `string` into a `number`?

**Desktop (please complete the following information):**
OS: macOS 10.15.6
Browser Chrome
Version 84.0.4147.89

**Comment by bluebill1049** [comment]
```
<input
          type="number"
          ref={register}
          name="notWorking"
          onChange={(e) => ({
            ...e,
            target: { ...e.target, value: +e.target.value }
          })}
        />
```

This code above doesn't work with native input, it works with Contorller, because `onChange` gets returned to `Controller`.

**Comment by FrimJo** [comment]
@bluebill1049 Ah, ofc! Thnx

**Comment by bluebill1049** [comment]
no worries :) happy to help. 👍
