### ISSUE TITLE
mode cannot be switched dynamically 

### ISSUE THREAD

**Issue by sahanatroam** [react-hook-form/react-hook-form#2689]
**Describe the bug**
Similar to this https://github.com/react-hook-form/react-hook-form/issues/2565
When the form `mode` changes dynamically it's not being picked up.

Codesandbox link (Required)
https://codesandbox.io/s/react-hook-form-validationschema-forked-4nuwd?file=/src/index.js

Expected behavior
If you open the Codesandbox above,

Enter a wrong URL in to website
Error is shown - this is good.
Now click on the toggle button.
Now the error should only be shown when the user focus out of the input
But the mode is not changed

**Comment by bluebill1049** [comment]
we don't support `mode` switching at this stage (as we cache the mode). if you need to change the validation behavior please use `trigger`.

**Comment by sahanatroam** [comment]
@bluebill1049 is there a reason why you wouldn't support this ?

**Comment by sahanatroam** [comment]
Would be great to have the freedom like how we did with the resolver. So that the DX improves a lot by having the ability to customise anyway a developer prefers.
