### ISSUE TITLE
Hidden inputs doesn't effect isDirty form state 

### ISSUE THREAD

**Issue by itamardavidyan** [react-hook-form/react-hook-form#2692]
**Describe the bug**
When hidden input changed the form state doesn't effect.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-hidden-input-bug-5dhke?file=/src/index.js

**Expected behavior**
When hidden input (as any other input) default value changed - the `isDirty` state will change to `true`. 

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04
- Browser: chrome

**Comment by bluebill1049** [comment]
you are mixing controlled with uncontrolled: https://codesandbox.io/s/react-hook-form-hidden-input-bug-forked-m1kls?file=/src/index.js
