### ISSUE TITLE
The example "Controller (MUI, React-Select and etc)" has a bug if upgraded to latest version 

### ISSUE THREAD

**Issue by terchris** [react-hook-form/react-hook-form#2695]
**Describe the bug**
In the list of examples there is a example "Controller (MUI, React-Select and etc)" that can be tested on https://codesandbox.io/s/react-hook-form-controller-079xx

This demo uses react-hook-form version 5.5.1. When you set the version to 6.5.1 there is a bug in the MUI Checkbox. 
In defaultValues the field Checkbox: true is ignored.

**To Reproduce**
1. In  defaultValues change  Checkbox: false to Checkbox: true
2. reload the page and see that the MUI Checkbox is now checked.
3. in package.json change     "react-hook-form": "5.5.1", to     "react-hook-form": "6.5.1",
4. reload page and you can see that the MUI Checkbox is now unckecked.

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.
The example https://codesandbox.io/s/react-hook-form-controller-079xx

**Expected behavior**
Changing version should not result in changing behavior.  

**Desktop (please complete the following information):**
- Browser Chrome and firefox

**Comment by bluebill1049** [comment]
please use the v6 example: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r `render`

**Comment by terchris** [comment]
Thank you :)

**Comment by mdaffan** [comment]
<Controller
                  name="contractId"
                  control={control}
                  defaultValue={undefined}
                  render={props => (
                    <Select
                      options={options ?? []}
                      isClearable
                      isDisabled={inputFile}
                      label="Select Contract"
                      {...props}
                    />
                  )}
                />

This is throwing warnings in console likeontractId is missing in the 'defaultValue' prop of either its Controller (https://react-hook-form.com/api#Controller) or useForm (https://react-hook-form.com/api#useForm)

**Comment by mdaffan** [comment]
Also, AS discord channel is not reachable. I just have one more issue to discuss, Since upgrading to 6.8.2 handleSubmit from useForm is giving undefined like if there was an input field with name="check" and defaultValue for it is true. While submitting it is not even giving that key for handleSubmit

**Comment by bluebill1049** [comment]
> Also, AS discord channel is not reachable. I just have one more issue to discuss, Since upgrading to 6.8.2 handleSubmit from useForm is giving undefined like if there was an input field with name="check" and defaultValue for it is true. While submitting without touching/editing that input field it is not even giving that key for handleSubmit
> 
> Update: 6.0.0 is working but 6.8.2 just gives undefined for those untouched fields while submitting

few issues sported, defaultValue shouldn't be undefined and use render props. Sorry i have updated the link on discord.
