### ISSUE TITLE
Watch throws a property is read-only exception when watching an object with nested properties

### ISSUE THREAD

**Issue by KarelVerschraegen** [react-hook-form/react-hook-form#2706]
**Describe the bug**
`watch` throws a `$property is read-only` exception when watching an object that has nested properties. This object is loaded from an graphql endpoint and passed into a `react-select` form-field

After upgrading from `6.4.1` to `6.5.0`, the code no longer works.

**To Reproduce**

1. Go to https://codesandbox.io/s/exciting-leftpad-4zlw4?file=/package.json
2. Click on the first item in the dropdown
3. See error

If you downgrade the version to 6.4.1 in the codesandbox, the example works as expected.

**Codesandbox link (Required)**

https://codesandbox.io/s/exciting-leftpad-4zlw4?file=/package.json

**Expected behavior**
Watch should not throw an error when watching an object that has nested fields.

**Screenshots**
![image](https://user-images.githubusercontent.com/11301291/91163946-a5f26880-e6ce-11ea-80ed-cb7b562e7fb5.png)

**Desktop (please complete the following information):**

- OS: Arch Linux
- Browser: Firefox
- Version : 80.0

**Additional context**

**Comment by bluebill1049** [comment]
Thanks a lot for the reporting! just got it patched: https://codesandbox.io/s/xenodochial-saha-j028q?file=/src/App.js

**Comment by bluebill1049** [comment]
patched in 6.5.3
