### ISSUE TITLE
Insert item in usefieldArray inside a loop

### ISSUE THREAD

**Issue by CarolinaStephanie** [react-hook-form/react-hook-form#2710]
**Describe the bug**
When insert an item in a fieldArray inside a loop, just the first one is added, the others are ignored. One way to solve this issue is putting a timeout for each insert, but depends of the size will be not performing. 

**To Reproduce**

1. Click on Insert
2. See error (Just the last one is added) 
3. If you comment the line  > insert(position + 1, itemNewOptions); and uncomment the setTimeOut code will work

Code link: [https://snack.expo.io/@carolstephanie1/laughing-pastry](https://snack.expo.io/@carolstephanie1/laughing-pastry)

The code is inside "components" path

- React-Native 0.61
- React-Hook-Form 6.0.8

**Comment by bluebill1049** [comment]
<img width="861" alt="Screen Shot 2020-08-26 at 9 03 08 am" src="https://user-images.githubusercontent.com/10513364/91236324-f7583180-e77a-11ea-8cf4-bd796fb2aaee.png">

we don't support multiple actions at the moment. we can consider adding `insert([])`

**Comment by bluebill1049** [comment]
I am going to close this as a bug because it's not intended usage, but please feel free to send a feature request i will tag it under the project.
