### ISSUE TITLE
defaultValues from Redux

### ISSUE THREAD

**Issue by opeah** [react-hook-form/react-hook-form#272]
Hi,

Again thanks for the great library 👍 

I have an issue/question with defaultValues : I would like to fill my fields with async fetch.

Steps :

1. Async request
2. Store data into redux's store
3. Get props 'profile' from store
4. Input is empty => it's ok
4. Use profile.email into component
5. Set defaultValues in useForm hooks => does not work
6. Input is still empty

I try with defaultValues or watch but both does not work.

<img width="755" alt="Screenshot 2019-08-28 at 17 33 58" src="https://user-images.githubusercontent.com/31569566/63870476-4fb6f080-c9ba-11e9-9e7b-614d8c772df9.png">
<img width="440" alt="Screenshot 2019-08-28 at 17 34 15" src="https://user-images.githubusercontent.com/31569566/63870478-4fb6f080-c9ba-11e9-8747-f8d3b834f7d8.png">

The only way that works is to set the value..

Do you have a better solution ? 

Thanks,

**Comment by Tymek** [comment]
[guessing]
When you don't have direct control over `input.value`, `defaultValues` only work for initial render.
Try setting value when prop changes. Something like:
``` js
useEfect(() => {
  if (profile.email) {
    setValue('email', profile.email)
  }
}, [profile.email])
```

Pasting code as text can speed up debugging :)

**Comment by opeah** [comment]
Thanks @Tymek it works!

**Comment by bluebill1049** [comment]
Thanks @Tymek :)

**Comment by bluebill1049** [comment]
@opeah by the way. you can use `reset` api to populate the entire form as well.
```
useEffect(() => {
  reset({
    email: 'test',
    other: 'data
  })
})
```

**Comment by ajay-dev-j** [comment]
@bluebill1049  Do you think the reset value get set in the first watch() call?

**Comment by bluebill1049** [comment]
it should get from defaultValues @ajay-dev-j
