### ISSUE TITLE
A plain input located before a controller steals focus on error

### ISSUE THREAD

**Issue by vcarel** [react-hook-form/react-hook-form#2723]
**Describe the bug**
A plain input located before a controller steals focus on error.

**To Reproduce**
I have a form with 3 inputs: first and last ones use a `Controller`, and the one in the middle is a regular input using `register`. All fields are empty and required.

1. When I click on submit
2. Then the focus is on the middle field whereas it should be on the first one.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-input-after-controller-focus-issue-lfd9m

**Expected behavior**
The focus should be on the first field having an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/1541093/91290380-d3edb080-e793-11ea-9b5a-f3865a7efdc7.png)

**Desktop**
- OS: Ubuntu 20.04.1 LTS
- Browser: Chrome
- Version: 85.0.4183.83

**Comment by bluebill1049** [comment]
This is due to the registration order. native input ref will always be registered first, Controller will be always registered after mount. you can avoid this problem by using all `Controller`.

**Comment by vcarel** [comment]
I guessed I had to do that 😅

However it's an unexpected and undocumented behavior, is it?

**Comment by bluebill1049** [comment]
It's expected behavior, I will add a comment under focus props with Controller.

**Comment by bluebill1049** [comment]
<img width="562" alt="Screen Shot 2020-08-26 at 8 32 39 pm" src="https://user-images.githubusercontent.com/10513364/91293392-4a61d100-e7db-11ea-94ed-ef1ae03ce6d6.png">

This will be under the `onFocus` props, feel feel to improve the doc if you feel that's not enough.

**Comment by vcarel** [comment]
Is there a work-around so to not rewrite the whole forms with Controller?

**Comment by bluebill1049** [comment]
> Is there a work-around so to not rewrite the whole forms with Controller?

It's going to be tricky because we can't register the item until `Controller` is mounted, while with native input we can register right away once ref is there.

**Comment by vcarel** [comment]
I can't prevent myself to be disappointed, since it will give me quite a lot of extrawork.

But thanks for your help! I appreciate your fast answers and this excellent library ☺

**Comment by bluebill1049** [comment]
> I can't prevent myself to be disappointed, since it will give me quite a lot of extrawork.
> 
> But thanks for your help! I appreciate your fast answers and this excellent library ☺

Sorry about this... I should have documented this under the doc, this could have been avoid...
