### ISSUE TITLE
Field does not dirty when when selecting a nested object.

### ISSUE THREAD

**Issue by KarelVerschraegen** [react-hook-form/react-hook-form#2725]
**Describe the bug**
Possibly related to #2706.

When selecting a value with nested properties from a `react-select` dropdown, the property `formState.isDirty` does not change.

As far as I can tell, the combination of `watch` and nested properties, breaks the formState. When removing the `watch` on the selected item, the `formState.isDirty` changes correctly.

When you downgrade to `6.4.1`, the code works as expected when you select an item from the dropdown. (i.e. the button is not disabled when an item is selected).

**To Reproduce**

1. Go to https://codesandbox.io/s/spring-tree-wrk13?fontsize=14&hidenavigation=1&theme=dark
2. Click on the first item in the dropdown
3. See that the button remains disabled even though the form is dirty

**Codesandbox link (Required)**
https://codesandbox.io/s/spring-tree-wrk13?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
The `formState.isDirty` property should change when clicking on an item in the dropdown field. (in combination with `watch`)

**Desktop (please complete the following information):**

- OS: OSX Catalina 10.15.6
- Browser Firefox
- Version 80

**Additional context**

**Comment by bluebill1049** [comment]
you are missing defaultValue there is warning at the console.


https://codesandbox.io/s/happy-snow-sz4qu?file=/src/App.js

**Comment by KarelVerschraegen** [comment]
I have updated the example with something that more closely resembles the codebase

https://codesandbox.io/s/blissful-shape-oc21u.

I have added a default value to the `useForm` hook which sets the default character as and object with empty properties.

## How to reproduce
1. Go to https://codesandbox.io/s/blissful-shape-oc21u
2. See that a `defaultValues` has been added to `useForm`
3. See that the button is disabled when the form is not dirty
4. Click on a character in the dropdown
5. See that a `<div>Warning</div>` is rendered based on some watch() condition.
6. See that the button is still disabled even though the field has been 'dirtied'

Thank you for your help already! :pray:

**Comment by bluebill1049** [comment]
oh thanks! this is a bug!
