### ISSUE TITLE
prepending to first-level field array when using nested arrays renders wrong second level fields

### ISSUE THREAD

**Issue by sincraianul** [react-hook-form/react-hook-form#2729]
**Describe the bug**
When using nested field arrays, prepending (or appending) a child to the first level array causes second level fields to render wrong values.

**To Reproduce**

1. Go to https://codesandbox.io/s/rhf-nested-arrays-bug-u6gei?file=/src/index.js
2. Click on 'prepend foo'
3. Notice the newly prepended object has the wrong `bars`.

**Expected behavior**
The prepended `foo` shouldn't have any `bars` rendered.

**Additional context**
I suspect this issue is caused by using two levels of nesting with field arrays (i.e. `foos[0].bars[0].name`.

**Comment by bluebill1049** [comment]
Each useFieldArray hosts its own field array so does either method, perhaps I need to reinforce that in the doc.

```
prepend({
      name: "",
      bars: [] // this line is not going to work, try to use useEffect at the child field array.
});
```

**Comment by sincraianul** [comment]
I'm afraid I don't quite understand how I would use `useEffect` to reset the child field array. If I try to set up a `useEffect` inside the `Child` to call ```setValue(`foos[${index}].bars`, [])``` it doesn't really work.

**Comment by sincraianul** [comment]
Seems that it's exactly the same issue as in #2223.

**Comment by bluebill1049** [comment]
Thanks, just reproduce this issue with my codesandbox: https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-x7btr

**Comment by bluebill1049** [comment]
> Seems that it's exactly the same issue as in #2223.

Don't think it's the same issue.

**Comment by sincraianul** [comment]
> > Seems that it's exactly the same issue as in #2223.
> 
> Don't think it's the same issue.

You're right, not the same one. What I pointed out (and it's the same issue in your codesandbox) is related to`prepend`. `append` works fine. 😄

**Comment by bluebill1049** [comment]
yea, thanks for the issue report @sincraianul looking into this problem.
