### ISSUE TITLE
`clearErrors` clears all nested errors unexpectedly

### ISSUE THREAD

**Issue by ilovett** [react-hook-form/react-hook-form#2730]
**Describe the bug**

Recursive form with nested arrays, due to mount effect order, `clearErrors` runs on the root item last, and that appears to clear all nested orders as well.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-query-builder-clearerrors-on-nested-items-z7d3o?file=/src/QueryBuilder.tsx
2. Click on console
3. Click on "Remove Condition"
4. Note: Error on root item
5. Click on "Add Logical Group"
6. Note: There should be an error on the most nested item, but it's cleared because root item `clearErrors` fires last (see console)

**Codesandbox link (Required)**

 https://codesandbox.io/s/react-hook-form-query-builder-clearerrors-on-nested-items-z7d3o?file=/src/QueryBuilder.tsx

**Expected behavior**

Only the ErrorOptions at the specified path are cleared -- `{ type, types, message }` and if its an empty object, then it can be removed...

Suggest the above logic or adding opts as second param to `clearErrors(arg1, { exact: true })` for backward compatibility

**Screenshots**

![2020-08-26 13 00 36](https://user-images.githubusercontent.com/1776100/91350907-3ba7f980-e79c-11ea-87d3-27c3e3f840fa.gif)

**Comment by bluebill1049** [comment]
This is not a bug, right? More of a feature request?

<img width="682" alt="Screen Shot 2020-08-27 at 9 03 23 am" src="https://user-images.githubusercontent.com/10513364/91365329-2ab2c300-e844-11ea-805b-c1f51a0798d6.png">

**Comment by bluebill1049** [comment]
By the way, really cool stuff~

**Comment by bluebill1049** [comment]
maybe I need a bit more context on this issue as well, especially below:

> Note: There should be an error on the most nested item, but it's cleared because root item clearErrors fires last (see console)

**Comment by ilovett** [comment]
@bluebill1049  Thanks!  Here's the flow:

1. Click `Remove Condition`
2. Root Group has no children, error is on `query.items` for `minLength` via `useEffect`
3. Click `Add Group`
4. The new Group has no child, so an error is set on `query.items.0.items` via `useEffect`
5. Root Group now has at least on child, so `minLength` is removed via `useEffect` (due to mounting order) -- but this clears all nested errors within that path, including child `query.items.0.items`

My thought is that it could be considered a bug because it was unexpected for me.  But it could also be a feature request if that was intended.

I would think clear error could check to see if any props other than `{ type, types, message}` exist at the error path `query.items` -- if yes, then remove the error props `{ type, types, message }` -- otherwise the whole object can be removed / deleted from the error object

**Comment by bluebill1049** [comment]
thanks, @ilovett :) at the moment `clearError` is very basic, it just gets the name of the field and clears the error. you may want to bake the logic inside your app at the moment and submit a separate feature request for adding functionality with `clearError`.

**Comment by bluebill1049** [comment]
sorry, @ilovett this is actually a bug, I just check the code and it's the wrong code...

**Comment by bluebill1049** [comment]
```
<input name="test.data" />
<input name="test.remove" />
```

if you run `clearErrors('test')` ❌, shouldn't clear any error, because no input is found.

`clearErrors('test.data')` ✅
`clearErrors('test.remove')` ✅
