### ISSUE TITLE
tab movement between fields when rendering using .map()

### ISSUE THREAD

**Issue by willxy** [react-hook-form/react-hook-form#2731]
**Describe the bug**
I'm wanting to display the set of fields using an array and .map() and a component, eg:

```
	const FormFieldEntry = ({ fieldname }) => (
		<fieldset name={fieldname}>
			<label>
				{fieldname}
				<input type="text" name={fieldname} ref={register} />
				<p> {errors && errors[fieldname]?.message} </p>
			</label>
		</fieldset>
	);

	const fieldnames = Object.keys(FormSchema.fields);

	return (
		<form onSubmit={handleSubmit(doSubmit)}>
			{fieldnames.map((x) => (
				<FormFieldEntry key={x} fieldname={x} />
			))}
		</form>
	);
}
```
When I do that, hitting tab doesn't move the cursor to the next field as expected.

**To Reproduce**
At https://codesandbox.io/s/rhf-yup-map-xmgzo:
 - click on the first field ("address")
 - hit tab to move through the fields
 - for the first set of fields, each press of tab triggers the validation error and moves the cursor to the next field
 - for the second set of fields, pressing tab will trigger the validation error, but not move to the next field; pressing tab after that will then start again at the first field in the set
 - so ie rather than moving 1,2,3,4,5, it moves 1,1,2,1,2,3,1,2,3,4,1,2,3,4,5

**Codesandbox link (Required)**
https://codesandbox.io/s/rhf-yup-map-xmgzo

**Expected behavior**
I'm expecting each tab press to move to the next field

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Chrome
- Version: 84.0.4147.135

**Additional context**
 - I realize there might be something else/additional I need to do when rendering the fields via .map, and I couldn't find what that might be.  I did see `useFieldArray()`, but it didn't look like that fit -- I don't need to **alter** the list of fields during the display of the form.
 - I also tried other versions of RHF; 6.5.3-6.5.1 had identical behavior; with 6.5.0 and below, react seemed to hang/freeze/become unrseponsive as soon as I put the cursor in any of the second set of fields.
 - It looks like it's also related to the fact that there's field validation going on; if I disable yup (resolver: yupResolver()) then it does move between fields as expected (but then of course there's no field validation).
 - (I realize there's no submit button in the form; I didn't end up copying that over to the sandbox since the behavior is prior to submitting.)

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/rhf-yup-map-forked-jnt63?file=/src/profile-map.js

> //  Pay attention here your component is getting unmounted each re-render, move it outside of this component

please looking for my note in the codesandbox.

**Comment by willxy** [comment]
Ahh, thanks, I'll take a look at that.

**Comment by willxy** [comment]
Got it, yep!  Thanks for seeing my error @bluebill1049.

**Comment by bluebill1049** [comment]
no worries @willxy 👍
