### ISSUE TITLE
Stale useWatch value

### ISSUE THREAD

**Issue by cYee992** [react-hook-form/react-hook-form#2738]
**Describe the bug**
useWatch returning stale value(default value) instead of latest value (Latest version of react-hook-form)

**To Reproduce**

1. Go to the sandbox 
2. Edit the name or age 
3. click Turn on watch display
4. See value is not updated

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-wizard-form-forked-f4wmt?file=/src/index.js

**Expected behavior**
The value should have updated, but this on works if watch display is on all the time.

**Comment by bluebill1049** [comment]
Thanks for the issue report, look like this is expected behavior rather than a bug. as for now, we are getting `defaultValue` of `useWatch` from `defaultValue` at `useWatch` or `defaultValues` from `useForm`.

https://github.com/react-hook-form/react-hook-form/blob/master/src/useWatch.ts#L62

**Comment by cYee992** [comment]
Alright then, I will go with a feature request. Thanks!

**Comment by bluebill1049** [comment]
Thanks @cYee992 👍

**Comment by cYee992** [comment]
@bluebill1049 I have given it some thought about it. I am not so sure am I using useWatch right. Let's say the user key in a form with quatity and price, they can click on the button to show a 'total price' modal, before submit. without the latest value it will be the initial default values. or is that should be the usecase just watch() since it will unmount eventually?

**Comment by bluebill1049** [comment]
@cYee992 if you keep `useWatch` running, without toggle it on and off. I think it should work for you. Do you have a simple codesandbox to mimic your app behavior? I can take a look at it tmr (it's late here).
