### ISSUE TITLE
Form with file upload not working

### ISSUE THREAD

**Issue by harish-bisht** [react-hook-form/react-hook-form#274]
Form with file upload not working. I tried this work around, 
useEffect({
  register({ name: 'file' }, { required: true }) // still have validation for required
}, [register])

const handleChange = (e) => {
  setValue('file', e.target.files[0]); // you get all the files object here
}

<input name="file" onChange={handleChange} />

Can anyone provide working example?

**Comment by bluebill1049** [comment]
what exactly you try to achieve here?

**Comment by harish-bisht** [comment]
I wanted to submit a form with text fields data and file data using single submit handler

**Comment by bluebill1049** [comment]
what information you wan to sore with the file?

**Comment by harish-bisht** [comment]
Information like name, description etc.

**Comment by bluebill1049** [comment]
oh ok you have a codesandbox i can have a play?

**Comment by harish-bisht** [comment]
Sorry! I do have account there. When I submit data image parameter is displayed as image:{} in console. It is not posting File Object.

**Comment by bluebill1049** [comment]
share that codesandbox, i can have a look for you :)

**Comment by ParmentierChristophe** [comment]
I had the same problem, I solved it by adding :

`    e.persist();
`

in your function 

```
const handleChange = (e) => {
setValue('file', e.target.files[0]); // you get all the files object here
}
```

**Comment by harish-bisht** [comment]
While debugging I find out that axios.post() is removing file object from data and making it image:{}

**Comment by bluebill1049** [comment]
I guess it's not an issue for React Hook Form, I am closing this issue, but feel free to ask questions here I will see what I can help with

**Comment by h0jeZvgoxFepBQ2C** [comment]
@harish-bisht Did you found a solution on how to make it work with normal form data combined and react-hook-form?

**Comment by Shaka-60hp** [comment]
What about this? any news about handling files to be sent ?

**Comment by bluebill1049** [comment]
@Shaka-60hp follow this video: https://www.youtube.com/watch?v=XlAs-Lid-TA

**Comment by h0jeZvgoxFepBQ2C** [comment]
Has anyone an example on how to send form values together with a file via axios?
I'm not really able to make it work...

**Comment by akshaykumar771** [comment]
> Has anyone an example on how to send form values together with a file via axios?
> I'm not really able to make it work... How can I convert the react-hook-form data parameter to a FormData object?

Hello, did you find an example on how to send form values with file?. Any help is appreciated. Struggling to fix this.

**Comment by rootsher** [comment]
I created a quick snippet for handling `input type="file"` via `react-hook-form` and `zod` in 3 different ways: `via register`, `via control` and `via useController` - feel free to use https://stackblitz.com/edit/input-file-react-hook-form?file=src/Form.js :)

**Comment by rajivchaulagain** [comment]
I think this is a common problem for any react developer using react-hooks-form. I am a beginners and along with me my friends are facing same problems for uploading single as well as multiple files. I think the above dicussion are for advanced and intermediate programmers.As a Beginner I want a simple solution if anyone can provide I could be very Thankful to you all.

**Comment by h0jeZvgoxFepBQ2C** [comment]
We ended up using this: https://github.com/therealparmesh/object-to-formdata - take care, it will convert your booleans from true to "1" etc, which broke many things in our system unintentionally.. But you get nice file objects back at least :)
