### ISSUE TITLE
Dynamic checkboxes losing selected state when adding/removing new items

### ISSUE THREAD

**Issue by raulfelix** [react-hook-form/react-hook-form#2743]
Describe the bug
Dynamic checkboxes has a strange behaviour with selected values when adding/removing new items to list of checkboxes.

To Reproduce

1. Go to https://codesandbox.io/s/weathered-cdn-rmp0u?file=/src/index.js
1. You will see 3 subjects each checked.
1. Click **Add 1 subject**.
1. Your list will now have 4 subjects with the new one unchecked.
1. Click **Remove 1 subject** now you are back to 3 subjects but only 2 items are checked

All items should still be checked??

Desktop (please complete the following information):

OS: mac OS
Browsers: All (but found in chrome)

**Comment by bluebill1049** [comment]
hmmm, @raulfelix this is going to be a tricky one, I think this one would probably need to be built into controlled group input and controlled with Controller.

**Comment by bluebill1049** [comment]
actually, let me do a quick one with `useFieldArray`. I think it may solve this problem.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/interesting-chatterjee-pv11u?file=/src/checkboxes.js:1185-1190

**Comment by raulfelix** [comment]
> for dynamic input, it's better to use `useFieldArray`.
> 
> https://codesandbox.io/s/interesting-chatterjee-pv11u?file=/src/checkboxes.js:1185-1190

Doesn't really meet the use case for widespread use in the code base. Are you saying for me to have a checkbox group I need to render them with fieldArray?

**Comment by raulfelix** [comment]
I have one more issue perhaps you can give me some guidance on please?

**To Reproduce**
Go to https://codesandbox.io/s/broken-pond-h7549?file=/src/checkboxes.js
1. Tick math
1. Tick spanish
1. Untick math
1. Tick year 1
1. Untick year 1
1. You will see an exception `Cannot read property 'ref' of undefined`

A solution for this would be very appreciated.

![Bug](https://user-images.githubusercontent.com/996002/91560052-81231d00-e97c-11ea-8556-b1f716b14c72.gif)

**Comment by bluebill1049** [comment]
> > for dynamic input, it's better to use `useFieldArray`.
> > https://codesandbox.io/s/interesting-chatterjee-pv11u?file=/src/checkboxes.js:1185-1190
> 
> Doesn't really meet the use case for widespread use in the code base. Are you saying for me to have a checkbox group I need to render them with fieldArray?

anything dynamic: append, remove, insert and etc, i would use useFieldArray hook.

**Comment by bluebill1049** [comment]
> I have one more issue perhaps you can give me some guidance on please?
> 
> **To Reproduce**
> Go to https://codesandbox.io/s/broken-pond-h7549?file=/src/checkboxes.js
> 
> 1. Tick math
> 2. Tick spanish
> 3. Untick math
> 4. Tick year 1
> 5. Untick year 1
> 6. You will see an exception `Cannot read property 'ref' of undefined`
> 
> A solution for this would be very appreciated.
> 
> ![Bug](https://user-images.githubusercontent.com/996002/91560052-81231d00-e97c-11ea-8556-b1f716b14c72.gif)

i will take a look at it over the weekend.

**Comment by vensauro** [comment]
Your first problem, is because you are using the index for the key prop, and this is bad
try using the value
```jsx
return (
    <div>
      {options.map((option, i) => (
        <label key={option.value} htmlFor={option.value}>
          <input
            id={option.value}
            type="checkbox"
            name="subjects"
            value={option.value}
            ref={register({ required: "make a selection" })}
          />
          <span>{option.label}</span>
        </label>
      ))}
    </div>
  );```

**Comment by raulfelix** [comment]
Ok looks like this can work by making 2 changes:

1. Use unique keys everywhere, if not might effect how hook form monitors mutations?
1. In a checkbox group the name must be consistent and cannot be `name[0]`, `name[1]` which is a mistake but instead must be `name[string]`. It appears to still work if you do not have any validation on the fields but if you do use validation then it will lead to an error.

That is all reasonable. Can close @bluebill1049 . Thanks

**Comment by bluebill1049** [comment]
Thanks, @raulfelix I think worth considering building a controlled component and embed your logic inside, and then apply `Controller` (if your use case gets complicated). 

With dynamic inputs, it can get a bit tricky with uncontrolled input due to how React treat uncontrolled inputs during `.map`, that's why I suggested `useFieldArray` if you ever encounter array field manipulation. (Thanks @vensauro for helping as well ❤️ )
