### ISSUE TITLE
Fields are getting unregistered after form reset

### ISSUE THREAD

**Issue by Elia-d** [react-hook-form/react-hook-form#2749]
**Describe the bug**
When used with a framer-motion input field, these are getting unregistered after form reset!!

Example:
```
<motion.input type="text" name={name} id={name} ref={register} />
```

**Codesandbox link (Required)**
https://codesandbox.io/s/boring-sea-6qs8o?file=/src/App.js

**To Reproduce**

1. Go to Codesandbox link provided above
2. Fill the Form
3. Submit the Form (Form will reset after being submitted)
4. At this point, if you look in the console, ```control.fieldsRef.current``` will be an empty
5. Fill the form again
6. When you try to submit, the Fields will have a required error, even though they are valid!

**Expected behavior**
Field won't get unregistered after resetting

**Desktop (please complete the following information):**

- Os: macOs
- Browser: chrome
- Version 85

**Additional context**
I am not sure if this is a problem with framer-motion or react-hook-form, but I thought I'll ask first here since you're familiar with working with 3rd party UI components and probably have an idea of what could be causing that!

**Comment by Elia-d** [comment]
Also, setting ```shouldUnregister: false``` did not solve the problem!

**Comment by bluebill1049** [comment]
not familiar with `motion.input` and how ref is exposed in the commponent, please use Controller instead: https://codesandbox.io/s/condescending-payne-gsezs?file=/src/App.js

**Comment by Elia-d** [comment]
First I want to thank you for the quick response, really amazing!

This is what I ended up doing.

How should the ref be exposed for react-form-hook to work as expected? Maybe I can then help fix the issue of framer-motion's side.

I love how this library embraces uncontrolled components and native inputs, and would love it if I manage to find a solution!

Thanks again 🙂

**Comment by bluebill1049** [comment]
Thanks @Elia-d 🙏 take a look at the updated CSB: https://codesandbox.io/s/condescending-payne-gsezs?file=/src/App.js

**Comment by bluebill1049** [comment]
close this issue as it's not an issue with this lib.
