### ISSUE TITLE
[Bug] Hidden input is ignored, when another input with `register()` is present

### ISSUE THREAD

**Issue by ssuvorov** [react-hook-form/react-hook-form#2752]
### Hidden input is ignored, when another input with `register()` is present 🐞 

**To Reproduce**
1. Go to https://codesandbox.io/s/distracted-payne-1ooyh?file=/src/App.js
2. Click on **Submit**
3. **Expected**: In console check a _submit_ object: test[0].validation has to be present with value `false`. **Current**: validation field is missing.
4. Select any value in `<select>` dropdown
5. **Expected**: In console check a _watch_ object: test[0].validation has to be present with value `true`. **Current**: validation field is missing.

**Codesandbox link**
https://codesandbox.io/s/distracted-payne-1ooyh?file=/src/App.js

- Version: checked 6.5.3 and 6.6.0

**Additional context**
Removing from code
```
<input
     defaultValue={fields[index].required}
     ref={register()}
     name={`test[${index}].required`}
     type="text"
/>
```
helps to solve `onChange` issue. But a default value is still ignored and empty.

**Comment by bluebill1049** [comment]
sorry, i think i need more context: why the following input is there? it's not even registered.

`<input type="hidden" name={`test[${index}].validation`} />`

**Comment by ssuvorov** [comment]
Sure, I need to extend `test[index]` object with external data based on select value.
The way you suggested to do this is here: https://codesandbox.io/s/epic-violet-yvgr9?file=/src/App.js. On Change -> update hidden fields.

I have more issues with **useFieldArray**. Also when removing some items. Maybe we can make a zoom call, so I can share the screen and show them. You can reach me with Telegram: @examp1e.

**Comment by bluebill1049** [comment]
> The way you suggested to do this is here: https://codesandbox.io/s/epic-violet-yvgr9?file=/src/App.js. On Change -> update hidden fields.

Yes, but that hidden field needs to be registered.

> I have more issues with **useFieldArray**. Also when removing some items.

do you mean conditional render item?

**Comment by ssuvorov** [comment]
let me try to register, I guess it's another issue then. With defaultValues, or submitting without modifying them. Let me quickly check it.

> do you mean conditional render item?
no conditions, only using `remove(index)`

**Comment by bluebill1049** [comment]
> no conditions, only using `remove(index)`

please provide a codesandbox, i will take a look at it over the weekend.

**Comment by ssuvorov** [comment]
https://codesandbox.io/s/distracted-payne-1ooyh?file=/src/App.js
okay, registred. Default values are fixed with providing `defaultValue={field[index].validation}`. But, please try 

1. select "1" in `<select>`.
2. submit.

As you can see validation changes to `true` on change, but submit has `false`

**Comment by bluebill1049** [comment]
hmmm looks like input type hidden can't be edited: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/hidden use css display: none instead.

**Comment by ssuvorov** [comment]
Ah! 
<img src="https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fmedia3.giphy.com%2Fmedia%2FgHzfFKMrDZWxvIFTqc%2Fgiphy.gif%3Fcid%3D6104955e08c8d08d2076eaf6835767fcadb0977f1166934c%26rid%3Dgiphy.gif" />

**Comment by ssuvorov** [comment]
Let me quickly reproduce an issue with removing an index. Glad to you we might kill all these 3. Thanks.

**Comment by ssuvorov** [comment]
In this modification: https://codesandbox.io/s/distracted-payne-1ooyh?file=/src/App.js

0. Refresh the page so default values are applied.
1. remove an item with "-" button.
2. submit

A watch object is not empty and contains an object with **validation** field. But the error in a console is correct **message: "at least 1 item is required"**

Then
0. refresh the page
1. change `<select>`
2. remove an item
3. submit

Error is empty and I'm able to submit :(

**Comment by bluebill1049** [comment]
This is due to `defaultValues` will kick in when all fields get removed: 

here is a walkaround: 

https://codesandbox.io/s/mystifying-grass-zelzc?file=/src/App.js

**Comment by ssuvorov** [comment]
I guess defaultValues has to be applied only during initialization. And for **useFieldArray** when it's empty a default `[]` is expected. Wdyt?

**Comment by bluebill1049** [comment]
<img width="907" alt="Screen Shot 2020-08-29 at 8 29 22 pm" src="https://user-images.githubusercontent.com/10513364/91634773-54334080-ea36-11ea-875b-922fb0d80f9c.png">

This is what's on the doc, when using watch with useFieldArray, honestly, i would recommend to use useWatch instead.

**Comment by ssuvorov** [comment]
Checked this workaround. Doesn't work. It's possible to submit after onChange and remove. Should be an error "at least 1 item is required". Seems like `setValue` onChange leads to this.

**Comment by bluebill1049** [comment]
I can conclude there is no bug in this issue.

**Comment by bluebill1049** [comment]
for min length, i think it's easier to do the following: 

```
useEffect(() => {
  if (!fields.length) {
    setError('xxx')
  }
})
```

**Comment by ssuvorov** [comment]
this is a workaround. Schema works perfectly. But only in case when `setValue` is executed - it fails. Seems like a bug, no?

**Comment by bluebill1049** [comment]
> But only in case when `setValue` is executed

what do you mean? u need to give me some details. u mean you want to trigger validation during `setValue`?

**Comment by ssuvorov** [comment]
In a comment above I described steps how to reproduce an issue when schema doesn't work https://github.com/react-hook-form/react-hook-form/issues/2752#issuecomment-682653563.

In a schema for `useFieldArray` I set `.required()` - meaning 1 item in the array is required. It works only until I modify a value inside of an object from `useFieldArray` manually with `setValue`. 

After that, if all items from the array are removed, schema says that this array is valid. Meaning something wrong is passed into it.

**Comment by ssuvorov** [comment]
The only difference I noticed during debugging, is that watching fields are not empty after manual modification with `setValue`.

**Comment by bluebill1049** [comment]
> In a comment above I described steps on how to reproduce an issue when schema doesn't work [#2752 (comment)](https://github.com/react-hook-form/react-hook-form/issues/2752#issuecomment-682653563).

did you see my example? resolved this problem?

**Comment by bluebill1049** [comment]
> The only difference I noticed during debugging, is that watching fields are not empty after manual modification with `setValue`.

it's definitely empty in above CSB:
<img width="706" alt="Screen Shot 2020-08-29 at 9 05 25 pm" src="https://user-images.githubusercontent.com/10513364/91635369-5fd53600-ea3b-11ea-9a69-3f5f213fef16.png">

**Comment by ssuvorov** [comment]
Let me upload a video. The problem is not with "watch", the problem is with a schema validation error.

**Comment by ssuvorov** [comment]
https://codesandbox.io/s/pensive-sun-indkr?file=/src/App.js
![111Screen Recording 2020-08-29 at 12 58 43](https://user-images.githubusercontent.com/3448821/91635445-e0267780-e9f8-11ea-8a53-78a83a9376c9.gif)

**Comment by ssuvorov** [comment]
I guess `remove(index)` doesn't remove items that were set with `setValue`. Sorry for disturbing you with this issue :)

**Comment by bluebill1049** [comment]
> I guess `remove(index)` doesn't remove items that were set with `setValue`. Sorry for disturbing you with this issue :)

Nah, that's fine. as long as we can resolve the problem here. The video certainly help, but it should remove item even with setValue which is registered.

**Comment by bluebill1049** [comment]
hmmm, looks like test again looks like it's otherwise... I will take a look at it again later.

**Comment by ssuvorov** [comment]
Okay. So, do u think it's a bug? Can I help somehow else?

**Comment by bluebill1049** [comment]
oh this is already fixed! haha, next patch will resolve this problem.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2757 we can close this issue now.

**Comment by bluebill1049** [comment]
here is a CSB with updated code from master: https://codesandbox.io/s/mystifying-grass-zelzc?file=/src/App.js

**Comment by bluebill1049** [comment]
please confirm if the above works. 👍

**Comment by ssuvorov** [comment]
Brilliant. Waiting for the next release! Thank you a lot!
