### ISSUE TITLE
onBlur event is not fired in Controller

### ISSUE THREAD

**Issue by arnnis** [react-hook-form/react-hook-form#2753]
**Describe the bug**
after updating from v0.5.7.2 onBlur event is not fired on Controller component

**To Reproduce**
1. Go to codesandbox link
2. Click on 'Input with controller'
3. change focus
4. event is not fired

**Codesandbox link (Required)**
https://codesandbox.io/s/billowing-firefly-5zc02?file=/src/App.js

**Expected behavior**
I expect the onBlur event to fire. manually passing onBlur with render porp does not work either

**Desktop (please complete the following information):**

- OS: Macos 10.15.6
- Browser Chrome 84
- Version 6.6.0

**Comment by bluebill1049** [comment]
Thanks for the issue report, v6 removed onChange and onBlur props, take a look at the changelog: https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md
