### ISSUE TITLE
Checkbox with default values that are 2-digit numbers cause strange behaviour

### ISSUE THREAD

**Issue by outerlook** [react-hook-form/react-hook-form#2754]
**Describe the bug**
I think the best way to understand this error is by viewing the sandbox I am providing.

**To Reproduce**

1 - Create a form with 4 checkboxes of values: "1", "2", "3", "12"
2 - Set form's default values as ["12"] or ["1", "12"] or things that select "12"
3 - See results: "1" and "2" also gets checked, as if number strings were iterated

[Sandbox link](https://codesandbox.io/s/react-hook-form-basic-forked-lyesm?file=/src/index.js)

**Comment by bluebill1049** [comment]
i think you forgot to save your CSB.

**Comment by outerlook** [comment]
Yes, I forgot... 😅 now I didn't

**Comment by outerlook** [comment]
It happens also with strings, not only numbers. I gave it a bad title, soon I will update it

**Comment by bluebill1049** [comment]
Thanks! that's a valid bug.
