### ISSUE TITLE
isValid is sometimes false despite no errors

### ISSUE THREAD

**Issue by krnlde** [react-hook-form/react-hook-form#2755]
**Describe the bug**
I sometimes get `isValid = false` despite having no visible errors and `errors` object being an empty object (`{}`)

**To Reproduce**
I do not yet have a reproducable sandbox, but I already found a code piece that might be the problem. Please see *additional context*

**Expected behavior**
isValid should always reflect what the `errors` object contains (e.g. `isValid = Object.keys(errors).length === 0`)

**Desktop (please complete the following information):**

- OS: Windows 10 202001
- Browser: Microsoft Edge
- Version: 86.0.621.0 (Official build) canary (64-bit)

**Additional context**
The problematic line could be this code piece here: https://github.com/react-hook-form/react-hook-form/blob/03216edb0b29bae631fb752e6ec612111d82798d/src/useForm.ts#L341 which triggers revalidation but without providing an `isValid` parameter as the 4th parameter. Hence this line https://github.com/react-hook-form/react-hook-form/blob/03216edb0b29bae631fb752e6ec612111d82798d/src/useForm.ts#L218 will resolve in `!!isValid` which essentially means `!!undefined === false`.

AFAIK the problem only appears on async filled inputs (inputs that get their value via an api request).

**Comment by bluebill1049** [comment]
Thanks @krnlde which version are you running?

**Comment by krnlde** [comment]
Latest, `6.6.0`. But it is the same with the previous.

**Comment by bluebill1049** [comment]
would be great if you can have a codesandbox for me, no stress if you are busy. i will take a look at it over the weekend.

**Comment by krnlde** [comment]
Alright! I'll try to do a reproducable codesandbox :)

**Comment by krnlde** [comment]
Here's a simple variant with only 2 radios where `isValid` is initially `false`, but when changed it gets `true`: https://codesandbox.io/s/rhf-isvalid-initially-false-bug-3ucht

And here's a variant where the fields are required. The `isValid` field will always be `false`: https://codesandbox.io/s/rhf-isvalid-always-false-bug-forked-uvb30

**Comment by bluebill1049** [comment]
looks like this is not a new issue, i switched to 6.4.1. it has the same behaviiour.

**Comment by bluebill1049** [comment]
also, both example doesn't have `mode: 'onChange'`

**Comment by krnlde** [comment]
Hey! Yes, I have that for a while now, but it got worse somewhere between 6.4 and 6.6.

**Comment by bluebill1049** [comment]
oh, I see, so 6.4 prior is working? I will check it out.

**Comment by krnlde** [comment]
Unfortunately I didn't recognize exactly when it started to happen... When I'm back on my PC I can "time travel" and investigate

**Comment by bluebill1049** [comment]
Don't worry about it @krnlde leave it to you, i will let you know.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/rhf-isvalid-initially-false-bug-forked-sjifc?file=/src/App.tsx
https://codesandbox.io/s/rhf-isvalid-always-false-bug-forked-fsk5l?file=/src/App.tsx

switched on mode: 'onChange' isValid is working for me. I think those two CSB is not reproducing the issue.

**Comment by bluebill1049** [comment]
I may need your help with a reproducible CSB. 🙏

**Comment by krnlde** [comment]
Will do! Thank you :)

Regarding not having the mode set to onChange: Shouldn't it be `true` initially anyways though?

**Comment by bluebill1049** [comment]
> Will do! Thank you :)
> 
> Regarding not having the mode set to onChange: Shouldn't it be `true` initially anyways though?

both codesandboxs are returning true after i attached `mode: 'onChange'` :)

**Comment by krnlde** [comment]
Here I got the exact problem I have. It's a bit tricky to force the `isValid: false` state, but when you just switch between the first and the second radio, it should appear after 1 second (the current timeout delay, to emulate network request). https://codesandbox.io/s/rhf-isvalid-always-false-bug-forked-xgt5u?file=/src/App.tsx

**Comment by bluebill1049** [comment]
Thanks very much, @krnlde 👍 I will take a look at it tmr night.

**Comment by bluebill1049** [comment]
This issue is related to `disabled`, I think it makes sense to read the value during validation but not at submit.

**Comment by krnlde** [comment]
Wow, I didn't actually know that :) I'll try and see what happens if I remove the disabled state in the current code just to be sure that this is the problem. Thanks for this insight!

**Comment by krnlde** [comment]
I adapted the current codesandbox again. Now I removed the disabled state, which initially worked. But then I exchanged the radios with select and the select with radios. Now do the following steps to get an `isValid: false` despite no errors:

1. Go to the site: https://codesandbox.io/s/rhf-isvalid-always-false-bug-forked-xgt5u
2. Wait for the async radios to appear (1sec)
3. select "second" from the `<select>` input
4. Wait for the radios to update (1sec)
5. activate "4" from the radios below (which is a new option not available in `first`)
6. -> `isValid: false` no matter what radios you activate from now on


Also if I then go back to "first" in the `<select>` field there will be an error printed:

![image](https://user-images.githubusercontent.com/1087002/91837778-c54c4100-ec4c-11ea-92c6-750800b4309e.png)

I'm pretty sure it has something to do with this code block:
```ts
          {asyncOptions.map((value) => (
            <label key={value}>
              <input
                type="radio"
                name="async_1"
                value={value}
                ref={register({ required: true })}
              />{" "}
              {value}
            </label>
          ))}
```
but then again, it worked some versions before, and if I use a select instead of radios it works too (when not disabling it, thanks for that again 👍  ), so it's probably an issue with `<input type="radio" />`

Cheers mate and thanks for your help

**Comment by bluebill1049** [comment]
no worries mate @krnlde can you do a quick test with the latest master? (the csb below)

https://codesandbox.io/s/rhf-isvalid-always-false-bug-forked-q1xsf?file=/src/App.tsx

**Comment by krnlde** [comment]
You mean `v6.7.0`? I cannot select an unreleased github state - or can I?

**Comment by bluebill1049** [comment]
no my CSB link above, it got the latest code.

**Comment by krnlde** [comment]
Same problem as described above (which was tested with `6.6.0` and `6.7.0`)

**Comment by bluebill1049** [comment]
kk, i will take a closer look at it.

**Comment by bluebill1049** [comment]
This one is trigger and hard... 
https://codesandbox.io/s/rhf-isvalid-always-false-bug-forked-q1xsf?file=/src/src/useForm.ts

what happens because your radio input shares the same name, but it gets unmounted and remounted with the same name. so it was working before because we had a bug not remove field with validation correctly (very rare case). I think this PR should fix this. also we doing deepEqual with validation fields with valid fields now, that's why it's picking up this issue.

**Comment by krnlde** [comment]
Uff, wow :D Sorry for creating such hard problems. Regardless of how complicated things are you manage to solve them in just 30 mins of time - everytime. You're awesome and I can't thank you enough.
The CSB works, I'd love to give it a spin in my realworld app :)

Thank you :-*

**Comment by bluebill1049** [comment]
> Uff, wow :D Sorry for creating such hard problems. Regardless of how complicated things are though, you manage to solve them in just 30 mins of time - everytime. You're awesome and I can't thank you enough.
> The CSB works, I'd love to give it a spin in my realworld app :)
> 
> Thank you :-*

You are welcome! no worries, it's my responsibility to maintain this lib, it was a bug in the first place. I will release the patch in the next couple days 👍

**Comment by tar-aldev** [comment]
For me doing this solved the problem
```
useForm<SignInFormValues>({
    resolver: yupResolver(validationSchema),
    reValidateMode: 'onChange', // this in pair with mode seems to give the expected result
    mode: 'onChange',
  })
```
Although I am not sure if it gives some porblems when used this way, as I am quite new to react hook form

**Comment by VladimirMikulic** [comment]
@tar-aldev which version are you using? The solution doesn't work for me. (v7.9.0)

**Comment by Kizmar** [comment]
Running into this issue after updating packages on an existing app that was working as expected. Tried suggestions above with no success.

Original versions before updating (works):
_RHF v7.4.1
@hookform/resolvers v2.4.0
yup v0.32.9_

Currently on versions (issue):
_RHF v7.11.0
@hookform/resolvers v2.6.1
yup v0.32.9_

The form starts in a locked/disabled state (not sure if relevant). User clicks button to unlock the form. There is a Material-UI Switch component for a boolean field. It does not matter if it start as `true` or `false`. The first change of the Switch always sets `isValid = false` with an empty `errors` property. 

Any following toggles of the Switch give the expected `isValid = true` result. The entire form always has default values. I've been inspecting the form values while debugging and those look fine.

The Yup validator only requires that the fields are defined - which they are in all cases as far as I can tell.

**Comment by noonii** [comment]
I've faced the same issue regarding `react-hook-form` built with `material-ui (legacy)` or `@mui (latest)` , here's the CSB

https://codesandbox.io/s/react-hook-form-issue-2755-r5j7k

@bluebill1049

**Comment by bluebill1049** [comment]
> formState is wrapped with a Proxy to improve render performance and skip extra logic if the specific state is not subscribed to. Therefore make sure you invoke or read it before a render in order to enable the state update.

https://react-hook-form.com/api/useform/formstate

```
const { isValid } = methods.formState;

console.log(isValid);
```

**Comment by noonii** [comment]
Thank you for the reference, I've updated to the suggestion and it works.

On the other hand, the following contradicts the suggestion partially? See below.

> therefore make sure you invoke or **read it** before a render


```
const disableSubmitButton = (formState: FormState<FormValues>) => { ❌ 
  return (
    !formState.isDirty ||
    formState.isValidating ||
    formState.isSubmitting ||
    !formState.isValid
  );
};


const disableSubmitButton = ({isDirty, isValidating, isSubmitting, isValid}: FormState<FormValues>) => { ✔️
  return !isDirty || isValidating || isSubmitting || !isValid;
};

const Form = () => {
   const methods = useFormContext<FormValues>();
   const { formState } = methods;
   const disabled = disableSubmitButton(formState); 
   ...
   return (
      .... 
      <Button type="submit" disabled={disabled}>Submit</Button>
   );
}
```

CSB: https://codesandbox.io/s/react-hook-form-issue-2755-r5j7k

**Comment by mcmxcdev** [comment]
I am running into this issue too. It works with `mode: 'all', reValidateMode: 'onChange'`, but we don't want to trigger validations before submitting the form first.

Destructuring `formState` as described above also doesn't seem to work.

**Comment by kelleyperry** [comment]
for me it is not that the functionality does not work, it is the tests that are failing when using "isValid" in the check.

**Comment by Nziranziza** [comment]
Having similar issue now was there any solution

**Comment by nir099** [comment]
hack until this is fixed. 

we can assert form validity by not having errors.

`isEmpty(methods.formState.errors)`

**Comment by GProst** [comment]
Having this issue on `v7.34.0`, destructuring and `onChange` mode deosn't help

**Comment by bluebill1049** [comment]
> Having this issue on `v7.34.0`, destructuring and `onChange` mode deosn't help

could you share a simple codesandox?

**Comment by GProst** [comment]
@bluebill1049 as you can see initially `isValid` is false but `errors` object is empty: https://codesandbox.io/s/recursing-mopsa-qvyt6g?file=/src/App.js

**Comment by bluebill1049** [comment]
That's expected @GProst errors state only start to update once user start to interact with the input/form, while isValid report the entire form valid state.

**Comment by GProst** [comment]
@bluebill1049 ahh, sorry for false alarm then

**Comment by bluebill1049** [comment]
No worriees, @GProst if you want to force errors state to be update/render, you can try to call `trigger()`, that would validate the whole form and flush down those `errors` state

**Comment by GProst** [comment]
@bluebill1049 actually, I think I was able to reproduce the actual issue I was having in my project: https://codesandbox.io/s/recursing-mopsa-qvyt6g?file=/src/App.js

As soon as I add a second field `isValid` will always be false

**Comment by ryu-liam** [comment]
Putting `trigger()` inside of useEffect works for me!

**Comment by Moshyfawn** [comment]
Yes, this is the recommended way to validate `defaultValues`

**Comment by franksimon90** [comment]
@bluebill1049 Sorry to spam a closed ticket, but since it has some activity. RFC: How's the new `useFieldArray` rules going to play with this errors behavior and refs, currently using `formState` errors with `{ mode: 'onChange'}` is far from usable, isValid is going to be true even with errors being shown on the UI, for more than a few use cases, using a trigger isn't logical, basically means to re-execute the rules (that in my case are async ones).

**Comment by Moshyfawn** [comment]
> call trigger() sort of works, but at the same time it checks all the other fields and resulted in error messages for all the other fields that user hasn't enter anything yet. What to do? Any expectation when this issue can be fixed?

You can pass the field name / list of names to the `trigger` method instead. See [the `trigger` RHF docs section](https://react-hook-form.com/api/useform/trigger) to learn more

**Comment by dimitriBouteille** [comment]
Hi @soulbeing If you want re-validate or validate form without display errors, yon can do this :  

```js
const {trigger,clearErrors,} = useForm<FormData>({
  resolver: yupResolver(schema(t)),
});

...

trigger(..).then(() => clearErrors());
```

**Comment by briangwaltney** [comment]
Just another data point for analysis, I have this error when using autocomplete from my browser in an input field. When I type, no issues. When I just select the suggested option, no errors and `!isValid`.

**Comment by wansiedler** [comment]
> Just another data point for analysis, I have this error when using autocomplete from my browser in an input field. When I type, no issues. When I just select the suggested option, no errors and `!isValid`.

How did you fix it?
Got the same problem.

**Comment by briangwaltney** [comment]
I ended up refactoring my form so I didn't need to use the isValid api. Now it goes through the normal check procedure on submit. I know that's not very helpful, but it's what worked for me.

**Comment by wansiedler** [comment]
> I ended up refactoring my form so I didn't need to use the isValid api. Now it goes through the normal check procedure on submit. I know that's not very helpful, but it's what worked for me.

I now realised that I have a big Yup validation scheme and in my stepper From only few are being analysed. This is why the Form is !isValid.

**Comment by rHilkner** [comment]
Using workaround of loadsh isEmpty function: `isEmpty(form.formState.errors)`

**Comment by stefanpl** [comment]
@bluebill1049 being confused about this as well, I just watched your video on formState.

I've noticed that [here](https://youtu.be/4kzd572NbkM?t=106) in the video, an older version of the docs is showing, which is giving a crucial hint about `isValid`:

> This state is only applicable with `onChange` and `onBlur` mode.

Why has this been removed from [the docs](https://react-hook-form.com/api/useform/formstate)? My impression is, this is still the case, and documenting it might be super helpful, as shown by the activity in this issue.

If you agree, I'll add it back in.

**Comment by bluebill1049** [comment]
@stefanpl This has been improved: https://github.com/react-hook-form/react-hook-form/releases/tag/v7.39.0

**Comment by rHilkner** [comment]
Actually in my case, what solved is to check form.control._formState.errors instead of form.formState.errors. Looks like form.formState.errors took 1 more render to appear for me and the form.control._formState.errors had the errors populated in the same render. The thing is that my formState was really invalid, but the errors just were not showing up.

**Comment by bluebill1049** [comment]
> Actually in my case, what solved is to check form.control._formState.errors instead of form.formState.errors. Looks like form.formState.errors is taking 1 more render to appear for me and the form.control._formState.errors had the errors populated in the same render. The thing is that my formState was really invalid, but the errors just were not showing up.

I think you should wait for the next render to flush out the updated `formState` and reflect on the UI.

**Comment by rHilkner** [comment]
In the end using `form.control._formState.errors` didnt solve all my issues also...

Here's my issue:
I'm not sure how do I wait for the next render since I need to perform the validation programatically when a button is clicked. I have this function below, that should return if my formulary is currently valid or not. The current behaviour is that it needs to be clicked twice to work.
```
    const validateForm = async (): Promise<boolean> => {
    console.log(form.getValues())
    await form.trigger()
    if (form.formState.isValid) {
      return true
    }
    if (isEmpty(form.formState.errors)) {
      console.error("Error in the form")
    } else {
      console.error(form.formState.errors)
    }
    return false
  }
```
And is called by
```
  const onButtonClick = async () => {
    if (!await validateForm()) return
    setLoading(true)
    makeRequest(...).then(...).finally(setLoading(false))
  }
```
In the first click in the button it prints "Error in the form" and in the second time it performs the request successfully. Both times the object printed by `form.getValues()` is the same. Any ideas on the fix? I thought calling `.trigger()` would solve my problems, but now I've ran out of ideas.

**Comment by rHilkner** [comment]
So the fix for me was reading `form.formState.errors` before performing the `trigger()`, even though the errors are always empty. Reading the errors made the `trigger()` execute correctly and updated the `form.formValues` properties.

```
  const validateForm = async (): Promise<boolean> => {
    const _ = form.formState.errors // also works if you read form.formState.isValid
    await form.trigger()
    if (form.formState.isValid) {
      return true
    }
    if (isEmpty(form.formState.errors)) {
      console.error("Error in the form")
    } else {
      console.error(form.formState.errors)
    }
    return false
  }
```
