### ISSUE TITLE
unregister method is not working for fields registered with register method

### ISSUE THREAD

**Issue by vitorsemeano** [react-hook-form/react-hook-form#2757]
**Describe the bug**
When you have a component that build a set of filters, you can use the methods register and unregister to add and remove filters at will. When the user submits, you should get a object containing the fields that were registered and not unregistered. 

In the latest version of the lib (6.6.0 at the time of writing), the unregister function is ignored/not working.

**To Reproduce**

1. Go to the code sandbox here: https://codesandbox.io/s/wonderful-raman-4uydv
2. Click multiple times on the button add. For each add click, a console log will be outputed with the action made
3. Click submit to see the current form object. Check that all values are there
4. Click on remove one or more times
5. Click submit and you will se the object exactly as it is in the point 3. At least, the object at this point should not contain the fields called with the unregister method.

**Codesandbox link (Required)**
https://codesandbox.io/s/wonderful-raman-4uydv

**Expected behavior**
When you call the unregister method, you should not see the unregistered fields on form submit .

**Screenshots**
![image](https://user-images.githubusercontent.com/4042283/91586588-82892100-e94d-11ea-8152-46578f6f4eb8.png)

**Desktop (please complete the following information):**

- OS: windows 10
- Browser: chrome 
- Version 84

**Comment by bluebill1049** [comment]
Thank you! patching this.

**Comment by vitorsemeano** [comment]
Thanks for the quick fix!

**Comment by bluebill1049** [comment]
Thank you for the issue report.

**Comment by ialapont451** [comment]
Hi, it still doesn't work for version 7
I have version 7.32.2 installed

**Comment by ialapont451** [comment]
doesn't work on example page either https://codesandbox.io/s/react-hook-form-unregister-v6-forked-qs8o6

**Comment by ZiggerZZ** [comment]
Same problem for me. Version 7.34.0.
