### ISSUE TITLE
Trigger function causes too many re-renders

### ISSUE THREAD

**Issue by kanavrov** [react-hook-form/react-hook-form#2758]
**Describe the bug**
The `trigger` function causes a form re-render for every field it validates. e.g. Passing 5 field names to the function will result in 5 re-renders. Executing the function without arguments results in a re-render for every field in the form. `handleSubmit` on the other hand causes only 2 re-renders, no matter how many fields there are in the form. This is especially problematic for partial / manual validation of forms containing many fields.

**To Reproduce**
Use the provided sandbox. It contains 8 inputs, `render` counter, a `submit` button and a `trigger` button. The `trigger` button executes partial validation for the first 5 fields. Click the `trigger` button and monitor the `render` counter. 

**Codesandbox link**
- [trigger issue sandbox](https://codesandbox.io/s/react-hook-form-partial-validation-issue-w43r0)

**Expected behavior**
The `trigger` function should behave similar to `handleSubmit` function. A single call to `trigger` should cause 1 re-render regardless of the number of fields passed to it. I guess the 2 re-renders for `handleSubmit` are caused by `formState` first changing to `submitting`, so for `trigger` there should be only 1 re-render.

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome (85.0.4183.83), Opera (70.0.3728.133)

**Comment by jeven2016** [comment]
@bluebill1049
I also encounter this issue, what version can we upgrade to 6.15.5 or 7.0.0-rc.7? 
But I've tried these two versions in codesandbox and the issue still can be reproduced, anything I missed?  
Thanks.

**Comment by LukasRada** [comment]
@bluebill1049
I have upgraded to 6.15.7 and the trigger still re-renders.
Any progress on this?

**Comment by kanavrov** [comment]
Seems to work correctly with the latest version (7.6.7) - [code sandbox](https://codesandbox.io/s/react-hook-form-partial-validation-issue-forked-9l30l) . Trigger on 5 fields re-renders only 1 time.

**Comment by LukasRada** [comment]
Well, then we have to upgrade to v7. Thx.
