### ISSUE TITLE
Radio group buttons crash browser tab on validation and make the page hang

### ISSUE THREAD

**Issue by sankalpk** [react-hook-form/react-hook-form#2759]
**Describe the bug**
Radio group buttons crash browser tab on validation and make the page hang

**To Reproduce**

1. Create a radio group with dynamic ids
2. Console log the errors in the form
2. Submit the form so validations are triggered
3. See that the form validation errors are continuously getting logged in a seemingly infinite loop

**Codesandbox link (Required)**
Warning: may crash your tab when you submit the form in CSB
https://codesandbox.io/s/react-hook-form-radio-button-group-with-validation-error-tdkf2?file=/src/RadioGroup.js

**Expected behavior**
I expected the radio buttons to just work

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Firefox
- Version 80.0

**Additional context**
There is a workaround where you can pass a consistent id to the radio input so that they don't error.

Thanks for building the library! I've been enjoying using it so far. This may not be an issue worth fixing depending on how much effort it takes. However, it is unexpected behavior (and took me quite some time to figure out) so it may be worth documenting somewhere.

**Comment by bluebill1049** [comment]
Thanks @sankalpk can you try one thing first? don't use key with index. i will take a look at it today.

**Comment by sankalpk** [comment]
@bluebill1049 thanks for the suggestion. I've updated the CodeSanbox to use a generated random id. https://codesandbox.io/s/react-hook-form-radio-button-group-with-validation-error-tdkf2?file=/src/RadioGroup.js

**Comment by sankalpk** [comment]
@bluebill1049 It looks like it is actually the dynamic`key` value (not the dynamic ID) which causes the error.

**Comment by bluebill1049** [comment]
why are u using dynamic `key`?

**Comment by sankalpk** [comment]
The map function requires a `key` for each element and I couldn't think of a better way to generate the radio inputs. I couldn't use the `name` prop as that would not be unique on the page and I didn't want to use the label as that's not guaranteed to be unique. 

My workaround was to require passing in a `uniqueId` as a prop to the input. Though, that's not ideal because it makes the component's API slightly more complex for an implementation concern. Is there any other way you'd recommend?

**Comment by bluebill1049** [comment]
that's a bug with this lib then, you should use value as key.
