### ISSUE TITLE
omitResetState not working

### ISSUE THREAD

**Issue by dhmacs** [react-hook-form/react-hook-form#2769]
**Describe the bug**

Setting `dirtyFields` on omitResetState argument when using `reset` does not seem to prevent dirty fields being reset. Am I missing something? My goal is to reset values when I receive a refresh from API, but I don't want dirty fields to be reset.

**To Reproduce**

1. Open [this codesandbox](https://codesandbox.io/s/clever-hooks-01dt2?file=/App.js)
2. Edit "Note" or "Email"
3. Click on ''Reset data"
4. Even if note and/or email are dirty due to step 2, they are being reset

**Codesandbox link**

https://codesandbox.io/s/clever-hooks-01dt2?file=/App.js

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/great-napier-husgi?file=/App.js
<img width="1205" alt="Screen Shot 2020-08-31 at 9 23 46 am" src="https://user-images.githubusercontent.com/10513364/91671614-ade95700-eb6b-11ea-8193-8b6a4fd67d61.png">

**Comment by dhmacs** [comment]
Oh I actually see now what `dirtyFields: true` means. it does not mean the dirty fields will not be reset, it means that the dirty status of the field will be reset, but the field itself will. So to achieve what I'm trying to achieve (I want to reset fields to new value after I receive data from API, but don't want to reset fields that the user has already change to avoid bad UX) I should handle myself the merge between new data and dirty fields right?

**Comment by bluebill1049** [comment]
you are right. it means not reset the `dirtyFields` in the `formState`. With your UX requirement, i don't have much context, so what you referring to sounds about right to me.

**Comment by dhmacs** [comment]
To give you more context: 

I use [React Query](https://github.com/tannerlinsley/react-query) to manage API requests, and every time focus changes, React Query revalidates your queries. 
So the use case is: the user wants to update some data, and starts to update fields in the form, then it switches to another window to copy some text (or answer an email, or whatever). When he goes back to the web app, React Query revalidates queries to get updated data and by default if I use `reset` passing the new data, everything the user has updated so far is replaced by new data. The behavior I want instead is a merge between new data and the dirty fields data, so that fields which are not dirty are updated, and dirty fields will be left as is. At first I thought I could achieve this by using `OmitResetState` argument, but now it seems to me that react-hook-form does not support this behavior out of the box, so I would need to do the merge myself.

Thanks for the clarification 👍

**Comment by bluebill1049** [comment]
is `setValue` potentially what you after? otherwise, yes it's not something we support. if you send a feature request with details tho.

**Comment by dhmacs** [comment]
I'll try to implement this so I can formulate a better feature request

**Comment by bluebill1049** [comment]
hey, @dhmacs any chance you could follow up with a feature request before I close this issue?

**Comment by dhmacs** [comment]
Hey @bluebill1049, eventually I decided not to use this library. If you'd like I can still write a feature request. Anyway you can close the issue 👍

**Comment by bluebill1049** [comment]
That's all good 👍 @dhmacs thanks for giving a test.
