### ISSUE TITLE
reset method doesn't update the subscriber of useWatch if defaultValue is provided

### ISSUE THREAD

**Issue by ahmad-medhat** [react-hook-form/react-hook-form#2771]
**Describe the bug**
`reset` method doesn't update the watched field (by `useWatch`) if a defaultValue is provided in the useWatch.

**To Reproduce**
_(please use the codesandbox below)_
1. refresh the page
2. wait for 3s for the `reset` method to get called
3. the subscriber to test field is updated with the new value
4. if adding a default value to useWatch, the subscriber doesn't get updated with the new value after calling reset

**Codesandbox link**
https://codesandbox.io/s/funny-kalam-gf05v?file=/src/App.js

**Expected behavior**
I am not sure if this is a bug or an intended behavoir. However, I think in all cases calling `reset` method should update the subscribers of useWatch

**Desktop (please complete the following information):**

- OS: macOs
- Browser firefox
- Version 80.0

Thank you for your hard work!

**Comment by bluebill1049** [comment]
This is expected, inline useWatch will overwrite what's coming from useForm.

**Comment by ahmad-medhat** [comment]
Thank you for your quick response!

Yes inline defaultValue will overwrite what is coming from useForm. However, if an async call is made and `reset` is called with new values, I think the subcribers to useWatch should get updated with the new value. Please correct me if I am wrong

**Comment by bluebill1049** [comment]
> Yes inline defaultValue will overwrite what is coming from useForm. However, if an async call is made and `reset` is called with new values, I think the subcribers to useWatch should get updated with the new value. Please correct me if I am wrong

Yes, that's correct. I tried your codesandbox and it's working for me unless i am missing the steps.

<img width="1194" alt="Screen Shot 2020-08-31 at 4 53 18 pm" src="https://user-images.githubusercontent.com/10513364/91691140-7bab1a00-ebaa-11ea-90a8-56bf59dbf9db.png">

**Comment by ahmad-medhat** [comment]
If you add a defaultValue to useWatch and refresh, the value of subscriber is not getting updated

**Comment by bluebill1049** [comment]
That's what I meant above, `reset` API will reset the `defaultValues`, but with `useWatch` inline `defaultValue` will take over that value.

**Comment by ahmad-medhat** [comment]
It is clear now. Thank you for you time :)

**Comment by bluebill1049** [comment]
no worries @ahmad-medhat 👍
