### ISSUE TITLE
IE11 problem in v6.7.0

### ISSUE THREAD

**Issue by kwht-k** [react-hook-form/react-hook-form#2775]
Thank you for answering #2468 the other day.
I have found a problem in IE11 again, so I will report it.

**Describe the bug**
When I was using `React Hook Form v6.7.0` with IE11, I got some errors as shown in the screenshot.
Also I installed `@babel/runtime-corejs3` with reference to [FAQs](https://react-hook-form.com/faqs/#BrowserSupport).
I think it was caused by changing the rollup settings in [v6.5.1 -> v.6.5.2](https://github.com/react-hook-form/react-hook-form/compare/v6.5.1...v6.5.2), but I'm not sure.

**To Reproduce**
1. Build the [following code](https://github.com/kwht-k/rhf670-ie11-reproduction)(Production or Debug Build) and run it with IE11.
2. Enter some characters in the form and click "Submit"(If you can't reproduce it, please reload a few times).
3. Get some error messages and the form does not work fine.

Specifically, after pressing The "Submit" button, the next process is not executed.
I have found this problem both `Production Build` and `Debug Build`.

**Codesandbox link (Required)**
I share my repository because it's difficult for Codesandbox to reproduce with IE11.

https://github.com/kwht-k/rhf670-ie11-reproduction

**Expected behavior**
The error message disappear and my code works fine in IE11.

**Screenshots**
![ie11-reproduction-en](https://user-images.githubusercontent.com/54492352/91697114-8619e380-ebab-11ea-86b1-229e21d85925.png)

**Desktop (please complete the following information):**

OS: Windows10 Pro 64bit
Browser: Internet Explorer 11 (11.1016.18362.0)
Version of React Hook Form: 6.7.0
Version of @babel/runtime-corejs3: 7.11.2

**Comment by bluebill1049** [comment]
IE 11! @kotarella1110 sorry to tag you again, looks like this IE is never-ending...

**Comment by bluebill1049** [comment]
Are there any more users affected by this? I will tag this as help wanted. if this only happens on @kwht-k, I may consider to move(close) on with the annoying IE issue.

**Comment by yhor1e** [comment]
I have the same problem too.
I guess many cases works fine using `import 'react-app-polyfill/stable';`.
ref: https://github.com/facebook/create-react-app/tree/master/packages/react-app-polyfill

But consider #2468 memory leaks and the global namespace, I want to
use minimal polyfills.

By the way, I try to import only below polyfills. And it seems to work
fine. It should be more test though.

* import "core-js/features/object/values";
* import "core-js/features/object/entries";

Are these right minimal polyfills for React Hook Form?
I'm afraid it may be hard to judge.

**Comment by bluebill1049** [comment]
> I have the same problem too.
> I guess many cases works fine using `import 'react-app-polyfill/stable';`.
> ref: https://github.com/facebook/create-react-app/tree/master/packages/react-app-polyfill
> 
> But consider #2468 memory leaks and the global namespace, I want to use minimal polyfills.
> 
> By the way, I try to import only below polyfills. And it seems to work fine. It should be more test though.
> 
> * import "core-js/features/object/values";
> * import "core-js/features/object/entries";
> 
> Are these right minimal polyfills for React Hook Form?
> I'm afraid it may be hard to judge.

Thanks, @yhor1e for the feedback. It's going to be tricky for me, as I am not a windows user, yes I can spin up a virtual machine but it would be great if you can provide me some insight, consider we are already using babel to transpile the project and dedicated IE build, we can potentially investigate there.

**Comment by yhor1e** [comment]
Thank you for your time @bluebill1049.

>  it would be great if you can provide me some insight

I got it. I'll report if I notice anything.

**Comment by bluebill1049** [comment]
> Thank you for your time @bluebill1049.
> 
> > it would be great if you can provide me some insight
> 
> I got it. I'll report if I notice anything.

Thanks a lot @yhor1e

**Comment by yhor1e** [comment]
I think React Hook Form is transpiled for IE11 by Typescript without Bable or core-js now.

Refs: 
* [rollup/rollup.ie11.config.js](https://github.com/react-hook-form/react-hook-form/blob/437eb09ba758b64f056705f9c31dd626b09ceb28/rollup/rollup.ie11.config.js)
* [tsconfig.ie11.json](https://github.com/react-hook-form/react-hook-form/blob/437eb09ba758b64f056705f9c31dd626b09ceb28/tsconfig.ie11.json)
* #2702

But I'm afraid the Typescript option `"target": "es5"` is not enough for IE11.

I tried to transpile a sample code using `Object.values` by Typescript.
I created **objectValues.ts**.

```ts
const object1 = {
  a: 'somestring',
  b: 42,
  c: false
};

console.log(Object.values(object1));
```

Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values

And I ran below command.

```bash
$ tsc --version                                      
Version 4.0.2

$ tsc objectValues.ts --target es5 --lib "es2017,dom"
```

Then I got **objectValues.js**. But it doesn't include any polyfills.

```js
var object1 = {
    a: 'somestring',
    b: 42,
    c: false
};
console.log(Object.values(object1));
```

**Comment by bluebill1049** [comment]
> @bluebill1049
> 
> I think React Hook Form is transpiled for IE11 by Typescript without Bable or core-js now.
> 
> Refs:
> 
> * [rollup/rollup.ie11.config.js](https://github.com/react-hook-form/react-hook-form/blob/437eb09ba758b64f056705f9c31dd626b09ceb28/rollup/rollup.ie11.config.js)
> * [tsconfig.ie11.json](https://github.com/react-hook-form/react-hook-form/blob/437eb09ba758b64f056705f9c31dd626b09ceb28/tsconfig.ie11.json)
> * #2702
> 
> But I'm afraid the Typescript option `"target": "es5"` is not enough for IE11.
> 
> I tried to transpile a sample code using `Object.values` by Typescript.
> I created **objectValues.ts**.
> 
> ```ts
> const object1 = {
>   a: 'somestring',
>   b: 42,
>   c: false
> };
> 
> console.log(Object.values(object1));
> ```
> 
> Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values
> 
> And I ran below command.
> 
> ```shell
> $ tsc --version                                      
> Version 4.0.2
> 
> $ tsc objectValues.ts --target es5 --lib "es2017,dom"
> ```
> 
> Then I got **objectValues.js**. But it doesn't include any polyfills.
> 
> ```js
> var object1 = {
>     a: 'somestring',
>     b: 42,
>     c: false
> };
> console.log(Object.values(object1));
> ```

Thanks very much for the finding and investigation!

That's correct @kotarella1110 made this change, hmmm perhaps we will have to ask users to include polyfills? otherwise, it does make this build rather complicated.

**Comment by yhor1e** [comment]
@bluebill1049 

> hmmm perhaps we will have to ask users to include polyfills? (include them in the doc) otherwise

I think the document will explain which polyfills are necessary is better, like the below.
* `Object.values`
* `Object.entries`

I want to avoid importing the whole polyfill like `import 'react-app-polyfill/stable';`

**Comment by bluebill1049** [comment]
> @bluebill1049
> 
> > hmmm perhaps we will have to ask users to include polyfills? (include them in the doc) otherwise
> 
> I think the document will explain which polyfills are necessary is better, like the below.
> 
> * `Object.values`
> * `Object.entries`
> 
> I want to avoid importing the whole polyfill like `import 'react-app-polyfill/stable';`

Sounds great will get them included in the doc.

**Comment by yhor1e** [comment]
Thanks @bluebill1049 .

But I'm not sure only `Object.values` and `Object.entries` are necessary. There may be others.

**Comment by bluebill1049** [comment]
> Thanks @bluebill1049 .
> 
> But I'm not sure only `Object.values` and `Object.entries` are necessary. There may be others.

we can probably can include more as we go...

**Comment by bluebill1049** [comment]
<img width="959" alt="Screen Shot 2020-09-09 at 11 35 30 am" src="https://user-images.githubusercontent.com/10513364/92544166-922f3080-f290-11ea-919b-5f607ae24f5f.png">

here is what will be included in the doc.

**Comment by yhor1e** [comment]
LGTM!! :100: 

Thanks @bluebill1049 .

**Comment by bluebill1049** [comment]
Thanks very much for your help @yhor1e ❤️

**Comment by kwht-k** [comment]
@bluebill1049 @yhor1e 
Thank you so much for supporting to this issue🙇‍♂️
I also think the added description is very good.

**Comment by bluebill1049** [comment]
Doc is live: https://github.com/react-hook-form/documentation/pull/418 with reference to this issue. :)

**Comment by yhor1e** [comment]
Thank you @bluebill1049 , but I can't find the modification https://github.com/react-hook-form/react-hook-form/issues/2775#issuecomment-689243832 in react-hook-form/documentation#418.
Would you tell me which file is changed?

**Comment by bluebill1049** [comment]
Oh it’s under the FAQ ie11.

**Comment by bluebill1049** [comment]
oops forgot to push, it's updating now... :)

**Comment by vutoan266** [comment]
Not relative to IE11 but I have a problem with safari on ios11. It lacks `Array.polyfill.flat()`.
Here is the polyfill I get from https://stackoverflow.com/questions/56468914/ie11-attempt-to-use-the-method-flat-polyfill-causes-error-within-the-polyfill/56501391
```
// Also polyfill Array.isArray:
if (!Array.isArray) {
  Array.isArray = function (arg) {
    return Object.prototype.toString.call(arg) === '[object Array]';
  };
}

// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#Polyfill
if (!Array.prototype.flat) {
  Array.prototype.flat = function (depth) {
    var flattened = [];
    (function flat(array, depth) {
      for (var i = 0; i < array.length; i++) {
        var el = array[i];
        if (Array.isArray(el) && depth > 0) {
          flat(el, depth - 1);
        } else {
          flattened.push(el);
        }
      }
    })(this, Math.floor(depth) || 1);
    return flattened;
  };
}
```

**Comment by bluebill1049** [comment]
Thanks @vutoan266 for sharing solution.

**Comment by davidspiess** [comment]
@bluebill1049 `String.startsWith` polyfill is also needed for IE11.

**Comment by bluebill1049** [comment]
> @bluebill1049 A polyfill for `String.startsWith` and `Array.includes` is also required for IE11, but not mentioned in the docs right now.

would like to send a PR to include those?

**Comment by davidspiess** [comment]
Here you go! https://github.com/react-hook-form/documentation/pull/467

**Comment by bluebill1049** [comment]
> Here you go! [react-hook-form/documentation#467](https://github.com/react-hook-form/documentation/pull/467)

Amazing! thank you. your name is in the repo now :)
