### ISSUE TITLE
Fields inside useFieldArray are marked as dirty when only touched!

### ISSUE THREAD

**Issue by Elia-d** [react-hook-form/react-hook-form#2778]
**Describe the bug**
The input text fields of a field array are getting marked as dirty when touched. This seems to be happening when providing a defaultValues object to useForm.

It also seems to only be happening when having a field array nested inside an object, but I'm a 100% sure as I need to test it a bit more!

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-field-array-dirty-s9xg5?file=/src/App.js

**To Reproduce**

1. Go to the CodeSandbox provided above
2. click on add
3. press Tab to switch to the second field
4. first field is marked dirty

**Expected behavior**
Fields should not be marked as dirty.

**Desktop (please complete the following information):**

- OS: macOs
- Browser chrome
- Version 85

**Additional context**
The issue is resolved by removing the defaultValues from the useForm parameters!

**Comment by bluebill1049** [comment]
this is expected behavior. the moment you append a new field array, the form is dirty, because the initial state is `[]`.

**Comment by Elia-d** [comment]
Oh, I did not see that! 
Does that apply only for array fields? because I tried removing the default value ``` items: [] ``` but it keept behaving like that and only stopped when I removed the whole parent object default value !

**Comment by bluebill1049** [comment]
> Oh, I did not see that!
> Does that apply only for field arrays? because I tried removing the default value `items: []` but it keept behaving like that and only stopped when I removed the whole parent object default value !

It should behave the same tho with `[]` or without `defaultValues`.

**Comment by Elia-d** [comment]
It doesn't, the only way I got it to work how I wanted is by removing the default value of the parent object containing the field array and setting the default values on the input fields themselves. 

https://codesandbox.io/s/react-hook-form-field-array-dirty-s9xg5?file=/src/App.js

here, the default value ```items: [] ``` is commented out but the fields are still marked dirty when they are only touched!

Also, should it be a default behavior marking the fields dirty even though they're not? Isn't that why we have touched?!
Just curious about the motivation behind this 🙂

Thank you so much 🙏

**Comment by bluebill1049** [comment]
> https://codesandbox.io/s/react-hook-form-field-array-dirty-s9xg5?file=/src/App.js

Thanks, I will patch that. 

For field array, the moment you append a new item, it mays the form value is been updated even you not filling up any value.

**Comment by bluebill1049** [comment]
nvm, this is already patched in `6.7.0`, I think for append you should append with all the fields as well, instead just empty `{}`

**Comment by Elia-d** [comment]
Man, you rock!
Thank you for the great work 🙏

**Comment by bluebill1049** [comment]
np ;)

**Comment by joaovbibiano** [comment]
How can I show the proper ErrorMessage? When I add a new "line" the touched is already true

I have an example here https://codesandbox.io/s/restless-currying-4wh6h?file=/src/App.tsx
