### ISSUE TITLE
defaultValues showing up as undefined on submission when the field is disabled

### ISSUE THREAD

**Issue by soojison** [react-hook-form/react-hook-form#2782]
**Describe the bug**
I think it might be related to #2655, but slightly different. I am creating a form where I have defaultValues that pre-populate the form, but a field needs to be disabled so the user cannot change it. In the previous version I used (6.3.3), on submission, I used to get the value back, but in the latest version (6.7.0) it is showing up as undefined.

**To Reproduce**

1. Create a form with default values
2. disable the input field
3. Click submission
4. The field value is undefined

**Codesandbox link (Required)**
I'm using the same form you linked as an example in one of the help threads.
https://codesandbox.io/s/mystifying-grass-zelzc?file=/src/App.js

If I change the input field to have the disabled prop and click submit, this is what I see
![Screen Shot 2020-08-31 at 10 52 41 AM](https://user-images.githubusercontent.com/10430283/91739882-26561500-eb78-11ea-8c14-3c29ce307354.png)

**Expected behavior**
I expect the submitted values to have the same value as the defaultValues.

**Desktop (please complete the following information):**

- OS: Mac
- Browser Chrome
- Version 6.7.0 (latest)

**Comment by bluebill1049** [comment]
use readOnly :) https://twitter.com/bluebill1049/status/1300231640392716288

**Comment by soojison** [comment]
@bluebill1049 gotcha. One more thing though -- readonly works for input fields, but it doesn't seem to work for <select> dropdowns. Is there a way to make it work?

**Comment by bluebill1049** [comment]
> @bluebill1049 gotcha. One more thing though -- readonly works for input fields, but it doesn't seem to work for dropdowns. Is there a way to make it work? If not I'll just stay in my current version :(

can you give an example with dropdown?

**Comment by soojison** [comment]
For this sandbox: https://codesandbox.io/s/cool-hopper-p7etf?file=/src/App.js

I put the readOnly property on the input tag, and I can't change the value. The submission value also is the same as defaultValues. This is working as expected :) 

But for the <select> tag, I set the readOnly property, but I am still able to change the value of the dropdown and submit a changed value.

![form](https://user-images.githubusercontent.com/10430283/92026138-298f0380-ed26-11ea-8474-9c45f8f09470.gif)

**Comment by bluebill1049** [comment]
have a read here: https://stackoverflow.com/questions/368813/html-form-readonly-select-tag-input HTML

**Comment by nathggns** [comment]
I really don't think "use readOnly" is sufficient – it's incredibly unexpected behavior that defaultValues don't show up in the values dictionary on submission regardless of whatever attributes you put on the field. Why not solve this edge case?

**Comment by bluebill1049** [comment]
> I really don't think "use readOnly" is sufficient – it's incredibly unexpected behavior that defaultValues don't show up in the values dictionary on submission regardless of whatever attributes you put on the field. Why not solve this edge case?

pretty sure you can get around the issue with `shouldUnregister: false` and include those value in the `defaultValues`, but again I am just trying to follow the standard here.

**Comment by 08screasey** [comment]
@bluebill1049 There seems to be some difference between how a controller manages this and how a regular input does. For example I have a case in which "react-phone-number-input", which implements react hook form's Controller actually maintains the value of the disabled input on submit, whereas my own disabled input has a value of undefined on submit. I am using v6.15.7. What is the best way to get consistent results, would it be worth wrapping my simple input in a controller?
P.S: Your work is fantastic.

**Comment by mdshahin-ahmed** [comment]
> For this sandbox: https://codesandbox.io/s/cool-hopper-p7etf?file=/src/App.js
> 
> I put the readOnly property on the input tag, and I can't change the value. The submission value also is the same as defaultValues. This is working as expected :)
> 
> But for the select tag, I set the readOnly property, but I am still able to change the value of the dropdown and submit a changed value.

Thank you so much!

**Comment by nandastone** [comment]
`<input type="checkbox" readonly />` has no effect in modern browsers, `disabled` is the only attribute that will prevent the user from interacting with the input unless we resort to JS or tricky CSS.

**Comment by bluebill1049** [comment]
`<fieldset disabled><input type="checkbox" /></fielset>` ?

**Comment by Nirmitjatana** [comment]
> > I really don't think "use readOnly" is sufficient – it's incredibly unexpected behavior that defaultValues don't show up in the values dictionary on submission regardless of whatever attributes you put on the field. Why not solve this edge case?
> 
> pretty sure you can get around the issue with `shouldUnregister: false` and include those value in the `defaultValues`, but again I am just trying to follow the standard here.

I tried using it, but it does not work. This prolly is an issue, even though the field is interactive, all the not modified values are `undefined` in the data object.
