### ISSUE TITLE
some data not being submitted on controlled components on field array since 6.5.0

### ISSUE THREAD

**Issue by ilovett** [react-hook-form/react-hook-form#2783]
**Describe the bug**

The submit data is different for same code between 6.4.1 and 6.5.0, 6.4.1 submits everything where 6.5.0 leaves out some values.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-query-builder-forked-t5gwk?file=/src/QueryBuilder.tsx
2. Fill out a condition (cost, greater than, 5)
3. Click submit -> on 6.4.1 submitted values good:

```json
{
    "query": {
        "type": "group",
        "operator": "$or",
        "items": [
            {
                "type": "cond",
                "data": {
                    "field": "weight",
                    "operator": "$gt",
                    "value": 5
                }
            }
        ]
    }
}
```

4. Change to 6.5.0 or above, submit leaves out some values:

```json
{
    "query": {
        "items": [
            {
                "data": {
                    "operator": "$gt"
                }
            }
        ],
        "type": "group",
        "operator": "$or"
    }
}
```

**Additional context**

I noticed that `name` prop was added to render props in 6.5.0, I suspect the change might be related.  In the CSB though, that prop is spread onto the rendered element.

**Comment by ilovett** [comment]
Actually just tried 6.7.0 appears to have fixed it...

**Comment by bluebill1049** [comment]
sorry about the regression...
