### ISSUE TITLE
Focus error field on manually triggered validation

### ISSUE THREAD

**Issue by kreftk** [react-hook-form/react-hook-form#2791]
**Is your feature request related to a problem? Please describe.**
Currently there is a different behaviour whether the error field is focused on validation. If validation is triggered by `onSubmit` the field is focused but if validation is triggered manually by `trigger()` the error field is not focused.

**Describe the solution you'd like**
I assume that this is the desired behaviour so it would be awesome to have an opt-in option in a config object as an argument:
```ts
trigger: (payload?: string | string[], config?: { shouldFocusError: boolean = false }) => Promise<boolean>
```

**Example**
https://codesandbox.io/s/mutable-dust-tglj1?file=/src/App.js

Would like to work on this feature if desired 😉

Awesome project 🙂

**Comment by bluebill1049** [comment]
Thanks @kreftk I will tag it as a feature request and waiting for more users to vote before including the feature.

**Comment by bluebill1049** [comment]
proposal API:

```ts
trigger('test', { shouldFocus: true })
```

by default `trigger('test', { shouldFocus: false })`

**Comment by kreftk** [comment]
@bluebill1049 Your proposed API LGTM 🙂 
Should I work on this feature?

**Comment by bluebill1049** [comment]
if you interested, yes please @kreftk.

**Comment by pablohenriquedev** [comment]
Hello guys. Is this feature ready to use?
