### ISSUE TITLE
"onTouched" mode not work with Controller component

### ISSUE THREAD

**Issue by Luchanso** [react-hook-form/react-hook-form#2792]
**Describe the bug**
When use `<Controller />` with render props, validation not correct fire with "onTouched" mode

**To Reproduce**

1. Focus input, enter "bla", change focus from input. Should render error about `minLength` 🆗 
2. Focus input again, enter "blabla". Error should hide ❌ 

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-get-started-forked-4pgcw?file=/src/index.js

**Expected behavior**
1. Focus input, enter "bla", change focus from input. Should render error about minLength 🆗
2. Focus input, enter "blabla". Error should hide 🆗 

Like here https://codesandbox.io/s/react-hook-form-useform-template-forked-3yrrv?file=/src/index.js

**Desktop**

- OS: MacOS
- Browser: Chrome
- Version 84.0.4147.135

**Comment by bluebill1049** [comment]
hey, @Luchanso thank you so much for sponsoring me! too kind. ❤️
