### ISSUE TITLE
checkbox material ui not correct working

### ISSUE THREAD

**Issue by publicaccount365** [react-hook-form/react-hook-form#2799]
**Describe the bug**
checkbox material ui not correct working in version 6.7.0 react-hook-form.
when set default true for checkbox not work, and change state checkbox (true/false) not correct working.
always true when default true, if you uncheck checkbox, value still true

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-controller-forked-m1t48?file=/src/index.js
2. Click on submit then see change state checkbox not working on data

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-forked-m1t48?file=/src/index.js

**Desktop (please complete the following information):**

- Browser [e.g. chrome]
- Version [84.0.4147.135]

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r
