### ISSUE TITLE
Get form values without register

### ISSUE THREAD

**Issue by BorisTB** [react-hook-form/react-hook-form#280]
**Is your feature request related to a problem? Please describe.**
It wasn't really obvious in doc that I must use `register` on every input to get its value on submit. This lib is really great (and your documentation page is beautiful) but I actually don't need any other functionality, just to handle submit and process input values.
// Ok, I just noticed "Get started" page and there it's super obvious that every field must be registered, my bad :/ 

**Describe the solution you'd like**
Would be great if there was an option to prefer getting value on submit automatically from `e.target.elements`. Something like `submitNotRegisteredFields?: boolean`

**Describe alternatives you've considered**

**Additional context**

**Comment by bluebill1049** [comment]
Hi @BorisTB, thanks for your kind words :) Yes, good suggestion. This was one of the features also suggested by @stramel. However, there is some flaw around this feature, this is not going to work smoothly with some of the custom components which have been created by the community, such as `react-select`. it's hard to assume what to grab within the form tag. hope this makes sense :)

**Comment by bluebill1049** [comment]
hey @BorisTB, just a quick follow up, is the above comment make sense before I close this issue?

**Comment by BorisTB** [comment]
Absolutely, thank you for explanation, I understand that there would be tons of bug reports even if you'd warn people they have to use register with custom components.

**Comment by bluebill1049** [comment]
Cool going to close this issue for now :)
