### ISSUE TITLE
6.7.0/6.7.1 setValue for conditionally registered field not working

### ISSUE THREAD

**Issue by szymonlesisz** [react-hook-form/react-hook-form#2808]
**Describe the bug**
Since 6.7.0 setValue method doesn't change values for field which are registered (rendered) conditionally
It works with 6.6.0

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-useform-template-forked-9nu6m
2. Click on TOGGLE
3. Additional input should be filled with value
4. `console.warn(getValues())` doesn't show the value

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-forked-9nu6m?file=/src/index.js

**Expected behavior**
Should set the `additionalField` value, like v6.6.0

**Comment by bluebill1049** [comment]
it's correct behavior now because the input wasn't mounted and it was a bug at 6.6.0.
you do use shouldUnregister: false tho: 

https://codesandbox.io/s/react-hook-form-useform-template-forked-5k9py?file=/src/index.js

**Comment by szymonlesisz** [comment]
thanks for quick response!

i'm working `useFieldArray` in my form as well (by the docs `shouldUnregister` doesnt work there yet) 
so when i set `shouldUnregister: false` i'm getting error in different part of the code where use `setValue` like:
`setValue(`input[${index}].field` , 'VAL')`

 `TypeError: Cannot assign to read only property '0' of object '[object Array]'`

is there any solution for that?

**Comment by bluebill1049** [comment]
> thanks for quick response!
> 
> i'm using `useFieldArray` in my form as well (by the docs `shouldUnregister` doesnt work there yet)
> so when i set `shouldUnregister: false` i'm getting error in different part of the code where use `setValue` like:
> `` setValue(`input[${index}].field` , 'VAL') ``
> 
> `TypeError: Cannot assign to read only property '0' of object '[object Array]'`
> 
> is there any solution for that?

I guess you can probably stay with 6.6.0 for now.

I am working on this PR to get `shouldUnregister` with `useFieldArray` over the line: https://github.com/react-hook-form/react-hook-form/pull/2691
