### ISSUE TITLE
Disabled "Select" values appear in form submit

### ISSUE THREAD

**Issue by jl-gogovapps** [react-hook-form/react-hook-form#2809]
**Describe the bug**
Similar to https://github.com/react-hook-form/react-hook-form/issues/2655, but for a Semantic-UI-React Select box.  I'd expect that the value is omitted from the onSave data payload, but it is included

**To Reproduce**

1.  Open sandbox link below
3.  Click "Submit"
4.  Observe `{"testSelect":"a"}` under the input field

**Codesandbox link (Required)**
Based on the codesandbox https://github.com/react-hook-form/react-hook-form/issues/2655
[Codesandbox](https://codesandbox.io/s/distracted-leakey-bv8v3?file=/src/App.js)

**Expected behavior**
I would expect that the output below the submit button does not include an entry for "textSelect

**Screenshots**

<img width="275" alt="Screen Shot 2020-09-03 at 10 49 23 AM" src="https://user-images.githubusercontent.com/44532602/92130794-24d45900-edd3-11ea-899c-8447aa01079e.png">

**Desktop (please complete the following information):**

- OS: OSX
- Browser Chrome
- Version 84

**Comment by bluebill1049** [comment]
it doesn't work with Controller, use native select, controller is meant for some input doesn't expose `ref`, so it doesn't read all the attribute. for native input just register them or expose/forward ref.

https://codesandbox.io/s/hungry-surf-6lppo?file=/src/App.js

**Comment by jl-gogovapps** [comment]
Hm, I'm not sure I follow, as the Select I'm using is not native.  Is there a way for Controlled inputs that are disabled to be excluded from the form state?  

Is this a feature request?

**Comment by bluebill1049** [comment]
you can post a feature request for the controller to support `disabled`.

**Comment by jl-gogovapps** [comment]
will do! thanks!
