### ISSUE TITLE
File input becomes "Dirty" when it loses focus

### ISSUE THREAD

**Issue by connelhooley** [react-hook-form/react-hook-form#2810]
**Describe the bug**
The file input appears to become "dirty" before its change event has triggered.

**To Reproduce**
There are two scenarios I've noticed.

Not selecting a file:
- Click on a registered file input.
- Even while the window picker window is open, the form is now dirty.

File input losing focus:
- "Tab" onto a registered file input so that it is focused.
- Press tab again so it loses focus.
- The form is now dirty.

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-v6-controller-forked-vne5q

- Click on the text box at the top, press tab twice and you will see the form is dirty.
- Click on the file input and you will see the form is dirty.

**Expected behaviour**
The form should only be dirty if the user actually selects a file.

**Desktop (please complete the following information):**

Chrome:
- OS: Windows
- Browser Chrome
- Version 85.0.4183.83

Firefox:
- OS: Windows
- Browser Firefox
- Version 80.0.1 (64-bit)

**Comment by bluebill1049** [comment]
<img width="988" alt="Screen Shot 2020-09-04 at 8 24 59 am" src="https://user-images.githubusercontent.com/10513364/92179511-23189d00-ee88-11ea-84a5-39f0052709a2.png">

The file input is immutable :(

**Comment by connelhooley** [comment]
Thanks for getting back to me @bluebill1049, apologies I missed that part of the docs.

**Comment by bluebill1049** [comment]
no worries at all @connelhooley
