### ISSUE TITLE
Strange async submit bug introduced on 6.5.0

### ISSUE THREAD

**Issue by outerlook** [react-hook-form/react-hook-form#2812]
Hi!

On my app I identified a bug where "isSubmitting" doesn't respect async functions on submitting form.

I will later identify where exactly this is happening to create a proper CodeSandBox repro.

But I couldn't so far... Async examples here are working fine.
I know this is on 6.5.0 because I was testing each version to find the one that breaks the behavior.

May I raise this issue til I figure out how to reproduce this?

This still happens on latest version

Version 6.4.1 with correct behavior
![rhf 6-4-1](https://user-images.githubusercontent.com/12937160/92178195-63d8cd80-ee18-11ea-8291-ec9ef7ca7a2a.gif)

Version 6.5.0
![rhf 6-5-0](https://user-images.githubusercontent.com/12937160/92178215-70f5bc80-ee18-11ea-8ba1-919edd556bcb.gif)

**Comment by bluebill1049** [comment]
oh, strange... I will look into it as well.

**Comment by bluebill1049** [comment]
I think i may find the root cause.

**Comment by bluebill1049** [comment]
it's due to proxy.

**Comment by bluebill1049** [comment]
are you consume formate like this?

`{formState.isSubmitting}` and it's inside the render?

**Comment by outerlook** [comment]
Precisely!
![image](https://user-images.githubusercontent.com/12937160/92248256-c5437f80-ee9e-11ea-8a63-016aaa46b7d6.png)

Thanks a lot for looking into this so quickly. It's working like a charm.
:)

**Comment by ejose19** [comment]
In my case this is still not fixed, I upgraded from 6.3.3 to 6.7.2 and isSubmitting is still true, can confirm latest working version is 6.4.1.

Here's the [sandbox](https://codesandbox.io/s/proud-currying-w5n00?file=/src/form.tsx) displaying the issue, isSubmitting remains true after a reset. You can change the sandbox version to 6.4.1 and see it works as expected.

**Comment by ejose19** [comment]
I think I've found the issue, it seems that here: https://github.com/react-hook-form/react-hook-form/blob/88d454f820e1f1baef77d7166127ccc600bebd91/src/useForm.ts#L162-L170

formStateRef.current still holds isSubmitting = true, but state doesn't have that property so when merged it still persist, shouldn't state contain isSubmitting property as well? I've checked and it's the only one that doesn't exist in state but it does on formStateRef

**Comment by ejose19** [comment]
@bluebill1049 I've submitted #2830 with my proposed solution for this, feel free to take a look.

**Comment by alexssandrog** [comment]
Hi @bluebill1049 , in which version will this fix be released? In 6.7.2 the problem still occurs...

**Comment by bluebill1049** [comment]
> Hi @bluebill1049 , in which version will this fix be released? In 6.7.2 the problem still occurs...

will release the fix those weekend or even earlier.
