### ISSUE TITLE
setValue() or reset() is not working with Antd Radio Group

### ISSUE THREAD

**Issue by Codyooo** [react-hook-form/react-hook-form#2821]
version: @6.7.2 
setValue() , reset() and `defaultValue`  is not working with Antd Radio Group 

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-forked-x1rc2?file=/src/index.js:0-1233

**Comment by bluebill1049** [comment]
hey @Codyooo you miss the value prop: https://codesandbox.io/s/react-hook-form-useform-template-forked-wjzzf?file=/src/index.js

**Comment by Codyooo** [comment]
You saved my day !😺👍👍
