### ISSUE TITLE
Unable to supply/reset to defaultValue within Controller with render()

### ISSUE THREAD

**Issue by berrybell** [react-hook-form/react-hook-form#2824]
**Describe the bug**
I am experiencing a number of bugs when supplying default values a React-Select within a Controller that is using a render prop. The component is not receiving the values supplied in `useForm()` and is not able to reset to default values supplied to `reset()`. 

**To Reproduce**

1. Go to CodeSandbox below. Despite default values being supplied to useForm(), they are not picked up by the component.
2. Uncomment the lines 41 and 51 to get a default value for the component. 
3. Change the value of Select.
4. Click Reset button. The value is not reset although it is supplied to reset().

**Codesandbox link (Required)**
https://codesandbox.io/s/fervent-roentgen-81c43

**Expected behavior**
Being able to provide a default value and forward it to the component in render() with the rest of functionality working as described.

**Comment by bluebill1049** [comment]
please refer to the doc under `Controller`: https://react-hook-form.com/api#Controller

there is a codesadnbox example in the doc as well: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r

**Comment by berrybell** [comment]
@bluebill1049 
Could you elaborate? If I do not provide `defaultValue`, the component does not actually receive it. You can see that in my CS by commenting that line out. 

The CS in the doc does not actually answer my use case since I need to provide a custom `onChange` for the component, which as I understand is only possible with `render` and not with `as`.

**Comment by bluebill1049** [comment]
@berrybell please take a look at my codesandbox in the above comment, it has the exact correct usage, which is the same as what's in the doc. You should wire up `value` or `checked` instead `defaultValue` with render props.

<img width="538" alt="Screen Shot 2020-09-09 at 7 53 16 pm" src="https://user-images.githubusercontent.com/10513364/92583721-1bb52180-f2d6-11ea-99cc-2c573a95b504.png">
