### ISSUE TITLE
Allow for Controller components to be disabled

### ISSUE THREAD

**Issue by jl-gogovapps** [react-hook-form/react-hook-form#2826]
**Is your feature request related to a problem? Please describe.**
#2809 

**Describe the solution you'd like**
```
Given I have a form
And a `Controller` component is marked as `disabled={true}`
And the `Controller` component has a value
When I submit the form
+Then the `Controller` component field is not included in the submission payload
-Then the `Controller` component field is included in the submission payload
```

**Describe alternatives you've considered**
- Workarounds include pre-processing the data payload in the handleSubmit callback

**Comment by bluebill1049** [comment]
hey @jl-gogovapps take a look at this section: https://react-hook-form.com/advanced-usage#ExtendController you may find it useful

**Comment by jl-gogovapps** [comment]
@bluebill1049 this video is really great.  I learned quite a few techniques here and am definitely onboard with some of the design decisions!

However, I'm not seeing the connection.  The video addresses how to pass props to an extended controller, and use the props to **produce** a UI.  This differs from what I was hoping to accomplish - excluding disabled form elements from being included in the handleSubmit payload.

I was thinking a change would have to be made [here](https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/getFieldValue.ts#L30)

```
 57           <Controller
 58             name="myField"
 59             control={control}
 60             render={({ onChange, value }) =>
 61               <Select fluid
 62                 name="myField"
 63                 onChange={(e, { value }) => onChange(value)}
 64                 disabled={isDisabled}
 65                 options={[]}
 68                 value={value}
 69               />
 70             }
 71           />
```

In this snippet, the Select component (semantic-ui-react) already knows it should be disabled, and renders as disabled.  However, in the handleSubmit, it is still appearing as part of the data payload.

Thanks for the great work, and let me know if I'm missing the connection!

**Comment by bluebill1049** [comment]
> @bluebill1049 this video is really great. I learned quite a few techniques here and am definitely onboard with some of the design decisions!
> 
> However, I'm not seeing the connection. The video addresses how to pass props to an extended controller, and use the props to **produce** a UI. This differs from what I was hoping to accomplish - excluding disabled form elements from being included in the handleSubmit payload at **consume** time.
> 
> I was thinking a change would have to be made [here](https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/getFieldValue.ts#L30)
> 
> ```
>  57           <Controller
>  58             name="myField"
>  59             control={control}
>  60             render={({ onChange, value }) =>
>  61               <Select fluid
>  62                 name="myField"
>  63                 onChange={(e, { value }) => onChange(value)}
>  64                 disabled={isDisabled}
>  65                 options={[]}
>  68                 value={value}
>  69               />
>  70             }
>  71           />
> ```
> 
> In this snippet, the Select component (semantic-ui-react) already knows it should be disabled, and renders as disabled. However, in the handleSubmit, it is still appearing as part of the data payload.
> 
> Thanks for the great work, and let me know if I'm missing the connection!

I think you do the following, probably need to play around with it.
```
useEffect(() => {
  if (disabled) {
    unregister('fields');
  }
}, [disabled])

return disabled ? <Select> : <Controller />
```

**Comment by jl-gogovapps** [comment]
Hm - i suppose this could work, although it does feel a bit untidy to me. 

Can you describe some of the thoughts an approach where the `getValue` function could detect a Controller and consume a `disabled` property?

**Comment by foray1010** [comment]
> I think you do the following, probably need to play around with it.
> 
> ```
> useEffect(() => {
>   if (disabled) {
>     unregister('fields');
>   }
> }, [disabled])
> 
> return disabled ? <Select> : <Controller />
> ```

But it will lose the value when disabled. Users probably will need to save the current value in state too, which is more messy.

**Comment by bluebill1049** [comment]
> > I think you do the following, probably need to play around with it.
> > ```
> > useEffect(() => {
> >   if (disabled) {
> >     unregister('fields');
> >   }
> > }, [disabled])
> > 
> > return disabled ? <Select> : <Controller />
> > ```
> 
> But it will lose the value when disabled. Users probably will need to save the current value in state too, which is more messy.

`shouldUnregister: false` will remain that input's value. however, I think it's probably easier to take care at the controlled input level rather than at `Controller`.

**Comment by texttechne** [comment]
Actually this feature would conform to HTML standards:
> The Boolean disabled attribute, when present, makes the element **not mutable**, focusable, **or even submitted with the form**. The user can neither edit nor focus on the control, nor its form control descendants.
>
> If the disabled attribute is specified on a form control, the element and its form control descendants **do not participate in constraint validation**. Often browsers grey out such controls and it won't receive any browsing events, like mouse clicks or focus-related ones.
[MDN - Disabled Attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled)

Given this background, I think it should be part of the core to support `disabled` & probably `readonly` as well:
* disabled / readonly: no constraint validation
* disabled: property is not part of the submitted form

**Comment by diloreto** [comment]
Agree with @texttechne comment's above; the Controller component should support all valid HTML standards (readonly, disabled, etc.). Is there an ETA on this feature as the ticket was opened over a year ago?

Thank you!

**Comment by Moshyfawn** [comment]
> Is there an ETA on this feature as the ticket was opened over a year ago?

Looking at the [project's board](https://github.com/react-hook-form/react-hook-form/projects/1), I don't think the feature is being worked on, as it's not in any of the status columns.

**Comment by texttechne** [comment]
@diloreto @Moshyfawn Please "upvote" this issue, by giving the initial comment a thumbs-up.
At least that's my understanding of status: Waiting-up-vote.

**Comment by Moshyfawn** [comment]
The issue has been closed and "feature request" and "waiting-up-vote" has been removed
![image](https://user-images.githubusercontent.com/16290753/150761482-d2297583-f86c-49c8-b19f-1be7871f4ec3.png)

**Comment by texttechne** [comment]
ooops. @bluebill1049 any objections to mark this as "waiting-up-vote" again?
