### ISSUE TITLE
Controller with MUI Checkbox or Switch return "false" always

### ISSUE THREAD

**Issue by cargallo** [react-hook-form/react-hook-form#2827]
MUI checkbox or MUI switch always return the value "false" when used in this way:

 ```tsx
<Controller name="Checkbox" 
          control={control} 
          as={<Checkbox />} 
        />
```
Here is a sandbox to check: 

https://codesandbox.io/s/react-hook-form-v6-controller-forked-2mt0z?file=/src/Mui.js

As an alternative I am using with render, but had to change my code.

**Comment by bluebill1049** [comment]
> I was thinking about this and other issues that I had in the past. Maybe I am wrong but I think that Controller is a great feature of the library and it gets the job done, but I think that RHF is in a state that having custom Controllers for each UI library could be easier to mantain and to solve this kind of burry logics...

yea, i think that would be great, but at the same time i don't think i have the capability to track those UI component update and keep them sync, it's better to leave other users to develop on top RHF.
