### ISSUE TITLE
Release notes for Version 6 are incomplete

### ISSUE THREAD

**Issue by IronSean** [react-hook-form/react-hook-form#2828]
Sorry, this isn't a bug. Possibly a feature request but that's not quite right either. It's feedback on the release process.

The Release Notes for Version 6.0.0 do not mention anything about the breaking changes involved in migrating from v5 => V6.

https://github.com/react-hook-form/react-hook-form/releases/tag/v6.0.0

I believe I've found the breaking changes in v6.00-rc1, but as a non-bleeding-edge user who would not install release candidates, I would have an easier time upgrading if any release candidate change logs we combined into the release 6.0.0 release notes.

I believe most of your users would fall into a similar category: Unless they're actively involved in helping beta test and improve a release candidate the typical upgrade path would be from v5.x.x => v6.0.0 skipping any `-rc` releases. As such, I feel the release notes/changelog for all full releases should combine any `-rc` release changes  so users who are not involved in beta testing don't need to look through 6 release candidates of adding and removing features to figure out which stayed and which were rolled back.

**Comment by bluebill1049** [comment]
Thanks for the feedback @IronSean take a look at here: https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG feel free to contribute if we have missed things.

Take a look at this section as well: https://react-hook-form.com/migrate-v5-to-v6 (same it's open-source feel free to contribute and improve)

**Comment by bluebill1049** [comment]
going to close this issue, feel free to let me what's missing, and happy to getting PRs as well.
