### ISSUE TITLE
Watched fields do not change when `shouldUnregister: false` is set

### ISSUE THREAD

**Issue by dannyshaw** [react-hook-form/react-hook-form#2835]
**Describe the bug**

When `shouldUnregister: false` is set, `useEffect()` routines do not run on subsequent updates of data that has a watched nested  (dot notation) fields object as a dependency. At least not in the way it does when `shouldUnregister: true`

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-shouldunregiser-controller-bug-37rwl?file=/src/index.js
1. Enter numbers into the input fields
1. The total at the bottom will update for the first number inputted but not subsequent.
1. Change to `shouldUnregister: true`  (or comment out) to see the expected behaviour.

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-shouldunregiser-controller-bug-37rwl?file=/src/index.js

**Expected behavior**

I expect the `useEffect()` hook that has `watch`ed nested fields as it's dependency to execute when the data in that dependency changes.

**Screenshots**
NA

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser Chrome
- Version 85

**Smartphone (please complete the following information):**
NA

**Additional context**

I'm wondering if there's an object equality check going on here.

**Comment by bluebill1049** [comment]
we don't memo what's return from watch, perhaps you don't even need `useEffect` for the watch value.

**Comment by bluebill1049** [comment]
or you can consider using this package from kent: https://github.com/kentcdodds/use-deep-compare-effect

**Comment by dannyshaw** [comment]
ok. Out of interest, why does it work as expected when `shouldUnregister` is true?

**Comment by bluebill1049** [comment]
I can think with `shouldUnregister` set to `false`, we are doing extra data merging. on top of that, would suggest removing that extra `useState` and just doing that calculation inside your component.
