### ISSUE TITLE
clearErrors doesn't clear the custom setError

### ISSUE THREAD

**Issue by vladi-strilets** [react-hook-form/react-hook-form#2845]
**Describe the bug**
The `clearErrors()` function with specified error name doesn't clear the custom error when I use `setError()`

**To Reproduce**
https://codesandbox.io/s/react-hook-form-useform-template-forked-hohuf

1. Click submit
2. You can see on the console that after clicking the button "Clear custom error",  errors object still contains the custom error.

**Expected behavior**
Clear the custom error from errors object.

**Comment by bluebill1049** [comment]
you can get away with this issue now with

`clearErrors('test', { exact: false })`
