### ISSUE TITLE
v6.7.2 with react-datepicker

### ISSUE THREAD

**Issue by Migggz** [react-hook-form/react-hook-form#2847]
**Describe the bug**
`react-hook-form` latest version `6.7.2` doesn't work with `react-datepicker`

**To Reproduce**
Try to select any date from datepicker dropdown

**Codesandbox link (Required)**
the same example in Controller, but upgraded `react-hook-form`

[![Edit React Hook Form - Controller (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-hook-form-controller-forked-r39np?fontsize=14&hidenavigation=1&theme=dark)

**Expected behavior**
Date selected

**Comment by pmaier983** [comment]
Replace 
```javascript
            <Controller
              as={ReactDatePicker}
              control={control}
              valueName="selected" // DateSelect value's name is selected
              onChange={([selected]) => selected}
              name="ReactDatepicker"
              className="input"
              placeholderText="Select date"
            />
```
with
```javascript
            <Controller
              control={control}
              name="ReactDatepicker"
              render={(props) => (
                <ReactDatePicker
                  {...props}
                  className="input"
                  placeholderText="Select date"
                  selected={props.value}
                />
              )}
            />
```

**Comment by bluebill1049** [comment]
Thanks @pmaier983

**Comment by pmaier983** [comment]
Also this is the most up to date controller example: https://codesandbox.io/s/react-hook-form-v6-controller-24gcl?file=/src/index.jsx:4625-4990. 😄 . Not 100% sure where your example came from, could you send me a link?

**Comment by Migggz** [comment]
@pmaier983 Many thanks 😃 
It was the controller example before v6, I maybe reached it somewhere on github or stackoverflow
