### ISSUE TITLE
Unable to reset form - still dirty

### ISSUE THREAD

**Issue by YM-KA** [react-hook-form/react-hook-form#285]
The form is still dirty after submitting the form and then performing reset(). 
Form validation is then performed instantly on field change - not after submit. 

**To Reproduce**
1. Fill out SignupForm with an already registered email address (see code below)
2. The form does _not_ validate field input before submit 
3. onSubmit() dispatches an action that calls firebase.auth() API that returns a rejection
4. The form is reset() 
5. The form is still dirty reporting several fields as "touched"
6. The form now validates instantly on field change, not _after_ submit

```
{
  "dirty": true,
  "isSubmitted": true,
  "submitCount": 1,
  "touched": [
    "email",
    "name",
    "password"
  ],
  "isSubmitting": false,
  "isValid": false
}

```
**Expected behavior**
Form validation to always be triggered on Submit, not instantly on field change. 

**Desktop **
 - MacOS 10.14.6 and Windows 10 1903
 - Chrome  76.0.3809.132
 - Firefox 68.0.2

**Code  excerpt**
```
export const SignupPage = (props) => {
  const { register, handleSubmit, errors, formState, getValues, setValue, reset } = useForm()

  const onSubmit = (data, e) => {
    let signupObj = { ...data, provider: REGISTER_ACCOUNT }
    props.startSignup(signupObj).then((response) => {
      const isLoggedIn = response.isAnonymous === undefined ? false : !response.isAnonymous
      if (isLoggedIn) {
        e.target.reset() // reset form on login
      }

      //Submit fail
      if (response.code === 'auth/email-already-in-use') {
        e.target.reset()
        //User gets prompted to try registering with another email address
        //Typing in any field triggers validation instantly 
        //Validation should only trigger next time user submits - just like before first submit 
      } 
      //...
    })
  }
  
  return (
    <div>
      <form onSubmit={handleSubmit(onSubmit)} autocomplete="on">
        {!isEmpty(errors) &&
          <div>
            <span>
              {errors.email && '- Please specify an email address'}
            </span>

          </div>
        }
        <input
          id="email"
          name="email"
          type="email"
          placeholder="email address"
          ref={
            register({
              required: true,
              minLength: 4,
            })
          }
        />
        <label for="name">Name</label>
        <input
          id="name"
          name="name"
          type="text"
          placeholder="name"
          ref={register({ required: true, maxlength: 20 })}
        />
      </form>
    </div>
    )
}
```

**Comment by bluebill1049** [comment]
any chance to provide a codesandbox for the issue?

**Comment by YM-KA** [comment]
I tried, but the sandbox gave me other problems. I will give it another go and send you the link.

**Comment by YM-KA** [comment]
Hi @bluebill1049 thanky ou for the reply! 
I have made a sandbox example that imitates the behaviour as close as I can. :)
https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-5v5jr

I am not fluent in promises, maybe the reject() from the Fgirebase API is the problem? 
I hope you might be able to point it out to me, if that is the case. 

Many thanks! /K

**Comment by YM-KA** [comment]
Hi @bluebill1049 ! I managed to remedy the problem. It was not related to react-hook-form. 
I simply called the firebase.auth() in a wrong way. 

My revised - working - code:
```
const onSubmit = (data, e) => {
    firebase.auth().createUserWithEmailAndPassword(data.email, data.password)
    .then((user)=> {
      //Success
      reset()
    })
    .catch((error)=>{
      //Fail
      //get submitted form values - only clear password
      let formValues = getValues()
      delete formValues.password
      if (error.code === AUTH_ERR_EMAIL_IN_USE || error.code === AUTH_ERR_INVALID_EMAIL || error.code === AUTH_ERR_NOT_ALLOWED || error.code === AUTH_ERR_WEAK_PW) {
        handleStatusMessage(error.code)
        reset(formValues)
      } else {
        handleStatusMessage('my-unknown-error')
        reset(formValues)
      }
    })
  }
```

Many thanks for taking your time to respond!

**Comment by bluebill1049** [comment]
Nice! Not a problem at all :) feel free to raise other issues if u encounter any :)
