### ISSUE TITLE
Controller render prop includes dirty/error in params

### ISSUE THREAD

**Issue by anhquande** [react-hook-form/react-hook-form#2850]
**Is your feature request related to a problem? Please describe.**
In the `<Controller>`, `render `function does not include the property field `dirty `or field `error `in the parameter list. 
I always have to build a` <ControllerWrapper> `in order to inject these two properties in the `render `function.

**Describe the solution you'd like**
My solution is:
```
function ControllerWrapper({name, formMethods, disabled, rules, defaultValue, render}) {
  const {control, formState} = formMethods;
  const {dirtyFields, errors} = formState;
  const dirty = get(dirtyFields, name);
  const error = get(errors, name);

  return (
        <Controller
          name={name}
          control={control}
          render={props => render({dirty, error, disabled, ...props});
          defaultValue={defaultValue}
          rules={rules}
        />
  );
}
```

**Describe alternatives you've considered**
It would be helpful if `dirty` and `error `are always included in the parameter list of the `render `function

**Comment by bluebill1049** [comment]
function ControllerWithState({
  name,
  control,
}) {
  const { formState } = useFormContext();
  return <Controller />
}

**Comment by bluebill1049** [comment]
what about the following?
```tsx
function ControllerWithState({
  name,
  control,
  render
}) {
  const { formState } = useFormContext();

  return <Controller name={name} control={control} render={(props) => render({ ...props, formState })} />;
}
```

**Comment by bluebill1049** [comment]
If there is no objection to the above solution, I would probably close this issue?

**Comment by anhquande** [comment]
I do not quite agree with you at this point. The problem is that it would be convenient to have error/dirty for each field (formik is currently support it). If you pass the whole form State in render, then you have to get() error and dirty state manually at some points. And this piece of code is repeated in every field. 

That is why it would be much cleaner if the core returns error and dirty state of EACH FIELD, and passes them in the render/as. 

Thanks

**Comment by bluebill1049** [comment]
no worries, I will tag this as a feature request and tagged to the board for others to vote for similar requests.

**Comment by bluebill1049** [comment]
hey @anhquande I did a quick tutorial on extending Controller's functionality video: https://www.youtube.com/watch?v=Vkiyg_KfNK4&t=509s (hope you find it useful)

csb: https://codesandbox.io/s/wonderful-tree-zuuol

**Comment by anhquande** [comment]
thanks @bluebill1049 , you did a great job
