### ISSUE TITLE
validate manually registered field?

### ISSUE THREAD

**Issue by rpmonteiro** [react-hook-form/react-hook-form#286]
Let's say I have a custom component, and I register it manually from the parent (without using the ref callback).

The `validateFunction` doesn't destructure the `validate` function properly (the one that we manually register the field with).
**Consequence:** validation doesn't happen for that manually registered field

![image](https://user-images.githubusercontent.com/7824615/64111899-14377000-cd86-11e9-811f-0ea94970f28f.png)

![image](https://user-images.githubusercontent.com/7824615/64111770-c4f13f80-cd85-11e9-82e2-97fd2114c324.png)

example: https://codesandbox.io/embed/react-hook-form-custom-validation-rluk4

I don't know if I'm just misusing the library, or this is a sneaky little bug.

Thanks for your time, Bill

**Comment by bluebill1049** [comment]
hi @rpmonteiro, thanks for the codesandbox :) that helps a lot

the problem is how you used register:

https://react-hook-form.com/api#register

it's the second argument.

```
register({
      name: "firstName",
    }, {
        validate: value => {
          console.log(value)
          return value !== "bill";
        }});
```

**Comment by rpmonteiro** [comment]
ahhhhhh... fantastic!! It now works.

Thanks again, Bill!

**Comment by bluebill1049** [comment]
all good :)
