### ISSUE TITLE
Mui Checkbox Switch default value doesnt work

### ISSUE THREAD

**Issue by thiagofernando** [react-hook-form/react-hook-form#2860]
**Describe the bug**
Cannot initialize with true value in Mui Checkbox / Switch

**To Reproduce**
just open de CSB

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-forked-wfnz7?file=/src/index.js

**Expected behavior**
respect value set in default values

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Firefox
- Version last

**Comment by peksipatongeis** [comment]
You can get the default values working with **Controller** component and using the **render prop**. I think the issue is that by default react-hook-form is passing the default values as `value` named prop but **Mui Switch** and **Checkbox** expects it to be `checked`

```
<Controller
  render={({ value, onChange, ...params }) => (
    <Switch checked={value} onChange={(_, data) => onChange(data)} {...params} />
  )}
  type="checkbox"
  name="switch"
  control={control}
  defaultValue={defaultValues["switch"]}
/>
```

**Comment by bluebill1049** [comment]
Thanks @peksipatongeis for answering the issue ❤️
