### ISSUE TITLE
Wrong types for error messages when using yup to validate a field which has it's value as an array

### ISSUE THREAD

**Issue by peksipatongeis** [react-hook-form/react-hook-form#2861]
**Describe the bug**
TypeScript is complaining about missing message property on errors when using yup to validate a field that has it's value as an array. 

**To Reproduce**

If you try to submit the empty form the error state and message is shown correctly but there's an error message for helperText value on line 48

`Property 'message' does not exist on type '(DeepMap<Item, FieldError> | undefined)[]'`

**Codesandbox link (Required)**
https://codesandbox.io/s/objective-black-lz94x?file=/src/App.tsx

**Expected behavior**
Error message is shown correctly on the multiselect field even though TypeScript is complaining that the property doesn't exist on the type. I'd expect the types to reflect the actual implementation.

**Desktop (please complete the following information):**

- Windows 10
- Firefox 80.0.1

**Comment by bluebill1049** [comment]
For any nonprimitive type input value, you will have to use: https://react-hook-form.com/ts#NestedValue

https://codesandbox.io/s/infallible-panini-7duc6?file=/src/App.tsx

**Comment by peksipatongeis** [comment]
NestedValue indeed solves the problem.

Thanks for the quick reply and for the great library, it's been pleasure to use it!

**Comment by bluebill1049** [comment]
no worries @peksipatongeis glad it's working out 👍
