### ISSUE TITLE
useFieldArray `move` with react-beautiful-dnd behaves oddly with controlled components

### ISSUE THREAD

**Issue by ilovett** [react-hook-form/react-hook-form#2865]
**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-v6-controller-forked-pzfo6

**Expected behavior**

Values to render in stay in expected moved spots, errors not to be cleared.

**Screenshots**

![2020-09-09 13 17 42](https://user-images.githubusercontent.com/1776100/92648885-05d83a00-f29f-11ea-897b-5408c54487fe.gif)

**Comment by ilovett** [comment]
turns out if I switch from

```jsx
name={["items", index, "firstName"].join(".")}
```

to 

```jsx
name={`items[${index}].firstName`}
```

then it works properly... I though dot notation would work just as well but it does not. 

https://codesandbox.io/s/react-hook-form-v6-controller-forked-5zi8i?file=/src/index.jsx

**Comment by bluebill1049** [comment]
@ilovett the dot donation is going to confuse hookform if it's an array or object.
