### ISSUE TITLE
Feature Request: OnReset Callback?

### ISSUE THREAD

**Issue by connelhooley** [react-hook-form/react-hook-form#2866]
**Is your feature request related to a problem? Please describe.**
I am trying to write a light wrapper around the a `<input type="file" />` element as a work-around for https://github.com/react-hook-form/react-hook-form/issues/2810.  In my wrapper I'm using `setState`. The docs state:

> Note: For controlled components like React-Select which do not expose a ref prop, you will have to reset the input value manually with setValue or by wrapping your component with Controller.

This means whenever I have a form, the reset button has to invoke the reset method exported from `useForm` and I also have to set the value on the file input to an empty string to reset it.

I'd like to have a solution where I can have a reset button that just calls the reset method exported from `useForm` regardless of whether there are any file uploads or not.

**Describe the solution you'd like**
I was thinking an `onReset` higher order function could be exported from `useForm`. It would take in a string which is the name of the field and a function that gets called when the given field is reset. It would provide a nice companion to the `setValue` method imo.

``` typescript
import React, { useCallback, useEffect, useRef } from "react";
import { UseFormMethods } from "react-hook-form";

interface FileInputProps<TName extends string, TFields extends Record<TName, File | null>> {
    id?: string;
    accept?: string;
    name: TName;
    form: UseFormMethods<TFields>;
}

const FileInput = <TName extends string, TFields extends Record<TName, File | null>>({id, accept, name, form}: FileInputProps<TName, TFields>) => {
    const {register, unregister, setValue, setError, reset, onReset} = form;
    const fileInputRef = useRef<HTMLInputElement>(null);
    
    useEffect(() => {
        register(name as any);
        onReset(name, resetValue => {
            if (fileInputRef.current) {
                fileInputRef.current.value = "";
            }
        });
        return () => unregister(name as any);
    }, [name, register, unregister]);

    const onFileInputChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target?.files?.length === 1 && e.target.files[0]) {
            setValue(name, e.target.files[0] as any, { shouldDirty: true });
        } else if ((e.target?.files?.length ?? 0) > 1) {
            setValue(name, null as any, { shouldDirty: true });
            setError(name as any, {type: "tooManyFiles"});
        } else {
            reset({[name]: null} as any);
        }
    }, [name, setValue, setError, reset, fileInputRef]);

    return (
        <input id={id} accept={accept} type="file" ref={fileInputRef} name={name} onChange={onFileInputChange} />
    );
};

export { FileInput };
```

**Describe alternatives you've considered**
Is there a better way to have the file input cleared when a form's reset method is called?

**Comment by bluebill1049** [comment]
```
reset({
  ...getValues(),
  yourInput: 'xxx'
})
```
what about above?

**Comment by connelhooley** [comment]
Thanks for taking the time to get back to me.

I'm not sure I follow or if I've not explained what I'm trying to do correctly. Given the code snippet above I want to do the following:

``` typescript
import React from "react";
import { FileInput } from "./Form";
import { useForm } from "react-hook-form";

interface FormFields {
    name: string;
    description: string;
    file: File | null;
}

const FormPage = () => {
    const form = useForm<FormFields>();
    return (
        <>
            <form>
                <button onClick={() => form.reset()}>Reset</button> {/* How will the file input know to clear when this is clicked? */}
                <input name="name" ref={form.register({required: "Required"})} />
                <input name="description" ref={form.register({required: "Required"})} />
                <FileInput
                    form={form}
                    id="file-upload"
                    name="file"
                    accept="image/*"
                    noPadding />
            </form>
        </>
    );
};

export { FormPage };
```

My current work-around is to use a ref and clear it when the button is clicked:

``` typescript
import React, { useRef } from "react";
import { FileInput } from "./Form";
import { useForm } from "react-hook-form";

interface FormFields {
    name: string;
    description: string;
    file: File | null;
}

const FormPage = () => {
    const fileInputRef = useRef<FileInputElement>();
    const form = useForm<FormFields>();
    const onReset = () => {
        form.reset();
        if (fileInputRef.current) {
            fileInputRef.current.value = "";
        }
    };
    return (
        <>
            <form>
                <button onClick={onReset}>Reset</button>
                <input name="name" ref={form.register({required: "Required"})} />
                <input name="description" ref={form.register({required: "Required"})} />
                <FileInput
                    innerRef={fileInputRef}
                    form={form}
                    id="file-upload"
                    name="file"
                    accept="image/*"
                    noPadding />
            </form>
        </>
    );
};

export { FormPage };
```

It would be nice if the `FileInput` component could handle this but I'm not quite sure how to know when its been reset.

I want to create a generic `FormPage` component where its children will be some collection of inputs and the reset button will be in the parent `FormPage` component so I'd like to avoid it having "form specific" code in it.

Apologies if I'm missing something obvious and stupid!

**Comment by bluebill1049** [comment]
can you wrap your FileInput with `Controller` and try it with just `reset` API?

**Comment by connelhooley** [comment]
I initially tried to use the `Controller` component before I created the more complex component I previously posted. I got the following working just fine:

``` typescript
interface FileInputProps<TName extends string> {
    inputRef?: Ref<HTMLInputElement>
    id?: string;
    accept?: string;
    name: TName;
    control?: Control<Record<TName, File | null>>;
}

const FileInput = <TName extends string>({inputRef, id, accept, name, control}: FileInputProps<TName>) => {
    return (
        <Controller<"input">
            control={control}
            name={name}
            render={({name, value, onChange, onBlur}) => {
                const onFileInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
                    if (e.target?.files?.length === 1 && e.target.files[0]) {
                        onChange(e.target.files[0]);
                    } else {
                        onChange(null);
                    }
                };
                const fileInputValue = value ? undefined : "";
                return (
                    <input
                        ref={inputRef}
                        id={id}
                        accept={accept}
                        type="file"
                        name={name}
                        value={fileInputValue}
                        onChange={onFileInputChange}
                        onBlur={onBlur} />
                );
            }} />
    );
};
```

The problem with this approach is that I keep getting error messages logged in the console saying the following:

> Warning: A component is changing a controlled input of type file to be uncontrolled. Input elements should not switch from controlled to uncontrolled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

It also logs the following warning:

> file is missing in the 'defaultValue' prop of either its Controller (https://react-hook-form.com/api#Controller) or useForm (https://react-hook-form.com/api#useForm)

Even though I did specify default values in `useForm`.

I'm a little confused why file type inputs become dirty on blur instead of on change. The code above seems to behave exactly how I'd expect a file input to work with regards to being marked as dirty and being reset.

**Comment by bluebill1049** [comment]
<img width="377" alt="Screen Shot 2020-09-13 at 9 12 04 am" src="https://user-images.githubusercontent.com/10513364/93006575-3242cd80-f5a1-11ea-9fa9-8fdb879b7ab7.png">
you shouldn't have `undefined` as defaultValue, that's the same as without the value prop. try empty `string` or `null`.

> I'm still a little confused why file type inputs become dirty on blur instead of on change (#2810). The code above seems to behave exactly how I'd expect a file input to work with regards to being marked as dirty and being reset.

like I mention in the doc, the file object is immutable.

<img width="1004" alt="Screen Shot 2020-09-13 at 9 13 26 am" src="https://user-images.githubusercontent.com/10513364/93006586-64542f80-f5a1-11ea-9721-eacc025cfaa3.png">

**Comment by connelhooley** [comment]
The TypeScript definition for the `value` attribute does not allow null to be given as a value:

``` typescript
interface InputHTMLAttributes<T> extends HTMLAttributes<T> {
        ...
        value?: string | string[] | number;
        ...
    }
```

Also, programatically setting the `value` property to anything other than an [empty string](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#Value) has [no effect](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#Notes) according to MDN.

The line you highlighted `const fileInputValue = value ? undefined : "";` sets the value of the file input to an empty string if the watch comes back with null, this in turn resets the file input. If the watch comes back with a value then it doesn't set value programically, hence the undefined.

I tried to set it to null anyway and I get the following error:

> Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.

react-hook-form is a fantastic library and you clearly know more about forms than I do but I'm still confused about the FIle object being immutable as a reason for the file input elements becoming dirty on blur.

E.g. [strings are immutable](https://gomakethings.com/immutability-in-javascript/#strings), but text inputs don't become dirty on blur. Doesn't an object being immutable make it easier to track whether it's dirty or not? If it was mutable it could be mutated by any peice of code, being immutable means it can only change when the "on change" event is fired.

**Comment by connelhooley** [comment]
I should proably also mention that I set the default value in the form, the line `const fileInputValue = value ? undefined : "";` doesn't set the "default value". E.g.

``` typescript
const form = useForm<FormFields>({defaultValues: { file: null}});
...
<FileInput
    control={control}
    name="file"
    accept="image/*" />
```

**Comment by bluebill1049** [comment]
you are right null does scream for error as well, so empty string is the way to go: 

https://codesandbox.io/s/romantic-hoover-fyfgb?file=/src/App.js:242-266

> react-hook-form is a fantastic library and you clearly know more about forms than I do but I'm still confused about the > FIle object being immutable as a reason for the file input elements becoming dirty on blur.

This is due to the object immutable and doing an object compare will always lead to failure and hence the dirty becomes true, you can argue to include if and else check-in inside the hook form library, but I wouldn't think it's a good idea when something it's outside of control with object comparison and create extra noise, so it's better to leave that at app/user level.

eg

`'' !== file object`
`fileObject !== fileObject`

conclusion anything file input related it's better and should handle at user/app level.

**Comment by bluebill1049** [comment]
closing this issue, feel free to follow up with more questions.

**Comment by connelhooley** [comment]
Apologies for the late reply, I agree closing the issue makes sense.

The code box you linked to throws saying "An attempt was made to use an object that is not, or is no longer, usable" an error when I select a file. 

> you can argue to include if and else check-in inside the hook form library, but I wouldn't think it's a good idea when something it's outside of control with object comparison and create extra noise, so it's better to leave that at app/user level.

As a consumer of the library it does feel like the library should do some of the heavy lifting here. I can't see scenarios where an application wouldn't expect the libary to do the following with form inputs:

- A file input should never have a default value and should never be dirty on inital load. It is not possible to programmatically set the value to a file so setting a default value is not possible. A warning should be logged when an application sets a default value for a file input.
- A file input is marked as dirty when its "change event" fires. If the change event fires with the same file, I don't think a comparison is necessary, it is still dirty regardless.
- A file input is marked as no longer being dirty when a reset occurs. It is impossible for a file input to be marked as no longer dirty via an "on change" event. The only way to reset the input is to programatically set the value it to an empty string which should can happen when the reset method is called.

None of this is "app specfic" imo.

I can programatically do the first two bullets using "setValue". I can't do the 3rd bullet point which is why I suggested an "OnReset" callback.

Storing global state just for file inputs, when their behaviour mostly fits into the design of the library is a big shame imo.

Thanks again though for getting back to me and thanks for making such a great library.
