### ISSUE TITLE
<FormProvider> node doesn't seem to respect `style` prop

### ISSUE THREAD

**Issue by dwiyatci** [react-hook-form/react-hook-form#2872]
**Describe the bug**
Not sure if this is React or RHF-specific.

**To Reproduce**

1. Put `style={{ display: 'none' }}` on the `<FormProvider>` or on the containing node, e.g. `<App>`.
2. Observe the behavior.

**Codesandbox link (Required)**
https://codesandbox.io/s/provider-perf-forked-zjd0k?file=/src/App.js:812-824

**Expected behavior**
Form should not be shown (not mounted).

**Desktop (please complete the following information):**

- OS: MacOS 10.15.6
- Browser: Chrome
- Version: 85

**Comment by bluebill1049** [comment]
`FormProvider` it's not a div. you should create a div inside and apply style there.

**Comment by dwiyatci** [comment]
Thanks @bluebill1049, you're always lightning fast!! 🏃🏻‍♂️⚡
