### ISSUE TITLE
errors object outdated with onChange validation 

### ISSUE THREAD

**Issue by cwagner22** [react-hook-form/react-hook-form#2875]
When using `useForm({ mode: "onChange" })` the input's `onChange` callback method will have an outdated `errors` object reference in Firefox. (not happening on Chrome)

Test (look at console logs)
https://codesandbox.io/s/react-hook-form-error-v6-forked-n20z5?file=/src/index.js

1. Enter value in input: no error
2. Remove value: no error!
3. Start entering value again: now having the last error instead of none. 

Is there a better way to do that?

**Comment by bluebill1049** [comment]
<img width="1203" alt="Screen Shot 2020-09-11 at 9 19 27 am" src="https://user-images.githubusercontent.com/10513364/92822797-e6145380-f40f-11ea-807f-21ab96dabf05.png">

works fine for me here.

**Comment by cwagner22** [comment]
That's so weird, I asked 2 other people to test in Firefox and they had the same issue as me...
![image](https://user-images.githubusercontent.com/5314435/92883660-47055100-f43b-11ea-90f7-b49c3cf3c3b5.png)

**Comment by bluebill1049** [comment]
try this

`useCallback(() => {console.log(errors)}, [errors])`

**Comment by cwagner22** [comment]
Thanks, not exactly sure why but it's working indeed :)
```
  const onChange = useCallback(() => {
    console.log(errors);
  }, [errors]);
```

Just a bit cumbersome having to pass all my dependencies to useCallback but that's ok.

**Comment by bluebill1049** [comment]
or u can try to pass as an argument as well.
