### ISSUE TITLE
Nested Field Array - Deep append error using formState

### ISSUE THREAD

**Issue by MatiasCiccone** [react-hook-form/react-hook-form#2877]
**Describe the bug**
This one is a bit hard to explain.
When you have a nested field array and you append one field at the top level and immediately you append a nested field it works as expected. But when you are trying to access to `formState` right when you append a first nested field in a second field it throws an error saying `Uncaught TypeError: get is not a function or its return value is not iterable` 

**To Reproduce**
1. Go to the sandbox
2. Click on the add array field button
3. Notice it is working (both, array field and nested array field were appended correctly)
4. Uncomment line `34` that prints `formState`
5. Click on the add array field button
6. It fails with the above-mentioned error.

Extra: (Hope this extra gives you a clue of what is going on)
1. Uncomment line `34` that prints `formState`
2. Click on the remove button
3. Click on the add array field button, twice
4. It fails with the above-mentioned error on the second try. 

**Codesandbox link (Required)**
- https://codesandbox.io/s/nested-field-array-deep-append-8d0f8

**Expected behavior**
It should not fail.

**Additional context**
Using react-hook-form v6.8.0

**Comment by bluebill1049** [comment]
Thank you @MatiasCiccone for the detail issue report, man this really helps. 👍 I will take a closer look tonight.

**Comment by MatiasCiccone** [comment]
Thanks @bluebill1049 I'll try to use setValue in my project then. Thank you so much for all your effort improving the library. I really love it!
