### ISSUE TITLE
[website] form builder, input type select dropdown not updating

### ISSUE THREAD

**Issue by sktt** [react-hook-form/react-hook-form#288]
**Describe the bug**
The dropdown doesnt seem to respond to changes.

**To Reproduce**
1. go to form builder on the website
2. select som type different from "Text"
3. Text remains selected

**Expected behavior**
Update input type after select

**Screenshots**
![image](https://user-images.githubusercontent.com/1434608/64164322-4ce94f00-ce43-11e9-9ebd-9435a6579ac2.png)

**Comment by bluebill1049** [comment]
oops i will fix that :) thanks for picking that up

**Comment by bluebill1049** [comment]
fixed :) deploying

**Comment by sktt** [comment]
Works over here! cheers
