### ISSUE TITLE
Unexpected behavior when using 'onChange' mode in IE11

### ISSUE THREAD

**Issue by fourmisz** [react-hook-form/react-hook-form#2881]
**Describe the bug**
Set 'onChange' mode in IE11, required validation run on blur event without entering value.

**To Reproduce**

1. run example in dev mode
2. open IE11
3. click input

**Codesandbox link (Required)**
https://codesandbox.io/s/validationonfieldchange-example-2zcc4?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
'onChange' mode should work the same for chrome and Ie11.

**Screenshots**
- chrome
  <details><summary>show</summary>

  ![2020-09-11_10-22-29](https://user-images.githubusercontent.com/2562653/92837910-1b716f00-f419-11ea-81ba-04e40c183bbb.gif)
</details>

- IE11
  <details><summary>show</summary>

  ![2020-09-11_10-24-04](https://user-images.githubusercontent.com/2562653/92838017-3cd25b00-f419-11ea-87a3-e709d640c4d3.gif)
</details>

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser [IE11]
- Version [11.1726.17134.0]

**Additional context**
`input[type=email]` works as expected in IE11

**Comment by bluebill1049** [comment]
It's the same code that is running, if this is only IE 11 related then we probably won't introduce a fix for it unless it's a polyfill related.

**Comment by bluebill1049** [comment]
sorry for IE11 related issue, it's the lowest priority and won't' be worked on with the same code which works with modern borrower beside polyfills.
