### ISSUE TITLE
clearErrors does not affect formState.isValid

### ISSUE THREAD

**Issue by val-o** [react-hook-form/react-hook-form#2888]
**Describe the bug**
It seems calling clearErrors does not reset formState.isValid flag. Sorry, for not providing example, but I think this might be made intentionally, as I saw following lines of code at https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L695
Couldn't you please confirm is it a bug or expected behaviour?
Thanks!

```
  updateFormState({
      errors: name ? formStateRef.current.errors : {},
    });
```

**Comment by bluebill1049** [comment]
not intentional, what's the case to reproduce?

**Comment by val-o** [comment]
Here a [sandbox](https://codesandbox.io/s/elastic-panini-dbpb6?file=/src/App.tsx). Although errors object itself are not even getting clear, not sure what might be a problem

**Comment by val-o** [comment]
Ah, I noticed if I move button which clears errors, the thing I describing in issue reproduces, i.e. errors object becomes empty but formState is still invalid

**Comment by bluebill1049** [comment]
Thanks for the CSB, sorry this is expected behavior. we can't reset isValid to true, since the input could still contain errors, `clearErrors` is only clear the errors in the `formState`, doesn't means the input is valid.

**Comment by val-o** [comment]
Ah, I see, thanks for the explanation. But it's interesting why errors object is not being cleared in the sandbox example, when the button is inside a <form>

**Comment by bluebill1049** [comment]
what do you mean? how to reproduce?

**Comment by bluebill1049** [comment]
<button onClick={() => clearErrors()}>Clear</button>
missing type button
