### ISSUE TITLE
errors object from useFormContext doesn't seem to update properly

### ISSUE THREAD

**Issue by changyeamoon** [react-hook-form/react-hook-form#2893]
**Describe the bug**
I'm not sure if this is intended ✨ 

I'm trying to use the `errors` object from the FormProvider/Context. I want to use it to update a global state outside of the FormProvider. So I want to use the 'errors' object as a dependency in my `useEffect`. However if doesn't look like the errors object is changing? or it is but not causing a reaction

**To Reproduce**

1. Start typing in input
2. Then delete all input to trigger onChange Validation
3. See Error state NOT change to `Error: true`

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-validation-onchange-errors-update-88zd8?file=/src/index.js

**Expected behavior**
The errors object from useFormContext should update and trigger re-renders

**Screenshots**
the CSB should be enough

**Desktop (please complete the following information):**

- OS: MAC IOS
- Browser chrome
- Version 84.0.4147.135 (Official Build) (64-bit)

**Comment by bluebill1049** [comment]
try to use `FormState` as the dep.

**Comment by changyeamoon** [comment]
doi, thanks!

**Comment by SatoAV** [comment]
> Thanks for the issue report, try to use FormState as the dep. errors just an alias inside formState.

I encountered a similar problem, in that `errors` object seems to be mutated and not re-created, when new errors appear, so it doesn't trigger re-render on my component.

According to typings, `formState` doesn't have `errors` field 🤔

**Comment by bluebill1049** [comment]
> > Thanks for the issue report, try to use FormState as the dep. errors just an alias inside formState.
> 
> I encountered a similar problem, in that `errors` object seems to be mutated and not re-created, when new errors appear, so it doesn't trigger re-render on my component.
> 
> According to typings, `formState` doesn't have `errors` field 🤔

@SatoAV it's part of the formState now. take a look the changelog.

**Comment by vzaidman** [comment]
I think it still persists in the new hook:  #3455

**Comment by mackankowski** [comment]
Hi all,

@bluebill1049 can you explain why `formState.errors` keeps input errors and `errors` doesn't have them anymore? I'm not sure what the `errors` object is about right now in v6...

**Comment by bluebill1049** [comment]
> @bluebill1049 can you explain why `formState.errors` keeps input errors and `errors` doesn't have them anymore? I'm not sure what the `errors` object is about right now in v6...

are you sure? do you have a codesandbox?

**Comment by mackankowski** [comment]
@bluebill1049 hi once again... I've noticed some difference between v5 and v6 that when I call `await trigger()` in an async function, in next line `errors` object is empty (I can only catch the updated `errors` in `useEffect` which is not too satisfying for me`. And again: I'm not able to reproduce it black box (where it just works fine like here: https://codesandbox.io/s/react-hook-form-v6-seterror-forked-3qdm0?file=/src/index.jsx), but in my current application (which worked fine for with v5) that issues appear. I can only add that together with `await trigger` (line by line), I have other async function with custom validation using `setErrors`, as well I'm using array form too. Let me try to investigate it more but if you have other tips, then let me know. I believe it's hard without code samples, but they just work fine independently. Thanks!

**Comment by bluebill1049** [comment]
hey @mackankowski i think this is what you after: https://codesandbox.io/s/react-hook-form-v6-seterror-forked-pohir?file=/src/index.jsx

**Comment by mackankowski** [comment]
> hey @mackankowski i think this is what you after: https://codesandbox.io/s/react-hook-form-v6-seterror-forked-pohir?file=/src/index.jsx

Hi Bill @bluebill1049, I'm happy to say that I replaced `errors` with `formState.errors` in my application (inline, without useEffect callbacks) and everything works just fine! Can you explain shortly, what the differences between these 2 objects? `errors` has a kind of delayed/outdated state, so without `useEffect` it doesn't seem to behave as expected. Here is my example again: https://codesandbox.io/s/react-hook-form-v6-seterror-forked-3qdm0?file=/src/index.jsx

Thank you for your great support and work!

**Comment by dwiyatci** [comment]
> doi, thanks! that's what I thought... when i used `formState` locally it was causing endless re-renders. I can't seem to duplicate it in CSB. ill lyk again when I can <3 (likely not related to the library)

@bluebill1049 I encountered pretty much the same issue as @changyeamoon today. Here is my snippet:

```js
let prevFormState;

function MyForm(props) {
  const { onErrorsChange } = props;

  const { formState, errors } = useForm(...);
  
  console.log(prevFormState === formState); // always false.
  prevFormState = formState;

  useEffect(
    () => {
      onErrorsChange(errors);
    },
    /**
     * Note that using `formState` as the dep will cause endless re-render somehow.
     * @see https://github.com/react-hook-form/react-hook-form/issues/2893#issuecomment-691585687
     */
    // [formState]
    [JSON.stringify(errors)]
  );

  // ...
}
```

As you can see, there, I've gotta resort myself using `JSON.stringify(errors)` to avoid infinite re-render. Furthermore, I also noticed that the `formState` seems to be always created as a new object (reference) across renders, which could be the cause of this endless re-render of the component in question. Do you have any explanation for this? 🙏

**Comment by bluebill1049** [comment]
> formState

we do a batch update on `formState`, instead of every single piece of state, that's why you should consider pushing `formState` as dep, otherwise, you will need another custom hook `useDeepComapre`, i believe Kent has built that.

**Comment by dwiyatci** [comment]
Yea, I've also researched that custom hook from Kent as an alternative of my `JSON.stringify` workaround. So this is expected to always get `formState` reference changed every render update, right?

My use case is actually to show some kind of error banner in the parent component every time we've got some form errors. That is why I only need to check whether the form errors got some changes.

**Comment by dwiyatci** [comment]
The more interesting finding is that when I stringified the `formState`, it would reach a "stable" point:

```javascript
console.log(prevStringifiedFormState === JSON.stringify(formState)); // will be true at some point.
prevStringifiedFormState = JSON.stringify(formState);
```

So I'm still wondering how can the reference of this `formState` always changes although the contents don't really change? @bluebill1049

**Comment by bluebill1049** [comment]
> The more interesting finding is that when I stringified the `formState`, it would reach a "stable" point:
> 
> ```js
> console.log(prevStringifiedFormState === JSON.stringify(formState)); // will be true at some point.
> prevStringifiedFormState = JSON.stringify(formState);
> ```
> 
> So I'm still wondering how can the reference of this `formState` always changes although the contents don't really change? @bluebill1049

no, it doesn't and shouldn't change each re-render.

**Comment by dwiyatci** [comment]
Ok, I'll try to isolate my issue and try to reproduce it on CSB then. If I didn't come back here, then I couldn't repro it. 😁 Thank youu!!

**Comment by dwiyatci** [comment]
@bluebill1049 @changyeamoon ^created a new issue for the endless re-render just now, managed to repro it on CSB :)
