### ISSUE TITLE
Skip Form Validation

### ISSUE THREAD

**Issue by OmriAroesti** [react-hook-form/react-hook-form#2896]
I have a use case in which several 'submit' buttons on a form do different things, such as resetting user password or deleting the user. 

I'd like an option to use the `handleSubmit` functionality (such as for disabling the form fields, and indicating submission), but skip the validation. 

Right now the way to do this is to handle the same submit logic on the `onInvalid` callback. While it does work, I'm considering how an additional parameter to the `handleSubmit` function to skip the validation process entirely would be helpful. 

Alternatively, Making the second parameter an options object with -

```ts
{
  onInvalid: SubmitErrorHandler<TFieldValues>,
  skipValidation: boolean
}
```

It can still maintain backwards compatibility by checking the type of the parameter and calling it if it is a function (onInvalid).

Please let me know what you think.

**Comment by bluebill1049** [comment]
current options

- `resolver`
-  `register` with validate function and keep an external state
