### ISSUE TITLE
🎉 Discord channel

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#2898]
I have just set up a discord channel, we can all discuss and help each other there.

https://discord.com/channels/754891658327359538/754891658327359541

**Comment by orblazer** [comment]
Hello,
Could you add an invitation link ? This link doesn't work if we are not on the server.

Thanks.

**Comment by bluebill1049** [comment]
Thanks @orblazer for the note: https://discord.gg/hU6c4X

**Comment by neighborhood999** [comment]
> Thanks @orblazer for the note: [discord.gg/hU6c4X](https://discord.gg/hU6c4X)

Invite link out of date.😭

**Comment by bluebill1049** [comment]
i am so noob with discord: https://discord.gg/tMsTW9m

**Comment by gsharathgoud** [comment]
Hello,
Could you please send discord invite link? It's out of date again.

**Comment by bluebill1049** [comment]
sorry again @gsharathgoud it's permanent now: https://discord.com/invite/yYv7GZ8
