### ISSUE TITLE
Add validation value in error object

### ISSUE THREAD

**Issue by orblazer** [react-hook-form/react-hook-form#2903]
**Is your feature request related to a problem? Please describe.**
If we want add default message for default rules `min`, `max`, `minLength` and `maxLength`, we can't access to the validation value. So the fallback message can't be custom like that :
> This field can't except **10** characters

**Describe the solution you'd like**
Add an field `value` on the error in addition to `type`, `message` and `ref`. 

**Describe alternatives you've considered**
Currently for make that i need call an function like `maxLength(10)` for return the value and the message.
```ts
export function maxLength (value: number): ValidationValueMessage<number> {
  return {
    value,
    message: `This field can't except ${value} characters`
  }
}
```

**Comment by bluebill1049** [comment]
Thanks for the feature request, as you would know everything comes with a cost in the lib. weather perf or package size, i would suggest for an alternative:

```
  validate: () => ({
    value,
    message: `This field can't except ${getValues().test} characters`
  })
```

certainly with your suggestion is an easier approach for scenarios like above but at the same time, it grows API, more things to document, more code inside the lib.

**Comment by orblazer** [comment]
OK, i understand the reason and after look the complexity i think is not an big feat.
For me we just need add an field like `value` here https://github.com/react-hook-form/react-hook-form/blob/5bf19cd79aacb74cff56f34937fb743f15b12668/src/logic/validateField.ts#L67 ans for the other reason i think just pass `null`.
