### ISSUE TITLE
Optionally trigger onChange event when setting value through ref

### ISSUE THREAD

**Issue by olup** [react-hook-form/react-hook-form#291]
I read a couple of this repo issue but I can't quite find my use case - I can't quite know if I am asking a stupid question or if it's a feature that doesn't exists.

I have a special input that has some cosmetic changes depending on the value : it's a material-ui-like input with schrinking placeholder. the ref is forwarded to the real input inside.

The input can be controlled or not, but even when not, we rely on a local state that listen to the onChange function of the input to determine if there is a value or not in the field.

Now, using this awesome library, and trying to use either `setValue` of some default values for the form, my inputs are properly changed through REF but the placeholder won't schrink as changing the input value is not reflected on the styled pseudo input's state.

My question is : in this case, do we have a way to trigger the `onChange` event when the library touches the input value ? Is there a workaround or a good practice to address this ?

Cheers, and thanks a lot for the great work.

**Comment by bluebill1049** [comment]
Any chance you can supply a codesandbox for the issue?

**Comment by olup** [comment]
It's going to be difficult. I'll try later on today.

However it boils down to how can the state of my functional component (`MaterialInput`) track the value of it's internal (real) input when the `form-hook` lib is updating it's value throught REF.

This is as much a React general interrogation than one for this libraey.

React answer would be : trigger manually the `onChange` event every time you update the input's ref's value so that react would be notified of the value change.

**Comment by bluebill1049** [comment]
React hook form focus on uncontrolled component as you would probably know. But if u need to trigger setState is also possible via ‘watch’

Your component can have a prop like value=“watch(‘value’)”

**Comment by bluebill1049** [comment]
I am on a bus sorry reply with code is difficult :( hope my above answer make sense

**Comment by olup** [comment]
It's perfect, and I understand very well your answer. In the case you mention, should I then not `register()` the input's ref, but use `onChange` with `setValue()` ?

**Comment by bluebill1049** [comment]
@olup I couldn’t see ur code, but I think u most likely need a custom ‘register’ with validation rules and using setValue. Note u can even trigger validation with set value as well by pass third argument as true. :p

**Comment by bluebill1049** [comment]
Oh u still need register your input but probably don’t need the ref 

U can do that during useEffect :)

**Comment by olup** [comment]
That's what I thought. However performance seems too bad that way. I am trying to set the initial input differently or to listen to value change on the html input by registering to an event.

**Comment by bluebill1049** [comment]
What do u mean performance is bad? Do u mean it’s becoming a controlled component?

**Comment by olup** [comment]
Yes, it is becoming a controlled element, but that's the goal. But in my case the controlled element is not performing that well. Quick type is okay but keeping key down lags a lot. So, as I just need this feature to pre-populate the form for now, I am trying to use an `initialValue` implementation. However, I am still daydreaming about a clean implementation, just registering the form and passing initial datas, and have my functionnal component check input's value when it changes.

**Comment by bluebill1049** [comment]
again it's hard to judge without seeing your code :) but I think idealy you just want an initial value (doing your animation) then let react hook form to collect the value for submit

**Comment by olup** [comment]
Ideally, the library would have an option to trigger the `change` or `input` event when it manipulates the input - what do you think ?

**Comment by bluebill1049** [comment]
I don't think that is a good idea.

**Comment by bluebill1049** [comment]
but I am curious to know the reason behind.

**Comment by olup** [comment]
I was just thinking of those cases when you indeed have some logic that needs to know about the input being changed. But actually it can be achieved equally by using `watch` and `setValue`, and it makes it clearer so my proposition is probably not a good idea.

**Comment by bluebill1049** [comment]
thanks for understanding @olup One of my primary goals is DX, I don't want to introduce complicated API to us, but I am glad you understand :) happy coding
