### ISSUE TITLE
useFieldArray: remove not working, in release only

### ISSUE THREAD

**Issue by Vi-dot** [react-hook-form/react-hook-form#2914]
Hello,

**Describe the bug**
With useFieldArray hook, remove function works fine in Debug mode, but not in Release mode.
In Release mode, remove(one_index) function removes all items appended, but keep items from defaultValues.

**Codesandbox link**
Code example for React Web, but we have this bug with React Native.
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-zrfty?file=/src/index.js

**Expected behavior**
remove(one_index) should remove only one item

**Screenshots**
in Release (not ok)
![release demo gif](https://gist.githubusercontent.com/Vi-dot/bc5223fe3d461771630fc2b878ca4404/raw/9eb37318f578502e096fc930fe5f980d1fb9bdc8/release.gif)
in Debug (ok)
![debug demo gif](https://gist.githubusercontent.com/Vi-dot/bc5223fe3d461771630fc2b878ca4404/raw/a1cb29cc44647e88624d2794666040a552d55767/debug.gif)

**Smartphone:**
- Device: iPhone11 Simulator
- OS: iOS 13.7

**Dependencies:**
- react 16.13.1
- react-native 0.63.2
- react-hook-form 6.8.2

Thanks

**Comment by Vi-dot** [comment]
I investigated a bit more:
This bug doesn't happen when there isn't defaultValues for the field array.

**Comment by bluebill1049** [comment]
you need to provide a codesandbox that reproduces the issue, otherwise, it's a maze for me to investigate. 

- reproduce the issue in a prod build (not your entire project but the part causing the issue)
- create a CSB with the reproduced code above

**Comment by Vi-dot** [comment]
Do you mean this codesandbox isn't enough good ?
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-zrfty?file=/src/index.js

I made an other one for React Native there:
https://codesandbox.io/s/objective-sun-iv7kc?file=/src/App.tsx

**Comment by bluebill1049** [comment]
> I made an other one for React Native there:
> https://codesandbox.io/s/objective-sun-iv7kc?file=/src/App.tsx

Thanks, @Vi-dot, is this one having an issue when you used the prod version of hook form?

**Comment by Vi-dot** [comment]
@bluebill1049 

You can test with this code, I tested it with both schemes: Debug and Release and it reproduces the bug only in Release :
https://codesandbox.io/s/objective-sun-iv7kc?file=/src/App.tsx

The bug appears in Release only when I put line 44
```typescript
register({ name: "tags" });
```

**Comment by bluebill1049** [comment]
> ```ts
> register({ name: "tags" });
> ```

why are you doing that? that's the issue then if that's your field array. it's not meant to be used that like, anyway try the following see if that resolve your problem.

```
useEffect(() => {
  register({ name: "tags" });
}, [register])
```

**Comment by Vi-dot** [comment]
I have the same issue with useEffect arround registers.
Moreover in fact in my original code I was using register only inside useEffect depending on register.

**Comment by bluebill1049** [comment]
honestly, I don't think you should use useFieldArray for your usage. I don't even see any inputs in your screenshot.

**Comment by Vi-dot** [comment]
I know my use case is border line. But even I don't have input, it should work the same way in Release or Debug..

If we put useEffect in the codesandbox, we can see the bug now:
https://codesandbox.io/s/objective-sun-iv7kc?file=/src/App.tsx

**Comment by bluebill1049** [comment]
> I know my use case is border line. But even I don't have input, it should work the same way in Release or Debug..

no, it's not even the borderline. it's not the **right** or **supported** usage. `useFieldArray` is made for uncontrolled `inputs`, there is not a single input in your screenshot, also in terms of prod or dev build. it's the same code, you can look the source it's open sourced.

the last thing i can offer here is to try to set `shouldUnregister` to `false`, again i wouldn't recommend to use this custom hook for what you try to achieve.
