### ISSUE TITLE
Hidden inputs reset to initial value on submit

### ISSUE THREAD

**Issue by mattboldt** [react-hook-form/react-hook-form#2917]
**Describe the bug**
When registering a hidden input via `ref={register}` and setting its value via `setValue`, the field is reset to its initial value `onSubmit`. However, when using `<Controller as={<input />} type="hidden" control={control} />`, the input's value persists.

Somewhat related thread: https://github.com/react-hook-form/react-hook-form/issues/284

**To Reproduce**

1. Go to demo page and see console logs for the current values
2. Click submit
3. See the 1st "brokenInput" value reset to the default

**Codesandbox link (Required)**
https://codesandbox.io/s/ecstatic-satoshi-420w3?file=/src/App.js

**Expected behavior**
Registered hidden inputs should persist their value on submit

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: `6.8.2`

**Comment by bluebill1049** [comment]
looks like this is not a bug with hook form, react cache the default value for hidden input for some reason:

https://codesandbox.io/s/misty-sea-41ko0?file=/src/App.js

so looks like you need to skip the defaultValue at hidden input.

**Comment by bluebill1049** [comment]
when there is a `defaultValue` for hidden input, the value persists even after updating.

<img width="445" alt="Screen Shot 2020-09-16 at 10 17 06 am" src="https://user-images.githubusercontent.com/10513364/93277685-c8772d80-f805-11ea-9f7c-959c7d4ac1e6.png">

**Comment by bluebill1049** [comment]
nvm, found solution.

**Comment by mattboldt** [comment]
🤔   it looks like it does the same thing if it has a `value` attribute too, though?
