### ISSUE TITLE
A way to escape sensitive characters in name?

### ISSUE THREAD

**Issue by colemars** [react-hook-form/react-hook-form#2921]
**Is your feature request related to a problem? Please describe.**
When communicating with Arango/Mongo it's convenient to directly expose queryable fields as they get passed to the db. e.g. `exampleArray[].id`. For further convenience it's nice to map query params directly to input fields. However, `exampleArray[].id` conflicts with `react-hook-form` nesting behavior. 

**Describe the solution you'd like**
A no brainer character escaping solution. 

`nested[exampleArray\[].\id][value]` becomes `nested: { 'exampleArray[].id': value }`

**Describe alternatives you've considered**
The alternative is special handling of the offending fields. Not hugely inconvenient but breaks up the pattern.

**Comment by layonthebeech** [comment]
DId you find a solution to this @colemars ?
