### ISSUE TITLE
Typescript, FieldError as array if FormInputs field is array

### ISSUE THREAD

**Issue by ptboyer** [react-hook-form/react-hook-form#2922]
**Describe the bug**
A Typescript error occurs if you have a form input field type as an array (e.g. `myArrayValue: string[]`) and attempt to read i.e. `message` from the error object of that form input field (e.g. `errors.myArrayValue?.message`).

The type of `errors.myArrayValue` is `(FieldError | undefined)[]` instead of `FieldError | undefined`, where the array potentially arises from an incorrectly inferred casting bug by using `FieldValues` to infer the fields available for the `errors` object.

I suspect it has something to do with [DeepMap used here](https://github.com/react-hook-form/react-hook-form/blob/master/src/types/errors.ts#L30) for typing `FieldErrors`.

![image](https://user-images.githubusercontent.com/8391902/93295153-c3c76f00-f82f-11ea-866d-4a7d3437578d.png)

**To Reproduce**

1. Go to [Codesandbox /src/index.tsx](https://codesandbox.io/s/react-hook-form-useform-template-forked-qdyly?file=/src/index.tsx)
2. In "/src/index.tsx"
3. See error on line `23` demonstrating type error as described above.

**Codesandbox link (Required)**
[Codesandbox /src/index.tsx](https://codesandbox.io/s/react-hook-form-useform-template-forked-qdyly?file=/src/index.tsx)

**Expected behavior**
The `errors` object MUST be agnostic of the field types used from `FieldValues` when creating `FieldErrors` so that all values in `errors` are ALWAYS of a `FieldError | undefined` type, and NEVER `(FieldError | undefined)[]` even if the type of the field that the error is representing is an array `[]`.

**Desktop (please complete the following information):**

- OS: MacOS 10.14.5
- Browser: Chrome v85

**Additional context**

- react-hook-form@6.8.2

**Comment by bluebill1049** [comment]
Thanks for the issue. please check the doc: https://react-hook-form.com/ts#NestedValue

**Comment by ptboyer** [comment]
@bluebill1049 Far out, I had no idea there was a TS section to the API docs, or even what to search for!

Thank you for the direction! :)

**Comment by bluebill1049** [comment]
> @bluebill1049 Far out, I had no idea there was a TS section to the API docs, or even what to search for!
> 
> Thank you for the direction! :)

no worries, mate.

**Comment by revskill10** [comment]
@bluebill1049 The docs for NestedValue in v6 is broken. Could u fix it for v6 ?

**Comment by bluebill1049** [comment]
> @bluebill1049 The docs for NestedValue in v6 is broken. Could u fix it for v6 ?

Sure, thanks. 👍
