### ISSUE TITLE
setError types are too strict

### ISSUE THREAD

**Issue by bc-jaka** [react-hook-form/react-hook-form#2925]
**Describe the bug**
Using `setError` from the `useForm` hook, the types are too strict if you have a simple flat `TFieldValues` structure.

**To Reproduce**

1. Define a simple flat form structure
```ts
type FormValues = {
  foo: string;
  bar: string;
}
```
2. Try to call `setError` with a key which is not in `FormValues`
```ts
const qux: string = 'qux';
setError(qux);
```
3. See error in Editor
"Argument of type 'string' is not assignable to parameter of type '"foo" | "bar"'

**Codesandbox link (Required)**
[Sandbox](https://codesandbox.io/s/react-hook-form-useform-template-forked-2vmc6?file=/src/index.tsx)

**Expected behavior**
I was expecting to be able to add errors to the form that does not have an associated input, as per bullet 2) in the documentation:
https://react-hook-form.com/api#setError
> Allows you to set an error that is not associated with an input field that will be persisted until it is manually cleared with clearError.

**Screenshots**
![image](https://user-images.githubusercontent.com/59699240/93308733-ebeca900-f802-11ea-99fe-3c7ed25d3878.png)

**Additional context**
If you use a nested `FormValues` structure this isn't a problem.

**Comment by bluebill1049** [comment]
This is is working as expected for `setError` to associated with the input value type.

**Comment by bc-jaka** [comment]
But the documentation clearly states otherwise. And I'm allowed to do it if my `FormValues` looked like this instead.
```ts
type FormValues = {
  foo: string;
  bar: {
    qux: string;
  }
}
```

**Comment by bluebill1049** [comment]
> But the documentation clearly states otherwise. And I'm allowed to do it if my `FormValues` looked like this instead.
> 
> ```ts
> type FormValues = {
>   foo: string;
>   bar: {
>     qux: string;
>   }
> }
> ```

where? happy to get it updated.

**Comment by bluebill1049** [comment]
> ```ts
> type FormValues = {
>   foo: string;
>   bar: {
>     qux: string;
>   }
> }
> ```

off course you are allowed to declare type like that.

**Comment by bluebill1049** [comment]
you may find this useful as well: https://react-hook-form.com/ts#NestedValue

**Comment by bc-jaka** [comment]
![image](https://user-images.githubusercontent.com/59699240/93310779-7e8e4780-f805-11ea-89b8-e3f16d310ac3.png)

Bullet 2) states that I should be able to set an error which is not associated with an input field

**Comment by bluebill1049** [comment]
> ![image](https://user-images.githubusercontent.com/59699240/93310779-7e8e4780-f805-11ea-89b8-e3f16d310ac3.png)
> 
> Bullet 2) states that I should be able to set an error which is not associated with an input field

Thanks, will add more info on the doc, in the meantime take a look at this blog post.

**Comment by bluebill1049** [comment]
<img width="923" alt="Screen Shot 2020-09-16 at 6 55 27 pm" src="https://user-images.githubusercontent.com/10513364/93315277-31829380-f84e-11ea-817f-96046f4c5f0e.png">

the same link have been posted to the doc.

**Comment by buchanaf** [comment]
@bluebill1049, sorry to resurrect this but is there a recipe for setting an error on a form that isn't tied to a field -- like a 500? Or, in the case of typescript, is it just casting the `name` in `setError` to `any`

**Comment by bluebill1049** [comment]
@buchanaf please refer to this comment: https://github.com/react-hook-form/react-hook-form/pull/4986#issuecomment-833402451
