### ISSUE TITLE
Add message to register({ validate: ... })

### ISSUE THREAD

**Issue by manuelnas** [react-hook-form/react-hook-form#293]
**Is your feature request related to a problem? Please describe.**
I currently can't set a message when validating the value using the `validate` method.

**Describe the solution you'd like**
Be able to add a `message` to `validate` like I can do with `minLength` for example.

I have tried different methods, but couldn't get this message to show up in the errors object.

Example:
When the `minLength` validation is tripped it will return message in the error object, but the same is not true for the `validate` validation (the validation does trigger an error object, but it doesn't have the message). 
```
<input
  inputRef={register({
    required: 'Password verification is required',
    minLength: { value: 6, message: 'Password must be at least 6 characters long' },
    validate: { value: value => value === watch('password'), message: "The password fields don't match" }
  })}
/>
```

**Comment by stramel** [comment]
`validate` doesn't take an object. If you want it to supply a custom message, you can just return a message from the function. 

```
<input
  inputRef={register({
    required: 'Password verification is required',
    minLength: { value: 6, message: 'Password must be at least 6 characters long' },
    validate: value => value !== watch('password') ? "The password fields don't match" : undefined
  })}
/>
```
