### ISSUE TITLE
Nested Field Array - useWatch and watch inconsistency

### ISSUE THREAD

**Issue by MatiasCiccone** [react-hook-form/react-hook-form#2931]
**Describe the bug**
When using `useWatch` with nested field arrays and adding a new field in the top-level field array (not nested) at some point the returned value is `undefined` and is not updated, but when you use `watch` it does.

**To Reproduce**

1. Check the printed values in the console
2. Click on the 'add array field' button
3. Check the printed values in the console again
4. Notice that at some point both `watch` and `useWatch` returned `undefined` (which makes sense), but later the `watch` value is updated whereas the `useWatch` value is not

**Codesandbox link (Required)**
https://codesandbox.io/s/nested-field-array-usewatch-and-watch-inconsistency-hy0wn

**Expected behavior**
`watch` and `useWatch` output should be consistent

**Additional context**
With the steps to reproduce the behavior, I noticed the `📋 watched fields: ... are not found.` warnings. But I tested the same behavior on the top field array (not nested) and I see the same warnings but the values are never `undefined`. To try this just uncomment lines 95-103 and comment lines 151-161 (for cleaner logs) and try appending with any button. You'll see that the warnings are not 100% consistent with the returned values. Maybe this is a different issue.

**Comment by bluebill1049** [comment]
Thanks @MatiasCiccone I will get back to you on this one. 👍

**Comment by bluebill1049** [comment]
This actually expected behavior, because form input state lives in the input itself, `watch`/`useWatch` will always be one render behind during input mount. It then works fine when the user interacts with the inputs itself. for `watch` we are actually triggering an extra re-render to make sure users get the correct watched fields array. 

**solutions**
always back up `watch`/`useWatch` with a field initial value before the render phase. I will update the doc accordingly to reflect this as well.

```
watch('test', fields)
useWatch({ name: 'test', defaultValue: field })
```

**Comment by bluebill1049** [comment]
<img width="915" alt="Screen Shot 2020-09-17 at 5 46 07 pm" src="https://user-images.githubusercontent.com/10513364/93436112-aec10d80-f90d-11ea-847d-76d87819dd67.png">
<img width="936" alt="Screen Shot 2020-09-17 at 5 46 23 pm" src="https://user-images.githubusercontent.com/10513364/93436128-b54f8500-f90d-11ea-89e2-10ee5dfaa7a0.png">
doc updated.

**Comment by dwiyatci** [comment]
Hi, I'm sorry to jump in. But I believe I encountered similar issue when adding/removing item using `useFieldArray`. 

@bluebill1049 I've followed your suggestion above to add default values, but it didn't seem to make the warnings go away. 😕 

```javascript
const xs = watch('xs', []);
// watched fields: xs are not found.

const foo = watch(`xs[${index}].foo`, '');
// watched fields: xs[1].foo are not found.
```

That said, it appears not to have functionality to the form UI though. Do you think I can safely ignore these warnings? Or perhaps you have any other suggestion?

**Comment by MatiasCiccone** [comment]
Thanks @bluebill1049

**Comment by bluebill1049** [comment]
> Hi, I'm sorry to jump in. But I believe I encountered similar issue when adding/removing item using `useFieldArray`.
> 
> @bluebill1049 I've followed your suggestion above to add default values, but it didn't seem to make the warnings go away. 😕
> 
> ```js
> const xs = watch('xs', []);
> // watched fields: xs are not found.
> 
> const foo = watch(`xs[${index}].foo`, '');
> // watched fields: xs[0].foo are not found.
> ```
> 
> That said, it appears not to affect functionality to the form UI though. Do you think I can safely ignore these warnings? Or perhaps you have any other suggestion?

What's the warning? can you reproduce that in a codesandbox?

**Comment by dwiyatci** [comment]
@bluebill1049 The "`📋 watched fields: ... are not found.`" warnings. 

And yes, I can repro it. Here I simply forked the CSB from Matias:
https://codesandbox.io/s/nested-field-array-usewatch-and-watch-inconsistency-forked-5u3u6?file=/src/App.js

Please click on "add array field" or "add nested array field" or "remove", and then you'll see the warnings in the console even though I've put default values for both `watch` and `useWatch` - I've got pretty much similar thing in my app.

**Comment by bluebill1049** [comment]
I think i know the issue, hmmm may need to rethink those warning messages...

**Comment by bluebill1049** [comment]
I am reverting back that change. release a patch now.

**Comment by oliseh6123** [comment]
HI, Guys. Hi @bluebill1049 blue  i have an issue after trying to enhance on your nested Field Array. I am using useWatch to try get the total sum of the nested array field. here is the sandbox  https://codesandbox.io/s/quiet-forest-pmykg?file=/src/fieldArray.jsx 

I want to indulge your help.  i am trying to watch this name={`test[${nestIndex}].nestedArray[${k}].field1`} from in side the first array form but i am having a repeated total sum.

**Comment by oliseh6123** [comment]
@bluebill1049  i don't know if my explanation is clear but you can take a look at my sandbox form to make it clear

**Comment by bluebill1049** [comment]
@oliseh6123 when you are watching a field array 

`useWatch({ control, name: "test" }, fields);` try to give it a fallback value (defaultValues)

<img width="855" alt="Screen Shot 2020-09-22 at 9 37 10 pm" src="https://user-images.githubusercontent.com/10513364/93877428-c76d6100-fd1b-11ea-97ba-cb57f0fff8a6.png">

**Comment by Nitheeshskumar** [comment]
@bluebill1049 When i have isolated the append button and used useWatch to check the value in last input field.If there is value in last field, show the appemd button so that i can add another field, so as to prevent adding another field without giving value to previous field. I have given the default value to '' (empty string). So basically what happens is initially the button is not visible. After i enter a value, the button becomes visible. When i click the append button, the new field is rendered but the button stays there. The useWatch is still listening to previous field. when i interact with the input like focus and blur, the button hides. The isolated button is receiving updated props, but the usewatch is not getting updated. Any workarounds?
