### ISSUE TITLE
`TypeError: Cannot read property 'split' of undefined` in production build after updating to version 6

### ISSUE THREAD

**Issue by hayk94** [react-hook-form/react-hook-form#2932]
**Describe the bug**
Getting `TypeError: Cannot read property 'split' of undefined` in production build after updating to version 6. In the development build everything seems to work fine though.

**To Reproduce**
Just look in your controller template. The problem seems to be with the controller component.

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-controller-template-yu0z5

**Expected behavior**
The form to render properly

**Screenshots**

Here is my component with the same problem
![image](https://user-images.githubusercontent.com/9801183/93372716-53d3db80-f865-11ea-872d-bda2368d5845.png)

**Desktop (please complete the following information):**

- OS: Windows 10 OS Version 1903 (Build 18362.1016)
- Browser: Chrome
- Version: 83.0.4103.61 (Official Build) (64-bit)

**Additional context**
Additionally even in version 4, there was a warning for my component that it's missing "name" prop. Even though as you can see in the screenshot it has. Despite the warning the component worked fine. It was filled with default value when provided, and provided it's value during submitting as well.
After updating to version 6 is when it breaks in production build. Also some additional warnings appear if the default value for it is undefined. So maybe these warnings are related to the main issue.

**Comment by MatiasCiccone** [comment]
@hayk94 in your sandbox example it will work with something like this. Remember that name is a required prop for Controller. https://react-hook-form.com/api/#Controller

```<form onSubmit={handleSubmit(onSubmit)}>
      <label>FirstName</label>

      <Controller
        name="FirstName"
        as={<input />}
        defaultValue="FirstName"
        control={control}
      />

      <label>LastName</label>
      <Controller
        name="LastName"
        as={<input />}
        defaultValue="LastName"
        control={control}
        rules={{ required: true, maxLength: 10 }}
      />
      {errors.LastName && <p>This field is required</p>}

      <input type="submit" />
    </form>
```

And regarding your real component, have you tried using render instead of as? Usually when as is not enough render gives you all that you need to work with controlled inputs.  Here you have some good examples https://codesandbox.io/s/react-hook-form-controller-079xx

**Comment by bluebill1049** [comment]
Thanks a lot, @MatiasCiccone for helping!

**Comment by bluebill1049** [comment]
have a look at the changelog for v5 to v6: https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md 👍
