### ISSUE TITLE
Controller doesn't forward all extra props

### ISSUE THREAD

**Issue by wereHamster** [react-hook-form/react-hook-form#2933]
**Describe the bug**

I was trying to pass `onBlur` to `<Controller>` in the hopes that it would forward it to the as=… component. But it overrides the `onBlur` prop without calling the original function.

**To Reproduce**

```
import { TextField } from "@material-ui/core";
<Controller name="test" as={TextField} onBlur={() => console.log("onBlur")} />
```

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-controller-template-onfocus-onblur-gfsc9?file=/src/index.js

**Expected behavior**

onFocus / onBlur are forwarded do the component.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS
- Browser [e.g. chrome, safari] chrome
- Version [e.g. 22] 85

**Comment by MatiasCiccone** [comment]
@wereHamster if you want to add an extra layer of logic to your input onBlur event you should do something like this https://codesandbox.io/s/react-hook-form-controller-template-onfocus-onblur-forked-mg348.
Regarding the onFocus prop for Controller the doc says: `This callback allows the custom hook to focus on the input when there is an error. This function is applicable for both React and React-Native components as long as they can be focused.`
So again, just add onFocus to your input inside your render function if you want to do something else onFocus when it doesn't come from an error (like submitting when one input is empty but is required)

**Comment by bluebill1049** [comment]
hey @wereHamster take a look the changelog with v6, `Controller` -> `render` props

https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md
