### ISSUE TITLE
Errors do not disappear when corrected for fields inside a composite value

### ISSUE THREAD

**Issue by NotWhatUHadInMind** [react-hook-form/react-hook-form#2938]
**Describe the bug**
I am trying to use a custom input, which returns a composite object as a value, and utilize it using the Controller component.
The value is set correctly, but I also have some yup validation rules for this object, and here comes the problem.

If this value object has at least two fields, and both fields have got validation errors, 
when I correct one of the fields I don't get the error immediately removed, only on the next change.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-composite-object-validation-0i50o

**To Reproduce**
Steps to reproduce the behavior (in the sandbox):

1. Press submit button (to get two errors for both User object fields)
2. Type one symbol into the First Name input
3. The error that the first name is required is still there!
4. Type second one, the error disappears

If you remove the second field (lastName) from the validation rules, 
so you don't have more than one error for the composite object fields anymore, 
the error finely disappears after the first input.

**Expected behavior**
Errors for nested object fields should disappear as soon as they are corrected.

**Additional context**
Tested on versions 6.5.3 and 6.8.2.

**Note**
I have looked into the source code of the library and found out, that the issue might be somewhere around the [isSameError](https://github.com/react-hook-form/react-hook-form/blob/master/src/utils/isSameError.ts) function, which is called from [shouldRenderBasedOnError](https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/shouldRenderBasedOnError.ts).
In the case of composite object value, it receives nested error object, but it does not seem that the isSameError function can handle that.
Example of isSameError arguments from one of my debugging sessions (when I corrected startTimeInMills field):
```
previousError: {
  "startTimeInMills": {
    "message": "Required",
    "type": "required"
  },
  "endTimeInMills": {
    "message": "Required",
    "type": "required"
  }
}

error: {
  "endTimeInMills": {
    "message": "Required",
    "type": "required"
  }
}
```
isSameError gives me true.

**Comment by bluebill1049** [comment]
great investigation @NotWhatUHadInMind. want to send a PR, if you think the issue is around isSameError, probably can just check the length will solve the problem.
