### ISSUE TITLE
incorrect watch warning 

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#2942]
@bluebill1049 The "`📋 watched fields: ... are not found.`" warnings. 

And yes, I can repro it. Here I simply forked the CSB from Matias:
https://codesandbox.io/s/nested-field-array-usewatch-and-watch-inconsistency-forked-5u3u6?file=/src/App.js

Please click on "add array field" or "add nested array field" or "remove", and then you'll see the warnings in the console even though I've put default values for both `watch` and `useWatch` - I've got pretty much similar thing in my app.

_Originally posted by @dwiyatci in https://github.com/react-hook-form/react-hook-form/issues/2931#issuecomment-694545677_

**Comment by bluebill1049** [comment]
This warning is reverted: https://github.com/react-hook-form/react-hook-form/commit/e3a877e0e9b51238d3fe621fa7bc634b2cda2eff

**Comment by dwiyatci** [comment]
@bluebill1049 Thanks for the quick patch. I just gave it a spin and works as expected as before. 🙇🏻‍♂️
