### ISSUE TITLE
Form reset resets dirty fields when added to omitResetState

### ISSUE THREAD

**Issue by PeterKerins** [react-hook-form/react-hook-form#2945]
**Describe the bug**
When resetting a form that has been given {dirtyFields: true} in the omitResetState config, dirty fields are reset.

**To Reproduce**
1. Enter values in form
2. Reset Form

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-reset-v6-forked-tdg92?file=/src/index.js

**Expected behavior**
Dirty fields should not be reset

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: macOs 10.15.6
- Browser Chrome
- Version 85

**Additional context**

**Comment by bluebill1049** [comment]
<img width="1173" alt="Screen Shot 2020-09-19 at 10 15 40 am" src="https://user-images.githubusercontent.com/10513364/93654490-1340b180-fa61-11ea-9153-4ea202aecace.png">

it is not been reset.

**Comment by PeterKerins** [comment]
Sorry if I'm mistaken opening this, I'm looking to reset just the first object and not modify the rear of the form. how can I reset some values after an api response, but not all?

**Comment by bluebill1049** [comment]
```
reset({
   ...getValues(),
  // do here
})
```

**Comment by PeterKerins** [comment]
Misinterpreted the docs. That should would. Thanks a mil

**Comment by bluebill1049** [comment]
> Misinterpreted the docs. That should would. Thanks a mil

let me know how to improve it. 👍

**Comment by PeterKerins** [comment]
In my case I need to reset just a subset of the form, I.e. just the values a pass to the first object. I thought by setting dirty fields to true it would reset the values that had been modified that aren't in the first object. It's a field array I'm eventually trying to update, but I should be able to make it from there. Hook form has made it so much easier so thanks a million

**Comment by vinujan59** [comment]
Hi, `reset` with `omitResetState` is not working in `"react-hook-form": "6.15.8"` 

codesandbox - https://codesandbox.io/s/react-hook-form-reset-v6-forked-tdg92?file=/package.json
