### ISSUE TITLE
[useFieldArray] Form state (dirty) not changing as expected on user interaction (fieldArray + checkbox)

### ISSUE THREAD

**Issue by vilanelle** [react-hook-form/react-hook-form#2946]
A form with field array. After removing a field array field form state is `dirty`. However, after changing the checkbox twice, form state is not `dirty` anymore.

1. Go to sandbox: https://codesandbox.io/s/react-hook-form-usefieldarray-forked-pmbli?file=/src/index.js
2. Click 'Delete'
3. Click checkbox twice
4. Form state is no longer dirty.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-pmbli?file=/src/index.js

**Expected behavior**
Form state should remain dirty after it changed.

**Desktop (please complete the following information):**

- OS: Win
- Browser chrome

**Comment by bluebill1049** [comment]
Thank you @vilanelle for the bug report.

**Comment by bluebill1049** [comment]
fixed: https://github.com/react-hook-form/react-hook-form/commit/5ce607b7cbe777eb5d38429d23654cc83e0baab9

**Comment by vilanelle** [comment]
Thanks for the super-quick fix @bluebill1049! Will test in codebase asa new release comes out!
