### ISSUE TITLE
6.8.x: useFieldArray + reset with shouldUnregister = false

### ISSUE THREAD

**Issue by szymonlesisz** [react-hook-form/react-hook-form#2958]
**Describe the bug**
since version 6.8.0+ reset() doesn't update `fields` of `useFieldArray`
works with 6.7.2

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-forked-2evgb?file=/src/index.js

**Expected behavior**
`fields` of `useFieldArray` is empty regardless of `defaultValues` in `useForm`

**Comment by bluebill1049** [comment]
please fix the CSB.

**Comment by szymonlesisz** [comment]
what should i fix?

**Comment by bluebill1049** [comment]
@szymonlesisz nah, it's a valid bug. i thought CSB contains nothing, but that was the problem...

**Comment by bluebill1049** [comment]
Thanks @szymonlesisz for the bug report 🙏
