### ISSUE TITLE
6.8.x useFieldsArray + clearErrors not working

### ISSUE THREAD

**Issue by szymonlesisz** [react-hook-form/react-hook-form#2961]
**Describe the bug**
since 6.8.0 `clearErrors` called with array of fields stops working
works with 6.7.2

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-useform-template-forked-j4wqk?file=/src/index.js
2. Click on 'Step 1: fill error' button
3. Click on 'Step 2: reset error' button

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-forked-j4wqk?file=/src/index.js

**Expected behavior**
`field1` error should be cleared

**Comment by bluebill1049** [comment]
thanks again @szymonlesisz

**Comment by szymonlesisz** [comment]
Hi again, thanks for quick fixes yesterday :)
I've updated version to 6.8.4 and found out that this issue still got some side effects.
`clearErrors` doesn't remove `errors.nestedField.key` anymore but sets them as undefined instead.

I've updated my CSB, pls use the same steps as in description (step 1, step 2) but this time watch for console log.
https://codesandbox.io/s/react-hook-form-useform-template-forked-j4wqk?file=/src/index.js

Expected behaviour:
After "Step 2" `errors` object should be empty

![Screenshot 2020-09-22 at 10 32 23](https://user-images.githubusercontent.com/3435913/93860256-1933ce00-fcbf-11ea-8906-f1337b570e43.png)

**Comment by bluebill1049** [comment]
> Hi again, thanks for quick fixes yesterday :)
> I've updated version to 6.8.4 and found out that this issue still got some side effects.
> `clearErrors` doesn't remove `errors.nestedField.key` anymore but sets them as undefined instead.
> 
> I've updated my CSB, pls use the same steps as in description (step 1, step 2) but this time watch for console log.
> https://codesandbox.io/s/react-hook-form-useform-template-forked-j4wqk?file=/src/index.js
> 
> Expected behaviour:
> After "Step 2" `errors` object should be empty
> 
> ![Screenshot 2020-09-22 at 10 32 23](https://user-images.githubusercontent.com/3435913/93860256-1933ce00-fcbf-11ea-8906-f1337b570e43.png)

that's expected, for individual node we can only set the error to `undefined`, if you want to clear the whole array field error use the `key`.

**Comment by szymonlesisz** [comment]
I wrote unexpected because this is not how it works with 6.7.2
My "submit button" is enabled on condition `Object.keys(errors).length === 0` and this change kinda breaks it so i was assuming that this is a bug 

Does it mean that i need to filter `undefined` errors from every nested field from now on? or is there a better way to check "if there are no errors"?

**Comment by bluebill1049** [comment]
> I wrote unexpected because this is not how it works with 6.7.2
> My "submit button" is enabled on condition `Object.keys(errors).length === 0` and this change kinda breaks it so i was assuming that this is a bug
> 
> Does it mean that i need to filter `undefined` errors from every nested field from now on? or is there a better way to check "if there are no errors"?

- This was patched by a bug because we used to unset `errors` by `name`, which lead to this unexpected behaviour and hence this bug. 
- Iif aclear a object key, then yes we should clear the entire error object for that key, if only particular field, we can't assume the other fields in the object doesn't have error or has, hence set to `undefined1` is the easy and simplest solution. 
- why are you checking for errors length? shouldn't you relay on `isVaid`?

**Comment by szymonlesisz** [comment]
I've tried `formState.isValid` but it is set to `false` at this point (see my updated CSB)

**Comment by bluebill1049** [comment]
> I've tried `formState.isValid` but it is set to `false` at this point (see my updated CSB)

then that's a separate issue, we should fix then.

**Comment by szymonlesisz** [comment]
should i create another issue for that?

**Comment by bluebill1049** [comment]
> should i create another issue for that?

I think it should be a separate issue, yes plz.

**Comment by bluebill1049** [comment]
@szymonlesisz if you setValue and trigger the validation, it's working right? https://codesandbox.io/s/react-hook-form-useform-template-forked-j4wqk?file=/src/index.js

**Comment by szymonlesisz** [comment]
unfortunately no, `{ shouldValidate: true }` in "Step 2" doesn't affect on `formState.isValid` (it's still false)

**Comment by bluebill1049** [comment]
![Screen Shot 2020-09-22 at 7 29 24 pm](https://user-images.githubusercontent.com/10513364/93865624-ed8a0580-fd09-11ea-93be-83d30a8fcd99.png)

but you didn't set `shouldValidate`

**Comment by szymonlesisz** [comment]
but it is clearing `errors` object as expected tho :)

Edit: id didn't save CSB, now should be there

**Comment by bluebill1049** [comment]
I am afraid you probably have to, otherwise i am running cycle here with your issue and this one #2730.

**Comment by szymonlesisz** [comment]
hm, thats not a good news :)
any idea how should i clear fields to default state (empty) without triggering "required" error?

**Comment by bluebill1049** [comment]
> hm, thats not a good news :)
> any idea how should i clear fields to default state (empty) without triggering "required" error? and without calling "reset" ?

The difficult here:

```
test: {
  data: {
     error: undefined
  }
}
```

need to be stripped to 

```
{}
```

:(

**Comment by bluebill1049** [comment]
otherwise, I have to `clearErrors('test', { exact: false })` which will do an object unset rather set to `undefined` which is not great at the lib level.

**Comment by bluebill1049** [comment]
hmmm, i may try something.

**Comment by bluebill1049** [comment]
tried what's in mind and having no luck and rather complicate things up, i think you should rely on `isValid`, and consider to trigger validation, while i will still think about potential solutions.

**Comment by szymonlesisz** [comment]
thank you very much for your time!
i will relay on `isValid` from now on but i did notice that you closed my issue https://github.com/react-hook-form/react-hook-form/issues/2972 as "not valid"

**Comment by bluebill1049** [comment]
> thank you very much for your time!
> i will relay on `isValid` from now on but i did notice that you closed my issue #2972 as "not valid" while it's valid. `isValid` field has invalid value (false) :)

i thought it was not working because setValue didn't have `shouldValidate`? if that's not the same, i will re-open.

**Comment by szymonlesisz** [comment]
yes, i've put it in to issue description
issue persist in both cases with or without `shouldValidate` 

using `shouldValidate` only affects how `errors` object looks like but does't affect `isValid` field

**Comment by bluebill1049** [comment]
oops...
