### ISSUE TITLE
[Feature Request] Dedicated `Controller` component for `React Native`

### ISSUE THREAD

**Issue by karlmarxlopez** [react-hook-form/react-hook-form#2963]
**Is your feature request related to a problem? Please describe.**
No. 
**Describe the solution you'd like**
Can we have a dedicated `Controller` component for `React Native` so that we can use the `as` prop like on the web? I'm thinking this can be imported via `import {Controller} from 'react-hook-form/native'`?

**Describe alternatives you've considered**
Another alternative is to auto-detect the current environment.

**Additional context**
Sample usage

```tsx
import React from 'react';
import {SafeAreaView} from 'react-native';
import {Input, Button} from 'react-native-elements';
import {Controller, useForm} from 'react-hook-form';

interface MyFormData {
  fullName: string;
  address: string;
}

const MyForm = () => {
  const {control, handleSubmit} = useForm<MyFormData>();

  const onSubmit = (data: MyFormData) => console.log(data);

  return (
    <SafeAreaView style={{flex: 1}}>
      <Controller
        as={Input}
        control={control}
        defaultValue=""
        label="Full Name"
        name="fullName"
        placeholder="John Doe"
      />
      <Controller
        as={Input}
        control={control}
        defaultValue=""
        label="Address"
        name="address"
        placeholder="321 Baker St."
      />
      <Button onPress={handleSubmit(onSubmit)} title="Submit" />
    </SafeAreaView>
  );
};

export default MyForm;


```

**Comment by bluebill1049** [comment]
please consider to use `render`, it's hard to predict the component props.

**Comment by karlmarxlopez** [comment]
@bluebill1049 What if providing the change listener prop to the `Controller`?

Something like this,
1. `changeListener` prop, accepts `string` prop key of the wrapped component.
```tsx
<Controller as={Input} control={control} changeListener="onChangeText"/>
```

1. `changeEvent` prop, accepts object.
```tsx
<Controller as={Input} control={control} changeEvent={{
	onChangeText: value => value,
}}/>
```

**Comment by bluebill1049** [comment]
That's what we had on v5: https://react-hook-form.com/v5/api doesn't work nicely :(

**Comment by bluebill1049** [comment]
Going to close this issue @karlmarxlopez , please consider to use `render` as we have moved on with named props from v5, trust me `render` props is better. 👍 feel free to follow up with question if you need help to get the render prop working.

**Comment by karlmarxlopez** [comment]
Thanks @bluebill1049 !
