### ISSUE TITLE
reset() only resets the first field even though defaultValues provided

### ISSUE THREAD

**Issue by dwiyatci** [react-hook-form/react-hook-form#2964]
**Describe the bug**
Calling `reset()` without argument only resets the first field even though `defaultValues` has been provided in `useForm()`.

**To Reproduce**

1. Click on 'Reset with values'.
2. Observe the "Last name" field.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-reset-v6-forked-4ppbq?file=/src/index.js

**Expected behavior**
Calling `reset()` without any args should fallback to `defaultValues` provided in the `useForm()`, i.e. "First name" and "Last name" fields should be reset to "bill" and "luo" respectively.

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.6
- Browser Chrome
- Version 85

**Comment by bluebill1049** [comment]
your codesandbox is using a beta version :)

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-reset-v6-forked-qpy10?file=/src/index.js try latest version and its fine.
