### ISSUE TITLE
getValues('fieldArray') doesn't seem to work inside of event handler

### ISSUE THREAD

**Issue by dwiyatci** [react-hook-form/react-hook-form#2969]
**Describe the bug**
When using `useFieldArray`, `getValues('fieldArray')` returns `undefined` inside of an event handler. But `getValues().fieldArray` returns the array though. 😅 

**To Reproduce**

1. Click on 'Append'.
2. See log in the console.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-erbwu?file=/src/index.js:1575-1702

**Expected behavior**
`getValues('fieldArray')` should returns the same thing as `getValues().fieldArray`.

**Comment by bluebill1049** [comment]
<img width="669" alt="Screen Shot 2020-09-22 at 6 38 04 pm" src="https://user-images.githubusercontent.com/10513364/93860658-c3811500-fd02-11ea-98a4-52ebda8f35b4.png">

that's not supported feature.

**Comment by dwiyatci** [comment]
Ahh okay, didn't know that it was expected. Thanks, as always, Bill! :))

**Comment by bluebill1049** [comment]
np.

**Comment by dwiyatci** [comment]
@bluebill1049 I'm sorry to come back to this issue again. But when I tried to `getValues()` in my app after `insert` and `remove`, it even returned `undefined` for the "fieldArray". Is this also intended?

Please go here again as I've updated the CSB, and click on "Insert at" and/or "Remove at":
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-erbwu?file=/src/index.js:2214-2341

**Comment by bluebill1049** [comment]
you probably want to use `watch` instead if you want to get the value of the entire field array

**Comment by dwiyatci** [comment]
@bluebill1049 Yes, actually I've been using `useWatch` in my child component under my field array construction. But it seems like there is a split-second discrepancy between the `watchedFieldArray` value and the `fieldArray` value itself after I insert and/or remove element to the the `fieldArray`. I've been inspecting this bug in my program since this morning because some variables in my child component depend on the `watchedFieldArray.length`. 😞

Here, I've updated the CSB again to further illustrate my problem:
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-erbwu?file=/src/Child.jsx:195-323

So I guess the question now is: should I use `fieldArray.length` from the parent or `watchedFieldArray.length`?

**Comment by bluebill1049** [comment]
> on now is: should I use `fieldAr`

sorry to hear that 🙏 

`fieldArray.length` is the right one, let me explain what's happening, with uncontrolled input, those form value states live inside the inptus, which the reason why you need `watch('fieldArray', fields)`, this goes to the same as watch need a defaultValue, otherwise it will return `undefined` when you try to watch input, because the input is not even rendered yet.

**Comment by dwiyatci** [comment]
I see. Thank you so much for this, at least I know now what's happening, roughly 😀

**Comment by bluebill1049** [comment]
no worries @dwiyatci see there is always going to be a gap if you don't provide defaultValue for watch, because 

-> start the function (gap)

-> render 

-> input (value ready, now they r subscribed)

<img width="869" alt="Screen Shot 2020-09-22 at 9 54 44 pm" src="https://user-images.githubusercontent.com/10513364/93878941-3ba90400-fd1e-11ea-98ba-fb77ba83b1a8.png">

**Comment by dwiyatci** [comment]
@bluebill1049 Yah, I've read that before. Thing is, I provided the complete `defaultValues`already in `useForm` for that certain `fieldArray` field. It should be the same as providing it in `watch` or `useWatch`, right? ButsStill, it didn't help to fill that "gap" during inserting/removing of an item (I've also double-checked that I filled all the default values for the item when inserting). Well, I guess I may well stick with `fieldArray.length` from the parent for now 😬

**Comment by bluebill1049** [comment]
> @bluebill1049 Yah, I've read that before. Thing is, I provided the complete `defaultValues`already in `useForm` for that certain `fieldArray` field. It should be the same as providing it in `watch` or `useWatch`, right? ButsStill, it didn't help to fill that "gap" during inserting/removing of an item (I've also double-checked that I filled all the default values for the item when inserting). Well, I guess I may well stick with `fieldArray.length` from the parent for now 😬

can you share a simple codesandbox around this? happy to investigate for a better solution.

**Comment by dwiyatci** [comment]
Sure! :) Would be glad to try to reconstruct this on CSB. I'll work on it sometime this week~

**Comment by dwiyatci** [comment]
@bluebill1049 Actually, you know what, Bill. I guess what I made in the previous CSB already manifests my issue very well. 😂 

Here is the updated CSB again:
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-erbwu?file=/src/Child.jsx:195-266

Please take notice on the followings:
- `defaultValues` is provided in `useForm()`.
- Default values (`firstName` and `lastName`) are provided for the new item when inserting.
- Try to insert/remove item. You can observe in the console during the first render, the length of `watchedFieldArray` is always 1, which I guess is the length of `test` array being passed as `defaultValues` to `useForm()`. Whereas the length of `fieldArray` always represents the _real_ length of the items, even on the first render.

Perhaps, as you said, this is a rather inevitable limitation?

**Comment by bluebill1049** [comment]
I will take a look at it, but for dynamic fields like useFieldArray, it's better to level an inline default value from the `fields`. I probably working on a video tutorial on this topic.

**Comment by bluebill1049** [comment]
> @bluebill1049 Actually, you know what, Bill. I guess what I made in the previous CSB already manifests my issue very well. 😂
> 
> Here is the updated CSB again:
> https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-erbwu?file=/src/Child.jsx:195-266
> 
> Please take notice on the followings:
> 
> * `defaultValues` is provided in `useForm()`.
> * Default values (`firstName` and `lastName`) are provided for the new item when inserting.
> * Try to insert/remove item. You can observe in the console during the first render, the length of `watchedFieldArray` is always 1, which I guess is the length of `test` array being passed as `defaultValues` to `useForm()`. Whereas the length of `fieldArray` always represents the _real_ length of the items, even on the first render.
> 
> Perhaps, as you said, this is a rather inevitable limitation?

`fields` will contain the correct length of `FieldArray`, that's why the `watch('test', fields)` need this. I think this needs some good explanation and tutorial. i will work on it.

**Comment by dwiyatci** [comment]
@bluebill1049 Hm. I, by the way, also put "inline" `defaultValue` on each `<Controller />` in my program, but it's got the same inconsistency as illustrated in my CSB above (not sure if this is what you mean by "inline default value"). **What makes it consistent in the end is to do defaulting values by using `watch('test', fields)` you mentioned above in my child component**. 🤩 

But then again, unfortunately I couldn't achieve the same consistency when using `useWatch({ name: 'test', control, defaultValue: fields })`. 😕 Here, you can see what I mean by uncommenting the `useWatch` block:
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-do236?file=/src/Child.jsx:132-248

And yup -  at the end of the day, probably this really needs some good explanation and tutorial 😁

**Comment by bluebill1049** [comment]
> @bluebill1049 Hm. I, by the way, also put "inline" `defaultValue` on each `<Controller />` in my program, but it's got the same inconsistency as illustrated in my CSB above (not sure if this is what you mean by "inline default value"). **What makes it consistent in the end is to do defaulting values by using `watch('test', fields)` you mentioned above in my child component**. 🤩
> 
> But then again, unfortunately I couldn't achieve the same consistency when using `useWatch({ name: 'test', control, defaultValue: fields })`. 😕 Here, you can see what I mean by uncommenting the `useWatch` block:
> https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-do236?file=/src/Child.jsx:132-248
> 
> And yup - at the end of the day, probably this really needs some good explanation and tutorial 😁

I will take a look this useWatch inconsistency tmr.
