### ISSUE TITLE
defaultValue prop does not seem to be working on Controller as ReactSelect.

### ISSUE THREAD

**Issue by nisarhassan12** [react-hook-form/react-hook-form#2974]
I'm using the `Controller` with `ReactSelect` but the `defaultValue` prop does not seem to be working as expected.

```tsx
<Controller
  as={ReactSelect}
  data-testid={testId}
  name={name}
  control={control}
  options={options}
  defaultValue={{
    label: options.find((option) => {
      return option.value === value;
    }).label,
    value: value,
  }}
/>
```

Ref: https://github.com/NeonLaw/codebase/pull/853

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by nisarhassan12** [comment]
Sorry. I'll close this one and open a new one which follows the Issue Template.
