### ISSUE TITLE
defaultValue prop does not seem to be working on Controller as ReactSelect.

### ISSUE THREAD

**Issue by nisarhassan12** [react-hook-form/react-hook-form#2976]
**Describe the bug**

```tsx
<Controller
  as={ReactSelect}
  data-testid={testId}
  name={name}
  control={control}
  options={options}
  defaultValue={{
    label: options.find((option) => {
      return option.value === value;
    }).label,
    value: value,
  }}
/>
```

Ref: https://github.com/NeonLaw/codebase/pull/853

I'm using the `Controller` with `ReactSelect` but the `defaultValue` prop does not seem to be working as expected i.e the first option always gets rendered and not the which is the current topic.

**To Reproduce**

The codesandbox link here is giving an un-expected error which I'm un-able to understand. Sorry that I can't mention the steps to re-produce.

Try the above code. 

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

https://codesandbox.io/s/react-hook-form-controller-template-forked-vm424?file=/src/index.js

Sorry I tried to make a CodeSandbox but due to unfamiliarity I'm getting an error there which I don't understand 

- [useForm](https://codesandbox.io/s/react-hook-form-useform-template-lsm61) Template
- [useFieldArray](https://codesandbox.io/s/react-hook-form-usefieldarray-template-q0jek) Template
- [Controller](https://codesandbox.io/s/react-hook-form-controller-template-yu0z5) Template

**Expected behavior**

Select should use whatever is provided to the defaultValue prop as the default value.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-controller-template-forked-p39k6?file=/src/index.js

looks fine to me, what's the issue here?

**Comment by nisarhassan12** [comment]
I keep getting this in the preview 
![image](https://user-images.githubusercontent.com/46004116/93884155-f96ecb00-fcfb-11ea-8531-16306ef92d52.png)

**Comment by nisarhassan12** [comment]
Closing because the defaultValue prop seems to work as expected. I was wrong. Sorry @bluebill1049 for wasting your time.

**Comment by bluebill1049** [comment]
that's all good buddy @nisarhassan12 glad it's working for you.
