### ISSUE TITLE
Possible issue with UnpackNestedValue

### ISSUE THREAD

**Issue by karlismelderis** [react-hook-form/react-hook-form#2978]
**Describe the bug**
I'm sorry if this is a bug/mistake on my side. I'm still catching up with TS and react-hook-form
Seems that certain types are not handled well with UnpackNestedValue

**To Reproduce**

```
import { useForm } from "react-hook-form";
import "./styles.css";

const testFunction = (query: Record<string, string | undefined | null>): void => {
  console.log(query)
};

export const Second = <T extends Record<string, string | undefined | null>>(): void => {
  const form = useForm<T>();

  const values = form.watch();
  testFunction(values)
}
```

Error:
```
Argument of type 'UnpackNestedValue<T>' is not assignable to parameter of type 'Record<string, string | null | undefined>'.
  Type 'NonUndefined<T> | (NonUndefined<T> extends Date | FileList ? T : NonUndefined<T> extends Record<string, unknown> ? { [K in keyof T]: UnpackNestedValue<...>; } : T)' is not assignable to type 'Record<string, string | null | undefined>'.
    Type 'NonUndefined<T> extends Date | FileList ? T : NonUndefined<T> extends Record<string, unknown> ? { [K in keyof T]: UnpackNestedValue<T[K]>; } : T' is not assignable to type 'Record<string, string | null | undefined>'.
      Type 'T | (NonUndefined<T> extends Record<string, unknown> ? { [K in keyof T]: UnpackNestedValue<T[K]>; } : T)' is not assignable to type 'Record<string, string | null | undefined>'.
        Type 'NonUndefined<T> extends Record<string, unknown> ? { [K in keyof T]: UnpackNestedValue<T[K]>; } : T' is not assignable to type 'Record<string, string | null | undefined>'.
          Type 'T | { [K in keyof T]: UnpackNestedValue<T[K]>; }' is not assignable to type 'Record<string, string | null | undefined>'.
            Type '{ [K in keyof T]: UnpackNestedValue<T[K]>; }' is not assignable to type 'Record<string, string | null | undefined>'.
              Type 'UnpackNestedValue<T[K]>' is not assignable to type 'string | null | undefined'.
                Type 'Record<string, unknown> | unknown[] | (NonUndefined<T[K]> extends Date | FileList ? T[K] : NonUndefined<T[K]> extends Record<string, unknown> ? { [K in keyof T[K]]: UnpackNestedValue<...>; } : T[K])' is not assignable to type 'string | null | undefined'.
                  Type 'Record<string, unknown>' is not assignable to type 'string'.
                    Type 'UnpackNestedValue<T[K]>' is not assignable to type 'string'.
                      Type 'Record<string, unknown> | unknown[] | (NonUndefined<T[K]> extends Date | FileList ? T[K] : NonUndefined<T[K]> extends Record<string, unknown> ? { [K in keyof T[K]]: UnpackNestedValue<...>; } : T[K])' is not assignable to type 'string'.
                        Type 'Record<string, unknown>' is not assignable to type 'string'.
```
**Expected behavior**

if I tweak UnpackNestedValue a bit error is gone.
```
export declare type UnpackNestedValue<T> = NonUndefined<T> extends NestedValue<infer U>
    ? U
    : NonUndefined<T> extends Date | FileList
        ? T
        : T extends Record<string, unknown> // change NonUndefined<T> to T
            ? {
                [K in keyof T]: UnpackNestedValue<T[K]>;
            }
            : T;
```

**Additional context**
issue arrived with 6.x react-hook-form version

**Comment by bluebill1049** [comment]
for nested value data, use this type: https://react-hook-form.com/ts#NestedValue

**Comment by stephane439** [comment]
Stepwise today harker

**Comment by karlismelderis** [comment]
> for nested value data, use this type: https://react-hook-form.com/ts#NestedValue

I'm not sure how this is relevant to the case?
I don't have any nested data values in my example.

**Comment by kotarella1110** [comment]
@karlismelderis You're right. `NonUndefined` is not need.
I will fix this soon.

**Comment by karlismelderis** [comment]
thanks you for fixing this

**Comment by vladi-strilets** [comment]
Same here 
```
<Controller
    control={control}
    name={name}
    render={({ field: { onChange, onBlur, value } }) => (
        <Input
            placeholder={placeholder}
            type={type}
            value={value}  // <-- error 
            variant={variant}
            onBlur={onBlur}
            onChangeText={(val) => onChange(val)}
        />
    )}
    rules={rules}
/>
```

```
// the value of input shows me this error:
Type 'UnpackNestedValue<PathValue<FieldsType, Path<FieldsType>>>' is not assignable to type 'string | undefined'.
```

I have just actualized to the latest version of "react-hook-form": "^7.17.5" and it still occurs.

**Comment by nickhill97** [comment]
> Same here
> 
> ```
> <Controller
>     control={control}
>     name={name}
>     render={({ field: { onChange, onBlur, value } }) => (
>         <Input
>             placeholder={placeholder}
>             value={value}  // <-- error 
>             onBlur={onBlur}
>             onChangeText={(val) => onChange(val)}
>         />
>     )}
>     rules={rules}
> />
> ```
> 
>  ```
> // the value of input shows me this error:
> Type 'UnpackNestedValue<PathValue<FieldsType, Path<FieldsType>>>' is not assignable to type 'string | undefined'.
> ```
> 
> I have just actualized to the latest version of "react-hook-form": "^7.17.5" and it still occurs.

I'm getting a similar error when using Controller. Did you find a solution to this?

**Comment by vladi-strilets** [comment]
@nickhill97 
It works, but still having this issue 

My Input is a React Native Input component. 
The allowed value type is `value?: string | undefined;`

**Comment by nickhill97** [comment]
@vladi-strilets my component is a custom form input that should always be a string but TypeScript is expecting `'UnpackNestedValue<PathValue<FieldsType,` Path<FieldsType>>>'`. This was causing functions that are expecting strings to throw errors. I've suppressed the errors by using `unknown` for the args in the functions but this feels like an unstable workaround. Did you provide react hook form a way of inferring the type of the value?

**Comment by k-one-o-two** [comment]
I'm using `^7.20.2` and facing the same error, can this please be reopened?

**Comment by redamsy** [comment]
> for nested value data, use this type: https://react-hook-form.com/ts#NestedValue

i used same example in my react app, and this what i am getting:

Type 'undefined[]' is not assignable to type 'NestedValue<number[]>'.
  Property '[$NestedValue]' is missing in type 'undefined[]' but required in type '{ [$NestedValue]: never; }'.ts(2322)
form.d.ts(11, 5): '[$NestedValue]' is declared here.
UpdateConferenceResourceCentre.tsx(55, 3): The expected type comes from property 'select' which is declared here on type 'IResourceCentreFormInputs'

**Comment by parker45** [comment]
+1 to reopen this!

**Comment by Moshyfawn** [comment]
Can you share a reproduction CSB? I might take a look later

**Comment by plxel** [comment]
I have the same issue
![image](https://user-images.githubusercontent.com/1496959/178998737-706d0421-9035-4247-91be-a4d03d7f2009.png)

**Comment by plxel** [comment]
https://codesandbox.io/s/restless-smoke-80bcug?file=/src/NumberField.tsx

I made a little sandbox 
@Moshyfawn
