### ISSUE TITLE
onChange doesnt get triggered for controlled component

### ISSUE THREAD

**Issue by Kannaj** [react-hook-form/react-hook-form#2979]
Im trying to trigger an onChange event for a TextField Material UI component (using the Controller component) - however , the onChange event doesn't seem to be passed down to the material UI component. Im wondering if im doing something wrong or if theres something i can do better. 

Enclosing a code sandbook template

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-template-forked-73525?file=/src/index.js

**Expected behavior**
The onChange event should get triggered

**Desktop **
- OS: Ubuntu 18.04
- Browser : Chrome
-  Version 85

**Comment by zulaica** [comment]
I had this issue recently and have been meaning to submit an issue — so thanks for that! 😆 

The workaround I came up with for the controlled components in my form is to explicitly call `trigger()` as part of `onChange`. For example:

```
onChange={(_event, option) => {
  doThings(option);
  trigger(<CONTROLLER_NAME>);
}}
```

**Comment by bluebill1049** [comment]
hey guys, this is changed from v5 to v6, have a read on changelog and use render prop instead.

https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md
