### ISSUE TITLE
formState.isValid is not being updated when fields are registered in useEffect

### ISSUE THREAD

**Issue by lnmunhoz** [react-hook-form/react-hook-form#298]
**Describe the bug**
The `formState.isValid` property doesn't update when using `useEffect` to `register` the fields.

**To Reproduce**
The codesandbox below shows the behaviour.
https://codesandbox.io/embed/bug-react-hook-form-formstateisvalid-wont-change-if-fields-are-registered-on-useeffect-segvo

**Expected behavior**
The formState.isValid should change accordingly.

**Additional context**
I just started using this library, so I hopefully I didn't miss anything. But I am trying for more than 1 hour and I can't find any issues with the example code. It suppose to work according to the docs.

**Comment by bluebill1049** [comment]
hey, because you are using custom `register` and `ref` is not attached during the registration. https://react-hook-form.com/api#setValue during setValue, you should trigger validation.

setValue('name', 'value', true) // third argument will trigger validation.

**Comment by lnmunhoz** [comment]
Oh all right! I didn't see that. Makes sense.

In my opinion this validate should be `true` by default, being false is so counterintuitive.
I will give it a try. Thank you!

**Comment by bluebill1049** [comment]
Sure we will improve on it in the following patch.

**Comment by bluebill1049** [comment]
However it need to be default to false. Because you aren’t certain it’s valid just yet
