### ISSUE TITLE
control type incompatibility in v6.5.0-6.8.4

### ISSUE THREAD

**Issue by delesseps** [react-hook-form/react-hook-form#2984]
**Describe the bug**

When specifying types for controls via `T extends Record<string, any>` typing errors are raised that exist from versions 6.5.0 through to 6.8.4.  I've demonstrated the issue in sandboxes below for the error as well as the working version in 6.4.1.

Note: that it doesn't seem to impact the execution on codesandbox, but under certain TypeScript configurations will break the build.

![image](https://user-images.githubusercontent.com/5125315/94095756-bfb9d380-fe65-11ea-8118-a86cc6f3ea18.png)

```typescript
Type 'Control<T>' is not assignable to type 'Control<Record<string, any>> | undefined'.
  Type 'Control<T>' is not assignable to type 'Control<Record<string, any>>'.
    Type 'Control<T>' is not assignable to type '{ removeFieldEventListener: (field: Field, forceDelete?: boolean | undefined) => void; mode: Readonly<{ isOnBlur: boolean; isOnSubmit: boolean; isOnChange: boolean; isOnAll: boolean; isOnTouch: boolean; }>; ... 19 more ...; renderWatchedInputs: (name: string, found?: boolean | undefined) => void; }'.
      Types of property 'updateFormState' are incompatible.
        Type '(args?: Partial<FormState<T>> | undefined) => void' is not assignable to type '(args?: Partial<FormState<Record<string, any>>> | undefined) => void'.
          Types of parameters 'args' and 'args' are incompatible.
            Type 'Partial<FormState<Record<string, any>>> | undefined' is not assignable to type 'Partial<FormState<T>> | undefined'.
              Type 'Partial<FormState<Record<string, any>>>' is not assignable to type 'Partial<FormState<T>>'.
                Types of property 'dirtyFields' are incompatible.
                  Type 'DeepMap<Record<string, any>, true> | undefined' is not assignable to type 'DeepMap<T, true> | undefined'.
                    Type 'DeepMap<Record<string, any>, true>' is not assignable to type 'DeepMap<T, true>'.ts(2322)
controller.d.ts(20, 5): The expected type comes from property 'control' which is declared here on type '(IntrinsicAttributes & { as: "textarea" | "input" | "select" | FunctionComponent<any> | ComponentClass<any, any> | ReactElement<...>; render?: undefined; } & { ...; } & Pick<...>) | (IntrinsicAttributes & ... 2 more ... & Pick<...>)'
```

**Codesandbox link (Required)**
Bug 6.8.4 - https://codesandbox.io/s/react-hook-form-control-type-issue-yj7kz?file=/src/TextField.tsx
Working 6.4.1 - https://codesandbox.io/s/react-hook-form-control-type-issue-forked-fmpuo?file=/src/TextField.tsx

**Comment by delesseps** [comment]
Closing temporarily to verify, could be a strange tsconfig issue, will verify.

**Comment by delesseps** [comment]
Re-opening with enhancements to the sandboxes.

**Comment by bluebill1049** [comment]
Thanks to @Tymek looks like this got resolved this PR: https://github.com/react-hook-form/react-hook-form/commit/3d713b310d5ccb303313ccad82585ea81a068c4e

https://codesandbox.io/s/react-hook-form-control-type-issue-forked-y7e59?file=/src/TextField.tsx

**Comment by delesseps** [comment]
> Thanks to @Tymek looks like this got resolved this PR: [3d713b3](https://github.com/react-hook-form/react-hook-form/commit/3d713b310d5ccb303313ccad82585ea81a068c4e) should be released in the next following days
> 
> https://codesandbox.io/s/react-hook-form-control-type-issue-forked-y7e59?file=/src/TextField.tsx

Thanks @bluebill1049 and @Tymek for the quick update!  I did notice a different issue on this new sandbox on the instance inside App.tsx:
https://codesandbox.io/s/react-hook-form-control-type-issue-forked-y7e59?file=/src/App.tsx

```typescript
Type 'Control<TestForm>' is not assignable to type 'Control<Record<string, any>>'.
  Type 'Control<TestForm>' is not assignable to type 'Pick<UseFormMethods<Record<string, any>>, "register" | "unregister" | "setValue" | "getValues" | "trigger">'.
```

**Comment by bluebill1049** [comment]
it works: https://codesandbox.io/s/react-hook-form-control-type-issue-forked-op0zr?file=/src/App.tsx i have updated the reference :)

**Comment by delesseps** [comment]
> it works: https://codesandbox.io/s/react-hook-form-control-type-issue-forked-op0zr?file=/src/App.tsx i have updated the reference :)

Thanks @bluebill1049 👏

**Comment by bluebill1049** [comment]
sweet closing this issue, will release the patch soon 👍

**Comment by delesseps** [comment]
> > it works: https://codesandbox.io/s/react-hook-form-control-type-issue-forked-op0zr?file=/src/App.tsx i have updated the reference :)
> 
> Thanks @bluebill1049 👏

hey @bluebill1049   This working sandbox where you've brought in the src manually seems ok but as soon as you remove the src and reference the latest version, the issue rears it's head again.  Is there something that I'm missing?

https://codesandbox.io/s/react-hook-form-control-type-issue-forked-0gik2?file=/src/TextField.tsx

**Comment by Tymek** [comment]
@delesseps typings around `Controller` and `control` are very convoluted. I'm trying to poke it from time to time, but I can't promise any results. Maybe
``` diff
diff --git a/src/controller.tsx b/src/controller.tsx
index 2dacb79..dea3b5c 100644
--- a/src/controller.tsx
+++ b/src/controller.tsx
@@ -17,7 +17,7 @@ const Controller = <
     | 'input'
     | 'select'
     | 'textarea',
-  TControl extends Control = Control
+  TControl extends Control = Control<any>
 >({
   name,
   rules,
```
for now?

I'm just guessing. Every change in this should be carefully tested, as my last failed proposal demonstrated :slightly_smiling_face:
