### ISSUE TITLE
Remove message: "field" is missing in the 'defaultValue' prop of either its Controller 

### ISSUE THREAD

**Issue by josias-r** [react-hook-form/react-hook-form#2990]
**Describe the bug**
I read from your docs that its _recommended_ to add all fields to the defaultValues object. I do get that that's the better pattern, but especially when working with non-vanilla form elements like react-select it often makes sense for a dev to work with undefined values.
Working with undefined values later on also helps with API requests since no empty strings will get communicated.

**Codesandbox link**
Here's an example that should work perfectly fine with undefined values
https://codesandbox.io/s/angry-euclid-yezfv?file=/src/Form.tsx

**Expected behaviour**
The above example should not throw annoying warnings (currently the console get A LOT of spam with a larger form).

If there is a REALLY good reason to why this warning should exist, at least optimize it to be one single warning that lists all the missing fields and only pops up once instead of spamming the console on every render. Also if this is the case, please explain and maybe put it into the docs.

**Comment by bluebill1049** [comment]
This is not a bug.... also in your CSB defaultValue is missing.

**Comment by bluebill1049** [comment]
Happy to discuss how to improve on it.

**Comment by josias-r** [comment]
Hmm okay, I'm still not fully understanding why undefined should not be a valid value? Where can this lead to a bug or problem?

Not logging on every render will already be a great improvement though :)

**Comment by bluebill1049** [comment]
> Hmm okay, I'm still not fully understanding why undefined should not be a valid value? Where can this lead to a bug or problem?
> 
> Not logging on every render will already be a great improvement though :)

- React give you a warning uncontrolled become controlled.
- for RHF, it will confuse `Controller` on which defaultValue to pick as well.
- uncontrolled input should have a defaultValue in React.

**Comment by josias-r** [comment]
Thanks for explaining! Since we don't work with vanilla components I never looked into such use cases. And since in the docs it's only "recommended" the warnings seemed unnecessary.
Thank you for adjusting the logging, this will already be a great improvement and maybe we can look into setting `null` as the default values on our end to get rid of the warnings completly.

**Comment by bluebill1049** [comment]
will publish the patch tmr. 👍

**Comment by tafelito** [comment]
in case of using components like react-select, undefined seems to be a valid option, what what would be the correct defaultValue in that case? null?

**Comment by tafelito** [comment]
this add a lot of `unnecessary?` boilerplate when you have a lot of react-selects in one form, having to initialize them as null just to get rid of the warnings 😕

**Comment by bluebill1049** [comment]
> this add a lot of `unnecessary?` boilerplate when you have a lot of react-selects in one form, having to initialize them as null just to get rid of the warnings 😕

I disagree with your statement, RHF by nature already reduced a lot of boilerplate for users to write, also without defaultValue you will get an issue like that, it's better to be consistent for all users so this doesn't bite you while developing.  here is a good example: https://github.com/react-hook-form/react-hook-form/issues/2998

**Comment by nihgwu** [comment]
@bluebill1049 where did you find the statement `uncontrolled input should have a defaultValue in React`, the official docs don't say that https://reactjs.org/docs/uncontrolled-components.html, if a prop is uncontrolled it could be `undefined` or `null`, but for controlled prop it couldn't be `undefined` or it will warn about changing a component from uncontrolled to controlled when you give it a valid value

**Comment by nihgwu** [comment]
the warning message is really annoying, I have a large form to create a record, and a lot fields are required according to typescript type declaration, but forced default values for those required fields makes no sense when creating a new record

**Comment by bluebill1049** [comment]
> the warning message is really annoying, I have a large form to create a record, and a lot fields are required according to typescript type declaration, but forced default values for those required fields makes no sense when creating a new record

hey, @nihgwu first of all, thanks for your feedback. 

1. it's not forced
2. without `defaultValue` or `undefined` is going to causing bugs, it's been multiple issues fired due to deafultVlaue missing.

**Comment by nihgwu** [comment]
@bluebill1049 I know it's a warning, but if there are a lot of fields in a form, there would be bunch of warnings in the console, which distracts a lot when debugging with tests in my case, I need to scroll down a lot to find the real problem, and there could be misleading, undefined defaultValue for uncontrolled prop is legit, I'm new to react-hook-form, so I don't know the issues raised by undefined defaultValue, but I think we should warn for those special cases instead of warning on a general pattern which is legit actually

**Comment by cargallo** [comment]
I'm facing the same issue in typescript, also you can't use null as default value you get this error when try to access the error message. I really like the library but I think I probably would have done faster without using the library, really using with MUI autocomplete or select in combination with typescript just gave me headache

![image](https://user-images.githubusercontent.com/13320290/98496814-3e55af00-2221-11eb-894b-92deab1e4468.png)

**Comment by bluebill1049** [comment]
> I'm facing the same issue in typescript, also you can't use null as default value you get this error when try to access the error message. I really like the library but I think I probably would have done faster without using the library, really using with MUI autocomplete or select in combination with typescript just gave me headache
> 
> ![image](https://user-images.githubusercontent.com/13320290/98496814-3e55af00-2221-11eb-894b-92deab1e4468.png)

How can we improve on this issue above? any suggestion? Did you use NestedValue for the type?

**Comment by cargallo** [comment]
Hi bill, I did not used NestedValue because it gave me an error. I just select one Client in the autocomplete I think that just using cliente: Cliente in the useForm had to work. If I define cliente as Cliente | null so I can use null as default value in useForm then I RHF complains of the error I pasted above.

![image](https://user-images.githubusercontent.com/13320290/98538315-505b4000-2269-11eb-9743-981dbf277615.png)

**Comment by bluebill1049** [comment]
> Hi bill, I did not used NestedValue because it gave me an error. I just select one Client in the autocomplete I think that just using cliente: Cliente in the useForm had to work. If I define cliente as Cliente | null so I can use null as default value in useForm then I RHF complains of the error I pasted above.
> 
> ![image](https://user-images.githubusercontent.com/13320290/98538315-505b4000-2269-11eb-9743-981dbf277615.png)

Thanks @cargallo I am removing that console warning anyhow.

**Comment by cargallo** [comment]
Ok, as I understand React has its own warning about controlled / uncontrolled, so if something goes wrong still the error can be catched by react. Tnx,

**Comment by cargallo** [comment]
@bluebill1049 as always you were right about controlled / uncontrolled. Sorry yesterday was very late at Argentina and I  was pissed of about another error with this. 

Now I've tested everything and realize that if you do not specify a defaultValue autocomplete (react in fact) is giving an error (anyway I think its better to see this error than the warning that you removed).

For other with this same problem that I had, I finally do this, it's temporally solution since NestedValue is not working for me as I said before. 

I define the autocomplete field as this in typescript (ClientesComponent is actually a wrapper around MUI autocomplete)

```JSX
interface FormFields {
  cliente: Cliente | null; // THIS IS NECESARRY TO DEFINE CLIENT IN DEFAULTVALUES AS NULL
}

const defaultValues = {
    cliente: null, //HERE INITIALIZE THE CLIENT AS NULL / THIS IS NECESARRY OTHERWISE  REACT  COMPLAINS ABOUT CONTROLLED / UNCONTROLLED
};

const methods = useForm<FormFields>({
    defaultValues: defaultValues,
    resolver: yupResolver(validationSchema)
  });


....

<Controller
                  render={props => (
                    <ClientesAutocomplete
                      RHFProps={props}
                      onChange={(_, data) => props.onChange(data)}
                      error={!!errors.cliente}
                      helperText={mensajes.ingresarCliente} // HERE I COULDN'T USE LIKE ERRORS.CLIENTE.ID.MESSAGE AS I THINK IT'S RHF BUG OR I DO NOT KNOW HOW TO USE NESTEDVALUES OR RECORD IN THIS CASE. SO I JUST PUT A HARDCODED MESSAGE.
                    />
                  )}
                  name="cliente"
                  control={control}
                />
```

**Comment by bluebill1049** [comment]
Thanks, @cargallo honestly I was pretty disappointed to see users complain about something that I did to help them avoid errors, and that's why I gave up on this and removed it for the sake of not hearing those. I will add it back, I think it's still useful to warn users about this, there are a couple of issues when users are frustrated because they think Controller doesn't need a default value. I think it gives the user a bit richer context on the error rather than those controlled to uncontrolled warning.

**Comment by tafelito** [comment]
@bluebill1049 for the record, mine was not a complain, but when you suddenly update to a new version and you see a lot of warnings that you didn't have before (and everything was working as expected at least on my end), you want to at least know what's going on. 
You're doing a great job with the library in general and I really appreciate the time you spend on it so I hope you didn't take the wrong way

**Comment by tafelito** [comment]
I wonder if the NestedValue type error is related to this https://github.com/react-hook-form/react-hook-form/issues/1631 somehow

**Comment by bluebill1049** [comment]
Thanks, @tafelito I think my intention was not to break or annoying every developer who uses this lib. I mean my intention was pretty clear the reason why I build and maintain this lib, the goal is to avoid problems or issues for developers. If I know there is going to be an issue and frustrate users when it's not working as expected and hence introduced some of the warnings to guide users on the right track, but by all means, I am not dictating the direction I see a lot of people complain so I took it off, but I still believe it will help to not bite you in a situation when `undefined` is going to bite you. I can't remember the issues on top of my head but we had a couple. I am keeping an eye on this post, and willing to make improvements (reasonable) in the long run.

**Comment by s97712** [comment]
This warning should not appear for optional fields

**Comment by bluebill1049** [comment]
> This warning should not appear for optional fields

please join the discussion here: https://github.com/react-hook-form/react-hook-form/discussions/3653

**Comment by r1y4h** [comment]
Hi, I still receiving "missing in the 'defaultValue' prop of either its Controller" even if I am already have default value on my useForm or Controller level. I am using ReactSelect 3rd party component.

**Comment by bluebill1049** [comment]
> Hi, I still receiving "missing in the 'defaultValue' prop of either its Controller" even if I am already have default value on my useForm or Controller level. I am using ReactSelect 3rd party component.

The bad news is something is wrong...
The good news: we are removing all those warnings.

Do you want to share a reproduceable csb?

**Comment by r1y4h** [comment]
I'm currently upgrading from 5.6.1 to 6.14.2, I will try to give a sample code. I just wanted to quickly ask if someone else also experience the same issue

**Comment by ottovw** [comment]
@bluebill1049 thanks for your efforts and this great lib. Removing this warning is a better solution though, also when i understand your concerns.

Classic example of:

![24e2828d38b6c7f2fc9c539347d5d1f4](https://user-images.githubusercontent.com/1045946/106185264-e0db5980-61a2-11eb-8859-9329f8840031.jpg)

Staying with the analogy: You can't rollerscate on the unpaved path, still people will choose it.

Anyways ... Thanks!

**Comment by bluebill1049** [comment]
> @bluebill1049 thanks for your efforts and this great lib. Removing this warning is a better solution though, also when i understand your concerns.
> 
> Classic example of:
> 
> ![24e2828d38b6c7f2fc9c539347d5d1f4](https://user-images.githubusercontent.com/1045946/106185264-e0db5980-61a2-11eb-8859-9329f8840031.jpg)
> 
> Staying with the analogy: You can't rollerscate on the unpaved path, still people will choose it.
> 
> Anyways ... Thanks!

Thanks for the feedback, we are removing all warning messages.

**Comment by patrickap-bkklinde** [comment]
What about an option to initially define a fallback for all fields? For example, one could set a general `defaultValue` of `""` if none was specified.

**Comment by bluebill1049** [comment]
> What about an option to initially define a fallback for all fields? For example, one could set a general `defaultValue` of `""` if none was specified.

that's what `useform`'s `defaultValues` does

**Comment by patrickap-bkklinde** [comment]
> that's what `useform`'s `defaultValues` does

Yes that's true, but I was thinking more of a way to not explicitly name each field individually.
