### ISSUE TITLE
getValues('test') returns undefined combined with useFieldArray.

### ISSUE THREAD

**Issue by KarelVerschraegen** [react-hook-form/react-hook-form#2992]
**Describe the bug**

When combining `getValues` and `useFieldArray`, `getValues('test')` returns `undefined` instead of the array itself.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-forked-3w36l?file=/src/index.js
2. Click on `GET VALUES`
3. See in console that `getValues('test')` logs `undefined` but that `getValues().test` returns an array with objects.

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-3w36l?file=/src/index.js

**Expected behavior**

`getValues('test')` should return the same value as `getValues().test`.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Arch linux
- Browser Firefox
- Version 81.0

**Additional context**

**Comment by bluebill1049** [comment]
<img width="631" alt="Screen Shot 2020-09-24 at 10 03 46 pm" src="https://user-images.githubusercontent.com/10513364/94142561-d259fa00-feb1-11ea-9002-d71f315dc15c.png">

we don't support `key` lookup for getValues.

**Comment by KarelVerschraegen** [comment]
So this is expected behaviour?

How would you read the fieldArray values?

```
onClick={() => {
    const myFieldArray = getValues().test
}}
```

Or is there a better way to access the fieldArray?

Thanks a lot for your quick responses!

**Comment by bluebill1049** [comment]
Yes, as the doc stated it's only made for input name lookup.

you have the entire form values, you can easily read the array value.
