### ISSUE TITLE
Unregistered defaultValues don't show up onSubmit

### ISSUE THREAD

**Issue by nandorojo** [react-hook-form/react-hook-form#2994]
First off, thanks for this library, it's been incredibly helpful.

**Describe the bug**

When I declare an initial value, I expect the entire initial value, plus the fields edited by the form, to be returned by `onSubmit`. However, only the fields registered by `useForm` show up in `onSubmit`. I'm coming from `useState`, where all state merges with initial state, so I might be misinterpreting the intent of `defaultValues`.

**To Reproduce**

1. Create a form with default values
2. Register only one of the fields corresponding to the default value
3. Log the result of `onSubmit`, notice that both fields aren't there.

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-defaultvalues-v6-forked-41fpm?file=/src/index.js

In this example, the `firstName` field is registered by an input, `lastName` is not. Both are provided in default value. `onSubmit` logs only the first name field, but it ignores `lastName`.

**Expected behavior**

I expect `onSubmit` to return a mutated version of the `defaultValues`, including fields that never get registered by `react-hook-form`.

<img width="1452" alt="Screen Shot 2020-09-24 at 12 15 28 PM" src="https://user-images.githubusercontent.com/13172299/94171891-d0ffe180-fe5f-11ea-9256-77148427c8df.png">

**Additional context**

My guess is that the behavior I'm describing here is intended by the library. 

Here is my use case: I want to let a user edit their profile. The first step is to fetch a user's profile from the server. I set this value as the `defaultValues`. Next, I want to let them edit just a few fields, like `name`, and `media.images[0]`. Once they do that, I want to return the **full `profile` object** to the server, and use that as the new profile.

Since I have many nested fields, I have to figure out a way to deep merge the `defaultValues` with the value this library returns `onSubmit`, and it's a bit messy. With `useState`, this isn't necessary, since it edits the `initialState` directly.

What do you suggest I do for this use case?

**Comment by bluebill1049** [comment]
Yes, it's intended.

I think of the following solution

1. HTML standard input type `hidden`
2. custom register at `useEffect`.

**Comment by nandorojo** [comment]
Got it, thanks for the quick reply. I think the idea behind your solution makes sense. But there are situations I'm running into where I'm not sure how it would work.

For example, I have a nested array, `media.images.all_sources`. My data looks like this (simplified):

```js
const defaultValues = {
  media: {
    images: {
      all_sources: [
        { url: 'one', height: 1, width: 1 },
        { url: 'two', height: 1, width: 1 },
        { url: 'three', height: 1, width: 1 },
        { url: 'four', height: 1, width: 1 } //...etc
      ]
    }
  }
}
```

Using `useFieldArray`, I let the user `remove` and `move` the images. Then, `onSubmit`, I try to merge `defaultValues` with `value`. But this isn't working as intended.

Imagine that the user removes every image, such that the form state looks like this:

```js
value = {
  media: {
    images: {
      all_sources: []
    }
  }
}
```

I'm not sure how to merge that with the initial state. If I use lodash's `merge`, it won't remove the items from the original state array. Instead, it will just combine my empty array with the original array.

This is what I'm trying to do `onSubmit`:

```js
import merge from 'lodash.merge'

handleSubmit(value => {
  const merged = merge(defaultValues, value)
  // this does not work, since it doesn't remove values from the array.
  // it's returning the same images as defaultValues was
})
```

The problem is, how can I know that these items should be removed at the submit step? With my current solution, they're just being merged, and not editing the original state. 

When I used to use `useState`, I mutated the entire `initialState`, so I knew that the fields I was editing / removing would be properly accounted for. The merging worked at the time of editing.

Now that I have to merge the fields dynamically when submitting, I'm a bit unclear on how to do it for the cases of removed items and such.

Thanks again for your help!

**Comment by nandorojo** [comment]
> HTML standard input type hidden

Also, for context, I'm using React Native.

**Comment by nandorojo** [comment]
The main idea is that, I want to be able to dynamically receive an object from the server, mutate it, and send it back, without knowing every field it will have in advance.

**Comment by nandorojo** [comment]
Excuse me sending many messages, but just to be as clear as possible, I remade the same use-case in Formik. 

As you can see, it's mutating the original state, even for fields that aren't registered: https://codesandbox.io/s/infallible-dream-cn2yw?file=/src/App.js:673-773

In that example, the `name` field doesn't get edited anywhere, but since it's in the original state, it still shows up `onSubmit`. Meanwhile, the nested field is easily edited.

I understand that this might not be the desired use case for every instance, but it would be awesome to have a way to do it in my case.

Thanks again!

**Comment by bluebill1049** [comment]
That's fundamentally two different things, you can't live in two "worlds". 

React Hook Form based on uncontrolled form, so your entire form is not re-render while your user interacts with the input (the re-render potential live inside the input itself or your controlled component), which means form state live inside inputs instead of your local state which acting as a skeleton to your entire form. Obviously taking RHF has its cons and props, and the choice is at users, what you list is what's the trade-off, this is not something we can or should adopt otherwise we going completely the opposite of why this lib exists, but remember anything can do in JS it can be achieved in React, so I don't think this is going to be a blocker rather how do you solve the problem. What I suggested above is my solution which I am pretty sure it will work, however, i understand those are not directly related to your project/work.

**Comment by nandorojo** [comment]
Got it, I understand, and I know that each approach has its trade-offs. It looks like RHF won't be able to do it for my use case. It's a bummer, since it's a great package, but I suppose I misunderstood the approach it had. Thanks again.

**Comment by bluebill1049** [comment]
> Got it, I understand, and I know that each approach has its trade-offs. It looks like RHF won't be able to do it for my use case. It's a bummer, since it's a great package, but I suppose I misunderstood the approach it had. Thanks again.

not a problem. 👍 the right tool for the right job.

**Comment by schickling** [comment]
Thanks for the thread above. Very useful as I was running into the same problem. Until there is some kind of "better solution" I resorted to merge the registered and unregistered values in my `handleSubmit` callback.

**Comment by bluebill1049** [comment]
> Thanks for the thread above. Very useful as I was running into the same problem. Until there is some kind of "better solution" I resorted to merge the registered and unregistered values in my `handleSubmit` callback.

glad you find it useful, have you tried to include those values in the `defaultValues`, and set `shouldUnregister: false`, maybe it would work for your "use case".

**Comment by nandorojo** [comment]
@schickling if you’re going to merge on submit, I recommend keeping your form very flat. Merging arbitrary nested values, especially field arrays, isn’t meant for this library. Formik is a better solution for this case.

**Comment by bluebill1049** [comment]
Thanks @nandorojo for the answer, although i kind does not agrees with part  "especially field arrays", I think react hook form's field array is special and solve different problems.

- User experience, we focus on input the moment user click on append/prepend/insert, so the user can continue to edit the form without the need to scroll up and down, better accessibility 👍 
- Much better performance: https://www.youtube.com/watch?v=Q7lrHuUfgIs your user input doesn't keep trigger re-rendering and skip the `map` each time when user typing.

also took a quick look at your example above again, you are using RC version of v6. I did what i suggested to @schickling above, looks like it's working ok for this particular example which you have posted, but i wouldn't say it will solve all the problems :) hopefully this clear a few things up, again right tool for the right job. 

<img width="1497" alt="Screen Shot 2020-10-13 at 9 47 41 am" src="https://user-images.githubusercontent.com/10513364/95796646-26316380-0d39-11eb-8336-31e1a6bda539.png">

**Comment by nandorojo** [comment]
Agreed. I'm not disparaging the quality of this library at all - it's really impressive work. But for the specific use case of mutating your original state with dynamic fields, Formik is a better fit. You lose the benefits of performance from this library, of course. But it reduces the need to find a way to deep-merge objects when that's needed.

For example, if I had an original list of images in a nested field and then removed 2, how would I merge that to send back to the server? It was entirely clear to me, since I wasn't registering all the fields.

Ultimately, I preferred the React-like nature of maintaining a single source of truth with Formik. But it's likely that my need to edit an entire document from a database isn't that common.

Also, for anyone else that comes across this issue: React hook form is maintained far better than Formik. I wish it were built for my use case, because overall, it's a much better library.

**Comment by bluebill1049** [comment]
again thanks for your proactive feedback @nandorojo 👍

**Comment by nandorojo** [comment]
No problem, and thanks for the suggestion with the new feature addition. I'll try it out next time!

**Comment by bluebill1049** [comment]
This issue has been improved on V7 👍 

https://codesandbox.io/s/react-hook-form-defaultvalues-v6-forked-4xdm4?file=/src/index.js

**Comment by nandorojo** [comment]
Thanks for the update! Could I ask what the new behavior / options are?

**Comment by bluebill1049** [comment]
> Thanks for the update! Could I ask what the new behavior / options are?

- inputs value/reference will not be removed due to unmount
- `formValues` will do a shallow merge with `defaultValues`

For more details, take a look at the RFC: https://github.com/react-hook-form/react-hook-form/discussions/3714

**Comment by nandorojo** [comment]
Just wanted to check in here. I'm back to re-evaluating using react-hook-form, so I wanted to see if there are any links/changes I should take a look at. Should I just reference the docs and RFCs? Is `shouldUnregister: false` sufficient for the aforementioned use case? Thank you!

**Comment by bluebill1049** [comment]
hey @nandorojo 

`shouldUnregister: false` is the default option now
https://codesandbox.io/s/react-hook-form-defaultvalues-v6-forked-s7lmf?file=/src/index.js

**Comment by nandorojo** [comment]
Awesome. I've been reading through the v7 RFC. It looks really great. Excited to try this out again.
