### ISSUE TITLE
Form fails to render with 'Controller' element in it in production build

### ISSUE THREAD

**Issue by pcwiek** [react-hook-form/react-hook-form#2996]
**Describe the bug**
A form with `Controller` element works with version 6.0.0 & 6.0.1.
From version 6.0.2 up to 6.8.4, it fails to render completely, but **only using production build** of `react-scripts`. It seems to work fine under dev build, which makes it hard to showcase, but fortunately I think I found a way to do it - or at least the stack traces look really similar.

I also confirmed it's the `Controller` part that crashes, because once I remove that one control from my form (and there's only one drop-down that's using `Controller`,  'cause I'm integrating with MaterialUI select pretty much like [the docs suggest](https://react-hook-form.com/get-started#IntegratingwithUIlibraries)), the form renders and all other controls work perfectly fine under 6.8.4.

**To Reproduce**

1. Go to the 'Controller' sandbox with the example
2. Select version 6.0.1 of the library and the form should render
3. Select any higher version and observe the error

My production build stack trace (with minification temporarily disabled):
```
TypeError: path is undefined
    get get.ts:6
    registerFieldRef useForm.ts:927
    register useForm.ts:1026
    setRef setRef.js:4
    useForkRef useForkRef.js:15
    setRef setRef.js:4
    useForkRef useForkRef.js:16
    setRef setRef.js:4
    useForkRef useForkRef.js:16
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
```

**Codesandbox link (Required)**

- [Controller](https://codesandbox.io/s/react-hook-form-controller-template-yu0z5) - no need to look far, the default template is crashing

**Expected behavior**
The form should render

**Screenshots**
Stack trace from the playground template: 
![image](https://user-images.githubusercontent.com/1394568/94182980-07f6e700-fea2-11ea-8190-dd59950dbf60.png)

So it seems that my production build & the playground both seem to crash in `get` with eerily similar errors.

**Desktop:**

- OS: Windows 10
- Browser: Firefox
- Version: 81

**Comment by bluebill1049** [comment]
The template is updated and your controller is missing name props, which is required. This is a major change from v5 to v6.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md

**Comment by pcwiek** [comment]
@bluebill1049 thank you!
Yup, that was it, along with the fact that all wrapping all MUI controls in `Controller` (instead of trying to use `inputRef`) worked like a charm.
Discussions/docs link for anyone else looking:
- https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r?file=/src/index.js
- https://github.com/react-hook-form/react-hook-form/discussions/2989

**Comment by bluebill1049** [comment]
np :)
