### ISSUE TITLE
Form does not reset properly when used with little-state-machine

### ISSUE THREAD

**Issue by harrisrobin** [react-hook-form/react-hook-form#2998]
**Describe the bug**
I have a react-hook-form that uses `useFormContext` and `little-state-machine`. The form fails to reset the checkbox, even though the text input seems to reset fine.

**To Reproduce**

1. Open the drawer
2. click the checkbox to toggle it.
3. click the reset button
4. see that the checkbox is still toggled and not reset.

![image](https://user-images.githubusercontent.com/3880008/94227293-0d672800-fec8-11ea-9d89-8af8e34f8ff0.png)

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-get-started-forked-oyvyg?file=/src/form.js

**Expected behavior**
For the form to reset completely. In this case, the checkbox should be unchecked.

**Comment by bluebill1049** [comment]
Please pay attention to the console warning: 

fixed: https://codesandbox.io/s/react-hook-form-get-started-forked-tixw8?file=/src/form.js

**Comment by bluebill1049** [comment]
<img width="752" alt="Screen Shot 2020-09-25 at 2 52 46 pm" src="https://user-images.githubusercontent.com/10513364/94227818-c8320d00-ff3e-11ea-8d6c-61025d4d24a2.png">

**Comment by realadamsmith** [comment]
So is it fixed and what's the solution? lol

**Comment by bluebill1049** [comment]
> So is it fixed and what's the solution? lol

do you have a codesandbox with the issue? the above is not really an issue :)
