### ISSUE TITLE
Typescript error with Control

### ISSUE THREAD

**Issue by rusefendi** [react-hook-form/react-hook-form#3002]
**Describe the bug**
Typescript error with Control type from example (https://react-hook-form.com/ts#Control)

**To Reproduce**
1. Open https://codesandbox.io/s/objective-raman-jyt0g?file=/src/App.tsx
2. Look at the control prop from IsolateReRender component.
3. See error

**Codesandbox link (Required)**
https://codesandbox.io/s/objective-raman-jyt0g?file=/src/App.tsx

**Expected behavior**
Not having any errors

**Comment by bluebill1049** [comment]
This issue is occured at 6.8.5
