### ISSUE TITLE
Typing issue: setValue accepts null or undefined unexpectedly

### ISSUE THREAD

**Issue by berlysia** [react-hook-form/react-hook-form#3007]
**Describe the bug**
Type definition of `setValue` is not respect to non-null, non-undefined definitions of `TFieldValues`

**To Reproduce**

1. define `TFieldValues` type, with nullable property and optional property
2. give generic parameter to `useForm<TFieldValues>`
3. use `setValue` with an each keys
4. run-time error is now possible

```ts

type FormValues = {
  simple: string;
  undefinedable: number | undefined;
  nullable: string | null;
  optional?: boolean;
};

const { setValue, getValues, handleSubmit, control } = useForm<FormValues>();

// all of these are not reported
setValue("simple", null);
setValue("undefinedable", null);
setValue("nullable", undefined);
setValue("optional", null);
```

**Codesandbox link (Required)**

since v6.8.3 https://codesandbox.io/s/funny-margulis-mkxp7?file=/src/App.tsx

**Expected behavior**

```ts
// all of these are reported
setValue("simple", null);
setValue("undefinedable", null);
setValue("nullable", undefined);
setValue("optional", null);
```

**Screenshots**

**Desktop (please complete the following information):**

(type definition issue)

**Smartphone (please complete the following information):**

(type definition issue)

TypeScript v4.0.3

**Additional context**

FYI: until v6.8.2 https://codesandbox.io/s/quizzical-snow-e2fxz?file=/src/App.tsx
This behavior is related to https://github.com/react-hook-form/react-hook-form/discussions/2915 , and fixed in https://github.com/react-hook-form/react-hook-form/pull/2924, but this fix causes current behavior.

**Comment by bluebill1049** [comment]
Thank you very much for the detailed issue report!
