### ISSUE TITLE
when I have a request api in useEffect after api response the form will reset all form content

### ISSUE THREAD

**Issue by silenceM** [react-hook-form/react-hook-form#301]
**Describe the bug**

**To Reproduce**
when I have a request api in useEffect after api response the form will auto reset all form content(I haven't use reset method)

**Expected behavior**
the form not auto reset form content

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac 
 - Browser chrome
 - Version  76.0.3809.132

**Smartphone (please complete the following information):**

**Additional context**

**Comment by stramel** [comment]
@silenceM 	Can you provide a codesandbox or some code that we can look at to explore the issue. There is no reason that the form should reset based on an async call in a `useEffect`

**Comment by bluebill1049** [comment]
Feel free to reopen once u have more information around issue :)
