### ISSUE TITLE
Invalid formState when using FormProvider and useFormContext

### ISSUE THREAD

**Issue by gdbrown** [react-hook-form/react-hook-form#3010]
When using `<FormProvider/>` and `useFormContext` a nested input (same with `useFieldArray`) will cause formState to be in an invalid or inconsistent state.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-v6-formstate-forked-4s29c
2. Notice that the form starts out as not dirty (correct)
3. Touch the `first name` field but do not change it.
4. Tab to the `last name` field.
5. Notice that the formState reports the form is dirty. (incorrect).

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-v6-formstate-forked-4s29c
This is a forked example from the current website.

**Expected behavior**
The formState should have isDirty value of false because the form has not changed.

**Desktop (please complete the following information):**

- OS: MacOS Catalina
- Browser: Firefox and Chrome show the issue
- Version: Firefox (80.0.1) and Chrome (85.0.4183.102)

---

Great library btw, nice work! 👍

**Comment by bluebill1049** [comment]
hey @gdbrown looks like this issue is due to missing default value for `corndogAmount`

https://codesandbox.io/s/react-hook-form-v6-formstate-forked-7dzbq?file=/src/index.jsx

**Comment by gdbrown** [comment]
@bluebill1049 interesting, i see that and thank you.  I noticed that if the defaultValues has additional keys that are not rendered as field it will produce the same behavior.  e.g.
```
    defaultValues: {
      firstName: "Grace",
      lastName: "Hopper",
      corndogAmount: "",
      someFieldYouDidNotRegister: ""
    }
```
never having assigned `someFieldYouDidNotRegister` to a field on the form.  interesting quirk to be aware of.  that defaultValues shape seems to have to match exactly the registered fields.

thanks for investigating!

**Comment by bluebill1049** [comment]
yes, we do a deep comparison with `defaultValues`, weather its inline or initialised at useForm.

**Comment by gdbrown** [comment]
makes sense, thanks again.
