### ISSUE TITLE
Controller for MUI switch, checkbox does not work in new version

### ISSUE THREAD

**Issue by sgreinert** [react-hook-form/react-hook-form#3016]
**Describe the bug**
Material UI switches, checkboxes do not work anymore with version 6.8.6. Values are not resetted or read. In the codesandbox example, Version 5.5.1 is used. This version works fine.

**To Reproduce**

1. Use Code Example https://codesandbox.io/s/react-hook-form-controller-079xx
2. Use current version 6.8.6 instead of version "5.5.1"
3. Interact with Material UI switch, checkbox. Pressing reset button will not reset the values. Submit Button will not show the values.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-079xx
Use current version

**Expected behavior**

**Desktop (please complete the following information):**

- OS: Win10
- Chrome, Firefox, Egde
- Version 6.8.6

**Comment by bluebill1049** [comment]
Take a look at the doc example: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r using render props.
