### ISSUE TITLE
React hook form is not working properly under iframe

### ISSUE THREAD

**Issue by sandy1018** [react-hook-form/react-hook-form#3017]
We had a project that all the React pages are under Iframe(React frame component). In this case, react hook form didn't work properly with two issues.
1).  Revalidate didn't work. Looks like onChange event didn't happen. Validations triggered only on submit. I tried set reValidateMode to "onChange" manually, but no luck.
2).  Form validate and submit data for all fields. Even if fields are hidden and not in the DOM. We have radio or toggle button to show/hide contents, but the hidden content also been validated and data was included in form submit. For example,in below code snip,  the data under both LocalUserForm and ExternalForm are been validated.
{type === "local" && (
          <LocalUserForm />
)}
 {type === "external" && (
          <ExternalUserForm />
  )}

**Comment by bluebill1049** [comment]
Don’t think we are support iframe usage.

**Comment by bluebill1049** [comment]
you may want to consider to use <Controller /> for your input or custom register at `useEffect`,

**Comment by sandy1018** [comment]
Controller component made it work. Thanks!

**Comment by bluebill1049** [comment]
cool
