### ISSUE TITLE
Wrong behaviour of useArrayField fields update after reset().

### ISSUE THREAD

**Issue by vadim080617** [react-hook-form/react-hook-form#3019]
**Describe the bug**
Hello, i have a problem with reset array field values. 
My default values: 
```
{
  name: "Initial",
  items: [
    { id: 56, name: "Initial 1" },
    { id: 65, name: "Initial 2" }
  ]
}
```
I do:
```
    const newFormValues = {
      name: "After reset",
      items: [
        { id: 56, name: "After reset 1" },
        { id: 65, name: "After reset 2" }
      ]
    };
    reset(newFormValues);
```
The bug is that form values are changed, but array field name input still display old value.
I figured out that this problem happends if objects have same id. ( { id: 65, name: "Inital 2" } => { id: 65, name: "After reset 2 } - dont work, { id: 65, name: "Inital 2" } => { id: 66, name: "After reset 2 } - works). Also figured out that this problem reproduces in verison 5.4.1 and higher.

**Reproduce**
[Form](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-81w46?file=/src/index.js)
Click reset

Is this correct way to reset array fields?
Thanks in advance

**Comment by bluebill1049** [comment]
This issue caused by `id`, `id` is used for field array's `key`, if you need to store `id`, use input type hidden:

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-qjs1g?file=/src/index.js

**Comment by vadim080617** [comment]
Whats wrong in default values?

**Comment by bluebill1049** [comment]
<img width="439" alt="Screen Shot 2020-09-28 at 5 29 19 pm" src="https://user-images.githubusercontent.com/10513364/94403016-26b1f200-01b0-11eb-8063-8805c1b2ed83.png">

`name` instead of `value`

**Comment by vadim080617** [comment]
Yeap, my bad. But even with correct field name it's still no working.

**Comment by bluebill1049** [comment]
please check my codesandbox.

**Comment by vadim080617** [comment]
I see, it updated. I need provide id property in array field objects. How i can do it? I tried use keyName property, but it not works as i expecting.

**Comment by bluebill1049** [comment]
please read me comment above ^ input type hidden to store your `id` just like how you building native form.

**Comment by bluebill1049** [comment]
keyName: 'others'

key={fields.others}

<input tyep="hidden" name="id" />

**Comment by vadim080617** [comment]
I got it, it's works, thank you a lot for explanation.
