### ISSUE TITLE
How to reset dirty or reinitialize form? dirty never false after call reset()

### ISSUE THREAD

**Issue by iamchanii** [react-hook-form/react-hook-form#302]
**Describe the bug**
Dirty is not reset after call reset().

**To Reproduce**
Here is codesandbox for reproduce: https://codesandbox.io/embed/smoosh-shape-fuy5e

1. There is `SampleForm` component to receive `user` and `onSubmit` props. it use `useEffect()` hook(line 15 ~ 18) for reset form when `props.user` is updated. but currently, I commented `reset(user)`(line 17) for reproduce.
2. change some fields, and reset original value. the submit button's disabled is toggle via `formState.dirty` (ex> Update name to Foo1, submit is enabled. Update name to Foo, submit is disabled)
3. uncomment `SampleForm` line 17, `reset(dirty)` line. and try again step 2. the submit button is never disabled again even I tried set original value.

**Expected behavior**
`formState.dirty` should be false when I change form value to original after call `reset()`

**Screenshots**
App.tsx
![image](https://user-images.githubusercontent.com/26643843/64504709-de593500-d30b-11e9-9369-77a104d03e22.png)

SampleForm.tsx:
![2019-09-09 14-10-15 2019-09-09 14_11_13](https://user-images.githubusercontent.com/26643843/64504674-b669d180-d30b-11e9-929f-d3885cea877e.gif)
(Ignore Rocket's popup... ;))

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.16 mojave
 - Browser: Chrome
 - Version: 76.0.3809.132
 - react-hook-form@3.23.4

**Additional context**
Maybe it is not a bug. but I want to reset dirty value after I call `reset()`. Is there another way to reset dirty? Thanks to your awesome library :)

**Comment by bluebill1049** [comment]
Thanks @iamchanii will take a look this issue soon :)

**Comment by bluebill1049** [comment]
want to test out this patched beta version: `react-hook-form@3.23.5-beta.1`?

**Comment by bluebill1049** [comment]
working on my end, if you can verify. we can release this fix soon :) ❤️

**Comment by iamchanii** [comment]
omg, blazing fast! I will check out your works!

**Comment by iamchanii** [comment]
Good! I tested on codesandbox, and my production! thanks to your works! ⚡️I have to close issue!

![2019-09-09 14-10-15 2019-09-09 14_11_13](https://user-images.githubusercontent.com/26643843/64506991-69d6c400-d314-11e9-9da2-397bf198f598.gif)

**Comment by bluebill1049** [comment]
I will publish this patch :) happy coding ❤️

**Comment by tjatwood** [comment]
I'm still seeing this issue even after upgrading to 3.28.1. Is there anything else that's needed besides just calling `reset()` on on the form?

**Comment by tjatwood** [comment]
Actually, the issue was that I was calling `reset()` inside the submit handler. Including a `setTimeout()` around the call to `reset()` fixed the issue.

**Comment by bluebill1049** [comment]
@tjatwood can you supply a codesandbox for this issue?

**Comment by tjatwood** [comment]
Here you go https://codesandbox.io/s/suspicious-cori-fd354. I was able to narrow it down to only happening when I use Material UI components. I don't know if that's something you really want to support though.

**Comment by bluebill1049** [comment]
thanks @tjatwood for the codesandbox :) for MUI related issue, the author is already considering to have better support for react-hook-form. So hopefully that will happen 👍

**Comment by olddustysocksunderthecouch** [comment]
I'm using the MUI Text Field component and found that it was showing the placeholder together with the value that I had set using `reset({ someValue: 'value'})` in a useEffect hook. I found that adding the InputLabelProps solved the issue
```             
<TextField
 InputLabelProps={{ shrink: true }}
...
/>
```

**Comment by bluebill1049** [comment]
> I'm using the MUI Text Field component and found that it was showing the placeholder together with the value that I had set using `reset({ someValue: 'value'})` in a useEffect hook. I found that adding the InputLabelProps solved the issue
> 
> ```
> <TextField
>  InputLabelProps={{ shrink: true }}
> ...
> />
> ```

Take a look this codesandbox: https://codesandbox.io/s/react-hook-form-controller-079xx

**Comment by olddustysocksunderthecouch** [comment]
@bluebill1049 I'm not sure if that would work for me. In my case, I fetch data asynchronously which might only return after the page has already loaded. So I have a useEffect which runs `reset` with the values from the async call. Without `InputLabelProps={{ shrink: getValues('someValue') }}` the input doesn't know that it's dirty and shows both the placeholder and the value. 

I'm not sure how I would solve this with a form controller - I'd greatly appreciate code sample if it is indeed possible.

**Comment by bluebill1049** [comment]
Look this is your original question: 

> I'm using the MUI Text Field component and found that it was showing the placeholder together with the value

there is a reset button at the bottom of that codesandbox.

**Comment by dequn** [comment]
> I'm using the MUI Text Field component and found that it was showing the placeholder together with the value that I had set using `reset({ someValue: 'value'})` in a useEffect hook. I found that adding the InputLabelProps solved the issue
> 
> ```
> <TextField
>  InputLabelProps={{ shrink: getValues('someValue') }}
> ...
> />
> ```

Looks like this only solve reset, but don't solve new form case.
