### ISSUE TITLE
Add reactstrap mention to integrationwithUIlibraries getting started

### ISSUE THREAD

**Issue by kantmichel** [react-hook-form/react-hook-form#3021]
Not sure if this belongs here, but wanted to let you know that in here, maybe you can mention that reactstrap uses "innerRef" instead of "ref" for registering. Handy for starter to know directly from the getting started. 

https://react-hook-form.com/get-started/#integratingwithuilibraries

**Comment by bluebill1049** [comment]
thanks. updated.
