### ISSUE TITLE
Controller with type="file"

### ISSUE THREAD

**Issue by VolkerSchiewe** [react-hook-form/react-hook-form#3025]
**Describe the bug**
When using a file input with a controller it returns a string instead of a FileList (behavior when using `register`)

**Codesandbox link (Required)**
https://codesandbox.io/s/headless-forest-t7wmm?file=/src/App.js

**Expected behavior**
Similar to the behavior of when using `register` I would expect the value of the filed to be a FileList

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser: chrome
- Version: 85

**Comment by rheng001** [comment]
Facing same issue

**Comment by bluebill1049** [comment]
- you don't use `register` with `Controller`, because Controller take care of the registration process
- working example with just `register`: https://codesandbox.io/s/dazzling-sea-5ph8m?file=/src/App.js
- if you want to use Controller, then you should build a controlled component which needs to sort out assign the input with value and provide file list object to react hook form as value.

**Comment by VolkerSchiewe** [comment]
Thanks for your feedback :+1: I assumed `Controller` could be used as drop-in replacement for `register` if one would like to have a controlled input.
I think I figured out how to use `Controller` with a file input: 
https://codesandbox.io/s/hungry-bas-n67j0?file=/src/App.js

The usage of `register` in the first sandbox was just a leftover, sorry for the confusion.

**Comment by bluebill1049** [comment]
no worries 👍

**Comment by Daud-Khan** [comment]
@VolkerSchiewe Hello. Can you also provide an example with applying validation rules for file type input in Controller? I am struggling with applying validations on size and type of the file uploaded. I am using Controller

**Comment by Moshyfawn** [comment]
@VolkerSchiewe you can use the `validate` controller callback to put your field size and type validation logic in:
```js
rules={{
  validate: (value) => {
    // do your validation here
    // return either true for "valid" or an error message string for the error
  }
}}
```

**Comment by Daud-Khan** [comment]
@Moshyfawn Thanks for the response. I have tried this already but the value in the validate call back is coming as undefined.

**Comment by Moshyfawn** [comment]
Any reason to not do the uncontrolled input with `register` for the native web input?
Anyway, check out [this CSB](https://codesandbox.io/s/dreamy-gauss-jebgu?file=/src/App.tsx) for an example of using `<Controller />` with input of type "file" with validation

**Comment by Daud-Khan** [comment]
@Moshyfawn It is showing me undefined value for fileList in handleSingleFileValidation function. I think there is some issue with the input I am using. I am using react bootstrap form-control with type " file".

**Comment by Moshyfawn** [comment]
Sorry, can't reproduce. See [this CSB](https://codesandbox.io/s/zealous-night-1f0h1?file=/src/App.tsx) with a RB controlled input example.
P.S. I didn't apply the Bootstrap CSS file to not break the rest of the example. So, the input has plain HTML styles + error messages aren't styled as errors.
P.P.S. There seems to be a TS issue with the `Form.Control` event type for `type='file'`, but it's on RB side, I believe. The input works as expected, tho

> Property 'files' does not exist on type 'EventTarget & FormControlElement'

**Comment by Daud-Khan** [comment]
@Moshyfawn Thank you so much for your time. I also think the issue is with the Form.Control type.

**Comment by Moshyfawn** [comment]
Np!
Well, you can make the input work as shown in [the CSB](https://codesandbox.io/s/zealous-night-1f0h1?file=/src/App.tsx). It's just that you'll need to `@ts-ignore` the `onChange` event. Unless I don't know something about RB and did something terribly wrong lol :P

**Comment by Daud-Khan** [comment]
@Moshyfawn No you did nothing wrong :p I will try this at my end. Thing is I am not using typescript. Using Plain Reactjs. I think that is why the solution is a bit different at my end. I will try to make it work :) learnt many things  💯

**Comment by zirkelc** [comment]
I switched from uncontrolled file input to a controlled one, because resetting of the file input field din't work. After submission, I was using `resetField` and `setValue('file', null)` to clean the input, but with the next submission a reference to the previous file was appearing again. Has someone else noticed issues with resetting uncontrolled file inputs?

**Comment by Moshyfawn** [comment]
Hey, @zirkelc!
Works as expected: see [this CSB](https://codesandbox.io/s/affectionate-breeze-d2epg?file=/src/App.tsx)
Do you call `resetField` and `setValue("file", null)` consecutively? If so, you should provide `defaultValues` with `file: null` set instead and call `resetField`. This should properly reset your uncontrolled file input

**Comment by zirkelc** [comment]
@Moshyfawn thank you for the example. I did call `reset` and `setValue` consecutively. Maybe that was actually the issue.

**Comment by NavizDev** [comment]
I have the following form (array), but when I click submit I have an error.

```
    const { control, handleSubmit, reset, trigger, formState: { errors, isSubmitting } } = useForm({
        mode: "onChange",
        defaultValues: {
            addresses: [{file:""}]
        }
    });

    const { fields, append, remove } = useFieldArray({
        control,
        name: "addresses"
    });
...

return fields.map(field, index => 
<Controller
      control={control}
      name={`addresses.${index}.file`}
      render={({ field }) => {
          return (
              <TextInput
                  fullWidth
                  {...field}
                  label="Subir archivo"
                  type="file"
                  onChange={(event) => field.onChange(event.target.files)}
                  InputLabelProps={{
                      shrink: true
                  }}
              />
          )
      }}
  />
)

```

error: `Uncaught DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.
    at HTMLInputElement.set [as value]`

**Comment by Moshyfawn** [comment]
Something to do with your `TextInput` component implementation, @NavizDev.
My guess, is you're trying to pass the actual File into the HTML `<input type="file" />` element by spreading `{...field}` and such input only takes in a `string` of a **file name**, **not the object** itself.

**Comment by NavizDev** [comment]
@Moshyfawn TextInput = TextField (Material UI). 
but, I already found the solution:
```
const handleChangeFile = (index, _event) => {
    setValue(`addresses[${index}].file`, _event.target.files[0])
}

...
onChange={(e) => handleChangeFile(index, e)}


```
