### ISSUE TITLE
"watch" and "getValues" methods should return deep copy of value(s)

### ISSUE THREAD

**Issue by kestas-devbridge** [react-hook-form/react-hook-form#3031]
**Describe the bug**
"watch" and "getValues" returns reference of value and allows us to mutate value directly.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-controller-forked-28qww?file=/src/index.js
2. Scroll down to date input
3. Select any date in calendar (i.e. today Sep 29)
4. Click on "Log" button and see what day is logged out in console (with example from step 3 it would be 2020-09-29)
5. Click on "Add 1 day" button and "Log" again
6. Inspect what is logged in console (with example from step 3 it would be 2020-09-30)

**Expected behavior**
"watch" and "getValues" methods should return deep copy of value(s)

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Browser Chrome
- Version 85

**Comment by bluebill1049** [comment]
you should create a deep copy at your app level.
