### ISSUE TITLE
useForm does not infer type from defaultValues starting from v6.8.2

### ISSUE THREAD

**Issue by hinsxd** [react-hook-form/react-hook-form#3032]
**Describe the bug**
Starting from v6.8.2, form methods cannot infer types from defaultValues without explicitly typing with `useForm<Type>()`

**To Reproduce**
See sandbox.

**Codesandbox link (Required)**
https://codesandbox.io/s/festive-poincare-r4lfu?file=/src/App.tsx
compare version v6.8.1 and v6.8.2

**Expected behavior**
form methods provided by useForm() should correctly infer type from `defaultValues`, as in v6.8.1.

**Screenshots**

defaultValues object
![defaultValues object](https://user-images.githubusercontent.com/8574962/94591014-125a1c00-02ba-11eb-9a88-6c67239e81d9.png)

Inferred type in v6.8.1, inside useForm parameters and form methods.
![Inferred type in v6.8.1](https://user-images.githubusercontent.com/8574962/94591070-269e1900-02ba-11eb-99b8-46260d8a2939.png)

Become a general object in v6.8.2
![v6.8.2](https://user-images.githubusercontent.com/8574962/94591101-30c01780-02ba-11eb-8173-0f056671f814.png)

- OS: macOS 10.15.7
- Browser Chrome lastest stable
- Typescript: happens in both 3.7.5 and 3.9.3

**Comment by hinsxd** [comment]
After investigation, the above behaviour is caused by an extra `Partial` wrapping the original type.
https://github.com/react-hook-form/react-hook-form/blob/0c012bb2323d6aa37ad3dc8b77cc13cc5a4c3f7b/src/types/form.ts#L77

**Comment by bluebill1049** [comment]
Thanks for the issue and investigation. would you like to send a PR? @hinsxd

**Comment by hinsxd** [comment]
I am happy to create a PR, but I am not too clear about the rationale behind the commit. 
https://github.com/react-hook-form/react-hook-form/commit/284faa0cc0bde175d3b9a3e32b59b9204e4a9c15
@bluebill1049 Is there any necessity in using Partial when you did the commit?

**Comment by bluebill1049** [comment]
thanks @hinsxd from memory the `Partial<>` as added due to default Value as empty `{}` which was used with cast `as`.

**Comment by hinsxd** [comment]
I am not sure I get it 100%. Is there a specific bug that you were trying to deal with?

**Comment by bluebill1049** [comment]
never mind, i will fix this in a pr.
