### ISSUE TITLE
When using Controller in combination with the Ant Design Radiol.group component, rules set Required to true, select false, and then commit, prompting required

### ISSUE THREAD

**Issue by hcg1023** [react-hook-form/react-hook-form#3035]
**Describe the bug**
When using Controller in combination with the Ant Design Radiol.group component, rules set Required to true, select false, and then commit, prompting required

**To Reproduce**
```
 <Controller
        render={(controllerProps) => (
          <Radio.Group
            options={options}
            onChange={(e) => controllerProps.onChange(e.target.value)}
          />
        )}
        control={control}
        name="radio"
        rules={{ required: "is required" }}
      />
```

**Codesandbox link (Required)**
[https://codesandbox.io/s/react-hook-form-useform-template-forked-olbfd?file=/src/index.js](https://codesandbox.io/s/react-hook-form-useform-template-forked-olbfd?file=/src/index.js)

**Comment by bluebill1049** [comment]
`e.target.checked`

**Comment by hcg1023** [comment]
> `e.target.checked`

I need to get its value

**Comment by hcg1023** [comment]
> `e.target.checked`
@bluebill1049 
If you use e.t.checked, the item that is checked for true will always be displayed

**Comment by bluebill1049** [comment]
then you shouldn't use `required` as validation.

**Comment by hcg1023** [comment]
> then you shouldn't use `required` as validation.

ok, thanks

**Comment by bluebill1049** [comment]
use `validate: (value) => value === 'yourValue'`
