### ISSUE TITLE
useFieldArray "append" method doest not update "fields" value

### ISSUE THREAD

**Issue by zudenkovas** [react-hook-form/react-hook-form#3036]
**Describe the bug**

**To Reproduce**

1. Go [https://codesandbox.io/s/react-hook-form-usefieldarray-forked-4tv6b?file=/src/index.js](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-4tv6b?file=/src/index.js)
2. Change the firstName in the first fields accordion
3. Click "append"
4. See console, "watch" and "getValues" methods return correct field values after "append", but fields do not. instead they return the old value. "fields" values are used in accordion header.
5. Try to "delete" or "insert", newly added accordion, now the value is updated. 

**Codesandbox link (Required)**
[https://codesandbox.io/s/react-hook-form-usefieldarray-forked-4tv6b?file=/src/index.js](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-4tv6b?file=/src/index.js)

**Expected behavior**
useFieldArray "fields" should return updated values after all field array actions including append.

**Desktop (please complete the following information):**
- OS: macOS Catalina
- Browser Chrome
- Version 85

**Comment by bluebill1049** [comment]
Reac Hook form is based on uncontrolled form, so does `useFieldArray`.

**Comment by bluebill1049** [comment]
<img width="961" alt="Screen Shot 2020-09-30 at 5 47 35 pm" src="https://user-images.githubusercontent.com/10513364/94657636-11ba9780-0345-11eb-8c19-54f64842847c.png">
