### ISSUE TITLE
Array field error type

### ISSUE THREAD

**Issue by motykadaw** [react-hook-form/react-hook-form#3037]
**Describe the bug**
Typing for array field's error assumes it is `Array<FieldError | undefined> | undefined`, when it can be just a single FieldError.

**Steps**
1. Run sandbox
2. Notice typescript error on line 51:
`helperText={errors.arrayField?.message}`
3. Click 'Submit'
4. Check out console to see that errors.arrayField is indeed of type `FieldError`

**Codesandbox link (Required)**
https://codesandbox.io/s/quirky-snowflake-iup57

**Expected behavior**
typings adhere to reality

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/eloquent-cdn-jeiry

please use NestedValue for none primitive data type for input: https://react-hook-form.com/ts#NestedValue

**Comment by motykadaw** [comment]
Well, I could have looked for something like that myself, it works indeed.
Thank You for Your quick help!

**Comment by bluebill1049** [comment]
@motykadaw soon we will have better typescript with string literal TS 4.1.0. 👍
