### ISSUE TITLE
trigger validation example need to update

### ISSUE THREAD

**Issue by codenoobforreal** [react-hook-form/react-hook-form#3038]
**Describe the bug**
trigger validation example need to update

**To Reproduce**
after click button

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-trigger-validation-w1g0m?file=/src/index.js

**Expected behavior**
no error

**Screenshots**
![image](https://user-images.githubusercontent.com/18373253/94672522-f1d8a300-0347-11eb-8bb5-309aeb83cf6e.png)

**Desktop (please complete the following information):**

- OS: windows
- Browser: Microsoft Edge
- Version 85.0.564.63

**Additional context**
I think it's awesome if you provide a search input to let us search API in your doc site
it is a little hard to find "triggerValidation" function right now.maybe it is deprecated

**Comment by bluebill1049** [comment]
where did you find that example? i will update it.

**Comment by bluebill1049** [comment]
thanks fixed, that's on V5.
