### ISSUE TITLE
Validation messages won't show up if form is using YupValidationResolver

### ISSUE THREAD

**Issue by zelucena** [react-hook-form/react-hook-form#3039]
**Describe the bug**
https://react-hook-form.com/advanced-usage/#CustomHookwithResolver
I copied / pasted yupValidationResolver from the docs and I realized my error messages weren't being displayed anymore. In the other hand, the default `validationSchema` property doesn't support nested objects (at least for v.5x).

const methods = useForm({
    defaultValues,
    reValidateMode: 'onChange',
    // validationSchema,
    validationResolver: useYupValidationResolver(validationSchema),
  });

const { errors } = methods;
// yupValidationResolver  catches and error but this object isn't updated for some reason;
console.log(errors);

**Codesandbox link (Required)**
The link for this sandbox is available on the docs. We can already see the problem there
https://codesandbox.io/s/custom-hook-with-resolver-v5-potl4?file=/src/App.js --> v.6
https://codesandbox.io/s/custom-hook-with-resolver-v5-forked-nltz2 --> v.5

**Expected behavior**
`errors` should update properly so every error message could be displayed as applicable.

I'm still using v. 5.7.2. Is there a way I can make this work or should I migrate imediately?

**Comment by zelucena** [comment]
Update: 
I worked it around by using lodash;

```
const { errors } = useFormContext();
const fieldError = _.get(errors, fieldName, false);
console.log(fieldError.message); // it works
```
This allows me to access nested error objects while calling by their flattened name.

**Comment by bluebill1049** [comment]
if you encounter issues around 5 I would recommend moving to 6. I know it's not trivial, but there are quite a few improvements done on v6 include bug fixes.
