### ISSUE TITLE
Different checking for onBlur and onSubmit

### ISSUE THREAD

**Issue by alexeenko-frontend** [react-hook-form/react-hook-form#304]
Is there possible to required check and field type check (email, phone, etc) will works when onSubmit event, and when onBlur event do only field type?

**Comment by bluebill1049** [comment]
can you explain your question with a bit more detail? possible with codesandbox example?

**Comment by alexeenko-frontend** [comment]
I can show schematically
![joxi_screenshot_1568203379728](https://user-images.githubusercontent.com/44862907/64696201-7c810280-d4a6-11e9-9a9a-33734ad3166d.png)

**Comment by bluebill1049** [comment]
isn't there is a `formState` `isValid`?

**Comment by alexeenko-frontend** [comment]
At the event onBlur, the field will be valid if it matches the rule (only letters).
And on the event onSubmit, the field will be valid if it matches the rule and required.

**Comment by bluebill1049** [comment]
> At the event onBlur, the field will be valid if it matches the rule (only letters) or is empty.
> And on the event onSubmit, the field will be valid if it matches the rule and required.

I am sorry, i don't think i understand what you after here... as much as i would like to help.

**Comment by hui21109** [comment]
I think I understand what alexeenko-frontend is asking.
there is an example:
I only want to check if the field is empty onBlur.
but I want to check additional regex rule onSubmit
I know I can implement onBlur and onSubmit separately,
but can I use one schema or something to define this behavior?

**Comment by bluebill1049** [comment]
> I think I understand what alexeenko-frontend is asking.
> there is an example:
> I only want to check if the field is empty onBlur.
> but I want to check additional regex rule onSubmit
> I know I can implement onBlur and onSubmit separately,
> but can I use one schema or something to define this behavior?

for custom validation, you probably have to set both validations (mode and reValidateMode) to `onSubmt` and trigger them manually with `trigger` API.
