### ISSUE TITLE
We can't make the proxied isSubmitting value work as expected

### ISSUE THREAD

**Issue by josoroma** [react-hook-form/react-hook-form#3040]
**The proxied isSubmitting is not working as expected (I guess)**

Not able to use the isSubmitting boolean value because is being set false before having a response from the server (promise), so I end up using:

```
 const [formLoginIsSubmitting, setFormLoginIsSubmitting] = useState(false);
```

```
                  <FormButton
                    variant="contained"
                    color="primary"
                    value="Login"
                    type="submit"
                    isSubmitting={formLoginIsSubmitting}
                    disabled={formLoginIsSubmitting}
                    fullWidth
                  />
```

Not able to make it work with:

```
const { handleSubmit, errors, control, formState: { isSubmitting } } = useForm();
```

It is being set to false before having a server response from a promise.

Not sure, but maybe... Is this a bug related to using Suspense?

**To Reproduce**

Clone this CRA repo and see this screen: https://github.com/lognllc/reacter/blob/master/src/screens/Login/index.tsx

Thank You!

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by josoroma** [comment]
@bluebill1049 my bad! Good luck!
