### ISSUE TITLE
isValid and watched do not detect values auto-populated by Chrome

### ISSUE THREAD

**Issue by mulholio** [react-hook-form/react-hook-form#3041]
**Describe the bug**
Chrome's save password features auto-populates a form when you first visit a page. Unfortunately, react-hook-form does not seem to recognise that these values are there until you click somewhere on the page which is misleading to users. For our form, where we wish to disable the submit button for empty values (we check this using `isValid` from form state), this makes it look like the form is disabled.

![image](https://user-images.githubusercontent.com/20966690/94712197-0b2a2100-0341-11eb-87bd-868498b23005.png)

**To Reproduce**

0. Save a password for your site using Chrome's save password feature.
1. Refresh the page your form is on. The name and password should be auto-populated.
2. Log your values with `watched` or check the value of `isValid`. Neither of these recognise that the form has been populated.

**Codesandbox link (Required)**

Unfortunately, Chrome's save password feature doesn't seem to work in CodeSandbox.

**Expected behavior**
Auto-populated values are detected immediately.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome (but maybe others)
- Version 85.0

**Comment by bluebill1049** [comment]
Don't think this is anything we can do.

**Comment by mulholio** [comment]
> Don't think this is anything we can do (browser level).

As this is a pretty commonly used feature for users, do you have any pointers on where to look to fix this?

**Comment by bluebill1049** [comment]
> > Don't think this is anything we can do (browser level).
> 
> As this is a pretty commonly used feature for users, do you have any pointers on where to look to fix this?

It's browser level stuff, but you can turn it off with autoComplete="false" other than that, there is nothing we can do at JS level.

https://stackoverflow.com/questions/11708092/detecting-browser-autofill
