### ISSUE TITLE
`unregister(...)` optional shouldDirty configuration parameter

### ISSUE THREAD

**Issue by Frantss** [react-hook-form/react-hook-form#3045]
**Is your feature request related to a problem? Please describe.**
I'm trying to unregister inputs and have them not affect the `isDirty` and `dirtyFields` properties.
Currently, after an input is unregistered, it sets `isDirty` to `true`.

**Describe the solution you'd like**
`unregisters` takes a second argument of type `{ shouldDirty: boolean }`.
This will be a non-braking change, and also provide future proof if more configs need to be added.

**Describe alternatives you've considered**
Having a `removeInput` function that removes all references to the input from the state.

**Comment by bluebill1049** [comment]
proposal: 

```ts

```
