### ISSUE TITLE
v6.8.5 seems to have regressed #2691

### ISSUE THREAD

**Issue by ZachMayry** [react-hook-form/react-hook-form#3047]
Copying from https://github.com/react-hook-form/react-hook-form/issues/2652

**Describe the bug**
When setting `shouldUnregister` on a form, `useFieldArray` still unregisters and clears all the values when it remounts.

**To Reproduce**

1. Go to codesandbox link
2. Click on append
3. Add a value
4. Click on unmount
5. Click on mount
6. See error

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-pgfif?file=/src/index.js

**Expected behavior**
Values entered in step 2 & 3 should be retained

**Desktop:**
MacOS
Firefox 80.0b7
Chrome 84.0.4147.125

**Comment by ZachMayry** [comment]
Link to the PR where this should have been fixed https://github.com/react-hook-form/react-hook-form/pull/2691
In the codesandbox you can see that v6.8.4 works correctly, but v6.8.5 does not

**Comment by bluebill1049** [comment]
nope, not the entire `FieldArray`, it's only field level with shouldUnregister:false.

**Comment by ZachMayry** [comment]
Is the question for me?

**Comment by bluebill1049** [comment]
no, read my answer above.

**Comment by ZachMayry** [comment]
This worked as of 6.8.4 as you had fixed it for 6.8.0. Now it no longer works.

**Comment by bluebill1049** [comment]
> This worked as of 6.8.4 as you had fixed it for 6.8.0. Now it no longer works.
> 
> I don’t understand your answer

That's why it's important to leave those important detail in the issue in the first place, I can't read your mind.

**Comment by bluebill1049** [comment]
nvm, i miss this message
![Uploading Screen Shot 2020-10-02 at 10.53.06 am.png…]()

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/commit/35b38907116dd8470390b3d72e4ef9bb13ef3391

**Comment by ZachMayry** [comment]
My bad. I made the title with the PR number that has regressed and copied the original issue. I’ll add these details next time.

**Comment by ZachMayry** [comment]
Thanks for the quick fix!
