### ISSUE TITLE
Overriding DefaultValues if form is dirty

### ISSUE THREAD

**Issue by warrenmcquinn** [react-hook-form/react-hook-form#305]
**Describe the bug**
When using `register` to provide DefaultValues to an input, it's possible that the input component will be removed from the virtual DOM and eventually re-added. Upon re-rendering, `register` will initialize the input as the DefaultValue, even if the form state has been changed (dirty) 

**Expected behavior**
`register` could be able to use the most recent form state, instead of reverting to DefaultValues.

**Comment by bluebill1049** [comment]
what do you mean to register with defaultValue? Like the example below?

`<input name="test" defaultValue="xxx" ref={regsiter} />`?

No, the state remain the same with re-render.

**Comment by marracheco** [comment]
@warrenmcquinn I ran into this problem in a multipart/wizard-type form where registered fields were being mounted and unmounted. I ended up registering the fields in the main form component via `useEffect`. That way the registration of the fields aren't tied to the fields themselves and are still accessible through the form context.

**Comment by bluebill1049** [comment]
@marracheco this is how we building wizzard form at work
```
const { register, handleSubmit, errors, setValue, watch } = useForm({ submitFocusError: false });

const onSubmit = step => data => {
    actions.updateCalculatorDataAction(data);
    actions.updateCalculatorStepsAction({
      [step]: true,
      currentStep: currentStep + 1,
    });
  };

const commonProps = { onSubmit, register, handleSubmit, calculatorData, errors, setValue, 
watch };

const section = () => {
    switch (currentStep) {
      case 0:
        return <BorrowingPowerCalculatorLoan {...commonProps} />;
      case 1:
        return <BorrowingPowerCalculatorIncome {...commonProps} />;
      case 2:
        return <BorrowingPowerCalculatorExpenses {...commonProps} />;
      case 3:
        return <CalculatorDemoPage4 {...commonProps} />;
      default:
        return <BorrowingPowerCalculatorLoan {...commonProps} />;
    }
  };

  return (
    <>
      {section()}
    </>
  );
```

Each page renders itself and during submission, it will update the data in the store.

**Comment by bluebill1049** [comment]
going to close this issue for now, if you have more questions feel free to reopen. i will probably do a wizard form example soon.

**Comment by marracheco** [comment]
@bluebill1049 I appreciate your response and the wizard sample. My needs are a little more complex, but I still really like your approach.

As far as the wizard example, I'd love to help out.

**Comment by bluebill1049** [comment]
@marracheco would you like to send a PR for your Wizzard example? we can have it under example folder. (keep it simple so devs can pick up the idea)
