### ISSUE TITLE
Bug when setState with value 0

### ISSUE THREAD

**Issue by rafaelbrier** [react-hook-form/react-hook-form#3057]
Hello,

When we try to set a input field with the number value 0, it does not work.

setValue('name', 0) -> does not work
setValue('name', '0') -> works

I suppose there's a place where a condition check considers the number 0 as false. Shouldn't this condition check only for null and undefined?

The same happens with the defaultValues and reset when one of the values is the number 0.

**Comment by risardi123** [comment]
First, please follow the rule to get fast response from the maintainer https://github.com/react-hook-form/react-hook-form/issues/2848#issue-695426528 for respect their time.
