### ISSUE TITLE
Default values are invalid but isValid is true and errors is {} when mode is 'onChange'

### ISSUE THREAD

**Issue by vangelov** [react-hook-form/react-hook-form#3058]
**Describe the bug**
Both default values are invalid according to the scheme but when the form renders `isValid` is `true` and `errors` object is `{}`. If one of the fields is edited `isValid` becomes `false`, but errors is still `{}`

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-forked-qzxl8?file=/src/index.js
2. View the logs
3. isValid is true, although the firstName field is marked as required and is empty by default

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-qzxl8?file=/src/index.js

**Expected behavior**
isValid should be false if the default values are not valid

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Safari
- Version 0.14

**Comment by risardi123** [comment]
Hello, @vangelov please use this schema. the default will return false. is it what you expect?
```
const schema = object().shape({
  test: array()
    .of(
      object().shape({
        firstName: string().required(),
        lastName: string()
      })
    )
    .required("field array is required")
})
```

**Comment by vangelov** [comment]
Just tried it, but I'm getting still getting isValid: true. Yes, I think think the form should not be valid if the default values are not. Even when the mode is onChange

**Comment by bluebill1049** [comment]
Thanks, @risardi123 🙏 the fix is coming.
