### ISSUE TITLE
It would be convenient if the input would restore its state after conditional rendering

### ISSUE THREAD

**Issue by SoEasy** [react-hook-form/react-hook-form#3059]
Hello!

If I use conditional rendering with some input, when input will be destroyed - form state lost them value.
And when input became rendered to DOM - obviously input has no data.

I think it will be cool if inputs dont loose their values after remounting.

Code example for illustrate:
```
import React, { useState } from "react";
import { useForm } from "react-hook-form";

export default function App() {
  const [isVisible, setIsVisible] = useState(true);
  const { register, watch } = useForm();

  const name = watch("firstName");
  return (
    <div className="App">
      {name}

      {isVisible && (
        <input name="firstName" ref={register()}/>
      )}

      <button onClick={() => setIsVisible((v) => !v)}>toggle</button>
    </div>
  );
}
```

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#useForm

![Uploading Screen Shot 2020-10-02 at 8.23.22 am.png…]()
