### ISSUE TITLE
Pattern with a /g flag causes issues

### ISSUE THREAD

**Issue by davorbadrov-toptal** [react-hook-form/react-hook-form#3060]
**Describe the bug**

First I'd like to say that I really love your lib and the docs are amazing. Great job :+1: 

Not sure if this is something to be considered a bug, but today I lost quite some time with this.

I kept getting a validation error even if my input was valid.

It happens when you use the `/g` flag in your Regex pattern, e.g. `/^\S+@\S+\.\S+$/g` instead of `/^\S+@\S+\.\S+$/`.

It's triggered when I keep adding characters to the end of a valid input. With the `/g` flag Regex remembers the state of the last match and it causes validations to fail occasionally.

**To Reproduce**

1. Go to https://codesandbox.io/s/async-monad-hesv9?file=/src/App.js
2. In the app, you can first click on the Submit button to trigger the validation message
3. In the input start typing "a@b.com"
3. There should be no error message visible for "a@b.com"
4. Continue typing `m`s into the input: a@b.comm, a@b.commm, a@b.commmm, and so on
4. You'll notice the error appearing every so often even if the input passes validation.

**Codesandbox link (Required)**

https://codesandbox.io/s/async-monad-hesv9?file=/src/App.js

**Expected behavior**

I expect that after typing in a valid pattern, and after I continue adding letters to the valid pattern (it keeps being valid) that the error message isn't visible. 

Because of the Regex pattern both a@b.com and a@b.commmmm should be valid. And no matter how many 'm's I add, it should still be considered valid.

**Desktop (please complete the following information):**

Tried with Chromium and Firefox:

- OS: Fedora 32
- Browser: Chromium 
- Version: 85.0.4183.102

- OS: Fedora 32
- Browser: Firefox 
- Version: 81.0

**Additional context**

Do note that the form can still be submitted, even if the error message is visible.

The problem is the  /g flag because that regex keeps the state/last position of the match so calling it multiple times returns true/false/true/false etc.

This isn't really related to your lib but the way Regex behaves, but maybe an note in the docs could help someone in the future.
Or a error/warning that checks the patterns, something like
```
if (patternValue.flags.includes('g')) {
  console.warn("You set a Regex pattern with the /g flag in your Regex. It will cause issues with validation, remove it to fix your pattern.");
}
```

**Comment by risardi123** [comment]
I don't know if it can solve your problem, instead arguing with the pattern, why you just find any regex pattern like this one?
`/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i`

**Comment by bluebill1049** [comment]
I wouldn't see that's a bug https://stackoverflow.com/questions/1520800/why-does-a-regexp-with-global-flag-give-wrong-results , i will update the doc to leave a small note.

**Comment by bluebill1049** [comment]
<img width="990" alt="Screen Shot 2020-10-02 at 10 47 09 am" src="https://user-images.githubusercontent.com/10513364/94877002-a1bf2500-049c-11eb-8734-f06a9b765103.png">
