### ISSUE TITLE
The resolver function is called many times with invalid data 

### ISSUE THREAD

**Issue by vangelov** [react-hook-form/react-hook-form#3066]
**Describe the bug**
The resolver function is called for each controller that is nested at least one level deep. Further more the values passed as a param do not contain all fields (each new call to the resolver function adds a new field). This causes the validation to run a large number of times (proportional to the number of Controllers in the form).

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-forked-qzxl8?file=/src/index.js
2. See the log
3. You will see the fields in level2 subform are added one by one

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-qzxl8?file=/src/index.js

**Expected behavior**
I think the resolver should be called once on the first render with every field of the default values.

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser Safari
- Version 14.0

**Comment by vangelov** [comment]
Just noticed that if level2 is implemented as a field array the problem disappears. Am I misunderstanding something here? More specifically: does react-hook-form actually support subforms or I'm using it wrong?

**Comment by bluebill1049** [comment]
Thanks for the bug report. I am pretty this is expected as we need to validate the result against the resolver or schema. also, your codesandbox is broken.

**Comment by vangelov** [comment]
Hey, what's the the issue with the codesandbox link? I'm able to open it without an issue in incognito mode. Why is this expected? I mean why add each field separately when validating? 
If you have a schema containing .when() that references a sibling property in yup there will be a lot cases where the result will be invalid, although the data is actually correct.

**Comment by bluebill1049** [comment]
> Hey, what's the the issue with the codesandbox link? I'm able to open it without an issue in incognito mode.

It's broken when I clicked on the link.

**Comment by bluebill1049** [comment]
> If you have a schema containing .when() that references a sibling property in yup there will be a lot cases where the result will be invalid

react hook form is focused on field level when you interact with each input, if you want to validate depend on field, you should use tirgger.

**Comment by bluebill1049** [comment]
> Plus it's just unnecessary to run validation for each Controller. Maybe I'm missing something?

then how do you isolate each field against an entire schema validation? unless I miss something. all those validation libs out there (controller form) percent the entire form data to validate against the schema on each keystroke, if you are going to argue unnecessary work, then hook form is already making a step to improve.

**Comment by vangelov** [comment]
I think I'm not explaining it well. 

I mean that during the first render the resolver function is called N times if you have N Controllers that are nested at least one level without interacting with the form at all. What error are you getting with code sandbox? I'm able to open it in every browser. https://codesandbox.io/s/react-hook-form-usefieldarray-forked-qzxl8

**Comment by bluebill1049** [comment]
> I think I'm not explaining it well.
> 
> I mean that during the first render the resolver function is called N times if you have N Controllers that are nested at least one level without interacting with the form at all. What error are you getting with code sandbox? I'm able to open it in every browser. https://codesandbox.io/s/react-hook-form-usefieldarray-forked-qzxl8

oh, that's incorrect. thanks

**Comment by bluebill1049** [comment]
<img width="576" alt="Screen Shot 2020-10-03 at 9 28 35 am" src="https://user-images.githubusercontent.com/10513364/94977147-d1ccfd80-055a-11eb-9b5b-00ef982cfa69.png">

what I got before, it's fixed now tho.

**Comment by vangelov** [comment]
Hmm, that's really strange. I haven't changed a thing

**Comment by bluebill1049** [comment]
<img width="1041" alt="Screen Shot 2020-10-03 at 9 36 55 am" src="https://user-images.githubusercontent.com/10513364/94977417-fc6b8600-055b-11eb-8db6-00b0c74c849b.png">

I am so confused... is it something wrong with CSB? i remove everything, still inputs r rendered and so does the console.log

**Comment by bluebill1049** [comment]
investigating...

**Comment by bluebill1049** [comment]
This is expected: I am confused with the `console.log` in the codesandbox and thought it was in the render. 

So here is the reason why, because `defaultValue` can be potentially inline right? so **first render** we will have to check on the validation on each input until it encounters an invalid input and update the isVald formState, but there is a small room to improve which validation could be stopped after finding an inValid input.

**Comment by bluebill1049** [comment]
think twice, i probably should move that logic into `useEffect`, will give it a try during the weekend.

**Comment by vangelov** [comment]
But why is it necessary to call the resolver function so many times in the first render? Why not call it just once with all the data in the first render?

**Comment by vangelov** [comment]
I updated my example to latest version (6.9.0) but the resolve  function is still called 4 times (the same count as the controllers). What if there are 50 controllers in form?  Isn't this going to be a huge performance issue?

**Comment by vangelov** [comment]
> So here is the reason why, because `defaultValue` can be potentially inline right? so **first render** we will have to check on the validation on each input until it encounters an invalid input and update the isVald formState, but there is a small room to improve which validation could be stopped after finding an inValid input.

Ok, you've actually explained the reason. Here's an example why this is still an issue: If you have a giant form for editing an item it's going to valid during the first time in renders, i.e. there will be no invalid fields to stop the validation early. If this form has 100 Controllers the validation is going to be called 100 times slowing the initial render considerably.

**Comment by wns3645** [comment]
Hi, I think this is resolved with latest version(7.10). 
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-jz8z3?file=/src/index.js
-> resolver is called only once.

However, It has still issue when the default value is automatically registered. The resolver is called until all default value is automatically registered into form state. 
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-ppbpw?file=/src/index.js
![image](https://user-images.githubusercontent.com/12604726/124545395-ecbefc00-de63-11eb-8db3-5d7858b51ca3.png)
-> I think there are 4 default values should be hiddenly registered, so the resolver is called 1 + 4 times.
