### ISSUE TITLE
Allow controller to accept onChange, and onBlur

### ISSUE THREAD

**Issue by allforabit** [react-hook-form/react-hook-form#3067]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use `onChange` and `onBlur` with the controller component when using the `as` syntax.

**Describe the solution you'd like**
The internal `onChange` and `onBlur` props should check if these have been passed in as props and if so call them after running their code.

**Describe alternatives you've considered**
Using the render prop. I really like the as syntax though because it's much smaller and neater.

**Comment by allforabit** [comment]
I can work on a PR for this if it seems like a good idea :-)

**Comment by bluebill1049** [comment]
no, please use `render` instead. we did this in v5 and not going back.

**Comment by allforabit** [comment]
Out of interest did it cause some technical issues? E.g. Type issues? I'll use the power controller idea from the docs to implement something similar. 

Sorry for all the feature requests and questions, just thing to get stuck and really understand the library. It takes a big change in thinking coming from the more state based approaches to form management.

**Comment by bluebill1049** [comment]
> Out of interest did it cause some technical issues? E.g. Type issues? I'll use the power controller idea from the docs to implement something similar.

yes, that's correct mate :) smart 👍 also it's not flexible enough as `render`

**Comment by bluebill1049** [comment]
> Sorry for all the feature requests and questions, just thing to get stuck and really understand the library. It takes a big change in thinking coming from the more state based approaches to form management.

no man, you don't need to apologize for that, I am happy to see those feature requests coming and assign them to accordingly, and don't hesitate to ask questions as well. ❤️

**Comment by allforabit** [comment]
Ah thanks very much and thanks for all the work on the library!
