### ISSUE TITLE
Controlled component no longer updating display value (react-datepicker)

### ISSUE THREAD

**Issue by tophergd** [react-hook-form/react-hook-form#3072]
**Describe the bug**
Between version 5.7.2 and 6.0.0 something breaks where the input value is no longer being shown in the component's input box after changing the date-picker value. 

**To Reproduce**
In the Codesandbox example below you can see the issue by swapping between these versions. I couldn't see anything in the docs to suggest doing anything different between these versions in terms of usage.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-forked-nck0j?file=/src/index.js

**Expected behavior**
I expect to see the newly selected date show in the input field after changing the date in react-datepicker.

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version 85.0.4183.121

**Additional context**

**Comment by bluebill1049** [comment]
please refer to the changelog and use `render` props for Contorller (if `as` prop is no longer working, and many props have been removed): https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md
