### ISSUE TITLE
Yup resolver does not validate correctly

### ISSUE THREAD

**Issue by vangelov** [react-hook-form/react-hook-form#3082]
The problem is that the resolver is called with the data that has changed. However, the schema passed as an argument is the original one and it validates all the fields, not just the changed ones. So the resolver returns an error, but it should not. 

Here's an example: https://codesandbox.io/s/react-hook-form-usefieldarray-forked-bltsh?file=/src/index.js

If you add a new field by clicking 'APPEND' the resolver will returns an error as the required field 'age' is not part of the data. But the form is actually valid. 

Is this supposed to be supported or I should write a custom resolver in this case?

**Comment by vangelov** [comment]
I think the problem is with my code. 
If you change name={`level2.level3.array[0].firstName`} to name={`level2.level3.array[${index}].firstName`} it seems ok.

**Comment by bluebill1049** [comment]
nah @vangelov it's a bug, i am patching it. thanks for reporting the issue 👍

**Comment by vangelov** [comment]
Just noticed that if you delete the last item in the field array the resolver is again called with missing fields. Not sure if that's fixed in the commit above.
