### ISSUE TITLE
[bug] isDirty is false after the input is changed inside a Submit function

### ISSUE THREAD

**Issue by ssuvorov** [react-hook-form/react-hook-form#3086]
### Bug 
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-vtnng?file=/src/index.js

0. Console must be opened
1. Modify input
2. submit

**Expected** 
`isDirty` is `true`

**Actual**
`isDirty` is `false`

- Version 6.9.0

If you first submit, then modify input and submit again, then `isDirty` is true.

**Comment by bluebill1049** [comment]
make sure your read those formState at render: https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-fj8i4

**Comment by ssuvorov** [comment]
@bluebill1049 Thanks for your reply. Yeah, I noticed that if I console.log it at rendering it changes also in submit. But isn't it a bug? 

I'd like to make an artificial delay when the form is dirty & valid before executing a submit function in `handleSubmit`. Any way to pass an updated **formState** into handleSubmit? I don't need it in a render.

**Comment by bluebill1049** [comment]
<img width="947" alt="Screen Shot 2020-10-06 at 6 45 58 pm" src="https://user-images.githubusercontent.com/10513364/95173276-2e9f1100-0804-11eb-9e2b-28c6d9f942a2.png">

**Comment by bluebill1049** [comment]
`const {formState: {isDrity}} = useForm()` you can read in inline as well, so hook form know you are subscribed tt the formState of `isDirty`.

**Comment by isaidavidvelez47** [comment]
If you are changing the form value with `setValue`, you must add this object as the third parameter

`setValue('key', value, { shouldDirty: true })`
