### ISSUE TITLE
useForm<T> expects `defaultValues` to be `T`, not a partial of T

### ISSUE THREAD

**Issue by wendorf** [react-hook-form/react-hook-form#3088]
**Describe the bug**
In v3.9.0, when useForm is given a type T, the defaultValues property must include keys for all members of type T, and cannot omit keys of T that are not optional. This is a regression from v6.8.6, and I think it is due to https://github.com/react-hook-form/react-hook-form/pull/3062/files

**To Reproduce**

```
interface FormValues {
  name: string;
}

useForm<FormValues>({
  defaultValues: {
    name: Math.random() < 0.5 ? "" : undefined,
  },
});
```

This will give the compile error: `Type 'string | undefined' is not assignable to type 'string'.`

```
interface FormValues {
  name: string;
}

useForm<FormValues>({
  defaultValues: {
    name: "",
  },
});
```

This will give the compile error: `Property 'location' is missing in type '{ name: string; }' but required in type 'FormValues'.`

**Codesandbox link (Required)**

I forked the `useForm` Codesandbox link and switched it to using TypeScript and newer dependencies. However, I was unable to reproduce the compile issue with Codesandbox, which is a bit confusing.

https://codesandbox.io/s/react-hook-form-useform-template-forked-pqgkx?file=/src/index.tsx is my codesandbox that confusingly does _not_ show the issue. I'm happy to close this bug report if there's something wrong with my setup, but I can't figure out what is different between my setup and the codesandbox that causes it to only break for me locally.

**Expected behavior**

`defaultValues` that omit some properties of T, or provide a `U | undefined` for a property of T that is of type U, should be accepted.

**Desktop (please complete the following information):**

- OS: macOS 10.15.7
- Browser: not applicable

**Additional context**

My local compilation process is triggered by `react-scripts start` ([react-scripts](https://www.npmjs.com/package/react-scripts))

**Comment by bluebill1049** [comment]
your codesandbox is not throwing errors, it's a deep partial in the type. 

`defaultValues: UnpackNestedValue<DeepPartial<TFieldValues>>;`

**Comment by wendorf** [comment]
@bluebill1049 Yeah, I'm not sure why the codesandbox is not throwing errors but my local environment is. Things seem to be the same. All I know is the bump from v3.8.6 to v3.9.0 caused me to start getting those errors, so we're currently locking to v3.8.x

**Comment by Fakkio** [comment]
+1 Same problem here

**Comment by bluebill1049** [comment]
which version of TS you guys are using?

**Comment by dolma** [comment]
The code in this PR was changed from `defaultValues = {}` to `defaultValues = {} as UnpackNestedValue<DeepPartial<TFieldValues>>`. Same thing but with an added type assertion.

Clearly providing `{}` for the `defaultValues` was working before that change but the added type assertion in this line proves that removing `Partial` from the type definition just messed things up. Otherwise the additional assertion wouldn't be needed.

**Comment by dolma** [comment]
And before you ask, yes I saw the discussion about removing that `Partial`. Clearly it was added for a reason in the first place. May not have been the best solution for the problem at the time but still worked. Simply removing it isn't imho a fix either because it invalidates the original fix and brings back the initial issue you were trying to solve. So back to square 1 (which is what's causing this issue now)

**Comment by bluebill1049** [comment]
@wendorf Tested on 3.9.2 and let me know if you can reproduce this in a git repo, happy to take a look at it. 

https://www.typescriptlang.org/play?ts=3.9.2#code/CYUwxgNghgTiAEYD2A7AzgF3gEgHIkxGADUoIBXEALnnJQEsBHS+NATwFsAjJCAbgBQAkAA8ADkhhYMbMQgAiIEGIAKsDPTIAeACoA+eAF54O+KIwgUwNPACCMGFDZb6KAGYgY8AKp6B8eAB+OwcnLUVlNSlNCC1fPwCaU3NLa3gAJRAoYFQINntHZ1cPL19-IIysnJQ8grCI1XUYuL0E+CSzEQsrG0zkGGAtTBhXAHMAGloUAGsUJAB3FDbggG9ygICAbQBpeFd4aZA2JDcTAF1AmgaojW0dHbO9QQ34AF9ypMFhcUlpWQR8IQSGRKFpyjpSBQECkelNZgsUJszvAAD6VfqDYZjSZ0eGLAyGdaouFzRZIolovqSTEYEYoCYkhF+AnwNZbPAECzAqFnGgoEAAN08gle8AAZCZIZQvqIJFJ4DI5D4UGIoGBpoCuVKQLoWckuqkbJqiNqXO5PD5lj4PiZOt00vIoBZiQAxegQEAAGXomHKwR0Nv19t64GpQ1p2MZ+L9rPgOz2KAORxO5xo3hVao1nJNIJ1922jzega+5UVCB0nKMrPeATLJk5AEYq2yNm56DBMLgoBxqKwI-TxkToJ3u72sQPyjWFf965gAEzNoltjsYLs9mjjiZDqAj9d9ulbl78oE0FsvZe7sf9w8veDD1ejjfXwcvKfvUszgDy5AwYh-TeMdNVXVY1uVBa4mjuTlWg-JVv1-H8F0AjMQOzMCdQg6IoMwBsYNrL8fz-DAAGYqyAzNQNNTDbliCt5xgoQgA

**Comment by dolma** [comment]
> which version of TS you guys are using?

tried updating to the latest TS version just in case (v4.0.3 as I'm writing this) and it didn't help unfortunately

**Comment by bluebill1049** [comment]
@dolma can you help to try to reproduce the issue in here? 

https://www.typescriptlang.org/play?ts=3.9.2#code/CYUwxgNghgTiAEYD2A7AzgF3gEgHIkxGADUoIBXEALnnJQEsBHS+NATwFsAjJCAbgBQAkAA8ADkhhYMbMQgAiIEGIAKsDPTIAeACoA+eAF54O+KIwgUwNPACCMGFDZb6KAGYgY8AKp6B8eAB+OwcnLUVlNSlNCC1fPwCaU3NLa3gAJRAoYFQINntHZ1cPL19-IIysnJQ8grCI1XUYuL0E+CSzEQsrG0zkGGAtTBhXAHMAGloUAGsUJAB3FDbggG9ygICAbQBpeFd4aZA2JDcTAF1AmgaojW0dHbO9QQ34AF9ypMFhcUlpWQR8IQSGRKFpyjpSBQECkelNZgsUJszvAAD6VfqDYZjSZ0eGLAyGdaouFzRZIolovqSTEYEYoCYkhF+AnwNZbPAECzAqFnGgoEAAN08gle8AAZCZIZQvqIJFJ4DI5D4UGIoGBpoCuVKQLoWckuqkbJqiNqXO5PD5lj4PiZOt00vIoBZiQAxegQEAAGXomHKwR0Nv19t64GpQ1p2MZ+L9rPgOz2KAORxO5xo3hVao1nJNIJ1922jzega+5UVCB0nKMrPeATLJk5AEYq2yNm56DBMLgoBxqKwI-TxkToJ3u72sQPyjWFf965gAEzNoltjsYLs9mjjiZDqAj9d9ulbl78oE0FsvZe7sf9w8veDD1ejjfXwcvKfvUszgDy5AwYh-TeMdNVXVY1uVBa4mjuTlWg-JVv1-H8F0AjMQOzMCdQg6IoMwBsYNrL8fz-DAAGYqyAzNQNNTDbliCt5xgoQgA

**Comment by dolma** [comment]
@wendorf try declaring your `FormValues` definition as a type instead. Worked for me.

Although this is not a solution, just a temporary fix.

**Comment by bluebill1049** [comment]
> @bluebill1049
> 
> ok I think I know what the issue is. Looks like one of the custom types (either UnpackNestedValue or DeepPartial) just doesn't work with interfaces. With equal definitions, the version declared as a Type works with `{}` but not the one declared as an interface. See this playground:
> 
> https://www.typescriptlang.org/play?ts=3.9.2#code/CYUwxgNghgTiAEYD2A7AzgF3gEgHIkxGADUoIBXEALnnJQEsBHS+NATwFsAjJCAbgBQAkAA8ADkhhYMbMQgAiIEGIAKsDPTIAeACoA+eAF54O+KIwgUwNPACCMGFDZb6KAGYgY8AKp6B8eAB+OwcnLUVlNSlNCC1fPwCaU3NLa3gAJRAoYFQINntHZ1cPL19-IIysnJQ8grCI1XUYuL0E+CSzEQsrG0zkGGAtTBhXAHMAGloUAGsUJAB3FDbggG9ygICAbQBpeFd4aZA2JDcTAF1AmgaojW0dHbO9QQ34AF9ypMFhcUlpWQR8IQSGRKFpyjpSBQECkelNZgsUJszvAAD6VfqDYZjSZ0eGLAyGdaouFzRZIolovqSTEYEYoCYkhF+AnwNZbPAECzAqFnGgoEAAN08gle8AAZCZIZQvqIJFJ4DI5D4UGIoGBpoCuVKQLoWckuqkbJqiNqXO5PD5lj4PiZOt00vIoBZiQAxegQEAAGXomHKwR0Nv19t64GpQ1p2MZ+L9rPgOz2KAORxO5xo3hVao1nJNIJ1922jzega+AkVCB0nIAjEZWe8yyZOQAmGts+BuegwTC4KAcaisCP08blaBdnt9rGDgR1-4NzAAZhb5XbnYw3d7NAnE2HUFH6-7dK3AX5QJorYCy9344Hh42I9XY4316HAXe71cFhgbjV5c5AEkUB+X5gAgrYXvee6bs+8B3muV4HkO7yljOADy5AYGIaHVsY6aquqxrcqC1xNHcVatEhSqoehaHNthGZ4dmBE6kR0QkZgjZkfWlEYRgC60bhWZAqazG3LEFbzhxKFodx-6Ad+NY4Zm+FCUojQsaJf4AZ4QEgGRAjIOgWBIFJmFiRgNBcZhLavII+mYPARlURgjameZxlOVZNmoHZDncXOLnwBZPEeXpXmGW5Mlad+-mBRFn5ycYKzWUAA

oh....🤔

**Comment by bluebill1049** [comment]
> @bluebill1049
> 
> ok I think I know what the issue is. Looks like one of the custom types (either UnpackNestedValue or DeepPartial) just doesn't work with interfaces. With equal definitions, the version declared as a `type` works with `{}` but not the one declared as an `interface`. See this playground:
> 
> https://www.typescriptlang.org/play?ts=3.9.2#code/CYUwxgNghgTiAEYD2A7AzgF3gEgHIkxGADUoIBXEALnnJQEsBHS+NATwFsAjJCAbgBQAkAA8ADkhhYMbMQgAiIEGIAKsDPTIAeACoA+eAF54O+KIwgUwNPACCMGFDZb6KAGYgY8AKp6B8eAB+OwcnLUVlNSlNCC1fPwCaU3NLa3gAJRAoYFQINntHZ1cPL19-IIysnJQ8grCI1XUYuL0E+CSzEQsrG0zkGGAtTBhXAHMAGloUAGsUJAB3FDbggG9ygICAbQBpeFd4aZA2JDcTAF1AmgaojW0dHbO9QQ34AF9ypMFhcUlpWQR8IQSGRKFpyjpSBQECkelNZgsUJszvAAD6VfqDYZjSZ0eGLAyGdaouFzRZIolovqSTEYEYoCYkhF+AnwNZbPAECzAqFnGgoEAAN08gle8AAZCZIZQvqIJFJ4DI5D4UGIoGBpoCuVKQLoWckuqkbJqiNqXO5PD5lj4PiZOt00vIoBZiQAxegQEAAGXomHKwR0Nv19t64GpQ1p2MZ+L9rPgOz2KAORxO5xo3hVao1nJNIJ1922jzega+AkVCB0nIAjEZWe8yyZOQAmGts+BuegwTC4KAcaisCP08blaBdnt9rGDgR1-4NzAAZhb5XbnYw3d7NAnE2HUFH6-7dK3AX5QJorYCy9344Hh42I9XY4316HAXe71cFhgbjV5c5AEkUB+X5gAgrYXvee6bs+8B3muV4HkO7yljOADy5AYGIaHVsY6aquqxrcqC1xNHcVatEhSqoehaHNthGZ4dmBE6kR0QkZgjZkfWlEYRgC60bhWZAqazG3LEFbzhxKFodx-6Ad+NY4Zm+FCUojQsaJf4AZ4QEgGRAjIOgWBIFJmFiRgNBcZhLavII+mYPARlURgjameZxlOVZNmoHZDncXOLnwBZPEeXpXmGW5Mlad+-mBRFn5ycYKzWUAA

Apply `Partial` fix the issue: https://www.typescriptlang.org/play?ts=3.9.2#code/CYUwxgNghgTiAEYD2A7AzgF3gEgHIkxGADUoIBXEALnnJQEsBHS+NATwFsAjJCAbgBQAkAA8ADkhhYMbMQgAiIEGIAKsDPTIAeACoA+eAF54O+KIwgUwNPACCMGFDZb6KAGYgY8AKp6B8eAB+OwcnLUVlNSlNCC1fPwCaU3NLa3gAJRAoYFQINntHZ1cPL19-IIysnJQ8grCI1XUYuL0E+CSzEQsrG0zkGGAtTBhXAHMAGloUAGsUJAB3FDbggG9ygICAbQBpeFd4aZA2JDcTAF1AmgaojW0dHbO9QQ34AF9ypMFhcUlpWQR8IQSGRKFpyjpSBQECkelNZgsUJszvAAD6VfqDYZjSZ0eGLAyGdaouFzRZIolovqSTEYEYoCYkhF+AnwNZbPAECzAqFnGgoEAAN08gle8AAZCZIZQvqIJFJ4DI5D4UGIoGBpoCuVKQLoWckuqkbJqiNqXO5PD5lj4PiZOt00vIoBZiQAxegQEAAGXomHKwR0Nv19t64GpQ1p2MZ+L9rPgOz2KAORxO5xo3hVao1nJNIJ1922jzega+AkVCB0nIAjEZWe8yyZOQAmGts+BuegwTC4KAcaisCP08blaBdnt9rGDgR1-4NzAAZhb5XbnYw3d7NAnE2HUFH6-7dK3AX5QJorYCy9344Hh42I9XY4316HAXe71cFhgbjV5c5AEkUB+X5gAgrYXvee6bs+8B3muV4HkO7yljOADy5AYGIaHVsY6aquqxrcqC1xNHcVatEhSqoehaHNthGZ4dmBE6kR0QkZgjZkfWlEYRgC60bhWZAqazG3LEFbzhxKFodx-6Ad+NY3M0wnNGJGAyZ4QEgGRAjIOgWBIFJmEqTQXGYS2ryCDpmDwPpVEYI2RnwCZdlmRZqBWTZ3Fzg5Tm8bWrm6dZBmqQB6nft5QVqZ+cnGCs5lAA

**Comment by dolma** [comment]
yeah well that was the state of the `defaultValue` type before the change so we already know it works.

But surely it should work with both types and interfaces equally without needing to add `Partial` on the consumer end. Either adding it in the library types (as it was before the change) or ideally figure out why it's behaving differently between the two

**Comment by bluebill1049** [comment]
> Either adding it in the library types (as it was before the change)

That was what added.

**Comment by dolma** [comment]
> > Either adding it in the library types (as it was before the change)
> 
> That was what added. #3032

I know, that's what I meant by _"which isn't optimal I guess since it causes other issues"_ but yeah might've not been very clear on that one, my bad.

**Comment by Fakkio** [comment]
> @wendorf (cc. @Fakkio) try declaring your `FormValues` definition as a type instead. Worked for me.
> 
> Although this is not a solution, just a temporary fix.

@dolma yes, declaring `FormValues` as type worked for me too. Thanks a lot!

**Comment by ejose19** [comment]
I also agree making defaultValues to not accept Partial<T> is not desirable, as in many cases defaultValues are set for only a subset of the types, with this change you would need to declare everything in defaultValues which is cumbersome.

**Comment by bluebill1049** [comment]
> I also agree making defaultValues to not accept Partial is not desirable, as in many cases defaultValues are set for only a subset of the types, with this change you would need to declare everything in defaultValues which is cumbersome.

I think you are missing the context, it's always supposed to be `Partial`.

**Comment by ejose19** [comment]
@bluebill1049 I know, but in https://github.com/react-hook-form/react-hook-form/commit/9fd5c5632c885522fafbdc3a8bcfcbe91db684e4 that was removed, hence leaving my feedback on why it should be reverted as currently the type is T and not Partial<T>

**Comment by bluebill1049** [comment]
> I also agree making defaultValues to not accept Partial is not desirable, as in many cases defaultValues are set for only a subset of the types, with this change you would need to declare everything in defaultValues which is cumbersome.

because I thought the DeepPartial would take care of it, and tested which its working: https://www.typescriptlang.org/play?ts=3.9.2#code/CYUwxgNghgTiAEYD2A7AzgF3gEgHIkxGADUoIBXEALnnJQEsBHS+NATwFsAjJCAbgBQAkAA8ADkhhYMbMQgAiIEGIAKsDPTIAeACoA+eAF54O+KIwgUwNPACCMGFDZb6KAGYgY8AKp6B8eAB+OwcnLUVlNSlNCC1fPwCaU3NLa3gAJRAoYFQINntHZ1cPL19-IIysnJQ8grCI1XUYuL0E+CSzEQsrG0zkGGAtTBhXAHMAGloUAGsUJAB3FDbggG9ygICAbQBpeFd4aZA2JDcTAF1AmgaojW0dHbO9QQ34AF9ypMFhcUlpWQR8IQSGRKFpyjpSBQECkelNZgsUJszvAAD6VfqDYZjSZ0eGLAyGdaouFzRZIolovqSTEYEYoCYkhF+AnwNZbPAECzAqFnGgoEAAN08gle8AAZCZIZQvqIJFJ4DI5D4UGIoGBpoCuVKQLoWckuqkbJqiNqXO5PD5lj4PiZOt00vIoBZiQAxegQEAAGXomHKwR0Nv19t64GpQ1p2MZ+L9rPgOz2KAORxO5xo3hVao1nJNIJ1922jzega+5UVCB0nKMrPeATLJk5AEYq2yNm56DBMLgoBxqKwI-TxkToJ3u72sQPyjWFf965gAEzNoltjsYLs9mjjiZDqAj9d9ulbl78oE0FsvZe7sf9w8veDD1ejjfXwcvKfvUszgDy5AwYh-TeMdNVXVY1uVBa4mjuTlWg-JVv1-H8F0AjMQOzMCdQg6IoMwBsYNrL8fz-DAAGYqyAzNQNNTDbliCt5xgoQgA

**Comment by ejose19** [comment]
This indeed seems like an issue with typings as mentioned by @dolma , using type instead of interface works. 

Here's a [sandbox](https://codesandbox.io/s/laughing-microservice-zeh2d?file=/src/App.tsx) with 3.9.2 as the typescript version, changing Form interface to use a type doesn't show any errors, so either ```UnpackNestedValue``` or ```DeepPartial``` is doing something that makes interface incompatible.

**Comment by bluebill1049** [comment]
confirmed it's due to type: `DeepPartial`, will looking for a fix soon.
