### ISSUE TITLE
The result of dirtyfields changes depending on the timing of the append

### ISSUE THREAD

**Issue by yamakeeeeeeeeen** [react-hook-form/react-hook-form#3090]
**Describe the bug**
If you do append before changing the form, the console.log output is normal, but if you do
After changing the form, append does not show console.log as expected.

**To Reproduce**

1. Change `plz change`
2. Click on  `APPEND`
3. See console

![image](https://user-images.githubusercontent.com/53547520/95146489-ead2ea00-07b8-11eb-9a83-ad8bf9d6f8b6.png)

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-qf093?file=/src/index.js

**Expected behavior**
I expected console.log to output the following.

```
Object {test: Array[4]}
  test: Array[4]
    0: Object
      firstName: true
    1: undefined
    2: undefined
    3: Object
      firstName: true
```

**Desktop (please complete the following information):**

- OS: [Win 10]
- Browser [chrome]
- Version [chrome 85.0.4183.121(Official Build)(64bit)]

**Additional context**
Maybe this behavior is normal.
If so, please let me know.

**Comment by bluebill1049** [comment]
yes, it's correct if you don't want such behavior, set `append({}, false)`, so the newly append item is not going to get focused.

**Comment by yamakeeeeeeeeen** [comment]
@bluebill1049 
Thanks, I didn't know about that option.
But I didn't think focus was an issue.

Shouldn't the following be output to the console when you append?

```
Object {test: Array[4]}
  test: Array[4]
    0: Object
      firstName: true
    1: undefined
    2: undefined
    3: Object
      firstName: true
```

but now output is

![image](https://user-images.githubusercontent.com/53547520/95154938-ef55cd80-07cd-11eb-9f3d-2bddfb50d52b.png)

After append, I want to write the logic using dirtyfield, but I don't think that's correct because the index of the newly added form is 1.

I'm sorry if my poor English makes it hard to understand.

**Comment by bluebill1049** [comment]
> @bluebill1049
> Thanks, I didn't know about that option.
> But I didn't think focus was an issue.
> 
> Shouldn't the following be output to the console when you append?
> 
> ```
> Object {test: Array[4]}
>   test: Array[4]
>     0: Object
>       firstName: true
>     1: undefined
>     2: undefined
>     3: Object
>       firstName: true
> ```
> 
> but now output is
> 
> ![image](https://user-images.githubusercontent.com/53547520/95154938-ef55cd80-07cd-11eb-9f3d-2bddfb50d52b.png)
> 
> After append, I want to write the logic using dirtyfield, but I don't think that's correct because the index of the newly added form is 1.
> 
> I'm sorry if my poor English makes it hard to understand.

That's a valid bug.

**Comment by yamakeeeeeeeeen** [comment]
@bluebill1049 
Thank you for the confirmation :D
