### ISSUE TITLE
Form auto validate after change some state.

### ISSUE THREAD

**Issue by armspkt** [react-hook-form/react-hook-form#3096]
**Describe the bug**
Form automatically validate after change state inside component.

**To Reproduce**

1. Click button click
2. Click button click again
3. validate trigger automatically
4. Click the button again
6. Click the button again
7. object errors is empty

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-validationschema-v6-forked-o2y8r?file=/src/index.js

- [useForm](https://codesandbox.io/s/react-hook-form-useform-template-lsm61) Template
- [useFieldArray](https://codesandbox.io/s/react-hook-form-usefieldarray-template-q0jek) Template
- [Controller](https://codesandbox.io/s/react-hook-form-controller-template-yu0z5) Template

**Expected behavior**
Form should not validate when set other states

![2563-10-06 22-52-02 2563-10-06 22_52_29](https://user-images.githubusercontent.com/49720317/95226028-aa11ba00-0826-11eb-9c23-45577ef2cb84.gif)

**Comment by risardi123** [comment]
Hello i have done this before, I think it's not the problem from useForm. but in the yup itself, we defined type Number but send it as String. to handle problem like this, please add this `.typeError("Please use number only")` it will handle all error type problem. Hope it's help.

**Comment by bluebill1049** [comment]
This is expected behavior, each input gets unmounted will trigger the form to be revalidated.eg:

- if there is an input not the screen with error
- once it gets removed
- error will get removed as well.

i would toggle the entire `useForm` the form level, otherwise you will have to `trigger` again when your state gets updated.

**Comment by armspkt** [comment]
@bluebill1049 
Thank for reply.

I just curious the first time that form re-render it will validate but the second time that component re-render validate not trigger and errors object disappear.

In my opinion expected behavior should always re-validate when unmount component or should never re-validate when unmount

Not just first time unmount and validate then second time unmount and not validate.

thanks.

**Comment by bluebill1049** [comment]
i can confirm the latest patch fixed this issue: https://codesandbox.io/s/react-hook-form-validationschema-v6-forked-q2o2c 👍
