### ISSUE TITLE
isDirty is not set to false after successful submission

### ISSUE THREAD

**Issue by thomaschaaf** [react-hook-form/react-hook-form#3097]
**Describe the bug**
After a form is submitted successfully `isDirty` should be reset to false.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-defaultvalues-v6-forked-pwp1p?file=/src/index.js

**Expected behavior**
After clicking submit `isDirty` should be set to false. Else there is no way to disable the button until changes are made.

**Comment by bluebill1049** [comment]
nope, as long as the form is dirty it remains dirty.

**Comment by mifrej** [comment]
How then make form pristine? There is no state argument in onSubmit handler

**Comment by mifrej** [comment]
Ok I know already. Reset filter with default values makes the form pristine.
So I have then issue as I want to disable submit after each consequential submit, leaving the changed state of the form fields.

**Comment by smashercosmo** [comment]
@bluebill1049 do I understand correctly that this is a valid way to address this:

```js
const { formState: { isSubmitted }, getValues, reset } = useForm(...)
useEffect(() => {
  if (isSubmitted) {
     reset(getValues())
  }
}, [isSubmitted, getValues, reset])

```

**Comment by praditha-hidayat** [comment]
I've found this answer on stackoverflow: https://stackoverflow.com/questions/63953501/react-hook-form-resetting-isdirty-without-clearing-form

And it's working for me.

**Comment by zignis** [comment]
> ```js
>   React.useEffect(() => {
>     if (isSubmitted) {
>       const values = getValues()
>       reset(values)
>     }
>   }, [isSubmitted, getValues, reset])
> ```

@JClackett Almost perfect, can be improved by using `isSubmitSuccessful` to prevent unwanted resetting of invalid fields.

```js
  React.useEffect(() => {
    if (isSubmitSuccessful) {
      reset(getValues());
    }
  }, [isSubmitSuccessful, getValues, reset]);
```

**Comment by Charlie-Hua** [comment]
There is no need to use `getValues()`, there is a `keepValues` option according to the [doc](https://react-hook-form.com/api/useform/reset) :

```js
  React.useEffect(() => {
    if (isSubmitSuccessful) {
      reset({}, { keepValues: true });
    }
  }, [isSubmitSuccessful, getValues, reset]);
```
