### ISSUE TITLE
Fields erroneously validating on initial render

### ISSUE THREAD

**Issue by IWCollege-AaronBentley** [react-hook-form/react-hook-form#3098]
**Describe the bug**

I'm using the awesome React Hook Form on a Gatsby.js site I'm building, using Yup for field validation.

I'm having an issue with forms validating on initial render - meaning all form inputs are marked as having errors before a user has interacted with them.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to the Codesandbox below
2. See validation errors marked on initial render

**Codesandbox link**

Forked from the provided `useForm` template:
https://codesandbox.io/s/react-hook-form-validation-on-initial-render-t83c6?file=/src/index.js

**Expected behaviour**

On initial render, the fields should not be validated or marked as having errors before a user has interacted with them.

**Desktop**

- OS: MacOS 10.15.7
- Browser: Confirmed on Chrome & Safari so far
- Version: Chrome 85.0.4183.121 & Safari 14.0

**Additional context**

I've been busy focusing other components of the site I'm working on, however I don't recall getting this error whilst using earlier version(s) of React Hook Form and/or @hookform/resolvers.

Additionally I'm sure this issue isn't specific to Gatsby.js SSR as I get the same issue on the Codesandbox when using vanilla React.

As [I've stated before](https://github.com/react-hook-form/react-hook-form/issues/1223#issuecomment-599954835), thank you for your work on this fantastic library and taking the time to check out my issue 🤩

**Comment by sktt** [comment]
I can confirm this, 
seems like the problem was added in 6.9.0

**Comment by IWCollege-AaronBentley** [comment]
Thank you @sktt for confirming I'm not going crazy, and thank you @bluebill1049 for the super prompt fix.
Outstanding work as always 👏

**Comment by bluebill1049** [comment]
Thanks, @sktt and @IWCollege-AaronBentley for the issue report! my bad... I introduced the regression.

**Comment by IWCollege-AaronBentley** [comment]
@bluebill1049 No worries my friend 👍

I must admit I found the behaviour of this bug quite humorous, it really made me LOL the way the validations would start shouting about errors when the user hasn't done anything yet 🤣

Thank again @bluebill1049.
