### ISSUE TITLE
DirtyFields does not work properly if the field hierarchy in useFieldArray is deep

### ISSUE THREAD

**Issue by yamakeeeeeeeeen** [react-hook-form/react-hook-form#3100]
**Describe the bug**
If the hierarchy of fields in useFieldArray is deep,
The flag doesn't disappear when I revert the value of a form that is dirty.

**To Reproduce**

1. Go to 'https://codesandbox.io/s/react-hook-form-usefieldarray-forked-scx03?file=/src/index.js:407-418'
2. Change 'plz change'
3. See console
4. Revert form 'plz change'
4. See console

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-scx03?file=/src/index.js:407-418

**Expected behavior**
If you change 'plz change' first, the console.log will look like this

```
dirtyFields {test: Array(1)}
              test: Array(1)
                0:
                  field: true
```

And if you set the form value back to 'plz change', the console.log flag should disappear.

```
dirtyFields {}
```

**Screenshots**

but now output is

![image](https://user-images.githubusercontent.com/53547520/95211608-c530f980-0827-11eb-9a44-b67477694d67.png)

**Desktop (please complete the following information):**

- OS: [Win 10]
- Browser [chrome]
- Version [chrome 85.0.4183.121(Official Build)(64bit)]

**Comment by bluebill1049** [comment]
<img width="533" alt="Screen Shot 2020-10-07 at 10 49 24 am" src="https://user-images.githubusercontent.com/10513364/95271888-c7786f80-088a-11eb-9a62-001c5551e53b.png">

looking at your `defaultValues` is not matching with your input name.

**Comment by yamakeeeeeeeeen** [comment]
@bluebill1049 
Sorry, you're right, the name didn't match the defaultValue.
Thank you for letting me know.
