### ISSUE TITLE
Controlled input not working properly with Yup Resolver and mode: all

### ISSUE THREAD

**Issue by matheusgrieger** [react-hook-form/react-hook-form#3101]
**Describe the bug**
When using Yup Resolver with `mode: 'all'`, controlled components like in the code sample (https://github.com/react-hook-form/react-hook-form/blob/master/examples/controlledInput.tsx) don't work properly. When typing the first character it doesn't respond, and when only one character remains, deleting it requires pressing delete twice.

**To Reproduce**
Add `yupResolver` and change `mode` to `all`.

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-controlled-input-forked-zjuym
(forked from code example - https://codesandbox.io/s/j36w7xkk7w)

**Expected behavior**

Typing on the field should behave as expected.

**Desktop (please complete the following information):**

- OS: MacOS 10.15.7
- Browser Chrome
- Version 85.0.4183.121 (64 bits)

**Additional context**
Not sure I was supposed to open this issue here or within the Resolvers package repository, so sorry if it's in the wrong place.

**Comment by bluebill1049** [comment]
that example is wrong, fixing it.

**Comment by bluebill1049** [comment]
actually this example doesn't make any sense, remove it and please use Controller instead.

**Comment by matheusgrieger** [comment]
Alright, thanks guys!

**Comment by matheusgrieger** [comment]
Thank you @bluebill1049 !
