### ISSUE TITLE
Tracking form pristine state

### ISSUE THREAD

**Issue by durdenx** [react-hook-form/react-hook-form#3104]
**Is your feature request related to a problem? Please describe.**

We're migrating from Formik and in this lib we use the dirty state to disable the submit button if values haven't changed. In Formik the dirty state works as follows:

`
Returns true if values are not deeply equal from initial values, false otherwise dirty is a readonly computed property and should not be mutated directly.
`

In react-hook-form the dirty state is set to true when a form field has changed but if the field recover its initial value, the dirty state remains true. And i can't find any way or example to do that in react-hook-form.

**Describe the solution you'd like**

Find a way to track the form pristine state e.g where current values are not equal from initial values.

**Describe alternatives you've considered**

Not sure :)

**Comment by bluebill1049** [comment]
> In react-hook-form the dirty state is set to true when a form field has changed but if the field recover its initial value, the dirty state remains true. And i can't find any way or example to do that in react-hook-form.

can u share that in a codesandbox?

**Comment by bluebill1049** [comment]
`isDirty` should just work for what you have described above.

**Comment by durdenx** [comment]
You're right, i've tried to reproduce that in a codesandbox and it works as expected.

It's surely something else, sorry for the inconvenience, you can close.

Here the codesandbox, feel free to use it in the example section: 
https://codesandbox.io/s/react-hook-form-disabled-submit-if-not-dirty-or-valid-form-78cuk

**Comment by bluebill1049** [comment]
np :)

**Comment by bluebill1049** [comment]
I would test out the latest. let me know if there is still an issue.

**Comment by durdenx** [comment]
@bluebill1049 Yes still occurs in v6.9.2 (from v6.8.4 to v6.9.2). I've updated the codesandbox.

**Comment by bluebill1049** [comment]
hmmm input without `defaultValue`, i guess it's the issue, because potentially `undefined !== ''`

**Comment by durdenx** [comment]
Here my defaultValues: 
```ts
const defaultValues = {
  field1: 10,
  field2: "",
  field3: "",
  field4: ""
};
```

And here the associated fields: 
```ts
        <section>
          <label>field 1</label>
          <Controller
            as={
              <Select fullWidth variant="outlined">
                <MenuItem value={10}>Ten</MenuItem>
                <MenuItem value={20}>Twenty</MenuItem>
              </Select>
            }
            control={control}
            name="field1"
          />
        </section>

        <section>
          <label>field 2</label>
          <TextField
            variant="outlined"
            fullWidth
            inputRef={register}
            name="field2"
          />
        </section>
        <section>
          <label>field 3</label>
          <TextField
            variant="outlined"
            fullWidth
            inputRef={register}
            name="field3"
          />
        </section>
```

As you can see there is not field for my `field4`default value. And this is the cause of the problem.

If i remove `field4` from defaultValues it works.

I don't know if this is the desired behaviour but before version 8.4.3 it was working like that.
