### ISSUE TITLE
CSS in Downshift material input example is broken

### ISSUE THREAD

**Issue by woidda** [react-hook-form/react-hook-form#3106]
**Describe the bug**
CSS in Downshift input example is broken for the example linked from the README: 
"Simple integration with [UI libraries](https://codesandbox.io/s/react-hook-form-v6-controller-24gcl)"

**To Reproduce**
Go to the [codesandbox](https://codesandbox.io/s/react-hook-form-v6-controller-24gcl) and add "a" to Downshift input. You will see tha the result for the autocomplete suggestion are rendered as unordered list without styling

**Comment by bluebill1049** [comment]
This is not a bug, the purpose of that CSB is to showcase `Controller`, and not to do styling.

**Comment by woidda** [comment]
Well then this is really an example on how "Simple integration with UI libraries" works. When the styling works so well...
