### ISSUE TITLE
Initial status is not correct with radio button

### ISSUE THREAD

**Issue by LeamonLee** [react-hook-form/react-hook-form#3107]
**Describe the bug**
I have a dynamic form which includes a group of radio button. Since it's dynamic (I render fields by reading a config file), I cannot give each field a default value by setting the dafaultValues attribute in useForm hook. My workaround is use setValue function in useEffect to give each field a default value, but the radio button seems to have problem rendering the correct initial value. (A TextField works instead)
If you click submit button, you still can see the value of radio button is actually being set correctly.

**Codesandbox link (Required)**
https://codesandbox.io/s/serene-http-vu84g?file=/src/App.js

**Expected behavior**
Radio button should display correct initial status after corresponding setValue being called in useEffect function.

**Desktop (please complete the following information):**

- OS: Windows10
- Browser: Chrome 85.0.4183.121
- Version 
react-hook-form: 6.9.2

**Comment by bluebill1049** [comment]
please read the console warning

```
<Controller
            as={
              <RadioGroup aria-label="gender">
                <FormControlLabel
                  value="female"
                  control={<Radio />}
                  label="Female"
                />
                <FormControlLabel
                  value="male"
                  control={<Radio />}
                  label="Male"
                />
              </RadioGroup>
            }
            name="RadioGroup"
            control={control}
            defaultValue=""
          />
```

**Comment by LeamonLee** [comment]
Sorry my bad. Thanks for your prompt reply.
