### ISSUE TITLE
Possibility of adding custom transformer to register

### ISSUE THREAD

**Issue by AkselAllas** [react-hook-form/react-hook-form#3111]
In https://github.com/react-hook-form/react-hook-form/issues/615 there was the following suggestion:

Add option in register function for custom transformer like:
```
register({
  transformValue: (value: string) => parseFloat(value),
});
```
So my question is that aside from increased library size, what negative effect would implementing a custom transform function inside register bring?

For me using only register seems like the most elegant way to handle inputs, and I would really prefer not to use controller.

**Comment by bluebill1049** [comment]
- (increase API complexity) at the moment register function only take care of one single responsibility which is validation.
- Yes, transform is one feature, then the next potential feature request will be parse. this is not the direction I personally like for hook form at least on the `register` level.

It's not that I haven't considered for such API, but at the moment I don't think it's a good idea to cumbersome `register` function, it serves as one function and it's for validation only.

**Comment by AkselAllas** [comment]
These are very good points. 

How would parse differ from transform? In the example provided, we used it (transform) to parse string to float?

I'm guessing that for cases where we want inputs to return specific types to our form, we should use TypeController?
https://react-hook-form.com/advanced-usage#StrictlyTyped

**Comment by bluebill1049** [comment]
I am still thinking about an API to cate for this `transform`, but most likely it won't be part of `register`.

I would just use `Controller` to parse the value, for now, I believe I have posted an example in the other issue.

https://codesandbox.io/s/ecstatic-waterfall-yfsqe

**Comment by AkselAllas** [comment]
For me, this can be closed.
