### ISSUE TITLE
FormState "isDirty" not in sync with "dirtyFields" when defaultValues doesn't include all fields

### ISSUE THREAD

**Issue by ejose19** [react-hook-form/react-hook-form#3113]
**Describe the bug**
FormState "isDirty" not in sync with "dirtyFields" when defaultValues doesn't include all fields

**To Reproduce**

1. Create a form with an input (text) and a checkbox
2. Use default values that only includes the text input
3. Monitor both isDirty and dirtyFields (console.log)
4. Toggle the checkbox, notice how isDirty is no longer being in sync with dirtyFields after second toggle

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

https://codesandbox.io/s/muddy-water-rf3yw?file=/src/App.tsx (Toggle the switch twice, notice how isDirty is always true, while dirtyFields is correct)

**Expected behavior**
Both properties should always being in sync

**Additional context**
I see the issues arises due to: https://github.com/react-hook-form/react-hook-form/blob/40766815cfe49dbe4ff0ed2dba95ff6ea297eda3/src/useForm.ts#L276-L282

Is there any reason why only ```!isEmptyObject(formStateRef.current.dirtyFields)``` does not suffices? Relying on using an OR will only make the form prone to errors like this one as both properties uses different logic.

**Comment by bluebill1049** [comment]
because your `switch` input doesn't have a `defaultValue`.

**Comment by ejose19** [comment]
Maybe the issue wasn't formulated correctly, the issue here is that ```isFormDirty``` is using 2 sources instead of being a derived value of ```dirtyFields``` only, so in a case where the the first condition: 
```ts
!deepEqual( 
     getValues(), 
     isEmptyObject(defaultValuesRef.current) 
       ? defaultValuesAtRenderRef.current 
       : defaultValuesRef.current, 
   )
``` 

differs from the 2nd one (like in this example):

```ts
!isEmptyObject(formStateRef.current.dirtyFields)
```

```dirtyFields``` and ```isDirty``` won't be in sync (which I don't see a case where that's desirable)

Note: 
If all inputs are meant to have a default value, the note on ```defaultValue``` page should be changed to something more strict:

> Note: It is encouraged that you set a defaultValue for all inputs to something non-undefined such as the empty string or null.

**Comment by bluebill1049** [comment]
> Note:
> If all inputs are meant to have a default value, the note on `defaultValue` page should be changed to something more strict:

please submit a PR if you can.

**Comment by bluebill1049** [comment]
```
!deepEqual( 
     getValues(), 
     isEmptyObject(defaultValuesRef.current) 
       ? defaultValuesAtRenderRef.current 
       : defaultValuesRef.current, 
   )
```

is definitely the source of the truth, I am confident to remove the second check in the following PR.

**Comment by bluebill1049** [comment]
actually no, If you would like to help, I would suggest you to clone and repo and remove the extra condition (that you suggested) and then run the test. see if you can spot the potential improvement.

**Comment by ejose19** [comment]
I did, and everything works correctly removing the first condition, (the one that I mentioned shouldn't be there). The added benefit is that we don't force users to specify all defaultValues in useForm if they only need to set some.

**Comment by bluebill1049** [comment]
> I did, and everything works correctly removing the first condition, (the one that I mentioned shouldn't be there). The added benefit is that we don't force users to specify all defaultValues in useForm if they only need to set some.

- clone the repo
- remove the logic
- run the uni test

**Comment by ejose19** [comment]
That's what I did, you want me to submit a PR?

**Comment by bluebill1049** [comment]
> That's what I did, you want me to submit a PR?

sure, i hope everything passes (unit test and integration) I run it locally and everything falls apart.

**Comment by bluebill1049** [comment]
let's continue the discussion here:

here is what I am trying to achieve.

- `isDirty` will be purely relay on deepEuqal `defaultValues`
- `dirtyFields` will be based on user interaction with the input and check again defaultValue based on the input **name**.

**Comment by hinsxd** [comment]
Not sure if the following is related with this PR (or if this is intended behavior):
https://codesandbox.io/s/eager-waterfall-l9w2z?file=/src/App.tsx

Using a boolean field to control the visibility of the text field, if the checkbox is toggled twice, the `isDirty` become true with `dirtyFields` being empty.

How should I ensure `isDirty` is false?

**Comment by bluebill1049** [comment]
@hinsxd with the new update (coming) we only check against `defaultValues` with your form value:

https://codesandbox.io/s/awesome-kare-buf9k?file=/src/App.tsx:976-978

FYI: the moment that you have unmounted your input, the text input value will be `undefined`

**Comment by durdenx** [comment]
I think #3104 is related

**Comment by ejose19** [comment]
In order to decide how to improve ```dirtyFields```, let's take a look at the more "complex" cases (nested objects and arrays)

Supposing we have an empty defaultValues, and the user adds a new array element with property name, should dirtyFields be ```{items: [{name: true}]``` or ```{items: [true]}``` ? If we go for the former, it would be more consistent when defaultValues is populated.

I'm assuming all nested properties can't be empty (ie: ```{ items: [{}] }```, because if that's the case, dirtyFields wouldn't be able to specify the most granular property, for example:

```defaultValues: { items: [{}] }```, we append a new empty item, so currentValues becomes ```{ items: [{}, {}] }```, since there's no property in those items elements, ```dirtyFields``` would need to equal: ```{ items: [undefined, true] }```

The same would apply for nested objects, let me know if I'm correct to assume neither a nested property or an array element can be empty.

**Comment by ejose19** [comment]
@durdenx I got bitten by that change as well, seems on last version we cannot longer specify properties on ```defaultValues``` that won't be registered (it was more of a convenience for the user), but in a way it makes sense because those have nothing to do with the form, they can be injected ```onSubmit``` when they're actually needed.

**Comment by durdenx** [comment]
@ejose19 Yes but i think the form values should be initialized with the provided default values. If there are more fields in the default values, it shouldn't affect the dirty state as there are no fields in the form to update them!

**Comment by bluebill1049** [comment]
> I'm assuming all nested properties can't be empty (ie: `{ items: [{}] }`, because if that's the case, dirtyFields wouldn't be able to specify the most granular property, for example:

Hey, @ejose19 much appreciated for investigating this and your help. I think we can avoid the above and make sure users doesn't level empty object in the field array.

**Comment by c0rodg2** [comment]
I have similar issue. Is the best way for the moment to check if "dirtyFields" is empty?

**Comment by bluebill1049** [comment]
> I have similar issue. Is the best way for the moment to check if "dirtyFields" is empty?

can you share a codesandbox? couple questions as well:

- do you have a defaultValues?
- when input unmount in shouldUnregister, the input value will remain the same, hence not trigger dirtyFields
