### ISSUE TITLE
Use a Real MutationObserver Shim when Testing

### ISSUE THREAD

**Issue by b-wils** [react-hook-form/react-hook-form#312]
When attempting to use this library with `@testing-library/react` I was having issues where calling a useState update in my submit callback was not being seen by the test runner. I used the information in https://github.com/react-hook-form/react-hook-form/issues/260 to get started. I could still log the updates in the component so it didn't seem to be a component problem.

I ended up adding https://github.com/megawac/MutationObserver.js/tree/master and this solved my problem. Assuming you agree with my analysis, the samples should be updated to reflect this. It took me quite some time to track the issue down.

Relevant repro code below

```
// Form.jsx

import * as React from 'react';

import {useState} from 'react';

import useForm from 'react-hook-form';

const Form = () => {
  const { register, handleSubmit, errors } = useForm(); // initialise the hook
  
  const [val, setVal] = useState(false);

  const onSubmit = (data) => {

    setVal(true);
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input data-testid="myinput" name="myinput" ref={register} /> {/* register an input */}
      
      <button type="submit" data-testid="login-submit"> Login </button>

      {val && <div data-testid="my-res"> Value Set! </div>}
    </form>
  );
};

export default Form;


// Form.test.jsx

import React from 'react';

import { render, cleanup, fireEvent } from '@testing-library/react';

import Form from './Form';

afterEach(cleanup);

beforeEach(() => {

  // This does not work
  global.MutationObserver = class {
    constructor() {}
    disconnect() {}
    observe() {}
  };

  // // This will!
  // require('mutationobserver-shim');
});

describe('React-Hook-Form + setSTate', () => {

  it('Displays the updated value', async () => {

    const { getByTestId, findByTestId } = render(<Form />);

    const myinput = getByTestId(/myinput/i);

    const submitButon = await findByTestId('login-submit');

    fireEvent.change(myinput, { target: { value: 'set random input' } });

    fireEvent.click(submitButon);

    await findByTestId('my-res')
  });

});
```

**Comment by bluebill1049** [comment]
Thanks heaps @b-wils for this info. I shall update my unit tests as well. I should include this information under website.

**Comment by bluebill1049** [comment]
I have updated the lib itself, will update the website to include this information tonight.

**Comment by bluebill1049** [comment]
I am closing this issue, the lib itself have been updated and website is updated as well under FAQ. thanks

**Comment by b-wils** [comment]
Thanks for the quick response and update! You could probably move the Shim to a global jest setup  like in the other thread. I've got it in my test case because I'm using Create React App which has limited support for global jest configuration.

**Comment by stramel** [comment]
@b-wils It is in a global jest setup file,
https://github.com/react-hook-form/react-hook-form/blob/6d908eeb81cc551fd7d2f3aa1901cfd9197e1199/setup.ts#L1

**Comment by b-wils** [comment]
@stramel Nice! I was looking at the FAQ which uses the individual test hook. It would be worth mentioning it there as well. 

https://react-hook-form.com/faq/

**Comment by bluebill1049** [comment]
@b-wils i will do that.

**Comment by pjaws** [comment]
Reminder: there's still nothing about this in the FAQ.

I found this issue, because I'm getting a "MutationObserver is not defined" error when I try to render a form component built with this library, using React Testing Library. Am I to understand that I have to install `mutationobserver-shim` and require it in my Jest setup?

**Comment by stramel** [comment]
Sorry @pjaws, I will re-open so we make sure to add a note about it. 

Yes that's correct.

**Comment by pjaws** [comment]
No need to be sorry! Just wanted to remind you so the next guy/girl who
gets stuck on this can fix it a little quicker!

**Comment by bluebill1049** [comment]
U mean this? 
![58E20350-9302-42E8-ADB7-D394ED431722](https://user-images.githubusercontent.com/10513364/73791647-d63bed80-47f6-11ea-84e7-f2a262234ead.png)

Please send a PR If u think the answer need improvement as well. It’s open sourced as well

**Comment by bluebill1049** [comment]
Same need to fix that button...

**Comment by stramel** [comment]
@pjaws Is that what you were looking for? I'm going to close it since it appears to exist. If you feel it needs more clarification, please feel free to contribute. Thanks for using the lib!

**Comment by pjaws** [comment]
I guess I missed that before, sorry. Wouldn't it make more sense to include
this in the "Testing React Hook Form" section? Or at least a reference to
it.

**Comment by thainararogerio** [comment]
For those who came into this post nowadays, **there is no need to use cleanup anymore if you are using mocha, Jest or Jasmine**: https://kentcdodds.com/blog/common-mistakes-with-react-testing-library
