### ISSUE TITLE
Nested watch (similar to lodash get) not working

### ISSUE THREAD

**Issue by 99uno** [react-hook-form/react-hook-form#3125]
**Describe the bug**
I have a mongo db model like: {phones: {mobile: '781347834', home: '78237216'}}. When I use react-hook-form 6 I register both inputs with name 'phones.mobile' and 'phones.home'. Everything is working fine but when I use form.watch('phones.mobile'), value is not being updated because it does not check nested values when I call form.setValue('phones', {mobile: '781347834', home: '78237216'}).

**Expected behavior**
Watch should work as lodash.get.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by alchaki2009** [comment]
‫أُرسلت من الـ iPhone‬

‫في ٠٩‏/١٠‏/٢٠٢٠ الساعة ٢:١٦ ص، كتب/كتبت ‏Bill ‏<notifications@github.com>:‬

﻿

#2848<https://github.com/react-hook-form/react-hook-form/issues/2848>
