### ISSUE TITLE
setValue for nested custom fields is not working as expected

### ISSUE THREAD

**Issue by 99uno** [react-hook-form/react-hook-form#3133]
**Describe the bug**
When I have a nested complex component, and call setValue using the parent key as the name, the method use getPath and search for primitives so it tries to set to the deeper value to the deeper key. For example if I call setValue('owner', {name: .., location: {}}) it will not set value for field registered as 'owner.location' but if I use the same json as defaultValues it works. Please check Sandbox link with comments about what works and what doesn't.

`{
      legalId: "123456",
      owner: {
        name: "Mike",
        location: { province: "Buenos Aires", city: "CABA" }
      }
}`

**To Reproduce**
1. Create a complex component and register to form with a deep name for example "owner.location".
2. Try the following options:
    a. Call setValue("owner", {legalId: "123456", location: {city: "123", province: "asd"}}). It won't work
    b. Call setValue("owner.location", {city: "123", province: "asd"}). It works
    c. Set {legalId: "123456", location: {city: "123", province: "asd"}} as defaultValues to form. It works

**Codesandbox link (Required)**
[https://codesandbox.io/s/nested-field-array-deep-append-forked-2bnwy?file=/src/App.js](https://codesandbox.io/s/nested-field-array-deep-append-forked-2bnwy?file=/src/App.js)

**Expected behavior**
Fix setValue to check registered component names and when iterating recursively if you found a registered key, try to set it.

**Desktop (please complete the following information):**
- Browser: Chrome
- Version 85.0.4183.121

**Additional context**
react-hook-form 6.9.2. I'm almost certain it was working in v5.

**Comment by bluebill1049** [comment]
<img width="994" alt="Screen Shot 2020-10-10 at 9 06 28 am" src="https://user-images.githubusercontent.com/10513364/95635346-e28bef00-0ad7-11eb-9e18-e981f9490c32.png">

setValue was meant to just update an input field with a value, it was not meant to do nested fields as you mentioned above.

**Comment by 99uno** [comment]
It was working in previous versions... So, which is the best way for iterating all fields in a form in order to set received values from the server? I don't want to set each one manually.

**Comment by bluebill1049** [comment]
use reset instead of setValue

**Comment by 99uno** [comment]
When I use reset and don't set an empty value for an array field, it throws an error (cannot read property map of undefined). I think that if an array property is not defined, it shouldn't break and set empty value.

**Comment by bluebill1049** [comment]
@99uno there is a regression issue with the latest, try 6.9.2 i will patch this issue tonight.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/3209
