### ISSUE TITLE
Feature request for Controller/setValue

### ISSUE THREAD

**Issue by pranab-witbybit** [react-hook-form/react-hook-form#3136]
**Is your feature request related to a problem? Please describe.**
When set name such as 'person.145.name', the person key is created as an array, with its 145th index being the object with name property.

**Describe the solution you'd like**
There should be an option to create it as object/map, such as:
{ person: {  '145': {   name: ""  }  } }

Such as it happens with [lodash.setWith](https://lodash.com/docs/4.17.15#setWith)

**Comment by bluebill1049** [comment]
We are going forward with a type-safe form, an integer will be used for array index. This is a design limitation and a trade-off from this library.
