### ISSUE TITLE
`watch` on nested fields should unfold into an object.

### ISSUE THREAD

**Issue by AlexFrazer** [react-hook-form/react-hook-form#314]
**Is your feature request related to a problem? Please describe.**
I am using `useForm`, which gives me `watch`. I have a field which represents a nested value.

```
<form onSubmit={handleSubmit(onSubmit)}>
  <input type="color" name="colors.primary" ref={register({ name: 'colors.primary' })} />
  <input type="color" name="colors.secondary" ref={register({ name: 'colors.secondary'})} />
</form>
```

When I submit, it serialized as follows:
```
{
  colors: {
    primary: '#003366',
    secondary: '#ffffff',
  }
}
```

However, when I use `watch`, it gives a different result

```
const fields = watch(['colors.primary', 'colors.secondary']);

  React.useEffect(() => {
    console.log(fields);
  }, [fields]);
```
The result of the console.log is like this:
```
{colors.primary: undefined, colors.secondary: undefined}
```

**Describe the solution you'd like**
Ideally, I would want the above example with `watch` to serialize in the same way the submitted form would

**Describe alternatives you've considered**
Project is still very workable without this. Just a nice-to-have

**Additional context**

**Comment by bluebill1049** [comment]
hey @AlexFrazer you can use watch('colors')

**Comment by bluebill1049** [comment]
i am closing this issue, feel free to ask a question if this above solution is not working for you.
