### ISSUE TITLE
Radio Input + React Router = TypeError: Illegal invocation

### ISSUE THREAD

**Issue by chungweileong94** [react-hook-form/react-hook-form#315]
**Describe the bug**
I'm trying to use radio inputs in my form, so when I click submit, I will then use React Router to navigate to a route. However, it keeps throw me an error `TypeError: Illegal invocation` during the navigation. 
After some investigation, the problem is basically caused by the radio input, which when it trying to remove the listeners.

**To Reproduce**
1. Add radio inputs in the form
2. use react-router to navigate to a route in handle submit event

**Expected behavior**
Get the form data and navigate to the route

**Screenshots**
![image](https://user-images.githubusercontent.com/15154097/65109454-d5065180-da0a-11e9-8568-f5dbd36d320f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge (chromium)
 - Version  78.0.268.3

**Comment by bluebill1049** [comment]
Can u share ur code in a codesandbox?

**Comment by chungweileong94** [comment]
@bluebill1049 Sure, here the simple [example](https://codesandbox.io/s/green-surf-vjibs?fontsize=14).

**Comment by chungweileong94** [comment]
@bluebill1049 I tried to downgrade the to version 3.23.7, and problem solved. I guess the 3.23.8 break something.

**Comment by bluebill1049** [comment]
thanks @chungweileong94 i will take a look

**Comment by bluebill1049** [comment]
i have patched issue ❤️ thanks for reporting.

**Comment by bluebill1049** [comment]
if you find it useful please leave a ⭐️ too thanks :)
