### ISSUE TITLE
Example code doesn't match sandbox

### ISSUE THREAD

**Issue by IamManifold** [react-hook-form/react-hook-form#3159]
I couldn't get the example code for multiple error messages to work, but the code example in the sandbox does work. The two code samples don't match. 
![BugNoticeScreenshot](https://user-images.githubusercontent.com/47574996/95780907-cd12f280-0c9a-11eb-8814-3abd248eec21.png)

**Comment by MikeyAlmighty** [comment]
I can have a look at this

**Comment by bluebill1049** [comment]
thanks @MikeyAlmighty ❤️

**Comment by bluebill1049** [comment]
FYI @IamManifold the doc example and CSB sometimes may not be 100% aligned, most of the time CSB contains more comprehensive examples. 👍

**Comment by MikeyAlmighty** [comment]
@bluebill1049 Will have a look after work (GMT+2)

**Comment by bluebill1049** [comment]
I am going to close this issue as I commented above docs code may not be the same as Codesandbox, but the idea is the same to showcase and demonstrate the usage., thanks for trying to help @MikeyAlmighty ❤️
