### ISSUE TITLE
  text area example

### ISSUE THREAD

**Issue by kammasuresh** [react-hook-form/react-hook-form#316]
Hi Is there any text area example ?

**Comment by bluebill1049** [comment]
<textarea ref={register} /> it's the same @kammasuresh

**Comment by The-Code-Monkey** [comment]
I feel like this issue can be closed as it was more of help than a bug?

**Comment by kammasuresh** [comment]
Plz close this

**Comment by kammasuresh** [comment]
Plz close it

**Comment by Slapbox** [comment]
The docs would benefit from just showing a `textarea` used somewhere. In the docs I looked at, I didn't see that so I Googled to see if there was any special configuration needed and it brought me here.

Pretty low priority though.

**Comment by Aryaman73** [comment]
Just for reference, in the latest version of RHF you want to do:
`<textarea {...register("textAreaID")` />

I do think this should be added into the documentation.

**Comment by bluebill1049** [comment]
thanks @Slapbox & @Aryaman73 which section should be placed?

**Comment by Slapbox** [comment]
Not really sure. Maybe just adding a CodeSandbox example would be simplest? The code wouldn't be any different from "Basic" I think, but it would stand out to someone searching for it.

https://github.com/react-hook-form/react-hook-form/tree/master/examples
