### ISSUE TITLE
Typescript error when trying to access error message for array field

### ISSUE THREAD

**Issue by nywleswoey** [react-hook-form/react-hook-form#3162]
**Describe the bug**
I get a typescript error when trying to access the error message for an array field 

**To Reproduce**
I've replicated the error in CodeSandbox. Line 42 gives a `Property 'message' does not exist on type '(FieldError | undefined)[]` error.  Examining the actual value using React DevTools show that the error object is storing the correct value.

**Codesandbox link (Required)**
https://codesandbox.io/s/condescending-meadow-u5cpm?file=/src/App.tsx

**Expected behavior**
There should not be any typescript error.

**Screenshots**
![image](https://user-images.githubusercontent.com/28249994/95809714-0eaaa880-0d42-11eb-8008-f03680f2830a.png)

**Desktop (please complete the following information):**

- OS: iOS
- Browser: Chrome
- Version 85.0.4183.121

**Comment by bluebill1049** [comment]
Take a look at below:

https://codesandbox.io/s/nervous-snow-920z6

https://react-hook-form.com/ts#NestedValue
