### ISSUE TITLE
Type incompatibility with UseFormMethods when imported from a shared component library

### ISSUE THREAD

**Issue by EwenDC** [react-hook-form/react-hook-form#3164]
**Describe the bug**
When integrating react-hook-form into my company's component library, I created a form wrapper component that required the form methods returned by useForm as a prop (so it could pass them onto FormProvider internally). This works perfectly from javascript's perspective, and my component is able to make use of those methods as required within the actual application. However, whenever I try to correctly type the prop using the "UseFormMethods" type within the library, in the calling application Typescript throws an error where the prop is passed in. It tells me the type returned by useForm and the type accepted by my prop are incompatible, despite both being defined by the exact same type definition from the same version of react-hook-form.

**To Reproduce**
Clone the repository linked below and follow the reproduction steps in the readme
https://github.com/EwenDC/react-hook-form-typing-bug

**Expected behavior**
Typescript accepts the prop without raising a type error.

**Additional context**
The repository linked is a vastly simplified mockup of the actual setups used when encountering the issue. When encountering the issue within my company's codebase [this](https://github.com/EwenDC/react-hook-form-typing-bug/blob/main/original_type_error.txt) is the typing error, and it only shows up on compile but not within VSCode. However, I get a [different](https://github.com/EwenDC/react-hook-form-typing-bug/blob/main/example_type_error.txt) typing error in the example which does show up in VSCode. The core issue however is identical. Apologies in advance if this is just me doing something completely wrong.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by EwenDC** [comment]
I presume you closed this for not having a codesandbox example? As I've followed the template otherwise.

I literally cannot include a codesandbox example as there is no way to simulate the dual package library/application relationship short of actually publishing a library to NPM. I tried, but the error does not occur unless you use the setup I linked.
