### ISSUE TITLE
`clearErrors` only removes the error closes to the input

### ISSUE THREAD

**Issue by AlanKrygowski** [react-hook-form/react-hook-form#3177]
**Describe the bug**
I'm attempting to create a more composite validation of two inputs. I require the value in input A to be lower than in input B. The catch is, I need both fields to show the error if the rule is not met, to give the user an ability to either decrease the value in A, or increase it in B.

I've created a simple, custom validation firing on both input's `onChange` and linked it to a custom validator which using `setError` sets the errors for both fields - and this part works wonders.
```
  const validateDates = () => {
    const startAt = parseInt(getValues(`entries.${index}.startAt`), 10);
    const expiryAt = parseInt(getValues(`entries.${index}.expiryAt`), 10);

    if (startAt > expiryAt) {
      setError(`entries.${index}.startAt`, {
        type: "manual",
        message: "Start date cannot be larger that expiry date"
      });
      setError(`entries.${index}.expiryAt`, {
        type: "manual",
        message: "Expiry date cannot be smaller that start date"
      });
    } else {
      clearErrors([`entries.${index}.startAt`, `entries.${index}.expiryAt`]);
    }
  };
```
The problem is when the values are ok, because the moment I set the field to a proper value, only the message closest to the input gets hidden, and the other one stays intact, even tho the error for it should be cleared.

I've recreated this sandbox to showcase the issue: https://codesandbox.io/s/hook-form-attempt-6gm4t?file=/src/components/entry.item.tsx:395-995

**To Reproduce**
1. Open the sandbox
2. Locate one of the two numeric input groups, like this one:
![image](https://user-images.githubusercontent.com/29440326/95983884-a54e9680-0e22-11eb-808c-d0ec1ef1ff6e.png)
3. Attempt to make the value in the upper one higher from the one at the bottom - An error message should appear over both fields.
4. Try to correct the value - you'll see the error message being removed only from over the input you've focusing, and not the other one.

**Codesandbox link (Required)**
https://codesandbox.io/s/hook-form-attempt-6gm4t?file=/src/components/entry.item.tsx:395-995

**Expected behavior**
the `clearErrors` function should remove all of the messages

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome

**Additional context**
Since I'm fairly new to the framework I bet 10$ that the issue is mostlikely caused by me doing something wrong, but after a few hours spend on tackling the issue, I'm finally not sure what the problem is.

**Comment by bluebill1049** [comment]
switch to the latest version, issue fixed: 

https://codesandbox.io/s/hook-form-attempt-forked-0vuom
