### ISSUE TITLE
reset with no values

### ISSUE THREAD

**Issue by tafelito** [react-hook-form/react-hook-form#3178]
**Describe the bug**
calling reset with no arguments does not reset the from if reset was called before with values

**To Reproduce**

1. Fill all the inputs
4. Click on 'Standard Reset...' // values are cleared
2. Click on 'Reset with values' // values are filled with reset values
3. Click on 'Reset' // nothing happens
4. Click on 'Standard Reset...' // values are cleared

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-reset-v6-forked-tlyf3?file=/src/index.js

**Expected behavior**
when calling reset with no values I'd expect the form will be cleared. Right now if reset is called with values before, then the reset with no values does not clear all values

if reset is called with an empty object, then it does work

**Comment by bluebill1049** [comment]
![test](https://user-images.githubusercontent.com/10513364/96060468-4cdbcf80-0edc-11eb-9491-1912f8d572b3.gif)
thanks @tafelito looks fine to me.

**Comment by tafelito** [comment]
@bluebill1049 it does work when the register is passed to the onClick but it doesn't when you call it like this `onClick={()=>reset()}`

I just updated the example

**Comment by bluebill1049** [comment]
@tafelito that's because after `reset({...data})` which means useform's `defaultValues` will be that `{...data}` (which start with `undefined`), a good example will be the following: 

```
it('should reset with field array', () => {
      const { result } = renderHook(() => {
        const { register, reset, control } = useForm({
          defaultValues: {
            test: [{ value: 'default' }],
          },
        });
        const { fields, append } = useFieldArray({
          name: 'test',
          control,
        });
        return { register, reset, fields, append };
      });

      act(() => {
        result.current.append({ value: 'test' });
      });

      result.current.register({ type: 'text', name: 'test[0].value' });

      act(() => {
        result.current.reset();
      });

      expect(result.current.fields).toEqual([{ id: '3', value: 'default' }]);
    });
```

I will update the doc now to reflect this.

**Comment by tafelito** [comment]
so what you're saying is that reset() will use default values? and when you do  reset({...data}) is resetting the defaults, so when you call the reset() again it uses the latest values?

what I don't get is why by doing  onClick={reset} always clears the values

**Comment by bluebill1049** [comment]
- when you don't supply useForm with `defaultValues`
- reset(value) will inject into useForm's`defaultValues`
- invoke `reset` is the same as `reset(defaultValues)` now
- it work with onClick={reset} because there is a hidden argument

**Comment by bluebill1049** [comment]
<img width="939" alt="Screen Shot 2020-10-15 at 12 21 59 pm" src="https://user-images.githubusercontent.com/10513364/96062290-09379480-0ee1-11eb-9fb8-e35765303ca0.png">

**Comment by tafelito** [comment]
ok I see, thanks for the explanation

**Comment by bluebill1049** [comment]
Thanks for the issue report @tafelito ❤️

**Comment by bluebill1049** [comment]
> ok I see, thanks for the explanation and the quick response as always!

my pleasure 👍
