### ISSUE TITLE
Wrong error typization when using object as value

### ISSUE THREAD

**Issue by dumaron** [react-hook-form/react-hook-form#3181]
**Describe the bug**
I think that errors' typization is inferred wrongly by typescript when a field's value is an object.

[Here's a demo](https://codesandbox.io/s/confident-napier-30361?file=/src/App.tsx) in which the code works, but typescript reports errors when accessing to `errors.something.type`. I've looked for `NestedValues` in search of help, but it doesn't seems to fit my needs.

**To Reproduce**
1. Go on codesandbox and see typescript warnings on `errors.country.type`.

**Codesandbox link**
[Link](https://codesandbox.io/s/confident-napier-30361?file=/src/App.tsx)

**Screenshots**
![Screenshot_20201015_121652](https://user-images.githubusercontent.com/1549216/96110665-74cd3200-0ee0-11eb-9a5a-c5116fa3018f.png)

**Expected behavior**
No errors are thrown by typescript

**Comment by bluebill1049** [comment]
please use this type: https://react-hook-form.com/ts#NestedValue

**Comment by dumaron** [comment]
Actually I've tried it, but without success. Sadly I cannot reproduce the problem in codesandbox, but I'll try harder later.

Anyway, my local instance of typescript reports this error:
```
Error:(42, 22) TS2344: Type 'Choice<MyEnum>' does not satisfy the constraint 'unknown[] | Record<string, unknown>'.
  Type 'Choice<MyEnum>' is not assignable to type 'Record<string, unknown>'.
    Index signature is missing in type 'Choice<MyEnum>'.
```
It seems to me that `NestedValue` looks for arrays and, since the examples on the docs always use arrays, I thought it worked only with arrays. 
I'm using `typescript@4.0.3` and `react-hook-form@6.9.2`. The problem is not related to the use of an enumeration, since I've tried in [this sandbox fork](https://codesandbox.io/s/vibrant-lamarr-oe4hj?file=/src/App.tsx) and everything seems fine.

Any idea on how I can improve my codesandbox example?

**Comment by dumaron** [comment]
After some investigation I've found the problem's root: it's [a Typescript issue](https://github.com/microsoft/TypeScript/issues/15300) not related to this library. Any typization defined with `interface` isn't compatible with `Record<string, unknown>`, which is used to define `NestedValue`.

To help other devs that may encounter this behavior I've created [a new sandbox](https://codesandbox.io/s/purple-mountain-9sgsm?file=/src/App.tsx) that reproduces the error. It must be compared with [the older sandbox](https://codesandbox.io/s/vibrant-lamarr-oe4hj?file=/src/App.tsx) where `type` is used instead of `interfaces`. You can see how by defining `Choice` with as an `interface` throw a Typescript's error, while using `type` makes the software compile successfully.

Sorry for the noise.
