### ISSUE TITLE
Wrong type in "errors"

### ISSUE THREAD

**Issue by Hentaro1989** [react-hook-form/react-hook-form#3186]
**Describe the bug**
When a value is an array, `errors.array` will be an array.

**Codesandbox link (Required)**
https://codesandbox.io/s/epic-jackson-gy001?file=/src/App.tsx

**Expected behavior**
`errors.array?.message` should be valid.

**Additional context**
- "react-hook-form": "6.9.2"
- [commit: improve type](https://github.com/react-hook-form/react-hook-form/commit/437eb09ba758b64f056705f9c31dd626b09ceb28)

**Comment by bluebill1049** [comment]
try this type: https://react-hook-form.com/ts#NestedValue

**Comment by bluebill1049** [comment]
offical doc eg: https://codesandbox.io/s/react-hook-form-v6-controller-ts-4dpm9
