### ISSUE TITLE
MODULE_NOT_FOUND: react-hook-form/dist/index.js

### ISSUE THREAD

**Issue by numToStr** [react-hook-form/react-hook-form#3192]
**Describe the bug**
After updting from `6.9.2` to `6.9.3`, I am keep getting this error.

```
Error: Cannot find module '/home/hello/Documents/code/hrms/node_modules/react-hook-form/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:315:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:528:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:818:27)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hello/Documents/code/project/node_modules/@hookform/resolvers/dist/zod.js:4:27)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/hello/Documents/code/project/node_modules/react-hook-form/package.json',
  requestPath: 'react-hook-form'
}
```
When I checked the `node_modules/react-hook-form`, indeed there was no `dist/index.js`.

**Packages**

- react: 16.4.0
- react-hook-form: 6.9.3
- @hookform/resolvers: 1.0.0
- nextjs: 9.5.5
- Typescript: 4.0.3

**Desktop (please complete the following information):**

- OS: Manjaro Linux
- Browser: Chromium 86

**Additional context**
I tried reinstalling packages after deleting `node_modules` but no luck.

**Comment by 99uno** [comment]
Same issue!!

**Comment by thongbn** [comment]
me too

**Comment by nguyenduy98** [comment]
same issue !!!

**Comment by schrimpium** [comment]
same issue

**Comment by nguyenduy98** [comment]
Resolve : 
try run npm install command again :)

**Comment by nguyenduy98** [comment]
Resolve : ( this working for me )
try run command again : npm install.

**Comment by thongbn** [comment]
Still got error.
![image](https://user-images.githubusercontent.com/14286010/96347981-1e2a4880-10d8-11eb-8b3e-f8cf895482e4.png)

**Comment by schrimpium** [comment]
> Still got error.
> ![image](https://user-images.githubusercontent.com/14286010/96347981-1e2a4880-10d8-11eb-8b3e-f8cf895482e4.png)

exactly same error

**Comment by bluebill1049** [comment]
Thanks, guys, strange issue, I will get a beta out see if resolve this issue.

**Comment by bluebill1049** [comment]
`react-hook-form@6.9.4-beta.1` please let me know if this beta fix the issue.

**Comment by bluebill1049** [comment]
i have reverted the script change at master and republish a patch for this issue.

**Comment by alenvlahovljak** [comment]
Try to delete node_modules, then install it again. I'm using Yarn, and that solved the problem.

**Comment by takayanomasashi2** [comment]
@bluebill1049 
react-hook-form@6.9.4-beta.1 worked!
thx a lot!
