### ISSUE TITLE
Yup validation not working with latest version of RHF.

### ISSUE THREAD

**Issue by bkiern** [react-hook-form/react-hook-form#3198]
I'm just getting started with RHF... looks amazing btw... and I've been following some tutorials from Maksim Ivanov. 

It this example you can only upload files under 2mb and in jpeg format. If you try to upload a png for example it triggers a validation error from yup.

It works as expected on the version included in the repo (version 5.7.2).

The issue is when I update to the latest version of RHF (6.9.4) as of this moment. The validation no longer works. Now you can upload any file type of any size. 

**To Reproduce**
1. Go to the codesandbox link provided and use version 5.7.2 of RFH. Upload a jpeg file under 2mb and on submit an alert will fire with the upload details.
2. Now upload a png file or any file other than a jpeg and on submit a validation error from yup will fire.
3. Update to the latest version of RFH and the validation from yup no longer works.

Link to example

https://codesandbox.io/s/boring-beaver-9i96n

I've only tested this on a web app on chrome.

**Comment by bluebill1049** [comment]
oops you need @hookform/resolver :) we support more than just `Yup` now: https://github.com/react-hook-form/resolvers

**Comment by bluebill1049** [comment]
you can read more at the doc: https://react-hook-form.com/api#useForm

**Comment by bkiern** [comment]
ahh... so it was a version 6 change. I added the  yup resolver and it works perfect now. Thanks!

**Comment by bluebill1049** [comment]
Yea, we want to support more than just Yup 👍

**Comment by bluebill1049** [comment]
by the way, there is a changelog in the repo as well, feel free to check it out there.
