### ISSUE TITLE
Fuzzy behavior from allowing values (dot / bracket notation) to determine behavior.

### ISSUE THREAD

**Issue by clehene** [react-hook-form/react-hook-form#3199]
Decided to open a new issue instead of commenting on a closed one (https://github.com/react-hook-form/react-hook-form/issues/676) 

1) Libraries are not supposed to be fuzzy in their behavior. As a library, the contract should be determined by the API / interface, not the actual variables that are being passed through. I.e. the values are not and can't be *the interface*. It's not something you can just document and consider solved, it fails silently, causing more harm and wasted time along the way. 

2) as a *validation*  library, the expectation is that it does robust validation. Instead this flaky validation as it silently fails and cause the same problems that it promises to solve - i.e. defeats its purpose. 

It's not just one example, it's an entire class of use-cases where this breaks silently - practically any externally fed content will be affected.

@bluebill1049 I think you should reconsider this design decision. 

Here's an example https://formik.org/docs/guides/arrays#avoid-nesting 
I think it can be done better.

If there's something that the users can do to avoid this, it should be possible to and should be handled internally (without having the user implement logic on top). Also this should be determined through the contract / interface which should be an `enableNestedFields` flag. I believe the default should be disabled.

**Comment by bluebill1049** [comment]
First of all, thanks for your feedback. Although I disagree with your comments above, I prefer you to send a feature request and I will post on the project board and be decided with the user's request and tagged with waiting for an upvote.
