### ISSUE TITLE
rseset not triggering re-rendering

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#320]
@bluebill1049 https://codesandbox.io/s/react-hook-form-array-watch-issues-bm7qt

On the "not working" input, after you select once, no further changes will be watched. The only difference to get it working correctly is adding the "true" for shouldValidate in the setValue function.

One weird thing I did notice is that this only seems to happen when the select inputs are child components and setValue/watch are passed down as props. If everything is inside the same component/render function, watch() seems to work correctly.

_Originally posted by @dpgalloway in https://github.com/react-hook-form/react-hook-form/issues/256#issuecomment-532892022_

**Comment by bluebill1049** [comment]
i have patched with react-hook-form@3.23.10-beta.5 will be released in the next patch.

**Comment by dpgalloway** [comment]
I'm having another issue that seems to be related, but might have been fixed with this patch. When I call the reset function, it does not trigger the watch or re-render. I can create a sandbox, or I can wait to try out this new patch to see if it's already resolved.

**Comment by bluebill1049** [comment]
@dpgalloway it could be related if you can reproduce a codesandbox would help a lot

**Comment by dpgalloway** [comment]
@bluebill1049 Here you go: https://codesandbox.io/s/react-hook-form-reset-issues-otejk

When you call the reset function, the watch values stay the same, and are only updated after you change a selection on the form.

**Comment by bluebill1049** [comment]
Sweet thanks a lot for the codesandbox I will investigate

**Comment by bluebill1049** [comment]
it's actually working @dpgalloway try to call watch outside of `render`, you should get the correct result. but during `render` it's not render the correct value seems like a React bug?

**Comment by dpgalloway** [comment]
I just updated to set values outside of the return statement and the behavior is the same for me. Check the sandbox and let me know if you see the same or if I'm missing something

**Comment by bluebill1049** [comment]
@dpgalloway yea try to console log the output, you will see the result is actually correct

**Comment by dpgalloway** [comment]
Ah yeah that's weird behavior. I'm displaying the selected values beside the form in my app so that makes sense why it's a bug for me. I noticed that if I run a `setValue` statement right after the reset, it re-renders correctly. I need to do so anyways for my react-select inputs, so it's not a critical bug for me, but good to be aware of.

**Comment by bluebill1049** [comment]
@dpgalloway i think i have found a solution, will release another beta. we can release this patch with al the fix

**Comment by bluebill1049** [comment]
`react-hook-form@3.23.10-beta.7`

**Comment by bluebill1049** [comment]
fixed @dpgalloway

**Comment by dpgalloway** [comment]
Thanks!

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/releases/tag/v3.23.10

closing this issue, just published the fix
