### ISSUE TITLE
React-input-mask with React-hook-form

### ISSUE THREAD

**Issue by vrg-success** [react-hook-form/react-hook-form#3201]
**Describe the bug**
When I first time start typing, I got empty value instead typed

**To Reproduce**
1. Click on date field
2. Start type text

https://codesandbox.io/s/react-hook-form-get-started-forked-vxokb?file=/src/index.js

**Comment by bluebill1049** [comment]
use Controller instead of the register for inputMask: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r

**Comment by vrg-success** [comment]
@bluebill1049  Tnx you for fast response and help

**Comment by bluebill1049** [comment]
np @vrg-success
