### ISSUE TITLE
Add touched to Controller's render prop

### ISSUE THREAD

**Issue by lazyd3v** [react-hook-form/react-hook-form#3204]
**Background**
In the app I'm working on, we have green checkmarks if some field is valid. To achieve that, we're using "touched" formState and have a logic like this under the hood:

```js
if (!isTouched) {
  return null
}

if (!errorMessage) {
  return <CheckmarkIcon />
}

return <CrossIcon />
```

**Problem**
Currently, there're two ways to access `touched` formState - get it from `useForm` or `useFormContext`. If you're intensively using custom components wrapped in `<Controller>` it could be not convenient and "clean", because you need to either do prop drilling, either create your own wrapper of `<Controller>`.

It would be nice if `<Controller>` will return `touched` value related to the individual property via render prop. Something like:

```jsx
<Controller
  control={control}
  name="test"
  render={({ onChange, onBlur, value, name,  touched }) => (
    <CustomInput
      onBlur={onBlur}
      onChange={e => onChange(e.target.value)}
      value={value}
      touched={touched}
      name={name}
    />
  )}
/>
``` 

Probably, it's even better if `<Controller>` will return `fieldState` (or something like this) via render prop. So we will be able to get touched, isDirty for individual field like this

```jsx
<Controller
  control={control}
  name="test"
  render={({ onChange, onBlur, value, name, fieldState: { touched, isDirty } }) => (
    <CustomInput
      onBlur={onBlur}
      onChange={e => onChange(e.target.value)}
      value={value}
      touched={touched}
      name={name}
    />
  )}
/>
```

**Additional context**
I can try to implement it and create a PR if you have nothing against this feature request :)

**Comment by bluebill1049** [comment]
Take a look at this section: https://react-hook-form.com/advanced-usage#ExtendController hopefully that's all you need.

**Comment by bluebill1049** [comment]
let me know if the above doesn't solve your problem.

**Comment by lazyd3v** [comment]
Yes, I think this method solves my problem. Thanks :)
