### ISSUE TITLE
useWatch value not updated after reset

### ISSUE THREAD

**Issue by natac13** [react-hook-form/react-hook-form#3205]
I am having a similar issue as #2771. However that sandbox is working as I would expect. See here https://codesandbox.io/s/funny-kalam-gf05v?file=/src/App.js

However when I update to the latest react-hook-form, 6.9.4 It does not work as expected. The useWatch value is not updated! See below for updated sandbox.

https://codesandbox.io/s/dazzling-swirles-33see?file=/src/App.js

*Note* The only change I made was to the react-hook-form package version

**Comment by bluebill1049** [comment]
@natac13 can you share the steps to reproduce?

**Comment by natac13** [comment]
The second link is to a sandbox with the updated react-hook-form, which leads to the reset call not updating the watched value as it does in the first link. What more did you need @bluebill1049? Sorry for my confusion.

**Comment by bluebill1049** [comment]
oh no worries @natac13 it's at the `useEffect` i will take a look at during lunch time or after work 👍

**Comment by natac13** [comment]
In the first link the reset call updates the watched value of the first component and a statement is logged in the console.log view. However when I updated the react-hook-form package to 6.9.4 and created the second link the usewatch is no longer updated.

Thanks for the help.

**Comment by ChrisSargent** [comment]
I seem to be experiencing a similar issue too - it is fixed now in the CodeSandbox provided? If not, I can try to create a new one.

In code like this, the two logged values are not the same after resetting the form (`watch` passed as a prop vs `useWatch`)

```tsx
export const SelectStockLevel: React.FC<SelectFieldProps> = ({ control, name, watch }) => {
  console.log( useWatch({ control, name }) );
  console.log( watch(name) );
  ...
}
```

**Comment by natac13** [comment]
Hey @ChrisSargent, The newest version 6.9.5 works great from me! Thanks to @bluebill1049

**Comment by bluebill1049** [comment]
Thanks for reporting @natac13 👍

**Comment by ChrisSargent** [comment]
@bluebill1049 - I still have this issue where the two logged values are not the same after resetting the form (watch passed as a prop vs useWatch)

export const SelectStockLevel: React.FC<SelectFieldProps> = ({ control, name, watch }) => {
  console.log( useWatch({ control, name }) );
  console.log( watch(name) );
  ...
}

**Comment by bluebill1049** [comment]
> @bluebill1049 - I still have this issue where the two logged values are not the same after resetting the form (watch passed as a prop vs useWatch)
> 
> ```tsx
> export const SelectStockLevel: React.FC<SelectFieldProps> = ({ control, name, watch }) => {
>   console.log( useWatch({ control, name }) );
>   console.log( watch(name) );
>   ...
> }
> ```

Could you please share a codesandbox?

**Comment by ChrisSargent** [comment]
@bluebill1049 - sorry for the delay, here you go: https://codesandbox.io/s/loving-bartik-q67ld?file=/src/App.js

Just type something in the form and then hit the Reset button

**Comment by natac13** [comment]
https://codesandbox.io/s/charming-cookies-xf3yl

If you call reset with the `defaultValues` then I think you may get the expected result?

**Comment by bluebill1049** [comment]
@chrisparton1991 we have an improvement on `useWatch` and `watch`, it may resolve this problem. Schedule to release this weekend.

**Comment by ChrisSargent** [comment]
> https://codesandbox.io/s/charming-cookies-xf3yl
> 
> If you call reset with the `defaultValues` then I think you may get the expected result?

@natac13 , I'd say it would achieve the _desired_ result, not the _expected_ result :-). I'm already passing watch as a workaround but yeah, that would probably work too. However, when using useWatch, it's normally because your component is deeply nested and passing down your defaultValues wouldn't be practical.

@bluebill1049 - okay great, I'll keep my eyes open. p.s. I think you mentioned the wrong Chris in the last message.

**Comment by ChrisSargent** [comment]
@bluebill1049 - just wanted to say that I updated the version and re-checked my Sandbox - I can confirm this is now fixed.

**Comment by bluebill1049** [comment]
Thank you very much for the confirmation @ChrisSargent

**Comment by andrejunges** [comment]
@bluebill1049 
I noticed a strange behavior today and ended up in this ticket during my debugging research.
There's a bug in the `useWatch` when its watching multiple fields and have a default value.

i.e.
```
const { test: textFieldWithDefaultValue } = useWatch({
  name: ["test"],
  control: control,
  defaultValue: {
    test: "MY DEFAULT"
  }
});
```

The default value `MY DEFAULT` does show up fine, but it doesn't update when `reset` is invoked.
When the input is manually update, it works fine.

Created based on a sandbox used here.
https://codesandbox.io/s/practical-albattani-3ruos?file=/src/App.js
