### ISSUE TITLE
Custom Id

### ISSUE THREAD

**Issue by arwinder3** [react-hook-form/react-hook-form#3207]
**Description**
_I don't think this is a bug, its more to do with my understanding I think._

I'd like to attach a custom id to each object in the array. In the sandbox mentioned below, I basically track the item count and append a new object using the task count in the id.

**To Reproduce**
Use append to add a new object with a pre-determined id, for example, `append({id: "customId"})`. customId will be unique.
1. Go to the sandbox link
2. Click on the add button...add a few
3. Click on save
4. Inspect console

Expected
id of each task has the custom id

Actual
id is an empty string

**Sandbox:** https://codesandbox.io/s/hardcore-worker-2xe1f?file=/src/App.js

**Comment by bluebill1049** [comment]
you can change the keyName to "others", so id doesn't get conflicted. Closing this issue now, but feel free to ask more question if this is not the answer.

<img width="931" alt="Screen Shot 2020-10-20 at 9 48 41 am" src="https://user-images.githubusercontent.com/10513364/96519762-710f2600-12b9-11eb-9bf3-03c3482d1b59.png">

**Comment by bluebill1049** [comment]
the next version 7.23.0 

https://github.com/react-hook-form/react-hook-form/releases/tag/v7.23.0-next.0
https://github.com/react-hook-form/react-hook-form/releases/tag/v7.23.0-next.1 

```tsx
const App = () => {
  const { control, register, handleSubmit } = useForm<FormValues>({
    defaultValues: {
      test: [{id: 'UUID5678', test: 'data' }] // id will be remained as it match default keyName
    }
  });
  const { fields, append } = useFieldArray({
    control,
    name: 'test',
  });

  return (
    <form>
      {fields.map((field, index) => {
        return <input key={field.id} {...register(`test.${index}.test`)} />;
      })}

      <button
        type={'button'}
        onClick={() => {
          append({
            id: 'UUID1234', // id value will be remained as it match default keyName
            test: '1234',
          });
        }}
      >
        append
      </button>
      <button>submit</button>
    </form>
  );
};
```

will no longer remove id from user's data.

**Comment by arwinder3** [comment]
Thank you so much @bluebill1049 ! super helpful.
