### ISSUE TITLE
isDirty changing to true when no field is actually dirty

### ISSUE THREAD

**Issue by vdeantoni** [react-hook-form/react-hook-form#3213]
Right after I added:

```
    defaultValues: {
      "First name": "Name"
    },
```

If you click on a field and then outside (forcing a blur) the isDirty flag will change to true, but the dirtyFields will not change.

https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-forked-7jn4k?file=/src/index.js

This was not the case with 6.7.2

**Comment by bluebill1049** [comment]
what we used to check is both `dirtyFields` and `defaultValues`, but in the later version we focused on `defaultValues` for a single source of truth, but think twice, we may need to include that check just to make sure it's not breaking user's app.

**Comment by tadger** [comment]
> This was not the case with 6.7.2

Looks like `6.8.3` was the last version where this worked as expected for me.

**Comment by ChrisSargent** [comment]
Seeing the same issue - it's behaving more like a `isTouched` rather that `isDirty`. For now, I'm working around it with:

```ts
  const isDirtyAlt = !!Object.keys(formState.dirtyFields).length;
```

**Comment by bluebill1049** [comment]
hmmm, maybe we should keep the dirtyFields check internal as well... I will think about it, I was hoping to have a single source of truth.

**Comment by ChrisSargent** [comment]
It looks like this code is setting the `isDirty` flag right now:

```ts
  const isFormDirty = () =>
    !deepEqual(
      getValues(),
      isEmptyObject(defaultValuesRef.current)
        ? defaultValuesAtRenderRef.current
        : defaultValuesRef.current,
    );
```

Which means that (I think) if I've used `setValue` and explicitly set `shouldDirty: false`, the formState will still show `isDirty: true`

**Comment by bluebill1049** [comment]
> It looks like this code is setting the `isDirty` flag right now:
> 
> ```ts
>   const isFormDirty = () =>
>     !deepEqual(
>       getValues(),
>       isEmptyObject(defaultValuesRef.current)
>         ? defaultValuesAtRenderRef.current
>         : defaultValuesRef.current,
>     );
> ```
> 
> Which means that (I think) if I've used `setValue` and explicitly set `shouldDirty: false`, the formState will still show `isDirty: true`

we used to have or not empty `dirtyFields`.

**Comment by Kizmar** [comment]
Is this fix released? I'm on version 6.12.1 and running into this issue where `isDirty: true`, but `dirtyFields: {}`. It's specifically happening when I collapse a panel that's open by default. Something is triggering `isDirty` `true`, but the form itself appears unchanged when reviewing `getValues()`. I've tried with and without setting `defaultValues` with `useForm`, same result.

```
 {
    "isDirty": true,
    "dirtyFields": {},
    "isSubmitted": false,
    "submitCount": 0,
    "touched": {},
    "isSubmitting": false,
    "isSubmitSuccessful": false,
    "isValid": true,
    "errors": {}
}
```

**Comment by bluebill1049** [comment]
> Is this fix released? I'm on version 6.12.1 and running into this issue where `isDirty: true`, but `dirtyFields: {}`. It's specifically happening when I collapse a panel that's open by default. Something is triggering `isDirty` `true`, but the form itself appears unchanged when reviewing `getValues()`. I've tried with and without setting `defaultValues` with `useForm`, same result.
> 
> ```
>  {
>     "isDirty": true,
>     "dirtyFields": {},
>     "isSubmitted": false,
>     "submitCount": 0,
>     "touched": {},
>     "isSubmitting": false,
>     "isSubmitSuccessful": false,
>     "isValid": true,
>     "errors": {}
> }
> ```

can you share a codesandbox for this?

**Comment by Kizmar** [comment]
@bluebill1049 I think my case may have more to do with the use of Material-UI's Accordion component. Still troubleshooting. Disregard my message. I'll follow up again if it looks like it's related to this library.

**Comment by bluebill1049** [comment]
> @bluebill1049 I think my case may have more to do with the use of Material-UI's Accordion component. Still troubleshooting. Disregard my message. I'll follow up again if it looks like it's related to this library.

all good, let me know if anything i could help.

**Comment by mackankowski** [comment]
@bluebill1049 @Kizmar In my current project we are migrating from v5 to v6 and we've noticed that in a hundred places isDirty's just stopped working as expected. Are you suggesting to replace all `isDirty` with `!!Object.keys(dirtyFields).length` in the entire production-living application?

**Comment by Kizmar** [comment]
@mackankowski We were able to get past this issue without using the `dirtyFields` property. The issue we were having was related to how we were setting/re-setting form values as selection changed or something was re-rendered. This is entirely dependent on how things are built, so there isn't one answer or fix I can type up here.

**Comment by mackankowski** [comment]
@Kizmar thank you for answer! My motivation was to get rid of isDirty flag in entire applications and relying only on dirtyFields. I cannot see a value of isDirty after upgrading to v6, even if I have empty default values and I reset all the form inputs as soon as data is fetched from external service.

**Comment by bluebill1049** [comment]
> @Kizmar thank you for answer! My motivation was to get rid of `isDirty` flag in entire applications and relying only on `dirtyFields`. I cannot see a value for `isDirty` after upgrading to v6, even if I have empty default values and I reset all the form inputs as soon as data is fetched from external service.

hey @mackankowski i have answered you in the other issue as well, always provide a `defualtValues` for hook form to compare with what's in your form. if this still not helping, fire a discussion provide a codesandbox, we can work this out.

**Comment by mackankowski** [comment]
@bluebill1049 After many hours of investigation, I'm not able to reproduce the issue in codesandbox (there everything works as expected...), but my application is broken in many areas after v5->v6 migration. Regarding the `isDirty` wrong value, in one place switching from uncontrolled input to Controller just made magic and it has started working... I have to underline that together with my team we've has been working a lot on using v5 of the library and we still under investigation, so I don't want to bother you too much. Thanks for your support.

**Comment by bluebill1049** [comment]
> @bluebill1049 After many hours of investigation, I'm not able to reproduce the issue in codesandbox (there everything works as expected...), but my application is broken in many areas after v5->v6 migration. Regarding the `isDirty` wrong value, in one place switching from uncontrolled input to Controller just made magic and it has started working... I have to underline that together with my team we've has been working a lot on using v5 of the library and we still under investigation, so I don't want to bother you too much. Thanks for your support.

@mackankowski just so you know, you have my support, feel free to send a question with your discovery at Github Discussion, i am more than happy to assist during my free time.

**Comment by vvo** [comment]
Small note because I faced a similar issue @mackankowski, I had a defaultValues object that contained MORE properties than the actual fields that were registered through react-hook-form. Which triggered this weird state of isDirty: true while dirtyFields was {}.

I think it's good that we enforce consistency here (fields in defaultValues must be the same as registered fields), but I wish it was more obvious that I made a mistake.

**Comment by bluebill1049** [comment]
> Small note because I faced a similar issue @mackankowski, I had a defaultValues object that contained MORE properties than the actual fields that were registered through react-hook-form. Which triggered this weird state of isDirty: true while dirtyFields was {}.
> 
> I think it's good that we enforce consistency here (fields in defaultValues must be the same as registered fields), but I wish it was more obvious that I made a mistake.

Thanks @vvo do you think there is a good spot to improve the documentation and we can include this information?

**Comment by vvo** [comment]
Yes I guess just at the defaultValues section, a note that says "For dirty checking to work properly, be sure to pass only values that you'll register inputs for. Do not pass extra properties that are not part of your form."

That plus, do you think there would be an easy way to warn developers of bad usage at this state automatically?

**Comment by bluebill1049** [comment]
> Yes I guess just at the defaultValues section, a note that says "For dirty checking to work properly, be sure to pass only values that you'll register inputs for. Do not pass extra properties that are not part of your form."
> 
> That plus, do you think there would be an easy way to warn developers of bad usage at this state automatically?

<img width="1027" alt="Screen Shot 2020-12-23 at 10 49 36 am" src="https://user-images.githubusercontent.com/10513364/102943566-8ea47a00-450c-11eb-8981-973d1dab5fb0.png">

we have that in the formState section, maybe it's worth to state that at `defaultValues` as well.

> That plus, do you think there would be an easy way to warn developers of bad usage at this state automatically? 

it's a bit difficult as the `type` is at compile-time, otherwise, we could have a dev warning to developers.

**Comment by cwiese** [comment]
> Small note because I faced a similar issue @mackankowski, I had a defaultValues object that contained MORE properties than the actual fields that were registered through react-hook-form. Which triggered this weird state of isDirty: true while dirtyFields was {}.
> 
> I think it's good that we enforce consistency here (fields in defaultValues must be the same as registered fields), but I wish it was more obvious that I made a mistake.

YES!   thank you!

**Comment by vvo** [comment]
A small comment, you can also experience this behavior if you pass defaultValues: {name: undefined}. While the name input will be `""` empty string (there's no concept of "undefined" input values, only empty strings).

On the next dirty check `undefined !=== ""` thus leading to a dirty state with no dirty fields.

**Comment by norayr93** [comment]
So what's the current behaviour ? Because I am facing the same issue again with latest version.

**Comment by vvo** [comment]
@norayr93 cases where dirty could be true without fields actually be dirty (empty dirtyFields):
- defaultValues contains more properties than the actual number of registered fields (register()..)
- defaultValues contains properties whose value is "undefined", it should be "" in this case

Other than that, no knowledge of any other surprising behavior of dirty flag. If you find another one do comment here though!

**Comment by vvo** [comment]
At this point I think I was born to discover edge cases. Welcome to another episode of "Dirty Or Not, Here I Come".

Here's another case of dirty going for true and never going back to false afterwards. Let's say you're building a form that as a number selector (`<input type="number"`) AND you pass it actual number values (to defaultValue and defaultValues) this way:

```js
const numberValue = 10;

const form = useForm({
  defaultValues: {
    numberField: numberValue
  }
});
```

You'll get in trouble! Why? Because a number input value is actually ... a string! So when react hook form compares "10" to 10 to check for dirty state it will say it's dirty, while it's not from your POV.

I wonder if I am doing something wrong OR not doing something right as for serialization between my form and my actual data types.. Any idea? Should we do a bit of type checking between defaultValues and form values? So we could warn in console like "numberField defaultValue was a `number` but form says it's a `string`, you might want to double check that".

WDYT?

Thanks!

**Comment by jgomez-nydig** [comment]
> At this point I think I was born to discover edge cases. Welcome to another episode of ["Dirty Or Not, Here I Come"](https://www.youtube.com/watch?v=aIXyKmElvv8).
> 
> Here's another case of dirty going for true and never going back to false afterwards. Let's say you're building a form that as a number selector (`<input type="number"`) AND you pass it actual number values (to defaultValue and defaultValues) this way:
> 
> ```js
> const numberValue = 10;
> 
> const form = useForm({
>   defaultValues: {
>     numberField: numberValue
>   }
> });
> ```
> 
> You'll get in trouble! Why? Because a number input value is actually ... a string! So when react hook form compares "10" to 10 to check for dirty state it will say it's dirty, while it's not from your POV.
> 
> I wonder if I am doing something wrong OR not doing something right as for serialization between my form and my actual data types.. Any idea? Should we do a bit of type checking between defaultValues and form values? So we could warn in console like "numberField defaultValue was a `number` but form says it's a `string`, you might want to double check that".
> 
> WDYT?
> 
> Thanks!

This should be documented as well along with the extra fields being included in the default values

**Comment by rainy-me** [comment]
I think I just encountered a similar problem like @Kizmar's , I was putting the `useForm` hook at the same level of the `Dialog` component and the form itself was inside the`Dialog`. Every time when I close the `Dialog`, something renders and makes the form dirty (was also changing the `dirtyFields`). After seperating the `useForm` hook and form to another component everything works fine as expected.

**Comment by benhickson** [comment]
Ran into this today, @vvo 's note about `undefined` in defaultValues fixed my issue. 🙌

I was thinking: what if instead of passing default values to both the `<input />`s, and the `useForm()`, instead we only pass them once, to `useForm()`, and spreading the `...register()` passes the default value to the input? That might be a bit easier to manage, and might make it easier to not end up in these edge cases.

**Comment by crtl** [comment]
This is still an issue or maybe im doing something wrong:

```ts
    const {watch, reset, register, handleSubmit, formState: {isDirty, errors, dirtyFields}} = useForm<EditProfileFormData>({
        mode: "onChange",
        defaultValues: {
            username: profile.username,
        }
    });
    // Will log "render true {}" which makes no sense
    console.log("render", isDirty, JSON.stringify(dirtyFields));
    
  <InputWrapper>
    <Label htmlFor="username">{t("Username")}</Label>
      <Input type="text" {...register("username", {
        required: true,
        minLength: 3,
        maxLength: 30,
        pattern: /^[\w.\-]{3,30}$/},
      )} />
    </InputWrapper>
```

`isDirty` will be true but `dirtyFields` will be empty when focus and blur on input without changing anything.

Im using `react-hook-form@7.12.2`

**Comment by kondei** [comment]
The same problem occurs when the form contains a material-ui v5 DatePicker, if I change only the other text fields.

**Comment by kondei** [comment]
In my case, forms in dialog (its first state is hidden) seem to generate this mismatch problem.

**Comment by kondei** [comment]
I resolved this problem by splitting form hooks of forms in dialog and in others.

**Comment by ThiagoMaia1** [comment]
How can I use the `Object.keys(dirtyFields).length` workaround in a way that causes a rerender, inside a useEffect for example? If I just use the dirtyFields property it doesn't get updated. I've tried using watch() but it causes infinity updates.

**Comment by ulken** [comment]
> How can I use the `Object.keys(dirtyFields).length` workaround in a way that causes a rerender, inside a useEffect for example? If I just use the dirtyFields property it doesn't get updated. I've tried using watch() but it causes infinity updates. 

Depends on what your condition is to re-render. If you want to re-render every time `dirtyFields` changes, pass `Object.keys(dirtyFields).lengt` as a dependency to `useEffect()`:

```ts
useEffect(() => {
 // do whatever
}, [Object.keys(dirtyFields).length]);
```

If you only want to act if dirty or not, add a check within `useEffect()`.

I haven't tested, but should work?

**Comment by ThiagoMaia1** [comment]
@ulken Hey, thanks a lot, having `Object.keys(dirtyFields).length` as a dependency was perfect. I actually didn't know this was possible. The hook does warn me to have it saved to a variable so that the complex expression can be evaluated as a dependency, I always thought this was something that didn't work because I thought the variable in the closure would not be updated, so it would trigger the effect. Glad I learned this. Thank you!

**Comment by bluebill1049** [comment]
> @bluebill1049 I'm probably missing something, but does it have to be any more complicated than isDirty = Object.keys(dirtyFields).length > 0?

Not really, `isDirty`  is a deep equal  again your `defaultValues`, while `dirtyFields` is checking against each input with your `defaultValue` value (We avoid each keystroke to check every single inputs, so only focus on the single input which user is interacting with). If this is an issue please reproduce it in the codesandbox, happy to take a look at it.

**Comment by pdevito3** [comment]
ran into this same issue due to this:

> At this point I think I was born to discover edge cases. Welcome to another episode of ["Dirty Or Not, Here I Come"](https://www.youtube.com/watch?v=aIXyKmElvv8).
> 
> Here's another case of dirty going for true and never going back to false afterwards. Let's say you're building a form that as a number selector (`<input type="number"`) AND you pass it actual number values (to defaultValue and defaultValues) this way:
> 
> ```js
> const numberValue = 10;
> 
> const form = useForm({
>   defaultValues: {
>     numberField: numberValue
>   }
> });
> ```
> 
> You'll get in trouble! Why? Because a number input value is actually ... a string! So when react hook form compares "10" to 10 to check for dirty state it will say it's dirty, while it's not from your POV.
> 
> I wonder if I am doing something wrong OR not doing something right as for serialization between my form and my actual data types.. Any idea? Should we do a bit of type checking between defaultValues and form values? So we could warn in console like "numberField defaultValue was a `number` but form says it's a `string`, you might want to double check that".
> 
> WDYT?
> 
> Thanks!


And seem to have it resolved with this method. This (or this: `isDirty = Object.keys(dirtyFields).length > 0`) seem to behave much more like I would expect `isDirty` to work vs the current implementation.

> Seeing the same issue - it's behaving more like a `isTouched` rather that `isDirty`. For now, I'm working around it with:
> 
> ```ts
>   const isDirtyAlt = !!Object.keys(formState.dirtyFields).length;
> ```

any new thoughts on this @bluebill1049? Seems overly complex and more rigid as it is currently

**Comment by benhickson** [comment]
@pdevito3 I worked around that issue by typing my default values and props in number fields as strings and coercing numbers to strings everywhere else. Everything is a string, and that seemed to make `isDirty` work as expected.
