### ISSUE TITLE
setValue(arrayField, [...values]) version over 6.9.2 not working

### ISSUE THREAD

**Issue by leimantas** [react-hook-form/react-hook-form#3215]
**Describe the bug**
setValue(arrayField, [...values]) not working

**To Reproduce**
https://codesandbox.io/s/sweet-pond-wbhy3?file=/src/App.js

**Additional context**
It seems it does not work with version over 6.9.2.
6.9.2 is last working version.

**Comment by bluebill1049** [comment]
patched with 6.9.5 👍
