### ISSUE TITLE
Consider adding a note about id being automatically added by useFieldArray

### ISSUE THREAD

**Issue by DamodarSojka** [react-hook-form/react-hook-form#3217]
**Is your feature request related to a problem? Please describe.**
I have a form collecting a list of ids, naturally I modelled the data as { ..., array: {id: UUIDv4}[] }. Used useFieldArray hook for it, all good except I didn't consider the useFieldArray to add and manage an id field on it's own. It totally makes sense, however I didn't consider it to be a case which resulted in a frustraiting debuging experience.

**Describe the solution you'd like**
Add a note about the id field being created and managed to the docs (https://react-hook-form.com/api#useFieldArray), likely to the important/"The following notes" section. Also should mention that the end value won't contain this autogenerated key (if I am not mistaken here).

**Describe alternatives you've considered**
It would have been a breaking change, but I would probably follow the convention of prefixing such "private" fields somehow, double underscore, double dolar sign.

Thank you in advance for taking the time to read and respond.

**Comment by bluebill1049** [comment]
Thanks, @DamodarSojka I understand your frustration, and thanks for your feedback. have you seen the section where you can change the `keyName`?

**Comment by DamodarSojka** [comment]
Don't worry about the frustration, this is not a vent, just an overlook on my side, I did see that part. After the fact really, however I am sure I did see it earlier but didn't consider it to be important for my case. 

I definitely understand hesitation to restate the same point again in "The following notes" section if it's already pointed out above, but I would still ask for it to be considered.

**Comment by bluebill1049** [comment]
Thanks @DamodarSojka I will add this to our project board, for the next major update.

**Comment by bluebill1049** [comment]
the next version 7.23.0 

https://github.com/react-hook-form/react-hook-form/releases/tag/v7.23.0-next.0
https://github.com/react-hook-form/react-hook-form/releases/tag/v7.23.0-next.1 

```tsx
const App = () => {
  const { control, register, handleSubmit } = useForm<FormValues>({
    defaultValues: {
      test: [{id: 'UUID5678', test: 'data' }] // id will be remained as it match default keyName
    }
  });
  const { fields, append } = useFieldArray({
    control,
    name: 'test',
  });

  return (
    <form>
      {fields.map((field, index) => {
        return <input key={field.id} {...register(`test.${index}.test`)} />;
      })}

      <button
        type={'button'}
        onClick={() => {
          append({
            id: 'UUID1234', // id value will be remained as it match default keyName
            test: '1234',
          });
        }}
      >
        append
      </button>
      <button>submit</button>
    </form>
  );
};
```

will no longer remove id from user's data.
