### ISSUE TITLE
useFieldArray resets/unregisters form field manually registered after deleting, moving ... 

### ISSUE THREAD

**Issue by jlame** [react-hook-form/react-hook-form#3218]
**Describe the bug**
I'm using some complex component in my form which i register manually and setValue onChange. When using delete, move ... from fieldArray, the value are removed from form and even worst seems like my component are not registered anymore.
In my example, the "complex component is replaced by the **Test** component.

Maybe i'm doing something wrong or i forgot to do something (like i need to register it each time ? but how do i do that without ending in infinite loop with my useEffect ?), i'd really appreciate help on that one. 
Thank you ! 😄 

**EDIT:** Managed to make something work in this one : https://codesandbox.io/s/react-hook-form-usefieldarray-forked-w5hri,
i had to : 

1. Add fields as dependency of my component useEffect in order to make it register again after a remove, move ...
2. Add a watcher to keep the current value so that the useEffect use it (as a default value) when registering back

**This seems pretty heavy to me, maybe there's another way to make it work, but didn't find it yet ... and i still have some issue when moving because of the watch where it keeps the previous value, so this is not viable too**

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-forked-mvl2v
2. Click on append
3. Submit and see that the "test" value is in the form
4. Delete one item
5. Submit and see that the "test" value has been removed from the form

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-mvl2v

**Expected behavior**
The value should still be there after removing, moving etc...

**Screenshots**
![image](https://user-images.githubusercontent.com/14272767/96581401-0d492500-12da-11eb-91ea-ee978ed6254a.png)

**Desktop (please complete the following information):**

- windows 10
- Browser chrome
- Version 86

**Additional context**

**Comment by DamodarSojka** [comment]
There is definitely something wrong with the useFieldArray even in a very basic case.
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-bemv3?file=/src/index.js
1. click append 
2. click prepend

GetValues returns an empty object as seen in the {JSON.stringify(getValues())}.

**Comment by bluebill1049** [comment]
It's always better to give `inputs` to hook form at useFieldArray.

- I would turn those custom register into hidden inputs and give a try. 
- set `shouldUnregister: false`

**Comment by DamodarSojka** [comment]
Did you have a look at my comment? It's not really the same issue but I though it's related and therefore didn't create another issue for it.

**Comment by bluebill1049** [comment]
> Did you have a look at my comment? It's not really the same issue but I though it's related and therefore didn't create another issue for it.

Question: why use `getValues()` in the render? it's always going to be one render behind the real value of the form.

<img width="579" alt="Screen Shot 2020-10-21 at 8 43 10 am" src="https://user-images.githubusercontent.com/10513364/96647486-7a5fc780-1379-11eb-8272-1e0dc3ff4fca.png">

**Comment by bluebill1049** [comment]
@DamodarSojka `getValues()` is made so you can read what's in the form, call it during the render will cause the issue. eg:

1. getValue()
2. mount: <input />
3. mount: <input />

it will potentially return empty form because 2 and 3 are mounted after.

**Comment by bluebill1049** [comment]
> Did you have a look at my comment? It's not really the same issue but I though it's related and therefore didn't create another issue for it.

Also, make sure you run the latest in the CSB :)

**Comment by DamodarSojka** [comment]
> Question: why use `getValues()` in the render? it's always going to be one render behind the real value of the form.

I am passing the values to another component.
I think it also caused issues in a onBlur callback but I would need to double check that.
What would you recommend instead?

> Also, make sure you run the latest in the CSB :)
Somehow I assumed the link I forked was already latest, I also did notice issues about getValues in my project anyway (but it seems the issues are justified).

**Comment by bluebill1049** [comment]
> I am passing the values to another component.
> I think it also caused issues in a onBlur callback but I would need to double check that.
> What would you recommend instead?

I need more context.

**Comment by jlame** [comment]
> It's always better to give `inputs` to hook form at useFieldArray.
> 
> * I would turn those custom register into hidden inputs and give a try.
> * set `shouldUnregister: false`

Thank you for your reply

I just tried that using the hidden input method and the issue i bump into is that when from my complex component i try to use setValue with an object, this object is cast into a string and so i end up with "[object Object]" as a value. Is there a way to keep the object ? Because one of my complex component will output a complex object structure which i need to keep.

**Comment by bluebill1049** [comment]
> > It's always better to give `inputs` to hook form at useFieldArray.
> > 
> > * I would turn those custom register into hidden inputs and give a try.
> > * set `shouldUnregister: false`
> 
> Thank you for your reply
> 
> I just tried that using the hidden input method and the issue i bump into is that when from my complex component i try to use setValue with an object, this object is cast into a string (i guess because the register element is an input) and so i end up with "[object Object]" as a value. Is there a way to keep the object ? Because one of my complex component will output a complex object structure which i need to keep.

if you set `shouldUnregister: false` you should be able to setValue with `object`, provide a codesandbox if not working out.

**Comment by DamodarSojka** [comment]
> I need more context.

Passing value to other component - I have an array of dropdowns, user can control the number of said dropdowns, picked values can't be duplicated so each dropdown has to know what other values were already picked.

onBlur callback - onBlur event of said dropdowns is used to add empty dropdown if the blured dropdown was last and just got a value, or remove a dropdown if it blured, isn't last in the array, there are at least two other dropdowns and it's empty.

I hope this time it's not too much context!
Let me know if you need any more information.

**Comment by jlame** [comment]
> > > It's always better to give `inputs` to hook form at useFieldArray.
> > > 
> > > * I would turn those custom register into hidden inputs and give a try.
> > > * set `shouldUnregister: false`
> > 
> > 
> > Thank you for your reply
> > I just tried that using the hidden input method and the issue i bump into is that when from my complex component i try to use setValue with an object, this object is cast into a string (i guess because the register element is an input) and so i end up with "[object Object]" as a value. Is there a way to keep the object ? Because one of my complex component will output a complex object structure which i need to keep.
> 
> if you set `shouldUnregister: false` you should be able to setValue with `object`, provide a codesandbox if not working out.

So i've managed to set an object using the hidden input method, but i still have an issue when removing, moving items : 
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-s2hvs

The key is still there in the object, but the value is set to undefined when doing one of the above action.

**Comment by bluebill1049** [comment]
> > I need more context.
> 
> Passing value to other component - I have an array of dropdowns, user can control the number of said dropdowns, picked values can't be duplicated so each dropdown has to know what other values were already picked.
> 
> onBlur callback - onBlur event of said dropdowns is used to add empty dropdown if the blured dropdown was last and just got a value, or remove a dropdown if it blured, isn't last in the array, there are at least two other dropdowns and it's empty.
> 
> I hope this time it's not too much context!
> Let me know if you need any more information.

Can you produce a simple codesandbox for what you try to achieve?

**Comment by bluebill1049** [comment]
> > > > It's always better to give `inputs` to hook form at useFieldArray.
> > > > 
> > > > * I would turn those custom register into hidden inputs and give a try.
> > > > * set `shouldUnregister: false`
> > > 
> > > 
> > > Thank you for your reply
> > > I just tried that using the hidden input method and the issue i bump into is that when from my complex component i try to use setValue with an object, this object is cast into a string (i guess because the register element is an input) and so i end up with "[object Object]" as a value. Is there a way to keep the object ? Because one of my complex component will output a complex object structure which i need to keep.
> > 
> > 
> > if you set `shouldUnregister: false` you should be able to setValue with `object`, provide a codesandbox if not working out.
> 
> So i've managed to set an object using the hidden input method, but i still have an issue when removing, moving items :
> https://codesandbox.io/s/react-hook-form-usefieldarray-forked-s2hvs
> 
> The key is still there in the data object, but the value is set to undefined when doing one of the above action.

I don't think it's going to work with the way you have provided above. here is what I would do:

I would create a separate useFieldArray in the `<Test />`. -> https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-x7btr

**Comment by jlame** [comment]
Hmm, in fact i only have one array which is my items and these items come with simple field (input, select) but also more complex one. So the output object i try to have is something like : [
      { atext: "something", aNumber: 1, aDate: { startDate: new Date(), endDate: new Date() ... }},
      { atext: "another thing", aNumber: 2, aDate: { startDate: new Date(), endDate: new Date() ... }}
]

From my point of view, this is not nested array, am i wrong ?

**Comment by bluebill1049** [comment]
> Hmm, in fact i only have one array which is my items and these items come with simple field (input, select) but also more complex one. So the output object i try to have is something like : [
> { atext: "something", aNumber: 1, aDate: { startDate: new Date(), endDate: new Date() }, ...},
> { atext: "another thing", aNumber: 2, aDate: { startDate: new Date(), endDate: new Date() }, ...}
> ]
> 
> From my point of view, this is not nested array, am i wrong ?

That's not, then you should two inputs
```
<input name="test[0].aDate.startDate />
<input name="test[0].aDate. endDate />
```
