### ISSUE TITLE
`reset` does not update watched values

### ISSUE THREAD

**Issue by AlexFrazer** [react-hook-form/react-hook-form#322]
**Describe the bug**
Using `reset` from the default export does not cause the watched values to update.

**To Reproduce**
Take the following example:
```
export default function Filters() {
  const methods = useForm();
  const onSubmit = values => {
    console.log(values);
  };
  return (
    <FormContext {...methods}>
      <form onSubmit={methods.handleSubmit(onSubmit)}>
        <fieldset>
          <legend>Basic Filters</legend>
          <MySelect
            name="name"
            options={[
              { label: 'Megumin', value: 1 },
              { label: 'Aqua', value: 2 },
              { label: 'Darkness', value: 3 },
            ]}
          />
        </fieldset>
        <div>
          <button onClick={methods.reset} type="button">Clear</button>
          <button type="submit">Submit</button>
        </div>
      </form>
    </FormContext>
  );
}
```

I then create a custom `ReactSelect` using the same basic items

```
function MySelect({
  name,
  options,
  onChange,
  ...props
}) {
  const { watch, register, setValue } = useFormContext();
  const value = watch(name);
  const selected = useMemo(() => findOption(value, options), [options, value]);
  const handleChange = useCallback((option, info) => {
    setValue(name, get(option, 'value', undefined));
    if (onChange) {
      onChange(option, info);
    }
  }, [name, setValue, onChange]);
  return (
    <ReactSelect
      name={name}
      options={options}
      value={selected}
      innerRef={register({ name })}
      onChange={handleChange}
    />
  );
}
```

When I click the reset button, it doesn't cause the watched values to update

**Expected behavior**
I expect `watch` to re-run with an empty value when I use the reset method.

**Screenshots**
Not super applicable

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: chrome
 - Version: latest

**Smartphone (please complete the following information):**

**Additional context**
I am using `react-hook-form@3.23.10-beta.5`

**Comment by bluebill1049** [comment]
can you create a codesandbox for your issue? that would help a lot. thanks

**Comment by AlexFrazer** [comment]
I had an existing codesandbox, might be overkill, but it should be easy to mess around with

https://codesandbox.io/s/formik-filters-byep9

**Comment by bluebill1049** [comment]
I was hoping a codesandbox related to this issue :)

**Comment by bluebill1049** [comment]
`react-hook-form@3.23.10-beta.7` can you test out this beta version.

**Comment by AlexFrazer** [comment]
That appears to have done it exactly as expected

![image](https://user-images.githubusercontent.com/1350392/65288622-52f65580-dafc-11e9-911b-dc3b5cfd1c2e.png)

**Comment by bluebill1049** [comment]
lovely @AlexFrazer i will release this patch with other fixes tonight

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/releases/tag/v3.23.10

**Comment by bluebill1049** [comment]
please consider star the repo to support if you find it useful too (no pressure) 🙏
