### ISSUE TITLE
Firebase file upload is broken since 6.9.4

### ISSUE THREAD

**Issue by saculbr** [react-hook-form/react-hook-form#3223]
**Describe the bug**
When using shouldUnregister: false, if the form have a File field, that field never will be File or a FileList instance, but a plain object

The currently implementation of [utils/cloneObject.ts](https://github.com/react-hook-form/react-hook-form/blob/master/src/utils/cloneObject.ts) clone every [File](https://developer.mozilla.org/en-US/docs/Web/API/File) instance in an Object instance, as expected.

That cast break the firebase web sdk, in my app after debugging I discovered that firebase break if the uploaded object is not serializable, like a clone of File into Object.

**To Reproduce**

1. Go to https://codesandbox.io/s/flamboyant-chandrasekhar-qsz3d?file=/src/App.tsx
2. Upload a file
3. See that the form value of the photo field is an Object instance

**Codesandbox link (Required)**
https://codesandbox.io/s/flamboyant-chandrasekhar-qsz3d?file=/src/App.tsx

**Proposed Solution**
Maybe we can skip cloning File and FileList instances, like the current implementation does with Date objects

**Screenshots**
****

![Cloning a File instance breaks firebase upload feature](https://user-images.githubusercontent.com/4311885/96665835-2b3f7580-132c-11eb-9f29-9f4436d76e83.png)

****

**Desktop (please complete the following information):**

- OS: Linux
- Browser Chrome
- Version 86

if you agree with the proposed solution I can send a PR

**Comment by bluebill1049** [comment]
I think we may have to return the original File during the clone.

**Comment by bluebill1049** [comment]
can you plz test this beta: `6.9.6-beta.1`?

**Comment by saculbr** [comment]
> can you plz test this beta: `6.9.6-beta.1`?

Yes, tested and that release works great

Thanks man, you are the best
