### ISSUE TITLE
Controller with react-datepicker broken on v6

### ISSUE THREAD

**Issue by JavRok** [react-hook-form/react-hook-form#3228]
Hi, I've been struggling integrating react-hook-form and react-datepicker a lot. I was confused because the same example in the codesandbox was not working for me. After a lot of debugging, I noticed the react-hook-form version in the codesandbox is old (*5.5.1*) whereas I'm using latest (*6.9.5*). The input keeps empty when selecting a date starting version 6. 

I made an exact copy of the sandbox in the docs and updated to latest version
https://codesandbox.io/s/react-hook-form-controller-forked-242zs
1. Click on react-datepicker input
2. Select a date
3. ...

Input should be filled with selected date

- OS: Ubuntu on WSL2
- Browser: Chrome
- Version: 86
- Node v13

Thanks !

PD: MUI Slider seems broken too.

**Comment by Fried-Chicken** [comment]
Was just looking at the same issue, have you tried the solution posted [here](https://github.com/react-hook-form/react-hook-form/issues/2847)?

**Comment by JavRok** [comment]
Well, I don't know how I missed that issue, but thanks, it worked ! I haven't tried render props since it was 'discouraged' on the docs.

Can I suggest to update the link to latest sandbox in this page? https://github.com/react-hook-form/react-hook-form/tree/master/examples, which is outdated. This also answers this question from @pmaier983 -> https://github.com/react-hook-form/react-hook-form/issues/2847#issuecomment-688529550 

Cheers !
