### ISSUE TITLE
Scroll and focus for Controller not working

### ISSUE THREAD

**Issue by vrg-success** [react-hook-form/react-hook-form#3229]
**Describe the bug**
Auto scroll and focus for Controller not working if have error on submit form.

**To Reproduce**
1. Just click on submit button

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-get-started-forked-g5w0b?file=/src/index.js

**Expected behavior**
Scroll to phone field and focus

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#Controller
Take a look at onFoucs props
<img width="935" alt="Screen Shot 2020-10-22 at 9 14 12 am" src="https://user-images.githubusercontent.com/10513364/96792861-f6741100-1446-11eb-8f3e-c61af23fc81d.png">
