### ISSUE TITLE
[REQ] Allow manually registered inputs to easily be reset

### ISSUE THREAD

**Issue by stramel** [react-hook-form/react-hook-form#323]
**Is your feature request related to a problem? Please describe.**
Right now, it is difficult and very hacky to get a a manually registered field to reset.

**Describe the solution you'd like**
Allow some kind of reset to be passed in on the register function

**Describe alternatives you've considered**
Currently, I'm tying into the code by mocking `closest`.

```js
register({
  name: localName,
  type: 'file',
  closest: () => ({ reset: () => setValue(localName, []) }),
})
```

/cc @bluebill1049 @barrymay

**Comment by bluebill1049** [comment]
```
 for (let [, value] of fieldsKeyValue) {
      if (!value || !value.ref) break;

      if (value.ref.closest) {
        try {
          value.ref.closest('form').reset();
          break;
        } catch {}
      } else {
        setValue(value.ref.name, '');
      }
    }```
this should resovle the problem

**Comment by stramel** [comment]
@bluebill1049 Would that allow the value to fallback to a defaultValue? 

In this case, I was wanting it to reset back to an array.

**Comment by bluebill1049** [comment]
@stramel, in that case. it's better to supply reset(values)

**Comment by stramel** [comment]
Hmmm, I think that might be good enough. We can revisit that if there is more interest.

**Comment by bluebill1049** [comment]
or we can do a lookup in the default value or '' @stramel

**Comment by bluebill1049** [comment]
or we stay the same use `reset(values)`

**Comment by stramel** [comment]
@bluebill1049 using `reset({ icon: [] })` works for me.

**Comment by barrymay** [comment]
agreed - at least there's a way to do it - I'd also prefer that reset go back to default values, but this is fine
