### ISSUE TITLE
Submit empty array conditionally

### ISSUE THREAD

**Issue by bjarkehs** [react-hook-form/react-hook-form#3231]
**Is your feature request related to a problem? Please describe.**
I have an issue where I need to conditionally send an empty array. I need the user to be able to specify that they want an empty array sent to the backend or not.

**Describe the solution you'd like**
I would like a way to provide a boolean or similar to useFieldArray, which if true causes submission to be an empty array if there are no inputs, but if false it should not submit anything if the array is empty.

So like shouldUnregister but not on whole form, because there could be multiple of these arrays that can be included independently·

**Describe alternatives you've considered**
I've tried using shouldUnregister, but I still want the unregister for non-array inputs.

**Additional context**
![image](https://user-images.githubusercontent.com/2279254/96782465-8e451100-13ed-11eb-8b48-14baa4753cca.png)
If include is checked, then the array should be sent as empty, if it's not, then nothing should be sent.

**Comment by bluebill1049** [comment]
@bjarkehs if you set `shouldUnregister: false` it will send an empty array, let me know if this works for you.

**Comment by bjarkehs** [comment]
@bluebill1049 Unfortunately there's quite a few weird behaviours when I'm using `shouldUnregister: false`. I'll report those when I have more time.

The problem with `shouldUnregister: false` is that it's only available on `useForm`.

I want for instance to have 2 arrays, where 1 does not send empty array and the other does.

I have solved this for now by storing it in a context and then using lodash defaultsDeep, but it would be nice if this was supported. I do understand that not many will have such a dynamic form.

**Comment by bluebill1049** [comment]
> @bluebill1049 Unfortunately there's quite a few weird behaviours when I'm using `shouldUnregister: false`. I'll report those when I have more time.
> 
> The problem with `shouldUnregister: false` is that it's only available on `useForm`.
> 
> I want for instance to have 2 arrays, where 1 does not send empty array and the other does.
> 
> I have solved this for now by storing it in a context and then using lodash defaultsDeep, but it would be nice if this was supported. I do understand that not many will have such a dynamic form.

fair points above, please send issue around shouldUnregister: false when you have sometimes.

**Comment by bluebill1049** [comment]
in V7, it will submit an empty array `[]` as long as defaultValue is supplied.
