### ISSUE TITLE
Incorrect order on focus

### ISSUE THREAD

**Issue by vrg-success** [react-hook-form/react-hook-form#3232]
**Describe the bug**
When I try step by step fix form errors, I got incorrect focus order

**To Reproduce**

1. Click on submit button
2. fill firstName field
3. Click again on submit button

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-get-started-forked-jdx40?file=/src/index.js

**Comment by bluebill1049** [comment]
focus order is based on registration order, `Controller` will always get registered after input with `ref`.

**Comment by bluebill1049** [comment]
actually, i will leave this information in the doc as well.

**Comment by bluebill1049** [comment]
<img width="930" alt="Screen Shot 2020-10-22 at 10 26 30 am" src="https://user-images.githubusercontent.com/10513364/96800435-16103700-1451-11eb-8bf9-634289dd7347.png">

actually it's already in the doc.

**Comment by vrg-success** [comment]
> focus order is based on registration order, `Controller` will always get registered after input with `ref`.

Can you show me please how to resolve the problem with my example https://codesandbox.io/s/react-hook-form-get-started-forked-jdx40?file=/src/index.js, I rly confused

**Comment by bluebill1049** [comment]
> > focus order is based on registration order, `Controller` will always get registered after input with `ref`.
> 
> Can you show me please how to resolve the problem with my example https://codesandbox.io/s/react-hook-form-get-started-forked-jdx40?file=/src/index.js, I rly confused

use all Controller, if you focus order is important for you, or go all the way with `ref={register}`

**Comment by vrg-success** [comment]
Tnx, I appreciate your help

**Comment by bluebill1049** [comment]
np mate.

**Comment by ejose19** [comment]
@bluebill1049 I also faced this and I'm wondering if introducing a new prop (either at ```useForm``` or ```resolver```) where user can specify the focus on error order. Some components really support only a controlled mode and changing the rest for just that one seems like a cumbersome thing to do, if you can point me where to look I could work on a PR, since I'm sure this feature will be appreciated.

**Comment by bluebill1049** [comment]
> @bluebill1049 I also faced this and I'm wondering if introducing a new prop (either at `useForm` or `resolver`) where user can specify the focus on error order. Some components really support only a controlled mode and changing the rest for just that one seems like a cumbersome thing to do, if you can point me where to look I could work on a PR, since I'm sure this feature will be appreciated.

yea, we are thinking about it, but having a clean API for such functionality is hard...

**Comment by ejose19** [comment]
@bluebill1049 the other option would be to make ```Controller``` (and  thus ```useController```) indeed work in register order like using ```register```. I checked https://github.com/react-hook-form/react-hook-form/blob/60713238a4730e50512491f3205d67d7aa7744aa/src/useController.ts#L198-L205 and was wondering if there's any issue in calling ```registerField()``` right before the return so the field is registered in the correct order and then ```useEffect``` will take care of the rest on future renders. 

I tried it locally and could confirm the order was respected and couldn't notice any issues with the form, if you think this is a solution I can submit a PR.

**Comment by andrenaught** [comment]
Just ran into this issue using react-select. @bluebill1049 since the pr didn't get merged i think it would be good to update the documentation for v7 to have the "native inputs gets focused before Controllers" like in v6 docs.

**Comment by andrenaught** [comment]
Just ran into this issue using react-select. @bluebill1049 since the pr didn't get merged i think it would be good to update the v7 docs to have the "native inputs get focused before Controllers" like in v6.
