### ISSUE TITLE
After removing a field from a `useFieldArray` of `Controller` components, form does not re-render properly

### ISSUE THREAD

**Issue by acco** [react-hook-form/react-hook-form#3240]
Thanks for your work here, Bill!

Using the latest (6.9.5)

**Describe the bug**
As you can see in the CSB link below, I have a list of three inputs that are using `useFieldArray`. Each input is wrapped in a `Controller`:

```
let defaultValues = {
  foods: [{ value: "apple" }, { value: "orange" }, { value: "pear" }]
};
let { control, reset } = useForm({
  defaultValues
});
let { fields, remove } = useFieldArray({
  control,
  name: "foods"
});
```

Each are rendered wrapped inside of a Controller. When `remove(1)` is called to remove the second item in the list (orange), the _last_ item is shown as removed on the UI:

<img src="http://g.recordit.co/5nFDHYtDzk.gif" width=500 /> 

_However_, the final representation of the `fields` _is_ accurate. Leading me to believe that the issue is just that the controlled inputs are not having their new values pushed to them:

```js
[
  {
    "id": "936fc700-cac8-49fe-a5c6-e49f341164cb",
    "value": "apple"
  },
  {
    "id": "83f1a635-7d9a-41ea-b466-582f8d66855e",
    "value": "pear"  /* "orange" is missing, yet still displayed on the UI */
  }
]
```

**To Reproduce**

1. Go to https://codesandbox.io/s/naughty-resonance-c5bm3?file=/src/index.tsx
2. Click on the "remove" next to orange
3. Note that the input for _pear_ is removed. Even so, curiously, the _fields_ are still accurate (which I display below the inputs)

**Codesandbox link (Required)**

https://codesandbox.io/s/naughty-resonance-c5bm3?file=/src/index.tsx

**Expected behavior**
That the orange input is removed

**Screenshots**
See GIF above

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chromium
- Version 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report! will investigate into it.

**Comment by bluebill1049** [comment]
you are missing the `id`

`<div style={divStyle} key={food.id}>` 👍

**Comment by acco** [comment]
@bluebill1049 Oh man! That was it! 

In my code, I had the equivalent of:

```
<div style={divStyle} key={idx}> 
```

Using the _index_ as opposed to the _id_ for the key 🤦 

On second look, docs look pretty clear about this:

![image](https://user-images.githubusercontent.com/927029/96943843-1bd83d80-148e-11eb-9512-37841f9c8bcb.png)

Thanks again for your great work here and your prompt reply!

**Comment by bluebill1049** [comment]
No worries at all @acco 👍
