### ISSUE TITLE
Unregistering field doesn't trigger watch api

### ISSUE THREAD

**Issue by jorisre** [react-hook-form/react-hook-form#3245]
👋🏻 

**Describe the bug**

**To Reproduce**

In the [CodeSandbox repro](https://codesandbox.io/s/react-hook-form-unregister-v6-watch-dmbrr):
1. Fill form
2. Unregister lastname field
3. watch api isn't triggered and lastname is still displayed

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-unregister-v6-watch-dmbrr

**Expected behavior**
When unregistering a field, watch api should return undefined because the field doesn't exist anymore

**Desktop (please complete the following information):**

- OS: MacOs BigSur beta
- Browser: Chrome
- Version 86.0.4240.80 (Official Build) (x86_64)

Thanks ! :)

**Comment by bluebill1049** [comment]
hey @jorisre used the latest :) it's already patched, your CSB is using beta version.

**Comment by jorisre** [comment]
Hey @bluebill1049 !
You're right ! 
Now, I have the following use case: https://codesandbox.io/s/react-hook-form-unregister-v6-watch-dmbrr
Same example but with default values. If you change the lastname (or not) and then unregister the field, `watch` returns default value. Is this behavior right ? Or `watch` should return undefined ?

**Comment by bluebill1049** [comment]
> Hey @bluebill1049 !
> You're right !
> Now, I have the following use case: https://codesandbox.io/s/react-hook-form-unregister-v6-watch-dmbrr
> Same example but with default values. If you change the lastname (or not) and then unregister the field, `watch` returns default value. Is this behavior right ? Or `watch` should return undefined ?

Yeah, it's expected behavior, watch will return `defaultValues` when value. is `undefined`.

**Comment by jorisre** [comment]
Thanks !

**Comment by bluebill1049** [comment]
> Thanks !

No worries, let me explain why is that the case: (i think it's probably not ideal for some use case) 

- initial render with `watch('test')` will return undefined
- some UI will need a defaultValue, so user can do `watch('test', 'default)`
- or they can set up a `defaultValues` at `useForm` for `watch` to read the defaultValue of that `input`

now this will be an issue, if the user (your use-case) doesn't want the defaultValue to show up, at the moment, i haven't got a good solution for that.

**Comment by jorisre** [comment]
Thanks for explanation. It's easy for me to get `undefined` from `watch`;

On button click, it'll re-trigger watch
```ts
onClick={() => {
    reset({...getValues(), lastName: undefined});
    unregister('lastName');
}}
```
