### ISSUE TITLE
Data type change from File to Object when shouldUnregister is false

### ISSUE THREAD

**Issue by vimutti77** [react-hook-form/react-hook-form#3246]
**Describe the bug**
When shouldUnregister is false, my data has been changed from File to normal Object.

**To Reproduce**

1. Go to https://codesandbox.io/s/shouldunregister-file-w5srx?file=/src/index.jsx
2. Select file
3. Click on Submit button
4. View console

**Actual behavior**
Data is normal Object type.
![image](https://user-images.githubusercontent.com/27840664/96989564-15aa9580-1550-11eb-98ef-9df5b6f9ab9f.png)

**Expected behavior**
Data should be File type.
![image](https://user-images.githubusercontent.com/27840664/96989520-fc094e00-154f-11eb-971a-959e68f0a55d.png)

**Desktop (please complete the following information):**

- OS: Windows 10 20H2
- Browser MS Edge
- Version latest

**Comment by bluebill1049** [comment]
Thanks for the issue report 👍 

This is already patched will be released in the next update. https://github.com/react-hook-form/react-hook-form/commit/471277e4b958581519a5d91b20dba091850a3c1c

you can use this beta version for now: `6.9.6-beta.1`

**Comment by vimutti77** [comment]
@bluebill1049 this also happen on other data type such as Set & Map.

In this example: https://codesandbox.io/s/shouldunregister-set-w5srx?file=/src/index.jsx:191-195
If you change shouldUnregister to false, It will throw error `value.has is not a function`.

**Comment by bluebill1049** [comment]
I will make a list of data that we will support for `shouldUnregister: false`.

here is the list:

- Set
- Map
- Object
- Date
- File
- Object
- Array
- Primitives
