### ISSUE TITLE
Issue resetting dirtyFields 

### ISSUE THREAD

**Issue by anthonyatp** [react-hook-form/react-hook-form#3248]
**Describe the bug**
I am having an issue where I reset dirtyFields but after resetting, the fields become dirty again without any user input. This has only started happening at version **6.8.4** and later.

I have replicated my current set-up in the codesandbox link below, however, I cannot replicate the issue. So I appreciate this is very difficult to solve but any ideas as to why (at v6.8.4) this starts to happen?

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-forked-dzyw4?file=/src/index.js

**Expected behavior**
v6.8.3:
![expected](https://user-images.githubusercontent.com/42555665/96999461-154cd300-152d-11eb-9c49-fa667176387c.gif)

**Current behavior**
v6.8.4:
![current](https://user-images.githubusercontent.com/42555665/96999494-239aef00-152d-11eb-930c-1cb42742c55e.gif)

**Comment by bluebill1049** [comment]
what are the steps to reproduce the problem?

**Comment by anthonyatp** [comment]
I tried to replicate the code [here](https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-forked-dzyw4?file=/src/index.js) but the issue doesn't come up - so it's hard to see why this is happening.

The useEffect hook is triggered when one of the users is toggled, which should reset the dirty fields. As you can see from the videos, from v6.8.4, after resetting the fields become dirty again.

Is there anything in v6.8.4 that could've caused this to happen?

Sorry I know that might not be very helpful but I can't reproduce outside of my codebase.

**Comment by bluebill1049** [comment]
This is going to be difficult for me as I wouldn't know the usage (especially the dirtyFields show in the console 18 times). I will do some investigation if I can't reproduce or find anything. there is little I can help here.

**Comment by bluebill1049** [comment]
<img width="904" alt="Screen Shot 2020-10-24 at 9 37 22 am" src="https://user-images.githubusercontent.com/10513364/97059586-89927f80-15dc-11eb-9c69-b87d6f472151.png">

here are the fixed happened in 6.8.4 i don't see any direct impact on `dirtyFields`. can you use the latest version? see if the issue persists, if not good, otherwise it will be hard for me to track down the problem until a reproducible codesandbox can be provided. 🙏

**Comment by bluebill1049** [comment]
Couldn't reproduce this issue, will re-open if CSB with reproducible steps provided.

**Comment by bluebill1049** [comment]
made a new patch on master: https://github.com/react-hook-form/react-hook-form/commit/85b7b81a8e72066fa8691c9123d80c5d02df1cc3 not sure if this is a related issue (most likely not)

**Comment by anthonyatp** [comment]
Ok thank you for helping anyway - I knew this would be very hard to solve.

I will keep investigating and let you know if I'm able to reproduce

**Comment by anthonyatp** [comment]
my only idea is that there are 16 inputs on this page, hence the 16 items in the console after resetting, so perhaps the inputs are causing rerenders which is defaulting to dirty as the default values have changed for the selected user.

**Comment by anthonyatp** [comment]
just upgraded to v6.9.6 and it's now working!

I have no idea why haha but thank you again!
