### ISSUE TITLE
DeepMap error when spreading on `defaultValues`

### ISSUE THREAD

**Issue by ilovett** [react-hook-form/react-hook-form#3253]
**Describe the bug**

**To Reproduce**

Go to sandbox.

View the `defaultValues` section -- comment out the spreaded and uncomment the non spreaded.. notice the typescript error difference

**Codesandbox link (Required)**

https://codesandbox.io/s/dry-violet-z0tpe

**Expected behavior**

Types inferred without DeepMap error on the overridden defaultValues

**Screenshots**

![image](https://user-images.githubusercontent.com/1776100/97052912-be4bfb80-1536-11eb-827f-619d75c2fbc4.png)

**Additional context**

RHF 6.9.5

**Comment by bluebill1049** [comment]
shall we do this instead: https://codesandbox.io/s/ecstatic-monad-w9bc3?file=/src/App.tsx?

**Comment by ilovett** [comment]
Yes I suppose this by explicitly passing the generic, but I wonder if it *can* be inferred on the deep map?

**Comment by bluebill1049** [comment]
> Yes I suppose that works by explicitly passing the generic, but I wonder if it _can_ be inferred on the deep map?

Yes, @kotarella1110 is investigating a solution. worse case we will have to use with passing the generic.

**Comment by bluebill1049** [comment]
```
-export type DeepPartial<T> = T extends Array<infer U>
-  ? Array<DeepPartial<U>>
-  : T extends ReadonlyArray<infer U>
-    ? ReadonlyArray<DeepPartial<U>>
-    : T extends Record<string, unknown>
-      ? {
-        [K in keyof T]?: DeepPartial<T[K]>;
-      }
-      : T;
+export type DeepPartial<T> = T extends Primitive
+  ? Partial<T>
+  : {
+      [P in keyof T]?: T[P] extends (infer U)[]
+        ? DeepPartial<U>[]
+        : T[P] extends Readonly<infer U>[]
+        ? Readonly<DeepPartial<U>>[]
+        : DeepPartial<T[P]>;
+    };
```

**Comment by bluebill1049** [comment]
also, I don't think we can `infer` what's inside the `defaultValues`, because we have to take care deeply nested value with `NestedValue` type. It's safer to stay with generic at useForm.

**Comment by bluebill1049** [comment]
hey @ilovett shall we have a quick discussion here: https://github.com/react-hook-form/react-hook-form/issues/3313 I think we may need to enforce generic at `useForm`.
