### ISSUE TITLE
Error for field array item isn't cleared when registered control is removed

### ISSUE THREAD

**Issue by dwiyatci** [react-hook-form/react-hook-form#3254]
**Describe the bug**
Error prop for field array item isn't cleared when the corresponding registered control is removed from the DOM.

**To Reproduce**

1. Click on 'Remove Item C'.
2. Observe error messages in the "Error Bar".

**Codesandbox link (Required)**
https://codesandbox.io/s/rhf-error-fieldarrayitem-when-control-removed-4cu0w?file=/src/index.jsx

**Expected behavior**
Error message "Item A is required" should **not** be in the Error Bar since the corresponding registered control for Item A is removed from the DOM when Item C is removed. Error message "Item B is required" should stay put.

**Additional context**
Actually, the logic I've got in my project to show/hide some form controls based on the existence of some other form controls in the DOM is much more complex than what depicted in the CSB. So I would like to rely on the "automatic" removal of the error for such control that's no longer in the DOM, rather than using the "manual" `clearErrors(...)` API. 😬

**Comment by bluebill1049** [comment]
I have to say this codesandbox is not very clear for the problem.

<img width="712" alt="Screen Shot 2020-10-24 at 8 53 32 am" src="https://user-images.githubusercontent.com/10513364/97057164-66fd6800-15d6-11eb-8cfd-b9b4d5fd3acc.png">

shouldn't the above component to be moved outside `App`?

**Comment by dwiyatci** [comment]
Umm, sorry. 🙄 I don't think it needs to be outside of the `App` though. 

There, I basically want to express sth like:
**"Only render item A if item C exists"** 

I can surely make the CSB clearer again tomorrow if it needs be (since it's already past midnight here, I only changed `shouldShow` to `shouldRenderItem` for now). Thanks Bill!!

**Comment by bluebill1049** [comment]
> Umm, sorry. 🙄 I don't think it needs to be outside of the `App` though.
> 
> There, I basically want to express sth like:
> **"Only render item A if item C exists"**
> 
> I can surely make the CSB clearer again tomorrow if it needs be (since it's already past midnight here, I only changed `shouldShow` to `shouldRenderItem` for now). Thanks Bill!!

I think it probably needs to be a separate component, otherwise, it gets mount/unmount each re-render.

**Comment by dwiyatci** [comment]
@bluebill1049 I just updated the CSB. It's now also using `FormProvider`/`useFormContext` which I also use in my project, so it resembles the real code even more. I also refactored the field array items into its own `<ItemList>` component - hope it makes it clearer :)

**Comment by bluebill1049** [comment]
I see your problem now, you will have to `trigger` or `clearError`, we don't remove errors based on input unmount at `useFieldArray`. errors object only gets manipulated by action: (append, prepend, delete) at `useFieldArray`.

**Comment by dwiyatci** [comment]
Yup, I noticed the latter behavior (on `remove`, `insert`, etc. - it's triggered - and it's so helpful. 

And yeah, I would really like to go with `trigger()` but it doesn't seem to work (please try to uncomment `trigger()` after `remove(index)` in the CSB). Also, as I wrote in the "Additional context", `clearErrors(...)` is not an option for me.

**Comment by bluebill1049** [comment]
@dwiyatci you need to do it `useEffect` with `trigger`.

**Comment by dwiyatci** [comment]
Hmm interesting. I just updated my CSB again (https://codesandbox.io/s/rhf-error-fieldarrayitem-when-control-removed-4cu0w?file=/src/index.jsx) - unfortunately still doesn't work by doing `useEffect(() => { trigger(); }, [trigger, fields]);`. Could you show me how I'm supposed to do it in the CSB?

**Comment by bluebill1049** [comment]
@dwiyatci looks like `trigger` need to clean all errors to get this working. i am patching this with a PR.

https://codesandbox.io/s/rhf-error-fieldarrayitem-when-control-removed-forked-drt9c?file=/src/src/useForm.ts

**Comment by dwiyatci** [comment]
@bluebill1049 Aaa ok. Thanks so much for the effort! 🙇🏻‍♂️

**Comment by dwiyatci** [comment]
@bluebill1049 I just tried the new release version `6.10.1` out but the issue persisted.

- When I use `watch` API on fieldArray in any components, it fails. 😕 (without it, it works as expected though)
- `trigger()` works, but `trigger('fieldArray')` doesn't. Is this expected that we can't trigger validation for fieldArray items only?

Updated CSB: https://codesandbox.io/s/rhf-error-fieldarrayitem-when-control-removed-4cu0w?file=/src/index.jsx:581-620

**Comment by bluebill1049** [comment]
@dwiyatci this is a fixed for `trigger()`, trigger array field is a feature request, please upvote there :) 

https://github.com/react-hook-form/react-hook-form/issues/2381

**Comment by dwiyatci** [comment]
@bluebill1049 🆗 thanks, I just did. :) But what about the first point about the usage of `watch` API that doesn't make this work as expected. Is it also related?

**Comment by bluebill1049** [comment]
@dwiyatci could you share a CSB for the first case? i will take a look at it during lunch or tonight.

**Comment by dwiyatci** [comment]
@bluebill1049 It's actually already mentioned in the comment: https://codesandbox.io/s/rhf-error-fieldarrayitem-when-control-removed-4cu0w?file=/src/index.jsx:581-620

Simply uncomment line 28 - thaaanks

**Comment by bluebill1049** [comment]
thanks @dwiyatci you may want to do the following instead: 

`const items = watch('items', fields);`

<img width="950" alt="Screen Shot 2020-11-02 at 10 08 07 am" src="https://user-images.githubusercontent.com/10513364/97817899-4f6b6100-1cf3-11eb-9eec-b00fe6a7986f.png">

**Comment by dwiyatci** [comment]
Umm, I don't think that's the issue, @bluebill1049. What I mean is not about what the `watch` returns. It's just that whenever I use `watch('fieldArray', ...)`, the error is not cleared as expected. Please try to:
1. Comment/uncomment line number 28.
2. Click "Remove Item C".
3. Compare the results.

**Comment by bluebill1049** [comment]
> Umm, I don't think that's the issue, @bluebill1049. What I mean is not about what the `watch` returns. It's just that whenever I use `watch('fieldArray', ...)`, the error is not cleared as expected. Please try to:
> 
> 1. Comment/uncomment line number 28.
> 2. Click "Remove Item C".
> 3. Compare the results.

oh! sorry miss that issue, i will investigate tonight.

**Comment by dwiyatci** [comment]
Thanks a lot. Have a good lunch and rest of the day for now then.. 🥘 ⛅

**Comment by bluebill1049** [comment]
**Investigation**

This implementation is going to be troublesome, let me explain why:

- remove C
- then you `trigger`
- it should return 2 errors
- but it's working because the `trigger` is async,
- by the time validation kick in Dom can or could be updated (potential race condition), because you have conditional render in the render again. 
- hence you got the correct result, but this is not a stable solution and could lead to issue to prod build

so the correct behavior is actually triggered return two errors A and B.

**Solution**

invoke `remove()` conditional inside `useEffect` or remove(['A', 'B']) with correct conditional logic, basically `trigger` should be only invoked after inputs are complete mounting because the source of truth of your value lives inside those inputs. The only situation trigger is going to work correctly, is with a custom register which updates the value in the virtual object, but this is not going to be the case for `useFieldArray`

**Comment by dwiyatci** [comment]
@bluebill1049 Thank you for the investigation and the explanation - I can make sense most of it. Unfortunately `remove([...])` is not an option for me because, as I said, in my project it is more complex than that, i.e. the control for `B` is actually a sub-field of an `item` field: `` `items[${index}].b` ``. 😔 

I think it would be much cleaner if I could somehow listen to the unmount event of the input control, and then do `` clearErrors(`items[${index}].b`) ``. Do you have an alternate idea for this?

**Comment by bluebill1049** [comment]
> @bluebill1049 Thank you for the investigation and the explanation - I can make sense most of it. Unfortunately `remove([...])` is not an option for me because, as I said, in my project it is more complex than that, i.e. the control for `B` is actually a sub-field of an `item` field: `` `items[${index}].b` ``. 😔
> 
> I think it would be much cleaner if I could somehow listen to the "unmount" event of the input control, and then do `` clearErrors(`items[${index}].b`) ``. Do you have an alternate solution to achieve this?

i see. 

Option A: i think we need to call the `trigger` after the input gets unmounted, perhaps you need to convert into a controlled component and run that at useEffect with `trigger`.  
Option B: You convert your logic into `useWatch`, so it doesn't effect the rendering with the entire fireldArray
Option C (hack): `setTimeout(() => trigger(), 100)`

**Comment by dwiyatci** [comment]
Hehe, I tried Option B and C already yesterday. Only Option C works but I didn't like it 'cause as you said, it's a hack. Will do some experiments on Option A now then. Thank youu!

**Comment by bluebill1049** [comment]
> Hehe, I tried Option B and C already yesterday. Only Option C works but I didn't like it 'cause as you said, it's a hack. Will do some experiments on Option A now then. Thank youu!

do you have a option B example? maybe i can have a play with it too?

**Comment by dwiyatci** [comment]
No, I don't have the CSB for it. But aw yeah, turns out after stitching it more carefully with `useWatch`, **Option B** seems to do the job for me. 🤩 I left the Option A out 'cause it'd require quite some structural changes in the code. Thanks, again, so much for the valuable hint @bluebill1049 !

However, along with the experimentation, I found another (little detail) annoying thing when using `useWatch` instead of `watch`. But that's another issue. Gonna create a new one and gonna close this one now :)

**Comment by bluebill1049** [comment]
no worries at all @dwiyatci feel free to follow me up with questions here if you stuck again.
