### ISSUE TITLE
First character input with react-input-mask gets lost

### ISSUE THREAD

**Issue by AkselAllas** [react-hook-form/react-hook-form#3256]
**To Reproduce**
1) Go to codesandbox
2) Click on form
3) Input `AAA`
4) Form only has `AA`

**Codesandbox link (Required)**
https://codesandbox.io/s/cocky-star-3o03k?file=/src/App.tsx

**Expected behavior**
If I type `AAA`, then the form gets value `AAA`

**Comment by bluebill1049** [comment]
shouldn't need to register input again at the Controller, it's already been taking care of inside.

https://codesandbox.io/s/cocky-star-3o03k?file=/src/App.tsx

**Comment by AkselAllas** [comment]
RIP. Silly me. Thank you! Solved.

**Comment by bluebill1049** [comment]
np :)
