### ISSUE TITLE
React Native / Metro bundler shows warning and ignores package due to change in rules about package.json's exports section

### ISSUE THREAD

**Issue by cabiad** [react-hook-form/react-hook-form#3257]
**Describe the bug**
React native's metro bundler ignores `react-hook-form` and shows a warning.

Similar issues have been reported in many other projects as listed in [this react native cli issue](https://github.com/react-native-community/cli/issues/1168#issue-617427926) and [the fix used by those projects is quite simple and seemingly low risk](https://github.com/i18next/i18next-http-backend/commit/1d8da7909425eb33ab286cd73ee53bb48a1a3dc4#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R8).

**To Reproduce**

With node 15.0.1 and yarn 1.22.10 installed (as of this writing, the latest available in homebrew)...

1. Create a new react native app with `npx react-native init DummyProj`
2. `cd DummyProj/`
2. Install `react-hook-form` with `yarn add react-hook-form`
3. Start the metro bundler with `yarn start`
4. Observe the following error output:

```
$ yarn start
yarn run v1.22.10
$ react-native start
warn Package react-hook-form has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/cabiad/src/DummyProj/node_modules/react-hook-form/package.json
```

**Codesandbox link (Required)**
(Not applicable for this build issue.)

**Expected behavior**
The package is not ignored in react native

**Desktop (please complete the following information):**

- OS: MacOS
- Browser N/A
- Version 6.9.6

**Additional context**

**Comment by bluebill1049** [comment]
Thanks heap for report the issue and provide a solution 🙏
