### ISSUE TITLE
3.23.11 does not work with useFormContext hook

### ISSUE THREAD

**Issue by dohomi** [react-hook-form/react-hook-form#326]
**Describe the bug**
After update from 3.23.10 => 3.23.11 validation is not being triggered any longer

3.23.10
https://codesandbox.io/s/react-hook-form-get-form-values-g7bkl

3.23.11
https://codesandbox.io/s/react-hook-form-get-form-values-94pxe

I am not sure what changed internally or if my approach of using the plugin was not correct.

**Comment by bluebill1049** [comment]
thanks @dohomi i am taking a look this issue.

**Comment by bluebill1049** [comment]
patching it now. issue found.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/releases/tag/v3.23.12
patched, thanks for report the issue 🙏 (sorry breaking your app too)

**Comment by dohomi** [comment]
No worries 👍 
Is the approach something how you would solve hooking into material-ui? If yes feel free to steal the two components for your example page.

**Comment by bluebill1049** [comment]
I will :) 👍
