### ISSUE TITLE
"Miss ref" when attempting to register a Material UI Checkbox component.

### ISSUE THREAD

**Issue by andrewjrhill** [react-hook-form/react-hook-form#327]
**Describe the bug**
After following the instructions under the "Work with UI library" section of the docs, I was unable to get my Material UI form fully registered with react-hook-form **due to MUI checkboxes**. 

When attempting to register an MUI checkbox control with `inputRef={register}`; I get a warning in the console `Miss ref` on the checkbox input and the checkbox value does not appear in the `onSubmit()` data object.

**To Reproduce**
1. Go to https://codesandbox.io/s/solitary-wood-ir6hq
2. Open the console.
3. See warning.
4. Click the Submit button on the form.
5. See an empty `Object {}` in the console.

**Expected behavior**
There should be no warning when attempting to register a checkbox with Material UI checkbox components. The checkbox value should be available on submit.

**Screenshots**

![Screenshot 2019-09-23 at 11 03 14](https://user-images.githubusercontent.com/3358672/65413462-c98f9d80-ddf1-11e9-87e4-26a77aa64b3f.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Google Chrome
 - Version: 77.0.3865.90 (Official Build) (64-bit)

**Comment by bluebill1049** [comment]
hi @andrewjrhill,

name is required, please find more information in the doc: https://react-hook-form.com/api#register

<img width="971" alt="Screen Shot 2019-09-23 at 9 47 18 pm" src="https://user-images.githubusercontent.com/10513364/65423189-c88b5a00-de4b-11e9-8f98-3324f2b92d22.png">

**Comment by bluebill1049** [comment]
i will improve the error messsage in the next release

to `Miss ref name:`

**Comment by andrewjrhill** [comment]
@bluebill1049 - thanks for your help.
