### ISSUE TITLE
With field array and Controller, focus is lost on revalidation; validate applies incorrectly to new row

### ISSUE THREAD

**Issue by mjhecht** [react-hook-form/react-hook-form#3272]
Hi, I've been loving `react-hook-form` but ran into a couple issues I'm stuck on, pointing to either bugs or docs improvement needed, after searching and trying things all afternoon. Thanks for a great library!

(1): I’m using the `useFieldArray()` hook, and have Material UI for my form fields. Originally, I did not use `Controller` around my `TextField`, and was getting an error that I solved by following the solution on [https://github.com/react-hook-form/react-hook-form/discussions/1693](this page), with a "Missing name @ <node>" error. That solved the problem. So then, I needed to get the contents of the input field that’s in the array before form submission; I experimented with `watch()` and found that this causes the fields rendered from the array to lose focus with each character typed, another common issue people were having. Using `getValues()` instead and avoiding `watch`, avoids the problem.

(2): Now I’m noticing that even without `watch()`, the field loses focus when it is revalidating. I see guidance on [https://spectrum.chat/react-hook-form/help/field-loses-focus-after-first-input-on-validation~43e417e7-b0f4-41b5-acd9-1b3c6f687b52](this page) from @bluebill1049 implying that the `Controller` around `TextField` (added as a solution in the above) should be removed in order to solve the unfocusing problem (which I had just added to solve #1...) I also tried adding `key` props everywhere (per StackOverflow discussion) hoping to prevent rerendering of the form; I extracted it into a separate component as well. Perhaps investigating memoizing the component will prevent its rerendering (and thus its losing focus?) But there must be an easier solution.

(3): I see another problem, which happens in this case: 
1. User submits the form; field does not validate; form fields are in revalidate-while-typing condition.
2. User adds another row to the field array, in the above condition.
3. The new row is in the instant-revalidate state, even though it technically has not be submitted yet.

This bug seems less important, but still isn’t the perfect user experience; we would expect new fields to appear as unsubmitted, and not subject to the system’s “monitoring” condition when the user is thinking their content needs to be fixed. Here’s a video showing my use case, with the annoying losing-focus condition as well:

![Oct-26-2020 16-08-44](https://user-images.githubusercontent.com/436116/97239873-f0b15f00-17a9-11eb-9171-5d6cc9581f33.gif)

**Codesandbox link (Required)**
Recreated the issue in this Codesandbox:
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-cb2le?file=/src/index.js:0-2526

**Expected behavior**
- Focus isn't lost when typing in the url field, at any point, even when revalidation is happening.
- After pressing submit, the fields active at the time remain in their instant-validate condition. New fields do not have this condition, and can be worked with, without triggering the error message (e.g. the `helperText` prop).

**Desktop (please complete the following information):**
- OS: MacOS Catalina
- Browser: Chorme
- Version: Version 86.0.4240.111 (Official Build) (x86_64)

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report. What are the steps to reproduce the issue for your CSB?

**Comment by bluebill1049** [comment]
> (1): I’m using the `useFieldArray()` hook, and have Material UI for my form fields. Originally, I did not use `Controller` around my `TextField`, and was getting an error that I solved by following the solution on [https://github.com/[/discussions/1693](https://github.com/react-hook-form/react-hook-form/discussions/1693)](this page), with a "Missing name @ " error. That solved the problem. So then, I needed to get the contents of the input field that’s in the array before form submission; I experimented with `watch()` and found that this causes the fields rendered from the array to lose focus with each character typed, another common issue people were having. Using `getValues()` instead and avoiding `watch`, avoids the problem.

This should resolve the issue: https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-cdifi?file=/src/index.js

- for as you can just place the component, you don't need render props

**Comment by bluebill1049** [comment]
In case you wondering about the `render` props usage: 

<img width="928" alt="Screen Shot 2020-10-27 at 11 05 46 am" src="https://user-images.githubusercontent.com/10513364/97241163-5eaa6480-1844-11eb-928c-d320cbc97532.png">

**Comment by mjhecht** [comment]
Thanks @bluebill1049 for the super quick reply! I'll give this a try.

**Comment by mjhecht** [comment]
That works! The render props were the issue.

There is still the #3 (live validation continues after initial validation even for new fields added) issue, but that's probably beyond the scope of what r-h-f manages and isn't a big deal. I really appreciate the quick help, and noticing your really active support in general is what encouraged me to post this issue. Thanks again!
