### ISSUE TITLE
`Controller`: validate `onBlur` + `shouldFocusError` seemingly not working properly

### ISSUE THREAD

**Issue by KATT** [react-hook-form/react-hook-form#3277]
**Describe the bug**

When using a `Controller` wraps a MUI `TextField` it does not seem to neither trigger validation onBlur nor focus the field.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-material-ui-helpers-h7swy
2. Fill in "a" in _First name_ (has `minLength` `4`)
3. Tab to next field (trigger blur )
4. Click _Submit_

**Codesandbox link (Required)**

 https://codesandbox.io/s/react-hook-form-material-ui-helpers-h7swy

**Expected behavior**

- at **3.** - it first name should have been validated and turned  into an error
- at **4.** - it should focus "First name" as it's the first - and only - field with an error

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Chrome
- Version: 86.0.4240.111 

**Additional context**

Have a look at `RHFTextField`, in a simplified way it basically does what's described in [the documentation](https://react-hook-form.com/api#Controller).

**Comment by bluebill1049** [comment]
Thanks for the issue report.

- `reValidateMode`
<img width="927" alt="Screen Shot 2020-10-27 at 6 26 54 pm" src="https://user-images.githubusercontent.com/10513364/97269678-02fecc00-1882-11eb-9d35-44bac2fdae39.png">
perhaps you are after `mode: 'onTouched'`

- `shouldFocusError`:
https://react-hook-form.com/api#Controller
<img width="933" alt="Screen Shot 2020-10-27 at 6 27 57 pm" src="https://user-images.githubusercontent.com/10513364/97269767-2590e500-1882-11eb-9fc5-b06769b70fe4.png">
working CSB in the doc:  https://codesandbox.io/s/react-hook-form-controllerautofocus-v6-disabled-k1of4

**Comment by KATT** [comment]
Hmmm, that made my Controller a lot more complicated, but you're right of course - no bug in RHF, just a bit tricky with third party form components.

I not a fan of imperatively mutating the `disabled` state, so I did this other hack that I also hate instead: 

```ts
          setTimeout(() => {
            inputRef.current?.focus();
          }, 0);
```

**Comment by KATT** [comment]
Amazingly quick response btw. Cheers 🙇 🙏

**Comment by bluebill1049** [comment]
> Hmmm, that made my Controller a lot more complicated, but you're right of course - no bug in RHF, just a bit tricky with third party form components.
> 
> I not a fan of imperatively mutating the `disabled` state, so I did this other hack that I also hate instead:
> 
> ```ts
>           setTimeout(() => {
>             inputRef.current?.focus();
>           }, 0);
> ```

I would build that disabled prop by extending Controller's functionality: https://react-hook-form.com/advanced-usage/#ExtendController

**Comment by bluebill1049** [comment]
probably in the future, we will include `ref` inside `render` prop

`render={({ onChange, value, ref }) => <MuiText inputRef={ref} />}`

**Comment by KATT** [comment]
Well, I got it working with nice UX so I'm happy until it breaks and then I'll fix it

**Comment by KATT** [comment]
Thanks again!

**Comment by bluebill1049** [comment]
This is better CSB: https://codesandbox.io/s/react-hook-form-controllerautofocus-v6-eeo66 I don't why there is crappy CSB in the doc, getting it updated.  will keep you updated with the render prop, i will have a play with the idea i had above, i agree onFocus prop is annoying and not great DX.

**Comment by KATT** [comment]
I got it working nicely in my CSB with typescript and all - https://codesandbox.io/s/react-hook-form-material-ui-helpers-h7swy

Thought - it's a bit odd  that it has `isSubmitting:true` whilst the form is validating but I guess that's needed if you want async validators

**Comment by bluebill1049** [comment]
`isSubmitting` is true during submit, because it's async right?

**Comment by KATT** [comment]
In my head validation is done synchronously before it actually submits so then isSubmitting should never switch state - it doesn't when you have in-browser validators (like `required`) so I'd expect it to work the same

**Comment by bluebill1049** [comment]
> In my head validation is done synchronously before it actually submits so then isSubmitting should never switch state - it doesn't when you have in-browser validators (like `required`) so I'd expect it to work the same

we don't have such a state for `isValidating` right now.

**Comment by KATT** [comment]
It actually creates a tiny UI glitch in my CSB above where the submit-button's ripple effect disappears

Compare:

- Empty first name input (browser input validation failed) + click submit -> ripple effect works
- Input "a" (RHF input validation failed) + click submit -> ripple effect only goes

**Comment by KATT** [comment]
In the case of synchronous validation methods I wouldn't expect it to ever reach `isSubmitting`

If one would have have async validation methods I don't know what would be good - maybe to introduce isValidation

**Comment by bluebill1049** [comment]
> In the case of synchronous validation methods I wouldn't expect it to ever reach `isSubmitting`
> 
> If one would have have async validation methods I don't know what would be good - maybe to introduce isValidation

you can up vote this feature request: https://github.com/react-hook-form/react-hook-form/issues/2842
