### ISSUE TITLE
Property 'current' is missing in type '(ref: ElementLike | null)

### ISSUE THREAD

**Issue by wouterds** [react-hook-form/react-hook-form#328]
Hi, first of all, this lib looks awesome!

Now, what I'm trying to do is use custom styled components (Form, Input, ..) with TypeScript and this lib but I keep running in issues regarding typings of ref. I've tried a couple of things now and this seems most correct, however, TS still complains about the return value of `register` vs the types of the `ref` prop.

I have this basic form with an `email` & `password` input.

```ts
const SignIn = () => {
  const { register, handleSubmit } = useForm();

  const onSubmit = handleSubmit((data: any) => {
    console.log({ data });
  });

  return (
    <Layout>
      <h1>Sign in</h1>
      <Form onSubmit={onSubmit}>
        <Form.Field>
          <Form.Label htmlFor="email">Email</Form.Label>
          <Form.Input
            id="email"
            type="email"
            name="email"
            forwardRef={register({ required: true })}
          />
        </Form.Field>
        <Form.Field>
          <Form.Label htmlFor="password">Password</Form.Label>
          <Form.Input
            id="password"
            type="password"
            name="password"
            forwardRef={register({ required: true })}
          />
        </Form.Field>
        <Form.Field>
          <Form.Button type="submit">Sign in</Form.Button>
        </Form.Field>
      </Form>
    </Layout>
  );
};
```

This is my custom styled `Input` component
```ts
const Container = styled.input`
  background: #F00;
`;

interface Props
  extends DetailedHTMLProps<
    InputHTMLAttributes<HTMLInputElement>,
    HTMLInputElement
  > {
  forwardRef?: RefObject<HTMLInputElement>;
}

const Input = (props: Props) => {
  return <Container {...props} ref={props.forwardRef} />;
};
```

But I keep getting **`Property 'current' is missing in type '(ref: ElementLike | null) => void' but required in type 'RefObject<HTMLInputElement>'.`**

### Example repository

https://github.com/wouterds/ts-react-hook-form

**Comment by bluebill1049** [comment]
what about 

`const { register, handleSubmit } = useForm<{
  email: string,
  password: string,
}>();`

**Comment by wouterds** [comment]
> what about
> 
> `const { register, handleSubmit } = useForm<{ email: string, password: string, }>();`

I'm sorry, I don't see how that helps? The TS error remains / is still present.

![Screenshot 2019-09-23 at 17 05 37](https://user-images.githubusercontent.com/1210628/65437617-6b2fe280-de24-11e9-9578-69e3486e4812.jpg)

**Comment by wouterds** [comment]
> `const { register, handleSubmit } = useForm<{ email: string, password: string, }>();`

I'm sorry I don't understand, but it solve the issue.

I added a repo to demo & reproduce the issue: https://github.com/wouterds/ts-react-hook-form.

**Comment by wouterds** [comment]
I created a repo to demo & reproduce the issue: https://github.com/wouterds/ts-react-hook-form.

**Comment by stramel** [comment]
@wouterds Is there a reason, you are using a prop called `forwardRef` instead of using the `React.forwardRef` function? 

```tsx
const Input = React.forwardRef<HTMLInputElement, Props>((props, ref) => {
  return <Container {...props} ref={ref} />;
});

// Usage
<Form.Input
  id="email"
  type="email"
  name="email"
  ref={register({ required: true })}
/>
```

**Comment by wouterds** [comment]
> @wouterds Is there a reason, you are using a prop called `forwardRef` instead of using the `React.forwardRef` function?

Inexperience with using refs! Thanks man, that helped me!

I ended up with the following which works & removes all my TS warnings / errors in my personal project. Same as what you gave me but written differently since that got rid of **`Component definition is missing display name eslint(react/display-name).`**

```ts
import React, {
  forwardRef,
  DetailedHTMLProps,
  InputHTMLAttributes,
  Ref,
} from 'react';
import { Container } from './styles';

type Props = DetailedHTMLProps<
  InputHTMLAttributes<HTMLInputElement>,
  HTMLInputElement
>;

const Input = (props: Props, ref: Ref<HTMLInputElement>) => {
  return <Container {...props} ref={ref} />;
};

export default forwardRef<HTMLInputElement, Props>(Input);
```

**Comment by stramel** [comment]
Personally, I would go with 

```tsx
import React, {
  forwardRef,
  DetailedHTMLProps,
  InputHTMLAttributes,
  Ref,
} from 'react';
import { Container } from './styles';

type Props = DetailedHTMLProps<
  InputHTMLAttributes<HTMLInputElement>,
  HTMLInputElement
>;

export default forwardRef<HTMLInputElement, Props>(function Input(props, ref) {
  return <Container {...props} ref={ref} />;
});
```

Which should fix your displayName linting error
