### ISSUE TITLE
Version 6.9.3–6.9.6 broke many TypeScript type definitions

### ISSUE THREAD

**Issue by mrlubos** [react-hook-form/react-hook-form#3289]
**Describe the bug**
Updating from 6.9.2 to the latest version (6.9.6) completely breaks my TypeScript app. There are too many different type errors to list, but what I've seen so far was:

1. `defaultValues` complaining `Type 'null' is not assignable to type '{} | undefined'.`
2. `errors` type error
3. `watch` type error

**To Reproduce**

1. Have a working TypeScript app on version 6.9.2
2. Upgrade to version 6.9.6
3. Try to compile the app

**Codesandbox link (Required)**

[CodeSandbox link](https://codesandbox.io/s/tender-lake-qxnu4?file=/src/App.tsx)

**Expected behavior**

The app compiles without any errors.

**Screenshots**

<img width="821" alt="Screenshot 2020-10-28 at 1 42 04 pm" src="https://user-images.githubusercontent.com/12529395/97438233-7de9e480-195f-11eb-911b-de04b4fa3d50.png">
<img width="603" alt="Screenshot 2020-10-28 at 1 41 49 pm" src="https://user-images.githubusercontent.com/12529395/97438244-80e4d500-195f-11eb-8dac-3db2eb094a27.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bluebill1049** [comment]
we will need the generic at the useForm, previous it's working because it didn't correctly report the type error:

https://codesandbox.io/s/pedantic-perlman-f93x8?file=/src/App.tsx

**Comment by bluebill1049** [comment]
hey @mrlubos shall we have a quick discussion here: https://github.com/react-hook-form/react-hook-form/issues/3313 I think we may need to enforce generic at `useForm`.
