### ISSUE TITLE
UseFieldArray gives error when calling reset without providing the array

### ISSUE THREAD

**Issue by tantommy** [react-hook-form/react-hook-form#3294]
**Describe the bug**
When using `useFieldArray` and calling reset, we are seeing the error: `Cannot read property 'map' of undefined`.

**To Reproduce**
Go to the CSB and the error appears immediately.  When we change the version to `6.9.3` and the error goes away:
https://codesandbox.io/s/young-microservice-uxsuk?file=/src/App.tsx

**Expected behavior**
There should be no error just like in version `6.9.3`

**Desktop (please complete the following information):**

- OS: MacOS Catalina 10.15.7
- Browser: chrome
- Version: 86.0.4240.111

**Comment by 99uno** [comment]
Provided codesanbox is still not working. I also tried 6.9.6-beta.1. Where is the fix implemented?

**Comment by GomberSahil** [comment]
Same error coming when null is providing as a value. Please handle the case for null value also
