### ISSUE TITLE
Calling reset does not reset controlled inputs within a useFieldArray, when rows have the same ID

### ISSUE THREAD

**Issue by milo-** [react-hook-form/react-hook-form#3296]
**Describe the bug**
When calling reset, all inputs, both controlled and uncontrolled should be reset. However if I provide an id, rather than react-hook-form generating one, and it matches a controlled input that has already been rendered, calling reset will not reset the controlled input.

**To Reproduce**

See example

1. Create a form with a field array
2. Set some default values, which contain an  id: `{ test: [ {"id": "123", "firstName: "Bill", lastName: "Luo"} ] }` 
3. Assign properties to controlled inputs within the field array
4. Call `reset({  test: [{"id": "123", "firstName": "Milo", "lastName": "Hill" }]})`
5. Note that the controlled inputs are not reset to the new values

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-gs2xw?file=/src/index.js

**Expected behavior**
The controlled input should be reset, just like the uncontrolled inputs

**Desktop (please complete the following information):**

Safari 14
Chrome 86

**Smartphone (please complete the following information):**

Not tested

**Additional context**

**Comment by bluebill1049** [comment]
`id` is preserved for `useFieldArray` unless if you change the `keyName`

**Comment by milo-** [comment]
Thanks for the speedy response @bluebill1049!! I'll go fix up my code.

I think there could also be an opportunity to improve the docs, as it's not clear that you can't provide the id yourself. 

It would also be awesome if react-hook-form logged a warning when you're using a reserved property, as currently everything seems to work... until it doesn't.

**Comment by bluebill1049** [comment]
> Thanks for the speedy response @bluebill1049!! I'll go fix up my code.
> 
> I think there could also be an opportunity to improve the docs, as it's not clear that you can't provide the id yourself.
> 
> It would also be awesome if react-hook-form logged a warning when you're using a reserved property, as currently everything seems to work... until it doesn't.

That's a good idea. Will investigate for a solution.

**Comment by bluebill1049** [comment]
also feel free to submit a PR to improve the doc: https://react-hook-form.com/api#useFieldArray

& in case you missed the following section:
<img width="1024" alt="Screen Shot 2020-10-29 at 7 25 30 pm" src="https://user-images.githubusercontent.com/10513364/97543559-83593480-1a1c-11eb-906f-52923efbbad1.png">

**Comment by milo-** [comment]
Thanks @bluebill1049 - Will take a look at the docs later today. I've also had a go at adding the warning logs.

**Comment by bluebill1049** [comment]
Thank you very much @milo- for the PR! ❤️ love it.
