### ISSUE TITLE
[Validation] required validate message is not appear with yup schema

### ISSUE THREAD

**Issue by iamchanii** [react-hook-form/react-hook-form#330]
**Describe the bug**
Required message is not appear with yup schema validation. only display 'Invalid email'. I made yup schema what checks 2 validation, required and valid(w/ regex test)

**To Reproduce**
Codesandbox: https://codesandbox.io/s/react-hook-form-required-not-appear-reproduce-losds
1. submit form without fill the email field
2. expect to display required message but invalid email is appeared.
3. but native validate is works as what I expected

**Expected behavior**
Display required error message

**Screenshots**
![image](https://user-images.githubusercontent.com/26643843/65486318-169d6d80-dedf-11e9-8f82-697a351473af.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Chrome
 - Version: 76.0.3809.132
 - Library: 3.23.12

**Additional context**
I think there is an issue in `logic/validateWithSchema.ts`. I've been through the same issue when I build a form without any form library just with yup. I have to find my old project to reference it. I need your opinion before that. do you think this is a bug? then, I'll do.

**Comment by iamchanii** [comment]
Take a minute, I test below schema in codesandbox:
```
const validationSchema = yup.object({
  email: yup
    .string()
    .required("Email required?") // <-- never
    .email("Invalid email 2")
});
```

then, required message is appear. umm...
![image](https://user-images.githubusercontent.com/26643843/65487280-84e32f80-dee1-11e9-8b1b-316fc5232ad3.png)

**Comment by iamchanii** [comment]
I think it's related with yup schema. I'm just close this issue. sorry, never mind.

**Comment by bluebill1049** [comment]
no worries at all :)

**Comment by iamchanii** [comment]
This is my conclusion: if email is empty, yup validate result contains `.required()` and `.test()` the issue I have drawn up is entirely related to it. check out below:

![image](https://user-images.githubusercontent.com/26643843/65489820-e8bc2700-dee6-11e9-8a5f-ecb011ef3400.png)

this is result of `console.log()` in `parseErrorSchema()` of `validateWithSchema.ts`. in reduce, does not check if `previous` already has key. so I can't get required message if I use `.test()` validation.

in this case, I think `parseErrorSchema()` have to check key. but I can't decide. is this a "real" issue of react-hook-form? I don't think so, even if I told.

**Comment by bluebill1049** [comment]
I don't think this is an issue with this lib :(

**Comment by bluebill1049** [comment]
can you post this in Yup?

**Comment by iamchanii** [comment]
yep, I will.

**Comment by iamchanii** [comment]
So, that result is absolutely intended. because, yup runs all validate in parallels like `Promise.all()`. of course, there is a feature request related it, but it is not included in their priority list.

Ref:
https://github.com/jquense/yup/issues/499#issuecomment-473111368
https://github.com/jquense/yup/issues/602#issuecomment-526154782

according to yup#499's comment, I have to set `abortEarly` to `false` and display error what I want from returned ValidationErrors.

**Comment by iamchanii** [comment]
currently, yup runs all validate in parallels and this lib overwrites errors in `parseErrorSchema()` function. I can create PR of that, but I think it will be a side effect at a high probability. If anyone who is had same issue, you can reopen this and comment.

**Comment by bluebill1049** [comment]
Sounds good to me :) let’s keep an eye on it if others having similar issue

**Comment by bluebill1049** [comment]
@iamchanii really appreciate your blog post on react-hook-form 🙏 감사

**Comment by hitbear518** [comment]
so for now what is the proper way to set error message when using yup?

**Comment by bluebill1049** [comment]
@hitbear518 you should be fine just by using yup

**Comment by hitbear518** [comment]
sorry for my ambiguity, I mean the official example is
```
const schema = yup.object().shape({
  firstName: yup.string().required(),
  age: yup
    .number()
    .required()
    .positive()
    .integer(),
});
```
but if I want to set error message like
```
const schema = yup.object().shape({
  firstName: yup.string().required(),
  age: yup
    .number()
    .required('age is required')
    .positive()
    .integer(),
});
```
it doesn't work for now right?

**Comment by bluebill1049** [comment]
can you produce a codesandbox with above? we are returning errors which produced by `yup`?

**Comment by hitbear518** [comment]
https://codesandbox.io/s/github/hitbear518/react-hook-form-required-not-appear-reproduce

so I think my problem is similar to iamchanii, the error message in .positive('age must > 0') do work,
but .required('age is required') never appear.
instead the error will be `
age must be a "number` type, but the final value was: `NaN` (cast from the value `""`)"

iamchanii is suggesting set abortEarly to false but I don't know how.

**Comment by bluebill1049** [comment]
hey @hitbear518 `validationSchemaOption: { abortEarly: false }`, is set to `false` by default. hmmm also that's what's returned by yup in the error object. you want to post this question to `Yup`?

`await validationSchema.validate(data, validationSchemaOption)`

above is how react hook form validates.

**Comment by bluebill1049** [comment]
hey @hitbear518 looking close to the code, i maybe above to improve on errors return. i will keep you updated.

**Comment by bluebill1049** [comment]
I think i will fix it by always return the first errors in the return list.

**Comment by bluebill1049** [comment]
ok look at this codesandbox @hitbear518 
https://codesandbox.io/s/react-hook-form-required-not-appear-reproduce-9xzxn
this is from yup, there is nothing i can do about it...

**Comment by hitbear518** [comment]
sorry for late reply, I think you are right, the wrong message is because yup will receive empty string instead of undefined from input.
I think I have to find a way around or try to understand yup more.

**Comment by bluebill1049** [comment]
no worries @hitbear518

**Comment by balzafin** [comment]
Don't know if this is already discussed somewhere else, but if you found this issue while searching for this problem like I did, one possible solution is to use [Yup.transform](https://github.com/jquense/yup#mixedtransformcurrentvalue-any-originalvalue-any--any-schema) 
(with numbers) like this:

```
const validationSchema = yup.object({
  age: yup
    .number()
    .transform(
      (currentValue: string, originalValue: string): string | undefined =>
        originalValue.trim() === "" ? undefined : currentValue
    )
    .required("required")
});
```

Here's a working codesandbox forked from the @hitbear518 one https://codesandbox.io/s/react-hook-form-required-not-appear-reproduce-gitzy

In the OP's case (RegexP.test for email), you could just skip the test if the value is `falsy`:
```
.test("email", "Invalid email", value =>
  !value || /[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/.test(
    value
  )
)
```
Codesandbox: https://codesandbox.io/s/react-hook-form-required-not-appear-reproduce-ycc4u

**Comment by bluebill1049** [comment]
thanks for sharing solution @balzafin 🙏

**Comment by bluebill1049** [comment]
FYI @balzafin on V4 we have fixed an issue with error reporting order. first rule in yup schema validation will report first.

**Comment by balzafin** [comment]
@bluebill1049 I noticed, thanks for the awesome work!

The order won't help with required numbers though as the type (`Yup.number()`) must be defined first? That's not a problem of this library though and the `transform` workaround is just fine imo.

**Comment by bluebill1049** [comment]
oh cool! thanks again @balzafin for your answer then, this will help others for sure
