### ISSUE TITLE
isValid stays false when using setValue

### ISSUE THREAD

**Issue by orszaczky** [react-hook-form/react-hook-form#3300]
**Describe the bug**
isValid never updates to true when a required value is set using setValue()

**To Reproduce**

In the codesandbox 
1. type a value into field 1
2. click the button, to set a value for field 2

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

https://codesandbox.io/s/objective-meadow-hykml?file=/src/App.js

**Expected behavior**
isValid should be set to true

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win10 64bit
- Browser: Chrome 86.0.4240.111 (Official Build) (64-bit)
- Version: React 17.0.0, react-hook-form 6.9.6

**Additional context**

**Comment by bluebill1049** [comment]
<img width="901" alt="Screen Shot 2020-10-30 at 8 28 10 am" src="https://user-images.githubusercontent.com/10513364/97634457-da492300-1a89-11eb-9e0f-87262c28787d.png">
