### ISSUE TITLE
Array field validation

### ISSUE THREAD

**Issue by 99uno** [react-hook-form/react-hook-form#3301]
**Is your feature request related to a problem? Please describe.**
I have an array field and want to validate for example, min and max length (eg min 1 if required), unique values, etc. I tried to register a dummy field using form.register but it's only working for empty forms but when I fill data from server with form.reset I'm not sure why this field is not registered. I know there is a similar example but validator is set in useForm and I want my custom component to autovalidate.

**Describe the solution you'd like**
Add validate option to useFieldArray.

**Describe alternatives you've considered**
Check values on handleSubmit or register a dummy field but it's only working for empty forms.

**Additional context**
Version 6.9.6

**Comment by bluebill1049** [comment]
i think it's worth considering using `resolver`.
