### ISSUE TITLE
Upgrading react-dom to 17.0.1 breaks `useForm` errors

### ISSUE THREAD

**Issue by changalberto** [react-hook-form/react-hook-form#3302]
No specific react related errors thrown in this case. But upgrading to latest react 17.0.1 - specifically react-dom package to 17.0.1 makes `useForm` `errors` return empty props when it should return a list of form fields that hasn't passed validation.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848
