### ISSUE TITLE
Array field must be an empty array when removing all fields

### ISSUE THREAD

**Issue by 99uno** [react-hook-form/react-hook-form#3303]
**Describe the bug**
I have an array field and when I remove all fields, the form value is undefined instead of an empty array. If the server doesn't receive a value because it's undefined, it won't replace current db value by an empty array.

**To Reproduce**

1. Open sandbox
2. Click Submit to verify that form value is not empty
3. Click on Delete to remove all rows
4. Click Submit to verify that form value is empty

**Codesandbox link (Required)**
[useFieldArray](https://codesandbox.io/s/react-hook-form-usefieldarray-template-q0jek)

**Expected behavior**
When there is an array field it should be always an array despite if contains fields or not. For example, in MongoDB when there is an undefined field, you won't see it in the model but when the field is an array, it is always an empty array. Same behavior is expected.

**Additional context**
Version 6.9.6

**Comment by bluebill1049** [comment]
This is expected result by default `shouldUnregister: true` all inputs get removed and hence return undefined, but you can work around this issue with: `shouldUnregister: false.

**Comment by 99uno** [comment]
I tried shouldUnregister: false, but value is an empty object instead of an empty array after deleting all rows.

[Example](https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-oy2iu)

**Comment by bluebill1049** [comment]
<img width="354" alt="Screen Shot 2020-10-30 at 12 32 02 pm" src="https://user-images.githubusercontent.com/10513364/97649637-eb0a9080-1aab-11eb-881a-7ceead921e5c.png">

**Comment by 99uno** [comment]
Ok, shouldUnregister works but, I'm still thinking that arrayfield should return an empty array after removing all rows because the array field isn't being unmounted, just its rows, so the component should have a value.

**Comment by bluebill1049** [comment]
Its tricky @99uno hook form is uncontrolled form, so there is based "state".

**Comment by denwakeup** [comment]
> Ok, shouldUnregister works but, I'm still thinking that arrayfield should return an empty array after removing all rows because the array field isn't being unmounted, just its rows, so the component should have a value.

@99uno As a workaround, if you are using Yup, try specifying `ensure()` on the field in the validation schema.

[Codesandbox Example](https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-m5930)

**Comment by bluebill1049** [comment]
V7 will start to return `[]` when all fields are removed.
