### ISSUE TITLE
Validation errors not consistent

### ISSUE THREAD

**Issue by tonyneel923** [react-hook-form/react-hook-form#3304]
**Describe the bug**
When using two different ui components (checkboxes, and input) if I submit and have errors on both, entering valid input will clear the error for the text input but not the cbeckboxes

**To Reproduce**

1. Go to sandbox link
2. Click on Remove Flags(s) text  button
3. Errors pop up as expected
4. Enter text in input (error clears)
5. Check a checkbox (error does not clear)
6. Click submit again and all errors clear

**Codesandbox link (Required)**
[sandbox link](https://codesandbox.io/s/young-star-3wjv2?file=/src/App.tsx)

**Expected behavior**
Error clears on checkboxes when one is clicked

**Desktop (please complete the following information):**

- OS: macOS catalina
- Browser safari
- Version 13.1.3

**Comment by bluebill1049** [comment]
ok this issue due to the moment you click on one of the checkbox the name is `flags.1', so it won't clear the `flags` errors. you can do `trigger('flags')` 

https://codesandbox.io/s/frosty-dan-7yt9y?file=/src/App.tsx

**Comment by bluebill1049** [comment]
DX should be improved in the next update, you don't need run `trigger` at `onChange`.

**Comment by tonyneel923** [comment]
Works beautifully thank you!

**Comment by bluebill1049** [comment]
Pleasure, thanks for reporting the issue.
