### ISSUE TITLE
6.10.0 broke partial interface to be passed as defaultValues

### ISSUE THREAD

**Issue by ejose19** [react-hook-form/react-hook-form#3313]
**Describe the bug**
This was previously reported at #3088, and it was fixed. But now after last release it broke again.

**To Reproduce**

Pass partial<T> as defaultValues on 6.10.0, notice the error. Passing a type doesn't cause it.

**Codesandbox link (Required)**
https://codesandbox.io/s/hungry-shaw-709ki?file=/src/App.tsx
- Use previous version and notice how there's no error.

**Expected behavior**
It should work with both types and interfaces

**Additional context**
Most likely the issue was caused by #3293, previously it was fixed on https://github.com/react-hook-form/react-hook-form/commit/3ca4a7516e553aa1ed43e479af85103cb80b7003

**Comment by bluebill1049** [comment]
This issue bounces back and forwards now: https://github.com/react-hook-form/react-hook-form/pull/3293 look at the two issues in the PR.

**Comment by bluebill1049** [comment]
I think we either enforce `defaultValue` or not, otherwise the `infer` is getting confused and leads to type error.

**Comment by bluebill1049** [comment]
or enforce the generic at `useForm` to avoid this confusing.

**Comment by ejose19** [comment]
I read those issues, and IMO being explicit on the generic at useForm<T> instead of infering from default values is more precise.

**Comment by bluebill1049** [comment]
> I read those issues, and IMO being explicit on the generic at useForm instead of infering from default values is more precise.

I think I am lean towards that as well, otherwise, it's a never-ending issue we are in a loop now...

**Comment by bluebill1049** [comment]
I have cc the relevant people who reported the issue, I think we can have a conclusion here that generic at the useForm is potentially necessary and will be documented down, so we don't have regression like this again.

**Comment by bluebill1049** [comment]
@ejose19 can you please update your CSB? it's probably not saved.

**Comment by ejose19** [comment]
@bluebill1049 done. Sure, let's hear others opinions. But being explicit at the start (useForm generic) should make users detect errors earlier in case defaultValues didn't contain all form properties.

**Comment by bluebill1049** [comment]
I agree with @ejose19, unless someone else has a better idea, otherwise, we will lock it in, fix it and update the doc.

**Comment by mrlubos** [comment]
I, too, have no problem with the generic. However, I have some questions:

1. Why is this suddenly an issue? What changed? I'm not aware of this being a problem prior to `6.9.3`.
2. Can you post an example of what `useForm()` would look like with a generic?

**Comment by ejose19** [comment]
@mrlubos For the example of generic:

```ts
interface User {
  name: string;
  age: number;
}

useForm<User>();

```

**Comment by bluebill1049** [comment]
> I, too, have no problem with the generic. However, I have some questions:
> 
> 1. Why is this suddenly an issue? What changed? I'm not aware of this being a problem prior to `6.9.3`.

it was due to the type change, which is what i have switch back and forward with, I think I finally figure this out now... bit late.

> 2. Can you post an example of what `useForm()` would look like with a generic?

`useForm<{ ... }>`

**Comment by mrlubos** [comment]
With yup, I am already doing this for each form

```tsx
const schema: ObjectSchema<Values> = object({
  name: string().required()
}).defined()

useForm({
  defaultValues: {
    name: ''
  },
  resolver: yupResolver(schema)
})
```

Would I have to now use `Values` also in `useForm<Values>({ ... })`? Is there any way to simplify my syntax? Feels a bit redundant to duplicate the same type annotation

**Comment by bluebill1049** [comment]
> With yup, I am already doing this for each form
> 
> ```tsx
> const schema: ObjectSchema<Values> = object({
>   name: string().required()
> }).defined()
> 
> useForm({
>   defaultValues: {
>     name: ''
>   },
>   resolver: yupResolver(schema)
> })
> ```
> 
> Would I have to now use `Values` also in `useForm<Values>({ ... })`? Is there any way to simplify my syntax? Feels a bit redundant to duplicate the same type annotation

could you share a CSB?

**Comment by bluebill1049** [comment]
@ejose19 looks like this fix the issue: https://codesandbox.io/s/priceless-resonance-k7hml?file=/src/App.tsx

**Comment by bluebill1049** [comment]
fix the other two issues as well: 
https://codesandbox.io/s/busy-framework-kkck1?file=/src/App.tsx
https://codesandbox.io/s/priceless-resonance-k7hml?file=/src/App.tsx

**Comment by bluebill1049** [comment]
released a beta, please help to test: `6.10.1-beta.1`

**Comment by ejose19** [comment]
@bluebill1049 tested on some medium size projects and no errors were reported.

**Comment by mrlubos** [comment]
Thank you @bluebill1049!

**Comment by bluebill1049** [comment]
thanks for helping out as well @mrlubos 🙏
