### ISSUE TITLE
Question: how to access refs inside component function?

### ISSUE THREAD

**Issue by bravo-kernel** [react-hook-form/react-hook-form#332]
Hi mr. @bluebill1049, love your form and everything works fine, amazing job 💯. 

However, there is one thing I cannot solve. Probably caused by me being new to React and missing something simple so I hope you don't mind me asking for help here. Basically... I am wondering how to access the form refs so I can do things like resetting classes etc.

My first sandbox can be found here, hope it explains itself. https://codesandbox.io/embed/twilight-hill-63qui

Thanks in advance

**Comment by bluebill1049** [comment]
hey @bravo-kernel thanks for your kind words :) https://reactjs.org/docs/forwarding-refs.html i think this will help you.

**Comment by bluebill1049** [comment]
by the way, if you just want to display a classname when the form is reset or in a initial state, you can use `formState` `isDirty` state https://react-hook-form.com/api#formState

**Comment by bluebill1049** [comment]
actually you can just use `isValid` state in `formState`

**Comment by bravo-kernel** [comment]
Thank you for the quick reply. I must be really tired because I just can't see the solution. Testing and reading through all the issues, ref-documentation and examples must have worn me out ;)

I also think my original question was not formulated incorrectly... I would like to remove those classes on form reset.

Anyway, I am certain that I am just missing some simple solution here because this cannot be this hard. I will try again when I find some inspiration.  FWIW

- I have updated the sandbox with two inputs and better descriptions
- I have looked at passing `formState`, `errors`, to the `etc so I definitely learned more about the API
- using `isValid` and `isInvalid` sure looks like a good improvement but I guess it would need some additional logic to make sure the form starts without any of them applied

**Comment by bluebill1049** [comment]
hahaha the solution is so simple... reset() I think you are tired, take a break and then try to go through the doc: https://react-hook-form.com/api#reset cause I have spend quite lot effort to documented down everything. It will make you react hook form master :)

**Comment by bluebill1049** [comment]
also, you can join this community: https://spectrum.chat/react-hook-form?tab=posts if I am not online, someone else in the community will help you out too :)

**Comment by bravo-kernel** [comment]
Thanks, I will go online to not bother you too much here (once I wake up again some day, haha). It's funny though.. I'm already using `reset()` on L10 and it works great for the values, I just wonder why it does not get picked up by the conditional class L22. 🙄

**Comment by bluebill1049** [comment]
`reset` from the custom hook :)

**Comment by bravo-kernel** [comment]
@bluebill1049 ok, I feel no shame, it was indeed as simple as that. This does the job.

```
reset()
```

Don't know why I was using `event.target.reset()` but probably an incorrect copy. Solution spoon fed by friendly Spectrum user btw. Hopefully this might help someone in the future. ❤️

**Comment by bluebill1049** [comment]
awesome!
