### ISSUE TITLE
watch inherits wrong type when input has period in name (nested)

### ISSUE THREAD

**Issue by DedaDev** [react-hook-form/react-hook-form#3320]
**Describe the bug**

Watch function inherits the wrong type if there is a default value provided and input has a period in the name.

**To Reproduce**

simple input

```
<input name="hello.world" ref={register} />

watch('hello.world', 'World Hello!') // undefined
```

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848
