### ISSUE TITLE
formState isDirty not reset to false

### ISSUE THREAD

**Issue by PeterKerins** [react-hook-form/react-hook-form#3327]
**Describe the bug**

isDirty not reset to false when form is manually set back to initial values 

**To Reproduce**
1. Modify input field to be different from its initial value.
2. Modify same input to be the same as it's initial value.

isDirty remains true but dirtyFields is an empty object.

**Codesandbox link (Required)**

Forked from the form state example
https://codesandbox.io/s/react-hook-form-v6-ts-formstate-forked-vb1cc

**Expected behavior**

In previous versions manually setting the form inputs back to their initial values would reset isDirty to false. 

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: chrome, safari
- Version 86, 14.0

**Smartphone (please complete the following information):**

N/A

**Additional context**

dirtyFields is calculated as expected so a work around would be determining if isDirty via dirtyFields 

i.e. Boolean(Object.keys.formstate.dirtyFields.length)

Thanks!

**Comment by bluebill1049** [comment]
missing defaultValue for the dogs tho.

**Comment by PeterKerins** [comment]
Sorry, didn't think to, CSB is the formState example just with updated dependencies. Have updated dog's default and same issue.

**Comment by bluebill1049** [comment]
np, native input return `string` as output:

https://codesandbox.io/s/react-hook-form-v6-ts-formstate-forked-d97vs
