### ISSUE TITLE
validationFields: not recognizing value when registered via useEffect

### ISSUE THREAD

**Issue by marracheco** [react-hook-form/react-hook-form#333]
**Description**

I was trying to use `validationFields` in my project and it wasn't working at all. So I started looking at the example in the API and updating its structure to match mine. 

**The issue is** that when fields are registered via `useEffect`, the field's value isn't recognized as valid and the field is still populated in the errors object.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-validationfields-pudl6
2. Click on 'Submit'
3. See that `firstName` is in the errors object in the console
4. Now enter a value in the `firstName` field
5. Click on 'Submit'
6. See that `firstName` is **_STILL_** in the errors object in the console
7. Therefore, form is not able to be submitted.

**Expected Behavior**

`validationFields` should work whether fields are registered via `ref` inline or `useEffect`.

https://codesandbox.io/s/react-hook-form-validationfields-pudl6

**Comment by bluebill1049** [comment]
> I was trying to use `validationFields` in my project and it wasn't working at all. So I started looking at the example in the API and updating its structure to match mine.

What do you mean not working at all, can you give an codesandbox?

**Comment by bluebill1049** [comment]
> `validationFields` should work whether fields are registered via `ref` inline or `useEffect`.

your example is not complete. when you are using custom register, you need to setValue https://react-hook-form.com/api#setValue

**Comment by bluebill1049** [comment]
<img width="524" alt="Screen Shot 2019-09-26 at 8 46 03 am" src="https://user-images.githubusercontent.com/10513364/65645255-16fe4b80-e03a-11e9-9a42-962452b2f644.png">
this is your code in the codesandbox

**Comment by marracheco** [comment]
Not valid issue
