### ISSUE TITLE
Watch API isn't triggered when fields are appended to a field array

### ISSUE THREAD

**Issue by zach-waggoner** [react-hook-form/react-hook-form#3330]
**Describe the bug**
I am using the watch API to listen to an entire field array (because I need to divide the array into sections depending on the state of each field). If I append to the field array, only the `fields` object returned by `useFieldArray` is updated; the value returned by the watch API isn't updated. I can't use the `fields` object to render the field array, however, because it isn't updated when the form state of an individual field is modified.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-3330-io5ul?file=/src/index.js
1. Open the console
1. Click on "Append"
1. Note that the `fields` object is updated with the new field, but the `watchedFields` object isn't

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-3330-io5ul?file=/src/index.js

**Expected behavior**
I expect the watch API to update when fields are appended to or removed from the field array.

**Desktop (please complete the following information):**
- OS: macOS 10.15.7
- Browser: Chrome
- Version: 86

**Additional context**
My current workaround is to do

```js
const { fields } = useFieldArray({ name: "test" });
const watchedFields = watch("test", fields);
const combinedFields = zip(fields, watchedFields).map(([field, watchedField]) => ({
    id: field.id,
    ...(watchedField || field),
  }))
```

This uses the watched field if it exists; otherwise, it uses the field from `useFieldArray`. It seems to work, but it seems like the watch API should already handle this.

**Comment by bluebill1049** [comment]
strange, the CSB in the official doc works: https://codesandbox.io/s/watch-with-usefieldarray-542bu?file=/src/App.tsx

**Comment by bluebill1049** [comment]
<img width="769" alt="Screen Shot 2020-11-03 at 10 51 20 am" src="https://user-images.githubusercontent.com/10513364/97931779-83fa1e00-1dc2-11eb-80cb-dadea05201d2.png">

after i tab on append, there is no input?

**Comment by zach-waggoner** [comment]
@bluebill1049 Right, that is the bug I am reporting. I am rendering only the fields that are returned by the watch API because I need to categorize them based on the checkbox state. The codesandbox doesn't use the workaround I mentioned in order to demonstrate that the watch API doesn't include newly appended fields.

**Comment by bluebill1049** [comment]
honestly, I don't think this is a bug, but you could try with `shouldUnregister: false`.

**Comment by zach-waggoner** [comment]
Gotcha—that seems to work. I don't really follow why `shouldUnregister` makes a difference in this case—especially since the watch API seems to be updating even with `shouldUnregister: true` in the codesandbox you linked. Perhaps something else is going on here that is preventing the watch API from including newly appended fields in my example?

**Comment by bluebill1049** [comment]
so react hook form's input state is a host in the input itself by default, which is the mechanism that we can skip all the re-render while user type (each keystroke). This means our inputs r the source of truth, so every time an input gets the mount and unmount, it will register and unregister (shouldUnregister: true). However, if you set `shouldUnregister: false`, then we will keep a copy of the state update (virtually object) which is why it's working for you.

**Comment by zach-waggoner** [comment]
I see; why then does it appear to work at https://codesandbox.io/s/watch-with-usefieldarray-542bu?file=/src/App.tsx even though `shouldUnregister` is `true`?

**Comment by bluebill1049** [comment]
> I see; why then does it appear to work at https://codesandbox.io/s/watch-with-usefieldarray-542bu?file=/src/App.tsx even though `shouldUnregister` is `true`?

it should work in the first place, your example didn't work because after append there is no input on the screen, going back to my comment above.

**Comment by zach-waggoner** [comment]
Ah, that makes sense. Thanks for the explanation.

**Comment by bluebill1049** [comment]
no worries, I know it's a bit tricky when we all coming from controlled input, where the local state is the source of your inputs.
