### ISSUE TITLE
Calling useFieldArray methods in one component doesn't update the fields in other components

### ISSUE THREAD

**Issue by zach-waggoner** [react-hook-form/react-hook-form#3331]
**Describe the bug**
If I try to use the field array methods for a given field array in a different component than the one in which the field array is rendered, the field array isn't updated in the component that renders it.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-3331-h6cik
2. Append some fields
3. Click on "Delete"
4. Note that nothing happens

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-3331-h6cik

**Expected behavior**
I expect that using the field array methods returned by `useFieldArray` in one component updates the `fields` array returned by `useFieldArray` in other components that are listening to the same field array.

**Desktop (please complete the following information):**

- OS: macOS 10.15.7
- Browser: Chrome
- Version: 86

**Additional context**
Currently, it is necessary to prop-drill the field array methods in order to use them from inner components. While this works, it would be preferable if you could just call `useFieldArray` again to gain access to the methods.

**Comment by bluebill1049** [comment]
`useFieldArray` holds its own instance, just like `useForm`

https://codesandbox.io/s/react-hook-form-3331-forked-uho79
