### ISSUE TITLE
path parsing and resolving issues

### ISSUE THREAD

**Issue by terebentina** [react-hook-form/react-hook-form#3335]
**Describe the bug**
A field name like `arr[0].nested.names[0].name` is not properly parsed (`<input ref={register()} name="arr[0].nested.names[0].name" />`):
1. `arr[0].nested.names[0].name` does not work whether you're accessing the field directly or in a loop with fieldArray.
2. `arr.0.nested.names[0].name` works but so does `arr[0.nested.names[0].name`, `arr.0].nested.names[0].name`, etc.
3. watchers (watch/useWatch) _seem_ to work at first with either version although there are some quirks too.

**To Reproduce**
1. open the CSB
2. wherever you see "does not work" it means that path is not working. Where you see "works1" or "works2", it works.
3. This might be a different problem but when you launch the CSB you can see that `watch("arr[0].nested.names[1].name")` doesn't show the value yet `useWatch({ name: "arr[0].nested.names[1].name" })` does!!! Once you start typing in the second field array where it says "does not work" both watched values are updated.

**Codesandbox link (Required)**
https://codesandbox.io/s/boring-currying-u1ijv?file=/src/Form.js

**Expected behavior**
- it should work with as many nested arrays as defined in the path.
- both notations (`arr.0` and `arr[0]`) should work and resolve to the same array (some sort of normalization, I suppose). I think [getPath](https://github.com/react-hook-form/react-hook-form/blob/master/src/utils/getPath.ts) should also test for arrays, not just objects.
- both `watch` and `useWatch` should be able to display the initial value.

**Comment by bluebill1049** [comment]
Thanks for the issue, but they r all working.

1. name needs to be unique, which you have reused the same name under `FieldArray`
<img width="895" alt="Screen Shot 2020-11-03 at 8 05 11 pm" src="https://user-images.githubusercontent.com/10513364/97966391-e3cae600-1e0f-11eb-9362-7aa15dff43f4.png">

2. field array is missing defaultValue
<img width="990" alt="Screen Shot 2020-11-03 at 8 06 14 pm" src="https://user-images.githubusercontent.com/10513364/97966507-08bf5900-1e10-11eb-8692-56f7bcae17ce.png">

```tsx
      {fields.map((field, index) => (
        <div key={index}>
          arr[0]:
          <input
            autoComplete="off"
            ref={register()}
            name={`arr[0].nested.names[${index}].name`}
            placeholder="does not work"
            defaultValue={field.name}
          />
          arr.0:
          <input
            autoComplete="off"
            ref={register()}
            name={`arr.0.nested.names[${index}].name`}
            placeholder="does not work"
            defaultValue={field.name}
          />
        </div>
      ))}
```

**Comment by terebentina** [comment]
1. ok, I commented out the "direct fields" in CSB. All that's left now are the not-working field arrays and the watchers. There should be no duplicated field names anymore.
2. I was under the impression that field's defaultValue can come from the `defaultValues` specified in the `useForm` and is not required to be specified per field. Even the documentation says this: `You can populate the fields by supply defaultValues at useForm hook`. I have them set in [useForm](https://codesandbox.io/s/boring-currying-u1ijv?file=/src/App.js:695-920) in my CSB.

With these changes, the field arrays are still not populated with the brackets syntax but they are with the dotted syntax. You can reproduce by commenting out line 54 in Forms.js and uncommenting line 55 (or 56 - that works too although the path is broken).

Same problem as before with the watchers.

**Comment by bluebill1049** [comment]
please read my point 2. I have even supplied the code snippet.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#useFieldArray it's also in the doc example:

<img width="740" alt="Screen Shot 2020-11-03 at 8 45 51 pm" src="https://user-images.githubusercontent.com/10513364/97970392-92bdf080-1e15-11eb-951c-fe5bcc9afb77.png">

**Comment by terebentina** [comment]
Thanks, I answered with my point 2 to your point 2. Maybe this is more of a documentation issue then: seeing that the first code example from https://react-hook-form.com/api/#useFieldArray doesn't have a defaultValue and that the first important bullet says we can populate fields from useForm's defaultValues, I thought field arrays don't absolutely require the defaultValue prop.
![image](https://user-images.githubusercontent.com/238611/97972703-975eb680-1dcd-11eb-9c9a-44311eae58a9.png)
So maybe tweaking the language in the documentation would solve the confusion.
As far as the bug report is concerned, I am happy to close this ticket, if you want.

However, if you don't mind, I would very much like to explore the reason why defaultValue is required for the field arrays but not for normal fields, **even if we have a `defaultValues` specified in `useForm`**. 
Seeing that there is a way to avoid it, as my CSB proved, what's the downside/gotchas of not specifying the input defaultValue and instead relying on useForm's `defaultValues`?

**Comment by bluebill1049** [comment]
> So maybe tweaking the language in the documentation would solve the confusion.
As far as the bug report is concerned, I am happy to close this ticket, if you want.

please send a PR to help improve the doc.

The code example has been fixed. 

`defaultValues` will generate the fields object, the reason why we need defaultValue because we have different actions that will need to unmount and remount input to re-initialised their input value, and they can be potentially modified rather than `defaultValues`.

**Comment by bluebill1049** [comment]
Thank you very much @terandrei It's merged 👍
