### ISSUE TITLE
HandleSubmit is not *always passing form field values to user defined submit method, instead it's passing a React change event

### ISSUE THREAD

**Issue by cliffordfajardo** [react-hook-form/react-hook-form#3339]
## Describe the bug (`react-hook-form` v 6.10.1)

The form values that react-hook-form's `handleSubmit` is passing to my own onsubmit method is changing. It sometimes gets called with a React change event value instead of the form values that handleSubmit should forward to a user's own formsubmit function.

Not sure, but this might be related to:
- #3324, if that goes in I can check if I'm still having issues.

For example:

```tsx
interface IStepFormData { name: string;}

function Step1() {
  const {user} = useAuth();
  const { register, errors, handleSubmit, formState } = useForm({ mode: 'all'});
  const myHandleSubmit = (data: IStepFormData) => {
    console.log(data); // (A React event -->) Class {dispatchConfig: {…}, _targetInst: FiberNode, _dispatchInstances: FiberNode, nativeEvent: MouseEvent, _dispatchListeners: ƒ, …}
  }

  return (
      <form onSubmit={handleSubmit(myHandleSubmit)}>
        <TextField
            placeholder='Your name'
            fullWidth
            name='name'
            id='name'
            defaultValue={user?.name}
            inputRef={register({
              required: false,
              validate: isValidName, //simple synchronous regex
            })}
        />
      <button type="submit" disabled={formState.isSubmitting}>Next</button>
    </form>
  );
}
```

## To Reproduce

1. I hit submit on my form with valid values.
2. It triggers my call to `myHandleSubmit` 2 times.
   1. the 1st time `myHandleSubmit` is called, the `data`' value is a React change event `Class {dispatchConfig: {…}, _targetInst: FiberNode, _dispatchInstances: FiberNode, nativeEvent: MouseEvent, _dispatchListeners: ƒ, …}` (see (see GIF)
   2. the second time `myHandleSubmit` is called, it's correctly passed the form values.

The issue with the the form firing off twice can be solved by with the suggested solution here #834.
Ok so I adjusted my submit button so its using `formState.isSubmitting`:

```
//Only gets fired once.
<button type="submit" disabled={formState.isSubmitting}>Next</button>
```

which stops the double submission from happening. 

However, I'm still getting passed a React change event the first time `myHandleSubmit` is called. But if i remove `formState.isSubmitting` from my button and I let submit happen twice, 
 - the 1st call to `myHandleSubmit` is still getting passed a react change event to my `myHandleSubmit` method,
 - the 2nd time it passed the correct form values (see GIF)

**Codesandbox link (Required)**
**Will try to reproduce shortly**

## Expected behavior
Inside `src/types/form.ts` submit I see the at [type definition for SubmitHandler](https://github.com/react-hook-form/react-hook-form/blob/e93a319ea000abd5d319e6bef2a0e9074ff7e32c/src/types/form.ts#L53-L57) looks like this:

```ts
export type SubmitHandler<TFieldValues extends FieldValues> = (
  data: UnpackNestedValue<TFieldValues>,
  event?: React.BaseSyntheticEvent,
) => any | Promise<any>;
```

Given this, I wasn't expecting to get passed a react change event as the value of the `data` arg.

I even tried modifying my function `myHandleSubmit` to match the type declaration above, but I still run into the issue of getting passed a react change event for the value of `data` arg the 1st time `myHandleSubmit` is called

```tsx
import { useForm, SubmitHandler } from 'react-hook-form';

interface IStepFormData { name: string;}
const myHandleSubmit:SubmitHandler<IStepFormData> = (data: IStepFormData, event: FormEvent<HTMLFormElement>) => {
    console.log(data); // (A React event -->) Class {dispatchConfig: {…}, _targetInst: FiberNode, _dispatchInstances: FiberNode, nativeEvent: MouseEvent, _dispatchListeners: ƒ, …}
  }

```

I also looked at the types for 

OR there should be some sort of warning raised

**Screenshots**
![double-submit-min (1)](https://user-images.githubusercontent.com/6743796/98017339-f4e60980-1db3-11eb-836f-12db25588ba9.gif)

**Desktop (please complete the following information):**
- Google Chrome Latest

**Comment by bluebill1049** [comment]
This is really strange... I am not aware if there is anything been changed around `handleSubmit`, I couldn't reproduce this issue as well. I will wait for your codesandbox and investigate if there is an issue with this.

**Comment by bluebill1049** [comment]
any update on the CSB?
