### ISSUE TITLE
Reset textarea value in Controller

### ISSUE THREAD

**Issue by erisnuts** [react-hook-form/react-hook-form#3340]
**Describe the bug**
I can reset value of textarea using ref={register} but I can't do it with Controller.

**To Reproduce**

1. Go to [codesandbox](https://codesandbox.io/s/react-hook-form-reset-v6-ts-forked-qmtj4?file=/src/index.tsx)
2. Fill FirstName, LastName
3. Click on SubmitButton/ResetButton

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-reset-v6-ts-forked-qmtj4?file=/src/index.tsx

**Expected behavior**
LastName should be empty after submit/reset

- OS: Ubuntu 20
- Browser: Chrome 86
- Version 6.10.1

**Comment by mrlubos** [comment]
Hi @erisnuts, your CodeSandbox works for me. However, it is not using Controller which seems to be the issue in your question. I wonder if you can update the example please?

**Comment by bluebill1049** [comment]
Thanks for helping @mrlubos ❤️ @erisnuts hope the following CSB helps: 

https://codesandbox.io/s/react-hook-form-reset-v6-ts-forked-ctjws?file=/src/index.tsx

**Comment by bluebill1049** [comment]
I will also improve the doc on this one.

**Comment by bluebill1049** [comment]
<img width="950" alt="Screen Shot 2020-11-04 at 6 18 04 pm" src="https://user-images.githubusercontent.com/10513364/98080787-176a4680-1eca-11eb-840e-61db14578788.png">
looks like there is already an example.

**Comment by erisnuts** [comment]
Sorry, I had an issue with CSB. That's how the code should look like:
![Screenshot 2020-11-04 at 20 30 19](https://user-images.githubusercontent.com/3906376/98131439-155db300-1edd-11eb-9476-5c07683c6703.png)

**Comment by erisnuts** [comment]
The problem is with textarea tag, if it rendered by Controller, it's not cleared after reset/submit

**Comment by mrlubos** [comment]
@erisnuts This should work – https://codesandbox.io/s/react-hook-form-reset-v6-ts-forked-ppfuc?file=/src/index.tsx

Explanation

1. Instead of `e.target.reset()`, I do `reset()` from react-hook-form to reset all fields
1. I add `defaultValues` to `useForm()` options so `reset()` knows what to reset these values to

That being said, maybe this is a bug? @bluebill1049 will be able to tell you more

**Comment by erisnuts** [comment]
Thank you, @mrlubos! Setting defaultValue of textarea as an empty string is a workaround. I tried to reset to undefined and it didn't work.
`    defaultValues: {
      firstName: undefined,
      lastName: undefined
    }`

**Comment by bluebill1049** [comment]
please take a look at my CSB above. it's working as expected. `defaultValues` can't be `undefined`, textarea default value should be empty string.

**Comment by erisnuts** [comment]
thank you @bluebill1049 !

**Comment by bluebill1049** [comment]
np:)
