### ISSUE TITLE
defaultValues with field arrays and yup stopped working in 6.3.1

### ISSUE THREAD

**Issue by mortenk** [react-hook-form/react-hook-form#3342]
**Describe the bug**
Form fields are not populated with default values when using field arrays and yup resolver

**To Reproduce**
Click on the sandbox link
Try react-hook-form 6.3.0 to see default values being populated
Change it to 6.3.1 to see it stop working

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-array-default-values-696-jigu1?file=/src/index.js

**Expected behavior**
I expect form fields to be populated

**Desktop (please complete the following information):**
Any os/browser

**Smartphone (please complete the following information):**
Any device/broser

**Comment by bluebill1049** [comment]
Have a look at the changelog just like we discussed: https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md

**Comment by bluebill1049** [comment]
reference for others: https://github.com/react-hook-form/react-hook-form/discussions/3280

**Comment by bluebill1049** [comment]
For more information in terms of defaultValue with `useFieldArray`, please refer to the doc: 
https://react-hook-form.com/api/#useFieldArray

**Comment by mortenk** [comment]
This has been working as expected since at least 5.x, now it is broken. 
How can it not be a bug? 
It breaks in a patch version and you say it's intentional?

**Comment by mortenk** [comment]
Commit 634bb0815c7e450c61c30a6c274ea68327e6af91 is the cause of this breakage

**Comment by bluebill1049** [comment]
same reply as in the discussion:

This is the best opportunity for you to contribute if you truly believe without defaultValue will not introduce bug with all useFieldArray action. I would recommend you fork the repo, have some deep investigation before making a judgment that I can work without defaultValue. On the other hand, if it truly works and passes all unit tests and integration I am more than happy to review your PR. This is in the doc from the very beginning of V6, you can go watch the video tutorial. It may work (but with a bug) before 6.3, but it's always required to have defaultValue to avoid issues while shuffling the array field if may work for your use case, but this is not made only work single use case.
