### ISSUE TITLE
Incorrect validation with Yup.ref

### ISSUE THREAD

**Issue by Kontsedal** [react-hook-form/react-hook-form#3346]
**Describe the bug**
A form shows incorrect errors if I'm using Yup.ref

**To Reproduce**

1. Go to [https://codesandbox.io/s/react-hook-form-with-yup-forked-st0fq?file=/src/Form.js](https://codesandbox.io/s/react-hook-form-with-yup-forked-st0fq?file=/src/Form.js)
2. Fill "Confirm password" field first
3. Enter the same string to the password field
4. See the error "Password and confirmed password do not match."

**Expected behavior**
If passwords match, no errors should be observed

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser Chrome
- Version 86

**Comment by bluebill1049** [comment]
<img width="715" alt="Screen Shot 2020-11-04 at 8 18 46 pm" src="https://user-images.githubusercontent.com/10513364/98092609-f3fbc780-1eda-11eb-9f96-fdfc06131bf6.png">

works for me.

**Comment by Kontsedal** [comment]
@bluebill1049  try to fill the second field at first

**Comment by bluebill1049** [comment]
Thanks, @Kontsedal, because RHF is based on field-level validation for better perf.

````passwordConfirm: Yup.string().oneOf(
    [Yup.ref("password"), null],
    "Password and confirmed password do not match."
  )```

so you need to `trigger('passwordConfirm')`

**Comment by Kontsedal** [comment]
Oh, I see. I've tried and it works. Thanks a lot :)

**Comment by bluebill1049** [comment]
np worries, some background: traditional with controlled form, we are pretty much validation the entire form all the time and render base on each keystroke, in RHF we focus on individual input unless the user wants to validate other fields.

**Comment by Kontsedal** [comment]
That makes sense, looks like I've missed this part in the docs, need to read it again
