### ISSUE TITLE
FormContext setError and clearError useEffect cause infinite renders

### ISSUE THREAD

**Issue by tknickman** [react-hook-form/react-hook-form#335]
## Description
Using `setError`, and `clearError` from `useFormContext` in the dependency array of a `useEffect` hooks causes components to infinitely re-render. 

I discovered this because we have the [react-hooks/exhaustive-deps](https://www.npmjs.com/package/eslint-plugin-react-hooks) eslint rule enabled in our codebase, so anything external to the effect MUST be included in the dependency array. 

I believe this is happening because `useFormContext` is providing _new_ copies of  `clearError` and `setError` on every render. I believe this could be fixed by utilizing `useCallback`. 

Simple example (full codesandbox with usecase included in reproduction steps below)
```
const { setError, clearError } = useFormContext();

useEffect(() => {
  if(error) {
      setError(error)
  } else {
      clearError()
  }
}, [setError, clearError, error]);

// infinitely renders
```

I was able to work around this for now by disabling the eslint rule for that line, but this should also be fixed for performance reasons.

I'll take a look at making PR later today as well, but wanted to get this up first for feedback. 

## To Reproduce
1. Go to [CodeSandbox](https://codesandbox.io/s/react-hook-form-form-context-bug-8nn6w)
2. Navigate to the `DatePicker.js` file
3. Notice how the form works and reports errors as usual, and renders only a few times (reported in console)
4. Change the useEffect dependency array on line 58 from `WORKING_DEP_ARRAY`, to `INFINITE_RENDER_DEP_ARRAY`. 
5. Notice how the form infinitely renders. 

## Expected behavior
A component should not re-render infinitely if  `setError`, and `clearError` need to be used within a `useEffect` dependency array. `useFormContext` should not return new copies of these functions every time. 

### Desktop
 - OS: Mac OX
 - Browser: Chrome
 - 77.0.3865.90

**Comment by bluebill1049** [comment]
thanks for reporting issue, i will take a look at it

**Comment by tknickman** [comment]
Thanks! 

I also noticed your automation tests are disabling this eslint rule as well:
https://github.com/react-hook-form/react-hook-form/blob/master/app/src/setError.tsx#L15

😄

**Comment by bluebill1049** [comment]
lol @tknickman I was lazy there :) will reenable them I tested all `useform` methods in the `useEffect`. This context one did test as well, try to find the root cause. feel free to submit a PR to re-enable those :)

**Comment by bluebill1049** [comment]
strange i couldn't reproduce locally with my example, but yours does cause the issue...

**Comment by bluebill1049** [comment]
try this beta: 3.23.13-beta.1

**Comment by bluebill1049** [comment]
`3.23.13-beta.1` i have tested and it's working

**Comment by bluebill1049** [comment]
can you verify this doesn't break your app?

**Comment by tknickman** [comment]
Boom, that works great. Thanks a ton @bluebill1049!

Updated the sandbox with the beta here and all is well: https://codesandbox.io/embed/react-hook-form-form-context-bug-8nn6w

I'll close this issue, and I'll keep using the beta for now and report back if I find anything weird. 

Thanks again!

**Comment by bluebill1049** [comment]
@tknickman thanks heaps buddy, i will release this patch soon as well :)

**Comment by Zerebokep** [comment]
Looks like I have the same problem. I'm using next js and receiving the following error when using setError inside useEffect:

`Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.`

I have setError in the dependency array of useEffect.
