### ISSUE TITLE
Suggestion: rename "ref" prop in Controller render()

### ISSUE THREAD

**Issue by dadouam** [react-hook-form/react-hook-form#3350]
Hello,

**Is your feature request related to a problem? Please describe.**
During my migration from V5 to V6, I used the following syntax to simplify moving from the `as` prop to the `render` Controller prop, since most of the time, there was a 1-1 match between the names of the passed props and the component props (value, onChange...)
```jsx
<Controller name={"myName"} render={p => <MyComponent {...p}/>}/>
```
Note that the following syntax is described in the doc, so I thought it would be an easy and convenient way to make the migration easier.

However, I found out that 6.10 recently added a `ref` prop, and while I think it's a good idea to be able to pass down a ref, it causes the following error to show up on the console for most of my controlled functional components : `Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

I certainly don't want to wrap all of my functional form components with forwardRef (sometimes tricky to do in TypeScript, and not always relevant) and of course, I can choose to not include the `ref` prop in what I pass down to the render() component, but I wonder if maybe it would be a good idea to rename this `ref` prop?

I think it makes some sense because :

- `ref` are unlike other props so passing down a `ref` prop has some gotchas (can trigger errors in console, doesn't work out of the box with functional components...)
- Most components used with RHF should be functional, since class components are kinda legacy now. So it would mean we would have to be extra careful when passing down the `render()` props, and even more also when using the `as` prop (I've checked that with the `as` prop, it also passes down the ref prop, and unlike `render()`, there doesn't seem to be a way out of this problem, although `as` is no longer the recommended way) 

**Describe the solution you'd like**
Considering that `ref` is a special prop "reserved" by React, I suggest renaming the `ref` passed down by `Controller` to something else, like `controllerRef`. Then it would be up to the developer to bind this ref to either the component `ref` or other prop (`inputRef`, etc...)

**Comment by dadouam** [comment]
A possible workaround is to wrap `Controller` into a custom Controller that renames the `ref` prop to something else. Not ideal of course since I'd need to keep the types consistent with future RHF releases.

```typescript
// eslint-disable-next-line @typescript-eslint/ban-types
type AsProps<TAs> = TAs extends undefined ? {} : TAs extends React.ReactElement ? Record<string, any> : TAs extends React.ComponentType<infer P> ? P : TAs extends keyof JSX.IntrinsicElements ? JSX.IntrinsicElements[TAs] : never;

type MyControllerProps<TAs extends React.ReactElement | React.ComponentType<any> | 'input' | 'select' | 'textarea', TControl extends Control = Control> = Assign<({
  as: TAs;
  render?: undefined;
} | {
  as?: undefined;
  render: (data: {
    onChange: (...event: any[]) => void;
    onBlur: () => void;
    value: any;
    name: FieldName<FieldValuesFromControl<TControl>>;
    controllerRef: React.MutableRefObject<any>;
  }) => React.ReactElement;
}) & {
  name: FieldName<FieldValuesFromControl<TControl>>;
  rules?: ValidationRules;
  onFocus?: () => void;
  defaultValue?: unknown;
  control?: TControl;
}, AsProps<TAs>>;

export function MyController<TAs extends React.ReactElement | React.ComponentType<any> | 'input' | 'select' | 'textarea', TControl extends Control = Control>(props: MyControllerProps<TAs, TControl>) {
  const {render, ...rest} = props;

  function myRender(data) {
    if (!render) {
      return undefined;
    }
    const {ref, ...r} = data;
    const passData = {...r, controllerRef: ref};
    return render(passData);
  }

  return (
      <Controller {...rest as any} render={myRender as any}/>
  );
}
```

I'll keep the issue open because I'd love to hear about what are the best practices with `render()` props passing, and if you consider to rename the ref prop.

**Comment by bluebill1049** [comment]
Valid point ^, this was made if input ref was exposed correctly for `focus`.

- <Controller render={({ ref, ...rest }) => <input rest={rest} />}
- <Controller render={({ inputRef, ...rest }) => <input rest={rest} ref={inputRef} />} // which need code change.

**Comment by dadouam** [comment]
Indeed, changing the name requires a code change, although I'm not sure if it would break a lot of projects since it's a recent addition.
I think the problem with the current `ref` prop is that it can only work for some specific cases unlike the other props (e.g an `<input/>`, or some third-party components that provide a `focus()` method such as React-Select, though it's pretty nice when it does work that way!) so personally I think a renaming to `inputRef` (or perhaps `focusRef` to make it more visible that RHF expects this ref to have a `focus()` method?) would make sense to avoid confusion over what this ref is supposed to do and prevent some warnings.
I'd totally understand if you keep it that way though :D

Btw, another suggestion about this line:
```typescript
const onFocusRef = React.useRef(onFocus || (() => ref.current.focus()));
```
I suggest adding a console.warn if `typeof current.focus !== 'function'` to make it apparent that this ref only works on elements/components that provide a focus method (for reference, at first, I tried to pass this ref to a `react-dates` datepicker, and during validation, it threw a `ref.current.focus is not a function` error)

**Comment by bluebill1049** [comment]
I have a deeper think last night in bed. I think we will keep `ref` as it is (not rename them just for now), the whole reason behind is to push users to wire up focus event if possible so their form is more accessible for input errors. To keep `ref` as it is, I think it aligns with how we use ref at `register` function, and hesitate to introduce breaking change for users who may already use it.

>I suggest adding a console.warn if typeof current.focus !== 'function' to make it apparent that this ref only works on elements/components that provide a focus method (for reference, at first, I tried to pass this ref to a react-dates datepicker, and during validation, it threw a ref.current.focus is not a function error)

please send us a PR :) your name should be on the contribution list. you can use `isFunction` method

**Comment by dadouam** [comment]
Thank you for your answer, I totally understand why you'd hesitate to introduce a breaking change here and your other reasons. So I'll close this issue for now.

Btw, thanks for your review on my PR and keep up your good work on your awesome lib :smile:
