### ISSUE TITLE
Dot (.) chars in property names result in nested form values

### ISSUE THREAD

**Issue by automatensalat** [react-hook-form/react-hook-form#3351]
**Describe the bug**

I have hit a use case now where we have an object that has dynamic keys that can contain dots (`.` character). This causes `react-hook-form` to break up the object into several nested objects: 

```tsx
function RHFTest() {
	const myObj = {
		"my.funny.key": 3,
	};

	const { control, getValues, watch } = useForm<typeof myObj>({
		defaultValues: myObj,
	});

	// prints {"my":{"funny":{"key":3}}} rather than {"my.funny.key": 3}
	console.log("watch(): ", JSON.stringify(watch()));
	// prints undefined
	console.log("getValues(): ", getValues()["my.funny.key"]);
	// prints {"my.funny.key": 3}
	console.log(JSON.stringify(myObj));

	return (
		<Controller
			name="my.funny.key"
			control={control}
			render={(props) => <input {...props} />}
		/>
	);
}
```

Thus, the values of the object controlled by the form no longer matches the shape of the input object, as declared by the type parameter. 

**Additional context**
Using RHF 6.8.0

**To Reproduce**
Mount above component

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-forked-hreyl?file=/src/index.js

**Expected behavior**
When I call `getValues()` or `watch()` I expect the return value to have the same shape as the input object

**Desktop (please complete the following information):**

- OS: Ubuntu Linux
- Browser Chromium
- Version 86

**Additional context**
To prevent ambiguity we could support bracket property accessor notation like so: 
```
const myObj = {
  hello: { "my.funny.key": 3 }
};
...
<Controller
  name="hello[my.funny.key]"
  control={control}
  render={(props) => <input {...props} />}
/>
```

**Comment by bluebill1049** [comment]
Not a bug, certainly you can request a separate feature request for not convert this into an object.
<img width="946" alt="Screen Shot 2020-11-05 at 8 56 04 am" src="https://user-images.githubusercontent.com/10513364/98172010-bdf32d80-1f44-11eb-98fe-5c29affbbde0.png">

**Comment by MikePrus** [comment]
> Not a bug, certainly you can request a separate feature request for not convert this into an object. then will let the community decide if such feature meet many's need.
> 
> <img alt="Screen Shot 2020-11-05 at 8 56 04 am" width="946" src="https://user-images.githubusercontent.com/10513364/98172010-bdf32d80-1f44-11eb-98fe-5c29affbbde0.png">

How I can avoid this behavior? I need to have key like ```'name.firstName': 'John' ```, in my data object on form submit.

**Comment by Moshyfawn** [comment]
You'll have to transform your data object `onSubmit` yourself
