### ISSUE TITLE
useWatch on a field array of controlled components leads to unexpected behaviour [Controller]

### ISSUE THREAD

**Issue by nhanpdnguyen** [react-hook-form/react-hook-form#3353]
**Describe the bug**
Hi everyone, I'm implementing a feature using field array with some controlled custom input (using `render` attribute on `Controller`)
Then I ran into this issue, the `watchedFieldArray`'s newly-added item gets `undefined`. I noticed that this issue happens when inserting an item at an in-between index.

**To Reproduce**
1. Go to CodeSandbox link
2. Click Insert at index 1
3. Watch the Console logs and see the index-1 item is `undefined`
4. Click Append
5. Watch the Console logs and see the last item is not `undefined`

**Desired output**

**Codesandbox link (Required)**
https://codesandbox.io/embed/unruffled-thompson-yx492?file=/src/App.js:1628-2152

**Expected behavior**
the index-1 item is not `undefined`

**Desktop (please complete the following information):**

- OS: MacOS 10.15.7
- Browser: Chrome
- Version: 86

**Additional context**
If I add `shouldUnregister: false` option to `useForm`, the problem goes away

**Comment by bluebill1049** [comment]
Thanks, i have created the same lol https://github.com/react-hook-form/react-hook-form/issues/3349 will take yourself.
