### ISSUE TITLE
useFieldArray's append does not create and set a value on input components

### ISSUE THREAD

**Issue by ramonmsp** [react-hook-form/react-hook-form#3355]
**Describe the bug**
I want to create a dynamic form (useFieldArray) and set a default values on fields from fetched data (this data really exists). Although I'm using append and/or setValue features, this data hasn't been set on inputs/selects.

**To Reproduce**

1. Go to sandbox
2. There is a loop on fields by useFieldArray and a array (myTasks) that contains a data to set on components

**Codesandbox link (Required)**
https://codesandbox.io/s/zen-lichterman-qyb7c?file=/src/App.js:867-1107

**Expected behavior**
 1 - It should render three (length of myTasks array) groups (input + select) of components 
 2 - These inputs should have been created, filled with myTasks data 

**Desktop (please complete the following information):**

- OS: WIN10
- Browser:  chrome
- Version: "react-hook-form": "^5.7.2",

**Comment by bluebill1049** [comment]
please refer to the doc under useFieldArray.

<img width="882" alt="Screen Shot 2020-11-05 at 8 59 07 am" src="https://user-images.githubusercontent.com/10513364/98172267-2b9f5980-1f45-11eb-8174-c705599094e3.png">

however, you can do append([])
