### ISSUE TITLE
Unexpected behaviour of isDirty form state when using field array in combination with regular controls.

### ISSUE THREAD

**Issue by PlaygroundA** [react-hook-form/react-hook-form#3368]
**Describe the bug**
Unexpected behaviour of isDirty form state when using field array in combination with regular controls.

I have a form, consisting of field array and several controls. And the problem is:
When I change one of the  regular input fields, that are not part of the field array -  "is Dirty" state becomes true - which is Ok. Then, when you append new array item, "isDirty " remains the same - which is also ok, but when you remove the array item you just added, "isDirty" becomes false, even though regular controls have changed.

**To Reproduce**

1. Open CSB link (link is below).
2. Open console.
3. Change 1st control value (default value 'hello'). In console you'll see 'IS DIRTY - true'
4. Click Append to add new array item. IS DIRTY remains the same
5. Remove just added array item.  Is dirty form state property will become false although the 1st control value has been changed.

**Codesandbox link (Required)**
[https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-dq1fh?file=/src/index.js](https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-dq1fh?file=/src/index.js)

**Expected behavior**
Property `formState.isDirty = true ` for any change in form controls values.

**Desktop**
- OS: Windows 10
- Browser: Chrome

**Additional context**
The latest version of react-hook form was used (6.10.1)

**Comment by bluebill1049** [comment]
Thank you for the issue report! fixed last night will be in the next patch: https://github.com/react-hook-form/react-hook-form/commit/2c5ad5e0a13b36c678c426e4c918c0e343accb78
