### ISSUE TITLE
Unable to use React Hook Form with Material UI's TextField: "Miss name on ref"

### ISSUE THREAD

**Issue by dpw1** [react-hook-form/react-hook-form#337]
**Describe the bug**
React Hook Form won't work with Material UI's `TextField`'. Once the form is submit the data is not captured.

**To Reproduce**
1. Add TextField from Material UI to your project;
2. Add name & ref;
3. Try to submit data.

[Live CodeSandbox example here](https://codesandbox.io/s/react-hook-form-get-started-znn11).

**Expected behavior**
It should work just like a regular JSX <input/>

**Desktop (please complete the following information):**
Windows 7
Google Chrome
Version: 77.0.3865.90

**Comment by bluebill1049** [comment]
for material ui is `inputRef={register({ required: true })}`

**Comment by bluebill1049** [comment]
feel free to re-open if this does not solve your issue :)

**Comment by dpw1** [comment]
Splendid! Thank you very much for your help and quick reply as always. :)
