### ISSUE TITLE
Input modifications are not persist in fields object from useFieldArray() hook

### ISSUE THREAD

**Issue by yekver** [react-hook-form/react-hook-form#3370]
This is quite a confusing thing but object `fields` exposed from the `useFieldArray({name: 'test')` hook is not equal to the current actual state (getValues('test'). And all modifications that has been made to this `test` array field using `setValue()` method are not exists in `fields` object. Somehow `remove()` method can temporary fix this bug, but this is even more strange.

If next appended row should copy edited value from the previous row this wouldn't work as expected and old value will be copied.

Also `useEffect` wouldn't be triggered during every row modification (except using exposed from the `useFieldArray` hook helper methods)

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-gj10i?file=/src/index.js

**Screenshots**
![Screen Recording 2020-11-05 at 23 02 04](https://user-images.githubusercontent.com/1935877/98291419-2b8e7080-1fbc-11eb-9424-14e882d5405a.gif)

**Comment by bluebill1049** [comment]
This is expected behavior, I am not sure how familiar you are with React Hook Form, but RHF is an uncontrolled form, which means `fields` is only meant to populate the default value of each input, the state update is lived within each input, hence this lib doesn't constantly trigger re-render the Form level. If you want to subscribe to each inputs' updated value, then use `watch` or `useWatch` API.

**Comment by bluebill1049** [comment]
![Uploading Screen Shot 2020-11-06 at 4.40.41 pm.png…]()

**Comment by yekver** [comment]
Yeah, you right I'm a newbie to RHF. Maybe this is even better, because I can provide a feedback without deep context of this lib and describe what exactly I was confused of.

I haven't wound any information in [useFieldArray section](https://react-hook-form.com/api#useFieldArray) about the `fields` actual behavior and I think it should be mentioned that this object is not a reference to the real data (provided by `getValues()` method).

Also I was confused by an example with `useEffect(() => {...}, [fields])` because I thought that `fields` declared as a dependency of an `effect` will behave like a real data. I had to read the source code to finally understand that `fields` changed only by hook helpers and nothing more. But why `delete()` temporarily fixes the situation - this is a good question that has to be clarified.

I think all of thinks should be carefully described in this docs section.

**Comment by bluebill1049** [comment]
> Yeah, you right I'm a newbie to RHF. Maybe this is even better, because I can provide a feedback without deep context of this lib and describe what exactly I was confused of.

Nope, I disagree with the above and contradict the rest of your statement. If you not going to read the doc and complain about missing context, sorry I can't help. I am not here to win you over an argument, by answering your issue, I am already here to help and it's better than just simplify ignore your question.

> I haven't wound any information in useFieldArray section about the fields actual behavior and I think it should be mentioned that this object is not a reference to the real data (provided by getValues() method).

Complain is a very easy task to do :) You can contribute as this is open source, no one owns anyone a favor.

> Also I was confused by an example with useEffect(() => {...}, [fields]) because I thought that fields declared as a dependency of an effect will behave like a real data.

context example?

> But why delete() temporarily fixes the situation - this is a good question that has to be clarified.

fix what? steps to reproduce?

**Comment by yekver** [comment]
>  If you not going to read the doc and complain about missing context, sorry I can't help. 

I didn't say that I haven't read the docs. Of corse I did and by missing context I meant that I don't have deep knowledge of how to deal with corner cases, etc.

> fix what? steps to reproduce?

In the example I've provided earlier there is a case when you

1. add a new row
2. modify lastName of the last row
3. add one more row (stale `lastName` value will be copied)
4. remove last row
5. add one more row (correct `lastName` value will be copied)

> context example?

Sorry, I didn't get it can you explain, please?

**Comment by bluebill1049** [comment]
your example is not following the doc: https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-gj10i?file=/src/index.js

<img width="586" alt="Screen Shot 2020-11-07 at 9 02 43 am" src="https://user-images.githubusercontent.com/10513364/98418891-0000a880-20d8-11eb-8e21-ed0f120c3ebd.png">

if you want to build field array controlled, this is not the lib for it.

**Comment by bluebill1049** [comment]
have a look at this CSB: https://codesandbox.io/s/react-hook-form-usefieldarray-vy8fv which contains an example with `watch`, again this is not a controlled form with `useFieldArray`.
