### ISSUE TITLE
Conditional input field let form dirty after unmounted/unregistered.

### ISSUE THREAD

**Issue by paslo22** [react-hook-form/react-hook-form#3373]
**Describe the bug**
When conditional input is unmounted the form remain dirty and conditional field still shows up on `formState.dirtyFields`. 

**To Reproduce**

1- Load the form.
2- Select "second" in radio options. Input should show up.
3- Select "first" again in radio options.
4. Watch console.

**Codesandbox link (Required)**
https://codesandbox.io/s/cool-field-5f5kf

**Expected behavior**
Form should be back to be clean && dirtyFields should be empty.

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser: Chrome
- Version 86.0.4240.183

**Comment by bluebill1049** [comment]
I think we need to focus on `deafultValues` instead of checking `dirtyFields` as well, make it a single source of truth, will make a minor version to fix this.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/commit/4c660f8fd94c1e564eee6dbf3fd36481469e81bd patched
