### ISSUE TITLE
Default values in submit object model

### ISSUE THREAD

**Issue by vytcus** [react-hook-form/react-hook-form#3376]
Original documentation mentions that: 
_Its not default state for the form, to include additional form values:_

_Register hidden input: `<input type="hidden" ref={register} name="test" />`_

_Combine values at onSubmit callback._

**Is your feature request related to a problem? Please describe.**
In dynamic nested forms. Where you receive form template from API, for example merging the objects can become quite tedious. And including hidden inputs seems like a workaround which reduces code readability and unnecessarily clutters the dom.

**Describe the solution you'd like**
Receive default values on submit as well.

**Comment by bluebill1049** [comment]
you can try with `shouldUnregister: false`.

**Comment by vytcus** [comment]
shouldUnregister works. Although all values become strings. Thanks for the fast response!

**Comment by bluebill1049** [comment]
👍 what do you mean all values become strings? do you have a csb?

**Comment by bluebill1049** [comment]
closing this issue, but feel free to follow up with the above question.
