### ISSUE TITLE
react-dom.production.min.js:209 TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by ankitk20** [react-hook-form/react-hook-form#3377]
**Describe the bug**
Upgraded package version from 6.0.4 to 6.10.1 and got the following error
![image](https://user-images.githubusercontent.com/13991339/98356256-4fe45e80-2049-11eb-8b0a-d928f2f5e102.png)

After downgrading the package back to 6.0.4 the error was gone

**Expected behavior**
Expected form to popup on a button click instead got the above error

**Screenshots**
![image](https://user-images.githubusercontent.com/13991339/98356256-4fe45e80-2049-11eb-8b0a-d928f2f5e102.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Microsoft Edge Chromium
- Version 86.0.622.63 (Official build) (64-bit)

**Additional context**
This error is only in production after publishing on App Service and works as expected on localhost

**Comment by bluebill1049** [comment]
where is the link for the prod app?

**Comment by bluebill1049** [comment]
and what's the code? can you share in a CSB?

**Comment by bluebill1049** [comment]
I will investigate this again once reproducible CSB or code is supplied.

**Comment by ankitk20** [comment]
Please pardon me for the delay, here's the file [URL](https://github.com/microsoft/Power-BI-Embedded-Contoso-Sales-Demo/blob/main/ContosoSalesDemo/ClientApp/src/components/Forms/EditLeadForm.tsx) which contains the code

**Comment by bluebill1049** [comment]
https://github.com/microsoft/Power-BI-Embedded-Contoso-Sales-Demo/blob/main/ContosoSalesDemo/ClientApp/src/components/Forms/EditLeadForm.tsx#L396

your component is potential gets mount and unmounted each render. create a separate component, see if this problem is still persist.

**Comment by ankitk20** [comment]
But it is working on localhost, how to explain that?

**Comment by lakheraakshay** [comment]
But it is working on localhost, how to explain that?  I am facing the same error

**Comment by bluebill1049** [comment]
@lakheraakshay I can't explain anything without the actual code compare with prod and local. steps

1. provide a simple codesandbox with local code
2. deploy to somewhere 
3. we do the investigation

**Comment by RolandSall** [comment]
Any update on this? I am also having the same issue

**Comment by TariqAbughofa** [comment]
until @bluebill1049 decide to take issues seriously instead of closing them, the solution is to use version 6.0.4

**Comment by bluebill1049** [comment]
> until @bluebill1049 decide to take issues seriously instead of closing them, the solution is to use version 6.0.4

Until someone can provide me a producible example of this problem and stop giving me bs about I am closing issues and maintaining this lib.

**Comment by mongsukim** [comment]
Any update on this? I am also having the same issue
