### ISSUE TITLE
Can't find variable: HTMLElement crash react-native

### ISSUE THREAD

**Issue by devaublanc** [react-hook-form/react-hook-form#338]
**Describe the bug**
In react native I got a crash when TextInput change. Because `HTMLElement` does not exists in a React native context. https://github.com/react-hook-form/react-hook-form/blob/886cb3664b3d7bd9ecf79b1de3940a1e9ac14db1/src/useForm.ts#L115
CF PR => https://github.com/react-hook-form/react-hook-form/pull/317

**To Reproduce**
Try to change the value of your `<TextInput />`

**Expected behavior**
You have to change to `setValue` without crash `<TextInput />`

**Screenshots**
![Capture d’écran 2019-09-30 à 11 51 03](https://user-images.githubusercontent.com/12794277/65868507-ad9f7500-e378-11e9-854c-aad7143c88fb.png)

**Desktop (please complete the following information):**
 - OS: iOS/Android

**Smartphone (please complete the following information):**
 - Device: iPhoneX

**Additional context**
Here the basic code I'm trying to run
```javascript
import React from "react"
import { Text, View, TextInput, Button, Alert } from "react-native"
import useForm from 'react-hook-form'

export default function App() {
  const { register, setValue, handleSubmit, errors } = useForm()
  const onSubmit = data => Alert.alert('Form Data', data)

  return (
    <View>
      <Text>First name</Text>
      <TextInput
        ref={register({ name: 'firstName'}, { required: true })}
        onChangeText={text => setValue('firstName', text, true)}
      />
      {errors.firstName && <Text>This is required.</Text>}

      <Text>Last name</Text>
      <TextInput
        ref={register({ name: 'lastName'})}
        onChangeText={text => setValue('lastName', text)}
      />

      <View>
        <Button onPress={handleSubmit(onSubmit)} title={'text'} />
      </View>
    </View>
  )
}
```

**Comment by bluebill1049** [comment]
thanks @devaublanc i will patch that, feel free to spend a PR too
