### ISSUE TITLE
Controller not working with Material UI Switch and Checkbox

### ISSUE THREAD

**Issue by Huford** [react-hook-form/react-hook-form#3392]
**Describe the bug**
Controller not working with Material UI Switch and Checkbox components

**To Reproduce**

1. Go to the code sandbox below
2. Send form without interacting with checkbox or Switch
3. Values are undefined
4. Interact with checkbox or Switch
5. Send form, observe now the values are empty string regarding the actual values of the components

**Codesandbox link (Required)**
[CodeSandBox](https://codesandbox.io/s/react-hook-form-controller-template-forked-mf582?file=/src/index.js)

**Expected behavior**
Switch should reflect the actual value (true or false)

**Screenshots**

**Desktop (please complete the following information):**

- OS:MacOs Catalina
- Browser: Chrome
- Version:  86.0.4240.111

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bluebill1049** [comment]
official doc example: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r
<img width="922" alt="Screen Shot 2020-11-09 at 8 46 02 am" src="https://user-images.githubusercontent.com/10513364/98485096-01f97180-2268-11eb-9a83-7d162c663cf3.png">

The following props will be passed into your component: onChange, onBlur, value, name, ref; there is no `checked` prop for `as`
<img width="962" alt="Screen Shot 2020-11-09 at 8 46 20 am" src="https://user-images.githubusercontent.com/10513364/98485106-0c1b7000-2268-11eb-94d1-c7a353f724d3.png">
