### ISSUE TITLE
Pattern validation not working properly with errors

### ISSUE THREAD

**Issue by danluckner** [react-hook-form/react-hook-form#3393]
Hello, I have found a strange behavior regarding the pattern validation.
Honestly, I don't know if it is a bug or if my code is wrong.

I'll try to explain to the best of my ability.

**Bug description**
The form has a telephone input validation with regex, that's where the behavior is somewhat confusing.
I have also made a mask logic with the onChange method that replaces the target value with the correct pattern.

Let's say one hits send without fulfilling the pattern. The React-Hook-Form will issue an "errors" object.

If one starts typing the telephone with numbers unitl the pattern (99) 9999-9999 is reached, the "errors" obejct will indcate a mismatch with the pattern, but if the send button is pressed, there will be no pattern error.

**To Reproduce**

1. Go to https://codesandbox.io/s/agitated-bush-8wutr?file=/src/App.js
2. Click on 'Send' without typing anything. Error message and style shall appear.
3. Start typing numbers in the text input until it reaches the pattern (99) 9999-9999. The "errors" object still issues a type "pattern".
4. Hit send. The pattern validation will go through and the data will go through.

**Codesandbox link **
https://codesandbox.io/s/agitated-bush-8wutr?file=/src/App.js

**Expected behavior**
The pattern validation should work the same way for onChange or onSubmit.

**Desktop (please complete the following information):**

- OS: Windows 10 version 18363.1139 64-bit
- Browser Chrome  version 86.0.4240.183 64-bit

**Comment by bluebill1049** [comment]
because you are manipulating the input `onChange`, which means is not the result which input is retrieved on the current state rather the next tick.

`event.target.value = normalizeTel(value);`

you can kick in the validation tho, with `trigger`

```
        onChange={(event) => {
          const { value } = event.target;
          event.target.value = normalizeTel(value);
          trigger("tel");
        }}
```

https://codesandbox.io/s/fervent-monad-bkmc1

**Comment by danluckner** [comment]
@bluebill1049 It worked, thank you!

**Comment by bluebill1049** [comment]
np :) hopefully, it makes sense of what I stated above.

**Comment by danluckner** [comment]
@bluebill1049 Yes, I was kind of understand that the target.value was always "one step behind" the validation. I just needed the trigger method to make it work.
