### ISSUE TITLE
Values are not cleared using the Сontroller

### ISSUE THREAD

**Issue by SergeyWebDeveloper** [react-hook-form/react-hook-form#3400]
**Describe the bug**
Field values made through the controller are not reset when set to zero

**To Reproduce**

1. Fill in the fields on the form. (the first field is done through a regular input, the second through a Controller);
2. Сlick on `Submit Form` button (in the console we will see the completed form fields)
3. Press the button `Submit Form` again. In the console, we will see that the field value made through the controller is not reset

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-reset-v6-forked-i155f?file=/src/index.js

**Expected behavior**
All form values are reset

**Comment by ZeroPie** [comment]
You have to provide default Values
https://react-hook-form.com/api#reset

I tried this in your code sandbox and both fields are now set to ""
```
  const formMethods = useForm({
    mode: "onBlur",
    defaultValues: {
      lastName: ""
    }
  });
```

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#reset

![Uploading Screen Shot 2020-11-09 at 10.58.58 pm.png…]()

**Comment by SergeyWebDeveloper** [comment]
as an option, of course, but I think zeroing shouldn't work that way. And if I have 1000 fields on the form, it's not entirely correct to set default values for all fields.

**Comment by bluebill1049** [comment]
does my answer above solve your problem?

**Comment by SergeyWebDeveloper** [comment]
@bluebill1049 , https://codesandbox.io/s/react-hook-form-reset-v6-forked-46dxw?file=/src/index.js
open console, pls, the value remains the same if you press the send button several times. What am I doing wrong?

**Comment by bluebill1049** [comment]
did you see my screenshot? there is an example in the doc as well. `reset` shouldn't be invoked inside onSubmit.

**Comment by bluebill1049** [comment]
<img width="1274" alt="Screen Shot 2020-11-10 at 10 06 35 pm" src="https://user-images.githubusercontent.com/10513364/98666348-007f9480-23a1-11eb-8fd8-67304ba8c0a3.png">

the order:

- `onSumbit` callback gets invoked
- reset({})
- input clear

**Comment by bluebill1049** [comment]
here is the correct usage: https://codesandbox.io/s/react-hook-form-reset-v6-forked-uqy6t?file=/src/index.js

when you declare useForm `defaultValues`, then you don't need `defaultValue` at Controler.

<img width="965" alt="Screen Shot 2020-11-10 at 10 11 34 pm" src="https://user-images.githubusercontent.com/10513364/98666843-b2b75c00-23a1-11eb-8a87-884459811ee1.png">

**Comment by SergeyWebDeveloper** [comment]
@bluebill1049 , what if i can't specify default values myself? Or if I have a lot of fields?
By clicking on Reset, I mean that all my fields should be reset to zero, both in UI and in the form state.
https://codesandbox.io/s/react-hook-form-reset-v6-forked-gdi7b?file=/src/index.js

In my real case, I have a lot of fields that are made through the Controller and have an empty string by default value, as in the example above.

**Comment by bluebill1049** [comment]
That's how this lib works and what's been specified in the doc.
