### ISSUE TITLE
formState.dirtyFields not working on first change for controlled components

### ISSUE THREAD

**Issue by LoicHa** [react-hook-form/react-hook-form#3402]
**Describe the bug**
I am maybe doing something wrong but i can't find a proper way to fix my issue . For controlled component dirtyFields are not updated on the first input change.

**To Reproduce**

I forked your more recent example (https://github.com/react-hook-form/react-hook-form/commit/c37814cc0a233d8c28fddecf8f3df2dc55d30ec9) and just console logged the formState.dirtyFields  here => 
https://codesandbox.io/s/react-hook-form-v6-customise-controller-return-value-forked-lhugp?file=/src/index.js

Change for chocolate , see the console , {} empty result, change for vanilla, now you see the field is dirty as expected.

Thank you for your help

**Comment by bluebill1049** [comment]
<img width="1293" alt="Screen Shot 2020-11-10 at 9 10 22 am" src="https://user-images.githubusercontent.com/10513364/98602431-929d8380-2334-11eb-90af-3c484c14264e.png">

<img width="978" alt="Screen Shot 2020-11-10 at 9 10 43 am" src="https://user-images.githubusercontent.com/10513364/98602474-9f21dc00-2334-11eb-9f9b-4c847baee157.png">

make sure to read the formState before render.

https://codesandbox.io/s/react-hook-form-v6-customise-controller-return-value-forked-2ywe5
