### ISSUE TITLE
insert method of useFieldArray does not behave as expected

### ISSUE THREAD

**Issue by LoicHa** [react-hook-form/react-hook-form#3403]
Linked issue : https://github.com/react-hook-form/react-hook-form/issues/1702

I reopened this ticket since i can't find a solution . I updated the given codesandbox example with the latest version ("react-hook-form": "^6.11.0")
I also use getValues as you mentionned

here is the new code example : https://codesandbox.io/s/react-hook-form-usefieldarray-forked-clb1e?file=/src/index.js

When i click on clone , the console log me the good cloned name , but the result is different , the cloned name is always is wrong.

Sorry for this issue , i am maybe blind and don't see any evident thing wrong in my code

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-wy1ou

https://react-hook-form.com/api#useFieldArray

i have read on the following section: you are missing the `id`

<img width="998" alt="Screen Shot 2020-11-10 at 10 32 30 am" src="https://user-images.githubusercontent.com/10513364/98608779-0c873a00-2340-11eb-94fa-040065dc56e3.png">
