### ISSUE TITLE
watch values undefined when using defaultValue in Controller

### ISSUE THREAD

**Issue by tafelito** [react-hook-form/react-hook-form#3405]
In the docs it says 

> When defaultValue is not defined, the first render of watch will return undefined because it is called before register, but you can set the defaultValue as the second argument.

I'm setting a defaultValue to a Controller but using watch still returns undefined in the first render. Is that correct? 

here's the sandbox

https://codesandbox.io/s/react-hook-form-controller-template-forked-2vj08?file=/src/index.js

**Comment by bluebill1049** [comment]
hey @tafelito, `defaultValues` at `useForm` or at watch :)

<img width="890" alt="Screen Shot 2020-11-10 at 8 57 16 am" src="https://user-images.githubusercontent.com/10513364/98601143-bcee4180-2332-11eb-962b-b29cb941abe0.png">

**Comment by tafelito** [comment]
ok thanks, that statement confused me for a sec. Is there any way to get the watch to re-compute after setting the defaultValue to a Controller or any regular input?

**Comment by bluebill1049** [comment]
would you like to improve it and send a PR? if you provide a defaultValues at useForm, it should be fine right?

**Comment by tafelito** [comment]
Maybe I would just add that setting the defaultValue in the Controller won't make the watch return the value, it will still return undefined. 

Sometimes is not posible to set the defaultValues at the useForm level and you have to set it at the Controller or input level. I understand that this happens at different times but what I was expecting, and that's why my confusion, that no matter where you set the defaultValues, you always get the value in the  first render using `watch` or `useWatch`

**Comment by bluebill1049** [comment]
> Maybe I would just add that setting the defaultValue in the Controller won't make the watch return the value, it will still return undefined.
> 
> Sometimes is not posible to set the defaultValues at the useForm level and you have to set it at the Controller or input level. I understand that this happens at different times but what I was expecting, and that's why my confusion, that no matter where you set the defaultValues, you always get the value in the first render using `watch` or `useWatch`

good point, it's actually the render order. watch is always ahead of render hence the result starts with undefined unless you have defined in useForm's defaultValues. 

maybe i should add those in the doc, what do you think?

**Comment by tafelito** [comment]
I think It won't hurt adding it to the docs and it will make it clearer for other people like me 😁

thanks!

**Comment by bluebill1049** [comment]
Will do.

**Comment by bluebill1049** [comment]
it's in the doc :)

<img width="929" alt="Screen Shot 2020-11-12 at 11 26 20 am" src="https://user-images.githubusercontent.com/10513364/98879531-e5647000-24d9-11eb-9fbc-67b24a7bcbcd.png">

**Comment by tafelito** [comment]
awesome! thank you!

**Comment by madhubabu-sureify** [comment]
@bluebill1049   
const disableContinue = () => {
    if (!watch('firstName','').trim() || !watch('lastName','').trim()) return true;
    if (!watch('nameChangeReason','')) return true;
    if (watch('nameChangeReason') === 'Other') {
      if (!watch('nameChangeOtherReason','').trim()) return true;
    }
    return false;
  };

if i select other from dropdown, it is causing TypeError: Cannot read properties of undefined (reading 'trim') for nameChangeOtherReason. though i am sending default value as empty string.
it is working fine if i select other option first (before giving values to other fileds)
what is the reason behind it?

**Comment by mhinkley42** [comment]
I appreciate the docs being updated on the site. There was a point where I would like to use a `defaultValue` in a `useWatch`, but on the first render, the value is still `undefined`. However this is not the case for `getValues`, so my solution was this:
```
// someVar is rendered in the component it is defined in, but it does have a `defaultValue` set in the `useForm` call. 
  const someVar = useWatch({ control, name: 'someVar', defaultValue: getValues('someVar') })
```
Could I make a PR, such that a flag could be passed into `useWatch` such that it would use the `getValue` as the return if the watch would otherwise result in undefined?
