### ISSUE TITLE
Lodash throttle not working with handleSubmit

### ISSUE THREAD

**Issue by sp0033212000** [react-hook-form/react-hook-form#3408]
**Describe the bug**

I use lodash.throttle with handleSubmit, but not working.

**To Reproduce**

1. Go to [codeSandBox](https://codesandbox.io/s/mystifying-morse-h3zfr?file=/src/App.tsx)
2. Click on 'Submit With HandleSubmit' button quickly and continuously.
3. Click on 'Submit Without HandleSubmit' button quickly and continuously.

**Comment by bluebill1049** [comment]
This is not even a problem with this lib.

<img width="884" alt="Screen Shot 2020-11-10 at 1 30 36 pm" src="https://user-images.githubusercontent.com/10513364/98620191-ec17a980-2358-11eb-8202-0decd66c062f.png">

https://react-hook-form.com/api#handleSubmit
