### ISSUE TITLE
ForwardRef issue when using <Controller>

### ISSUE THREAD

**Issue by gor918** [react-hook-form/react-hook-form#3411]
**Describe the bug**
After updating to 6.11.0 I am facing an issue when I am using `<Controller>`

**To Reproduce**

1. Go to 'https://codesandbox.io/s/react-hook-form-controller-forked-drdv2?file=/package.json'
2. Click on 'open console'
4.  **Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?**

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-forked-drdv2?file=/package.json

**Screenshots**
<img width="896" alt="Screen Shot 2020-11-10 at 18 58 40" src="https://user-images.githubusercontent.com/11815472/98690918-eb960780-2386-11eb-9490-863ce4d7ebc7.png">
<img width="647" alt="Screen Shot 2020-11-10 at 18 58 48" src="https://user-images.githubusercontent.com/11815472/98690934-ef298e80-2386-11eb-8fed-56bc90892930.png">

**Comment by pke** [comment]
Wanted to report the same. This a a new one in the newest version of the lib. Older versions did not have this problem

**Comment by bluebill1049** [comment]
`Controller` now has `ref` prop for better focus management and accessibility. eg now React-Select works out the box with auto focus.

https://codesandbox.io/s/focused-sammet-tr193

```
<Controller
  control={control}
  name="test"
  render={({ onChange, onBlur, value, name, ref }) => (
    <TextField
      onBlur={onBlur}
      onChange={onChange}
      checked={value}
      inputRef={ref}
    />
  )}
/>
```

it's best to wire up the `ref` yourself, eg: TextField could be `inputRef` so we can focus that input when an error occurred, or you can omit that `ref` prop.

**Comment by tafelito** [comment]
@bluebill1049 this does not work when using the as prop of the Controller 

I updated your example, you can see the error there

https://codesandbox.io/s/wandering-wood-bcmm7?file=/src/App.tsx

**Comment by bluebill1049** [comment]
@tafelito it's working for react-select and the focus as well.

I guess we can discuss whether we should keep or remove `ref` from `as` prop, what my goal is every component wrapped with a controller can be focused with an error.

<img width="1081" alt="Screen Shot 2020-11-12 at 8 07 43 am" src="https://user-images.githubusercontent.com/10513364/98864533-26e72200-24be-11eb-8bed-e4aea851b870.png">

**Comment by tafelito** [comment]
I was pretty sure I saw the error for the example above but I don't see the error any more, weird. 
But yes, that works for `react-select` since `react-select` expects a `ref` prop but I have other components that don't have a `ref`, or use any other prop like `innerRef` or whatever. 
I see your point, and for those cases like `react-select` I think is fine to use the `as` prop, it's simple and no much else is needed there. 
For the rest of the components ideally you'd want to either use the `as` prop as it is now, where you get the `ref` as a prop, or adding a new prop to no pass the ref, like a `noRef`, so then using the `as` prop it won't pass the ref, or if you need more control, then use the render prop

Option 1 
```js
<Controller
    as={
    <ReactSelect
      options={[
        { value: "chocolate", label: "Chocolate" },
        { value: "strawberry", label: "Strawberry" },
        { value: "vanilla", label: "Vanilla" }
      ]}
    />
  }
  name="ReactSelect"
  control={control}
  defaultValue={null}
  rules={{
    required: true
  }}
/>
```

Option 2 
```js
<Controller
    as={
    <MyComponent
      {...compProps}
    />
  }
  noRef={true}
  name="MyComp"
  control={control}
  defaultValue={null}
  rules={{
    required: true
  }}
/>
```

Option 3 
```js
<Controller
  render={(props) => (
    <ReactSelect
      options={[
        { value: "chocolate", label: "Chocolate" },
        { value: "strawberry", label: "Strawberry" },
        { value: "vanilla", label: "Vanilla" }
      ]}
      {...props}
    />
  )}
  name="ReactSelect"
  control={control}
  defaultValue={null}
  rules={{
    required: true
  }}
/>
```

What do you think?

**Comment by bluebill1049** [comment]
Thanks, @tafelito I think I get the issue and see the concern as well, maybe we should remove `ref` from `as`, and it's only exposed for `render` prop. So those warnings can go away, and if users really cares about (as they should) use render prop.

**Comment by tafelito** [comment]
to be honest, without that error I would have not realized that on some of my fields when I have an error, there are not getting focused. So i guess is not a bad idea after all. I know the error is from react, but maybe showing a warning explaining the error would help understand why is needed?

**Comment by bluebill1049** [comment]
The PR is merged with warning @tafelito https://github.com/react-hook-form/react-hook-form/commit/f161c0c62075d518bbd16d89e0b7a5764c144bf8 will be in the next patch.

**Comment by bluebill1049** [comment]
Going to close this issue but keep an eye on this after the next patch release.

**Comment by clodal** [comment]
Using Material-UI TextField here. This is an issue when using `Controller` with `as` prop (Note: `render` prop works fine). Getting console.errors from React i.e. `Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`. As we want to avoid using `render` as it's too verbose and prefer `as`our workaround for now is to forward the ref into the component. CSB example: https://codesandbox.io/s/cool-lovelace-y3o0q?file=/src/App.tsx:455-714. 

`RHF version: 6.12.1`
`MUI/core version: 4.9.12`

**Comment by bluebill1049** [comment]
> Using Material-UI TextField here. This is an issue when using `Controller` with `as` prop (Note: `render` prop works fine). Getting console.errors from React i.e. `Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`. We want to avoid using `render` as it's too verbose so we prefer the `as` prop. Our workaround for now is to forward the ref into the component. CSB example: https://codesandbox.io/s/cool-lovelace-y3o0q?file=/src/App.tsx:455-714.
> 
> `RHF version: 6.12.1`
> `MUI/core version: 4.9.12`

if you want to focus on an error to work correctly, then you probably want to hook up the ref prop, in MUI, it's probably renamed to something as `inputRef`.

<img width="965" alt="Screen Shot 2020-11-30 at 9 55 10 am" src="https://user-images.githubusercontent.com/10513364/100555808-23db9680-32f2-11eb-9803-8cdcf297ec34.png">

there is the CSB in the doc: https://codesandbox.io/s/react-hook-form-focus-74ecu

**Comment by clodal** [comment]
Thanks @bluebill1049 , what if user wants to customise the TextField and still use the `as` prop? This used to work before. In this case, there will be console.error about ref forwarding required. See: https://codesandbox.io/s/react-hook-form-focus-forked-r86w5

**Comment by lauralouiset** [comment]
Btw, still running into this on version 6.12.2. can't use `as` with a custom (non-library) select menu, had to use the render prop.

**Comment by bluebill1049** [comment]
I think `ref` at `as` is creating more issues than it should, (i was hoping it will make focus management better for everyone). I will remove `ref` injection from `as`, also worth noting that `as` will most likely be deprecated in the next major version, but i will be next year.

**Comment by jpodpro** [comment]
i too just noticed this error after recently upgrading to 6.13.1. however if `as` is being deprecated then it's hardly worth continuing to use it.

**Comment by bemulima** [comment]
Also I have a similar error: I used this code and it worked for me:

`const BFormDropDownList = React.forwardRef(({ errors, input, register }, ref) => {
    return (<Form.Group>
        {input.label && <Form.Label>{input.label}</Form.Label>}
        <DropDownList
            input={{
                name: input.name,
                ref: ref
            }}
            list={input.list}
        />
        <ErrorMessage errors={errors} name={input.name}>
            {({ message }) => <div className='has-error'>{message}</div>}
        </ErrorMessage>
        {input.hint !== undefined ? <Form.Text className="text-muted">{input.hint}</Form.Text> : ''}
    </Form.Group>)
});
`
And I called like this:
`<BFormDropDownList errors={errors} input={fields.sex.input} ref={register({...fields.sex.register})}/>`

But after update to 6.13.1 I see error massage:
`React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ForwardRef`.`

**Comment by joelharkes** [comment]
what is currently the preferred solution?  i took @bluebill1049 solution for hooked components but it seems not ideal?

**Comment by hazarartuner** [comment]
I use Controller with the `carbon-components-react` package's `Dropdown` component. But there is a problem on rendering with initial state. If I use `as` prop, Dropdown component is rendering correctly with its initial value, if I use render prop, it is not. To make render prop work correctly for initial value, I have to do some workaround like setting random value to some state variable. By this way I can re-render the component and even this is not always work. On the other hand,  the issue with the `as` prop is that gives ref error. My question is, what is the difference between `as` and `render` props which causes this rendering issue? How can I fix it?

**Comment by good3n** [comment]
> `Controller` now has `ref` prop for better focus management and accessibility. eg now React-Select works out the box with auto focus.
> 
> https://codesandbox.io/s/focused-sammet-tr193
> 
> ```ts
> <Controller
>   control={control}
>   name="test"
>   render={({ onChange, onBlur, value, name, ref }) => (
>     <TextField
>       onBlur={onBlur}
>       onChange={onChange}
>       checked={value}
>       inputRef={ref}
>     />
>   )}
> />
> ```
> 
> it's best to wire up the `ref` yourself, eg: TextField could be `inputRef` so we can focus that input when an error occurred, or you can omit that `ref` prop.

I'm a bit confused by your example. `name` is never used/read. And you're using ref but where are you passing options to it? Like register?

**Comment by Smichaelidis** [comment]
Hi, there is no way to focus the next input with onSubmitEditing and ref in Controller ? 
I try to do something like this : 

<Controller
  control={control}
  name="test"
  render={({ onChange, onBlur, value, name, ref }) => (
    <TextField
      onBlur={onBlur}
      onChange={onChange}
      checked={value}
      inputRef={ref}
onSubmitEditing={() => setFocus('test2')
    />

<Controller
  control={control}
  name="test2"
  render={({ onChange, onBlur, value, name, ref }) => (
    <TextField
      onBlur={onBlur}
      onChange={onChange}
      checked={value}
      inputRef={ref}
onSubmitEditing={() => setFocus()

    />
  )}
/>

thanks for your help.

**Comment by val-o** [comment]
I was having the same issue and couldn't find out what I am doing wrong. Turns out that I missed `control` prop!  😄  @bluebill1049  Can we make it required in types or maybe add some descriptive error message in runtime?)

**Comment by raphaelsoul** [comment]
now (react-hook-form v7.30.0) controller passes no 'ref' props to render function

<img width="739" alt="image" src="https://user-images.githubusercontent.com/8615787/172557560-85d16844-6f07-49a3-b4e9-ee069d0eb10f.png">

**Comment by aimanjaffer** [comment]
> now (react-hook-form v7.30.0) controller passes no 'ref' props to render function
> 
> <img alt="image" width="739" src="https://user-images.githubusercontent.com/8615787/172557560-85d16844-6f07-49a3-b4e9-ee069d0eb10f.png">

ref is a part of field i.e. `field.ref`, it's available when you destructure the field object.

**Comment by gainskills** [comment]
> carbon-components-react

Hi @hazarartuner , does it work for you now? thanks,
