### ISSUE TITLE
mix yupResolver with RHF rules

### ISSUE THREAD

**Issue by tafelito** [react-hook-form/react-hook-form#3412]
**Describe the bug**
I have a form that has 2 parts, 1 is static and 1 is dynamic. The static part I'm using a yup schema to do the validation, and for the dynamic part, I'm either setting the rules within the register or in the rules prop of the Controller component.  
I'm pretty sure this was working before but now it seems it does not work anymore

**To Reproduce**

1. Go to the sandbox and click on submit
2. It only gives an error when the name input has no value 

**Codesandbox link (Required)**
https://codesandbox.io/s/provider-perf-forked-y94dv?file=/src/App.js

**Expected behavior**
I know I could do my validation as part of the resolver and call the yupResolver there, but I want to leverage RHF for the dynamic validations since the ones built-in are enough for my use case

**Comment by bluebill1049** [comment]
you can't mix up with build-in and resolver, i will update the doc to emphasis that.

**Comment by bluebill1049** [comment]
<img width="888" alt="Screen Shot 2020-11-11 at 6 57 24 pm" src="https://user-images.githubusercontent.com/10513364/98784805-c3bea680-244f-11eb-909a-9e36030a9940.png">

**Comment by tafelito** [comment]
Is there any particular reason why this can't be supported? How hard could that be to implement if it's even possible?

**Comment by bluebill1049** [comment]
> Is there any particular reason why this can't be supported? How hard could that be to implement if it's even possible?

it's better to stick with a single source of truth for validation, it will make the codebase much more complex and potentially introduce more issues in the long run.

**Comment by tafelito** [comment]
ok makes sense. I was able to create a dynamic schema using concat from yup, it's a bit more work but it won't be an issue.  

anyway thanks for the clarification!
