### ISSUE TITLE
Form state always false with controller and select component and Yup

### ISSUE THREAD

**Issue by DirkWolthuis** [react-hook-form/react-hook-form#3421]
**Describe the bug**
The form state isValid keeps returning false even if all required fields are filled. If the first field (input / text) revalidates on the onBlur event than the state does changes. 

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-controller-state-always-false-w89yu?file=/src/index.js
2. Fill something in the text input
3. Select item 2 in the dropdown
4. Blur the select box.
4. check the console and see the log that says the form is not valid

**Expected behavior**
The onblur event of the select revaluates the form and sets isValid to true

**Comment by bluebill1049** [comment]
<img width="526" alt="Screen Shot 2020-11-12 at 8 52 48 am" src="https://user-images.githubusercontent.com/10513364/98868565-716b9d00-24c4-11eb-8e47-3fc53190074c.png">
your schema is not matching with fields that registered.
<img width="575" alt="Screen Shot 2020-11-12 at 8 53 07 am" src="https://user-images.githubusercontent.com/10513364/98868588-7d575f00-24c4-11eb-8167-dc456ff2f3da.png">
