### ISSUE TITLE
'get' method from 'react-hook-form' 

### ISSUE THREAD

**Issue by azenkovets** [react-hook-form/react-hook-form#3422]
Hi there.

There is a very helpful method called 'get' which can be imported from 'react-hook-form' package.
I see that you use it in your 'ErrorMessage' component - https://github.com/react-hook-form/error-message/blob/807c639794093f725e4331ae2545e0428febfeae/src/ErrorMessage.tsx#L21

It looks like you use it for a 'Deep search' in the 'errors' object.

I was not able to find any info about it in docs. 
But i found it by chance and it saved my day.

Probably, it will be great to add any info about it somewhere in docs or on the GitHub page.

P.S. Love 'react-hook-form' a lot. Great project!

**Comment by bluebill1049** [comment]
hey @azenkovets thanks for the suggestion and kind words. I would recommend using lodash/get instead hookform's as it will help with more edge cases, hook form's get is purely focus on our usage. 🙏
