### ISSUE TITLE
useFieldArray auto clear errors.

### ISSUE THREAD

**Issue by nghiepit** [react-hook-form/react-hook-form#3424]
**Describe the bug**
When changing the input field value, all errors will be clear empty. 

**To Reproduce**

1. Click submit
2. Enter name input
3. See error: "Error message of age input will be removed"

**Codesandbox link (Required)**
https://codesandbox.io/s/festive-dirac-61pwl?file=/src/App.tsx:92-105

![ezgif com-gif-maker](https://user-images.githubusercontent.com/4768095/98839751-83bfe980-2478-11eb-8c70-4dc73ad5a5ed.gif)

**Expected behavior**
Keep other errors

**Additional context**
Maybe the problem with `yupResolver`

**Comment by bluebill1049** [comment]
This is expected for default mode: 'onSubmt', have a read at the useForm section for more detail.

**Comment by nghiepit** [comment]
Does the behavior change from the `react-hook-form@6.10.0` version?

But why if I don't use schema validation, it works the same as the `6.9.3` version.

Example: https://codesandbox.io/s/romantic-stallman-xm6dj?file=/src/UserForm.tsx:331-380

**Comment by bluebill1049** [comment]
The current behavior is correct.

hit submit show errors and then follow with onChange to reValidate. 
<img width="992" alt="Screen Shot 2020-11-12 at 1 30 05 pm" src="https://user-images.githubusercontent.com/10513364/98888025-2dd85980-24eb-11eb-933f-65fe556538ba.png">
