### ISSUE TITLE
Errors dont follow reValidate policy from useForm when using `trigger()`

### ISSUE THREAD

**Issue by grantglidewell** [react-hook-form/react-hook-form#3425]
**Describe the bug**
When programmatically validating using the `trigger` method, errors persist after the values in fields have changed.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-useform-template-forked-tbvzt
2. Click on VALIDATE
3. enter data into last name field
4. See error persist

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-useform-template-forked-tbvzt

**Expected behavior**
Errors should clear according to the `useForm` reValidate policy

**Comment by grantglidewell** [comment]
My current workaround if others are finding this issue is as follows.

```js
const valid = await trigger();
if(valid) {
    // move forward in form process
} else {
    handleSumbit() // this will fail and trigger the same errors, but with the expected clearing behavior
}
```

**Comment by bluebill1049** [comment]
trigger() is action for one event, if you need to trigger validation on each event, then attach to the `onChange`.

**Comment by grantglidewell** [comment]
Im not sure what you mean.
In the example Im attaching `trigger` to a button because the result of that would be used to make decisions about the next step in the form before submitting. This would involve a confirmation dialog. 

If I were to do this onChange it kind of defeats the purpose of the flow. This really strikes me as a divergent behavior from the way validation works on submission. 

Should I not expect the form validation to behave the same way?

**Comment by grantglidewell** [comment]
@bluebill1049 ☝️

**Comment by bluebill1049** [comment]
@grantglidewell trigger only invokes once to test what's in the current form, it doesn't follow up with the validation `mode`, i think that's what you confused with.

**Comment by bluebill1049** [comment]
<img width="684" alt="Screen Shot 2020-11-12 at 10 48 57 am" src="https://user-images.githubusercontent.com/10513364/98877467-ac75cc80-24d4-11eb-91d6-03afa10a88ec.png">
trigger pressed

<img width="709" alt="Screen Shot 2020-11-12 at 10 49 10 am" src="https://user-images.githubusercontent.com/10513364/98877485-b39cda80-24d4-11eb-847c-8cf8d40d0b70.png">
error remain

<img width="667" alt="Screen Shot 2020-11-12 at 10 49 23 am" src="https://user-images.githubusercontent.com/10513364/98877497-bb5c7f00-24d4-11eb-857e-e6654f5c7a92.png">

trigger again the error goes away.

**Comment by grantglidewell** [comment]
ok, so the workaround to get the behavior I want is really the only option. Would you accept a PR if I could get `trigger` to align with the behavior set with the `reValidate` policy in `useForm`?

**Comment by grantglidewell** [comment]
@bluebill1049 Im hesitant to add trigger to onchange for every field as its not necessary when errors are triggered using the submit button.

**Comment by bluebill1049** [comment]
> ok, so the workaround to get the behavior I want is really the only option. Would you accept a PR if I could get `trigger` to align with the behavior set with the `reValidate` policy in `useForm`?

The correct way to trigger the "mode" validation is to use `handleSubmit()()`, `trigger` is doing the right thing here and expected behavior. eg `trigger('test')` will only trigger that single input for an error or not.

**Comment by bluebill1049** [comment]
have a look at this CSB: https://codesandbox.io/s/react-hook-form-useform-template-forked-nfv52

**Comment by grantglidewell** [comment]
the problem here is that I dont want to submit the form @bluebill1049 , does the curried operation of handleSubmit stop it from submitting? it seems to submit in the example you sent me

**Comment by bluebill1049** [comment]
I am not sure about your app behavior, if you don't want to submit the form, perhaps you want to switch the mode to 'onChange' then trigger will trigger validation and re validating the input will happen onChange.

**Comment by bluebill1049** [comment]
going to close this issue, as it's expected behavior, feel free to follow up with the question if your problem still not resolved.
