### ISSUE TITLE
Typing issue: setValue fails to error for invalid field names

### ISSUE THREAD

**Issue by distinctdan** [react-hook-form/react-hook-form#3428]
**Describe the bug**
If you call `setValue` with an invalid field name, the typescript compiler fails to throw an error.

**To Reproduce**
1. Call setValue with a nonexistent field name, like `setValue('fjdsafafsaf', 'abc');`
2. Fail to see error

**Codesandbox link (Required)**
This is the `setValue` example forked from the docs. On line 30, I've changed `setValue("firstName", "Grace")` to `setValue("firstName_fdsafdsa", "Grace")`, so it should be erroring. In fact, I'm not getting errors either if I change an input name to something invalid.
https://codesandbox.io/s/react-hook-form-v6-ts-setvalue-forked-0yh7q?file=/src/index.tsx:811-829

**Expected behavior**
It should throw a compile error.

**Screenshots**

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Chrome
- Version: react-hook-form 6.11.0

**Additional context**
I see there was a recent issue with typing here https://github.com/react-hook-form/react-hook-form/issues/3363, not sure if it addressed this issue.

**Comment by distinctdan** [comment]
Thanks for looking into it so fast!

**Comment by bluebill1049** [comment]
thanks for the issue report @distinctdan 👍
