### ISSUE TITLE
React Hook Form doesnt work on React Native when using validationSchema.

### ISSUE THREAD

**Issue by galihlprakoso** [react-hook-form/react-hook-form#343]
**Description of the bug**
The React Hook form doesnt work when i use validation schema on React Native. It Shows a warning :
`Possible Undhandled Promise Rejection (id: 3):
TypeError: undefined is not an object (evaluating 'error.inner.length')
`

and the validation doesnt work.

**To Reproduce**
1. Implement the react native example in the : https://react-hook-form.com/api/#ReactNative
2. Then implement the validationSchema as in the documentation using yup.

**Expected behavior**
It can validate the input as defined in the schema and shows error on the errors object.

**Screenshots**
<img width="383" alt="Screen Shot 2019-10-02 at 5 41 43 PM" src="https://user-images.githubusercontent.com/16918033/66038355-1a16a180-e53c-11e9-88f1-b1b8d4d9f350.png">

**Smartphone:**
 - Device: [iPhone X]
 - OS: [iOS]
 - Version [12.1]

**Comment by bluebill1049** [comment]
can you share the code?

**Comment by galihlprakoso** [comment]
**ValidationSchemas.js**
`
import * as yup from 'yup';
import { alphanumeric } from './Regex';

const AccountSettingSchema = yup.object().shape({
  username: yup.string().min(6).max(24).matches(alphanumeric).required(),
  facebook: yup.string().url().required(),
  instagram: yup.string().url().required(),
  youtube: yup.string().url().required(),
  twitter: yup.string().url().required()
})

export {
  AccountSettingSchema
}

`
**index.js**
`
import useForm from 'react-hook-form';
import { AccountSettingSchema } from './ValidationSchemas';

export default () => {
  const { register, setValue, handleSubmit, errors } = useForm({
    validationSchema: AccountSettingSchema
  });
  const onSubmit = data => alert(JSON.stringify(data));
  return (
    <ScrollView style={styles.container}>
      <KeyboardAvoidingView>
        <Text style={styles.title}>User</Text>
        <RootTextInput
          ref={register({ name: 'username' })}
          onChangeText={text => setValue('username', text, true)}
          label="USERNAME" 
          error={errors.username && 'username is required'}
        />

        <Text style={styles.title}>Social Media</Text>
        <RootTextInput label="FACEBOOK" />
        <RootTextInput label="INSTAGRAM" />
        <RootTextInput label="YOUTUBE" />
        <RootTextInput label="TWITTER" />

        <RootButton text="SAVE" onPress={handleSubmit(onSubmit)} />
      </KeyboardAvoidingView>
    </ScrollView>
  );
};
`

**Comment by bluebill1049** [comment]
thanks i will take a look at this 👍

**Comment by galihlprakoso** [comment]
thanks my bro. your lib is awesome btw! love it!

**Comment by bluebill1049** [comment]
no worries buddy 👍 so glad to hear that

**Comment by bluebill1049** [comment]
```
import React from 'react';
import { StyleSheet, Text, View, TextInput, Button } from 'react-native';
import useForm from 'react-hook-form';
import * as yup from 'yup';

const AccountSettingSchema = yup.object().shape({
  username: yup.string().min(6).max(24).required(),
  facebook: yup.string().url().required(),
  instagram: yup.string().url().required(),
  youtube: yup.string().url().required(),
  twitter: yup.string().url().required()
})

export default function App() {
  const { register, setValue, handleSubmit, errors } = useForm({
    validationSchema: AccountSettingSchema
  });

  const onSubmit = (data) => console.log(data);

  console.log(errors);

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <TextInput
        ref={register({ name: 'username' })}
        style={{ height: 40, borderColor: 'gray', borderWidth: 1 }}
        onChangeText={text => setValue('username', text, true)}
      />
      <Button title="SAVE" onPress={handleSubmit(onSubmit)} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```
tested and works for me, try to remove alphanumeric and see if work with your example

**Comment by galihlprakoso** [comment]
okay thankss

**Comment by galihlprakoso** [comment]
mmm.. it works.. but i need to validate with regex.. how to do it? @bluebill1049

**Comment by bluebill1049** [comment]
can you post this question in `Yup`?

**Comment by bluebill1049** [comment]
i did a quick googling for you, hope this helps :) https://stackoverflow.com/questions/52483260/validate-phone-number-with-yup

going to close this for now, feel free to ask more question or re-open 👍
