### ISSUE TITLE
custom React-input-mask with controller is not updating touched state

### ISSUE THREAD

**Issue by sakwok** [react-hook-form/react-hook-form#3433]
**Describe the bug**

I was following this [example](https://github.com/react-hook-form/react-hook-form/blob/master/examples/customMaskedInputWithController.tsx) with react-hook-form (v 6.11.0) and came across a problem with form state properly updating with masked value, but its touched state was not being updated.

Note*
When copying the [example](https://github.com/react-hook-form/react-hook-form/blob/master/examples/customMaskedInputWithController.tsx), I updated the code to forwardRefs down to my desired input because I also came across the issue in ss below.
<img width="1272" alt="Screen Shot 2020-11-11 at 10 44 17 PM" src="https://user-images.githubusercontent.com/4992352/98906660-5a9c5a80-2472-11eb-86f5-38c1edbc53a5.png">

**To Reproduce**

 - Type into the input, 
 - Click submit,
 - Look at console, you will see state printed out, but touched object being empty.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-forked-yc377?file=/package.json

- [useForm](https://codesandbox.io/s/react-hook-form-useform-template-lsm61) Template
- [useFieldArray](https://codesandbox.io/s/react-hook-form-usefieldarray-template-q0jek) Template
- [Controller](https://codesandbox.io/s/react-hook-form-controller-template-yu0z5) Template

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

OS: macOS 10.15.7
Browser: Chrome
Version: 86

**Comment by bluebill1049** [comment]
you are missing:

```
      onBlur={e => {
        onBlur(e.target.value)
      }}
```

**Comment by sakwok** [comment]
Awesome thank you!
