### ISSUE TITLE
coerse data type

### ISSUE THREAD

**Issue by voxspox** [react-hook-form/react-hook-form#3436]
**Is your feature request related to a problem? Please describe.**

I want to suggest an improvement to [Example for transform and parse](https://react-hook-form.com/advanced-usage#TransformandParse). Here the value is reseted to 0 as far as some invalid characters are entered. My idea is to keep the value as a string as long as it is invalid. If the value becomes valid it is tranformed to the final type. If it gets further editited and becomes invalid again the value is kept as string again.

```
<ControllerPlus
  transform={{
    input: (value) => value?.toString() ?? '',
    output: (e) => {
      if (typeof input !== 'string') return input                                                   
      const x = Number.parseInt(input, 10)                                                          
      return Number.isFinite(x) ? x : input                                                         
    }
  }}
...

<Controller
  ...
  rules={{
    validate: (value) => Number.isFinite(value) || 'Please enter a number.'
  }}
```

**Comment by bluebill1049** [comment]
That was just an example for users to follow and improve, but happy to enhance it to fix the problem.

Do you have a working version or do you want me to investigate a solution? Empty input will always be `string` and the rest of them can be number, but potentially we can save 0 into the store tho.

**Comment by voxspox** [comment]
My initial issue was that I want to have only valid data types in `values` of the form. The code above is only a workaround. To accomplish this I think we need two values per field:

1. an edit value which is a string and displayed in the input component. It is exact what the user has entered, p.ex. "+100", thus no modifications p.ex. via convert to type then convert back to string, are done.
2. a 'valid' value with correct data type which is saved to `values` of the form. The validation functions should have passed befor this and we need a value for invalid p.ex. `null`. For example I use `null` for radio buttons if none of these is selected.

I don't know the internal data structures of RHF. Maybe it would be easy to do it.

To your question: I have no separate solution. I extracted the code above from my working code.

**Comment by bluebill1049** [comment]
@voxspox I think it's two-pieces of data: 

- what user see (string)
- what you want to save into store (any that you transformed) 

do I miss anything else?

**Comment by voxspox** [comment]
@bluebill1049  no

**Comment by bluebill1049** [comment]
I think there is going to be a problem with this approach tho because you will have two sources of truth. If that's really the desired behavior then probably much easier to have an input set a "text", and store the user input into a hidden input as a number. perhaps to consider use this when `register` new API proposal is gets passed: https://twitter.com/HookForm/status/1330261464792371200 I will close this issue as there is no perfect solution for this, have two sources of truth is not really an ideal solution for all use case and it really depends on your app usage or UX design.
