### ISSUE TITLE
a field is cleared from dirtyFields in spite of shouldUnregister=false

### ISSUE THREAD

**Issue by voxspox** [react-hook-form/react-hook-form#3437]
**Describe the bug**

My form is based on accordion tabs. The input fields are inside the accordion tabs. Thus closing a tab leads to an unregistration of the fields. Next, I set `shouldUnregister` to `false`. This keeps the form values (`getValues()`) in an expected state.

In `dirtyValues` an entry exists after opening the tab and editing the field. After closing the tab the `dirtyValue` is still there, as expected. But after re-opening the tab, and thus re-registration of the field, the `dirtyValue` is gone.

**To Reproduce**

1. set `shouldUnregister` to `false`
2. register component
3. edit -> `dirtyValue` is set
4. unregister component -> `dirtyValue` still there 
5. re-register component
6. `dirtyValue` is gone

**Codesandbox link (Required)**
Sincerely apologize, I hope the description is clear enough to retrace the issue directly in the code. 

**Expected behavior**
`dirtyValue` should not vanish

**Smartphone (please complete the following information):**

using react-native 0.63

**Comment by bluebill1049** [comment]
please provide a CSB.

**Comment by bluebill1049** [comment]
let's discuss the issue here: https://github.com/react-hook-form/react-hook-form/issues/3437

**Comment by voxspox** [comment]
@bluebill1049 Please edit the related issue :)
