### ISSUE TITLE
If a field is disabled, his value doesn't appear in the handleSubmit

### ISSUE THREAD

**Issue by Trireir** [react-hook-form/react-hook-form#3438]
**Describe the bug**
If an input field is disabled, his value appears in the _watch_ and _getValues_ function, but it's undefined in the _handleSubmit_. Check the console in the codesandbox link.

**To Reproduce**

1. Go to the codesandbox link.
2. Click in the submit button.
3. Check the console. The Watch line have values for both inputs, but the onSubmit only for the first one

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-forked-fpquo?file=/src/index.js

**Expected behavior**
The onSubmit values have both inputs filled

**Screenshots**
![image](https://user-images.githubusercontent.com/5498514/98985740-49138b00-2524-11eb-9487-23ed2928e703.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome
- Version 86.0.4240.183

**Comment by bluebill1049** [comment]
we followed the standard, have a quick read here: https://stackoverflow.com/questions/1355728/values-of-disabled-inputs-will-not-be-submitted

**Comment by ebonow** [comment]
Thank you for the explanation. I recently updated from v3 to v6 and found that my disabled inputs suddenly were failing validation with the error type being required even thought they had values. This explains the behavior.

**Comment by bluebill1049** [comment]
> Thank you for the explanation. I recently updated from v3 to v6 and found that my disabled inputs suddenly were failing validation with the error type being required even thought they had values. This explains the behavior.

Thanks for understanding, one of the philosophies with react hook form is we try to align as close as possible with the native form and embrace the browser behavior, so if one day this library dies, some of the knowledge you learned can port into your next lib/framework.
