### ISSUE TITLE
submitFocusError does not work when using yup Validation Schema.

### ISSUE THREAD

**Issue by Dinhh1** [react-hook-form/react-hook-form#344]
**Bug Description**
When using yup schema validation, the submitFocusError does not focus the first error.

**To Reproduce**
1. configure a yup schema
2. use schema in useForm
3. Try to submit
4. It does not focus error

Here's two example code sandbox taken from the sample github page.
[Example without using validation schema](https://codesandbox.io/s/w7p3km6nyw)
[Example using validation schema and it does not autofocus](https://codesandbox.io/s/928po918qr)

**Expected behavior**
It should auto focus first Error, similar to when not using a validation schema.

**Comment by bluebill1049** [comment]
This is should be resolved by this beta: react-hook-form@3.23.18-beta.1

**Comment by Dinhh1** [comment]
That was quick! Thanks a lot.
