### ISSUE TITLE
Please add some unit test examples. 

### ISSUE THREAD

**Issue by antonpegov** [react-hook-form/react-hook-form#3446]
**Is your feature request related to a problem? Please describe.**
Can't find the way to test it with create-react-app and material-ui.

**Describe the solution you'd like**
I expect to see test examples

**Comment by bluebill1049** [comment]
you can have a look at our lib test file: 

https://github.com/react-hook-form/react-hook-form/blob/master/src/controller.test.tsx

hope that's useful.
