### ISSUE TITLE
Watch + formState dirty

### ISSUE THREAD

**Issue by opeah** [react-hook-form/react-hook-form#345]
I have an issue when I use watch + formState.
As you can see on the screenshot, I have 2 fields with values but dirty is false.

When I update 'assignee' or 'status' field that are not controlled by 'watch', dirty goes to true.

Keep up the good job!

![Screenshot 2019-10-03 at 19 39 54](https://user-images.githubusercontent.com/31569566/66150500-9c26c900-e615-11e9-9a0c-e19936ae07c4.png)

<img width="567" alt="Screenshot 2019-10-03 at 19 41 03" src="https://user-images.githubusercontent.com/31569566/66150580-ca0c0d80-e615-11e9-8472-d054be45377c.png">

**Comment by bluebill1049** [comment]
thanks @opeah 👍 any chance you can create a codesandbox for this issue?

**Comment by bluebill1049** [comment]
by the way, dirty is not controlled by the watch. it's the entire form.

**Comment by opeah** [comment]
@bluebill1049 of course https://codesandbox.io/s/cocky-bush-g87tx?fontsize=14

**Comment by opeah** [comment]
As you can see, when I change the first two fields that are controlled by 'watch', formState.dirty does not update. With the last field, it works.

**Comment by bluebill1049** [comment]
nah you are right, i will investigate on this issue :)

**Comment by bluebill1049** [comment]
patch on beta: react-hook-form@3.23.18-beta.2

let me know if that fixes your issue 👍

**Comment by opeah** [comment]
It works! thanks for the quick fix

**Comment by bluebill1049** [comment]
going to close this issue and release it in the next patch :)
