### ISSUE TITLE
The last thing added when appending is not in focus

### ISSUE THREAD

**Issue by yamakeeeeeeeeen** [react-hook-form/react-hook-form#3450]
**Describe the bug**

**To Reproduce**

1. Go to 'https://codesandbox.io/s/react-hook-form-usefieldarray-vy8fv'
2. Click on 'APPEND'
3. See the items in focus.

**Expected behavior**
The focus needs to be on the last item added.  
This sample is working fine.

But I don't know what the difference is.

https://codesandbox.io/s/react-hook-form-usefieldarray-focus-last-added-forked-7dury?file=/src/fieldArray.js

**Screenshots**

![image](https://user-images.githubusercontent.com/53547520/99150450-02669200-26d8-11eb-9897-576e153ac9c7.png)

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser [chrome]
- Version [ 86.0.4240.193（Official Build） （64bit）]

**Comment by bluebill1049** [comment]
thank you @yamakeeeeeeeeen 🙏
