### ISSUE TITLE
Different objects that are equal by value causing rerender

### ISSUE THREAD

**Issue by ogabrielsantos** [react-hook-form/react-hook-form#3451]
**Describe the bug**
Screen rerendering when `formState` object changed (not equal by reference) but its value not.

**To Reproduce**

1. Open Codesandbox
2. Click on LastName input
3. Type anything
4. Leave field
5. See console log

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-forked-rdtej

**Expected behavior**
When objects doesn't have real changes, rerender should not occour

**Screenshots**
![Captura de tela de 2020-11-14 14-01-10](https://user-images.githubusercontent.com/5789536/99152671-e0dabb80-2681-11eb-96ef-5803da55d9bc.png)

**Comment by bluebill1049** [comment]
<img width="552" alt="Screen Shot 2020-11-15 at 9 33 33 am" src="https://user-images.githubusercontent.com/10513364/99158327-a7f42280-2725-11eb-860c-dddb017e07b7.png">

if you console the `formState`, `dirtyFields` and touched has been updated.

**Comment by ogabrielsantos** [comment]
Oh, sorry. Looks like a [why-did-you-render](https://github.com/welldone-software/why-did-you-render/) false-positive because of proxied values.

**Comment by bluebill1049** [comment]
np 👍

**Comment by ogabrielsantos** [comment]
related https://github.com/react-hook-form/react-hook-form/issues/3455
