### ISSUE TITLE
onChangeName doenst work in 6+  version

### ISSUE THREAD

**Issue by thiagofernando** [react-hook-form/react-hook-form#3452]
**Describe the bug**
After updating Bill's example to the current version of RHF (version 6 or higher), the onChangeName parameter is no longer recognized

I cant get the floatValue from react number format like in 5.7.2 version

**To Reproduce**

just execute the CSB https://codesandbox.io/s/rhf-numberformat-mu-forked-sb6i0?file=/src/App.js

**Expected behavior**
just like the previosly version
https://codesandbox.io/s/rhf-numberformat-with-yup-b2sxl?from-embed=&file=/src/App.js

- OS: windows 10
- Browser firefox lastest

**Comment by bluebill1049** [comment]
have a look at the migration guide: https://react-hook-form.com/migrate-v5-to-v6
