### ISSUE TITLE
errors and formState.errors from the useForm hooks are mutated

### ISSUE THREAD

**Issue by vzaidman** [react-hook-form/react-hook-form#3455]
If you use `errors` or `formState.errors` from `useForm`, you receive a persistent error object that can be modified later.

It won't trigger useEffect in code like this, because both `errors` objects are always the same obejct:
```js
  React.useEffect(() => {
    console.log("errors", errors);
  }, [errors]);

  React.useEffect(() => {
    console.log("formState.errors", formState.errors);
  }, [formState.errors]);
```

But may also be buggy in cases where this object is used after the fact, not expecting it has been mutated.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-useform-template-forked-fmljf?file=/src/index.js

**To Reproduce**
1. open the console
2. click on the "last name" input
3. click outside the input
4. you will see that the component has been updated with the new error, but the `useEffect` hooks in the code were not triggered.

**Expected behavior**
I expected to have the error object to be able to work with it. For example, use it for analytics.
It should also be a unique, unmutable object because else I might send a mutated, later version of it.

**Screenshots**
![image](https://user-images.githubusercontent.com/5188459/99184435-6a09f500-274b-11eb-8aa7-6bd00238e85c.png)

**Desktop**

- OS: Windows 10
- Browser: Chrome 
- Version: 86

Related issues: #2893

**Comment by bluebill1049** [comment]
hello @vzaidman, thanks for the detailed investigation and report. This is actually by design because we are using `Proxy` to guard the form state, eg: if you are not reading `isDirty` or `isValid` state, then we can avoid that extra re-render and even those validations within the form. You can do the following to tracking down the `formState` change

```
React.useEffect(() => {
    console.log("formState.errors", formState.errors);
  }, [formState]);
```

**Comment by vzaidman** [comment]
> You can do the following to tracking down the `formState` change
> 
> ```tsx
> React.useEffect(() => {
>   console.log("formState.errors", formState.errors);
> }, [formState]);
> ```

But that would get you into `useEffect` for every state change. Not only errors change. Right?

**Comment by bluebill1049** [comment]
> > You can do the following to tracking down the `formState` change
> > ```tsx
> > React.useEffect(() => {
> >   console.log("formState.errors", formState.errors);
> > }, [formState]);
> > ```
> 
> But that would get you into `useEffect` for every state change. Not only errors change. Right?

yes, correct. we are batching `formState` update. everything inside `formState` will get a state update, instead of an individual piecestate.

**Comment by vzaidman** [comment]
also if you do something like:
```
React.useEffect(() => {
  setTimeout(() => {
    console.log("formState.errors", formState.errors);
  }, 1000);
}, [formState]);
```
you are not guaranteed to have the correct errors object.
so it would be a good idea to do the following:
```
React.useEffect(() => {
  const currentErrors = {...formState.errors}
  setTimeout(() => {
    console.log("currentErrors", currentErrors);
  }, 1000);
}, [formState]);
```

**Comment by bluebill1049** [comment]
You are right. That's correct @vzaidman what you had above.

**Comment by bluebill1049** [comment]
In fact, I will update the doc to include more detail on what we discussed above. Thank for your input @vzaidman.

**Comment by vzaidman** [comment]
Thank you!
Do you think it's possible to keep the error object changing? even without triggering a re-render.

**Comment by bluebill1049** [comment]
Yes, I did consider having a `useFormState` hook, which would prevent errors trigger re-render, unless the hook is invoked at the component level. This is probably something that will come in the future, I do pay extra attention to the library bundle size as well, so I am quite cautious about introducing new features or functionality. Right now, the lib is 9KB, I would love to stay at 8KB and try to keep polish the code to reduce the footprint.

**Comment by bluebill1049** [comment]
<img width="968" alt="Screen Shot 2020-11-20 at 6 12 21 pm" src="https://user-images.githubusercontent.com/10513364/99770641-f194a100-2b5b-11eb-8892-a3bcfae44c18.png">

updated 👍
