### ISSUE TITLE
useFieldArray.ts:37 --> error in dev

### ISSUE THREAD

**Issue by quertenmont** [react-hook-form/react-hook-form#3462]
**Describe the bug**
I just migrated to react-hook-form version >=9.10,
and my code is not working anymore, because of the line src/useFieldArray.ts:37

The reported error is:
TypeError: Cannot use 'in' operator to search for 'id' in name1

```
  34 | ): Partial<ArrayField<TFieldArrayValues, TKeyName>>[] => {
  35 |   if (process.env.NODE_ENV !== 'production') {
  36 |     for (const value of values) {
> 37 |       if (!!value && keyName in value) {
  38 |         console.warn(
  39 |           `📋 useFieldArray fieldValues contain the keyName \`${keyName}\` which is reserved for use by useFieldArray. https://react-hook-form.com/api#useFieldArray`,
  40 |         );
```

I don't quite understand why, but it applies the "in" operator on the array item, and not on the array itself.
I suspect it comes from the form of my data which are structured as:
```
{
   "names":{
      "en":["name1", "name2", "name3"]
   }
}
```
I suspect that the code is now faulty because you expect to get "object" inside the array, but my data aren't structure that way.
can you fix the code to check first if "value" is of type object ?

Thanks in advance,
Loic

**Comment by bluebill1049** [comment]
can you share a CSB?

**Comment by bluebill1049** [comment]
i am going to patch now, but keen to see your usage like.

**Comment by quertenmont** [comment]
bha, the usage is pretty simple...
just useFieldArray on data of the form:
```
{
   "names":{
      "en":["name1", "name2", "name3"]
   }
}
```
const { handleSubmit, errors, control } = useForm({ defaultValues: obj });
const { fields, append, remove } = useFieldArray({ control, name: "names.en" });

**Comment by quertenmont** [comment]
PS: thanks for your prompt action, this is appreciated

**Comment by quertenmont** [comment]
it's actually more problematic apparently, because the fields returned by useFieldArray have converted my string items to object items --> so the "name1" item has now become: { 0:"n", 1:"a", 2:"m", 3:"e", 4:"1", id:"...."  },
and so my controller receiving those data is not happy at all...

**Comment by bluebill1049** [comment]
your input name should be in object shape, we don't support flat array.

**Comment by quertenmont** [comment]
yes, this is what I figured out, what is a pitty is that this was supported in version 6.0.8
may I suggest you to update the documentation to clearly state that flat array are not supported.

Thanks for help anyway,

**Comment by bluebill1049** [comment]
<img width="891" alt="Screen Shot 2020-11-17 at 7 15 02 pm" src="https://user-images.githubusercontent.com/10513364/99363739-34126f80-2909-11eb-8d43-accab63b8085.png">
yes it's in the doc, let me know how can we improve or PR welcome as well.

introduce another PR to include console.warn as well.

**Comment by parties** [comment]
@bluebill1049 can we get an explanation as to _why_ flat arrays aren't supported? This seems like a pretty crucial feature..

Quick explanation of what I'm trying to do:
- I'm building a bridge from a GraphQL schema to a react-hook-form (in short, auto-generating a form from a GraphQL schema).
- Our schemas use lists of scalars such as string arrays, float arrays, etc. and we want these to be handled by react-hook-form.
- Unfortunately, given this constraint of not supporting flat arrays we have to come up with some kind of workaround where we map our flat arrays into non-flat arrays with id/value combos.

Any advice on how to proceed?

**Comment by k-one-o-two** [comment]
Are there any plans to support flat arrays?
