### ISSUE TITLE
isDirty is not updated with multiple select field

### ISSUE THREAD

**Issue by ronakkaji** [react-hook-form/react-hook-form#3468]
**Describe the bug**
`isDirty` is not updated with multiple select although it updates `dirtyFields` to empty object.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-forked-sj6tk?file=/src/index.js
2. Try to change Title Field to "Mr" only and then change back to Mr & Mrs
3. Observe formState `isDirty`

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-forked-sj6tk?file=/src/index.js

**Actual behavior**
`isDirty` is not updated once that field is changed.

**Expected behavior**
`isDirty` should be updated to `false`

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-forked-h7vx3?file=/src/index.js

please provide **full** defaultValues.

<img width="938" alt="Screen Shot 2020-11-17 at 9 41 56 pm" src="https://user-images.githubusercontent.com/10513364/99380193-b9078400-291d-11eb-9925-0e98d170bc15.png">
