### ISSUE TITLE
Support one field required out of many validation

### ISSUE THREAD

**Issue by nimabrownlee** [react-hook-form/react-hook-form#3471]
**Is your feature request related to a problem? Please describe.**
At the moment there is only validation for specific fields. It would be amazing if somehow you could add validation based off other inputs.

For example:

`Email`
`Phone`

Only one of them is required. If you fill in `Email` then `Phone` is not required.

**Describe the solution you'd like**

Right now validation is added part of `register`. Possibly add an extra field like `mode` to the `useForm` hook and call it `validation`.

**Describe alternatives you've considered**

I think something similar is possible using `getValues` and comparing them. But this would be a great addition to the great library react-hook-form is.

**Comment by bluebill1049** [comment]
Thanks @nimabrownlee i think that's what `validate` function was made for.

```
validate: (value) => {
  return !!getValue().Phone || value;
}
```

**Comment by nimabrownlee** [comment]
@bluebill1049 

Thanks Bill for the quick response. Usually I have my validation outside the component as an object and I think it would be nice if you could access other fields through the `validate` function. That way I can share the same validation with multiple components.

**Comment by bluebill1049** [comment]
> @bluebill1049
> 
> Thanks Bill for the quick response. Usually I have my validation outside the component as an object and I think it would be nice if you could access other fields through the `validate` function. That way I can share the same validation with multiple components.

Yes, definitely considered that, but that's the thing is we want hook form to be cheap, simple, and fast. The less burden we carry the better in my opinion. So instead of hard code `getValues()` inside the `validate`, maybe consider to compose a function which can leverage `getValues` as an argument,

**Comment by bluebill1049** [comment]
I will ping on the board for a couple of weeks anyhow, see if other users have a similar request.

**Comment by nimabrownlee** [comment]
@bluebill1049 I understand. Thanks for the great library you guys have created and for all the hard work you do.

**Comment by Semigradsky** [comment]
@bluebill1049 I have the same problem. See example: https://codesandbox.io/s/react-hook-form-customresoliver-v6-forked-ctzoi?file=/src/index.jsx

I need to validate `from`, `to` and `enabled` fields together. With `resolver` I did it
```tsx
  const { register, handleSubmit, errors, watch } = useForm({
    resolver: (data) => {
      let error = null;

      if (data.enabled) {
        if (!data.from || !data.to) {
          error = '"from" and "to" are required.';
        } else if (data.to < data.from) {
          error = '"to" date should be geater than "from" date.';
        }
      }

      return {
        values: error ? {} : data,
        errors: error
          ? {
              enabled: error
            }
          : {}
      };
    }
  });
```
but error messages disappears only when I press "Submit". I need revalidation on any of these fields changes.

**Comment by bluebill1049** [comment]
> @bluebill1049 I think I have the same problem. See example: https://codesandbox.io/s/react-hook-form-customresoliver-v6-forked-ctzoi?file=/src/index.jsx
> 
> I need to validate `from`, `to` and `enabled` fields together. With `resolver` I did it
> 
> ```tsx
>   const { register, handleSubmit, errors, watch } = useForm({
>     resolver: (data) => {
>       let error = null;
> 
>       if (data.enabled) {
>         if (!data.from || !data.to) {
>           error = '"from" and "to" are required.';
>         } else if (data.to < data.from) {
>           error = '"to" date should be geater than "from" date.';
>         }
>       }
> 
>       return {
>         values: error ? {} : data,
>         errors: error
>           ? {
>               enabled: error
>             }
>           : {}
>       };
>     }
>   });
> ```
> 
> but error messages disappears only when I press "Submit". I need revalidation on any of these fields changes.

you couldn't getValues from `getValues()` method within `validate`?

**Comment by Semigradsky** [comment]
> you couldn't getValues from `getValues()` method within `validate`?

Could you please show on codesandbox above? I don't how it can help me with revalidation on fields changes.

**Comment by bluebill1049** [comment]
> > you couldn't getValues from `getValues()` method within `validate`?
> 
> Could you please show on codesandbox above? I don't understand how it can help me with revalidation on fields changes.

I may miss something here, but here is what i meant: https://codesandbox.io/s/naughty-feather-p63zi?file=/src/App.js

**Comment by Semigradsky** [comment]
@bluebill1049 in your example `errors` changed only on first change `test1` field. And it doesn't change on `test` field change.

**Comment by bluebill1049** [comment]
> @bluebill1049 in your example `errors` changed only on first change `test1` field. And it doesn't change on `test` field change.

you will need to user `trigger` for dependent inputs, we focus an input at a time to give better perf

**Comment by Semigradsky** [comment]
> you will need to user `trigger` for dependent inputs

Thanks a lot!
