### ISSUE TITLE
Controlled Input: need to press backspace two times to delete last remaining character

### ISSUE THREAD

**Issue by Nisfan** [react-hook-form/react-hook-form#348]
**Describe the bug**
In controlled Input, need to press backspace two times to delete last remaining character

**To Reproduce**
1. enter some text into text input
2. delete the character one by one (backspace)
3. You have to press backspace two times to delete the last character

https://codesandbox.io/s/react-hook-form-controlled-input-bug-vxxig

**Comment by bluebill1049** [comment]
hey @Nisfan,

please remove value and use defaultValue instead

https://react-hook-form.com/faq

Why is first keystroke is not working?

**Comment by Nisfan** [comment]
> please remove value and use defaultValue instead

I don't think default value will solve the problem, In codesandbox demo, if I want to set custom value like formatting number, How can I do that?

> Why is first keystroke is not working?
Hmm, I didn't notice

**Comment by bluebill1049** [comment]
you can do native HTML stuff like below :)

`onChange={e => e.target.value = maskInput(e.target.value);}`

`maskInput` will be your own function to transform the input.

**Comment by bluebill1049** [comment]
This is one of the example: https://codesandbox.io/s/387z7njwzp

**Comment by bluebill1049** [comment]
i am closing this issue :) feel free to re-open or asking more questions here.

**Comment by nullwriter** [comment]
This happens to me. Whenever I get an error, and I try to delete the input, the first try only removes the error message, then the second try removes the character I'm trying to actually delete.

Anyone fixed this?

**Comment by bluebill1049** [comment]
Take a look here: https://react-hook-form.com/faqs#Whyisfirstkeystrokeisnotworking @nullwriter i think it's due to controller changed to uncontrolled or vice versa.

**Comment by iron66** [comment]
> Take a look here: https://react-hook-form.com/faqs#Whyisfirstkeystrokeisnotworking @nullwriter i think it's due to controller changed to uncontrolled or vice versa.
Okay, what if I need input to be controlled?

**Comment by bluebill1049** [comment]
> > Take a look here: https://react-hook-form.com/faqs#Whyisfirstkeystrokeisnotworking @nullwriter i think it's due to controller changed to uncontrolled or vice versa.
> > Okay, what if I need input to be controlled?

https://react-hook-form.com/api#Controller
