### ISSUE TITLE
getValues() retrieves old value for hidden inputs with default value

### ISSUE THREAD

**Issue by zach-waggoner** [react-hook-form/react-hook-form#3484]
**Describe the bug**
I have a field array with a hidden input that is modified with `setValue()`. If I later call `getValues()` on that hidden input, I always get back the original value rather than the updated value. This is in spite of the watch API returning the updated value. This only occurs for hidden inputs; if I make it a text input, `getValues()` returns the correct value.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-field-array-hidden-input-vbn5w
1. Open the console
1. Click on "Modify x" next to the hidden field
1. Observe that the watched value for `x` changes from "a" to "b"
1. Click on "Log x" next to the hidden field
1. Observe that the logged value is "a"
1. Repeat the above steps for the text input
1. Observe that the logged value is now "b," as expected

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-field-array-hidden-input-vbn5w

**Expected behavior**
I expect `getValues()` to return the updated value as it does for text inputs.

**Desktop (please complete the following information):**
- OS: macOS 10.15.7
- Browser: Chrome
- Version: 86

**Comment by bluebill1049** [comment]
This is React related to uncontrolled defaultValue plus hidden input. If you really need to achieve what you want, you will have to do the following.

```
<input
  type={index % 2 === 0 ? "hidden" : "text"}
  name={`fields[${index}].x`}
  defaultValue={x || field.x}
  ref={register()}
/>
```

**Comment by zach-waggoner** [comment]
Are you sure? See the following codesandbox: https://codesandbox.io/s/react-hook-form-hidden-input-defaultvalue-771d5?file=/src/index.js

Notice that if you click "Modify value (RHF)" and then log the value, "a" is still logged, but if you click "Modify value (React)" and then log the value, "b" is correctly logged. Thus, it seems it _is_ possible to modify an uncontrolled hidden input with a deafult value in React, and the problem specifically has to do with `setValue()`.

**Comment by bluebill1049** [comment]
not if you try to `updateState` at the same time: https://codesandbox.io/s/react-hook-form-hidden-input-defaultvalue-forked-5wwmo?file=/src/index.js

**Comment by bluebill1049** [comment]
I don't think there is much we can do at this lib level :( and probably not going to hack to get it working as well. so please consider using CSS display none for the fix.

**Comment by zach-waggoner** [comment]
That is interesting; I wonder if it would be worth mentioning this gotcha in the docs somewhere? I'm not able to find anything about this special behavior of hidden inputs in the React docs, so it is likely to trip others up too. Your call, and thanks for the help.

**Comment by bluebill1049** [comment]
another quick solution here with Controller: https://codesandbox.io/s/react-hook-form-hidden-input-defaultvalue-forked-5wwmo?file=/src/index.js
