### ISSUE TITLE
"missing ref" error from version 6.10

### ISSUE THREAD

**Issue by kino90** [react-hook-form/react-hook-form#3485]
**Describe the bug**
I am using:

- React + Typescript
- Material-ui (`@material-ui/core`) for the UI
- Material-ui-pickers (`@material-ui/pickers`) for the KeyboardDatePicker
- `date-fns` and DateFnsUtils (`@date-io/date-fns`) for the picker
- `react-hook-form` (of course)
- `yup` and `@hookform/resolvers/yup` resolver.

Trying to connect a KeyboardDatePicker with the `Controller` component I was getting errors, so I googled and found a solution (see sandbox below), but with my version of `react-hook-form` (which is 6.11.3) it is not working. 

The error in console says:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

This happens only with any version that is >= 6.10.0
 

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-ref-bug-rji1w
2. The Date input is working
2. Update react-hook-form to any version that is >= 6.10.0
4. See error in console

**Codesandbox link (Required)**
- [CodeSandbox](https://codesandbox.io/s/react-hook-form-ref-bug-rji1w)

**Expected behavior**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] any
- Browser [e.g. chrome, safari] Chrome

**Comment by ghostd** [comment]
It seems, according to #3411, it should be fixed with the last release

**Comment by kino90** [comment]
Hello @ghostd , Thanks for the quick reply!
I am actually using `6.11.3` (which I think it's the last.. or at least NPM says so) and I still got the error.
Maybe it will be fixed in the _next_ one?

**Comment by bluebill1049** [comment]
hey @kino90 please use `render` prop and assign `ref` if there is any (eg: `inputRef`), we try to improve accessibility for `onFocus` during an error.

**Comment by kino90** [comment]
Thanks, got it working with the following code 

``` typescript
<Controller
    control={control}
    name="myDateField"
    render={({ onChange, onBlur, value, name, ref }) => (
        <KeyboardDatePicker
            autoOk
            disabled={isLoading}
            error={Boolean(errors?.myDateField)}
            format="dd/MM/yyyy"
            fullWidth={true}
            helperText={getHelperText("myDateField")}
            inputRef={ref}
            inputVariant="outlined"
            label="Date"
            name={name}
            onBlur={onBlur}
            onChange={onChange}
            size="small"
            variant="inline"
            value={value}
        />
    )}
/>
```

by also setting `defaultValues` to `null` to avoid "converting uncontrolled input to controlled" error 😃

**Comment by bluebill1049** [comment]
@kino90 focus on error working as well?

**Comment by kino90** [comment]
@bluebill1049 just tried it.. focus is not working at the moment, but at least the datepicker works! 

Any suggestion for the focus behavior?

**Comment by bluebill1049** [comment]
Does the DatePicker have `focus` callback prop or `ref` for the actual input? eg: `react-select`'s ref has a focus callback. It's the correct thing to do for accessibility, then the user will get focused on that errored input. here is an example: https://codesandbox.io/s/react-hook-form-focus-74ecu

**Comment by bzmillerboy** [comment]
I faced this same issue and @kino90 's solution to use `render` instead of `as` worked for me.  Why isn't `as` supported anymore?

**Comment by bluebill1049** [comment]
> I faced this same issue and @kino90 's solution to use `render` instead of `as` worked for me. Why isn't `as` supported anymore? There are a lot of tutorials and info floating around that suggest `as`, example https://dev.to/raduan/4-ways-to-use-material-ui-select-with-react-hook-form-41b2

I think we will slowly move away from `as`, and deprecated it in the next major version. It has quite a few design issues.

**Comment by bianchi** [comment]
> ```ts
> render={({ onChange, onBlur, value, name, ref }) => (
>         <KeyboardDatePicker
>             autoOk
>             disabled={isLoading}
>             error={Boolean(errors?.myDateField)}
>             format="dd/MM/yyyy"
>             fullWidth={true}
>             helperText={getHelperText("myDateField")}
>             inputRef={ref}
>             inputVariant="outlined"
>             label="Date"
>             name={name}
>             onBlur={onBlur}
>             onChange={onChange}
>             size="small"
>             variant="inline"
>             value={value}
>         />
>     )}
> ```

Using typescript I get and error **Property 'ref' does not exist on type '{ onChange: (...event: any[]) => void; onBlur: () => void; value: any; name: string; }'.ts(2339)**. Any ideas?

**Comment by bluebill1049** [comment]
> > ```ts
> > render={({ onChange, onBlur, value, name, ref }) => (
> >         <KeyboardDatePicker
> >             autoOk
> >             disabled={isLoading}
> >             error={Boolean(errors?.myDateField)}
> >             format="dd/MM/yyyy"
> >             fullWidth={true}
> >             helperText={getHelperText("myDateField")}
> >             inputRef={ref}
> >             inputVariant="outlined"
> >             label="Date"
> >             name={name}
> >             onBlur={onBlur}
> >             onChange={onChange}
> >             size="small"
> >             variant="inline"
> >             value={value}
> >         />
> >     )}
> > ```
> 
> Using typescript I get and error **Property 'ref' does not exist on type '{ onChange: (...event: any[]) => void; onBlur: () => void; value: any; name: string; }'.ts(2339)**. Any ideas?

can you reproduce that in a codesandbox?

**Comment by bianchi** [comment]
Was able to move forward just passing all props

`render={props => (
autoOk
...
{...props}
size="small"
...
)}
`
