### ISSUE TITLE
ES6 module build includes references to `process.env.NODE_ENV`

### ISSUE THREAD

**Issue by spaceaardvark** [react-hook-form/react-hook-form#3498]
**Describe the bug**
The ES6 module build includes references to `process.env.NODE_ENV`, which breaks browser usages -- browsers now support ES6 modules. This is hidden by `react-scripts` in Codesandbox.io because it provides a definition for process.env.NODE_ENV.

**To Reproduce**

1. Use Rollup to create an ES6 module build that runs in the browser.
2. Pass `register` to the `ref` prop as done in just about every example.
3. Run the code in the browser.
4. Open the JS console and note the "process is not defined" error.

**Codesandbox link (Required)**
I flipped a table trying to get Codesandbox to **not** use create-react-app. I hope you don't mind if I just created a dedicated repo with reproduction instructions in the README:

https://github.com/spaceaardvark/react-hook-form-bug1

**Expected behavior**
The browser build should not encounter or use process.env.NODE_ENV.

**Desktop (please complete the following information):**

- OS: Ubuntu 20
- Chrome
- v86.0.4240.198

**Additional context**
From conversation in #1441 after it was closed.

**Comment by bluebill1049** [comment]
@jorisre if we using https://github.com/developit/microbundle in the main lib, this issue can be potentially solved by itself (cause that lib takes care of it)?

**Comment by jorisre** [comment]
👋🏻

@spaceaardvark Thanks for reporting. 
Your use case is really interesting ! Thanks for the reproduction.
I think you mean [modern module (es6) ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules). At this time, RHF's ES6 module is not a modern module, that's why it contains `process.env.*`.

@bluebill1049 Yes, this can be solved by using microbundle which provide modern bundle. I started to switch from custom rollup config to microbundle this morning ;)

**Comment by bluebill1049** [comment]
That's amazing! Thanks a lot @jorisre

**Comment by bluebill1049** [comment]
hey, @jorisre do you know if this plugin can solve this problem? https://github.com/rollup/plugins

**Comment by jorisre** [comment]
> hey, @jorisre do you know if this plugin can solve this problem? https://github.com/rollup/plugins

Which plugin ?

**Comment by bluebill1049** [comment]
> > hey, @jorisre do you know if this plugin can solve this problem? https://github.com/rollup/plugins
> 
> Which plugin ?

oops wrong link, should be this one: https://github.com/rollup/plugins/tree/master/packages/replace

**Comment by jorisre** [comment]
The easy way to generate a modern bundle is to use [microbundle](https://github.com/developit/microbundle):

    microbundle build -f modern --define process.env.NODE_ENV=production --jsx React.createElement

But I could'nt find where to add this bundle in the exports map in the package.json file.

**Comment by bluebill1049** [comment]
> But I can't find where to add this bundle in the exports map in the package.json file.

What do you mean by that?

**Comment by jorisre** [comment]
I mean I don't know where I have to add the modern bundle  in the `exports` field of the package.json: https://nodejs.org/api/packages.html#packages_conditional_exports

We use `exports` too for resovlers but not for modern https://github.com/react-hook-form/resolvers/pull/108/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R11

Is it more clear ?

**Comment by bluebill1049** [comment]
Got it, thanks @jorisre

**Comment by bluebill1049** [comment]
This will be fixed in v7's release.
