### ISSUE TITLE
Issues using the controller and Ant select fields.

### ISSUE THREAD

**Issue by amponsah** [react-hook-form/react-hook-form#3499]
Description:

I think the onChange prop on controlled select does not update form values until submit.  Is there a way to update getValues() as you trigger onChange prop?

When looking at the sandbox to reproduce check the Components (ControlledSelect1, ControlledSelect2 & ControlledSelect3) in index.js.  I've tried different ways of creating the select but have the same results!

Steps to reproduce the behaviour:

1. Refresh page In sandbox
2. Don't click submit
3. Change all 3 dropdown menus to another item , not the default.
4. Notice the the getValues() output on the page below the submit button does not update.
5. Now click submit
6. Now getValues() is updated

Codesandbox:
https://codesandbox.io/s/bitter-sky-4zy6m?file=/src/index.js

Expected behavior
I need getValues() to update onChange. Is the possible?  I need to get this new value because it determines how other form fields below it will render.

Thanks in Advance!

Desktop:
- Mac OS Mojave
- Browser [Chrome]
- Version [87.0.4280.67]

**Comment by amankkg** [comment]
@amponsah this is not the intended way of using of `getValues` API

Here is a note in docs https://react-hook-form.com/api/#getValues

`**Important**: You shouldn't use this method inside render. This is suitable for reading values in an event handler. You can refer to the example below.`

**Comment by bluebill1049** [comment]
`watch/useWatch` API instead of `getValues()`

**Comment by amponsah** [comment]
Hey, thanks that was what I was looking for!
