### ISSUE TITLE
Controller component's TControl type parameter does not respect subtyping

### ISSUE THREAD

**Issue by amankkg** [react-hook-form/react-hook-form#3500]
**Describe the bug**
Controller and a few other components/hooks/prop types are parameterized on `TControl` and, while this is not an issue in development (e.g. if you import types locally from `react-hook-form/src`), in production this ends up as following
```ts
// dist/controller.d.ts:4
declare const Controller: <..., TControl extends Control<Record<string, any>> = Control<Record<string, any>>...
```
This leads to Controller's `control` prop being incompatible with type parameters on userland component with similar type constraint `T extends Record<string, any>`

**To Reproduce**

0. Make sure your imports are from the production bundle (e.g. `node_modules` or `./dist` for local)
1. Create a component which has a generic parameter (note: this is the same as `Control`s type parameter) and render a `Controller` wrapper with its `control` property taken from parameterized props, as follows:
```tsx
import {Control, Controller, FieldName, useForm} from 'react-hook-form'

type FieldProps<FV extends Record<string, any>> = {
  control: Control<FV>
  name: FieldName<FV>
}

const Field = <FV extends Record<string, any>>(props: FieldProps<FV>) => (
  <Controller control={props.control} name={props.name} as="input" />
)
```
2. See type error at `<... control={props.control} .../>` which boils down to this:

```sh
Type 'DeepMap<Record<string, any>, true>' is not assignable to type 'DeepMap<FV, true>'. ts(2322)
```

**Codesandbox link (Required)**
https://codesandbox.io/s/stoic-dawn-xx41j

**Expected behavior**
No errors, types of Controller's `control` prop and passed in value's generic constraints match fully

**Additional context**
This is a long-standing issue. First, I faced this error back in July 2020. We were building re-usable components with integrations of `@material-ui` and `react-hook-form` in order to minimize the code needed to build large and complex forms (project requirements). And, on top of that, I spent a lot of time to make all these components and hooks typed as strictly as possible. Once this problem occurred I tried to discuss it here #2700 but got no response. Also, I had some priorities changed at work so I `@ts-expect-error`ed this and only came back to this recently, so I'm happy to help!

Also, there is a similar issue closed but not completely fixed I believe: #2984 

I found a partial fix for this 3d713b310d5ccb303313ccad82585ea81a068c4e in git logs but it was reverted due to some other error.

IMO that fix was in right direction since the main "type variable" here is the user's form data shape (i.e. `FieldValues`). So, it makes sense if we make all other type constraints based on this. And, this way we don't need `TControl` type param anywhere since it can be replaced by `Control<FV>` directly unless the `Control` type itself is not a static type (e.g. if there are some descendants of it, then it also needs to be mentioned in generic parameters, so far I didn't find such cases in the codebase).

**Comment by amankkg** [comment]
I opened PR, plz take a look and give your feedback. Thanks!

**Comment by amankkg** [comment]
Hey @bluebill1049 @kotarella1110 
I'm slowly getting familiar with the codebase, and I think there is another use of `TControl`
```ts
// src/types/fieldArray.ts
export type FieldArrayName = string;

export type UseFieldArrayOptions<
  TKeyName extends string = 'id',
  TControl extends Control = Control
> = {
  name: FieldArrayName;
  keyName?: TKeyName;
  control?: TControl;
};
```

Since I've not used this API yet I'm not sure if there are any bugs about it. However, the pattern is quite similar.

I quickly tried to replace `TControl` here with `Control<FieldValues` and got an error that led me to `FieldArrayName` type being just a `string` (kinda strange, isn't it?).

So, if you have some context on this line, can you shed some light on it. I'll take a deeper look later too.

Another Q: what is https://github.com/react-hook-form/strictly-typed and how it correlates with this repo? Thanks!

**Comment by kotarella1110** [comment]
> Another Q: what is https://github.com/react-hook-form/strictly-typed and how it correlates with this repo? Thanks!

@amankkg strictry-typed can be used if you want to make Controller components more type-safe 👮‍♂️ 
If you need a strictly type, please install it 👍
