### ISSUE TITLE
useFieldArray reset field value for first item

### ISSUE THREAD

**Issue by martinpham97** [react-hook-form/react-hook-form#3502]
**Describe the bug**
When removing the added element, the first element's value is reset.
This seems to only happen when using Controller and FormProvider.

**To Reproduce**

1. Enter a value in 1st input
2. Add another item
3. Enter a value in 2nd input
4. Remove the 2nd item

**Codesandbox link (Required)**

https://codesandbox.io/s/silly-rosalind-c4di0

**Expected behavior**
Removing the 2nd item should not reset the 1st item's value

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 86.0.4240.198

**Additional context**
N/A

**Comment by bluebill1049** [comment]
you are missing `defaultValue`, have a look at the example in the doc: https://codesandbox.io/s/react-hook-form-usefieldarray-vy8fv

https://react-hook-form.com/api#useFieldArray

**Comment by martinpham97** [comment]
In your example [(codesandbox.io/s/react-hook-form-usefieldarray-vy8fv)](codesandbox.io/s/react-hook-form-usefieldarray-vy8fv) it would not work on the latest version (react-hook-form v6.11.4)

**Comment by bluebill1049** [comment]
> In your example [(codesandbox.io/s/react-hook-form-usefieldarray-vy8fv)](codesandbox.io/s/react-hook-form-usefieldarray-vy8fv) it would not work on the latest version (react-hook-form v6.11.4) for the Controller input only.

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-obrtn?file=/src/index.js

can you share the steps?

**Comment by martinpham97** [comment]
[https://codesandbox.io/s/react-hook-form-usefieldarray-forked-xqy0i](codesandbox.io/s/react-hook-form-usefieldarray-forked-xqy0i)

If the default value is an empty string "", upon changing the first field and removing subsequent fields, the first field's value is reset.

**Comment by bluebill1049** [comment]
the issue is caused by this PR: https://github.com/react-hook-form/react-hook-form/pull/3420
