### ISSUE TITLE
Feature: input type in the form builder

### ISSUE THREAD

**Issue by zaaakher** [react-hook-form/react-hook-form#3506]
It'd be nice to see the field type next to the field name. 👍 

https://github.com/react-hook-form/react-hook-form/blob/4a58084e2d3aaa0f47872da22dd17d51b3eb22cb/website/src/SortableContainer.tsx#L129-L131

**Comment by bluebill1049** [comment]
Thanks, @zaaakher We don't have a plan to improve the builder at the moment, while priority the task at lib first.
