### ISSUE TITLE
`append` function of `useFieldArray` and `isDirty` on form state does not work as expected when nesting forms

### ISSUE THREAD

**Issue by delijah** [react-hook-form/react-hook-form#3508]
**Describe the bug**
When having nested forms, it looks like the context of the `append` function of `useFieldArray` gets messed up. Therefore `isDirty` on the form state stays false after appending a field to the field array, even though `dirtyFields` have been populated (Example 1).

If i wait for the nested form to get removed from the dom, the `append` function works as expected again (Example 2).

**To Reproduce**

For Example 1:
1. Type any string into the text field in the modal on the bottom right
2. Press 'Submit' in the modal on the bottom right
3. Now you see in the dumped form state, that `isDirty` is still false, but there are `dirtyFields`

**Codesandbox link (Required)**
Example 1 (bug): https://codesandbox.io/s/react-hook-form-useform-template-forked-4lnku?file=/src/index.js
Example 2 (workaround): https://codesandbox.io/s/react-hook-form-useform-template-forked-pyuy6?file=/src/index.js

**Expected behavior**
1. `append` should work correctly, even in nested forms
2. `isDirty` must be true, when there are dirty fields / when a field has been added to a field array

**Desktop (please complete the following information):**

- OS: macOS Mojave Version 10.14.6 (18G5033)
- Browser: Google Chrome Version 87.0.4280.67 (Official Build) (x86_64)

**Comment by bluebill1049** [comment]
Please provide a reasonable and isolated Codesandbox example to reproduce the issue. There are way too many side effects and extra components which make it hard for me to investigate the issue.

**Comment by delijah** [comment]
Ok, i'll try so 👍

**Comment by bluebill1049** [comment]
Thanks, @delijah worth to mention, `isDirty` is doing a deep comparison against your defaultValue. so if you can prove `defaultValues` is set and the field array is not working correctly, then I will investigate for a fix for the bug.

**Comment by delijah** [comment]
Hey @bluebill1049! I've simplified the first example. Therefore the second example is obsolete since i've also removed the form removal from the first example in order to make it more slim.

**Comment by bluebill1049** [comment]
ok, let's focus on this one first: https://codesandbox.io/s/react-hook-form-useform-template-forked-km3r6?file=/src/index.js

what are the steps to reproduce the issue? can you also remove all those debug info as well? let's focus on the code and usage. We can console log those values easily.

**Comment by delijah** [comment]
> ok, let's focus on this one first: https://codesandbox.io/s/react-hook-form-useform-template-forked-km3r6?file=/src/index.js
> 
> what are the steps to reproduce the issue? can you also remove all those debug info as well? let's focus on the code and usage. We can console log those values easily.

As described in the issue description...
1. Click on 'Another one' in the Modal/Portal
2. Click on 'Submit' in the Modal/Portal
3. Now you see in the dumped form state, that `isDirty` is still false, but there are `dirtyFields`

**Comment by delijah** [comment]
One more even simpler example: https://codesandbox.io/s/react-hook-form-useform-template-forked-4lnku?file=/src/index.js

What to do:
1. Type any string into the text field in the modal (bottom right)
2. Press 'Submit' in the modal (bottom right)
3. Now you see in the dumped form state, that `isDirty` is still false, but there are `dirtyFields`

**Comment by delijah** [comment]
@bluebill1049 sorry there was a small bug in the examples, fixed now.

**Comment by bluebill1049** [comment]
Thanks, @delijah for the update. Much cleaner to focus on the problem now.

**Comment by bluebill1049** [comment]
<img width="539" alt="Screen Shot 2020-11-24 at 8 25 37 am" src="https://user-images.githubusercontent.com/10513364/100017195-a36af080-2e2e-11eb-80cb-a04aa52aa9a1.png">

That's why i said console.log it's easier hahaha.

**Comment by bluebill1049** [comment]
<img width="1050" alt="Screen Shot 2020-11-24 at 8 28 47 am" src="https://user-images.githubusercontent.com/10513364/100017488-14aaa380-2e2f-11eb-926f-14e7a490e416.png">

just did a quick test, it's working for me, but I am sure I miss the steps.

<img width="436" alt="Screen Shot 2020-11-24 at 8 30 21 am" src="https://user-images.githubusercontent.com/10513364/100017613-4cb1e680-2e2f-11eb-8825-41e9a70ff896.png">

why this input name is not a field array shape?

**Comment by delijah** [comment]
> why this input name is not a field array shape?

because this is a separate form. it has nothing to do with the field array. this form belongs to the modal. the idea behind it is to have a modal where the user can select additional data from a list, which will get inserted into the field array.

**Comment by delijah** [comment]
> That's why i said console.log it's easier hahaha.

yeah it can get tricky 😄 but the overview of the data, if it's not blocked by an overlay, is great 😉

**Comment by delijah** [comment]
> just did a quick test, it's working for me, but I am sure I miss the steps.

hmm, that's weird. this is how it looks on my site:

![Uploading react-hook-form.gif…]()

**Comment by bluebill1049** [comment]
I have removed all those extra components, have a test below, let me know.

https://codesandbox.io/s/react-hook-form-useform-template-forked-j2770?file=/src/index.js:182-191

**Comment by bluebill1049** [comment]
ok, looks like I found the issue, it's due to the `watch` at your debugger.

**Comment by delijah** [comment]
> I have removed all those extra components, have a test below, let me know.
> 
> https://codesandbox.io/s/react-hook-form-useform-template-forked-j2770?file=/src/index.js:182-191

hmmm, ok, that's weird. yeah in your example it works for me as well. but in the older a bit more complex example it still doesn't work correctly, even without the watch:

https://codesandbox.io/s/react-hook-form-useform-template-forked-km3r6?file=/src/index.js

**Comment by delijah** [comment]
> https://codesandbox.io/s/react-hook-form-useform-template-forked-km3r6?file=/src/index.js

seems to work with version `6.11.6-beta.1` 👍

**Comment by bluebill1049** [comment]
👍 will release the patch this weekend.

**Comment by bluebill1049** [comment]
> still the question why you've removed the `reset` is bugging me @bluebill1049 . is this not needed anymore?

I didn't know why you need it.

**Comment by delijah** [comment]
> > still the question why you've removed the `reset` is bugging me @bluebill1049 . is this not needed anymore?
> 
> I didn't know why you need it.

because of https://github.com/react-hook-form/react-hook-form/issues/3378 ?
