### ISSUE TITLE
TypeError: e.persist is not a function (inside handleSubmit function)

### ISSUE THREAD

**Issue by dudiharush** [react-hook-form/react-hook-form#3512]
**Describe the bug**
when i call handleSubmit in an "onClick" event, i get this error: TypeError: e.persist is not a function inside handleSubmit function

**To Reproduce**

1. import handleSubmit: const { handleSubmit } = useForm()
2. write click handler: const onClickHandler = (e) => { e => handleSubmit(()=>{}, ()=>{})(e); }
3. Click on the button with the handler
4. See error: TypeError: e.persist is not a function inside handleSubmit function

this may be related to: https://reactjs.org/docs/events.html
"Note: As of v17, e.persist() doesn’t do anything because the SyntheticEvent is no longer pooled."

**Comment by bluebill1049** [comment]
Do following:

`onClick={() => handleSubmit(onSubmit)()}`

**Comment by dudiharush** [comment]
Thanks. I decided not to work with rhf, since i couldn't find a way to work with it without using a form element, i just couldn't get the data out of "register" function's inner map, getValues didn't return the updated data, just the initial. any idea?

**Comment by bluebill1049** [comment]
not sure, you need to supply a codesandbox before anything can be assumed.
