### ISSUE TITLE
Nested form is unresponsive when using useWatch in production

### ISSUE THREAD

**Issue by mlonn** [react-hook-form/react-hook-form#3513]
**Describe the bug**
After updating from 6.11.0 to 6.11.2 we noticed in our production system that our address form was unresponsive.

We have a few inputs that should be shown or hidden depending on external input outside of the component where these unresponsive inputs are located. This means that we have a useEffect with the watched values as dependencies that is necessary to show the inputs if they receive a value. 

The issue only happens when doing a production build. Not when using the dev server. Demonstrated below that the code sandbox works as expected but the deploy to netlify does not work

**To Reproduce**
1. Go to netlify and code-sandbox links
2. Click on "SHOW ADDITIONAL ADDRESS LINES"
3. Try to fill in Address line2
4. In netlify only 1 character is register in the field before the field is unresponsive

**Codesandbox link **
https://csb-gti49.netlify.app/
https://codesandbox.io/s/react-hook-form-controller-template-forked-gti49
**Expected behavior**
The form should behave equally in dev and prod environments and the nested form component should update

**Desktop (please complete the following information):**

- OS: macOS 11.0.1
- Browsers
Firefox 84.0b4, 
Chrome Version 87.0.4280.67 (Official Build) (x86_64), 
Edge Version 87.0.664.41 (Official build) (64-bit), 
Safari 14.0.1

**Comment by bluebill1049** [comment]
could you please test out this beta version with a prod build: `6.11.6-beta.1`, let me know if the issue is resolved.

**Comment by mlonn** [comment]
> 6.11.6-beta.1

I can't find that tag 

We can confirm that it's still an issue on 6.11.5 though

**Comment by bluebill1049** [comment]
`react-hook-form@6.11.6-beta.1` try agian

**Comment by bluebill1049** [comment]
is the issue occurred at 6.11.1 or 6.11.2?

**Comment by mlonn** [comment]
Tried 6.11.1 now and the issue is there as well.

**Comment by bluebill1049** [comment]
<img width="539" alt="Screen Shot 2020-11-24 at 9 28 01 pm" src="https://user-images.githubusercontent.com/10513364/100082119-f16a0d80-2e9b-11eb-9891-ac184c6eb518.png">

why there is a warning?

**Comment by bluebill1049** [comment]
can you fix this line: 

```
<Controller
        control={control}
        name={`addressLine2`}
        defaultValue={""}
        render={({ onChange, value }) =>
          additionalAddressLines ? (
            <>
              <label>Address line 2</label>
              <input
                type="text"
                ref={register}
                onChange={onChange}
                value={value}
              />
            </>
          ) : (
            <></>
          )
        }
      />
```

**Comment by bluebill1049** [comment]
<img width="567" alt="Screen Shot 2020-11-24 at 9 29 18 pm" src="https://user-images.githubusercontent.com/10513364/100082253-1d858e80-2e9c-11eb-9780-5445e5627ce6.png">

one more warning.

**Comment by bluebill1049** [comment]
> can you fix this line:
> 
> ```
> <Controller
>         control={control}
>         name={`addressLine2`}
>         defaultValue={""}
>         render={({ onChange, value }) =>
>           additionalAddressLines ? (
>             <>
>               <label>Address line 2</label>
>               <input
>                 type="text"
>                 ref={register}
>                 onChange={onChange}
>                 value={value}
>               />
>             </>
>           ) : (
>             <></>
>           )
>         }
>       />
> ```

can you test this one out first?

**Comment by bluebill1049** [comment]
<img width="342" alt="Screen Shot 2020-11-24 at 9 30 46 pm" src="https://user-images.githubusercontent.com/10513364/100082416-51f94a80-2e9c-11eb-888b-880a5487c2dd.png">
change to the following, controller doesn't need register again.
```
<input
                type="text"
                onChange={onChange}
                value={value}
              />
```

**Comment by mlonn** [comment]
Thanks! it was the ref that was left from before we wrapped it in a controller. 

Greatly appreciated the feedback and help.

**Comment by bluebill1049** [comment]
I was sweating badly lol! good, we work it out. 👍

**Comment by oherik** [comment]
Hi! @mlonn's teammate here. I just wanted to chime in and thank you for your quick help, you made our day 🙏

**Comment by bluebill1049** [comment]
No worries guys ❤️ l am glad it's working out.
