### ISSUE TITLE
add "shouldDirty" to append from useFieldArray 

### ISSUE THREAD

**Issue by quertenmont** [react-hook-form/react-hook-form#3525]
**Is your feature request related to a problem? Please describe.**
would it be possible to add the "shouldDirty" flag to the append of useFieldArray ?

The shouldFocus already exist, so I guess it shouldn't be a big deal.
Thanks in advance

**Comment by bluebill1049** [comment]
What's the use case?

**Comment by quertenmont** [comment]
The use case is typically that I want my form array to always contain X items,
so if this is not the case, I pragmatically append empty items to the form array in a useEffect function.
```

React.useEffect(() => {
  if (fields.length < 2) {
    append({value:0});
  }
}, fields)
```

Given that the user has not interacted with the form, it doesn't make sense to have the form marked as dirty.

Thanks in advance
Loic

**Comment by bluebill1049** [comment]
sounds legit. let's put on the feature board.

**Comment by bluebill1049** [comment]
After future investigation this is not possible or difficult to implement, because each input gets append/prepend will leave inputs as an empty string, which then fails against deep equal against `defaultValues` and will result dirty as true, and if we don't enforce such behavior, it will leave inconsistent behavior for the formState.

**Comment by ezrabowman** [comment]
It would be helpful to be able to add fields to a FieldArray in a non-dirty state.

Sample use case:

- User has the ability to add sections to my form  of the same type of information (i.e. a form capturing multiple addresses).
- When the form loads, there is one instance of address in the field array
- User clicks "+ Add Another Address" and I use `append` to add the new address fields to the FieldArray
- All new fields are dirty although the user has not interacted with them

Note: This form uses the isDirty property to show the user what field they have changed when editing a record, so all the fields in the new address instance show up as dirty.

I am trying to come up with a work-around using some form of `reset`, but do not have a solution yet.

Also - @bluebill1049, you rock! Thanks for RHF.

**Comment by bluebill1049** [comment]
thanks for the feedback @ezrabowman 

related feature request: https://github.com/react-hook-form/react-hook-form/issues/3525 will probably get to it later in the stage, it's not a simple config update. I will mark this as duplicated and track it in the other one.
