### ISSUE TITLE
PROPOSAL: Pass the name/ref of the field being validated over to resolvers

### ISSUE THREAD

**Issue by ealush** [react-hook-form/react-hook-form#3538]
Hello 👋
Thank you for this awesome library! The amount of effort put into it is just incredible!

## Context
I am looking into writing custom resolver for [Vest](https://github.com/ealush/vest). Vest has a feature that allows the you to [only validate the field the user is currently interacting it](https://ealush.com/vest/#/./exclusion?id=only-running-specific-tests-including), while the rest of the results are cached internally (so no errors are lost when switching between fields).

This is quite a big perf-saver when working in an onChange or onBlur mode, because we do not need to worry about running everything and then filtering out the irrelevant errors.

The only thing required to allow this feature in HF as well is to pass the field (or fields) name (when applicable) being validated to the resolver. At the moment this behavior is only supported in `validateField` which does accept a reference to a field, but does not call the resolver.

The resolver would then be able to either use `vest.only` on behalf of the consumer, or pass it over for the consumers to use directly - depending on the validation strategy.

## Requested interface change
I would expect to use it like this:
```js
const { register, errors} = useForm({
	// fieldNames is either undefined, a string or an array of strings.
    resolver: (values, context, isValidateAllFieldCriteria, fieldNames) => {

      const result = validate(values, fieldNames);

      const errors = {};
      const vestErrors = result.getErrors();
      for (const field in vestErrors) {
        errors[field] = vestErrors[field][0];
      }

      return { values, errors };
    },
    mode: "onChange"
  })
```

### Alternative 1

One alternative would be to add an `extra`/`options` object. It would be effectively the same, but support future extensions of the interface without introducing bloat to the function signature.

```js
const { register, errors} = useForm({
    resolver: (values, context, isValidateAllFieldCriteria, extra = {}) => {

      const result = validate(values, extra.fieldNames);

      const errors = {};
      const vestErrors = result.getErrors();
      for (const field in vestErrors) {
        errors[field] = vestErrors[field][0];
      }

      return { values, errors };
    },
    mode: "onChange"
  })
```

### Alternative 2

Another viable alternative that does not require changing the function signature is extending the context ref with the current field/fields name. This might introduce a breaking change, since consumers may be using `context` to store primitives.
Also, it would require a post-validation cleanup of the context.

```js
// Using a symbol to prevent  a clash with consumer properties.
const INTERNAL_FIELD_NAMES = Symbol();
// ...
const { register, errors} = useForm({
    resolver: (values, context, isValidateAllFieldCriteria) => {

      const result = validate(values, context[INTERNAL_FIELD_NAMES]);

      const errors = {};
      const vestErrors = result.getErrors();
      for (const field in vestErrors) {
        errors[field] = vestErrors[field][0];
      }

      return { values, errors };
    },
    mode: "onChange"
  })
```

## Planned lib changes

I've mapped out the code changes I believe are needed in order to support this addition. There may be more that I missed. Let me know if you would like me to take a stab at it, or if you prefer a different approach.

#### Change 1 // for trigger()

https://github.com/react-hook-form/react-hook-form/blob/279061c7df264dd0549d050a294e57dc509b3447/src/useForm.ts#L382-L392
```js
const executeSchemaOrResolverValidation = React.useCallback(
  async (
    names:
      | InternalFieldName<TFieldValues>
      | InternalFieldName<TFieldValues>[],
  ) => {
    const { errors } = await resolverRef.current!(
      getValues(),
      contextRef.current,
      isValidateAllFieldCriteria,
	  names
    );
```

#### Change 2 // handleChangeRef

https://github.com/react-hook-form/react-hook-form/blob/279061c7df264dd0549d050a294e57dc509b3447/src/useForm.ts#L614-L618
```js
const { errors } = await resolverRef.current(
  getValues(),
  contextRef.current,
  isValidateAllFieldCriteria,
  name
);
```

#### Change 3 // validateResolver implementation
https://github.com/react-hook-form/react-hook-form/blob/279061c7df264dd0549d050a294e57dc509b3447/src/useForm.ts#L712-L721

```ts
const validateResolver = React.useCallback(
async (values = {}, fieldName?: string | string[]) => { 
  const { errors } = await resolverRef.current!( 
    { 
      ...getValues(), 
      ...values, 
    }, 
    contextRef.current, 
    isValidateAllFieldCriteria,
    fieldName
  ); 
```

#### Change 4 // validateResolver usage
https://github.com/react-hook-form/react-hook-form/blob/279061c7df264dd0549d050a294e57dc509b3447/src/useForm.ts#L776-L779

```js
readFormStateRef.current.isValid &&
  resolverRef.current &&
  validateResolver(undefined, field.ref.name);
updateWatchedValue(field.ref.name);
```

**Comment by bluebill1049** [comment]
Thanks, heaps for the detailed proposal! 

I think the following is going to be cleanest. It's a breaking change, probably will be part of v7.  

```
type Options = {
  isValidateAllFieldCriteria: boolean,
  fieldNames: FieldName[],
}

const { register, errors} = useForm({
    resolver: (values, context, { isValidateAllFieldCriteria, fieldNames } : Options ) => {

      const result = validate(values, fieldNames);

      const errors = {};
      const vestErrors = result.getErrors();
      for (const field in vestErrors) {
        errors[field] = vestErrors[field][0];
      }

      return { values, errors };
    },
    mode: "onChange"
  })
```

I think we will go with **Alternative 1** as it's more future proof.

**Comment by ealush** [comment]
Yes! Exactly. That would be amazing. I didn't want to introduce a breaking change, so I tried to walk around it - I wasn't aware of the plans for V7.

**Comment by bluebill1049** [comment]
not closing this 👍 , moving into project board.
