### ISSUE TITLE
"Maximum call stack size exceeded" when using react element in required

### ISSUE THREAD

**Issue by fxsloker** [react-hook-form/react-hook-form#3539]
**Describe the bug**
If I use react element inside register for required property, then I am getting the error "Maximum call stack size exceeded". 

**To Reproduce**

1. Go to the sandbox
2. Click on the email input to make it focused.
3. Click outside of the email input to make it unfocused.
4. Click on the email input again to make it focused.
5. Click outside of the email input to make it unfocused.
6. It throws the error "Maximum call stack size exceeded".

**Codesandbox link (Required)**
- https://codesandbox.io/s/quizzical-gauss-3nu25?file=/src/index.js

**Expected behavior**
It should render react element if email input is empty.

**Additional context**
Using react-hook-form v6.11.5

**Comment by jorisre** [comment]
👋🏻  Hi @fxsloker 

`message` should be a string, not a react element. That's why you got that error.

To wrap your message error you can do the following thing:

```js

<Form.Group controlId="email">
    <Form.Label>Email</Form.Label>
    <Form.Control
        name="email"
        type="email"
        ref={register({
            required: {
                value: true,
                message: "Email can't be empty."
             }
          })}
    />
    {errors.email && <div className="invalid-feedback">{errors.email.message}</div>}
</Form.Group>
```

@bluebill1049 Do you think it should be an enhancement ?

**Comment by fxsloker** [comment]
Hello @jorisre 

Thank you, your code works.

I just wanted to show why I used react element in `message`. Maybe I misunderstood it. According to the documentation here - https://react-hook-form.com/api#register it's written that `message` can be either string or React.ReactElement. http://prntscr.com/vr8ei4 . So I expected it to work the way I did it.

**Comment by bluebill1049** [comment]
@fxsloker I couldn't reproduce the issue at your CSB by following the steps.

I changed to P tag, so i can see the error message as well: https://codesandbox.io/s/pedantic-chatelet-g7q2i

**Comment by fxsloker** [comment]
@bluebill1049 I recorded a video showing the problem - https://www.loom.com/share/45b1cf5c126d496dbeb766d622749a54 Let me know if it helps to reproduce it.

**Comment by danielo515** [comment]
This problem still happens as reported. Was this "fix" reverted or was never the intention to allow passing `reset` as a click handler and the "fix" was a documentation update?
