### ISSUE TITLE
[Question] How to disable native HTML 5 validation

### ISSUE THREAD

**Issue by nshaikhinurov** [react-hook-form/react-hook-form#354]
I'm passing a `{nativeValidation: false}` option to the `useFormContext` hook although it is documented as a default value. However, even when I use custom `validate` function as an option to the `register` method of an email input type I can see unneeded native Chrome bubble with yellow exclamation mark. How can I get rid of it? The `type="email"` attribute of an input is convenient for determining what validation function to use in React components but this also causes HTML 5 browser-native design elements to appear which is not suitable for my project. 

So the question is how to disable that behavior.

As a workaround, I passed a custom react prop to a component wrapping my input element (`dataType="email"`)

[Related StackOverflow question](https://stackoverflow.com/questions/22358433/enable-html-5-form-validation-but-disable-the-standard-error-message)

**Comment by danihazler** [comment]
<form onSubmit={handleSubmit(onSubmit)} noValidate>

use noValidate

**Comment by bluebill1049** [comment]
thanks @danihazler or you can pass `type="text"` and write a `regex` yourself :)

**Comment by nshaikhinurov** [comment]
Thank you @danihazler! `noValidate` attribute does exactly what I wanted.
