### ISSUE TITLE
Issue with values when working with conditional fields

### ISSUE THREAD

**Issue by redhwannacef** [react-hook-form/react-hook-form#3543]
**Describe the bug**
Hi, hopefully I am not missing something obvious. There seems to be an issue when working with conditional fields. I have a checkbox that dictates the rest of the form (show different fields depending on true/false). The problem is, the value of the first input stays even when is unmounted and the new input appears. In fact, it is not limited to the first input, but just the first n number of inputs that are the same (so if both had 5 text inputs, the values of all would carry over between forms). Not sure if this is clear, but the codesandbox link should help clarify. 

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-conditional-fields-forked-z5kzx?file=/src/index.js
2. Notice there is a default value for the `Dislikes` input.
3. Click on the `More Details` checkbox which should show different inputs.
4. Notice the value for the `Dislikes` input is still there under the newly mounted `Likes` input.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-conditional-fields-forked-z5kzx?file=/src/index.js

**Expected behavior**
When following the above steps, I would expect the mounted `Likes` input to be empty.

**Desktop (please complete the following information):**

- OS: macOS Big Sur version 11.0.1
- Browser: Tested on Google Chrome, Safari, Firefox 
- Version: React Hook Form version 6.11.0

**Comment by redhwannacef** [comment]
Just as an additional note, there are probably a few workarounds:
  - Using css to hide the form instead of unmounting (tested works fine).
  - Maybe have the checkbox outside the form with react state, then mount and unmount two separate forms instead of just the fields within the one form? (not tested)

**Comment by bluebill1049** [comment]
`useForm`'s `defaultValues` will always populate your input's defaultValue (there is no hidden logic to determine when it's first rendered or not), it's the same as doing the following

`<input defaultValue="xxxx" />`

if you want to avoid this behavior use `shouldUnregister: false`

**Comment by redhwannacef** [comment]
Thanks for the reply. I understand the behaviour of `defaultValues` and `shouldUnregister`, but I think I am missing how that helps in this scenario? In the code sandbox example above, regardless of the `defaultValue`/`shouldUnregister` values, I still see the issue where the value that exists in the `dislike` input appears in the `like` input as if it does not realize the input has changed.

**Comment by bluebill1049** [comment]
This is what i meant: https://codesandbox.io/s/react-hook-form-conditional-fields-forked-etg7n
