### ISSUE TITLE
useFieldArray - deleting rows with checkbox inputs

### ISSUE THREAD

**Issue by rudral** [react-hook-form/react-hook-form#3544]
Hi,
When you delete rows from a checkbox-populated fieldArray, the values of the checkboxes are getting messed up.

After opening the [Codesandbox Reproduce Example](https://codesandbox.io/s/react-hook-form-field-arraycheckbox-bug-jg8bu?file=/src/App.js) please follow the instructions to reproduce;
1. Create several rows by pressing the `add` button.
2. Click and make checked the ***middle rows only***.
3. Start deleting the rows ***from the top***. Then you will see the values of checkboxes got messed up.

I think the values stay the same according to the index of the rows, no matter the order of the rows.

I've followed the [documentation ](https://react-hook-form.com/advanced-usage#FieldArrays) exactly but I am not sure if I am missing something or this is a bug. Thanks.

**Comment by bluebill1049** [comment]
make sure you include the `key`

https://codesandbox.io/s/react-hook-form-field-arraycheckbox-bug-forked-g7wrg?file=/src/App.js

https://react-hook-form.com/api#useFieldArray
