### ISSUE TITLE
Yup array error not showing up

### ISSUE THREAD

**Issue by vassbence** [react-hook-form/react-hook-form#3550]
**Describe the bug**
react-hook-form does not register/notice a validation error when a similar yup schema is used: `array.of(...).min(1)`

**To Reproduce**
Select and remove an option from the react-select dropdown and notice that react-form-hook's error object does not have an error for `min(1)` and returns true for `isValid` when the value is an empty array _(= invalid)_.

Also notice that yup correctly returns `false` for the `isValidSync` check when I pass the current state of the form (from `watch()`). I think this confirms that the problem is with react-hook-form and not yup.

[**Codesandbox**](https://codesandbox.io/s/react-hook-form-controller-template-forked-inq4c)

**Expected behavior**
An error should be raised that the array needs at least one item.

**Comment by bluebill1049** [comment]
can you do some debugging with the schema? here is a CSB which I have included some extra logging.

https://codesandbox.io/s/react-hook-form-controller-template-forked-ugbqb?file=/src/index.js

**Comment by vassbence** [comment]
Thanks for the quick reply @bluebill1049. I believe the yup schema is correct in a sense that when given an empty array in gives back an error (you can check this by running isValid as I do in the example). I checked out the extra console.logs you provided in the resolver, the problem is still there, when adding and removing an element the following object is returned from the resolver function:
```
{
  "values": {
    "array": []
  },
  "errors": {}
}
```
The errors object should not be empty.

**Comment by bluebill1049** [comment]
have a look at this file: https://codesandbox.io/s/react-hook-form-controller-template-forked-ugbqb?file=/src/src/yup.ts

which is our yup resolver's logic, it didn't throw an error, with yup's `validate`, let me know if i am missing anything. 👍

**Comment by vassbence** [comment]
All I could find is that if I do not spread the options object on the `schema.validate` on line 70 then react-hook-form too catches the "min 1" error

**Comment by bluebill1049** [comment]
so this is not the issue with hook form. Would you like to submit an issue at yup?

**Comment by vassbence** [comment]
You are absolutely correct. Thank you very much for your time helping me and thanks for creating this awesome package!

**Comment by bluebill1049** [comment]
no worries @vassbence thanks for reporting the issue and the investigation. 👍
