### ISSUE TITLE
valueAsDate rule and datetime-local input resulting in null value

### ISSUE THREAD

**Issue by amankkg** [react-hook-form/react-hook-form#3560]
**Describe the bug**
Input of type `datetime-local` and rule `valueAsDate: true` result in `null` in form values. However, `date` input works as expected.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-forked-xzhhq?file=/src/index.js

**To Reproduce**

1. Edit both fields
2. Submit the form
3. See `null` value in the console

**Expected behavior**
`datetime-local` input value is saved

**Additional context**
Note that `datetime-local` input type is not supported in [some browsers (Firefox, IE, Safari)](https://caniuse.com/?search=datetime-local)

**Comment by bluebill1049** [comment]
your input is not a `date` input, instead of a `datetime` input. This is browser native behavior. 👍

**Comment by amankkg** [comment]
@bluebill1049 so it's only designed for `date` and not `datetime-local`? The latter is also a standard and I would expect it to be supported. As it seems to me, there are no many differences between those two input types, either way, you'll receive a parseable date string. Or do I miss something here?

**Comment by bluebill1049** [comment]
`datetime-local` is not a date input, you can check out the spec and try a native input at codesandbox, just do `e.target.valueAsDate`, we don't do any magic or logic, instead, embrace HTML standard API.
