### ISSUE TITLE
isDirty is not reset when defaultValues is filled

### ISSUE THREAD

**Issue by amanteaux** [react-hook-form/react-hook-form#3562]
**Describe the bug**
When `useForm` is called without `defaultValues`, the `formState.isDirty` works as expected: when a form value is changed, `isDirty=true`, and when this form value is emptied, `isDirty=false`.
However, if some `defaultValues` is provided: when a form value is changed, `isDirty=true`, and when this form value is set back to its initial value, there is still `isDirty=true`.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-forked-jnkvl?file=/src/index.js:196-205

1. Set `a` in the `Mobile number` field => you will see that `isDirty=true` and `dirtyFields` will contain `Mobile number`
2. Empty the `Mobile number` field => you will see that `isDirty=true` and `dirtyFields` will be empty

It works correctly when no default values are provided: https://codesandbox.io/s/7o2wrp86k6?file=/src/index.js

**Expected behavior**
The `isDirty` behavior should be consistent whether some `defaultValues` are provided or not.

**Comment by bluebill1049** [comment]
please make sure to have a full set of default values, we can't assume what's the default value for each input.

<img width="1000" alt="Screen Shot 2020-11-30 at 9 37 05 am" src="https://user-images.githubusercontent.com/10513364/100555440-9dbe5080-32ef-11eb-8117-54b5b3406e90.png">

**Comment by kidroca** [comment]
It seems like a bug to me - `isDirty` is `true` but `dirtyFields` is empty `{}`

**Comment by amanteaux** [comment]
Thank you for your answer and sorry I misread the documentation.

Just to be sure, in the case some incomplete `defaultValues` are provided, what is the goal of `isDirty` not being equal to `objects.keys(dirtyFields).length !== 0`?
Is it because `defaultValues != getValues()` because undefined values are now equals to empty string?
On my side the `isDirty` behavior seems non-intuitive and I am tempted to replace the `isDirty` usage by `objects.keys(dirtyFields).length !== 0`, but I would like to be sure not to miss something important here.

Thank you for your help!

**Comment by bluebill1049** [comment]
@amanteaux that's correct. we are relying on `isDirty` with `defaultValeus` with `deepEqual`, we can't assume input's `defaultValue` when it's not provided, while `dirtyFields` still will get updated when the user changes the input.

**Comment by kidroca** [comment]
If you're using `yup`, and you only have partial defaults - you can get the complete default values using `schema.cast`. 
It will fill missing keys with default values based on the schema definition

```js
const defaultValues = React.useMemo(() => MyYupSchema.cast(partialDefaults), [partialDefaults]);
const form = useForm({ 
  defaultValues, 
  resolver: yupResolver(MyYupSchema),
});
```

**Comment by amanteaux** [comment]
Thank you @bluebill1049 and @kidroca for your answers, it is clear!

**Comment by mackankowski** [comment]
@bluebill1049 I follow similar topics and I cannot figure out how i`sDirty` works now - from one hand we have default values, from the other these values are fetched from the server and filled by `reset`. I followed this sample and with `defaultValues` or not, this form's `isDirty` flag works just fine but it's broken in our whole application. I'm during an investigation but any suggestion will be helpful... I like the library and the work you do, but so a lot of major changes make me freaky. Stay safe!

**Comment by bluebill1049** [comment]
> @bluebill1049 I follow similar topics and I cannot figure out how `isDirty` works now - from one hand we have default values, from the other these values are fetched from the server and filled by `reset`. I followed this sample: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r?file=/src/index.js and with `defaultValues` or without, this form's `isDirty` flag works just fine but it's broken in our whole application. I'm during an investigation but any suggestion will be helpful... I like the library and the work you do, but so a lot of major changes make me freaky. Stay safe!

`isDirty` will do a deepEqual with your defaultValues compare with what's in your form.

<img width="932" alt="Screen Shot 2020-12-11 at 9 46 15 am" src="https://user-images.githubusercontent.com/10513364/101839000-b8b57e00-3b95-11eb-9e66-83a0031d223e.png">

**Comment by mackankowski** [comment]
> > @bluebill1049 I follow similar topics and I cannot figure out how `isDirty` works now - from one hand we have default values, from the other these values are fetched from the server and filled by `reset`. I followed this sample: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r?file=/src/index.js and with `defaultValues` or without, this form's `isDirty` flag works just fine but it's broken in our whole application. I'm during an investigation but any suggestion will be helpful... I like the library and the work you do, but so a lot of major changes make me freaky. Stay safe!
> 
> `isDirty` will do a deepEqual with your defaultValues compare with what's in your form.
> 
> <img alt="Screen Shot 2020-12-11 at 9 46 15 am" width="932" src="https://user-images.githubusercontent.com/10513364/101839000-b8b57e00-3b95-11eb-9e66-83a0031d223e.png">

When no `defaultValues` are provided, the `isDirty` flag works just fine. As I understand, a `defaultValues` object is required (in v6) for `isDirty` working - can you confirm that? My basic sample: https://codesandbox.io/s/rhf6-isdirty-xouil

**Comment by bluebill1049** [comment]
> > > @bluebill1049 I follow similar topics and I cannot figure out how `isDirty` works now - from one hand we have default values, from the other these values are fetched from the server and filled by `reset`. I followed this sample: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r?file=/src/index.js and with `defaultValues` or without, this form's `isDirty` flag works just fine but it's broken in our whole application. I'm during an investigation but any suggestion will be helpful... I like the library and the work you do, but so a lot of major changes make me freaky. Stay safe!
> > 
> > 
> > `isDirty` will do a deepEqual with your defaultValues compare with what's in your form.
> > <img alt="Screen Shot 2020-12-11 at 9 46 15 am" width="932" src="https://user-images.githubusercontent.com/10513364/101839000-b8b57e00-3b95-11eb-9e66-83a0031d223e.png">
> 
> When no `defaultValues` are provided, the `isDirty` flag works just fine. As I understand, a `defaultValues` object is required (in v6) for `isDirty` working - can you confirm that? My basic sample: https://codesandbox.io/s/rhf6-isdirty-xouil

actually no, you just haven't got into a bug with it in v5, it's safer to do a deep compare with `defaultValues`.

**Comment by lilyannh** [comment]
@bluebill1049 Just piggybacking onto this discussion since my problem is similar.  

The deep compare causes false positives in `isDirty` if the `defaultValues` object is not "perfect." In these situations `isDirty` will be set to `true` as soon as you change focus on the form, and `dirtyFields` is still empty.

In my case, I initialize `defaultValues` with a "row" from the database. For example: 
```
{
  id: 1,
  first_name: "Bart",
  last_name: "Simpson",
  note: null
}
```
In a form with the fields for `First Name`, `Last Name`, and `Note`, `isDirty` will be `true` without changing anything because:
- `note` was `null` in defaultValues, but (I think) it gets compared to an empty string from the form
- `id`  exists in defaultValues, but does not exist in the form

I understand the reasoning behind the deep compare, but you can see from the example here that it is also causing some real usability issues.

**Comment by totalard** [comment]
Is there Any Fix ??
