### ISSUE TITLE
More render on handleSubmit

### ISSUE THREAD

**Issue by RemDav** [react-hook-form/react-hook-form#3566]
Hi everybody,

I detected a bug with handleSubmit. When submit with button 'validate', i enter in my function call by handleSubmit.
In function, i'm setState. And i'd two render. it's generate more display bug. I'd find one solution. I wrap setstate function around setTimeOut:
```
setTimeOut(() => {
  setState(true)
}, 0)

```
With solution, i don't the two render.
It's bug or not ?

**Comment by bluebill1049** [comment]
Thanks for the issue.

That's correct and not a bug.

1. first render is to wipe all errors on the page
2. render what's coming from the validation results (Promise resolved)

**Comment by RemDav** [comment]
Hi, than for answer, how fix this problem just for display error ? In my catch I update error state for display the alert. And display two alert.

**Comment by bluebill1049** [comment]
can you share a simple codesandbox to reproduce your issue?

**Comment by RemDav** [comment]
here is my problème: https://codesandbox.io/s/brave-northcutt-j4k5g?file=/src/App.js
I use react-toastify for generate the alert

**Comment by RemDav** [comment]
You can reopen this issue ?

**Comment by bluebill1049** [comment]
thanks @RemDav can you share the steps to reproduce the issue, and what's wrong with your CSB? I will see if this is really an issue with the lib before reopen.

**Comment by RemDav** [comment]
You see the problem with this codepen: https://codesandbox.io/s/brave-northcutt-j4k5g?file=/src/App.js
The user inform his information (login password) if error inside to catch. I change the state error. Or if success change state success (inside handlesubmit). If error or success is true display react toastify but more render. If just console log this state and I see more render. If execute outside handlesubmit the state change one.

**Comment by bluebill1049** [comment]
```

  toast("🦄 Wow so easy!", {
    position: "top-right",
    autoClose: 5000,
    hideProgressBar: false,
    closeOnClick: true,
    pauseOnHover: true,
    draggable: true,
    progress: undefined
  });
```

should this be inside `useEffect` and check formState is submitSuccesfully?

**Comment by RemDav** [comment]
Oh yeah,  i use this fix and corrig this problem. Thank :)
