### ISSUE TITLE
Having a setSuccess function just like setError

### ISSUE THREAD

**Issue by alieslamifard** [react-hook-form/react-hook-form#3567]
**Is your feature request related to a problem? Please describe.**
I'm wondering what if we have a `setSuccess` function to avoid having another state outside of the useForm hook to keep the API call response messages.

**Describe the solution you'd like**
I want to set a success message inside the `onSubmit` function. for now, I can set an extra state using `useState` or just use `setError` with a custom type like `success` (which is not a good way because it will disappear on input changes) or dispatch a success custom alert. but what if we have a `setSuccess` function?

**Describe alternatives you've considered**
having a `setSuccess` function to keep the state of the `onSubmit` event.

**Comment by bluebill1049** [comment]
Thanks for the feature request, I would recommend using that extra state option which you have suggested. However, I will ping on the board for a couple of weeks, see if users pick up with similar requests.
