### ISSUE TITLE
Validation not working for inputs with `type="range"` 

### ISSUE THREAD

**Issue by cornedor** [react-hook-form/react-hook-form#3568]
**Describe the bug**
Validation rules are not working in combination with an input with type range.

**To Reproduce**

1. Open sandbox link
2. Click submit, below the type="number" input an error is shown.
3. Change both values to a high number, another error is shown below the type="number" input
4. Both times no error is shown below the range input

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-forked-dhxsx?file=/src/index.js

**Expected behavior**
The same validation rules that are used with the number input also work with the range input.

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome, Safari, Firefox Developer Edition
- Version 87, 14, 84

**Smartphone (please complete the following information):**

- Device: iPhone X
- OS: iOS 14
- Browser: Safari
- Version: latest

**Additional context**
After some searching I've found this: https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/validateField.ts#L108

The problem might be that range is missing here, but I'm new with this library and want to check here first before I create a PR.

**Comment by bluebill1049** [comment]
thanks fixed: https://github.com/react-hook-form/react-hook-form/commit/5f86d70d154bee9b77c3a3f96dd518c0d750f20a

**Comment by cornedor** [comment]
Nice, thanks.
