### ISSUE TITLE
remove method broken field array

### ISSUE THREAD

**Issue by alexeikaratai** [react-hook-form/react-hook-form#3577]
**Describe the bug**
If we use Controller for field array item we have got broken remove method. If we use register all works. 
**To Reproduce**n

1. Go to 'sandbox'
2. Click on 'append' and append 1,2,3,4 items;
3. Submit in console log 4 elements
4. Remove 3 item and press submit console show 3 elements but 1 and 2 elements undefined

**Codesandbox link (Required)**
[https://codesandbox.io/s/react-hook-form-usefieldarray-forked-s6nvw?file=/src/index.js](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-s6nvw?file=/src/index.js)

**Comment by bluebill1049** [comment]
`item.id` 👍

**Comment by bluebill1049** [comment]
<img width="961" alt="Screen Shot 2020-12-02 at 9 10 58 am" src="https://user-images.githubusercontent.com/10513364/100802895-4c909700-347e-11eb-974b-15d7fda23e8e.png">

**Comment by alexeikaratai** [comment]
@bluebill1049 please see  sandbox, it's doesn't work.

**Comment by bluebill1049** [comment]
please read the doc and follow the example: 

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-c0o1v

https://react-hook-form.com/api/#useFieldArray

**Comment by alexeikaratai** [comment]
@bluebill1049 it is work on 6.11.0 but on upper versions doesn't work. it doest work. [https://codesandbox.io/s/react-hook-form-usefieldarray-forked-c0o1v](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-c0o1v)
1. add 4 items;
2. press submit;
3. remove 3 item;
4. press submit;
error in submit handler function field 

> data  [undefined, undefined, Object]


![image](https://user-images.githubusercontent.com/16285931/100804527-17fceb00-343e-11eb-82db-d78097a89567.png)

**Comment by bluebill1049** [comment]
@alexeikaratai oh i see, i will do some investigation today. thanks

**Comment by bluebill1049** [comment]
issue PR: https://github.com/react-hook-form/react-hook-form/pull/3561

**Comment by bluebill1049** [comment]
patching.

**Comment by IHIutch** [comment]
Im facing a similar issue in 7.9.0, any thought why this would be happening again?

**Comment by IHIutch** [comment]
Im facing a similar issue in 7.9.0, any thought why this would be happening?
