### ISSUE TITLE
Slight inconsistencies in validate API typings / logic

### ISSUE THREAD

**Issue by jonathan-sigma** [react-hook-form/react-hook-form#3580]
There are a few oddities with the current typings and logic around this section of the code that make it awkward for more complex use cases. This is one entry point to demonstrate these issues:

```ts
import { useForm } from 'react-hook-form';

interface FormValues {
  email: string;
}

const INVALID_EMAILS_TYPE = 1

export default EmailForm = () => {
  const { register, handleSubmit } = useForm<FormValues>({ defaultValues: { email: '' } });

  const emailReg = register({
    validate: () => {
      if (INVALID_EMAILS_TYPE === 1) {
        // Fails to result in an error - misses isMessage check
        return ['Invalid email: bad@', 'Invalid email: ~#%']
      } else if (INVALID_EMAIL_TYPE === 2) {
        // Fails Typescript - cannot return Element
        return <div className="invalid-email">Invalid email: No@no@no</div>
      } else {
        return true
      }
    }
  })

  return (
    <form onSubmit={handleSubmit(d => console.log(d))}>
      <input name="email" ref={register(} />
      <input type="submit" />
    </form>
  )
}
```

The issues are as follows:

1. The isMessage check used for the return value of validate does not include string arrays, even though that is allowed for in the `Message` type. This means that returning a string array won't result in a failed validation.

https://github.com/react-hook-form/react-hook-form/blob/master/src/utils/isMessage.ts#L6

2. The `Message` type, as included in `ValidateResult` does not include Element even though that is accounted for in the logic (including isMessage) and gets passed through appropriately.

**Comment by bluebill1049** [comment]
if you are using typescript, please stick with `string` type, JSX is only made for JS. Notice we don't document JSX syntax anywhere in the documentation, and most likely will be removed in the next major version.

**Comment by bluebill1049** [comment]
I will add a note on the documentation to reflect the above.

**Comment by bluebill1049** [comment]
updated in the doc to reflect the comment above: https://github.com/react-hook-form/documentation/commit/10d49bb4cdad808fcaf2c740df7f04ea5e6a5b64
