### ISSUE TITLE
NestedValue does not work with Map

### ISSUE THREAD

**Issue by amcsi** [react-hook-form/react-hook-form#3593]
**Describe the bug**
I want to wrap my `myNestedValue` Map property in NestedValue so I could get `FieldError|undefined` when referencing `errors?.myNestedValue`. But NestedValue can't wrap Map.

**To Reproduce**

Type:
`type MyNestedMap = NestedValue<Map<any, any>>;`

**Codesandbox link (Required)**
I can't get importing of NestedValue to work at all in CodeSandbox.

**Expected behavior**
For the TypeScript to allow it

**Actual behavior**
```
TS2344: Type 'Map<any, any>' does not satisfy the constraint 'unknown[] | Record<string, unknown>'.   Type 'Map<any, any>' is not assignable to type 'Record<string, unknown>'.     Index signature is missing in type 'Map<any, any>'.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/116494/101022451-b50c7080-3571-11eb-9f73-234c9e7e7a7a.png)

**Additional Information**

I think this PR might have caused this to not work anymore. It seems like before this PR, what I'm trying to do would have worked: #2635

**Comment by amcsi** [comment]
@bluebill1049
Thanks for fixing the Map at least for string keys.
In the fix, why is it being restricted to string key maps only? I want to use NestedValue, because I don't want my Map to be treated as a leaf in the data tree, thus it shouldn't matter what type the keys are.

**Comment by gavinwahl** [comment]
This seems to be happening again
