### ISSUE TITLE
Validation mistake

### ISSUE THREAD

**Issue by ELEliseev** [react-hook-form/react-hook-form#3598]
Hello. I found a small bug in the react-hook-form validation system.
If the name of the input is a string that contains dots, then the errors object perceives the name of the input as an object and the validation does not work.
<input   name={name} ref={register({ validate: validateForm})}    />
                    { errors[name] && <p>"Error"</p>}

where    name="word.word.word"

<input   name={name.replaceAll(".", "_")} ref={register({ validate: validateForm})}    />
                    { errors[name.replaceAll(".", "_")] && <p>"Error"</p>}
This solves the problem.
Thanks! I like react-hook-form

**Comment by bluebill1049** [comment]
can you reproduce the issue here: https://codesandbox.io/s/charming-robinson-4z4ii?file=/src/App.js?

**Comment by ELEliseev** [comment]
Yes.
https://codesandbox.io/s/cold-rgb-ib3cl?fontsize=14&hidenavigation=1&theme=dark

**Comment by bluebill1049** [comment]
<img width="1115" alt="Screen Shot 2020-12-04 at 6 04 43 pm" src="https://user-images.githubusercontent.com/10513364/101132486-325fe000-365b-11eb-82e9-73bfce64319a.png">
What's the issue?

**Comment by ELEliseev** [comment]
Error does not visible

**Comment by bluebill1049** [comment]
it's a deep nested object, `test.test.test` not `test[test.test]`

**Comment by ELEliseev** [comment]
Yes, everything is correct, but how to make the error work if the name contains points? I apologize if I didn't understand something

**Comment by bluebill1049** [comment]
use lodash `get` or error?.test?.test 👍
