### ISSUE TITLE
Rename register({ validate }) to validator or getErrorMessage

### ISSUE THREAD

**Issue by devinrhode2** [react-hook-form/react-hook-form#3599]
I am creating a company-specific wrapper around RHF. I think RHF a very nice form library that can help with performance. It's important that the lower level code is fast so that users are not punished quite much when they make mistakes. I have no problems with the library.

I think the name `validate` is not the best for `register({})` option. I think a better name would be `validator`, but I think `getErrorMessage` is an even better name. Consider:
```ts
<TextField
  name={name}
  ref={register({
    validate: createGetErrorMessageFn({ // I may also call this 'createValidator'
      isValidProp,
      // data from CMS with { fieldIsValid: 'you cannot be born in future', fieldIsRequired: 'birthday is required' }
      errorMessageContent
    })
  }/>
```
I have a sort of naming clash, I couldn't decide on the best names for my utilities, and realized the `validate` name just isn't the best name.

It's quite a subjective thing, so I don't want to share a whole bunch of code, since my code is only specific to my situation.

Even if you are passing in an object to `validate`, I think it's still not the best name, but I don't really pass in sets of validator functions, am not so concerned about that variation of this api.

Thumbs Up 👍 ` => ` let's improve this api/it's naming
Thumbs Down 👎 ` => ` don't change a thing

If we get even even 50% thumbs up, I think we should consider improving this api/it's naming

**Comment by bluebill1049** [comment]
Thanks for the suggestion. We will consider that in the future major release, but at the moment, we probably not going to introduce a breaking change.

**Comment by devinrhode2** [comment]
Ok cool, thanks Bill! Feel free to close/categorize this as you see fit :)

**Comment by bluebill1049** [comment]
Thanks for understanding, will bring this up in the next major version.
