### ISSUE TITLE
Once click on submit handler. Its not re-validating

### ISSUE THREAD

**Issue by nageshwari17** [react-hook-form/react-hook-form#3600]
**Describe the bug**
I am using react-form-hooks  to control over form element .

Once click on handle submit there is a requirement in my application show the confirmation box (dialog box) with all details . If all the field values are correct you can go ahead to submit . If not simply close the confirmation box and edit the fields again .

here reack- hook-form is failing . its not validation form properly even with empty field also isValid returning true and not triggering validate rule onBlur .

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by nageshwari17** [comment]
@bluebill1049  . Please find sample code in below link

https://codesandbox.io/s/epic-shadow-loo8k?file=/src/App.js

**Comment by bluebill1049** [comment]
you have set the validation to be `onSubmit`

`const methods = useForm({ mode: "onBlur", reValidateMode: "onSubmit" });`

<img width="1003" alt="Screen Shot 2020-12-05 at 11 38 48 am" src="https://user-images.githubusercontent.com/10513364/101228132-7223d780-36ee-11eb-8e76-bf6ad18c0f75.png">
