### ISSUE TITLE
Default values of disabled inputs are ignored

### ISSUE THREAD

**Issue by Bastian** [react-hook-form/react-hook-form#3601]
**Describe the bug**

Having an input field marked as disabled but with a default value, the default value is not included in the data object of `onSubmit`. If the `Controller` is used, it works as expected.

**To Reproduce**

1. Look at the codesandbox linked below
2. Enter a value in the first input field (optional)
3. Click on Submit

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

- https://codesandbox.io/s/react-hook-form-js-forked-6rrtw?file=/src/App.js

**Expected behavior**

The value of the disabled field should be included in the data object. At least it should not make a difference if a `Controller` is used or not.

**Desktop:**

- OS: Linux 
- Browser: Chrome v86.0.4240.183

**Additional context**

This does also affect validation, e.g. if the field is required to not be empty.
![image](https://user-images.githubusercontent.com/5033001/101154000-6e784e00-3625-11eb-8529-7f45e2119feb.png)

**Comment by bluebill1049** [comment]
Take a look at this tweet: https://twitter.com/bluebill1049/status/1300231640392716288

**Comment by Bastian** [comment]
Thank you very much, I wasn't aware about the difference.
However, I don't fully understand why it behaves differently when a `Controller` is used?

**Comment by bluebill1049** [comment]
`Controller` is not a native input, it's basically a controller input.

**Comment by Bastian** [comment]
Thank you :)
