### ISSUE TITLE
Unmounting while async onSubmit handler is running causes state update on unmounted component error

### ISSUE THREAD

**Issue by jmmoser** [react-hook-form/react-hook-form#3603]
**Describe the bug**
If the onSubmit handler is async and the form is unmounted while the handler is running then a "Can't perform a React state update on an unmounted component." warning is logged to the console once the handler finishes.

**To Reproduce**

1. Go to codesandbox link
2. Click on Submit button
3. Click on "Toggle Show Form" button in less than 3 seconds
4. See error in console

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-useform-template-forked-5bkz6?file=/src/index.js

**Expected behavior**
User does not update state in the form component so no error should be logged.

**Desktop:**

- OS: macOS 11.0.1
- Browser: chrome
- Version: 87.0.4280.88

**Comment by bluebill1049** [comment]
This is not an issue with the prod build, we avoid the ref unmounted check at dev build for fast refresh.

**Comment by dwiyatci** [comment]
@bluebill1049 Just to double-check/clarify: so you're saying that this warning is expected/safe to ignore during development, correct?

**Comment by bluebill1049** [comment]
> @bluebill1049 Just to double-check/clarify: so you're saying that this warning is expected/safe to ignore during development, correct?

yes, correct.

**Comment by sethbro** [comment]
Is this documented anywhere, or can the unmounted check be turned on in dev? 

It seems strange to me to (1) vary behavior based on the implementer's environment, and (2) to allow it to *appear* that a memory leak may be present. I just started working with this library, & I *love* it, but it may be hard to assure coworkers, "Don't worry about that warning message—it's not 'real'".

**Comment by bluebill1049** [comment]
> Is this documented anywhere, or can the unmounted check be turned on in dev?
> 
> It seems strange to me to (1) vary behavior based on the implementer's environment, and (2) to allow it to _appear_ that a memory leak may be present. I just started working with this library, & I _love_ it, but it may be hard to assure coworkers, "Don't worry about that warning message—it's not 'real'".

Thanks for the feedback. I will include that in the doc. Here is the problem: input `ref`'s callback doesn't get invoked again with fast refresh because none of the inputs unmounted.

**Comment by bluebill1049** [comment]
FAQ new section included with the following commit: https://github.com/react-hook-form/documentation/commit/7d983dc564c924b7d4bae2f7b7c8877a6147f8fa

**Comment by mlarcher** [comment]
Those warnings are cluttering our test suite output, making more important warnings less noticeable. Is there anything we can do to avoid that ?

**Comment by bluebill1049** [comment]
> Those warnings are cluttering our test suite output, making more important warnings less noticeable. Is there anything we can do to avoid that ?

can you share the test case? I will take a look at it. you can set env to prod to avoid this error tho.

`process.env.NODE_ENV = 'production';`

we do that in our test as well for testing warning messages.

**Comment by mlarcher** [comment]
Here is an example of a test triggering the warning :
```jsx
import React from 'react';
import { fireEvent, render, screen } from '@testing-library/react';
import { Route, Router } from 'react-router-dom';
// eslint-disable-next-line import/no-extraneous-dependencies
import { createMemoryHistory } from 'history';

import { mockCredentials, MockedProvider, unmockCredentials, waitForPageLoaded } from '../../../../testing/helpers';
import CompanyOfferCreate, { CREATE_OFFER } from '../CompanyOfferCreate';
import AuthProvider from '../../AuthProvider';
import routes from '../../../constants/routes';

describe('CompanyOfferCreate', () => {
  const componentPath = '/test';
  const history = createMemoryHistory();

  beforeEach(() => {
    history.replace(componentPath);
    mockCredentials();
  });
  afterEach(() => {
    unmockCredentials();
  });

  const redirectedContent = 'redirected_route_content';

  const defaultCreateOfferInput = {
    title: '',
  };

  const defaultCreateOfferMock = jest.fn().mockReturnValue({
    data: {
      createOffer: {
        id: '1318',
        __typename: 'Offer',
      },
    },
  });

  function setup({ createOfferMock = defaultCreateOfferMock, createOfferInput = defaultCreateOfferInput } = {}) {
    const mocks = [
      {
        request: {
          query: CREATE_OFFER,
          variables: {
            input: createOfferInput,
          },
        },
        result: createOfferMock,
      },
    ];

    return render(
      <AuthProvider>
        <MockedProvider mocks={mocks} addTypename={false}>
          <Router history={history}>
            <Route exact path={routes.COMPANY_OFFERS} render={() => (<div>{redirectedContent}</div>)} />
            <Route exact path={componentPath} component={CompanyOfferCreate} />
          </Router>
        </MockedProvider>
      </AuthProvider>,
    );
  }

  it('should successfully create an offer', async () => {
    // ARRANGE

    // ACT
    setup();
    await waitForPageLoaded();

    fireEvent.click(screen.getByText("Créer l'offre"));
    await waitForPageLoaded();

    // ASSERT
    expect(defaultCreateOfferMock).toHaveBeenCalled();
  });
});
```
and code for the component is :
```tsx
import React from 'react';
import { useForm } from 'react-hook-form';
import { Redirect } from 'react-router-dom';
import { gql, useMutation } from '@apollo/client';
import { formButtonsDefaultStyle, formInputDefaultStyle } from '../../constants/styleConstants';
import { ButtonsWrapper } from '../shared/FormElements';
import CTAButton from '../shared/buttons/CTAButton';
import SimpleInput from '../shared/inputs/SimpleInput';
import routes from '../../constants/routes';

export const CREATE_OFFER = gql`
  mutation createOffer($input: CreateOfferInput!) {
    createOffer(input: $input) {
      id
    }
  }
`;

const CompanyOfferCreate: React.FC = () => {
  const { handleSubmit, errors, control } = useForm();

  const [createOffer, { data: saveData, error: saveError }] = useMutation(CREATE_OFFER);

  async function onSubmit(formData: any): Promise<void> {
    await createOffer({
      variables: {
        input: formData,
      },
    });
  }

  if (saveData && !saveError) {
    return <Redirect push to={{ pathname: `${routes.COMPANY_OFFERS}` }} />;
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} data-testid="createOfferForm">
      <SimpleInput
        inputId="title"
        name="title"
        errors={errors}
        control={control}
        label="Titre de l'offre*"
        help="Ce champ ne sera visible uniquement par votre entreprise"
        style={formInputDefaultStyle}
        maxLength={100}
      />
      <ButtonsWrapper style={formButtonsDefaultStyle} position="left">
        <CTAButton>Créer l'offre</CTAButton>
      </ButtonsWrapper>
    </form>
  );
};

export default CompanyOfferCreate;
```
I tried setting NODE_ENV to production, but it seems react-scripts is overriding it later on, so it is always on "test"

**Comment by tbrannam** [comment]
Looking for NODE_ENV in the release package seems to show no matches - so I'm not sure how this workaround would ever work.
