### ISSUE TITLE
Field with Controller wrapper does not reset

### ISSUE THREAD

**Issue by crabn3bula** [react-hook-form/react-hook-form#3604]
**Describe the bug**
Hello, sorry to bother you. I'm not entirely sure if this is a bug. 

I am currently trying to make a form that contains custom components, in my case it is third-party datepicker.
At first glance, everything works, but I noticed that when the form is reset, the datepicker visually resets its value, but it remains in the form's state.

I thought that I just did something wrong and went to read the documentation about the controller and reset method. There is your [example](https://codesandbox.io/s/react-hook-form-v6-controller-ts-4dpm9) from the sandbox, in which this situation is repeated.

**To Reproduce**

1. Go to [sandbox](https://codesandbox.io/s/react-hook-form-v6-controller-ts-4dpm9)
2. Select a date from ReactDatepicker
3. Click on 'Submit'
4. Look at the results, field 'ReactDatepicker' contains a value
5. Click 'Reset Form'
6. Then again click 'Submit'. As you can see ReactDatepicker clears his value, but the form state is still contains old value 

**Expected behavior**
Form state must match the visual representation of the form

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Mozilla Firefox
- Version 83.0

Same for Chrome 86.0

**Comment by bluebill1049** [comment]
This should work now, miss-spelled the value name: 

https://codesandbox.io/s/react-hook-form-v6-controller-ts-4dpm9?file=/src/index.tsx:5561-5576

**Comment by crabn3bula** [comment]
Yep. This work fine now and i was find a bug in my code too. Thanks for the help!

**Comment by bluebill1049** [comment]
no problem 👍
