### ISSUE TITLE
Bug | Watching full value of useFieldArray doesn't work. 

### ISSUE THREAD

**Issue by ssuvorov** [react-hook-form/react-hook-form#3605]
Watching full useFieldArray doesn't work. 

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-forked-3rnvf?file=/src/index.js
2. Change dropdown's value
3. open a console
4. compare values

A correct value
`console.log(useWatch({ name: "steps[0].type", control }));` 

An old value
```
const stepsValues = useWatch({ name: "steps", control });
console.log(stepsValues[0].type);
```

**Comment by bluebill1049** [comment]
Thanks for the issue, please wrapped FieldArray correctly: https://codesandbox.io/s/react-hook-form-usefieldarray-forked-c3z0j?file=/src/index.js

**Comment by ssuvorov** [comment]
@bluebill1049 no sure if this is the right way. What if you want to display the 2nd dropdown at the same component based on these values?

**Comment by bluebill1049** [comment]
> @bluebill1049 no sure if this is the right way. What if you want to display the 2nd dropdown at the same component based on these values?

You move that `Controller` component inside `<Test />` right?

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-c3z0j?file=/src/index.js

**Comment by bluebill1049** [comment]
just a quick follow up on the above solution.

**Comment by ssuvorov** [comment]
@bluebill1049 I have a very complicated form with a funnel solution. And still migrating it to react-hook-form. Of course, your suggestion works, but it's not intuitive. I'll comment on this issue once I have more free time and dive deeper in comparison. Sorry about that.

**Comment by bluebill1049** [comment]
> @bluebill1049 I have a very complicated form with a funnel solution. And still migrating it to react-hook-form. Of course, your suggestion works, but it's not intuitive. I'll comment on this issue once I have more free time and dive deeper in comparison. Sorry about that.

no worries @ssuvorov let me know.
