### ISSUE TITLE
Custom error message alongside custom validation

### ISSUE THREAD

**Issue by jgb-solutions** [react-hook-form/react-hook-form#361]
Wasn't sure whether this was an issue so I post it as a feature.

I'm just getting started with this package and i already like it. For the sake of keeping related things closed,  is it possible to keep custom error messages alongside a custom validation method just like `required` or `min` or `max`? And if not I think that would be a nice feature to have. Would reduce the number of `type` comparison to display the error messages.

 Thanks!

**Comment by bluebill1049** [comment]
Thank you for your kind words! 👍 so glad to hear you like it.

hahaha YES, and it's documented: 

https://react-hook-form.com/api#register

check the checkbox of  `Register with validation and error message`

**Comment by jgb-solutions** [comment]
nice! Awesome. I found it. I'm actually using React Final Form, that's from the same author of Redux Form and it's pretty lightweight. And  today i found this package from the react newsletter and I already like it by just reading the docs. it seems pretty lightweight and has a nice 
API. How does it compare to React Final Form?

**Comment by bluebill1049** [comment]
hahaha tough question. 

One thing I can be pretty confident to say, react hook form is simple and DX focus. every project is about pros and cons. my focus will be on the developers' experience. Keep API simple and great documenation.

**Comment by jgb-solutions** [comment]
very wise answer! nice work man! I'm going to try it out tonight.

**Comment by bluebill1049** [comment]
sounds good @jgb-solutions feedback welcome! going to close this issue now :)
