### ISSUE TITLE
Expose error in Controller render prop

### ISSUE THREAD

**Issue by zoontek** [react-hook-form/react-hook-form#3615]
Hi 👋

Would it be possible to exposes `error` in the `<Controller />` render prop?

**Is your feature request related to a problem? Please describe.**

Our custom `Input` handle the error display by itself (in a tooltip), and accessing `error` directly from the render prop would be easier to handle, and probably more elegant / performant.

**Describe the solution you'd like**

Just adding the `error` value. Something like this:
**P-S:** Adding `touched` could be nice too! 🙂

```tsx
import * as React from "react";
import { Controller, useForm } from "react-hook-form";
import "./styles.css";

export default function App() {
  const { control } = useForm({
    reValidateMode: "onBlur",
    defaultValues: { firstname: "" }
  });

  return (
    <div className="App">
      <Controller
        control={control}
        name="firstname"
        render={({ error, onBlur, onChange, value }) => (
          <Input
            value={value}
            onChange={onChange}
            error={error}
            onBlur={onBlur}
          />
        )}
      />
    </div>
  );
}
```

**Describe alternatives you've considered**

None, it's an API change. But if you need it, I could write a PR.

**Additional context**

Our `Input` component (with error details on icon hover):

<img width="554" alt="Screenshot 2020-12-07 at 10 18 01" src="https://user-images.githubusercontent.com/1902323/101332430-8fcf7900-3875-11eb-8ef5-7cb38795b3cc.png">

**Comment by bluebill1049** [comment]
hey @zoontek should coming soon, i will be working on it this weekend if I don't hear anymore negative feedback: https://github.com/react-hook-form/react-hook-form/discussions/3487

**Comment by bluebill1049** [comment]
`<Controller render={(props, state) => console.log(state.InValid)} />`

**Comment by zoontek** [comment]
@bluebill1049 That would be perfect! Thanks for the fast answer 👍

**Comment by bluebill1049** [comment]
No worries :) 

```
{
      inValid: !get(errors, name),
      isDirty: !!get(dirtyFields, name),
      isTouched: !!get(touched, name),
    }
```

the above will be exposed. 👍
