### ISSUE TITLE
Bug | Wiriting 'append' in 'useEffect' will render infinitely

### ISSUE THREAD

**Issue by yamakeeeeeeeeen** [react-hook-form/react-hook-form#3617]
**Describe the bug**
Wiriting 'append' in 'useEffect' will render infinitely
Ths bug has happened since version 6.11.2

**To Reproduce**

1. Go to 'https://codesandbox.io/s/react-hook-form-usefieldarray-forked-d49x5?file=/src/index.js'

**Expected behavior**

I don't want it to re-render even if the 'fields' have been updated.

**Additional context**

The one released in version 6.11.2 was what I wanted.
But there were effects elsewhere.

https://github.com/react-hook-form/react-hook-form/releases/tag/v6.11.2
https://github.com/react-hook-form/react-hook-form/issues/3450

**Comment by yamakeeeeeeeeen** [comment]
@bluebill1049 
Since this part is required in the production, is it possible to have it released?

**Comment by bluebill1049** [comment]
Hey @yamakeeeeeeeeen I will release a beta for you, I try to avoid publishing during weekdays (mostly weekends) due to work, if anything wrong I can't patch it quickly.

**Comment by yamakeeeeeeeeen** [comment]
@bluebill1049 
Okay.
Thanks for the beta release.

**Comment by bluebill1049** [comment]
here is the beta version: "version": "6.12.3-beta.2",
