### ISSUE TITLE
MUI Checkboxes completely broken >= 6.03

### ISSUE THREAD

**Issue by technicallynick** [react-hook-form/react-hook-form#3629]
**Describe the bug**
When using a `<Controller />` component to render a [MUI Checkbox](https://material-ui.com/api/checkbox/), the value is returned as a string but beyond that, even though the checkbox performs correctly in the browser, the logged value is always `"false"`. 

**To Reproduce**

1. Fork the [Controller (MUI, React-Select and etc) Example](https://codesandbox.io/s/react-hook-form-controller-079xx) from the Example page or go to [my fork](https://codesandbox.io/s/react-hook-form-controller-forked-8sln1?file=/src/index.js).
2. Add `watch` to the list of destructured functions from `useForm()`, create a variable to assign this value to, and log this variable before the return/render statement.
3. Click on the checkbox and see proper boolean returns.
4. Update the react-hook-form package from the saved version of 5.5.1 to >= 6.0.3
5. Click on the checkbox and see it always return "false"

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-forked-8sln1?file=/src/index.js

**Expected behavior**
Logged watch should show the boolean of the current value rather than a static string.

**Desktop (please complete the following information):**

- OS: Mac OS 10.15.7
- Browser: Chrome
- Version: 87

**Comment by bluebill1049** [comment]
hey there, please use `render` prop for checkbox: https://react-hook-form.com/api#Controller 

there is a working version in this CSB: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r
