### ISSUE TITLE
onChange mode doesn't work with array of objects

### ISSUE THREAD

**Issue by dextervip** [react-hook-form/react-hook-form#363]
Hello,

onChange mode doesn't work with array of objects. It only validates on submit. For example, on the code below, location is validaded correctly as soon as I type anything but the array of persons doesnt fire up validation while I type anything. It only shows me validation erros when I submit. Any clues? Regards

```
const schema = yup.object().shape({
    location: yup.string().required().min(4),
    persons: yup
        .array()
        .required()
        .of(
            yup.object().shape({
                name: yup.string().required().min(4),
            })
        )
});

const { register, errors, handleSubmit } = useForm({
      mode: 'onChange',
      validationSchema: schema
});


<div className="form-group input-sm">
	<div className={"col-sm-12 " + (errors["persons[0].name"] ? 'has-error' : '')}>
		<input type="text" className="form-control" placeholder="name" name="persons[0][name]" 
			   ref={register}/>
		{errors["persons[0].name"] ? (<div>
			<span className="form-control-feedback" aria-hidden="true"><i className="fa fa-remove"></i></span>
			<span className="help-block">{errors["persons[0].name"].message}</span>
		</div>) : ''}
	</div>
</div>
```

**Comment by bluebill1049** [comment]
can you convert this code into a codesandbox?

**Comment by dextervip** [comment]
@bluebill1049 Here go https://codesandbox.io/embed/react-hook-form-validationschema-3y6c7
If you type in location field, you will see validation message instantly but if you type in name which must represent a array of objects person. You wont see any message, except if you click submit.

**Comment by bluebill1049** [comment]
Thanks I will take a look this soon

**Comment by bluebill1049** [comment]
if you update your name to be the following

 `name="persons[0].name"` which is same as your error name

should be working for you.

**Comment by dextervip** [comment]
It works, thx! however my error messages are not nested objects as location field. It becames a flat key. I must use errors["persons[0].name"].message instead of errors.persons[0].name.message. Any way to code it as nested objects in case I need to iterate all validation messages? For example a tag list plugin in a text field would generate different message keys for each validated tag.

**Comment by bluebill1049** [comment]
@dextervip I try to avoid that for now, because your code will run into object undefined, at the moment, I think `erros[${name}]` is a safer choice.

**Comment by dextervip** [comment]
@bluebill1049 Okay! thank for your support!

**Comment by bluebill1049** [comment]
no worries @dextervip
