### ISSUE TITLE
`setValueAs` seems not working with `required` option

### ISSUE THREAD

**Issue by tommy1994111** [react-hook-form/react-hook-form#3630]
**Describe the bug**
Define `setValueAs` and `required` in `register` function, then trigger `handleSubmit` seems that `setValueAs` is bypassed.

**To Reproduce**

1. register input field
```
register({
  required: true,
  setValueAs: value => value.trim()
})
```
2. type space in the input
3. trigger `handleSubmit`
4. See console.log

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-validation-setvalueas-forked-ehp4k

**Expected behavior**
`handleSubmit` shouldn't fire the callback and the `errors` object should have the error information.

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS 10.15.7
- Browser: chrome
- Version: 87.0.4280.88

**Smartphone (please complete the following information):**

- Device: iPhone SE (2020 ver.)
- OS: iOS 14.2
- Browser: chrome
- Version 87.0.4280.77

**Additional context**
I saw the [RFC](https://github.com/react-hook-form/react-hook-form/discussions/3495) and noticed the **Important Notes**

> validation will run against the transformed value instead of what's in the view.

The `validate` option in `register()` is working with `setValueAs`, do I misunderstanding the "validation" in the Important Notes ?

**Comment by bluebill1049** [comment]
validation is going to trigger before `valueAs`, you should use `valdiate` function instead. `valueAs` is only applicable for the value itself.

**Comment by bluebill1049** [comment]
`setValueAs` is for retrieve value, it's not invoked before validation, if you need validation use `validate` function instead.

**Comment by tommy1994111** [comment]
Got it, Thanks a lot.
But I didn't see any information about this in the document, could you add some information to the document?

**Comment by bluebill1049** [comment]
will do 👍

**Comment by bluebill1049** [comment]
<img width="946" alt="Screen Shot 2020-12-09 at 6 46 28 pm" src="https://user-images.githubusercontent.com/10513364/101600045-ddeba480-3a4e-11eb-95bf-f3bd18a038cd.png">

updating and deploying.

**Comment by JoshuaCS94** [comment]
@bluebill1049... _valueAs process is happening **after** validation_? thats not what the [v6 docs](https://react-hook-form.com/v6/api/#register) says...

**Comment by DevDaveJ** [comment]
@bluebill1049 @JoshuaCS94 
Yep. Definitely says **_before_** validation in the documentation...

![image](https://user-images.githubusercontent.com/68554476/148637293-c9b90fa1-66e1-480a-b218-3d2e5f4dfb0b.png)

**Comment by DevDaveJ** [comment]
> `setValueAs` is for retrieve value, it's not invoked before validation, if you need validation use `validate` function instead.

Nope. Don't need it for validation, in my use case I want to trim leading and trailing whitespace **_before_** validation.

**Comment by xepozz** [comment]
I need to transform value **before** validation.
As I can see in the [documentation](https://react-hook-form.com/api/useform/register) the `setValueAs` should do it, but it doesn't.

<img width="853" alt="image" src="https://user-images.githubusercontent.com/6815714/168730704-b81e242f-b5d2-4024-87af-f85e57a3174d.png">

I want to use the rest rules with pre-transformed value. Of course I can write my own validate function and implement such of rules, but it looks like overengineering.

**Comment by redvelvet-fan** [comment]
In My Case Only Interger
```typescript

const formhook = useForm();
const { getValues,setValue } = formhook

const numberOnlyRegex = /[^0-9]/g;
`
const myChangeFunctions = (name : string) => {
    const originText = getValues()[name];
    const numberOnlyText = text.replace(numberOnlyRegex,"")
    setValue(name,numberOnlyText)
}
<input 
    {...register(name,{
        onChange : () => {
            myChangeFunctions(name)
        },
    })}
/>
```
