### ISSUE TITLE
Updating defaultValues won't update the form (useForm)

### ISSUE THREAD

**Issue by kbrah** [react-hook-form/react-hook-form#3638]
**Describe the bug**
If defaultValues are changed, the form does not update it's data. 

**To Reproduce**

1. Take defaultValues from the props and give it to useForm
2. update the prop somewhere else to cause the component to update
3. See that the form does not update it's values

**Codesandbox link (Required)**
[codesandbox](https://codesandbox.io/s/react-hook-form-useform-template-forked-tfruk?file=/src/index.js)

**Expected behavior**
The form should render with new defaultValues

**Desktop (please complete the following information):**
Windows, Chrome

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api

read the doc, if you need to update form values, use `reset`
<img width="1004" alt="Screen Shot 2020-12-09 at 8 35 00 pm" src="https://user-images.githubusercontent.com/10513364/101611762-03cc7580-3a5e-11eb-90a3-026a433ea16b.png">

**Comment by kbrah** [comment]
Sorry, my bad!

I would however add to this that it feels a little bit unintuitive. It would be nice if it was a configurable feature and not the default behavior. Unless of course there is a good reason for it to be the default behavior.

**Comment by dimaqq** [comment]
I too would like to re-render (hook re-call) with different defaultValues to change those fields that were not edited by the user.

I suppose I have to hack up reset+omit based on whether individual field was edited... But then I'm not sure how to handle 1. focused field that was not changed and 2. field that is being changed but was never blurred.
