### ISSUE TITLE
Reset does not work as expected on component initialized with Controller

### ISSUE THREAD

**Issue by clement-faure** [react-hook-form/react-hook-form#3639]
**Describe the bug**
Form is not reseted as expected when fields are initialized with Controller

**To Reproduce**

1. Go to sandbox link
2. Type custom value in input field
3. Try resetting the form
4. Old value is still here

**Codesandbox link (Required)**
https://codesandbox.io/s/fancy-flower-mog4f?file=/src/App.js

**Expected behavior**
In case when are resetting with empty object, all fields in this object should be reseted.

**Desktop (please complete the following information):**

- OS: IOS
- Browser: chrome
- Version: Version 87.0.4280.88

**Comment by bluebill1049** [comment]
we don't support such usage. In other words, we don't look into the nested objects and seek what's inside an object of fields (no magic). Users need to define the fields that need to be reset to.

**Comment by clement-faure** [comment]
Ok.. well noted! Thank you for you quick response.

Would it be possible to support at least "undefined" : 

```
{
  properties: {
    custom: {
      aaaa: undefined
    }
 }
}
```

**Comment by bluebill1049** [comment]
`Controller` strictly try to avoid `undefined`, you can consider set to an empty `string`.

**Comment by clement-faure** [comment]
The strange part is that feature is currently supported when initialize fields with **register**

**Comment by bluebill1049** [comment]
> The strange part is that this feature is currently supported when initialize fields with **register**

There is a bit difference between `register` and `Controller`.

`register` is actually a real uncontrolled input, while `Controller` is actually a wrapper with `controller` input, so we need to determine what's the initial value for `Controller`, we don't have the issue with native input (`register`)

**Comment by clement-faure** [comment]
Ok thank you, i'll have to specify all values in my reset function then. 

Thank you for you time, and this awesome lib !

**Comment by bluebill1049** [comment]
> Ok thank you, i'll have to specify all values in my reset function then.
> 
> Thank you for you time, and this awesome lib !

Thank you for your understanding. Less magic,  less code, less bug from this simple lib.
