### ISSUE TITLE
Yup Resolver with .when / dependent field validation

### ISSUE THREAD

**Issue by redgumnfp** [react-hook-form/react-hook-form#3642]
**Describe the bug**
Not 100% whether this is a bug, or a feature, but when using conditional validation, such as a `.when` within a Yup resolver, the validation process does not re-run for the dependent fields.

It appears to only run `onChange`/`onBlur` of the respective field, when the `trigger` function is run, or on `Submit`. This is likely for performance reasons to mitigate re-renders. 

As the errors object is not updated, it does not amend the props of the Input components, meaning that the visual error message is not shown until submit or if triggered to run conditionally.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-template-forked-nkg6m?file=/src/index.js

**To Reproduce**
Using the above code sandbox:

1. Enter a FirstName of TEST
2. See that LastName does not have an error
3. Click Submit
4. See that LastName does have an error
5. Amend FirstName
6. See that LastName still has an error (as that field wasn't changed)
7. Click Submit, see that error is resolved

**Expected behavior**
Set the errors object for the whole form when validating.

**Additional context**
I've found a suitable work-around:
https://codesandbox.io/s/react-hook-form-controller-template-forked-czifs?file=/src/index.js

This essentially watches the relevant field(s), and if changed (useEffect hook), triggers a re-validation.

So I've completely rubber-ducked my bug (kudos), but I'm still wondering if this is the best solution to the issue, and if so, it could be a useful example for your documentation.

**Comment by bluebill1049** [comment]
react hook form focus input field validation for better perf rather than trigger the entire form each input. u will probably have to use `trigger` with `onChange` or `onBlur`.

**Comment by redgumnfp** [comment]
Sure, that makes sense. I guess you can do it either way, but a bit more straight-forward with the trigger and onChange/onBlur.

Thanks for your feedback
