### ISSUE TITLE
How to use forwardRef when 'register' is using 'ref' ?

### ISSUE THREAD

**Issue by marrkeri** [react-hook-form/react-hook-form#365]
Hello,
here is my demo app: https://codesandbox.io/s/react-hook-form-smart-form-component-fi7nl

I have injected field with register, but it uses ref to be able to cooperate with field.
But I have scenario where I have to do focus into the field after some action/button click.

Code
```
const App = () => {
  const inputRef = useRef();

  const onSubmit = data => alert(JSON.stringify(data));

  const boxFocus = e => {
    e.preventDefault();
    alert("clicked but not focused");
    if (!inputRef || !inputRef.current) return;
    inputRef.current.focus();
  };

  return (
      <Form onSubmit={onSubmit}>
         <InputWitForwardedRef name="testRef" ref={inputRef} />
      </Form>
  )
}
```
Form is traversing children and injecting 'register'
InputWitForwardedRef is wrapped into forwardRef, but because register is used for ref, I can't put there both.
```
export const InputWitForwardedRef = forwardRef((props, ref) => {
  // TODO !!! HOW TO USE 'ref' ??? If I use 'ref' instead of 'register' it works.
  const { register, name, ...rest } = props;
  return <input name={name} ref={register} {...rest} />;
});
```

Thanks

**Comment by marrkeri** [comment]
I have tried also something from this link but it doesn't work https://github.com/react-hook-form/react-hook-form/issues/25:
```
export const InputWitForwardedRef = forwardRef((props, ref) => {
  // TODO !!! HOW TO USE 'ref' ??? If I use 'ref' instead of 'register' it works.
  const { register, name, ...rest } = props;
  return <input name={name} ref={inputRef => {
    ref = inputRef
    register(inputRef)
  }} {...rest} />;
});
```

**Comment by bluebill1049** [comment]
@marrkeri should be much simpler right?
```
const FancyButton = React.forwardRef((props, ref) => (
  <button ref={ref} className="FancyButton">
    {props.children}
  </button>
));
```

**Comment by marrkeri** [comment]
Sorry, I'm not following.
How ref to button can trigger focus to a textbox?
Can you adjust demo: https://codesandbox.io/s/react-hook-form-smart-form-component-fi7nl
After you press on button "Focus", the cursor on an above field InputWitForwardedRef should be provided

**Comment by bluebill1049** [comment]
I was giving you an example of how to use `forwardRef`.

**Comment by bluebill1049** [comment]
what are you trying to achieve in your example?

**Comment by stramel** [comment]
@bluebull1049 Just to add my 2 cents, ref merging doesn't work. Which is something I would like to see supported. However, this use-case seems strange. Would be interested in seeing the reasoning behind it.

**Comment by bluebill1049** [comment]
@stramel  what do u mean by ref merging?

**Comment by bluebill1049** [comment]
You can share the ref instead of merge them?

**Comment by stramel** [comment]
No, ref sharing wasnt working either.

**Comment by bluebill1049** [comment]
![925CC5F8-9D83-4592-B1EC-1E1930E8481F](https://user-images.githubusercontent.com/10513364/66689905-d4df3600-ecd8-11e9-82eb-abd0b30a50fc.png)
It doesn’t work?

**Comment by stramel** [comment]
Correct, I will have to put together a codesandbox when I get back to a computer

**Comment by bluebill1049** [comment]
Ok

**Comment by marrkeri** [comment]
Hi guys, @bluebill1049 your solution is working. I did a mistake in my second post.
Instead of ```ref = e``` now I'm using ```ref.current```
Btw use case is for example in a virtual list where you want to scroll/focus into a field which is errored or if you have for example chat room and someone is 'replaying' on some message and you what to preselect select box and focus into chat box. There are multiple usecases for more complex forms and it is good to hear it is possible. 
Thx

Working code
```
return <input name={name} ref={e =>{
    ref.current = e
    register(e)
  }} {...rest} />
```

**Comment by bluebill1049** [comment]
glad it works for you @marrkeri happy coding :)

**Comment by hjrobinson** [comment]
I've read "How to share ref usage?" here:
https://react-hook-form.com/faqs

The problem is that the destructured { ref } can only be used for one input using the line of code below:
```
 const { ref, ...rest } = register('firstName');
```

How would you get another ref assignment for say a 'lastName" input? Pardon my ignorance if I'm overlooking something.

**Comment by hjrobinson** [comment]
I found a solution to the problem I mentioned in my comment above:
```
const firstNameInputRegister = register('firstNameInput', { required: true});

const firstNameInputRegisterRest = {
    name:firstNameInputRegister.name, 
    onBlur:firstNameInputRegister.onBlur, 
    onChange:firstNameInputRegister.onChange
};

const firstNameInputRegisterRef = firstNameInputRegister.ref;
```
But this seems like a lot of code to accomplish something that should be fairly routine.

If somebody knows a more efficient way to handle this let me know.

**Comment by timi-codes** [comment]
```
    const focusRef = useMountFocus();
    const { ref: firstNameRef, ...rest} = register("firstName");
```

```

                  <TextField
                        id="firstName"
                        label="First Name"
                        placeholder="First Name"
                        ref={mergeRefs(focusRef, firstNameRef)}
                        {...rest}
                    />
```
