### ISSUE TITLE
setValue mutates second parameter when used with nested fields

### ISSUE THREAD

**Issue by DamianPereira** [react-hook-form/react-hook-form#3651]
**Describe the bug**
I'm having a problem where I'm trying to use setValue to return an input to it's defaultValue.

**To Reproduce**
Go to [this](https://codesandbox.io/s/react-hook-form-example-58h4o?file=/src/App.js) codepen. And do the following:

1. Select a person from the dropdown
2. Uncheck the something checkbox
3. Switch the person selected

At this point, "something" checkbox remains unchecked, even though the code is supposed to set nested to defaultValue.nested. The intended behavior is to return everything under nested to defaults when the input changes. With the included console.log, you can see that the actual defaultValue defined outside of the react component is getting mutated, so setValue ends up re-setting the something input as unchecked.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-example-58h4o?file=/src/App.js

**Expected behavior**
I'd expect setValue to not mutate a parameter given, or at least to be explicitely stated in the documentation, so I can do a workaround like the one commented out in the code sandbox (clone the object that is sent to setValue).

**Desktop (please complete the following information):**

- OS: Manjaro
- Browser Chrome
- Version 83

**Comment by bluebill1049** [comment]
hey @DamianPereira please use shallow clone for `setValue`, we are trying to get away from `deepClone`, as it causes other problems.

`setValue("nested", { ...defaultValues.nested })`

**Comment by DamianPereira** [comment]
So you suggest using the workaround that I have in the codesandbox? Or you mean a different cloning technique? Also, is mutating the second parameter an intended side-effect of setValue? Or is it a bug?

**Comment by bluebill1049** [comment]
> So you suggest using the workaround that I have (commented) in the codesandbox? Or you mean a different cloning technique? Also, is mutating the second parameter an intended side-effect of setValue? Or is it a bug?
> 
> This is what I currrently have in the codesandbox:
> 
> ```
>   useEffect(() => {
>     console.log(defaultValues.nested);
>     setValue("nested", defaultValues.nested);
>     // This is my current workaround:
>     // setValue("nested", { ...defaultValues.nested });
>   }, [personSelected, setValue]);
> ```
> 
> I'm using that workaround there for my code, but ideally I'd like to just use setValue without cloning.

I see you are using `shouldUnregister: false`, I would recommend you doing the shallow clone above, I will patch this issue tho. The problem you will encounter is when an immutable object like DraftJS's state, it's much safer to not directly use nested object value as deepClone will cause issues as well.

**Comment by DamianPereira** [comment]
Oh I did not realize that shouldUnregister option was contributing to the problem. Thanks for the quick fix!
