### ISSUE TITLE
formState example is broken

### ISSUE THREAD

**Issue by kristian240** [react-hook-form/react-hook-form#3658]
**Describe the bug**
Codepen example for `formState` object breaks when there are errors. JSON.stringify can't  convert circular reference

**To Reproduce**

1. Open `formState`example [link](https://codesandbox.io/s/react-hook-form-v6-formstate-ht098)
2. Set `Number of Corndogs` number input to negative number or positive number greater than 99
3. Press submit

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

https://codesandbox.io/s/react-hook-form-v6-formstate-ht098

**Expected behavior**

`formState` should be printed beneath the form.

**Screenshots**

![image](https://user-images.githubusercontent.com/55184443/101914276-6475c280-3bc4-11eb-98fe-3c5cf05f0d68.png)

**Desktop (please complete the following information):**

- OS: MacOS - Big Sur
- Browser - latest Chrome (v87.0.4280.88)

**Additional context**

I would like to work on this if possible 😄

**Comment by totongcute** [comment]
[](https://github.com/mattermost/mattermost-mobile)

**Comment by bluebill1049** [comment]
thanks @kristian240 fixed 👍
