### ISSUE TITLE
register, unregister are called at each value change.

### ISSUE THREAD

**Issue by elkamy** [react-hook-form/react-hook-form#366]
Hello,

I use react-hook-form@3.23.18 . 
I have created a component to render a field and its registration with the form. The call of the `register` function is made in a `useEffect` that returns a function to `unregister` it.
```javascript
useEffect(() => {
  register({ name });

  return () => {
    unregister({ name });
  };
}, [register, unregister, name]);
```
I also have in my component, another useEffect to define the value within the form.
```javascript
useEffect(() => {
  setValue(name, value);
}, [setValue, name, value]);
```
I wonder if it is normal that at the first rendering, the field is registered and then unregistered, and then registered again.

And it's the same with every change in value.

Am I using `useForm` correctly ?

This seems to be due to the fact that the register function is redefined each time the useForm function is called.

You can see the full example [here](https://codesandbox.io/s/icy-bird-4pems).

Thanks in advance.

**Comment by bluebill1049** [comment]
just read your code, I think you are making yourself life hard, and probably not doing the way react hook form should be doing.

```
return (
    <input
      name="label"
      type="text"
      value={value}
      ref={register} // pass regsiter here instead during useEffect
      // onChange={handleLabelChange} remove this line
    />
  );
```

i think if you do the above, things probably much simpler than you thought.

**Comment by bluebill1049** [comment]
hey @elkamy, any update on this issue from what I have suggested above?

**Comment by elkamy** [comment]
Thanks @bluebill1049 for your answer.

I have made a new [codesandbox sample](https://codesandbox.io/s/cocky-mcclintock-8nbzo) to explain more precisely my concerns.

I have to use manually `register`, `unregister` and `setValue` methods because I have some custom components, and it doesn't have `ref` prop that can be used with `register` (rf `GenderSelectField`).
Is that still the correct way to use react-hook-form ?

Secondly, as you can see in the console, there is a lot of re-render for each `Friend` and its children, each time I change a value.
Even if is use `React.memo`, it doesn't change anything. In my real case, I have a big form with a lot of rows (~ 50, 100) and I'm having low performances. As I explain previously, it seems to be due to the fact that the `register` function is new each time `useForm` is run.

**Comment by bluebill1049** [comment]
FYI, you don't have to call `unregister` for custom registered input.

**Comment by bluebill1049** [comment]
can you try `register` without `unregister`? see if it improve the performance, react hook form works best with ref attached. let me know how did you go.

**Comment by bluebill1049** [comment]
I removed `unregister` and tested your app, the performance looks fine. as you typing, your input only gets re-render during the form dirty and touche.

**Comment by elkamy** [comment]
> I removed `unregister` and tested your app, the performance looks fine. as you typing, your input only gets re-render during the form dirty and touche.

Yes of course, but my real case doesn't look exactly like the app I send to you. It have between 50 to 100 rows, and each one have 10 value components that do not necessarily have ref prop.

We also have another issue in our sample app. In the `GenderSelectField` component, how can I get the current value from the formState. I try to get it from `getValues` it doesn't work.

**Comment by bluebill1049** [comment]
> Yes of course, but my real case doesn't look exactly like the app I send to you. It have between 50 to 100 rows, and each one have 10 value components that do not necessarily have ref prop.

that's what I mentioned above if you don't have ref access, you don't need to call `unregister`, in fact you hardly need to call `unregister`

**Comment by bluebill1049** [comment]
> We also have another issue in our sample app. In the `GenderSelectField` component, how can I get the current value from the `formState`. I try to get it from `getValues` but it doesn't work.

what do you mean get formState from getValues? getValues only return form data.

https://react-hook-form.com/api#getValues
https://react-hook-form.com/api#formState

**Comment by elkamy** [comment]
> what do you mean get formState from getValues? getValues only return form data.

Sorry, I meant to say form data. In my example, i try to get value from `getValues` but values aren't updated. 

How to do to manage custom component with `register` and `setValue`  ? Did i miss something ?

**Comment by bluebill1049** [comment]
you just `register` your input in `useEffect` and `setValue`, that's it. 

I am not sure what do you refer as `getValues` aren't updated, if you did set value, then it should return what's in the entire form.

**Comment by elkamy** [comment]
If you look at the `GenderSelectField`, you will see that I try to get the current value with `const value = getValues()[name];`.
It works the first i change the value but not after. I guess it's because the first time, the `formState` change and re-render the form. But next the `formState` doesn't change, so how to do to refresh the custom component value ?

**Comment by bluebill1049** [comment]
if you just want to watch things allt he time, you should just use `watch`
https://react-hook-form.com/api#watch

**Comment by bluebill1049** [comment]
I am going to close this issue, it's not clear on what the issue. if the question is around how to use react-hook-form you can ask questions at spectrum channel.
