### ISSUE TITLE
Validation errors do not always contain all values returned by a custom resolver

### ISSUE THREAD

**Issue by codeaid** [react-hook-form/react-hook-form#3663]
**Describe the bug**
When using a custom validation resolver (haven't tried without one) hook's `errors` object does not contain all values returned by said validation resolver for fields that are not being edited.

**To Reproduce**
I have created a sample sandbox recreating the issue exactly how I'm encountering it. Please find it below.

It also contains steps to reproduce at the bottom of the page so please follow those to get an idea of what's going on.

As you'll see despite hook's `mode` option being set to `all` and `reValidateMode` option to `onChange` the error message for field "one" is not present, while field two (as well as field one) fails validation.

You can also visit the direct CodeSandbox link if you don't want to see the code: https://d32os.csb.app/.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-validation-d32os?file=/src/App.js

**Expected behavior**
I'm expecting errors for all fields to be present in `useForm` hook's `error` value, or in other words it should contain everything that custom resolver returned.

**Comment by bluebill1049** [comment]
Thanks for the detailed issue demo. 👍 

is this a dependent validation? hook form focuses on a single input at a given time, so you expected the other input shows an error as well? I think you will need to use `trigger` to trigger an error on the other input.

**Comment by codeaid** [comment]
Hmm, interesting... I updated the sandbox to make a `trigger` call on every input change and it's actually working. I swear I tried it in my custom component which I was building when I stumbled upon this "bug" so it looks like it could be something on my end 🤔

Let me look into that and get back to you.

Thanks for getting back to me so quick!

**Comment by codeaid** [comment]
False alarm! Turned out it was a bug on my side. Don't know what it was as it just worked when I added the trigger call 🤦🏻‍♂️. It was probably the result of coding all day and not seeing what's in front of your nose.

Happy to close the issue if there's nothing left to do.

**Comment by bluebill1049** [comment]
aha good to know. all good. thanks for the update.
