### ISSUE TITLE
Duplicate field on usage FieldArray

### ISSUE THREAD

**Issue by brunoJSX** [react-hook-form/react-hook-form#3664]
**Describe the bug**
I have a section with two selects, one input and buttons to add new section and remove. The problem happen when I remove the last section e add a new section, then the section duplicate. Apparently the problem is in the input element.

**To Reproduce**
1. Go to [useFieldArray](https://codesandbox.io/s/prod-sun-20zj6?file=/src/App.tsx)
2. Click *Add section*
3. Remove the first section
4. Click *Add section*
5. Then the section duplicate

**Additional context**
Note: I'm sorry for my English :smile: .

**Comment by bluebill1049** [comment]
the problem is here

```
const removeCriteriaItem = React.useCallback(
    async (index) => {
      // const criteriaData = get(getValues(), `criteria[${index}]`);

      // if (await removeItem(criteriaData)) {
        remove(index);
      // }
    },
    [getValues, remove, removeItem]
  );
```

**Comment by brunoJSX** [comment]
My congratulations for responding so quickly, I am happy because I think your work is super cool :smile: :100: .

I already realized that it was okay to call an asynchronous function before, but I need this to work. Would you help me out of this?

**Comment by bluebill1049** [comment]
> My congratulations for responding so quickly, I am happy because I think your work is super cool 😄 💯 .
> 
> I already realized that it was okay to call an asynchronous function before, but I need this to work. Would you help me out of this? I need wait for call api and if have success, then remove from front.

I will take a look at it, see if there is any work around.

**Comment by bluebill1049** [comment]
<img width="1186" alt="Screen Shot 2020-12-12 at 1 22 15 pm" src="https://user-images.githubusercontent.com/10513364/101970184-12dd3e80-3c7d-11eb-81cc-99b78c723086.png">

I think your issue is due to the `key`, please take a look at the console.warning. let me know if you can found out the issue behind.

**Comment by bluebill1049** [comment]
hey @brunoJSX solution for now: https://codesandbox.io/s/react-hook-form-usefieldarray-forked-6fi7d?file=/src/index.js use Controller to wrap your inputs.

**Comment by brunoJSX** [comment]
Hi @bluebill1049 

I'm very happy with this solution. The suport is very fast! Thanks :smile: .

Is it really a bug? If so, I’m even happier to help with this issue :laughing:

**Comment by bluebill1049** [comment]
@brunoJSX it's a strange one with `async` invoke method. I have made a patch anyhow.

**Comment by HenriTalk** [comment]
Hey! I have a similar problem with current 7.18.1 version.
For me it seems that useForm getValues method is not aligned with useFieldArray fields values correctly.
When I append 2 objects example object1 and object2 ( { id: uuid(), name: "" }) to field array it is saved for me in the redux store using values from getValues().
Then I unmount the form from component lets say by unselecting my active item.
Then by selecting active item again to mount the form with default values from redux (all ids are unique still) I remove object1 from fieldArray and then add new object3.

Expected result: 
Object2 and object3 should have unique ids from getValues()

Actual result:
Last added object 3 has the same id that object 2 from getValues().
Although useFieldArray fields have unique ids for object2 and object3.
So getValues() and array fields are not in sync correctly.

This seems to be a bug with react-hook-form
