### ISSUE TITLE
formState isValid/isDirty depends on whether the values has been read before

### ISSUE THREAD

**Issue by automatensalat** [react-hook-form/react-hook-form#3673]
**Describe the bug**
I noticed some weird behavior with the `isValid` and `isDirty` field of the `formState`. Now I don't know if that's a bug or some side-effect of intended behavior, but to me this is very irritating: When included in JSX `isValid` and `isDirty` seem to depend on whether the values have been accessed before in the render function. 

In my case, I have a form with two inputs and I disable the submit button if the formState is either invalid or not dirty: 
```tsx
<input type="submit" disabled={!formState.isDirty || !formState.isValid} />
```
For me, this only works when both inputs are touched OR `formState.isValid` has been accessed before, for example by logging it to console. 

**To Reproduce**
See codesandbox below: 
1. change value of an input field
2. observe that button stays disabled and that the console logs `isDirty true`
3. uncomment console.log 
4. change value of an input field
5. observe that the button gets enabled

**Codesandbox link (Required)**
This Codesandbox contains a form with two input fields and a button. The button is disabled when the form is not both valid and dirty. If you change one input, it should make the form dirty and enable the button. But this does not happen. 
Instead, uncomment the line `console.log(formState.isValid)` and try again - this enables the button. Also works with assigning it to a variable.

https://codesandbox.io/s/react-hook-form-useform-template-forked-mxoj7?file=/src/index.js

**Expected behavior**
The values do not depend on having been accessed before, i.e. in the example it should not matter if I have the console.log commented or not. 

**Desktop (please complete the following information):**

- OS: Ubuntu Linux 20.4
- Browser chromium
- Version 87

**Additional context**
The issue is also resolved if you swap `isDirty` and `isValid` in the example, i.e. change it to `!formState.isValid || !formState.isDirty`. However in my earlier experiments I also had problems with that order.

I hope I didn't make any obvious emberassing mistake here but I don't understand why this is happening.

**Comment by bluebill1049** [comment]
<img width="979" alt="Screen Shot 2020-12-15 at 8 49 56 am" src="https://user-images.githubusercontent.com/10513364/102139839-83b96c00-3eb2-11eb-8587-8075980fe0b5.png">

> Important: formState is wrapped with Proxy to improve render performance, so make sure you invoke or read it before render in order to enable the state update. This reduced re-render feature only applies to the Web platform due to a lack of support for Proxy in React Native.

**Comment by automatensalat** [comment]
Hmm. Does this apply to this case though? There's no `useEffect` in place in my example and the component *does* rerender after typing in the input field. 

I modified the sandbox here: https://codesandbox.io/s/react-hook-form-useform-template-forked-i6hto?file=/src/index.js
I extracted the condition into a variable: 

```ts
const buttonIsDisabled = !formState.isDirty || !formState.isValid;
```
What I find especially strange is that 
```ts
!formState.isDirty || !formState.isValid // shows described behavior
``` 
does not behave the same way as 

```ts
!formState.isValid || !formState.isDirty // works
```

I did some experiments with my real life use case. Structurally it's the same as the example: two required inputs and a save button. I modified the RHF code to include logging access to the `formState` proxy: 

```ts
// index.esm.js
// useForm() hook
...
 const commonProps = {
        ...
        formState: isProxyEnabled
            ? new Proxy(formState, {
                get: (obj, prop) => {
                   ...
                    if (prop === "isValid" || prop === "isDirty")
                        console.log("access", prop, "from formstate: ", obj[prop]);
                    return obj[prop];
...
```
and modified my code like so: 
```ts
console.log("evaluating form states...");
const saveButtonIsDisabled = !formState.isDirty || !formState.isValid;
console.log("done. disabled =", saveButtonIsDisabled);
```
After changing the input field, the output looks like this:
```
evaluating form states...
useForm.ts:1289 access isDirty from formstate:  false
UserForm.tsx:63 done. disabled = true
UserForm.tsx:36 render
evaluating form states...
useForm.ts:1289 access isDirty from formstate:  true
useForm.ts:1289 access isValid from formstate:  true // <-- here!
UserForm.tsx:63 done. disabled = false
UserForm.tsx:36 render
UserForm.tsx:61 evaluating form states...
useForm.ts:1289 access isDirty from formstate:  true
useForm.ts:1289 access isValid from formstate:  false
UserForm.tsx:63 done. disabled = true
... (further renders with same output)
```
There is a brief moment in which both `isDirty` and `isValid` are true as expected (line 7 in above log output) but it's changed back to `isValid: false` immediately. 

I do think this is wrong and surprising as a user of the library and it should not happen, but in case you disagree: What's the suggested workaround? Reading both `formState.isDirty` and `formState.isValid` into a temporary variable that's not used?

**Comment by bluebill1049** [comment]
here is the working version: https://codesandbox.io/s/react-hook-form-useform-template-forked-oem7f?file=/src/index.js

`!formState.isDirty || !formstate.isValid // if first condition is true, second won't be evaluated and hence not info proxy that state is subscribed`

**Comment by automatensalat** [comment]
Ok, thanks for your response. I can live with that, but I do think it's problematic. IMO, the values of the two props should not depend on their order of access, even if it uses such a thing as a Proxy. 

Is there anything I can do to help improve this? I could try clarifying this in the docs or add another example at least.

**Comment by bluebill1049** [comment]
By the way, that's how JS works with `||`. One thing I can assure you that we have put a lot of thoughts into this to give the developer the performance on the form which they deserved (especially to skip that validation logic when they r not even subscribe to the form state), it's a tradeoff which we decide to take, and I am more than happy to answer your question and other developers around the whole, but it's not a lib made just for you, so I don't really care whether you can live that or not. 

> Is there anything I can do to help improve this? I could try clarifying this in the docs or add another example at least.

I would appreciate it if you can improve the doc, to explain better if you have a better way of describing it. I am going to close this, if you would like to contribute feel free to send a PR at the documentation.
