### ISSUE TITLE
Complex form structure breaks useFieldArray throwing resetFieldArrayFunctionRef.current[name] is not a function

### ISSUE THREAD

**Issue by matheusgrieger** [react-hook-form/react-hook-form#3677]
**Describe the bug**
We have support for localized form input, so we're using a field array for added languages. But some fields inside each language are also arrays and as such we use a new field array for them. It all works as expected when using regular append/remove methods. Problem is that we have to introduce an automated translation feature that gets data from the first language, translates to all other enabled languages, and replaces everything in the form. We've ended up using `setValues` to replace everything. Problem is that when using `setValues` on a _nested_ field array, React Hook Form crashes with the following error: `resetFieldArrayFunctionRef.current[name] is not a function`.

**To Reproduce**
- Create nested field arrays
- Try to `setValue` in a nested field array such as `setValue("language[0].list", newList)`
- See error thrown

**Codesandbox link (Required)**
In the sandbox, just click FETCH DATA and the error will be thrown:

https://codesandbox.io/s/react-hook-form-usefieldarray-error-with-complex-form-structure-hkibv

**Expected behavior**
The array should be replaced with new values.

**Desktop (please complete the following information):**

- OS: MacOS 10.15.7
- Browser Chrome
- Version 87.0.4280.88 (64 bits)

**Additional context**

Also tried to replace the _entire key_ as in my case the second array is nested in another object, but that didn't work either:

```js
const data = {
  contents: [{
     customData: { specifications: [/* this is the nested field array */] }
  }, {
     customData: { specifications: [/* this is the second nested field array */] }
  }],
};
const { setValue } = useForm({ defaultValues: data });

// after fetching data:
setValue('contents', newDataWithNewArrays);
```

In this case, the error isn't thrown but the arrays don't update either.

**Comment by bluebill1049** [comment]
`setValue` at the moment only supports the entire FieldArray: 

https://codesandbox.io/s/react-hook-form-usefieldarray-error-with-complex-form-structure-forked-jb3to?file=/src/index.js

**Comment by matheusgrieger** [comment]
Thank you so much for looking into this! Definitely the most well-maintained React form library out there 👍
