### ISSUE TITLE
Reusable FieldArray component with single field removes the wrong element

### ISSUE THREAD

**Issue by chrisbag** [react-hook-form/react-hook-form#3680]
First of all, many thanks @bluebill1049 for this amazing library which I use everyday.
I have been struggling on this problem for many hours.

**Goal**
Build a FieldArray component with a single field to use accross different forms
Unlike the useFieldArray function, I would like the field to return an array of strings e.g. ["email@adress.com", "email2@adress.com, ...]

**Describe the bug**
Remove an element from a FieldArray removes the wrong element

**Code Sandbox Link**
https://codesandbox.io/s/react-hook-form-array-fields-forked-2irok?file=/src/FieldArray.js

**To reproduce**
1) Go to the sandbox
2) Add 3 new fields to fieldOne and type in random text
3) Remove the first Field. Notice that a field is indeed deleted but the value of first field remains in place

**Expected behavior**
Should remove correct field value

**Questions**
Do you know why the wrong element is being deleted ?
Is there a better approach to building a FieldArray with a sigle value with React Hook Forms ?

Thanks a lot for your help, looking forward to your answers :)

**Comment by bluebill1049** [comment]
hey @chrisbag use this instead: https://react-hook-form.com/api/#useFieldArray there are quire a few gotchas with delete if you implemented yourself :)

**Comment by chrisbag** [comment]
hey @bluebill1049 
Thanks for your fast answer. However in the doc you mentioned, flatArrays are not supported. Is there a workaround to implement flatArrays ?

**Comment by bluebill1049** [comment]
> hey @bluebill1049
> Thanks for your fast answer. However in the doc you mentioned, flatArrays are not supported. Is there a workaround to implement flatArrays ?

not, it has to be `object`

**Comment by bluebill1049** [comment]
Are you ok to use `object` with useFieldArray? I guess you will have to flat it, if you need flat array.

**Comment by chrisbag** [comment]
Hello @bluebill1049,
useFieldArray works like a charm, I have been using it for a while.
I have had to do a little workaround to make it work with my a flat array in my DB (transforming element into object when loading into a form and then flattening object on submit). Not the most convenient for my specific use case but I get that you cannot create a package fitting all use cases :)
thank you so much for answering so fast and managing to keep on top of all issues & questions regarding this awesome library !

**Comment by bluebill1049** [comment]
Awesome to hear! @chrisbag thanks very much for your understanding as well. I wish we have more developers like yourself in the community. again thank you for your support and kind words. have a lovely weekend and Merry Xmas!
