### ISSUE TITLE
Controller's value got eaten up by its defaultValue when using useFieldArray

### ISSUE THREAD

**Issue by dwiyatci** [react-hook-form/react-hook-form#3682]
**Describe the bug**
As the title says, but not sure if this is a bug or by-design (?) 🙄😅 

**To Reproduce**

1. Go to the CSB link below.
2. Observe the values in the form controls. The values should be "foo", "bar", "baz" respectively, but instead each control takes `defaultValue` specified in the `Controller` which is "foobar".

**Codesandbox link (Required)**
https://codesandbox.io/s/controllers-value-got-eaten-up-b48kf?file=/src/App.jsx:892-930

**Expected behavior**
`defaultValue` in `Controller` should get overridden by `defaultValues` in `useForm`.

**Comment by bluebill1049** [comment]
yes, use `item.name` instead. inline `defaultValue` will always be the initial value for the input over `defaultValues` from `useForm`. 👍

**Comment by dwiyatci** [comment]
Right, I know `item.name` would make it work 😋. I just wanted to know the `default`-ing mechanics. Thanks for confirming, @bluebill1049. 

Just one doubt though: if I remove `defaultValue` from the `Controller`, everything works as expected ("foo", "bar", "baz") – taking the values from the `defaultValues` from `useForm` but then there's always be a warning in the console: ``"Controller is missing `defaultValue` prop when using `useFieldArray`"`` (CSB here: https://codesandbox.io/s/controllers-value-got-eaten-up-forked-twljc?file=/src/App.jsx). Do you think this warning still makes sense when the `defaultValues` from `useForm` are filled? 🤔

**Comment by bluebill1049** [comment]
yea, we need the defaultValue during shuffling the inputs. so don't remove it 👍

**Comment by dwiyatci** [comment]
Gotcha. All clear now. Thanks!! 🙇🏻🙇🏻
