### ISSUE TITLE
deafaultValue={null} is causing pattern rule to trigger an error

### ISSUE THREAD

**Issue by andidev** [react-hook-form/react-hook-form#3684]
**Describe the bug**
If defaultValue={null} is used instead of defaultValue={''} the pattern will cause a form error.

**To Reproduce**
Open codesandbox and press submit to show the difference between defaultValue={null} and defaultValue={''} 

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-template-forked-0j2nw?file=/src/index.js

**Expected behavior**
Expected defaultValue={null} to work as defaultValue={''} and not cause a form error. The required rule should cause an error here but not the pattern.

**Screenshots**
![image](https://user-images.githubusercontent.com/571389/102155463-e17e9180-3e7b-11eb-8e95-9818e8f3a95e.png)

**Desktop**
- OS: OSX Catalina
- chrome

[EDIT] By the way thanks for the most awesome form lib I have ever used!

**Comment by andidev** [comment]
I beleive this row is the issue
https://github.com/react-hook-form/react-hook-form/blob/5f86d70d154bee9b77c3a3f96dd518c0d750f20a/src/logic/validateField.ts#L164

should be 
```js
if (pattern && !isEmpty && !isNullOrUndefined(value)) {
```

**Comment by bluebill1049** [comment]
Thanks for the detailed issue and even looking into the code 👍 

would like to send a PR on this?

`if (isString(value) && pattern && !isEmpty) {` looks shorter and valid.

**Comment by andidev** [comment]
I'll do it right away

**Comment by andidev** [comment]
@bluebill1049 Done! Thanks again for an awesome lib!
