### ISSUE TITLE
useFieldArray nested array manipulation bug

### ISSUE THREAD

**Issue by paprikman** [react-hook-form/react-hook-form#3689]
**Describe the bug**
After removing any but the last parent element in field array, nested field array elements will not receive key values (id). Works fine in the 6.13 build used by the default CSB (see link below), but does not work on the latest 6.13 from the npm repository.

**To Reproduce**

1. Go to the default example [csb](https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-lo2er)
2. Click 'update' on the react-hook-form library (important). Everything works fine with the build used in this CSB by default.
3. Modify (or not, does not matter) the first main element.
4. Add another parent element, add one nested element to it.
5. Remove first parent element.
6. Try adding more nested elements to the only remaining parent element in the list.
7. All previously present nested elements will lose their id. Only the last nested element will have an id, which will change on each append. Other elements in the nested list will have `id: undefined`.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-lo2er

**Expected behavior**
New nested elements always receive an id on append, the previous nested elements do not lose their id.

**Comment by bluebill1049** [comment]
> Works fine in the 6.13 build used by the default CSB (see link below), but does not work on the latest 6.13 from the npm repository.

what do you mean by above?

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report.

> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to the default example [csb](https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-lo2er)
> 2. Click 'update' on the react-hook-form library (important). Everything works fine with the build used in this CSB by default.
> 3. Modify (or not, does not matter) the first main element.
> 4. Add another parent element, add one nested element to it.
> 5. Remove first parent element.
> 6. Try adding more nested elements to the only remaining parent element in the list.
> 7. All previously present nested elements will lose their id. Only the last nested element will have an id, which will change on each append. Other elements in the nested list will have `id: undefined`.

however, i find it difficult to follow, would you be able to record a short video on this?

**Comment by paprikman** [comment]
> what do you mean by above?

When opening the CSB that I have attached, there's a 'react-hook-form' dependency, which shows as:
![image](https://user-images.githubusercontent.com/57448756/102190716-305b1400-3eda-11eb-90d9-2b9cfa9e4c57.png)

And when you hover it, it changes into 6.13 text. When using this version, it's all ok and there's no issues. But if you click the update icon and refresh the csb browser window, the issue appears.

> however, i find it difficult to follow, would you be able to record a short video on this?

Sure, I will try recording it.

**Comment by bluebill1049** [comment]
thanks a lot @paprikman if you can indicate which `id` would be great as well. 👍

**Comment by paprikman** [comment]
> thanks a lot @paprikman if you can indicate which `id` would be great as well.

Sorry, I didn't read this at the time I was recording, but the video should be informative enough. Here's a link to it: https://youtu.be/4rxq8vgGL-M

Note that dependency update I do before the second test. You can clearly see the react's no key warning in the console, which is due to the id being undefined. I hope that it makes sense and will help you to reproduce the issue.

**Comment by bluebill1049** [comment]
That was really helpful! thankkyou
