### ISSUE TITLE
Returns error even if a field has default value, if it is disabled

### ISSUE THREAD

**Issue by sabbiu** [react-hook-form/react-hook-form#3691]
**Describe the bug**
- I am using this logic during form update.
- I provide the defaultValues and also in schema the fields are required.
- Among them one of the field is disabled and also required.
- Now when I try to update other field, it gives me error for the disabled field.

**To Reproduce**

1. Go to [codesandbox demo](https://codesandbox.io/s/react-hook-form-get-started-forked-muh1p?file=/src/index.js)
2. Click on 'submit button'  
4. See error 'this field is required

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.
- [codesandbox demo](https://codesandbox.io/s/react-hook-form-get-started-forked-muh1p?file=/src/index.js)

**Expected behavior**
- It should not have thrown error saying the field is required, as it already contains default value.

**Comment by bluebill1049** [comment]
you are after `readonly` not `disabled`
