### ISSUE TITLE
Cannot set nested value when array is in an object ?

### ISSUE THREAD

**Issue by UnbearableBear** [react-hook-form/react-hook-form#3696]
Hey ! First of all, thanks for this amazing library 🙏  It's my absolute must use when I build forms in react.

I might be missing something, but it seems to me that `setValue` is somehow buggy when I use it to set a value on a nested array, which is itself inside an object. I tried to simplify the codsandbox the best I could to make it more obvious. The same problem seems to happen with `append` of `useFieldArray`. Am I missing something ?

```
            setValue("obj.test", [
              {
                name: "append",
                nestedArray: [{ field1: "append", field2: "append" }]  // <---- this line is ignored
              }
            ]);
```
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-2f8vg?file=/src/index.js

Note that if I remove `obj.` from my form/data structure, everything works just fine.

**Comment by bluebill1049** [comment]
Thanks @UnbearableBear will patch this on the next release.

**Comment by UnbearableBear** [comment]
I feel guilty for not taking the time to look at the code and fix it myself. Thanks a lot, you're a modern hero ! 👏

**Comment by bluebill1049** [comment]
> I feel guilty for not taking the time to look at the code and fix it myself. Thanks a lot, you're a modern hero ! 👏

my pleasure @UnbearableBear, thanks for reporting the issue. PR welcome too in the near future. ❤️
