### ISSUE TITLE
Handlesubmit doesn't respect error set with setError

### ISSUE THREAD

**Issue by BatuhanW** [react-hook-form/react-hook-form#370]
**Describe the bug**
I have a register form where I do async requests to server to validate username and email. I do this `onChange` and set or clear error when needed.

My problem is, when `handleSubmit` is triggered via onClick handler of the form's submit button, it clears error on username, email. Even though these username and email aren't valid and unique, my error ge

**To Reproduce**
1. Have a form where you do `setError` from `onChange`.
2. Submit form

**Expected behavior**
It shouldn't submit the form and show the error on the field.

**Comment by bluebill1049** [comment]
can you please provide a codesandbox for your issue?

**Comment by BatuhanW** [comment]
https://codesandbox.io/embed/gifted-moon-vixny

**Comment by bluebill1049** [comment]
Ur codesandbox is empty.

**Comment by BatuhanW** [comment]
@bluebill1049 sorry, can you check again? it seems I forgot the save.

**Comment by bluebill1049** [comment]
ok why you are not using `valdiate` function for that async validation?

**Comment by waynebloss** [comment]
@bluebill1049 The docs only mention async validation by passing an async function to the [handleSubmit](https://react-hook-form.com/api#handleSubmit) function. Nowhere else is async validation mentioned.

However, I think that you just recommended the `validate` function, I'm assuming as part of the call to `register`, e.g. `register({ name: "hello" }, { validate: async () => await xxx() })`. 

~~Is that correct? Can you pass an async call like that, to the `validate` option of `register`?~~

OK, I looked in the code and I see the call to `await validate` [here in validateField.ts](https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/validateField.ts#L134).

Your documentation is so good looking, that I bet people are thinking that it's up to date as well.

**Comment by bluebill1049** [comment]
I will update the doc with async :) @waynebloss there are examples for async validation in the example folder FYI.

**Comment by bluebill1049** [comment]
@BatuhanW any update on this issue? is validate function works for you?

**Comment by bluebill1049** [comment]
closing this issue, feel free to re-open or leave questions.

**Comment by BatuhanW** [comment]
> ok why you are not using `valdiate` function for that async validation?

Hello @bluebill1049,

Since it is being triggered with `every` keystroke, I don't want to do request with every keystroke. To avoid this, I put this server request in a timeout, I'm keeping timeout id in the state and clearing as user keeps typing. Once user stop typing, I send request.

However, it's not possible to access state inside `validate` function. This is why I have to use it on `onChange`. 

```
const { value } = event.target;

                                                const validate = setTimeout(async () => {
                                                    const resp = await AccountService.CheckUsername(
                                                        {
                                                            body: { username: value },
                                                        }
                                                    );

                                                    if (!resp.Ok) {
                                                        setError(
                                                            "username",
                                                            "UsernameExist",
                                                            "username exist"
                                                        );
                                                    } else {
                                                        clearError("username");
                                                    }
                                                }, 700);

                                                clearTimeout(usernameTimeout);
                                                setUsernameTimeout(validate);
```

**Comment by bluebill1049** [comment]
hey @BatuhanW 

1. you can throttle the request by debounce/throttle. 
2. you can access state inside `validate` function by hoist a variable outside React component, or use `useRef`. If your state information is inside another input, then you can use `watch()` as well

**Comment by BatuhanW** [comment]
throttle/debounce doesn't fix my issue, because they make requests eventually. 
@bluebill1049 My quick solution is to prevent submitting form;

```
 onClick={e => {
                                        if (formState.isValid) {
                                            handleSubmit(onSubmit)(e);
                                        }
                                    }}
```

But I will give a shot to useRef or hoisting variable.

But still can't understand tho, why do the errors being reset onSubmit, isn't it something bad?

**Comment by BatuhanW** [comment]
Thanks for the quick responses and great library btw. @bluebill1049

**Comment by bluebill1049** [comment]
@BatuhanW thanks, it's not been reset, because your input is not returned any error during submit.

each input will go through all valuations rule, and your input doesn't have any error return by the input. that's why I suggested using `validate`.

why not set the mode to `onSubmit`? so validation is not triggered during input change?

**Comment by bluebill1049** [comment]
let's follow up on your question/progress in the spectrum. https://spectrum.chat/react-hook-form
