### ISSUE TITLE
formState seems to keep changing its object reference on each render update, causing endless/infinite re-render

### ISSUE THREAD

**Issue by dwiyatci** [react-hook-form/react-hook-form#3706]
**Describe the bug**
Elaboration of https://github.com/react-hook-form/react-hook-form/issues/2893#issuecomment-691585687.

**To Reproduce**

1. Go to the CSB link provided in the below section.
2. See the console. Observe that `prevFormState === formState` is always `false`, meaning that the object reference of the `formState` is always changing on each render.
3. In order to reproduce the endless re-render, comment the guard condition `if (renderCount < 10)` in `index.jsx`.

**Codesandbox link (Required)**
https://codesandbox.io/s/rhf-formstate-issue-22j1t?file=/src/index.js:483-517

**Expected behavior**
`formState` should not change its object reference on each render update if nothing changes in the form.

**Comment by bluebill1049** [comment]
```
onErrorsChange={(errors) => {
  // comment this below if to reproduce endless re-render
  if (renderCount < 10) {
    setBannerErrors(createBannerErrors(errors));
  }
}}
```

what's this sideEffect above?

**Comment by dwiyatci** [comment]
It's an effect that kicks-in because of setting a new state (basically creating a new `bannerErrors` object) every time the form errors changes, which in turn gonna re-render the parent (`<App>`) component, and hence the child (`<MyForm>`) component. I guess it's also just a state update. 

What makes me wonder is when it re-renders (updates) the `<MyForm>` component, it always triggers the `useEffect()` inside that component again and again, which means the `formState` always changes, right..?

**Comment by bluebill1049** [comment]
if `updateFormState` gets invoked inside hook form, it will trigger `useEffect`.

**Comment by dwiyatci** [comment]
Hm ok, and `updateFormState` gets invoked every time the component that has `useForm` gets updated (re-rendered)?

**Comment by bluebill1049** [comment]
> Hm ok, and `updateFormState` gets invoked every time the component that has `useForm` gets updated (re-rendered)?

nope, you should try an example with those side effects that you have in your CSB.

eg: https://codesandbox.io/s/react-hook-form-useform-template-forked-z566k?file=/src/index.js

**Comment by dwiyatci** [comment]
Right, that could be simpler, but got the same result, unfortunately. 😕 Please check out:

https://codesandbox.io/s/react-hook-form-useform-template-forked-xmyqy?file=/src/index.js:566-604

If you click on the "click me" button, it will change/update the state of the component (increment the `count`) and then re-render/update the component. But then the `formState` also keeps changing along with it (although we don't do anything to the form itself).

**Comment by bluebill1049** [comment]
I see this is probably due to `Proxy` around `formState`. Don't think there is much we can do about this one.

**Comment by dwiyatci** [comment]
@bluebill1049 Thanks, Bill, that's fine. I guess sticking to the workaround should do the job for me for now (and at least I can sleep well tonight :)

```javascript
useEffect(
  () => {
    onErrorsChange(formState.errors);
  },
  /**
   * Note that using `formState` directly as the dep will cause endless re-render,
   * probably due to Proxy around formState.
   * @see https://github.com/react-hook-form/react-hook-form/issues/2893#issuecomment-691585687
   * @see https://github.com/react-hook-form/react-hook-form/issues/3706#issuecomment-747773616
   */
  [JSON.stringify(formState.errors)]
);
```

**Comment by bluebill1049** [comment]
@dwiyatci I will put this down in our internal Trello board, see if we can get around this issue by not using Proxy in the next major version.

**Comment by bluebill1049** [comment]
<img width="388" alt="Screen Shot 2020-12-18 at 11 29 40 am" src="https://user-images.githubusercontent.com/10513364/102559593-52e06d80-4124-11eb-9560-f68bfb3e80f6.png">

a note on the project board first, it's a tricky one, but we will try.

**Comment by dwiyatci** [comment]
Ohh, that is too nice of you, Bill!! 🥺🥺 THANK YOUU

![bow](https://user-images.githubusercontent.com/4405796/102597776-6804ce80-411b-11eb-859c-f18c2b555fca.gif)

**Comment by sjdemartini** [comment]
@bluebill1049 Sorry for the ping on this old issue, but I'm curious whether there are any updates here, given that this was moved to the internal Trello board when it was closed in Dec 2020. I'm still seeing that `formState` changes on every single render (even if the render is unrelated to `react-hook-form`). This has an additional side-effect that `FormProvider` re-renders any time the parent using `useForm` renders, preventing any `memo`/`PureComponent`s children inside the `FormProvider` from being actually memoized (they always re-render). 

Thanks in advance; love react-hook-form and hoping an optimization here might be possible to improve performance further!
