### ISSUE TITLE
Add utility or configuration to change shape of data for Field Array?

### ISSUE THREAD

**Issue by waynebloss** [react-hook-form/react-hook-form#371]
**Is your feature request related to a problem? Please describe.**

The [field-array example](https://codesandbox.io/s/6j1760jkjk) returns a data object with a non-standard shape, e.g.:

```js
{
  firstName: ["a", "b"],
  lastName: ["aa", "bb"],
  email: ["a@aa.com", "b@bb.com"]
}
```

It would be more convenient for many situations, to be able to access data shaped like this:

```js
[
  { firstName: "a", lastName: "aa", email: "a@aa.com" },
  { firstName: "b", lastName: "bb", email: "b@bb.com" },
]
```

Such as, for sending the data to a server or storing it somewhere else. Certainly, this is the much more common format and I believe that many programmers will have to write functions to convert data to and from `react-hook-form`.

Another problem is that I must write a second function to convert server data to this format to load `defaultValues`. Writing this second function is more difficult because each row of data may not have the same keys.

A third problem is that I cannot load data very well. The comments in my example code show this issue.

See my [code sandbox](https://codesandbox.io/s/react-hook-form-array-fields-8ngx5) based on the field array example.

**Describe the solution you'd like**

Therefore, I think it would be a benefit if you included such functions to convert data to and from either format. Alternatively, add a configuration feature to always shape the data in the more common format.

**Describe alternatives you've considered**

I have considered storing and sending data to my server in the format used by `react-hook-form` but that seems rather excessive.

Perhaps, there are some `lodash` functions that handle this, but I am not sure. I do not use `lodash` in every project.

**Additional context**

From https://codesandbox.io/s/react-hook-form-array-fields-8ngx5

Here are the functions that I created. They are not written very well, but they do the job.

```js
function pivotData(data, size = data[Object.keys(data)[0]].length) {
  const keys = Object.keys(data);
  const keysLength = keys.length;
  const rows = [];
  for (let i = 0; i < size; i++) {
    const row = {};
    for (let j = 0; j < keysLength; j++) {
      const key = keys[j];
      const value = data[key][i];
      row[key] = value;
    }
    rows.push(row);
  }
  return rows;
}
```

```js
/** This function needs the keys, otherwise it has to also normalize the keys for each row. */
function unpivotData(data, keys = []) {
  const output = keys.reduce((r,key) => {
    r[key] = [];
    return r;
  }, {});
  data.forEach((row, i) => {
    keys.forEach(key => {
      output[key][i] = row[key] !== undefined ? row[key] : null;
    });
  });
  return output;
}
```

In my example, this code does not work:

```js
async function loadFromServer() {
  await Promise.resolve(); // Simulate async...

  sampleData.forEach((row, i) => {
    dataKeys.forEach(key => {
      console.log(`${key}[${i}]`, row[key]);
      setValue(`${key}[${i}]`, row[key]);
    });
  });
  // ****************************************************
  // Issue: Values beyond the first row are not rendered!
  // ****************************************************
  setSize(sampleData.length);
}
```

It only works when `size` is initialized to `2`.

**Comment by waynebloss** [comment]
One other small bug in the original field array example that I changed in my copy:

```js
function createArrayWithNumbers(length) {
  return Array.from({ length }, (_, k) => k); // Issue: k + 1 causes null values.
}
```

**Comment by bluebill1049** [comment]
Thanks @waynebloss for your suggestion. I think most of the stuff you have mentioned above would be better to sit at your app level. At this stage, I like to keep react hook form API as primitive, any utility function probably should not be part of this package. However, there is some utility within react hook form, such as 

https://react-hook-form.com/api#getValues `//when you pass nest, is true`

**Comment by bluebill1049** [comment]
> One other small bug in the original field array example that I changed in my copy:
> 
> ```js
> function createArrayWithNumbers(length) {
>   return Array.from({ length }, (_, k) => k); // Issue: k + 1 causes null values.
> }
> ```

thanks i will update that

**Comment by waynebloss** [comment]
@bluebill1049 Thanks! 

Just one question if you happen to have time. Any idea how I would go about loading data into that field array example?

When I set all of the values using my `loadFromServer` function, none of the values beyond row 1 were displayed. How would you fix that?

**Comment by bluebill1049** [comment]
Hey @waynebloss 

First of all, thanks for understanding. I think you can use reset function.

https://react-hook-form.com/api#reset
