### ISSUE TITLE
`dirtyFields` mutates and does not update when it changes

### ISSUE THREAD

**Issue by aaronjensen** [react-hook-form/react-hook-form#3711]
**Describe the bug**
It appears that `dirtyFields`'s reference does not change when it changes. This means I can't use it as a dependency in `useEffect`, instead needing to use and memoize the list of field names.

Is this intentional for some reason?

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-useform-template-forked-il3j5?file=/src/index.js
2. Update first name
3. Observe that the useEffect does not trigger

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-forked-il3j5?file=/src/index.js

**Comment by bluebill1049** [comment]
please use `formState` as dep, we don't memo state inside `formState`

**Comment by aaronjensen** [comment]
Okay, that works, though it's surprising. I see now that's the first line of the `formState` docs, sorry. I was trying to follow the the other line in the docs that said you should access it "before render" (maybe it means "in render") and access it before the useEffect. Is it safe to use only inside useEffect? It seems to work in my example.

**Comment by bluebill1049** [comment]
> Okay, that works, though it's surprising. I see now that's the first line of the `formState` docs, sorry. I was trying to follow the the other line in the docs that said you should access it "before render" (maybe it means "in render") and access it before the useEffect. Is it safe to use only inside useEffect? It seems to work in my example.

yeah good point, formState is wrapped with `Proxy`, so to trigger the subscript to the state, it's correct to read from the `formState`, if you want to be notified with formState update, put that in the useEffect is the correct solution.

**Comment by aaronjensen** [comment]
Got it, as long as it's not too late in `useEffect` (which happens after render) then I think we're good. Thanks!

**Comment by aaronjensen** [comment]
Actually, it looks like it's too late to pick up changes that happen in a useEffect. Even invoking it in the render is too late: 

https://codesandbox.io/s/react-hook-form-useform-template-forked-yizxd?file=/src/index.js

Though maybe this is expected behavior?

**Comment by bluebill1049** [comment]
> Actually, it looks like it's too late to pick up changes that happen in a useEffect. Even invoking it in the render is too late:
> 
> https://codesandbox.io/s/react-hook-form-useform-template-forked-yizxd?file=/src/index.js
> 
> Though maybe this is expected behavior?

hey @aaronjensen what do you mean it's too late?

**Comment by aaronjensen** [comment]
I corrected the example by adding `{shouldDirty: true}`

https://codesandbox.io/s/react-hook-form-useform-template-forked-yizxd?file=/src/index.js

Essentially, if a value is updated in an effect, and I don't invoke `formState.dirtyFields` before that effect (either by ensuring that my effect happens before the value changing effect, or by invoking it in my render method like the commented out console.log) then I won't get notified when the field is dirtied

It's certainly an edge case, but it's one of those areas where the proxy makes for some surprising behavior.

**Comment by bluebill1049** [comment]
> I corrected the example by adding `{shouldDirty: true}`
> 
> https://codesandbox.io/s/react-hook-form-useform-template-forked-yizxd?file=/src/index.js
> 
> Essentially, if a value is updated in an effect, and I don't invoke `formState.dirtyFields` before that effect (either by ensuring that my effect happens before the value changing effect, or by invoking it in my render method like the commented out console.log) then I won't get notified when the field is dirtied
> 
> It's certainly an edge case, but it's one of those areas where the proxy makes for some surprising behavior.

I see what do you mean now, thanks for update the CSB, I will think about if we can resolve that in the next major version.
