### ISSUE TITLE
Watching all fields causes rerenders on blur

### ISSUE THREAD

**Issue by aaronjensen** [react-hook-form/react-hook-form#3712]
**Describe the bug**
If using `useWatch({})` to watch all fields, the component is rerendered on blur of a field (even without a change)

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-useform-template-forked-joie5?file=/src/index.js
2. Click on first name
3. Click on last name
4. Observe rerender console log

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-useform-template-forked-joie5?file=/src/index.js

**Comment by bluebill1049** [comment]
Thanks @aaronjensen will improve on this one.

**Comment by aaronjensen** [comment]
Thank you for the quick fix! :heart:
