### ISSUE TITLE
submitted useFieldArray data empties when using the remove() then hit submit

### ISSUE THREAD

**Issue by neilnahid** [react-hook-form/react-hook-form#3724]
**Describe the bug**
submitted useFieldArray data empties when using the remove() then hit submit

**To Reproduce**

1. Go to https://codesandbox.io/s/boring-surf-7pvi3?file=/src/App.js'
2. Click on add button twice
3. fill out data of 2 items
4. hit submit
5. delete 1 of the items
6. hit submit again
7. submittedData becomes empty

**Expected behavior**
submittedData should not be empty

**Desktop (please complete the following information):**

- OS: Ubuntu 20.10
- Browser: chrome
- Version: 6.12.2

**Comment by neilnahid** [comment]
my apologies if I haven't used the template

**Comment by bluebill1049** [comment]
`ref={register()}` ?

**Comment by neilnahid** [comment]
I have completely overlooked that from the docs. It works now. cheers!
