### ISSUE TITLE
Input hasn't trigger focus after setError

### ISSUE THREAD

**Issue by tin80122** [react-hook-form/react-hook-form#3728]
**Describe the bug**
input hasn't trigger focus after submit which has a validation function will setError

**To Reproduce**

1. type enter space
2. Click Submit button
3. setError is successful which can see the errors information in console.log
4. Don't click anywhere, then you will see that input hasn't focus

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-with-input-focus-test-forked-8pbwh

**Expected behavior**
I want to validate empty value after clicking submit button,
if the input value is empty, setError for the input and focus on the input

**Screenshots**
![截圖 2020-12-18 下午6 57 05](https://user-images.githubusercontent.com/22350321/102607554-71198e00-4163-11eb-87d4-cdf61c16f473.png)

**Desktop (please complete the following information):**

- OS: iOS 11.0.1
- Browser : chrome
- Version : 87.0.4280.88

**Comment by markivancho** [comment]
https://codesandbox.io/s/react-hook-form-controller-with-input-focus-test-forked-vq4t5?file=/src/App.tsx
you should add `shouldFocus: true` to setError call, and attach ref from controller's render props to your input

**Comment by bluebill1049** [comment]
Thanks @markivancho! You are right.

**Comment by tin80122** [comment]
@markivancho  @bluebill1049  I see, thanks for helping!

**Comment by tin80122** [comment]
@bluebill1049  What if I don't call setError , are there any other ways to trigger focus after have errors?

**Comment by bluebill1049** [comment]
it should focus an input automatically during submit, what's your use case?

**Comment by tin80122** [comment]
@bluebill1049  After surveying, we found out that we missed the ref on input element.so we just fixed it.
Thanks for helping.
