### ISSUE TITLE
Not working with @material-ui/pickers ?

### ISSUE THREAD

**Issue by fjandakornid** [react-hook-form/react-hook-form#373]
**Describe the bug**
I am using material-ui pickers on a form and I can't find a way to register them with required validation (or any other validation). I've tried very method I found in the examples with no luck.

I created a sandbox with the problem: [https://codesandbox.io/s/youthful-hellman-xh1dm](https://codesandbox.io/s/youthful-hellman-xh1dm)

**To Reproduce**
1. Click on submit
2. See registered values and errors in console

**Expected behavior**
Should be an error in the errors collection since all fields are undefined

**Comment by waynebloss** [comment]
Here you go:

```jsx
import "date-fns";
import ReactDOM from "react-dom";
import React from "react";
import useForm from "react-hook-form";
import DateFnsUtils from "@date-io/date-fns";
import Grid from "@material-ui/core/Grid";
import Button from "@material-ui/core/Button";
import {
  MuiPickersUtilsProvider,
  KeyboardTimePicker,
  KeyboardDatePicker
} from "@material-ui/pickers";

/**
 * Custom validation function.
 * See issue near console.log("useEffect register"); line 72
 */
function required(displayName) {
  return function validateRequired(value) {
    // console.log("VALIDATING: ", displayName, value);
    return value !== null || `${displayName} is required.`;
  };
}
/**
 * Hook to run a handler once on mount and never again.
 * @param {() => void} handler Function to run on mount.
 * See https://reactjs.org/docs/hooks-reference.html#useeffect
 * See https://github.com/facebook/create-react-app/issues/6880
 * This function is mainly to provide a better signal to the developer than
 * knowing how `useEffect` works when you pass an empty array. It also helps to
 * get around warnings raised by `react-hooks/exhaustive-deps` and we use it
 * instead of `// eslint-disable-next-line react-hooks/exhaustive-deps`.
 * We only run the handler once, so we don't care if dependencies change!
 */
function useOnMount(handler) {
  return React.useEffect(handler, []);
}

// Material-ui pickers need a null if you want to start them off as blank.
const defaultValues = {
  eventDate: null,
  startTime: null,
  endTime: null
};

function App() {
  const { errors, getValues, handleSubmit, register, setValue } = useForm({
    defaultValues
  });

  const onSubmit = data => {
    console.log("DATA: ", data);
    // NOTE: onSubmit is never called when errors exist,
    // so the following will always be blank:
    // console.log("ERRORS: ", errors);
  };

  const handleDateChange = date => {
    console.log("eventDate CHANGED: ", date);
    setValue("eventDate", date);
  };

  const handleStartTime = date => {
    setValue("startTime", date);
  };

  const handleEndTime = date => {
    setValue("endTime", date);
  };

  useOnMount(() => {
    console.log("useEffect register");
    // ************************************************************************
    // ISSUE: Setting `required: true` here doesn't do anything at all.
    // I had to write my own validation function.
    // ************************************************************************
    register(
      { name: "eventDate", type: "text" },
      { validate: required("Event date") }
    );
    register(
      { name: "startTime", type: "text" },
      { validate: required("Start time") }
    );
    register(
      { name: "endTime", type: "text" },
      { validate: required("End time") }
    );
  });

  const values = getValues();

  console.log("RENDERING VALUES: ", values);
  console.log("RENDERING ERRORS: ", errors);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <MuiPickersUtilsProvider utils={DateFnsUtils}>
        <Grid container spacing={3}>
          <Grid item xs={12} sm={4}>
            <KeyboardDatePicker
              id="eventDate"
              name="eventDate"
              label="Event date"
              format="dd.MM.yyyy"
              disablePast
              margin="normal"
              disableToolbar
              fullWidth
              value={values.eventDate}
              onChange={handleDateChange}
              KeyboardButtonProps={{
                "aria-label": "change date"
              }}
              error={errors.hasOwnProperty("eventDate")}
              helperText={errors.eventDate && errors.eventDate.message}
            />
          </Grid>
          <Grid item xs={12} sm={4}>
            <KeyboardTimePicker
              id="startTime"
              name="startTime"
              label="Starts at"
              margin="normal"
              ampm={false}
              fullWidth
              value={values.startTime}
              onChange={handleStartTime}
              KeyboardButtonProps={{
                "aria-label": "change start time"
              }}
              error={errors.hasOwnProperty("startTime")}
              helperText={errors.startTime && errors.startTime.message}
            />
          </Grid>
          <Grid item xs={12} sm={4}>
            <KeyboardTimePicker
              id="endTime"
              name="endTime"
              label="Ends at"
              margin="normal"
              ampm={false}
              fullWidth
              value={values.endTime}
              onChange={handleEndTime}
              KeyboardButtonProps={{
                "aria-label": "change end time"
              }}
              error={errors.hasOwnProperty("endTime")}
              helperText={errors.endTime && errors.endTime.message}
            />
          </Grid>
        </Grid>
      </MuiPickersUtilsProvider>

      <Button
        id="submit"
        name="submit"
        type="submit"
        variant="contained"
        color="primary"
        fullWidth
      >
        Create
      </Button>
    </form>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

From https://codesandbox.io/s/vigorous-jones-pyee5

**Comment by waynebloss** [comment]
There does seem to be an issue with `react-hook-form` not setting errors when `required: true` is used in the custom `register` call. I thought the problem was in [`validateField.ts` on line 50](https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/validateField.ts#L50) but even when I remove `type: "text"` from the calls to `register()`, it doesn't work without my custom validation function.

Some things to note:

- Nothing seems to change when I call `register` with `type: "text"` or `type: "custom"` or remove it altogether. [The docs](https://react-hook-form.com/api#register) recommend `type: 'custom'`.
- The call to `register` in your original code had `required: true` in the first argument. However, my `validate` function will not work unless it's in the second argument. When I tried to put `required: true` in the second object instead of a custom validation function, that didn't work either. The docs don't mention a second argument for `register` but the typescript type and the intellisense show it.
- Compare your code to mine to see what else I changed. For instance, getting error messages out of the `errors` object. I left other information in the comments.

**Comment by fjandakornid** [comment]
Thank you so much.. works like a charm :) I also added a call to triggerValidation({ name: 'eventDate' }) to the on-change-handlers since the inputs' errors weren't clearing when changed.

I'll leave this issue open due to the things @waynebloss talked about in the earlier comment. I would guess this is only a workaround.

**Comment by bluebill1049** [comment]
thanks @waynebloss, also @fjandakornid what's the reasoning issue? you can also trigger validation during setValue as well FYI 
https://react-hook-form.com/api#setValue

**Comment by bluebill1049** [comment]
a custom register should be `register({ name: 'test' }, { required: true })` @waynebloss, can you verify it having issue with requried?

**Comment by bluebill1049** [comment]
<img width="1022" alt="Screen Shot 2019-10-16 at 7 22 38 am" src="https://user-images.githubusercontent.com/10513364/66866792-c1d4aa80-efe5-11e9-8afe-7e5473328d73.png">

**Comment by fjandakornid** [comment]
> thanks @waynebloss, also @fjandakornid what's the reasoning issue? you can also trigger validation during setValue as well FYI
> https://react-hook-form.com/api#setValue

The need to use a custom validator. The { required: true } as a second parameter does not seem to be working.
And thanks for the setValue shouldValidate tip.. didn't see it :)

**Comment by bluebill1049** [comment]
Have u tested and debug what’s root cause? I have a feeling to do with the value been set

**Comment by bluebill1049** [comment]
`required: true` works: https://codesandbox.io/s/weathered-microservice-whh8y-to-delete-whh8y

**Comment by waynebloss** [comment]
@bluebill1049 OK, here is the bug - it doesn't work when you set `type: "custom"`.

https://codesandbox.io/s/weathered-microservice-whh8y-to-delete-zugnl

**Comment by bluebill1049** [comment]
oh! thanks @waynebloss i will patch that soon.

**Comment by bluebill1049** [comment]
patched `react-hook-form@3.24.1-beta.2` thanks @waynebloss

**Comment by bluebill1049** [comment]
i will release this soon, after we solve the type issue with react native

**Comment by cristian-eriomenco** [comment]
I don't know if this helps but i managed to get it working with validation, defaultValues, outline style, without any hacks and overrides.

[Sandbox Here](https://codesandbox.io/s/react-hook-form-controller-h4h6v?file=/src/index.js)

**Comment by bluebill1049** [comment]
Thanks @cristian-eriomenco for sharing solution.

**Comment by PathAbhi** [comment]
> I don't know if this helps but i managed to get it working with validation, defaultValues, outline style, without any hacks and overrides.
> 
> [Sandbox Here](https://codesandbox.io/s/react-hook-form-controller-h4h6v?file=/src/index.js)

The same code in TypeScript, however, throws the error: `Type '{}' is missing the following properties from type 'BasePickerProps': value, onChange  TS2739`

As per Material-UI pickers (v3.2.9) [documentation](https://material-ui-pickers.dev/getting-started/usage): 

> @material-ui/pickers ... components are controlled, meaning that it's required to pass the value and onChange props.

**Comment by alexanderomnix** [comment]
> > I don't know if this helps but i managed to get it working with validation, defaultValues, outline style, without any hacks and overrides.
> > [Sandbox Here](https://codesandbox.io/s/react-hook-form-controller-h4h6v?file=/src/index.js)
> 
> The same code in TypeScript, however, throws the error: `Type '{}' is missing the following properties from type 'BasePickerProps': value, onChange TS2739`
> 
> As per Material-UI pickers (v3.2.9) [documentation](https://material-ui-pickers.dev/getting-started/usage):
> 
> > @material-ui/pickers ... components are controlled, meaning that it's required to pass the value and onChange props.

Try using the render props of the Controller component, works fine with typescript, the props provided by the Controller have the onChange, onBlur, needed to the datapicker component, so no need to pass it manually.

The example bellow works fine with typescript

```
<MuiPickersUtilsProvider locale={brLocale} utils={DateFnsUtils}>
<Controller
  name="birthdate"
  control={control}
  render={({ ref, ...rest }) => (
    <KeyboardDatePicker
      defaultChecked={false}
      margin="normal"
      id="date-picker-dialog"
      label="Data de nascimento"
      format="dd/MM/yyyy"
      animateYearScrolling
      invalidDateMessage="Data inválida"
      views={["year", "month", "date"]}
      cancelLabel="Cancelar"
      openTo="year"
      {...rest}
    />
  )}
/>
</MuiPickersUtilsProvider>
```
