### ISSUE TITLE
Not working with PrimeReact framework

### ISSUE THREAD

**Issue by jjayaraman** [react-hook-form/react-hook-form#374]
Not working with PrimeReact framework. Is this a known issue, please?

I tried in their component like this. And the errors object does not capture any error 

	<InputText id="neatMaterialCost" className="field" value={price.neatMaterialCost} 
		onChange={handleOnChange} onBlur={handleOnBlur} placeholder="Neat material cost"
		ref={register({ required: true })} />

**Comment by waynebloss** [comment]
The maintainer is going to ask you to create a codesandbox to demonstrate your issue.

You can click one of [the examples](https://github.com/react-hook-form/react-hook-form/tree/master/examples#examples) and just start editing it to add your packages and so forth.

**Comment by mertsincan** [comment]
Hi,

Please see; https://primefaces.org/primereact/showcase/#/reacthookform
