### ISSUE TITLE
Prefilling inputs

### ISSUE THREAD

**Issue by timotgl** [react-hook-form/react-hook-form#375]
It wasn't clear to me from https://react-hook-form.com/api#setValue how I would go about prefilling form inputs (from a redux store for example). Calling `setValue` in a function component causes too many re-renders and is probably the wrong way anyway, but `register` doesn't seem to have any parameter to add an initial value (**not** a placeholder).

**Comment by waynebloss** [comment]
You can use the [reset](https://react-hook-form.com/api#reset) function like this:

```js
reset({ field1: "value1", field2: "value2" });
```

If you are making a single form to edit a list of things all at once, see the `Field Array` example [here](https://github.com/react-hook-form/react-hook-form/tree/master/examples#examples)

and then you will want to see the notes on [my issue](https://github.com/react-hook-form/react-hook-form/issues/371) about how to transform data to/from the server for the `Field Array`.

My code sandbox for that issue uses `reset` on line 68 - https://codesandbox.io/s/react-hook-form-array-fields-8ngx5

**Comment by waynebloss** [comment]
If your component gets a prop that has all the initial data, you can just call `reset` inside of a `useEffect` handler that depends on the prop with the initial values. e.g.

```js
React.useEffect(() => { reset(myProp); }, [myProp]);
```

**Comment by bluebill1049** [comment]
thanks @waynebloss you can only prefill inputs during `useForm` with `defaultValues`

**Comment by timotgl** [comment]
Thanks @waynebloss and @bluebill1049 using `useEffect` with `reset` or `setValue` inside worked, as well as `defaultValues`. The latter was what I was actually looking for I think.

**Comment by bluebill1049** [comment]
fantasy @timotgl 👍

**Comment by bluebill1049** [comment]
by the way, you can join https://spectrum.chat/react-hook-form sometimes the community will reply your questions quicker too :)
