### ISSUE TITLE
FormState isValid lags behind when used inside an onBlur handler

### ISSUE THREAD

**Issue by jannisg** [react-hook-form/react-hook-form#3750]
**Describe the bug**
When accessing `formState` inside a function that is triggered `onBlur`, the `isValid` value is lagging 1 render cycle behind.

**To Reproduce**

1. Go to https://codesandbox.io/s/bug-report-onblur-handler-and-formstate-desync-8qzk4
2. Click on the first "First Name" field
3. Click off the field to trigger the blur handler
4. Check console log which shows that `formState.isValid` is `true` even though `formState.errors` already contains the "required" error

Perhaps of note:
- This happens for both `mode` `"onBlur"` and `"onChange"`
- and for both `Controller` and `<input ref={register(...)} />`.

**Codesandbox link (Required)**
https://codesandbox.io/s/bug-report-onblur-handler-and-formstate-desync-8qzk4

**Screenshot**
Probably easier to just use the codesandbox tbh but hey, maybe it helps :)
![image](https://user-images.githubusercontent.com/109211/102824120-13c25d00-4441-11eb-9c9d-e20e9ff8d9df.png)

**Expected behavior**
I would expect that `formState` behaves holistically in that, if `formState.errors` has an error in in `formState.isValid` should not be out of sync with its own `formState` properties and values.

---

Is there a better way to assess the overall form's validity inside an `onBlur` handler that I'm missing?

The use case is basically to persist the field values if the form is valid (but hasn't been submitted yet).

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#formState

> Important: formState is wrapped with Proxy to improve render performance, so make sure you invoke or read it before render in order to enable the state update. This reduced re-render feature only applies to the Web platform due to a lack of support for Proxy in React Native.

we are using Proxy to detect subscription to the form state, it should be read before the callback, so just destruct the form state should resolve this issue.

**Comment by jannisg** [comment]
Wow, my apologies, I even read that section before posting and just completely misunderstood this sentence from the docs:
> This object contains information about the form state. If you want to subscribe to formState update at useEffect, **make sure that you place the entire formState in the optional array.**

I thought I was meant to **not** put the individual flags in and instead add the whole `formState` to my dependencies array.

Thanks for clearing that up :)

**Comment by bluebill1049** [comment]
@jannisg let me know how can we make this a bit more clear, in fact in the next major version we going to rely on Proxy to optimize `formState` further.

I have just update the doc to make that section more prominent.

<img width="973" alt="Screen Shot 2020-12-22 at 10 38 47 am" src="https://user-images.githubusercontent.com/10513364/102832228-e1652f80-4441-11eb-95af-4db4de12ac74.png">

any feedback welcome and PR too 👍

**Comment by jannisg** [comment]
I can provide some quick feedback now, but would also be happy to contribute a PR but that would be after Christmas since I'm still on a work deadline currently :( 

**Feedback:**
- Show a destructuring example within the useForm call, example:
```js
const {
  handleSubmit,
  formState: {
    isDirty,
    isValid,
    dirtyFields,
    touched,
    errors
  }
} = useForm();
```

That way you don't even need to deal with the `formState` variable in your continued React function/flow and as far as I now understand you would never really need the `formState` Proxy directly anyway? (Might be wrong about the use case)

- A Do/Don't example for the `useEffect` and maybe `useCallback` usage, so just in addition to the existing, we could have an example of how to do it properly.

- If there is a use-case for actually handling the `formState` object as a whole and not just its parts individually in your react code, perhaps a callout on such a use case would be handy? (I see there is a mention of "subscribing to `formState` in a `useEffect`" in the docs currently but I'm not entirely sure when/why I would use that to be honest.

---

Happy to help contribute once I'm done with this deadline but maybe the above helps a little already :)

**Comment by jannisg** [comment]
@bluebill1049 sorry to keep posting on this thread but I have updated the example to more accurately reflect my local dev issue around the lagging flag, and even though I am destructuring `formState` ahead of time now, it seems to still lag behind.

Maybe you have another idea?
https://codesandbox.io/s/bug-report-onblur-handler-and-formstate-desync-8qzk4?file=/src/index.js

**Steps**
(fields are empty on load)
1. type "test" in both fields
2. blur the second field, you will find that `isValid` is `false` even though `errors` is `{}`

I can't figure out what's causing this… I am sort of assuming it's because I have async logic within my `persistValues` function?

![image](https://user-images.githubusercontent.com/109211/102839111-a45e6480-4464-11eb-9345-b5b95a89f7a8.png)

**Comment by bluebill1049** [comment]
That's because `onBlur` is happening before `formState` update, because `formState` update is async.

https://codesandbox.io/s/bug-report-onblur-handler-and-formstate-desync-forked-dgl6b?file=/src/index.js

**Comment by jannisg** [comment]
Ah okay, thank you.

Is there any way to run `onBlur` logic _only_ if the form is valid after the validation?

I've tried (within the `onBlur` handler) to use `await trigger()` to force a full validation (https://codesandbox.io/s/bug-report-onblur-handler-and-formstate-desync-forked-06uqx?file=/src/index.js) but that seems to then supersede the `mode: "onBlur"` logic of `useForm` and will show errors on fields you haven't touched yet.

There is no way to run something like `await trigger()` without actually applying the errors is there?

**Comment by bluebill1049** [comment]
what about this?

`onBlur={() => isValid && run()}`

**Comment by jannisg** [comment]
That has the same issue unfortunately since when `onBlur` executes it will still be `false` so `run()` will never execute until a field triggers `onBlur` _after_ the previous update has set it to `true`.

Example: https://codesandbox.io/s/bug-report-onblur-handler-and-formstate-desync-forked-06uqx?file=/src/index.js

**Comment by bluebill1049** [comment]
oh you want onBlur fire delay with formState update, you may need to keep an extra state and do at useEffect then.

**Comment by jannisg** [comment]
Just thought I'd pop back in to post my working solution based on a combo of `useState` and `useEffect` which listens to `formState`.

https://codesandbox.io/s/bug-report-onblur-handler-and-formstate-desync-forked-18lt8?file=/src/index.js

This is the best I could come up with and it seems to work rather nicely I think, any feedback appreciated of course 😄 

Thanks for all your help throughout this journey 👍

**Comment by bluebill1049** [comment]
LGTM! no worries @jannisg
