### ISSUE TITLE
Have a config or option to allow Dot and Bracket chars to be in the name property 

### ISSUE THREAD

**Issue by ieow** [react-hook-form/react-hook-form#3755]
**Is your feature request related to a problem? Please describe.**
Dot (.) chars and bracket ([]) in property names result in nested object

**Describe the solution you'd like**
Have a config or option to allow Dot and Bracket chars to be in the name property instead of nested object

**Describe alternatives you've considered**
none

**Comment by ieow** [comment]
#3351 
#3199 
#3335 
#676

**Comment by bluebill1049** [comment]
Thanks for the feature request and for collecting all the related issues.

**Comment by nspaeth** [comment]
It would be great if anywhere that you provide a field name that accepts a path in `.` format, you could also instead provide a path in array form like it is done in in https://ramdajs.com/docs/#path.

E.g., `setvalue(['listOfPeople', 0, 'firstName'], 'bob')`

**Comment by bluebill1049** [comment]
This is most likely not going to happen as we going toward strictly typed form in V7, `dot` syntax is import for as get object and array filed right.

**Comment by SunShinewyf** [comment]
I also have met this problem, I want to avoid the Dot and Bracket feature

**Comment by ThomasRedstone** [comment]
I've also run into this, but it is oddly inconsistent - which can leave me with duplicates, and no idea which is the latest value!
I'll substitute the dots now, but it has been a real head scratcher!

**Comment by xahy** [comment]
It would be great to just switch off the nested attributes to the dot feature.

**Comment by nmenal** [comment]
@bluebill1049 are you planing on implementing this request please ?

**Comment by bluebill1049** [comment]
If you need this feature, you can use V3/v4 which is a flat structure. Going forward this feature is not compatible with TS(type safe) and will not be worked on.

**Comment by r-raymond** [comment]
I've also just ran into this, after debugging for a couple of hours. I think as a minimum you need to mention this clearly in the documentation, I can't find a trace anywhere. This is very surprising behavior.

**Comment by Moshyfawn** [comment]
[`register` rules RHF docs section](https://react-hook-form.com/api/useform/register#main)
![image](https://user-images.githubusercontent.com/16290753/150423239-59c05419-b139-44ae-b1dc-8bec9f0ae52c.png)
