### ISSUE TITLE
Release description should also include TS changes

### ISSUE THREAD

**Issue by finom** [react-hook-form/react-hook-form#3756]
**Describe the bug**
I have upgraded from version 6.11.3 to 6.13.1 and got the following error:

```
ERROR in /...path_to_component/index.tsx
./.../index.tsx
[tsl] ERROR in /.../index.tsx(2,10)
      TS2724: '"../../../../node_modules/react-hook-form/dist"' has no exported member named 'ValidationRules'. Did you mean 'ValidationRule'?
 @ ./components/index.ts 29:0-63 29:0-63
 @ ./Root/ErrorBoundary.tsx 26:0-50 51:33-41 55:29-35
 @ ./Root/index.tsx 26:0-44 29:29-42
 @ ./index.tsx

```
And have to figure out how to fix that. Unfortunately releases don't explain such changes, but they should (at least I didn't find corresponding information). Types are really important part of the library, and their changes (especially types removal) should be meant as breaking changes with all corresponding responsibility. If you don't like to publish a major version (that's an arguable question) then please at least describe what was changed/removed and what developer needs to do to make an upgrade. This is not the first time when I need to spend some time figuring type changes out by myself.

All additional issue template parts are irrelevant.

Thank you. I hope fixing this "logistics" issue will make this amazing library even better.

**Comment by bluebill1049** [comment]
hey, @finom thanks for the note. This could or should be avoided, I have included all the change information in the Change log: 

https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md

**Comment by finom** [comment]
@bluebill1049 thank you! Do you mean all TS changes always posted at CHANGELOG.md?

**Comment by bluebill1049** [comment]
> @bluebill1049 thank you! Do you mean all TS changes always posted at CHANGELOG.md?

yes, that rename was my bad...
