### ISSUE TITLE
Bugs that default keyboard opens on the the password form in RN on iOS devices

### ISSUE THREAD

**Issue by match** [react-hook-form/react-hook-form#3757]
**Describe the bug**
There is a bug that the default keyboard opens under the password form.
Additionally, when the keyboard opens, it freezes for 10 or more seconds.
I expect the keyboard for password to open, but the default flick keyboard is open when tapping the form.
The password form is create by `ReactNative.TextInput` with `secureTextEntry={true}` option.
This bug is only occur in RN on iOS devices.

**To Reproduce**

1. Create a form by `useForm`
2. Place one normal form and two secureTextEntry forms
3. Select the password form then open the default keyboard

**Codesandbox link (Required)**
https://gist.github.com/match/f4448a79096047b16dab256750709fdb

**Expected behavior**
Open the password keyboard when RN TextInput is in password mode

**Screenshots**
![image](https://user-images.githubusercontent.com/303984/102884587-32524380-4495-11eb-881b-1d8add09f3a0.png)

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**

- Device: iPhone Xs
- OS: iOS 14.2
- Browser: N/A [native]
- Version: 6.9.2

**Additional context**
-

**Comment by bluebill1049** [comment]
I am not sure this is hook form issue :(

**Comment by match** [comment]
Thanks for the reply.

I try this code without `react-hook-form`:
```
import React from 'react';
import { TextInput, View } from 'react-native';

export default function App() {
  return (
    <View style={{flex: 1, justifyContent: 'center'}}>
        <TextInput
          style={{margin: 20, borderWidth: 1, paddingVertical: 8}}
          keyboardType="default"
        />
        <TextInput
          style={{margin: 20, borderWidth: 1, paddingVertical: 8}}
          secureTextEntry={true}
        />
        <TextInput
          style={{margin: 20, borderWidth: 1, paddingVertical: 8}}
          secureTextEntry={true}
        />
    </View>
  );
}
```

It reproduce the bugs. It is not a hook form issue clearly... So I will close this.
