### ISSUE TITLE
useWatch is returning undefined in first render using useFieldArray

### ISSUE THREAD

**Issue by guicovred** [react-hook-form/react-hook-form#3758]
**Describe the bug**

If we use `useWatch` inside a component appended to `useFieldArray` to watch a field that is outside this field array (an existing field on the form), `useWatch` returns `undefined` in the first rendering.

if we append another component, all the first ones are able to access the value, the problem is always with the newly appended.

**To Reproduce**

Already prepared a CSB with the problem in question:

1 - Type something in the field
2 - Click on "Append item" button
3 - See result on console

In CSB I also put a comparison with `form.watch`, where the problem does not occur, but I believe there is a difference in functionality between them, since `useWatch` isolate re-rendering at the component level.

**Codesandbox link (Required)**

https://codesandbox.io/s/nostalgic-fire-grh5p

**Expected behavior**

I believe that `useWatch` should be able to get the values of existing fields on the form in the first rendering of the component added to the field array.

**Desktop:**

- OS: macOS Catalina 10.15.6
- Browser chrome
- Version 83.0.4103.116

**Comment by markivancho** [comment]
![image](https://user-images.githubusercontent.com/30623974/102900577-2b1b3d80-4475-11eb-8d5f-e69dcdebd288.png)
https://react-hook-form.com/api/#watch
I think it's expected and documented

**Comment by bluebill1049** [comment]
Thanks for the issue, looks like this is a design flaw with `useWatch`, as the first re-render at `useWatch` need to generate a unique hash, the good news is we are addressing this issue in the next major release.

you can work around this issue with the following:
https://codesandbox.io/s/usewatch-on-usefieldarray-forked-5qb42?file=/src/App.js

**Comment by guicovred** [comment]
> you can work around this issue with the following:
> https://codesandbox.io/s/usewatch-on-usefieldarray-forked-5qb42?file=/src/App.js

Okay, I realized now that this is not related to `useFieldArray` as I initially imagined, sorry about the mess.

> Thanks for the issue, looks like this is expected, as the first re-render at `useWatch` need to generate a unique hash at `useEffect` and set up the initial state and etc while `watch` is already been initialized at `useForm`. Maybe it's worth including that information in the doc as well.

Well, it makes a lot of sense to me what you said. 

Thinking about it now, it makes sense returning `undefined`, since `watch` serves mainly to watch the changes that occur and not to access the existing values, right!? (although some things would be easier if that were possible).

> (also will look to improve that on the next major version)

Well, you're in charge! Let me know if I can help with something.

Thank you for your time!

**Comment by bluebill1049** [comment]
> Thinking about it now, it makes sense returning `undefined`, since `watch` serves mainly to watch the changes that occur and not to access the existing values, right!? (although some things would be easier if that were possible).

I think you can put `fields` as `defaultValue` (`useWatch`) to avoid the initial render `undefined`.

```
useWatch({
  name: 'fieldArray',
  defaultValue: fields
})
```

I will include some information regarding this in the doc as well. Thanks for putting everything up in this issue and your time. 🙏

**Comment by bluebill1049** [comment]
> Note: when useWatch mounted, it will return defaultValue or defaultValues from useForm and then subscribe to the input changes.

The above note added to the doc.
