### ISSUE TITLE
Pattern in Register Options not validating correctly

### ISSUE THREAD

**Issue by FranAmorim** [react-hook-form/react-hook-form#3759]
**Describe the bug**
Seems like pattern doesn't work properly, the value is accepted if the string contains the pattern.
The expected behavior is to only accept the value according to the pattern.

**To Reproduce**

1. Go to the example in RHF Documentation (https://codesandbox.io/s/react-hook-form-validation-pattern-zgbut?file=/src/App.jsx)
2. Name input and type **123abc**
3. The input value is accepted

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-validation-pattern-zgbut?file=/src/App.jsx

**Expected behavior**
Only accept the value according to the pattern.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version Chromium: 87.0.4280.101

**Comment by bluebill1049** [comment]
It's working, if you press the submit button.
