### ISSUE TITLE
FormContext cause typescript error

### ISSUE THREAD

**Issue by iamchanii** [react-hook-form/react-hook-form#376]
**Describe the bug**
when I use `useForm()` hook with custom interface (or type) as generics, `FormContext` props is not compatiable with values as it returned.

**Expected behavior**
It should be not cause Typescript error even I try to use `FormContext` and `useForm` hook with generic

**Screenshots**
![2019-10-16 14-07-15 2019-10-16 14_08_01](https://user-images.githubusercontent.com/26643843/66889818-c1a4d100-f01e-11e9-98d6-51c85a93c3f3.gif)
```
Error:(152, 22) TS2322: Type '{ children: Element; register: { <Element_1 extends ElementLike = ElementLike>(validateRule: Partial<{ required: string | boolean; min: string | number | { value: ReactText; message: string; }; max: string | number | { value: ReactText; message: string; }; maxLength: string | ... 1 more ... | { ...; }; minLength: st...' is not assignable to type 'FormProps<IAdminLayoutCreateFormData>'.
  Types of property 'reset' are incompatible.
    Type '(values?: IAdminLayoutCreateFormData) => void' is not assignable to type '(values?: Record<string, any>) => void'.
      Types of parameters 'values' and 'values' are incompatible.
        Type 'Record<string, any>' is missing the following properties from type 'IAdminLayoutCreateFormData': name, description, isCover, widthSize, and 3 more.
```

**Desktop (please complete the following information):**
 - OS: macOS catalina
 - Browser: Chrome 
 - Version: 77.0.3865.90 64bit
 - Typescript: 3.5.1
 - react-hook-form: 3.24.0

**Additional context**
- I made a interface to use with `useForm` hook.
```typescript
export interface IAdminLayoutCreateFormData {
    name: string;
    description: string;
    isCover: boolean;
    widthSize: number;
    heightSize: number;
    visible: boolean;
    isMultivision: boolean;
}
```
- Then used it
```typescript
const formMethods = useForm<IAdminLayoutCreateFormData>(formName.adminLayoutCreateForm, options);
// FYI: I made a custom hook for handle error code via redux state... so you don't have to know and think about why this hook got 2 args
```

**Comment by iamchanii** [comment]
If you need a codesandbox to reproduce this issue, I will be, but I have no time currently. please give me some days 🙏thanks!

**Comment by bluebill1049** [comment]
thanks @iamchanii no worries thanks for the detailed issue report. @stramel looks like we still having an issue with FormContext, could you please assist?

**Comment by stramel** [comment]
I can take a look but a codesandbox would make it a lot easier to figure out.

**Comment by bluebill1049** [comment]
yea @stramel let's wait for a codesandbox :)

**Comment by iamchanii** [comment]
I try to reproduce this issue in codesandbox, finally I have see what is a mistake as I made. as I told in main text, I made a custom hook to set errors from redux state if api request failed. yes, it cause this issue.

it lost its type even I set a generic type for original `useForm` hooks. so I think I have to set return type to custom hook.

```ts
const useForm = <Data>(formName: TFormName, props: Options<Data>): ??? /* 👈*/ => {
    const formContext = useFormHook<Data>(props);
    // ...
};
```

for solve this problem, I need the interface(or type) of return type what is useForm hook returned or I have to refactor my custom hooks.

conclusion: maybe this issue is not a bug, just need the interface(or type) is returned from useForm hook.

@bluebill1049 Can you remove bug label form this issue? I will close this issue. and sorry to you and @stramel cause I made you waste a time. 🙏

**Comment by bluebill1049** [comment]
thanks, @iamchanii 👍 and @stramel to follow up this issue ❤️
