### ISSUE TITLE
Getting Unknown Type for Form when using watch

### ISSUE THREAD

**Issue by Tooluloope** [react-hook-form/react-hook-form#3765]
**Describe the bug**

I have a Form that can take precisely two forms. So I did a union type for `useForm`. when watching for some keys that are unique between the two types, I get unknown for them.

```
interface fileType  {
  file: [File]
}
interface AnotherfileType  {
  files: [File]
}
export default function App() {


	const { watch } = useForm<fileType|AnotherfileType>() 
  

  const watchFile = watch('file')
  
  
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
    </div>
  );
}
```

**Codesandbox link (Required)**
https://codesandbox.io/s/interesting-williamson-zebv7?file=/src/App.tsx

**Expected behavior**
Watch function should give me the type of key already declared in the union type

**Comment by bluebill1049** [comment]
we don't support union type for the `useForm` at the moment, you will have to go with intersection types.

**Comment by euphocat** [comment]
Hello @bluebill1049 sorry to re-open this, but can you give more info about the union type limitation? Is there any typescript limitation about this ? I am a bit disappointed as I heavily used them in react-hook-form 6 and now the migration to 7 is pretty hard for me.

**Comment by bluebill1049** [comment]
> Hello @bluebill1049 sorry to re-open this, but can you give more info about the union type limitation? Is there any typescript limitation about this ? I am a bit disappointed as I heavily used them in react-hook-form 6 and now the migration to 7 is pretty hard for me.

This is one of the trade-off going for strictly typed form, as input `name` now is checked against with type definition, however, this raises limitations with union type and recursive type with template string literal, with my knowledge and @kotarella1110 we couldn't figure out a way to support that. I think it's a limitation with TS template string literal.

**Comment by euphocat** [comment]
Thank you for your answer 👍 I hope TS will evolve in a way we could achieve this. After thinking about this problem, I figured that having union types to define a form is maybe not the best idea though... However I think it would worth mentionning it in a FAQ section.

**Comment by bluebill1049** [comment]
> Thank you for your answer 👍 I hope TS will evolve in a way we could achieve this. After thinking about this problem, I figured that having union types to define a form is maybe not the best idea though... However I think it would worth mentionning it in a FAQ section.

sounds good to me, I will include some detail on this one. String template literal definitely has its own limitation, but I think we are moving forward for input name type check, before that we have zero checks on input names, basically `as any` for any object or array inputs, it only worked for flat form.
