### ISSUE TITLE
Watch the result of a selector function

### ISSUE THREAD

**Issue by fabiosantoscode** [react-hook-form/react-hook-form#3766]
**Is your feature request related to a problem? Please describe.**

I have a form where the user inserts a list of e-mails (`useFieldArray` is used). I would like to know if at least one of these e-mails is filled in, to choose the text of the submit button ("invite", or "skip").

I can grab fieldArray.fields.length, but this doesn't tell me which fields are filled in. I can also use watch, but every time the user types, the form is re-rendered.

**Describe the solution you'd like**
I would like to be able to pass a selector to useWatch or watch, like so:

```
const { select, ... } = useForm(...)

const hasAnyFilledInEmails = select(fields => fields.emails.some(email => email != ""))
```

This would only cause an update if my function returns a different boolean, minimizing re-renders.

**Describe alternatives you've considered**
For now I left a `watch()` call in my component, and it works fine, even if my consciousness tells me that I shouldn't be re-rendering so much.

Something else I've considered is to split the submit button into another component, and useWatch inside of it to minimize re-renders. 

I've also considered listening to bubbled `input` events in the form, calling `getValues()` each time, and setting the value of a `useState`.

**Additional context**
Edit: I've added a [codesandbox](https://codesandbox.io/s/compassionate-thompson-rkhnv?file=/src/App.js) to illustrate the problem.

As you can see, "is any of these filled in" is correctly false, but when you type it doesn't turn true, because nothing is being watched. Adding `watch()` fixes the issue but re-renders too much.

**Comment by bluebill1049** [comment]
Thanks this feature is coming under the v7 proposal: https://github.com/react-hook-form/react-hook-form/discussions/3714. The only difference is it doesn't return a value, instead, you can probably pass useState inside of it. Feel free to join the discussion and comment there.
