### ISSUE TITLE
Checkbox group, if registered the required to true, at least one input required?

### ISSUE THREAD

**Issue by subhendukundu** [react-hook-form/react-hook-form#377]
**Is your feature request related to a problem? Please describe.**
I am quite not sure if this is possible with the current version we have if we have it already how do I achieve it?

**Describe the solution you'd like**
So the idea is to have a group of checkboxes where at least one checked it required, right now I am passing `register({ required: true })` to all of my checkboxes, which kind of right as it behaving also weird at the same time as to fix the error I need to check all the checkboxes, ideally it should be at least one.
`<input type="checkbox" name="hey.1" ref={register({ required: true })} />`

**Additional context**
Codesandbox link
https://codesandbox.io/s/react-hook-form-form-context-bhqe0

**Comment by bluebill1049** [comment]
Hey @subhendukundu thanks for the detailed issue report and codesandbox. I believe you can use `validate` function and combine with `watch `

**Comment by subhendukundu** [comment]
Sure, Thanks for confirming. Yes, we could make it work. That's why I put the bug as a feature request, do you think it should work as I described by default or additional props?

**Comment by bluebill1049** [comment]
👍 it should work by default, you don't need additional props. I think i had an example somewhere but lost it...

**Comment by bluebill1049** [comment]
When I said working as default means use validate and watch functions.

**Comment by bluebill1049** [comment]
Wait, why u have different names? If u want to just check 1 of them checked then u should name them the same.

**Comment by bluebill1049** [comment]
If u want checked with different name then u can use validate plus watch.

**Comment by subhendukundu** [comment]
I added the same name in the example, still, it is asking to check all the input check.

**Comment by bluebill1049** [comment]
```
  <>
      <input type="checkbox" name="hey" ref={register} />
      <input type="checkbox" name="hey" ref={register} />
      <input type="checkbox" name="hey" ref={register({ required: true })} />
    </>
```

if you only need one of them, just assign one. I will update the doc about this.

**Comment by subhendukundu** [comment]
Umm, I meant, at least one of them to be checked. What I meant is something like http://jsfiddle.net/qyE97/

**Comment by bluebill1049** [comment]
sorry about the confusion... check issue on mobile doesn't help... i will post a codesandbox soon

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-form-context-5kmgh

**Comment by subhendukundu** [comment]
Thanks, That works! :)

**Comment by bluebill1049** [comment]
no worries @subhendukundu 👍

**Comment by bluebill1049** [comment]
btw next time usage related question, you can post in our spectrum channel too :)

**Comment by rofrol** [comment]
> https://codesandbox.io/s/react-hook-form-form-context-5kmgh

404

**Comment by bluebill1049** [comment]
@rofrol you will have to need to write a `validate` function to check one of them is checked

**Comment by DeBraid** [comment]
Might help some folks to consider this example of a validate function: 

`ref={register({ validate: v => v && v.length})}`

where the markup is something like: 

```
{storeIds.map((storeId) => (
  <div key={storeId}>
    <input
      type="checkbox"
      id={storeId}
      name="storeIds"
      value={storeId}
      ref={register({ validate: v => v.length > 0 })}
    />
    <label htmlFor={storeId}>{storeId}</label>
  </div>
))}
```

**Comment by Aryaman73** [comment]
@DeBraid could some explain how this is meant to work? Won't `v` only have information about that checkbox in particular? How would `v.length > 0` work?

**Comment by ShahriarKh** [comment]
> 
> 
> https://codesandbox.io/s/react-hook-form-form-context-5kmgh

The sandbox doesn't exist.

**Comment by gormonn** [comment]
Like that:
```javascript
const MailingDays = () => {
  const { control, register, getValues } = useFormContext();
  const { fields } = useFieldArray({ control, name: 'mailing_days' });

  const validate = useCallback(() => {
    const errorMessage = 'Choose format';
    const values = getValues(
      fields.map((v, index) => `mailing_days.${index}.value`),
    );
    const isValid = values.some((v) => v);
    return isValid || errorMessage;
  }, []);

  return (
    <Column>
      <Flex sx={{ gap: 12 }}>
        {fields.map((field, index) => (
          <DayBox
            key={field.id}
            day={weekDays[index]}
            index={index}
            {...register(`mailing_days.${index}.value`, { validate })}
          />
        ))}
      </Flex>
      <FormErrorContext name={'mailing_days.0.value'} />
    </Column>
  );
};```
