### ISSUE TITLE
Multiple array of check box not getting values properly .

### ISSUE THREAD

**Issue by nageshwari17** [react-hook-form/react-hook-form#3770]
**Describe the bug**

**To Reproduce**

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

**Expected behavior**

https://codesandbox.io/s/material-demo-forked-vy85c?file=/demo.js

**Desktop (please complete the following information):**

- OS: window
- Browser : Chrome
- Version: Window 10

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by nageshwari17** [comment]
@bluebill1049  I have updated issue as per template . Please go through it and do the need full
