### ISSUE TITLE
Multiple array of check box not getting values properly

### ISSUE THREAD

**Issue by nageshwari17** [react-hook-form/react-hook-form#3771]
Describe the bug
I am implementing filter in my application . multiple filter with respect to colors, fruits, size, etc ....
When I am trying get data with selected filters like in array format like

If I have checked fruits as orange, banana and from colors orange and pink .

Expected behavior
should give data as below format

`data: { fruits: [ orange, banana ], colors: [ pink, orange ] }
`
To Reproduce

1. Go to the sandbox
2. Check checkbox with two colors and fruits
3. Click on Submit
4. you can see selected values

Codesandbox link (Required)
https://codesandbox.io/s/material-demo-forked-vy85c?file=/demo.js

Desktop (please complete the following information):

OS: window
Browser : Chrome
Version: Window 10

**Comment by bluebill1049** [comment]
This is not an issue with Controller, what's called with `onChange`, it's what gets send to hook form.

```
const sortDataHere = () => // should return what's the value that's your expected.
<Controller render={(props) => props.onChange(sortDataHere()} />
```
