### ISSUE TITLE
`watch` is giving first item's value in the first render when there is 1 item in an array

### ISSUE THREAD

**Issue by ykaragol** [react-hook-form/react-hook-form#3773]
**Describe the bug**

While using `useFieldArray` with an array of items, `watch` returns wrong value at the first run.

**To Reproduce**

1. Use `useFieldArray` for an array of items and have an initial list for `defaultValues`.
2. Remove all rows properly by clicking `delete` buttons for each row
3. Create new row after removing all rows.
4. See that `watch` is giving the value of the initial list at the first run.

**Codesandbox link (Required)**

[A sandbox link forked from docs](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-q5nj1?file=/src/index.js)

0. See the first column calculating some data according second column
1. Delete all items by clicking delete
2. Append new one
3. See that there is a flicker on the first column that `Bill` is shown initially.

**Expected behavior**
It should not get that wrong value at initial render. (Because we want to have a calculation over that value and set as `defaultValue` to another input. But input gets wrong value.)

**Screenshots**
If sandbox not works, I can add.

**Desktop (please complete the following information):**

- OS: Mac OS
- Chrome
- Version: 6.11.0 (reproduced also in 6.13.1 too)

**Additional context**

**Comment by bluebill1049** [comment]
`watch` should not be used inside `render`, it's supposed to be invoked before `render`.

**Comment by ykaragol** [comment]
In the docs of `getValues`, it is saying:
> Important: You shouldn't use this method inside render.

But I didn't see anything about `watch`. 

How can I get the initial value of a field? Should I pass it from outside? But I don't want to have prop-drilling, can I get initial value from FormContext?

**Comment by bluebill1049** [comment]
there is an example under https://react-hook-form.com/api#watch
<img width="944" alt="Screen Shot 2020-12-28 at 9 23 52 am" src="https://user-images.githubusercontent.com/10513364/103180892-68a51e00-48ee-11eb-8ca5-5a66f7e09b2b.png">

```
import * as React from "react";
import { useForm, useFieldArray, ArrayField } from "react-hook-form";

function App() {
  const { register, control, handleSubmit, watch } = useForm();
  const { fields, remove, append } = useFieldArray({
    name: "test",
    control
  });
  const onSubmit = (data: FormValues) => console.log(data);
  
  console.log(watch("test")); 

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      {fields.map((field, index) => {
        return (
          <input
            key={field.id}
            name={`test[${index}].firstName`}
            defaultValue={field.firstName}
            ref={register()}
          />
        );
      })}
      <button
        type="button"
        onClick={() =>
          append({
            firstName: "bill" + renderCount,
            lastName: "luo" + renderCount
          })
        }
      >
        Append
      </button>
    </form>
  );
}
```
