### ISSUE TITLE
Focus on error + reset + Material UI

### ISSUE THREAD

**Issue by bianchi** [react-hook-form/react-hook-form#3784]
**Describe the bug**
Using render in controllers with Material UI:
If I use inputRef={props.ref} focus on error does not work but reset works.
If I use inputRef={register} focus on error works but reset does not.

**To Reproduce**

1. Go to CSB link, Case1 is default, you will see value is set from reset. Delete the value from the input, click submit. Will have error but no focus
2. In same CSB, change component to Case2 in App. You will see that reset value is not set. Click submit, focus on input works.

**Codesandbox link (Required)**
https://codesandbox.io/s/peaceful-surf-hky3e?file=/src/App.tsx

**Expected behavior**
Both cases should work reset and focus on error.

**Screenshots**
In my local computer, Case2 actually sets the value on reset but label overlaps value. Could not reproduce in CBS even with exactly same versions in all libs.
![image](https://user-images.githubusercontent.com/1824997/103152414-792a8c80-4766-11eb-9bcc-5bcedcfaead4.png)

**Desktop (please complete the following information):**

- OS: Linux Mint
- Browser: chrome
- Version 86.0.4240.111

**Comment by bluebill1049** [comment]
use Controller instead: https://react-hook-form.com/api/#Controller

**Comment by bianchi** [comment]
I am using controller, as you can see in CSB link

**Comment by bianchi** [comment]
@bluebill1049 can this be reopen?

**Comment by bluebill1049** [comment]
<img width="1295" alt="Screen Shot 2020-12-29 at 9 48 33 am" src="https://user-images.githubusercontent.com/10513364/103247438-0534f200-49bb-11eb-97d3-825bb27aa8a6.png">

This is all I can. how can i reproduce the issue?

**Comment by bianchi** [comment]
> <img alt="Screen Shot 2020-12-29 at 9 48 33 am" width="1295" src="https://user-images.githubusercontent.com/10513364/103247438-0534f200-49bb-11eb-97d3-825bb27aa8a6.png">
> 
> This is all I can. how can i reproduce the issue?

I was able to make it work based on another answer you gave in another issue. Had to destructure ref. Thank you
```
<Controller
	control={control}
	name="un_medida_primaria_decimais"
	defaultValue={2}
	render={props => {
	    const {ref, ...rest} = props;
	    return <TextField {...rest} inputRef={ref} required disabled={disabled} />;
	}}
/>
```
