### ISSUE TITLE
Significant performance drop on Draft.js and RHF 6.13.1

### ISSUE THREAD

**Issue by veekungx** [react-hook-form/react-hook-form#3785]
**Describe the bug**
When integrate with draft.js and RHF 6.13.X. After input a lot of text it start to drop some performance.
This issue **not** happed in RHF 6.12.X

**To Reproduce**
```
import React from 'react';
import { Controller, useForm } from "react-hook-form";
import { Editor, EditorState } from "draft-js";

function App() {
  const { control } = useForm({
    defaultValues: {
      draft: EditorState.createEmpty(),
    },
  });

  return (
    <div>
      <form>
        <Controller
          name="draft"
          control={control}
          render={({ value, onChange }) => {
            return <Editor editorState={value} onChange={onChange} />;
          }}
        />
      </form>
    </div>
  );
}
```
**GIF**
[![2563-12-27-19.03.04.gif](https://s2.gifyu.com/images/2563-12-27-19.03.04.gif)](https://gifyu.com/image/C6Ma)

**Codesandbox link (Required)**
- [useController@6.13.X](https://codesandbox.io/s/nifty-chaum-qt6dx?file=/src/App.js)
- [Controller@6.13.X](https://codesandbox.io/s/priceless-drake-9ljir?file=/src/App.js)

**Expected behavior**
- [Controller@6.12.X](https://codesandbox.io/s/bold-bassi-q56dl)

**Desktop (please complete the following information):**

- OS: macOS(Big Sur)
- Browser: Chrome
- Version: 87.0.4280.88

**Comment by bluebill1049** [comment]
can you provide more information and detail? perhaps perf measurement and see if it's worth it for us to spend time on fixing this.

**Comment by veekungx** [comment]
@bluebill1049 I provide some gif for you.

[![RHF 6.12 & 6.13](https://s2.gifyu.com/images/2563-12-27-19.03.04.gif)](https://gifyu.com/image/C6Ma)

When typing a lot of text or pasted. 6.13 start to jumpy and hang.

**Comment by bluebill1049** [comment]
we will use shallow clone instead of deep clone for object value.
