### ISSUE TITLE
Should `handleSubmit` add defaultValues that were not registered?

### ISSUE THREAD

**Issue by stramel** [react-hook-form/react-hook-form#379]
I'm currently using `defaultValues` as a quick way to throw together some data that I want on the submission but not actually in the form. I was a bit surprised when it wasn't there.

I looked through the code and it appears we are only putting data in for "registered fields". My question is should we just pass through any data for "non-registered fields" if it exists?

@bluebill1049 @barrymay

**Comment by bluebill1049** [comment]
I think I prefer input to get registered.

**Comment by stramel** [comment]
My example is 

```
useForm({
  defaultValues: {
    token: 'a.b.c',
    username: 'stramel'
  }
})
```

```
<form onSubmit={handleSubmit(onSubmitCallback)}>
  <input name="code" />
</form>
```

I expected `onSubmitCallback` to be called with:


```
{
  code: '123456',
  token: 'a.b.c',
  username: 'stramel'
}
```

**Comment by bluebill1049** [comment]
If data coming from external, I think it make sense to manually aggregate them. 
I think `defaultValues` service its purpose for inputs correctly right now.
