### ISSUE TITLE
Nested custom component refs don't work properly with Controller.

### ISSUE THREAD

**Issue by edimitchel** [react-hook-form/react-hook-form#3793]
**Describe the bug**
Ref is not properly use with nested components

I got a ref with only `focus` and the `name` property.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-controller-template-forked-68tu6?file=/src/index.js
2. Empty the field
3. Click on Submit
4. See in console the errors details and see that ref is empty..

We use components from a common library which use all `forwardRef` like in example.

**Expected behavior**
I expect to see the input ref information in the errors excerpt and in this case it's not.
I would like to get the field instance to being able to determine the type of my field ([if it's a checkbox](https://github.com/react-hook-form/react-hook-form/blob/8c198d88cb46e55a7ef709767726e6e8c56a3eab/src/utils/isCheckBoxInput.ts)).

**Screenshots**
![image](https://user-images.githubusercontent.com/2922851/103221674-7aed7f00-4923-11eb-93da-e7398cca7f4a.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Vivaldi (Chromium)
- Chrome Version 86

**Additional context**

**Comment by bluebill1049** [comment]
That's expected for Controller at v6, we don't store `ref` in Controller, expect that to be improved at v7.

**Comment by edimitchel** [comment]
Ok, then how could I do with custom component which I want to have a native behaviour (for my cheboxes for example) ?

Also, fields are validated using refs and DOM information (like type for getting the type of input).

**Comment by bluebill1049** [comment]
can you just use `regsiter` as that component already expose `ref`?

**Comment by edimitchel** [comment]
I'm encounter some issue with `register`, my ref is mutated as undefined using `register`.
I've tried all possibilities (`ref={register()}`, `ref={(ref) => register(ref, {})}`) and none works well.

**Comment by danieladarve** [comment]
@edimitchel  Hey mate did you end up solving this issue somehow?
