### ISSUE TITLE
In dev mode, wrong RegExp to match ref.name

### ISSUE THREAD

**Issue by coocooooo** [react-hook-form/react-hook-form#3794]
https://github.com/react-hook-form/react-hook-form/blob/60713238a4730e50512491f3205d67d7aa7744aa/src/useForm.ts#L919-L924

I read through the code, the purpose of RegExp is split  'test[index].name' into ['test', '.name'], but as boundary assertions **$** here, the RegExp won't work as expect. Am i right?

**Comment by bluebill1049** [comment]
can you provide some more details? This is just to help users to provide the correct name for the input name, feel free to send a PR to adjust that.

**Comment by coocooooo** [comment]
the next line is doc of hook `useFieldArray`
> Name of the field. Important: make sure name is in object shape: name=test[index].name as we don't support flat arrays.

so we can assume the name here is something like `test[1].name`. the `'test[1].name'.split(/\[\d+\]$/)[0]'` result to `['test[1].name']`. 

but the regexp `/\[\d+\]/` will work fine here

**Comment by coocooooo** [comment]
a pr later

**Comment by bluebill1049** [comment]
For a side note, the next major version we will use `.` instead for better type support.

```diff
- test[1].test
+ test.1.test
```

**Comment by coocooooo** [comment]
ok I check the test, the origin regexp is to prevent user to write name suffix with `[index]`, so origin regexp work fine. I misunderstand it. 

Feel free to close the issue

It seems next version is more clear

**Comment by bluebill1049** [comment]
no worries 👍 Thanks for the issue and PR as well ❤️
