### ISSUE TITLE
Losing validation functionality on hot reload

### ISSUE THREAD

**Issue by eterv** [react-hook-form/react-hook-form#3799]
I am making a project with next.js, and of course, I use hot-reloading feature.
So, when I modify my code, and then the browser is hot-reloaded.
but, I think that validation functionality does not work.

For example, you can see this link.

https://codesandbox.io/s/react-form-test-g8n2x?file=/src/App.js

first, I think that Next.js has a problem with hot reload.
but, same problem occurred at codesandbox.

So, am I using this library wrong? OR is this problem a bug?
please help me.

- OS: [e.g. iOS] : Mac, Windows
- Browser [e.g. chrome, safari] : chrome

**Comment by bluebill1049** [comment]
This is expected for v6 with fast refresh, we are improving that in v7. https://github.com/react-hook-form/react-hook-form/discussions/3714
