### ISSUE TITLE
Yup Schema Validation requiring number gives NaN error

### ISSUE THREAD

**Issue by giulianok** [react-hook-form/react-hook-form#3806]
**Describe the bug**
Requiring a field that's a type number with some restrictions gives the following error `X must be a `number` type, but the final value was: `NaN` (cast from the value `""`).`

There's an example in the documentation (https://react-hook-form.com/get-started#schemavalidation) that takes you to a codesandbox where I see the same error.

**To Reproduce**

1. Go to [codesandbox](https://codesandbox.io/s/react-hook-form-v6-validationschema-b3dib)
2. Click on Submit
4. See error under `age` input

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-v6-validationschema-b3dib

**Expected behavior**
Should handle empty string by default and provide a nicer error message

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: macOS Big Sur 11.1
- Browser; Chrome
- Version: 87.0.4280.88

**Smartphone (please complete the following information):**
Does not apply

**Additional context**
N/A

**Comment by bluebill1049** [comment]
Thanks, fixed.
