### ISSUE TITLE
Conditionally-rendered Checkbox watch value is array (even when using key)

### ISSUE THREAD

**Issue by JonathanWilbur** [react-hook-form/react-hook-form#3809]
**Describe the bug**

When I conditionally-render a checkbox, the watch value for that checkbox becomes an array once the form changes. This happens even when I use keys as described [here](https://react-hook-form.com/faqs#Whyisdefaultvaluenotchangingcorrectlywithternaryoperator).

**To Reproduce**

1. Toggle the value of a conditionally-rendered checkbox.

**Codesandbox link (Required)**

https://codesandbox.io/s/modest-goldberg-t7wn7?file=/src/App.tsx

**Expected behavior**

The watch value to always be a `boolean`.

**Desktop (please complete the following information):**

- OS: Microsoft Windows 10 Pro
- Browser: Microsoft Edge
- Version: 6.13.1

**Comment by ghostd** [comment]
Hi,

I think you lose the reference because the component hierarchy changes, so the react reconcilier destroy and recreate an other checkbox:
* in one case, the checkbox parent is the `FormControl`
* in a second case, the checkbox parent is the `Tooltip`

Try this:
```jsx
        <FormControl fullWidth={true} margin="dense" key="bloop">
          <Tooltip key="bloop" disableHoverListener={!blap} title={"Tooltip"} placement="bottom-start">
            {sendPackageViaEmailField(blap)}
          </Tooltip>
        </FormControl>
```
With this code, the checkbox parent never changes, only the `Tooltip` props.

**Comment by JonathanWilbur** [comment]
That worked! I implemented that complicated logic because I did not know about `disableHoverListener`. Thanks @ghostd . I will close this isue.

**Comment by bluebill1049** [comment]
Thanks, heaps @ghostd for the recent answers.
