### ISSUE TITLE
NextJs | Yup resovler causing crash

### ISSUE THREAD

**Issue by HadiSDev** [react-hook-form/react-hook-form#3816]
**Describe the bug**

Whenever you try to load a yup schema with the useForm method you get an import module exception.

**Codesandbox link (Required)**
https://codesandbox.io/s/inspiring-lichterman-wzq2n?file=/pages/index.js

**Screenshots**
![image](https://user-images.githubusercontent.com/10367624/103442249-c5893700-4c54-11eb-8466-36d59a2c7121.png)

**Comment by jorisre** [comment]
Thanks for reporting, same issue already reported on resolvers repository https://github.com/react-hook-form/resolvers/issues/100

Please use 1.3.0 version as a workaround

resolvers's V2 will solve this issue
