### ISSUE TITLE
Use cases for unregister function

### ISSUE THREAD

**Issue by jbranchaud** [react-hook-form/react-hook-form#382]
I'm trying to understand what the purpose is behind the [`unregister`](https://react-hook-form.com/api#unregister) function. What are some use cases for it?

I see this example in the docs, but I'm don't understand practically why you would want to do this.

```javascript
import React from "react"
import useForm from "react-hook-form"

export default function App() {
  const { register, handleSubmit, unregister } = useForm()
  const onSubmit = (data) => console.log(data)

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input type="text" name="firstName" ref={register} />
      <input type="text" name="lastName" ref={register} />
      <button type="button" onClick={() => unregister('lastName')}>unregister</button>
      <input type="submit" />
    </form>
  )
}
```

**Comment by bluebill1049** [comment]
To be honest, it's not that common... 

one use case would be if you want to conditionally unregister a field, so it won't be part of the submit result.

**Comment by jbranchaud** [comment]
That makes sense, I was thinking about that use case.

For instance, consider a "how did you hear about us?" field with a few options including "other". If the user selects "other", then you'd reveal and register a text input for specifying the "other". If the user then selects a different value from the drop down, then you'd hide the text input and _unregister_ it. As a result, the `otherInput` would not be included in the submitted result.

Does that make sense?

**Comment by bluebill1049** [comment]
Yeah, make sense, but there is an easier approach.

`{isOther && <Input ref={register} />}`

when `isOther` turns to `false`, it gets unregistered automatically. 

I guess `unregister` is when you want to manually/conditionally remove data from the form. like i said most of the time you don't need to use it.

**Comment by bluebill1049** [comment]
if you pay attention, I purposely to exclude unregister from the API side menu on the website as well. cause most of the time you don't need it :)

**Comment by bluebill1049** [comment]
going to close this, thanks for updating the doc as well :)
