### ISSUE TITLE
TS definition for values returned from watch incorrectly matches InputTypes

### ISSUE THREAD

**Issue by bscaspar** [react-hook-form/react-hook-form#3825]
**Describe the bug**
TS defines values returned from `watch` based on the input types, but `watch` returns strings even for `number` type fields.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-watch-v6-ts-forked-oby0d

**Expected behavior**
One of the following: 
- `watch` returns the type as defined by the input types. This seems like it has been considered and decided to not implement.
- Update documentation to explicitly mention that numbers are returned as strings from `watch`. Does this happen for other types as well?

If the second option, I can help make the update.

**Desktop (please complete the following information):**

- OS: MacOS Big Sur
- Browser: Chrome 87.0.4280.88

**Additional context**
Worth noting in the CSB is one other oddity that was surprising to me but not sure if an actual bug: 
The `watch` type for the `name` field (`watchName`) is updated to `string` when the `age` field is filled out, but before the `name` field has any value. At first glance I would expect this to be undefined before the field it was referencing was populated.

**Comment by bluebill1049** [comment]
`input`'s value is always return string by default unless invoked as `valueAsNumber`

<img width="1427" alt="Screen Shot 2021-01-04 at 10 28 39 am" src="https://user-images.githubusercontent.com/10513364/103491384-9ef71600-4e77-11eb-9c6f-f31404dde9af.png">

**Comment by bscaspar** [comment]
Thank you for the follow up! I was checking this out (looks like relatively new functionality, very cool) and it appears as though `register({valueAsNumber: true})` throws a type error: https://codesandbox.io/s/react-hook-form-watch-v6-ts-forked-271np

**Comment by bluebill1049** [comment]
please use the latest version.

**Comment by bscaspar** [comment]
Looks good, thanks!
