### ISSUE TITLE
useFieldArray append api adds default values of nested array

### ISSUE THREAD

**Issue by naveen4854** [react-hook-form/react-hook-form#3826]
We are trying to use RHF for a multiple layer array form.

One thing we have observed is that when default values are provided to the form 
for example: 
```
const defaultValues = {
  test: [
    {
      name: "useFieldArray1",
      nestedArray: [{ field1: "field1", field2: "field2" }]
    },
    {
      name: "useFieldArray2",
      nestedArray: [{ field1: "field1", field2: "field2" }]
    }
  ]
};
```

delete all the elements and then append a new item to "test".

it adds nested objects(in the example - nestedArray) from defaultvalues.test[0]

[](https://codesandbox.io/embed/react-hook-form-usefieldarray-nested-arrays-x7btr)

Please help me resolve this

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848
