### ISSUE TITLE
Integrating with UI libraries option 3 - bug

### ISSUE THREAD

**Issue by sshmyg** [react-hook-form/react-hook-form#3828]
**Describe the bug**
Form state doesn't change on manual value change. Which is described here https://react-hook-form.com/get-started#IntegratingwithUIlibraries , option 3

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-custom-input-forked-jfxkp
2. Change `reactSelect` field
3. Form state should be changed (isDirty: true)
4. But form state not changed

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-custom-input-forked-jfxkp

**Expected behavior**
Form state should be changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/1410608/103530404-0c16a580-4e90-11eb-8180-060cf4558946.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser chrome (latest)
- Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#formState

> Make sure to provide all inputs' defaultValues at the useForm, so hook form can have a single source of truth to compare whether the form is dirty.

**Comment by sshmyg** [comment]
> https://react-hook-form.com/api#formState
> 
> > Make sure to provide all inputs' defaultValues at the useForm, so hook form can have a single source of truth to compare whether the form is dirty.

`defaultValues` not  helped :(

**Comment by bluebill1049** [comment]
> Make sure to provide all inputs' defaultValues at the useForm

Did you provide all?

**Comment by sshmyg** [comment]
> > Make sure to provide all inputs' defaultValues at the useForm
> 
> Did you provide all?

https://codesandbox.io/s/react-hook-form-custom-input-forked-jfxkp?file=/src/index.js

Yes, default values as empty string.

**Comment by bluebill1049** [comment]
Did you use `setValue` with `shouldValidate`?

**Comment by sshmyg** [comment]
> Did you use `setValue` with `shouldValidate`?

Nope, I use it as was described in doc.

**Comment by bluebill1049** [comment]
you want to trigger validation during `setValue` action

https://react-hook-form.com/api#setValue

You can also set the shouldDirty parameter to true in order to set field to dirty.

`setValue('name', 'value', { shouldDirty: true })`

**Comment by sshmyg** [comment]
@bluebill1049  Thanks for the help ;)

**Comment by bluebill1049** [comment]
No worries, mate @sshmyg 👍

**Comment by icelic** [comment]
Thanks this also helped me! 

How come this is not true by default? I would expect it to be true by default because setting something should dirty the form (by default).
