### ISSUE TITLE
Reset method with dirtyFields to true doesn't work as expected

### ISSUE THREAD

**Issue by vmc08** [react-hook-form/react-hook-form#3829]
Hi @bluebill1049 , thanks for this great library but I need help. 

Currently working with array field value, what I wanted to do is add/remove values using `reset` method and still want the form to be dirty. 

**Describe the bug**
❌ When I add/remove an item via `reset` method, it doesn't dirty the form.

This is how i used the method in my code.
`reset?.({ questions: newQuestions }, { dirtyFields: true })`

**To Reproduce**

1. Go to CSB https://codesandbox.io/s/react-hook-form-reset-issue-qzjdb?file=/src/App.tsx:3820-3842
2. Click on any of the trash icon OR the `Add another department` button
3. Click submit
4. See alert and dirty is still false

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

- [RHF Reset Issue](https://codesandbox.io/s/react-hook-form-reset-issue-qzjdb?file=/src/App.tsx) - link to my CSB

**Expected behavior**
Form should be dirty as I set the `dirtyFields` to `true`

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 Home Single Language
- Browser: Google Chrome
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**Additional context**
If you are wondering why I am not using useFieldArray, it was originally written on it but I refactored it because I am working with react-beautiful-dnd library to re-order stuff and it doesn't work well with it (as I've read also in some of your resources).

**Comment by bluebill1049** [comment]
yeah, I expected this is not going to as expected because it's not using useFieldArray, you will have to manage the dirty state yourself.

**Comment by bluebill1049** [comment]
by the way, I have seen users using dnd with `useFieldArray`.

**Comment by vmc08** [comment]
@bluebill1049 I did try using useFieldArray earlier but using the `move` method is causing some issues, it seems like values on the affected indexes after moving is removed also. I'll create another CSB for this as reference. Thanks for your flash reply :)

**Comment by vmc08** [comment]
Sorry wasn't able to respond back asap (internet issues), I will be closing this issue now. I tried to do it again with useFieldArray and still experience the problem above ^, then I tried to update my libraries to wanted version and seems to fixed the issue. Thanks @bluebill1049
