### ISSUE TITLE
Too Many Re-Renders

### ISSUE THREAD

**Issue by eugenegordeiev** [react-hook-form/react-hook-form#3833]
**Describe the bug**
When using useFieldArray with dynamically generated form and fields having rules required true, on swap and other commands, the validation trigger excessive number of re-renders of the view (the more array items, the more re-renders of the main view).

**To Reproduce**

1. Go to https://codesandbox.io/s/8rr6d?file=/src/index.js
2. Open console and note "REFRESH MAIN-------"
2. Click on 'ADD CONTACT'
3. Notice 2 "REFRESH MAIN---------"
4. Select "Phone" from Type select list
5. Click "ADD CONTACT"
6. Select "Address" from Type select list
7. Click "SAVE" (will trigger swap)
8. Notice 3 "REFRESH MAIN---------"

Repeat steps 6-8 to see re-renders (REFRESH MAIN----) will grow.
To better see whats happening, clear the console after every action.

**Codesandbox link (Required)**
https://codesandbox.io/s/8rr6d?file=/src/index.js

**Additional context**
I believe the issue is related to the validation which is triggered during "swap" and since the fields are empty and having rules required, this triggers some sort of a loop of refreshes.

If rules required are removed, this does not happen.  Also, if append is used with non-empty fields, this also doesnt happen.  Additionally I'm not sure if this issue is related to material ui.

**Comment by bluebill1049** [comment]
<img width="747" alt="Screen Shot 2021-01-05 at 3 11 26 pm" src="https://user-images.githubusercontent.com/10513364/103605553-49e6fd00-4f68-11eb-8142-a525b79cea57.png">

That's expected right, the main is not getting refreshed, only those component which has `useWatch`.

**Comment by eugenegordeiev** [comment]
No.. The Main is getting refreshed multiple times.. that is the problem..

**Comment by bluebill1049** [comment]
send a video on how to produce the problem.

**Comment by eugenegordeiev** [comment]
Here you go.
https://user-images.githubusercontent.com/6035444/103608088-7c511580-4ee8-11eb-86d1-989988216ecd.mov

**Comment by bluebill1049** [comment]
This is due to you are subscribed to `isValid`, and there are many inputs that are conditional re-rendered, hence re-render is happening again and again at your root to update `isValid`.

conditional inputs
<img width="511" alt="Screen Shot 2021-01-05 at 4 15 18 pm" src="https://user-images.githubusercontent.com/10513364/103609105-355b3280-4f71-11eb-9729-e4d54a3cf2cd.png">

subscribed to isValid formState
<img width="431" alt="Screen Shot 2021-01-05 at 4 15 05 pm" src="https://user-images.githubusercontent.com/10513364/103609094-2e342480-4f71-11eb-97dc-ae1eed8acc52.png">

**Comment by eugenegordeiev** [comment]
@bluebill1049 Removing the isValid does help.  However, isValid is still needed for submission and is a valid use case.  What would be the alternative to checking if the form is valid for submission?

I still think there is an issue.

**Comment by bluebill1049** [comment]
Like I stated above this is by design, I would suggest not toggling the input `&&` instead just show and hide with CSS style.
