### ISSUE TITLE
Form wrapped around multiple Material UI tabs does not retain state

### ISSUE THREAD

**Issue by joejordan** [react-hook-form/react-hook-form#3834]
**Describe the bug**
A RHF form wrapped around Material UI tabs does not retain state when switching between tabs.

**To Reproduce**

1. Fill in values under Name tab
2. Click on Identifiers tab
3. Click back to Names tab, TextField values are reset

**Codesandbox link (Required)**
https://codesandbox.io/s/happy-vaughan-06yu5?file=/src/App.js

**Expected behavior**
I expected that my changed fields would be retained when I returned to the tab to continue editing

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox, Chrome
- Version: latest release

**Comment by bluebill1049** [comment]
This is expected :) take a look at the example folder, i had an example:

https://github.com/react-hook-form/react-hook-form/tree/master/examples 

https://codesandbox.io/s/tabs-760h9

you can set `shouldUnregister: false` which we keep a shallow copy of the form state.

**Comment by joejordan** [comment]
> you can set `shouldUnregister: false` which we keep a shallow copy of the form state.

Thanks @bluebill1049 this helps with retaining the state, however it appears that formState.dirtyFields is cleared when you toggle between the tabs. Any solution for that?

**Comment by bluebill1049** [comment]
can you share a CSB?

**Comment by joejordan** [comment]
@bluebill1049 sure, just updated the original one: https://codesandbox.io/s/happy-vaughan-06yu5?file=/src/App.js

Watch the console as you set text to fields and then click to the next tab. Looks like `dirty` is retained until you return to the tab, but you can see `dirtyFields` entries drop off as you fill in fields and click to other tabs.

**Comment by bluebill1049** [comment]
<img width="1107" alt="Screen Shot 2021-01-06 at 8 57 46 am" src="https://user-images.githubusercontent.com/10513364/103704339-405ba480-4ffd-11eb-8e33-e31a1f24214b.png">
still broken.

**Comment by joejordan** [comment]
> still broken.

Just re-saved and tested it in an incognito window. https://codesandbox.io/s/happy-vaughan-06yu5

The material ui import line should look like this:
`import { Tab, Tabs, TextField } from "@material-ui/core";`
