### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by nick-lvov-dev** [react-hook-form/react-hook-form#3837]
So basically I can't find a way to make the library work in IE11 because it doesn't support `Proxy`.
The IE11 compatible version from `react-hook-form/dist/index.ie11` doesn't work because it also has a Proxy inside.
According to [this thread on SO](https://stackoverflow.com/questions/45285992/es6-proxy-polyfill-for-ie11) Proxy is not polyfillable, so `core-js` or `babel` are out of the question.
Do you guys think it would be possible to solve this? Or is IE11 support done for good?

**Comment by bluebill1049** [comment]
Try this? https://www.npmjs.com/package/proxy-polyfill 

We are still trying to support IE11 with v6, but will drop it in V7.

**Comment by nick-lvov-dev** [comment]
Will give it a go, thanks!

**Comment by bluebill1049** [comment]
Np 👍

**Comment by scott0730** [comment]
@bluebill1049 I tried to import proxy.min.js at the root of the project but no dice. Do you know how to import it via webpack? Thanks a bunch in advance!

**Comment by bluebill1049** [comment]
> @bluebill1049 I tried to import `proxy-polyfill` at the root of the project but no dice. Do you know how to import it via webpack? Thanks a bunch in advance!

try this: https://github.com/zloirock/core-js

**Comment by AnnaVih** [comment]
would that mean dot notation does not work in IE11 + V7? I am having trouble getting form data properties as an object.
