### ISSUE TITLE
onChange revalidation does not work for nested fields

### ISSUE THREAD

**Issue by GorkemSahin** [react-hook-form/react-hook-form#3838]
**Describe the bug**
When a field is inside an object, revalidation does not trigger onChange like it does for other fields. You can observe the values being updated but the errors stay the same.

**To Reproduce**

1. Go to the Codesandbox link down below.
2. See that the validation schema consists of a person object with the name and surname fields in it.
3. Leave the name field empty, try to submit, see that the name field is required.
4. Type something, see that the error does not go away until you try to submit again even though the default revalidation mode is onChange. It works for non-nested fields just fine.
5. You can also console.log the values acquired through getValues() and the errors, both of which are provided by the useForm hook. Values get updated, resolver returns no errors, but the changes are not reflected upon the errors object.

**Codesandbox link (Required)**
Here's the Codesandbox I created to demonstrate the issue.
https://codesandbox.io/s/react-hook-form-validationschema-forked-ouk7v?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
Error should go away when there's a value typed, just like it does for non-nested fields.

**Comment by bluebill1049** [comment]
you are not returning the correct shape of the errors object at the `resolver`, it should be a nested object.
```
test: {
   firstName: xxx
}
```

**Comment by GorkemSahin** [comment]
> you are not returning the correct shape of the errors object at the `resolver`, it should be a nested object.
> 
> ```
> test: {
>    firstName: xxx
> }
> ```

I didn't quite understand where and what I should fix. The code for resolver is taken from the official documentation: https://react-hook-form.com/advanced-usage#CustomHookwithResolver

**Comment by bluebill1049** [comment]
The example is a flat structure: 

```
import React, { useCallback, useMemo } from "react";
import { useForm } from "react-hook-form";
import * as yup from "yup";

const useYupValidationResolver = validationSchema =>
  useCallback(
    async data => {
      try {
        const values = await validationSchema.validate(data, {
          abortEarly: false
        });

        return {
          values,
          errors: {}
        };
      } catch (errors) {
        return {
          values: {},
          errors: errors.inner.reduce(
            (allErrors, currentError) => ({
              ...allErrors,
              [currentError.path]: {
                type: currentError.type ?? "validation",
                message: currentError.message
              }
            }),
            {}
          )
        };
      }
    },
    [validationSchema]
  );

export default function App() {
  const validationSchema = useMemo(
    () =>
      yup.object({
        firstName: yup.string().required("Required"),
        lastName: yup.string().required("Required")
      }),
    []
  );
  const resolver = useYupValidationResolver(validationSchema);
  const { handleSubmit, register } = useForm({ resolver });

  return (
    <form onSubmit={handleSubmit(data => console.log(data))}>
      <input name="firstName" ref={register} />
      <input name="lastName" ref={register} />
      <input type="submit" />
    </form>
  );
}
```

your form is deep nested. have a look at the example in here: https://github.com/react-hook-form/resolvers on how we build resolvers.

**Comment by GorkemSahin** [comment]
@bluebill1049 I don't see any nested examples at https://github.com/react-hook-form/resolvers and the code you posted is exactly the same as mine. I can't understand what I did wrong, could you be more specific? I debugged the resolver, the errors returned from the resolver go away when there's a value, but the errors object from the useForm hook stay the same.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/resolvers/blob/master/src/yup.ts

read my comment above again, your form inputs are nested, the code I posted is flat.

**Comment by GorkemSahin** [comment]
I just figured it out. It'd be helpful if you had a code sample for nested validation as well. Thanks for the help and also the great tool!

**Comment by bluebill1049** [comment]
no worries @GohKianSeng will get a nested version up in the doc.
