### ISSUE TITLE
Form Context + React-Autosuggest not working: user has to type twice for the character to show up

### ISSUE THREAD

**Issue by dpw1** [react-hook-form/react-hook-form#384]
**Describe the bug**
Whenever using React Hook Form with [react-autosuggest](https://github.com/moroshko/react-autosuggest) the first key stroke is not read. 

**To Reproduce**
1. Access the [codesandbox example](https://codesandbox.io/s/react-hook-form-form-context-mrusg);
2. At the "EAN" field just type "123". 
3. You will notice the "1" will not show up.

PS: Upon submission the value is sent just fine. You can also check that at the console.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-form-context-mrusg

**Expected behavior**
When typing "123" the "1" should show up right away just in like any other input.

**Desktop (please complete the following information):**
Windows 7
Google Chrome
Version: 77.0.3865.90

**Comment by bluebill1049** [comment]
https://react-hook-form.com/faq

Why is first keystroke is not working?

The reason is that you are probably using `value` instead of `defaultValue`

**Comment by bluebill1049** [comment]
closing as no follow-up, feel free to reopen and ask more questions here
