### ISSUE TITLE
6.14.0  dirty is not reset

### ISSUE THREAD

**Issue by xiaoyu-tamu** [react-hook-form/react-hook-form#3848]
**Describe the bug**

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-forked-bet6g?file=/src/index.js
2. type 1
3. delete 1
4. dirty and dirty fields not reset

if you switch to 6.13.1, it work as expected
 
**Expected behavior**

It should reset form dirty when changed value equals initial value

**Screenshots**
![image](https://user-images.githubusercontent.com/33362998/103871034-1f915e80-5092-11eb-9c80-d02c6c007689.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bluebill1049** [comment]
please always supply a `defaultValues`, we are only doing a compare with `defaultValues` to determine `isDIrty`.

**Comment by xiaoyu-tamu** [comment]
okay, that’s a breaking change? I think It’s not the case prior 6.14

**Comment by bluebill1049** [comment]
See that's the difficult part, it resolves the existing bug while it leads to breaking change with incorrect usage. it causes another related issue by not related to the single source of truth, and the doc is included that information to emphasize the importance of `defaultValues` for measure `isDirty`.

**Comment by xiaoyu-tamu** [comment]
Ok, make sense, thanks for that.

**Comment by bluebill1049** [comment]
Thanks for understanding @xiaoyu-tamu! 🙏
