### ISSUE TITLE
Uncaught TypeError: Cannot delete property '3' of [object Array]

### ISSUE THREAD

**Issue by ssuvorov** [react-hook-form/react-hook-form#3850]
I'm getting an error `Uncaught TypeError: Cannot delete property '3' of [object Array]`.

My component is a dynamic that uses `useFieldArray({ name: 'step.answers', control })`.

```js
    if (defaultValues && fields.length < defaultValues.length) {
      defaultValues.pop(); // here where it breaks
      set(fieldArrayDefaultValuesRef.current, name, defaultValues);
    }
```

`defaultValues.length` is 4, `fields.length` is 2. That's why `defaultValues.pop();` is fired.

Could you clarify please, why this error might happen? I can debug further then.

It would be nice to have a clarification error in the console for such cases.

<img width="476" alt="Screenshot 2021-01-07 at 14 07 54" src="https://user-images.githubusercontent.com/3448821/103896137-cbb66200-50f1-11eb-95d3-cc8312a0e225.png">
<img width="513" alt="Screenshot 2021-01-07 at 14 11 37" src="https://user-images.githubusercontent.com/3448821/103896447-45e6e680-50f2-11eb-8325-7347229bd8a2.png">

I'd be glad to create a codesandbox, but my form is very complicated. With funnel and little-state-machine.

**Comment by ssuvorov** [comment]
Okay, I reproduced the issue partially https://codesandbox.io/s/react-hook-form-usefieldarray-error-with-complex-form-structure-forked-tfezu?file=/src/Question.js Still didn't get the error above, but the issue is with a dynamic nester field array.
I think the reason is there.

Step 1
1. Select type **question**
2. select a question: **Q1**
Answers are not visible

Step 2
1. Open **Questoin.js**
2. Replace `{watchedElementUUID && <Answers />}` with `<Answers />`

Repeat Step 1. 
Answers are visible

**Comment by bluebill1049** [comment]
we don't support usage: 

```
// Custom "step.answers[i].xxx" fields registration
  useEffect(() => {
    // fired once when the key is changed in <Answers key="">
    fields.forEach((answer, index) =>
      ANSWER_KEYS.forEach((answerKey) => {
        register({
          name: `step.answers[${index}].${answerKey}`,
          value: fields[index][answerKey]
        });
      })
    );

    return () => {
      fields.forEach((answer, index) =>
        ANSWER_KEYS.forEach((answerKey) => {
          unregister(`step.answers[${index}].${answerKey}`);
        })
      );
    };
  }, [fields, ANSWER_KEYS]);
  ```
  
you can try with `shouldUnregister: false`, this wouldn't work for the next major version as well. field inputs need to be in the render for us to manipulate the field array.

**Comment by ssuvorov** [comment]
Okay. Is the next supported?

```js
const { fields } = useFieldsArray({ name: 'step.fields', control });
...
return {fields.map((field, index) =>
        Object.keys(field).map((fieldKey) => (
          <input
            ref={register()}
            key={`${index}-${fieldKey}`}
            style={{ display: 'none' }}
            value={field[fieldKey]}
            name={`step.answers[${index}].${fieldKey}`}
          />
        ))
      )}
```

Can `useFieldArray` be unmounted? I need to register different arrays based on a **step.type** selection.
`{  step: { type: 'form', fields: [ ]} }`
and 
`{ step: {  type: 'question', answers: [ ]} }`.

And when the type is changed, I have to either `reset` or use `setValue` to specify different answers or fields.

**Comment by bluebill1049** [comment]
why do you have to do the double `map`? if you need nested field array, create another `useFieldArray`.

**Comment by ssuvorov** [comment]
I don't need a nested one. I need a different field array based on the "type". And a different array has different keys in its objects.

**Comment by bluebill1049** [comment]
Then you need to at least wrap the whole field array with unique `key`.

**Comment by ssuvorov** [comment]
But the keys are unique for useFieldArrays.

App component:
 - A type switch Component form/question (based on it one of the following is mounted and unmounted)
  - Component for a "question" type (it has `useFieldArray({ name: 'step.answers' })`)
  - Component for "form" type (it has `useFieldArray({ name: 'step.fields' })`)

**Comment by bluebill1049** [comment]
no, the key is for React, when you do a map you should provide a key for the inner component. It's important for react hook form as well, this is the identity for the field array.

**Comment by ssuvorov** [comment]
do you mean here
```
{fields.map((field, index) =>
        Object.keys(field).map((fieldKey) => (
          <input
            ref={register()}
            key={`${index}-${fieldKey}`}  // <---------
            style={{ display: 'none' }}
            value={field[fieldKey]}
            name={`step.answers[${index}].${fieldKey}`}
          />
        ))
      )}
```

or to `<FieldsComponent key="HERE"/>`?

**Comment by bluebill1049** [comment]
I think you need a `div` to wrap around your inner `.map`, not with the individual inputs. Try that.

**Comment by ssuvorov** [comment]
Nope, that's not it. I will try to reproduce it on Codesandbox tomorrow.

**Comment by ssuvorov** [comment]
My Gosh! Spent a few days and found the reason for the error above. 

The data that I pass as default values is immutable. It's frozen with [deepFreeze](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze)

**The next code throws an error**
```js
function deepFreeze(object) {
  // Retrieve the property names defined on object
  const propNames = Object.getOwnPropertyNames(object);

  // Freeze properties before freezing self

  for (const name of propNames) {
    const value = object[name];

    if (value && typeof value === "object") {
      deepFreeze(value);
    }
  }

  return Object.freeze(object);
}

deepFreeze([{a: 1}]).pop()
```
that's why `defaultValues.pop()` in the library leads to the `Cannot delete property '0' of [object Array]`

The solution can be `[...defaultValues].pop()` or a deep copy of values `JSON.parse(JSON.stringify(defaultValues))`.
Not sure what is better for performance, especially for the IE version.

**Comment by bluebill1049** [comment]
> My Gosh! Spent a few days and found the reason for the error above.
> 
> The data that I pass as default values is immutable. It's frozen with [deepFreeze](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze)
> 
> **The next code throws an error**
> 
> ```js
> function deepFreeze(object) {
>   // Retrieve the property names defined on object
>   const propNames = Object.getOwnPropertyNames(object);
> 
>   // Freeze properties before freezing self
> 
>   for (const name of propNames) {
>     const value = object[name];
> 
>     if (value && typeof value === "object") {
>       deepFreeze(value);
>     }
>   }
> 
>   return Object.freeze(object);
> }
> 
> deepFreeze([{a: 1}]).pop()
> ```
> 
> that's why `defaultValues.pop()` in the library leads to the `Cannot delete property '0' of [object Array]`
> 
> The solution can be `[...defaultValues].pop()` or a deep copy of values `JSON.parse(JSON.stringify(defaultValues))`.
> Not sure what is better for performance, especially for the IE version.

Thanks, @ssuvorov for the investigation, we will improve this in v7. I will patch this will a shallow clone.

**Comment by bluebill1049** [comment]
actually will do a slice and it would solve this issue for now.

**Comment by bluebill1049** [comment]
Keep this open, i will patch this tonight and close it.
