### ISSUE TITLE
Controller render prop : state parameter seems to have invalid type

### ISSUE THREAD

**Issue by benjamin-schneider** [react-hook-form/react-hook-form#3851]
**Describe the bug**
In a Controller render prop, the second argument state of type Input state does not reflect the parameter value.

**To Reproduce**
1. Go to codesandbox (https://codesandbox.io/s/react-hook-form-controller-template-forked-3tv08)
2. Click on submit
3. fieldStateInvalid value is not corresponding to typings (InputState)

**Codesandbox link (Required)**
`https://codesandbox.io/s/react-hook-form-controller-template-forked-3tv08`

**Expected behavior**
I expect to have a boolean, not an object (or better, to have the error message in state, but with correct typings)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser Chrome
- Version Version 87.0.4280.88 (Build officiel) (64 bits)

**Additional context**
Thanks for this nice project and sorry if what I said is a mistake.

**Comment by bluebill1049** [comment]
oops, you are right.

**Comment by benjamin-schneider** [comment]
> oops, you are right.

thanks for the quick fix

**Comment by bluebill1049** [comment]
> > oops, you are right.
> 
> thanks for the quick fix

np, thanks for reporting.
