### ISSUE TITLE
fragmented string while using useFieldArray with defaultValues

### ISSUE THREAD

**Issue by sukjae** [react-hook-form/react-hook-form#3852]
**Describe the bug**
Same as issue #924 which was solved.

**To Reproduce**

1. Go to https://codesandbox.io/s/focused-moon-8fqq4
2. Click on latest version
3. can see fragmented string 

**Codesandbox link (Required)**
https://codesandbox.io/s/focused-moon-8fqq4

**Expected behavior**
change to version 6.4.1 will work propery

**Screenshots**
| as-is (v6.14) | to-be (v6.4) |
|---|---|
| ![image](https://user-images.githubusercontent.com/8156543/103914534-4e203f80-514d-11eb-94bc-00158099bec4.png)| ![image](https://user-images.githubusercontent.com/8156543/103914474-3d6fc980-514d-11eb-9f08-9da2c7274e30.png)|

Related fix: #940
related Issue: #924
possible reason for issue: https://github.com/react-hook-form/react-hook-form/commit/eaf0b030b759d699e74fd5dbfe59511003f46803

**Possible solution**

```js
 // src/useFieldArray.ts line:60
  type FixMe = any
  // ...
  return values.map((value: Partial<TFieldArrayValues>) => ({
    [keyName]: value[keyName] || generateId(),
    ...(isObject(value) ? value : {value} as FixMe),
  }));
```

**Comment by bluebill1049** [comment]
we don't support flat array.

**Comment by sukjae** [comment]
> we don't support flat array.

i see.. thank you for response! 

do i need to close this Issue by my self?

**Comment by bluebill1049** [comment]
Thanks for understanding! here is a quick example. we need a unique key for each field array and hence we can't do flat array. 

```
function Test() {
  const { control, register } = useForm();
  const { fields, append, prepend, remove, swap, move, insert } = useFieldArray({
    control, // control props comes from useForm (optional: if you are using FormContext)
    name: "test", // unique name for your Field Array
    // keyName: "id", default to "id", you can change the key name
  });

  return (
    {fields.map((field, index) => (
      <input
        key={field.id} // important to include key with field's id
        name={`test[${index}].value`}
        ref={register()} // register() when there is no validation rules 
        defaultValue={field.value} // make sure to include defaultValue
      />
    ))}
  );
}
```
