### ISSUE TITLE
Add field name as param to Controller.onFocus

### ISSUE THREAD

**Issue by morhogg** [react-hook-form/react-hook-form#3853]
I think that would be good if I can a more generic code to focus with field name.
Currently I need to manually pass the field name to a custom function, which is something that ends up repeating a bit of code

```JSX
const handleFocus = inputName => () => {
  document.querySelector(`[name="${inputName}"]`)?.focus();
}

<Controller
  name='personName'
  onFocus={ handleFocus('personName') }
  as={TextField}
/>
```

I think being able to write the code like that would be wonderful

```JSX
const handleFocus = inputName => {
  document.querySelector(`[name="${inputName}"]`)?.focus();
}

<Controller
  name='personName'
  onFocus={ handleFocus }
  as={TextField}
/>
```

**Comment by ghostd** [comment]
Hi,

I'm not sure to get the point. It seems the `onFocus` event is not specific to RHF. If you need to have some generic event handlers, i think you can get the input name with this (not tested):
```js
const handleFocus = (event) => {
  document.querySelector(`[name="${event.target.name}"]`)?.focus();
}
```

The DOM specification provides enough data for this use case (keep in mind `focus` event is DOM Level 0).

BTW, why call `focus()` in a `focus` event handler?

**Comment by morhogg** [comment]
@ghostd the onFocus that I mentioned is specific to RHF Controller component, see https://react-hook-form.com/api#Controller

this callback is called when there is a field error

**Comment by morhogg** [comment]
the shouldFocusError: true feature not work automatically with Controller, we need to write a custom focus callback to Controller to make that work, that why I think that having the field name would help to make my code a bit less verbose

**Comment by ghostd** [comment]
You're right, i missed this handler :-/

**Comment by bluebill1049** [comment]
we are removing `onFoucs` prop on the next major version, use the `ref` coming from the render prop instead. 

https://react-hook-form.com/api#useController

`name` it's already in the `field` object.

`ref` in side field iss basically doing the focus if the ref is exposed, if not. you can always do `ref({ target: focus: () => {} })`

**Comment by morhogg** [comment]
Oh, I didn't know that, thanks :dancers:
