### ISSUE TITLE
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### ISSUE THREAD

**Issue by sgentile** [react-hook-form/react-hook-form#3857]
I have a component wrapped as follows:

```
<Controller
                                                                as={MaskedInput}
                                                                control={control}
                                                                mask="999-999-9999"
                                                                name="phone"
                                                                data-testid="phone"
                                                                label="Phone"
                                                                defaultValue={user.phone || ''}
                                                                errors={errors}
                                                                alwaysShowMask
                                                                rules={{
                                                                    pattern: {
                                                                        value: /^([1-9]\d{2}-\d{3}-\d{4})$/i,
                                                                        message:
                                                                            'Please enter a valid Phone Number (expected format: 000-000-0000)',
                                                                    },
                                                                }}
                                                            />
```

it actually works, but it throws the error.   My MaskedInput does not have ref

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#useController

or render props from the `Controller`, the inner component doesn't expose ref that's why you got this warning.

**Comment by twhoff** [comment]
This is still an issue with render or useController as well...

Example:
![image](https://user-images.githubusercontent.com/4405822/123020019-f59be080-d414-11eb-8660-ccecd867cc94.png)

The code is something like this:

![image](https://user-images.githubusercontent.com/4405822/123020789-36482980-d416-11eb-8b56-c3592f1fdf0a.png)
![image](https://user-images.githubusercontent.com/4405822/123020833-46600900-d416-11eb-93c4-224a5665e6a1.png)

**Comment by RongxinZhang** [comment]
Having similar issues as @twhoff

**Comment by Moshyfawn** [comment]
First off, "having similar issues" or just a screenshot of the error doesn't exactly help us to debug / help you with an issue ;)
Secondly, @bluebill1049 has already given the answer about the issue.
> or render props from the Controller, the inner component doesn't expose ref that's why you got this warning.

Many custom components libraries can choose to not expose the underlining input's `ref` or choose to expose it undera different name like `innerRef` or `inputRef` instead of using `React.forwardRef`. With RHF, instead of simply spreading all the input's handlers / props _(`{...field}` or `{...register("name")}`)_, you should destruct the `ref` and pass it into the input's prop your component exposes for the `ref`, if it has one, that is.
