### ISSUE TITLE
shouldUnregister: false working strange with useFieldArray actions

### ISSUE THREAD

**Issue by vytcus** [react-hook-form/react-hook-form#3872]
**Describe the bug**
When using shouldUnregister: false options together with useFieldArray - does not prepend value without input to form values. Did not check other actions.

**To Reproduce**

1. Go to [https://codesandbox.io/s/react-hook-form-usefieldarray-forked-g22up?file=/src/index.js](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-g22up?file=/src/index.js)
2. Click on Submit button. Check console - valueWithoutInput: "test" exists in first item.
3. Click prepend. Check console - valueWithoutInput: "test" does not exist in first item.

Sorry if this is intended behavior. Should I then have a hidden input for this value?

**Comment by bluebill1049** [comment]
I will take a look at it, we are removing `shouldUnregister: false` from the next version, it's better to use hidden input and toggle input's visibility.

**Comment by bluebill1049** [comment]
This is expected, you never register such input `valueWithoutInput`.

**Comment by vytcus** [comment]
Why never? Some props can be related to actions in the form, but not exist as inputs in the DOM.

Example:
Our use case is that you can add rows from different sources. So each row would have a prop `addedFromSource: 'x' | 'y' | 'z'`
which is not really a field in the form. So in this case I see two solutions with react-hook-form:

1. Add hidden input to form `name="addedFromSource"` - this seems like a workaround rather than a solution.
2. Have a separate mapping object and `onSubmit `do the mapping - this adds unneeded complexity. The way I see it this prop is actually part of the form as it relates to an action done on the form so why not have it in global state?

Does that make sense? I believe there is a use case for having props in global form state that do not have visible inputs.

**Comment by bluebill1049** [comment]
> Why never?

I said in your example is never gets registered. 

> Some props can be related to actions in the form, but not exist as inputs in the DOM.

**Comment by vytcus** [comment]
Understood. Thanks for clarifying
