### ISSUE TITLE
Material UI tabs does not retain state with useFieldArray 

### ISSUE THREAD

**Issue by oualidmaz** [react-hook-form/react-hook-form#3875]
**Describe the bug**
useFieldArray in Material UI tabs does not retain state when switching between tabs even with "shouldUnregister: false".

_Note_ : fields outside the useFildArray is working well (state is kept) 

**To Reproduce**

1. Go to https://codesandbox.io/s/gallant-night-2y6g6
2. Click on 'Multiple Names' tab
3. Fill the fileds with some text
4. Click on the first tab ie "Name" tab 
5. Navigate back to 'Multiple Names' tab => no data on the fields 

**Expected behavior**
Filled fields should be retained when switching between tabs
**Desktop :**

- OS: Windows 10
- Browser Chrome
- Version 6.14.1

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/104293562-3c0a1c80-5512-11eb-953b-51246db3800e.mov

looks ok to me, did you forgot to save the codesandbox?

**Comment by oualidmaz** [comment]
Sorry I forgot to save the codesandbox ... I update it 
![bug4](https://user-images.githubusercontent.com/25105818/104334051-e573f280-54bf-11eb-939a-88a37adca34a.gif)

**Comment by bluebill1049** [comment]
can you try to move that useFieldArray into its own component? because useFieldArray not getting unmounted and hence it's keeping the same `defaultValue` for the field array. also, I would recommend doing the following instead: 

https://codesandbox.io/s/tabs-760h9

side note: `shouldUnregister` is getting deprecated in v7 as well.

**Comment by oualidmaz** [comment]
Moving useFieldArray into its own component didn't seems to solve the problem . codesandbox updated

**Comment by bluebill1049** [comment]
you are missing `defaultValue`:

```
<div key={id}>
            <TextField
              name={`persons[${i}].name`}
              label="Name"
              type="text"
              inputRef={register()}
              defaultValue={name}
            />
          </div>
          ```

**Comment by oualidmaz** [comment]
Thank you @bluebill1049 . Adding defaultValue fix the problem 

```
{fields.map((item, i) => {
        return (
          <div key={item.id}>
            <TextField
              name={`persons[${i}].name`}
              label="Name"
              type="text"
              inputRef={register()}
              defaultValue={item.name}
            />
          </div>
        );
      })}
```

**Comment by ahug** [comment]
> can you try to move that useFieldArray into its own component? because useFieldArray not getting unmounted and hence it's keeping the same `defaultValue` for the field array. also, I would recommend doing the following instead:
> 
> https://codesandbox.io/s/tabs-760h9
> 
> side note: `shouldUnregister` is getting deprecated in v7 as well.

I am experiencing a similar issue. 

Could you please explain why having the `useForm` and `useFieldArray` call both in the same file does not work as expected? (see https://codesandbox.io/s/determined-lamarr-cjx5s)

**Comment by oualidmaz** [comment]
However it is not working (tabs does not retain state) when using useFieldArray with nested array 
Here is the codesandbox : https://codesandbox.io/s/quiet-dew-c2vi5

![bug3](https://user-images.githubusercontent.com/25105818/104533029-8dcca880-55df-11eb-8ed0-799426e8911a.gif)
