### ISSUE TITLE
SetValue not clearing Dirty state?

### ISSUE THREAD

**Issue by Geddard** [react-hook-form/react-hook-form#3876]
Hi there, I've been trying to figure out this for a few days now...

I have a form that is split into a couple of different sections.

I'm trying to handle the sections as part of one form, but I'm having trouble clearing the state (dirt) of the sections on submit or cancel, and keeping the other sections intact.

I need these subsections to be able to submit by parts, or as a whole (that's why it's all one form and not many).

so for example if I have these fields

```
Name:__
Last Name:__

[Save] [Cancel]

------

Age:__
Height:__

[Save] [Cancel]
```

each subform has their onSubmit and onCancel.

And what I need to achieve is that, if it has both subforms with dirty fields, and I cancel only one.
I need to clear the dirty fields only from that form, not both, so i'm trying this for example:

```
<Button
  onClick={() => {
    const shouldKeepDirt = Object.keys(dirtyFields).some(key => !sectionFields.includes(key));  // this helps me know if fields on other sections have dirt

    sectionFields.forEach(key => setValue(key, defaultValues[key], { shouldDirty: false })); // sectionFields is a list of the names of the fields in this section
    reset(getValues(), { isDirty: shouldKeepDirt, dirtyFields: shouldKeepDirt }); // And here i try to reset with the current values (the setValue should have changed that to the default one, right?) but the current section fields still display as dirty....
  }}
>
   Cancel
 </Button>
```

I've even tried the other way around, meaning first resetting and then setValue, exact same result

Am I doing something wrong or is this just buggy?

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

take a quick glance without reading into detail because you are not following our issue or question template: 

`setValue('name', 'value', { shouldDirty: true })`

**Comment by Ansalibrahim** [comment]
This is still an issue. Should I have to file another issue with the template or can we re-open this?
