### ISSUE TITLE
action(data) is not a function

### ISSUE THREAD

**Issue by travisboss** [react-hook-form/react-hook-form#3880]
**Describe the bug**
Per this example when submitting the form I get an error of `action(data) is not a function`

**To Reproduce**

1. Go to 'https://codesandbox.io/s/react-hook-form-wizard-form-13yud?file=/src/Step1.js'
2. Click on 'put in first name and last name and click submit'

action(data) is not a function

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

https://codesandbox.io/s/react-hook-form-wizard-form-13yud?file=/src/Step1.js

**Expected behavior**

Should submit to next piece of wizard form and save state.

**Screenshots**

<img width="1108" alt="Screen Shot 2021-01-12 at 2 44 02 PM" src="https://user-images.githubusercontent.com/16948721/104370530-a015ec00-54e4-11eb-9055-be11b4feb2ae.png">

**Desktop (please complete the following information):**

- OS: [Mac]
- Browser [Edge]
- Version [87.0.664.75]

**Comment by bluebill1049** [comment]
this is an issue for little state machine: https://codesandbox.io/s/react-hook-form-wizard-form-13yud?file=/src/Step1.js also read the doc for the latest API, you are using v4. i think the tutorial is on v3.
