### ISSUE TITLE
after normalisation form values receive first wrong character

### ISSUE THREAD

**Issue by bibblebabl** [react-hook-form/react-hook-form#3889]
**Describe the bug**
On change with normalisation and setValue sets first wrong character value to form values. formState.isValid becomes true

**To Reproduce**

1. type any character to field with normalisation which should not match regex
2. console.log shows what form values have received first inputed character even it was normalised 
3. if all other fields are valid but this one stays empty form becomes valid

**Codesandbox link (Required)**

- https://codesandbox.io/s/ecstatic-goldwasser-gv4xv?file=/src/App.tsx

**Expected behavior**
Form shouldn't receive normalized value if normalise function returned empty value

**Comment by bluebill1049** [comment]
couple issues here: 

1. getValues() is not meant to use like that, getValues. you are most likely after `watch` API

> An optimized helper for reading form values. The difference between watch and getValues is that getValues will not trigger re-renders or subscribe to input changes.

2. I think for Antd Input you should probably use `Controller` or `useController`

https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r

read more here: https://react-hook-form.com/advanced-usage#TransformandParse

**Comment by bibblebabl** [comment]
@bluebill1049 if you pay attention. I'm using native input (loot at `styles.ts` file). It is copy paste from real project, I didn't remove Ant from deps. I only used it for the `Title` and `Layout`. 

Even if getValues should't work in that way, isValid is still incorrect. 

I have removed ant completely from project. Here is a link https://codesandbox.io/s/ecstatic-goldwasser-gv4xv?file=/src/App.tsx So problem is still exists.

**Comment by bluebill1049** [comment]
read the doc under https://react-hook-form.com/api#setValue

`setValue('name', 'value', { shouldValidate: true })` i think you are missing the should validate

**Comment by bibblebabl** [comment]
@bluebill1049 thanks. seems it worked for me. 
to be honest, it wasn't obvious to me, since I was doing normalization, not validation. so without your help, I definitely wouldn't have guessed

**Comment by bluebill1049** [comment]
that's why you should read the doc. 👍
