### ISSUE TITLE
How to validate 'Select' in react-select with a controller (react hook form) when press submit

### ISSUE THREAD

**Issue by ChiSach** [react-hook-form/react-hook-form#3892]
**Describe the issue**
I combine the 'Select' component in React-select with 'controller' in React-hook-form. I set the rule = {{Required: true}}, when I press the Submit button with empty select option and I do not receive the required message.

**To Reproduce**

1. Go to [codeSandbox](https://codesandbox.io/s/react-select-forked-wpul7?file=/pages/index.js:1148-1164)
2. Click on clear select option
3. Click submit button
4. See validate

**Codesandbox link ** My [codeSandbox](https://codesandbox.io/s/react-select-forked-wpul7?file=/pages/index.js:1148-1164)

**Expected behavior**
When submit form with empty select, I will receive message required.

**Comment by bluebill1049** [comment]
you should use `validate` because `react-select` value is an object, and it's always going to pass the validation.

**Comment by ChiSach** [comment]
Thank you very much @bluebill1049
