### ISSUE TITLE
Pattern validation not sticking. It seems to toggle on and off.

### ISSUE THREAD

**Issue by stoplion** [react-hook-form/react-hook-form#3897]
Pattern validation not sticking. It seems to toggle on and off.

[![Image from Gyazo](https://i.gyazo.com/d1a0c5cb2958ed9da264402de535ef79.gif)](https://gyazo.com/d1a0c5cb2958ed9da264402de535ef79)

**Codesandbox link**

**https://codesandbox.io/s/muddy-sun-8uc8l?file=/src/App.js**

- OS: OS X latest
- Browser Chrome
- Version 6.14.1

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/104515325-c18ee900-5646-11eb-822d-98d2f1547927.mov

couldn't reproduce.

**Comment by stoplion** [comment]
Try a ten digit phone number like `7578717992` and continuously hit the send button

**Comment by bluebill1049** [comment]
`/\s*(?:\+?(\d{1,3}))?[-. (]*(\d{3})[-. )]*(\d{3})[-. ]*(\d{4})(?: *x(\d+))?\s*/g`

see the regex above there is `/g` at the end, that's the problem.

**Comment by stoplion** [comment]
Ahh.. I see in the docs where the `g` flag is mentioned. I've added `{exact: true}` to the sandbox and it works like expected. Thanks!

**Comment by bluebill1049** [comment]
all good.
