### ISSUE TITLE
Documentation website is unavailable 

### ISSUE THREAD

**Issue by alexjfno1** [react-hook-form/react-hook-form#3902]
**Describe the bug**
The documentation website is currently unavailable and returns a `404`

![image](https://user-images.githubusercontent.com/2777141/104586163-002f9e00-565d-11eb-859f-b5e4cee1f98d.png)

**To Reproduce**

1. Go to [https://react-hook-form.com/](https://react-hook-form.com/)
2. See the `404`

**Expected behavior**
Able to view the docs

**Comment by james2m** [comment]
I the meantime you can clone https://github.com/react-hook-form/documentation and `yarn && yarn start`

**Comment by alexjfno1** [comment]
It looks to be back working now.

**Comment by chrissyast** [comment]
Still failing for me

**Comment by jorisre** [comment]
> Still failing for me

Can you try in private navigation please ?

**Comment by chrissyast** [comment]
> > Still failing for me
> 
> Can you try in private navigation please ?

@jorisre  Same result

**Comment by jorisre** [comment]
> > > Still failing for me
> > 
> > Can you try in private navigation please ?
> 
> @jorisre  Same result

@chrissyast can you provide more info please ? I don't have any problem on my side. Thanks

**Comment by chrissyast** [comment]
> > > > Still failing for me
> > > 
> > > 
> > > Can you try in private navigation please ?
> > 
> > 
> > @jorisre  Same result
> 
> @chrissyast can you provide more info please ? I don't have any problem on my side. Thanks

ah, it's working now for me

**Comment by bluebill1049** [comment]
It's back now. thanks for everyone's help.
