### ISSUE TITLE
documentation doesn't seem to work

### ISSUE THREAD

**Issue by Newbie012** [react-hook-form/react-hook-form#3903]
**Describe the bug**
Documentation pages doesn't work

**To Reproduce**

1. Open https://react-hook-form.com/get-started

See
![image](https://user-images.githubusercontent.com/10504365/104586682-74bf0880-566e-11eb-903f-e4ac3615077d.png)

**Expected behavior**
Should work 😂

**Screenshots**
see image above

**Additional context**
https://vercel.com/docs/edge-network/frequently-asked-questions#why-do-i-see-a-404-error-when-accessing-my-deployment

**Comment by walkerdepaula** [comment]
The `/api` page it's not working too 😢

**Comment by bluebill1049** [comment]
Thanks, guys, it's an unknown issue, but doing a re-deploy fix the problem.
