### ISSUE TITLE
Bug: Validation on <Controller/> with render prop

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#3904]
**Describe the bug**
Validation does not seem to be working on the `<Controller/>` component when a custom input component is used with the render prop.

**To Reproduce**

1. Go to the sandbox below
2. Notice that validation is not occurring for the last name component using render and a custom input component.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-template-forked-8kfzt?file=/src/index.js

**Expected behavior**
As in the template  `<Controller/>`  sandbox, I expect errors to not be equal to `{}` and `invalid` to be `true` on the custom input component that receives via the render props field state.

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04 LTS
- Browser Chrome
- Version 87.0.4280.141 (Official Build) (64-bit)

**Attached files**
https://user-images.githubusercontent.com/36898266/104640925-f9edf180-565d-11eb-99b4-6d600aeab032.mp4

**Additional context**
The only thing I can think of is the `<input/>` is receiving the wrong props (I am using `{...field}`). I've tried using just the `ref` vs `onChange` but still no luck. If this is the case a note in the docs about this would be really helpful.

**Comment by oualidmaz** [comment]
By default the validation will trigger on "onSubmit" mode . if you want to validate onChange you have to add this : 

```
 const { handleSubmit, errors, control, watch } = useForm({
    mode: "onChange",
  });
```
Note : OnChange mode will causes performance issue due to multiple re-renders

![fix](https://user-images.githubusercontent.com/25105818/104660987-9da6c400-5695-11eb-9a9c-047e07b2b5b1.gif)


https://codesandbox.io/s/react-hook-form-controller-template-forked-beymi

**Comment by wdfinch** [comment]
I see. Ok, thanks so much. Sorry I missed that from the docs.

**Comment by bluebill1049** [comment]
Thanks @oualidmaz ❤️

**Comment by wdfinch** [comment]
Just an idea here, but maybe in v7 or a future major release `mode` could be renamed to `validationMode` or something more clear. I read through the entire docs, but I didn't think mode was the issue here due to the name. Just a thought.

**Comment by bluebill1049** [comment]
> Just an idea here, but maybe in v7 or a future major release `mode` could be renamed to `validationMode` or something more clear. I read through the entire docs, but I didn't think mode was the issue here due to the name. Just a thought.

Thanks for the feedback.
