### ISSUE TITLE
Add useTransform hook [feature-request]

### ISSUE THREAD

**Issue by sethsnel** [react-hook-form/react-hook-form#3906]
**Is your feature request related to a problem? Please describe.**
It can be quite challenging to have end users insert currency values. More often than not the application has to submit the value as number to an api. Whilst it is ux wise better to have endusers insert currency in a format they are familiar with, because this increases readability.

**Describe the solution you'd like**
A way to control actual underlying value of a field and it's transformed diaplay value for the enduser. Something like 'useTransform' hook, but I'm open to other solutions.

**Describe alternatives you've considered**
Transforming data when form state is initialized and transforming data on handleSubmit. The issue I have with this is about abstraction level. Initial form state and handlesubmit are quite high level and should not  need to be aware that somewhere down in a component there is a field that wants to display a number as localized currency text. So it's separation of concerns where I'm after. (something react-hook-form excels at thus far)

**Additional context**
https://angular-evan.medium.com/react-hook-form-our-implementation-6f2ed346c07
https://github.com/react-hook-form/react-hook-form/issues/615
https://github.com/react-hook-form/react-hook-form/blob/master/examples/parseFormatInputValues.tsx

**Comment by bluebill1049** [comment]
Thanks for the feature request, personally I prefer this sort of logic gets build by a specific component or external custom hook rather than live inside react hook form. I will leave this feature quest on the project board for a couple of weeks, and see if other users have a similar request, but most likely this will not be built into the core.

**Comment by bluebill1049** [comment]
we have `valueAs` for register now, this should make everyone's life a bit earlier, for a custom controlled component you can write your own logic at `onChange`, you can find an example here: https://react-hook-form.com/advanced-usage#TransformandParse
