### ISSUE TITLE
Adding an element to a field array causes Controller elements with a defaultValue to set dirty=true

### ISSUE THREAD

**Issue by joejordan** [react-hook-form/react-hook-form#3908]
**Describe the bug**
Using Material UI tabs and `useFieldArray` with `shouldUnregister=false`, adding a new element to the field array causes the pre-set default fields that are wrapped in a Controller to suddenly have `dirty` fields.

A side-effect of this setup is that RHF is reporting that the Controller is not using the `defaultValue` prop, when it most certainly is.

Possibly related: when removing the second item that was set with `defaultValues`, RHF does not clear out the state completely, so when you add a new field element, it is loaded with the Controller's old state.

**To Reproduce**
**First Bug:**
1. Go to https://codesandbox.io/s/reverent-lichterman-vl74s
2. Click on "Identifiers" tab
3. Click on "Add Field Element"
4. See unnecessarily dirty fields in the console AND incorrect warning about `Controller is missing defaultValue prop`

**Second Bug:**
1. Go to https://codesandbox.io/s/reverent-lichterman-vl74s
2. Click on "Identifiers" tab
3. Click "Remove" on one or both elements
4. Click "Add Field Element" 3 times
5. Notice that the old state is loaded into the Controller-based fields

**Codesandbox link (Required)**
https://codesandbox.io/s/reverent-lichterman-vl74s

**Expected behavior**
RHF should better handle state and dirty values in Controller-based fields in a field array

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome, Firefox
- Version: Latest

**Comment by bluebill1049** [comment]
> See unnecessarily dirty fields in the console AND incorrect warning about Controller is missing defaultValue prop

defaultValue is `undefined`
<img width="1124" alt="Screen Shot 2021-01-16 at 9 14 20 am" src="https://user-images.githubusercontent.com/10513364/104783924-385ceb00-57db-11eb-9fca-c03802fafa8c.png">

**Comment by joejordan** [comment]
> can you try to fix the `append` and see if the rest of the issues are still persisting?

Instead of feeding `append` an empty object, I set the fields to `{ type: null, value: '' }` and the Controller defaultValue warning went away. It also fixed the stale state being retained after removing all field elements and adding new ones back (Bug 2). 

It did not, however, address the `dirty` values being set on field array items that were loaded with defaultValues. To demonstrate, simply click "Add Field Element" on a fresh form and note the new `dirtyFields` on the elements that already existed. 

Expected behavior is that I should be able to add and then remove a Field Element, and the form state would go from `false` (initial load) to `true` (after adding the element), back to `false` (after removing the new element).

Also potentially related is that the `value` field is included with `undefined` as it's dirty state when we add a new Field Element. If you for example add and remove a 3 from the second SSN, the field is (correctly IMO) no longer included in the dirtyFields object.

**Comment by bluebill1049** [comment]
It's due to the input itself is a nested object, so reference compare fails, although I am a bit hesitant to introduce deepEqual, but I think this should fix simple nested field value like in your example.

**Comment by joejordan** [comment]
Interesting! Thanks for the very quick fix, looking forward to trying it out.

**Comment by joejordan** [comment]
@bluebill1049 got to try out the fix this morning, and there appears to be one minor issue. I updated the original example to 6.14.2 (https://codesandbox.io/s/reverent-lichterman-vl74s); if you 1) add a Field Element, then 2) remove the newly added Field Element, the `dirtyFields` object is empty, but `isDirty` remains true. I would expect that if `dirtyFields` was empty, then `isDirty` would also be false.

**Comment by bluebill1049** [comment]
for `isDirty` flag we are doing a deep equal with `defaultValues`.

`return !deepEqual(formValues, defaultValuesRef.current);`
