### ISSUE TITLE
isSubmitted does not update after reset()

### ISSUE THREAD

**Issue by borm** [react-hook-form/react-hook-form#3919]
**Describe the bug**
`isSubmitted` does not update after reset()
also tried with `omitResetState`

**Codesandbox link (Required)**
[codesandbox](https://codesandbox.io/s/react-hook-form-reset-issubmitted-state-after-form-submitted-forked-xpwir?file=/src/index.js)

**Comment by bluebill1049** [comment]
you need to do `reset` at `useEffect`, not within the `handleSubmit`.

**Comment by bluebill1049** [comment]
there is an example here as well in the doc: https://react-hook-form.com/api#reset

https://codesandbox.io/s/react-hook-form-handlesubmit-with-reset-xrh0t

**Comment by borm** [comment]
hm, no, so bad what i cant reset form after submit, too long delay after submit and `isSubmitted, isSubmitSuccessful` state updated
