### ISSUE TITLE
setValue with undefined resets the variable to its defaultValue

### ISSUE THREAD

**Issue by RLRabinowitz** [react-hook-form/react-hook-form#3922]
**Describe the bug**
1. Using `setValue('fieldName', undefined)` results in setting the value to the its `defaultValue` instead of `undefined`
2. `Controller` seems to ignore value change caused by `setValue('fieldName', undefined)`

**To Reproduce**

1. Go to Sandbox link
2. Type anything in input -> watched value changes accordingly
3. Click on "Set to 1234" -> Controlled input and watched value change to `'1234'`
4. Click on "Set to undefined" -> Controlled input value does not change (BUG) and watched value is changed to `'default'` (BUG)

**Codesandbox link (Required)**
https://codesandbox.io/s/sharp-bird-gh7jp?file=/src/App.js

**Expected behavior**
1. `setValue('myField', undefined)` should have set the value to `undefined`, and not the defaultValue `'default`'
2. Controlled input should have updated its value after `setValue('myField', undefined)` was called

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Chrome
- Version: 87.0.4280.141

**Comment by bluebill1049** [comment]
you probably aware `Controller`'s defaultValue doesn't support `undefined` and it's by design. however, you can work around this issue by the following CSB:

https://codesandbox.io/s/dawn-surf-mjcgx?file=/src/App.js

**Comment by avnerenv0** [comment]
@bluebill1049 I don't know if you saw this but the CSB isn't working as expected - you need to click 'setValue' twice for the input to be reset

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/104837327-e6fe4a00-5907-11eb-96a1-f7069b1b2c40.mov

**Comment by bluebill1049** [comment]
fixed try again.

**Comment by avnerenv0** [comment]
Sorry @bluebill1049 , still requires two clicks to reset the input.

Anyway - the issue is not that. The issue is when `defaultValue` is NOT `undefined`, but the `setValue` is TO `undefined`.
In essence - there is a default value, and there is also a button on the form to clear that field.

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/104837874-ab657f00-590b-11eb-900c-6a167d6d0772.mov

single click for me. do I miss the steps?

**Comment by avnerenv0** [comment]
> single click for me. do I miss the steps?

Yeah you are "cheating" :) You are triggering a `blur` event before clicking the button.
If you click `setValue` while the input is still in focus it's two clicks.

But again - not what this issue is about.

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/104838061-a8b75980-590c-11eb-9f6e-fac5da7fe94b.mov

I removed the extra state, still working for me as well. I didn't cheat lol 🙉

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/104838111-f0d67c00-590c-11eb-8503-98f73372d574.mov

**Comment by avnerenv0** [comment]
Looks good 👍 

What can be done if there is no controller involved - like this case - 
https://codesandbox.io/s/frosty-gareth-5lr55?file=/src/App.js

Thanks

**Comment by bluebill1049** [comment]
you probably want to move that `register` into `useEffect`, so it doesn't call each render? This is the wrong behavior for v6 with `watch` API, we are fixing it in the next major version v7.

**Comment by avnerenv0** [comment]
Thanks 🙏

**Comment by avnerenv0** [comment]
@bluebill1049 since this issue is closed, is there an issue/PR for that `watch` API , so we can stay updated on this matter?
Thanks

**Comment by bluebill1049** [comment]
> @bluebill1049 since this issue is closed, is there an issue/PR for that `watch` API , so we can stay updated on this matter?
> Thanks

This is not an issue, probably design mistaking change that behavior is a breaking change. you can follow the RFC here for v7: https://github.com/react-hook-form/react-hook-form/discussions

**Comment by RLRabinowitz** [comment]
> This is not an issue, probably design mistaking change that behavior is a breaking change

Hey @bluebill1049, why is that not a bug? Current `form.watch` returns the default value after performing `form.setValue(fieldName, undefined)`, instead of `undefined`.

 See https://codesandbox.io/s/frosty-gareth-5lr55?file=/src/App.js
`watch` returns the wrong value (the default), `getValues` however returns the correct value

**Comment by bluebill1049** [comment]
@RLRabinowitz like I suggested this is one of the design mistakes on the current version, in which `defaultValue` should only appear once before the actual render. we have corrected that in the next major version: https://codesandbox.io/s/serverless-bash-txy8e
