### ISSUE TITLE
useFieldArray append api adds default values of nested array

### ISSUE THREAD

**Issue by naveen4854** [react-hook-form/react-hook-form#3927]
**Describe the bug**
FieldArray retains child elements when a new item is added to replace its index, by replace I mean delete the existing item and add a new item

**To Reproduce**

1. Create a nested array form
     For example: 
     `
const defaultValues = {
  array1: [
    {
      name: "useFieldArray1",
      nestedArray: [{ field1: "field1", field2: "field2" }]
    },
    {
      name: "useFieldArray2",
      nestedArray: [{ field1: "field1", field2: "field2" }]
    }
  ]
};
`
2. And provide default values to fieldarray
3. Delete all the items in the first array, so now the form has empty items in array1
4. And then append a new item

`append({ name: "append" });
`
5. Something weird happens here, a new item is added to the list - array1 with nestedArray also added to the item

following code sandbox should help to reproduce

https://codesandbox.io/embed/react-hook-form-usefieldarray-nested-arrays-x7btr

**Comment by bluebill1049** [comment]
publishing the fix now.

**Comment by naveen4854** [comment]
can i please know the duplicate issue, just to be sure that its deployed

**Comment by lucifilote** [comment]
I can still reproduce this issue in version 7.7.1 btw.
