### ISSUE TITLE
Append from useFieldArray making the page scroll to top

### ISSUE THREAD

**Issue by am-rbrain** [react-hook-form/react-hook-form#3928]
Im using useFieldArray to add dynamic inputs.

```
  const { register, reset, control, watch, setValue, handleSubmit } = useForm({
    defaultValues: {
      answers: [
        {
          text: "Hello",
        },
      ],
    },
  });
  const { fields, append, prepend, remove, swap, move, insert } = useFieldArray(
    {
      control,
      name: "answers",
    }
  );
```

I am displaying like this:

```
 {fields.map((field, index) => {
    return (
      <div className="answer-field" key={field.id}>
        <input
          type="text"
          name={`answers[${index}].value`}
          ref={register()} // register() when there is no validation rules
          defaultValue={field.text}
          className="form--control"
        />
        <FontAwesomeIcon
          className="remove-quesiton-icon"
          icon={faTimes}
          onClick={() => remove(index)}
        />
     </div>
    );
  })}
```

And appending like this:

```
<button className="add-more-answers" onClick={() => append({ answers: "" })}>
    <FontAwesomeIcon icon={faPlus} />
    Add More...
  </button>
```

Problem is that whenever i hit append it scrolls the whole page to top?

**Comment by bluebill1049** [comment]
pretty sure this is not related to hook form, but you can try to disable the focus 

`append(..., false)`

https://react-hook-form.com/api#useFieldArray

**Comment by am-rbrain** [comment]
I found the prob.

It is related to react hook form somehow.  I should have change the type of the append button to "button". Otherwise it will try to submit the form and therefore scrolling to top to trigger errors. Though i don't display errors right now so i was really lost.

Damn, i feel stupid.

**Comment by bluebill1049** [comment]
aha, all good 👍 i make that mistake too.

**Comment by parvathirajan** [comment]
> pretty sure this is not related to hook form, but you can try to disable the focus
> 
> `append(..., false)`
> 
> https://react-hook-form.com/api#useFieldArray

Honestly, this solved my problem. Great!

**Comment by LeeonardoVargas** [comment]
This solved my problem: `append(..., { shouldFocus: false })`
