### ISSUE TITLE
Typescript issue with errors object

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#3929]
**Describe the bug**
If an input value is an object, then the errors object for that input (`errors.inputName`) will be the type of the object rather than the `<FieldErrors/>` type.

**To Reproduce**

1. Go to https://codesandbox.io/s/summer-sunset-b2wwn
2. Uncomment line 43
3. Observe how the message property of the error cannot be referenced because typescript thinks the type is the input value type (in this case {value: string, label: string})

**Codesandbox link (Required)**
https://codesandbox.io/s/summer-sunset-b2wwn

**Expected behavior**
The errors object for an object value input should still be the `<FieldErrors/>` type.

**Screenshots**
![Screenshot from 2021-01-17 13-50-11](https://user-images.githubusercontent.com/36898266/104857112-2490b200-58cb-11eb-9029-4dca706a869e.png)

**Comment by bluebill1049** [comment]
use this type: https://react-hook-form.com/ts#NestedValue 👍

**Comment by wdfinch** [comment]
Thanks. That works but it seems like I need to destructure my object for it to be accepted by `NestedValue`.

so for example, if I have: 

```
interface Option {
  value: string
  label: string
}
```

I cannot do `NestedValue<Option>`

I must do `NestedValue<{[key: string]: keyof Option}>`

Would be nice if the first one could work.
