### ISSUE TITLE
Need to memoize returned object from useForm()

### ISSUE THREAD

**Issue by zeckdude** [react-hook-form/react-hook-form#393]
**Describe the bug**

```js
const {
        register,
        getValues,
        unregister,
        triggerValidation,
      } = useForm({
        mode: 'onChange',
      });
    
    const values = getValues();
```

Then I am using a `useEffect()` hook to run a series of function from the `useForm()` hook's returned object whenever a certain value changes:

```js
useEffect(() => {
        unregister([
          'lostDate',
          'lostTimezone',
          'amountReceived',
        ]);
    
        if (values.reason === 'REASON_1') {
          register({ name: 'lostDate' }, { required: 'Choose a lost date' });
          register({ name: 'lostTimezone' }, { required: 'Choose a timezone' });
        }
    
        if (values.reason === 'REASON_2') {
          register({ name: 'amountReceived' }, { required: 'Choose the amount received' });
        }
    
        triggerValidation();
      }, [values.reason, register, unregister, triggerValidation]);
```

This causes an infinite loop. I was reading up on it and it seems that I need to memoize the returned value from the `useForm()` call. I tried to do this:

```js
const useFormOptions = React.useMemo(
    () => ({
      mode: 'onChange',
    }),
    [],
  );

const {
    register,
    getValues,
    unregister,
    triggerValidation,
  } = useMemo(() => {
    return useForm(useFormOptions);
  }, [useFormOptions]);
```

My linter gives me this error though: 

> React Hook "useForm" cannot be called inside a callback. React Hooks
> must be called in a React function component or a custom React Hook
> function.eslint(react-hooks/rules-of-hooks)

I get this error from the `react-hook-form` library though:
<img src="https://i.stack.imgur.com/7bInn.png" />

Any ideas where I am going wrong?

**Codesandbox link**
This will crash the sandbox window pretty quickly
https://stackblitz.com/edit/react-hook-form-use-memo 

You can see it better here. Just make sure to open the inspector before so you can see the console I added inside the `useEffect()` call to show it is re-rendering over and over.
https://react-hook-form-use-memo.stackblitz.io

**Expected behavior**
Expect to be able to add useForm methods as dependencies in `useEffect()` call without causing infinite loops.

**Screenshots**
Up top

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 76

**Smartphone (please complete the following information):**
NA

**Additional context**
Nope

**Comment by bluebill1049** [comment]
thanks Chris for your detailed issue report! I will take a look at it :)

**Comment by bluebill1049** [comment]
all the methods are all memories, I think having `register/unregister` then `triggerValidation` maybe the root cause of this issue. i tried with the following and works.

```
useEffect(() => {
    register({ name: 'name' }, { required: 'Choose a name' });
    register({ name: 'notes' }, { required: 'Add notes' });
    console.log('why')
  }, [register]);

  useEffect(() => {
    console.log('Extra fields useEffect ran'); 
    unregister(['hobby, location']);

    if (values.name === 'Chris') {
      register({ name: 'hobby' }, { required: 'List a hobby' });
    }

    if (values.name === 'Jeff') {
      register({ name: 'location' }, { required: 'What is your location' });
    }
  }, [values.name, register]);

  useEffect(() => {
    triggerValidation();
  }, [values.name])
```

**Comment by zeckdude** [comment]
Thanks for looking into the issue @bluebill1049! Why would I need to separate `triggerValidation()` into a separate `useEffect()` call? That looks pretty confusing to any other engineer who works on the code later. Is there any way that can be fixed behind the scenes so the `triggerValidation() ` can remain in the same `useEffect()`?

Also I'm a bit concerned that the first `useEffect()` doesn't necessarily register those fields before the `triggerValidation()` runs. What do you know about that?

**Comment by bluebill1049** [comment]
> Thanks for looking into the issue @bluebill1049! Why would I need to separate `triggerValidation()` into a separate `useEffect()` call? That looks pretty confusing to any other engineer who works on the code later. Is there any way that can be fixed behind the scenes so the `triggerValidation() ` can remain in the same `useEffect()`?

True, I will investigate abit more on this, what's the reason behind trigger validation right after register?

**Comment by zeckdude** [comment]
Thank you! That would be great! The reason I am calling `triggerValidation` right after register is because when I unregister all those fields and then register the new ones, the `isValid` flag doesn't automatically go back to `false`, so I need it to re-evaluate the form validation with the newly registered fields. I am using the `isValid` flag to determine if the submit button should be enabled/disabled.

**Comment by bluebill1049** [comment]
oh, I see, good point :)

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-trigger-validation-to-delete-1296w

will be patched in the next release 

`3.24.2-beta.3` you can use this beta if impact your project

**Comment by zeckdude** [comment]
Wow! You work fast! Works great! Thanks so much! 🎉 🥇 💯

**Comment by repl-shenoy-sukumaran** [comment]
I have also same issue as useForm return new object every time it does un-wanted re-renders (our eslint force to add it as dependency)

https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L1335 (this return should be wrapped in useMemo?
