### ISSUE TITLE
handleSubmit not forwarding data to local function

### ISSUE THREAD

**Issue by gilneto8** [react-hook-form/react-hook-form#3939]
**Describe the bug**
I have a form using the Yup resolver and, after passing validation, the submitting function doesn't render any data.

**To Reproduce**

1. Go to [Code sandbox](https://codesandbox.io/s/great-jones-0mqss) (didn't go with template because I needed the yup resolver and my code was a bit different from the templates...);
2. Fill 'value' field with anything, and remaining fields accordingly (e.g., Type 'click', Attribute 'id');
3. Click 'Submit';
4. If no filling errors appear, on the console the data should appear.

**Expected behavior**
The 'onSubmit' function should show all the data on the console.

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04
- Browser Firefox
- Version 84.0.2 (64-bit)

**Comment by bluebill1049** [comment]
<img width="1088" alt="Screen Shot 2021-01-19 at 8 49 52 am" src="https://user-images.githubusercontent.com/10513364/104965664-4dcc5200-5a33-11eb-8bd4-7bd43250189a.png">

because your schema declared id is required.
