### ISSUE TITLE
Material UI uncontrolled input

### ISSUE THREAD

**Issue by vicasas** [react-hook-form/react-hook-form#3940]
**Describe the bug**

Integrating RHF with MUI I realized that the console throws me the uncontrolled component error when using the implementation with the Controller component.

For me this is an error since as indicated in the React documents and in the same error the form inputs must be controlled.

Is there a solution for that?

**To Reproduce**

1. Create a form
2. Use the Controller component of RHF
3. In the prop place place the MUI TextField text component
4. Write in the input
5. Check the browser console and the error will appear.

**Codesandbox link (Required)**

- [Example](https://codesandbox.io/s/youthful-snow-il5vf?file=/src/App.js)

**Expected behavior**

What is expected as the documents say is that the text field is controlled.

**Screenshots**

![image](https://user-images.githubusercontent.com/57921784/104960702-86c4e200-59b3-11eb-98dc-c4544ea52908.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome lastest
- Version RHF 6.14.2
- Version MUI 4.11.2

**Additional context**

This after doing the RHF implementation with Material UI

**Comment by bluebill1049** [comment]
`<Controller as={TextField} name="names" control={control} defaultValue="" />`

also `as` is getting deprecated in the next major, use `render` instead.

**Comment by bluebill1049** [comment]
<img width="920" alt="Screen Shot 2021-01-19 at 8 45 23 am" src="https://user-images.githubusercontent.com/10513364/104965349-acdd9700-5a32-11eb-8570-31ab30e17b85.png">
in the doc
