### ISSUE TITLE
watch on property which holds fileList is undefined on firefox after upload

### ISSUE THREAD

**Issue by Nightliss** [react-hook-form/react-hook-form#3946]
**Describe the bug**

**To Reproduce**

Chrome
1. Go to https://codesandbox.io/s/magical-torvalds-k30cv?file=/src/App.js
2. Open console - initial log should be undefined
3. Upload any file
4. In console it should log upload file twice; on Firefox the second log is undefined

**Codesandbox link (Required)**
https://codesandbox.io/s/magical-torvalds-k30cv?file=/src/App.js

**Expected behavior**
Same as on Chrome

**Screenshots**
Chrome:
![image](https://user-images.githubusercontent.com/30467858/105034177-6ea79e00-5a59-11eb-9032-94704acacfd2.png)

Firefox:
![image](https://user-images.githubusercontent.com/30467858/105034226-7b2bf680-5a59-11eb-8d69-b7d60860fc2f.png)

**Desktop (please complete the following information):**

- OS: Win 10 Pro x64 20H2
- Browser: Firefox Developer
- Version: 85.0b8

**Comment by bluebill1049** [comment]
I think there is little we can do about it, why do you need to `setValue`?  I think you probably should avoid that with input file due to security concerns, I think firefox probably is doing the right thing.

**Comment by Nightliss** [comment]
I wanted to do some front validation like check file size, but now I realize I can do that in useEffect on watched field 🤦. Sorry to bother you, gonna close it :)

**Comment by bluebill1049** [comment]
no worries at all, glad you found a solution. the input file is a serious one for security, so quite a bit of constraint around it (not a bad thing).
