### ISSUE TITLE
Include information about failing validation constrain in formState.errors.

### ISSUE THREAD

**Issue by eagor** [react-hook-form/react-hook-form#3950]
**Is your feature request related to a problem? Please describe.**
I have a helper function that takes the `formState.errors[fieldName]` as parameter and uses it's `type` field to constructs an error message. For the failing minLength/maxLength validations I'd like to indicate the desired length in the error message.
````javascript
function formErrorMessages(fieldError) {
  if (fieldError.message) return fieldError.message;

  switch (fieldError.type) {
    case ERROR_TYPES.required:
      return 'Field is requried';
    case ERROR_TYPES.minLength:
      return 'Value is too short';   // <-- I want `Value must be at least {x} characters long`.
    default:
      return 'Invalid';
  }
}
````

**Describe the solution you'd like**
`formState.errors[fieldName]` to include optional payload field, similar to how angular [does](https://angular.io/api/forms/Validators#minLength-usage-notes) it:
````javascript
{
  message,
  type: "minLength",
  ref,
  minLength: {  // <-- this key to match the type, as there might be multiple errors.
    required,
    actual
  }
}
````

**Describe alternatives you've considered**
Pass the required length as error message in register: `register({ minLength: { value: 2, message: 2 } })`. But it's it's a duplication, and `2` is not really a message. Could also provide the whole error message here, but I still need to repead the `2` inside the error message, and my helper function is useless in this case.
Or I could pass it as optional 2nd parameter for my `formErrorMessages` function, but again, its a duplication, that would require extracting the `2` into variable to make sure validation and error message always match when in future someone only updates the validation rule and not the message.

**Additional context**
-

**Comment by bluebill1049** [comment]
good feature request! i believe you can achieve this with `validate` function for now.

**Comment by bluebill1049** [comment]
moving this into our feature board, I think we will keep it simpler:

```
{
  actual: 0,
  expected: 5
}
```

**Comment by bluebill1049** [comment]
what if an error message can accept a callback?

```
({
  received: 0,
  expected: 5
}) => string
```

**Comment by DavidRouyer** [comment]
Can this be prioritized? We have no way to fetch the value passed to the `register` function? (Even in the `formState` ?)
```
{...register('name', {
  required: true,
  maxLength: 200,
})}
```

**Comment by bluebill1049** [comment]
maybe the API should be 

```tsx
{
  detail: {
    received: 0,
    expected: 5
  }
}
```
