### ISSUE TITLE
Validation not working with React-Select (No Yup)

### ISSUE THREAD

**Issue by gustavomm19** [react-hook-form/react-hook-form#3959]
**Describe the bug**
Hi! I am using a library called react-timezone-select (which is totally absed on react-select) and validation with Controller is not working :(

I saw someone with a similar issue here, but he was using Yup and I am not. How could I fix this?

I need help

Sandbox here:
https://codesandbox.io/s/help-with-react-select-and-form-hook-ooh9x

**Comment by bluebill1049** [comment]
please post questions at Discussion, i think you may want to use `render` instead.
