### ISSUE TITLE
map api response error to the form

### ISSUE THREAD

**Issue by SanjuAppeonix** [react-hook-form/react-hook-form#396]
Is there any way to map the errors from api response other than the setError method?
For eg: my api response comes like

`{
    code: 400,
    response: {
        email: ["The email has already been taken."],
        phone: ["The phone has already been taken."]
    },
    status: "error"
}`

so how can i map these errors to the respective fields or how can it be done using the setError method.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/#setError
```
const { response }  = data;
Object.entries(response).forEach(([name, value]) => { setError(name, value) });
```

what's on top of my head.

**Comment by bluebill1049** [comment]
Hope my answer helps. going to close this issue, feel free to leave more questions or reopen the issue.
