### ISSUE TITLE
valueAsNumber converts empty string to 0

### ISSUE THREAD

**Issue by LauSam09** [react-hook-form/react-hook-form#3963]
**Describe the bug**
For optional fields, having an empty string converted to `0` is undesirable, and we're having to work around the issue by doing `setValueAs: (value: string) => value === "" ? undefined : +value`. I believe this should be the behaviour of `valueAsNumber`. 

**To Reproduce**

1. Go to Code Sandbox below
2. Open console and click `Submit`
3. See `myNumber` has been given a value of `0` instead of undefined.
4. See desired behaviour from 2nd input and how it could work with required fields with the 3rd input.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-optional-valueasnumber-40grr

**Expected behavior**
valueAsNumber should convert empty strings to undefined to allow optional field values.

**Additional context**
react-hook-form v6.14.2

**Comment by bluebill1049** [comment]
Thanks for the issue report, i think we have the option to either give `NaN` (native behavior) or `0`. I did go ahead with `0` instead, i think for your use case `setAsValue` is the preferred solution.

**Comment by LauSam09** [comment]
I see what you mean - `NaN` would be better than `undefined` and changing it in the CSB seems fine. Our server would complain about `NaN` but it's a simple process to loop over properties and remove those properties (something not possible with `0` as it is a valid value). 

I've looked over the RFC and I'm curious as to why `0` was chosen over `NaN` - I'm struggling to think of a use-case where anyone would want an empty string to be converted to `0`. On the other hand, having optional numbers is probably fairly common, and makes `valueAsNumber` unusable.

**Comment by bluebill1049** [comment]
hmmm, you made a good point, the reason I went with 0 was purely focused on the `number` part.

**Comment by elie222** [comment]
Agree that this should be the default:

```ts
export function setValueAsNumber(value: string) {
  return value === '' ? undefined : +value;
}
```
