### ISSUE TITLE
Validation rules on Controller or useController minLength not working

### ISSUE THREAD

**Issue by rdewolff** [react-hook-form/react-hook-form#3968]
**Describe the bug**
When trying to use validation rules on React Native and `Controller` or `useController()`, I could not get the `minLength` validation to trigger and display an error message.

Maybe I use it wrong? But I could setup a Snack to reproduce the problem.

**To Reproduce**
- Use react-native
- Create a validation rule with a controller
- The validation rules does not generate any error message

Example:
```
rules={{ required: { value: true, message: 'required' }, minLength: { value: 3, message: 'too short'} }}            
```

The `required` rule works, but the `minLength` rule does not.

**Codesandbox link (Required)**

Snack : https://snack.expo.io/OTb9eV2hK

**Expected behavior**
The validation rule should display an error message "too short" when the field char's length is less than 3.

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS catalina and Expo Snack
- Browser Firefox
- Version latest: 84.0.2 (64-bit)

**Smartphone (please complete the following information):**

- Device: iPhone 11 
- OS: iOS 13.5

**Additional context**
n/a

**Comment by bluebill1049** [comment]
<img width="1415" alt="Screen Shot 2021-01-21 at 8 41 01 am" src="https://user-images.githubusercontent.com/10513364/105244308-6b7cf100-5bc4-11eb-9652-72d98b99589b.png">

works for me? unless you want to show both error message which is `criteriaMode`

**Comment by rdewolff** [comment]
Yeah got it working, was mixing the field checked in the error message 🙈 
Thanks for the quick feedback and for closing the issue 🙏

**Comment by bluebill1049** [comment]
no worries @rdewolff ❤️
