### ISSUE TITLE
MUI RadioGroup - setValue() doesn't update the value

### ISSUE THREAD

**Issue by MinaAmrouche** [react-hook-form/react-hook-form#397]
Hello,

I use Material UI RadioGroup component and I would like to change the value of this radio input by using `setValue()` when another field in my form changes, but it doesn't seem to have any control on the value of RadioGroup.

Here is a simple example of what I'm trying to do:
https://codesandbox.io/s/withered-cloud-1xeq2

When the value of the first block changes, `setValue` is called to update the value of the second block but nothing happens.

Am I missing something ?

**Comment by bluebill1049** [comment]
hey @michaelbirchler,

I think you probably want to post this issue at Material-UI. I don't think material-ui is updating the UI when `checked` set to `true`

**Comment by chungweileong94** [comment]
Hi @MinaAmrouche,

MUI works differently, the `checked` prop of the `<input/>` in the `RadioGroup` component can only trigger by the user interaction.

From my experience, in order to set the value of the radio group, you have to create a custom component with state to wrap around the RadioGroup component

**Comment by bluebill1049** [comment]
thanks @chungweileong94 for helping, I think MUI is not supporting uncontrolled components. that's the main reason, while react hook form is based on uncontrolled component to have better performance and trigger less re-rendering.

**Comment by MinaAmrouche** [comment]
Thank you for your answer @chungweileong94.
I've decided to create my own Radio component based on MUI style and it works just fine.
You're right @bluebill1049, MUI doesn't support uncontrolled components entirely.

**Comment by bluebill1049** [comment]
Good to hear @MinaAmrouche ❤️🙏🏻

**Comment by karimja** [comment]
Mina

Would you mind sharing the code for your custom component. I am keen to use this library over formik but want to ensure that it will work with MUI.It would be good to see how you have developed the custom component

**Comment by MinaAmrouche** [comment]
@karimja here is my previous example with the custom Radio component :
https://codesandbox.io/s/quiet-currying-2gy6l

I pretty much copied-paste the MUI Radio component so that it looks almost exactly the same and now I can do whatever I want with it.
I hope it helps.

I had problems with 2 MUI components so far:
* Select
* Radio
After spending a few hours trying to make them behave like I needed, creating custom ones seemed to be a good solution for me. But it depends on your use cases of course.

**Comment by bluebill1049** [comment]
going to close this issue @karimja feel free to continue the discussion in here tho. thanks for your help @MinaAmrouche <3

**Comment by keemor** [comment]
For any one who came here wondering how to integrate MUI RadioGroup with hook-form here is an example of handling controlled MUI RadioGroup component with react-hook-form

https://codesandbox.io/s/handling-controlled-mui-component-with-react-hook-form-run4z

**Comment by bluebill1049** [comment]
Thanks for your the example @keemor

**Comment by dandv** [comment]
@keemor: thanks for the example. Surprisingly complicated :( I was hoping that the RadioGroup would provide a value to RHF onSubmit's data, but no, you must call `useForm().setValue` from each radio button's onChange. Is there really no simpler way in 2020 to have the value of a radio button be gathered along with other form elements into one `data` object, the way `TextField`s allow?

**Comment by bluebill1049** [comment]
Take a look at this example: https://codesandbox.io/s/react-hook-form-controller-079xx @dandv

**Comment by dandv** [comment]
Thanks @bluebill1049, that example is much simpler and a comprehensive Material UI example with all the controls. I wish I had found it at https://github.com/react-hook-form/react-hook-form/tree/master/examples, would've saved me a few hours :)

**Comment by utegenovkamel** [comment]
@bluebill1049
If I have a pagination test
There are answer options - this is a radio input and all inputs must have the same name
If I answered all the questions on page 1, and go to page 2 and back to page 1, I need to display all the user's answers
How can I set the value to the input via setValue () which have the same input name

**Comment by bluebill1049** [comment]
> @bluebill1049
> If I have a pagination test
> There are answer options - this is a radio input and all inputs must have the same name
> If I answered all the questions on page 1, and go to page 2 and back to page 1, I need to display all the user's answers
> How can I set the value to the input via setValue () which have the same input name

can you share a simple codesanbox?
