### ISSUE TITLE
Form onChange does not fire when useFieldArrayis used.

### ISSUE THREAD

**Issue by dbousamra** [react-hook-form/react-hook-form#3978]
**Describe the bug**
My form `onChange` handler does not receive events when `useFieldArray` is used.

**To Reproduce**

1. Use a `useFieldArray`.
2. Modify said array
3. See that `onChange` is not fired

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-onchange-fieldarray-zmfue?file=/src/index.js

**Expected behavior**
I expect my `onChange` to fire.

Some background: I am using onChange as a way to debounce an autosave to the server. Is this the recommended approach to avoid rerenders? Do you have an autosave example? 

Thank you for this really nice library and your open source contribution

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bluebill1049** [comment]
`onChange` mode is made for input chnage validation.

**Comment by dbousamra** [comment]
> `onChange` mode is made for input change validation.

Thanks. What does this mean? Can I not use the form onChange to capture ALL changes to the form? Should i subscribe using useWatch? My goal is to debounce ALL changes to the form, and then perform a server save.

**Comment by bluebill1049** [comment]
oh you the `onChange` event, I got mixed up with `mode: 'onChange'`.

`onChange` event works fine.
<img width="1044" alt="Screen Shot 2021-01-21 at 8 47 23 pm" src="https://user-images.githubusercontent.com/10513364/105333465-ddd3ec80-5c29-11eb-8442-30632158b2ba.png">

do you mean like `append` action?

**Comment by dbousamra** [comment]
Yeah, I mean append, remove etc. I would expect if I add new items to the array, for them to be reflected in my onChange

**Comment by bluebill1049** [comment]
they don't trigger onChange, they do not fire change events for the inputs.

**Comment by dbousamra** [comment]
Okay. Thanks.

What do you recommend?

**Comment by bluebill1049** [comment]
Can you try `useWatch`? by create an extra component and subscribe to the change it? V7 next major version will make your life easier, but it's still under construction.

**Comment by dbousamra** [comment]
Thanks. I think I tried using useWatch. I think i was incurring a lot of rerenders. I would like to debounce (i.e. I dont need the latest results, and am happy to debounce to 1000ms).

**Comment by bluebill1049** [comment]
> Thanks. I think I tried using useWatch. I think i was incurring a lot of rerenders. I would like to debounce (i.e. I dont need the latest results, and am happy to debounce to 1000ms).

`useWach` should isolate that re-render right? not trigger render at your form level.

**Comment by bluebill1049** [comment]
oh... why not just do that on `onClick` and denounce there?

**Comment by dbousamra** [comment]
I will give it a go in my actual app tomorrow. I will try in codesandbox now.

**Comment by dbousamra** [comment]
> oh... why not just do that on `onClick` and denounce there?

onClick? onClick where? It's auto-save (i.e. no button)

**Comment by bluebill1049** [comment]
> > oh... why not just do that on `onClick` and denounce there?
> 
> onClick? onClick where? It's auto-save (i.e. no button)

even autosave, users still need to click the button to append / prepend right?

**Comment by bluebill1049** [comment]
you can add a debounce with onChange at the form level, and denounce all the actions.

**Comment by dbousamra** [comment]
Ohh. Right.

Sure. I could debounce that. But I have hundreds of form fields. I was hoping to have a top level component `<AutoSave control={control} />` that supervised the form and submitted on changes. I am working on an example in codesandbox atm. Thanks for your help.

**Comment by dbousamra** [comment]
@bluebill1049 I think I have something working: https://codesandbox.io/s/react-hook-form-onchange-fieldarray-zmfue?file=/src/index.js

**Comment by bluebill1049** [comment]
try: `deepEqual`

**Comment by dbousamra** [comment]
https://codesandbox.io/s/react-hook-form-onchange-fieldarray-zmfue?file=/src/index.js

Doesn't seem to help. Is this what you meant? I copied the deepEqual implementation from react-hook-form.

**Comment by bluebill1049** [comment]
maybe try this hook? https://github.com/streamich/react-use/blob/master/docs/useDebounce.md

**Comment by bluebill1049** [comment]
any luck?

**Comment by dbousamra** [comment]
Hey @bluebill1049 Yeah I did have some luck. I ended up with a semi working solution. Not at my PC right now so can't post the code. I will post it as an autosave solution that perhaps can be included in the examples, when I get back. I think you can close this issue. Thanks for your help!

I ran into I guess, an unrelated fundamental issue that i don't know how to solve. How do I get access to the values in my form state that aren't registered to inputs? I.e. If I have an initial values of:

```
const initialValues = {
  items: [{ name: "abc", age: 30 }, { name: "def", age: 40 }]
}
```
And say I track that using a useFieldArray, where I wire up the name fields using an input. 

I want to be able to get access to all the values using watch or getValues, so I can post that to the server. Does that make sense?

**Comment by dbousamra** [comment]
Just discovered `shouldUnregister` which does exactly what I need. It seems like V7 will help me also.

**Comment by bluebill1049** [comment]
v7 is 100% going to help you.

```
React.useEffect(watch(deboucne((data) => data, 1000)), [watch])
``` 

you can subscribe tot he form inputs with a callback
