### ISSUE TITLE
Add Dynamic Fields to the form

### ISSUE THREAD

**Issue by zsid** [react-hook-form/react-hook-form#398]
**Is your feature request related to a problem? Please describe.**
* I am struggling  to find an example with dynamics fields. For example, we have a todo list where a user can add/remove todos from the form.

**Describe the solution you'd like**
* I would like to have an example in the docs or in the examples folder, where we can add remove dynamic fields. Field array example is helpful but it does not shown how to add/remove items to that array. 
* I would assume that when you edit the form and initialise it with the dynamic values, the behaviour describe above would work as expected

**Describe alternatives you've considered**
* I used another state in the component to track the items that can be dynamically added/removed but that creates two sources of truth and it is not a good solution. Also, in the array when I add, remove, add the item, the array values in the form has empty entries.

Keep up the good work and thanks in advance!

**Comment by bluebill1049** [comment]
https://react-hook-form.com/advanced-usage#FieldArrays

I think this is what you after.

**Comment by MinaAmrouche** [comment]
Is it what you are looking for : https://codesandbox.io/s/6j1760jkjk ?

**Comment by zsid** [comment]
@MinaAmrouche, yes this is what i would like to have. The issue with this one is that we now have two sources of truth which the form is tracking and our state as well. Also if you do the following:

1. Add three friends, filling in all of the fields
2. Delete your second entry
3. Enter a new friend and fill in the details.
4. Press submit - you will see that our form array has 4 values with one of them being empty
```
[
  {
    "firstName": "1",
    "lastName": "1"
  },
  null,
  {
    "firstName": "3",
    "lastName": "3"
  },
  {
    "firstName": "4",
    "lastName": "4"
  }
]
```

I would have expected to not have null in the array and have 3 values in the correct order.

**Comment by bluebill1049** [comment]
For the null value, you can easily filter them out.

**Comment by zsid** [comment]
Thanks for the responses. So to conclude the end result is the same as my alternative and there are no other options - you will need to have another state in your component to track the dynamic entires and not having one source of truth for the state of your data.

I will close the issue. 😄

**Comment by bluebill1049** [comment]
I am pretty sure you can have a single source of truth, it's matter of how you structure your data. you can use `uuid` to generate a key for each of your object. 

`[{ id: uuid() }, { id: uuid() }]`

and you maintain that array of objects. I think its worth to give it a try.

**Comment by mjsarfatti** [comment]
@zsid I came here because I encountered the same problem. A slight improvement on your solution can be to `delete` the array element instead of setting it to `null` or `''`, or splicing it away:

```js
  const [fields, setFields] = useState([]);

  const addField = () =>
    setFields(fields => {
      // DON'T USE [...spread] to clone the array because it will bring back deleted elements!
      const outputState = fields.slice(0);
      outputState.push('');
      return outputState;
    });

  const removeField = idx =>
    setFields(fields => {
      const outputState = fields.slice(0);
      // `delete` removes the element while preserving the indexes.
      delete outputState[idx];
      return outputState;
    });
```

Working example: https://codesandbox.io/s/react-hook-form-array-fields-8opi2

**Comment by bluebill1049** [comment]
FYI guys we are working on a new custom hook for this: 

https://github.com/react-hook-form/react-hook-form/pulls

take a look, if you have sometime feel free to test it out and help us to release it sooner to everyone 👍

**Comment by arpit016** [comment]
hey @bluebill1049 any idea how can I add yup validation to dynamic forms as the name field will be generated during run time?

**Comment by bluebill1049** [comment]
> hey @bluebill1049 any idea how can I add yup validation to dynamic forms as the name field will be generated during run time?

Do you mean `useFieldArray`?

**Comment by arpit016** [comment]
yes basically in this example [https://codesandbox.io/s/6j1760jkjk](https://codesandbox.io/s/6j1760jkjk) i am struggling how i can use Yup validation to validate the fields as required

**Comment by arpit016** [comment]
@bluebill1049 I was able to add the validation in the Add Friends List example below is the codesandbox link: Do yo have any better suggestion that can be improved?

[My Implementation](https://codesandbox.io/s/react-hook-form-array-fields-lkgpv?file=/src/index.js)

[Original Implementation](https://codesandbox.io/s/6j1760jkjk)

**Comment by bluebill1049** [comment]
hey @arpit016 i think you missing this hook: https://react-hook-form.com/api#useFieldArray

**Comment by mdaffan** [comment]
Hey, how do I get append from useFieldArray to act dynamically? For example, after fetching data from API(Array of objects), I want every element In that API fetched array to be in fields of useFieldArray. I tried mapping elements and append({...item}) inside map itself but that didn't work and only one element was added

**Comment by bluebill1049** [comment]
> Hey, how do I get append from useFieldArray to act dynamically? For example, after fetching data from API(Array of objects), I want every element In that API fetched array to be in fields of useFieldArray. I tried mapping elements and append({...item}) inside map itself but that didn't work and only one element was added

use `setValue('test', [...])

**Comment by nprasanth-fs** [comment]
Hi i can pass my useffect api data in the defaultvalues ? , i am getting undefined 
 const { register, control, handleSubmit, reset, watch } = useForm({
    defaultValues: {
        test: dyn_arr
    }
  });

**Comment by bluebill1049** [comment]
> Hi i can pass my useffect api data in the defaultvalues ? , i am getting undefined
> const { register, control, handleSubmit, reset, watch } = useForm({
> defaultValues: {
> test: dyn_arr
> }
> });

`useEffect` with `reset`

**Comment by nprasanth-fs** [comment]
> > Hi i can pass my useffect api data in the defaultvalues ? , i am getting undefined
> > const { register, control, handleSubmit, reset, watch } = useForm({
> > defaultValues: {
> > test: dyn_arr
> > }
> > });
> 
> `useEffect` with `reset`

I have tried with reset, but still i can't see the values in my defaultValues , in console log I can see my values , and if I pass a static array of objects into defaultValues its working fine,

**Comment by ItayGershman** [comment]
https://jasonwatmore.com/post/2020/09/29/react-dynamic-form-example-with-react-hook-form
In my opinion, this page explains how to control the dynamic form with react-hook-form.
Enjoy :)
