### ISSUE TITLE
problem with zod validation of nativeEnum with optional

### ISSUE THREAD

**Issue by kerosan** [react-hook-form/react-hook-form#3985]
Hi, pls help me
i cant validate my schema with zod using z.nativeEnum(Enum).optional()

example:

https://codesandbox.io/s/react-hook-form-nestedvalue-forked-6gh4n?file=/src/App.tsx

optional field is invalid how i can fix it?
![image](https://user-images.githubusercontent.com/10149363/105379319-61371300-5c15-11eb-9a17-557c2b5f8a8b.png)

workaround - but it looks strange 
![image](https://user-images.githubusercontent.com/10149363/105379509-92afde80-5c15-11eb-9c89-39a8bc1a188d.png)

**Comment by jorisre** [comment]
Hi @kerosan 
Thanks for reporting, it seems the value is an empty string that's why you get this error. 
`select: undefined` is transformed to `select: ""`.

@bluebill1049 I'm not sure to have time to find a fix

**Comment by bluebill1049** [comment]
<img width="663" alt="Screen Shot 2021-01-22 at 9 42 52 am" src="https://user-images.githubusercontent.com/10513364/105421442-3640d380-5c96-11eb-874a-35880445520c.png">

maybe worth sending a question at Zod. hook form only throw the data at the `schema.safeParse`

`schema.safeParse(values, options);`

and this is the `values`

`{name: "Name", select: ""}`

**Comment by kerosan** [comment]
But form is invalid and submit don't work 😥

**Comment by jorisre** [comment]
@bluebill1049 zod receives `select: ""` instead of `select: undefined` that's why zod throw an error. I don't think it's a zod's issue

**Comment by bluebill1049** [comment]
Thanks @jorisre makes sense, we return an empty string for all native input, for example, `select` and `input`, undefined is not applicable for native input. for radio input, we are retiring its selected `value`, if nothing selected, we return '' as well.

**Comment by jorisre** [comment]
Good to know ! thanks, where can I find this information is the documentation ?

**Comment by kerosan** [comment]
@bluebill1049 it's not only about radio buttons, in my project I use nativeEnum for drop down component and method .optional() works same

**Comment by bluebill1049** [comment]
@jorisre I don't think this is documented... which is my bad.

@kerosan that's the thing for native form behavior that input select will be removed from the submission:

`select: ''`or `select: undefined`

For the sake of consistency for all native form behavior, I made a decision to make them all return an empty string when nothing is selected, checked, or inputted. It's by design and could be a bad design for example at the current example, but in order to change such behavior, it will lead to a breaking change for all existing applications. I am happy to discuss the idea return result for none checked radio button and check box (single and multiple) as well.

**Comment by kerosan** [comment]
For now I have no any idea which could be better than workaround 😑
Thx for your time🙃

**Comment by bluebill1049** [comment]
Thanks for understanding @kerosan, let's leave this issue open and have some good discussion. perhaps we can resolve this issue in the next breaking change. it's a tricky one, you want to keep it simple at the time, not with a surprise like above. we just need to find a good balance.

options are:

1. none-selected or checked: ''
2. none-selected or checked: undefined
3. none-selected or checked: null
4. none-selected or checked: remove from the submission

**Comment by bluebill1049** [comment]
hmmm think about this issue twice, this is actually a bug. eg:

`<input type="radio" name="test" value="" />` this will not make a difference whether user is selected or not...

**Comment by bluebill1049** [comment]
Thank you guys' input. I will send a PR to fix this issue.
