### ISSUE TITLE
Array Fields render thrice 6.14.2(was okay with 4.3.0)

### ISSUE THREAD

**Issue by MudulOzan** [react-hook-form/react-hook-form#3987]
**Describe the bug**
I am terribly sorry, this is probably my first issue on github and I don't know if I am explaining it well, so I wanted to use Field Array as in this example: https://codesandbox.io/s/6j1760jkjk
Well, the code was fine in the sandbox and I was confused when you remove friend in the sandbox in increases one and then I do it in my project it re-render 3 times. Then I realized that the sandbox version was 4.3.0 and I was using the latest package. I don't know if this issue known to you but it was working well on 4.3.0

**To Reproduce**

1. Click on 'Add Friend Button'
2. Watch the render count
3. Click on 'Remove Friend Button'
4. Then you will get render count as 5 instead of 3

**Codesandbox link (Required)**
Here I prepared a fork with 6.14.2
https://codesandbox.io/s/react-hook-form-array-fields-forked-60tih?file=/src/index.js
compare with: https://codesandbox.io/s/6j1760jkjk

**Expected behavior**
It should render once

**Screenshots**
-
**Desktop (please complete the following information):**

- OS: Windows 10
- Chrome
- Version 87.0.4280.141

**Smartphone (please complete the following information):**

- Not tested

**Additional context**
I am sorry I am concerning that I submit a bad thread but I hope this issue will help you to understand the problem, I can provide more information if needed.

**Comment by bluebill1049** [comment]
hey @MudulOzan I would recommend using this instead: https://react-hook-form.com/api#useFieldArray now that you are in v6.

**Comment by bluebill1049** [comment]
Let me know if you got any more questions about `useFieldArray`. I am going to close this issue.

**Comment by MudulOzan** [comment]
Thanks, in first look, I prefered to use that but I will try useFieldArray to.

**Comment by mshalabi1990** [comment]
I need help in my blockchain for moving company
