### ISSUE TITLE
watched value not update when watching a nested property and setValue all object

### ISSUE THREAD

**Issue by wanglam** [react-hook-form/react-hook-form#3989]
**Describe the bug**
I have a input name is `user.name`, and I watch `user.name` in the same component. I log the watched value every render. I call `setValue("user", {name:"foo"})` after "SET VALUE" button click.Then I click the button, but the component didn't re-render and the log "foo" not output.

**To Reproduce**

1. Go to [the codesanbox](https://codesandbox.io/s/react-hook-form-watch-v6-forked-r7cdk?file=/src/index.js)
2. Click on 'SET VALUE'
4. "foo" not output

**Codesandbox link (Required)**

- [codesandbox](https://codesandbox.io/s/react-hook-form-watch-v6-forked-r7cdk?file=/src/index.js) 

**Expected behavior**
Should output "foo" after the button click

**Screenshots**
![image](https://user-images.githubusercontent.com/4034161/105483794-551a8680-5ce5-11eb-881f-ce172cfc0343.png)

**Additional context**

react-hook-form@6.14.2 not work

react-hook-form@6.4.1  work fine

**Comment by bluebill1049** [comment]
First of all, thanks very much for report this issue.

I did think about this use case last night, instead of knowing and parse the `setValue`'s second object to find out the input path, which is not efficient for `watch` API, I would recommend using `watch('object')` instead, I will update the doc to reflect on this. 

let me know your thoughts unless there is a strong use case, otherwise, i don't think this will be fixed.

**Comment by getTobiasNielsen** [comment]
https://codesandbox.io/s/react-hook-form-watch-v6-forked-slhqt?file=/src/index.js ?

**Comment by wanglam** [comment]
Thanks @bluebill1049 . Yeah, I find a `isFieldWatched` in `useForm` function, this block the value update. I can call `setValue("user.name", "foo")`, this watch function work fine. Shall we always use the whole path(eg: user.name) instead of use root path(eg: user) to set a nested property? 

`watch("user")` work fine. But the trouble is user is a very big object, I don't want to re-render the whole component cause other property update.

**Comment by bluebill1049** [comment]
for specific field its better to `setValue('test.xxx', 'value')`.

**Comment by bluebill1049** [comment]
<img width="832" alt="Screen Shot 2021-01-23 at 7 53 02 pm" src="https://user-images.githubusercontent.com/10513364/105573875-9fb70400-5db4-11eb-8e4f-28a65c21b62f.png">

updated the doc to include the above info.
