### ISSUE TITLE
Conditional fields don't seem to be validated on submit

### ISSUE THREAD

**Issue by ldanet** [react-hook-form/react-hook-form#399]
**Describe the bug**
I made a form with two required fields: one field is always displayed, the other one is only displayed if you check the checkbox.
The second field doesn't validate on submit when it is displayed.

I thought I may have been doing something wrong but my code is pretty much the same as this example: https://github.com/react-hook-form/react-hook-form/blob/master/examples/conditionalFields.tsx
except I added validation.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-ts-validation-uwcwo
2. Click 'Submit'
3. See that `firstName` field is properly validating, displaying error and preventing submission.
4. Enter something in `firstName` input field
5. Check the "Display last name" checkbox
6. Click 'Submit'
7. The form is submitted and no error shows for the required `lastName` field

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-ts-validation-uwcwo

**Expected behavior**
When the required `lastName` field is displayed, it should prevent form submission if left empty, as well as populate the `errors` object with an error at the `lastName` key.

**Desktop (please complete the following information):**

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 77.0.3865 | OS X 10.15.0           |

**Comment by bluebill1049** [comment]
You are missing register 🤟🏻

**Comment by ldanet** [comment]
Sorry about that! 😬

**Comment by bluebill1049** [comment]
All good 🤗
