### ISSUE TITLE
Non registered fieldArray fields not in watched value with shouldUnregister: false and appending async

### ISSUE THREAD

**Issue by AlexanderMeheus** [react-hook-form/react-hook-form#3990]
**Describe the bug**
I will try my best to describe the bug here as it is a very specific one. When using shouldUnregister: false I would expect the values set by the different fieldArray methods to persist even when the fields mentioned are not registered. Now when we use the `append` method of `useFieldArray` `in a async function` and access the `formState.dirtyFields` before accessing watched values, the non registered values disappear. If this is not clear check the codesandbox.

**To Reproduce**

1. Go to the sandbox
2. Click on append
3. Notice that the last log in the console has all the values (even of unregistered fields) of the new entry.
4. Click on append async
5. Notice that the last log in the console only has the registered values for the new entry.
6. Comment out `formState.dirtyFields;` in index.js line 22.
7. Click on append async again
8. Notice that the last log in the console has all the values (even of unregistered fields) of the new entry.

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

- https://codesandbox.io/s/react-hook-form-usefieldarray-y69xq

**Expected behavior**
When `shouldUnregister: false` I expect the appended values to appear in the watched value as it does with a non async append.

**Desktop (please complete the following information):**

- OS: macOS Catalina v10.15.7
- Browser: Google Chrome Version 87.0.4280.88

**Additional context**
Using react-hook-form v6.14.2

**Comment by bluebill1049** [comment]
so with async, `watch` will call `getValues()` instead of getting what's in your argument. I will do some investigation to see if there fix we can walk around with this issue, and verify if this issue is already been addressed in V7. This is most likely to be a design limitation to v6.

**Comment by bluebill1049** [comment]
for field array, make sure you are watching the field array instead of the entire form. also, you don't need to use `useEffect` as well.

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-9f50q?file=/src/index.js
