### ISSUE TITLE
Inputs with the same name should push values into an array

### ISSUE THREAD

**Issue by jbsmith731** [react-hook-form/react-hook-form#3992]
**Is your feature request related to a problem? Please describe.**
When multiple checkbox inputs that share a common name are selected react hook form saves the value as the last item selected.

**Describe the solution you'd like**
I think inputs that share the same name should save the values into an array ex: `inputName: [value1, value2, ...]`

**Describe alternatives you've considered**
I've considered using the `onSubmit` function to store the values as comma separated items in a string.

**Additional context**
https://formik.org/docs/examples/checkboxes

**Comment by bluebill1049** [comment]
Thanks for the feature request, for current usage: use `Controller`. I will ping this on the feature board.

**Comment by enheit** [comment]
> When multiple checkbox inputs that share a common name are selected react hook form saves the value as the last item selected

I can't find a solution how to use react-hook-form v7+ with material-ui (react). 

Could you provide me a link with a description of how to use group of checkboxes?

I expect to have array of strings (e.g. `['value1`, `value2`, `value3`] whenever I check a checkbox.
