### ISSUE TITLE
Validation: field validation in MUI does not work past v5.50

### ISSUE THREAD

**Issue by darrenfurr** [react-hook-form/react-hook-form#3993]
**Describe the bug**
I'm trying to just add required field validation using v6.14.2, but the errors object is empty.

**To Reproduce**
In Material-UI with react-hook-form 6.14.2, create a TextField using Controller render & add required: true in the register:
```
<Controller
      name="atest"
      control={control}
      render={({ onChange }) => (
          <TextField
             label="atest"
             inputRef={register({
                  required: true
             })}
             error={!!errors?.atest?.message}
             helperText={errors?.atest?.message}
             onChange={onChange}
           />
      )}
 />
```

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-forked-wmicq?file=/src/index.js

I've tried v6.14.1, v6.0.0, v5.5.3. It only seems to work with v5.5.0 here:
https://codesandbox.io/s/react-hook-form-controller-forked-sopyg?file=/src/index.js
(Which is me just adding the `inputRef={register({ required: true })}`)

**Expected behavior**
I would expect the errors object to be populated on form submit or trigger

**Desktop (please complete the following information):**
- OS: macOS
- Browser: Chrome
- Version: 87.0.4280.141 (Official Build) (x86_64)

**Comment by bluebill1049** [comment]
remove that `register`, for `Controller` the registration is been taking care of.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#Controller

https://codesandbox.io/s/controller-rules-8pd7z?file=/src/App.tsx (in the doc under rules)

**Comment by darrenfurr** [comment]
Thanks for the quick response @bluebill1049.

I updated the codesandbox, but for anyone that finds this issue here's the correct syntax:

```
          <Controller
            name="atest"
            control={control}
            defaultValue=""
            rules={{ required: true }}
            render={({ onChange, ref }) => (
              <TextField
                label="atest"
                inputRef={ref}
                error={!!errors?.atest?.message}
                helperText={errors?.atest?.message}
                onChange={onChange}
              />
            )}
          />
```
