### ISSUE TITLE
Yup validation broken when using `render` prop?

### ISSUE THREAD

**Issue by chrissyast** [react-hook-form/react-hook-form#4020]
**Describe the bug**
I am trying to migrate from using the `as` prop to `render`. This seems to have broken validation as it is failing validation even when the input is valid. I am using Yup for the validation.

**To Reproduce**
https://codesandbox.io/s/happy-frost-x6z6p?file=/src/App.tsx

The above CodeSandbox has two form instances - the top one using the `as` prop (OldFormInput.tsx), the bottom one using the `render` prop (FormInput.tsx).

1. Open the link, 
2. Put your name in the top field, press the top 'submit'. See no validation, see "submitted" in the console log.
3. Put your name in the bottom field, press the bottom 'submit'. See validation message appears, no "submitted" in the console log.

**Codesandbox link (Required)**

See above

**Expected behavior**
Same behaviour in bottom field as top field.

**Screenshots**
![image](https://user-images.githubusercontent.com/31564153/105725861-5637f780-5f21-11eb-8151-b1617bdd49b4.png)

**Desktop (please complete the following information):**

Windows 10
Chrome 87.0.4280.141

**Comment by getTobiasNielsen** [comment]
I think you are mixing out your `onChanges` among other things. (`onBlur`)

https://codesandbox.io/s/cranky-glade-xmshc?file=/src/components/FormInput.tsx

**Comment by chrissyast** [comment]
@getTobiasNielsen Thanks for your reply, and for getting it working! So, looking at what you've changed, it seems like the `onChange` from the props was conflicting with the `onChange` being destructured from the render, so you gave the prop one an alias of `FormInputOnChange` to avoid the conflict?

**Comment by getTobiasNielsen** [comment]
@chrissyast Actually, you didn't have the `onChange` at all only `value` in the `render`, you'll have to take care of multiple things when you use a `Controller`. Before `as` injected most of them on it's own, this is getting removed as it is really bad design, because people aren't getting how "complicated" it is to use a a `Controller`.

When you use a `Controller`, you are being tasked with adding the render props correctly, this becomes more clear now that the `as` magic is gone.

When you use third-party UI libraries there is no telling how they are built and `Controller` is a way to wire them up. `as` did a good job, but ultimately, `as` was redundant and confuses people because they think it's more clever than it is.

I also think you misplaced the defaultValue as you are sticking it in the render, where it belongs on the `Contoller`.

You might also benefit from adding  `onBlur`, `name` on the textfield in the render.

**Comment by chrissyast** [comment]
> @chrissyast Actually, you didn't have the onChange at all only value in the render

Ah yes. I tried so many combinations I forgot which version I had on CSB 😆 I'm a bit confused in general by the two different `onChange`s and what the one destructured from the render is for.

> You might also benefit from adding onBlur, name on the textfield in the render.

`name` was already there on my CSB. Will look into `onBlur` but haven't seen any use case for it.

> I also think you misplaced the defaultValue as you are sticking it in the render, where it belongs on the Controller.

My general workflow was "bung everything that was in controller into the render" 😆 . I'm not really able to distinguish what should go in the render and which in the controller. For default value both seem to work...

**Comment by getTobiasNielsen** [comment]
Here is a few of the things I'd do.

https://codesandbox.io/s/determined-kowalevski-fe35k?file=/src/components/FormInput.tsx

- Added `shouldFocusError` and `mode` to the useForm. Read about them in the [useForm docs](https://react-hook-form.com/api#useForm).

- Also changed the destructure renaming to be easier to follow.

- Added onBlur and a proper ref (here cRef) to make the two former additions work properly.

**Comment by chrissyast** [comment]
@getTobiasNielsen What is the difference between the name in the `Controller` and the name in the `TextField` ?

**Comment by getTobiasNielsen** [comment]
Ahh, okay!

So, I get that you "could" pass the name value directly to the render inside the controller, but by doing so you bypass the internal `useController`.

Simply said, the `name` on the Controller is just passed along to the render, but before that happens, the `name` is used for a bunch of internal logic. You miss out on that logic, if you don't pass it through in this way.

In a more simple example:

```js
<Controller
  control={control}
  name="test"
  render={(
    { onChange, onBlur, value, name, ref },
    { invalid, isTouched, isDirty }
  ) => (
    <CustomCheckbox
      RandomNameField:{name} // "test" is passed here
      onBlur={onBlur}
      onChange={(e) => onChange(e.target.checked)}
      checked={value}
      inputRef={ref}
    />
  )}
/>
```

Also [`const { field, meta } = useController(props);`]( https://github.com/react-hook-form/react-hook-form/blob/0562212b9d96650eb93bd39e6a2461e54ceba87b/src/controller.tsx#L14) from the source highlights this as well.

**Comment by chrissyast** [comment]
@getTobiasNielsen Awesome, really appreciate your help! 😍

**Comment by bluebill1049** [comment]
Thank you @getTobiasNielsen 🙏
