### ISSUE TITLE
Validations not working after submit

### ISSUE THREAD

**Issue by adiazgargiulo** [react-hook-form/react-hook-form#4031]
I create a form using react-hook-form with schema validations using yum. All seems to be working fine, but i found out after doing a submit on the form, if the user tries to re send the form empty (i used the reset function to clear the form), the form is sent with empty fields...

This is the example: https://www.loom.com/share/8907fb1cf5bf4320897ff00abfadda1a

**Comment by getTobiasNielsen** [comment]
Looks like you have some sort of reset going on at the end of the submit.
Maybe [`reValidateMode`](https://react-hook-form.com/api#useForm) can help you?

With no code, it's really hard to estimate.

**Comment by adiazgargiulo** [comment]
`import React, { useState } from 'react';
import { Input as AntdInput, Typography, Row, Button } from 'antd';
import { useForm, Controller } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from 'yup';
import notification from '../molecules/notification/notification';
import { addressMinLength, ZERO } from '../../utils/constants';
import { validateHash, saveMigrationRequest } from '../../utils/api';

import ContractDetail from '../molecules/contract/contract-detail';
import {
  trackMigrationRequest,
  trackMigrationSearch
} from '../../utils/util-functions';

const schema = yup.object().shape({
  email: yup
    .string()
    .email('E-mail must be a valid address')
    .required('E-mail is required'),
  name: yup
    .string()
    .matches(/^[\sA-Za-z|]*$/, 'Name value is not correct')
    .required('Name is a required field'),
  surname: yup
    .string()
    .matches(/^[\sA-Za-z|]*$/, 'Surname value is not correct')
    .required('Surname is a required field'),
  organization: yup.string()
});

const { Title, Paragraph } = Typography;

// eslint-disable-next-line sonarjs/cognitive-complexity
const MigrateForm = () => {
  const [contracts, setContracts] = useState([]);
  const [contractAddress, setContractAddress] = useState([]);
  const [invalidAddress, setInvalidAddress] = useState(false);
  const [emptyAddress, setEmptyAddress] = useState(false);

  const { control, handleSubmit, errors, reset, getValues } = useForm({
    resolver: yupResolver(schema),
    reValidateMode: 'all'
  });

  const cleanPage = () => {
    reset();
    setContracts([]);
    setContractAddress([]);
    setInvalidAddress(false);
    setEmptyAddress(false);
  };

  const validHash = () => {
    const condition = contracts.length > ZERO;
    return condition ? true : setEmptyAddress(true);
  };

  // eslint-disable-next-line unicorn/consistent-function-scoping
  const onSubmit = async () => {
    if (!validHash()) return; // invalid form state
    try {
      trackMigrationRequest({
        email: getValues('email'),
        name: getValues('name'),
        surname: getValues('surname'),
        organization: getValues('organization'),
        contractAddresses: contracts
      });
      await saveMigrationRequest({
        email: getValues('email'),
        name: getValues('name'),
        surname: getValues('surname'),
        organization: getValues('organization'),
        contractAddresses: contracts.map(contract => contract.contractAddress)
      });
      notification({
        title: 'Request Sent',
        subtitle: 'Your request has been successfully sent',
        text:
          'Thank you for your interest. Our office will contact you soon via your provided information',
        type: 'success'
      });
      cleanPage();
    } catch (error) {
      notification({
        title: 'Request Failed',
        text: 'Your request has failed, please retry',
        type: 'error'
      });
    }
  };

  const removeItem = address => {
    setContracts(
      contracts.filter(contract => contract.contractAddress !== address)
    );
  };

  const addContract = async event => {
    if (event.key !== 'Enter') return;
    const contractExist = contracts.filter(
      contract_ => contract_.contractAddress === contractAddress
    );
    const isValid = contractExist.length === 0;
    if (!isValid) setInvalidAddress(true);
    if (contractAddress.length >= addressMinLength && isValid) {
      try {
        const data = await validateHash({ contractAddress });
        trackMigrationSearch({
          contractAddress,
          tokenName: data.name
        });
        setContracts([...contracts, data]);
        setInvalidAddress(false);
      } catch (error) {
        setInvalidAddress(true);
        trackMigrationSearch({
          contractAddress,
          tokenName: null
        });
      }
    }
    setContractAddress('');
  };

  const validateContract = async event => {
    const contract = event.target.value;
    setContractAddress(contract);
  };

  return (
    <form
      autoComplete="off"
      className="container form"
      style={{ paddingTop: '3rem', position: 'relative', minHeight: '100vh' }}
    >
      <Title level={4} className="migration-title">
        Migrate a Token
      </Title>
      <Paragraph className="migration-subtitle">
        Apply your token for a migration on Cardano blockchain network
      </Paragraph>
      <div>
        <div className="title-inputs">
          <span>E-mail</span>
        </div>
        <Controller
          as={AntdInput}
          control={control}
          className="migrate-inputs"
          placeholder="Enter your e-mail..."
          name="email"
          defaultValue=""
        />
        <div className="error-message">{errors.email?.message}</div>
      </div>
      <Row>
        <div className="row-inputs-container">
          <div className="title-inputs">
            <span>Name</span>
          </div>
          <Controller
            as={AntdInput}
            control={control}
            className="migrate-inputs-row"
            placeholder="Enter your name"
            type="text"
            name="name"
            defaultValue=""
          />
          <div className="error-message">{errors.name?.message}</div>
        </div>
        <div className="row-inputs-container">
          <div className="title-inputs">
            <span>Surname</span>
          </div>
          <Controller
            as={AntdInput}
            control={control}
            className="migrate-inputs-row"
            placeholder="Enter your surname"
            type="text"
            name="surname"
            defaultValue=""
          />
          <div className="error-message">{errors.surname?.message}</div>
        </div>
        <div className="row-inputs-container">
          <div className="title-inputs">
            <span>Organization</span>
          </div>
          <Controller
            as={AntdInput}
            control={control}
            className="migrate-inputs-row"
            placeholder="Enter your organization name"
            name="organization"
            defaultValue=""
          />
          <div className="error-message">{errors.organization?.message}</div>
        </div>
      </Row>
      <div>
        <div className="title-inputs">
          <span>Contract Hash</span>
        </div>
        <AntdInput
          className="migrate-inputs"
          placeholder="Please, paste your address and press enter"
          name="contracts"
          value={contractAddress}
          onChange={validateContract}
          onKeyUp={addContract}
          defaultValue=""
        />
        <div className="error-message">
          {invalidAddress ? 'Invalid contract' : null}
        </div>
        <div className="error-message">
          {emptyAddress ? 'You need to add at least one contract hash' : null}
        </div>
        {contracts.map((contract, key) => (
          <ContractDetail
            key={key}
            contract={contract}
            removeItem={removeItem}
          />
        ))}
      </div>
      <div className="btn-request-container">
        <Button
          className="btn-request"
          size="large"
          type="primary"
          // disabled={formHasErrors()}
          onClick={handleSubmit(onSubmit, validHash)}
        >
          Request Migration
        </Button>
      </div>
    </form>
  );
};

export default MigrateForm;
` 
i tried using reValidateMode: 'all', but the error persisted

**Comment by adiazgargiulo** [comment]
Solved it by setting the default Values of the fields inside the useForm function.

**Comment by getTobiasNielsen** [comment]
Make sure you are aware that version 7 will no longer support Controller `as`

**Comment by bluebill1049** [comment]
Thanks very much for the support @getTobiasNielsen
