### ISSUE TITLE
MUI Autocomplete does not work with controlled

### ISSUE THREAD

**Issue by vicasas** [react-hook-form/react-hook-form#4032]
**Describe the bug**

The Material-UI `Autocomplete` component does not work in the same way as the other ` TextField` components when used with RHF's `Controller`.

I am trying to make the component controlled, following the definitions in React.js and with that I came across an example of the integration in the documentation of RHF https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r?file=/src/MuiAutoComplete.js that if I take it to my code it generates the following warnings.

![image](https://user-images.githubusercontent.com/57921784/105999146-1e998e80-608c-11eb-839b-6f8f6cce6383.png)

 when adding `defaultValue=''` (as it would be done in the other cases) it generates the following warnings and errors in console.

![image](https://user-images.githubusercontent.com/57921784/105999388-628c9380-608c-11eb-81e5-33266eab36e3.png)

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r?file=/src/MuiAutoComplete.js
2. Copy example of integration componente `Autocomplete`
3. Implement example in your aplication with Material-UI 4.11.0
4. Review errors and warnings

**Codesandbox link (Required)**

https://codesandbox.io/s/integration-material-ui-autocomplete-with-react-hook-form-7dhi2?file=/src/App.js

**Expected behavior**

The expected thing is that it works in the same way as the other components such as `TextField` do since they do not generate this type of warnings or errors in the console when setting `defaultValue=''`

**Screenshots**

![image](https://user-images.githubusercontent.com/57921784/106000844-07f43700-608e-11eb-9b81-1f3fc1effc41.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome latest

**Comment by Tymek** [comment]
Maybe it's not related to react-hook-form. Code works if I use

```js
defaultValue={{ code: "PL", label: "Poland" }}
```

or try
```js
getOptionLabel={(option) => option.label || ""}
```

**Comment by vicasas** [comment]
@Tymek  If I add the first or second method, a warning still appears in the console, update the sandbox with the change and leave an image attached

Link to codesandbox: https://codesandbox.io/s/integration-material-ui-autocomplete-with-react-hook-form-7dhi2?file=/src/App.js

![image](https://user-images.githubusercontent.com/57921784/106005626-27419300-6093-11eb-92fa-56938230bdf3.png)

**Comment by Tymek** [comment]
@vicasas how about something like:
```js
getOptionSelected={(option, value) => option.code === value.code}
defaultValue={countries.find(({code}) => code === "PL")}
```

https://material-ui.com/api/autocomplete/

and pro-tip: if you paste errors as text, it's easier to Google it, and find the issue :)
For anybody who has this problem in the future:
```
Material-UI: The value provided to Autocomplete is invalid.
None of the options match with … .
You can use the `getOptionSelected` prop to customize the equality test. 
```

**Comment by getTobiasNielsen** [comment]
@vicasas 
`getOptionSelected` compares the instances of value and option by default, you'll have to overwrite it like this, if you use the `defaultValue` on the Controller.

`getOptionSelected={(option, value) => option.label === value.label}`

https://codesandbox.io/s/integration-material-ui-autocomplete-with-react-hook-form-forked-eb1g5

**Comment by getTobiasNielsen** [comment]
@Tymek Didn't see you there! Great work!

**Comment by vicasas** [comment]
I also end up working doing this

```jsx
<Controller
    control={control}
    name='test'
    render={(props) => (
      <Autocomplete
        options={countries}
        getOptionLabel={(option) => option.label || ''}
        renderOption={(option) => (
          <span>
            {countryToFlag(option.code)}
            {option.label}
          </span>
        )}
        renderInput={(params) => (
          <TextField
            {...params}
            label='Choose a country'
            variant='outlined'
          />
        )}
        onChange={(_, data) => props.onChange(data)}
      />
    )}
    defaultValue=''
 />
```

**Comment by getTobiasNielsen** [comment]
I would suggest the solution underneath for other people stumbling upon this.

https://codesandbox.io/s/integration-material-ui-autocomplete-with-react-hook-form-forked-hoiqb

**Comment by vicasas** [comment]
I will close this issue. Thank you all for the prompt help to find several alternatives to mitigate the problem.

**Comment by bluebill1049** [comment]
Thank you @getTobiasNielsen 👍

**Comment by vicasas** [comment]
I reopen the issue since I keep running into the same problems, in this case when implementing another Autocompelte in cascade the second depends on the first

**Comment by vicasas** [comment]
@bluebill1049 @getTobiasNielsen @Tymek I share a new codesandbox with the warning that continues to appear, if I select a new region and the value of the second Autocomplete does not match it generates additional warnings. Try to handle this using `setValue` but the same thing keeps happening.

https://codesandbox.io/s/integration-mui-autocomplete-whit-react-hook-form-g5335

**Comment by getTobiasNielsen** [comment]
I left `// here` where I made a change.

https://codesandbox.io/s/integration-mui-autocomplete-whit-react-hook-form-forked-1o2ke?file=/src/App.js

This is happening in part because the code needed to empty the box, and also MUI has issues comparing something to nothing.

**Comment by vicasas** [comment]
@getTobiasNielsen  I get it. With the line `getOptionSelected = {(option) => option || ""} // here`  all values ​​are pre-selected

**Comment by getTobiasNielsen** [comment]
All values?

**Comment by vicasas** [comment]
@getTobiasNielsen Here you can see that they are all marked. The same goes for the second `Autocomplete`

![image](https://user-images.githubusercontent.com/57921784/106189987-c34cc680-6187-11eb-8d13-39c3ae7306f8.png)

**Comment by getTobiasNielsen** [comment]
Alright, I see what you mean. On the other one is it more clear.

**Comment by getTobiasNielsen** [comment]
I think you just allow that warning tbh.

**Comment by bluebill1049** [comment]
We are removing all the warnings in the next major version, but it doesn't mean the default value is not essential to get it right.

`<input onChange={() => {}} />` without `defaultValue`, it's basically doing this, now with native input compontn, react will throw a warning too.

 I will take a look at your example later in the day as well. (Thanks @getTobiasNielsen's help)

**Comment by getTobiasNielsen** [comment]
The warning is from MUI.

**Comment by bluebill1049** [comment]
yes... those r MUI warnings, right?

```
Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `""`.
You can use the `getOptionSelected` prop to customize the equality test. 
    in Autocomplete (created by WithStyles(ForwardRef(Autocomplete)))
    in WithStyles(ForwardRef(Autocomplete)) (created by Controller)
    in Controller (created by App)
    in App 
```

```
Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `"Crillon"`.
You can use the `getOptionSelected` prop to customize the equality test. 
    in Autocomplete (created by WithStyles(ForwardRef(Autocomplete)))
    in WithStyles(ForwardRef(Autocomplete)) (created by Controller)
    in Controller (created by App)
    in App 
```

**Comment by getTobiasNielsen** [comment]
Yep, I solved the main issue, but the last warning isn't something that I think MUI allows for when cascading. It's also not supposed to equal anything when switching to blank in the bottom MUI component.

**Comment by vicasas** [comment]
But if it were done as a controlled component following the Material UI guidelines, this problem should not occur https://material-ui.com/components/autocomplete/#controllable-states I think it is when integrating with the RHF `Controller` component.

**Comment by getTobiasNielsen** [comment]
Didn't realize there were two states, but it changes nothing.

Here's a working example with no warnings or errors.

https://codesandbox.io/s/integration-mui-autocomplete-whit-react-hook-form-forked-l1p58?file=/src/App.js

Based on your link, I think it is more proper to use `value/onChange`. Also, setting defaultValue to `null` takes care of the eqeqeq problem.

**Comment by vicasas** [comment]
Sure that way it works from what I see. But you end up sacrificing the UI of the component since that highlighting that I mentioned earlier continues to occur.

Finally I couldn't implement this component with RHF and I had to do it with MUI's `Select` component which also throws warnings with RHF but I patch it using `setValue`.

**Comment by getTobiasNielsen** [comment]
What highlight error? It's gone, no?

**Comment by vicasas** [comment]
[Reference to comment](https://github.com/react-hook-form/react-hook-form/issues/4032#issuecomment-769328988)

**Comment by getTobiasNielsen** [comment]
Did you click the sandbox or am I blind?

https://codesandbox.io/s/integration-mui-autocomplete-whit-react-hook-form-forked-l1p58?file=/src/App.js

**Comment by bluebill1049** [comment]
closing this issue, if you got more questions feel free to follow it up here or GitHub discussion. thanks, @getTobiasNielsen's help! ❤️

**Comment by mmcgahan** [comment]
It looks like all the codesandbox links on this issue are dead - I'm seeing some similar warnings, but not sure how to get the default `===` equality check to work.

**Comment by getTobiasNielsen** [comment]
@mmcgahan I'm sorry the links died.

Are you also using Material-UI Autocomplete?

Maybe a little demo of the bug could clue me in on your issue.

**Comment by mmcgahan** [comment]
apologies for missing your response @getTobiasNielsen - I'm just going with a custom equality check for now but if I get stuck again I'll put together a minimal demo, thanks!
