### ISSUE TITLE
Support useController hook to be called "conditionally" (in a safe manner)

### ISSUE THREAD

**Issue by dwiyatci** [react-hook-form/react-hook-form#4033]
**Is your feature request related to a problem? Please describe.**
There are some (edge) cases in my code where I cannot simply use `<Controller>` wrapper component. That is why I resort to `useController` hook. As far as I notice, calling this hook means registering the field with the given `name` regardless the corresponding control will be rendered or not.

**Describe the solution you'd like**
Since [the rules of hooks](https://reactjs.org/docs/hooks-rules.html) says that we shouldn't call hooks conditionally, I'd like to be able to call `useController()` with `undefined`, `null`, `false`, or any falsy argument so that I can always call the hook without registering a field/control. Please see my hypothetical code below in the additional context.

**Describe alternatives you've considered**
As workaround, I'm currently considering: https://unsplash.com/blog/calling-react-hooks-conditionally-dynamically-using-render-props/

**Additional context**
```js
export default function App() {
  const { handleSubmit, control } = useForm();
  const onSubmit = (data) => console.log(data);

  const firstNameControllerProps = useController({ name: 'firstName', control });

  const showLastName = false;
  // currently this is not supported, code will break here
  const lastNameControllerProps = useController(showLastName && { name: 'lastName', control });

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <CustomControl {...firstNameControllerProps} />
      {showLastName && <CustomControl {...lastNameControllerProps} />}
      <input type="submit" />
    </form>
  );
}
```

**Comment by getTobiasNielsen** [comment]
You don't want to make <CustomControl> and have the useController in those, and just pass the name and control props?

**Comment by getTobiasNielsen** [comment]
https://codesandbox.io/s/vibrant-ride-7tll8?file=/src/App.js

**Comment by getTobiasNielsen** [comment]
I guess, after rereading your question, I understand what you want, but that is already done automatically if you hide the component.

**Comment by getTobiasNielsen** [comment]
What you are looking for already happens automatically:

https://codesandbox.io/s/vibrant-ride-7tll8?file=/src/CustomControl.js

Hope this helps.

**Comment by dwiyatci** [comment]
@getTobiasNielsen Thank you but unfortunately I don't have control over `<CustomControl>`. 🙂  My `<CustomControl>` there is more like a component from some UI widget library, just like the `<TextField>` in the API docs that can only accepts `value`, `onChange`, `onBlur`, and `ref`.

So I guess there's no other way than wrapping it in a wrapper component, yeah? If so, then I may well go with the workaround I mentioned.

**Comment by getTobiasNielsen** [comment]
I used `<TextField>` from @material-ui/core in my example, that doesn't work?

**Comment by bluebill1049** [comment]
I think shouldn't this be:

`{showLastName && <UseControllerBasedComponent />}`

in V7, we are removing auto `unregister`, so you will need to bake that logic inside your component conditional as well.

**Comment by dwiyatci** [comment]
@getTobiasNielsen No, your example works fine. 🙆🏻‍♂️ It's just not what I'm looking for. Sorry to mislead you with my previous comment (I cannot provide my component anyway 'cause it's a private UI component/widget from a private repo. 😬 But again, it doesn't have anything to do with my <CustomControl> or <TextField> from Material UI).

@bluebill1049 Thank you for your correction on my syntax mistake (I edited it just now 😛) and the heads-up for V7 - I hope it's gonna come with a good migration guide aswel.

So guys, what I'm actually looking for here is the possibility of improving `useController` hook such that **when it's called with no (or falsy) argument, it won't do anything / any registration at all**. Consider this adapted `useEffect` hook examples from https://reactjs.org/docs/hooks-rules.html:
```js
// 🔴 We're breaking the first rule by using a Hook in a condition
if (name) {
  useEffect(function persistForm() {
    localStorage.setItem('formData', name);
  });
}

useEffect(function persistForm() {
  // 👍 We're not breaking the first rule anymore
  if (name) {
    localStorage.setItem('formData', name);
  }
});
```

I was just thinking that maybe a similar pattern could be applied to useController hook:
```js
// 🔴 We're breaking the first rule by using a Hook in a condition
let props;
if (name) {
  props = useController({ name, control });
}

// 👍 We're not breaking the first rule anymore
// but this is currently not supported.
const props = useController(name ? { name, control } : undefined)
```

Do you think this kinda improvement makes sense or is it something that's out of scope of `useController` hook to handle?

**Comment by getTobiasNielsen** [comment]
Maybe it's better to feed a value to the controller like: 

`const props = useController({ name, control, shouldRegister: boolean });`

**Comment by bluebill1049** [comment]
honestly, I would do that at component level, rather than in the hook itself.

`{name && <ControlledInputWithUseController />}`

**Comment by bluebill1049** [comment]
@dwiyatci 100% on migration guide and documentation before we release V7.

**Comment by dwiyatci** [comment]
🆗, I guess it should be acceptable then. I was just asking about this possibility because I didn't wanna create a different wrapper component for each of my `<CustomControlA>`, `<CustomControlB>`, `<CustomControlC>`, and so on. 😁 But going with the workaround by creating one common `<RenderFunction>` (like in mentioned the link above) seems to do its job and serves as a good middle ground.

Thank you all, very much, as usual! <3

**Comment by dohomi** [comment]
I just stumbled across this issue. 
Is there an easy way to determine if a component is part of a provider? I've seen
```js
  const ctx = useFormContext()
  // ctx is null if no provider is present
  return ctx ? <ChildWithController /> : <ChildWithoutController />
``` 
I am not sure if this is a performant way. @bluebill1049 would you suggest this or is there a better way to do this?

**Comment by matinzd** [comment]
Please make this hook undefined/null safe when passing options.

**Comment by dohomi** [comment]
I created https://github.com/react-hook-form/react-hook-form/pull/5015 to solve this issue

**Comment by bluebill1049** [comment]
I have test with a potential solution but gets really ugly... so an alternative solution is to mock `control` when control is not defined, now I know this is not the best solution, but it's a way to get around this issue.


```
mockControl:  {
  register: [Function (anonymous)],
  isWatchAllRef: { current: false },
  watchFieldsRef: { current: Set(0) {} },
  getIsDirty: [Function (anonymous)],
  formStateSubjectRef: { current: Subject { observers: [] } },
  fieldArraySubjectRef: { current: Subject { observers: [] } },
  controllerSubjectRef: { current: Subject { observers: [] } },
  watchSubjectRef: { current: Subject { observers: [] } },
  watchInternal: [Function (anonymous)],
  fieldsRef: { current: {} },
  validFieldsRef: { current: {} },
  fieldsWithValidationRef: { current: {} },
  fieldArrayNamesRef: { current: Set(0) {} },
  readFormStateRef: {
    current: {
      isDirty: false,
      dirtyFields: false,
      touchedFields: false,
      isValidating: false,
      isValid: false,
      errors: false
    }
  },
  formStateRef: {
    current: {
      isDirty: false,
      isValidating: false,
      dirtyFields: {},
      isSubmitted: false,
      submitCount: 0,
      touchedFields: {},
      isSubmitting: false,
      isSubmitSuccessful: false,
      isValid: false,
      errors: {}
    }
    },
    defaultValuesRef: { current: {} },
    fieldArrayDefaultValuesRef: { current: {} },
    unregister: [Function: unregister],
    shouldUnmountUnregister: undefined
  }
```

**usage**

```
useController({
  control: control || mockControl
})
````

**Comment by PenguinDetective** [comment]
Any updates on this? I also have to call useController conditionally for an generic Input component that can be used with or without react hook form.
