### ISSUE TITLE
Cannot use 'formState' and 'control' together

### ISSUE THREAD

**Issue by giulianok** [react-hook-form/react-hook-form#4034]
**Describe the bug**
I have a component that's reused in different forms and receives 2 props, `name` and `control`. The `name` is the name of the input and `control` is the object provided by `useForm`. The component uses control to access to things like `register` and `formState`. When I use `formState` in the parent component, for example, to know if it's submitting, the value of `control.formState.errors` is an empty object. If I don't use `formState` from the parent component, then `control.formState.errors` is an object with errors (expected).

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-v6-validationschema-forked-gqqwz?file=/src/index.js
2. Click on submit
3. Form validates but the error in `first name` does not show up
4. Comment line 34 (`console.log("submitting", formState.isSubmitting);`)
5. The error in first name now appears.

**Comment by bluebill1049** [comment]
thanks for the issue report, you are not supposed to access what's inside the `control` object.

https://codesandbox.io/s/react-hook-form-v6-validationschema-forked-gqqwz?file=/src/index.js

if you need to access other methods, use `useFormContext`.

**Comment by giulianok** [comment]
What about `control.formStateRef.current`? could that be used instead? (https://codesandbox.io/s/react-hook-form-v6-validationschema-forked-gqqwz?file=/src/index.js)

**Comment by bluebill1049** [comment]
I wouldn't use anything inside the `control` object, please stick to the usage of those exposed API.
