### ISSUE TITLE
Validation doesn't work with material-ui without click submit

### ISSUE THREAD

**Issue by AlexeyMatskevich** [react-hook-form/react-hook-form#404]
When I touch the field with validation `register({ required: true})`, interactive errors are not displayed until I click the button.

**To Reproduce**
1. Touch email field ( add symbol then delete)

**Expected:**
Trigger a validation error.

**Observe:**
Validation error in not triggered

[sanbox](https://codesandbox.io/s/react-hook-form-custom-input-zn4i7)

**Desktop (please complete the following information):**
 - OS: ManjaroLinux
 - Browser Chromium       , Firefox 
 - Version  77.0.3865.120, 70.0b14

When I click submit button `SIGN UP` validation starts working as expected (just like this happens on your official website)

**Comment by bopfer** [comment]
The default `mode` is `onSubmit`.  Try changing the mode to `onChange`:

```javascript
const { register, handleSubmit, errors, formState } = useForm({ mode: `onChange`});
```

**Comment by AlexeyMatskevich** [comment]
Thank you @bopfer , I looked at the documentation for a long time and did not notice this part.

**Comment by MincePie** [comment]
I think I'm having the same issue - I'm trying to use antd front end with this form tool. As i understand it the solution is to replace:
`  const { register, handleSubmit, errors } = useForm();
`
with:
`  const { register, handleSubmit, errors } = useForm({ mode: `onChange`});
`
I'm not sure if I'm supposed to replace submit in the button with: onChange
 ```
<Form.Item>
              <Button type="secondary" htmlType="submit">
                Next
              </Button>
            </Form.Item>

```

This didn't work for me. Is it possible to use antd with react-hook-form?

If so, how do I get the errors to render?

My total form (is a multipart wizard) is below:

```
import React from "react";
import useForm from "react-hook-form";
import { BrowserRouter as Router, Route } from "react-router-dom";
import { StateMachineProvider, createStore } from "little-state-machine";
import { withRouter } from "react-router-dom";
import { useStateMachine } from "little-state-machine";

import updateAction from "./updateAction";
import { Button, Select, Form, Input,  Divider, Layout, Typography, Skeleton, Switch, Card, Icon, Avatar } from 'antd';
import HeaderBranding from '../../home/header/HeaderBranding';
import StandardFooter from '../../footer/StandardFooter';
// import List from './List';
import Options from '../../home/hero/Options';


const { Content } = Layout 
const { Text, Paragraph } = Typography;
const { Meta } = Card;
const { Option } = Select;


createStore({
  data: {}
});

const General = props => {
  const { register, handleSubmit, errors } = useForm({ mode: `onChange`});
  const { action } = useStateMachine(updateAction);
  const onSubit = data => {
    action(data);
    props.history.push("./ProposalMethod");
  };
          
          
  return (
    
      <div>
  
      <HeaderBranding />
        <Content
          style={{
            background: '#fff',
            padding: 24,
            margin: "auto",
            minHeight: 280,
            width: '70%'
          }}
        >
        <Form onSubmit={handleSubmit(onSubit)}>
          <h2>Part 1: General</h2>
            <Form.Item label="Title" >
              <Input 
                name="title" 
                placeholder="Add a title" 
                ref={register({ required: true })} 
              />
              {errors.title && 'A title is required.'}
            </Form.Item>
            <Form.Item label="Subtitle" >
              <Input 
                name="subtitle" 
                placeholder="Add a subtitle" 
                ref={register({ required: true })} 
              />
              {errors.subtitle && 'A subtitle is required.'}
            </Form.Item>
            <Form.Item label="Select">
              
                <Select mode="multiple" placeholder="Please select favourite colors">
                  <Option value="red">Red</Option>
                  <Option value="green">Green</Option>
                  <Option value="blue">Blue</Option>
                </Select>
              
              
            </Form.Item>

            <Form.Item>
              <Button type="secondary" htmlType="submit">
                Next
              </Button>
            </Form.Item>
        
        </Form>
        
        </Content>
        <StandardFooter />
      </div>  
  );
};

export default withRouter(General);

```

**Comment by bluebill1049** [comment]
@MincePie you may need to use custorm register at `useEffect` and update value with `setValue`. I don't think antd having good support over uncontrolled component just yet

**Comment by MincePie** [comment]
@bluebill1049 - thanks - do you have any idea how I would go about doing that? I struggle to understand the concepts from the level of detail in the docs

**Comment by bluebill1049** [comment]
no worries @MincePie 

react hook form is lean towards uncontrolled component, and register input's ref into the hook. it also the custom hook to easily get data and validate them. so it should all work perfectly. you can read about uncontrolled components from react doc.

however, for antd and MUI, they r not supporting uncontrolled components just yet(which i hope they will), they do not expose `ref` fo react hook form or your component to consume, so the solution will be using custom register.

you can read more here: https://react-hook-form.com/api#register

example:
```
useEffect(() => {
  register({ name: 'test' }, { required: true });
}, [register]) 

<Input name="test" onChange={e => setValue('test', e.target.value)} />
```

hope these make sense.
