### ISSUE TITLE
Problem with rerender component so many when change state

### ISSUE THREAD

**Issue by ninhtq97** [react-hook-form/react-hook-form#4040]
Hi. I have problem with rerender component on version 6

On version 5 not using spread still rerender one time.

**Describe the bug**
When next or previous page change `data` state then component rerender so many time.

**Expected behavior**
Rerender one time

Example:
https://codesandbox.io/s/heuristic-meitner-mxl3u?file=/src/App.tsx

If using spread data or change file but not reload browser then rerender one time

Not using spead:
![image](https://user-images.githubusercontent.com/33461757/106122804-b3cf7c80-618b-11eb-9907-adcb5f0af6e5.png)

Using spead:
![image](https://user-images.githubusercontent.com/33461757/106122716-97334480-618b-11eb-9cfa-949fd0db601a.png)

**Comment by bluebill1049** [comment]
honestly, i am not sure what you try to do in the CSB above. looks like you want to do a Field Array. 

you may want to have a read on this section: https://react-hook-form.com/api#useFieldArray

**Comment by ninhtq97** [comment]
> honestly, i am not sure what you try to do in the CSB above. looks like you want to do a Field Array.
> 
> you may want to have a read on this section: https://react-hook-form.com/api#useFieldArray

I was update issue. pls review it.

**Comment by bluebill1049** [comment]
still not clear what you try to achieve and the bug here, is it just the render count? none of the input boxes can interact as well.

**Comment by bluebill1049** [comment]
```
<input
          type="text"
          key={e.id}
          name={`ipt-${e.id}`}
          ref={register}
          value={e.name}
          onChange={() => {}}
        />
        ```
        
        also very stange usage, mixed with controlled and uncontrolled.

**Comment by ninhtq97** [comment]
> ```
> <input
>           type="text"
>           key={e.id}
>           name={`ipt-${e.id}`}
>           ref={register}
>           value={e.name}
>           onChange={() => {}}
>         />
> ```
> 
> also, very strange usage, mixed with controlled and uncontrolled. I suggest you pick one, either control or uncontrolled.
