### ISSUE TITLE
Make setValue with an object fill checkbox group

### ISSUE THREAD

**Issue by jcognard-actinvision** [react-hook-form/react-hook-form#4048]
I have a checkbox group with names like `framework[react]` and using `setValue('framework', { react: true })` doesn’t work.
I have to manually loop on the object keys to do `setValue('framework[react]', true)`.

See my CodeSandbox example: https://codesandbox.io/s/romantic-ardinghelli-mwffs?file=/src/App.js

**Comment by bluebill1049** [comment]
It's an object: https://codesandbox.io/s/nervous-hellman-cb685

**Comment by jcognard-actinvision** [comment]
Thank you @bluebill1049 it works with dot notation names.
