### ISSUE TITLE
[Question] How to make a conditional input without a ref validate only when displayed?

### ISSUE THREAD

**Issue by ldanet** [react-hook-form/react-hook-form#405]
Hi, it's me again 👋 

I have a form where I'm using an input from a library that only exposes a few props, including an `onChange` prop which gives me an object I use for validation. I don't have access to a meaningful ref or much else.
The issue arises when the field is displayed then hidden, the validation shouldn't happen anymore but it still does.

I tried to recreate something similar on Codesandbox that reproduces the same behaviour: https://codesandbox.io/s/react-hook-form-ts-conditional-controlled-field-validation-4dpoj

Using only 'register', the field never seems to get *un*-registered, and the validation errors remain even when the field is unmounted.

I tried to manually `unregister` when the field unmounts, that clears the error, but it won't validate nor submit when the field is displayed: https://codesandbox.io/s/react-hook-form-ts-conditional-controlled-field-validation-unregister-2hfyt

Is there a correct way to make this work?

**Comment by bluebill1049** [comment]
hey @ldanet,

why not bake `unregister` into your custom field? during `useEffect` return? so it will get unregistered automatically when removed from the render tree.

**Comment by ldanet** [comment]
Thank's for the spectrum link! 
Let's continue there. https://spectrum.chat/react-hook-form/help/how-to-make-a-conditional-input-without-a-ref-validate-only-when-displayed~c4638626-8472-45c4-ab64-2d55bfe9a180

**Comment by bluebill1049** [comment]
yea sure.

**Comment by bluebill1049** [comment]
Here is what I meant: https://codesandbox.io/s/react-hook-fom-unregister-controlled-component-hu990

I will write another section under advance page on the website soon, so more developers can just read from there and solve the problem.

**Comment by bluebill1049** [comment]
we resolved the issue :) closing

**Comment by bluebill1049** [comment]
FYI: updated the website too 
https://react-hook-form.com/advanced-usage#ConditionalControlledComponent
