### ISSUE TITLE
react-hook-form can't correctly validation with value and onChange after submit

### ISSUE THREAD

**Issue by major697** [react-hook-form/react-hook-form#4053]
I have component:
```
    const FormComponent = () => {
      const { register, handleSubmit, errors } = useForm();
    
      const [val, setVal] = useState("");
    
      const handleSubmitForm = () => console.log("send!");
    
      const handleChange = (e) => {
        setVal(e.target.value);
      };
    
      return (
        <form onSubmit={handleSubmit(handleSubmitForm)}>
          <input
            type="text"
            name="test"
            value={val}
            ref={register({ required: "The field is required." })}
            onChange={handleChange}
          />
          {errors.test && errors.test.message}
          <button type="submit">Send</button>
        </form>
      );
    };

```
When I click "Submit", `react-hook-form` show me error message: 'The field is required.
'. And when I want write word "TEST" and I click first letter from this word (letter T) then only disapear error message, but letter 'T' is not added to input value. But when I second time click letter T the I can see inside input value letter T.

How I can use `react-hook-form` with `value` and `onChange` event?

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by wdfinch** [comment]
Don't use setVal. useForm() holds all the form values and you should not manage it yourself in this fashion. If you want to get the form values out, use watch or getValues().
