### ISSUE TITLE
V7 alpha getValues() not returning default values

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4054]
**Describe the bug**
In V7 `getValues()` is supposed to return the default values before the component mounts. However, it appears that the V6 behavior of waiting until the input component mounts before loading the values is still occurring. I'm not sure if this is a bug or just hasn't been implemented yet. 

**To Reproduce**
Simply view the output of `getValues()` in the console. 

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-template-forked-8kfzt?file=/src/index.js

**Comment by bluebill1049** [comment]
```
defaultValues: {
      name: "test"
}
```

missing **s**

**Comment by wdfinch** [comment]
Thanks. Sorry, I should've seen that one.
