### ISSUE TITLE
shouldFocusError does not exist in type 'Partial<{....

### ISSUE THREAD

**Issue by CRGavrila** [react-hook-form/react-hook-form#4063]
**Describe the bug**
Hy, i'm using v6.14.2 and I get 'shouldFocusError does not exist in type 'Partial<{....' when I add shouldFocusError: false to useForm

**To Reproduce**

const { handleSubmit, register, errors, getValues, setValue, watch, control } = useForm<any>({
    defaultValues: {},
    shouldFocusError: false
  })

**Codesandbox link (Required)**
No need is simple type error

**Expected behavior**
useForm should have a shouldFocusError  type

Thanks!

**Comment by bluebill1049** [comment]
please follow the template: https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by Mendoza920** [comment]
Elaborate
