### ISSUE TITLE
Is there a way to support IE 10

### ISSUE THREAD

**Issue by shxinlei** [react-hook-form/react-hook-form#4065]
IE 10 Error  “MutationObserver” undefined

I really, really want to be able to support IE 10

The product is driving me crazy

Because I've been driven crazy by IE 10

**Comment by getTobiasNielsen** [comment]
MutationObserver was added to IE 11.

If you use anything prior to IE 11, you will not have that method hence it is undefined.

IE 10 isn't being supported by MS anymore, it is an inherent risk to use it, for users, and the company.

Similar, MS IE11 support will end this year, and will also not be supported in future versions of RHF.

[MS goodbye letter](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/the-perils-of-using-internet-explorer-as-your-default-browser/ba-p/331732?OCID=AID681541_aff_7795_1243925&epi=je6NUbpObpQ-1.xUKfKnB3w_tVDlJh.vaw&irclickid=_ijg0gyue0gkfrnuv0c1gdjgco32xml2xjak11l0h00&irgwc=1&ranEAID=je6NUbpObpQ&ranMID=43674&ranSiteID=je6NUbpObpQ-1.xUKfKnB3w_tVDlJh.vaw&tduid=(ir__ijg0gyue0gkfrnuv0c1gdjgco32xml2xjak11l0h00)(7795)(1243925)(je6NUbpObpQ-1.xUKfKnB3w_tVDlJh.vaw)())

That being said, these are two different issues.

https://github.com/react-hook-form/react-hook-form/issues/545

Here was a moment when it was considered to remove it. I'm not sure it is correct at all, that there would be a performance increase using react vs an interface that is build directly into the browser.

In fact, I'd bet future versions of react might use `MutationObserver`, meaning that react itself, might be a problem in a project trying to support IE10. I'm unsure if they did some facebook magic to make it work faster than the API, but it just seems unlikely to think one way or the other without asking someone, who knows. But as a general rule, browser API's I'd think are faster than Javascript code.

**Comment by shxinlei** [comment]
Thank you very much for your answer ， 
I found a MutationObserver package that introduced the React portal，
The problem of useFormContext is not completely solved, but useFrom is ready to use，
While some of the issues are still a pain in the neck, our company is eager to support IE 10

package link:
https://github.com/megawac/MutationObserver.js

**Comment by getTobiasNielsen** [comment]
Brilliant.

**Comment by bluebill1049** [comment]
thanks @getTobiasNielsen :hear
