### ISSUE TITLE
Allow control over when two values are equal (for dirty checking and to possibly prevent rerenders)

### ISSUE THREAD

**Issue by nunocastromartins** [react-hook-form/react-hook-form#4066]
**Is your feature request related to a problem? Please describe.**

RHF seems to currently use strict equality (`===`) to check whether values are equal to their default value when checking for dirty fields.

The date component that I'm using produces JavaScript dates (`Date` objects): these are the values seen by RHF. However, when changing the date to the "same" date (i.e. to a new date object which represents the same date), RHF marks the field as dirty because the identity of the object changes.

This is just my use case, but in practice it can happen whenever RHF deals with non-primitive values.

**Describe the solution you'd like**

When registering, it would be nice to be able to provide an `equals` function. The default behaviour would stay the same (strict equality with `===`).

This would allow me to pass something like: `equals: (date1, date2) => date1.toISOString() === date2.toISOString()`.

RHF could also use this function to prevent unnecessary rerenders, for example with `watch` (i.e. a `watch` would only cause a rerender if the value changed according to its `equals` function). This means that, if wanted, I could implement things like deep equality of arrays/objects and other data structures being used to improve performance in certain scenarios.

**Describe alternatives you've considered**

For my particular use-case, there are some alternatives that I could implement such as making my component produce strings instead of dates (although dates makes it cleaner to use `yup` together with `yup.date`) or even manually detect that two dates are the same and ignore the dirty field when so.

However, I still believe that this should be implemented to make RHF generic over any data type.

**Comment by bluebill1049** [comment]
An interesting one, do you have a csb to demonstrate this problem?

**Comment by nunocastromartins** [comment]
Here you go, just made one: https://codesandbox.io/s/react-hook-form-js-forked-0bksj?file=/src/App.js

I created a simple `DateField` that uses RHF with JavaScript `Date`s. To reproduce the issue with this simple component you can do the following: change the start date's initial date (`2020-01-01`) to a different date (e.g. `2020-01-02`) and then change it again to the initial date (`2020-01-01`). The form will continue to be dirty (and the `reset` button will not be disabled).

Again, this is just a simple reproduction and it would be possible to work around it in multiple ways. However, I still think that the cleanest solution should come from RHF's side by allowing the definition of an `equals` function as I've commented in `DateField.js`.

Another use-case would be with a component that represent lists or sets of values (e.g. a multiple select); it would allow us to define equality between lists or sets as we see fit.

**Comment by bluebill1049** [comment]
Thanks for the CSB and detailed description. I will move this into the project board.
