### ISSUE TITLE
field array unintentionally initialized or throw a exception

### ISSUE THREAD

**Issue by Beingbook** [react-hook-form/react-hook-form#4070]
**Describe the bug**
field arrays are suddenly cleared or throws an error with basic usage.

**To Reproduce**
**Codesandbox link (Required)**

you can reproduce [here](https://codesandbox.io/s/stoic-ives-id75s?file=/src/App.js)

Unexpected initialization

1. Click `Delete` of test3
2. Click `Add`
3. Click `Delete` of test3
4. all items are suddenly cleared

Unexpected exception

1. Click `Delete` of test1
2. Click `Add`
3. Click `Delete` of test2
4. `Cannot read property 'name' of undefined` Error throwed

**Expected behavior**
field array should be consistent and not throw an error.

**Desktop (please complete the following information):**

- OS: OSX 11.1
- Browser: Chrome 88

**Smartphone (please complete the following information):**

- not tried

I don't think I used here some edge cases usage and couldn't find some specific caveats.

**Comment by bluebill1049** [comment]
is it due to `ref={register()}`? v7 we are making this API consistent, so should avoid this problem.

**Comment by Beingbook** [comment]
@bluebill1049 // Thank you for investigation.

**Comment by bluebill1049** [comment]
no worries @Beingbook make sure you check out v7's usefieldarray, it's a lot better in terms perf, design decision and etc.
