### ISSUE TITLE
V7 watch in onChange mode not working

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4078]
**Describe the bug**
It seems like when the validation mode is set to `onChange` or `all`, `watch` will not subscribe to the form state and output the new values.

**To Reproduce**
Notice that as you type in the input field, `watch` does not output anything. 

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-template-forked-fxsgr?file=/src/index.js:361-365

**Comment by bluebill1049** [comment]
thx patched.
