### ISSUE TITLE
Use Joi for schema validation

### ISSUE THREAD

**Issue by mlarcher** [react-hook-form/react-hook-form#408]
Would it be possible to somehow allow the use of Joi as a validationSchema ? 
Right now it seems to me that only Yup is supported :-/
Why not offer a hook to provide a validation function that would receive the raw data and be expected to return a given format to react-hook-form, using any validation tool it wants ?
What do you think ?

**Comment by bluebill1049** [comment]
@mlarcher it is on the roadmap https://github.com/react-hook-form/react-hook-form/projects/1 I just haven't got time to work on it just yet.

**Comment by bluebill1049** [comment]
> Why not offer a hook to provide a validation function that would receive the raw data and be expected to return a given format to react-hook-form, using any validation tool it wants ?
> What do you think ?

that's a good idea, but I do afraid this will lead developers to write more code and config. but i am happy to do a quick investigation on it and that probably will be rolling into v4 because its a breaking change.

**Comment by mlarcher** [comment]
That's great news @bluebill1049 🙂
Any ETA on the matter ?

**Comment by bluebill1049** [comment]
I hope I can deliver it next month :)

**Comment by JeromeDeLeon** [comment]
I have been cracking this on my mind since I read the `Joi` feature on the roadmap. I've seen libraries using `Yup` or only one validator but its limiting the power of `validationSchema`. Would be better if we provided an interface for any validation adapter.

**Comment by bluebill1049** [comment]
yes I totally agree @JeromeDeLeon , you probably need other validation libraries to work with us as well. At the moment, I think we are in a position to make it work for them instead of the other way around. However, we probably can figure out something generic, but it's probably not a small task and need good planning.

**Comment by bluebill1049** [comment]
closing this issue now, we will release Joi validation schema support in the future release

**Comment by bluebill1049** [comment]
@mlarcher FYI custom validation schema is working in progress: https://github.com/react-hook-form/react-hook-form/pull/529
