### ISSUE TITLE
V7 Resolver context is not being passed to Joi validation

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4080]
**Describe the bug**
If the joi validation library is used and the user passes in some custom context, then the context is not passed into joi. It is just displayed as null.

**To Reproduce**
Observe that when I call `scehma.validate` manually with context, I get the values. When I pass the context via `useForm`, I get null.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-template-forked-svn2f?file=/src/index.js

**Comment by bluebill1049** [comment]
we don't pass context into schema's context, rather the second argument of the resolver function.

**Comment by bluebill1049** [comment]
<img width="1322" alt="Screen Shot 2021-02-02 at 11 48 42 am" src="https://user-images.githubusercontent.com/10513364/106536459-9cf2a680-654c-11eb-85f2-a8ffae4e225d.png">

**Comment by wdfinch** [comment]
Oh my bad. Could you post an example of how to do this. I tried something like:

`resolver: (vales, context) => schema.validate(values, {context: context}),`

but I get a type error. How would I use the joiResolver and pass in the context?

**Comment by bluebill1049** [comment]
not an expert on joi, but you should be able to console.log the context and see that we have pass it down.

**Comment by wdfinch** [comment]
Ok I think I got this. You would do this:

 resolver: (values, context, options) => {
      const resolver = joiResolver<FormValues>(schema, {context: context})
      return resolver(values, context, options)
    }

It might be good to add an example of this to the docs. It's a little tricky with the factory function and type checking.

**Comment by jorisre** [comment]
@wdfinch That's a Joi resolver issue, we don't pass the context to Joi. I'll open a PR to fix it. Thanks for reporting
