### ISSUE TITLE
FormProvider custom props

### ISSUE THREAD

**Issue by NextNebula** [react-hook-form/react-hook-form#4083]
**Is your feature request related to a problem? Please describe.**
I am trying to migrate a project from V5 to V6, but the the typescript typings limit the way we used react hook forms before. We were able to add custom props to the FormContext (now renamed to FormProvider) and get those with useFormContext. Sadly, I think because of stricter typings, this is not possibly any more.

```
<FormProvider {...methods} fields={fields}></FormProvider>

const { formState, fields } = useFormContext();
```

**Describe the solution you'd like**
I would like to know if this was unsupported behaviour in V5 and I should rewrite this usage or if the typings are to strict now.

**Comment by bluebill1049** [comment]
Hey @NextNebula thanks for the feature request, I think we have fixed the type on v6 with context, if you need custom props, I would be recommended you build your own context.

**Comment by NextNebula** [comment]
Yeah creating our own context instead of mixing it with the form context is probably cleaner code anyway. Thank you!

**Comment by bluebill1049** [comment]
Thanks for understanding @NextNebula 🙉
