### ISSUE TITLE
Bug - V7 field arrays do not update item value

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4086]
**Describe the bug**
I'm not sure if this a bug or just hasn't been updated from V6. It seems that the `item` element provided by `fields.map` does not update its values. 

So the issue is if I have a field array  element and it's unmounted, and remounted later, I would expect to see the value that was previously there given that we don't automatically unregister inputs in V7. While form values do hold the correct state even after the unmount, the field array will be set to the wrong value via the default value prop the docs recommend we add to the element. This is because `item` never is updated when the input changes.

**To Reproduce**

1. Go to the sanbox
2. Change the input on the field array element
3. Click the toggle button to unmount the input
4. Remount the input and notice that the original default value is present in the input rather than what you just entered

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-template-forked-7twbb?file=/src/index.js:782-786

**Expected behavior**
On remount, I expect that all field array elements will hold the values that are stored in `formValues`

**Comment by bluebill1049** [comment]
Hook form useFieldArray is uncontrolled, if you want to do conditional inputs, you will have to use `useWatch` or `watch`:

https://codesandbox.io/s/react-hook-form-controller-template-forked-qxomn?file=/src/index.js

**Comment by wdfinch** [comment]
I see. Ya, I was thinking of just using the form values for that default value, but I wanted to ask first since the docs recommend using the `item` passed by fields map.

Is there a reason why `useFieldArray` is uncontrolled? Is it just for performance? Sorta like how `useForm` has the `mode` options to control when we validate, maybe we could add an option to `useFieldArray` to make it controlled? I feel like for most use cases the benefit of `item` being in sync with form values would out weight the performance gains unless you had a ton of items to display.

**Comment by bluebill1049** [comment]
I think that's the direction of hook form going with what you suggested above. :)

**Comment by wdfinch** [comment]
Ok so you would recommend using watch to get the default value and just use item for the id (for the key prop)?

**Comment by bluebill1049** [comment]
- conditional field which related to the form level `useWatch`
- use CSS or build a simple component to toggle the visiblity

**Comment by wdfinch** [comment]
Ok. I personally think it would be nice if `item` could be controlled and stay in sync, so we didn't need to use `useWatch` to do this, but it's ok if we don't. 

I'm not really a huge fan of hiding things with css and I think it's cleaner and more react like to just mount and unmount stuff. Feels wrong to use the `display: none` stuff.

**Comment by bluebill1049** [comment]
another way to get around with this issue: https://codesandbox.io/s/react-hook-form-usefieldarray-forked-32d60
