### ISSUE TITLE
useWatch vs watch with dynamic rendering

### ISSUE THREAD

**Issue by dbousamra** [react-hook-form/react-hook-form#4087]
**Describe the bug**
I am using `useWatch` to render out some content based on form state. I noticed when I render dynamically, the watched value gets reset.

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

https://codesandbox.io/s/react-hook-form-fieldsarray-yup-validation-min-length-forked-4p7fs?file=/src/index.js

Notice the `useWatch` doesnt show the updated value correctly in component `A`, yet `watch` does in component `B`? I am sure I am misunderstanding something.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dbousamra** [comment]
It appears I can combine `useWatch` with `getValues`:

```const values = useWatch({ name: 'a', defaultValue: getValues('a') });
```

**Comment by bluebill1049** [comment]
hey @dbousamra is it working with the latest patch? https://codesandbox.io/s/react-hook-form-fieldsarray-yup-validation-min-length-forked-gkklo?file=/src/index.js

**Comment by dbousamra** [comment]
Nope!

You can see the issue yeah?

**Comment by bluebill1049** [comment]
> Nope!
> 
> You can see the issue I am talking about yeah?

No, I don't.

> Notice the useWatch doesnt show the updated value correctly in component A, yet watch does in component B? I am sure I am misunderstanding something.

can you elaborate on the above steps? or even share a video.

**Comment by dbousamra** [comment]
Are you on discord atm. Might be easiest if I share my screen. Alternatively I can paste a gif

**Comment by dbousamra** [comment]
![react-hook-form](https://user-images.githubusercontent.com/648137/106581242-63db2600-658e-11eb-9b65-b13b8fe357cf.gif)

**Comment by bluebill1049** [comment]
oh thanks for the gif, because when `useWatch` mount it will always fall back to defaultValue, `watch` is "mounted" when useForm is initialized, so if you want to have the correct value, getValues reading is actually the correct approach.

**Comment by dbousamra** [comment]
Right okay. I have to do more reading. So I can safely combine `useWatch` and `getValues` as I did above?

**Comment by bluebill1049** [comment]
you can pass down a `defaultValue` `prop` for `useWatch` as well.

**Comment by dbousamra** [comment]
Thanks for your help!

**Comment by bluebill1049** [comment]
np, mate.
