### ISSUE TITLE
Add isDisabled form flag to formState.

### ISSUE THREAD

**Issue by paslo22** [react-hook-form/react-hook-form#4098]
**Is your feature request related to a problem? Please describe.**
I'm working on a couple of forms and I have a use case that a user with read-only permissions can access them and see the values but it's not able to change any of them.
Right now, what I'm doing is checking the user permission and after that I'm passing a prop to every field to tell them `disabled={!isUserAdmin}` and it's a little bit annoying.

**Describe the solution you'd like**
I was thinking in a `formState.isDisabled` field that can be toggled using some kind of `setDisabled` method or something on those lines.
I was also thinking that you already have the input's refs so it can even pass it to its fields. But that it's just an afterthought.

**Comment by bluebill1049** [comment]
isn't this easier to be managed with a `useState`?

**Comment by paslo22** [comment]
My solution uses a `useState` already but this feature request is because I believe it's going to be useful to store this `disabled` state as a "form state".

With something like that, I wont need to pass down the `disabled={!isUserAdmin}` on any field, I can just read it inside the component from `formState.isDisabled` and act accordingly.

**Comment by bluebill1049** [comment]
ok, will move into the pending feature log and see if anyone has a similar request.

**Comment by awdyson** [comment]
@bluebill1049 I added my thumbs up.
Is there a better channel for us to show support for requests?
I only ask because I had to sift through quite a few "why won't my disabled value show up" issues 😅

For a case study, I'm working on a product that is introducing permissions.
As such, we have a need to mark entire forms disabled/readonly.
I'd love to be able to control something like that from the same level as `defaultValues`, etc.
```tsx
// MUI's TextField hooked into your controller

const CTextField = forwardRef<HTMLDivElement, CTextFieldProps>(
  ({ children, error, helperText, name, required, rules, ...rest }, ref) => {
    const { formState } = useFormContext();
    const { errors } = formState;
    const { field } = useController({ name, rules });
    const { ref: inputRef, value, ...fieldProps } = field;

    // Having access to formState makes error handling super convenient
    const rhfError = get(errors, name);

    return (
      <TextField
        {...fieldProps}
        {...rest}
        disabled={...} // <----- I'd love to hook into a global or per-input disabled state, similar to rhfError
        error={error !== undefined ? error : !!rhfError}
        helperText={helperText !== undefined ? helperText : rhfError?.message || ' '}
        inputRef={inputRef}
        ref={ref}
        required={required || !!rules?.required}
        value={value || (rest.SelectProps?.multiple ? [] : '')}
      >
        {children}
      </TextField>
    );
  },
);
```
