### ISSUE TITLE
TS: SubmitHandler event argument type

### ISSUE THREAD

**Issue by antoinerousseau** [react-hook-form/react-hook-form#4099]
**Describe the bug**

I'm using the second argument of the `SubmitHandler`, which is the form submit `event`, to easily create a `FormData`.
It works well, but TS complains that the event might be _undefined_, which is weird to me: could it really be undefined? How?

**To Reproduce**

In a submit handler, try using the second argument with TypeScript in strict mode.

**Codesandbox link (Required)**
https://codesandbox.io/s/rhf-ts-nq1c6?file=/src/App.tsx

**Expected behavior**
`event` should not be optional in TS typings. And it should even be a `FormEvent<HTMLFormElement>`.

**Additional context**
Using react-hook-form 6.14.2.

**Comment by getTobiasNielsen** [comment]
The warning tells you that it "possibly" could be undefined, you can check if it is before running that line of code, or add non-null assertion operator `!`.

https://codesandbox.io/s/rhf-ts-forked-m9ll6

https://codesandbox.io/s/rhf-ts-forked-pe49f

**Comment by antoinerousseau** [comment]
@getTobiasNielsen I'm well aware of these solutions, and I'm well aware of what the warning means, since I wrote it in this issue's description, but I'm opening this issue to suggest fixing the type, because it seems to me that the event is always defined, so I shouldn't have to add a `!` or `?`.

Also, I don't like the tone of your answer.

**Comment by bluebill1049** [comment]
not in React Native @aaronjensen

**Comment by getTobiasNielsen** [comment]
I guess, I didn't fully understand the curious inquiry, you had.

I can see how that could be annoying.

But are you sure you couldn't type for `Synthetic Touch Events` / `PressEvent`, @bluebill1049 ?

**Comment by bluebill1049** [comment]
@getTobiasNielsen you can do this as well `handleSubnit()()`

**Comment by getTobiasNielsen** [comment]
I was just thinking if there was a type that actually exists it would be smart to include it, to avoid people checking the event, or asserting it, right?

**Comment by bluebill1049** [comment]
yeah @getTobiasNielsen especially for RN users.

**Comment by getTobiasNielsen** [comment]
But also to avoid web developers having to add assertions.

From this https://github.com/facebook/react-native/blob/4d247fe058e3cefd557a166717a753683754f1c4/Libraries/Types/CoreEventTypes.js

It looks like there are `SyntheticEvent`s and `ResponderSyntheticEvent`s.

**Comment by antoinerousseau** [comment]
Fyi I built a `<Form>` wrapper like this (simplified here):

```tsx
import { PropsWithChildren, FormEvent } from "react"
import { useForm, FormProvider } from "react-hook-form"

interface FormProps<T> extends Omit<FormHTMLAttributes<HTMLFormElement>, "onSubmit"> {
  onSubmit: (data: UnpackNestedValue<T>, target: HTMLFormElement) => any | Promise<any>
}

export function Form<T>({ onSubmit, ...delegated }: FormProps<T>) {
  const form = useForm<T>()

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    try {
      await form.handleSubmit((data) => onSubmit(data, event.target as HTMLFormElement))(event)
    } catch (error) {
      //...
    }
  }

  return (
    <FormProvider {...form}>
      <form method="POST" onSubmit={handleSubmit} {...delegated} />
    </FormProvider>
  )
}
```

Not sure why `event.currentTarget` is null but anyway it works like a charm.

Now in my submit handler I can either access the `data` as usual with the first argument, or create a `FormData` with the second argument:

```tsx
const handleSubmit = async (data, target) => {
  const data = new FormData(target)
  //...
}

return (
  <Form onSubmit={handleSubmit}>
    <input name="test" />
    <input type="file" name="file" />
  </Form>
)
```
