### ISSUE TITLE
Implement Batch feature to perform multiple imperative operations

### ISSUE THREAD

**Issue by santino** [react-hook-form/react-hook-form#4104]
**Is your feature request related to a problem? Please describe.**
Not really a problem but genuinely a new feature that would improve performance.
Today any imperative operation that I might want to execute on a field (such as `reset`, `setError`, `setValue` etc.) is dispatched individually.
This means that every time I invoke an operation like those any listener (like `watch` or `getValues` f.i.) would be triggered, and so will the `formState`; since this might change given the new values/state that I'm setting on individual fields.

Updating multiple fields as a result of a single user interaction is very likely; especially when working with conditional fields.
Ultimately this behaviour would cause multiple re-renders, one for every field that is updated on every component that either uses `formState`, `watch` or `getValues`.

**Describe the solution you'd like**
I would like Hook Form to expose a new `batch` method. This could take a function that wraps multiple operations.
Ultimately `batch` will execute all those operations and only once they're all complete will notify listeners and update `formState`.

This is how the signature could look like:
```js
const { batch, setValue } = useForm();

handleConditionalFieldChange = () => {
  batch(() => {
    setValue('field1', 'newField1Value')
    setValue('field2', 'newField2Value')
    setValue('field3, 'newField3Value')
  })
}
```

**Comment by santino** [comment]
This is probably no longer necessary.
React 18 is introducing [Automatic batching](https://github.com/reactwg/react-18/discussions/21), which should take care of this.

**Comment by bluebill1049** [comment]
Correct 👍  @santino

**Comment by Moshyfawn** [comment]
React 18 rules in terms of performance! :P
I'm already Suspending my forms whilst my form data is being loaded from BE, so that I don't need to `reset` the form values after the data comes in!

**Comment by santino** [comment]
That sounds good.

However, you can probably take it a step further and suspend only fields that are depending on data, rather than the entire form.
So you can have users interacting with any field that doesn't have a dependency on back-end response as soon as your form is rendered, then at a second stage un-suspend fields once they get relevant data from back-end.

Anyway, OT, but yes, moving from blocking-rendering to concurrent-rendering is a game-changer.
