### ISSUE TITLE
V7 Bug - setValue doesn't work with Object

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4108]
**Describe the bug**
If `setValue` is used and the value being set is an object, then it appears that the `value` property of the `field` argument passed to the `<Controller/>` `render` is not set. It appears that value is properly being set in form values, so the problem seems that `formValues` is not sending the value over to the `field` prop. 

**To Reproduce**

1. Go to the sandbox below
2. Observe that `watch` shows the value being stored in `formValues`
3. Observe that despite this, `field.value` is `null`

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-template-forked-0msci?file=/src/index.js:1029-1033

**Expected behavior**
`setValue` should work with objects as it did in V6

**Comment by bluebill1049** [comment]
The latest alpha version should fix it.

**Comment by bluebill1049** [comment]
shall we close this one as well? (if it's working now)

**Comment by wdfinch** [comment]
Sounds good, I'll reopen if I find some issues. Appreciate the help here.
