### ISSUE TITLE
Performance Feature: Opt out of isValidating flag on formState 

### ISSUE THREAD

**Issue by rosemariesadler** [react-hook-form/react-hook-form#4109]
**Is your feature request related to a problem? Please describe.**
It is noted in the api docs for `useForm` that there are performance problems with validating onChange. From what I can tell, isolating `formState.isValidating` and the `watch` method out of the context reuslts in fewer re-renders because the context only updates if `isValid` or `errors` change. (It confuses me a little bit that running validation results in a new `watch` method - it's memory stable most of the rest of the time.)

**Describe the solution you'd like**
I would love to be able to opt-out of these two pieces being part of the context.

**Describe alternatives you've considered**
We're currently creating a custom context that just removes those two unwanted pieces of `useForm` and passes that value down. We then use our custom context instead of the provided `useFormContext`. If there is already a workaround that is the desired solution, maybe adding it into the docs as a good solution to performance problems in the Advanced section could be useful?

**Additional context**
Code Snippet for our custom context:
```js
const FormMethods = createContext({})
export function useFormContext() {
  return useContext(FormMethods)
}
export function CustomFormProvider({ children, ...useFormProps }) {
  // can't pull out with the rest operator because it creates a new object every time so it won't be memory stable
  const {
    handleSubmit,
    setValue,
    register,
    control,
    clearErrors,
    getValues,
    reset,
    setError,
    trigger,
    unregister,
    watch,
    formState,
  } = useForm(useFormProps)
  const {
    isValidating,
    isDirty,
    dirtyFields,
    isSubmitted,
    isSubmitSuccessful,
    submitCount,
    touched,
    isSubmitting,
    isValid,
    errors,
  } = formState

  // to optimize rendering, we only pass along form methods that need to be included
  const surgicalUseProps = useMemo(
    () => ({
      handleSubmit,
      setValue,
      register,
      control,
      clearErrors,
      getValues,
      reset,
      setError,
      trigger,
      unregister,
      formState: {
        isDirty,
        dirtyFields,
        isSubmitted,
        isSubmitSuccessful,
        submitCount,
        touched,
        isSubmitting,
        isValid,
        errors,
      },
    }),
    [
      handleSubmit,
      setValue,
      register,
      control,
      clearErrors,
      getValues,
      reset,
      setError,
      trigger,
      unregister,
      isDirty,
      dirtyFields,
      isSubmitted,
      isSubmitSuccessful,
      submitCount,
      touched,
      isSubmitting,
      isValid,
      errors,
    ]
  )

  return <FormMethods.Provider value={surgicalUseProps}>{children}</FormMethods.Provider>
}
```

**Comment by bluebill1049** [comment]
This is coming for v7 with a subscription model. 👍 you can try out in 7.0.0-alpha.2

**Comment by rosemariesadler** [comment]
Thanks so much! We will try it out!
