### ISSUE TITLE
V7 Major Bug - useFieldArray and reset() crash application

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4111]
**Describe the bug**
If a field array has an empty array for it's default value and `reset` is called, then react-hook-form will throw an unhandled error and crash the application. 

**To Reproduce**

1. Click reset
2. Optionally append some values

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-template-forked-ydf5r?file=/src/index.js

**Comment by bluebill1049** [comment]
oh wow... thanks!

**Comment by wdfinch** [comment]
No problem. Any way we could get a hot fix for this? This is causing some big issues for me.

**Comment by bluebill1049** [comment]
> No problem. Any way we could get a hot fix for this? This is causing some big issues for me.

I will sort it out tonight after work.

**Comment by wdfinch** [comment]
Thanks!

**Comment by bluebill1049** [comment]
`<button onClick={reset}>Reset</button>`

same as above

`<button onClick={(e) => reset(e)}>Reset</button>`

I will patch this with a fix, but you should not to the above, because `event` will be passed as argument.

**Comment by wdfinch** [comment]
Oh, that's an easy workaround. I was noticing this issue in my app though and I'm not passing an event. I will try to reproduce that too.

**Comment by bluebill1049** [comment]
don't worry about it @wdfinch i trust you, i will patch this anyhow 👍

**Comment by bluebill1049** [comment]
retag with `bug`

**Comment by wdfinch** [comment]
@bluebill1049 it took a little more digging but I think I found it this time. The issue is if you use `setValue` with a field array and then run `reset()`. 

Could you take a look at the updated sandbox and click reset again?

https://codesandbox.io/s/react-hook-form-controller-template-forked-ydf5r?file=/src/index.js

**Comment by wdfinch** [comment]
I don't think it's related to the conditional rendering, but I added some of that too in on my quest to find this.

**Comment by wdfinch** [comment]
Also, it looks like this will occur if you use `reset` with new array values as well, so I think it's something deeper than just `setValue`.

**Comment by bluebill1049** [comment]
Will get another alpha tonight, see if those issues can be resolved.

**Comment by wdfinch** [comment]
Thanks!

**Comment by bluebill1049** [comment]
The latest alpha version should fix it.

**Comment by wdfinch** [comment]
Thanks so much! I now have a breaking issue related to @hookform/resolvers. It appears that the resolvers rely on an export called "transformToNestObject". After upgrading, I'm getting an error because those files can't find this export. Was this item removed or modified in the patch just now? 

I would show a sandbox, but I can't get this error in the sandbox, possibly because it all happens inside code that hasn't been run yet/is outside the project scope. 

This is specially the line that is giving me trouble:

`import { appendErrors, transformToNestObject, } from 'react-hook-form';`

**Comment by bluebill1049** [comment]
@wdfinch get the latest beta of `resolver`

**Comment by wdfinch** [comment]
Ok I got downloaded the latest resolver. Took some serious trial and error but it seems like there's another unhandled exception  in the latest resolvers package (2.0.0-rc.1). Not sure if this is true with all resolvers, but if you use the joi resolver with a schema that can be invalid (some validation), you don't have any inputs registered and you check `formState.isValid`, the library will throw an error and crash your application. 

@jorisre could we get a hotfix for this?

Note I need to click the refresh button on the code sandbox in order to trigger it.

https://codesandbox.io/s/react-hook-form-controller-template-forked-7twbb?file=/src/index.js

**Comment by bluebill1049** [comment]
not the `rc`, `beta` (It was a mistake release)

**Comment by jorisre** [comment]
@wdfinch You have to install the beta as @bluebill1049 said
https://codesandbox.io/s/react-hook-form-controller-template-forked-7dvgp

**Comment by wdfinch** [comment]
My bad. I thought RC is newer than beta so I went with that. Oh well. Ok, so it looks like everything is working fine now! Thanks so much for everyone's help on this. Really appreciate it.
