### ISSUE TITLE
useController - validation onBlur does not work until you have submitted form

### ISSUE THREAD

**Issue by MagicDuck** [react-hook-form/react-hook-form#4112]
**Describe the bug**
useController() - validation onBlur does not work until you have submitted form
onBlur from controlled component calls this:
![image](https://user-images.githubusercontent.com/95201/106845952-d3b9e100-6660-11eb-9c55-8c3cc36c6607.png)
which calls `shouldValidate(true)`
![image](https://user-images.githubusercontent.com/95201/106846068-04017f80-6661-11eb-8b10-83a4a3507c6d.png)
which calls into this:
![image](https://user-images.githubusercontent.com/95201/106846188-475bee00-6661-11eb-9d3c-8ae2e334f370.png)
Problem is `isOnBlur` is never true as it doesn't get passed in...
**To Reproduce**

1. Create a form with a custom resolver that simply console logs when invoked and option: `reValidateMode: 'onBlur'`
2. Form should contain a component that uses useController() and invokes onBlur() when clicking out
3. Click in and out of component, resolver will not log

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

Sorry, don't have time to create a sandbox atm.

**Expected behavior**
resolver should trigger

**Desktop (please complete the following information):**

- OS: macOS
- Browser: chrome
- Version 6.14.2

**Comment by MagicDuck** [comment]
am guessing fix should be as simple as passing `isOnBlur: true` to `skipValidation()` invocation in `shouldValidate()`

**Comment by bluebill1049** [comment]
`reValidateMode` is after submitting the form. I think you are after onTouched mode.

**Comment by bluebill1049** [comment]
This option allows you to configure when inputs with errors get re-validated after submit. By default, validation is only triggered during an input change.
--

**Comment by MagicDuck** [comment]
@bluebill1049 ah doh, you are right, for some reason my tired brain decided to use `reValidateMode` instead of `mode` ... aaargh
Thank you for the quick response! Btw, loving the library so far, we're switching over to it from redux-form

**Comment by bluebill1049** [comment]
no worries at all buddy. 👍
