### ISSUE TITLE
useFieldArray doesn't remove correct indexes

### ISSUE THREAD

**Issue by Grandnainconnu** [react-hook-form/react-hook-form#4117]
**Describe the bug**
I have discovered that after removing 5 indexes, wait for the render, then remove 5 other indexes, this time one of the index will be wrongly removed.

**To Reproduce**
On CSB: add all the possible attributes on the select field, then remove the two last ones. The first remove will be fine, on the second one, variants should be removed from index 9 to 17, but variant n°2 is removed, and variant n°9 is kept.
(Check console for id's and indexes)

**Codesandbox link (Required)**
https://codesandbox.io/s/problem-remove-usefieldarray-m8zub?file=/src/App.js

**Expected behavior**
Elements at indexes should be removed correctly.

**Workaround**
Using `remove` in a forEach instead of passing an array of indexes does the work. 

**Desktop (please complete the following information):**

- OS: Ubuntu 20
- Browser : Chrome
- Version :  87.0.4280.66

**Additional context**
I'm making a form to add products variations, depending on attributes (Sizes, Colors, Cut, etc.), I discovered this bug when testing my migration from formik (it was triggering 30 renders per product variant update) to react-hook-form.

**Comment by bluebill1049** [comment]
- please supply a reasonable codesandbox for us to reproduce the issue.
- also useFieldArray is not meant to be used in your CSB.

**Comment by cargallo** [comment]
I'm having issues with remove using index too. It removes others than the clicked one

**Comment by bluebill1049** [comment]
> I'm having issues with remove using index too. It removes others than the clicked one

hey @cargallo, please supply a codesandbox for me to reproduce the issue.

**Comment by cargallo** [comment]
Hi @bluebill1049 here is the sandbox. Click n times in append and then delete items, it always deletes the last one.

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-b0k18

**Comment by bluebill1049** [comment]
Hi @cargallo it's made for field inputs: https://codesandbox.io/s/react-hook-form-usefieldarray-forked-qgx40

**Comment by cargallo** [comment]
Hi, I realize that the problem in my code was that it mandatory to use item.id in the main wrapper of fields. If you set another key it doesn't work. Maybe you can throw an error in that case? Without putting the key in that way it was deleting the last one!

![image](https://user-images.githubusercontent.com/13320290/107174165-48b25100-69a8-11eb-969c-b66cb521e84b.png)
