### ISSUE TITLE
`formState.isDirty` is true even though no field is really dirty

### ISSUE THREAD

**Issue by delijah** [react-hook-form/react-hook-form#4119]
**Describe the bug**
When setting values on a form for which there are no related fields for, the form stays dirty after reverting these values back to their original state.

**To Reproduce**

1. Click on 'Clear' button
2. Click on 'Revert' button
3. Click on 'Submit' button
4. In the console i compare the `defaultValues` with the values the form submits. They are totally equal! `formState.isDirty` is true, `formState.dirtyFields` is an empty object.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-forked-q3iw3?file=/src/index.js

**Expected behavior**
When the current values of the form equals the `defaultValues`, `formState.isDirty` must be false.

**Desktop (please complete the following information):**
- OS: macOS Mojave Version 10.14.6 (18G5033)
- Browser: Google Chrome Version 88.0.4324.96 (Official Build) (x86_64)

**Additional context**
Besides the only form field called "nickname" in the example provided, there is an additional `operations` variable in the `defaultValues` object (which is not a field, only data) which also gets updated in the example by using `setValue`. The issue is related to that variable. If i remove the `operations` thingy, the example works fine without any issue.

**Comment by bluebill1049** [comment]
<img width="526" alt="Screen Shot 2021-02-06 at 9 19 15 am" src="https://user-images.githubusercontent.com/10513364/107095153-6377af00-685c-11eb-8d33-cdb781fdace8.png">

why are you mutating the defaultValues? 

see below: 
<img width="351" alt="Screen Shot 2021-02-06 at 9 22 00 am" src="https://user-images.githubusercontent.com/10513364/107095373-c6694600-685c-11eb-86fd-8b4e08813698.png">

<img width="409" alt="Screen Shot 2021-02-06 at 9 21 21 am" src="https://user-images.githubusercontent.com/10513364/107095320-adf92b80-685c-11eb-9236-85c850c9a164.png">

**Comment by delijah** [comment]
Hmm, not sure if i understand. But i try to answer. It's not about the defaultValues, i've just used those since i wanted to set the values back to the original state. This just as an example.. the real world use case would be: The user starts to edit a form, but manually sets the values back to the original state. Let's say the form consists out of one field called "colors". A dropdown...

1. By default the first entry with the value "red" is selected (the form is not dirty)
2. The user selects blue, the form gets dirty. We can display a visual thingy to the user so he sees that the form is dirty
3. The user then decides to go back to "red"
4. IMHO the dirty state should disappear again, since the value of the field is the same as when the form got initialised

I've adjusted the example with the hope to reduce confusion.

**Comment by bluebill1049** [comment]
The problem `isDirty` is set back to false, because the defaultValues is not matching with what's form values, inside hook form we just simply do a deepEqual.

here is an updated screenshot of your csb:

<img width="447" alt="Screen Shot 2021-02-06 at 10 03 40 am" src="https://user-images.githubusercontent.com/10513364/107098109-9a50c380-6862-11eb-8e48-810b17432332.png">

see the diff above with formValues and defaultValues

**Comment by delijah** [comment]
Hmm, ok. But on line 37 i do `setValue("operations", []);`. So the value of `operations` should be an empty array again, isn't it? Also in the giphy in my recent comment you can see (in the console at the end of the "movie") that the form values i get in the submit handler are the same (equal) as the defaultValues.

**Comment by bluebill1049** [comment]
There is no such `operations` input been registered.

**Comment by delijah** [comment]
Yes exactly, this is on purpose. It's kind of metadata that belongs to the form (but no need for a field). So i am not sure if this is supported.
I mean i can pass in `operations` in the defaultValues, it looks like i can update `operations` with `setValue` and it works well (i get the updated value with `getValues` and as values argument in the submit handler). So it looks like it works, until it comes to the `isDirty` state of the form...

**Comment by bluebill1049** [comment]
by default we don't, input sneed to register, although you can try to set the option `shouldUnregister: false`

**Comment by delijah** [comment]
Yeah exactly, that's what i did in my example. `shouldUnregister` is set to `false`.
Otherwise (if `shouldUnregister` would be `true`) the value `operations` would not be in the `values` argument at all in the submit handler.
But still, the `isDirty` flag stays `true` magically 🤷..

**Comment by bluebill1049** [comment]
I know such an issue frustrates you, but this is such a convoluted example... it even gets my head spinning by looking at it, so please consider helping me to help you.

https://codesandbox.io/s/react-hook-form-useform-template-forked-dp2ip?file=/src/index.js

Summary: 
`setValue("operations", [], { shouldDirty: true });`

**Comment by delijah** [comment]
Yeah sometimes it is hard to provide a reasonable, for an outsider, understandable example, coming from a use case connected deeply in a complex app.

Hahaha, oh no really? That `shouldDirty` makes it work? I didn't think about it because my mind was stuck with "i want the form state UNdirty". But it makes total sense. Thank you very much 🙏  Sorry for bothering.

**Comment by bluebill1049** [comment]
No worries at all, please don't take the message in a negative way. I think it's a general message when an issue sends to the maintainer, we expect the example can be a bit more straightforward, at the same time I understand the complexity within your or everyone's app. I hope you understanding where I am coming from, and I thank you for your understanding too. ❤️  have a good weekend.

**Comment by delijah** [comment]
Sure sure 👍  Thank you, have a good weekend as well 🥳
