### ISSUE TITLE
Add a setFocus option

### ISSUE THREAD

**Issue by joejordan** [react-hook-form/react-hook-form#4120]
**Is your feature request related to a problem? Please describe.**
Similar to `setValue()`, `setFocus()` would allow developers to programmatically tell which form field should have focus.

**Describe the solution you'd like**
` setFocus('fieldName')` would give that particular form field the focus.

**Describe alternatives you've considered**
None

**Additional context**
Since React Hook Form already handles field refs, it appears that it would be fairly straightforward to add the ability to programmatically set focus on a particular field.

**Comment by kwerty** [comment]
+1

Also, if no field name is provided to setFocus() it should focus on the first input with errors.

https://github.com/react-hook-form/react-hook-form/issues/4518

**Comment by mogelbrod** [comment]
I'm disabling all inputs while `formState.isSubmitting`, which unfortunately prevents the `shouldFocusError: true` option from working as expected. Having `useForm()` or `useFormState()` return a `setFocus()`/`focusError()` would allow me to simulate `shouldFocusError: true` without having to re-implement the internal RHF helper `focusFieldBy()`:

```js
function FormComponent(props) {
  const form = useForm({})
  const { isSubmitting } = form.formState
  const { formStateRef, fieldsRef } = form.control

  // Trigger focus after fields are no longer disabled (during isSubmitting)
  React.useEffect(() => {
    if (isSubmitting) { return }
    // FIXME: Here is where I'd call `form.setFocus()`/`form.focusError()` instead of `focusFieldBy()`
    const { errors } = formStateRef.current
    focusFieldBy(
      fieldsRef.current,
      (key: string) => getIn(errors, key),
    )
  }, [isSubmitting, fieldsRef, formStateRef])

  return ...
}

/**
 * Adapted from the private focusFieldBy() react-hook-form helper.
 */
function focusFieldBy(
  fields: FieldRefs,
  callback: (name: string) => boolean,
  fieldsNames?: Set<string>,
) {
  for (const key of (fieldsNames || Object.keys(fields))) {
    if (key === '_f') { continue }
    const field = getIn(fields, key)

    if (field) {
      const { _f } = field
      if (_f && callback(_f.name)) {
        if (_f.ref.focus && _f.ref.focus() === undefined) {
          break
        } else if (_f.refs) {
          _f.refs[0]?.focus()
          break
        }
      } else if (field && typeof field === 'object' && !Array.isArray(field)) {
        focusFieldBy(field, callback)
      }
    }
  }
}
```

**Comment by bluebill1049** [comment]
@mogelbrod v7 is released, will looking into this one. looks like we got few users to want this feature.
