### ISSUE TITLE
Functionality with Typescript

### ISSUE THREAD

**Issue by Eriickson** [react-hook-form/react-hook-form#4124]
Regards, I am passing register and setvalues ​​for props, my project is built with Typecript, what are the specific types for these props?

![image](https://user-images.githubusercontent.com/38663299/107125029-a302c300-687d-11eb-9ca9-e21e86d8bbf8.png)

**Comment by getTobiasNielsen** [comment]
https://github.com/react-hook-form/react-hook-form/blob/8189de25e8e7e9cbaf864a83ffa4a00cfe5a0943/src/types/form.ts#L204

**Comment by Eriickson** [comment]
![image](https://user-images.githubusercontent.com/38663299/107129261-92147a80-689a-11eb-8d7f-c01843e968a7.png)
There are several types of registration, which corresponds to the type of prop to pass through parameter?

**Comment by getTobiasNielsen** [comment]
These are function overloads that are all part of `register`s type.

You need all of them, because depending on how you use the function, it can change the return value, or parameter types.

**Comment by Eriickson** [comment]
look, for you to understand better, I am just trying to pass the register property to another component and from that component use the register that I passed, since the form is quite long and it is better if I divide it into multiple tabs, I can get this functionality without have to resort to setValue?

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by bluebill1049** [comment]
Thanks, @getTobiasNielsen's help 👍

**Comment by getTobiasNielsen** [comment]
@Eriickson Try using `useFormContext` instead.

https://react-hook-form.com/api#useFormContext
