### ISSUE TITLE
V7 - Disabled field setting empty object {} as value

### ISSUE THREAD

**Issue by andrwo** [react-hook-form/react-hook-form#4130]
**Describe the bug**
When using Reactstrap input field with ref, when field is disabled, the value being set is empty object {}.
Happens with both direct ref & Controller.

**To Reproduce**
Use the codeSandbox below and click on "Get Values" and observe the values output in console log.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-nestedvalue-forked-ecyf1?file=/src/App.tsx

**Expected behavior**
Values should be set to undefined for disabled fields, not empty object.

Result:
```
{metadata: "test", lname: {}, fname: {}, mname: "x"}
```

Expected:
```
{metadata: "test", lname: undefined, fname: undefined, mname: "x"}
```

**Desktop (please complete the following information):**

- Windows
- Chrome 88
- Also codesandbox
- V 7.0.0-beta.1

**Comment by bluebill1049** [comment]
Thanks, @andrwo

**Comment by naseemali925** [comment]
I am facing the same issue. The disabled fields gives an undefined value.

**Comment by bluebill1049** [comment]
`disabled` attribute will return `undefined` for any `register` input at hook form, we don't have a mechanism to change that return result.

**Comment by naseemali925** [comment]
> `disabled` attribute will return `undefined` for any `register` input at hook form, we don't have a mechanism to change that return result.

Okay. Is there a workaround for this? Or any plans to add some flag to the API for this?

**Comment by naseemali925** [comment]
@bluebill1049 When I am using the `getValues` in handleSubmit I am able to get the values for disabled fields using `getValues` but the same fields have undefined as the value in the `data` param from handleSubmit.

**Comment by bluebill1049** [comment]
`disabled` field gets will get undefined during submission, but you still get retrieve value with getValues(), as that's not the final submit form values.

**Comment by bluebill1049** [comment]
actually, `disabled` input should be excluded from the submission... https://www.w3.org/TR/html5/forms.html#constructing-the-form-data-set will adjust that.

**Comment by bluebill1049** [comment]
change discussion here: https://github.com/react-hook-form/react-hook-form/discussions/3714#discussioncomment-355573
