### ISSUE TITLE
useFieldArray in nested objects

### ISSUE THREAD

**Issue by 99uno** [react-hook-form/react-hook-form#4138]
**Describe the bug**
I had the following schema {extraData: []} and now I want to have {settings: {extraData: []}}
I use shouldUnregister false because want to send an empty array if there is no rows. The problem is that in the first case, it's returning the empty array if no values, but inside settings, it's returning undefined.

**To Reproduce**

1. Go to [https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-ufx51?file=/src/index.js](https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-ufx51?file=/src/index.js)
2. Click on Submit
3. View log, it doesn't contain an empty array
4. Repeat in this url where I removed "settings." [https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-b51zj](https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-b51zj) and you will see the empty array

**Expected behavior**
Value must be an empty array despite it's inside an object or not.

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome
- Version 88

**Comment by bluebill1049** [comment]
I would supply a `defaultValues` with an empty field array.

**Comment by 99uno** [comment]
I don't want to implement defaultValues as a workaround, I'm using shouldUnregister just because want empty arrays if no values, and if I need specific code for this situation shouldUnregister is not necessary anymore because I always need special source code for arrays.

**Comment by bluebill1049** [comment]
then what do you expect me to do about it? if you don't want to use the lib in the way it's been built?

**Comment by 99uno** [comment]
I think it should work the same way if it is an array inside a deep key or not.

**Comment by bluebill1049** [comment]
not if you don't supply a `defaultValues`.
