### ISSUE TITLE
Removing item from nested fieldArray using ID instead of index returns error

### ISSUE THREAD

**Issue by ergunp** [react-hook-form/react-hook-form#4140]
**Describe the bug**
When using fieldArray and setting the name to the item id instead of the index for example 
```name={`settings.extraData[${item.id}].firstName`}```
And trying to remove the item an error is thrown. 

```
get(...).map is not a function
```

**To Reproduce**
Set field name to use id instead of index. 
Add a item.
Then remove the item.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-jitwh?file=/src/index.js

**Expected behavior**
Should remove the item regardless of index or id.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 88

**Comment by bluebill1049** [comment]
we don't support such usage.
