### ISSUE TITLE
"isValid" does not work in "production" mode correctly for "useFieldArray"

### ISSUE THREAD

**Issue by Travellerme** [react-hook-form/react-hook-form#4141]
***"isValid" does not work in "production" mode correctly for "useFieldArray"***

**Describe the bug**

`isValid` from `formState` behaves itself differently for `dev` mode and `production` build by using `useFieldArray`

- `dev` mode is launched by `react-scripts start`
- `production` mode is built by `react-scripts build` and served by any server. In my example, it's `express` server

 

**To Reproduce**
- Please clone the git repo with [reproducible scenarios:](https://github.com/Travellerme/react-hook-form-issue)
- Make `npm install`
- Run `npm run dev:make-build-and-serve:run`

**First test-case**

1. Go to `localhost:8001` and check that `isValid: false` is shown on the bottom of the page.
2. Enter any `Quantity` and `Product ID` for `Heading` section. `isValid` label will be changed to `true` 
3. Delete `Quantity` or `Product ID`. `isValid` label will be changed to `false`
4. Validation will be shown under the fieldname
5. Select `Heading2`. First `Heading` will be closed and inputs should be unmounted from DOM.
6. Enter any `Quantity` and `Product ID` for `Heading2` section. `isValid` label is still equal `false`.

![Prod First scenario gif](https://github.com/Travellerme/react-hook-form-issue/blob/master/Prod_first_scenario.gif?raw=true "Prod First scenario")

**If you perform the same scenario but for `dev` mode (`npm start`), on the `6` step `isValid` will be changed to `true`**

![Dev First scenario gif](https://github.com/Travellerme/react-hook-form-issue/blob/master/Dev_first_scenario.gif?raw=true "Dev First scenario")

**Second test-case**

1. Go to `localhost:8001` and check that `isValid: false` is shown on the bottom of page.
2. Enter `Quantity` OR `Product ID` for `Heading` section. The second field must be empty. 
3. Select `Heading2`. First `Heading` will be closed and inputs should be unmounted from DOM.
4. Enter any `Quantity` and `Product ID` for `Heading2` section. `isValid` label is still equal `false`.

![Prod Second scenario gif](https://github.com/Travellerme/react-hook-form-issue/blob/master/Prod_second_scenario.gif?raw=true "Prod Second scenario")

**If you perform the same scenario but for `dev` mode (`npm start`), on the `4` step `isValid` will be changed to `true`**

![Dev Second scenario gif](https://github.com/Travellerme/react-hook-form-issue/blob/master/Dev_second_scenario.gif?raw=true "Dev Second scenario")

**Codesandbox link (Required)**

[Codesandbox:](https://codesandbox.io/s/heuristic-kirch-nnhth)
Please make sure that you go to the `Deployment` section and made a `production` build and deployed it to `Netlify`

Then please click the `Visit Site` link

![Codesandbox](https://github.com/Travellerme/react-hook-form-issue/raw/master/Codesandbox.png?raw=true "Codesandbox")

**Expected behavior**
- `isValid` must behave itself equally for `production` and `dev` builds.
- For `production` build `isValid` must behave itself equally how it works for `dev` build. 

**Screenshots**
![Prod First scenario gif](https://github.com/Travellerme/react-hook-form-issue/blob/master/Prod_first_scenario.gif?raw=true "Prod First scenario")

![Prod Second scenario gif](https://github.com/Travellerme/react-hook-form-issue/blob/master/Prod_second_scenario.gif?raw=true "Prod Second scenario")

**Desktop (please complete the following information):**

- Windows 10 / Ubuntu / OS:
- Browser Chrome / Firefox / Safari
- Version 88.0.4324.150 / 85.0 / 13.1 (15609.1.20.111.8)

**Smartphone (please complete the following information):**

- was not tested

**Additional context**

This issue is reproducible only by using `useFieldArray`

`isDirty` and other flags are also affected

We use your library in our application and it's in `production` already, so we would really appreciate it if it's possible to fix it asap.

Thank you

**Comment by bluebill1049** [comment]
Provide a codesandbox version.

**Comment by Travellerme** [comment]
Hello @bluebill1049 
I've updated the description with codesandbox example

[Codesandbox:](https://codesandbox.io/s/heuristic-kirch-nnhth)
Please make sure that you go to the `Deployment` section and made a `production` build and deployed it to `Netlify`

Then please click the `Visit Site` link

![Codesandbox](https://github.com/Travellerme/react-hook-form-issue/raw/master/Codesandbox.png?raw=true "Codesandbox")

**Comment by bluebill1049** [comment]
Thanks for providing the CSB link, however, it's not reasonable for me to inspect your entire app with all those side effects. I
 believe if there is an issue, you can reproduce that pretty quickly with native inputs. By inspecting blow:

<img width="560" alt="Screen Shot 2021-02-10 at 6 55 46 pm" src="https://user-images.githubusercontent.com/10513364/107480989-965dd200-6bd1-11eb-9631-b01030f68b80.png">

here is a CSB you can base on: 

https://codesandbox.io/s/react-hook-form-usefieldarray-vy8fv

**Comment by Travellerme** [comment]
Hello @bluebill1049 
I've removed all bootstrap / sass / lodash dependencies. 
Please take a look

**Comment by bluebill1049** [comment]
Production behavior is the correct behavior. I am patching this by removing the production check under `useEffect`. This will impact react fast refresh, we are having a prop fix in v7.

**Comment by Travellerme** [comment]
@bluebill1049 
Hmm...If the production behavior is the correct one, then how it's possible in my example to make the form valid after unmounting   `fieldArray` with errors from DOM ? `reset` does not help

**Comment by bluebill1049** [comment]
The usage should be a single useFieldArray instead of mounting and unmount multiple field array, but that's an implementation detail. Prod build is correct as the logic was intended that way because dev is the correct output by "accident".

**Comment by bluebill1049** [comment]
here is a beta: `react-hook-form@6.15.2-beta.1`

**Comment by Travellerme** [comment]
I do understand that this is an implementation detail. But still, we need to have a possibility to have a kind of toggler that will allow us to have several `useFieldArray`  on the page with the possibility to unmount it. I tried to use 'clearErrors, reset, setValue' but nothing helped. 

Do you have any suggestions on how to make the form valid after unmounting `useFieldArray` or how to umount fieldArray correctly from `react-hook-form` ?

**Comment by bluebill1049** [comment]
Did you test the `beta` above?

**Comment by Travellerme** [comment]
@bluebill1049 Yes, I did
Right now I have this issue both in `prod` and `dev` mode
[gif](https://drive.google.com/file/d/1QXQuO3jOcKzm8jXd7c6OBGkGw4PzaL4f/view?usp=sharing)

From my point of view, this is a bug if there is no way to delete/reset fieldArray data from a form to make it valid.

**Comment by bluebill1049** [comment]
`react-hook-form@6.15.2-beta.2`

**Comment by Travellerme** [comment]
@bluebill1049 Now it works fine! )
Thank you so much
In which stable version it will be fixed ?
