### ISSUE TITLE
Allow `setValue` to accept an updater function

### ISSUE THREAD

**Issue by nspaeth** [react-hook-form/react-hook-form#4147]
**Is your feature request related to a problem? Please describe.**
I would like to be sure that I never have a race-condition type bug in my state logic. 

For example,
```ts
const fieldValue = watch('field') // fieldValue === 1
... 
// some other code updates `field` before a re-render causes `fieldValue` to update
// 'field' === 2
...
setValue('field', fieldValue + 1)
// 'field' === 2, should === 3
```

**Describe the solution you'd like**
When using `const [ myState, setMyState ] = useState` you can call `setMyState` with an updater function rather than a literal value: `setMyState((previousState) => previousState + 1)`.

**Describe alternatives you've considered**
```ts
const setFieldValue = useCallback(
	() => setValue('field', getValues('field') + 1), 
	[setValue, getValue],
)
...
setFieldValue(2) 
```

Or, a slightly more complicated example: 
```ts
const onDrop = useCallback(
	newValues => {
		const prev = getValues(name) ?? []
		const newValue = [ ...prev, ...newValues ]
		setValue(name, newValue, { shouldValidate: true, shouldDirty: true })
	},
	[setValue, getValues, name],
)
```
It is easy to see here how 
`newValues => setValue(name, (prev) => [...prev, ...newValues], { shouldValidate: true, shouldDirty: true })` would be much more ergonomic.

**Comment by bluebill1049** [comment]
Thanks for the feature request! moving into project board.
