### ISSUE TITLE
PR 4023 Introduces a Breaking change rather than just a FIX

### ISSUE THREAD

**Issue by westrem** [react-hook-form/react-hook-form#4151]
**Describe the bug**
The PR #4023 changes what kind of value is being passed to `validate` function as it introduces new boolean flag `shouldKeepRawValue` which now forces `validate` fn to get the raw value, instead of whatever value it would get before (even one from `setValueAs`.

Hence, any component that uses custom validate function and also some of the valueAs functionality breaks, because it's getting raw value now rather than the parsed one - this is clearly a BC, as it breaks the contract established before.

**To Reproduce**

Pseudocode below. 

Imagine input `abc`

In version `6.14.2`

```
<AnyFormComponent
  validate={val => /* val here is cba */}
  setValueAs={val => 'cba'} /* map any input to cba */
```

In version `6.15.0` (very next release of minor version change)

```
<AnyFormComponent
  validate={val => /* val here is abc */} ← DIFFERENCE HERE
  setValueAs={val => 'cba'} /* map any input to cba */
```

**Expected behavior**
The new behaviour should be released as new MAJOR version and any `16.*` should keep the old behaviour, or make this new behaviour configurable

**Comment by bluebill1049** [comment]
It was made to fix this bug: https://github.com/react-hook-form/react-hook-form/issues/4019 I forgot to include that in the changelog.

**Comment by westrem** [comment]
Ah, thanks for explanation & looking into this!

**Comment by bluebill1049** [comment]
No worries, sorry about the initial bug...
