### ISSUE TITLE
useController/Controller doesn't support native checkbox input without value

### ISSUE THREAD

**Issue by mogelbrod** [react-hook-form/react-hook-form#4161]
**Describe the bug**
Toggling an input of type `checkbox` without a proper `value` managed by `useController()` or `<Controller>` is not possible as the value is stuck as `""` (or `"on"` if `value` attribute is omitted).

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-controlled-checkboxes-not-working-wwmcs
2. Click on Submit to verify that the RHF model matches the UI form state (`{ withDefaultValue: true }`)
3. Click on either checkbox
4. Submit the form again
5. Notice how the corresponding value is now `""` rather than `true` or `false`
6. Click on the same checkbox again
7. Notice how the checkbox cannot be unchecked and is stuck

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controlled-checkboxes-not-working-wwmcs

**Expected behavior**
Calling the `onChange` function provided by `useController`/`<Controller>` with a ChangeEvent having `input.target.type === "checkbox" && input.target.value === ""`) should toggle the value between `true`/`false` rather than setting it to `""`

**Desktop (please complete the following information):**

- OS: Mac OSX
- Browser: Chrome
- Version: 88.0.4324.150

**Comment by bluebill1049** [comment]
i think you should use `e.target.checked`:

https://codesandbox.io/s/react-hook-form-controlled-checkboxes-not-working-forked-we8oc

**Comment by mogelbrod** [comment]
Thanks for the quick response @bluebill1049!

Unfortunately your forked version exhibits issues - withDefaultValue can only be unchecked, after which it's stuck with `""` as the model value.

Looking at the code `useController()` uses `getInputValue()`:
https://github.com/react-hook-form/react-hook-form/blob/57b7d0c15863745ee647d3ad440066658a85b426/src/useController.ts#L102-L103
Which in turn only uses `checked` if `value` is undefined:
https://github.com/react-hook-form/react-hook-form/blob/57b7d0c15863745ee647d3ad440066658a85b426/src/logic/getInputValue.ts#L5-L12
This can as far as I know never happen since the `value` of checkbox/radio inputs are always a string.

**Comment by bluebill1049** [comment]
what about this: https://codesandbox.io/s/react-hook-form-controlled-checkboxes-not-working-forked-we8oc?file=/src/index.js

FYI: we do need defaultValue for Controller/useController.

**Comment by mogelbrod** [comment]
Yes, providing a custom `onChange` handler does avoid the issue, at the cost of some additional boilerplate. The main reason I raised this as an issue was that `getInputValue()` already contains (seemingly incorrect) logic specific to checkbox inputs (the `checked` property access), and I was wondering if it would be reasonable to tweak it so that it supports boolean checkboxes without additional boilerplate. Something like this:
```ts
 export default (event: any) => 
   isPrimitive(event) || 
   !isObject(event.target) || 
   (isObject(event.target) && !event.type) 
     ? event 
     : event.target.type === 'checkbox' && event.target.value === ''
     ? event.target.checked 
     : event.target.value; 
```

**Comment by bluebill1049** [comment]
> Yes, providing a custom `onChange` handler does avoid the issue, at the cost of some additional boilerplate. The main reason I raised this as an issue was that `getInputValue()` already contains (seemingly incorrect) logic specific to checkbox inputs (the `checked` property access), and I was wondering if it would be reasonable to tweak it so that it supports boolean checkboxes without additional boilerplate. Something like this:
> 
> ```ts
>  export default (event: any) => 
>    isPrimitive(event) || 
>    !isObject(event.target) || 
>    (isObject(event.target) && !event.type) 
>      ? event 
>      : event.target.type === 'checkbox' && event.target.value === ''
>      ? event.target.checked 
>      : event.target.value; 
> ```

That's actually what we used to have, we avoid to specific type check because not all "Checkbox" is consistent with their data. I know it's a bit verbose or annoying to set up your own `onChange`, but it's better to expose that to the users, than bake the condition inside `useController`.

**Comment by bluebill1049** [comment]
what we used to have: 

```
import isUndefined from '../utils/isUndefined';
import isNullOrUndefined from '../utils/isNullOrUndefined';
import isObject from '../utils/isObject';
import isPrimitive from '../utils/isPrimitive';

export default (target: any, isCheckbox: boolean) => {
  if (isNullOrUndefined(target)) {
    return target;
  }

  return isCheckbox
    ? isUndefined(target.checked)
      ? target
      : target.checked
    : isUndefined(target.value)
    ? target
    : target.value;
};

export default (event: any, isCheckboxInput: boolean) =>
  isPrimitive(event) ||
  !isObject(event.target) ||
  (isObject(event.target) && !event.target.type)
    ? event
    : isCheckboxInput || isUndefined(event.target.value)
    ? event.target.checked
    : event.target.value;
```

**Comment by bluebill1049** [comment]
happy for other suggestions, but most likely we will not go back to a specific input type check inside that function.

**Comment by mogelbrod** [comment]
Interesting! I completely missed the [original PR that changed this](https://github.com/react-hook-form/react-hook-form/pull/2140),  nor [this PR](https://github.com/react-hook-form/react-hook-form/pull/2675) suggesting this change as well - my bad! It's unfortunate that checkbox inputs aren't supported "off the shelf" like the other input types, but like you write it's possible to work around.

> That's actually what we used to have, we avoid to specific type check because not all "Checkbox" is consistent with their data.

Do you know any such examples from the the top of your head? It would be useful when trying to come up with alternatives 👍

**Comment by bluebill1049** [comment]
I can't remember on top of my head, but I think the lesson learned was not to have `e.target.type` check inside the `getInputValue` function, keep it simple and leave the input type check at the consumer level.

**Comment by bluebill1049** [comment]
I was thinking about this last night, this maybe the solution.

```
import isUndefined from '../utils/isUndefined';
import isObject from '../utils/isObject';
import isPrimitive from '../utils/isPrimitive';

export default (event: any) =>
  isPrimitive(event) ||
  !isObject(event.target) ||
  (isObject(event.target) && !event.type)
    ? event
    : isUndefined(event.target.checked)
    ? event.target.value
    : event.target.checked;

```

**Comment by bluebill1049** [comment]
The diversity here is some users want the `value`, and some do want the `checked` for `checkbox`.  I think the above change would resolve this problem for native `checked`, while the user still can hijack the `onChange` to get the desired input value.

**Comment by mogelbrod** [comment]
I think that looks like a great solution!
The only potential issue that I can think of would be arrays of native checkboxes with `value` set where the user expects the model value to be an array containing the values of the checked inputs. From what I've seen it doesn't look like this code would be responsible for that use case though - if not then I'm all for this change 👍

**Comment by bluebill1049** [comment]
Thanks, @mogelbrod for the group checkbox, I think it's better to maintain your own `useState`. 👍

**Comment by bluebill1049** [comment]
@mogelbrod if you interested to contribute, feel free to send a PR as well, otherwise I will get to it tonight after work.

**Comment by bluebill1049** [comment]
Ok, i just had a quick play it's actually tricky... because checkbox `value="on"` by default.

**Comment by mogelbrod** [comment]
I won't be able to work on an PR today, but might be able to on Monday if you haven't beat me to it 😃 

If I were to guess I'd say that having a single checkbox toggle between true and false is the most commonly desired behaviour. My general suggestion would be to make the most common use case supported with minimal boilerplate, while of course allowing less common (but valid) use cases possible through configuration.

Having an `<input type="checkbox" name="check" value="customValue">` toggle the model between `{ check: 'customValue' }` and `{}` would definitely be a valid use case, albeit likely not very common. I believe the "array of checkboxes" use case is more frequent, and it's already supported by this library as far as I know.

**Comment by bluebill1049** [comment]
I think I have a find a solution, probably not going to patch this on V6 (afraid of breaking change with value as boolean instead of string) but get that in V7.

**Comment by mogelbrod** [comment]
@bluebill1049 Sounds great - I just started migrating to the V7 beta anyway! The other changes look solid as well 💯 
I'm really appreciative of all the work you put into this library by the way, and the quick response times on questions and issues is nothing short of amazing ❤️ 

Feel free to close this issue if the PR gets merged 👍

**Comment by bluebill1049** [comment]
Thanks, @mogelbrod for your understanding and support. I wish there are more reasonable developers like yourself, we can really push this library to the next level. I will do some more testing tmr because it's getting merge and published at v7. ❤️

**Comment by bluebill1049** [comment]
merged.
