### ISSUE TITLE
Support for Flow type definitions

### ISSUE THREAD

**Issue by abogacki** [react-hook-form/react-hook-form#4175]
**Is your feature request related to a problem? Please describe.**
Hi, as a developer I'm currently working on projects, which are using Flow as a static type checker. 

Because of simplicity and robustness of react-hook-form,  I would like to introduce/refactor forms within the codebase using this library. The problem is that without Flow support, I potentially loose the advantage of using static type checker in forms.

**Describe the solution you'd like**
My question is whether you possibly could support Flow type definitions in either this repository, or in [flow-typed](https://github.com/flow-typed/flow-typed) repo.

**Describe alternatives you've considered**
AFAIK, redux-form and Formik are the only alternatives, supporting Flow types. My use case requires high performant forms. I could really benefit from a library that is "~13% faster than Formik and ~25% faster than Redux Form" 😄

**Additional context**

**Comment by bluebill1049** [comment]
Hey, @abogacki I will move this into our feature request board, I am not an expert on flow type, hopefully, someone else can pick this up, not sure flow type will be compatible with string template literal with TS 4.1
