### ISSUE TITLE
Field Array Breaks with TypeError on version 6.0.0+

### ISSUE THREAD

**Issue by LethalPants** [react-hook-form/react-hook-form#4178]
**Describe the bug**
On filling the input to the field array a type error occurs. In case the error does not occur, I am unable to submit the form most likely due to a validation error. I am migrating from formik and know that the validation isn't the issue, can't figure out what is wrong with my implementation.

**To Reproduce**

1. Go to [https://codesandbox.io/s/condescending-lalande-i5i9z](https://codesandbox.io/s/condescending-lalande-i5i9z)
2. Fill the Article No., Name, Supplier, Unit, Attribute and Value fields
3. Click on the Active field

**Codesandbox link (Required)**
https://codesandbox.io/s/condescending-lalande-i5i9z

**Expected behavior**
Should be able to see the values on submitting the form and no error while appending, removing and filling the field array fields. 

**Screenshots**
![image](https://user-images.githubusercontent.com/48921721/107774757-7bfe3280-6d50-11eb-99aa-7e499d3530f1.png)

**Desktop (please complete the following information):**

- OS: Window w/ WSL
- Browser : Firefox
- Version: 85.0.2 (64-bit)

**Comment by leapful** [comment]
@LethalPants : The problem is from resolver (line 81) of CreateProduct.jsx. In case everything is valid (no error), there is no returned value while it should be.

```
Make sure you are returning an object that has values and errors properties. Their default values should be {}.
```

Referer: https://react-hook-form.com/api/#useForm

Working sample:https://codesandbox.io/s/gifted-cache-2fpvc

**Comment by LethalPants** [comment]
Oh, I didn't catch that. Thanks a lot!
