### ISSUE TITLE
useWatch() returns defaultValue instead of updated value on a multi-step form when switching between steps

### ISSUE THREAD

**Issue by uncvrd** [react-hook-form/react-hook-form#4197]
**Describe the bug**
I have a multi-step form that presents fields to the user as they click `forward` or `back`. Similar to a form wizard. I have recently converted my code to use `FormProvider` so that I can access `useForm` properties/methods within each separate step by using `useFormContext()`. This works great, except on a certain step, I need to "watch" for a field value to determine which data I display on the screen. I've used `watch` in the past, but now that I am using the provider, I thought I'd try `useWatch` which makes use of the provider.

What I've discovered is that when using `useWatch`, it properly tracks changes to the input you're watching, but once you step forward in your form **and then go back to the previous step you typed in**, the `useWatch` hook returns the default value of the form input instead of what's actually stored in the input.

Steps to reproduce in the environment below:

1. On step one, the defaultValue is.. "default value", go ahead and type in to this input to change the value, you will see the watched value change in the text above as well which accurately tracks the current value
2. Click the "Go Forward" button
3. Nothing to really note here, but transitioning to new step is important. Now click "Go Back" to go back to the first step
4. Now you'll note that the `input` has the latest value you typed in (great!), however the watched value returned from `useWatch` is back to our "default value" text instead of whatever text you typed in the input before moving to the next step

Here's a simple codesandbox:
https://codesandbox.io/s/musing-fire-i5p84?file=/src/App.tsx

Video replication: 
https://streamable.com/9n9xn8

**Expected behavior**
I expect that the `useWatch` value is the value that I've typed in to the input when I return back to the previous step

**Desktop (please complete the following information):**

- OS: Mac OS Big Sur
- Browser Chrome
- Version 88.0.4324.146

Running RHF: 6.15.1

---

EDIT: FYI using the basic`watch` performs as I stated in "Expected Behavior"

**Comment by bluebill1049** [comment]
This is actually the expected behavior, when `useWatch` gets mounted, it will return `defualtValue`, a simple fix would provide a `defaultValue` at `useWatch`.

```
useWatch({
  control,
  defaultValue: getValues().test
})
```

In the next major version, you wouldn't be having this issue tho.

**Comment by uncvrd** [comment]
I see! Ok thanks for letting me know, I guess I was expecting the same behavior as `watch` when it mounts. I'll use that for now and then when the next major version releases I'll switch to `useWatch` thanks for the insight :)

**Comment by bluebill1049** [comment]
Yea, because `watch` never gets unmounted and remounted, but yes we have found a better solution in v7, so useWatch will always return the updated value, even unmount and remount. 👍
