### ISSUE TITLE
`setValueAs` doesn't work for checkboxes and radio inputs

### ISSUE THREAD

**Issue by KubaJastrz** [react-hook-form/react-hook-form#4201]
**Describe the bug**

I've found in the docs that `setValueAs` can be used to manipulate submitted value based on the input, but it seems like only the text inputs (like `type="text"`, `type="number"` etc) and select dropdowns support this.

I didn't manage to get any working results with `input[type="checkbox"]` and `input[type="radio"]` but it could possible that I'm doing something wrong. In that case please correct me.

Working example:
```js
const {register} = useForm()
return (
  <input
    type="text"
    name="number"
    ref={register({
      setValueAs: (value) => parseInt(value, 10),
    })}
  />
)
```

Not working example:
```js
const {register} = useForm()
return (
  <input
    type="radio"
    name="boolean"
    value="true"
    ref={register({
      setValueAs: (value) => JSON.parse(value),
    })}
  />
)
```

**To Reproduce**

1. Go to codesandbox reproduction
2. Select some checkboxes, radio buttons, dropdowns and type in numbers
3. Submit the form
4. Notice that only `<select>` and text inputs get modified by `setValueAs`

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-reproduction-q6gxf?file=/src/index.js

**Expected behavior**

`"data.array"` should be of type `number[]` and `"data.radio"` of type  `boolean` but instead they are `string[]` and `string` respectively.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome 86
- Version: 6.15.1

**Comment by bluebill1049** [comment]
Thanks for the bug report. This feature right now it's limited to input type="text".

**Comment by bluebill1049** [comment]
Going to close this issue, as the feature was only applicable to input type `text`.

**Comment by KubaJastrz** [comment]
Understandable, however a change to the documentation would be helpful to avoid further confusion, since I don't think this behavior is stated anywhere.

**Comment by bluebill1049** [comment]
<img width="972" alt="Screen Shot 2021-02-19 at 6 32 03 pm" src="https://user-images.githubusercontent.com/10513364/108472374-c5b2c400-72e0-11eb-8134-67dd7a5a0660.png">

doc is updated.

**Comment by michaeljblum** [comment]
Does this mean there is no way of preventing react-hook-form from converting numbers into strings upon submission of a type="radio" input form? 

I've tried setValueAs as well as valueAsNumber, but no luck. The number keeps being changed to a string. Easy enough to override on my own afterwards, but would be nice to be able to stop this from happening anyway.

**Comment by tomascarignano98** [comment]
Thank you guys!
