### ISSUE TITLE
React Router v.6 re-render

### ISSUE THREAD

**Issue by guygit** [react-hook-form/react-hook-form#4203]
The new Router has the concept of an "Outlet" component similar to Angular.

## Scenario
Say a Parent-Component hosts such an outlet because it has 2 Child-Components (routes).

```js
const Parent = () => {
    const methods = useForm();
    return (
       <FormProvider {...methods}>
          <Form onSubmit={...}>
             <div>Child Components go here ...</div>
             <Outlet />
         </Form>
     </FormProvider/>
   );
}

const ChildA = () => {
   const {register} = useFormContext();
   return (
      <input ref={register} name="name"/>
  )
}
const ChildB = () => {
 // basically same as ChildA
```
## Problem
Parent gets re-rendered each time navigating from ChildA to ChildB component.
## Question
Is this behavior indented?

Thank you!

**Comment by bluebill1049** [comment]
I think that's a react-router question right?

**Comment by guygit** [comment]
No Bill, I wish it was - I checked it by removing all RHF references. Then, the Parent Component doesn't re-render.

**Comment by bluebill1049** [comment]
then plz follow our issue template to provide enough information for us to reproduce the problem.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by guygit** [comment]
Sorry - fair enough

**Comment by bluebill1049** [comment]
will re-open after more detail is supplied and the issue exists.
