### ISSUE TITLE
Checkbox requires 2 clicks when form is submitted `onChange`

### ISSUE THREAD

**Issue by abeMedia** [react-hook-form/react-hook-form#4212]
**Describe the bug**
When using `handleSubmit` on the `onChange` event of a form checkboxes require 2 clicks to check/uncheck.
As can be seen on the devtools the form data actually updates after the first click but it's not reflected on the UI. The second click doesn't change the form data but only the UI. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://codesandbox.io/s/checkbox-error-when-submitting-onchange-mmvng
2. Click on the checkbox (nothing happens)
3. Click on the checkbox again (now it's checked)

**Codesandbox link (Required)**
https://codesandbox.io/s/checkbox-error-when-submitting-onchange-mmvng

**Expected behavior**
Should be checked after first click.

**Desktop:**

- OS: MacOS 11.2.1
- Browser Chrome
- Version 88

**Comment by bluebill1049** [comment]
this is not related to hook form: https://codesandbox.io/s/checkbox-error-when-submitting-onchange-forked-4y9ko?file=/src/App.js

**Comment by abeMedia** [comment]
Thanks for the quick response @bluebill1049! It does seem to be `react-hook-form` though as not using the `handleSubmit` functions works. See https://codesandbox.io/s/checkbox-error-when-submitting-onchange-forked-stt1h

**Comment by bluebill1049** [comment]
i see `handleSubmit` has e.preventDefult for not having native submit (refresh page) behavior, that's why it's not working for your usage, you will have to do what i suggested above.

**Comment by abeMedia** [comment]
Ok. I had actually wondered if it's that. Thanks for your help!
