### ISSUE TITLE
Getting "TypeError: undefined is not an object" in an Expo React Native project when trying to create a custom "react-hook-form" input component

### ISSUE THREAD

**Issue by sepsol** [react-hook-form/react-hook-form#4213]
**Describe the bug**
I'm trying to create a reusable component and use it instead of the default `TextInput` component in all of our screens. Inside this new `CustomTextInput.js` component, I'm exporting the main configurable component as default which is wrapped in a `Controller` component provided by the `react-hook-form` library. I'm then supposed to pass the `control` config object from the parent component whenever I create an instance of the `CustomTextInput` component.

Besides the default export, I'm also exporting some pre-configured variations of that `CustomTextInput` component. I was successful with exporting and using the `EmailInput` and `PasswordInput` configurations, but I'm encountering `ref` and `revalidation` errors whenever I try to use my `CalendarInput` and `LocationInput` components. Though I'm able to create them manually by passing all the configurations through the main component from the default export of `CustomTextInput.js`.

To be more specific I'm getting this error message for when I try to display either `CalendarInput` or `LocationInput`:

```
TypeError: undefined is not an object (evaluating '_ref21$reValidateMode.isReValidateOnBlur')
```

**To Reproduce**

1. Go to https://snack.expo.io/@sepsol/custom-text-input-error
2. Uncomment either line 50 or 51
3. See the error in the preview panel on the right

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.
➡️ https://snack.expo.io/@sepsol/custom-text-input-error

- [useForm](https://codesandbox.io/s/react-hook-form-useform-template-lsm61) Template
- [useFieldArray](https://codesandbox.io/s/react-hook-form-usefieldarray-template-q0jek) Template
- [Controller](https://codesandbox.io/s/react-hook-form-controller-template-yu0z5) Template

**Expected behavior**
A clear and concise description of what you expected to happen is that I want to bypass this error and resolve this issue by successfully displaying `CalendarInput` and `LocationInput` components which are exported from `CustomTextInput.js` file, just like how the `EmailInput` and `PasswordInput` behave.

**Screenshots**
If applicable, add screenshots to help explain your problem. -> N/A

**Desktop (please complete the following information):**

- OS: [e.g. iOS] React Native (iOS + Android)
- Browser [e.g. chrome, safari] N/A
- Version [e.g. 22] 6.15.1 for the library on local computer

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] Any Device
- OS: [e.g. iOS8.1] iOS + Android
- Browser [e.g. stock browser, safari] N/A
- Version [e.g. 22] 6.15.1 for the library on local computer

**Additional context**
Add any other context about the problem here. -> Let me know if I should further clarify the problem.

**Comment by bluebill1049** [comment]
I don't think ref works for react native, you should stick with `controller` or `useController`/

```
export function LocationInput(
  control,
  errors,
  input = {
    name: 'location',
    label: 'Location',
    placeholder: '',
    defaultValue: '',
  },
  icon = 'location',
  ...inputProps
) {
  return (
    <CustomTextInput
      control={control}
      error={errors}
      input={{
        name: input.name,
        label: input.label,
        placeholder: input.placeholder,
        defaultValue: input.defaultValue,
      }}
      icon={icon}
      {...inputProps}
    />
  );
}
```

Pretty sure this component is not going to work in RN.

**Comment by leapful** [comment]
@sepsol @bluebill1049 

The CalendarInput and LocationInput are currently using wrong props parameter. It should be:

```
export function CalendarInput({ control, ... }) {} 
```

instead of 

```
export function CalendarInput(control, ...)
```

**Comment by sepsol** [comment]
@leapful  Thank you sooo much, you don't know how many hours it's been since I was trying to find what the hell is wrong with my code. I appreciate your help 🙏

**Comment by bluebill1049** [comment]
Thank you @leapful 🙏
