### ISSUE TITLE
`useFieldArray` to skip deep nested initialisation 

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#4216]
Hi! I have a question regarding setting values after the field array form is registered and all inputs have been mounted. We fetch some additional data from the API and overwrite all the values within that field array with the new data. What would be the best way to  do so? 

`reset` would not be possible because we don't want to overwrite other changes in the form. I have tried `setValue` but it seems to be adding an extra random entry to the field array. 

I can try to do a code sandbox but its hard to replicate the form we have in a much simpler way :( Hopefully this code snippet helps, if not I can try do a codesandbox

Pretend the timeout is an api fetch.
```
  React.useEffect(() => {
    const timer = setTimeout(() => {
      const features = [{ name: "hello" }, { name: "world" }];    // pretend this is returned from an API
      features.forEach((feature, index) => {
        setValue(`test.${index}.data.features.${index}.name`, feature.name);
      });
    }, 5000);
    return () => clearTimeout(timer);
  }, []);
```

Have also tried: 
```
setValue(`test.${index}.data.features`, features);
```
Thank you!

_Originally posted by @WhatIsTofu in https://github.com/react-hook-form/react-hook-form/discussions/3714#discussioncomment-374144_

**Comment by leapful** [comment]
@bluebill1049 

Did you try to use method append() of useFieldArray ?

For example:

```
React.useEffect(() => { 
   // Fetching features with delay
   append(features); 
}, []);
```
https://codesandbox.io/s/intelligent-tereshkova-qi0kw?file=/src/App.js

**Comment by bluebill1049** [comment]
hey @leapful thanks for looking into it. this one is on v7.

**Comment by bluebill1049** [comment]
I really appreciated your help on all those questions and issues @leapful 🙏

**Comment by leapful** [comment]
@bluebill1049 

I've tried with v7 and it seems to work too

https://codesandbox.io/s/serene-shaw-f2ug0?file=/src/App.js

**Comment by bluebill1049** [comment]
try this CSB: https://codesandbox.io/s/peaceful-tu-c78or-test2-c78or?file=/src/App.js

click setValue, then append. (it will do a reset right away)

**Comment by bluebill1049** [comment]
here is the fixed: https://codesandbox.io/s/peaceful-tu-c78or-test2-forked-gxeo9?file=/src/App.js

**Comment by bluebill1049** [comment]
haha, you are a master with this lib usage. yeah, your usage works. lol

**Comment by bluebill1049** [comment]
react-hook-form@7.0.0-beta.6

patched.
