### ISSUE TITLE
defaultValues with fetch breaks after upgrade to 3.26.2

### ISSUE THREAD

**Issue by hitbear518** [react-hook-form/react-hook-form#422]
**Describe the bug**
After upgrade to 3.26.2, use defaultValues withed fetched data does not work any more

**To Reproduce**

**Codesandbox link**
https://codesandbox.io/s/github/hitbear518/react-hook-form-defaultvalues-break

**Expected behavior**
defaultValues should update input when fetched data arrive

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bluebill1049** [comment]
hey @hitbear518 ,

I think you are doing it the wrong way, it was working for you on the previous version because react-hook-form was triggering re-rendering.  with the latest update, we are no longer trigger re-rendering at all for submit mode :).

```
import React, { useState, useEffect } from "react";
import ReactDOM from "react-dom";
import useForm from "react-hook-form";

import "./styles.css";

function App() {
  const { register, handleSubmit, watch, errors, reset } = useForm({
    defaultValues: {
      example: ""
    }
  });

  useEffect(() => {
    async function fetchData() {
      return await fetch("https://api.github.com/orgs/octokit/repos").then(
        res => res.json()
      );
    }
    fetchData().then(d => {
      reset({
        example: d[0].name
      });
    });
  }, []);
  
  const onSubmit = data => {
    console.log(data);
  }; // your form submit function which will invoke after successful validation

  console.log(watch("example")); // you can watch individual input by pass the name of the input

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <label>Example</label>
      <input name="example" ref={register} />
      <label>ExampleRequired</label>
      <input
        name="exampleRequired"
        ref={register({ required: true, maxLength: 10 })}
      />
      {errors.exampleRequired && <p>This field is required</p>}
      <input type="submit" />
    </form>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by hitbear518** [comment]
that makes sense.
but since the api is 'useForm', I used to thought it was somewhat 'declarative', so got confused.

**Comment by bluebill1049** [comment]
yea. you can read more on reset here: https://react-hook-form.com/api#reset I have documented with an example as well. The new update is good, we can have 0 re-render now :)
