### ISSUE TITLE
V7: useWatch is not triggered on first key stroke in input

### ISSUE THREAD

**Issue by samantha-wong** [react-hook-form/react-hook-form#4223]
**Describe the bug**
`useWatch` is not triggered on first key stroke in input. Subsequent inputs will trigger a live update.

**To Reproduce**

1. Wait until form loads
2. Type 1 single character into any form field

Expected behavior:
The preview should show the new character that was entered

Actual: 
You have to type another character to get the up to date preview

Codesandbox link (Required):
https://codesandbox.io/s/form-context-watched-fields-2vfr1?file=/src/App.js

Additional context
v7.0.0 beta.6
Also, it works on the alpha versions of V7

**Comment by bluebill1049** [comment]
resolved, releasing a patch for it.

**Comment by bluebill1049** [comment]
-beta.7
