### ISSUE TITLE
[Feature Request] Better DX, add <Watch />, the component version of useWatch 

### ISSUE THREAD

**Issue by xiaoyu-tamu** [react-hook-form/react-hook-form#4228]
**Is your feature request related to a problem? Please describe.**

Similar to `useController` and `<Controller />`, Sometime it's easier to use render prop instead of hook. (naming things is hard, LOL)

It would be nice to add component version of `useWatch`, I understand it's easy to implement on the user side, but some people prefer to import all RHF from the core lib, it make import looks clean. 

Just want to open an issue see how many ppl want this feature.

**Describe the solution you'd like**

```
<Watch<FieldValues> name="" defaultValue="">
   {(values)=> <div>...</div>}
</Watch>
```

**Describe alternatives you've considered**

None
**Additional context**

**Comment by bluebill1049** [comment]
probably can easily build a component as a receipt with useWatch

**Comment by bluebill1049** [comment]
wouldn't it be easy to do by just create a component with `useWatch` inside?

```
const Watcher = (props) => {
 return props.render(useWatch(porps))
}
```

**Comment by xiaoyu-tamu** [comment]
yeah, it just need a simple wrapper, it would be nice included in this lib, so developers won’t deal with typescript types. Just like  ‘Controller’ and ‘useControlller’, it only add few bytes to the lib bundle size.
