### ISSUE TITLE
Module not found: Can't resolve 'react-hook-form'. NextJS

### ISSUE THREAD

**Issue by alextseitlin** [react-hook-form/react-hook-form#4230]
**Describe the bug**
I am using nextjs. All works when running dev but when I do `npm run build` get an error: `Module not found: Can't resolve 'react-hook-form`. 

**To Reproduce**
1. `npm run build`
2. Error in console

**My code**

```
import { useForm } from 'react-hook-form';
import { Input, Button } from '@/atom/form';

export default function CourseLandingPage({ onSubmit }) {
  const { register, handleSubmit, watch, errors } = useForm();

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <div className='bg-light px-4 py-2'>
        <Button secondary>Create a new course</Button>
      </div>

      <div className='mt-5'>
        <Input
          lg
          name='name'
          label='Course name'
          defaultValue={name}
          refProp={register({ required: true })}
          errors={errors}
          error='This field is required'
        />
      </div>
    </form>
  );
}

```
**My build**
"react-hook-form": "^6.15.1",
"next": "^10.0.6",
"next-auth": "^3.2.0",
"react": "16.13.1",

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by bluebill1049** [comment]
we simply need more detail before re-open this issue.

**Comment by alextseitlin** [comment]
@bluebill1049 sorry, I thought I did. Is this better?

**Comment by bluebill1049** [comment]
@alextseitlin which version are you running? the code looks fine.

**Comment by alextseitlin** [comment]
@bluebill1049 Using react-hook-form `6.15.1`

**Comment by bluebill1049** [comment]
> @bluebill1049 Using:
> "react-hook-form": "^6.15.1",
> "next": "^10.0.6",
> "next-auth": "^3.2.0",
> "react": "16.13.1",

can you share a public repo?

**Comment by alextseitlin** [comment]
This is big project... But I can past code here. Will it help? what should I show?

**Comment by bluebill1049** [comment]
> This is big project... But I can past code here. Will it help? what should I show?

as long as you can reproduce the build failed.

**Comment by bluebill1049** [comment]
any update on this?

**Comment by alextseitlin** [comment]
@bluebill1049 making the code smaller for sharing =) Almost done

**Comment by alextseitlin** [comment]
After leaving only the page with the form all works... I will have to dig more and see why I have it on my end

**Comment by bluebill1049** [comment]
ok, let me know if anything I can help, i will close it for now.
