### ISSUE TITLE
V7 Bug - Typescript performance issue on Field Array

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4237]
**Describe the bug**

If 
1. A custom type is created to represent form values
2. The type is of a certain structure
3. The type is used as a generic in `useForm`, 

then typescript compilation will slow down tremendously. 

In larger apps with many useForms that take this generic, Node can run out of heap memory even with 8gb of allocated heap. I've created a code sandbox, but unfortunately, the issue can not really be observed there since we cannot track typescript compilation time (at least to my knowledge). Therefore, I've created a very simple sample project to show the issue.

**To Reproduce**

1. Download the sample project. 
2. Run npm/yarn install
3. Run npm/yarn start
4. Observe the extremely long time it takes for typescript to compute results via react-scripts latest version

**Codesandbox link (Required)**
Use this
[memory-issues.zip](https://github.com/react-hook-form/react-hook-form/files/6006700/memory-issues.zip)

might not help but included regardless. 
https://codesandbox.io/s/summer-sunset-b2wwn?file=/src/App.tsx

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04 LTS

**Additional Context**
I copied over my types exactly. The issue is focused around using an object in a triple nested array. So line 51 in types.ts. If you remove the custom select type here and just use null, then the issue is improved exponentially.

**Comment by bluebill1049** [comment]
can you try with TS `4.2.0-beta`?

**Comment by wdfinch** [comment]
Just tried. Unfortunately, it didn't help. Any ideas on how we can fix this?

**Comment by wdfinch** [comment]
Are you able to reproduce this on your end?

**Comment by bluebill1049** [comment]
It definitely took a lot longer for the type check, but I didn't get into the memory leak issue.

https://user-images.githubusercontent.com/10513364/108445385-68068380-72b0-11eb-9260-e4d919b3c294.mp4

**Comment by wdfinch** [comment]
I think for node to run out of memory you need a larger app with many calls to useForm. Something this small won't cause the error. However it makes developing very difficult as the ts check takes so long now with useForm.

**Comment by wdfinch** [comment]
I guess it's not a memory leak but rather just really poor performance than can cause node to crash.

**Comment by bluebill1049** [comment]
Let me investigate this one. It mostly likes to do with string template literal with the array index.

**Comment by wdfinch** [comment]
Sounds good! Let me know if I can help. This is currently a blocker for me since the performance is so slow.

**Comment by bluebill1049** [comment]
@wdfinch feel free to take a look at our ts definition: https://github.com/react-hook-form/react-hook-form/tree/v7/src/types see if anything you can pick up for the improvement.

**Comment by bluebill1049** [comment]
I have something in mind, will release a beta after work.

**Comment by wdfinch** [comment]
Awesome! Thanks so much!

**Comment by bluebill1049** [comment]
try `react-hook-form@7.0.0-beta.9`.

**Comment by wdfinch** [comment]
Just tested. The issue seems resolved now. Thank you so much for getting this out so quickly. I really appreciate it.

**Comment by wdfinch** [comment]
I noticed you changed this line.

```
type ArrayKey = number | Digits | `${OneToFourDigits}${Digits}`;
````

Does this affect how nested of an array we can use in any way? Is there a limit to the depth?

**Comment by leapful** [comment]
@wdfinch 

The old one allows any child item which is an array in a nested object might have length "0" -> "99"  while the new one allows "0" -> "49" of length.

**Comment by bluebill1049** [comment]
I will update the doc accordingly.

**Comment by wdfinch** [comment]
Ok thanks!

**Comment by wdfinch** [comment]
Unfortunately, I think we need to reopen this issue. While the solution works great for a triple nested array, it seems like the performance issues come back as soon as the array nesting is increased beyond 3. So with a 4 level nested array, I'm experiencing really poor performance again. While performance will degrade with each level of nesting, I would hope this could be linear rather than exponential.

See attached for an example of the issue. I implied the types to be easier to follow. 
[Uploading memory-issues-new.zip…]()

**Comment by wdfinch** [comment]
I guess another solution is just to opt out type checking with any or something at a certain point. I hope we don't need to do this though.

**Comment by wdfinch** [comment]
Additionally, this can cause a typescript error related to `getValues()`.

The error being: 
`Type instantiation is excessively deep and possibly infinite.`

**Comment by bluebill1049** [comment]
I think we probably would have to limit to 3 levels deep check, because 49 ^ 3 * plus all your fields value, that's the root cause with type lagging.

**Comment by bluebill1049** [comment]
I think we are hitting a limitation with TS here.

**Comment by wdfinch** [comment]
I see. Is there a way we could build this into the library or would we just have to warn users that they need to use the `any` type after three levels?

**Comment by bluebill1049** [comment]
@wdfinch I hope you wouldn't need `any`, hopefully, we can stop checking the input name after 3 levels deep. I need to investigate this... you know TS always get my head spinning.

**Comment by wdfinch** [comment]
Sounds good. Hopefully, it can be done. I appreciate you helping me with this issue.

**Comment by wdfinch** [comment]
Also if we are going this route, then it might be best to stop type checking after 2 levels. While 3 is still reasonable, I'm noticing significantly better performance opting out with `any` from 2 levels over 3.

**Comment by leapful** [comment]
@bluebill1049

Since Typescript 4.1 allows to use template literal type by using primitive type, can we just use:

```
declare type ArrayKey = number | `${number}`;
```

instead of 

```
type ArrayKey = number | Digits | `${OneToFourDigits}${Digits}`;
```

Do you see any issue if we switch into this one ?

**Comment by bluebill1049** [comment]
> declare type ArrayKey = number | `${number}`;

Thanks, @leapful can you elaborate this with an example?

**Comment by leapful** [comment]
@bluebill1049 

I've changed the type definition in line 66 of types/utils.ts

https://github.com/react-hook-form/react-hook-form/blob/v7/src/types/utils.ts#L60-L66

**Comment by bluebill1049** [comment]
so we let the user declare the `ArrayKey`? can we have a default tho?

**Comment by bluebill1049** [comment]
I really like this idea if it's configurable and still, we can have a default, we can make the default number a lot smaller as well.

**Comment by bluebill1049** [comment]
oh! `declare type ArrayKey = number | `${number}`;`

**Comment by bluebill1049** [comment]
you want to send a PR since it's your solution, we can push a beta to see if that solves the issue.

**Comment by leapful** [comment]
@bluebill1049 

Okie, I will open a PR.

**Comment by bluebill1049** [comment]
@leapful with the amount of help and contribution, would you consider joining our team?

**Comment by wdfinch** [comment]
Thanks @leapful!

**Comment by wdfinch** [comment]
Since you brought it up, how does one get to join the react-hook-form team @bluebill1049? I would be interested.

**Comment by leapful** [comment]
@bluebill1049 @wdfinch 

PR is created at https://github.com/react-hook-form/react-hook-form/pull/4248

> @leapful with the amount of help and contribution, would you consider joining our team?

I would be glad to join the team.

**Comment by bluebill1049** [comment]
@wdfinch as long as someone contributes often to the codebase or having good knowledge around the lib and help many others. 👍

**Comment by bluebill1049** [comment]
`react-hook-form@7.0.0-beta.11` is releasing.

**Comment by wdfinch** [comment]
Just had a chance to check out the new build. Looks good to me. It seems like the performance issues are resolved. Thanks again @leapful for the fix here. Really appreciate it. I think we can close this for now.

**Comment by bluebill1049** [comment]
That's awesome to hear! thanks for the confirmation @wdfinch and @leapful's fix.
