### ISSUE TITLE
Build error with React import in useForm.d.ts

### ISSUE THREAD

**Issue by LukasVerstraete** [react-hook-form/react-hook-form#424]
**Describe the bug**
We are having build errors in our project when using the latest version of react-hook-form.
ERROR in [at-loader] ./node_modules/react-hook-form/dist/useForm.d.ts:1:8 
TS1192: Module '"{path to node_modules}/node_modules/@types/react/index"' has no default export.

I think any project using typescript will have this error during build and that the issue has something to do with the following line (useForm.d.ts:1:8).

`import React from 'react';`

I'm not sure but I think this can be easily fixed by replacing it with the following.
 
`import * as React from 'react';`
or maybe even 
`import {BaseSyntheticEvent} from 'react';`
Since this is the only reason React is imported in the file.

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome

I am currently on version 3.26.2 of react-hook-form.

**Comment by bluebill1049** [comment]
thanks, @LukasVerstraete can you test out this beta, see if it's fixing your issue?

`3.26.3-beta.1`

**Comment by LukasVerstraete** [comment]
Yes! This has fixed the issue. Thank you for the quick response.

**Comment by bluebill1049** [comment]
no worries, I will release the fix in the next patch. in the meantime, you can keep using this beta version.

**Comment by bluebill1049** [comment]
by the way please consider leaving a star to support this lib <3 👍

**Comment by avtarnanrey** [comment]
I was having this same issue because of my Typescript package version was lower than the **React Hook Form** typescript version 3.7.3

**Comment by bluebill1049** [comment]
@LukasVerstraete can you share a screenshot of the actual error?

**Comment by sstraus** [comment]
Same problem with @4 and @5

'react-hook-form' does not contain a default export (imported as 'useForm').

**Comment by bluebill1049** [comment]
`import { useForm } from 'react-hook-form'` @sstraus

**Comment by akoh-victor** [comment]
I have tried all the suggested solution but the error is still there 
my typescript version is 4.1.2 while my react-hook-form version is 7.15.1. Please i will really appreciate any assistance i can get

**Comment by bluebill1049** [comment]
what's the error log? @akoh-victor

**Comment by akoh-victor** [comment]
thanks i have solved it. sorry i've been busy production issues

**Comment by ErrettB** [comment]
Can you please post the solution to your error?
