### ISSUE TITLE
isDirty working inconsistently when using formControl

### ISSUE THREAD

**Issue by rweller59** [react-hook-form/react-hook-form#4246]
In some components, the isDirty flag only switches on TextField values, not on FormControlLabel elements. The dirtyFields seems to always display appropriately.

**Difficult To Reproduce**
In the example [codesandbox](https://codesandbox.io/s/mystifying-mclean-w78kl?file=/src/App.js:273-289), the isDirty flags works as expected with changes in either field triggering true. When I paste this same function into my application and render from another component, the isDirty flag does not change with the formControlLabel switch but works correctly with the TextField.

I all cases, dirtyValues indicates the correct dirty variables, i.e., I can mimic the isDirty field by using dirtyValues.length > 0

**Expected behavior**
isDirty should show true when either input is changed from default.

seems to work the same with Chrome and Firefox.

**Comment by bluebill1049** [comment]
I can solve the problem if you can reproduce it. none of these need to go into `useEffect`  as well

```
useEffect(() => {
    const { dirtyFields, isDirty } = formState;
    const data = {
      isDirty: isDirty,
      dirtyFields: dirtyFields,
      watch: watch()
    };
    console.log(
      "useEffect isDirty = " +
        isDirty +
        ", dirtyFields = " +
        JSON.stringify(dirtyFields)
    );
  }, [formState, watch]);
```

**Comment by rweller59** [comment]
will keep trying to re-produce in sandbox. any ideas on what to look for in parent component(s) that could potentially cause some issues?

**Comment by rweller59** [comment]
I deleted packages and did npm install. issue went away.
In my app, the useEffect also calls a parent function on form data change. I put the code into useEffect to eliminate the error 

'Cannot update a component while rendering a different component.'

**Comment by rweller59** [comment]
had to delete and re-install npm packages in order to get rid of issue. I also had an additional defaultValue property so isDirty would show true when dirtyValues.length===0; 

My useEffect is calling a parent component function which caused some issues when I put this code outside of useEffect.

**Comment by bluebill1049** [comment]
ok, thanks for the update.
