### ISSUE TITLE
Cant update input values with live data after changes. 

### ISSUE THREAD

**Issue by alextseitlin** [react-hook-form/react-hook-form#4250]
**Describe the bug**
Cant update input values with live data after changes. 

**What I am trying to do**
In my project I have a user detail page with user inputs on one side and the list of the users on the other. When I click a new user, the user data appears in the inputs. I make changes and click another user. The issue is that as soon as I make a change that field is not updating any more.

This is a simplified versions but the the issue is visible
https://codesandbox.io/s/react-hook-form-default-issue-vl2s9

**To Reproduce**

1. Make any edit to the input value
2. click "new person"
3. Value will not change

And this way works

1. Refresh the page and do not make any edit to the input value
2. click "new person"
3. Value will change

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-default-issue-vl2s9

**Additional context**
I am using nextJS

**Comment by bluebill1049** [comment]
use setValue: https://react-hook-form.com/api#setValue it's an uncontrolled input.

**Comment by alextseitlin** [comment]
@bluebill1049 amazing! Thanks
