### ISSUE TITLE
V7 register function destructuring return null for "name" tag in SSR

### ISSUE THREAD

**Issue by svo393** [react-hook-form/react-hook-form#4253]
**Describe the bug**
If the page is rendered on server, "name" tag of registered field input gets value "null" which breaks the form.

**To Reproduce**
1. Go to the sandbox
2. Refresh internal browser just to be sure it's SSR
3. Type some characters in the input field
4. Console (which executes watch()) doesn't show anything

**Codesandbox link**
[https://codesandbox.io/s/register-bug-ostw4?file=/pages/index.js](https://codesandbox.io/s/register-bug-ostw4?file=/pages/index.js)

**Expected behavior**
The field should be registered with name "field".

**Additional context**
A workaround would be to manually set name tag after register function.

**Comment by bluebill1049** [comment]
fixed in beta.12 👍
