### ISSUE TITLE
The dirtyField is wrong when append the data with array with useFieldArray.

### ISSUE THREAD

**Issue by koichiba** [react-hook-form/react-hook-form#4256]
**Describe the bug**
The dirtyField is wrong when append the data with array with useFieldArray.

**To Reproduce**
1. Go to https://codesandbox.io/s/epic-ritchie-ibuvj?file=/src/App.js
2. Click on `Add` button
3. See console

**Codesandbox link**
https://codesandbox.io/s/epic-ritchie-ibuvj?file=/src/App.js

**Expected behavior**
I want the dirty field to be undefined.

**Screenshots**

| Wrong | Expected behavior |
| --- | -- |
| 6.11.4 | 6.11.3 |
| ![image](https://user-images.githubusercontent.com/12792276/108690490-c5633480-753d-11eb-8296-c240af9d100f.png) | ![image](https://user-images.githubusercontent.com/12792276/108690587-e2980300-753d-11eb-8577-79a0bdd9fef9.png) |

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 88.0.4324.182

**Additional context**
It does not occur in react-hook-form version 6.11.3.
React-hook-form version occurs after 6.11.4.

Is this a bug?

**Comment by bluebill1049** [comment]
6.11.4 is expected.
<img width="711" alt="Screen Shot 2021-02-22 at 8 55 24 pm" src="https://user-images.githubusercontent.com/10513364/108692071-49beb300-7550-11eb-9050-86182f4fb649.png">

**Comment by koichiba** [comment]
That's right. thanks you.

So if you put data in an array, do you expect it to not appear in the changes?
![image](https://user-images.githubusercontent.com/12792276/108692816-71a61a80-7540-11eb-96c0-b6f657e3e8a4.png)

**Comment by bluebill1049** [comment]
I expect the `user` object to be a field array to work properly.

**Comment by koichiba** [comment]
Thank you for your answer.
