### ISSUE TITLE
Bug V7 - setValue issues with array

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4265]
**Describe the bug**
I'm not sure if this is a bug or just related to shallow equality checks. My issue is I would like to use `setValue` to set an array to a new array value. Specifically, I would like to remove the current last element of the array and then use `setValues` to update the form values to this new array. On the sandbox, I can get this work once, but subsequent attempts don't work. Can anyone explain if this is a bug or just something I am doing wrong here? 

**To Reproduce**

1. Go to the sandbox
2. Click add element a few times to add some elements
3. Click remove element a few times and notice it only works the first time

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-bim91?file=/src/index.js:689-723

**Expected behavior**
I know that in the past fields and form values were not always in sync. From our discussion in the V7 RFC, I thought this was improved a bit after beta release 11. Am I just facing a limitation of the library?

**Comment by bluebill1049** [comment]
patch in the next beta.

**Comment by wdfinch** [comment]
Thanks for the quick patch. Unfortunately, I'm still noticing this issue in the code sandbox after upgrading beta 14.

**Comment by wdfinch** [comment]
Can we reopen this?

**Comment by bluebill1049** [comment]
u sure? https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-l93j3?file=/src/index.js

**Comment by wdfinch** [comment]
Weird. In my sandbox which is the same, it doesn't work but yours works fine.

https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-bim91?file=/src/index.js:689-723

maybe this is some issue with code sandbox box using the older version. Anyway, yours works so that good enough me.
