### ISSUE TITLE
Bug V7 - Watched values of a nested field array resets when moved

### ISSUE THREAD

**Issue by samantha-wong** [react-hook-form/react-hook-form#4269]
**Describe the bug**
Watched values of a nested field array resets when moved  

**To Reproduce**

1. Click Edit and change the values **This is a heading**, **Hello World** and **Foo bar** to something else
2. Click **move down**

Notice the heading is okay, but the new values edited reverts back to Hello World and Foo bar.
I've also tried providing and not providing a default value.

**Codesandbox link (Required)**
https://codesandbox.io/s/brave-golick-pvr4b?file=/src/App.js:1262-1267

**Expected behavior**
Submitted form values are correct, but watched values shouldn't reset

**Comment by bluebill1049** [comment]
hey @samantha-wong those `id` is suspecious:

```
{
      sections: [
        {
          data: {
            heading: "This is a heading",
            features: [
              { id: "1", title: "Hello World" },
              { id: "2", title: "Foo bar" }
            ]
          }
        },
        {
          data: {
            heading: "This is a second heading",
            features: [
              { id: "4", title: "One" },
              { id: "5", title: "Two" }
            ]
          }
        }
      ]
    }
    
```

you are not meant to overwrite `id` from `field.id`, if you want to use your own `id`, you can change `keyName` to something else.

<img width="550" alt="Screen Shot 2021-02-24 at 9 46 35 pm" src="https://user-images.githubusercontent.com/10513364/108989512-c46f0600-76e9-11eb-8274-53ca55626ea7.png">

**Comment by samantha-wong** [comment]
I removed the suspicious ids sorry, but the issue remains. No worries, have a good night!

**Comment by bluebill1049** [comment]
looks like the issue is due to `useWatch` usage:

take a look at my example: https://codesandbox.io/s/determined-heisenberg-ch16i?file=/src/App.js

**Comment by samantha-wong** [comment]
I'm afraid listening to all the sections would make our project very slow, but looks like the issue was because our Preview component was rendered before the form!!! (updated CSB). Thanks for looking and sorry for wasting your time 🙏

**Comment by bluebill1049** [comment]
no worries at all @samantha-wong but don't use `useWatch` hook inside the render.
