### ISSUE TITLE
I suggest to add « react-hook-form » vs « formik 2.0 » section in faqs

### ISSUE THREAD

**Issue by harobed** [react-hook-form/react-hook-form#427]
Hi,

I suggest to add « react-hook-form » vs « [formik 2.0](https://www.npmjs.com/package/formik) » section in [faqs](https://react-hook-form.com/faqs).

Best regards,
Stéphane

**Comment by bluebill1049** [comment]
thanks @harobed I will update that tonight :) it's pretty much controlled vs uncontrolled and react hook form is purely build by hook too.

**Comment by bluebill1049** [comment]
actually I am going to leave my answer here and we can all contribute to the answer.

**Comment by bluebill1049** [comment]
**react-hook-form and Formik?**

First of all, both libs try to solve the same problem which is making build form experience easy and great. However, there are fundamental differences between the two, `react-hook-form `is built with uncontrolled input in mind and try to provide your form with the best performance with least re-render if possible. On top of that, react-hook-form is built by React Hook and used as hook, which means there is no Component for you to `import` and consume except `FormContext` (which is React Context behind the scenes). At the end of the day, the choice is yours and some of the reasons for you to decide. 

(Order: React Hook Form, Formik)
1. uncontrolled vs controlled. 
2. minimum re-render vs re-render according to local state (as you type in the input)
2. pure hooks API vs Component API + hooks API
3. new player in town vs well-established/most popular form lib in the community

**Conclusion:** 
I believe both lib/solution can make and achieve great results in form building, and both libs are trying to help developers around the world to make form building life easier and fun.

**Comment by bluebill1049** [comment]
let me know what you guys think of the answer as well before I updated it on the website.

**Comment by bluebill1049** [comment]
What about the lib learning curve? IMHO react hook form is very easy to use because it's built by an average developer hahaha and tries to make simple for myself and others.

**Comment by bluebill1049** [comment]
@harobed you want to migrate this issue to the website repo? I am going to close it here for now, cause it's not an issue.

**Comment by Skaronator** [comment]
You can actually move issues to other repos https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository
