### ISSUE TITLE
Delayed Remove item in Field Array is causing issues while submiting data

### ISSUE THREAD

**Issue by priyen27** [react-hook-form/react-hook-form#4271]
**Describe the bug**

I am wrapping remove function(received from useFieldArray) with setTimeOut. Ui is updated well when remove function is called, but while submiting, form is returning incorrect data. I have edited an exisiting codesandbox.

**To Reproduce**

1. open the sandbox : https://codesandbox.io/s/react-hook-form-usefieldarray-forked-k6fqi?file=/src/index.js
2. click on append to add second item
3. click on delete button of the first item
4. click on submit
5. check console

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-k6fqi?file=/src/index.js

**Expected behavior**
In console: Array should have only 1 object.

**Actual output** 
In console: Array has 2 objects.

**Screenshots**
![image](https://user-images.githubusercontent.com/79581381/109002277-012c0480-76cc-11eb-96e3-ccf43d19999a.png)

**Desktop (please complete the following information):**

- OS:  Macos
- Browser: Chrome
- Version: 88.0.4324.192 (Official Build) (x86_64)

**Comment by bluebill1049** [comment]
for async action please change to `Controller`: https://codesandbox.io/s/react-hook-form-usefieldarray-forked-2vg1v

This issue with async action is getting resolved at v7: 

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-mbhbv?file=/src/index.js
