### ISSUE TITLE
formState.touched not set by Controller

### ISSUE THREAD

**Issue by OW-Coder2** [react-hook-form/react-hook-form#4273]
**Describe the bug**
Controller does not add field to touched array when value is changed.

**To Reproduce**

```
<Controller
  name="ReactSelect"
  control={control}
  render={({ value, onChange }) => (
    <ReactSelect
      options={options}
      isClearable
      value={value}
      onChange={onChange}
    />
  )}
/>
```

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-forked-wnl65?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
After change: formState.touched = [ReactSelect : true]

**Desktop (please complete the following information):**

- Browser chrome
- Version 6.15.4

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-controller-forked-qk1hm

- missing `onBlur` props on the Controller.
