### ISSUE TITLE
Prefilling form with complex data

### ISSUE THREAD

**Issue by 18601673727** [react-hook-form/react-hook-form#428]
### Description:
Hi @bluebill1049,

I've encountered an issue while trying to mutate the dynamically generated fields, giving this [code](https://codesandbox.io/embed/react-hook-form-array-fields-v1jk7) which based upon this #371. It turns out `setValue` is not properly updating the form or there's any better way to achieve?

### Steps to reproduce:
1. Open https://codesandbox.io/embed/react-hook-form-array-fields-v1jk7
2. Click "Add Person"
3. Click "Submit"
4. Take a look at the "Console", state `selected` updated, form data doesn't

### Version:
"react-hook-form": "3.26.2"

**Comment by bluebill1049** [comment]
hey @18601673727 , `setValue` doesn't support `object` at this stage, but you can compose a function to do what you want tho.

**Comment by bluebill1049** [comment]
by the way, have you tried to use `reset`https://react-hook-form.com/api/#reset

**Comment by 18601673727** [comment]
@bluebill1049 , Thanks for the suggestion on `reset` but I had passing `useState` hook tuple down to the component tree in this case for now..

**Comment by bluebill1049** [comment]
maybe stick with setValue and wrap it up with a function for now, until we have a better solution for it and it's on the todo list for us.

**Comment by 18601673727** [comment]
Yea, I don't wanna use `reset` because I'm using it for #181 scenario as we speaked.

**Comment by bluebill1049** [comment]
i will close this issue for now but have improve setValue on the roadmap so please keep an eye on it.

https://github.com/react-hook-form/react-hook-form/projects/1

**Comment by 18601673727** [comment]
Hey @bluebill1049 , sorry for commenting on closed issue here but I do have to check in again for asking any updates on this?

**Comment by bluebill1049** [comment]
@18601673727 i think you can use `reset` now, it has the option to not populate the `formState`.

**Comment by 18601673727** [comment]
@bluebill1049 Great, thanks for the INSTANT reply, I'll go through my old project and give feedback on that(if any) as soon as I can.

**Comment by 18601673727** [comment]
Hey @bluebill1049 , It turns out that I couldn't find the right option you mentioned above, tried all combinations..

codesandbox: https://codesandbox.io/s/react-hook-form-array-fields-v1jk7

`setValue` still not working btw..

**Comment by 18601673727** [comment]
Well, fixed by refactor the `addPersonHandler` to:
```js
  const addPersonHandler = newFriend => {
    const formData = getValues();
    reset({
      ...formData,
      friends: getValues("friends").concat([newFriend])
    });
  };
```
but I'm not sure this is the best approach to do so..

**Comment by bluebill1049** [comment]
hey @18601673727 I think `setValue` is made for a single input value update (just as the name suggested), I think what you did with `reset` is fine unless we will introduce `setValues` but then it overlaps with `reset` quite a bit.

**Comment by 18601673727** [comment]
Yes, it does @bluebill1049

IMHO, `reset` should be vaguely considered as multiple `setValue()`s in regard to follow what hooks generally looks like right?
```
const [value, setValue] = useState()
```
So, I would like to suggest moving the values setter role out of `reset()` and creating a new `setValues()` function to do the advanced `setValue()` job, and don't forget we've got `getValues()` as values getter already.
