### ISSUE TITLE
Incorrect type for name parameter in Controller.render

### ISSUE THREAD

**Issue by bentefay** [react-hook-form/react-hook-form#4281]
**Is your feature request related to a problem? Please describe.**

In the function passed to `Controller.render`, TypeScript is inferring `field.name` to have type `any` when it should be a union of the keys in `TFieldValues`.

**Describe the solution you'd like**

Is this possibly because `ControllerRenderProps.name` has type `FieldName<Control<TFieldValues>>` when it should have `FieldName<TFieldValues>`?

Link to the source:

https://github.com/react-hook-form/react-hook-form/blob/413c4aa35d8b716945a7439bb0e76bfb6bc653de/src/types/props.ts#L34

**Comment by bluebill1049** [comment]
Thanks, @bentefay I think we have some issue with the Control type, which semi-related to https://github.com/react-hook-form/react-hook-form/issues/2887 it's a bit convoluted for v6, but we are already addressed them in v7.

**Comment by bentefay** [comment]
Ok, great to hear @bluebill1049. Sorry for the unnecessary issue!

**Comment by bluebill1049** [comment]
It's not unnecessary at all (Thanks for point this out). in fact, let me share you with a working version with v7 with the correct name type check. hold on, I am creating one with CSB.

**Comment by bluebill1049** [comment]
Try this: https://codesandbox.io/s/intelligent-nobel-n25qr?file=/src/App.tsx

this is what gets me excited for V7.

**Comment by bentefay** [comment]
I love your library, and I'm very excited for v7! It can't come soon enough. One thing I just noticed playing with the sandbox is that `field.name` appears to still be of type string. It could probably be the actual name string literal, right?

**Comment by bluebill1049** [comment]
<img width="500" alt="Screen Shot 2021-02-25 at 7 46 43 pm" src="https://user-images.githubusercontent.com/10513364/109127138-3145d700-77a2-11eb-99f1-2c4e60f32226.png">

Thanks @bentefay you are right! fixing that.
