### ISSUE TITLE
V7 Bug - field array values being removed automatically 

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4282]
**Describe the bug**
If an element is added to a field array and the field array input is not mounted, then the field value will be removed from form values without any user interaction. It will successfully be added initially. `fields` will still have the correct values but `formValues` will not.

**To Reproduce**

1. Go to the sandbox
2. Click on the add element button
3. Click on the get latest values button
4. Notice that the values object is an empty object and is missing the array element
5. Observer that the field value is briefly part of form values via the `watch` call

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-bim91?file=/src/index.js

**Expected behavior**
I expect the field array values to be kept in form values even if the element is not currently mounted. I have a situation where I am conditionally rendering parts of the field array and this is causing me to lose form values.

**Comment by bluebill1049** [comment]
`append` will only create a temp value, the input itself then will need to be `registered`.

**Comment by wdfinch** [comment]
I see. I thought we were trying to move away from this model and keep field array values more in sync with form values. I have a situation where each element of a field array is a wizard form. Therefore, when I append my starting values, I lose a bunch of the values for sections that are hidden.

Is there any downside to keeping the values in `formState`? I think it's kind of deceptive and error-prone to have them in there only on the first render. I'd rather have them stay all the time or never personally.

**Comment by bluebill1049** [comment]
Let me look into that and give you a definite answer. 👍

**Comment by wdfinch** [comment]
The bigger issue here is I need to way to access and modify all my current `formValues`. With regular form values, I have all the tools I need with what's provided by `useForm` and it's awesome to use. With fields arrays, it's a struggle. The issues are:

1. `fields` contains the correct values after operations (append, remove, etc.) but it is not controlled. Therefore, I can't rely on it for up-to-date values. It's also harder to access in complex forms since there is no `useFieldArrayContext`.

2. `getValues()` contains the up-to-date values but is constantly missing field array values for various reasons (operations not applied there, the issues I described above, etc.)

My current solution is to get use both `fields` and `formValues` to search for the current state of the `formValues`. This adds a ton of extra code and logic over time. 

I personally think the best solution would be to have `formValues` be the single source of truth (always in sync with the operations we use). I would also like to see us move away from requiring a field to be mounted in order to have it appear in `formValues`, set values, etc. This has mostly been solved with regular form input, but field arrays still have some issues like this.

**Comment by bluebill1049** [comment]
Thanks for your feedback @wdfinch.

**Comment by wdfinch** [comment]
I guess right now it seems like `fields` and `formValues` are separate objects with separate values. I think it would be better if fields were a snapshot of form values that was uncontrolled. Updates like `append`, `remove`, etc. would go to `formVaues` first, and then `fields` would take the latest snapshot.

**Comment by wdfinch** [comment]
I guess this might be more appropriate in the V7 RFC as it's more of a library change than a bug at this point. I can start a discussion there if you would like and close this. What should I do?

**Comment by bluebill1049** [comment]
@wdfinch Let me take a look at this tonight, I have a couple of ideas, I just need to test them out. what you state above are all valid and constructive feedbacks.

**Comment by wdfinch** [comment]
Ok thank you!

**Comment by bluebill1049** [comment]
works: https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-0d67j?file=/src/index.js

**Comment by wdfinch** [comment]
Thanks so much! Seems to be working now.
