### ISSUE TITLE
useFieldArray `append` doesn't work with files

### ISSUE THREAD

**Issue by mordechaim** [react-hook-form/react-hook-form#4286]
**Describe the bug**
When `append`ing a file in a field array, I find just a stub object with an ID.

**Codesandbox link (Required)**
https://codesandbox.io/s/eloquent-cache-dhus3?file=/src/App.js

**Expected behavior**
`fields` should output the exact same as `appending`

**Comment by bluebill1049** [comment]
This is the no usage we support. follow the doc for useFieldArray https://react-hook-form.com/api#useFieldArray

if you want to store a file in an array, use an array like `name` field

**Comment by mordechaim** [comment]
> This is the no usage we support. 
Can you please elaborate? Do you mean `File` is a special case in `useFieldArray`? Can't seem to find this in the docs.

**Comment by bluebill1049** [comment]
look at the example and compare with you CSB

```
function Test() {
  const { control, register } = useForm();
  const { fields, append, prepend, remove, swap, move, insert } = useFieldArray({
    control, // control props comes from useForm (optional: if you are using FormContext)
    name: "test", // unique name for your Field Array
    // keyName: "id", default to "id", you can change the key name
  });

  return (
    {fields.map((field, index) => (
      <input
        key={field.id} // important to include key with field's id
        name={`test[${index}].value`}
        ref={register()} // register() when there is no validation rules 
        defaultValue={field.value} // make sure to include defaultValue
      />
    ))}
  );
}
```
