### ISSUE TITLE
Old default values keep persisting when clearing an array (with useFieldArray)

### ISSUE THREAD

**Issue by DirkWolthuis** [react-hook-form/react-hook-form#4290]
**Describe the bug**
In our application we have a section where user can edit a checkDigitSchema, in this schema they can choose for a static flow, or a dynamic flow. Dynamic is just a couple of fields that need to be filled, but the static one is a array of numbers they can fill. If they load a existing checkDigitSchema, the array of numbers may be filled and are passed as defaultValues in the useForm hook. After switching from static to dynamic and back to static, the number values are cleared by using `setValue("manipulationSequence.sequenceDetails.numbers", []);`. But if a user clicks the button to add a new field (by using append, the field is filled with the old value (the number from the defaultValues array). 

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-zpkf6?file=/src/index.js
2. Click on on `switch mode` twice
3. Click on `new`
4. See the old value in the input field

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-zpkf6?file=/src/index.js

**Expected behavior**
If I use a setValues on a field, I expect the useFieldArray to clear the values.

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
-  "version": "6.14.2",

**Comment by bluebill1049** [comment]
you are missing `defaultValue`:

```
<Controller
          name={`numbers[${index}].value`}
          control={control}
          defaultValue={field.value}
          render={({ onChange, onBlur, value, name }) => (
            <input
              name={name}
              onChange={onChange}
              value={value}
              onBlur={onBlur}
            />
          )}
        />
```
