### ISSUE TITLE
`useEffect` not triggering when `errors` object updates on `reValidate`

### ISSUE THREAD

**Issue by ryanwalters** [react-hook-form/react-hook-form#4299]
**Describe the bug**
When subscribing to changes to `errors` within `useEffect`, the callback does not fire when the `errors` object updates on `reValidate`.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-useform-template-forked-yfrwp
2. Click on "Submit"
3. View the console, you should see an error for `LastName` (something like `{LastName: {…}}`)
3. Type something into the `LastName` field
4. The error in the UI disappears

**Expected behavior**
View the console, you should see an empty `errors` object after it was updated

**Actual behavior**
View the console, nothing has been logged

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 88.0.4324.190

Apologies if this was asked elsewhere already, I couldn't find an Github issue regarding this specific issue.

**Comment by bluebill1049** [comment]
use `formState` for dep instead.

**Comment by ryanwalters** [comment]
That works for my use case, thanks! 

Just out of curiosity, is it documented somewhere that `errors` won't be updated in a `useEffect` for certain scenarios? It seems unexpected.

**Comment by bluebill1049** [comment]
<img width="963" alt="Screen Shot 2021-02-27 at 10 12 19 am" src="https://user-images.githubusercontent.com/10513364/109365025-47f44700-78e4-11eb-8655-b1393796f05d.png">

**Comment by ryanwalters** [comment]
Awesome, thank you!

**Comment by DamianPereira** [comment]
Hi! When using the whole formState as a dependency, I'm getting the useEffect executed on unrelated scenarios. Even re-renders for unrelated reasons will trigger the useEffect when using formState as dependency. Check out this example repo here: https://codesandbox.io/s/formstate-re-render-example-10rt1?file=/src/index.js

Clicking force render will make the useEffect hook run and console log the errors, even if errors did not change, and even if none of the fields of formState changed. Not sure about how the proxy in formState affects this.

**Comment by bluebill1049** [comment]
> Hi! When using the whole formState as a dependency, I'm getting the useEffect executed on unrelated scenarios. Even re-renders for unrelated reasons will trigger the useEffect when using formState as dependency. Check out this example repo here: https://codesandbox.io/s/formstate-re-render-example-10rt1?file=/src/index.js
> 
> Clicking force render will make the useEffect hook run and console log the errors, even if errors did not change, and even if none of the fields of formState changed. Not sure about how the proxy in formState affects this.
> 
> use-what-changed is used in the example to show the deps change.

if you want to watch an individual one, use can consider some useDeepCompare hook, i believe kent has created one.

**Comment by DamianPereira** [comment]
So until useFormState is released as part of v7 there is no way of watching only 1 value from formState right?
