### ISSUE TITLE
V7 watch bug. maybe?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [react-hook-form/react-hook-form#4301]
**Describe the bug**
I was play around v7 and noticed something unexpected, it might be a bug?

![image](https://user-images.githubusercontent.com/33362998/109374171-eb0f7700-7878-11eb-9e5b-963005e4bade.png)

**To Reproduce**

2. type a
3. delete a
4. See output

**Codesandbox link (Required)**
https://codesandbox.io/s/material-demo-forked-pifom?file=/demo.tsx

**Expected behavior**

```
value 
{name: "1"}
value 
{name: undefined}
```

**Comment by bluebill1049** [comment]
it's due to sending `undefined` to `useController`. here is a working version: 

https://codesandbox.io/s/material-demo-forked-syih7?file=/demo.tsx
