### ISSUE TITLE
isDirty remaining false 

### ISSUE THREAD

**Issue by kashifnazar** [react-hook-form/react-hook-form#4303]
**Describe the bug**
We are have a `users` array in our form. Even when the value of this attribute changes, the `isDirty` flag remains false.

**Codesandbox link (Required)**
https://stackblitz.com/edit/react-iz8muh?devtoolsheight=33&file=src/App.js

**Steps to reproduce**
In the Codesandbox example, changing the values in the one of the fields updates the form value. However, `isDirty` flag stays false.

**Expected behavior**
`isDirty` should be set to true when the value of the form is different from the defaultValues.

**Comment by bluebill1049** [comment]
you have to convert that into 3 separate fields with `Controller`.

this is what you try to compare each onChange below: 

```
`Kashif_whatever_you_type` === [
    { id: 1, name: "Kashif" },
    { id: 2, name: "Yakaya" },
    { id: 3, name: "Ahmad" }
  ]
```

**Comment by Mendoza920** [comment]
This is Yadira
I need help

**Comment by kashifnazar** [comment]
> you have to convert that into 3 separate fields with `Controller`.
> 
> this is what you try to compare each onChange below:
> 
> ```
> `Kashif_whatever_you_type` === [
>     { id: 1, name: "Kashif" },
>     { id: 2, name: "Yakaya" },
>     { id: 3, name: "Ahmad" }
>   ]
> ```

Thanks for your response @bluebill1049. We are actually trying to create a Controller out of [ag-grid](ag-grid.com) by leveraging its inline editing feature; such that when a value is updated in ag-grid, the React Hook Form detects this dirty state.

**Comment by bluebill1049** [comment]
each change should update the entire input group then.

```
setState([
    { id: 1, name: "Kashif" },
    { id: 2, name: "Yakaya" },
    { id: 3, name: "Ahmad" }
])
```

treat your input as a group input.

**Comment by kashifnazar** [comment]
@bluebill1049 - This is what the intentions are. However, even when the value of user changes, `isDirty `flag is `false`.

**Comment by bluebill1049** [comment]
here is a quick example: https://codesandbox.io/s/musing-leavitt-35e0e?file=/src/App.js for what I meant above.
