### ISSUE TITLE
mode onBlur not work in React Native

### ISSUE THREAD

**Issue by davideddr** [react-hook-form/react-hook-form#431]
Maybe is related to this issue #23 but in React Native version **"0.61.2"** when i change the mode to **"onBlur"** the form don't trigger the validation when i change the input focus.
I tried with the example in the documentation:
```js
import React from 'react';
import {Alert, Text, SafeAreaView, View, TextInput, Button} from 'react-native';
import useForm from 'react-hook-form';
export default function App() {
  const {register, setValue, handleSubmit, errors} = useForm({
    mode: 'onBlur',
  });
  const onSubmit = data => Alert.alert('Form Data', data);

  return (
    <SafeAreaView style={{flex: 1}}>
      <Text>First name</Text>
      <TextInput
        ref={register({name: 'firstName'}, {required: true})}
        onChangeText={text => setValue('firstName', text, true)}
      />
      {errors.firstName && <Text>This is required.</Text>}

      <Text>Last name</Text>
      <TextInput
        ref={register({name: 'lastName'})}
        onChangeText={text => setValue('lastName', text)}
      />

      <View>
        <Button title="SUBMIT" onPress={handleSubmit(onSubmit)} />
      </View>
    </SafeAreaView>
  );
}
```

**Comment by bluebill1049** [comment]
<img width="922" alt="Screen Shot 2019-10-29 at 10 21 35 pm" src="https://user-images.githubusercontent.com/10513364/67762868-808ad300-fa9a-11e9-8c4c-df9198b3247d.png">

hey @davideddr for react native you have to attach onBlur manually.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#setValue you can trigger validation while set value as well

**Comment by davideddr** [comment]
> https://react-hook-form.com/api#setValue you can trigger validation while set value as well

I tried this in the example but the validation onBlur was not triggered.



> <img alt="Screen Shot 2019-10-29 at 10 21 35 pm" width="922" src="https://user-images.githubusercontent.com/10513364/67762868-808ad300-fa9a-11e9-8c4c-df9198b3247d.png">
> 
> hey @davideddr for react native you have to attach onBlur manually.

Sorry, I didn't see the tooltip. 😅
I added onBlur prop in my TextInput and now it works:
```js
<Text>First name</Text>
<TextInput
   ref={register({name: 'firstName'}, {required: true})}
   onChangeText={text => setValue('firstName', text, true)}
   onBlur={async () => await triggerValidation()}
/>
{errors.firstName && <Text>This is required.</Text>}
```

**Comment by nboliver** [comment]
Using React Native, I am finding that `formState.isValid` only updates on blur when `mode: 'onBlur'` is set, even though this seems to contrary to what the docs suggest. Adding `onBlur` prop to the input can validate the input, but doesn't update the `formState`.  Is that the intended functionality?

**Comment by bluebill1049** [comment]
Hey @nboliver , `mode` is only available to DOM API (i will imporve the doc website in the near future)
<img width="977" alt="Screen Shot 2019-11-03 at 8 38 13 am" src="https://user-images.githubusercontent.com/10513364/68077310-9b03da00-fe15-11e9-9e5b-aa829d9938dc.png">
. if you want to update `formState` during onChange, you can do `onChange={e => setValue('name', e.target.value, true)}`

**Comment by ianmartorell** [comment]
Hey @bluebill1049, if I use `onChange={e => setValue('name', e.target.value, true)}`, the form will validate on every `onChange`, but I want the validation to occur only `onSubmit`, just like the default DOM API mode. How can we achieve that on React Native?

**Comment by bluebill1049** [comment]
@ianmartorell I believe if you are using `Controller`, it will respect the `mode` which i should update the doc as well. i will leave a note to myself.

**Comment by ianmartorell** [comment]
@bluebill1049 You are right! I was using the `register` function with regular `TextInput` components instead of using `Controller`. Thank you for the super quick reply!
