### ISSUE TITLE
Cross Field Validation - formstate.isValid doesn't update after correcting error

### ISSUE THREAD

**Issue by knoefel** [react-hook-form/react-hook-form#4310]
**Describe the bug**
I have created a date interval that implements cross field validation.  I check against the user input in each field to see if the "From" date is before the "To" date. Everything works great when I correct an error in the field where it was triggered.

What unfortunately does not work is the following use case: If I provoke an error in one of the two fields and then make the correction in the other field. See "Steps to Reproduce" for further information.

The curious thing is that the error in the `errors` object is removed, so the `errors` object is an empty object. The `formState`, however, remains invalid.

**To Reproduce**

1. Go to [Codesandbox](https://codesandbox.io/s/react-hook-form--cross-field-validation-bug-kwbdp?file=/src/index.js)
2. Set the "To" date to a value before the "From" date
3. `errors` object now has one error and the formState is invalid
4. Set the "From" date to a value before the just changed "To" date
5. The `errors` object is now empty, but the `formState` remains invalid

The `formState` only changes back to valid, if the "To" date is updated again.

**Codesandbox link**
[Codesandbox](https://codesandbox.io/s/react-hook-form--cross-field-validation-bug-kwbdp?file=/src/index.js)

**Expected behavior**
If I change the value of one of the fields in a cross field validation so that there is no longer an error, the `formState` should be valid.

**Desktop:**

- OS: macOS
- Browser [chrome]
- Version [latest]

**Comment by lop862** [comment]
Hola me puedeayudar para una aplicación de secretar

**Comment by bluebill1049** [comment]
<img width="1044" alt="Screen Shot 2021-03-01 at 8 59 33 am" src="https://user-images.githubusercontent.com/10513364/109435047-72710c00-7a6c-11eb-8429-f1f20a249ac6.png">
<img width="708" alt="Screen Shot 2021-03-01 at 9 00 13 am" src="https://user-images.githubusercontent.com/10513364/109435065-89aff980-7a6c-11eb-84c2-8e74dba05dec.png">
Do i miss any steps?

**Comment by knoefel** [comment]
No, you did it exactly right. However, as you can see in your second image, the `formState` remains invalid even though the error has been corrected and the errors object is now empty again. Shouldn't correcting the error also set `formState.isValid` back to `true`?

**Comment by bluebill1049** [comment]
<img width="740" alt="Screen Shot 2021-03-01 at 6 19 40 pm" src="https://user-images.githubusercontent.com/10513364/109464383-b2f77680-7aba-11eb-9826-e668b753845c.png">

because `to` is not marked as valid, you should trigger that `to` input validation as well.

**Comment by knoefel** [comment]
Ok. How can I do it? I tried with the `trigger` method, but than I got trapped in an endless loop, because both fields use the same validation function. Do I need to split it up, so that each field has it’s own validation function?

**Comment by bluebill1049** [comment]
```
onChange={(e) => {
    trigger("to");
    onChange(e);
}}

onChange={(e) => {
    trigger("from");
    onChange(e);
}}  
```

works?

**Comment by knoefel** [comment]
No, unfortunately not. With your change, even the error is now no longer removed from the `errors` object after the correction.

<img width="827" alt="Screenshot 2021-03-01 at 09 47 57" src="https://user-images.githubusercontent.com/2396344/109473284-65a3e680-7a73-11eb-8c16-e8ebb583d19a.png">

**Comment by bluebill1049** [comment]
try now: https://codesandbox.io/s/react-hook-form--cross-field-validation-bug-forked-6uxul?file=/src/index.js i should do `trigger` after `onChange`

**Comment by knoefel** [comment]
Many, many thanks! It works perfectly now. Really great how quickly problems/questions are solved here. And sorry that I posted it as an issue, it would fit better in Discussions....

**Comment by bluebill1049** [comment]
no worries at all. glad it's working out 👍 hook form only focus on a single field level (performance), then you have to have to use the trigger for dependent fields, if you want form level, you will have to use resolver.
