### ISSUE TITLE
Dynamically update validators

### ISSUE THREAD

**Issue by alfetopito** [react-hook-form/react-hook-form#432]
**Describe the bug**
*Note:* Can't tell whether this is a bug or simply not supported.

Validators values are not updated dynamically.
Once the form is loaded, values set on the validators can't be updated.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-get-started-spyu1?fontsize=14
1. On the input field, insert a number over 1 and under 10
1. Click on submit 
  You should see the expected error message: `Over max!`
1. On the select, chose `10`
1. Click on sumbit
  The error message `Over Max!` is still visible.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-get-started-spyu1?fontsize=14

**Expected behavior**
On step `5` above, I expect to see no error message, given that the value between 1 and 10 is bellow the validation threshold of 10.
The validation threshold for the `usingMax` input should reflect the new value

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 70.0 64-bit / Chrome 78.0.3904.70 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by bluebill1049** [comment]
we do cache the register validation rules, you may want to switch into `validate` and `watch` function.

**Comment by alfetopito** [comment]
@bluebill1049 thanks for the quick response!

By the way, I've tried using `validate`, and the outcome is the same https://codesandbox.io/s/react-hook-form-get-started-spyu1?fontsize=14

Unless you mean something different?

**Comment by bluebill1049** [comment]
```
import React from "react";
import ReactDOM from "react-dom";
import useForm from "react-hook-form";

import "./styles.css";

function App() {
  const { register, handleSubmit, errors, watch } = useForm();
  const onSubmit = data => {
    console.log("data", data);
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <label>Choose max allowed number:</label>
      <select name="whatever" ref={register}>
        <option value="1">1</option>
        <option value="10">10</option>
      </select>
      <label>Insert a number</label>
      <input
        name="usingMax"
        type="number"
        ref={register({
          required: true,
          validate: {
            max: value => Number(value) <= watch('whatever') || "Over max!"
          }
        })}
      />
      {errors.usingMax && (
        <p>
          {errors.usingMax.message
            ? errors.usingMax.message
            : "Required field!"}
        </p>
      )}
      <input type="submit" />
    </form>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```
try above

**Comment by alfetopito** [comment]
That does indeed work!

Unfortunately, the source of the validation value in my case is coming from somewhere else, not another input  field.

I guess I could set that value to a hidden input, but that does not sound good at all.

**Comment by bluebill1049** [comment]
```
import React, { useState, useRef } from "react";
import ReactDOM from "react-dom";
import useForm from "react-hook-form";

import "./styles.css";

function App() {
  const { register, handleSubmit, errors } = useForm();
  const [maxValue, setMaxValue] = useState(1);
  const maxValueRef = useRef();
  const onSubmit = data => {
    console.log("data", data);
  };

  console.log("maxValue", maxValue);
  console.log("errors", errors);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <label>Choose max allowed number:</label>
      <select
        name="max"
        onChange={e => {
          console.log("updating maxValue to", e.target.value);
          setMaxValue(+e.target.value);
        }}
      >
        <option value="1">1</option>
        <option value="10">10</option>
      </select>
      <label>Insert a number</label>
      <input
        name="usingMax"
        type="number"
        ref={register({
          required: true,
          validate: {
            max: value => Number(value) <= maxValueRef.current || "Over max!"
          }
        })}
      />
      {errors.usingMax && (
        <p>
          {errors.usingMax.message
            ? errors.usingMax.message
            : "Required field!"}
        </p>
      )}
      <input type="submit" />
    </form>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```
what about this? FYI: i have to use `useRef` for `useState` due to JS closure

**Comment by alfetopito** [comment]
Oh right!
With a `ref` instead of a `prop` or `state` it works as a charm.

Thanks a lot for the help!

**Comment by bluebill1049** [comment]
lovely good to hear!
