### ISSUE TITLE
V7 append/prepend/insert not update all nested value

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#4325]
1. So simply click show element. You'll notice that the first field array element which is a default value and has not been registered stays around which is good (because I registered it). However, if you take a look at the second newly added element in the field array, you'll notice that the object is `{name: "will"}`. I would like it to be {name: "will", dog: "spike"} as this is what I just appended.

https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-pzz1b?file=/src/index.js

2. I think this is inline with your design as you aren't modifying default values and you don't want to add `formValues` that aren't associated with a registered input. Let me know what you think.

_Originally posted by @wdfinch in https://github.com/react-hook-form/react-hook-form/issues/4314#issuecomment-788679202_

**Comment by wdfinch** [comment]
So if values are now kept when append is run, how does this align with the design? Are these values new form values or just default values?

**Comment by bluebill1049** [comment]
here is the expected result: 

https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-csnp2?file=/src/index.js

**Comment by wdfinch** [comment]
Gotcha. Ok sounds good.

**Comment by bluebill1049** [comment]
releasing a patch now.

**Comment by wdfinch** [comment]
thanks!
