### ISSUE TITLE
[React Native] Property 'Proxy' doesn't exist

### ISSUE THREAD

**Issue by oxyii** [react-hook-form/react-hook-form#433]
**Describe the bug**
Looks like PR #407 are breaking React Native support.

**Comment by bluebill1049** [comment]
Hmmmm, what’s your react native version? I did test with it.

**Comment by oxyii** [comment]
@bluebill1049 "react-native": "0.61.2",

**Comment by oxyii** [comment]
Yep. `v3.25` works fine

**Comment by bluebill1049** [comment]
Ok looks like a version problem

**Comment by bluebill1049** [comment]
Going to close this then :)

**Comment by bluebill1049** [comment]
If u r using old version, u gonna to need a proxy polyfill

**Comment by oxyii** [comment]
@bluebill1049 Why closed? `v3.25` is last version of `react-hook-form` **before** merging #407. So since `v3.26` React Native support is really breaking.

**Comment by bluebill1049** [comment]
Oh sorry I got confused...

**Comment by bluebill1049** [comment]
can you please test out this version? `react-hook-form@3.26.3-beta.2`

**Comment by omarkhatibco** [comment]
also is not working in IE11 due to usage of Proxy

**Comment by omarkhatibco** [comment]
`react-hook-form@3.26.3-beta.2` is working on IE11.

**Comment by bluebill1049** [comment]
thanks @omarkhatibco

**Comment by oxyii** [comment]
@bluebill1049 `v3.26.3-beta.2` works fine on React Native too. Tested on Android 8.1 and iOS 12.4.3, 10.3.3

**Comment by bluebill1049** [comment]
nice @oxyii I will patch and release it now :) thanks for testing.

**Comment by oxyii** [comment]
I confirm `v3.26.3` works fine. Thank you!

**Comment by bluebill1049** [comment]
thank you too @oxyii for your help and report 👍

**Comment by frank-martinez-27** [comment]
I have a react app that needed to support IE11 and also had the issue with the Proxy, this is how I got it to work. I did `npm install --save proxy-polyfill` and on my app.js file I added `import 'proxy-polyfill/proxy.min.js';` at the top and then this function 
```
if (!window.Proxy) {
  const proxyPolyfill = ProxyPolyfillBuilder();
  window.Proxy = new proxyPolyfill();
}
```
Hope this helps someone in the future.
