### ISSUE TITLE
V7 issues with multiple calls to useFieldArray with same name and control

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4333]
**Describe the bug**
I'm currently noticing two bugs regarding `useFieldArray`. The bugs seem to be related to the idea of having two calls to `useFieldArray` with the same `name` and `control` but in different components.

Bug 1 - `fields` not in sync
If `useFieldArray` is used in component A and then another `useFieldArray` is used in a child component B with the same `name` and `control`, then the `fields` object will **not** be in sync once an operation like `append` occurs in the one component. So for example `append` in component B will not update the fields in component A.

Bug 2 - `remove` operation not working
If we have a similar setup to the bug 1 (`useFieldArray` called in component A and child component B with same `name` and `control`) and the field array inputs have been mounted, then the `remove` operation will not work if the field was appended from another component.

**To Reproduce**

1. Go to the code sandbox
2. Click on the show element button
3. Click log values and notice the fields do not represent the current fields
4. Click remove last element and notice that we cannot remove the element

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-vgnvt?file=/src/index.js

**Expected behavior**
I believe these issues are caused by each `useFieldArray` call creating its own state. If this is the case, I don't understand why this would be advantageous. I think the desired behavior would be to have one state and we could expect all our array methods to work regardless of where we call them (like useForm context). 

If it is the case that we must only have one `useFieldArray` call per array, are we still considering `useFieldArray` context?

My use case is that I need to be able to modify field array values from multiple components.

**Comment by bluebill1049** [comment]
First one: 

we don't support the same useFieldArray multiple usages, they don't broadcast changes. 

```
const { fields, append } = useFieldArray({
  name: "names"
});

const { fields, append } = useFieldArray({
  name: "names"
});
```

will take a look again at the other one later too.

**Comment by wdfinch** [comment]
Gotcha. Are there any plans for a `useFieldArray` context so we could manage a field array from multiple components?

**Comment by wdfinch** [comment]
There are other issues aside from `remove` I'm noticing that seem connected to multiple uses of `useFieldArray` with the same name/control. We might want to document this as a limitation of the library.

**Comment by bluebill1049** [comment]
> There are other issues aside from `remove` I'm noticing that seem connected to multiple uses of `useFieldArray` with the same name/control. We might want to document this as a limitation of the library.

yea sure, I think the easiest fix, for now, is having one and pass down those methods and `fields`.

**Comment by bluebill1049** [comment]
> Gotcha. Are there any plans for a `useFieldArrayContext` so we could manage a field array from multiple components?

yea, it's in the backlog. a tricky one tho.

**Comment by wdfinch** [comment]
I see. Ok so for now I'm going to just pass around the methods or use context callbacks with one `useFieldArray`. Not sure how much time you want to spend on this then. Might be best just to close this and warn people not to try this for now.

**Comment by bluebill1049** [comment]
> I see. Ok so for now I'm going to just pass around the methods or use context callbacks with one `useFieldArray`. Not sure how much time you want to spend on this then. Might be best just to close this and warn people not to try this for now.

ok, I will update the docs for this tonight.

**Comment by bluebill1049** [comment]
<img width="887" alt="Screen Shot 2021-03-03 at 5 46 37 pm" src="https://user-images.githubusercontent.com/10513364/109765045-69d52d00-7c48-11eb-809b-26a687a0df2c.png">
