### ISSUE TITLE
V7 bug - nested field array has incorrect value appended and exception thrown on future append

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4337]
**Describe the bug**
This one might make your head spin a little. There are two issues here related to nested field arrays. 

Let's say we have a form values object like:

```
{
   "first":[
      {
         "second":[
            {
               "third":[
                  {
                     "fourth":{
                        "objectKey":"someValue"
                     }
                  }
               ]
            }
         ]
      }
   ]
}
```

Then there will be some issues if we try to append the middle values of the field array.

1. If we append a middle field array element (let's say `second`) to the `first` array and we pass the final value (`fourth`) as an object, then it will be appended as `undefined` rather than the object we specified. 

```
{
   "second":[
      {
         "third":[
            {
               "fourth":{
                  "objectKey":"someValue"
               }
            }
         ]
      }
   ]
}
```

2. If we try to append a middle element after we've appended a previous middle element, then the operation will throw an exception and crash our application. So for example we append the value above and then append. 

```
{
   "third":[
      {
         "fourth":{
            "objectKey":"someValue"
         }
      }
   ]
}
```

to the previously appended element (`second`) this will throw an exception. 

**To Reproduce**

1. Go to the code sandbox
2. Immediately observe via the `watch` output that the newly appended value has undefined as a final value rather than the object. Notice the default value passed to `useForm` does have the correct value
3. Click show elements
4. Click the second add button that appears (add for the newly created field array element) and notice the exception that is thrown. 

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-qc0ye?file=/src/index.js:1120-1181

I'm not sure if there is a limit to nesting, but if there is I would hope it could go more than 3-4 levels deep.

**Comment by bluebill1049** [comment]
the problem is useFieldArray is limited to a flat array field, each deeply nested field array should create a separate `useFieldArray`, however, I am happy to do a quick investigation to see if this is archeiveable.

**Comment by wdfinch** [comment]
I see. So how could you append a middle nested element then? I'm not sure how else you could do it.

Thanks, it would be awesome if we could make this work cause my project is depending on it lol.

**Comment by bluebill1049** [comment]
> Right now it just seems impossible to add elements on a nested array.

It's possible, you will have to use useFieldArray and properly build up a tree of field array, you know what i meant right? like chain up useFieldArray correctly, since each one meant to host a UI of array of fields, but let me play around with custom register. I think it may works.

**Comment by wdfinch** [comment]
Ok, thanks. Could you post a sandbox or code snippet with a quick example after you play with the custom register? I'm not sure how to approach this.

**Comment by bluebill1049** [comment]
here is a working version with custom register within append: https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-8hccp?file=/src/index.js

I am a bit hesitant to introduce this feature just yet.

**Comment by bluebill1049** [comment]
let me know if the CSB works, and I will release another beta before the RC this weekend.

**Comment by wdfinch** [comment]
Thanks for the sandbox. So it seems like the solution involves adding an empty value into the array. EX: `{ third: [{}, ...` in

`append({ second: [{ third: [{}, { fourth: { testKey: "test" } }] }] });`

results in

![Screenshot from 2021-03-03 09-33-03](https://user-images.githubusercontent.com/36898266/109846939-88650500-7c03-11eb-8c9c-211ec16d7cec.png)

So in other words we can't add nested array elements unless an element at the level of insertion is already present right? Because the issue here is now we are introducing an `undefined` element at the `third` level. This in turn interferes with validation, type definitions, and creates a somewhat invalid array structure that we then need to work around.

> and I will release another beta before the RC this weekend.

Could you provide some more details on what this beta would address here? Is the only solution that we have the sandbox solution or do you plan on adding something else? Just wondering because I will need to change my design if we are allowing `undefined` elements into the nested arrays.

**Comment by bluebill1049** [comment]
@wdfinch I forgot to save correctly... try again.

https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-8hccp?file=/src/index.js

**Comment by bluebill1049** [comment]
<img width="516" alt="Screen Shot 2021-03-04 at 9 03 13 am" src="https://user-images.githubusercontent.com/10513364/109878482-7600cf00-7cc8-11eb-9819-1f60c04d2efc.png">

**Comment by bluebill1049** [comment]
once verify it's working, I will release the beta.

**Comment by wdfinch** [comment]
Ok, thanks. Yes, this seems to be working correctly.

**Comment by bluebill1049** [comment]
so the change will unlock deeply nested append, but it doesn't mean we can freely manipulate and shuffle inputs with the other `actions`. you will still need to create a deeply nested field array to use those `action` to manipulate inner field arrays. eg: `move` inner field array,

**Comment by wdfinch** [comment]
Sounds good. Appreciate all the help here.

**Comment by bluebill1049** [comment]
no worries, thanks for reporting those issues as always.

**Comment by wdfinch** [comment]
Do you have any updates on when the beta will be out? Just wondering cause I need the fix above to continue working on my project.

**Comment by bluebill1049** [comment]
I will do that tonight after work. 🙏 on my work laptop now.

**Comment by wdfinch** [comment]
No rush just wondering. Thank you!
