### ISSUE TITLE
[Bug] onSubmit reValidateMode breaks watching form values

### ISSUE THREAD

**Issue by nshaikhinurov** [react-hook-form/react-hook-form#434]
**Describe the bug**
Watching is broken when the hook is used with `{reValidateMode: 'onSubmit'}`

**To Reproduce**
1. Go to [Codesandbox](https://codesandbox.io/s/react-hook-form-watch-jz8rg)
2. Start typing to a text Input
4. See that no updates are logged to the console and the component does not rerender regardless of using `watch` method

**Codesandbox link**
[Codesandbox](https://codesandbox.io/s/react-hook-form-watch-jz8rg)

**Expected behavior**
Component rerenders with new input values being logged to the console

**Additional context**
Also, the `reValidateMode` option is not documented at the official site

**Comment by bluebill1049** [comment]
it's been documented, try to refresh your cache.

**Comment by bluebill1049** [comment]
patch on `react-hook-form@3.26.3-beta.3`

**Comment by bluebill1049** [comment]
will be in the next patch
