### ISSUE TITLE
V7 bug - setValue with field array does not work

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4343]
**Describe the bug**
I'm not sure if this is a bug or limitation of the library but it seems like a bug as it works on other cases. It seems that using `setValue` with a field array as the name argument and a new array of values as the value argument does not do the update. So `formValues` is not mutated. It seems like this bug occurs if we only mount a specific element of a field array rather than using `fields` to mount all the field array elements.

Additionally, in my own project, I've noticed an issue here where `formValues` is updated, but the `field.value` sent to my `controller` `render` function does not change. I can't seem to reproduce this one. 

**To Reproduce**

1. Go to the sandbox'
2. Click on change value
3. Notice that the `formValues` are not updated to represent the new array.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-1q7p5?file=/src/index.js

**Expected behavior**
This does seem to work if we set the individual fields. So for example:

`setValue("names[0].name", "will");`

This is an issue though if we need to set multiple fields in an array as I believe each `setValue` call must wait for the next render to operate correctly. I would hope that we could just pass in a new array and bulk update everything in one go.

**Comment by bluebill1049** [comment]
`setValue("names", [{ name: "mike" }]);`

will update `fields` and hence update all registered input under field array. right now, in your CSB it's disconnected, which is the reason why it's not working. 

`setValue("names[0].name", "mike");`

works because it's not a field array name, and it finds the input which gets registered and hence updated the value.

**Comment by wdfinch** [comment]
> right now, in your CSB it's disconnected, which is the reason why it's not working.

Could you explain this? How could I make it connected? I tried registering the array field names but this didn't change anything. Can `setValue` only change individual fields or can you update a whole field array like what I'm trying to do above?

**Comment by bluebill1049** [comment]
This is what i meant: https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-gf2fv?file=/src/index.js

**Comment by wdfinch** [comment]
I see. So for my use case, I have a really big field array, and therefore, I can't display multiple field array elements at the same time. Instead, I have a list of the elements and an edit button which then mounts the inputs for that one array element. So in other words I use something like in my sandbox and don't use `field.map`, to display the elements. 

I'm not sure why this would work differently than what you have. `fields.map` shouldn't matter as this is just a ui detail. The only other difference is adding `key={field.id}`. Does this make it connected? If I added this to a single controller by finding the field at that index, would this solve the issue?

**Comment by bluebill1049** [comment]
you can do this instead: https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-uqkto?file=/src/index.js

**Comment by wdfinch** [comment]
Ok great! Thanks for the help here! We can close this one out.

**Comment by wdfinch** [comment]
I'm not sure if this is a bug or a design feature but I'm noticing another issue here. If we have multiple array elements and only mount one, we must register each field name. Otherwise, `setValue` will delete array elements that haven't been mounted yet. I would expect that I would only need to call `register` when the field array length changes. So in order words, if we have new fields, we need to register them.

However, in the sandbox, it seems that if we don't call `register` immediately after calling setValues, then the field array elements that were not mounted will be deleted. I would expect we would not need to reregister these fields because we are simply changing the value. We are not changing the field name or introducing new field names.

If you click change value in the sandbox, you'll notice that field array elements will be removed via the call to `watch`. However, if we uncomment the useEffect hook right above that run on every rerender, then the field array elements will not be removed. Can you explain why we need to register the fields after `setValue` is called and no new fields are added?

https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-gp03c?file=/src/index.js

**Comment by wdfinch** [comment]
Additionally, I wanted to bring up one issue regarding the connected input. Right now we use the key={field.id} to connect an input. The issue is:

**if** we have a conditionally rendered field array **and** the key={field.id} hasn't run yet **and** we use `setValue`, **then** we will lose the field array elements.

Like `register`, I'm wondering if you would be open to being able to connect a field array without having to mount it. Otherwise, I need to use display none to always keep it mounted which leads to hooks running and more complex code. What do you think?

**Comment by bluebill1049** [comment]
I don't think `useFieldArray` will play nicely without the actual UI, probably not the right tool to use for just managing states without the view. I would say it's a limitation.

**Comment by wdfinch** [comment]
Ok. It would be nice if there was something like `register` where we could connect it prior to mounting it. In my use case, I would really like to call `setValue` before I mount the field array and when I do this, my default values are removed.

I totally get having the works by default method be to just mount everything. With the bigger forms in the enterprise space, this usually isn't an option though :(. 

Thanks for the help here, I'll find a way to work around this. I opened a feature request for this earlier so hopefully, someday it could be changed.

**Comment by alextaymx** [comment]
UseFieldArray only works with setValue when the array are already rendered in the UI, what if my current field array value is [{name:"alex",age:12}], and from another text input, there is an onChange method that setValue on the field array to : [{name:"alex",age:12},{name:"alex2",age:13}], in this case, it won't trigger the rerender, my field array mounted is still only 1 element, may i know how to get this work?

**Comment by wdfinch** [comment]
Can you attached a sandbox example?

**Comment by alextaymx** [comment]
i would need some time to come out with a sandbox, thanks for the instant reply , you're too kind.
