### ISSUE TITLE
setValue doesn't set entire object when passing a object

### ISSUE THREAD

**Issue by linde12** [react-hook-form/react-hook-form#4344]
**Describe the bug**
When calling `setValue` with an object path, e.g. `setValue('peopleMap[id123]', {...})` we get, in our submit handler, something like `{ peopleMap: { id123: {...} } }` but when calling `setValue('peopleMap', {})` the map is not being cleared. This makes it impossible to unset objects in your form without using "reset" - in my use case using "reset" is not an option (i don't want to touch any other fields and it is way more complex than just clearing the field i want to clear)

**Expected behavior**
`setValue('someKeyOfObject', {})` should set the `someKeyOfObject` to `{}` (removing all keys)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: 6.12.2

**Comment by bluebill1049** [comment]
we don't support that unfortunately, `setValue` is made for the individual field in v6 and set value for field array.
