### ISSUE TITLE
Disabled input throws validation error even though it has a value

### ISSUE THREAD

**Issue by Vishal1419** [react-hook-form/react-hook-form#4347]
**Describe the bug**
I have a disabled input on my form. I am setting its value by using setValue. But still when I submit the form, I get a validation error saying the field is required.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-xusvs?file=/src/app.js

**To Reproduce**
1. Open codesandbox
2. Click on Submit button
3. You should see a validation error
4. Click on Change Value button
5. Click on Submit button again
6. You will see that error does not go away.

**Expected behavior**
Validation error should not be thrown when submitting the form and input has a value.

**Desktop (please complete the following information):**

- OS: MAC OS High Sierra 10.13.6 (17G13035)
- Browser: Google Chrome 88.0.4324.192 (Official Build) (x86_64)
- RHF Version: 6.9.5

**Comment by bluebill1049** [comment]
we omit the `disabled` input for during submit.

**Comment by Vishal1419** [comment]
Is there any configuration that gives me the required behavior?

**Comment by bluebill1049** [comment]
you will have to pass context into your schema to conditional check.

**Comment by jmgirao** [comment]
sorry guys,
This ticket is closed but I didn't understand, why do you have this behaviour?
i think that not make sense in this scenario. the input is required and he have a value and he is valid.
