### ISSUE TITLE
Add Back Log Docs to Website

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4350]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
As someone who has used V7 a lot, I have brought up many changes and ideas. Some of these are in the backlog and some aren't. 

Being as this library is still growing and changing significantly between major builds, I wanted to bring up the idea of adding a road map or backlog to the website docs. This would give users greater visibility into what features will and will not be worked on, what the status/priority of new features is, and reduce issues/questions on Github.

I couldn't find an official backlog but I would like to list some of the items I've heard are on the backlog and/or would like to see on the backlog. I'd also like to list some ideas that I would think would be nice to have. I get that some of these won't be worked on, but I wanted to add them just to make sure my thoughts are all in one place.

Backlog items and design ideas
| Item Name                                                            | Details                                                                                                                                                                          | Status                                                       |
|----------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------|
| useFieldArrayContext                                                 | Add a way to use field array methods and data in multiple components                                                                                                             | In back log                                                  |
| controlled fields                                                    | Provide an option to make fields provided from useFieldArray controlled. Makes it much easier to get values and set defaultValues when a field array is mounted/unmounted            | won't be worked on                                           |
| modify default values                                                | Provide means to modify default values. Especially helpful with useFieldArray methods so we don't need to register every input to prevent default values from being removed.     | won't be worked on because of issues with watch and useWatch |
| auto unregister input                                                | Provide a prop on controller or option on register to auto unregister the input on unmount                                                                                                 | in backlog                                                  |
| access to schema validation errors not associated with an input      | Provide a means to access arbitrary schema validation errors. Ex field array must have length of 1                                                                               | maybe in backlog                                            |
| add the ability to chain form mutation methods that require a re render  | Right now we must wait for the next render cycle if we want to run multiple mutation methods. It would be nice if we could write them all at once and bulk update the formState  | not in back log                                              |
|                                                                      |                                                                                                                                                                                  |                                                              |

This is what I have now. Let me know if there are any updates here so we can work on a master list.

**Comment by bluebill1049** [comment]
I would prefer to use this board: https://github.com/react-hook-form/react-hook-form/projects one less thing for me to maintain. could you please send those feature requests if you are seeing missing in the project board?

**Comment by wdfinch** [comment]
I see. I didn't notice that. I don't think I have permission to edit there. Would I need to just make a separate issue for each of these and then you add it to that list?

**Comment by bluebill1049** [comment]
let me know which ones are missing from the feature request? I will add them.

**Comment by wdfinch** [comment]
Sorry, I'm a little confused. These are all the ones I had. Did you want me to make a separate issue for each one so you could individually add them? The items on the board you linked to are connected to individual github issues. Or did you want to make the issues for these?

They should probably be split into multiple requests as there are a bunch of items here.

**Comment by bluebill1049** [comment]
Do you want to convert those into feature requests? I will ping them to the board.

**Comment by wdfinch** [comment]
Sure. So I should open 6 issues, have you tag them, close them, and add them to the board right?

**Comment by bluebill1049** [comment]
4 of them, `won't be worked` on can leave them as issues.

**Comment by wdfinch** [comment]
Sounds good. 

Hopefully someday the fields one could be worked on because getting the current values for the default values of a nested array input is a real pain. 

I'll add those tonight.

**Comment by bluebill1049** [comment]
send that one as a feature request as well then. 👍

**Comment by wdfinch** [comment]
Ok, thanks. Can I just send them all so they are on the board? I think they all could lead to a better user experience. You don't have to work on any of them, but it would be nice for people to see them.

**Comment by bluebill1049** [comment]
sure 👍 thanks

**Comment by wdfinch** [comment]
Just added all the feature requests I have at this time.
