### ISSUE TITLE
Feature request - Add fieldArrayContext

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4353]
**Is your feature request related to a problem? Please describe.**
Yes

**Describe the solution you'd like**
Currently, multiple `useFieldArray` hooks with the same name and control are not connected. This means that methods called on field array A will **not** update the `fields` property of field array B with the same name and control. There are also other issues that are caused by trying to do this. 

Therefore, I propose adding something similar to `useFormContext` and `FormProvider`. I view the API as being very similar where we simply pass the output of the `useFieldArray` to a `FieldArrayProvider`. From there we can use `useFieldArrayContext` to access the properties of the field array. An operation like append would then update all the `fields` properties across multiple components. 

**Describe alternatives you've considered**
Right now use callbacks and custom context to pass around field array methods and properties from the top level.

**Comment by joefraley** [comment]
whatever happened to this? it seems like a super useful feature

**Comment by sscotth** [comment]
Just came across this today myself.

**Comment by bluebill1049** [comment]
Just to be clear the form context API will be applied to the field array, it's not a subscription on each input.
