### ISSUE TITLE
Feature request - add options to make fields on useFieldArray controlled 

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4354]
**Is your feature request related to a problem? Please describe.**
Right now the `fields` array provided by `useFieldArray` is not controlled. This means changes to our inputs will not be reflected by fields. This becomes an issue when we need to conditionally render field arrays. 

If we unmount and remount a field array, we likely would want the inputs to show the last values the user entered. This means using the `defaultValues` prop. However, because `fields` are not controlled, the values present on the object will not be the most recent values the user entered. This means we must use `formValues` via `getValues` to reinitialize the input to the correct value. This leads to harder-to-read syntax and more code. It gets really bad when we have nested field arrays with long names. 

**Describe the solution you'd like**
I would like to see an option on useFieldArray to make fields controlled. I get that leads to a performance hit, but I think it would be nice if the user could decide.

**Describe alternatives you've considered**
Using `getValues` to get the most up to date value.

**Comment by bluebill1049** [comment]
I am afraid this feature is not going to be worked on.

```
const formValues = getValues('fieldArrayName');

{fields.map((field, index) => {
  return {
     ...field,
     formValues[index]
  }
})}
```

by merging with `getValues()`.

**Comment by wdfinch** [comment]
This is fine. As mentioned if fields could sync on mount it would solve this issue. Are you still exploring that?

**Comment by bluebill1049** [comment]
> This is fine. As mentioned if fields could sync on mount it would solve this issue. Are you still exploring that?

I have done my investigation, hence with the conclusion above. If you want to control, you can do what i suggested above with the combination with `watch()` as well.

**Comment by wdfinch** [comment]
ok thanks.
