### ISSUE TITLE
Feature Request - auto unregister inputs on unmount 

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4355]
**Is your feature request related to a problem? Please describe.**
Yes. In V7 and going forward, inputs are not unregistered on unmount. So in other words, we must manually unregister an input if we want its value removed from form values. While this is a great design choice and in most cases makes things much easier, there are cases where we do want form values removed on unmount. 

For example, take a check box that adds additional fields. If the user unchecks the box, then in most cases we can assume that the fields are no longer relevant and we don't want to keep the values around. While it's totally doable to unregister the fields via `watch` and `useEffect`, it adds extra code and logic. It gets especially bad when we have a chain of related fields. For example show C if B and show B if A. We then need to add a bunch of checks to make sure we are not unregistering the field when we shouldn't be. 

**Describe the solution you'd like**
I propose adding a prop to Controller and an option to register that will unregister the input when on unmount. So essentially the V6 behavior. This would give us complete control over how to manage our inputs regarding mounting and unmounting. 

**Describe alternatives you've considered**
Using `useEffect`, `watch`, and `unregister`.

**Comment by linde12** [comment]
> If the user unchecks the box, then in most cases we can assume that the fields are no longer relevant and we don't want to keep the values around. While it's totally doable to unregister the fields via `watch` and `useEffect`, it adds extra code and logic. It gets especially bad when we have a chain of related fields. For example show C if B and show B if A. We then need to add a bunch of checks to make sure we are not unregistering the field when we shouldn't be.

This is how Angulars "reactive forms" works and it is a _pain_ to work with when dealing with complex conditionals in forms. I'd rather much have to deal with a occasional `display: none` rather than all of that complex and error-prone logic conditional logic which is already defined declaratively with JSX.

This behavior is the same for `useFieldArray` and `useController` as well, but with `useFieldArray` there is no way (that i know of) to actually reset it. It If i call `append` 3 times and then manually do `setValue('myarray', [])` then `fields` from `useFieldArray` will still contain 3 elements making form state & whatever `useFieldArray` reports differ. 😞

**Comment by wdfinch** [comment]
@linde12 

The issues with `display: none` are:

1. Performance - If the form is complex and contains many elements, then it can be really slow to mount everything at once. This is especially true for large field arrays. If you have a field array with 100 elements and each element is a complex custom input (react-select), then it becomes unbearably slow even with `display: none`. These types of forms are pretty common in enterprise software.

2. Imported libs - The standard in the react community is to unmount when a component no longer needs to be displayed. This means if you place your form in a modal from a library like material UI, semantic, etc. then the library will unmount the form if the modal is closed and we don't have control over this. This can be an issue if parts of your form are presented this way and you don't want to lose the inputs on unmount. 
 
`setValue('myarray', [])` is a valid operation and should work. Can you attach a sandbox showing the issue?

**Comment by linde12** [comment]
> @linde12
> 
> The issues with `display: none` are:
> 
> 1. Performance - If the form is complex and contains many elements, then it can be really slow to mount everything at once. This is especially true for large field arrays. If you have a field array with 100 elements and each element is a complex custom input (react-select), then it becomes unbearably slow even to do the initial mount even with `display: none`. These types of forms are pretty common in enterprise software.

Yes i've been doing a lot of those kind of apps lately, but also a couple of smaller ones. Either way, regardless of rhf v6 and v7, everything will still be mounted and unmounted, just not unregistered in v7. I don't see how v7 wouöd change that at least.

> 2. Imported libs - The standard in the react community is to unmount when a component no longer needs to be displayed. This means if you place your form in a modal from a library like material UI, semantic, etc. then the library will unmount the form if the modal is closed and we don't have control over this. This can be an issue if parts of your form are presented this way and you don't want to lose the inputs on unmount.

Yep, recently had this issue with a modal myself but the state could be stored in a outside rhf and then restored. Don't see it as an issue, more a minor inconvenience but i definetely prefer the form state to be ephemeral & local in most cases.

> `setValue('myarray', [])` is a valid operation and should work. Can you attach a sandbox showing the issue?

`setValue` works and empties the state, but `fields` frome `useFieldArray` still had the same length (but not the actual values) - I have downgraded to V6 again for now becausw V7 is unusable to me in its current state, but if i have time ill try to reproduce it in a codesandbox.

Apologies in advance for typos, writing from a phone atm :-)

**Comment by bluebill1049** [comment]
FYI: I am going to start an RFC on this and work on this feature.

**Comment by bluebill1049** [comment]
RFC: https://github.com/react-hook-form/react-hook-form/discussions/4783
