### ISSUE TITLE
Feature request - provide access to schema level validation errors

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4356]
**Is your feature request related to a problem? Please describe.**
Yes. If we are using schema-based validation like joi or yup, then we currently only have access to field-level error messages. However, it's common to have field array level error messages and multi-field error messages that don't relate to one field. For example, a very common use case would be to require that a field array contains at least one element.

While the validation works fine, we have no easy way of showing the user an error message. Instead, we must write our own resolver or do the validation ourselves to get this information. 

**Describe the solution you'd like**
I would like to find a way to add schema level error to `formState.errors`. This does break the rule of having each error relate to a field but I think it's necessary given how common a use case is. I think we could modify the object shape to be `formState.errors.schema` and `formState.errors.inputs`. This would mean that `inputs` could stay the same as it is now and `schema` could take on a new shape. 

**Describe alternatives you've considered**
Custom resolver and running the validation myself or again.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/discussions/6348#discussioncomment-1246393

**Comment by wdfinch** [comment]
I replied. I think we should have the discussion here rather than on the issue since the issue is related to an invalid bug report.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/discussions

**Comment by bluebill1049** [comment]
updated.
