### ISSUE TITLE
Feature request - add ability to chain mutation methods

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4357]
**Is your feature request related to a problem? Please describe.**
Yes. If we want to run multiple mutation functions like `append`, `remove`, `setValue`, etc. then we must wait for the previous method to run and the component to rerender before we can run the next one. 

This makes writing this logic much harder as we need to use `useEffect` to watch for the previous update. This also leads to worse performance as we need multiple renders to fully modify the form state. 

**Describe the solution you'd like**
I would like a way to update the `formValues` synchronously without having to wait for the next render cycle. I would see this as a helper method where we could pass multiple mutation methods in. Each one would receive the result of the previous action in case we need that for the next operation. So kinda like the flow method in lodash. 

**Describe alternatives you've considered**
Using useEffect to wait for the previous mutation method to run.

**Comment by bluebill1049** [comment]
After evaluation, this is not possible with the current design include v6, 7, especially because we are batching form state as well. if users are looking for similar functionality please use `useEffect` with additional **single** action or `setVlaue` instead,
