### ISSUE TITLE
Feature request - add ability to modify default values

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4358]
**Is your feature request related to a problem? Please describe.**
Yes. If we use a method like `append`, existing default values that have not been manually registered or mounted will be dropped from form values. This means we must manually register all our field inputs ahead of time and continually reregister new fields if they are added (ex `append`). This is a pain and is also tricky for nested field array where we need nested loops to register everything.

**Describe the solution you'd like**
For a start, I would like to see methods like append, remove, etc. simply be able to modify default values. I think it created a clearer mental picture of what is happening and means that we don't need to constantly register our inputs and worry about them being removed. 

The main issue here is it causes issues with watch and useWatch. Therefore, we will need some thought on how to execute this.

Additionally, I think it would be nice to add an option to setValue to allow the user to modify default values. This would provide more control and be helpful in certain situations.   

**Describe alternatives you've considered**
Constantly registering my inputs.

**Comment by bluebill1049** [comment]
I think this issue FR should be resolved by register absent fields from default values right?

**Comment by wdfinch** [comment]
Yes. No longer needed.
