### ISSUE TITLE
Watch() inconsistent return data issue

### ISSUE THREAD

**Issue by ericluwj** [react-hook-form/react-hook-form#436]
**Describe the bug**
Watching radio field doesn't result in rerender.

**To Reproduce**
1. Go to [Codesandbox](https://codesandbox.io/s/react-hook-form-watch-m92p0)
2. Start clicking the radio buttons.
3. See that component doesn't rerender so no console log of `watchRole` happens
4. Uncomment `watchAll` statements and comment `watchRole` statements.
5. Start clicking the radio buttons.
6. Now the component rerenders with every change in the radio field and `watchAll` gets logged in console.

**Codesandbox link**
[Codesandbox](https://codesandbox.io/s/react-hook-form-watch-m92p0)

**Expected behavior**
Component should rerender.

**Additional context**
This started happening since version 3.26.*

**Comment by bluebill1049** [comment]
thanks a lot @ericluwj i am patching this issue.

**Comment by nshaikhinurov** [comment]
I have found another bug. There is an inconsistent behavior between "string" and "object" syntaxes of `watch` arguments.

Additional info:
forked conditional fields example, used `react-hook-form@3.26.4`

How to reproduce:
1. Go to the [Sandbox](https://codesandbox.io/s/react-hook-form-conditional-fields-iwfd1)
2. Click to "Show" button, see `Object {Interests: undefined}` logged to a console regardless of the default value been set to `// (1)` `watch` option
3. Uncomment `(2)` and comment `(1)` options
4. Click to the button again, after showing a conditional field the is a `default Interests` logged as expected.
5. If the conditional field is the first child of a form the behavior is consistent, comment `// (3)` to test that

**Comment by bluebill1049** [comment]
thanks @nshaikhinurov but it's not very clear on this issue.

**Comment by bluebill1049** [comment]
what's inconsistency? return data?

**Comment by nshaikhinurov** [comment]
> @nshaikhinurov want to give a test on this beta? `react-hook-form@3.26.5-beta.1`

Yup, now it's working as expected. Thanks @bluebill1049
