### ISSUE TITLE
Issue while the field name has a '.' in it

### ISSUE THREAD

**Issue by Kishen-ravi** [react-hook-form/react-hook-form#4363]
Hi,

I generate the form using the title that is custom provided by the customers, and there is one customer who uses 'No. of pages' as the title of the field. This is causing an issue in showing the error field, and also the msg to be shown. I have added an example in the below sandbox. 
https://codesandbox.io/s/react-hook-form-get-started-forked-8d15m?file=/src/index.js

**Comment by bluebill1049** [comment]
`.` is preserved for object shape input. read here: https://react-hook-form.com/api#register
