### ISSUE TITLE
Remove is not removing the field when using nested field arrays.

### ISSUE THREAD

**Issue by Elia-Darwish** [react-hook-form/react-hook-form#4364]
**Describe the bug**
When using nested field arrays. Remove is not really removing the field from the fields array. Instead, the field is set to `undefined` and `fields` array maintains the same length.

**To Reproduce**

1. Go to the CodeSandbox provided below
2. Click on add child
3. Click on add child
4. in the console, `fields` will be `[Object, Object]`
3. Click on remove child
4. in the console, `fields` will be `[Object, undefined]`

**Codesandbox link (Required)**
https://codesandbox.io/s/hook-form-nested-field-array-t4m3g?file=/src/App.js

**Expected behavior**
The fields should me removed from the array and `fields.length` should reflect the actual fields count.

**Desktop (please complete the following information):**

- OS: macOs
- Browser: Chrome 88
- Version 6.15.4

**Comment by bluebill1049** [comment]
the whole component will get unmounted anyhow, why would you need to read what's in the fields object (component gets unmounted)?

**Comment by bluebill1049** [comment]
if there is any serious concern around the fields object after unmount, then v7 will be the solution for it: https://codesandbox.io/s/hook-form-nested-field-array-forked-ybhx6?file=/src/App.js

**Comment by Elia-Darwish** [comment]
This is actually not a big issue, and very simple to work around until v7 is released.

I thought I would point it out just in case, sorry 😅

**Comment by bluebill1049** [comment]
thanks, @Elia-Darwish we will most like to ship the release candidate (stable version) this weekend, so expect a lot of those "issues" get resolved in V7.
