### ISSUE TITLE
Module not found: Can't resolve '@videojs/vhs-utils/dist/byte-helpers'

### ISSUE THREAD

**Issue by acandael** [react-hook-form/react-hook-form#4365]
Since I installed React Hook Form in my Next.js project, I'm getting this error when running the server:

Module not found: Can't resolve '@videojs/vhs-utils/dist/byte-helpers'

I tried to fix it by installing @videojs/vhs-utils, but that did not fix it.

When I remove the React Hook Form package, the error is gone, so it is React Hook Form related.

Anyone else encountered this issue?

**Comment by jorisre** [comment]
👋🏻  @acandael
Could you please provide an example of your problem and follow the issue template #2848 ? Thanks
