### ISSUE TITLE
V7 possible bug - setValue with field array

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4368]
**Describe the bug**
Again not sure if this a design feature or a bug. The issue is it seems like `setValues` does not update `formValues` correctly even for connected field arrays.

I have two mounted field arrays. When I call `setValue`, I would expect `formValues` to be what I passed in given that everything is mounted and there are no virtual modifications. However, what's actually happening is just `fields` are being updated. So if I want the `formValues` to be updated, then I must use the mapped field item property name ex `item.name`.

My issues here are:
1. If I want the correct `defaultValue` for a field array I must use `field` and `getValues` because fields are not controlled and `formVaues` are not updated. 
2. If for some reason I want to use `setValue` and modify a field array that was mounted at some point (connected), but is longer mounted, then the operation won't work. I would hope that connecting field arrays could work like `register` where they only need to be mounted once in order to perform an operation on them.
3. For one render cycle `formValues` will be incorrect until the `defaultValue` kicks in for the field array element. This also causes issues. 

**To Reproduce**

1. Go to the code sandbox
2. Click on change value
3. Notice that the `formValues` are not updated correctly. 

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-v3dfs?file=/src/index.js

**Expected behavior**
I would hope that if a field array is connected, or has been connected, then we could successfully use `setValues` to modify our `formValues` without relying on `defaultValue={item.name}`.

**Comment by bluebill1049** [comment]
is this the correct CSB: https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-v3dfs?file=/src/index.js?

**Comment by bluebill1049** [comment]
use value from field instead: 

```
{fields.map((item, index) => (
        <Controller
          key={item.id}
          render={({ field }) => <input {...field} />}
          name={`${name}[${index}].name`}
          defaultValue={item.value}
        />
      ))}
```

https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-8ttjk

**Comment by wdfinch** [comment]
Yes, that's the right sandbox. Sorry, I mixed up the two for my issues yesterday. The example you posted still doesn't work. The values aren't changed.

**Comment by wdfinch** [comment]
And I guess the point of the question is I wanted to do this just using `formValues` and not `defaultValue={item.value}`. The issue is that `formValues` don't seem to update immediately from this operation and must wait for the new default value to be set which causes other issues. I mention some other issues above. 

Like I mentioned before, I would hope all operations could mutation `formValues` correctly, and fields could pull from this rather than just updating `field`.

**Comment by bluebill1049** [comment]
This should be the expected result by using the `field`: https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-8ttjk

**Comment by bluebill1049** [comment]
There is an issue with useFieldArray input's `defaultValue`,

**Comment by wdfinch** [comment]
Thanks for the patch. I'm having another issue here. Again not really sure if this part of the design or another bug. My issue is regarding `watch`, `setValue`, and `fieldArrays`. If we use `setValue` on a field array and add/remove fields, then we must wait for the next render when the field inputs mount in order for `formValues` to be updated. 

This presents an issue because our `formValues` are incorrect until the fields have been mounted. For example, if we want to use  `watch` on a field array input that has just been mounted and has a value set via `setValue`, then we will get undefined for that element until the next render.

Would it be possible to have `setValue` update field array elements immediately rather than having to wait for the new fields to mount? Otherwise, I need to check for these invalid states that should not occur and cause issues. 

In the sandbox, notice how `watch` on line 17 outputs undefined until the field is mounted.

https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-4c5n7?file=/src/index.js

It would be awesome if field array values could be more connected to `formValues`. I feel like `fields` and `formValues` are totally separate sometimes and it makes it tough to figure out what operations will affect what.

**Comment by bluebill1049** [comment]
I would use `useWatch` or `watch` to subscribe to the input change. `fields` are only meant to be used for the first render of input and reasons why it's assigned to defaultValue. When you are `reset` or `setValue`, it's remount those inputs again.

**Comment by wdfinch** [comment]
I do. I guess the bigger issue is `setValue` will update fields but not `formValues`. We must wait for the field array inputs to remount until we get the correct values. This leads to a render cycle where we have a valid array element, but `watch` will report the element as undefined because it hasn't rerendered yet. this is one of many issues of keeping the two out of sync.

**Comment by cargallo** [comment]
> I would use `useWatch` or `watch` to subscribe to the input change. `fields` are only meant to be used for the first render of input and reasons why it's assigned to defaultValue. When you are `reset` or `setValue`, it's remount those inputs again.

I'm having similar issue. I'm updating a fieldArray with setValue but still seeing old values in the page. If I do console.log(getValues('fieldArray')) it show updated, also with the watch but fields returned by fieldArray doesn't get updated. Also, all the examples of the library shows to use fields.map(item,index)=> to show de fields of fieldArray. What do you mean when you say use watch to subscribe to input change? 
Furthermore, I tried to use remove and insert to update but it doesn't work neither. I read at docs that "You can not call actions one after another. Actions need to be triggered per render.". I do not know what else I can try.

**Comment by andrewcbuensalida** [comment]
This library sucks
