### ISSUE TITLE
V7 bug - useFieldArray fields removed values on unmount

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4369]
**Describe the bug**

**If** 
1. we use a field array
2. append new values
3. unmount the field array and show another input
4. remount the field array

all while using `useFormContext`, **then** `fields` will only contain the default values and completely drop all newly appended elements.

**To Reproduce**

1. Go to the sandbox
2. Click on add element 
3. Click the toggle show field array button to unmount the field array
4. Click the toggle show field array button again to remount the field array
5. Notice that all the elements that we appended have now been removed. 

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-v3dfs?file=/src/index.js

**Expected behavior**
Remounting fields should contain all the values that are inside of `formState`.

**Comment by bluebill1049** [comment]
<img width="639" alt="Screen Shot 2021-03-06 at 6 55 19 pm" src="https://user-images.githubusercontent.com/10513364/110199653-81611f80-7ead-11eb-9edc-7f5bd7597166.png">

don't see an append button.

**Comment by bluebill1049** [comment]
is this the correct CSB: https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-kit46?file=/src/index.js

**Comment by bluebill1049** [comment]
fix will be released tmr.

**Comment by wdfinch** [comment]
Yes sorry, it's the one you posted. I opened two issues yesterday and linked the wrong sandbox.

https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-kit46
