### ISSUE TITLE
Question - Field validation based on other field value.

### ISSUE THREAD

**Issue by ashernguyen** [react-hook-form/react-hook-form#437]
Thank you for the awesome work. Does `react-hook-form` support validating one field that based on the inputed value from other field in the same form ?

**Comment by bluebill1049** [comment]
hey @ashernguyen yes we do 

`validate` function

I would recommend asking the question in here: https://spectrum.chat/react-hook-form

https://react-hook-form.com/api#register

cause sometimes even the community can help you out when I am away. :)

**Comment by ashernguyen** [comment]
hi @bluebill1049 , thank you for quick response. Please fix me if I am misunderstanding something here. From the API document, how can you get other field value from `validate` function. From my understanding, you only can get current `value` of the input field you want to validate. For example

```javascript
<input
  name="test1"
  ref={
    register({
      validate: {
        positive: value => { \\ I want to validate value of test1 based on the input length of test2 so how can I get value of test2 here ? },
      }
    })
  }
/>
<input
  name="test2"
/>

```

**Comment by bluebill1049** [comment]
You can use getValues function

**Comment by ashernguyen** [comment]
I found the answer from [here](https://spectrum.chat/react-hook-form/help/how-to-validate-a-field-depending-on-the-value-of-another-field~255ad6f6-1373-4944-a200-5d15daf06ff9?authed=true).  Thank you
