### ISSUE TITLE
[V7] useForm doesn't work with TS Generics

### ISSUE THREAD

**Issue by JuanM04** [react-hook-form/react-hook-form#4373]
**Describe the bug**
If I create a generic, for example, `FieldsType extends { query: string }`, and pass `FieldsType` to `useForm`, the types brake

**Codesandbox link (Required)**
Minimal reproduction:
https://codesandbox.io/s/react-hook-form-beta-generics-gckot?file=/src/MyForm.tsx

**Expected behavior**
Talking about my example, it should let me use the `query` inside `MyForm`. This worked in V6

**Comment by bluebill1049** [comment]
unfortunately, `type` that couldn't get extended by `FieldValues` will not be supported.

**Comment by JuanM04** [comment]
Oh... well, do you know any workaround to this problem?

**Comment by bluebill1049** [comment]
export 

```
type FormType = {
  query: string;
  name: string;
};
```

consider an option?

**Comment by JuanM04** [comment]
Not exactly... I'm trying to create like a "base form" and if I need it, pass extra inputs to it. That's a component with a form, some inputs and more inputs as children.

**Comment by bluebill1049** [comment]
Not sure, it's going to work out in V7, as we need to know what's exactly going to be in the form.
