### ISSUE TITLE
Set value for nest values of DatePicker type input

### ISSUE THREAD

**Issue by fabiorich-ico** [react-hook-form/react-hook-form#4374]
**Describe the bug**
Using set value to insert a value of type object {} works normally for common type inputs. When I use it for a DatePicker type input it doesn't work, unless you set the individual fields

**To Reproduce**

1. Open linked Sandbox
2. Click on " Set dummy Values (ok)"
3. It works! Values are setter correctly
4. Click on "Invia", in console form data is setter correctly
5. Reload sandbox
6. Click on " Set dummy Values (ko)"
7. It not works! Values are not setter correctly
8. Click on "Invia", in console form data is not setter correctly

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-fluentui-forked-bu6wi?file=/src/index.tsx

**Expected behavior**
Using set value to insert a value of type object {} works also for input DatePicker type.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by fabiorich-ico** [comment]
Sorry, I thought I pasted the sandbox link. 
Now I have updated the issue.
Thanks

**Comment by bluebill1049** [comment]
we only support setValue via input name, not deeply nested object.

**Comment by fabiorich-ico** [comment]
For TextField it works. In the example "input name" is set correctly through the setValue of a nested object

**Comment by bluebill1049** [comment]
for v6 we update the input value what value you have provided, and it's safer to stay with the input name itself.

It's not going to work with a nested object, in your example, new Date() is an object within an object.

**Comment by bluebill1049** [comment]
This issue will get fixed in v7: https://codesandbox.io/s/react-hook-form-fluentui-forked-3st71?file=/src/DateComponent.tsx

**Comment by bluebill1049** [comment]
fix merged into v7 root branch, will be part of the final release.
