### ISSUE TITLE
V7 RC 0 Typescript Issues with useFieldArray

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4379]
**Describe the bug**
The most recent typescript changes to `useFieldArray` make the field name argument to methods such as `setValue` too restrictive and remove previously valid naming schemas.

More specifically the issues I am noticing are:

1. Names such as `fieldArrayName[index]` are no longer valid (setting a specific element of the array)
2. Names such as `fieldArrayName[index].object` are no longer valid if the object is nested. 

So in other words, if I'm using a library  like `react-select` which represents data in the simplest form as 

```
interface Option {
  value: string,
  label: string
}
```

I cannot do something like `setValue(fieldArrayName[index].option, {value: "hi", label: "hi")`

I must do `setValue(fieldArrayName[index].option.value, "hi)` and `setValue(fieldArrayName[index].option.label, "hi)` which is unnecessarily complex. 

**To Reproduce**

1. Go to the code sandbox
2. Observe the typescript errors produced by setValue

**Codesandbox link (Required)**
https://codesandbox.io/s/thirsty-jang-jwi1e?file=/src/index.tsx

**Expected behavior**
I expect that setting an index of an array or setting an object rather than each element of the object would be a valid operation according to the type definition.

**Comment by kotarella1110** [comment]
I will investigate this 👍🏻

**Comment by kotarella1110** [comment]
@wdfinch v7 supports only dot syntax, and has dropped support for bracket syntax.

```ts
setValue("fieldArrayName.0.option", {value: "hi", label: "hi"});
setValue("fieldArrayName.0.option.value", "hi");
```

https://codesandbox.io/s/new-bash-xq9ve?file=/src/index.tsx

**Comment by bluebill1049** [comment]
Thanks, @kotarella1110! yea, dot syntax only 👍 That's the breaking change from v6 to v7.

**Comment by wdfinch** [comment]
I see. Ok, thanks.
