### ISSUE TITLE
Question - How to set initialValue for @material-ui/pickers.

### ISSUE THREAD

**Issue by VuongVu** [react-hook-form/react-hook-form#438]
Hi, i have a problem with` KeyboardDatePicker - @material-ui/pickers`.

This is my DatePicker Component: 
```
const DateTimePickerFieldComp = ({ type, id, name, label, format, inputRef, value, ...props }) => {
    const [selectedDate, setSelectedDate] = useState(new Date(''));
    const DatetimePicker = type === pickerTypes.DATE ? KeyboardDatePicker : KeyboardDateTimePicker;

    const handleDateChange = date => {
        setSelectedDate(date);
    };

    return (
        <MuiPickersUtilsProvider utils={MomentUtils}>
            <DatetimePicker
                {...props}
                id={id}
                name={name}
                label={label}
                format={format}
                value={selectedDate}
                onChange={handleDateChange}
                inputRef={inputRef}
            />
        </MuiPickersUtilsProvider>
    );
};
```
And this is place i apply with hook-form:
```
<FormControl margin="normal" fullWidth>
                <DatetimePicker
                    id="max_date"
                    label="Max date"
                    name="max_date"
                    type={pickerTypes[0]}
                    format={pickerFormat}
                    inputRef={register}
                />
            </FormControl>
```

When i init form. If i set `selectedDate` is `new Date('')`, the DatePicker have right initialValue inject from react-hook-from but it have error: `Invalid Date Format `and when i change date, it raise waring about `Uncontrolled input...`
If i set `selectedDate` is `new Date()`, initialValue is wrong. 

Plz tell me a solution or the wrong in my code. Thank so much.

**Comment by bluebill1049** [comment]
Please provide a codesandbox so we can reproduce easily and identify the solution.

**Comment by VuongVu** [comment]
https://codesandbox.io/s/elated-cdn-0e354.

Plz check it out.

**Comment by bluebill1049** [comment]
thanks for the codesandbox, i think the problem is because material-ui/KeyboardDateTimePicker doesn't support uncontrolled components, hence the warning. you will have to handle the change separately and update the value with `setValue` method

**Comment by VuongVu** [comment]
So i will pass a `value` and `onChange` function to my DatePicker component and use `setValue` in `onChange`.

**Comment by bluebill1049** [comment]
correct @VuongVu let me know how did you go with it. btw you can use setValue to trigger validation as well (3rd argument)

**Comment by VuongVu** [comment]
> correct @VuongVu let me know how did you go with it. btw you can use setValue to trigger validation as well (3rd argument)

It works but generates more code than the other case :D. Thank you for your support.

**Comment by VuongVu** [comment]
yep, agree with you :smile:. Thanks for your hard work.

**Comment by svict4** [comment]
Does `RHFInput` help with `@material-ui/pickers` or @VuongVu do you have a more complete example incorporating https://github.com/react-hook-form/react-hook-form/issues/438#issuecomment-548268070 ? 😊

**Comment by bluebill1049** [comment]
@svict4 pretty sure you can do it with `onChangeEvent` something i added recently if you are not aware.

**Comment by collegeimprovements** [comment]
Hi Guys, I'm facing the same issue. Can you please provide an example that works with @material-ui/pickers- with or without RHFInput!

**Comment by VuongVu** [comment]
@svict4  @collegeimprovements  just set manual `value` and `onChange` function for your `@material-ui/pickers`. `register` your field in `useEffect`.

**Comment by bluebill1049** [comment]
thanks @VuongVu yes @collegeimprovements you can refer to the example here: https://react-hook-form.com/get-started#WorkwithUIlibrary

**Comment by cargallo** [comment]
Hi, I couldn't find the MaterialUI picker's example in the provided link. Just for clarification is this the proper way? Please note that onChange and value properties are set in like empty functions in KeyboardDatePicker because the component forces them as required fields. This code is actually running ok in my code but I want to manage it in the recommened manner

```JSX
<Controller
  as={
	<KeyboardDatePicker
	  className={clsx(classes.textField)}
	  clearable
	  error={!!errors.startDate}
	  format="dd/MM/yyyy"
	  inputVariant="outlined"
	  label="Start Date"
	  margin="dense"
	  onChange={() => { }}
	  required
	  value={() => { }}
	  helperText={errors.startDate && errors.startDate.message}
	/>
  }
  name="startDate"
  control={control}
/>
```

**Comment by bluebill1049** [comment]
hey @cargallo what are those props?

```
onChange={() => { }}
value={() => { }}
````

**Comment by cargallo** [comment]
The component KeyboardDatePicker requests those properties to be set, they are mandatory in typescript. If I don't put that way I can't compile the code. But the code still works, seems that Controller is overriding them. I don't like to leave that code like that but I couldn't think of another way..

**Comment by bluebill1049** [comment]
Oh I see @cargallo I will think about it if we can improve it

**Comment by JuanmaMenendez** [comment]
I didn't need to set
onChange={() => { }}
value={() => { }}

What worked for me (using also MomentJS) was:



    <form onSubmit={handleSubmit(formSubmit)}\>
      <Controller
        as={
            <KeyboardDatePicker
                clearable
                autoOk
                format="MM/DD/YYYY"
                views={["year", "month", "date"]}
                inputVariant="outlined"
                margin="dense"
                InputAdornmentProps={{ position: "start" }}
                error={!!errors?.opened_at}
            />
        }
        name="opened_at"
        defaultValue={myCustomObject?.opened_at}
        rules={{ required: "Field Required" }}
        control={control}
      />
     <ErrorMessage name="opened_at" errors={errors} as="p" className="textError"/>
    </form>


     const formSubmit = dataToSubmit => {

     //If a new date was selected, Save the date in the correct format (utc)
     //_d has the new selected date (not in utc)
    if (dataToSubmit?.opened_at?._d) {
        dataToSubmit.opened_at = utc(dataToSubmit?.opened_at?._d).format();
    }

    //update Mutation call
    updateExecutionKitchenFunction({ variables: { uuid: myCustomObject?.uuid, input: dataToSubmit } });

    };

**Comment by bluebill1049** [comment]
thanks for sharing solution @JuanmaMenendez

**Comment by giovanniantonaccio** [comment]
@JuanmaMenendez which version of @material-ui/pickers are you using in your project?

I have the same issue here but can't apply your solution on version  "@material-ui/pickers": "^3.2.8" because onChange and value are required.

**Comment by JuanmaMenendez** [comment]
@giovanniantonaccio      "@material-ui/pickers": "^3.2.10", "@material-ui/core": "^4.9.1",

**Comment by dandv** [comment]
@cargallo: What do you mean by "This code is actually running ok", does it supply the date into `data.startDate` in the form's `onSubmit` handler? I've tested it and it's actually an "Invalid date format", which is visible if you remove the `helperText`. Also, clearing the value like that (`value={() => { }}`) means the field remains empty after you select a value.

@JuanmaMenendez: I don't think [that code](https://github.com/react-hook-form/react-hook-form/issues/438#issuecomment-605025654) works any more. If I don't pass `onChange` to my picker I get `_onChange is not a function`:

![DateTimePicker_onChange](https://user-images.githubusercontent.com/33569/82779322-be6d9100-9e08-11ea-8ca4-6c5efc4de5c7.png)

Also, that code has syntax errors. If you want to fix it out, it would be nice to add syntax highlight and remove extraneous stuff like `margin="dense"` or the mutation call.

### MUI DateTimePicker with React Hook Form

Anyway, here's a [pretty comprehensive example of Material UI DateTimePicker v4 with RHF](https://codesandbox.io/s/mui-v4-datetimepicker-with-rhf-jqv1c?file=/index.tsx). v4 is in alhpa right now but should be released soon, and [v3 is no longer supported](https://github.com/mui-org/material-ui-pickers/issues/1813#issuecomment-633468860). Features:
 * takes a `name` parameter for the name of the input
 * takes an optional inputFormat parameter, default "yyyy-MM-dd HH:mm"
 * returns a Date object to the onSubmit handler, under data[name]
 * sets the helperText underneath the TextField to a custom error
 * sets the errors[name].type to the error returned by the DateTimePicker

**Comment by cargallo** [comment]
@dandv my comment was at 6 of January. Surely the things has changed now. But looking at your example, I think that you are misleading the purpose of Controller of RHF, you shouldn't need to set onchange and value and let the controller handled them. The problem with MUI DateTimePicker is that in typescript it has the value and onChange properties mandatory so you must specify them. In the version of RHF that my comment was related to, RHF overrides them later so the was no problem in letting them empty.

**Comment by dandv** [comment]
> you shouldn't need to set onchange and value and let the controller handled them. 

I'd be very happy to find a simpler way get the date from the picker. I think the whole setup is way too complicated vs. the conceptual modeling of what I really want, form with a date picker that gets the picker's final value. I really don't care about controlled vs. uncontrolled components, `register()`, refs etc. I just want `form.datetime = [...let the user pick a date...]`.

**Comment by cargallo** [comment]
@dandv All of us wish the life of a developer as simpler as that!

**Comment by dandv** [comment]
@cargallo: it used to be! Have a look at how trivial is to get form data, including a datetime, with Webix:

https://snippet.webix.com/p2vll1xf

But nah, we developers hadddd to go after React, hooks, MUI, and all the fancy modern stuff just because.

**Comment by bluebill1049** [comment]
Thanks, @cargallo for your explanation.

Hey @dandv, Thanks for your feedback, but I think you have some misunderstanding with Controller, and having comparison with something like webwix is irrelevant here as well. 

Take a look at my example below: 

https://codesandbox.io/s/mui-v4-datetimepicker-with-rhf-7xgus?file=/index.tsx

`Controller` is made to control an isolated input component not your entire UI.

in terms of the following extra props:

```
  value=""
  onChange={() => {}}
```

we have an issue which wanting to fix: https://github.com/react-hook-form/react-hook-form/issues/1580

**Comment by cargallo** [comment]
With the purpose of adding context to this topic, it seems that the MUI Pickers creators are infatuated with keeping onchanged and value required without any reasonable explanation. 

https://github.com/mui-org/material-ui-pickers/issues/1575

**Comment by dandv** [comment]
Thanks for the advice. I've updated the [RHF + MUI DateTimePicker](https://codesandbox.io/s/mui-v4-datetimepicker-with-rhf-jqv1c?file=/index.tsx) to control the component as @bluebill1049 advised, and to use validation `rules` instead of the MUI Picker onError handler. Further feedback appreciated :)

**Comment by bluebill1049** [comment]
This looks great! much cleaner, less code, validation, and good focus manage.
@dandv at the time time, I think I should improve the doc to avoid confusion around `Controller` usage as well.

**Comment by cristian-eriomenco** [comment]
I don't know if this helps but i managed to get it working with validation, without any hacks and overrides. 
[Sandbox Here](https://codesandbox.io/s/react-hook-form-controller-h4h6v?file=/src/index.js)

**Comment by cargallo** [comment]
Hi @cristian-eriomenco the problem is in typescript code and you are using js project. Reggards,

**Comment by rexebin** [comment]
Failing to find a working sample, inspired by the discussions here, I have managed to remove the warning by managing a state and wiring up the date picker with RHF manually.  The code is [here](https://rexebin.medium.com/use-material-ui-pickers-with-react-hook-form-3ed5d24d6afc). Hope it helps to anyone looking for a working solution.

**Comment by bluebill1049** [comment]
Thanks for sharing solution @rexebin.

**Comment by finnmerlett** [comment]
> Failing to find a working sample, inspired by the discussions here, I have managed to remove the warning by managing a state and wiring up the date picker with RHF manually. The code is [here](https://rexebin.medium.com/use-material-ui-pickers-with-react-hook-form-3ed5d24d6afc). Hope it helps to anyone looking for a working solution.

This worked great! I even managed to get error validation hooked up properly. Happy to share my findings if anyone else wants them (I also tried to summarise it in a comment on @rexebin 's [medium article](https://rexebin.medium.com/use-material-ui-pickers-with-react-hook-form-3ed5d24d6afc))

**Comment by finnmerlett** [comment]
> I don't know if this helps but i managed to get it working with validation, defaultValues, outline style, without any hacks and overrides.
> [Sandbox Here](https://codesandbox.io/s/react-hook-form-controller-h4h6v?file=/src/index.js)

When I checked this out, it wasn't reporting errors. I fixed it by changing your code to this
```
<Controller
  as={
    <KeyboardDatePicker
      fullWidth
      autoOk
      {...error ? {error} : {}}
      ...
    />
  }
  ...
/>
```
It looks like even setting error to 'undefined' overwrites the internal error setting

**Comment by bluebill1049** [comment]
@finnmerlett switch to render if possible, as is getting deprecated.

**Comment by finnmerlett** [comment]
@bluebill1049 haha - literally every other example bit of code on this thread has been using `as` and not been called out :laughing:  but thanks for the heads up! Can you use `render` just as a drop-in replacement for `as`?

**Comment by bluebill1049** [comment]
> @bluebill1049 haha - literally every other example bit of code on this thread has been using `as` and not been called out 😆 but thanks for the heads up! Can you use `render` just as a drop-in replacement for `as`?

close... `<Controller render={({ field }) => <Input {...field} />} />`

looking for a single robust solution and without giving too much headache to the developer when `as` is not as expected.

**Comment by rexebin** [comment]
> > Failing to find a working sample, inspired by the discussions here, I have managed to remove the warning by managing a state and wiring up the date picker with RHF manually. The code is [here](https://rexebin.medium.com/use-material-ui-pickers-with-react-hook-form-3ed5d24d6afc). Hope it helps to anyone looking for a working solution.
> 
> This worked great! I even managed to get error validation hooked up properly. Happy to share my findings if anyone else wants them (I also tried to summarise it in a comment on @rexebin 's [medium article](https://rexebin.medium.com/use-material-ui-pickers-with-react-hook-form-3ed5d24d6afc))

@finnmerlett I am using Yup and validation just worked for me let why I didn't write about it in the article. I will add it in after.

My setup is as follow: 

1. schema:  
```typescript
import { Asserts, date, object} from 'yup';

export const companySchema = object({
  yearEndDate: date().nullable().typeError('Invalid Date'),
});

export type Company = Asserts<typeof companySchema>;
```
2. deconstruct `errors` from `useForm`:
```typescript
const { reset, control, handleSubmit, errors } = useForm<Company>({
    resolver: yupResolver(companySchema)
  });
```

3. assign `error` and `helperText` to the wrapped date-picker:
```tsx
 <EpicDatePicker
                control={control}
                name={'yearEndDate'}
                label={'Year End Date'}
                error={!!errors.yearEndDate}
                helperText={errors.yearEndDate?.message}
              />
```
