### ISSUE TITLE
Unregister does not work

### ISSUE THREAD

**Issue by Narquadah** [react-hook-form/react-hook-form#4392]
**Describe the bug**
Unregister does not remove values from the resulting data onSubmit.

**To Reproduce**
1. Goto Codesandbox
2. Enter something in the two fields
3. Click on submit both fields are there
4. Click on `unregister lastname`
5. Click on submit
6. Both fields still present

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-unregister-v6-forked-rhx54?file=/src/index.js

**Expected behavior**
As described [here](https://react-hook-form-website-git-v7-bluebill1049.vercel.app/api/useform/unregister).

**Comment by bluebill1049** [comment]
make sure you unmount that input because it will get re-registered again in the next render.

**Comment by Narquadah** [comment]
Ok thx for your tip, I updated the codesandbox and it works 👍

**Comment by leapful** [comment]
@bluebill1049 : I've found a bug while checking the method "unregister" :smile: 

https://github.com/react-hook-form/react-hook-form/blob/1d928550dfa98541f0be3e54aa63a0a7e1668bcc/src/useForm.ts#L807-L808

**Comment by bluebill1049** [comment]
oh wow, yes plz @leapful
