### ISSUE TITLE
[V7] How to use V7 with forwardRef

### ISSUE THREAD

**Issue by matamatanot** [react-hook-form/react-hook-form#4395]
**Describe the bug**
Is it possible to use `forwardRef` in the same way as V6?
I can't get right values and they are always initial values.

**To Reproduce**

1. Create a forwardRef Component.
2. Use `{...register("fooBar")}` newSyntax.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-forked-sv7yq?file=/src/index.tsx

**Expected behavior**
Get right values.

**Comment by bluebill1049** [comment]
hey @matamatanot you forgot to pass down the rest of the props: 

https://react-hook-form-website-git-v7-bluebill1049.vercel.app/api/useform/register

<img width="669" alt="Screen Shot 2021-03-10 at 9 07 34 am" src="https://user-images.githubusercontent.com/10513364/110544564-0edb9280-8180-11eb-9628-2f82abe30500.png">

(i will need to update to include `name` as well)

**Comment by matamatanot** [comment]
@bluebill1049  Thanks for the reply. But I don't know exactly how to fix it.

```
type FormValue = {
  displayName: string;
  permissions: 0 | 1 | 2;
};

const ForwardInputItem = forwardRef<HTMLInputElement, { label: string }>(
  ({ label }, ref) => {
    return (
      <div>
        <label>{label}</label>
        <input ref={ref} />
      </div>
    );
  }
);

const ForwardSelectItem = forwardRef<HTMLSelectElement, { label: string }>(
  ({ label }, ref) => {
    return (
      <div>
        <label>{label}</label>
        <select ref={ref}>
          <option value={0}>{"None"}</option>
          <option value={1}>{"Read"}</option>
          <option value={2}>{"Read / Write"}</option>
        </select>
      </div>
    );
  }
);

function App() {
  const { register, handleSubmit } = useForm<FormValue>({});

  return (
    <div>
      <form onSubmit={handleSubmit((values) => console.log(values))}>
        <ForwardInputItem label={"displayName"} {...register("displayName")} />
        <ForwardSelectItem label={"permissions"} {...register("permissions")} />

        <div>
          <button type="submit">{"Submit"}</button>
        </div>
      </form>
    </div>
  );
}
```

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-useform-template-forked-o3fdn?file=/src/index.tsx

**Comment by matamatanot** [comment]
Thanks! 👍

**Comment by bluebill1049** [comment]
np 👍

**Comment by matamatanot** [comment]
@bluebill1049 
This is not a bug, but it bothered me.

I created a component that looks like this.

```
import { forwardRef } from "react";
import { InputLabel } from "../InputLabel/";

type InputDateType = React.ComponentProps<"input">;
export type DatePickerProps = InputDateType & {
  label?: string;
};

export const DatePicker = forwardRef<HTMLInputElement, DatePickerProps>(
  (props, ref) => {
    return (
      <div className="flex-1 flex flex-col">
        {props.label && (
          <InputLabel>{props.label}</InputLabel>
        )}
        <input
          {...props}
          ref={ref}
          type="date"
          className="w-full p-4 border border-gray-300 rounded"
        />
      </div>
    );
  }
);
```


It is a so-called 'atoms' component.
Currently, I use it in combination with React Hook Form in most cases. However, this component itself is not restricted in how it can be used. 

However, in V7, if you want to combine a component that uses forwardRef with React Hook Form, you need to modify the 'atoms' component.

**Comment by bluebill1049** [comment]
> @bluebill1049 
> 
> This is not a bug, but it bothered me.
> 
> 
> 
> I created a component that looks like this.
> 
> 
> 
> ```
> 
> import { forwardRef } from "react";
> 
> import { InputLabel } from "../InputLabel/";
> 
> 
> 
> type InputDateType = React.ComponentProps<"input">;
> 
> export type DatePickerProps = InputDateType & {
> 
>   label?: string;
> 
> };
> 
> 
> 
> export const DatePicker = forwardRef<HTMLInputElement, DatePickerProps>(
> 
>   (props, ref) => {
> 
>     return (
> 
>       <div className="flex-1 flex flex-col">
> 
>         {props.label && (
> 
>           <InputLabel>{props.label}</InputLabel>
> 
>         )}
> 
>         <input
> 
>           {...props}
> 
>           ref={ref}
> 
>           type="date"
> 
>           className="w-full p-4 border border-gray-300 rounded"
> 
>         />
> 
>       </div>
> 
>     );
> 
>   }
> 
> );
> 
> ```
> 
> 
> 
> 
> 
> It is a so-called 'atoms' component.
> 
> Currently, I use it in combination with React Hook Form in most cases. However, this component itself is not restricted in how it can be used. 
> 
> 
> 
> However, in V7, if you want to combine a component that uses forwardRef with React Hook Form, you need to modify the 'atoms' component.

What do you have to modify?
