### ISSUE TITLE
`shouldUnregister` does not work with class-based instances

### ISSUE THREAD

**Issue by luciorubeens** [react-hook-form/react-hook-form#4397]
**Describe the bug**

In addition to https://github.com/react-hook-form/react-hook-form/issues/3877 and https://github.com/react-hook-form/react-hook-form/issues/3246, I noticed this issue after upgrading from `6.8.x` to `>6.9.3` (bug introduced here https://github.com/react-hook-form/react-hook-form/pull/3185). I saw in the thread that is being resolved in `v7`, however it's a breaking change and should not break applications, so better to implement a workaround to make it compatible with semantic versioning.

**Failing test**

```diff
--- a/src/utils/cloneObject.test.ts
+++ b/src/utils/cloneObject.test.ts
@@ -81,4 +81,18 @@ describe('clone', () => {

     expect(copy.items).toEqual([2]);
   });
+
+  it('should copy prototype methods', () => {
+    class Counter {
+      count = 1;
+      increment() {
+        this.count++;
+      }
+    }
+    const counter = new Counter();
+    const copy = cloneObject(counter);
+
+    expect(copy.count).toBe(1);
+    expect(typeof copy.increment).toBe('function'); // Received: "undefined"
+  });
 });
```

**Solution**

```diff
--- a/src/utils/cloneObject.ts
+++ b/src/utils/cloneObject.ts
@@ -12,6 +12,14 @@ export default function cloneObject<T extends unknown>(data: T): T {
     return data;
   }

+  if (
+    !['Set', 'Map', 'Object', 'Date', 'Array'].includes(data.constructor.name)
+  ) {
+    return data;
+  }
```

**Comment by bluebill1049** [comment]
thanks, mate. will be released in the next patch.
