### ISSUE TITLE
dirtyFields are not updated after resetting the form

### ISSUE THREAD

**Issue by tymoteusz-duraj** [react-hook-form/react-hook-form#4398]
**Describe the bug**
After calling `reset` function, the `dirtyFields` value is empty object.

**To Reproduce**
1. Go to codersandbox link provided below
2. Type something into FirstName and LastName fields (in the console you can see `dirtyFields` object with correct values)
3. Click submit button (the form value will be stored in state)
4. Click 'go back' button
5. Look at the console - `dirtyFields` is an empty object

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-forked-fmk0u

**Expected behavior**
After resetting the form, `dirtyFields` should includes FirstName and LastName fields because values of theese fields are different than values provided in `defaultValues`.

**Comment by bluebill1049** [comment]
reset will clear all `dirtyFields`, unless you use the second `omit` argument

**Comment by tymoteusz-duraj** [comment]
Ok, I added `dirtyFields` to `omit` argument but nothing changes.

**Comment by tymoteusz-duraj** [comment]
So it' impossible to get my goal when inputs are getting unmounted, right? I tought that useForm is comparing 
defaultValues and values setting by reset and updates dirtyFields based on theese differenes

**Comment by bluebill1049** [comment]
try `shouldUnregister: false`
