### ISSUE TITLE
Controlled component behaves weird when trying to fill it in, after a validation

### ISSUE THREAD

**Issue by adhenrique** [react-hook-form/react-hook-form#4399]
**Describe the bug**
I have a simple functional component form, using MaterialUI and redux state. (For this example, i used local state with the useState() hook. The behavior is the same.)  
When trying to save the form that has a field with required validation, for example, the react-hook-form returns the error as expected. However, when I try to type in the field with the error, the first and last character is not inserted.  

Is it related to the fact that you are using `ref` and `register` in a Controlled component?

**To Reproduce**
I reproduced this error in the codesandbox. (using the react-hook-form example itself)  
The component in question is `index.js`:
```js
<input
    name="firstName"
    ref={register({
      required: true,
      maxLength: 20,
      pattern: /^[A-Za-z]+$/i
    })}
    onChange={e => setValue(e.target.value)}
    value={value}
  />
```

**Codesandbox link (Required)**
Heres a link to [reproduce this issue](https://codesandbox.io/s/react-hook-form-apply-validation-forked-dnbnn)

**Expected behavior**
I expected that I could type in the field freely, for example, if I remove the `value` prop in the line `29`

**Desktop (please complete the following information):**

- OS: iOS
- Browser chrome
- Version 89

**Comment by bluebill1049** [comment]
don't mix controlled with uncontrolled. 

register => uncontrolled
useController => controlled.

**Comment by rjgux** [comment]
I'm having the exact same issue and trying to work out what the correct approach is. Instead of using `register` should it be using the `useController` hook?

**Comment by bluebill1049** [comment]
@rjgux yes, for controlled input, use `useController`

**Comment by rjgux** [comment]
Thanks @bluebill1049 

@adhenrique In case it helps you, here's how I updated my component based on @bluebill1049's tip -

```
// Before
<input
  name="firstName"
  ref={register({
    required: true,
    maxLength: 20,
    pattern: /^[A-Za-z]+$/i
  })}
  onChange={e => setValue(e.target.value)}
  value={value}
/>

// After
const { control } = useFormContext()
const {
  field: { ref, ...inputProps },
  meta: { invalid },
} = useController({
  name: name,
  control,
  rules: { required: required },
  defaultValue: '',
})

<input
  name={inputProps.name}
  ref={ref}
  onChange={e => {
    setValue(e.target.value)
    inputProps.onChange()
  }}
  onBlur={inputProps.onBlur}
  value={value}
/>
```

**Comment by bluebill1049** [comment]
Thank you @rjgux

**Comment by bluebill1049** [comment]
thanks for sharing @adhenrique
