### ISSUE TITLE
onChange validation mode not working for nested field arrays, only for top level fields

### ISSUE THREAD

**Issue by arochadaniel** [react-hook-form/react-hook-form#4403]
**Describe the bug**
Errors in `formState` not updating in `mode: onChange` or `reValidateMode: onChange` inside nested field arrays, but it updates in top level fields, all this while using a custom resolver to manage validation. Is worth noting that I'm using FormProvider to handle deeply nested components.

**To Reproduce**

1. Create form with FormProvider
2. Provide defaultValues, e.g: `{ name: '', steps: [ { name: '' } ] }`
3. Create top level input for `name` and nested field array inputs for `steps[i].name`
4. Create Yup schema and custom resolver for validation
5. Submit form with errors
6. Change top level `name` to fix the error message (and you will see the error dissapear)
7. Change nested field array input to fix the error, and even when it is in `onChange` mode it will not make the error dissapear from the state on change, but only after another submit.

**Codesandbox link (Required)**
[Sandbox link](https://codesandbox.io/s/react-hook-form-v7-validation-error-yw66e?file=/src/App.tsx)

**Expected behavior**
It should validate all fields in the expected mode.

**Additional context**
I'm using the latest release candidate `7.0.0-rc.2` because I needed Fast Refresh support, but I got the same error even using the latest stable V6 release, in fact, I changed to V7 in hopes that it was fixed.

I've tried a lot of workarounds (subscribing to formState, trigger validation onChange manually, etc.) and the only that worked for me was using the local validation solution inside the `register` rules, with that validation mode it does work as expected, but I'm more comfortable using a custom resolver as the form structure is really big and defining validation in each component could become a mess.

The sandbox is just a minimum representation of my code, in my source code I have up to 4th level nested arrays.

The strange thing is that the resolver does make the error dissapear like expected, but it seems that maybe something is wrong while comparing with the previous state inside hook form and it doesn't get updated? Like is only doing a shallow comparison in `onChange` mode. I left identified console logs in the sandbox for you to check it out.

This package is amazing! I was using Formik but the performance becomes really bad when doing really large structures, so I might switch completely to Hook Form.

**Comment by bluebill1049** [comment]
v7: https://codesandbox.io/s/react-hook-form-v7-validation-error-forked-n0eiu?file=/src/App.tsx

<img width="522" alt="Screen Shot 2021-03-11 at 9 00 59 am" src="https://user-images.githubusercontent.com/10513364/110703793-4e6db180-8248-11eb-8020-8aeeaf7468ba.png">

this is not going to work with deeply nested errror.

**Comment by bluebill1049** [comment]
changed to yupresolver and everything is fine: https://codesandbox.io/s/react-hook-form-v7-validation-error-forked-n0eiu?file=/src/App.tsx

**Comment by arochadaniel** [comment]
I saw my mistakes. 

First the shape of the errors I was returning in my custom resolver was `[path]: { message }` and it should be the same shape as the values of the form, with the yupResolver works fine.

Second I had the names with the brackets instead of dots.

Now everything is ok. Thank you for your time!
