### ISSUE TITLE
Trying to setValue of useFieldArray

### ISSUE THREAD

**Issue by niteshgrg** [react-hook-form/react-hook-form#4404]
**Describe the bug**
Set value of a field array works like here my fields name is slab.

`setValue(`slabs[${index + 1}].start`, 3, true);`

If i check my slabs now value is reflected there as well but while handleSubmit function data it shows this value as undefined. So only data object is not in sync with fieldsArray which is weird.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by niteshgrg** [comment]
Sure sorry let me try to create it in codesandbox and send that link again.

**Comment by Mendoza920** [comment]
I apologize.
Due to no active phone or
Income. I lack of communication.

**Comment by niteshgrg** [comment]
@bluebill1049 Created a sandbox.
https://codesandbox.io/s/field-array-setvalue-bug-zq68b

To reproduce fill the values in 2 fields shown click on add another slab. 
- At this point ideally 3 field should have +1 value set of 2nd fields as you can see in line num 76-78 logic.
- If i change my value in 2nd field my 3rd field should get updated as i am trying to do in line 59. 
-Clicking on submit it will console the data in that as you can see 3rd field value would be undefined.

in my structure [{"start": '', "end": ""}] start of after 1st field are coming as undefined.

**Comment by niteshgrg** [comment]
I was seeing there are improvements to setValue in v7 is this bug already known and being fixed in v7 ?

**Comment by bluebill1049** [comment]
`disabled={index > 0}` use readOnly instead of disabeld.

**Comment by niteshgrg** [comment]
Thanks that made it work. But i am using material ui and i would like these fields to be disabled generally ui wise. As it handles them better. Also tab selection and all also skips it. Is there any way i can make it work with disabled too ?

**Comment by bluebill1049** [comment]
> Thanks that made it work. But i am using material ui and i would like these fields to be disabled generally ui wise. As it handles them better. Also tab selection and all also skips it. Is there any way i can make it work with disabled too ?

I would investigate into MUI doc for solutions.

**Comment by niteshgrg** [comment]
I think this would be more about making it work with disabled. As MUI also accepts InputProps and in that if i supply readonly it works. Also just in general curious why does it not work with disabled elements ?

**Comment by bluebill1049** [comment]
what do you mean `not work`? `disabled` input should not be part of the submission data.

**Comment by niteshgrg** [comment]
Ok got it so disabled fields are intentionally not registered.

**Comment by bluebill1049** [comment]
yes intentionally omitted by following HTML starndard.
