### ISSUE TITLE
formState isValidating not updated on validation

### ISSUE THREAD

**Issue by GeenCo86** [react-hook-form/react-hook-form#4409]
**Describe the bug**
When using an async validation formState.isValidating is not set to true while validating

**To Reproduce**

1. use the codesandbox example and click on submit
2. After 5s there will be the validation error.
3.  Every fomState update is logged to the console. But when clicking submit the formState.isValidating is not switching to true.

**Codesandbox link (Required)**
[isValidating](https://codesandbox.io/s/react-hook-form-v6-ts-errormessage-multiple-error-messages-forked-ihf8j?file=/src/index.tsx)

**Expected behavior**
On each validation the isValidating should be updated

**Desktop (please complete the following information):**

- OS: [Mac Os BigSur 11.2]
- Browser [e.g. chrome]
- Version [e.g. 88]

**Additional context**

I want to be able to show a loading icon for the validation process, independet of validation mode (submit, onBlur ...)

**Comment by bluebill1049** [comment]
> Note: isValid is affected by mode. This state is only applicable with onChange and onBlur mode.

**Comment by GeenCo86** [comment]
Hi, thanks for investigation. But if I set mode to 'all' then onBlur and onChange are also used!

**Comment by uncvrd** [comment]
I think I'm running in to a similar issue with `isValidating`, I'd like to disable a button during an async validation event. In my case, `isValidating` is changed to `true` but quickly switches back to false before the async validation is complete. For example, here is my validate handler:

```
validate: async (value) => {
    console.log("start validation")
    const {
        data,
    } = await apolloClient.query<CampaignNameExistsQuery>({
        query: CampaignNameExistsDocument,
        variables: {
            campaignName: value,
        },
        fetchPolicy: "network-only",
    });
    console.log("end validation")

    if (data && data.campaignNameExists) {
        // if it exists then validate 'false' saying that name is taken
        return (
            !data.campaignNameExists ||
            "This campaign name is already taken"
        );
    }

    return true;
},
```

Then, if I were to print out in my form the `formState.isValidating` boolean, I'd see:

```
start validation
true
false <-- changes to false before async validate is complete
end validation
```

Ideally would like to see `isValidating` stay `true` until the async validation is complete. I'm using RHF 6.15.1

**Comment by mdjzon** [comment]
Similar issue here. Would like to reformat the value only after it has changed to a valid value and the field has lost focus. But I'm not able to find the right moment to do so.

```
useEffect(() => {
  if (formatter && isTouched && !isFocused && !invalid) {
    setValue(name, formatter(value))
  }
}, [formatter, invalid, isFocused, isTouched, name, setValue, value])
```

**Comment by owlran** [comment]
hope `isValidating` can stay in `true` +1
