### ISSUE TITLE
V7 appending multiple items to a field array results in duplicate items

### ISSUE THREAD

**Issue by kalley** [react-hook-form/react-hook-form#4410]
**Describe the bug**
Appending multiple items using `useFieldArray` results in duplicates being added

**To Reproduce**

1. Use `useFieldArray`
2. `append` multiple items at once (the more you add, the more duplicates get added)
3. Check `watch()`
4. Check `data` on submit

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-idbu5?file=/src/index.js

**Expected behavior**
The correct number of items would be added to the form data

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Chrome
- Version: 88.0.4324.192

**Comment by kalley** [comment]
Screen recording attached. You'll notice that I added the "Append Multiple" button and it appends 2 additional items to the list. But, when you click it, the array goes from length of 1 to length of 4 and submit has the same items in it.

It duplicates the last item in the list. Also, if I were to change it to append 3 items, it would have 6 items, duplicating the last two. But after you do it once, additional clicks work correctly.

https://user-images.githubusercontent.com/289053/110947162-6bb48580-8305-11eb-99ee-e26efe838c30.mov

**Comment by bluebill1049** [comment]
thanks @kalley 👍 patching this.

**Comment by kalley** [comment]
Thanks @bluebill1049! Appreciate your quick responses!

**Comment by bluebill1049** [comment]
no worries @kalley thanks for the detailed reporting. 🙏
