### ISSUE TITLE
v7 migration issue when using innerRef

### ISSUE THREAD

**Issue by krnlde** [react-hook-form/react-hook-form#4414]
Hey Bill!
It's been a while :D

right now I'm fiddling with the latest version of RHF and struggle migrating a Reactstrap component. In v6 I used to do:

```tsx
import { Input } from 'reactstrap';

// ... later 

<Input
  type="email"
  id="username"
  name="username"
  invalid={usernameHasErrors}
  placeholder={t(`LOGIN.USERNAME`)}
  autoComplete="username"
  innerRef={register({ // <------ SEE HERE
    required: true,
  })}
/>
```

when now the [migration guide](/react-hook-form/react-hook-form/releases/tag/v7.0.0-rc.0) tells me to do this:

```tsx
import { Input } from 'reactstrap';

// ... later 

<Input
  type="email"
  id="username"
  name="username"
  invalid={usernameHasErrors}
  placeholder={t(`LOGIN.USERNAME`)}
  autoComplete="username"
  {...register('username', { // <------ SEE HERE
    required: true,
  })}
/>
```

which is not working anymore. Would you recommend to migrate to your `<Controller />` entirely, or could I keep the HTML and I'm just missing something?

Cheers and greetings from Germany :)

**Comment by bluebill1049** [comment]
hey @krnlde how are you? 

you will have to do the following. 

```
const { ref, . .. rest } =  register('test')

return <Input innerRef={ref} {...rest} />;
```

Cheers
Bill

**Comment by krnlde** [comment]
Hey Bill, I'm really great. Woring from home has its upsides :D

Your suggestion works but changes a lot of code when having a form with 10+ inputs. In that case you have a lot of loose variables cluttering the component. I'll need to reconsider the current approach and move to a wrapped component which does the spread you suggested (or move to the Controller right away).

**Comment by bluebill1049** [comment]
Hey @krnlde, yea, I started WFH more as well (props and cons), but I think the whole pandemic is slowly recovering, soon it will return to normal. 

Yea, for input that doesn't expose `ref` name, it's probably easier to use `useController` or `Controller`, V7 is worth the upgrade and it has a lot of improvements.

**Comment by Unforgiven-wanda** [comment]
Hello,
This particular issue makes it impossible the project I am currently working on, one that relies on Reactstrap heavily.
I have hundreds of forms and thousands of inputs and I just can't imagine making this change to every form one by one.
Is there no more concise way of going about this? Maybe expose a custom innerRef or a codemod or anything?
Thank you.

**Comment by bluebill1049** [comment]
> Hello,
> This particular issue makes it impossible the project I am currently working on, one that relies on Reactstrap heavily.
> I have hundreds of forms and thousands of inputs and I just can't imagine making this change to every form one by one.
> Is there no more concise way of going about this? Maybe expose a custom innerRef or a codemod or anything?
> Thank you.

I do aware of this tradeoff, I would recommend you to stay with v6 as it's still getting maintained.

**Comment by Unforgiven-wanda** [comment]
For posterity, and to anyone who might stumble on this issue in the future:
The simplest solution to upgrading from V6 to V7 while using components that require an innerRef (in this case Reactstrap) was this

1. Follow the [migration guide](https://react-hook-form.com/migrate-v6-to-v7). It's painless as codemods automate most of the work. Just make sure not miss any steps. (If you're starting with V7 ignore this step)
2. Assuming now that my JSX file looks something like this:
```javascript
import { FormGroup, Label, Input, FormFeedback } from 'reactstrap'

<FormGroup>
  <Label>Unité</Label>

  <Input
    {...register('myinput')}
    readOnly={readOnly}
    className={`${isLoading}`}
    invalid={!!errors.myinput}
  />

  {errors.myinput && (
     <FormFeedback>
       {errors.myinput.message}
     </FormFeedback>
  )}
</FormGroup>
```
Simply create a new `Input` component that will forward the ref we get from `register`
```javascript
// Input.tsx file
import React from 'react';
import { Input } from 'reactstrap';

const WrappedInput = React.forwardRef((props, ref) => (
  <Input innerRef={ref} {...props} />
));

export default WrappedInput;
```

And use this new Input in our components, instead of the one directly from `Reactstrap` like this:
```javascript
import { FormGroup, Label, FormFeedback } from 'reactstrap';
import Input from './Input'
// Same code as before...
```
And just like that we have painlessly made the upgrade.
I hope this helps whoever stumbles upon this issue in the future.
Good day to all.

**Comment by andresebr** [comment]
The solution proposed by @Unforgiven-wanda is exactly what I did when migrating to version 7. And it works, except for when the field needs to be prepopulated (display a default value). When the component gets mounted all fields that should be displaying values by default are empty. Here's how my code looks:

```js
  <FormGroup>
    <Label for="firstName" className="required">
      First Name
    </Label>
    <CCInput
      disabled={!isEditableField}
      maxLength={
        memberDemographicsInfo ? memberDemographicsInfo.nameFieldMaxLength : 50
      }
      autoComplete="given-name"
      {...register("firstName")}
      id="firstName"
      defaultValue={
        memberDemographicsInfo && memberDemographicsInfo.firstName
      }
    />
    <CCFormError error={errors.firstName && errors.firstName.message} />
  </FormGroup>
```

And my custom input component.

```js
import React from "react";
import { Input, InputProps } from "reactstrap";

interface CCInputProps extends InputProps {}

const CCInput = React.forwardRef<any, CCInputProps>((props, ref) => (
  <Input innerRef={ref} {...props} />
));

export default CCInput;
```

`defaultValue` should be displayed if the filed has a default value after fetching `memberDemographics` but that's not happening for some reason. The field stays empty no matter the value of `firstName`.

**Comment by andresebr** [comment]
The solution proposed by @Unforgiven-wanda is exactly what I did when migrating to version 7. And it works, except for when the field needs to be prepopulated (display a default value). When the component gets mounted all fields that should be displaying values by default are empty. Here's how my code looks:

```js
  <FormGroup>
    <Label for="firstName" className="required">
      First Name
    </Label>
    <CCInput
      disabled={!isEditableField}
      maxLength={
        memberDemographicsInfo ? memberDemographicsInfo.nameFieldMaxLength : 50
      }
      autoComplete="given-name"
      {...register("firstName")}
      id="firstName"
      defaultValue={
        memberDemographicsInfo && memberDemographicsInfo.firstName
      }
    />
    <CCFormError error={errors.firstName && errors.firstName.message} />
  </FormGroup>
```

And my custom input component.

```js
import React from "react";
import { Input, InputProps } from "reactstrap";

interface CCInputProps extends InputProps {}

const CCInput = React.forwardRef<any, CCInputProps>((props, ref) => (
  <Input innerRef={ref} {...props} />
));

export default CCInput;
```

`defaultValue` should be displayed if the filed has a default value after fetching `memberDemographics` but that's not happening for some reason. The field stays empty no matter the value of `firstName`. Default values work if I remove the `innerRef={ref}` from the Input.
