### ISSUE TITLE
nested value disappear when remount NestedFieldArray 

### ISSUE THREAD

**Issue by TseHang** [react-hook-form/react-hook-form#4416]
**Describe the bug**
I have a nested array form, and some components need to be hidden when `show` flag is false.
The form will remove component when show is false, and mount component when flag is true.
It is perfect at the first level field array. However, in nested-field-array, we lose the default values after we re mount it.

I am not sure it is a bug or I misunderstood the correct way. 😭
Please help me!

**To Reproduce**

1. Go to [code sandbox link](https://codesandbox.io/s/react-hook-form-nestedarray-empty-issue-fpolt?file=/src/Item.js)
2. Click "show" checkbox in first level
3. See our nested array components.
3. Click test1's "show" checkbox.
4. See test1's children(nested field array)
5. Click test1's "show" checkbox.
6. Hidden test1's children(nested field array)
7. Click test1's "show" checkbox.
8. **LOL... We can not see the test1's children(nested field array)**

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.
https://codesandbox.io/s/react-hook-form-nestedarray-empty-issue-fpolt?file=/src/Item.js

**Expected behavior**
1. Go to [code sandbox link](https://codesandbox.io/s/react-hook-form-nestedarray-empty-issue-fpolt?file=/src/Item.js)
2. Click "show" checkbox in first level
3. See our nested array components.
3. Click test1's "show" checkbox.
4. See test1's children(nested field array)
5. Click test1's "show" checkbox.
6. Hidden test1's children(nested field array)
7. Click test1's "show" checkbox.
8. **See the test1's children(nested field array)**

**Screenshots**
![螢幕錄製 2021-03-13 下午3 06 57](https://user-images.githubusercontent.com/14778824/111022698-5a57a000-840f-11eb-953b-7c6d24e658f9.gif)

**Desktop (please complete the following information):**

- OS: macOS Big Sur 11.0.1
- Browser: Safari 14.0.1
- React Hook Form Version: 16.15.4

**Additional context**
I am not sure it is a bug or I misunderstood the correct way. 😭
IMO, I should get defaultValue when mount a fieldArray component. And it works on the version 6.14.2
https://codesandbox.io/s/react-hook-form-nestedarray-empty-issue16142-wrznk?file=/src/Item.js

**Comment by bluebill1049** [comment]
for v6, you can set config `shouldUnregister: false`. this will be the default behavior in v7.

**Comment by TseHang** [comment]
If it is possible, I have another questions about this example: https://codesandbox.io/s/react-hook-form-nestedarray-empty-issue16154-fpolt

1. Although I watch in the `Item.js` component, looks like it triggers the whole field array... Why? However, it works expected
way when using `useWatch`.
2. `renderCount` always add 2 when I click `show` flag, however, only get one log in console... curiously 😭

**Comment by TseHang** [comment]
> for v6, you can set config `shouldUnregister: false`. this will be the default behavior in v7.

Thanks, it resolves my problem with below link.

**Comment by bluebill1049** [comment]
watch is always at root, useWatch at component level.

**Comment by TseHang** [comment]
I have a little strange about  why my link can work on `6.14.2`? but I can not work on `6.15.4`?
6.15.4: https://codesandbox.io/s/react-hook-form-nestedarray-empty-issue16154-fpolt
6.14.2: https://codesandbox.io/s/react-hook-form-nestedarray-empty-issue16142-wrznk
---
In my example `6.15.4`,
At root level's `show flag`: It works with defaultValue after unmount.
At children nested level's `show flag`: It can not get defaultValue after unmount.
What is the reason?

![螢幕錄製 2021-03-13 下午4 24 24](https://user-images.githubusercontent.com/14778824/111024261-b3780180-8418-11eb-9bab-34769a0b8d78.gif)


**I am not sure, but maybe my real problem is why I can not get defaultValues in nested-field-array after re-mount?**

p.s. In `6.14.2`, I don't set `shouldUnregister: false`, and I can get the defaultValues in root & nested children level.

**Comment by TseHang** [comment]
> watch is always at root, useWatch at component level.
Thanks!!!!

> 2. `renderCount` always add 2 when I click `show` flag, however, only get one log in console... curiously 😭
Could somebody tell me why ?

**Comment by bluebill1049** [comment]
for unmounted inputs to be retained with value, use `shouldUnreigster: false` otherwise consider upgrading to v7 as it's in RC now.

**Comment by TseHang** [comment]
Curiously, how if I want to set value to a re-registered component ?

I use setValue in this way is not worked 😢
https://codesandbox.io/s/react-hook-form-nestedarray-empty-issue16154-setvalue-btsqs
