### ISSUE TITLE
v6: useWatch returns empty value on rerender

### ISSUE THREAD

**Issue by jurij** [react-hook-form/react-hook-form#4419]
**Describe the bug**
In `v6` the hook `useWatch` returns empty value after rerender.
Behavior in `v7` is as expected.

**To Reproduce**

not working example with `v6` see https://codesandbox.io/s/admiring-colden-osv63?file=/src/App.js:
1. Open codesandbox
2. Enter something  in input field `childValue`
3. Press `toggle` button twice, to hide and show `UseWatchOutput`
4. output is empty

working example with `v7` see https://codesandbox.io/s/nostalgic-bhaskara-9l85u?file=/src/App.js:
1. Open codesandbox
2. Enter something  in input field `childValue`
3. Press `toggle` button twice, to hide and show `UseWatchOutput`
4. output is value of `step 2`

**Expected behavior**
v6 probably should work like v7 in this case

**Comment by bluebill1049** [comment]
v6 will need a `defaultValue` for the first invoke before render. It's by design and "improved" in v7.
