### ISSUE TITLE
TypeError  Object.values is not a function

### ISSUE THREAD

**Issue by andrisole92** [react-hook-form/react-hook-form#4424]
**Describe the bug**
So, I can't reproduce it, but my APM reports it (it happens rarely)

**To Reproduce**
The exact piece of code:

```
      Object.values(fieldsRef.current).forEach(function (field) {
        return removeFieldEventListenerAndRef(field, true);
      });
```
./node_modules/react-hook-form/dist/index.esm.js in c at line 2035:14

**Expected behavior**
Should not throw an exception

**Desktop (please complete the following information):**

- OS: Android 5.1
- Browser: Chrome Mobile Version:49.0.2623

**Smartphone (please complete the following information):**

LS-5018

**Comment by bluebill1049** [comment]
https://react-hook-form.com/faqs#BrowserSupport
