### ISSUE TITLE
WatchObserver generic type is not provided

### ISSUE THREAD

**Issue by lionskape** [react-hook-form/react-hook-form#4425]
https://github.com/react-hook-form/react-hook-form/blob/f44096026a3d1e849221dd57a213d132b4ac6fca/src/useForm.ts#L767

Seems like it should be like this:
```WatchObserver<TFieldValues>```

**Comment by bluebill1049** [comment]
send us a PR if you have time. 👍

**Comment by bluebill1049** [comment]
it's actually a callback :) we good.
