### ISSUE TITLE
Adding empty objects when submiting values for field array inputs.

### ISSUE THREAD

**Issue by sarbazx** [react-hook-form/react-hook-form#4427]
**Describe the bug**
Form is registering non registered array fields with indexes.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-qc13y
2. Enter inputs
3. Click submit query
4. See concole

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-qc13y

- [useForm](https://codesandbox.io/s/react-hook-form-useform-template-lsm61) Template
- [useFieldArray](https://codesandbox.io/s/react-hook-form-usefieldarray-template-q0jek) Template
- [Controller](https://codesandbox.io/s/react-hook-form-controller-template-yu0z5) Template

**Expected behavior**
There are too many empty fields, it should not exist.

**Screenshots**
![image](https://user-images.githubusercontent.com/5629946/111150540-46db3f00-859f-11eb-8761-4ff3c5d917ad.png)

**Desktop (please complete the following information):**

- OS: MacOS BigSur 11.2.3
- Browser Firefox Developer Edition
- Version 87.0b8 (64-bit)

**Smartphone (please complete the following information):**
didn't test on smartphone

**Additional context**
N/A

I just want only fields that has been registered, why it is registiring automatically non registered fields?

**Comment by kpnigalye** [comment]
Looks like you are not using it correctly. Please checkout my solution which uses useForm and useFieldArray to load the values from myInputes.

https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-5gz28?file=/src/index.js

**Comment by sarbazx** [comment]
> Looks like you are not using it correctly. Please checkout my solution which uses useForm and useFieldArray to load the values from myInputes.
> 
> https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-5gz28?file=/src/index.js

I see in your solution you didn't specify id on myInputs, is react-hook-form generating it?

**Comment by bluebill1049** [comment]
<img width="875" alt="Screen Shot 2021-03-16 at 9 04 45 am" src="https://user-images.githubusercontent.com/10513364/111227423-a9334e80-8636-11eb-8ab7-d8d54ba47ce0.png">

yes, you will need to change keyName to something else.

**Comment by kpnigalye** [comment]
> > Looks like you are not using it correctly. Please checkout my solution which uses useForm and useFieldArray to load the values from myInputes.
> > 
> > https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-5gz28?file=/src/index.js
> 
> I see in your solution you didn't specify id on myInputs, is react-hook-form generating it? also ids are string so when submitted it is in object form but I want them in array format, how can I achieve that?

Yes React hook form generates ids for you so when you are mapping **fields**, you can assign it as a key to your input. So the final output will be an array as you are passing reference to your input field.

**Comment by bluebill1049** [comment]
thanks @kpnigalye 👍

**Comment by sarbazx** [comment]
@kpnigalye thanks for the code, another question :) if input values are set using setValue, without defaulValues, how to use useFieldArray?

**Comment by bluebill1049** [comment]
It would be the same. 

```
useEffect(() => {
  setValue('fieldArray', [....])
})

{fields.map(...)}
```

the important part is not to overwrite the `id` from `useFieldArray`, you can host your own field array id by changing the `keyName` in the config and store your own `id` in the hidden input.

hope above make sense.
