### ISSUE TITLE
setError types

### ISSUE THREAD

**Issue by sinnlosername** [react-hook-form/react-hook-form#443]
Hi.

I am using WebStorm as my IDE, which has support for typescript. It does show you a warning if you're using a value as an argument which does not match the functions signature. This happens for me when using the setError method. Is this a problem with your types or with the inspection of the IDE?

![screenshot](https://user-images.githubusercontent.com/17328331/68063506-e634c480-fd11-11e9-881a-f6b4d3433cb1.png)

**Comment by bluebill1049** [comment]
lovely, I am a webstorm user as well:

<img width="331" alt="Screen Shot 2019-11-02 at 11 43 13 am" src="https://user-images.githubusercontent.com/10513364/68063534-01c9ba80-fd66-11e9-9162-017df43e4e45.png">

**Comment by sinnlosername** [comment]
It seems as it only shows the warning when using normal javascript (but still with types completion). If I understand it correctly the type definition states that FieldName must be a key of FormValues, however when using normal javascript you can not define FormValues as it's a generic type, can you?

Test.js
```
import React from "react";
import useForm from "react-hook-form";

function Test() {
  const {setError} = useForm();

  setError("test", "custom", "");

  return (<div></div>)
}
```

**Comment by bluebill1049** [comment]
i think you are missing the type

`const {setError} = useForm<FormType>();

**Comment by sinnlosername** [comment]
As I said, it's plain js, there are no generics. But I am not sure if you can possible fix that (haven't got that much knowledge about typescript). I also got a similar problem with handleSubmit, which expects a method returning void or Promise<void>, but you can't really get a Promise<void> without typescript.

**Comment by bluebill1049** [comment]
I am a little bit confused, are you using typescript or just pure JS? if you are using pure JS you don't need type and if it shows your warning/error then it's your IDE. If you are using typescript then you should provide types.

**Comment by sinnlosername** [comment]
I am using pure js, but it still shows me if I offer the right types to your function, as typescript libraries quite commonly check the types supplied to their functions. I was just wondering why it's showing such an error if the types are correct, but I guess that's the lack of generics in pure js. As I said in my original question, I'm not really sure if it's a problem with the types or just the IDE.^^

**Comment by bluebill1049** [comment]
Yea I think it’s IDE related :) because I used both typescript and pure JS at work
