### ISSUE TITLE
V7 onSubmit mode doesn't switch to onChange after submit click

### ISSUE THREAD

**Issue by olesmarola** [react-hook-form/react-hook-form#4433]
**Describe the bug**
If use default mode "onSubmit", validation fires after submit button click and then validation need to fire on every change, but it doesn't.

**To Reproduce**

1. Use "mode: 'onSubmit'"
2. Click on submit button
3. Change some field with validation to make it valid.
4. Error message persists (but it needs to be deleted).

**Codesandbox link (Required)**
https://codesandbox.io/s/musing-rhodes-u0wom?file=/pages/index.js

**Expected behavior**
After submitting button click validate on every change

**Additional context**

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848
