### ISSUE TITLE
Custom checkbox bug / question, cannot trigger onChange event of the custom checkbox

### ISSUE THREAD

**Issue by klendi** [react-hook-form/react-hook-form#4440]
**Describe the bug**
When using a custom checbox, and you forward ref from a component you can't use setValue to make a checkbox active. Or how to trigger the onChange event of the checkbox when setting the value with react-hook-form. Perhaps it isn't supposed to call the onChange event and I may be wrong.

**To Reproduce**
1. Create custom checkbox component.
2. Forward Ref from the component.
3. Set value using `setValue("name", true)`

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-custom-checkbox-forked-h2u1i?file=/src/App.js

**Expected behavior**
To trigger onChange when you setValue

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome

**Additional context**
Is there any way to trigger the event. Because the custom checkbox isn't changed at all. When you click on it it works. But with set value can't find a way on how to do it using react hook form.

**Comment by bluebill1049** [comment]
If you want to invoke `onChange`, use `useController`. setValue with register will directly update the dom value.

**Comment by klendi** [comment]
How does setValue of useForm works? How it doesn't trigger onChange, because I'm trying to keep a standard, using useForm instead of useControl. Is that possible ?

**Comment by klendi** [comment]
What I am having a problem with kinda "defaultValue", when I fetch the data I set the value, but with a custom checkbox that doesn't work. I don't have a way how to check the custom checkbox, I thought react hook form would do that and onChange event would be triggered so I would have the opportunity to change it. Without doing any hacks

**Comment by bluebill1049** [comment]
> when I fetch the data I set the value, but with a custom checkbox that doesn't work. 

share an example?
