### ISSUE TITLE
Register argument cache issue

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#445]
**Describe the bug**
I had to build a form with something like 25 fields, where some of them where dependent of others. The main problem I had was trying to validate field B against field A, because the register function only considers the value of the input itself.

(value) => value >0 || 'value should be greater than 0'

Of course you can pass it a second argument, and it will work.

(value, rest) => value >rest.fieldA|| 'value should be greater than fieldA'

Now, when I had to pass a compare Value which was a state, that's when I realized that this library, among many of its optimizations, also saves the initial function that you pass it, meaning that if the arguments you pass to the function change, the library won't validate correctly with the new params.

const [selectedCurrency, setSelectedCurrency] = useState('dolar')

(value, rest) => validate something with rest. selectedCurrency || 'Error Message depending on selected currency '

That last example won't work, and I had to fork the library to force a register of a field and it's validation dictionary so it would consider changing validation params.

**Additional context**
https://www.reddit.com/r/reactjs/comments/dq2v1f/build_the_next_generation_of_forms_with_react/

**Comment by bluebill1049** [comment]
test with `3.26.5-beta.3`

**Comment by hnromante** [comment]
Thanks for taking a look at my comment, this fixed the issue.

**Comment by bluebill1049** [comment]
my pleasure @hnromante I am glad it workes now :)

**Comment by bluebill1049** [comment]
by the way, if you find this lib useful please consider to drop a star to support it as well :) thanks
