### ISSUE TITLE
V7 - trigger validation for a single input rerenders full form

### ISSUE THREAD

**Issue by fantapop** [react-hook-form/react-hook-form#4456]
**Describe the bug**
I'm unable to use input validations in custom components that use onChange handlers and setValue because calling `trigger('myfield');` rerenders the entire form.  I wasn't sure if this was intentional behavior or not.  Since setValue doesn't trigger a check for validations directly, it means that any direct usage of setValue can result in an invalid value being set in the form.  The fields are still being validated during the submit phase but if the form is intended to be validated onChange this is not ideal.  Thank you for all your work on this project. It really makes forms easy to use!

**To Reproduce**

1. visit the code sandbox link below
2. Click into the input with the placeholder "customInput"
3. start typing
4. See error render counts for all components going up

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-custom-input-forked-rk1tc?file=/src/index.js

**Expected behavior**
Triggering a validation for a single field should not rerender all fields

**Desktop (please complete the following information):**

- OS: macos
- Browser: chrome
- Version: 89

**Smartphone (please complete the following information):**

**Comment by bluebill1049** [comment]
<img width="1060" alt="Screen Shot 2021-03-18 at 7 12 30 pm" src="https://user-images.githubusercontent.com/10513364/111593282-e443a680-881d-11eb-9bef-33b9ecffba58.png">

can you share more detail on how to reproduce? i couldn't find what you referred above with the steps.

**Comment by bluebill1049** [comment]
<img width="702" alt="Screen Shot 2021-03-18 at 7 56 07 pm" src="https://user-images.githubusercontent.com/10513364/111599058-fcb6bf80-8823-11eb-81eb-132405c77864.png">

there is no `trigger` usage as well.

**Comment by fantapop** [comment]
I apologize for that.  I didn't realize i needed to save the files in the codesandbox :-) 

I've gone through and saved them and verified its working now in incognito.

https://codesandbox.io/s/react-hook-form-custom-input-forked-rk1tc?file=/src/index.js

**Comment by bluebill1049** [comment]
that's expected, if you subscribed at the root, it will re-render at root.

**Comment by fantapop** [comment]
okay, thanks for your response.  When you say subscribe at a the root what do you mean?  Is there a different way to do this manually with onChange and setValue?

One approach I was considering is to have a function (external to RHF) which manually runs the validations. something like:

```javascript

const executeValidations = (value, validations) => {
  for(const validation of Object.values(validations)) {
    const result = validation(value);
    if (result !== true) {
      return result;
    }
  }
  return true;
}

  const handleCustomInputChange = useCallback(
    (e) => {
      setValue("customInput", e.target.value);
      const valid = executeValidations(e.target.value, validations);
      if (valid !== true) {
        trigger("customInput");     
      }
    },
    [setValue, trigger, validations]
  );
```

It needs some work to only call trigger on a change of validation state for just that component.

**Comment by bluebill1049** [comment]
`const { formState: { errors } } = useForm()`

that's root.

`const { errors } = useFormState` 

means at the component level.

**Comment by fantapop** [comment]
oh interesting!  That fixes the codebox example I shared.  My actually code is still rerendering so apparently i didn't distill down the problem correctly but this helps.  Thank you

**Comment by bluebill1049** [comment]
no worries @fantapop
