### ISSUE TITLE
calling onChange function in useEffect that is placed below (in app tree) useController doesn't rerender form

### ISSUE THREAD

**Issue by AntonBakinowsky** [react-hook-form/react-hook-form#4459]
**Describe the bug**
Calling `onChange` function from `useController` doesn't apply changes correctly so app tree is not updated with latest form state

**To Reproduce**

1. Create form component and add `useForm` usage
2. Create container component and add `useController` usage. Place container component inside form component
3. Create field component and add `useEffect` without second argument and call `onChange` function from `useController` from container component. In return render value of the field defined in `useController` and `isDirty` from `useForm` formState.
4. Add submit button. On submit call alert / console.log with from model passed to handleSubmit callback.
5. See that render of field component shows that `value` is `null` (which is default value) and `isDirty` is `false`.
6. Click submit button
7. See that alert / console.log shows that value is changed
8. See that field render now shows correct `value` (which you passed to `onChange` function in 3rd step)  and `isDirty` is `true`.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-with-usecontroller-and-onchange-in-different-components-t1yl6

**Expected behavior**
On step 5 `value` is rendered as it was changed on step 3 and `isDirty` is `true`

**Screenshots**
![ react-hook-form-with-useController-and onChange](https://user-images.githubusercontent.com/10063600/111629352-42629080-8802-11eb-8502-d2c6a69843e7.gif)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 89

**Comment by bluebill1049** [comment]
That's a question for the order invoke for `useEffect` right? The child `useEffect` will get overwritten by the parent one with onChange inside `useController`.

**Comment by bluebill1049** [comment]
I guess the real question is what you try to solve here.

**Comment by AntonBakinowsky** [comment]
> That's a question for the order invoke for `useEffect` right? The child `useEffect` will get overwritten by the parent one with onChange inside `useController`.

Yeap, I conducted some debugging and found out that `onChange` invokes `setInternalValue`.

![image](https://user-images.githubusercontent.com/10063600/111735903-d9c0f580-888d-11eb-9314-03120f76052a.png)

And `if` condition checks whether there is field ref and call function to validate and set dirty state.

But in my case there is no field  yet when this function is called due to `useEffect` with field registration haven't been invoked yet.

![image](https://user-images.githubusercontent.com/10063600/111736234-7d120a80-888e-11eb-90ed-975f009a41ee.png)

Yes, having `useController` and `useEffect` within the same component solves the problem. 
Interesting point for me is the order of `useEffect` calls. But I think it's just my lack of understanding of it that I need to get into :)

**Comment by AntonBakinowsky** [comment]
Thanks for the answer.

**Comment by bluebill1049** [comment]
no worries at all @AntonBakinowsky ❤️
