### ISSUE TITLE
[React Native] triggerValidation() not updating errors value on the same time

### ISSUE THREAD

**Issue by muhamad-rizki** [react-hook-form/react-hook-form#446]
**Describe the bug**
`<Button
        title="Submit"
        onPress={async () => {
          console.log('asdsasd', await triggerValidation())
          console.log('asdasdasd', errors);
      />`
after waiting triggerValidation() errors is not updated, after press for second time, it's now updated. But the field validation is fine, and input field can get the error message. maybe you can return errors value after triggerValidation? instead void, because I need updated errors after press submit to make scroll to specific input error. or maybe you can add error callback on handleSubmit

**Smartphone (please complete the following information):**
 - Device: Android emulator
 - OS: 9.0 Pie
 - React native apps
 - 0.59.9

**Comment by bluebill1049** [comment]
```<Button title="Submit" onPress={async () => { console.log('asdsasd', await triggerValidation()) console.log('asdasdasd', errors); />```

I think you should console log before the re-render.
```
console.log('errors', errors);
return {
  <Button title="Submit" onPress={async () => { console.log('asdsasd', await triggerValidation())} />
}
```

**Comment by muhamad-rizki** [comment]
> `<Button title="Submit" onPress={async () => { console.log('asdsasd', await triggerValidation()) console.log('asdasdasd', errors); />`
> 
> I think you should console log before the re-render.
> 
> ```
> console.log('errors', errors);
> return {
>   <Button title="Submit" onPress={async () => { console.log('asdsasd', await triggerValidation())} />
> }
> ```
> 
> if you refer to the documentation, https://react-hook-form.com/api/#triggerValidation this api return `boolean` to indicate validation failed or success.

sure but it will make function I tried to call multiple times called, what I tried to achieve here is something like this:
```
await triggerValidation();
if(errors[fieldKey]){
const offset = itemHeights[fieldKey];
scrollToComponent.current.scrollToOffset({ offset });
}
```

**Comment by bluebill1049** [comment]
```
useEffect(() => {
  if(errors[fieldKey]){
    const offset = itemHeights[fieldKey];
    scrollToComponent.current.scrollToOffset({ offset });
  }
}, [errors])
```
what about `useEffect`?

**Comment by muhamad-rizki** [comment]
> useEffect(() => {
>   if(errors[fieldKey]){
>     const offset = itemHeights[fieldKey];
>     scrollToComponent.current.scrollToOffset({ offset });
>   }
> }, [errors])

ah I forgot about the useEffect, thanks for pointing it. :)

**Comment by bluebill1049** [comment]
no worries
