### ISSUE TITLE
please update the documents pages  like the "useForm" and replace the "as" props which is deprecated with "render"

### ISSUE THREAD

**Issue by Alirez14** [react-hook-form/react-hook-form#4462]
**Describe the bug**
some documentations still use "as" prop instead of "render"

**Additional context**
https://react-hook-form.com/api#control

**Comment by bluebill1049** [comment]
This is already updated in v7 doc: https://react-hook-form-website-git-v7-bluebill1049.vercel.app/api/useform/control

if nothing goes wrong, should release in 2 weeks.
