### ISSUE TITLE
isDirty false positive when default value of array field is []

### ISSUE THREAD

**Issue by jgomez-nydig** [react-hook-form/react-hook-form#4463]
**Describe the bug**
The form goes into a dirty state after blurring a field and stays that way even if the data hasn't changed, this happens only when the default value of an array field is []

**To Reproduce**

- Blur a field without making changes
- isDirty will be set to true
or
- Make changes an undo them
- isDirty will be set to true and remain that way
or
create a new entry and delete it

I created a sandbox that replicates the issue:
https://codesandbox.io/s/relaxed-davinci-07nwg?file=/src/App.js

**Expected behavior**
isDirty goes back to false

**Screenshots**
See the sandbox example
<img width="594" alt="Screen Shot 2021-03-18 at 1 28 46 PM" src="https://user-images.githubusercontent.com/74317197/111678082-e130c200-87ed-11eb-9ac7-cd0a9931e402.png">

**Desktop (please complete the following information):**

- OS: iOS
- Browser chrome
- react-hook-forms v6.15.4

**Comment by bluebill1049** [comment]
That's expected. we are doing deep equal again what's on the screen and `defaultValues`, in your case

const defaultValues = {
  test: "initial",
  testArray: []
};

vs

const defaultValues = {
  test: "initial"
};

**Comment by jgomez-nydig** [comment]
how can I know what is being compared underneath to determine isDirty? this is a bit of an unexpected behavior since the value of the array didn't change but isDirty is set to true

**Comment by bluebill1049** [comment]
remove `testArray: []`
