### ISSUE TITLE
Form is rerender after first validation of each input

### ISSUE THREAD

**Issue by czmacer** [react-hook-form/react-hook-form#4464]
**Describe the bug**
Form is in onBlur mode and each input have custom validation. First blur of each input start new form render due to "hooks changed" event.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-rerender-first-change-3zgxf?file=/src/App.js

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome

**Comment by czmacer** [comment]
![2021-03-18 09-56-35_5](https://user-images.githubusercontent.com/7201802/111706358-7067c500-8842-11eb-882e-72ead7d074fe.gif)

**Comment by bluebill1049** [comment]
because you are on `onBlur` mode, so touched field is getting updated and get re-rendered at the root. This behavior is getting enhanced on V7.

https://codesandbox.io/s/react-hook-form-rerender-first-change-forked-v3tc0?file=/src/App.js
