### ISSUE TITLE
Add "isSubmitting" in useController().meta

### ISSUE THREAD

**Issue by ivanhoe-dev** [react-hook-form/react-hook-form#4465]
**Is your feature request related to a problem? Please describe.**
I'm currently wrapping my controller with a "Smart Form Component". In this case, my formState is inside another component, which my controller input can't access. In order to make my controller input able to disable according to the is Submitting flag, would like to request for adding it in useController().meta

**Describe the solution you'd like**
Add "isSubmitting" in useController().meta

**Describe alternatives you've considered**
I try to smartly restructure my JSX and render them to the form react-hook-form support, but not working, also not clean way to do so

**Comment by bluebill1049** [comment]
This is already part of the v7, `useController` with have full access to `formState`

**Comment by ivanhoe-dev** [comment]
Thanks! Didn't notice that. :)

**Comment by ivanhoe-dev** [comment]
@bluebill1049 Sorry, but I just upgraded to v7 and not so sure how to access isSusbmitting. May I have some guide?
![image](https://user-images.githubusercontent.com/39026006/111757136-f8e37580-88d5-11eb-8c22-3f9060065559.png)

**Comment by PeterKerins** [comment]
@ivanhoe-dev You'll need to destructure isSubmitting.

<img width="904" alt="Screenshot 2021-03-20 at 10 39 50" src="https://user-images.githubusercontent.com/17780655/111866921-b323bd00-8968-11eb-98c9-ac6411bb9738.png">
