### ISSUE TITLE
isValid computed incorrectly when dynamically adding required fields

### ISSUE THREAD

**Issue by krnlde** [react-hook-form/react-hook-form#447]
**Describe the bug**
The `isValid` state lags one tick behind the actual validation state when having dynamic form fields registered later. 

**To Reproduce**
1. Go to https://codesandbox.io/s/dawn-tree-yrwfk
2. Switch between the two radios ("Bank Transfer", which is `valid` instantly and "Debit", which requires more fields, hence `invalid`)

Note: when I blur the radio after changing it, the `isValid` gets rerendered and is then correct, but right after the toggle its incorrectly "false"

**Codesandbox link**
https://codesandbox.io/s/dawn-tree-yrwfk

**Expected behavior**
The `isValid` state should be rerendered immediately after registering new fields.

**Desktop (please complete the following information):**
 - OS: Win 10 1909
 - Browser: Chrome 78.0.3904.87, Chromium Edge 80.0.320.0

Thanks for the awesome project! Nice work ❤️

**Comment by bluebill1049** [comment]
Thank you for the detailed issue report (really made my life much easier) a patch will be landed on this issue. I will release a beta for you to verify the issue as well :) thanks

**Comment by bluebill1049** [comment]
`react-hook-form@3.26.5-beta.4`

**Comment by krnlde** [comment]
Darn, you're fast 🚤 !! The described issue works like a charm, but going back to the "Debit" in the codesandbox it renders it incorrectly as invalid. Verify here: https://codesandbox.io/s/zealous-visvesvaraya-or3ee

**Comment by bluebill1049** [comment]
aha, @krnlde thank you. I will sort out this during lunchtime :) I need to get off my bed now.

**Comment by bluebill1049** [comment]
couldn't help myself thinking about the issue on the bus...  `react-hook-form@3.26.5-beta.5` this should be it

**Comment by krnlde** [comment]
Now I have to get out of bed and try it :D ...

**Comment by bluebill1049** [comment]
haha 💃

**Comment by krnlde** [comment]
It works! https://codesandbox.io/s/magical-bush-z7sxe

🙇

**Comment by bluebill1049** [comment]
OH YEAH ~

**Comment by krnlde** [comment]
Hey man :) This error is back again in `3.28.14` and `3.29.0-beta.1`.

See for reference: https://codesandbox.io/s/interesting-merkle-0yvw7

**Comment by bluebill1049** [comment]
... i did even add automation test this time. I will take a look tonight.

**Comment by bluebill1049** [comment]
This time I will patch it and add a automation test with ur codesandbox example. 👍🏻

**Comment by bluebill1049** [comment]
Some background reference why these happening: I did some refactoring to clean up isValid logic (simplify) which lead to those regression issue, but once we nail it and it’s better for the long term ❤️

**Comment by bluebill1049** [comment]
`react-hook-form@3.28.15-beta.1` please help to verify

**Comment by krnlde** [comment]
I updated the codepen with the version `3.28.15-beta.1` but it doesn't seem to work :(

https://codesandbox.io/s/priceless-yonath-wiv6o

To reproduce:
1. Click on "Bank Transfer" (form will get valid)
2. Click on "Direct Debit" (form should get invalid immediatelly)
3. Click somehwere else to trigger the `blur` (form actually gets invalid)

**Comment by bluebill1049** [comment]
thanks @krnlde for testing

**Comment by bluebill1049** [comment]
please testing this one for me `3.28.15-beta.2` (i did my own testing as usual :(

**Comment by krnlde** [comment]
I can confirm it works with `3.28.15-beta.2` 🥇 

working example: https://codesandbox.io/s/dreamy-swartz-y5hgp

**Comment by bluebill1049** [comment]
amazing i will add some automation to lock it in.

**Comment by bluebill1049** [comment]
much appreciated your help and support @krnlde i will add your name in the release note. thank you ❤️

**Comment by krnlde** [comment]
🙇

**Comment by krnlde** [comment]
Hey hey hey! I'm back again with a wonderful variation of this bug! This time it's a little more complicated to reproduce, but it's the same error as the original title states.

If I have nested error objects (as recommended in the [API docs](https://react-hook-form.com/api#errors)) I can produce an invalid state, despite being valid.

**To reproduce:**

1. Go to this sandbox: https://codesandbox.io/s/great-leakey-resm7
2. Notice `isValid: false` correctly
3. Activate the "Bank transfer" radio
4. Notice `isValid: true` correctly
5. Activate the "Direct Debid" radio
6. Notice `isValid: false` correctly
7. Change something in an input field that just appeared _**and then delete it**_ (this part is crucial)
8. Notice `isValid: false` correctly
9. Activate the "Bank transfer" radio again which removes the debit inputs from the DOM and also should remove their required-ness
10. Notice `isValid: false` **incorrectly**

If you do not do step 7 (inserting something and then removing it), the `errors` object will be empty and therefore the bug won't appear. I got the same result when hitting the "Validate" button at this step.

The reason is, that the `errors` Object holds an empty `debit` property. It looks like this: `{debit: {}}`
My guess is `isValid` is calculated by `Object.keys(errors).length` or something.

The solution would be to remove the dangling, empty nest-object.

**Comment by bluebill1049** [comment]
Thank you ❤️ @krnlde fixed already :) will release this weekend. you can try with the latest beta.

**Comment by krnlde** [comment]
Works in `4.9.9-beta.3` 🎉 🎉 🎉 You're the fastest man on github :P

**Comment by bluebill1049** [comment]
lol not really @krnlde i had the fix in beta just haven't released the fix. that's why.

**Comment by krnlde** [comment]
...so you fix issues before they are posted :P That's lightning-fast!
