### ISSUE TITLE
Multiple submit button with different values

### ISSUE THREAD

**Issue by edimitchel** [react-hook-form/react-hook-form#4470]
**Describe the bug**
_It's may be a bug or simply a misusage of form._
I have a form with two submit button, and I would like to know on submit on which button the user clicked.
With `input[type=button]`, it's working, but on my case, I would like to do it with native `button`, not `input`.

**To Reproduce**

1. Click on first submit button (option 1)
2. See the form state in the alert : `button_submit` key have option 2, and not the option 1.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-submithandler-forked-6ddr1?file=/src/App.tsx

**Expected behavior**
Both submit button and input should permits to differentiate option clicked.

**Comment by bluebill1049** [comment]
why are you `register` all the buttons with value? I would prefer to store value in a hidden input.

<img width="939" alt="Screen Shot 2021-03-20 at 10 54 05 am" src="https://user-images.githubusercontent.com/10513364/111852318-98524800-896a-11eb-830a-5271ac294da5.png">
