### ISSUE TITLE
[fieldState] unexpected behavior when fieldState is read

### ISSUE THREAD

**Issue by deebov** [react-hook-form/react-hook-form#4474]
**Describe the bug**
I know, this is a super edge case but we're currently in this situation. When `fieldState.error` or `formState.errors` is read inside `Controller` there's an unexpected behavior with removing field item. When you remove, for example, the first item the last item gets duplicated in the field array value but fields are not affected. It's 10x better if you see this issue yourself.

**To Reproduce**

1. Go to https://codesandbox.io/s/fragrant-firefly-xjp98?file=/src/App.tsx
2. Add a few fields (e.g. 3)
3. Select some values
4. Remove the first field
5. You should see the last field value get duplicated

However, if you remove the lines where `formState` or `fieldState` is read inside the `SelectController` it will work as expected. Or if you replace `onPress` of the button with `onClick`.

**Codesandbox link (Required)**
https://codesandbox.io/s/fragrant-firefly-xjp98?file=/src/App.tsx

**Expected behavior**
Field array value is stable and synced when `fieldState` or `formState` is read inside `Controller` AND when using `onPress` of button.

**Screenshots**
<details>
  <summary>Events value before removing the first item:</summary>

![image](https://user-images.githubusercontent.com/28673719/111866828-08c08f80-8992-11eb-9d5b-c375c6a87688.png)
</details>

<details>
  <summary>After removing the first item:</summary>

![image](https://user-images.githubusercontent.com/28673719/111866830-1118ca80-8992-11eb-92b3-a72427a49e61.png)
</details>

**Additional context**
I'm using the latest possible version of all libraries.
Again, this is an extremely rare use case but we found ourselves in this exact situation. We have a big UI component library built with `react-hook-form`, `react-aria`, `yup`, `stitches`, `typescript`. And we have almost the same component structure in our app. I'm not quite sure whose bug this is. `react-hook-form`s or `react-aria`s.

**Comment by bluebill1049** [comment]
Thanks a lot for the detailed issue report.

**Comment by bluebill1049** [comment]
I would trust the name `button`, and replace it avoided this problem. Not try to push around the root cause with which lib, I will investigate a bit more for the root cause.
