### ISSUE TITLE
[v7] getValues is null when disabled={true}

### ISSUE THREAD

**Issue by ivanhoe-dev** [react-hook-form/react-hook-form#4485]
**Describe the bug**
When using "getValues()" in "validate", and set "isSubmitting" as disabled. The getValues will return strange values.

**To Reproduce**
Enter something in all input > click submit > check the console

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-js-forked-7t0c8?file=/src/App.js

**Expected behavior**
getValues() should return current input no matter disabled or other status. Actually v6 is working in the same situation.

**Comment by bluebill1049** [comment]
Discussion: https://github.com/react-hook-form/react-hook-form/discussions/4413

https://codesandbox.io/s/react-hook-form-js-forked-s4zcd?file=/src/App.js:836-848

disabled input will consistently return `undefined` from v7 onwards, we already had quite a lot discussions on this topic. If you want to disable the user from update the input, you have two options:

- `readOnly`
- use `<fieldset />` to disable the whole input group.

**Comment by bluebill1049** [comment]
more reference on the incoming V7 doc: 

<img width="943" alt="Screen Shot 2021-03-22 at 8 57 28 pm" src="https://user-images.githubusercontent.com/10513364/111972133-39025c80-8b51-11eb-9566-84f737f4f0f9.png">
<img width="990" alt="Screen Shot 2021-03-22 at 8 57 57 pm" src="https://user-images.githubusercontent.com/10513364/111972178-4881a580-8b51-11eb-94bd-7f09ffaa44fc.png">

**Comment by ivanhoe-dev** [comment]
Thanks! Now I know how to get it work

**Comment by bluebill1049** [comment]
Thanks for understanding @ivanhoe-dev we should release v7 doc soon, and the updated doc will help more developers to get a clear understanding of this.
