### ISSUE TITLE
React Native Can't find variable MutationObserver

### ISSUE THREAD

**Issue by khalidahmada** [react-hook-form/react-hook-form#4488]
I have an error Can't find variable: MutationObserver

**To Reproduce**

`const { errors, handleSubmit, control } = useForm();`

**Screenshots**
![error-react-hook-form](https://user-images.githubusercontent.com/2378611/112028921-fb91d500-8b38-11eb-8dfa-957274b5fdde.jpg)

- OS: [ios, Android]

**Comment by bluebill1049** [comment]
which version and how to reproduce.

**Comment by khalidahmada** [comment]
@bluebill1049  thanks for your reply. 

The version of react-hook-form is **6.14.1**. Please note my app is on react-native. to produce this issue whenever I  call the hook useForm() here is the implementation:

Here is the implementation : 

`import React from 'react';
import {View } from 'react-native';
import { useForm, Controller } from "react-hook-form";
import { InputText } from "./InputText";
export const LoginForm = ()=> {
    const { errors, handleSubmit, control } = useForm();
    
     const rules = {
       required: true,
       pattern: {
         value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
         message: "Bad format email",
       },
     };

    return (
      <View>
        <Controller
          control={control}
          name="email"
          rules={rules}
          defaultValue=""
          render={({ onChange, value, onBlur }) => {
            return (
              <InputText
                label={"Email"}
                onChangeText={onChange}
                value={value}
                onBlur={onBlur}
              />
            );
          }}
        />
      </View>
    );
}`

**Comment by bluebill1049** [comment]
Unless that package injects `window` object, if this still causes an issue, I would recommend migrating to v7, as the `mutationObserver` has been completely removed.

**Comment by khalidahmada** [comment]
@bluebill1049 witch package events or react-hook-form ? Thank you

**Comment by bluebill1049** [comment]
react-hook-form@7.0.0-rc.6

**Comment by khalidahmada** [comment]
@bluebill1049  Thank you !!!! it works, Do you think it's stable?

**Comment by bluebill1049** [comment]
yes it's stable and it's in RC. release next month if nothing goes completely wrong.
