### ISSUE TITLE
Material UI Select initial value not picked up by form

### ISSUE THREAD

**Issue by stocksp** [react-hook-form/react-hook-form#449]
**Describe the bug**
The initial value of the Material UI Select does not appear in the form submit callback.  It does appear if the control is used (onChange called).
**To Reproduce**
1.  https://codesandbox.io/s/react-hook-form-custom-input-urrjm
2. Click the submit button after the form loads before clicking the Select control.  Notice no 'filters' in the alert
3. Change the value in the Select from 'Chocolate' click submit again and you will see the the 'filters' now appear in the alert data

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-custom-input-urrjm

**Expected behavior**
I expect to see ALL the form data when submit is clicked.  Select controls that have not been used (onChange called) don't have their values available on submit.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MAC current version
 - Browser Chrome latest version

Thanks a million for your marvelous package!!!

**Comment by bluebill1049** [comment]
hey @stocksp , thanks to the lovely encouragement!

The problem is material UI is not really good at support uncontrolled component, so to solve this solve, you could set up `defaultValue` in the `useForm`

https://react-hook-form.com/api#useForm

**Comment by stocksp** [comment]
Works like a charm!  Thanks again for all your work.  I think I'm finally divorced from Formik!

**Comment by bluebill1049** [comment]
thank you for your encouragement and support. I still hope one-day material UI will start supporting uncontrolled components.

**Comment by agoiabel** [comment]
@bluebill1049 @stocksp.

Please how do you get this to work, I used the default value like below:

```
  const { register, handleSubmit, setValue } = useForm({
    defaultValues: {
      firstName: "bill",
      filters: options[0]
    }
  });
``` 

but still shows the error

**Comment by bluebill1049** [comment]
@agoiabel have you taken a look at Controller: https://react-hook-form.com/api#Controller

**Comment by agoiabel** [comment]
@bluebill1049 Yes thanks.
