### ISSUE TITLE
V7 Bug - set value with field array throws exception if object is read only

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4490]
**Describe the bug**
At first, I thought this might just be a design feature, but being as this works in V6 and it works with non-field array values, I'm going to say this is a bug. The issue is:

**if** 

1. we use `setValue` to change a field array
2. the new array we pass in is read-only

**then** the library will throw an error and crash our application

The reason this would come up is primarily when using libraries like immer. Many times I will use immer throughout my app to modify different objects. If I then try to use one of these objects to initialize my form, I will get this crash. The only workaround would be to use the `setAutoFreeze` method to false every time I use immer which is kinda a pain and defeats some of the benefits of using it (creating immutable objects).

https://immerjs.github.io/immer/freezing

**To Reproduce**

1. Go to the sandbox
2. Click on change value
3. notice the crash

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-l6l9l?file=/src/index.js

**Expected behavior**
I think the library should be able to work when objects are frozen. A simple check could be added to see if an object is frozen, and then the object could be cloned if so.

**Screenshots**
![Screenshot from 2021-03-22 12-29-27](https://user-images.githubusercontent.com/36898266/112047251-49dbaf80-8b0a-11eb-8979-e8952a63b4e0.png)

**Comment by bluebill1049** [comment]
Thanks, @wdfinch, I don't think we will add that extra check.

**Comment by wdfinch** [comment]
:( ok. Just out of curiosity how come? Seems like a really simple check that would make working with the library safer and easier.

**Comment by wdfinch** [comment]
@bluebill1049 I realize that fully unfreezing an object isn't super trivial. I wrote a custom helpful function to do this. If you change your mind, I can make a pr and you can have my helper.
