### ISSUE TITLE
[v7] Checkbox value is not updated in onChange mode

### ISSUE THREAD

**Issue by ivanhoe-dev** [react-hook-form/react-hook-form#4492]
**Describe the bug**
When using "onChange" mode on a checkbox, the "data" value is not aligned with the native "checked" value

**Codesandbox link (Required)**
```import * as React from "react";
import { useForm } from "react-hook-form";

export default function App() {
  const { register, handleSubmit } = useForm({
    mode: "onChange"
  });
  const onSubmit = (data, e) => console.log(data);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input
        type="checkbox"
        {...register("test")}
        onChange={(e) => {
          console.log(e.target.checked);
          handleSubmit(onSubmit)(e);
        }}
      />
    </form>
  );
}
```

**Expected behavior**
The handleSubmit should return same value as native "checked" vlaue

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by ivanhoe-dev** [comment]
@bluebill1049 Below are more detail, thank you:

**Describe the bug**
[v7] When using "onChange" mode on a checkbox, the "data" value is not aligned with the native "checked" value

**To Reproduce**
Steps to reproduce the behavior:
1. Use "onChange" mode
2. Submit form when onChange a checkbox
3. The callback is not getting correct checked value. It gets the value before "clicked the checkbox" instead

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-js-forked-f39sc?file=/src/App.js

**Expected behavior**
The handleSubmit should return same value as native "checked" vlaue

**Comment by bluebill1049** [comment]
you need to call the onChange from the `register`. 

`const { onChange, ...rest } = useForm()`

**Comment by kkeattlai** [comment]
I think calling `register` **includes** onChange props. If you would want to simulate the behaviour of onChange in submit, it would be calling **useWatch** to see if the value changes. If it does, then handleSubmit.

```
const value = useWatch({ name: props.name, control });

useEffect(() => {
    handleSubmit(onSubmit)
}, [ value ]);
```

**Comment by bluebill1049** [comment]
```
import * as React from "react";
import { useForm } from "./src";

export default function App() {
  const { register, handleSubmit, setValue } = useForm({
    mode: "onChange"
  });
  const onSubmit = (data, e) => console.log(data);
  register("test")

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input
        type="checkbox"
        onChange={(e) => {
          setValue('test', e.target.checked);
          handleSubmit(onSubmit)();
        }}
      />
    </form>
  );
}
``` 

or just the above.

**Comment by ivanhoe-dev** [comment]
> ```tsx
> import * as React from "react";
> import { useForm } from "./src";
> 
> export default function App() {
>   const { register, handleSubmit, setValue } = useForm({
>     mode: "onChange"
>   });
>   const onSubmit = (data, e) => console.log(data);
>   register("test")
> 
>   return (
>     <form onSubmit={handleSubmit(onSubmit)}>
>       <input
>         type="checkbox"
>         onChange={(e) => {
>           setValue('test', e.target.checked);
>           handleSubmit(onSubmit)();
>         }}
>       />
>     </form>
>   );
> }
> ```
> 
> or just the above.

I finally use this solution, thanks bluebill!

**Comment by ivanhoe-dev** [comment]
@bluebill1049 @kkeattlai I just found that the above two solutions are having some other issues:

kkeattlai's solution will submit form several times because the useEffect will be triggered when "value" and "handleSubmit" are initalized

bluebill's solution is working well in submission, but it is failed to implement default value.

I finally combined both solutions and come up a better solution, hope it helps the others:

```
import * as React from "react";
import { useForm } from "./src";

export default function App() {
  const { register, handleSubmit, setValue } = useForm({
    mode: "onChange"
  });

 const checkboxChangeHandler = async (e) => {
    setEditingField('test');
    setValue('showProfile', e.target.checked);
    handleSubmit(onSubmit)();
  }

  const onSubmit = (data, e) => console.log(data);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input
        type="checkbox"
        {...register('test')} 
        onChange={checkboxChangeHandler}
      />
    </form>
  );
}
```

**Comment by bluebill1049** [comment]
Thanks a lot for sharing solutions.
