### ISSUE TITLE
V7 setValue is not working from rc.3 and upwards where rc.0/rc.1/rc.2 works 

### ISSUE THREAD

**Issue by kkeattlai** [react-hook-form/react-hook-form#4496]
**Describe the bug**
When using rc.3 and upwards, using setValue will set the value but revert to default value.

Kindly below is the code to replicate the bug where both of them is using the same code but different versions.

**Sandbox rc.2**
https://codesandbox.io/s/react-hook-form-array-fields-forked-ooyiw?file=/src/index.js

**Sandbox rc.3**
https://codesandbox.io/s/react-hook-form-array-fields-forked-7qqy0

Thank you !

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/4486 will release another RC tonight for the fix.

**Comment by bluebill1049** [comment]
can you share the step to reproduce as well? in case, it's a different one.

**Comment by kkeattlai** [comment]
Thanks ! I thought it was a different issue from #4486. This is my first time creating an issue so I am not sure if providing the link to the sandbox is sufficient.

When open the link the the sandbox for rc.2, there would be 3 buttons there.
- Press append
- Then, press add
- Finally, press clear.

Similarly, when opening the link the the sandbox for rc.3, there would be 3 buttons there.
- Press append
- Then, press add **It blinks and seems to trying to set the value but it failed.**
- Finally, press clear. **When i tried to key in some value, clearing them would have similar blinking effect**

Thank you once again for the prompt reply.

**Comment by bluebill1049** [comment]
Thanks @kkeattlai will try to get a fix for this tonight.

**Comment by kkeattlai** [comment]
@bluebill1049 Cool. Thank you !! Keep up with the good work !!
