### ISSUE TITLE
getValues() returns an empty object after reset

### ISSUE THREAD

**Issue by MarianKmotorka** [react-hook-form/react-hook-form#4497]
**Describe the bug**
Same issue as in [here](https://github.com/react-hook-form/react-hook-form/issues/2320) - reopen

the issue described in linked issue seems to be only fixed on 6.1.2. Any other version is broken, even the latest (6.15.5)

**To Reproduce**
[sandbox](https://codesandbox.io/s/react-hook-form-useform-template-forked-ivgv6?file=/src/index.js)

**Comment by bluebill1049** [comment]
@MarianKmotorka getValues is always going to be one render behind, it was fixed and probably broken something else hence the "re-fix", however, this is no longer the case in V7.

**Comment by Dartv** [comment]
I have the same problem. This issue shouldn't be closed because this is most definitely a bug.

**Comment by bluebill1049** [comment]
No, this is not a bug @Dartv. it's by design, inputs have updated after render not before. This issue is getting resolved at V7.
