### ISSUE TITLE
update online docs for register validate prop to show that message strings can be returned

### ISSUE THREAD

**Issue by MagicDuck** [react-hook-form/react-hook-form#4498]
The online documentation at https://react-hook-form.com/api/#register does not show how you can return custom error message strings from a function within the `validate` property, which btw it's amazingly flexible. It was just a bit hard to figure out how to have error messages with it until I looked at https://github.com/react-hook-form/react-hook-form/blob/8c198d88cb46e55a7ef709767726e6e8c56a3eab/src/types/validator.ts
Sample Example for docs:
```js
<input
  name="test1"
  ref={
    register({
      validate: {
        uniqueName: value => isUniqueName(value) ? true : "Only use unique names!",
      }
    })
  }
/>
```

**Comment by MagicDuck** [comment]
also, am not sure the docs mention this pattern related to messages:
```
              rules={{
                maxLength: {
                  value: 2000,
                  message: "This value is too long!"
                },
              }
```

**Comment by bluebill1049** [comment]
<img width="954" alt="Screen Shot 2021-03-24 at 9 09 10 am" src="https://user-images.githubusercontent.com/10513364/112225253-9a751900-8c80-11eb-91bf-ea896a7cdbf7.png">

it's in there, there is an option you can switch to see the updated code.

**Comment by MagicDuck** [comment]
ah doh, thanks for pointing out. It's pretty low priority, but one thing that could be considered is not using that radio button UI in the docs as it makes it hard to search. Maybe just my preference...
