### ISSUE TITLE
[React-Native] Peer dependency warning

### ISSUE THREAD

**Issue by ahce** [react-hook-form/react-hook-form#450]
**Describe the bug**
```
npm WARN react-hook-form@3.26.4 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
```

**To Reproduce**
1. npm install react-hook-form
2. Check the warn

**Expected behavior**
No peer warn

**Environment**

| Tech                | Version |
|---------------------|---------|
| react-native       | 0.61.3 |
| react               | 16.9.0 |
| react-hook-form | 3.26.4 |

**Comment by bluebill1049** [comment]
thanks, @ahce I will remove the peer dependency for `react-dom`

**Comment by bluebill1049** [comment]
next patch will have this updated :) which is tonight
