### ISSUE TITLE
Feature Request - better support for frozen objects

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4500]
**Is your feature request related to a problem? Please describe.**
Yes. Nowadays it's very common to use libraries like `immer` that freeze objects in order to enforce they stay immutable. We can also freeze objects ourselves without a library. This is extremely useful as it helps us write safer and easier to understand code.

Unfortunately, it seems that react-hook-form breaks when we provide it an object that is frozen for example via `setValue`. This means that we cannot use frozen objects and the library together. I have tried to unfreeze objects, clone objects, etc, but it seems that no matter what I do, I'm still getting errors from the library. The only solution I've found is to disabled to object freeze feature for large chunks of my code that use react-hook-form and in turn deal with more bugs that stem from not having immutable objects.

**Describe the solution you'd like**
I would like react-hook-form to work if we provide it a read-only/frozen object via `setValue`, `reset`, or other methods.

**Describe alternatives you've considered**
Turning off the auto freeze feature on `immer` or not freezing objects and therefore exposing myself to more bugs.  

**Additional context**
I believe this move would be a good move for `react-hook-form` as it might make the library safer as well. In other words not modify our objects we pass and instead create new ones.

**Comment by wdfinch** [comment]
Just to add an example for this, I had a situation where I passed in an object to `setValue` that was obtained by using `store.getState`. Because I forgot to clone the object and `store.getState` passes a reference (it assumes you will not be mutating it), I had a bug where react-hook-form was changing the values in my redux store. This took a long time to debug before.

The only downside I can see to deep cloning the object is performance. However, this would only occur when we are going to have a render anyway (setValue, reset, etc.) which is a much greater performance hit. I think the additional safety we get from not having to worry about the original object being mutated outweighs the performance hit for operations that aren't run very often (this shouldn't affect watch, getState, etc.)

**Comment by danielo515** [comment]
Why was this closed without any comment? We also want this check to be included as we use Apollo, which freezes values recursively by default.

**Comment by wdfinch** [comment]
It would be nice but the solution would involve making a deep clone of the form values being passed in which would degrade performance.

**Comment by wdfinch** [comment]
Just make a deep clone of the object before you pass it into the form state.

**Comment by bluebill1049** [comment]
we are already doing clone with `defaultValues`, https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/createFormControl.ts#L117  we will provide a utility export so you can clone your frozen objects.  https://github.com/react-hook-form/react-hook-form/issues/7279

**Comment by wdfinch** [comment]
Sounds good. Ya I've just been using the lodash clone deep method.

**Comment by danielo515** [comment]
> we are already doing clone with `defaultValues`, https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/createFormControl.ts#L117 we will provide a utility export so you can clone your frozen objects. #7279

Is a deep clone for default values? I saw frozen objects in there if I recall correctly
