### ISSUE TITLE
`isValidating` is documented, but not included in the `FormState` type

### ISSUE THREAD

**Issue by dancrumb** [react-hook-form/react-hook-form#4519]
**Describe the bug**
`isValidating` is documented, but not included in the `FormState` type.

**To Reproduce**
Just try to use `isValidating` in any Typescript code and you'll get an error

**Codesandbox link (Required)**
Not really relevant, since this is a documentation

**Expected behavior**
The documentation should not list `isValidating` as a form state property

**Comment by bluebill1049** [comment]
Which version?

**Comment by dancrumb** [comment]
My bad, I'm on 6.13.1

I'll update to the latest and see if it works.
