### ISSUE TITLE
How to make <OutlinedInput /> work properly?

### ISSUE THREAD

**Issue by Z-wave** [react-hook-form/react-hook-form#452]
Click the Set button to set the value, which will overlap with the label. It seems that the new value change has not been detected by input.

**Codesandbox link**
https://codesandbox.io/s/material-demo-ruuq0

**Comment by bluebill1049** [comment]
hey @Z-wave thanks for the codesandbox :) I think this is an issue with material UI, you want to post it there?

**Comment by bluebill1049** [comment]
alternative you can use custom register, which still required to use `useState` and update value with `setValue`

**Comment by bluebill1049** [comment]
This is an issue with material UI :(

**Comment by Z-wave** [comment]
@bluebill1049 Thank you for your answer ! How to use `register()` with `useState`?

**Comment by bluebill1049** [comment]
hey @Z-wave have a look this example:
https://codesandbox.io/s/72j69vnk1x

pay attention to:

```
 useEffect(() => {
    register({ name: "reactSelect" });
    register({ name: "antDInput" });
  }, [ register ]);
```
