### ISSUE TITLE
`useDerivedFormValue` as a hook

### ISSUE THREAD

**Issue by ez-alexfrazer** [react-hook-form/react-hook-form#4520]
**Is your feature request related to a problem? Please describe.**

Here is some context:
https://codesandbox.io/s/dazzling-feynman-c80kl?file=/src/App.tsx

**The situation**: I have a form with an array field. I also have a field that is dependent on the state of that array to render or disable itself

**The problem**: I must use `useWatch` to observe the _entire_ state of that field array. This will cause some performance problems because it will recalculate every time an item is added, removed, or changed in any way. This form is simplified, but there is a problem here for sure.

You'll see, for example, that if you type in any of the fields listed, it will trigger a great deal of re-rendering.

**Describe the solution you'd like**
I would propose a new API, something like `useDerivedFormValue`. I would imagine it would look something like this:

```ts
function ShipInBulkCheckbox() {
  const { register, control } = useFormContext();
  const hasMoreThanOneBook = useDerivedFormValue(control, values => values?.books?.length > 1);
  return (
    <Checkbox
      name="sendInBulk"
      ref={register}
      flexGrow={1}
      disabled={!hasMoreThanOneBook}
    />
  );
}
```

**Describe alternatives you've considered**
I can think of a few ways to cache it and derive it, but none quite so ergonomic as something like this

**Additional context**

**Comment by bluebill1049** [comment]
Have u considers to watch the individual input?
