### ISSUE TITLE
[resolver] The error doesn't set correctly when there is a nested object in yup schema

### ISSUE THREAD

**Issue by andykao1213** [react-hook-form/react-hook-form#4523]
**Describe the bug**
As title, I am using the `yupResolver` with `useForm` for validation. I got a nested object schema. The validation works correctly when submitting. After the submit, I expected  `formState.errors` will change after change actions (e.g. click on a checkbox), but the error in the nested object doesn't been set to `formState.errors`.

**To Reproduce**

1. First, check the checkbox `checkbox.a`
2. Click on submit, there shouldn't be any error in the console
3. uncheck the `checkbox.a`
4. No error in console.

**Codesandbox link (Required)**
https://codesandbox.io/s/yup-error-ydjj6?file=/src/App.js

**Expected behavior**
The error object should contain the error of `checkbox`

**Desktop (please complete the following information):**

- OS: macOS Big Sur 11.0.1
- Browser chrome  89.0.4389.90 
- Version 6.15.5

**Additional context**
I've been testing with yup.schema independently and I found that the issue is not in yup, so I report the issue here.

Finally, thank you for the hard work. React-hook-form is an amazing library!

**Comment by bluebill1049** [comment]
here is a quick example for build in validation: https://codesandbox.io/s/checkbox-min-checked-5vocd because hook form validate focus validation on single input, you will need to use trigger to notify the other dependent fields.

**Comment by andykao1213** [comment]
Hi @bluebill1049 ,
Thank you for the fast response!
However, I cannot really understand your words "because hook form validates focus validation on a single input". As this [CSB](https://codesandbox.io/s/yup-error-test-validation-triggered-cen4b?file=/src/App.js) presents, the field `checkbox` in yupSchema has been triggered. It would be awesome if you could answer the question. Thank you!

**Comment by andykao1213** [comment]
After researching the source code, I found the answer. I post my research here for whom may also encounter the same question.

The main logic in inside the function [executeSchemaOrResolverValidation](https://github.com/react-hook-form/react-hook-form/blob/6e56954af872f1f2477fb60064a4eba9b10cbdad/src/useForm.ts#L360):
```js
const { errors } = await resolverRef.current!(
// ...
);
// ...

if (Array.isArray(names)) {
  const isInputsValid = names
    .map((name) => {
      const error = get(errors, name);
  
      error
        ? set(formStateRef.current.errors, name, error)
        : unset(formStateRef.current.errors, name);
  
      return !error;
    })
    // ....
```
Because RHF will call `trigger` with the name of a single input (e.g. `trigger(['checkbox.a']`)), although the schema will be triggered and validate whole fields, RHF will only set the errors which are mentioned in `trigger`. Thats why the `yupSchema` has been triggered but no related errors in `formState.errors`.

So if this is correct, I would like to know why this function design like this? Since the resolver has been validate through all fields, wouldn't it be easier to just return the `errors` from `resolver` ?

**Comment by bluebill1049** [comment]
@andykao1213 it was due to consistency as we are supporting more than just one resolver.
