### ISSUE TITLE
disabled input returns data to handleSubmit

### ISSUE THREAD

**Issue by ivnmood** [react-hook-form/react-hook-form#4525]
**Describe the bug**
I use a Controller with a material ui TextField, which is disabled, but the handleSubmit receives data from this instance, although it should not
I have the same problem as here #2655 

**Codesandbox link (Required)**
https://codesandbox.io/s/interesting-flower-eljie?file=/src/App.js

**Expected behavior**
data from disabled TextInput must not get into handleSubmit

**Desktop (please complete the following information):**

- OS: macOS
- Browser chrome
- Version [Version 89.0.4389.90 (Official Build) (x86_64)

**Comment by bluebill1049** [comment]
We don’t support disabled for controller, only native input. Controller host it’s own value from internal state. There is a feature request u can consider to up vote in the project board.
