### ISSUE TITLE
Use HTML's tabindex for focus order

### ISSUE THREAD

**Issue by Falci** [react-hook-form/react-hook-form#4526]
**Is your feature request related to a problem? Please describe.**
The problem is related to the focus order: for a form like this:

```
<input name="a" ref={register} />
<Controller name="b" render={p => <input {...p} />} />
<input name="c" ref={register} />
```

The focus order will be `a`, `c`, `b`. Which is pretty annoying.

**Describe the solution you'd like**
HTML's way to solve field ordering is the [tabindex](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) attribute. Maybe react-hook-form could use this attribute to decide which field focus next.

**Describe alternatives you've considered**
1. Pass it direct to register: `register({index: 1})`
2. Don't use `<Controller/>`
3. Only use `<Controller/>`

**Additional context**
I don't think it's necessary.

**Comment by bluebill1049** [comment]
solving this problem in v7.
