### ISSUE TITLE
Watch fields are undefined on async initialization using reset

### ISSUE THREAD

**Issue by gumpenaajayvarma** [react-hook-form/react-hook-form#4527]
**Describe the bug**
Hi,

I have a use case where I should allow user to specify a value when none of the options are applicable. A field with two radio buttons, Second radio button is named 'Other'. When other is chosen the user should be able to enter the value in Text field.

**To Reproduce**

1. Create a radio group with other option
2. On selecting other option allow user to enter a value in text field
3. The field names are "fieldname.standard" and "fieldname.custom"
4. Initialize these fields from async api using reset.
5. watch the fields in order to set other values.
6. Once the reset happens the watchfields turn into undefined.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-v6-controller-ts-forked-s4x1z?file=/src/index.tsx

**Expected behavior**
The watchFields should not be undefined when initializing fields using reset, if it is expected kindly share the correct way to watch fields that are nested on async initialization using reset.

**Screenshots**
Code Sanbox mentioned above will give the error after 2 seconds of loading.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 81.0

**Additional context**
I need to initialize the field values from an api to view the saved changes. So I am using reset API to initialize. Then The watch fields are turned into undefined which is causing problem.

**Comment by bluebill1049** [comment]
<img width="1047" alt="Screen Shot 2021-03-26 at 8 35 50 pm" src="https://user-images.githubusercontent.com/10513364/112612292-dbcd1a80-8e72-11eb-9ce3-62cf715575c4.png">

**Comment by jctaveras** [comment]
I noticed that you named the `Controller` as `RadioGroup.standard` and then trying to access this property in the `useEffect` this will cause an error since the `standard` property doesn't exist.

Instead of doing this
```JS
React.useEffect(() => {
    console.log("To Set a value of some field");
  }, [watchFields.RadioGroup.standard]);
```
You will have to do this

```JS
React.useEffect(() => {
    console.log("To Set a value of some field");
  }, [watchFields["RadioGroup.standard"]]); // use bracket notation to access the RadioGroup.standard property
```

**Comment by gumpenaajayvarma** [comment]
Thank you for clarifying
