### ISSUE TITLE
A watched field array does not contain id

### ISSUE THREAD

**Issue by andrewoverwatch** [react-hook-form/react-hook-form#4530]
**Describe the bug**
When accessing a `field` from `useFieldArray`, the field contains a unique`id`.  However the result from `useWatch()` when watching a field array, the field object do not contain the id.  The id is useful for the likes of the keys in a `Array.prototype.map`, in my case the id's are used for defining the id on drag and drop items

The example I had attached just shows my point, it doesn't include drag and drop etc. it just adds a date to a form and appends more dates to an array of dates.

**To Reproduce**

```
const { fields, append } = useFieldArray({
    control,
    name: "formItems"
  });

  const fieldsWatched = useWatch({
    control,
    name: "formItems"
  });
 
 append({...})

 console.log(fields)
 console.log(fieldsWatched)
```

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-v6-form-context-forked-9u35b?file=/src/index.js

- [useForm](https://codesandbox.io/s/react-hook-form-useform-template-lsm61) Template
- [useFieldArray](https://codesandbox.io/s/react-hook-form-usefieldarray-template-q0jek) Template
- [Controller](https://codesandbox.io/s/react-hook-form-controller-template-yu0z5) Template

**Expected behavior**
The id should be returned?

**Screenshots**
<img width="528" alt="Screenshot 2021-03-26 at 13 44 30" src="https://user-images.githubusercontent.com/79635226/112640661-714bb880-8e39-11eb-9218-b48e02e24992.png">

**Desktop (please complete the following information):**

- OS: [e.g. iOS] iOS
- Browser [e.g. chrome, safari] chrome

**Comment by andrewoverwatch** [comment]
How I even got to this solution, is that in a deeply nested child, I am using `useFormContext` to append to a list within the form, and I noticed that it did not rerender the parent with a new value for `fields`, so I looked into _watching_ fields instead, and acting on it instead, however the ids were missing

**Comment by bluebill1049** [comment]
the unique array is only made for rendering the inputs (key), if you need unique id for your input please generate your own.
