### ISSUE TITLE
Typescript problem with registering a (non static) field name in V7

### ISSUE THREAD

**Issue by medihack** [react-hook-form/react-hook-form#4531]
In a [Blitz.js](https://blitzjs.com/) I chose `react-hook-form` as the form library (it has some setup tool to let one choose). But after upgrading to `react-hook-form` V7 RC7 (and adapting some files) I get the following error when running `tsc`:

```
app/core/components/LabeledTextField.tsx:28:66 - error TS2345: Argument of type 'string' is not assignable to parameter of type '`${string}` | `${string}.${string}` | `${string}.${number}`'.

28           <input disabled={isSubmitting} {...props} {...register(props.name)} />
```

If I just do `register("foo")` typescript does not complain. I am pretty sure this wasn't the case with an earlier release candidate (RC3 or so).

Here is a repository that demonstrates the problem: https://github.com/medihack/react-hook-form-v7
To show the problem simply do `yarn; yarn run tsc`.

**Comment by bluebill1049** [comment]
`string` type is not going to satisfied with type check against the `name`, you will need to extend `Path<FormValue>`

**Comment by medihack** [comment]
Ok, then the error message is a bit hard to grasp (but I am a Typescript newbie). I also can't find anything about `Path` in the [V7 TS documentation](https://react-hook-form-website-git-v7-bluebill1049.vercel.app/ts). Is there some little example of how to type it correctly?

**Comment by bluebill1049** [comment]
have a look at this example: https://codesandbox.io/s/react-hook-form-adapting-existing-form-ts-uzfxm?file=/src/index.tsx
