### ISSUE TITLE
V7 Typescript Issue - useWatch returns never type

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4532]
**Describe the bug**
If we:

1. use `useWatch`
2. provide our form values type as a generic
3. provide name as a path in our form values

then the type of the output should be the same type of that path in our form values type. So for example the type of the variable `name` produced from `useWatch` should be `string`.

```
interface FormValues {
  name: string
}

const name = useWatch<FormValues>({
  control,
  name: 'name',
  defaultValue: ''
});
```

However, in my form, I am getting `never` for the type of the output. I am using enums for the names of my input fields, but unlike my `useFieldArray`  issue #4499, there is not the option for a second generic argument to `useWatch` of an enum

**To Reproduce**

1. Go to the sandbox
2. Observer that the type produced from useWatch is `never` when it should be `string`

**Codesandbox link (Required)**
https://codesandbox.io/s/hungry-glade-qk13t?file=/src/App.tsx

**Expected behavior**
I expect the type of output from `useWatch` to be the same type field we want to watch provided we pass in our form values type as a generic.

**Screenshots**
![Screenshot from 2021-03-26 17-34-02](https://user-images.githubusercontent.com/36898266/112705241-162abd80-8e5b-11eb-8cfb-2c0265c6378e.png)

**Comment by bluebill1049** [comment]
remove that generic, it should work.

**Comment by wdfinch** [comment]
You're right. I guess it's kinda confusing because `useWatch` take a form values type. So as a user I would expect to pass one in to give it the information it needs. Maybe a note on the docs could explain this or ideally it could work even when we pass in the generic.

**Comment by wdfinch** [comment]
@bluebill1049 do you have any advice on how to handle this when we are using `useWatch` with `FormProvider`? It seems that when I try the approach above, I get an `any` type for my `useWatch` return value. Additionally, if I try to provide more information, I get the `never` type instead. What should I do in this case?

https://codesandbox.io/s/hungry-glade-qk13t?file=/src/App.tsx

![Screenshot from 2021-03-30 16-19-42](https://user-images.githubusercontent.com/36898266/113068737-c3f7de00-9173-11eb-8266-28fc877da019.png)

**Comment by bluebill1049** [comment]
@wdfinch for context API, I think you will have to use the generic at the `useWatch`. cc @kotarella1110
