### ISSUE TITLE
change the touched array more accessible

### ISSUE THREAD

**Issue by ibnumusyaffa** [react-hook-form/react-hook-form#455]
instead of this 
`touched: [
    "first_name:true",
    "first_name:true",
  ],
`
what about something like this
`
touched: {
    first_name:true,
    last_name:true
 }
`
i think its more accessible
`
{errors.firstName && touched.firstName ? (
            <div>{errors.firstName}</div>
 ) : null}
`

**Comment by bluebill1049** [comment]
a good suggestion I will note this down for future improvement. 

or you can do `touched.inclues('first_name:true')`

**Comment by bluebill1049** [comment]
I have added into the todo list, this will be in the next major version consider it's breaking change.
