### ISSUE TITLE
Dirty check not clean after input `defaultValue` set back to original value.

### ISSUE THREAD

**Issue by paslo22** [react-hook-form/react-hook-form#4553]
**Describe the bug**
Dirty check is not being handled correctly when using `defaultValue` on fields.

I found this issue when trying to upgrade from 6.11.3 to latest (6.15.5).
Previously it was working just fine.

**To Reproduce**

1. Create a form with an input text with a `defaultValue`. Like:
```html
<input name="inputName" ref={register} defaultValue="change me" />
```
2. Change it to whatever.
3. Change it back to "change me".

Dirty state stays as `isDirty: true`.

**Codesandbox link (Required)**
https://codesandbox.io/s/runtime-cherry-jbkrf?file=/src/App.js

**Expected behavior**
If the input gets back to its `defaultValue`, the formState should be set back to `isDirty: false`.

**Desktop (please complete the following information):**

- OS: Ubuntu LTS 20.04
- Browser Chrome
- Version: 89.0.4389.90

**Comment by bluebill1049** [comment]
<img width="970" alt="Screen Shot 2021-03-30 at 11 26 11 am" src="https://user-images.githubusercontent.com/10513364/112915745-bc700f00-914a-11eb-86a5-e929b15d1d83.png">

The source of truth for dirty measure only lives in the `defaultValues`.
