### ISSUE TITLE
Feature Request: Option to Keep Values of Unmounted Inputs in FormState (React Native)

### ISSUE THREAD

**Issue by kpervin** [react-hook-form/react-hook-form#4555]
**Is your feature request related to a problem? Please describe.**
When using Modals, [especially the Modal component from React Native Paper](https://github.com/callstack/react-native-paper/blob/aa835497e1f8e362cec0ce470cd3b0136c581894/src/components/Modal.tsx#L194), if the form elements are unmounted, then their values are removed from the formState.

**Describe the solution you'd like**
Please give an option to allow for these values to persist when unmounted, as React Native has a lot of areas in which Dialog components simply return `null` to show that they are not displayed, rather than tweaking the styling.

**Describe alternatives you've considered**
I've considered creating my own Modal components just to get around this issue, but honestly it would be nice to have the option regardless.

**Comment by bluebill1049** [comment]
use `shouldUnregister: false` in v6.

**Comment by kpervin** [comment]
@bluebill1049 Will this also work if the component has never been mounted, such as when a modal is not open on first mount?

**Comment by bluebill1049** [comment]
yes, you can setValue or put inside of defaultValues.

**Comment by baba43** [comment]
> use `shouldUnregister: false` in v6.

What should be used in v7? I checked the notes but did not find any hint regarding this option?

**Comment by bluebill1049** [comment]
> > use `shouldUnregister: false` in v6.
> 
> What should be used in v7? I checked the notes but did not find any hint regarding this option?

v7 will no longer remove unmounted input value.

**Comment by bartosz-szymanski** [comment]
> > > use `shouldUnregister: false` in v6.
> > 
> > 
> > What should be used in v7? I checked the notes but did not find any hint regarding this option?
> 
> v7 will no longer remove unmounted input value.

Are you sure? Version 7.0.4, which does not support `shouldUnregister: false` flag, still removes values when switching between tabs.

**Comment by bluebill1049** [comment]
> > > > use `shouldUnregister: false` in v6.
> > > 
> > > 
> > > What should be used in v7? I checked the notes but did not find any hint regarding this option?
> > 
> > 
> > v7 will no longer remove unmounted input value.
> 
> Are you sure? Version 7.0.4, which does not support `shouldUnregister: false` flag, still removes values when switching between tabs.

yes, unless you unmount the entire `useForm`.

**Comment by bartosz-szymanski** [comment]
> > > > > use `shouldUnregister: false` in v6.
> > > > 
> > > > 
> > > > What should be used in v7? I checked the notes but did not find any hint regarding this option?
> > > 
> > > 
> > > v7 will no longer remove unmounted input value.
> > 
> > 
> > Are you sure? Version 7.0.4, which does not support `shouldUnregister: false` flag, still removes values when switching between tabs.
> 
> yes, unless you unmount the entire `useForm`.

Thanks, I was exactly expecting that. Have a look at the documentation it doesn't directly point out that it is now the default behaviour.
https://react-hook-form.com/faqs/#Howtoworkwithmodalortabforms

**Comment by bluebill1049** [comment]
> > > > > > use `shouldUnregister: false` in v6.
> > > > > 
> > > > > 
> > > > > What should be used in v7? I checked the notes but did not find any hint regarding this option?
> > > > 
> > > > 
> > > > v7 will no longer remove unmounted input value.
> > > 
> > > 
> > > Are you sure? Version 7.0.4, which does not support `shouldUnregister: false` flag, still removes values when switching between tabs.
> > 
> > 
> > yes, unless you unmount the entire `useForm`.
> 
> Thanks, I was exactly expecting that. Have a look at the documentation it doesn't directly point out that it is now the default behaviour.
> https://react-hook-form.com/faqs/#Howtoworkwithmodalortabforms

want to send a PR to correct that?

**Comment by bartosz-szymanski** [comment]
> > > > > > > use `shouldUnregister: false` in v6.
> > > > > > 
> > > > > > 
> > > > > > What should be used in v7? I checked the notes but did not find any hint regarding this option?
> > > > > 
> > > > > 
> > > > > v7 will no longer remove unmounted input value.
> > > > 
> > > > 
> > > > Are you sure? Version 7.0.4, which does not support `shouldUnregister: false` flag, still removes values when switching between tabs.
> > > 
> > > 
> > > yes, unless you unmount the entire `useForm`.
> > 
> > 
> > Thanks, I was exactly expecting that. Have a look at the documentation it doesn't directly point out that it is now the default behaviour.
> > https://react-hook-form.com/faqs/#Howtoworkwithmodalortabforms
> 
> want to send a PR to correct that?

Sure, just tell me how. I'd mention that in the migration guide from v6 to v7  as well and extend Material UI Sandbox by an example with Checkbox and FormControlLabel, was struggling to figure it out on my own.

**Comment by bluebill1049** [comment]
> > > > > > > > use `shouldUnregister: false` in v6.
> > > > > > > 
> > > > > > > 
> > > > > > > What should be used in v7? I checked the notes but did not find any hint regarding this option?
> > > > > > 
> > > > > > 
> > > > > > v7 will no longer remove unmounted input value.
> > > > > 
> > > > > 
> > > > > Are you sure? Version 7.0.4, which does not support `shouldUnregister: false` flag, still removes values when switching between tabs.
> > > > 
> > > > 
> > > > yes, unless you unmount the entire `useForm`.
> > > 
> > > 
> > > Thanks, I was exactly expecting that. Have a look at the documentation it doesn't directly point out that it is now the default behaviour.
> > > https://react-hook-form.com/faqs/#Howtoworkwithmodalortabforms
> > 
> > 
> > want to send a PR to correct that?
> 
> Sure, just tell me how. I'd mention that in the migration guide from v6 to v7 as well and extend Material UI Sandbox by an example with Checkbox and FormControlLabel, was struggling to figure it out on my own.

Fork the `documentation` repo, send us a PR with some better explanation and information for the change. 👍
