### ISSUE TITLE
Provide onSubmit option for reValidateMode

### ISSUE THREAD

**Issue by khushboo097** [react-hook-form/react-hook-form#4556]
**Is your feature request related to a problem? Please describe.**
we want to keep the validation on form fields only onSubmit, by using the mode: 'onSubmit' i can achieve that but reValidateMode doesn't support onSubmit and gets triggered on every change to the field which is not ideal. There should be an option to configure the revalidateMode onSubmit as well.

**Describe the solution you'd like**
ideally if reValidateMode is set to 'onSubmit' the validate function should be called only when the user submits the form and not be tied to the onChange event.

**Comment by bluebill1049** [comment]
have you tried to set them both to `onSubmit`?
