### ISSUE TITLE
V6 Bug - Controller warns and does not register field if "name" ends with array syntax "example.arr[index]"

### ISSUE THREAD

**Issue by VeriClock-Bryce** [react-hook-form/react-hook-form#4559]
**Describe the bug**

Controller component cannot take as a name an array index directly, example.arr[index], and instead expects a variable name after the square bracket, example.arr[index].name.  This breaks any usage case where a complex component returns an object into an array of objects, or even a simple component populating an array of strings.  Problem introduced in 6.3.1 and persists to 6.15.5 and seems to be caused by an overly restrictive name check within useForm.ts's registerFieldRef

(this is a simplified contrived example)

Simple form with a field that is an array of Person objects; for example, the typescript types would be:
```
type Person = {
  firstName: string,
  lastName: string
}
type FormType = {
   test2: Person[]
}
```

I have a simple controlled component that edits a Person, taking a person object as a value prop, and passing back a person object in an onChange prop callback.  Since this is an array of Person objects, I used the useFieldArray helper, and a controlled component with render props to  create the array of form fields:

```
      {fields2.map((item, index) => {
          return (
            <div key={item.id}>
              <Controller
                name={`test2[${index}]`}
                control={control}
                defaultValue={item} // make sure to set up defaultValue
                render={({ value, onChange }) => (
                  <PersonSubForm value={value} onChange={onChange} />
                )}
              />
            </div>
          );
        })}
```

When doing this in a debug build, it doesn't work - values typed into the form do not make it into the form's actual values output by getValues(), or watch() - and there is a warning in the console:
```
\`name\` prop should be in object shape: name="test[index].name" 
```

Interestingly, a production build will work with no warning in the console, and values showing up in getValues/watch as expected.

**To Reproduce**
This sandbox is setup to demonstrate the issue:
[https://codesandbox.io/s/react-hook-form-usefieldarray-forked-twnj5?file=/src/index.js](url)

Part 1 of the form is from the useFieldArray example sandbox

1. type text into Part 2 of the form (first name or last name)
2. Notice the JSON printed at the bottom of the form does not contain the test2 array of Person objects from the form.
3. Notice the console contains the warning: prop should be in object shape: name="test[index].name"

**Expected behavior**
the test2 array should show up in the output of watch() that is printed at the bottom of the form.

**Desktop:**
- Browser: Latest Chrome

**Additional context**
The problem appears to have been introduced in 6.3.1, as a quick test in the above sandbox shows 6.3.0 works as expected, and 6.3.1 does not.  

The issue is in useForm.ts, in function registerFieldRef() at line ~926:
[https://github.com/react-hook-form/react-hook-
form/blob/6ffca201b7d35d8a43c9e21337a7765ab57c8a5c/src/useForm.ts#L926](url)

in the check of the name value.  It expects it to end with a dot and then one or more characters.  When it fails to see this, it prints the warning and returns, not completing the rest of the function and explaining why it does work in production builds.  

It feels like it might be a mistake to have this specific requirement for a component name as it would prevent the usage pattern of a component returning an object value directly into an array.

**Comment by bluebill1049** [comment]
This is correct behavior:

- we don't support flat array in `useFieldArray`. 
- warning are removed in prod build.

**Comment by VeriClock-Bryce** [comment]
Ah, ok.   Thanks for the speedy response!    

(I was under the impression useFieldArray was really just a helper hook, and thought that since the code that was name checking was in useForm.ts that it was unrelated to useFieldArray itself).

So would it be considered fine, as far as the library is concerned, to implement my own method of field arrays, and use the Controller component with flat arrays myself:

```
    let test2Array = watch('test');
.....
        {test2Array.map((item, index) => {
          return (
            <div key={index}>
              <Controller
                name={`test2[${index}]`}
                control={control}
                defaultValues={item}
                render={({ value, onChange }) => (
                  <PersonSubForm value={value} onChange={onChange} />
                )}
              />
            </div>
```

Or is there something fundamental about not supporting flat arrays in the entire library?  

Bonus question: What was the reasoning behind not supporting flat arrays in the useFieldArray hook?  (and given that it does work when the warning is off in production, is there something somewhere that will break when using it like that?)

Thanks!

**Comment by bluebill1049** [comment]
we have embed unique id for each inputs group for the react `key` prop, so we can't do flat array.

**Comment by VeriClock-Bryce** [comment]
Roger that.

As to my part 1 question - can we use flat arrays ourselves - not with useFieldArray - as I did in the code snippet there.

ie:

```
    let test2Array = watch('test');
.....
        {test2Array.map((item, index) => {
          return (
            <div key={index}>
              <Controller
                name={`test2[${index}]`}
                control={control}
                defaultValues={item}
                render={({ value, onChange }) => (
                  <PersonSubForm value={value} onChange={onChange} />
                )}
              />
            </div>
```
Or is something in the library somewhere going to break?  A quick test in a codesandox seems to suggest it will work:

[https://codesandbox.io/s/react-hook-form-usefieldarray-forked-63r2f?file=/src/index.js](url)

(The defaultValue doesn't seem to work, and I can see there being a performance hit with this implementation using watch like this potentially with sufficient numbers of array fields in the form)

But fundamentally, can the basic use of react-hook-form support flat arrays like this?  

Thanks again!

**Comment by bluebill1049** [comment]
you can, as long as you don't go into the complexity of managing a "real" field array.

**Comment by Mendoza920** [comment]
Yes. This is Yadira Gaytan.
I have been bugged and all information has been
Lost/stolen.
