### ISSUE TITLE
form is not re-rendered when using setValue to update a field that was manually registered

### ISSUE THREAD

**Issue by petercpwong** [react-hook-form/react-hook-form#456]
**Describe the bug**
When registering fields manually, the form does not re-render after calling `setValue`.

**To Reproduce**
```js
const MyForm = () => {
  const { register, unregister, getValues, setValue } = useForm({
    defaultValues: { email: '' }
  });

  useEffect(() => {
    register({ name: 'email' });
    return () => unregister({ name: 'email' });
  }, [register, unregister]);

  /* getValues does not work because setValue does not trigger a re-render */
  const values = getValues();

  const onChange = e => setValue(e.target.name, e.target.value, true);

  return <input type="text" name="email" value={values.email} onChange={onChange} />;
};
```

**Expected behavior**
Explicitly calling `setValue` should trigger a re-render

The usual use-case would be to simply pass `register` into the input's `ref`. However, manually registering fields is still required for components that don't expose a ref prop. The above code snippet is just a contrived example to show that manually registering a field does not work as intended.

**Comment by bluebill1049** [comment]
dame i think i know a better fix, i will merge yours and release another patch right away.

**Comment by bluebill1049** [comment]
actu

**Comment by bluebill1049** [comment]
I am going to update the website with re-render condition. It's on the todo list

**Comment by petercpwong** [comment]
> actually, that's not the correct usage... `setValue` shouldn't trigger re-render unless there is an error for the field (react hook form is more towards uncontrolled component). for the controlled component, you should use `useState` and `setValue`.

Then wouldn't manually registering fields with `register` be pointless then because the most likely scenario would be to use it for controlled components. If you're concerned with preformance, perhaps we should provide an option to trigger a re-render in `setValue` (a 4th argument perhaps?)

The alternative of using `useState` to maintain a shadow copy is redundant when we already have mechanisms for using controlled components via `setValue` and `getValues`.

**Comment by bluebill1049** [comment]
you have a valid point there. what's your usage like? in my head `setValue` is used for below:

```
useEffect(() => {
  register({name: 'test'});
})

<input name="test" onChange={e => setValue('test', e.target.value)} />
```

and the duty of setValue is only for update value, it doesn't reflect the UI, and I didn't need another piece of state.

**Comment by petercpwong** [comment]
The most basic scenario is for interfacing with third party UI components that don't expose the `ref` prop (eg. react-select). As my original post illustrated, `getValues` doesn't reflect the latest form state because `setValue` doesn't trigger a re-render. Maintaining another copy of the form state with `useState` seems really cumbersome and error-prone (ie. having to keep both form states in sync).

**Comment by bluebill1049** [comment]
I agree with extra `useState` is bad and I am not supporting that (i was not fully awake in the morning :), but why `getValues` during render.
```
const MyForm = () => {
  const { register, unregister, getValues, setValue } = useForm({
    defaultValues: { email: '' }
  });

  useEffect(() => {
    register({ name: 'email' });
  }, [register]); // u don't need unregister here which i should document it in the site

  const onChange = e => setValue(e.target.name, e.target.value, true);

  return <BlackboxComponent onChange={onChange} />;
};
```

why not just remove value? let the component render the value itself.

**Comment by petercpwong** [comment]
I suppose that depends on the implementation of the component. Your solution may be suitable for components that support being both controlled and uncontrolled, but what about for components that only support being uncontrolled? I think it might be a good idea to give the user an option to trigger a re-render in `setValue` for those cases.

**Comment by bluebill1049** [comment]
I would like to take a look at such component which only supports controlled/props. as far as I know, HTML inputs are stateful, they don't need to be driven by external state/props and that's what react hook form is great for. I can easily introduce the 4th argument, but I don't feel it's the right thing to do.

**Comment by bluebill1049** [comment]
If anyone else has similar issues or concerns, feel free to leave your example here as well.

**Comment by bluebill1049** [comment]
@stramel @barrymay @JeromeDeLeon feel free to leave your input as well.

**Comment by petercpwong** [comment]
> I would like to take a look at such component which only supports controlled/props

There are actually quite a few components that only support controlled props (whether that's a good design choice is another question).

One notable example:
https://polaris.shopify.com/components/forms/text-field

The above component doesn't expose a `ref` prop and can only be interfaced with `onChange` and setting the `value` prop.

**Comment by bluebill1049** [comment]
@petercpwong thanks for the example... seriously I am shaking my head right now...

**Comment by petercpwong** [comment]
@bluebill1049 In an ideal world, we probably wouldn't need to deal with these third party components :)

**Comment by bluebill1049** [comment]
to be honest, I am even doubting `react-hook-form` is the right lib for those components and it's a pretty bad pattern to `getValues()` on each render.  Honestly, formik or those controlled form lib would be a better fit for it, I am not devaluing react-hook-form here but the right tool for the right job.

**Comment by bluebill1049** [comment]
at the same time, let me think about better* solutions...

**Comment by bluebill1049** [comment]
hey @petercpwong just use `watch()`! i think it should work!

**Comment by bluebill1049** [comment]
use watch() instead of getValues()

**Comment by bluebill1049** [comment]
closing this :)

**Comment by petercpwong** [comment]
> use watch() instead of getValues()

We might want to add a `nest` argument to `watch()`, although not sure what the function signature should look like (3rd argument?)

**Comment by balupton** [comment]
So how do I get this working? `use watch` isn't that clear of instructions

Just ran into this trying to apply https://react-hook-form.com/faqs#Whatifyoudonthaveaccesstoref to my polaris application

**Comment by JeromeDeLeon** [comment]
@balupton , and @petercpwong , have you tried updating your react-hook-form and use `Controller`?

Here's an [example](https://codesandbox.io/embed/autumn-snowflake-hbhth?fontsize=14&hidenavigation=1&theme=dark)

**Comment by JeromeDeLeon** [comment]
@balupton , I think that question needs an update because we now have `Controller` for that.

**Comment by bluebill1049** [comment]
thanks @JeromeDeLeon for answering this :)

**Comment by JeromeDeLeon** [comment]
No worries :)

**Comment by balupton** [comment]
Ok, got it going with watch. I will try with Controller after this batch is committed.

**Comment by JeromeDeLeon** [comment]
You can't go wrong with either of the two because what you're doing is just want `Controller` is doing under the hood.

**Comment by JeromeDeLeon** [comment]
Let us know your thoughts. We can re-open this one if this doesn't solve your issue.

**Comment by rootux** [comment]
I'm facing the same issues where the values return from `const { text, images } = watch();` are not being updated when I call `setValue('text', newVal, false)`

**Comment by JeromeDeLeon** [comment]
I believe there is no reason to use a manual register since we already have `Controller` and soon `useController` that you can use. If you are working with conditional fields, `shouldUnregister` is your friend.

**Comment by JeromeDeLeon** [comment]
Also, if you could provide a codesandbox that would be helpful.

**Comment by nikhilsarvaiye** [comment]
@petercpwong @bluebill1049 i think setValue can take a new parameter or a complete new method which just say rerender like trigger does its own thing.
The reason I am saying as watch has different purpose, it re-renders on each change which is killing(incase of IE11) and even in chrome you see lag,
here is what I am trying to do, so validation works just fine on each change, i just want to re-render on blur event which could work for controlled components just fine.
Have a thought

**Comment by bluebill1049** [comment]
> @petercpwong @bluebill1049 i think setValue can take a new parameter or a complete new method which just say rerender like trigger does its own thing.
> The reason I am saying as watch has different purpose, it re-renders on each change which is killing(incase of IE11) and even in chrome you see lag,
> here is what I am trying to do, so validation works just fine on each change, i just want to re-render on blur event which could work for controlled components just fine.
> Have a thought

can you provide a codesandbox? so you want setValue to re-render or not re-render?

**Comment by nikhilsarvaiye** [comment]
https://codesandbox.io/s/react-hook-form-useform-template-forked-p6xg2?file=/src/index.js

here is the codesandbox, i want to re-render on on-blur event, it does re-renders on submit form action and if I use watch it re-renders on each change.
I was hoping to have some method I can use on blur event.
Re-render == getValues() updates also right?

**Comment by bluebill1049** [comment]
@nikhilsarvaiye 
`getValues()` doesn't trigger re-render
`useWatch || watch` trigger re-render

**Comment by sebastienfi** [comment]
We should be able to use [watch](https://react-hook-form.com/faqs#watchvsgetValuesvsstate) on a specific value `const watchfirstName = watch("firstName", props.firstName);` with a `Controller`.

This should trigger a re-render because that's what's expected with a watch'like function :) 

This allows to bypass a redundant pattern when  `useState` implemented locally triggers re-rendering of form which then can take into account the change of value for whatever side effect.

**Comment by vankadn** [comment]
@bluebill1049 I recently started using react and react-hook-forms, I am using a controlled with a third part input component, when user move between tabs context updates state, but when user comes back to initial tab the data need to be presented, how can I achieve this , didn't want to use `defaultValue` as this is not triggering validations.

**Comment by bluebill1049** [comment]
> @bluebill1049 I recently started using react and react-hook-forms, I am using a controlled with a third part input component, when user move between tabs context updates state, but when user comes back to initial tab the data need to be presented, how can I achieve this , didn't want to use `defaultValue` as this is not triggering validations.

you can set `shouldUnregsiter: false`

**Comment by vankadn** [comment]
@bluebill1049 I tried with `shouldUnregsiter: false` still I don't see validations triggering.

I have also tried below, but this is triggering validations on initial load of empty page
 ```

  useEffect(() => {
    console.log("trigger validation");

    trigger();
  }, [trigger]);
```

**Comment by bluebill1049** [comment]
> @bluebill1049 I tried with `shouldUnregsiter: false` still I don't see validations triggering.
> 
> I have also tried below, but this is triggering validations on initial load of empty page
> 
> ```
> 
>  useEffect(() => {
>    console.log("trigger validation");
> 
>    trigger();
>  }, [trigger]);
> ```
> 
> Thanks for jet speed reply

can you share a simple codesandbox for what you try to achieve? maybe i am missing the context.

**Comment by enheit** [comment]
For anyone who is registering fields manually like `Autocomplete` from Material UI + React Hook Form` you can provide options as a 3rd argument of `setValue` method.

It should work like this

```TypeScript

const { setValue } = useForm()

<Autocomplete
   ...
   onChange={event, option => setValue('fieldName', option.value, { shouldValidate: true }}
   ...
/>
```

**Comment by rattkin** [comment]
We have custom components wrapping html form elements and when I setValue() them, they show the new value, but don't re-render.
Since we have material-style animation of label from placeholder position, depending on the input value, we need the render.
Or, how else should we determine the tooltip position and trigger the animation?
![image](https://user-images.githubusercontent.com/910080/146005961-dd5bfca1-90c9-41a0-b0a5-3182f32d93d5.png)

**Comment by hungnv-zinza** [comment]
fuck that library. why setValue does not trigger form re rendering
HOw to do that

**Comment by bluebill1049** [comment]
> fuck that library. why setValue does not trigger form re rendering HOw to do that

Please read our code of conduct: https://github.com/react-hook-form/react-hook-form/blob/master/CODE_OF_CONDUCT.md One more time of this sort of abusive language, we will block you from this project!
