### ISSUE TITLE
V7 - FieldArray - Multiple checkbox values

### ISSUE THREAD

**Issue by BTiers** [react-hook-form/react-hook-form#4571]
First of, really wanted to thank you all for the great library !
I'm very looking forward for the release of v7.

**Describe the bug**
When appending an item to a fieldArray that has a "multiple checkbox values" default this error is thrown:
```
Cannot read property 'ref' of undefined
``` 

**To Reproduce**

1. On the sandbox, click on the "Append" button

**Codesandbox link (Required)**
[Sandbox reproducing the bug](https://codesandbox.io/s/fieldarray-checkboxes-append-bug-9tyxu?file=/src/App.tsx)

**Expected behavior**
The default value should be added to the field

**react-hook-form version:**
- Version 7.0.0-rc-8

**Additional context**
I believe that the error occurs on [this function]( https://github.com/react-hook-form/react-hook-form/blob/a9ca476588a629a24fae4ba5559e3bbad8e1f62e/src/useFieldArray.ts#L230) when the array is re-send to `registerFieldArray` the `Object.entries` split the string into individuals characters and the input name is evaluated falsely therefore leading the next call to [registerFieldRef](https://github.com/react-hook-form/react-hook-form/blob/a9ca476588a629a24fae4ba5559e3bbad8e1f62e/src/useForm.ts#L837) to fail

**Comment by bluebill1049** [comment]
please use `Controller` or `useController` to build a controlled component for such usage. `field array` needs to have unique names.

**Comment by bluebill1049** [comment]
<img width="928" alt="Screen Shot 2021-03-31 at 8 41 30 pm" src="https://user-images.githubusercontent.com/10513364/113124673-7ce81680-9261-11eb-90c8-29555e3e65b4.png">

**Comment by BTiers** [comment]
Thanks for the quick reply, i'll read the doc more thoroughly next time mb.

**Comment by bluebill1049** [comment]
not your fault at all @BTiers the doc is not published yet (V7).
