### ISSUE TITLE
React select required error appears even when value is selected

### ISSUE THREAD

**Issue by tabughofaupgrade** [react-hook-form/react-hook-form#4575]
**Describe the bug**
I have aReact-select element wrapped within a controller with required rule. It keeps giving a required error even when value is selected.

**To Reproduce**
latest version 6.15.5
in the sandbox click submit after choosing a value from the select element. an error would appear

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-forked-p4ee3?file=/src/index.js:1132-1143

**Expected behavior**
required error should disappear when I choose an element with react select

**Desktop (please complete the following information):**
- Browser: chrome
- version: 89.0.4389.90

**Comment by bluebill1049** [comment]
read the doc on Controller, onChange prop is not assigned.

**Comment by tabughofaupgrade** [comment]
worked when onchange event occur but still triggers it if default value is assigned. I updated the sandbox
