### ISSUE TITLE
V7 - useFieldArray: typed field name check is not working

### ISSUE THREAD

**Issue by knoefel** [react-hook-form/react-hook-form#4578]
**Describe the bug**
Either using the `name` prop from `Controller` or passing the field name as an argument to `register` results in the following type error:

> Type 'string' is not assignable to type '"fields" | "fields.${number}" | "fields.${number}.field1Name" | "fields.${number}.field2Name"'

Assuming that 'fields' is the name of the Field Array and field1Name and field2Name are form fields.

**To Reproduce**

1. Go to [CodeSandBox](https://codesandbox.io/s/usefieldarray-field-name-typing-6xj8o)
2. Check Type Errors for name and register

**Expected behavior**
The passed string to `name` or `register` is inferred correctly.

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS 11.0.1
- Browser: Chrome
- Version: 89

**Comment by bluebill1049** [comment]
`as const` is missing. wait for the new v7 is release there will be more info.
