### ISSUE TITLE
Support default error message for required errors

### ISSUE THREAD

**Issue by babramczyk** [react-hook-form/react-hook-form#458]
**Is your feature request related to a problem? Please describe.**
For simple forms where the required error message is the same (i.e. "This field is required"), it would be nice to default this error message so that you can just use `ref={register({ required: true })` in all of these cases, instead of `ref={register({ required: 'This field is required' })`` or `ref={register({ required: REQUIRED_ERR_MESSAGE })}`

**Describe the solution you'd like**
Some API for defaulting error messages (or at least required error messages). Maybe something like `useForm({ errorMessages: { required: "This field is required }})`? Not sure.

Then a user could override the default wherever necessary.

**Describe alternatives you've considered**
Noted in first section above.

**Comment by bluebill1049** [comment]
good suggestion @babramczyk, for now, I think we will keep what we got. One of the important goals for react hook form is to keep API simple and primitive. I don't want to introduce multiple ways of doing an error message, but if you think it's not friendly enough, I would suggest doing a constant or some kind of utility function.

**Comment by babramczyk** [comment]
No worries.

Can you give me insight on the motivation for a primitive API, vs a configurable one?

**Comment by bluebill1049** [comment]
I think primitive API is more scalable in my own opinion, it allows you to build things on top of it quite easier, while configurable ones it's fixed and likely to introduce breaking changes (at least those r what I learned so far) I could be wrong as well...

**Comment by bluebill1049** [comment]
hope above answers your question for now. feel free to leave more questions too

**Comment by mcabrams** [comment]
Any recommendations on how to effectively achieve the result @babramczyk is seeking - even if the implementation requires a work-around right now?

**Comment by patcon** [comment]
Doable by pre-processing the `rules` object in a simple hook. This included internationalization of that default for us, but even simpler (and maybe no need for a hook) if you don't need that:

```js
/**
 * One-off hook to add default messages to validation rule object.
 *
 * @param rules initial rule object
 * @returns modified rule object
 */
export const useRulesWithDefaultMessages = (rules) => {
  const { formatMessage } = useIntl();
  const rulesWithDefaults = { ...rules };

  if (rules.required === true) {
    rulesWithDefaults.required = formatMessage({
      defaultMessage: "This field is required.",
      description: "The default validation message when a field is required",
    });
  }

  return rulesWithDefaults;
};
```

**Comment by anilanar** [comment]
Example solution (`useIntl` is a our own custom hook that provides translations):

```ts
export const useForm = <
  TFieldValues extends FieldValues = FieldValues,
  TContext extends object = object,
>(
  props?: UseFormProps<TFieldValues, TContext>,
): UseFormReturn<TFieldValues, TContext> => {
  const intl = useIntl();
  const { register: register_, ...rest } = useForm_(props);

  const register: UseFormRegister<TFieldValues> = (name, options) =>
    register_(name, {
      ...options,
      required: options?.required === true ? intl.formatMessage('foobar required') : options?.required,
      minLength:
        typeof options?.minLength === 'number'
          ? intl.formatMessage(`foobar ${options.minLength`)
          : options?.minLength,
      maxLength:
        typeof options?.maxLength === 'number'
          ? intl.formatMessage(`foobar ${options.maxLength`)
          : options?.maxLength,
      min: typeof options?.min === 'number' ? intl.formatMessage(`foobar ${options.min}`) : options?.min,
      max: typeof options?.max === 'number' ? intl.formatMessage(`foobar ${options.max}`) : options?.max,
    });

  return { register, ...rest };
};
```
