### ISSUE TITLE
Validation for number zero

### ISSUE THREAD

**Issue by gpsfl** [react-hook-form/react-hook-form#4583]
When validating the number `0` with `required: true`, it will return a validation error which states the field is empty. I took a look at the source code and this seems to happen because values are checked with `!value`, which in the case auf `0` will cause a type conversion to `true`. Is this a bug?

We already had multiple cases in our app where we mapped an array on a select component (value = index) and it caused problems (because array indexes start at zero). Is there a better way of doing this with react-hook-form?

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by gpsfl** [comment]
@bluebill1049 edited it

**Comment by bluebill1049** [comment]
i think you are after `min`, `max` instead of `required`, for customized usage you can use `validate` function.
