### ISSUE TITLE
V7 - Error `transformToNestObject is not a function` is thrown while submitting with validation errors using yupResolver

### ISSUE THREAD

**Issue by arochadaniel** [react-hook-form/react-hook-form#4586]
**Describe the bug**
App throws `react_hook_form_1.transformToNestObject is not a function` while submitting with validation errors using yupResolver

**To Reproduce**

1. Create form with useForm
2. Set yupResolver with a schema
3. Click submit button

**Codesandbox link (Required)**
- [Sandbox](https://codesandbox.io/s/hook-form-transform-to-nest-object-bug-5n6p3?file=/src/App.tsx)

**Expected behavior**
Error should not be thrown

**Screenshots**
[https://i.imgur.com/2fzZcGJ.png](url)

**Additional context**
I started happening as I updated to latest resolvers `2.0.0-rc.1` from `2.0.0-beta.15`  and react-hook-form `7.0.0-rc.8` from `7.0.0-rc.7`, before that it didn't happen. I tried rolling back to previous versions but it kept happening. Already tried deleting my node-modules and package-lock.json and reinstalling and is the same. 

Thanks!

**Comment by jorisre** [comment]
Hi @arochadaniel 
Don't use the resolvers rc version, it's an old version. Install the beta to get it works:
```sh
yarn add @hookform/resolvers@beta
```

**Comment by arochadaniel** [comment]
Thank you @jorisre! Now is fixed. 
Closing.
