### ISSUE TITLE
React-datepicker dirty flag is incorrect upon reselect of default value

### ISSUE THREAD

**Issue by QuicklynX19** [react-hook-form/react-hook-form#4587]
_Originally posted by @QuicklynX19 in https://github.com/react-hook-form/react-hook-form/discussions/2345#discussioncomment-551178_

**Describe the bug**
I have come across this issue as well, where when we want to update a react-datepicker field, once selecting the defaultValue date, it will still mark the form dirty (dirtyFields has the date input inside). I would guess that the issue here is that two Date objects are being compared and as stated [here](https://stackoverflow.com/questions/7606798/javascript-date-object-comparison) two Date objects are not the same, no matter if the dates are. Would you mind taking a look at this?

**To Reproduce**

1. Visit [https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r](https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r)
2. Observe the `formState` field (either console.log it or use react developer tools)
3. Change the React-datepicker date to a different defaultValue
4. Change the React-datepicker date back to defaultValue

**Expected behavior**
The form will still mark the date as dirty, even though the initial value was selected. Expected behavior is that upon defaultValue selection, date wouldn't be marked as dirty

**Comment by bluebill1049** [comment]
please don't just fork my codesandbox... instead try to isolate the problem and help us to find out the root cause easier, provide another isolated codesandbox.

**Comment by QuicklynX19** [comment]
Here is a [link ](https://codesandbox.io/s/react-hook-form-v6-controller-forked-dvcbc?file=/src/index.js) with just the date picker that is at the issue. Above is the provided `defaultValue` and below is the `formState.dirtyFields` object. Upon selecting any date on the date picker, the date picker is marked as dirty. Selecting the default date again, would not clear that state (it will **always stay dirty**, no matter if the value is equal to the provided `defaultValue`)

**Comment by bluebill1049** [comment]
This is a problem with compare `Date` object with string right?

**Comment by QuicklynX19** [comment]
What I'm guessing is the issue is that **time part** in the Date object is different. Once we create a date picker we are setting `new Date()` which has its own timestamp and upon selection, a different timestamp is selected. That's why the equal check fails. 

I have **updated the sandbox** to reflect this acknowledgment. If you click submit upon page load (not changing the date) it will say they are the same and not set `dirtyFields`. Because they will have the same timestamp. But once we click on the date, the milliseconds will reset to `.000Z` and thus all further checks will fail.

**Comment by bluebill1049** [comment]
I think you will need to manipulate the value gets send to hook form, it's not a bug in the lib itself.
