### ISSUE TITLE
API page on website not working for v7 (?)

### ISSUE THREAD

**Issue by brentguf** [react-hook-form/react-hook-form#4588]
**Describe the bug**
API page on website returns a 404. The version in the URL is not correct (undefined): https://react-hook-form.com/vundefined/api.

I only seem to have it when the language selector is present in combination with v7.

![hook form](https://user-images.githubusercontent.com/16427929/113419893-a40d2800-93c8-11eb-9695-68faaca01e7f.PNG)

**To Reproduce**
I don't know how I arrived at the homepage where I have both the language selector and version 7. I can't reproduce getting there. When I select v7, the language selector disappears.

**Comment by Alexus2** [comment]
same problem.
clear cookie and local storage helped me

**Comment by bluebill1049** [comment]
yep, open in a new tab should resolve the issue. It's due to a session storage conflict.
