### ISSUE TITLE
V7 setValue method to change field Array

### ISSUE THREAD

**Issue by olesmarola** [react-hook-form/react-hook-form#4589]
**Describe the bug**
Maybe I don't understand something (tell me, please), but if I want to change the values ​​for a group of related fields at once, then nothing happens (maybe I'm using the wrong method of course :З).

**To Reproduce**

1. Go to sandbox
2. Click on button to change values for fields
4. See that nothing happens

**Codesandbox link (Required)**
https://codesandbox.io/s/cranky-wood-vornd?file=/src/index.jsx

**Expected behavior**
inputs values need to be changed

**Screenshots**
https://cln.sh/i7cLLq

**Desktop (please complete the following information):**
- OS: macOS 11.2.3
- Browser: Chrome 89.0.4389.114

**Comment by nucleartux** [comment]
fixed version: https://codesandbox.io/s/happy-leakey-pem59
