### ISSUE TITLE
V7 await trigger always returning 'undefined'

### ISSUE THREAD

**Issue by hugo-andrade** [react-hook-form/react-hook-form#4592]
### Describe the bug
Trigger validation across the form is not working property.

### To Reproduce
Codesandbox from API page:
[https://react-hook-form.com/api/useform/trigger](https://codesandbox.io/s/react-hook-form-v6-triggervalidation-forked-8w9tn)
Go to sandbox and than click the button "Trigger Async First Name Validation"

### Expected behavior
Return true or false

**Comment by jorisre** [comment]
Hi @hugo-andrade 👋🏻 

The `trigger` function no longer returns validation, that's why you get `undefined`

https://react-hook-form.com/api/useform/trigger

![Screenshot 2021-04-02 at 21 35 48](https://user-images.githubusercontent.com/7545547/113448052-65449580-93fb-11eb-9e5a-7540421f34c7.png)

Thanks for reporting, I'll add the info to the [migration guide](https://react-hook-form.com/migrate-v6-to-v7/)

**Comment by hugo-andrade** [comment]
Thanks for the quick response @jorisre! 

Now, the best approach to check if the validation fields are valid is call trigger than inspect error object for errors?

**Comment by jorisre** [comment]
Yes, when you trigger a field then you have to read the `formState.errors.FIELDNAME` value to know if the validation pass or not.

**Comment by hugo-andrade** [comment]
Ok, thanks @jorisre!

**Comment by bluebill1049** [comment]
Thank you @jorisre

**Comment by daggmano** [comment]
The sample code on the API page is still showing the Promise version. Oh, and the API menu link for v7 goes to https://react-hook-form.com/vundefined/api, getting a 404.

**Comment by bluebill1049** [comment]
> The sample code on the API page is still showing the Promise version. Oh, and the API menu link for v7 goes to https://react-hook-form.com/vundefined/api, getting a 404.

Take a look at here: https://react-hook-form.com/api/useform/trigger

**Comment by daggmano** [comment]
Yep, that's the one...
![image](https://user-images.githubusercontent.com/290460/113644912-f732f380-96c4-11eb-8b6c-7925e2f66c79.png)

**Comment by bluebill1049** [comment]
> Yep, that's the one...
> ![image](https://user-images.githubusercontent.com/290460/113644912-f732f380-96c4-11eb-8b6c-7925e2f66c79.png)

oh, you are right! would you like to send a PR?

**Comment by daggmano** [comment]
If I get a chance I can, but I'm not sure when I'll get a chance.

**Comment by bluebill1049** [comment]
> If I get a chance I can, but I'm not sure when I'll get a chance.

np, i will get it sorted.
