### ISSUE TITLE
path.split is not a function

### ISSUE THREAD

**Issue by darrenbarklie** [react-hook-form/react-hook-form#4595]
**Describe the bug**
Follow the initial [Get Started](https://react-hook-form.com/get-started/) documentation, install on a new Create Next App. Adding an input with `ref={register}` produces blocking error.

**To Reproduce**

1. Create Next App
2. `npm install react-hook-form`
3. Copy example block
4. Unhandled Runtime Error / TypeError: path.split is not a function

**Codesandbox link (Required)**
Occurs on default CodeSandbox: [https://codesandbox.io/s/react-hook-form-defaultvalues-v6-09b8g](https://codesandbox.io/s/kw7z2q2n15?file=/src/index.js)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- "react-hook-form": "^7.0.0"
- OS: macOS latest
- Browser: All

**Additional context**
```jsx
import { useForm } from "react-hook-form";

function Form() {
  const { register } = useForm();

  return (
    <div>
      <h2>Form</h2>
      <input name="firstName" ref={register} />
    </div>
  );
}

export default Form;
```

**Comment by leylandjacob** [comment]
Experiencing the same issue

**Comment by bluebill1049** [comment]
the wrong version, the above syntax is for v6.  Take a look at here: https://react-hook-form.com/v6/api

**Comment by w3bdesign** [comment]
If you use react-hook-form version 6, then the mentioned code above will work.

**Comment by christowiz** [comment]
@bluebill1049 The default example on the homepage is using version 6 but you wouldn't know unless you inspected the dependencies.  Is there a version 7 example that it could be replaced with.
![image](https://user-images.githubusercontent.com/597282/114675433-13362680-9cbd-11eb-90e5-ad002108d373.png)

**Comment by bluebill1049** [comment]
> @bluebill1049 The default example on the homepage is using version 6 but you wouldn't know unless you inspected the dependencies. Is there a version 7 example that it could be replaced with.
> ![image](https://user-images.githubusercontent.com/597282/114675433-13362680-9cbd-11eb-90e5-ad002108d373.png)

can you point me to the section? will get that fixed.

**Comment by ViieeS** [comment]
Found mention here:
https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md#v700-alpha0---2021-01-31

It would be better to summarise all changes from v6->v7 in release version notes as well and some migration guid also would be helpful.

**Comment by bluebill1049** [comment]
> Found mention here:
> https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md#v700-alpha0---2021-01-31
> 
> It would be better to summarise all changes from v6->v7 in release version notes (note alfa/beta/rc ones) as well and some migration guid also would be helpful.

Thanks @ViieeS take a look at here: https://react-hook-form.com/migrate-v6-to-v7
