### ISSUE TITLE
V7: Controller field.onChange is not memoized

### ISSUE THREAD

**Issue by anark** [react-hook-form/react-hook-form#4596]
**Describe the bug**
When using the onChange render prop of a Controller in v7 and passing it to a component that uses the onChange as a dependency of useEffect an infinite rerender occurs because the field.onChange render prop is not memoized as it was in V6

**To Reproduce**
1. View the codeSandbox at https://codesandbox.io/s/react-hook-form-useform-template-forked-0yrie?file=/src/index.js.
2. Click the 'Change Value' button
3. View console errors.

**Expected behavior**
onChange is memoized and can be used as a dependency without causing an infinite rerender

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-forked-0yrie?file=/src/index.js

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by anark** [comment]
Sorry @bluebill1049 , I've added the simplest example I could figure out how to workup via CodeSandbox.  It's a bit of a contrived example to simply show the issue.

**Comment by bluebill1049** [comment]
no worries, I would recommend to move that onChange inside your own `onChange`, i don't find the need to memorize the onChange, it should be cheap and simple.

**Comment by anark** [comment]
That makes sense.  Just wanted to note the regression as this wasn't the case in V6 and see if there were other unintended consequences.  I'll proceed using either `setValue` or by passing the onChange to a memoized function

**Comment by bluebill1049** [comment]
Thanks for understanding, we have clean up the useController quite a bit in the v7.

**Comment by orenklein** [comment]
In my case, I have a complex form which can reach to hundreds of fields. 
Some of the components rendered under useController/Controller are expensive. So it is kind of a necessity to memoize those functions. 
In order to solve it, I wrote a useController that memoizes the functions as follows:

      export const useControllerMemoized = <TFieldValues extends FieldValues = FieldValues>(
        options: UseControllerProps<TFieldValues>
      ): UseControllerReturn<TFieldValues> => {
      
        const { field, ...rest } = useController(options);
        // eslint-disable-next-line
        const onBlur = React.useMemo(() => field.onBlur, []);
        // eslint-disable-next-line
        const onChange = React.useMemo(() => field.onChange, []);
        // eslint-disable-next-line
        const ref = React.useMemo(() => field.ref, []);
        return { field: { ...field, onBlur, onChange, ref }, ...rest };
      };

My only concern is that it might be prone to unexpected behavior after upgrading to future versions.
