### ISSUE TITLE
V7: formState.isDirty is not set to true onChange if value is watched

### ISSUE THREAD

**Issue by anark** [react-hook-form/react-hook-form#4597]
**Describe the bug**
In v7 in a form with only one input the formState.isDirty will not be true when the input is changed if you are watching the form value.  It will become true once the input is blurred, however this is not good if the save button is disabled when !form.isDirty as it prevents the user from submitting the form unless they have blurred the input.

If you remove the watch on the form value it works as expected

**To Reproduce**
Create a form with a single input and set the submit button to be disabled if !formState.isDirty

1.  Watch a field with something similar to what is below or in the codeSandbox
```
function Form(){
  const { register, formState, watch } = useForm()
  const { isDirty } = formState

  const name = watch('name')
  return <form>
    <input type='text' {...register('name')} />
    <button type='submit' disabled={!isDirty}>Save</button>
  </form>
}
```
2.  Change the field value
3. The submit button will be disabled when it should be enabled

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-forked-rpm8c?file=/src/index.js

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by anark** [comment]
@bluebill1049 , Sorry about that.  I've added a codeSandbox link and a bit more context.  It appears this only happens when you are using watch to watch the value of the field.

Also would it be possible to update the codeSandbox templates in the issue template to use V7?  Currently the samples use v6.

**Comment by bluebill1049** [comment]
I see the problem you are missing `defaultValues`, for hook form to check dirty state, we are compare with `defaultValues`.

<img width="943" alt="Screen Shot 2021-04-04 at 9 50 49 am" src="https://user-images.githubusercontent.com/10513364/113494407-3f1e1300-952b-11eb-9a6a-a5a872cd8e1d.png">

**Comment by anark** [comment]
I don't think that is the problem.

The codeSandbox I shared in fact does set defaultValues.

If I remove the watch command it works correctly, however if I am watching the filed then isDirty is not set until the input is blured.

**Comment by bluebill1049** [comment]
thank you, that's a valid bug.

**Comment by tombburnell** [comment]
Has a fix for this been included in latest version?

I'm suffering from this same issue using 7.28.0.

I have an onChange handler on an input and changes to the input do not affect the Dirty state until blur unless I remove the onChange handler.

**Comment by Moshyfawn** [comment]
Working fine in the latest version: see [this CSB](https://codesandbox.io/s/late-violet-zz55ub?file=/src/App.tsx)

**Comment by tombburnell** [comment]
> @tombburnell, works fine in the latest version: see [this CSB](https://codesandbox.io/s/late-violet-zz55ub?file=/src/App.tsx)

Hi, Your example doesn't contain an onChange()  handler on the input field.  If you add one like below, then the isDirty flag is not updated until the focus changes away from the edited field.
regards, Tom

function titleChange(e: any) {
    console.log("Title changed", e.target?.value);
 }
  
  return (
    <div>
      <Headers
        renderCount={renderCount}
        description="Performant, flexible and extensible forms with easy-to-use validation."
      />

      <form onSubmit={handleSubmit(onSubmit)}>
        <input {...register("firstName")} placeholder="First Name" onChange={titleChange}/>
        <pre>
          <code>First Name: {firstName || "''"}</code>
        </pre>
        <button disabled={!isDirty} type="submit">
          Submit
        </button>
      </form>
    </div>
  );

**Comment by Moshyfawn** [comment]
By spreading all the `register` props to your input via `{...register("field")}` and passing your `onChange` handler after, you're re-assigning the input's `onChange` which is used by RHF.

Please, assign your `onChange` handler as a second options argument to `register` instead.
```diff
<input
  {...register("name", {
+   onChange: titleChange
  })}
-   onChange={titleChange}
/>
```

**Comment by Moshyfawn** [comment]
> > @tombburnell, works fine in the latest version: see [this CSB](https://codesandbox.io/s/late-violet-zz55ub?file=/src/App.tsx)
> 
> Hi, Your example doesn't contain an onChange() handler on the input field. If you add one like below, then the isDirty flag is not updated until the focus changes away from the edited field. regards, Tom
> 
> function titleChange(e: any) { console.log("Title changed", e.target?.value); }
> 
> return (
> 
> ```
>   <form onSubmit={handleSubmit(onSubmit)}>
>     <input {...register("firstName")} placeholder="First Name" onChange={titleChange}/>
>     <pre>
>       <code>First Name: {firstName || "''"}</code>
>     </pre>
>     <button disabled={!isDirty} type="submit">
>       Submit
>     </button>
>   </form>
> </div>
> ```
> 
> );

By spreading all the `register` props to your input via `{...register("field")}` and passing your `onChange` handler after, you're re-assigning the input's `onChange` which is used by RHF.

Please, assign your `onChange` handler as a second options argument to `register` instead.
```diff
<input
  {...register("name", {
+   onChange: titleChange
  })}
-   onChange={titleChange}
/>
```

**Comment by tombburnell** [comment]
> 

Ahha - right, it works now.  Thank you.

**Comment by tombburnell** [comment]
I have another similar issue - I have a field 'xxx' that is populated programatically a bit like the following.. where I use setValue() to update a field - this is also not causing the isDirtyFlag to update. Is there a way around this?

<input type="text" {...register('xxx')} />
<button onClick={() => setValue("xxx", "test")}>press me</button>

Also, similarly, I have a file input that I am not currently register on and just using setValue after uploading the image and resizing it... this also does not cause the isDirty to update. I tried to use register() and place the onChange inside it, but it caused the value of the input to become { 0: {} } and I'm not sure I understand why.

 <input
        type="file"
        onChange={(e) => { handleImageUpload(e, (imageUrl) =>  setValue("image_url", imageUrl))}}
    />

Any tips appreciated. Thanks

**Comment by Moshyfawn** [comment]
You want to set the `shouldDirty` flag to `true` in the third options argument of `setValue`.

You can learn more at [RHF `setValue` method docs](https://react-hook-form.com/api/useform/setvalue)

```js
setValue('name', 'value', { shouldDirty: true })
```

**Comment by tombburnell** [comment]
> You want to set the `shouldDirty` flag to `true` in the third options argument of `setValue`.
> 
> You can learn more at [RHF `setValue` method docs](https://react-hook-form.com/api/useform/setvalue)
> 
> ```js
> setValue('name', 'value', { shouldDirty: true })
> ```

Brilliant thanks, that works! thanks for the pointer in the docs too.

**Comment by Moshyfawn** [comment]
I'm glad I could help!

**Comment by bluebill1049** [comment]
thanks @Moshyfawn 🙏
