### ISSUE TITLE
Controller and useController are not strictly typed

### ISSUE THREAD

**Issue by lynxtaa** [react-hook-form/react-hook-form#4599]
**Describe the bug**
react-hook-form@7 should infer types  for `value` and `onChange` props of `Controller` and `useController` from `name` prop

**To Reproduce**

1. Open codesandbox link
2. Hover over `onChange` and `value` in Controller
3. See `any`

**Codesandbox link (Required)**
https://codesandbox.io/s/smoosh-hooks-iuw56?file=/src/App.tsx

**Expected behavior**
Correct typing based on `name` prop

**Screenshots**
![Снимок экрана 2021-04-03 113400](https://user-images.githubusercontent.com/22496946/113473281-63b5b480-9471-11eb-8a29-666adf6960c2.png)
![Снимок экрана 2021-04-03 113422](https://user-images.githubusercontent.com/22496946/113473283-66b0a500-9471-11eb-9e2c-71dd80d56865.png)

**Comment by lynxtaa** [comment]
Wow, that was fast! Thank you @bluebill1049 for your work on this awesome library

**Comment by bluebill1049** [comment]
👍

**Comment by clarkbynum** [comment]
@bluebill1049 I see that the type for value is now typed correctly but it looks like your PR did not address the parameter type for the onChange function. Is this possible?
