### ISSUE TITLE
V7: `form.watch(watchObserver)` should always include `{type}`

### ISSUE THREAD

**Issue by mikestopcontinues** [react-hook-form/react-hook-form#4601]
**Is your feature request related to a problem? Please describe.**

`{type}` should always be available when using an observer. The reason being, the callback receives a lot of data, and filtering it to be able to act on it correctly is important.

For instance, my app supports live updates on an iframe, so when a user changes a form field, I tell the iframe to update. I need to send an identical message when a field value updates via `setValue()`, but not when it updates via `reset()` or `unregister()`. The trouble is, there's no way to differentiate between `set` and `reset` or `unregister` events, and they all occur within the context of form use.

**Describe the solution you'd like**

Right now, only type `change` exists, but the values should include: `reset`, `unregister`, `register`, and `set`.

For type `set`, it may make more sense for the type to be sent as `change`, or perhaps that it includes the `setValue` options as well. I'm not sure about the specifics, but I would likely opt for a `set` type.

**Describe alternatives you've considered**

This seems like the best option I can think of.

**Comment by bluebill1049** [comment]
can you give an example of the above?

**Comment by mikestopcontinues** [comment]
Sure:

https://codesandbox.io/s/formwatch-types-o7yoh?file=/src/index.js

Notice:
1. Editing fields - type: 'change'
2. Setting fields programatically (set button) - type: undefined
3. Unregistering fields (reg/unreg button) - type: undefined
4. Registering fields (reg/unreg button) - type: undefined

Yes, it's possible to infer the `set` action, but only if you aren't using `undefined` values, as that's the only way to tell the difference between `set` and `unregister`.

Register, I suspect, should also trigger watch, at least when a field is registered after the form is initialized. In this particular case, it's useful to know, especially when using a field array. There are times when it will have a value from `useForm({defaultValues})`, `form.register(name, {defaultValue})`, `<input defaultValue={} />`, or when it will have an undefined value, and yet is still distinct from other ways a field can end up with an `undefined` value.
