### ISSUE TITLE
[Preact, RHF 7.0] Radio inputs not working 

### ISSUE THREAD

**Issue by r04423** [react-hook-form/react-hook-form#4604]
**Describe the bug**
Radio inputs aren't working correctly in Preact project after upgrading to the latest RHF version.
Only last selected input produces a value, other input values are shown as `null`.

**To Reproduce**

1. Go to the Codesandbox example
2. Click on 'One', click 'Submit'
3. `{test: null}` is logged to the console
4. Click on 'Three', click 'Submit'
5. `{test: "three"}` is logged to the console

**Codesandbox link (Required)**
https://codesandbox.io/s/funny-saha-1dr1e?file=/src/index.js

**Expected behavior**
All radio inputs produce values.

**Screenshots**
N/A

**Desktop:**

- OS: Windows
- Browser: Edge
- Version: 89

**Additional context**
Not sure if Preact compatibility is something that has any priority, just wanted to report this as it worked in RHF 6.

**Comment by leapful** [comment]
@r04423 

Preact is currently handling "ref callback" different than React. At the time "ref callback" is triggered, radio inputs are not attached to the page yet. When collecting and merging DOM reference of multiple radio inputs in a radio group, method "register" of react-hook-form v7 performs a safe filtering to check if those radio inputs exists in the page or not by using "document.contains(ref)" therefore the previous DOM references are cleared and only the last "ref" is available.

Using Controller is a workaround for this issue at the moment:
https://codesandbox.io/s/admiring-bush-ht19u?file=/src/index.js

@bluebill1049 

Do you see any problem if we remove the filter condition "document.contains" in 

https://github.com/react-hook-form/react-hook-form/blob/17788756bbdabf3121edcb96ada1e8e465ba5076/src/useForm.ts#L866

**Comment by bluebill1049** [comment]
> @r04423
> 
> Preact is currently handling "ref callback" different than React. At the time "ref callback" is triggered, radio inputs are not attached to the page yet. When collecting and merging DOM reference of multiple radio inputs in a radio group, method "register" of react-hook-form v7 performs a safe filtering to check if those radio inputs exists in the page or not by using "document.contains(ref)" therefore the previous DOM references are cleared and only the last "ref" is available.
> 
> Using Controller is a workaround for this issue at the moment:
> https://codesandbox.io/s/admiring-bush-ht19u?file=/src/index.js
> 
> @bluebill1049
> 
> Do you see any problem if we remove the filter condition "document.contains" in
> 
> https://github.com/react-hook-form/react-hook-form/blob/17788756bbdabf3121edcb96ada1e8e465ba5076/src/useForm.ts#L860-L866
> 
> ?

yes, @leapful you want to send a PR, let's see if it breaks anything.

**Comment by leapful** [comment]
@bluebill1049 PR is created at https://github.com/react-hook-form/react-hook-form/pull/4615

**Comment by leapful** [comment]
@r04423 

There is an use case to show/hide input element that needs "document.contains", while the "detached" DOM element and "not attached yet" DOM element have the same behavior, it's hard to define a handling for use case of Preact.

I would suggest another workaround to keep using "register" instead of using Controller:

```
const { register } = useForm();

const customRegister = (name, options) => {
  const { ref, ...field } = register(name, options);
  
  const customRef = (...args) => {
    setTimeout(() => ref(...args));
  }
  
  return { ...field, ref: customRef };
}

// Just use "customRegister" instead of "register"
```

**Comment by r04423** [comment]
@leapful and @bluebill1049 thank you so much for looking into this!

And indeed, this workaround does seem to work 👍

**Comment by bluebill1049** [comment]
Thank you very much @leapful
