### ISSUE TITLE
isValid is false when there are no errors

### ISSUE THREAD

**Issue by lynxtaa** [react-hook-form/react-hook-form#4610]
**Describe the bug**
`isValid` is false when there are no errors in react-hook-form@7

**To Reproduce**

1. Create a form
2. console.log('isValid', isValid) // false

**Codesandbox link (Required)**
https://codesandbox.io/s/busy-elion-32tkr?file=/src/App.tsx

**Expected behavior**
Expected `isValid` to be `true`

**Comment by jhg023** [comment]
I had a similar issue in version `6.15.4` where `isValid` would be true when the page was first loaded, but any subsequent page refresh would cause it to be `false`. I've given up at this point and removed `isValid` from our codebase.

**Comment by lynxtaa** [comment]
https://github.com/react-hook-form/react-hook-form/blob/17788756bbdabf3121edcb96ada1e8e465ba5076/src/useForm.ts#L144 hmm.. it seems like `isValid` is `false` when `mode: "onSubmit"`

**Comment by bluebill1049** [comment]
`onChange` or `onBlur` mode only.

<img width="960" alt="Screen Shot 2021-04-04 at 8 29 41 am" src="https://user-images.githubusercontent.com/10513364/113493102-e85f0c00-951f-11eb-95c0-df86a9a7954e.png">
