### ISSUE TITLE
v7: Error when use input date (native) with  required validation

### ISSUE THREAD

**Issue by JuanLuisGarciaBorrego** [react-hook-form/react-hook-form#4617]
**Describe the bug**
```
Warning: unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering.

"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-hook-form": "^7.0.0"

```
**To Reproduce**

1. Go to [codesanbox](https://codesandbox.io/s/funny-montalcini-p2z7c?file=/src/index.js) 
2. Use <input {...register("date", { required: "required" })} type="date" />
3. Choose a date
4. Submit //view console.log(form data is ok)
5. choose the date and press the backspace key on the keyboard // Error!!! view console.log(Warning: unstable_flushDiscreteUpdates)
6. Remove formState: { errors } from useForm 
7. Choose a date
8. Submit
9. choose the date and press the backspace key on the keyboard // it works 

**Codesandbox link (Required)**
[Link codesanbox](https://codesandbox.io/s/funny-montalcini-p2z7c?file=/src/index.js
)Include a codesandbox will help us to investigate the issue quicker.

**Screenshots**
Include video gif

https://user-images.githubusercontent.com/5416367/113519292-8d62fe80-958b-11eb-893a-df2dd8a48654.mov

**Desktop (please complete the following information):**

- OS: [Mac]
- Browser [chrome]
- Version [89.04]

**Additional context**
```javascript
function App() {
  const {
    register,
    handleSubmit,
    formState: { errors }
  } = useForm();

  const onSubmit = (data) => {
    console.log(data);
  }; // your form submit function which will invoke after successful validation

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <label>Input date native</label>
      <input {...register("date", { required: "required" })} type="date" />
      <p>Step to error (open console):</p>
      <ol>
        <li>choose a date</li>
        <li>Submit</li>
        <li>choose the date and press the backspace key on the keyboard</li>
        <li>
          IMPORTANT!!: If remove formState: errors from use Form, does NOT show
          the error
        </li>
      </ol>

      <input type="submit" />
    </form>
  );
}
```

**Comment by bluebill1049** [comment]
provide a `defaultValue` should resolve this problem, i think that would make sure React **know** this is an uncontrolled input.

**Comment by JuanLuisGarciaBorrego** [comment]
Hello @bluebill1049, thanks for your reply, I have tried defaultValue but the same thing happens...
...

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/113550473-74fbee00-9636-11eb-9595-44390ea94551.mov

works fine for me?

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/113550632-b9878980-9636-11eb-9ead-21a77a8e9e0a.mov

works for me.

**Comment by JuanLuisGarciaBorrego** [comment]
Stay the same, even with defaultValue

[Link codesanbox](https://codesandbox.io/s/funny-montalcini-p2z7c?file=/src/index.js)
https://user-images.githubusercontent.com/5416367/113671756-14f95c00-96b7-11eb-9989-1df67ba0d746.mov

**Comment by JuanLuisGarciaBorrego** [comment]
Stay the same, even with defaultValue

https://user-images.githubusercontent.com/5416367/113671901-440fcd80-96b7-11eb-82d0-401c7f2d1571.mov

[Link codesanbox](https://codesandbox.io/s/funny-montalcini-p2z7c?file=/src/index.js)

Note: First submit and then remove with keyboard any data (day, month or year)
