### ISSUE TITLE
Provide a way to disable merging of `defaultValues` into submission results

### ISSUE THREAD

**Issue by bmamouri** [react-hook-form/react-hook-form#4619]
**Is your feature request related to a problem? Please describe.**
V7 [introduced](https://github.com/react-hook-form/react-hook-form/discussions/3714) a new feature to merge `defaultValues` into submission result.

This would break the logic for many use cases including dynamically generated fields. If the defaultValue includes `mobileNumbers[3]` and the user delete that particular mobile number, the submission results would include the number that user intended to delete which renders the deletion useless.

**Describe the solution you'd like**
A way to disable the merging by default. At the moment, I cannot keep using V7 because there is absolutely no way to extract the actual state of the form. Because `defaultValues` is canceling all the deletions.

**Describe alternatives you've considered**
Since `getValues`, `watch`, and `handleSubmit` is also affected, there is no way to extract the actual data. If there is an alternative, I can't see it.

**Additional context**
I understand users voted for this feature, but I think it does more harms than good. Merging the result is such an easy thing that users would be able to make a decision themselves and implement it in their code. I don't really think the library should be in charge of making this decision. At least there should be a way to disable it.

**Comment by bluebill1049** [comment]
Thanks for your feedback and feature request.

>  Because defaultValues is canceling all the deletions.

can you provide an example on the above?

**Comment by bmamouri** [comment]
Thank you for your reply.

I've build a [simple demo](https://github.com/bmamouri/react-hook-form-issue) to show the issue:

```
import {useState} from 'react';
import './App.css';
import {useForm} from 'react-hook-form'
import {v4} from 'uuid';

function App() {
    const defaultValues = {
        [v4()]: 'A',
        [v4()]: 'B',
        [v4()]: 'C',
    }

    const [data, setData] = useState(defaultValues)
    const {register, handleSubmit} = useForm({defaultValues});

    const onSubmit = (data) => {
        console.log(data); // Return all the fields, even the deleted ones
    }

    const deleteField = (key) => {
        setData(
            Object.fromEntries(
                Object
                    .entries(data)
                    .filter(item => item[0] !== key)
            )
        )
    }

    return (
        <div className='App'>
            <form onSubmit={handleSubmit(onSubmit)}>
                {Object
                    .entries(data)
                    .map((item) => {
                        const key = item[0];
                        const value = item[1];

                        return (
                            <p key={key}>
                                <input name={key} defaultValue={value} {...register} />
                                <button type='button' onClick={() => deleteField(key)}>Remove</button>
                            </p>
                        )
                    })
                }

                <button type='submit'>Submit</button>
            </form>
        </div>
    );
}

export default App;
```

**Comment by bluebill1049** [comment]
That's a valid example, however, could I recommend using useFieldArray to deal with Field Array, but I have actually resolved the problem there.

**Comment by deniercounter** [comment]
This is similar to https://github.com/react-hook-form/react-hook-form/discussions/4515#discussioncomment-534067 from 25. March 2021. In these sandboxes using the usefieldArray() and its remove(index)-function didn't prevent these "removed" values from being submitted in the array.

**Comment by bluebill1049** [comment]
> This is similar to [#4515 (reply in thread)](https://github.com/react-hook-form/react-hook-form/discussions/4515#discussioncomment-534067) from 25. March 2021. In these sandboxes using the usefieldArray() and its remove(index)-function didn't prevent these "removed" values from being submitted in the array.

just check the example is broken... can you supply a simple and clean version? 

<img width="585" alt="Screen Shot 2021-04-05 at 11 01 18 pm" src="https://user-images.githubusercontent.com/10513364/113576387-d5a12000-9662-11eb-8aaa-71b0ef63d308.png">

**Comment by wdfinch** [comment]
@bmamouri 

I brought this up initially and pushed for this. The reason this was added was that in many use cases, it helps tremendously to have access to the default values. I guess it depends on your view of what default values are. To me, they are the starting form values that I want to include and have access to all the time. If I submit data, run `getValues`, `watch`, etc. I want to have my default values present. I could merge them in manually myself, but I would rather have the lib do this as it makes life much easier.

I do have a use case like yours where I want to delete a field and it doesn't make sense to use a field array. I think you could use `unregister` as a workaround. With `unregister` you can add an option called `keepDefaultValue`. I believe this would solve your issue of delete a field input and not having the default value persisted.

Assuming this works for you, do you have any other use cases for this aside from deleting input keys?

**Comment by bmamouri** [comment]
@wdfinch 

Thank you for the comment. Unfortunately, I wasn't able to use `unregister` to make this work. I receive the deleted inputs even after some inputs are unregistered. Maybe I am doing something wrong. I yet need to look into using `useFieldArray` to see if that can be used to solve this issue. When I started using this library `useFieldArray` did not exist.

There are also a few other use cases that this change breaks:

1. Before you could fetch data from a GraphQL endpoint and feed it into `defaultValues` and get the modified values back. But now you need to remove GraphQL `__typename` field carefully. Otherwise, the submitted value to the API endpoint contains `__typename`, which is obviously not a valid field in your GraphQL Input.

2. If you've hidden fields like `createdAt`, `updatedAt`, `deletedAt` that are maintained in the database automatically (db triggers handle their values), you were able to feed the fetched record to `defaultValues` and be ensured that you will receive only the values that actually exist in the form, and consequently write those value down in the database without requiring to remove the aformentioend fields.

I think this change makes the life of 70% of people who vote for it **slightly easier** (and only in few use cases), but it makes the life of that 30% who voted against it **difficult** or in some cases, it simply disallows them from using V7 unless they monkey patch it. 

I know that @bluebill1049 is very careful to keep the API as light as possible and as unopinionated as possible. But in my humble oponion, this change is against all of that. I think, features like this can and should be handled in user land not in the API.

**Comment by wdfinch** [comment]
Hi @bmamouri. 

Thanks for the reply. You cannot use `unregister` on individual field array inputs. You can `unregister` the entire field array or normal inputs. To remove the default values from field arrays, I suggest using `setValue`. You can pass in an array to represent the state you want. 

Regarding your other points:

1. The library is not meant to hold arbitrary data unrelated to inputs. Although you can pass whatever you want into default values, this goes against the design. Therefore, I don't think data like `__typename` should be passed in at all. Instead, you should parse the data returned from the server to align with the inputs you have in your form. 

2. Relates to the above. If you want those values to be submitted as part of your form data, you should add a hidden input. This is the correct way to add metadata to a form according to the HTML standard and what the library suggests as well. If you don't want them as form data, then they shouldn't be passed to default values. 

Additionally, another solution rather than deleting keys of form values is to set the values to null or undefined. This could indicate that you aren't interested in the value. You could also use booleans like checkboxes to indicate whether a field or fields should be included in what you submit to the server.

Obviously the deleting of keys does become a little more challenging with the new approach. However, I would say that aside from the convenience of having access to our default values, the shallow merge helps to enforce proper use of the library. I feel like the two cases above go against the recommended use of the library.

However, at the end of the day, it comes down to what works best for you. Adding an option to avoid the shallow merge would probably be pretty easy to do. This feature has not changed the internal representation of the data. We could simply skip the merge when running `getValues`, `watch`, or `handleSubmit`. I personally don't have a use for it, but I don't see an issue adding this option.

**Comment by bluebill1049** [comment]
Thanks, guys, for all the valid feedback. I will keep an eye on this feature request.

**Comment by bluebill1049** [comment]
Going to do an RFC on this one after `shouldUnregister`, my purpose is to have a config at `useForm` to turn on and off the behavior.

```
useForm({
  shouldIncludeDefaults: true, // or shouldMergeDefaults
})
```

let me know you guys's early thoughts on this.

**Comment by wdfinch** [comment]
That works. What would the default option be?

**Comment by bluebill1049** [comment]
> That works. What would the default option be?

true, so it's not a breaking change.

**Comment by wdfinch** [comment]
Ok sounds good.

**Comment by bmamouri** [comment]
Eventually, I started using `useFieldArray` with the hope that users can successfully delete some fields. However, the problem still persists. I am using `useWatch` to conditionaly render a field array. (as demonstrated in the [docs](https://react-hook-form.com/api/usefieldarray)). Given the following `defaultValue`:

```jsx
{
        hasNicknames: true,
        nicknames: ['Joe Bananas']
}
```

When the user disable `hasNicknames`, the existing nicknames should be deleted. However, since the `defaultValue` is merged back into the submitted values, it still exist in the submitted paylod. Do I need to somehow unregister the fields. This is my conditional field:

```jsx
const NicknamesField = ({control, index, register}: {
    control: Control<MafiaFormData>;
    index: number;
    register: UseFormRegister<MafiaFormData>;
}) => {
    const incorrect = useWatch<any>({
        name: `body.parts.${index}.hasNicknames`,
        control,
        defaultValue: false,
    });

    const {fields, append, remove} = useFieldArray({name: `body.parts.${index}.nicknames` as any, control});

    return incorrect ?
        <>
            {fields.map((field: any, nicknameIndex: number) => (
                <Label key={nicknameIndex}>
                    <span>Nicknames</span>
                    <TextRow>
                        <input
                            type='text'
                            {...register(`body.parts.${index}.nicknames.${nicknameIndex}` as any)} />

                        {nicknameIndex > 0 &&
                        <CrossIcon onClick={() => remove(nicknameIndex)}/>}
                    </TextRow>
                </Label>
            ))}

            <Toolbar right={true}>
                <Button onClick={() => append('')}>
                    <PlusIcon/> Add nickname
                </Button>
            </Toolbar>
        </>
        : null;
};
```

I think the `defaultValue` should be values that use by default, and should not be related to submitted values (i.e. semantically there are two different things).

I understand that'd be a breaking change, but I really think this option should be off by default for the next release. Otherwise, we should put a big warning sign in the doc telling people that this merge is happening. I have mentioned this before, but this tiny helper feature helped some users marginally, but make it extremly difficult for some other users.

**Comment by bluebill1049** [comment]
setting `shouldUnregister: true` at `useForm` level will resolve all of your concerns above. I am working on it...

**Comment by bmamouri** [comment]
Sorry, @bluebill1049 did not mean to sound ungrateful or critical of you. I truly appreciate that you released this and maintaining it. I expressed my opinion only to recommend improvement. Thanks a lot. I will try the `shouldUnregister` flag.

**Comment by bluebill1049** [comment]
> Sorry, @bluebill1049 did not mean to sound ungrateful or critical of you. I truly appreciate that you released this and maintaining it. I expressed my opinion only to recommend improvement. Thanks a lot. I will try the `shouldUnregister` flag.

@bmamouri i am still working on it, i completely understanding from your point of view as well. give me sometimes, i will ship the cofnig.

**Comment by bluebill1049** [comment]
here is a the commit which i did early on: @bmamouri https://github.com/react-hook-form/react-hook-form/commit/5c993734a8dfc072f0dc564e54ba8e7787217363 if you interested to take a look, still some issues which i am working on. hopefully, this will give you more insight, i am not let go of the issue, just so many things... i try to catch up.

**Comment by bmamouri** [comment]
@bluebill1049 thanks again, and please don't put yourself on too much trouble. I can always revert to V6. I set `shouldUnregister` to true, but that stopped the `useWatch` for conditional rendering. Setting `hasNicknames` checkbox does not show the `nicknames` field array. I think that's the expected behaviour with `shouldUnregister`.

**Comment by bluebill1049** [comment]
> @bluebill1049 thanks again, and please don't put yourself on too much trouble. I can always revert to V6.
> 
> However, setting `shouldUnregister` to true, stops the `useWatch` from working. I am using it to render fields conditionally. In another word, checking `hasNicknames` checkbox does not show the `nicknames` field array. I think that's the expected behaviour of `shouldUnregister` though.

Thanks for understanding. here is a beta version if you interested to try, i want to release it in the next couple of days.

`v7.2.2-beta.0`

`useForm({ shouldUnregister: true })`

**Comment by bmamouri** [comment]
Thank you for pointing me to the beta. But as I've mentioned before `shouldUnregister` flag would stop me from using `useWatch` to render fields conditionally. Is this the intended behaviour?

**Comment by bluebill1049** [comment]
> Thank you for pointing me to the beta. But as I've mentioned before `shouldUnregister` flag would stop me from using `useWatch` to render fields conditionally. Is this the intended behaviour?

Can you provide a CSB on the behavior? provide me some steps as well, i can take a look at it.

**Comment by bmamouri** [comment]
Actually I made it work and setting `shouldUnregister` to true works!

However, I found another issue. When `shouldUnregister` is set to true, you cannot use the `useWatch` hook and the `watch` method returned by `useForm` at the same time:

```
    const {register, handleSubmit, control, watch} = useForm<CorrectMistakeFormData>({
        defaultValues: props.defaultValues,
        shouldUnregister: true,
    });
    const watchAllFields = watch();

    const incorrect = useWatch<any>({
        name: `body.parts.${index}.incorrect`,
        control,
        defaultValue: false,
    });
```

In this example, the `incorrect` doesn't get updated. As soon as I disable `watch()` method it works again.

**Comment by bmamouri** [comment]
Here is a reproducible repo: https://github.com/bmamouri/react-hook-form-issue

Just disable the following line and everything works as expected:

```jsx
const watchAllFields = watch();
```

**Comment by bluebill1049** [comment]
> Here is a reproducible repo: https://github.com/bmamouri/react-hook-form-issue
> 
> Just disable the following line and everything works as expected:
> 
> ```js
> const watchAllFields = watch();
> ```
> 
> Only happens when `shouldUnregister: true`

what's the steps?

**Comment by bmamouri** [comment]
Sorry forgot to include them.

1. Comment the following line:
```
const watchAllFields = watch();
```

2. Press "Add Animal" button. You notice a new row appears.
3. Check "Has Nicknames?" checkbox. You notice "Add nickname" appears. (i.e. useWatch is working)
4. Press "Add Nickname". You notice a new row appears to enter a new nickname.
5. Uncomment the following line. You will notice that selecting "Has Nicknames?" has no effect anymore. (i.e. useWatch is not working)
```
const watchAllFields = watch();
```

In another word, if you watch all field, `useWatch` doesn't work anymore if you set the `shouldUnregister: true`.

**Comment by bluebill1049** [comment]
> Sorry forgot to include them.
> 
> 1. Comment the following line:
> 
> ```
> const watchAllFields = watch();
> ```
> 
> 1. Press "Add Animal" button. You notice a new row appears.
> 2. Check "Has Nicknames?" checkbox. You notice "Add nickname" appears. (i.e. useWatch is working)
> 3. Press "Add Nickname". You notice a new row appears to enter a new nickname.
> 4. Uncomment the following line. You will notice that selecting "Has Nicknames?" has no effect anymore. (i.e. useWatch is not working)
> 
> ```
> const watchAllFields = watch();
> ```
> 
> In another word, if you watch all field, `useWatch` doesn't work anymore (assuming `shouldUnregister: true` as per the codebase).

Thanks @bmamouri will try to patch that tonight and release another beta.

**Comment by bluebill1049** [comment]
looks like the latest fixed the issue: `react-hook-form@7.2.2-beta.1`

**Comment by bmamouri** [comment]
Hey Bill,

Today I tested 7.2.3 version. The issue above is resolved. However this new version has a new issue. All inputs are readonly and cannot be changed anymore. You can see a demo in the previous repo: https://github.com/bmamouri/react-hook-form-issue.

Sorry if this issue is getting too long. If you want I can create a new issue for it.

**Comment by bluebill1049** [comment]
> Hey Bill,
> 
> Today I tested 7.2.3 version. The issue above is resolved. However this new version has a new issue. All inputs are readonly and cannot be changed anymore. You can see a demo in the previous repo: https://github.com/bmamouri/react-hook-form-issue.
> 
> Sorry if this issue is getting too long. If you want I can create a new issue for it.

No worries, can you share a codesandbox instead? so I wouldn't have to clone the repo?

**Comment by bmamouri** [comment]
Here you go: https://codesandbox.io/s/long-rain-1pr72

If you start typing, you notice that the data changes (only one character), but the field doesn't really get updated.

**Comment by bluebill1049** [comment]
Thanks @bmamouri will take a look at it.

**Comment by bmamouri** [comment]
Hey @bluebill1049, Thank you for fixing the bug. I really appreciate it. Would you consider backporting this to 7.2.3 or issuing a new minor release? Is there a way to install the library at that particular commit that you made to fix the issue?

**Comment by bmamouri** [comment]
Hey @bluebill1049, I have tried the newest version 7.3.1. But there is a regression. The `defaultValues` doesn't work anymore. You can see the issue in the following sandbox: https://codesandbox.io/s/github/bmamouri/react-hook-form-issue

I think changing the `defaultValue` behaviour in V7 is causing so much problem. Can I please respectfuly ask you to consider disabling this feature entirely and leave it to user to do the merging, or do this helper utility under a flag?

**Comment by bluebill1049** [comment]
hey @bmamouri pretty sure it's working, as I have tested your example during the PR. I just double check your code, I think it's missing `deafultValue` at each input.

**Comment by bluebill1049** [comment]
check the ref here: https://github.com/react-hook-form/react-hook-form/pull/4930

**Comment by bmamouri** [comment]
So we need to add `defaultValue` to every input field? Is this a new change in V7? Can you please point me to the docs, if it is mentioned there?

**Comment by bluebill1049** [comment]
> So we need to add `defaultValue` to every input field? Is this a new change in V7? Can you please point me to the docs, if it is mentioned there?

This is actually always the case, even with v6 (it probably worked for your use case) otherwise you will have unexpected behavior during the shuffle and more complex operations. 

V7: 
<img width="1036" alt="Screen Shot 2021-04-25 at 3 08 21 pm" src="https://user-images.githubusercontent.com/10513364/115981570-15ab5100-a5d8-11eb-9796-1bd6559b0340.png">

V6:
![Screen Shot 2021-04-25 at 3 09 15 pm](https://user-images.githubusercontent.com/10513364/115981590-396e9700-a5d8-11eb-800f-f52051755a4d.png)

**Comment by bmamouri** [comment]
Hey @bluebill1049, Sorry I was looking at the wrong part of the doc. It is actually wokring properly. Thank you
