### ISSUE TITLE
Interceptors before form validation.

### ISSUE THREAD

**Issue by xiaoyu-tamu** [react-hook-form/react-hook-form#462]
**Is your feature request related to a problem? Please describe.**

The problem that I encountered is form values are transformed to empty strings automatically before validate. Can wee add a way to intercept form values before they are handled by validate function.

A minimal example:
https://codesandbox.io/s/competent-borg-3vcoe?fontsize=14

The yup check is failed b/c field 'phone' is an empty string instead of undefined. I know that I can use yup.lazy to determine at runtime, but it can be quite cumbersome.
```
schema = {
  phone: yup.lazy(
    v === ""
      ? yup.string()
      : yup
          .string()
          .matches(/^[2-9]\d{2}-\d{3}-\d{4}$/, "invalid phone number")
          .notRequired()
          .nullable()
  )
}
```

**Describe the solution you'd like**

Allow user intercept form values before they are handled by validate function.

**Describe alternatives you've considered**

Add an option to transform empty string to undefined or null?

**Comment by bluebill1049** [comment]
hey, @xiaoyu-tamu that's native input return, I don't think it is a good idea to manipulate that. same goes to select option
```
<select>
  <option value={2}>2</option>
</select>
```
You would think select 2 will give 2? not really html select will return string which is "2". To be honest, I would like to follow HTML standard.

**Comment by xiaoyu-tamu** [comment]
> hey, @xiaoyu-tamu that's native input return, I don't think it is a good idea to manipulate that. same goes to select option
> 
> ```
> <select>
>   <option value={2}>2</option>
> </select>
> ```
> 
> You would think select 2 will give 2? not really html select will return string which is "2". To be honest, I would like to follow HTML standard.

My suggestion was allow intercept form values before handled by validate function. please read **Describe the solution you'd like** not **Describe alternatives you've considered**

**Comment by bluebill1049** [comment]
Dude isn’t that the same thing? U probably would want 2 to become a number but it’s a string, and input default value was meant to be empty string, and I state clearly I don’t think it’s a good idea l.

**Comment by bluebill1049** [comment]
Sorry I read the message wrong, I thought u were angry about the reply with the bold text...

**Comment by bluebill1049** [comment]
Hmmm I still don’t think it’s a good idea to intercept return from native input or any inputs and this will introduce an extra api for this lib as well (I still want the lib to be simple) also why u need your input to return undefined?

**Comment by bluebill1049** [comment]
I am not expert on Yup, but is there any other way to handle empty string with ur match regex?

**Comment by xiaoyu-tamu** [comment]
Ok. understand. I can just use a custom validate function instead of the build in one.

**Comment by bluebill1049** [comment]
cool sorry about that @xiaoyu-tamu 😔
