### ISSUE TITLE
v7: dirtyFields not updating on first input change

### ISSUE THREAD

**Issue by mustafahlvc** [react-hook-form/react-hook-form#4620]
**Describe the bug**

I am trying to migrate v6 to v7, when using controlled fields dirtyFields do not updating on first input change.

**To Reproduce**
Just start type one character into MUI Textfield.
Watch the changes on dirtyFields.
Second type will be effect dirtyFields.

**Codesandbox link (Required)**
I have just added dirtyFileds code to show changes.
https://codesandbox.io/s/react-hook-form-v7-controller-forked-1vckf?file=/src/index.js:1322-1327

**Expected behavior**
dirtyFields must be updated on first change.

Best regards.

**Comment by bluebill1049** [comment]
please provide a reasonable codesandbox for the issue reproduction instead of just cloning my example which has everything in there. for MUI you will probably have to use `useController` or call register before `render`

```
const { ref, ...rest } = register('test');

<Input inputRef={props.ref} {...rest} />
```

**Comment by mikhail-nikolaev** [comment]
I have the same issue. After the first input isDirty = true, but dirtyFields is empty. Both were read from formState to subscribe to changes.

**Comment by mustafahlvc** [comment]
Hi, 

I have simplified the issue at https://codesandbox.io/s/react-hook-form-v7-controller-issue-mjye7?file=/src/index.js

The issue is not related with ui library. I have also created **simple toggle button with controller**, it behaves same.

I don't want to use MUI TextField with useController because i don't want to write another component on top of mui components. It wasn't a necessity with v6.

Thanks for this great library btw

**Comment by bluebill1049** [comment]
Thanks for the updated CSB, can you share some steps @mustafahlvc?

**Comment by bluebill1049** [comment]
oh wait, this is duplicated of https://github.com/react-hook-form/react-hook-form/issues/4597 i will release the patch now.

**Comment by mustafahlvc** [comment]
I have updated the version number but the issue is not resolved.

I have added some notes for the steps checkout at : https://codesandbox.io/s/react-hook-form-v7-controller-issue-mjye7?file=/src/index.js

when isDirty is false dirtyFields must be empty. 

_I ve also tested on my local, considering if the package is not updated._

**Comment by srcn** [comment]
I can also confirm that the issue still exists.

**Comment by bluebill1049** [comment]
oh thanks guys, i will investigate into this.

**Comment by mrsimply** [comment]
I'm experiencing the same, I just want to verify that it is okay not to completely deconstruct the useForm return params, as I am using a custom Input component as an abstraction. 

```tsx
  const { handleSubmit, reset, watch, ...formProps } = useForm<Customer>({
    defaultValues,
    resolver: Validation.resolver(validationSchema),
  });
  const { isDirty } = useFormState({ control: formProps.control });

  return (
    <Input
      {...formProps}
      name={'companyName'}
      preset={'name'}
      label={t('companyName')}
      focused
    />
  );
```

This should be working, right? `isDirty` is always one keystroke behind in comparison to my `<Input/>`.

Thanks for your feedback.

**Comment by dbousamra** [comment]
I am also experiencing this issue still.

**Comment by bluebill1049** [comment]
can you supply a codesandbox @dbousamra to reproduce?

**Comment by dbousamra** [comment]
Yeah. I'll do it tomorrow, as it's late here.
