### ISSUE TITLE
isSubmitted does not work as expected

### ISSUE THREAD

**Issue by 913-Filp-Teodor** [react-hook-form/react-hook-form#4621]
**Describe the bug**
After you submit a form, if the form was valid and you reset the form using the `reset()` the `isSubmitted` flag is reset to `false` as expected until the first rerender after which its value is set back to `true`.

**To Reproduce**
1. enter this [sandbox](https://codesandbox.io/s/react-hook-form-reset-issubmitted-state-after-form-submitted-forked-smzy9?file=/src/index.js)
2. Fill in the form
3. Press submit
4. Check the console
5. You may try to refill the form, click submit while paying attention to the console

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

**Expected behavior**
The `isSubmitted` flag should remain false until the next submit

**Screenshots**
before submitting
![image](https://user-images.githubusercontent.com/30023610/113569542-5dfbd280-961b-11eb-93cc-a44ce381f7b8.png)
after first submit
![image](https://user-images.githubusercontent.com/30023610/113569574-69e79480-961b-11eb-97d6-9b6e0913117e.png)
after second submit
![image](https://user-images.githubusercontent.com/30023610/113569600-71a73900-961b-11eb-9c8c-fb494158e5a3.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Google Chrome

**Comment by bluebill1049** [comment]
```
useEffect(() => {
    console.log(formState.isSubmitted);
}, [formState]);
```

<img width="969" alt="Screen Shot 2021-04-05 at 9 38 13 pm" src="https://user-images.githubusercontent.com/10513364/113570213-3aef1400-9657-11eb-8af3-489b68ebad23.png">

**Comment by 913-Filp-Teodor** [comment]
same behaviour is still present

**Comment by bluebill1049** [comment]
- `const { formState, formState: {isSubmitted} } = useForm();` // subscribe to the form isSubmitted by deconstructor 
- `useEffect` with dep as `formState` to trigger the useEffect

**Comment by 913-Filp-Teodor** [comment]
with the applied suggestion nothing seems to have changed. Can you look at the sandbox and make it work as it should? @bluebill1049

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-reset-issubmitted-state-after-form-submitted-forked-up3lm?file=/src/index.js

**Comment by 913-Filp-Teodor** [comment]
but I still want to be able to reset my form when the user clicks the submit and the form is valid

**Comment by 913-Filp-Teodor** [comment]
@bluebill1049

**Comment by bluebill1049** [comment]
> @bluebill1049 the problem is not solved if I still want to be able to reset my form.. I still need some help. Uncomment the reset after clicking the submit button, and submit the form twice. At first the flag resets normally, but after the second submit if you check the console something weird is going on. 2 console logs are called, one with isSubmitted false and right after it one with true again, which should not happen

update your codesandbox and i will take a look when i am "FREE".

**Comment by 913-Filp-Teodor** [comment]
https://codesandbox.io/s/react-hook-form-reset-issubmitted-state-after-form-submitted-forked-bubji?file=/src/index.js this is the updated sandbox. Check the console. As far as I am interested once the form is resetted the isSubmitted should be set to false until the next submit is done and that does not happen

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-reset-issubmitted-state-after-form-submitted-forked-79gow?file=/src/index.js

read the doc:
<img width="1155" alt="Screen Shot 2021-04-14 at 8 16 17 pm" src="https://user-images.githubusercontent.com/10513364/114694820-47adef00-9d5e-11eb-8732-ba60660cac36.png">

**Comment by 913-Filp-Teodor** [comment]
The idea is that I want to show an error only if the user tried to submit the form or he/she touched the input. This https://codesandbox.io/s/react-hook-form-reset-issubmitted-state-after-form-submitted-forked-bubji?file=/src/index.js works only until the first submit, after you submit, if you touch the first input you can see that I do a global trigger onBlur, and the error message is also displayed for the second input even though that should not happen since it was not touched, nor was the form resubmitted
