### ISSUE TITLE
[useController] option to unregister automatically

### ISSUE THREAD

**Issue by orenklein** [react-hook-form/react-hook-form#4622]
**Description & Context**
As it been discussed in https://github.com/react-hook-form/react-hook-form/discussions/3714#discussion-73652, unregister is not being called automatically anymore.

**Current Solution**
In one controller:

      const ControlledInput = React.memo(({ name, rules, ...props }) => {
        const { unregister } = useFormContext();
        const {
          field: fieldProps,
          fieldState: { invalid, isTouched, isDirty, error },
        } = useController({
          name,
          rules,
          defaultValue: '',
        });
      
        useEffect(() => {
          return () => unregister(name);
        }, [unregister, name]);
      
        return (
          <div>
            <label>
              {name}
            </label>
            <input type="text" {...props} {...fieldProps} />
            <span>{error?.message}</span>
          </div>
        );
      });

Global useControllerUnregister:

      const useControllerUnregister = (options: UseControllerProps)=>{
        const { unregister } = useFormContext();
        useEffect(() => {
          return () => unregister(options.name);
        }, [unregister, options.name]);
        return useController(options)
      }

**Suggested Solution Steps**
1. Add option property called `shouldUnregister` to useController.
2. Add unregister method to any control object.
3. Call unregister in useController useEffect cleanup `shouldUnregister && unregister(name);` (https://github.com/react-hook-form/react-hook-form/blob/master/src/useController.ts#L64)

**Additional context**
1. It is probably the same with useArrayField

**Additional Suggestions**
1. Mention in the migration guide from v6 to v7 that unregister is not occurring automatically anymore.

**Comment by bluebill1049** [comment]
not a bug. vote here: https://github.com/react-hook-form/react-hook-form/issues/4355
