### ISSUE TITLE
v7: `{valueAsNumber: true}` inconsistent

### ISSUE THREAD

**Issue by mikestopcontinues** [react-hook-form/react-hook-form#4626]
**Describe the bug**

Hi again! (Sorry for all the issues this week!)

There seem to be multiple things going on:

1. `useController({rules: {valueAsNumber: true}})` doesn't work. (It works with `form.register` though.)
2. `useForm({defaultValues: {field: 0}}` doesn't get used on `valueAsNumber` fields.
3. With `useController()` valueAsNumber fields, you have to force a value, or you get a react controlled/uncontrolled warning.

**Codesandbox link (Required)**

https://codesandbox.io/s/valueasnumber-bugs-ok2oz?file=/src/index.js

To see issues

-  3, change the value of the second slider. You'll get the error.
- To see issue 2, just look at the default values on all of the sliders, compared to the `defaultValues`.
- To see issue 1, change the values of all three sliders, then press `Submit` and look at the console.

**Expected behavior**

- `defaultValues` get used on `valueAsNumber` fields
- `useController({rules: {valueAsNumber: true}})` handles values exactly as `form.register` does.

**Comment by Delave-las-Kure** [comment]
I see the same behavior for `setValueAs`.

**Comment by bluebill1049** [comment]
> useController({rules: {valueAsNumber: true}}) doesn't work. (It works with form.register though.) 

we don't support for `controller` or `useController`, i will double check type and omit if needs to be.

**Comment by bluebill1049** [comment]
<img width="595" alt="Screen Shot 2021-04-06 at 8 25 38 am" src="https://user-images.githubusercontent.com/10513364/113634180-abc31a00-96b1-11eb-8e8f-860e18c0b895.png">

it's already been omitted.

**Comment by bluebill1049** [comment]
it's working for `register`: https://codesandbox.io/s/valueasnumber-bugs-forked-wz5lf?file=/src/index.js

you didn't provide `defaultValues`

<img width="1372" alt="Screen Shot 2021-04-06 at 8 29 12 am" src="https://user-images.githubusercontent.com/10513364/113634484-2be97f80-96b2-11eb-94d9-c3a6f4cdc4a5.png">

**Comment by bluebill1049** [comment]
The reason `valueAs` is not been a feature for controlled component, because you can already convert to anything inside your inner controlled component.

**Comment by mikestopcontinues** [comment]
Ah, thanks. A few thoughts:

1. My mistake with the `defaultValues`. Yikes!
2. I think it makes more sense to keep register and useController as aligned as possible, for developer experience. Why have users reimplement `getControllerValue` logic for no reason?
3. The performance of value-related rules is better than wrapping onChange/onBlur. 
3. The docs for useController indicate the `rules` param is the same as for register. Additionally, the type on useController `rules` doesn't actually block any of the value-related props. Screenshot below of TS with no errors...

<img width="636" alt="Screen Shot 2021-04-06 at 10 46 20 AM" src="https://user-images.githubusercontent.com/150434/113692315-0a2cd000-9693-11eb-9cbc-dd90ad408532.png">

Use case:

My primary issue here is that I'm using a custom Field component (that gives a label, hover tip, shows errors, changes classNames, etc). Some inputs wrapped by Field are third-party (Slate, color picker, etc), but some are vanilla inputs. It makes the most sense for me to use `useController` for all of them. It limits the props I have to support, and I can avoid doing anything wonky to pass the `form.register().ref` through. (No renames or anything.) 

I'm actually surprised the code for useController and register diverges so much. I expected useController to only add the extra outputs (fieldState, formState) for convenience. 

Anyway, I'm interested to hear what you think.

**Comment by bluebill1049** [comment]
Thanks for your feedback. I will put that into consideration.

**Comment by joaopaulobdac** [comment]
Hi!
I found this issue because I wanted to use `valueAsNumber` with the `Controller` component. Is this being planned, and if so, should we open a new issue?

**Comment by joaopaulobdac** [comment]
I've been using this workaround:

```tsx
const valueAsNumber =
  (onChange: ControllerRenderProps['onChange']): React.ChangeEventHandler<HTMLInputElement> =>
    ({ currentTarget }) => onChange(currentTarget.valueAsNumber)

<Controller
  name='threshold'
  control={control}
  render={({ field }) => (
    <AutoWidthWrapper>
      <input type='number' {...field} onChange={valueAsNumber(field.onChange)} />
    </AutoWidthWrapper>
  )}
/>
```
