### ISSUE TITLE
Validation with params {required: true, valueAsNumber: true} doesn't work for '0' value

### ISSUE THREAD

**Issue by gromaco** [react-hook-form/react-hook-form#4627]
**Describe the bug**
Validation for required doesn't work properly when `valueAsNumber: true` and the input value is `0`.

**To Reproduce**
codesanbox with example 

1. Open codesandbox
2. Type `0` in input
2. Click on 'Send' button
3. Check console
4. See error object with error of type `required`

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-validation-required-forked-z4mrl?file=/src/App.jsx.

**Expected behavior**
There should be an error of type `min`.

**Comment by bluebill1049** [comment]
please use `validate` function instead, required only check for the empty string.

**Comment by Maxime50** [comment]
I think you should put the input type to number so the browser won't allow any string values on it

**Comment by gromaco** [comment]
> please use `validate` function instead, required only check for the empty string.

Maybe I described it badly. But the thing is that required check considers value as an empty string when it is '0'. So the value is there and `required` validation shouldn't generate an error. In v6 '0' was handled properly.
From what I see after quick debug is that in `handleChange` `getFieldValue` is called
`const inputValue = inputType ? getFieldValue(field) : value;`
and it calls

**Comment by bluebill1049** [comment]
I prefer to follow the HTML standard: https://codesandbox.io/s/nervous-almeida-5ucwi?file=/src/App.js

<img width="1124" alt="Screen Shot 2021-04-06 at 7 11 15 pm" src="https://user-images.githubusercontent.com/10513364/113687606-de016580-970b-11eb-8f6e-6ea3166bed49.png">

doc will getting updated for v7.

**Comment by gromaco** [comment]
> I prefer to follow the HTML standard: https://codesandbox.io/s/nervous-almeida-5ucwi?file=/src/App.js
> 
> <img alt="Screen Shot 2021-04-06 at 7 11 15 pm" width="1124" src="https://user-images.githubusercontent.com/10513364/113687606-de016580-970b-11eb-8f6e-6ea3166bed49.png">
> 
> doc will getting updated for v7.
@bluebill1049 the main problem is not when it's invoked. The main problem is to properly handle `0` value. In provided by you example everything works as expected  - `0` doesn't cause 'required' error.
But in codesandbox provided in the description(https://codesandbox.io/s/react-hook-form-validation-required-forked-z4mrl?file=/src/App.jsx) it triggers 'required' error even though the value is `0`:
