### ISSUE TITLE
v7.0.1 dirtyFields not truely updated with Custom Controller Component

### ISSUE THREAD

**Issue by mustafahlvc** [react-hook-form/react-hook-form#4628]
**Describe the bug**
dirtyFields do not updated when Controller component on first change.
I ve tested with material-ui's Textfield and created a basic toggle button with Controller component. Both of them behaves same.
Clearly the issue is not related with ui library but Controller component.

**Codesandbox link (Required)**
I have added some notes for the steps checkout at : https://codesandbox.io/s/react-hook-form-v7-controller-issue-mjye7?file=/src/index.js

**Expected behavior**
when isDirty is false dirtyFields must be empty.
I m using dirtyFields to disable submit button with v6.

**Comment by bluebill1049** [comment]
Thanks a lot @mustafahlvc.
