### ISSUE TITLE
Allow users to specify the `ref` prop for `register`

### ISSUE THREAD

**Issue by ricokahler** [react-hook-form/react-hook-form#4629]
**Is your feature request related to a problem? Please describe.**

Congrats on v7! I haven't been watching the pre-releases but all of the changes make sense. There is just one piece that makes the API less appealing than v6 and I would like to propose a solution.

My issue is with the new `register` API. All of our input components are wrapped in divs so their `ref` property refers to that `div` vs the nested `input` component. The migration guide gives [an example of how to work around this](https://react-hook-form.com/migrate-v6-to-v7/#main:~:text=Missing%20ref) however that example isn't as appealing when you have a lot of inline register calls (therefore requiring multiple declarations).

**Describe the solution you'd like**

I think it makes sense to create an option in the second argument of `register` called `refProp`. By default that could be just `ref` but for those of us using components libs like [material-ui](https://material-ui.com/api/text-field/#textfield-api), it would be great to change this to `inputRef`.

```tsx
<InputField {...register('foo', { refProp: 'inputRef' })} />
```

**Describe alternatives you've considered**

I can't think of any alternate APIs at the moment but the goal would be to keep the same inline usage as v6 but using custom ref prop names.

**Additional context**

I believe typescript would allow capturing this prop name so it can be in the return type. [Here is a demo](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgPIAczAPYgM4A8AKshAB6QgAmeyeYUoA5gHzIDeAUMj8lBDAAKUbOgBcyIgG5OAX06cYAVxAIsuPhCbB60YqQoRqteoxCsAFGAkZ1+YiwCUE9shjZsE082SzkAMg5kAG1BZFBJAF0JOBAAT18Obl5+MCUoECTebLcPCQByACM4KHyAGhCwADp+IRF0aOQQJQAbFuQ4Wli45J4-TqD3TzoGHz9A11DwzKJG7t8ZeU4EXHpNPFawZABeTW1dKAtXWuFRAtB0JTAAJQEAQXiwAAtmAE1sJQB1WLB830cZAogQowHF0ChbhsWltdqDwdgYOtNlIgA)

![image](https://user-images.githubusercontent.com/10551026/113615657-1e84b480-9622-11eb-9d92-8044688bdbdc.png)

Notice how `Result` reflects the string literal.

I would be willing to work on a PR for this if you are accepting. Thank you!

**Comment by yudielcurbelo** [comment]
I’m on the same boat using Material UI. Started to wrap everything inside a Controller by don’t know if is going to be a good decision.

**Comment by bluebill1049** [comment]
This is an interesting one, but tricky at the same time I can see it easily gets blow off the API, users will request for onChange, onBlur, ref, name, all to be able to rename. Sometimes, I wish all components can follow the standard on export the ref as `ref`, but unfortunately, `ref` was never getting enough attention until people start to care about focus management.

**Comment by yudielcurbelo** [comment]
In my component, I went from 

````
 <TextField
        inputRef={register}
        name="name"
        label="Name"
        margin="dense"
        defaultValue={formValues.name}
        fullWidth
        required
        error={!!errors.name}
        helperText={errors.name?.message}
      />
````
to this

````
<Controller
        control={control}
        name="name"
        defaultValue={formValues.name}
        render={({ field }) => (
          <TextField
            {...field}
            label="Name"
            margin="dense"
            fullWidth
            required
            error={!!errors.name}
            helperText={errors.name?.message}
          />
        )}
      />
```

**Comment by nghiepit** [comment]
I care about this issue.

**Comment by pepsighan** [comment]
```js
function useMaterialForm() {
  const { register, ...rest } = useForm();

  return {
    register: (...args) => {
      const { ref, ...restRegister } = register(...args);
      return { inputRef, ...restRegister };
    },
    ...rest,
  };
}
```

You can use something like this to rename the ref for the Material Forms. Its just a smaller wrapper.

**Comment by bluebill1049** [comment]
> ```js
> function useMaterialForm() {
>   const { register, ...rest } = useForm();
> 
>   return {
>     register: (...args) => {
>       const { ref, ...restRegister } = register(...args);
>       return { inputRef: ref, ...restRegister };
>     },
>     ...rest,
>   };
> }
> ```
> 
> You can use something like this to rename the ref for the Material Forms. Its just a smaller wrapper.

oh wow, this is smart.

**Comment by haydencleary** [comment]
Same issue as OP, all of my inputs are custom and wrapped in `div` tags. In it's current state I can't justify a migration to V7, there would be too much excess code and we would lose the benefit of the streamlined API V6 offers.

**Comment by dmbarry86** [comment]
Same issue here when trying to upgrade our tools to v7 today. We are using mui which requires inputRef. The workaround from @pepsighan seems the best proposal so far.

**Comment by marr** [comment]
> ```js
> function useMaterialForm() {
>   const { register, ...rest } = useForm();
> 
>   return {
>     register: (...args) => {
>       const { ref, ...restRegister } = register(...args);
>       return { inputRef: ref, ...restRegister };
>     },
>     ...rest,
>   };
> }
> ```

Works for me! One improvement would be to accept `options` in the constructor. So:
```
function useMaterialForm(options) {
  const { register, ...rest } = useForm(options);

  return {
    register: (...args) => {
      const { ref, ...restRegister } = register(...args);
      return { inputRef: ref, ...restRegister };
    },
    ...rest,
  };
}
```

**Comment by yudielcurbelo** [comment]
WIll there be any gain or loss between using something like this wrapper or just using Controller?

**Comment by bluebill1049** [comment]
@yudielcurbelo `Controller` is really a wrapper with `register` from `useForm`. I think it's more of a syntax difference.

**Comment by yudielcurbelo** [comment]
> @yudielcurbelo `Controller` is really a wrapper with `register` from `useForm`. I think it's more of a syntax difference.

Thank you for your quick clarification. I just finish the migrations and everything is working as expected. Your library is awesome.

**Comment by bluebill1049** [comment]
Thanks, @yudielcurbelo.

**Comment by sepehr500** [comment]
As a heads up. BluprintJS does the same thing as Material with `inputRef` and I'm having the same problem other are having. I have forms that use some BlueprintJS components and some components that use normal `ref` and the `register` change makes things complex. Especially when using Typescript and trying to make the types work.

**Comment by ricokahler** [comment]
> As a heads up. BluprintJS does the same thing as Material with inputRef and I'm having the same problem other are having. I have forms that use some BlueprintJS components and some components that use normal ref and the register change makes things complex. Especially when using Typescript and trying to make the types work.

@sepehr500 I'm in the same boat with `ref` vs `inputRef` in the same file. That's why I'd want it to be configurable without a wrapper but to @bluebill1049's point, I could see how this could blow up the API.

wondering if you have any other ideas

**Comment by sepehr500** [comment]
Crazy idea, but maybe register could take some kind of middleware function that takes ref onChange onBlur etc. and allows you to modify what is returned?
`register('name', {middleware: ({ref, ...rest})=> ({ref, ...rest})})`

**Comment by orhels** [comment]
One possible workaround is to create a function that does the destructuring/reassignment:
```
function asInputRef({ ref, ...rest }: UseFormRegisterReturn) {
    return {
        inputRef: ref,
        ...rest,
    };
}
```
Then use it like this with Material-UI TextField:
```
<TextField {...asInputRef(register('name'))}/>
```

**Comment by orhels** [comment]
Or if you don't need to use the `ref` prop on the Material-UI `TextField`, create a simple wrapper component:
```typescript
import { TextField as MuiTextField, TextFieldProps } from '@material-ui/core';

const TextField: React.FunctionComponent<TextFieldProps> = ({ ref, ...rest }) => {
    return <MuiTextField inputRef={ref} {...rest} />;
};
```

Then change the import path and use it as a Material-UI `TextField`
```typescript
import { TextField } from '../HookFormTextField/TextField';

<TextField {...register('name')}/>
```

**Comment by bluebill1049** [comment]
here is another approach:

```tsx
const firstName = register('firstName')
const lastName = register('firstName')

<Input {...firstName} onTextChange={firstName.onChange} />
<Input {...lastName} inputRef={lastName.ref} />
```

**Comment by bluebill1049** [comment]
https://twitter.com/i/timeline

**Comment by lucasmfredmark** [comment]
I'm also hit by this issue. It does limit the simplicity and flexibility of `register` since you cannot just spread the props onto the input.

As far as I can read from the RFC proposal the intent was to improve type safety of `register` by passing `name` as the first argument. However, it does not mention the rationale behind changing `register` to return an object instead of just the ref?

Perhaps you can shed some light on this, @bluebill1049?

**Comment by Moshyfawn** [comment]
@lucasmfredmark There're a couple of points @bluebill1049 goes over related to the `register` API change [in one of his RHF v7 preview videos at around 2:33](https://youtu.be/ZBfBiwyR2HY?t=152) you might wanna take a look at

**Comment by cvburgess** [comment]
@bluebill1049 can you provide any context around the decision to "pause" this one?

**Comment by ifeltsweet** [comment]
material-ui v5 is dropping `inputRef` for `ref` (https://github.com/mui-org/material-ui/pull/23174)

**Comment by bluebill1049** [comment]
oh wow! @ifeltsweet that's awesome!
