### ISSUE TITLE
getValues does not return default values on field array

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4634]
**Describe the bug**
The original V7 RFC stated that default values would be returned before the first render only. However, I thought we agreed that the preferred behavior was to perform a shallow merge of the `formValues` with the `defaultValues` when using operations like `watch` and `getValues`. It seems that in a code sandbox the default values are being returned after the first render, but not for field arrays. I believe this is a bug as it seems inconsistent that only field array values are omitted. Plus I don't think this is how it worked in earlier versions of V7. 

**To Reproduce**

1. Go to the sandbox
2. Click on log values
3. Noticed that while the regular input default value is returned, the field array shows 0 elements. If it was truly being omitted, shouldn't it not appear as a key at all rather than an empty array? 

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-6ogy1?file=/src/index.js

**Expected behavior**
I thought after our discussions in the RFC, any returned of form values would include a shallow merge of default values. At the least, I would hope this could be true for `getValues`. The docs seems to suggest otherwise though which contradicts the current behavior of the library.

"It will return defaultValues from useForm before the initial render."
https://react-hook-form.com/api/useform/getvalues

"default value will only get returned in the first invoke before render, the subsequence invocation will always return what's in the inputs."
https://react-hook-form.com/api/useform/watch

**Screenshots**
![Screenshot from 2021-04-05 17-51-21](https://user-images.githubusercontent.com/36898266/113643604-8d203d00-9637-11eb-8794-5a2a75d90a13.png)

Note I would be happy to fix the docs if they are incorrect, but I honestly don't know what's the intended behavior vs bugs.

**Comment by aecorredor** [comment]
I can confirm the exact same thing is happening on our end. We set some default `uuid` on each field in the array (we start with two so we have two IDs). Then, as soon as we make a change (like appending, removing, or changing a field), the IDs for the initial two items disappear. I'm assuming this happens because they do not get set in any input directly. It still feels like a bug, since I expect my initial values to be there if they haven't changed.

**Comment by bluebill1049** [comment]
> I can confirm the exact same thing is happening on our end. We set some default `uuid` on each field in the array (we start with two so we have two IDs). Then, as soon as we make a change (like appending, removing, or changing the value of one of the fields), the IDs for the initial two items disappear. I'm assuming this happens because they do not get set in any input directly. It still feels like a bug, since I expect my initial values to be there if they haven't changed.

can you share with an example?

**Comment by aecorredor** [comment]
@bluebill1049 here's a codesandbox example: https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-rht5z?fontsize=14&hidenavigation=1&theme=dark

**Comment by bluebill1049** [comment]
> @bluebill1049 here's a codesandbox example: https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-rht5z?fontsize=14&hidenavigation=1&theme=dark
> 
> If you append an item and log, you'll see the new item does have a `localId`, but the initial ones do not.

I would recommend using input hidden for now. I think it's different case for the issue above.

**Comment by bluebill1049** [comment]
@wdfinch this is correct behavior for shallow merge, we don't do deep merge with `defaultValues`.

**Comment by wdfinch** [comment]
I see. So I guess the issue then becomes `useFieldArray`. In the sandbox, I call `useFieldArray`, but I haven't connected or registered any inputs. Therefore, I would expect the get my default values back as no actual inputs have been mounted to replace the default values.

I guess where this goes for me is aside from having access to the default values of the field array, I want to be able to run append, remove, etc. on a field array without having to mount every element. The reason is I have a massive field array that really slows down performance because I need to mount every input and there are a lot of them for some users. Therefore, I display a list of all elements in a list and the user can remove, append, etc from the list without me having to mount every element. Otherwise, I always need to keep my field array's mounted to do any operation on them.

The solution here would probably lead back to `useFieldArray` accepting default values and storing them as its field array values without required that every input be mounted. We've talked about this before and you said you didn't want to do this, so I guess my only option is to just always keep my field array elements mounted when working with them in any capacity.

**Comment by bluebill1049** [comment]
@wdfinch if you just need to shuffle and re-arrange data (not involve with inputs), I guess maybe it's easier to just do treat it as a piece of data and manipulate them.

**Comment by bluebill1049** [comment]
or use `setValue` to let `useFieldArray` know you want to store those data at `useEffect`.

**Comment by wdfinch** [comment]
You're right `setValue` could be used for everything provided we continue to allow it to change field array values that aren't mounted. I guess I like using the field array methods cause it's less work (easier to call the field array `move` method than use `setValue`), but this isn't a big deal.

I still would have those performance issues when it does come time to mount the entire massive field array, but I guess there's not much that can be done about this since I need to mount the whole thing at once. 

Thanks for the help! Now regarding the docs, I think they are incorrect regarding the behavior. I can open a PR for those this week along with more typo fixes if you want to wait that long. Otherwise, we should probably change it so people don't get confused about how default values work.
