### ISSUE TITLE
Type error in utils.d.ts

### ISSUE THREAD

**Issue by lisiver** [react-hook-form/react-hook-form#4638]
**Describe the bug**

**To Reproduce**

1. Go to /dist/types/utils.d.ts
2. Click on 
3. Scroll down to 24 lines
![image](https://user-images.githubusercontent.com/46680792/113662770-b696a280-96e3-11eb-8563-a2432726bb54.png)

**Codesandbox link (Required)**
https://codesandbox.io/s/vigorous-tereshkova-xb9p9
Include a codesandbox will help us to investigate the issue quicker.

V7

- [JS](https://codesandbox.io/s/elated-dubinsky-vol10) Template
- [TS](https://codesandbox.io/s/frosty-wave-f1pco) Template

V6

- [useForm](https://codesandbox.io/s/react-hook-form-useform-template-lsm61) Template
- [useFieldArray](https://codesandbox.io/s/react-hook-form-usefieldarray-template-q0jek) Template
- [Controller](https://codesandbox.io/s/react-hook-form-controller-template-yu0z5) Template

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wdfinch** [comment]
Please attach a link to the sandbox.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by lisiver** [comment]
https://codesandbox.io/s/vigorous-tereshkova-xb9p9

**Comment by lisiver** [comment]
> Please attach a link to the sandbox.

sry I did it

**Comment by bluebill1049** [comment]
looks fine in codesandbox, what's the TS version you are on?

**Comment by TheoLeao** [comment]
Hello, I have exactly the same error with TypeScript version 3.8.0 and react-hook-form@7.0.2

**Comment by bluebill1049** [comment]
@TheoLeao we need 4.1 above for type check against input names.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/migrate-v6-to-v7

<img width="1102" alt="Screen Shot 2021-04-06 at 8 01 40 pm" src="https://user-images.githubusercontent.com/10513364/113694301-e8732d80-9712-11eb-974d-51129c7f6c73.png">

**Comment by TheoLeao** [comment]
> @TheoLeao we need 4.1 above for type check against input names.

Thanks, it works !

**Comment by lisiver** [comment]
> looks fine in codesandbox, what's the TS version you are on?

I using there deps

"typescript": "3.9.9"
"@types/node": "14.14.37"
"@types/react": "17.0.3"

**Comment by lisiver** [comment]
> https://react-hook-form.com/migrate-v6-to-v7
> 
> <img alt="Screen Shot 2021-04-06 at 8 01 40 pm" width="1102" src="https://user-images.githubusercontent.com/10513364/113694301-e8732d80-9712-11eb-974d-51129c7f6c73.png">

thx bro
