### ISSUE TITLE
Website api url 404

### ISSUE THREAD

**Issue by eldiegod** [react-hook-form/react-hook-form#4642]
On the navbar clicking api redirects to https://react-hook-form.com/vundefined/api which shows a 404 error.

Happened on Firefox, on Chrome it redirected normally to https://react-hook-form.com/api without error, not sure why.
Everything else seems to work normally.

I guess there is also a chance this only happens to me 🤷‍♂

**Comment by bluebill1049** [comment]
it's a cache with session storage, open the site in a new tab should solve the issue.

**Comment by eldiegod** [comment]
Worked 👍
