### ISSUE TITLE
V-7.03 React-Select onChange not working as expected inside of Controller 

### ISSUE THREAD

**Issue by nate456789** [react-hook-form/react-hook-form#4648]
When using React-Select and requiring it to have a value, using the onChange event prevents react-hook from verifying that it now has a selected value. This puts an error in the Errors list for the react-select control even though a value is now selected.
If you try my code example as is you can see that when the control does have a value the errors are cleared out. But if you uncomment the onChange on line 50 it will now stop clearing the error list when a value is selected.

What is the correct way to utilize the onchange event for React-Select in a Controller? 
I use this event to set a useState variable and to also update Little State Machine.
Thanks

[Code Example](https://codesandbox.io/s/silly-fire-24uyj?file=/src/App.js)

**Comment by davidroeca** [comment]
Try updating your `onChange` to:

```tsx
onChange={(x)=>{
  console.log('Selection =',x)
  field.onChange(x)
}}
```

**Comment by nate456789** [comment]
@davidroeca that worked. Thank you very much. 
Is there documentation that would have helped with this?
Thanks again.

**Comment by davidroeca** [comment]
Check out: https://react-hook-form.com/api/usecontroller/controller

Basically, the spread of `{...field}` has an `onChange` prop that gets overridden by the other `onChange` set on the component

**Comment by bluebill1049** [comment]
thank you @davidroeca .
