### ISSUE TITLE
TS types errors not exported

### ISSUE THREAD

**Issue by Morbden** [react-hook-form/react-hook-form#4649]
```ts
const { errors } = useForm()
```

the `errors` object not exported in types

version used [7.0.3](https://www.npmjs.com/package/react-hook-form/v/7.0.3)

**Comment by jorisre** [comment]
Hi @Morbden 

I'm not sure to understand what you expect but with the V7, `errors` moved into `formState`

```tsx
const { formState: { errors } } = useForm()
```

[The migration guide V6 to V7](https://react-hook-form.com/migrate-v6-to-v7)

Does it help you ?

**Comment by matamatanot** [comment]
@Morbden 
https://react-hook-form.com/migrate-v6-to-v7/

> errors object has been moved into formState object. This will info hook form that errors object is been subscribed.
> 
> You can use this codemod library to speed up the process: https://github.com/react-hook-form/codemod by running the following command:
> 
> npx @hookform/codemod v7/move-errors-to-formState

**Comment by bluebill1049** [comment]
errors is moved into `fomrState`, we are allowing users to subscribe to `formState` by reading via Proxy.
