### ISSUE TITLE
useFieldArray with getValues return incorrect value

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#4654]
Thank you very much for the insights!!!

Unfortunately I have to bother you again, sorry. 👻 You had suggested the solution to my initial problem of this discussion in this [comment](https://github.com/react-hook-form/react-hook-form/discussions/4565#discussioncomment-561635) as follows: 

> the problem is fields only contain the defaultValue, you may want to merge with getValues() which is current form values.

I had then defined the defaultValue as follows to fix the problem:

```defaultValue={getValues(`data.${index}.name` as const)}```

But unfortunately there is maybe a bug. When I want to remove entries of the field array via "remove" method the wrong item gets removed.

Steps to reproduce

1. open [CodeSandbox](https://codesandbox.io/s/usefieldarray-remove-bug-oeu67?file=/src/App.tsx:935-990)
2. remove the first item
3. first item is still there, instead the last item is removed

This happens in v6 as well as in v7.

_Originally posted by @knoefel in https://github.com/react-hook-form/react-hook-form/discussions/4565#discussioncomment-576393_

**Comment by martin8877** [comment]
I don't know if it is related with this issue but since 6.15.3 getValues with nested useFieldArray() is not working correctly. 6.15.2 has [bug](https://github.com/react-hook-form/react-hook-form/issues/4251) with removing. Latest working version is 6.15.1.

Steps to reproduce
1. open [CodeSandbox](https://codesandbox.io/s/pensive-cherry-wtx8w?file=/src/App.js)
2.  click three times on "+ Add"

**Comment by bluebill1049** [comment]
This issue is resolved. 

<img width="919" alt="Screen Shot 2021-04-08 at 8 37 21 am" src="https://user-images.githubusercontent.com/10513364/113943265-a4cd1080-9845-11eb-9d38-4107339e59a3.png">

@martin8877 please submit a separate issue with more details and follow the issue template.
