### ISSUE TITLE
Combination of required & valueAsNumber doesn't validate the input correctly if it is empty. (7.0.3)

### ISSUE THREAD

**Issue by Maxime50** [react-hook-form/react-hook-form#4657]
**Describe the bug**
Since the version 7.0.3, the combination of `required` and `valueAsNumber` will not validate the input even if it is empty. In others words, it will consider an empty value to be a valid `required` value.

**To Reproduce**
1. Go to the Codesandbox link
2. Write anything in the name field
3. Erase whatever inside the number field or leave it empty
4. Submit the form and look at the console log
5. The form will submit even if it is empty and required.

**Codesandbox link (Required)**
https://codesandbox.io/s/eloquent-pond-k22pm

**Expected behavior**
I am assuming the form to validate an input that is required if the value is empty or just NaN if `valueAsNumber` is also present in the rules object.

**Additional context**
1. I am really not sure because i'm a noob, but I think this issue might come from this patch: #4641.
2. I did not try with `setValueAs`
3. If you set the default value of number to "" instead of 0, then refresh the page to get a fresh mount, give the Name field anything and leave the number field empty. On the first submit you will see that the form will validate properly and give the correct error. ...but as soon as you revalidate for the second time, now the validation doesn't apply and let the empty field pass.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/commit/538b1d244d4f028e41eb5168b5aaedc4500c0dfd
