### ISSUE TITLE
Pattern Regexp is not working for email input field when passed as a string

### ISSUE THREAD

**Issue by maheshk-coditas** [react-hook-form/react-hook-form#4659]
Hi Team,

Maybe I am doing something wrong over here, I am facing an issue in the pattern for email validation. 
Below is the regex which I am using for email validation through the pattern in React Hook form 
*regex ="/^(([^<>()[\]\.,;:\s@\"]+(\.[^<>()[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i"*

I am rendering form dynamically and the pattern value is comming form the BE so it is comming in JSON string format.
Whenever I am passing the value in "{pattern}" double quotes it is not working however if the same value is passed without {pattern} double quotes so it is working fine.
1st way
`inputRef={register({
pattern: {
                                  value: new Regexp(registrationObject?.pattern),
                                  message: registrationObject.validationMessages?.pattern,
                                },
                              })}`

2nd way 
`inputRef={register({
pattern: {
                                  value: new Regexp(registrationObject?.pattern, "i"),
                                  message: registrationObject.validationMessages?.pattern,
                                },
                              })}`

3rd way

`inputRef={register({
pattern: { value: /^(([^<>()[\]\.,;:\s@\"]+(\.[^<>()[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i,
                                  message:  registrationObject.validationMessages?.pattern,
                                },
                              })}`

So it is working with only 3rd way 

please help me to resolve this

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848
