### ISSUE TITLE
Nested default values are overridden 

### ISSUE THREAD

**Issue by olaf89** [react-hook-form/react-hook-form#4667]
When default value is an object and input that is nested part of this object is registered the defaultValue is overridden

https://codesandbox.io/s/laughing-pike-3xzry?file=/src/App.tsx
```
   defaultValues = {
      obj: {
        a: "12",
        b: "22"
      }
    }
```
Form code
``` 
<form onSubmit={handleSubmit(onSubmit)}>
        <input {...register("obj.a")} placeholder="Object value" />
        <input type="submit" />
</form>
```

Submitted value

```
{ 
  obj : { 
    a: "12"
  }
}
```

  
   Expected Submitted value

```
{ 
  obj : { 
    a: "12",
    b: "22"
  }
}
```

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by bluebill1049** [comment]
This is expected behavior, we don't do deep merge against default value, consider to store value in a hidden input.

**Comment by olaf89** [comment]
Hmm, ok I see.
