### ISSUE TITLE
Form Field Registration Type Error with Circular Type (V7)

### ISSUE THREAD

**Issue by jeffdc** [react-hook-form/react-hook-form#4670]
**Describe the bug**
In V7 it is not possible to have a Type in the Form Field definitions that has an internal circular type definition. e.g., if the type of a piece of data stored in the form represents a tree structure it can not be used without a Type Error:

```Type of property 'parent' circularly references itself in mapped type '{ [K in keyof TaxonomyEntry]-?: PathImpl<K & string, TaxonomyEntry[K]>; }'.ts(2615)```

**To Reproduce**

1. Create a type that references itself (in my case it is a Taxonomy Entry from a Taxonomy tree)
2. Create a form and attempt to register a field using the type created in step 1
3. A type error occurs when trying to register the field

**Codesandbox link (Required)**
https://codesandbox.io/s/goofy-feistel-5orcs

**Expected behavior**
To be able to have a type that has a circular type definition.

**Additional Context**
In my case I am using a typeahead component in the form. I need to store the object, not just a string value, hence I need to register the field with the full type (or as a hack workaround I have to define an entirely new type that deletes the parent reference and re-type all of the functions that work with the data on the UI side).

**Comment by nucleartux** [comment]
possible duplicate https://github.com/react-hook-form/react-hook-form/issues/4055

**Comment by jeffdc** [comment]
Ugh, GH search did not return anything for the phrase 'ciricular type' 🤷‍♂️. 

Ummm, if this is going to stay this way then I am not going to be able to use this lib anymore, at least not V7. I have too much data that is like this AND I am already familiar with the`Omit` type to tweak things. I will basically have to double all of my types and change function signatures and write a lot of conversion code to go from the "Omit" type back "up" to the correct type. 

This is a real Bummer as this is a great library. This seems like a severe limitation and I really hope you reconsider.

**Comment by nucleartux** [comment]
I am not a library developer, jfyi :)

**Comment by bluebill1049** [comment]
Thanks for the helo @nucleartux, It's a design limitation in my eyes, if we want to support strictly typed form with string template literal. CC @kotarella1110
