### ISSUE TITLE
setValueAs is not working in Controller

### ISSUE THREAD

**Issue by dwdt** [react-hook-form/react-hook-form#4673]
**Describe the bug**
When using Controller, it appears that the function passed to `setValueAs` is not executed.

In the following Codesandbox example, I have one controlled input and one uncontrolled input. I pass to both `setValueAs` a function to capitalize the value that comes from the input. When I click submit, in case of the uncontrolled input, the value is capitalized (as expected), but in the case of the controlled input, the value is not capitalized (the bug).

This bug happens in versions 7.0.0 to 7.0.4.
This bug does not happen in version 7.0.0-alpha.2

**To Reproduce**

0. Open [Codesandbox](https://codesandbox.io/s/late-night-9re0n?file=/src/App.tsx)
1. Write `hello` in the input labeled `uncontrolled input`. 
2. Write `hello` in the input labeled `controlled input`. 
3. Click on Submit.
4. Open console tab and see what is printed:
```
{
    uncontrolledInput: "HELLO",
    controlledInput: "hello",
}
```

**Expected behavior**
I expect to see printed in the console:
```
{
    uncontrolledInput: "HELLO",
    controlledInput: "HELLO",
}
```

**Desktop**

- OS: Ubuntu 20.04
- Browser: Chrome 89.0.4389.114

**Comment by bluebill1049** [comment]
we don't support `valueAs` in `controller`, you are meat to do those value transform inside your controlled component.

**Comment by DylanCulfogienis** [comment]
@bluebill1049 Has your opinion changed on this by any chance? If not, I think it'd be worth updating the documentation with this gotchya. My team just ran into it and it took us some time to find this thread and arrive at the correct solution.

**Comment by bluebill1049** [comment]
> @bluebill1049 Has your opinion changed on this by any chance? If not, I think it'd be worth updating the documentation with this gotchya. My team just ran into it and it took us some time to find this thread and arrive at the correct solution.

<img width="950" alt="Screen Shot 2021-05-22 at 9 37 33 am" src="https://user-images.githubusercontent.com/10513364/119207367-574cf000-bae1-11eb-9dbe-67b469193196.png">

The missing doc on Controller is updated.
