### ISSUE TITLE
Unregister breaks state when called on untouched input with default value

### ISSUE THREAD

**Issue by micreas** [react-hook-form/react-hook-form#4674]
**Describe the bug**
When you call `unregister` on an input that has a value loaded from `defaultValues` that comes from an object inside of React's state, it removes that value from that object without React knowing about it. No re-renders occur, nothing...

**To Reproduce**

1. Go to this [sandbox](https://codesandbox.io/s/broken-butterfly-0y6ej)
2. Open the console
3. Click on 'Log state' and look at the logged value
4. Click on 'Unregister'
5. Click on 'Log state' and look at the logged value

**Codesandbox link (Required)**

V7

- [JS](https://codesandbox.io/s/broken-butterfly-0y6ej)

**Expected behavior**
Unregistering should not affect the state from which are the `defaultValues` loaded.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox Developer Edition
- Version: 88.0b8

**Additional context**
Maybe you'd like to know how I discovered this bug. I am building an app that contains dynamic forms inside modals. For example, the user selects an option from select input and it shows a different set of fields inside of the same form based on the user's choice. When the set of inputs changes, the inputs that will be unrendered call the `unregister` function, so their values don't remain in the form's state. When the user fills it and saves it, it gets saved inside of a state in a context. When the modal gets re-opened, the values are loaded from the state into the form. The problem appeared when I tried to re-open the modal multiple times. The values kept disappearing for no reason. Maybe `react-hook-form` was not built to be used like that, but it certainly should not be able to modify React's state without React knowing about it. This most likely is an issue with low-level Javascript references.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/useform/unregister

`keepDefaultValue`

**Comment by micreas** [comment]
> https://react-hook-form.com/api/useform/unregister
> 
> `keepDefaultValue`

@bluebill1049 This does not solve the problem. By using `keepDefaultValue` the value will remain both in the form's state and the external state that is used for `defaultValues`. I am intentionally calling `unregister` because I don't want these values to remain in the internal form's state BUT I do want them to remain in the state used for `defaultValues` until that state is intentionally rewritten. I am using that external state as a "save" location. 

By doing what you suggest there will remain values from inputs that are unregistered (in the internal form state) and that is not what I want. I want to keep only the values of the fields that are registered WITHOUT it affecting any external state before the user saves it. 

### **What I am trying to say...**
I am trying to point on the fact, that calling `unregister` deletes values used in `defaultValues` even outside the internal state of the hook form. Even if it is inside of an object that is a part of React's state. If that state stored a frozen object, the hook form would cause errors, because it is trying to call delete on that object that is passed to `defaultValues` and that is wrong. It should not be able to modify what is passed to it. It should probably clone that object passed to `defaultValues` instead of working directly with its reference. Because as in my case, it can modify an object inside of a React's state without React knowing about it. And that should not be happening.
