### ISSUE TITLE
register() return undefined and Controller component render wrong object

### ISSUE THREAD

**Issue by Morbden** [react-hook-form/react-hook-form#4676]
Using version 7.0.3

In the hook `useForm()` the `register()` function is returning `undefined`  value in browser, but in SSR mode its OK.
Printing in terminal
![image](https://user-images.githubusercontent.com/5295072/113921786-d6e66000-97bc-11eb-912b-3b998b1f37b2.png)

And the Controller component, in render function, receive wrong object.

Expected type
![Captura de tela 2021-04-07 160303](https://user-images.githubusercontent.com/5295072/113920144-c7661780-97ba-11eb-85d3-53cf76060d33.png)

Type received
![image](https://user-images.githubusercontent.com/5295072/113920267-efee1180-97ba-11eb-8aa4-3ff0b18d6a4d.png)

**Comment by bluebill1049** [comment]
I am confused and please follow the issue template...

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848
