### ISSUE TITLE
Can't integrate v7 with Material-UI Autocomplete-TextField

### ISSUE THREAD

**Issue by jnthnk** [react-hook-form/react-hook-form#4678]
When I try to register the TextField inside the Autocomplete component, the input can't be indexed.

V7 - [JS](https://codesandbox.io/s/fervent-poincare-lpe8w?file=/src/App.js) Example

Is weird cause if the TextField component is alone, I can make it work using the register inside the inputProps attribute. Somethins that may appear in docs.

Also the old ways of version 6 works fine, either the Autocomplete or TextField, using the ref.

Thanks.

**Comment by bluebill1049** [comment]
please use `useController` or `Controller`, for MUI inputs. 

https://react-hook-form.com/api/usecontroller
