### ISSUE TITLE
"isValid" doesn't work well on V7

### ISSUE THREAD

**Issue by Hentaro1989** [react-hook-form/react-hook-form#4679]
**Describe the bug**
When you have 2 or more custom register fields, "isValid" doesn't work well on V7. But It works on V6.

**To Reproduce**

on the Codesandbox below,

1. type a character into `field-a` or `field-b`
2. delete the character that you've typed

**Codesandbox link (Required)**
https://codesandbox.io/s/crimson-dew-k7nvx?file=/src/App.js

**Expected behavior**
`isValid` should be `true`.

**Desktop (please complete the following information):**

- OS: MacOS Catalina Version10.15.7
- Browser: chrome
- Version: Version 89.0.4389.114 (Official Build) (x86_64)

**Comment by bluebill1049** [comment]
what do you mean isValid should be true? can you give a bit more detail?

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/113974674-a7e5f200-9881-11eb-8057-4bb898ce99bf.mov

**Comment by Hentaro1989** [comment]
`isValid` should be always `true`. Because `field-a` and `field-b` are just required fields. If I changed a value from `default` to `default2`, this form is valid.

https://user-images.githubusercontent.com/18099928/113980054-0363b000-9881-11eb-8c08-e02b975d9fa3.mov

**Comment by Hentaro1989** [comment]
Thank you for the commit, Bill.

**Comment by bluebill1049** [comment]
Thanks for the report @Hentaro1989 i will try to release it tonight.

**Comment by danicaliforrnia** [comment]
I'm having the same bug using V7 with a select and a text field. If I edit one or another, isValid is false even when both have default values.
