### ISSUE TITLE
Problems with custom array & yup

### ISSUE THREAD

**Issue by tomaskallup** [react-hook-form/react-hook-form#468]
**Describe the bug**
While trying to reproduce what we have in our codebase (where `yup.array(yup.string().oneOf([...]))` doesn't seem to set `errors` object) I ran into what seems to be a different issue.
Seems like when arrays have a strict validator (example `yup.array(yup.number())`) and we try to set it to something, that doesn't validate (example  a string `'123'`) the `setValue` throws error `TypeError: error.inner is undefined`. 

Crashing in Firefox seems to be a problem of `yup` (jquense/yup#683)

**To Reproduce**
Navigate to codesandbox
In there if you try to click the first "checkbox" with text `test` - it gets set correctly and `-Checked` show up next to it.
If you try to check any other, which shouldn't pass validation, nothing happens and there is an error thrown in console.

**Codesandbox link**
[Codesandbox](https://codesandbox.io/s/react-hook-form-custom-array-field-bug-1luru)

**Expected behavior**
I expect the `errors` object to be updated when I select any checkbox other than the first one.

**Desktop (please complete the following information):**
 - Device: Thinkpad, Macbook Pro
 - OS: Linux, MacOS
 - Browser Firefox, Chrome
 - Version 3.27.0-beta.1, 3.26.5

**Comment by bluebill1049** [comment]
hey @tomaskallup any chance post this issue at yup as well? looks like the validation failed at yup.

**Comment by bluebill1049** [comment]
hmm i tested your demo and it's working.

**Comment by tomaskallup** [comment]
It seems to fail on the codepen, however if I run it localy in our project:
```
try {
yup.object().shape({ custom: yup.array().of(yup.string().oneOf(['test'])) }).validateAsync({ custom: ['test', 'test2']})
catch(e) { console.log(e) }
```
It seems to produce correct error, but inside the hook form this error is not picked up (even though `isValid` inside `formState` gets set to `false`) :confused:

**Comment by tomaskallup** [comment]
@bluebill1049 Did another check, the demo seems to work in my Chrome on linux. BUT it shows the second error, if you check one of the invalid values, the `errors` object is empty.

**Comment by tomaskallup** [comment]
So the `error.inner is undefined` seems to be Firefox only thing.

**Comment by bluebill1049** [comment]
sounds strange if it only breaks at firefox, is that the same demo?

**Comment by tomaskallup** [comment]
Yep, same demo. Tried Linus - Chrome (no error), Firefox (error) and MacOS - Chrome (no error), Firefox (error)

**Comment by bluebill1049** [comment]
you are right, this is a bug from yup. Do you want to raise it there?

`Error: Unexpected frame by generating stack.`

**Comment by tomaskallup** [comment]
Sure, that would be great.
Should I create a second issue for the second part (errors object not being populated in Chrome, possibly also in Firefox) or is that affected by this problem?

**Comment by bluebill1049** [comment]
they r the same issue right?

**Comment by tomaskallup** [comment]
I'm not sure how to check it, it's possible that in Chrome the same error happens and it just fails silently. 
Basically in Chrome the validation seems to happen (`isValid` gets set to false, but errors object remains empty). Maybe in Chrome `yup` actually throws somewhat correct error, but it's empty.
![react-hook-form-missing-errors](https://user-images.githubusercontent.com/26621166/68301903-39f03680-00a1-11ea-87ef-286f6dcb6150.gif)

**Comment by tomaskallup** [comment]
Did some quick testing, seems like this is probably a separate problem. If you take a look at this [codepen](https://codesandbox.io/s/yup-array-validation-error-2jlwn), in Firefox it throws the error, so I'll report this to `yup`, but in Chrome it gives and actual error and that is the part that doesn't seem to be picked up by `react-hook-form`

**Comment by bluebill1049** [comment]
thanks @tomaskallup i will take a closer look again

**Comment by bluebill1049** [comment]
ok that first issue, there is already a fix for it, which I haven't publish just: https://github.com/react-hook-form/react-hook-form/pull/464

so the remaining one is just firefox when it comes to yup schema validation.

**Comment by tomaskallup** [comment]
@bluebill1049 Perfect, thank you! I'll keep an eye on that PR waiting for release.

**Comment by bluebill1049** [comment]
no worries @tomaskallup thanks for report the issue and help on testing too 👍

**Comment by tomaskallup** [comment]
No problem, I quickly grew to love this project when replacing our Formik based form, mainly because the implementation was so smooth and clean. Keep up the great work and thanks for the quick response time! I'll try and help on the `yup` side so this can be closed soon.

**Comment by bluebill1049** [comment]
> I'll try and help on the `yup` side so this can be closed soon.

that would be awesome! thank you.

**Comment by bluebill1049** [comment]
hey @tomaskallup the fix is been patched, any update from `Yup`? maybe you can reference the issue in here.

**Comment by tomaskallup** [comment]
@bluebill1049 sadly no response on yup side, I'll have some free time during the weekend, so I might try and fix it myself. The yup issue is referenced up in the issue description

**Comment by bluebill1049** [comment]
thanks, @tomaskallup for the update :) I believe the first issue should be resolved by the latest patch tho :)

**Comment by bluebill1049** [comment]
I am going to close this issue for now since its a dependency problem, will re-open once I hear back from you(yup). We can keep the conversation going in here too, plus it's in the project board.
