### ISSUE TITLE
Controlled input with Material UI is leaving the input field while typing with `mode` property set

### ISSUE THREAD

**Issue by hazemalabiad** [react-hook-form/react-hook-form#4686]
**Describe the bug**
I am using `react-hook-form@7` with `Material UI` to create a simple form however, there is a weird behavior when setting the mode in `useForm({mode: ".."})` Here is my code snippet:

**To Reproduce**

1. selected the input field
2. started typing
3. after one char it leaves the input field so, I need to select it to type again.

V7
[Codesandbox](https://codesandbox.io/s/floral-tdd-j9gd0?file=/src/App.js)
**Note:** In codesandbox it's working with no issues, however, it is not working the same locally.

**Expected behavior**

**Screenshots**
![React-App-Person-1-Microsoft-Edg](https://user-images.githubusercontent.com/16942677/114005759-87f60480-9868-11eb-96b5-59ba4cc1a174.gif)

**Desktop (please complete the following information):**

- OS: [Windows 10 Version, 10.0.19042 Build 19042]
- Browser [Microsoft Edge]
- Version [89.0.774.68 (Official build) (64-bit)]

**Code**
```js
import { yupResolver } from "@hookform/resolvers/yup";
import { Button, Grid, Link, TextField, Typography } from "@material-ui/core";
import { makeStyles } from "@material-ui/core/styles";
import Alert from "@material-ui/lab/Alert";
import { Controller, useForm } from "react-hook-form";
import { _MESSAGES } from "src/constants/messages";
import * as yup from "yup";
import AuthContainer from "./AuthContainer";

// #####################   Helpers    ######################
/**
 * @param {object} error
 * @param {string} msg
 */
const renderError = (error, msg) =>
  error ? <Alert severity="error">{msg}</Alert> : "";

// ##############   Schema & Default Values   ##############
const schema = yup.object().shape({
  email: yup.string().required(),
  password: yup.string().required(),
});

const defaultValues = {
  email: "",
  password: "",
};

// ######################   Styles    ######################
const useStyles = makeStyles((theme) => ({
  form: {
    width: "100%", // Fix IE 11 issue.
    marginTop: theme.spacing(1),
  },
  submit: {
    margin: theme.spacing(3, 0, 2),
  },
}));

// #################   Main Component    ###################
const SignInPage = () => {
  const classes = useStyles();
  const {
    handleSubmit,
    formState: { errors },
    reset,
    control,
  } = useForm({
    // mode: "all",
    resolver: yupResolver(schema),
    defaultValues,
  });

  const onSubmit = (data) => {
    console.log(data);

    // Reset form fields
    reset();
  };

  console.log(errors);

  const Form = () => (
    <>
      <Typography component="h1" variant="h5">
        Sign In
      </Typography>
      <form className={classes.form} onSubmit={handleSubmit(onSubmit)}>
        <Controller
          control={control}
          name="email"
          render={({ field }) => (
            <TextField
              variant="outlined"
              margin="normal"
              fullWidth
              autoComplete="email"
              label="Email Address"
              {...field}
              error={errors.email?.message ? true : false}
            />
          )}
        />
        {renderError(errors.email?.message, _MESSAGES.required)}
        <Controller
          control={control}
          defaultValue=""
          name="password"
          render={({ field }) => (
            <TextField
              variant="outlined"
              margin="normal"
              fullWidth
              autoComplete="current-password"
              type="password"
              label="Password"
              {...field}
              error={errors.password?.message ? true : false}
            />
          )}
        />
        {renderError(errors.password?.message, _MESSAGES.required)}
        <Button
          type="submit"
          fullWidth
          variant="contained"
          color="primary"
          className={classes.submit}
        >
          Sign In
        </Button>
        <Grid container>
          <Grid item xs={12}>
            <Link href="#" variant="body2">
              Forgot password?
            </Link>
          </Grid>
          <Grid item>
            <Link href="#" variant="body2" color="secondary">
              {"Don't have an account? Sign Up"}
            </Link>
          </Grid>
        </Grid>
      </form>
    </>
  );

  return <AuthContainer Form={<Form />} />;
};

export default SignInPage;
```

**Comment by bluebill1049** [comment]
I think this issue is due to the `ref` name been `inputRef`, the focus is probably not working as well for error:

can you try the following: 

```
<Controller
    control={control}
    name="email"
    render={({ field: { ref, ...rest} }) => (
      <TextField
        margin="normal"
        fullWidth
        autoComplete="email"
        label="Email Address"
        {...rest}
        error={errors.email?.message ? true : false}
      />
    )}
  />
  ```

**Comment by hazemalabiad** [comment]
@bluebill1049 I tried it but, did not work. I think the problem is `useForm({mode: ".."})` so when the mode is set I am having this leaving the input issue when it is not set everything seems to work fine.

**Comment by jorisre** [comment]
@bluebill1049 Original issue: https://stackoverflow.com/questions/66994706/react-hook-form-is-leaving-the-input-field-while-typing-with-mode-property-set/66998418

That's strange, it's working in the codesandbox: https://codesandbox.io/s/mui-textfield-forked-1w8r6

**Comment by hazemalabiad** [comment]
I have just deployed to Netlify, the problem is occurring there.
Can you check out this [netlify-deploy](https://gatcha.netlify.app/), please?
Shall we continue here? or on Stackoveflow?

**Comment by bluebill1049** [comment]
@hazemalabiad can you share a simple github repo? i can build locally as prod build and debug the issue.

**Comment by bluebill1049** [comment]
> @bluebill1049 Original issue: https://stackoverflow.com/questions/66994706/react-hook-form-is-leaving-the-input-field-while-typing-with-mode-property-set/66998418
> 
> That's strange, it's working in the codesandbox: https://codesandbox.io/s/mui-textfield-forked-1w8r6

i only see a blank page @jorisre 
<img width="1532" alt="Screen Shot 2021-04-08 at 8 26 53 pm" src="https://user-images.githubusercontent.com/10513364/114011613-c3b0be80-98a8-11eb-8de3-c84676c5f634.png">

**Comment by jorisre** [comment]
@bluebill1049  working for me
![Screenshot 2021-04-08 at 12 28 03](https://user-images.githubusercontent.com/7545547/114011736-deae0f00-9865-11eb-9483-6329e2274c91.png)

**Comment by hazemalabiad** [comment]
@bluebill1049 for me 2

**Comment by bluebill1049** [comment]
> @bluebill1049 for me 2

can you share a github repo?

**Comment by bluebill1049** [comment]
This behaviour looks like your component is getting mount and unmounted with the first stroke.

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/114013239-abda3a00-98aa-11eb-966f-42424df349e7.mov

I quickly tried with our automation app, and it's fine.

**Comment by bluebill1049** [comment]
<img width="468" alt="Screen Shot 2021-04-08 at 8 42 19 pm" src="https://user-images.githubusercontent.com/10513364/114013486-ecd24e80-98aa-11eb-9fed-dee34b84ef6c.png">

with mode onChange as well.

**Comment by bluebill1049** [comment]
so would need to see an isolated reproducible GitHub repo before I can do any further investigation on this.

**Comment by hazemalabiad** [comment]
@bluebill1049 I am working on creating a separate repo.

**Comment by hazemalabiad** [comment]
@bluebill1049 Here is the [repo](https://github.com/hazemalabiad/react-hook-form-controller).

**Comment by bluebill1049** [comment]
thanks looking now./

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/114015310-e6dd6d00-98ac-11eb-95c6-3700904a7730.mov

I was right about the unmount. your form is getting the mount and unmount. move Form outside the main compoennt.

**Comment by bluebill1049** [comment]
answered in StackOverflow as well.
