### ISSUE TITLE
[Question / Bug] Errors object identity

### ISSUE THREAD

**Issue by nshaikhinurov** [react-hook-form/react-hook-form#469]
After some time testing the use case described [on Spectrum](https://spectrum.chat/react-hook-form/help/how-to-flash-an-error-for-a-short-timespan~3cc9db3e-cad7-4ed2-9a62-f15dd382c34e) I've found some defect which causes a bug when using with a regular `useEffect` hook.

The problem is that `useEffect` hook's dependency list checks for object identity to skip calling an effect callback and the `react-hook-form` doesn't keep the identity of `errors` prop returned from `useForm` even when no revalidation made. So it's impossible to include `errors` to dependency array of the `useEffect`.

The code to reproduce is 

**To Reproduce**
1. Go to [Sandbox](https://codesandbox.io/s/react-hook-form-conditional-fields-b8hmc)
2. Click on 'Submit' button
3. See red border flashes around a required field (expected because of validation)
4. Check the checkbox to show a conditional field
5. See red border flashes around a required field again (unexpected because no revalidation was made, just rerendered, happens because the identity of `errors` is broken)
5.1 Type smth into the required field
6. Start typing to the second input
7. See red border flashes around a required field again many times (obviously a strange behaviour, there was no revalidation made but the `errors` object changes)

**Additional context**
`getObjectId` is just a helper function which kinda shows the unique ID of any js object

So in the console you can see that the identity of a `register` method is saved but the `errors` changes even if the `type` and `message` stay the same (only `ref` is changing). 

The main question is how to get rid of the redundant error flashes and skip these calls of `useEffect` callbacks?

**Comment by tomaskallup** [comment]
I think a better approach would be to actually use `clearError` from the form itself, but after trying that it seems like when I initialy check the checkbox, the form gets revalidated and the error flashes, this happens only on the first check.

**Comment by bluebill1049** [comment]
I think there is 2 solutions in my head

1. https://github.com/kentcdodds/use-deep-compare-effect
2. do your check inside useEffect

**Comment by nshaikhinurov** [comment]
I've found another good solution. I used `formState.submitCount` as a dependency of the `useEffect` hook and it worked like a charm. Now my effect gets called only after submitting the form.

**Comment by bluebill1049** [comment]
awesome!
