### ISSUE TITLE
Can't append new item to manually registered array

### ISSUE THREAD

**Issue by nucleartux** [react-hook-form/react-hook-form#4690]
**Describe the bug**
Imagine I have array of entities where I can't edit any inputs, just append new or remove existing items.
If I understood correctly for such case I need call `register`.
But if I'm trying to `append` new items I'm getting error `Cannot read property 'disabled' of undefined`

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-sq3hq?file=/src/index.js
2. Click on Append
3. Click Submit
4. See error `Cannot read property 'disabled' of undefined`

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-sq3hq?file=/src/index.js

**Comment by bluebill1049** [comment]
we currently don't support such usage.
