### ISSUE TITLE
isSubmitSuccessful is true on rejected promises?

### ISSUE THREAD

**Issue by baba43** [react-hook-form/react-hook-form#4691]
I thought that when using this simple form, `isSubmitSuccessful` should not be set to true.

```javascript
function TestForm() {
  const {
    handleSubmit,
    formState: { isSubmitSuccessful },
  } = useForm();
  function onSubmit() {
    return Promise.reject("test");
  }
  return <form onSubmit={handleSubmit(onSubmit)}></form>;
}
```

However, it seems that errors of any kind (errors and promise rejections) are counted as successful submits.

Is this a bug, on purpose or am I thinking wrong?

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/3956 it's already under the project.
