### ISSUE TITLE
Incorrect typings for return from useFormContext

### ISSUE THREAD

**Issue by don-hover** [react-hook-form/react-hook-form#4694]
**Describe the bug**
In react-hook-form v7.0.4, typing for `useFormContext` and `getValues` is not correct/as expected.

**To Reproduce**

1. Use `useFormContext` in a component, typed like this: `useFormContext<UseFormReturn<{firstName: string}>>`
2. Use the `getValues` function from `useFormContext`. 
3. In VisualStudio Code, hover over the `getValues` function.
4. Observe that the return type is not as expected.  (See screen shots.)

**Codesandbox link (Required)**
https://codesandbox.io/s/fervent-glade-plsqi?file=/App.ts

V7

- [JS](https://codesandbox.io/s/elated-dubinsky-vol10) Template
- [TS](https://codesandbox.io/s/frosty-wave-f1pco) Template

V6

- [useForm](https://codesandbox.io/s/react-hook-form-useform-template-lsm61) Template
- [useFieldArray](https://codesandbox.io/s/react-hook-form-usefieldarray-template-q0jek) Template
- [Controller](https://codesandbox.io/s/react-hook-form-controller-template-yu0z5) Template

**Expected behavior**
Expected -
When using `useFormContext` with a provided type for the generic `FieldValues` like `useFormContext<UseFormReturn<OrderFormFields>>`, I expect the return type of `getValues` to match the `FieldValues` type.

Actual -
When using `useFormContext` with a provided type for the generic `FieldValues` like `useFormContext<UseFormReturn<OrderFormFields>>`, the return type of `getValues` is the same type as `useFormContext`; it shows a type that has properties of `getValues, setValue, register, watch`, etc.

**Screenshots**
![Screen Shot 2021-04-08 at 11 58 19 AM](https://user-images.githubusercontent.com/77687833/114058746-bcb28d80-9861-11eb-87f6-79900c1b1eb8.png)

![Screen Shot 2021-04-08 at 11 45 29 AM](https://user-images.githubusercontent.com/77687833/114058779-c2a86e80-9861-11eb-8980-3963234ade1e.png)

**Desktop (please complete the following information):**

- OS: macOs Big Sur
- Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bluebill1049** [comment]
<img width="670" alt="Screen Shot 2021-04-09 at 8 11 21 am" src="https://user-images.githubusercontent.com/10513364/114102716-2d61b480-990b-11eb-9e77-b8bd9e3bc19a.png">

```
const { control, getValues } = useForm<
  { firstName: string }
  >();

  const { firstName } = getValues();
  ```

**Comment by don-hover** [comment]
@bluebill1049 
Here is what I'm seeing when TypeScript checking is completed:
```
typescript: src/style-guide/components/Select/Select.tsx(71,16): error TS2345: Argument of type 'string' is not assignable to parameter of type '`${string}`'.
```

The code causing this is this React component definition:
```
export type SelectProps<
  TDisplayProperty extends string,
  TValueProperty extends string
> = RebassSelectProps & {
  name: string;
  valueProperty: TValueProperty;
  displayProperty: TDisplayProperty;
};

export const Select = <
  TDisplayProperty extends string,
  TValueProperty extends string
>({
  valueProperty,
  displayProperty,
  name = '',
  ...props
}: SelectProps<TDisplayProperty, TValueProperty>) => {

  const {
    control,
    formState: { errors },
    setValue,
  } = useFormContext<{ [key: string]: string }>();

  const handleChange = useCallback(
    (event: ChangeEvent<HTMLSelectElement>): void => {
      // Update the form state value.
      setValue(name, event.currentTarget.value, { shouldValidate: true });  <= TS error here.
    },
    [name, onChange, setValue],
  );

      <Controller
        control={control}
        name={name}
        defaultValue={defaultValue}
        rules={{
          ...(required ? { required: `${label} is required` } : {}),
          ...rules,
        }}
        ...
```

The idea here is that this is a Select component, used in a form, and it will be provided with a `name` property.  That `name` property is the property name in `react-hook-form` that will be registered - so that's the property name to be used when calling a function like `setValue()`.  However, I'm seeing this TypeScript error which seems to be suggesting that the `name` argument can only be a string literal - which is not possible.
```
src/style-guide/components/Select/Select.tsx:71:16 - error TS2345: Argument of type 'string' is not assignable to parameter of type '`${string}`'.

71       setValue(name, event.currentTarget.value, { shouldValidate: true });
                  ~~~~

src/style-guide/components/Select/Select.tsx:91:9 - error TS2322: Type 'string' is not assignable to type '`${string}`'.

91         name={name}
           ~~~~

  node_modules/react-hook-form/dist/types/controller.d.ts:19:5
    19     name: TName;
           ~~~~
    The expected type comes from property 'name' which is declared here on type 'IntrinsicAttributes & { render: ({ field, fieldState, formState, }: { field: ControllerRenderProps<{ [key: string]: string; }, `${string}`>; fieldState: ControllerFieldState; formState: FormState<...>; }) => ReactElement<...>; } & UseControllerProps<...>'

```


Can you please provide some guidance or solution for this?  We need to be able to provide a variable (not string literal) for the name property, in order to create reusable components.

Thanks.

**Comment by don-hover** [comment]
Same typing problem also occurs with computed property in errors field:
```
src/style-guide/components/Select/Select.tsx:86:14 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'DeepMap<{}, FieldError>'.
  No index signature with a parameter of type 'string' was found on type 'DeepMap<{}, FieldError>'.

86       error={errors[name]?.message ?? undefined}
                ~~~~~~~~~~~~
```

**Comment by bluebill1049** [comment]
update this codesandbox with the issue which you described above: https://codesandbox.io/s/fervent-glade-plsqi?file=/App.ts

**Comment by don-hover** [comment]
Updated here:
https://codesandbox.io/s/fervent-glade-plsqi?file=/App.ts

The basic issue is this:
The typings being applied to `useForm`/`useFormContext` in version 7 may work well for form that have fixed field names, these typings don't seem to be adaptable for more generic uses.  In particular, we often need to define reusable form components like TextField, Select, etc., that we can use in forms - and these components will have a `name` prop used to set the `name` of both the DOM element and the `react-hook-form` field. 
I have not seen how it's possible to create a typing usable in the `useForm`/`useFormContext` functions that will allow us to use a dynamic/computed field name property.

Trying to do this results in some TypeScript error like what I posted above:
`Argument of type 'string' is not assignable to parameter of type '`${string}`'.`
or
`Argument of type 'string' is not assignable to parameter of type 'never'.`

If you know of a way to make this work using the version 7 typings, please let me know.  Thanks.
