### ISSUE TITLE
Share ref usage in V7 Typescript not working

### ISSUE THREAD

**Issue by tjolr** [react-hook-form/react-hook-form#4696]
**Describe the bug**
Sharing ref usage as described in the FAQ https://www.react-hook-form.com/faqs under `How to share ref usage?` is giving an error that ref is not callable. 

**To Reproduce**
Follow the FAQ linked to above with typescript. 

useForm, useRef and register:
![image](https://user-images.githubusercontent.com/30324054/113938292-ade4c000-97fa-11eb-98f3-3ed1641f7db5.png)

Note: TaskAnswerInput is a styled input component
![image](https://user-images.githubusercontent.com/30324054/113938127-7544e680-97fa-11eb-8727-1dc409332812.png)

![image](https://user-images.githubusercontent.com/30324054/113937775-f64fae00-97f9-11eb-9b88-e3b2ba51d7d3.png)

TS version: 4.1.2

Thanks in advance :-)

**Comment by larrifax** [comment]
@bluebill1049 should this fix also be applied to `ControllerRenderProps`? I'm trying to do the same as the OP, just using `useController` instead of `register`.

**Comment by bluebill1049** [comment]
> @bluebill1049 should this fix also be applied to `ControllerRenderProps`? I'm trying to do the same as the OP, just using `useController` instead of `register`.

Sure, can u give some more detail and a codesandbox to show case the problem?

**Comment by larrifax** [comment]
> > @bluebill1049 should this fix also be applied to `ControllerRenderProps`? I'm trying to do the same as the OP, just using `useController` instead of `register`.
> 
> Sure, can u give some more detail and a codesandbox to show case the problem?

Like the OP, I'm trying to share the ref usage, but I'm doing it inside of a component which uses `useController`. The ref returned in the `ControllerRenderProps` of the `UseControllerReturn` has the type `Ref<any>` which Typescript deems not callable.

See the following codesandbox for a reproduction: https://codesandbox.io/s/sharp-allen-obk9k?file=/src/App.tsx:424-439

**Comment by bluebill1049** [comment]
> > > @bluebill1049 should this fix also be applied to `ControllerRenderProps`? I'm trying to do the same as the OP, just using `useController` instead of `register`.
> > 
> > 
> > Sure, can u give some more detail and a codesandbox to show case the problem?
> 
> Like the OP, I'm trying to share the ref usage, but I'm doing it inside of a component which uses `useController`. The ref returned in the `ControllerRenderProps` of the `UseControllerReturn` has the type `Ref<any>` which Typescript deems not callable.
> 
> See the following codesandbox for a reproduction: https://codesandbox.io/s/sharp-allen-obk9k?file=/src/App.tsx:424-439

Thank you, will get the fixed.
