### ISSUE TITLE
TS error: `<Controller />` with `Object` or extended interface field causes `property circularly references` 

### ISSUE THREAD

**Issue by ishikawa** [react-hook-form/react-hook-form#4704]
**Describe the bug**

When you have a controlled input and its field value is one of `Object` subclasses. TS compiler complains *Type of property 'caller' circularly references itself*.

```ts
interface IMyCheckbox extends Object {
  ok: boolean;
}

interface IFormInputs {
  MyCheckbox: IMyCheckbox;
}

export default function App() {
  const { handleSubmit, control } = useForm<IFormInputs>();
  ...
      <Controller
      ^^^^^^^^^^^
      Type of property 'caller' circularly references itself in mapped
      type '{ [K in keyof Function]-?: PathImpl<K & string, Function[K]>; }'.ts(2615)

        ...
        name="MyCheckbox"
        control={control}
        defaultValue={false}
        rules={{ required: true }}
        render={({ field: { onChange, value } }) => (
          <Checkbox
            onChange={(e) => onChange({ ok: e.target.checked })}
            value={value.ok}
          />
        )}
      />

```

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-controller-with-object-field-zll3i?file=/src/App.tsx:450-785
2. See the compilation error on the line 19.

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-controller-with-object-field-zll3i?file=/src/App.tsx:450-785

**Expected behavior**

No TS compier error.

**Screenshots**

<img width="873" alt="スクリーンショット 2021-04-09 18 45 20" src="https://user-images.githubusercontent.com/18448/114162127-c45a5b00-9963-11eb-8530-8942cb478205.png">

**Desktop (please complete the following information):**

- OS: Mac OS X 11.2.3
- Browser: chrome 
- Version: 89.0.4389.114

**Additional context**

In my project (React Native), I'm creating a date/time control and it handles dateTime value with [moment.js](https://momentjs.com/). The definition of moment.js'es primary dateTime object is [here](https://github.com/moment/moment/blob/e96809208c9d1b1bbe22d605e76985770024de42/moment.d.ts#L454).

**Comment by bluebill1049** [comment]
We only support the following usage: 

```
interface IFormInputs {
  MyCheckbox: {
    ok: boolean
  };
}
```

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/4373

**Comment by bluebill1049** [comment]
I am open for any TS master to resolve this problem, as my understanding this is a limitation on template string literal with name type check in this lib.

**Comment by ishikawa** [comment]
Thank you for your prompt reply. I should have searched the existing issues more carefully. I will reimplement the input so that it only uses primitive types. 🙇

**Comment by AlexTemina** [comment]
This also happens to me but in the "watch" statements. 

I'm also using a rather complex Interface for the form, and I also use moment in it. This didn't happen to me in version 6.

**Comment by bluebill1049** [comment]
@AlexTemina v6 is not strictly typed. only v7 started with a strictly typed check.

**Comment by bluebill1049** [comment]
> Thank you for your prompt reply. I should have searched the existing issues more carefully. I will reimplement the input so that it only uses primitive types. 🙇

no worries at all @ishikawa if you find a good solution around please let us know, as right now this is a design limitation for myself and the team members.

**Comment by AlexTemina** [comment]
Ah, so we cannot use moment or any other complex type for a field, right? Changing these fields to string should be enough. It makes sense, tho, it was smelly for me in the past anyways. 

Thanks!

**Comment by bluebill1049** [comment]
> Ah, so we cannot use moment or any other complex type for a field, right? Changing these fields to string should be enough. It makes sense, tho, it was smelly for me in the past anyways.
> 
> Thanks!

Personally, I prefer to embrace HTML standards and keep all input as `string`, and convert different types at submit time. It's much easier to embrace HTML standards than going the opposite. Yes, string type makes sense for input.
