### ISSUE TITLE
watch with multiple defaultValues returns undefined

### ISSUE THREAD

**Issue by mihaibogdan** [react-hook-form/react-hook-form#4705]
Hi there,

**Describe the bug**
I'm not sure if this is my fault, but it seems like if I use watch with multiple default values, i get undefined on first render.
I have to mention that if I change to individual watches, it works.

**To Reproduce**

1. Go to the code sandbox
2. Check to console (it will show {showAge: undefined, age: undefined} instead of {showAge: true, age: 30}) 

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-watch-multiple-values-yw9tc?file=/src/index.js

**Comment by bluebill1049** [comment]
follow with steps and follow the issue template.

**Comment by mihaibogdan** [comment]
Sorry for that, done 😊

**Comment by bluebill1049** [comment]
`const [showAge, age] = watch(["showAge", "age"], {showAge: 2, age: 2});` 👍

**Comment by mihaibogdan** [comment]
Hmmm, I tried that but in typescript I get some errors.

For this line:
const [showAge, age] = watch(['showAge', 'age'], { showAge: 2, age: 2 });

`No overload matches this call.
  Overload 1 of 4, '(fieldName: string | `${string}.${string}` | `${string}.${number}`, defaultValue?: any): any', gave the following error.
    Argument of type 'string[]' is not assignable to parameter of type 'string | `${string}.${string}` | `${string}.${number}`'.
      Type 'string[]' is not assignable to type '`${string}.${number}`'.
  Overload 2 of 4, '(fieldNames: ("showAge" | "age")[], defaultValue?: any[]): any[]', gave the following error.
    Argument of type '{ showAge: number; age: number; }' is not assignable to parameter of type 'any[]'.
      Object literal may only specify known properties, and 'showAge' does not exist in type 'any[]'.
  Overload 3 of 4, '(callback: WatchObserver<FieldValues>, defaultValues?: { [x: string]: any; }): Subscription', gave the following error.
    Argument of type 'string[]' is not assignable to parameter of type 'WatchObserver<FieldValues>'.
      Type 'string[]' provides no match for the signature '(value: { [x: string]: any; }, info: { name?: string; type?: EventType; value?: unknown; }): void'.ts(2769)`

I've updated the sandbox here: https://codesandbox.io/s/react-hook-form-watch-multiple-values-yw9tc?file=/src/index.tsx

**Comment by bluebill1049** [comment]
looks like a type mismatch, will look into it.

**Comment by mihaibogdan** [comment]
Awesome! Thank you for taking care of this 😊. This is one of the best packages that I've encountered.

PS: I love the emoji system from your commit messages. ❤️
