### ISSUE TITLE
Typescript type errors for existing react-hook-form properties

### ISSUE THREAD

**Issue by kihuha** [react-hook-form/react-hook-form#4715]
**Describe the bug**
I have upgraded my typescript/react project to use the latest version of react-hook-form (version 7.0.5). I am now getting type definition errors that previously were not being raised. In addition, when I use the example samples of code given in the documentation, the same type definitions errors are being raised.

**To Reproduce**
Case 1:

1. Import the useForm hook to any react component file
2. Destructure property `error` from the `useForm()` hook
3. A type definition error is raised `Property 'errors' does not exist on type 'UseFormReturn<Inputs>'

Case 2

1. Import the useForm hook to any react component file
2. Destructure property `register` from the `useForm()` hook
3. Create a form component with an input or select component
4. Add a `ref` to the input/select component and assign it to `register`
5. A type definition error is raised

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

V7

- [TS](https://codesandbox.io/s/adoring-grothendieck-s3n85)

**Expected behavior**

- I expect to be able to restructure the `errors` property without getting a type definition error
- It should be possible to assign `register` to an input's ref without ts errors

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Chrome
- Version: 88

**Additional context**
- I am using the following packages:
      React version 17.0.2
      React Dom version 17.0.2
      React Hook Form version 7.0.5
      Typescript Version 4.2.3
- Be sure to explicitly define a ref prop and assign it `register` to be able to see the error. If you do it like so:
- Check the type definition `UseFormReturn`

**Comment by bluebill1049** [comment]
which example has this? I will get it updated.

`formState: { errors }`

**Comment by bluebill1049** [comment]
provide the incorrect code on the doc, will get it updated.

**Comment by kihuha** [comment]
Sorry for the delay in replying. 

The examples I was referring to are in a lot of places in the doc. Examples include:
- https://codesandbox.io/s/react-hook-form-get-started-ts-5ksmm    ----> taken from https://react-hook-form.com/get-started
- https://codesandbox.io/s/react-hook-form-get-started-ts-4sfje       ------> taken from https://react-hook-form.com/get-started

In the examples, you are passing the register prop like so:
```
// Example 1 
<input   {...register("test", { required: true })}  />
```
as opposed to 
```
// Example 2
<input   ref={register("test", { required: true })}  />
```

Example 1 works without raising errors in version 7 but Example 2 will not work. 

I am working on a codebase that has been using this wonderful package since version 5 and it would be quite an undertaking to change all our forms to pass props as in Example 1.

**Comment by bluebill1049** [comment]
<img width="1057" alt="Screen Shot 2021-04-13 at 9 36 46 am" src="https://user-images.githubusercontent.com/10513364/114475516-c52d0e80-9c3b-11eb-8ca2-deaada6362d6.png">

what's the issue above? 

by all means, if v6 works for you, we are still maintain it. 👍

**Comment by jasperkuperus** [comment]
There are still several examples on this page: https://react-hook-form.com/get-started

Just look for `, errors` and you'll find them. Also, I see multiple `ref={register}` in these examples, while I found out now that `{...register()}` is the way to go?

**Comment by bluebill1049** [comment]
> `, errors`

can you provide some screenshots?

**Comment by jasperkuperus** [comment]
Yes sir,

![Screenshot 2021-04-29 at 10 44 35](https://user-images.githubusercontent.com/1655683/116524768-0b3ecf00-a8d8-11eb-8919-118d642cef27.png)
![Screenshot 2021-04-29 at 10 44 51](https://user-images.githubusercontent.com/1655683/116524779-0da12900-a8d8-11eb-87cb-d4452eb83e46.png)
![Screenshot 2021-04-29 at 10 45 10](https://user-images.githubusercontent.com/1655683/116524786-0e39bf80-a8d8-11eb-99ff-f47ec1f10304.png)
![Screenshot 2021-04-29 at 10 45 26](https://user-images.githubusercontent.com/1655683/116524788-0ed25600-a8d8-11eb-8920-875d88c16c21.png)

**Comment by bluebill1049** [comment]
@jasperkuperus you are getting a cached version, please do a hard refresh.

**Comment by jasperkuperus** [comment]
That's so weird! I honestly thought I've visited this page for the first time in my life 😨  But yes, I also see a `Version 7` badge in the top left corner which I didn't see before. Thanks. This explains all the TypeScript issues I ran into!
