### ISSUE TITLE
Add a useWatchError or equivalent way to watch errors for a single field in a nested component

### ISSUE THREAD

**Issue by antoineol** [react-hook-form/react-hook-form#4716]
**Is your feature request related to a problem? Please describe.**

I haven't found an easy way to watch errors of a single field in a nested component without re-rendering it each time _any_ other field error changes (or other events that change the form state).

**Describe the solution you'd like**

`useWatch` works well to return the value of the provided field name and don't cause re-renders when other fields have a value change (assuming we pass the control as prop instead of relying on the FormProvider). I'd love to have the same to track errors instead of values.

The idea is to have a nested component for each field. Each component is responsible for displaying its own errors, and should _not_ render on events that are not related to this field (e.g. other fields' errors or value changes). Example use case: make a form builder (based on a JSON model).

**Describe alternatives you've considered**

Passing specific errors as props. But it's not ideal for all use cases.

I have checked the useWatch implementation to get some inspiration, but I haven't found any easy way to watch error changes from control methods. Maybe `formStateSubjectRef`? But it might require to loop over all errors, for each component that is subscribing.

**Additional context**

N/A

**Comment by bluebill1049** [comment]
1. useFormState
2. useController by subscribe `fieldState` which will be only return that single input's error state.

**Comment by antoineol** [comment]
Thanks for the quick answer and the lead!

I'm experimenting with it. My quick results are:

**useFormState**:

```ts
const { errors: { [name]: error } } = useFormState({ control });
```

=> Re-renders on all error changes, not just the current field's error.

**useController**

```ts
const { fieldState: { error } } = useController({
  name,
  control,
});
```

=> Same, it re-renders on error changes on any field, not just the current field + it seems to be dedicated to controlled components. Mine is uncontrolled, and it seems to cause a bug. When the error state changes, what I'm typing is lost. I have to type it again to be taken into account.

----

**Update on what I have tried**

The below approach seems to work as expected, only rendering a given field when its errors changes, not other fields' errors. I'm okay to keep it. I'm sharing, in case it can help in any way. Maybe not the cleanest, but I'm open to suggestions :)

`WatchErrors.tsx`

```tsx
import { createContext, FC, useContext, useEffect, useRef, useState } from 'react';
import { Control, FieldError, FieldValues } from 'react-hook-form';

interface Props<TFieldValues extends FieldValues = FieldValues> {
  control: Control<TFieldValues>;
}

const WatchErrorsContext = createContext<Control | null>(null);

WatchErrorsContext.displayName = 'RHFControlContext';

const useWatchErrorsContext = <TFieldValues extends FieldValues>(): Control<TFieldValues> =>
  (useContext(WatchErrorsContext) as unknown) as Control<TFieldValues>;

export const WatchErrorsProvider: FC<Props> = props => (
  <WatchErrorsContext.Provider value={props.control as Control}>
    {props.children}
  </WatchErrorsContext.Provider>
);

export function useWatchErrors(name: string) {
  const [error, setError] = useState<FieldError>();
  const errRef = useRef<FieldError>();
  const control = useWatchErrorsContext();
  useEffect(() => {
    const sub = control.formStateSubjectRef.current.subscribe({
      next: ({ errors }) => {
        if (errors) {
          const err: FieldError = errors?.[name];
          if (err !== errRef.current) {
            errRef.current = err;
            setError(err);
          }
        }
      },
    });
    return sub.unsubscribe;
  }, [control.formStateSubjectRef, name]);
  return error;
}
```

_Usage:_

Form root:

```tsx
const methods = useForm(/* ... */);

// ...

return <WatchErrorsProvider control={methods.control}>
  <form onSubmit={/* ... */}>
    {/* ... */}
  </form>
</WatchErrorsProvider>;
```

In the nested component:

```tsx
const error = useWatchErrors(name);
```

Why using a new `WatchErrorsProvider`? Because the existing `FormProvider` seems to re-render the nested component on any field error change, even if I'm only reading the `control` from the provider's hook.

**Comment by bluebill1049** [comment]
> Mine is uncontrolled, and it seems to cause a bug. When the error state changes, what I'm typing is lost. I have to type it again to be taken into account.

can you share a codesandbox?

**Comment by bluebill1049** [comment]
just reproduced the bug on Controller, it shouldn't re-render other input for error update: https://codesandbox.io/s/strange-panini-z9cub?file=/src/App.js

**Comment by bluebill1049** [comment]
actually, it's a valid feature request, to limit on field level. right now useFormState is form level. i will ping to the board.

**Comment by bluebill1049** [comment]
I will investigate this feature for a solution in the meantime.

**Comment by antoineol** [comment]
Thanks for the quick reply!

Here is a sandbox. It reproduces the fact that all inputs are re-rendered using `useController` (cf logs).

https://codesandbox.io/s/aol-rhf-errors-of4sr?file=/src/index.js

It seems the key stroke blocked when the error status changes is an error specific to my app; you can ignore it.

**Comment by bluebill1049** [comment]
> Thanks for the quick reply!
> 
> Here is a sandbox. It reproduces the fact that all inputs are re-rendered using `useController` (cf logs).
> 
> https://codesandbox.io/s/aol-rhf-errors-of4sr?file=/src/index.js
> 
> It seems the key stroke blocked when the error status changes is an error specific to my app; you can ignore it.
> 
> Edit: I use Material UI fields as uncontrolled components.

that's right as we are using useFormState internally, will seek for improvement.
