### ISSUE TITLE
Type error with react select

### ISSUE THREAD

**Issue by apoorvmote** [react-hook-form/react-hook-form#4719]
**Describe the bug**
The code runs but there is type error when using latest react-select with react-hook-form

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-with-ui-library-ts-forked-i2pzb?file=/src/index.tsx
2. Look at Select component there is red squigly 
```ts
import React from "react";
import ReactDOM from "react-dom";
import Select from "react-select";
import { useForm, Controller } from "react-hook-form";

import "./styles.css";

interface IFormInput {
  iceCreamType: string;
}

const App = () => {
  const { control, handleSubmit } = useForm<IFormInput>();

  const onSubmit = (data: IFormInput) => {
    alert(JSON.stringify(data));
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <label>Ice Cream Preference</label>
      <Controller
        name="iceCreamType"
        render={({ field }) => (
          <Select
            {...field}
            options={[
              { value: "chocolate", label: "Chocolate" },
              { value: "strawberry", label: "Strawberry" },
              { value: "vanilla", label: "Vanilla" }
            ]}
          />
        )}
        control={control}
        defaultValue=""
      />

      <input type="submit" />
    </form>
  );
};

const rootElement = document.getElementById("root");

ReactDOM.render(<App />, rootElement);
```

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-with-ui-library-ts-forked-i2pzb?file=/src/index.tsx

**Expected behavior**
It should work with react select with typescript enabled.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 89

**Comment by jorisre** [comment]
react-select value type is: `{ label: string;  value: string; }`.
Your form type doesn't satisfy react-select type.

Change
```ts
interface IFormInput {
  iceCreamType: string;
}
```
to
```ts
interface IFormInput {
  iceCreamType: { value: string; label: string };
}
```

Working sandbox: https://codesandbox.io/s/react-hook-form-with-ui-library-ts-forked-83rg2

**Comment by apoorvmote** [comment]
Thanks its working. The docs have it differently. Maybe fix docs for others.
Also now I think bill is human. Before I thought he is machine who's awake 24X7.

**Comment by jorisre** [comment]
@apoorvmote Can you send me the link of the docs where you see a mistake ? thanks

**Comment by apoorvmote** [comment]
https://react-hook-form.com/get-started#IntegratingwithUIlibraries

There is codesandbox attached to it. I forked the same for this example.

**Comment by apoorvmote** [comment]
![error](https://user-images.githubusercontent.com/9799239/114273467-c392f900-9a37-11eb-9cd7-47ab30cc42cb.jpg)
Even though its working perfectly I get this error in console. What am I missing here.
I am using NextJS in Typescript.

**Comment by jorisre** [comment]
It's a Next.js warning with ssr. Your component's `id` isn't the same between the server and the client render.

**Comment by jorisre** [comment]
Please open a Github discussion if it's related to React Hook Form

**Comment by apoorvmote** [comment]
Thanks for helping with this issue. And you were right. I did static export and error disappeared.
