### ISSUE TITLE
Input is cleared after onBlur validation

### ISSUE THREAD

**Issue by nuno-andrade** [react-hook-form/react-hook-form#4720]
**Describe the bug**
With a custom Input, with validation mode: 'onBlur', the input is cleared after the validation if the input is Invalid. If then you repeat the same patter it will work correctly.

**To Reproduce**

1. Go to 'https://codesandbox.io/s/v7-q2wdw'
2. Click on 'date input'
3. Insert '12/20'
4. Click outside of the input
5. See Input with default placeholder instead of the entered values

If then you repeat the same steps(2-4) it will work correctly.

I also included the same input without the package validation in order to check if there is something needed to investigate.

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

V7

- [JS](https://codesandbox.io/s/v7-q2wdw?file=/src/App.js) Template

**Expected behavior**
Input is validated but remains with the entered values.

**Desktop (please complete the following information):**

- OS: iOS
- Browser: Chrome, Safari

**Comment by bluebill1049** [comment]
for Controlled component, use `useController` or `Controller` as during component re-render `value` is not provided by register method and hence the input value gets losted.
