### ISSUE TITLE
broken API docs page

### ISSUE THREAD

**Issue by deebov** [react-hook-form/react-hook-form#4727]
**Describe the bug**
the API docs page shows 404

**To Reproduce**
go to https://react-hook-form.com/api

it throws you to https://react-hook-form.com/vundefined/api

**Screenshots**
 
![image](https://user-images.githubusercontent.com/28673719/114316744-1686b200-9b05-11eb-8437-f2772d6662f1.png)

**Comment by jorisre** [comment]
It's a cache issue, here is a solution: https://github.com/react-hook-form/react-hook-form/issues/4642#issuecomment-814052880

**Comment by bluebill1049** [comment]
yea, it should be resolved after a hard refresh or in a new tab 👍
