### ISSUE TITLE
@bluebill1049 I used version 3.26.4, I have a wizard form that generating child form using json schema, defaultValues getting undefined whenever I jump to the next step and re register new child component. But it's work perfectly whenever it's on first step.

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#473]
@bluebill1049 I used version 3.26.4, I have a wizard form that generating child form using json schema, defaultValues getting undefined whenever I jump to the next step and re register new child component. But it's work perfectly whenever it's on first step.
Whenever I jump to the next step, I do reset({}), and re register component

_Originally posted by @muhamad-rizki in https://github.com/react-hook-form/react-hook-form/issues/411#issuecomment-550922107_

**Comment by bluebill1049** [comment]
@muhamad-rizki can you share the code how you register the input?

**Comment by muhamad-rizki** [comment]
here is how I register my component:
https://github.com/muhamad-rizki/dynamic-form/blob/0c93d30853c3e4c3ba78ee5dcd5a055ae9511b5b/src/modules/DynamicForm.js#L96

and here I log getValues(), at first its initialized, but after registering component, values become undefined
https://github.com/muhamad-rizki/dynamic-form/blob/0c93d30853c3e4c3ba78ee5dcd5a055ae9511b5b/src/modules/DynamicForm.js#L307

**Comment by bluebill1049** [comment]
@muhamad-rizki try to use `watch()` instead.

**Comment by bluebill1049** [comment]
and only watch the fields that you want to `watch` as well

**Comment by muhamad-rizki** [comment]
i got little confused on how to use the ```watch``` function, so it is we just render all page and using watch as trigger to moving between page?

**Comment by muhamad-rizki** [comment]
ah never mind, I already figured it out, thanks anyway. now it's worked 💃

**Comment by bluebill1049** [comment]
oh!! cool awesome 

@muhamad-rizki if you are using `setValue` it doesn't get re-render all the time, which the lib is optimized to only render when necessary.
