### ISSUE TITLE
valueAsNumber has no effect on checkboxes

### ISSUE THREAD

**Issue by rkjaer** [react-hook-form/react-hook-form#4732]
**Describe the bug**
When using the `valueAsNumber` option (set to `true`) when registering checkbox inputs RHF still returns value(s) as string.

**To Reproduce**

1. Go to https://codesandbox.io/s/stoic-diffie-4sdf3
2. Click on one of more of the checkboxes
3. Submit the form
4. See the data in the console – `shoppingFriends` is an array of strings

**Codesandbox link**
https://codesandbox.io/s/stoic-diffie-4sdf3

**Expected behavior**
Registering checkbox inputs with `valueAsNumber` should also return them as numbers.

**Additional context**
`setValueAs` also does have any effect when used with checkboxes w/ values.

**Comment by bluebill1049** [comment]
`valueAs` only apply to input type at the moment.

**Comment by bluebill1049** [comment]
<img width="575" alt="Screen Shot 2021-04-12 at 5 14 54 pm" src="https://user-images.githubusercontent.com/10513364/114355282-a0408900-9bb2-11eb-9509-7366d9c266fc.png">
