### ISSUE TITLE
V7: radio group defaultChecked

### ISSUE THREAD

**Issue by kitloong** [react-hook-form/react-hook-form#4735]
**Describe the bug**
`defaultChecked` is not working with radio group

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-get-started-forked-oiuoh
2. Check radio group with `Developer`

**Codesandbox link (Required)**
V7: https://codesandbox.io/s/react-hook-form-get-started-forked-oiuoh?file=/src/index.js:1113-1130

**Expected behavior**
radio `No` is checked by default

**Additional context**
V6 working code
https://codesandbox.io/s/react-hook-form-get-started-forked-rn0q7?file=/src/index.js:969-986
`Developer` radio group was generated from Form Builder.

**Comment by bluebill1049** [comment]
fixed: https://github.com/react-hook-form/react-hook-form/pull/4375

**Comment by bluebill1049** [comment]
oops used wrong issue number: https://github.com/react-hook-form/react-hook-form/commit/74f7c42758f4f1949fb887512db0f45d49d9e41f
