### ISSUE TITLE
Form is dirty even though dirtyFields is empty

### ISSUE THREAD

**Issue by lynxtaa** [react-hook-form/react-hook-form#4740]
**Describe the bug**
Form is dirty when it should not be dirty

**To Reproduce**

1. Focus on first input
2. Click elsewhere
2. See `isDirty: true`

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-dirty-y7x03?file=/src/App.tsx

**Expected behavior**
Expected `isDirty` to be `false` since nothing is changed and `dirtyFields` is empty

**Comment by bluebill1049** [comment]
looks like missing defaultValues: 

`defaultValues: { foo: "", bar: '' }`, we are doing deepCompare with defaultValues, and can't assume input's value.

**Comment by lynxtaa** [comment]
@bluebill1049  Is it comparing `{ foo: "" }` with `{ foo: "", bar: undefined }`? If so, I think these values should be considered equal

**Comment by lynxtaa** [comment]
@bluebill1049 Check out this version please https://codesandbox.io/s/react-hook-form-dirty-forked-on4pf?file=/src/App.tsx

**Comment by bluebill1049** [comment]
> @bluebill1049 Is it comparing `{ foo: "" }` with `{ foo: "", bar: undefined }`? If so, I think these values should be considered equal

your input is registered with Controller, so it's '' vs undefined.

**Comment by bluebill1049** [comment]
> @bluebill1049 Check out this version please https://codesandbox.io/s/react-hook-form-dirty-forked-on4pf?file=/src/App.tsx
> Touching first input sets `isDirty: true`

will take a look at it.

**Comment by bluebill1049** [comment]
> @bluebill1049 Check out this version please https://codesandbox.io/s/react-hook-form-dirty-forked-on4pf?file=/src/App.tsx
> Touching first input sets `isDirty: true`

there is no `deafultValues`

**Comment by bluebill1049** [comment]
<img width="927" alt="Screen Shot 2021-04-13 at 10 09 58 am" src="https://user-images.githubusercontent.com/10513364/114477881-6a49e600-9c40-11eb-8aaf-5bc8aa0923ac.png">

**Comment by lynxtaa** [comment]
Thanks!
In this example https://codesandbox.io/s/react-hook-form-dirty-y7x03?file=/src/App.tsx formValues after load are `{ foo: "" }`. After touching first input values are : `{ foo: "", bar: undefined }`. If I understood correctly react-hook-form is comparing these values with `defaultValues` which are `{ foo: "" }`.

1. Maybe it should ignore `undefined` when comparing? For example, we are using complex controlled fields with signatures like `{ id: number, label: string } | undefined`. Setting `defaultValues: { myField: undefined }` works but it feels strange
2. Why `dirtyFields` is empty? Should it contain `bar`?

**Comment by bluebill1049** [comment]
> 2\. Why `dirtyFields` is empty? Should it contain `bar`

what do you mean? can you share steps?

**Comment by kpnigalye** [comment]
> @bluebill1049 Is it comparing `{ foo: "" }` with `{ foo: "", bar: undefined }`? If so, I think these values should be considered equal

I checked your code you have posted here. https://codesandbox.io/s/react-hook-form-dirty-y7x03?file=/src/App.tsx
 
You are missing **defaultValue** for **bar**, thats why it is undefined. Add a defaultValue for 'bar' and it will work as expected.

**Comment by lynxtaa** [comment]
> 
> 
> > 2. Why `dirtyFields` is empty? Should it contain `bar`
> 
> what do you mean? can you share steps?

@bluebill1049,

1. Open https://codesandbox.io/s/react-hook-form-dirty-y7x03?file=/src/App.tsx
2. Touch the first input
3. See in console that `isDirty: true` but `dirtyFields: {}`

**Comment by lynxtaa** [comment]
> 
> 
> > @bluebill1049 Is it comparing `{ foo: "" }` with `{ foo: "", bar: undefined }`? If so, I think these values should be considered equal
> 
> I checked your code which you have posted here. https://codesandbox.io/s/react-hook-form-dirty-y7x03?file=/src/App.tsx
> 
> You are missing **defaultValue** for **bar**, thats why it is undefined. Add a defaultValue for 'bar' and it will work as expected.

This is simplified example but imagine we have a complex controlled field with a signature like `{ id: number, label: string } | undefined`.

```ts
type FormValues = {
  foo: { id: number, label: string } | undefined
}

const form1 = useForm<FormValues>({
  mode: "onBlur",
  defaultValues: {} // this breaks isDirty
});

const form2 = useForm<FormValues>({
  mode: "onBlur",
  defaultValues: {
    foo: undefined // this works
  } 
});
```

I think `form1` and `form2` should behave equally

**Comment by bluebill1049** [comment]
@lynxtaa I see what you mean, however for now we will stick to what we got for a deep check against `defaultValues`, and ask the user to provide full defautlValues.

**Comment by lynxtaa** [comment]
@bluebill1049 I've created a PR, hope it'll be helpful https://github.com/react-hook-form/react-hook-form/pull/4761

**Comment by bluebill1049** [comment]
Thanks for the PR and your contribution! however, we are intentionally don't want to make the following equal:

`{} !== {test: undefined}`

**Comment by lynxtaa** [comment]
No problem, thanks for your awesome library! I'll set `undefined` for my fields -- it works.

But still, should `isDirty` be consistent with `dirtyFields`? Is it expected behaviour?

**Comment by bluebill1049** [comment]
Thanks for understanding. `isDirty` is measured against `defaultValues`, while `dirtyFields` are more "relaxed" with key not found. It's expected behavior.

**Comment by mlnarik** [comment]
Does this fix issue when isDirty = true when default values has more values than there are inputs?

eg.
defaultValues { name: "John", middle: "Johnny",  surname: "Doe"}
getValues { name: "John", surname: "Doe"}

this would set isDirty to true

I have an issue when field **is not always** present (like Middle name) in the form but default value is set then isDirty flag is always true

**Comment by bluebill1049** [comment]
> Does this fix issue when isDirty = true when default values has more values than there are inputs?
> 
> eg.
> defaultValues { name: "John", middle: "", surname: "Doe"}
> getValues { name: "John", surname: "Doe"}
> 
> this would set isDirty to true
> 
> I have an issue when field **is not always** present (like Middle name) in the form but default value is set in case it is needed then isDirty flag is always true. I have found the cause to be deepEquals function..

nope, it's a deep equal and its expected behavior.

**Comment by mlnarik** [comment]
> > Does this fix issue when isDirty = true when default values has more values than there are inputs?
> > eg.
> > defaultValues { name: "John", middle: "", surname: "Doe"}
> > getValues { name: "John", surname: "Doe"}
> > this would set isDirty to true
> > I have an issue when field **is not always** present (like Middle name) in the form but default value is set in case it is needed then isDirty flag is always true. I have found the cause to be deepEquals function..
> 
> nope, it's a deep equal and its expected behavior.

But should we use deepEqual for isDirty? It makes isDirty flag unusable in highly dynamic forms, which is half of them in my current project. I wish I could supply my own isDirty function.

**Comment by bluebill1049** [comment]
You can build ur own :) getValues() and do ur  own compare 👌

**Comment by rygo11** [comment]
I had the same issue, so instead of using isDirty, I'm checking if the dirtyFields object is empty:

```
export const isEmpty = (obj: object) => {
  return Object.keys(obj).length === 0;
}
```
`if(!isEmpty(dirtyFields)) { "insert code here" }`

Seems to be working fine

**Comment by AndrewCraswell** [comment]
Oof, I just hit this issue and was absolutely convinced that it *must* be a bug, until reading this. I can understand the logic about missing `defaultValue`. But *surely* if a field is considered dirty, then it should appear in the `dirtyFields` object? By definition, `isDirty` cannot be `true` while `dirtyFields` is empty.

If this is really expected behavior as described above, then at the very least it's not clear or obvious and feels more like tribal knowledge. For now, I'm resorting to @rygo11's workaround.

**Comment by Venipa** [comment]
![image](https://user-images.githubusercontent.com/17952364/189899299-d999b93f-ac07-4199-ad0e-27f338022782.png)
left: dirtyFields prop
right: isDirty prop

there is definitely something wrong there, i've changed a prop, the isDirty prop is right, dirtyFields are not reflecting the real value as it seems
