### ISSUE TITLE
Getting error Type instantiation is excessively deep and possibly infinite after upgrade to v7

### ISSUE THREAD

**Issue by lBilali** [react-hook-form/react-hook-form#4745]
**Describe the bug**
After upgrading to 7.0.7 I get typescript issue:
`Type instantiation is excessively deep and possibly infinite.`

**To Reproduce**

1. Go to the sandbox 
2. Notice the typescript error

**Codesandbox link (Required)**
https://codesandbox.io/s/interesting-brook-qfxwo?file=/src/App.tsx

**Expected behavior**
Should not throw an error

**Additional context**
Here is a similar bug which was fix already https://github.com/react-hook-form/react-hook-form/issues/4441

**Comment by bluebill1049** [comment]
we don't support circular reference for string template literal type check, it's a design limitation for type check.

**Comment by bluebill1049** [comment]
after careful assessment by myself and @kotarella1110 we are closing this issue as a design limitation with type check (string template literal).

**Comment by geritol** [comment]
I am also running into the same issue using `7.1.1`

**Comment by bianchi** [comment]
Any way to overcome this?
