### ISSUE TITLE
V7 automatic unregister

### ISSUE THREAD

**Issue by linde12** [react-hook-form/react-hook-form#4746]
**Describe the bug**
In V7, automatic unregister of fields was not only changed but removed entirely. This means that most applications which rely on this (e.g. conditional fields) today will break even after running the V6 to V7 codemod and reading through the guide (which doesn't mention this _very_ important change)

This change seems to be undocumented (outside of github discussions) yet a _huge_ breaking change. Even the example of "Conditional Fields" does not address this - the code is the same (except the changes to `register`) but the output is different (see screenshots)

**To Reproduce**
See [V6](https://codesandbox.io/s/react-hook-form-conditional-fields-forked-mku3i?file=/src/index.js) and [V7 ](https://codesandbox.io/s/react-hook-form-conditional-fields-qgr41) versions after clicking the checkbox, entering some text, and unclicking it. The output differs and there is not suggested solution on how to handle this.

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

**Expected behavior**
V6 & V7 to have same default behaviors, or if changed to be well documented and provide an alternate solution. Even the `shouldUnregister` prop of `useForm` has been removed now so basically all existing applications that rely on this behavior (which, i'm willing to bet, is a very good chunk of all applications) will break when trying to upgrade.

**Screenshots**
![image](https://user-images.githubusercontent.com/3235069/114420065-4771f000-9bb4-11eb-939a-783a68509529.png)
![image](https://user-images.githubusercontent.com/3235069/114420081-4b9e0d80-9bb4-11eb-983e-b8b99c29c692.png)

**Additional context**

Most of the applications i've written rely on this behavior (i use a state management library to save state when i need) and it is a feature i actively look for in a form management library. Now it has been removed with no other apparent solution other than manually unregistering every field. Yup/Joi validations will fail because fields that aren't supposed to be there are now there and instead i have to introduce additional implicit logic in my submit handler to remove certain fields based on other fields before submitting anything to my API.

Writing nested conditional rendering now will be painful because you'd have to:
a) implicitly keep track of an unregister fields (OK in a small app, nightmare in a larg complex & nested app with lots of conditional fields)
b) wrap your input components in some wrapper component which does something like `useEffect(() => () => unregister(...), [])` - additional boilerplate for something that was not even needed in V6 which of course also had the (now removed) option to disable it with `shouldUnregister: false`

I don't think it was a good idea to change the default behavior here _and_ remove the option (`shouldUnregister`) to opt-out. Maybe it is something that can be reintroduced?

**Comment by iamacook** [comment]
It would be nice to see this feature again. In the meantime, I threw together a quick hook that hacks this feature back in [here](https://codesandbox.io/s/react-hook-form-conditional-fields-forked-9hpwi?file=/src/index.js). You just have to pass it a form ref and the unregister function.

**Comment by bluebill1049** [comment]
This is in the changelog as breaking change, but I will update the documentation as well. We do have a feature request in the backlog which you can upvote against: `shouldUnregister`, but we have removed mutationObserver and we will not include that back again.

**Comment by bluebill1049** [comment]
here is the feature request: https://github.com/react-hook-form/react-hook-form/issues/4355

**Comment by bluebill1049** [comment]
Doc is updated, will implement the feature once it reaches its demand from the community.

**Comment by linde12** [comment]
> This is in the changelog as breaking change, but I will update the documentation as well. We do have a feature request in the backlog which you can upvote against: `shouldUnregister`, but we have removed mutationObserver and we will not include that back again.

Cool, thanks!

**Comment by rpelorosso** [comment]
Not having this feature renders react-hook-form useless.
