### ISSUE TITLE
Values set using reset are overridden with the values in useEffect

### ISSUE THREAD

**Issue by nanivijay** [react-hook-form/react-hook-form#4747]
React-hook-form version : V7
Repro steps:
https://codesandbox.io/s/react-hook-form-js-forked-oc3pn?file=/src/App.js
1. Open the codebox link mentioned
2. Click on the load data button without selecting any thing in the dropdown

Expected result:
Dropdown should be selected to "Category A" and the first name should be **"first name - reset"**

Actual result:
Dropdown option selected to "Category A" but the first name is **"first name - useEffect"**

Could you please help how can I solve this issue?

**Comment by bluebill1049** [comment]
need more detail and context.
