### ISSUE TITLE
Feature request: Include validation parameters in error object

### ISSUE THREAD

**Issue by krnlde** [react-hook-form/react-hook-form#475]
**Is your feature request related to a problem? Please describe.**
Currently when a field has a validation-error it returns an object of the following structure:
```json5
{
  type: "minLength"
  message: ""
  ref: [RefObject]
}
```

**Describe the solution you'd like**
It would be awesome to get the validation parameters as well as the type to include them in the error message, e.g.:
```json5
{
  type: "minLength"
  parameter: 6 // <----- Notice this line here
  message: ""
  ref: [RefObject]
}
```

**Additional context**
This way we would be able to translate it parametrized:

`Component.tsx`
```tsx
// ...
  <FormControl type="password" name="password" innerRef={register({minLength: 6})} />
  <FormFeedback>{t(`validation.${error.type}`, {param: error.parameter})}</FormFeedback>
// ...
```

`i18n.json`
```json5
// ...
  "validation": {
    "minLength": "This field must be at least {{param}} characters"
  },
// ...
```

I briefly took a look at your sourcecode but couldn't pinpoint where to get and add this information so far (it should be somewhere around [here](https://github.com/react-hook-form/react-hook-form/blob/1ea1f797916c9bbc978245f365ade31bdd524be0/src/useForm.ts#L522)) but I'm glad to produce a PR if you guide me. What do you think?

Cheers,
Kai

**Comment by krnlde** [comment]
This will influence this PR #430

**Comment by bluebill1049** [comment]
Thanks @krnlde. I think in fact you are register with your validation rule, you can easily be made into a variable and use it in your error message. as much as I want to include it at the same time I try my best to avoid "unnecessary" (things you can achieve in your app-level) features to increase the package size, hope you understand.

**Comment by bluebill1049** [comment]
I am going to close this for now, maybe we can look into this in the future :)
