### ISSUE TITLE
V7: Add onChange and onBlur options to register()

### ISSUE THREAD

**Issue by kensukesaito** [react-hook-form/react-hook-form#4751]
**Is your feature request related to a problem? Please describe.**

In V6, I was able to use the following, but in V7, it is no longer available, which is inconvenient.

There is a workaround as follows, but it is tedious and not beautiful.

It would be nice to be able to use the onChange and onBlur options in register().

```jsx
// V6
<input type="text" name="example" ref={register({ required: true })} onChange={(event) => { ... }} onBlur={(event) => { ... }} />
```

**Describe the solution you'd like**

```jsx
// Wish
<input type="text" {...register('example', {
  required: true,
  onChange: (event) => { ... },
  onBlur: (event) => { ... },
})} />
```

**Describe alternatives you've considered**

```jsx
// Workaround
const { onChange, ...restProps } = register('example')

<input {...restProps} onChnage={(event) => {
  onChange(event)
  // do something
}} />
```

**Comment by bluebill1049** [comment]
Good feature request!

**Comment by msheakoski** [comment]
I ran into this issue as well after upgrading from 6 to 7. I did not realize that my input's onChange was conflicting with register()'s. @kensukesaito's API suggestion looks good to me! 👍

**Comment by Sannnao** [comment]
I think it could be possible to also add a possibility to pass a custom ref
