### ISSUE TITLE
V6: useWatch not able to get value of existing form on render

### ISSUE THREAD

**Issue by bjarkehs** [react-hook-form/react-hook-form#4753]
**Describe the bug**
When using `useWatch` it doesn't work on first render of a component, even if the form already has content from the user inputting. I know that the documentation states that `useWatch` and `watch` do not work on first render, but according to docs it's because register has not run yet. In this case it has.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-form-context-forked-kpufy?file=/src/index.js
2. Enter some data into the Test input field
3. Click the "Show conditional"
4. See that it shows no watched error
5. Enter some more data into Test input field
6. See that now it shows the data

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-form-context-forked-kpufy?file=/src/index.js

**Expected behavior**
I expect watched value to be whatever I've inputted into the test field before showing the conditional component

**Comment by bjarkehs** [comment]
It seems that if I change `useWatch` to `watch` then it works as expected:
https://codesandbox.io/s/react-hook-form-form-context-forked-47odg?file=/src/index.js

**Comment by bluebill1049** [comment]
This is due to when <ConditionalComponent /> gets mounted, it will need a defaulValue to fallback. This was one of the design limitation in v6, watch works because it never gets "unmounted".

**Comment by bjarkehs** [comment]
Okay, is this not the case for v7?

**Comment by bluebill1049** [comment]
Yes, fixed in v7 with a new design.

**Comment by bjarkehs** [comment]
Yeah I just tried.

https://codesandbox.io/s/react-hook-form-form-context-forked-cz622?file=/src/index.js

Okay, thanks! I'll close this. We'll use `watch` until we can upgrade to v7.

**Comment by bluebill1049** [comment]
@bjarkehs I think you can work around this by the following:
```
useWatch({
  defaultValue: getValues('test'),
})
```

**Comment by bjarkehs** [comment]
Thank you! I had not considered using defaultValue for this.

**Comment by bluebill1049** [comment]
let me know if that helps.

**Comment by bjarkehs** [comment]
It does. I think I'll go with this approach until we can upgrade. Thanks.
