### ISSUE TITLE
useWatch() does not always catch changes

### ISSUE THREAD

**Issue by serg-prasolov** [react-hook-form/react-hook-form#4762]
**Describe the bug**
Two components, in the second one I set a value to the registered input field, in the first one I watch the values and want to re-render the component. I use setValue(). It works when called from a button onClick(). It does NOT when called from the component body. 

**To Reproduce**
1. Create two components, Component1 and Component2 inside a FormProvider. Component1 watches for a value using useWatch() and displays the value. Component2 registers a field, then sets the value, then displays the field and buttons.
2. In the component1 default value is displayed: 111.
3. setValue(222) in the component body is ignored, disregarding shouldDirty parameter.
3a. however if I run setValue(222) from useEffect() in component2, it works
3b. registering the field before both components are called does not help.
4. clicking on "SET" button changes Component1 display to 444.
5. clicking on "SET DEEP" button has no effect on Component1 display (is it correct? would be great if it worked).

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usewatch-forked-m7iiy

**Expected behavior**
I expect useWatch() to re-render the component ANY TIME the watched value changes.

**Desktop (please complete the following information):**

- OS: win10
- Browser FF
- Version 87

**Comment by bluebill1049** [comment]
> setValue(222) in the component body is ignored, disregarding shouldDirty parameter.
3a. however if I run setValue(222) from useEffect() in component2, it works
3b. registering the field before both components are called does not help.

do in `useEffect` is correct, input hasn't finish register with ref's callback.

looking into the 4 and 5 now.

**Comment by bluebill1049** [comment]
the only issue here is: 

```
<button
        onClick={() => {
          setValue("one.two", { dep: 333 });
        }}
      >
        set deep
</button>
```

looking into it now.

**Comment by serg-prasolov** [comment]
> do in `useEffect` is correct, input hasn't finish register with ref's callback.

what if I only register() a field (in App()), and have no actual <input> field at all?
https://codesandbox.io/s/react-hook-form-usewatch-forked-2zf56

**Comment by bluebill1049** [comment]
> > do in `useEffect` is correct, input hasn't finish register with ref's callback.
> 
> what if I only register() a field (in App()), and have no actual field at all?
> https://codesandbox.io/s/react-hook-form-usewatch-forked-2zf56
> 
> it also works with useEffect(), but register() should be completed already, no?

put setValue inside a `callback` or `useEffect`.
