### ISSUE TITLE
Watch and getValues don't return all fieldarray properties

### ISSUE THREAD

**Issue by woutkl** [react-hook-form/react-hook-form#4763]
**Describe the bug**
When registering a subset of the FieldArray values as inputs, neither watch nor getValues return all the necessary FieldArray values even though v7 is supposed to return unmounted input values as well.

**To Reproduce**

1. Go to https://codesandbox.io/s/pedantic-lamport-e8luy?file=/src/App.tsx
2. Open the console
3. The first console value will show both the _firstName_ and the _name_ property.
4. After that, all the console values will show only the mounted input value: _name_.
5. Type some characters to trigger new console updates.

**Codesandbox link (Required)**
https://codesandbox.io/s/pedantic-lamport-e8luy?file=/src/App.tsx

**Expected behavior**
Watch and getValues should return all the FieldArray properties. Instead of returning only the mounted input values, they should be merged with the defaultValues.

**Comment by bluebill1049** [comment]
We don't do deep merge, this is expected behavior.

**Comment by woutkl** [comment]
So, am I correct to say that it is no longer possible to retrieve all the field array values in v7 if only a subset of the field array values are registered to an input?

**Comment by bluebill1049** [comment]
Take a look at this section: https://react-hook-form.com/api/usefieldarray

<img width="950" alt="Screen Shot 2021-04-13 at 8 58 55 pm" src="https://user-images.githubusercontent.com/10513364/114542274-11f40200-9c9b-11eb-83f7-ee677ff62922.png">

you still can use customer register to embed those "hidden" inputs.
