### ISSUE TITLE
[V7] FileInput in <Controller /> component throws error about setting the value of a HTMLInputElement

### ISSUE THREAD

**Issue by SocialBrothersDEV** [react-hook-form/react-hook-form#4765]
**Describe the bug**
Since V7 i am not able to use a controller which controls my fileinput components. In V6 this implementation was working flawlessly. The error that i'm getting is the following: 
```
Uncaught DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.
```

**To Reproduce**

1. Make a controller component
2. Return a file input from the render method
3. Spread the `field` variable to the file input field.
4. Upload a file.

**Codesandbox link (Required)**
https://codesandbox.io/s/delicate-sound-19ufb?file=/src/App.tsx

**Expected behavior**
I am expecting for it to work as it did in V6, or that a valid alternative is provided. 

**Desktop (please complete the following information):**

- OS: MacOS
- Browser chrome
- Version  89.0.4389.114

**Additional context**
The use case for having a controller wrapping my fileInput is to only submit the first entry in the FileList.

**Comment by bluebill1049** [comment]
can you use the latest version? https://codesandbox.io/s/gallant-keldysh-muvu6?file=/src/App.tsx

**Comment by SocialBrothersDEV** [comment]
@bluebill1049 The default onChange is indeed working at the latest version now. I have now changed the codesandbox to my actual implementation that also causes the errror. See https://codesandbox.io/s/condescending-violet-60ct8?file=/src/App.tsx.

**Comment by bluebill1049** [comment]
have a read here: https://medium.com/trabe/controlled-file-input-components-in-react-3f0d42f901b8

the problem is value as FileList is not going to work with input's `value` prop.

**Comment by bluebill1049** [comment]
or simplify go with uncontrolled: `<input type="file" {...register('test')} />`

**Comment by dewaele-benoit** [comment]
I think if you use {...register('test')}, it should work but you have to use onChange and setValue :  
You can try something like this : 
```tsx
import * as React from "react";
import { useForm, Controller } from "./src";
import Headers from "./Header";
import "./styles.css";

type FormValues = {
  firstName: string;
};

let renderCount = 0;

export default function App() {
  const { handleSubmit, control, setValue } = useForm<FormValues>();
  const onSubmit = (data: FormValues) => console.log(data);
  renderCount++;
  const handleChange = (event: any) => {
              const file = event.target.files;
              setValue("firstName", file);
            };
  return (
    <div>
      <Headers
        renderCount={renderCount}
        description="Performant, flexible and extensible forms with easy-to-use validation."
      />

      <form onSubmit={handleSubmit(onSubmit)}>
        <Controller
          control={control}
          name="firstName"
          render={({ field }) => {
            return <input {...register("firstName")} onChange={handleChange} type="file" />;
          }}
        />
        <input type="submit" />
      </form>
    </div>
  );
}
```
