### ISSUE TITLE
reset() now sets all values in the formState, even when they are not registered as fields. 

### ISSUE THREAD

**Issue by SocialBrothersDEV** [react-hook-form/react-hook-form#4766]
**Describe the bug**
RHF V7 automatically unregistered registers fields when reset() is being called with unknown fields. 

In v6, when i reset the form with values that weren't registered, the formState would not include them. Since v7, formValues are automatically registered when i reset the form with the response from the API. The reason i am resetting the form with API values is because there is no other method that allows me to set very complex data structures at once. An alternative would be to write a recursive function that formats an final `name` prop derived from the model and calls `setValue()` with it, but in the current project scope that is not possible.

**To Reproduce**

1. Register a form with only one key
2. Call reset() with an object that contains more keys then the single registered key
3. Submit the form
4. The final submit values will contain values that have not been registered.

**Codesandbox link (Required)**
https://codesandbox.io/s/snowy-star-5yu8w?file=/src/App.tsx

**Expected behavior**
I would expect one of the following: 
- Unregistered fields would not get registered automatically.
- The reset() function would have an extra argument disabling automatic registering of fields.
- RHF would export a function dedicated for setting a whole formState instead of single setValue() methods, eg. setFormValue(). 
- RHF would supply and alternative, easy way to set complex data structures in forms at once. 

**Desktop (please complete the following information):**

OS: MacOS
Browser chrome
Version 89.0.4389.114

**Additional context**
Our use case is the following: we are building a CRUD dashboard. Whenever a model is being edited, our application fetches that model on the detail page. The form has already been rendered then, so whenever the API data comes in, we are resetting the form with the actual values. 

An alternative i tried is not rendering the form until API data has been fetched and then render the form with the API data as `defaultValues` but that results in exactly the same issue.

**Comment by bluebill1049** [comment]
This is not a bug rather intended behavior for V7, i would exclude those additional results from the reset API.

**Comment by SocialBrothersDEV** [comment]
@bluebill1049 For our case that would not work, since we are building a CRUD-template in which the form is unaware of the values it will receive. Should i submit a PR for adding an option `shouldAutoRegister` which will checked at `useForm.tsx:477` ?

**Comment by mart-jansink** [comment]
@bluebill1049 is this also the intended behaviour for nested fields? Because that doesn't seem to work, neither with the `defaultValues` nor with `reset()`, see https://codesandbox.io/s/brave-brown-x8vsu?file=/src/App.tsx.

**Comment by bluebill1049** [comment]
> @bluebill1049 For our case that would not work, since we are building a CRUD-template in which the form is unaware of the values it will receive. Should i submit a PR for adding an option `shouldAutoRegister` with `true` as default value which will be checked at `useForm.tsx:477` ?

please stay at v6, if v7 is not working out for you as V6 is still maintained.

**Comment by bluebill1049** [comment]
> @bluebill1049 is this also the intended behaviour for nested fields? Because that doesn't seem to work, neither with the `defaultValues` nor with `reset()`, see https://codesandbox.io/s/brave-brown-x8vsu?file=/src/App.tsx.

more details and steps to reproduce, your codesandbox is the same as what the author provided.

**Comment by mart-jansink** [comment]
Apologies, my bad, please see https://codesandbox.io/s/peaceful-tdd-5gsql. The top-level `age` property is added to data provided to the `onSubmitHandler`, but the `name.last` property isn't. For neither of them an input was registered. Removing the `React.useEffect` block, that resets the data, shows the same result when just using `defaultValues`.

**Comment by bluebill1049** [comment]
@mart-jansink take a look this issue: https://github.com/react-hook-form/react-hook-form/issues/4771

**Comment by mart-jansink** [comment]
Ah, I now see that it's the same issue, I hadn't gotten that from its description. Since you only shallow-merge the `defaultValues` you're saying that it's the intended behaviour? If so then I will have to work around it with extra `register()` calls, but it does feel a bit inconsistent to me.
