### ISSUE TITLE
💅🏻 material-ui: reset, setValue and defaultValues (better support uncontrolled components)

### ISSUE THREAD

**Issue by LeoLozes** [react-hook-form/react-hook-form#477]
**Describe the bug**
I'm trying to do a simple form with react-hook-form and material-ui. I'd like to be able to:
1. submit / validate a form
2. reset the form correctly
3. load data correctly

The first step works correctly. 
The reset function clears the value, but the state of the material-ui TextField seems to stay at "filled", and the styles don't match with the cleared data. 
The reset function with initial values set correctly the value, but the behavior is the same as with reset (well, the opposite in this case), the data is loaded but the internal state of the TextField is not "filled". 

**To Reproduce**
You can try the three buttons on this CodePen:
https://codesandbox.io/s/material-demo-ywutu

1. Submit: works correctly validating the data.
2. Correctly resets but the state of the TextFields is not empty. 
3. Correctly loads data but the state of the TextFields is not filled. 

**Expected behavior**
The empty TextField should have the label as placeholder, and the filled TextField should have the label move on top of the data.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge Chromium

**Comment by bluebill1049** [comment]
React hook form embrace uncontrolled components. The reset api is based on native form reset API. However material UI is mainly supporting controlled component which result reset to be not working as expected. I would suggest to raise an issue at material UI. In the meantime you probably will need to use local state to solve this issue during reset action.

**Comment by bluebill1049** [comment]
thanks @LeoLozes for raising the issue at MUI, I am keeping my eyes on it as well :)

**Comment by bluebill1049** [comment]
If you having similar issue with material-UI, please consider upvote this issue:

https://github.com/mui-org/material-ui/issues/18269

**Comment by bluebill1049** [comment]
Going to close this issue, but I did pin it on the board, and more people can vote on the issue :)

**Comment by man-trifork** [comment]
@bluebill1049 This is still relevant with the latest stable version. What can we do to workaround?

https://codesandbox.io/s/material-demo-wnmog?file=/demo.js

Thanks in advance!

**Comment by bluebill1049** [comment]
@man-trifork please use Controller: https://react-hook-form.com/api#Controller

https://codesandbox.io/s/react-hook-form-controller-079xx

**Comment by man-trifork** [comment]
@bluebill1049 Unfortunately it doesn't work either:

https://codesandbox.io/s/material-demo-wnmog?file=/demo.js

Do I miss something?

**Comment by bluebill1049** [comment]
@man-trifork please take a look my reply above with that Codesandbox.

**Comment by Idonoghue** [comment]
I'm still getting this problem using the controller. It is setting the form value but it doesn't trigger 'filled' for MUI. See this sandbox: https://codesandbox.io/s/example-muitextfield-setvalue-with-react-hook-form-forked-dvhr9

**Comment by bluebill1049** [comment]
> I'm still getting this problem using the controller. It is setting the form value but it doesn't trigger 'filled' for MUI. See this sandbox: https://codesandbox.io/s/example-muitextfield-setvalue-with-react-hook-form-forked-dvhr9

Take a look at this CSB (in the doc): https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r

**Comment by Idonoghue** [comment]
Thanks for the prompt reply! Yea my main problem for this issue was not setting defaultValues for useForm.

**Comment by totongcute** [comment]
[](https://github.com/mattermost/mattermost-mobile)

**Comment by sgentile** [comment]
so the sandbox code works with 'as' but using 'render' it does not work - as seems easier to use but react-hook-forms appears to be sunsetting as

**Comment by sgentile** [comment]
as an example:

'as' properly sets the default value and reset works:

```
<Controller
                                                                                        as={
                                                                                            <Select>
                                                                                                <MenuItem value="KY">
                                                                                                    Kentucky
                                                                                                </MenuItem>
                                                                                                <MenuItem value="IN">
                                                                                                    Indiana
                                                                                                </MenuItem>
                                                                                                <MenuItem value="OH">
                                                                                                    Ohio
                                                                                                </MenuItem>
                                                                                            </Select>
                                                                                        }
                                                                                        defaultValue={
                                                                                            data.organization.state
                                                                                        }
                                                                                        name="state"
                                                                                        control={control}                                                                                       
                                                                                    />
```

convert it to render

```
<Controller
                                                                                        
                                                                                        defaultValue={
                                                                                            data.organization.state
                                                                                        }
                                                                                        name="state"
                                                                                        control={control}
                                                                                        render={() => (
                                                                                            <Select>
                                                                                                <MenuItem value="KY">
                                                                                                    Kentucky
                                                                                                </MenuItem>
                                                                                                <MenuItem value="IN">
                                                                                                    Indiana
                                                                                                </MenuItem>
                                                                                                <MenuItem value="OH">
                                                                                                    Ohio
                                                                                                </MenuItem>
                                                                                            </Select>
                                                                                        )}
                                                                                    />
```
default value nor reset works

**Comment by mstruensee** [comment]
has there been a workaround for this? still is an issue ... 
using Controller or register, issue still exists.

**Comment by Idonoghue** [comment]
> has there been a workaround for this? still is an issue ...
> using Controller or register, issue still exists.
> 
> yes, setting defaultValues work in useForm, but one has none, then does API call to get them, and use reset to trigger the update of the new values ... the new values are set but "filled" is not triggered for MUI.

When you say "one has none" do you mean you have no defaultValues on mount? Typically if I want to initialize the form to values from an API I will still set defaultValues as empty strings or just a filler value until the API call completes triggering the reset to refill the form with the API values.

**Comment by mstruensee** [comment]
yup, that is what I have currently ...
`  const defaultValues = {
    title: '',
    ...data
  }`

**Comment by mstruensee** [comment]
I got a working example ... not sure how it is for best practices but it's working  
I ended up using the FormProvider/useFormContext with reset and Controller/controller

`fancy-form-component.js`
```  
export const FancyFormComponent = () => {
  const onSubmit = data => console.log('onSubmit', data)
  const handleClose = () => console.log('handleClose')

  const { data  } = useFetch(url)

  const defaultValues = {
    title: '', // <-- this is required, cannot be undefined, else "filled" not called ... 🤷 
    ...data
  }

  return (
    <>
      <FormComponent defaultValues={defaultValues} onSubmit={onSubmit} handleClose={handleClose}>
        <Grid container spacing={2}>
          <Grid item xs={12} sm={6}>
            <TitleComponent/>
          </Grid>
        </Grid>
      </FormComponent>
    </>
  )
}
```

`form-component.js`
```
export const FormComponent = ({ defaultValues, handleClose, onSubmit, children }) => {
  const methods = useForm({ defaultValues })

  const {
    handleSubmit,
    reset,
  } = methods

  useEffect(() =>  reset(defaultValues), [ defaultValues ])

  return (
    <FormProvider {...methods}>
      <form onSubmit={handleSubmit(onSubmit)}>
        {children}
        <div>
          <Button variant={'contained'} onClick={handleClose}>
            Cancel
          </Button>
          <Button type={'submit'} variant={'contained'}>
            Save
          </Button>
        </div>
      </form>
    </FormProvider>
  )
}

```
`title-component.js`
```
export const TitleComponent = ({ inputProps, ...rest }) => {
  const { control } = useFormContext()

  return (
    <Controller
      name={"title"}
      control={control}
      rules={{ required: 'Title is a required field.' }}
      render={({ field, fieldState }) => {
        const { error: { message } = {} } = fieldState
        return (
          <TextField
            {...field}
            inputProps={inputProps}
            error={!!message}
            helperText={message}
            {...rest}
          />
        )
      }}
    />
  )
}
```

**Comment by Idonoghue** [comment]
I personally think initializing a defaultValue for a field makes sense intuitively. It essentially 'registers' a controlled component with RHF. [From the docs](https://react-hook-form.com/api/useform): 

>The defaultValues for inputs are used as the initial value when a component is first rendered, before a user interacts with it. It is >encouraged that you set defaultValues for all inputs to non-undefined values such as the empty string or null.
