### ISSUE TITLE
v7 hidden fields are unregistred after rerender

### ISSUE THREAD

**Issue by loun4** [react-hook-form/react-hook-form#4771]
**Describe the bug**
When a `{...register('name')}` is called, hidden fields are unregistered after the Form rerender. 

**To Reproduce**

1. Go to the code sandbox
2. Open console
3. First render log `[]` for `getValues("specs.list")` 
4. Second render log `undefined` instead of `[]`

**Codesandbox link (Required)**
https://codesandbox.io/s/nice-swanson-pls4o?file=/src/App.js

**Expected behavior**
According to https://github.com/react-hook-form/react-hook-form/issues/4416 the expected behavior should be similar to v6 `shouldUnregister: false` option.

**Comment by bluebill1049** [comment]
we are doing a shallow merge against `defaultValues`, in your use case

```
const data = {
  specs: {
    list: [],
    name: ""
  }
}
```

then after register

```
const data1 = {
  specs: {
    name: ""
    // list gone missing
  }
}
```

shallow merge
```
{
  ...data,
  ...data1,
}
```

and return 


```
const data1 = {
  specs: {
    name: ""
    // list gone missing
  }
}
```

using a hidden input or custom register to store that missing field value.
