### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by tbuglc** [react-hook-form/react-hook-form#4773]
Just experiencing some typescript issue that I can tell what's wrong, details below.

Errors: 
<img width="957" alt="Screen Shot 2021-04-13 at 6 12 59 PM" src="https://user-images.githubusercontent.com/19764908/114585856-5cb64f80-9c84-11eb-87fe-b10a36435a12.png">

Form:

<img width="674" alt="Screen Shot 2021-04-13 at 6 17 20 PM" src="https://user-images.githubusercontent.com/19764908/114586050-8a9b9400-9c84-11eb-9bb7-9940c2fa1955.png">
<img width="674" alt="Screen Shot 2021-04-13 at 6 17 31 PM" src="https://user-images.githubusercontent.com/19764908/114586086-92f3cf00-9c84-11eb-954c-eab1b62e3c0d.png">

**Comment by tbuglc** [comment]
I'm using v7.0.7, sorry I forgot to mention that.

**Comment by tamagokun** [comment]
I ran into the same thing, I had to upgrade to the latest version of typescript and all was good.

**Comment by pesachoice** [comment]
Oh thanks, lemme try that and see

**Comment by tbuglc** [comment]
Thank you @tamagokun it fixed the issue
