### ISSUE TITLE
v7 useWatch with useFieldArray and controlled input with unregister

### ISSUE THREAD

**Issue by orenklein** [react-hook-form/react-hook-form#4777]
**Describe the bug**
When using a controller with `unregister` on unmount under array field, `useWatch` does not return the correct value after remove.

**To Reproduce**

1. Go to codesandbox
2. Click on remove for the second item
3. All the items below it will get empty watch value

**Codesandbox link (Required)**
https://codesandbox.io/s/intelligent-sea-ygfd5?file=/src/App.js

**Expected behavior**
Watch value should not be lost

**Desktop (please complete the following information):**

- OS: windows
- Browser: chrome
- Version:  89.0.4389.114 

**Additional context**
It is probably happening because unregister is executed after remove is called for the same path.

**Comment by bluebill1049** [comment]
This is due to `unrgister` is removing all the input during the shuffle.

```
React.useEffect(() => {
    console.log('name', name)
    return () => unregister(name);
}, [unregister, name]);
```
