### ISSUE TITLE
v7.0.7 dirtyFields are not reflected

### ISSUE THREAD

**Issue by haruhikonyan** [react-hook-form/react-hook-form#4778]
**Describe the bug**
v7.0.7 dirtyFields are not reflected at the first time

**To Reproduce**

1. Go to codesandbox
2. Change input on First Name field
3. Click on Submit
4. See console
    - First Name don't  show console.log as dirtyFields
5. Again change input on First Name field
    - First Name show console.log as dirtyFields

- If display dirtyFields, the log will be displayed
    - codesandbox line 28 comment out

**Codesandbox link (Required)**
https://codesandbox.io/s/gallant-agnesi-lxbvu

**Expected behavior**
Console.log is displayed on the first input

**Screenshots**
- ![18cbcc4f9af3a5530242670ffafbc757](https://user-images.githubusercontent.com/16318813/114639865-d3496080-9d09-11eb-9a7b-76e08f2d4675.gif)

**Desktop (please complete the following information):**

- OS: windows
- Browser: chrome
- Version: 89.0.4389.114

**Comment by bluebill1049** [comment]
`const { register, handleSubmit, formState, formState: {dirtyFields} } = useForm<FormValues>();`

<img width="954" alt="Screen Shot 2021-04-14 at 11 17 44 am" src="https://user-images.githubusercontent.com/10513364/114640251-0b08d600-9d13-11eb-99b2-5afad23a54e0.png">
