### ISSUE TITLE
unexpected behavior with formState.errors object

### ISSUE THREAD

**Issue by oziged** [react-hook-form/react-hook-form#4779]
**Describe the bug**
I have some big form and trying to avoid too often rerenders. 
According to docs ([context performance](https://react-hook-form.com/advanced-usage#FormProviderPerformance)). I tried to repeat your example, but in my situation I have **'onTouched'** form and **formState.isDirty check** in "React.memo" is not enough. 

I'm trying to compare here **'formState.errors'** object from **prevProps** and **nextProps** (because I have to rerender component when it's errors changes). 
But as result, in prevProps and nextProps all the time I get same objects (if some errors appeared, it's already in **prevProps.formState.errors**)

That's maybe a little bit strange example, but in my real situation I have some parent component with two useForm() hooks.
This parent component contains 2 child form components and passes error objects and to the first, and to the second child component. And if there is some error happened in first useForm, I didn't have to update second form (but because of same formState.errors in prevProps and nextProps, it rerenders) 

`const Parent = () => (`
  `const form1 = useForm()`
  `const form2 = useForm()`
  
  `<ChildForm1 {...form1}/>`
  `<ChildForm2 {...form2}/>`
`)`

**To Reproduce**

1. Go to '[sandbox](https://codesandbox.io/s/provider-perf-forked-xv3xd?file=/src/App.js)'
2. Blur input (to start onChange validation)
3. Change input value from empty string to anything and in console you'll see result of equality function, which get already updated props.

**Codesandbox link (Required)**
[https://codesandbox.io/s/provider-perf-forked-xv3xd?file=/src/App.js](https://codesandbox.io/s/provider-perf-forked-xv3xd?file=/src/App.js)

**Expected behavior**
formState.errors object in prevProps and nextProps must be different

**Comment by bluebill1049** [comment]
This is not a bug, and use `useFormState`.

**Comment by oziged** [comment]
I tried to use useFormState, but couldnt' achive needed result. 

I have some ChildForm1/ChildForm2 components where I'm doing comparison of **prevProps** and **nextProps** in **React.memo** function, and it works good in situation when we trying to compare some simple types (isDirty (boolean), for example). I check prevProps.isDirty === nextProps.isDirty and if it changed - everything re-renders, it's fine. 

But when I'm trying to compare some objects (errors), in prevProps.errors I already get next value of this prop and _isEqual(prevProps.errors, nextProps.errors) or JSON.stringify are equal all the time.

Сan you please tell me where I can be wrong? Because I can't guess how to do it more correctly.

Here's some another demo that looks like my simplified form: [sandbox](https://codesandbox.io/s/provider-perf-forked-heedm?file=/src/App.js)
