### ISSUE TITLE
Nested useFieldArray items disappear on move()

### ISSUE THREAD

**Issue by tzarger** [react-hook-form/react-hook-form#4786]
When using nested useFieldArray, if you use move() after a couple times in v6.15.5 and on first move in v.7.0.7 the nested useFieldArray items disappear. Also, when appending an item in v6.15.5, the nested useFieldArray Person is not added.

**Codesandbox for v6.15.5**
[https://codesandbox.io/s/react-hook-form-usefieldarray-forked-v6155-u5n62
](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-v6155-u5n62)

1. Click the Move Button twice. Or move drag and drop the section twice.
2. Refresh to start over, Click on Append, notice the nested person is not showing or added.

**Codesandbox for v7.0.7**
[https://codesandbox.io/s/react-hook-form-usefieldarray-forked-v707-bsurb](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-v707-bsurb)

1. Click the Move Button once. Or move drag and drop the section once.
2. Refresh to start over, Click on Append, person is correctly added, whereas in v6.15.5 it is not working correctly.

**Browser Info**
- OS: MacOS
- Browser Chrome
- Version 89.0.4389.114

**Comment by bluebill1049** [comment]
I wouldn't be able to help on this one, as it a dependency on another library. If you can reproduce the issue without the dependency i can investigate for the issue.

**Comment by tzarger** [comment]
@bluebill1049 No worries. I found a work-around... don't use useFieldArray() on the nested items seems to work. Simply send in the person to the Nested component. I updated the codesandbox:

[https://codesandbox.io/s/react-hook-form-usefieldarray-forked-v6155-u5n62](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-v6155-u5n62)
