### ISSUE TITLE
Support "register" design as it was at version 6 🙏 

### ISSUE THREAD

**Issue by finom** [react-hook-form/react-hook-form#4791]
**Is your feature request related to a problem? Please describe.**
I have a ton of code that uses `register` passed as field's `ref`. Me and I suppose many other developers would prefer to keep this logic and make some minor changes provided by the version 7 (like useForm options).

Personally I have to request additional budget to make the migration, but as you know clients, managers and project owners are not getting happier if you propose to make some additional "code stuff". I work on 3 apps at the same time and all of them use react-hook-form heavily. One of the apps is a one huge multi step form. Since market requirements are more important than my own preferences I have to keep version 6 forever. 

Another issue (but much less important though) I'm facing is this ESLint rule https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-props-no-spreading.md. Spreading is an anti-pattern, at the same time react-hook-form requires me to disable it. The only alternative is to create a lot of variables (name of this, ref of that) at multi-filed components.

**Describe the solution you'd like**
I propose to keep the version 7 logic but make possible to keep `register` as is if code was made with version 6. The solution is to keep `register` as a function (v6 logic) but enhanced with the "spreadable" properties (v7 logic).

Another alternative is to create additional `useForm` property called `registerRef` or similar that follows the v6 logic. It's easier to rename something than making major and bug-sensitive changes.

**Comment by finom** [comment]
Sorry guys, submitter early. Making updates...

**Comment by bluebill1049** [comment]
v6 is still under-maintained, and you can safely keep using v6. I don't think we will go back to the old syntax. 🙏 hope for your understanding.
