### ISSUE TITLE
V6: useFieldArray with nested useFieldArray renders with fields [empty]

### ISSUE THREAD

**Issue by bjarkehs** [react-hook-form/react-hook-form#4792]
**Describe the bug**
I experience that when I add an entry to a field array with a nested field array and remove it again. Then I get 2 renders of my outer field array. One with `[]` (length 0) and afterwards one with `[empty]` (length 1). Then my application crashes since it can't get the id of undefined.

This is the data I can see with the React Components DevTools:

![image](https://user-images.githubusercontent.com/2279254/114721418-31416c80-9d39-11eb-8d41-dde29ee66922.png)

The issue only exists in v6. Not in v7.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-xif3x
2. Click on append
3. Click on delete
4. Click on submit
5. Click on append
6. See that it crashes

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-xif3x

**Expected behavior**
The field array does not contain empty values.

**Comment by bluebill1049** [comment]
I probably going to need a reproducible CSB in order to investigate and provide a solution in v6.

**Comment by bjarkehs** [comment]
@bluebill1049 https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-xif3x?file=/src/fieldArray.js

Steps to reproduce (I'll also update the main issue):
Click append
Click delete
Submit
Click append

This is the same bug I experience. But for some reason mine happens also on:
Append -> Delete -> Append

Whereas the codesandbox I linked to needs the submit before it breaks.

**Comment by bluebill1049** [comment]
<img width="410" alt="Screen Shot 2021-04-15 at 7 59 01 pm" src="https://user-images.githubusercontent.com/10513364/114851298-07657400-9e25-11eb-8475-9d8f379c3c83.png">

none of those input r registered.

**Comment by bjarkehs** [comment]
They should be. `<Input>` is a custom component that uses `useController`.

**Comment by bimbeonguyen** [comment]
Hello @bluebill1049, this bug is still existing. Step to reproduce: 
Append -> Append -> Append -> Delete first, second item => the fields return [object, empty]
Append -> Append -> Append -> Delete first, second and third item => the fields return [empty, empty, epmty]

https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-xif3x

**Comment by bluebill1049** [comment]
Thanks @bimbeonguyen i will take a look at it tonight.

**Comment by bluebill1049** [comment]
patched again with latest v6.
