### ISSUE TITLE
V7: Trigger validation with return

### ISSUE THREAD

**Issue by bjarkehs** [react-hook-form/react-hook-form#4793]
**Is your feature request related to a problem? Please describe.**
We have a blocker before we can upgrade to v7. We currently have some code that looks like this:

```javascript
const onClick = async () => {
  const valid = await inputForm.trigger();
  if (!valid) {
    return;
  }
  const data = inputForm.getValues();
  // use data
}
```

We are currently unable to move to v7 since I cannot figure out how to do this in v7.

**Describe the solution you'd like**
Some way to trigger validation and get the result back.

**Describe alternatives you've considered**
None

**Comment by bluebill1049** [comment]
You can subscribe to the `errors` object with `useFormState` as an alternative.

**Comment by bjarkehs** [comment]
Subscribing to errors is unfortunately not enough, since the changes to errors don't occur until next render. So I can't trigger validation, wait for it, check if everything is valid, and then perform some action.

My use case is I have some button that uses the form data outside of submission.

**Comment by lynxtaa** [comment]
@bjarkehs I think you can use `handleSubmit`:

```ts
const onClick = handleSubmit(
  values => {
    // ...
  }
)
```

**Comment by bjarkehs** [comment]
@lynxtaa That could be a solution, but I need to also be able to only trigger validation on certain inputs.

So my example above is more like:

```javascript
const onClick = async () => {
  const valid = await inputForm.trigger(paths);
  if (!valid) {
    return;
  }
  const data = inputForm.getValues();
  // use data
}
```
