### ISSUE TITLE
V7: isValid is false for valid form

### ISSUE THREAD

**Issue by lynxtaa** [react-hook-form/react-hook-form#4795]
**Describe the bug**
After resetting the form `isValid` should be `true` since there are no errors and form is valid.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-isvalid-5broc?file=/src/App.tsx
2. See `isValid: false`

**Comment by bluebill1049** [comment]
`onBlur={field.onBlur}` was missing :)

**Comment by lynxtaa** [comment]
@bluebill1049 I'm not sure it's the case. Even after adding `onBlur` and touching the field `isValid` is `false`

**Comment by bluebill1049** [comment]
oops my assumption was wrong then... will look into this.
