### ISSUE TITLE
V7: FileList returned as empty on safari

### ISSUE THREAD

**Issue by defless** [react-hook-form/react-hook-form#4799]
I use react hook form to import jpeg/png on a web app without any issues on chrome. I wanted to try it on safari on my mobile phone (see more infos at the end of this message). But each time I submit my form, the fileList is returned as empty. The same on my laptop safari. 

as you can see below : 
<img width="304" alt="Capture d’écran 2021-04-14 à 23 23 55" src="https://user-images.githubusercontent.com/43884154/114781377-df203b80-9d78-11eb-91cb-096b54704e21.png">

but if I log the `event.target.files[0]` triggered by the onChange of my `<input type="field ...` I got the following as expected :

<img width="696" alt="Capture d’écran 2021-04-14 à 23 40 37" src="https://user-images.githubusercontent.com/43884154/114784052-f3653800-9d7a-11eb-966f-efc799f804f3.png">

In comparison with the same exact file on chrome: 

![Capture d’écran 2021-04-14 à 23 42 17](https://user-images.githubusercontent.com/43884154/114784131-12fc6080-9d7b-11eb-9460-487cbabf53d8.png)

**Desktop:**

- OS: Mac OS Big Sur (11.2.3)
- Browser: Safari
- Version: 14.0.3

**Smartphone:**

- Device: iPhone Xr
- OS: iOS (14.4.2)
- Browser Safari

**Comment by bluebill1049** [comment]
can you please provide a CSB?

**Comment by defless** [comment]
Here it is: https://codesandbox.io/s/rhf-fieldlist-issue-68flr

**Comment by bluebill1049** [comment]
<img width="1093" alt="Screen Shot 2021-04-15 at 7 44 04 pm" src="https://user-images.githubusercontent.com/10513364/114849282-f156b400-9e22-11eb-9a95-ab0380cda155.png">

pass `onChange` solve the problem for me in safari.
