### ISSUE TITLE
Controller and unregister not working as expect

### ISSUE THREAD

**Issue by huynd0902** [react-hook-form/react-hook-form#4803]
**Describe the bug**
I use react-hook-form V7.1.0 try to unregister a field but it seem not working as my expect.

**To Reproduce**

1. Go to link Code sandbox
2. Click on Click on button submit see console log
3. Click on Unregister First name button and hit button submit again. It still not remove the field first name.

**Codesandbox link**
https://codesandbox.io/s/busy-franklin-3p5z6

This is expect behavior of lib or a bug. Please help me figure out. Thanks

**Comment by bluebill1049** [comment]
Your `Controller` still present, so next re-render it will get registered again.

**Comment by huynd0902** [comment]
I have update the code. Even I remove the field from dom. It not working as my expect.

**Comment by bluebill1049** [comment]
please have a test: https://codesandbox.io/s/snowy-framework-expgh

**Comment by huynd0902** [comment]
Sr but I see no different. First I submit with empty input and get errors as expect. After that I unregister field first name and expect that when I fill the rest input. I'll submit success but still getting error. Please see image bellow
![test](https://user-images.githubusercontent.com/62128897/114827035-66f65c00-9df2-11eb-9390-72828cb39402.PNG)

**Comment by bluebill1049** [comment]
isn't that due to your schema on the top? the input is definitely got unregistered and remove, you can use watch to test it out.
```
const validationSchema = yup.object().shape({
  firstName: yup.string().required("First Name Required"),
  lastName: yup.string().required("Last Name Required")
});
```

**Comment by huynd0902** [comment]
Yes I can see the ref was removed. But currently I haven no idea how to work around with this. Not sure about place the schema on the top is the cause. But it as a normal. I think react-hook-form should work with this situation. Do you have any idea work around for this issue? Thanks

**Comment by bluebill1049** [comment]
you can use `context` to switch your schema or make it conditional.

**Comment by huynd0902** [comment]
I was used condition for schema and it working. But it not convenient. I need define schema again and again when I unregister a field. I think that not a good idea. Please see the code https://codesandbox.io/s/amazing-fast-p3iod?file=/src/App.js

**Comment by bluebill1049** [comment]
1. there is no bug with `unregsiter`as what this issue was reporting.
2. as much as I want to make all use case as pleasant as possible, there will always go to be possible for your to tweak around to suit your use case.

so if there is no bug with unregister, I am going to close this issue. you can submit a separate feature request with a good proposal and we will wait for the community to vote and seek a solution.
