### ISSUE TITLE
IE11 bug, no support `document.contains`

### ISSUE THREAD

**Issue by ikun** [react-hook-form/react-hook-form#4809]
https://github.com/react-hook-form/react-hook-form/blob/dd1924d4f22e03b84f47e6b52f1e666a70068e74/src/useForm.ts#L892

change `document.contains` into `document.body.contains`

**Comment by bluebill1049** [comment]
we have dropped IE 11 support, thanks for the tip 👍

**Comment by IanVS** [comment]
It would probably be good to mention that in the release notes:  https://github.com/react-hook-form/react-hook-form/releases/tag/v7.0.0 (along with any other breaking changes).

**Comment by bluebill1049** [comment]
> It would probably be good to mention that in the release notes: https://github.com/react-hook-form/react-hook-form/releases/tag/v7.0.0 (along with any other breaking changes).

look at the changelog for all the breaking changes, i will include the ie11 part too.
