### ISSUE TITLE
validationSchema not working with material ui

### ISSUE THREAD

**Issue by julian-linux** [react-hook-form/react-hook-form#481]
**Describe the bug**
When i use `useForm({ validationSchema })`, handleSubmit is not called in a material-ui TextField

**To Reproduce**
1. click on SEND

**Codesandbox link**
https://codesandbox.io/s/staging-moon-hi7hc

**Expected behavior**
data and errors logged

**Comment by JeromeDeLeon** [comment]
It is because the default `mode` is `onSubmit` and will be triggered validation when form was submitted.

**Comment by JeromeDeLeon** [comment]
Have you seen the this [API](https://react-hook-form.com/api#useForm) section? You can set `mode` and `reValidateMode`.

**Comment by julian-linux** [comment]
tnks for help 👍

**Comment by bluebill1049** [comment]
thanks @JeromeDeLeon ❤️
