### ISSUE TITLE
"latest" tag should point to version 7

### ISSUE THREAD

**Issue by s-KaiNet** [react-hook-form/react-hook-form#4810]
**Describe the bug**
[Migration guide](https://react-hook-form.com/migrate-v6-to-v7/) says you should install the latest version `npm i react-hook-form@latest`.    
However, the `latest` tag still points to version 6 of the package: 

![image](https://user-images.githubusercontent.com/10658276/114863967-19c9b880-9df9-11eb-8bb1-3a1454f0c06a.png)

**Comment by bluebill1049** [comment]
This is an issue when we try to maintain two major versions, happy for any good suggestion. For now we will have to release another release to overwrite the @latest

**Comment by bluebill1049** [comment]
releases latest 7 to overcome this issue.
