### ISSUE TITLE
Semantic, Accessible HTML: Registering a 'checkbox' is decoupled from its label

### ISSUE THREAD

**Issue by MartinDM** [react-hook-form/react-hook-form#4811]
**Description**

When registering a checkbox, it is missing an `id` attribute, having only a `name`, meaning that clicking the associated registered `<label>` does not activate it.

This makes for reduced accessibility, as users cannot click the <label> unless the developer has wrapped the associated <input> with it, but this should not be relied upon as being the case as this is not necessarily a semantic requirement. Having a corresponding Id is.

**Sandbox example**
https://codesandbox.io/s/react-hook-form-get-started-forked-3hdu5?file=/src/index.js

**To Reproduce**

- Define a label and corresponding input of type `checkbox` eg.
```
<label htmlFor="showAge">Show age?</label>. 
<input type="checkbox" { ...register("showAge") } />
```
- Inspect resulting HTML
- See that the rendered checkbox has a `name` but no `id` as seen with `text` inputs, which connect their labels to the input
- Clicking the checkboxes' <label> area does **not** activate its checkbox

**Expected behavior**
1. Clicking the Label activates the associated checkbox input, linked with an `id` attribute matching the `htmlFor` specified on the label
2. Registered checkbox input has both `name` and `id` attributes

**Screenshots**
![image](https://user-images.githubusercontent.com/7467069/114866874-02380300-9dec-11eb-9708-f26c860de574.png). 
See DOM structure missing an `id` on the checkbox input.

**Comment by bluebill1049** [comment]
<img width="762" alt="Screen Shot 2021-04-15 at 10 51 16 pm" src="https://user-images.githubusercontent.com/10513364/114871888-1a843e00-9e3d-11eb-8b28-a50b4875afdf.png">

we don't pass `id` as `prop`, you will have to pass id yourself.
