### ISSUE TITLE
Validation not working after submiting form with 'onTouched' mode

### ISSUE THREAD

**Issue by oziged** [react-hook-form/react-hook-form#4821]
**Describe the bug**
When using the 'onTouched' mode and useFieldArray, after submitting the form, if you append a new field, click outside of it - the validation will not work.

**To Reproduce**

1. Go to '[https://codesandbox.io/s/provider-perf-forked-xv3xd?file=/src/App.js](https://codesandbox.io/s/provider-perf-forked-xv3xd?file=/src/App.js')
2. Add input and click outside => an error has appeared
3. Submit form
4. Add input and click outside => there is no error

**Codesandbox link (Required)**
[https://codesandbox.io/s/provider-perf-forked-xv3xd?file=/src/App.js](https://codesandbox.io/s/provider-perf-forked-xv3xd?file=/src/App.js)

**Expected behavior**
After submitting form, adding input again, triggering onBlur => error should appear

**Video**
https://user-images.githubusercontent.com/51995357/114949409-a73cf500-9e59-11eb-9a74-1c67afb7f719.mp4

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Chrome
- Version 87

**Comment by JamesWong1999** [comment]
https://react-hook-form.com/api/useform

reValidateMode: onChange | onBlur | onSubmit = 'onChange'

doesn't support `onTouched`.

**Comment by bluebill1049** [comment]
This could be a feature request.

**Comment by oziged** [comment]
> This could be a feature request.

Do I need to do something to turn this to feature request?

**Comment by bluebill1049** [comment]
Please submit a feature request instead @oziged. will include that in the back log for community to upvote.
