### ISSUE TITLE
Controller & control should not be triggered validation when its removed from the dom (Version 7)

### ISSUE THREAD

**Issue by liho00** [react-hook-form/react-hook-form#4822]
**Describe the bug**
The controller & control validate the fields that has been removed from the dom based on watching select value.

**To Reproduce**
```
 {watchBusinessOwnerForm("idType") === "PASSPORT" && (
                      <div class="flex items-start justify-between space-x-6">
                        <Controller
                          control={controlBusinessOwnerForm}
                          rules={{ required: "This field is required" }}
                          name="beginDate"
                          defaultValue=""
                          render={({
                            field: { ref, ...props },
                            fieldState: { invalid, error },
                          }) => (
                            <TextField
                              {...props}
                              type="date"
                              InputLabelProps={{
                                shrink: true,
                              }}
                              inputRef={ref}
                              error={invalid}
                              helperText={invalid ? error.message : ""}
                              className="w-full"
                              label="Passport date of issue"
                            />
                          )}
                        />

                        <Controller
                          control={controlBusinessOwnerForm}
                          rules={{ required: "This field is required" }}
                          name="endDate"
                          defaultValue=""
                          render={({
                            field: { ref, ...props },
                            fieldState: { invalid, error },
                          }) => (
                            <TextField
                              {...props}
                              type="date"
                              InputLabelProps={{
                                shrink: true,
                              }}
                              inputRef={ref}
                              error={invalid}
                              helperText={invalid ? error.message : ""}
                              className="w-full"
                              label="Passport date of expiry"
                            />
                          )}
                        />
                      </div>
                    )}
```
**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

**Expected behavior**
Its should not validate those fields that has been removed from the dom, its should work as v6. After the field add back only will be trigger the validation rules.

**Comment by bluebill1049** [comment]
We are working on a feature for this.

**Comment by liho00** [comment]
> We are working on a feature for this.

this is a feature? I though it was a bug....

**Comment by liho00** [comment]
@bluebill1049 does version 7.2.1 fix this issue?

**Comment by liho00** [comment]
@bluebill1049 I tried v7.2.1, this issue still not yet fix. 

![image](https://user-images.githubusercontent.com/77238199/115340653-ad283280-a1d9-11eb-8fc1-e3603ca68bff.png)
![image](https://user-images.githubusercontent.com/77238199/115340663-b2857d00-a1d9-11eb-8033-ced7a3880b1d.png)

I pretty sure this is a bug, because v6 dont have this issue, we shall not validate the fields that has been removed from the DOM.

Could you reopen this issue and fix it? just like how version 6 did. Why I like version 7 because i cant rollback to v6, as version 6 cant properly show error messages with ease.

**Comment by bluebill1049** [comment]
now that's a bug with Controller (shouldUnregister: true), i am investigating for the fix, someone else also reported the bug.

**Comment by liho00** [comment]
ok thanks

> now that's a bug with Controller (shouldUnregister: true), i am investigating for the fix, someone else also reported the bug.

**Comment by fauzymk** [comment]
@bluebill1049 Hi! I already used the latest version (v7.6.2) and still getting this issue. Here's a reproducible example https://codesandbox.io/s/react-hook-form-js-forked-1kb3w?file=/src/App.js

**Comment by liho00** [comment]
@bluebill1049 Could you help to reopen this issue & set the label as bug please. Thanks!

**Comment by bluebill1049** [comment]
> @bluebill1049 Hi! I already used the latest version (v7.6.2) and still getting this issue. Here's a reproducible example https://codesandbox.io/s/react-hook-form-js-forked-1kb3w?file=/src/App.js
> 
> As for now I had to manually use `unregister`

can you share steps to reproduce?

**Comment by fauzymk** [comment]
Alright, here's how to reproduce:

1. Go to this sandbox https://codesandbox.io/s/react-hook-form-js-forked-2985j
2. Fill in the input and then hit submit
3. In the console tab you'll see `firstName` is required

What I expect is that the form should skip `firstName` validation because the `Controller` is not mounted. I also tried adding `shouldUnregister: true` but still got the same issue.

**Comment by bluebill1049** [comment]
Thanks, @fauzymk this feature is only applicable for in-build validation, not schema. for schema, you will have to bring your own context.

**Comment by fauzymk** [comment]
> Thanks, @fauzymk this feature is only applicable for in-build validation, not schema. for schema, you will have to bring your own context.

@bluebill1049 Thanks for the reply. I've adjusted the schema to suit my context but still got the same issue. Same reproducible steps as above.

Here's the new codesandbox https://codesandbox.io/s/v7-2985j?file=/src/App.js

However, In v6 there's no issue. For comparison here's the v6 version of the code https://codesandbox.io/s/v6-2fpsm?file=/src/App.js

I think it has something to do with the `defaultValues` maybe? I'm not sure whether this is the expected behavior or if it's a bug.

**Comment by bluebill1049** [comment]
you are right @fauzymk `defaultValues` will be registered for absent input. This is an improvement so users doesn't have to register inputs manually at `useEffect`.

<img width="943" alt="Screen Shot 2021-05-21 at 7 18 26 pm" src="https://user-images.githubusercontent.com/10513364/119114659-b1aa6a00-ba69-11eb-88a8-441a542de7e5.png">
