### ISSUE TITLE
reValidate doesnt work after trigger RN

### ISSUE THREAD

**Issue by wwwenjie** [react-hook-form/react-hook-form#4824]
**Describe the bug**
reValidate doesnt work after trigger. However, use handleSubmit to invoke validate, everything is fine.

**To Reproduce**

1. Click Trigger button, will see error message
2. input values in TextInput, error message doesnt disapper

**Codesandbox link (Required)**
https://snack.expo.io/@jinwenjie/react-hook-form-doesnt-revalidate-after-trigger

**Expected behavior**
After trigger, then change values in input, error message should disapper

**Comment by bluebill1049** [comment]
`reValidateMode` is only for after Submit action. 

> This option allows you to configure when inputs with errors get re-validated after submit. By default, validation is only triggered during an input change.
