### ISSUE TITLE
Controller render field is undefined

### ISSUE THREAD

**Issue by chiararv** [react-hook-form/react-hook-form#4831]
I'm getting an error when using onChange, value and onBlur because field (inside render prop) seems to be undefined.
I recently migrated from v6 to v7. Until today it worked just fine.
This is my code:

 <Controller
      control={control}
      defaultValue={defaultValue}
      name={name}
      rules={{
        required: { value: required, message: ERROR_MESSAGES.REQUIRED },
        pattern: regExPattern,
        minLength: minLengthValidation,
      }}
      render={({ field: { onChange, onBlur, value } }) => (
        <Input
          label={label}
          value={value}
          onBlur={onBlur}
          error={errors}
          helperText={helperText}
          onChange={text => {
            onChange(text);
          }}
          isNumber={isNumber}
          rightIcon={rightIcon}
          maxLength={maxLength}
          {...restProps}
        />
      )}
    />
![Screenshot_20210416-121103](https://user-images.githubusercontent.com/62294095/115045779-345d6980-9ead-11eb-98e4-be8395b8fdbd.png)

**Comment by mbretter** [comment]
which version (6, 7) are you using?

**Comment by chiararv** [comment]
I recently migrated from v6 to v7. Until today it worked just fine. If I use it as I did before in v6 it works.
Its just field that doesnt work
