### ISSUE TITLE
IsValid state does not change when there's a select component

### ISSUE THREAD

**Issue by danicaliforrnia** [react-hook-form/react-hook-form#4832]
**Describe the bug**
In a form with two inputs with default values and both required, a Select and a TextField,  the isValid field is true. When I only edit the TextField the isValid value changes to false. The isValid field change to true only if I pick a value from the Select component.

**To Reproduce**

1. Go to https://codesandbox.io/s/erlxg
2. Edit the value in the TextField
3. Check the formState in the console

**Codesandbox link (Required)**
https://codesandbox.io/s/erlxg

**Expected behavior**
As both inputs have default values, when I edit one or another, the isValid field should stay true.

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version  90.0.4430.72

**Additional context**
The Select is a custom component using Material UI and React Hook Form.

**Comment by bluebill1049** [comment]
- I would appreciate if we can provide more isolated and example (less wrapper component, unrelated usage and etc...), that why it's much easier for me to investigate the issue.
- without deconstruct and reading the isValid formState, hook form is not subscribed to the formState `isValid`.
<img width="990" alt="Screen Shot 2021-04-17 at 9 56 36 am" src="https://user-images.githubusercontent.com/10513364/115095067-341fa580-9f63-11eb-8222-7f20b1c88538.png">

It's working for me now, unless i am missing something.
<img width="1310" alt="Screen Shot 2021-04-17 at 9 54 50 am" src="https://user-images.githubusercontent.com/10513364/115094985-f589eb00-9f62-11eb-95a6-16c6967b0f55.png">
