### ISSUE TITLE
Value isn't passed to Controller after using useFieldArray's append

### ISSUE THREAD

**Issue by marianozicavo** [react-hook-form/react-hook-form#4834]
**Describe the bug**
I'm using `useFieldArray` and mapping that array to show multiple [TextFields](https://next.material-ui.com/components/text-fields/). But when I called `useFieldArray`'s `append` function with a new value, that new value is added to the form but it isn't passed as `value` to the new input.
I added some console logging to the codesandbox to show what I'm saying.

**To Reproduce**

1. Go to sandbox example linked below
2. Click on the append button
3. The new `TextField` should show the new value, but it isn't showing.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-eefkf?file=/src/index.js

**Expected behavior**
I expected the new `TextField` to receive the new value as `value`, but it isn't receiving it.

**Desktop:**

- OS: MacOS Big Sur 11.2.3 (20D91)
- Browser: Chrome
- Version: 89.0.4389.90 (Official Build) (x86_64) 

**Additional context**
I also noted something else that might be related with this.
https://codesandbox.io/s/simple-mmtbq?file=/src/index.js
When I rerender a component (with a state update for example) that uses `useFieldArray`, `form.getValues()` and `form.watch()` show an empty array. `fields` is still looking fine, but I find it weird that the previous values are gone from the form. Is that ok or am I missing something?

I'm using v7.1.1

**Comment by bluebill1049** [comment]
missing `defaultValue`
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-eefkf?file=/src/index.js
<img width="735" alt="Screen Shot 2021-04-17 at 10 15 59 am" src="https://user-images.githubusercontent.com/10513364/115095799-e9ebf380-9f65-11eb-84ff-d803311ba412.png">

**Comment by marianozicavo** [comment]
@bluebill1049 
https://codesandbox.io/s/append-forked-weejz?file=/src/index.js
I just added the default value here and the problem is still happening

**Comment by bluebill1049** [comment]
please read the doc.

**Comment by marianozicavo** [comment]
You're right! My bad.
thanks

**Comment by bluebill1049** [comment]
> You're right! My bad.
> thanks

all good.
