### ISSUE TITLE
`useWatch` method does not watch form values when `defaultValue` has a value.

### ISSUE THREAD

**Issue by YuitoSato** [react-hook-form/react-hook-form#4837]
**Describe the bug**
`useWatch` method does not watch form values when the `defaultValue` has a value.
When `defaultValue` is undefined, form values are watched.

**To Reproduce**
The expected value A is not displayed even though `defaultValues` has a value  in the codesandbox page below.

```ts
import "./styles.css";
import { useForm, useWatch } from "react-hook-form";

export default function App() {
  const { control } = useForm({
    shouldUnregister: false,
    defaultValues: {
      select: "A"
    }
  });

  return (
    <span>
      <SelectedValue control={control} />
    </span>
  );
}

const SelectedValue = function SelectedValue({ control }) {
  const selectedValue = useWatch({
    control,
    name: "select",
    defaultValue: ""
  });

  // Value A is not displayed.
  return <>selectedValue: {selectedValue}</>;
};
```

**Codesandbox link (Required)**
https://codesandbox.io/s/immutable-browser-09fxk?file=/src/App.js

V7

- [JS](https://codesandbox.io/s/elated-dubinsky-vol10) Template
- [TS](https://codesandbox.io/s/frosty-wave-f1pco) Template

V6

- [useForm](https://codesandbox.io/s/react-hook-form-useform-template-lsm61) Template
- [useFieldArray](https://codesandbox.io/s/react-hook-form-usefieldarray-template-q0jek) Template
- [Controller](https://codesandbox.io/s/react-hook-form-controller-template-yu0z5) Template

**Expected behavior**
form values are watched by the useWatch method

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by YuitoSato** [comment]
I'm willing to create pull request if you like. Thank you for your great OSS

**Comment by bluebill1049** [comment]
hey, @YuitoSato thanks for the kind words and willingness to fixing this issue. I think this got overwrite by inline `defaultValue: ""`

**Comment by bluebill1049** [comment]
I am open to discussion on this right behavior too.

**Comment by YuitoSato** [comment]
I think `useWatch` should return a value in a form if they exist, not are undefined.

When a form value is undefined → it should return a value in `defaultValue`.
When a form value is defined (including empty string) → it should return a form value.

https://github.com/react-hook-form/react-hook-form/blob/a6586260727a746770045db4cf4e4f795b4a03e8/src/useWatch.ts#L49

Maybe this line will be fixed.
Can `getValues` method be used here?

### before
```
  const [value, updateValue] = React.useState<unknown>(
    isUndefined(defaultValue)
      ? watchInternal(name as InternalFieldName)
      : defaultValue,
  );
```

### after 
```
  const [value, updateValue] = React.useState<unknown>(
    isUndefined(defaultValue)
      ? getValues(name as InternalFieldName)
      : defaultValue,
  );
```

**Comment by bluebill1049** [comment]
I see what you mean @YuitoSato want to send a PR on this? Let's see if the tests or E2E will pick up anything.

**Comment by bluebill1049** [comment]
taking a closer look at it.

```
const [value, updateValue] = React.useState<unknown>(
    isUndefined(defaultValue)
      ? watchInternal(name as InternalFieldName)
      : defaultValue,
  );
```

so we are taking inline default value over what's provided in `useForm`, that's why the behavior you are using to return '' on the first render.

**Comment by bluebill1049** [comment]
ideally, we should only need one default value, eg

`useForm({ defaultValues: {} })`

vs 

`<Controller defaultValue="" />`

**Comment by YuitoSato** [comment]
> I see what you mean @YuitoSato want to send a PR on this?

Yes, I will! 
I'll give it a try for a couple of weeks.

**Comment by bluebill1049** [comment]
Going to close this issue, for now, I will keep an eye when you have the PR. Thank you @YuitoSato for looking into this. 🙏
