### ISSUE TITLE
If onBlur is before register it does not fire (it fires if onBlur is after register)

### ISSUE THREAD

**Issue by karland** [react-hook-form/react-hook-form#4843]
**Describe the bug**
If the `onBlur` prop is set before the `{...register()}` the onBlur does not fire.

**To Reproduce**

https://codesandbox.io/s/priceless-heisenberg-w4w6j?file=/src/App.js

1. Open codesandbox
2. Open Console of Developer Mode
3. Click between input fields. Only one fires when left.

```JSX
      <form onSubmit={handleSubmit(onSubmit)}>
        <label>Does not fire onBlur</label>
        <input
          type="text"
          onBlur={onBlur}
          {...register("onBlurBeforeRegister")}
        />
        <br />
        <label>Fires onBlur</label>
        <input
          type="text"
          {...register("onBlurAfterRegister")}
          onBlur={onBlur}
        />
      </form>
```

**Expected behavior**
Both input fields should fire, when left, but only one fires.

![image](https://user-images.githubusercontent.com/4803370/115121857-36125480-9fb5-11eb-8f75-3857801e0dda.png)

**Desktop (please complete the following information):**

- react-hook-form: 7.1.1
- OS: Windows
- Tested on Chrome and Firefox
- Current versions

**Comment by bluebill1049** [comment]
you will have to combine your own onBlur with register's returned onBlur

```
const input = register('firstName');

<input {...input} onBlur={(e) => { onBlur(e); input.onBlur(e) }} />
```
