### ISSUE TITLE
Example for FieldArray Usage with Append/Prepend crashes

### ISSUE THREAD

**Issue by shartte** [react-hook-form/react-hook-form#4845]
**Describe the bug**
The example page for advanced usage here: https://react-hook-form.com/advanced-usage#FieldArrays
Links to this code sandbox: https://codesandbox.io/s/react-hook-form-v6-controller-append-prepepend-insert-7clz7

Given the URL mentions v6, this was probably just not updated, although it's not clear from the error what the actual problem is (path.split is not a function).

**To Reproduce**

1. Open link in documentation
2. Get React error (path.split is not a function)

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-v6-controller-append-prepepend-insert-7clz7

**Desktop (please complete the following information):**

- OS: Win10
- Browser Firefox

**Comment by shartte** [comment]
Either I am imagining things, or the entire section about field arrays just disappeared 😢

**Comment by bluebill1049** [comment]
It's cached @shartte please use `useFieldArray` instead.
