### ISSUE TITLE
Next build failing with Typescript

### ISSUE THREAD

**Issue by Sysnomid** [react-hook-form/react-hook-form#4846]
Running ``` npm run build ``` on a NextJS Typescript app with react-hook-form yields this error 

```Failed to compile.

./node_modules/react-hook-form/dist/types/utils.d.ts:24:77
Type error: '?' expected.

  22 | declare type TupleKey<T extends ReadonlyArray<any>> = Exclude<keyof T, keyof any[]>;
  23 | declare type ArrayKey = number;
> 24 | declare type PathImpl<K extends string | number, V> = V extends Primitive ? `${K}` : `${K}` | `${K}.${Path<V>}`;
     |                                                                             ^
  25 | export declare type Path<T> = T extends ReadonlyArray<infer V> ? IsTuple<T> extends true ? { 
```

**To Reproduce**
1. Run npm run build on a NextJS Typescript project with react-hook-form

**Codesandbox link (Required)**
https://codesandbox.io/s/next-build-test-wfmsk

V7

- [JS](https://codesandbox.io/s/elated-dubinsky-vol10) Template
- [TS](https://codesandbox.io/s/frosty-wave-f1pco) Template

V6

- [useForm](https://codesandbox.io/s/react-hook-form-useform-template-lsm61) Template
- [useFieldArray](https://codesandbox.io/s/react-hook-form-usefieldarray-template-q0jek) Template
- [Controller](https://codesandbox.io/s/react-hook-form-controller-template-yu0z5) Template

**Expected behavior**
next build would run properly

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bluebill1049** [comment]
TS 4.1 above
