### ISSUE TITLE
V7: Controller ```value``` type and ```watch``` type is ```never```  when using ```watch``` inside a Field array

### ISSUE THREAD

**Issue by Gencko94** [react-hook-form/react-hook-form#4853]
**Describe the bug**
As Shown in the sandbox, I was trying to access a value using the watch method from inside the field components. but the return type is always never.
The Same type occurs in the Controller at the same component  when trying to access the value.
Also setting a value with ```setValue()``` is not possible due to the never type.
![screen2](https://user-images.githubusercontent.com/72993353/115150221-2a379880-a070-11eb-9db1-f9d57e606f75.PNG)

Am I doing something wrong ? 

**Codesandbox link (Required)**
https://codesandbox.io/s/bold-meninsky-4ppxs?file=/src/App.tsx

**Expected behavior**
watch method should return the proper type defined the the type definitions, instead returns never.

**Screenshots**

screenshot from the actual project, somehow the type here is never while in the sandbox the type is any.

![screen](https://user-images.githubusercontent.com/72993353/115150126-ad0c2380-a06f-11eb-892d-e912a1115e1e.png)

**Comment by bluebill1049** [comment]
please share the steps to reproduce the issue.

**Comment by ymor** [comment]
@Gencko94  You need to use something like the following for TS to get the correct type.
```variationValues.${index}.priceEnabled` as `variationValues.0.priceEnabled```

I assume this is some form of typescript limitation.

**Comment by bluebill1049** [comment]
Thanks, @ymor I think the next release of TS will improve on that (https://github.com/microsoft/TypeScript/pull/43361).

**Comment by Gencko94** [comment]
@ymor, @bluebill1049 , Thanks , 

> @Gencko94 You need to use something like the following for TS to get the correct type.
> `` `variationValues.${index}.priceEnabled` as `variationValues.0.priceEnabled` ``
> 
> I assume this is some form of typescript limitation.

This works well when hardcoding index value, however, what if we want to get dynamic values from the current iteration ?  trying dynamic indeces like ````variationValues.${index}.priceEnabled` as `variationValues.${number}.priceEnabled```` still returns ```never```.





> Thanks, @ymor I think the next release of TS will improve on that ([microsoft/TypeScript#43361](https://github.com/microsoft/TypeScript/pull/43361)).

Yes I hope TS will fix that soon.


Sorry for my English.

**Comment by bluebill1049** [comment]
All good, hope the next version gets released soon. ❤️
