### ISSUE TITLE
useFormState doesn't exist

### ISSUE THREAD

**Issue by Krausso** [react-hook-form/react-hook-form#4854]
**Is your feature request related to a problem? Please describe.**
Yep, I'm looking for a solution how to disable a button when form is not valid and I've opened documentation where I found this mistake. 
```
const { isDirty } = useForm(); // ✅
              
const formState = useForm(); // ❌ should deconstruct the formState
formState.isDirty; // ❌ subscription will be one render behind. 
```

**Describe the solution you'd like**
I haven't found any mentions of useFormState inside a lib and an error appears when I want to get `isDirty` or something else using `useForm`;
This method is probably deprecated, cuz I don't know any other possible reasons.

**Additional context**
![image](https://user-images.githubusercontent.com/52201020/115193221-8a701e00-a0f4-11eb-8bee-116bd0553b00.png)
react: 16.14.0
react-hook-form: 6.15.5

**Comment by Krausso** [comment]
Oh, sry, I forgot to add a [url](https://react-hook-form.com/api/useformstate) of this method id a documentation

**Comment by bluebill1049** [comment]
hey, @Krausso thanks for the issue require. this feature is only available since v7 due to the new architecture inside the code base, I don't think we will introduce this hook into v6 as well.

**Comment by Krausso** [comment]
Okay, thx for an answer:)
Have a nice day
