### ISSUE TITLE
V7.2.1 still problems with shouldUnregister

### ISSUE THREAD

**Issue by mbretter** [react-hook-form/react-hook-form#4864]
**Describe the bug**
I'm sorry to file a bug again, but useForm with shouldUnregister set to true still does not work as in V6

**To Reproduce**
V6:
https://codesandbox.io/s/thirsty-hooks-k0oo4

V7.2.1:
https://codesandbox.io/s/sharp-cloud-48n07?file=/src/Form.js

**Comment by bluebill1049** [comment]
What's not working @mbretter can you provide more details?

**Comment by bluebill1049** [comment]
can you reproduce the problem here: https://codesandbox.io/s/bold-fire-k48gz?file=/src/App.js?

**Comment by mbretter** [comment]
Switch the tab to DE, the input field still shows "English", but it should show "Deutsch", like on the v6 version.

**Comment by mbretter** [comment]
Your solution works, but this does not help in my case, because I would have to render the input fields for every single language, imagine you have a lot of languages, with multiple fields, this would be a big code bloat.

**Comment by bluebill1049** [comment]
I found the issue to be related to `Controller`, will investigate tonight for a fix. personally i prefer CSB to be easier to identify the issue, i identify the issue with another codesandbox with just Controller.

**Comment by mbretter** [comment]
ok, great thx

**Comment by bluebill1049** [comment]
after the fix, you will still need `key` for toggling the input just like what i suggested above. here is a working example: https://codesandbox.io/s/jolly-chaum-vukjp?file=/src/FormField.js

**Comment by mbretter** [comment]
hmm, if I am changing the input value, the watch shows the right value, but when submitting the form, the initial values are shown, without the changed value

**Comment by bluebill1049** [comment]
works for me in the example: https://codesandbox.io/s/bold-fire-k48gz?file=/src/App.js see if you can reproduce the problem.

**Comment by mbretter** [comment]
I have found the issue, the effect which triggers the data reset is triggered before submitting the form, causing the data to be reset.
The reason why this effect runs is the isSubmitting flag (formState), this is always false. I have to look deeper into it, seems to be a problem with this CSB.
Anyway I have removed the reset, and it is now working as expected.
Thank you for your support.

**Comment by bluebill1049** [comment]
That's awesome to hear! thanks for your help @mbretter still working on the fix, i will do my best to push this out tonight.

**Comment by bluebill1049** [comment]
here is a beta version:  react-hook-form@7.2.2-beta.0 would you like to have a try?

**Comment by mbretter** [comment]
updated the CSB:
https://codesandbox.io/s/sharp-cloud-48n07?file=/src/FormField.js
If switching to DE, "Deutsch" is displayed, this is ok, if switching back to EN, the input field is empty, switching to DE, the input field is empty too. It looks like that the default values are disappearing.

**Comment by mbretter** [comment]
found the problem, I had shouldUnregister only at the Controller, but it looks like that is needed on the form too.
CSB is now working
