### ISSUE TITLE
Possible regression in 7.2

### ISSUE THREAD

**Issue by ddolcimascolo** [react-hook-form/react-hook-form#4865]
**Describe the bug**
One of our tests started to fail when trying to upgrade this library to 7.2.0, then 7.2.1 and it kept failing. 
The test ensures that a field is in error state when an error condition triggers, then turn back to normal state when error condition is cleared. 

**To Reproduce**
Nothing really fancy, except that we manually call `setError(field)` / `clearErrors(field)`, i.e.: manual validation. 

**Codesandbox link (Required)**
I will try to provide a codesandbox later, but I do provide all the details above. 

V7

- [JS](https://codesandbox.io/s/elated-dubinsky-vol10) Template
- [TS](https://codesandbox.io/s/frosty-wave-f1pco) Template

V6

- [useForm](https://codesandbox.io/s/react-hook-form-useform-template-lsm61) Template
- [useFieldArray](https://codesandbox.io/s/react-hook-form-usefieldarray-template-q0jek) Template
- [Controller](https://codesandbox.io/s/react-hook-form-controller-template-yu0z5) Template

**Expected behavior**
The test does not fail. 

**Desktop (please complete the following information):**

- OS: Linux
- Browser: jsdom (jest tests) 
- Version: latest

**Additional context**
I see there's a change regarding validation in 7.2, this might be related.

**Comment by debikad** [comment]
+1 I too see this error!

**Comment by NickR49** [comment]
I'm seeing this problem too with a controlled component. 
setError and clearErrors are not correctly updating the formState.errors for the component.

**Comment by bluebill1049** [comment]
could I have a reproduceable codesandbox @NickR49 ?

**Comment by bluebill1049** [comment]
if you guys can help reproduce: https://codesandbox.io/s/romantic-maxwell-svxvp?file=/src/App.js

**Comment by anark** [comment]
The regression I am seeing can be viewed at https://codesandbox.io/s/summer-shape-rvkq8?file=/src/App.js.

In 7.1.1 You could enter a value and click submit and the form would correctly show NOT DIRTY(after a reset).
In 7.2.1 When you submit and `reset` is called the `isDirty` value is still true

**Comment by NickR49** [comment]
@bluebill1049 I've fixed the issue I was having. It was where my component was doing an unnecessary call to clearErrors(name) before then calling setError(name) in the next render (my component in this case was meant to start in an error state). I didn't think it would matter but this was causing my component to not be listed in the errors object. Removing the unnecessary call to clearErrors (even though it happened before setError) meant that it was correctly in the errors object.

**Comment by bluebill1049** [comment]
> The regression I am seeing can be viewed at https://codesandbox.io/s/summer-shape-rvkq8?file=/src/App.js.
> 
> In 7.1.1 You could enter a value and click submit and the form would correctly show NOT DIRTY(after a reset).
> In 7.2.1 When you submit and `reset` is called the `isDirty` value is still true

Thanks, fixing that.

**Comment by bluebill1049** [comment]
> Refresh the CSB a few times and sometimes the error shows correctly and sometimes it doesn't

Thanks @NickR49. can you define what's not working in more detail? so the error is not clearing? or state is not updated.

**Comment by ddolcimascolo** [comment]
@bluebill1049 Sorry for the delay, I managed to reproduce in a CSB https://codesandbox.io/s/condescending-volhard-3xj87 

Submit with an empty field, the field turns to error state. Type-in some characters, the error state does not automatically reset.
If you change the version of RHF to 7.1.1 it resets.

I'm a bit confused now by our call to clearErrors that might not be required at all, but that's another story :/

David

**Comment by bluebill1049** [comment]
> @bluebill1049 Sorry for the delay, I managed to reproduce in a CSB https://codesandbox.io/s/condescending-volhard-3xj87
> 
> Submit with an empty field, the field turns to error state. Type-in some characters, the error state does not automatically reset.
> If you change the version of RHF to 7.1.1 it resets.
> 
> I'm a bit confused now by our call to clearErrors that might not be required at all, but that's another story :/
> 
> David

oh! i see. thanks!
