### ISSUE TITLE
Typescript error when using errormessage on an array of primitives (not using fieldArrays)

### ISSUE THREAD

**Issue by Huuums** [react-hook-form/react-hook-form#4874]
**Describe the bug**
If you're typing a field inside the TFieldValues as an array of primitives the react-hook-form types will tell you that there is no error message on that field directly. 

Example:
```ts
type FormValues = {
  numArray: number[]
}

errors.numArray.message // Property 'message' does not exist on type '(FieldError | undefined)[]'
errors.numArray[0].message // this would work but won't show up if the value is an empty array.
```

**To Reproduce**

1. Go to https://codesandbox.io/s/hookform-message-doesnt-exist-typing-error-ygi37?file=/src/App.tsx
2. Click on Submit
3. See error message even though in the editor (line 37) the typescript error specifies that the message doesn't exist.

**Codesandbox link (Required)**
https://codesandbox.io/s/hookform-message-doesnt-exist-typing-error-ygi37?file=/src/App.tsx

**Expected behavior**
The typescript error shouldn't appear as there is a possibility that an error message exists on `errors.numArray` in this specific example

**Comment by bluebill1049** [comment]
I think this is what you after: https://react-hook-form.com/ts#NestedValue

**Comment by Huuums** [comment]
Ay, thanks for that, that's exactly what I've been looking for.

Turns out I should just have read the documentation more thoroughly.

**Comment by karenscheng** [comment]
Hi @Huuums - I'm stuck on this still and not quite sure what the nested value documentation points to in terms of a solution, could you share exactly how you fixed this problem?

I currently have this in my code:

```
{errors.categories?.type === 'required' && (
              <p className="error">Please choose at least one category</p>
            )}
```

And I get the TS error: `Property 'type' does not exist on type '(FieldError | undefined)[]'`

However when I console log the object errors I get the object:

```{
  "categories": {
    "type": "required",
    "message": "",
    "ref": {
      "name": "categories"
    }
  }
}```
