### ISSUE TITLE
Validation triggering on useFieldArray append

### ISSUE THREAD

**Issue by cjhines** [react-hook-form/react-hook-form#4880]
**Describe the bug**

I have a custom component which handle's a useFieldArray. It supports the adding of additional fields using the `append` function. However, upon pressing `append` validation is triggered for the entire form.

You'll see I'm passing errors to display some labels and these are shown on appending.

I've tried using a defaultValue for the input (see commented out line 41 in  `ArrayInput.tsx`), but I am unable to run:
`Property 'value' does not exist on type 'Record<"id", string>'.`

I've tired loosening the typing with some `any` usage, but this has no effect.

**To Reproduce**

1. Click on either 'Add another'
2. Validation is triggered for form and error labels are shown.

**Codesandbox link (Required)**
https://codesandbox.io/s/usefieldarray-error-uknm4?file=/src/ArrayInput.tsx

**Expected behavior**
Validation doesn't happen until submit is pressed.

**Desktop (please complete the following information):**

- Browser Chrome
- Version 88

**Comment by bluebill1049** [comment]
-  type issue: https://codesandbox.io/s/usefieldarray-error-forked-n2j7i
-  validation doesn't happen on append, however you can use `trigger`

**Comment by cjhines** [comment]
@bluebill1049 I appreciate the typing help!

However you can see validation does still occur, even in the codesandbox you linked.

Am I still doing something else wrong?

**Comment by bluebill1049** [comment]
<img width="1103" alt="Screen Shot 2021-04-21 at 4 32 52 pm" src="https://user-images.githubusercontent.com/10513364/115507250-39605580-a2bf-11eb-91be-899fd808287c.png">
<img width="1007" alt="Screen Shot 2021-04-21 at 4 33 02 pm" src="https://user-images.githubusercontent.com/10513364/115507268-3ebda000-a2bf-11eb-9ebe-794678425b1f.png">


hmmm looks fine at my end? maybe cache?

**Comment by cjhines** [comment]
@bluebill1049 Is the screenshot after you clicked 'Add another'?

Both fields array's still seem to have one field, and it's after clicking either "Add another" button I'm getting this unwanted validation.

**Comment by bluebill1049** [comment]
> @bluebill1049 Is the screenshot after you clicked 'Add another'?
> 
> Both fields array's still seem to have one field, and it's after clicking either "Add another" button I'm getting this unwanted validation.

no, I meant for the type error.

**Comment by bluebill1049** [comment]
share a video clip may be easier to see the problem.

**Comment by cjhines** [comment]
@bluebill1049 Apologies if I was unclear. I'm no longer getting the typing issue, thanks for that! However the app still validates on append which is unexpected.

Clicking "Add another" is causing validation which is the behaviour I'm most confused by.

**Comment by bluebill1049** [comment]
This due to your button is missing type.

https://user-images.githubusercontent.com/10513364/115513013-f2c22980-a2c5-11eb-85db-372b62627022.mov

**Comment by cjhines** [comment]
Ah, such a small oversight! thank you very much @bluebill1049

**Comment by bluebill1049** [comment]
np.
