### ISSUE TITLE
unregister method is working wrong.

### ISSUE THREAD

**Issue by oljapolja** [react-hook-form/react-hook-form#4881]
**Describe the bug**
In the latest version of the lib (v7), the unregister function is working wrong.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-unregister-v6-forked-qs8o6?file=/src/index.js
2. Click on 'unregister lastName'
3. Click submit and you will see the object contains lastName.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-unregister-v6-forked-qs8o6?file=/src/index.js

**Expected behavior**
When you call the unregister method, you should not see the unregistered fields on form submit .

**Screenshots**

**Desktop (please complete the following information):**

- OS: windows 10
- Browser: chrome
- Version 89

**Comment by bluebill1049** [comment]
That's because your component get register again in the render, try to unmount the input so this line: 

`{...register("lastName")}`

won't get invoked again.

**Comment by oljapolja** [comment]
Ok, thanks! 
I expected the behavior will be the same as v6 https://codesandbox.io/s/react-hook-form-unregister-v6-9nyzn , 
now to register inputs I should use useEffect
