### ISSUE TITLE
V7 4.2.1: Field validation doesn't work when custom validate function returns Message[]

### ISSUE THREAD

**Issue by svntime** [react-hook-form/react-hook-form#4895]
**Describe the bug**

[V7 4.2.1]

When custom validate function returns the array of messages, field's validation is not working. 
I found that ValidateResult = Message | Message[] | boolean | undefined.

**To Reproduce**

1. Go to the below Codesandbox
2. Click on the 'Submit' button
3. Go to the Console tab
4. 'firstName' is not present in errors, field was not validated.
5. 'city' was validated with maxLength and errors has object with key 'city' and its messages equal to ["city-1", "city-2"].

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-custom-validation-forked-vm4wm?file=/src/index.js

**Expected behavior**
Validation should work if field's custom validate function returns the array of messages (allowed by ValidateResult type and working when using maxLength)

**Screenshots**
![image](https://user-images.githubusercontent.com/42152930/115520723-be7d4780-a28a-11eb-8b01-db563a393f1b.png)
![image](https://user-images.githubusercontent.com/42152930/115516919-e66aac00-a286-11eb-855f-cf7291a25136.png)

**Desktop (please complete the following information):**

- OS: Win10
- Browser: Chrome
- Version: 89.0.4389.128

**Comment by bluebill1049** [comment]
we don't support return array for an error messages.

**Comment by avbee** [comment]
@bluebill1049 can you please specify what do you mean by "not supporting" arrays for error messages? The example above clearly shows that you can pass an array and use it to display custom messages for some validation types.

**Comment by bluebill1049** [comment]
> @bluebill1049 can you please specify what do you mean by "not supporting" arrays for error messages? The example above clearly shows that you can pass an array and use it to display custom messages for some validation types.

![image](https://user-images.githubusercontent.com/10513364/115531530-3c1b7480-a2d8-11eb-9179-3e14832bd46d.png)

**Comment by avbee** [comment]
What if I told you I read the docs (not just the 'Get Started' section), analyzed the types and analyzed codesandbox examples you provide on your github page and still didn't get the answer? Types show different behavior than the docs. I can't see what's wrong in asking and expecting the author to spend at least few minutes to actually read the question and give a sensible answer. Really disappointed, knowing that you have one of the most popular form libraries for react. I guess I'm not interested in getting information any more. Have a good day.

**Comment by bluebill1049** [comment]
**(Not reply to the above)** I don't need any of those drama crap in open source. 

If anyone else encounters the same issue. 

There is no such case that supports array as an error message and it is clearly shown in the doc. (If we do support such usage, and it will be documented)

https://react-hook-form.com/api/useform/register

<img width="501" alt="Screen Shot 2021-04-21 at 8 04 10 pm" src="https://user-images.githubusercontent.com/10513364/115536089-bd750600-a2dc-11eb-95fb-2fe9b5723ccf.png">

As type do indicate return multiple error message, however, this is only applicable for 

`criteriaMode: "firstError",`

<img width="974" alt="Screen Shot 2021-04-21 at 8 06 43 pm" src="https://user-images.githubusercontent.com/10513364/115536389-193f8f00-a2dd-11eb-9dec-aa3126bfaa60.png">

Going to lock this issue as there is no more issue to be resolved.
