### ISSUE TITLE
Form doesn't work if not initially visible

### ISSUE THREAD

**Issue by victorcarvalhosp** [react-hook-form/react-hook-form#490]
**Describe the bug**
Hi team,
I noticed an issue where the form doesn't work if it's not initially visible

**To Reproduce**
1. Go to https://react-hook-form-issue.netlify.com
2. Change the value in the form and submit, and you'll be able to see the watch function and the form value submitted just fine if you look at the browser console
3. Click on "Show Hidden Form" button
4. See that the watch value doesn't show up anymore and the form is submitted with no values(look at the browser console) - After the first time you try to submit it starts to work again

**Codesandbox link**
Didn't create on Codesandbox, but I have the repository here: https://github.com/victorcarvalhosp/react-hook-form-issue/tree/master and the project is running here: https://react-hook-form-issue.netlify.com

**Expected behavior**
The second form should work like the first one

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chromium
 -Version 78.0.3904.70 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Additional context**
I tried to look for some way to fix this looking at the documentation without success...

**Comment by bluebill1049** [comment]
could you reproduce that in a codesandbox? it's much easier to identify the issue, then going through your repo.

**Comment by bluebill1049** [comment]
also, there is a warning as well: 
<img width="1217" alt="Screen Shot 2019-11-11 at 7 24 12 am" src="https://user-images.githubusercontent.com/10513364/68550138-49ca9a80-0454-11ea-8545-e506eb0f6cfb.png">

**Comment by bluebill1049** [comment]
both `input` has
<img width="884" alt="Screen Shot 2019-11-11 at 7 25 40 am" src="https://user-images.githubusercontent.com/10513364/68550154-7c749300-0454-11ea-8b9d-8fb71867b14b.png">
 the same name could be the issue as well.

**Comment by victorcarvalhosp** [comment]
Hi @bluebill1049 ! Thanks for your answer, I'll create the codesandbox as soon as I can. 
But I tested with different form names and just with the not visible form, and in both cases it didn't work

**Comment by bluebill1049** [comment]
cool thanks, I will look at your codesandbox when it's ready.

**Comment by victorcarvalhosp** [comment]
I believe the error is related to the Ionic component... 
On codesandbox the input using ionic doesn't work in the form in any way... =\

Using plain HTML it works when initially not visible, but I can't get it to work with Ionic on codesandbox, even when visible. 

This is something that you would help/advise here?
On my repository, the form work with ionic inputs - but when not initially visible it doesn't work - On codesandbox ionic inputs doesn't work inside the form.

This is the codepen:
https://codesandbox.io/s/react-hook-form-basic-0cl0u?fontsize=14

I would be very glad if you can take a look into this, as I really want to use this with Ionic, but I'll understand if this is something not an issue related to react-hook-form and I'll try to contact the Ionic team in this case.

**Comment by bluebill1049** [comment]
No worries mate. I will take a look when I can for you 👌🏻

**Comment by bluebill1049** [comment]
Ok after a quick investigation. looks like ionic doesn't expose `innerRef` but `ref`.

However, the `ref` is not pure HTML input.

<img width="1649" alt="Screen Shot 2019-11-11 at 9 47 48 am" src="https://user-images.githubusercontent.com/10513364/68552189-578a1b00-0468-11ea-8afc-622d85986d6e.png">

You will have to use custom `register` during `useEffect`

```
useEffect(() => { 
  register({ name: 'xxx' });
}, [])
```

and update value using `setValue`

https://react-hook-form.com/api#setValue

**Comment by victorcarvalhosp** [comment]
Thank you so much for looking into this!
I made the changes and now it's working as expected! =D

I'll leave it here in case someone else wants to see the solution to work with Ionic!
https://codesandbox.io/s/react-hook-form-basic-0cl0u?fontsize=14

Thank you so much again!

**Comment by bluebill1049** [comment]
thank you @victorcarvalhosp I am glad it worked out for you :)

**Comment by tml123** [comment]
I also found that you can try something like this:

```html
<IonItem key={input.name}>
    <IonLabel>{ input.label }</IonLabel>
        <IonInput type={input.type}
                        onInput={handleChange}
                        name={input.name}
                        value={getValues()[input.name]}
                        ref={async el => {
                                   const element = el && await el.getInputElement();
                                   register(element, input.validations)
                                }}
                         >
        </IonInput>
        <ErrorMessage errors={errors} name={input.name} />
</IonItem>
```
Ionic provides a method to get the underlying input element.  You can pass that to `register` along with the validations as well.  Above I am mapping over an array of input objects that look like

```typescript
{
    name: 'name',
    label: 'Label',
    validations: { },
    type: 'text'
}
```

**Comment by kiily** [comment]
Ionic components are written in Stencil.js and aside from calling a method exposed on the component, which is always async (see [@Method](https://stenciljs.com/docs/methods)), I am not sure that web components can expose the `innerInputRef` directly like other React-libraries such as MaterialUI.

Thanks for the nice fix @tml123, it made perfect sense to me immediately and it works well :+1:

**Comment by bluebill1049** [comment]
@kiily i think Controller probably going to solve the problem as well: https://react-hook-form.com/api#Controller

**Comment by kiily** [comment]
I tried using it in my React TS app and was getting a shady TypeError, probably related to a mismatch in @types/react versions, I will continue investigating that and will update back

**Comment by kiily** [comment]
Moved my setup to `yarn` and everything works perfectly, I suspect some mismatch in versioning of `@types/react` that npm was having trouble with.

Thanks a lot for the awesome library 👍

**Comment by bluebill1049** [comment]
awesome. good to hear :) @kiily

**Comment by patelrikin** [comment]
> Thank you so much for looking into this!
> I made the changes and now it's working as expected! =D
> 
> I'll leave it here in case someone else wants to see the solution to work with Ionic!
> https://codesandbox.io/s/react-hook-form-basic-0cl0u?fontsize=14
> 
> Thank you so much again!

Your code is probably outdated, its not working because useForm is not default rather has to be named import.
Also validation does not work for IonicInput

**Comment by akhil0317** [comment]
import React, { useState,  } from "react";
import "./styles.css";
import { useForm } from "react-hook-form";

export default function App() {
  const { register, handleSubmit, errors } = useForm();
  const [imageSource, setImageSource] = useState("");
  const [name, setName] = useState("");
  const [lastName, setLastName] = useState("");
  const [email, setEmail] = useState("");
  const [number, setNumber] = useState("");
  const [gender, setGender] = useState("");
  const [age, setAge] = useState("");
  const onFileSelected = (event) => {
  
  
    if (event.target.files && event.target.files[0]) {
      const reader = new FileReader();
      reader.readAsDataURL(event.target.files[0]);
      reader.onload = (e) => setImageSource(e.target.result);
    }
  };
  const onFormSubmit = (data) => {
    console.log(data);
  };

  return (
    <div>
      <form onSubmit={handleSubmit(onFormSubmit)}>
        <h1>User Form</h1>
        {imageSource ? (
          <img
            alt="preview"
            style={{ height: "100px", width: "100px" }}
            src={imageSource}
          />
        ) : null}
        <input
          type="file"
          ref={register({ required: true })}
          onChange={onFileSelected}
          name="file"
          id = "file"
        ></input>
        <br />
        {errors.file && (
          <span style={{ color: "red" }}>
            Please select a file before submit
          </span>
        )}
        <br />
        <lable> first Name</lable>
        <input
          name="firstname"
          type="text"
          placeholder="Enter your first name"
          value={name}
          onChange={(e) => setName(e.target.value)}
          ref={register({ required: true })}
        />
        <br />
        {errors.firstname && (
          <span style={{ color: "red" }}>firstname should not be empty</span>
        )}
        <br />

        <lable> last Name</lable>
        <input
          name="lastname"
          type="text"
          placeholder="Enter your last name"
          value={lastName}
          onChange={(e) => setLastName(e.target.value)}
          ref={register({ required: true })}
        />
        <br />
        {errors.lastname && (
          <span style={{ color: "red" }}>lastname should not be empty</span>
        )}
        <br />
        <lable> Email:</lable>
        <input
          label="Email"
          name="mail"
          type="email"
          placeholder="Enter your email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          ref={register({ required: true })}
        />
        <br />
        {errors.mail && (
          <span style={{ color: "red" }}>email should not be empty</span>
        )}
        <br />
        <lable>Mobile Number</lable>
        <input
          name="mobilenumber"
          type="number"
          placeholder="Enter your phone number"
          value={number}
          onChange={(e) => setNumber(e.target.value)}
          ref={register({ required: true, pattern: /^[6-9]{1}[0-9]{9}/ })}
        />
        <br />
        {errors.mobilenumber && errors.mobilenumber.type === "required" && (
          <span style={{ color: "red" }}>
            Mobile number should not be empty
          </span>
        )}
        {errors.mobilenumber && errors.mobilenumber.type === "pattern" && (
          <span style={{ color: "red" }}>
            Please enter a valid phone number
          </span>
        )}
        <br />
        <lable>Gender: </lable>
        <label>
          <input
            type="radio"
            name="male"
            value="male"
            checked={gender === "male"}
            onClick={() => setGender("male")}
            ref={register({ required: true })}
          />
          Male
        </label>

        <label>
          <input
            type="radio"
            name="female"
            value="female"
            checked={gender === "female"}
            onClick={() => setGender("female")}
            ref={register({ required: true })}
          />
          Female
        </label>
        <br />

        {errors.male && errors.female && (
          <span style={{ color: "red" }}>please select a gender</span>
        )}
        <br />
        <lable> Age</lable>
        <input
          name="age"
          type="number"
          placeholder="Enter your age"
          value={age}
          onChange={(e) => setAge(e.target.value)}
          ref={register({
            required: true,
            min: 15
          })}
        />
        <br />
        {errors.age && errors.age.type === "required" && (
          <span style={{ color: "red" }}>age should not be empty</span>
        )}
        {errors.age && errors.age.type === "min" && (
          <span style={{ color: "red" }}>age should be greater than 14</span>
        )}
        <br />
        <br />
        <input type="submit" />
      </form>
    </div>
  );
}
i have created a form using react hook form everything works fine but when i click on submit onFormSubmit method is not trigerring and i am not able to get the form data can someone help

**Comment by mooSylla** [comment]
@akhil0317  I'm interested in this issue could you produce this bug in codesandbox ?
