### ISSUE TITLE
By Default `shouldUnregister` should be true?

### ISSUE THREAD

**Issue by liho00** [react-hook-form/react-hook-form#4901]
Could set the shouldUnregister as true by default? instead of setting the global config, i think its a normal behaviour that unregister the controller when its removed from the DOM?

![image](https://user-images.githubusercontent.com/77238199/115340653-ad283280-a1d9-11eb-8fc1-e3603ca68bff.png)
![image](https://user-images.githubusercontent.com/77238199/115340663-b2857d00-a1d9-11eb-8033-ced7a3880b1d.png)

I pretty sure that v6 shouldUnregister is true by default, we shall not validate the fields that has been removed from the DOM.
```
// global config
useForm();  // shouldUnregister: true
```

Besides, in my application, I have a lots of files that using useForm(), I need to add shouldRegister attributes to each of the useForm(), i think is unnecessary.

**Comment by bluebill1049** [comment]
Nope, it will be a breaking change.

**Comment by liho00** [comment]
May i know the reason?
