### ISSUE TITLE
v7 form values not propagating while using input component

### ISSUE THREAD

**Issue by Ciabas** [react-hook-form/react-hook-form#4902]
**Describe the bug**
Form not remembering the inputs' values  while using component wrappers.

**To Reproduce**
1. Open the codesandbox.
2. Fill the form.
3. Submit form.

**Codesandbox link (Required)**
https://codesandbox.io/s/inpulso-react-bumpo-6z1pz

**Screenshots**
![image](https://user-images.githubusercontent.com/9249181/115575856-3f583580-a2c3-11eb-9f63-02f421b61b88.png)

**Expected behaviour**
In both inputs (check the codesandbox) the value should be propagated.

**Comment by Ciabas** [comment]
I have simplified the codesandbox example.
I might be missing something, but how to use external Input components?

**Comment by yarrgh** [comment]
You need to use `forwardRef()` when using functional components.

Change your Input component to look like this:

```ts
type Props = any;
const Input = forwardRef<any, Props>((props, ref) => {
  return <input {...props} ref={ref} />;
});

export default Input;
```

**Comment by bluebill1049** [comment]
Thanks @yarrgh~ That's the right answer.

**Comment by Ciabas** [comment]
Thank you, neat solution.
