### ISSUE TITLE
Errors properties off by one render outside render

### ISSUE THREAD

**Issue by kongebra** [react-hook-form/react-hook-form#4903]
**Describe the bug**
When we need to do something after the validation (in another function) is done, it seems like `errors`-properties are off by one render on their values.

**To Reproduce**

1. Open console (to see output)
2. Go to firstName input-field
3. Remove John
4. Insert a single space-character ' '
5. Click outside input-field (to trigger onBlur)
6. Look at console-output
7. Go to firstName input-field
8. Remove the single space and leave input blank
9. Click outside input-field (to trigger onBlur)
10. Look at console-output

**Codesandbox link (Required)**
https://codesandbox.io/s/small-thunder-nq0t4

**Expected behavior**
Expected that `errors.firstName` contains the error as the same as `error` does in the console.

**Screenshots**
![image](https://user-images.githubusercontent.com/5748207/115569195-4714db80-a2bd-11eb-96d2-f0ad9b353d70.png)
(Image above) This one shows that `errors` contains the correct error, but `errors.firstName` is undefined. Should not say `Do something`. The UI-error is correct.

![image](https://user-images.githubusercontent.com/5748207/115569276-58f67e80-a2bd-11eb-8110-dd77f6c8186b.png)
(Image above) This one shows that `errors` contains the correct error, but `errors.firstName` is `errors` previous value. Should say `Don't do something`. The UI-error is correct.

**Additional context**
Have tried the same in JS (not TS) same result.
Tested on version: 7.2.2 and 7.1.1

**Comment by St3ff1** [comment]
I have the same issue

**Comment by bluebill1049** [comment]
Thanks, @kongebra for the very detailed issue report! I wish every issue report is like that. ❤️ Is this issue related to the stale `errors` object inside of your `validationOutSide`? Are you referring to the errors inside the callback that is behind one render?

**Comment by kongebra** [comment]
@bluebill1049 Yes, when trying to access `errors.firstName` as in this example, it will be `undefined` and I will "Do something" even though it actually has an error.

**Comment by bluebill1049** [comment]
> @bluebill1049 Yes, when trying to access `errors.firstName` as in this example, it will be `undefined` and I will "Do something" even though it actually has an error.

Does this fix the issue? https://codesandbox.io/s/naughty-jepsen-8mzho?file=/src/App.tsx

**Comment by kongebra** [comment]
> > @bluebill1049 Yes, when trying to access `errors.firstName` as in this example, it will be `undefined` and I will "Do something" even though it actually has an error.
> 
> Does this fix the issue? https://codesandbox.io/s/naughty-jepsen-8mzho?file=/src/App.tsx

Not really, still has the same result. If doing step 1 to 6. The output will be "Do something" and the `errors.firstName` is still `undefined`.

One working solution that we found was to wrap the code after `trigger`, in `requestAnimationFrame`

```js
const validationOutSide = React.useCallback((e: React.FocusEvent<HTMLInputElement>) => {
  trigger("firstName");

  const { value } = e.currentTarget;

  requestAnimationFrame(() => {
    if (value !== defaultValues.firstName) {
      console.log("console.log(errors):", formState.errors);
      console.log( "console.log(errors.firstName):", formState.errors.firstName);

        if (formState.errors.firstName === undefined) {
          console.log("Do something");
        } else {
          console.log("Don't do something");
        }
      }
    });
  },
  [formState, trigger, defaultValues]
);
```

**Comment by bluebill1049** [comment]
by the way, `trigger` is async. I think this PR may resolve your issue: https://github.com/react-hook-form/react-hook-form/pull/4856

**Comment by kongebra** [comment]
> by the way, `trigger` is async. I think this PR may resolve your issue: #4856

Yeah if trigger is async then having a Promise would help to do things in the correct order.

How can I test the code in that PR?

**Comment by bluebill1049** [comment]
> > by the way, `trigger` is async. I think this PR may resolve your issue: #4856
> 
> Yeah if trigger is async then having a Promise would help to do things in the correct order.
> 
> How can I test the code in that PR?

I will release a beta tonight for you.

**Comment by bluebill1049** [comment]
Another way is using `useEffect` with formState as `dep`

**Comment by bluebill1049** [comment]
you can try with this beta: `v7.2.4-beta.0`

**Comment by MercurialWeb** [comment]
Hi, same problem here.
After last update formState.errors state updates only onSubmit, was working good with {register, errors} of previous version.
Now all forms with mode/revalidation: 'onChange','onBlur' shows errors message until form submit (i check for formState.errors.[nameOfField])

Tested v7.2.4-beta.0 but same problem occurred.

**Comment by kongebra** [comment]
> Another way is using useEffect with formState as dep and check the errors object, achievable but a bit more difficult.

Looked at that solution earlier, but got nasty when our forms are getting bigger.

> you can try with this beta: `v7.2.4-beta.0`

https://codesandbox.io/s/throbbing-snow-ji72p

Seems like it works nicely! Tested in codesandbox.io and on my local project.

Had to change from `e.currentTarget.value` to `e.target.value`
Cause the currentTarget is null. Guess it has something to do with the async, but not any issue.

**Comment by MercurialWeb** [comment]
Did a clean installation of `v7.2.4-beta.0`, now working well!

**Comment by bluebill1049** [comment]
> Did a clean installation of `v7.2.4-beta.0`, onBlur working good.
> Still have problems with onChange validation when using FormContext.

can you provide a simple codesandbox? otherwise it's hard to imagine the problem.

**Comment by MercurialWeb** [comment]
Can't reproduce the error on CodeSandbox, maybe there is something else conflicting in my project.
So i confirm that all problems gone with this  v7.2.4-beta.0

**Comment by bluebill1049** [comment]
Thanks guys, will try to release it today.

**Comment by Pika-Pool** [comment]
> Did a clean installation of `v7.2.4-beta.0`, onBlur working good. Still have problems with onChange validation when using FormContext.

@MercurialWeb, did you find a solution for this. I'm having the same issue with v7.34.2. mode is onChange and using FormContext

**Comment by Moshyfawn** [comment]
You might wanna open a new issue / discussion instead

**Comment by Moshyfawn** [comment]
> > Did a clean installation of `v7.2.4-beta.0`, onBlur working good. Still have problems with onChange validation when using FormContext.
> 
> @MercurialWeb, did you find a solution for this. I'm having the same issue with v7.34.2. mode is onChange and using FormContext

You might wanna open a new issue / discussion instead
