### ISSUE TITLE
V7 useWatch returns undefined after reset

### ISSUE THREAD

**Issue by mbretter** [react-hook-form/react-hook-form#4912]
**Describe the bug**
useWatch returns undefined, after invoking reset.

**To Reproduce**

1. open the codesandbox console
2. the first watch returns "" which is ok
3. the second watch returns undefined, but it should display "Alice"

**Codesandbox link (Required)**
https://codesandbox.io/s/loving-night-7rz4d?file=/src/App.js

**Comment by bluebill1049** [comment]
please provide an isolated codesandbox @mbretter it will really make my life easier.

**Comment by mbretter** [comment]
here we go:
https://codesandbox.io/s/loving-night-7rz4d?file=/src/App.js

I have found, that shouldUnregister is the problem, when setting it to false, useWatch works as expected

**Comment by bluebill1049** [comment]
Thanks @mbretter 👍
