### ISSUE TITLE
v7 register forward refs failed with nested components

### ISSUE THREAD

**Issue by aryan340** [react-hook-form/react-hook-form#4913]
**Describe the bug**
register forward refs failed while nesting components.

**Expected behavior**
ref to be created properly with the spread operator

**Screenshots**
![image](https://user-images.githubusercontent.com/69184573/115715001-5c5d3900-a395-11eb-9095-7fe9bdce2f72.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser chrome
- Version 89

**Additional context**
I have the following components.
```js
export const TextField = props => {
  return (
    <input
      type={props.type}
      defaultValue={props.defaultValue}
      value={props.value}
      name={props.name}
      placeholder={props.placeholder}
      onChange={props.onChange}
      maxLength={props.maxLength}
      className={`input ${props.variant}`}
      spellCheck={false}
      {...props}
    />
  )
}

TextField.defaultProps = {
  variant: 'default',
  maxLength: 99
}
```
```js
// FormField
export const FormField = props => {
  // access context from FormProvider
  const { register, formState: { errors } } = useFormContext();
  const field_errors = get(errors, props.name);

  return (
    <div className="formField-wrapper">
      <div className="header">
        <label className={`label ${field_errors && 'errors'}`} htmlFor={props.name}>{props.label}</label>
        {field_errors && <label className="error-msg errors">{field_errors.message}</label>}
      </div>
      <TextField
        {...register(props.name)}
        variant={field_errors ? `${props.variant} errors` : props.variant}
        type={props.type}
        defaultValue={props.defaultValue}
        value={props.value}
        placeholder={props.placeholder}
        onChange={props.onChange}
        maxLength={props.maxLength}
      />
    </div>
  )
}
FormField.defaultProps = {
  variant: 'default'
}
```
So here, I would like to register the FormField's inner TextField component (which has the base HTML input). So I have used the spread operator with FormField and am taking it in the TextField with `{...props}`

However, I get the error shown in the screenshot
and the submit method is not firing after the first time.

**Comment by togradywk** [comment]
React does not allow for refs to be forwarded on functional components.  You can either use React.forwardRef, or you can extract the ref from the register return and pass that into your TextField component with a new prop name.  

https://reactjs.org/docs/forwarding-refs.html

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

if the above didn't solve the problem, please follow the template and we will look at it again.

**Comment by aryan340** [comment]
https://codesandbox.io/s/v7-nested-register-react-hook-form-94yey?file=/src/forms.js
Here is an updated sandbox.

**Comment by bluebill1049** [comment]
<img width="1037" alt="Screen Shot 2021-04-23 at 11 52 26 am" src=@aryan340 fps://user-images.githubusercontent.com/10513364/115806578-61b89300-a42a-11eb-91a4-52de45b0fdec.png">

thanks @ary failed right away.

**Comment by bluebill1049** [comment]
> https://codesandbox.io/s/v7-nested-register-react-hook-form-94yey?file=/src/forms.js
> Here is an updated sandbox.

what's the steps to reproduce issue?

**Comment by aryan340** [comment]
@bluebill1049 I am not too sure.
The forms work on codesandbox but not in my environment.
For me, the form does not submit if there is any error.

What makes it worse is I revalidate only on submit, and the form does not submit
so the form freezes after the first validation.

**Comment by aryan340** [comment]
https://user-images.githubusercontent.com/69184573/115811265-04621900-a40d-11eb-8783-fe9df8651f50.mp4

**Comment by aryan340** [comment]
I am using react-hook-form: "^7.2.3"

**Comment by bluebill1049** [comment]
honestly, I am not sure what's going on unless you can reproduce in a codesandbox, but are your component gets mount and remount each render? it looks like they r getting re-regsitered.

maybe the following as well:

```
<TextField
        {...register(props.name)}        
```

`register` return 'onChange, onBlur, value ref`

so in your example above material UI is using `inputRef`, so ref is never getting `registered`.

try the following:

```
const { ref, ...rest } = register(props.name);
<TextField
  inputRef={ref} 
  {...rest}        
```

**Comment by aryan340** [comment]
you mean like this?
```js
export const TextField = props => {
  const { ref, ...rest } = props.register(props.name);

  return (
    <input
      type={props.type}
      defaultValue={props.defaultValue}
      value={props.value}
      name={props.name}
      placeholder={props.placeholder}
      onChange={props.onChange}
      maxLength={props.maxLength}
      className={`input ${props.variant}`}
      spellCheck={props.spellCheck}
      inputRef={ref}
      {...rest}
    />
  )
}
```

**Comment by bluebill1049** [comment]
> you mean like this?
> 
> ```js
> export const TextField = props => {
>   const { ref, ...rest } = props.register(props.name);
> 
>   return (
>     <input
>       type={props.type}
>       defaultValue={props.defaultValue}
>       value={props.value}
>       name={props.name}
>       placeholder={props.placeholder}
>       onChange={props.onChange}
>       maxLength={props.maxLength}
>       className={`input ${props.variant}`}
>       spellCheck={props.spellCheck}
>       inputRef={ref}
>       {...rest}
>     />
>   )
> }
> ```

no only for MUI, native input should work out of the box.

**Comment by aryan340** [comment]
> so in your example above material UI is using inputRef, so ref is never getting registered.

earlier I registered like this.
```js
export const TextField = props => {
  const register = props.register;

  return (
    <input
      type={props.type}
      defaultValue={props.defaultValue}
      value={props.value}
      name={props.name}
      placeholder={props.placeholder}
      onChange={props.onChange}
      maxLength={props.maxLength}
      className={`input ${props.variant}`}
      spellCheck={props.spellCheck}
      {...register(props.name)}
    />
  )
}
```

**Comment by aryan340** [comment]
> no only for MUI, native input should work out of the box.

sorry I dont get you.
am not using material UI the library 😅.

The TextField is my own reusable component.

**Comment by bluebill1049** [comment]
> > no only for MUI, native input should work out of the box.
> 
> sorry I dont get you.
> am not using material UI the library 😅.
> 
> The TextField is my own reusable component.

then you are not forward the `ref` correctly like @togradywk suggested.

**Comment by aryan340** [comment]
I am trying to reproduce in codesandbox, thanks for your time.

**Comment by aryan340** [comment]
@bluebill1049 here it is.
https://codesandbox.io/s/v7-nested-register-react-hook-form-94yey?file=/src/App.js

So when I do validation with react-hook-form, it is okay.
I have a required field validation in the example given (please look at the sandbox).

However, in my real project,
I have a django server running on the local network and I set the server side errors manually.
So I think that that's where the error lies.

**Comment by aryan340** [comment]
this is how the actual error handling part of the form looks like.
```js
/* Base Form with provider
(Handles server-side validation).
Expects the submit handler to
return a promise (most likely an
axios request). */
export const Form = props => {
  const methods = useForm(props.useFormProps);
  const { setError, handleSubmit } = methods;
  const submitHandler = props.onSubmit;

  const handleErrors = errors => {
    Object.keys(errors).forEach((field) => {
      setError(field, {
        type: "server",
        message: errors[field]
      })
    });
  }

  const onSubmit = data => {
    console.log('submitting...')
    submitHandler(data)
      .catch(errors => {
        handleErrors(errors.response.data);
      }
      )
  }

  return (
    <FormProvider {...methods} >
      <form onSubmit={handleSubmit(onSubmit)}>
        {props.children}
      </form>
    </FormProvider>
  )
}
```

**Comment by aryan340** [comment]
this is how the errors look like, provided by the server.
![image](https://user-images.githubusercontent.com/69184573/115815879-72aad980-a415-11eb-83f2-8df1c41db37d.png)

**Comment by bluebill1049** [comment]
<img width="845" alt="Screen Shot 2021-04-23 at 2 03 32 pm" src="https://user-images.githubusercontent.com/10513364/115816717-b1a05580-a43c-11eb-8a9e-13fd3edf56aa.png">

you will have to clear manually set errors.

**Comment by aryan340** [comment]
oh.. just got to know that.

**Comment by aryan340** [comment]
oh.. just got to know that.
when should I do it? if onsubmit isn't even firing?

I don't get that part, sorry.

**Comment by aryan340** [comment]
@bluebill1049 I really don't know if there is a way to do this.
I have been searching for references on the internet, no luck.
can you please help me out on this? thanks a lot!
