### ISSUE TITLE
V7 useFieldArray and Controller

### ISSUE THREAD

**Issue by mbretter** [react-hook-form/react-hook-form#4915]
**Describe the bug**
When using useFieldArray with inputs wrapped inside a Controller, the field values are not displayed.

**To Reproduce**

1. open the codesandbox
2. only the input field without the Controller displays it's value
3. neither the materia-ui Texfield nor the raw html input displays a value

**Codesandbox link (Required)**
https://codesandbox.io/s/gracious-wozniak-np1r5?file=/src/App.js

**Comment by sshquack** [comment]
Running into a similar error here https://github.com/react-hook-form/react-hook-form/issues/4917. When the value passed into render prop is `value={field.value}` it seems to get the whole object but when changing it to `value={getValues["root"]?.[index]?.["key"]}` it shows the right value. But it seem like a bug.

**Comment by bluebill1049** [comment]
<img width="996" alt="Screen Shot 2021-04-23 at 9 39 59 am" src="https://user-images.githubusercontent.com/10513364/115797704-e0580500-a417-11eb-8e33-bc6d4cfb6d85.png">

>defaultValue must be set for all inputs. Supplied defaultValues in the useForm hook will prepare the fields object with default value.

**Comment by mbretter** [comment]
ok, in the CSB
https://codesandbox.io/s/gracious-wozniak-np1r5?file=/src/App.js
there are all the defaultValues passed to useForm.

Actually, I could get the example to work, I have removed the defaultValue from the controller! This is the opposite what the docs say.
