### ISSUE TITLE
V7 FieldArray Typescript template string error

### ISSUE THREAD

**Issue by sshquack** [react-hook-form/react-hook-form#4917]
**Describe the bug**
When using RHF V7 with controlled and uncontrolled inputs for arrays, the Typescript template literal syntax throws an error.

**To Reproduce**
- Create uncontrolled `<input {...register(`test.${index}.title`)} />` throws error `Argument of type 'string' is not assignable to parameter of type '"test" | `test.${number}` | `test.${number}.title` | `test.${number}.quantity`'.ts(2345)`
- Create controlled input `<Controller name={`test.${index}.quantity`} ...` throws error `Type 'string' is not assignable to type '"test" | `test.${number}` | `test.${number}.title` | `test.${number}.quantity`'.ts(2322)`

**Codesandbox link (Required)**
https://codesandbox.io/s/rhf-usefieldarray-virtual-inputs-27g7p?file=/src/App.tsx

**Expected behavior**
Should compile with Typescript 4.2

**Screenshots**
![Screen Shot 2021-04-22 at 12 53 09 PM](https://user-images.githubusercontent.com/5678459/115777138-c95ad980-a369-11eb-8d16-f51bd126b2f9.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS
- Browser [e.g. chrome, safari] chrome
- Version [e.g. 22] 90.0.4430.72

**Comment by bees** [comment]
I just ran into this - you can add `as const` to your template literal declaration:

```typescript
<input {...register(`test.${index}.title` as const)} />
```
to prevent it from widening to a string type. Interactive version of the fix: https://codesandbox.io/s/rhf-usefieldarray-virtual-inputs-forked-wkk3c

Given the release notes on [4.2](https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/#reverting-template-literal-inference) it sounds like `as const` will be necessary to get the template literal inference.

**Comment by bluebill1049** [comment]
<img width="948" alt="Screen Shot 2021-04-23 at 9 37 45 am" src="https://user-images.githubusercontent.com/10513364/115797572-91aa6b00-a417-11eb-973b-00bc9c0ee0ad.png">

Thanks @bees that's right.

**Comment by adamtay** [comment]
@bluebill1049 could we please add this to the documentation if not already? Was stuck on this for quite some time :(

**Comment by bluebill1049** [comment]
> @bluebill1049 could we please add this to the documentation if not already? Was stuck on this for quite some time :(

This is in the doc.

**Comment by adamtay** [comment]
@bluebill1049 apologies if this is in the documentation already but how about for using `setValue`?

```
    setValue(
      `addresses.${addressIndex}.isActive` as `addresses.${number}.isActive`,
      false
    );
```
But getting the error:
```
Argument of type 'boolean' is not assignable to parameter of type 'never'.ts(2345)
```

**Comment by bluebill1049** [comment]
> @bluebill1049 apologies if this is in the documentation already but how about for using `setValue`?
> 
> ```
>     setValue(
>       `addresses.${addressIndex}.isActive` as `addresses.${number}.isActive`,
>       false
>     );
> ```
> 
> But getting the error:
> 
> ```
> Argument of type 'boolean' is not assignable to parameter of type 'never'.ts(2345)
> ```

They r related to this: https://github.com/microsoft/TypeScript/pull/43361 I think the future release of TS should resolve this problem.
