### ISSUE TITLE
Version 7 problems with input type="hidden"

### ISSUE THREAD

**Issue by MercurialWeb** [react-hook-form/react-hook-form#4925]
Registered hidden input not updating values. This is useful for store computed values like Multi Select and apply validation.
As you can see in examples, in version 7, when you submit form the value of hidden input is not updated.

Working version 6 example:
https://codesandbox.io/s/react-hook-form-get-started-forked-h02j9?file=/src/index.js

Same example not working on version 7:
https://codesandbox.io/s/react-hook-form-get-started-forked-ov4ev?file=/src/index.js

**Comment by bluebill1049** [comment]
use hook form setValue method: https://codesandbox.io/s/react-hook-form-get-started-forked-ro1d7?file=/src/index.js 👍
