### ISSUE TITLE
version 7 ref={register({pattern://})} throwing error path.split is not a function

### ISSUE THREAD

**Issue by dhruv-choudary** [react-hook-form/react-hook-form#4926]
**Describe the bug**
I recently updated to version 7 and started to get error for all regsiter which have pattern format in it 

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-js-wbybv?file=/src/App.js

I added new input field in old way ref pattern 
```html
<input name="lastName" ref={register({pattern:/\d/})} placeholder="Last name" />
```

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

https://codesandbox.io/s/react-hook-form-js-wbybv?file=/src/App.js

**Comment by MercurialWeb** [comment]
You are using old notation for register.

This is correct definition for your input:
`<input {...register("lastName",{pattern:/\d/})} placeholder="Last name" />`

**Comment by bluebill1049** [comment]
Thanks @MercurialWeb :) yes use the new v7 syntax and read the doc https://react-hook-form.com/api/useform/register
