### ISSUE TITLE
useFieldArray with array strings transforms them into object

### ISSUE THREAD

**Issue by asaf** [react-hook-form/react-hook-form#4927]
Using `useFieldArray` with an array of strings (e.g., ["foo"]) transforms each element into `{0:"f",1:"o",2:"o":"id":"..."}`

See: https://codesandbox.io/s/react-hook-form-v7-form-context-forked-dn9yu?file=/src/index.js:174-202
and inspect the console for: `console.log('string becomes array', fields)`

Possible solution: If array's element is string, push it under `value` field so final object would be `{"value": "foo", "id": "uuid"}`

**Comment by bluebill1049** [comment]
> Does not support flat field array.

<img width="1126" alt="Screen Shot 2021-04-23 at 9 52 59 pm" src="https://user-images.githubusercontent.com/10513364/115867304-46777300-a47e-11eb-92bc-3754e6542129.png">

**Comment by asaf** [comment]
@bluebill1049 but why not support it? this is a very common case. otherwise it requires to perform object transformation, which may be complex in case of nesting, etc.
