### ISSUE TITLE
Validation messages using Yup

### ISSUE THREAD

**Issue by jonatasfl** [react-hook-form/react-hook-form#493]
**Describe the bug**
Using Yup to validate my form, I'm noticing something that looks like a bug.
If I register a field with `ref={register}` and is optional number field for example, I receive validation error like the following if its leave empty: 

> field must be a `number` type, but the final value was: `NaN` (cast from the value `""`).

If I change `ref={register}` to `ref={register()}`, the optional validation works, but the form dont clear error messages when I fill a required field after validation fails.

**To Reproduce**
You can try this CodeSandbox: https://codesandbox.io/s/react-hook-form-with-yup-vdz3v?fontsize=14

1. Fill all fields, except the last one (Years of experience)
2. Click on submit button to see the error.
3. Change all `ref={register}` to `ref={register()}` and try again, making validation fail before.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-with-yup-vdz3v?fontsize=14

**Expected behavior**
Dont show error message when leave optional field blank.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 78.0.3904.97

**Comment by bopfer** [comment]
HTML form values are always strings.  So, that behavior is expected.  You can transform the field when it is `NaN`:

```javascript
experience: Yup.number().transform(value =>
        isNaN(value) ? undefined : value
      ).required("Insert years of experience")
```

**Comment by bluebill1049** [comment]
thanks @bopfer for helping :)
