### ISSUE TITLE
none of those V6 code samples working

### ISSUE THREAD

**Issue by kelinwu** [react-hook-form/react-hook-form#4932]
Hi,

I found none of those V6 samples are working. V7 samples are working fine

here is V6 the sample
https://codesandbox.io/s/rwpz2jn6ln

error on screenshot
![image](https://user-images.githubusercontent.com/4358510/115888873-67f64180-a421-11eb-83b0-79ec4182bd1c.png)

-K

**Comment by bluebill1049** [comment]
fixed thank you.
