### ISSUE TITLE
 TypeError · Cannot destructure property `_f` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by xdumaine** [react-hook-form/react-hook-form#4933]
**Describe the bug**
I'm getting this type error frequently (reported to me via bugsnag) but I've not yet identified the root cause:

` TypeError · Cannot destructure property `_f` of 'undefined' or 'null'.`

![image](https://user-images.githubusercontent.com/833911/115896648-a55ecd00-a429-11eb-8c4c-6b8b9154520d.png)

**To Reproduce**

**Codesandbox link (Required)**

Working on reproducing, in the meantime, it looks like the culprit is this typecast, which is not always accurate (`get(fieldsRef.current, name)` might return null): https://github.com/react-hook-form/react-hook-form/blob/f917e1e805bc3c0fe49857995529c3f8611cfa66/src/useForm.ts#L361

V7

- [JS](https://codesandbox.io/s/elated-dubinsky-vol10) Template
- [TS](https://codesandbox.io/s/frosty-wave-f1pco) Template

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: linux
- Browser: Chrome
- Version 73

**Comment by bluebill1049** [comment]
will patch that, it worth checking if this is some async validation which results after the component is removed?
