### ISSUE TITLE
option to have RHF behave backwards compatibly.

### ISSUE THREAD

**Issue by jpodpro** [react-hook-form/react-hook-form#4936]
V7 introduced breaking changes that have no work-arounds or configuration options:
- forced shallow merging of `defaultValues` or `reset` contents into output structure.
- forced validation of fields that have been removed from the DOM.

both of these are highly problematic for our complex dynamic forms and there are no work-arounds. i would very much appreciate the ability to use V7 features with V6 behavior under the hood. please consider adding in control options for this behavior, thanks.

**Comment by bluebill1049** [comment]
thanks for your feedback, we will consider it. If v7 migration is too hard, stay in v6 as it's still maintained.

**Comment by bluebill1049** [comment]
also confident to say both are getting addresses.

**Comment by jpodpro** [comment]
unfortunately v6 has problems too - such as not providing real DOM refs in the errors structure. since we need those i'm going to have to create a manual system of managing them - something that v7 provides. so i'm very much stuck in between. sorry if it comes across as rude. i just spent over 2 days fighting with something that was working just fine the way it was.

**Comment by bluebill1049** [comment]
one thing I hope next time is to jump into RFC (it has been running for months) earlier rather than after release (if your work relies on the lib a lot).
