### ISSUE TITLE
`useController` / `Controller` wrongly retains nested path's value when inserting item with `useFieldArray` 

### ISSUE THREAD

**Issue by dwiyatci** [react-hook-form/react-hook-form#4941]
**Describe the bug**
When inserting item with `useFieldArray` between existing items, and the control is registered with `useController` or `Controller` against a nested path, the newly inserted value is not respected and the control retains the previous value that occupies the control instead.

**To Reproduce**

1. Click on 'insert at'.
2. See the inserted values in the controls.

**Codesandbox link (Required)**
https://codesandbox.io/s/rhf-usefieldarray-template-v7-plain-forked-59qni?file=/src/index.js

**Expected behavior**
In the CSB above, the newly inserted values should be empty string in the controls for both first name and last name.

**Additional context**
I believe this issue been occurring since I upgraded to v7.3+.

**Comment by bluebill1049** [comment]
related #4861

**Comment by dwiyatci** [comment]
@bluebill1049 This issue seems to come back, but only when using `<input {...register(...)}>`; `<Controller>` works fine. Please follow the given CSB link above once more, I've upgraded it using v7.5.2. Thank you.

**Comment by bluebill1049** [comment]
@dwiyatci can you test out this beta: `v7.5.3-beta.1`

**Comment by dwiyatci** [comment]
Lookin' great now, thanks!! Let's close this again 🙇🏻
