### ISSUE TITLE
When appending/inserting a field that's not registered, the field remains in the data structure (different behavior than v6)

### ISSUE THREAD

**Issue by dwiyatci** [react-hook-form/react-hook-form#4951]
**Describe the bug**
I found this when debugging using RHF DevTools, but I can also easily reproduce it in CSB. 😅 When appending or inserting an item using `useFieldArray`, and that item contains a field that can be conditionally/not-yet rendered -- thus not registered yet -- the data structure contains this field that's not registered.

**To Reproduce**

1. Click on 'insert at'.
2. Observe the inserted item in the `fields` array in the console.

**Codesandbox link (Required)**
https://codesandbox.io/s/rhf-usefieldarray-template-v7-inserting-not-registered-fields-qk038

**Expected behavior**
In the CSB above, the `foo` field in the inserted item should _**not**_ be in the data structure because it is not rendered (not registered) yet against a control (just like in v6).

**Comment by bluebill1049** [comment]
That's expected behaviour.

**Comment by dwiyatci** [comment]
Ah ok, thanks Bill. May I know which of the breaking changes in v7 changes this behavior from v6?

**Comment by bluebill1049** [comment]
Let me take a closer look tmr and give you a confirmed reply.

**Comment by bluebill1049** [comment]
I can confirm the above answer is correct. we do register on each useFieldArray action now, to enable deep nested field array action.

**Comment by dwiyatci** [comment]
Ok, thank you so much. I'll keep this mind if I'd get some usage cases that break/need adaptations (hopefully not :D). Have a good start into the week tomorrow! :)
