### ISSUE TITLE
[v7-React-Native]  Yup validations don't work

### ISSUE THREAD

**Issue by ahce** [react-hook-form/react-hook-form#4953]
**Describe the bug**
When the form is validated, the error object is empty.

**To Reproduce**

1. Go to v6 code sample
2. Click on submit
3. Check the validations
4. Try again with  v7 code sample

**Code sample link (Required)**
- [v6](https://snack.expo.io/@ahce/rn-hook-form-v6) (works)
- [v7](https://snack.expo.io/@ahce/rn-hook-form-v7) (don't work)

**Expected behavior**
v6 behavior.

**Smartphone**
- Device: Emulator
- OS: iOS 13.7 / Android 8.1.0
- Browser chrome
- Version 89

**Environment**

| Tech                | Version |
|---------------------|---------|
| expo       | 41.0.0 |
| yup | 0.32.9 |
| react-hook-form | 7.3.3 |
| @hookform/resolvers | 2.4.0 |

**Comment by jorisre** [comment]
Hi @ahce 

You should use the version 2 of @hookform/resolvers

**Comment by bluebill1049** [comment]
<img width="421" alt="Screen Shot 2021-04-26 at 8 34 38 am" src="https://user-images.githubusercontent.com/10513364/116011808-3fad5380-a66a-11eb-8777-e846f7b490f2.png">

It's an issue with loading with the old resolvers, v7 need v2 resolvers.

**Comment by ahce** [comment]
> <img alt="Screen Shot 2021-04-26 at 8 34 38 am" width="421" src="https://user-images.githubusercontent.com/10513364/116011808-3fad5380-a66a-11eb-8777-e846f7b490f2.png">
> 
> It's an issue with loading with the old resolvers, v7 need v2 resolvers.

Sorry for my mistake, this line is the problem: 
![image](https://user-images.githubusercontent.com/12452003/116012534-fd97f980-a5f8-11eb-8e55-f8853214b045.png)
