### ISSUE TITLE
With mui textfield = Warning: A component is changing an uncontrolled input to be controlled

### ISSUE THREAD

**Issue by devhyunjae** [react-hook-form/react-hook-form#4956]
**Describe the bug**

**Given**: Mui TextField with Controller wrapped
**When**: User enter something in input
**Then**:
```
Warning: A component is changing an uncontrolled input to be controlled.
This is likely caused by the value changing from undefined to a defined value, which should not happen.
Decide between using a controlled or uncontrolled input element for the lifetime of the component.
```

**To Reproduce**

1. Click on Enter userName input
2. type something
3. look at console
4. See warning log

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.
https://codesandbox.io/s/nervous-dewdney-4fd2t

**Expected behavior**
There should be no warning.

**Screenshots**
![Screen Shot 2021-04-26 at 9 43 35 AM](https://user-images.githubusercontent.com/12890257/116015362-e8ac7c00-a673-11eb-9d11-b9af3ca2a72c.png)

**Desktop (please complete the following information):**

- OS: macos bigsur 11.2.3
- Browser: Chrome
- Version: 90.0.4430.85

**Comment by devhyunjae** [comment]
Warning disappears when add init value
```
const { handleSubmit, control } = useForm<FormData>({
    defaultValues: {
      userName: ""
    }
  });
```

1 weird thing is, why does the demo csb in the doc,
https://codesandbox.io/s/react-hook-form-with-ui-library-ts-forked-qjgkx
dont have the initvalue code, but doesn't show this warning?

Anyway i will close the issue. Recommend somebody check the reason and update the doc or demo code

**Comment by bluebill1049** [comment]
you can use inline `defaultValue` as well :)

**Comment by devhyunjae** [comment]
@bluebill1049 Thanks!

1 quick question,

```
<Controller
  render={({ field }: any) => <TextField {...field} fullWidth />}
  name="userName"
  control={control}
/>
```

What type should i import to replace that `any` ?

**Comment by bluebill1049** [comment]
I don't think you shouldn't need to provide a type.

you can take a look at `ControllerProps`
