### ISSUE TITLE
[Bug] React Native custom register example from documentation doesn't work

### ISSUE THREAD

**Issue by MrPumpking** [react-hook-form/react-hook-form#4964]
**Describe the bug**
React Native custom register [example](https://snack.expo.io/@bluebill1049/react-hook-form-v7---basic) from [documentation](https://react-hook-form.com/get-started#ReactNative) throws an error when editing any of the input fields

This is probably due to `onChangeText` returning text value instead of event while [`handleChange`](https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L606) expects the passed value to be an event. Using the default register function spread (`{...register(name)}`) does not throw an error, but also doesn't update the values as [TextInput's `onChange`](https://reactnative.dev/docs/textinput#onchange) returns `{ nativeEvent: { eventCount, target, text} }`

**To Reproduce**

1. Go to https://snack.expo.io/@bluebill1049/react-hook-form-v7---basic
2. Edit any of the input fields
3. Check the error in console

**Snack link (Required)**
https://snack.expo.io/@bluebill1049/react-hook-form-v7---basic

**Expected behavior**
It should not throw an error when editing input's, and update the input values

**Screenshots**
![image](https://user-images.githubusercontent.com/9134970/116076283-5072bf00-a694-11eb-930a-3a86a6f4de79.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: 90

**Comment by bluebill1049** [comment]
should be this link: https://snack.expo.io/@bluebill1049/react-hook-form-v7---controller getting it updated. now

**Comment by divyanshu013** [comment]
Hey @bluebill1049 I also followed the same link from example [docs](https://github.com/react-hook-form/react-hook-form/tree/master/examples#react-native) - the basic [snack example](https://snack.expo.io/@bluebill1049/react-hook-form---basic). But this one isn't working fine on react native - updated values in inputs aren't getting reflected on submitting.

However the controller example is working fine. So is the basic usage (with register) not intended for react native?

**Comment by divyanshu013** [comment]
Thanks, I really liked the API with `register`, will switch to controller on react native 😅

**Comment by bluebill1049** [comment]
> Thanks, I really liked the API with `register`, will switch to controller on react native 😅 

Thanks, unfortunately react native doesn't have event target ':(

**Comment by borasumer** [comment]
"You will get the same performance boost and enhancement in React Native. To integrate with input component, you can use register your component or wrapped with Controller."

I am getting this completely wrong or this statement is wrong? it says you can use register OR wrapped with Controller.

**Comment by bluebill1049** [comment]
Thanks @borasumer I am fixing this so it's easier to understand.  https://github.com/react-hook-form/documentation/commit/4a4eaab355542a6438ca88befbb949d7d3619feb 

- register: only works for uncontrolled input and won't be able to reset or update input value
- Controller: works with the controlled component by isolating re-render and reporting/validating value update
