### ISSUE TITLE
Type 'Control<MyFormValues>' is not assignable to type 'Control<FieldValues>'

### ISSUE THREAD

**Issue by jacobroufa** [react-hook-form/react-hook-form#4965]
This seems like a duplicate of #2984.

**Describe the bug**

I am experiencing this issue after following the [Control example in your documentation](https://react-hook-form.com/ts#Control) and using any 7.x release. (have tried 7.0, 7.1, 7.2, 7.3 and patch versions of all)

I am calling `useForm` with a generic type in the shape of my form values -- the error occurs whether I use a generic or not -- and pass `control` to my components which wrap form values. My components accept a property `control: Control` per your example.

I get the error `error TS2322: Type 'Control<FormValues>' is not assignable to type 'Control<FieldValues>'. Types of property 'register' are incompatible.` and if I don't assign a generic it will just read the object type e.g. `Control<{ valuea: string, valueb: boolean }>`.

**To Reproduce**

* Assign a set of form values to the generic input of `useForm`
* Pass `control` to component which accepts `Control` type from react-hook-form
* Witness issue

**Codesandbox link (Required)**
https://codesandbox.io/s/nervous-rubin-pdh9g?file=/src/App.tsx

**Expected behavior**

I expect the generic type that I supply to `useForm` to be respected throughout the rest of the form interfaces as specified in the documentation.

**Screenshots**

<img width="551" alt="image" src="https://user-images.githubusercontent.com/450734/116092950-de867f80-a66b-11eb-9075-56784b0e91ed.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: All browsers -- fails basic TSC compilation
- Version: 7.x

**Comment by jordan-jarolim** [comment]
I have very similar issue. However, I think your TS definition is "wrong" (same as mine). You define control props as `Control` in `ICheckboxProps` but you pass there `Control<MyFormValues>`. I am struggling to find a way of how to use `useForm<FormInputsType>` with generic form components. I have found few solutions, so far:

1. type control prop `as unknown as FieldValues`
2. use JSX type generics https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#generic-type-arguments-in-jsx-elements
3. do not pass type generic to `useForm`

I hope there is a way to declare a shared form field component and use it with type-specific form? Can type generic be ignored on `Control` maybe?

**Comment by jordan-jarolim** [comment]
Now I also see that the doc is different from codesandbox! https://react-hook-form.com/ts#Control vs. https://codesandbox.io/s/control-2mg07

`function IsolateReRender({ control }: { control: Control }) {` vs . `function IsolateReRender({ control }: { control: Control<FormValues> }) {
`

**Comment by jacobroufa** [comment]
@jordan-jarolim thank you for your response! I've had no success with the options you mentioned. It looks like I might have to go with Option 2 despite my apprehension.

Option 1 (type control prop `as unknown as Control<MyFormValues>`) fails with:
```
error TS2365: Operator '>' cannot be applied to types 'Control<FieldValues>' and '{ defaultValues: { checked: boolean; }; mode: string; }'.
error TS2693: 'FormValues' only refers to a type, but is being used as a value here.
```

I have been avoiding Option 2 you mentioned because I feel like the syntax is confusing with JSX -- if at all possible I would like to avoid this.

Option 3 fails as mentioned in my original post:
> if I don't assign a generic it will just read the object type e.g. Control<{ valuea: string, valueb: boolean }>.

**Comment by jordan-jarolim** [comment]
1. `useForm<MyType>` in combination with `control={(yourControlInstance as unknown) as Control<FieldValues>}` works for me, its still just a workaround tho.
2. I agree! 
3. I am not sure if we have the same issue here...  if you don't pass generic to `useForm` it takes `FieldValues` as default and this is the same for `Control` type. You can try to define you interface as `control: Control<FieldValues>`

I hope we will get some support on this :)

**Comment by jacobroufa** [comment]
Jordan, I was able to get item 1 working. While it is kludgy it will be acceptable for now.

I was unsuccessful not passing a generic to `useForm` even with `Control<FieldValues>` typing (not just `Control` sans generic).

Regarding item 2 (Generics in JSX) I think it would be useful for a more accurately representative example in codesandbox e.g. not containing both components in the same file. My particular implementation is being built for reuse, and so the customized `FieldValues` per form will not be able to simply be imported and used by the fields themselves.

**Comment by BTiers** [comment]
Hello !
I'm not quite sure I understand the problem entirely but if the goal is to have a generic component over the type of the `useForm` data structure, I think something like this should do the trick:
```
export interface IReactHookFormFieldProps<T> {
  name: FieldPath<T>;
  control: Control<T>;
  rules?: RegisterOptions<T>;
}
```

Here is [a sandbox](https://codesandbox.io/s/throbbing-sound-yufjf) showing it with your code.

____

For fun I've made another one that ensure that the key passed to the component is a boolean

You can find this version [here](https://codesandbox.io/s/nervous-saha-gnc9d) (If you're interested)


Hope it can be helpful ! :)

**Comment by bluebill1049** [comment]
The one on the doc is wrong, just got it updated.

**Comment by jordan-jarolim** [comment]
@BTiers thanks, this works for me.

Off-topic question. What exactly is happening there? You define an interface to expect `T` as generic but then you don't pass it from the component. As TS cannot infer type correctly based on `T` that you did not pass, it's basically turning off TS check for `Control<T>`? Am I correct? Thanks.

**Comment by BTiers** [comment]
@jordan-jarolim Glad it helped ! :)
___

> You define an interface to expect T as generic but then you don't pass it from the component  

In this case TS will be able to infer the type of `T` based off the props. The only use-case I know about for using
`<Component<MyType> {...props} />` is when you when to opt out of TS compiler type inference which here isn't the case.

Here is a [great reference about that](https://react-typescript-cheatsheet.netlify.app/docs/advanced/patterns_by_usecase#generic-components)

> it's basically turning off TS check for Control<T> ?

I don't really get what you mean by "*turning off TS check*".
With the defined interface, TS expect a prop `control: Control<T>`, `T` being a type that `extends Record<string, any>` which is the same constraint as the `Control` itself.

**Comment by bluebill1049** [comment]
Thanks very much, @BTiers for the helping and solutions. 🙏

**Comment by artuska** [comment]
Why this issue is closed? It still throws an error.

My `LoginFormValues` type is 

```
export type LoginFormValues = {
  username: string;
  password: string;
};
```

My `useForm` is

```
const {
	control,
	handleSubmit,
	formState,
} = useForm<LoginFormValues>({
	defaultValues: {
		username: '',
		password: '',
	},
});
```

And my custom input is

```
export type InputProps = {
  ...
  control: Control<FieldValues, any>;
  ...
}
```

So, when i pass `control` to the InputField it throws an error above

```
<InputField
  name="username"
  size="large"
  theme="primary"
  color="light"
  namespace="login_form"
  control={control} // this is marked red
/>
```


```
Type 'Control<LoginFormValues, any>' is not assignable to type 'Control<FieldValues, any>'.
  The types of '_options.resolver' are incompatible between these types.
    Type 'Resolver<LoginFormValues, any>' is not assignable to type 'Resolver<FieldValues, any>'.
```

This is really frustrating.

**Comment by bestickley** [comment]
Error in my previous comment occurred because I had an attribute on the component that wasn't on the props of the component. Not sure why the error message was incorrect... but removing it fixed the issue for me.

**Comment by keemor** [comment]
Hi @bluebill1049 and @bestickley 

CSB -> https://codesandbox.io/s/react-hook-form-mui-5-v7-controller-ts-10d64d?file=/src/form/InputField.tsx

I'm also struggling with this error and I ended up using _control: any;_ 😁

Could you take look?

![image](https://user-images.githubusercontent.com/1793635/183838955-855166ab-fba1-4a49-8fe9-168806a2caa1.png)


My props for MUI components look this:
```js
type Props = Omit<TextFieldProps, "name"> & {
  control: Control<any, object>;
  disableErrorSpace?: boolean;
  name: string;
  maxLength?: number;
};

const InputField = ({
  control,
  disableErrorSpace,
  name,
  required,
  label,
  maxLength = 50,
  sx,
  ...restProps
}: Props) => (
  <Controller
    render={({ field: { ref, ...restField }, fieldState: { error } }) => (
```

**Comment by keemor** [comment]
This is how how I typed it:

https://codesandbox.io/s/react-hook-form-mui-5-v7-controller-ts-10d64d?file=/src/form/InputField.tsx

```js
import { Control, Controller, FieldValues, Path } from "react-hook-form";
import { TextField, TextFieldProps } from "@mui/material";
import { textFieldValidator } from "./validators";

type Props<T extends FieldValues> = Omit<TextFieldProps, "name"> & {
  control: Control<T, any>;
  disableErrorSpace?: boolean;
  name: Path<T>;
  maxLength?: number;
};

const InputField = <T extends FieldValues>({
  control,
  disableErrorSpace,
  name,
  required,
  label,
  maxLength = 50,
  sx,
  ...restProps
}: Props<T>) => (
  <Controller
    render={({ field: { ref, ...restField }, fieldState: { error } }) => (
      <TextField
      [...]
```
