### ISSUE TITLE
useFieldArray retains previously removed values

### ISSUE THREAD

**Issue by evanl5** [react-hook-form/react-hook-form#4967]
**Describe the bug**
When appending a field to an array field after an initial value in that array has been removed, the previously removed value will be added back.

**To Reproduce**

1. Go to sandbox
2. Scroll down to 'Friend 2'
3. Click 'Remove'
4. Click 'Add friend'
5. See previously removed friend

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-array-fields-forked-bdfge

**Expected behavior**
In the sandbox above, add friend should append empty values for first and last name.

**Desktop (please complete the following information):**

- OS: macOS
- Browser: chrome
- Version: 90

**Comment by bluebill1049** [comment]
read the doc plz.

**Comment by evanl5** [comment]
Can you be more specific? I have read the docs and I don't understand where the problem is. 

Additionally please see this example (forked from the docs) https://codesandbox.io/s/react-hook-form-reset-usefieldarray-forked-08ob1 where lastName is retained and firstName is not.

Thanks

**Comment by bluebill1049** [comment]
`friends.append()`

we argument is required and can't be `undefined`.

**Comment by bluebill1049** [comment]
> Can you be more specific? I have read the docs and I don't understand where the problem is.
> 
> Additionally please see this example (forked from the docs) https://codesandbox.io/s/react-hook-form-reset-usefieldarray-forked-08ob1 where lastName is retained and firstName is not.
> 
> Thanks

same problem as well.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/usefieldarray

more reference here: 

![Uploading Screen Shot 2021-04-27 at 9.15.16 am.png…]()
