### ISSUE TITLE
react-hook-form using @material-ui/core/Select

### ISSUE THREAD

**Issue by leandroZanatta** [react-hook-form/react-hook-form#497]
Good night,

I am trying to use react-hook-form with @ material-ui / core / Select, but I am unable to register the component.

In some searches I was instructed to use inputRef = {register ({required: true})}, but when I submit the form even with the field not selected, it returns no value for this field, nor the invalid tag.

Is there any different way to register this field?

**Comment by bluebill1049** [comment]
hey @leandroZanatta can you supply a code sandbox for your issue? also if innerRef is not working you may want to `register` during `useEffect`
```
useEffect(() => {
  register({name: 'test'}, {required: true});
}, [register])
```

and trigger value update with `setValue` :)

**Comment by leandroZanatta** [comment]
the code in 
https://codesandbox.io/s/silly-mcclintock-ntgo8

**Comment by bluebill1049** [comment]
because material-ui Select is not a native input, so register with ref (their ref is not the actual element) hence it doesn't work, 

<img width="1163" alt="Screen Shot 2019-11-13 at 1 38 08 pm" src="https://user-images.githubusercontent.com/10513364/68728253-e048b880-061a-11ea-844d-40e1839b61fb.png">

you need to use the custom register. see my reply above.

**Comment by bluebill1049** [comment]
how did you go with the customer register?

**Comment by bluebill1049** [comment]
ok I am going to close this issue, the solution is in my reply :) feel free to post the question in here next time https://spectrum.chat/react-hook-form?tab=posts the community may be able to help you out too. if still doesn't make sense or not working, feel free to continue with this issue and i will try my best to help :)

**Comment by JuanmaMenendez** [comment]
@bluebill1049  is there a cleaner way to register the <Select>, maybe using <Controller> ?

**Comment by JuanmaMenendez** [comment]
I found some good example https://codesandbox.io/s/rhf-mui-select-tqe89

**Comment by manualva7** [comment]
That works good. Interesting that I'm always relying on state, but the controller is managing it all the time.

I think the plugin should clarify to not rely on state. It's a bit confusing. All data is passed from the handleSubmit handler to the final onSubmit function. 

That parameter there, data, replaces the need for state.

`const onSubmit = (data) => {
        console.log(data)
        alert('payload = ' + JSON.stringify(data))
        mock.onGet("/register").reply(200, {
            users: [{
                id: 1,
                fname: data.fname,
                lname: data.lname,
                email: data.email,
                email_confirm: data.email_confirm,
                password: data.password,
                password_confirm: data.password_confirm,
                address: data.address,
                address_2: data.address_2,
                city: data.city,
                state: data.state,
                country: data.country,
                postal: data.postal,
                phone: data.phone,
                phone_type: data.phone_type,
                linkedin_url: data.linkedin_url,
                skype: data.skype
            }],
        });

        axios.get("/members").then(function (response) {
            console.log(response.data);
        });
    };`

Great work and thanks!

**Comment by hulivets** [comment]
![Screenshot from 2020-05-30 20-30-21](https://user-images.githubusercontent.com/48622868/83335291-7d67f780-a2b4-11ea-90ac-db7024fb7807.png)

**Comment by challme28** [comment]
Off all the answers here @JuanmaMenendez's answer was what worked for me. [Option 3](https://react-hook-form.com/get-started#WorkwithUIlibrary) didn't work for me because I need the `required` option. But now that I look at the first answer the `required` option was not another property next to `name`, it was another param to the `register()` function.

**Comment by fabriciocarboni** [comment]
After some research and tests I could manage that like this:
`
<FormControl variant="outlined" size="small" fullWidth>
                <InputLabel>Language</InputLabel>
                <Controller
                  control={control}
                  name="studentLanguage"
                  defaultValue=""
                  rules={{ required: true }}
                  error={errors.studentLanguage && true}
                  as={
                    <Select label="Language *" defaultValue="">
                      <MenuItem value="french">French</MenuItem>
                      <MenuItem value="english">English</MenuItem>
                    </Select>
                  }
                />
              </FormControl>
`

**Comment by viniciushvc** [comment]
I'm trying to create a component of this example, but it doesn't work, has anyone get it?

> After some research and tests I could manage that like this:
> 
> ![image](https://user-images.githubusercontent.com/19577484/85928215-554ec280-b879-11ea-80a4-441fcb55e493.png)

**Comment by bluebill1049** [comment]
@viniciushvc take a look the doc, there is an example of cab: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r

**Comment by v1adko** [comment]
@bluebill1049 I've added the onChange listener on the `form` level right along side `onSubmit`.
It triggers on text fields but does not trigger on select. Any way to make this work for all Controller-wrapped inputs?
Here's a forked sandbox from @JuanmaMenendez
https://codesandbox.io/s/rhf-mui-select-forked-gp59j

**Comment by bluebill1049** [comment]
> @bluebill1049 I've added the onChange listener on the `form` level right along side `onSubmit`.
> It triggers on text fields but does not trigger on select. Any way to make this work for all Controller-wrapped inputs?
> Here's a forked sandbox from @JuanmaMenendez
> https://codesandbox.io/s/rhf-mui-select-forked-gp59j
> 
> ![Screen Shot 2021-01-26 at 6 51 33 PM](https://user-images.githubusercontent.com/11582927/105877674-e735ce00-6008-11eb-9898-a0f4a38ceb36.png)

onChange will only work for the input itself follow `<input onChange />` i have a feeling that Select component is probably not a standard HTML component, that's why it's not working. you can switch to `useWatch`, I think it would work.

**Comment by v1adko** [comment]
Thank you @bluebill1049, the useWatch approach did work for me, had to pass around the form control object, but it worked.
Was a bit confused about the inconsistency in the onChange, but thanks for clearing that up.

**Comment by bluebill1049** [comment]
> Thank you @bluebill1049, the useWatch approach did work for me, had to pass around the form control object, but it worked.
> Was a bit confused about the inconsistency in the onChange, but thanks for clearing that up.

Good news, in v7 next major version. you do the following

```
watch((data) => {
  console.log('entire form data', data);
});
```
