### ISSUE TITLE
[version 7.3.4] CheckBox undefined value in form data

### ISSUE THREAD

**Issue by fabrusso** [react-hook-form/react-hook-form#4978]
**Describe the bug**
I'm trying to connect a CheckBox input to an useForm with {...register("checkbox")} as name.
Currently the checkbox is always undefined, also if the checked property is passed as true.

**To Reproduce**

1. Create an useForm form
2. Add a CheckBox
3. console.log the form data to console
4. Checkbox value is undefined

Sandbox Demo:
https://codesandbox.io/s/magical-sea-9t8vf?file=/src/App.js

**Expected behavior**
Show the value of checkbox as `true` or `false`, or checked and not checked

**Devices**
Trying this on 86.0b6 (64 bit) Mozilla for Developers
Package version: 7.3.4

**Comment by bluebill1049** [comment]
plz use `useController` or `Controller` for controlled input.

https://react-hook-form.com/api/usecontroller
https://react-hook-form.com/api/usecontroller/controller

**Comment by fabrusso** [comment]
> plz use `useController` or `Controller` for controlled input.
> 
> https://react-hook-form.com/api/usecontroller
> https://react-hook-form.com/api/usecontroller/controller

I modified the Demo with the `<Controller />` component:

```
<Controller
          control={control}
          name="checkbox"
          render={({ field: { onChange, value, name, ref } }) => (
            <Input name={name} value={value} ref={ref} onChange={onChange} />
          )}
 />
```

fot me It's still returning `undefined`
