### ISSUE TITLE
Type error on register name parameter

### ISSUE THREAD

**Issue by MercurialWeb** [react-hook-form/react-hook-form#4981]
I've this error on next build when i use register in a Functional Component:

```
interface Props {
   name: string
}
```
```
Type error: Argument of type 'string' is not assignable to parameter of type '`${string}` | `${string}.${string}` | `${string}.${number}`'.

  45 |         <select
> 46 |             {... register(name, {
```

If i define a const like this: `const name='firstName';` I've no problem, but in Functional Component it throws this error on next build.

Maybe the name prop needs this definition:
``string | `${string}` | `${string}.${string}` | `${string}.${number}``

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848
