### ISSUE TITLE
[v7-React-Native] Ref isn't ready after first render

### ISSUE THREAD

**Issue by ahce** [react-hook-form/react-hook-form#4985]
**Describe the bug**
After second render the ref is ready.

**To Reproduce**

1. Go to code sample
2. Focus on firstName input
3. Press next button on keyboard (the focus on second input won't work)
4. Press submit button (this dispatch a new render)
5. Try again step 2 and 3

**Code sample link**
- [snack expo](https://snack.expo.io/@ahce/rn-hookform-ref)

**Expected behavior**
Ref ready after first render.

**Smartphone**
- Device: Emulator
- OS: iOS 13.7 / Android 8.1.0

**Environment**

| Tech                | Version |
|---------------------|---------|
| expo       | 41.0.0 |
| react-hook-form | 7.3.4 |Ω

**Comment by JamesWong1999** [comment]
That's expected behavior right? `ref` is a callback that gets register afterward. you should be using `useEffect` with `setFocus`.

**Comment by bluebill1049** [comment]
this is getting fixed: https://github.com/react-hook-form/react-hook-form/commit/65520033b2e838dc0f42921c28efa00f956dcf54

you should be using the `setFocus` method instead of anything from the `control` object. I will release it tonight.

**Comment by ahce** [comment]
@bluebill1049 why the field ref is undefined but the ref in fieldsRef object is defined? Check [this example](https://snack.expo.io/@ahce/rn-hookform-ref) plis, FirstName component line 16-17
