### ISSUE TITLE
Nested useArrayField looses value after adding or removing new fields

### ISSUE THREAD

**Issue by shubham-sns** [react-hook-form/react-hook-form#4987]
**Describe the bug**
I am using useFieldArray one nested inside another

## Here's link
[link to the codesandbox](https://codesandbox.io/s/react-hoook-form-issue-11qcz?file=/src/App.js)

**Steps to reproduce**
1. Create new question field by clicking
2. Create new option field by clicking `add option` button
3. Insert text in that option field
4. now add another option by clicking `add option` button
5. value in option1 should now disappear 
6. check console log for `watch()` values, they are spreaded like this 👇
![image](https://user-images.githubusercontent.com/61004681/116369080-9790b980-a826-11eb-868a-5808bd3a4407.png)

```js
const schema = {
  // i am top-level field array
  questions: [
    {
      createdAt: new Date(),
      question: {
        title: "",
        isRequired: true,
        options: ["option1", "option2"] // I am nested field array
      }
    },
    {
      createdAt: new Date(),
      question: {
        title: "",
        isRequired: true,
        options: []
      }
    }
  ]
};
```

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by shubham-sns** [comment]
I have updated description.

**Comment by bluebill1049** [comment]
can you provide the steps to reproduce?

**Comment by shubham-sns** [comment]
sorry, I have added now

**Comment by bluebill1049** [comment]
<img width="775" alt="Screen Shot 2021-04-28 at 6 48 00 pm" src="https://user-images.githubusercontent.com/10513364/116375067-439bca00-a852-11eb-9f4c-3547979ee054.png">

we don't support flat arrays. This is the root cause.
