### ISSUE TITLE
Setting a date using setValue does not work properly

### ISSUE THREAD

**Issue by bmichotte** [react-hook-form/react-hook-form#4988]
Hi there,

if you set a date using the `setValue` method having the `valueAsDate: true` on that field, the value from that field (either on `handleSubmit` and `getValues`) is a string, but if you change it using the datepicker, it becomes a js date.

The issue is not here if you set the date on the `defaultValue` parameter

**Codesandbox link (Required)**
Here is a Codesandbox with an input with `defaultValue` and an input using `setValue`
https://codesandbox.io/s/react-hook-form-basic-forked-kpo23

**Expected behavior**
Getting the value from a date field setted with `setValue` should return a js date to respect the `valueAsDate` option

``` 
"dependencies": {
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-hook-form": "7.3.4",
    "react-scripts": "4.0.3"
  },
```

**Comment by bluebill1049** [comment]
Note this is only going to work with JS, I am patching this, but we can't reverse input value from `date` to string.

eg:

```tsx
function App() {
  const { register, handleSubmit, setValue } = useForm<{
    setStringDate: Date
  }>();

  React.useEffect(() => {
    setValue('setStringDate', '2021-04-23'); // this will result a type error
  }, []);

  return (
    <form onSubmit={handleSubmit((data) => {
      console.log(data);
    })}>
      <input
        type="date"
        {...register('setStringDate', { valueAsDate: true })}
      />
      <input type="submit" />
    </form>
  );
}
```

**Comment by bmichotte** [comment]
Thanks for the quick update and fix

**Comment by csulit** [comment]
This isn't working if valueAsDate is set to true.

**Comment by leochoo** [comment]
@bluebill1049 My code in v6 had no problem, but migrating it to v7 is causing this issue for me...
Is this a new bug in V7..?

**Comment by bluebill1049** [comment]
could you share a reproducible codesandbox?

**Comment by Moshyfawn** [comment]
[Works fine for me](https://codesandbox.io/s/agitated-panini-t90v01?file=%2Fsrc%2FApp.tsx), I believe

**Comment by rzec-allma** [comment]
While the above example does show the setting the date does change the value that is being stored under the hood, the input itself does not update when the date value it set which seems like a bug.
