### ISSUE TITLE
validation inconsistencies between `onSubmit` and `triggerValidation`

### ISSUE THREAD

**Issue by chrise86** [react-hook-form/react-hook-form#499]
Given the following schema:

```javascript
const validationSchema = yup.object().shape({
  // ... fields truncated
  treatments: yup.array(
    yup.object().shape({
      id: yup.string(),
      productId: yup.string().required('required'),
      quantity: yup.number().required('required'),
      calibrationDate: yup.date().required('required'),
      calibrationSheet: yup.boolean().required('required'),
      freeReason: yup.string(),
      lineItemNumber: yup.number().required('required'),
      _destroy: yup.boolean(),
    })
  )
})
```

and registering the treatments manually, i.e. `register({ name: 'treatments' })`

When submitting a form normally (i.e. via submit button) the validation for the treatment fields works as expected.

However, using `await triggerValidation()` does not validate the nested fields, and the `errors` object does not contain a `treatments` key.

**Comment by bluebill1049** [comment]
could you submit a codesandbox for us to reproduce?

**Comment by bluebill1049** [comment]
going to close now, feel free to re-open once we get a codesandbox to reproduce the problem. thanks
