### ISSUE TITLE
[v7] watch method return types when over 10 keys watched

### ISSUE THREAD

**Issue by BTiers** [react-hook-form/react-hook-form#4994]
**Describe the bug**
When using `watch` with an array of more than 10 keys, the types of the returned tuple fallback to the behaviour observed before #4721 was merged  I believe in `v7.0.6` (aka: a `union` of each possible types of the retrieved `FieldValue`)

**To Reproduce**

1. Go to [this sandbox](https://codesandbox.io/s/cranky-kapitsa-3sd8m?file=/src/App.tsx)
2. Hover variables [a1, ..., j1] from the first `watch` call (The one with 10 keys) types are correct
3. Hover variables [a2, ..., k2] from the second `watch` call. See the variables being falsely typed.

**Expected behavior**
The types should be correct in both cases.

___
<details>

<summary> Potential solutions </summary>

I see two solutions to get rid of this typing issue.

- "Manually" type the watch call
```ts
  const [key1, ..., key11] = watch<["key1", ..., "key11"]>(["key1", ..., "key11"]);
```

***Pros***: It doesn't require any changes to the current API. (and this issue can be closed right away)
***Cons***: Even tho it might be a niche use case, it's a bit verbose and the DX (that I found wonderful since v7) is less enjoyable.

- Make use of [the variadic tuple typing](https://github.com/microsoft/TypeScript/pull/39094) of TS 4.0
For what I have tested this could be done by changing [this definition](https://github.com/react-hook-form/react-hook-form/blob/4cb6579b03e5f2a5b22ed2c04d5b6df037b33965/src/types/form.ts#L167-L346) to:
```ts
  <TFieldNames extends Array<FieldPath<TFieldValues>>>(
    fieldNames: readonly [...TFieldNames],
    defaultValue?: UnpackNestedValue<DeepPartial<TFieldValues>>,
  ): [...FieldPathValues<TFieldValues, TFieldNames>];
```

***Pros***: It provides a better DX imho.
***Cons***:  It could potentially be a breaking change if people have typed their `watch` like so (even tho I cannot see a use case to do so):
```ts
watch<"k1", "k2">(["k1", "k2"])
```
as it would need to be define like this afterward:
```ts
watch<["k1", "k2"]>(["k1", "k2"])
```

</details>

If, by chance, you would like to see this implemented, I'll be more than happy to create a PR.

**Comment by bluebill1049** [comment]
> If, by chance, you would like to see this implemented, I'll be more than happy to create a PR.

Yes, please send us a PR if you have time. 🙏

**Comment by BTiers** [comment]
@bluebill1049 I'll work on this this evening :)

I've notice that `getValues` is having the same typing issue that `watch` had prior to `7.0.6` so i'll include this in the PR if that's ok for you ?

**Comment by bluebill1049** [comment]
Sounds great to me. Thanks a lot. 🙏
