### ISSUE TITLE
Test references 'test' instead of 'test1'

### ISSUE THREAD

**Issue by uglow** [react-hook-form/react-hook-form#5001]
Hi, I just noticed this while trying to get `setValueAs` to work on a field that has a `validate` function, just like what is in this test. However it appears that the test has a type on this line:
https://github.com/react-hook-form/react-hook-form/blob/50ee46bab80f3673573adc1ab4b48114b7bf406e/src/__tests__/useForm/register.test.tsx#L617

I think it should say `{errors.test1 &&` instead of `{errors.test &&`

**Comment by bluebill1049** [comment]
you are right, send us a PR.

**Comment by uglow** [comment]
Thanks for your work @bluebill1049 ! I don't have time right now, unfortunately. The behaviour I've been seeing is that `setValueAs()` is called first (correct), then `validate()` is called with the transformed-value from `setValueAs()` (correct), but then the input field does *not* show the transformed-value. I suspect that when/if this test is updated, it will start failing.

To work around this, you can use the `onBlur` / `onChange` callback to modify the change-event-control's value:
```
const { onBlur: fldOnBlur, ...fldHookProps } = register(
    'myField',
    {
      validate: async (v) => await validateField(v),
    },
  )
  
// On the field itself (JSX):
{...fldHookProps}
onBlur={(e) => fldOnBlur(formatField(e))}
```
