### ISSUE TITLE
TypeScript definition mismatch in `formState.errors` for array field

### ISSUE THREAD

**Issue by giovannipiller** [react-hook-form/react-hook-form#5004]
**Describe the bug**
TypeScript definition mismatch for `formState.errors.something` when `something` is defined to be an array.

**To Reproduce**

1. Go to https://codesandbox.io/s/nifty-sunset-nppo5?file=/src/App.tsx
2. Check the TS error on App.tsx

**Note:** also check the definition of my custom interface passed to `useForm()`.

----

Looking for a "real world" example?
Here I'm using yupResolver to validate an array field:

1. Go to: https://codesandbox.io/s/loving-monad-zbmgv?file=/src/App.tsx
2. Click on 'Submit'
3. The validation error will be printed as a string in the page. Code runs fine.

In the code, `errors.arrayField?.message` is marked as a TypeScript error, that's because `errors.arrayField` is expected to be an array of `FieldError[]`. However, this is not the case when the code is executed, where `errors.arrayField` is a simple `FieldError`.

**Codesandbox link (Required)**
https://codesandbox.io/s/nifty-sunset-nppo5?file=/src/App.tsx

**Expected behavior**
I believe `errors.arrayField` should be of type `FieldError` rather than `FieldError[]`.

**Screenshots**
<img width="658" alt="Screenshot 2021-04-29 at 17 35 51" src="https://user-images.githubusercontent.com/628799/116578104-5cb78000-a911-11eb-9f69-5b668165e9bb.png">

**Comment by bluebill1049** [comment]
https://react-hook-form.com/ts

Use NestedValue type instead.
