### ISSUE TITLE
Add a function to validate form fields using Yup and custom async functions

### ISSUE THREAD

**Issue by giovanniantonaccio** [react-hook-form/react-hook-form#501]
**Is your feature request related to a problem? Please describe.**
Today it is not possible to to mix async validations with Yup validations. We can only pass an Yup object that will check the whole form or create our own functions if we want to validate the fields individually.

**Describe the solution you'd like**
It would be great to have a generic function where we could pass the key of the field we want to validate with its value, the schema for that specific field and other optional parameters if the user need to pass them for the function.

**Describe alternatives you've considered**
I made some tests for a project that I'm working and solved this problem creating a function to first solve the Yup validation and then the custom validations if they exist:

```javascript
const validate = async (value, key, schema, params) => {
  return await schema.yupValidations[key]
    .validate(value)
    .then(value => {
      if (schema.customValidations[key])
        return schema.customValidations[key](value, params);
    })
    .catch(err => err.message);
};

export default validate;

```

For each form of the system I create a FormSchema file like the one below, where instead of having one Yup object for the whole form, I create one object for each field.

```javascript
import * as Yup from "yup";
import api from "../services/api";

const SignupFormSchema = {
  email: Yup.string()
    .required("Email is required")
    .email("Invalid format"),
  name: Yup.string()
    .required("Name is required")
    .min(5, "Min length is 5"),
};

async function NameValidation(value) {
  try {
    const result = await api.get("https://swapi.co/api/people/1/?format=json");
    if (value !== result.data.name) return "Invalid name";
  } catch (err) {
    return "Could not validate name. Network error";
  }
}

export default {
  yupValidations: SignupFormSchema,
  customValidations: {
    name: NameValidation,
  }
};
```

When I register the component I pass the schemaValidate
```javascript
inputRef={register({
        validate: value => schemaValidate(value, field, schema, params)
      })}
```

And the form could be written like this:
```javascript
import React from "react";
import useForm from "react-hook-form";

import schema from "../../schemas/SignupFormSchema";

import TextInput from "../../components/TextInput";
import Button from "../../components/Button";

export default function SignupForm() {
  const { register, errors, handleSubmit, clearError } = useForm({
    mode: "onBlur"
  });

  const props = {
    register,
    errors,
    clearError,
    schema
  };

  const onSubmit = (data, e) => {
    e.preventDefault();
    console.log(data);
  };

  return (
    <form>
      <TextInput props={props} field="email" label="Email" />
      <TextInput props={props} field="name" label="Name" />
      <Button
        handleSubmit={handleSubmit(onSubmit)}
        label="submit"
        color="primary"
      />
    </form>
  );
}

```
**Additional context**
You can check the example where I tested this solution with TextFields, Selects and DatePickers from Material-UI here: https://github.com/giovanniantonaccio/react-hook-form-test,

**Comment by bluebill1049** [comment]
Hey @giovanniantonaccio thanks for the feature request. However, it's not very clear with your objective here, there is `validate` function in the register already. We are already planning to have a generic way to using external validation schema, maybe that's what you are after?

**Comment by giovanniantonaccio** [comment]
Hey @bluebill1049, the idea is to give users the possibility to use Yup validation individually for each field, instead of validating the whole form at once. The customValidation would be useful for situations where the user want to mix async validations (checking a value in an API for example) with Yup or if he wants to pass parameters for the schema.

It is possible to do this with a little bit of code and the tools that the lib already provides, but it would be great to have a function to do this for us directly from the lib.

If you guys didn't think that this would apply for the project at least I hope that this could help other people that face a similar problem like mine, because I didn't find any other lib to solve this kind situation :)

**Comment by bluebill1049** [comment]
oh ok thanks, @giovanniantonaccio. Let's leave this for a while to see if someone else facing a similar problem and then we can go from there. 👍

**Comment by bluebill1049** [comment]
going to close this issue now, you guys can keep upvote this issue if you think it's necessary.

**Comment by estshy** [comment]
@giovanniantonaccio If I understood your issue correctly then I think it was facing similar problem, the think which I did to solve it was as follow

components/form/validationSchemaContext.js
```
import React from 'react'

const ValidationSchema = React.createContext({});

export const ValidationSchemaProvider = ValidationSchema.Provider;
export const ValidationSchemaConsumer = ValidationSchema.Consumer;

export default ValidationSchema;
```

components/form/index.js
```
import React from 'react';
import { FormContext } from 'react-hook-form';

import {ValidationSchemaProvider} from './validationSchemaContext';

export default ({className, methods, validationSchema, onSubmit, children}) => (
  <ValidationSchemaProvider value={validationSchema}>
    <FormContext {...methods} >
      <form className={className} onSubmit={methods.handleSubmit(onSubmit)}>
        {children}
      </form>
    </FormContext>
  </ValidationSchemaProvider>
);
```

components/input/index.js
```
import React, { useContext } from 'react';
import { useFormContext } from 'react-hook-form';

import ValidationSchemaContext from '../form/validationSchemaContext';

export default ({ name, ...props }) => {
      const { register, errors } = useFormContext();
      const validationSchema = useContext(ValidationSchemaContext);

      <input
        name={name}
        ref={register({
          validate: (val) => {
            return validationSchema.validateAt(name, {
              [name]: val
            })
            .then(() => true)
            .catch((e) => e.message)
          }
        })} />
});
```

**Comment by Saoirse-Derry** [comment]
The main use case I have for this is when checking that a value is unique with an api call, for example, onBlur to check if the username/email value already exists.
