### ISSUE TITLE
[v7-React-Native] Validations don't work correctly with hermes enabled (Android only)

### ISSUE THREAD

**Issue by ahce** [react-hook-form/react-hook-form#5011]
**Describe the bug**
When hermes is enabled, the validations don't work, if hermes is disabled works normally. 
![rn-hf-hermes](https://user-images.githubusercontent.com/12452003/116774160-af379000-aa28-11eb-98b6-29011ce9cb03.gif)

**To Reproduce**

1. clone this [repo](https://github.com/ahce/rn-hook-form-demo)
2. open terminal
3. yarn install / npm install
4. yarn start / npm start
5. open new terminal
4. yarn android / npm run android
5. press submit button and check validations
7. type in the text input and check validations
8. disable [hermes](https://github.com/ahce/rn-hook-form-demo/blob/main/android/app/build.gradle#L81)
9. try again from step 4 to 7

**Code sample link**
- [repo](https://github.com/ahce/rn-hook-form-demo)

**Expected behavior**
Same behavior with or without hermes
![rn-hf-no-hermes](https://user-images.githubusercontent.com/12452003/116774169-b9598e80-aa28-11eb-986a-a9ce56029f90.gif)

**Smartphone**
- Device: Emulator
- OS: Android 10

**Environment**

| Tech                | Version |
|---------------------|---------|
| react      | 16.13.1 |
| react-native       | 0.63.4 |
| react-hook-form | 7.3.6 |

**Comment by bluebill1049** [comment]
Try to reproduce it here: https://snack.expo.io/@bluebill1049/react-hook-form-v7---controller.

**Comment by ahce** [comment]
> Try to reproduce it here: https://snack.expo.io/@bluebill1049/react-hook-form-v7---controller.

Expo doesn't have this issue because expo doesn't enable [hermes](https://reactnative.dev/docs/hermes).

**Comment by bluebill1049** [comment]
what difference is that going to make? I am not familiar with hermes.

**Comment by bluebill1049** [comment]
I would copy what's in my expo and export it to your project and test it out yourself.

**Comment by ahce** [comment]
> what difference is that going to make? I am not familiar with hermes.

Hermes is a JS engine, provides some improvements, perfomance, small app and others.
I don't know it's failing with react-hook-form

**Comment by ahce** [comment]
> I would copy what's in my expo and export it to your project and test it out yourself.

It also has the issue.
The submit count doesn't increment, without hermes works.

**Comment by bluebill1049** [comment]
<img width="816" alt="Screen Shot 2021-05-01 at 6 39 33 pm" src="https://user-images.githubusercontent.com/10513364/116776612-94a6fa80-aaac-11eb-8d9c-c60adf6b044e.png">

I don't even see a submit count in my example.

**Comment by ahce** [comment]
It is a detail to detect the issue.
I added version 6 with switch to change (with v6 hermes works).
![image](https://user-images.githubusercontent.com/12452003/116778153-46f3a900-aa3e-11eb-9601-66ffe8b463f1.png)
Please download the repo.

**Comment by bluebill1049** [comment]
I am having a hard time getting it working react-native... can you reproduce that in expo app? or expo doesn't support hermes?

**Comment by ahce** [comment]
> I am having a hard time getting it working react-native... can you reproduce that in expo app? or expo doesn't support hermes?

Expo doesn't use hermes.
The issue could be similar to [this](https://github.com/immerjs/immer/issues/626) 

I uploaded the apks:
- [apk with hermes](https://drive.google.com/file/d/18zg4LE1OLos444H36bSxVvfj04h0cej1/view?usp=sharing)
- [apk without hermes](https://drive.google.com/file/d/1kn35yG9gchOby4rmCVRjCkii2zYrVraQ/view?usp=sharing)

Also I updated the repo with form state info.
![image](https://user-images.githubusercontent.com/12452003/116792146-e5a6f680-aa8c-11eb-89c1-1457b0e608e4.png)

**Comment by bluebill1049** [comment]
Can u try to install a 'Proxy' ployfill? Apk doesn't really help me to debug the issue.

**Comment by bluebill1049** [comment]
<img width="952" alt="Screen Shot 2021-05-02 at 8 56 07 am" src="https://user-images.githubusercontent.com/10513364/116796985-3ddd0780-ab24-11eb-9cbd-fe96690fb90b.png">

it's on and it's working for me.

https://user-images.githubusercontent.com/10513364/116797007-6e24a600-ab24-11eb-818d-35c3154a4d08.mp4

**Comment by ahce** [comment]
This issue only happens on Android, iOS doesn't enable hermes.

**Comment by bluebill1049** [comment]
-_-

**Comment by ahce** [comment]
[proxy-polyfill](https://www.npmjs.com/package/proxy-polyfill) solved this issue!
I [updated](https://github.com/ahce/rn-hook-form-demo/commit/3dce6ab10794f33a889280fd56ac446d105e4dd9) the sample repo!

**Comment by bluebill1049** [comment]
<img width="935" alt="Screen Shot 2021-05-02 at 9 24 23 am" src="https://user-images.githubusercontent.com/10513364/116797352-36b7f880-ab28-11eb-837a-83e422772fa2.png">

it's on ios as welll

**Comment by bluebill1049** [comment]
so it's PROXY???

**Comment by ahce** [comment]
> so it's PROXY???

Yes!!!

**Comment by bluebill1049** [comment]
> > so it's PROXY???
> 
> Yes!!!

AWESOME! this needs to go into FAQ.

**Comment by ahce** [comment]
> <img alt="Screen Shot 2021-05-02 at 9 24 23 am" width="935" src="https://user-images.githubusercontent.com/10513364/116797352-36b7f880-ab28-11eb-837a-83e422772fa2.png">
> 
> it's on ios as welll

Yes, but since react-native >= 0.64, the sample repo uses 0.63.4

**Comment by bluebill1049** [comment]
<img width="959" alt="Screen Shot 2021-05-02 at 5 23 48 pm" src="https://user-images.githubusercontent.com/10513364/116805657-33922c00-ab6b-11eb-8482-8387fc919515.png">

**Comment by GfxKai** [comment]
Proxy is now enabled by default from Hermes v0.7, so this step is no longer necessary https://github.com/facebook/hermes/releases/tag/v0.7.0

**Comment by bluebill1049** [comment]
> Proxy is now enabled by default from Hermes v0.7, so this step is no longer necessary https://github.com/facebook/hermes/releases/tag/v0.7.0

we have removed `proxy`, so react native will share the same perf enhancement as web.
