### ISSUE TITLE
V7: Trigger returns void, but is supposed to return Promise<boolean> according to Docs for V7

### ISSUE THREAD

**Issue by nigel-dewar** [react-hook-form/react-hook-form#5013]
**Describe the bug**
"react-hook-form": "^7.1.1".   With;
"react": "^17.0.1",
"typescript": "^4.1.3",

According to docs here https://react-hook-form.com/api/useform/trigger  , Trigger is supposed to return a Promise<boolean>.

![image](https://user-images.githubusercontent.com/9402456/116828862-d6d35780-abe4-11eb-9e95-307cf0e14ebe.png)

But.. It doesn't currently. It instead returns void.

![image](https://user-images.githubusercontent.com/9402456/116828906-02564200-abe5-11eb-9687-b8d59fc4ff6e.png)

**Comment by bluebill1049** [comment]
Use the latest.

**Comment by nigel-dewar** [comment]
Thanks Bill. You must be on similar timezone as me, Im  in East Coast Aussie.

cheers mate

**Comment by bluebill1049** [comment]
That's it mate. Keep an eye on the changelog .
