### ISSUE TITLE
v7: registering the input causing onChange to fail

### ISSUE THREAD

**Issue by adiusz** [react-hook-form/react-hook-form#5021]
**Hello there.** Since I migrated to v7, I'm facing an issue with my inputs. I would consider that I'm doing something wrong, but in v6 everything worked just fine. 
**Problem is, when I register the input, onChange is being simply ignored.** 

### inputs in v7 looks like this:
```
<input                                                  
    type="text"                                                                         
    id="name"                                           
    onChange={e => setName(e.target.value)}             
    {...register('name', { required: true })}           
/>                                                      
```

### in v6 it looked like that:
```
<input                                                  
    type="text"                                                                         
    id="name"                                           
    onChange={e => setName(e.target.value)}             
    ref={register({ required: true }, formFieldRef)}
/>     
```

### Demo: 
I provided the CodeSandbox demo here: https://codesandbox.io/s/react-hook-form-v7-form-context-forked-p4i1x
Also here is the link to the v6 version with the same feature working just fine (just type in first input and see the console - state is being updated like expected):
https://codesandbox.io/s/react-hook-form-example-forked-iq43b

### Expected behavior
I'm using useState hook to get state value saved so I can use it somewhere else in the app.
I simply wish to react-hook-form let me use this onChange method just like it did with v6. 

**Desktop (please complete the following information):**

- OS: macOS Big Sur 11.3.1
- Browser: Opera
- Version: 75

Also I have a solution - I can update the state in onSubmit function. But since it was working in v6, why shouldn't it work in v7, right? 😀

**Comment by bluebill1049** [comment]
<img width="943" alt="Screen Shot 2021-05-04 at 4 42 58 pm" src="https://user-images.githubusercontent.com/10513364/116968440-c9f35880-acf7-11eb-8f91-ca05152d5dde.png">

Made a new section, hope that will make thing a bit clearer. 🙏 Let me know if you still have questions.

**Comment by adiusz** [comment]
Yes, 2 questions:

1. How can I make this input required and set pattern with message to it?
For example like this:
```
{...register('email',{
        required: true,
        pattern: {
            value: /\S+@\S+\.\S+/,
            message: `Wrong email format`
        }})
}
```
2. Look at the screen below. Why does WebStorm doesn't recognize this firstName.onChange(e) syntax?
![Zrzut ekranu 2021-05-4 o 13 05 49](https://user-images.githubusercontent.com/20825919/116994787-74a84e80-acd9-11eb-96ef-018d2be0ce07.png)

**Comment by bluebill1049** [comment]
> How can I make this input required and set pattern with message to it?

what do you mean?

> Look at the screen below. Any idea why doesn't WebStorm recognize this firstName.onChange(e) syntax? Is it necessary?

Not sure, if you are using Typescript, it should give you the correct type for the output.

**Comment by adiusz** [comment]
> what do you mean?
I mean validation, something like this: 
```
{...register('name',{
  required: 'This field is required'
  maxLength: {
      value: 40,
      message: 'the allowable number of characters is 40'
  }
})}
``` 
> Not sure, if you are using Typescript, it should give you the correct type for the output.
Nope, no TypeScript here

**Comment by bluebill1049** [comment]
> I mean validation, something like this:

validation looks fine to me.

**Comment by adiusz** [comment]
It is fine, but with that syntax onChange isnt working. I'm wondering how can I apply this validation to the example you posted to my original post question

**Comment by adiusz** [comment]
> <img width="943" alt="Screen Shot 2021-05-04 at 4 42 58 pm" src="https://user-images.githubusercontent.com/10513364/116968440-c9f35880-acf7-11eb-8f91-ca05152d5dde.png">
> 


I mean this syntax.

**Comment by bluebill1049** [comment]
check out the doc again, I have included the validation. it's the same as without validation.

`const firstName = register('firestName', { required: true })`

**Comment by adiusz** [comment]
I had to do some refactoring in order to make my app works in v7, seems to me like v6 was more flexible. Anyway, thanks for help and good luck with your project 🙂
