### ISSUE TITLE
Problem with typings

### ISSUE THREAD

**Issue by pret-a-porter** [react-hook-form/react-hook-form#5029]
**Describe the bug**
Typings of error is incorrect, when using array in field

**To Reproduce**

1. Go to https://codesandbox.io/s/hidden-fire-2tusc?file=/src/App.tsx:1662-1668
2. Click on "Submit" button
3. Check source code `{errors.items.message}`
4. See typings error

**Codesandbox link (Required)**
https://codesandbox.io/s/hidden-fire-2tusc?file=/src/App.tsx:1662-1668

**Expected behavior**
I expect that typings will be correctly describes runtime js objects

**Desktop (please complete the following information):**

- OS: Windows, Linux
- Browser Chrome
- Version 90

**Comment by BTiers** [comment]
Hi @pret-a-porter !

You should use `NestedValue<string[]>` instead of `string[]` in your `FormValues`

For reference see  [the documentation](https://react-hook-form.com/ts/#NestedValue)

**Comment by pret-a-porter** [comment]
@BTiers Thank you!

**Comment by bluebill1049** [comment]
Thank you @BTiers ❤️
