### ISSUE TITLE
Allow users to opt out of excluding disabled fields from state

### ISSUE THREAD

**Issue by blakestone95** [react-hook-form/react-hook-form#5031]
While attempting to upgrade a project from v6.15.5 to v7.2.3, I ran into a issue where disabled fields are suddenly being removed from the form state.  I saw the discussion in another issue the explained the reason for the change - it's how HTML forms work - but some libraries do not handle readOnly properly.  In my specific case, Material UI and this library no longer play nice because MUI doesn't fully support readOnly.  I explored many options and workarounds and determined that the easiest thing would be for this project to allow users to toggle that behavior if so desired.  While my issue is specifically with Material UI, this change could also benefit consumers of other component libraries.

The line of code in question is found here: https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/getFieldsValues.ts#L23

I would work on adding this myself, but my workplace is weird about open source contribution and it's a lot of annoying hoops to jump through to work on adding something like this.  Would you guys be willing to add some kind of config option for this?

**Comment by JGibel** [comment]
I'm new to the library, but I think a hidden input should work I think. 

Otherwise, you can re add the value on submit.

You can also wrap whatever material ui component that doesn't support readonly and control its own state/detach the ref.

CSB for the last one: https://codesandbox.io/s/react-hook-form-custom-input-forked-qog64

See on submit, the DisabledInput value still stays.

**Comment by bluebill1049** [comment]
Thanks very much @JGibel for the potential answer.


I hope that's what you after and we can save one less config for this lib.

**Comment by bluebill1049** [comment]
This may work for you

```
<fieldset disabled>
  <input {...register('test'} />
</fieldset>
```

so the input is disabled and the value will still be submitted with hook form.

**Comment by brandondurham** [comment]
> This may work for you
> 
> ```
> <fieldset disabled>
>   <input {...register('test'} />
> </fieldset>
> ```
> 
> so the input is disabled and the value will still be submitted with hook form.

Had no idea you could disable a fieldset. Wonderful! Thanks!
