### ISSUE TITLE
isValid is incorrectly set to false when a hidden required field with defaultValue shows up

### ISSUE THREAD

**Issue by JimmyRowland** [react-hook-form/react-hook-form#5036]
**Describe the bug**
When a new required input field with defaultValue is added and rendered, isValid should not be set to false.

**To Reproduce**

1. Go to [This sandbox](https://codesandbox.io/s/react-hook-form-get-started-forked-eu7bg?file=/src/index.js)
2. Click on 'checkbox'
3. A new required input field with default value shows up
4. see error message: should be valid

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

V7

- [JS](https://codesandbox.io/s/react-hook-form-get-started-forked-eu7bg?file=/src/index.js) Template

**Expected behavior**
isValid flag should be true

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser Chrome
- Version 90.0.4430.85

**Additional context**
isValid flag stays true in V6

**Comment by bluebill1049** [comment]
unmounted input still getting validated, and that's the current behavior, but this PR will address this once test and merged. https://github.com/react-hook-form/react-hook-form/pull/4785

**Comment by JimmyRowland** [comment]
This might be a different bug.

[https://codesandbox.io/s/react-hook-form-get-started-forked-zxb9u?file=/src/index.js](https://codesandbox.io/s/react-hook-form-get-started-forked-zxb9u?file=/src/index.js)

isValid is set to false even if the required input field with default value is never unmounted.

**Comment by bluebill1049** [comment]
<img width="975" alt="Screen Shot 2021-05-05 at 6 59 07 pm" src="https://user-images.githubusercontent.com/10513364/117118318-f9779300-add3-11eb-9c38-06fbd223a719.png">

@JimmyRowland make isValid will need `defaultValues` at the useForm level.

**Comment by JimmyRowland** [comment]
Thanks for the help. Should defaultValues be set at hookform level in the future or some point in the future, isValid will be set to true if required input fields have defaultValue prop.

**Comment by bluebill1049** [comment]
Personally, I prefer to set at useform level.
