### ISSUE TITLE
Typescript Structural Typing does not work on `UseFormReturn` type

### ISSUE THREAD

**Issue by SimonSelg** [react-hook-form/react-hook-form#5038]
**Describe the bug**
Typescript is based on [structural typing](https://en.wikipedia.org/wiki/Structural_type_system). This allows to use the following pattern:
```tsx
type Big = { foo: string, bar: string}
type Small = { foo: string } // or Pick<Big, 'foo'>

const big: Big = { foo: "foo", bar: "bar"}
const small: Small = big // <-- no error, since "big" has all the properties that are required by Small
```

I find this pattern very useful when working with react components - have them only require the data which they absolutely need (to have a clear interface, and to make tests easier), but if someone passes data of the bigger type to the component, that's no issue - neither for the component, nor typescript.

Prior to react-hook-form, this approach worked well for the `UseFormReturn` type (it was renamed in v7, but the principle remained the same - it's the data returned by `useForm`): 

```typescript
type FormValues = { foo: string, bar: string}
type FormValuesSubset = Pick<FormValues, 'foo'> // or { foo: string}

const methods: UseFormReturn<FormValues> = useForm<FormValues>()
const smallMethods: UseFormReturn<FormValuesSubset> = methods // <----- no error in v6, error in v7
```

However, with `react-hook-form` v7, I am now getting a type error:
```
Type 'UseFormReturn<FormValues>' is not assignable to type 'UseFormReturn<Pick<FormValues, "foo">>'.
  Types of property 'getValues' are incompatible.
    Type 'UseFormGetValues<FormValues>' is not assignable to type 'UseFormGetValues<Pick<FormValues, "foo">>'.
      Type 'Pick<FormValues, "foo">' is not assignable to type 'FormValues'.ts(2322)
```

**To Reproduce**
Compile the code above, you will get a typescript error

**Codesandbox link**
minimal example: https://codesandbox.io/s/serene-https-zqmh4
real world example: https://codesandbox.io/s/react-hook-form-methods-type-error-kruqg

**Expected behavior**
I would expect `methods` can be assigned to `smallMethods` without type errors. My reasoning behind this is that if the form state includes more fields then the component expects this is no problem. And due to the structural typing system of typescript, this should also be possible to implement. 

**Additional context**
Here I describe why the pattern above is useful and why have used it in the past. A concrete example is in the "real world example" codesandbox.

In the past, I have followed the following pattern
- Have a form, which has a typed FormState
- Have subcomponents, which require only a subset of the formState to be present (I'm passing the `methods` of the form down to the components)
- Pass the `methods` of the form down to the subcomponents (that contains more data then the subcomponent needs)

That has the advantage that
- the components can be better reused in a different form
- the component require only the data which they really need

----

I first wanted to discuss whether you would like this to be fixed. If yes, I can work on that.

Also, thanks a lot for the great library and all the effort you have put in it. The v7 upgrade is great!!

**Comment by bluebill1049** [comment]
Thank you @SimonSelg I am currently sick, I will follow you up tonight.

**Comment by bluebill1049** [comment]
```ts
import { UseFormReturn } from "react-hook-form";

type FormValues = Partial<{ foo: string; bar: string }>;
type FormValuesSubset = Pick<FormValues, "foo">; // or { foo: string}

const methods: UseFormReturn<FormValues> = {} as UseFormReturn<FormValues>;
const smallMethods: UseFormReturn<FormValuesSubset> = methods; // <----- error here!
```

will the above help? if you set the form values to be partial.

**Comment by SimonSelg** [comment]
Hi @bluebill1049,

thank you for the reply. No hurries, I hope you get well soon! Your health is more important then this, this bug can wait, I have a workaround in our code base for now.

> ```ts
> import { UseFormReturn } from "react-hook-form";
> 
> type FormValues = Partial<{ foo: string; bar: string }>;
> type FormValuesSubset = Pick<FormValues, "foo">; // or { foo: string}
> 
> const methods: UseFormReturn<FormValues> = {} as UseFormReturn<FormValues>;
> const smallMethods: UseFormReturn<FormValuesSubset> = methods; // <----- error here!
> ```
> 
> will the above help? if you set the form values to be partial.

Unfortunately not, as it changes the types for `FormValues` to have all keys optional, which is not what I want. I'd rather want to fix the problem that a value of type  `UseFormReturn<FormValues>` is not assignable to a value of type `UseFormReturn<FormValuesSubset>`, even tho `FormValuesSubset` is a subset of `FormValues` (which means that a value of type `FormValues` can be assigned to a value of type `FormValuesSubset`). 

I created this issue to check with you whether you even consider that a bug / potential for improvement. If yes, I can put in some work to find out why the types are not assignable (despite typescripts structural typing), and (if possible, I don't see how it shouldn't be possible) add a PR that fixes this issue. 

By no means I wanted to put the burden if fixing this on you.

**Comment by bluebill1049** [comment]
Hi, @SimonSelg Thank you! I am slowly recovering. If you have time, please give it a try and PR welcome. I really appreciated your help here.

**Comment by bluebill1049** [comment]
hi, @SimonSelg thanks for looking into this issue, wondering if you have any progress on this issue? if you are busy, I can always pick up where you left off. no pressure if you haven't, let me know I will start to investigate this soon.

**Comment by bluebill1049** [comment]
both I and @kotarella1110 did the investigation on this one, looks like it's rather difficult... we are going to close it as a design limitation.
