### ISSUE TITLE
[v7]: trigger function always returns false

### ISSUE THREAD

**Issue by opeah** [react-hook-form/react-hook-form#5043]
Trigger function always returns `false` without params (Triggers validation on all fields).
```
trigger()
```

1. Create basic form
2. Register some fields with validation (not working also without validation)
3. Call `trigger` function without params
4. `trigger` always return false even if the form is valid

**Codesandbox link**
https://codesandbox.io/s/serverless-snow-47vxd?file=/src/App.js

**Expected behavior**
Should return false only when fields are not valid

**Desktop:**

- OS: macOS 11.3
- Browser:  chrome
- Version: 92

**Additional context**
react 17.0.2
react-hook-form 7.4

**Comment by bluebill1049** [comment]
patched used wrong # https://github.com/react-hook-form/react-hook-form/commits/master
