### ISSUE TITLE
Default values are not preserved on useFieldArray

### ISSUE THREAD

**Issue by FDiskas** [react-hook-form/react-hook-form#5044]
**Describe the bug**
Default values are not preserved on useFieldArray
Input checkbox does not acts normaly. It must be clicked twice to start working.

**To Reproduce**

1. Open provided link
1. Change dependency of react-hook-form to latest
1. Refresh browser window
1. Click "buzz" checkbox to display the input
1. See error

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-reset-usefieldarray-forked-wzgl6?file=/src/index.js

**Expected behavior**
I would like to see form with default Values including conditionally rendered input

**Additional context**
At some point starting from 7.0.0-rc.2 version it stopped working. The provided example is on this version, but it is still not fully acceptable. Only checkbox is preserved from defaultValues. Also Reset functionality in this version works as not accepted.

**Comment by bluebill1049** [comment]
That's after you have reset the form right? 

To the following value.

```
const data = {
  names: [
    { state: false, id: 1, conditional: "1", label: "foo" },
    { state: false, id: 2, conditional: "2", label: "buzz" },
    { state: false, id: 3, conditional: "3", label: "foobuzz" },
    { state: false, id: 4, conditional: "4", label: "buzzfoo" }
  ]
};
```

**Comment by FDiskas** [comment]
The ideal would be like on resetting the form applied initial data and on top defaultValues. So lets imagine that as a user i have a big form toggle some inputs add some data then save that form for later using for example localstorage, come back to that form and i would like to be prefilled pre toggled fields. And if I mestup something in that form I hit reset and it would be reseted to previews data from localstorage. Hard to explain 🤣

**Comment by bluebill1049** [comment]
> The ideal would be like on resetting the form applied initial data and on top defaultValues. So lets imagine that as a user i have a big form toggle some inputs add some data then save that form for later using for example localstorage, come back to that form and i would like to be prefilled pre toggled fields. And if I mestup something in that form I hit reset and it would be reseted to previews data from localstorage. Hard to explain 🤣

That's `setValue`, not reset the entire. `reset` will reset the entire form. the RC version worked due to a bug.

**Comment by FDiskas** [comment]
Reset i would imagine just work out of the box like in formik. It reset to the state right before dirty form

**Comment by bluebill1049** [comment]
Well, this is `react-hook-form`... `reset` will reset what's you have supplied.

**Comment by FDiskas** [comment]
The problem that it is not working :D - keep closing the issues

**Comment by bluebill1049** [comment]
oh my god, @FDiskas how dare you? say shit like that...

**Comment by bluebill1049** [comment]
if I didn't look at your codesandbox, how would I reply to you with your CODE? 

<img width="854" alt="Screen Shot 2021-05-06 at 8 13 03 pm" src="https://user-images.githubusercontent.com/10513364/117281886-77f13500-aea7-11eb-8101-2b7ae913879d.png">

read my comment ^ and read my reply.
