### ISSUE TITLE
Default values are thrown away on first edit or form submission if input is disabled

### ISSUE THREAD

**Issue by gfpacheco** [react-hook-form/react-hook-form#5045]
**Describe the bug**

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-bug-disabled-i9frz
2. Open the console in the preview panel
3. Click the checkbox or submit the form
4. See foo field is undefined

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-bug-disabled-i9frz

**Expected behavior**
Foo field should keep the default value of 1

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 90

**Additional context**
Removing the disabled attribute from foo field makes the field keep the default value.

**Comment by bluebill1049** [comment]
<img width="977" alt="Screen Shot 2021-05-06 at 12 12 55 pm" src="https://user-images.githubusercontent.com/10513364/117232403-65094100-ae64-11eb-8ccc-c72f0f5d4e3b.png">


> disabled input will result in an undefined form value. If you want to prevent users from updating the input, you can use readOnly or disable the entire <fieldset />. Here is an example.

**Comment by gfpacheco** [comment]
This only works for input fields. Selects don't have a readOnly prop. Checkboxes don't obey the readOnly prop. Didn't test textarea though.

**Comment by bluebill1049** [comment]
you can use do the following:

```tsx
<fieldset disabled>
  <select />
</fieldset>
```
