### ISSUE TITLE
[7.4.1] trigger always returns false when using yupResolver scheme

### ISSUE THREAD

**Issue by dewit** [react-hook-form/react-hook-form#5051]
**Describe the bug**
When using a yupResolver schema in the useForm, a trigger that will always return false  

**To Reproduce**

1. Create a useForm with a yupResolver resolver.
2. Register fields with yup schema validation
3. Call trigger function with params
4. trigger will return false even when it's true

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

https://codesandbox.io/s/react-hook-form-v6-triggervalidation-forked-d2jkr?file=/src/index.js

**Comment by AndreBastos23** [comment]
Hey @bluebill1049, how are you?

Quick question, when will you release 7.4.2 with this fix? :)
