### ISSUE TITLE
v7.4.1 useFormState doesn't isolate rerenders by name in some scenarios

### ISSUE THREAD

**Issue by orenklein** [react-hook-form/react-hook-form#5053]
**Describe the bug**
Mentioned release is quite fresh, and I'm not sure if this is the right way to use it, so correct me if anything is wrong.

In the following sandbox, useFormState with fieldname provided, rerenders when: 
1. New field is added to the form
2. Specified field doesn't have any error and submit is clicked

**To Reproduce**
Go to sandbox.

First issue:
1. Click on toggle
2. SpecificErrorMessage rerenders and logs 'specific error message firstName {}'

Second Issue (after refresh):
1. fill something within first name field
2. click on submit
3. SpecificErrorMessage rerenders and logs 'specific error message firstName {lastName: Object}'

**Codesandbox link (Required)**
https://codesandbox.io/s/flamboyant-gates-gv24x?file=/src/SpecificErrorMessage.tsx

**Expected behavior**
useFormState shouldn't rerender on both cases

**Comment by orenklein** [comment]
@bluebill1049 The behavior with v7.4.2 is still the same as described in the issue

**Comment by bluebill1049** [comment]
can you test against the last name?

https://user-images.githubusercontent.com/10513364/117566340-86368f80-b0f9-11eb-9d4d-23400198b305.mov

**Comment by orenklein** [comment]
Changing other fields is working is expected. 
The issue I described occurs when submitting or adding/removing fields as you can see in the video:

https://user-images.githubusercontent.com/21295634/117573442-778fae80-b0e0-11eb-9cca-c0c4f2ab00a8.mp4

**Comment by bluebill1049** [comment]
I think that re-render is coming from parent's `useState` right?

**Comment by orenklein** [comment]
Quite sure it's not coming from parent due to `React.memo` on `SpecificErrorMessage`

**Comment by bluebill1049** [comment]
It's due to context: https://codesandbox.io/s/strange-sound-ct5gv?file=/src/App.tsx

**Comment by orenklein** [comment]
Could you elaborate?

**Comment by bluebill1049** [comment]
Try on my codesandbox above, and compare comment and unco
mment the provider

**Comment by orenklein** [comment]
It doesn't compile
Anyway, control would update the component in every render, and context shouldn't as far as I'm aware (?)
In my example I used the context and `React.memo` so the rerender of `SpecificErrorMessage` could only come from useFormState

**Comment by bluebill1049** [comment]
> In my example I used the context and React.memo so the rerender of SpecificErrorMessage could only come from useFormState

no, it's not from `useFormState`, you can test out from the source code.
