### ISSUE TITLE
Typescript issue - useFieldArray defaultValue and fields incorrect type

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#5054]
**Describe the bug**
When using a field array, typescript is reporting an error on a field array input name. The name in the example should be valid given my type definition.

**To Reproduce**

1. Go to the sandbox
2. Observe the typescript error

**Codesandbox link (Required)**
https://codesandbox.io/s/async-surf-3gnh7?file=/src/App.tsx

**Expected behavior**
This should be a valid name and typescript should not report an error

**Screenshots**
![Screenshot from 2021-05-06 10-39-03](https://user-images.githubusercontent.com/36898266/117342291-e9a19280-ae57-11eb-8e38-09f215955838.png)

**Comment by wdfinch** [comment]
Thanks for the reply. I tried that and it solved the error above but now I have a new ts error on line 33. 

https://codesandbox.io/s/green-bush-olo1z?file=/src/App.ts

**Comment by ccheney** [comment]
> Thanks for the reply. I tried that and it solved the error above but now I have a new ts error on line 33.
> 
> [codesandbox.io/s/green-bush-olo1z?file=/src/App.ts](https://codesandbox.io/s/green-bush-olo1z?file=/src/App.ts)

I think when you're calling `append()` with `name` it's colliding since you now have multiple fields registered with the same name. You're using `name` to register each field in the fields array.  If you set the `defaultValue` to:

```ts
defaultValue={`item.${index}.name`}
```

 that seems to work around it by ensuring each field has a unique name.

**Comment by wdfinch** [comment]
If I use defaultValue={\`item.${index}.name\`}, then I don't get the proper default value. The value of new elements will be `item.0.name`, `item.1.name`, etc.

I believe `item.name` is the correct way to reference the default value here as this is what the docs state and how I've been doing it for a long time.

https://codesandbox.io/s/green-bush-olo1z?file=/src/App.tsx

**Comment by bluebill1049** [comment]
as const ?

**Comment by bluebill1049** [comment]
`export declare type FieldValues = Record<string, any>;` 

This line is the problem, TS template literal is not going to work out with the above.

**Comment by wdfinch** [comment]
I see, so how could I strongly type my field array in this simple example? I've done stuff like this with `Controller` and it's been fine.

**Comment by bluebill1049** [comment]
I think that's the limitation with string template literal because it needs to map out the field name.

**Comment by wdfinch** [comment]
So should I just omit passing `FormValues` as a generic to `useFieldArray`? I'm not sure how you could strongly type a field array if this causes an error. Is it something specific to how I named the inputs?

**Comment by wdfinch** [comment]
Another issue here is `fields` has a type of `const fields: Record<"id", string>[]` rather than the type specified by form values. I don't think it worked like this in previous versions of V7. 

![Screenshot from 2021-05-06 17-55-43](https://user-images.githubusercontent.com/36898266/117382853-4ae75700-ae94-11eb-9a8e-410bb9657414.png)

**Comment by wdfinch** [comment]
@kotarella1110 any ideas here?

**Comment by kotarella1110** [comment]
Hi @wdfinch 👋

Do not define an Intersection Type using `FieldValues`.

```diff
- type FormValues = FieldValues & {
+ type FormValues = {
    names: Array<Name>;
  };
```

You must either omit Generics, or pass all Generics.

```ts
const { fields, append } = useFieldArray({
  control,
  name: "names"
});
// or
const { fields, append } = useFieldArray<FormValues, "names", "id">({
  control,
  name: "names"
});
```

**Also, when using useFieldArray, use `as const` with `register`'s name.**

```ts
<input
  key={item.id}
  {...register(`names.${index}.name` as const)}
  defaultValue={item.name}
/>
```

Please see here: https://codesandbox.io/s/youthful-poitras-hnwsy

**Comment by wdfinch** [comment]
Hi @kotarella1110 

This was my original sandbox with the original error.

https://codesandbox.io/s/async-surf-3gnh7?file=/src/App.tsx

@ccheney recommended I add the intersection. 

Ok perfect! Before the other attributes weren't required. I'll add that to the docs this weekend. Thanks for the help.

**Comment by ccheney** [comment]
> Hi @kotarella1110
> 
> This was my original sandbox with the original error.
> 
> [codesandbox.io/s/async-surf-3gnh7?file=/src/App.tsx](https://codesandbox.io/s/async-surf-3gnh7?file=/src/App.tsx)
> 
> @ccheney recommended I add the intersection.
> 
> Ok perfect! Before the other attributes weren't required. I'll add that to the docs this weekend. Thanks for the help.

Yeah, sorry about that! Thanks for clarifying @kotarella1110

**Comment by bluebill1049** [comment]
Thank you very much @kotarella1110 👍 ❤️

**Comment by ioanungurean** [comment]
I would like to expand further on this issue:

What should happen when the 'names' field is dynamic? 

I'm failing to make it work as it supposed to: https://codesandbox.io/s/youthful-mestorf-v0zzo?file=/src/App.tsx:0-934

Can someone point me in the right direction?

**Comment by Mastard69** [comment]
> I would like to expand further on this issue:
> 
> What should happen when the 'names' field is dynamic?
> 
> I'm failing to make it work as it supposed to: https://codesandbox.io/s/youthful-mestorf-v0zzo?file=/src/App.tsx:0-934
> 
> Can someone point me in the right direction?

I kinda have the same issue with useFieldArray.
The name I have to provide is a dynamic path, like : 
``const { fields } = useFieldArray({
    name: `pages.${pageIdx}.lines`,
  })``
Problem is that the 'item' object in the fields.map(...) is of type Record<'id', string>, so I cannot access properties of my item (admiting that my Line object has properties obviously)

I tried : 
``useFieldArray<Book, `pages.${pageIdx}.lines`, 'id>'()``
But obviously TS gives me an error like "pageIdx is a variable but is used as a type"

If someone can help with this, it would be greatly appreciated ^^

**Comment by iuacuris** [comment]
Hi @bluebill1049, @kotarella1110 do you have some ideas for the issue described above? It would be appreciated.

**Comment by nklaasse** [comment]
You can also type the `useFormContext` and pass down the `control` to the `useFieldArray` to apply types on `fields`.

```
  const { control } = useFormContext<FormValueProps>();
  const { fields } = useFieldArray(
    {
      control,
      name: "someName"
    }
  );
  
  fields.fieldName // will be typed
```
