### ISSUE TITLE
TS: useController ref issue

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#5065]
> > @bluebill1049 should this fix also be applied to `ControllerRenderProps`? I'm trying to do the same as the OP, just using `useController` instead of `register`.
> 
> Sure, can u give some more detail and a codesandbox to show case the problem?

Like the OP, I'm trying to share the ref usage, but I'm doing it inside of a component which uses `useController`. The ref returned in the `ControllerRenderProps` of the `UseControllerReturn` has the type `Ref<any>` which Typescript deems not callable.

See the following codesandbox for a reproduction: https://codesandbox.io/s/sharp-allen-obk9k?file=/src/App.tsx:424-439

_Originally posted by @larrifax in https://github.com/react-hook-form/react-hook-form/issues/4696#issuecomment-834120417_

**Comment by bluebill1049** [comment]
working version: https://codesandbox.io/s/compassionate-vaughan-w6d92?file=/src/App.tsx

**Comment by larrifax** [comment]
That was quick. Thanks! 🥇
