### ISSUE TITLE
Support array as well as object in register return value

### ISSUE THREAD

**Issue by kotarella1110** [react-hook-form/react-hook-form#5070]
**Is your feature request related to a problem? Please describe.**

It is a bit cumbersome to customize prop names because supports only object in `register` return value.

```ts
const { name, ref: inputRef, onChange: onChangeText, onBlur } = register("name");
```

**Describe the solution you'd like**

We can support array as well as object.
If this feature request is accepted, I will create a PR 👍🏻 

**Describe alternatives you've considered**

```ts
// object destructing
const { name, ref: inputRef, onChange: onChangeText, onBlur } = register("name");
// array destructing, making it easy to customize the prop names 
const [name, inputRef, onChangeText, onBlur] = register("name");
```

**Additional context**

https://codesandbox.io/s/react-hook-form-5070-fy2kd?file=/src/index.tsx

**Comment by bluebill1049** [comment]
@kotarella1110 that's related to https://github.com/react-hook-form/react-hook-form/projects/1 oh yeah, I really like the array idea! please go ahead. I will add this into project board.
