### ISSUE TITLE
:bug: Error trying to use the onBlur/OnChange functionality: undefined is not an object

### ISSUE THREAD

**Issue by ReactGirl** [react-hook-form/react-hook-form#5074]
There is this terrible bug that does not allow you to use the validations needed to OnChange and onBluer causing the entire app to crash.

**Describe the bug**
Example does not work for onBlur/OnChange validation

---> undefined is not an object (evaluating 'errors.firstName')

**To Reproduce**

1. Go to  the code sandbox example

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-validation-onblur-onchange-pnq16

**Comment by bluebill1049** [comment]
fixed.
