### ISSUE TITLE
Feature Request - Expand Shallow Merge of Default Values to Field Arrays

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#5076]
**Is your feature request related to a problem? Please describe.**
Yes. In order for field arrays to _fully_ work correctly, each element of the field array must be mounted to the dom. This presents a big problem for large field arrays. If we have many elements and each element consists of complex inputs like react-select, date pickers, etc. then we start to run into some serious performance issues trying to mount all of this. This can get to the point of being **unusable** when things get large enough.

**Describe the solution you'd like**
I would like to only mount parts of a field array to make it more manageable. So a simple example of this is pagination where each page shows 10 elements out of 100 total elements. While this works, we have an issue if we try to retrieve our form values. Running `getValues()` will only return the field array elements that have been mounted. Therefore in our example above, we would only get 10 elements back even though there are 100. 

I think the easiest way to solve this that wouldn't require a big rewrite of `useFieldArray` is to shallow merge the `defaultValues` of a field array with the values tracked by `formValues`. To do this, we could simply do [...(defaultValues - fieldArrayValues), ...fieldArrayValues]. The id of an element could be used for the diff operation.

**Describe alternatives you've considered**
In order to do this now, I must save a copy of all my default values from the server and do the merge myself. 

**Additional context**
Here's a sandbox to show the current issue.
https://codesandbox.io/s/shallow-array-merge-forked-f8j6e?file=/src/App.js

**Comment by bluebill1049** [comment]
This is duplicated. Let's discuss the other feature request.

**Comment by wdfinch** [comment]
Yes, I noticed the other one after I posted this. The deep merge would be superior to this.
