### ISSUE TITLE
Receiving a warning when not passing a ref with controlled component

### ISSUE THREAD

**Issue by ahmedosama7450** [react-hook-form/react-hook-form#5080]
**Describe the bug**
I am trying to integrate react hook form with [Headless UI Select Component](https://headlessui.dev/react/listbox)
This component is built from scratch, It doesn't have an underlying native html select tag, I guess. So, I don't have access to a `ref`. It only exposes `onChange` and `value` ([API Reference](https://headlessui.dev/react/listbox#component-api)).

I am using the hook form `Controller` to wrap a custom select like this
```
<Controller
  name='year'
  control={control}
  render={({ field }) => {
    return (
      <CustomSelect
        value={field.value}
        onChange={(value)=> field.onChange(value)}
        label='Year'
        className='mt-5 sm:flex-1'
        options={[
          {
            value: 1,
            text: 'First Year',
          },
          {
            value: 2,
            text: 'Second Year',
          },
        ]}
      />
    );
  }}
/>
```
I think everything is working just fine except that I receive this warning in chrome devtools
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Controller`.
    at CustomSelect (http://localhost:3000/_next/static/chunks/pages/create-profile.js?ts=1620420857237:473:22)
    at Controller (http://localhost:3000/_next/static/chunks/pages/create-profile.js?ts=1620420857237:40059:37)
    at form
    at div
    at div
    at main
    at div
    at CreateProfile (http://localhost:3000/_next/static/chunks/pages/create-profile.js?ts=1620420857237:46240:81)
    ....
```

I think that you require passing `ref` in controlled components for things like focusing the component. I don't really need this and also this component doesn't support that, I guess.

**To Reproduce**
Use headless UI select component with  hook form

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by ahmedosama7450** [comment]
The issue template is not very applicable here!

**Comment by sandren** [comment]
@bluebill1049 I've created a react-hook-form + @headlessui/react demo here which may help reproduce this issue; https://codesandbox.io/s/react-hook-form-headlessuireact-demo-y4tyn?file=/src/pages/index.js

The `<Switch>` component seems to work fine, but uncommenting the `<Listbox>` component breaks it.

**Comment by coolRoger** [comment]
Don't close the issue please, I got the same issue here with Mantine UI

**Comment by coolRoger** [comment]
Ha, finally found out the solution by omit the "ref" key from field object: 

```
<Controller
      name="password"
      control={control}
      defaultValue=""
      rules={{ required: true }}
      render={({ field }) => (
           <PasswordInput
                required={true}
                styles={inputStyles as any}
                label="密码"
                placeholder="请输入您的密码"
                elementRef={field.ref}
                {...omit(field, ["ref"])}
           />
      )}
/>
```
It's because of spread out the `...{field}`, ref = {ref} declaration is duplicate with elementRef = {field.ref}, so the error is thrown.

**Comment by bluebill1049** [comment]
thanks for the update @coolRoger note: it's recommended to provide `ref` for the input, otherwise focus management is not going to work as expected.

**Comment by coolRoger** [comment]
Thank you for the reply @bluebill1049, and I checked out the source code of [mantine](https://github.com/mantinedev/mantine):

The prop `elementRef` defined as `elementRef?: React.ForwardedRef<HTMLInputElement>;`, so I think it is doing the same thing like `ref` that keeps focus management to work.
