### ISSUE TITLE
Feature request - add option to getValues to include field array element ids

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#5081]
**Is your feature request related to a problem? Please describe.**
Yes. If we want to modify a field array's values, then typically we would use `setValue`. A common setup might look like this: 

```
const currentValues = getValues().myFieldArray
const currentValues[index] = {
  values: 'newValue'
}
setValue('myFieldArray', currentValues)
```

The issue is that when we do this we are creating new field array elements. So in other words a new id will be generated and a new component will be mounted meaning all our state of that element will be lost.

**Describe the solution you'd like**
A solution for the above is to include the field array element's ids in the `setValue` operation. So for example:

```
const currentValues = getValues().myFieldArray
const currentValues[index] = {
  values: 'newValue'
  id: elementID
}
setValue('myFieldArray', currentValues)
```

If we do this then the same id will be used and the element will retain its existing state. However, right now it's kinda clunky to get the id as we need to find it inside of `fields` and merge it. It would be nice if `getValues` could include this id so that `setValue` was a more performant operation and preserved our component state. 

**Describe alternatives you've considered**
Manually adding the `id` from fields when using `setValue`

**Comment by wdfinch** [comment]
@bluebill1049 I think we can move this one out pending feature requests. This was to solve issues in #5083 but it's not the right approach.

**Comment by bluebill1049** [comment]
kk. thanks for the update @wdfinch
