### ISSUE TITLE
Feature request - getValues to return deep copy 

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#5082]
**Is your feature request related to a problem? Please describe.**
Yes. I am constantly running into issues because `getValues` will not return a true deep copy of `formValues` merged with `defaultValues`. It seems that some things are copied but mainly with field arrays they are not. This means if I want to use the current form values as a starting point for some type of mutation, I must manually deep clone to values myself to ensure I'm not messing with the internal form state during my mutation. 

**Describe the solution you'd like**
I would like to add an option to `getValues` that will return a deep copy of the `formValues` so that I don't need to do `_.deepClone` every time I am going to mutate `formValues` and then use `setValue` to update a field array. It would be nice if there was a global setting on `useForm` for this as well. 

**Describe alternatives you've considered**
Running _.deepClone everytime I use `getValues()`

**Comment by bluebill1049** [comment]
@wdfinch that's duplicated as well. the other feature request should cover this as well. 👍

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/5003

**Comment by wdfinch** [comment]
@bluebill1049 would you be willing to open a modified version of this as a feature request? It would cover #4500 as well. I'm still facing constant bugs because the library returns and accepts references to form values vs deep copies. See my discussion below. 

#5919

**Comment by bluebill1049** [comment]
Personally, I don't think we should include deepClone for those results returned, and users should do at the app level and avoid mutate the return data.
