### ISSUE TITLE
Bug - using setValue on field array breaks future setValue call

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#5089]
**Describe the bug**
**If** we use `setValue` to initialize a field array. EX: 

```
React.useEffect(() => {
  setValue("names", [{ name: "will" }]);
}, []);
```

**And** then later on we try and update an index of the same field array using `setValue`:

```
const changeValue = () => {
  setValue(`names.${index}`, {
    name: "updated"
  });
}; 
```

**Then** formValue will **not** update

**To Reproduce**

1. Go to the sandbox
2. Click on the change value button
3. Notice that the value does not change
4. Comment out line 48 or replace line 48 with lines 51-53.
5. Notice that it works now.

**Codesandbox link (Required)**
https://codesandbox.io/s/pensive-hofstadter-chm2i?file=/src/App.js:302-310

**Expected behavior**
I would expect a call of `setValue` to not affect future calls of `setValue`. While we can use reset here as a workaround, I think this should work. Additionally, I know in this example it would be better to use default values, but in my project, I need to use either `setValue` or `reset` to initlize the form.

**Comment by leapful** [comment]
@wdfinch It seems the root cause is from internal method "setInternalValue" of "useForm" hook. I will submit a pull request soon.
