### ISSUE TITLE
Validation is not working properly when using controlled components

### ISSUE THREAD

**Issue by zcsongor** [react-hook-form/react-hook-form#509]
**Describe the bug**
By default, validation is triggered during an input change. But if you use controlled component, revalidation does not occur properly.

**To Reproduce**
Forked your example called `Controlled mixed with Uncontrolled Components` and added `required: true` to both of the inputs.
1. Submit the form as it is, with empty inputs. You will see two errors.
2. Start typing into the input field. Input error should disappear.
3. Select an option. Select error stays.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-controlled-mixed-with-uncontrolled-eg4t3

**Expected behavior**
Select error should have been disappeared as well.

**Comment by bluebill1049** [comment]
@zcsongor my bad
i will update the example: `setValue("select", e.target.value, true);

**Comment by zcsongor** [comment]
Oh, missed this one in the documentation.
Thanks for your quick reply!

**Comment by bluebill1049** [comment]
no worries! thanks for spotting the issue too. I just published it today, you are quick haahh

**Comment by bluebill1049** [comment]
looks like you come from angular! you will see some familiar API such as `watch`

**Comment by bluebill1049** [comment]
closing now, feel free to ask more questions :)
