### ISSUE TITLE
Resetting form using values from custom hook fails

### ISSUE THREAD

**Issue by clintharris** [react-hook-form/react-hook-form#511]
I'm noticing unexpected behavior when attempting to reset the form in an effect based on state maintained by a custom hook. I'm not sure if it's a bug with react-hook-form or with my own code...

I use a custom hook to load a `customer` object from the server:
```javascript
const { customer, saveCustomer, loading, saving } = useCustomer(1234);
```
Then I use an effect to reset the form and "array field" state (per react-hook-form examples) whenever `customer` changes:
```javascript
const [indexes, setIndexes] = React.useState([]);
const [counter, setCounter] = React.useState(0);
const hookForm = useForm();
const { reset: resetForm } = hookForm;

React.useEffect(() => {
  resetForm(customer);
  const itemCount = customer && customer.items ? customer.items.length : 0;
  setCounter(itemCount);
  setIndexes(Array.from({ length: itemCount }, (_, k) => k));
}, [customer, resetForm]);
```

The issue is that the form is rendered with empty `<input>` elements, depending on where I call `setLoading(false)` in my custom hook, shown here:
```javascript
export default function useCustomer(customerId) {
  const [customer, setCustomer] = React.useState();
  const [loading, setLoading] = React.useState(false);
  const [saving, setSaving] = React.useState(false);

  React.useEffect(() => {
    if (!customer && !loading) {
      setLoading(true);
      // Simulate delay while loading the customer...
      setTimeout(() => {
        setLoading(false); // 👈 If setLoading is here, the form renders empty elements
        setCustomer({
          items: [{ name: "Item 1" }, { name: "Item 2" }, { name: "Item 3" }],
          modified: null
        });
        // 👈 BUT if setLoading(false) is here the form renders correctly
      }, 1000);
    }
  }, [customer, loading, customerId]);

  return { customer, loading, saving, saveCustomer };
}
```
Why would changing the order in which `setLoading()` and `setCustomer()` are called affect if the form values are rendered correctly? Any ideas or advice?

I have a Sandbox here that shows the issue (empty `<input>` elements)--move the `setLoading(false)` call as described above to "fix" the issue: https://codesandbox.io/s/react-hook-form-array-without-formcontext-h9wej

**Comment by bluebill1049** [comment]
looks like you have posted the same question in spectrum, i am closing it here and let's sort it out there.
