### ISSUE TITLE
Breaking changes in 7.5.0 and above

### ISSUE THREAD

**Issue by n19htz** [react-hook-form/react-hook-form#5122]
**Describe the bug**
there is a breaking change for typescript users in version 7.5.0, yet its not versioned properly to avoid such breaking changes.

**To Reproduce**
![Screen Shot 2021-05-10 at 13 59 00](https://user-images.githubusercontent.com/39006390/117649530-4c689600-b198-11eb-99a3-e7144e5743c6.png)

**Codesandbox link (Required)**
nothing to display in codesandbox

**Comment by bluebill1049** [comment]
can you share a breaking example?

**Comment by n19htz** [comment]
In our project we use custom form input components with prop ```error?: string```, so an example of component would be:
![Screen Shot 2021-05-10 at 14 15 36](https://user-images.githubusercontent.com/39006390/117651084-32c84e00-b19a-11eb-84f2-b076899b4469.png)

and with array of strings its changing behaviour and ts will complain of type missmatch, by the way in docs aswell example will throw an error in typescript

![Screen Shot 2021-05-10 at 14 18 16](https://user-images.githubusercontent.com/39006390/117651439-9ce0f300-b19a-11eb-92f3-53631a5e33e1.png)

**Comment by bluebill1049** [comment]
it's fine with an error message: https://codesandbox.io/s/thirsty-shaw-ywb1d?file=/src/App.tsx perhaps you want to use `Message` type? I mean users may find `validate` function multiple error messages usage.

**Comment by n19htz** [comment]
well, now ofcourse I need to change everything to ```error?: Message``` and make changes to my inputs or  leave it as it is and before passing it as a prop to my components I should check either its an array of string or a string. But those changes is breaking for me and I only noticed about it when I actually clonned project on different machine and ran ```npm install``` (which upgraded react-hook-form to 7.5.0+ and broke my inputs)

**Comment by bluebill1049** [comment]
That's the thing, it's hard to justify the "breaking" part, if the intention is just for error messages as what it intended to show then it's not a breaking change. However, I do get your point, I will leave this issue open for a bit before revert it back.

**Comment by bluebill1049** [comment]
actually i found a better approach, let me patch it.
