### ISSUE TITLE
[Feature Request] useFormState - exact: false (for formState.errors)

### ISSUE THREAD

**Issue by orenklein** [react-hook-form/react-hook-form#5124]
**Is your feature request related to a problem? Please describe.**
Specifically referring to formState.errors - When "subscribing" to a name that is not associated with an input field, such as field array, children errors will not trigger an update (meaning it won't rerender).

**Describe the solution you'd like**
Perhaps adding option to define `exact: boolean`. If `exact: true`, subscribe only to current path. if `exact: false`, subscribe to current path and children path.

**Additional context**
I know it might be difficult than the suggested solution. However in my case, it is only needed to examine if there's inner error (`errors.test.0.value`) or not and I assume it is the same as examine if there's error for the exact array field name(`errors.test`):
If an error is set for the array name (`test`), it will trigger rerender with `useFormState({name})`. Seemingly, the error object of array field name (`errors.test`), is changed either when setting error for itself (adding properties such as`type`, `message`) or setting error to one of it's children (adding "array indexes" such as `0`, `1`)

**Comment by bluebill1049** [comment]
thanks for the feature request 👍 putting into the backlog for upvotes.
