### ISSUE TITLE
`errors` for nested fields not in expected format

### ISSUE THREAD

**Issue by babramczyk** [react-hook-form/react-hook-form#515]
**Describe the bug**
Maybe not necessarily a bug, but unexpected behavior

When using a nested fields (i.e. `name="accounts[0].name"`), the `errors` returned from `useForm` are not in the nested format expected, as the `data` is when submitting.

Example:

```jsx
<input name="accounts[0].name" ref={register({ required: true })} />
```

In this scenario, the `data` supplied to `handleSubmit` properly looks like this, as the docs describe:

```javascript
{
  accounts: [
    name: 'Brett',
  ]
}
```

But, if the field is invalid (in this scenario, if the field is left empty, the `errors` returned from `useForm` looks like this:

```javascript
{ 
  'accounts[0].name': {
    message: ""
    ref: input
    type: "required"
  }
}
```

Where I would expect it to look like this:
```javascript
{
  accounts: [
      name: {
      message: ""
      ref: input
      type: "required"
    }
  ]
}
```

Obviously there's a workaround (look at `errors['accounts[0].name']` for the error instead of `errors.accounts?.[0]?.name`), but it's inconsistent with the `data`'s shape, and the behavior was at least unexpected for me.

**Comment by bluebill1049** [comment]
hey @babramczyk , I understand your concern, however, this is by design. At least for now, I will keep the errors object in this pattern(string). I know you can use `Optional Chaining`, however it's not widely supported just yet, and until then I will move into such object shape.

**Comment by babramczyk** [comment]
I don't think my concern is specifically tied to optional chaining -- that's just what I chose to use in my example.

That being said, I understand wanting to avoid the alternative, I guess? (`errors.accounts && errors.accounts[0] && errors.accounts[0].name`). This is still unintuitive, especially considering the difference with `data`.

At the very least I'd expect the documentation to point this out. Optional chaining aside, I still would have expected the shape of `data` and `errors` to match for nested fields.

**Comment by bluebill1049** [comment]
sure @babramczyk I will update the documentation. 
`(errors.accounts && errors.accounts[0] && errors.accounts[0].name)` This is exactly what I try to avoid and running into `undefined`. In the near future, when optional chaining is getting better coverage, I will get it back into nested object shape.

**Comment by bluebill1049** [comment]
It actually would be a good idea for you to improve the docs too. you can find the repo here: (feel free to send a PR to address this concern) https://github.com/react-hook-form/react-hook-form-website

**Comment by babramczyk** [comment]
I've actually ran into a use case that pretty well justifies my original suggestion.

If you want to check if there's _any_ errors for a particular model, that's not possible with the current implementation.

e.g.
```jsx
<input name="accounts[0].name" />
<input name="accounts[0].dob" />
<input name="accounts[0].phoneNumber" />

<input name="accounts[1].name" />
<input name="accounts[1].dob" />
<input name="accounts[1].phoneNumber" />
```

Currently, to check if there's any errors for `accounts[0]`, you have to do this `accounts[0].name || accounts[0].dob || accounts[0].phoneNumber` instead of `accounts[0]`.

**Comment by bluebill1049** [comment]
why not just `errors['accounts[0].name']`?

**Comment by bluebill1049** [comment]
ok, i see, we have to live with this for a while until we move on to the next major version.

**Comment by bluebill1049** [comment]
in the meantime, you can easily build a little utility function

`containError('name')` do your forEach to check the error inside
