### ISSUE TITLE
Any function can be passed to handleSubmit with no type error raised

### ISSUE THREAD

**Issue by smashercosmo** [react-hook-form/react-hook-form#5157]
**Describe the bug**
Any function can be passed to handleSubmit with no type error raised

**To Reproduce**
1. just open the sandbox and observe that no type error is being raised

**Codesandbox link (Required)**
https://codesandbox.io/s/compassionate-surf-jyuc8?file=/src/App.tsx

**Comment by bluebill1049** [comment]
please use this type: https://react-hook-form.com/ts#SubmitHandler

**Comment by smashercosmo** [comment]
Thx for the tip. Any reason it can't be done without explicit submit handler type?

**Comment by bluebill1049** [comment]
no specific reason, if you interested or know how to make it work. please send us a PR.

**Comment by smashercosmo** [comment]
@bluebill1049 what's the reason for having two different generics here (TFieldValues and TSubmitFieldValues)? https://github.com/react-hook-form/react-hook-form/blob/master/src/types/form.ts#L422-L424

Seems like removing this part
```ts
<TSubmitFieldValues extends FieldValues = TFieldValues>
```
fixes the issue

**Comment by bluebill1049** [comment]
oh, this is because we allow the `resolver` to return custom form values. thanks for the investigation.

**Comment by smashercosmo** [comment]
Sorry, don't know what the ```resolver``` is :) But will you be able to fix it now? or is there anything else I can do?

**Comment by bluebill1049** [comment]
Let's keep it as it for now.

**Comment by bluebill1049** [comment]
You ok to use the SumitHandler type before I close this issue?

**Comment by smashercosmo** [comment]
It's ok for now. But I'm considering it as a workaround. How do you think, would it be possible to make it more dev friendly in future?

**Comment by bluebill1049** [comment]
That's only if we don't support resolver return tranformed value which will potentially result in a breaking Change. So not going to change it for now.

**Comment by bluebill1049** [comment]
Closing this issue for now, if others encounter similar issue use the SumitHandler type.
