### ISSUE TITLE
watch returns null instead of default checked value in dynamically generated checkbox

### ISSUE THREAD

**Issue by f4z3k4s** [react-hook-form/react-hook-form#516]
**Describe the bug**
A dynamically added checkbox's value returned from `watch` is `null` although it has a default value of `true`.

**To Reproduce**
1. Click on checkbox with label `a`

**Codesandbox link**
https://codesandbox.io/s/crimson-cdn-8w3lv

**Expected behavior**
I exptected `b` to be `true` as soon as it is added to DOM.

**Comment by bluebill1049** [comment]
thanks, @f4z3k4s for reporting this issue, it's been fixed you can verify via the codesandbox link or install the patched version. https://github.com/react-hook-form/react-hook-form/pull/517

**Comment by f4z3k4s** [comment]
@bluebill lightning fast, thank you, this repo is one of the most well-maintained ones I've seen

**Comment by bluebill1049** [comment]
thank you @f4z3k4s please consider to leave a star to support us too ❤️
