### ISSUE TITLE
Bug 7.5.2-beta.0 - Deep merge does not work with reset

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#5169]
**Describe the bug**
**If** we use `reset` to initialize our form state, **then** the next render will cause deep merging to fail. I am noticing this specifically on field arrays but it could occur in regular inputs as well. 

**To Reproduce**

1. Go to the sandbox
2. After 1 second open the console
3. Notice that `getValues()` only outputs the field array element that has been mounted. No deep merging has occured

**Codesandbox link (Required)**
https://codesandbox.io/s/frosty-night-4rt6n?file=/src/App.js

**Expected behavior**
While I would expect `setValue` to stop default value merge (assuming we pass a new array value in), `reset` should work. `reset` takes `defaultValues` as its first argument implying it should work the same as if we set our default values in `useForm`.

**Comment by bluebill1049** [comment]
fixed: `v7.5.3-beta.0`

**Comment by Aaronius** [comment]
OMG you have no idea how long I spent trying to figure out why this was happening. Thank you so much for reporting and fixing.
