### ISSUE TITLE
Controller fieldState is empty

### ISSUE THREAD

**Issue by jgullstr** [react-hook-form/react-hook-form#5176]
**Describe the bug**
I can't seem to get the fieldState object to populate for controlled fields. 

**To Reproduce**
1. Go to https://codesandbox.io/s/quirky-keller-jqb59
2. See error (fieldState is an empty object)

**Codesandbox link (Required)**
https://codesandbox.io/s/quirky-keller-jqb59

**Expected behavior**
fieldState should contain metadata { invalid, isTouched, isDirty, error } as described in https://react-hook-form.com/api/usecontroller/controller

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by jgullstr** [comment]
Apologies, first post formatted.

**Comment by bluebill1049** [comment]
<img width="1053" alt="Screen Shot 2021-05-12 at 10 11 59 pm" src="https://user-images.githubusercontent.com/10513364/117972929-14677b80-b36f-11eb-9b70-966db4f854a1.png">

if you log the object, you will see the value is there. It's a way for us to improve the perf, and knowing which attribute that you are accessing and hence trigger re-render accordingly.

you can find all the `fieldState` in this page: https://react-hook-form.com/api/usecontroller/controller

**Comment by jgullstr** [comment]
Aha, thanks! I haven't ran into a similar construct before.
