### ISSUE TITLE
Bug 7.5.3-beta.0 - Reset with nested list causes app to crash

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#5179]
**Describe the bug**
**If** we use `reset` and set a form value to an object that contains an array as a property **and** use `<Controller/>` with the `name` property matching the input path, **then** the library will throw an uncaught exception.

**To Reproduce**

1. Go to the sandbox
2. Notice the error
3. If you don't see the error then click the refresh button in code sandbox. 

**Codesandbox link (Required)**
https://codesandbox.io/s/objective-beaver-49w1t?file=/src/App.js

**Expected behavior**
This should still work as it does in the non-deep merge version of the library.

**Comment by bluebill1049** [comment]
@wdfinch the data structure is different tho:

```
name={`names.${index}.name`}
```

compare with 

```
reset({
      names: [
        {
          name: {
            title: "will",
            pets: []
          }
        }
      ]
    });
```

I don't think we should support for such usage.

**Comment by wdfinch** [comment]
So the input could be anything. For example, let's say we have a custom input like `react-select` and our input looks like this:

```
{
  value: string,
  label: string,
  meta: {
    someList: []
  }
}
```

In this example, I want to use react select but attach some meta information to each select input. I do this all the time currently. If we don't allow nested list items, then I can't use an array to represent the input.

Another example and where this is causing a crash in for a custom picklist component I built. The picklist allows the user to select an active and inactive list of elements. The data model looks like this.

```
interface Element {
  value: string, 
  label: string
}

interface PickListValue<> {
    activeElements: Array<Element>
    inactiveElements: Array<Element>
}
```

I use the `onChange` method provide by `field` in the controller `render` function in order to change this input. I currently can't use this input because it's represented using an object with a nested list.

Here's what it looks like for reference.

![Screenshot from 2021-05-12 16-52-53](https://user-images.githubusercontent.com/36898266/118058362-ecfab980-b342-11eb-844c-2d56bdb44a91.png)

**Comment by wdfinch** [comment]
For simple cases this is true, but many inputs are complex and don't align with a simple text or number. This is why `<Controller/>` exists, to give us a bridge to map our custom inputs to the form values.

**Comment by wdfinch** [comment]
Here's an example where we can't use hook form using an actual input.

This format is common within components like this:
https://material-ui.com/components/transfer-list/

https://codesandbox.io/s/icy-surf-3ps43?file=/src/App.js

**Comment by bluebill1049** [comment]
`v7.5.3-beta.2` can you try this beta?

**Comment by wdfinch** [comment]
Looks good! Thanks so much for this. I really appreciate it!

**Comment by bluebill1049** [comment]
No worries @wdfinch 👌
