### ISSUE TITLE
3.28.0 setError type incorrect

### ISSUE THREAD

**Issue by hitbear518** [react-hook-form/react-hook-form#518]
**Describe the bug**
in 3.28.0 setError's type is
```
setError: {
        (name: ManualFieldError<FormValues>[]): void;
        (name: FieldName<FormValues>, type: Record<string, import("./types").ValidateResult>): void;
        (name: FieldName<FormValues>, type: string): void;
    };
```
which only accept to arguments, which is previous 3

**To Reproduce**

**Codesandbox link**
Include a codesandox will help us to investigate the issue quicker.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bluebill1049** [comment]
@hitbear518 what do you mean? it always supports 2 arguments, but with the latest release, you supply an array of errors

**Comment by hitbear518** [comment]
in example it used 3 arguments `setError("username", "notMatch", "please choose a different username")`, previously in type declaration it's second param is  'type'.
by 3 arguments I mean 'name', 'type', 'message'.

**Comment by bluebill1049** [comment]
oh.... you are right!

**Comment by bluebill1049** [comment]
sorry i will patch it right away, crap...

**Comment by bluebill1049** [comment]
hmmm...

```
function setError(name: ManualFieldError<FormValues>[]): void;
  function setError(
    name: FieldName<FormValues>,
    type: MultipleFieldErrors,
  ): void;
  function setError(name: FieldName<FormValues>, type: string): void;
  function setError(
    name: FieldName<FormValues> | ManualFieldError<FormValues>[],
    type: string | MultipleFieldErrors = '',
    message?: string,
  ): void
```

**Comment by bluebill1049** [comment]
weird...

**Comment by bluebill1049** [comment]
find the issue, thanks mate :)
