### ISSUE TITLE
fieldsRef returned from useFormContext is stale

### ISSUE THREAD

**Issue by dkadrios** [react-hook-form/react-hook-form#5188]
v7.4.0

I've a generic form component that needs to know if any of the dynamically added inputs are marked as required.  (BTW, I'd be great if `formState` had a `hasRequired` or similar)

The way I'm going about this is:

```
const { control } = useFormContext()
const fields = control.fieldsRef.current

const hasRequiredFields = Object
  .values(fields)
  .some(isFieldRequired)
```
where `isFieldRequired` just checks to see if `required` is present and truthy for a given field.

This works great on the first render, however, if the number of required fields changes, the value does not update immediately.  It *does* update on the *next* render though.  It's as if the contents of `useFormContext` lags behind by one render (or at least the `control` property does).

Is this a known issue?  Is there a better way to get at the `required` prop of all registered controls?

**Comment by bluebill1049** [comment]
#2848
