### ISSUE TITLE
YUP+ RHF required file field do not show error message

### ISSUE THREAD

**Issue by denyschornyi** [react-hook-form/react-hook-form#5199]
**Describe the bug**
When make file validation with yup, required error messages do not shown.

For example.

const schema = yup.object().shape({
  files: yup.mixed().required("A file is required")
});

export const ApplicationForm = () => {
const { register, handleSubmit, errors, control, reset } = useForm({
    mode: "onBlur",
    resolver: yupResolver(schema)
  });

return (
   <div>
          <p >
            files{" "}
            <span> * {errors?.files?.message}</span>
          </p>
          <FileInput name="files" control={control} />
        </div>
);
}

Followed this tutorial: https://www.youtube.com/watch?v=tYGTjxhzrqY&t=40s&ab_channel=MaksimIvanov

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848
