### ISSUE TITLE
useFieldArray show default field value, when it mounts after being unmounted, instead of last actual field value

### ISSUE THREAD

**Issue by CyberNinja6610** [react-hook-form/react-hook-form#5202]
### Expected behavior
Field has actual value, when it mounts after being unmounted

### Expected behavior
Field value drops to default value, when it mounts after being unmounted

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-904hv

Edit field and use "Show/Hide" button, to mount/unmount.

**Comment by bluebill1049** [comment]
<img width="1154" alt="Screen Shot 2021-05-15 at 10 41 59 pm" src="https://user-images.githubusercontent.com/10513364/118361425-c3ee5900-b5ce-11eb-8021-df180d42b027.png">
