### ISSUE TITLE
Custom registered input error not getting removed

### ISSUE THREAD

**Issue by subhendukundu** [react-hook-form/react-hook-form#521]
**Describe the bug**
After page load if I submit the inputs, got a list of input errors of the required fields. After selecting the input or adding value, the errors not removing.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-custom-input-q1mo9
2. Click on Submit
3. See console.log about the errors
4. Now add the required values
5. See console logs, errors are still there

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-custom-input-q1mo9

**Expected behavior**
After adding the values, errors go away

**Desktop (please complete the following information):**
 Environment Info:

  System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.16.0 - ~/.nvm/versions/node/v12.4.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.97

**Comment by bluebill1049** [comment]
for the custom register, you will have to unregister yourself as well. because `ref` is not attached during `register`

https://react-hook-form.com/api#unregister

**Comment by subhendukundu** [comment]
A bit confusion here, when do I have to `unregister`?
Cause the idea is to make it work as it works with ref. So to do that are you unregister the input, but on what event? onsubmit?
Sorry for the trouble :(

**Comment by bluebill1049** [comment]
sorry I didn't look at your example just by reading your title...

`setValue("antDInput", e.target.value, true)` you can set the thrid argument to trigger validation.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#setValue

**Comment by subhendukundu** [comment]
Aha makes sense now. Ok, thanks
And if  I had a pattern to validate, I have to that with `triggerValidation` and based on that value passes the validation true false? No out of the box like normal input works?

**Comment by bluebill1049** [comment]
```
useEffect(() => {
  register({ name: 'test' }, { pattern: /\d+/, required: true  })
},[register])

<Input onChange={(e) => setValue('test', e.target.value, true)} />
```

should be the same.

**Comment by subhendukundu** [comment]
Perfect. Thanks
