### ISSUE TITLE
Type error occurs for nested arrays

### ISSUE THREAD

**Issue by tanmen** [react-hook-form/react-hook-form#5213]
**Describe the bug**
The key part that specifies the index of the Array generates an error.
```
const Component: FC = () => {
  const {register} = useForm<{options: ({value: string})[]}>();
  const [length, setLength] = useState(0);

  return <form>
    {
      Array.from(Array(length))
        .map((_, index) => <input {...register(`options.${index}.value`)}/>) // <- It is not recognized as a number string.
    }
  </form>
}
```

**To Reproduce**
Try it with the code above

**Codesandbox link (Required)**
https://codesandbox.io/s/pedantic-kapitsa-wxt6w?file=/src/App.tsx

**Expected behavior**
It is determined that the type of `options.${number}.value` is not applicable.
You need to either loosen the type or provide a function to generate the name.

**Screenshots**
<img width="1012" alt="スクリーンショット 2021-05-16 17 14 43" src="https://user-images.githubusercontent.com/18521406/118390820-25183a00-b66c-11eb-9708-1e3a4635a204.png">

**Desktop (please complete the following information):**
- OS: macOS
- Browser: Chrome 90
- Version: 7.6.0

**Smartphone (please complete the following information):**
I haven't tried it.

**Additional context**
N/A

**Comment by bluebill1049** [comment]
This is what you need.

<img width="968" alt="Screen Shot 2021-05-16 at 6 41 06 pm" src="https://user-images.githubusercontent.com/10513364/118391172-47af5080-b676-11eb-9387-72c063ebd290.png">


`<input {...register(`options.${index}.value` as const)} />`

**Comment by tanmen** [comment]
Oops, I hadn't been able to find it.
Sorry for being so busy.
Thank you very much!

**Comment by bluebill1049** [comment]
no worries at all @tanmen 🙏
