### ISSUE TITLE
{shouldUnregister: true} regression

### ISSUE THREAD

**Issue by davisriska** [react-hook-form/react-hook-form#5219]
**Describe the bug**
shouldUnregister: true doesn't work anymore.
By setting shouldUnregister to true at useForm level, defaultValues will not be merged against submission result.

**To Reproduce**

1. Click submit and check console.

**Codesandbox link (Required)**
https://codesandbox.io/s/dazzling-platform-5r5df?file=/src/App.js

**Expected behavior**
By setting shouldUnregister to true at useForm level, defaultValues will not be merged against submission result.

**Desktop (please complete the following information):**

- OS: OSX
- Browser chome
- Version 90.0.4430.212

**Comment by bluebill1049** [comment]
That's expected behavior, use `shouldUnregister: false` instead.

here is the reason why:

if a input gets remove/unmount then `shouldUnreigster true` will remove that input, but if we do merge again, it will bring the value back, it's not the intended behavior. 

<img width="786" alt="Screen Shot 2021-05-17 at 8 51 36 am" src="https://user-images.githubusercontent.com/10513364/118415339-19208c80-b6ed-11eb-9120-dd1b1e1b750f.png">

**Comment by davisriska** [comment]
> That's expected behavior, use `shouldUnregister: false` instead.
> 
> here is the reason why:
> 
> if a input gets remove/unmount then `shouldUnreigster true` will remove that input, but if we do merge again, it will bring the value back, it's not the intended behavior.
> 
> <img alt="Screen Shot 2021-05-17 at 8 51 36 am" width="786" src="https://user-images.githubusercontent.com/10513364/118415339-19208c80-b6ed-11eb-9120-dd1b1e1b750f.png">

If i change to shouldUnregister: false the values still get merged into the submission. Im confused now, what is the proper setting so that defaultValues and values from reset dont get merged into submission, if there are no fields for them?

**Comment by davisriska** [comment]
@bluebill1049 It seems I have made a mistake in the "Describe the bug" part. 

As I understand, shouldUnregister: true should make it so that defaultValues are **NOT** merged in the submission. Currently with version 7.6.0 this does not work. 

As you can see in my codesandbox, i have set shouldUnregister to true and the defaultValues and the values from reset still get merged into the submission.

**Comment by bluebill1049** [comment]
> @bluebill1049 It seems I have made a mistake in the "Describe the bug" part.
> 
> As I understand, shouldUnregister: true should make it so that defaultValues are **NOT** merged in the submission. Currently with version 7.6.0 this does not work.
> 
> As you can see in my codesandbox, i have set shouldUnregister to true and the defaultValues and the values from reset still get merged into the submission.

I think the problem is why irrelevant form default values get stored in `defaultValues` in the first place, I think overall this new feature with register absent inputs is beneficial to all use cases. 

```
onst [value] = React.useState(() => ({
  a: ["value", "value2"],
  firstName: "firstName"
}));
```

also when you reset, why are you reset inputs which are not in the view for shouldUnregister: true? 

<img width="603" alt="Screen Shot 2021-05-17 at 5 15 31 pm" src="https://user-images.githubusercontent.com/10513364/118446910-7e976c00-b733-11eb-82b5-4b8c64fbd132.png">

the above is when I switch between 7.5 and 7.6.

**Comment by davisriska** [comment]
> I think the problem is why irrelevant form default values get stored in `defaultValues` in the first place, I think overall this new feature with register absent inputs is beneficial to all use cases.

For example i get data from an api - 
```json
{"username": "someUsername", "abilities": [], "roles": []}
```

The form only contains field username and roles.someRole. I would like to not need to remove this abilities array. This is a simplified version of the issue.

An actual issue for example is that i have a form that can have a list of files or string/number input. When I open this form for edit, I get back an api response with 
```
{"files":[], value:"someValue", "type": "string"}
```

The form gets built appropriately from the json response, but with this change i have to process the response even more before using it to build the form.

And I would assume that this breaks this too - https://github.com/react-hook-form/react-hook-form/issues/4619

**Comment by davisriska** [comment]
> > @bluebill1049 It seems I have made a mistake in the "Describe the bug" part.
> > As I understand, shouldUnregister: true should make it so that defaultValues are **NOT** merged in the submission. Currently with version 7.6.0 this does not work.
> > As you can see in my codesandbox, i have set shouldUnregister to true and the defaultValues and the values from reset still get merged into the submission.
> 
> I think the problem is why irrelevant form default values get stored in `defaultValues` in the first place, I think overall this new feature with register absent inputs is beneficial to all use cases.
> 
> ```
> onst [value] = React.useState(() => ({
>   a: ["value", "value2"],
>   firstName: "firstName"
> }));
> ```
> 
> also when you reset, why are you reset inputs which are not in the view for shouldUnregister: true?
> 
> <img alt="Screen Shot 2021-05-17 at 5 15 31 pm" width="603" src="https://user-images.githubusercontent.com/10513364/118446910-7e976c00-b733-11eb-82b5-4b8c64fbd132.png">
> 
> the above is when I switch between 7.5 and 7.6.

This https://codesandbox.io/s/dreamy-blackburn-uvr5d is with 7.5.3 and it only gives firstName submission value.

**Comment by bluebill1049** [comment]
you shouldn't put irrelevant data into the `reset` in the first, you are basically doing a `useState` but include all the irrelevant data to the form and this would also break if users are using typescript.

**Comment by bluebill1049** [comment]
> And I would assume that this breaks this too - #4619

I don't think this would break the above too, the above feature request was based on inputs get removed and the state still retained.

if input is part of the `defautlValues` or gets registered, the moment it gets unmounted they will also get `unregsitered`

**Comment by francofantini** [comment]
Hi! I'm having the same issue over here. 
I do a GET from an API to populate the defautlValues and I get data that I don't need on submission result.

From the documentation:
![image](https://user-images.githubusercontent.com/11973156/119240778-6b681000-bb28-11eb-8413-28f485bd5399.png)
I understand that when I set `shouldUnregister: true` defaultValues not registered on the form will not be merged against submission result. I'm I understanding the docs right? 

Thanks for taking the time!

**Comment by bezreyhan** [comment]
@bluebill1049 I'm getting a similar error: setting `shouldUnregister: true` does not remove the input values from the `handleSubmit`. Meaning, even though the input is no longer mounted, I'm still seeing its values inside of `handleSubmit`.

The values is being set via `reset` when the api data is returned. But if that input gets unmounted, I'm still seeing the inputs value.

Am I understanding the purpose of `shouldUnregister` correctly?

**Comment by bluebill1049** [comment]
Hey guys, can you please share a simple  reproduceable codesandbox? So I can investigate if it's a bug or not?

**Comment by bezreyhan** [comment]
@bluebill1049 Yes I just put this together:  https://codesandbox.io/s/prod-cherry-zbhil?file=/src/App.tsx

I have two inputs that are conditionally rendered. When one the inputs  un-mounts, its value get's applied to the newly mounted input. Also, the value is retained inside of `handleSubmit`

Thanks for your help in looking into this.

Here is a quick video as well: 

https://user-images.githubusercontent.com/6013763/119873987-03277e80-beda-11eb-90b0-a2d697b207ff.mov

**Comment by bluebill1049** [comment]
Thanks, @bezreyhan for the detailed reply above. I just tried your CSB. it's working for me.

https://user-images.githubusercontent.com/10513364/119907119-f31fa580-bf92-11eb-9d12-20f38a2b98a4.mov

**Comment by bezreyhan** [comment]
@bluebill1049 I think I found the issue and updated the CSB, I should have forked it. I just reverted my changes so now it should be broken again.

The fix was to assign a unique `key` to each input. I'm not sure if this is required for React or a bug in react-hook-form. 

Here is a link to the updated version that has the fix: https://codesandbox.io/s/react-hoo-form-shouldunregister-fix-modfu?file=/src/App.tsx

**Comment by bluebill1049** [comment]
> @bluebill1049 I think I found the issue and updated the CSB, I should have forked it. I just reverted my changes so now it should be broken again.
> 
> The fix was to assign a unique `key` to each input. I'm not sure if this is required for React or a bug in react-hook-form.
> 
> Here is a link to the updated version that has the fix: https://codesandbox.io/s/react-hoo-form-shouldunregister-fix-modfu?file=/src/App.tsx

oh yea, for toggling native input, `key` is required to let react know it's a different component/input.

**Comment by bluebill1049** [comment]
reference here: https://react-hook-form.com/faqs#Whyisdefaultvaluenotchangingcorrectlywithternaryoperator

**Comment by bezreyhan** [comment]
Got it, sorry I missed that.
