### ISSUE TITLE
Remove browser build-in validation feature

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#522]
Hi guys,

I just want to get your thoughts on remove `nativeValidation` option at `useForm`.
https://react-hook-form.com/api#NativeValidation
after 9 months of maintaining this lib, there is no single question regard browser build-in validation, I have a feeling that most of us are using this lib for custom form validation (which is what I used at work as well). 

I still want to keep this lib as light and small as possible even though at this stage our bundle size is 5.6Kb which is small but eliminated browser build-in validation, we can reduce the package size even more and leave us with the room with other features.

If not many of you are against doing so, I would probably drop this option off on the next release.

<img width="527" alt="Screen Shot 2019-11-17 at 4 02 45 pm" src="https://user-images.githubusercontent.com/10513364/69003329-b8778e80-0953-11ea-9ddf-3f1924dec2b2.png">
(Browser build-in validation)

cheers
bill

**Comment by Kurzdor** [comment]
The library is already lighter than all form managment libraries, so be mindful when removing any API. Personally, I don't use NativeValidation API in library.

**Comment by bluebill1049** [comment]
yea thanks @Kurzdor for your feedback.

**Comment by sirluis** [comment]
I think it's good to have native validation as an alternative to yup (which is pretty huge and no tree-shakeable) until the generic validation feature comes out.

**Comment by bluebill1049** [comment]
thanks, @sirluis for your feedback, I think I may confused you with `native validation`, it's the browser build-in validation (I will update with a screenshot), which hardly has people using it with this lib. Yes, generic schema validation is going to come, I have a plan for it already :)

**Comment by bluebill1049** [comment]
I am more than happy to keep its functionality if people are using it, otherwise, it's a burden for this lib.

**Comment by stramel** [comment]
Hmm between this and adding custom schema validation. I feel like we could probably just implement the generic validation API for a plug-in style architecture. I brought it up a while back

**Comment by bluebill1049** [comment]
valid point :) I didn't pursuit the plugin idea, because I prefer dev not to worry about which plugin for which type of validation. To be honest, I may just keep browser build in validation, it probably only can save us 0.2 - 0.3 Kb (gzipped). any thought on the custom schema validation, I want to support Joi and other validation schemas for a while, I think this will help.

**Comment by bluebill1049** [comment]
closing this, for now, maybe we can leave as it is...

**Comment by github0013** [comment]
nativeValidation is actually removed in V4?

**Comment by bluebill1049** [comment]
yea removed in V4 @github0013 hardly anyone using it.
