### ISSUE TITLE
Reset one field resetting the whole form

### ISSUE THREAD

**Issue by mcha-dev** [react-hook-form/react-hook-form#5223]
Hello, 

**Describe the bug**
My understanding is [reset](https://react-hook-form.com/api/useform/reset) can be used to reset one field only (while keeping other dirty ones as they are)

Simple scenario: 2 drop downs (state & city). I want to reset the `city` when the `state` changes

**To Reproduce**

1. Go to [codesandbox](https://codesandbox.io/s/keen-monad-ddoyc?file=/src/App.tsx:524-621)
2. Select state/city works fine
3. Now uncomment `React.useEffect` 
4. Now try to select a state (nothing will be selected cause the `reset` is resetting the whole form)

**Codesandbox link (Required)**
https://codesandbox.io/s/keen-monad-ddoyc?file=/src/App.tsx:524-621

**Expected behavior**
`reset` to only reset the field(s) provided to it

**Screenshots**

https://user-images.githubusercontent.com/13101565/118499582-456df480-b751-11eb-8ef3-959706228473.mov

**Comment by JGibel** [comment]
Why not just call setValue instead?

**Comment by mcha-dev** [comment]
I ended up using `setValue` instead. Please close if it's not an issue

**Comment by JGibel** [comment]
csb w/ setValue in case anyone from the internet comes across this in the future: https://codesandbox.io/s/crazy-gates-lkuk8

**Comment by mcha-dev** [comment]
The reason I wanted to do it with `reset` was/is to avoid writing several `setValue`s.

I ended up extracting the logic to a custom hook:

```js
export function useWatchFields() {
  const { watch } = useFormContext();
  const [region, country, state] = watch(['region', 'country', 'state']);

  const { setValue } = useFormContext();

  useEffect(() => {
    setValue('country', '');
    setValue('state', '');
    setValue('city', '');
  }, [region]);

  useEffect(() => {
    setValue('state', '');
    setValue('city', '');
  }, [country]);

  useEffect(() => {
    setValue('city', '');
  }, [state]);

  return {
    region, country, state,
  };
}

```

**Comment by bluebill1049** [comment]
```
reset({
   ...getValues(),
   // reset goes here
})
```

however, I would still recommend going with setValue, you can easily write an abstraction to do multiple eg setValues
