### ISSUE TITLE
7.6.x - App crashes when using form in react-modal, with downshift.

### ISSUE THREAD

**Issue by florianchevallier** [react-hook-form/react-hook-form#5229]
**Describe the bug**
App crashes when using form in react-modal, with downshift.
I don't know if it's a regression, but this code works until 7.6.0

**To Reproduce**
Steps to reproduce the behavior:  https://codesandbox.io/s/frosty-night-fmih5?file=/src/App.tsx

**Expected behavior**
Not to crash

**Desktop (please complete the following information):**

- OS: MacOS
- Browser : Chrome, Safari, Edge
- Version : 92.0.4510.0

**Additional context**
Everything is in the codesandbox. I've tried to simplify the most.
I've also tried in 7.6.1-beta.1, but still go the same.

Many thanks !

**Comment by bluebill1049** [comment]
thank you very much for the detailed issue report! it really helps.

**Comment by florianchevallier** [comment]
You're very welcome, thank _you_ for this amazing lib 😄
