### ISSUE TITLE
Document version 7.6.0 as a breaking change

### ISSUE THREAD

**Issue by mrlubos** [react-hook-form/react-hook-form#5232]
**Is your feature request related to a problem? Please describe.**
There's a breaking change that occurred after the release of [version 7.6.0](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.6.0). I suspect it is related to https://github.com/react-hook-form/react-hook-form/pull/5069 where we add default values to register even if their corresponding fields are not rendered.

Previously, if we wanted to manually track fields that were not rendered in the HTML, we'd do something like this

```tsx
const { register } = useForm({
  defaultValues: {
    manuallyTracked: true,
  },
});

useEffect(() => {
  register('manuallyTracked');
}, []);

// some functions modifying manuallyTracked state

return (
  <html-without-input-named-manually-tracked />
)
```

With the release of version 7.6.0, we no longer need to call `register()` to manually track fields which is great! However, doing so may result in unexpected bugs. In my case, an empty array was becoming an empty object.

**Describe the solution you'd like**
Document this change and the fact we no longer need nor should call `register()` to manually register inputs.

**Describe alternatives you've considered**
Downgrading the library version 😂

**Additional context**
N/A

**Comment by bluebill1049** [comment]
>  In my case, an empty array was becoming an empty object.

can you describe the use case above?

**Comment by bluebill1049** [comment]
I will include more detail on the `defaultValues` section under `useForm`.

**Comment by bluebill1049** [comment]
<img width="939" alt="Screen Shot 2021-05-18 at 7 35 29 pm" src="https://user-images.githubusercontent.com/10513364/118628741-4023af00-b810-11eb-948e-711750bf6bd2.png">

doc updated and changelog also has relevant information. Let me know your use case, in case there is something I have miss implemented.

**Comment by mrlubos** [comment]
> <img alt="Screen Shot 2021-05-18 at 7 35 29 pm" width="939" src="https://user-images.githubusercontent.com/10513364/118628741-4023af00-b810-11eb-948e-711750bf6bd2.png">
> 
> doc updated and changelog also has relevant information. Let me know your use case, in case there is something I have miss implemented.

Thanks @bluebill1049! I was going to create a CodeSandbox but in the middle of doing so I realised "hold on, let's try to remove the manual register step" and it worked without it. I am unable to reproduce it locally with primitive values, it seems to only affect arrays or perhaps empty arrays to be more precise.

My use case is a form in which one field is a list of selected string ids. This is always initialised to be an empty array and simply by logging the watched value I could see it has the correct state for a few re-renders but then suddenly changes to an empty object. Removing the register call as outlined above or downgrading to previous version fixes the issue.

**Comment by bluebill1049** [comment]
Thanks for the update @mrlubos Let me know if you can reproduce that issue, I am happy to investigate to the problem why and potentially patch it within the library.

**Comment by mrlubos** [comment]
> Thanks for the update @mrlubos Let me know if you can reproduce that issue, I am happy to investigate to the problem why and potentially patch it within the library.

I found a related issue I believe, it might've appeared after removing the `register()` call https://github.com/react-hook-form/react-hook-form/issues/5423

**Comment by mrlubos** [comment]
Hey @bluebill1049, just wanted to provide you with an update. I was able to isolate the issue related to removing the `register()` call in my code. The bug was in my application, so nothing to fix in `react-hook-form`. Thank you for your fast responses and continued maintenance of this library!

**Comment by bluebill1049** [comment]
> Hey @bluebill1049, just wanted to provide you with an update. I was able to isolate the issue related to removing the `register()` call in my code. The bug was in my application, so nothing to fix in `react-hook-form`. Thank you for your fast responses and continued maintenance of this library!

That's awesome to hear! thanks for the update.

**Comment by mrlubos** [comment]
@bluebill1049 Hey Bill, sorry for the back and forth. 😃 I am not sure if this is something to be fixed on my end after all.

I managed to narrow it down to this [CodeSandbox](https://codesandbox.io/s/proud-dust-dd4xq?file=/src/App.tsx). The important part is that I am logging the value of `array`. `defaultValues` is a static object, so the form state should not change. Notice it's correct on the first render, but on the second render, the `array` value becomes `undefined`.

This happens when a `useEffect()` updates any React state which triggers another render. You can verify this by looking at the render count which shows "2" instead of the default "1" it shows in RHF examples.

Are you able to provide any insights as to why this is happening? Frankly, this might be hard to resolve on my end because of the way React hooks work. I wonder what's going on in RHF as to me, it appears I am making the same call twice, so I should not get 2 different values for `array`. Are you able to help?

**Comment by mrlubos** [comment]
@bluebill1049 You can also notice I am using `register()` to instantiate the manual field. If I remove that call, this bug becomes resolved, but then I run into https://github.com/react-hook-form/react-hook-form/issues/5423 which we already discussed. So I either get array `undefined` when using `register()`, or the array won't update on modification when not using `register()`.

**Comment by mrlubos** [comment]
@bluebill1049 I'd like to point out to you the difference between library versions and this matches my experience but I thought I was noticing things because nobody else reported it. So if you switch the library in CodeSandbox to version `7.5.3`, everything works well. If you switch it to version `7.6.0`, the second render will return an empty object `{}`. If you switch it to version `7.6.1` or newer, the second render will return `undefined`.

**Comment by mrlubos** [comment]
@bluebill1049 So in conclusion, I think the title of this issue is correct -> "document version 7.6.0 as a breaking change" 😃

**Comment by bluebill1049** [comment]
Thanks for putting up all the investigation in the codesandboxes above, looks like it's an edge case that I didn't consider carefully enough for inputs that you want to update manually without an actual input. As I explained in the other issue, react hook form can't predict if it's a single input or array of inputs. 

Here are a couple workaround for such use cases: 

7.8.0 (which will release this weekend)

- Letting hook form know that its a single input and assign it with value
https://codesandbox.io/s/awesome-mestorf-9bktk?file=/src/App.tsx

```
React.useEffect(() => {
  register("array", { value: getValues("array") });
}, [register, getValues]);
```

- set `shouldUnregister: true`, so it's more close to native form behavior, the input value will get removed after unmount and `defaultValues` will not be automatically registered.
https://codesandbox.io/s/eager-darkness-l8rw4?file=/src/App.tsx

```
const { control, getValues, handleSubmit, register, watch } = useForm<
  FormValues
>({
  defaultValues,
  shouldUnregister: false
});
```

I hope the above can solve your problem.

**Comment by mrlubos** [comment]
> Thanks for putting up all the investigation in the codesandboxes above, looks like it's an edge case that I didn't consider carefully enough for inputs that you want to update manually without an actual input. As I explained in the other issue, react hook form can't predict if it's a single input or array of inputs.
> 
> Here are a couple workaround for such use cases:
> 
> * Letting hook form know that its a single input and assign it with value [7.8.0 (which will release this weekend)]
>   https://codesandbox.io/s/awesome-mestorf-9bktk?file=/src/App.tsx
> 
> ```tsx
> React.useEffect(() => {
>   register("array", { value: getValues("array") });
> }, [register, getValues]);
> ```
> 
> * set `shouldUnregister: true`, so it's more close to native form behavior, the input value will get removed after unmount and `defaultValues` will not be automatically registered.
>   https://codesandbox.io/s/eager-darkness-l8rw4?file=/src/App.tsx
> 
> ```tsx
> const { control, getValues, handleSubmit, register, watch } = useForm<
>   FormValues
> >({
>   defaultValues,
>   shouldUnregister: false
> });
> ```
> 
> * `unregister` input and then `setValue` to reset the entire field input.
> 
> ```tsx
> unregistre('array');
> setValue('array', [1,2,3]);
> ```
> 
> I hope the above can solve your problem. In the meantime, I will still try to figure a solution for custom array-like inputs (which doesn't contain a real input) with auto register in the coming releases.

Thank you! I think the second approach with `shouldUnregister` will work as it should essentially be the behaviour prior to `7.6.0`, right? Either way I tested it and it appears to work as expected. Thanks again
