### ISSUE TITLE
useFieldArray with nested arrays throws error with `append` and `remove` in nested array (data is not iterable)

### ISSUE THREAD

**Issue by mason-smith** [react-hook-form/react-hook-form#5246]
**Describe the bug**

Creating a nested useFieldArray 
```
setValue("test", [
  ...(getValues().test || []),
  {
    name: "append",
    nestedArray: [{ field1: "append", field2: "append" }]
  }
]);
```
does not populate the fields for `nestedArray` values `field1` and `field2`

Using 
```
remove(k)
```
to remove the empty `nestedArray` throws an error. `removeAtIndexes - data is not iterable`

<hr />

Creating a nested useFieldArray 
```
setValue("test", [
  ...(getValues().test || []),
  {
    name: "append",
    nestedArray: [{ field1: "append", field2: "append" }]
  }
]);
```
and then using 
```
append({
  field1: "field1",
  field2: "field2"
})
```
to append a nested array throws an error `append - data is not iterable`

<hr />

Using
```
append({ name: "append" });
```
to create a single level array works. 

Using
```
append({
  field1: "field1",
  field2: "field2"
})
```
to populate the `nestedArray` works

Using
```
setValue("test", [
  ...(getValues().test || []),
  {
    name: "append",
    nestedArray: [{ field1: "append", field2: "append" }]
  }
]);
```
to create a new nested array clears the values of the other `nestedArray`

This seems like it could be somewhat related to #5208

<hr />

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-cg4yj?file=/src/index.js
2. Click on 'Append Nested' button
3. Notice the fields are not populated with default values
4. Click on 'Delete Nested' button
5. Observe thrown error
6. Clear the error and refresh the page
7. Click on 'Append Nested' button
8. Click on the new 'Append Nested' button that appears above the `hr` tag
9. Observe error
10. Clear the error and refresh the page
11. Click the 'Append' button
12. Click on the new 'Append Nested' button that appears above the `hr` tag
13. Click on the original 'Append Nested' button below the `hr` tag
14. Notice the fields are cleared of their default values

<hr />

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-cg4yj?file=/src/index.js

USING v7.6.2

<hr />

**Expected behavior**
Should work exactly as the [v7.0.0 example](https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-m8w6j?file=/src/index.js) without errors

<hr />

**Desktop (please complete the following information):**

- OS: Mac OSX
- Browser: chrome, firefox
- Version 7.6.2

**Comment by peakercope** [comment]
@bluebill1049  I have the same issue with `prepend` function

**Comment by bluebill1049** [comment]
> @bluebill1049  I have the same issue with `prepend` function

Can u submit an separate issue and follow the template?

**Comment by peakercope** [comment]
I'm sorry it was my mistake. I was using `prepend` to add element with nested array.
With `setValue` it works ok

**Comment by mason-smith** [comment]
@bluebill1049 You rock, thanks for tackling this!

**Comment by simplenotezy** [comment]
I have the same issue - it works with with setValues, but not with prepend.

          append({ name: 'append' }); // does not work
          setValue('memberships', [ // works
            ...(getValues().memberships || []),
            {
              name: 'append',
            },
          ]);

**Comment by bluebill1049** [comment]
can you provide a codesandobx @simplenotezy ?
