### ISSUE TITLE
If a field changed from disabled to enabled, it passes undefined to validate function.  

### ISSUE THREAD

**Issue by mjza** [react-hook-form/react-hook-form#5272]
I want to have a sort of switch between review and edit mode in my form, then I used `disabled` property. 

If this property is controlled with a property in `state`, and its value set to `true` in the beginning, then the value that is passed to the `validate` function would be `undefined`. 

Please look at the following sandbox:

https://codesandbox.io/s/react-hook-form-controlled-input-failed-validation-bug-forked-gxbh5?file=/src/index.js:1749-1764

The input field has value but when we press on submit we will see error!

In my real app, user press on an edit button, the field would change from disabled to enabled, however, when user presses on submit button they will see error while the item has value!

In version 6 it was working, upgrading to version 7 caused this error.

**Comment by mjza** [comment]
Check the console for better understanding:

```
Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at form
    at Login (https://gxbh5.csb.app/src/index.js:48:34)
    at App (https://gxbh5.csb.app/src/index.js:142:41)
```

**Comment by mjza** [comment]
Also if the field has the `autoComplete` property, again it does not recognise the value, and will pass `undefined` to the `validate` function, for example:

`autoComplete="username"`

**Comment by leapful** [comment]
@mjza 

This is not a bug. Disabled field value will not be included in form following the web standard. 

Referrer:
https://react-hook-form.com/api/useform/handlesubmit/#main
https://stackoverflow.com/questions/1355728/values-of-disabled-inputs-will-not-be-submitted

Your second issue of attribute "autocomplete" cannot be re-produced too. Plus, the block code in your comment is not using "validate".
