### ISSUE TITLE
Calling setValue on Material UI Autocomplete input fails when default value is undefined.

### ISSUE THREAD

**Issue by josiahayres** [react-hook-form/react-hook-form#5279]
**Describe the bug**
Calling setValue for Material UI Autocomplete component when default value is "undefined" fails to work as expected.
When setting default value to empty string, calling setValue returns expected results. 
Autocomplete is connected up using Controller component as per documentation. 

Potentially related to, but not exactly the same as #5276

**To Reproduce**

1. Go to [code sandbox](https://codesandbox.io/s/react-hook-form-v7-controller-forked-683yc?file=/src/index.js)
2. Scroll down to the new set country button (below MUI autocomplete section which is enabled).
3. Verify that country is empty.
4. Click set country button.
5. This is the bug, nothing happens. I would expect to see country now display "New Zealand" but it's still empty. 

Temporary workaround: 
1. Scroll up to line 41 of index.js and change `country: undefined,` to `country: ""`
2. Reload the app, and repeat steps 3 and 4.
3. Clicking set country when default is empty string works as expected. 

As country is an object I would expect that I can leave it empty by defaulting it to undefined.

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-v7-controller-forked-683yc?file=/src/index.js

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Edge
- Version: 90.0.818.62 (Official build) (64-bit)

**Additional context**

**Comment by bluebill1049** [comment]
Thanks for the issue report, but please keep your codesandbox as minimal and isolated as possible.

**Comment by josiahayres** [comment]
Fair enough - I have removed all unrelated code that was pulled in when forking the codesandbox from the demo. I have updated the link.

**Comment by bluebill1049** [comment]
`defaultValue` can't be `undefined`, i will update the doc on this part.

**Comment by JamesWong1999** [comment]
`undefined` will lead to uncontrolled become controlled.

**Comment by bluebill1049** [comment]
<img width="930" alt="Screen Shot 2021-05-21 at 6 18 50 pm" src="https://user-images.githubusercontent.com/10513364/119105750-00073b00-ba61-11eb-9071-eedac47b30a5.png">

doc is updated.
