### ISSUE TITLE
Can't watch field when using react-input-mask

### ISSUE THREAD

**Issue by gustavopch** [react-hook-form/react-hook-form#528]
**Describe the bug**
When using `react-input-mask`, the input stops working as soon as you `watch` the field.

**To Reproduce**
1. Open the CodeSandbox.
2. Try typing in the first input: it works.
3. Try typing in the second input: you can't type.

**Codesandbox link**
https://codesandbox.io/s/exciting-germain-73xe4

**Expected behavior**
The second input should work just like the first one.

**Desktop:**
 - OS: Linux
 - Browser: Chrome
 - Version: 78

**Comment by bluebill1049** [comment]
hey @gustavopch,

The issue because when you are watching the `input`, it will get re-rendered each keystroke. I will suggest using onChange yourself to do the masking.

`<input name="test" onChange={e => e.target.value = 'do your mask here' } />`

**Comment by gustavopch** [comment]
@bluebill1049 The problem with doing the mask myself is that it'll lose the cursor position as I add/remove characters. There are also a lot of little UX details around input masking that are not trivial to address.

To name just one example:
1. Open this CodeSandbox: https://codesandbox.io/s/387z7njwzp
2. Enter "12" in the DOB field. It'll automatically become "12/" and the cursor will be positioned after the slash.
3. Now press backspace once.
4. You'll see that the slash is re-added.

**Comment by bluebill1049** [comment]
please use this, for now, I will take a looking solution with `watch`

```
import React from "react";
import ReactDOM from "react-dom";
import useForm from "react-hook-form";
import MaskedInput from "react-input-mask";

function App() {
  const [value, setValue] = React.useState("");
  const { register } = useForm();

  console.log('value', value)

  return (
    <div>
      <MaskedInput
        name="date1"
        mask="99/99/9999"
        inputRef={register}
        onChange={e => setValue(e.target.value)}
      />
      <br />
      <MaskedInput name="date2" mask="99/99/9999" inputRef={register} />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by gustavopch** [comment]
I understand. Thanks @bluebill1049. I don't know if you want to keep this issue open while you investigate further. You may close it if you want.

Just as a side note: maybe you should think about adding masking capabilities to this lib. :thinking:

**Comment by bluebill1049** [comment]
thanks @gustavopch I will leave this open until I figure out something. yea I will get to that when I get some free time (right now RHF takes most of the time), it would be a separate project tho :)

**Comment by bluebill1049** [comment]
hey @gustavopch 

I think this is a better solution: 

```
function App() {
  const { register, watch } = useForm();

  const date2 = watch("date2", "");

  return (
    <div>
      <MaskedInput name="date1" mask="99/99/9999" inputRef={register} />
      <br />
      <MaskedInput
        name="date2"
        mask="99/99/9999"
        onChange={() => {}}
        value={date2}
        inputRef={register}
      />
    </div>
  );
}
```

**Comment by bluebill1049** [comment]
we can close this if you are happy with the above solution :)

**Comment by gustavopch** [comment]
@bluebill1049 I've replicated your last suggestion. It doesn't work well, try typing in the second input: https://codesandbox.io/s/admiring-glade-b5p7k

**Comment by bluebill1049** [comment]
hmmm I am not sure then (not sure the detail about the input mask component)... please use `useState` for now :)

**Comment by bluebill1049** [comment]
ok final solution : )  and it works closing

```
import React from "react";
import ReactDOM from "react-dom";
import useForm from "./src";
import MaskedInput from "react-input-mask";

const Test = React.memo(({ register }) => {
  return (
    <>
      <MaskedInput name="date1" mask="99/99/9999" inputRef={register} />
      <br />
      <MaskedInput
        name="date2"
        mask="99/99/9999"
        onChange={() => {}}
        // value={date2}
        inputRef={register}
      />
    </>
  );
});

function App() {
  const { register, watch } = useForm();

  const date2 = watch();
  console.log('test', date2)

  return (
    <div>
      <Test register={register} />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by codler** [comment]
@bluebill1049 any plans to bundle mask feature to react-hook-form?

**Comment by bluebill1049** [comment]
hey @codler we don't have any plan to handle masking. I think it's better to leave this for the external component library (I think there are components out there). I prefer to keep RHF small, simple and focus.
