### ISSUE TITLE
Conditional rendering of components don't work in React.StrictMode

### ISSUE THREAD

**Issue by talcomputas** [react-hook-form/react-hook-form#5283]
**Describe the bug**
When running an React App in StrictMode where some parts of the form are conditional, the conditional components are never rendered.

**To Reproduce**

1. Go to codesandbox and see example where 2 questions appear.
2. Go into index.tsx, and remove the <React.StrictMode> tag.
3. REfresh page, and see the 2 questions dissaper.

**https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-dg287?file=/src/index.tsx**

V7

- [JS](https://codesandbox.io/s/great-paper-deove) Template
- [TS](https://codesandbox.io/s/eager-sun-jt4df) Template

V6

- [JS](https://codesandbox.io/s/mystifying-keller-5jwf5) Template
- [TS](https://codesandbox.io/s/romantic-moon-0chz7) Template

**Expected behavior**
The StrictMode should not interfer with the rendering of the RHF components.

**Comment by bluebill1049** [comment]
<img width="1114" alt="Screen Shot 2021-05-22 at 9 36 07 am" src="https://user-images.githubusercontent.com/10513364/119207307-240a6100-bae1-11eb-8563-841d9ddf6406.png">

please provide a relevant codesandbox and keep example isolated and minimal.

**Comment by bluebill1049** [comment]
will re-open once the above is udpated.

**Comment by talcomputas** [comment]
I have made the example sandbox as minimal as I could.

[](https://codesandbox.io/s/usearray-nested-not-registered-s1yue?file=/src/index.tsx)

**Comment by talcomputas** [comment]
I have clarified the example as best as I could.

The example is in TypeScript, with a model Building-> Floors -> Rooms.

Without the <React.StrictMode> around the <App> component, the sandbox works fine. However, with strictmode on the Rooms will not show on the page. If I change any of the fields that are shown, I see that the Rooms are registered when I submit the form. But of course, as they are not visible i cannot change any of them :-) 

I suspect this is an issue with the "useFieldArray as const name". In your React Form Hooks own example with nested fieldArrays everythinh works fine, but that is in JS, not TS.



**https://codesandbox.io/s/usearray-nested-not-registered-s1yue?file=/src/index.tsx**
