### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined using v7

### ISSUE THREAD

**Issue by Jonofat** [react-hook-form/react-hook-form#5288]
I am not sure if this is because your tutorial was using V6 and I am using V7 but I get the 'split' error when clicking 'Append'. I was following your awesome tutorial here:

https://www.youtube.com/watch?v=LhIvi4XHIco

```
import { useForm, useFieldArray, useWatch } from "react-hook-form";

const Create = () => {
  const { register, control } = useForm();
  const { fields, append, remove } = useFieldArray({
    control,
    name: "items",
  });
  return (
    <form>
      {fields.map(({ id }) => {
        return (
          <div key={id}>
            <input ref={register()} name="" />
            <button ref={register()} type="button" name="" />
          </div>
        );
      })}
      <button type="button" onClick={() => append({})}>
        Append
      </button>
    </form>
  );
};

export default Create;
```

I am doing this in a Next.js project but wouldn't think it would make a difference

**Comment by bluebill1049** [comment]
hey buddy, the video tutorial is on v6.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/usefieldarray

<img width="1020" alt="Screen Shot 2021-05-22 at 7 18 38 pm" src="https://user-images.githubusercontent.com/10513364/119221386-83dd2800-bb32-11eb-991b-c76424b006a0.png">
