### ISSUE TITLE
deselecting checkbox returns false instead of null or empty array

### ISSUE THREAD

**Issue by curlybom** [react-hook-form/react-hook-form#5296]
**Describe the bug**
When there's only one checkbox input and you deselect it, `onChange` returns `false` instead of `null` or empty array

check the example below :
https://codesandbox.io/s/proud-fire-lexrn?file=/public/index.html

**Comment by bluebill1049** [comment]
This is expected behavior which returns `e.target.checked,` if you want to return `null`, build a controlled input and return value as your requirement.
