### ISSUE TITLE
`minLength` validation triggers when empty and not required

### ISSUE THREAD

**Issue by jgb-solutions** [react-hook-form/react-hook-form#530]
I have an input that's not required. But if it has a value, the length must be at least 20 characters. 

Goal: If empty, submitting the form without it should succeed. 
Behavior: It asks for a min length of 20 when the field is not required.

**Comment by bluebill1049** [comment]
@jgb-solutions, please try to upgrade to the latest version, also please consider uploading a codesandboa by following the issue template 👍

**Comment by jgb-solutions** [comment]
ok thanks! I'll try upgrading it and let you know how it goes.

**Comment by jgb-solutions** [comment]
upgrading from `3.23.18` to `3.28.1` actually fixes it. Thanks.

**Comment by bluebill1049** [comment]
great :) closing
