### ISSUE TITLE
First time interaction not working with Object / Array as field default values with Controller

### ISSUE THREAD

**Issue by uidev547** [react-hook-form/react-hook-form#5300]
**Describe the bug**
When **useForm** initialized with **defaultValues** ( consists field value as Array or Object ) and **Controller** is used for rendering the input / Custom input field then first time interaction is not working as expected. But from the second time interaction onwards it works fine.  codesanboxlink added for to reproduce the scenario. 

**Version**: (react-hook-form # 7.6.5)

**To Reproduce**

1. Go to 'https://codesandbox.io/s/elegant-haibt-i1bp8'
2. With in 'Component with react-hook-form' under section1 try to check / uncheck the checkboxes (observe first interaction is not working)
3. With in 'Component with react-hook-form' section2 try to uncheck checkboxes[Surfing, Reading] (observe first interaction is not working) (but Try to check 'Playing' will work fine in the first time interaction) 
4. Same component is working fine with similar data working fine in 'section3' and 'section4'
5. Please reload the page to reproduce every time

*Observations*
- Addition of the fields in to array or object (addition of new key fields in the object) working fine in the first interaction

**Expected behavior**
It should be able to work on the first interaction with give scenario

- Browser [chrome, Firefox, Edge] (hope this is in all browsers)

**Comment by JamesWong1999** [comment]
https://codesandbox.io/s/hopeful-currying-o3dhx?file=/src/App.js

**Comment by uidev547** [comment]
@bluebill1049 Working as expected. Thanks a lot for the quick turnaround and cool library

**Comment by bluebill1049** [comment]
No worries 😊 thanks for reporting issue with details. Really make my life easier in terms of debug and find out the root cause.
