### ISSUE TITLE
Input lose the cursor position when use 'watch' and 'setValue(name,value,true)'

### ISSUE THREAD

**Issue by Chastrlove** [react-hook-form/react-hook-form#531]
**Describe the bug**
Input lose the cursor position when I use the api  'watch' and 'setValue(name,value,true)'

**To Reproduce**
1. input 1231
2. cursor to 12|31  to input 1
3. the result 12131|

**Codesandbox link**
https://codesandbox.io/s/antd-reproduction-template-tnljn  Antd Input
https://codesandbox.io/s/jovial-bash-i6wc7 native input

**Expected behavior**
 the cursor still focuses on the original position

**Desktop (please complete the following information):**
 - OS: Mac Catalina
 - Browser: chrome lastest

**Additional context**
when i use 'setValue(name,value,false)' ,the cursor works normally, but it cant trigger field validation 🤷🏿‍♂️

**Comment by bluebill1049** [comment]
Hey @Chastrlove looks like both examples work. I think i may miss the steps on how to reproduce?

**Comment by bluebill1049** [comment]
thanks @Chastrlove I will take a look this one soon :)

**Comment by Chastrlove** [comment]
![Kapture 2019-11-19 at 10 51 45](https://user-images.githubusercontent.com/17813559/69112221-b67c0f80-0aba-11ea-94c7-309f0868cb77.gif)

**Comment by bluebill1049** [comment]
hey @Chastrlove the issue should have been resolved. you can try the codesandbox in that PR.

**Comment by Chastrlove** [comment]
it works :) ,but i am confuse with reason. it looks like exchanging the render time，then it work？

**Comment by bluebill1049** [comment]
@Chastrlove it's because when you set the third argument to `true`, it will trigger validation and it is async, hence it breaks the react rendering. so I am fixed to render naturally as required (when you are watching), and trigger another extra re-render, if there is the need for re-render an error or resolve the error.

**Comment by CreativeSight** [comment]
Hey guys, got same issue on Safari MacOS Catalina, in my project as in your codesandbox examples
