### ISSUE TITLE
Nested Field Array Items are not correctly typed

### ISSUE THREAD

**Issue by KiwiKilian** [react-hook-form/react-hook-form#5318]
**Describe the bug**
The items in `fields` from a **nested** `useFieldArray` are not properly typed when using Typescript and supplied with a type for FieldValues. The **nested** field array items are only typed as containing the `id` nothing else: `Record<"id", string>`

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-nested-types-5mgd4?file=/src/nestedFieldArray.tsx
2. View the red markings at line 32 and line 40 in file `nestedFieldArray.tsx`

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-nested-types-5mgd4?file=/src/nestedFieldArray.tsx

**Expected behavior**
The nested field items should be properly typed and be aware of the fields `field1` and `field2`.

**Screenshots**
<img width="1036" alt="Bildschirmfoto 2021-05-24 um 19 28 40" src="https://user-images.githubusercontent.com/18724559/119385356-4dd0ad00-bcc6-11eb-86d2-f1f90c7ec126.png">

**Additional context**
The typing for `register` works properly.

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report.

This is a limitation for TS for now. hopefully, this PR gets released and will improve above: https://github.com/microsoft/TypeScript/pull/43361

solution for now: 

<img width="916" alt="Screen Shot 2021-05-25 at 9 30 14 am" src="https://user-images.githubusercontent.com/10513364/119418655-d0e01a80-bd3b-11eb-9dc9-47ebbe7a4822.png">

https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-nested-types-ne908

**Comment by KiwiKilian** [comment]
@bluebill1049 thank you as always for the really fast response! Actually the problem in my application was, that the `nestedArray` was typed as optional on the FormFieldValues. I guess that's intentional too? It's weird because now it also works with `as const`.

**Comment by bluebill1049** [comment]
No worries. We will need as const for any dynamic string for the type check.

**Comment by LoicHa** [comment]
Oh god thank you so much @bluebill1049  awesome , i had the same issue with useFormContext and nested form array definition typing
