### ISSUE TITLE
useFieldArray not working when append/insert called multiple times quickly

### ISSUE THREAD

**Issue by harshzalavadiya** [react-hook-form/react-hook-form#5323]
**Describe the bug**
When using fieldArray in react-hook-form@7 if append is called multiple times it does not work as expected, I don't know weather this was designed intentionally since it works when timeout is added before calling

use case: In our application I have to create multiple dropdowns based on parsed excel sheet to map fields, so I can't provide value as defaultValues, I have to create N fields at runtime all at once

**To Reproduce**
see `useState` method of codesandbox

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-05z9z?file=/src/index.js

**Expected behavior**
It should create multiple fields

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Linux
- Browser [e.g. chrome, safari] chrome and firefox
- Version [e.g. 22] chrome@90 and firefox@88

**Smartphone (please complete the following information):**

**Additional context**
If you try it with `insert()` from `useFieldArray` internally it creates fields but `fields` object from `useFieldArray` only shows 1 item as above

**Comment by bluebill1049** [comment]
<img width="992" alt="Screen Shot 2021-05-25 at 7 25 20 pm" src="https://user-images.githubusercontent.com/10513364/119473884-f3e7ea00-bd8e-11eb-98a6-905daaca2ed8.png">

if you need to append multiple rows, use array syntax.

**Comment by bluebill1049** [comment]
![Uploading Screen Shot 2021-05-25 at 7.26.02 pm.png…]()

**Comment by harshzalavadiya** [comment]
@bluebill1049 thanks for quick response,

Is there any way to add multiple fields at once after form is initialized, for example if I want to append 5 fields at once into array, or adding timeout is only way?, since this fields are added after form is initialized and size is unknown
