### ISSUE TITLE
Struggle behavior of registering in defaultValues of useForm 

### ISSUE THREAD

**Issue by daklin2** [react-hook-form/react-hook-form#5334]
Hi there, find some strange behavior of RHF after update to the 7.6.*.
Working with library _Bignumber.js_ and there bug with default registered fields. 

If we pass to defaultValues of useForm value which is instance of BigNumber it's convert it to simply object(which seems like prototype of BigNumber). 
But if we will somewhere in code register this field with BigNumber value by ourself it will apply BigNumber type to value again.

As i understand, it shouldn't change type by default. 
And as i checked, before 7.6.* it's worked as expected without converting type.  

**Steps to reproduce:**

1. Go to sandbox(which below)
2. Click on the button
3. See in console object with 2 property, one is unregisterSum(it's registered by default with RHF), second is registeredSum(which registered lately with "register" code).
4. So there is problem, one which only registered by default has type of **"Object"**, and other which registered with "register" has right type **"BigNumber"** 

**Link to sandbox:** [Sandbox](https://codesandbox.io/s/rhfv7-type-bug-dmdvn)
<br><br><br>

**System**
- OS: Ubuntu
- Browser: Chrome (89.0.4389.114)

**Comment by bluebill1049** [comment]
we don't support custom objects (Bignumber.js) as default values, you work around this issue by supplying them inline.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/rhfv7-type-bug-forked-jr0bi

another work around below:

```tsx
import React from "react";
import { FormProvider, useForm } from "react-hook-form";
import BigNumber from "bignumber.js";
import "./styles.css";

type FormValues = {
  registeredSum: BigNumber;
  unregisteredSum: BigNumber;
  manualSetSum: null | BigNumber;
};

const App = () => {
  const formMethods = useForm<FormValues>({
    defaultValues: {
      unregisteredSum: new BigNumber("12").toString(),
      registeredSum: new BigNumber("12").toString()
    }
  });
  const onSubmit = (data: FormValues) => console.log(data);

  formMethods.register("registeredSum");
  return (
    <div className={"container"}>
      <FormProvider {...formMethods}>
        <button type={"button"} onClick={formMethods.handleSubmit(onSubmit)}>
          Click for Console Input!
        </button>
      </FormProvider>
    </div>
  );
};

export default App;
```
