### ISSUE TITLE
Implimentation of validation in form created with more than two components

### ISSUE THREAD

**Issue by sagar10k** [react-hook-form/react-hook-form#534]
hello there i have a problem case where there are two components one parent and one child so in parent component i have     <form onSubmit={ handleSubmit(any_func) }> but the input fields of this form is called with child component where i have registered the input fields to hooks and also used error method if field is left empty so my problem is when i click on submit button of form the handleSubmit is invoked but the error message for empty field is not shown so is there a way i can approch this problem. i have attack txt file about how my code looks so please take a look
[Issue.txt](https://github.com/react-hook-form/react-hook-form/files/3862171/Issue.txt)

**Comment by bluebill1049** [comment]
please prepare a codesandbox with your problem. it's hard to read your code without proper format and to reproduce the issue as well.

**Comment by bluebill1049** [comment]
you should pass the `register` down as `props`
```
function Form(props){
  const[obj, setObj]=useState(props.form_data)
  const { handleSubmit, register } = useForm()

  return (
    <form onSubmit={ handleSubmit(handleUpdate) }>
      <Child txtEl={obj} register={register} />
      <input  type="submit"/>
    </form>
  )
}
```

**Comment by sagar10k** [comment]
> you should pass the `register` down as `props`
> 
> ```
> function Form(props){
>   const[obj, setObj]=useState(props.form_data)
>   const { handleSubmit, register } = useForm()
> 
>   return (
>     <form onSubmit={ handleSubmit(handleUpdate) }>
>       <Child txtEl={obj} register={register} />
>       <input  type="submit"/>
>     </form>
>   )
> }
> ```

**Comment by sagar10k** [comment]
> you should pass the `register` down as `props`
> 
> ```
> function Form(props){
>   const[obj, setObj]=useState(props.form_data)
>   const { handleSubmit, register } = useForm()
> 
>   return (
>     <form onSubmit={ handleSubmit(handleUpdate) }>
>       <Child txtEl={obj} register={register} />
>       <input  type="submit"/>
>     </form>
>   )
> }
> ```

it is working now thanks buddy great help....

**Comment by bluebill1049** [comment]
my pleasure :) 👍 next time please try to come up with a codesandbox, it will help me to help you easier and better :) you can join here to get help from the community as well: https://spectrum.chat/react-hook-form

**Comment by bluebill1049** [comment]
leave a star if you find the lib useful too :)

**Comment by sagar10k** [comment]
Sure things man its really good lib and i want to explore a lot so kudos for your work

**Comment by bluebill1049** [comment]
thanks @sagar10k make sure you learn this as well: https://react-hook-form.com/api#FormContext
you don't have to pass down prop all the time, and if your child input is quite deep. you can use FormContext, have a play with the codesandbox. you will get the idea.

**Comment by sagar10k** [comment]
yeah i will take a look at formContext...and currently my task i quite big and there are lot of components i have used which are dependent on each other so i was confuse how to use sandbox and thats why i tried to create dummy sample in txt file to explain my problem but next time i will try sandbox thanks

**Comment by bluebill1049** [comment]
Awesome! 👍🏻
