### ISSUE TITLE
Library throws an error when trying to fill a file input with the default data

### ISSUE THREAD

**Issue by jog1t** [react-hook-form/react-hook-form#5344]
**Describe the bug**
The library causes an error when filling out a file input with the default data.

> Uncaught TypeError: Failed to set an indexed property on 'FileList': Indexed property setter is not supported

**To Reproduce**

1. Go to the following CodeSandbox
2. Pick an image
3. Click Submit (to save form state)
4. Click Toggle visibility (to toggle unmount)
5. Click Toggle visibility (to toggle mount)
4. See an error

**Codesandbox link (Required)**
https://codesandbox.io/s/mystifying-galileo-epbq7

**Expected behavior**
This error does not exist in version 6 of this library. You can test it by switching the version of the `react-hook-form` library in the sandbox.
The library should fill out the input file with the default data without any problem.

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome
- Version 90

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/119637035-9324e400-be58-11eb-8590-3422cbe80835.mov


What are the steps to produce the error?

**Comment by jog1t** [comment]
@bluebill1049 thanks for your reply. 

Steps to reproduce the behavior (must be executed in that order):
1. Go to https://codesandbox.io/s/mystifying-galileo-epbq7
2. Pick an image
3. Click Submit (to save form state)
4. Click Toggle visibility (to toggle unmount)
5. Click Toggle visibility (to toggle mount)
6. See an error

**Comment by jog1t** [comment]
Thanks @bluebill1049, for a quick fix!

**Comment by bluebill1049** [comment]
Thanks for the quick response and detailed issued.
