### ISSUE TITLE
input focus was delayed when submit

### ISSUE THREAD

**Issue by dhieunguyen** [react-hook-form/react-hook-form#5351]
**Describe the bug**
Can you guys help me in this case. When i submitted my form, input was focus but it delayed a little time. Please watch the video. I'm using v7. Thanks for reading

Uploading 3796217609563621237.mp4…

**Comment by dhieunguyen** [comment]
https://user-images.githubusercontent.com/64343185/119765478-89918f80-bedd-11eb-8a95-3002b6d769ae.mp4

**Comment by bluebill1049** [comment]
Do you have any Async validation?
