### ISSUE TITLE
initial state inconsistant: isValid no longer works with defaultValue

### ISSUE THREAD

**Issue by jbdemonte** [react-hook-form/react-hook-form#5366]
**Describe the bug**
**isValid** is set to false despite **defaultValue** is set and valid

**To Reproduce**

1. Go to [codesandbox](https://codesandbox.io/s/upbeat-morse-u7fmq?file=/src/App.js)
2. Look at the input state, **isValid** equals **false** while the requirement is valid
3. update it or just focus and blur it 
4. **isValid** became **true**

**Codesandbox link (Required)**
[codesandbox](https://codesandbox.io/s/upbeat-morse-u7fmq?file=/src/App)

**Expected behavior**
Should be true

**Additional context**
The last working version was the `7.0.4`. Since the `7.0.5`, it no longer works as expected.

**Comment by jbdemonte** [comment]
😱 this is the fastest `issue => label => fix => release` I ever see on a huge project!

thanks a lot

**Comment by bluebill1049** [comment]
no worries @jbdemonte ❤️ try to produce something great for all of us.
