### ISSUE TITLE
isDirty is true for objects inside fieldArray elements before changes

### ISSUE THREAD

**Issue by noisyscanner** [react-hook-form/react-hook-form#5367]
**Describe the bug**
When using `useFieldArray` with an array of objects, containing nested objects, `dirtyFields` will be `true` for the nested object as soon as it is added, **before** any of its children have been changed.

**To Reproduce**

1. Go to the below Codesandbox
2. No fields are currently dirty (as shown in the screenshot below)
3. Click 'Add User'
4. Dirty fields is now:
```js
[
  {
    "details": true // Expected: false
  }
]
```
5. Fill out either (or both) of the inputs
6. Dirty fields is now (if both filled out):
```js
[
  {
    "details": {
      "first": true,
      "last": true
    }
  }
]
```

**Codesandbox link (Required)**
https://codesandbox.io/s/infallible-wave-kg5z4?file=/src/App.js

V7.6.7

**Expected behavior**
I would expect either of the following:
- `details` to be `false` - as I have not modified any of its child fields yet
- `details` to be `{ first: false, last: false }` - as it should know about the child fields already as they have been `register`ed

**Screenshots**
![image](https://user-images.githubusercontent.com/627654/119860111-ea38c080-bf0d-11eb-9b69-cf7c68ff1483.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 90

**Additional context**
N/A

**Comment by bluebill1049** [comment]
This is expected behavior, we are doing a deep equal with `defualtValues`, once appending is happening, the formvalues will be updated, because by default HTML input will return an empty string.

**Comment by noisyscanner** [comment]
Cheers - is there any way to achieve what we are after? Knowing if an appended object is dirty?

**Comment by bluebill1049** [comment]
It would be difficult, that's why some of the form libraries skip `dirtyFields` for field array completely.

**Comment by bluebill1049** [comment]
> Is it worth sticking that in the docs with a brief explanation? Maybe it will help someone else?

definitely a good idea. I will get that updated.

**Comment by bluebill1049** [comment]
updated: https://github.com/react-hook-form/documentation/commit/bbd8afb5805bb5f44adeaa2decdb39b16463b494
