### ISSUE TITLE
Support for file input

### ISSUE THREAD

**Issue by jgb-solutions** [react-hook-form/react-hook-form#537]
Do you guys already have, or do have plans to support file inputs? I'm working on a form that uploads one or more files and integrating them with this package is a pain in the neck. Adding support for custom file input would be great. Anyway that's just a suggestion.

**Comment by bluebill1049** [comment]
Pretty sure we do. I would recommend you join our spectrum channel for general questions. 🤟🏻

**Comment by jgb-solutions** [comment]
I'm joining now. thanks

**Comment by bluebill1049** [comment]
sounds good! thanks :) @jgb-solutions
