### ISSUE TITLE
initial `isValid` is false when having registered and controlled components

### ISSUE THREAD

**Issue by jbdemonte** [react-hook-form/react-hook-form#5378]
Following the #5366

**Describe the bug**
Initial state has some strange behaviour when dealing with both registered and controlled component

**To Reproduce**

1. Go to [codesandbox](https://codesandbox.io/s/modest-wave-2hwho?file=/src/App.js)
2. The `isValid` is `false` while it should be `true`

If you remove any of the component and reload, the initial `isValid` come `true`, it seems to become false after a re-render

**Comment by bluebill1049** [comment]
This is due to `ref` is not assigned, I am looking for a solution to overcome this.

**Comment by bluebill1049** [comment]
This is fixed: https://codesandbox.io/s/quizzical-tesla-mpx87 will be released the patch in the following days.
