### ISSUE TITLE
Not converted to Number type

### ISSUE THREAD

**Issue by tanmen** [react-hook-form/react-hook-form#5379]
**Describe the bug**
If you do not use defaultValue and manage the value by custom, valueAsNumber does not work.

**To Reproduce**
Browse codesandbox.

**Codesandbox link (Required)**
https://codesandbox.io/s/eager-bush-66exf?file=/src/App.tsx

**Expected behavior**
To be converted to Number

**Screenshots**
N/A

**Desktop (please complete the following information):**
Version: 7.6.9

**Smartphone (please complete the following information):**
N/A

**Additional context**
I also tried 7.6.3 but it didn't happen in 7.6.3.

**Comment by bluebill1049** [comment]
> When defaultValue is not defined, the first render of watch will return undefined because it is called before register, but you can set the defaultValue as the second argument or provide defaultValues via useForm to avoid this behaviour.

please provide a `defaultValues` or `defaultValue`
![Uploading Screen Shot 2021-05-28 at 5.50.51 pm.png…]()
.

**Comment by tanmen** [comment]
Is this the behavior of WATCH?
I get NaN even if I do submit.

**Comment by bluebill1049** [comment]
> Is this the behavior of WATCH?

Yes.

> I get NaN even if I do submit.

not with submit, I am looking into it.

**Comment by bluebill1049** [comment]
Thank you @tanmen 🙏
