### ISSUE TITLE
Field marked as dirty if it was just touched

### ISSUE THREAD

**Issue by oschade** [react-hook-form/react-hook-form#5387]
**Describe the bug**
 A field is marked as dirty if the content has just touched not changed.

**To Reproduce**
I use the sandbox from the documentation example:

https://codesandbox.io/s/react-hook-form-get-started-forked-zpptw?file=/src/index.js

If you place the cursor in a field and leave it (blur) without any changes, the field name appears in touchedFields and dirtyFields (see console).

**Expected behavior**
The field should appear in the touchedFields but not in the dirtyFields.

**Comment by bluebill1049** [comment]
<img width="962" alt="Screen Shot 2021-05-29 at 9 13 08 am" src="https://user-images.githubusercontent.com/10513364/120049687-17948400-c05e-11eb-91c4-46b280a3149f.png">

missing defaultValues.
