### ISSUE TITLE
Typescript ERROR in /node_modules/react-hook-form/dist/types/utils.d.ts

### ISSUE THREAD

**Issue by amermemic** [react-hook-form/react-hook-form#5388]
On runtime it renders this error in the console: 
```
ERROR in /.../node_modules/react-hook-form/dist/types/utils.d.ts
[tsl] ERROR in /.../node_modules/react-hook-form/dist/types/utils.d.ts(38,100)
      TS1005: ',' expected.
```

and also for the characters:  `(` ,
                                              `;` , 
                                             `?` 

and the very last error message: 
```
ERROR in .../node_modules/react-hook-form/dist/types/utils.d.ts
[tsl] ERROR in .../node_modules/react-hook-form/dist/types/utils.d.ts(45,1)
      TS1160: Unterminated template literal.
```

All i did was `import { useForm, SubmitHandler } from "react-hook-form";`
and then used it like in the getting started guide..

It still compiles the app though and everything works fine. But that typescript error stops my react app from recompiling after a change, so its annoying to reload manually after every change.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848
