### ISSUE TITLE
`name` with nested field notation consistency

### ISSUE THREAD

**Issue by MunifTanjim** [react-hook-form/react-hook-form#541]
**Is your feature request related to a problem? Please describe.**

If `name` prop is `key.abc`, it sets `{ key: { abc: '' } }`.
If `name` prop is `key.123`, it creates a large array with `123` empty elements and sets the value on `123` index.

So if the nested field's key is a huge number, it ends up creating a huge array.

**Describe the solution you'd like**

Consistent behavior:

`key.abc` will set `{ key: { 123: '' } }`

`key.123` will set `{ key: { 123: '' } }`

and, for creating array:

`key[123]` notation should be used instead.

**Comment by bluebill1049** [comment]
@MunifTanjim maybe we can avoid start with a number? I am happy to drop a note about this on the website.

**Comment by MunifTanjim** [comment]
I'm using this to mark items as selected. Each item has a checkbox, selecting it sets `selected.ITEM_ID` to `true`. But the `ITEM_ID`s are very large integers. So, I don't feel comfortable with `react-hook-form` creating a large array for that.

The workaround I'm using is by adding a minus in front of the `ITEM_ID`. So setting `selected.-999` sets the key (`-999`) to the object (`selected`). And later I have to remove that minus for getting the selected `ITEM_ID`s.

> maybe we can avoid start with a number

As you can see, in this case, to avoid start with a number is not really possible (without some crazy workaround like I described above).

Anyway thanks for creating this wonderful library :tada: :smile:

**Comment by bluebill1049** [comment]
thank you @MunifTanjim very much for your kind words! my pleasure to give back to the community :) dame I will give another try on the input name, last time almost killed me with the regex. Hopefully I can get it to work, otherwise, we may have to leave with the hack for now.

**Comment by bluebill1049** [comment]
I tried again, it's too tricky to get it right and it make thing much easier with just detect number as an array... let's keep as what we got, for now, maybe someone can help on this or one day I can
