### ISSUE TITLE
shouldUnregister stopped working for versions >= 7.6

### ISSUE THREAD

**Issue by mbretter** [react-hook-form/react-hook-form#5416]
**Describe the bug**
shouldUnregister at useForm level stopped working for versions >= 7.6

**To Reproduce**

1. open the sandbox console
2. Click on "console log form state"
3. the formdata should contain the field "name" only without the defaultData.
4. reverting rhf back to the latest 7.5.x brings back the desired behavior

**Codesandbox link (Required)**
https://codesandbox.io/s/rhf-basic-nknkm?file=/src/App.js

**Expected behavior**
The formdata should contain the field "name" only

This seems to be a problem with this change introduced into 7.6:
"From version 7.6.0 onwards, any missing registered inputs from defaultValues will get automatically registered. "

**Comment by bluebill1049** [comment]
please don't include those values inside `defaultValues`, as they will get registered automatically from v7.6.

**Comment by mbretter** [comment]
those values comes from an async api, filtering them out, would be an additional effort.
the main reason, why I have chosen rhf in favour to other form handlers, was because rhf had the option to submit only the values with corresponding input fields.
until 7.5.latest everything was fine, this seems to be a big breaking change.

**Comment by bluebill1049** [comment]
Honestly, I have no intention to break anyone's application. the whole reason to introduce such **feature** was to make everyone's life easier in terms of register inputs with a custom register, I wish I could make everyone happy about some of the decisions and yet I am the one who listens and receive feedback from the community. For now, you can keep the version at 7.5 or doing the filtering as I have suggested above, and until I figure something which will make your use case easy as well.

**Comment by mbretter** [comment]
the docs are misleading then, because the doc to shouldUnregister says:
"By setting shouldUnregister to true at useForm level, defaultValues will not be merged against submission result."
but this is not true anymore (starting from 7.6)
Maybe you can disable this self-registering feature, if shouldUnregister is set to true?

btw, I really appreciate your work, there are not so many opensource projects, which are maintained as perfectly as rhf ;)

**Comment by bluebill1049** [comment]
> Maybe you can disable this self-registering feature, if shouldUnregister is set to true?

I think this can be a valid change, as we can keep shouldUnregister: true as close to native input behavior as possible, and making `shouldUnregister: false` behavior to make most dev happy.
