### ISSUE TITLE
Trigger specific validator

### ISSUE THREAD

**Issue by nimabrownlee** [react-hook-form/react-hook-form#5417]
**Is your feature request related to a problem? Please describe.**

So I have multiple validations on an input. But I only want to trigger a specific one for different circumstances.  

**Describe the solution you'd like**

`trigger('name', ['required', 'pattern'])`

This would only trigger the required and pattern validation. So you can pass a string or an array as a secondary param.

**Describe alternatives you've considered**

No alternatives. This is not possible to achieve today.

**Comment by bluebill1049** [comment]
thanks, moving into feature flags board.

**Comment by nimabrownlee** [comment]
@bluebill1049 Wow that was fast. Thanks Bill!

Unrelated question: I used the Form component here: https://github.com/react-hook-form/react-hook-form/blob/master/examples/V7/typescript/UseFormMethods.tsx
The problem is that when I try to add `defaultValues` like this:

```
  const methods = useForm<TFormValues>({
    defaultValues: {
      name: 'hi'
    }
  })
```

Typescript complains and says that I have to implement all members.
Its because of this part: `const Form = <TFormValues extends Record<string, any> = Record<string, any>>({`
But I don't know enough TS to know what I have to change.

**Comment by bluebill1049** [comment]
> TFormValues

you want to ask this question in Github discussion and supply with a codesandbox?

**Comment by nimabrownlee** [comment]
@bluebill1049 Absolutely!
