### ISSUE TITLE
SetValue is not fully typesafe

### ISSUE THREAD

**Issue by girards** [react-hook-form/react-hook-form#542]
When using the `setValue` with the `useForm<T>` we realised that the first parameter of `setValue()` is not typesafe. it has been change to have the following typing : 

``` ts
type BaseFieldName<FormValues extends FieldValues> = Extract<
  keyof FormValues,
  string
>;

export type FieldName<FormValues extends FieldValues> =
  | BaseFieldName<FormValues>
  | string;
```

the `| string` makes the following code not break where it actually should

```ts
import { useEffect } from "react";
import useForm from "react-hook-form";
import { FieldName } from "react-hook-form/dist/types";

interface InviteMemberFormProps {
  firstname: string;
  lastname: string;
  email: string;
}

export const useInviteMemberForm = () => {
  const { register, handleSubmit, errors, setValue } = useForm<InviteMemberFormProps>();
  setValue("foo", "bar");

  return {
    errors
 }
};

```
_Here, `foo` is not a property of `InviteMemberFormProps` therefore I should not be able to use it as a `setValue()` parameter_

By removing  the `| string` the following error pops up

![image](https://user-images.githubusercontent.com/6340743/69264198-195acd00-0bc7-11ea-9623-9f05bf99e806.png)

Unfortunately, just removing `| string` breaks the build job.

Could there be a way of make the `SetValue()` typesafe ?

**Comment by bluebill1049** [comment]
thanks, @girards for report this issue. the reason why there is a type for `string`. it's hard to predict type for `object | array` inputs. Feel free to send a PR or provide your suggestion to solve this problem tho, which I do want to address this.

**Comment by bluebill1049** [comment]
going to close this issue for now until we or someone else figure out a better solution for this.
