### ISSUE TITLE
setValue not working for arrays with controller

### ISSUE THREAD

**Issue by mrlubos** [react-hook-form/react-hook-form#5423]
**Describe the bug**
I wonder if this bug is related to https://github.com/react-hook-form/react-hook-form/issues/5232 as the issues I usually see are related to non-primitive values, namely arrays.

**To Reproduce**
1. Use controller interface instead of register to track fields in your form
2. Add a manually tracked field via `defaultValues`
3. Add a callback modifying the manual field and call it (in my example by pressing the "Remove" button)
4. Press the "submit" button

**Codesandbox link (Required)**
https://codesandbox.io/s/dark-voice-glnie?file=/src/App.tsx

**Expected behavior**
The submitted values are

```json
{
  "array": ["a"],
  "firstName": "alll"
}
```

**Actual behavior**
The submitted values are

```json
{
  "array": ["a", "b"],
  "firstName": "alll"
}
```

**Comment by mrlubos** [comment]
@bluebill1049 it seems if I add this piece of code, it works

```tsx
useEffect(() => {
  register('array')
}, []);
```

but you've told me in https://github.com/react-hook-form/react-hook-form/issues/5232 calling `register()` is optional and perhaps it's just a coincidence it works after adding this code

**Comment by bluebill1049** [comment]
```
useForm({
  defaultValues: {
    test: [1,2]
  }
})
```

The above `defaultValues` will basically do the following `register`.

```
register('test.0')
register('test.1')
```

There is no way for hook form to detect if this is single input.

So when you invoke `setValue('test', [3])`, this is basically only updating the first input.

```
register('test.0')
setValue('test,0', 3])
```

I will update the doc to include a better description on auto `register` from `defaultValues`.

**Comment by mrlubos** [comment]
> ### Alternative solutions
> * `register` the input so hook form can identity it's a single input

Hey @bluebill1049, thanks for the reply. Can you please clarify this point? How should I call the `register()` method to correctly detect my array of strings?

**Comment by bluebill1049** [comment]
I would register that `key` as input, so hook form knows it's a group input instead of individual inputs.

```
register('array') // you can do that in useEffect 

setValue('array', ['1', '2', '3']
```

**Comment by mrlubos** [comment]
> I would register that `key` as input, so hook form knows it's a group input instead of individual inputs.
> 
> ```
> register('array') // you can do that in useEffect 
> 
> setValue('array', ['1', '2', '3']
> ```

Thanks @bluebill1049, I'll have a look. Doing this triggers the other bug I reported in #5232 but I have not been able to reproduce it in CodeSandbox so far. Will keep you posted if I succeed

**Comment by damianobarbati** [comment]
@mrlubos how are you dealing with arrays now?

I'm not getting it. I have an array field in my form:
```js
const { register, handleSubmit, setValue, formState, control, reset } = useForm({
        mode: 'onBlur',
        reValidateMode: 'onChange',
        defaultValues: {
            status: 'enabled',
            disciplines: [],
            subscription_exp: !id && dayjs().endOf('day').add(1, 'month').format('YYYY-MM-DD'),
            entrances: 999,
            entrances_per_week: 999,
        },
    });
```

An ajax starts and fetch the data to prefill form:
```js
        for (const [key, value] of Object.entries(data)) {
            setValue(key, value, { shouldValidate: true });
        }

        reset(dataFixed);
```

`disciplines` is a react-select wrapped into `Controller` but field.value is always the default value of empty array and not the data I just set with setValue (or reset, I tried all I found).

**Comment by damianobarbati** [comment]
EDIT: ok this sucks, but I think it's a bug with renders (some data is accessed when re-rendering?).

I had to do this (see `key`):
```js
<DisciplinesSelect key={Date.now()} label={'Disciplines'} control={control} />
```

**Comment by mrlubos** [comment]
> @mrlubos how are you dealing with arrays now?

Hey @damianobarbati, do you still need a response?

**Comment by damianobarbati** [comment]
@mrlubos yes, I'd appreciate :) 

Are you still using:
```js
useEffect(() => {
  register('array')
}, []);
```

where you have an array field?

**Comment by mrlubos** [comment]
> Are you still using:
> 
> ```js
> useEffect(() => {
>   register('array')
> }, []);
> ```
> 
> where you have an array field?

@damianobarbati As of version `7.8.8`, I define the form like this.

```tsx
useForm({
  defaultValues: {
    array: [],
  },
  shouldUnregister: true,
});
```

And in the same component I also add this hook.

```tsx
useEffect(() => {
  register('array');
}, [register]);
```

Hopefully this helps!

**Comment by damianobarbati** [comment]
@mrlubos thanks, I tried both on 7.8.8 and the 7.9.0 but I can't manage to have the array properly working, only `defaultValues` is always passed from `Controller` to `react-select`.

I'm sticking to this workaround of `key={Date.now()}` thus always re-rendering the component wrapping the `react-select` into `<Controller />`. 

Thanks!

**Comment by mrlubos** [comment]
> @mrlubos thanks, I tried both on 7.8.8 and the 7.9.0 but I can't manage to have the array properly working, only `defaultValues` is always passed from `Controller` to `react-select`.
> 
> I'm sticking to this workaround of `key={Date.now()}` thus always re-rendering the component wrapping the `react-select` into `<Controller />`.
> 
> Thanks!

If you share a CodeSandbox we might be able to help you @damianobarbati

**Comment by damianobarbati** [comment]
@mrlubos I tried to trim it down to this here: https://codesandbox.io/s/react-hook-form-react-select-u36uv

It's actually not behaving like the real app where I see always an empty array but I see another weird behaviour: removing all items from the select leaves 1 item in the watched values. 🤔

**Comment by mrlubos** [comment]
> @mrlubos I trimmed it down to this repro here: https://codesandbox.io/s/react-hook-form-react-select-u36uv
> 
> It's actually not behaving like the real app where I see always an empty array but I see another weird behaviour.
> Removing all items from the select... 🤔
> 
> * leaves 1 item in the watched values
> * is undefined in submit values

@damianobarbati Are you able to upgrade `react-select` to version `4.0.0` or newer? Doing so fixes the issues you mention above. Can you verify if that would also resolve the other issues you're seeing?

**Comment by damianobarbati** [comment]
@mrlubos I see it working properly with the latest `react-select`.
I'll ping if I manage to reproduce the real app behaviour, thank you!

**Comment by bluebill1049** [comment]
I think we have resolved this limitation with the latest.
