### ISSUE TITLE
React hook form doesn't work with react-native-testing-library

### ISSUE THREAD

**Issue by Sven2219** [react-hook-form/react-hook-form#5438]
**Describe the bug**

When I try to set the value of a TextInput using react-native-testing-library, I got "TypeError: j is not a function". This only happens in combination with the react-hook-form.

**Expected behavior**
The field should be filled.

**To Reproduce**

Controller
![Screenshot 2021-06-01 at 15 15 19](https://user-images.githubusercontent.com/62476842/120332409-01e9bd80-c2ef-11eb-99c0-a425e36694fe.png)

Test
![Screenshot 2021-06-01 at 15 38 53](https://user-images.githubusercontent.com/62476842/120332955-85a3aa00-c2ef-11eb-9ac9-55943e44f5b9.png)

Error
![Screenshot 2021-06-01 at 15 21 59](https://user-images.githubusercontent.com/62476842/120332563-26de3080-c2ef-11eb-95b6-418c235f15c8.png)

**Describe alternatives you've considered**
I tried this article https://www.albertgao.xyz/2020/07/19/how-to-test-react-hook-form-with-react-native-testing-library/
Also, I found on some website this `fireEvent.changeText (emailField,'onChangeText', 'Fill input');`, but it didn't work.

**Versions**
![Screenshot 2021-06-01 at 15 42 26](https://user-images.githubusercontent.com/62476842/120333481-0498e280-c2f0-11eb-8626-4c527d93a7f1.png)

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.native.test.tsx

**Comment by kayzenkayzen** [comment]
@Sven2219 remember to add this to your "setupFilesAfterEnv" setup file:

global.window = {};
global.window = global;

**Comment by leoparis89** [comment]
> @Sven2219 remember to add this to your "setupFilesAfterEnv" setup file:
> 
> global.window = {};
> global.window = global;

Thanks this worked for me after hours of debugging.
This has to be added in docs asap because react-hook-forms it broken out of the box with react-native-testing-library...

I don't see why this issue is closed.
