### ISSUE TITLE
reset + defaultChecked doesn't set the values for checkbox group

### ISSUE THREAD

**Issue by PraveenPeri** [react-hook-form/react-hook-form#5439]
**Describe the bug**
Material's checkbox group doesn't have the initial state correctly set through defaultChecked when the initial values are coming from reset(). I don't think this problem is specific to Material-UI though.

**To Reproduce**

1. Create a checkbox group using Material-UI
2. Use reset to provide the initial checked states of the boxes
3. Use defaultChecked to set the initial checked state
4. See that the checked state is not correctly set

**Codesandbox link (Required)**
https://codesandbox.io/s/patient-sunset-pt5jz

**Expected behavior**
Should be able to set the initial checkbox state using the values from reset. (These values are coming from an API in our application).

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Edge
- Version: 90.0.818.66

**Comment by bluebill1049** [comment]
<img width="1156" alt="Screen Shot 2021-06-02 at 8 29 23 am" src="https://user-images.githubusercontent.com/10513364/120397962-a403b700-c37c-11eb-83bb-8e5fe6a76485.png">

**Comment by PraveenPeri** [comment]
Could you try it now?
