### ISSUE TITLE
Cannot use special characters as controller name

### ISSUE THREAD

**Issue by MerleBaake** [react-hook-form/react-hook-form#5441]
**Describe the bug**
When using the Controller to use React Hook Forms with Material UI, I cannot use special characters as the Controller name, like `|` (pipe)

**Codesandbox link (Required)**

https://codesandbox.io/s/vigorous-maxwell-nc30n?file=/src/App.tsx

**Expected behavior**
I would like to use any name as the Controller name to control Checkboxes by a unique name.

**Desktop (please complete the following information):**

- OS: macOS Version 11.1
- Browser: Firefox 89.0b15

**Comment by JGibel** [comment]
I looked in the code. I think what's going on is when the Controller registers it, it replaces |,{,'," when storing the ref, but not on any lookups after the fact.

I'm not sure why it's replacing pipe (might just be a typo in the regex), but the others make sense.

Are there other special characters not working or just pipe?

Relevant replace logic: https://github.com/react-hook-form/react-hook-form/blob/master/src/utils/stringToPath.ts

**Comment by bluebill1049** [comment]
we don't support special characters for names.

**Comment by mediafreakch** [comment]
@bluebill1049 I get why `.` and `[]` isn't supported, but why not the `|`? This seems random. Could you elaborate?
Pipes would be handy for react-admin in conjunction with [api filter operators](https://github.com/marmelab/react-admin/issues/7618#issue-1223033124)
