### ISSUE TITLE
Add "pre-scroll to error" hook

### ISSUE THREAD

**Issue by dudiharush** [react-hook-form/react-hook-form#5453]
**Is your feature request related to a problem? Please describe.**
The Problem is that some part of my form fields are inside an accordion component, so they are not visible when i hit the "submit" button, so i need to first open the accordion before i can scroll, and I can't find a hook before the scroll, to open the accordion with, so i solved it with some custom code that also needed scrolling to the error, that is already implemented by RHF. 

**Describe the solution you'd like**
I would like to have a "pre scroll" hook, so I can open the accordion before the scroll to error field happens.

**Describe alternatives you've considered**
I solved it by writing a custom onInvalid function for handleSubmit. @bluebill1049  Do you have a better way to solve it?
[csb](https://codesandbox.io/s/controlled-field-array-forked-yxjdl?file=/src/App.tsx)
in the csb, click on "submit" to see the accordion opening and the scroll to error field

**Comment by lennerd** [comment]
@bluebill1049 not enough upvotes I guess?

**Comment by bluebill1049** [comment]
@lennerd it's instead a difficult one too (eg with or without animation, duration and etc), this would instead expand the code base quite a bit. However, because each errors object does expose with `ref` you can actually have that logic at your app level and take full control of when to call scrollIntoView with or without the animation and etc.

**Comment by lennerd** [comment]
Thanks for the quick response. I already figured that errors have a ref. My problem at this point is with `useController` and how the ref is used there. It currently does not apply the element itself but functions calling the methods on the element. So there is no way to get the reference to the actual element at that point. Whats the reason for that?

**Comment by lennerd** [comment]
Isn‘t okay to simply assing the ref if provided? How does it help tonhave the provided wrapper? Refs can be undefinded anyway, no?

**Comment by bluebill1049** [comment]
Yes, we can simply pass `ref`, but it also lost the ability for the library to differentiate a controlled component (with Controller/useController) vs native input as the current status. I may be looking into this to figure out an alternative way to differentiate rather than rely on ref.

**Comment by lennerd** [comment]
That would be awesome! Currently this exception inside `useController` is the only impediment for using the element ref inside our accordion to find invalid form fields and open the accordion accordingly (haha).

**Comment by lennerd** [comment]
@bluebill1049 What do you think about me making a PR directly? What are the problems you are seeing when changing this behavior in `useController`?

**Comment by bluebill1049** [comment]
It will break `useController` / `Controller` by assigning `ref` directly.

**Comment by lennerd** [comment]
Does it break a specific place in the code? Or is it several places?

**Comment by bluebill1049** [comment]
the other option is to consider exposing `scrollIntoView` if that's the API that you are after, but still, I would expect a feature request before the actual implementation and rollout from the lib.

**Comment by lennerd** [comment]
My problem is not related to scrolling (which is done by focusing the input anyway), but to open something like an accordion having an invalid input as a child (and focus this field manually when the accordion content is shown).

But I understand your concerns and will open a feature request and create a simple example ASAP. (Maybe there is an easier solutions to this after all.)
