### ISSUE TITLE
register option: setValueAs not working as expected.

### ISSUE THREAD

**Issue by sp0033212000** [react-hook-form/react-hook-form#5459]
**Describe the bug**
register option: setValueAs not working as expected.

**To Reproduce**

1. <input {...register("text", {setValueAs: v => v.replaceAll(/[^\d]/g, "")})} />
2. the value at input not be replace.

**Codesandbox link (Required)**
https://codesandbox.io/s/compassionate-leakey-1bwcu?file=/src/App.tsx

**Expected behavior**
The new value return by setValueAs will replace the value at input element.

**Desktop (please complete the following information):**

- OS: OSX
- Browser chrome
- Version 90.0.4430.212 (x86_64)

**Comment by bluebill1049** [comment]
It's not a mask input, it only parse the input during submit or value retrieve.
