### ISSUE TITLE
why entire component rerenders after error message is displayed?

### ISSUE THREAD

**Issue by sagar10k** [react-hook-form/react-hook-form#546]
hey there, I have a doubt regarding the error method that we use to display error message, my question is when the error message is displayed on the form after that does it render the entire component again or not because in my case i have form component which get renders again when error message is displayed after submit button is clicked (ideally it should not happen it should just display the message and thats it.) can you explain what might be the problem.

**Comment by bluebill1049** [comment]
that's the react render life cycle. react hook form need to trigger re-render in order to display an updated error message. same as useState or setState.
