### ISSUE TITLE
TypeScript: Controller defaultValue incorrect type

### ISSUE THREAD

**Issue by revich2** [react-hook-form/react-hook-form#5461]
**Describe the bug**
When you use Controller for field with name containing array literal, then defaultValue can't catch type from form values types.

**To Reproduce**
  - Open Codesandbox link
  - See the typescript error on field defaultValue - Type 'string' is not assignable to type 'undefined'.ts(2322)

**Codesandbox link (Required)**
https://codesandbox.io/s/lively-haze-zbqzs?file=/src/App.tsx

**Expected behavior**
Prop defaultValue should have the right type from form values types

**Comment by bluebill1049** [comment]
working as expected for me: https://codesandbox.io/s/hardcore-jepsen-x1ey7?file=/src/App.tsx
