### ISSUE TITLE
SetValue should respect mode/revalidateMode

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#548]
**Describe the bug**
SetValue should respect mode/revalidate mode, so user don't have to manually set the trigger validation argument

**Expected behavior**
smarter setValue for error correction and display

**Additional context**
This will work well with the new react-hook-form-input component to support MUI and react-select.

**Comment by dijkstra007** [comment]
@bluebill1049 Is it also related with react-datepicker? my revalidateMode for this field doesn't work.

**Comment by bluebill1049** [comment]
hey @dijkstra007 `revalidateMode` is not going to work with controlled component with react-datepicker. but you can leverage with `formState` and `setValue`

`setValue('name', 'value', formState.isSubmitted)`

also i am making a wrapper component for controlled component. maybe you will find it useful too :

https://github.com/react-hook-form/react-hook-form-input
