### ISSUE TITLE
how to use error method  for input type of file in edit form?

### ISSUE THREAD

**Issue by sagar10k** [react-hook-form/react-hook-form#549]
Hey there, I have a problem where i have created a input field with type file and i have registered it into hooks now the problem is the form is an edit form so initially i have to display the previous selected image name on form so user has an option if he wants to change the image or not and when user don't want to change the image and click submit. the error method is run and error is shown as "please select image". so how should i  approach this situation where there is edit form with image already being selected which is sent by the server so the error method wont throw error of "please select image"
Any help would be appreciated thanks.

**Comment by bluebill1049** [comment]
can you please supply a codesandbox? and prefer asking questions in the spectrum channel please.

**Comment by bluebill1049** [comment]
i am going to close it here, and post your quesiton in here. https://spectrum.chat/react-hook-form/general/not-my-question~ae3ceaf3-33e6-45de-b326-d9f2e3fd825e
you can upload your codesandbox here.
