### ISSUE TITLE
Bug: Unmount of non-primitive field immediately after reset causes error

### ISSUE THREAD

**Issue by rosemariesadler** [react-hook-form/react-hook-form#5492]
**Describe the bug**
When the value of a field is not a primitive (i.e. we have some meta-data that we save into the form for a typeahead component), if the field is unmounted immediately after reset an error occurs: `cannot set property 'mount' of undefined`. `registerAbsentFields` treats the object like each layer is its own key, causing `_f` to be undefined on `get(fieldsRef.current, name)` during the cleanup function of `useController`'s `useEffect`.

**To Reproduce**

1. Go to https://codesandbox.io/s/restless-tree-j60ws
2. Click on "Toggle Metadata" so the field is showing
3. Click on "Reset", which resets the form and hides the field

**Codesandbox link (Required)**
https://codesandbox.io/s/restless-tree-j60ws

**Expected behavior**
No error should occur when the field is unmounted immediately after reset.

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Browser: Chrome
- Version 91

**Smartphone (please complete the following information):**

- Device: Pixel 3
- OS: Android 11
- Browser: Chrome
- Version: 91

**Additional context**
I'm happy to put out a PR to fix the issue, but I'm not certain of the preferred approach. The most obvious fast fix I see is adding the check for `_f` existence in the cleanup function, but I'm wondering if more support should be added for non-primitive values? Maybe a ref that keeps track of the names of registered fields that we would then reference during `registerAbsentFields` instead of just checking if the field is a primitive value?

**Comment by rosemariesadler** [comment]
Thank you for the quick resolution! I appreciate the great work you've done on this library and the good support you provide!

**Comment by bluebill1049** [comment]
Welcome @rosemariesadler 🙉

**Comment by Deepak7985** [comment]
@bluebill1049 I'm getting the same bug again in the new version 7.30.0 , I saw few lines around that useEffect has changed https://github.com/react-hook-form/react-hook-form/commit/c41511fa10ffad75b95f5e054b58492dc87113d5 ??

**Comment by Deepak7985** [comment]
In the Commit https://github.com/react-hook-form/react-hook-form/commit/c41511fa10ffad75b95f5e054b58492dc87113d5 we can see there is a check  on **field._f** but in the latest version we don't have that check.

**Comment by tetchel** [comment]
I have this bug as well, and cannot figure out why. It seems to be happening on a component which is being unmounted after the form submits.

I tried versions 7.29.0, 7.30.0, and 7.31.2 and have the same result on all 3.

**Comment by tetchel** [comment]
I had a wrapper component which was passed the `name` to provide to the controlled component. 

for some reason, changing the object so that the `name` did not contain any periods (ie, the object was not nested) fixed this bug.
