### ISSUE TITLE
Wrong value if multiple submit buttons used

### ISSUE THREAD

**Issue by dawidurbanski** [react-hook-form/react-hook-form#5494]
**Describe the bug**
I'm not sure if this is a bug or is it how it supposed to be but when I have two or more submit buttons and I want to get the value of the clicked button I always get the first button value.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://codesandbox.io/s/react-hook-form-get-started-forked-3u9t1
2. Open the console
3.  Click on SUBMIT 1 button 
4.  Console logs: `{example: "test", submitValue: "button1"}` good
5.  Click on SUBMIT 2 button
6.  Console logs: `{example: "test", submitValue: "button1"}` wrong, expected `{example: "test", submitValue: "button2"}`

**Codesandbox link (Required)**
 https://codesandbox.io/s/react-hook-form-get-started-forked-3u9t1

**Expected behaviour**
Data in `onSubmit` callback should have correct value based on which button user clicked.

**Desktop (please complete the following information):**

- OS: macOS Mojave (10.14.6)
- Browser Chrome
- Version 90.0.4430.212 (Official Build) (x86_64)

Thanks for creating this amazing library!

**Comment by bluebill1049** [comment]
<img width="970" alt="Screen Shot 2021-06-05 at 9 10 06 am" src="https://user-images.githubusercontent.com/10513364/120870992-d3fdc500-c5dd-11eb-9d76-da42f1d023b6.png">

`name` should be unique.

**Comment by dawidurbanski** [comment]
@bluebill1049 thanks for quick response.

This makes sense, I should have picked up from the docs.

Although it does not solve the problem. If I make both buttons with different name they are both sent with every submit. How do I know which button was used to submit the form?

Check this one: https://codesandbox.io/s/react-hook-form-get-started-forked-8monb

No matter which button I click, I get the same data in `onSubmit`: `{example: "test", submitValue1: "button1", submitValue2: "button2"}` consisting bot buttons values.

**Comment by dawidurbanski** [comment]
I'll use some workaround for now. Thanks again for this amazing library!

**Comment by bluebill1049** [comment]
perhaps it's better to store those values in a hidden input?

**Comment by dawidurbanski** [comment]
Yeah, that's one way to go.

In case someone ends up here from Google, I actually solved it in a bit different way. I actually handled adding data to state manually (instead letting library to handle it for me), by accessing `nativeEvent`s `submitter` property like so:

```
const onSubmit = (data, { nativeEvent }) => {
  const { submitter } = nativeEvent;

  actions.updateAction({
    dogs: submitter.value
  });

  props.history.push("./step2");
};
```

If you think for a second about it, you probably will realise that if you only have yes/no questions through the entire wizard you probably don't even need to use `react-hook-form`. You can just simply handle submission + state population manually without any library.

In my case yes/no are actually just one type of a form step (I simplified it for sake of showcasing the problem). Some steps in my wizard are fully-fledged forms, and only some are yes/no, so I'll keep `react-hook-form` for all steps for consistency.

Here's the working demo: https://codesandbox.io/s/react-hook-form-get-started-forked-jk5ym

And once again @bluebill1049 thanks for the support and your hard work!

**Comment by bluebill1049** [comment]
thanks, @dawidurbanski for the follow-up and detailed explanation. This will definitely be useful for others. 👍
