### ISSUE TITLE
Validation doesn't work 

### ISSUE THREAD

**Issue by beqramo** [react-hook-form/react-hook-form#5501]
**Describe the bug**
Hi, I'm using this package for more than a year but now I have a problem with React native, in short validation doesn't work anymore starting from yesterday, and I don't understand what happened, I tried to downgrade but the same thing.  I'm doing super simple stuff, I checked on the Web and it worked. 

With `setError` it setting an error on the field, `trigger` and submit press does nothing. 

So I'm logging formState to see errors but it is empty

thank you in advance.

**To Reproduce**
press submit and it will not throw an error

**Codesandbox link (Required)**
sorry but I can't do it for RN, I will paste a little snippet here:

```tsx
// app.tsx // entry file
const App = () => {

  const { handleSubmit, control, formState, trigger, setError } = useForm({
    defaultValues: {
      email: '',
    },
  });
  console.log(formState, 'formState'); // errors object is always empty
  return (
    <Column >
      <Controller
        control={control}
        name="email"
        render={({ field: { onChange, onBlur, value } }) => (
          <TextInput
            onBlur={onBlur}
            onChangeText={(value) => onChange(value)}
            value={value}
            placeholder={'email'}
          />
        )}
        rules={{ required: true, minLength: 8 }}
      />
    </Column>

    <Button title="Submit" onPress={handleSubmit(() => {})} />)
}
```

**Expected behavior**
show error

**Screenshots**
this is a log on submit but indeed there should be the object of errors with data.
![image](https://user-images.githubusercontent.com/40486471/120905851-03f0ab00-c666-11eb-8b9b-22dd3f274899.png)

**Smartphone (please complete the following information):**

- Device:  iPhone12
- OS: 14.5
`"react-hook-form": "^7.8.1"`

**Comment by bluebill1049** [comment]
https://snack.expo.io/@bluebill1049/react-hook-form-v7---controller
