### ISSUE TITLE
If I remove all the items of a list using useFieldArray, I don't get an empty array, I get an array with null items.

### ISSUE THREAD

**Issue by giomv** [react-hook-form/react-hook-form#5506]
**Describe the bug**
I have a nested array with 3 parent elements and I child element, using useFieldArray. If I remove all the default items I get an array with 3 null elements instead of an empty array, using watch. When I try to add a new element, I get 4 parent elements, 3 of them are the elements previously deleted.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-forked-iw71g?file=/src/index.js
2. Click on Remove on each of the 3 items.
3. See the watch elements and instead of an empty array you see null elements inside the array.
3. Click on Add
4. You see 4 elements instead of one.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-iw71g?file=/src/index.js

**Expected behavior**
I expect first to have an empty array in the watch when I remove all the elements. And after adding one element on that empty array, I should have only one element in the form and the watch.

**Screenshots**

<img width="544" alt="Captura de Pantalla 2021-06-06 a la(s) 17 47 25" src="https://user-images.githubusercontent.com/1816080/120942569-85d8e680-c6ef-11eb-909b-b8545796ef0b.png">
<img width="544" alt="Captura de Pantalla 2021-06-06 a la(s) 17 47 30" src="https://user-images.githubusercontent.com/1816080/120942573-87a2aa00-c6ef-11eb-96bc-92c4c1f53f0a.png">
<img width="544" alt="Captura de Pantalla 2021-06-06 a la(s) 17 47 34" src="https://user-images.githubusercontent.com/1816080/120942575-883b4080-c6ef-11eb-86e2-8da7842e3c54.png">
<img width="544" alt="Captura de Pantalla 2021-06-06 a la(s) 17 47 38" src="https://user-images.githubusercontent.com/1816080/120942577-88d3d700-c6ef-11eb-930d-3df2c02827c8.png">
<img width="544" alt="Captura de Pantalla 2021-06-06 a la(s) 17 47 44" src="https://user-images.githubusercontent.com/1816080/120942578-896c6d80-c6ef-11eb-876e-a53001868c80.png">

**Desktop (please complete the following information):**<img width="544" alt="Captura de Pantalla 2021-06-06 a la(s) 17 47 25" src="https://user-images.githubusercontent.com/1816080/120942560-735ead00-c6ef-11eb-88e2-f5e317ab1239.png">
- OS: MacOS
- Browser: Chrome
- Version: latest

**Additional context**
React Hook Form version: 6.15.7

**Comment by giomv** [comment]
It's working great in the new version. Thank you very much!

**Comment by bluebill1049** [comment]
> It's working great in the new version. Thank you very much!

Welcome. thanks for the detailed issue report too.
