### ISSUE TITLE
Version 7.8.0 introduces breaking change to manual arrays

### ISSUE THREAD

**Issue by mrlubos** [react-hook-form/react-hook-form#5507]
**Describe the bug**
This issue is related to https://github.com/react-hook-form/react-hook-form/issues/5232 and https://github.com/react-hook-form/react-hook-form/issues/5423. After using the suggested solution, I was able to fix both issues by calling the `register()` method and setting `shouldUnregister` to `true`. This worked for a day until the version 7.8.0 was released and now the `undefined` bug is back.

**To Reproduce**

1. Open [CodeSandbox](https://codesandbox.io/s/relaxed-galois-85r89?file=/src/App.tsx)
2. Click on the submit button
3. Notice the `array` state is undefined
4. Notice I call both `register()` and `shouldUnregister` as [recommended](https://github.com/react-hook-form/react-hook-form/issues/5232#issuecomment-854662861) for `7.7.1`

**Codesandbox link (Required)**
[CodeSandbox](https://codesandbox.io/s/relaxed-galois-85r89?file=/src/App.tsx)

**Expected behavior**
The behaviour remains unchanged since this was a minor version update to version 7.8.0.

**Additional context**
I would think the problem is with `register()` now expecting a `value` supplied in options and since I don't do that, it assumes it to be `undefined`?

**Comment by bluebill1049** [comment]
Thanks. The new API is the root cause, will try to patch it tonight.

**Comment by mrlubos** [comment]
> Thanks. The new API is the root cause, will try to patch it tonight.

As always, thank you!
