### ISSUE TITLE
setFocus error: get(...)._f.ref.focus is not a function

### ISSUE THREAD

**Issue by Rafatcb** [react-hook-form/react-hook-form#5514]
**Describe the bug**
When I call `setFocus()` immediately after `reset()`, it throws an error:

> Uncaught TypeError: get(...)._f.ref.focus is not a function
    at setFocus (index.esm.js:1573)

The referenced row is in `setFocus()`:

https://github.com/react-hook-form/react-hook-form/blob/85c60610006b606669d59d42212f18d361c84d3a/src/useForm.ts#L1141-L1142

**To Reproduce**

1. Go to [this CodeSandbox](https://codesandbox.io/s/react-hook-form-setfocus-error-pi5k6)
2. Click on Reset
3. See the error (unfortunately, the CodeSandbox will refresh the page)

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-setfocus-error-pi5k6

**Expected behavior**
Should just focus the input, without losing its reference.

**Screenshots**

The screenshot is an error for the following code:

```javascript
function hideModal() {
  reset({ product: getValues('product') });
  setFocus('product');
  setModalVisible(false);
}
```

I've put a `console.log(get(fieldsRef.current, name))` inside `setFocus` function to see its value.

![Error screenshot](https://user-images.githubusercontent.com/26308880/121066478-533af680-c7a0-11eb-889b-3bf5b76a3379.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Reproduced the CodeSandbox in OperaGX, but I'm using Electron (Chrome)
- Version: OperaGX aLVL 2 (core: 75.0.3969.282), Electron 11.4.7 (Chrome 87.0.4280.141)

**Additional context**

In my Electron app, inverting the order ( `reset(); setFocus();` to `setFocus(); reset();`) works fine, but in CodeSandbox it still throws.

**Comment by Rafatcb** [comment]
I believe just checking `_f.ref.focus()` as in `focusFieldBy` would fix the error, but I don't know if it should be losing reference like this in `reset({ field: value })`.

https://github.com/react-hook-form/react-hook-form/blob/85c60610006b606669d59d42212f18d361c84d3a/src/logic/focusFieldBy.ts#L20-L25

To avoid this problem in my app, I'm just using it in the order that it doesn't throw an error (`setFocus()` -> `reset()`)

**Comment by bluebill1049** [comment]
This is due to ref is getting lost after reset. Do it at useEffect
