### ISSUE TITLE
Validation Resolver broken on 7.8.0

### ISSUE THREAD

**Issue by yudielcurbelo** [react-hook-form/react-hook-form#5527]
**Describe the bug**
After the update, I'm not able to dynamically change the validation scheme.

**To Reproduce**
Open the sandbox and type something on the age input.
The message "age" is not allowed is going to show since age is not specified in validation1.
Click the button and type some string.
The message "age" must be a number is going to show since age is a number specified in validation2.

Repeat the same steps in version 7.8.0, the scheme does not change.

V7.7.1

- [codesandbox](https://codesandbox.io/s/validation-version-771-2lj9i?file=/src/index.js)

V7.8.0

- [codesandbox](https://codesandbox.io/s/validation-version-780-qjrcr?file=/src/index.js)

**Comment by marr** [comment]
I think I'm hitting this same issue. I thought it was something to do with my stepper form, but the schema appears to not be updating here as well <https://codesandbox.io/s/beautiful-borg-dse83?file=/src/App.js>

**Comment by yudielcurbelo** [comment]
> I think I'm hitting this same issue. I thought it was something to do with my stepper form, but the schema appears to not be updating here as well https://codesandbox.io/s/beautiful-borg-dse83?file=/src/App.js

Looks the same.

**Comment by bluebill1049** [comment]
> To Reproduce
Open the sandbox and type something on the age input.
The message "age" is not allowed is going to show since age is not specified in validation1.
Click the button and type some string.
The message "age" must be a number is going to show since age is a number specified in validation2.

I couldn't reproduce that in 7.7.1 as well.

**Comment by bluebill1049** [comment]
I think I know the root cause, in fact, I never thought such a use case, and `context` was meant to do that, but if users are using it in such a way, I think we should support it.

**Comment by yudielcurbelo** [comment]
> > To Reproduce
> > Open the sandbox and type something on the age input.
> > The message "age" is not allowed is going to show since age is not specified in validation1.
> > Click the button and type some string.
> > The message "age" must be a number is going to show since age is a number specified in validation2.
> 
> I couldn't reproduce that in 7.7.1 as well.

In 7.7.1 works. The issue is on 7.8.0

**Comment by yudielcurbelo** [comment]
> I think I know the root cause, in fact, I never thought such a use case, and `context` was meant to do that, but if users are using it in such a way, I think we should support it.

When you mention `context` are you making a reference to `useFormContext`. I use it in multiple places but don’t know of any way of changing the validation scheme after `useForm` methods have been initialized.

**Comment by bluebill1049** [comment]
No the context object

**Comment by bluebill1049** [comment]
fix on the next patch.
