### ISSUE TITLE
Schema Errors cleaned after manually triggering setValue(name, value, true) for a given field

### ISSUE THREAD

**Issue by miguel-lattuada** [react-hook-form/react-hook-form#553]
**Describe the bug**
Schema Errors are cleaned when you manually set a value with setValue and trigger validation.
This will return an empty object, or if the value is still invalid just the object with that value.
https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L312

**To Reproduce**
1. Configure useForm to use schema validation
2. Trigger form validation on submit (and get the { errors } fulfilled)
3. Now manually trigger setValue(name, value, true) (this will validate the new value) for some invalid field
4. See how every field error is cleaned

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-trigger-validation-gmsvi

**Expected behavior**
`{ errors }` object should be updated accordingly with the error you removed and not completed cleared.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [78]

**Additional context**
You can avoid this behavior using two calls, instead of `setValue(name, value, true)` 
you can 
```
setValue(name, value); 
triggerValidation([{ name }]) // notice the array as a parameter otherwise it's the same
```

**Comment by bluebill1049** [comment]
thanks for the detailed issue report @miguel-lattuada :) i will take a look at it.
