### ISSUE TITLE
V7 - Bug: GetValues() returns only array of values

### ISSUE THREAD

**Issue by rpk-red** [react-hook-form/react-hook-form#5537]
In v7 when getValues is called with multiple properties return value is array of values only and not object with key/value pair like in v6.

Example:
`const values = getValues(["property1", "property2", "propertyu3"])`
 V6: 
 `values` would be `{property1: "value1", property2: "value2," property3: "value3"}`
 V7: 
 `values` are `["value1", "value2", "value3"]`

I have read [Migration Guide](https://react-hook-form.com/migrate-v6-to-v7/) and could not find any changes regarding getValues(), also read [API documentation](https://react-hook-form.com/api/useform/getvalues) where in example it is illustrated that it should return array of objects with key/value pair  so I assume it is a bug?

**Comment by bluebill1049** [comment]
<img width="943" alt="Screen Shot 2021-06-09 at 11 52 42 pm" src="https://user-images.githubusercontent.com/10513364/121367609-c9488480-c97d-11eb-9158-da00c969f6ae.png">

that's expected for v7.

**Comment by rpk-red** [comment]
But then documentation is not correct or am I missing something?
In provided example it says: 
```
          const multipleValues = getValues(["test", "test1"]);
          // [{ test: "test-input" }, { test1: "test1-input" }]
```
That is wrong? It should be `["test-input",, "test1-input"]`

**Comment by bluebill1049** [comment]
thanks, updated.

**Comment by RikkiMasters** [comment]
> <img alt="Screen Shot 2021-06-09 at 11 52 42 pm" width="943" src="https://user-images.githubusercontent.com/10513364/121367609-c9488480-c97d-11eb-9158-da00c969f6ae.png">
> 
> that's expected for v7.

It isn't working as quoted.

`getValues(["yourDetails.lastName"])` returns `['']`

The documentation https://react-hook-form.com/api/useform/getvalues needs updating

```
const multipleValues = getValues(["test", "test1"]);
 // [{ test: "test-input" }, { test1: "test1-input" }]
```
should be

```
const multipleValues = getValues(["test", "test1"]);
 // ["test-input", "test1-input"]
```

Surely it would be better if it returned the keys too like v6?

**Comment by bluebill1049** [comment]
thanks @RikkiMasters  fixed, please send us a pr next time if you spot thing is incorrect.
