### ISSUE TITLE
setError shouldFocus doesn't work

### ISSUE THREAD

**Issue by orenklein** [react-hook-form/react-hook-form#5538]
**Describe the bug**
Calling `setError` manually with `shouldFocus: true` does not focus on the related input field.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-v7-seterror-forked-52dil?file=/src/index.jsx

**Comment by bluebill1049** [comment]
`setError(name, { type, message }, { shouldFocus })` thrid argument.

**Comment by orenklein** [comment]
Great! So what is the shouldFocus in the second argument for?

**Comment by bluebill1049** [comment]
good pick up, i will fix the `type`.
