### ISSUE TITLE
setValue Only Works on Rendered Fields

### ISSUE THREAD

**Issue by marr** [react-hook-form/react-hook-form#5546]
**Describe the bug**
When calling `setValue` on a form, the fields have to exist on the page.

**To Reproduce**

1. Go to https://codesandbox.io/s/purple-paper-i7p5s?file=/src/App.js
2. Select "Foo" from the dropdown- this will call `setValue` on a field that exists in `defaultValues`
3. Click "Reveal". You will see the fields rendered using default values.

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

V7

https://codesandbox.io/s/purple-paper-i7p5s?file=/src/App.jse

**Expected behavior**
I would expect setValue to be honored if used before the fields are rendered.

**Comment by bluebill1049** [comment]
I will include more detail on this part in the documentation.

**Comment by bluebill1049** [comment]
actually i will do some investigation tonight, see if we can improve on this.

**Comment by bluebill1049** [comment]
This is not going to work because, during `setValue` action, the hook form doesn't have context it's a field array because it's not even rendered. I will add this information to the doc. You can keep the field array rendered and just toggle the visibility to pass this behavior.
