### ISSUE TITLE
Problem watching complex custom fields

### ISSUE THREAD

**Issue by GProst** [react-hook-form/react-hook-form#555]
I'm trying to implement a single source of truth via react-hook-form for my dynamic form.
Let's say there is a dynamic array of objects (`animals`) with props `name` and `type`, so the fields will have the following names: `animals[index].name` and `animals[index].type`. And `type` is a custom field.
I watch all the animals using `watch('animals')`, animals can be added and removed dynamically and I have a few animals defined initially.

The problem appears when I try to register a custom field that has nested props, i.e. `register({name: 'animals[0].type'})`. It doesn't matter if I have `defaultValues` suppled to the `watch` method or not I have the following error:
```
Uncaught TypeError: Cannot convert undefined or null to object
```

One possible workaround that I figured out is to manually set initial value right after the field was registered, i.e. `setValue('animals[0].type', 'Cat')`. But this makes the form dirty and it's not the behavior I want for the initial fields.

The second issue is that even if I put `type: 'custom'` it won't re-render component after `setValue` is called. I believe this is only when it's a complex field (with nested props) and when you watch not all fields.

**Expected behavior**
1. `watch` method should either use `defaultValues` provided as the second argument when trying to resolve values for complex custom fields or just use `undefined` if `defaultValues` wasn't provided
2. `setValue` should trigger re-render if a field was registered with `type: 'custom'` prop even if it's a complex custom field.

P.S. Thank you for your great work on this library!

**Comment by GProst** [comment]
I think the problem appears when there are several field types involved (custom and not-custom). I.e. if `animals[0].type` is custom and `animals[0].name` is not.

Here is a Sandbox example:
https://codesandbox.io/s/react-hook-form-get-started-43dde
Uncomment `useEffect` and try to update text input, it will crash.

**Comment by GProst** [comment]
Example with not triggered re-render:
https://codesandbox.io/s/react-hook-form-get-started-6r6x8

**Comment by GProst** [comment]
I believe the issue is in the `getPath` checks ([this line](https://github.com/react-hook-form/react-hook-form/blob/master/src/utils/getPath.ts#L19) and [this line](https://github.com/react-hook-form/react-hook-form/blob/master/src/utils/getPath.ts#L28))
I think it should be `!isObject` instead, otherwise if the value is a primitive other than string it will throw an error.

**Comment by bluebill1049** [comment]
hey @GProst thanks for the detailed issue report and diagnose! Do you want to submit a PR since you figure the solution (credit goes to you) 👍. i can help to test as well.

**Comment by GProst** [comment]
@bluebill1049 yep, will do!
But probably tomorrow morning already 👍

**Comment by bluebill1049** [comment]
no worries :) whenever you have some free time 👍
