### ISSUE TITLE
Material ui Datepicker format wrong when using Controller

### ISSUE THREAD

**Issue by lassekl92** [react-hook-form/react-hook-form#5559]
**Describe the bug**
Hello! I just upgraded from v6 to v7 and found one issue i think is a Bug.

When using Controller and Datepicker from material-ui/pickers the date format is displayed wrong on initial render or page reload.
But after clicking and selecting new date the problem dissapears.

This only happens when you add the inputRef from Controller component.

**To Reproduce**

1. Reload page in codesandbox
2. Long format type displayed in Datepicker input like this:
![image](https://user-images.githubusercontent.com/61147590/121537045-de67f680-ca03-11eb-9a3e-4f0645b38eea.png)
3. Then after clicking the format goes back to the correct one:
![image](https://user-images.githubusercontent.com/61147590/121537134-f50e4d80-ca03-11eb-9cdc-4a8c04cd58f1.png)

**Codesandbox link (Required)**

V7
https://codesandbox.io/s/determined-meninsky-y8cg9?file=/src/App.js

browser: edge

**Comment by bluebill1049** [comment]
Take a look at this question' answer: https://github.com/react-hook-form/react-hook-form/discussions/5360

**Comment by lassekl92** [comment]
Thanks!

**Comment by bluebill1049** [comment]
This behaviour will be improved in the next minor update.
