### ISSUE TITLE
Issue with setValue with nested objects within useFieldArray after calling append

### ISSUE THREAD

**Issue by ryanbuxton523** [react-hook-form/react-hook-form#5562]
**Describe the bug**
When using useFieldArray with fields containing nested objects, setValue does not work as expected on appended fields.

**To Reproduce**
1. Click 'Append'.
2. Click 'Set Appended Values'.
3. See newly appended inputs are not updated.
4. Click 'Set Original Values'.
5. See the original inputs are updated as expected.

**Codesandbox link (Required)**
https://codesandbox.io/s/focused-einstein-p74ps?file=/src/App.js

**Expected behavior**
Expected the newly appended inputs to be updated using setValue the same way the original inputs are updated.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 90.0.4430.212

**Additional context**
I recently migrated from V6 to V7, and this issue did not exist in V6. Please let me know if there is a different recommended method for setting values of inputs nested within useFieldArray.

Thanks for this awesome library!

**Comment by bluebill1049** [comment]
There are differences in form inputs. 

- A single input can contain a single value.
- A single input can multiple values (object or array)

## Problem

```
<input
  {...register(`test.${index}.value.first`)}
  defaultValue={field.value.first}
/>
<input
  {...register(`test.${index}.value.second`)}
  defaultValue={field.value.second}
/>

setValue("test.0.value", { first: "newFirst", second: "newSecond" })
```

## Solution

This will make hook form confused `test.0.value` is a single input with multiple values, so to solve the problem you should invoke two setValue to update those two inputs unless you have a group input which contain object/array as input value.
