### ISSUE TITLE
isDirty not working as expected when using Controller instead of the hook to provide the default value (v7)

### ISSUE THREAD

**Issue by josias-r** [react-hook-form/react-hook-form#5563]
**Describe the bug**
I tried switching to the defaultValue Prop of the controller, instead of using the defaultValues object argument of useForm. I found, that the isDirty state behaves like isTouched isntead of isDirty when used this way.

**To Reproduce/Codesandbox**
See comparison / reproduction: https://codesandbox.io/s/amazing-wilbur-p1c5v?file=/src/App.js

**Expected behavior**
I expect the defaultValue prop of Controller to behave the same as the defaultValues argument of useForm.

**Comment by bluebill1049** [comment]
>Make sure to provide all inputs' defaultValues at the useForm, so hook form can have a single source of truth to compare whether the form is dirty.

<img width="976" alt="Screen Shot 2021-06-11 at 8 34 40 am" src="https://user-images.githubusercontent.com/10513364/121605514-df466a00-ca8f-11eb-8ee9-a284902092a4.png">

We will need `defaultValues`.

**Comment by josias-r** [comment]
@bluebill1049 For my understanding, is the `defaultValue` prop of Controller only used for `useFieldArray` in that case, or what other uses does it have?

**Comment by bluebill1049** [comment]
yes, for isDirty we will always need `defaultValues` as the source of truth for the comparison.
