### ISSUE TITLE
Wrong input focused with useFieldArray insert

### ISSUE THREAD

**Issue by ryanbuxton523** [react-hook-form/react-hook-form#5568]
**Describe the bug**
When using the insert method from useFieldArray, the wrong input is focused sometimes.

**To Reproduce**
1. Click 'insert' directly below the input containing '0'.
2. Repeat step 1 for a total of 10 clicks.
3. See on the tenth click the last input in the array is focused instead of the newly inserted input.

**Codesandbox link (Required)**
https://codesandbox.io/s/awesome-lake-g14kn?file=/src/App.js

**Expected behavior**
The newly inserted input should be focused instead of the last input in the array.

**Desktop (please complete the following information):**

OS: Windows 10
Browser: Chrome
Version: 90.0.4430.212

Thanks for this awesome library!

**Comment by bluebill1049** [comment]
I couldn't reproduce this issue, can you share more detail?

https://user-images.githubusercontent.com/10513364/121605903-8cb97d80-ca90-11eb-822f-34cce8ab5a44.mov

**Comment by ryanbuxton523** [comment]
Sorry for the confusion. I meant click the same insert button 10 times. This CSB should be less misleading:
https://codesandbox.io/s/awesome-lake-g14kn?file=/src/App.js
