### ISSUE TITLE
Controller component doesn't work on version >= 3.28.0

### ISSUE THREAD

**Issue by ahce** [react-hook-form/react-hook-form#557]
**Describe the bug**
Works fine on version 3.27.0

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-bug-ben8i

**Expected behavior**
3.27.0 behavior

**Comment by bluebill1049** [comment]
This is correct behavior, 3.27.0 has a bug that triggers re-render when not required. I would recommend use this component for controlled component: https://github.com/react-hook-form/react-hook-form-input

**Comment by bluebill1049** [comment]
you should have use `watch()` if you want to subscribe to the input'value too.

**Comment by ahce** [comment]
I use this behavior for material-ui-pickers, as indicated in the [documentation](https://react-hook-form.com/api/#register).

What is the best solution in 3.28.x?

**Comment by bluebill1049** [comment]
take a look this wrapper component, you will find it much easier to work with react-hook-form while still give you app great performance: https://github.com/react-hook-form/react-hook-form-input.

```
import React from 'react';
import useForm from 'react-hook-form';
import { RHFInput } from 'react-hook-form-input';
import Select from 'react-select';

const options = [
  { value: 'chocolate', label: 'Chocolate' },
  { value: 'strawberry', label: 'Strawberry' },
  { value: 'vanilla', label: 'Vanilla' },
];

function App() {
  const { handleSubmit, register, setValue, reset } = useForm();

  return (
    <form onSubmit={handleSubmit(data => console.log(data))}>
      <RHFInput
        as={<Select options={options} />}
        rules={{ required: true }}
        name="reactSelect"
        register={register}
        setValue={setValue}
      />
      <button
        type="button"
        onClick={() => {
          reset({
            reactSelect: '',
          });
        }}
      >
        Reset Form
      </button>
      <button>submit</button>
    </form>
  );
}
```

**Comment by bluebill1049** [comment]
live demo here: https://codesandbox.io/s/react-hook-form-hookforminput-rzu9s

**Comment by bluebill1049** [comment]
i am updating the docs as we speak with this new component.

**Comment by ahce** [comment]
Great! 
Thank you very much!

**Comment by bluebill1049** [comment]
you are welcome :) ask you a favor if you find this lib useful, please consider to leave a star to support us too (no pressure if you don't want to)

**Comment by bluebill1049** [comment]
just use `watch`

```
import React from "react";
import ReactDOM from "react-dom";
import useForm from "react-hook-form";
import { IconButton, InputAdornment, TextField } from "@material-ui/core";
import {
  Visibility as VisibilityIcon,
  VisibilityOff as VisibilityOffIcon
} from "@material-ui/icons";

import "./styles.css";

function App() {
  const { register, getValues, setValue, watch } = useForm({
    defaultValues: { password: "", showPassword: false }
  });

  const showPassword = watch('showPassword');

  return (
    <div className="App">
      <TextField
        name="password"
        inputRef={register}
        type={showPassword ? "text" : "password"}
        InputProps={{
          endAdornment: (
            <InputAdornment>
              <IconButton
                buttonRef={register({
                  name: "showPassword",
                  type: "custom"
                })}
                onClick={() => setValue("showPassword", !showPassword)}
              >
                {showPassword ? <VisibilityIcon /> : <VisibilityOffIcon />}
              </IconButton>
            </InputAdornment>
          )
        }}
      />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

i think it's important to understand the difference between `watch` and `getValues()`

watch subscribe to the input and watch each input
getValues doens't trigger re-render and only return the current form values

**Comment by ahce** [comment]
Awesome thanks!

**Comment by ahce** [comment]
@bluebill1049 
When you pass validationSchema, watch method doesn't work correctly
https://codesandbox.io/s/react-hook-form-pwd-input-zskgv

**Comment by bluebill1049** [comment]
can you provide more detail @ahce ? what's not working?

**Comment by bluebill1049** [comment]
step to reproduce the issue.

**Comment by ahce** [comment]
In the sanbox link

1. Clic on the eye button
2. Check that it doesn't work
3. Remove line 15 ``` validationSchema: {} ```
4. Try again an check that it works

**Comment by bluebill1049** [comment]
why you using the third argument if you are not doing validation?

`setValue('xx', 'xx', true)`

**Comment by bluebill1049** [comment]
i am patching this

**Comment by AsadSaleh** [comment]
@bluebill1049 In https://codesandbox.io/s/react-hook-form-pwd-input-zskgv your React-Select component does not give the value when I submit. The other component works fine, but the Select did not. Only when I clear the value, the value null exists `{ "ReactSelect": null }`.

Please help, thanks!

**Comment by bluebill1049** [comment]
did you try the latest version?
