### ISSUE TITLE
TypeScript missing property "value" on register function.

### ISSUE THREAD

**Issue by angelvega93** [react-hook-form/react-hook-form#5573]
TypeScript missing property "value" on register function.

Example:
`register("test", { value: "something" });`

**Comment by bluebill1049** [comment]
<img width="559" alt="Screen Shot 2021-06-11 at 2 47 53 pm" src="https://user-images.githubusercontent.com/10513364/121632254-01f27600-cac4-11eb-8732-13bce77d23e6.png">

https://github.com/react-hook-form/react-hook-form/issues/2848
