### ISSUE TITLE
calling setValue triggering handleSubmit method

### ISSUE THREAD

**Issue by Humadroid** [react-hook-form/react-hook-form#5590]
**Describe the bug**
I have got a custom input field and attached a clear "x" button to clear the field.
To clear the custom input field I'm calling `setValue('fieldName', '')`
this works but it's also calling the `handleSubmit` method of the form.

**To Reproduce**
1) Go to the stackblitz link
2) Click on the 'x' cross button for the firstName input field
3) You will find submit triggered message in the `console.log` along with the submitted value.

[**STACKBLITZ LINK FOR THE ISSUE**](https://stackblitz.com/edit/react-custom-input-clear-button-setvalue-react-hook-form-issue2?file=src/App.js)

**Expected behavior**
calling setValue should not trigger handleSubmit.

If, that's not the case how can we call setValue from a child/nested component which will trigger validation but won't trigger handleSubmit ? 

**Additional context**
Using react-hook-form v7.8+

**Comment by bluebill1049** [comment]
type="button"
