### ISSUE TITLE
If the value is set after rendering, the value that is passed to the validation function is the old value.

### ISSUE THREAD

**Issue by mjza** [react-hook-form/react-hook-form#5593]
**Describe the bug**
If the value is set after rendering, the value that is passed to the validation function is the old value.

**To Reproduce**
1. Go to the following link: https://codesandbox.io/s/objective-sky-r176z?file=/src/App.js
1. The variable `firstName` is set to an empty string first.
2. The variable is set to a text later in `useEffect` function
3. Open the console.
4. Press on `toggle` button to change the input from disabled to active
5. press on `submit` button 
6. Look at the console
7. While the input has value, it sends the old value (e.g. empty string) to the validation function

**Codesandbox link (Required)**
https://codesandbox.io/s/objective-sky-r176z?file=/src/App.js

**Expected behavior**
It must pass the current value to validation function

**Why it is important**
I found this error for the input boxes that their values are set via auto complete. When browser set their value after rendering, those auto set values are not passed. 

**Where is the source of problem**
If I remove `onChangeInput` function then the values that are set by auto complete also are passed to the validation function. It seems something is missing in my code when I need to have `onChange` event for cleaning up the input, or do some further actions. 

**Screenshots**
![](https://i.stack.imgur.com/hnMnz.png)

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [chrome]
- Version [91]

**Additional context**
We discussed similar error former [here](https://github.com/react-hook-form/react-hook-form/discussions/5277), 
it seems these two errors are related to each other.

**Comment by bluebill1049** [comment]
use `setValue` instead, also you are mixing `uncontrolled` with `controlled`.

https://react-hook-form.com/api/useform/setvalue

**Comment by mjza** [comment]
@bluebill1049 Why should I use setValue if the value is read from state.

**Comment by mjza** [comment]
Anyway it seems it is a good trick.
https://codesandbox.io/s/agitated-chaplygin-mfk4x?file=/src/App.js

**Comment by tonypee** [comment]
Since you are dynamically changing the value, you should be using a Controller as it is a controlled component.
