### ISSUE TITLE
TS: Error type inferred incorrectly on Array fields

### ISSUE THREAD

**Issue by ohlr** [react-hook-form/react-hook-form#5601]
**Describe the bug**
The error type of an array field is an array (according to Typescript) however logging it to the console its an object

**To Reproduce**
Hover over `errors.tags` to see the type inferred by TS is an array. Open the console to see that in reality its an object.

Typescript infers Array of errors:
`(property) tags?: (FieldError | undefined)[] | undefined `

Reality object:
`{type: "required", message: "tags are required", ref: HTMLInputElement}`

**Codesandbox link (Required)**
https://codesandbox.io/s/blue-voice-fentm

**Expected behavior**
Typescript should infer the right type (object)

**Desktop (please complete the following information):**

- OS: [e.g. iOS]: Linux
- Browser [e.g. chrome, safari]: chrome
- Version [e.g. 22]: Version 91.0.4472.77

**Comment by ohlr** [comment]
Current workaround is to disable typescript when accessing such errors.tags (`// @ts-ignore`)

**Comment by bluebill1049** [comment]
https://react-hook-form.com/ts#NestedValue

**Comment by ohlr** [comment]
thanks
