### ISSUE TITLE
Insert/Append/Prepend drops nested data

### ISSUE THREAD

**Issue by Xadoy** [react-hook-form/react-hook-form#5603]
I will like to thank you for building such great library, it literally saved me from perf hell.

**Describe the bug**
Using useFieldArray's `append`, `insert`, `prepend` with nested array of objects, where one of the value in the object is another nested array.  The field (`field1` in the example) gets omitted.

``` javascript
    insert(1, {
      name: "insert",
      nestedArray: [{ field1: ["field1", "field11"], field2: "field2" }]
    });
```
will generate the following form data.
``` JSON
{
  "test": [
      {
          "name": "insert",
          "nestedArray": [
              {
                  "field2": "field2"
              }
          ]
      }
  ]
}
```

**To Reproduce**

1. Go to CSB
2. Click on buttons: `APPEND`, `APPEND NESTED`, `PREPEND`, `INSERT`, `PREPEND NESTED`
3. Click on `SUBMIT`
3. Scroll down to console, and check the output data
4. Only element fields created by `setValue` will preserve `field1`; element fields that are created by `append`, `insert`, `prepend` do not have `field1`.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-nw7pz?file=/src/fieldArray.js

**Expected behavior**
`append`, `insert`, `prepend` should preserve deeply nested array (`field1`).

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 91

**Comment by bluebill1049** [comment]
> I will like to thank you for building such great library, it literally saved me from perf hell.

Thanks for the kind words. <3

click `append`, I got the field 1? do I missing the steps to reproduce?

<img width="605" alt="Screen Shot 2021-06-15 at 9 54 03 am" src="https://user-images.githubusercontent.com/10513364/121972974-9fe58980-cdbf-11eb-8464-9336c167e0f7.png">

**Comment by Xadoy** [comment]
> click `append`, I got the field 1? do I missing the steps to reproduce?
> 
> <img alt="Screen Shot 2021-06-15 at 9 54 03 am" width="605" src="https://user-images.githubusercontent.com/10513364/121972974-9fe58980-cdbf-11eb-8464-9336c167e0f7.png">
The one you are seeing is the default value, please ignore this entry with the name of `"useFieldArray1"`.

**Comment by bluebill1049** [comment]
I see because we don't support flat array (register input for useFieldArray)

<img width="884" alt="Screen Shot 2021-06-15 at 10 14 24 am" src="https://user-images.githubusercontent.com/10513364/121974318-7712c380-cdc2-11eb-8656-a1cb23ba519a.png">

but, let me do some investigation on this deeply nested append, I think we may be able to work around this issue.

if you want to get it working for now, just use an object node inside, it should solve the problem.

for your knowledge, for append nested input, we are actually pre-registering those inputs on your behalf. hook form is all about inputs.

**Comment by Xadoy** [comment]
Thanks for being so responsive, I have changed my data structure to work around this. Also thanks for the knowledge, I am not sure if I am using RHF the worst way (maybe "anti-patter"), but I have been thru I lots of problems, especially for `setValues()` and `useWatch()`, they always triggered some unexpected behaviour to me. I might try to summarize those cases if I could. Or I should read a little more about how to use RHF properly.

**Comment by bluebill1049** [comment]
> they always triggered some unexpected behaviour to me. I might try to summarize those cases if I could

Feel free to summarise them, I will respond.

**Comment by dancixx** [comment]
@bluebill1049 If I want to append array elements without any input, then I cant do it with RHF? So in the form state, I have an 'exercises' array in which are elements, and in each element is another array for example 'exerciseSets' where the inputs exist.

**Comment by bluebill1049** [comment]
@dancixx this is working with V7, you can append without actual inputs. Hook form will register them on your behalf.

**Comment by dancixx** [comment]
@bluebill1049 It is just working with setValue. If I use the append method will be added into the form state but the fields don't update, I can get the updated array with the watch method only, the other problem is with the remove method I get sometimes empty objects after the remove, it seems the remove delete the parent object and copy the nested field array again into the state.

**Comment by bluebill1049** [comment]
> @bluebill1049 It is just working with setValue. If I use the append method will be added into the form state but the fields don't update, I can get the updated array with the watch method only, the other problem is with the remove method I get sometimes empty objects after the remove, it seems the remove delete the parent object and copy the nested field array again into the state.

send me a codesandbox with more context (steps to reproduce)

**Comment by dancixx** [comment]
@bluebill1049 https://codesandbox.io/s/priceless-dijkstra-4j4vv?file=/src/App.tsx

I hope this is helps to solve my issue.

**Comment by bluebill1049** [comment]
you are append a number? `<button key={index} onClick={() => append(i)}>` you should append an object for your inputs' defaultValues.

**Comment by dancixx** [comment]
i is the ith object in the sample data. :)

**Comment by dancixx** [comment]
@bluebill1049 I can reproduce my code. I want something like that.
https://codesandbox.io/s/priceless-dijkstra-4j4vv?file=/src/App.tsx
