### ISSUE TITLE
Set message to pattern 

### ISSUE THREAD

**Issue by ajay-dev-j** [react-hook-form/react-hook-form#561]
**I always have a problem to set the message in the pattern validation. So I will move to validate often**
Validation using pattern works like a charm. But setting the message for the same is not available for me. I especially using UI library reactstrap. 

**Set msg like validate for pattern would be great**
I like to add my code snippet to get more details of what exactly am facing.

useEffect(() => {
        register({ name: "location_name" },
            {
                required: 'location_name is required',
                validate: 
                    value => value === 'aj' ? 'Location name is bad' : true
                
            }
        );
.....

useEffect(() => {
        register({ name: "email" },
            {
                required: 'Email is required',
                pattern: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/
            }
        ); // Set a message here like 'Email is bad'

**Comment by bluebill1049** [comment]
hey @ajay-dev-j 

first of all, you should try to use react-hook-form-input https://github.com/react-hook-form/react-hook-form-input for controlled components.

also, you can append message in during register: https://react-hook-form.com/api#register
<img width="892" alt="Screen Shot 2019-11-25 at 6 37 17 pm" src="https://user-images.githubusercontent.com/10513364/69521252-a2507a80-0fb2-11ea-8a46-8aa02f63b1b2.png">

**Comment by ajay-dev-j** [comment]
@bluebill1049  Glad!! that I got a response from you. I am a huge fan of react-hooks-form. When I started to learn this, I somehow missed this react-hook-form-input repo. Anyway, I got the point to solve my case. But a small clarification here is like Can we set the message for pattern without RHFinput? Do we really need this new repo of this simple use-case(my case)?

**Comment by bluebill1049** [comment]
hey @ajay-dev-j for simple usage no :) you don't need react-hook-form-input at all for simple task :) you can register with value and message for your need.

**Comment by bluebill1049** [comment]
going to close this issue :) if you find this lib useful please support us by leaving a star for the lib. thanks in advance
