### ISSUE TITLE
Field using `setValueAs` deemed dirty even though no user interaction has changed it

### ISSUE THREAD

**Issue by larrifax** [react-hook-form/react-hook-form#5611]
**Describe the bug**
I'm using `setValueAs` in combination with `<input type="date" />` in order to use `Date` objects both in and out of my forms.

When focusing and subsequently blurring such an input, it is incorrectly marked as "dirty".
This may be due to [updateTouchAndDirtyState ](https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L317-L320) using `inputValue` directly instead of using `getFieldValueAs` on the value.

**To Reproduce**

1. Go to 'https://codesandbox.io/s/infallible-haze-xgf1i?file=/src/App.tsx'
2. Click on 'Submit' and look in the console. Verify that both `touched` and `dirty` are empty - as they should be.
3. Focus the input field and blur it without making any changes to it
4. Click on 'Submit' and look in the console. Now the input is shown as both `touched` and `dirty` - even though it's only been touched.

**Codesandbox link (Required)**
https://codesandbox.io/s/infallible-haze-xgf1i?file=/src/App.tsx

**Expected behavior**
The input should only be marked as dirty when the user has actually changed the field

**Comment by bluebill1049** [comment]
thanks for the detailed issue report. it really helps.

**Comment by larrifax** [comment]
Thanks a bunch! Did some quick tests on the new version, and it seems to have fixed my problem. Will report back if it turns out that it doesn't.

Once again, thanks for the quick response time! 🥇
