### ISSUE TITLE
Checkbox and Radio inputs not converted to number type

### ISSUE THREAD

**Issue by dsbrianwebster** [react-hook-form/react-hook-form#5617]
**Describe the bug**
Checkbox and Radio types dot work with `valueAsNumber`

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-register-ts-forked-okcvv?file=/src/App.tsx

**Expected behavior**
To be converted to Number

**Desktop (please complete the following information):**
- Browser [e.g. chrome]

**Comment by bluebill1049** [comment]
<img width="923" alt="Screen Shot 2021-06-16 at 8 45 33 am" src="https://user-images.githubusercontent.com/10513364/122132978-375de180-ce7f-11eb-88b9-9b157f824638.png">

limited to input text only.

**Comment by dsbrianwebster** [comment]
![image](https://user-images.githubusercontent.com/8154653/122255539-38513c00-ce9c-11eb-8974-34b02bef7eed.png)

**Comment by bluebill1049** [comment]
@dsbrianwebster I think if you want to convert the checkbox value, it's better to build a controlled component and then wrapped with Controller. so you have the full control.
