### ISSUE TITLE
Allow setting defaultValue via `register` method

### ISSUE THREAD

**Issue by GProst** [react-hook-form/react-hook-form#562]
Imagine there is a custom input, MUI Select, that has 2 options 'Cats' and 'Dogs' and it doesn't have an empty option (like 'None') so you always have to provide some value.
I believe a current solution is to provide a default value to `useForm` method and then retrieve the value using `watch` which works fine when the form is static.

But let's say we have a form where you can dynamically add/remove inputs, providing defaultValues to `useForm` in this case isn't convenient (and perhaps won't work?) since we can't know in advance how many Selects there will be.
As a possible workaround you could use `setValue` with a default value right after you register a custom field. But this makes a form dirty which is bad.

Also, even for static forms, I think it would be just nicer if we didn't have to provide default values for all fields in one place.

**Solution**
An ability to provide default values for a specific field during its registration (this probably will override default value provided to `useForm` for this specific field if such was provided there):
```js
register({ name: 'myField' }, { defaultValue: 'Bob' })
```
This feels intuitive to me and seems like a logical thing to allow.

Thanks!

**Comment by bluebill1049** [comment]
hey @GProst you can now use `react-hook-form-input` and combined with `defaultValues`

**Comment by GProst** [comment]
@bluebill1049 yeah, I wanted to use it but I don't see `defaultValues` props in readme. How do I provide it to MUI Select for example.
`defaultValues` for uncontrolled inputs makes sense.

But don't you think if we could provide default value to `register` method it would be more universal solution and wouldn't require to install `react-hook-form-input` library?

**Comment by bluebill1049** [comment]
> @bluebill1049 yeah, I wanted to use it but I don't see `defaultValues` props in readme. How do I provide it to MUI Select for example.
> `defaultValues` attribute for uncontrolled inputs makes sense.
```
useForm({
 defaultValues: {
   test: 'data'
 }
})
```

**Comment by bluebill1049** [comment]
> But don't you think if we could provide default value to `register` method it would be more universal solution and wouldn't require to install `react-hook-form-input` library?

yea, but this lib focus is on uncontrolled component, building react-hook-form-input was try to closer the gap between controlled components such as MUI, react-select and Antd. it wasn't framework specific.

**Comment by GProst** [comment]
@bluebill1049 okay, I got you.
But my problem is that I don't know the name of the field initially.
Let's say I have fields structure like this:
```js
{
  animals: [
    {name: 'Scratchy', type: 'Cat'},
    {name: 'Scrappy', type: 'Dog'}
  ]
}
```
And I can add as many animals in the form as I want (dynamically). How do I set default values for fields which indexes I don't know yet? Provide default values for 1000 fields in advance to be safe?
But this tricky workaround won't solve it if I structure fields based on their local unique ID (I can't know it in advance):
```js
{
  animals: {
    "setr341f": {name: 'Scratchy', type: 'Cat'},
    "5lgf45sa": {name: 'Scrappy', type: 'Dog'}
  }
}
```

**Comment by bluebill1049** [comment]
@GProst can you use `defaultValue` during render?

**Comment by GProst** [comment]
@bluebill1049 I currently use `watch` for each field and if it's `undefined` I use a defaltValue.
But I don't think I can use this approach with `react-hook-form-input`, at least currently.
So I thought that providing `defaultValue` to `register` will make my code cleaner and my life better 😄

**Comment by bluebill1049** [comment]
hey @GProst as much as I want to make your life easier, I think I will leave second argument just for validation for API consistency (simple API). a bit tired today, you want to supply codesandbox of your issue. I will spend sometime tmr for an alternative solution. 👍

**Comment by GProst** [comment]
@bluebill1049 cool, will do 👍

**Comment by GProst** [comment]
Okay, while I was preparing the Sandbox example I realized that the problem I have won't be solved by providing default value`register` method since at initial render it will be `undefined` anyway. And the problem is in `watch` behavior. I'll open another issue
