### ISSUE TITLE
Regression:  Default values are not propagated in useFieldArray (after v.7.2.3)

### ISSUE THREAD

**Issue by mak-elena** [react-hook-form/react-hook-form#5628]
**Describe the bug**
Default values supplied in the **useForm** are not priovider to the inputs rendered for the fields from **useFieldArray**

**To Reproduce**

For  the reproduction I used the examplle of Controlled Field Array from  the documentation (https://react-hook-form.com/api/usefieldarray).

The only modification: I extended defaultValues with an array of values: 

``````
  const { register, handleSubmit, control, watch } = useForm<FormValues>({
    defaultValues: {
      firstName: "test",
      fieldArray: [
        {
          name: "test 1",
          value: 2
        },
        {
          name: "test 2",
          value: 3
        },
        {
          name: "test 3",
          value: 5
        }
      ]
    }
  });
  const { fields, append } = useFieldArray({
    control,
    name: "fieldArray"
  });
``````

1.  Select the dependency version **react-hook-form@7.2.3**
2. Restart the app
3. Result: all the input fields are **filled wit defautl values**
4. Select the latest version  of **react-hook-form** (or any one newer than 7.2.3)
5. Restart the app
6. Result: The input fields related to the field array are **empty**

**Codesandbox link (Required)**
https://codesandbox.io/s/controlled-field-array-forked-jyxuh

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome

**Comment by bluebill1049** [comment]
Thanks for the detailed issue, because all the input didn't provide `defaultValue` and they r required. 

https://react-hook-form.com/api/usefieldarray

> defaultValue must be set for all inputs. Supplied defaultValues in the useForm hook will prepare the fields object with default value.
