### ISSUE TITLE
defaultValue passed to `watch` overrides defaultValues passed to `useForm` at first render

### ISSUE THREAD

**Issue by GProst** [react-hook-form/react-hook-form#563]
`watch` method picks up a default value provided to it instead of picking up the values set in `useForm` and seems like this happens only at initial render.
This makes it problematic to work with dynamic fields for me.

Here is a Sandbox example: https://codesandbox.io/s/dynamic-custom-fields-f5w03
Note that initially both animals have `Cat` type despite the defaultValue for the second animal was set to `Dog` in `useForm`.
As soon as you click 'Add animal' button you'll see that it gets fixed.

**Expected behavior**
I'd expect that `defaultValue` in watch method will be used only in cases when it wasn't set in `useForm` method.

Thanks!

**Comment by bluebill1049** [comment]
hey @GProst the idea was use either watch `defaultValue` or useForm's `defaultValues`. right now in the code defaultValue overwrites defaultValues. i guess it makes sense as it's inner than useForm. I will take a look at this issue tho, see if we can fix it by implementation before changing the lib itself.

**Comment by bluebill1049** [comment]
hey @GProst i don't see any watch usage in your codesandbox example.

**Comment by GProst** [comment]
Hey @bluebill1049, it's in Animal.jsx file

**Comment by GProst** [comment]
@bluebill1049 I was thinking that perhaps implementing 'expected' behavior for `watch` method I described isn't the right thing to do after all.
Just thinking out loud but perhaps the second argument to `watch` method is some redundant/confusing thing? It's a bit mixed that we define default values when we start watching field values.
I think if we had a way to update defaultValues set in `useForm` it would be a clearer solution for my problem:
```js
const {updateDefaultValues, ...} = useForm(...);

const addAnimal = () => {
  const localId = Date.now();
  updateDefaultValues(defaultValues => ({
    animals: {
      ...defaultValues.animals,
      [localId]: {name: '', type: 'Cat'}
    }
  }));
  setAnimalsIds([...animalsIds, localId]);
};
```
I think this could make it nicer to work with dynamic fields not only for custom fields but for uncontrolled inputs too.

**Comment by bluebill1049** [comment]
This is my attempt: https://codesandbox.io/s/react-hook-form-field-array-advanced-l19pz

**Comment by GProst** [comment]
@bluebill1049 yeah, this would work too but `RHFInput` doesn't accept `defaultValue` for controlled components like MUI Select for example (judging by the README). If such prop existed there it would be nice.

Under the hood for controlled inputs I believe it would look something like that:
```js
let value = watch(fieldName);
value = typeof value === 'undefined' ? defaultValue : value
...
```
Cause you can't do `const value = watch(fieldName, defaultValue);` if there is some defaultValue set to `useForm`.
So, I still think it would be nicer and less confusing to dynamically update defaultValues provided to `useForm` but if `RHFInput` could accept `defaultValue` prop for controlled fields it'd be good enough for me.

**Comment by GProst** [comment]
@bluebill1049 dang, should have checked it. Seems like it works with `defaultValue` for MUI Select...

**Comment by bluebill1049** [comment]
if everything goes well, then i will clean up the demo and upload to the website to help others for similar issues.

**Comment by GProst** [comment]
@bluebill1049 seems like this works smoothly, thanks for the help!

**Comment by bluebill1049** [comment]
going to close this issue here, i will follow up to add more information on the website.
