### ISSUE TITLE
UseFieldArray error typing

### ISSUE THREAD

**Issue by Rinta01** [react-hook-form/react-hook-form#5638]
**Describe the bug**

When using **typescript**, **useFieldArray** and **yup** as a validator, library types do not recognise error message property on the array. Code still works, but only with // @ts-ignore. 

**To Reproduce**

Create a form using useFieldArray.
Set a validation rule on the array (e.g. min or required).
Try to access errors.ARRAY.message property to visualise the error
Typescript will show an error

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-go28t

V7.8.1

**Expected behaviour**
Typescript should correctly type the errors object

**Desktop**

- OS: Windows 10
- Browser: Chrome
- Version: 79

**Comment by bluebill1049** [comment]
missing generic type at useForm.

**Comment by Rinta01** [comment]
@bluebill1049 Forgot to add it to the sandbox. Had it in my project. Behaviour is still the same. Am I missing something?

**Comment by FPDK** [comment]
@Rinta01 Did you solve your problem? And can you elaborate on how you did it?

**Comment by bluebill1049** [comment]
missing the notification the object look up should be 

`errors.array?.[0].firstName.message`

**Comment by FPDK** [comment]
@bluebill1049 Thank you, however my issue was related to https://github.com/react-hook-form/resolvers/issues/245  - I've followed your fix in that topic and it works :)
