### ISSUE TITLE
Smart Form Component and validate function

### ISSUE THREAD

**Issue by waynebrantley** [react-hook-form/react-hook-form#564]
First of all - I would like to congratulate you on a great library and docs!

I have implemented smart forms similar to these:
https://codesandbox.io/s/react-hook-form-smart-form-component-eqb3n
(Note this codesandbox link from your docs does not actually use smartform components or even work)

As we pass in a custom validate function to something like ``<Input/>`` we need access to the rest of the values on the form.  For example, if I were to build a password changing screen - where the two passwords would have to match - with smart form components, the validate function would need access to things from the form.  It would need the values from the form.  It might want the touched values, etc.

What I wanted to propose was to add a 2nd parameter to the validate function.  At a minimum the 2nd parameter would be  ``getValues`` function - that a validator function could call if it needed them.  At max, the 2nd parameter would be an object that contained ''all' of the functions from UseForm() call.   That might be overkill, but we do need the getValues() function - and I could see people wanting 'touched'.  (no since in comparing and showing an error for passwords not matching until both fields are touched.  

Thoughts on this idea or another suggestion?

**Comment by waynebrantley** [comment]
While I think it would be an advantage to do what I suggested above, one possible workaround in the meantime is to use smart 'components' but not a smart 'form'.   Doing something like this would give you access to ``methods.getValues()`` to use in the validator functions.

```import React from 'react'
import { Form, Input, Select } from './Components';

export default function App() {
  const onSubmit = data => console.log(data);
  const methods = = useForm()

  return (
    <>
      <h1>Smart Form Component</h1>
      <form onSubmit={methods.handleSubmit(onSubmit)}>
        <Input name="firstName" {...methods}/>
        <Input name="lastName" {...methods}/>
        <Select name="sex" options={["female", "male"]} {...methods}/>

        <Input type="submit" value="Submit" {...methods}/>
      </form>
    </>
  );
}
```

**Comment by bluebill1049** [comment]
> I have implemented smart forms similar to these:
> https://codesandbox.io/s/react-hook-form-smart-form-component-eqb3n
> (Note this codesandbox link from your docs does not actually use smartform components or even work)

Thanks for the note 👍 i have fixed the codesandbox ❤️ 

https://codesandbox.io/s/react-hook-form-smart-form-component-eqb3n

**Comment by bluebill1049** [comment]
> What I wanted to propose was to add a 2nd parameter to the validate function. At a minimum the 2nd parameter would be `getValues` function - that a validator function could call if it needed them. At max, the 2nd parameter would be an object that contained ''all' of the functions from UseForm() call. That might be overkill, but we do need the getValues() function - and I could see people wanting 'touched'. (no since in comparing and showing an error for passwords not matching until both fields are touched.

Not this stage, i don't have any plan to introduce any more argument (keep the api simple)

**Comment by bluebill1049** [comment]
> While I think it would be an advantage to do what I suggested above, one possible workaround in the meantime is to use smart 'components' but not a smart 'form'. Doing something like this would give you access to `methods.getValues()` to use in the validator functions.
> 
> ```
> import { Form, Input, Select } from './Components';
> 
> export default function App() {
>   const onSubmit = data => console.log(data);
>   const methods = = useForm()
> 
>   return (
>     <>
>       <h1>Smart Form Component</h1>
>       <form onSubmit={methods.handleSubmit(onSubmit)}>
>         <Input name="firstName" {...methods}/>
>         <Input name="lastName" {...methods}/>
>         <Select name="sex" options={["female", "male"]} {...methods}/>
> 
>         <Input type="submit" value="Submit" {...methods}/>
>       </form>
>     </>
>   );
> }
> ```

I personally didn't like the spread operator, it creates an issue to overwrite or gets overwrote.

**Comment by bluebill1049** [comment]
if you need full access of methods from hook form, i will recommend still using smart form but combined with https://react-hook-form.com/advanced-usage#ConnectForm.

**Comment by waynebrantley** [comment]
Trying to avoid the re-render and not use the connectForm.   When we write a simple validator like change password - where two fields need to be the same, we need access to the other values.  We find this happens much of the time.  What is the problem with having an optional second parameter where the useForm things can be provided so the validator can do what it needs?   We can do the example like I showed above - essentially making it 'smart components', not smart forms....but seemed like adding this new object would be easy and keep api simple?

As far as the spread operator goes, I do agree.  However, in the above example, each component simply needs register - so I could not spread it.  However, if I am wrapping react-select, that one needs ``setValue`` and ``register``.  If I am wrapping my custom 'submitbutton', that one needs ``isSubmitting``.   If I make those required, I cannot use them inside a 'smart form' for the simple use case - so it makes it much more difficult to use the components?

If you would make a smart form that did a password validation - I think you would see the pain point that we would often encounter...and the ConnectForm would be good, just was avoiding what appeared to be a rending problem (and/or potentially complex code on when to re-render).

I guess if we used yup, then your native support of that handles this, I just think you have potentially left out a common scenario.  I know other apis are not a reason to do anything, but Formik, final-form and redux-form all pass the full value list into the validator too...(which is probably where I got the idea).

Interested in your thoughts - as it is, looks like smart 'components' instead of a smart 'form' are the way to go as many of our forms need the values from the other fields to do validations.

Thanks for considering!

**Comment by bluebill1049** [comment]
thanks for the detailed reply. I don't think i am killing the functionality to get the entire form state. you can still call `getValues()` inside the validate function (just not within the smart form approach which I did).

**Comment by bluebill1049** [comment]
in terms of connecting form. you don't have to connect every field only the ones that you want to use `getValues()`. you probably will need to use ConnectForm anyway when your UI gets more complicated and not all inputs are at the root level of your form.

**Comment by bluebill1049** [comment]
by the way I am not killing your idea here. I am considering like every new API

**Comment by bluebill1049** [comment]
This is what i used at work

```
<FormWizard onNext={onNext}>
      <FormTitle>{name}</FormTitle>

      <InputCurrency
        label="Extra cash out"
        errorMessage={{
          required: 'This is required',
          maxValue: `Must be $${convertNumberToCurrency(MAX_PROPERTY_VALUE)} or less`,
          minValue: `Must be $${convertNumberToCurrency(MIN_DEPOSIT_BORROW_AMOUNT)} or more`,
        }}
        name="cashOutAmount"
        required
      />

      <ConnectForm>
        {({ formState, formProps, formProps: { errors } }) => {
          const { cashOutAmount } = formProps.watch(['existingLoanAmount', 'cashOutAmount']);

          return (
            <>
              <InputCurrency
                label="Current loan balance"
                errorMessage={{
                  required: 'This is required',
                  maxValue: `Must be $${convertNumberToCurrency(MAX_PROPERTY_VALUE)} or less`,
                  minValue: `Must be $${convertNumberToCurrency(MIN_DEPOSIT_BORROW_AMOUNT)} or more`,
                }}
                register={formProps.register}
                errors={formProps.errors}
                name="existingLoanAmount"
                description="Exclude your offset balance"
                required
                validate={{
                  maxValue: value => !validateMaxCurrencyInput(value),
                  minValue: value => convertStringToNumber(value) >= MIN_DEPOSIT_BORROW_AMOUNT,
                  isLessThanMinLoanAmount: value => isLessThanMinLoanAmount(value, cashOutAmount),
                  moreThanTotalLoanAmount: value => moreThanTotalLoanAmount(value, cashOutAmount),
                }}
              />
            </>
          );
        }}
      </ConnectForm>
</FormWizard>
```

**Comment by waynebrantley** [comment]
That works - I had not considered a ConnectForm inside the same form!  I was hoping for something a little cleaner.  In this case, you would not need ConnectForm or render props or watch statement if your validator could ask for the values of the form

I really do like how the conenctForm works and that is super power to make things integrate nicely - was just (perhaps overly) concerned about any performance issues...

And I agree you might have to connect anyway - but large use case is other values.  Maybe if I were to use ``Yup`` this would not be an issue as it has access to other field values I guess?

**Comment by bluebill1049** [comment]
I am not expert with `yup` but you can try it out.

**Comment by bluebill1049** [comment]
i am going to close this issue, but i will add a todo list in the project as to be considered.

**Comment by bluebill1049** [comment]
you can find it here: https://github.com/react-hook-form/react-hook-form/projects/1

**Comment by tafelito** [comment]
I have a similar requirement where  I need to compare 2 passwords to be the same. 

What would be the problem accessing the getValues from the validate function?

```js
const { register, errors, handleSubmit, getValues } = useForm();
...
<TextField
  name="email"
  label="EMAIL"
  fullWidth
  ref={register({ required: true })}
/>
{errors.email && 'E-mail is required'}
<TextField
  name="confirmEmail"
  label="CONFIRM EMAIL"
  ref={register({
    required: true,
    validate: value => getValues().email === value,
  })}
/>
```

If using Yup this can be done using [`when` ](https://github.com/jquense/yup#mixedwhenkeys-string--arraystring-builder-object--value-schema-schema-schema)

**Comment by bluebill1049** [comment]
@tafelito you are doing correctly :) using `getValues` is right 👍

**Comment by siam88** [comment]
@bluebill1049  in the smart form component you send the register in ref of  a custom input but how could I validate that input or pass the validations in register


https://codesandbox.io/s/react-hook-form-smart-form-component-uocr9?file=/src/components.js:773-781

**Comment by bluebill1049** [comment]
@siam88 pass `rules` as props. rules can contain your validation logic.

**Comment by siam88** [comment]
@bluebill1049 I tried it to send as props. but whenever I am putting the rules inside the register it is saying that register is not a function . can you please help me out or show me any demo on how to resolve this 


https://codesandbox.io/s/react-hook-form-smart-form-component-m0n70?file=/src/components.js

**Comment by bluebill1049** [comment]
@siam88 https://codesandbox.io/s/react-hook-form-smart-form-component-17k06?file=/src/index.js

**Comment by siam88** [comment]
@bluebill1049  thanks a lot now it works for me <3

**Comment by jatinrathod17** [comment]
@bluebill1049 I got how to put rules to the component but how can we add error for each input, can you please share working copy for that?

**Comment by bluebill1049** [comment]
> @bluebill1049 I got that how to put rules to the component but how can we add error for each input, can you please share working copy for that?

what do you mean by adding errors? isn't that you just read from the `errors` object?

**Comment by jatinrathod17** [comment]
I mean for seperate input components how I do show error.
