### ISSUE TITLE
How can i set defaultValue and How can i use setValue in React Native

### ISSUE THREAD

**Issue by hakanozkaptan** [react-hook-form/react-hook-form#565]
I have an input and ref like this
**ref={register({ name:'firstName' }, validations)}**

setValue('firstName', 'John Doe');

setValue givin' an undefined..
const {
    register, setValue, handleSubmit, errors, getValues,
  } = useForm({
    mode: 'onBlur',
    defaultValues: {
      firstName: 'Hakan Ozkaptan',
    },
  });

How can set a value onPress and initial value on react native

**Comment by bluebill1049** [comment]
you have two solutions here when it come to setValue and reset: 
`watch()` to turn your form into controlled
or 
using `react-hook-form-input`

https://github.com/react-hook-form/react-hook-form-input

**Comment by hakanozkaptan** [comment]
Thanks man.

**Comment by bluebill1049** [comment]
pleasure :)

**Comment by peterkuiper** [comment]
@bluebill1049 The final argument to `useEffect` should be an array, ie:
```
useEffect(() => {
  register({ name: 'test' });
}, [register])
```
```Warning: useEffect received a final argument that is not an array (instead, received `function`). When specified, the final argument must be an array.```

I can't seem to get it to work though. Can you perhaps share a working example for React Native?

**Comment by bluebill1049** [comment]
@peterkuiper you saw this section: https://react-hook-form.com/get-started#ReactNative?

**Comment by peterkuiper** [comment]
@bluebill1049 Yes, I did. The problem is that I want to set default values on a custom text input component. I tried the `useEffect` method but that does not work. The code example from the section you mentioned works, but I need to set value. The form is being used to update existing data.

**Comment by bluebill1049** [comment]
@petercpwong have you tried react-hook-form-input?

**Comment by petercpwong** [comment]
@bluebill1049 I think you responded to the wrong person :)

**Comment by bluebill1049** [comment]
oops sorry my bad :( @peterkuiper

**Comment by peterkuiper** [comment]
@bluebill1049 I have not (yet). I will check that out, hopefully that will work. It would still be great to have a working example in your docs, though (your documentation is excellent).

**Comment by bluebill1049** [comment]
thanks @petercpwong i have expo link in the code example. 
<img width="1236" alt="Screen Shot 2019-12-10 at 8 10 06 am" src="https://user-images.githubusercontent.com/10513364/70473110-7e4d7700-1b24-11ea-94fb-7b50528ec1e1.png">
