### ISSUE TITLE
Field Array - fields won't update after changing a field

### ISSUE THREAD

**Issue by knoefel** [react-hook-form/react-hook-form#5658]
**Describe the bug**
Not 100% sure if it is bug or intended behaviour, but when i edit an item (some input) of a field array, `fields` won't reflect those changes. Only after i alter the fields array (for example with `remove` or `add`) then the fields array will have those previous changes. I also tried using `mode: "onChange"` or using `watch`, but this doesn't helped.

**To Reproduce**
1. Open [CodeSandbox](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-0cc27?file=/src/index.js)
2. Edit any input of the first field array item
3. Check console that although using `watch` and `mode: "onChange"` the value isn't updated
4. remove the second field array item
5. now `fields` have the changes

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-0cc27?file=/src/index.js

**Expected behavior**
When editing a field array item the changes will be updated immediately.

Thanks for your feedback!!

**Comment by bluebill1049** [comment]
> Check console that although using watch and mode: "onChange" the value isn't updated

please read the doc, mode is for validation. use watch or useWatch if you want to subscribe to the changes.

**Comment by knoefel** [comment]
Thanks for the answer. I already used `watch` in my example but it doesn't reflect the changes after editing a field array item. I removed mode: 'onChange', here is the updated [CodeSandbox](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-ocu0u?file=/src/index.js).

**Comment by bluebill1049** [comment]
you should log what's returned by `watch`, fields are only meant to return default input value, I think you are confused with Controlled field array vs uncontrolled filed array.

**Comment by knoefel** [comment]
Aaah yes, you're right. 😳 Thanks for the clarification!
