### ISSUE TITLE
How to submit the form outside the form 

### ISSUE THREAD

**Issue by eranabir** [react-hook-form/react-hook-form#566]
we have a case that we want to submit the form outside the form element 
how can we do that ?

**Comment by bluebill1049** [comment]
as long as your useForm() is outside

you can do 

````
const { handleSubmit } = useForm();

<button onClick={handleSubmit((d) => console.log(d))} />

<form>

</form>
```

please consider ask general question at our specturm channel

**Comment by eranabir** [comment]
thanks but our use case is a little bit different 

we have a common component BaseForm : 

````
function BaseForm2({onSubmit, render,defaultValues}){
    const methods = useForm({defaultValues});
    return (
        <form onSubmit={methods.handleSubmit(onSubmit)}>
            {render(methods)}
        </form>
    )
}
````
and we use it like this : 

````
function CustomerForm({onSubmit, getFormMethods}){
    return (
        <BaseForm2
            getFormMethods={getFormMethods}
            onSubmit={onSubmit}
            render={({register}) =>
                <input name='name.firstName' type='text' ref={register}/>
            }/>);
}
````
now we want to submit the form not inside the render function

**Comment by bluebill1049** [comment]
you may want to consider to use `FormContext`. so you can move `useFrom` out from the inner Component.

**Comment by bluebill1049** [comment]
going to close this question in here, feel free to leave more questions or prefer to answer it in specturm then other community members can helps too.

**Comment by asciant** [comment]
For those who come across this issue like I did, and found it didn't quite address the question. You can submit a form programatically by passing a ref to the `form` DOM element and then dispatching a _cancelable_ event:

```
formRef.current.dispatchEvent(new Event('submit', { cancelable: true }))
```

This will trigger the `onSubmit` handler via the RHF `handleSubmit` method.

**Comment by chellongCoder** [comment]
thanks, you save my day @asciant

**Comment by dgtlmonk** [comment]
`getValues()` seems to work as well.

```js
onSubmit(formData)  {
 ....
}
```

**Comment by neighborhood999** [comment]
I solved this issue by HTML attribute, e.g:

```jsx

const { handleSubmit } = useForm();
const onSubmit = data => {
	console.log(data);
};

//...

<form id="hook-form" onSubmit={handleSubmit(onSubmit)}>
	{/* your awesome form */}
</form>

<button type="submit form="form="hook-form"">Submit</button>
```

**Comment by bluebill1049** [comment]
Thanks @neighborhood999 for sharing solutions.

**Comment by Katochimoto** [comment]
Also can use `useImperativeHandle`

```js
const BaseForm = forwardRef(({ onSubmit, render, defaultValues }, ref) => {
    const methods = useForm({defaultValues});
    const handleSubmit = methods.handleSubmit(onSubmit);

    useImperativeHandle(ref, () => ({
        submit () {
            handleSubmit()
        },
    }))

    return (
        <form onSubmit={handleSubmit}>
            {render(methods)}
        </form>
    )
})


function CustomerForm({onSubmit, getFormMethods}){
    const refFrom = useRef()
    return (
      <>
        <BaseForm
            ref={refFrom}
            getFormMethods={getFormMethods}
            onSubmit={onSubmit}
            render={({register}) =>
                <input name='name.firstName' type='text' ref={register}/>
            }
        />
        <button onClick={() => refFrom.current.submit()}>Submit</button>
      </>
    );
}
```

**Comment by bluebill1049** [comment]
Thanks for sharing @Katochimoto

**Comment by pzi** [comment]
> 1. If you don't have access to the `handleSubmit` method. You can submit a form programatically by passing a ref to the `form` DOM element and then dispatching a _cancelable_ event:
> 
> ```
> formRef.current.dispatchEvent(new Event('submit', { cancelable: true }))
> ```
> 


This seemed to have stopped working in the recent release(s). Use the below to get it to work again:
> ```
> formRef.current.dispatchEvent(new Event('submit', { cancelable: true, bubbles: true }))
> ```

**Comment by andidev** [comment]
> as long as your useForm() is outside
> 
> you can do
> 
> ```
> const { handleSubmit } = useForm();
> 
> <button onClick={handleSubmit((d) => console.log(d))} />
> 
> <form>
> 
> </form>
> ```
> 
> please consider ask general question at our specturm channel

Just thought I mention that there is an error here that caused me some confusion. There handleSubmit returns a function that needs to be called. So `()` is missing at the end.

```html
<button onClick={handleSubmit((d) => console.log(d))()} />
```

**Comment by bluebill1049** [comment]
> > as long as your useForm() is outside
> > you can do
> > ```
> > const { handleSubmit } = useForm();
> > 
> > <button onClick={handleSubmit((d) => console.log(d))} />
> > 
> > <form>
> > 
> > </form>
> > ```
> > 
> > 
> > please consider ask general question at our specturm channel
> 
> Just thought I mention that there is an error here that caused me some confusion. There handleSubmit returns a function that needs to be called. So `()` is missing at the end.
> 
> ```
> <button onClick={handleSubmit((d) => console.log(d))()} />
> ```

we have this on the doc: https://react-hook-form.com/api#handleSubmit have a look there 👍 

<img width="895" alt="Screen Shot 2020-12-15 at 10 17 32 am" src="https://user-images.githubusercontent.com/10513364/102147367-c08b6000-3ebe-11eb-99c6-3ab81b258477.png">

**Comment by xmd5a** [comment]
Well in my opinion the cleanest solution is just using prepared by lib authors hook: [`useFormContext()`](https://react-hook-form.com/api/#useFormContext) + [`handeSubmit`](https://react-hook-form.com/api/#handleSubmit)

You guys should avoid @Katochimoto solution using imperative code. Event docs is saying about avoiding this kind of solutions 
https://reactjs.org/docs/hooks-reference.html#useimperativehandle

**Comment by Maaasyn** [comment]
My solution is quite simple, trigger programmatically hidden submit button. You can pass this fn down, use it in useEffect etc.

```jsx
const myForm = () => {

  const refSubmitButtom = useRef<HTMLButtonElement>(null);
  const { handleSubmit } = useForm();

  const triggerSubmit = () => {
    refSubmitButtom?.current?.click();
  };

  const submitHandler = (data: any) => {
    console.log(data);
  }

  return (
    <>
    <form onSubmit={handleSubmit(submitHandler)}>
       {/* your form goes here */}
      <button hidden={true} ref={refSubmitButtom} type={"submit"} />
    </form>
    </>
  )
}
```

**Comment by bluebill1049** [comment]
Thanks @Maaasyn for sharing solution.

**Comment by corysimmons** [comment]
`form.handleSubmit(yourHandleSubmitFunction)()`

**Comment by dpejic** [comment]
Thanks @asciant on `handleSubmit(onSubmit)()`


> For those who come across this issue like I did, and found it didn't quite address the question.
> 
> You have two options:
> 
> 1. If you don't have access to the `handleSubmit` method. You can submit a form programatically by passing a ref to the `form` DOM element and then dispatching a _cancelable_ event:
> 
> ```
> formRef.current.dispatchEvent(new Event('submit', { cancelable: true }))
> ```
> 
> This will trigger the `onSubmit` handler via the RHF `handleSubmit` method.
> 
> 1. If you have access to the `handleSubmit` method. You can call `handleSubmit` and immediately invoke/execute the function programatically:
> 
> ```
> handleSubmit(onSubmit)()
> ```
> 
> Happy days!

**Comment by JavaJamie** [comment]
I have a similar issue, but need access to the isValid, isSubmitting etc in a different component where the submit button is?

**Comment by squidis** [comment]
When using `<button type="submit" onClick={handleSubmit((d) => console.log(d))()}>Submit</button>` in Storybook, React throws an error "Warning: Expected `onClick` listener to be a function, instead got a value of `object` type.
button".

**Comment by kasongoyo** [comment]
> For those who come across this issue like I did, and found it didn't quite address the question.
> 
> You have two options:
> 
> 1. If you don't have access to the `handleSubmit` method. You can submit a form programatically by passing a ref to the `form` DOM element and then dispatching a _cancelable_ event:
> 
> ```
> formRef.current.dispatchEvent(new Event('submit', { cancelable: true }))
> ```
> 
> This will trigger the `onSubmit` handler via the RHF `handleSubmit` method.
> 
> 1. If you have access to the `handleSubmit` method. You can call `handleSubmit` and immediately invoke/execute the function programatically:
> 
> ```
> handleSubmit(onSubmit)()
> ```
> 
> Happy days!

For some reasons, this seems to be slow like there is a huge lag between when the event get fired up to when the onSubmit is called. Weird and I can't use it for that reason

**Comment by hoaiphong99** [comment]
> I solved this issue by HTML attribute, e.g:
> 
> ```js
> const { handleSubmit } = useForm();
> const onSubmit = data => {
> 	console.log(data);
> };
> 
> //...
> 
> <form id="hook-form" onSubmit={handleSubmit(onSubmit)}>
> 	{/* your awesome form */}
> </form>
> 
> <button type="submit" form="hook-form">Submit</button>
> ```

thank you <3

**Comment by michaeljarizala** [comment]
> I solved this issue by HTML attribute, e.g:
> 
> ```js
> const { handleSubmit } = useForm();
> const onSubmit = data => {
> 	console.log(data);
> };
> 
> //...
> 
> <form id="hook-form" onSubmit={handleSubmit(onSubmit)}>
> 	{/* your awesome form */}
> </form>
> 
> <button type="submit" form="hook-form">Submit</button>
> ```

You are heaven sent 🙏

**Comment by bar-coder** [comment]
I stumbled upon this problem yesterday, but in React Native, where the `<form>` element is not available.
The approach I adopted makes use of the combination of `FormProvider` (provided by `react-hook-form`) & a couple of JS goodies. I'll share it here, in case could be helpful to someone.

**WRAPPER COMPONENT**
```
import React from 'react';
import {Button} from 'react-native';
import { FormProvider, useForm } from 'react-hook-form';

import NestedForm from '/path/to/NestedForm' ;

const FormsWrapper = () => {
    const methods = useForm();

    return (
        <FormProvider {...methods}>
                <NestedForm identifier="form_one" />
                <NestedForm identifier="form_two" />
                <NestedForm identifier="form_three" />

                <Button
                    onPress={methods.handleSubmit(data => console.log(data))}
                    title="Submit Form"
                />
        </FormProvider>
    );
};

export default FormsWrapper;
```
**NESTED FORM COMPONENT**
```
import React from 'react';
import {Text, TextInput, View} from 'react-native';
import { useFormContext, Controller } from 'react-hook-form';

const NestedForm = ({ identifier }) => {
    const ctx = useFormContext();

    // Destructuring here because in initial render 'useFormContext' was returning null
    if (!!ctx) {
        var {
            control,
            formState: {errors}
        } = ctx;
    }

    return (
        <View>
            <Text style={{fontWeight: 'bold', marginTop: 24}}> { identifier } </Text>

            <Controller
                control={control}
                rules={{ required: 'Field required', /* or any other validation rule */ }}
                render={({ field }) => (
                    <TextInput
                        {...field}
                        placeholder="First name"
                        onChangeText={field.onChange}
                    />
                    // or any other form element
                )}
                name={`first_name_${identifier}`}
            />
            { 
                 !!errors[`first_name_${identifier}`] &&
                 <Text style={{color: 'red'}}> {errors[`first_name_${identifier}`].message} </Text>
            }

            {/* Basically any other controller similar to the previous one, e.g. one named `last_name_${identifier}` */}
        </View>
    );
};

export default NestedForm;
```
Supposing having another `Controller` named precisely `last_name_${identifier}` the resulting object after submission (click on `Button` in _parent_ component) would be:
```
{
	"first_name_form_one": "...",
	"last_name_form_one": "...",
	"first_name_form_two": "...",
	"last_name_form_two": "..."
	"first_name_form_three": "...",
	"last_name_form_three": "...",
}
```
Then, since there are some repetitions, one could simply reduce the result into an object having each form identifier as root fields, for example.

Maybe this solution can be further optimized, but it works. Oh, and even though I haven't tested it, it should work in React too.

**Comment by Enache-Ionut** [comment]
> I solved this issue by HTML attribute, e.g:
> 
> ```js
> const { handleSubmit } = useForm();
> const onSubmit = data => {
> 	console.log(data);
> };
> 
> //...
> 
> <form id="hook-form" onSubmit={handleSubmit(onSubmit)}>
> 	{/* your awesome form */}
> </form>
> 
> <button type="submit" form="hook-form">Submit</button>
> ```

This is awesome 🚀 Thank you!

**Comment by ahmadalfy** [comment]
Why doesn't `form.current?.submit()` work? It trigger submit and refreshing of the page ...
