### ISSUE TITLE
Several validations triggers whenever formState is used after v7.1.1

### ISSUE THREAD

**Issue by guilhermeocosta** [react-hook-form/react-hook-form#5660]
**Describe the bug**
After [this PR](https://github.com/react-hook-form/react-hook-form/pull/5415), any changes to the `formState` triggers validations (including the async ones) several times to other fields as you can see in this [CodeSandbox](https://codesandbox.io/s/nice-volhard-jgf92?file=/src/App.js).

**To Reproduce**

1. Go to [CodeSandbox](https://codesandbox.io/s/nice-volhard-jgf92?file=/src/App.js);
2. Open the console;
3. Fill the "Email" field;
4. Start typing into the "Full name" field;
5. The validation (and the console.log at line 35) will trigger at every `formState` update

**Codesandbox link (Required)**
[https://codesandbox.io/s/nice-volhard-jgf92?file=/src/App.js](https://codesandbox.io/s/nice-volhard-jgf92?file=/src/App.js)

**Expected behavior**
Updating the value of other fields shouldn't re-trigger validations.

**Desktop (please complete the following information):**

- OS: OSX Catalina
- Browser: Chrome
- Version: 91.0.4472.101

**Comment by bluebill1049** [comment]
This is expected. Like I mentioned in the PR, please refer to the pros and cons. In the end, the current solution proposes much stable and less error-prone for isValid `formState` and having a single source of truth for the output.

**Comment by FlorianBurgevin** [comment]
Hello. @bluebill1049 

Filling the fullname field trigger validation of email field again ?

This is weird no ?

**Comment by guilhermeocosta** [comment]
> Hello. @bluebill1049
> 
> Filling the fullname field trigger validation of email field again ?
> 
> This is weird no ?
> 
> I have the same problem with my form. I built an async validation for an email field, but filling and even focus an other input trigger the email validation API to be called.
> It's a problem :/

What do I recommend as long as the maintainer seems to see this as expected behavior is to store the latest validated value into the async function to avoid unnecessary re-validations.

**Comment by FlorianBurgevin** [comment]
@guilhermeocosta, I get around the problem by counting `formState.errors` keys.
If no keys, the form is valid and that not re-trigger validations.
