### ISSUE TITLE
Trigger throws an error when used with useFieldArray

### ISSUE THREAD

**Issue by phenrique7** [react-hook-form/react-hook-form#5661]
**Describe the bug**
The manual validation via `trigger` throws an error when the `useFieldArray` field name is passed as a parameter (string or array). The `trigger` validation on all fields works normally.

**To Reproduce**

1. Go to Codesandbox
2. Click on button "Trigger Contacts" or "Trigger User Name and Contacts"
3. See error `TypeError: (destructured parameter)._f is undefined`

**Codesandbox link**
https://codesandbox.io/s/delicate-star-ficbs

**Expected behavior**
It should not fail and should validate `useFieldArray` fields.

**Desktop**

- OS:  Ubuntu
- Browser: Firefox
- Version: 89.0.1

**Comment by bluebill1049** [comment]
`trigger` for the object node is not supported, you can upvote this feature request: https://github.com/react-hook-form/react-hook-form/issues/2381

I will pack this error throw tho.
