### ISSUE TITLE
useFieldArray with useFormContext doesn't work properly

### ISSUE THREAD

**Issue by niteshgrg** [react-hook-form/react-hook-form#5671]
**Describe the bug**
I looked into previous issue as well (https://github.com/react-hook-form/react-hook-form/issues/1198) but for me i am using controllers for inputs so cannot use register(). 

**To Reproduce**
Easily reproducible with any formContext and fields with controller. Sorry if there is any clear cut syntax on how to use controllers with context and i am missing it.

Steps to reproduce the behaviour:
1. Create a fieldArray from formContext and inputs registered with Register input with controller
2. Add few fields with append() and remove with remove()
3. Submit data it becomes empty.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-3zd6g?file=/src/index.js

**Comment by bluebill1049** [comment]
What's the issue here? Can u elaborate the expectation? If I append once and delete, obviously the date is going to be empty.
