### ISSUE TITLE
Re-introduce onFocus on Controller

### ISSUE THREAD

**Issue by aximusnl** [react-hook-form/react-hook-form#5674]
**Is your feature request related to a problem? Please describe.**
In 7.0.0 `onFocus` has been removed from `Controller`, in favour of using `ref` for a better developer experience. But using `ref` is limited. It forced us to drop focussing as a whole.

**Describe the solution you'd like**
I would like to propose to re-introduce `onFocus` for complex form elements. Such as form fields that, under the hood, are composed of multiple form fields. Or form fields where manually controlling the focus is important.

**Describe alternatives you've considered**
I don't see a clear alternative.

**Additional context**
No additional context

**Comment by bluebill1049** [comment]
`onFocus()` is the same as `ref()` the only difference is before you need to invoke it manually, now if the component forward ref correctly then it will work out of the box.

**Comment by aximusnl** [comment]
`onFocus()` gives me full manual control, where `ref()` can only be placed on one input element.

**Comment by aximusnl** [comment]
What works is

```
		ref({
			focus: () => {
				// your custom focus logic
			},
		});
```

But i'm not sure if it has side effects

**Comment by bluebill1049** [comment]
that's fine @aximusnl

**Comment by sepruda** [comment]
I am struggling hard to properly focus on errors, for my controlled react-select components. Could either of you provide a working example, I don't understand the syntax provided above. Thanks!

**Comment by bluebill1049** [comment]
> I am struggling hard to properly focus on errors, for my controlled react-select components. Could either of you provide a working example, I don't understand the syntax provided above. Thanks!

It should work by default now. can you provide a none working example, because `{ field }` from `Controller` does contain `ref` inside now.

**Comment by sepruda** [comment]
I couldn't reproduce it in a codesandbox, so might have to do with the UI library we're using (which in turn is using `react-select`) - works fine just passing ref through from `field`.
