### ISSUE TITLE
setValue can not update array data when its has defaultvalue. 

### ISSUE THREAD

**Issue by tonyYo00** [react-hook-form/react-hook-form#5677]
**Describe the bug**
setValue can not update array data when its has defaultvalue. its also happen in useFieldArray  ,when remove row, [object] will lost

**To Reproduce**

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

 https://codesandbox.io/s/controlled-field-array-forked-xjfl9?file=/src/App.tsx

just click submit and see the log.

- Browser [browser,]
- Version [7.88]

**Comment by tonyYo00** [comment]
![Peek 2021-06-18 17-45](https://user-images.githubusercontent.com/79240024/122542320-25399a00-d05d-11eb-9b40-15dfe1e485c5.gif)

**Comment by bluebill1049** [comment]
we don't support `undefined` for `defaultValues`.

**Comment by bluebill1049** [comment]
what's the steps to reproduce the issue in your CSB?
