### ISSUE TITLE
reset({}, { keepDefaultValues: true }) with useController clears out input's value but keeps form value

### ISSUE THREAD

**Issue by JGibel** [react-hook-form/react-hook-form#5687]
**Describe the bug**
calling reset with keepDefaultValues clears default values (with useController).

**To Reproduce**

1. Create form with an input created with useController. Default value can be provided on the useForm level or inline.
2. Call reset({}, { keepDefaultValues: true })
3. The value passed to the input gets set to undefined. a watch on the field value does not change.

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

V7

- [JS](https://codesandbox.io/s/react-hook-form-v7-customise-controller-return-value-forked-e3mm4?file=/src/index.js) CSB
 You can reproduce in this sandbox by hitting the reset button. The value updated log statement shows the value passed to the input ref, the field updated statement shows the form's value.

**Expected behavior**
input value and form value should match. This does not impact the value passed to submit. Just keeps showing the annoying react error warning message.

**Screenshots**

**Desktop (please complete the following information):**
Don't think it matters, but here's mine:
- OS: [macOS (Big Sur)]
- Browser [Chrome]
- Version [Version 91.0.4472.106 (Official Build) (x86_64)]
**Additional context**
Not a real issue as far as I can tell, but those react error messages are polluting my logs and make it difficult to debug.

**Comment by bluebill1049** [comment]
Fixed, thanks.
