### ISSUE TITLE
Off-by-1 error with watch + custom validation

### ISSUE THREAD

**Issue by hbarcelos** [react-hook-form/react-hook-form#569]
First of all, I am sorry if this has been answered before. I have looked for closed issues with similar problems, but couldn't find any with the very same problem.

**Describe the bug**
I have to check for password strength in my form and disallow weak passwords.

I've created a separate module to calculate the strength of a given password and return a string (more like an enum) that says if it is a weak, average or strong password.

Then in my component I have `const password = watch('password')` and use this to calculate the strength:

```js
const passwordStrength = useMemo(() => calculatePasswordStrength(password), [
    password
  ]);
```

To prevent users from submitting a weak password, I have done this:

```jsx
<input
  name="password"
  type="password"
  ref={register({
    required: "Required",
    validate: () => {
      return passwordStrength !== StrengthLevels.WEAK || "Too weak";
    }
  })}
/>
```
However, what I observe if that the validation is always off-by-1:
- When the password becomes average, the validation error "Too weak" it still there
- When the password is average and then becomes weak, there's no error message
- When toggling between weak and average passwords, the "Too weak" message shows when the strength is average and hides when it is weak
- If the input is blurred, then the validation updates itself and is correct (which is good, because it will prevent form submission, but still, the UI won't reflect what is going on).

**To Reproduce**
1. Go to the sandbox link bellow.
2. Click on the rendered "Send" button.
3. Start typing in the password input. It will be considered average with 5 or more characters.
4. After getting "average", remove one character to get back to "weak" and see that the error message is not there.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-issue-with-validation-xhdyw

**Expected behavior**
Validation and the helper text should be in sync.

**Screenshots**
Here's a screencast of the behavior.

![react-hook-form-issue](https://user-images.githubusercontent.com/16565602/69646494-af1eae00-1046-11ea-92d8-e42e272b259d.gif)

**Desktop:**
 - OS: Linux (Manjaro)
 - Browser: Firefox
 - Version: 70.0.1 (64-bits)

**Comment by bluebill1049** [comment]
thanks @hbarcelos for the detailed error report. i will be looking into this.

**Comment by bluebill1049** [comment]
I am bit confused with the usage:

```
validate: () => {
  console.log("validate:", passwordStrength
  return passwordStrength !== StrengthLevels.WEAK || "Too weak";
}
```
instead
```
validate: (value) => {
  return value === 5 || 'test'
}
```
?

**Comment by hbarcelos** [comment]
That's because the validation is not derived from the password itself, it is a memoized value that is calculated previously by a another module.

**Comment by bluebill1049** [comment]
I haven't look too close, but I think it's because your value is stored above render. so it's 1 render behind.

**Comment by hbarcelos** [comment]
Yeah, I'm not sure yet.

In this case there's no problem because `checkPasswordStrength` is not a heavy algorithm, so there's no problem running it again.

Any ideas on how I could tackle this if one cannot run the same check twice?

**Comment by bluebill1049** [comment]
> Any ideas on how I could tackle this if one cannot run the same check twice?

can you elaborate on this? the other solution i could think of is doing the check by adding your own event listener (onChange, onBlur) and you can trigger validation whenever you like.

**Comment by hbarcelos** [comment]
> can you elaborate on this?

I have already calculated `passwordStrength` here because **I need to show it on screen**:

```js
  const password = watch('password');
  const passwordStrength = useMemo(() => checkPasswordStrength(password), [password]);
```

Doing like in my latest version it works:

```js
          validate: value => checkPasswordStrength(value) !== StrengthLevels.WEAK || 'Too weak',
```

Now let's imagine that `checkPasswordStrength` function is expensive. Running it twice would be wasteful.

I am wondering if there's a way I could reuse the same `passwordStrength` for validation.

I'll give it a try with `triggerValidation` and let you know the results.

**Comment by bluebill1049** [comment]
hey @hbarcelos valid point, I used debounce at work, will that work for you?

**Comment by najandz** [comment]
Hey @hbarcelos 
I was wondering if you found a solution to your problem. I am working on a password strength component and want to know how to display the user's strong password message.
