### ISSUE TITLE
useFieldArray append marks all entry IDs dirty

### ISSUE THREAD

**Issue by jovermier** [react-hook-form/react-hook-form#5692]
**Describe the bug**
useFieldArray append marks all existing entries IDs in the dirtyFields array as dirty when appending to the fields array.

**To Reproduce**
1. Click Submit and see console log dirtyFields = {}
2. Click Append and notice new entry in field array
3. Click Submit and see console log dirtyFields = {test: [
0: {id: true, firstName: undefined, lastName: undefined},  **<- SHOULD NOT  HAVE TRUE ID**
1: {id: true, firstName: undefined, lastName: undefined}, **<- SHOULD NOT HAVE TRUE ID**
2: {firstName: true, lastName: true }, **<- MISSING ID**
]}

**Codesandbox link (Required)**
https://codesandbox.io/s/clever-murdock-b08i1

**Expected behavior**
- The dirtyFields array should only have true on properties that change. All other unmodified array entries should not have an id marked as dirty.
- Inserted entries should have the id property marked as dirty.

Suggested dirty structure A:
dirtyFields = {test: [
0: {},
1: {},
2: {id: true, firstName: true, lastName: true }
]}

Suggested dirty structure B:
dirtyFields = {test: {
'2': {id: true, firstName: true, lastName: true }
}}
Note: When you change the ID it would be equivalent to doing a delete and append. Not sure if this behavior is ideal for all use cases.

**Desktop (please complete the following information):**

- OS: Win10
- Browser: Edge
- Version: 91.0.864.48

**Comment by bluebill1049** [comment]
This is expected behavior, we are doing a deep comparison with your `defautlValues` of the current form values. There is no filter or anything like that, wroth to mention input's default is the empty string for standard input.
