### ISSUE TITLE
useFieldArray: values from conditional fields doesn't get reset when these fields are unmounted

### ISSUE THREAD

**Issue by trueboris** [react-hook-form/react-hook-form#5696]
Thanks to contributors for the great form library!

**Describe the bug**
Values from some conditional fields doesn't get reset when these fields are unmounted using useFieldArray from react-hook-form v6.8.4.

**To Reproduce**

1. Change question type to "rate" from "select".
2. Note that fields related to "select" type of question are unmounted.
3. See printed form values. Values related to options doesn't exist as expected.
4. Values "selectionMin" and "selectionMax" are still present despite that these 2 fields "selectionMin" and "selectionMax" are conditional.

**Codesandbox link (Required)**
https://codesandbox.io/s/epic-edison-h1k7e?file=/src/App.js

**Expected behavior**
Values "selectionMin" and "selectionMax" should not exist in form values after conditional fields are unmounted. 

**Additional context**
I tried to use 7.8.x version in working project, but had the same behavior. If CSB for 7.x.x is needed, I can provide an example.

**Comment by bluebill1049** [comment]
can you share a v7 example?

**Comment by bluebill1049** [comment]
with v7 if you set to `shouldUnregister: true`, can you still reproduce the issue?

**Comment by trueboris** [comment]
Here is an example of using `v7.9.0`. I set `shouldUnregister: true` in `useForm` and in `useFieldArray`. 

I see that unmounting 2 inner inputs of first `field` from `useFieldArray` leads to removing values of these inputs as expected. But If I remove same inputs of next `fields` from `useFieldArray`, only 1 of 2 values of these 2 fields gets removed.

**To Reproduce**
Steps to reproduce the behavior:

1. Change first question's type to `rate` from `select`. Note that values of unmounted inputs are gone.
2. Click `Add question`.
3. Change added question's type to `rate` from `select`. Note that value for 2nd input named `selectionMax` still exists, but value for 1st input named `selectionMin` is gone.

**Codesandbox link (Required)**
https://codesandbox.io/s/pedantic-waterfall-2gtb5?file=/src/App.js

**Expected behavior**
Value from unmounted input named `selectionMax` should be reset.

**Comment by bluebill1049** [comment]
I have spent quite a bit of time investigating this issue, I think it's a limitation with deeply nested object field with `shouldUnreigster` and `useFieldArray`, to have consistent behavior for the data output, I would recommend using `unregister` method, for the more stable and correct result. You could try to break into sub `useFieldArray`, which may resolve the issue as well.

here is a working CSB: https://codesandbox.io/s/flamboyant-lewin-qi2cn?file=/src/src/useForm.ts

```tsx
<select
  {...type}
  onChange={(e) => {
    type.onChange(e);
    unregister(`questions.${questionIndex}.payload`);
  }}
>
```

**Comment by trueboris** [comment]
> I have spent quite a bit of time investigating this issue, I think it's a limitation with deeply nested object field with `shouldUnreigster` and `useFieldArray`, to have consistent behavior for the data output, I would recommend using `unregister` method, for the more stable and correct result. You could try to break into sub `useFieldArray`, which may resolve the issue as well.
> 
> here is a working CSB: https://codesandbox.io/s/flamboyant-lewin-qi2cn?file=/src/src/useForm.ts
> 
> ```tsx
> <select
>   {...type}
>   onChange={(e) => {
>     type.onChange(e);
>     unregister(`questions.${questionIndex}.payload`);
>   }}
> >
> ```

thanks for you support and quick answer!

**Comment by bluebill1049** [comment]
I appreciate your politeness and understanding.
