### ISSUE TITLE
Validating everything with `shouldFocus` is not focusing

### ISSUE THREAD

**Issue by kaisermann** [react-hook-form/react-hook-form#5699]
**Describe the bug**
After a form is validated via `trigger(undefined, { shouldFocus: true })`, an input with error is not focused.

**To Reproduce**

See codeSandbox below

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-v6-triggervalidation-forked-n27ch?file=/src/index.js

1 - Click validate all
2- First name input should be focused but it's not

**Expected behavior**
First input with error should be focused.

**Additional context**

I did some investigation and it seems that we're sending `[undefined]` as `fieldNames` [here](https://github.com/react-hook-form/react-hook-form/pull/4960/files#diff-07a36f93b9f2954db217ab021a0444c89c5fabc9506b8c390db329e5e74b9f06R496), which renders [this short circuiting](https://github.com/react-hook-form/react-hook-form/pull/4960/files#diff-e38717710e219df75e4b10c7622ecc6f1595c2e49601cc643a9e9bf2980030b2R12) useless, since `fieldsNames` is always truthy. 

Replacing the condition with something like the code below made it work.

```ts
  const fieldList =
    fieldsNames && Array.from(fieldsNames).length > 0
      ? fieldsNames
      : Object.keys(fields);
  for (const key of fieldList) {
```

**Comment by kaisermann** [comment]
Introduced on: https://github.com/react-hook-form/react-hook-form/commit/c26533fc746b9f73b937b3c951a38b7677a9c21f#diff-07a36f93b9f2954db217ab021a0444c89c5fabc9506b8c390db329e5e74b9f06R441

**Comment by bluebill1049** [comment]
thanks for the PR!
