### ISSUE TITLE
FormBuilder for react-hook-form customization

### ISSUE THREAD

**Issue by KKS1** [react-hook-form/react-hook-form#5711]
Can FormBuilder be exposed by this library ( or pls point to the source code for website). 

We are trying to see if Form builder can also be provided via applications, to have dynamic forms, which can be later customized by admins, on the fly. 

On such solution is https://github.com/rjsf-team/react-jsonschema-form, but that is JSON driven and becomes complex for non-technical folks. 

Thus, looking forward to see if there is any suggestion we can use react-hook-form, alongside keeping dynamic functionality in place with FormBuilder or JSON.

**Comment by bluebill1049** [comment]
Take a look at the public site repo.

**Comment by KKS1** [comment]
Can I pls have link for public site repo?

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/documentation

**Comment by cyril36** [comment]
Hello,

I am interesting about using the react-hook-form to generate the jsonschema-form

@bluebill1049 Can you point the part of the documentation that talks about it, i did not find it?

@KKS1 Did you do any development on this sense?

Thank you

**Comment by KKS1** [comment]
> Hello,
> 
> 
> 
> I am interesting about using the react-hook-form to generate the jsonschema-form
> 
> 
> 
> @bluebill1049 Can you point the part of the documentation that talks about it, i did not find it?
> 
> 
> 
> @KKS1 Did you do any development on this sense?
> 
> 
> 
> Thank you

Not really, as we ended up creating an in house solution with HTML forms.

**Comment by bluebill1049** [comment]
someone made a package: https://github.com/vtex/react-hook-form-jsonschema

**Comment by cyril-moreau** [comment]
I dont want to generate a form from a jsonschema file, I would like to do the opposite.
I would like to generate a jsonschema based on the the builder-form from react-hook-form website when clicking on the button "save"
