### ISSUE TITLE
shouldUnregister arguments: function or boolean

### ISSUE THREAD

**Issue by branrhino** [react-hook-form/react-hook-form#5726]
**Is your feature request related to a problem? Please describe.**
It would be great that we could pass a function to validate if we want to unregister the field at that moment. Ex: If we are changing to a new step we don't want to unregister it but if we are dismounting the field because of the previous answers of the form change the behaviour then we might not need that field anymore. In that case we truly want to unregister the field

**Describe the solution you'd like**
Send a function or a boolean to the shouldUnregister prop

**Code Example**
`<input
  {...register("test", {
    shouldUnregister: ()=>{
    if(age >= 18) return false
    return true
    },
  })}
/>`

**Comment by bluebill1049** [comment]
Please consider to use unregister method combined with a local state to unmount the input. A config or function return is not enough.
