### ISSUE TITLE
Add new method, set, to useFieldArray

### ISSUE THREAD

**Issue by jhg023** [react-hook-form/react-hook-form#5728]
### Is your feature request related to a problem? Please describe.
I have a dynamic form that uses `useFieldArray`.

When a form element is changed by the user, I currently call `remove` (to remove the element from the array at a specific index) and then `insert` (using the same index) within a `useEffect` (as invoking `insert` immediately after `remove` does not work according to the documentation).

This results in the form flickering for a brief moment when the row is removed and inserted, as it happens over multiple renders.

### Describe the solution you'd like
I would like a mechanism to set the value of an element in the `fields` array at a specific index **and have it re-render immediately** in order to avoid the flicker.

### Describe alternatives you've considered
I've spent a lot of time trying to get it to work using `setValue`, but that method does not update the `fields` array, nor does it result in a re-render.

I've tried it using both controlled and non-controlled inputs as well, to no avail.

### Additional context
I was surprised that this functionality didn't already exist, as all of the other methods already do (`append`, `insert`, `remove`, etc.)

I could probably fix the issue by introducing an additional state to track the fields as they're changed, but then I would just remove `useFieldArray` at that point, as it wouldn't be providing any benefit.

**Comment by bluebill1049** [comment]
here is the RFC for the new API: https://github.com/react-hook-form/react-hook-form/discussions/5832

**Comment by sgranadosa** [comment]
Hello, Can you tell me what is the correct use of Update? 
I try to use it in a dynamic way, on a useEffect when I catch a field that should not be Required I updated the field like this to fill the value: 
update(conditionIndex, [])
but if its required i updated the structure needed update(conditionIndex, [{value: ''}]);
However, with this approach in the UI for some reason, I got 2 inputs and not 1. 
Is not like the new update rewriting over the last value as I would expect. 
So am I implementing it wrong?

**Comment by bluebill1049** [comment]
@sgranadosa can you share a codesandbox and ask a question in the Github discussion?
