### ISSUE TITLE
Add isValidating by field

### ISSUE THREAD

**Issue by young666** [react-hook-form/react-hook-form#5744]
**Is your feature request related to a problem? Please describe.**
I implement a spinner when the field is validating. I use `isValidating` from `formState` and this will trigger loading for every fields.

**Describe the solution you'd like**
We need `isValidating` from `fieldState` the same as `isDirty`, it could be trigger by field, and we should have `isValidatingFields` in case of we don't to use `Controller`.

**Describe alternatives you've considered**
At the moment, I have to use `trigger` and implement `isValidatingFields` using React State. When I manually trigger the validation, I will `setState` the field.

**Additional context**
This is my UI screenshot when doing this feature.
![image](https://user-images.githubusercontent.com/9252925/123512622-a96dcc00-d6b2-11eb-8685-a7cade9a1cd2.png)

**Comment by bluebill1049** [comment]
thanks for the feature request.

I would recommend using: 

- useFormState at your component level
- useController (like what you suggested) above.

i will still ping this feature on our feature board for sometimes, see if other users have similar requests.

**Comment by davbrito** [comment]
This is a feature that I definitely would like to see in RHF soon. 👍🏽

**Comment by bluebill1049** [comment]
thanks, @davbrito thinking about this, would it be easier to host a local state (i guess if you are using `useController` hook).

**Comment by konarssuresh** [comment]
> thanks, @davbrito thinking about this, would it be easier to host a local state (i guess if you are using `useController` hook).

There is a similar use case in my project . @bluebill1049 . Can you show me a example how to do it using useController and state.
Will isValidating prop be added at fieldState in useController ?

**Comment by nathanqg** [comment]
@konarssuresh did you manage to solve this? I'm also looking for a way to display the validation status per field.

**Comment by thenano** [comment]
I would also love this feature. 
In my case, I use a yup schema with the yup resolver and an async api call to validate the field (specifically we check if the handle is available or not). I want to explicitly set a message below the field only when that field is validating, not when the rest of the form is validating, and since yup handles the validation it's pretty tricky to add this as a local state.

**Comment by kyledevans** [comment]
Was this feature added?  I see a couple bugs that are asking for this that have been closed, but I don't see how this can be accomplished.

**Comment by WhiteMaskVarre** [comment]
this is good feature if we are dealing with multiple asynchronous form , either way it might cause pending ui to appear on another input , it would be great if you add this feature

**Comment by MatthewTang** [comment]
Another vote for this feature! Thanks a lot, really like this library!
