### ISSUE TITLE
Typescript error with triggerValidation

### ISSUE THREAD

**Issue by lundn** [react-hook-form/react-hook-form#575]
**Describe the bug**
I'm unsure if this is just my setup, or not. The documentation clearly states that triggerValidation can be supplied with empty argument. However, this produces an error with the Typescript definition.

**Desktop**:
OS: macOS mojave
React-Native: iOS iPhone XS (12.1) simulator
Typescript: 3.4.1
react-hook-form: 3.28.4

**Screenshots**
![image](https://user-images.githubusercontent.com/4386964/69711504-78f23480-1101-11ea-931c-7c04387d635d.png)

**Additional context**
I see now that there is a difference between the typings for `useForm` and `FormContext`. Is this intentional?

**Comment by bluebill1049** [comment]
> I see now that there is a difference between the typings for useForm and FormContext. Is this intentional?
This is not intentional, should be patched.

<img width="607" alt="Screen Shot 2019-11-27 at 9 33 17 pm" src="https://user-images.githubusercontent.com/10513364/69716172-a10f8100-115d-11ea-87f7-3d3cd171ba68.png">

it's definitely optional

**Comment by bluebill1049** [comment]
feel free to send a PR to correct the type between useForm and formContext. useForm is most updated.
