### ISSUE TITLE
`setValue` doesn't update an array properly

### ISSUE THREAD

**Issue by JuanM04** [react-hook-form/react-hook-form#5766]
**Describe the bug**
Updating arrays with `setValue` works in a weird fashion when there are a default array.

**To Reproduce**

1. Make a form.
2. Add a array value like `number[]`.
3. Add a default value to it, like `[3,1,4]`.
4. Use `setValue` and `watch` to update the values (check out the Codesanbox for a better example). 

**Codesandbox link**
https://codesandbox.io/s/elastic-chebyshev-2jlxu?file=/src/Forms.tsx

**Desktop (please complete the following information):**

- OS: Fedora 34
- Browser: Brave (Chromium-based)
- Version: 91

**Additional context**
Previously mentioned [here](https://github.com/react-hook-form/react-hook-form/issues/5724#issuecomment-867706511).

**Comment by JamesWong1999** [comment]
What's the steps to reproduce the issue? and what's the expected result?

**Comment by bluebill1049** [comment]
> What's the steps to reproduce the issue? and what's the expected result?

@JuanM04 can you elaborate on the above?
