### ISSUE TITLE
object `errors` missing from `useFormContext(...)`

### ISSUE THREAD

**Issue by senal** [react-hook-form/react-hook-form#5767]
**Describe the bug**
I was using RHF V 6.15.1 and accessing `errors` object from `useFormContext(...)`
But with the latest version V: 7.9.0

**To Reproduce**
Having 2 applications reference both versions will provide evidence.

**Expected behavior**
Get access to `errors` object from `useFormContext(...)` would be convenient when the child components wrapped within a `<FormProvider>` 

I could be missing something from the new version of RHF API. Any advice or feedback highly appreciated.

**Comment by bluebill1049** [comment]
formState: { errors }
