### ISSUE TITLE
Use with AMD CommonJs

### ISSUE THREAD

**Issue by lyvyu** [react-hook-form/react-hook-form#578]
Hey there guys,

I'm working on a project which is compiled with kotlin and has a old architecture. So there basically is AMD with RequireJs and CommonJs therefore I cannot use the library with ES6 import and stuff. Is there anything I could do to use this library this way ?!

**Comment by bluebill1049** [comment]
u want to try the ie 11 version? https://react-hook-form.com/faqs#BrowserSupport

**Comment by lyvyu** [comment]
Hey, thanks for the blazing fast response !!!
Unfortunately now I'm getting useForm is not a function error.

I did copied the ie11 file and added to my project, defined it in requirejs.config like so: 
```
require.config({
...
'react-hook-form': 'resources/js/react-hook-form'
...
})
```

**Comment by bluebill1049** [comment]
i will take a look AMD stuff tmr for you, hopefully it's not too tricky...

**Comment by lyvyu** [comment]
Thanks man, ur awesome !!!

**Comment by bluebill1049** [comment]
`3.28.8-beta.1` with 

`react-hook-form.amd.js`

i am probably not going to include this in the future build tho :)

let me know if that works for you. 👍

**Comment by lyvyu** [comment]
Sir, you are a LEGEND !!!
Thank you very much for the time and effort in helping me with problem !!!

**Comment by bluebill1049** [comment]
hope it works 👍 no worries
