### ISSUE TITLE
It is not a typescript error to access an incorrect field on the errors object.

### ISSUE THREAD

**Issue by mkellyclare** [react-hook-form/react-hook-form#579]
**Describe the bug**
It is not a typescript error to access an incorrect field on the errors object. In the [typescript section of the docs](https://react-hook-form.com/api#TypeScript) - there is a line that should demonstrate this behaviour and a comment indicating that a typescript error should be there.
```javascript
errors.bill; // ❌: property bill does not exist
```
However, when testing locally on in the linked sandbox, there is no typescript error on this line.

**To Reproduce**
1. Go to the [typescript section of the docs](https://react-hook-form.com/api#TypeScript)
2. Click on the code sandbox link
3. Expect to see typescript error on line 29

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-typescript-mm

**Expected behavior**
If I try and access a field in the errors object that is not defined, this should be a typescript error.

**Comment by bluebill1049** [comment]
your codesandbox is empty: https://codesandbox.io/s/react-hook-form-typescript-mm can you supply one?

**Comment by mkellyclare** [comment]
Strange, it looks like the typescript section of the docs has been removed. The code sandbox was the one linked directly from that.

I had copied the example from the docs locally, here is a codesandbox with the code that was in that example before it was removed that demonstrates the issue - https://codesandbox.io/s/red-dawn-xgn9l

**Comment by bluebill1049** [comment]
@mkellyclare not removed, migrated to get started page

**Comment by bluebill1049** [comment]
hey @stramel would you be able to help on this?

**Comment by bluebill1049** [comment]
@stramel any update on this issue?

**Comment by iangregsondev** [comment]
Probably not helpful, but locally I am also seeing the same issue. As per the docs I create a type 

```
type FormData = {
  email: string
}
```

And using 

```
  const { register, handleSubmit, watch, errors } = useForm<FormData>()
```

And this does not highlight any issue, but it should as its not on the type.

```
console.log(errors.somethingNotThere)
```

This was created the latest version and I am using vscode.

**Comment by bluebill1049** [comment]
i am looking into this over the weekend @iangregsondev. let me know @stramel if you have worked on it already i can branch off what you left off.
