### ISSUE TITLE
defaultValues not available to nested fields in a fieldArray

### ISSUE THREAD

**Issue by mgerring** [react-hook-form/react-hook-form#5799]
**Describe the bug**
If I have a field array, and the field array renders a custom component that contains one or more fields, and I use useFormContext within that custom component, that component's fields will not have default values set automatically, even though the form correctly handles the default values.

**To Reproduce**
- Create a form wrapped with FormProvider
- Provide default values to useForm
- Create a field array
- Within the fieldArray's fields, render a custom component that wraps one or more form inputs
- Access the form context inside the custom component via useFormContext
- Register the fields in the custom component

**Codesandbox link (Required)**
https://codesandbox.io/s/serene-cartwright-y7s8p?file=/src/App.js

**Expected behavior**
I expect the fields in the custom component to have their default values set

**Desktop (please complete the following information):**

- macOS
- Firefox
- latest stable as of 6/30/2021

**Comment by bluebill1049** [comment]
<img width="1083" alt="Screen Shot 2021-07-01 at 9 25 34 am" src="https://user-images.githubusercontent.com/10513364/124043395-4b443e80-da4e-11eb-9f5a-69d71475b26e.png">
