### ISSUE TITLE
support register required to have value & message

### ISSUE THREAD

**Issue by thomb** [react-hook-form/react-hook-form#580]
**Describe the question?**
It appears that there is an typescript definition for the `required` and `message` strings inside of the `register` block when used with `react-i18next`

**To Reproduce**
Attempting to use the `t` function `useTranslation` in the following manner...
```
import useForm from 'react-hook-form';
import {useTranslation} from 'react-i18n';
export const simpleForm = () => {
  const {t} = useTranslation()
  const {handleSubmit, register}  = useForm()
  return (
    <form onSubmit={handleSubmit((data:unknown) => {}>
        <input
          name="lastName"
          placeholder="Luo"
          ref={register({
            required: t('thisIsRequired'),
            minLength: {
              value: 2,
              message: t('minLengthIsTwo'),
            },
          })}
        />
    <button type="submit" />
   </form>
  )
}
```
results in the following typescript error (full output has been truncated):
```
Type 'TFunctionResult' is not assignable to type 'string | boolean | undefined'.
  Type 'null' is not assignable to type 'string | boolean | undefined'.
```

Is it possible to support translated strings inside of these register definitions?

**Comment by bluebill1049** [comment]
could please you provide me with a TS codesandbox? 👍

**Comment by thomb** [comment]
Here ya go:
https://codesandbox.io/s/elated-sun-3i559

**Comment by bluebill1049** [comment]
looks like the problem is not with this lib, rather than what `t("doesNotWork")` returns, it returns `TFunctionResult` rather than `string`. Do you want to raise an issue at that repo?

**Comment by bopfer** [comment]
I think the difference is that `TFunctionResult` includes `null` is it's union and in `react-hook-form` it is only `boolean | string | undefined`.  See https://github.com/react-hook-form/react-hook-form/blob/master/src/types.ts#L74

Not sure what the proper solution is though.  Adding `null` to that line would make it work.

I don't see them changing `TFunctionResult` since the `t` function does more than handle just strings.

**Comment by bluebill1049** [comment]
oh wow @bopfer thanks for the info! i will give it a try with null, see if it will solve the problem.

**Comment by bluebill1049** [comment]
hey @thomb it's not the best, but looks like you will have to use `required: t("doesNotWork") as string,`

because in RFH you can register without message, `register({ required: true })` which is what conflict with `TFunctionResult` (only support string)

**Comment by thomb** [comment]
@bluebill1049 I had assumed this would be the case after examining the typing. What would be your response to me logging a feature request to disambiguate the types in the structure itself?

ie.

```
{
  required: boolean,
  requiredMessage: string,
}
```

In general it feels like a better practice to have your structures be declarative, as opposed to having a single variable represent vastly different meanings. 

This is more a preference, and I do understand the conciscion (and familiarity you with existing types) you are going for... but without a pattern like this (or something better), localization with your lib is a bit of a PITA, and I would probably decide against using it.

All preferences aside:
```
        <input
          name="lastName"
          placeholder="Luo"
          ref={register({
            required: t("doesNotWork") as string,
            minLength: {
              value: 2,
              message: t("stillWorks") as string
            }
          })}
        />
```

as an implementation guideline is not overly cumbersome, should be serviceable for a wider audience.

**Comment by bluebill1049** [comment]
thanks @thomb 
```
        <input
          name="lastName"
          placeholder="Luo"
          ref={register({
            required: t("doesNotWork") as string,
            minLength: {
              value: 2,
              message: t("stillWorks")
            }
          })}
        />
```

FYI: you don't need type casting for `message`

i think alternative i can make a change for the lib itself for required to support value and message

```
required: {
  value: true,
  message: t("doesNotWork")
},
```

**Comment by thomb** [comment]
@bluebill1049 Good to know about `message`, apologies for my misunderstanding.

Would you like me to log a feature request for this or do you have it in hand? I mainly just want a github issue for internal tracking at work.

**Comment by bluebill1049** [comment]
we can keep this ticket open. I will track from here.

**Comment by thomb** [comment]
Cheers @bluebill1049. Thanks!

**Comment by josias-r** [comment]
I ended up on this issue because of the "validate" method with the same type interference. From the types it seems the validation method does not support returning an object with the message.
In general: Why not allow all types but throw a browser console warning including the error message value, saying it should be a string?

I'm doing this as a workaround, better ideas are appreciated too:

```
const errMsg = t("The status of the job cannot be published");
return typeof errMsg === "string" ? errMsg : "error";
```
