### ISSUE TITLE
defaultValues not available to nested fields in a fieldArray

### ISSUE THREAD

**Issue by mgerring** [react-hook-form/react-hook-form#5804]
### Discussed in https://github.com/react-hook-form/react-hook-form/discussions/5802

<div type='discussions-op-text'>

<sup>Originally posted by **mgerring** June 30, 2021</sup>
**Describe the bug**
If I have a field array, and the field array renders a custom component that contains one or more fields, and I use useFormContext within that custom component, that component's fields will not have default values set automatically, even though the form correctly handles the default values.

**To Reproduce**
- Create a form wrapped with FormProvider
- Provide default values to useForm
- Create a field array
- Within the fieldArray's fields, render a custom component that wraps one or more form inputs
- Access the form context inside the custom component via useFormContext
- Register the fields in the custom component

**Codesandbox link (Required)**
https://codesandbox.io/s/serene-cartwright-y7s8p?file=/src/App.js

**Expected behavior**
I expect the fields in the custom component to have their default values set

**Desktop (please complete the following information):**

- macOS
- Firefox
- latest stable as of 6/30/2021
</div>

**Comment by bluebill1049** [comment]
thanks for the updated issue.

<img width="955" alt="Screen Shot 2021-07-01 at 10 09 43 am" src="https://user-images.githubusercontent.com/10513364/124046079-76319100-da54-11eb-9cf4-e57f975df5ba.png">

>Does not support flat field array.

**Comment by mgerring** [comment]
OK. I updated the code example to use an array of objects instead of a flat array. The issue is still present, and is actually worse than the flat array example. With the flat array, `isDirty` worked correctly, but with an array of objects, isDirty is set incorrectly if I input what should have been the default values to the text inputs.

Updated code example: https://codesandbox.io/s/serene-cartwright-y7s8p?file=/src/App.js

**Comment by bluebill1049** [comment]
please spend some time with the doc.

<img width="947" alt="Screen Shot 2021-07-01 at 10 35 30 am" src="https://user-images.githubusercontent.com/10513364/124047684-10df9f00-da58-11eb-8693-18b97f2eef23.png">

**Comment by mgerring** [comment]
I can see from this comment that you are expected to provide the defaultValue to a field in a fieldArray, but the docs don’t really explain why this is the case, and it’s incredibly cumbersome when it doesn’t need to be provided elsewhere.

**Comment by bluebill1049** [comment]
If you are here just to complain without reading the doc, then stop wasting my time! There are things that we want to improve over time (the next release should improve the defaultValue).  https://github.com/react-hook-form/react-hook-form/commit/4494e2e58a980f3ce12be2eca90d1cee2a78a35b

**Comment by mgerring** [comment]
I'm not trying to waste your time. I'm in the middle of implementing a complex form, and discovering that fields in fieldArrays work very differently from any other field. The doc is not especially clear about this, and there is conflicting advice in the documentation, in this repo's issues, on StackOverflow, etc.
