### ISSUE TITLE
Validation doesn't set any error on a different field

### ISSUE THREAD

**Issue by mic4ael** [react-hook-form/react-hook-form#5809]
**Describe the bug**
Even though validation is performed on a field, the error is not properly set until the actual field is modified.

**To Reproduce**

1. Type something into the `name` field (make sure you don't use @)
2. Update the `mode` field to `email`
3. Type something into the `other` field (the console logs prove that the validation is performed on the `name` field which is weird because that doesn't happen if I change the value of the `mode` field)

Even though the validation is done on the `name` field with every change to the value of the `other` field, the error is not visible
until you change the value of the `name` field. 

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

V7

https://codesandbox.io/s/react-hook-form-async-field-validation-forked-1k2mx?file=/src/index.js

**Expected behavior**
I would expect to have the actual error available in `formState.errors`. However, this behaviour is a bit inconsistent since if I change the value of the `mode` field I don't see any logs in the console proving that the validation of the `name` field has been performed.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Fedora 32
- Browser [e.g. chrome, safari] Firefox
- Version [e.g. 22] 89

**Comment by bluebill1049** [comment]
react hook form focus on single input validation at a time to improve performance, if you need dependant fields validation, please use `trigger`, from memory we do have a feature request for `register` with `dep` array, but it's not implemented just yet.

**Comment by mic4ael** [comment]
The question is why does the validation happen only if I change the input field and not when the dropdown's value changes?

**Comment by bluebill1049** [comment]
because on your dropDown there is no validation associated with the input, and if you need to show errors for the `name` field use `trigger`.

**Comment by mic4ael** [comment]
What I mean is the following:

1. Type into the first field
2. Type into the second field (the first field is also validated - console shows the messages)
3. Try to change the dropdown's value (this first field is not validated - console doesn't show any messages)

**Comment by bluebill1049** [comment]
yes, because we focus on one single input at a time.  you can follow the thread: https://github.com/react-hook-form/react-hook-form/discussions/5597 where we discussed about the new (potential) feature.

**Comment by mic4ael** [comment]
I understand why the error is not visible. What I don't get is why the custom validate method is not invoked when the dropdown's value changes.

**Comment by bluebill1049** [comment]
because you interact with a field with doesn't have validation. question: does `trigger` solve your problem?

**Comment by mic4ael** [comment]
> because you interact with a field with doesn't have validation

Ahh.. now I see. And yeah, `trigger` solves the issue ;)

**Comment by bluebill1049** [comment]
keep an eye on this area, I think I am going to plan on working on the `dep` for register. so you don't need to manually invoke `trigger`.

**Comment by mic4ael** [comment]
> keep an eye on this area, I think I am going to plan on working on the `dep` for register. so you don't need to manually invoke `trigger`.

That would be nice indeed!
