### ISSUE TITLE
New validation mode

### ISSUE THREAD

**Issue by reichhartd** [react-hook-form/react-hook-form#5810]
First of all thank you for your great work 🌞 
It would be great if you could help me out.

**Is your feature request related to a problem? Please describe.**

I am currently not happy with the validation methods used so far, as they don't solve all our problems. We need a validation method that does not declare the initial input as invalid, is not only triggered by the `onBlur` event and passes the status to the `isValid` property.

For example, we have a phone number input that we validate with a minimum length, a maximum length and a regex. Our Continue button is en- or disabled depending on the `isValid` property.
So far we have used `onChange`, but since for example `+49123` is still too short a phone number, an error is displayed already at the initial input. This gives our customers a bad feeling as if they did something wrong and we wanted to avoid this.

**Describe the solution you'd like**

Potential solutions that came to my mind:

-   onDelay: The input is validated only after there have been no more keystrokes for a certain time. It would be optimal if this time could be passed as a parameter.
    An extended version would be that the input is always validated, but the result is only withheld if the outcome is invalid. This way, if the input is valid, the property `isValid` would immediately be `true` and the user could continue, and would not have to wait the time period before pressing the continue button.
-   onValid: The state remains "idle" until the input is valid once. But at that point it is a `onChange`.
    Disadvantage: Until the input is valid once, the user gets no feedback what he did wrong. (Is the submit button is disabled depending on the `isValid` state.)

**Describe alternatives you've considered**

I switched to the validation method `onTouched`. Here, however, a new problem occurs. Since there is only a single input field on this page, `onBlur` is never triggered because the user does not leave the field. Therefore the button remains disabled until the user has left the input field, and an additional click is required, which we would also like to avoid.
Additionally `isValid` does not work with `onTouched`.

**Additional context**

We use this lib in conjunction with React Native.

**Comment by bluebill1049** [comment]
This is a duplicated of https://github.com/react-hook-form/react-hook-form/issues/1321 let's follow up there.
