### ISSUE TITLE
typo in useController

### ISSUE THREAD

**Issue by guerrap** [react-hook-form/react-hook-form#5816]
First of all, thank you for your work on this repo.

**Describe the bug**
After upgrading to the latest version `7.10.0`, I get an error when changing the value of a custom select component, wrapped by a `Controller`.

The error:
```TypeError: Cannot read property '_f' of undefined```

The error seems to occur only with my custom select component because with a native select or, for example, with the `antd` select, it all works fine.

**To Reproduce**
I couldn't reproduce the error in a sandbox because the select component I rely on is part of a private npm package.

**Expected behavior**
I'd expect the select component to keep working after the update.

**Screenshots**
![image](https://user-images.githubusercontent.com/9011637/124278648-cbe66600-db46-11eb-9f5f-6768e41f8e0d.png)

**Desktop:**

- OS: Ubuntu 20.04.2 LTS 
- Browser: Brave

**Additional context**
As I said I couldn't reproduce the error, but I believe there may be a typo in the implementation of the `useController`, at [this](https://github.com/react-hook-form/react-hook-form/blob/5cc71b7012250e0c03df28e09f0f6c63a955b733/src/useController.ts#L67) line; isn't it supposed to be `field` instead of `filed`, and then:

```js
const field = get(fieldsRef.current, name);

if (field && field._f) {
  field._f._c = true;
}
```
I've tried to fix it, in order to provide a PR, but I couldn't figure out how to fix the tests accordingly, and also I wasn't sure that this was the actual problem.

**Comment by bluebill1049** [comment]
thanks, that's just a variable name, i think you probably have a typo in your `name`. i will patch this with a PR anyhow.
