### ISSUE TITLE
Example of embedding custom script for populated inputs

### ISSUE THREAD

**Issue by Arsikod** [react-hook-form/react-hook-form#5824]
Just wanted to add an implementation example of how to embed custom scripts into populated input components of a form.
It uses useWatch, setValue, useFormContext and FormProvider.

Main takeaway is how to communicate between independent react components using RHF.

I believe you can add it as an example to V7 examples.

Code: https://codesandbox.io/s/cold-rain-tqoul?file=/src/App.js

**Comment by bluebill1049** [comment]
Thanks for the example! I will leave to the discussion section and users can refer to it as example.
