### ISSUE TITLE
Controller not working properly with `setValue` without `ref`

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#5838]
**Describe the bug**
`Controller` with `setValue` is no longer working as expected.

**To Reproduce**

1. Go to https://codesandbox.io/s/gracious-sunset-q5dy4
2. Click on `setValue` button
3. See value is not been updated.

**Codesandbox link (Required)**
https://codesandbox.io/s/gracious-sunset-q5dy4

**Expected behavior**
Expected to update input value without `ref`

**Additional context**
This is most likely to be a regression caused at `7.10.0`

### Discussed in https://github.com/react-hook-form/react-hook-form/discussions/5837

<div type='discussions-op-text'>

<sup>Originally posted by **Kyoij** July  5, 2021</sup>
When I use `Controller` or `useController`, I only pass `field.value` and `field.onChange` into `input` component, then I cannot use `setValue`. but when I call `getValues` function, I still get the value i just passed in.

[Codesandbox link](https://codesandbox.io/s/gracious-sunset-q5dy4)

- Device: [dell]
- OS: [window 10]
- Browser [chrome]
- Version [7.10.0]
</div>

**Comment by bluebill1049** [comment]
published the patch related to this: https://github.com/react-hook-form/react-hook-form/commit/77be0a616a6cb855dcd77f30e8001988323a87b3

**Comment by mmgil** [comment]
If the control is from userFormContext() this patch does not work.
