### ISSUE TITLE
Property 'message' does not exist on type 'DeepMap<Date, FieldError>' when the field is nullable

### ISSUE THREAD

**Issue by leosuncin** [react-hook-form/react-hook-form#5839]
**Describe the bug**
When using `Date | null` type the error field is not inferred correctly, is inferred as `Date` not `FieldError`

```jsx
interface FormData {
  name: string;
  birthdate: Date | null;
}
// ...
const { formState } = useForm<FormData>();
// ...
<small role="alert">{formState.errors.birthdate.message}</small>
// Property 'message' does not exist on type 'DeepMap<Date, FieldError>'.
```

![image](https://user-images.githubusercontent.com/4307697/124419983-d86fe780-dd1b-11eb-8332-4f79879d4b10.png)

**To Reproduce**

1. Go to https://codesandbox.io/s/keen-shamir-2zqxn
2. Open the file Form.tsx or FormWithZod.tsx
3. Go to [line 76 in Form.tsx](https://codesandbox.io/s/keen-shamir-2zqxn?file=/src/Form.tsx:2097-2131) or [line 50 in FormWithZod.tsx](https://codesandbox.io/s/keen-shamir-2zqxn?file=/src/FormWithZod.tsx:1479-1513)
4. See the Typescript error

**Codesandbox link (Required)**
https://codesandbox.io/s/keen-shamir-2zqxn

**Expected behavior**
Infer the type of the error as `FieldError` because property `message` actually exists and it isn't a date object

**Screenshots**
![image](https://user-images.githubusercontent.com/4307697/124420944-bb3c1880-dd1d-11eb-8e68-b2c219638bc3.png)

**Desktop (please complete the following information):**

- OS: GNU/Linux (Manjaro)
- Browser Firefox
- Version 89

**Additional context**
Maybe this is related to #5808

**Comment by bluebill1049** [comment]
can you please provide an isolated codesandbox?

**Comment by leosuncin** [comment]
This one [https://codesandbox.io/s/keen-shamir-2zqxn](https://codesandbox.io/s/keen-shamir-2zqxn)  
Do you need that I change something?

**Comment by bluebill1049** [comment]
thanks for the update @leosuncin

**Comment by b3coded** [comment]
@leosuncin  I think it's not caused because Date is nullable,
but because Date is not an primitive type but an `class`, so an field with property of type `File` will show the same error message

**Comment by leosuncin** [comment]
> @leosuncin I think it's not caused because Date is nullable,
> but because Date is not an primitive type but an `class`, so an field with property of type `File` will show the same error message

I don't think so, the error is a `FieldError` as you can see in the image

![image](https://user-images.githubusercontent.com/4307697/124483243-56a5ab80-dd67-11eb-96c3-e7acecda449c.png)

The problem is how typescript infer the type, here https://github.com/react-hook-form/react-hook-form/blob/90e3332a7efeda8c4e40519f7957671fb905ec3a/src/types/utils.ts#L35-L51

@bluebill1049, I updated the codesanbox to show more info, I hope it helps

**Comment by bluebill1049** [comment]
I would remove that `| null` for now.
