### ISSUE TITLE
Dynamic Checkboxes with same name are not having the event handlers registered

### ISSUE THREAD

**Issue by JayantDaruvuri** [react-hook-form/react-hook-form#584]
**Describe the bug**
When a different set of check boxes are rendered after the initial render. 
The checkboxes renderd after the initial render do not have their event handlers registered with react-hook-form

**To Reproduce**
1. Go to the dropdown
2. Select an option
3. Select the checkbox values and see the values getting rendered by the watch
4. Select a different option 
5. Select the checkboxes, notice that the values are not getting rendered

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-custom-input-ymxx7

**Expected behavior**
Selected checkboxes should render values after the initial render

**Screenshots**
First render: 

![image](https://user-images.githubusercontent.com/55671870/69772029-a9b29680-11f3-11ea-91ea-ad8f7e0d9f16.png)

Select Strawberry from the dropdown and select all the strawberry checkboxes
Notice that the values are not getting updated for the checkBoxValues
![image](https://user-images.githubusercontent.com/55671870/69772049-b9ca7600-11f3-11ea-958b-838e176cc452.png)

**Additional context**

It appears that the problem is from this line:
https://github.com/react-hook-form/react-hook-form/blob/10ab10b24ed0bad36cb0c589e747dfe2d7f8ab80/src/logic/findRemovedFieldAndRemoveListener.ts#L51

When the checkboxes are getting rerendered, it always checks if the checkor the radio button has the options or not 
https://github.com/react-hook-form/react-hook-form/blob/10ab10b24ed0bad36cb0c589e747dfe2d7f8ab80/src/logic/findRemovedFieldAndRemoveListener.ts#L27

When we register the check box, we only pass field attributes to the removeEventListenerAndRef
https://github.com/react-hook-form/react-hook-form/blob/9112a1eb036c3120a2d399063013d1f05734575e/src/useForm.ts#L691

**Comment by JayantDaruvuri** [comment]
Let me know if you have any questions :-)

**Comment by bluebill1049** [comment]
hey @JayantDaruvuri want to submit a PR to fix this? sounds like you know this Repo quite well :)

**Comment by JayantDaruvuri** [comment]
Hi @bluebill1049  buddy, but I have limited knowledge of the repo :-(. Let me try to pull down the package and give it a try. I hope I can create a PR :-)

**Comment by bluebill1049** [comment]
hey @JayantDaruvuri no stress, if take too much effort, i will take it over. it's good to get more people familiar with the code base. either way i will try to resolve the problem asap :)

**Comment by JayantDaruvuri** [comment]
Thanks a ton @bluebill1049,  it will be really helpful if you can take over this problem :-)

**Comment by bluebill1049** [comment]
no worries i will 👍 all good

**Comment by bluebill1049** [comment]
hey @jasondibenedetto i looked closer to this issue, it's going to be very tricky to support what you are doing. i would recommend a different `name`. react re-render always happen before DOM get's removed, so it's always 1 tick behind. you can try react-hook-form-input see if this will help.

**Comment by bluebill1049** [comment]
but i did find some issue around remove checkbox which is nice :) i am patching it.

**Comment by JayantDaruvuri** [comment]
Hi @bluebill1049 , we use yup schema extensively for validating the form inputs. If we use a different name everytime for checkbox rendering it makes it harder to validate the checkboxes :-(

**Comment by bluebill1049** [comment]
hey @JayantDaruvuri alternative solution in my head you can render everything on the screen, and use style to show and hide.

**Comment by JayantDaruvuri** [comment]
@bluebill1049 , thanks for taking a look at it. I will let the team know and see what we want to do!!

I have another question for you here is the codesand box.
https://codesandbox.io/s/react-hook-form-validationschema-wgxwd

Yup schema validation is validating all the fields now. 
I presume this wasn't the case with 3.24.1 package version, where only the touched fields were validated.

Can you please let me know what can I do to make it work?

**Comment by bluebill1049** [comment]
also have you tried with `react-hook-form-input` (make sure give `unregister` as prop name)?

**Comment by bluebill1049** [comment]
@JayantDaruvuri I patched that issue last night :) (sorry about that)

**Comment by JayantDaruvuri** [comment]
I haven't tried react-hook-form-input, I will try that over the weekend :-)

**Comment by bluebill1049** [comment]
yea let me know @JayantDaruvuri i think we can work out a solution for sure.

**Comment by JayantDaruvuri** [comment]
> @JayantDaruvuri I patched that issue last night :) (sorry about that)

Great thanks @bluebill1049 , I have tried reproducing the issue with the latest version 3.28.9. I can still see that this issue remains.

https://codesandbox.io/s/react-hook-form-custom-input-ymxx7

**Comment by bluebill1049** [comment]
> @bluebill1049 , thanks for taking a look at it. I will let the team know and see what we want to do!!
> 
> I have another question for you here is the codesand box.
> https://codesandbox.io/s/react-hook-form-validationschema-wgxwd
> 
> Yup schema validation is validating all the fields now.
> I presume this wasn't the case with 3.24.1 package version, where only the touched fields were validated.
> 
> Can you please let me know what can I do to make it work?

i meant patched this one :)

**Comment by JayantDaruvuri** [comment]
@bluebill1049 , thanks again. I will let you know we go with the checkbox rendering!!

**Comment by bluebill1049** [comment]
any update on this one?

**Comment by JayantDaruvuri** [comment]
Hi @bluebill1049 , thanks for the follow up. We could fix it with trying different names for the checkbox group. But the validation has been very hard for us to git it working :-(

**Comment by bluebill1049** [comment]
Even with react hook form input and same name?

**Comment by bluebill1049** [comment]
I will give a try in my free time then

**Comment by JayantDaruvuri** [comment]
I had a quick play with react-hook-form-input over the weekend. But it doesn't work, can you please let me know if I'm doing it right or not?

https://codesandbox.io/s/react-hook-form-custom-input-ymxx7

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-custom-input-delete-p1b7s

This is the best i can come up with.

**Comment by bluebill1049** [comment]
going to close this issue, above is best i could come up with for now.

**Comment by JayantDaruvuri** [comment]
> going to close this issue, above is best i could come up with for now.

@bluebill1049 , Thanks for taking a look at it.
 `   as={<input type="checkbox" />}
              rules={{ required: true }}
              name={`checkbox[${index}]`}
              register={props.register}
              setValue={props.setValue}`
checkbox[${index}] is making it harder to validate it through yup validation. 
In validations we either check if the validation is through yup schema or if it has it's own validation.
I will look at creating a PR for this in my spare time :-)

**Comment by bluebill1049** [comment]
thanks a lot @JayantDaruvuri I am trying my best as I can here :( looking forward to your PR
