### ISSUE TITLE
Testing input with Jest + Enzyme

### ISSUE THREAD

**Issue by phpSing** [react-hook-form/react-hook-form#585]
Please consider asking the question at our spectrum channel.

https://spectrum.chat/react-hook-form

**Describe the question?**
How to trigger/simulate an input change in order to trigger the useEffect which depend on the result of watch()

e.g.
const watchAll = watch()
useEffect(() => {
const {someField} = watchAll
// changed someField input
}, [watchAll])
**To Reproduce**

I tried
someField.simulate('input', { target: { value: 111 }})
someField.simulate('change', { target: { value: 111 }})
someField.instance().value = 111
someField.props().onPress({ target: {value: 111} })
tree.update()
both of them fail to trigger a re-run of the useEffect

any idea to solve this?

![image](https://user-images.githubusercontent.com/1982947/69775984-88db4880-11d5-11ea-81a2-73f4e23053db.png)
![image](https://user-images.githubusercontent.com/1982947/69775991-909aed00-11d5-11ea-8cd0-8911483d9c71.png)

**Comment by phpSing** [comment]
will keep on updating this in case it is just I am stupid somewhere

**Comment by bluebill1049** [comment]
hmmm you want to try with `react-testing-library`? it's probably working better with custom hooks.

**Comment by phpSing** [comment]
> hmmm you want to try with `react-testing-library`? it's probably working better with custom hooks.

Thanks for the reply, also do u know react-hook-form has IE10 fully support?

**Comment by bluebill1049** [comment]
that's babel transpiler's job right?

**Comment by phpSing** [comment]
ok, since I am working on other people's code, i found out the config is actually update when blur event fires.

so I need to do something like this to fire the update:

`    fireEvent.focus(dom);
    fireEvent.change(dom, { target: { value: 123 } });
    expect(dom.value).toEqual('123');
    fireEvent.blur(dom);`

closing this, thanks for help

**Comment by bluebill1049** [comment]
no worries :) if you find this lib please leave us a star ❤️ (no pressure tho)

**Comment by phpSing** [comment]
DONE :)

**Comment by bluebill1049** [comment]
thank you very much for your support 👍
