### ISSUE TITLE
regression - native array input does not unregister

### ISSUE THREAD

**Issue by orenklein** [react-hook-form/react-hook-form#5851]
**Describe the bug**
When removing a field which its value is array, it does not unregister
used to work in v7.9.0 and also 7.8.9.beta1

**To Reproduce**

1. Go to CSB
2. Click on toggle show twice
3. values are still presented even though they should be unregistered
4. change to version 7.9.0 and repeat - values get unregistered

**Codesandbox link (Required)**
https://codesandbox.io/s/input-native-array-doesnt-unregister-qz6c3

**Additional context**
The latest feature (`deprecated defaultValue at useFieldArray as a required prop`) is great and my project heavily relies on it. 
I used version 7.8.9.beta-1 for two weeks and the abovementioned regression does not occur on that version, so it might be an helpful fact.

**Comment by bluebill1049** [comment]
not regression, rather it was a bug fix: https://github.com/react-hook-form/react-hook-form/issues/5777

**Comment by orenklein** [comment]
so how would you unregister this field? isn't `shouldUnregister: true` should make it happen?

**Comment by bluebill1049** [comment]
yes, it does, but when you remount that input, the value will be populated via `defaultValeus`.

same as the behavior below:

`<input name="test" defaultValue="test' />`

mount it and remount it should still keep the `test`. you can invoke `unregister` manually again to remove the defaultValue reference tho.

**Comment by orenklein** [comment]
Yeah, however in the CSB the defaultValue is not passed to the ControlledInput component and it is defaulted to empty string in the component itself

**Comment by bluebill1049** [comment]
`setTimeout(() => reset({ solo: ["first", "second"] }), 0);`

**Comment by orenklein** [comment]
it gets called only once when `App` is mounted. it doesn't get called again when the input remount..
