### ISSUE TITLE
Add custom validation to Controller without register

### ISSUE THREAD

**Issue by riwu** [react-hook-form/react-hook-form#5852]
**Is your feature request related to a problem? Please describe.**
I use `Controller` instead of `register` and it doesn't seem like I can add custom input validation without using `register`.

**Describe the solution you'd like**
Support `validation` prop on `Controller` for custom validation.

**Describe alternatives you've considered**
Implement custom validation on my own through `setError`.

**Comment by bluebill1049** [comment]
there is `rules: validate`

https://react-hook-form.com/api/usecontroller

`rules`

**Comment by riwu** [comment]
@bluebill1049 that just specifies what rules to enable for that controller. 
You still need to use `register` to define those rules.
Please reopen, thanks.

**Comment by bluebill1049** [comment]
No, read the doc... At controller

**Comment by bluebill1049** [comment]
Rules props.

**Comment by riwu** [comment]
@bluebill1049 ok let's prove it with a codesandbox: https://codesandbox.io/s/react-hook-form-controller-forked-e5zzw?file=/src/index.js

Do you see `validate` being executed when you click the checkbox? You can change it to `rules={alert}` and it wouldn't work either.

**Comment by riwu** [comment]
@bluebill1049 in light of the CodeSandbox link provided, would you be able to reopen this? Thanks.

**Comment by miggynascimento** [comment]
you can do custom validation using `rules` prop like @bluebill1049 mentioned. 

use this Controller with a text input and type in "riwu" to see the error message. 
```
<Controller
    rules={ validate: (value) => {
          if (value === "riwu")
            return "read the docs" : true;
        },
      }),
```

**Comment by bluebill1049** [comment]
Thanks @miggynascimento 👍

**Comment by riwu** [comment]
@miggynascimento your code is identical to mine (apart from the obvious syntax errors), and if you click on the checkbox you would realize the function is not being invoked at all: https://codesandbox.io/s/react-hook-form-controller-forked-cqzyo?file=/src/index.js

@bluebill1049 please take a look at the Codesandbox.

**Comment by miggynascimento** [comment]
@riwu (apart from the obvious misconfiguration), the function does get invoked on validation. you just need to trigger the validation by adding a submit button and clicking on it or configuring useForm to trigger validation on change:

```
useForm({mode: "onChange"});
```

**Comment by bluebill1049** [comment]
> @bluebill1049 please take a look at the CodeSandbox and test it instead of just assuming the doc is correct and the library is bug-free...

1. I am not assuming the library is bug-free
2. I am here to maintain the library nothing personal
3. have some decency in open-source, no one own you anything

**Comment by bluebill1049** [comment]
Thanks again @miggynascimento for the response.

**Comment by riwu** [comment]
@miggynascimento thanks, completely forgot about that when testing in sandbox...

@bluebill1049 I was just requesting to reopen the issue as the first 5 responses did not address the issue with my code in the CodeSandbox link provided. 
Appreciate your time in contributing to open source almost for free :)
