### ISSUE TITLE
[React-Native] Keyboard disappear after entering text in text input

### ISSUE THREAD

**Issue by nguyenduckhai** [react-hook-form/react-hook-form#5863]
**Describe the bug**
The keyboard disappears after entering text in text input.  To be precise, I have 2 text inputs, both are required. After I entered the 1st one, ignore the 2nd one, and press the submit button, the 2nd field shows the required message (which is expected). When I am typing the 2nd text input, the keyboard immediately disappears after the 1st character.

**To Reproduce**

1. Go to my expo snack
2. Enter text in the first text input
3. Press the button which it shows the required message
4. Enter text in the second text input.
5. Keyboard disappears while entering text.

**Codesandbox link (Required)**

* [My expo snack](https://snack.expo.io/@closebeta12/keyboard-bug) 

**Expected behavior**
The keyboard does not disappear while entering text in text input

**Smartphone (please complete the following information):**

- Device: Redmi note 8 pro
- OS: Android 10

**Environment**

| Tech            | Version |
|-----------------|---------|
| React-hook-form | 7.10.1  |
| Expo            | 40.0.0  |

**Comment by bluebill1049** [comment]
This is not related to this libary.
