### ISSUE TITLE
onBlur validation

### ISSUE THREAD

**Issue by ao-alex** [react-hook-form/react-hook-form#587]
Hi,  on the latest  version "onBlur" validation is trigger validation for all fields even if they are not touched. Is this intentional or a bug? 
If this is intentional is there a way to get previous behavior, when blur trigger only validation on blurred field?
Thanks for plugin!

**Comment by bluebill1049** [comment]
can you send me a codesandbox? and which version was working and which version is broken

**Comment by bluebill1049** [comment]
that's not intentional for sure.

**Comment by bluebill1049** [comment]
still working fine with my codesandbox. https://codesandbox.io/s/w7p3km6nyw

**Comment by ao-alex** [comment]
https://codesandbox.io/s/react-hook-form-validationschema-ki8xn

**Comment by ao-alex** [comment]
thanks for quick answer, seems issue when validation schema is used

**Comment by bluebill1049** [comment]
oops... i will looking into it.

**Comment by bluebill1049** [comment]
latest version should patch this problem, let me know if you still facing issues
