### ISSUE TITLE
Shape of defaultValues is not preserved when submitting

### ISSUE THREAD

**Issue by valerii15298** [react-hook-form/react-hook-form#5874]
**Describe the bug**
When a passing object with numeric keys to defaultValues and submitting form, - the shape of values is not preserved.
Also as a result non-numeric properties is not available when submitting.

**To Reproduce**
`  const { register, handleSubmit } = useForm({
    defaultValues: { a: { someProp: "someValue", "2": "value" } }
  });
  const onSubmit = (data) => console.log(data);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input {...register("a.2")} />
      <input {...register("a.someProp")} />
      <input type="submit" />
    </form>
  );
`
In the code above `a` will be `array` when submitting, but must be `object` !

**Codesandbox link**
https://codesandbox.io/s/admiring-torvalds-ovvk4?file=/src/App.js

**Expected behavior**
When submitting form values must preserve the initial shape(as in defaultValues)!! (e. g. Array must be array and object must be object)
Also all values must be available.

**Additional context**
I think the solution can be use Array.isArray to determine the type of objects in defauldValues. And if the entity is array then use array, else object.

**Comment by bluebill1049** [comment]
Thanks for the issue report. This is expected, `number` is reserved for array index only.

> To produce an array of fields, input names should be followed by a dot and number. For example: test.0.data

https://react-hook-form.com/api/useform/register
