### ISSUE TITLE
Value-Message object is valid for custom validation (validate field) but message gets ignored

### ISSUE THREAD

**Issue by jschmuecking** [react-hook-form/react-hook-form#589]
**Describe the bug**
The type information for the validate field inside of ValidationOptions allows the form
`{
    value: Validate,
    message: string
}`
But when used, the provided message is ignored and just an empty string is returned in the errors message field.

**To Reproduce**
1. Create a simple input field.
2. register input with 
`<input
    name="example"
    ref={
        register({
            validate: {
                value: value => value === '1',
                message: "error message"
            }
        })
    }
/>`
3. Display error with `{errors["example"] && errors["example"].message}`
4. Display formState below field `{JSON.stringify(formState, null, 2)}`
5. Enter a 1 in the field and you will see that the form is valid
6. Enter a 10 in the field and the form is valid, but the error message will not be displayed

**Codesandbox link**
https://codesandbox.io/s/mystifying-ganguly-2f8tr?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
Either ValidationOptions don't allow a `{ value: Validate, message: string }` object in the validate field, or the given message is handed to the error object.

**Comment by bluebill1049** [comment]
hey @jschmuecking  we don't support value and message for `validate` function. it's already a function, i don't see much value to do value and message.

<img width="486" alt="Screen Shot 2019-11-28 at 10 06 38 pm" src="https://user-images.githubusercontent.com/10513364/69801459-5fe5a280-122b-11ea-9084-af34fcd1730a.png">

**Comment by jschmuecking** [comment]
Hey thank you for the quick response!

I can understand that standpoint. I myself find it a bit more clear than attaching it to the end of the validation function, but that is a matter of taste.

BUT I then would expect to remove the {value, message} object from the validate field in the ValidationOptions typescript types. That is how I got the impression this would work in the first place ;-)

**Comment by bluebill1049** [comment]
you are right on that, would you like to send a PR to correct that 👍

**Comment by jschmuecking** [comment]
sure thing

**Comment by bluebill1049** [comment]
awesome thanks!

**Comment by jschmuecking** [comment]
Thanks for the fix :) I guess a PR would be redundant now ;-)

**Comment by Atralbus** [comment]
@bluebill1049 I think there could be a case where you need a message in `validate`. I'm working on an input field where I get an regex value from the user. I want to check if the input value is valid regex or not. I have a function which returns an error message if the value is invalid and `''` if it's valid. I wanted to call my validation function in `validate` and display this error message. Currently `validate` considers this string output as error and returns it. If I call a function which only returns boolean in `validate` then I would need to get the message separately. I guess it would be nice to be able to just pass `register({ validate: checkRegexSyntax })`, then validate and get the message at the same time.

**Comment by bluebill1049** [comment]
@Atralbus i am not very clear above, but could you do the following?

```
validate: () => {
  if (someCondition) {
    return 'error message'; 
  }
  // you can do more logic here
  return true;
}
```

**Comment by Atralbus** [comment]
@bluebill1049 Yes, you are right. It seems like my issue could just be solved with a simple trick.

```typescript
inputRef={register({ validate: value => checkRegexSyntax(value) || true })}
```

Here, `checkRegexSyntax` returns the error message or `''`.

Thank you for the fast response.

**Comment by bluebill1049** [comment]
sweet all good :)

**Comment by bluebill1049** [comment]
@Atralbus if you find this lib useful, please consider to support us by leaving a star in the near future as well :) thanks in advance

**Comment by simonv3** [comment]
Is there a way for the `validate` function to return an object so that we can define a unique message for it?

```
validate: async d => {
  const blueprint = await fetchBlueprintById(blueprintId);
  const foundStep = blueprint.value.steps.find(
    step => step.mainEntity.abbreviation === d
  );
  return !foundStep;
}
```

**Comment by bluebill1049** [comment]
> Is there a way for the `validate` function to return an object so that we can define a unique message for it?
> 
> ```
> validate: async d => {
>   return {
>     value: false,
>     message: "bla"
>   }
> }
> ```
> 
> or even better:
> 
> ```
> validate: { 
>   unique: async d => {
>     return {
>       value: false,
>       message: "bla"
>     }
>   }
> }
> ```

perhaps you can do the following:

```
validate: {
 aaa:  () => {}
 aaa1:  () => {}
}
```

**Comment by REDLIGHTFILMS** [comment]
How can I use ErrorMessage with validate? I want to pass into the validate function the value, from the text field and then validate. How can I do that?

`validate: (value: string) => {
        if(Number(value) > 3) {
            return "test"
        }
}`

This code does not work....

**Comment by maciejdzialo** [comment]
When we use **validate** our function/s has to return **true** or **false** in order to validate if the input value meets our requirements. I have email input and I'm checking if it contains '@', here's the code:
```
validate: {
                containsAt: (value) =>
                  value.includes('@') ? true : 'Email should contain @',
              },
```
And it works! 😃
![image](https://user-images.githubusercontent.com/49043489/118410844-d4b3d300-b691-11eb-8909-86bee2db1209.png)
