### ISSUE TITLE
Build crashes on old Chrome versions

### ISSUE THREAD

**Issue by zhicong** [react-hook-form/react-hook-form#5905]
**Describe the bug**
React Hook Form causes a fatal JS error on old browsers. On a test device with Chrome 51 (which already supports ES6), JS fails to load due to a SyntaxError in the compiled build of RHF. This is affecting our ability to support our users on old devices.

This occurs even if we run a new Next.js project with RHF as the only package.

**To Reproduce**

1. Install [Create Next App](https://nextjs.org/docs/api-reference/create-next-app)
2. Run `npm install react-hook-form` and insert `import { useForm } from 'react-hook-form'` in index.js

**Codesandbox link (Required)**
Codesandbox initialised with the above steps: https://codesandbox.io/s/nextjs-with-react-hook-form-qsrq9?file=/pages/index.js

Open the preview link on an old version of Chrome to see the error. I installed [an old APK](https://www.apkmirror.com/apk/google-inc/chrome/chrome-51-0-2704-81-release/) on an Android device.

**Expected behavior**
RHF should load on all browsers that support ES6.

**Smartphone (please complete the following information):**

- Device: Android
- OS: 5.0.1
- Browser: Chrome
- Version: 51

**Additional context**
The error shows in console as:
```
Uncaught SyntaxError: Unexpected token (
./node_modules/react-hook-form/dist/index.esm.js | @ | index.js?ts=1626069739932:462
-- | -- | --
options.factory | @ | webpack.js?ts=1626069739932:675
__webpack_require__ | @ | webpack.js?ts=1626069739932:37
fn | @ | webpack.js?ts=1626069739932:353
(anonymous function) | @ | index.js:9
./pages/index.js | @ | index.js?ts=1626069739932:387
options.factory | @ | webpack.js?ts=1626069739932:675
__webpack_require__ | @ | webpack.js?ts=1626069739932:37
fn | @ | webpack.js?ts=1626069739932:353
(anonymous function) | @ | ?e594:5
(anonymous function) | @ | route-loader.js?361d:29
```

**Comment by bluebill1049** [comment]
This is not an issue with the library. Check out your bundle config. Also we have dropped old browser like IE 11. If u need old version of browser support, use version 6 IE11 build.

**Comment by zhicong** [comment]
I was skeptical that that would be an accurate solution when you replied and closed this within 2 minutes... but that was indeed the solution! Thank you!

For anyone facing the same issue, the solution is buried inside the [FAQs](https://react-hook-form.com/faqs):

`import { useForm } from 'react-hook-form/dist/index.ie11'; // V6`

**Comment by bluebill1049** [comment]
It's not about closing within 2 min, it's about someone who cares and maintains this library, and most importantly nothing personal.
