### ISSUE TITLE
Reset function clear `_c` variable for Controller ref

### ISSUE THREAD

**Issue by naharyd** [react-hook-form/react-hook-form#5908]
**Describe the bug**
When we are calling to `useForm` **reset** function without `keepStateOptions` (as second variable) it reset `fieldsRef.current` object and `useController` is registering the field again but the `useEffect` whos responsible to set `_c` value is not being call.

**Codesandbox link (Required)**
https://codesandbox.io/s/determined-moore-6shrp?file=/src/App.tsx

**Expected behavior**
`_c` variable will be set after reset function is being called

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: chrome
- Version 91.0.4472.114

**Comment by bluebill1049** [comment]
this is not exposed to public use and `Controller` should re-register the inputs again with _c.
