### ISSUE TITLE
`setState` does not update input if `reset` was called before

### ISSUE THREAD

**Issue by dlindenkreuz** [react-hook-form/react-hook-form#5911]
**Describe the bug**
Since v7.10.0, `setState` does not update the related inputs that are controlled by a controller, but only if `reset` was called before. This issue is slightly different from https://github.com/react-hook-form/react-hook-form/issues/5838, but probably related.

**To Reproduce**

1. Form "resets" the field `name` to `"initial"` after 500msec delay
2. Click "setValue" button
3. Input is **not** updated
4. Submit the form once: logs correct value `"abc"`

**Codesandbox link (Required)**
https://codesandbox.io/s/lucid-cache-7ikxh?file=/src/App.js

**Expected behavior**
Step 3: Input should be updated to show correct value `abc`.
Everything works as expected in v7.9.0 (switch between versions in the Codesandbox above). It seems this broke with v7.10.0.
Everything works as expected in v7.10.2-beta.0, but only if `reset` is never called.

**Desktop (please complete the following information):**

- OS: macOS 10.15
- Browser: Firefox, Safari, Chrome -- all the same.
- Version: 89, 14, latest

**Comment by TonyVeigel** [comment]
Not sure if this falls in the same line but when prepending a new field the new values take on the previous values of the field. https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-u7eim?file=/src/index.js  click on prepend.

**Comment by dlindenkreuz** [comment]
Works perfectly now. @bluebill1049 you're on fire, that was unexpectedly quick. Thanks for the release. 🔥
