### ISSUE TITLE
Option to submit only registered fields

### ISSUE THREAD

**Issue by ZachMayry** [react-hook-form/react-hook-form#5914]
### **Is your feature request related to a problem? Please describe.**
Sometimes there are fields which end up in default values but are not part of the form. It would be nice to omit those with an option if they are not registered. 

Ex. 
```jsx
const user = {
  name: 'name',
  updatedAt: '10-10-2020', // handled by the database but available to the frontend
}

const formMethods - useForm({ defaultValues: user })

return (
  <form onSubmit={formMethods.handleSubmit(submitFunc)}>
    <input {...formMethods.register('name') />
  </form>
)
```

I can provide other examples if needed. This was just the simplest.
We do have some forms that add or remove inputs based on a "type" drop down.
If you load up one of type A then change it to type B, you still have the old defaults for fields that are no longer available for type B

### **Describe the solution you'd like**
In this case the submit method has both name and `updatedAt` but only `name` is registered.
It would be nice to have an easy way of submitting `name` and not `updatedAt` without having to strip these out of the defaultValues.
This is how it used to work in v6.

### **Describe alternatives you've considered**
in the meantime I'm manually only setting defaults or submitting fields that are registered. It's a bit tedious since we don't have the internal list of what's registered at any time. That lives inside the react-hook-form package.

### **Additional context**

**Comment by bluebill1049** [comment]
isn't this `shouldUnregister:false`?

**Comment by ZachMayry** [comment]
Oh my bad, I didn't realize those had changed.
There is this in the migration guide: `Important: input value and reference will no longer get removed after unmount.`
Is there a way to call out the option in the migration guide to help others.

**Comment by bluebill1049** [comment]
no worries @ZachMayry if you have time please send us a PR: https://react-hook-form.com/migrate-v6-to-v7

**Comment by ZachMayry** [comment]
Yeah I’ll take a look tomorrow

**Comment by bluebill1049** [comment]
thank you @ZachMayry no stress.
