### ISSUE TITLE
`useWatch` hook with array of names returns values with invalid typings

### ISSUE THREAD

**Issue by maxsbelt** [react-hook-form/react-hook-form#5928]
**Describe the bug**

If I pass array of field names to `form.watch()` method it'll return array of values with proper typings. But if I pass this array as `name` property of `useWatch` hook it'll return array of values with wrong typings.

**To Reproduce**

See codesandbox.

**Codesandbox link (Required)**
https://codesandbox.io/s/funny-gates-btzez?file=/src/App.tsx

**Expected behavior**
`useWatch` hook should return values with the same typings as `form.watch` method.

**Screenshots**

|form.watch|useWatch|useWatch(with type arguments)|
|-|-|-|
|<img width="769" alt="Screenshot 2021-07-13 at 14 02 44" src="https://user-images.githubusercontent.com/950216/125441468-887b5aee-709f-4717-9c03-5186c3b3eab7.png">|<img width="705" alt="Screenshot 2021-07-13 at 14 02 49" src="https://user-images.githubusercontent.com/950216/125441463-0f05be94-d6d6-4ad5-bd03-c98b9620f481.png">|<img width="530" alt="Screenshot 2021-07-13 at 14 07 45" src="https://user-images.githubusercontent.com/950216/125441760-2fd30b8b-974b-4183-bacf-7fa073e136f8.png">|

**Comment by bluebill1049** [comment]
thanks for the detailed issue report. from memory this is a limitation, but let me confirm this with you.

**Comment by maxsbelt** [comment]
UPD: ok, so basically I already can pass name array as a `const`. Seems like this feature was added yesterday :)

<img width="599" alt="Screenshot 2021-07-13 at 15 35 11" src="https://user-images.githubusercontent.com/950216/125452560-2ec4c65f-3080-4726-b812-cd519ae60e10.png">

@bluebill1049  From my perspective this ticket can be closed.

**Comment by bluebill1049** [comment]
thanks for the update @maxsbelt let me confirm if we can omit the `const` as well.
