### ISSUE TITLE
formState.touched is not updated when form fields are changed

### ISSUE THREAD

**Issue by Smona** [react-hook-form/react-hook-form#593]
**Describe the bug**
The 'touched' array in my form's formState is always empty, even after i modify some of the inputs.

**To Reproduce**
1. Create a hook form
2. Access the formState returned by the hook.

**Codesandbox link**
Include a codesandox will help us to investigate the issue quicker.

**Expected behavior**
I expected the array to list inputs that have been edited.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser vivaldi

**Additional context**

**Comment by bluebill1049** [comment]
can you supply a codesandbox?

**Comment by bluebill1049** [comment]
going to close this as issue is not clear with an example, happy to re-open once more information provided.

**Comment by Smona** [comment]
I think i've figured it out. Once I set the `mode` to "onChange", it looks like touched fields are updating properly. I don't think anything is needed here but possibly a documentation update noting that touched fields aren't updated unless validation is triggered.

Thanks for the great library! Uncontrolled inputs ftw

**Comment by bluebill1049** [comment]
Thanks @Smona i will update the doc accordingly
