### ISSUE TITLE
V7 Missing getValues method in Control

### ISSUE THREAD

**Issue by ViieeS** [react-hook-form/react-hook-form#5932]
In V6 I could access all values via `control.getValues()` method. However, in v7 there is only `control.setValues()` method.

**Comment by JGibel** [comment]
You shouldn't be using control.getValues() (or setValues()) according to the [docs for control](https://react-hook-form.com/api/useform/control):
> Important: do not access any of the properties inside this object directly. It's for internal usage only.

getValues() is available to you in useForm. You can pass that down via props or use [useFormContext](https://react-hook-form.com/api/useformcontext)

**Comment by bluebill1049** [comment]
Thanks @JGibel ❤️
