### ISSUE TITLE
useFieldArray remove() always removes last even if index is passed

### ISSUE THREAD

**Issue by afermon** [react-hook-form/react-hook-form#5933]
**Describe the bug**
useFieldArray remove() always removes last item even if index is passed. According to the documentation it should remove the item at the specific index.

**To Reproduce**

1. Create a form using useFieldArray
2. in your logic add a call to remove(index) passing the index of a specific item.
3. Execute it
4. The last item will be removed and not the one indicated.

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

https://codesandbox.io/s/usefieldarray-conditional-forked-ujykn?file=/src/App.tsx

**Expected behavior**
should remove field at the indicated Index

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS Big Sour
- Browser Safari
- Version 14.1.1

**Smartphone (please complete the following information):**

- Device: iPhone XR
- OS: 14.5
- Browser Safari

**Additional context**

**Comment by bluebill1049** [comment]
please follow the doc on how to implement useFieldArray 

https://react-hook-form.com/api/usefieldarray

<img width="646" alt="Screen Shot 2021-07-14 at 11 50 59 am" src="https://user-images.githubusercontent.com/10513364/125547927-882a167f-17aa-46ed-9f9e-90b0181eef78.png">

you are missing the `key`
