### ISSUE TITLE
Reset doesn’t resetting Select with Controller

### ISSUE THREAD

**Issue by yuvalshim** [react-hook-form/react-hook-form#5948]
When using Select with Controller the value doesn’t resetting.

https://codesandbox.io/s/react-hook-form-with-ui-library-forked-6jgur

**Expected behavior**
Reset all the values in the form include the Select input.

**Comment by bluebill1049** [comment]
provide defaultValues and provide defaultValues to the reset as the argument. 

https://react-hook-form.com/api/useform/reset

**Comment by yuvalshim** [comment]
Thanks I missed it...

**Comment by bluebill1049** [comment]
all good.
