### ISSUE TITLE
Issue with drag and drop and nested field array

### ISSUE THREAD

**Issue by revich2** [react-hook-form/react-hook-form#5955]
**Describe the bug**
In my case, i have fieldArray with nested fieldArray. Root field array can be draggable. Then i change place items of root fieldArray, receive updated data from backend and apply this data to form - i see wrong behaviour. One item lose own nested array and get nested array of second item.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Codesandbox example
2. Wait for data from "backend"
3. Change place of items with drag and drop
4. Wait for data from "backend" will be update
5. You can see collision which happened

**Codesandbox link (Required)**
https://codesandbox.io/s/practical-sun-1y339?file=/src/App.tsx

**Expected behavior**
When data from backend applying after root fieldArray moving, all nested fieldArrays should on their own places

**Screenshots**
<img width="478" alt="Screenshot 2021-07-15 at 12 35 45 PM" src="https://user-images.githubusercontent.com/24573190/125768647-6082b27f-e76d-4308-b7bf-7fd2bfbbc72c.png">
<img width="467" alt="Screenshot 2021-07-15 at 12 36 27 PM" src="https://user-images.githubusercontent.com/24573190/125768656-7590030a-12d7-4b01-bf89-b73a41e03e65.png">

**Desktop (please complete the following information):**

- OS: Big Sur 11.4
- Browser chrome
- Version 91.0.4472.114

**Additional context**
react: 17.0.2
react-hook-form: 7.11.0
react-beautiful-dnd: 13.1.0

**Comment by bluebill1049** [comment]
<img width="934" alt="Screen Shot 2021-07-16 at 1 39 58 pm" src="https://user-images.githubusercontent.com/10513364/125888259-5fcf256a-b09d-4826-ad3c-2a6fa68f6fc5.png">

this is a limitation at the moment, I would suggest do that second action in `useEffect` like above.

**Comment by revich2** [comment]
@bluebill1049 i think this problem doesn't related with this limitation. Because i edited CodeSandbox example:
Now all form methods separated on different handlers and i see similar behaviour.

Link to example: https://codesandbox.io/s/gracious-shockley-8hej6?file=/src/App.tsx

Steps:
1. Go to Codesandbox example
2. Wait for data from "backend"
3. Change place of items with drag and drop
4. Click on bottom button for emulate backend behaviour and delay.
5. You can see collision which happened

**Comment by bluebill1049** [comment]
> You can see collision which happened

https://user-images.githubusercontent.com/10513364/125927796-b3ea085e-b419-4f9d-a151-8a34e744148e.mov

what do you mean by collision happened?

**Comment by revich2** [comment]
> what do you mean by collision happened?

on your video, you can see that nested arrays changed their place

After move:
<img width="530" alt="Screenshot 2021-07-16 at 12 47 43 PM" src="https://user-images.githubusercontent.com/24573190/125928576-f84c1f8c-ee84-459b-af30-430df668b379.png">

After last reset:
<img width="528" alt="Screenshot 2021-07-16 at 12 47 55 PM" src="https://user-images.githubusercontent.com/24573190/125928635-4b614838-465b-4d03-a051-3b8c395b24aa.png">

**Comment by revich2** [comment]
@bluebill1049 do you have time to investigate this issue?

**Comment by revich2** [comment]
i have a workaround for this issue. i can make to render nothing before "backend reset" and it will be work as expected. But if i have a huge list of elements, then this list will become jumping after rendering nothing and applying new state. it makes me to do another workaround for scrolling list to previous dragging place. it sounds painful)

**Comment by bluebill1049** [comment]
Had another look and I believed the issue is caused by your Id which is just 1,2 make sure they r using unique hash or Id from hook form.

**Comment by revich2** [comment]
@bluebill1049 changed ids to uuids, but it didn't solve the problem

**Comment by bluebill1049** [comment]
what's the reason to overwrite hook form's id? if you need to have those `id`, create a separate field or change the `keyName`.

**Comment by revich2** [comment]
@bluebill1049 uh, really, "id" was identifier of data and generated identifier of form
thank you for explaining! i think you can take away label "design limitation" - issue solved.
