### ISSUE TITLE
Yup array fields using the test method are missing in V7 formState errors property on fail

### ISSUE THREAD

**Issue by r-hirsch** [react-hook-form/react-hook-form#5959]
**Describe the bug**
When using the Yup test method on an array, if validation fails the errors object remains empty. Before version 7 the array object would be present with the message and type fields.

**To Reproduce**

1. Open the two codesandbox links below and make sure the console is visible on both. Note both are identical, the version 7.10.1 codesandbox only differs because the errors field has been moved on to the formState. 
2. In the App.js file, on line 17 there is a `questions` array field which has a `test` method on it. The test throws false if the input values total exceeds 100. So in the first input field (percentage 0) add the value '200' and click 'Submit Query'.
3. This will show an error message to the left of the buttons in V6.11.3, but it does not in V7.10.1.
4. Looking at the V6.11.3 console the errors object is being logged out with the `questions` object inside with the message and type fields present as expected (see Screenshot 1).
5. Looking at the V7.10.1 console the errors object is empty (see Screenshot 2).
6. In the V7.10.1 App.js file on line 26 there is a commented out 'min' method `// .min(4, 'test')`. If this is uncommented and 'Add field' is clicked then the error object is logged out with the questions field present (see Screenshot 3). Because of this I think this is an issue with the 'test' method on the React Hook Form Yup Resolver.

**Codesandbox links**
V6.11.3: https://codesandbox.io/s/zealous-lamport-o3205?file=/package.json
V7.10.1: https://codesandbox.io/s/peaceful-booth-tpknw?file=/package.json

**Expected behavior**
The errors object is updated so that the message can be displayed where it is failing.

**Desktop (please complete the following information):**

- OS: macOS Big Sur 11.2.2
- Browser: Firefox
- Version: 89.0.2

**Additional context**
I commented out the test method and used the 'min' method with a message and that updated the errors object so I believe there must be something specifically wrong with the 'test' method on the React Hook Form Yup Resolver.

Screenshot 1:
![Screenshot1](https://user-images.githubusercontent.com/71602987/125918653-af5bae26-074d-4ce7-b88f-417a871c0ef2.png)

Screenshot 2:
![Screenshot2](https://user-images.githubusercontent.com/71602987/125918673-953f985e-41cc-433a-8f49-2033b4f6cfc3.png)

Screenshot 3:
![Screenshot3](https://user-images.githubusercontent.com/71602987/125918713-7c2434d6-bbc1-4d85-abcf-22f9f18b7411.png)

**Comment by bluebill1049** [comment]
missing steps to reproduce.

**Comment by r-hirsch** [comment]
Hi @bluebill1049, I've updated the steps and attached some screenshots. Hopefully this is adequate enough, thanks :)

**Comment by bluebill1049** [comment]
<img width="382" alt="Screen Shot 2021-07-16 at 6 53 33 pm" src="https://user-images.githubusercontent.com/10513364/125921201-a3407382-eb01-451f-8fed-7bbe288d7cb7.png">
you are using the wrong version of the resolver package.
