### ISSUE TITLE
Types are too loose

### ISSUE THREAD

**Issue by sbdchd** [react-hook-form/react-hook-form#5964]
**Describe the bug**

This code produces a runtime error and passes typescript

```tsx
import React from "react";
import ReactDOM from "react-dom";
import { useForm, SubmitHandler } from "react-hook-form";

import "./styles.css";

type Inputs = {
  example: string;
  exampleRequired: string;
  web: { value: string };
};

function App() {
  const {
    register,
    handleSubmit,
    formState: { errors }
  } = useForm<Inputs>();

  const onSubmit: SubmitHandler<Inputs> = (data) => {
    console.log(JSON.stringify(data));
    // explodes at runtime with a type error but passes the type checker
    console.log(data.web.value);
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <label>Example</label>
      <input {...register("example")} defaultValue="test" />
      <label>ExampleRequired</label>
      <input {...register("exampleRequired")} />
      {errors.exampleRequired && <p>This field is required</p>}
      <input type="submit" />
    </form>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**To Reproduce**

1. Add that code to code sandbox
2. click submit
3. `TypeError: undefined is not an object (evaluating 'data.web.value')`

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-get-started-ts-forked-4hlh0?file=/src/index.tsx

**Expected behavior**
Should get a type error instead

**Desktop (please complete the following information):**

- OS: Mac
- Browser:  Safari
- Version: Version 14.0.3

EDIT: I think the bound on the generic needs to be more strict than `Record<string, any>`

https://github.com/react-hook-form/react-hook-form/blob/991fdbcf3a98adb4c05d36b772e5d26ae773ab0b/src/types/fields.ts#L25

**Comment by bluebill1049** [comment]
Thanks for the issue. I don't think there is too much we can do on this one. However, happy to have suggestion on improvments.

**Comment by ifeltsweet** [comment]
Maybe if react-hook-form allowed to specify validation rules in the hook, then it would not call `handleSubmit` when user forgot to register a field. This could also potentially allow data type passed to `handleSubmit` to be of "valid" type by inferring a valid schema from the rules. Because right now even if your field is marked as required, the data type passed to `handleSubmit` can still show null, which can never happen of course.
