### ISSUE TITLE
Bug - field array fields removed when useFieldArray hook is used in parent and child component

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#5967]
**Describe the bug**

**if** 
1. I have a parent component and child component that both call `useFieldArray` with the same-named field array
2. I mount the child and add some elements to the field array
3. I unmount the child field array and then remount it

**then**
The `fields` property of the field array will be empty rather than containing the values in `formValues`. 

**To Reproduce**

1. Go to the sandbox
2. Click add element and type some input
3. Click the toggle show child button twice to unmount and remount the child component
4. Notice that fields is now empty while `formValues` still has the field array values

**Codesandbox link (Required)**
https://codesandbox.io/s/nice-monad-rkydl?file=/src/App.js

**Expected behavior**
I expect that fields would have the `formValues` for the field array when it's remounted.

**Additional context**
The only reason I am mounting `useFieldArray` twice in the parent and child component is because in my app I need to use `setValue` to modify the field array values before the field array is first mounted. If I don't call `useFieldArray`, then I can't use `setValue` on field array elements. If this is no longer the case, then I would gladly remove the `useFieldArray` call in the parent.

Additionally, @bluebill1049 mentioned that using calling `useFieldArray` twice was safe when I last asked. Additionally, this did work in older versions which leads me to believe it is just a bug.

**Comment by bluebill1049** [comment]
<img width="435" alt="Screen Shot 2021-07-16 at 4 01 29 pm" src="https://user-images.githubusercontent.com/10513364/125899754-e5b9d92d-dd57-4103-bd8e-2855e7df34f5.png">

i almost miss that, why there is another useFieldArray?
