### ISSUE TITLE
[useFieldArray] Type 'string' is not assignable to type 'never'

### ISSUE THREAD

**Issue by enheit** [react-hook-form/react-hook-form#5972]
**Describe the bug**

**To Reproduce**

1. Import `useFieldArray`
2. Populate `useFieldArray` with required parameters
3. Pass `name` as a string to the `useFieldArray`
4. Open console to see the error or hover over `name` property of the `useFieldArray` (see pictures below)

**Codesandbox link (Required)**
https://codesandbox.io/s/smoosh-sun-zplfb?file=/src/App.tsx

**Expected behavior**
The type of the `name` property should expect `string` instead of `never`

**Screenshots**

Screenshot from the codesandbox
![image](https://user-images.githubusercontent.com/8645216/125941994-50655e46-c3d6-4553-9414-61c647db45a3.png)

Screenshot form my personal project
![image](https://user-images.githubusercontent.com/8645216/125942067-d838f8aa-6826-4105-842b-789bd6c427e9.png)

Error message from the console of my personal project
```
Type 'string' is not assignable to type 'never'.  TS2322

    40 |   const { fields, append, remove } = useFieldArray({
    41 |     control: control,
  > 42 |     name: 'breaks'
       |     ^
    43 |   })
    44 |
    45 |   const openTime = watch('openTime')
```

**Desktop (please complete the following information):**

- OS: WIndows
- Browser Chrome
- Version Version 91.0.4472.164 (Official Build) (64-bit)

**Additional context**
Typescript version used in my project is `"typescript": "^4.1.2"`

**Comment by bluebill1049** [comment]
<img width="538" alt="Screen Shot 2021-07-16 at 9 47 31 pm" src="https://user-images.githubusercontent.com/10513364/125942903-1a6258db-e8a8-48e4-aeb4-dd6fbb6e5cfc.png">

there is no `items` in your form data.

**Comment by enheit** [comment]
I found a problem. I was needed to add `items` to the `FormData` interface

```typescript
interface FormData
  foo: string;
  items: { value: string }[]
```

and use it like this

```JSX
<Input
   name={`items.${index}.value`}
/>
```

**Comment by kolnogorov** [comment]
But if you do so, then `items` be in the final serialized form data. But when i get `data` object in submit handler, i suppose it does not contain any other fields more than needed. Yet, `items` will be there, but they are not really form fields.
