### ISSUE TITLE
setValues not working inside Controller

### ISSUE THREAD

**Issue by nachten** [react-hook-form/react-hook-form#5978]
**setValues not working inside Controller**

I'm trying to clear the data for a specific field within my custom control using the <Controller>

You can find my problem here: 

https://codesandbox.io/s/elegant-sun-060xt

**Expected behavior**
I would expect that my field can be cleared by pressing the clear icon inside the textfield

**Screenshots**
not applicable

**Desktop (please complete the following information):**

- OS: macos big sur
- Browser: edge
- Version: Version 91.0.864.64 (Official build) (x86_64)

**Comment by bluebill1049** [comment]
use onChange from `field` object instead.

also: 
<img width="979" alt="Screen Shot 2021-07-17 at 9 41 16 am" src="https://user-images.githubusercontent.com/10513364/126018119-8d4e9bbb-5512-4a0f-9c47-45375ca2e4e3.png">

**Comment by nachten** [comment]
Thanks man, this works for me ... although an `setValue` on `field` object would be more logical for me :)
