### ISSUE TITLE
Auto focus on the first input with error when both native and custom inputs are used

### ISSUE THREAD

**Issue by tedliang** [react-hook-form/react-hook-form#5981]
Auto focus on the first input with error when both native and custom inputs are used

**Describe the solution you'd like**
https://codesandbox.io/s/react-hook-form-v6-auto-focus-on-the-first-input-with-error-8s50w?file=/src/index.js
When submit button is clicked, it should focus on the input for first name.

**Describe alternatives you've considered**
N/A

**Additional context**
We can use fieldErrors and form.elements to find out the first focusable error input.
https://erikras.com/blog/focus-on-errors

**Comment by bluebill1049** [comment]
We can't guarantee the focus order at v6, the order is based on the `register` order. If you want to get it consistent, I would recommend to use all `Controller` at v6.

**Comment by bluebill1049** [comment]
consider to use v7: https://codesandbox.io/s/goofy-elbakyan-nety1?file=/src/App.js

**Comment by tedliang** [comment]
v7 has the same problem: https://codesandbox.io/s/zen-hertz-2ftkt
The workaround would be using Controller for all inputs. 

Thanks for your prompt reply.

**Comment by jeina7** [comment]
Hi, I am also struggling with getting an auto focus on input which has error with `<Controller>`.

It seems that now `"react-hook-form": "7.11.1"` version works fine with simple `<input>` tag, and also works fine when `<Controller>` renders simple `<input>` tag. However, it doesn't work for 3rd party components. 

I have a demo with material-ui: https://codesandbox.io/s/lucid-christian-2bqqx

It takes auto focus when "firstName" field or "lastName" field is empty, however it doesn't take auto focus on material-ui field when it is still empty.

Is this on-going issue on react-hook-form v7?

**Comment by tedliang** [comment]
MUI is using inputRef instead of ref.
