### ISSUE TITLE
Updating state in useEffect with formState dependency causes endless loop

### ISSUE THREAD

**Issue by brandondurham** [react-hook-form/react-hook-form#5996]
**Describe the bug**
I’m working on creating a form wizard with several panels. The entire form has a single Submit button, so I can’t run validation panel by panel. Each panel has some required fields, and until the validations on those fields are met, you cannot navigate to the next panel in the wizard. In order to determine if fields for individual panels are valid (essentially running validation on a subset of form fields), I have something like the following `useEffect` in place:
```js
const [validFields, updateValidFields] = useState();
useEffect(() => {
  const dirty = Object.keys(formState.dirtyFields);
  const errored = Object.keys(formState.errors);
  const valid = dirty.filter((key) => errored.indexOf(key) < 0);
  // updateValidFields(valid);
}, [formState]);
```

`valid` essentially becomes an array of fields that have passed validation. I need to be able to update state to account for that (and, in turn, flag the panels that have passed validation), but any time I uncomment the `updateValidFields(valid);` line I get an endless loop of re-rendering.

I expect this is more user error than bug, but I read that you can’t use `formState.errors` in the dependency array since it’s an alias, and that it was suggested you use `formState` as the dependency, but this is what seems to be causing the loop.

**To Reproduce**

1. Go here: https://codesandbox.io/s/suspicious-moon-iqpi3?file=/src/App.js:431-777
2. Uncomment line 23.
4. See the “Render Count” in the header climb.

**Codesandbox link (Required)**
https://codesandbox.io/s/suspicious-moon-iqpi3?file=/src/App.js:431-777

**Expected behavior**
I would expect to be able to update local state with the `valid` array value.

**Desktop (please complete the following information):**

- OS: macOS Big Sur 11.4
- Browser: Brave
- Version: 1.26.74 Chromium: 91.0.4472.124 (Official Build) (x86_64)

**Comment by bluebill1049** [comment]
```tsx
useEffect(() => {
    const dirty = Object.keys(formState.dirtyFields);
    const errored = Object.keys(formState.errors);
    const valid = !!dirty.filter((key) => errored.indexOf(key) < 0);
    updateValidFields(valid);
}, [formState]);
```

your valid is not return a boolean instead an array of objects.

**Comment by brandondurham** [comment]
The `valid` above returns an array of field names, like `["firstName"]`, which is what I want. If I use a boolean like you suggest, it works, but I’m looking for an array of valid field names.

**Comment by bluebill1049** [comment]
Then it's not an issue with react hook form: https://codesandbox.io/s/fancy-meadow-hii8i?file=/src/App.js

**Comment by tedliang** [comment]
You might not need to use hook at all.
```
const dirty = Object.keys(formState.dirtyFields);
const errored = Object.keys(formState.errors);
const validFields = dirty.filter((key) => errored.indexOf(key) < 0);
```

**Comment by bluebill1049** [comment]
agreed @tedliang you don't need `useEffect`

**Comment by brandondurham** [comment]
I ended up using `useMemo` just to store valid panels any time new fields are added or removed to the `valid` array.

```js
const validPanels = useMemo(() => {
	const validPanels = [];
	panels?.requiredFields.length && panels.requiredFields.forEach(panel => {
		const validFields = intersection(panel.fields, valid);
		if (validFields.length === panel.fields.length) {
			validPanels.push(panel.panel);
		}
	});
	return validPanels;
}, [panels.requiredFields, valid]);
```
I really appreciate the help! Thanks so much.
