### ISSUE TITLE
A bug relates to 'Standard Reset Field Values' button in this example

### ISSUE THREAD

**Issue by jeven2016** [react-hook-form/react-hook-form#5997]
**Describe the bug**
Reset button cannot remove the form data 

**To Reproduce**
1. Go to this sample: https://codesandbox.io/s/react-hook-form-reset-v7-r7m5s
2.  change the code in line 14:
   const onSubmit = (data, e) => {
    alert(JSON.stringify(data));
  };
3. enter 'abc' in firstName and lastName fields
![1](https://user-images.githubusercontent.com/21193241/126098277-8bb43026-1b30-4bce-b031-5fdef15f84d3.png)
4. click button 'Standard Reset Field Values' to reset
5. both the firstName and lastName are blank
6. click the submit button, you can find the validation is passed but the old data is returned
![2](https://user-images.githubusercontent.com/21193241/126098523-9f47cc43-0c37-4dbd-bba1-60d0b884cfb8.png)

**Codesandbox link (Required)**
Using this sample: https://codesandbox.io/s/react-hook-form-reset-v7-r7m5s?file=/src/index.js

V7
Version is : 7.11.1

**Comment by bluebill1049** [comment]
that line is been removed.
