### ISSUE TITLE
Problem validating checkbox group

### ISSUE THREAD

**Issue by hbarcelos** [react-hook-form/react-hook-form#600]
**Describe the bug**
I have a group of checkboxes that need validation. The rule can vary, but let's consider that the user must select at least 1 of the available items.

I wrote a custom validation function which would get the value of the multiple checkboxes (with `getValue`) and check if the number of checked items is greater than 1.

The problem is that the array fields are exposed not as an array, but put into an object with a key like `'themes[0]'`.

**Non-optimal Solutions**
1. One could start tumbling around with object keys to check for partial matches, extract the values and check for the length of selected cases. However this is at least error-prone in simple scenarios and a true nightmare with nested fields.
2. Using `watch` doesn't seem like an option, because the validate function will be always one render before the component itself.

**To Reproduce**
1. Go to the codesandbox linked bellow
2. Click on the submit button and you will see the error being properly shown in the console.
3. Uncomment the following lines:
    ![Code to Uncomment](https://user-images.githubusercontent.com/16565602/69890411-451b3880-12d4-11ea-92e6-8bc4acbb798c.png)
4. Submit the form again to see what `getValues()` returns in the validation function.

**Codesandbox link**
https://codesandbox.io/s/rhf-multiple-checkboxes-validation-bdhii

**Expected behavior**
`getValues` should probably expose an array field as a proper array, instead of put it in an object with `<name>[<index>]` key, the same way it does on `handleSubmit`.

**Screenshots**
Here's what `getValue()` returns:
![image](https://user-images.githubusercontent.com/16565602/69889970-8b6f9800-12d2-11ea-959d-134905a17786.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 70.0.1

**Comment by bluebill1049** [comment]
`getValues({ nested: true})` ?

**Comment by hbarcelos** [comment]
Oh boy... The one time I don't read the docs properly :sweat: 

That will probably do it.

Thank you very much.

**Comment by hbarcelos** [comment]
Sorry, I'd like to reopen this because it is related.
I'm trying to emulate the `onChange` mode for multiple checkboxes as well.

**Describe the bug**
`triggerValidation` won't work properly on `onChange` handler.

To Reproduce
Steps to reproduce the behavior:

1. Go to the codesandbox linked bellow
2. Submit the form the trigger the validation
3. Toggle some checkboxes in the last field
4. See that validation errors only disappears when I select all of the checkboxes, but the validation rule only requires 2.

**Codesandbox link**
https://codesandbox.io/s/rhf-multiple-checkboxes-validation-bdhii

**Expected behavior**
It should

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/rhf-multiple-checkboxes-validation-delete-e9hp8

**Comment by bluebill1049** [comment]
closing this issue as the solution is above :)
