### ISSUE TITLE
Custom onChange Documentation missing name tag

### ISSUE THREAD

**Issue by georgiossalonad** [react-hook-form/react-hook-form#6003]
In the documentation for the custom onChange found here

https://react-hook-form.com/api/useform/register/

the name tag is missing from the following part

```
const firstName = register('firstName', { required: true })
<input 
  onChange={(e) => {
    firstName.onChange(e); // method from hook form register
    handleChange(e); // your method
  }}
  onBlur={firstName.onBlur}
  ref={firstName.ref} 
/>
```

Without the `name={firstName.name} `the register is not working. Add this please in the docu.

**Comment by bluebill1049** [comment]
no, it should use worked.
