### ISSUE TITLE
number-format broken inside v7 example

### ISSUE THREAD

**Issue by Alb93** [react-hook-form/react-hook-form#6006]
**Describe the bug**
number-format broken inside v7 example.

**To Reproduce**
Go to https://codesandbox.io/s/react-hook-form-v7-controller-5h1q5 and try to write inside the component

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-v7-controller-5h1q5

**Expected behavior**
Numbers should be visible when typing

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS
- Browser chrome
- Version 91
- 
**Additional context**
Also it will be useful to understand how the number-format floatvalue can be used as value inside the form.

**Comment by bluebill1049** [comment]
it works due to css
