### ISSUE TITLE
Huge example which contains complex cases and uses most of library functionality

### ISSUE THREAD

**Issue by revich2** [react-hook-form/react-hook-form#6008]
### Discussed in https://github.com/react-hook-form/react-hook-form/discussions/6007

<div type='discussions-op-text'>

<sup>Originally posted by **revich2** July 19, 2021</sup>
I see common problem for most of form libraries or another libraries - many examples, which shows separated corners of library functionality and experience. But in real projects, very often i become collected cases from this examples and sometimes it takes many time for produce code, which collect these cases.

It would be cool to have huge example, which cover most of library functionality in one place.

My real example, which got some pain for my is that:
- Dynamic and huge form
- Drag and drop first level field array and in the same time nested field arrays, for reordering data
- Controlled inputs, which fired change event by click on some button
- One form in another form
- Typings
I could forget some cases, but pretty often forms can be like this.

And my suggestion sounds like this:
- We can create modular example with one form instance, where people can add their own complex cases.
I'm sure it can help to most of users of library and can be some kind of testing.

May be for this example can be need some simple backend.

@bluebill1049 and anyone reader, what do you think about this?
</div>

**Comment by bluebill1049** [comment]
It's not an issue, let's discuss in discussion.
