### ISSUE TITLE
How can I create a dependent field?

### ISSUE THREAD

**Issue by nguyenhuudungz** [react-hook-form/react-hook-form#6009]
I have 5 fields that are dependent on each other. How can I create that form with `react-hook-form`. Formik supports it out of the box. 

https://formik.org/docs/examples/dependent-fields

**Comment by bluebill1049** [comment]
Use trigger for depend fields.

**Comment by nguyenhuudungz** [comment]
> Use trigger for depend fields.

I tried to code like this but it didn't work. What I want is if `firstName` is typed, then `lastName` change, if `lastName` is typed, then `firstName` change too.

```
  const firstName = watch('first_name');
  const lastName = watch('last_name');

  useEffect(() => {
    if (firstName !== undefined) {
      setValue('last_name', firstName);
    }
  }, [firstName, setValue]);

  useEffect(() => {
    if (lastName !== undefined) {
      setValue('first_name', lastName);
    }
  }, [lastName, setValue]);
```

**Comment by nguyenhuudungz** [comment]
Also, how can I know which input is an independent field currently?

**Comment by bluebill1049** [comment]
do that `onChange`.

```tsx
const test = register('test');
<input {...test} onChange={(e) => {
  test.onChange(e);
  trigger('otherinput')
}} />
```

**Comment by nguyenhuudungz** [comment]
> Also, how can I know which input is an independent field currently?

Tks a lot!!! But what about detect independent field?

**Comment by nguyenhuudungz** [comment]
> do that `onChange`.
> 
> ```tsx
> const test = register('test');
> <input {...test} onChange={(e) => {
>   test.onChange(e);
>   trigger('otherinput')
> }} />
> ```

Also, it doesn't work if I set `test` programmatically. It only works if I type on the input.

**Comment by nguyenhuudungz** [comment]
I think we should create `this dependent feature`, right?

**Comment by ansgarsteinkamp** [comment]
I'm looking for the feature "Dependent Fields", too. Doesn't seem to work with trigger and onChange. Nothing in the documentation or in the Code Examples regarding that topic. Or am I wrong?

**Comment by nguyenhuudungz** [comment]
@ansgarsteinkamp Until they support it, you can implement it as I did in the code above.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/useform/register

<img width="680" alt="Screen Shot 2021-11-06 at 11 48 20 pm" src="https://user-images.githubusercontent.com/10513364/140610201-1cb54c00-4924-4499-9360-2ab934d6dbab.png">

```
<input
  {...register("test", {
    deps: ['inputA', 'inputB'],
  })}
/>
```

**Comment by ansgarsteinkamp** [comment]
Thanks for the answer! I don't want to trigger validation, though. I want to set a registered value depending on another registered value.
With useEffect, setValue and watch I succeeded meanwhile. The docs of react-hook-form were no help for me in this case. Sometimes they are quite hard to understand, in my opinion.

**Comment by nguyenhuudungz** [comment]
> https://react-hook-form.com/api/useform/register
> 
> <img alt="Screen Shot 2021-11-06 at 11 48 20 pm" width="680" src="https://user-images.githubusercontent.com/10513364/140610201-1cb54c00-4924-4499-9360-2ab934d6dbab.png">
> 
> ```tsx
> <input
>   {...register("test", {
>     deps: ['inputA', 'inputB'],
>   })}
> />
> ```

The doc says that `Validation will be triggered for the dependent inputs,it only limited to register api not trigger.`. So it is for validation trigger, what we need is if you change A, then B change too. Like this:

https://formik.org/docs/examples/dependent-fields

**Comment by ansgarsteinkamp** [comment]
Yes, that's the point. Validation-Triggering is not what we are looking for.
Change A => Change B
Dependent Fields

**Comment by bluebill1049** [comment]
then I don't see the difficulty in here, either do we need to support this, because it's already working. Include programmatically update.

https://codesandbox.io/s/dazzling-currying-dwin1?file=/src/App.tsx

```tsx
import { useForm } from "react-hook-form";

export default function App() {
  const { watch, register, handleSubmit, setValue, formState } = useForm({
    defaultValues: {
      a: "",
      b: "",
      c: ""
    }
  });
  const onSubmit = (data: FormValues) => console.log(data);
  const [a, b] = watch(["a", "b"]);

  useEffect(() => {
    if (formState.touchedFields.a && formState.touchedFields.b && a && b) {
      setValue("c", `${a} ${b}`);
    }
  }, [setValue, a, b, formState]);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input {...register("a")} placeholder="a" />
      <input {...register("b")} placeholder="b" />
      <input {...register("c")} placeholder="c" />
      <input type="submit" />

      <button
        type="button"
        onClick={() => {
          setValue("a", "what", { shouldTouch: true });
          setValue("b", "ever", { shouldTouch: true });
        }}
      >
        trigger value
      </button>
    </form>
  );
}
```

**Comment by ansgarsteinkamp** [comment]
Thank you Bill! That's exactly how I made it work. With useEffect, setValue and watch.
Just missing in the docs so far.

**Comment by ansgarsteinkamp** [comment]
In a nutshell: 
`useEffect(() => {
      if (!!watch("B") {
         setValue("A", watch("B");
      }
   }, [watch("B"), setValue]);`

**Comment by ansgarsteinkamp** [comment]
Unfortunately, my solution with watch() and useEffect is very slow with lots of re-rendering. So, there doesn't seem to be a reasonable way to handle Dependent Fields with React-Hook-Form. Or at least no solution I am able to understand. Thinking about switching to Formik. :(
