### ISSUE TITLE
setValue called on field array causes append to crash if fieldArray is not previously mounted

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#6010]
**Describe the bug**
In my app, I have a complex form and I need to call `setValue` to change a field array before the field array can be mounted. Previously, at the root level of the component I would add in:

```
useFieldArray({
  name: "myArray"
});
```

to make this work. However, this stopped working in newer versions and resulted in bugs so I removed it (see #5967). Now it seems like there is a crash that occurs when using `setValue` and `append` if this is omitted.

**To Reproduce**

1. Go to the sandbox
2. Click on show child
3. Click append
4. See the crash

**Codesandbox link (Required)**
https://codesandbox.io/s/cranky-bassi-y36gm?file=/src/App.js:260-298

**Expected behavior**
I really don't know what to do here in the newer versions to get past this. If I add in 

```
useFieldArray({
  name: "myArray"
});
```

before running `setValue`, then `fields` get out of sync with `formValues` (#5967). If I don't I get a crash when trying to use append. I can't just keep everything mounted because I'm using external modals that unmount their children to show my forms. Essentially I need to be able to change an array value with `setValue` before I can mount it and still have everything after like append work properly. @bluebill1049 do you have any advice here?

**Comment by bluebill1049** [comment]
`setValue` will not create a field array.

you are trying to use `setValue` to create a field array, and then assume `append` will append another item on top of `setValue. This will not work.

I would useFieldArray up and have a single useFieldArray instance instead of `setValue` but use `append`. I will prepare a PR to prevent the crash, but will not enable the above ussage.

**Comment by wdfinch** [comment]
Thanks for the PR. I didn't know that `useFieldArray` created the field array and thought it would be registered and created via the deep merge update you made. So really I need to use `reset` then since I'm trying to change the default values of the field array. I guess a `setDefaultValue` (or options to `setValue`) or `useFieldArray` context could be useful in this use case. Not sure if enough users need to change field array values before it's mounted/created though to make it worth while. Anyway thanks for the information and help. I really appreciate it.

**Comment by bluebill1049** [comment]
no worries @wdfinch being busy lately sorry if I didn't reply your message or delaed rely.

**Comment by wdfinch** [comment]
No worries! I know how many people open issues each day and how on top of it you are so really appreciate it.
