### ISSUE TITLE
Typescript - Potential runtime error onChange due to `event: any`

### ISSUE THREAD

**Issue by Newbie012** [react-hook-form/react-hook-form#6018]
**Describe the bug**

There's a potential runtime error when using `register` on an input that is not returning an event as the first argument due to this line:

https://github.com/react-hook-form/react-hook-form/blob/885257c74c380a33038e71a50fdaa228c69fb109/src/types/form.ts#L81

According to this line, the first argument accepts any value. I'm using [@react-aria](https://github.com/adobe/react-spectrum/tree/main/packages/%40react-aria) in order to build a custom `<Checkbox />` component, which returns `(isSelected: boolean) => void` instead of the input onChange signature.

**To Reproduce**

1. Go to https://codesandbox.io/s/affectionate-morse-kk7oo?file=/src/App.tsx
2. Click on `Toggle me 😐`

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

V7

https://codesandbox.io/s/affectionate-morse-kk7oo?file=/src/App.tsx

**Expected behavior**
The compiler should throw an Error that `(isSelected: boolean) => void` doesn't match the signature of `(e: EventOrSomethingElse) => void`;

**Comment by bluebill1049** [comment]
Thanks for the issue, i don't think we can predict the event target value send by all types of custom-controlled components. That's why it's an `any`.

**Comment by Newbie012** [comment]
@bluebill1049 You don't need to predict the event target, you can set it as unknown (Although I believe you can if you pass it down). I suggest changing this line to:

```ts
 export type ChangeHandler = (event: React.ChangeEvent<unknown>) => Promise<void | boolean>; 
```

This way, you get more type safety:

![image](https://user-images.githubusercontent.com/10504365/126477533-e82b9a59-c241-463e-ad78-8210b59ab099.png)

I suggest reopening this issue since it's actually a bug and it's fixable. I'm willing to create a PR if necessary.

**Comment by bluebill1049** [comment]
Thanks, @Newbie012 🙏 what bout a use case when it's not React.ChangeEvent, when the user just wants to pass some data?

```tsx
const test = register('test') 

test.onChange('whatever')
```

I understand to be more strict on the type, but I hope to give users the freedom on certain use cases as well.

**Comment by bluebill1049** [comment]
By the way, I appreciate your PR and willing to help out as well. 🙏

**Comment by Newbie012** [comment]
@bluebill1049 then he will get a runtime error. see:

```ts
import * as React from "react";
import { useForm } from "react-hook-form";

type FormValues = {
  firstName: string;
};

export default function App() {
  const { register, handleSubmit } = useForm<FormValues>();
  const onSubmit = (data: FormValues) => console.log(data);
  const test = register("firstName");

  const surprise = () => {
    test.onChange("whatever")
  }


  return (
    <div>
      <form onSubmit={handleSubmit(onSubmit)}>
        <label>
          <button onClick={surprise}>😭</button>
        </label>
      </form>
    </div>
  );
}
```

demo - https://codesandbox.io/s/distracted-rgb-fr5x7?file=/src/App.tsx:0-557

**Comment by bluebill1049** [comment]
valid! @Newbie012 I think i should refer to the `Controller`, https://codesandbox.io/s/weathered-sound-bk471?file=/src/App.tsx if the type change is only target on `register`, I think we can do that.

**Comment by bluebill1049** [comment]
happy to apply on the change for `register`, just checked the type. feel free to send a PR if you have time @Newbie012

**Comment by Newbie012** [comment]
@bluebill1049 ready - https://github.com/react-hook-form/react-hook-form/pull/6030

**Comment by bluebill1049** [comment]
thank you @Newbie012

**Comment by bluebill1049** [comment]
I will close this issue for now. 👍

**Comment by ifeltsweet** [comment]
Stumbled here because we are also looking for a way to make `onChange` coming from `Controller` accept a strict type. Currently, we are resorting to something like this:

```tsx
export function strictField<T extends ControllerRenderProps>(
  field: T
): Omit<T, 'onChange'> & { onChange: (value: T['value']) => void } {
  return field;
}

<Controller render={({ field }) => <Autocomplete onChange={strictField(field).onChange} ...etc />} />
```

**Comment by oliverbutler** [comment]
@ifeltsweet Also researching this (a year later 😓 ), you could also potentially make a `declare` to change the typescript definition globally...?
