### ISSUE TITLE
Deep Nested field Array -  Previous nested values dont get cleaned when inserting new item

### ISSUE THREAD

**Issue by Bair95** [react-hook-form/react-hook-form#6026]
**Describe the bug**
First of all many thanks to all the contributor of this awesome project. 
You saved me so much time with this library that i lost the count.

I'm not sure if it's a regression or a new bug as i've seen some closed issues referring to this behavior.
I think it's very close to : https://github.com/react-hook-form/react-hook-form/issues/5696 
Feel free to discard this issue if it's the same.

When trying to insert an item in a deep nested field, it seems that the previous nested values aren't cleaned so the newly added option get filled with the previous value

**To Reproduce**

1. Go to https://codesandbox.io/s/angry-fog-01z49
2. Wait for the data to be populated (timeout=3s)
3. In the Section 0, Click on "Add New options list"
3. On the newly created field (at the top), click on "Add new suboption"
4. See that the nested value of the first field is "test" ( it should be "" )

**Codesandbox link (Required)**
https://codesandbox.io/s/angry-fog-01z49

**Expected Behavior**
Newly created value should be empty

**Comment by bluebill1049** [comment]
<img width="486" alt="Screen Shot 2021-07-21 at 6 52 24 pm" src="https://user-images.githubusercontent.com/10513364/126460659-81f39570-e236-4e55-858e-0723b6211fc7.png">

Thanks for the issue report, but seriously this does make my life any easier to reproduce an issue, can you simply the codesandbot to isolate the problem.

**Comment by Bair95** [comment]
Thanks for the quick response.
I'm sorry for this mess i've cleaned up the CSB before submitting but it didnt saved my changes.
I've updated it now it should be cleaner.
