### ISSUE TITLE
Latest Release (3.28.10) isValid is initially false

### ISSUE THREAD

**Issue by krnlde** [react-hook-form/react-hook-form#603]
**Describe the bug**
The problem started between the version `3.28.10-beta.1` and `3.28.10` (final). The `isValid` is initially false, despite all the values are correctly set. If I move back to `3.28.10-beta.1` or `3.28.9` it works. Unfortunately I can't do a reproducible codesandbox since the final version is not yet selectable there. Anyways I did an exact replicate of my setup in codesandbox, which will fail in the final `3.28.10` version as soon at is selectable there.

**To Reproduce**
1. Go to https://codesandbox.io/s/delicate-rain-pehsz
2. See that the submit button is initially disabled because the form is invalid

**Codesandbox link**
https://codesandbox.io/s/delicate-rain-pehsz

**Expected behavior**
The form should be initially valid: `isValid === true`

**Desktop (please complete the following information):**
 - OS: Win10 1909
 - Browser Chromium Edge
 - Version 80.0.346.0

**Additional context**
If I hit `triggerValidation` directly after init, it will get valid, but again, only in the final `3.28.10` version which is - at the time of writing - _not_ selectable in codesandbox

**Comment by bluebill1049** [comment]
that was my bad! I will patch it now. I know why too...

**Comment by bluebill1049** [comment]
can you verify the fix for me, please? getting close to midnight going to sleep now before work tmr :)

**Comment by krnlde** [comment]
Verified, `3.28.11` works. Is it possible to do a regression test for this issue? I remember, we had that bug before. I saw cypress, but have no experience with it.

**Comment by bluebill1049** [comment]
@krnlde I have added a todo for myself to do some unit test or cypress to cover this. would be amazing if you could contribute on this tho @krnlde sorry for breaking it too, i was refactoring some of the bad parts.
