### ISSUE TITLE
`useWatch` doesn't react to value changes caused by a `defaultValue` being set via `useController(...)`

### ISSUE THREAD

**Issue by giovannipiller** [react-hook-form/react-hook-form#6034]
**Describe the bug**
`useWatch` doesn't react to value changes caused by a `defaultValue` being set via `useController(...)`/`register(...)`

**To Reproduce**

1. Go to https://codesandbox.io/s/xenodochial-forest-tez5p?file=/src/App.tsx
2. `<WatchingCustomInput>` will render in the page, setting up an `useWatch({ control, name: "myInput" })` which correctly returns `undefined`, since no "myInput" has been registered in the page
3. `<CustomInput>` then gets rendered, which sets up a `useController(name: "myInput", defaultValue: "myDefaultValue")` which correctly sets the value for `myInput` to `"myDefaultValue"`

**Expected behavior**
At this point, I would expect `<WatchingCustomInput>` to re-render, since `myInput` changed from `undefined` to `"myDefaultValue"`, but that doesn't happen.

**Codesandbox link (Required)**
- https://codesandbox.io/s/xenodochial-forest-tez5p?file=/src/App.tsx
- [here's a similar example using `watch()` instead](https://codesandbox.io/s/mutable-sky-t3sbv?file=/src/App.tsx), the results are the same

**Desktop:**

- OS: macOS
- Browser: chrome
- Version: 91.0.4472.114

**Additional context**
While the example itself might make little sense, I've synthesised it from a much more complex form that involves components reacting to values set by other components.

In my own code, `defaultValue` is a bit unpredictable, which is the reason why I choose to populate it via `useController` rather than supplying it directly to the `useForm`.
I'm using `useWatch` from another component assuming it always returns the current value for the watched field.

If anybody has suggestions or needs more examples from my end, just let me know.

Thanks! 😊

**Comment by bluebill1049** [comment]
UseWatch or watch doesn't render based on defaultValue change and it's expected behaviour.

**Comment by giovannipiller** [comment]
@bluebill1049 is there a way to react to a defaultValue being set?

> UseWatch or watch doesn't render based on defaultValue change and it's expected behaviour.

May I ask why?
While I could see that it would make sense when `defaultValues` is supplied to a `useForm`, it does seem quite limiting when dealing with `useController`, which can supply its own `defaultValue` and be added to a form at any time and in any place.

In other words: the form data will change as new defaultValue are added to it by `useController`/`register` inserted conditionally. What approach should be used to monitor those values being added?

Right now, there seem to be no way of knowing when new data is inserted, except if manually set via `setValue` or actively changed by a user.

Would an option to `useWatch`/`watch` make sense?

----

## Practical example
https://codesandbox.io/s/distracted-grass-j89ve?file=/src/App.tsx

In this example scenario, the user will land on a page where the checkbox "Yes, I'd love to get spam in my email" is checked by default (`hasUserAcceptedPrivacyPolicy` will have a `defaultValue: true`). Note that in real life, this `defaultValue` could be determined by an API call, local storage, cookie, or whatever.

The email `<input>` inside `<UserEmail>` is inserted in the page whenever the field `hasUserAcceptedPrivacyPolicy` is set to true.
I'm using `useWatch` to monitor `hasUserAcceptedPrivacyPolicy` and react accordingly.

### Expected result
- "Yes, I'd love to get spam in my email" is checked
- `<UserEmail>` displays an input for the user to provide an email

### Actual result
- "Yes, I'd love to get spam in my email" is checked
- `<UserEmail>` thinks that `hasUserAcceptedPrivacyPolicy` is `undefined`, and therefore doesn't display the input

**Comment by bluebill1049** [comment]
Thanks for the detailed reply. 

### Why defaultValue is not triggered a watching update?

Because react hook form is uncontrolled by default, which means default value is for `defaultValue` for the initial render.

### What if I want to make changes to input and trigger watch?

use `setValue` will trigger watch to update input change.

I hope the above explain and give solution to your use case.

**Comment by giovannipiller** [comment]
@bluebill1049 Thank you so much for the replies.

> use setValue will trigger watch to update input change.

I've been trying to implement this solution by removing the `defaultValue` from the `useController(...)`, and setting it using a `useEffect` when the component is rendered. Something like this:

```typescript
const myOwnDefaultValue = true;
React.useEffect(() => {
  // checking for undefined, to simulate setting a default value
  if (field.value === undefined)
    setValue("hasUserAcceptedPrivacyPolicy", myOwnDefaultValue);
}, [field.value, setValue]);
```

However, while the value for `hasUserAcceptedPrivacyPolicy` is effectively set to `true`, the `useWatch` won't trigger. Therefore, `<UserEmail>` won't display an input.

https://codesandbox.io/s/wizardly-pasteur-rq8z1?file=/src/App.tsx

## Hacky workaround

I noticed that letting the `useEffect` run twice, makes things work. I'm assuming that it's just a coincidence, probably something related to `watch` beginning to subscribe to changes only after a some other event.

 ```typescript
const myOwnDefaultValue = true;
React.useEffect(() => { 
  if (field.value === undefined || field.value === myOwnDefaultValue)
    setValue("hasUserAcceptedPrivacyPolicy", myOwnDefaultValue);
}, [field.value, setValue]);
```

https://codesandbox.io/s/clever-hooks-whzud?file=/src/App.tsx

----

Another _terrible_ hack would be using a `setTimeout` or some sort of empty `async/await`, to delay the run of the first `useEffect`.
This again makes me think that I'm calling the `setValue` way before RHF has started watching for value changes to notify via `watch`.

```typescript
const myOwnDefaultValue = true;
React.useEffect(() => {
  setTimeout(() => {
    if (field.value === undefined)
      setValue("hasUserAcceptedPrivacyPolicy", myOwnDefaultValue);
  });
}, [field.value, setValue]);
```

This of course doesn't look like something sane to do 😰.

https://codesandbox.io/s/brave-margulis-70ic1?file=/src/App.tsx

----

Am I doing something wrong here?

**Comment by bluebill1049** [comment]
Can you post this in the Github discussion? i will have a look at it tmr.
