### ISSUE TITLE
isValid is true even if the dynamic required fields are empty

### ISSUE THREAD

**Issue by wtchnm** [react-hook-form/react-hook-form#6035]
**Describe the bug**
isValid is true even if the dynamic required fields are empty.

**To Reproduce**

1. Set the marital status to single. The button is enabled.
2. Set the marital status to married. The button is disabled.
3. Set the marital status to single. The button is enabled.
4. Set the marital status to married. The button is enabled!!!

**Codesandbox link (Required)**
https://codesandbox.io/s/rhf-controller-l00mp

**Expected behavior**
isValid should be false if the dynamic required fields are empty.

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Brave, Firefox
- Version: 1.26.74 (Chromium: 91.0.4472.124), 90.

**Additional context**
If the dynamic field is focused, the button will be disabled.

**Comment by bluebill1049** [comment]
<img width="585" alt="Screen Shot 2021-07-22 at 8 13 40 am" src="https://user-images.githubusercontent.com/10513364/126566831-ea61f2b1-28dc-4d11-9e7f-bd99b642cf5a.png">

your input components are both required.

**Comment by wtchnm** [comment]
Sorry Bill, but I think you misunderstood. I know that the dynamic fields are required. The problem is that, if you follow the steps that I provided, RHF will think that the dynamic fields are no required.

**Comment by bluebill1049** [comment]
because we do no `unregiseter` input after unmount. read the doc on `shouldUnregister`.

**Comment by wtchnm** [comment]
Yeah, shouldUnregister is set to true.

**Comment by wtchnm** [comment]
@bluebill1049 can you investigate this further please?

**Comment by bluebill1049** [comment]
hey @wtchnm should have been fixed last night with this commit https://github.com/react-hook-form/react-hook-form/pull/6053

**Comment by wtchnm** [comment]
Unfortunately not, but I can confirm that the problem is with the Controller: https://codesandbox.io/s/rhf-register-el146

**Comment by bluebill1049** [comment]
It's not even released. Will get it released this weekend.

**Comment by wtchnm** [comment]
Yes I know, I cloned the react-hook-form repo, built and tested it via `yarn link`.

**Comment by bluebill1049** [comment]
let me confirm.

**Comment by bluebill1049** [comment]
i don't get the issue in here.

select: required
input: required
input: required

- when you mount select required but empty, so false
- select married false
- when you select single, it's correct to be **true** right?
  - select: required (pass) the other two inputs are unmounted

**Comment by wtchnm** [comment]
To reproduce you have to do the following:

1. Set the marital status to single. The form is valid.
2. Set the marital status to married. The form is invalid.
3. Set the marital status to single. The form is valid.
4. Set the marital status to married. The form is still valid. This is the problem.

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/126850930-e37e6dae-46ae-4c9b-993f-c0b7df435611.mov

are you sure you are using the latest code?

**Comment by wtchnm** [comment]
Oh, this is the sandbox that I created using register. This works. The one that not works is using Controller: https://codesandbox.io/s/rhf-controller-l00mp.

**Comment by wtchnm** [comment]
Thanks!
