### ISSUE TITLE
`setValue` fails with an array of objects

### ISSUE THREAD

**Issue by avremel** [react-hook-form/react-hook-form#6038]
**Describe the bug**
According to the [docs](https://react-hook-form.com/v5/api#setValue), I should be able to `setValue` with an array of objects:

```js
// set multiple values
setValue([
    { test : "1", },
    { test1 : "2", },
])
```

Instead, an error is thrown: `TypeError: path.split is not a function`

**To Reproduce**
Create a form with uncontrolled fields using [this example](https://react-hook-form.com/get-started#Integratinganexistingform). Inside a `useEffect`, pass an array of objects to `setValue` and observe the error.

**Codesandbox link (Required)**
https://codesandbox.io/s/awesome-paper-njcdd?file=/src/App.js

**Expected behavior**
Be able to update multiple values in the form using `setValue` without raising an error.

**Screenshots**
<img width="790" alt="Screen Shot 2021-07-21 at 5 24 09 PM" src="https://user-images.githubusercontent.com/10588097/126562112-612c48a6-dc70-449b-9f34-0151915ccc14.png">

**Desktop (please complete the following information):**

- react-hook-forms 7.11.1
- OS: macOS Big 11.4
- Browser Chrome
- Version 91.0.4472.164

**Comment by bluebill1049** [comment]
Use object instead of array.

**Comment by bluebill1049** [comment]
{ email: xxx }

**Comment by avremel** [comment]
@bluebill1049 
Using an object doesn't seem to help. CSB: https://codesandbox.io/s/long-bush-y389i?file=/src/App.js

The error in the source code seems to be because the function `setValue` is always expecting the `name, value` signature. https://github.com/react-hook-form/react-hook-form/blob/e32797b2c752a338eea4011085fb00055e7c6a0a/src/useForm.ts#L592

Would you like me to open a PR to remove that example from the docs?

**Comment by avremel** [comment]
My bad, I was looking at V5 documentation.

**Comment by bluebill1049** [comment]
all good.
