### ISSUE TITLE
Nested 'useArray' problem when swap parent array

### ISSUE THREAD

**Issue by Raphaww** [react-hook-form/react-hook-form#6040]
**Describe the bug**
I have an array within an array and when I make a swap in the items of the parent array, the values of the child array are kept in the wrong index.

**To Reproduce**
To reproduce open the codesandbox link:

1.  Notice how the first item has a child with the name property 'child of index 0' and the second item has no children.
<img width="200" alt="Screen Shot 2021-07-21 at 19 05 53" src="https://user-images.githubusercontent.com/7801116/126575252-6f558e11-bafd-4d04-bce3-0ed30091130b.png">

2. CLICK the button 'Up' in the second item, that changes the position of the items in the parent array, now the first item is the one with no children
<img width="200" alt="Screen Shot 2021-07-21 at 19 06 03" src="https://user-images.githubusercontent.com/7801116/126575255-a81fd2b1-eb36-4d40-8674-9fb39980f222.png">

3. CLICK the 'Add Child' button on the first item, notice how the created input has the same value of the previous item in that position
<img width="200" alt="Screen Shot 2021-07-21 at 19 06 17" src="https://user-images.githubusercontent.com/7801116/126575262-b314d53f-4259-4596-b9b5-1212e069911c.png">

4. It should be an empty text.    
<img width="200" alt="Screen Shot 2021-07-21 at 19 06 36" src="https://user-images.githubusercontent.com/7801116/126575268-5025f755-75d2-4c2a-b852-6c7077330bce.png">

**Codesandbox link (Required)**

- [JS](https://codesandbox.io/s/youthful-williamson-rxnzo) Template

**Expected behavior**
values of previous items should not be kept in new items when a swap is made 

**Desktop (please complete the following information):**

- OS: [MacOS BigSur 11.4]
- Browser [chrome]
- Version [91.0.4472.114 (Official Build) (arm64)]

**Additional context**

**Comment by bluebill1049** [comment]
try to remove all your `defaultValue`

**Comment by bluebill1049** [comment]
This is not a bug...

```
<button
  type="button"
  onClick={() => children.append({})}
  className="leading-6 py-1.5 px-3 border rounded-md font-medium"
>
  Add Child
</button>
```

you append with an empty object, it's required.

**Comment by Raphaww** [comment]
Hello, Im sorry I submitted an incomplete example, now I've updated it and added an non-empty object and it solves the problem, however when that object is more than one level deep, those default values are overwritten on fields using <Controller /> 

<img width="300" alt="Screen Shot 2021-07-22 at 11 04 00" src="https://user-images.githubusercontent.com/7801116/126671629-826f767d-bb03-4ea2-9e55-485f49d2f20b.png">

The steps to reproduce are the same:

https://codesandbox.io/s/youthful-williamson-rxnzo

I know is a very edgy case, thank you for giving it some of your time. I really enjoy using this library and I've done my best to understand it, I'm sorry if I'm doing something wrong.

**Comment by bluebill1049** [comment]
no worries, can you share the steps with the above? I think it's doing to with nested objects but using as flat field with the controller. have a look at this thread: https://github.com/react-hook-form/react-hook-form/discussions/6028

**Comment by Raphaww** [comment]
Hello, from what I can see in that thread it's the same issue and it has to do only with the use of <Controller /> and nested objects, not sure if I understand you but Im sharing the steps again: 

1. Open https://codesandbox.io/s/youthful-williamson-rxnzo
2. Notice how the first item has a child with the following data (it includes a nested object): `{
   name: "child of index 0",
   position: "RIGHT",
   options: {
      name_b: "options index 0",
      position_b: "RIGHT"
   }
}` and the second item has no children.
<img width="300" alt="Screen Shot 2021-07-22 at 18 07 07" src="https://user-images.githubusercontent.com/7801116/126720374-9a5d31b8-4383-4537-9126-3860d418e90f.png">


3. CLICK the button 'Up' in the second item; that changes the position of the items in the parent array, now the first item is the one with no children
<img width="300" alt="Screen Shot 2021-07-22 at 18 07 20" src="https://user-images.githubusercontent.com/7801116/126720382-2b4d469b-76ed-4531-9c95-2188d09b0108.png">

4. CLICK the 'Add Child' button on the first item, notice how the created input has defaults values EXCEPT on the 'Options position' value which is nested and it's using `<Controller />`. 'RIGHT' is highlighted when it should be the default 'LEFT'
<img width="300" alt="Screen Shot 2021-07-22 at 18 10 45" src="https://user-images.githubusercontent.com/7801116/126720396-5e432b0a-f48d-45a3-afe0-4b02b3f1c3ff.png">

**Comment by bluebill1049** [comment]
Yes, I believe it's the same issue as well, I have provided a workaround there, see if it can be fixed for your project now.

**Comment by bluebill1049** [comment]
I will test if the fix i had will resolve your use case as well.

**Comment by bluebill1049** [comment]
can you confirm if this CSB works? https://codesandbox.io/s/admiring-agnesi-1e8wh?file=/src/TextForm.js:43-48

**Comment by Raphaww** [comment]
yes it works as expected :)

**Comment by bluebill1049** [comment]
sweet! thanks for the update.
