### ISSUE TITLE
conditional yup schema produces error

### ISSUE THREAD

**Issue by mathishuettl** [react-hook-form/react-hook-form#6044]
The condition in my yup schema doesn't update correctly 

**To Reproduce**
Codesandbox: https://codesandbox.io/s/amazing-hawking-d2rmx?file=/src/App.js
1. Click the "Yes" Radio, let the input empty and click on submit
2. Click the "No" Radio and click on submit => Now the conditional schema shouldn't trigger, but it does

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

**Expected behavior**
The validation should pass

**Comment by bluebill1049** [comment]
<img width="1152" alt="Screen Shot 2021-07-22 at 5 55 27 pm" src="https://user-images.githubusercontent.com/10513364/126606378-97c69513-4b60-47d0-8275-012b959dc712.png">

empty.

**Comment by mathishuettl** [comment]
@bluebill1049 sorry, I updated it - can you reopen it again?

**Comment by bluebill1049** [comment]
> Click the "No" Radio and click on submit => Now the conditional schema shouldn't trigger, but it does

I have no idea what do you mean by that, I would debug the resolver see what data is send to your reesolver 

```tsx
reoslver: async (data) => {
  console.log('data', data); // log what's in the form data and hit against your schema
  return yupReoslver(data)
}
```

**Comment by mathishuettl** [comment]
It means, that when I click "no", yup shouldn't validate this part, but it doesn and so the form can't be submitted.

First submit (Radio = no) => everything fine
Second submit (Radios = yes, input = empty) => everything fine, because input is required!
Third submit (Radio = no) => I cant submit


```js
.when("hasBalcony", {
      is: true,
      then: (s) => **s.required("required")**
    })
```
