### ISSUE TITLE
asyncValidate is triggered multiple times (onSubmit also)

### ISSUE THREAD

**Issue by krasimirkostadinov** [react-hook-form/react-hook-form#6045]
### Discussed in https://github.com/react-hook-form/react-hook-form/discussions/6033

<div type='discussions-op-text'>

<sup>Originally posted by **krasimirkostadinov** July 21, 2021</sup>
Hi, i have form with async validation for field, triggerred onBlur. Everything is ok, but onSubmit() this validation (async API call check is triggering again). Is there a way to skip this?

 [Codesanbox example](https://codesandbox.io/s/react-hook-form-async-field-validation-forked-iit46?file=/src/index.js:450-847)

In my case i have multiple step form and on every step i submit subset of form fields. In this case when async check is triggerred again, it's delaying submit and this results to "flashing" screen before continue to next step (happening onSubmit callback). 

Is there way to skip running async validation check again onSubmit()  ?</div>

Does this depends from form mode (onBlur, onSubmit etc) or?

**Comment by krasimirkostadinov** [comment]
@bluebill1049 thanks. If the form mode is "onBlur/onTouched" it still validates onBlur (if registered field and validation), and again onSubmit (async API call).
I can manually trigger specific field validations, but not registering async validaiton, right?

**Comment by bluebill1049** [comment]
> I can manually trigger specific field validations, but not registering async validaiton, right?

i would skip the register to the input, but manually fire those validation.

```tsx
const input = register('test', { validate: () => {} )

onBlur={() => {
  trigger('test');
}}
```

validate will be triggered and called in submit.

**Comment by krasimirkostadinov** [comment]
So you mean in any case i can't stop calling async validate onSubmit? ( i want all validations only onBlur, not onSubmit)

**Comment by bluebill1049** [comment]
`onSubmit` will validate all input's validation, if you don't want to include that in submit, don't put validation in `register`.

**Comment by krasimirkostadinov** [comment]
Right. thanks again.
