### ISSUE TITLE
isValid for custom form component doesn't have the right value

### ISSUE THREAD

**Issue by ajnikgunu** [react-hook-form/react-hook-form#605]
I am trying to use react-hook-form and I was testing it by creating a custom component. I have two textFields in my form. What I want is the submit button to be disabled until the form is valid. I am trying to use isValid to check if the form is valid or not. But I am not getting the behavior I wanted. I have shared the codesandbox link below:

**To Reproduce**
1. Please check the codesandbox link and see the console

**Codesandbox link**
https://codesandbox.io/s/friendly-bird-j67vl

Regards,

**Comment by bluebill1049** [comment]
none of your input have any `validation`

**Comment by bluebill1049** [comment]
```
const MyInput = ({ name, label, register, errors }) => {
  useEffect(() => {
    register({ name: name }, { required: true });
  }, []);
  return (
    <>
      <label htmlFor={name}>{label}</label>
      <input
        name={name}
        placeholder="..."
        ref={register({ required: true })}
        className={cn("form-input", {
          "is-error": errors[name]
        })}
      />
      {errors[name] &&
        errors[name].type === "required" &&
        "This field is required"}
    </>
  );
};
```

**Comment by vatosarmat** [comment]
But `isValid` should also consider `validationSchema`, shouldn't it?
https://codesandbox.io/s/wsd5l

**Comment by bluebill1049** [comment]
@vatosarmat it should.

**Comment by bluebill1049** [comment]
@vatosarmat you want to test this beta version: 3.28.12-beta.1

**Comment by bluebill1049** [comment]
`3.28.12-beta.2`

**Comment by vatosarmat** [comment]
3.28.12-beta.2 works as expected :+1:

**Comment by bluebill1049** [comment]
awesome thanks @vatosarmat i will merge it in and publish it today :)

**Comment by vatosarmat** [comment]
Documentations says "isValid | boolean | Set true if doesn't have any error.". That's not true - isValid is false on untouched form which doesn't have any errors

**Comment by bluebill1049** [comment]
is this an issue almost related to schema validation or both?

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/rhf-schema-isvalid-v551m
I think this fix it.

**Comment by bluebill1049** [comment]
hmm looks like its better to start with true and then set to false. i will change that accordingly

**Comment by bluebill1049** [comment]
3.28.12-beta.3 third attempt to get them all working. i tested working for me, you want to verify @vatosarmat

**Comment by vatosarmat** [comment]
https://codesandbox.io/s/keen-noyce-wsd5l here I have initial `isValid` is `false`. I am not sure about should it be true initially, or not. Maybe introduce some kind of `isInitiallyValid` like [formik does](https://jaredpalmer.com/formik/docs/api/formik#isinitialvalid-boolean). Or just leave it as is... Personally, I just do `hasValidationErrors = Object.keys(errors).length  > 0`

**Comment by bluebill1049** [comment]
@vatosarmat it's correct right? cause your input are invalid against the schema

**Comment by bluebill1049** [comment]
> Personally, I just do hasValidationErrors = Object.keys(errors).length > 0

it's more than that :) i will get it right tho. thanks for helping here.

**Comment by bluebill1049** [comment]
actually it's working 
you had mode set to `mode: "onSubmit",`

**Comment by bluebill1049** [comment]
if you checking isValid it's defeat the purpose of isValid.

**Comment by bluebill1049** [comment]
let me know if this works for you, we can release this patch soon.

**Comment by bluebill1049** [comment]
i am going to close this issue. i think we have resolved and will patch in the next release.
