### ISSUE TITLE
Required validation is not triggered after using "prepend" from "useFieldArray"

### ISSUE THREAD

**Issue by kerendot** [react-hook-form/react-hook-form#6052]
Thanks a lot for this awesome library! This is my first issue report so sorry in advanced if I made any mistakes :)

**Describe the bug**
Required validation is not triggered after using useFieldArray's "prepend" with "Controller". For the same scenario but using "append" (instead of "prepend") - it is working fine.

**To Reproduce**
Using the example here: https://codesandbox.io/s/react-hook-form-usefieldarray-forked-sjixc, click prepend and "submit" (leave the new fields empty). 
Expected behavior - errors should be logged. 
Actual behavior: onSubmit was called.

**Screenshots**

<img width="399" alt="array3" src="https://user-images.githubusercontent.com/29173459/126639227-3c698cfc-d78e-443e-a99f-aa163b4ea047.png">

**Desktop (please complete the following information):**

- OS: win10
- Browser : chrome
- Version : 91.0.4472.164

**Comment by bluebill1049** [comment]
oh wow! good pick up.
