### ISSUE TITLE
Regression Tests

### ISSUE THREAD

**Issue by krnlde** [react-hook-form/react-hook-form#606]
Discussion continued coming from #603 

Regression tests would help to keep issues closed by creating tests that resemble the exact bug description.
 
After a short glance it seems you are using cypress for all your tests - which is _very very_ slow compared to unit- / integration-tests like [Enzyme](https://airbnb.io/enzyme/) or [react-testing-library](https://github.com/testing-library/react-testing-library). Do you use something like that, or are you planning to? I could prepare a scaffold depending on how you decide.

**Edit:** Ah I see you use jest already! Sorry I didn't see that.

**Comment by bluebill1049** [comment]
I am using both @krnlde. I think i have missed unit tests for isValid check, which I have added myself on the todo list to cover that.

**Comment by bluebill1049** [comment]
going to close this issue here :) as I have already added a todo for this 👍let me know if you interested to contribute or i will do it anyhow ❤️

**Comment by krnlde** [comment]
Of course I'd like to help! Could you put a finger on the code where I should add it? I'm not too familiar with your structure, yet :)

**Comment by bluebill1049** [comment]
Yes that would be fantasy! Sorry to delegate to you 😬cause I didn’t get a chance (selected) to a talk at react conference au next year. So I am preparing some tweets around react hook form to spread around the lib in the community 👌🏻
