### ISSUE TITLE
How to get the realtime validation state?

### ISSUE THREAD

**Issue by southorange1228** [react-hook-form/react-hook-form#6060]
### Discussed in https://github.com/react-hook-form/react-hook-form/discussions/6043

<div type='discussions-op-text'>

<sup>Originally posted by **southorange1228** July 22, 2021</sup>
Now, i need to get the realtime validation state in order to disabled the submit button.
i try to use `trigger()`,but `formState.errors` will rerender component and render all errors.

just like this.

https://codesandbox.io/s/strange-dhawan-kk5vp?file=/src/App.tsx

what i should do?</div>

**Comment by bluebill1049** [comment]
please don't spam Github issues. if you have an issue follow the template.

**Comment by southorange1228** [comment]
so could you help me to resolve this discussions？thanks a lot :) @bluebill1049
