### ISSUE TITLE
[Bug]: setValue of type Array has a strange behaviour after resetting the form

### ISSUE THREAD

**Issue by sim-r** [react-hook-form/react-hook-form#6062]
After resetting a form. Calling 'setValue' with an array seems to keep the default value's length and fill it with duplicates of the last element of the current array.

### Version Number

7.7.0+

### Codesandbox

https://codesandbox.io/s/laughing-noether-kvz7c?file=/src/App.js

### Steps to reproduce

1. Click the 'X' on the right side of an element to remove it from the list. It works fine.
2. Click the reset button. The list gets back to its initial test, seems fine.
3. Click any 'X' button again. The list starts duplicating elements

### Expected behaviour

A "watched" value should be the one we passed to "setValue". The behaviour seems fine on version <7.7.0.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
We don't support such usage. Follow the doc with input registration instead.

**Comment by sim-r** [comment]
@bluebill1049 I understand it's not a normal usage of a form but I do use it inside a larger form. It is just a different way to represent a data.

What I don't understand is why setValue behaves differently before and after reset is called. And why it did work before version 7.7.
