### ISSUE TITLE
[Bug]: append resets previously updated value

### ISSUE THREAD

**Issue by peakercope** [react-hook-form/react-hook-form#6064]
### Version Number

7.11.1

### Codesandbox

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-zljz7?file=/src/index.js

### Steps to reproduce

1. Go to [https://codesandbox.io/s/react-hook-form-usefieldarray-forked-zljz7?file=/src/index.js](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-zljz7?file=/src/index.js)
2. Click on `APPEND` button.
3. Observe that new row without value has been added.
4. Click `UPDATE` button.
5. Observe that first value has been updated (text `bar` appeared).
6. Click on `APPEND` button.
7. Added second row but first one was cleared

### Expected behaviour

Second row added and first row value remained.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Where are the input and `reigster` method? As much as I want to support such usage, but react hook form is trying to focus on form inputs, and if you just want to manipulate the data and shifting the order, I think this is probably not going to be the right tool. 

although this PR may improve usage like this above (https://github.com/react-hook-form/react-hook-form/pull/5958), I would still suggest sticking with `inputs` for this library.
