### ISSUE TITLE
[Bug]: material-ui TextField get undefined value when defaultValue set

### ISSUE THREAD

**Issue by yousetme** [react-hook-form/react-hook-form#6073]
### Version Number

^7.12.0

### Codesandbox

https://codesandbox.io/s/react-hook-form-defaultinitial-form-value-forked-s07j0?file=/src/index.js

### Steps to reproduce

When <TextField /> defaultValue set，and click submit button，onSubmit function get undefined value，but not the defaultValue. if TextField get focus and submit again, it work. 
Is there some usage unknown?

import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { TextField } from '@material-ui/core';

const Form = (props) => {
  const { register, handleSubmit } = useForm();
  const onSubmit = (data) => {
    alert(JSON.stringify(data));
  };

  return (
    <>
      <form onSubmit={handleSubmit(onSubmit)}>
        <TextField
          defaultValue={'ssss'}
          {...register('firstName')}
          placeholder="First name"
        />
        <input type="submit" />
      </form>
    </>
  );
};

### Expected behaviour

form `onSubmit` function should get default value where first submit.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
have a read on this thread: https://github.com/react-hook-form/react-hook-form/issues/4629 it's due to `ref` name.
