### ISSUE TITLE
[Bug]: remove function in useFieldArray work incorrectly when using with react-transition-group

### ISSUE THREAD

**Issue by Trucnt** [react-hook-form/react-hook-form#6075]
### Version Number

7.12.0

### Codesandbox

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-q47zj?file=/src/ArrayComponent.js

### Steps to reproduce

1. Go to [https://codesandbox.io/s/react-hook-form-usefieldarray-forked-q47zj](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-q47zj?file=/src/ArrayComponent.js)
2. Click on 'SETVALUE'  -->  2 rows will be added
3. Click on 'SUBMIT'  -->  display alert with 2 rows of data
4. Click on 'REMOVE' at row 2nd (last row)  -->  row 2nd will be deleted
5. Click on 'SUBMIT'  -->  display alert with 2 rows of data. The row 2nd is still in the form state

### Expected behaviour

When call remove([last index]), the last item in the array will be deleted in form state

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I don't think this lib works with hook form.

**Comment by nratter** [comment]
Are there plans to get `remove` to function properly with `react-transition-group` in v8? This is also creating an issue for us. Thanks!
