### ISSUE TITLE
[Bug]: regression with useWatch, nested arrays and shouldUnregister: false

### ISSUE THREAD

**Issue by terebentina** [react-hook-form/react-hook-form#6079]
### Version Number

7.6.1+

### Codesandbox

https://codesandbox.io/s/loving-goodall-2jy5t?file=/src/App.js

### Steps to reproduce

The CSB shows how watching level 2 arrays breaks when the inputs are not present, even though default values are specified and shouldUnregister is set to false. 
The regression was introduced in 7.6.1 and is present in all versions since.

1. open the CSB console
2. notice how the console shows `Block.columnsCount 2` for the first render but `Block.columnsCount 0` for the second render. 
3. notice how, even when the inputs appear, useWatch doesn't catch that (there's no 3rd render pass to settle on 2)
4. change the RHF version to 7.6.0 and try again
5. the 2 renders both show a count of 2

### Expected behaviour

Always showing 2 as the count in versions higher than 7.6.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for the issue, the regression was introduced with perf improvement. you can use `7.12.1-next.0` to solve the issue for now until we release the final version.
