### ISSUE TITLE
Array Fields show with default values

### ISSUE THREAD

**Issue by yi-tuan** [react-hook-form/react-hook-form#608]
I'm using array fields, but it doesn't show well with default values. And If I remove one of the middle fields, I want the array to reduce this item and keep the values of the other fields the same. Can you give me some suggestions?
https://codesandbox.io/s/react-hook-form-array-fields-tzor1

**Comment by bluebill1049** [comment]
hey @yi-tuan try this one: https://codesandbox.io/s/react-hook-form-field-array-advanced-with-delete-insert-append-edit-l19pz

**Comment by yi-tuan** [comment]
I use `reset` or `defaultValues` to initialize the page data, the array fields can't show well.The demo you give will work well at creation time, but backfill can't work.

**Comment by bluebill1049** [comment]
i would suggest to use inline `defaultValue`.

**Comment by bluebill1049** [comment]
it's going to be very tricky for `defaultValues` to render the children as well. you still need to map your input with local state.

**Comment by yi-tuan** [comment]
But what about asynchronous data, and my components are nested in several layers.

**Comment by yi-tuan** [comment]
i use `getvalues()[name]` to get data. i get `name[0]、name[1]、name[...]`.

**Comment by bluebill1049** [comment]
```
const result = await dataFetchFromServer() 

result.map() // you can have your default value as well
```

is this what you mean?

**Comment by bluebill1049** [comment]
maybe you could give me a more meaningful codesandbox in order for me to understand the issue better.

**Comment by yi-tuan** [comment]
like this
https://codesandbox.io/s/react-hook-form-array-fields-tzor1

**Comment by bluebill1049** [comment]
I guess my demo only missing populate fields? Why not just using the append method in my demo? Basically call the method to populate your inputs.

**Comment by bluebill1049** [comment]
how did you go with map data inline?

**Comment by bluebill1049** [comment]
closing this for now, it's much easier to map the input and place default value, then having defaultValues to support dynamic data structure.

**Comment by shubhamjajoo** [comment]
I am also facing the same issue 
[Link to codeSandbox](https://codesandbox.io/s/falling-firefly-u3vcm?file=/src/App.js).

But I guess if we are specifying default values for Form so it should fill those fields.
