### ISSUE TITLE
[Bug]: delayError period affects isValid 

### ISSUE THREAD

**Issue by reichhartd** [react-hook-form/react-hook-form#6081]
### Version Number

7.12.0

### Codesandbox

https://codesandbox.io/s/useform-delayerror-isvalid-example-epcoi?file=/src/App.js

### Steps to reproduce

1. Open the Codesandbox link
2. Type for example `12345` (which should be valid)
3. The `isValid` is only validated after the `delayError` period and then set to `true`

### Expected behaviour

That `delayError` really only affects the errors, and `isValid` is instantly set to `true` for a valid input.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for the error report. can you test ou this CSB? https://codesandbox.io/s/useform-delayerror-isvalid-example-forked-bgtjr?file=/src/App.js

**Comment by reichhartd** [comment]
It works. Many thanks for the quick fixing!
