### ISSUE TITLE
[Bug]: array mutated with useWatch in 7.12.1-next.0?

### ISSUE THREAD

**Issue by terebentina** [react-hook-form/react-hook-form#6082]
### Version Number

7.12.1-next.0

### Codesandbox

https://codesandbox.io/s/agitated-sun-eg1um?file=/src/App.js

### Steps to reproduce

1. open the CSB console
2. start typing in one of the inputs
3. notice how for the first character you get a log in the console but then the logging doesn't happen anymore
4. 7.12.0 behaves correctly

### Expected behaviour

There should be a log line for every character we type with the updated watched values. 
This is because the `useEffect` in the `Preview` component should run after every change.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
the result is there: https://codesandbox.io/s/agitated-sun-eg1um?file=/src/App.js

**Comment by bluebill1049** [comment]
i will patch this minor issue with `useEffect`

**Comment by terebentina** [comment]
> the result is there: https://codesandbox.io/s/agitated-sun-eg1um?file=/src/App.js

Sorry, I don't understand what you mean. Here's a screenshot of the input having the value `block01111111` but the latest value from useWatch is `block01`:
![image](https://user-images.githubusercontent.com/238611/126968103-5746695d-36e8-48bc-9036-ad7d40378f73.png)

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/126968281-d39a15fc-3e47-4f2a-8f54-33d97c717293.mov

you don't need that `useEffect`

**Comment by terebentina** [comment]
Oh, you're right, I don't need useEffect for this simplified demo. My usecase is slightly more complicated though as I am merging the useWatch value with some other data and doing a useMemo on the result, like this:
```
const { blocks } = useWatch({});
const mergedData = React.useMemo(() => {
    const output = ...; // merge blocks and otherData
    return output;
}, 
[blocks, otherData]);
```
And this useMemo doesn't get triggered when I make changes to the form.

I used useEffect instead of useMemo in my CSB to make it easier to exemplify what I'm seeing in my app.

**Comment by bluebill1049** [comment]
```
const data = useWatch()

// use data instead
```
