### ISSUE TITLE
[Bug]: Problem with default value using input type=checkbox and controller

### ISSUE THREAD

**Issue by giulianopiovezan** [react-hook-form/react-hook-form#6087]
When i upgrade from version 7.10.2 to 7.11.1, controlled inputs of type checkbox with defaultValues stopped to be checked.

### Version Number

7.11.1

### Codesandbox

https://codesandbox.io/s/loving-blackburn-p817f?file=/src/App.js

### Steps to reproduce

1. Upgrade react-hook-form to v7.11.1
2. Saw that checkbox isn't checked
3. If downgrade to v7.11, checkbox was checked

### Expected behaviour

When set defaultvalue, checkbox should be setted according

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JamesWong1999** [comment]
This is expected behaviour, controller should have `checked` instead of `value`

```tsx
import { useForm, Controller } from "react-hook-form";
import "./styles.css";

export default function App() {
  const { control } = useForm({
    defaultValues: {
      checkbox: true
    }
  });

  return (
    <form>
      <label>
        Check test
        <Controller
          control={control}
          name="checkbox"
          render={({ field: { name, onChange, value, ref } }) => (
            <input
              ref={ref}
              name={name}
              checked={value}
              onChange={onChange}
              type="checkbox"
            />
          )}
        />
      </label>
    </form>
  );
}
```

**Comment by giulianopiovezan** [comment]
But this should be a break change, because in version 7.11 works and after minor upgrade this does not works more

**Comment by bluebill1049** [comment]
I can confirm this was a bug fix, we shouldn't update input value though `ref`, this cause issue when the user manipulates or transform input value. The current version is the correct behaviour.
