### ISSUE TITLE
[Bug]: input string not working correctly as defaultValue/rest

### ISSUE THREAD

**Issue by entozoon** [react-hook-form/react-hook-form#6090]
### Version Number

7.12.0

### Codesandbox

https://codesandbox.io/s/laughing-euler-qkel1?file=/src/App.js

Or snippet :
```js
useEffect(() => {
  reset({ date: new Date() }); // <-- should set input to today's date
}, reset);
// ...
<input
  type="date"
  {...register("date", {
    valueAsDate: true
  })}
/>
```
### Steps to reproduce

Using [reset](https://react-hook-form.com/api/useform/reset) to set a date input with parameter `valueAsDate: true`.

### Expected behaviour

This should set the input date value but it appears to do nothing. I've tried variations of date objects or date string formats but nothing has any effect. 

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
- defaultValue shouldn't contain DateTime object
- `valueAs` only meant to transform with user input as the final result 

however, there is an issue with `setValue` even with defaultValue as `string` will get it fixed

**Comment by bluebill1049** [comment]
expected behaviour: https://codesandbox.io/s/silly-haze-0tx23?file=/src/App.js

**Comment by entozoon** [comment]
Okay doke, thank you very much @bluebill1049 
I can see that it works with a string now in 7.12.1 which'll do just fine :)

https://codesandbox.io/s/gracious-sunset-ee3i6?file=/src/App.js

**Comment by bluebill1049** [comment]
thanks for the issue report.
