### ISSUE TITLE
[Bug]: The input becomes slow with validation

### ISSUE THREAD

**Issue by thangpham-wz** [react-hook-form/react-hook-form#6095]
### Version Number

7.12.1

### Codesandbox

https://codesandbox.io/s/wizardly-hellman-6mfq8?file=/src/App.tsx

### Steps to reproduce

1. Open the code sandbox link
2. Enter a long text to the input which has more than 30 characters
2. Unfocus out of the text input.
3. It might cause the app to crash or block the UI for a while.
4. The next onChange will be extremely slow

### Expected behaviour

Input should not be crash / be blocked when having validation rules,

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
adjust your regex to avoid this sort of bad perf. this is not an issue with hook form.

https://codesandbox.io/s/awesome-andras-yggsi?file=/src/App.tsx
