### ISSUE TITLE
[Bug]: valueAsNumber remains a string (Material-UI)

### ISSUE THREAD

**Issue by SemperFortis** [react-hook-form/react-hook-form#6098]
### Version Number

7.12.1

### Codesandbox

https://codesandbox.io/s/ecstatic-dewdney-yjk9y?file=/src/App.js

### Steps to reproduce

1. Open the code sandbox link
2. Enter any number in the text input
3. Click submit, check the console which will log the value as a string

### Expected behaviour

Text input should be a number, not a string when `valueAsNumber: true` is specified.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
I haven't looked into the RHF source code yet, so I don't know what's actually happening under the hood. But the gist of it is that it works if the **ref** from register **is passed down to the component correctly**.
The `<TextField />` component [takes in a ref as an inputRef prop to pass down](https://next.material-ui.com/api/text-field/) to the actual `</ input>` element. So, take a look at  #4629 as it's related to passing a ref to a component with a different naming convention

**Comment by SemperFortis** [comment]
I've already tried passing down the ref directly using `inputRef={register('name', { valueAsNumber: true }).ref}` to no avail.

**Comment by bluebill1049** [comment]
<img width="977" alt="Screen Shot 2021-07-28 at 9 18 16 am" src="https://user-images.githubusercontent.com/10513364/127239573-19d8d706-0d81-4fe8-85bf-8620b6c22c75.png">

looks like the `ref` itself is not the input ref, so hook form can't invoke `valueAsNumber`, I will see if we can work around with this issue, otherwise you will have to use `Controller `

**Comment by bluebill1049** [comment]
unfortunately, because the ref itself is not an input `ref`, MUI text input is not even compatible with `setValue` as well, so for some perspective, it's less compatible than the previous version. Not really much we can do at hook form unless `input` ref is exposed to hook form.
