### ISSUE TITLE
Typescript Problem because defaultValues must be a string

### ISSUE THREAD

**Issue by RobIsHere** [react-hook-form/react-hook-form#6109]
**Is your feature request related to a problem? Please describe.**

```
export interface IChildFormData {
  supportHoursPerWeek: number;
}

export interface ViewProps {
  defaultValues: Partial<IChildFormData>;
  onSubmit: (data: IChildFormData) => void;
}

export const View: VFC<ViewProps> = ({ defaultValues = {}, onSubmit }) => {
  const {
    register,
    handleSubmit,
    formState: { isValid, errors },
  } = useForm<IChildFormData>({
    defaultValues: {
      ...defaultValues,
      supportHoursPerWeek: typeof defaultValues.supportHoursPerWeek === 'number'? defaultValues.supportHoursPerWeek.toString() : undefined,
    },
  });

  return (
    <Input type="number" {...register('supportHoursPerWeek', { required: true, valueAsNumber: true })} />
  )

```

==> TYPESCRIPT ERROR: Type 'string | undefined' is not assignable to type 'number | undefined'.
                                         Type 'string' is not assignable to type 'number | undefined'.ts(2322)
                                         (property) supportHoursPerWeek?: number | undefined

Redefining my interface to
```
export interface IChildFormData {
  supportHoursPerWeek: number | string;
}
```
is just absurd because supportHoursPerWeek has to be a required number, not some string. I expect that also 
as a return value from submit.

**Describe the solution you'd like**
I would like to provide the defaultValues as a number type when valueAsNumber is set or as a Date type when valueAsDate is set. 

By the way: thanks, except of this issue it's been a real joy to work with your form hook :)

**Comment by bluebill1049** [comment]
Native input supposed to be string by default. ValueAsNumber is invoked based on string.
