### ISSUE TITLE
When reValidateMode is onChange, doesn't revalidate after calling triggerValidation

### ISSUE THREAD

**Issue by babramczyk** [react-hook-form/react-hook-form#611]
**Describe the bug**
When `reValidateMode` is `'onChange'`, inputs aren't revalidated on change after `triggerValidation` is called.

**To Reproduce**
1. `useForm({ triggerValidation: 'onChange' })`
2. Put some required inputs on the page
3. Put a button on the page that on click does `triggerValidation()`
4. Click the button without filling out any of the inputs
5. Change an input so that it's not empty

**Expected behavior**
- The input is re-validated when it changes and becomes valid, just as it would if the validation would have been triggered by submitting the invalid form instead of manually calling `triggerValidation`

**Comment by bluebill1049** [comment]
can you please provide a codesandbox for this issue? it would be much easier for me to test and verify.

**Comment by bluebill1049** [comment]
closing now, please supply a codesandbox, i will re-open and take look into it.
