### ISSUE TITLE
[Bug]: input should Input basically first letter should be capital.

### ISSUE THREAD

**Issue by harshalone** [react-hook-form/react-hook-form#6120]
### Version Number

7

### Codesandbox

no link

### Steps to reproduce

1. npm install react-hook-form
2. Copied following code
```
import React from "react";
import { useForm } from "react-hook-form";

export default function App() {
  const { register, handleSubmit, watch, formState: { errors } } = useForm();
  const onSubmit = data => console.log(data);

  console.log(watch("example")); // watch input value by passing the name of it

  return (
    /* "handleSubmit" will validate your inputs before invoking "onSubmit" */
    <form onSubmit={handleSubmit(onSubmit)}>
      {/* register your input into the hook by invoking the "register" function */}
      <input defaultValue="test" {...register("example")} />
      
      {/* include validation with required or other standard HTML validation rules */}
      <input {...register("exampleRequired", { required: true })} />
      {/* errors will return when field validation fails  */}
      {errors.exampleRequired && <span>This field is required</span>}
      
      <input type="submit" />
    </form>
  );
}
```

### Expected behaviour

It should have run without error but currently its asking me to change the first letter to capital letter on my expo react-native app

### Relevant log output

```shell
expo
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshalone** [comment]
Here is the error I am receiving:

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by dnaicker** [comment]
This is a big issue and makes the library unusable

**Comment by manoj27110696** [comment]
I am having the same issue as above when using the example from the get started guide
Invariant Violation: View config getter callback for component `input` must be a function (received `undefined`). Make sure to start component names with a capital letter.

**Comment by Moshyfawn** [comment]
Come on! The issue was closed with the "need more detail" label. What's the deal with "I'm having the issue too"? The only helpful thing would be to provide a codesanbox _(or snack)_ reproduction of the issue.

BTW, the issue doesn't seem to be related to RHF, but rather it's a RN error telling you to not use one of the plain web elements and using the RN components
```js
import { View, TextInput } from "react-native"
```

The example in Get Started section of RHF docs is clearly a web example, not an RN one.
