### ISSUE TITLE
[Bug]: Cannot assign to read only property '0' of object '[object Array]'

### ISSUE THREAD

**Issue by hugodelnegro** [react-hook-form/react-hook-form#6121]
### Version Number

v7

### Codesandbox

https://codesandbox.io/s/react-hook-form-get-started-forked-w7zev?file=/src/index.js

### Steps to reproduce

Submit form and check console logs

### Expected behaviour

I would expect to run this on my system as in codesandbox.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Unlike in Codesandbox I am unable to change checkbox fields getting:  "Cannot assign to read only property '0' of object '[object Array]'".
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
<img width="824" alt="Screen Shot 2021-07-29 at 9 22 43 pm" src="https://user-images.githubusercontent.com/10513364/127483673-c7d84861-d8e4-4750-871b-6705fb3b36a7.png">

can't reproduce

**Comment by hugodelnegro** [comment]
I can only run locally and I see it on compilation

**Comment by bluebill1049** [comment]
- could be your dependency if can't be reproduce in codesandbox
- for complex checkbox like you got above, build a controlled component and host your state inside and let controller collect value and validate

**Comment by ZipBrandon** [comment]
I ran across this same issue when I lazy initialized the form after having provided `defaultValues`. 


Given the shape of a `reviewSite` being `{ label: string, active: boolean }` and the checkbox manipulates the active field.

```
  const methods = useForm({
    defaultValues: {
      reviewSites: [],
    },
  });
```

This useEffect with setValue creates an issue when the checkbox field is later manipulated
```
  useEffect(() => {
    if (loadingComplete) {
      methods.setValue(`reviewSites`, loadedData); 
    }
  }, [loadingComplete]);
```
However this useEffect works with the reset.
```
  useEffect(() => {
    if (loadingComplete) {
      methods.reset({reviewSites: loadedData}); 
    }
  }, [loadingComplete]);
```

**Comment by Andreychikov-Vasiliy** [comment]
Have same problem when migrating from 7.12.2 --> 7.13.0-next.0

**Comment by ZipBrandon** [comment]
I believe the broader source of my issue is that I was taking the direct response of an Apollo query and using that for the values.  I am pretty new to `react-hook-form` after coming from three years with `formik` where I could do such things.  I have sense remedied this and other issues I ran across by using a `deepClone` of the GraphQL responses when using them for form values.

**Comment by Andreychikov-Vasiliy** [comment]
@ZipBrandon , for me - on the other hand, I had opposite situation - I got a whole form state from *whatch* subscription and stored it in redux toolkit store, which under the hood looks like "proxified" this object using *immer* perhaps. And still as for you I've resolved it by doing deepClone before use form state elsewhere.

**Comment by HeyiMaster** [comment]
The problem is in src/utils/set.ts，when the form data is stored in the immer store，the `object: FieldValues` is not expandable，so the original object should not be manipulated directly. I'll submit a PR later. Please check and merge it after passing.😄

**Comment by FunctorDev** [comment]
I also ran into this problem when setting form value from **redux-toolkit selector**, I fixed it by using deep clone `JSON.parse(JSON.stringify(...))`.
