### ISSUE TITLE
[Bug]: isDirty & dirtyFields are out of sync with values on first render

### ISSUE THREAD

**Issue by realleyriley** [react-hook-form/react-hook-form#6125]
### Version Number

7.12.1

### Codesandbox

https://codesandbox.io/s/bug-isdirty-dirtyfields-are-out-of-sync-with-values-on-first-render-oo00x

### Steps to reproduce

1. do not click anywhere and observe that the render count is 1, and isDirty is false
2. click the Submit button and check the console to see that there is in fact a value in firstName. Also observe the render count has not changed
3. from here, causing a re-render will fix the issue. This can be done by changing the value in either textfield, or by clicking into one of the fields, then clicking elsewhere

### Expected behaviour

isDirty should be true since there is in fact a value inside of the formState that is different from the provied default values. The dirtyFields should reflect this as well

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
{firstName: "martin", lastName: ""}
{isDirty: false, isValidating: false, dirtyFields: Object, isSubmitted: true, submitCount: 0…}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by realleyriley** [comment]
Found this bug because I need to be able to populate the form with default values, but I also want to use the reset functionality to clear all fields. My reset button is disabled depending on `isDirty`, but its broken on the first render as the Codesandbox shows.

Thanks for the awesome library btw!

**Comment by realleyriley** [comment]
My colleague discovered that passing `{ shouldDirty: true }` as the third parameter to `setValue()` will fix the issue!

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report. please use `shouldDirty` flag with setValue instead. We don't check dirty during `handleSubmit`, only with user interaction or manually change value.
