### ISSUE TITLE
[Bug]: Errors object is not being updated when form is invalid

### ISSUE THREAD

**Issue by AndreNunes1** [react-hook-form/react-hook-form#6161]
### Version Number

7.12.2

### Codesandbox/Expo snack

https://codesandbox.io/s/quiet-sea-u2qni

### Steps to reproduce

Two similar situations:

1# :
1. Increase number of bags to 4 and leave number of passengers at 1
2. Increase number of passengers to 2 and leave bags at 4

2#:
1. Increase passenger's number to 2 and bags to 4
2. decrement number of passengers to 1 and leave bags at 4

### Expected behaviour

1#: After increasing the passenger's number to 2 the form is valid, but the error persist within the errors object.

2#: After decreasing the number of passengers to 1, the form becomes invalid but the Errors object displays no error.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
<img width="1056" alt="Screen Shot 2021-08-04 at 8 49 11 am" src="https://user-images.githubusercontent.com/10513364/128096137-0ec50279-67ea-45be-b079-d64c294588c2.png">

the form value is in string

**Comment by vitorcamachoo** [comment]
@bluebill1049  
Thank you for your feedback.
I still have some wrong behaviour when I set the following scenarios:

## Scenario 1:
1. Decrease passengers to 1. (form will be invalid but not showing any error)

## Scenario 2:
1. Increase bags to 5 (It will show `bags` error)
2. Increase passengers to 3. (form will be valid at this point, but the bags error persists)


https://codesandbox.io/s/quiet-sea-u2qni?file=/src/App.tsx

**Comment by bluebill1049** [comment]
I would suggest you investigate the form value against your schema. react hook form doesn't no magic on the form validation with resolver by passing values to your schema.

**Comment by mrasoahaingo** [comment]
The issue is that even the resolver have cleared all errors, the fields which are not focused or touched are not updated

**Comment by bluebill1049** [comment]
> the fields which are not focused or touched are not updated

because hook form only focus on the single input validation at a time to trigger validation, if you need to trigger depend validation use `trigger`.

**Comment by vitorcamachoo** [comment]
> > the fields which are not focused or touched are not updated
> 
> because hook form only focus on the single input validation at a time to trigger validation, if you need to trigger depend validation use `trigger`.

Using trigger after onChange event, I get the expected result, but, I don't know if it's good practice to do that.

**Comment by mrasoahaingo** [comment]
For what i know, resolver is made to manage errors on complex fields dependencies., custom validation, etc... using manual trigger looks like a hack (which may also trigger component extra render?)

**Comment by bluebill1049** [comment]
It is not a **hack** with `trigger`, I think we are all used with form level validation, which `triggers` re-render on each keystroke and flush `formState` within the entire form. hook form is optimized for performance so it focuses on the user's input at a time and reconciled for when to render an error and an error gets resolved.

eg: if user input contains an error, the lib will trigger a **single** re-render to show an error and not **spam** re-render on the user errors, and only re-render again when user's inputs get corrected. This is why hook form is performant and focuses on end-user experience without constantly re-rendering your entire form/app.

For any dependant validation, we will have to use `trigger`, so the hook form knows it's an associated input and hence re-render with the correct errors state. 

Now, we do have a feature branch right now which adds a sugar syntax for dependency validation: https://github.com/react-hook-form/react-hook-form/pull/6141 but underneath we are still using `trigger` to info hook form its dep validation.


The purposed syntax right now:

```tsx
register('test', { dpes: ['otherInput']})
```

Hope the above explanation makes sense, and the new feature above may make this experience better for us.

**Comment by mrasoahaingo** [comment]
This can be very helpful, i updated the sandbox and manually trigger related fields. And now i got extra renders as expected, while it would cost only one render if errors from hook was the same as returned by resolver :(

![image](https://user-images.githubusercontent.com/12088397/128184067-b4bc0747-26b5-4b7e-b422-9be0010e5e62.png)
