### ISSUE TITLE
[Bug]: object comparison for isDirty

### ISSUE THREAD

**Issue by realleyriley** [react-hook-form/react-hook-form#6164]
### Version Number

7.12.2

### Codesandbox/Expo snack

https://codesandbox.io/s/bug-object-comparison-for-isdirty-tkgp5?file=/src/App.js

### Steps to reproduce

1. change the value of either field, then change it back to the default and notice that isDirty works properly
2. change the value of either field so that isDirty is true
3. click the reset object button
4. notice that isDirty is now true, even though the object values are the same
5. causing a re-render will not fix it, but clicking reset will

### Expected behaviour

isDirty should be false if object values are identical.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
use `7.13.0-next.0`, looks like the issue already resolver there

**Comment by realleyriley** [comment]
I tried `7.13.0-next.0` in the codesandbox but still encounter the same issue :(

**Comment by bluebill1049** [comment]
share a video clip, i didn't reproduce the issue.

**Comment by realleyriley** [comment]
https://youtu.be/Z9adImv7r9I

**Comment by bluebill1049** [comment]
thanks for the video 

```
setValue("dateRange.firstDate", "7", { shouldDirty: false });
setValue("dateRange.secondDate", "8", { shouldDirty: false });
```

why should dirty set to `false`?

**Comment by bluebill1049** [comment]
if you set them to `false`, then dirty check will be omitted.

**Comment by realleyriley** [comment]
Thats my bad. Setting it to true fixes it! 

As for using `field.onChange` instead, that is also my bad, no problem there. Sorry, thanks for the help

**Comment by bluebill1049** [comment]
All good ☺️
