### ISSUE TITLE
Errors computed on resolver doesn't match errors on formState

### ISSUE THREAD

**Issue by mrasoahaingo** [react-hook-form/react-hook-form#6172]
I made a sandbox which test NET + VAT = GROSS with validation https://codesandbox.io/s/react-hook-form-customresoliver-v7-forked-f07rv?file=/src/index.jsx

This is the nominal valid case which 1 + 1 = 2
![image](https://user-images.githubusercontent.com/12088397/128150440-a54e191a-05ce-419c-883e-85fab51a2784.png)

Then in this case all fields are not valid because the sum is not correct, so the user have to update the values
![image](https://user-images.githubusercontent.com/12088397/128150695-3de9b9ac-cc05-4e6f-9152-42771efa5886.png)

And once I update the total, the resolver doesn't found any errors: {} , but on the render there's still errors on NET and VAT
![image](https://user-images.githubusercontent.com/12088397/128151038-f865647d-dba4-4e29-8e47-39b21be99eee.png)

Why errors return by the resolver are not the same as on the render?

_Originally posted by @mrasoahaingo in https://github.com/react-hook-form/react-hook-form/issues/6161#issuecomment-892476227_

**Comment by bluebill1049** [comment]
do not spam issue. i am replying in the other issue.

**Comment by mrasoahaingo** [comment]
Sorry, i though this is another case

**Comment by mrasoahaingo** [comment]
Hi, Is there any solution to make formState errors synched with errors returned on resolver? (without triggering another render by calling trigger() or use deps option on each register)?

Thanks a lot

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/discussions/6348#discussioncomment-1246393
