### ISSUE TITLE
Validation not working with fields arrays in joi

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#6176]
**Describe the bug**
I'm noticing a new issue with schema validation with joi. After upgrading to the latest versions of hook-form and resolvers, it seems like validation is not working anymore with non-field attributes. So for example, if I want to validate that a field array has a min length, this no longer seems to be working. If I use `schema.validate(formValues)`, then I get an error. However, `formState.isValid` still returns `true` when it should be returning `false`. This is how it worked in previous versions. 

**To Reproduce**

1. Go to the sandbox
2. Open the console 
3. Notice that `formState.isValid` is true but the `schema.validate(watch())` reports an error.

**Codesandbox link (Required)**
https://codesandbox.io/s/summer-grass-qm6om?file=/src/App.js

**Expected behavior**
If the schema reports an error, then `formState.isValid` should be `false`.

**Screenshots**
![Screenshot from 2021-07-19 10-15-47](https://user-images.githubusercontent.com/36898266/126200358-e9d8982f-756d-4eae-81c8-e4ff543b276a.png)

**Additional context**
If this was changed so that validation is only run on fields and non-field errors are ignored, then please let me know. I did not see this in the changelog. I would hope that while error messages are not reported for non-field items in `formState.errors`, `formState.isValid` could simply check if the `schema.validate` method returns an error to give us more flexibility.

**Comment by wdfinch** [comment]
My current workaround is I create error hidden inputs that hold errors for field arrays. This also allows me to get an error message for invalid field arrays without having to write a custom resolver.

**Comment by bluebill1049** [comment]
I will take a look at it.

**Comment by bluebill1049** [comment]
use 7.13.0-next.0 it should fix your issue.

**Comment by bluebill1049** [comment]
will re-open if still an issue with 7.13-0-next.0
