### ISSUE TITLE
[Bug]: Issue with controller and testing

### ISSUE THREAD

**Issue by pollard93** [react-hook-form/react-hook-form#6189]
### Version Number

7.12.2

### Codesandbox/Expo snack

https://github.com/pollard93/react-hook-form-issue

### Steps to reproduce

1. Go to and clone https://github.com/pollard93/react-hook-form-issue
2. Run `yarn && yarn test`

### Expected behaviour

There should not be an error. The error is coming from the use of the `Controller` -> `render`-> `field.onChange`. This works fine outside of a test environment. I've also tested using `setValue` with no issues.

### Relevant log output

```shell
TypeError: A is not a function
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
post questions at disucssion
