### ISSUE TITLE
Not able to submit remotely

### ISSUE THREAD

**Issue by vsharma918** [react-hook-form/react-hook-form#619]
Hi I have very complex form where we have two and three places where we need to call submit and go to next page but it doesn't allow me to onsubmit from out side.

**Comment by bluebill1049** [comment]
codesandbox plz?

**Comment by bluebill1049** [comment]
`onClick={handleSubmit(onSubmit)}` ?

**Comment by bluebill1049** [comment]
going to close this issue, above should be the solution. otherwise please provide more detail and follow the issue template or asking question at spectrum channel.

**Comment by vsharma918** [comment]
We figured out an alternate way by have  a form id and trigger submit event
from out side of form component. it working now fine thanks for reply.

**Comment by bluebill1049** [comment]
no worries :) glad you work it out.

**Comment by vsharma918** [comment]
How can we watch a particular field in array object like I have list of
person and want to watch on dob only.
Thanks,
Vishal

**Comment by bluebill1049** [comment]
`watch('person')` https://react-hook-form.com/api#watch

**Comment by vsharma918** [comment]
Hi Bill,

I have stuck while using hook form. Here is my cases so let me know how can
we solve this.

1. We have two payment form with two radio button like if user select first
payment option then we show only billing and once user select new card pay
option then we show credit card form with billing form.
2.  If user fill half form then switch to other option then we want to keep
half form filled so if user switch again then they can see value again.

Please check https://m.cheapoair.com and go to payment page and let me know
how can I architect it.

Thanks,
Vishal

**Comment by bluebill1049** [comment]
hey @vsharma918 I think it's pretty easy.  two options in my head

1. you just hide the form by display: 'none'  and not remove the DOM
2. use a state machine to store data in session storage: https://github.com/bluebill1049/little-state-machine

**Comment by AjithkumarJM** [comment]
Hi Bill, 

I have a situation here, 
I need to perform multiple actions on same onClick which has `handleSubmit`.
in this case, the `handleSubmit `is not working.

`onClick = { if() ...someAction else handleSubmit(onSubmit) }`

Is there any other way to achieve this?

**Comment by bluebill1049** [comment]
> Hi Bill,
> 
> I have a situation here,
> I need to perform multiple actions on same onClick which includes `handleSubmit` as well.
> in this case, the `handleSubmit `is not working.
> 
> `onClick = { if() ...someAction else handleSubmit(onSubmit) }`
> 
> Is there any other way to achieve this?

`handleSubmit(onSubmit)()` i think you miss the `()`

**Comment by AjithkumarJM** [comment]
> > Hi Bill,
> > I have a situation here,
> > I need to perform multiple actions on same onClick which includes `handleSubmit` as well.
> > in this case, the `handleSubmit `is not working.
> > `onClick = { if() ...someAction else handleSubmit(onSubmit) }`
> > Is there any other way to achieve this?
> 
> `handleSubmit(onSubmit)()` i think you miss the `()`

Thanks mate! :)

**Comment by bluebill1049** [comment]
> > > Hi Bill,
> > > I have a situation here,
> > > I need to perform multiple actions on same onClick which includes `handleSubmit` as well.
> > > in this case, the `handleSubmit `is not working.
> > > `onClick = { if() ...someAction else handleSubmit(onSubmit) }`
> > > Is there any other way to achieve this?
> > 
> > 
> > `handleSubmit(onSubmit)()` i think you miss the `()`
> 
> Thanks mate! :)

all good mate. 👍
