### ISSUE TITLE
watch return input values without shallow merge with defaultValues

### ISSUE THREAD

**Issue by derekaspaulding** [react-hook-form/react-hook-form#6193]
### Version Number

7.12.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-validationschema-v7-forked-6d8gf?file=/src/FormWithCheckboxes.js

### Steps to reproduce

This sandbox is setup to have the first checkbox determine if the second checkbox is shown/hidden and then that second one determines if the third one is show/hidden. This is done by passing `shouldUnregister` to `useForm` and watching the values. This is a demonstration of a bug in a larger more complex component, so I need to be able to just watch all the values rather than watching individual values. By default in this example all are checked so all are shown. If you uncheck the second one, the third one should be hidden and the value unregistered. If you uncheck the first one, the second should be hidden and unregistered and if it wasn't already, the third should also hide and unregister.

To Reproduce:
1. Uncheck the "First" field.
2. Notice that the "Third" field is still shown and the "values" logged in the console are 
```json
{
  "first": false,
  "second": true,
  "third": true,
}
```

### Expected behaviour

I would expect that values that are returned from `watch` or `useWatch` should match the values that would be submitted. In this case, that should be just 
```json
{
  "first": false
}
```
since the other 2 fields should be unregistered. 

Currently it is 
```json 
{
  "first": false,
  "third": true
}
```
which shows that the second field is getting correctly unregistered, but because the logic for that is using `watch` the third field doesn't get unregistered.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is not a bug and its intended behavior, doesn't support `checkbox` with the same `name` because they have been treated as a single unit with an object as the value, build a controlled component wrapped with Controller to achieve your custom behavior.

**Comment by derekaspaulding** [comment]
The checkboxes don’t have the same name. I don’t see how using a Controller will help here. If this is the expected behavior, is there no way to get the values that would be submitted without actually submitting the form?

**Comment by derekaspaulding** [comment]
Or alternatively, is it possible to work around this limitation by getting a list of the currently registered fields?
