### ISSUE TITLE
[Bug]: ShouldFocus for useFieldArray is broken

### ISSUE THREAD

**Issue by calcifer9000** [react-hook-form/react-hook-form#6200]
### Version Number

7.8.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-i9klt

### Steps to reproduce

Sandbox above has been set 

1. Go to codesandbox.
2. Focus bottom input (above submit). Click enter a few times. Until there are more than 3 entries.
3. Focus stays on bottom input. No matter how many times user enter.

Change react hook form version to 7.7.1 and Expected works.

### Expected behaviour

When there are 3 entries, it should focus the 3rd one. For each and every enter, it should refocus 3rd one.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Thanks for the issue report, however, not going to support such usage tho. This will potentially conflict with `handleSubit` focus by onSubmit.
