### ISSUE TITLE
[Bug]: Controller's onChange seems to not trigger useWatch

### ISSUE THREAD

**Issue by janKozie1** [react-hook-form/react-hook-form#6207]
### Version Number

7.12.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-basic-forked-p9kkw?file=/src/index.js

### Steps to reproduce

1. Open the codesandbox
2. Check the console - note how the value is only logged once, despite being changed after the first render.

### Expected behaviour

Seems like something causes the `onChange` provided by the controller to not trigger a rerender where the `useWatch` is used. This seems to happen only immediately after first render. (typing in the input works just fine)
The actual value in the form is updated (i'm assuming so based on the fact that "onSubmit" shows the correct value)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mattlysf** [comment]
I am seeing the same behavior with `mode: 'all'` as well.

**Comment by bluebill1049** [comment]
This is due to function execution order, grandChild will be run before grand's useWatch's subscription is in place, and therefore when the onChange fire, there is no subscription is there to listen to the change.

**Comment by janKozie1** [comment]
I'm curious - why is this not considered to be an issue?

**Comment by bluebill1049** [comment]
> useWatch execution order matters, which means if you are update form value before the subscription is in place, then the value update will be ignored.

```
setValue('test', 'data');
useWatch('test'); // ❌ subscription is happened after value update, no update received

useWatch('example'); // ✅ input value update will be received and trigger re-render
setValue('example', 'data'); 
```

<img width="962" alt="Screen Shot 2021-08-11 at 7 50 32 pm" src="https://user-images.githubusercontent.com/10513364/129008611-a9457523-618e-4dc8-ae21-c469d65b939c.png">

**Comment by janKozie1** [comment]
Okay, sorry for missing that. 
I don't think the example from docs shows clearly that `useWatch` depends on the order in which `useEffect`s runs though - especially when it comes to nested children.

**Comment by bluebill1049** [comment]
It's the same idea, `useEffect` is a function that has its own execution order too.

**Comment by janKozie1** [comment]
Yup, but that's an implementation detail you won't know without checking the code. (unless this is also somewhere in documentation). If the subscription was created on render (maybe in a ref), then you probably wouldn't need to depend on the order of effects.
