### ISSUE TITLE
[Bug]: Nested field arrays not receiving correct types

### ISSUE THREAD

**Issue by jaydray1** [react-hook-form/react-hook-form#6229]
### Version Number

7.12.2

### Codesandbox/Expo snack

https://codesandbox.io/s/options-variants-u4dtx?file=/src/variation-row.tsx

### Steps to reproduce

1. Go to line 161
2. Hover over `name`
3. See type error

### Expected behaviour

We are on version `4.1.5` of TS. Expecting name to be a usable value matching the form types. 

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
(property) name: "regularVariations" | "personalizedVariations"
Type 'string' is not assignable to type '"regularVariations" | "personalizedVariations"'.ts(2322)
fieldArray.d.ts(7, 5): The expected type comes from property 'name' which is declared here on type 'UseFieldArrayProps<ProductFormValues, "regularVariations" | "personalizedVariations", "id">'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/usefieldarray

<img width="992" alt="Screen Shot 2021-08-14 at 8 58 16 am" src="https://user-images.githubusercontent.com/10513364/129425539-84ca21a2-ed20-4021-8a65-0f6317dd4add.png">

`const { fields } = useFieldArray({ name: `test.${index}.keyValue` as 'test.0.keyValue' });`
