### ISSUE TITLE
[Bug]: React-hook-form always triggers 2 renders on mount

### ISSUE THREAD

**Issue by hyungjs** [react-hook-form/react-hook-form#6230]
### Version Number

7.7.2-beta.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-basic-forked-h91ih?file=/src/index.js

### Steps to reproduce

Refresh the page. See logs for `isValid` showing up twice. (react re-renders)

1. false
2. true

### Expected behaviour

Hook form should not tigger unnecessary re-renders.

Check any version prior to 7.7.2-beta.1
and you will see logs only show up once (1 render)

1. true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
expected behaviour changed isValid check logic internally.
