### ISSUE TITLE
[Bug]: Pattern validator on text input sets value as stringified regex

### ISSUE THREAD

**Issue by SeanFree** [react-hook-form/react-hook-form#6238]
### Version Number

7.12.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-pattern-validator-bug-j21et?file=/src/App.js

### Steps to reproduce

1. Go to CodeSandbox link
2. View preview pane
3. See stringified regex as value in text input

### Expected behaviour

The input's value should not be set

### What browsers are you seeing the problem on?

Chrome 92.0.4515.131

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
don't support such usage.
