### ISSUE TITLE
Trigger a parent of nested fields should trigger them all

### ISSUE THREAD

**Issue by kadoshms** [react-hook-form/react-hook-form#6239]
**Is your feature request related to a problem? Please describe.**
Assuming my form is structured as the following:

`
details: {
 name: string;
 age: number;
},
contatcts: string[];
`

Currently, I want to trigger a validation on all the fields under `details`, and only them.

**Describe the solution you'd like**
It would be nice if I could `trigger('details')` and all the fields under that will be triggered.

Current option is to manually trigger all the fields `trigger(['details.name', 'details.age'])` although in complex examples is pretty rough.

**Comment by bluebill1049** [comment]
you can try out the `next` version now.

**Comment by kadoshms** [comment]
@bluebill1049 works like a charm.

**Comment by bluebill1049** [comment]
Awesome to hear 👍
