### ISSUE TITLE
version ^3.28.12-beta.2:  formstate isValid bug

### ISSUE THREAD

**Issue by Liza491646703** [react-hook-form/react-hook-form#624]
**Describe the bug**
One login page contains
password login and verification code login。
![image](https://user-images.githubusercontent.com/19361078/70214432-67023880-1776-11ea-80ac-cdb20eea8919.png)
![image](https://user-images.githubusercontent.com/19361078/70214452-6d90b000-1776-11ea-96e1-67b758e29085.png)
![image](https://user-images.githubusercontent.com/19361078/70214640-c9f3cf80-1776-11ea-8d06-088714ed2fa6.png)
the first bug is :  When I set cellphone is required, and not set any scheme to password. when I input the cellphone,  the isValid is false but actually it is true.

the second bug is: use yup when judge,  the password and the smscode，Select one to input ，the isValid will be true. but now the two must be input ,the isValid is true.

**Comment by bluebill1049** [comment]
Can u please verify this beta https://www.npmjs.com/package/react-hook-form/v/3.28.12-beta.6

**Comment by Liza491646703** [comment]
I am so sad . It is still the bug.

**Comment by Liza491646703** [comment]
the 'yup when' is not support good . and the first time , all the fileds must be input, the valid will be true.

**Comment by bluebill1049** [comment]
don't be sad, you can either roll it back to the older version, if that's work for you. i will take a look your codesandbox now.

**Comment by bluebill1049** [comment]
wait do you have a codesandbox?

**Comment by bluebill1049** [comment]
or share your code at least.

**Comment by Liza491646703** [comment]
a little long

**Comment by Liza491646703** [comment]
import React, { useState, useRef } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import useForm, { FormContext, useFormContext } from 'react-hook-form';
import { Button, Toast } from 'antd-mobile';
import CustomInputItem from '@components/HookForm/InputItem';
import { CountdownWithGeetest } from '@components/Countdown';
import { Link } from '@server/routes';
import * as userApi from '@lib/api/user';
import * as utils from '@lib/utils';
import { loginSuccess } from '@lib/reusable';
import * as yup from 'yup';

import styles from '@styles/login.less';

interface RouteState {
  loginType: 'password' | 'smsCode'; // 登录方式
}

interface FormChildrenProps {
  redirectUrl: string | undefined;
  loginType: RouteState['loginType'];
  changeLoginType: () => void;
  onClickSubmitButton: any;
}

const FormChildren = (props: FormChildrenProps) => {
  const [checkCellhoneResult, setCheckCellhoneResult] = useState(false);
  const refCountdown: any = useRef();
  const refCountdownInner: any = useRef();

  const methods = useFormContext();
  const { formState, getValues } = methods;

  const getSmsCode = async geetestValidate => {
    const cellphone = utils.trimAll(getValues().cellphone);
    const body = {
      ...geetestValidate,
      cellphone
    };

    const res: any = await userApi.getNotifySmsCode(body);

    Toast.info('验证码已发送');

    if (process.env.SERVER_ENV !== 'prod') {
      methods.setValue('smsCode', res.content || '', true);
    }
  };

  const geetestSuccess = geetestValidate => {
    getSmsCode(geetestValidate);
    refCountdown.current.resetGeetest();
    refCountdownInner.current.countdown();
  };

  // 验证手机号
  const verifyCellphone = value => {
    const cellphone = utils.trimAll(value);
    setCheckCellhoneResult(/^1\d{10}$/.test(cellphone));
  };

  const { redirectUrl, loginType, changeLoginType, onClickSubmitButton } = props;
  const registerRoute = utils.pathAddRedirectUrl('/register', redirectUrl, true);
  const forgetPasswordRoute = utils.pathAddRedirectUrl('/forget-password', redirectUrl, true);

  const isPasswordLogin = loginType === 'password' ? true : false;

  return (
    <div>
      <CustomInputItem
        name="cellphone"
        type="phone"
        title="手机号"
        inputType="vertical"
        onChange={verifyCellphone}
      />
      <CustomInputItem name="isPassword" title="isPassword" customClass={styles['hidden']} />
      <CustomInputItem
        name="password"
        type="password"
        title="密码"
        inputType="vertical"
        extra="eye"
        customClass={isPasswordLogin ? styles['show'] : styles['hidden']}
      />
      <CustomInputItem
        name="smsCode"
        title="手机动态验证码"
        inputType="vertical"
        customClass={isPasswordLogin ? styles['hidden'] : styles['show']}
        extra={
          <CountdownWithGeetest
            ref={refCountdown}
            innerRef={refCountdownInner}
            ready={checkCellhoneResult}
            onSuccess={geetestSuccess}
          />
        }
      />
      <p className={`${styles['tip-bar']} clearfix`}>
        <span className={`${styles['login-type']} float-left`} onClick={changeLoginType}>
          {isPasswordLogin ? '验证码登录' : '密码登录'}
        </span>
        {isPasswordLogin && (
          <Link route={forgetPasswordRoute}>
            <a className="float-right">忘记密码？</a>
          </Link>
        )}
      </p>
      <div className={styles['btn-bar']}>
        <Button type="primary" disabled={!formState.isValid} onClick={onClickSubmitButton}>
          登录
        </Button>
      </div>
      <p className={styles['extra-row']}>
        还没有账号？
        <Link route={registerRoute}>
          <a>点此注册</a>
        </Link>
      </p>
    </div>
  );
};

export default function() {
  const router = useRouter();
  const [loginType, setLoginType] = useState('password');
  const loginSchema = yup.object().shape({
    cellphone: yup.string().required(''),
    isPassword: yup.boolean(),
    password: yup.string().when('isPassword', {
      is: true,
      then: yup.string().required('密码必填')
    }),
    smsCode: yup.string().when('isPassword', {
      is: true,
      otherwise: yup.string().required('验证码必填')
    })
  });

  React.useEffect(() => {
    methods.setValue('isPassword', 1, true);
  }, []);

  const methods = useForm({
    mode: 'onChange',
    validationSchema: loginSchema,
    validationSchemaOption: { abortEarly: false },
    validateCriteriaMode: 'firstError'
  });

  const { watch, handleSubmit } = methods;
  watch();

  const { redirectUrl }: any = router.query;

  const changeLoginType = () => {
    const changeType = loginType === 'password' ? 'smsCode' : 'password';
    setLoginType(changeType);
    methods.setValue('isPassword', loginType === 'password' ? 0 : 1, true);
  };

  const onSubmit = async data => {
    let res: any = {};
    if (loginType === 'password') {
      res = await userApi.login(data);
    } else {
      res = await userApi.loginAndRegister(Object.assign({ loginOnly: true }, data));
    }
    loginSuccess(res.content, redirectUrl);
  };

  return (
    <div className={styles.page}>
      <Head>
        <title>登录</title>
      </Head>
      <div className={styles['page-title']}>登录</div>
      <div className={styles.content}>
        <FormContext {...methods}>
          <form onSubmit={handleSubmit(onSubmit)}>
            <FormChildren
              redirectUrl={redirectUrl}
              loginType={loginType as any}
              changeLoginType={changeLoginType}
              onClickSubmitButton={handleSubmit(onSubmit)}
            />
          </form>
        </FormContext>
      </div>
    </div>
  );
}

**Comment by bluebill1049** [comment]
easiest is codesandbox if you have it

**Comment by Liza491646703** [comment]
I am so sorry, I have not.

**Comment by bluebill1049** [comment]
that's fine, put your code up

**Comment by Liza491646703** [comment]
const FormChildren = (props: any) => {
  const methods = useFormContext();
  const { formState } = methods;
  const { loginType, changeLoginType, onClickSubmitButton } = props;
  const isPasswordLogin = loginType === 'password' ? true : false;

  return (
    <div>
      <CustomInputItem name="cellphone" type="phone" title="手机号" inputType="vertical" />
      <CustomInputItem name="isPassword" title="isPassword" customClass={styles['hidden']} />
      <CustomInputItem
        name="password"
        type="password"
        title="密码"
        inputType="vertical"
        extra="eye"
        customClass={isPasswordLogin ? styles['show'] : styles['hidden']}
      />
      <CustomInputItem
        name="smsCode"
        title="手机动态验证码"
        inputType="vertical"
        customClass={isPasswordLogin ? styles['hidden'] : styles['show']}
      />
      <p className={`${styles['tip-bar']} clearfix`}>
        <span className={`${styles['login-type']} float-left`} onClick={changeLoginType}>
          {isPasswordLogin ? '验证码登录' : '密码登录'}
        </span>
      </p>
      <div className={styles['btn-bar']}>
        <Button type="primary" disabled={!formState.isValid} onClick={onClickSubmitButton}>
          登录
        </Button>
      </div>
    </div>
  );
};

export default function() {
  const [loginType, setLoginType] = useState('password');
  const loginSchema = yup.object().shape({
    cellphone: yup.string().required(''),
    isPassword: yup.boolean(),
    password: yup.string().when('isPassword', {
      is: true,
      then: yup.string().required('password required')
    }),
    smsCode: yup.string().when('isPassword', {
      is: true,
      otherwise: yup.string().required('code required')
    })
  });

  React.useEffect(() => {
    methods.setValue('isPassword', 1, true);
  }, []);

  const methods = useForm({
    mode: 'onChange',
    validationSchema: loginSchema,
    validationSchemaOption: { abortEarly: false },
    validateCriteriaMode: 'firstError'
  });

  const { watch, handleSubmit } = methods;
  watch();

  const changeLoginType = () => {
    const changeType = loginType === 'password' ? 'smsCode' : 'password';
    setLoginType(changeType);
    methods.setValue('isPassword', loginType === 'password' ? 0 : 1, true);
  };

  const onSubmit = async data => {};

  return (
    <div className={styles.page}>
      <div className={styles.content}>
        <FormContext {...methods}>
          <form onSubmit={handleSubmit(onSubmit)}>
            <FormChildren
              loginType={loginType as any}
              changeLoginType={changeLoginType}
              onClickSubmitButton={handleSubmit(onSubmit)}
            />
          </form>
        </FormContext>
      </div>
    </div>
  );
}

**Comment by Liza491646703** [comment]
const FormChildren = (props: any) => {
  const methods = useFormContext();
  const { formState } = methods;
  const { loginType, changeLoginType, onClickSubmitButton } = props;
  const isPasswordLogin = loginType === 'password' ? true : false;
  return (
    <div>
      <CustomInputItem name="cellphone" type="phone" title="手机号" inputType="vertical" />
      <CustomInputItem name="isPassword" title="isPassword" customClass={styles['hidden']} />
      <CustomInputItem
        name="password"
        type="password"
        title="密码"
        inputType="vertical"
        extra="eye"
        customClass={isPasswordLogin ? styles['show'] : styles['hidden']}
      />
      <CustomInputItem
        name="smsCode"
        title="手机动态验证码"
        inputType="vertical"
        customClass={isPasswordLogin ? styles['hidden'] : styles['show']}
      />
      <p className={`${styles['tip-bar']} clearfix`}>
        <span className={`${styles['login-type']} float-left`} onClick={changeLoginType}>
          {isPasswordLogin ? '验证码登录' : '密码登录'}
        </span>
      </p>
      <div className={styles['btn-bar']}>
        <Button type="primary" disabled={!formState.isValid} onClick={onClickSubmitButton}>
          登录
        </Button>
      </div>
    </div>
  );
};
export default function() {
  const [loginType, setLoginType] = useState('password');
  const loginSchema = yup.object().shape({
    cellphone: yup.string().required(''),
    isPassword: yup.boolean(),
    password: yup.string().when('isPassword', {
      is: true,
      then: yup.string().required('password required')
    }),
    smsCode: yup.string().when('isPassword', {
      is: true,
      otherwise: yup.string().required('code required')
    })
  });
  React.useEffect(() => {
    methods.setValue('isPassword', 1, true);
  }, []);
  const methods = useForm({
    mode: 'onChange',
    validationSchema: loginSchema,
    validationSchemaOption: { abortEarly: false },
    validateCriteriaMode: 'firstError'
  });
  const { watch, handleSubmit } = methods;
  watch();
  const changeLoginType = () => {
    const changeType = loginType === 'password' ? 'smsCode' : 'password';
    setLoginType(changeType);
    methods.setValue('isPassword', loginType === 'password' ? 0 : 1, true);
  };
  const onSubmit = async data => {};
  return (
    <div className={styles.page}>
      <div className={styles.content}>
        <FormContext {...methods}>
          <form onSubmit={handleSubmit(onSubmit)}>
            <FormChildren
              loginType={loginType as any}
              changeLoginType={changeLoginType}
              onClickSubmitButton={handleSubmit(onSubmit)}
            />
          </form>
        </FormContext>
      </div>
    </div>
  );
}

**Comment by Liza491646703** [comment]
`CustomInputItem`

**Comment by Liza491646703** [comment]
`const FormChildren = (props: any) => {
  const methods = useFormContext();
  const { formState } = methods;
  const { loginType, changeLoginType, onClickSubmitButton } = props;
  const isPasswordLogin = loginType === 'password' ? true : false;
  return (
    <div>
      <CustomInputItem name="cellphone" type="phone" title="手机号" inputType="vertical" />
      <CustomInputItem name="isPassword" title="isPassword" customClass={styles['hidden']} />
      <CustomInputItem
        name="password"
        type="password"
        title="密码"
        inputType="vertical"
        extra="eye"
        customClass={isPasswordLogin ? styles['show'] : styles['hidden']}
      />
      <CustomInputItem
        name="smsCode"
        title="手机动态验证码"
        inputType="vertical"
        customClass={isPasswordLogin ? styles['hidden'] : styles['show']}
      />
      <p className={`${styles['tip-bar']} clearfix`}>
        <span className={`${styles['login-type']} float-left`} onClick={changeLoginType}>
          {isPasswordLogin ? '验证码登录' : '密码登录'}
        </span>
      </p>
      <div className={styles['btn-bar']}>
        <Button type="primary" disabled={!formState.isValid} onClick={onClickSubmitButton}>
          登录
        </Button>
      </div>
    </div>
  );
};
export default function() {
  const [loginType, setLoginType] = useState('password');
  const loginSchema = yup.object().shape({
    cellphone: yup.string().required(''),
    isPassword: yup.boolean(),
    password: yup.string().when('isPassword', {
      is: true,
      then: yup.string().required('password required')
    }),
    smsCode: yup.string().when('isPassword', {
      is: true,
      otherwise: yup.string().required('code required')
    })
  });
  React.useEffect(() => {
    methods.setValue('isPassword', 1, true);
  }, []);
  const methods = useForm({
    mode: 'onChange',
    validationSchema: loginSchema,
    validationSchemaOption: { abortEarly: false },
    validateCriteriaMode: 'firstError'
  });
  const { watch, handleSubmit } = methods;
  watch();
  const changeLoginType = () => {
    const changeType = loginType === 'password' ? 'smsCode' : 'password';
    setLoginType(changeType);
    methods.setValue('isPassword', loginType === 'password' ? 0 : 1, true);
  };
  const onSubmit = async data => {};
  return (
    <div className={styles.page}>
      <div className={styles.content}>
        <FormContext {...methods}>
          <form onSubmit={handleSubmit(onSubmit)}>
            <FormChildren
              loginType={loginType as any}
              changeLoginType={changeLoginType}
              onClickSubmitButton={handleSubmit(onSubmit)}
            />
          </form>
        </FormContext>
      </div>
    </div>
  );
}
`

**Comment by Liza491646703** [comment]
const FormChildren = (props: any) => {
  const methods = useFormContext();
  const { formState } = methods;
  const { loginType, changeLoginType, onClickSubmitButton } = props;
  const isPasswordLogin = loginType === 'password' ? true : false;
  return (
    <div>
      <CustomInputItem name="cellphone" type="phone" title="手机号" inputType="vertical" />
      <CustomInputItem name="isPassword" title="isPassword" customClass={styles['hidden']} />
      <CustomInputItem
        name="password"
        type="password"
        title="密码"
        inputType="vertical"
        extra="eye"
        customClass={isPasswordLogin ? styles['show'] : styles['hidden']}
      />
      <CustomInputItem
        name="smsCode"
        title="手机动态验证码"
        inputType="vertical"
        customClass={isPasswordLogin ? styles['hidden'] : styles['show']}
      />
      <p className={`${styles['tip-bar']} clearfix`}>
        <span className={`${styles['login-type']} float-left`} onClick={changeLoginType}>
          {isPasswordLogin ? '验证码登录' : '密码登录'}
        </span>
      </p>
      <div className={styles['btn-bar']}>
        <Button type="primary" disabled={!formState.isValid} onClick={onClickSubmitButton}>
          登录
        </Button>
      </div>
    </div>
  );
};
export default function() {
  const [loginType, setLoginType] = useState('password');
  const loginSchema = yup.object().shape({
    cellphone: yup.string().required(''),
    isPassword: yup.boolean(),
    password: yup.string().when('isPassword', {
      is: true,
      then: yup.string().required('password required')
    }),
    smsCode: yup.string().when('isPassword', {
      is: true,
      otherwise: yup.string().required('code required')
    })
  });
  React.useEffect(() => {
    methods.setValue('isPassword', 1, true);
  }, []);
  const methods = useForm({
    mode: 'onChange',
    validationSchema: loginSchema,
    validationSchemaOption: { abortEarly: false },
    validateCriteriaMode: 'firstError'
  });
  const { watch, handleSubmit } = methods;
  watch();
  const changeLoginType = () => {
    const changeType = loginType === 'password' ? 'smsCode' : 'password';
    setLoginType(changeType);
    methods.setValue('isPassword', loginType === 'password' ? 0 : 1, true);
  };
  const onSubmit = async data => {};
  return (
    <div className={styles.page}>
      <div className={styles.content}>
        <FormContext {...methods}>
          <form onSubmit={handleSubmit(onSubmit)}>
            <FormChildren
              loginType={loginType as any}
              changeLoginType={changeLoginType}
              onClickSubmitButton={handleSubmit(onSubmit)}
            />
          </form>
        </FormContext>
      </div>
    </div>
  );
}

**Comment by Liza491646703** [comment]
you can replace CustomInputItem with input

**Comment by bluebill1049** [comment]
did you try validate Yup with raw input?

**Comment by bluebill1049** [comment]
also was previous version works for you? or it's never worked

**Comment by bluebill1049** [comment]
its working here for me: https://codesandbox.io/s/rhf-schema-isvalid-v551m

**Comment by bluebill1049** [comment]
你也可以打中文， 我也看的懂。

**Comment by bluebill1049** [comment]
ok fixed https://codesandbox.io/s/rhf-schema-isvalid-v551m

**Comment by bluebill1049** [comment]
v3.28.12 released should fix your issue, let me know if there is still problem.

**Comment by Liza491646703** [comment]
你好，按照你修改的，我试了一下，还是有一个小问题，就是初始化，没有输入任何内容的时候，submit框应该保持disabled的状态。

**Comment by Liza491646703** [comment]
thanks a lot。

**Comment by Liza491646703** [comment]
何时发布3.28.12正式版？

**Comment by bluebill1049** [comment]
> 你好，按照你修改的，我试了一下，还是有一个小问题，就是初始化，没有输入任何内容的时候，submit框应该保持disabled的状态。

这个情况因该使用 touched

**Comment by bluebill1049** [comment]
3.28.12正式版发布了 有问题再发我。

**Comment by Liza491646703** [comment]
嗯好的，谢谢，有问题再请教您

**Comment by bluebill1049** [comment]
> 嗯好的，谢谢，有问题再请教您

好的 你可以进我们的spectrum聊天室 有时候其他朋友也可以帮你的问题

**Comment by Liza491646703** [comment]
spectrum聊天室入口在哪里

**Comment by bluebill1049** [comment]
https://spectrum.chat/react-hook-form
