### ISSUE TITLE
Access form state without a subscription in a callback.

### ISSUE THREAD

**Issue by adriantrunzo** [react-hook-form/react-hook-form#6243]
**Is your feature request related to a problem? Please describe.**
Currently it is only possible to subscribe to form state (`isDirty`, `isSubmitting`, etc) via the `formState` property returned by `useForm`. Even if you only need to test one piece of form state in an event handler or `useEffect` call, you still have to subscribe, which in some cases can lead to unnecessary re-renders. Consider the following two patterns, which I have written myself a few times, but have simplified for this discussion:

```jsx
// Set up the form.
const { formState, reset } = useForm();
const { isDirty } = formState;

// Set the default values via reset once the data is fetched. If the form is dirty
// we need to show an alert to the user that the form is going to refresh. (Maybe
// a background fetch is giving new remote data since the first page load, etc).
useEffect(() => {
  if (data == null) {
    return;
  }

  if (isDirty) {
    window.alert('The data has been updated since you started...')
  } 
  
  reset(data)
}, [data]) // Only run hook when data changes, but unfortunately the entire component will still re-render when isDirty changes.
```

```jsx
// Set up the form.
const { formState } = useForm();
const { dirtyFields } = formState;

const handleSuccessfulSubmit = () => {
  window.alert('Success!!')

  // Send analytics showing all of the fields the user modified for this submission.
  sendTrackingInformation(dirtyFields)
}
```

In both of these cases I have to subscribe to `isDirty` or `dirtyFields`, even though I just need to get their values once in a callback. The distinction I am trying to make here is similar to the one that exists between `watch` and `getValues`. There is no equivalent to `getValues` for `formState`.

**Describe the solution you'd like**
A method returned by `useForm` called `getFormState` would allow me to query the form state without needing a subscription. In the second example above, I wouldn't need to subscribe to `dirtyFields` and my component would not re-render every time a new field becomes dirty. I imagine calling `getFormState` like so:

```js
getFormState() // -> Return the current values for all of the properties of formState.
getFormState('dirtyFields') // -> Return the current value of just one of the properties.
```

**Describe alternatives you've considered**
I don't think there are any alternatives because the only interface available currently is subscribing to `formState` after the call to `useForm` as [described in the docs](https://react-hook-form.com/api/useform/formstate).

**Additional context**

**Comment by bluebill1049** [comment]
We did this so form state will be batch updated, react 18 will solve this problem for us.

**Comment by zyasir** [comment]
But how come we allow `getValues`? Isn't this very similar to `getFormState`?

**Comment by bluebill1049** [comment]
> But how come we allow `getValues`? Isn't this very similar to `getFormState`? I posted a video showing it here - #6575

I think most users skipped one of the core reasons for such design:

getValues involve also 0 computation to retrieve the result because it just retrieves values from the store.

however for other form states such as below which does require computation and the idea is to save that consumption if you are not subscribed to those states, **not** only skip the re-render.

for example:

- `dirty` required deep equal against `defaultValues`
- `isValid` required validation against your entire form

This feature is still relevant because it helps with `useEffect`, something like `getFormState` is a different feature request and most likely not going to implement as it doesn't fit the design principle behind this lib (performance).

**Comment by bluebill1049** [comment]
I think this feature would be difficult because we are not only preventing re-render, we actually omit the computation within each form state if not subscribed, so if you are not reading or give hook form a signal, that extra computation will be shut as well. eg calculate isValid/isDirty and etc.

**Comment by Noitidart** [comment]
Currently I was going through all fields and doing `getFieldState` and if all are not dirty, then form is not dirty. Is there now maybe a way to get form sate without extra computation, similar to getFieldState?
