### ISSUE TITLE
Multiple form inside a same page with in different functional component. When click one submit then all the forms are triggering

### ISSUE THREAD

**Issue by ajay-dev-j** [react-hook-form/react-hook-form#625]
I asked the same in Spectrum too.

**Comment by bluebill1049** [comment]
I will take a look there, issue like this need more detail. Please follow the template.

**Comment by ajay-dev-j** [comment]
Really sorry for this question. In a hurry, I raised this. Not a validate question.

**Comment by bluebill1049** [comment]
that's ok i will take a look now.

**Comment by mildrenben** [comment]
Did this ever get solved?

It still happens. 

If you have multiple different forms, with multiple separate useForm calls, and you submit one form, then all the others trigger. Similarly, firing trigger() manually will trigger validation for every single field on the page (not just the single form it's meant to be triggering).

When you use useForm() multiple times, does all the data get mixed together as if it's one single form?

**Comment by bluebill1049** [comment]
> Did this ever get solved?
> 
> It still happens.
> 
> If you have multiple different forms, with multiple separate useForm calls, and you submit one form, then all the others trigger. Similarly, firing trigger() manually will trigger validation for every single field on the page (not just the single form it's meant to be triggering).
> 
> When you use useForm() multiple times, does all the data get mixed together as if it's one single form?

it really depends on how you structure your form, sounds like you have wrapped a single form element with multiple `useForm`.
