### ISSUE TITLE
[Bug]: moment() objects are converted to regular objects

### ISSUE THREAD

**Issue by realleyriley** [react-hook-form/react-hook-form#6259]
### Version Number

7.12.2

### Codesandbox/Expo snack

https://codesandbox.io/s/bug-moment-objects-are-converted-to-regular-objects-sqwsh

### Steps to reproduce

1. on first load, notice in the console that 'Moment' is printed before the object. This is correct behavior
2. click on the setValue('m', moment()) button
3. notice in the console that the object is printed without the 'Moment' string, and is just a regular object
4. click the do operation with m button and observe the error

### Expected behaviour

Something strange is going on with Moment objects. I do not know why the console log has 'Moment' before printing a Moment object, but without it the moment library crashes. I lack javascript knowledge here. Is there a better technical explanation for what is going on?

Ideally, React Hook Form should stop converting Moment objects to regular Object so that the Moment library can still operate with its own objects.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
test out with the latest `next` version, it's working fine for me.

**Comment by realleyriley** [comment]
sorry I didn't get a notification for your comment. 

I just tried 7.13.next-5 and 7.13.0 and I'm getting the same error in both cases:
![image](https://user-images.githubusercontent.com/43195764/130526805-9e041a14-5293-4f5d-8afb-9e80ba07e4b3.png)


What do you mean when you say its working fine for you? I assume that you don't get any errors when you click on 'do operation with m'?
