### ISSUE TITLE
[Bug]: Typescript error emitted in editor for seemingly normal form TS(2615)

### ISSUE THREAD

**Issue by sachaw** [react-hook-form/react-hook-form#6262]
### Version Number

7.13.0-next.5

### Codesandbox/Expo snack

https://github.com/meshtastic/meshtastic-web

### Steps to reproduce

1. Go to https://github.com/meshtastic/meshtastic-web/blob/a797cf7be161e7b4bdada75c0d378087804bc8ee/src/pages/settings/Device.tsx#L58
2. Typescript error 'Type of property '[Symbol.species]' circularly references itself in mapped type '{ [K in keyof SharedArrayBuffer]-?: PathImpl<K & string, SharedArrayBuffer[K]>; }'.ts(2615)` is emitted.
3. Adding another identical line underneath calling the same `register` method with the same parameters does emit any error.
4. Data scructure that the form assumes is as follows:
```ts
export interface User {
    id: string;
    longName: string;
    shortName: string;
    macaddr: Uint8Array;
    hwModel: HardwareModel;
    isLicensed: boolean;
}

export declare enum HardwareModel {
    UNSET = 0,
}
```
For reference here is the generated typings for the specific register method:
```ts
const register: <"longName">(name: "longName", options?: Partial<{
    required: string | ValidationRule<boolean>;
    min: ValidationRule<string | number>;
    max: ValidationRule<string | number>;
    ... 9 more ...;
    disabled?: boolean | undefined;
}> | undefined) => UseFormRegisterReturn
```
I have similar forms that throw no such error.

### Expected behaviour

No TS errors emitted

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shymonb** [comment]
This error is emmited whenever you add field of type Uint8Array (or another SharedArrayBuffer object) to the form.
Why is it closed when it's not fixed?

**Comment by Moshyfawn** [comment]
You can see the issue status is `need more detail`. You can't expect us to run someone's whole project and debug the issue. Consider creating [a codesandbox](https://codesandbox.io/s/beautiful-paper-if1je) with an isolated issue reproduction instead to help use investigate it.
