### ISSUE TITLE
[Bug]: zod resolver / error type inconsistency

### ISSUE THREAD

**Issue by mlecoq** [react-hook-form/react-hook-form#6265]
### Version Number

3.7.2

### Codesandbox/Expo snack

https://codesandbox.io/s/silent-sky-u9ps1?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/silent-sky-u9ps1?file=/src/App.tsx
2. Click on submit
3. All message errors are well displayed (according to submitted values)
4. In the code, there is a typescript issue : errors.monday, errors.tuesday ... have no `message` property whereas they are returned

### Expected behaviour

each key has a message property

### Relevant log output

```shell
Property 'message' does not exist on type 'DeepMap<{ closed?: boolean | undefined; fullDay?: boolean | undefined; morningStartAt?: string | undefined; morningEndAt?: string | undefined; afternoonStartAt?: string | undefined; afternoonEndAt?: string | undefined; }, FieldError>'.ts(23
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for the issue report and provide a PR as well. 👍

**Comment by bluebill1049** [comment]
hey @mlecoq I think for object value, we will have to use `NestedValue`, otherwise hook form couldn't differentiate if it's an object of inputs or object of value. I may need to revert the above PR. cc @kotarella1110
