### ISSUE TITLE
formState.isValid does not work

### ISSUE THREAD

**Issue by sergiors** [react-hook-form/react-hook-form#627]
**Describe the bug**
Hey, I had to code a custom input and I found a problem when I use `register` in `useEffect`.
When I use `setValue` the `formState.isValid` keeps `false`

Thats happened when I updated the component to version `3.28.x`, at version `3.27` works

**Codesandbox link**
https://codesandbox.io/s/affectionate-galois-1qgjl

**Expected behavior**
`formState.isValid` should be `true`

**Desktop:**
 - OS: Archlinux and macOS X
 - Browser Firefox
 - Version 71.0

**Comment by bluebill1049** [comment]
thanks @sergiors that was my bad, i did a refactor on validate schema isValid and i have broken few things. sorry about that, but the refactor did clean up few things for long term. 

try this beta, should fix it: 3.28.13-beta.1

**Comment by bluebill1049** [comment]
let me know if that fix it, i will release it ASAP

**Comment by sergiors** [comment]
Thanks! u r awesome! when I goes to Australian I'll buy a couple of beers (or coffee, as u wish) to us

**Comment by bluebill1049** [comment]
ha thanks! no worries :)

**Comment by bluebill1049** [comment]
maybe celebrate a bit too early, can you please verify if it's work for me? (I did my own testing).

**Comment by sergiors** [comment]
Yep, everything works now! :confetti_ball: :confetti_ball: :confetti_ball: :confetti_ball:

**Comment by sergiors** [comment]
Hey @bluebill1049 I caught another problem

https://codesandbox.io/s/react-hook-form-formstateisvalid-with-number-1qgjl
If you uncomment the line 31 or 46 the `formState.isValid` works, but If you don't trigger something `formState.isValid` doesn't work.

Is there any proxy that should trigger?

**Comment by bluebill1049** [comment]
strange it's working for me here? uncomment either 31 or 46?

**Comment by sergiors** [comment]
I guess I explained myself wrong

If you uncomment line 31 46, It will run correctly, but If you don't trigger `watch` or `JSON.stringify(formState, null, 2)`, the `formState.isValid` does not work

**Comment by sergiors** [comment]
If you load the page and type, does not work, but If clear the field and type again works Oo

**Comment by bluebill1049** [comment]
Ok thanks I will sort it out soon.

**Comment by bluebill1049** [comment]
`react-hook-form@3.28.15-beta.1` please help to verify

**Comment by bluebill1049** [comment]
`3.28.15-beta.2` latest :)testing please

**Comment by bluebill1049** [comment]
`3.28.15-beta.4`

**Comment by sergiors** [comment]
Sorry for delay.
Okay, now is triggered, `from State.isValid` start as `true`, I need to type to validation run correctly.

https://codesandbox.io/s/affectionate-galois-1qgjl

**Comment by bluebill1049** [comment]
confirm on my end 3.28.15-beta.3 works :)

**Comment by bluebill1049** [comment]
could you verify in your app as well?

**Comment by bluebill1049** [comment]
let's release this once i get a green light from your end.

**Comment by sergiors** [comment]
confirmed! it's works!

**Comment by bluebill1049** [comment]
sweet let's release this! thanks @sergiors

**Comment by sergiors** [comment]
Thanks you too! u rock!

**Comment by Andrey-Zag** [comment]
So, if someone will need short answer.

Just use next expression. You need to add `{ shouldValidate: true }` as 3rd parameter.

Example:
`setValue('SomeFieldName', value, { shouldValidate: true });`
