### ISSUE TITLE
[Bug]: double validation behavior in version >7.7.1

### ISSUE THREAD

**Issue by jurito** [react-hook-form/react-hook-form#6274]
### Version Number

7.12.2

### Codesandbox/Expo snack

https://codesandbox.io/s/practical-kate-ej2ru?file=/src/App.js

### Steps to reproduce

1. open the console
2. type something in the text field
3. click outside to trigger the blur event
4. in the console it logs "validating" twice.
5. downgrade the version of react-hook-form to 7.7.1
6. type again and blur
7. the console logs "validating" just once

### Expected behaviour

It should log only once as in the 7.7.1 version. 
Without destructuring _formStatus_ to _formStatus:{isValid}_ in _useForm_' hook return value the bug seems not to happen.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jurito** [comment]
Also, with multiple fields the blur event triggers the validation twice on the blurred field and once on the other ones. Still, downgrading to 7.7.1 the validation is triggered only on the blurred field.
[codesandbox](https://codesandbox.io/s/confident-chandrasekhar-dxy6b?file=/src/App.js)

**Comment by bluebill1049** [comment]
expected behaviour, first validation check that single input, second validation which caused by check the entire form `isValid`.
