### ISSUE TITLE
[Bug]: Form Breaks after Google Translate

### ISSUE THREAD

**Issue by bigtone1284** [react-hook-form/react-hook-form#6283]
### Version Number

6.13.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-errors-with-google-translate-d3he7

### Steps to reproduce

I copied and pasted this from [#985](https://github.com/react-hook-form/react-hook-form/issues/985)

This is still a problem. I think the library shouldnt break after Google Chrome Translate the page.

Describe the bug
Translate page to another language by google translator in chrome with use register with validation with custom error message. After click on submit with empty inputs which they are required, try type anything to the input and you got error.

To Reproduce

Go to https://codesandbox.io/s/react-hook-form-errors-with-google-translate-d3he7
Click on open in new window (https://prnt.sc/qygchd)
Translate page by google to another language. (https://prnt.sc/qygfdc)
Don't fill inpust and click on Submit button and try type to input. I get error: NotFoundError
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Codesandbox link
https://codesandbox.io/s/react-hook-form-errors-with-google-translate-d3he7

Video
https://streamable.com/n0p17

Desktop (please complete the following information):
Chrome Version 79.0.3945.130 (Official Build) (64-bit)

### Expected behaviour

The form/page should not break

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
you can consider moving to v7, see if this resolves the problem, otherwise it's a dependency not at the lib level.
