### ISSUE TITLE
[Bug]: using Arrays in base form

### ISSUE THREAD

**Issue by Sindr0me** [react-hook-form/react-hook-form#6285]
### Version Number

7.12.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-typescript-forked-1cst8?file=/src/index.tsx

### Steps to reproduce

- set formdata with arrays inside objects
- trying to use this kind of type definition in prop name of controller "data.${string}.coefficients.${number}"

As i can see the base form won't works with arrays coz it waits an objects therefore i can't set the 'number' in string type of name. Am I right that I can't use arrays - only objects? Or can I set number like '0' instead 'number' in type as you can see in my example? 
Is it like antipattern, then why I'v possibility to set formtype with arrays? bug or it's ok?

### Expected behaviour

i can use this kind of type in name prop of controller : "data.${string}.coefficients.${number}"

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
<img width="974" alt="Screen Shot 2021-08-20 at 5 41 28 pm" src="https://user-images.githubusercontent.com/10513364/130198271-4893ff7f-325b-4201-89e4-e2b3a410693a.png">

This is a limitation as we have stated in the doc.
