### ISSUE TITLE
[Bug]: null values are changed to zero with valueAsNumber option

### ISSUE THREAD

**Issue by frankie567** [react-hook-form/react-hook-form#6287]
### Version Number

7.12.2

### Codesandbox/Expo snack

https://codesandbox.io/s/determined-forest-5l886

### Steps to reproduce

1. Define an object interface with a field `numberField`with type `number | null`
2. Instantiate a form with a default for this field set to `null`
3. Add a form input for this field and set the `valueAsNumber` option to true
4. Run the example: the field is pre-filled with the value zero
5. Without touching the field, on form submission, the value zero is returned for this field.

### Expected behaviour

The field should be empty and the value returned on submission should still be `null`.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
expected behaviour, if you need custom behaviour, use `setValueAs`.
