### ISSUE TITLE
[Bug]: `shouldUnregister: true` combined with `useFormContext()` doesn't remove hidden values

### ISSUE THREAD

**Issue by larrifax** [react-hook-form/react-hook-form#6288]
### Version Number

7.12.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-form-context-forked-4v3rv?file=/src/index.js

### Steps to reproduce

1. Go to 'https://codesandbox.io/s/react-hook-form-v7-form-context-forked-4v3rv?file=/src/index.js'
2. Fill in values in all 3 fields
3. Submit the form. Console should log all 3 values.
4. Click the "Toggle nested input" button
5. Submit the form. Console still logs all 3 values, where it should have just logged 2 values
6. Click the "Toggle optional input" button
7. Submit the form. Console logs only 1 value, which is correct

### Expected behaviour

Using `shouldUnregister: true` together with `useFormContext()` doesn't seem to remove hidden inputs from the form value.

I'd expect toggling the nested input and submitting the form would only log the two fields that are currently shown on the screen, but all 3 values are logged. When subsequently toggling the optional input, the submitted form value is (correctly) containing only the single remaining value on screen.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is a limitation with hook form, because `useEffect` is not fired at `useForm`  or `useWatch`,  hence we can't verity if the input is removed from the dom. I will update the doc, to make this more clear and obvious.

**Comment by bluebill1049** [comment]
> unmounted input will need to notify at either useForm, or useWatch's useEffect for hook form to verify input is unmounted from the DOM.

<img width="854" alt="Screen Shot 2021-08-20 at 8 23 20 pm" src="https://user-images.githubusercontent.com/10513364/130219689-de00b45e-4ad2-4e05-93b7-26af517f39fc.png">
