### ISSUE TITLE
Major bug - regression - reading formState.isValid after reset with large nested field array causes browser to freeze

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#6290]
### Version Number

7.12.2

### Codesandbox/Expo snack

https://codesandbox.io/s/angry-wildflower-lry4u?file=/src/App.js

### Steps to reproduce

1. Simply open the sandbox and notice that the lower spinner/browser is frozen 

### Expected behaviour

This bug seems to be related to reading `formState.isValid` after doing a large reset that involves nested arrays. I believe this is a bug because this works fine in version `7.8.0`. If this is a new design limitation, then perhaps a warning or error would be better than freezing the browser. 

What's interesting is that the `reset` operation seems pretty performant under load. Additionally, I'm not adding in any sort of complex validation. It's just reading the `isValid` state which causes the issue.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
None
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wdfinch** [comment]
The precise version this broke was 7.8.2

**Comment by bluebill1049** [comment]
thanks. tested in `next`, looks like it's fixed. will release the 7.13.0 today.

**Comment by wdfinch** [comment]
thanks for the quick fix

**Comment by bluebill1049** [comment]
👍 thanks for the detailed report as usual @wdfinch
