### ISSUE TITLE
[Bug]: react-hook-form force you to fill a disabled/readOnly field

### ISSUE THREAD

**Issue by jnthnk** [react-hook-form/react-hook-form#6292]
### Version Number

7.12.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-form-context-ytudi

### Steps to reproduce

1. Go to https://codesandbox.io/s/react-hook-form-v7-form-context-ytudi
2. Update all deps to latest stable
3. Go to the file Test.js
4. Add required rule to the register function inside input
5. Add readOnly or disabled in that input
6. Try to submit
7. Can't submit... the disabled input is required (?)

### Expected behaviour

The form should submit even if a required field now is disabled.

### What browsers are you seeing the problem on?

Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jnthnk** [comment]
I use FormProvider BTW

**Comment by bluebill1049** [comment]
the question is why is `disabled` combined with `required`?
