### ISSUE TITLE
[Bug]: useController with no defaultValues

### ISSUE THREAD

**Issue by csantos1113** [react-hook-form/react-hook-form#6293]
### Version Number

7.12.2

### Codesandbox/Expo snack

https://codesandbox.io/s/usecontroller-forked-incws

### Steps to reproduce

1. Go to https://codesandbox.io/s/usecontroller-forked-incws?file=/src/App.tsx
2. Open the console
3. Type anything in the field

### Expected behaviour

Using `useController` in a form that hasn't defined `defaultValues` should not have warnings in the console about uncontrolled inputs.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Relevant log output

```shell
Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at div
    at Input (https://incws.csb.app/src/App.tsx:35:59)
    at form
    at div
    at App (https://incws.csb.app/src/App.tsx:61:47)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by csantos1113** [comment]
Additional context, the warning is not present when using the `register()` method from `useForm`,

See the: https://codesandbox.io/s/react-hook-form-register-ts-forked-e2lw3

**Comment by bluebill1049** [comment]
<img width="951" alt="Screen Shot 2021-08-21 at 9 00 15 am" src="https://user-images.githubusercontent.com/10513364/130301055-8b50e52b-22c4-462d-9f96-ad92ed29a5cd.png">

>You need to either set defaultValue at the field-level or call useForm with defaultValues. If both are set,devaultValues will be used.
