### ISSUE TITLE
onSubmit reValidateMode triggers validation when form is emptied after being submitted

### ISSUE THREAD

**Issue by danielhochman** [react-hook-form/react-hook-form#631]
**Describe the bug**
onSubmit reValidateMode incorrectly triggers validation when form is emptied after being submitted

**Codesandbox link**
https://codesandbox.io/s/hardcore-mendeleev-g02m8

**Expected behavior**
Form will not validate when it is emptied after submission because that is not a submission.

**Comment by bluebill1049** [comment]
thanks @danielhochman i will patch that soon :) good pick up
