### ISSUE TITLE
[Bug]: Controller change the Material-UI TextField to be controlled component

### ISSUE THREAD

**Issue by askariacc** [react-hook-form/react-hook-form#6311]
### Version Number

7.13.0

### Codesandbox/Expo snack

https://codesandbox.io/s/rhf-controller-bug-report-vhn8h

### Steps to reproduce

1. Enter the value in the field
2. Check the CSB console
3. See error

### Expected behaviour

Console should not display such errors

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
<img width="933" alt="Screen Shot 2021-08-23 at 5 04 02 pm" src="https://user-images.githubusercontent.com/10513364/130404619-1a093323-362f-451b-b40f-f30688ef4bd8.png">
