### ISSUE TITLE
[Bug]: useFieldArray v5 not working as expected

### ISSUE THREAD

**Issue by floustao** [react-hook-form/react-hook-form#6327]
### Version Number

5

### Codesandbox/Expo snack

https://codesandbox.io/s/calc-forked-wgm88?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/calc-forked-wgm88?file=/src/App.tsx
2. Add some values to the inputs and click on submit
3. it will not submit
4. If you upgrade the react-hook-form to v7 in the dependencies tab and click submit, it will work.

Any reasons why?
The code sandbox is a copy of https://react-hook-form.com/v5/api#useFieldArray
Thanks for the help!

### Expected behaviour

It should submit with v5 (?)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
v5 is no longer maintained, please upgrade to v6 or v7.

**Comment by bluebill1049** [comment]
same code with v6: https://codesandbox.io/s/calc-forked-9nceu?file=/src/App.tsx

**Comment by floustao** [comment]
Thanks for the quick reply @bluebill1049 
Unfortunately, it's not an option for the team to upgrade at the moment as we heavily rely on react-hoof-form and we have a short deadline for this new feature :/

**Comment by bluebill1049** [comment]
I belive v5 and v6's break change is minor, check out the release note or try to update to the latest v5.
