### ISSUE TITLE
[Bug]: handleSubmit won't return defaultValue of Controller

### ISSUE THREAD

**Issue by uny** [react-hook-form/react-hook-form#6328]
### Version Number

v7.13.0

### Codesandbox/Expo snack

https://codesandbox.io/s/long-night-47pul

### Steps to reproduce

1. Go to https://codesandbox.io/s/long-night-47pul
2. Click on 'Submit'
3. Check the console output.

### Expected behaviour

`{value: 0}` is expected.

On the below cases, it works well.
* `defaultValue = 1`
* react-hook-form v7.12.2

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
`{value: undefined}`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
shouldn't your default value to a string in the first place? `defaultValue={'0'}`

**Comment by uny** [comment]
This also gives undefined.
```
      <Controller
        control={control}
        defaultValue={false}
        name="value"
        render={(props) => (
          <select {...props.field}>
            <option value={true}>0</option>
            <option value={false}>1</option>
          </select>
        )}
      />
```

It seems that it gives undefined when `!defaultValue === true`

**Comment by bluebill1049** [comment]
native input, the value should be `string`, I will looking for a fix, but I don't think the usage of native input is expected.

**Comment by uny** [comment]
In fact, I am using material-ui.
For sake of simplicity, I used native input for the reproduction code.

**Comment by bluebill1049** [comment]
thanks, that's why reproduced code is actually important for maintainers to identify the issue easier.
