### ISSUE TITLE
defaultValues not working in RN

### ISSUE THREAD

**Issue by MehdiJarraya** [react-hook-form/react-hook-form#633]
**Describe the bug**
Default Value is not showing in React Native TextInput, but I can see it in the console.log() when I submit the form.

**Comment by bluebill1049** [comment]
can you share your code snippet?

**Comment by bluebill1049** [comment]
closing this issue. feel free to ask questions if the above comment doesn't solve your issue.

**Comment by MehdiJarraya** [comment]
`
import React from 'react'
import useForm from 'react-hook-form'
import { Button, Text, TextInput, View } from "react-native"


function NewForm(props) {


    const { register, setValue, handleSubmit, errors } = useForm({
        defaultValues: {
            "firstName": "mehdi",
            "lastName": "jarrraya"
        }
    })



    const onSubmit = data => {
        // console.log("erros", Object.entries(errors))
        console.log("submit", data);
    };
    return (
        <View>
            <Text>First name</Text>
            <TextInput
                ref={register({ name: 'firstName' }, { required: true })}
                // ref={register} name="firstName"
                onChangeText={text => setValue('firstName', text, true)}
            />
            {errors.firstName && <Text>This is required.</Text>}

            <Text>Last name</Text>
            <TextInput
                //   ref={register({ name: 'lastName'})}
                ref={register} name="lastName"
                onChangeText={text => setValue('lastName', text)}
            />

            <View>
                <Button onPress={handleSubmit(onSubmit)} title="submit" />
            </View>
        </View>
    )
}
`

**Comment by bluebill1049** [comment]
did you try to use https://github.com/react-hook-form/react-hook-form-input?

**Comment by bluebill1049** [comment]
https://snack.expo.io/@bluebill1049/react-hook-form-input

**Comment by MehdiJarraya** [comment]
Thanks a lot, default values and validation are working using react-hook-form-input.

**Comment by bluebill1049** [comment]
no worries

**Comment by crystalneth** [comment]
The React Native examples in the documentation for custom register does not support default values, and this doesn't appear to be documented. This is pretty confusing. Is there a supported or suggested way to have default values using a custom register as opposed to a Controller?

https://react-hook-form.com/get-started#ReactNative

**Comment by crystalneth** [comment]
The consequence of this is that I implemented initially with the custom register, spent an hour trying to figure out what the right way to handle initial values is, then found this bug, and have to reimplement. 

Not that big a deal, however some more clarity in the docs would be helpful.

**Comment by bluebill1049** [comment]
Take a look at this example @crystalneth : https://react-hook-form.com/get-started#ReactNative

**Comment by crystalneth** [comment]
Thanks. Yeah, that's what I'm looking at. The custom register version does not show how to support initial values. I'm guessing there's a way, however I'd rather do something documented, so the controller based example is what I'm following now, which has a defaultValue param for the Controller element.

Separately would love to see the examples in Typescript.

**Comment by bluebill1049** [comment]
Controller is easier to set defaultValues, in terms of TS we are making improvement on V6, hopefully we will have a dedicated page for `TS`.

**Comment by bemulima** [comment]
I don't understand why defaultVaules not working when input radio value number and set default value as integer? It working only when number as string.  is it normal?

**Comment by bluebill1049** [comment]
@bemulima that's expected. 2 === '2' this is not going to set the input to be checked.

**Comment by bemulima** [comment]
Ok. But I thik it's not comfortable for work because every time before to set defaultValues I must to parse integer to string number.

**Comment by bluebill1049** [comment]
> Ok. But I thik it's not comfortable for work because every time before to set defaultValues I must to parse integer to string number.

why so, I need more context.

**Comment by alvinthen** [comment]
> Controller is easier to set defaultValues, in terms of TS we are making improvement on V6, hopefully we will have a dedicated page for `TS`.

On this, if Controller is indeed easier, would you mind changing the text on `defaultValues` doc?

Instead of `React Native: Custom register or using Controller`, please just suggest to use Controller. And hiding the info behind a button doesn't help too. Not sure what was the initial motive, shouldn't RHF encourage just using the Controller?

I love this package and grateful for the work done, but not without spending hours to only find out the method I'm using is totally unworkable. I started with Controller, but decided to change to custom register to declutter my JSX. After changing everything, only to find out defaultValues don't work.

LMK if you need help, I'd send in a PR once I catch up with my work

**Comment by bluebill1049** [comment]
> > Controller is easier to set defaultValues, in terms of TS we are making improvement on V6, hopefully we will have a dedicated page for `TS`.
> 
> On this, if Controller is indeed easier, would you mind changing the text on `defaultValues` doc?
> 
> Instead of `React Native: Custom register or using Controller`, please just suggest to use Controller. And hiding the info behind a button doesn't help too. Not sure what was the initial motive, shouldn't RHF encourage just using the Controller?
> 
> I love this package and grateful for the work done, but not without spending hours to only find out the method I'm using is totally unworkable. I started with Controller, but decided to change to custom register to declutter my JSX. After changing everything, only to find out defaultValues don't work.
> 
> LMK if you need help, I'd send in a PR once I catch up with my work

Thanks for your feedback. For custom register, you can still make it work with `watch()` which is basically controlled input, but happy to remove that. There is an example here: https://react-hook-form.com/api#reset

**Comment by bemulima** [comment]
I went back to this poblem again. Why we can't set integer default value by react hook form to input radio?
so when:
`useForm({ defaultValues: { number: 2 } });` // not working
but when value type is string working
`useForm({ defaultValues: { number: '2' } });`

Just when form is big it methos is realy not comfortable for coding
