### ISSUE TITLE
[Bug]: DevTool component not working after 7.13.0 update

### ISSUE THREAD

**Issue by guerrap** [react-hook-form/react-hook-form#6337]
### Version Number

7.13.0

### Codesandbox/Expo snack

https://codesandbox.io/s/nervous-orla-3c9kp?file=/src/App.js

### Steps to reproduce

1. Upgrade to `v7.13.0`
2. Add `@hookform/devtools v3.1.0`
3. Render `<DevTool control={control} />` component
4. See error `Cannot read property 'current' of undefined`

### Expected behaviour

DevTools keeps working after the `v7.13.0` update

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by msalahz** [comment]
same here

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/devtools/issues/100

**Comment by bluebill1049** [comment]
thanks for the report, i am working on it.
