### ISSUE TITLE
[Bug]: v7.13.0 setValue with shouldDirty:true does not set formState 

### ISSUE THREAD

**Issue by joniaiuser** [react-hook-form/react-hook-form#6344]
### Version Number

7.13.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v6-ts-formstate-forked-tkl8l?file=/src/index.tsx

### Steps to reproduce

1. setValue with {shouldDirty: true} for arrays does not work without first registering input on each render. 

### Expected behaviour

This behaviour differs from 7.12.2 (can try in sandbox)... expect to work.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
<img width="952" alt="Screen Shot 2021-08-25 at 8 54 27 am" src="https://user-images.githubusercontent.com/10513364/130700402-a22310e0-106e-4b23-a7d1-cd38312e5142.png">
