### ISSUE TITLE
[Bug]: `setValueAs` does not support `undefined` as return value

### ISSUE THREAD

**Issue by hpohlmeyer** [react-hook-form/react-hook-form#6345]
### Version Number

7.13.0

### Codesandbox/Expo snack

https://codesandbox.io/s/friendly-swartz-5ztu4

### Steps to reproduce

1. Go to the [codesandbox reproduction](https://codesandbox.io/s/friendly-swartz-5ztu4)
2. Enter some text into the input
3. Press submit
4. See the console print out the input value as the entered string

### Expected behaviour

If `setValueAs` returns `undefined` I would expect to see `undefined` as the input value during validation and in the `handleSubmit` function.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
doesn't support return `undefined`.
