### ISSUE TITLE
[Bug]: Error typings incorrect, when form type is a union type

### ISSUE THREAD

**Issue by hpohlmeyer** [react-hook-form/react-hook-form#6360]
### Version Number

7.13.0

### Codesandbox/Expo snack

https://codesandbox.io/s/happy-hamilton-hstoc?file=/src/App.tsx

### Steps to reproduce

1. Use a union type with mutually exclusive fields for `useForm`
2. Try to access one of the exclusive fields in `formState.errors`
3. TypeScript will report that no such field exists

### Expected behaviour

No typescript errors for fields defined on the union type.

This is especially relevant, since `zod` is one of the supported validation libraries and it creates union types like that.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hpohlmeyer** [comment]
I have played around a little to see if I can find a fix for it. The root of the problem is `DeepMap` using `keyof T`, which only interates over "visible" fields.

Not get a correct error map, we would need to merge all possible keys and assign a union type of all their values to them.

```ts
type FormType =
  | {kind: "string", stringInput: string }
  | {kind: "number", numberInput: number };
```

would become

```ts
type FormType = {
  kind: "string" | "number,
  stringInput: string,
  numberInput: number
}
```

the furthest I could get in figuring out how to build a type for that is the following:

```ts
type FormType =
  | {kind: "string", stringInput: string }
  | {kind: "number", numberInput: number };

type IntersectionLike<T> = {
    [K in T extends any ? keyof T : never]: T[K];
}

type Result = IntersectionLike<FormType>;
```

`Result` looks like this:

```ts
type FormType = {
  kind: "string" | "number,
  stringInput: unknown,
  numberInput: unknown
}
```

Maybe someone can help out with some more TypeScript knowledge or with a better approach …

**Comment by kotarella1110** [comment]
@hpohlmeyer Thank you for your feedback!

> `T extends any ? keyof T : never`

Great technique using distributive conditional types!
I will fix this 👍

**Comment by hpohlmeyer** [comment]
Wow, this is moving fast! One week on vacation and a lot of progress made.

I have worked around the issue by casting the error object to what you proposed with in option one, so I second @bluebill1049's preference. Since every `FieldError` is optional anyways, I think the theoretical type guard – while more correct – would also make things more complicated.
