### ISSUE TITLE
[Bug]: useFieldArray lost  selected value (select input) on reset or append

### ISSUE THREAD

**Issue by thiagofernando** [react-hook-form/react-hook-form#6377]
### Version Number

7.14

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-m1jj8

### Steps to reproduce

I'm trying to create a array form with pre loaded data (from server), but the select type fields doesnt load data

Just click on Reset button, or append nested button

### Expected behaviour

on reset button, just load default value with select field filled.

on the append button, create a new line with select field filled too

### What browsers are you seeing the problem on?

Firefox, Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
- `reset` will reset the entire form.
-  append you can disabled the auto focus

**Comment by bluebill1049** [comment]
> In my understanding the reset should return the form's original state, which in this case is the preloaded value. This is not the behavior observed. I am wrong?

it reset the whole form, the entire form reference gets reset.

> in append even disabling auto focus the same behavior is observed,

reproduce above in a codesandbox.

**Comment by thiagofernando** [comment]
> 
> 
> > In my understanding the reset should return the form's original state, which in this case is the preloaded value. This is not the behavior observed. I am wrong?
> 
> it reset the whole form, the entire form reference gets reset.
> 
> > in append even disabling auto focus the same behavior is observed,
> 
> reproduce above in a codesandbox.

@bluebill1049 

when  click reset, the input fields restore initial value. The select field gets blank. Same to append. 


Here the csb with autoFocus off
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-m1jj8

**Comment by thiagofernando** [comment]
> > > In my understanding the reset should return the form's original state, which in this case is the preloaded value. This is not the behavior observed. I am wrong?
> > 
> > 
> > it reset the whole form, the entire form reference gets reset.
> > > in append even disabling auto focus the same behavior is observed,
> > 
> > 
> > reproduce above in a codesandbox.
> 
> @bluebill1049
> 
> when click reset, the input fields restore initial value. The select field gets blank. Same to append.
> 
> Here the csb with autoFocus off
> https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-m1jj8

@bluebill1049 there are solution?

**Comment by bluebill1049** [comment]
check your `FormSelect` component, the problem should be live in there.

**Comment by thiagofernando** [comment]
@bluebill1049 
Just for you know, possible have a incompatibility with material-ui select, because I changed the mui select  for react-select and it worked.
