### ISSUE TITLE
[Bug]: registering checkbox with disable and validate causes problems

### ISSUE THREAD

**Issue by markwoon** [react-hook-form/react-hook-form#6379]
### Version Number

7.14.0

### Codesandbox/Expo snack

https://codesandbox.io/s/solitary-voice-u2wvh

### Steps to reproduce

1. Go to https://codesandbox.io/s/solitary-voice-u2wvh
2. Click on submit button
3. See "Must have at least one checked!" error
4. Select checkbox
5. Click on submit button
6. No errors
7. Click on submit button
8. See "Must have at least one checked!" error
repeat from step 5

The validate method is alternately getting the value, then undefined if the `disabled` property is defined and passed to `register()`.

### Expected behaviour

Validation should happen consistently.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markwoon** [comment]
@bluebill1049 After this fix, disabled checkboxes will still submit their value...

Using the same codesandbox:

1. update to latest version of RHF
2. click "A"
3. click "Disable"
4. click "Submit"
5. Check console and see values submitted

**Comment by bluebill1049** [comment]
can i reproduce this in the same codesandbox above?

**Comment by markwoon** [comment]
Yes.
