### ISSUE TITLE
[Bug]: setValue drops all other properties of an default

### ISSUE THREAD

**Issue by eakl** [react-hook-form/react-hook-form#6387]
### Version Number

7.1.0

### Codesandbox/Expo snack

https://codesandbox.io/s/setvalue-svek6?file=/src/Header.js

### Steps to reproduce

Just observe the behavior in the code

I have 3 useEffect
1. One to set the default values with `reset`
2. One to set the `value` property when the dates changes
3. One to update another field when the metric array changes using the current metric values

### Expected behaviour

`metrics.0.value` is a controlled input that changes the `value` of the `metrics.0` object.

When the `value` updates with `setValue('metrics.0.value', ...)` the other keys of `metrics.0` should stay unchanged.

Current behavior, they disappear

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
<img width="1500" alt="Screen Shot 2021-08-30 at 6 52 00 pm" src="https://user-images.githubusercontent.com/10513364/131313359-25ebbaeb-98d7-408a-861d-7d1997fc5b96.png">

**Comment by eakl** [comment]
The CSB is fixed.

Can you reopen the ticket?
