### ISSUE TITLE
[Bug]: DeepMap type behaves weirdly with arrays

### ISSUE THREAD

**Issue by smashercosmo** [react-hook-form/react-hook-form#6390]
### Version Number

7.14.0

### Codesandbox/Expo snack

https://codesandbox.io/s/fervent-lichterman-oopdi

### Steps to reproduce

1. Go to provided codesandbox
2. Check type errors

### Expected behaviour

Honestly, I don't know how it should behave) but there is definitely something wrong with DeepMap type. 
https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gEgHIkxGADUoIBXEALnnJQEsBHS+NATwFsAjJCAbgBQIAB4AHJDCyhIsBBjaiEuVAFUUoAGb0URADwAVAHzwAvPH3wRGEOrS11ILTuDwA-PB0A3EDHg19giLikvDS0HDw8orw+IQkZJQGpBQIVjbAdnQA1ihIAO4oANoAuvAAPvAASuASwLqYMNoA5gA09jn5KMYVALJQorrZuQVtQ53GZmMFJeVVNTB1Dc2jKB0FhhPwAN4C8HvwhXgE1vEpxTRePoIAvvAAZObJlIFiElLg4XIKCACSaACCKDYBk2PF4ICgKEswmstngAAoLGk4ZdfO4MDAWDQNGQ0CAAJRuSKYhDY3EgF7Bd4yCJRBAAERAIFEfQG+ja+ieIE2O32BwA0vBtPAsiA2EgNOZiq4aH9AcD9IV+cVjMiMsSWO5IWw-DFULhyBBoFwICADEqVdDYerYicubN6VBrLMAGL0U0AGXomFd7oQ7k5CVJepQak02j0iuVqph6TsSC4ACtwFh3IzmazzcqOVzjA8AAqwDD0MhJIPGGjKUMOJyRi0x612FCGiBE9Ms-pZ4o58u6qthxwRupRy1quz-GAwKDA7QaHzwFTGdxyoG6RdWuMa-3wCdT4HaisLjdw21Ee0VR3Oipuz3e1M7yfTsspQ8qY-qhPJsD33dP9uZlQexfQ9fwVXNdUDFIbkEAQBGQdApHoSQ2DdEAIAyGh-07LYhWsDg0BoHD6GAGglhQJp4GuGZrjaDFKB5XCQHwmhCiIkit0oto2JoOiEGuUprgEIA

P.S. It's broken since 7.13.0. Version 7.12.2 works fine

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
related: https://github.com/react-hook-form/react-hook-form/issues/6265
