### ISSUE TITLE
[Bug]: Watching nested objects no longer detects changes

### ISSUE THREAD

**Issue by joshkel** [react-hook-form/react-hook-form#6393]
### Version Number

7.14.0

### Codesandbox/Expo snack

https://codesandbox.io/s/cool-sunset-94bpu?file=/src/App.tsx

### Steps to reproduce

1. Check the checkboxes.
2. Note that the "Total count" display doesn't update or only updates once.
3. Downgrade to React Hook Form 7.13.0.
4. Note that the "Total count" display updates as desired when checkboxes are checked or unchecked.

### Expected behaviour

Calling `watch` with a nested form object no longer returns a new object when the values change, so React techniques such as using `useMemo` or `useEffect` to respond to nested changes no longer works.

This is apparently caused by #6336. (7.13.0 worked, and when I reverted #6336 in a local copy of react-hook-form, the problem seemed to go away.) 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we are cached the `watch` result to improve performance, watch result shouldn't be used as dep, it's value it's dynamic based on input value and should be used inside the render function.

**Comment by bluebill1049** [comment]
If you want to detect changes, you can use this hook by kent: https://github.com/kentcdodds/use-deep-compare-effect

**Comment by joshkel** [comment]
I realize this is a late reply, but if I understand things correctly, useDeepCompareEffect doesn't work. It's written to handle the opposite problem (the object is new on every render, even though its contents haven't changed, so too many effects / memo updates are triggered). React Hook Form's behavior is that the same object is used on every render, even if its contents have changed, so not enough effects / memo updates are triggered.

To address this, I added a hook that uses a `watch` subscription (the callback form of `watch`) to get an object that can be used as a useEffect / useMemo dependency:

```ts
export interface WatchDependencyValue<T> {
  value: T;
}

export function useWatchDependency<
  TFieldValues extends FieldValues,
  TFieldName extends FieldPath<TFieldValues>
>(watch: UseFormWatch<TFieldValues>, fieldName: TFieldName) {
  const [state, setState] = React.useState<
    WatchDependencyValue<FieldPathValue<TFieldValues, TFieldName>>
  >(() => ({
    value: watch(fieldName),
  }));
  React.useEffect(() => {
    const subscription = watch((formData, { name }) => {
      if (name != null && (name === fieldName || name.startsWith(fieldName))) {
        setState({ value: get(formData, fieldName) });
      }
    });
    return () => subscription.unsubscribe();
  }, [watch, fieldName]);
  return state;
}

// Sample usage:
const { watch } = useForm();
const subObject = useWatchDependency(watch, 'field');
React.useEffect(() => {
  // Do something with subObject.value.
}, [subObject]);
```
