### ISSUE TITLE
Incorrect type of "field" argument in watch() and setValue() when using nested fields.

### ISSUE THREAD

**Issue by lukaszfiszer** [react-hook-form/react-hook-form#640]
**Describe the bug**
When using `useForm` with a generic parameter and nested form fields, `setValue` and `watch` methods do not accept nested field names with dot notation (`name.firstName`)

**To Reproduce**

```tsx
interface FormFields {
  name: {
    firstName: string
  }
}

function Form() {
  const {watch, setValue, register} = useForm<FormFields>()
  
  watch('name.firstName'); // TS error

  return (
    <form>
      <input name="name.firstName" ref={register} />
      <button type="button" onClick={() => {
          setValue('name.firstName', 'bill')  // TS error
      }}>SetValue</button>
    </form>
  )
}
```

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-nested-field-bug-935tp

**Expected behavior**
First argument of `setValue` and `watch` should be string OR an object should be accepted

**Comment by bluebill1049** [comment]
at this moment, we can only support a flat structure.

```
interface Fields {
  'name.firstName': string,
}
```

**Comment by lukaszfiszer** [comment]
Unfortunately flat structure as above does not work well in `getValues` and `handleSubmit` 

```tsx
getValues({nest: true})["name.firstName"]) // undefined
getValues({nest: true}).name.firstName // TS error

<form onSubmit={ handleSubmit((data) => data["name.firstName"] ) }> // undefined
<form onSubmit={ handleSubmit((data) => data.name.firstName ) }> // TS error
```

The only working solution I've found is to keep nested interface but silent TS error with either `@ts-ignore` or `any`.

 Looking forward to next major version!

**Comment by bluebill1049** [comment]
yea you are right @lukaszfiszer. I could loose the typescript check to make error not sing, but then it lose the point of having it. yea we will improve this on the next major version. I did flat error object because optional chaining was not that popular :(

**Comment by bluebill1049** [comment]
I will close this issue at this stage, we will address that in the next breaking change.

**Comment by timc13** [comment]
Why close this? Is there another ticket tracking this issue (or planned feature)?
