### ISSUE TITLE
[Bug]: React Native setFocus() error after using reset()

### ISSUE THREAD

**Issue by tomasmozeris** [react-hook-form/react-hook-form#6403]
### Version Number

7.14.1

### Codesandbox/Expo snack

https://snack.expo.dev/kYuyr0xf-

### Steps to reproduce

1. Click on "reset" button
2. Click on "setfocus" button
3. Error in console: "Uncaught TypeError: A(...)._f.ref.focus is not a function"

### Expected behaviour

setFocus() to work fine after form reset()

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tomasmozeris** [comment]
Thanks for quick fix, works flawlessly 🙏👍

**Comment by bluebill1049** [comment]
thanks for the report @tomasmozeris 👍
