### ISSUE TITLE
[Bug]:  id key of object gets deleted when appending or prepending on useFieldArray

### ISSUE THREAD

**Issue by tonyjara** [react-hook-form/react-hook-form#6414]
### Version Number

7.14.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-e8ptt?file=/src/index.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-forked-e8ptt?file=/src/index.js
2. Click on prepend and then submit
3. See error on console

### Expected behaviour

Object should have id key. I have not found on the docs anything that points to this behavior. The key is present when logging but as soon as you append or prepend it gets deleted. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`key` is for react to identify the component and not part of the form value.

**Comment by tonyjara** [comment]
I meant that if you have an object, and that object has a key named "id", it gets ignored. I solved it just renaming my id key to something else. But I think it could be helpful to have a heads up on the docs.

**Comment by bluebill1049** [comment]
checkout this prop: 

```
keyName | string = 'id' |   | field array key value, default to "id", you can change the key name.
```

**Comment by bluebill1049** [comment]
- your id field needs to come from your data source.
- react hook form's id is made for **render only**.

```
reset({
  myData: [ { id: 'yourUuid', test: 'whatever' } ]
})

useFiedlArray({
  name: 'myData'
  keyName: 'ChangeMeSoIdontConficltWithYourId'
})

{fields.map((field) => {
   <div key={field.ChangeMeSoIdontConficltWithYourId}>
    <input type="hidden" {...register('id')} />
  </div>
})}
```

**Comment by dlindenkreuz** [comment]
Thanks, it seems to work now, even without the hidden input!

**Comment by jovermier** [comment]
My understanding is the keyName that by default is `id` is an internal react-hook-form generated id. This internal id should not overlap with the form data being collected. I have run into this issue when using graphql where id is used as the unique id. To fix it use a keyName that is not being used in the graphql data structure such as `rhfId`.

A better solution would be for react-hook-form to switch the default keyName to something less commonly used or to have a configurable global default keyName so that it can be set once by the developer.

**Comment by bluebill1049** [comment]
> At the very least the docs should be updated to clear up the confusion.

Great suggestion. I would appreciate any sort of contribution towards the documentation as well.

**Comment by bluebill1049** [comment]
the next version 7.23.0 

https://github.com/react-hook-form/react-hook-form/releases/tag/v7.23.0-next.0
https://github.com/react-hook-form/react-hook-form/releases/tag/v7.23.0-next.1 

```tsx
const App = () => {
  const { control, register, handleSubmit } = useForm<FormValues>({
    defaultValues: {
      test: [{id: 'UUID5678', test: 'data' }] // id will be remained as it match default keyName
    }
  });
  const { fields, append } = useFieldArray({
    control,
    name: 'test',
  });

  return (
    <form>
      {fields.map((field, index) => {
        return <input key={field.id} {...register(`test.${index}.test`)} />;
      })}

      <button
        type={'button'}
        onClick={() => {
          append({
            id: 'UUID1234', // id value will be remained as it match default keyName
            test: '1234',
          });
        }}
      >
        append
      </button>
      <button>submit</button>
    </form>
  );
};
```

will no longer remove id from user's data.
