### ISSUE TITLE
useForm mode - onSubmit without attaching onChange

### ISSUE THREAD

**Issue by penx** [react-hook-form/react-hook-form#6420]
**Is your feature request related to a problem? Please describe.**

At the moment, the onSubmit mode for useForm "will attach onChange event listeners" after the first submit.

https://react-hook-form.com/api/useform/

Accessibility research by [GDS](https://www.gov.uk/government/organisations/government-digital-service) shows that some users can have problems with fields that validate on change or on blur.

> Do not validate when the user moves away from a field. Wait until they try to move to the next part of the service - usually by clicking the ‘continue’ or ‘submit’ button at the bottom of the page.
>
> Generally speaking, avoid validating the information in a field before the user has finished entering it. This sort of validation can cause problems - especially for users who type more slowly.

https://design-system.service.gov.uk/patterns/validation/

I [maintain a library called govuk-react](https://github.com/govuk-react/govuk-react/issues/886) for writing govuk applications using React and would like to add an example of how to use react-hook-form in a way that meets this requirement. At the moment I don't think it would be possible without this feature being added.

**Describe the solution you'd like**
A new mode, called for example onSubmitOnly, which doesn't attach onChange listeners after the first submit.

**Comment by bluebill1049** [comment]
can't you set mode and reValidateMode both to `onSubmit`?

**Comment by penx** [comment]
@bluebill1049 oh sorry I missed that and it's right underneath, I'll close this assuming it works :-D

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/thirsty-glitter-d01z9?file=/src/App.js

**Comment by penx** [comment]
Confirmed this works, thanks, sorry again!

**Comment by bluebill1049** [comment]
no worries at all 👍
