### ISSUE TITLE
[Bug]: getValues with array of fields returns array of strings

### ISSUE THREAD

**Issue by PerfilievAlexandr** [react-hook-form/react-hook-form#6423]
### Version Number

7.14.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-ts-getvalues-txsfg?file=/src/index.tsx

### Steps to reproduce

Click button Alert First & Last Name

### Expected behaviour

We see array of strings, but expect array of objects where key is field name and value is field value

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
expected behavior.
