### ISSUE TITLE
[Bug]: Type error on errors message, non empty array isn't supported

### ISSUE THREAD

**Issue by jgoux** [react-hook-form/react-hook-form#6424]
### Version Number

1.4.2

### Codesandbox/Expo snack

https://codesandbox.io/s/late-resonance-0lspd?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/late-resonance-0lspd?file=/src/App.tsx
2. See error

### Expected behaviour

The type of `formState.errors.projects_ids` should be the same as when we use`Array<string>`, a single `FieldError`.

I guess there is something wrong in `DeepMap`, the bug wasn't there on `1.4.0`.

I can't adapt my types as we use `zod` and automatically infer the types from a validation schema : 

```ts
const validationSchema = z.object({
  project_ids: z.array(z.string().uuid()).nonempty().max(100),
  users: z
    .array(z.object({ ...userSchema.shape }))
    .nonempty()
    .max(100),
});
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://react-hook-form.com/ts#NestedValue

**Comment by bluebill1049** [comment]
for `object` or `array` like input, please use the above type.

**Comment by jgoux** [comment]
@bluebill1049 Thanks for the pointer. Do you have any idea about how to do it automatically when having object or array? As I said above we're relying on Zod for generating the types of the form from the validation schema so I can't really manipulate those types case per case.

**Comment by bluebill1049** [comment]
@kotarella1110 is working on improving the object input type. 👍
