### ISSUE TITLE
watch method should have an option to nest data (similar to getValues)

### ISSUE THREAD

**Issue by bmamouri** [react-hook-form/react-hook-form#643]
I'm watching the form for any changes to update the preview. But `watch`'s output is not consistent with `getValues` output when it is nested.

The `watch` method should have an option to nest the output, similar to `getValues` function.

An alternative is to use `combineFieldValues` function. But since it is not exported, I'd need to copy it in my project which is not DRY.

**Comment by bluebill1049** [comment]
```
data.test
data.last
```

i think you can `watch('data')` 

please supply your issue with a codesandbox if above is not helping too.

**Comment by bmamouri** [comment]
The `watch` method accepts an array of field names. So `watch('data')` is not accepted. I have tried `watch(['data'])`, but that returns undefined too.

**Comment by bmamouri** [comment]
I created a simple sandbox: https://codesandbox.io/s/beautiful-northcutt-yxgnp?fontsize=14&hidenavigation=1&theme=dark

![image](https://user-images.githubusercontent.com/6419173/70480898-09366d80-1b35-11ea-885f-1d448a93b47a.png)

**Comment by bluebill1049** [comment]
<img width="1277" alt="Screen Shot 2019-12-10 at 10 11 37 am" src="https://user-images.githubusercontent.com/10513364/70481041-78ac5d00-1b35-11ea-8507-d439f2ab298f.png">

it does accept 'name'

**Comment by bluebill1049** [comment]
works similar as lodash.get function

**Comment by bmamouri** [comment]
In my case, I would like to watch all the fields in the form

**Comment by bluebill1049** [comment]
```
  watch();
  const watchAll = getValues({ nest: true })
```

does above solve your current problem?

**Comment by bmamouri** [comment]
Not really. Because I want to watch for changes, and whenever something changed, I need to update the preview.

If I can't use `watch`, I need to do the following which is overly complex:

1. Attach `onChange` handler to every input.
2. On the change handler, wait 500 ms (smelly code) until react update the data. (otherwise `getValues` returns the previous data)
3. Use `getValues` to get updated data and update the `preview` state so react update the preview.

**Comment by bluebill1049** [comment]
why not? when you invoke `watch()` it will watch everything on the field. did you try in your codesandbox?

**Comment by bluebill1049** [comment]
I don't get it make `watch()` return nested structure is different form the below code
```
watch();
const watchAll = getValues();
```
can you try this in your codesandbox?

**Comment by bluebill1049** [comment]
<img width="1260" alt="Screen Shot 2019-12-10 at 10 25 25 am" src="https://user-images.githubusercontent.com/10513364/70481665-659a8c80-1b37-11ea-89db-67b17f945994.png">

**Comment by bmamouri** [comment]
The problem is that `getValues` gives you the stale data. I will create a code sandbox.

I am curious to know why you are against adding a `nest` option to `watch` method. It is simple, and create consistency. I can send you a PR if you accept it.

**Comment by bluebill1049** [comment]
I am not denying that `watch()` should somehow return nested data as well (need some thoughts), try to offer an alternative solution for now.

**Comment by bluebill1049** [comment]
> The problem is that `getValues` gives you the stale data. I will create a code sandbox.
> 
> I am curious to know why you are against adding a `nest` option to `watch` method. It is simple, and create consistency. I can send you a PR if you accept it.

thanks would like to see a codesandbox, to make it work is pretty easy i just want to keep the api as simple as possible, somehow avoid second argument is preferred. I can keep this issue open until i figure out something.

**Comment by bluebill1049** [comment]
maybe this: `watch({ nest: true })` is better than second argument and consistent with getValues()

**Comment by bmamouri** [comment]
Understood. Thank you for that. I will send you a sandbox soon.

Great library by the way, and thanks for all the hard work.

**Comment by bmamouri** [comment]
[New Codesandbox](https://codesandbox.io/s/optimistic-morning-ynb1v?fontsize=14&hidenavigation=1&theme=dark) that demonstrate the issue with using `getValues` for my use case.

![image](https://user-images.githubusercontent.com/6419173/70482632-186bea00-1b3a-11ea-91d9-c25cc26827d4.png)

**Comment by bluebill1049** [comment]
works for me with your codesandbox

**Comment by bmamouri** [comment]
Can you please follow this steps to reproduce the issue:

1. Type something in the first input.
2. Notice that the preview is updated.
3. Click on 'Add name'
4. Notice that the new name (currently empty) does not exists in the preview.

**Comment by bluebill1049** [comment]
oh i see, the new node.

**Comment by bluebill1049** [comment]
@bmamouri if you got sometime you want to submit a PR? with what i suggested above?
`watch({nest: true})`, otherwise i can work on it later this week as well.

**Comment by bmamouri** [comment]
I think not that many people are using `watch` method. That's why nobody has reported a similar issue. Nevertheless, I think the `watch` method is very powerful.

I am happy to submit a PR. Will send one it through soon. Thanks again

**Comment by bluebill1049** [comment]
awesome. thanks @bmamouri in your PR you will get a beta version each commit (with codesandbox) so you can test it out too (hopefully it works 👍)

again thanks for the issue and willingness to contribute.

**Comment by bmamouri** [comment]
There is an issue with `watch({nest: true})`. Users would lose the ability to specify which data they would like to watch.

They would need to choose exclusively if they care about nesting, or about watching a subset of form data. (because a subset of form data can be nested too: `groups[0].questions[0].answers`)

I think the `watch` function signature should be like the following:

```
  function watch(
    fieldNames?: Name | string | (Name | string)[] | undefined,
    defaultValue?: string | Partial<Data> | undefined,
    payload?: { nest: boolean }
    {
  ): FieldValue | Partial<Data> | void
```

However, it is a bit verbose. Another option is to add a new `watchNested` function which I think is terrible. Yet another option is to keep the `watch` method intact, and export `combineFiledValues` function so the users of the library can nest the data themselves if they want. (which is not great either)

What do you think?

**Comment by bluebill1049** [comment]
I think with `watch({nest: true})`, users can deconstruct themselves similar to a local state, which should be fine.

**Comment by bmamouri** [comment]
So just to be clear you are thinking of this:

```
  function watch(
    payload?: { nest: boolean },
    defaultValue?: string | Partial<Data> | undefined,
    {
  ): FieldValue | Partial<Data> | void
```

So users can't choose `fieldNames` anymore. 

I think it is a great idea, but it would be a breaking change, right?

**Comment by bluebill1049** [comment]
> So just to be clear you are thinking of this:
> 
> ```
>   function watch(
>     payload?: { nest: boolean },
>     defaultValue?: string | Partial<Data> | undefined,
>     {
>   ): FieldValue | Partial<Data> | void
> ```
> 
> So users can't choose `fieldNames` anymore.
> 
> I think it is a great idea, but it would be a breaking change, right?

yes :)

not breaking change tho

```
function watch(): FormValues;
  function watch<T extends FieldName<FormValues>>(
    field: T & string,
    defaultValue?: string,
  ): FormValues[T];

// new one?
  function watch<T extends FieldName<FormValues>>(
    field: { nest: boolean },
    defaultValue?: string,
  ): FormValues[T];

  function watch(
    fields: FieldName<FormValues>[] | string[],
    defaultValues?: Partial<FormValues>,
  ): Partial<FormValues>;
  function watch(
    fieldNames?: FieldName<FormValues> | FieldName<FormValues>[],
    defaultValue?: string | Partial<FormValues>,
  ): FieldValue<FormValues> | Partial<FormValues> | string | undefined {

```

**Comment by bmamouri** [comment]
Thanks Bill.

Unfortunately, I realized that `watch` has the same stale problem that `getValues` has.

Since the form inputs are uncontrolled, sometimes it take a while for the DOM to get updated. So you get the stale data. This does not cause any problem in most cases because when the form is submitted, the changes has reflected to the DOM. But in my case, I want to preview the form in real time.

I have to find another way to solve the issue. Thanks for the help, again. Feel free to close the issue.

**Comment by bluebill1049** [comment]
oh ok, let me know when you find better solution. I am keen to know the fix.
