### ISSUE TITLE
[Bug]: Error focus passed to wrong input when using register & Controller

### ISSUE THREAD

**Issue by zacol** [react-hook-form/react-hook-form#6432]
### Version Number

7.14.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-register-and-controller-jexsr

### Steps to reproduce

1. Go to the Sandbox
2. Click on the submit button (leave both inputs empty)
3. The first name input is focused even though select also contains errors and is defined first.

### Expected behaviour

A form that contains components that use a mix of register and Controller it prioritizes the autofocus to the inputs that use register.

The form should respect the order in which the inputs are laid out when deciding which input to focus on.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is due to the registration order with `register` API, the controller's register will always going to be behind the native input's registration, if the focus order is important, consider move everything into `Controller` or `register` only.

**Comment by zacol** [comment]
@bluebill1049 Thank you for your quick reply.

Maybe I'm missing something but didn't you said that this problem should be fixed in v7?
> This issue is getting resolved in V7 @SAGARACH65, in v6 we can't avoid this problem as input gets registered at useEffect which is going to behind of native input register progress.

https://github.com/react-hook-form/react-hook-form/issues/1766#issuecomment-809132070

**Comment by bluebill1049** [comment]
Yea, tried and failed :)

**Comment by zacol** [comment]
Thank you for your efforts. I really appreciate it :)

**Comment by bluebill1049** [comment]
I did consider having an API for ordering the index manually. 

`focusIndex: [....]`, but it's very manually and not scalable for large and complex forms, in fact, it's almost too difficult for different view point and media. as you know CSS queries can change input order as well. If anyone have better suggestion or idea, feel free to provide.
