### ISSUE TITLE
Wrapping field properties in useCallback

### ISSUE THREAD

**Issue by mrowe009** [react-hook-form/react-hook-form#6435]
**Is your feature request related to a problem? Please describe.**
The properties inside of field in `useController` are not being memorized.

therefore even just focusing into an input (click inside), and unfocusing (click outside) causes a re-render of the fields properties.

![Screenshot from 2021-09-02 18-41-34](https://user-images.githubusercontent.com/7875131/131925384-230cb632-a63f-480b-9d74-344b69e4fda7.png)

**Describe the solution you'd like**
wrapping the fields props (onChange, onBlur, ref) in a `useCallback`, so those fields become memoized 

is there a reason why these properties are not surrounded in a `useCallback`?

**Comment by bluebill1049** [comment]
We had this feature request before taking a look at this PR: https://github.com/react-hook-form/react-hook-form/pull/5113

**Comment by rubber-duck-software** [comment]
👍 This would be a really big deal! Currently have an expensive-to-render controlled component that I cannot effectively memoize because these fields change so often!

**Comment by rubber-duck-software** [comment]
This should be categorized as a bug. See my comment here  https://github.com/react-hook-form/react-hook-form/issues/5113#issuecomment-917013572 .

**Comment by mattsputnikdigital** [comment]
I have just hit this issue as well, given the claims for RHF I had assumed it would not cause re-renders and could be memorised.

**Comment by rubber-duck-software** [comment]
This is such a big deal! Thanks @bluebill1049 ! Really excited to convert all forms to using react-hook-form now!
