### ISSUE TITLE
[Bug]: Type of defaultValue expected by useController cannot be defined in reusable input

### ISSUE THREAD

**Issue by slugalisk** [react-hook-form/react-hook-form#6444]
### Version Number

7.14.2

### Codesandbox/Expo snack

https://codesandbox.io/s/charming-northcutt-zyv9p?file=/src/App.tsx

### Steps to reproduce

1. Go to codesandbox.io/s/charming-northcutt-zyv9p?file=/src/App.tsx
2. Scroll line 26
3. See the typescript error.

### Expected behaviour

The type (string) of the default value should be assignable to `defaultValue` because `name` can only be the key of a string type field value from type T. This broke in a recent update but it may only ever have worked because the typing used to be more lax.

It's not really relevant but from the input implementer's perspective this functions correctly - see lines 53 and 54 where the valid and invalid names are flagged correctly.

I looked through 50+ implementations of this library on GitHub and I didn't see anyone who managed to write a reusable type safe input. Everyone resorts to typing `control` as `any` or `Control<any>` or using `UseControlProps<any>` so there's clearly a fair bit of confusion around how this should be written. Assuming it's possible it would be helpful to have an example.

### Relevant log output

```shell
(property) defaultValue?: UnpackNestedValue<PathValue<T, Path<T>>>
Type 'string' is not assignable to type 'UnpackNestedValue<PathValue<T, Path<T>>>'.ts(2322)
controller.d.ts(21, 5): The expected type comes from property 'defaultValue' which is declared here on type 'UseControllerProps<T, Path<T>>'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by slugalisk** [comment]
sorry, i forgot to set a title the first time...

**Comment by bluebill1049** [comment]
all good duplicated: https://github.com/react-hook-form/react-hook-form/issues/6442

Discussion: https://github.com/react-hook-form/react-hook-form/discussions/6443
