### ISSUE TITLE
Validation min:1 in number fields doesn't work correctly

### ISSUE THREAD

**Issue by ingridoberbuchler** [react-hook-form/react-hook-form#645]
**To Reproduce**

1. Set validateRule `min: 1`
2. try write in input 0 - error - it's ok
3. write 01, 001, etc.... no error handled

**Comment by bluebill1049** [comment]
it works: https://codesandbox.io/s/naughty-davinci-e1br4

**Comment by bluebill1049** [comment]
i think you are using type as `string`

**Comment by ingridoberbuchler** [comment]
@bluebill1049 It doesn't works!. Try type to number input `0001` Is the 01, 001, 00001  etc. good number values?
