### ISSUE TITLE
[Bug]: calling useController's field.onChange with 'undefined' does not trigger watch/useWatch until another form component's value changes

### ISSUE THREAD

**Issue by VeriClock-Bryce** [react-hook-form/react-hook-form#6456]
### Version Number

7.14.2

### Codesandbox/Expo snack

https://codesandbox.io/s/usecontroller-forked-7vr5u?file=/src/App.tsx

### Steps to reproduce

1. Goto sandbox:
https://codesandbox.io/s/usecontroller-forked-7vr5u?file=/src/App.tsx

2. Note there are two controls, a controlled component constructed with useController, and a basic input text field

3. Type a string 'asdf' into the first input box.  Notice that it's value updates in the html at the bottom, coming from 'watch('first')'.

4. Highlight and delete asdf - note that in the component's code, if the value of the field is the empty string, it passes 'undefined' through to onChange, not the empty string (this is to mimic some controlled components where I am seeing this bug in practice).

5. Note that watch('first') did not update and the value in the html is still rendering as 'asdf'

6. Type a single character into the second input box, 'another'.  

7. As soon as one character is typed, the watch('another') fires and outcomes the 'undefined' value

### Expected behaviour

In step 4 above, I would expect upon deleting the value and passing 'undefined' to onChange, watch('first') would output undefined immediately.  Not (what is at this stage the previous value) 'asdf' again.

I stepped through the code, field.onChange goes through useController.ts  to createFormControl.ts  there is this chunk of code:

`      
if (!isUndefined(inputValue)) {
        set(_formValues, name, inputValue);
}
`

Which seems to be the culprit, skipping the step if the value is undefined.  

I can work around this by intercepting the output and passing in null and working with that instead.  If this is intentional, I'd be interested to know what the thinking was.

Great library, thanks a lot.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we don't allow `undefined` for an input value, use `null` or empty string instead.

## why

`undefined` should be avoided for form value, it creates an issue when controller identity the defaultValue is from inline or from `useForm`.

**Comment by VeriClock-Bryce** [comment]
ok, thanks for the info.  I can understand how it might allow some other behaviour to work correctly.  I found it odd since the 'undefined' value eventually propagates through, but just not without a forced re-render by some other means than the controlled component calling control.onChange.
