### ISSUE TITLE
[Bug]: the `required` validation is not working with the `valueAsDate` option

### ISSUE THREAD

**Issue by jpbarela** [react-hook-form/react-hook-form#6465]
### Version Number

7.14.2

### Codesandbox/Expo snack

https://codesandbox.io/s/keen-thunder-txevs?file=/src/App.js

### Steps to reproduce

1. Go to the sandbox 
2. Click on the submit button 
3. See the `Text Input Required` div

### Expected behaviour

Expect to see `Date Input Required` div or have the `requiredDate` error populated.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Date object should be using validate function instead. Required only check empty string and falsey value not object.
