### ISSUE TITLE
 when i watch the data or after the submission of form it is returning all the values in string  and devtools is not showing the type of that field

### ISSUE THREAD

**Issue by praveshsapkota** [react-hook-form/react-hook-form#6467]
### Version Number

v7.15.0

### Codesandbox/Expo snack

https://codesandbox.io/s/dreamy-brown-iby1s?file=/src/App.tsx

### Steps to reproduce

type FormValues = {
	first-name: string;
	last-name: string;
	age: number;
}

const  {
		handleSubmit,
		watch,
	} = useForm<FormValues>({
		defaultValues: datas,
});

const watchformdata = watch()

after submission {
console.log(watchformdata) 
}

### Expected behaviour

expected output
{
   
    "first-name": "ethan",
    "second-name": "rogue ",
    "age": 22
}

### What browsers are you seeing the problem on?

Chrome , brave 

### Relevant log output

```shell
// output for watchformdata /// all values are string 
{
   
    "first-name": "ethan",
    "second-name": "rogue ",
    "age": "22"
}
```
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I don't understand the issue here...

**Comment by bluebill1049** [comment]
typescript is for type, not for run time result and input is string by default.

**Comment by praveshsapkota** [comment]
> typescript is for type, not for run time result and input is string by default.
> 
> note, you are using v6 syntax with v7.

how to change run time result   values from string to number  the "age" is returning string  i have defined its type to be number

**Comment by bluebill1049** [comment]
@praveshsapkota https://react-hook-form.com/api/useform/register

have a look at this section `setValueAs` and `valueAsNumber`, if you need something completely custom, i suggest you build a controlled component and wrapped with `Controller`:

https://react-hook-form.com/advanced-usage#TransformandParse
