### ISSUE TITLE
[Bug]: Ref lost in Controller after reset

### ISSUE THREAD

**Issue by 913-Filp-Teodor** [react-hook-form/react-hook-form#6478]
### Version Number

7.14.0

### Codesandbox/Expo snack

https://codesandbox.io/s/controller-rules-forked-8cqw6?file=/src/App.tsx

### Steps to reproduce

1. Go to sandbox
2. Click on 'submit'
3. See input was focused
4. Click on 'reset'
5. Click on 'submit'
4. See input was not focused anymore

### Expected behaviour

the input should be focused even after resetting the form and submitting

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
works with the latest.
