### ISSUE TITLE
[Bug] [ReactNative]: Property 'xxx' does not exist on type 'FieldError' (Cannot find name 'FileList' in node_modules/react-hook-form/dist/types/utils.d.ts)

### ISSUE THREAD

**Issue by paulintrognon** [react-hook-form/react-hook-form#6479]
### Version Number

7.15.0

### Codesandbox/Expo snack

Cannot reproduce on Web

### Steps to reproduce

1. `npx react-native init MyApp --template react-native-template-typescript`
2. `cd MyApp`
3. `yarn add react-hook-form`
4. Replace `App.tsx` with:
```tsx
// App.tsx
import React from 'react';
import {useForm} from 'react-hook-form';
import {View} from 'react-native';

interface FormData {
  firstName: string;
}

export default function App() {
  const {
    formState: {errors},
  } = useForm<FormData>();

  console.log(errors.firstName);

  return <View />;
}
```

5. **Error:** `Property 'firstName' does not exist on type 'FieldError'.ts(2339)`

### Expected behaviour

No errors, or at least a mention on how to fix this error on the documentation

### How to fix

When you open file `node_modules/react-hook-form/dist/types/utils.d.ts`, there are errors as well:
- Cannot find name 'FileList'
- Cannot find name 'File'

If you remove the mentions of FileList and File, or if you add

```
interface File extends Blob {
    readonly lastModified: number;
    readonly name: string;
}

interface FileList {
    [Symbol.iterator](): IterableIterator<File>;
}
```
The error goes away (thanks https://github.com/react-hook-form/react-hook-form/issues/2419#issuecomment-669718660)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aardvarkk** [comment]
I just ran into this with many of my error fields. Downgrading to 7.14.2 fixed the problem. Looks like some kind of typing issue on the FieldError type returned in `errors`.

**Comment by kotarella1110** [comment]
Sorry. Improvements to `DeepPartial` and `DeepMap` types in `7.15.0`.
This will be resolved when the PR associated with this is merged.
