### ISSUE TITLE
Cannot mutate value of Material-UI Switch manually

### ISSUE THREAD

**Issue by Atralbus** [react-hook-form/react-hook-form#648]
**Describe the bug**
`setValue` does not work on Material-UI `Switch` component, although it has `inputRef`.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-conditionally-register-component-bk642
2. Uncheck `Field 1`
3. See no updates on `Field 2` although it's set to `false` inside useEffect hook.

**Codesandbox link**
[![Edit React Hook Form - setValue on Material UI Switch](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-hook-form-conditionally-register-component-bk642?fontsize=14&hidenavigation=1&theme=dark)

**Expected behavior**
`Switch` component should be updated when it's mutated with `setValue`.

**Desktop:**
- OS: macOS Mojave, v10.14.6
- Browser: Chrome, v78

**Environment**
react: 16.8.6
react-dom: 16.8.6
reach-hook-form: 3.29.0-beta.1
@material-ui/core: 4.7.2

**Additional context**
`inputRef` seems like working fine with MUI `TextField`. This made me think that it would also work with `Switch` component but it wasn't the case. It works fine for managing the state directly (from UI), but it fails on any programmatical update. It looks like the form value is updated but it does not reflect to the `Switch` component.
While preparing the codesandbox I also realized that giving the default values to the hook (`useForm({defaultChecked: {field1: true, field2: true}})`) is not causing the `Switch` components to render as `checked` in the initial state. Could it be an issue with the `Switch` component's internal logic?

P.S. If I'm not mistaken, while debugging the `setValue` function, I saw that `setFieldValue` function was going into `isCheckBoxInput` condition correctly and `shouldRender` was `true`.

**Comment by bluebill1049** [comment]
have you tried to wrap it around with react-hook-form-input?

**Comment by Atralbus** [comment]
@bluebill1049 Yes, it works with `RHFInput` but I was trying to avoid it.
[![Edit React Hook Form - setValue on Material UI Switch](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-hook-form-setvalue-on-material-ui-switch-0koid?fontsize=14&hidenavigation=1&theme=dark)

I see that `react-select` and MUI `Select` are complex and controlled components and I'm using them with `RHFInput` but `Switch` is actually really simple and I thought it was using the underlying native `input` element.

Now, I checked the DOM of controlled `Switch` component and seems like MUI actually doesn't use the input element and handles it with JS & CSS. Here, in the DOM `value` and `checked` never changes.
<img width="1012" alt="Screen Shot 2019-12-11 at 13 51 43" src="https://user-images.githubusercontent.com/4368872/70615475-84734e80-1c1d-11ea-989e-5980755ab2dd.png">

So it seems like only option is to convert it to controlled component with `RHFInput`?

**Comment by bluebill1049** [comment]
yea @Atralbus it's hard for RHF to track the value with MUI switch, I will use RHFInput instead. sometimes I wish UI library can always export their input's ref eg: inputRef={xxx}

**Comment by bluebill1049** [comment]
or you can use a custom register, which is register during useEffect

**Comment by gsouf** [comment]
hi @bluebill1049  could you please elaborate on using custom register?

**Comment by bluebill1049** [comment]
hey @gsouf take a look this section: https://react-hook-form.com/api#Controller
and this example: https://codesandbox.io/s/react-hook-form-controller-079xx

**Comment by gsouf** [comment]
That we helpful, thank you.

How does the Controller works exactly? Does it set the "value" property to the element passed in `as`?

I'm having some warnings saying some components are switching from controlled to uncontrolled. Would prefer to get rid of those warnings if possible.

**Comment by bluebill1049** [comment]
@gsouf please read through the doc, you will find your answers there.

**Comment by gsouf** [comment]
@bluebill1049 nothing I could find, but not a big deal. The issue was because of my storybook. All good.

**Comment by eduardoribeiro17** [comment]
this not working in 4.11.0 version? I have the same situation using this version.

**Comment by devhyunjae** [comment]
I am not sure about the full history, but looks like above example doesn't work anymore. If somebody is getting annoyed in here, try using this kind of code. Since `as` is deprecated and `render` should be used. as in the latest doc.

new doc: https://react-hook-form.com/api#Controller

```
<Controller
  name="switch"
  control={control}
  render={({ onChange, value }) => {
    return (
      <Switch
         checked={value}
         onChange={(e) => onChange(e.target.checked)}
      />
     );
  }}
/>
```

**Comment by asimgiri** [comment]
I encountered the same kind of issues when using the material switch along with the RHF. 

Later found out about the update to version 7 of RHF,  Here's a code I used : 

```
            <FormControlLabel
              control={
                <Controller
                  control={control}
                  name="active"
                  render={({ field: { onChange, ref } }) => (
                    <Switch
                      color="primary"
                      inputRef={ref}
                      onChange={onChange}
                    />
                  )}
                />
              }
              label="Active / Inactive"
              classes={{
                label: classes.switchLabelSmall,
              }}
            />
```
