### ISSUE TITLE
[Bug]: Setting a field's value to an array that uses Controller doesn't provide proper value (array values)

### ISSUE THREAD

**Issue by ampossardt** [react-hook-form/react-hook-form#6484]
### Version Number

7.15.0

### Codesandbox/Expo snack

https://codesandbox.io/s/dreamy-ramanujan-zlmip?file=/src/App.js

### Steps to reproduce

**From scratch:**
1. Add a form that uses `yupResolver`
2.  Configure schema to reflect an object that has a property which is also an object, and the nested object having a field with a value of an array
3. Configure input using `Controller` for the field: something like `section.fieldName` as the name
4.  Try to update data with `setValue` at the section level: something like `setValue('section', { fieldName: ['item'] })`
5.  'Value' passed to the `render` prop doesn't include the field value

**From codesandbox:**

1. Go to attached codesandbox
2.  Click on button under Form 2
3.  No value is output from within the `Controller` render

### Additional Details

Apologies if this isn't as clear due to its nuanced nature - it was hard to describe in the title. Basically, it seems that when using setValue with an object that has some nested array, that value isn't getting passed properly to the controller. I can confirm that the data is properly getting sent down from the API call (in our case) and appears correctly right before calling `setValue`, however the value that's passed to the controller render (and consumed by our component thats rendered) doesn't have the value. In 'Form 3' of the codesandbox, the behavior is as expected when making an update directly to the property.

For reference, my use case is this: the form has a number of sections, each section containing fields. In this case, when we fetch existing data to populate these sections, each part is done separately and needs to update the entire section with the data from a network call. I can confirm the form values are all properly hydrated for all fields except for those that have a value of an array of strings. 

The schema looks something like this:
`
{
  "section": {
    "someField": "string value",
    "anotherField": ["string value"]
  }
}
`
With an updating looking like this:
`setValue("section", {
  someField: "string value",
  anotherField: ["item"]
})
`
And a controller configured something like this:
`
<Controller 
  name="section.anotherField"
  control={control}
  render={({ field }) => (
    <MyComponent value={field.value} />
  )
}/>
`

### Expected behaviour

Nested fields that have a value of an array should be passed to the `Controller` render prop. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report and a good description. Another good example of an issue. Will take a look at it.

**Comment by bluebill1049** [comment]
This is a limitation. 

## Why

The nature of the form should contain a single value for each input, however, as we enter more complex cases we start to introduce object/array inputs, this makes thing difficult for setValue to predict which field or value to update.

in general `setValue` works the best with targeted input names.

eg

```tsx
setValue('test.test.test', 'value')
<input name="test.test.test" />
```

however, for custom components like what you have 

```
setValue("section", {
  arrayValue: ["one", "two"]
});
<Controller
  name="section.arrayValue"
  control={control}
  render={({ field }) => {
    console.log(field);
    return <p>{JSON.stringify(field.value)}</p>;
  }}
/>
```

hook form will look for the field named as `section` first and check if it's a field, in your case, it's not, so hook form will seek to update  `array.0.one`, `array.1.two` and treat it as two separate fields.

**Comment by bluebill1049** [comment]
Just add on top above, it's best to think `setValue` API as set a field value, it needs to find the field first.
