### ISSUE TITLE
Typing for subforms/complex fields

### ISSUE THREAD

**Issue by abelgibayev** [react-hook-form/react-hook-form#6492]
**Is your feature request related to a problem? Please describe.**
I'm migrating an application from formik to react-hook-form and have a problem with migrating complex fields. The idea of them is reusing group of fields in different forms. E.g. Sport and Player entities have field 'translations' that is working with the same subform. This becomes hard if I want to use this subform in different entities, once it may be just `'translations'` in other cases `'player.translations'`

**Describe the solution you'd like**
I'm using `useController` hook to work with this field and would like to define types of this field inside subform, like
`const controller = useController<Translations[]>({ name })` like it's in formik.

**Describe alternatives you've considered**
I tried to accept generic type `FormValues extends {translations: Translation[]}`, but the default value doesn't accept nor `[]`, nor `[] as Translation[]`, even if the name prop of the hook is clearly set as `'translations'`

**Additional context**
![image](https://user-images.githubusercontent.com/22354231/132511397-4d8d0575-cbbe-469e-84f6-69a30766650c.png)

I tried to find answers in documentations, but typescript is used only in `useForm` hook in all examples.

**Comment by bluebill1049** [comment]
can you provide a codesandbox for the above usage?

**Comment by bluebill1049** [comment]
can you provide some details for your codesandbox above and remove all those extra codes if you can? thanks
