### ISSUE TITLE
useFieldArray().append typings should be DeepPartial?

### ISSUE THREAD

**Issue by osdiab** [react-hook-form/react-hook-form#6496]
**Is your feature request related to a problem? Please describe.**
Hi, I am using `useFieldArray()` in a form and when I try to append a new item to the field array, TypeScript complains that what I pass into `append()` needs to be a `Partial<TheFieldType>` instead of `DeepPartial<TheFieldType>`, so the mostly empty value I passed to it doesn't match up.

**Describe the solution you'd like**
Change `append()`, and probably `insert()`, to allow `DeepPartial` instead of `Partial` of the field type

**Describe alternatives you've considered**
Just using a type assertion for now.

**Comment by bluebill1049** [comment]
Thanks for the feature request, however we do not support partial as it will run into issues, this is not only case for typescript as well.
