### ISSUE TITLE
[Bug]: TypeScript fieldState.error is not an array when the relative data type is an array

### ISSUE THREAD

**Issue by peter-oms** [react-hook-form/react-hook-form#6498]
### Version Number

7.14.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-nestedvalue-forked-usecontroller-z72sg?file=/src/App.tsx

### Steps to reproduce

1. Go to [https://codesandbox.io/s/react-hook-form-nestedvalue-forked-usecontroller-z72sg?file=/src/App.tsx](https://codesandbox.io/s/react-hook-form-nestedvalue-forked-usecontroller-z72sg?file=/src/App.tsx)
2. Add a Todo
3. Check the console for the error object output
3. Open `Todos.tsx` and hover on the destructured `error` property
4. See that its type is `FieldError`

### Expected behaviour

Expecting that because the type of todos is an array (defined in `TFormValues.tsx`), any errors that occur when validating the schema would be returned as a FieldError[] array type (it can be seen in the console they are they are actually an array).

This makes getting a particular item in the errors array difficult.

Error type:
![image](https://user-images.githubusercontent.com/83673746/132585750-af88397f-7038-4ffa-8196-14f20a01e66d.png)

Error object:
![image](https://user-images.githubusercontent.com/83673746/132585777-ec2daba7-92f9-48a2-a2ff-b771ae7a9993.png)

Example trying to get the zeroth item of the error array:
![image](https://user-images.githubusercontent.com/83673746/132587187-dd19522c-3977-4aad-bf25-ccce83e7d4a8.png)

### Other attempts

1. I have read a few other issue reports where `NestedValue` was suggested to be used when dealing with arrays or nested structures.  I tried doing this as well, but I haven't been able to achieve any success because I hit another issue in `yupResolver`:<br />
         ```
Property '[$NestedValue]' is missing in type 'TTodo[]' but required in type '{ [$NestedValue]: never; }'.
        ```<br/>
I think this is already covered in [#234](https://github.com/react-hook-form/resolvers/issues/234) of the resolvers package, though. I am not entirely sure that `NestedValue` will actually achieve the behaviour I am looking for though.

   ![image](https://user-images.githubusercontent.com/83673746/132586798-74182516-3542-48e6-a46e-eceb7a42a610.png)

2. Another approach I tried is using `useFieldArray` instead of `useController`, but this wouldn't even register my validation schema errors.<br/>
Here's a codesandbox that logs the global errors object to the console: [https://codesandbox.io/s/react-hook-form-nestedvalue-forked-usefieldarray-p3jtj?file=/src/App.tsx](https://codesandbox.io/s/react-hook-form-nestedvalue-forked-usefieldarray-p3jtj?file=/src/App.tsx)<br/>
I don't prefer this approach anyway, because `useFieldArray` doesn't seem to return the errors related to that field. I tried getting them using another `useController` hook, but having `useFieldArray` and `useController` for the same field in the same component seems to wreak all kind of havoc and ended up breaking updating.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kotarella1110** [comment]
We need to fix the `ControllerFieldState` type.
I will fix this.
