### ISSUE TITLE
After calling reset formState is not Valid even though it should be

### ISSUE THREAD

**Issue by robandrose** [react-hook-form/react-hook-form#650]
**Describe the bug**
In my setup with nested Elements using the FormContext to register with custom validations i ran into problems using the reset functionality. The state of the form will not become valid, unless i enter a value into each field (even though they are not required)

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-form-context-gtcls?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
Call reset function should reset the form properly and not let it dangling in an undefined state

**Comment by bluebill1049** [comment]
what's the step to reproduce?
