### ISSUE TITLE
[Bug]: Form not submitting on testing environment when dealing with Radio Group

### ISSUE THREAD

**Issue by georgekaran** [react-hook-form/react-hook-form#6502]
### Version Number

7.15.1

### Codesandbox/Expo snack

https://codesandbox.io/s/infallible-herschel-clejz?file=/src/App.tsx

### Steps to reproduce

1. Go to `Tests` tab and you'll see that the test is not calling the onSubmit callback but when you do it through the browser it works as expected.

### Expected behaviour

The onSubmit callback should be called on the test.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
submit is async, you can refer to the example below:

https://github.com/react-hook-form/react-hook-form/blob/master/src/__tests__/useForm.test.tsx#L193

**Comment by georgekaran** [comment]
It didn't work. I've updated the [CodeSandbox](https://codesandbox.io/s/infallible-herschel-clejz?file=/src/App.test.tsx) as suggested, is there something that I'm missing?

**Comment by marcospassos** [comment]
@bluebill1049 I'm facing the same problem here. No matter if wrapped into an async act, the callback is never invoked.

**Comment by bluebill1049** [comment]
have a look at this section: https://react-hook-form.com/advanced-usage#TestingForm hope it helps.
