### ISSUE TITLE
[Bug]: useFieldArray returns never[] if path to name contains optional field 

### ISSUE THREAD

**Issue by darylf** [react-hook-form/react-hook-form#6505]
### Version Number

7.4.1

### Codesandbox/Expo snack

https://codesandbox.io/s/vibrant-hermann-2mu3l?file=/src/App.tsx

### Steps to reproduce

 If form includes optional array field, useFieldArray will return with type never[] for fields

This has been documented in two seperate discussions:
* https://github.com/react-hook-form/react-hook-form/discussions/5906
* https://github.com/react-hook-form/react-hook-form/discussions/5517

Changing the object definition to not be optional isn't always feasible. In my case, the objects are from generated code

### Expected behaviour

Fields should be an empty array of the appropriate type 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by darylf** [comment]
I'm using [graphql-codeg-enerator](https://github.com/dotansimha/graphql-code-generator) to create my objects, and it looks like even without the optional field, react-hook-form returns `nothing[]` for the fields object. I assume this is caused by the union type of `Array<T> | T`

I'm not sure if this would bloat the scope of any intended fix to the initial report, but it'd be cool if useFieldArray could handle a union type like this as well, by returning an array of the appropriate type.

---
**Generated code:**

    export type UpdateCreditsMutationVariables = Types.Exact<{
      bookId: Types.Scalars["ID"];
      input: Array<Types.CreditInput> | Types.CreditInput;
    }>;

---
**React-Hook-form:**

    const {
      control,
        formState: { errors, isSubmitting },
        handleSubmit,
        register,
      } = useForm<UpdateCreditsMutationVariables>();

    const { fields } = useFieldArray({
        control, 
        name: "input", 
      });

**Comment by Lemaro86** [comment]
Try to use "@hookform/resolvers": "1.3.7", and react-hook-form@6.15.8
And for name use type like this: 
`control,
  name: `inputs.${nestIndex}.name` as 'name'
`

But you should update your type or interface for inputs array, like this:
`
interface InnerType { creditInput: string, debt: number  } 
`
and parent interface:
`
name: Array<InnerType>
`

And if you trust docs add in the input cast:
`... as const`

But if I using last version of RHF I have so much problem with resolver and yup validation. I'm not recommend to use last.

**Comment by bluebill1049** [comment]
> But if I using last version of RHF I have so much problem with resolver and yup validation. I'm not recommend to use last.

could you provide a bit more detail on this statement above? happy to resolve it, if you can provide more retail and a codesandbox.

**Comment by Lemaro86** [comment]
> could you provide a bit more detail on this statement above? happy to resolve it, if you can provide more retail and a codesandbox.
Thank you, I fixed it with last version it works good, problem was in cast, "any" save the world:
`control?: Control<any, any>;`
Its too hard to use last version resolvers and RHF for "Select" and for structure like this:  Record<Array<Record>>>.
