### ISSUE TITLE
[Bug]: Reseting a form with a file input using `getValues()` produces an error

### ISSUE THREAD

**Issue by roydukkey** [react-hook-form/react-hook-form#6508]
### Version Number

7.15.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-file-input-reset-getvalues-mztmk?file=/src/App.tsx

### Steps to reproduce

1. Go to the Codesandbox
2. After load, wait 3 second to see the error.

### Expected behaviour

I would expect the form to reset, only ever clearing file type inputs (since I don't believe their values can be set).

### Relevant log output

```shell
Failed to set the 'files' property on 'HTMLInputElement': Failed to convert value to 'FileList'.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
you wouldn't be able to set an input's file list programmatically, you can only update its value as string, basically it's not mutable : https://github.com/whatwg/html/issues/3269
