### ISSUE TITLE
Callback function validate could accept the form values as second argument

### ISSUE THREAD

**Issue by VGLoic** [react-hook-form/react-hook-form#651]
I have a form where validation of specific field is based on the value of another field in the form.

I wanted to use the `validate` callback function but this function takes only the new value of the associated field as argument. I ended up doing some nasty overriding of the validate function in such a way that the `validate` function had access to the `getValues` function. Therefore, I was wondering what you though about giving access to the `validate` function the form values.

Another point could be to give access to the validate function an arbitrary ref.

**Describe the solution you'd like**
The signature of the `validate` callback function could become 
```
(newValue, formValues) => myValidateFunction(newValue, formValues)
```
or in the case with a custom ref
```
(newValue, { formValues, myCustomRef }) => myValidateFunction(newValue, formValues, myCustomRef)
```
Where `formValues` contains the other (or old) values of the form and `myCustomRef` is an externally defined ref.

Thanks for the work on this package :).

**Comment by bluebill1049** [comment]
thanks, @VGLoic for your great suggestion. I did think about this when I was design the API, and it would be quite useful when you build inputs that are dependent on another. It's also the reason why i build `getValues` and `watch` API .

However, `getValues()` and `watch()` are both not "free" to invoke, they do consume resource to generate the data, which means you validate function will essentially calling one of them each time even when you are not using them, hence the reason I am not baking them into the `validate` function. 

// validate: (value, allValues)  

this `allValues`  is basically calling `getValues()` each time. 

alternative you can still call validate inside, or make a `curry` function to carry the input value and `getValues` function. hence for now, maybe we can leave as it is util we figure out something is cheap to run.

**Comment by VGLoic** [comment]
I completely understand the arguments, thank you for the quick and detailed answer :)

**Comment by bluebill1049** [comment]
thank you for understanding @VGLoic
