### ISSUE TITLE
[Bug]: Unstable onChange, onBlur, and ref returned from useController

### ISSUE THREAD

**Issue by rubber-duck-software** [react-hook-form/react-hook-form#6514]
### Version Number

7.13.0

### Codesandbox/Expo snack

https://codesandbox.io/s/black-monad-iwtug?file=/src/App.js

### Steps to reproduce

1. Click on the "First name" field to give it focus
2. Click away from the "First name" field to trigger the onBlur event. 
3. Open the Console and notice that the ref for both "First name" and "Last name" has changed

### Expected behaviour

The properties of "field" on UseControllerReturn such as ref, onChange, and onBlur change by reference every time the form state is updated. This is not a huge deal for touchedFields changes, but for other properties such as errors this is a larger issue resulting in may unnecessary renders. 

Note: this issue only exists if the form state proxy is enabled. 

Expected behavior is that the ref, onChange, and onBlur fields returned from useController remain constant, even when other fields are touched. This allows for memoizing the underlying controlled component as well as other optimizations. 

### What browsers are you seeing the problem on?

Chrome, Safari

### Relevant log output

```shell
firstName: ref Changed 
lastName: ref Changed 
firstName: ref Changed 
lastName: ref Changed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
hey there, thanks for the detailed issue report. we don't memory onChange, onBlur and this is expected behavior. For more reference, please follow here: https://github.com/react-hook-form/react-hook-form/pull/5113

**Comment by bluebill1049** [comment]
related feature request: https://github.com/react-hook-form/react-hook-form/issues/6435#issuecomment-916720991
