### ISSUE TITLE
[Bug]: Unregister not working in the example given on offical wesbite

### ISSUE THREAD

**Issue by nuel77** [react-hook-form/react-hook-form#6515]
### Version Number

7.2.2-beta.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-unregister-v6-forked-qs8o6

### Steps to reproduce

1. go to https://codesandbox.io/s/react-hook-form-unregister-v6-forked-qs8o6
2. click  on unregister lastname button 
3. check the alert
4. both last name and first name are showing.

### Expected behavior

only the first name should be shown in the alert after submitting

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I will include a note on this doc for this issue as it occurred quite a few times already.

**Comment by bluebill1049** [comment]
<img width="962" alt="Screen Shot 2021-09-10 at 6 24 47 pm" src="https://user-images.githubusercontent.com/10513364/132824051-87a8a6c8-e5ac-4aff-94e3-d10b59b735b8.png">

>Make sure you already remove that input that has register callback or else the input will get registered again. 

```tsx
const [show, setShow] = React.useState(true)

const onClick = () => {
  unregister('test');
  setShow(false); // make sure to unmount that input so register not invoked again.
}
              
{show && <input {...register('test')} />}
```
