### ISSUE TITLE
[Bug]: TS error while providing defaultValue to Controller using useForm with defaultValues

### ISSUE THREAD

**Issue by pashtet422** [react-hook-form/react-hook-form#6516]
### Version Number

7.15.2

### Codesandbox/Expo snack

https://codesandbox.io/s/he-foked-up-0z4e3?file=/src/App.tsx

### Steps to reproduce

1. Go to [useFieldArray](https://react-hook-form.com/api/usefieldarray) docs
2. Scroll down to 'return' section & copy an example
3. Fill `defaultValues` in `useForm`
3. Try to run it
4. Face with a TS issue with `Controller` component's `defaultValue` prop

### Expected behaviour

no error while providing `defaultValue` to `Controller`

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
(JSX attribute) defaultValue?: undefined
Type 'string' is not assignable to type 'undefined'.ts(2322)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
<img width="833" alt="Screen Shot 2021-09-10 at 6 26 20 pm" src="https://user-images.githubusercontent.com/10513364/132824277-9093390f-6f57-4f64-83af-f68fb4bceb6c.png">

where is your useForm generic?

**Comment by pashtet422** [comment]
Updated
https://codesandbox.io/s/he-foked-up-0z4e3?file=/src/App.tsx

**Comment by bluebill1049** [comment]
looks like this is related to TS compatible issue, reverted to 4.2.2 this issue appears.  changed to the latest resolve the problem.

**Comment by pashtet422** [comment]
Yes! Thanks for your time. I've updated TS to 4.4.2 and the error was gone

**Comment by bluebill1049** [comment]
I am looking into this issue. 👍

**Comment by bluebill1049** [comment]
@kotarella1110 This template string look-up didn't work properly https://github.com/react-hook-form/react-hook-form/blob/master/src/types/utils.ts#L108 I have tested with 4.2.2 and the latest version since fixing the issue.

**Comment by kotarella1110** [comment]
I created a TS issue https://github.com/microsoft/TypeScript/issues/43060 to solve this, and it was fixed in TS `4.3`. 
I think we should add `"typescript":">=4.3.2"` to the `peerDependencies`.

**Comment by bluebill1049** [comment]
That's right! thanks, @kotarella1110 for the confirmation I will update the peer.

**Comment by bluebill1049** [comment]
actually probably not a good idea to add into the peerDep in the package.json, i will include this information in the doc instead. closing here.

**Comment by bluebill1049** [comment]
>Typescript ^4.3 above is the recommended version to work with react hook form.

<img width="983" alt="Screen Shot 2021-09-10 at 9 15 16 pm" src="https://user-images.githubusercontent.com/10513364/132845340-b2773fe6-e915-437f-8712-3d840dabb659.png">
