### ISSUE TITLE
[Bug]: useWatch not updated on all components that are watching

### ISSUE THREAD

**Issue by tkolanko** [react-hook-form/react-hook-form#6520]
### Version Number

7.15.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-js-forked-htumd?file=/src/App.js

### Steps to reproduce

1. Go to Codesandbox link
2. See Field value (correctly updated by setValue) for the first child
3. See "useWatch value" (remain the default) for the second child

This is similar to #6473 except I am watching the same field from multiple components

The useWatch on the second child is triggered before the useEffect on the first child I would expect that the second child becomes aware of changes to the first child

### Expected behaviour

All children who subscribe to be notified when a watched value changes should be notified

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/usewatch

<img width="929" alt="Screen Shot 2021-09-11 at 9 13 06 am" src="https://user-images.githubusercontent.com/10513364/132926768-393669ae-2f9a-4bc0-b934-6493d7314404.png">

> useWatch execution order matters, which means if you are update form value before the subscription is in place, then the value update will be ignored.

**Comment by tkolanko** [comment]
@bluebill1049 The useEffect which calls setValue happens after the second child subscribes to watch the changes, there are console logs which show the order of execution. This problem can also be reproduced by calling watch on the root component, it won’t rerender with the new value after the useEffect

**Comment by bluebill1049** [comment]
<img width="1097" alt="Screen Shot 2021-09-11 at 10 16 29 am" src="https://user-images.githubusercontent.com/10513364/132929606-881342ae-fdfb-49d9-93b3-04e034779d53.png">

and the source code which subscription kicked in the `useEffect`: https://github.com/react-hook-form/react-hook-form/blob/master/src/useWatch.ts#L62

I would consider lifting up the `setValue` to the parent, so the subscription will be there.

**Comment by tkolanko** [comment]
The screenshot shows the subscription in child 2 before the useEffect in child one, in that case the order of execution is subscribe then setValue so it meets the requirements

**Comment by tkolanko** [comment]
@bluebill1049 Here's another sandbox which might show the issue a little better:
https://codesandbox.io/s/react-hook-form-js-forked-3q990?file=/src/App.js


In the parent component a watch is set before it renders the child component which calls useEffect to setValue

The first time the sandbox loads it shows:

![image](https://user-images.githubusercontent.com/63593302/132954379-6dd90e6e-83fe-4e3a-9e14-87fcdb5e125a.png)

If you make any change which triggers fast refresh then the parent will update to the correct state, for example comment out one of the console.log statements. As soon as fast refresh triggers the state will update correctly. If you just refresh the codesandbox app then the problem will come back

**Comment by tkolanko** [comment]
@bluebill1049 I also tried what you suggested of moving setValue to the parent component and that does work but it seems like the parent form component is going to be overly complex. Here's a codesandbox with the change https://codesandbox.io/s/react-hook-form-js-forked-kfbp5?file=/src/App.js

The challenge I have with this is that we have a complex form where the available selections/default values for inputs depend on what values have been set for previous inputs. Additionally in our case we need to make API calls to populate the data as inputs change. We were hoping to keep things isolated and watch changes to the form through useWatch

**Comment by bluebill1049** [comment]
at the moment this is by design just like what I described above (include pointed out in the source), you can consider submitting a feature request instead and we can consider to prioritize that if this is the majority problem that the community is facing.
