### ISSUE TITLE
[Bug]: Confusing behaviour change from v7.5.3 to v7.6.0

### ISSUE THREAD

**Issue by aardvarkk** [react-hook-form/react-hook-form#6521]
### Version Number

7.6.0

### Codesandbox/Expo snack

https://codesandbox.io/s/modest-lamarr-1cpl6?file=/src/App.tsx

### Steps to reproduce

1. Click the Submit button and notice `null` is output
2. Revert react-hook-form to version 7.5.3 and reload
3. Click the Submit button and notice the time string is outputted

This is a form where I'm trying to use a luxon DateTime object as a form entry. This worked in previous versions of react-hook-form. 

Although the code doesn't seem to complain in Codesandbox, I get the following TS errors in VS Code when I upgrade from v7.5.3 to v7.6.0:

```
Argument of type '(data: FormTypes) => void' is not assignable to parameter of type 'SubmitHandler<FormTypes>'.
  Types of parameters 'data' and 'data' are incompatible.
    Type '{ foo: { get: {}; readonly isValid: boolean; readonly invalidReason: string | null; readonly invalidExplanation: string | null; readonly locale: string; readonly numberingSystem: string; ... 65 more ...; toRelativeCalendar: {}; }; }' is not assignable to type 'FormTypes'.
      The types of 'foo.get' are incompatible between these types.
        Type '{}' is not assignable to type '(unit: keyof DateTime) => number'.
          Type '{}' provides no match for the signature '(unit: keyof DateTime): number'.
```

It seems like somehow in v7.5.3 the form values (or just default values?) were actual objects, whereas in v7.6.0 they seem to be some kind of shallow copy thing that doesn't bring along the relevant nested functions.

### Expected behaviour

The time string should be outputted in the latest version

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
expected behavior: https://github.com/react-hook-form/react-hook-form/releases?after=v7.6.4

The reason is due to input is missing from default values. 

## Solution

- register an input so react hook form doesn't register that missing input on your behalf
- use `shouldUnregister: true` mode, so only registered input gets included as the submission result
