### ISSUE TITLE
[Bug]: TypeScript errors type incorrect if value is an Object

### ISSUE THREAD

**Issue by osdiab** [react-hook-form/react-hook-form#6523]
### Version Number

7.6.0

### Codesandbox/Expo snack

https://codesandbox.io/s/blue-sea-fkyiq?file=/src/App.tsx:198-216

### Steps to reproduce

Make a form whose type includes a value of type `Big`, see that the errors field types it as a `DeepMap<Big, FieldError>` and that you end up with the error object having a bunch of fields it shouldn't have. 

I ended up in this situation using a `zod` resolver with a `transform` to convert string number input into a `Big`

### Expected behaviour

Since it's a leaf it should have a value of `FieldError`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
As far as I know, we don't support custom Interface as above, @kotarella1110 is there any workaround for this usage?

**Comment by kotarella1110** [comment]
I will try to come up with a solution for this.

**Comment by Meemaw** [comment]
I think we're experiencing an issue related to this. For example if we want to use `Set<string>` as a type in our `FormData` this doesn't work in latest versions.

Note that that used to work `v7.12.2`.

**Comment by kotarella1110** [comment]
To support the custom Interface, I have built [`NestedValue`](https://react-hook-form.com/ts#NestedValue) type.
However, the `NestedValue` type does not work well with schemas such as `zod`...

My suggestion is to use ambient modules to allow the user to overload the `NestedValue`.

The user should be able to overload as follows:

```ts
// global.d.ts
import "react-hook-form";
import Big from "big.js";

declare module "react-hook-form" {
  export interface NestedValue extends Big {}
}
```

Perhaps this fix will allow users to overload the custom interface themselves.
This is a breaking change.

**Comment by aardvarkk** [comment]
I believe I may be experiencing the same issue in an upgrade from v7.14.2 to v7.15.1. I get the following TS errors on my formSubmit function when I try to pass it to `handleSubmit`:

```
Argument of type '(data: FormTypes) => void' is not assignable to parameter of type 'SubmitHandler<FormTypes>'.
  Types of parameters 'data' and 'data' are incompatible.
    Type '{ foo: { get: {}; readonly isValid: boolean; readonly invalidReason: string | null; readonly invalidExplanation: string | null; readonly locale: string; readonly numberingSystem: string; ... 65 more ...; toRelativeCalendar: {}; }; }' is not assignable to type 'FormTypes'.
      The types of 'foo.get' are incompatible between these types.
        Type '{}' is not assignable to type '(unit: keyof DateTime) => number'.
          Type '{}' provides no match for the signature '(unit: keyof DateTime): number'.
```

In this case, I'm trying to use a luxon `DateTime` object in the form.

**Comment by bluebill1049** [comment]
@aardvarkk can you share a codesandbox as this is probably not related to this issue?

**Comment by aardvarkk** [comment]
@bluebill1049 Sure.

Note that Codesandbox doesn't show any problem with this, but VS Code does. They seem to be using the exact same version of TS (latest -- 4.4.3), so I'm not sure what's going on. But it looks like when you're using a type with a function in it, the nested values (the functions) appear like empty objects rather than functions.

Codesandbox: https://codesandbox.io/s/condescending-tdd-81lgj?file=/src/App.tsx

Here's a screenshot from VS Code demonstrating the problem (with the exact same code):

![image](https://user-images.githubusercontent.com/1251092/133469847-68c4c3e6-ec2d-4db6-a7f2-7a2c151571da.png)

Perhaps this is a separate issue, but the name of this one matched the problem I'm having: TS errors about incorrect types when the value is an object.

NOTE: As I mentioned above, **downgrading to react-hook-form@7.14.2 fixes this issue.**

**Comment by kuzkokov** [comment]
I also faced the same problem @aardvarkk did. Again, not sure if it has something to do with this very issue, but here we are.

As far as I understand, the problem is in this type:
`export declare type UnpackNestedValue<T> = T extends NestedValue<infer U> ? U : T extends Date | FileList | File ? T : T extends object ? {
    [K in keyof T]: UnpackNestedValue<T[K]>;
} : T;`

and specifically in this part:
`T extends object ? {
    [K in keyof T]: UnpackNestedValue<T[K]>;
} : T;`

Since function type extends object, it's being unpacked into `{}` as you can see in the screenshot of the error above.

**Comment by akafaneh** [comment]
> To support the custom Interface, I have built [`NestedValue`](https://react-hook-form.com/ts#NestedValue) type.
> However, the `NestedValue` type does not work well with schemas such as `zod`...
> 
> My suggestion is to use [ambient modules](https://www.typescriptlang.org/docs/handbook/modules.html#ambient-modules) to allow the user to [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) ​the `NestedValue`.
> 
> As follows:
> 
> ```ts
> // global.d.ts
> import "react-hook-form";
> import Big from "big.js";
> 
> type Value = Big | { custom: string };
> declare module "react-hook-form" {
>   interface NestedValue extends Value {}
> }
> ```
> 
> Perhaps this fix will allow users to overload the custom interface themselves.
> **This is a breaking change.**

For sure `yup` doesn't play well with `NestedValue` and the custom solution basically limit the type as it's not generic anymore.
For now i will loosely type it. But yeah i had no luck with making it work with `yup`

**Comment by kotarella1110** [comment]
> https://github.com/react-hook-form/react-hook-form/issues/6523#issuecomment-920160640

I will fix this

**Comment by JakeGinnivan** [comment]
I've got another related scenario where I can't assign default value

```
interface FormValues {
    dataType: DataTypes
}

export type DataTypes = BooleanDataType | NumberDataType | StringDataType | OptionsDataType

export interface BooleanDataType {
  kind: 'boolean'
  [k: string]: unknown
}
export interface NumberDataType {
  kind: 'number'
  [k: string]: unknown
}
export interface StringDataType {
  kind: 'string'
  [k: string]: unknown
}
export interface OptionsDataType {
  kind: 'options'
  options: string[]
  [k: string]: unknown
}
```

I think the quick fix is to add another condition to DeepPartial which only maps the object type if it's an object then fall back to unknown. I don't think you can test for unknown

```
export declare type DeepPartial<T> = T extends Date | FileList | File | NestedValue ? T : T extends object ? {
    [K in keyof T]?: DeepPartial<T[K]>;
} : unknown;
```

Out of interest what is the use case for the deep partial, wouldn't a top level partial be enough?

**Comment by aardvarkk** [comment]
> > [#6523 (comment)](https://github.com/react-hook-form/react-hook-form/issues/6523#issuecomment-918854255)
> > [#6523 (comment)](https://github.com/react-hook-form/react-hook-form/issues/6523#issuecomment-920160640)
> 
> I will fix this

@kotarella1110 If I'm reading your comment correctly, it seems like the code I pasted above should no longer be a problem in the latest version, but I'm still seeing it. Putting the following code into VS Code still gives me a TS error:

```
import React from "react";
import { useForm } from "react-hook-form";

type Foo = {
  bar: () => {};
};

type FormTypes = {
  foo: Foo;
};

function App() {
  const form = useForm<FormTypes>();
  function formSubmit(data: FormTypes) {}
  return <form onSubmit={form.handleSubmit(formSubmit)} />;
}

export default App;
```

**Comment by rafahuaman** [comment]
First, thank you for your work on this library!

I am getting a similar error with the following code on `v7.22.2`. Posting it here instead of  because it looks related to an error mentioned above.  The difference is that I am using generics.  

```
import React from "react";
import { useForm } from "react-hook-form";

type BaseFormProps<T> = {
  onSubmit: (data: T) => void;
};

function BaseForm<T>({ onSubmit }: BaseFormProps<T>) {
  const form = useForm<T>();
  function formSubmit(data: T) {
    onSubmit(data);
  }
  return <form onSubmit={form.handleSubmit(formSubmit)} />;
}
```

This yields the following TS errors on `formSubmit` when passing it to `handleSubmit`:

```
Argument of type '(data: T) => void' is not assignable to parameter of type 'SubmitHandler<T>'.
  Types of parameters 'data' and 'data' are incompatible.
    Type 'UnpackNestedValue<T>' is not assignable to type 'T'.
      'T' could be instantiated with an arbitrary type which could be unrelated to 'UnpackNestedValue<T>'
```

**Comment by uncvrd** [comment]
I'm experiencing the same problem as @aardvarkk when using a Luxon DateTime object, just upgraded to the latest but still have the same problem. Do you think we can reopen this issue?

**Comment by congqiao** [comment]
Same error on `7.27.1`

**Comment by aardvarkk** [comment]
@uncvrd @congqiao My solution for this was just to manually cast the types in the `onSubmit` handler. This lets me use the latest version, even though it'd be nice if I didn't have to cast. Here's an example:

```
type MyFormTypes = {...};

const myForm = useForm<MyFormTypes>(...);

function formSubmit(data: MyFormTypes) {
  ...
}

<form
  onSubmit={myForm.handleSubmit((formData) =>
    formSubmit(formData as MyFormTypes)
  )}
>
```

**Comment by DIOGO-MOTA** [comment]
changing tsconfig.json will solve

{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}

**Comment by julioflima** [comment]
> > > [#6523 (comment)](https://github.com/react-hook-form/react-hook-form/issues/6523#issuecomment-918854255)
> > > [#6523 (comment)](https://github.com/react-hook-form/react-hook-form/issues/6523#issuecomment-920160640)
> > 
> > 
> > I will fix this
> 
> @kotarella1110 If I'm reading your comment correctly, it seems like the code I pasted above should no longer be a problem in the latest version, but I'm still seeing it. Putting the following code into VS Code still gives me the same TS error as before:
> 
> ```
> import React from "react";
> import { useForm } from "react-hook-form";
> 
> type Foo = {
>   bar: () => {};
> };
> 
> type FormTypes = {
>   foo: Foo;
> };
> 
> function App() {
>   const form = useForm<FormTypes>();
>   function formSubmit(data: FormTypes) {}
>   return <form onSubmit={form.handleSubmit(formSubmit)} />;
> }
> 
> export default App;
> ```

Thanks a lot in my case I was using Arrow Function instead of Function. Is a pity that we should have to use a function instead. But I did as you and works.

```
  const handleSignIn = (data: TFormData) => {}

```
