### ISSUE TITLE
remove issue with useFieldArray async data

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#6528]
First of all, thanks a lot for the great library and all the work you have been doing maintaining it !!

I am trying to implement form edition with data fetched from a database.
I'm leveraging the useFieldArray hook to handle dynamic sections creation and edition.

I created a codesandbox to help you investigate
https://codesandbox.io/s/objective-haze-9vr3x?file=/src/App.js

(I don't know if I am doing something wrong but here are the steps to reproduce my issue)

1. Wait for the data to load (to simulate a fetch request, we simply used a setTimeout and populated the defaultValues with dummy data)
2. Remove the 2nd item of the array
3. Hit the submit button

The data coming into the submit function should normally be an array of one item.

I have been struggling with this issue for quite some time and I would greatly appreciate your help.

_Originally posted by @devmadou in https://github.com/react-hook-form/react-hook-form/discussions/6527_

**Comment by devmadou** [comment]
Thank you very much !
Now everything works fine

**Comment by bluebill1049** [comment]
you are weclome @devmadou

**Comment by pourya7** [comment]
@bluebill1049 Any plan to fix this issue for v6?

**Comment by bluebill1049** [comment]
@pourya7 what's the chance to move to v7? it's internal design has been improved over v6.

**Comment by pourya7** [comment]
@bluebill1049 Thanks for the quick response. As much as we'd love to use the latest version, we're using v6 on two separate large codebases where migrating to v7 would be costly for us.

Although we found a quick fix (for v6) and that is to use _**only**_ `Controller`s.

[This is a minimal version of your example using v6 (only native elements)](https://codesandbox.io/s/eager-benji-bdqx8?file=/src/App.js)
[This is an alternative solution for v6](https://codesandbox.io/s/romantic-rosalind-e2vww?file=/src/App.js)
