### ISSUE TITLE
[Bug]: Validation does not get triggered when using setValue

### ISSUE THREAD

**Issue by Arsikod** [react-hook-form/react-hook-form#6533]
### Version Number

7

### Codesandbox/Expo snack

https://codesandbox.io/s/bold-poincare-l9xe3?file=/src/App.js

### Steps to reproduce

1. Fill "count" and "price" inputs
2. "Sum" input will be filled automatically due to setValue() method. (multiplies count to price)
2. Click on 'Submit'
3. See validation errors. Last input validation error not triggered even thought they all represent one component with maxLength value = 5.
4. but validation works fine for "sum" input when I try to type something inside of the input. (without using setValue)

### Expected behaviour

third input - "sum" should show error message when clicked on submit if maxLangth is exceeded.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
- please provide an isolated example for the issue
- this is mostly due to setValue missing should validate config

https://react-hook-form.com/api/useform/setvalue

**Comment by Arsikod** [comment]
Hi Bill, thank you for your kind response.
Here is isolated example for the current issue, I added shouldValidate as well.
So when value is set with setValue, the validation is not being triggered.
https://codesandbox.io/s/bold-poincare-l9xe3?file=/src/number-input.js

**Comment by bluebill1049** [comment]
<img width="1111" alt="Screen Shot 2021-09-14 at 2 59 44 pm" src="https://user-images.githubusercontent.com/10513364/133197599-4e0a7dcf-62f9-4717-ada7-4c91801959ef.png">

maxLength is for string 👍 same as native HTML validation api
