### ISSUE TITLE
[Bug]: path.split is not a function on upgrade from 6.15.8 to 7.0.0-alpha.0 or later

### ISSUE THREAD

**Issue by rmouser** [react-hook-form/react-hook-form#6537]
### Version Number

7.0.0-alpha.0 or later

### Codesandbox/Expo snack

https://codesandbox.io/s/elegant-gwen-ovy21?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/elegant-gwen-ovy21?file=/src/App.tsx
2. Observe the crash with 7.0.0-alpha.0 (same on latest as of this writing)
3. Change react-hook-form to version to 6.15.8
4. Observe app running correctly

Let me know if you need anything else, this is my first bug submission, happy to help but not guru level.

Apologies about the codesandbox, I skinned down from huge app before I saw you had a template to start with.

### Expected behaviour

6.15.8 & 7.x.x work the same, or I missed something that is a breaking change between 6.x and 7.x.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
TypeError
path.split is not a function
get
https://ovy21.csb.app/node_modules/react-hook-form/dist/index.esm.js:105:31
eval
https://ovy21.csb.app/node_modules/react-hook-form/dist/index.esm.js:1009:57
App
/src/App.tsx:54:19
  51 |   name="lower_cost"
  52 |   id="yes4"
  53 |   value="Yes"
> 54 |   ref={register({ required: true })}
     |       ^
  55 |   onChange={handleInputChange}
  56 | />
  57 | <label htmlFor="yes4">Yes (you've found a real bug)</label>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please refer to the migration guide, from v6 and v7 has breaking changes.
https://react-hook-form.com/migrate-v6-to-v7

**Comment by rmouser** [comment]
Thank you, totally missed the migration guide.
