### ISSUE TITLE
[Bug] Invalid behaviour with insert and async action

### ISSUE THREAD

**Issue by revich2** [react-hook-form/react-hook-form#6541]
@bluebill1049 Hi, this bug actual again

I found commit with breaking changes - https://github.com/react-hook-form/react-hook-form/commit/dbf6c74b1094adbde7f30645f41d4d981c9cc25d

For comparing you can use this CSB - https://codesandbox.io/s/practical-boyd-tij3l
For version `7.13.0-next.4` it works fine, but `7.13.0-next.5` breaks this behaviour

_Originally posted by @revich2 in https://github.com/react-hook-form/react-hook-form/discussions/6039#discussioncomment-1315748_

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/commit/1af061ee9079077b666be4e9b85317d9f1c87a67

**Comment by bluebill1049** [comment]
fixed in the above commit.
