### ISSUE TITLE
[Bug]: isValid broken between 7.13.x => 7.14.x

### ISSUE THREAD

**Issue by bkniffler** [react-hook-form/react-hook-form#6542]
### Version Number

7.14.x

### Codesandbox/Expo snack

https://codesandbox.io/s/reverent-swanson-7bbh3?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/reverent-swanson-7bbh3?file=/src/App.tsx
2. Fill field, button is not getting enabled
3. Change hook version to 7.13.0
4. Fill field, button is getting enabled

### Expected behaviour

isValid should become true.

### What browsers are you seeing the problem on?

Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please refer to the doc:
<img width="1004" alt="Screen Shot 2021-09-14 at 9 03 18 pm" src="https://user-images.githubusercontent.com/10513364/133246362-f869beb9-daba-409b-a4b7-9eacaf29e744.png">
