### ISSUE TITLE
[Bug]: Nested getValues / defaultValues get mixed up / stalled between nested or dot notation

### ISSUE THREAD

**Issue by pandaiolo** [react-hook-form/react-hook-form#6543]
### Version Number

7.15.3

### Codesandbox/Expo snack

https://codesandbox.io/s/sweet-matsumoto-40271?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/sweet-matsumoto-40271?file=/src/App.js
2. Click on `DROP VALUES` button
3. Check the initial values in the console (without any interaction)
4. Modify the last name
5. Click on `DROP VALUES` button again
6. Check the new values in the console (after a nested field value changed)

### Expected (somehow) behaviour

Notes on the initial values dropped in point `2.`:

```js
{
  "name.first": "first",
  "name.last": "last",
  isDeveloper: true,
  email: "",
  name: {
    first: "first",
    last: "last"
  }
}
```

- The `defaultValues`, provided as dot notation, are correctly parsed and used in the relevant fields
- We get both the values in dot notation, and those in nested format. Not a big deal but it was a bit confusing at first. Is this expected? Even with a single version of the data, we can get what we want using `lodash.get` or similar. 
- It is inconsistent with the values got in the submit handler (no dot notation values)

### Unexpected behavior

The main difference that I consider a bug here, is in the second values drop from point `5.` above. Let's says we changed the last name from `last` to `pizza`:

*We get the following values:*

```js
{
  "name.first": "first",
  "name.last": "last", // WRONG
  isDeveloper: true,
  email: "",
  name: {
    first: "first",
    last: "pizza"
  }
}
```

*What I was expecting instead*:

```js
{
  "name.first": "first",
  "name.last": "pizza", // RIGHT
  isDeveloper: true,
  email: "",
  name: {
    first: "first",
    last: "pizza"
  }
}
```

Notes:
- I was actually expecting the dot notation only, but I'm was fine having both notations
- This is particularly annoying because even using `lodash.get` to get nested values does not work, because `lodash.get(values, "name.last")` will return `values["name.last"]` over `values.name.last` :D

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
dot notation is revered used that for both type check and nested object data. This is a design limitation with the current v7 design.

**Comment by pandaiolo** [comment]
@bluebill1049 sorry did not see your answer before

> dot notation is revered used that for both type check and nested object data

I do not understand what do you mean?

1. What is the limitation with v7 API?
2. Why do you think the wrong value in `getValues` should not be either fixed, or removed, as a fix for this bug?

**Comment by bluebill1049** [comment]
`<input {...register("name.first")} />` 

This `name` which you have provided above, dot nation will covert into array or object. 

```
test.0.test` will converted to `test[0].data
test.test.test` will converted to `test.test.test
```

**Comment by pandaiolo** [comment]
This is fine to me. But why the **value** in `getValues` is wrong?

**Comment by bluebill1049** [comment]
because there are a lot of developers request fo `defaultValues` to be preserved: https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/createFormControl.ts#L809 we had a shallow merged there.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/useform/getvalues

<img width="961" alt="Screen Shot 2021-09-16 at 8 15 18 pm" src="https://user-images.githubusercontent.com/10513364/133594865-afee42a4-e9b3-4d66-a287-368ec11581ed.png">

> It will return defaultValues from useForm before the initial render.

> After the initial render, form values will be shallowly merged with defaultValues.

personally i prefer the flat data structure with v3, but gotta follow what the community wants...

**Comment by pandaiolo** [comment]
All right but isn't this still a bug? The expected **value** in my example above should clearly be `pizza` and instead what I get is `last`. `getValues` is supposed to return _current_ values, not _default_ values, right?

I mean:
```js
getValues('name.last')
// -> 'pizza'
getValues()['name.last']
// -> 'last'

How any developper would want that behavior? 🤷‍♂️

**Comment by pandaiolo** [comment]
I updated my code sandbox with more explicit logging when you click on the 'DROP VALUES' button. Try changing the last name and see what happens. Now if you say this is by design, well I don't know what to say 😃

**Comment by bluebill1049** [comment]
```tsx
console.log("getValues('name.last')", getValues("name.last")); // this is your defaultValue
console.log("getValues()['name.last']", getValues()["name.last"]); // this is what in the form
```

just treat your input name with dot as an object, we no longer do flat with any dot notation.

**Comment by bluebill1049** [comment]
use this `defaultValues` instead:

```
defaultValues: {
      name: {
        first: 'test',
        last: 'last'
      },
      isDeveloper: true,
      email: ""
    }
    ```

**Comment by pandaiolo** [comment]
I am going to try that, thank you for the suggestion.

However, If this is how it is supposed to be used, would it make sense to not allow dot notation in the default values?

To me, either:
- Both notations are accepted in the default values, and work as expected in `getValues` (returning _current_ value)
- OR, It is **not** accepted in default values so it will not lead to unexpected behavior in `getValue`

It makes no sense at all that `form.getValues('name.last')` and `form.getValues()['name.last']` return different values. The code intention feels exactly the same when you read it: "Please give me the current value of last name in the form".
