### ISSUE TITLE
[Bug]: pop on watched array value modified form values, since 7.14.0

### ISSUE THREAD

**Issue by michalbundyra** [react-hook-form/react-hook-form#6546]
### Version Number

Since 7.14.0

### Codesandbox/Expo snack

https://codesandbox.io/s/throbbing-cdn-s7r5h?file=/src/App.tsx

### Steps to reproduce

1. Click "Append Name" button.
2. input with "Hello 1" will be added.
3. click the button again
4. the input value will be updated to "Hello 11"

### Expected behaviour

Expected new input to be added with "Hello 11" value.

The problem is present since version 7.14.0 - might be related to https://github.com/react-hook-form/react-hook-form/pull/6336.

All works as expected on version 7.13.0.

The problem is that we watch the array field and call `pop` on the watched field. It somehow modifies array fields in the form and field is replaced, not a new added as it was before (in 7.13.0).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we have a single value store, I would suggest not mutate with the watch returned value, this could lead to unexpected behavior like above.

**Comment by michalbundyra** [comment]
@bluebill1049 

> we have a single value store ...

this is just simplified example, case in our application is much more complex.
I just showed the issue, something what was not an issue before. 

And it is very weird behaviour that modification of watched value changes internal state of the form....

**Comment by bluebill1049** [comment]
This is the same as `useState` we don't clone the return result of `watch`, if you want to mutate the result, please deepClone at your app level.
