### ISSUE TITLE
[Bug]: watch() misses last value after reset()

### ISSUE THREAD

**Issue by adarnon** [react-hook-form/react-hook-form#6548]
### Version Number

7.15.3

### Codesandbox/Expo snack

https://codesandbox.io/s/hardcore-kepler-ihou8?file=/src/App.tsx

### Steps to reproduce

1. Visit codesandbox
2. See that "val: true" is never printed to console

### Expected behaviour

After the `useEffect()`, the value returned from `watch()` should be `true`.

It only happens when `shouldUnregister: true`

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is actually expected behavior. somewhat related to ##6482

initially, I was against such a suggestion in #6482, but after careful consideration, it make sense to me. 

the difference between shouldUnregister: `true` and `false`, when set shouldUnregister true, defaultValues is only there to populate your input and it's not the form values, so make sense when inputs get unmounted and the result will be removed. So the source of truth lives in your inputs. 

opposite `shouldUnregister: false` behavior the opposite, which accepts defaultValues as the form values and removes inputs will take no effect on the form values.

so `reset` in shouldUnregister: true only will update defaultValues not affect the formValues which lead to watch not updated its value until the user interacts with the inptus.

hope the above makes sense, I will reinforce in the doc to reflect above.

**Comment by adarnon** [comment]
@bluebill1049 The input does not get unmounted. It is always mounted, and `reset()` sets its value - you can see the checkbox is checked when the page loads. But `watch()` returns a wrong false.

**Comment by bluebill1049** [comment]
yes, but reset() is going to be 1 render ahead for the `render`

```
- mount input
- reset()
- watch()  // this is behind of the actual render
- render
```

**Comment by adarnon** [comment]
But in my example, the checkbox is mounted with default value `false` and the reset then changes the value to `true` - so the `reset()` doesn't only affect the default values, it also changes the form values.

I'm in the process of migrating from v6 to v7 and this seems like the biggest blocker. We've relied on calling `reset(...)` in order to batch set all form values when they are received from a fetch, such as the backend. This only works in `shouldUnregister: true` mode because when `shouldUnregister: false`, setting values for unregistered inputs registers then and makes the value hang around.

**Comment by bluebill1049** [comment]
> But in my example, the checkbox is mounted with default value false and the reset then changes the value to true - so the reset() doesn't only affect the default values, it also changes the form values.

`reset` with `shouldUnregister: true` only update the defaultValues **not** the formValues. It's not the same as setState, react hook form's inputs are uncontrolled by default.

**Comment by bluebill1049** [comment]
ok, I think I may have a solution: 

1. `mount`
2. `reset()`
3. `watch()`
4. `render`
5. `render` (trigger an extra render)

**Comment by bluebill1049** [comment]
My statement above remains the same, `defaultValues` not equal `formValues` in react hook form.

**Comment by adarnon** [comment]
I understand if that's the behavior you want `reset()` to have - but then currently there's a bug that calling `reset()` did change the checkbox' value to `true` even though it shouldn't have.

By the way, in version 7.13 the `watch()` does receive the proper value

**Comment by bluebill1049** [comment]
> By the way, in version 7.13 the watch() does receive the proper value

yes, it's been reported as a bug,  i have referenced above: https://github.com/react-hook-form/react-hook-form/issues/6482

**Comment by adarnon** [comment]
I understand the change you made in #6482. Just to make sure there isn't a misunderstanding, after loading the codesandbox in my bug report, clicking on submit will log `{ val: true}` (because the checkbox is checked), while the value of `watch('val')` in the latest render is `val: false`. This is a mismatch that in any case should be considered a bug

**Comment by bluebill1049** [comment]
please read my comments above: 

the current behavior: https://github.com/react-hook-form/react-hook-form/issues/6548#issuecomment-919635389
the proposed improvement: https://github.com/react-hook-form/react-hook-form/issues/6548#issuecomment-919638868 

I think I have made it quite clear.
