### ISSUE TITLE
cannot write to Mui TextField if maxLength with message defiend at register

### ISSUE THREAD

**Issue by ebadta81** [react-hook-form/react-hook-form#655]
**Describe the bug**
Input box doesn't get any input if I define maxLength: { value: 256, message: "message" }

**To Reproduce**
I created a codesandbox example for this.

If you just give maxLength: 256, then everything ok.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-bug-j0fiz

**Expected behavior**
I can write

**Comment by bluebill1049** [comment]
wow this one is so strange...
