### ISSUE TITLE
Add all possible types in Form Builder

### ISSUE THREAD

**Issue by pom421** [react-hook-form/react-hook-form#6552]
**Is your feature request related to a problem? Please describe.**
I used to use Form Builder but some input types are missing.
For example, we don't have access to date (only datetime, which is separate).

Only these ones are present : 
- text
- select
- checkbox
- radio
- number
- textarea
- email
- range
- search
- tel
- url
- time
- datetime
- datetime-local
- week
- month
- validate

**Describe the solution you'd like**
Taking reference from React.HTMLInputTypeAttribute type definition, it should be these ones: 

- button
- checkbox
- color
- date
- datetime-local
- email
- file
- hidden
- image
- month
- number
- password
- radio
- range
- reset
- search
- submit
- tel
- text
- time
- url
- week

 I don't see any bad consequences of adding these type values in the list. Do you? 🤔

**Comment by bluebill1049** [comment]
I am building something at the moment will keep this current form builder as simple as right now.

**Comment by devmrfitz** [comment]
@bluebill1049 
Is there a way we can provide the option to upload images?
