### ISSUE TITLE
[Bug]: Default values are not being set to useFieldArray if shouldUnregister: true

### ISSUE THREAD

**Issue by felon91** [react-hook-form/react-hook-form#6556]
### Version Number

7.15.3

### Codesandbox/Expo snack

https://codesandbox.io/s/tender-darkness-wcl9o

### Steps to reproduce

1. Go to codesandbox
2. Click on getValues
3. See that in console there are no values in form

### Expected behaviour

Values to be in the form

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
you are missing all the inputs. `shouldUnregsiter: true` values are based on all the inputs, if you want to keep defaultValues as formValues use `shouldUnregister: false`. I will reinforce that in the doc.
