### ISSUE TITLE
Any way to not include empty strings for blank inputs?

### ISSUE THREAD

**Issue by captrespect** [react-hook-form/react-hook-form#656]
**Describe the question?**
When I we have a form with optional values, the submit data object has empty string set for values that are not set?

For example for a user with an optional phone number, I'd like the data object to be: 
{ username: 'theusername' } when no phone is filled out instead of { username: 'theusername', phone: '''}

The api i'm using will validate empty strings as submitted values. Here it will error saying phone number must have a length of 10, even though it's optional.

**Comment by bluebill1049** [comment]
Can you write a transform function to filter the inputs during submit?

**Comment by captrespect** [comment]
Yeah that's what I ended up doing, just making sure I didn't miss some other setting.

`function removeEmptyFields(data) {
  Object.keys(data).forEach(key => {
    if (data[key] === '' || data[key] == null) {
      delete data[key];
    }
  });
}

const onSubmit = data => {    
    removeEmptyFields(data);
....
}
`

**Comment by risardi123** [comment]
Thanks for the answer it solved my problem too, but for the future, is it include in react-hook-form @bluebill1049 ?

**Comment by bluebill1049** [comment]
Don't think so, we are trying to follow HTML standard, if you want to stripe empty, i would recommend you look at this: https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-furtc

**Comment by zeckdude** [comment]
If you don't want to mutate your values object and you want a nifty one-liner, here you go:

```js
import { pickBy } from 'lodash';

// Strip out all empty strings
const sanitizedValues = pickBy(values, value => value.length > 0);
```

**Comment by risardi123** [comment]
Oh i see, thanks for the reply and answer 
@bluebill1049 , @zeckdude

**Comment by davea38** [comment]
I appreciate this is a closed issue and the answers above, but I was wondering if there is a way to centralise this behaviour. I've got a project with several forms and would like all of them to put null in the database rather than an empty string.

I can create a wrapper hook around useForm > handleSubmit that performs the deletion of properties with '', but feel like that's a bit of a hack.

Is there any way you could support this via a property passed to the useForm hook or similar?

**Comment by Saulius-HALO** [comment]
I have the same issue and this is beyond strange. Why would it convert an explicitly set value from null to empty string even through `reset`..

**Comment by omar-dulaimi** [comment]
I would also appreciate a way to submit only the touched fields values, any fields that weren't touched should not be part of the submission. Is that possible?

**Comment by Fralalala** [comment]
Is there a way for it to be handled before submission? If it can be checked before a form submit, the "require" pop ups of an input can be utilized instead of handling it manually.

**Comment by sshquack** [comment]
If you have nested objects and want to remove `falsy` values on a per-field basis, something like this might help:

```typescript
import _ from "lodash";

export const setEmptyOrStr = (v: unknown) => {
  if (_.isString(v) && _.isEmpty(v)) return undefined;
  else return v;
};
```

```typescript
{/* optional input */}
<input
  type={"text"}
  {...register(`description`, { required: false, setValueAs: setEmptyOrStr })}
/>
```

`setValueAs` provides granular input setters.

[See docs here](https://react-hook-form.com/api/useform/register)

Thanks @bluebill1049 for this beautiful library 🙏

**Comment by norikt** [comment]
There is an example of submit only Dirty Fields.
https://github.com/react-hook-form/react-hook-form/tree/master/examples
