### ISSUE TITLE
[Bug]: setValue doesn't trigger formState after reset()

### ISSUE THREAD

**Issue by guvenakcoban** [react-hook-form/react-hook-form#6581]
### Version Number

7.15.3

### Codesandbox/Expo snack

https://codesandbox.io/s/crimson-rgb-rfz1p

### Steps to reproduce

1. Go to sandbox
2. wait 3 seconds to run reset
3. wait 2 seconds more to run setValue
4. isDirty should be true but nothing happening

### Expected behaviour

isDirty should be true after setValue run

It works as expected on 7.4.1

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is due to after `reset`, that registered input is not get registered again. I will see if I can improve this behavior and fix it accordingly.

**Comment by bluebill1049** [comment]
did a few attempts to make it work but failed with some of the units which prevent other bugs to raised. 

here is easy work around: 

https://codesandbox.io/s/suspicious-paper-ubzxo

the idea is an input should get registered before `setValue`, I did attempt in the PR above to include pre-register function but it lead to other unwanted issues. so called `register` solve the problem, and it's quite cheap to call `register` as well (if performance is a concern.

**Comment by bluebill1049** [comment]
hmmm may found a solution...
