### ISSUE TITLE
[Bug]: update api of useFieldsArray is not working correctly

### ISSUE THREAD

**Issue by sp0033212000** [react-hook-form/react-hook-form#6585]
### Version Number

7.15.3

### Codesandbox/Expo snack

https://codesandbox.io/s/snowy-tdd-90o4e?file=/src/App.tsx

### Steps to reproduce

1. click plus button
2. click pencil button
3. key in something at input field
4. click times button
5. the input value should be reset, but it doesn’t

### Expected behaviour

the field should be reset to previous value

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please create a simple codesandbox instead of the entire project, it's hard for me or any maintainer to debug and find the root cause.

**Comment by bluebill1049** [comment]
here is a good template to follow: https://codesandbox.io/s/react-hook-form-usefieldarray-ssugn

**Comment by sp0033212000** [comment]
Hi @bluebill1049 
Thanks for your replied.
The template was too simply for my situation..., but the behavior that what I expected is how to reset the value of item of certain index by cached value.

**Comment by bluebill1049** [comment]
if it's an issue with the `update` then it can be reproduced, not without other side effects and dependencies.

**Comment by sp0033212000** [comment]
ok, I try to reproduced this problem, then you could see the issue by this sandbox
[https://codesandbox.io/s/react-hook-form-usefieldarray-forked-ctcvj?file=/src/index.js](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-ctcvj?file=/src/index.js)

**Comment by sp0033212000** [comment]
OK, I found the problem that I can't send the data that include id key to be updated.
so that I have to exclude the id key out of data.

**Comment by bluebill1049** [comment]
make sense, thanks for the investigation. yes, the API is not allowed to overwrite those `id` or keyName, they are used for rendering for all the inputs, you can update individual fields tho. such as

```
update(index, { lastName: "" });
```
