### ISSUE TITLE
validationSchema when input field doesnt exist

### ISSUE THREAD

**Issue by mikaelkristiansson** [react-hook-form/react-hook-form#659]
When I have a yup schema where a field is required and the field does not exist in the form it will not submit the form since it contains an error.
Let's say I have conditions for a field to only render when another value is set, and the new field should be required, but the first field is not required. Then I have to set conditions both in the schema and the code rendering the fields.
I think formik for example only validates the fields existing and doesnt depend on every schema rule.
Is there something i've missed or is it suppose to be this way?

**To Reproduce**
1. fill all fields
2. submit the form
3. form wont be submitted since there is an error, but no field for this error

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-validationschema-gh3ym

**Comment by bluebill1049** [comment]
hey, @mikaelkristiansson thanks for your issue report. at the moment we are validation form data against yup schema. I think it makes sense to omit out when data is not there.

**Comment by bluebill1049** [comment]
actually I believe you can write dependency schema as well right? would it make more sense to sort it out at the schema level?

**Comment by bluebill1049** [comment]
example in here: https://github.com/jquense/yup/issues/79

**Comment by bluebill1049** [comment]
any thoughts guys @JeromeDeLeon  @adhrinae @kotarella1110 ?

**Comment by mikaelkristiansson** [comment]
> example in here: [jquense/yup#79](https://github.com/jquense/yup/issues/79)

@bluebill1049 yeah that was why I asked, because right now I can get around it by setting conditions in both the render and the schema:
https://codesandbox.io/s/react-hook-form-validationschema-ow4qg

but I asked because I might missed something out.

**Comment by JeromeDeLeon** [comment]
@bluebill1049 was right. I had similar scenario where I had this `field` in the schema that was not visible in the UI but was need to identify if my other field was going to be required or not using `is-then-otherwise` of `yup`.

```js
object({
  shape: string()
    .ensure()
    .required("Shape is required"),
  isAreaDisabled: boolean(),
  area: string().when("isAreaDisabled", {
    is: false,
    then: string().required("Area is required"),
    otherwise: string()
      .default("0")
      .notRequired()
  })
});
```

`isAreaDisabled` is triggered using `setValue` of `react-hook-form` and visible on the screen of user. I changed it based on the `shape` provided by user.

**Comment by bluebill1049** [comment]
We can easily omit out removed inputs, but I feel like if we are using schema validation, it's better to leave the validation (source of truth) at the schema level. IMOH Less "magic" from the lib itself is better and keep this lib light as well.

**Comment by kotarella1110** [comment]
> We can easily omit out removed inputs, but I feel like if we are using schema validation, it's better to leave the validation (source of truth) at the schema level.

I think so too.

**Comment by mikaelkristiansson** [comment]
> We can easily omit out removed inputs, but I feel like if we are using schema validation, it's better to leave the validation (source of truth) at the schema level. IMOH Less "magic" from the lib itself is preferred and keep this little lib light as well.

totally agree
