### ISSUE TITLE
[Bug]: Cannot read property '_f' of undefined

### ISSUE THREAD

**Issue by exneval** [react-hook-form/react-hook-form#6590]
### Version Number

7.15.4

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-5m8jg?file=/src/App.tsx

### Steps to reproduce

1. Import the package
2. Call `setValue` in useEffect with `option` `shouldValidate: true`
3. Try do some refresh page
4. Error happened

### Expected behaviour

No error happened like previous version 7.15.3

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
TypeError
Cannot read property '_f' of undefined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for reporting the issue and improved with a PR as well.
