### ISSUE TITLE
[Bug]: Form `reset` and `defaultValues` destroy objects

### ISSUE THREAD

**Issue by gerrod** [react-hook-form/react-hook-form#6592]
### Version Number

7.15.4

### Codesandbox/Expo snack

https://codesandbox.io/s/inspiring-mirzakhani-de7wb?file=/src/App.tsx

### Steps to reproduce

_(Note - the example uses `7.15.3` because `7.15.4` isn't available on CodeSandbox yet...)_

1. Load the form. Note that the dete field shows a formatted date object.
2. Click the "reset" button. The date field now shows "Invalid DateTime".
3. Notice also that the code says that the `onSubmit` handler is invalid as the types for `FormValues` aren't compatible.

If using `7.15.4`, I think the initial render would also show that the date is invalid.

I'm pretty sure the problem is due to [createFormControls](https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/createFormControl.ts) using `cloneObject` to clone the values that are passed as defaults / reset - with the luxon `DateTime` instance this results in an invalid `DateTime` object.

The incompatibility between `FormValues` is again because one of them has a `DateTime` instance, and one has a clone of a `DateTime` instance.

The only work-around I've come up with is to reduce the `DateTime` instance to a primitive (either a `Date` or millis since epoch) but this is suboptimal as it means lots of converting to/from a `DateTime` instance (which is what the date picker control (MUI) works with).

One potential work-around could be to allow suplementing the `cloneObjects` method in `react-hook-form` when you create the form instance; for example, maybe you could provide an array of methods to use for testing an object when cloning - just as a throwaway example, if we provided a map of key/value pairs where the key tests if that clone method should be used, and the value was the function that actually did the cloning; something like:
```tsx
const form = useForm({
    defaultValues: { ... },
    cylons: [
        [obj => obj instanceof DateTime, (obj: DateTime) => DateTime.fromObject(obj.toObject())],
    ],
});
```

### Expected behaviour

1. The form does not create invalid objects and maintains the `DateTime` instance
2. The typings on the form recognize the `onSubmit` handler as valid

### What browsers are you seeing the problem on?

Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
A custom object is going to make things difficult, the reason which we are doing the clone object is to avoid mutating the original object. I probably going with mark as a design limitation on this or have a config to bypass the clone during reset.

**Comment by bluebill1049** [comment]
as a workaround is what you described above instead passes the custom object but native primitive data.

**Comment by nigel-dewar** [comment]
I tried playing around a little and here is a fork, https://codesandbox.io/s/agitated-maxwell-osq3y?file=/src/App.tsx  

It does seem strange that the Date will not reset.

**Comment by gerrod** [comment]
@bluebill1049 - would it be an option to pass an entirely new `cloneObject` method as an option to `useForm`?

**Comment by bluebill1049** [comment]
> I tried playing around a little and here is a fork of Gerrods, https://codesandbox.io/s/agitated-maxwell-osq3y?file=/src/App.tsx
> 
> It does seem strange that the Date will not reset.

It's not a standard `DateTime` object.

**Comment by bluebill1049** [comment]
> @bluebill1049 - would it be an option to pass an entirely new `cloneObject` method as an option to `useForm`?
> 
> I'm happy to submit this as a feature request instead if that's viable.

Thanks, @gerrod for the issue report and potential pride a PR for the fix, maybe start with a feature request first and we can seek a better solution for this. 

 I think we have the following options:

- provide a clone option at `useForm` level as you suggested 
- skip the clone at `reset` and have a config option

**Comment by gerrod** [comment]
OK thanks @bluebill1049

**Comment by pogo19** [comment]
Just my 2 cents.

I have the same problem with Blob as I have a media input component that can both play and record audio. As a workaround I converted the blob to Int8Array

...but this way I have to load all the data before displaying the form. With Blob it load asynchronously later.

**Comment by gerrod** [comment]
Sorry it took so long - I finally got around to adding the feature request for consideration 👆. Thanks!
