### ISSUE TITLE
[Bug]: maximum call stack size exceeded

### ISSUE THREAD

**Issue by mlecoq** [react-hook-form/react-hook-form#6593]
### Version Number

7.15.4

### Codesandbox/Expo snack

todo

### Steps to reproduce

Display form with initial values

### Expected behaviour

The form is displayed

Instead I have an error  ERROR  RangeError: Maximum call stack size exceeded

I know that it is related to react-hook-form : with 7.15.3 all works fine but with 7.15.4 I have the error

I didn't manage to identify the direct cause but I use the same form for creation and update: it crashed on update form but not on create one

### What browsers are you seeing the problem on?

React Native (Android)

### Relevant log output

```shell
ERROR  RangeError: Maximum call stack size exceeded
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by mlecoq** [comment]
Ok I will make a small repro (my use case is a big form so it's hard to identify the issue)

**Comment by mlecoq** [comment]
Sentry gives me this line as the cause of the infinite loop 

```{snip} });var t=e(require("react")),r=e=>"checkbox"===e.type,s=e=>e instanceof Date,a=e=>null==e;const n=e=>"object"==typeof e;var i=e=>!a(e)&&!Arr {snip}```

**Comment by mlecoq** [comment]
I have found the cause of the issue, I had a complex object in defaultValues

```
useForm({defaultValues}) 
```

generated an infinite loop when defaultValues contained it

**Comment by bluebill1049** [comment]
Provide a codesandbox.

**Comment by mlecoq** [comment]
Ok

**Comment by mlecoq** [comment]
@bluebill1049  I have created a very small example (didn't manage to make it work on codesandbox unfortunately) 

https://github.com/mlecoq/react-hook-form-infinite-loop

To reproduce you have just to create a post, then click on it. UpdatePost component is not finished and defaultValues are intentionally incorrect to reproduce the infinite loop 

 This issue has appeared with 7.15.4

**Comment by bluebill1049** [comment]
this file? https://github.com/mlecoq/react-hook-form-infinite-loop/blob/main/src/CreatePost.tsx

**Comment by bluebill1049** [comment]
have you try the latest?

**Comment by mlecoq** [comment]
@bluebill1049 in fact it is this one https://github.com/mlecoq/react-hook-form-infinite-loop/blob/eb3a2c5aefc92c7e996fb7651042748ef7d52519/src/UpdatePost.tsx

The infinite loop is provoked by Post object in default values

**Comment by mlecoq** [comment]
The loop is caused by cloneObject 

```
cloneObject
src/utils/cloneObject.ts:19
  16 |       copy = data;
  17 |       break;
  18 |     }
> 19 |     copy[key] = cloneObject(data[key]);
     | ^  20 |   }
  21 | } else {
  22 |   return data;
```

**Comment by bluebill1049** [comment]
we don't support Class at the moment for defaultValues, the feature request would resolve your issue while you will need to provide your own clone function: https://github.com/react-hook-form/react-hook-form/issues/7279
