### ISSUE TITLE
[Bug]: Radio input has changed value after second submit action

### ISSUE THREAD

**Issue by rootkowsky** [react-hook-form/react-hook-form#6601]
### Version Number

7.15.3

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-renders-6mere

### Steps to reproduce

1. Click on 'radio-2' input
2. Click on 'radio-1' input
3. Click on 'Send' button
4. See log from console (value is OK)
5. Click on 'Send' button again
4. See log from console (value is incorrect)

### Expected behaviour

Radio input should persist current value

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is not an issue related to the Controller, please find the related issue here: https://github.com/react-hook-form/react-hook-form/issues/6579
