### ISSUE TITLE
[Bug]: `onBlur` validation does not work with `useFormContext`

### ISSUE THREAD

**Issue by vicasas** [react-hook-form/react-hook-form#6606]
### Version Number

7.15.4

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-with-ui-library-forked-n996k?file=/src/index.js

### Steps to reproduce

1. Go to codesandbox
2. Make onBlur in the First Name text field
3. The validation will not work, there are no errors.

### Expected behaviour

It should work the same as the useForm hook does since its API is the same as the useFormContext according to the documentation.

What is expected is that it validates and generates the corresponding error object.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please refer to the doc, there is no config at `useFormContext`, this should only applied to `useForm`.

**Comment by vicasas** [comment]
The documentation indicates that it accepts all `useForm` methods

![image](https://user-images.githubusercontent.com/57921784/134341499-8d33eae7-0fb5-4ee1-9cee-cc02a7c3f13d.png)

**Comment by bluebill1049** [comment]
I will add a note on that to stop the confusion.
