### ISSUE TITLE
[Bug]: `setValue` does not set dirty field

### ISSUE THREAD

**Issue by pandaiolo** [react-hook-form/react-hook-form#6608]
### Version Number

7.15.3

### Codesandbox/Expo snack

https://codesandbox.io/s/sleepy-browser-09rgs?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/sleepy-browser-09rgs?file=/src/App.js
2. Click on 'SET TEST INPUT VALUE AND DIRTY'
3. Value is set but form is not dirty

### Expected behaviour

After clicking on the button, form should be dirty

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please refer to the doc for the options name:
https://react-hook-form.com/api/useform/setvalue

it should be `shouldDirty`

<img width="899" alt="Screen Shot 2021-09-22 at 9 21 19 am" src="https://user-images.githubusercontent.com/10513364/134260254-edaa309b-e976-4374-9981-d1e937119301.png">

**Comment by pandaiolo** [comment]
@bluebill1049 :face_palm: thanks! (and sorry for the waste of time...) I _do_ have an issue in my app and I did use `shouldDirty`, though... I just don't know what I'm doin wrong now. I will try to investigate more, there must be something that is different from the codesandbox

**Comment by bluebill1049** [comment]
Nah mate, thanks for the issue preparation (really good quality as usual). It really make my life a lot easier while maintaining the lib for everyone.
