### ISSUE TITLE
[Bug]: Appending field array item does not reflect the nested field array

### ISSUE THREAD

**Issue by repl-ullas-ml** [react-hook-form/react-hook-form#6609]
### Version Number

7.15.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-nested-usefieldarray-forked-x6uf0

### Steps to reproduce

1. Click on `Add Order`
2. Notice on `Add Order`, for a field array `orders` and order was added  ``` { title: "birds", items: [{ title: "sparrow" }] }``` 
3. An attribute of `order`  ie `items` is again a field array
3. Even though `items` with `sparrow` is added, it does not reflect on the fields

### Expected behaviour

Adding the order with `items` should reflect on the fields

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`<button type="button" onClick={() => append({})}>`

why the append function is an empty object? it's required to have a payload for what you want to append.
