### ISSUE TITLE
[Bug]: After changes to DeepPartial in PR #6451, arrays passed through DeepPartial can have undefined elements

### ISSUE THREAD

**Issue by jakpaw** [react-hook-form/react-hook-form#6615]
### Version Number

7.15.4

### Codesandbox/Expo snack

https://codesandbox.io/s/cocky-waterfall-4lng4?file=/src/App.tsx

### Steps to reproduce

Arrays passed through DeepPartial can now have undefined elements.
Most probable cause is the change introduced here:
https://github.com/react-hook-form/react-hook-form/pull/6451/files#diff-439a5e6647cc7b7366cf58c46c608bfc41ae8bc760485ee489e8ee8ee9eb5b18R21

### Expected behaviour

Arrays passed through DeepPartial shouldn't be allowed to have undefined elements, like it was in previous versions.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
this is related: https://github.com/react-hook-form/react-hook-form/issues/6505
