### ISSUE TITLE
[Bug]: Array field's fieldState property has no "message" property

### ISSUE THREAD

**Issue by DoronTorangy** [react-hook-form/react-hook-form#6618]
### Version Number

7.15.3

### Codesandbox/Expo snack

https://codesandbox.io/s/quirky-bird-mgri2?file=/src/App.tsx

### Steps to reproduce

I have the following form data type:
```
interface UploadedFile {
  data: string;
  extension: string;
  file: File;
}

type FormValues = {
  firstName: string;
  images: UploadedFile[];
}
```

I create a ```useForm``` hook:
```
function MyForm() {
    const { control, register, handleSubmit } = useForm<FormValues>()
    return (
         <form>
             <Controller
                    control={control}
                    name="firstName"
                    rules={{
                      validate: (name) => {
                        if (!name) return "error";
                        return undefined;
                      }
                    }}
                    render={({ field, fieldState }) => (
                      <FormControl error={!!fieldState.error} fullWidth>
                        <FormHelperText>{fieldState.error?.message}</FormHelperText>
                      </FormControl>
                    )}
               />
        <Controller
                control={control}
                name="images"
                rules={{
                  validate: (images) => {
                    if (!images.length) return "error";
                    return undefined;
                  }
                }}
                render={({ field, fieldState }) => (
                  <FormControl error={!!fieldState.error} fullWidth>
                    <FormHelperText>{fieldState.error?.message}</FormHelperText>
                  </FormControl>
                )}
        />
         </form>
    )
}
```

In `<Controller name="firstName" ....` in the render prop the ```fieldState.error``` type is:
```
FieldError | undefined
```
That means i can access ```fieldState?.error?.message```

But in `<Controller name="images" ....` in the render prop the ```fieldState.error``` type is:
```
{
    data?: FieldError | undefined;
    extension?: FieldError | undefined;
    file?: FieldError | undefined;
}[] | undefined
```
Why here its not ```FieldError | undefined```? why its the ```UploadedFile[]``` but with every property inside of `UploadedFile` having the type `FieldError | undefined`?

How can I access the ```fieldState?.error?.message``` in the `'images'` property?

### Expected behaviour

`images` property should have `fieldState.error` type as `FieldError | undefined` like in the `firstName` property and not 
```
{
    data?: FieldError | undefined;
    extension?: FieldError | undefined;
    file?: FieldError | undefined;
}[] | undefined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
@kotarella1110 made a fix yesterday 🙏 it will be in the next release: https://github.com/react-hook-form/react-hook-form/pull/6605
