### ISSUE TITLE
Versions after 3.27.0 broken with Material UI

### ISSUE THREAD

**Issue by OssiPesonen** [react-hook-form/react-hook-form#662]
I was attempting to figure out why `errors` was not being populated using Material UI. It appers since version 3.27.0 the library has been broken, for unknown reasons. I found a Codepen where I could test this with an older version which can be updated up to 3.27.0-beta that works (use the Double Click Form):

To replicate, open the Codepen from below and click "Double Click Form". See that it works with 3.19.0. (prevents submit, shows error). Update the dependency up to 3.27.0 and see that errors are not being populated anymore.

https://codesandbox.io/s/react-hook-form-material-ui-0fib6?from-embed

If you upgrade the version up to 3.27.0 the errors are not being populated and the form continues to submit.

**Comment by bluebill1049** [comment]
hey @OssiPesonen any chance you can test out the latest version? see if we have resolved it

**Comment by OssiPesonen** [comment]
Yes, I installed the package today, 3.29.0, and the problem persists.

**Comment by bluebill1049** [comment]
ok thanks, i will take a look tmr morning.

**Comment by bluebill1049** [comment]
it's actually correct and it was a bug fix. because you would need `required`.

**Comment by OssiPesonen** [comment]
Adding `required` to TextFields do nothing in this case.

Here's a codepen of 3.29.0 with TextField and `required`
https://codesandbox.io/s/react-hook-form-material-ui-tydr4

**Comment by krnlde** [comment]
I don't see any required in your code. You'd need to set `ref={register({required: true})}` on any Input you want to be required.

**Comment by OssiPesonen** [comment]
`ref` is not something Material UI has in TextFields, that's why you use innerRef (https://react-hook-form.com/get-started/#WorkwithUIlibrary)

    <TextField inputRef={register} label="First name" name="FirstName"/>

I updated the codepen to add  `required` in the register (which already has a pattern defined) but the problem still persists:
https://codesandbox.io/s/react-hook-form-material-ui-d9wtc

**Comment by OssiPesonen** [comment]
Damn, it's `inputRef` not `innerRef`, where did I read inner...? It appears to work with `inputRef`, i'm sorry!

Thank you so much for a quick response! This is the fastest I've ever received a comment on Github.

 I'm closing this issue.

**Comment by krnlde** [comment]
`innerRef` is commonly used by react libraries like reactstrap. Maybe you copied it somewhere there :) Anyhow, great to hear it works.

**Comment by cargallo** [comment]
Hi I'm just evaluating the library for first time (looking for a replacement of Formik because it's making me crazy with FieldArray performing unexpected behaviour), so I was checking the docs to learn how to integrate it with material ui. 

I think the confussion between innerRef and inputRef comes from an ambiguity in the docs, here is the link: 

[https://react-hook-form.com/get-started#WorkwithUIlibrary](https://react-hook-form.com/get-started#WorkwithUIlibrary)

![image](https://user-images.githubusercontent.com/13320290/70811708-e90ce580-1da4-11ea-8f0d-63390059c006.png)

**Comment by bluebill1049** [comment]
@cargallo you want to submit a PR for this? I should be `inputRef/innerRef`.

**Comment by cargallo** [comment]
@bluebill1049 I recently did it. I realized that there is no documentation in Spanish, I am from Argentina if you are interested I can collaborate with translation, but I don't know how to. Great job by the way!

**Comment by bluebill1049** [comment]
wow, that would be awesome! @cargallo it's not a small task tho. Would love to have Spanish to help more developers <3

Here are the translation files:
https://github.com/react-hook-form/react-hook-form-website/tree/master/src/data

no pressure, if you find it's too much work, but you are happy to help it would be amazing!  ❤️✌🏻

**Comment by cargallo** [comment]
I'll glad to contribute. I hope to make time the next week for starting. I took a look to the actual structure of the docs and IMHO I think it could be easier to mantain if you make a folder for each topic and a particular file for each language. In the changes I made in getStarted.tsx the chinese and japanese languages differ in structure from the other languages, but it's difficult to compare. If you have a file for each the maintainers could just copy the entire file and start to translate, and then you can check if the structure is similar to 'en' translation.
For example in getStarted folder you could have the files
getStarted.tsx --> the main file with the export for all languages importing each language in folder
getStarted.en.tsx .... getStarted.es.tsx ... getStarted.jp.tsx... and so on

**Comment by bluebill1049** [comment]
well, I totally I agree on @cargallo that was my fault... when i get some free time after V4 of RHF I will structure it that way. If you don't mind to spend extra effort on time, i would really appreciate too.
