### ISSUE TITLE
[Bug]: Receive NaN warning when input is required and input is cleared

### ISSUE THREAD

**Issue by blainelawson** [react-hook-form/react-hook-form#6620]
### Version Number

7

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-furtc?file=/src/index.tsx

### Steps to reproduce

1. Go to code box example
2. Add `required={true}` to input with both name and type of "number"
3. Delete values from input field
4. View warning in console.

### Expected behaviour

Value is successfully stored as a number, not a string. 
"Please fill out this field" warning occurs if the field is left blank. 
No NaN warnings.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
this is not an issue with the lib, since you are building a controlled component, you should take care of your input state during integer parsing.

`props.onChange(parseInt(e.target.value, 10));`
