### ISSUE TITLE
[Bug]: unregister method isn't working in version 7 while it works in the version 6

### ISSUE THREAD

**Issue by M2Changezi** [react-hook-form/react-hook-form#6625]
### Version Number

7

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-unregister-v6-forked-qs8o6

### Steps to reproduce

There is a solved same issue of version 6 .but version 7 has the same one

### Expected behaviour

the unregister method should work it doesn't work ! 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
because next render this line will run again and input get register again

`<input {...register("lastName")} />`

unmount that input to avoid input gets register again.

**Comment by bluebill1049** [comment]
please read my comments above.
