### ISSUE TITLE
[Bug]: RHF treats a checkbox as radio after the type of the field has been changed

### ISSUE THREAD

**Issue by samld** [react-hook-form/react-hook-form#6638]
### Version Number

7.15.3+

### Codesandbox/Expo snack

https://codesandbox.io/s/competent-swartz-mh4ve?file=/src/App.tsx

### Steps to reproduce

1. Go to sandbox
2. Select an option for a snack
3. Select a drink
4. Click on go

The error messages are expected.

6. Click on "multiple for snacks"
7. Select a second snack
8. Select a second drink

When you select an additonal a snack, it's treated as if it was an `option` and it changes the value of field instead of appending to it.

9. Click on "add a snack"

One of the snacks disappears.

10. Select a second snack

The error message disappears and the content is logged in the form.

### Expected behaviour

When the type of the input is switched from `radio` to `checkbox`, it should not behave as if it was a radio button.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
We don't support such usage.

- build a controlled component and change input type internally 
- switch component instead its type.

**Comment by samld** [comment]
Thank you for the quick response! I would suggest that you document this fact somewhere so people won't assume that changing a prop on a HTML element works with RHF. I'll try one of your solutions. Good day to you!
