### ISSUE TITLE
[Bug]: Virtual inputs registered in useEffect can dissappear from form values.

### ISSUE THREAD

**Issue by adriantrunzo** [react-hook-form/react-hook-form#6639]
### Version Number

7.15.4

### Codesandbox/Expo snack

https://codesandbox.io/s/exciting-pasteur-d6c7y?file=/src/App.js

### Steps to reproduce

1. Press "Get values" or "Submit" to verify that the `id` of the first field array element is present in the form values.
1. Add a new field.
1. Press "Get values" or "Submit" to verify that the `id` of the first field array element is missing from the form values.
![Screen Shot 2021-09-24 at 5 02 53 PM](https://user-images.githubusercontent.com/1218900/134739397-f87591f3-ff32-4656-a7ae-81f5b37628e2.png)

### Expected behaviour

The virtual input registered for the first field array element does not disappear from the form values.

---

The documentation for the `register` method states in the "Custom Register" section:
> You can also register inputs with useEffect and treat them as virtual inputs

When I try to do so in a field array context, as shown in the sandbox, the virtual input value does not persist across multiple renders (due to appending more fields in this case). If I completely remove the dependency array from `useEffect` so that it runs after every render, there is no problem, but at that point I should just get rid of the `useEffect` all together.

In this case I happen to be using a string value that could also just be associated with a hidden input, but I am hoping to use virtual inputs for more complex object types that can't easily be put into hidden inputs without converting to/from JSON. 

Please let me know if I am misunderstanding the documentation. Thanks.

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please refer to this discussion: https://github.com/react-hook-form/react-hook-form/discussions/6621 `id` is reserved for render.
