### ISSUE TITLE
Delayed Register when Form in offcanvas area ??

### ISSUE THREAD

**Issue by iwarner** [react-hook-form/react-hook-form#664]
**Describe the bug**

When the form is within an offcanvas area, it takes two submit clicks to submit the form - video below.

Video: https://www.loom.com/share/5988d97cbf9e441687af65a77ee8492d

**Comment by bluebill1049** [comment]
hey @iwarner thanks for the video, any chance you can reproduce this in a codesandbox?

**Comment by iwarner** [comment]
@bluebill1049 I would love to but its just quite a complicated use case to do that.

What I need to do is 
A. test form outside of the Offcanvas to elimiate that possibility
B. Reproduce a simpler show hide example to add your form onto the Dom dynamically and see if the Submit works first time.

Will take some time to do B

Ian

**Comment by bluebill1049** [comment]
thanks @iwarner is it possible to just isolate the issue and reproduce such an issue?

**Comment by iwarner** [comment]
@bluebill1049 As per the video its not an easy useCase to simply reproduce. I will try my best though, I am working on A at the moment to make sure that there is not an error with my code, which is more likely the case :)

**Comment by bluebill1049** [comment]
thanks for the update @iwarner

**Comment by bluebill1049** [comment]
going to close this issue now, feel free to re-open when you have more information and example to reproduce.
