### ISSUE TITLE
[Bug]: 7.16.0 breaks types of fieldState in render Controller

### ISSUE THREAD

**Issue by iamchathu** [react-hook-form/react-hook-form#6646]
### Version Number

7.16.0

### Codesandbox/Expo snack

https://codesandbox.io/s/clever-wind-e90us?file=/src/App.tsx

### Steps to reproduce

Property 'message' does not exist on type 'string'

### Expected behaviour

Types to work without issues.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Property 'message' does not exist on type 'string'.
   31 |                 error={fieldState.error !== undefined}
   32 |                 label="Name"> 
> 33 |                 helperText={fieldState.error?.message}
     |                                               ^
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
potentially related to this commit: https://github.com/react-hook-form/react-hook-form/pull/6605 will do more investigating next week.

**Comment by joniaiuser** [comment]
I am still seeing this with 7.16.1. 

Type error: Property 'line1' does not exist on type 'FieldError'.

register={register("bankAddress.line1")}
error={errors.bankAddress?.line1?.message}

**Comment by bluebill1049** [comment]
@joniaiuser can you share a reproducible codesandbox?
i have even attached tests and they are passing in the commit above.
https://github.com/react-hook-form/react-hook-form/pull/6650/files#diff-9f0ec296b68f740c4920c606982bbc1f471f9b2b3ab415e22d96af1b612b000fL1186-R1188
