### ISSUE TITLE
The "Get Started"'s CodeSandbox validation message is not viewable because of the black background

### ISSUE THREAD

**Issue by OfirD1** [react-hook-form/react-hook-form#6647]
The [Get Started](https://react-hook-form.com/get-started) page links to [this CodeSandbox](https://codesandbox.io/s/react-hook-form-get-started-j5wxo) in which the validation message can't be seen because it has black color displayed over a black background.

Either the background or the message color should be changed.

**Comment by bluebill1049** [comment]
thanks fixed.
