### ISSUE TITLE
[Bug]: HTMLInputElement.files setter: Value being assigned does not implement interface FileList.

### ISSUE THREAD

**Issue by jsefiani** [react-hook-form/react-hook-form#6648]
### Version Number

7.15.3

### Codesandbox/Expo snack

https://codesandbox.io/s/condescending-feather-57ded?file=/src/App.js

### Steps to reproduce

Click on "Choose file" to upload a photo (it directly uploads your file and saves the response of the API call to the form state)

### Expected behaviour

When uploading the file, it should save the response of the API call (id and URL of the resource) to the form state such that I can save it together with the whole form and create a product.

Desired form state:
```
{
 productName: "",
 file: {
  id: "",
  url: ""
 }
}
```

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Relevant log output

```shell
When I try to save the the API response from the uploaded file to the form state, I get the following type error:

HTMLInputElement.files setter: Value being assigned does not implement interface FileList.
```

I don't want to save the file to the form state, as that is not needed in my setup but nevertheless `setValue` is expecting the value to implement the `FileList` interface while I just want to save the ID an URL of the uploaded file.

Let me know if anything is unclear.
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
FileList object is immutable. What are you try to achieve here?
