### ISSUE TITLE
setState set default values

### ISSUE THREAD

**Issue by sayjeyhi** [react-hook-form/react-hook-form#665]
When I set another state on my form component it will set all field to default value, cuz they come from my component props .

```javascript
  const { handleSubmit, register, errors } = useForm({
    defaultValues: {
      title: props.address.title,
      phone: props.address.phone,
      address: props.address.address,
    },
  });
  const [location, setLocation] = useState({});
```

**Desktop (please complete the following information):**
 - Device: :Laptop
 - OS: windows
 - Browser chrome
 - Version  last

**Comment by bluebill1049** [comment]
This is not clear. please supply with codesandbox or better explanation on your issue.

**Comment by bluebill1049** [comment]
you probably should use `reset()`

**Comment by sayjeyhi** [comment]
it was a mistake and thank you for great library 🤓

**Comment by bluebill1049** [comment]
ha no worries :) glad you sort it out.

**Comment by jinocj** [comment]
hey im facing the same issue , if default values are set by state ,  the form in not updating with default values, @bluebill1049 can u help

**Comment by bluebill1049** [comment]
need richer context, I am not a mind reader... provide a codesandbox i can take a look.

**Comment by jinocj** [comment]
import React  from 'react';
import { Card,CardBody, Button,Input,Form,Label,Row,Col,FormGroup} from 'reactstrap';
import { useForm ,Controller} from 'react-hook-form';
import ReactDatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
import InvalidFeedback from 'components/InvalidFeedback'

const CreateFormComponent = (props) => {
    

    const { register, handleSubmit, errors,control  } = useForm({
        defaultValues: {
         ...props.defaultValues,
        },
      });
      
    const onSubmit = (data,e) => {
        props.onSubmit(data)
        e.target.reset();
    }
  
  return (
     
          <Card>
              <CardBody>
                <Form onSubmit={handleSubmit(onSubmit)}>
                    <Row>
                    <Col md={6} xs={12}>
                    <FormGroup>
                    <Label >Title</Label>
                    <Input type="text" name="title"  innerRef={register({required: true})} placeholder="title"/>
                    {errors.title && errors.title.type==='required' && <InvalidFeedback text="This field is required" /> }
                    </FormGroup>
                    </Col>
                    <Col md={6} xs={12}>
                    <FormGroup>
                    <Label >Date</Label>
                    <Controller
                        as={<ReactDatePicker minDate={new Date()} dateFormat="dd/MM/yyyy"/>}
                        control={control}
                        valueName="selected" 
                        onChange={([selected]) => selected}
                        name="date"
                        className="form-control"
                        placeholderText="Select date"
                        rules={{ required: true }}
                       />
                        {errors.date && errors.date.type==='required' && <InvalidFeedback text="This field is required" /> }
                    </FormGroup>
                    </Col>
                    <Col md={6} xs={12}>
                    <FormGroup>
                  <Label>Status</Label>
                        <Input type="select" name="status"  innerRef={register({required: true})}>
                        <option value="active">active</option>
                            <option value="inactive">inactive</option>
                        </Input>

                    </FormGroup>
                    </Col>
                    <Col md={6} xs={12}>
                    <FormGroup>
                    <Label >Description</Label>
                    <Input type="textarea" name="description"  innerRef={register({required: true})} placeholder="description"/>
                    {errors.description && errors.description.type==='required' && <InvalidFeedback text="This field is required" /> }
                    </FormGroup>
                    </Col>
                    </Row>
                    
                     <center><Button color="primary" className="submit-btn" type="submit">Create</Button></center>
                </Form>
               </CardBody>
           </Card>

    
  );
}

export default CreateFormComponent;

**Comment by jinocj** [comment]
@bluebill1049  this is my code ,  where props.defaultValues are coming from a parent component

**Comment by bluebill1049** [comment]
use `reset` at `useEffect`, if default values coming async

**Comment by jinocj** [comment]
thanks @bluebill1049 , it helped , thanks for quick response

**Comment by man-trifork** [comment]
@bluebill1049 This is still relevant with the latest stable version. What can we do to workaround?

https://codesandbox.io/s/material-demo-wnmog?file=/demo.js

Thanks in advance!
