### ISSUE TITLE
[Bug]: ShouldFocus for useFieldArray is broken

### ISSUE THREAD

**Issue by calcifer9000** [react-hook-form/react-hook-form#6654]
### Version Number

7.8.0 to latest

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-i9klt

### Steps to reproduce

Append button has been set to shouldFocus: true and focusIndex: 1. (If they exist, it should focus on that input)

1. Go to codesandbox.
2. Click an input. So that focus will be on it.
3. Click Append button.

Expected Behavior: 
Second row, 2nd column should be focused for whenever append is clicked

Actual Behavior:
Focus stays on wherever it previously was. No matter how many times user enter. ShouldFocus is simply not being honored.

4. Repeat Step 2 and 3, to see that the focus simply does not change

### Expected behaviour

Change react hook form version to 7.7.1 and Expected works.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
while looking for an alternative solution found a issue tho, you can use `focusName` instead to hardcode which input to be focused

```
{
  focusName: 'xxxx'
}
```

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/commit/dcd8c7e743bad61f451416115e614a3a2bf34dce
