### ISSUE TITLE
Support equality checks on form values of Date objects

### ISSUE THREAD

**Issue by jviall** [react-hook-form/react-hook-form#6657]
**Is your feature request related to a problem? Please describe.**
The input field of the project I work on works with native Date objects. We also allow the user to clear any changes to an individual input field back to its default value. However, since RHF's `deepEqual` function only does a simple reference equality check on Date objects, manually setting the value back to its default value doesn't satisfy the check of if the field `isDirty`, since `(new Date()) !== (new Date())`

**Describe the solution you'd like**
The `deepEqual` utility that RHF uses to check against default values already checks whether either of the values are instances of `Date`. Rather than handle `Date` objects with a simple `===` check, I'd love for there to be a separate case to handle the comparison of two `Date` objects in a way like:
```JS
if (isDateObject(object1) && isDateObject(object2)) {
  return object1.valueOf() === object2.valueOf();
}
```

**Describe alternatives you've considered**
The most obvious alternative is for my team to refactor our project's use of Date objects to instead work with Dates in some normalized primitive representation like Epoch string, UTC, etc. This would be a non-trivial amount of work for us, so I'm hoping that supporting equality checks on Date objects would be a welcome enhancement to RHF, since you already make an effort to handle more typical object types of n-depth.

**Comment by jviall** [comment]
If this enhancement would be a welcome change, I'd be happy to submit a PR.

**Comment by bluebill1049** [comment]
Thanks for the feature request, putting into the pending status.

**Comment by kondei** [comment]
I want this feature because react-hook-form with MaterialUI DatePicker assumes the once-touched same date dirty.

**Comment by kondei** [comment]
Or how about using a library like fast-deep-equal, but not deepEqual.ts?

**Comment by bluebill1049** [comment]
looks like there are quite a few upvotes as users desire to have this feature, I will implement what you suggested @jviall and include you in the contribution list when the release notes is out.

**Comment by bluebill1049** [comment]
> Or how about using a library like fast-deep-equal, but not deepEqual.ts?

thanks for the suggestion, but I care a lot about lib bundle size, so if I can avoid external deps that would be my preferred option.

**Comment by jviall** [comment]
@bluebill1049 thank you!! One follow-up question: after [this commit](https://github.com/react-hook-form/react-hook-form/pull/6706), what is the expected behavior of `deepEqual` if `isDateObject(object1) === true` but `isDateObject(object2) === false`. Previously this case was being handled as `object1 === object2`, but now I believe it will go into the recursive `deepEquals` check. Just want to verify that this case is being checked and doesn't result in any unexpected error, but I have a feeling it will be ok since `Object.keys(new Date())` is an empty array.

**Comment by bluebill1049** [comment]
> @bluebill1049 thank you!! One follow-up question: after [this commit](https://github.com/react-hook-form/react-hook-form/pull/6706), what is the expected behavior of `deepEqual` if `isDateObject(object1) === true` but `isDateObject(object2) === false`. Previously this case was being handled as `object1 === object2`, but now I believe it will go into the recursive `deepEquals` check. Just want to verify that this case is being checked and doesn't result in any unexpected error, but I have a feeling it will be ok since `Object.keys(new Date())` is an empty array. 

Yes, ur assumption is correct.
