### ISSUE TITLE
[Bug]: setValue to null for nullable field does not reset dirtyFields

### ISSUE THREAD

**Issue by jreg123** [react-hook-form/react-hook-form#6673]
### Version Number

7.15.3

### Codesandbox/Expo snack

https://codesandbox.io/s/7bvjg

### Steps to reproduce

I'm creating a large form where it is useful for users to be able to independently revert changes before submitting the entire form. I'm trying to leverage the dirtyFields property to achieve this, as shown in the sandbox.

1. Go to the sandbox
2. Type in the first input field
3. Reset button pops up for that field
4. Press reset button
5. Field resets to default and reset button disappears
6. Repeat steps 2-4 for second (nullable) input field
7. Field resets to original null value, however reset button does not disappear, and dirtyFields remains true for the nullable field

### Expected behaviour

The same behaviour whether resetting a field to a string value or a null value (provided the type is nullable)

I don't think the nullability itself is the issue, you can set the type of the first field to be nullable, but start with a string value and it performs as expected.

I have tried to fork the repo and play with a few tests for deepEquals and setValue but they don't seem to reproduce the issue so I may be looking in the wrong places.

In reality I probably don't need the string values to be nullable, but the same occurs for input with type="number", which I would prefer to be nullable if possible.

Thanks in advance for your help, and putting together this brilliant library! 

### What browsers are you seeing the problem on?

Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report (it helps). This is expected behaviour and let me explain:

## What happened

For uncontrolled input (native input)

```
<input id="test" />

const input = document.querySelect('#test')

input.value = undefined;  
// will result 
console.log(input.value);  "undefined"

input.value = null;  
// will result 
console.log(input.value);  ""
```

This will result `""` never match will null and hence dirty fields remain dirty.

## Solutions

- Use native input natively, avoid `null` or `undefined` and set default as `''`
- build a controlled component wrapper with `Controller`, so the input state gets hosted locally and nonstandard input value will be allowed.

**Comment by jreg123** [comment]
Thanks for responding to this so quickly!

I can move to using the controller for everything, I already do for react-select and textarea items. I was a bit concerned the performance of that for many items would be worse that the uncontrolled versions though.

Does the controller not also use the setValue method behind the scenes? As in this case even when I don't submit the actual value returned by the input (which will be '' as you say) to setValue it doesn't reset the dirtyFields. This is hopefully demonstrated by the logged output at the bottom of the form if you update the value in onResetField to a constant value.

i.e.
- setValue("fieldName", null, {shouldDirty: true}) will set isDirty back to false but will leave dirtyFields populated if the defaultValue was null
- setValue("fieldName", "test", {shouldDirty: true}) will set isDirty back to false and remove the dirtyFields entry for that field if the defaultValue was "test"

Probably still solved by changing to controlled as you suggest but just wanted to clarify that the same seems to occur even if you take the input itself out of the equation.

Thanks for your help!

**Comment by jreg123** [comment]
I've added two buttons at the bottom of the CSB that hopefully highlight this using only setValue calls.

Thanks

**Comment by bluebill1049** [comment]
> I can move to using the controller for everything, I already do for react-select and textarea items. I was a bit concerned the performance of that for many items would be worse that the uncontrolled versions though.

Each Controller acting as its own isolated component, it wouldn't impact your page/form level. They just re-render within.

> Does the controller not also use the setValue method behind the scenes? In this case the value returned by the input (which will be '' as you say) isn't used to reset the value. A value from the defaultValues object is passed to setValue and it doesn't reset the dirtyFields, despite correctly setting the value to null (confirmed by using a watch or getValues). This is hopefully demonstrated by the logged output at the bottom of the form if you update the value in onResetField to a constant value.

for the controlled component, you are responsible and controlling for the input value, not necessarily what's presented in the view. eg:

```tsx
const [value, setValue] = React.useState(1)
<input value={value} onChange={(e) => { setValue(+e.target.value) }} />
```

you can parse the input value to `number`, but the native input will still present the input value as string.

> I think that is independent of the input itself being controlled or uncontrolled?

for uncontrolled input, we are reading the input value straight way unless you are using the `setValueAs` API, that's the difference. 

- native input the input value
- controller/controlled component reading from the state

hope the above make more sense.

**Comment by jreg123** [comment]
Ok thanks for clarifying, I'll move to controllers throughout and see how I get on, thanks!
