### ISSUE TITLE
[Bug]: Rules don't seem to modify the fieldState on Controller-wrapped components

### ISSUE THREAD

**Issue by natedsaint** [react-hook-form/react-hook-form#6674]
### Version Number

7.16.1

### Codesandbox/Expo snack

https://codesandbox.io/s/weathered-monad-yi8q3?file=/src/App.js

### Steps to reproduce

1. Go to provided code sandbox
2. Edit text field with any value
3. Delete value
4. Field does not show error message, console does not show issue

### Expected behaviour

The field should be marked as an error with a message about being required

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by natedsaint** [comment]
derp. I didn't realize the validation only runs when you call it to (with handleSubmit or trigger). Fixed my stuff, closing this. Sorry about that!

**Comment by bluebill1049** [comment]
All good, u can change the mode as well. Eg onChange
