### ISSUE TITLE
[Bug]: Disabled fields still submit their values

### ISSUE THREAD

**Issue by thomasdbock** [react-hook-form/react-hook-form#6690]
### Version Number

7.15.4

### Codesandbox/Expo snack

https://codesandbox.io/s/wizardly-kalam-kgusn?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/wizardly-kalam-kgusn?file=/src/App.tsx
2. Fill in some data in the input field(s)
3. Disable the input fields by clicking the "disable" button
4. Submit the form
5. Check the submitted data

### Expected behaviour

The values should be given as `undefined` as described in the docs:
https://react-hook-form.com/api/useform/handlesubmit 

Additionally, defaultValues are also provided in the submitted values, instead of `undefined`

> disabled inputs will appear as undefined values in form values. If you want to prevent users from updating an input and wish to retain the form value, you can use readOnly or disable the entire fieldset. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by getTobiasNielsen** [comment]
Version 6 does disable and set the values to `undefined`

https://codesandbox.io/s/react-hook-form-get-started-forked-96l4b?file=/src/index.js

**Comment by bluebill1049** [comment]
use the `disabled` props instead of the attribute.

```
<input
   {...register("firstName", {disabled: true})}
  placeholder="First Name"
/>
<input
  {...register("lastName", {disabled: true})}
  placeholder="Last Name"
/>
```

<img width="992" alt="Screen Shot 2021-10-01 at 10 07 02 pm" src="https://user-images.githubusercontent.com/10513364/135617268-93191044-48fd-4252-b520-2fe7e925a607.png">

https://react-hook-form.com/api/useform/register

**Comment by thomasdbock** [comment]
@bluebill1049 is there a way to use this feature when using a control object instead of a register?
