### ISSUE TITLE
[Bug]: Required Rule Validation Triggered When Field Has Default Value and `valueAsNumber`

### ISSUE THREAD

**Issue by kpervin** [react-hook-form/react-hook-form#6694]
### Version Number

17.5.3

### Codesandbox/Expo snack

https://codesandbox.io/s/autumn-moon-hn8yh?file=/src/App.js

### Steps to reproduce

1. Go to codesandbox link.
2. Attempt to submit and see `required` message appear on Controller wrapped component.
3. Remove `valueAsNumber` from Controller rules.
4. See that `required` message no longer appears.

### Expected behaviour

This should not create an issue.

### What browsers are you seeing the problem on?

Chrome 94.0.4606.61

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we don't support `valueAs` API with Controller, please refer to the doc and type definition.

**Comment by kpervin** [comment]
That's odd, because it worked fine in 17.2.3 and did not give Typescript errors (nor does it now).

**Comment by kpervin** [comment]
If possible, I'm going to ask for stricter Typescript rules on the Controller component, so as to identify these errors.

**Comment by bluebill1049** [comment]
please refer to the type definition.

```
export type UseControllerProps<
  TFieldValues extends FieldValues = FieldValues,
  TResult = any,
  TName extends FieldPathWithValue<TFieldValues, TResult> = FieldPathWithValue<
    TFieldValues,
    TResult
  >,
> = {
  name: TName;
  rules?: Omit<
    RegisterOptions<TFieldValues, TName>,
    'valueAsNumber' | 'valueAsDate' | 'setValueAs' | 'disabled'
  >;
  shouldUnregister?: boolean;
  defaultValue?: IsAny<TResult> extends true
    ? UnpackNestedValue<FieldPathValue<TFieldValues, TName>>
    : UnpackNestedValue<TResult>;
  control?: Control<TFieldValues>;
};
```

**Comment by kpervin** [comment]
> please refer to the type definition.
> 
> ```tsx
> export type UseControllerProps<
>   TFieldValues extends FieldValues = FieldValues,
>   TResult = any,
>   TName extends FieldPathWithValue<TFieldValues, TResult> = FieldPathWithValue<
>     TFieldValues,
>     TResult
>   >,
> > = {
>   name: TName;
>   rules?: Omit<
>     RegisterOptions<TFieldValues, TName>,
>     'valueAsNumber' | 'valueAsDate' | 'setValueAs' | 'disabled'
>   >;
>   shouldUnregister?: boolean;
>   defaultValue?: IsAny<TResult> extends true
>     ? UnpackNestedValue<FieldPathValue<TFieldValues, TName>>
>     : UnpackNestedValue<TResult>;
>   control?: Control<TFieldValues>;
> };
> ```
> 
> https://github.com/react-hook-form/react-hook-form/blob/master/src/types/controller.ts#L74

Understood, but it does not show up in Intellisense as an error, so I'm humbly requesting stricter typing so these errors show up in the IDE. I'll personally take this into account from here on, but the documentation does say on `useController`: "Validation rules in the same format as for register."
