### ISSUE TITLE
Feature Request - Show which fields are invalid

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#6697]
**Is your feature request related to a problem? Please describe.**
Often times it would be helpful to know which fields are invalid without having to trigger errors. For example, if I have some sort of wizard form, I might want to disable the next button when certain fields are invalid. However, I don't want to trigger an error and therefore show an error message to the user before they have had a chance to fill in the data.

**Describe the solution you'd like**
I think it would be nice if a new object could be added to `formState` to show which fields are valid and invalid. It could simply be an object with boolean values. 

**Describe alternatives you've considered**
My current solution is to use trigger immediately to see which fields are invalid in certain parts of my app.

**Comment by wdfinch** [comment]
This is especially an issue when working with complex field arrays. If we have a field array with multiple fields, a common UI is to add a save button below each group of field array elements. This way the user can incrementally update field array elements rather than all at once at the end. The issue is I need to constantly use trigger on each change to know if a particular field array element is valid or invalid. In other words, I want to enable the save button for a field array element when its fields are valid and disable it when they are invalid. The only way I can get this information is with trigger which also means prematurely showing errors to the user.

**Comment by bluebill1049** [comment]
i suggest to have `validFields` instead of `inValid`.

**Comment by wdfinch** [comment]
Sound good. Thanks for taking a look at this. This will really help me out.

**Comment by bluebill1049** [comment]
> This way the user can incrementally update field array elements rather than all at once at the end. The issue is I need to constantly use trigger on each change to know if a particular field array element is valid or invalid. 

This is an implemented detail, I wouldn't do that in a single form with multiple field arrays. instead, I would separate them into multiple forms and update them back to the main form when they are valid.

**Comment by wdfinch** [comment]
That fair. I guess it's easier in most cases to do it all in one form since that way I can write all my validation in one schema and all the data is in one place. It works well for me aside from the one drawback of not knowing which field array is invalid without triggering errors.

**Comment by wdfinch** [comment]
I noticed this was removed from the features request list. Is this not going to be implemented?

**Comment by bluebill1049** [comment]
yep, due to the complexity of capturing the valid form inputs.

**Comment by wdfinch** [comment]
Aww ok. Isn't this already captured when we add validation using a scheme or via the `rules` prop? I'm just looking for an object that contains the result of all the validation rules I write so I don't need to trigger errors to know which specific fields are invalid. Is there some compromise to make this simpler? It doesn't need to be calculated for inputs that don't have explicit validation rules. I think that would be fine.

**Comment by wdfinch** [comment]
This would just really help with wizard forms and large field arrays where every input can't be visible at the same time. I tried the above approach of using separate forms, but sync data and validation state across them get pretty complex and messy. It would really be nice to just keep it one form.

**Comment by bluebill1049** [comment]
@wdfinch I think you forgot the schema validation which is not field level (form level) for field level it's a little bit easier, honestly, I did spend quite a bit of time before moving it out.  I may look into it again later on, but so far it's rather a difficult task to fulfill without a lot more code and complexity to be involved.

**Comment by wdfinch** [comment]
Ok, thanks for looking into it.
