### ISSUE TITLE
Allow customization of unregistration on field unmount

### ISSUE THREAD

**Issue by croraf** [react-hook-form/react-hook-form#6698]
**Is your feature request related to a problem? Please describe.**
`register` function has the `shouldUnregister` boolean prop which controls behavior of the unregistration after unmount. As `unregister` can be customized in several ways, this requires that `shouldUnregister` also supports all these customizations.

**Describe the solution you'd like**
Improve the `register` properties so that unregistration after unmount can be fully customized.

**Describe alternatives you've considered**

**Additional context**

**Comment by bluebill1049** [comment]
Thanks for the feature request. what do you mean by have `shouldUnregister` with register? Isn't that already there.

**Comment by bluebill1049** [comment]
![Screen Shot 2021-10-02 at 9 11 09 pm](https://user-images.githubusercontent.com/10513364/135713640-2b605547-c283-49dd-a5bd-3a1feffb35d7.png)

https://react-hook-form.com/api/useform/register

**Comment by croraf** [comment]
I never said "have `shouldUnregister` with register".

It is there, **but only as a boolean**. What I say is that it is **not customizable**. For example, it does not support "unregister but preserve value" logic, and other options that `unregister` function itself supports.

**Comment by bluebill1049** [comment]
oh i see, thanks. will add to the pending feature requests to the proejcts.
