### ISSUE TITLE
A reset empties the input when it is nested inside a FormContext

### ISSUE THREAD

**Issue by bopfer** [react-hook-form/react-hook-form#670]
**Describe the bug**

This is sort of a continuation of the issue that was reported here:

https://spectrum.chat/react-hook-form/general/changes-to-reset-with-version-3-29-1-possibly-a-bug~34f33334-9682-4149-a835-3f9a6bd00fa6

And fixed here: https://github.com/react-hook-form/react-hook-form/pull/667

**Details**

When an input is nested under a `FormContact`, resting will cause the field to go empty.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-reset-form-z0q4o

Just click the `Reset` button and the "Last Name" field will get emptied out. 

**Expected behavior**

The reset should put the default values back in all fields.

Switching to v3.28.15 will work as expected.

**Comment by bluebill1049** [comment]
`react-hook-form@3.29.3-beta.1`

**Comment by bopfer** [comment]
Thanks again for the quick fix!  Yarn is giving me `Couldn't find any versions for "react-hook-form" that matches "3.29.3-beta.1"`.  Maybe it takes time to make it to all their CDNs.  I will try it out later.

**Comment by bluebill1049** [comment]
thanks @bopfer i will release another beta, i am having similar issue here too.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-reset-form-bug-ygmku

**Comment by bopfer** [comment]
Just updated my project to 3.29.3-beta.2 and the resetting is now working properly across all my tests.

**Comment by bluebill1049** [comment]
awesome! @bopfer thanks for reverify the issue. much appreciated ❤️

**Comment by bopfer** [comment]
This issue seems to be happening again.  Maybe I am doing something wrong.

Here is an updated sandbox from the original post above: https://codesandbox.io/s/react-hook-form-reset-form-v87lu (It resets with the defaultValues)

Here is a new one I just created today to try an emulate my app:  https://codesandbox.io/s/beautiful-worker-597ue (It resets by just calling `reset()`)

In both of them, just loading the form, then clicking reset will clear out all values.

Any ideas?

**Comment by bluebill1049** [comment]
dame, I removed the dep by mistake.

**Comment by bluebill1049** [comment]
will patch on the next release sorry @bopfer

**Comment by bopfer** [comment]
Looks like the fix worked for the non-field array fields.  But, it's still emptying out the field arrays.  Here is an updated sandbox:

https://codesandbox.io/s/green-paper-cu24v

I noticed it does _seem_ to work if the `defaultValue` prop is added when mapping over the fields. (It's currently commented out in the above sandbox).  But, the docs don't seems to indicate that it should be used (or I missed it).  Should I be using it for field arrays?

**Comment by bluebill1049** [comment]
> I noticed it does _seem_ to work if the `defaultValue` prop is added when mapping over the fields. (It's currently commented out in the above sandbox). But, the docs don't seems to indicate that it should be used (or I missed it). Should I be using it for field arrays?

Yes, you are right. I will update the doc for this issue.

**Comment by bluebill1049** [comment]
I will close this issue and improve on the documentation, let me know if you find other issues. really appreciated here <3

**Comment by bopfer** [comment]
I think I got my wires crossed with issue https://github.com/react-hook-form/react-hook-form/issues/960#issuecomment-581637840.  That comment was more related to this issue, but they are similar.  Either way, things are clearer now.  Thanks, as always!
