### ISSUE TITLE
[Bug]: Stop shallow copying objects with prototype that are used as field value

### ISSUE THREAD

**Issue by julienavert** [react-hook-form/react-hook-form#6704]
### Version Number

7.17.0

### Codesandbox/Expo snack

https://codesandbox.io/s/eager-mclaren-s7nv4?file=/src/App.js:0-673

### Steps to reproduce

1. Use any custom object with prototype (e.g. a class) as a field value.
2. use `useWatch` or `useForm({ defaultValues })` + submit (provided code sandbox)
3. The object get shallow copied here https://github.com/react-hook-form/react-hook-form/blob/e511ac47b41d59626366e2d58b4e61bde87b89c5/src/utils/cloneObject.ts#L3 and here https://github.com/react-hook-form/react-hook-form/blob/e511ac47b41d59626366e2d58b4e61bde87b89c5/src/useWatch.ts#L80
4. The object is now a plain object.

### Expected behaviour

The object should keep its prototype !!!!!!!

The current behavior (shallow copying) is really unexpected and didn't exist in previous versions (e.g. `v7.12.2`).

If the object needs to be immutable, I think it would be a better approach to use `Object.freeze` (deeply is needed) which keeps prototype.

related issue: https://github.com/react-hook-form/react-hook-form/issues/6319

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> The object should keep its prototype !!!!!!!

Don't ever write a comment like that.

**Comment by julienavert** [comment]
I'm sorry if I offended you, it wasn't my intention.

However, it's a bit rude to ignore a totally valid issue just because of some exclamation marks.

**Comment by bluebill1049** [comment]
I don't care, go fork the repo and fix it yourself, it's open-sourced.
