### ISSUE TITLE
[useController]: Type error when trying to access `fieldState.error.message`

### ISSUE THREAD

**Issue by manskron** [react-hook-form/react-hook-form#6707]
### Version Number

7.17.0

### Codesandbox/Expo snack

https://codesandbox.io/s/heuristic-stonebraker-b514g?file=/src/Input.tsx

### Steps to reproduce

**Describe the bug**
When using `useController`, trying to access `fieldState.error.message` results in a type error.

**To reproduce**
1. Go to 'https://codesandbox.io/s/heuristic-stonebraker-b514g?file=/src/Input.tsx'
2. Look at the type error on line 27

### Expected behaviour

No type errors.

### Relevant log output

```shell
TS2339: Property 'message' does not exist on type 'NonNullable>, PathValue ...>>>>'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
you can try with the new type which just got released, https://github.com/react-hook-form/react-hook-form/releases/tag/v7.17.0

**Comment by bluebill1049** [comment]
also in your example, you are missing the extend

```tsx
import { useController, UseControllerProps } from "react-hook-form";
import { FieldValues } from 'react-hook-form';
interface IProps<FormValues> extends UseControllerProps<FormValues> {
  type: string;
}

export const Input = <FormValues extends FieldValues>({
  name,
  control,
  rules,
  type,
}: IProps<FormValues>) => {
  const {
    field: { ref, ...inputProps },
    fieldState: { error }
  } = useController({
    name,
    control,
    rules
  });

  console.log(error);

  return (
    <div>
      <input ref={ref} type={type} {...inputProps}/>
      <p>{error?.message}</p>
    </div>
  );
};
```
