### ISSUE TITLE
Number of renders when using watch('nameField')

### ISSUE THREAD

**Issue by stephoune** [react-hook-form/react-hook-form#671]
**Describe the question?**
Why when using watch('nameField') in a FieldComponent, every components are rerendered. 
**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-rhfinput-9hrf9
2. Go to Test.js and see the call of watch('Select')
3. Check the number of renders when changing all of components 

Shouldn't the component be rerender only when you change the select value?
**Codesandbox link**
https://codesandbox.io/s/react-hook-form-rhfinput-9hrf9

Thanks for your help !

**Comment by bluebill1049** [comment]
that's because you are using FormContext which is React context API :)
https://react-hook-form.com/advanced-usage#FormContextPerformance

**Comment by stephoune** [comment]
Thank's !! 😀

**Comment by stephoune** [comment]
Sorry, i'm trying to understand how use dirty in React.memo like in your example : 
https://react-hook-form.com/advanced-usage/#FormContextPerformance

Here is my code : 
https://codesandbox.io/s/react-hook-form-rhfinput-9hrf9

**Comment by bluebill1049** [comment]
you mean this?
```
return React.memo(
    () => (
      <div>
        <input name="test" ref={register} />
        {dirty && <p>This field is dirty</p>}
      </div>
    ),
    [dirty]
  );
```

**Comment by stephoune** [comment]
Yes exactly ! But in my codesandbox, this code throw an error...

**Comment by bluebill1049** [comment]
it only works at the root level tho, did you put inside your react component tree?
