### ISSUE TITLE
[Bug]: useFieldArray `append(...)` is reflected in `watch()`, but not in `useWatch()`

### ISSUE THREAD

**Issue by azrosen92** [react-hook-form/react-hook-form#6712]
### Version Number

6.9.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-watch-forked-5m4tk?file=/src/index.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-watch-forked-5m4tk?file=/src/index.js
2. Click on "Append"
3. See console output – there are two `console.log`s, one logging `watch(...)` and one logging `useWatch(...)`
4. The log of `watch` immediately shows the new item in the field array. `useWatch` isn't updated until another character is typed into the new form field or it's unfocused.

### Expected behaviour

I would expect `useWatch` and `watch` to return the same form state at this point.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
<img width="721" alt="Screen Shot 2021-10-05 at 10 27 37 am" src="https://user-images.githubusercontent.com/10513364/135937717-5d0403a2-14dd-46b0-b374-46cab187f15d.png">

can you use the latest v6?
