### ISSUE TITLE
[Bug]: `Path<T>` can not handle generics

### ISSUE THREAD

**Issue by hpohlmeyer** [react-hook-form/react-hook-form#6726]
### Version Number

7.17.1

### Codesandbox/Expo snack

https://codesandbox.io/s/rhf-generic-path-report-iwvwy?file=/src/App.tsx

### Steps to reproduce

1. Create a component, that takes a generic, which extends a minimum set of field values
2. Take the `useForm`-return from a parent component through a prop typed as `UseFormReturn<T>`
3. Try to register a field with one of the prop names defined in the minimum field set
4. Error: Argument of type '<field-name>' is not assignable to parameter of type 'Path<T>'

This becomes way clearer if you look at the codesandbox.

### Expected behaviour

I should be able to register a field with the paths, that can be derived from the extended shape of the generic.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
perhaps we can do the following? @kotarella1110 

```
export declare type Path<T> = (T extends ReadonlyArray<infer V>
  ? IsTuple<T> extends true
      ? { [K in TupleKey<T>]-?: PathImpl<K & string, T[K]>; }[TupleKey<T>]
      : PathImpl<ArrayKey, V>
  : { [K in keyof T]-?: PathImpl<K & string, T[K]>; }[keyof T]) | { [K in keyof T]-?: K; }[keyof T];
  ````

**Comment by bluebill1049** [comment]
thanks, @hpohlmeyer I couldn't get it working deeply nested generic, I will leave this issue open for few more days see if someone else could come up with a solution cc @barrymay @kotarella1110 if there is none, we will implement the flat-level first as an enhancement and leave nested as a limitation.

**Comment by xxleyi** [comment]
@hpohlmeyer Maybe we don't need use generic type in this use case. we can just have a PartialFormData type, such like this: https://codesandbox.io/s/rhf-generic-path-report-forked-x5l6q?file=/src/App.tsx

**Comment by hpohlmeyer** [comment]
@xxleyi Good point! You are right, we do not need a generic here in this example, because excess properties are allowed.

If we turn the concept around and create a form that can have additional fields we would need it again though: https://codesandbox.io/s/rhf-generic-path-report-2-h1u10?file=/src/App.tsx
Without the generic the submit handler would have the wrong type.

We could lift up the form in that case, so it is nothing we couldn’t solve. But I think having the addition to `Path<T>`, that @bluebill1049 proposed would enable the use of extends for flat hierachies without doing harm, so I would still like to see it added to the type.

**Comment by bluebill1049** [comment]
interesting... i think we may need to revert that union then.

**Comment by hpohlmeyer** [comment]
Oh, that is unfortunate, thanks for pointing that out @mSakakibara2000. I’ll play around with the type a little more … maybe I can come up with a different version that is more robust. I’ll open up another PR if I can come up with something.

**Comment by Joe312341** [comment]
So currently the only way to handle partial forms (forms that get used within multiple or forms) is to make all the attributes which are not part of the partial form optional?

**Comment by crudemandarin** [comment]
Too bad a solution wasn't able to be implemented here. @hpohlmeyer, how were you able to address this issue in your implementation?

**Comment by JanPretzel** [comment]
@crudemandarin not sure if it helps your use case, but instead of a constrained generic I used [Required](https://www.typescriptlang.org/docs/handbook/utility-types.html#requiredtype).

Instead of
```typescript
export function PartialForm<T extends { name: string }>({
  form
}: {
  form: UseFormReturn<T>;
}) {
  return <input {...form.register("name")} />;
}
```

try
```typescript
export function PartialFormNew({
  form
}: {
  form: UseFormReturn<Required<{ name: string }>>;
}) {
  return <input {...form.register("name")} />;
}
```

This may not be optimal but for me it was better than nothing.
