### ISSUE TITLE
Avoid input name containing dot/bracket to create nested form fields

### ISSUE THREAD

**Issue by edouardb** [react-hook-form/react-hook-form#676]
Hi there,

Following the `register` section of the [documentation](https://react-hook-form.com/api#register), 
when an input name contains a dot/bracket, it creates nested form fields. This is great! But is there a way to disable this behavior and allow the use of input names with dots or brackets?

```
 <input type="text" name="with.height" ref={register} />
```

What I get

```
{
  width: {
    height: 400
  }
}
```

What I'd like

```
{
  width.height: 400
}
```

Thanks a lot.

**Comment by JeromeDeLeon** [comment]
Is `width_height` not working for you? Because we could provide that feature however I don’t thinks it’s good thing to do considering your use case. Can you give me an example where it might be useful?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by edouardb** [comment]
@JeromeDeLeon thanks for your answer! Currently, I already have a workaround to handle that. I was just asking myself if there is a way to disable the default behavior for this feature, as in some cases you do not necessarily need the creation of nested fields when using dot or bracket.

**Comment by bluebill1049** [comment]
hey @edouardb hmmm we don't have such mechanism just yet.

**Comment by bluebill1049** [comment]
going to close this issue for now as we don't support that in the lib at the moment.

**Comment by BananaWanted** [comment]
Hi @edouardb could you kindly let me know what is the workaround you've used?

I'm currently facing a similar situation. My app relies on some 3rd party APIs that I don't have any control of, requires dot fields like this:
```json
{
  "a.b": [
    {"c": "<input value goes here>"}
  ]
}
```

It would save me a lot of time mapping values around if by any chance something like `<input name="'a.b'[0].c" />` can work.

**Comment by ivansivaklepsi** [comment]
I have the same issue with this library. You can't use input names with a dot in it for this reason.

**Comment by JeromeDeLeon** [comment]
Is my solution above not working for you? and use mapper to map from API to form and vice versa

**Comment by ivansivaklepsi** [comment]
Unfortunately no, because we're using a filename as a key which has extension with a dot. I managed to fix it in another fashion. The only problem I have with this is that for me it felt like a bug at first and had to investigate, but now I see it's actually documented.

**Comment by iampava** [comment]
Could use a way of disabling this behavior as well :D
