### ISSUE TITLE
Is field with array values behavior ok?

### ISSUE THREAD

**Issue by Climooo** [react-hook-form/react-hook-form#678]
**Describe the question?**
I tested the examples with array values, and I the observed behavior is not the one I would exepect, but maybe it's normal.

**To Reproduce (1st case)**
1. Go to https://codesandbox.io/s/6j1760jkjk
2. Click on 'Add friend' two times
3. Remove the first friend
4. Submit and check console
5. There is an undefined value in at the first position of the data array. I expected to have only one value.
Also, when looking at https://react-hook-form.com/advanced-usage#FieldArrays does not have remove button, and the link to codeSandbox does not redirect to the same code.

**To Reproduce (2nd case)**
1. Go to the advanced array example: https://codesandbox.io/s/react-hook-form-field-array-advanced-with-delete-insert-append-edit-l19pz
2. Add some data 
3. Submit and check the console
4. It works, but there is no real array values, just dynamic properties with the id concateneted to the field key. It would be nice if we have a real array instead.

Thank you!

**Comment by bluebill1049** [comment]
hey @lemcii that's expected behavior because RHF removes the index of the item, however, you can filter the items with `undefined`. Here is a complete example: 

https://codesandbox.io/s/react-hook-form-field-array-advanced-with-delete-insert-append-edit-l19pz

**Comment by Climooo** [comment]
OK thank you for your answer (but I'm not Lemcii!). I know your example (I mentioned it in my question), but I was hoping it was possible to have real array (easier to manage, here it's not possible to submit the data as it, and it's hard to describe that kind of data with Typescript).
