### ISSUE TITLE
When the initial value is set by the 'reset' method, the previously customized field disappears

### ISSUE THREAD

**Issue by flycj** [react-hook-form/react-hook-form#680]
**Describe the bug**
When the initial value is set by the 'reset' method, the previously customized field disappears
当我使用reset 方法在异步获取数据后，设置表单的初始值时，之前自定义的表单字段消失了

**To Reproduce**

1. 
```useEffect(() => {
    register(
      { name: "pics", type: "custom" },
      { validate: value => (value && value.length > 1) || "place upload pic" }
    );
  }, []);
```
2. Get data asynchronously through the interface 
3. 
```
reset({ pics: "test pics", test: "test" });
```
4.  on submit  pics field disappear 

**Codesandbox link**
https://codesandbox.io/s/frosty-rain-fsgne

**Expected behavior**
When using reset, custom fields do not disappear and are assigned correctly

**Comment by bluebill1049** [comment]
hey @flycj that's my lack of documentation. after reset all reference will be clear, so you will have to register your input again (even with custom register). This wasn't the behaviour on the previous version, however recently we properly fixed reset and `formState`. hope this name sense. reset will clear all reference regular fields and custom fields.

**Comment by flycj** [comment]
> hey @flycj that's my lack of documentation. after reset all reference will be clear, so you will have to register your input again (even with custom register). This wasn't the behaviour on the previous version, however recently we properly fixed reset and `formState`. hope this name sense. reset will clear all reference regular fields and custom fields.

Therefore, if there are many fields and custom fields, how should I set the initial value in the asynchronous case?

**Comment by bluebill1049** [comment]
1. native fields will take care during re-render itself.
2. custom register you can register again during useEffect

**Comment by flycj** [comment]
If there are multiple custom fields, when re-registering asynchronously and using setValue to set the initial value, it will be re-rendered each time. So in the asynchronous case, is there a better way to implement all the initial values in one command?

**Comment by bluebill1049** [comment]
> If there are multiple custom fields, when re-registering asynchronously and using setValue to set the initial value, it will be re-rendered each time. So in the asynchronous case, is there a better way to implement all the initial values in one command?

hmm that's a good question. looks like for now you will have to RHFInput, but I will think about it and give you a solution soon. a possible solution is not reset custom register fields, but then it's not consistent.

**Comment by flycj** [comment]
Thank you very much for your prompt reply, I will go and see RHFInput.
Of course, I also look forward to better solutions.
I wish you a happy life!

**Comment by flycj** [comment]
> Thank you very much for your prompt reply, I will go and see RHFInput.
> Of course, I also look forward to better solutions.
> I wish you a happy life!



> > If there are multiple custom fields, when re-registering asynchronously and using setValue to set the initial value, it will be re-rendered each time. So in the asynchronous case, is there a better way to implement all the initial values in one command?
> 
> hmm that's a good question. looks like for now you will have to RHFInput, but I will think about it and give you a solution soon. a possible solution is not reset custom register fields, but then it's not consistent.

Thank you very much for your prompt reply, I will go and see RHFInput.
Of course, I also look forward to better solutions.
I wish you a happy life!

**Comment by bluebill1049** [comment]
hey @flycj what about calling the customer register after `reset()`?

```
reset({ pics: "test pics", test: "test" });
      register(
        { name: "pics", type: "custom" },
        { validate: value => (value && value.length > 1) || "请上传作品图片" }
      );
```

**Comment by bluebill1049** [comment]
what about this?
https://codesandbox.io/s/eager-bush-ny64o

**Comment by bluebill1049** [comment]
what about this? https://codesandbox.io/s/eager-bush-ny64o

**Comment by bluebill1049** [comment]
hey @flycj how did you go with the issue?

**Comment by bluebill1049** [comment]
going to close this issue now. feel free to follow up with questions, i have my example above.

**Comment by flycj** [comment]
> going to close this issue now. feel free to follow up with questions, i have my example above.
Sorry, I've been too busy lately. Did not reply to you in time
It is Ok !  thank you very much.

**Comment by bluebill1049** [comment]
awesome! thanks for the update too.
