### ISSUE TITLE
Cannot set 'isTouched' to a field inside Controller

### ISSUE THREAD

**Issue by ivanovserge** [react-hook-form/react-hook-form#6816]
### Version Number

7.17.4

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-possibility-set-istouched-inside-controller-0wg08

### Steps to reproduce

1. Set date via date picker on the first input
2. 'touchedFields' object is empty now

### Expected behaviour

When we deal with components of third-party libraries such as MUI DatePicker we need to set 'isTouched' to a field when interacting with it. Now we can't.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
![Screen Shot 2021-10-15 at 8 40 24 pm](https://user-images.githubusercontent.com/10513364/137467179-0114d2fa-59c4-4819-9d6d-61c6e880dda7.png)

This is not an issue with hook form, looks like the component doesn't have `onBlur` prop, you probably know better than i when to fire onBlur with this component, as long as `onBlur` is executed, hook form will register the input as touched.

**Comment by ivanovserge** [comment]
The old version doesn't have a bug:
https://codesandbox.io/s/react-hook-form-possibility-set-istouched-inside-controller-forked-kzqy5
But the new one does, see the [comment](https://github.com/react-hook-form/react-hook-form/issues/6816#issuecomment-944167867) above.

**Comment by bluebill1049** [comment]
because onBlur is invoked with `undefined`, and there was a bug: https://github.com/react-hook-form/react-hook-form/pull/6481

**Comment by ivanovserge** [comment]
Thanks a lot. You're cool

**Comment by ivanovserge** [comment]
https://codesandbox.io/s/react-hook-form-possibility-set-istouched-inside-controller-forked-serod
Please try to fill date via picker and in console you can see that there's no validation error initially and then the error appears and finally there's no error again. This situation causes the interface to blink (((
