### ISSUE TITLE
Touched array doesn't update when expected

### ISSUE THREAD

**Issue by snorrid** [react-hook-form/react-hook-form#684]
I'm experiencing an issue where if I don't have any "result" rendered the touched array is not updated immediately on change. But the array is populated correctly if I print out the result somewhere in the JSX.

Is this expected behaviour or Is this a bug?

[Wrong Behaviour](https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-zyd7j?fontsize=14&hidenavigation=1&theme=dark)
[Correct Behaviour](https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-8mgkl?fontsize=14&hidenavigation=1&theme=dark)

**To Reproduce**
1. Go to ['Sandbox'](https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-zyd7j?fontsize=14&hidenavigation=1&theme=dark)
2. Type in the "First Name" box.
3. Tab to the next field
4. Click Submit
5. Observe in console that the touched array hasn't changed.

**Expected behavior**
I would expect the touched array to be updated whenever there is a change to a input field.

**Desktop (please complete the following information):**
 - Browser [Chrome, Safari, Firefox]

**Comment by bluebill1049** [comment]
This is expected behaviour. because `formState` is wrapped with `proxy`. so you are not using it during render phase, it will omit the `formSate`. curious what's the usage to read formState in the submit not during the render. i guess you can move formState outside the onSubmit and it should work.

**Comment by snorrid** [comment]
I wanted to read the touched array when submitting to only act on values that have been touched. Your suggestion of moving the formState.touched to a variable outside onSubmit works. 

Thanks you for a great library.

**Comment by bluebill1049** [comment]
awesome @snorrid glad it's working for you
