### ISSUE TITLE
issue: With value set as empty string or null in register api, the field values are getting unset inconsistently during every submit

### ISSUE THREAD

**Issue by sibiraj-sr** [react-hook-form/react-hook-form#6857]
### Version Number

7.x

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-js-forked-hh8os?file=/src/App.js

### Steps to reproduce

1. Go to codesandbox
2. Fill the values
3. Click on submit button (This will successfully submit the form)
4. Now, keep on clicking the Submit button

For every submit this will unset/set the field values inconsistently which causes the error messages to appear too. Even though the value is filled in the input box. `getValues()` returns empty values inconsistently.

https://user-images.githubusercontent.com/45618743/138112843-7ab21e40-f067-478b-9ef7-d560ae76d461.mov

### Expected behaviour

The filed values shouldn't be reset unless resetted.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Relevant log output

```shell
None..
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for the detailed issue report. the issue occurred at the value prop, each time it gets re-run it change the value to empty "", if you need defaultValue set defaultValue or defaultValues in the useForm. i will improve the doc on this part too.

```
{...register("firstName", {
  required: "First name is required",
  value: ""
})}
```

**Comment by bluebill1049** [comment]
i would keep you formValues and do a merge on the submit with whatever defaultValues you would like to fallback.

**Comment by sibiraj-sr** [comment]
This seems to be working fine with original expectations with latest version version without any changes.
