### ISSUE TITLE
Intermitent act warnings

### ISSUE THREAD

**Issue by thoughtassassin** [react-hook-form/react-hook-form#686]
**Describe the bug**
I get intermittent warnings (leaky tests) about components unmounting when I run tests in react-testing-library.

**To Reproduce**
Create tests for a component that has useEffect 

**Codesandbox link**
https://codesandbox.io/s/objective-leavitt-inwp1

**Expected behavior**
There should be some remedy to seeing these errors.

**Screenshots**
From codesandbox example:

<img width="796" alt="Screen Shot 2019-12-18 at 4 57 11 PM" src="https://user-images.githubusercontent.com/1539057/71130467-91f97d00-21b7-11ea-8255-95309f5a11d1.png">

What I see when I run my tests locally: 

![Screen Shot 2019-12-12 at 9 23 35 AM](https://user-images.githubusercontent.com/1539057/71130546-c66d3900-21b7-11ea-987b-62283284a539.png)
![Screen Shot 2019-12-12 at 9 23 42 AM](https://user-images.githubusercontent.com/1539057/71130547-c66d3900-21b7-11ea-89fe-7a4517eb4f64.png)

I have tried wrapping these tests in async methods. Sometimes the problem will go away for a while but they never entirely go away no matter how I try to set up the tests.

**Comment by bluebill1049** [comment]
have you tried `async` act?

**Comment by thoughtassassin** [comment]
I saw the issue that you closed. I have one test that bugs out all of the time. I thought I wrapped it in async act but it didn't have an effect.

**Comment by bluebill1049** [comment]
sure thanks @thoughtassassin i will take a look at this.

**Comment by thoughtassassin** [comment]
Thank you. This issue has been the bane of my existence for the past three weeks. I couldn't figure out where it is coming from.

**Comment by bluebill1049** [comment]
hmm @thoughtassassin i am running it and i don't get any warning?

**Comment by thoughtassassin** [comment]
It happens intermittently. I've been working with that codesandbox for a while. It seems like if the test breaks, the warning shows up and doesn't go away. Once I got the tests are passing, the warning will continue to show. 

It seems that if I refresh the tab or open a new window the tests pass without warnings. It's almost as if a bad state begins the environment is corrupted and the error continues. I don't know. I just kind of baffled as to why it decides to show up and why it is so persistent once it starts happening.

It was interesting creating a codesandbox example and seeing the tests beginning to fail. It acted the same way that it does when my tests begin to fail when I am running my app that was built using Create React App.

I've been trying to look at documentation for this issue and I just saw a good blog about this by Kent C. Dodds talking about this issue in relation to React Testing Library: https://kentcdodds.com/blog/write-fewer-longer-tests.

**Comment by bluebill1049** [comment]
nice article @thoughtassassin i am going to have a read too.

**Comment by thoughtassassin** [comment]
I think I may have discovered what is at the root of my problem. There were three issues:

1) **I was mocking useForm functions.** My form component was being passed those functions from a parent container. Moving useForm directly into my component reduced the failure rate from approximately 30% to 25%  to 5% (based upon running `yarn test` 100 times).

2) **I was sharing one component among all of my`it` blocks.** Creating a new component in each `it`block further reduced the failure rate to 1%.

3) **I didn't have all of my tests wrapped in async methods provided by React Testing Library.** Moving the only test that wasn't wrapped in an async method reduced the failure rate to 0.

Admittedly, this is a small sample. Nevertheless, I think it is statistically significant. Reading Dodds blog was instructive. I realized that I need to change the way I think about testing. Attempting to mock useForm functions in a test is probably not the right approach.

**Comment by bluebill1049** [comment]
awesome man. glad you sort it out and thanks for the detailed update!
