### ISSUE TITLE
is working nested with FormContext ?

### ISSUE THREAD

**Issue by esuarezz** [react-hook-form/react-hook-form#688]
Is not giving me the values of every registered into the form

Parent
<FormContext {...methods} >
      <form className={classes.root} onSubmit={handleSubmit(onSubmit)}>
		<RHFInput
					as={<TextField label={"X"}/>}
					name="X"
					register={register}
				/>
       					<IngredientComponent/>

      </>
</>

And then in IngredientComponent:

	const { register} = useFormContext();
				<RHFInput
					as={<TextField
						id="quantity"
						label="cantidad"
						type="number"
						InputLabelProps={{
							shrink: true,
						}}
					/>}
					name="quantity"
					register={register}
				/>

I wrote just the "behaviour" obviously are missing elements. 
I am submitting from parent and I can see just the parent registered
I have used also without the materialUI elements, and my output from the parent are just the parent elements

**Comment by bluebill1049** [comment]
Can you please follow our issue template? Create a codesandbox for ur issue? It would make my life much easier to solve and verify the issue. Thanks

**Comment by esuarezz** [comment]
Now I am going to bed...
but I have created a parent and then calling this now:

const Example = () => {
	const {register} = useFormContext();

	return(
		<RHFInput
			as={<TextField
				id="standard-number"
				label="unidades"
				type="number"
				InputLabelProps={{
					shrink: true,
				}}
			/>}
			name="units"
			register={register}
		/>
	)
};export default Example;

And the same, the result was just the parent values when I submitted the data

**Comment by esuarezz** [comment]
I just replicated this example:
https://codesandbox.io/s/sad-sutherland-zvfok
And didnt work, I got:
test: "asdasd"


perhaps is something related with typescript?(I am using it)

**Comment by bluebill1049** [comment]
glad you worked it out yourself. what's the confusing part?
