### ISSUE TITLE
add defaultRegister as useForm option

### ISSUE THREAD

**Issue by 890f2151c2be69c51db72017546d00fd** [react-hook-form/react-hook-form#689]
Hi
first, thank you for great hook
then I would like to suggest little improvement
if i want to use custom elements i have to manually register them like 

```
useEffect(() => {
    register({ name: 'customElement' })
}, [])
```

it would be nice add option defaultRegister to useForm like

```
const { register } = useForm({
  defaultValues: {},
  defaultRegister: [
    {name: 'custom element1'},
    {name: 'custom element2'},
  ]
})
```

**Comment by bluebill1049** [comment]
thanks @890f2151c2be69c51db72017546d00fd next version will have a new way doing controlled component :)
https://github.com/react-hook-form/react-hook-form/pull/666

which you probably can skip some of the custom register :)

**Comment by 890f2151c2be69c51db72017546d00fd** [comment]
looks promising.  consider rename Controller to something less generic
