### ISSUE TITLE
Expose `types`, `contextTypes`

### ISSUE THREAD

**Issue by umidbekkarimov** [react-hook-form/react-hook-form#690]
**Is your feature request related to a problem? Please describe.**
Currently, only `useForm`, `FormContext` and `useFormContext` are exposed in main file, all the types has to be imported `react-hook-form/dist/contextTypes` or `react-hook-form/dist/types` which always look hacky and it's not resilient to change. 

**Describe the solution you'd like**
Export all the types from `src/types.ts` and `src/contextTypes.ts`.

**Comment by bluebill1049** [comment]
This will be in the next major release :)  https://github.com/react-hook-form/react-hook-form/pull/666
