### ISSUE TITLE
Field Array add empty item into array

### ISSUE THREAD

**Issue by mohammadhamrah** [react-hook-form/react-hook-form#691]
**Describe the bug**
The library add n `null` item to the array of submited form when the first item has removed.

Even on the sample it's provided by website, this bug exists
https://codesandbox.io/s/6j1760jkjk

**To Reproduce**
1. Add 3 new Friends
2. Then remove the first one
3. Submit the form
4. View the console
```json
{"friends":[null,{"firstName":"","lastName":""},{"firstName":"","lastName":""}]}
```

**Codesandbox link**
https://codesandbox.io/s/6j1760jkjk

**Expected behavior**
It should return 2 item as an array.

**Screenshots**
<img width="701" alt="Screen Shot 2019-12-20 at 21 32 11" src="https://user-images.githubusercontent.com/56275484/71283079-34f4f700-2370-11ea-87dd-5b042548771b.png">

**Comment by bluebill1049** [comment]
Thanks for the issue report @mohammadhamrah That's not a bug, I do aware of this behavior when it was implemented, you can filter out the undefined or null at app. I didn't bake the logic into the lib, because having it your app seems to be the easier solution.

**Comment by mohammadhamrah** [comment]
@bluebill1049 Thanks for you reply, And also thanks for the great library and job you have done.

Just don't you think that as user, clean array is more expected? maybe a `flag` or something can be added to the component to switch it off/on ? so user can decide between clean or un-clean array?

**Comment by bluebill1049** [comment]
@mohammadhamrah you have a valid point. 👍  I will do some investigation on how much logic we will have to implement for this (without growing the lib too much) my design philosophy around RHF is not turning it into a Swiss Army Knife if the developer can easily sort out at app level I would prefer to leave to them and hence simplify the code. I will keep you updated with the investigation too.

**Comment by bluebill1049** [comment]
This is be included in the next Major version (V4)

**Comment by bluebill1049** [comment]
please help on testing too: `v4.0.0-rc.3`

**Comment by mohammadhamrah** [comment]
@bluebill1049 sure, i will check that and give you feed back
