### ISSUE TITLE
React-Native TextInput w/ defaultValues not updating

### ISSUE THREAD

**Issue by smooJitter** [react-hook-form/react-hook-form#692]
Please consider asking the question at our spectrum channel.

https://spectrum.chat/react-hook-form

**Describe the question?**
I can use some help with the following.  The issue... when I attempt to update the text input, the input text changes but quickly reverts back to the default.   

**To Reproduce**
My component looks like this.

```
function SomeFunction({defaulftValues}) { 
  const {
    register,
    watch,
    setValue,
    handleSubmit,
    errors,
    triggerValidation,
   } = useForm({mode, validationSchema});

   const watchFields = watch();

   useEffect(() => {
     Object.keys(defaultValues).forEach(key => {
        setValue(key, defaultValues[key]);
      });
    }, [register]);
       
      return (
        <InputText
              key={f.name}
              field={f}
              reference={() => register({name: f.name})}
              defaultValue={defaultValues[f.name]}
              onChange={text => { setValue(f.name, text, f.require)}}
              errors={errors}
           />
       )
   }
```
and my react native text input looks like this

. TextInput.js
```
      ...
        return (
          <TextInput
              {...field}
              secureTextEntry={field.secureTextEntry && !showPassword}
              ref={reference}
              placeholder={placeholder}
              value={defaultValue}
              onChangeText={text => onChange(text)}
           />
         )
```
Again, The issue... when I attempt to update the text input, the input text changes but quickly reverts back to the default.

**Comment by bluebill1049** [comment]
hey @smooJitter have you tried using https://github.com/react-hook-form/react-hook-form-input? maybe a quick and easy solution for you. we are moving that component into the main repo in the next major version too. so it's a good idea to use it. I will take a deeper look at your issue later too.

**Comment by smooJitter** [comment]
I tried it to no avail.  My first problem was which component should I wrap?   From the above code snippet, The native TextInput is wrapped.   I tried using RNHInput  around each.   To see the actual code, consider “react-native-hook-form-builder”.  [https://github.com/davideddr/react-native-hook-form-builder/issues/2](url)

  

When I log out the onChange event, I can see the changed text but as for the field itself, it changes briefly (flashes) but then changes back.  This only happens when the TextInput has a default value, whether passed dynamically or directly.

**Comment by bluebill1049** [comment]
any chance you can provide an expo link? eg: https://snack.expo.io/@bluebill1049/react-hook-form-input

if you want to debug state change, you can use `watch` API

**Comment by smooJitter** [comment]
lol...  I am anti expo, perhaps I should rethink that.  After playing around with the watch API I realized my text input should should set the "defaultValue" attribute.  I was setting the "value" attribute

**Comment by bluebill1049** [comment]
It’s not about expo, check the code inside expo.

**Comment by bluebill1049** [comment]
going to close this issue now, feel free to ask more questions here or at spectrum 👍

**Comment by mattslight** [comment]
Since this comes up in google when searching for placeholder / default values in Google, I'm including what worked for me in v7 when setting placeholder values in React Native using TextInput

```jsx
export default function MyAwesomeComponent() {
  const {
    register,
    setValue,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm()
  const onSubmit = (data) => {
    console.log('data', data)
  };

  return (
    <View style={styles.container}>
      <TextInput
        style={styles.input}
        {...{ onChangeText: register('firstName').onChange }}
        ref={(data) => console.log(data)}
        placeholder="email address"
      />
      <View style={{height: 16}} />
      <TextInput
        style={styles.input}
        {...{ onChangeText: register('lastName').onChange }}
        placeholder="password"
      />
    </View>
  );
}

const styles = StyleSheet.create({
  label: {
    color: 'white',
    margin: 20,
    marginLeft: 0,
  },
  button: {
    marginTop: 40,
    color: 'white',
    height: 40,
    backgroundColor: '#ec5990',
    borderRadius: 4,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    padding: 8,
    backgroundColor: '#0e101c',
  },
  input: {
    backgroundColor: 'white',
    borderColor: 'none',
    height: 40,
    padding: 10,
    borderRadius: 4,
  },
});
```
