### ISSUE TITLE
issue: react-hook-form with nextjs 12 failed during `yarn build`

### ISSUE THREAD

**Issue by bigint** [react-hook-form/react-hook-form#6935]
### Version Number

7.18.0

### Codesandbox/Expo snack

https://gitlab.com/yo/devparty/-/jobs/1733284296

### Steps to reproduce

1. Clone this repo https://gitlab.com/yo/devparty
2. Migrate to Next 12
3. Run `yarn build`

Here is the CI log https://gitlab.com/yo/devparty/-/jobs/1733284296

### Expected behaviour

`yarn build` should not fail

### Relevant log output

```shell
https://gitlab.com/yo/devparty/-/jobs/1733284296
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
ref: https://github.com/react-hook-form/resolvers/issues/271
