### ISSUE TITLE
issue: Trigger an error abnormally when using require and valueAsNumber rules together

### ISSUE THREAD

**Issue by vimcaw** [react-hook-form/react-hook-form#6938]
### Version Number

7.18.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-bug-vu7gf?file=/src/index.js

### Steps to reproduce

1. Use require and valueAsNumber rules together (maybe only happen on `Controller` component)
2. Submit the form
3. See the error

### Expected behaviour

Don't trigger an error.

After testing, it works well in v7.13.0, the bug happened after upgrading to v7.14.0.

### What browsers are you seeing the problem on?

Chrome, Safari

### Relevant log output

```shell
Error: {"number":{"type":"required","message":"","ref":{}}}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`valueAsNumber` is not supported for Controller
![Screen Shot 2021-11-01 at 5 17 10 pm](https://user-images.githubusercontent.com/10513364/139629727-0f286538-c566-4a8e-8fc8-526c11408deb.png)

**Comment by vimcaw** [comment]
Ok, thanks.
