### ISSUE TITLE
Data call success handling

### ISSUE THREAD

**Issue by dvandervlag** [react-hook-form/react-hook-form#6949]
**Is your feature request related to a problem? Please describe.**
When we do a server call (Let's say a POST) on submit, and the server returns success, there is no way to set the form to 'isDirty: false' anymore. 

**Describe the solution you'd like**
Expose 'setIsDirty' method on useFormState().

**Describe alternatives you've considered**
I tried updating 'defaultValues' with the new data, but the form hooks component did not update this to use the new defaultValues (I put the defaultValues in the useForm hook as stated in the docs).

**Comment by bluebill1049** [comment]
```tsx
React.useEffect(() => {
  if (formState. isSubmitSuccessful) {
    reset(getValues())
  }
}, [formState])
```

**Comment by bluebill1049** [comment]
If the above is not what you after, then i will move into the pending feature log then.

**Comment by dvandervlag** [comment]
Hi @bluebill1049,

Thanks for the quick reply, I'll be testing this today and reopen if needed! 👍🏻

**Comment by dvandervlag** [comment]
Just wanted to get back to you, it works as expected, thank you so much @bluebill1049 !!

**Comment by bluebill1049** [comment]
amazing! awesome to hear.
