### ISSUE TITLE
Type inference is suboptimal when relying on context

### ISSUE THREAD

**Issue by mvestergaard** [react-hook-form/react-hook-form#6952]
### Version Number

7.18.1

### Codesandbox/Expo snack

https://codesandbox.io/s/hopeful-wood-wtgi4?file=/src/index.ts

### Steps to reproduce

The sandbox demonstrates the issue.
When using `useController` or `useWatch` where the form values type is specified directly, the type of the value is a combination of any possible type of any field in the type.

When a control object is passed in, or the path is specified explicitly as a generic parameter, it is inferred correctly.

### Expected behaviour

The type is inferred correctly when not passing in `control`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
There is no usage as beblow: 

```
const {
  field: { value }
} = useController<FormValues>({ name: "name" }); // don't support pass generic per hook

const watchedValue = useWatch<FormValues>({ name: "name" }); // don't support pass generic per hook
```

At the moment, this is a limitation, we had approached to try to unlock this generic but failed which result in the revert from 7.18.0 to 7.18.1 https://github.com/react-hook-form/react-hook-form/pull/6753

**Comment by mvestergaard** [comment]
If it's a known limitation, then that's fine. I couldn't really find anything in the docs touching on it.

If we want type safety, the expected approach right now is this then?
```ts
  const { control } = useFormContext<FormValues>();
  const value = useWatch({ control, name: "name" });
```

Can I be sure that this approach doesn't cause any sort of context related re-renders?

**Comment by bluebill1049** [comment]
> Can I be sure that this approach doesn't cause any sort of context related re-renders?

we don't trigger re-render at the root/provider level of your application.

**Comment by mvestergaard** [comment]
Alright, we'll use that workaround for now then.

**Comment by cuddlecake** [comment]
Just commenting on here because I've also encountered this problem, specifically with useWatch.

Workarounds I have found, given a form with `type IForm = {prop1: string}` are:

The redundancy way
```tsx  
const value = useWatch<IForm, "prop1">({ name: "prop1" });
```

Creating a custom hook
```tsx
function useSpecializedWatch<Path extends FieldPath<IForm>>(name: Path) {
  return useWatch<IForm, Path>({ name });
}

const Child = () => {
  const value = useSpecializedWatch("prop1");
}
```

Another is to create a new type, just to avoid the function nesting. With this one, I have purposefully removed `control` from the props, since if it's provided, the regular `useWatch` can be used. Here's a code example:
```tsx
type UseWatchFn<TFieldValues extends FieldValues = FieldValues>  = {
  <TFieldName extends FieldPath<TFieldValues>>(props: {
    name: TFieldName;
    defaultValue?: UnpackNestedValue<DeepPartialSkipArrayKey<TFieldValues>>;
    disabled?: boolean;
  }): FieldPathValue<TFieldValues, TFieldName>
}

const useSpecializedWatch: UseWatchFn<IForm> = useWatch;

const Child = () => {
  const value = useSpecializedWatch({ name: "prop1" });
}
```
