### ISSUE TITLE
Regression - Jest incorrectly reporting fromState.errors and formState.isValid

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#6955]
### Version Number

7.18.1

### Codesandbox/Expo snack

NA

### Steps to reproduce

Note to reproduce this issue, you will need to use the attached create-react-app project. Because this is a node/jest related issue, it's difficult to reproduce in code sandbox. 

1. Open the attached project
2. Run `npm install`
3. Run `npm start` and open the project in your browser
4. Select an option from the select input and notice that in the console log of `formState.errors` is an empty object and `formState.isValid` is `true` as expected. 
5. Run `npm test` and select all using the `a` key
6. Notice that the final console log of the test reports `formState.errors` as not being empty. Instead, an error is present while `formState.isValid` is `true`. This is correct and does not match how the browser logs. 
7. Downgrade `react-hook-form` to version `7.14.2`
8. Run the tests again and notice that the jest console logs are now correct and show the `formState.errors` object as being empty. 

The output from jest is:
`formState.errors: [object Object] formState.isValid: true`

The output from the browser is:
`formState.errors: undefined formState.isValid: true`

[react-hook-form-jest-issues.zip](https://github.com/react-hook-form/react-hook-form/files/7464355/react-hook-form-jest-issues.zip)

### Expected behaviour

The expected behavior is obviously for jest and the browser to match output. At first, I thought this might be an issue with `jest` or some tooling but it works as expected in older versions of `react-hook-form`. However, if you keep everything constant and downgrade `react-hook-form`, it works as expected.

Note these issues only seems to arise with:

1. field arrays
2. object form values (select inputs)

Lastly in my own project, I am getting incorrect output for `formState.isValid` in jest as well as `formState.errors`. I couldn't reproduce that here but hopefully, the causes are related and both can be resolved. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Thanks, @wdfinch for the report, I don't think this will be something that we will investigate too deep into unless we can reproduce this problem in code sandbox or a use case.

**Comment by wdfinch** [comment]
The use case is a bunch of my tests are failing now even though my forms work correctly in the browser. I don't think this is related to jest because the issue can be observed by keeping the jest version consistent and simply downgrading hook-form.

Code sandbox does have a node environment but it hard to use compared to attaching a project.

If this is a jest issues, I'd be happy to bring it up with them.

**Comment by wdfinch** [comment]
I guess more precisely the use case is users can't perform certain tests in jest right now if they are using field array's and select inputs in their form.

**Comment by bluebill1049** [comment]
If this is an issue, you can reproduce it in a codesandbox with that particular test case as well.

**Comment by wdfinch** [comment]
Ok if i can reproduce in code sandbox would you take a look?

**Comment by bluebill1049** [comment]
yes, definitely. 

- if this issue can reproduce as a user
- if the test case is legit and reproduce the issue

**Comment by wdfinch** [comment]
So it doesn't affect and end user in the browser. It affects the developer who is writing tests for code that uses `react-hook-form`. Is that valid?

**Comment by bluebill1049** [comment]
> It affects the developer who is writing tests for code that uses react-hook-form. Is that valid?

It really depends on the test case.

**Comment by wdfinch** [comment]
Ok let me see if I can reproduce it in code sandbox.

**Comment by wdfinch** [comment]
Just for reference this seems to have started in version 7.15.1.

**Comment by bluebill1049** [comment]
you can refer to the release notes: https://github.com/react-hook-form/react-hook-form/releases/tag/v7.15.1 i don't see anything particularly suspicious.

**Comment by wdfinch** [comment]
Ok so I tried to set this up on code sandbox, but I can't seem to click on and therefore naturally select an element in their environment. I looked at other sandboxes and I couldn't find one working test here for selecting something with `react-select`. I guess we'll just have to close this then and maybe this will work itself out down the road.

**Comment by bluebill1049** [comment]
Thanks for the investigation. If you can reproduce the issue again, happy to reopen and loo into it.

**Comment by wdfinch** [comment]
It seems this has been resolved in the newer versions.
