### ISSUE TITLE
improve validation trigger 

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#6966]
if you are subscribed to `isValid`, then the first call is to update input errors state, second invoke to update the entire form is valid or not. hence invoked twice.

_Originally posted by @bluebill1049 in https://github.com/react-hook-form/react-hook-form/discussions/6959#discussioncomment-1579589_

**Comment by bluebill1049** [comment]
Will try to improve this validation behaviour to reduce the amount of validaiton.

**Comment by chozzz** [comment]
@bluebill1049  Why don't we just do this in our `trigger`?
```
if (name) {
      validationResult = isValid = (
        await Promise.all(
          fieldNames.map(async (fieldName) => {
            const field = get(_fields, fieldName);
            return await executeBuildInValidation(
              field && field._f ? { [fieldName]: field } : field,
            );
          }),
        )
      ).every(Boolean);

      if (_formState.isValid && !isValid) {
        _formState.isValid = false;
      }
    }
```

**Comment by bluebill1049** [comment]
`validationResult` doesn't field level **not** form level

**Comment by chozzz** [comment]
@bluebill1049 But when that code block triggers, the form level was already run, right? (Which got triggered when user validats the previous form control)

**Comment by bluebill1049** [comment]
@chozzz thanks for looking into this.

https://github.com/react-hook-form/react-hook-form/commit/6205e099652a6d8c1b253e3df26236744d2d9f94#diff-5a85c1643c71f45e050ce584d7c0db2bdf2e56f8a7dae86d74fedf01be2d2cabR765

refer to `fieldNames`, it's not every field in the form. So when `trigger` runs, if you are subscribed to `isValid`, then it will return what's the fields validation result is, but if you have subscbed `isValdi` then the whole form need to be validated before flush out the re-render to update the formState of isValid.

**Comment by chozzz** [comment]
Gotcha, thanks for looking into this!

**Comment by bluebill1049** [comment]
thanks for the code review as well. 👍
