### ISSUE TITLE
Removing element from field array data is not iterable

### ISSUE THREAD

**Issue by svict4** [react-hook-form/react-hook-form#6971]
### Version Number

7.18.1

### Codesandbox/Expo snack

https://codesandbox.io/s/mystifying-poitras-zxvfv?file=/src/components/SimpleForm.tsx

### Steps to reproduce

1. Open the form
2. Click on add on Question 2
3. Click on Remove

### Expected behaviour

No error and for element to be removed from field array.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Uncaught TypeError: data is not iterable
    at removeAtIndexes (index.esm.js:373)
    at removeArrayAt (index.esm.js:380)
    at Object._updateFieldArray (index.esm.js:1046)
    at Object.remove (index.esm.js:431)
    at onRemoveFromList (SimpleForm.tsx? [sm]:90)
    at onClick (getQuestionField.tsx? [sm]:117)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
hey, @SimonSelg how's going, mate? 

I did some investigation on your example, I have found a couple of issues. Which I would like to suggest to improve:

-  `Controller` shouldn't wrap around a group of field arrays, if you want to subscribe to `formState`, use `useFromState` hook instead
- I would prefer to convert this function into Component and perhaps convert them into multiple components for maintainability and readbility

```tsx
{getQuestionField(
  i,
  false,
  control,
  null,
  onAddToList,
  onRemoveFromList,
  fieldArrays.find((a) => a.id === i.id)
    ?.fieldArray.fields
)} 
```

The following codesandbox works with deletion now, I have moved the field array into its own Component, just so structure-wise is a bit nicer. 

https://codesandbox.io/s/patient-sun-qfzbr?file=/src/utils/getQuestionField.tsx

**Comment by HenriTalk** [comment]
Hi @bluebill1049 
I think I found a bug regarding useFieldArray which I posted here:
https://github.com/react-hook-form/react-hook-form/issues/3664#issuecomment-961261055
It seems that getValues() and fields (from useFieldArray) are becoming out of sync while mounting/unmounting form and then appending/removing fields.

**Comment by bluebill1049** [comment]
> Hi @bluebill1049 I think I found a bug regarding useFieldArray which I posted here: [#3664 (comment)](https://github.com/react-hook-form/react-hook-form/issues/3664#issuecomment-961261055) It seems that getValues() and fields (from useFieldArray) are becoming out of sync while mounting/unmounting form and then appending/removing fields.

https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by bluebill1049** [comment]
hey, @svict4 is my answer above resolved your issue?

**Comment by svict4** [comment]
Hey thanks **so** much for your help! Really appreciate your suggestions.

**Comment by bluebill1049** [comment]
No worries @svict4, please don't hesitate to ask more. 👍 have a good weekend, mate.
