### ISSUE TITLE
issue: useController() trigger a render when a similar field is updated

### ISSUE THREAD

**Issue by kegi** [react-hook-form/react-hook-form#6977]
### Describe the bug

When using `useController()` hook, a render is trigger on all fields that starts with "name" prop.
By example, if you have fields name :
 - foo
 - bar
 - fooo

touching field "foo" or "fooo" will trigger a render on both of them.

### Version Number

7.18.1

### Codesandbox/Expo snack

https://codesandbox.io/s/55p3h

### Steps to reproduce

1. Go on the sandbox
2. Open the console
3. Touch first field (named "foo")
4. Notice that both "foo" and "fooo" fields were re rendered.

Optionally, try the same thing with the other fields and notice they're working properly.

### Expected behaviour

`useController` should not trigger renders for other fields with similar name.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mufteev** [comment]
A similar problem is if all fields start with the letter "c...", and at the same time create an input field named "c", then updating this field will rerender all fields

**Comment by bluebill1049** [comment]
thanks for the issue, will improve that in the next minor release.

**Comment by mufteev** [comment]
Hi!

I think I experienced this problem again.

My case uses two variables with the following names:
_services_ and _servicesStates_.
```js
const rhf = useForm({
  mode         : 'all',
  defaultValues: {
    services: [],
    servicesStates: []
  }
}
```

And when watching "services", i get re-render if change "servicesStates".
```js
  const services = useWatch({
    name   : 'services',
    control: rhf.control
  });
```

I couldn't believe for a long time that this problem had reappeared.
It wasn't until i renamed the variable "servicesStates" -> "states", that I realized it had happened again.

--
Thank you for developing this wonderful product that allows your users to get rid of the re-rendering of the entire form.
Now I am creating dynamic forms from json and this library allows me to implement my ideas!

**Comment by bluebill1049** [comment]
thanks @mufteev will look into this issue.

**Comment by bluebill1049** [comment]
@mufteev you can use `exact: true` to resolve this problem.

**Comment by mufteev** [comment]
It is interesting, but if using name as array in useWatch does not give the desired effect with `exact`. On the contrary, I don't even get the current state.
```js
  const [minDate, maxDate] = useWatch({
    control: props.rhf.control,
    name   : [props.nameMinDate, props.nameMaxDate],
    // exact  : true,
  });
```
After commenting `exact` i get standard behavior

**Comment by bluebill1049** [comment]
@mufteev can you provide some more detail on the above? what's inside the pro names and what's are you try to subscribe to?

**Comment by bluebill1049** [comment]
hmm looks like this issue is not resolved.

**Comment by mufteev** [comment]
I trying to subscribe on array in dynamic component DatePicker, in which there can be either minDate (field name `startDate`) or maxDate (field name `endDate`).

So for subscription may be following array's:
```js
[undefined, 'startDate']
['endDate', undefined]
```

**Comment by bluebill1049** [comment]
can you try to reproduce this in a codesandbox? are those inputs wrapped with `Controllers` or `useController`?

**Comment by mufteev** [comment]
Hi!

Made a small example, if you comment `exact` then you will see a workable form

https://codesandbox.io/s/suspicious-fast-2l4z1?file=/src/components/Text.jsx
