### ISSUE TITLE
issue: Setting focus directly after resetting causes an error

### ISSUE THREAD

**Issue by henryjin3** [react-hook-form/react-hook-form#6978]
### Version Number

7.18.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-reset-and-setfocus-nv0fq?file=/src/App.tsx

### Steps to reproduce

1. Open sandbox
2. Click on submit query
3. See error
![image](https://user-images.githubusercontent.com/11601915/140382402-e681b83b-7374-42c9-8841-a77c2a4ea203.png)

### Expected behaviour

The form should reset and set focus successfully.

It seems like the reset needs to be async/await somehow? Since adding a timeout like the following works fine:
```
  if (isSubmitSuccessful) {
    reset();
    setTimeout(() => {
      setFocus(`firstName`);
    }, 1);
  }
```

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
setFocus will need to be reset at `useEffect` because the input reference has been reset.

**Comment by henryjin3** [comment]
> 
> 
> setFocus will need to be reset at `useEffect` because the input reference has been reset.

Sorry, could you confirm what you mean? I need to wrap `setFocus` in a `useEffect`?

**Comment by milo-** [comment]
@bluebill1049 I've also just run into this, when calling reset and setFocus in a useEffect. Repro here: https://codesandbox.io/s/reverent-merkle-ke0n3
