### ISSUE TITLE
Inconsistent `watch()` behaviour on complex field names

### ISSUE THREAD

**Issue by KATT** [react-hook-form/react-hook-form#698]
**Describe the bug**

When having default values with complex fields the initial `watch()`-call gives the default values rather than the flattened version.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-watch-issue-hbgwl
2. Observe _"Data from `watch()`:"_ below the Submit-button
3. Edit _Complex field_

**Codesandbox link**

https://codesandbox.io/s/react-hook-form-watch-issue-hbgwl

**Expected behavior**

Both initial `watch()`-call and following `watch()`-calls should produce `Record<string, any>` rather than whatever default form values you put in.

**Comment by bluebill1049** [comment]
This is expected behaviour for V3 as it described in the Doc, however in V4 which will release soon will introduce `watch({ nest: true })` which produce nested object.

**Comment by bluebill1049** [comment]
V4: watchAPI: https://react-hook-form-website-git-v4.bluebill1049.now.sh/api/#watch

**Comment by KATT** [comment]
@bluebill1049 I also tried calling it with `watch(undefined, defaultValues)` but it didn't flatten it either.

I finally got to this workaround -- 

```ts
const { watch } = useFormContext();
const [values, setValues] = useState(watch());

useEffect(() => {
  setValues(watch());
}, [watch]);
```

But it ain't very intuitive.

**Comment by KATT** [comment]
Actually this is what I landed on to get a consistent format of `Record<string, any>` 

```ts
const { watch } = useFormContext();
const [values, setValues] = useState<Record<string, any>>({});
useEffect(() => {
  const t = setTimeout(() => {
    setValues(watch());
  }, 1);

  return () => clearTimeout(t);
}, [watch]);
```

Got any nicer way? If the internal flatten method is exposed I could just call that rather than this mess

**Comment by KATT** [comment]
Thanks for the insanely quick response. I'll wait for V4.

**Comment by bluebill1049** [comment]
actually @KATT you want to give a try on the RC version, then we can go from there: 

`react-hook-form@4.0.0-rc3`

**Comment by KATT** [comment]
Getting same results on V4 on first render when doing `{ nest: false}`

Another issue with complex default values is that I kinda have to use 

```
useForm<any>({
  defaultValues: initialValues,
  reValidateMode: 'onBlur',
});
```

With complex fields as it complains about missing field names when doing reffing of for instance `name="complex.field"`

**Comment by KATT** [comment]
Here's a V4 sandbox with the same issue and using `nest: false`: https://codesandbox.io/s/react-hook-form-v4-watch-issue-y94oo

**Comment by bluebill1049** [comment]
set to `true`?

**Comment by KATT** [comment]
Yeah, then it's consistent, but it's not what I want

**Comment by bluebill1049** [comment]
maybe i need to understand your issue better...

**Comment by bluebill1049** [comment]
what exactly you requirement here? I am a bit confused here. i thought you want the watch result to return nested object, which is what v4 nested offer. give me more context please.

**Comment by KATT** [comment]
I can refactor my code to rely on `{ nested: true }`, that wasn't an option before V4.

A bit of background -- 

I'm using `react-hook-form` over formik in the first place because I have a form with > 100 inputs (a table of data you can bulk update).

In each row I have columns that need to be conditional based on others, i.e. a checkbox should display another input.

To achieve this I have a context provider in my form that calls `watch()` once (calling it in each individual row seems expensive).


This is how a cell in my big table looks like:


```ts


const ResultInputs: React.FC<{
  disabled: boolean;
  namePrefix;
  onChangeResults: TextFieldProps['onChange'];
  register: UseFormInstance['register'];
}> = ({ disabled, namePrefix, onChangeResults, register }) => {
  const { values } = useBulkUpdateContext();
  const enabled = values[`${namePrefix}.enabled`];
  // Avoid re-render except if stuff change
  return useMemo(() => {
    console.log('rerender', `${namePrefix}.enabled`, enabled);
    const checkbox = false ? (
      // This doesn't work for some reason (prob issue in material UI)
      <FormControlLabel
        control={<Checkbox color="primary" />}
        label={`${namePrefix}.enabled`}
        disabled={disabled}
        inputRef={register}
        name="Enabled"
      />
    ) : (
      // tmp workaround
      <label>
        <input
          type="checkbox"
          disabled={disabled}
          ref={register}
          name={`${namePrefix}.enabled`}
        />{' '}
        Played
      </label>
    );

    return (
      <>
        {checkbox}
        {/* 
          Rather than doing `display: 'none'` here I previously did 
          `{enabled && <TextField ..}` but that caused all rows to re-render
        */}
        <div style={{ display: enabled ? 'inline-block' : 'none' }}>
          <TextField
            name={`${namePrefix}.value`}
            type="text"
            inputRef={register}
            disabled={disabled}
            label="Value"
            onChange={onChangeResults}
          />
        </div>
      </>
    );
  }, [disabled, namePrefix, onChangeResults, enabled, register]);
};
```

**Comment by bluebill1049** [comment]
wouldn't it be more efficient to only watch those you want to reply on? instead of watch everything? (unless that's your requirement to watch everything)

**Comment by KATT** [comment]
Yes. But using `useFormContext()` & calling `watch('x')` in each component was really slow, so I just store a big `values: Record<string, any>` in my local context instead; picking up a single value from a flat map is cheap.

**Comment by KATT** [comment]
Also `watch` isn't a callback function so it triggers re-renders

**Comment by bluebill1049** [comment]
`getValues() is a callback function`

**Comment by bluebill1049** [comment]
it's much cheaper to run getValues than watch

**Comment by KATT** [comment]
`getValues()` seem to be working good. I only get 2 renders per cell now on initial load now.

The `?? true` is still needed because the default value isn't propagated until after mounting (which somehow triggers a new render but get an initial glitch where it's falsy)

```ts
const ResultInputs: React.FC<{
  disabled: boolean;
  namePrefix;
  onChange: () => void;
}> = ({ disabled, namePrefix, onChange }) => {
  const { getValues, register } = useFormContext();
  const values = getValues({ nest: false });
  const enabled = values[`${namePrefix}.enabled`] ?? true; 

  return useMemo(() => {
    console.log('rerender', namePrefix, enabled);
    const checkbox = false ? (
      // This doesn't work for some reason
      <FormControlLabel
        control={<Checkbox />}
        label={`${namePrefix}.enabled`}
        disabled={disabled}
        inputRef={register}
        name="enabled"
      />
    ) : (
      // tmp workaround
      <label>
        <input
          type="checkbox"
          disabled={disabled}
          ref={register}
          name={`${namePrefix}.enabled`}
          onChange={onChange}
        />{' '}
        Played
      </label>
    );

    return (
      <>
        {checkbox}
        <div style={{ display: enabled ? 'inline-block' : 'none' }}>
          <TextField
            name={`${namePrefix}.value`}
            type="text"
            inputRef={register}
            disabled={disabled}
            label="Value"
            onChange={onChange}
          />
        </div>
      </>
    );
  }, [disabled, namePrefix, onChange, enabled, register]);
};
```

**Comment by KATT** [comment]
Thank you!! It has acceptable perf now... still triggers unnecessary visit to the render as I use context in it, but I'll see what I can think of later this week to improve it further.

Merry xmas 🎅

**Comment by bluebill1049** [comment]
hey @KATT no worries. I would prefer without using FormContext for your senario, try to compose or pass down props instead Context if possible :) 

Merry Xmas

**Comment by KATT** [comment]
I'll see if I can make it more performant w/o context and report back

**Comment by KATT** [comment]
Hey @bluebill1049 , I still think there's a bug here or a consistent API --

Have a look at https://codesandbox.io/s/react-hook-form-v4-watch-issue-y94oo where I explicitly use `nest: false` on both `watch()` and on `getValues()`, I really do think the API should be consistent and return a flat object both on first render and on following render.
