### ISSUE TITLE
Focus ordering issue when `register` is called in child component

### ISSUE THREAD

**Issue by kuus** [react-hook-form/react-hook-form#6982]
### Version Number

7.18.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-downshift-autocomplete-bz16x

### Steps to reproduce

1. Click submit immediately
1. Fill out autofocused 1st field, then click submit again
2. Fill out autofocused 4th field, then click submit again
3. Fill out autofocused 2nd field, then click submit again
4. Fill out autofocused 3rd field, then click submit
5. The focus order is not correct

### Expected behaviour

Not sure if it is possible and not sure if this can be called a bug, but would be nice that the focus would be respected despite `register` is called in a child component, or is that really an antipattern?

I was doing that as I wanted to encapsulate two form inputs (one is fruit and one is a related hidden input) into the same `Autocomplete` wrapper component, like `AutocompleteFruits` is.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
The focus order is defined by the register order and we don't have an API Or mechanism to change or arrange the focus order.

**Comment by bluebill1049** [comment]
Going to close this issue as is expected behavior. 👍
