### ISSUE TITLE
Why always get a strange number when using the V4 version in ReactNative

### ISSUE THREAD

**Issue by Deantsui** [react-hook-form/react-hook-form#699]
**Describe the question?**
Why always get a strange number when using the V4 version in ReactNative.
I used the ui-kitten component library, but I used got the same result using the ReactNative component.
**To Reproduce**
```
const { handleSubmit, errors, control} = useForm(); 
<Controller
            as={<Input />}
            control={control}
            name="name"
            placeholder="username"
/>
<Button
            onPress={handleSubmit(data => {
              console.log(data);
            })}>
            登陆
</Button>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/10671142/71399840-f016dc00-265f-11ea-8f13-6e1a6ed9955d.png)
![image](https://user-images.githubusercontent.com/10671142/71399845-f3aa6300-265f-11ea-84fa-7e324d84be17.png)
**Package Version**
```
    "react-hook-form": "4.0.0",
    "react": "16.9.0",
    "react-native": "0.61.5",
```

**Comment by bluebill1049** [comment]
```
<Controller
  as={<Input />}
  control={control}
  name="name"
  placeholder="username"
  onChange={(data) => {
    console.log(data);
    return data;
  }}
/>
```

can you show me what's in the console.log?

**Comment by Deantsui** [comment]
@bluebill1049 
[expo](https://snack.expo.io/rkWWvLJyU)
If it works on a real machine, there will be problems. You can go to EXPO to check
![image](https://user-images.githubusercontent.com/10671142/71405613-f2356680-2670-11ea-861f-dbccab0df052.png)

**Comment by bluebill1049** [comment]
I think i under the issue, that's the exactly that example i posted on RHFInput readme page. RHF follow standard borrow event which result is e.target.value, however for native input the argument is different. I am waiting for expo's turn i will supply example soon.

**Comment by bluebill1049** [comment]
try attach onChange like below:

```
onChange={(data) => {
  return data[0].nativeEvent.text
}}
```

**Comment by bluebill1049** [comment]
```
<Controller
            as={<TextInput />}
            control={control}
            name="name"
            placeholder="请输入名称"
            onChange={(data) => {
              return data[0].nativeEvent.text
            }}
          />```

**Comment by Deantsui** [comment]
thanks！

**Comment by bluebill1049** [comment]
no worries :) for React Native you will need to return the input data, cause most React Native input doesn't follow the web standard (e.target.value || e.target.checked). hence you have to attach your own onChange. hope these make sense :)

**Comment by bluebill1049** [comment]
i am closing this issue, feel free to ask more questions here too :)
