### ISSUE TITLE
issue: false should be a valid value for required fields

### ISSUE THREAD

**Issue by aronhoyer** [react-hook-form/react-hook-form#6993]
### Version Number

7.17.5

### Codesandbox/Expo snack

https://snack.expo.dev/tQToV6MKr

### Steps to reproduce

1. Go to Expo Snack
2. Open logs
3. Tap Yes to see empty `formFields.errors` object.
4. Tap No to see field receives error

### Expected behaviour

For a `required` field with boolean values not to receive an error if the value is `false`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Thanks for the issue report. I would suggest using validate function instead for object required check, what we had for required is expected result.

**Comment by aronhoyer** [comment]
yeah that's what we ended up doing. is there a reason the required check for boolean values is written this way?

**Comment by aronhoyer** [comment]
> I would suggest using `validate` function instead for object required check

the value itself isn't getting set to an object, but a boolean. apologies if the Expo Snack isn't clear on that.

**Comment by bluebill1049** [comment]
The `required` attribute is aligned with the native `required` attribute for web-native constraint API, which is mostly used for checking `string` value. for boolean or other data type, refer to `validate`.

**Comment by aronhoyer** [comment]
thanks for the prompt replies!
