### ISSUE TITLE
Warning: [antd: Switch] `value` is not validate prop, do you mean `checked`? 

### ISSUE THREAD

**Issue by violabg** [react-hook-form/react-hook-form#700]
When using Controller with and Switch, I'getting this warning:

```jsx
<Controller
              as={<Switch />} 
              rules={{ required }}
              name={name}
              control={control}
            />
```

Warning: [antd: Switch] `value` is not validate prop, do you mean `checked`? 

in version 3 I resolved this with the type attribute of RHFInput, but is missing on the new Controller component.

```jsx
<RHFInput
             as={<Switch />}
             type="checkbox"
             rules={{ required }}
             name={name}
             register={register}
             setValue={setValue}
            />
```

**Comment by bluebill1049** [comment]
thanks i will sort this out :)

**Comment by bluebill1049** [comment]
@violabg did you provide a default value? that's how controller determine if it's an checkbox or value input.

**Comment by bluebill1049** [comment]
it's better to leave default value for controlled input.

**Comment by bluebill1049** [comment]
Test this out, i may introduce another prop: `defaultValue` then if you pass boolean and it will treat as checkbox

**Comment by violabg** [comment]
> @violabg did you provide a default value? that's how controller determine if it's an checkbox or value input.

I'm building the form dynamically, so I don't know in advance the type of fields.

**Comment by bluebill1049** [comment]
i see, what if i expose a defaultValue prop and you can populate with false, and Controller can detect its a checkbox?

**Comment by violabg** [comment]
I can confirm that by setting the default property to boolean fixes the warning.

> i see, what if i expose a defaultValue prop and you can populate with false, and Controller can detect its a checkbox?

Do you mean expose a defaultValue prop on the  Controller component ?
I think that would be useful in many occasions, especially in dynamic generated forms, when the defaultValue on useForm(defaultValue) it's not known.

**Comment by bluebill1049** [comment]
yes :) i will add the `defaultValue` will release a patch for it. (i think it's useful too)

**Comment by bluebill1049** [comment]
closing this issue, i will release the default value soon :) it's been merged already.
