### ISSUE TITLE
issue: formState isValid is always true after clearErrors

### ISSUE THREAD

**Issue by Kancianeski** [react-hook-form/react-hook-form#7000]
### Version Number

7.19.1

### Codesandbox/Expo snack

https://codesandbox.io/embed/sad-bouman-u5m84

### Steps to reproduce

Example sandbox shows required input control, button which triggers setError + clearErrors and debug informations. At the start: isValid is false, isDirty is false, no errors.

First case:
1. Just simple click the button
2. You see isValid flag is set to true despite the control has not any value (it has required validator)

Second case:
1. Fill control with some example value and then delete it and leave the input empty (just to make the field dirty)
2. You see errors are generated for the control
3. Click the button
4. Despite there are errors for control, isValid flag is set to true

### Expected behaviour

In both cases isValid flag should be set to false after clearErrors

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`clearError` will temporarily remove `errors` and set `isValid` to true, if you want the updated isValid, use trigger instead.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/useform/clearerrors

> https://react-hook-form.com/api/useform/clearerrors
