### ISSUE TITLE
Add wasValidated to the formState properties

### ISSUE THREAD

**Issue by Pavinati** [react-hook-form/react-hook-form#7002]
**Is your feature request related to a problem? Please describe.**
While trying to disable submit buttons while the form is invalid, I need to distinguish between invalid because not yet validated vs invalid due to invalid user input.
This would also help me with the popular css framework Bootstrap, which requires the `was-validated` class on the form element to properly display validation feedbacks to the user.

**Describe the solution you'd like**
I'd like to be able to tell if the validation has run at least once without depending on workarounds that depend on the useForm mode.
```js
  const { formState:{ wasValidated } } = useForm(...);
```

**Describe alternatives you've considered**
When using `onSumbit` mode i can workaround by checking if `submitCount > 0` which guarantees that the input was validated at least once. On the other hand modes like `onTouched` have no clean way to detect it.
Using an effect to set a local state triggers many unwanted re-render and in general doesn't feel right.
```js
useEffect(() => {
  setWasValidated(true); // BAD
}, [isValidating]);
```

**Additional context**

**Comment by bluebill1049** [comment]
thanks, add to the feature board for waiting for upvote.

**Comment by bluebill1049** [comment]
this is actually a duplicated feature request.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/6697

**Comment by bluebill1049** [comment]
you can do this 

```
const { formState: { touchedFields, errors } } = useForm({
  mode: 'onChange'
})

{touchedFields.xxx && !errors.xxx} // this is a valid field
```

**Comment by Pavinati** [comment]
Maybe i didn't express myself clearly, I was not searching for a single field check but a more generic "was the whole form validated at least once?".
I don't care about the result of the validation at this stage, I'll use the `error` object field by field to check if there were errors

**Comment by bluebill1049** [comment]
"was the whole form validated at least once?" 

is that a field level or form level? if form level: at the moment `isSubmitted` does that to check if a form is submitted with or without error.

**Comment by Pavinati** [comment]
Thinking about it, I think I was stuck in a anti-pattern.
I shouldn't expect a whole form check when mode is not "onSumbit".
When using "onChange" or "onTouched" I should stick with field by field checks.

**Comment by bluebill1049** [comment]
That's right. `onChange` or `onTouched` sounds better for your validation strategy.
