### ISSUE TITLE
issue: useController onBlur overwrites onChange value when used in same render

### ISSUE THREAD

**Issue by brandonwestcott** [react-hook-form/react-hook-form#7007]
### Version Number

7.19.1

### Codesandbox/Expo snack

https://codesandbox.io/s/quirky-hodgkin-gy5vf?file=/src/App.tsx

### Steps to reproduce

Hello, first off thank you for all the work in this amazing library - its my go to form lib in react.

I'm having an issue with `onBlur` overwriting the previous `onChange` value when both methods are called within the same render cycle. My actual use case is integration with ionic picker component where I desire to set the value and close/blur the picker on "Done". I've built a reduced (and somewhat contrived ) example below using a regular controlled input:

1) Visit https://codesandbox.io/s/quirky-hodgkin-gy5vf?file=/src/App.tsx
2) Type: `123` in foo input
3) The controlled input retains `123` as its value, however the form state contains `12`
4) Given form state is `12`, hitting submit processes validation with the `12` value 

Note this only happens inside of the same render. As expected, forcing a separate render step (ex `doBlur`) will use the correct form state value from the last `onChange` execution. Maybe this is intended behavior, but I will note it was counterintuitive to me and took a bit of time to track the root cause.

### Expected behaviour

Calling `onBlur` from `useController` should use the most recent value provided inside of `onChange`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for the detailed issue report, onBlur is not supporting sending any update. It should only notify the onBlur event and update `formState` touched in react hook form.

https://github.com/react-hook-form/react-hook-form/blob/18c0b6d40fc32650c506435c6006d222713e9af1/src/useController.ts#L87

and this is going to be a problem which confused with react hook form which event is it sending down, which should be an `onChange` event but sent a signal as onBlur.

**Comment by bluebill1049** [comment]
aha, found a workaround

```
onChange={(evt) => {
  if (evt.target.value?.length >= 3 && inputRef.current) {
    inputRef.current.blur();
  }
  onChange(evt); // so hook form know it's a onChange event before the onBlur is fired
}}
```

👍

**Comment by brandonwestcott** [comment]
👍 thanks @bluebill1049. The way my "real" code was organized I hadn't even thought to try blur -> onChange.

After digging in _very_ slightly to the source here, I'm wondering if it makes sense to omit `value` from https://github.com/react-hook-form/react-hook-form/blob/18c0b6d40fc32650c506435c6006d222713e9af1/src/useController.ts#L87-L95

And instead switch https://github.com/react-hook-form/react-hook-form/blob/18c0b6d40fc32650c506435c6006d222713e9af1/src/logic/createFormControl.ts#L635-L636 to pull from field value if its a blur? Ex:
```js
const isBlurEvent = event.type === EVENTS.BLUR;
const fieldValue = (target.type || isBlurEvent) ? getFieldValue(field._f) : target.value;
```

**Comment by bluebill1049** [comment]
then it will issue an regression #6481
