### ISSUE TITLE
issue: calling reset function cause error for antd controlled  DatePicker 

### ISSUE THREAD

**Issue by vuthpov** [react-hook-form/react-hook-form#7013]
### Version Number

7.19.3

### Codesandbox/Expo snack

https://codesandbox.io/s/gracious-butterfly-h6ijd?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/gracious-butterfly-h6ijd?file=/src/App.js.
2. Change DatePicker value
3. Click on reset button

### Expected behaviour

I expect the form to have default values after calling reset function.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
instead of supply moment custom object to the form value, try to use string formate stead.
