### ISSUE TITLE
issue: isValid re-trigger validation for each field

### ISSUE THREAD

**Issue by FlorianBurgevin** [react-hook-form/react-hook-form#7027]
### Version Number

7.9.0

### Codesandbox/Expo snack

https://codesandbox.io/s/confident-chandrasekhar-dxy6b?file=/src/App.js

### Steps to reproduce

1. Focus a field and blur it
2. Check the Console
3. See that the 3 validators are triggered on each blur even if not the same field

Each validator is called multiple time (3 times for 3 fields here).

My problem is that if I have a async validator that calls an API, my API will be flooded.

### Expected behaviour

Hello,

I think the validation should only happen on the focused/blured field.

I have an async validation and I don't want to flood my API every time something happen on a field.

So, I can't disable my validation field based on the isValid.

Do you have a solution for that ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is expected behavior, for `isValid` formState, the entire form needs to be validated.

**Comment by FlorianBurgevin** [comment]
Ok.

But is it expected that validation is trigered as many times as the number of field (3 in the sandbox), when a field is blured, or touched ?

How can I disable my submit button without re-calling a lot of times my API if I can't use the isValid ?

**Comment by bluebill1049** [comment]
I think we can optimise skip that blur validation, but each inputs will need to be validated to generate isValid.

**Comment by FlorianBurgevin** [comment]
For the first render yes for sure.

But then, if the value of a field don't change, maybe it's not necessary to revalidate all.
The isValid could be recalculated only when a field change with this field, because all the other values don't change ?

**Comment by bluebill1049** [comment]
> But then, if the value of a field don't change, maybe it's not necessary to revalidate all.

we don't have such a mechanism at the moment.

**Comment by FlorianBurgevin** [comment]
Ok :(

So, do you have an other way for me to do my validations ?

**Comment by bluebill1049** [comment]
you will have to trigger those validation manually before this feature flags gets implemented: https://github.com/react-hook-form/react-hook-form/projects/1

**Comment by bluebill1049** [comment]
in fact, if you have async validation and need to trigger on the form level, you may want to look into resolver with one of those schemas.

**Comment by FlorianBurgevin** [comment]
Thanks I will follow the mentionned issue.

**Comment by gicontz** [comment]
I came here to thank you for this issue that gave me an idea in order to solve my problem. 
My issue is the `isValid` and `'isDirty` flags are not updating properly during callback functions which made me frustrated on how to track multiple form errors. 
I have a single form that has a validation using Yup, and it is used in FE as an array of it.
i tried to solve this on our application and here's what i've done (it took me whole day to come up on this idea haha)

```typescript
myValidationSchema // is from Yup validation schema
```

```typescript
const areInputsValid = async (data: MyObject[]): Promise<boolean> => {
    const validations = await Promise.all(data.map(async () =>  {
    try {
        await myValidationSchema.validate(myobj);
        return true;
    } catch (e) {
        return false;
    }
    } );
 return !validations.includes(false);
}
```
