### ISSUE TITLE
formState.isDirty is true without any fields being dirty

### ISSUE THREAD

**Issue by ryanmk54** [react-hook-form/react-hook-form#7028]
### Version Number

7.19.3

### Codesandbox/Expo snack

https://codesandbox.io/s/reverent-cartwright-ydvtf?file=/src/App.tsx

### Steps to reproduce

1. Notice the "Submit Query" button is disabled
2. Click on the "First Name" text field
3. Click off the "First Name" text field
4. Notice the "Submit Query" button is enabled, even though dirty is false in the DevTool

### Expected behaviour

On the [form state](https://react-hook-form.com/api/useform/formstate) page, it says:

isDirty - Set to true after the user modifies any of the inputs
dirtyFields - An object with the user-modified fields

Based on the above, isDirty should only be true if there is at least one dirty field.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
<img width="746" alt="Screen Shot 2021-11-11 at 11 54 47 am" src="https://user-images.githubusercontent.com/10513364/141217490-b294a78e-d401-4931-8c37-a6a6817852c5.png">

- this sort of issue is mostly due to missing `defautlValues`

**Comment by bluebill1049** [comment]
> Make sure to provide all inputs' defaultValues at the useForm, so hook form can have a single source of truth to compare whether the form is dirty.

https://react-hook-form.com/api/useform/formstate

<img width="937" alt="Screen Shot 2021-11-11 at 11 55 45 am" src="https://user-images.githubusercontent.com/10513364/141217567-d23bb24c-46e1-47ce-8d53-c8c86adb0a02.png">

**Comment by ryanmk54** [comment]
I'm sorry. I didn't provided the default values to useForm correctly.
firstName isn't a valid key for useForm. How did Typescript not catch that?

By the way, thank you for making the documentation mobile friendly.

**Comment by bluebill1049** [comment]
It did pick it up, see the screenshot above.
