### ISSUE TITLE
watch doesn't return all values

### ISSUE THREAD

**Issue by tafelito** [react-hook-form/react-hook-form#703]
**Describe the bug**
when doing this 
```js
const watchFields = watch(['shipping.save'], {
    'shipping.option': 'new',
  });
```
only returns the shipping.save value 

it does work doing 
```js
const saveShipping = watch('shipping');
```
the problem with this is that it will re-render for any change on the form and there is no way to set up 

or 
```js
const newShipping = watch('shipping.option', 'new');
const saveShipping = watch('shipping.save', 'false');
```
the problem with this is that it will re-render multiple times

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-basic-8q5nr

**Expected behavior**
return both watch values with their defaults

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] any

**Comment by bluebill1049** [comment]
```
const watchFields = watch(['shipping.save', 'shipping.option'], {
    'shipping.option': 'new',
  });
```
?

**Comment by tafelito** [comment]
that works! thanks @bluebill1049

**Comment by bluebill1049** [comment]
nice! it is in the doc: https://react-hook-form.com/api/#watch
