### ISSUE TITLE
issue: types are broken for errors object when using arrays or objects

### ISSUE THREAD

**Issue by TheMeteoRain** [react-hook-form/react-hook-form#7030]
### Version Number

7.19.4

### Codesandbox/Expo snack

https://codesandbox.io/s/green-sun-bkkkl?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/green-sun-bkkkl?file=/src/App.tsx
2. Try to use intellisense for error object. line: 19
3. Next you can press submit and look at console.log
4. The underlying object is still the same old error type with message, type, etc.

Typescript infers the error object wrong.

The example uses FormValues with value set as `string[]` but you can change it to as well `Record<string, string>`
This very same configuration worked in version: 7.14.2

You can change version to 7.14.2 -> typescript understands its an array. 
Though I don't know how errors are set if the real value is array.
In this case the real value is simple string.

You can change FormValues value to string -> error object is actually what it's suppose to be.

### Expected behaviour

Typescript should work for error object, even when FormValues value is set as array or object.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
We have to make a tradeoff on the type check here, it is almost difficult/impossible for hook form to type check if it's a single input that has a value of array, or array of inputs. That is why we had `NestedValue` for input with array/object value.

`7.14.2` certainly has other issues, which is why we have improved  overtime so it covers more generic use cases.

**Comment by TheMeteoRain** [comment]
I see, so if I just use NestedValue to wrap my object and array types I'm in good again.
Just tested it, seems like it. If this is intented, you can just close this as resolved.

**Comment by bluebill1049** [comment]
It's a tradeoff we have to make to support `UnionLIke` and `DeepMap`, the old version works because it only support `DeepPartial`.

**Comment by TheMeteoRain** [comment]
Though it makes me think why it's not done automatically under the hood, or is that kinda hard?

**Comment by bluebill1049** [comment]
> Though it makes me think why it's not done automatically under the hood, or is that kinda hard?

I don't think it's possible to predict (without runtime): if it's a single input that has a value of array, or array of inputs. if you have better idea, feel free to submit a PR. 👍

**Comment by TheMeteoRain** [comment]
Nice to know I can at least handle this situation with current tools. Maybe I will take look at the types, if something can be done, but otherwise thank you for your time ❤️
