### ISSUE TITLE
issue: fast refresh Form Error Doesn't Appear After Submitting Invalid Form Values

### ISSUE THREAD

**Issue by Moshyfawn** [react-hook-form/react-hook-form#7031]
### Version Number

7.19.4

### Codesandbox/Expo snack

https://codesandbox.io/s/rhf-validation-error-issue-xvfmj

### Steps to reproduce

1. Go to [rhf-validation-error-issue codesandbox](https://codesandbox.io/s/rhf-validation-error-issue-xvfmj)
2. Click on submit button
3. Don't see email field error message due to empty field validation error underneath the email input

or

1. Go to [rhf-validation-error-issue codesandbox](https://codesandbox.io/s/rhf-validation-error-issue-xvfmj)
2. Enter some string into email input with invalid email format
3. Click on submit button
4. Don't see email field error message due to invalid email format validation error underneath the email input

### Expected behaviour

Validation error appear underneath the email input after submitting an empty or invalid email value

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
It looks like the first version of RHF where the expected behavior breaks for me is `7.19.0`.

**Comment by cuddlecake** [comment]
It seems to work just fine for me on initial render.

If I make a change to the code, and the page hot reloads, then there seem to be no more re-renders on submit after the initial re-render.

**Comment by Moshyfawn** [comment]
> It seems to work just fine for me on initial render.
> 
> If I make a change to the code, and the page hot reloads, then there seem to be no more re-renders for errors on submit.

**Comment by Moshyfawn** [comment]
> It seems to work just fine for me on initial render.
> 
> If I make a change to the code, and the page hot reloads, then there seem to be no more re-renders for errors on submit.

Yeah, you're right. I couldn't consistently reproduce the issue ones I've re-opend the sandbox. I get it every time In my project on a local machine, since it reloads a couple of times after the initial build, so I couldn't tell.
