### ISSUE TITLE
issue: useController – using field.onBlur() to validate the input can provide an older value to the validate function

### ISSUE THREAD

**Issue by giovannipiller** [react-hook-form/react-hook-form#7032]
### Version Number

7.19.4

### Codesandbox/Expo snack

https://codesandbox.io/s/tender-frost-3d00y?file=/src/App.tsx

### Steps to reproduce

1. Go to [codesandbox](https://codesandbox.io/s/tender-frost-3d00y?file=/src/App.tsx)
2. Open the console
3. Click "CLICK HERE"
4. validation will run with "starting value" (which is the defaultValue)
5. Click again "CLICK HERE"
6. validation will finally run with "updated value"

### Expected behaviour

This used to work fine up until v7.15.0.
Meaning that the issue has been **introduced with v7.15.1**, possibly with [this change](https://github.com/react-hook-form/react-hook-form/compare/v7.15.0...v7.15.1#diff-3f5bdfa7d822b4562b8e1c72dd1996197fe93478b039779bb78853ab3ae2a3feR98) to the `useController`.

1. Go to [codesandbox](https://codesandbox.io/s/flamboyant-ganguly-6rhdy?file=/src/App.tsx)
2. Open the console
3. Click "CLICK HERE"
4. validation will run with "updated value"
5. Click again "CLICK HERE"
6. validation will finally run with "updated value"

**Disclaimer**
I'm aware that it makes little sense to write code like this, using a `<span>` to act as a `<button>`.
I've just done so to provide a succinct test scenario.
In most real-life scenarios, the `field.onChange(....)` and `field.onBlur()` could likely be replaced with a `setValue(...)`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`onBlur` does not update field/input value, you can switch the order of onChange to last to solve this issue.

```
onClick={() => {
  field.onBlur();
  field.onChange("updated value");
}}
```

**Comment by giovannipiller** [comment]
Hi @bluebill1049, thanks for checking this out.

> `onBlur` does not update field/input value, you can switch the order of onChange to last to solve this issue.

I tried doing that, with similar results:
https://codesandbox.io/s/dry-tree-nol8q?file=/src/App.tsx

Note that In these example, the form is set to `mode: "onBlur"`, so I'd guess that performing the `onBlur` before the `onChange` would lead to a validation being run with outdated value.
You can reproduce the correct behaviour by interacting with the "setValue" button.

The same example works on 7.15.0, but not for the "blur, then change" scenario. Which I think it's fine, in theory.
https://codesandbox.io/s/morning-sea-evs8v?file=/src/App.tsx

Am I missing something?

**Comment by bluebill1049** [comment]
hi @giovannipiller instead of focusing on `onBlur/onChange` API which has behavior influence, maybe we can use `setValue` instead?

`setValue('user.name', "updated value", { shouldValidate: true });`

**Comment by giovannipiller** [comment]
Sure, I can use `setValue` in this example.
However, assuming this is the correct behaviour for `onBlur/onChange`, I think this should be considered a breaking change which was probably unnoticed.

I get it that `setValue` is the best way to programmatically.... set a value (😄) and trigger validation, but it used to work the other way as well.
I can for sure update all my affected components to use `setValue`, although it will mean using `useFormContext` in addition to the `useController`.

Not a big deal, but a change for sure.
It just seems odd that calling `onChange` followed by `onBlur` should trigger a validation with an obsolete value.

Feel free to close if this is the expected behaviour.

Thanks 😊

**Comment by bluebill1049** [comment]
This is the change that I can trace down: https://github.com/react-hook-form/react-hook-form/pull/6481 which i think it's valid case for the bug fix, let me know if you think otherwise or we can have better strategy to fix it without having the issue above.

**Comment by giovannipiller** [comment]
I just noticed that my issue is pretty much the same as #7007.
Not sure what can be done to solve both this scenario and #6481.

I'll try to investigate a bit more, but it might take me a few days.

**Comment by bluebill1049** [comment]
hey, @giovannipiller just a quick follow up, any update on this issue 🙏

**Comment by giovannipiller** [comment]
Hi @bluebill1049, nothing tangible really. Closing this issue for the time being.

**Comment by bluebill1049** [comment]
found solution: https://codesandbox.io/s/great-tdd-lbzzr?file=/src/App.tsx:463-553

**Comment by giovannipiller** [comment]
thank you @bluebill1049 for taking a second look at this,
tested on some of my older code and everything seems to be working as expected!
