### ISSUE TITLE
issue: Type of errors is not usable when TFieldValues receives a generic type

### ISSUE THREAD

**Issue by cornedor** [react-hook-form/react-hook-form#7040]
### Version Number

7.19.5

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-errors-type-xxp63

### Steps to reproduce

1. Look at line 42, firstname is read from the errors object.
2. Look at line 50, name can only be "firstname" or "lastname" as expected.
3. Look at line 23, while name can only be firstname or lastname (which are valid properties on this errors object) a type error is thrown.

### Expected behaviour

It is possible to retrieve a property from the errors object when TFieldValues is set to a Generic while keeping type safety.

### Relevant log output

```shell
const errors: DeepMap<DeepPartial<UnionLike<TFieldValues>>, FieldError>

Type 'Path<TFieldValues>' cannot be used to index type 'DeepMap<DeepPartial<UnionLike<TFieldValues>>, FieldError>'.ts(2536)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for the issue report, both I and @kotarella1110 have looked at this issue for some time, looks like this is a limitation of the type check. for work around use as string.

`const fieldError = errors[name as string];`
