### ISSUE TITLE
issue: handleSubmit() returns all the fields from defaultValues even though not registered

### ISSUE THREAD

**Issue by PraveenPeri** [react-hook-form/react-hook-form#7048]
### Version Number

7.19.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-controller-forked-o29mm

### Steps to reproduce

1. Go to the attached sandbox
2. Notice the "_unregisteredField" in the defaultValues JSON that's not rendered in the form
3. Click on 'Submit' button to display submitted data and notice that it contains the '_unregisteredField' though we did not explicitly register it

### Expected behaviour
I have a multi-step form with defaultValues json passed to it. The JSON contains all the fields appearing in all the steps. However, we show only a subset of those fields per step and they will be posted to the API as the user continues to the next step. We are using component to render Material UI components on our form. We noticed that the data returned to the handleSubmit() hook contains all the fields from all the steps instead of just the ones on the current step. Our expectation was that since only the fields on the current step are registered with the form, the submit handler will only receive those fields but that's not the case. Is this a but? Am I misunderstanding the behavior? What should we do to receive only the current step's fields in the handler?

### What browsers are you seeing the problem on?

Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> defaultValues will be included in the submission result by default, if this is not the desired behaviour use shouldUnregister: true instead which means inputs will host all input values.

![Screen Shot 2021-11-14 at 1 36 45 pm](https://user-images.githubusercontent.com/10513364/141665225-04d02f39-7168-4cd9-9a69-88524a1ab3c7.png)

**Comment by PraveenPeri** [comment]
Why don't see that point here in the documentation? 
https://react-hook-form.com/api/useform

**Comment by bluebill1049** [comment]
> Also, what does "input will host all input values" mean? 

so input get unmount will remove just like shouldUnregister: true, will update the wording.

**Comment by PraveenPeri** [comment]
Thanks for the response! Appreciate the help. I see your update in the documentation too :). 
Just a side note, I love react-hook-form. Cheers!

**Comment by bluebill1049** [comment]
no worries @PraveenPeri more references in case others see this issue.

## shouldUnregister: false (default)

`defaultValues` will be your form's `formValues` and then user action will update the `formValues`, so it's a store for hosting the input values.

## shouldUnregister: true

input value will stay within each field, so when the field unmount then the input value will be removed (the behaviour is similar to native form)
