### ISSUE TITLE
issue: useFieldArray append: TypeError: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by orszaczky** [react-hook-form/react-hook-form#7050]
### Version Number

7.19.5

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-lvj9d?file=/src/index.js

### Steps to reproduce

1. Open attached codesandbox link
2. Click on 'Append'
3. See error:
TypeError
Cannot read properties of undefined (reading 'startsWith')

Uncaught TypeError: Cannot read properties of undefined (reading 'startsWith')
    at useFieldArray.ts:301
    at focusFieldBy (focusFieldBy.ts:19)
    at useFieldArray.ts:301

### Expected behaviour

Should be able to append field without an error

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
useFieldArray.ts:301 Uncaught TypeError: Cannot read properties of undefined (reading 'startsWith')
    at useFieldArray.ts:301
    at focusFieldBy (focusFieldBy.ts:19)
    at useFieldArray.ts:301
    at invokePassiveEffectCreate (react-dom.development.js:23487)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at HTMLUnknownElement.dispatchEvent (<anonymous>)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at flushPassiveEffectsImpl (react-dom.development.js:23574)
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushPassiveEffects (react-dom.development.js:23447)
    at react-dom.development.js:23324
    at workLoop (scheduler.development.js:590)
    at flushWork (scheduler.development.js:545)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:157)
(anonymous)	@	useFieldArray.ts:301
focusFieldBy	@	focusFieldBy.ts:19
(anonymous)	@	useFieldArray.ts:301
invokePassiveEffectCreate	@	react-dom.development.js:23487
callCallback	@	react-dom.development.js:3945
invokeGuardedCallbackDev	@	react-dom.development.js:3994
invokeGuardedCallback	@	react-dom.development.js:4056
flushPassiveEffectsImpl	@	react-dom.development.js:23574
unstable_runWithPriority	@	scheduler.development.js:646
runWithPriority$1	@	react-dom.development.js:11276
flushPassiveEffects	@	react-dom.development.js:23447
(anonymous)	@	react-dom.development.js:23324
workLoop	@	scheduler.development.js:590
flushWork	@	scheduler.development.js:545
performWorkUntilDeadline	@	scheduler.development.js:157
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by orszaczky** [comment]
Also getting this warning in the console (see in codesandbox):

Warning: Unexpected ref object provided for input. Use either a ref-setter function or React.createRef().
    in input (at src/index.js:44)
    in li (at src/index.js:43)
    in ul (at src/index.js:40)
    in form (at src/index.js:36)
    in App (at src/index.js:124)

**Comment by rodrigofuentes** [comment]
This looks to be because you didn't pass the required string to the register function. 

```diff
          <input
           name={`test.nested[${index}].firstName`}
           defaultValue={`${item.firstName}`} // make sure to set up defaultValue
-          ref={register()}
+          ref={register(`test.nested[${index}].firstName`)}
         />

         <input
           name={`test.nested[${index}].lastName`}
           defaultValue={`${item.lastName}`} // make sure to set up defaultValue
-          ref={register()}
+          ref={register(`test.nested[${index}].lastName`)}
         />
         <button type="button" onClick={() => remove(index)}>
           Delete
```

Once you pass that in , should work as intended.

**Comment by bluebill1049** [comment]
Thanks @rodrigofuentes ❤️

**Comment by orszaczky** [comment]
Thanks guys, indeed, I found an older codesandbox example floating around, using the old syntax (https://codesandbox.io/s/vy8fv?file=/src/index.js). Updating the syntax fixed the issue. 🙏

**Comment by fernandocieri** [comment]
> @orszaczky This looks to be because you didn't pass the required string to the register function.
> 
> ```diff
>           <input
>            name={`test.nested[${index}].firstName`}
>            defaultValue={`${item.firstName}`} // make sure to set up defaultValue
> -          ref={register()}
> +          ref={register(`test.nested[${index}].firstName`)}
>          />
> 
>          <input
>            name={`test.nested[${index}].lastName`}
>            defaultValue={`${item.lastName}`} // make sure to set up defaultValue
> -          ref={register()}
> +          ref={register(`test.nested[${index}].lastName`)}
>          />
>          <button type="button" onClick={() => remove(index)}>
>            Delete
> ```
> 
> Once you pass that in , should work as intended.
> 
> @bluebill1049 you can close this.

I did this and it works but I'm still getting the waring @orszaczky mentioned. Any fixes?

**Comment by fernandocieri** [comment]
qsqsqs

**Comment by fernandocieri** [comment]
h

**Comment by JarnoRFB** [comment]
@orszaczky Updating the examples would be great, I was also confused after following https://codesandbox.io/embed/react-hook-form-usefieldarray-nested-arrays-x7btr . @bluebill1049 are the codesandbox examples somehow part of the repositroy? Then the community could update them.

**Comment by bluebill1049** [comment]
@JarnoRFB yes they r, let me know the fix I can get them updated.

**Comment by JarnoRFB** [comment]
@bluebill1049 the main change is just using the newer register API, instead of passing name and ref separately. I made the changes that I think are necessary to a fork of the sandbox https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-vpdquk?file=/src/fieldArray.js
