### ISSUE TITLE
issue: useFieldArray keyName doesn't accept anything but 'id'

### ISSUE THREAD

**Issue by andrei9669** [react-hook-form/react-hook-form#7054]
### Version Number

7.4.1

### Codesandbox/Expo snack

https://codesandbox.io/s/kind-faraday-3phd1?file=/src/App.tsx

### Steps to reproduce

1. Go to App.tsx
2. See error: Type '"iddd"' is not assignable to type '"id" | undefined'

### Expected behaviour

no type error

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
you don't need to assign the generic: 

```
const fieldArray = useFieldArray({
  control,
  name: "names",
  keyName: "iddd"
});
```

**Comment by andrei9669** [comment]
ooh, so the field types come from control? That's neat.

okay, but what if I'm using FormProvider? and context is so to say automatic there. then I don't have to set the control but I also don't get the type safety without setting the generic.
