### ISSUE TITLE
issue: can't retrieve value for function component which can't have ref assigned since 7.14.1

### ISSUE THREAD

**Issue by twhoff** [react-hook-form/react-hook-form#7055]
### Version Number

7.14.1

### Codesandbox/Expo snack

-

### Steps to reproduce

In the previous version (7.14.0) we were able to get the value of form components from our internal component library (function components wrapped with React.forwardRef() which eventually passes to a regular `<input ref={ref} />`).

Our component looks something like:
```
<TextInput {...register('username')} />
```

This component has always caused the follow warning in the console:
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

However, the handleSubmit function was still able to retrieve the values from the form prior to version 7.14.1.

Recently I had to clear the node_modules folder and ended up with react-hook-forms 7.19.5 (I think) and the issue started happening where the values from the form started coming back as `undefined`.

Digging through the source code I can see changes were made in 7.14.1 to `createFormControl.ts` and I think the issue might be on line 428:
![image](https://user-images.githubusercontent.com/4405822/141927813-4fd51cea-1cdd-40d6-9baf-04198a008b2d.png)

Can you please confirm if this update would cause reach-hook-form to stop retrieving values from the form if a ref can't be assigned and why it worked previously?

Also, if this is not a bug, what is the correct way to go about using react-hook-form with a function component which can't have a ref assigned?

### Expected behaviour

handleSubmit function should retrieve values from function component inputs as this worked in previous versions.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by twhoff** [comment]
Hi Bill, sorry, I'm not able to follow the template on this one, it's difficult to describe, the use case is probably an edge case, but it's caused because we have an internal component library which uses function components, and there is a regression in the react-hook-form source code.

I've put a lot of effort digging into the versions to locate exactly where I believe the regression is to minimise effort on your part - could you please take a look? I think the report has all the information you need...

**Comment by bluebill1049** [comment]
can you provide a codesandbox to reproduce this issue? 

if your input is forward the `ref` /uncontrolled component then you should use Controller, as it needs to be wrapped with state update. 

https://react-hook-form.com/get-started#Integratinganexistingform

for uncontrolled input, should always forward the ref, so hook form can update value and focus on the input.

**Comment by twhoff** [comment]
Hi Bill, thank you for your comment, I've created a codesandbox and linked in the issue above - can you please take a look?

The pattern the StyleGuide uses is NamedInput implements NamedInputWithRef implements TextInput implements input - it seems totally weird to me, but you can see in the console the Warning and that the value comes back as `undefined`.

The reason I've raised this issue though, is because it doesn't happen in 7.14.0 (even though the warning is there) - the value comes back as expected - so I think it is a regression?

**Comment by twhoff** [comment]
If you change the version number for react-hook-form in codesandbox and try the example you will see what I mean

**Comment by bluebill1049** [comment]
thanks for the updated codesandbox. You will need to forward the ref, otherwise, it's going to other unexpected issues. the latest version is the expected behavior.

**Comment by twhoff** [comment]
Any ideas why it worked in the previous version though (7.14.0)?

**Comment by bluebill1049** [comment]
It worked due to a bug and incorrect usage, for uncontrolled input, input reference is required. there is no way for react hook form to update/reset or focus input without the ref. I would adjust your input component or use Controller instead.
