### ISSUE TITLE
issue: Controller field spread operator not working for focus on error

### ISSUE THREAD

**Issue by FloforPresident** [react-hook-form/react-hook-form#7059]
### Version Number

7.16.2

### Codesandbox/Expo snack

https://codesandbox.io/s/ref-width-spread-operator-cs2vl?file=/src/App.tsx

### Steps to reproduce

1. Go to Sandbox link
2. Type a value smaller than 9 and Submit
3. The error textfield will not be focused
4. Comment out spread operator in line 23 and comment in line 24-27
5. The textfield will be focused this way 

### Expected behaviour

Text fields should have the correct configuration using the spread operator (I guess Ref is missing here?)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
not really much we can do, when different external component forward `ref` with different names, react hook form only refer to the name `ref`
