### ISSUE TITLE
React Select is not selectable i cannot select any value

### ISSUE THREAD

**Issue by khanakia** [react-hook-form/react-hook-form#706]
**Describe the bug**
When you select any value from REACT SELECT it does not shows the selected value on React Select.

**To Reproduce**
1. Go to https://react-hook-form.com/api#Controller
2. Click on Codesandbox
3. Scroll down to React Select
4. try to select any value from the dropdown you will not be able to select any value

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-rhfinput-00pm9

**Expected behavior**
On selecting the value from dropdown it should show value on React Select

**Screenshots**

**Desktop (please complete the following information):**
 - OS: LINUX
 - Browser CHROME, SAFARI
 - Version 79

**Smartphone (please complete the following information):**
 - Device: DESKTOP
 - OS: CHROME
 - Browser CHROME
 - Version N/A

**Additional context**

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-hookforminput-rzu9s see example in here, see if this example helps.

**Comment by bluebill1049** [comment]
thanks @khanakia for report this issue, i have updated the code example: 
https://codesandbox.io/s/react-hook-form-hookforminput-rzu9s

because react-select is not return standard onChange event, so we need to return the expected value, which is `{ value: selectedOption }`

https://codesandbox.io/s/react-hook-form-hookforminput-rzu9s

**Comment by bluebill1049** [comment]
you can use the `onChange` prop: https://react-hook-form.com/api#Controller

**Comment by khanakia** [comment]
Hi Bill,

That's working now. Also, the default value is not working for ReactSelect **and** also when i submit the data it returns the ReactSelect Object not the raw value.
Check example please
https://codesandbox.io/s/react-hook-form-rhfinput-00pm9

**Comment by bluebill1049** [comment]
`ReactSelect: { value: "vanilla", label: "Vanilla" }`

**Comment by khanakia** [comment]
Ok, but how do i set the default value?
this is not working.
```
const defaultValues = {
  ReactSelect: "vanilla"
};
```

https://codesandbox.io/s/react-hook-form-rhfinput-00pm9

**Comment by khanakia** [comment]
Hi ,
I am setting the defaultValue for REACT SELECT using
```
value={{ value: "vanilla", label: "Vanilla" }}
```
When i click the button it says FIELD REQUIRED.
Please check the sandbox link
https://codesandbox.io/s/react-hook-form-rhfinput-00pm9

**Comment by bluebill1049** [comment]
hey @khanakia use defaultValue instead of value, value gets controlled by the Controller

**Comment by khanakia** [comment]
I cannot use defaultValue as i have a dynamic form so it does not update the value. I want to get the values via AJAX and then set it to form something like this. 
Please check the sandbox again i just updated the code how do i want
https://codesandbox.io/s/react-hook-form-rhfinput-00pm9

**Comment by bluebill1049** [comment]
use setValue then

**Comment by khanakia** [comment]
Thanks it worked :)

**Comment by bluebill1049** [comment]
I would recommend you to read through our documentation website, we have spend a lot of effort to make it available for everyone. https://react-hook-form.com/api

**Comment by algebrathefish** [comment]
@bluebill1049 it seems like for the new version you may need to do: onChange={([selected]) => {
                return selected;
              }}

**Comment by bluebill1049** [comment]
no u dont need onChange for react-select now. @algebrathefish

**Comment by DeepeshKr** [comment]
@khanakia it works if set the defaults values like this:
```
function App() {
  const { handleSubmit, register, errors, control, setValue } = useForm({
      defaultValues: { 
        ReactSelect: { value: "vanilla", label: "Vanilla" }
      }
  });
```

**Comment by usmansabir98** [comment]
> @bluebill1049 it seems like for the new version you may need to do: onChange={([selected]) => {
> return selected;
> }}

Actually you are right. My react-select was not working (i.e. it wasn't displaying the selected value. Had to do the following to get it to work. I request the admin to please update the docs.

<Controller
    as={<Select placeholder="Select Brand" className="mt-4"/>}
    name="brand"
                        control={control}
                        options={brands}
                        onChange={([selected]) => {
                          // React Select return object instead of value for selection
                          return selected;
                        }}
                        defaultValue={values.brand}
                      />

**Comment by bluebill1049** [comment]
> > @bluebill1049 it seems like for the new version you may need to do: onChange={([selected]) => {
> > return selected;
> > }}
> 
> Actually you are right. My react-select was not working (i.e. it wasn't displaying the selected value. Had to do the following to get it to work. I request the admin to please update the docs.
> 
> <Controller
> as={Select}
> control={control}
> options={brands}
> onChange={([selected]) => {
> return selected;
> }}
> />

I maintain the doc as well, let me know which section it is or a screenshot will do. i will sort it out.

**Comment by usmansabir98** [comment]
> > > @bluebill1049 it seems like for the new version you may need to do: onChange={([selected]) => {
> > > return selected;
> > > }}
> > 
> > 
> > Actually you are right. My react-select was not working (i.e. it wasn't displaying the selected value. Had to do the following to get it to work. I request the admin to please update the docs.
> > <Controller
> > as={Select}
> > control={control}
> > options={brands}
> > onChange={([selected]) => {
> > return selected;
> > }}
> > />
> 
> I maintain the doc as well, let me know which section it is or a screenshot will do. i will sort it out.

In the section Working with UI Library. The approach "{value: selected}" no longer works. You have to return just the variable "selected" in this onChange listener to make it work. I have given an example in my previous comment 
![image](https://user-images.githubusercontent.com/28140807/85400544-03a0f200-b572-11ea-949d-d456a583b464.png)

**Comment by bluebill1049** [comment]
thanks @usmansabir98 fixed in the v6 doc should be released early next week. 

<img width="569" alt="Screen Shot 2020-06-23 at 9 58 59 pm" src="https://user-images.githubusercontent.com/10513364/85401060-c00fad80-b59c-11ea-8225-9a9c603056a4.png">

**Comment by usmansabir98** [comment]
> thanks @usmansabir98 fixed in the v6 doc should be released early next week.
> 
> <img alt="Screen Shot 2020-06-23 at 9 58 59 pm" width="569" src="https://user-images.githubusercontent.com/10513364/85401060-c00fad80-b59c-11ea-8225-9a9c603056a4.png">

That's great. You're doing a great job. Thanks
