### ISSUE TITLE
issue: reset(undefined, { keepValues: true, keepDefaultValues: false}) is not resetting defaultValues to current values

### ISSUE THREAD

**Issue by cpitt** [react-hook-form/react-hook-form#7064]
### Version Number

v7.19.5

### Codesandbox/Expo snack

https://codesandbox.io/s/reset-default-values-bug-imnc1?file=/src/App.js

### Steps to reproduce

In code sandbox

1. Modify input field by typing into it
1. Click 'reset keep values' button
1. Observe defaultValues are not updated

### Expected behaviour

defaults should match current form values

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
is this what you after?

```
reset({
  ...getValues()
})
```

**Comment by cpitt** [comment]
Ok I guess I had an incorrect assumption.

I incorrectly assumed the following were equivalent

```
reset({...getValues()}, { keepDefaultValues: false })
```

```
reset(undefined, { keepValues: true, keepDefaultValues: false})
```

It seems like keepValues has no effect on defaultValues

**Comment by bluebill1049** [comment]
yes `keepValues` only keep values on the UI.

**Comment by cpitt** [comment]
Thanks makes sense
