### ISSUE TITLE
🙏🏻Help more international developers ❤️

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#709]
## Help more international developers
    
Building good open-source software is important, however, the ultimate goal is always helping more developers around the world. Most of our users are non-English background and it's important to translate to their native language to help them understand better. 
    
However, we need more help with other languages and also back up those solo translators: 
    
- 🇦🇺 English - Bill
- 🇨🇳 简体中文 - Bill
- 🇯🇵 日本語 - @kotarella1110 
- 🇰🇷 한국어 - @adhrinae 
- 🇫🇷 Français - @opeah
- 🇮🇹 Italiano - ??
- 🇧🇷 Português - @kevenleone
- 🇪🇸 Español - @Samushel 
- 🇷🇺 Русский - ??

https://github.com/react-hook-form/react-hook-form-website

**Comment by Samushel** [comment]
I'd like to help with Spanish.

**Comment by bluebill1049** [comment]
Thanks @Samushel That would be great amazing! Let me know if you need help on what to do. I did documented something on the readme file.

**Comment by opeah** [comment]
I'll help you in French

**Comment by bluebill1049** [comment]
That would be awesome! thank you @opeah

**Comment by cargallo** [comment]
@bluebill1049 remember that I proposed few weeks ago to help translating docs to spanish, and I proposed another structure for the docs. We could coordinate with @Samushel to bring it faster. Nowdays I'm bussy cause end of year things but glad to help after that.

**Comment by bluebill1049** [comment]
FYI @cargallo thanks i did improve the structure

**Comment by cargallo** [comment]
Hi @bluebill1049 here I am again 😄 Today I forked and started translating to spanish. I'm at 60% of the translation. @Samushel contact me if you want to help, to avoid overlaping the work in progress

**Comment by bluebill1049** [comment]
awesome thanks @cargallo

**Comment by cargallo** [comment]
Just the api.tsx page still remains to finish the spanish translation. I hope tomorrow I have time to finish it!

**Comment by bluebill1049** [comment]
thanks for the update @cargallo much appreciated your help!

**Comment by cargallo** [comment]
You're killing my free time deeply, but I'm glad to help 😄

**Comment by bluebill1049** [comment]
@cargallo I think what you are contributing here is totally worth. you are potentially helps hundreds and thousands developers out there. At least that's what i am passionate bout for making open source project as well ❤️ so thank you again 🏆

**Comment by ScreamZ** [comment]
I can also help in French

**Comment by bluebill1049** [comment]
thank you @ScreamZ 🙏

**Comment by SW999** [comment]
Hi @bluebill1049! I'd like to help with Russian.

**Comment by bluebill1049** [comment]
that would be awesome! thanks @SW999

**Comment by bluebill1049** [comment]
Let me know if you guys need more information on how to translate the website too. 🙏

**Comment by scherbo** [comment]
Can I join in to help with Russian?

**Comment by bluebill1049** [comment]
yes please @scherbo

**Comment by nicolastrote** [comment]
Can I join in to help with French?

**Comment by bluebill1049** [comment]
hey @nicolastrote that would be great! I don't think @opeah @ScreamZ have made a start on it. so I think you can start with the get started page, let me know if you need some help around how to start. thank you very much.

**Comment by nicolastrote** [comment]
Thanks for the state of art @bluebill1049. I will begin the translation, and push files per files, so perhaps @opeah and @ScreamZ could make the reviewers :)

**Comment by brigolini** [comment]
I can help translate to portuguese.

**Comment by bluebill1049** [comment]
Thanks @brigolini , i will attach you to the list and will ask you for help :)

**Comment by brigolini** [comment]
@bluebill1049 , I'm new on this so Sorry for the dummy question. Can I begin to make the translation? :)

**Comment by nicolastrote** [comment]
@bluebill1049 Yes you can :D For that you can read this article on how contribute : https://codeburst.io/a-step-by-step-guide-to-making-your-first-github-contribution-5302260a2940

**Comment by bluebill1049** [comment]
Yes @brigolini actually takes a look at the website under Portuguese, some of the sections are not translated.

**Comment by Paquan** [comment]
I could help with some german I guess. Is there any process, yet?

**Comment by bluebill1049** [comment]
thanks @Paquan i think there is a PR half baked and the author dropped for some reason. https://github.com/react-hook-form/react-hook-form-website/pulls

**Comment by Paquan** [comment]
> Yes @brigolini actually takes a look at the website under Portuguese, some of the sections are not translated.

Since it isn't my PR, can I commit something to it?

**Comment by LorenzHenk** [comment]
Hey @Paquan, I can push all the progress I made and you can take over if you want, I do have very little time at the moment.
The PR is here: https://github.com/react-hook-form/react-hook-form-website/pull/142
I do have some local progress on api.

@bluebill1049 Can you merge the current PR, so @Paquan can continue in his own fork?

**Comment by bluebill1049** [comment]
hey @LorenzHenk thanks for the update. I will merge the PR tonight.

**Comment by bluebill1049** [comment]
can you change from draft to actual PR? @LorenzHenk

**Comment by hernanG89** [comment]
Spanish available here.

**Comment by bluebill1049** [comment]
hey @hernanG89 thanks! I need Spanish translation help badly... did a lot of google translate. can you please take a look at this folder: https://github.com/react-hook-form/react-hook-form-website/tree/master/src/data/es didn't have to do them all, chunk by chunk will be awesome. thanks.
