### ISSUE TITLE
issue: watch deep input by their parent name

### ISSUE THREAD

**Issue by zakaoai** [react-hook-form/react-hook-form#7090]
### Version Number

since 7.19.4

### Codesandbox/Expo snack

https://codesandbox.io/s/sweet-cohen-gwsp6

### Steps to reproduce

1 Type in field and see that log and show result are not equal to the input value

### Expected behaviour

Expect that useWatch in render with parent name ("field" in sandbox) refresh at each input update of this parent

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
@zakaoai there is no generic been supplied either with `defaultValues` in your example.

`const { register, handleSubmit, control } = useForm();`

**Comment by zakaoai** [comment]
I update the sandbox with a defaultValues dont seem to get better. Since "react-hook-form": "7.19.4" when I type more than 1 character the render dont update and the log more than 2 and you don't get the updated value either.

**Comment by bluebill1049** [comment]
oh i got it, i was confused with type when i saw the keyword `deep`... too much typescript hahah

**Comment by zakaoai** [comment]
So when I watch the entire form the render update at each input but when I try to get my field with the group "field" that I made, useWatch seem to loose the value.
