### ISSUE TITLE
issue: Email pattern in quotes not working and email type not picking up invalid email

### ISSUE THREAD

**Issue by kuhlaid** [react-hook-form/react-hook-form#7091]
### Version Number

7.19.5

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-pattern-validator-bug-forked-m873h?file=/src/App.js

### Steps to reproduce

Using an email pattern wrapped in quotes does not work (I'm assuming since '\\' needs to be escaped to be valid JSON syntax). See below for example input field pattern:
```html
<input
          id="email"
          {...register("email", {
            required: "required",
            pattern: {
              value: "/^\\S+@\\S+\\.\\S+$/",
              message: "Entered value does not match email format"
            }
          })}
          type="email"
        />
```
The reason this is an issue is I am dynamically building forms based on a JSON configuration (for an entire form), so the pattern needs to be valid JSON in my case.

Also a value of `sdfd@asd` in the email type input box registers as a valid email even though it is an invalid email value (this is separate from the registered pattern issue above). Would expect the popup saying to `Please enter an email address` would not disappear if 'sdfd@asd' were entered.

### Expected behaviour

Expect patterns to accept valid JSON quoted values. Also for email input type to treat `asdf@asdf` as invalid email address (regardless of pattern entered).

As a side-note, I would assume you would want to use regex pattern `/^\S+@\S+\.\S+$/` in the email input type field and change the `\src\__tests__\logic\validateField.test.tsx` emailRegex pattern (which seems to be invalid).

- cheers (love this repository, thank you)

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kuhlaid** [comment]
I worked on a solution to this today and will submit a PR. It isn't ideal but it should be a starting point.

**Comment by bluebill1049** [comment]
> The regex pattern for the input.

the regex pattern needs a regex, we do not support `string`.
<img width="965" alt="Screen Shot 2021-11-20 at 9 25 28 am" src="https://user-images.githubusercontent.com/10513364/142699159-6d54e2d7-0185-4d4c-afcc-a0281f6bc80a.png">
