### ISSUE TITLE
JSON Pointer support (Feature Request)

### ISSUE THREAD

**Issue by loganvolkers** [react-hook-form/react-hook-form#7094]
**Is your feature request related to a problem? Please describe.**

It is impossible to edit objects with dots in their field names:

```
{
    "user":{
       "firstName": "Bob",
       "lastName": "Testerson"
    }
    "user.firstName": "hidden",
    "user.lastName": "visible",
}
```

1. There are a number of noted bugs and incompatibilities noted due to using dot notation for fields that may contain dots.
2. Dot notation is an incomplete standard for describing possible object structures
3. [JSON Pointer](https://datatracker.ietf.org/doc/html/rfc6901) support all possible object structures, has implementations in every language, and is used by a broad community, e.g. the Open API Specification and JSON Schema communities

**Describe the solution you'd like**

Allow field `name` parameters to be specified as a JSON pointer syntax, e.g. `register("/user.name")` or  `register("/user/name")`

**Describe alternatives you've considered**

Instead of adapting an RFC standard, a new standard could be created that fixes dot notation. There have been attempts in a few other languages using escape sequences, e.g.
 * [JSONata](https://jsonata.org/) format uses backticks e.g. ``` `user.firstName` ```
 * [JMESPath](https://jmespath.org/specification.html#identifiers) identifiers uses double quotes e.g. `"user.firstName"`

**Comment by bluebill1049** [comment]
thanks for the feature request. interesting one as well.
