### ISSUE TITLE
TypeError with FormState touched (nested objects)

### ISSUE THREAD

**Issue by Samushel** [react-hook-form/react-hook-form#710]
At the moment touched is handling the fields through an array of type `touched: FieldName<FormValues>[]` which saves property hierarchy with a string value using the types defined in useForm:

```typescript
interface User {
  name: string;
}
interface FormFields {
  user: User;
  password: string;
}

const { formState: { touched } } = useForm<FormFields>();

// When printing to console
touched: ['password', 'user.name']
```

But trying to access `user.name` will return a typescript error because it doesn't exist on FormFields. I was doing this before 4.0: 

```
touched.includes('user.name')
```

And now I get this error: 

```
TS2345: Argument of type '"user.name"' is not assignable to parameter of type '"user" | "password".
```

**Comment by bluebill1049** [comment]
Can you please provide a codesandbox for this? easy for me to investigate and verify.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/small-haze-dxo22

**Comment by bluebill1049** [comment]
hmmm i think this issue on v3 as well.

**Comment by bluebill1049** [comment]
looks like we may have to convert it into object to have type support...

**Comment by bluebill1049** [comment]
ok let's move into object from 4.1.0 and onwards: https://codesandbox.io/s/small-haze-dxo22
