### ISSUE TITLE
Can't set value nested attributes in typescript.

### ISSUE THREAD

**Issue by tanmen** [react-hook-form/react-hook-form#712]
**Describe the bug**
Can't set value nested attributes in typescript.
```js
setValue('name', 'test');
setValue('person.firstName', 'my name'); // <- 'person.firstName' type error
```

**To Reproduce**
1. create nest array or object form
2. setValue use in target nest property 

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-set-inputselect-value-u4u2u

**Expected behavior**
```js
type Form = { name: string, person: { firstName: string, lastName: string } };

const {setValue} = useForm<Form>();

setValue('person.firstName', 'tanmen'); //<- no error
```

**Screenshots**
<img width="434" alt="スクリーンショット 2019-12-26 18 26 03" src="https://user-images.githubusercontent.com/18521406/71469713-60169500-280d-11ea-9a32-839f40fd77e3.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bluebill1049** [comment]
thanks, @tanmen will look into this 👍

**Comment by bluebill1049** [comment]
can you provide a codesandbox?

**Comment by tanmen** [comment]
ok, i try

**Comment by tanmen** [comment]
created :)
https://codesandbox.io/s/react-hook-form-set-inputselect-value-u4u2u

**Comment by bluebill1049** [comment]
hmmm looks like this is pretty much impossible with TS to support nested object.

methodA:
```
type Form = { name: string; person: { firstName: string; lastName: string }; 'person.firstName': string  };
```

methodB:

basically we take `FieldName | string`

**Comment by bluebill1049** [comment]
we probably go with `methodB`

**Comment by tanmen** [comment]
I think too..
so sad typescript... haha :(

methodB is this line?
```js
export declare type FieldName<FormValues extends FieldValues> = keyof FormValues & string;
```

**Comment by bluebill1049** [comment]
yes @tanmen

**Comment by tanmen** [comment]
ok :)
thank you check this problem!
i like this lib. and so good correspondence.

**Comment by bluebill1049** [comment]
no worries @tanmen i am very glad you like it, actually you want to submit a PR for this? get your name in the repo too ❤️

**Comment by bluebill1049** [comment]
we can close this issue with your contribution too :)

**Comment by tanmen** [comment]
really?
I so happy!
I need try it :)

**Comment by bluebill1049** [comment]
👍
