### ISSUE TITLE
issue: deal with setValue and shouldDirty

### ISSUE THREAD

**Issue by mydesweb** [react-hook-form/react-hook-form#7121]
### Version Number

7

### Codesandbox/Expo snack

https://snack.expo.dev/

### Steps to reproduce

The default value of my field is undefined declared with `useForm({defaultValues: {fieldName: undefined})` and later I use `setValue('fieldName', newValue, {shouldDirty: true})` to change the value of the field, all good but if I delete the field value by calling again `setValue('fieldName', undefined, {shouldDirty: false})` the fields remains dirty even it has the same default value now.

Probably I am doing something wrong, but how to remove dirty flag from a certain field if it's value is the same as initial / default value after few changes?

### Expected behaviour

The field should not be dirty when it has the same value as the default one.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we don't support undefined in the `defaultValues`

https://react-hook-form.com/api/useform

> The defaultValues for inputs are used as the initial value when a component is first rendered, before a user interacts with it. It is encouraged that you set defaultValues for all inputs to non-undefined values such as the empty string or null.
![Screen Shot 2021-11-23 at 9 36 57 pm](https://user-images.githubusercontent.com/10513364/143009281-947cf591-5c47-4e6f-8703-769be7b742e9.png)

**Comment by bluebill1049** [comment]
just to add more context on the above, `undefined` is reserved for diffing between inline `defaultValue` and useForm `defaultValues`.

eg

```
useForm({
  defaultValeus: {
    test: '',
  }
})

// when it's undefined with defaultValue we will fall back to the defaultValues
useController({
  name: 'test',
})

useWatch({
  name: 'test',
  defaultValue: ''
})
```

**Comment by mydesweb** [comment]
@bluebill1049 I understand, but  how to remove dirty flag from a certain field if it's value is the same as initial / default value after few changes? 

For example if we deal with a Date field, and the same date is finally set. I have to manually check if it is the same date by comparing the year, month and day.. the date1 === date2 comparison will not work since are different objects.

**Comment by bluebill1049** [comment]
> how to remove dirty flag from a certain field if it's value is the same as initial / default value after few changes?

not 100% sure what do you mean above, you want to provide a codesandbox? 

> the date1 === date2 comparison will not work since are different objects.

we do a compare comparison with date objects inside with `getTime()`.

**Comment by mydesweb** [comment]
Ah, if you are using getTime() for date comparison this is perfect. 
I was thinking I have to manually check two dates and set shouldDirty accordingly.
Thank you for this great library.

**Comment by bluebill1049** [comment]
no worries @mydesweb thanks for understanding 👍
