### ISSUE TITLE
React-hook-form and polyfill.io causing page to crash Z.current.unMount is not iterable.

### ISSUE THREAD

**Issue by kezzakyle** [react-hook-form/react-hook-form#7129]
### Version Number

7 -> Issue started from version 6.8.4 and up

### Codesandbox/Expo snack

Empty

### Steps to reproduce

On IE11 you can go to [polyfill.io](https://polyfill.io/v3/) and download the minified code. **Or** simply paste this into IE11 https://polyfill.io/v3/polyfill.min.js and you will get the required code. 

Create a React project (not in codebox/codepen a real project) and create a basic form using [React-form-hook. ](https://react-hook-form.com/)

Next import the polyfill and this will result in the page crashing: `Z.current.unMount is not iterable.` As soon as you remove the polyfill, the form works as expected.

### Expected behaviour

I expect React-hook-form library to not be effect by polyfills. Any work arounds here? I have also added a stackoverflow post around this with image references: https://stackoverflow.com/questions/70088236/react-hook-form-and-polyfill-io-causing-page-to-crash-z-current-unmount-is-not-i

**This issue seems to have come from version 6.8.4 of React-hook-form and above.**

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
no longer support IE 11.

**Comment by kezzakyle** [comment]
I understand that. This is an issue in all browsers if a polyfill is present on a page.
Which I guess since react-hook-form does not support IE11 post v6.8.4 (or whenever) we cannot use it at all due to conflicts with polyfill in any browser the user uses. But I guess if the App doesn't support IE11 we would have no need for a polyfill. Fair point.

Quick solution if anyone else comes across this in ALL browsers, is to downgrade to v6.8.3 to make the forms functional again.
