### ISSUE TITLE
Cannot read property 'errors' of null when using FormContext

### ISSUE THREAD

**Issue by opeah** [react-hook-form/react-hook-form#713]
I got an error 'Cannot read property 'errors' of null' when using FormContext

v4.1.0

<img width="570" alt="Capture d’écran 2019-12-26 à 10 30 30" src="https://user-images.githubusercontent.com/31569566/71469891-d1812400-27ca-11ea-9de7-4a57f76d1ff6.png">

<img width="510" alt="Capture d’écran 2019-12-26 à 10 30 50" src="https://user-images.githubusercontent.com/31569566/71469892-d2b25100-27ca-11ea-8630-42c4d77256ae.png">

<img width="573" alt="Capture d’écran 2019-12-26 à 10 32 05" src="https://user-images.githubusercontent.com/31569566/71469964-01302c00-27cb-11ea-92d2-579d4cf96721.png">

**Comment by bluebill1049** [comment]
can you provide a codesandbox for this?

**Comment by opeah** [comment]
Ok sorry the error comes from me, you can close the issue.

Thanks 👍

**Comment by bluebill1049** [comment]
cool 👍

**Comment by zivl** [comment]
@bluebill1049 I'm facing the same thing,  can you share what was your faulty scenario?
