### ISSUE TITLE
issue: Validation on nested fieldArrays is not consistent

### ISSUE THREAD

**Issue by Mimameid** [react-hook-form/react-hook-form#7136]
### Version Number

7.20.2

### Codesandbox/Expo snack

https://codesandbox.io/s/suspicious-kirch-v2dy3?file=/src/schemas.js

### Steps to reproduce

1. Open the provided codesandbox
2. Turn on the switch on the right side. A `TextField` with the value "Ace" will be generated. Remove one character and you will see an error.
3. In the opened `schemas.js` file, scroll down until you find commented out code. Comment it back in.
4. Turn off the switch on the right side and try to reproduce step 2.

Triggering the error manually on every input change as you can find commented out in the `NameList` component doesn't seem to have any effect, which is also very peculiar.

### Expected behaviour

The validation process should register the error in the `formState` object. From what I know, the `useFieldArray` methods don't trigger validation. Which is considered. Using `trigger` doesn't seem to have an effect either.

I'm wondering if there is something that I'm not considering or doing wrong. But after fighting for hours with this I'm here...

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
react hook form is focused on field-level validation, for parent node level validation with the schema you will have to use `trigger`.

**Comment by Mimameid** [comment]
> react hook form is focused on field-level validation, for parent node level validation with the schema you will have to use `trigger`.

Ehm, did you even read what I wrote or look into the provided example? I am mentioning that trigger apparently doesn't work.

**Comment by bluebill1049** [comment]
> Ehm, did you even read what I wrote or look into the provided example? I am mentioning that trigger apparently doesn't work.

This is not a product support hot line, you better change your tone of voice. I did look at your example and read, I may miss things because I am a human.

**Comment by Mimameid** [comment]
My apologies didn't want to be rude. I neither assumed that this is a support hot line, nor that you aren't human.

I just wanted to issue a bug report to the best of my knowledge. Read through a lot. Spend a lot of time into investigating this and decided that the maintainers should know and the bug should be fixed .

I must admit, seeing an unrelated comment and the issue getting closed right after, without feedback of the issuer confused me. So, I was wondering, if you read through the report.

**Comment by bluebill1049** [comment]
I have deleted my previous message... so let's focus on the problem. 

https://codesandbox.io/s/jolly-knuth-0qeu1?file=/src/App.js can you debug the 
```tsx
resolver: async (data, context, option) => {
  console.log("data", data);
  const output = await yupResolver(NestedSchema)(data, context, option);
  console.log("validation output", output);

  return output;
}
```

first, can you debug the validation schema above?

**Comment by Mimameid** [comment]
Validation output shows the error of the parent object. But the issues mentioned in the report maintain:

1. `trigger` doesn't have any effect at all
2. field level validation isn't registered when there is a parent level error

**Comment by bluebill1049** [comment]
> trigger doesn't have any effect at all

https://codesandbox.io/s/jolly-knuth-0qeu1?file=/src/App.js 

there are no errors from your schema by `trigger` the `nestedObject` can you look into your schema? and also the codesandbox which i provided which have some debug code

> field level validation isn't registered when there is a parent level error

like I mentioned above, react hook form is focused on field level, it doesn't aware of parent level error. This is expected behavior.

**Comment by Mimameid** [comment]
I should make myself more clear. If I'm not getting something wrong, it is as follow:


> https://codesandbox.io/s/jolly-knuth-0qeu1?file=/src/App.js
> 
> there are no errors from your schema by `trigger` the `nestedObject` can you look into your schema? and also the codesandbox which i provided which have some debug code

I tested your codesandbox. There is indeed an error. If you remove one Character from "Ace". But, this error is not triggered by "trigger". You can remove the line  ` trigger("nestedObject");` and it is still the same. No difference.

> 
> > field level validation isn't registered when there is a parent level error
> 
> like I mentioned above, react hook form is focused on field level, it doesn't aware of parent level error. This is expected behavior.

I understand, but I meant something else. If you remove the `test` function ("simple length test parent") from the schema, you can see the error of other `test` function ("simple length test"). One is on the field, the other is on the parent.

**Comment by Mimameid** [comment]
Here are images to explain further what I mean.

Here is the example with `trigger`. Validation output shows error, when input field has less than 3 characters "Ac":
![image](https://user-images.githubusercontent.com/18268210/143328829-bc54f36d-4fa9-417e-abc8-5469a23f8ea0.png)


Now, let's look what happens if we remove trigger:
![image](https://user-images.githubusercontent.com/18268210/143329315-5e0dcf30-a2d1-4e70-a561-928f8d0acfb2.png)

As you can see, there is no difference.

But something more peculiar for me is this one. If we remove the `teste` function on the parent, field level validation (`test` of newName) starts working again.
![image](https://user-images.githubusercontent.com/18268210/143329726-5b117f0b-ccc0-4a79-a3c0-0742d2a98ff2.png)

**Comment by bluebill1049** [comment]
> I understand, but I meant something else. If you remove the test function ("simple length test parent") from the schema, you can see the error of other test function ("simple length test"). One is on the field, the other is on the parent.

I have updated the doc to make this behavior more clearly and why: 

> Schema validation focus on the field level for error reporting. Parent level error look is only limited to the direct parent level that is applicable for components such as group checkboxes.

![Screen Shot 2021-11-25 at 11 50 16 am](https://user-images.githubusercontent.com/10513364/143332288-d4cc0cb7-655d-4324-96c3-a8e4e520835e.png)

It's always better/precious to trigger for group/parent level error, at the end of the day, react hook form is focused on field level when the user interacts with a single input at a time.

**Comment by Mimameid** [comment]
What about field level error not triggering, when there is a parent level error? Is this, how it is supposed to work? If so, do you have an idea, how I could get both errors?

**Comment by bluebill1049** [comment]
That's a problem to solve at your schema level right? 

react hook form will read the errors object returned by your schema, if it's a field level that matches with your input then it will update `formState` and render the error. If you mix up with form level and field level, things are going to get difficult. which I assume it's the case here. you want to report field level and also be aware of form level. I suggest you pick one. if you want field level then the first half of your schema works, if you want to return form level, then stick with `trigger`, so it always return a group level of error.

**Comment by bluebill1049** [comment]
the other really important aspect is group error vs index error

`const errors = {}`

vs

`const errors = []`

see the conflict here, that's the nature of field array errors as well, you need to pick either index level or group level.

**Comment by Mimameid** [comment]
So there is no way of getting both errors at the same time?

I don't quite understand what you `trigger` does here. From what I tested and seen in the pictures about, it has essentially no functionality in this context.

**Comment by bluebill1049** [comment]
not possible, read this part: https://github.com/react-hook-form/react-hook-form/issues/7136#issuecomment-978687491

you can't have a root and index errors at the same time.

**Comment by Mimameid** [comment]
I understand. Would it make sense to add this "feature"?

**Comment by bluebill1049** [comment]
I have no idea how to get around such an issue unless someone can purpose a solution to cate both index and object. I am more than happy to move that into the feature backlog if that's the case.

**Comment by Mimameid** [comment]
I don't know much about the code to have a take on this.

I'm wondering though, how this is not working. From what I understand, the validation is running on every level anyway (if you debug the test functions, you see that they are running). Why can't the errors be registered?
