### ISSUE TITLE
Add select method to useForm

### ISSUE THREAD

**Issue by ryanmk54** [react-hook-form/react-hook-form#7138]
**Is your feature request related to a problem? Please describe.**
I would like to be able to select all the text in a field when focusing.

In the form I have created, I advance to the next field when the user presses tab or enter if the form is valid. I use setFocus to handle enter, to prevent advancing if the field is invalid, and the next field may be based on certain conditions. I would like the text selected in a field because this makes it easier for the user to change the input value.

**Describe the solution you'd like**
setFocus is defined here
https://github.com/react-hook-form/react-hook-form/blob/13ceee6b459d5a306367e096c2997a82c25c9521/src/logic/createFormControl.ts#L1140

If `field.ref.select()` is used instead of `field.ref.focus()`, then it would select the text in the field instead of just focusing the field. It might be nice to be able to select text and/or focus the field, maybe a new method could be returned from useForm called `select("firstName")`.

**Describe alternatives you've considered**
Alternatively, an option could be added to setFocus to select the text when the field is focused. For example, `setFocus("firstName", {select: true})`.

**Comment by vmosyaykin** [comment]
I find the option to select all the text in the field on focus quite useful.
I also think it would be useful to be able to set the caret position to the start/end of the field.

E.g. a "serial number"-style input:
![image](https://user-images.githubusercontent.com/4989930/144725654-f4f0f200-4721-4bfa-bbbf-2efdb844b67e.png)

When the user enters four digits in the first field, I want to set focus to the second field, with the caret at the start of the field, regardless of the previous caret position in this field.

This should be possible using the [setSelectionRange](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange) method.

So my idea for `setFocus` options looks something like this:
```
setFocus: (name: string, options?: Record<string, boolean | any>) => void

options  shouldSelect        boolean   Select all the text in the field
         shouldCaretToStart  boolean   Place the text insertion caret to the start of the field
         shouldCaretToEnd    boolean   Place the text insertion caret to the end of the field
```

Another possibility is a `mode` option with values of `select | caretToStart | caretToEnd`.

Sidenote: "caret" seems a better choice than "cursor" to avoid confusion with the mouse cursor. It is used, for example, in the [caret-color](https://developer.mozilla.org/en-US/docs/Web/CSS/caret-color) css property.

If this looks okay, I can try to create a PR with this update to `setFocus`.

_I can re-post this comment as a separate feature request, if that's more appropriate._

**Comment by bluebill1049** [comment]
Thanks for the detailed input @vmosyaykin

**Comment by bluebill1049** [comment]
shall we start with `shouldSelect`? then incrementally introduce other APIs, if the demand increases. cc @Moshyfawn

**Comment by Moshyfawn** [comment]
Sounds good!
Just yesterday there was an issue created on the cursor position `onFocus` #7776. Maybe it's next up for a feature ;)

Tho, let's be cautious. RHF is a headless hook, not a UI lib. Let's not overwhelm the API with UI management as well
