### ISSUE TITLE
issue: useFieldArray - is deleting id property on mutation

### ISSUE THREAD

**Issue by abFx** [react-hook-form/react-hook-form#7139]
### Version Number

7.20.2

### Codesandbox/Expo snack

https://codesandbox.io/s/usefieldarray-forked-nl6c0?file=/src/App.tsx

### Steps to reproduce

We upgraded recently to latest version and some validations started to show us the issue. When adding or modifying an item using useFieldArray, the id property gets deleted.

1. Open Sandbox
2. Click 'Add'
3. Inspect window to show console log
4. Look at the values, the new inserted item contains default values except for id

### Expected behaviour

insert() or append() should add a new item with default values including ID

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
0: {key: 'Key1', name: 'Name1'}
1: {key: 'Key2', name: 'Name2'}
2: {name: '', key: ''}
3: {name: '', key: ''}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> Change keyName to other when your form value contains id which is the default key name.
<img width="964" alt="Screen Shot 2021-11-25 at 9 18 12 am" src="https://user-images.githubusercontent.com/10513364/143319791-aa894055-33be-4f25-85d9-8c8aeaab6d4a.png">

**Comment by dnquang1996vn** [comment]
> > Change keyName to other when your form value contains id which is the default key name.
> 
> <img alt="Screen Shot 2021-11-25 at 9 18 12 am" width="964" src="https://user-images.githubusercontent.com/10513364/143319791-aa894055-33be-4f25-85d9-8c8aeaab6d4a.png">

Hi @bluebill1049 , Can I keep id as keyName and still keep the key id after append().
Your solution works but it's a bit inconvenience

**Comment by mfferreira** [comment]
@dnquang1996vn To be clear, is it the case that the dataset passed to the form cannot contain `id`?

If it can, how can we keep using it as the form keyname (default) and still keep it in when mutating the array?

**Comment by bluebill1049** [comment]
> > > Change keyName to other when your form value contains id which is the default key name.
> > 
> > 
> > <img alt="Screen Shot 2021-11-25 at 9 18 12 am" width="964" src="https://user-images.githubusercontent.com/10513364/143319791-aa894055-33be-4f25-85d9-8c8aeaab6d4a.png">
> 
> Hi @bluebill1049 , Can I keep id as keyName and still keep the key id after append(). Your solution works but it's a bit inconvenience

https://github.com/react-hook-form/react-hook-form/issues/7115#issuecomment-979039537

**Comment by bluebill1049** [comment]
the next version 7.23.0 

https://github.com/react-hook-form/react-hook-form/releases/tag/v7.23.0-next.0
https://github.com/react-hook-form/react-hook-form/releases/tag/v7.23.0-next.1 

```
const App = () => {
  const { control, register, handleSubmit } = useForm<FormValues>({
    defaultValues: {
      test: [{id: 'UUID5678', test: 'data' }] // id will be remained as it match default keyName
    }
  });
  const { fields, append } = useFieldArray({
    control,
    name: 'test',
  });

  return (
    <form>
      {fields.map((field, index) => {
        return <input key={field.id} {...register(`test.${index}.test`)} />;
      })}

      <button
        type={'button'}
        onClick={() => {
          append({
            id: 'UUID1234', // id value will be remained as it match default keyName
            test: '1234',
          });
        }}
      >
        append
      </button>
      <button>submit</button>
    </form>
  );
};
```

will no longer remove id from user's data.
