### ISSUE TITLE
issue: setValue with {shouldDirty: true} option is not setting field in dirtyFields array if Value is Number Object

### ISSUE THREAD

**Issue by swapnilrohom** [react-hook-form/react-hook-form#7149]
### Version Number

7.16.1

### Codesandbox/Expo snack

https://codesandbox.io/s/upbeat-cohen-vxdx0?file=/src/App.tsx

### Steps to reproduce

1. Go to Sandbox Link
2. Try changing/adding input field data
3. See `dirtyFields` are still undefined

NOTE: Value is `Number` Object

### Expected behaviour

`dirtyFields` should be true after updating input

I made some investigation and found that `deepEqual` function is not supporting Number Object equality.

By adding the above condition in `deepEqual function` it will start working.

`if (!isNaN(object1) || !isNaN(object2)) {
      return object1.toString() === object2.toString();
  }`

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
that's for raising an issue and even providing a csb.
