### ISSUE TITLE
issue: useFieldArray use remove API and next use append  API old value cover new value

### ISSUE THREAD

**Issue by yaeSakuras** [react-hook-form/react-hook-form#7165]
### Version Number

7.20.4

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-f8vg2?file=/src/index.js

### Steps to reproduce

1. Click 'Delete' remove one item
3. next Click 'Append' add one item
4. See bug old value 'Luo3' cover add new item value ''

### Expected behaviour

Expect add item value exactly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yaeSakuras** [comment]
![image](https://user-images.githubusercontent.com/7360502/143853233-b6acd302-703b-4a07-8957-6f85aa6c0efb.png)

click remove

![image](https://user-images.githubusercontent.com/7360502/143853277-2da364a4-f535-4cf3-9919-af576eb960c4.png)

click append

![image](https://user-images.githubusercontent.com/7360502/143853335-2d632d20-a53d-4cfb-8ba6-56df9a16d3dc.png)

**Comment by yaeSakuras** [comment]
old value ‘Luo3’

**Comment by bluebill1049** [comment]
append data is required, not partial.

```
(obj: object \| object[], { shouldFocus?: boolean; focusIndex?: number; focusName?: string; }) => void
```
