### ISSUE TITLE
issue: clearErrors set / hardcode the formState isValid to true 

### ISSUE THREAD

**Issue by zyl-edison** [react-hook-form/react-hook-form#7171]
### Version Number

7.20.4

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-clearerrors-forked-6o2wb?file=/src/index.jsx

### Steps to reproduce

From the clear errors documentation, it states `This function will not update formState (set isValid to true). It only clear errors`. 

1. Go to clear errors documenation https://react-hook-form.com/api/useform/clearerrors
2. Click on CODESANDBOX link
3. In the codesandbox choose the react hooks form verison 7.20.4
4. Inspect the formState.isValid after clear one of the input error, first name in this case.

I think the bug was introduced by Version 7.17.5 with the commit change https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/createFormControl.ts#L787

### Expected behaviour

It should not set the formState isValid to true since other fields may not be valid.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> set isValid to true

That was what I meant in this documentation (it will set to true), but think twice, I think `clearErrors` should affect isValid `formState`. It's a hard topic... as there is no clear standard out there.

**Comment by bluebill1049** [comment]
let me dig out the commit against the original issue as well.

**Comment by bluebill1049** [comment]
any update on this before i am closing it as expected behaviour.
