### ISSUE TITLE
issue: useFieldArray defaultValues not populating form

### ISSUE THREAD

**Issue by pwharff** [react-hook-form/react-hook-form#7172]
### Version Number

7.15.3

### Codesandbox/Expo snack

https://stackblitz.com/edit/react-hook-form-7-dynamic-form-example-nidvxr?file=App.jsx

### Steps to reproduce

1. Open the code sandbox
2. See `Full name` default value of `Joe Schmoe` not populated

When using `useFieldArray` and `defaultValues`, no values are populated in the form:

```
const { control, errors, handleSubmit } = useForm({
    defaultValues: {
      accounts: [{ fullName: 'Joe Schmoe' }],
    },
  });
```

See stack blitz example.

### Expected behaviour

To populate the form with default values by providing object to `defaultValues` argument of `useForm`

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
can we provide a reasonable example for me to look into instead of dumping a partial project here? here is a template you can fork and use: https://codesandbox.io/s/react-hook-form-usefieldarray-ssugn
