### ISSUE TITLE
issue: Unmounted fields are not validated when submitted

### ISSUE THREAD

**Issue by thaingu** [react-hook-form/react-hook-form#7178]
### Version Number

7.20.4

### Codesandbox/Expo snack

https://codesandbox.io/s/usefieldarray-unmounted-fields-not-being-validated-ho6sr?file=/src/App.tsx

### Steps to reproduce

1. Open Sandbox
2. Click on one of the checkboxes to show hidden field
3. Click on 'Submit'
4. Open the console to see that submission failed with `errors` indicating the required field
5. Click on the checkbox again to hide the field
6. Click on 'Submit'
7. See in the submission that the form is submitted with the invalid hidden field.

### Expected behaviour

All fields that are submitted by the form should have the validation rules applied to them despite being unmounted when using `shouldUnregister: false`. 
The main use-case for this is in large complex forms where some fields need to be unmounted for performance, like with virtualised lists or pagination, validation should apply to all the fields sent to `onSubmit` instead of only the visible fields.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
{"data":[{"name":"test"},{"name":"test1"},{"name":"test2","conditional":""}]}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
That's expected behaviour we don't validate unmounted inputs.

**Comment by thaingu** [comment]
Thanks for the quick response!
Is there a way to modify the data being sent into the built-in validation or is custom validation the best option here?

**Comment by bluebill1049** [comment]
Not at the moment with built-in validation, you can consider using schema validation which is validated at the form level.

**Comment by thaingu** [comment]
Looks like schema validation is the way to go, thank you for your time :)
