### ISSUE TITLE
Allow to setValue without registering first

### ISSUE THREAD

**Issue by vuhg** [react-hook-form/react-hook-form#719]
Hi Bill,

Thank you for this awesome library!

I would like to request `setValue` without register first to dynamically set custom value to form's data. It would be great for form builder.

So i'm writing quiz maker function which construct a quizz dynamically like this:
```js
export function QuizMaker({ type, index, ...props }) {
  const { setValue, register, unregister } = useFormContext()

  useEffectOnce(() => {
    register(`quiz[${index}].type`)
    setValue(`quiz[${index}].type`, type)
    return () => unregister(`quiz[${index}]`)
  })

  return React.createElement(quizTypes[type], { index, ...props })
}
```

If i need to set custom info like quiz's points, i have to register and setValue again.
Or i want to add quiz level to form data first to test api, add level picker later, ... register and setValue must be used again.

Should we have another function call `inject` to dynamically set custom value to form data?

**Comment by bluebill1049** [comment]
hey @vuhg, thanks for the kind words. It is possible just register once

`register('quiz')`

and you can `setValue('quiz[0]', 'data')` see if that works.

**Comment by vuhg** [comment]
Thank you for quick response.

That doesn't work.
`register('quiz')` overrides my default quiz and set quiz undefined instead of array[quiz].
incorrect behavior: `quiz: undefined`
correct behavior: `quiz: [{ default quiz object }]`

**Comment by bluebill1049** [comment]
what about this `register('quiz[0]')`?  will that make the input filed `registered` as array?

To be honest, i will try to get away with this `inject` concept for now.

**Comment by vuhg** [comment]
`register` once and using `setValue` many times is great alternative.
But the current behavior is unexpected for me, or i don't understand correctly.

```
useEffectOnce(() => {
    register(`quiz[${index}]`)
    setValue(`quiz[${index}].type`, type)
    return () => unregister(`quiz[${index}]`)
})
```

quiz is empty array instead of array of 3 (because i added 3 quizzes to test)

**Comment by bluebill1049** [comment]
what do you get by running this: 

```
register('quiz[0]')

setValue(`quiz[0].type`, type)
setValue(`quiz[1].type`, type)
setValue(`quiz[2].type`, type)
```

**Comment by vuhg** [comment]
the result is `quiz: Array(0)`
actually, ```register(`quiz[${index}]`)``` will reset all the default quiz's values and return empty array

```
const quizTypes = {
  input: QuizInput,
  choice: QuizChoice,
  reorder: QuizReorder
}

export function QuizMaker({ type, index, ...props }) {
  return React.createElement(quizTypes[type], { index, ...props })
}
```

That would give me correct behavior and return 3 correct quizzes `quiz: Array(3)` but it doesn't inject the quiz's type that i want.

**Comment by bluebill1049** [comment]
maybe you could build a small utility function to do these.

**Comment by vuhg** [comment]
yeah, thank you for taking time to answer.

i have 2 different direction now: 
one is watch all inputs' changes and send them to `zustand`'s store
two is use nested form, send all children's changes to parent form.

**Comment by bluebill1049** [comment]
thanks for understanding @vuhg ❤️
