### ISSUE TITLE
issue: form behaves like `{mode: 'onChange'}` after calling handleSubmit

### ISSUE THREAD

**Issue by Liooo** [react-hook-form/react-hook-form#7195]
### Version Number

7.20.5

### Codesandbox/Expo snack

https://codesandbox.io/s/serene-sun-smze8?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/serene-sun-smze8?file=/src/App.tsx
2. type in something in firstName, then remove them all, then blur
3. make sure errors is shown and mode onBlur is working
4. click Submit
5. try typing and removing firstName
6. errors: will update as you type, instead of when you blur

### Expected behaviour

behave as onBlur mode after submit

(this seems pretty basic, sorry in advance if I'm missing something 🙏)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/useform

refer to the doc for revalidateMode:

>reValidateMode: onChange | onBlur | onSubmit = 'onChange'!React Native: Custom register or using Controller
This option allows you to configure validation strategy when inputs with errors get re-validated after user submit the form (onSubmit event). By default, validation is triggered during the input change event.

**Comment by Liooo** [comment]
thanks!! (and now apology is official)

**Comment by bluebill1049** [comment]
@Liooo no worries at all.
