### ISSUE TITLE
Changes in 7.20.3 seem to cause useFieldArray changes to make all fields dirtyFields

### ISSUE THREAD

**Issue by dbousamra** [react-hook-form/react-hook-form#7197]
### Version Number

7.20.3

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-submit-only-dirty-fields-forked-o6yc4?file=/src/index.tsx

### Steps to reproduce

If you append/remove a field array value, you will notice the dirty fields are a different format to what they were previously. Not such an issue, but this function:

```
const getDirtyValues = (
  dirtyFields: UnknownArrayOrObject | boolean,
  allValues: UnknownArrayOrObject,
): UnknownArrayOrObject => {
  // NOTE: Recursive function.

  // If *any* item in an array was modified, the entire array must be submitted, because there's no
  // way to indicate "placeholders" for unchanged elements. `dirtyFields` is `true` for leaves.
  if (dirtyFields === true || Array.isArray(dirtyFields)) {
    return allValues;
  }

  return Object.fromEntries(
    // @ts-ignore
    Object.keys(dirtyFields).map((key) => [key, getDirtyValues(dirtyFields[key], allValues[key])]),
  );
};
```

Which is floating around in an official example, and also this discussion: https://github.com/react-hook-form/react-hook-form/discussions/1991

I spent ages trying to fix the function but I ran out of time.

### Expected behaviour

I expect when I modify an array field, that the othern on array fields are not dirty

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
there were issue with original implementation and hence the fix: https://github.com/react-hook-form/react-hook-form/issues/7109

**Comment by dbousamra** [comment]
https://github.com/react-hook-form/react-hook-form/blob/master/examples/V7/dirtyFieldsOnlySubmitted.tsx

**Comment by bluebill1049** [comment]
> https://github.com/react-hook-form/react-hook-form/blob/master/examples/V7/dirtyFieldsOnlySubmitted.tsx

Removed, this example was from the community.

**Comment by dbousamra** [comment]
Hmm. Is it possible to fix the function? I depend on it, but I could not figure out how to get it working. It should be so simple, but the recursion was doing my head in.

**Comment by bluebill1049** [comment]
As far as functionality goes with formate, the current dirty fields fix the field array issue the issue which i have pointed out above, if this is blocking I recommend using the previous version for now.

**Comment by dbousamra** [comment]
Okay, so stay with 7.20.2. That's fine. Thanks!

**Comment by bluebill1049** [comment]
Thanks for understanding. We will keep it as it is for now, as it fixes the issue with incorrect field array reporting which is a pretty bad bug causing app crash.

**Comment by dbousamra** [comment]
@bluebill1049 any updates here? I want to upgrade, but I am still seeing this issue where all fields are marked dirty for field arrays.

**Comment by rostber** [comment]
The 7.28.1 version has had that problem yet.
