### ISSUE TITLE
Use browser native validation messages

### ISSUE THREAD

**Issue by enisdenjo** [react-hook-form/react-hook-form#7201]
**Is your feature request related to a problem? Please describe.**

Registering an input with a `required: true` option on a `shouldUseNativeValidation: true` form shows an empty validation tooltip when invalid.

**Describe the solution you'd like**

Registering an input with a `required: true` option on a `shouldUseNativeValidation: true` form shows the browser native message when invalid.

**Describe alternatives you've considered**

You can just put the `required` prop directly on the input (`<input {...register('name')} required />`) and get the browser message, but is this the intended usage that `react-hook-form` would advocate? If so, I'd naturally expect the `required` option to get spread to the input field when using the form with the `shouldUseNativeValidation: true` option.

**Additional context**

It's simply annoying to always have to supply the exact same message on all inputs that are required. Especially annoying when you have internationalization. For example sake, this is how all required inputs would have to look like with [`react-intl`](https://github.com/formatjs/formatjs/tree/main/packages/react-intl):
```diff
+ import { FormattedMessage } from 'react-intl';

...

+ <FormattedMessage id="FIELD_REQUIRED">
+   {([message]) => (
      <input
        {...register('name', {
+         required: message,
        })}
      />
+   )}
+ </FormattedMessage>
```

Whereas, the browser would translate the appropriate message for you depending on the user's browser language settings.

_* I guess the expected behavior should happen for all other browser native validation properties, like `pattern` and `min/max`_

**Comment by bluebill1049** [comment]
similar disucssion here: https://github.com/react-hook-form/react-hook-form/discussions/7193

**Comment by bluebill1049** [comment]
> Whereas, the browser would translate the appropriate message for you depending on the user's browser language settings.

It doesn't translate messages for you, only those default ones.

**Comment by bluebill1049** [comment]
move to the project board.

**Comment by enisdenjo** [comment]
> It doesn't translate messages for you, only those default ones.

Yes, that's what I meant. It translates the built-in default messages to the browsers language.

Anyways, thanks for the quick response and the PR, much appreciated! 😄
