### ISSUE TITLE
issue: unable to invoke callback on watch with typescript

### ISSUE THREAD

**Issue by bianchi** [react-hook-form/react-hook-form#7202]
### Version Number

6.15.3

### Codesandbox/Expo snack

https://codesandbox.io/s/stupefied-einstein-r1wsy?file=/src/App.tsx

### Steps to reproduce

1. Go to the sandbox
2. See error when trying to use watch with callback

### Expected behaviour

No errors.

Just copied the code from video [https://www.youtube.com/watch?v=3qLd69WMqKk&t=577s](https://www.youtube.com/watch?v=3qLd69WMqKk&t=577s)
Checked on the docs [https://react-hook-form.com/v6/api#watch](https://react-hook-form.com/v6/api#watch)

Maybe I'm not seeing something

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
There is no such usage for V6, it's a V7 syntax. please refer to the doc 

https://react-hook-form.com/api/useform/watch

vs 

https://react-hook-form.com/v6/api#watch

**Comment by bianchi** [comment]
> There is no such usage for V6, it's a V7 syntax. please refer to the doc
> 
> https://react-hook-form.com/api/useform/watch
> 
> vs
> 
> https://react-hook-form.com/v6/api#watch

It is in the example of V6 docs you, and I, have linked. Maybe it should be removed.

Anyway, is it possible to achieve the same behavior in V6? Migrate would probably be a pain in the project I'm working on

**Comment by bluebill1049** [comment]
Will update that, not possible with v6
