### ISSUE TITLE
issue: watch and getValues return undefined after disabling and enabling back an input

### ISSUE THREAD

**Issue by felipeS** [react-hook-form/react-hook-form#7203]
### Version Number

7.12.2

### Codesandbox/Expo snack

https://codesandbox.io/s/awesome-shadow-nmk0p?file=/src/App.tsx

### Steps to reproduce

1. Go to the [condesandbox](https://codesandbox.io/s/awesome-shadow-nmk0p?file=/src/App.tsx)
2. Click on check the checkbox
3. Type something into the text input field
3. See the value of the text input field rendered below
4. uncheck the checkbox and verify that the input text field is disabled
5. check back the checkbox.
4. See error, the value of the text input field is undefined and therefore not rendered.

### Expected behaviour

After checking the checkbox that enable the text input field watch and getValues should return the current value of the input field.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This issue will need to be resolved by providing a `defaultValues` at useForm or `defaultValue` at `watch`. 

## Reson

without `defaultvalue`, hook form can't predict what's inside the render phase, as the click happens on the checkbox and next re-render will fallback to the `defaultValues` or defaultValue, the same reason for the watch API

> When defaultValue is not defined, the first render of watch will return undefined because it is called before register, but you can set the defaultValue as the second argument or provide defaultValues via useForm to avoid this behavior.

https://react-hook-form.com/api/useform/watch

**Comment by felipeS** [comment]
Thanks for the clarification. But, in this case, is there any workaround? Is there a way to access the text of the text input in the onChange of checkbox?

**Comment by bluebill1049** [comment]
Have you considered with `readOnly`, or otherwise you have to store that value in a `useState` or `useRef`, like a mention above the next render will still set input as `disabled` and hence render return `undefined`.

**Comment by bluebill1049** [comment]
better solution.
