### ISSUE TITLE
issue: setValue with dot notation mutates the object instead of creating a new one

### ISSUE THREAD

**Issue by randex** [react-hook-form/react-hook-form#7205]
### Version Number

7.20.5

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-useeffect-setvalue-issue-m3uut?file=/src/App.js

### Steps to reproduce

1. Go to [codesandbox](https://codesandbox.io/s/react-hook-form-useeffect-setvalue-issue-m3uut?file=/src/App.js)
2. Click on "token1" field. Type "5".
3. After a 1 sec delay the simulation value updates. "token2" must update with this exact value too, but doesn't. Take a look at the console to see controller's behavior. See the line 37 for a workaround (it feels like on line 34 the form mutates the value in the object instead of creating a new one, that's why we see this behavior).

### Expected behaviour

The controller should correctly pass the current value from the form. `setValue` with a dot notation should **not** mutate the object that has the value because it screws up re-renders (I guess).

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
It's expected behavior, setValue mutate internal `formValue`, setValue is not the same as `useState`.
