### ISSUE TITLE
Errors object doesn't work with yup in version 4

### ISSUE THREAD

**Issue by ahce** [react-hook-form/react-hook-form#722]
**Describe the bug**
Errors object is always empty.

**To Reproduce**
1. Open sandbox
2. Type text
3. Clear text
4. Check the console log

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-v4-errors-bug-ywth0

**Expected behavior**
https://codesandbox.io/s/react-hook-form-v3-errors-ok-7tbof

**Comment by bluebill1049** [comment]
Thank you! i broke it...

**Comment by bluebill1049** [comment]
react-hook-form@4.2.1-beta.1 tested and it's working again
