### ISSUE TITLE
Transfer the error infos in the FieldError

### ISSUE THREAD

**Issue by gbersac** [react-hook-form/react-hook-form#7223]
**Description of the issue**
I want to generalize form error handling (ie, provide generic error message):

```typescript
const {formState: { errors } } = useForm<SignupForm>()
return errors.myFieldName?.type === "minLength" ? <p>Some generic error message which contains the minLength value</p> : undefined
```

The problem is that in `errors.MyFieldName`, I don't have the minLength value. I have to specify that minLength value both in input declaration `<input {...register("password", { minLength: 6 })} />` and in my field error renderer component.

**Proposed solution**
Transform the `return errors.myFieldName?.type` from a `{type: string}` to a `{type: string, minLength: 6}`

**Comment by bluebill1049** [comment]
thanks for the feature request, please upvote this issue instead: https://github.com/react-hook-form/react-hook-form/issues/3950
