### ISSUE TITLE
[setValue] Using setValue with nested object doesn't update input value of Controller

### ISSUE THREAD

**Issue by FunctorDev** [react-hook-form/react-hook-form#7231]
### Version Number

7.21.0

### Codesandbox/Expo snack

https://codesandbox.io/s/morning-wave-xpo1c

### Steps to reproduce

1. Go to https://codesandbox.io/s/morning-wave-xpo1c
2. Click on `setValueWhole` button and `setValueEach` button
3. If you click to `setValueWhole` button, only the registered input is updated, the input of Controller isn't updated.
But if you click to `setValueEach` button, both inputs are updated

### Expected behaviour

Using method setValue with nested object should update input value of Controller.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I am going to patch this one, but I would recommend the `forEach` way of doing it, explained in here: https://www.youtube.com/watch?v=qpv51sCH3fI&feature=emb_logo

**Comment by FunctorDev** [comment]
Ok thanks @bluebill1049 .

I watched your video but didn't see the `forEach` way.
I guess it is this one:

![image](https://user-images.githubusercontent.com/60058060/145015837-218270cb-cdd9-4b41-9592-8c670f3accba.png)

**Comment by bluebill1049** [comment]
no worries, I have fixed the issue, it will be released in the next path.

**Comment by Georgiy-G** [comment]
@bluebill1049  Hi, did you solve this problem, or maybe I didn't see it?
