### ISSUE TITLE
issue: getValues() are stale inside custom onChange event handler 

### ISSUE THREAD

**Issue by nodeEnthu** [react-hook-form/react-hook-form#7234]
### Version Number

7

### Codesandbox/Expo snack

Related to #4977 and #4751

### Steps to reproduce

Create a parent component and pass the `handleOnChange` to child input component
like:
```
<input type="text" {...register('test', {
    onChange: (e) => {
       handleOnChange(e) // custom onChange handler
    },
    onBlur: (e) => {
        // custom onBlur handler
    },
})}/>
```
and inside` handleOnChange` in parent call `getValues()` like:

```
const handleOnChange= (e) => {
    console.log(getValues());
 };
  ```
  the field will be one character behind: e.g. type "asda" but the `getValues()` will be { test: "asd"}

### Expected behaviour

`getValues()` should be up to date inside custom onChange/onBlur functions

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by eqqe** [comment]
I also have this issue

**Comment by egimenos** [comment]
Same problem here
