### ISSUE TITLE
issue: useFieldArray update all values when is in separed component and item has nested keys

### ISSUE THREAD

**Issue by apoutchika** [react-hook-form/react-hook-form#7239]
### Version Number

>= 7.21 (Fails since version 7.13)

### Codesandbox/Expo snack

https://codesandbox.io/s/xenodochial-sky-ynlhb?file=/src/index.js

### Steps to reproduce

A: Test fail :
1. Click on "Append"
2. Add content in field
3. Click on "Append"
4. See your content on the new field
3. Click several times on "Append"
5. Change the content of one field
5. Click on "Append"
6. All field are updated with last updated field

B: Working Test  
1. In index, comment AppFail and uncomment AppWorking import
2. Click on "Append"
3. Add content in field
4. Click on "Append"
5. See the new field is empty

C: Test other working method with version
1. In index, comment AppWorking and uncomment AppFail import
2. Change react-hook-form version to 7.12.2
3. Click on "Append"
4. Add content in field
5. Click on "Append"
6. See the new field is empty

### Expected behaviour

The new fields must be empty and the modifications of one field must not impact the others

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for the example, however, the example gets me a bit confused...

```tsx
<Multi
  name="test"
  control={control}
  itemDefaultValue={{ name: { en: "" } }}
>
  {({ index }) => (
    <Input
      id={`test-${index}-name-en`}
      label={`Test ${index} EN`}
      name={`test.${index}.name.en`}
      control={control}
    />
  )}
</Multi>
```

and usage as below: 

```
{children({ index })}
```

I don't know if we are going to support such.

**Comment by apoutchika** [comment]
Thank you very much for your answer

I created a simplified version without the confusing part : https://codesandbox.io/s/charming-moore-qo6zv

Is this enough to get help?
