### ISSUE TITLE
issue: useFieldArray setValue without setting the whole object

### ISSUE THREAD

**Issue by bianchi** [react-hook-form/react-hook-form#7243]
### Version Number

6.15.3

### Codesandbox/Expo snack

https://codesandbox.io/s/silent-sunset-1n9l6?file=/src/Persons.tsx:1369-1374

### Steps to reproduce

1. Go to the sandbox
2. Click on "Print to console", it will print John and John's mother, as expected
3. Click on "Change whole object", the inputs will be updated. Click on "Print to console", it will print Lillian and Lillian's mother, as expected
4. Click on "Change only names". The inputs will be updated on indexes 2,3,4. Click on "Print to console", it will print Lillian and Lillian's mother instead of Mary's on indexes 2,3,4.

### Expected behaviour

Mary and Mary's mother should have been printed on indexes 2,3,4.

Not sure if it's a bug or it's not intended to allow that.

Thanks

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
It's a limitation with v6, would you be able to move to v7?

**Comment by bianchi** [comment]
It will not be easy but I have another situation that is available in V7, I will have to give a try. Thank you for your help
