### ISSUE TITLE
issue: form's onSubmit gets called when input component rerenders.

### ISSUE THREAD

**Issue by ricardogzm** [react-hook-form/react-hook-form#7248]
### Version Number

7.21.0 (latest)

### Codesandbox/Expo snack

https://codesandbox.io/s/form-show-password-issue-forked-zmbg7?file=/pages/index.js

### Steps to reproduce

1. Go to the sandbox on index.js
2. Fill the email and password fields
3. Press the eye button that is next to the password field to reveal password
![image](https://user-images.githubusercontent.com/46659539/145479176-e50bf4ad-7fa4-4f30-b26e-d28e2ea0d652.png)
4. Check console. onSubmit function gets called by handleSubmit whenever the eye button gets clicked.
![image](https://user-images.githubusercontent.com/46659539/145485951-91172ada-7f96-4a7a-affe-89df79be73c6.png)

### Expected behaviour

`onSubmit` function should not be called when an input component rerenders. In this case, I'm trying to reveal user's password with input's `type` attribute, changing it from "text" to "password" and vice versa.

Is this intended behavior? If so, how can I avoid it? I think I'm missing something. Clicking the reveal password button should not make, for instance, an axios request whenever the user clicks it (as the code shows it).

### What browsers are you seeing the problem on?

Firefox, Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ricardogzm** [comment]
I think I have solved it...

The button itself was submitting the form. I added e.preventDefault() to it and it is now working like I wanted.
```
<button
    onClick={(e) => {
      e.preventDefault();
      setShowPwd(!showPwd);
    }}
>
```

 I'm sorry for the inconvenience.

**Comment by ricardogzm** [comment]
I'm closing the issue.

**Comment by bluebill1049** [comment]
hey @ricardogzm the issue is without type='button' it will trigger the form submit, this is not related to hook form but a HTLM standard.
