### ISSUE TITLE
issue: calling setValue with shouldValidate=true does not update formState.isValid

### ISSUE THREAD

**Issue by chrisspadanuta** [react-hook-form/react-hook-form#7249]
### Version Number

7.21.0

### Codesandbox/Expo snack

https://codesandbox.io/s/shouldvalidate-broken-fnfkn?file=/src/App.js

### Steps to reproduce

I created a mask function to only allow ASCII characters (A-Z and a-z) to be entered into an input field and when calling `register`. I define an `onChange` callback that calls `setValue` with `shouldValidate` set to true.  The submit button being enabled is tied to `isDirty` and `isValid` in order to more easily illustrate how this might be used in a real world application.

1. Fill out the First name field with a single ASCII character (ie: 'A')
2. Notice that after a re-render, `isValid` is true and the submit button is enabled
3. Highlight First name field and enter '1'
4. Notice that field becomes blank (as expected because we don't allow non ASCII characters)

**Expected:** `isValid` to be false
**Actual:** `isValid` is still true, which allows the form to be submitted when it's in an error state.  It's worth noting that the `errors` object correctly contains an error for firstName.

### Expected behaviour

`isValid` to be false because calling `setValue` with `shouldValidate=true` should cause validation to re-run.  The [setValue documentation](https://react-hook-form.com/api/useform/setvalue) specifically mentions both `errors` and `isValid` being tied to `shouldValidate`.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
For reference, isValid seems to return a correct value when deleting the value of the field, as can be illustrated by following these steps:
1. Fill out the First name field with a single ASCII character (ie: 'A')
2. Notice that after a re-render, isValid is true and the submit button is enabled
3. Highlight First name field and delete its value

Notice that isValid immediately becomes false (and the submit button is disabled)

Also, simply entering '1' into the input field when the page first loads also correctly sets isValid to false.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Such usage will lead to an unexpected issue because register `onChange` will get fired within the `onChange`.

```tsx
const field = register('test', { onChange })

field.onChnage(onChnage)
```

which results in value overwrite, if you want to have such I would recommend building a controlled component, and sending data with `field.onChange` directly 

https://react-hook-form.com/api/usecontroller

**Comment by bluebill1049** [comment]
here is another workaround as well, avoid duplicated onChnage

```tsx
import { useState } from "react";
import { useForm } from "react-hook-form";
import Headers from "./Header";

export default function App() {
  const {
    register,
    handleSubmit,
    setValue,
    formState: { isDirty, isValid, errors }
  } = useForm({
    mode: "onChange"
  });
  const [result, setResult] = useState("");
  const onSubmit = (data) => setResult(JSON.stringify(data));

  console.log("isValid", { errors, isDirty, isValid });
  const upperAscii = (value) => {
    return value ? value.replace(/[^a-zA-Z]/u, "").toUpperCase() : "";
  };

  const { onChange, ref, name } = register("firstName", {
    required: true,
    validate: (value) => {
      console.log("value", value);
      return !!value;
    }
  });

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <Headers />
      <input
        name={name}
        onChange={(e) => {
          setValue("firstName", upperAscii(e.target.value), {
            shouldValidate: true,
            shouldDirty: true
          });
        }}
        ref={ref}
        placeholder="First name"
      />
      <p>{result}</p>
      <input type="submit" disabled={isDirty && !isValid} />
    </form>
  );
}
```

https://codesandbox.io/s/shouldvalidate-broken-forked-1cq2q?file=/src/App.js

**Comment by chrisspadanuta** [comment]
Thank you, will give it a try.
