### ISSUE TITLE
FieldError's message property

### ISSUE THREAD

**Issue by kusmierz** [react-hook-form/react-hook-form#725]
**Describe the bug**
I think there is a small issue in TS typings introduced somewhere in 4.x release. I can't read `.message` property on `errors`.

It applies only to `FieldErrors<any>`... `FieldErrors<FooBar>` with `type FooBar = { foobar: string; }` works as expected...

**To Reproduce**

try to use `message` property on FieldError:

```ts
const {
  errors,
} = useFormContext();

const name = 'username';
console.log(errors[name]?.message);
```

**TS Play link**
https://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgMQWABsATAUSimjgG8AoOOGATzGAC44BnGKZAOYBuRkzgB6cTwQBbMMQToWcUsHZJVSbEW6imkqMHQB+LgCUjIsRPGt23U3ACyAV2IwE84IRIUq0bisxGWBubkwBYEdefiRhPURuJ0wkF0xiRwAjCAhiYBSRAF96UEhYFWBsYkxDZjY8HzJKaihuAB58aBkANXSXUIA+OABeOgSAbQBpYGVkOABrGYh0Ai7e4n7uAF1HTqgevtCpma24UFQNbjgUlnHT41X99c3jli3x1JlMtFPz4Eu4BBMgArSrwB6NPwtdp7A4bI7TN4fFxfH4DO5wLiQ5o0LFrQ7cV6-EAXUhXIGg7DgghEJr+VodfHwwmIrZDLG0qHQIoiejYCBIXhnencDm+HEMm5DUa0Qq8-mC+BITAhEZwADk6BymRq6pEaGh4wADDsAHQhMIRYAlEXjTXa3Vmi3hSI26GmrVAmrGc2hF3Wg0BD4q4BOv1WoA

**Expected behavior**

It would be nice to have an ability to use `.message` as in 3.x

**Screenshots**
```
Property 'message' does not exist on type 'FieldError | FieldErrors<any> | FieldErrors<any>[]'.
Property 'message' does not exist on type 'FieldErrors<any>[]'.  TS2339
```

**Comment by bluebill1049** [comment]
can you provide a codesandbox for this issue?

**Comment by bluebill1049** [comment]
This is probably due to the nested errors object which introduced at v4

**Comment by bluebill1049** [comment]
tested: https://codesandbox.io/s/nostalgic-driscoll-p5ize-delete-p5ize type is working for me

**Comment by kusmierz** [comment]
hey @bluebill1049, have a look at https://codesandbox.io/s/react-hook-form-typescript-n0e5l.

It works perfectly fine when strictly typed (as in your example `useForm<Form>`), but as I would like to have some "universal" wrapper, I have to use more generic `useFormContext()` (which is `useFormContext<Record<string, any>>()` in fact).

Similar issue can be found in your code as well, when we use `useForm<any>` (I know using `any` is bad approach, but my `<InputWrapper />` component is impossible (?) to type better): https://codesandbox.io/s/nostalgic-driscoll-p5ize-delete-zo6v3

**Comment by bluebill1049** [comment]
I am confused here... show me an example of a "universal" wrapper. I believe what we have done here in v4 is correct if you are using TS.

**Comment by kusmierz** [comment]
I wrote a `ControllerTextField` component which basically wraps around `<Controller as={<TextField {...props} /> />` (`TextField` is from `@material-ui/core`), but additionally uses yup's validation schema to add a `label` text, `required` flag and error text (as a `helperText`) from yup. In other words, I'd like to have fully featured MaterialUI's TextField component with yup integration.

I can use `useFormContext<yup.InferType<typeof validationSchema>>()` (instead of generic `useFormContext()`, so I could use `errors[name].message` then), which should solve this issue to me (and it's much better, because it's typed)... but I was just wondering, if the issue described above is a bug or a feature :) You can't easily use non-typed `useForm()` and `error.message`, as seen here: https://codesandbox.io/s/nostalgic-driscoll-p5ize-delete-zo6v3. If it is intended action, please just ignore this bug report ;)

**Comment by bluebill1049** [comment]
Yes, it's intended action to have better Type support for `errors`, that's was also one of the most requested features to moving away from falt `errors` object (due to optional changing becoming more popular).

**Comment by dimitir** [comment]
(errors.email as any)?.message it's work for me
email it's you fildName
