### ISSUE TITLE
Can't bundle CRA with v7.21.1

### ISSUE THREAD

**Issue by ddolcimascolo** [react-hook-form/react-hook-form#7251]
### Version Number

7.21.1

### Codesandbox/Expo snack

https://github.com/ddolcimascolo/react-hook-form-issue-7251

### Steps to reproduce

```
npx create-react-app react-hook-form-bundling-issue
cd react-hook-form-bundling-issue
npm i --save -E react-hook-form
```

Then use the lib in its simplest form

```diff
import logo from './logo.svg';
import './App.css';
+
+import { useForm } from 'react-hook-form'

function App() {
+  const { register } = useForm();
+
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
+      <div>
+        <form>
+          <input {...register('myField')} />
+        </form>
+      </div>
    </div>
  );
}

export default App;
```

Build the app

```
npm run build
```

### Expected behaviour

Build succeeds

### Relevant log output

```shell
node_modules/react-hook-form/dist/index.esm.mjs
Can't import the named export 'createContext' from non EcmaScript module (only default export is available)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
provide more detail and a GitHub repo if you have plz: https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by ddolcimascolo** [comment]
On my way :)

**Comment by ddolcimascolo** [comment]
Reproduction steps + repo added

**Comment by bluebill1049** [comment]
thanks.

**Comment by bluebill1049** [comment]
publishing 7.21.2 thanks for the reporting

**Comment by evocateur** [comment]
@ddolcimascolo If you could verify #7261 works in your project, that would be very appreciated.

**Comment by ddolcimascolo** [comment]
Ah sorry I didn't post back 😅

This was actually handled without me being involved! Our dependency bot (renovate) did pick up v7.21.2 and updated the pull request, our pipeline went green and got merged :)

So yes, I can confirm v7.21.2 works as expected

Thx guys, keep up the great work

David

**Comment by bluebill1049** [comment]
would you like to confirm @ddolcimascolo 
yarn add react-hook-form@7.21.3-beta.0

i have tested and it's building correctly for me.

**Comment by ddolcimascolo** [comment]
Hi @bluebill1049 

Sorry I'm late :astonished: 

I can confirm that v7.21.3-beta.0 builds fine.

Cheers,
David
