### ISSUE TITLE
Errors are not cleared for arrays

### ISSUE THREAD

**Issue by chriscarrillo** [react-hook-form/react-hook-form#726]
**Bug Overview**
I have `referrals[0].name`, `referrals[0].email`, `referrals[1].name`, `referrals[1].email`, `referrals[2].name`, `referrals[2].email`. The fields with index `0` are the only required fields. After filling out the first name and email, I still get an error on the form and `isValid` is `false`.

**To Reproduce...**
1. Create a form with some inputs having the name of an array with the corresponding index and value.
2. Set the submit button's `disabled` state to `!isValid`.
3. Observe the behavior.

**Codesandbox**
I have created a Codesandbox to reproduce the bug. The `console.log`'s will help you see the issue more clearly.
https://codesandbox.io/s/react-hook-form-array-errors-tuegg

**Expected Behavior:**
The array should not be shown in the errors.

**Screenshots**
The inputs:
![image](https://user-images.githubusercontent.com/22056205/71522172-39963f80-2889-11ea-9e34-24b4e8cb1399.png)

The console output:
![2019-12-27 09_11_30-Window](https://user-images.githubusercontent.com/22056205/71522132-1075af00-2889-11ea-9e21-c541e12c05d4.png)

**Specifications**
OS: Windows 10 Pro, Version 1809
Browser: Google Chrome, Version 79.0.3945.88

Please let me know if I can provide any further details. Thanks in advance! :)

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-array-errors-fix-8ewfq

please reverify for me as well :) 

4.2.2-beta.1

then we release the patch

**Comment by bluebill1049** [comment]
i will release this patch and you can verify with that patch

**Comment by chriscarrillo** [comment]
It looks like it's working! Thank you!
