### ISSUE TITLE
`handleSubmit` should return value from `SubmitHandler`

### ISSUE THREAD

**Issue by petercpwong** [react-hook-form/react-hook-form#7278]
**Is your feature request related to a problem? Please describe.**
Currently, `handleSubmit` only returns a Promise resolving to void, which makes sense when it's being passed as a callback to a form's `onSubmit`. However, there are times when we would want to get the value returned by the `SubmitHandler` (for example, data returned by the server), especially if the `SubmitHandler` is a function from a third-party library.

**Describe the solution you'd like**
I've already submitted a pull request: https://github.com/react-hook-form/react-hook-form/pull/6817

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by bluebill1049** [comment]
thanks for the feature request, ping on the board.

**Comment by plrthink** [comment]
We're also waiting for this feature.

**Comment by petercpwong** [comment]
It's an easy code change and I've already submitted a PR. Just waiting for community support to greenlight this new feature.

**Comment by petercpwong** [comment]
@bluebill1049 Any chance we can merge in the PR? It's a very small non-breaking change with no likelihood of causing a regression. It's very unlikely existing users of the library depend on `handleSubmit` to always return `undefined`.

**Comment by bluebill1049** [comment]
@petercpwong the new Form component exposes the `fetcher` prop would that resolve your issue?

```tsx
<Form
  fetcher={(action) => {
    const response = await fetch(action)
  }}
/>
```
