### ISSUE TITLE
issue: Unexpected behaviour with isDirty and dirtyFields

### ISSUE THREAD

**Issue by mydesweb** [react-hook-form/react-hook-form#7283]
### Version Number

7.22.0

### Codesandbox/Expo snack

https://snack.expo.dev/

### Steps to reproduce

1. render a field (with a default date)
2. change the date
3. change again the field to the default date 

If I declare the default field value with `defaultValues` inside useForm everything works as expected but if I declare the default field value inside Controller wrapper using `defaultValue`  prop after the step 3 the field remains dirty.

### Expected behaviour

After step 3 isDirty should be **false** and dirtyFields should be an empty object.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
expected behaviour.

**Comment by mydesweb** [comment]
@bluebill1049 since I only provide a defaultValue in Controller I think it can be considered the only source of truth and we should know if the actual value is the same as defaultValue.

**Comment by mydesweb** [comment]
@bluebill1049 you already mention in the documentation that if defalutValues are not provided will fall back to defaultValue. I don't think that having different behaviours is a good idea. Seems confusing to me.

**Comment by bluebill1049** [comment]
Thanks for the feedback, it will fallback, but noy means we capture or own that defaultValue inside hook form. Its an external state.

**Comment by bluebill1049** [comment]
It's not only about Controller, library such a hook need to consider for native input as well. eg `defaultChecked` `defaultValue`, so conclusion it's required to provide a defaultValues for hook form to work out dirty correctly.
