### ISSUE TITLE
issue: build v7.20.5 esm contains arrow functions, Hope to support es5, Which version supports es5 ??

### ISSUE THREAD

**Issue by guangwen** [react-hook-form/react-hook-form#7288]
### Version Number

^v7.20.5

### Codesandbox/Expo snack

no

### Steps to reproduce

see https://github.com/react-hook-form/react-hook-form/issues/210
build v7.20.5 esm contains arrow functions, Hope to support es5, Which version supports es5 ??

### Expected behaviour

Hope to support es5, Which version supports es5 ??

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
no longer support with v7, you can downgrade to v6 with ie build.
