### ISSUE TITLE
issue: FieldPath slows down TypeScript considerably

### ISSUE THREAD

**Issue by felixschorer** [react-hook-form/react-hook-form#7290]
### Version Number

7.20.1

### Codesandbox/Expo snack

https://codesandbox.io/s/charming-browser-9ujqf?file=/src/App.tsx

### Steps to reproduce

1. Open `App.tsx` in the provided repo link.
2. Change the value of the `name` prop on any of the `<Controller />` to an invalid path.
3. Wait for TS to recognize the mistake.
4. Make further changes.

Typescript will come to a crawl:
- Simple changes will take seconds to process.
- IntelliSense becomes unusable.

### Expected behaviour

Changes shouldn't take multiple seconds to process on complex form data.

The issue seems to be the definition of the `FieldPath` type and similar types like `ArrayPath`.
These types eagerly enumerate all paths of an object type.
The resulting union type becomes excessively big for nested objects containing complex objects like `Date`s.

This could be fixed by lazily evaluating the paths. See [`ts-toolbelt`](https://github.com/millsp/ts-toolbelt)'s [`AutoPath`](https://millsp.github.io/ts-toolbelt/modules/function_autopath.html).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
what's under the hood: https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html and this is a design limitation.

**Comment by bluebill1049** [comment]
> This could be fixed by lazily evaluating the paths. See ts-toolbelt's AutoPath.

thanks for the suggestion with `AutoPath` as well, I will evaluate it see if this can be potential solution.

**Comment by bluebill1049** [comment]
cc @barrymay @kotarella1110

**Comment by bluebill1049** [comment]
That `AutoPath` really is just `get` type, it doesn't replace the functionality with `FieldPath` to produce autocomplete/hint for fields name when register with inputs. I don't think this will resolve the underlining limitation. Correct me if I am wrong here.

**Comment by felixschorer** [comment]
We're currently using `AutoPath` like this.
https://codesandbox.io/s/vigilant-flower-oydoe?file=/src/App.tsx

Basically, `name` is just constrained to `string`.
If `name` isn't a valid path into the object, then every type using that path evaluates to never.

**Comment by felixschorer** [comment]
> That `AutoPath` really is just `get` type, it doesn't replace the functionality with `FieldPath` to produce autocomplete/hint for fields name when register with inputs.

`AutoPath` triggers autocompletion. Typing `"prop1."` will suggest any of `"prop1.prop0" | "prop1.prop1" | "prop1.prop2" | "prop1.prop3" | "prop1.prop4" | "prop1.prop5" | "prop1.prop6" | "prop1.prop7" | "prop1.prop8" | "prop1.prop9"`, but nothing more. If you continue typing after selecting one of those, it will suggest the next path segment and so forth.

This works great in editors which use the vanilla Typescript Language Server, e.g. VS Code, Atom, etc. WebStorm sadly doesn't show any suggestions.

**Comment by bluebill1049** [comment]
thanks, @felixschorer will look into it a bit more this weekend.

**Comment by bluebill1049** [comment]
@felixschorer would you be interested to send us a PR?

**Comment by felixschorer** [comment]
I can have a look.

**Comment by felixschorer** [comment]
@barrymay I understand your concerns. Something like this needs to be thoroughly type tested as it shouldn't break existing code.

[`ts-toolbelt`](https://github.com/millsp/ts-toolbelt)'s [`AutoPath`](https://millsp.github.io/ts-toolbelt/modules/function_autopath.html) can't be used anyways as hooks like `useFieldArray` impose further constraints on the path other than it being valid. In the case of `useFieldArray` any path, which doesn't point to an array, would have to be rejected too.

I've tinkered around with this in this [TS playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBACghsAFgZQgcwLYQHbCgXigGdgAnAS2zSgB8psBXDAIwlICh3RIpkwAbcsAA88JFAgAPYDgAmRYmUpoAfAVgJEE6XIUADACQBvSgDM2UABIQ4sgL4A6Y2YsAVOOX529UdlH9QAPxQANrWtgA0UA4xfIIi7p4qALq+AVAAXBriUjLY8lAARIV+6QHBIcmlZZmhYohVXODQAFIA9pSimtp5BfWomDjAlWqE9T26oS6kVjayVenB4bLVteO5kyHTs5HRMduJ-As1QVCGRgCi0qRwAMYiy1H96Fi4Ko7G7Z1XZHcJHvwnpoBq9hskVO89Kt0llipxuNAAGpwQSyerCVxAnI6fIKZ6DXAjdTrHEFLbYcwzR57BwHAGpVZLOYTXFQADWEBAbVMUFc0PKoWpMQcyNR6NcYTmySiPxu9wxAKxKBeQxGKX5-iylTSAS1jQRUAAIqQ2mAADJwEgYlkFBjYNnYNoAd2wRMIrhtChCwu21LtDud2FSTNstUq8OaUAA4hAEkrPdllQSwaNEwnyZSdrIoj6KW56Tr-CHZAmOVyeR6NacYwlJbZpVBZX8FZ4lSDVeCVFWstgIAA3NirLJ8po8ADCbQwAljEHqAEkp-xhKtMYW0xtWSQKFQIqsAKrqf2Ol1RVbIEm9PHAlWE1KEOJCLpIFSn9KIi+TfGg7WEUXkNGaBiUTnpoL7sKmqwABRVh+rJfNgwjvqBa4nKcVaodBqFYQENZAVASHPgmB7odhZTBOMJGkbq9D9oOVHpAAlLQUDwcIxqmhaVoEYgEKUbUrHcV2jHMax3oxNxMrXM2ZbctGsZ4YJbY3sAKRdqO0ATouM7ivGG4FFuyhRAehBHoGqaadOMjzoueH1EZakGhZDAyBiqYenpCgesEHo9rRHDsLIEC3PwcCkNAph2vc5BtNgUBoPJq6wfpShUCokFtMwABWw5RGAmhZE5LkWfw2mAYlmhRIwLBsBCDFZLhq4PiI9S8ewtwxSQUAyJ1hDxcAkFGKYbRtFkRjMKFWQACwAEx2HYUSFENbQOONpCFAxQA). Basically `get` rejects any path which isn't valid or doesn't point at a `number`. This is my first attempt, so the types are still a bit messy.

**Comment by bluebill1049** [comment]
Thanks, @felixschorer and @barrymay's input, I agree with all comments above. I see the light when I saw the `AutoPath` works with `string` and lazy evaluating the input path. This is huge! It fundamentally solves some of the type "difficulty" for reusable components and performance issues that could lead to when forms type is a generic of complex data. I think even ts-toolbelt is stopped being maintained, would be good to learn and borrow the idea for the `AuthPath`. This could be a huge improvement.
