### ISSUE TITLE
issue: using reset in HeaderBackButton makes all element undefined but does not clear out field array

### ISSUE THREAD

**Issue by hanchenjhc** [react-hook-form/react-hook-form#7293]
### Version Number

7.22.1

### Codesandbox/Expo snack

https://codesandbox.io/embed/react-hook-form-reset-usefieldarray-forked-yk7g4?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce

Thanks for the previous fix on the similar issue. However that doesn't **_entirely_** address the issue I'm having. For resetting through onPress of HeaderBackButton only makes all elements in the field array `undefined`, but it does not clear out the array. So we are left with an array with n undefined element.

1. Go to https://codesandbox.io/embed/react-hook-form-reset-usefieldarray-forked-yk7g4?fontsize=14&hidenavigation=1&theme=dark
2. Click on "Append"
3. Click on "Back"
4. field array has 1 element that is `undefined`(if you click on "Append" more times, you will have more undefined elements)

### Expected behaviour

field array is empty with 0 elements. Just like how clicking "RESET" would work.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
you need to read the doc on the usage, there are so many things that are incorrect here.

- append argument is required
- no defaultValue is required for the field array
- input name is dot syntax only for v7

please address all of those above first: https://react-hook-form.com/api/usefieldarray

**Comment by hanchenjhc** [comment]
OK. The example is based on [your documentation here](https://react-hook-form.com/api/useform/reset). But I'll update the sandbox based on your comment.

**Comment by bluebill1049** [comment]
which example? screenshot plz

**Comment by bluebill1049** [comment]
found it. fixing

**Comment by hanchenjhc** [comment]
I've updated the sandbox here: https://codesandbox.io/s/react-hook-form-reset-usefieldarray-forked-yk7g4?from-embed=&file=/src/index.js

Could you take another look?

**Comment by hanchenjhc** [comment]
Just saw another behavior to make this bug more obvious. 
1. click "Append"
2. click "Back", which removes the input
3. click "Append"
Expected: to see 1 input
Actual: 2 inputs appeared

**Comment by bluebill1049** [comment]
`<button type="button" onClick={() => reset()}>` need to provide a payload for the reset.

**Comment by hanchenjhc** [comment]
Updated sandbox with a payload for `reset` in both usages. The one in plain `button` is working as expected. The one passed into `HeaderBackButton` does not clear out the field array.
