### ISSUE TITLE
Nested form is not possible

### ISSUE THREAD

**Issue by abhijitkadam** [react-hook-form/react-hook-form#7295]
HTML does not allow nested form.
However with react if we want to have a conditional nested "form" that renders inside parent form that is not possible.
The inside child form will have its own validation and state.

Need a custom tag like <Form> (in caps) that will support nesting with independent state and validation.

**Comment by bluebill1049** [comment]
please read the doc on register API

**Comment by abhijitkadam** [comment]
Hi, There is a support of nested fields inside same form. 
Not the nested forms
`<form>... <form>...</form></form>`

Above HTML will prevent so `<Form>... <Form>...</Form></Form>`

So I used  div instead of form with no submit handler

`<div >... <CustomInLineChileForm/>...</div>`

Then submitted the form manually on button click:

```
const handleFormSubmit = () => {
        handleSubmit(onFormSubmit)();
    }
```
