### ISSUE TITLE
Controller can't use number validators

### ISSUE THREAD

**Issue by Dru89** [react-hook-form/react-hook-form#730]
**Describe the bug**
Number validators like `min` and `max` don't work when you're using a `<Controller />` to wrap a component.

**Codesandbox link**
https://codesandbox.io/s/amazing-lichterman-ocm5j

**Expected behavior**
`min` and `max` should still function properly whenever you're using `<Controller />` if the value is a number.

**Additional context**
It looks like the `min` and `max` validators only work if the `<input />`'s type is `"number"`. https://github.com/react-hook-form/react-hook-form/blob/60b5af5197acfa4dcffdd9e034c4fa1e34b6c089/src/logic/validateField.ts#L86-L102

And when you use `<Controller />`, you're sort of foregoing the whole `ref` altogether: https://github.com/react-hook-form/react-hook-form/blob/60b5af5197acfa4dcffdd9e034c4fa1e34b6c089/src/controller.tsx#L93-L110

I thought about submitting a pull request, but I wasn't sure what the best option was for fixing this. Some options I was thinking about:

1. The `type="number"` check in `validateField` could be removed and instead just check to see if the value is "number-like". Or if `typeof value === "number"` as a possible check.
2. Alternatively, instead of using `min` and `max` for dates, too, there could be a separate rule like `minDate` and `maxDate`, but those would be breaking changes.
3. There could be a `type` property on `<Controller />`. This feels like a bit of a hack, though, and I can't think of any other reasons to declare a "type" on controller.

**Comment by bluebill1049** [comment]
i forgot to add this into the doc, `min` and `max` is not going to work with Controller. Use `validate` function instead. Doing number/date check is not small check. (i did similar thing before)

**Comment by bluebill1049** [comment]
Doc is updated :)

**Comment by bluebill1049** [comment]
actually think twice, maybe we can do the following:
