### ISSUE TITLE
issue: useFieldArray key on form cannot be re-dirtied after calling resetField on it

### ISSUE THREAD

**Issue by nbpeth** [react-hook-form/react-hook-form#7307]
### Version Number

7.22.1

### Codesandbox/Expo snack

https://stackblitz.com/edit/react-hook-forms-xj4hgj?file=index.js

### Steps to reproduce

1. Go to https://stackblitz.com/edit/react-hook-forms-xj4hgj?file=index.js
2. Change values in "useFieldArray fields" inputs - `dirtyFields`, `isDirty`, `fields`, `useWatch` dumped onto the DOM 
3. Verify the fields and dirty state correctly getting updated as input values are changed
4. Click "ResetField: Array - target individual field" to show the field in the array getting reset, un-dirtied and able to be re-dirtied
5. Dirty the fields again
6. Click "ResetField Array" button and note that the dirty state gets reset as well as the values, but the array cannot be re-dirtied

### Expected behaviour

invoking `resetField` on the name of a `useFieldArray` object should allow the fields in the array to re-dirty the form

### What browsers are you seeing the problem on?

Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
<img width="1088" alt="Screen Shot 2021-12-17 at 8 50 52 am" src="https://user-images.githubusercontent.com/10513364/146454304-15a131b2-aca8-4c86-9082-0622931e68da.png">

could you update your example?

**Comment by nbpeth** [comment]
hey @bluebill1049 are you just seeing a blank page? This is what I see when I click the link 
![image](https://user-images.githubusercontent.com/10249534/146456074-0ec71e99-5332-4e13-94a5-dba61f9c9db6.png)

**Comment by bluebill1049** [comment]
yep blank page, even with hard refresh, could you try codesandbox?

**Comment by nbpeth** [comment]
here you go https://codesandbox.io/s/distracted-water-8g1k2?file=/src/App.js

**Comment by bluebill1049** [comment]
> Reset an individual field state.

`resetField` is used for input field not supporting object/array nodes at the moment. use `reset` API instead

**Comment by nbpeth** [comment]
are their plans to implement this feature? I have a work around at the moment, to manually reset each field, but it's pretty bulky and doesn't scale well to the model.

I cannot use `reset` for my use case, unfortunately - I have a form that needs to know exactly which fields are dirty - and `reset` will clear `isDirty` on the formLevel, making `dirtyFields` out of sync / unreliable.

My form is a multi-component form that has a cancel / apply buttons that I need to be able to roll back changes (or allow changes) for that one specific field while maintaining the previous changes. 
For instance if I have default values `{a:[{b:1}]}` and I update them to `{a:[{b:2}]}`, then `a` is dirty and this is my new commit point on the data. Then if I go back to the form and update them to `{a:[{b:3}]}` - and I want to roll back those changes to the last change `{a:[{b:2}]}` - I still want this to be considered dirty

**Comment by bluebill1049** [comment]
> are their plans to implement this feature? I have a work around at the moment, to manually reset each field, but it's pretty bulky and doesn't scale well to the model.

not at the moment (you can send a feature request instead and see how the community reacts to it), if there will be such implementation in the library it would quite similar to what have already done. `resetField` really is focused on a single input.

**Comment by nbpeth** [comment]
alright, thanks for taking the time to look into it!

**Comment by bluebill1049** [comment]
np @nbpeth going to close this issue, for now, feel free to send a PR if you want, I can send it to the backlog.
