### ISSUE TITLE
issue: The value of the last radio will set the correct value when used in combination with Web Component and "Watch" method

### ISSUE THREAD

**Issue by Rensvl** [react-hook-form/react-hook-form#7310]
### Version Number

7.22.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-playground-forked-n71qn?file=/index.js

### Steps to reproduce

1. Click on one of the radio inputs (only the last radio will set the correct value the others will set NULL).

- When the watch method is removed, the value is correctly set for all the radio input after pressed.
- When the Web Component is removed, the value is correctly set for all the radio input after pressed.
  

### Expected behaviour

I expect all the radio values will set correctly.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
doesn't support at the moment, you can upvote this feature request: https://github.com/react-hook-form/react-hook-form/projects/1
