### ISSUE TITLE
issue: defaultValue isn't removed when using Controller shouldUnregister property

### ISSUE THREAD

**Issue by luizeboli** [react-hook-form/react-hook-form#7313]
### Version Number

7.22.1

### Codesandbox/Expo snack

https://codesandbox.io/s/musing-feistel-pc9ko?file=/src/App.js

### Steps to reproduce

1. In this example theres 2 boolean fields, one using `Controller` and another using `register`. Both are using `shouldUnregister`
2. There's also a `Toggle` button that is used to mount/unmount these fields
3. When toggling `register` input, the defaultValue is removed and in the next mount, the checkbox has `false` value
4. When toggling `Controller` input, the defaultValue is not removed and in the next mount, the checkbox persists it's `true` default value

### Expected behaviour

In this example, `booleanController` field should not have `true` value after unmount as docs:

![image](https://user-images.githubusercontent.com/13091635/146574734-303b6c23-ea2a-4c48-b6b0-197ba340fda7.png)

[Controller doc](https://react-hook-form.com/api/usecontroller)

### What browsers are you seeing the problem on?

Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luizeboli** [comment]
Looks like this bug has been introduced in version 7.19.1.

I'm gonna try to investigate a little bit further

**Comment by luizeboli** [comment]
Well, this came from #7001.

So, is this the expected behavior? To keep defaultValue when using Controller? Why it differs from `register`?

**Comment by bluebill1049** [comment]
hey, @luizeboli thanks for the issue report and including the investigation. yea, this is expected for `shouldUnregister: true`, really `shouldUnregister: true` is more aligned with native form behavior, so input state lives inside each input.

**Comment by luizeboli** [comment]
@bluebill1049 sorry it is not clear for me. shouldUnregister must remove value from defaultValues also? Thats not happening now

**Comment by bluebill1049** [comment]
thanks, @luizeboli I can see the inconsistency here, let me address that.

**Comment by bluebill1049** [comment]
looking close #7001 is an incorrect fix because, after input mounted with `shouldUnreegister: false` (default), the input value will be an empty string hence the default value is not showing. I am reverting that fix.

**Comment by luizeboli** [comment]
Thanks @bluebill1049 for your effort and amazing work done with this lib👍
