### ISSUE TITLE
Empty form state in v7.22.x

### ISSUE THREAD

**Issue by jscheel** [react-hook-form/react-hook-form#7314]
### Version Number

7.22.x

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-formstate-dirty-touched-submitted-forked-wjk0k

### Steps to reproduce

I've attached the codesandbox link from the examples directory. If you switch the react-hook-form version to 7.22.1, you will see that the formState is now empty. Guessing this has to do with the proxy object, but it works in v7.0.0-alpha.

### Expected behaviour

The formState is still accessible.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
It's expected behavior, you just need to read it or deconstruct it.

**Comment by jscheel** [comment]
@bluebill1049 fair enough, but does that mean there is no clean way to debug the formState like in the repo's example? Should that example be updated to deconstruct the formState with all the values pulled out?
