### ISSUE TITLE
issue: `watch`ing array value doesn't trigger `useMemo` on changes

### ISSUE THREAD

**Issue by awesomeunleashed** [react-hook-form/react-hook-form#7315]
### Version Number

7.22.1

### Codesandbox/Expo snack

https://codesandbox.io/s/silly-cdn-kzcgh?file=/src/App.tsx

### Steps to reproduce

1. Change the value of one of the dropdowns
2. See that the "Unused Values" changes after the re-render, but "Memoized Unused Values" does not

### Expected behaviour

I would expect that the `useMemo` would recalculate, since `options` changed. React is expecting that a dependency for `useMemo` (or `useEffect`, or `useCallback`, etc.) will change reference equality if it changes, but this doesn't appear to happen with `watch` in this case. The result of `watch` for an array value therefore seems to be unsafe to use in any of those hooks.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> watch result is optimised for render phase instead of useEffect's deps, to detect value update you may want to use an external custom hook for value comparison.

https://react-hook-form.com/api/useform/watch

**Comment by awesomeunleashed** [comment]
> > watch result is optimised for render phase instead of useEffect's deps, to detect value update you may want to use an external custom hook for value comparison.
> 
> https://react-hook-form.com/api/useform/watch

I see; I guess I forgot about and/or misinterpreted that bullet point. Sorry about that.

Do you have any particular suggestions for existing external hooks/patterns that would do this well? I've come up with a couple ways that seem to work:

```ts
  const options = watch("options");

  // This option seems efficient, though somewhat complex for the problem
  const [memoableOptions, setMemoableOptions] = React.useState(options);
  React.useEffect(() => {
    const subscription = watch((value, { name }) => {
      if (name?.startsWith("options")) {
        setMemoableOptions(cloneDeep(value.options as Option[]));
      }
    });
    return () => subscription.unsubscribe();
  }, [watch]);

  // This option (using lodash) is simple, but requires doing a deep compare every render,
  // in addition to setting state mid-render
  const [memoableOptions2, setMemoableOptions2] = React.useState(
    cloneDeep(options)
  );
  if (!isEqual(options, memoableOptions2)) {
    setMemoableOptions2(cloneDeep(options));
  }
```
...but I don't particularly like either one of them. Any advice is appreciated!
