### ISSUE TITLE
issue: watch with useFieldArray

### ISSUE THREAD

**Issue by akilansengottaiyan** [react-hook-form/react-hook-form#7318]
### Version Number

^7.20.0

### Codesandbox/Expo snack

https://codesandbox.io/s/watch-with-usefieldarray-forked-8ez2w

### Steps to reproduce

Note : I am using the fork of [watch with useFieldArray codesandbox](https://codesandbox.io/s/watch-with-usefieldarray-e2d64) provided in the doc and just updated the version in the **package.json** with the same example code.
Also this is working fine in the versions below 7.20.0. Probably, some other fix should have breaked it.
1. use **useFieldArray** hook with a field containing array of nested objects.
2. **watch** the above declared field.
3. append/remove the useFieldArray fields.
4. Now the **watch** field would trigger the re-render ( we could see in the console).
5. Edit the nested object in a particular array index.
6. Now the **watch** field is not triggering the re-render ( we could see in the console). 

### Expected behaviour

The **watch** field should trigger the re-render whenever some data changes inside the **useFieldArray**.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akilansengottaiyan** [comment]
I would like to fix the above mentioned bug once acknowledged. Cheers

**Comment by bluebill1049** [comment]
hey, @akilansengottaiyan i couldn't reproduce the issue, could you provide some more detail? I am using the latest.
<img width="328" alt="Screen Shot 2021-12-20 at 9 09 37 am" src="https://user-images.githubusercontent.com/10513364/146692550-81a376e4-381b-45de-9bae-9eab627efd5c.png">

**Comment by akilansengottaiyan** [comment]
Hey @bluebill1049. Thanks for the reply. In the [sandbox](https://codesandbox.io/s/watch-with-usefieldarray-forked-8ez2w) i provided above, on editing the input fields, renderCount is not getting incremented and there is no console logs to match the current state. But if we remove or append, its getting re-rendered with the current updated state.
I am not sure how you are able to pull-off the above attached screenshot. Kindly make sure the version you used in the above code is **^7.20.0**.

**Comment by bluebill1049** [comment]
I see the problem now: `{...register(`test.${index}.firstName`)}` please use dot notation.

> we are using dot syntax only for typescript usage consistency, so bracket [] will not work for array form value.

https://react-hook-form.com/api/useform/register

**Comment by akilansengottaiyan** [comment]
Aah. I missed it. Thanks a lot. @bluebill1049

**Comment by bluebill1049** [comment]
np @akilansengottaiyan 👍  thanks for rising the issue and even being willing to fix it.
