### ISSUE TITLE
Using <Controller /> with react-select

### ISSUE THREAD

**Issue by vgandzyuck** [react-hook-form/react-hook-form#732]
Hello, trying to use < Controller /> with [react-select](https://github.com/JedWatson/react-select)

![image](https://user-images.githubusercontent.com/22315319/71542626-b4d71e80-2979-11ea-8f81-aad4ee79addf.png)

This happens because react-select 'onChange' event returning result of onChange event (value) not event target. Could you please work around this?

**Comment by bluebill1049** [comment]
There is an example on the website: http://localhost:8000/api#Controller

**Comment by vgandzyuck** [comment]
I was following this example, I can provide my source code

**Comment by bluebill1049** [comment]
Do a codesandbox

**Comment by vgandzyuck** [comment]
Issue was resolved, thank you much
