### ISSUE TITLE
Custom message in native validation does not work

### ISSUE THREAD

**Issue by I-Lotus** [react-hook-form/react-hook-form#733]
**Describe the bug**
I try to use native html validation and I want to set custom message for required field. But I see the regular message of browser instead of mine. I have tried an exapmale from https://github.com/react-hook-form/react-hook-form/blob/master/examples/nativeValidation.tsx
and get the same. It does not work.

**To Reproduce**

**Codesandbox link**
Include a codesandox will help us to investigate the issue quicker.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [Version 79.0.3945.88 (Official Build) (64-bit)]

**Additional context**

**Comment by bluebill1049** [comment]
Native validation only working on v3, it's been removed on v4. If you switch your version to latest V3, then it should work.

**Comment by I-Lotus** [comment]
> Native validation only working on v3, it's been removed on v4. If you switch your version to latest V3, then it should work.

I am using "react-hook-form": "^3.29.4"

**Comment by bluebill1049** [comment]
oh you want to supply a codesandbox?

**Comment by I-Lotus** [comment]
@bluebill1049 Ok. I will prepare example on codesanbox how I do.

**Comment by bluebill1049** [comment]
Did you manage to reproduce this in a codesandbox?

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-native-validation-ez5ww
