### ISSUE TITLE
issue: useFormField functions set whole dirtyFields Object

### ISSUE THREAD

**Issue by chamabreu** [react-hook-form/react-hook-form#7338]
### Version Number

7.22.3

### Codesandbox/Expo snack

https://codesandbox.io/s/usefieldarray-dirtyvalues-1t71j?file=/src/App.tsx

### Steps to reproduce

1. Go to [This Codesandbox](https://codesandbox.io/s/usefieldarray-dirtyvalues-1t71j?file=/src/App.tsx)
2. Read the Description and try it yourself.
3. Typing in the single Fields marks the sections correkt as dirty (watch also Console for a console log of dirtyFields)
4. But adding or removing a pet, sets the dirtyValues to a whole Object (filled with false values). But this makes it impossible to simple check if a nested Object contains real dirty values.

### Expected behaviour

If I append or remove a field (pet), the dirtyFields should only contain the specific parent object and the pets Array, not the whole formData.
With the implementation now, I can not check a "parent Object node" for real dirtyValues, because it is filled with props, even if they are false.

Also if I hover over the `formState.dirtyFields.personalData` it shows me it could only `true | undefined`, but in reality it contain fields with `false` values.
![image](https://user-images.githubusercontent.com/31648926/147051647-411f4325-aea7-4732-b409-75d56c90aa9d.png)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is expected behavior, will update the type to boolean.
