### ISSUE TITLE
issue: Obtaining formState.errors causes the component to refresh

### ISSUE THREAD

**Issue by zhnoah** [react-hook-form/react-hook-form#7339]
### Version Number

7.22.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-adapting-existing-form-forked-gs4u5?file=/src/index.js

### Steps to reproduce

1. Release the comment on line 33
2. Form input
3. View the browser's console panel

### Expected behaviour

"Select refresh" should only be printed once during initialization，
Did I miss something?

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/useform/formstate

> formState is wrapped with a Proxy to improve render performance and skip extra logic if specific state is not subscribed to. Therefore make sure you invoke or read it before a render in order to enable the state update.

please refer to the doc above for formState.
