### ISSUE TITLE
Is there an example using Controller with Antd Input

### ISSUE THREAD

**Issue by ayepRahman** [react-hook-form/react-hook-form#734]
Hi, loving the library so far. Recently with the new update using Controller component to wrap around Ui library and iam excited to try it out. 

Face some issue not able to submit the form when using Controller with Antd input

**Comment by bluebill1049** [comment]
hey @ayepRahman can you share a codesandbox with this issue?

**Comment by ayepRahman** [comment]
Hey @bill, found the issue. Controller works fine, Its the way ive nested my Form component as a child of both react apollo mutation and react-hook-form. Thats what causing the form to rerender hence the Form component rerender.

**Comment by bluebill1049** [comment]
awesome @ayepRahman glad you work it out.
