### ISSUE TITLE
issue: useFieldArray has wrong types on keyValue

### ISSUE THREAD

**Issue by chamabreu** [react-hook-form/react-hook-form#7346]
### Version Number

7.22.3

### Codesandbox/Expo snack

https://codesandbox.io/s/keyname-only-id-l8l89?file=/src/App.tsx

### Steps to reproduce

Create an useFieldArray and try to set the keyName to some string, like the [documentation says](https://react-hook-form.com/api/usefieldarray) - or:

1. Go to [this sandbox](https://codesandbox.io/s/keyname-only-id-l8l89?file=/src/App.tsx)
2. Hover about the error on `keyName` and read the message
3. The string is only assignable to `'id'` or `undefined` by the typing.

"workaround" is also found in the codesandbox.

### Expected behaviour

The string I choose is accepted, and I should not be limited to `'id'` or `undefined`, which does not make any sense at all.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
```
const { fields } = useFieldArray({ //wihtou the generic 
  control,
  name: "customers",
  keyName: "keyId"
});
```

if name `id` is the issue, then this PR will resolve the problem you will no longer need to change the keyName
