### ISSUE TITLE
issue: Disabled field handling is inconsistent with native browser behavior

### ISSUE THREAD

**Issue by LadyKamille** [react-hook-form/react-hook-form#7347]
### Version Number

7.22.3

### Codesandbox/Expo snack

https://codesandbox.io/s/mystifying-kare-smbzu?file=/src/App.js

### Steps to reproduce

1. Verify loaded version of react-hook-form in codesandbox dependencies is set on the latest version
2. Click on "Submit" for all of the provided forms
3. See validation errors and current form values

I have also provided a table of the current version our software is on (7.12.2), the version that we believe broke our current implementation (7.13.0), and the latest at the time of this issue (7.22.3).

### Expected behaviour

React Hook Form behavior matches the native form behavior:

1. Value is displayed to user
2. Input cannot be modified
3. Input has :disabled styling
4. On submit, field is not validated
5. On submit, field value is undefined

Here is a link to a vanilla JS sandbox: https://codesandbox.io/s/focused-germain-gcr5m?file=/index.html

On version 7.23.2 of react-hook-form, the only combination of HTML attributes/RHF rules that works as expected is React's `defaultValue` attribute and RHF's disabled rule. Using the RHF default values and RHF disabled rule does not match native browser behavior.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report.

![Screen Shot 2021-12-23 at 10 03 35 am](https://user-images.githubusercontent.com/10513364/147164655-f6ccc512-0f71-4af8-9bab-ac9686875dc3.png)

There are issues with the inline `disabled` attribute and hence we are solving it by providing a new `disabled` prop.  I would only use the inline disabled attribute if the input is completely static. Can you double-check with the `disabled` prop at the `register`.

**Comment by LadyKamille** [comment]
Hi, thanks for getting back to me! There are really two issues here.

The behavior differs between versions. I do expect between versions there could be breaking changes, but also the disabled attribute going from working (7.12.2) to not working (7.22.3) feels like a bug to me.

However, if the expectation is to use the rule now, that's fine, but I would also expect that it would work with RHF's defaultValues. If you look at the sandbox on 7.22.3, defaultValues does not populate disabled fields.

The only time you can set a value for a disabled field is with React's defaultValue on the individual input and using the RHF disabled rule.

**Comment by bluebill1049** [comment]
> The behavior differs between versions. I do expect between versions there could be breaking changes, but also the disabled attribute going from working (7.12.2) to not working (7.22.3) feels like a bug to me.

I wouldn't say it's a bug, perhaps a potential regression. Inline disabled is quite tricky and troublesome when users are toggling with react state. In fact, the disabled have been raised quite a few bugs and I have tried to attend with quite a few solutions and hitting the wall. I probably showing green on your table, but there are other use cases which going to fail, but `disabled` prop is definite the bug solver, it gives react hook form context when the state gets updated.

 > However, if the expectation is to use the rule now, that's fine, but I would also expect that it would work with RHF's defaultValues. If you look at the sandbox on 7.22.3, defaultValues does not populate disabled fields.
 
 I think this maybe a regression, i will take a look at it.
