### ISSUE TITLE
issue: formState.errors wrong if update array field before swap

### ISSUE THREAD

**Issue by HelKyle** [react-hook-form/react-hook-form#7348]
### Version Number

7.22.3

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-k82px?file=/src/index.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-forked-k82px?file=/src/index.js
2. Click on [VALIDATE]
3. Click on [UPDATE AND SWAP]
4. Click on [UPDATE AND SWAP]
5. Input elements are having error both

### Expected behaviour

The empty input display error only

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Thanks for the issue, I will adjust the code to avoid this problem. however, I would recommend not executing actions one after, as they have an individual set state within, I would remove that additional action into `useEffect`
