### ISSUE TITLE
Controller component && onBlur validation: onBlur on React Select clears the value when triggered

### ISSUE THREAD

**Issue by VGLoic** [react-hook-form/react-hook-form#736]
Hi :wave:

I'm using the validation mode `onBlur` in the `useForm` and using the `Select` of `react-select`. When the `onBlur` event is triggered, my previous set value vanishes for a falsy value.

Is it intentional? :)

If yes, any idea how to elegantly disable this behavior? And I saw that the `handleBlur` of the `Controller` is using a `setValue` with the value extracted from the value of the `onBlur` event, is this what we want instead of just triggering the validation without modifying the value of the input? (in case of the `onBlur` validation mode at least :))

In order to reproduce:
Use this codesandbox (previously used in other issues but with onBlur validation mode): https://codesandbox.io/s/react-hook-form-rhfinput-yjndq
Set a value to the React Select example, click next to it in order to trigger the onBlur event

**Comment by bluebill1049** [comment]
That codesandbox is not working. can you please a codesandbox and follow our issue template.

**Comment by VGLoic** [comment]
Sure, let me close this one and create a clear one! My bad :). Thanks for the quick answer!

**Comment by VGLoic** [comment]
Closed due to bad format and bad codesandbox link
