### ISSUE TITLE
getValues() doesn't cause a re-render when the values change

### ISSUE THREAD

**Issue by Dru89** [react-hook-form/react-hook-form#738]
**Describe the bug**
`getValues()` doesn't cause a re-render when the values change.

Imagine a scenario where you have an input like `name`, and you want to be able to have some text that reads that field when it updates to say `"Hello, {name}"`. Because `useFormContext()` and `getValues()` don't trigger a re-render, you're currently forced to make sure you're capturing the state of the input both locally and in `react-hook-form`.

The only time `getValues()` seems to work is:
* In buttons or things where the user took some action before it was called.
* Whenever the component that calls `getValues()` is forced to re-render for some other reason.

**Codesandbox link**
https://codesandbox.io/s/quizzical-flower-j5ye7

**Expected behavior**
The context should update whenever values change to trigger a re-render. If we don't want to re-render *everything* that uses `useFormContext()`, perhaps there should be a separate `useFormValues()` setup? Or even `useFormValue("name")`?

**Additional context**
My belief is that this is because the form's context doesn't change whenever you change the values. Perhaps because the values objects are being modified directly?

**Comment by bluebill1049** [comment]
if you want re-render, you should use `watch` instead

**Comment by Dru89** [comment]
That makes sense. I’ll close this issue since there’s a solution.
