### ISSUE TITLE
issue: Accessing errors.[fieldName].message for a fieldArray gives type errors (it's seen as array)

### ISSUE THREAD

**Issue by boi87** [react-hook-form/react-hook-form#7381]
### Version Number

7.22.5

### Codesandbox/Expo snack

https://codesandbox.io/s/cars-form-error-object-fjcmx?file=/src/App.tsx

### Steps to reproduce

In the CodeSandBox

1. Select no cars in the form
2. The error appears as expected
3. the code shows a TS error (line 74) when you access the errors object with `errors?.cars?.message`, but it works in the UI:
```
TS2339: Property 'message' does not exist on type '{ name?: FieldError | undefined; value?: FieldError | undefined; }[]'.
```
4. the code will **not** complain if you access it with `errors.cars?.map((err) => err.value?.message).join(' ')`, but will crash the UI because in fact it's not an array

Basically it considers the form field `cars` to be an array, but the error is attached to the form field as "one", as if it were a normal form field.
I think this behaviour is the correct one in my opinion, but the typing is wrong. Hope it makes sense 😅 

### Expected behaviour

The code should not complain, because even though it's a field Array, still it should count as "one" field, not as an array of fields.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
TS2339: Property 'message' does not exist on type '{ name?: FieldError | undefined; value?: FieldError | undefined; }[]'.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
It's not possible for hook form to determine the input is a group of inputs or input of groups, which is the case here. that's why we have introduced https://react-hook-form.com/ts#NestedValue which you have to apply in your use case here.

**Comment by boi87** [comment]
Thanks a lot for the quick answer @bluebill1049 :) 
Using `NestedValue<CarCheckbox[]>` the errors can be accessed without TS errors.

```
type CarCheckbox = { name: Car; value: boolean };

  type CarsForm = {
    cars: NestedValue<CarCheckbox[]>;
  };

errors?.cars?.message // no type errors :) 
```

However my TS is complaining on the `onSubmit={handleSubmit(onSubmit)}` line:

This is the error I'm getting:
```
Types of property 'cars' are incompatible. Type 'CarCheckbox[]' is not assignable to type 'NestedValue<CarCheckbox[]>'.
Property '[$NestedValue]' is missing in type 'CarCheckbox[]' but required in type '{ [$NestedValue]: never; }'.
```  

Not sure why it doesn't happen in the CodeSandBox though...
Do you have any idea about this? Thank you :)

**Comment by danielo515** [comment]
> It's not possible for hook form to determine the input is a group of inputs or input of groups, which is the case here. that's why we have introduced https://react-hook-form.com/ts#NestedValue which you have to apply in your use case here.

That NestedValue type seems very interesting, but the documentation is quite sparse. Can you give a high level overview of what issue is it supposed to fix, and why on the example you have to register the fields out of the field itself (on useEffect) and then just leverage the different setters?
