### ISSUE TITLE
When validateCriteriaMode is set to `all`, new errors aren't reported as long as the old ones are active

### ISSUE THREAD

**Issue by Dru89** [react-hook-form/react-hook-form#739]
**Describe the bug**
When validateCriteriaMode is set to `all`, new errors aren't reported as long as the old ones are active.

For instance, if you have an input that has two validation errors:
* One validation error if any of the characters in the input are uppercase.
* Another validation error if the input contains an `@`

And then you type `D` and blur the field to validate it, you'll correctly receive an error. But if you then adjust the input to be `D@`, you won't get the error about the input having an `@`.

However, if your *initial* value to the input was `D@`, you'll receive both errors.

**Codesandbox link**
https://codesandbox.io/s/cool-bhaskara-99pkr

**Expected behavior**
When there are multiple errors in the input and `validateCriteriaMode` is set to "all", all of the input errors are reported.

**Additional context**
My best guess is that what's happening here is that the `errors` object is being *directly modified*, causing the `useFormContext()` to not trigger a re-render, because the object references are the same and so the data looks *unmodified*. 

This feels sort of similar in spirit to #738, given that it's about the context not getting updated, but this feels more like an issue with reusing the same object when you update it and not just using the same method between renders.

**Comment by bluebill1049** [comment]
<img width="1021" alt="Screen Shot 2019-12-29 at 8 20 30 pm" src="https://user-images.githubusercontent.com/10513364/71554837-b20f2300-2a78-11ea-98f1-eb25fc698d23.png">

Can you do a console.log on the errors object?

**Comment by bluebill1049** [comment]
it's returning correct errors types

**Comment by bluebill1049** [comment]
feel free to re-open if there still an issue :)
