### ISSUE TITLE
issue: adding values to field array via setValue doesnt rerender field array

### ISSUE THREAD

**Issue by mmahalwy** [react-hook-form/react-hook-form#7399]
### Version Number

7.22.5

### Codesandbox/Expo snack

https://codesandbox.io/s/trusting-nobel-nwdmm?file=/src/App.tsx

### Steps to reproduce

1. Click on the add more button at the bottom
2. Click the submit button
3. See console log, you'll notice that there are 2 users in the submission data, but the app did not rerender to show 2 user fields

### Expected behaviour

Since the data will be passed in the submit function, the expectation is also the app would rerender to include the newly set field array fields. I understand the docs say we have to use `setValue` with the whole field array, but the expectation in that case is the values would not show up in the submit function. 

Expected behavior should either:
1. rerender field array to include newly created fields due to `setValue`
2. do not rerender but do not include these fields in the submit values

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`setValue` is made for setting an input value, not creating new field array input.  I would use append/prepend those dedicated field array methods instead.

**Comment by mmahalwy** [comment]
@bluebill1049 But this is a valid bug as it has an unexpected effect. Even if append is the right way to do this, this doesn't behave correctly then
