### ISSUE TITLE
<Controller>'s control prop should be optional (useFormContext)

### ISSUE THREAD

**Issue by kusmierz** [react-hook-form/react-hook-form#740]
**Is your feature request related to a problem? Please describe.**
`<Controller>` component has to have `control` prop defined, even when using `<FormContext>`. Maybe it would be possible to use `const { control } = useFormContext()` in case there is no `control` prop directly passed?

**Describe the solution you'd like**
I'd love to don't repeat myself and use clean and clear `<Controller>` component without passing additional `control` each and every time.

**Describe alternatives you've considered**
Previously, React Hook Form input [worked as described above](https://github.com/react-hook-form/react-hook-form-input/blob/master/src/index.tsx#L55-L58).

**Additional context**
https://github.com/react-hook-form/react-hook-form-input/blob/master/src/index.tsx#L55-L58

**Comment by kusmierz** [comment]
That was quick, thank you very much @bluebill1049!

**Comment by bluebill1049** [comment]
pleasure @kusmierz I am working on RHF, may as well as get this one in.

**Comment by bluebill1049** [comment]
should be on the next minor release.
