### ISSUE TITLE
document that name field on useController is able to target nested values

### ISSUE THREAD

**Issue by danielo515** [react-hook-form/react-hook-form#7403]
**Is your feature request related to a problem? Please describe.**
Hello. This is a documentation issue. I think the useController hook is a bit undocumented.
Since it can be used to create nested components (which is what I'm using it for) one expected feature is that you can target nested values. This is not documented anywhere, but I tested to provide a "path" on the name and it worked as expected

**Describe the solution you'd like**
I want this feature to be documented.
Also I understand that the name will not always match perfectly the actual path, so having a separate property to specify the field path will be useful too

**Describe alternatives you've considered**
At least documenting the current feature will be nice.

**Additional context**
As I said above, I'm using this hook to wrap controlled components targeting nested fields.

**Comment by bluebill1049** [comment]
register input name is documented here: https://react-hook-form.com/api/useform/register feel free to send us a PR at the `useController`, if that's not what you after.
