### ISSUE TITLE
issue: Names can't be substrings of each other, causes infinite render loop

### ISSUE THREAD

**Issue by lamotik** [react-hook-form/react-hook-form#7408]
### Version Number

7.22.5

### Codesandbox/Expo snack

https://codesandbox.io/s/sweet-rhodes-mk9ho?file=/src/App.js

### Steps to reproduce

Please see example in codesandbox.
I haven't found in documentation that I did something wrong, but it looks like you can't have names in same object where one is a substring in another, e.g. field1 has name 'name', field2 has name 'nameAndSomethingElse'.

```
import "./styles.css";
import { useForm, useWatch } from "react-hook-form";

export default function App() {
  const { control, register, setValue } = useForm({});
  const name = useWatch({
    control,
    name: "name"
  });
  setValue("nameInOtherLang", name);
  return (
    <div className="container-main">
      <form>
        <p>It looks like all names can't be substring of each other </p>
        <input {...register("name")} placeholder='Change Me First' />
        {/* Change  nameInOtherLang to something else */}
        <input {...register("nameInOtherLang")} placeholder='I must have same value'/>
      </form>
    </div>
  );
}
```

### Expected behaviour

I should be able to have field1 with name 'name' and field2 has name 'nameAndSomethingElse'

### Relevant log output

```shell
Chrome Version 96.0.4664.110 (Official Build) (64-bit)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mufteev** [comment]
I think it may be related to  https://github.com/react-hook-form/react-hook-form/issues/6977#issuecomment-1003585307

**Comment by felixschorer** [comment]
Probable causes: https://github.com/react-hook-form/react-hook-form/search?q=startsWith

**Comment by bluebill1049** [comment]
This issue is due to 

`setValue("nameInOtherLang", name);`  before the render. I am looking more into a solution, but you may want to setValue inside `useEffect` instead of before the render on each function invoke.

**Comment by bluebill1049** [comment]
The investigation is complete, this is expected behavior, by default `useWatch` will match none exact field name which is why we are using `startsWith`. You can resolve the problem with what I supplied above, or simply turn on the `exact` prop, so the blur (`startsWidth`) search will be omitted.

https://codesandbox.io/s/blazing-paper-fipsp?file=/src/App.js

```tsx
const name = useWatch({
  control,
  name: "name",
  // opitons A
  exact: true,
});
```

option B is on the above comment

**Comment by lamotik** [comment]
Great! Thank you!
