### ISSUE TITLE
Controller with React-Select and onBlur mode, onBlur event clears the value of the input

### ISSUE THREAD

**Issue by VGLoic** [react-hook-form/react-hook-form#742]
**Describe the bug**
When using the `onBlur` mode for the `useForm` and a `react-select` input wrapped into a `Controller`, the trigger of the `onBlur` event clears the value of the input.

**To Reproduce**
1. In the codesandbox below, chose a value for the `react-select` input
2. Click somewhere else in order to trigger the `onBlur` event
3. Previously selected value should have been gone

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-rhfinput-yjndq

**Expected behavior**
Value should not be modified, only validation should be applied.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 78.0.3904.97

**Comment by bluebill1049** [comment]
is that because you missing this?
```
onBlur={([selected]) => {
                return { value: selected };
              }}
````

**Comment by VGLoic** [comment]
Not sure, I modified the codesandbox to add the `onBlur` like so but it looks like the `onChange` and `onBlur` are quite different in the React-Select :(.

https://codesandbox.io/s/react-hook-form-rhfinput-yjndq

I did a workaround like so:
```
onBlurName="onChange"
onBlur={([selected]) => ({ value: selected  })}
```
but I'm not sure this is what we want ahah.

PS: Sorry I didn't see I was modifying stuff on this codesandbox before so I hope you had a good version.

**Comment by bluebill1049** [comment]
looks like that's how onBlur is like in react-select: https://github.com/JedWatson/react-select/issues/186

**Comment by JeromeDeLeon** [comment]
Upon looking, it seems like `onBlur` triggers because we set the `mode` to "onBlur" and therefore, replaces the value of empty string.

**Comment by JeromeDeLeon** [comment]
What you can do is

```js
const [selectValue, setSelectValue] = useState(null);

return (
  <Controller
    as={<ReactSelect />}
    options={options}
    name="ReactSelect"
    isClearable
    control={control}
    onChange={([selected]) => {
       console.log("From onChange: ", selected);
       setSelectValue(selected)
       return { value: selected };
    }}
    onBlur={([selected]) => {
      console.log("From onBlur: ", selectValue);
      return { value: selectValue };
    }}
  />
)
```

**Comment by JeromeDeLeon** [comment]
You might wanna wrap this one like this what this guy did https://github.com/JedWatson/react-select/issues/186#issuecomment-106695850

**Comment by JeromeDeLeon** [comment]
> Not sure, I modified the codesandbox to add the `onBlur` like so but it looks like the `onChange` and `onBlur` are quite different in the React-Select :(.
> 
> https://codesandbox.io/s/react-hook-form-rhfinput-yjndq
> 
> I did a workaround like so:
> 
> ```
> onBlurName="onChange"
> onBlur={([selected]) => ({ value: selected  })}
> ```
> 
> but I'm not sure this is what we want ahah.
> 
> PS: Sorry I didn't see I was modifying stuff on this codesandbox before so I hope you had a good version.

That's really clever IMO :laughing:

**Comment by bluebill1049** [comment]
going to close this issue, looks like what you got is the solution for now. Let me know if anything else i can help.

**Comment by ricardoenriquez** [comment]
> 
> 
> going to close this issue, looks like what you got is the solution for now. Let me know if anything else i can help.



> 
> 
> What you can do is
> 
> ```js
> const [selectValue, setSelectValue] = useState(null);
> 
> return (
>   <Controller
>     as={<ReactSelect />}
>     options={options}
>     name="ReactSelect"
>     isClearable
>     control={control}
>     onChange={([selected]) => {
>        console.log("From onChange: ", selected);
>        setSelectValue(selected)
>        return { value: selected };
>     }}
>     onBlur={() => {
>       console.log("From onBlur: ", selectValue);
>       return { value: selectValue };
>     }}
>   />
> )
> ```

after version 60.0.0.rc2 the onchange no longer works

**Comment by bluebill1049** [comment]
> > going to close this issue, looks like what you got is the solution for now. Let me know if anything else i can help.
> 
> > What you can do is
> > ```js
> > const [selectValue, setSelectValue] = useState(null);
> > 
> > return (
> >   <Controller
> >     as={<ReactSelect />}
> >     options={options}
> >     name="ReactSelect"
> >     isClearable
> >     control={control}
> >     onChange={([selected]) => {
> >        console.log("From onChange: ", selected);
> >        setSelectValue(selected)
> >        return { value: selected };
> >     }}
> >     onBlur={() => {
> >       console.log("From onBlur: ", selectValue);
> >       return { value: selectValue };
> >     }}
> >   />
> > )
> > ```
> 
> after version 6.0.0.rc2 the onchange no longer works

Take a look at the v6 doc: https://react-hook-form.com/api#Controller
