### ISSUE TITLE
Form reuses last state when re-rendering

### ISSUE THREAD

**Issue by ISilviu** [react-hook-form/react-hook-form#7420]
### Details

I have a page with a dynamic number of forms, as they can be added or removed. The forms' submitted states are held in a list and used as default values when rendering them. The problem appears when I try to remove a form; they somehow keep their previous state when re-rendering.

### Version Number

7.20.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-with-ui-library-forked-0dz1o?file=/src/index.js

### Steps to reproduce

1. Click "Add new form" twice (we need at least 2 forms to reproduce the issue)
2. Complete the forms as follows:

- Form 1 -> A, Strawberry
- Form 2 -> B, Chocolate

3. Click "Remove form" for the first form.

### Expected behaviour

A single form with the values "B, Chocolate" should be rendered, yet we get the "A, Strawberry" instead.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is expected behavior, each useForm holds its own formValues unless the hook gets unmounted. 

options:

- useForm({ shouldUnregister: true })
- each form has its own `useForm` 
- use `reset` API to reset  the entire form when you switch to a new form.

**Comment by ISilviu** [comment]
@bluebill1049 thank you for the quick answer.

I've figured it out in the end. :+1: 

In case anyone else has the same issue: it's not related to react-hook-form, it's related to the fact that I'm mutating the array containing the forms.

As I'm using index as the key, deleting an item will break the indexes and React won't render what we'd be expecting.
