### ISSUE TITLE
Manually calling 'onChange' with 'mode: onChange' does not trigger validation

### ISSUE THREAD

**Issue by gerrod** [react-hook-form/react-hook-form#7434]
### Version Number

7.22.5

### Codesandbox/Expo snack

https://codesandbox.io/s/silent-breeze-jfrfy

### Steps to reproduce

The form presented has the "Submit" button disabled until the form is both dirty and valid.

```
const canSubmit = formState.isDirty && formState.isValid;
```

The form has been setup with `mode: onChange`.

1. On the form, check any of the boxes next to one of the days of the week - notice that the submit button is still disabled
2. Uncheck the box, then check it again - the submit button is now enabled

### Expected behaviour

Since the form has been setup with `mode: onChange`, I would expect that when the `onChange` handler is called, the form would trigger validation / be marked as touched / etc. After the first box has been checked, the form should be both dirty and valid, and so the "submit" button should be enabled.

Calling `onBlur()` after `onChange(...)` (line 24 in `Days.tsx` file) yields the expected output.

### What browsers are you seeing the problem on?

Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
this is due to `formState` proxy is not been "activated"

`const canSubmit = formState.isDirty && formState.isValid; // formState.isValid is not evaluated as long as the first condition is false`

https://codesandbox.io/s/unruffled-benz-j45pm?file=/src/App.tsx

```
import * as React from "react";
import { FormProvider, useForm } from "react-hook-form";
import { Days } from "./Days";
import "./styles.less";
import { DaysOfWeek, FormValues } from "./types";

export default function App() {
  const methods = useForm<FormValues>({
    mode: "onChange",
    defaultValues: {
      days: DaysOfWeek.map(() => null)
    }
  });

  const {
    formState: { isDirty, isValid },
    handleSubmit
  } = methods;
  const canSubmit = isDirty && isValid;
  const onSubmit = (data: FormValues) => console.log(data);

  return (
    <FormProvider {...methods}>
      <form onSubmit={handleSubmit(onSubmit)}>
        <Days />

        <input type="submit" disabled={!canSubmit} value="Submit" />
      </form>
    </FormProvider>
  );
}
```

**Comment by gerrod** [comment]
Thanks for the explanation @bluebill1049 .
