### ISSUE TITLE
issue: get.ts triggers path.split not a function error

### ISSUE THREAD

**Issue by EdmundsEcho** [react-hook-form/react-hook-form#7446]
### Version Number

7.22.5

### Codesandbox/Expo snack

na

### Steps to reproduce

Using MUI component, I set the `inputRef` prop to the `register` value as follows:

```jsx
      <Input
        key={`${stateId}`}
        id={`${stateId}`}
        name={name}
        inputRef={register}
        value={buffer}
        onChange={handleOnChange}
        onBlur={handleOnBlur}
        onKeyUp={handleOnKeyUp}
        label={label}
        {...rest}
      />
```
It worked for literally years.  However, when I updated the `react-form-hook` from `6.0.8` I started to get the following error:

```
Uncaught TypeError: path.split is not a function
    get get.ts:8
    register createFormControl.ts:879
```

I'm not sure what guards are in place to make sure the path is in fact a string, but I suspect for whatever reason, this is now a likely requirement.

\- E

### Expected behaviour

No error

### Relevant log output

```shell
see above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848
