### ISSUE TITLE
issue: Typescript: Form errors are incorrectly typed when using NewTypes

### ISSUE THREAD

**Issue by meoyawn** [react-hook-form/react-hook-form#7454]
### Version Number

7.22.5

### Codesandbox/Expo snack

https://codesandbox.io/s/epic-tesla-df1f6?file=/src/App.tsx

### Steps to reproduce

Open CodeSandBox, see lines `40` & `47`

There shouldn't be type errors, since it runs just fine

### Expected behaviour

There are no type errors, since it runs fine

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felixschorer** [comment]
I don't think that is possible. Adding `& NestedValue` to the `EmailAddress` and `Password` types gets rid of the errors, but raises a new error on the resolver property.

@bluebill1049 maybe we should use V8 to examine all usages of `NestedValue` and rewrite all types that depend on it. Introspecting types as in `DeepMap` causes more troubles than it solves.

**Comment by bluebill1049** [comment]
This is definitely the thing I was talking about before, input primitive vs with nested value. I don't think I can be solved by `NestedValue` as well. I recommend keeping either primitive or nested value for the input otherwise it's a limitation that I don't think we have a solution for.

**Comment by meoyawn** [comment]
sad, thanks. I guess this is when people roll their own form libraries 🙂
