### ISSUE TITLE
submitFocusError doesn't work for nested fields

### ISSUE THREAD

**Issue by prog13** [react-hook-form/react-hook-form#746]
**Describe the bug**
`submitFocusError: true` does not work for nested field names.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-nested-fields-3uknx
2. Press `Submit`.
3. `Title` input is focused as expected, validation error is logged to console
4. Input anything in the `Title` input
5. Press `Submit`
6. Observe how `First Name` input doesn't receive focus

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-nested-fields-3uknx

**Expected behavior**
When submitting the form with `Title` input filled, `First Name` input should receive focus.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser chrome
 - Version 79.0.3945.88

The issue is affecting any variant of nested input (e.g. `name=checkboxes[0]`, `name=branches[1].leaf` etc)

**Comment by bluebill1049** [comment]
fixed: https://codesandbox.io/s/react-hook-form-nested-fields-fix-4spig
