### ISSUE TITLE
issue: update is not a function with useFieldArray

### ISSUE THREAD

**Issue by maxy4u** [react-hook-form/react-hook-form#7460]
### Version Number

7.8.4

### Codesandbox/Expo snack

https://codesandbox.io/s/usefieldarray-virtual-input-forked-61i7e

### Steps to reproduce

1. Go to https://codesandbox.io/s/usefieldarray-virtual-input-forked-61i7e
2. Click on checkbox and then append it will introduce a new input field with some value.
3. Click on x button next to this conditional input.
4. It will trigger a call to onClear with is call update method returned by useFieldArray.

<img width="803" alt="Screen Shot 2022-01-06 at 2 41 10 PM" src="https://user-images.githubusercontent.com/6682288/148435511-5df52ef7-3b47-40fa-a651-c6c9b4ec5e51.png">
<img width="1440" alt="Screen Shot 2022-01-06 at 2 54 35 PM" src="https://user-images.githubusercontent.com/6682288/148435814-7047449a-af3b-4507-b774-ef4a6da403b3.png">

### Expected behaviour

As per documentation update method is returned by useFieldArray to update a particular index of input.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Please upgrade to the latest version.
