### ISSUE TITLE
Provided Fields Array example do not work properly

### ISSUE THREAD

**Issue by alexfgo** [react-hook-form/react-hook-form#747]
**Describe the bug**
Example provided in https://codesandbox.io/s/6j1760jkjk crashes when we try to add/remove items in specific order that duplicates keys in index array..

**To Reproduce**

1. In the codesandbox below, add 3 friends using the button `Add Friend`
2. Click `Remove` button to delete the 2nd item.
3. Click `Add Friend` again

The following error should appear in the console:
_Warning: Encountered two children with the same key, `friends[2]`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in form (at src/index.js:31)
    in App (at src/index.js:73)_

Codesandbox link
https://codesandbox.io/s/6j1760jkjk

**Desktop (please complete the following information):**

OS: Windows 10
Browser chrome
Version 79.0.3945.88

**RHF is being a terrific tool for my projects and I really enjoy the lib, although I'm facing some problems trying to use it with dynamic arrays, specially with validations which seems to get out of sync with the rendered fields after adding and removing itens. It would be worderful if someone could fix the example or even provide a complex example including validations in Field Arrays.**

**Comment by bluebill1049** [comment]
hey @alexfgo have you seem this example: https://codesandbox.io/s/react-hook-form-field-array-advanced-with-delete-insert-append-edit-l19pz?

**Comment by bluebill1049** [comment]
by the way, I do have plan to make a generic component for the field array and it's on my todo list. will come to it when I get some more free times :)

**Comment by alexfgo** [comment]
Thank you for the fast anwser.
I'll look at this example carefully.
I look forward to see the generic component for array fields when it come out.

**Comment by bluebill1049** [comment]
closing this issue for now, feel free to ask more questions :)
