### ISSUE TITLE
issue: Validate method with other validate functions

### ISSUE THREAD

**Issue by vrg-success** [react-hook-form/react-hook-form#7471]
### Version Number

7.22.5

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-get-started-forked-c776y?file=/src/index.js:787-795

### Steps to reproduce

1. Click on "Submit" button
2. Type value "some text" to "exampleRequired" field
3. Click on "Submit" button
4. Type int value "1221"

### Expected behaviour

After 4. step I validation message should be hide and form should allows submit

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please refer to the doc on what's returned by `validate` function. 

`validate: (val) =>
            /^\d+$/.test(val) ? "" : "Field should contains only int"`
