### ISSUE TITLE
Create a Proxy for `fieldState` in `useController`

### ISSUE THREAD

**Issue by Jasonkoolman** [react-hook-form/react-hook-form#7472]
**Is your feature request related to a problem? Please describe.**
Using `useController` is causing extra (unnecessary) renders in my case as I don't always need access to `fieldState`.

**Describe the solution you'd like**
Make a proxy of `fieldState` here: (https://github.com/react-hook-form/react-hook-form/blob/master/src/useController.ts#L112). The same is already done for `formState`.

**Describe alternatives you've considered**
Tried to create a Proxy in a custom hook:

```ts
const {
    field: { ref, ...input },
    // fieldState
    formState,
  } = useController<TFormValues>({
    name,
    rules,
    control,
    defaultValue,
    shouldUnregister,
  });
  
const inputState = Object.defineProperties({},
    {
      invalid: {
        get() {
          return invalid !== undefined ? invalid : !!get(formState.errors, name);
        },
      },
      isDirty: {
        get() {
          return !!get(formState.dirtyFields, name);
        },
      },
      isTouched: {
        get() {
          return !!get(formState.touchedFields, name);
        },
      },
      error: {
        get() {
          return get(formState.errors, name);
        },
      },
    }
  );
  
  // ...
```

However, this does not work as `useController` is still causing re-renders when `fieldState.error` or `fieldState.isTouched` changes, for example.

**Comment by bluebill1049** [comment]
Thanks for the feature request, putting it on the project board.

**Comment by mmahalwy** [comment]
+1

**Comment by yaeSakuras** [comment]
+1 I need this feature
