### ISSUE TITLE
Bug - reset() followed by setValue() does not update field argument in <Controller/> render function for nested fields

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#7476]
### Version Number

7.22.5

### Codesandbox/Expo snack

https://codesandbox.io/s/beautiful-cartwright-43whr?file=/src/App.js

### Steps to reproduce

1. Go to the sandbox
2. Click on the reset button
3. Notice that the values have been reset
4. Click on the set value button
5. Notice that the form values are correct (as indicated by the `watch` method), however, the `field` argument produced by the render function is not updated and still holds the previous value. 

### Expected behaviour

I would expect the field value to match the value in form values as indicated by `watch` and `getValues`.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
use `setValue("nested", { first: "newValue" });` setValue is focus on field name level, update group of inputs are just sugar syntax, in this case it's impossible to do check, because it will return none for such field.

**Comment by bluebill1049** [comment]
I will update this in detail in the doc now.

**Comment by bluebill1049** [comment]
![Screen Shot 2022-01-08 at 10 55 19 am](https://user-images.githubusercontent.com/10513364/148621606-aa26694d-a72f-4efc-8645-1c55ab10a2fd.png)
live

**Comment by wdfinch** [comment]
Wow that was fast. Ok thanks so much.

**Comment by bluebill1049** [comment]
you are welcome, thanks for always preparing a detailed issue. it really makes my life a bit easier.
