### ISSUE TITLE
issue: It seems to me that section "Custom Hook with Resolver" example is not working

### ISSUE THREAD

**Issue by nospoon27** [react-hook-form/react-hook-form#7490]
### Version Number

7.22.5

### Codesandbox/Expo snack

https://codesandbox.io/s/custom-hook-with-resolver-v7-forked-ov2wp

### Steps to reproduce

1. Go to [example](https://codesandbox.io/s/custom-hook-with-resolver-v7-forked-ov2wp)
2. Click on "submit"
3. Open console logs
4. You should see errors in the logs, but we see undefined value

### Expected behaviour

We should see the object with errors in the console

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please read the doc on fromState: errors
