### ISSUE TITLE
issue: Reset causes infinity loop with default props

### ISSUE THREAD

**Issue by TonyVeigel** [react-hook-form/react-hook-form#7495]
### Version Number

7.22.5

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-basic-forked-4krvg?file=/src/index.js

### Steps to reproduce

Once you get to the page you are in an infinity loop. 

### Expected behaviour

There should be no infinity loop. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please refer to react doc on useEffect, this is not related to hook form

**Comment by TonyVeigel** [comment]
> please refer to react doc on useEffect, this is not related to hook form

@bluebill1049 

This has nothing to do with useEffect. You should refer to the react docs yourself, this is the second time as code owners you don't know how the basics of how React works; I also created a bug for the last time. DefaultParam is a dependency, useEffect should only run if defaultParam is updated. Why is reset() updating defaultParam? 

If you need another example replace reset() with a state update and you will see how it is supposed to work.
