### ISSUE TITLE
support register with uncontrolled  dynamic checkboxes

### ISSUE THREAD

**Issue by spacenate** [react-hook-form/react-hook-form#7500]
### Version Number

7.22.5

### Codesandbox/Expo snack

https://codesandbox.io/s/quiet-morning-678cv?file=/src/App.tsx

### Steps to reproduce

1. Go to [the CSB](https://codesandbox.io/s/quiet-morning-678cv?file=/src/App.tsx) (or this [alternate example](https://codesandbox.io/s/hungry-night-kn5nt?file=/src/App.tsx)).
2. Compare the `defaultValues` to the rendered checkboxes, and see checkbox "A" checked by default even though the `defaultValues` does not specify it should be (nor does the input have `defaultChecked`).

### Expected behaviour

Given a checkbox input with a `defaultValues` that is an array, `register()` should only check the checkbox by default if the array includes the input's value.

The issue appears to come from this line: https://github.com/react-hook-form/react-hook-form/blob/cf2c633280bf3f752912263f0e10d07c937ea010/src/logic/createFormControl.ts#L539

I will open a PR shortly.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

(edited to clarify `defaultValues` vs `defaultValue`)

**Comment by bluebill1049** [comment]
Thanks for the issue report and especially the PR by looking into the issue itself. However, I think it's better to have either `defaultValues` or `defaultValue/defeaultChecked` as what we documented, that way it's clear on your input value's source of truth. The same reason why we did for in build validation or resolver. you should use either one of them, rather mix them up.

**Comment by spacenate** [comment]
Thanks for your quick reply. I agree it is reasonable to use `defaultValue` as the source of truth, and omit `defaultChecked` completely.

What are your thoughts on the alternate scenario, where a `defaultValue` of `[]` results in single checkbox being checked? (https://codesandbox.io/s/hungry-night-kn5nt?file=/src/App.tsx) 

My use-case is a dynamically-generated list of checkboxes, where 1 is a valid number of checkboxes. (Something like, "choose recent items", where there could be 1 or more items). I am providing `defaultValue` to my form (so that `isDirty` works), and this is causing issues when there is only 1 checkbox in my list.

**Comment by bluebill1049** [comment]
> My use-case is a dynamically-generated list of checkboxes, where 1 is a valid number of checkboxes. (Something like, "choose recent items", where there could be 1 or more items). I am providing defaultValues to my form (so that isDirty works), and this is causing issues when there is only 1 checkbox in my list.

In such a case, I think it makes sense to build a controlled component (which is the strength) to host those checked values and use `Controller/useController` to collect and validate the value.

**Comment by spacenate** [comment]
I think that sounds like a fine alternate solution (workaround). As a consumer of this library, I would still argue that `defaultValues: { checkbox: [] }` causing a single checkbox to be checked by default is **unexpected** (and thus is a bug).

Reasoning:

- react-hook-form explicitly distinguishes itself from competing libraries by using (and **encouraging** the use of) uncontrolled form components (per the [FAQs](https://react-hook-form.com/faqs#PerformanceofReactHookForm): "Performance is one of the primary reasons why this library was created. React Hook Form relies on uncontrolled form, [...]")
- In the [Get Started guide](https://react-hook-form.com/get-started#IntegratingControlledInputs), `Controller/useController` is described as a "escape hatch", not a primary solution ("React Hook Form embraces uncontrolled components and native HTML inputs, however, it's hard to avoid working with external controlled components [...]. To make this simple, we provide a wrapper component [...]")
- The [Code Examples](https://github.com/react-hook-form/react-hook-form/tree/master/examples) link to this [Checkbox minimum checked (Native)](https://codesandbox.io/s/checkbox-min-checked-forked-0tkjz) example, demonstrating that uncontrolled checkbox input groups are supported.
  - And in fact, uncontrolled checkbox input groups do work as expected, even with array-type `defaultValues: { checkbox: [] }` -- but _only_ when more than 1 checkbox input is registered (and also assuming the library consumer does not make the mistake of using both `defaultValues` and `defaultChecked`, which can result in the same edge case occurring, where `setFieldValue()` is only called once).

Is there a good reason to not "embrace uncontrolled components and native HTML inputs" in this scenario of dynamically generated checkbox options?

---

As an aside, I have found a different workaround that lets me use uncontrolled checkbox options in this way. I simply ensure that there is always more than 1 checkbox option registered:

```
{cbOptions.length === 1 && (
  <input type="checkbox" style={{display: 'none'}} value='--react-hook-form-workaround--' {...register('checkbox')} /> 
)}
```

**Comment by bluebill1049** [comment]
thanks, @spacenate for your detailed feedback above and appreciate your input and even include solutions and potential fixes (consider most of the users only here to report without giving that much attention to detail and provide fixes). At the moment, we don't support dynamic checkboxes/radios with uncontrolled input, because the original intention was made for static checkboxes and radios, if users need group-level inputs state management, I would vote for controlled input as it gives you the full scope of your inputs state. While we can make this works for uncontrolled, I am worried this will open other unexpected use cases for dynamic inputs. More features more issues to be covered, I wouldn't be surprised with more use cases such as shuffle, insert swap and etc. Especially we have `useFieldArray` which is dedicated to such task. So my personal preference is not to expand on the functionality of `register` uncontrolled checkboxes or radios inputs instead turn this into a feature request and see if many uses do have such usage cases before we merge your PR and publish it as the "new" functionality.

**Comment by bluebill1049** [comment]
come back to this feature request. I think i find a better solution.

**Comment by bluebill1049** [comment]
This is issue getting resovled.
