### ISSUE TITLE
optimization: onChange reference cause re-renders

### ISSUE THREAD

**Issue by mysuf** [react-hook-form/react-hook-form#7507]
### Version Number

7.22.5

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-controller-forked-wjzh8

### Steps to reproduce

1. write into React Input Mask
2. watch console => every React Input Mask change generates new onChange reference

### Expected behaviour

onChange reference changes even when FormContext is used (without changing value). I would be curious what dependecies are related to this function. It should only use setters that doesn't change their references.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
[why-did-you-update] render function args {onChange: {…}, value: {…}}
[why-did-you-update] render function args {onChange: {…}, value: {…}}
[why-did-you-update] render function args {onChange: {…}, value: {…}}
[why-did-you-update] render function args {onChange: {…}, value: {…}}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Currenlty, we do not memorize onChange, onBlur which pass down by the controller/useController, and the re-render is isolated at the component level.

**Comment by bluebill1049** [comment]
you can upvote this feature request: https://github.com/react-hook-form/react-hook-form/issues/6435
