### ISSUE TITLE
issue: Firefox: can not change text input after submit when error ocures

### ISSUE THREAD

**Issue by anticol** [react-hook-form/react-hook-form#7510]
### Version Number

6.15.4

### Steps to reproduce

When I submit form with one input which has reg ex pattern for validation and mode: 'onSubmit' I can not edit input value when error occurs. Only happens on Firefox (Chrome and Safari are working)

### Expected behaviour

Edit input value after validation error occurs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Can't reproduce

**Browser:** Firefox 97.0b2 _(64-bit)_
**Package version:** 6.15.4

[Check out this codesandbox](https://codesandbox.io/s/pattern-input-validation-x4jo1) to see if there's something you're doing differently

**Comment by bluebill1049** [comment]
thank you @Moshyfawn
