### ISSUE TITLE
issue: setValue with shouldDirty and shouldTouch combine not update state correctly

### ISSUE THREAD

**Issue by lecoqjacob** [react-hook-form/react-hook-form#7513]
### Version Number

7.23.0

### Codesandbox/Expo snack

https://codesandbox.io/s/should-dirty-fail-qnsfm

### Steps to reproduce

See code sandbox for referece

### Expected behaviour

using `setValue` with options `{ shouldDirty: true, shouldTouch: true }` should set the field to be touched and dirty.

Reference to earlier error #7506

This was bug fixed this morning, but the error is still occuring 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks fixed last night will release in the next patch: https://github.com/react-hook-form/react-hook-form/commit/124e00ff9f447905c03024f242fbda0071b6958f
