### ISSUE TITLE
issue: resetField and setValue change unregistered field behaviour

### ISSUE THREAD

**Issue by bouzlibop** [react-hook-form/react-hook-form#7514]
### Version Number

7.23.0

### Codesandbox/Expo snack

https://codesandbox.io/s/distracted-morning-2o26h?file=/src/App.js

### Steps to reproduce

1. Enter some value into the input field.
2. Submit the form. Notice the expected values: `{ type: <type> }`
3. Click "Reset" button.
4. Submit the form. This time notice that the submitted changed: `{ type: <type>, labels: [] }` 

### Expected behaviour

I would expect that `resetField` (and also `setValue`) would not affect which fields are included in the submission. And if shouldUnregister is true and the field is not registered I would expect that the field won't be included in the submission even if resetField was called for that field.

> defaultValues will be included in the submission result by default, if this is not the desired behavior use shouldUnregister: true instead which means input values will host within all the fields.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`resetField` will reset input value to `defaultValue`. This API no context of input is mount or not, and simply reset it back to its defaultValue.

**Comment by bouzlibop** [comment]
@bluebill1049 (1) how can I make sure that unregistered fields are **not** included in the submission? After reading following:

> defaultValues will be included in the submission result by default, if this is not the desired behavior use shouldUnregister: true instead which means input values will host within all the fields.

my understanding was that if I set `shouldUnregister` to `true` (at `useForm` level) then unregistered fields won't be included in the submission. I observed that to be true unless I call `resetField` (as shown in the linked codesandbox example). So (2) if `resetField` resets the input value to `defaultValue` and nothing more, why is that after calling it this `defaultValue` is now included in the submission? I'm struggling to get my head around these 2 questions.

**Comment by bluebill1049** [comment]
That's only applicable when an input gets unmounted and gets unregisterd.

**Comment by bouzlibop** [comment]
@bluebill1049 thanks for the answer. 

![image](https://user-images.githubusercontent.com/8625570/149285053-d96d67a3-9e75-45a1-9897-2f88a1a09462.png)

Why docs mention "failed by input not found"? I [modified the provided codesandbox a bit](https://codesandbox.io/s/relaxed-black-58e9b?file=/src/App.js). Even if there is no input, no `register`, no `defaultValue` and someone calls `form.resetField("non-existent-name")` now `non-existent-name` **will** be included in the submission. Why is that? I believe it should be mentioned in the docs.

**Comment by bluebill1049** [comment]
will include name check
