### ISSUE TITLE
issue: Radio Inputs Do Not Register Correctly In React Portals

### ISSUE THREAD

**Issue by dairyisscary** [react-hook-form/react-hook-form#7515]
### Version Number

7.23.0

### Codesandbox/Expo snack

https://codesandbox.io/s/sharp-joliot-5cb75?file=/src/App.js

### Steps to reproduce

1. Use sandbox, observe the same form rendered twice, once normally and once in a portal.
2. The normal form works fine but the portaled form only allows the _last_ option to be registered. use the submit button to see this in action

### Expected behaviour

Shouldn't this work the same in both cases? Perhaps this is because of some unusualness with my `Portal` implementation, but note this is very similar to the portal example from the official React docs.

After some debugging, I think this is a related issue to https://github.com/react-hook-form/react-hook-form/issues/6776, though not exactly the same. I think this comes down to this `live` check for radio and checkbox inputs. In the version I originally discovered this in (`7.22`), there's a `document.contains(el)` check, which won't be true when the refs are registered, since the `useEffect` hasn't attached the portal to the DOM yet. I know in newer versions, the form submission now causes a crash. Unfortunately, even if this crash is fixed, I believe latest version will use `el.isConnected` which is still falsy before the `useEffect` runs.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
TypeError
e.refs[0] is undefined
z
https://5cb75.csb.app/node_modules/react-hook-form/dist/index.cjs.js:1:4551
handleSubmit/<
https://5cb75.csb.app/node_modules/react-hook-form/dist/index.cjs.js:1:18951
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
yea, thanks for the invetigation. I think we will take a hit as a limitation with portal usage. work around using `Controller/useController` to solve this problem.

**Comment by dairyisscary** [comment]
Thanks for looking into this @bluebill1049 :)

For anyone who comes here from google somehow, I solved this without a controller by just waiting to render in the modal until after the dom attachment. This generically solves it for my application since it's incredibly common to have forms inside modals that use portals, for instance:

```js
import { useState, useLayoutEffect } from "react";
import { createPortal } from "react-dom";
import { useForm } from "react-hook-form";

export function Portal({ children }) {
  const [isAttached, setIsAttached] = useState(false);
  const container = useMemo(() => document.createElement("div"), []);

  useLayoutEffect(() => {
    document.body.appendChild(container);
    setIsAttached(true);
    return () => {
      document.body.removeChild(container);
    };
  }, [container]);

  // Only render once we know that children are in `document.body`
  return isAttached ? createPortal(children, container) : null;
}

function SampleForm() {
  const { register } = useForm();
  return (
    <Portal>
      <form onSubmit={handleSubmit(console.log)}>
         <input type="radio" value="one" {...register("field")} />
         <input type="radio" value="two" {...register("field")} />
      </form>
    </Portal>
  );
}
```

**Comment by bluebill1049** [comment]
Thanks for understanding and sharing solutions.

**Comment by bluebill1049** [comment]
another easier solution, just flush with a `reset` so all inputs get re-register again

```tsx
React.useEffect(() => {
  reset()
  // reset({...getValues()}) if you want to retain value
}, [reset])
```

https://codesandbox.io/s/sharp-edison-xu0q1?file=/src/App.js
