### ISSUE TITLE
setValue - setting shouldTouch and shouldDirty both to true is getting only one of them changed.

### ISSUE THREAD

**Issue by husseinAbdulnabi** [react-hook-form/react-hook-form#7522]
### Version Number

7.23.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-setvalue-forked-vsnhu?file=/src/index.jsx

### Steps to reproduce

1. Go to '[sandbox](https://codesandbox.io/s/react-hook-form-v7-setvalue-forked-vsnhu?file=/src/index.jsx)'
2. Click on 'set last name'
3. Scroll down to 'console => last console log'
4. Check the log

### Expected behaviour

expecting the field to be both dirty and touched when setting `shouldDirty: true` and `shouldTouch: true`, the actual result is that only the touched value is being changed, removing `shouldTouch` will result in the field being dirty, so only one of these flags is working at a time, which is not the expected behavior.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Duplicate #7513. Fixed & ready to be released with this patch 124e00ff9f447905c03024f242fbda0071b6958f. See [this comment](https://github.com/react-hook-form/react-hook-form/issues/7513#issuecomment-1011482337)
