### ISSUE TITLE
issue: clearErrors method doesn't influence isValid form state if custom error took place

### ISSUE THREAD

**Issue by Moshyfawn** [react-hook-form/react-hook-form#7524]
### Version Number
7.23.0
### Codesandbox/Expo snack
https://codesandbox.io/s/custom-error-form-state-py33x
### Steps to reproduce
1. Open [codesandbox](https://codesandbox.io/s/custom-error-form-state-py33x)
2. Enter 3 or more characters into the First Name field
3. See that "Form Valid" field is empty
### Expected behavior
The form becomes valid even if there were custom errors _(set via `setError` form method)_ that have been cleared by `clearErrors` form method. 
### What browsers are you seeing the problem on? 
Chrome, Firefox
### Relevant log output
There's something about this behavior that feels incorrect. @bluebill1049 is it expected?
If the form `mode` is `'onSubmit'` and I kick in my own **custom validation** via `setError` **without** ever **submitting** the form, is `clearErrors` expected to **not** reset the `isValid` from state?

_Originally posted by @Moshyfawn in https://github.com/react-hook-form/react-hook-form/discussions/7517#discussioncomment-1963946_
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
1, `clearErrors` should not reset isValid, because it has nothing to do with validation rules, it only clear errors
2. setError with custom required manual clear because it's not associated with any inputs

**Comment by enesozturk** [comment]
Hi @bluebill1049, I wonder if there could be the following case: I'll set a custom error message with `setError`, to show an error alert message to the user, but the user should be able to re-submit without clearing the error. RHF disable re-submit without clearing the error with `clearError`, can I make it not required? Thanks!

**Comment by bluebill1049** [comment]
if you are set an error on a registered input then its validation rules should be the source of truth to revalidate that input, however, if you setting an error outside of that, you will need to manually clear that error before we can continue to validate the rest of the registered inputs. hope this makes a bit of sense, basically the source of truth lives inside all the validation rules or schema.

**Comment by enesozturk** [comment]
I see, I would better create this kind of errors outside of the form fields then. This will be a better approach. Thanks for the explanation!
