### ISSUE TITLE
submit only values from registered fields even when setValue is called on an unregistered field

### ISSUE THREAD

**Issue by prince272** [react-hook-form/react-hook-form#7547]
Please 🙏🥺 help! Thank you!

**Is your feature request related to a problem? Please describe.**
Hi, Is there an option to submit only values from registered fields?

I have a form which I initialize with data from my rest api. All the data from my API goes to the values as my form values event if I didn't register all the field, then after submission I receive all the data in the handleSubmit method. is it possible to filter only values from field which was registered (i.e. in the form )?

In version 7.0.0 rc 2: setValue now embed with register. That is what is causing the problem.

**Describe the solution you'd like**
Calling setValue should not register the input alone.

**Describe alternatives you've considered**

**Additional context**

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/still-lake-lwcow?file=/src/App.js:0-798

what about the above example?

```tsx
import * as React from "react";
import { useForm } from "react-hook-form";
import Headers from "./Header";
import "./styles.css";

let renderCount = 0;

export default function App() {
  const { register, handleSubmit, reset } = useForm({
    shouldUnregister: true
  });
  const onSubmit = (data) => console.log(data);
  renderCount++;

  React.useEffect(() => {
    reset({
      firstName: "data",
      data: "test"
    });
  }, [reset]);

  return (
    <div>
      <Headers
        renderCount={renderCount}
        description="Performant, flexible and extensible forms with easy-to-use validation."
      />

      <form onSubmit={handleSubmit(onSubmit)}>
        <input {...register("firstName")} placeholder="First Name" />
        <input type="submit" />
      </form>
    </div>
  );
}
```

**Comment by prince272** [comment]
In version 7.0.0-rc.2 : setValue now embed with register. That is what is causing the problem.

**Comment by prince272** [comment]
I have a form which I initialize with data from my rest api. All the data from my API goes to the setValue.
 
var data = { registered1: "Test", notRegistered: "Test"   } // from the api.
Object.entries(data).forEach(([name, value]) => { form.setValue(name, value); });

Since the setValue now embed with register, upon submission I receive all the data in the handleSubmit method.

**Comment by bluebill1049** [comment]
Thanks, but I wouldn't dig an RC version, we are currently running `7.23.0`. unfortunately, this feature request by changing the `setValue` behavior is considering breaking change, especially its support object parent node value update `set('parentNode', { test: 'data' })` i wouldn't want to over complicated this API. so I would recommend you sort out your setValue at your app-level or consider to use `reset` like what I suggested above.

**Comment by prince272** [comment]
Thanks so much. reset works perfectly. 🙏🙏🙏

**Comment by prince272** [comment]
I was using the method below which was causing all the data from the api to be added in the handleSubmit method.
Object.entries(result.data).forEach(([name, value]) => { form.setValue(name, value); }); 

But now the method below works.
form.reset(result.data);

**Comment by bluebill1049** [comment]
Awesome 👍
