### ISSUE TITLE
Integrate with global state

### ISSUE THREAD

**Issue by fjuriolli** [react-hook-form/react-hook-form#755]
I read the part of the documentation about integration with global state and I didn't understand.
I'm not using connect from react-redux, I'm using the new hooks style like useDispatch.

Take a look at part of my code (It's not compiling, just to see the actual code)
https://codesandbox.io/s/react-5rfno

The goal here is to connect with my redux and get a defaultValue to each of my inputs.

Based on the code above, how can I connect the form to my redux?

**Comment by kelsonpw** [comment]
I'm not an expert with the library but i was able to get your solution working

https://codesandbox.io/s/react-n9kfm

It looks like you were trying to make your inputs controlled, using `useState` and `value={state}`. 
 This is not necessary to do with this library, as it handles the `value` for you using the ref. (uncontrolled input).  You can dispatch inside either `onSubmit` or inside an individual `onChange`.

**Comment by fjuriolli** [comment]
Hey @kelsonpw thanks for the reply, what if I need each of my inputs to have a defaultValue connected to my redux. 

For example, I have a form to edit a product from my state
