### ISSUE TITLE
issue: Empty space doesn't occur error when `valueAsNumber` flag is set.

### ISSUE THREAD

**Issue by hyungjunk** [react-hook-form/react-hook-form#7555]
### Version Number

7

### Codesandbox/Expo snack

https://codesandbox.io/s/amazing-bohr-1smus

### Steps to reproduce

1. Focus on the input field on codesandbox
2. Press spacebar.
3. Check log that it is saying error is false

### Expected behaviour

__To emit an error__

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Comment

It seems that empty space is converted to `0` when `valueAsNumber` flag is on. But it is not a number so is expected to emit an error.

If this is expected behavior, is there any way to set a value as another type other than string?

At version 6, `valueAs` is triggered after validation so I guess it would have been validate and set as number(or others)

but from version 7, since it casts to other type -> and validate, I wonder if there is a way to set a value as a type I want.

**Comment by JamesWong1999** [comment]
https://react-hook-form.com/api/useform/register

> valueAs process is happening before validation.

maybe you want to use `setValueAs` instead?

**Comment by bluebill1049** [comment]
thanks @JamesWong1999 that's right.
