### ISSUE TITLE
Validate currently mounted fields

### ISSUE THREAD

**Issue by stutrek** [react-hook-form/react-hook-form#7561]
**Is your feature request related to a problem? Please describe.**

I'm making multi-page forms, and I need to ensure that the user has filled out each page with valid information before moving on to the next. Currently there is no way of determining that every input currently in the DOM has a valid value.

Using trigger without any arguments will check fields that haven't been shown to the user, returning false for all but the last page.

**Describe the solution you'd like**

These are my two ideas, but any way that allows me to accomplish the task is fine.

- an API to get the currently mounted fields, which I can then pass into trigger
- an option for trigger that only checks what's currently in the DOM

**Describe alternatives you've considered**

- manually keeping track of what's on each page (will be very hard to maintain)
- creating a custom validation function for each page (same maintenance issues)
- using a separate useForm for each page. Moves a lot of responsibility from shared components to individual pages, creating a lot of duplicate code.
- Make each page's validation object optional and add a field to it when the page is mounted (assumes a 1:1 ratio of data to pages, hard to support a page being split on mobile, hacky, relies on the page to create that validation-triggering field)

**Additional context**

[I made this PR](https://github.com/react-hook-form/react-hook-form/pull/7535), but I am in no way attached to that implementation.

**Comment by wdfinch** [comment]
I made a PR to see which fields were valid already but it was closed for now. The way I handle this is to use schema validation + context. Sof for my schema I pass in some context indicating which page the user is on. From there I only apply validation to the inputs present on the current page.

**Comment by stutrek** [comment]
@wdfinch interesting solution, how do you know which fields are on the page? Do you rely on a config staying in sync with reality?

**Comment by bluebill1049** [comment]
This feature request is only relevant to schema level validation, right?

**Comment by stutrek** [comment]
We are using yup for schema validation, the type safety it provides is important to us because the objects we're building are quite large. You'd know better than me if it applies to configs on the inputs.
