### ISSUE TITLE
issue: useFieldArray ids get overwritten while append

### ISSUE THREAD

**Issue by gabaj** [react-hook-form/react-hook-form#7562]
### Version Number

7.23.0

### Codesandbox/Expo snack

https://codesandbox.io/s/gallant-architecture-obeeg?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/gallant-architecture-obeeg?file=/src/App.js
2. See how rendered objects have overwritten IDs with new UUIDs vs. their real IDs
3. Click on 'Add meal' button
4. New objects will be added with overridden ID value, even though it's set to "undefined"

### Expected behaviour

ID values shall not be overwritten during rendering nor appending new items.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Please, take a look at the Rules section of RHF docs on `useFieldArray`:
> When your array field contains objects with the key name id, useFieldArray will overwrite and remove it. If you want to keep the id field in your array of objects, you must use keyName prop to change to other name.

It looks like you're experiencing the expected behavior

**Comment by gabaj** [comment]
@Moshyfawn true, but in that case we have double identifier fields. What if I don't want to have auto-generated UUID along my custom object ID?

**Comment by ribeaud** [comment]
> Auto-generated field ID **won't be included in the submitted data**. But `useFieldArray` needs to somehow track all the new fields that get manipulated, i.e. using `append`, a new field should get a unique identifier); `append({ id: undefined })` won't provide a unique value. Additionally, see #7301. RHF **ver. 7.23.0** changes the behavior: by not providing `keyName` while having your own dataset id,` onSubmit` will still have your own id. Try submitting the form in [this codesandbox](https://codesandbox.io/s/friendly-saha-918ir?file=/src/App.js:463-489)

So, what should I do when facing this problem and want to keep using the DB `id` on client side? This is unclear to me... Concretely In the **codesandbox** example, what should be changed so that it works like in _7.22.5_? Thanks.

**Comment by gabaj** [comment]
@ribeaud you can set "keyName" prop to make library assign their UUID to some other key, example:

> const { append, fields } = useFieldArray({
>     control,
>     name: "meals",
>     keyName: "key"
>   });

**Comment by Moshyfawn** [comment]
> @ribeaud you can set "keyName" prop to make library assign their UUID to some other key, example:
> 
> ```js
> const { append, fields } = useFieldArray({
>     control,
>     name: "meals",
>     keyName: "key"
>   });
> ```
> 
> Now, you can keep using your id as earlier, but your objects will have additional auto-generated "key" prop:
> 
> ```js
> {
>     id: "1"
>     name: "palacinke"
>     key: "c826599d-ad6b-4ead-9b31-54586dc53aca"
> }
> ```

Thank you, @gabaj 🙏
