### ISSUE TITLE
Typescript: Wrong type assigned to fields when form values contains a nested array

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#7567]
### Version Number

7.24.0

### Codesandbox/Expo snack

https://codesandbox.io/s/nostalgic-northcutt-gvy48?file=/src/App.tsx

### Steps to reproduce

1. Hover over fields and notice the type is incorrect.

![Screenshot from 2022-01-17 13-17-08](https://user-images.githubusercontent.com/36898266/149838251-c0c12e52-88b5-40cb-abd1-216b8e1e77d5.png)

### Expected behaviour

The expected type is:

`FieldArrayWithId<FormValues, "dogs", "id">[]`

The type output is:

```FieldArrayWithId<FormValues, "dogs" | `dogs.${number}.toys`, "id">[]```

It is including the type for the nested array, however, the path I am provided is for the top-level array. Therefore, the nested array type should not be unioned with the top-level array type.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`useFieldArray<FormValues>` does not support generic.
