### ISSUE TITLE
issue: useForm or useFieldArray mutate original states

### ISSUE THREAD

**Issue by AntonioDeCasper** [react-hook-form/react-hook-form#7571]
### Version Number

7.24.0

### Codesandbox/Expo snack

https://codesandbox.io/s/cocky-herschel-cq7tc?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/cocky-herschel-cq7tc?file=/src/App.js
2. Change input value
3. Look at console logs
4. See that original data state was mutated

### Expected behaviour

 Original data state stay unmutable.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
expected behavior we don't support passing down the external state into `setValue` either `deepClone` the value been pass through, `setValue` will mutate and react hook form internal `formValues`.

**Comment by AntonioDeCasper** [comment]
Ok, then can you tell me how can i check is any field value in useFieldArray was changed? isDirty props works only when you add new field not edit a value in some field

**Comment by bluebill1049** [comment]
did you provide a `defaultValues`?

**Comment by AntonioDeCasper** [comment]
Well i can't provide default value on initial render because i need to fetch them first. I provide them later in useState hook with setValue or resetField actions

**Comment by bluebill1049** [comment]
then you should reset at `useEffect`, your usage is just not going to working with react hook form.

**Comment by bluebill1049** [comment]
for others reference `setValue("fieldArray", data);` update field array at the root will be deprecated with the next major version use `replace` instead.

reference RFC: https://github.com/react-hook-form/react-hook-form/discussions/7433

**Comment by AntonioDeCasper** [comment]
My usage is usual use case for web app no? You get the data and pass initial data to the form. Then you work with form and save your changes back to the server via API.

My quetion is - how can i check is any value in field array was changed for saving only that data, nor all the fields

**Comment by bluebill1049** [comment]
`dirtyFeilds`

**Comment by AntonioDeCasper** [comment]
@bluebill1049 Testing dirtyFields property now. As i see you use mutation a lot and i can't check is field become to its initial state after change. Its sad :(
