### ISSUE TITLE
Typescript: Generic component using useController

### ISSUE THREAD

**Issue by pmizio** [react-hook-form/react-hook-form#7577]
### Version Number

7.24.1

### Codesandbox/Expo snack

https://codesandbox.io/s/beautiful-payne-sjfoy?file=/src/FileUpload.tsx

### Steps to reproduce

Hi, I try to write generic component using `useController` but I don't belive it is possible to make field value returned from hook typesafe. I checked most of exported generics but any of them don't allow to set type for field value(`useController(props).field.value`). I belive it was feature in one of prereleases https://github.com/react-hook-form/react-hook-form/releases/tag/v7.18.0-next.0 but it is reverted now.
There is any solution/workaround or I simply overlooked it?

1. Go to sandbox
2. Checkout typescipt error
![image](https://user-images.githubusercontent.com/4346598/150004347-20245787-bcb1-4bfb-a35e-049e990409eb.png)

### Expected behaviour

`useController` hook return typesafe field value for generic components.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
working on that in V8: https://github.com/react-hook-form/react-hook-form/discussions/7354
