### ISSUE TITLE
Feature Request: Allow resetField to be used on object/field array inputs

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#7579]
**Is your feature request related to a problem? Please describe.**
I would like to use the `resetField` method on a field array input like so:

```resetField(`array.${index}.field`)```

Currently, it seems this behavior is unsupported: #7307

**Describe the solution you'd like**
I think the `resetField` method should work for all fields regardless of whether they are field array fields or nested. This mirrors the behavior of `setValue` which is a very useful method. 

**Describe alternatives you've considered**
Resetting the entire field with the current form values.

**Comment by bluebill1049** [comment]
I wouldn't want resetField to go for the same rout as setValue, if this related fieldArray, maybe we should have dedicated method for field array only.

**Comment by wdfinch** [comment]
I'm fine with that. I just would like to resetField array inputs.

**Comment by bluebill1049** [comment]
i assume you are using `reset` API right now with `getValues`?

**Comment by bluebill1049** [comment]
also would `replace` to be a good option?

**Comment by wdfinch** [comment]
Correct. So right now I'm doing this:

```
 reset(getValues())
 setValue(`fieldArray.${index}.field`, defaultValue')
```

Replace would work but it's not much better than the above. It would look like:

```
 replace(getValues('fieldArray'))
 setValue(`fieldArray.${index}.field`, defaultValue')
```

You could of course modify what you pass into `reset` or `replace` and therefore avoid the `setValue` call, but this is also messy since I need to dig into the object and modify it (plus mutation issues since getValue doesn't return a deep copy).

Maybe a new method called `replaceField` could work? Or `updateField`? Not sure what you would want, but I would just like to reset not only the value but the meta state of a field array input. 

This mainly is due to conditionally rendered field array inputs which is mentioned in the other PR I made #7580

**Comment by bluebill1049** [comment]
- for group of inputs: `['a', 'b'].forEach(resetField)`
- for field array, we can consider to introduce seperate method.

**Comment by wdfinch** [comment]
Ok, thanks.

**Comment by Evalon** [comment]
`for field array, we can consider to introduce seperate method.`
I'm really waiting for this feature! I feel like after this the react-hook-form will be feature complete for all my cases.

**Comment by lobatolais** [comment]
That's the only feature I miss in react-hook-form. I wish we can see this being implemented in a near future.

**Comment by mariocsantos** [comment]
Waiting for the feature! 😃
