### ISSUE TITLE
Feature Request: Add reset API to field array

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#7584]
**Is your feature request related to a problem? Please describe.**
Currently, there are two ways to reset form values. By reset I am referring to:

1. Modifying form default values
2. Modifying form meta data (`isError`, `isTouched`, `isDirty`, etc.)

These two ways are:

1. The `reset` method
2. The `resetField` method

These are great for modifying regular form fields, but they don't really cover field array fields well. `reset` is too big and changes the entire form's values and `resetField` doesn't work on field array inputs.

**Describe the solution you'd like**
I propose adding or modifying existing field array methods to allow them to reset field array inputs. There are three functionalities that need to be covered.

1. Resetting an entire root field array
2. Resetting a field array element (group of fields at a specific index)
3. Resetting a single field array input

If we use the existing `replace` + `update` methods, we could add in options like so:

```
replace([{
    name: 'newValue'
}], {
    keepError: false,
    keepDirty: false,
    keepTouched: false,
    defaultValue: 'newDefaultValue'
})
```

If we use this pattern, we would still need a new method for modifying a single field array input. This could work as follows:

```
setField(`${index}.fieldName`, {
    keepError: false,
    keepDirty: false,
    keepTouched: false,
    defaultValue: 'newDefaultValue'
})
```

**Describe alternatives you've considered**
Using the `reset` methods for everything.

**Comment by nichita-pasecinic** [comment]
will this ever be done ? (I think reset API should work same way with normal fields, and field arrays)
