### ISSUE TITLE
[TS] Default values for nested fields are required

### ISSUE THREAD

**Issue by kusmierz** [react-hook-form/react-hook-form#759]
**Describe the bug**
Having nested fields in our FormSchema require to fill all nested fields in defaultValues.

**To Reproduce**
1. Introduce nested form schema, ie.:

```ts
type FormData = {
  user: {
    firstName: string;
    age: number;
  }
  website?: string;
}
```

2. define default values for nested field:

```ts
useForm<FormData>({
    defaultValues: {
      user: {
        age: 18,
      },
    },
  });
```

ERROR!
```
Type '{ age: number; }' is not assignable to type 'Shape<object, { firstName: string; age: number; }>'.
  Property 'firstName' is missing in type '{ age: number; }' but required in type '{ firstName: string; age: number; }'.ts(2322)
index.tsx(10, 5): 'firstName' is declared here.
index.tsx(9, 3): The expected type comes from property 'user' which is declared here on type 'Partial<Id<Partial<Pick<Shape<object, { user: Shape<object, { firstName: ...; age: ...; }>; website: string; }>, "user" | "website">> & Pick<Shape<object, { user: Shape<object, { firstName: ...; age: ...; }>; website: string; }>, never>>>'
```

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-typescript-14qt0

**Expected behavior**
No TS error at all.

**Additional context**
The problem is related with `UseFormOptions`' `defaultValues: Partial<FormValues>;`, it should be a `DeepPartial` instead:

```ts
// ...
export type DeepPartial<T> = {
  [P in keyof T]?:
  T[P] extends Array<infer U> ? Array<DeepPartial<U>> :
    T[P] extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>> :
      DeepPartial<T[P]>
};
// ...
export declare type UseFormOptions<FormValues extends FieldValues = FieldValues> = Partial<{
// ...
    defaultValues: DeepPartial<FormValues>;
// ...
```

**Comment by bluebill1049** [comment]
would you like to submit a PR for this? @kusmierz

**Comment by kusmierz** [comment]
sure, with pleasure!  See #762.

**Comment by bluebill1049** [comment]
thanks very much @kusmierz

**Comment by ScreamZ** [comment]
Side question, but is dot notation and nesting specified in the documentation? I flattened everything because most of time it's easier with ts :p 

<input name="user.age" />

**Comment by bluebill1049** [comment]
hey @ScreamZ we do support dot notation, but it does have limitation with TS support, because TS only does build time check. Recently i did add a runtime checker but it wasn't a good solution. So still try to figure out a better solution for name checking at runtime.

**Comment by ScreamZ** [comment]
That's a problem with Typescript, also experiencing it with Lodash / MongoDB. I should make an issue on the official repository someday.

I guess that currently, it's safer to not support it and rely on some kind of conversion after.

You can name your keys `a.b` without supporting nesting. And you can transform that later using kind of things like https://www.npmjs.com/package/flat.

By doing this, you keep types working by using a Flat Form and then if you want to, you just have to unFlat.
