### ISSUE TITLE
issue: Controlled inputs initiated with null don't get reset

### ISSUE THREAD

**Issue by Moshyfawn** [react-hook-form/react-hook-form#7590]
### Version Number

7.24.1

### Codesandbox/Expo snack

https://codesandbox.io/s/reset-controlled-example-forked-q62kd?file=/src/App.tsx

### Steps to reproduce

1. Go to [this CSB](https://codesandbox.io/s/reset-controlled-example-forked-okxvw?file=/src/App.tsx)
2. Enter any value into the Room input
3. Click on Submit button
4. See the form value reset under the Room input, but the actual input value hasn't been reset

### Expected behaviour

Controlled inputs get properly reset with it's default set to `string` or `null` as per [this comment](https://github.com/react-hook-form/react-hook-form/discussions/5858#discussioncomment-972991) and [RHF docs on controlled inputs](https://react-hook-form.com/api/usecontroller/controller)

See #7589 for context

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
cc @msageryd

**Comment by Evalon** [comment]
You need to provide a string to the input if you want it to use in a controlled mode. This is not related to react-hook-form but to react (you can see the warning in the console). So when you call reset in your example you also change it to uncontrolled input: [example](https://codesandbox.io/s/polished-cloud-8sn1e?file=/src/App.tsx)
Also, if you want to reset all fields to corresponding defaultValues you need to call reset() (without object) or provide defaultValues. If you want to reset only one field to default value you can use resetField.

**Comment by bluebill1049** [comment]
thanks, @Moshyfawn & @Evalon that's correct.

**Comment by Moshyfawn** [comment]
First of all, you're completely right. I got stuck thinking about the "not `undefined`" default value, forgot about how React rules _(also, didn't notice the console warning, my bad)_.

Also, the `reset` without args point - was testing things, sry!

Is it a good idea to update the controller docs notes to mention `null` as a "no-no" for controlled input's default value?

> Setting defaultValue inline or at useForm can not be undefined.

**Comment by bluebill1049** [comment]
@Moshyfawn i will update it now.

**Comment by bluebill1049** [comment]
updated: https://github.com/react-hook-form/documentation/commit/ac4caef464bbd06ba01dbe520094b0c74fb34060 deploying

**Comment by Evalon** [comment]
@bluebill1049 I think it's should be possible that defaultValues contains null for more complex cases (select or some custom controls).

**Comment by bluebill1049** [comment]
correct @Evalon hmmm how can I word it better...

**Comment by bluebill1049** [comment]
this is what i going with 

```
Setting <code>defaultValue</code> inline or at{" "}
<code>useForm</code> can not be <code>undefined</code>, and
<code>null</code> is also invalid for native input such as text
box.
```

**Comment by bluebill1049** [comment]
thank you guys 🙏 closing this issue.

**Comment by msageryd** [comment]
Thanks for the calrification. I will try to adopt to this.

On a side note, React-Native seems capable of handling null as field values. I am now initializing the form with a default object where all fields are set to null. When I call `reset()` all fields are cleared both in RHF and in the UI.

I guess that I should not rely on this if I want to use my form engine with web components going forward.
