### ISSUE TITLE
issue: rules for mounted do not change when removed

### ISSUE THREAD

**Issue by mmahalwy** [react-hook-form/react-hook-form#7591]
### Version Number

7.24.1

### Codesandbox/Expo snack

https://codesandbox.io/s/wandering-brook-6bohn?file=/src/App.tsx

### Steps to reproduce

1. Go to sandbox link
2. Click on submit button, see that required rules apply
3. Click on the button labeled 'click me', notice that the values change, and `should rules` is now false. At this point, rules should not apply
4. Click on submit button, see that required rules still apply when `register` has `{}` for rules
5. This happens for field array inputs and non-field arrays

### Expected behaviour

Validation rules should be changed when the rules object is changed. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mmahalwy** [comment]
I think the workaround is to set those validations as explicitly the opposite. So `{required: true}` needs to turn into `{ required: false}`. Having `{}` or `undefined` will not work because of this spread: https://github.com/react-hook-form/react-hook-form/blob/9d96ef85dcaca068a138890a7e187e7491d20d83/src/logic/createFormControl.ts#L911-L916

**Comment by bluebill1049** [comment]
Hmm interesting, never considered such a use case...  may take this as a design limation considering the amount of code needed to introduce to this problem.

**Comment by mmahalwy** [comment]
@bluebill1049 i think this could be solved by having `const optionsForRegister = {required: undefined, min: undefined, ...options}`; That way, `required` and others are explicit.

**Comment by bluebill1049** [comment]
> the amount of code needed to introduce this problem.

There are multiple ways to address this (i already tried), however, it increases the bundle size quite a bit for what it is worth. I am happy to take this as a design limitation and document this down.

**Comment by mmahalwy** [comment]
@bluebill1049 curious why my suggestion would have not worked? I can open a PR if that helps. It should increase the bundle size by a negligible amount.

**Comment by bluebill1049** [comment]
send a PR we will see the bundlesize increase.

**Comment by mmahalwy** [comment]
actually, come to think of it, why do we need this?
```ts
...(field && field._f ? field._f : { ref: { name } }),
```

Feels like it could be just
```ts
...({ ref: { name } }),
```

Logic here is every time you register a field with the same name, the previous one shouldnt be merged. This is an explicit override of previously reigstered

**Comment by bluebill1049** [comment]
there is input `ref` and `refs`

the shortest i have come up with 

```
{
  _f: {
    ...(field && field._f
      ? {
          ref: field._f.ref,
          name: field._f.name,
          refs: field._f.refs,
          mount: field._f.mount,
        }
      : { ref: { name } }),
    name,
    mount: true,
    ...options,
  },
}
```

that still increase the bundlesize quite a bit for what it worth.

**Comment by mmahalwy** [comment]
by how much?

**Comment by bluebill1049** [comment]
by pretty much a new feature worth of bytes.

**Comment by mmahalwy** [comment]
https://github.com/react-hook-form/react-hook-form/pull/7595

**Comment by bluebill1049** [comment]
```
| Filename | Size | Change |
| :--- | :---: | :---: |
| `dist/index.cjs.js` | 8.75 kB | +20 B (0%) |
| `dist/index.umd.js` | 8.87 kB | +20 B (0%) |

```

**Comment by bluebill1049** [comment]
thanks for the PR tho, if you would like to help you can send a PR to improve the doc on this particular usage.

**Comment by bluebill1049** [comment]
I am uploading the doc now.
