### ISSUE TITLE
Feature request: Allow unregister to keep default values 

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#7592]
**Is your feature request related to a problem? Please describe.**
I like the `unregister` method and `shouldUnregister` prop as a way to reset or remove field values when an input is unmounted. The issue is I don't want the default value for that input to be removed in the process

**Describe the solution you'd like**
I would like to have the same behavior as `unregister` but the option to keep the default value for the input being unregistered. This would solve the need in #7580. I think a global option on `useForm` could work for this. The `unregister` method could take an options object as well for more granular control. 

**Describe alternatives you've considered**
Using the `reset` API. This will be a problem in V8 if we lose the ability to remove validation errors for unmounted inputs. If an input is mounted and is invalid and we remove it, our form state is still invalid without the ability to reset errors.

**Comment by bluebill1049** [comment]
<img width="971" alt="Screen Shot 2022-01-20 at 12 55 51 pm" src="https://user-images.githubusercontent.com/10513364/150248443-2ae647f2-57c7-4bce-8a51-e24fc6687b67.png">

isn't it already there?

**Comment by wdfinch** [comment]
My bad, I didn't see that. Is there anyway to control this for the `shouldUnregister` prop? This is where use this feature more.

**Comment by bluebill1049** [comment]
no.

**Comment by bluebill1049** [comment]
I am happy to see feature request coming as it give users choice, but at the same time this probably is pretty easy to work around by extending Controller with a `useEffect` with `unregister`.
