### ISSUE TITLE
Regression: shouldUnregister not removing field array input values in 7.22.3 onward 

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#7593]
### Version Number

7.24.1

### Codesandbox/Expo snack

https://codesandbox.io/s/ecstatic-blackburn-9y4fh?file=/src/App.tsx

### Steps to reproduce

1. Go to the sandbox
2. Click on the checkbox input to hide one of the fields
3. Look at the console log for watch and notice unmounted input field is still present in form values

### Expected behaviour

I would expect the unmounted field array input to be removed from form values. This is how it worked on older versions of V7. The exact version this broke was 7.22.3. I didn't see anything in the change log about this behavior and this is a breaking change. I'm following the rules listed in the docs such as using `useWatch` to control whether the input is shown. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
for more details here it the issue: https://github.com/react-hook-form/react-hook-form/issues/7313

**Comment by wdfinch** [comment]
Thanks. I'm not sure I understand. Is the issue that I'm using react-select and that's not a native input? Is there anyway to get the expected behavior above?

**Comment by mmahalwy** [comment]
running into same issue too, 7.24.1

**Comment by wdfinch** [comment]
I think #7313 is a separate issue. It seems like the issue there is fields are not being added back after being remounted. The issue here is fields are not being removed to begin with.

**Comment by mmahalwy** [comment]
I can see that `unregister` is being called on the field array itself, but not individual items in the field array

**Comment by mmahalwy** [comment]
Oh yeah, this looks fishy:
https://github.com/react-hook-form/react-hook-form/pull/7317/files#diff-3f5bdfa7d822b4562b8e1c72dd1996197fe93478b039779bb78853ab3ae2a3feR68-R72

```ts
isArrayField
        ? _shouldUnregisterField && !control._stateFlags.action
        : _shouldUnregisterField
        ? control.unregister(name)
        : updateMounted(name, false);
```

Nested ternaries are confusing and shouldnt be used. This technically means `control.unregister(name)` is called when `_shouldUnregisterField && !control._stateFlags.action` is false, which is incorrect.

**Comment by bluebill1049** [comment]
> Nested ternaries are confusing and shouldnt be used. 

This is so we use fewer bytes.

**Comment by mmahalwy** [comment]
> > Nested ternaries are confusing and shouldnt be used.
> 
> This is so we use fewer bytes.

Totally understand. Maybe a middle ground is to wrap them with `()`?

**Comment by bluebill1049** [comment]
> Totally understand. Maybe a middle ground is to wrap them with ()?

any code style/lint should be taken care of by lint or prettier.

**Comment by bluebill1049** [comment]
will look into this after work.

**Comment by mmahalwy** [comment]
thanks for the fix @bluebill1049 !
