### ISSUE TITLE
issue: DeepMap and DeepPartial don't account for `unknown` type

### ISSUE THREAD

**Issue by qlonik** [react-hook-form/react-hook-form#7594]
### Version Number

7.24.1

### Codesandbox/Expo snack

https://codesandbox.io/s/confident-benji-n48vb?file=/src/App.tsx

### Steps to reproduce

1. Go to the link above
2. Scroll down to line 29
3. See error

### Expected behaviour

Error type for the registered field shouold be `FieldError` instead of `{}`. The `DeepPartial` and `DeepMap` util types should account for `unknown` type of value. Potentially other recursive types should do it to. 

### Proposed fix:

Similar to how there is `IsAny` check and the `isNever` helper, the following `IsUnknown` helper can be added and used:

```ts
type IsUnknown<T> = [unknown] extends [T] ? true : false
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
what's the usage to have a type of `Record<string, unknonw>`? It's basically doing no type check right?

**Comment by qlonik** [comment]
Yes. We are building the form based on fields we received from the API. We don't care about the value type, since we will receive them from the form as strings and will submit them back to API as strings. 

Hmm, maybe we should just be declaring data for those forms as `Record<string, string>` and then this issue is not going to be relevant. 😅

**Comment by bluebill1049** [comment]
yea, I think that's probably the preferable type. I mean we can add IsUnkown check but probably not add much value for the type check.
