### ISSUE TITLE
issue: Uncontrolled inputs: Memoized component inputs not updating through Reset(reset from useForm)

### ISSUE THREAD

**Issue by Peter-AMD** [react-hook-form/react-hook-form#7607]
### Version Number

7.24.2

### Codesandbox/Expo snack

https://codesandbox.io/s/provider-perf-forked-6lyw9?file=/src/App.js

### Steps to reproduce

I actually forked [https://react-hook-form.com/advanced-usage#FormProviderPerformance](url), with a few modifications.

1. Make sure the codesandbox virtual browser is refreshed
2. Click on "reset" button
3. input registered as "immediateInput" is successfully reset
4. input registered as "test"(memoized input component) is on default state

### Expected behaviour

- "Test" input(memoized) should update after the reset.
![image](https://user-images.githubusercontent.com/28400709/150357514-caa0de1d-76a4-4e96-a76f-df62687f3108.png)
- Notice if we set `shouldUnregister` to `true` then click reset, it will show "Test" input is not registered anymore.
![image](https://user-images.githubusercontent.com/28400709/150358520-72a04218-2662-4592-9777-2bed33f09a70.png)

- Other things to note, after clicking "reset" button, when editing the "immediateInput" input field through typing, it will now show the updated value of "test" input. Even if we set `shouldUnregister` to `true` , "test" input will still update as long as we type on "immediateInput" input, but nothing will happen if we edit first the "test" input field after clicking "reset" button.

I was stuck with this issue for a few days now, tried reading the docs related to the issue several times, I still can't find an answer, that's why I decided to post an issue. I might be missing something.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
The latest version of RHF that successfully have `reset` the memoized input was [`7.6.10`](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.6.10). The issue is reproducable since the [`7.7.0`](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.7.0) release.

**Comment by JamesWong1999** [comment]
`prevProps.formState.isDirty === nextProps.formState.isDirty` will remain false right with `React.memo`, the check is never pass.

**Comment by JamesWong1999** [comment]
> The latest version of RHF that successfully has reset the memoized input was 7.6.10. The issue is reproducable since the 7.7.0 release.

@Moshyfawn I don't see any version supporting the above usecase, tried 7.6 and 7.7

**Comment by Moshyfawn** [comment]
You're right, @JamesWong1999, sorry. It may sound dumb, but I've managed to make it work in some CSB forked from [that FormProvider Perfomance CSB example](https://react-hook-form.com/advanced-usage#FormProviderPerformance). Can't reproduce again, tho

**Comment by Peter-AMD** [comment]
Hi @Moshyfawn , 

> `prevProps.formState.isDirty === nextProps.formState.isDirty` will remain `true` right with `React.memo`, the check is never pass as `false`.

It will pass false, it just needs a some sort of re-render on the component input, as what I've mentioned in my "Other things to note", "test" input will behave properly once we typed something in "immediateInput".

>  also why is `watch` used in the function? shouldn't that be `getValues()`.

I was thinking I need to get the "actual"(quoting because I'm not sure if it is) list of registered inputs.
- If we use `getValues()` and set `shouldUnregister: true` in `useForm`, it will still show the value of "test" input.
- If we use `watch()` and set `shouldUnregister: false`(default) in `useForm`, "test" will not be returned as a register input.

**Comment by Peter-AMD** [comment]
> You're right, @JamesWong1999, sorry. It may sound dumb, but I've managed to make it work in some CSB forked from [that FormProvider Perfomance CSB example](https://react-hook-form.com/advanced-usage#FormProviderPerformance). Can't reproduce again, tho

Hi @Moshyfawn , do you still have the CSB that is working fine?

**Comment by JamesWong1999** [comment]
> It will pass false, it just needs a some sort of re-render on the component input, as what I've mentioned in my "Other things to note", "test" input will behave properly once we typed something in "immediateInput".

what's the point of the check if it's always going to return `false` when you call reset without any data modifed?

> I was thinking I need to get the "actual"(quoting because I'm not sure if it is) list of registered inputs.

`watch` is not made for inline function instead before `render`, that's the doc sas.

**Comment by Peter-AMD** [comment]
Hi @JamesWong1999 , thanks for the response.

> what's the point of the check if it's always going to return false when you call reset without any data modifed?
the `defaultValues` are set to an empty string. I believe data is modified when we click the "reset" button? Or am I misunderstanding what you're saying?

> watch is not made for inline function instead before render, that's the doc sas.
I'm actually using `watch` here just for a test. I never use it like that if I'm planning to ship a code.

**Comment by Peter-AMD** [comment]
I actually manage to make it work by adding a `useState`, setting this `state` every after `reset`.
The `state` value is then attached to `<NestedInputContainer key={resetCounter} />` (resetCounter is my state name) as a key.
I feel this is somewhat hacky though.

Here's the csb: https://codesandbox.io/s/provider-perf-forked-lgt6y?file=/src/App.js:1195-1238

**Comment by Peter-AMD** [comment]
I updated the main CSB for this one.
- Added `type="button"` to the "reset" button.
- Added some comments above the `watch()` console.log

**Comment by bluebill1049** [comment]
@Peter-AMD I will looking into it after work today.

**Comment by Peter-AMD** [comment]
> @Peter-AMD I will looking into it after work today.

Thanks @bluebill1049 , yodabest.

**Comment by bluebill1049** [comment]
ok here is the reason behind this issue.

### Here are the steps:

- invoke `reset` all input references and form values will be removed 
- then we will update input values 
- however, the memoed component never received another render/state update, hence input references remain **unknown** and **empty**, hence input value can't be updated.

### Solutions

- Make sure the component gets re-render after the reset and pay attention to the memo props to compare
- use setValue instead of `reset`, so the reference will still be retained.

**Comment by official-carledwardfp** [comment]
Use `prevProps.formState.isDirty && nextProps.formState.isDirty` instead of `prevProps.formState.isDirty === nextProps.formState.isDirty`

as what @bluebill1049 have said

**Comment by Peter-AMD** [comment]
Yes, it's all good now. Thank you @bluebill1049 and @official-carledwardfp :D

**Comment by Peter-AMD** [comment]
Closing this thread now, thank you everyone!

**Comment by bluebill1049** [comment]
you are welcome. thank you @Moshyfawn, @JamesWong1999 and @official-carledwardfp
