### ISSUE TITLE
issue: Error object

### ISSUE THREAD

**Issue by GeorgiyCox** [react-hook-form/react-hook-form#7608]
### Version Number

7.24.1

### Codesandbox/Expo snack

https://codesandbox.io/s/unruffled-tree-kd8pz?file=/src/App.js

### Steps to reproduce

1. Checkout the sandbox;
2. Сlick on submit button;
3. In the console an example of the received error object
shape of  object: 
Yup.object({
    nameInput: Yup.object({
        value: Yup.string().required("valueDoc"),
        label: Yup.string().required("lavelDoc")
})
4. Expected behavior: error.message;
    as a result: error.value.message;

### Expected behaviour

Is it correct that the error object returns with the shape of the validated object? Is that how it should be?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
I believe, this is the intended behavior since V4. See [this comment](https://github.com/react-hook-form/react-hook-form/issues/735#issuecomment-569453961)

**Comment by bluebill1049** [comment]
Thanks, @Moshyfawn that's correct.
