### ISSUE TITLE
watch('fieldName') results Error: fieldName field not found when using partial form

### ISSUE THREAD

**Issue by kusmierz** [react-hook-form/react-hook-form#761]
**Describe the bug**
"Error: fieldName field not found." on specific code, see below.

**To Reproduce**
I guess it is connected with [this commit](https://github.com/react-hook-form/react-hook-form/pull/756/files), because the code used to work with `4.3.1-beta.2`.

Basically it seems it's about using `FormContext` in another component. Removing `<Controller />` from line 29 removes that error tho... weird.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-unregister-fbgbr

**Expected behavior**
No error :)

**Comment by IronSean** [comment]
I've also run into this. In my case, it's because I don't register the form until `useEffect` but the watch function runs when the component function runs.

To get around this I'm thinking about switch to the Controller component instead of the use of manual registering and watch, but one input is a date range picker which needs to have both the start and end date controlled so I'm not sure I can use it under a single Controller component.

**Comment by bluebill1049** [comment]
thanks @IronSean and @kusmierz i will take a look into this. maybe we should change this into a warning dev mode instead of throw an error.

**Comment by bluebill1049** [comment]
i am going to remove this throw error for now.

**Comment by mikaelkristiansson** [comment]
I get the same problem when using the Controller

**Comment by bluebill1049** [comment]
sorry guys... removing now

**Comment by kusmierz** [comment]
> maybe we should change this into a warning

I'm not sure if it's a good solution. I mean imho there should be a possibility to custom `register` and `watch` fields without any warning (as it is proper way, isn't it?)

**Comment by bluebill1049** [comment]
> > maybe we should change this into a warning
> 
> I'm not sure if it's a good solution. I mean imho there should be a possibility to custom `register` and `watch` fields without any warning (as it is proper way, isn't it?)

agree, i will remove it for now until we have a better solution

**Comment by bluebill1049** [comment]
This has been patched and released. If you still encounter issue let me know. thanks bill
