### ISSUE TITLE
issue: watch doesn't get defaultValue of conditional field

### ISSUE THREAD

**Issue by uyig** [react-hook-form/react-hook-form#7631]
### Version Number

7.25.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-js-forked-yleqs?file=/src/App.js

### Steps to reproduce

1. enter "f" in the field "First name"
2. open console, first call "watch" ​​doesn't contain default value of "Last name"

### Expected behaviour

The first call "watch" will get the new value "First name" and the defaultValue of the field "Last Name"

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
You want to set your field's defaultValue at the hook level. See [RHF docs on `useForm` API](https://react-hook-form.com/api/useform#useFormRef)

**Comment by bluebill1049** [comment]
Thanks, @Moshyfawn this is expected behavior.
