### ISSUE TITLE
Validate Optimization

### ISSUE THREAD

**Issue by iamwelk** [react-hook-form/react-hook-form#764]
**Is your feature request related to a problem? Please describe.**
When I call handleSubmit, it'll trigger form's validation.But some fileds has been validated when I edited. Maybe we can remember fields that have been validated and only check fields which not validate yet

**Describe the solution you'd like**
When submit, jump fields that have been checked

**Comment by bluebill1049** [comment]
thanks for the great suggestion @iamwelk! ❤️  That would be a good performance enhancement for validation, however, every feature requires more code and impact this small library (~6kb). I hope we can as small as it is for a bit longer, i will keep this feature request in our backlog tho, so if there are a lot of devs request for such feature we can always pull it out and work on it.

**Comment by bluebill1049** [comment]
<img width="332" alt="Screen Shot 2020-01-03 at 6 39 42 pm" src="https://user-images.githubusercontent.com/10513364/71712219-6d103580-2e58-11ea-9c06-0dc5cab5226d.png">
will close this feature request for now :)

**Comment by iamwelk** [comment]
OK, Thx~

**Comment by bluebill1049** [comment]
thanks for understanding ✌🏻
