### ISSUE TITLE
issue: Unable to setFocus to Controller after reset

### ISSUE THREAD

**Issue by ryanmk54** [react-hook-form/react-hook-form#7648]
### Version Number

7.25.0

### Codesandbox/Expo snack

https://codesandbox.io/s/vigilant-resonance-8kjrw?file=/src/App.js

### Steps to reproduce

1. Click Reset
2. Click Focus
4. The page crashes

### Expected behaviour

The field should be focused.

This works in 7.23.0

It also works in the following code sandbox: https://codesandbox.io/s/trusting-hugle-ixey2?file=/src/App.tsx
I'm not sure why wrapping it in the form with a handler would fix it. I have my Controlled input wrapped in a form and I still get an error.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
Chrome output
Cannot read properties of undefined (reading '0')

Firefox output
t.refs is undefined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
> It also works in the following code sandbox: https://codesandbox.io/s/trusting-hugle-ixey2?file=/src/App.tsx
I'm not sure why wrapping it in the form with a handler would fix it. I have my Controlled input wrapped in a form and I still get an error.

Notice, the RHF hooks are being imported from `./src` folder in the same CSB workspace. Idk what version if RHF is it, but if you change the import from `./src` to `react-hook-form`, you'll see the same issue you've described
![image](https://user-images.githubusercontent.com/16290753/150852615-292abc32-834b-4e74-94fa-59c23c18bf94.png)
