### ISSUE TITLE
FileUpload Quesion

### ISSUE THREAD

**Issue by Plummtw** [react-hook-form/react-hook-form#765]
I've already read the Issue#127 and Issue#274, but I still don't understand how to do with the FileUpload, maybe some FileUpload example would be good.

The following the current code I made, but I just want to change it to use react-hook-form.
Thanks

function ConnectedUserIconPage() {
 const [form, setForm] = React.useState({}) 

 const onChangeHandlerFile = (event) => {
    // eslint-disable-next-line no-console
    console.log(event.target.files[0])
    setForm({...form, file: event.target.files[0]})
  }

  const onChangeHandler = (event) => {
    let name = event.target.name
    if (name != null)
      setForm({...form, [name]: event.target.value})
  }

  return(<div>
    <Form className="container-fluid" onSubmit={onSubmit}>
      <Form.Group>
        <Form.Label>Comment : </Form.Label>
        <Form.Control id="formFileComment" type="text" name="filecomment" onChange={onChangeHandler} required></Form.Control>
      </Form.Group>

      <Form.Group className="files color">
        <Form.Label>File : </Form.Label>
        <Form.Control id="formUploadFile" type="file" name="file" onChange={onChangeHandlerFile} required></Form.Control>
      </Form.Group>
      <Button type="submit" variant="primary" className="m-1">Upload</Button>
    </Form>
  </div>)

**Comment by bluebill1049** [comment]
please spend your time learning how its API: https://react-hook-form.com/get-started I have spent a lot of my time on documentation. You ask more questions later on in our spectrum channel.
