### ISSUE TITLE
Validation mode "onBlur", formState.isValid starts as "true" and instantly change to "false"

### ISSUE THREAD

**Issue by VGLoic** [react-hook-form/react-hook-form#766]
**Describe the bug**
When validation mode is `onBlur`, the `formState.isValid` starts as `true` and instantly updates to `false`. The expected value was `false` of course :).

**To Reproduce**
Use codesandbox below or
1. useForm with `mode: "onBlur"`
2. Use a native input with `registered: true` as validation rules
3. `console.log` the `formState.isValid`

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-rhfinput-k4lni

**Expected behavior**
Expected `formState.isValid` starts as `false`

**Desktop (please complete the following information):**
OS: iOS
Browser Chrome
Version 78.0.3904.97

**Comment by bluebill1049** [comment]
That's expected behavior and almost by design. react-hook-form embrace uncontrolled component, so `value` can live inside input which means validation needs or could happen at `render` level, rather than controlled component you can validate by `defaultValues` (state)

**Comment by VGLoic** [comment]
Thanks for the quick answer! :)
