### ISSUE TITLE
issue: handle global error in forms

### ISSUE THREAD

**Issue by alikazemkhanloo** [react-hook-form/react-hook-form#7661]
**Is your feature request related to a problem? Please describe.**
when I get response after submitting a form, I get two types of errors: a) field related errors, which can be handled by `setError` b)  some global errors, like user not found. there is no place for this kind of errors in `react-hook-form`

**Describe the solution you'd like**
there can be a field starting with dangle (_) to used as global error for the form.

**Describe alternatives you've considered**
Now I use a custom field named `_error`, but typescript keeps complaining about it, as there is no `_error` field in my inputs.
another workaround was to use a local state.

**Additional context**
in `redux-form` we could use `_error` field for global errors. and it's handled nicely providing a prop named `error`.

**Comment by bluebill1049** [comment]
thanks, pinging to the project board.

**Comment by alikazemkhanloo** [comment]
I'm willing to contribute to this specific issue, but the question is how we should handle it. My solution is to add _error as a reserved field for the global error.

**Comment by Moshyfawn** [comment]
> I'm willing to contribute to this specific issue, but the question is how we should handle it. My solution is to add _error as a reserved field for the global error.

Any feature request goes through community up-voting the feature to see if the feature is in demand before it goes into development

**Comment by julio3266** [comment]
@Moshyfawn  I understand that there are limitations, but since I have a separate form on another useForm screen, and it generates multiple arrays, would it be possible to generate an error for each different entity?

**Comment by bluebill1049** [comment]
Idea: 

cc @Moshyfawn 

related: https://github.com/react-hook-form/react-hook-form/issues/7278

```tsx
handleSubmit((data) => {
  const result = await request();

  return {
    values: data, // will return by handleSubmit
    errors: {
      dataMismatch: {
        type: 'server',
        message: 'whatever',
      }
    } // will update errors object and to be persisted and only `clearErrors` and `handleSubmit` method can remove those error
  }
})
```

**Comment by Moshyfawn** [comment]
Hm.. what about the fact that it's pretty common to do
```js
handleSubmit(data => updateEntry(data).then(res => success(res)).catch(err => fail(err)))
```

Meaning, if you use `.then().catch()`, the API can return an entry `object`, which is gonna be `return`ed

**Comment by bluebill1049** [comment]
thanks @Moshyfawn correct above solution is not valid then.

**Comment by bluebill1049** [comment]
Actually we don't return anything at the moment, only catch part is valid.

**Comment by Moshyfawn** [comment]
> Actually we don't return anything at the moment, only catch part is valid.

I'm not sure I fully understand what you mean by that :P

Here's a thought: is there a way we can have.. IDK, I custom error we can allow to throw and have a `catch` inside the `handleSubmit` logic that would handle it i such a way that the form submission's gonna fail and take an `object` of errors to set?..

FYI, It's a very spontaneous raw thought. I'm not sure how much sense it makes lol

**Comment by bluebill1049** [comment]
> I'm not sure I fully understand what you mean by that :P

as we don't return what's returned by `onValid` callback, https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/createFormControl.ts#L1051 which was related to another feature request #7278

Throw error will probably need to have specific errors type before we can react to that. 

**when the user doesn't catch errors:**

```tsx
handleSubmit((data) => {
  const result = await request();

  return {
    values: data,
    errors: {
      dataMismatch: {
        type: 'server',
        message: 'whatever',
      }
    }
  }
}).catch((error) => {
  // will catch stuff get throw inside the callback. 
  // setError()
})
```

**when users do catch errors:**

```tsx
handleSubmit((data) => {
  try {
    const result = await request();
    return {
        values,
        errors: {
          dataMismatch: {
            type: 'server',
            message: 'whatever',
          }
        }
      }
  }

  return {
    values: data,
  }
}).then(({ values }) => {
  console.log(values)
})
```

**Comment by ixartz** [comment]
@bluebill1049 is it any update about this? It would make the code much more cleaner and at the same time, I don't see any drawbacks because it's an optional feature. You won't be forced to use it.

There are a lot of reaction in the first comment. I think there are lot of people in the same case.

For example one of my use case can be related to the database connection. My API failed to connect to the database and the error isn't related to any fields.

**Comment by bluebill1049** [comment]
@ixartz any thoughts on the API proposal above? https://github.com/react-hook-form/react-hook-form/issues/7661#issuecomment-1112766670

**Comment by ixartz** [comment]
@bluebill1049 thank you for your response and for maintaining this project.

We can take examples from other libraries which has already solved this issue.
I don't have any strong opinion, I like the idea to use `_error` like @alikazemkhanloo suggested.

**Comment by alikazemkhanloo** [comment]
I started this discussion but now I'm starting think maybe handling global errors alongside field-specific errors is not a good idea. it depends on the design of the project, but showing a toast is a better approach than showing a `<p />` tag based on the errors' state.

**Comment by jrobeson** [comment]
this issue was closed as completed, but folks are still talking about it. If it's not done, then shouldn't it be reopened?

**Comment by Moshyfawn** [comment]
> this issue was closed as completed, but folks are still talking about it. If it's not done, then shouldn't it be reopened?

The feature is tracked on the project board and closed as an issue for maintainer's convenience

**Comment by bluebill1049** [comment]
todo: need to include async default values error handling.

**Comment by bluebill1049** [comment]
RFC: https://github.com/react-hook-form/react-hook-form/discussions/9691

**Comment by aksdevac** [comment]
It seems in 7.43 version only setError allows `root.*` values, clearErrors method is giving TS error for `root.*` key.

**Comment by bluebill1049** [comment]
> It seems in 7.43 version only setError allows `root.*` values, clearErrors method is giving TS error for `root.*` key.

can you create an issue with this?

**Comment by aksdevac** [comment]
Ok, just created an issue https://github.com/react-hook-form/react-hook-form/issues/9842.
