### ISSUE TITLE
issue: Autofill with 'onTouch' mode doesn't validate other fields after reset

### ISSUE THREAD

**Issue by illia-chaban** [react-hook-form/react-hook-form#7669]
### Version Number

7.5.2

### Codesandbox/Expo snack

https://codesandbox.io/s/fervent-solomon-cqwui?file=/src/App.tsx

### Steps to reproduce

1. autofill the form --> should see cellphone error since it should always throw
2. submit to reset
3. autofill again --> the error doesn't show up

### Expected behaviour

the cellphone field error should show up

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
at the moment, revalidate mode doesn't have onTouch which is something missing...

`reValidateMode: onChange | onBlur | onSubmit = 'onChange'` so after submit it will fall back to `onChange` and hence no blur is firing error.
