### ISSUE TITLE
issue: FieldArray replace after touch produce invalid value for getValues()

### ISSUE THREAD

**Issue by Evalon** [react-hook-form/react-hook-form#7686]
### Version Number

7.25.1

### Codesandbox/Expo snack

https://codesandbox.io/s/usefieldarray-virtual-input-forked-1bhdf?file=/src/App.js

### Steps to reproduce

1. Click on field
2. Click outside of field
3. Click replace button
4. Click on field and remove value completely
5. Click on submit
6. See value in console. (The result of getValues call)

### Expected behaviour

Expected result of getValues call:
`{
  fieldArray: [{ firstName: '' }]
}`

Observed result of getValues call: 
`{
  fieldArray: [{ firstName: true }]
}`

I think somehow object from the values comes to `_formState.touchedFields` and mutated [there](https://github.com/react-hook-form/react-hook-form/blob/ca27da8a1f3dd5462f9b7d55d3453722ff7d356d/src/logic/createFormControl.ts#L309) to boolean value (true).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
regression with this PR: https://github.com/react-hook-form/react-hook-form/commit/6da966223109000df2535cb806de88f009bf7191

**Comment by Evalon** [comment]
Thank you :)
