### ISSUE TITLE
React Native: Invalid prop `value` of type `number` supplied to `TextInput`, expected `string`.

### ISSUE THREAD

**Issue by mjstelly** [react-hook-form/react-hook-form#769]
**Describe the bug**
Any input in either form field first throws the warning 
`Warning: Failed prop type: Invalid prop `value` of type `number` supplied to `TextInput`, expected `string` in TextInput (at Login.js:21)`

Then, if the input is submitted, the app crashes with the following error:
```
JSON value '{
    firstName = 7;
    lastName = 15;
}' of type NSMutableDictionary cannot be converted to NSString
```
**To Reproduce**
1. Copy the react-native form example into an empty project.
2. Launch the app in an ios simulator (iPhone 11, ios 13.0 used). I haven't tested in android, yet.
3. Input text into the First Name field. Notice the simulator Yellowbox warning.
4. Press button to submit the form.

**Expected behavior**
Expected the input to throw no warning. Then, on submit, the app pops an alert box that displays "Form Data" and the data output of the form.

**Screenshots**
![form-submit-error](https://user-images.githubusercontent.com/313819/71758575-19f1af00-2e67-11ea-9d32-dc8357ac8fa6.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.1 (19B88)

**Smartphone (please complete the following information):**
 - Simulator: iPhone 11
 - OS: ios 13.0

**Comment by bluebill1049** [comment]
In terms of the crash on submit. That's for demo purpose (you can replace that to console.log), i didn't crash on the my expo demo app.
https://snack.expo.io/@bluebill1049/react-hook-form-input

I will take a look the warning part. any chance of supplying a screenshot of the warning?

**Comment by bluebill1049** [comment]
I did a test at my end, there is no issue. I am uploading the video.
![workingVersion](https://user-images.githubusercontent.com/10513364/71759034-55d65400-2efb-11ea-880b-b31870595e7d.gif)

**Comment by mjstelly** [comment]
![form-entry-warning](https://user-images.githubusercontent.com/313819/71759073-5aecc200-2e6d-11ea-9b3a-79d659cdb5b5.png)
Here is a screenshot of the warning.

**Comment by bluebill1049** [comment]
hmmmm strange... can you get to know your `react-native` version?

**Comment by bluebill1049** [comment]
i couldn't reproduce even with latest `create-react-native-app`

**Comment by mjstelly** [comment]
I used the generic react-native init to generate the base app.
These are my react packages:

"react": "16.9.0",
    "react-hook-form": "^4.2.2",
    "react-native": "0.61.5",

Sincerely,
Michael Stelly | M: +1.918.978.2000 Blog | LinkedIn | Github

**Comment by bluebill1049** [comment]
> react-native init

ok i will give this a try.

**Comment by bluebill1049** [comment]
> I used the generic react-native init to generate the base app. These are my react packages: "react": "16.9.0",     "react-hook-form": "^4.2.2",     "react-native": "0.61.5", Sincerely, Michael Stelly | M: +1.918.978.2000 Blog | LinkedIn | Github
> […](#)
> On Jan 3, 2020, 9:21 PM -0600, Bill ***@***.***>, wrote: Closed #769. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I will give it a try

**Comment by bluebill1049** [comment]
no warning at all. I have spend quite a lot time on investigating this... no more further investigation.
<img width="1008" alt="Screen Shot 2020-01-04 at 3 10 08 pm" src="https://user-images.githubusercontent.com/10513364/71759651-50c9d280-2f04-11ea-9254-73f402e2129d.png">

**Comment by fxamauri** [comment]
I noticed that the warning appears when there is no onChange property with "args [0] .nativeEvent.text". I solved the problem added this prop.
Example: 
```
<Controller
    as={<TextInput />}
    control={control}
    rules={{ required: true }}
    name="name"
    onChange={args => {
        return {
             value: args[0].nativeEvent.text,
        };
    }}
    defaultValue=""
/>
```

**Comment by IngenieroLata** [comment]
I got the same error on a brand new project I started with `expo`.

<img width="663" alt="Screen Shot 2020-03-17 at 12 01 28 PM" src="https://user-images.githubusercontent.com/5667514/76881443-228f3a00-6847-11ea-9e6a-d5b9e02500b0.png">

Here is the component

```typescript
import React, { FC } from 'react'
import { SafeAreaView, Text, TextInput, Button } from 'react-native'
import { useForm, Controller } from 'react-hook-form'
import { StackNavigationProp } from '@react-navigation/stack'
import { Title } from 'react-native-paper'

import { ScreenParamList } from 'navigation'

type NotificationsScreenNavigationProp = StackNavigationProp<
  ScreenParamList,
  'Notifications'
>

interface NotificationsScreenProps {
  navigation: NotificationsScreenNavigationProp
}

const NotificationsScreen: FC<NotificationsScreenProps> = () => {
  const { control, handleSubmit } = useForm()

  const onSubmit = data => {
    console.log('data', data)
  }

  return (
    <SafeAreaView>
      <Title>Notifications</Title>

      <Text>First name</Text>
      <Controller
        as={<TextInput />}
        control={control}
        rules={{ required: true }}
        name="firstName"
        onChange={args => {
          return {
            value: args[0].nativeEvent.text,
          }
        }}
        defaultValue=""
      />

      <Button onPress={handleSubmit(onSubmit)} title="submit" />
    </SafeAreaView>
  )
}

export default NotificationsScreen
```

**Comment by bluebill1049** [comment]
`onChange={args => args[0].nativeEvent.text}` i probably need to update the doc, but take a look the error message.

**Comment by zooboole** [comment]
If you have any text input check the type. In my case I had this:

`keyboardType={'phone-pad'}`

Then I changed to

`keyboardType={'numeric'}`

**Comment by johnlai1011** [comment]
> ![form-entry-warning](https://user-images.githubusercontent.com/313819/71759073-5aecc200-2e6d-11ea-9b3a-79d659cdb5b5.png)
> Here is a screenshot of the warning.

I have this warning after upgrade expo to ^37.0.0. The other project with expo ^36.0.0 have no issue. Please advice for expo 37. Thanks a lot!

**Comment by bluebill1049** [comment]
check your data type, number vs string

**Comment by stephenfjohnson** [comment]
Everything is correct but still throwing the error.

**Comment by bluebill1049** [comment]
@stephenfjohnson can you show some code sand or perhaps a repo? otherwise, I am chasing a ghost here.

**Comment by SDP190** [comment]
@stephenfjohnson I have same issue, when field bound to input has a numeric value, I get this error: "Invalid prop `value` of type `number` supplied to `TextInput`, expected `string`"

**Comment by stephenfjohnson** [comment]
@SDP190 I haven't resolved it yet but i do think it is tied to https://reactnative.dev/docs/textinput#defaultvalue only accepting a type of string.

**Comment by jcahuana** [comment]
Hello, @stephenfjohnson I resolve it using **String()** to wrap the value **<TexInput value={String(value)} keyboardType={'numeric'} ... />**. Maybe this article can help you https://aboutreact.com/warning-invalid-prop-value-of-type-number-supplied-to-textinput-expected-string/

![Screenshot_20200622-220954_Expo](https://user-images.githubusercontent.com/1317580/85356733-4791e980-b4d5-11ea-8f13-1574dd04fe50.jpg)

**Comment by amit13091992** [comment]
I tried to make it work like this:

```
<TextInput
            keyboardType={'numeric'}
            value={result.toString()}
            onChangeText={(text) => setResult(text)}
          />
```

and it works fine.
