### ISSUE TITLE
issue: replace of useFieldArray does not work since 7.25.1

### ISSUE THREAD

**Issue by michalbundyra** [react-hook-form/react-hook-form#7700]
### Version Number

since 7.25.1

### Codesandbox/Expo snack

https://codesandbox.io/s/modest-mclean-197xt?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/modest-mclean-197xt?file=/src/App.tsx
2. Click on `Click BUTTON`
3. See error:
```
TypeError
undefined is not an object (evaluating 'args.argA')
```

### Expected behaviour

No error - as on previous version (7.25.0 and down are fine, bug is since 7.25.1+)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Can't reproduce: see [this CSB](https://codesandbox.io/s/divine-flower-7qb3d?file=/src/App.tsx:832-839)

Notice in your CSB you're importing `useForm` from `./src`, which is a local RHF package, which isn't the `7.25.1` version you've installed and importing the `useFieldArray` hook from.

<img width="474" alt="image" src="https://user-images.githubusercontent.com/16290753/151821443-71534908-d34c-472d-9121-433f4147c9ec.png">

**Comment by michalbundyra** [comment]
@Moshyfawn my bad, thanks for your help!

**Comment by Moshyfawn** [comment]
No problem! Ik I've got confused by [this particular CSB](https://codesandbox.io/s/eager-sun-jt4df) you've into the issue with.
Try using [this one](https://codesandbox.io/s/react-hook-form-v7-ts-template-4tn8i) instead. The one with the local copy of RHF is for debugging and PRs ;)
