### ISSUE TITLE
issue: the controlled input value update causes an infinite loop 

### ISSUE THREAD

**Issue by Moshyfawn** [react-hook-form/react-hook-form#7708]
### Version Number

7.19.0

### Codesandbox/Expo snack

https://codesandbox.io/s/pedantic-rhodes-wryr9?file=/src/App.tsx

### Steps to reproduce

1. Go to [this CSB](https://codesandbox.io/s/pedantic-rhodes-wryr9?file=/src/App.tsx)
---// START steps for a **working** select //---
2. Notice the installed RHF version is [`7.18.1`](https://github.com/react-hook-form/react-hook-form/releases?q=7.18.1&expanded=true)
```json
{
  "dependencies": {
    "react-hook-form": "7.18.1"
  }
}
```
3. Click on the **Color Set 2** select input
4. Select multiple different options
5. Click **Set** button
6. Notice the **Color Set 2** select value has been updated successfully
---// END steps for a **working** select //---
---// START steps for a **broken** select //---
7. Install RHF version [`7.19.0`](https://github.com/react-hook-form/react-hook-form/releases?q=7.19.0&expanded=true)
```json
{
  "dependencies": {
    "react-hook-form": "7.19.0"
  }
}
```
8. Refresh the app page
9. Click on the **Color Set 2** select input
10. Select multiple different options
9. _(**CAUTION**, infinite loop after this step)_ Click **Set** button
10. See the page starts to slow down _(infinite loop)_
---// END steps for a **broken** select //---

### Expected behaviour

The page doesn't slow down on select value change after RHF version [`7.19.0`](https://github.com/react-hook-form/react-hook-form/releases?q=7.19.0&expanded=true)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Context: #7706

**Comment by bluebill1049** [comment]
I believe this issue is due to @ionic value change detection. This issue can be reproduced without react-hook-form.

[@ionic](https://codesandbox.io/s/thirsty-pasteur-wqpuz?file=/src/App.tsx:137-143) As much as I want to provide a solution for this but rather difficult. I would kindly ask to rise an issue at iconic instead.

**Comment by aruljayaraj** [comment]
@bluebill1049 Sure will do that on the Ionic side. Thanks.
