### ISSUE TITLE
[Typescript] - formState.errors reports incorrect type with schema field array error

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#7711]
### Version Number

7.25.3

### Codesandbox/Expo snack

https://codesandbox.io/s/purple-http-nj7ob?file=/src/App.tsx

### Steps to reproduce

1. Go to the sandbox
2. Click on the trigger button
3. In the console notice the output
4. Hover over `formState.errors?.nested` on line 37 and notice that the type is incorrect compared to the output

### Expected behaviour

I believe this issue is because the types did not change after implementing #4356. 

`formState.errors?.someFieldArray` is showing the type in the old format where field arrays themselves could not contain error messages. Solving this is tricky because it means the type of a field array error could either be `FieldError` or the paths to the nested fields within its field errors. Doing a union of either option isn't the best user experience but would be a solution.

Another limitation here is the field array error overwrites the field errors within it. So for example in the sandbox there are two errors:

1. the field array must have a min length of 2
2. the nested field array field called name is required

It seems that because the field array error (1) is present, it overwrites access the nested error (2).

Originally I suggested it might be good to split the field array errors into a separate object within `formState` and leave `formState.errors` as is. This would be a breaking change and goes beyond the scope of this issue, but it might be worth considering in V8. 

![Screenshot from 2022-02-01 16-40-58](https://user-images.githubusercontent.com/36898266/152075999-b0f622ea-8ab7-43e4-bd6e-c717e4247600.png)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I am open to suggestions on how to resolve this, I don't think it's possible or I have an idea how to resolve this with runtime vs static TS type analysis. Field Array error array vs object is probably one of the most difficult and annoying things because an error could be at the group level, while the field array's data structure is set to be array-like.

**Comment by wdfinch** [comment]
Makes sense. I think the only way to handle it is to move the field array error into a separate object within `formState`. So something like:

```
formState.fieldArrayErrors = {
  fieldArrayName: {
    message: "nested field must have at least 2 items"
    type: "min"
    ref: undefined
  }
}
```

What do you think? We would leave `formState.errors` as it worked before the same type information.

**Comment by bluebill1049** [comment]
I don't have a good and clean solution at the moment (over the years), the above is not my preference at the moment.

**Comment by wdfinch** [comment]
If you want to keep it in the same object, another idea is to modify the type of the field array elements so they contain paths to children and the error message in an object. So something like the following. 

```
formState.error = {
  fieldArrayName: {
    error: {
    message: "nested field must have at least 2 items"
    type: "min"
    ref: undefined
    }
    paths: [{
      name: {
       message: "nested[0].name is a required field"
       type: "required"
       ref: undefined   
       }
    }]
  }
}

```

**Comment by bluebill1049** [comment]
Thanks for the suggestions above as well.

**Comment by wdfinch** [comment]
Ok, I think the most versatile solution is rather than each item be of type `FieldError`, we change it to something like this:

```typescript
type FieldErrorWrapper = {
    error: FieldError,
    paths: null | PathsToNestedFields
}

```

I like this since it handles both field array errors and nested object errors possibly down the road (not supported now).

So this would be a more complete example.

```typescript
const formState.error = {
  regularFieldName: {
    error: {
      message: "field cannot be empty",
      type: "required",
      ref: undefined,
    },
    paths: null
  },
  nestedObjectName: {
    error: {
      message: "object must contain 3 keys",
      type: "keys",
      ref: undefined,
    },
    paths: {
      nestedFieldOne: {
        error: {
          message: "field cannot be empty",
          type: "required",
          ref: undefined,
        },
        paths: null
      },
      nestedFieldTwo: {
        error: {
          message: "field cannot be empty",
          type: "required",
          ref: undefined,
        },
        paths: null
      },
    }
  },
  fieldArrayName: {
    error: {
      message: "nested field must have at least 2 items",
      type: "min",
      ref: undefined,
    },
    paths: [{
      name: {
        message: "nested[0].name is a required field",
        type: "required",
        ref: undefined,
      }
    }]
  }
}
```

**Comment by wdfinch** [comment]
Do you want to move this discussion to V8 or just leave it for now?

**Comment by bluebill1049** [comment]
I think close this for now, this is not part of v8 as well.

**Comment by bluebill1049** [comment]
could you change this issue to a feature request instead? let's ping this onto the feature board. Hopefully we have some solution from typescript site.

**Comment by wdfinch** [comment]
Ya, sure I'll take care of that later today.
