### ISSUE TITLE
issue: [handleSubmit] exposes internal errors references in `onInvalid` callback

### ISSUE THREAD

**Issue by tiii** [react-hook-form/react-hook-form#7717]
### Version Number

>= 7.13.0

### Codesandbox/Expo snack

https://codesandbox.io/s/hardcore-firefly-598rs

### Steps to reproduce

1. Go to https://codesandbox.io/s/hardcore-firefly-598rs
2. Click on submit button
2. Click on set custom error
4. See read-only error

### Expected behaviour

Freezing errors in `onInvalid` callback should not freeze internal errors object.

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```
-- Firefox:
 Uncaught (in promise) TypeError: "email" is read-only
    set index.esm.mjs:475
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tiii** [comment]
This is a related issue to #7703 but this time for `onInvalid` callback instead of the `onValid` callback.

**Comment by bluebill1049** [comment]
Hey @tiii Thanks for the PR, I hope we can skip on apply `object.freezon` and clone the errors object on what's returned on the invalid state and consider it as only readable data. Have you considered any workaround on the above issue?

**Comment by tiii** [comment]
I share your doubts about expanding the `cloneObject` function.

I implemented your shallow clone suggestion in the linked PR. As the `fieldError` are recreated on every validation this should solve the problem as well. Thanks for the suggestion!

I also marked the `errors` parameter on the `onInvalid` callback as Readonly. I don't think this is strictly necessary as it's not the internal reference anymore. Should we keep this? What do you think? If tho this might be a breaking change.

**Comment by bluebill1049** [comment]
I think we can keep it as it is for the `type` to avoid breaking change, but feel free to send a PR on the next major version: https://github.com/react-hook-form/react-hook-form/pull/5941 I think it makes sense to mark it as `readOnly` which I should do that from day one.

**Comment by tiii** [comment]
Alright, I hope I will remember to do that :wink:

What do you think about the `onValid` callback? I would say the `data` parameter should also be `readOnly` then.

**Comment by bluebill1049** [comment]
Yea, they should all be readOnly 👍 no pressure tho I will do that in v8 anyhow.
