### ISSUE TITLE
issue: After calling trigger(), the formState is not evaluated again if the form isn't submitted yet

### ISSUE THREAD

**Issue by pganster** [react-hook-form/react-hook-form#7722]
### Version Number

7.23.0

### Codesandbox/Expo snack

https://codesandbox.io/s/intelligent-kepler-f71yu?file=/src/App.tsx

### Steps to reproduce

1. Click on "Click me to trigger validation"
2. See that "Is Form Error" is now true
3. Type something into the input box
4. "Is Form Error" is still true

### Expected behaviour

When calling trigger(), I would expect the fields to behave the same ways as they do when the form is being submitted:
1. Click on "Send"
2. See that "Is Form Error" is now true
3. Type something into the input box
4. **"Is Form Error" is now false**

After calling trigger(), when the user fixes the validation error (i.e. types something into the input box), I expect the formState.errors to be re-evaluated and now have no errors anymore.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pganster** [comment]
I can confirm that this works for my case. However, if one doesn't want to incur the performance penalties that come along with using `onChange`, I ended up with the following solution:

Wrap the button click handler in a `handleSubmit`. This, of course, sets the formState to `isSubmitted`, but for my case, this is fine. [Codesandbox for this solution](https://codesandbox.io/s/lucid-bose-57yit?file=/src/App.tsx).

**Comment by Moshyfawn** [comment]
> if one doesn't want to incur the performance penalties that come along with using `onChange`

As soon as you "submit" the form by firing the `onClick` event with your `trigger` call wrapped in `handleSubmit`, given that your `reValidateMode: "onChange"`, the form's gonna start behaving **the same way** it would with `mode: "onChange"`, but you have a false `isSubmitted: true` flag.
I'd suggest to set `mode: onChange` instead
