### ISSUE TITLE
issue: isDirty isn't set if defaultValues contains a function

### ISSUE THREAD

**Issue by ryanmk54** [react-hook-form/react-hook-form#7723]
### Version Number

7.25.3

### Codesandbox/Expo snack

https://codesandbox.io/s/wild-https-9d45q?file=/src/App.tsx

### Steps to reproduce

1. Change the text field value
2. Notice the submit button is disabled because isDirty is false

### Expected behaviour

isDirty should be true

I'm guessing this was broken in [commit 6081c6c3d5a68497bda8dd373e2020c1f4cf949b](https://github.com/react-hook-form/react-hook-form/commit/6081c6c3d5a68497bda8dd373e2020c1f4cf949b#diff-dfdef7c059f38b3d4993e46d175f2d8827e84655cc6170a431190f8a63263f69)

Here is the [original discussion](https://github.com/react-hook-form/react-hook-form/discussions/7710#discussioncomment-2098582)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is expected, we are not going to clone anything that's function-based. If this is required behavior, you can consider upvoting this feature request.  https://github.com/react-hook-form/react-hook-form/issues/7279
