### ISSUE TITLE
Feature Request - Improve structure of formState.errors to accommodate field array errors

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#7742]
**Is your feature request related to a problem? Please describe.**
Yes. Feature #4356 added support for viewing schema field array errors within `formState.errors`. However the implementation has 2 problems:

1. The type information is incorrect when a field array error is present
2. **If** a field array error is present **and** errors are present on the fields within a field array, **then** only the field array error can be viewed. 

For example in a structure like
```typescript
interface FormValues {
  myFieldArray: {
    name: string
  }[]
}
```

If `myFieldArray` and `myFieldArray.{index}.name` both had errors, then only the error for `myFieldArray` could be viewed.

**Describe the solution you'd like**
I believe the best way to fix this is to modify the structure of `formState.errors` slightly so that rather than each item linking to a `FieldError` or path to nested fields, it links to a structure like this:

```typescript
type FieldErrorWrapper = {
    error: FieldError,
    paths: null | PathsToNestedFields
}
```

This would allow both field array roots and containers for nested fields to hold errors as well as show errors for their child fields.

An example would be as follows:

```typescript
const formState.error = {
  regularFieldName: {
    error: {
      message: "field cannot be empty",
      type: "required",
      ref: undefined,
    },
    paths: null
  },
  nestedObjectName: {
    error: {
      message: "object must contain 3 keys",
      type: "keys",
      ref: undefined,
    },
    paths: {
      nestedFieldOne: {
        error: {
          message: "field cannot be empty",
          type: "required",
          ref: undefined,
        },
        paths: null
      },
      nestedFieldTwo: {
        error: {
          message: "field cannot be empty",
          type: "required",
          ref: undefined,
        },
        paths: null
      },
    }
  },
  fieldArrayName: {
    error: {
      message: "nested field must have at least 2 items",
      type: "min",
      ref: undefined,
    },
    paths: [{
      name: {
        message: "nested[0].name is a required field",
        type: "required",
        ref: undefined,
      }
    }]
  }
}
```

**Describe alternatives you've considered**
Right now I'm manually casting the type of a field array error to `FieldError` in order to show it. 

**Additional context**

This sandbox shows the problem.
https://codesandbox.io/s/purple-http-nj7ob?file=/src/App.tsx

![Screenshot from 2022-02-01 16-40-58](https://user-images.githubusercontent.com/36898266/152385721-1fdf0a60-08e4-4b91-a03b-3f14f3887122.png)

**Comment by bluebill1049** [comment]
thanks for the detailed feature request.
