### ISSUE TITLE
can controller support undefined as defaultValue?

### ISSUE THREAD

**Issue by iamwelk** [react-hook-form/react-hook-form#775]
**Describe the bug**
My component accepts undefined and number, but when I use controller wrapped my componnet, it will set '' as default value which will report an error in my component

**Expected behavior**
Don't set '' as default value of controller

**Comment by bluebill1049** [comment]
where did you set your default value? from `useForm` or as `prop` at Controller

**Comment by iamwelk** [comment]
Controller's prop
