### ISSUE TITLE
issue: Nested controlled input doesn't re-render when using setValue

### ISSUE THREAD

**Issue by fknop** [react-hook-form/react-hook-form#7758]
### Version Number

7.26.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-object-controlled-not-updated-qx4e2?file=/src/index.js

### Steps to reproduce

1. Go to the codesandbox link
2. Click on 'Update' 
3. The "Object controlled field" nested value will not re-render in the UI (highlighted in red) although the watched value of that same field shows the proper value is being set 
4. Click "Update object controlled" and the nested value will re-render properly when using `setValue` on the nested field directly

### Expected behaviour

Calling `setValue` should re-render the nested controlled field correctly.
I'm not sure if this is expected behavior or not but it seems counter-intuitive as updating a nested controlled field works if that field is not an object.  Note that I also added nested controlled value inside an array and it updates properly as well.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
the `controller` only subscribes to the exact field name, if you want to watch nested value, use `useWatch`.

**Comment by Moshyfawn** [comment]
Notice you pass `nested.objectControlled` as a controlled input field name to your controlled component into the `useController` hook.
```js
 <NestedControlledField control={control} name="nested.objectControlled" />
```
The field you're updating with the `setValue` method is `nested`
```js
setValue("nested", {
  objectControlled: {
    nestedValue: "updated"
  }
});
```
which is not the field your controlled input is being subscribed to. Remember, you've passed `name="nested.objectControlled"` not `name="nested"`. Hence, your field controlled field value is not being updated / re-rendered.

**Comment by fknop** [comment]
Isn't it counter intuitive that it works with controllers inside arrays but not inside the root object?

**Comment by Moshyfawn** [comment]
[From RHF docs on `setValue`](https://react-hook-form.com/api/useform/setvalue#main):
> Important: use replace from useFieldArray instead, update entire field array with setValue will be removed in the next major version.

You shouldn't use setValue with field arrays as you can encounter unwated / weird behavior

**Comment by Moshyfawn** [comment]
So, the behavior is expect. In your case, you can
- set your controlled input name as `nested` to track the whole object
- use `setValue` with the exact or deeper nested field name
```js
setValue("nested.objectControlled", {
  nestedValue: "updated"
});
```
or
```js
setValue("nested.objectControlled.nestedValue", "updated");
```
See [this CSB](https://codesandbox.io/s/react-hook-form-object-controlled-not-updated-forked-40e1c?file=/src/index.js) for example

**Comment by Moshyfawn** [comment]
On the use of `setValue` for field arrays deprecation you can read more in #7433 RHF next version discussion

**Comment by fknop** [comment]
> [From RHF docs on `setValue`](https://react-hook-form.com/api/useform/setvalue#main):
> 
> > Important: use replace from useFieldArray instead, update entire field array with setValue will be removed in the next major version.
> 
> You shouldn't use `setValue` with field arrays as you can encounter unwanted / weird behavior

I updated the codesandbox to use update instead of setValue for the array, and added a nested property for the array as well.
Again, it works fine for nested properties inside arrays.
https://codesandbox.io/s/react-hook-form-object-controlled-not-updated-qx4e2?file=/src/index.js

**Comment by fknop** [comment]
> So, the **not working** behavior is expect. In your case, you can
> 
>     * set your controlled input name as `nested` to track the whole object
> 
>     * use `setValue` with the exact or deeper nested field name
> 
> 
> ```js
> setValue("nested.objectControlled", {
>   nestedValue: "updated"
> });
> ```
> 
> or
> 
> ```js
> setValue("nested.objectControlled.nestedValue", "updated");
> ```
> 
> See [this CSB](https://codesandbox.io/s/react-hook-form-object-controlled-not-updated-forked-40e1c?file=/src/index.js) for example

That's indeed what I ended up doing in our code.
But I think that there is a small inconsistency to how it is handled with nested values inside arrays.

**Comment by Moshyfawn** [comment]
Hm, it's an point interesting, tho.
From [the `useController` source code](https://github.com/react-hook-form/react-hook-form/blob/master/src/useController.ts#L53)
```js
function useController() {
  const isArrayField = isNameInFieldArray(control._names.array, name);
    const value = useWatch({
    exact: !isArrayField,
  })
}
```
So, that implies that for field arrays we're watching the whole array object and for an object field input we're subscribing to the exact field name value set. Is it correct, @bluebill1049? Is it a performance thing?

**Comment by bluebill1049** [comment]
@Moshyfawn that's a mistake, it should always be `exact`. I will patch this inconsistency.

**Comment by Moshyfawn** [comment]
> @Moshyfawn that's a mistake, it should always be `exact`. I will patch this inconsistency.

I guess, that answers your concern about the inconsistency in behavior between fields and fields array, @fknop

**Comment by bluebill1049** [comment]
thanks @Moshyfawn for looking into this issue.

**Comment by fknop** [comment]
Thank you for your quick response 😄 
If I understood correctly, updating nested values inside arrays will not re-render anymore after the patch, right?

**Comment by Moshyfawn** [comment]
> Thank you for your quick response 😄 If I understood correctly, updating nested values inside arrays will not re-render anymore after the patch, right?

Yep, you're correct
