### ISSUE TITLE
issue: errors object has an unnamed field when using zod

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [react-hook-form/react-hook-form#7761]
### Version Number

7.26.0

### Codesandbox/Expo snack

https://codesandbox.io/s/hookform-bug-t14kz?file=/src/App.tsx

### Steps to reproduce

1. Go to the CodeSandbox
2. Do not enter any field
3. Click `Submit`
4. Check the console, and the message next to the date input

### Expected behaviour

This error object should have a defined name (on the `errors` interface) or a way to access it without typescript complaining (`implicit any type`)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
You need to provide am error field path along with the error message when using `.refine()` to attach the error to. Without it it's default value is `""` _(empty string)_
```js
.refine((data) => data.dob || data.name, {
  message: "Please enter either field",
  path: ["name"]
});
```

**Comment by Moshyfawn** [comment]
Here's [a working CSB](https://codesandbox.io/s/hookform-bug-forked-0tuey?file=/src/App.tsx)

**Comment by AlvaroAquijeDiaz** [comment]
thanks, I'm looking at it and works, but my use case for `refine()` was to prevent the user from not sending any field, so how can I define an specific key like `noFieldsError` to display that error?

**Comment by Moshyfawn** [comment]
Atm RHF doesn't support global errors, so you need to append your error to either or both of the existing inputs to prevent TS from complaining.
If you're interested to see this in RHF, you can vote for it on the project dashboard #7661
To learn more on how to append your error to either or both of the related inputs, refer to[ the Zod docs section on how to customize error path](https://github.com/colinhacks/zod#customize-error-path)

**Comment by AlvaroAquijeDiaz** [comment]
Sure thanks anyway, this was quite helpful

**Comment by bluebill1049** [comment]
thanks @Moshyfawn 🙉
