### ISSUE TITLE
Typescript x Controlled components

### ISSUE THREAD

**Issue by ScreamZ** [react-hook-form/react-hook-form#777]
Hello,

I'm using Elastic UI, which is a great framework for back-offices. I starting being used to with react-forms-hook, but I still have some questions.

I'm just facing a controlled component which is `EuiSwitch`, a simple switch.

I succeed in doing such a thing now:

```tsx
  <Controller as={<EuiSwitch label="Actif ?" />} control={control} name="enabled" />
```
The thing is that now Typescript is yielding that there are some missing props on `EuiSwitch`.
Before I was doing a custom component with:

```tsx
import { EuiSwitch, EuiSwitchEvent } from "@elastic/eui";
import React, { useEffect, useState } from "react";
import { FormContextValues } from "react-hook-form";

interface Props {
  name: string;
  label: string;
  register: FormContextValues["register"];
  unregister: FormContextValues["unregister"];
  setValueFn: FormContextValues["setValue"];
  defaultChecked?: boolean;
}

export const Switch: React.FC<Props> = props => {
  const [checked, setInternalValue] = useState(props.defaultChecked ?? true);

  const onChange = (data: EuiSwitchEvent) => {
    props.setValueFn(props.name!, data.target.checked);
    setInternalValue(data.target.checked);
  };

  useEffect(() => {
    if (props.name) {
      props.register({ name: props.name });
      props.setValueFn(props.name!, props.defaultChecked);
    }

    return () => props.unregister(props.name);
  }, [props.name, props.defaultChecked]);

  return (
    <EuiSwitch
      name={props.name}
      defaultChecked={props.defaultChecked}
      label={props.label}
      checked={checked}
      onChange={onChange}
    />
  );
};
```

I the second case, nothing is yielding, because I'm filling props.
I could have also used `FormContext`

## Question
Do you think we could maybe find another pattern that would make this work without warning (currently I'm just doing a `@ts-ignore`)

I guess we could pass a `React.FunctionComponent<EuiSwitchProps>` instead of a `JSX.Element` and imagine some kind of genericity using things described here: https://github.com/typescript-cheatsheets/react-typescript-cheatsheet/blob/master/ADVANCED.md

create another prop which allows passing some of the props, as optional

```tsx
<Controller<Partial<EuiSwitchProps>>
  as={EuiSwitch}
  withProps={label: "Actif?"}
  name="test"
/>
```

Kind of thing? What do you thing about that?

**Comment by bluebill1049** [comment]
Can i have a screenshot of the type error? I think @JeromeDeLeon made a PR for it: https://github.com/react-hook-form/react-hook-form/pull/771

**Comment by JeromeDeLeon** [comment]
@bluebill1049 was right. Handling rest props  is my problem as I described it on the PR I made.

Regarding your concern about handling types of the `CustomComponent` that will be passed on the `Controller` like what you did above, I tried to find a workaround but drop it down because of insufficient knowledge of TS before. You can raise a PR if you want and we'll take a look at it.

Right now, if you pass your custom component to the `Controller` like `as={CustomComponent}` then all props from `CustomComponent` will be lost.

**Comment by ScreamZ** [comment]
I think there is some confusion about the controller and how to use it.
I'll try to fork and do something but I'm having hard type coding it ^^.

What I'm currently trying to do is:
1. Instead of exposing a `control` property from `useForm`
2. Expose a `Controller` argument, this could allow typing the `name` props to only match keys form field keys.

Then we have two solutions.

## First solution, the current one
use `as` and some other props like `valueName`, etc but it gets a bit tricky as you don't exactly know when this is a props from the inner component or not.

## Second solution

Using children prop, i'll make a PR

**Comment by ScreamZ** [comment]
Due to other related threads, this is not required and it's about typescript only. I'll close
