### ISSUE TITLE
Ability to re-scope a form object to a sub-section of a form

### ISSUE THREAD

**Issue by samboylett** [react-hook-form/react-hook-form#7771]
**Is your feature request related to a problem? Please describe.**
I would like sub form components to be agnostic of the surrounding form

**Describe the solution you'd like**
The ability to take the output of `useForm` hook and scope it to a certain field path.

**Describe alternatives you've considered**
-

**Additional context**
I'm effectively looking for a hook with the following API:

```typescript
import { FieldPath, UseFormReturn } from "react-hook-form";

const useFormScope = <
  FValues extends Record<string, any>,
  FPath extends FieldPath<FValues>
>(
  form: UseFormReturn<FValues>,
  path: FPath
): UseFormReturn<FValues[FPath]>;
```

I have tried to right my own hook that does this, but i'm not 100% on how it works internally (some preliminary testing did show it working).

You would use it like:

```typescript
const form = useForm(...args);

const scopedForm = useFormScope(form, 'path');
```

Cheers

**Comment by bluebill1049** [comment]
please take a look at this RFC: https://github.com/react-hook-form/react-hook-form/discussions/7354 see if this is what you after.

**Comment by samboylett** [comment]
It looks similar and i believe it is trying to solve the same issue. However I am using controlled components with useController so need access to the control object. The hook interface I've tried above could work for both controlled and uncontrolled components, plus would prevent the sub forms (in that case AddressFields) needing to be aware it's a sub component.

**Comment by bluebill1049** [comment]
I am pretty sure it will solve the controller as well. cc @felixschorer

**Comment by bluebill1049** [comment]
> The hook interface I've tried above could work for both controlled and uncontrolled components

would you like to share your solution?

**Comment by bluebill1049** [comment]
Thanks @felixschorer going to close this and improve it on V8.
