### ISSUE TITLE
issue: NestedValue with field array data

### ISSUE THREAD

**Issue by hpersson** [react-hook-form/react-hook-form#7772]
### Version Number

7.4.1

### Codesandbox/Expo snack

https://codesandbox.io/s/suspicious-river-ceinx?file=/src/App.tsx

### Steps to reproduce

1) Create form data that has an array of objects that utilize `NestedValue`
2) call "append", "insert", "remove", etc from useFieldArray hook passing an object that matches the type inside NestedValue
3) observe TypeScript error:
```
Type 'Foo' is not assignable to type 'NestedValue<Foo>'.
  Property '[$NestedValue]' is missing in type 'Foo' but required in type '{ [$NestedValue]: never; }'.ts(2322)
```

### Expected behaviour

I can call append, insert, remove, etc without type errors

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Type 'Foo' is not assignable to type 'NestedValue<Foo>'.
  Property '[$NestedValue]' is missing in type 'Foo' but required in type '{ [$NestedValue]: never; }'.ts(2322)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thank you very much for the issue and even supplied with a PR. 🙏
