### ISSUE TITLE
Get event type in the resolver function

### ISSUE THREAD

**Issue by Pixelatedza** [react-hook-form/react-hook-form#7775]
I would like the ability to know whether the resolver was triggered for a `change` or a `submit` event.

Unless I'm missing something obvious I didn't see a way to differentiate the calls.

**Describe the solution you'd like**
Add this to the `options` object that is passed to the resolver.

**Describe alternatives you've considered**
Handling the validation life cycle outside of react hook forms, but this just removes on of the benefits of using react hook forms.

**Additional context**
The reason, I want to show notifications when there are errors for `onSubmit` but not `onChange`.

**Comment by Moshyfawn** [comment]
What's preventing you from using the submit error handler handler instead? It's gonna be called on a failed submit only
```js
const onError = (errors) => console.error(errors)

<form onSubmit={handleSubmit(onSubmit, onError)}></form>
```
See [this example](https://codesandbox.io/s/runtime-http-wj2gl?file=/src/App.tsx:679-685)

**Comment by bluebill1049** [comment]
Yea, I think to diff `onSubmit` or `onChange`, should be at the form level or the other. we are happy to put it on the waiting for upvote list but this is unlikely to be implemented.

**Comment by Pixelatedza** [comment]
> What's preventing you from using **the submit error handler handler** instead? It's gonna be called on a failed submit only
> 
> ```js
> const onError = (errors) => console.error(errors)
> 
> <form onSubmit={handleSubmit(onSubmit, onError)}></form>
> ```
> 
> See [this example](https://codesandbox.io/s/runtime-http-wj2gl?file=/src/App.tsx:679-685)

Absolutely nothing. I somehow completely forgot that was a thing and feel a bit daft now.

In which case I agree with bluebill1049. Not something the validation process should be concerned with.

**Comment by Moshyfawn** [comment]
Ahaha, that's alright! I'm glad you the solution you need ;)
