### ISSUE TITLE
issue: Disabled option not accepted in controller rules nor register rules using Typescript

### ISSUE THREAD

**Issue by GoudekettingRM** [react-hook-form/react-hook-form#7779]
### Version Number

7.26.1

### Codesandbox/Expo snack

https://codesandbox.io/s/old-snow-4qfx0?file=/src/App.tsx & https://codesandbox.io/s/optimistic-visvesvaraya-j3jm5

### Steps to reproduce

1. Go to either of the code sandbox links
2. Wait for it to initialize / install / get ready
3. See the typescript error for `disabled: true` in the controller [rules props](https://codesandbox.io/s/old-snow-4qfx0?file=/src/App.tsx) and the [register method](https://codesandbox.io/s/optimistic-visvesvaraya-j3jm5).

### Expected behaviour

It should allow the disabled option as per the docs

![Screenshot 2022-02-09 at 09 21 54](https://user-images.githubusercontent.com/56813989/153154722-9df34ebe-c264-4b86-9a69-e634326789e5.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we do not support disabled prop for the controller. https://react-hook-form.com/api/usecontroller

**Comment by GoudekettingRM** [comment]
But it also happens in the register function.. https://codesandbox.io/s/optimistic-visvesvaraya-j3jm5

Good to know though, I thought I read that it accepts everything the register method accepts.

**Comment by bluebill1049** [comment]
please use the latest version, this `prop` was introduced in the later version.

**Comment by GoudekettingRM** [comment]
My bad, I thought codesandbox used the latest version... Sorry to waste your time -_- 

Thanks for the quick reply though!

**Comment by bluebill1049** [comment]
no worries at all.
