### ISSUE TITLE
Trigger validation on a filed based on another filed change.

### ISSUE THREAD

**Issue by Shaker-Hamdi** [react-hook-form/react-hook-form#778]
Hello, I have a question.
I'm migrating from Formik to "RHF", however, I don't know how to do the following with "RHF" ...

I want to trigger the validation on the "old_password" if the user starts typing inside the "password" field.

I know you guys have this method "triggerValidation" but I'm not quite sure how to utilize it in this scenario.

Any help would be highly appreciated.

Here's a Sandbox link on my Formik version ...

**Codesandbox link**
https://codesandbox.io/s/yup-conditional-validation-with-formik-sq7fq

**Comment by bluebill1049** [comment]
it's actually really simple, two API to use
```
register({
  validate: (value) => {
    return value === getValues()['valueB'];
  }}
)
```

**Comment by bluebill1049** [comment]
going to close this issue now, feel free to ask more question too :)

**Comment by Shaker-Hamdi** [comment]
@bluebill1049 I really appreciate your prompt response, really nice job maintaining this library :)
I just didn't know how to implement your solution using a custom input component with Typescript, so I created a Codesandbox so that you can take a look at the exact scenario I'm after ...

https://codesandbox.io/s/adoring-oskar-pllqf

**Comment by bluebill1049** [comment]
> In the example above, I didn't know where exactly to implement
> 
> ```
> ref={register({
>   validate: (value) => {
>     return value === getValues()['valueB'];
>   }}
> ```
> 
> Should I do it inside the custom input component? and if yes, will I need to pass down the "getValues()" method to the custom component or what should I do?

at the moment, you will have to pass down `getValues` method, or use FormContext

**Comment by zeckdude** [comment]
@bluebill1049 I am trying to define a custom validation for one field based on the value of another field, but I am using the `register()` method outside of the render method. For some reason, I am not seeing the console log I added in there though.

```js
register({
    name: 'numStickersOrdered',
    validate: value => {
      console.log('here');
      return value === '' && areStickersOrdered;
    },
  });
```

How can I get that to work? And how do I define the error message in this case?

**Comment by bluebill1049** [comment]
> @bluebill1049 I am trying to define a custom validation for one field based on the value of another field, but I am using the `register()` method outside of the render method. For some reason, I am not seeing the console log I added in there though.
> 
> ```js
> register({
>     name: 'numStickersOrdered',
>     validate: value => {
>       console.log('here');
>       return value === '' && areStickersOrdered;
>     },
>   });
> ```
> 
> How can I get that to work? And how do I define the error message in this case?

Are u using setValue with validation? 

SetValue(name, error, true)

If the validate method return a string, it will be the error message.

**Comment by bluebill1049** [comment]
> @bluebill1049 I am trying to define a custom validation for one field based on the value of another field, but I am using the `register()` method outside of the render method. For some reason, I am not seeing the console log I added in there though.
> 
> ```js
> register({
>     name: 'numStickersOrdered',
>     validate: value => {
>       console.log('here');
>       return value === '' && areStickersOrdered;
>     },
>   });
> ```
> 
> How can I get that to work? And how do I define the error message in this case?

Have a read at register on the website too

**Comment by zeckdude** [comment]
Thanks @bluebill1049! I got this to work:

```js
register(
    {
      name: 'numStickersOrdered',
    },
    {
      validate: value => {
        if (value === '' && areStickersOrdered) {
          return 'Specify how many stickers';
        }
      },
    },
  );
```

**Comment by bluebill1049** [comment]
> Thanks @bluebill1049! I got this to work:
> 
> ```js
> register(
>     {
>       name: 'numStickersOrdered',
>     },
>     {
>       validate: value => {
>         if (value === '' && areStickersOrdered) {
>           return 'Specify how many stickers';
>         }
>       },
>     },
>   );
> ```

short syntax `register('test', { required: true })`:)

**Comment by AjithkumarJM** [comment]
Hey, I need this same case to work out in controller,
so I have a start date and end date fields.

Depends on the start date, the end date should be validated.
The start date should be greater than the end date this is the case!

It works fine when I initially fill the start date and end date. 
but the validation is not triggering when I again change the start date less than the end date.

**Comment by bluebill1049** [comment]
can you share a simple codesandbox @AjithkumarJM ?

**Comment by aimanptz** [comment]
@AjithkumarJM Have the same problem. I've just just added 'triggerValidation()' into the controller's 'onChange' handler manually - that helped. 
![image](https://user-images.githubusercontent.com/36487126/90476262-d6b42a00-e131-11ea-96d9-cbfda62fc36b.png)


!But providing the 'watch(startDate)' or 'getValues().startDate' into the 'validate' option does not trigger the validation of the endDateField
![image](https://user-images.githubusercontent.com/36487126/90476378-14b14e00-e132-11ea-8361-5041f1eaedfb.png)

**Comment by AjithkumarJM** [comment]
Hey @aimanptz Actually I resolved it, For your reference! Hope it helps!

My Validation Part:

```
 {
    required: true,
    validate: {
      mustNotLessThanCurrentDate: (value: string) => isLessThanCurrentDate(value) || "Must be current date or higher",
      mustBeGreaterThanStartDate: (value: string) => (+new Date(value) >= +new Date(getValues()["startDate"] ?? new Date()).setHours(0,0,0,0)) || "Must be same or greater than from date",
    },
  }
```

My Controller

```
<Controller
          onClose={() => watchValue?.endDate && triggerValidation("endDate")}
          onBlur={() =>  watchValue?.endDate && triggerValidation("endDate")}
          as={DateField}    
          value={watchValue?.startDate}
          label="From"
          control={control}
        />
```

**Comment by AjithkumarJM** [comment]
Hey @aimanptz just try calling like this `getValues()["startDate"]`

**Comment by bluebill1049** [comment]
which version you are running?

**Comment by AjithkumarJM** [comment]
@bluebill1049 `^5.7.0`

**Comment by bluebill1049** [comment]
Thanks @AjithkumarJM `getValues` is correct instead of `watch`

**Comment by mercteil** [comment]
I have the following issue:

I have a select field where you can choose a country:
```javascript
<Controller
  as={SelectField}
  control={control}
  name="countryId"
  placeholder={t('select-country')}
  options={countriesOptions}
  error={errors.countryId || ''}
/>
```

And an async validated field where the form validates the company's vatId but depends on the value within the SelectField:
```javascript
const selectedCountryId = getValues('countryId');

<InputField
  name="vatId"
  register={register({
    validate: async (vatId) => {
      const { error, message } = await validateVat(selectedCountryId)(vatId);
      return (error && t(message)) || true;
    },
  })}
  placeholder={t('vat-number')}
  error={errors?.vatId?.message || ''}
/>
```

I have the following cases:

1. Customer enters VAT-ID => validates via API => countryId not selected = error 
2. Customer enters VAT-ID => validates via API => countryId selected and matches = success
3. Customer **changes** VAT-ID selection/field => ... ?revalidation?

How can I force to revalidate my "vatId" input whenever the selected field/value changes?

**Comment by mercteil** [comment]
Got it running with:

```javascript
  // effect watching on countryId
  useEffect(() => {
    ...
    trigger('vatId'); // retriggers validation
  }, [watch('countryId')]);

 // turned my select field back into a controlled one
 <SelectField
  name="countryId"
  placeholder={t('select-country')}
  onChange={({ value }) => setValue('countryId', value)}
  value={watch('countryId', user.countryId)}
  options={countriesOptions} 
 />

```
