### ISSUE TITLE
move onSubmit/onInvalid from handleSubmit into UseFormProps

### ISSUE THREAD

**Issue by pamapa** [react-hook-form/react-hook-form#7791]
**Is your feature request related to a problem? Please describe.**
Allow to simply reuse handleSubmit, without passing every time onSubmit. Specifically when using huge froms, which are split into multiple files, would make it easier to consistently use submit. E.g. when not directly using a submit button, but TypeScript code like `onChange={() => {console.log("do something and auto submit"); handleSubmit(onSubmit); }}` In that case the `onSubmit` must be passed all the way down via props or a custom provider context needs to be implemented, which wraps the `onSubmit` with a `React.useCallback`, thus makes things more complex... .

**Describe the solution you'd like**
Extending `UseFormProps` with:
```
onSubmit: (values: UnpackNestedValue<TFieldValues>, actions: UseFormExtendedReturn<TFieldValues, TContext>) => any | Promise<any>;
onInvalid?: (errors: FieldErrors<TFieldValues>, actions: UseFormExtendedReturn<TFieldValues, TContext>) => any | Promise<any>;
```

In the `handleSubmit` drop the parameters `onValid` and `onInvalid` and make use of the above ones like `resolver` is already accessed:
```ts
// old
await onValid(fieldValues, e);
// ...
if (onInvalid) {
  await onInvalid({ ..._formState.errors }, e);
}

// new
await _options.onSubmit(fieldValues, e);
// ...
if (_options.onInvalid) {
  await _options.onInvalid({ ..._formState.errors }, e);
}
```

The usage is then:
```ts
function App() {
  const { register, handleSubmit } = useForm({
    onSubmit: (data) => console.log(data),
  });

  return (
    <form onSubmit={handleSubmit()}>
    ...
    </form>
  );
}
```

Additionally it may makes sense to rename `onInvalid` to `onError`.

**Comment by bluebill1049** [comment]
Thanks for the feature request, moving to the project board, and waiting for upvotes.
