### ISSUE TITLE
issue: `state.errors` does not update

### ISSUE THREAD

**Issue by Ploppy3** [react-hook-form/react-hook-form#7817]
### Version Number

7.26.1

### Codesandbox/Expo snack

https://codesandbox.io/s/gifted-leaf-mlzhp

### Steps to reproduce

1. Submit form

### Expected behaviour

The `effect` should execute and log the new error into the console.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ploppy3** [comment]
I would like to run code based on the errors generated by RHF. But the `errors` object seem to be mutated.

**Comment by Moshyfawn** [comment]
If you're seeking to execute validation on field value update, you should consider setting form's validation mode to `onChange`
```js
useForm({ mode: "onChange" })
```
[For more info, see RHF `useForm` docs ](https://react-hook-form.com/api/useform)

**Comment by Moshyfawn** [comment]
> That's not what I want. I want to run code based on the errors generated by RHF on submit. Though, the `errors` state does not update as you can see in the demo.

You can either use the `onError` callback
```jsx
const { handleSubmit } = useForm()

const onError = err => console.log(err)

return <form onSubmit={handleSubmit(onSubmit, onError)}></form>
```
or watch the `isSubmitted` to execute your error handler
```jsx
const { formState } = useForm()
const { isSubmitted, errors } = formState

useEffect(() => {
  if (isSubmitted) {
    console.log(errors)
  }
}, [isSubmitted, errors])
```

In regards to `errors` state update not executing a side-effect, let's see what @bluebill1049 has to say about it

**Comment by bluebill1049** [comment]
please refer the doc: https://react-hook-form.com/api/useform/formstate

> This object contains information about the form state. If you want to subscribe to formState via useEffect, make sure that you place the entire formState in the optional array.

there is a video which I explain in detail, we are batching `formState` update.

**Comment by Moshyfawn** [comment]
> please refer to the doc: https://react-hook-form.com/api/useform/formstate
> 
> > This object contains information about the form state. If you want to subscribe to formState via useEffect, make sure that you place the entire formState in the optional array.
> 
> there is a video which I explain in detail, we are batching `formState` update.

![the-more-you-know](https://user-images.githubusercontent.com/16290753/153855640-a0c2fa2a-404d-4854-be28-80e3251e7a52.gif)

**Comment by bluebill1049** [comment]
you probably need to use a `deepEqual` `useEffect` for the current design.

**Comment by Ploppy3** [comment]
@bluebill1049 Alright, I think you can close the issue.

If I have more questions related to this, can I ask them here?

**Comment by bluebill1049** [comment]
yes, you can or would you like to send a GitHub discussion question instead?
