### ISSUE TITLE
issue: 

### ISSUE THREAD

**Issue by NarenderSiri** [react-hook-form/react-hook-form#7819]
### Version Number

V7

### Codesandbox/Expo snack

https://codesandbox.io/s/reacthookforms-pr4qb?file=/src/Form.js

### Expected behaviour

Hi,

I want to update only single  Array with total fields. but below code is not working please check ones. 
 setValue(`uoms[${rowIndex}]`, value);
In value we have total field Array values.

Thanks&Regards,
Narender

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848
