### ISSUE TITLE
Inconsistency useFieldArray's update

### ISSUE THREAD

**Issue by matamatanot** [react-hook-form/react-hook-form#7820]
### Version Number

7.27.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-update-rs9bj

### Steps to reproduce

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-update-rs9bj
2. Click on 'Set Random Age'. FirstName(bill) will not change, only Age will change.
3. Click on 'Append' and 'Set Random Age'. The FirstName will change to ''(empty) and the Age will also change.

### Expected behaviour

https://react-hook-form.com/api/usefieldarray

> When you append, prepend, insert and update the field array, the obj can't be empty object rather need to supply all your input's defaultValues.

`node_modules/react-hook-form/dist/types/fieldArray.d.ts`
> `const update: (index: number, value: Partial<FormItem>) => void`

I'm confused by the documentation and type definitions. Since it was Partial, I assumed that if I passed some parameters, the other parts would be kept as they were. In this case, I think that `firstName: matamatanot` will be retained and only age will change.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks, the type definition is incorrect. it shouldn't have been `Partial` in the first place.

**Comment by matamatanot** [comment]
@bluebill1049 
Thank you for replying quickly. 

It's a bit more complicated in a my real application, but is it safe to use the value of `fields` like this?

```
update(index, {
  firstName: item.firstName,
  age: Math.floor(Math.random() * 101)
})
```

**Comment by bluebill1049** [comment]
@matamatanot it's better use `getValues()` API, in case the item data is staled.
