### ISSUE TITLE
minLength / min rules not taken into account on controlled input

### ISSUE THREAD

**Issue by Tbaut** [react-hook-form/react-hook-form#783]
First of all, thank you so much for this library, love it, and I'm not 100% sure whether I'm using it wrong of if that's a bug.

**Describe the bug**
With a controlled input, the "required" is taken into account but "min" or "minLength" aren't. 

**To Reproduce**
Codesandbox: https://codesandbox.io/s/react-hook-form-defaultvalues-0y3wu
My code is available at: https://github.com/paritytech/polkassembly/commit/48f13a12e0d8b3dda3f35af983456ce95c33a27f#diff-c8fae73adf478f3b7e78993abdac2174R70

**Expected behavior**
When I type more than 3 letters, with a `rules={{required: true, minLength: 3}}` the validation should pass.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 71

**Additional context**
Also on the same line mentioned, I get a type error on `errors.username.type`:
>Property 'type' does not exist on type 'FieldError | NestDataObject<any> | NestDataObject<any>[]'.
  Property 'type' does not exist on type 'NestDataObject<any>[]'.ts(2339)

**Comment by stephoune** [comment]
Hi !
See : https://codesandbox.io/s/react-hook-form-defaultvalues-qsk91
You had multiple registerName (username, firstname, firstName) in your file for one same Field. Also, you was trying to set values from field manually. But with the Controller component, you don't have to. Is that what you wanted to do?

**Comment by Tbaut** [comment]
Thanks for the quick answer. One thing that I don't understand, is why using a custom handler makes `react-hook-form` to fail: https://codesandbox.io/s/react-hook-form-defaultvalues-0y3wu

Here my `onUsernameChange` is fire correctly at every key stroke, but for some reason, the validation fails with "required".

**Comment by stephoune** [comment]
You have to return something from your onUsernameChange function. 
Like this : https://codesandbox.io/s/react-hook-form-defaultvalues-e3b9f

**Comment by Tbaut** [comment]
ah totally forgot that. Thanks a lot.

**Comment by bluebill1049** [comment]
thank you very much for helping @stephoune ❤️
