### ISSUE TITLE
issue: Using dot syntax for array value adds false for unchecked values

### ISSUE THREAD

**Issue by lukevella** [react-hook-form/react-hook-form#7834]
### Version Number

7.27.0

### Codesandbox/Expo snack

https://codesandbox.io/s/optimistic-goldstine-gigwvp?file=/src/App.tsx

### Steps to reproduce

The codesandbox includes a form with two sets of checkboxes. One of them is registering the checkboxes using the dot notation.

1. Select a checkbox from the good checkboxes.
2. Select a checkbox from the bad checkboxes.
3. Note that the values returned are different. The bad checkboxes have `false` for all the unchecked checkboxes.

### Expected behaviour

Unchecking a checkbox from a group should remove the value from the array rather than setting it to `false`.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
I'm gonna take a guess here, 'cuz @bluebill1049 is the one who's gonna know it 100%, but `fieldName.{number}` is reserved for handling field arrays and RHF doesn't support flat arrays, so, what you're doing mapping the checkboxes with dot notation using index won't cut it by RHF design.

From [the RHF docs `register` section ](https://react-hook-form.com/api/useform/register)
> To produce an array of fields, input names should be followed by a dot and number. For example: test.0.data

**Comment by lukevella** [comment]
@Moshyfawn Thanks for the reply. Perhaps this is a user error but the issue I have is that my form can dynamically a number of checkboxes. If I register the checkbox using only the name ex:

```jsx
<input type="checkbox"  value="my value" {...register("checkboxes")} />
```

Then in the event of having only one checkbox, my form state will be set to:

```js
{ checkboxes: "my value" }
```

This is why I figured using the dot notation would be a good way to "force" an array value. Is there some other way?

**Comment by bluebill1049** [comment]
the uncontrolled checkbox only supports the field with the same name which is following the web standard, if you would like to use dot syntax and manage your own, please consider building into a controlled component and wrapped with `Controller` or `useController` hook.

**Comment by lukevella** [comment]
Thanks @bluebill1049. I understand that perhaps dot notation is not what is required here. I'm just wondering what your thoughts are about the use case where you have a checkbox group that potentially only has a single checkbox. From my point of view this is a valid use case that is not covered by RFC. The only options that are currently available are to either:

a) Implement your own logic using Controller/useController – This requires considerable effort replicating functionality that is already inside RFC to handle a single edge case.

b) Add an invisible checkbox so that there is always at least two checkboxes being registered which tells RFC to format values in an array – Easy but hacky.

Perhaps an option could be added to `register()` that could tell it to format values in an array, similar to the `valueAsNumber` and `valueAsDate` options. Maybe there can be `valueAsArray`?

**Comment by bluebill1049** [comment]
Thanks for the feedback. which `RFC` are you referring to? at this stage, we don't have any plan to add more config to `register` API.

**Comment by Moshyfawn** [comment]
> Maybe there can be `valueAsArray`?

`valueAsNumber`, `valueAsDate` are [the Web standard](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement) API and RHF has opted in to support those. `valueAsArray` doesn't seem fit this category.
> you have a checkbox group that potentially only has a single checkbox

This does seem like an uncommon edge-case that should be handled at the app level, IMO. If an input group has 1 checkbox, it's not a group of choices but rather a single `true` / `false` and doesn't make a lot of sense UX-wise as a group. But knowing that your checkbox group is intended to be a group _(list)_ of values, you can always format your checkbox group value to an array regardless.

At the end of the day, RHF tries to embrace the Web standards more than add any additional features that go against it.

**Comment by lukevella** [comment]
> which RFC are you referring to

Sorry I meant to type RHF.

> we don't have any plan to add more config to register API

Ok that's fair.

> At the end of the day, RHF tries to embrace the Web standards more than add any additional features that go against it.

I can respect that. I can see that having a single checkbox in a group is not something that is covered by this. Thanks for your help.
