### ISSUE TITLE
I want the `formState: { errors }` which can not only get errors when submit but also in other time

### ISSUE THREAD

**Issue by SnowingFox** [react-hook-form/react-hook-form#7838]
**Is your feature request related to a problem? Please describe.**
I found that i only can get `errors` when user submit the form, it give me some troubles that I cannot show the form errors in real-time display

**Describe the solution you'd like**
I think i can do it like this
```js
const { control, formState: { errors } } = useForm()
const watchForm = useWatch({ control, name: ["studentId", "password"] })

useEffect(() => {
    Object.keys(errors).forEeach((key) => {
        console.log(`This filed #${key} is wrong`)
    })
}, [watchForm])
```

**Describe alternatives you've considered**
No alternatives

**Additional context**
I just want to get erros in any time

**Comment by Moshyfawn** [comment]
Please, refer to [the RHF docs section on `useForm`](https://react-hook-form.com/api/useform).
You can set the validation mode to `onChange` to achieve the behavior you want
```js
useForm({
  mode: "onChange"
})
```

**Comment by Moshyfawn** [comment]
No worries, you can find [React Hook Form documentation in Chinese](https://react-hook-form.com/zh/get-started) as well
