### ISSUE TITLE
Pass the mode / event that caused resolver / input level validation to be triggered.

### ISSUE THREAD

**Issue by jhicken** [react-hook-form/react-hook-form#7839]
**Is your feature request related to a problem? Please describe.**
When I am using a resolver on `useForm` I would like to be able to only do a specific type of validation when my mode is `onSubmit`. I peeked at https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/createFormControl.ts#L382 Looks like it may not be super simple. I think something like everything that calls `_executeSchema` might need to pass along the mode string that triggered them. Or you could do something like add it to a state variable and pass that along. Or maybe implement an internal eventing system. 🤷 

Some thing like this would be nice though.

```
  useForm({
    mode:'all',
    context: "context",
    resolver: async (values, context, options) => {
      if (options.mode === 'onSubmit') {
        return {
          values: {},
          errors: await checkDuplicateNames(values)
        };
      }
      if (options.mode === 'onBlur') {
        return {
          values: {},
          errors: await validateInputs(values)
        };
      }
    }
  })
```

I might also be nice to have this on the field level as ... like a register option.
`{...register("firstName", { mode: 'onSubmit', minLength: 3 })}` or
`{...register("firstName", { validate: async(value, mode)=>(mode === 'onSubmit' ? checkForDuplicateName(value) : '') })}`

**Describe alternatives you've considered**
I could invoke 2 separate useForms that track the same form fields but this seems bad and yucky and such.

**Comment by jhicken** [comment]
There are a few options on the useForm api side of this aswell. Like you could pass an array of modes and an array of resolvers and use them internally by index. Or you could also pass an array of options objects to to useForm with each having its own mode and resolver.

The main thing I want to achieve is having string validation onBlur and server side duplicate name checking onSubmit.

**Comment by bluebill1049** [comment]
thanks for the feature request. going to put to the project board, curious why not just leverage the `mode` from `useForm`?

**Comment by jhicken** [comment]
`curious why not just leverage the mode from useForm?`

I think you asking why not just use `mode:'onSubmit'`? If not just correct me.  But the reason 'why not' is that, I want to perform a server side validation from the 'onSubmit' which may be a little slow on a few fields and the rest of the fields I want to have `onChange` validation so the user get quick feedback. 

I mean there are other solutions like I could debounce the serverside validation with some sort of promise cancelation. but... I think that would be a bit ugly in my code. I would look a lot cleaner to only run the specific type of validation that I need to when I need to.

Does that make sense or did I answer the wrong thing?

**Comment by bluebill1049** [comment]
Make sense, thanks for the additional information. I guess if we can expose the mode inside the resolver would solve your problem here.

**Comment by jhicken** [comment]
Yeah that would solve my particular problem. 

The other thing I was mentioning was that might be helpful at the field level as well. But that is not a must for me. I am okay doing all my validation in the resolver.

**Comment by bluebill1049** [comment]
I think at the field level would be easier to use `trigger` instead of having more `mode` related work.
