### ISSUE TITLE
issue: Controller is not working in production ReactNative v0.59

### ISSUE THREAD

**Issue by sajcics** [react-hook-form/react-hook-form#7842]
### Version Number

7.27.0

### Codesandbox/Expo snack

https://codesandbox.io/s/tender-jennings-6x7qfc?file=/src/CusomComponent.js

### Steps to reproduce

The component is used in React Native v0.59, and in production/release mode Controller is not working, but in development/debug mode is working perfectly. Even when I remove rule definition for Controller, submit button is never triggered! 
1. Go to input field and put values
2. Click on button to submit
3. In sandbox, you will see that values are submitted correctly, but in release mode I never can get to success callback of handleSubmit method.

### Expected behaviour

I am expecting of Controller component to work the same in production as it works in debug mode. 

### Relevant log output

```shell
None.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
There is a lot of things that could lead to such an issue. 

- prop assignment (component prop miss)
- other side effects in your form

If you could provide a solid example to reproduce of why it's problem or a unit test to showcase the error, there is very little we can do here.

**Comment by bluebill1049** [comment]
happy to look into it once the above requirement is fulfilled.

**Comment by sajcics** [comment]
@bluebill1049 Hi, thank you for fast feedback. I am not sure what do you mean by prop assignment? The Controller is not wrapped by form, instead I have button that will trigger to submit data with axios to backend.

**Comment by Moshyfawn** [comment]
Please, consider creating an isolated reproduction example instead. While your info is valuable, we can't know what went wrong in your particular use-case.

**Comment by sajcics** [comment]
Hi, here is a example of logic that I have currently in my app [codeExample](https://codesandbox.io/s/jovial-frost-4wg7pn?file=/src/Form.js). Because codesandbox is little bit buggy for react native, at least you can see how the logic is created and to see if the Controller is correctly created. It's really strange that for me on iOS and Android in a debug mode a form works perfectly, but when I test the same code in release it's not working. A handleSubmit function is not undefined (so this is not a problem), so it's really strange that when clicking to button a button is not triggering even when errors variable is empty object.Also, value to notice that errors is always a empty object even rules are defined in Controller. Maybe this helps?

**Comment by bluebill1049** [comment]
i think i know the issue @sajcics, try below:

```diff
- <Button onPress={handleSubmit(onSuccess, onFailure)} />
+ <Button onPress={() => handleSubmit(onSuccess, onFailure)()} />
````

**Comment by sajcics** [comment]
@bluebill1049 Unfortunately that didn't help. Even tho submitCount increases in release mode. I did printed some things out in release mode, maybe this also helps.

control: 
`{"_subjects":{"watch": {"observers": [{}, {}, {}, {}]}, "array": {"observers": []}, "state": {"observers" :[{}, {}, {}, {}, {}]}}, "_proxyFormState": {"isDirty": false, "dirtyFields": true, "touchedFields": "all", "isValidating": "all", "isValid": "all", "errors": "all", "isSubmitted": "All", "submitCount": "all"}, "_fields": {"first_name": {"_f": {"ref": {"name": "first_name"}, "name": "first_name", "mount": true, "required": "This field is required", "value": null}}, "_formValues": {"first_name: null}, "_stateFlags": {"action": false, "mount": true, "watch": false}, "_defaultValues": {}, "_names": {"mount": {}, "unMount": {}, "array": {}, "watch": {}}, "_formState": {"isDirty": false, "isValidating": false, "dirtyFields": {}, "isSubmitted": true, "submitCount": 1, "touchedFields": {}, "isSubmitting": false, "isSubmitedSuccessful": false, "isValid": true, "errors": {}}, "_options": {"mode": "onSubmit", "reValidateMode": "onChange", "souldFocusError": "true}}`

after I change value in input then I have:
`{"_subjects":{"watch": {"observers": [{}, {}, {}, {}]}, "array": {"observers": []}, "state": {"observers" :[{}, {}, {}, {}, {}]}}, "_proxyFormState": {"isDirty": false, "dirtyFields": true, "touchedFields": "all", "isValidating": "all", "isValid": "all", "errors": "all", "isSubmitted": "All", "submitCount": "all"}, "_fields": {"first_name": {"_f": {"ref": {"name": "first_name"}, "name": "first_name", "mount": true, "required": "This field is required", "value": "test"}}, "_formValues": {"first_name: "test"}, "_stateFlags": {"action": false, "mount": true, "watch": false}, "_defaultValues": {}, "_names": {"mount": {}, "unMount": {}, "array": {}, "watch": {}}, "_formState": {"isDirty": false, "isValidating": true, "dirtyFields": {"first_name": true}, "isSubmitted": true, "submitCount": 2, "touchedFields": {}, "isSubmitting": false, "isSubmitedSuccessful": false, "isValid": true, "errors": {}}, "_options": {"mode": "onSubmit", "reValidateMode": "onChange", "souldFocusError": "true}}`

Also, if I remove value from "first_name" field the button still do not triggers and getting the same output as the first one that I attached (except submitCount increases, other stays the same).

**Comment by cybercris** [comment]
This indeed is happening, for me calling handleSubmit(function) is not working in production mode. Does anyone know what is happening?

**Comment by tomtargosz** [comment]
@sajcics in your example it looks like the `GenerateField` component isn't being created properly, if you use this code it will work:
```
import { Controller, useForm } from "react-hook-form";
import { useCallback, useState } from "react";

const CustomComponent = () => {
  const { control, handleSubmit } = useForm();
  const [data, setData] = useState(null);

  const onFormSuccess = useCallback((data) => {
    setData(data); // only for example

    // axios.post('', data); send data to backend
  }, []);

  const onFormError = useCallback(() => {
    console.log("error");
  }, []);

  return (
    <>
      {["1", "2"].map((item) => (
        <p>
          <Controller
            control={control}
            rules={{ required: true }}
            name={item}
            render={({ field: { onChange, value, name } }) => (
              <label for="name">
                Fill for {item}:
                <input
                  onChange={onChange}
                  name={name}
                  value={value}
                  type="text"
                />
              </label>
            )}
          />
        </p>
      ))}
      <button onClick={handleSubmit(onFormSuccess, onFormError)}>submit</button>

      <p>
        Submitted:
        {data ? JSON.stringify(data) : "nothing"}
      </p>
    </>
  );
};

export default CustomComponent;
```

This being said, in our react native project we found that the reason it wasn't working in prod was because of `rules={{ required: true }}`. We removed this an instead used a resolver via https://github.com/jquense/yup and that solved the issue for us!
