### ISSUE TITLE
issue: invalid useFieldArray context type 

### ISSUE THREAD

**Issue by TiagoSaAdvizr** [react-hook-form/react-hook-form#7853]
### Version Number

7.27.0

### Codesandbox/Expo snack

https://codesandbox.io/s/resolver-context-forked-m8rcrl

### Steps to reproduce

Check line 38, the control cannot infer the context type. 

### Expected behaviour

Control should infer context type.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Type 'Control<FormValues, { isValid: boolean; }>' is not assignable to type 'Control<FormValues, object>'.
  The types of '_options.resolver' are incompatible between these types.
    Type 'Resolver<FormValues, { isValid: boolean; }> | undefined' is not assignable to type 'Resolver<FormValues, object> | undefined'.
      Type 'Resolver<FormValues, { isValid: boolean; }>' is not assignable to type 'Resolver<FormValues, object>'.ts(2322)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Possible regression, @bluebill1049?
It happened between [v7.12.2](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.12.2) and [v7.13.0-next.0](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.13.0-next.0).
The `Control` type accepts `TContext extends object = object` generic now
```ts
export declare type Control<TFieldValues extends FieldValues = FieldValues, TContext extends object = object> = {
    ...
    _updateProps: (props: UseFormProps<TFieldValues, TContext>) => void;
    ...
};
```
and `useFieldArray` doesn't pass it into the control
```ts
export declare type UseFieldArrayProps<TFieldValues extends FieldValues = FieldValues, TFieldArrayName extends FieldArrayPath<TFieldValues> = FieldArrayPath<TFieldValues>, TKeyName extends string = 'id'> = {
    ...
    control?: Control<TFieldValues>;
    ...
};
```
