### ISSUE TITLE
Dynamically inserting form fields prevents further "onSubmit" triggers

### ISSUE THREAD

**Issue by Kunigaikstis** [react-hook-form/react-hook-form#786]
**Describe the bug**
The `onSubmit` method of the form does not get triggered after an element was dynamically added to the form.

**To Reproduce**
After calling `onSubmit`, insert a new input and assign the `register` ref property.

**Codesandbox link**
https://codesandbox.io/embed/react-example-e2bp3?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
`onSubmit` gets triggered after additional registered form elements were added.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: react-hook-form ^4.3.0

**Comment by bluebill1049** [comment]
Did u change the input name?

**Comment by Kunigaikstis** [comment]
No name changes. The additional inputs get assigned a unique name though.

**Comment by bluebill1049** [comment]
it works if you add a submit button

```
import ReactDOM from 'react-dom';
import React, { useState } from 'react';
import { useForm } from 'react-hook-form';

let increment = 0;

export default function DynamicallyAddedFieldForm() {
  const { register, handleSubmit } = useForm();
  const [extraInputs, setExtraInput] = useState([]);

  const onSubmit = (data) => {
    console.count('onSubmit triggered', data);
    increment += 1;
    setExtraInput([...extraInputs, increment]);
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input type="text" name="input" ref={register} />
      {extraInputs.map(a => (
        <input key={a} name={a} ref={register} />
      ))}
      <button>submit</button>
    </form>
  );
}


ReactDOM.render(<DynamicallyAddedFieldForm />, document.getElementById('root'));```

**Comment by Kunigaikstis** [comment]
My bad, you're absolutely right.

**Comment by bluebill1049** [comment]
all good @Kunigaikstis 👍
