### ISSUE TITLE
Dynamic forms

### ISSUE THREAD

**Issue by mydesweb** [react-hook-form/react-hook-form#7871]
Generally I create forms using a structure like this:
```
{
  title: 'Form title',
  sections: [
    {
      title: 'Section title',
      description: 'Section description.',
      fields: [
        {
          name: 'fieldName',
          placeholder: 'fieldPlaceholder',
          defaultValue: 'fieldDefaultValue',
          maxLength: 10,
        },
      ],
    },
  ],
};
```
and I would like to suggest some ideas/improvements.

Since I don't know from the beginning what fields I am using it is difficult to declare the `defaultValues` in `useForm`, I prefer to declare the  field `defaultValue` in `useController` or `Controller`.

The problem here is that `dirtyFields` will not work in the same way (after one change the field will remain dirty even if it will have the same `defaultValue` in the end)

Also I find more useful if you declare a `defaultValue` in `useController` or `Controller` to override the value declared in `defaultValues` for the same field.

**Comment by Moshyfawn** [comment]
Come on, there's a feature request template that has a structure you're supposed to fill out to describe your feature idea in **a clear to the maintainer fashion**. Please, consider **following this template**. It's the second time you just omit the structure set by the maintainers of React Hook Form and proceed pushing your opinions on the way this library should work. **Not cool**.

That said, I don't see any feature request in what you wrote here.
If you want to define your `defaultValue` at the component level, you can do that with `Controller` as per the RHF docs. There's no other info / wanted behavior or anything else in your description that suggests a feature / a solution to a problem you've encountered using RHF.

**Comment by Moshyfawn** [comment]
I'm gonna close this issue until you meet the feature request template requirements.

**Comment by mydesweb** [comment]
@Moshyfawn I think you treat superficially my request, I write the context, the problem and the solution (the request for a change in the API) but if you don't read it is not my fault.

I know I can use `defaultValue` at the component level , I already mentioned this in my feature request the problem is about something else.
