### ISSUE TITLE
issue: Unable to get error properties from object value

### ISSUE THREAD

**Issue by TiagoSaAdvizr** [react-hook-form/react-hook-form#7874]
### Version Number

7.27.1

### Codesandbox/Expo snack

https://codesandbox.io/s/jolly-moser-b9grzh?file=/src/App.tsx

### Steps to reproduce

Add an object to the form values ( `country: {label: string, value: number}` ) 

Try to get the error message from it. 

Unable to access `message` from errors

### Expected behaviour

expect to access `message` from form state errors

### Relevant log output

```shell
Property 'message' does not exist on type 'FieldError | { label?: FieldError | undefined; value?: FieldError | undefined; }'.
  Property 'message' does not exist on type '{ label?: FieldError | undefined; value?: FieldError | undefined; }'.ts(2339)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I think you are missing this type: https://react-hook-form.com/ts#NestedValue

**Comment by TiagoSaAdvizr** [comment]
Indeed, thank you!
