### ISSUE TITLE
issue: Cann't resolve react hook form with yarn berry

### ISSUE THREAD

**Issue by grapgrap** [react-hook-form/react-hook-form#7875]
### Version Number

7.27.1

### Codesandbox/Expo snack

https://github.com/grapgrap/rhf-error-reproduce

### Steps to reproduce

1. Clone [this repo](https://github.com/grapgrap/rhf-error-reproduce)
2. Install dependencies with `yarn install`
3. Run next app with `yarn dev`

I'm using Yarn Berry with the `pnpEnableEsmLoader` is turned off.
When i use react-hook-form, I met the error that means Cannot find esm file of react-hook-form.

react-hook-form has no [`type` field](https://nodejs.org/api/packages.html#type) on package.json.
The resolver seems to try to resolve react-hook-form to commonjs.
Because importing react-hook-form to `import`, Resolver get to the esm code as specified in `package.json`.

### Expected behaviour

I expect to do not meet error.

### Relevant log output

```shell
error - Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'react-hook-form' imported from /Users/kimjonghyen/workspace/rhf-with-berry/.next/server/pages/index.js
Did you mean to import react-hook-form-virtual-a27f2ddb20/0/cache/react-hook-form-npm-7.27.1-972f8b03f0-99af1d47d3.zip/node_modules/react-hook-form/dist/index.cjs.js?
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
which version are you using? I don't think this is an issue for this library.

**Comment by flex-jonghyen** [comment]
I am using 
- react-hook-form 7.21.1
- yarn berry 3.2.0-rc.6
- node 14.17.3

After issue, I spend more time for this problem.
I can solved to remove exports field.
But, I do not think this is answer, I think yarn berry fault.

**Comment by Moshyfawn** [comment]
See yarnpkg/berry#3687, [this comment](https://github.com/yarnpkg/berry/issues/3687#issuecomment-957240140) in particular for the "fix". Not sure if it's in `stable` by now

**Comment by bluebill1049** [comment]
thanks for the additional information @flex-jonghyen we can keep an eye on this issue if anyone has solutions, but I am not sure if there is anything this repo needs to change.

**Comment by flex-jonghyen** [comment]
@bluebill1049 I solved to this with turned on `pnpEnableEsmLoader` option. Thanks!

**Comment by bluebill1049** [comment]
That's awesome! Thanks for sharing the solution.
