### ISSUE TITLE
issue: Dynamic input receives value from a different field when rendered

### ISSUE THREAD

**Issue by uncvrd** [react-hook-form/react-hook-form#7880]
### Version Number

7.4.1

### Codesandbox/Expo snack

https://codesandbox.io/s/beautiful-sanne-vw96h1?file=/src/App.tsx

### Steps to reproduce

This issue appears to occur with dynamic inputs. I have a `select` form field that determines whether a textfield or another select field should be rendered. The `First Option` in the select will display a TextField while the `Second Option` will display the select field. I only wish to submit values of form fields that are visible to the user which is why `shouldUnregister` is set to `true`.

1. Open console log in CSB
2. Type "abc" in to the text input
3. Observe the logs and see the current output

<img width="540" alt="image" src="https://user-images.githubusercontent.com/25097099/155032795-094a4000-28f7-48d0-880c-8048c3dd739b.png">

3. Change the `select` option from `First Option` to `Second Option`
4. Observe logs and notice how the `textField` value is now showing in the `dynamicSelect` value

<img width="533" alt="image" src="https://user-images.githubusercontent.com/25097099/155032961-7629da20-ec92-4a3f-91e3-1b38ddd27a0e.png">

### Expected behaviour

I expect for the `dynamicSelect` value to be initialized with `""` when the select is rendered on the page instead of receiving an initial value from the `textField` input.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
{mainSelect: "first", textField: "", dynamicSelect: ""}
{mainSelect: "first", textField: "a", dynamicSelect: ""}
{mainSelect: "first", textField: "ab", dynamicSelect: ""}
{mainSelect: "first", textField: "abc", dynamicSelect: ""}
{mainSelect: "second", textField: "abc", dynamicSelect: ""}
{mainSelect: "second", textField: "", dynamicSelect: "abc"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
i think it's related to this: https://react-hook-form.com/faqs#Whyisdefaultvaluenotchangingcorrectlywithternaryoperator

here is a working example: https://codesandbox.io/s/ecstatic-volhard-lre4ys?file=/src/App.tsx

**Comment by uncvrd** [comment]
You are correct, many thanks @bluebill1049 for your time, always helpful.
