### ISSUE TITLE
issue: SetFocus is not working in usefield Array onBlur

### ISSUE THREAD

**Issue by NarenderSiri** [react-hook-form/react-hook-form#7883]
### Version Number

7

### Codesandbox/Expo snack

https://codesandbox.io/s/modest-lake-p706y3?file=/src/App.js:3628-3719

### Expected behaviour

focus on lastname when i onBlur from firstname.
bill Please give reply

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by NarenderSiri** [comment]
> #2848

bill ,i want to setFocus in usefieldArray not SetValue  in usefieldArray

**Comment by NarenderSiri** [comment]
Please bill I am working for last 3 days on setFocus in usefieldarray.

#2848 link is setValue..
Not setFocus

Please do this please
Please
Please

**Comment by bluebill1049** [comment]
I am willing to help and as I do for pretty much anyone. however you need to pay some attention to your issue report, so it's not wasting my time.

- provide a reasonable codesanbxo
- provide steps to reproduce the issue.

**Comment by Moshyfawn** [comment]
Your issue is using square brackets notation to assign and access the field name.
`Controller` name should be
```js
name={`uoms.${index}.${id}`}
```
`setFocus` field name path should be
```js
setFocus(`uoms.0.lastname`)
```
And you must provide the `ref` from `field.ref` to your input in order for focus management to work
```jsx
<Controller
  render={({ field }) => (
    <input
      value={field.value}
      onChange={field.onChange}
      // INFO: this is important to provide
      ref={field.ref}
      onBlur={onBlur}
    />
  )}
  name={`uoms.${index}.${id}`}
  control={control}
  rules={{ required: true }}
/>
```

**Comment by Moshyfawn** [comment]
I'm providing the solution as there's [a codesanbox](https://codesandbox.io/s/modest-lake-p706y3?file=/src/App.js:3628-3719) with the reproduced issue described. But next time, please, don't omit the issue template reproduction steps and provide an isolated codesanbox right way, even if you think it's an "easy" to reproduce issue. It's a waste of out time other-wise

**Comment by NarenderSiri** [comment]
Sir,
I am using usefieldArray with three fields,
when i enter uomName and uomCode new row will append dynamically,
but horizontal tabindex is not working.
when onBlur of each field updatedata function will fire and i am appending total fields.
I am using react table component.

Am, I following correct way of approach in writing Code?
please suggest me.
please 

Sandbox code is neat and clear


[SandBox](https://codesandbox.io/s/reacthookformsforsetfocus-2yuzjy?file=/src/App.js)

**Comment by Moshyfawn** [comment]
React Hook Form doesn't manage the input's focus order. It's out of scope of this library

**Comment by Moshyfawn** [comment]
[This RHF docs section](https://react-hook-form.com/advanced-usage/#Workingwithvirtualizedlists) might help you with the virtualized inputs list you have

**Comment by NarenderSiri** [comment]
thanks

**Comment by NarenderSiri** [comment]
setFocus(`uoms[0][uomName]`);
    setFocus(`uoms[0].uomCode`);
    setFocus(`uoms.0.uomCode`);
    This focus is not working in UsefieldArray.
    Please give solution for this

**Comment by Moshyfawn** [comment]
```js
setFocus(`uoms.0.uomCode`)
```
should work, just tested. Make sure to provide `field.ref` into the correct ref prop of your input
