### ISSUE TITLE
[v6] fields do not unregister on unmount

### ISSUE THREAD

**Issue by ialsowalkdogs** [react-hook-form/react-hook-form#7885]
### Version Number

6.15.8

### Codesandbox/Expo snack

https://codesandbox.io/s/elastic-feather-7jhh2?file=/src/App.js

### Steps to reproduce

1. Go to [https://codesandbox.io/s/elastic-feather-7jhh2?file=/src/App.js](https://codesandbox.io/s/elastic-feather-7jhh2?file=/src/App.js)
2. Check the 'Check me' checkbox. Observe that second checkbox with 'I should unregister' label appears. 
3. Uncheck the 'Check me' checkbox. 
4. Verify from the console/devtools that `formState.isDirty` is true and `formState.dirtyFields` includes the unmounted/unregistered field

### Expected behaviour

- `formState.isDirty` should be false since it is equal to initial state
- `formState.dirtyFields` should be empty

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is because after `unrgister`, `second` input will become `undefined` and deepEqual will be failed. This would be the same result even in v7 (i think)

**Comment by ialsowalkdogs** [comment]
I updated my codesandbox to use the `undefined` as the default value explicitly but it still fails.

**Comment by bluebill1049** [comment]
<img width="586" alt="Screen Shot 2022-02-22 at 11 40 36 pm" src="https://user-images.githubusercontent.com/10513364/155134282-be9beef4-88ae-45d1-8e57-6845e177aa82.png">

the node is still mismatched, you can try with v7. we may have fixed.
