### ISSUE TITLE
Resolver does not apply value changes in onChange mode

### ISSUE THREAD

**Issue by KeKs0r** [react-hook-form/react-hook-form#7887]
### Version Number

7.27.1

### Codesandbox/Expo snack

https://codesandbox.io/s/objective-http-fhjyr0?file=/src/App.tsx

### Steps to reproduce

1. Enter a value for `Last Name`
2. Enter a value for first name with a space in between such as `Firstname MiddleName`
3. Submit the form (console logs the final values that are parsed)

### Expected behaviour

I would expect in `onChange` mode that the updated values would be reflected in the form before submit.
But they stay with their original value in the form itself and are only "parsed" on submit. 

Maybe this is the expected behaviour, but I find it very confusing, since the examples show that the resolver uses schemas to `parse` the values and return them. Some of the schema libraries have also the capability to modify input values and not only produce errors. I would have thought that those changes would also be reflected. It seems that its possible to generate validation errors during an onChange, so also allowing value updates would seem consistent.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
resolver only focuses on validation, if you want to have data transfer. do at the submissino level.

**Comment by Moshyfawn** [comment]
Hm, I wonder what's the difference between Zod and Yup here, 'cuz we had a similar "issue" #7730 and the resolution was that we let the validation library deal with mutation / processing values, if it happens to do so.

**Comment by bluebill1049** [comment]
different issue @Moshyfawn this one is related to `onChange`

**Comment by KeKs0r** [comment]
I understand that the intention of resolvers is validation. Does this have to be like this? Or would it be beneficial to make them more powerful?
If not, I find the documentation misleading, since libraries like Zod are not only for validation, but also for decoding. The examples used, suggest I can return "parsed" values in a resolver and it would work. But there is a combination of props (mode:'onChange' and resolver) that don't have the suggested behaviour. 

It feels like something is misleading, either the documentation or the API.

**Comment by bluebill1049** [comment]
very good feedback, the documentation is open-sourced as well, you can do everyone a favor and summary your concern and complaints to update it, so others don't make the same mistake.
