### ISSUE TITLE
Calling useFieldArray's update causes field.id to change since 7.23.0

### ISSUE THREAD

**Issue by pmrukot** [react-hook-form/react-hook-form#7889]
### Version Number

7.23.0 and above

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-7-23-0-jkp58z?file=/src/App.js

### Steps to reproduce

7.22.5 codesandbox -> https://codesandbox.io/s/react-hook-form-7-22-5-kjlvsl?file=/src/App.js
7.23.0 codesandbox -> https://codesandbox.io/s/react-hook-form-7-23-0-jkp58z?file=/src/App.js
7.27.1 codesandbox -> https://codesandbox.io/s/react-hook-form-7-27-1-mkdsy9?file=/src/App.js

1. Go to attached codesandbox of version 7.22.5
2. Update any field, be it add some characters or remove to trigger onChange event
3. `field.id` should stay the same.
4. Bump the version to 7.23.0 or above on dependency list or use some of the links attached above
5. Update any field, be it add some characters or remove to trigger onChange event
6. `field.id` changes

### Expected behaviour

I would say, this is a breaking change and not a feature and correct me If I'm wrong - it was not mentioned in the release notes of 7.23.0. I'm aware there were changes with DX improvements that you could rename the `id` to not overlap with some hypothetical database values.

This caused disturbance in my App, as with every update the field rerenders due to the `field.id` changing on `onChange` event. 

Issue might be on my side and my code might be wrong and there might be better ways to update the form state with every change, I'm not super experienced with the library but keen to learn 😅 In my app Im not using primitive values in array, but rather objects array of objects and each object represents section in a dynamic form. The example in codesandbox is simplified but I think it's enough to outline issue.

### What browsers are you seeing the problem on?

Only tested with Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
My bet is some RHF methods misuse on your end, 'cuz the way the input looses focus is wrong. Will look into your implementation in bit

**Comment by pmrukot** [comment]
Thanks for the answer, I could get rid of the `update` usage in my code during `onChange`. So what is the use case of `update` method? Maybe it's worth mentioning in release notes that the behaviour changed (field.id would be changed with the call)?

Otherwise I think it's closeable, would just like to hear more clarity on the `update` method.

**Comment by bluebill1049** [comment]
`update` API is made for update field array (group of field array inputs), for `controller` you should just use `onChange` method which it returns. hope this makes more sense.
