### ISSUE TITLE
issue: Controlled component - calling onChange with "undefined" doesn't update value correctly

### ISSUE THREAD

**Issue by Daniel-Novikov** [react-hook-form/react-hook-form#7892]
### Version Number

7.27.0

### Codesandbox/Expo snack

https://codesandbox.io/s/distracted-alex-uifrpu?file=/src/App.js

### Steps to reproduce

1. Go to ['Codesandbox'](https://codesandbox.io/s/distracted-alex-uifrpu?file=/src/App.js)
2. Click on 'Pick a date'
3. Notice how both App.js "start" value, and useControllers value changed.
3. Click on 'Unselect date'
4. See how the App.js "start" value changed to "undefined", yet useController's value is set back to defaultValue

### Expected behaviour

Expected to update useController value to "undefined", when called `onChange(undefined)`. Otherwise the controlled component is left with incorrect value. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Please refer to the documentation, controller or useController does not accept Undefined as a value.

**Comment by Daniel-Novikov** [comment]
It's only referring to `defaultValue`. 

Does it apply to `onChange` function as well? 
How would you approach this - if you need to unselect the value in a controlled component (can't be an empty string)?

**Comment by bluebill1049** [comment]
I will include undefined for `onChange` as well. Use null or empty string.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/documentation/commit/2aef4de552a66da67938f07763b399e218fba44b
