### ISSUE TITLE
errors object typing is not narrowing properly

### ISSUE THREAD

**Issue by whengely** [react-hook-form/react-hook-form#7907]
### Version Number

7.27.1

### Codesandbox/Expo snack

https://codesandbox.io/s/hopeful-rgb-31g7zp?file=/src/App.tsx

### Steps to reproduce

1.  Go to sandbox
2.  Select Person
3.  Hit submit and see that the input is wired up correctly
4.  Scroll to line 43 in App.tsx and see that the typing does not believe firstName exists

### Expected behaviour

errors.firstName should be valid as a property.  Even if you try to narrow with type === 'Person', it still is not a valid property.

In the schema.ts file there are examples of objects utilizing the type from the schema without any issues.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Property 'firstName' does not exist on type '{ type?: FieldError | undefined; firstName?: FieldError | undefined; lastName?: FieldError | undefined; } | { type?: FieldError | undefined; organizationName?: FieldError | undefined; }'.
  Property 'firstName' does not exist on type '{ type?: FieldError | undefined; organizationName?: FieldError | undefined; }'.ts(2339)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Currently, this is a limitation where nested input (as we would know if its a single input or a group of inputs) will need to use this type https://react-hook-form.com/ts#NestedValue
