### ISSUE TITLE
Errors are not tracked correctly when using Array Fields

### ISSUE THREAD

**Issue by Badyl1g** [react-hook-form/react-hook-form#791]
**Describe the bug**
When I add error handling to Array Fields example on CodeSandbox the errors object is not updated correctly.
I added a console.log statement to demonstrate how the errors object behaves

**To Reproduce**
1. Add two friends
2. Click submit
3. See four inputs highlighted red
4. Enter first name of the first friend - input will get re-validated and red highlight will disappear (as expected)
5. Enter last name of the first friend - inputs for the second friend will lose their red highlight - there will be two console outputs and the errors object will look like this:

First console output:
`{
  "friends": [
    {
      "firstName": {
        "type": "required",
        "message": ""
      },
      "lastName": {
        "type": "required",
        "message": ""
      }
    }
  ]
} `

Second console output:
`{
  "friends": [
    {
      "firstName": {
        "type": "required",
        "message": ""
      }
    }
  ]
} `

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-array-fields-qw6is

**Expected behavior**
Friends array in `errors` object should have length of 2 and the first item in the array should be null
After entering last name of the first friend errors object should look like this:
`{
  "friends": [
    null,
    {
      "lastName": {
        "type": "required",
        "message": ""
      },
      "firstName": {
        "type": "required",
        "message": ""
      }
    }
  ]
} `

**Screenshots**
![image](https://user-images.githubusercontent.com/27491471/71885340-74765e00-313a-11ea-9615-6276d3543bd1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave Version 1.2.41 Chromium: 79.0.3945.88 (Official Build)  (64-bit)

**Comment by bluebill1049** [comment]
can you please help test out this patch? `4.4.5-beta.1`

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-array-fields-gl7te

**Comment by Badyl1g** [comment]
This seems to work fine now, but there's one more issue I found (related to inputs with type number)

Should I submit another issue for that case?

**Comment by bluebill1049** [comment]
> This seems to work fine now, but there's one more issue I found (related to inputs with type number)
> 
> Should I submit another issue for that case?

yes plz
