### ISSUE TITLE
append not working useFieldArray when using for Loop

### ISSUE THREAD

**Issue by khanakia** [react-hook-form/react-hook-form#7921]
### Version Number

7.2.3

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-tvf23x?file=/src/index.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-forked-tvf23x?file=/src/index.js
Check code 
```
  useEffect(() => {
    for (let index = 0; index < 3; index++) {
      append({ firstName: "appendBill1", lastName: "appendLuo1" });
    }
  }, []);
```
It only appends 1 time

### Expected behaviour

It should appends 3 time

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please use `append([])` syntax instead.
