### ISSUE TITLE
Bug: formState.errors is not properly updated when field array error is present

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#7922]
### Version Number

7.27.1

### Codesandbox/Expo snack

https://codesandbox.io/s/optimistic-voice-mj1c8p?file=/src/App.tsx

### Steps to reproduce

1. Go to the sandbox
3. Click on one of the field array inputs to trigger a `focus` event
4. Click outside the field to trigger a `blur` event
5. Look in the console and notice that `formState.errors` does not contain an error for the field array when it should.
6. Repeat the same steps but for the non-field array input (first input). Notice that when the `blur` event is triggered, `formState.errors` is updated correctly.

### Expected behaviour

I expect field array errors to update `formState.errors` the same way that regular fields do. This means it should respect the `mode` setting on `useForm`. Currently, the only way to get the field array error to appear or disappear is to use the `trigger` method.

https://user-images.githubusercontent.com/36898266/155825647-c1f2e6a9-6c02-4bd3-9dfa-6d930deea10b.mp4

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> Schema validation focus on the field level for error reporting. Parent level error look is only limited to the direct parent level that is applicable for components such as group checkboxes.


thanks for the detailed issue report. this refer to the above.

**Comment by wdfinch** [comment]
I see. I think this is more of a feature request then and it depends on #7742 getting implemented first. 

The desired behavior would be if a field array input meets the requirement to trigger validation and a field array error is present, then that error would appear in `formState.errors` without having to use trigger.

So for example, if we had:

1. A field array that consisted of two elements and each element had a single text input
2. A schema that specified that each text input in the field array needed a unique value
3. `mode` set to `blur`

**then**

If the user triggers a blur event on an input, then the validation would run and if multiple inputs had the same value, `formState.errors` would show that.
