### ISSUE TITLE
Error not handled correctly on input registered with minimum value

### ISSUE THREAD

**Issue by Badyl1g** [react-hook-form/react-hook-form#793]
**Describe the bug**
When I register a field with type number and minimum value of `0` and type in negative value validation doesn't correctly add `type: 'min'` error

**To Reproduce**
1. Open Example Sandbox
2. Add one friend
3. Submit the form
4. Type in negative number into age field
5. Type positive number and change it to negative using arrow keys

Validating numbers below minimum value is triggered only on filled inputs (for example when you change from `2` to `-1` using arrow keys). But when the field is empty errors with type min are not present. **They appear after submiting form again**

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-array-fields-m2z0x

**Expected behavior**
Numbers below mininum value should always be validated

**Screenshots**
![image](https://user-images.githubusercontent.com/27491471/71890381-70e7d480-3144-11ea-832e-7a77526043aa.png)

**Desktop (please complete the following information):**
 - OS: Windowxs 10
 - Browser: Brave

**Comment by bluebill1049** [comment]
`react-hook-form@4.4.5-beta.3` should fix the issue
