### ISSUE TITLE
Disabling a form 

### ISSUE THREAD

**Issue by kashifnazar** [react-hook-form/react-hook-form#7945]
A very important use case with the forms is to enable/disable to form as a whole or some of its fields. I feel that this is something that would be a great add-on.

Another filed can be added to `formState` and `fields`, called `disabled` telling if the form or the field is disabled or not. 

Similarly, we can have `enable` and `disable` methods as members of the `methods` to allow us to enable/disable/toggle a form or it's fields.

I have created an [example](https://codesandbox.io/embed/react-hook-form-js-forked-vx0j5u) to demonstrate my idea. (This is just for demonstration purposes. Please don't use this on production as it will break).

**Comment by bluebill1049** [comment]
oops looks like the issue closer didn't cover the feature request correctly... I will move your feature request to the feature board anyhow.

**Comment by Moshyfawn** [comment]
I'll look into expanding the issue checker once I get to a quite working place

**Comment by Moshyfawn** [comment]
> oops looks like the issue closer didn't cover the feature request correctly... I will move your feature request to the feature board anyhow.

I'll look into expanding the issue checker once I get to a quite working place
