### ISSUE TITLE
issue: Custom Validation from examples page does not work

### ISSUE THREAD

**Issue by paulhan221** [react-hook-form/react-hook-form#7951]
### Version Number

7.22.5 in sandbox but also latest 7.27.1 has errors

### Steps to reproduce

In version 7.22.5 (sandbox version)
1. Go to https://codesandbox.io/s/react-hook-form-custom-validation-8kuu7
2. Click on First name field and change it to be anything other than `bill`
3. Custom validation for `firstName` field does not throw an error

In version 7.27.1 (latest version)
1. https://codesandbox.io/s/react-hook-form-custom-validation-forked-ulsllk
2. Click on submit button, error displays for `firstName` field even if user name is `bill`
3. There seems to be two errors here.
        - Error for `firstName` gets thrown even though name is bill.
        - Validation errors only get thrown when user hits submit, in sandbox version 7.22.5 the errors display immediately with keystroke

### Expected behaviour

Custom validation for "firstName" field should throw an error.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please refer to the documentation on `mode`: https://react-hook-form.com/api/useform

**Comment by paulhan221** [comment]
thank you
