### ISSUE TITLE
checkbox not checked when using with reakit Portal

### ISSUE THREAD

**Issue by sam-chuang** [react-hook-form/react-hook-form#7958]
### Version Number

7.27.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-reakit-react-hook-form-checkbox-jjkl08?file=/src/App.js

### Steps to reproduce

**Describe the bug**
Checkbox not show checked inside [reakit Portal](https://reakit.io/docs/portal/)

Note: react-hook-form version **7.22.5 works fine**, checkbox show checked within Portal,  after **version 7.23.0** not work anymore

Note: I also try to use ReactDOM.createPortal, but checkbox works fine with it, I am sorry for not able to further simplify the issue, If the sample code still too complicated for investigation, please feel free to close this ticket.

**To Reproduce**

1. Go to [https://codesandbox.io/s/react-reakit-react-hook-form-checkbox-jjkl08?file=/src/App.js](sandbox)
2. Click the button to open form inside portal
3. the checkbox inside portal not checked

**Expected behavior**
the checkbox should show checked

Screenshots
![not-checked](https://user-images.githubusercontent.com/33828310/156720994-8a690e67-a064-47e4-afa4-319c32d9ada2.png)

### Expected behaviour

the checkbox should show checked within Portal

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I am going to patch this, however, for anything to do with the portal, I would recommend going with a controlled checkbox instead, as it's more reliable and resistant to actual dom mutation during portal action.

**Comment by sam-chuang** [comment]
Thanks for your suggestion and help, really appreciated!!
