### ISSUE TITLE
Typescript errors

### ISSUE THREAD

**Issue by clementAC** [react-hook-form/react-hook-form#796]
I'm upgrading my react hook form to the latest stable version (previously on 3.29) and have some problems concerning types.

I'm using reset and error messages and I have type errors for both. The behavior in 3.29 is good but problems begin at 4.0.0 for error messages.
Here is the [codesandbox](https://codesandbox.io/s/react-hook-form-typescript-j1ddf
) that show the problems on line 23 and 31

Thank you for bringing alive this library. it's really simple & clean to use

**Comment by cargallo** [comment]
Hi @clementAC the library is trying to support better typescript support, with that saying, the better approach to overcome your actual error is that you declare an interface for the form values and pass it to useForm, here is the code: 

```JSX
interface IMyInterface{
  myText:string;
}

const { register, handleSubmit, errors, reset } = useForm<IMyInterface>();
```

And here is the sandbox corrected:

https://codesandbox.io/s/react-hook-form-typescript-flw31

**Comment by bluebill1049** [comment]
hope @cargallo have answered your question @clementAC, going to close this issue. Feel free to ask more questions here tho.

**Comment by clementAC** [comment]
Thank you @cargallo . Effectively, enforcing types like this is a really good thing.
@bluebill1049 it may be useful to had a question about enforcing type with typescript on the FAQ with a simple example like the one in @cargallo codesandbox?

**Comment by bluebill1049** [comment]
sounds really good @clementAC would you like to send a PR for a new FAQ for TS section?
