### ISSUE TITLE
issue: `formState.dirtyFields` goes nuts when using nested data structures as field values

### ISSUE THREAD

**Issue by delijah** [react-hook-form/react-hook-form#7965]
### Version Number

7.27.1

### Codesandbox/Expo snack

https://codesandbox.io/s/recursing-cache-65l4t9?file=/src/App.js

### Steps to reproduce

1. Make a change to the rich text editor on the first tab, `formState.dirtyFields` changes to the following, which is fine
```
{
    "variants": [
        {
            "title": true
        }
    ]
}
```
2. Click on the second tab and make a change to the rich text editor, `formState.dirtyFields` changes to the following, which is fine
```
{
    "variants": [
        {
            "title": true
        },
        {
            "title": true
        }
    ]
}
```
3. Add another tab by clicking `+`
4. See error: the whole dirty fields structure goes nuts ;)
```
{
    "variants": [
        {
            "variantId": false,
            "title": [
                {
                    "type": false,
                    "children": [
                        {
                            "text": true
                        }
                    ]
                }
            ]
        },
        {
            "variantId": false,
            "title": [
                {
                    "type": false,
                    "children": [
                        {
                            "text": true
                        }
                    ]
                }
            ]
        },
        {
            "variantId": true,
            "title": [
                {
                    "type": true,
                    "children": [
                        {
                            "text": true
                        }
                    ]
                }
            ]
        }
    ]
}
```
5. Touch and/or change any rich text editor field, and dirty fields go "back to normal" for that field

### Expected behaviour

`react-hook-form` must not start to compare nested data structures of fields. The nested keys should not appear in `formState.dirtyFields`. The dirty state should only be reported on the level of the actual field, not further down.

Correct
```
{
    "variants": [
        {
            "variantId": false,
            "title": true,
        }
    ]
}
```

Wrong
```
{
    "variants": [
        {
            "variantId": false,
            "title": [
                {
                    "type": true,
                    "children": [
                        {
                            "text": true
                        }
                    ]
                }
            ]
        }
    ]
}
```

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I have spent a couple of hours on this and I don't think we have a good solution when you pass down a deeply nested object (such as field value with draftJS) we are simply doing a diff comparison with `defaultValues`. I have tried the approach with doing diff only against registered input, however, this would bring a regression with field array (because field array potentially append/prepend/insert value ahead of time of registration), so I think we will take this as a design limation.

**Comment by delijah** [comment]
Oh no, sad. But thank you for investigating!
