### ISSUE TITLE
DeepPartial with TS

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#797]
The `reset` is good now.  So, that part is taken care of.

The issue with `AnotherComponent` in my sandbox, is that in my real app, components like that are part of a shared library of form components that are used by many different forms throughout the app.  The data for each form can vary widely.

For example, I have an `ImageUpload` component that displays the currently uploaded image or allows a new one to be uploaded.  If the name of that field on the form is `imageURL`, then I want to grab the default value via `defaultValues[name]`, where `name` is a prop with the value `imageURL` in one form.  But, it might be something like `primaryImageURL` in another form.  Either way, I would like `defaultValues[name]` to give me a string. 

It's possible I have a flaw in my component structure, but I am not seeing it at the moment if there is one.  I see the value for `DeepPartial` in simple form components.  But, It doesn't seem to hold up for abstracted components that are meant to be re-used by many different forms.

Prior to the `DeepPartial` my shared components would get `any` for `defaultValues[name]`, which is not ideal either, but it works.  My TypeScript knowledge is not deep enough to know if there is a way to make the `DeepPartial` work better.

If the `DeepPartial` sticks around, then I will need to do something like this in my components:

```javascript
const { defaultValues } = useLocalFormContext<Record<string, string>>();
```

Which I am fine with, since I know what my app is doing and it is slightly better than getting `any`.  But, I can see the `DeepPartial` causing similar issues for many others.

_Originally posted by @bopfer in https://github.com/react-hook-form/react-hook-form/pull/762#issuecomment-571710411_

**Comment by bluebill1049** [comment]
Original PR: https://github.com/react-hook-form/react-hook-form/pull/762#issuecomment-571710411

**Comment by bluebill1049** [comment]
I have tried the other DeepPartial `type` not working really well... i am send a PR to revert DeepPartial for now.

**Comment by kusmierz** [comment]
btw, it is worth to consider use `DeepPartial` equivalent to `FormErrors`, as it seems the same/similar (?).

**Comment by bluebill1049** [comment]
I think let's keep `DeepPartial` for awhile, see if any users encounter similar issue that @bopfer encountered, then we can take a look at it again. sounds ok?

**Comment by kusmierz** [comment]
it sounds good to me, you could also mention me in any case related with `DeepPartial`, I'll try to help if I could.

**Comment by bluebill1049** [comment]
much appreciated your help @kusmierz and @bopfer ❤️
