### ISSUE TITLE
issue: Form `isDirty` doesn't always match `dirtyFields`

### ISSUE THREAD

**Issue by evankennedy** [react-hook-form/react-hook-form#7970]
### Version Number

7.27.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-71uudg?file=/src/index.js

### Steps to reproduce

This is an interesting one I found in working with `react-hook-form` in a very complex situation where we show the editing controls for a single field array index at a time and allow them to update the default values of that part of the form if it's valid.

In testing, I've found two issues, possibly related. I'll go through more complex first, as it matches the issue title and is the bigger issue, but the second issue may give hints on what's going on.

If I can learn about the internals and have time, I'll try submitting some failing test cases and taking a stab at a solution.

## Issue 1

1. Go to Code Sandbox link
2. Click on 'Add'
3. Click on 'Update Defaults'
4. Click on 'Set Individual Value'

## Issue 2

1. Go to Code Sandbox link
2. Type 'test' into the first input
3. Click on 'Update Defaults'
4. Click on 'Set Individual Value'
6. Click on 'Update Defaults'
7. Click on 'Set Individual Value'

## Issue 1

At this point, you'll see the overall form `isDirty = false` and `dirtyFields` has `true` values within it.

## Issue 2

See that even though we are always explicitly setting `shouldDirty` and `keepDirty`, it is resetting dirty on that final `setValue('', { shouldDirty: true})`

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> At this point, you'll see the overall form isDirty = true and dirtyFields has true values within it.

What's the issue with the above? if your form is dirty and dirty fields have dirty fields.

> See that even though we are always explicitly setting shouldDirty and keepDirty, it is resetting dirty on that final

I am not sure if I follow the above.

The internal logic to resolve the following `formState`

- `isDirty` : deep equal against defaultValues
- `dirtyFeilds`: set dirty field to `true` or `false` depending on value against each individual field level. This is especially the case for field arrays, the reason some other form libraries just avoid including dirty fields. When you append a new field it will include new form values and in side hook form it will be marked as dirty, because your default value for the field array is empty (`undefined`)

**Comment by Moshyfawn** [comment]
Possibly related #7845

**Comment by evankennedy** [comment]
My apologies, it's been quite a week. I meant `isDirty = false`, while `dirtyFields` has `true` values within it. Will update the issue.

**Comment by bluebill1049** [comment]
> My apologies, it's been quite a week. I meant isDirty = false, while dirtyFields has true values within it. Will update the issue.

Yes, as I stated above `isDirty` is form level again `defaultValues`, `dirtyFields` will be measured at field level for performance reason we are not updating each fields' dirty flag, only the ones that you are interacting or setValue with, by invoking `setValue` will update the `isDirty` and update that specific field's dirty state.

**Comment by bluebill1049** [comment]
update the doc on what I referred to above. let me know if this makes things a bit clear or potentially improves the doc further.
