### ISSUE TITLE
issue: incorrect type of formState.errors if the field is an Array

### ISSUE THREAD

**Issue by ykun91** [react-hook-form/react-hook-form#7972]
### Version Number

7.27.1

### Codesandbox/Expo snack

https://codesandbox.io/s/boring-cookies-91h8di?file=/src/App.tsx:675-1016

### Steps to reproduce

1. See my Codesandbox example

### Expected behaviour

the type of `errors.arrayField` should be `FieldError | undefined` or should be a `Union` that contains `FieldError | undefined`?

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
you should use this type with V7: https://react-hook-form.com/ts#NestedValue we are addressing this problem in the next major version. basically, it's difficult to determine between field error vs a group of fields error.

**Comment by ykun91** [comment]
@bluebill1049 
Thanks for you quick response! 

umm.. I did have a look at the document and tried to change my code to [this](https://codesandbox.io/s/epic-monad-6ccu0k?file=/src/App.tsx). 
Seems that the type issue of `errors.arrayField` get solved, but 2 others typescript errors come out at the line 22, 40

**Comment by ykun91** [comment]
Seems like the same issue is reported here?
https://github.com/react-hook-form/react-hook-form/issues/7888

So it may be better for me to wait for your v8 and just make a workgroud like
`const error = formState.errors.arrayField as unknown as FieldError | undefined` 😄

**Comment by bluebill1049** [comment]
you can try out v8 already, some of the breaking changes here: https://github.com/react-hook-form/react-hook-form/discussions/7433 but it may not affect you at all.

**Comment by bluebill1049** [comment]
looks fine in v8: https://codesandbox.io/s/quirky-williams-pv1lgg?file=/src/App.tsx

**Comment by ykun91** [comment]
Thanks, I confirmed v8 works.
