### ISSUE TITLE
Form fields not resetting after page refresh in Firefox

### ISSUE THREAD

**Issue by indahud** [react-hook-form/react-hook-form#7976]
### Version Number

7.27.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-get-started-smspp?file=/src/index.js

### Steps to reproduce

I am using react-hook-form inside Nextjs application. I am using this [example](https://codesandbox.io/s/react-hook-form-get-started-smspp?file=/src/index.js). I have this weird issue. When I refresh the page inside firefox or firefox-developer-edition the form fields are not resetting. But it's not case with the Chromium based browsers.

### Expected behaviour

Form fields should reset after page refresh.

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for the issue @indahud not sure if there is anything we could do at the browser level. we do not persist data.

**Comment by indahud** [comment]
Firefox is trying to autocomplete the data. `autoComplete="off"` resets the data.

**Comment by bluebill1049** [comment]
Thanks for the additional detail. However, just like what i suggested above, this is not an issue that this library could resolve.
