### ISSUE TITLE
Enable Consumers to Supply Their Own Handlers (`onChange`, `onBlur`, etc.)

### ISSUE THREAD

**Issue by ITenthusiasm** [react-hook-form/react-hook-form#7978]
## The Problem
I discovered that I cannot supply my own handlers (e.g., `onChange`, `onBlur`, etc.) to `input` elements without losing the benefits of `React Hook Form` error handling. It seems that the `register` function returns its own asynchronous `onChange` and `onBlur` props to an input. This means that right now, if a consumer wants to add custom functionality to an `input`, they will be forced to choose between `React Hook Form`'s features and their own custom functionality.

## The Solution
It would be **_amazing_** if `React Hook Form` could find another way to add its functionality _without_ usurping the `onChange` and `onBlur` props of elements. That's the entirety of this feature request. Maybe the `ref` function returned from `register` could set up the event handlers it needs when it's called?

## Alternatives
The alternative is to off-shift the responsibility of this matter to the consumer. In that case, users would need to find a clever way to add event handlers to their inputs. This gets a little harder if state is being used, but hopefully it isn't too bad when state isn't used.

## Additional Context
N/A

**Comment by ITenthusiasm** [comment]
@bluebill1049 Could this be re-opened? I did indeed follow the issue template. But I used header elements (`#`) instead of bold text (`**`) because I thought it would make the issue easier to read.

**Comment by bluebill1049** [comment]
`register('name', { onChange, onBlur })` this feature is already been implemented.

**Comment by ITenthusiasm** [comment]
Can't believe I missed something that obvious. Sorry!!! Thanks!

**Comment by bluebill1049** [comment]
no worries @ITenthusiasm ❤️

**Comment by geekus** [comment]
@bluebill1049 : But does it work? Typescript says `onChange` and `onBlur` are not valid properties for options object, and also in the example sandboxes it does not seem to be recognized.

<img width="1494" alt="Screen Shot 2022-03-11 at 14 22 28" src="https://user-images.githubusercontent.com/6450570/157876082-e78eaafe-3a15-460a-9f2e-48e9976ba2ba.png">

**Comment by ITenthusiasm** [comment]
@geekus Are your versions correct? Everything works fine on my application with `react@17.0.2`, `react-dom@17.0.2`, and `react-hook-form@7.26.1`. I'd imagine that you don't need v17 for this to work; you should only need a version of React after hooks were introduced.

**Comment by geekus** [comment]
Thanks @ITenthusiasm . :)

Looks like I was at an older version of 7. Thought I'd had installed the latest but ran in wrong directory, but when the example sandboxes didn't work either I thought there might be something. But now realize they were using an alpha version. 😳 So now with the latest and greatest installed it works as you say. Thanks again!
