### ISSUE TITLE
issue: useFormState does not rerender when the control prop changes

### ISSUE THREAD

**Issue by gummybuns** [react-hook-form/react-hook-form#7990]
### Version Number

7.27.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-js-forked-b8e6v9?file=/src/App.js

### Steps to reproduce

When using `useFormState` in a separate component from where `useForm` is rendered, the values (like `isDirty`) do not change when the `control` object passed in changes.

I think the codesandbox link is a good demo:
https://codesandbox.io/s/react-hook-form-js-forked-b8e6v9?file=/src/App.js

1. The parent component has two `useForm()` calls for separate forms
2. Create a child component with a `control` prop. Call `useFormState({ control })`
3. Update the first form by editing a field - confirm that the `useFormState` reflects the state of the first form
4. The parent component dynamically changes which control object is passed to the child (maybe with a button)
5. Update the second form by editing a field - notice that the `useFormState` is still reflecting the state of the first form

![Kapture 2022-03-08 at 13 45 22](https://user-images.githubusercontent.com/47437711/157304793-fbef79a0-744e-4d19-8514-578489395a65.gif)

### Expected behaviour

`useFormState` takes in a `control` parameter. When the reference to the `control` parameter passed changes, `useFormState` should properly return data for the new control passed.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for the detail. we don't support such usage by shared control.

**Comment by gummybuns** [comment]
Can you explain a valid useCase for `useFormState`?

The example included https://react-hook-form.com/api/useformstate calls the hook in the same component as `useForm`:

```
export default function App() {
  const { register, handleSubmit, control } = useForm({
    defaultValues: {
      firstName: "firstName"
    }
  });
  const { dirtyFields } = useFormState({
    control
  });
  const onSubmit = (data) => console.log(data);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input {...register("firstName")} placeholder="First Name" />
      {dirtyFields.firstName && <p>Field is dirty.</p>}
      
      <input type="submit" />
    </form>
  );
}
```

why would someone want to call `useFormState` when `useForm` returns the formState directly?

To me it seems like the idea behind it was so you can have multiple components and you instead have to pass the `control` as a prop?
```
const Child = ({ control }) => {
  const { isDirty } = useFormState({ control });
  return (
    <p>{isDirty}</p>
  );
}

const App = () => {
  const { control } = useForm();

  return(
    <div>
      <Child control={control} />
    </div>
  )
}
```
again though why use it if `useForm` already returns the `formState`, i can just pass `formState` directly to `<Child />`

**Comment by bluebill1049** [comment]
> This custom hook allows you to subscribe to each form state, and isolate the re-render at the custom hook level. It has its scope in terms of form state subscription, so it would not affect other useFormState and useForm. Using this hook can reduce the re-render impact on large and complex form application.

https://react-hook-form.com/api/useformstate
