### ISSUE TITLE
issue: Focus problem for MUI ToogleButton 

### ISSUE THREAD

**Issue by atillaaliyev** [react-hook-form/react-hook-form#7994]
### Version Number

7.27.0

### Codesandbox/Expo snack

https://codesandbox.io/s/vb1x99

### Steps to reproduce

1. Go to codeSandbox

### Expected behaviour

I have a ToogleButton and Autocomplete. When I pressed submit button, validation OK. But I have a problem for ToogleButton.  While focusing worked good for AutoComplete , didn't work for  ToogleButton.

I read all api documents , but I didn't find any solution that why isn't working. I guessed this item is button so didn't work. I wrapped this item by FormControl, but result is same.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
You're trying to focus the button group `div` element by passing the the RHF `ref` callback to your `VToogleButtonGroup` component and down to the `ToggleButtonGroup`.

In theory, to focus the actual `button` element, you want to pass the `ref` in the `VToogleButtonGroup` to the `ToggleButton` component.

That said, you want to `forwardRef` in your `VToogleButtonGroup` to get the ref passed from the parent component in your functional component. See [this CSB](https://codesandbox.io/s/react-hook-form-toogle-focus-forked-g4q19h?file=/v-toogle-button-group.tsx) for the example.

**Comment by atillaaliyev** [comment]
Thank you @Moshyfawn ,
Perfect answer, i got clearly.

**Comment by bluebill1049** [comment]
thank you @Moshyfawn
