### ISSUE TITLE
How to allign horizontally ?

### ISSUE THREAD

**Issue by burton666** [react-hook-form/react-hook-form#800]
This is probably a stupid question but how do I allign input-fields horizontally?

**Comment by TimFletcher** [comment]
Hi there. This is a generic question about CSS styling and not related to `react-hook-form`. Maybe search https://stackoverflow.com for a solution.

You should look at flexbox and / or grid layout for this.

**Comment by bluebill1049** [comment]
yea please ask stackoverflow :) plenty answers there for sure
