### ISSUE TITLE
issue: Errors are not cleared when yup when method is valid

### ISSUE THREAD

**Issue by tamir61** [react-hook-form/react-hook-form#8003]
### Version Number

7.27.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-validationschema-v7-forked-qqcp21?file=/src/index.js

### Steps to reproduce
In this example, I created a validation that name is required only if age is greater than 3,
So if you will enter age like 2 and the name will stay empty no error will appear as expected. 
But, if you will do these steps you will see a behavior that looks strange to me.
1. enter age greater than 3,
2. enter some string in name input (everything works correctly)
3. remove the string from name input, you will see the expected error 
4. change the age to below 3

### Expected behavior

I expected the error to be deleted by the RHF lib, also you will see at the console that the form isValid is true but errors are filled with the error of the name input

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
dependency validation use `trigger` or `deps` attribute from `register.

> Schema validation focus on the field level for error reporting. Parent level error look is only limited to the direct parent level that is applicable for components such as group checkboxes.

https://react-hook-form.com/api/useform
