### ISSUE TITLE
issue: pattern rule is not unset on change to undefined

### ISSUE THREAD

**Issue by michalbundyra** [react-hook-form/react-hook-form#8004]
### Version Number

7.27.1

### Codesandbox/Expo snack

https://codesandbox.io/s/sharp-mirzakhani-pxcw9p?file=/src/App.tsx

### Steps to reproduce

1. Go to codesanbox https://codesandbox.io/s/sharp-mirzakhani-pxcw9p?file=/src/App.tsx
2. Provide values like "hello" and "world" in two fields
3. Click "submit"
4. You should see `{ value1: "hello", value2: "world" }`
5. Click on button "mention"
6. Click "submit"
7. See errors on both fields
8. Click button "No pattern"
9. Click "submit"
10. See error only on the second field.

### Expected behaviour

I am changing rules on the field dynamically - I want to change the pattern on the field. I set the same rules, and output rules in console log.
When I want to unset pattern somehow it does not work.
To get it working I need to to explicitly: `{pattern: undefined, ...rules}` and just `rules` is not working even tho pattern is not defined in rules.

I am not sure if this is something you want to fix, or this is "by design" and "won't fix". Just wanted to make sure I am not doing something wrong here.

Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> Individual register option can't be removed by undefined or {}. You can update individual attributes instead.

https://react-hook-form.com/api/useform/register
