### ISSUE TITLE
Re-registered field not visible on submit when used with FormContext

### ISSUE THREAD

**Issue by mlnarik** [react-hook-form/react-hook-form#801]
**Describe the bug**
Field that is re-registered is not visible on submit when used with FormContext.

**To Reproduce**
Sandbox: https://codesandbox.io/s/react-hook-form-defaultvalues-7rjbh
1. Click Toggle to hide last name input
2. Click Toggle to show last name input
3. Submit form
Expected: last name visible in popup
Actual: last name not visible in popup

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-defaultvalues-7rjbh

**Expected behavior**
last name visible in popup

**Additional context**
Field is not properly re-registered.
"control.fields" are refreshed after submission when react rerenders form component.
You have to click submit again to get right form values.

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report. it's working you are using a beta version. try 4.4.6

https://codesandbox.io/s/react-hook-form-defaultvalues-wxgo6

**Comment by mlnarik** [comment]
I tried your sandbox, it's NOT working on Chrome.

**Comment by bluebill1049** [comment]
why it's working for me each time?

**Comment by bluebill1049** [comment]
ok i just reproduced it, by click the toggle couple times.

**Comment by bluebill1049** [comment]
i just release i have fixed this issue in another branch: 

https://codesandbox.io/s/react-hook-form-defaultvalues-wxgo6 

test it out, i will release the fix tonight

**Comment by bluebill1049** [comment]
let me know if the above codesandbox fix the issue (verify) then i will release the patch.

**Comment by mlnarik** [comment]
I tried your sandbox and it seems to be working correctly now. Thank you. Looking forward to use it in my project

**Comment by bluebill1049** [comment]
sweet! thanks for re-verify. going to release the patch now.
