### ISSUE TITLE
Support a `normalize` method too (like `redux-form` does)

### ISSUE THREAD

**Issue by afilp** [react-hook-form/react-hook-form#8013]
**Is your feature request related to a problem? Please describe.**
I greatly miss the `normalize` feature that `redux-form` has. See here:
https://redux-form.com/6.5.0/docs/valuelifecycle.md/

**Describe the solution you'd like**
Can we also please have the `normalize` method along with `parse`/'format` ? 

**Describe alternatives you've considered**
Cannot find an alternative way.

**Additional context**
I am using the `normalize` method in `react-admin`.
See comment here, on how I use it and why it is important (cannot find another way to do the same there):
https://github.com/marmelab/react-admin/issues/7281#issuecomment-1055913756 

Thank you!

**Comment by Moshyfawn** [comment]
Sorry for the closed issue. You need to tweak the config a bit.

Your feature request is still relevant, let's see what @bluebill1049 has to say about it.

**Comment by bluebill1049** [comment]
putting to the project board.

**Comment by afilp** [comment]
Thanks a lot! 

Please note that `normalize` is quite useful (and we were using it a lot). It may also be easy to implement if you look what `redux-form` also does for this method.

Just to give you an idea, what we do with this:

normalize={upper}
```
export const upper = v => v && v.toUpperCase();
```

normalize={numbersOnly}
```
export const numbersOnly = v => v && Number(v.toString().replace(/[^0-9.,]/g, ''));
```

normalize={digitsOnlyNoCommas}
```
export const digitsOnlyNoCommas = v => v && Number(v.toString().replace(/[^0-9]/g, ''));
```

...and so on. 

Very useful to "force" the end-user enter data in the format the field needs to.
('parse' and 'format' cannot enforce this)

Looking forward for such an implementation, we are holding a major upgrade of react-admin v3 to v4, just for this (as we could not replace these methods).

Thanks!

**Comment by afilp** [comment]
Not to mention that this is the most important `normalize` function we created, much needed for converting english characters to greek while typing (and vice versa):

normalize={englishToGreekUpper} 

and 

normalize={greekToEnglish}
