### ISSUE TITLE
issue: We can't use quotes and double quotes in the form inputs' names

### ISSUE THREAD

**Issue by vinassefranche** [react-hook-form/react-hook-form#8014]
### Version Number

7

### Codesandbox/Expo snack

https://codesandbox.io/s/recursing-leaf-7x4ntu?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/recursing-leaf-7x4ntu?file=/src/App.tsx
2. See the error `Cannot read properties of undefined (reading '_f')`

### Expected behaviour

I would expect the form to work properly.
However, the quotes and double quotes are explicitly removed in the [stringToPath function](https://github.com/react-hook-form/react-hook-form/blob/master/src/utils/stringToPath.ts) which is used in the `set` function. There might be a good reason for that. In that case, It would be great to have a clearer error and a mention of this limitation in the documentation (I might have missed it if it is existing)

FYI, in our codebase where we mainly use `control`, not error is thrown and the `formData` given by `handleSubmit` does not contain the fields with quotes in their names. This make the issue very hard to understand

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinassefranche** [comment]
I'll be willing to help implement the solution, by the way!

**Comment by bluebill1049** [comment]
At the moment we don't support single and double quotes for sting names probably applicable for other special characters. I would suggest avoiding those, if not that's the case, sending a feature request and waiting for the community's request on such support or improvement.

**Comment by vinassefranche** [comment]
FYI, just modifying `stringToPath` to:
```
import compact from './compact';

export default (input: string): string[] =>
  compact(
    input
      .replace(/\[["|']/g, '[')
      .replace(/["|']\]/g, ']')
      .replace(/\]/g, '')
      .split(/\.|\[/),
  );

```
makes all the test pass.

**Comment by bluebill1049** [comment]
Thanks for the suggestion, I would like to avoid those extra `replace` logic if possible before we consider to support the above usage, so goes back to the original statement. 

> I would suggest avoiding those, if not that's the case, sending a feature request and waiting for the community's request on such support or improvement.

**Comment by bluebill1049** [comment]
Thanks for the suggestion, I would like to avoid those extra `replace` logic if possible before we consider to support the above usage, so goes back to the original statement. 

> I would suggest avoiding those, if not that's the case, sending a feature request and waiting for the community's request on such support or improvement.

**Comment by vinassefranche** [comment]
@bluebill1049 I've created the feature request [here](https://github.com/react-hook-form/react-hook-form/issues/8019)
I'm closing this issue then. Thanks for the answers
