### ISSUE TITLE
Support the use of quotes (simple and double) in fields' names

### ISSUE THREAD

**Issue by vinassefranche** [react-hook-form/react-hook-form#8019]
**Is your feature request related to a problem? Please describe.**
If your form model has keys with quotes, react-hook-form will throw an unclear error: `Cannot read properties of undefined (reading '_f')`
See [here for the reproduction of the issue](https://codesandbox.io/s/recursing-leaf-7x4ntu?file=/src/App.tsx). 

**Describe the solution you'd like**
As having quotes in the keys of an object is perfectly valid in javascript, I would expect react-hook-form to work correctly with them.

**Describe alternatives you've considered**
The only alternative I see is forbidding the use of quotes. In that case, we should have a clear error.

**Additional context**
I've reported the issue previously [here](https://github.com/react-hook-form/react-hook-form/issues/8014).
As noted there, it seems like the culprit is the [`stringToPath` function](https://github.com/react-hook-form/react-hook-form/blob/master/src/utils/stringToPath.ts)
Modifying it to this should fix the issue while making the current tests pass: 
```typescript
import compact from './compact';

export default (input: string): string[] =>
  compact(
    input
      .replace(/\[["|']/g, '[')
      .replace(/["|']\]/g, ']')
      .replace(/\]/g, '')
      .split(/\.|\[/),
  );
```

![image](https://user-images.githubusercontent.com/15926755/158211245-b6e8145f-4ee9-40d7-be4d-d99be7839bbe.png)

**Comment by bastoche** [comment]
Maybe we can provide a PR for this?

**Comment by bluebill1049** [comment]
putting the project board, if this is something important for your current project, you can fork the repo and publish your own for now.

**Comment by vinassefranche** [comment]
@bluebill1049 thanks for letting me know. Don't hesitate to come back to me if I can help implement it when you decide to do so.
