### ISSUE TITLE
Controller throws error

### ISSUE THREAD

**Issue by thoughtassassin** [react-hook-form/react-hook-form#802]
**Describe the bug**
If you don't supply defaultValues to useForm, a third party component wrapped in a Controller throws this warning:

```
Warning: A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component.
```

**To Reproduce**
1. Wrap a third party input in Controller.
2. Don't supply defaultValues to useForm.
3. Type in the input.

**Codesandbox link**
https://codesandbox.io/s/autumn-breeze-txshv

**Expected behavior**
The input should not switch between uncontrolled and controlled.

**Screenshots**
![Screen Shot 2020-01-08 at 10 48 11 AM](https://user-images.githubusercontent.com/1539057/71998359-0fd40580-3205-11ea-9503-c6ba005b2bc6.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome, Firefox
 - Version: 79.0.3945.88, 71.0

**Comment by miguel-lattuada** [comment]
I think this is more a React thing and not related to `react-hook-form`. [Check this example](https://stackoverflow.com/questions/47012169/a-component-is-changing-an-uncontrolled-input-of-type-text-to-be-controlled-erro/47012342#47012342), you can set empty values as empty strings to avoid this.

**Comment by bluebill1049** [comment]
please refer to default value part of `Controller`.

https://react-hook-form.com/api#Controller

**Comment by thoughtassassin** [comment]
@bluebill1049 so you DO need to supply defaultValues? I guess I am just making sure that is the case.

**Comment by bluebill1049** [comment]
@thoughtassassin you can provide either `defaultValues` at `useForm` or `defaultValue` at `Controller`. It's hard to predict `defaultValue`/`value` for external component, so it's better as user to declare that. (eg: checkbox, input)

**Comment by bluebill1049** [comment]
going to close this issue, feel free to ask more questions tho.
