### ISSUE TITLE
Discriminate unions on useForm TFieldValues

### ISSUE THREAD

**Issue by alec-pirillo-le** [react-hook-form/react-hook-form#8022]
**Is your feature request related to a problem? Please describe.**
I'm trying to handle a dynamic form which could contain 3 different models. Currently, register cannot descern which of the union types to check against.

**Describe the solution you'd like**
When a watched field is updated e.g. `Type`

```
const type FirstModel = {
type: 'FIRST'
first: string
}
const type FirstModel = {
type: 'SECOND'
second: string
}
const { handleSubmit, control, watch, register } = useForm<
    | FirstModel
    | SecondModel
  >({ defaultValues: { type: 'FIRST' } })

const type = watch('type')
...
return (
     {type === 'FIRST' && (
          // This should give me an error, as we know second is not available on FirstModel
          <TextInput {...toClassProps(register('second'))} label="Host" />
     )}
)
```

**Describe alternatives you've considered**
Creating separate views for each model is possible, but is not as practical when there is many fields, and types only vary 1-2 fields.

**Additional context**
There may be other approaches, but I couldn't find a suitable solution in the docs or examples

**Comment by alec-pirillo-le** [comment]
Apologies for the duplicate issue, the auto close made me second guess my formatting so I recreated the feature request.

**Comment by bluebill1049** [comment]
hey @alec-pirillo-le sorry about the auto closer, I may disable that for now. It was meant to close the issue without reproducible codesandbox. Your feature request, could you try it out with the alpha version of v8? it may be already resolved.

**Comment by alec-pirillo-le** [comment]
No problem @bluebill1049, thanks for responding so quickly.

No it appears the issue is actually worse on 8.0 in a way - it can see there is a union type, and wont let me access `second` or `first` so it actually would not allow me to access the properties/fields at all. 

Unless there is some new syntax to help the register discriminate the types outside of wrapping it as below
```
     {type === 'FIRST' && (
          <TextInput {...register('bar')} />
     )}
```
