### ISSUE TITLE
setValue destroys Map objects

### ISSUE THREAD

**Issue by nkahnfr** [react-hook-form/react-hook-form#8026]
### Version Number

7.28.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-setvalue-forked-nzfoyu

### Steps to reproduce

1. Provide a `Map` object to `setValue`.
2. Saved value is an empty object.
3. See repro in Codesandbox.

### Expected behaviour

Saved value should be the provided `Map` object.

It seems that [cloneObject](https://github.com/react-hook-form/react-hook-form/blob/1150dc7752410e490ae32154592e67ca03d1cd23/src/utils/cloneObject.ts#L4) function does not support `Map` object.
It should be easily fixed using the same approach as with `Set` object.
```
if (data instanceof Map) {
  copy = new Map(data);
} 
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nkahnfr** [comment]
I proposed the following PR: #8027
Hope it helps.

**Comment by bluebill1049** [comment]
thanks for the PR and issue report, i think this is the direction we are going ahead with: https://github.com/react-hook-form/react-hook-form/issues/7279

**Comment by bluebill1049** [comment]
I am going to move that feature request to in progress and start preparing a RFC.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/discussions/8030

**Comment by nkahnfr** [comment]
@bluebill1049 Thanks for the feedback, your RFC makes sense.

Please note my PR does not fix the issue with Map object, `useWatch` should also be modified to prevent getting an empty object on update. So I propose to close #8027.

My actual workaround is to use a wrapper for that kind of data, i.e. an object with an accessor method which will disable cloning.
```
const myMap = new Map([['test', { test: true }]];
const mapWrapper = { getMap: () => myMap };
setValue('test', mapWrapper);

```
Sandbox has been updated: https://codesandbox.io/s/react-hook-form-v7-setvalue-forked-nzfoyu

**Comment by bluebill1049** [comment]
ok, thanks for the update and for the PR as well. I am going to close this issue as we don't support `Map` during the clone at the moment. Let's keep an eye on the RFC and discuss things over there. Your input is welcome in the RFC.

RFC: https://github.com/react-hook-form/react-hook-form/discussions/8030

**Comment by bluebill1049** [comment]
Just to add some more context into the RFC as well.

- what's the ur usage with `Map` data type? 
- what sort of form input has that type of support? 
- is there s component that uses such or you are just storing data as a state?

**Comment by Moshyfawn** [comment]
The OPs use-case looks like it would benefit from `onSubmit` data transformation instead of storing data in a Map, IMO

**Comment by nkahnfr** [comment]
To be honest, my scenario does not require absolute support for the Map type.

I am storing structured data from the import of a CSV file but I could use an object to do it and more importantly, follow another strategy by deferring the file upload and data parsing to another component.

It was just an easy way to proceed quickly even if it's certainly not a good practice. :)

Thanks for your support and the fantastic work with that package.
