### ISSUE TITLE
issue: errors = {}, isValid = false

### ISSUE THREAD

**Issue by iBreadInside** [react-hook-form/react-hook-form#8031]
### Version Number

7.28

### Codesandbox/Expo snack

https://codesandbox.io/s/dank-pine-7fq2nx?file=/src/form/form.jsx

### Steps to reproduce

1. Click on button 'Console errors'
2. Check console

### Expected behaviour

I thought while there are no errors in errors object isValid === true.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
plz fix your codesandbox first.

**Comment by iBreadInside** [comment]
> 

How? Link works for me.

**Comment by iBreadInside** [comment]
>

**Comment by bluebill1049** [comment]
That's after you have fixed it. thanks

**Comment by bluebill1049** [comment]
- refer to the doc on isValid: 

https://react-hook-form.com/api/useform/formstate#return

> Note: isValid is affected by mode at [useForm](https://react-hook-form.com/api/useform). This state is only applicable with onChange, onTouched, and onBlur mode.

- errors only get updated with user's interaction, eg after submitting or interacting with input.

**Comment by iBreadInside** [comment]
Ok, trying to disable sumbit button with !isValid. but after I fill all fields it stay disabled.

**Comment by bluebill1049** [comment]
It's a question if your entire form is valid or not.

**Comment by RigottiG** [comment]
I'm facing the same issue, I have a visible form. When it's valid I want to display the other form, the problem that is validating the invisible form is also valid so `isValid` never be `true` because it's validating a form that so far is not rendering.

**Comment by bluebill1049** [comment]
> I'm facing the same issue, I have a visible form. When it's valid I want to display the other form, the problem that is validating the invisible form is also valid so `isValid` never be `true` because it's validating a form that so far is not rendering.

That's a feature of hook form which only validates mounted inputs. options: 

1. use schema validation which doesn't have context of mounted inputs
2. break your form into multiple which hidden inputs a separate form

**Comment by RigottiG** [comment]
> > I'm facing the same issue, I have a visible form. When it's valid I want to display the other form, the problem that is validating the invisible form is also valid so `isValid` never be `true` because it's validating a form that so far is not rendering.
> 
> That's a feature of hook form which only validates mounted inputs. options:
> 
> 1. use schema validation which doesn't have context of mounted inputs
> 2. break your form into multiple which hidden inputs a separate form

I have 2 forms on component, when the first form is valid I want to render the second form, I have a `FormProvider` wrapping both but `isValid` isn't true because is validating the second form (that's is not rendered so far)

**Comment by RigottiG** [comment]
If I remove the second form from component (delete indeed). `isValid` works fine.

**Comment by RigottiG** [comment]
```javascript
  function renderSecondCard() {
    if (!hasFilledFirstCreditCard) { //hasFilledFirstCard is setted inside of <CreditCardForm /> when isValid is true.
      return (
        <div className="disabled">
          <span className="title">Cartão 2</span>
          <div className="divider" />
          <span>Aguardando preenchimento dos dados do Cartão 1. </span>
        </div>
      )
    }

    return (
        <CreditCardForm
          installments={installments}
          onSubmit={(data) => onSubmit(data)}
          formFields={formFields2}
          isTwoCreditCards
        />
    )
  }

  return (
    <Container>
      <span className="title">Cartão 1</span>
      <div className="divider" />
      <FormProvider {...useFormReturn}>
        <CreditCardForm
          installments={installments}
          onSubmit={(data) => onSubmit(data)}
          formFields={formFields1}
          setHasFilledFirstCreditCard={setHasFilledFirstCreditCard}
          isTwoCreditCards
        />
        {renderSecondCard()}
      </FormProvider>
    </Container>
  )
```

**Comment by bluebill1049** [comment]
@RigottiG send a separate issue or question at Github discussion with reproducible codesandbox

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/158803699-d8f58f6d-0e83-4435-ba6d-906ecc2f3706.mov

<img width="1063" alt="Screen Shot 2022-03-17 at 10 55 20 pm" src="https://user-images.githubusercontent.com/10513364/158803398-01918bee-f966-4c44-b0c8-c3d2e23a9217.png">


https://codesandbox.io/s/hungry-sunset-16gkuq

updated the `codesandbox` above

1. include mode: 'onChange' as what I have suggested in the comment above and refer to the doc
2. inValid update correct when the form is valid
