### ISSUE TITLE
issue: Reset appended field

### ISSUE THREAD

**Issue by EliseyMartynov** [react-hook-form/react-hook-form#8040]
### Version Number

7.28

### Codesandbox/Expo snack

https://codesandbox.io/s/romantic-cookies-57513t?file=/src/App.js

### Steps to reproduce

1. Go to sandbox
2. Click on reset field button on a default inpit
3. Add input with append field button
4. Reset appended field with it's button
5. See console - input with `defaultValue` resets correctly to a default value. But appended field resets to `undefined`.

### Expected behaviour

Since `resetField` relies on a default value, I expected appended field to have a default value (the value with what it was appended).

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EliseyMartynov** [comment]
https://github.com/react-hook-form/react-hook-form/discussions/8039

**Comment by bluebill1049** [comment]
This may work from the UI but indeed this is an incorrect usage and the root cause of the issue.

```tsx
defaultValues: {
  testArray: [
    {
      someField: "item"
    }
  ]
}
```

Above are your field array default values.

```tsx
<button onClick={() => resetField(`testArray.${index}.someField`)}>
```

you are calling reset for the first input, yes it works, because there is the default value, but it would not work correctly for anything more than index 0 because there are no `defaultValues` which you have supplied in `useForm`.

```tsx
<button onClick={() => resetField(`testArray.${index}.someField`, { defaultValue: '1234'})}>
```

you will need to supply `defaultValue`

**Comment by EliseyMartynov** [comment]
Thank you for this reply, Bill @bluebill1049. But as I mentioned in linked discussion that I created yesterday

> And I know that we have defaultValue in the resetField method, but I guess my expected behavior will produce better DX isn't?

But I really expected that appended fields will have a default value. And this default value would be the value this field was appended initially with `append` method. And again, anyways resetting it to `undefined` is really what I did not expect at all :(

**Comment by bluebill1049** [comment]
`append` does not equally set a defaultValue. there is no `defaultValue` for the second index (in your example). perhaps you want to capture that defaultValue in the state, so when you reset the field you can supply with a `defaultValue`.  

Below are the `defaultValues` which you have supplied.

```
defaultValues: {
  testArray: [
    {
      someField: "item"
    }
    // there is no second index for defaultValue
  ]
}
```

**Comment by EliseyMartynov** [comment]
Yes, I understand that. And the fact `append` will not set default value under the hood is sad for me, especially it becomes harder to work with dynamic forms. Thank you for your time, @bluebill1049 :)

**Comment by bluebill1049** [comment]
If you think this is an important feature that we should consider, please go ahead and send a feature request. We will ping to project board, if this is a common feature that users are encountering we can potentially introduce a way to work with such use case.

**Comment by EliseyMartynov** [comment]
I guess I will do this :) At least I will understand this is problem only for me or not. That's cool, thanks!

**Comment by bluebill1049** [comment]
```tsx
const [defultValues, setDefaultValues] = useState([])

setDefaultValues((data) => {
  data[index] = value
  return data
})

append({
  value,
})

resetField(`name.${index}.value`, { defaultValue: defultValues[index] })
```

would you consider above as a workaround for now?

**Comment by EliseyMartynov** [comment]
Unfortunately, that would not work for me :( Because I'd want just reset the field without manually passing `defaultValue` to the `resetField` method.

**Comment by bluebill1049** [comment]
```

**Comment by EliseyMartynov** [comment]
Sure, it would work. But that was a minimal reproduction. In the real application there is different levels of nesting and that would hurts. I just want to keep `resetField` more abstractive from any values, that's why I don't like passing `defaultValue` to `resetField` method manually. I will describe it in my feature request
