### ISSUE TITLE
Controller - zod validation for nullable object

### ISSUE THREAD

**Issue by knoefel** [react-hook-form/react-hook-form#8046]
### Version Number

7.28.0

### Codesandbox/Expo snack

[![Edit React Hook Form Zod resolver example (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-hook-form-zod-resolver-example-forked-fqh979?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

1. Go to Sandbox
2. Click on Submit
3. Check error on address2 fields

### Expected behaviour

I'm not 100% sure this is an actual bug but it i'm out of options on how to get this working.

This is my schema:

```js
const addressSchema = z.object({
  street: z.string().min(1),
  city: z.string().min(1)
});

const baseSchema = z.object({
  name: z.string().min(1),
  address: addressSchema,
  address2: addressSchema.nullable()
});

const checkedSchema = baseSchema.extend({
  checkbox: z.literal(true),
  checkboxInput: z.string().min(1)
});

const uncheckedSchema = baseSchema.extend({
  checkbox: z.literal(false),
  checkboxInput: z.string().nullish()
});

const schema = z.union([checkedSchema, uncheckedSchema]);
```

```js
const {
    register,
    control,
    handleSubmit,
    trigger,
    formState: { errors }
  } = useForm({
    resolver: zodResolver(schema),
    defaultValues: {
      name: "",
      checkboxInput: "",
      address: { street: "", city: "" },
      address2: null
    }
  });
```
So what i'd expect is, that RHF will handle `address2` as it is nullable with a null value, right now zod will throw an error for `address2`:

![image](https://user-images.githubusercontent.com/2396344/158994064-d472293d-5654-49de-9487-3ced13c6d0ae.png)

Another strange side effect of this is, that with this setting also the discriminated union for `checkbox` isn't working anymore as it also throws, when you hit submit (it should only throw if i check the checkbox).

Thx in advance for any feedback to this!

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by knoefel** [comment]
I also wonder (and maybe this is related to this issue): what is the best way to define a default value via RHF for a `<Controller />`  field via `defaultValues`, when the schema defines for example an object for a field, but initially it is null as long as the user hasn't selected any value.

```js
const clientSchema = z.object(
  {
    id: z.string().uuid(),
    name: translationSchema,
  },
);

export const schema = z.object({
  client: clientSchema
});
```

```js
const methods = useForm({ defaultValues: { client: null } });
```
This will throw an TS error, as i can't set field initially to null. And i can't leave it out, because than RHF will complain. 😁 I'd be really interested in how to solve this.

**Comment by bluebill1049** [comment]
I would recommend you to look into the input value against your schema validation: 

```
resolver: (data, context, options) => {
  console.log(data)
  return zodResolver(schema)(data, context, options)
},
```

This is what hook form has collected as form values: 

![Screen Shot 2022-03-19 at 10 02 26 am](https://user-images.githubusercontent.com/10513364/159095181-0a26f08b-bfdb-40ec-8a56-2932a7deb0ec.png)

This is probably the reason why your schema validation occurred with an error. 

hook form resolver's concept is to bring form value and validate with the schema which you have supplied.

**Comment by bluebill1049** [comment]
> I also wonder (and maybe this is related to this issue): what is the best way to define a default value via RHF for a <Controller /> field via defaultValues, when the schema defines for example an object for a field, 

I prefer to set up `defaultValues` at `useForm` level, it's more scalable for large forms.

> but initially it is null as long as the user hasn't selected any value.

I would lean toward native input default value which is empty string, instead of `null`

**Comment by knoefel** [comment]
Thx for your reply!

So my question was how to handle this with `<Controller />` not with native inputs. So for example using MUI's `DatePicker` or `Autocomplete`, the initial value should be `null`, as the user has to select a date or an option from the `Autocomplete`. So in this scenario i can't use an empty string as the default value. But in my schema i define it either as a `Date` type or for the `Autocomplete` example i'd define it as an object.

**Comment by Moshyfawn** [comment]
Does [this](https://codesandbox.io/s/distracted-brook-k9lvr5?file=/src/Form.tsx) help, @knoefel

**Comment by bluebill1049** [comment]
The issue presented in the codesandbox is that `address 2` actually registers a group input, an object of street and city, which would provide an object of nulls instead of a nullable value which is way failed in the schema validation. That's not a problem with Controller, you can provide any defaultValue other than `undefined`.

**Comment by knoefel** [comment]
> Does [this](https://codesandbox.io/s/distracted-brook-k9lvr5?file=/src/Form.tsx) help, @knoefel

@Moshyfawn Thanks for helping out, but unfortunately it's not a working solution. In your example you're defining `field` as `nullable`, so it's possible to submit the form without selecting a value for `fieldSchema`. The same goes for the `date` field. But my requirement is that those fields are indeed required and not `nullable`. It's only for the initial defaultValue that i need to set it. You can reproduce this by removing the `nullable` method from the `date` field, then TS will complain.

[![Edit dazzling-https-r760dk](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dazzling-https-r760dk?fontsize=14&hidenavigation=1&theme=dark)

Of course i could do something like this:

```typescript
const defaultValues: DefaultValues<FormValues> = {
  field: null,
  date: new Date()
};
```
But from an UX perspective or even with a concrete requirement of leaving the field initially empty, i don't know how to handle such case when RHF needs to have a defaultValue for every `<Controller />` field. For the other field in your example it's even more difficult, as i would need to know one of the options to pass it to `defaultValues`. Besides that it should also be possible to leave it empty when the user first loads the form.

**Comment by bluebill1049** [comment]
> For the other field in your example it's even more difficult, as i would need to know one of the options to pass it to defaultValues. Besides that it should also be possible to leave it empty when the user first loads the form.

I haven't looked into your codesandbox above just yet, but I don't agree with the statement above. you should always provide and be able to provide an initial state/defaultValue for your input. That's applicable for either controlled or uncontrolled inputs. That's not a problem created by react hook form, that's something users need to solve for their component value requirement.

**Comment by bluebill1049** [comment]
```
const defaultValues: DefaultValues<FormValues> = {
  field: null,
  date: new Date() // date: null
};
```

as long as your type definition is nullable and in your case with your Zod schema.

**Comment by knoefel** [comment]
> I haven't looked into your codesandbox above just yet, but I don't agree with the statement above. you should always provide and be able to provide an initial state/defaultValue for your input. That's applicable for either controlled or uncontrolled inputs. That's not a problem created by react hook form, that's something users need to solve for their input component value as a requirement. A form library can't assume a default value for any of the inputs.

I think you misunderstood me, sorry if i wasn't clear enough. I totally agree with you, that it is mandatory to provide a default value for every field. But in case of MUI's `<Autocomplete />` and `<Datepicker />` i need to use `null` as the initial default value, because it's the only "empty value" i can use that RHF will allow while using `<Controller />`. I can't use `undefined`, and any other primitive value will get thrown by the zod/yup schema.

I also agree with you that this is absolutely no fault or problem of RHF, it's more like i want to know how i can solve this situation? So once again my requirements:

1. zod (or yup) schema where i have a required date field/autocomplete field with an object as value once the user selects one
2. defaultValues on useForm level, for both fields a value which represents an empty/uninitialised state

I find it really strange that no one else has encountered this problem, so it's also possible that i'm doing/thinking something completely wrong. 😄

**Comment by knoefel** [comment]
> you are setting `address2` as null, but then you are rendering two inputs.

Ok, thx. My understanding was, that if i set the default value for `address2` to `null` and never type anything in those related fields, then on submit `address2` would still be `null`. So when RHF initialises the form, it will take the `null` value i set for `address2` and apply it to the subfields `street` and `city`?

**Comment by bluebill1049** [comment]
> Ok, thx. My understanding was, that if i set the default value for address2 to null and never type anything in those related fields, then on submit address2 would still be null. So when RHF initialises the form, it will take the null value i set for address2 and apply it to the subfields street and city?

That's not going to be the case, since those two inputs will provide null values as an object.  

```tsx
register('address.a', { value: null })
register('address.b', { value: null })
```

basically above.

**Comment by bluebill1049** [comment]
> 1. zod (or yup) schema where i have a required date field/autocomplete field with an object as value once the user selects one

This is an incorrect understanding part. Validation mode can detect whether the user is interacting with this input by trigging touched fields, however, this is not responsible with validation schema. Schema/rules should only take care if the value match xxx or not.

> defaultValues on useForm level, for both fields a value which represents an empty/uninitialised state

i have answered above.

**Comment by bluebill1049** [comment]
for object nullable object the following example hope will make things clearer:

```tsx
const { onChange, value } = useController({
  defaultValue: null
})

return <>
  <input name="A" onChange={() => { onChange(value ? { ...value, A: 'data' } : { A: null, B: 'data' }) }} />
  <input name="A" onChange={() => { onChange(value ? { ...value, B: 'data' } : { B: null, A: 'data' }) }} />
<>
```

**Comment by bluebill1049** [comment]
@knoefel is the above make more sense?

**Comment by knoefel** [comment]
Thanks for your input! Unfortunately i'm having a bit of trouble understanding it. Just to get some feedback from you on this: is this really such a rare case wanting a required controlled field defined via yup/zod schema and just leave it empty before the user filled out the form? So again, i don't think it's a failure of RHF, but i also don't think it's a failure of the schema lib either. Because looking from the schema perspective, i define for example that field "a" must have a selected value/option in the form of `{ id: "", name: "" }`, when the user hits the submit button, otherwise throw an vaildation error. But i don't expect that field "a" must have that value when i initialise the form. So in this situation i haven't got many options on how to get that solved.

In the end i decided to switch from zod to yup (luckily it's only a very small internal project) and got it working by using yup's `default` method although it still feels a bit hacky.

I would be really interested how you would implement the described requirements above using RHF, TS and yup/zod. But i totally understand that you have enough other tasks to do preparing v8 of RHF, so i guess i will just close this issue. It's probably also more a discussion than an issue, therefore  sorry for using the wrong spot.

As always thanks for taking the time and keep up the great work!!

**Comment by DannyLingard** [comment]
@knoefel @bluebill1049 

I am facing a similar issue and also curious as to the best approach. I myself thought this would be a common and wondering what the best approach is.

I face the issue with Dates (using MUI datepicker) and Numbers via Currency Input (using react-number-format and Mui TextField). Let's summarize the issue as covering 2 areas:

- Storing an 'empty' value in a type that differs from the target/schema data type and the recommended native input type.
- UX forced value input vs default values

For demo purposes. imagine a create/update form is managing a future payment date with an amount(number) field and a paymentDate(date) field. For UX reasons, when in create mode, I want forced value input, not 0 and new Date(). When in update mode, these will be pre-existing values (default values). During the form lifetime, previously valid values can revert to empty values (invalid), falling back to forced value input.

If I widen the Schema typings to allow e.g | null, the onSubmit method payload includes the null types. If I only widen the defaultValues typings, it's incompatible with the Schema due to | null.

The problem with widening Schema types is technically, onSubmit shouldn't have the null types given correct validation logic. If I need to manage this then I'm arguably re-validating.

Default values are recommended to always be provided, however the only way round I can see is to use yup .default(null) and not provide the field(s) to defaultValues. 

Is there any other way?

I can get around this by providing 0 and new Date() as initial defaultValues and incapsulating empty state in yup but this provides a different UX than what I'm after.

Awesome library and thanks for all your hard work.
