### ISSUE TITLE
issue: Uncontrolled disabled checkbox assigned the wrong defaultChecked

### ISSUE THREAD

**Issue by Moshyfawn** [react-hook-form/react-hook-form#8050]
### Version Number

7.28.0

### Codesandbox/Expo snack

https://codesandbox.io/s/strange-tess-cltbts?file=/src/App.tsx:250-255

### Steps to reproduce

1. Go to [CSB](https://codesandbox.io/s/strange-tess-cltbts?file=/src/App.tsx:250-255)
2. See the second checkbox looks unchecked despite `defaultChecked: true`

There seems to be a particular combination of conditions that cause the issue:
- The "problematic" checkbox **has to have sibling checkboxes** in a group and **has to be disabled**
- The first checkbox **can have `defaultChecked` `true` or `false`** but **has to be not disabled**
- The last checkbox **has to have `defaultChecked: false`** and **can be either enabled or disabled**

For more context see #8049

### Expected behaviour

Disabled checkbox with `defaultChecked: true` is checked

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
cc @antonsamper

**Comment by Moshyfawn** [comment]
It happens with setting `defaultChecked` **and** if `defaultValues` on `useForm` hooks are provided.

A [CSB](https://codesandbox.io/s/unruffled-elgamal-w3q6p6?file=/src/App.tsx:353-358) with defaultValues on `useForm` hook

**Comment by Moshyfawn** [comment]
Just remembered that setting `disabled: true` sets the input's value to `undefined`. So, the issue might be connected to some logic with handing disabled inputs. Tho, keep in mind, that it works properly if the conditions described in the issue body haven't been met.

**Comment by bluebill1049** [comment]
thanks @Moshyfawn will look into it.

**Comment by antonsamper** [comment]
Thanks for the quick fix @bluebill1049

**Comment by r1y4h** [comment]
I have a similar issue with uncontrolled disabled checkbox.

```
<input
          {...register("user.selected")}
          type="checkbox"
          disabled
          defaultChecked={defaultChecked}
/>
```

When disabled is set to true, the value of "user.selected" is undefined, upon submit. 
Regardles if "defaultChecked" is true or not.
No other sibling checkboxes.
No default values. Also tried with default value.

I have updgraded to v7.28.1 where the fixed is supposed to be.
Also upgraded to latest 7.31.1

**Comment by joriswitteman** [comment]
Same issue here. My workaround is to add another checkbox with the same values, but not disabled, with `display: none`. Far from ideal.

**Comment by Moshyfawn** [comment]
Who ever encounters whatever problem, please, don't just spam "I have the same issue". The mentioned issue has been resolved as per it's status and "same" doesn't help debug it at all.

I'd recommend creating a new issue with all the repro steps, minimal codesandbox repro and the lib version. It would actually help a lot. Bonus points for referencing this issue as related
