### ISSUE TITLE
SetFocus with optional preventScroll: true

### ISSUE THREAD

**Issue by davidkutas** [react-hook-form/react-hook-form#8057]
Feature request:
When you do `.focus` with the native browser API you have the following option: `.focus({preventScroll:true});` this prevents the browser to immediately scroll to the location where the input field is.

I think we should have an API that adds the option of `preventScroll` like this: setFocus("name", { preventScroll: true })

More info: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus

What do you think?

**Comment by Moshyfawn** [comment]
Do you mean to focus the input with an error but not scroll to it?

**Comment by Moshyfawn** [comment]
Thank you for the feature request. I've assigned it to the project board.
I'm gonna close the issue. Feel free to provide the info in this this thread.
