### ISSUE TITLE
add support for superstruct

### ISSUE THREAD

**Issue by hemedani** [react-hook-form/react-hook-form#806]
**Is your feature request related to a problem? Please describe.**
related to validation schema 

**Describe the solution you'd like**
```javascript
import React from 'react'
import ReactDOM from 'react-dom'
import { useForm } from 'react-hook-form'
import { struct } from 'superstruct'

const SignupSchema = struct({
  name: 'string',
  age: 'number',
})

export default function App() {
  const { register, handleSubmit, errors } = useForm({
    validationSchema: SignupSchema
  })
  const onSubmit = data => { console.log(data); }
  console.log(errors)

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input name="name" ref={register} />
      <input type="number" name="age" ref={register} />
      <input type="submit" />
    </form>
  )
}
```

**Describe alternatives you've considered**

**Additional context**
just support other validation schema lib other than yup

**Comment by bluebill1049** [comment]
there is a PR for custom validation: you can upvote this PR, when there is enough vote. we will consider merging into master

https://github.com/react-hook-form/react-hook-form/pull/529
