### ISSUE TITLE
issue: Errors don't update with useFieldArray

### ISSUE THREAD

**Issue by danielnakamashi** [react-hook-form/react-hook-form#8069]
### Version Number

6.15.8

### Codesandbox/Expo snack

https://codesandbox.io/s/async-pond-kwzei0?file=/src/App.js

### Steps to reproduce

1. Click "append" button
2. Click "submit" button
3. You should see error messages below text fields
4. Click "No last name" checkbox
5. Error below last name should disappear (not happening)
6. Click "submit" button
7. Error below last name disappears

### Expected behaviour

Validation in one field that depends on another field, should trigger error update.
As you can see in console, the validation runs (`validation errors`) but it doesn't update the `errors` object.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
could you upgrade to the latest v7?

**Comment by bluebill1049** [comment]
> Error below last name should disappear (not happening)

Schema validation focus on the field level for error reporting. Parent level error look is only limited to the direct parent level that is applicable for components such as group checkboxes.

https://react-hook-form.com/api/useform

i think you may need to use `trigger` API for dependent validation.

**Comment by danielnakamashi** [comment]
I've upgraded to v7 and added `trigger` to `onChange` event of checkbox but it didn't work. :(

**Comment by bluebill1049** [comment]
![Screen Shot 2022-03-23 at 8 01 59 pm](https://user-images.githubusercontent.com/10513364/159662151-40054aa4-c07e-4be8-b2a3-2fb78a0d8d54.png)

I think the structure of your errors object is a bit out of shape. could you correct those first? `trigger` should be able to update the entire form or associated fields.

**Comment by danielnakamashi** [comment]
It's working now :). Thank you!
