### ISSUE TITLE
mode without ref

### ISSUE THREAD

**Issue by binjospookie** [react-hook-form/react-hook-form#807]
**Describe the question?**
Hi! I try to use `useForm` with `mode: 'onBlur'` without `ref={register}`.
The problem is that `errors` object from `useForm` includes error  immediately (not after `onBlur`).
Is it possible to achive behaviour like with `ref={register}` but with `register("inputName",{...})` in my case ?

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-errormessage-55whl

**Comment by binjospookie** [comment]
My goal is to hide error for current active (focused) field from `errors`.

**Comment by dawidvdh** [comment]
Trying to see if I can migrate from final-form to this and also really missing an active flag for fields, is there any plans for this feature?

**Comment by bluebill1049** [comment]
There is @dawidvdh https://github.com/react-hook-form/react-hook-form/issues/1312 Final Form is awesome by the way. ❤️
