### ISSUE TITLE
FormState not being updated as expected

### ISSUE THREAD

**Issue by AndrewOttavianoAbb** [react-hook-form/react-hook-form#8070]
### Version Number

7.28.0

### Codesandbox/Expo snack
https://codesandbox.io/s/reverent-ramanujan-gn9wsn

### Steps to reproduce

1. See the codesandbox above. Basically create a project where we render a form, use a `FormProvider`, use yup and the `yupResolver` to validate the form (with one field marked required), and make the inputs custom components.
2. Add this `useEffect` to catch the `formState` updates:
```js
useEffect(() => {
  onStateUpdate(formState);
}, [onStateUpdate, formState]);
```
3. Do not enter anything in the form and click the submit button.

### Expected behaviour

The `useEffect` is triggered when the submit button is clicked and the callback logs the data to the console. I would expect to see the errors field filled out (since the field marked required is empty) so I could add messages to the form.

Instead, nothing is logged to the console and focus is shifted to the empty required field. The focus shift is a nice thing, but I want to be able to add my own error message on top of this feature.

**Note** If I change `formState` to `formState.errors` and update the dependency array accordingly, it works as expected. It is specifically called out in the docs not to use a sub-property like `.errors` in the dependency array. So I'm not entirely sure if this is a misunderstanding of how `useEffect` works on my part or if it is a bug in the library. I would prefer not individually passing all the properties to this callback and calling out every property in the dependency array; that would make the code very brittle. In any case, I would like to pass the _whole_ state to the consumer when changed and would appreciate help to that end.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
I don't think there's any workaround for you other than to destruct all of the `formState` values with the current RHF design.

The `formState` is a `Proxy`; you need to read each state you want to subscribe to.

**Comment by AndrewOttavianoAbb** [comment]
Ah, sad day. A little curious why the Proxy object but I guess that makes sense why my thing wasn't working. Thank you for the quick reply! Please keep me posted if this changes.

**Comment by Moshyfawn** [comment]
They way `formState` setup is an optimization measure to avoid unnecessary re-renders and only subscribe the component to the `formState` values changes it actually is interested in _(subscribed to)_.

So, that way
```js
const { isDirty } = formState
```
would cause the component re-render only when the isDirty state is changed, not the other once, like `dirtyFields`, `isSubmitting` etc.

**Comment by AndrewOttavianoAbb** [comment]
> They way `formState` setup is an optimization measure to avoid unnecessary re-renders and only subscribe the component to the `formState` values changes it actually is interested in _(subscribed to)_.
> 
> So, that way
> 
> ```js
> const { isDirty } = formState
> ```
> 
> would cause the component re-render only when the isDirty state is changed, not the other once, like `dirtyFields`, `isSubmitting` etc.

Ah I see. I am unfamiliar with the internals of the how the library handles re-renders. I also understand what you are getting at: it essentially forces the user to be smart about how they deal with the data. However, I think this is assuming the consumer whishes to use the data (which could cause a re-render) in the same component they called `useForm`. I am creating a reusable component that abstracts away the form library and they may use the `formState` data and cause the form to re-render, they may use the data to cause something else to update, or they may not care and just want the response through handle submit. As a library owner, I can't dictate that and thus want to provide flexibility. So this approach, while I understand it, requires me to make my code messier (making my `useEffect` longer to listen to every field but not directly causing a re-render) while potentially nullifying the optimization you guys put in place. I honestly don't know how to solve this (besides wrapping things in my own Proxy which I'm not keen on doing and doesn't simplify my code), but if you come up with a solution, I'm all ears :)

Also, this optimization feels a little inconsistent w/ the rest of the API. It's not a big deal, but take the `handleSubmit` call back for example. It simply returns an object with my fields and data when the form is submitted. It just seems a bit weird to have to handle the `formState` object differently ya know? Not saying this is a reason to change what you have, just feels a little weird 🤷🏻‍♂️

**Comment by Moshyfawn** [comment]
> I think this is assuming the consumer wishes to use the data _(which could cause a re-render)_ in the same component they called `useForm`

You don't necessarily need to use `formState` at the root form level _(where the `useForm` hook is called)_. There's [a `useFormState` hook](https://react-hook-form.com/api/useformstate) available to access the form's state down at some child component level.

As an example, working on a project big on forms, I've created a `SubmitButton` component that utilities `useFormState` hook, which subscribes to `isDirty` to determine if it should be disabled. That way, only the "interested" component re-renders on `isValid` change and not the whole form.

As to listing the whole `formState` related deps array _(or creating a Proxy)_, while I definitely see your pain point, I can't say I can come up with a lot of use-cases where I'd want to watch the whole `formState` and react to it _(`useEffect` side-effects)_, except, maybe, logging?.. Please, feel free to prove me wrong _(it's been a long work day :P)_. From the RHF perspective, granular usage of `formState` values is more common to include this optimization.

> Also, this optimization feels a little inconsistent w/ the rest of the API.

I can see that. A note is actually sitting in my "thoughts" list to discuss with @bluebill1049 a possibility of having some sort of `getFormState` function instead of the `formState`, which can take, say, a list of `formState` values keys to subscribe to the corresponding states like:
```js
const { getFormState } = useForm()

const [isValid, errors] = getFormState(["isValid", "errors"])
```
That way the API's gonna become more aligned with what `watch` API looks like.

Development is all about trad-offs _(or so I think)_. Whitelist RHF went for the `Proxy` approach to try optimize the most common form use-cases, feedback like yours really helps to get the full picture and consider options ;)

**Comment by AndrewOttavianoAbb** [comment]
>You don't necessarily need to use formState at the root form level (where the useForm hook is called). There's [a useFormState hook](https://react-hook-form.com/api/useformstate) available to access the form's state down at some child component level.

Will check out. Thanks!

> As to listing the whole formState related deps array (or creating a Proxy), while I definitely see your pain point, I can't say I can come up with a lot of use-cases where I'd want to watch the whole formState and react to it (useEffect side-effects), except, maybe, logging?.. Please, feel free to prove me wrong (it's been a long work day :P). From the RHF perspective, granular usage of formState values is more common to include this optimization.

The main one I was thinking of would be navigation. At my company, we create a lot of wizard-like forms where we are jumping from page to page, each w/a form on it. It doesn't make a ton of sense to have a submit button for each form on those pages because there's still more to fill out (we are collecting that into higher state as we go). Nevertheless, the dev building the form will want to know if the next button can be enabled, which is dependent on the form being valid. I'm sure there's probably a few more, can't think of them either rn.

> I can see that. A note is actually sitting in my "thoughts" list to discuss with @bluebill1049 a possibility of having some sort of getFormState function instead of the formState, which can take, say, a list of formState values keys to subscribe to the corresponding states like:
```js
const { getFormState } = useForm()

const [isValid, errors] = getFormState(["isValid", "errors"])
```

❤️

**Comment by AndrewOttavianoAbb** [comment]
Also, one side note that is completely unrelated to this issue but still about the api, could you all add a check for duplicate field names. If I add two inputs w/the same field name, I'd expect an exception to be thrown, instead I'm writing code like this

```js
  const checkName = (inputName: string) => {
    if (componentNames.includes(inputName)) {
      // This is intened to not be a case in production code, it is supposed to alert the
      // developer to this issue because we don't have any way to resolve it.
      throw new Error(
        `The input with name: ${inputName} already exists in this form.`,
      );
    }

    componentNames.push(inputName);
  };
.....
  React.Children.forEach(children, (child) => {
    if (React.isValidElement(child) && child.props.name) {
       checkName(child.props.name);
     }
   });
```

Which is fine, that was a fun little piece to write, buuuut also seems like something that should probably be a 1st class api.

**Comment by bluebill1049** [comment]
Thanks, @Moshyfawn for looking into this. This is expected behavior since we batch update form state update.
