### ISSUE TITLE
issue: Controller's shouldUnregister prop is mutating defaultValues object

### ISSUE THREAD

**Issue by TheMoonDawg** [react-hook-form/react-hook-form#8071]
### Version Number

7.28.1

### Codesandbox/Expo snack

https://codesandbox.io/s/new-rain-wgxvv1?file=/src/Form.js

### Steps to reproduce

The `shouldUnregister` prop on `Controller` is mutating the `defaultValues` object used to instantiate the form.

1. Click `Toggle Form` to unmount the form.
2. Click it again to render the form.
3. Notice that `firstName` is no longer populated AS WELL as the `defaultValues` object being mutated in the console.

Note: The `shouldUnregister` flag on `register` does not produce this bug (as noted in the code sandbox).

### Expected behaviour

`Controller` should not be mutating the object being passed into `defaultValues`.

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/usecontroller

>  shouldUnregister | boolean = false |   | Input will be unregistered after unmount and defaultValues will be removed as well.
