### ISSUE TITLE
Module not found: Can't resolve 'react-hook-form' in '/opt/buildhome/repo/components'

### ISSUE THREAD

**Issue by konradbjk** [react-hook-form/react-hook-form#8072]
### Version Number

7.28.1

### Codesandbox/Expo snack

NA

### Steps to reproduce

While trying to serve the page using cloudflare pages I receive the error
```
Module not found: Can't resolve 'react-hook-form' in '/opt/buildhome/repo/components'
```
Full message
```
19:51:02.767 | info  - Checking validity of types...
-- | --
19:51:05.378 | info  - Creating an optimized production build...
19:51:09.732 | Failed to compile.
19:51:09.733 |  
19:51:09.733 | ./components/OrderForm.jsx
19:51:09.733 | Module not found: Can't resolve 'react-hook-form' in '/opt/buildhome/repo/components'
19:51:09.733 |  
19:51:09.733 | Import trace for requested module:
19:51:09.733 | ./pages/index.js
19:51:09.733 |  
19:51:09.733 |  
19:51:09.733 | > Build failed because of webpack errors
19:51:09.755 | Failed: build command exited with code: 1
```

I am using YARN 1.22.17 and node 17.0.1

All dependencies
```json
  "dependencies": {
    "next": "12.0.8",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-hook-form": "^7.28.1"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.2",
    "eslint": "8.7.0",
    "eslint-config-next": "12.0.8",
    "postcss": "^8.4.5",
    "tailwindcss": "^3.0.15"
  },
  "version": "0.0.0"
}
```

### Expected behaviour

The build should pass and page work

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
We'd appreciate it if you'd give us some pointers to what's your Cloudflare Pages setup looks like as well as some actual minimal app reproduction sandbox to try deploy to CP. I don't think we can just start guessing all the variables here

**Comment by bluebill1049** [comment]
This is not an issue with hook form library.

**Comment by konradbjk** [comment]
Thank you for following up. I will provide sample app. 

I could not find any indication that `react-hook-forms` require special npm registry. I understand that there is no limit (like backend only) for this module?

**Comment by bluebill1049** [comment]
It's a public module and without any restriction.

**Comment by konradbjk** [comment]
Thank you for following up. I will provide sample app. 

I could not find any indication that `react-hook-forms` require special npm registry. I understand that there is no limit (like backend only) for this module?

**Comment by TheMoonDawg** [comment]
Yeah, this sounds like more of an issue with your build pipeline than the library.

**Comment by konradbjk** [comment]
You were right guys. I did a dummy commit again of the code + `yarn.lock` and it worked.

For anyone with the similar issue. Remove the package and add it again. Then push the code (+ `packages.json` and `yarn.lock`) again. This has solved the issue for me.
