### ISSUE TITLE
React 18 strict mode useEffect running twice lead to`fieldState` is delayed when using `useController`

### ISSUE THREAD

**Issue by mwskwong** [react-hook-form/react-hook-form#8076]
### Version Number

7.28.1

### Codesandbox/Expo snack

https://codesandbox.io/s/floral-wood-lkpd25

### Steps to reproduce

1. Create a component using `useController`
2. To best visualize the issue, set the field to `required` and output a message when error is encountered
3. Create a form as usual

WIth the field empty, when the submit button is clicked, the field is focused as expected, but the error state is not updated and the error message is not displayed.

When form `mode = onChange`, clearing the field does NOT trigger the error. The error is displayed in the next cycle.

e.g. Field content: _empty_ -> a  -> _empty_ (error should be triggered here, but it doesn't) -> a (error is triggered here)

Only seem to affect DEV build only.

### Expected behaviour

WIth the field empty, when the submit button is clicked, the error state will be updated, causing the error message to be displayed

When form `mode = onChange`, clearing the field should trigger the error state and the error message should be displayed.

### What browsers are you seeing the problem on?

Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mwskwong** [comment]
I should mention that this issue is encountered when using React 18 RC.

**Comment by bluebill1049** [comment]
although we are not officially support react 18 just yet, this issue is due to react 18 strict mode running `useEffect` twice. I will patch this issue.
