### ISSUE TITLE
Active in formState

### ISSUE THREAD

**Issue by binjospookie** [react-hook-form/react-hook-form#808]
My goal is to exclude error of current active (focused) field from `errors` (with filter, for example).

Maybe it's possible to get current active form element's name (like `Active` from https://final-form.org/docs/final-form/types/FormState) ?

**Comment by bluebill1049** [comment]
can you provide a better use case for such `formState`?  we will then consider to include such a feature.

**Comment by binjospookie** [comment]
It could be useful for taking value of active field like `getValues()[formState.active]`. Or add logic based on this property (show pro-active instructions for example).

**Comment by binjospookie** [comment]
Also it can simplify `setValue`: `setValue(formState.active,someValue,true)`

**Comment by bluebill1049** [comment]
Some valid points and some I think there are alternative by using existing API. I will set this to be waiting for vote and add to our back log.

**Comment by bluebill1049** [comment]
<img width="358" alt="Screen Shot 2020-01-10 at 9 38 22 am" src="https://user-images.githubusercontent.com/10513364/72110691-f65dc580-338c-11ea-94ee-18ab3f1d0c33.png">

will keep an eye on it.

**Comment by bluebill1049** [comment]
when there are enough user request for this feature, i will looking into it @binjospookie. now that the library is pretty stable and i am bit more careful in terms of new API get introduced and hope you understand too.
