### ISSUE TITLE
ArrayPath type returns invalid types

### ISSUE THREAD

**Issue by RobertVillalba** [react-hook-form/react-hook-form#8083]
### Version Number

7.28.1

### Codesandbox/Expo snack

https://codesandbox.io/s/hardcore-khorana-17i6b7?file=/src/index.ts:52-173

### Steps to reproduce

1. Hover over the type `AP1` and see that resulting type is `never`

### Expected behaviour

ArrayPath should return paths that have array values

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
It's related to the fact that RHF doesn't support flat arrays. [From RHF docs on `useFieldArray`](https://react-hook-form.com/api/usefieldarray#rules):
> Does not support flat field array.

Your example of `T1` type
```ts
type T1 = { a: number; b: string[] };
```
implies that your field array will be of type `string` and RHF only supports an `object` type _(not flat array)_.

You can see it works as expected if you provide a type of array of `object` with properties
```ts
type T1 = { a: number; b: { name: string }[] };
```

**Comment by RobertVillalba** [comment]
Ah got it thank you very much for that explanation!
