### ISSUE TITLE
issue: reading `formState` in component causes `watch` / `getValues` to not update when `reset` is called

### ISSUE THREAD

**Issue by stbowen** [react-hook-form/react-hook-form#8087]
### Version Number

7.28.1

### Codesandbox/Expo snack

https://codesandbox.io/s/blissful-goldberg-y7sefc?file=/src/App.js

### Steps to reproduce

1. The form has two fields: firstName and lastName.  The first name is "darth" by default and the last name is "vader" by default.
2. Clicking the "reset" button will call `reset`, setting the values to first name "boba" and last name "fett"
3. The values returned by `getValues` or `watch` do not update when `reset` is called.

### Expected behaviour

I would expect subscriptions made with `watch`, or values read with `getValues` to update after the form's values have been changed with `reset`.

Note that this expected behavior works, provided that we don't read the `formState` from `useForm`.  By simply commenting out the two lines:
```
// const { formState } = methods;
// const { isValid } = formState;
```
the values returned by `getValues` and `watch` will be updated when `reset` is called.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is expected behavior. 

After `reset` API is invoked, all input references including subscription will be reset and removed until the next render or user interaction.

1. watch (subscribe)
2. reset (remove subscribe)

**Comment by stbowen** [comment]
@bluebill1049 Thanks for the very quick response!  Is there any way you could add this to the documentation for `reset` method?  Or is this feature already documented, and I missed it somehow?

**Comment by bluebill1049** [comment]
> Reset the entire form state, fields reference, and subscriptions. There are optional arguments and will allow partial form state reset.

Execution orders always matter, we are using `formState` as `proxy` to detect subscriptions.
