### ISSUE TITLE
[4.4.7] returns watch value differently after setValue

### ISSUE THREAD

**Issue by github0013** [react-hook-form/react-hook-form#810]
**Describe the bug**
setValue after reset will break watch values.

**To Reproduce**
1. push reset
2. push setValue
3. see the console

**Codesandbox link**
https://codesandbox.io/embed/rhf-watch-and-setvalue-wcc1m

**Expected behavior**
setValue should not break watched values.

**Screenshots**
## 4.4.6
![](https://spectrum-proxy.imgix.net/https%3A%2F%2Fi.gyazo.com%2F7d4d2895582ab19088402db67d58c2d4.png?expires=1577664000000&ixlib=js-1.4.1&s=5616e8064c0de7a8c8a137216910c91e)

## 4.4.7
![](https://spectrum-proxy.imgix.net/https%3A%2F%2Fi.gyazo.com%2Fea27ef8e178933dc42544cf54fff78b1.png?expires=1577664000000&ixlib=js-1.4.1&s=f22d851d4c398b704a0bf276c08eb068)

**Comment by bluebill1049** [comment]
thanks @github0013

**Comment by bluebill1049** [comment]
patched https://github.com/react-hook-form/react-hook-form/releases/tag/v4.4.8
