### ISSUE TITLE
issue: reset is not working correctly with object values

### ISSUE THREAD

**Issue by SafaAlfulaij** [react-hook-form/react-hook-form#8101]
### Version Number

7

### Codesandbox/Expo snack

https://codesandbox.io/s/usecontroller-forked-9l651i

### Steps to reproduce

1. Open console
3. Notice first render shows default value: `{}`
4. Then after a while (2000ms), the value is `undefined`.

### Expected behaviour

The value would be as passed, a simple JS object:
```js
{
      First: "First",
      Last: "Last"
}
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
you are using the beta version.

**Comment by SafaAlfulaij** [comment]
Actually, I'm using 7.21.2 and this seems to be fixed now.
Thanks!
