### ISSUE TITLE
issue: id in fieldArray is omitted at a later stage

### ISSUE THREAD

**Issue by SafaAlfulaij** [react-hook-form/react-hook-form#8103]
### Version Number

7.28.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-2lqtl7?file=/src/index.js

### Steps to reproduce

1. Open console
3. Notice the first watch output: array items contain an `id` attribute
3. The second watch output (why does it occur anyway?): array items _doesn't_ contain an `id` attribute

Note: Clicking append (only once for testing) adds a new item, with an `id`, and can be observed in the watch output.

### Expected behaviour

The array item ids are retained as mentioned in the version notes: https://github.com/react-hook-form/react-hook-form/releases/tag/v7.23.0

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
![Screen Shot 2022-03-27 at 4 51 27 pm](https://user-images.githubusercontent.com/10513364/160268634-43edf330-37e9-4dff-bbee-7c59fb102894.png)

refer to the doc for generated ID

**Comment by SafaAlfulaij** [comment]
But my data needs an id that is consistent with the back-end data, that's why I need the passed id again to send the data to the back-end.

**Comment by Moshyfawn** [comment]
RHF needs to retain it's internal array field ID to track the position and the values of the fields.

If you need your stable IDs you get from BE, you might wanna pass the `keyName` prop with a custom key name you want RHF to use to store it's internal field GUIDs.

```jsx
const fieldArray = useFieldArray({ keyName: "key" })
...
// INFO: notice the use of an additional key prop instead of id
// This way your BE IDs haven't been overriden 
fields.map(field => <input key={field.key} />)
```

**Comment by SafaAlfulaij** [comment]
I'm aware of that totally, and understand it. My issue is that RHF is _stripping_ the id from the final output (in some situations!)
Please note how the first `console.log` is giving the ids, while the second is not.

My thinking says that if the user is providing an id by themselves, then it should be retained and not overridden whatsoever.

And:
> Name of the attribute with autogenerated identifier to use as the key prop. **This prop is no longer required and will be removed in the next major version.**

**Comment by SafaAlfulaij** [comment]
Bumping this.
I'd like to know how can I keep the id persistent and tell RHF to not remove it.

**Comment by Moshyfawn** [comment]
If you pass the `keyName` different from `"id"`, RHF will strip the prop with name set in `keyName` `onSubmit` instead of your `id`. See [this CSB](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-s1lxym?file=%2Fsrc%2Findex.js)
Once again, RHF needs **some** field prop to store it's **internal** ids. It's nothing to do with your DB ids or whatever. The default prop name for internal RHF ids is `"id"` and you can override it with the `keyName` prop. If you set it to something like `"key"`, you will get your desired result.

**Comment by SafaAlfulaij** [comment]
Alright, this seems good enough.

Now my next question, what about the text saying that `keyName` prop will be removed in next major release?
How would I tell RHF to not remove my `id` prop?

**Comment by bluebill1049** [comment]
please show a bit of appreciation here... I see no "thank you" or any sort of appreciation rather than just question after another question. @Moshyfawn is kind enough to answer your question in his own free time. Yes, in your world open-source is maintained by robots.
