### ISSUE TITLE
Form Wizard with Radio Buttons Example

### ISSUE THREAD

**Issue by Doomd** [react-hook-form/react-hook-form#811]
I'm sorry if I'm posting this in the wrong section...but I only had 3 choices and none seemed to fit...

To the point: I amended the example code for the "Wizard Form/Funnel" that you have listed on your ["Advanced Usage" page](https://react-hook-form.com/advanced-usage#WizardFormFunnel).

1.  I've included a radio button group that keeps its state between pages and loads...just like the text inputs. [It took me a few hours to figure that one out](https://stackoverflow.com/questions/59674845/how-do-i-store-the-state-of-radio-groups-in-react-using-react-hook-form) (I'm fairly new to React), so I'm sure others might benefit from the example configuration.

Here's the [Original CodeSandBox url,](https://codesandbox.io/s/form-wizard-pages-kkg7m) and here's [My Amended Version with Radio Buttons](https://codesandbox.io/s/react-hook-form-wizard-form-with-radio-buttons-whvf7)

2.  There's no mention of the Wizard Form/Funnel in the [ code examples page](https://github.com/react-hook-form/react-hook-form/tree/master/examples). It should probably be included there as multi-page form functionality is fairly popular. In fact, there's a few more unmatching/missing example code links between the official website, and the github example code page.

3. If you need help with documenting that aforementioned page(s) with better descriptions of what each example actually does, and which API's they use, I'd be happy to help. It's very minimally instructive and/or confusing to a newbie as it stands...

Cheers,
BC

**Comment by bluebill1049** [comment]
> 2\. If you need help with documenting that aforementioned page(s) with better descriptions of what each example actually does, and which API's they use, I'd be happy to help. It's very minimally instructive and/or confusing to a newbie as it stands...

Yes, please! it's open-sourced and everyone can help.

**Comment by bluebill1049** [comment]
> 1. I've included a radio button group that keeps its state between pages and loads...just like the text inputs. [It took me a few hours to figure that one out](https://stackoverflow.com/questions/59674845/how-do-i-store-the-state-of-radio-groups-in-react-using-react-hook-form) (I'm fairly new to React), so I'm sure others might benefit from the example configuration.

probably more of React question.
