### ISSUE TITLE
issue: Using optional (?) number properties, with valueAsNumber results in NaN being returned for empty fields

### ISSUE THREAD

**Issue by Nikola-Milovic** [react-hook-form/react-hook-form#8110]
### Version Number

7.26.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-typescript-forked-05e0ik?file=/src/index.tsx

### Steps to reproduce

1. Go to the sandbox
2. Fill out the name and last name(leave the age empty)
3. Check the console

The issue stems from having a field be optional eg
```
type Example {
age?: number
}
```

```
 <input
        name="age"
        {...register("age", { valueAsNumber: true })}
        type="number"
      />
```

Alongside registering a field as optional with `valueAsNumber: true`.

Seems that the library tries to parse this value

### Expected behaviour

It should leave the value blank instead of NaN. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mordv** [comment]
For those who's zod resolver is broken by NaN in optional field, here's the approach I used
```js
useForm({
    resolver: (values, ...rest) => {
      const modifiedValues = Object.fromEntries(
        Object.entries(values).map(([k, v]) =>
          schema.shape[k]._def.typeName === 'ZodOptional' && Number.isNaN(v) ? [k, undefined] : [k, v]
        )
      );
      return zodResolver(schema)(modifiedValues, ...rest);
    },
  });
```

**Comment by Moshyfawn** [comment]
> For those who's zod resolver is broken by NaN in optional field, here's the approach I used
> 
> ```js
> useForm({
>     resolver: (values, ...rest) => {
>       const modifiedValues = Object.fromEntries(
>         Object.entries(values).map(([k, v]) =>
>           schema.shape[k]._def.typeName === 'ZodOptional' && Number.isNaN(v) ? [k, undefined] : [k, v]
>         )
>       );
>       return zodResolver(schema)(modifiedValues, ...rest);
>     },
>   });
> ```

Or you can simply transform the `NaN` value to whatever value you want it to be.
```js
const schema = z.object({
  number: z.number().or(
    z
      .nan()
      .transform(() => undefined)
      .optional()
  )
})
```
