### ISSUE TITLE
issue: onSubmit Doesn't get called while submitting form

### ISSUE THREAD

**Issue by howdyAnkit** [react-hook-form/react-hook-form#8111]
### Version Number

7.24.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-headless-ui-dialog-modal-forked-gmzxql?file=/src/App.js

### Steps to reproduce

I am using react tailwind with headless ui for Form Radio group component
When I select the Value as Yes the submit value is set as true which is expected
but when I select the value as No and try to submit the form the onSubmit dosen't seem to get Invoked

### Expected behaviour

On Selecting No the value submitted should be false and the onsubmit should be called

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
RHF is following the HTML web standards. Setting `required: true` will ensure that a checkbox _(or a radio group in your case)_ must be `true`.

[I've modified your CSB](https://codesandbox.io/s/react-headless-ui-dialog-modal-forked-5fb8re?file=%2Fsrc%2FApp.js) to show the validation error when the value is `false`

**Comment by howdyAnkit** [comment]
But i don't want it to be like that when i click on No and submit the value should be submitted as false instead of showing validation error is there any way i can fix that?

**Comment by howdyAnkit** [comment]
Thanks for the Help I've fixed it if anyone wants to refer they can
```https://codesandbox.io/s/react-headless-ui-dialog-modal-forked-mu938f```

**Comment by Moshyfawn** [comment]
Once again, it's the web spec and we try to follow it closely where possible. It's the whole idea of RHF to embrace the native web handling uncontrolled inputs and native form validation attributes.

You can
- **either** pass the `string` value instead of `boolean` _(`"true"` / `"false"`)_
- **or** provide a custom validation function instead of `required`
```js
rules={{
  validate: (value) => {
    // INFO: will result in `true` for `null` and `undefined`
    if (value == null) {
      return 'Field must be checked'
    }
    return true
  }
}}
```
