### ISSUE TITLE
MaxLength property missing from <input> when using ZodResolver

### ISSUE THREAD

**Issue by henryjin3** [react-hook-form/react-hook-form#8115]
### Version Number

7.29.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-zod-maxlength-pln7n5?file=%2Fsrc%2FApp.tsx

### Steps to reproduce

1. Enter "asdfasdf" into the input box
2. Inspect the <input> element and see that the `maxLength` property is missing

### Expected behaviour

The `maxLength` property should either propagate from the Zod resolver or be allowed to be applied directly in the `registerOptions`.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
You're combining the form level validation _(the Zod resolver)_ and the field level validation _(`register` validation options)_, which is not allowed.

[From RHF docs on `resolver`](https://react-hook-form.com/api/useform#validationResolver):
> A resolver cannot be used with the built-in validators (e.g.: required, min, etc.)

**Comment by Moshyfawn** [comment]
RHF doesn't inject the resolver validation rules into the input element and focuses in form level validation.

You can simply pass your `maxLength` attribute to the input element like
```jsx
<input
  {...register('string')}
  maxLength={maxLength}
  placeholder="string"
/>
```

**Comment by bluebill1049** [comment]
Some of the rationals got discussed here: https://github.com/react-hook-form/react-hook-form/issues/8422#issuecomment-1141530563
