### ISSUE TITLE
issue: formState.errors.username somethimes is undefined when  at useForm onChange mode use setError method

### ISSUE THREAD

**Issue by bigbigbo** [react-hook-form/react-hook-form#8121]
### Version Number

7.29.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-seterror-forked-z90myw?file=/src/index.jsx

### Steps to reproduce

1. Go to Username input and start input content, devtools console pane will log `errors.username`.
2. When I enter the first character, it log `{type: "manual", message: "Error message", ref: Object}`.
3. Then enter the second character, after it log `{type: "manual", message: "Error message", ref: Object}`, it immediately outputs `undefined` again.
4. Keep inputting content, and this phenomenon will always appear again and again. It always doesn't appear `undefined` the first time it is input, but it does the second time.
5. Cause `{errors.username && <p>{errors.username.message}</p>}` to be displayed for a while and not displayed for a while.

https://user-images.githubusercontent.com/19587016/161197913-6fcba42a-fdbc-47bd-8be9-36af7206a60b.mp4

### Expected behaviour

In the `setError` [API document](https://react-hook-form.com/api/useform/seterror), I see the Rules:

> - This method will not persist the associated input error if the input passes validation.

So `errors.username` to be `undefined` is in this rule? If so, the log input each time should be the same instead of the one described above.

If I change `useForm` options.mode not `onChange`, `errors.username` return `{type: "manual", message: "Error message", ref: Object}` every time. I expect use `onChange mode`  can do the same. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Your `register` method holds the source of truth for your validation, `setError` will not persist again with the rules that you have cleared again the `register` method. in your example, `register` gets invoked on each render, which updates the filed registration to be no rules associated with it.

```tsx
// the following line gets run on each re-render and update registration (no rules)
const username = register("username");
const lastName = register("lastName");
```

If you can it's better to embed the validation logic with each `register` and treat `setError` as a temp form error.

**Comment by bigbigbo** [comment]
@bluebill1049 Thank you for your answer. I'm sorry I don't quite understand(but I understand `register's` behavior). My main question is why first enter output:
```bash
{type: "manual", message: "Error message", ref: Object}
```
and second enter output:
```bash
1. {type: "manual", message: "Error message", ref: Object}
2. undefined
```
If I switch `username.onChange` with `setError`, like this:
```js
setError("username", {
  type: "manual",
  message: "Error message"
});

username.onChange(e);
```
this is always output:
```bash
1. {type: "manual", message: "Error message", ref: Object}
2. undefined
```
Does this mean `username.onChange` is async and execute after `setError` ?

**Comment by bluebill1049** [comment]
> Does this mean username.onChange is async and execute after setError ?

validation is always async by default: https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/validateField.ts#L27

**Comment by bluebill1049** [comment]
curious: Why do you need to `setError` on the `onChange` instead `register` with validation rules?

**Comment by bigbigbo** [comment]
> curious: Why do you need to `setError` on the `onChange` instead `register` with validation rules?

The example from [official website](https://react-hook-form.com/api/useform/seterror), I use this example and changed `useForm options.mode`, then be confused by this phenomenon.

Finally, thank you for your answer. I have solved my doubts.

**Comment by bluebill1049** [comment]
@bigbigbo which example is confusing? I will update it. The multiple errors one?

**Comment by bigbigbo** [comment]
@bluebill1049 
![image](https://user-images.githubusercontent.com/19587016/161363316-73148af8-6146-4f96-8823-f2a06140554b.png)

**Comment by bluebill1049** [comment]
thanks will adjust.
