### ISSUE TITLE
Support for yup generated types or interfaces.

### ISSUE THREAD

**Issue by dberry-rcs** [react-hook-form/react-hook-form#8125]
If I am already using yup, I would like to use the yup generated type or interface so that I do not have to maintain a separate type or interface.

{...register("OrgName")}  reports the following error  TS2345: Argument of type 'string' is not assignable to parameter of type 'never' when calling useForm with a yup generated type or interface.

This works:
```
 interface IOrganization {
   OrgID : string,
   OrgName : string
}
useForm<IOrganization>();

```

This does not work:
```
const OrganizationSchema = yup.object().shape({
  OrgID : yup.string()
    .length(32, 'Invalid UUID')
    .required('UUID is required')
    .default(uuidv4()),
  OrgName : yup.string()
    .min(5, 'Organization Name must be at least 5 Characters')
    .required('UUID is required')
    .default(''),
});

type OrganizationType = yup.InferType<typeof OrganizationSchema>;
interface OrganizationInterface extends yup.InferType<typeof OrganizationSchema>{};

```
useForm<OrganizationType> or useForm<OrganizationInterface> will cause register to have a name:never parameter.

**Comment by Moshyfawn** [comment]
The problem is not necessarily with RHF but with the yup's `.shape` function and how TS infers it's types.

Refer to jquense/yup#1179 for more info.

The easiest workaround is to just use the `.object` function instead.

See [this working example](https://codesandbox.io/s/elegant-flower-3myske?file=%2Fsrc%2FApp.tsx).

**Comment by dberry-rcs** [comment]
Thank you for the workaround and the fast response!
