### ISSUE TITLE
issue: Control and Register do not support typescript interfaces inside storybook

### ISSUE THREAD

**Issue by jain24sachin** [react-hook-form/react-hook-form#8129]
### Version Number

7.18.0

### Codesandbox/Expo snack

NA

### Steps to reproduce

1. Create an interface and give default values to the hook form.
2. Destructure control and register.
3. Create a storybook and use control and register inside storybook, you need to give type to storybook component (register: UseFormRegister<FieldValues> and control: Control)
4. Now add the storybook component to the working view where you wish to use the component.
5. It will give TS error that Fieldvalue is incompatible type and do not overlap with the interface we give. 

### Expected behaviour

It should not ask to convert the Control to unknown first and then explicit convert it to control.
control={(control as unknown) as Control} //Wrong
control={control as Control} //Right

Same in case with register.

Hook form should have <T extends FieldValues> as interface for register and control that can be sent by the user so that the field will behave according to users expectation.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Relevant log output

```shell
Type 'Control<ICompany, object>' is not assignable to type 'Control<FieldValues, object>'.
  Types of property 'unregister' are incompatible.
    Type 'UseFormUnregister<ICompany>' is not assignable to type 'UseFormUnregister<FieldValues>'.
      Types of parameters 'name' and 'name' are incompatible.
        Type 'string | readonly string[] | string[] | undefined' is not assignable to type '"trading_platforms_&_station_number" | "email" | "company_name" | "phone_number" | "address1" | "city" | "state" | "zipcode" | "type" | "company_position" | "company_owner" | ... 19 more ... | undefined'.
          Type 'string' is not assignable to type '"trading_platforms_&_station_number" | "email" | "company_name" | "phone_number" | "address1" | "city" | "state" | "zipcode" | "type" | "company_position" | "company_owner" | ... 19 more ... | undefined'.  TS2322
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Consider providing [a reproduction codesandbox](https://codesandbox.io/s/storybook-react-typescript-0vuqg) before you can investigate.

Codesandbox template – https://codesandbox.io/s/storybook-react-typescript-0vuqg
