### ISSUE TITLE
getting handleSubmit from useFormContext hooks

### ISSUE THREAD

**Issue by mdebo** [react-hook-form/react-hook-form#813]
**Describe the bug**
Hi
First thanks for your wonderful works.
After trying useFormContext hooks, i'm not able to use handleSubmit function in a sub component
In fact, I have a FormSubmit component responsible of getting the submit function from the context (using useFormContext hook)
It seems that handleSubmit is never executed.

```
//Form component
type FormProps = {
  validationSchema?: any;
};
const Form: React.FC<FormProps> = ({ children, validationSchema }) => {
  const formMethods = useForm({
    validationSchema: validationSchema || {}
  });

  return <FormContext {...formMethods}>{children}</FormContext>;
};
export default Form;

//SubmitComponent
type SubmitProps = {
  onSubmit?: (data: any) => any;
};

const Submit: React.FC<SubmitProps> = ({ onSubmit }) => {
  const data = useFormContext(); // retrieve all hook methods
  // console.log(data);
  return (
    <Button
      onPress={(): any => {
        data.handleSubmit(onSubmit);
      }}
    >
      My label
    </Button>
  );
};
export default Submit;

//App
     <Form validationSchema={signinSchema}>
        <View>
          <InputText
            name="firstName"
            label="First name"
          />
        </View>
        <View>
          <InputText
            name="lastName"
            label="Last name"
          />
        </View>
        <Submit onSubmit={(data: any): any => console.log(data)} />
      </Form>

```
Do you have any ideas why my function handleSubmit I get from hooks does not executes the "onSubmit" callback

Again, thanks!

**Comment by bluebill1049** [comment]
`data.handleSubmit(onSubmit)(event)` I have replied you at spectrum early today as well :)

**Comment by mdebo** [comment]
Thanks you for your response! it wasn't me this morning on spectrum :-), but i really have appreciate your reactivity

All is working fine, now, so I think you can close this issue which wasn't a real one 
I have subscribed on spectrum too, :-)

**Comment by theweiweiway** [comment]
It was me lol. Ya, all i was missing was the ``(event)``. Thanks!

**Comment by bluebill1049** [comment]
lol sorry guys. u just ask the same questions at the same time.
