### ISSUE TITLE
issue: onSubmit Type Error

### ISSUE THREAD

**Issue by mustakimkr** [react-hook-form/react-hook-form#8130]
### Version Number

7.29.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-type-error-in-v7-29-0-yp2tqb

### Steps to reproduce

1. Open [Codesandbox](https://codesandbox.io/s/react-hook-form-type-error-in-v7-29-0-yp2tqb)
2. Click on 'App.tsx'
3. Scroll down to 'form' onSubmit 
4. See type error  _Argument of type 'SubmitHandler<FormValues>' is not assignable to parameter of type 'SubmitHandler<FieldValues>'._

<img width="1439" alt="Screenshot 2022-04-04 at 4 04 08 PM" src="https://user-images.githubusercontent.com/46971357/161521817-4a72302e-72dd-4ccc-ab6e-aa7ace700254.png">

Note: The above type error is only produced in some newer versions works fine in v7.21.0

### Expected behaviour

1. Works fine in react-hook-form@7.21.0
2. Here is working [Codesandbox](https://codesandbox.io/s/react-hook-form-without-type-error-in-v7-21-0-ijqmrp)

- As far my research its cause after this [commite](https://github.com/react-hook-form/react-hook-form/commit/70f2902172c361a9f78d45fde6cbf3896bf06799)
- Maybe after this PR merge #7405 

Please help me with this issue. If I'm doing anything wrong please let me know.

Thank you.

### What browsers are you seeing the problem on?

Google Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
missing `defaultValues` and you should supply the generic at `useForm`

```
const { control, handleSubmit } = useForm<FormValues>(); // missing defaultValues for hook form to infer 
const onSubmit: SubmitHandler<FormValues> = (data) => console.log(data);
```

**Comment by Moshyfawn** [comment]
You should provide the `FormValues` to `useForm` hook
```ts
useForm<FormValues>()
```

It's gonna fix your `onSubmit` TS issue.

Now, it's gonna surface an error with your `control` type in your `Input` component as you only pass the `FieldValues` type into `Control` and you want to use a generic instead to get the proper `Control` type when you pass your `control` to the `Input`.

There're a couple of issues with your `name` and `defaultValues` types as well.

See [this CSB](https://codesandbox.io/s/react-hook-form-type-error-in-v7-29-0-forked-2lk5xm?file=%2Fsrc%2FApp.tsx) for how to fix them

**Comment by Moshyfawn** [comment]
For more TS info on why it is the way it is you can check out the type definition of `useController` [here](https://codesandbox.io/s/react-hook-form-type-error-in-v7-29-0-forked-2lk5xm?file=%2Fsrc%2FInput.tsx)

**Comment by mustakimkr** [comment]
@bluebill1049  and @Moshyfawn Thank you so much for your super fast response.

Yes you are right I didn't provide the `FormValues` to `useForm` hook because it was causing another error in `control`
type in my `Input` component as @Moshyfawn mentioned.

**Comment by mustakimkr** [comment]
@Moshyfawn Thank u so much I got it.

Can you give me some resources where I can learn these kinds of types and generics

**Comment by Moshyfawn** [comment]
> @Moshyfawn Thank u so much I got it.
> 
> Can you give me some resources where I can learn these kinds of types and generics

There's [a RHF docs section on types](https://react-hook-form.com/ts#UseControllerProps), tho, @bluebill1049, it looks like it's a bit outdated.

Honestly, I usually just click into the RHF hook / method / prop instead in my IDE to go into it's type definition and see how it has been implemented :P 

https://user-images.githubusercontent.com/16290753/161530942-75022d1c-69c0-4292-948b-e9e17836f959.mp4

**Comment by bluebill1049** [comment]
I will get that updated @Moshyfawn 👍

**Comment by Moshyfawn** [comment]
> I will get that updated @Moshyfawn 👍

IK ppl somehow export type defs from code to their docs pages on deploy.. We might wanna look into doing smth similar
