### ISSUE TITLE
issue: SetValue with undefined doesn't clear the value

### ISSUE THREAD

**Issue by gregtayl** [react-hook-form/react-hook-form#8133]
### Version Number

7.29.0 (and 8.0.0 alpha)

### Codesandbox/Expo snack

https://codesandbox.io/s/strange-sammet-w3wo6y?file=/src/App.js

### Steps to reproduce

1. Click the 'Set undefined' button in the sandbox
2. See that the value in the input does not change/clear
3. Change the value in the input, click the 'Set undefined button'
4. See that the value in the input resets to the original

setValue('myField' undefined) doesn't clear the input value, instead it behaves like resetValue('myField')

### Expected behaviour

I would expect that calls to setValue('myField', undefined) should clear the underlying model state - not reset the value to the original value.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we don't support `undefined` for the input value. value is a required prop and can't be `undefined`, if you want to reset field, use `resetField` API: https://react-hook-form.com/api/useform/resetfield.

**Comment by gregtayl** [comment]
@bluebill1049 Thank you for the quick response!

Any chance the react-hook-form team might reconsider supporting undefined as a worthwhile feature? Our models make extensive use of optional fields, and unless I'm missing something, there doesn't seem to be a good way to approach clearing these properties in the current version of react-hook-form.

This is definitely a matter of opinion/style, however some development teams discourage use of null - leaving undefined as the only option for the absence of a value (e.g., often citing the following as rationale: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#null-and-undefined, http://bdadam.com/blog/video-douglas-crockford-about-the-new-good-parts.html).

Is there a recommended way to clear a field when the underlying model uses optional properties? Or is the recommendation of the react-hook-form team to use 'null' instead of 'undefined'?

```
type Model = {
   value?: number;
}
```
