### ISSUE TITLE
issue: dirtyFields does not change with shouldUnregister: false

### ISSUE THREAD

**Issue by imtrent** [react-hook-form/react-hook-form#8134]
### Version Number

6.15.8

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-dirty-state-testing-v6-15-8-5o2l36?file=/src/App.tsx

### Steps to reproduce

For v6.15.8 version with bug
1. Go to the codesandbox: https://codesandbox.io/s/react-hook-form-dirty-state-testing-v6-15-8-5o2l36?file=/src/App.tsx
2. Type into the "first name" input.
3. Click the "second step" button.
4. Type into the "last name" input.
5. You'll notice that the `dirtyFields` does not update properly with `shouldUnregister` set to false

For v7.29.0 version that is working properly
1. Go to the codesandbox: https://codesandbox.io/s/react-hook-form-dirty-state-testing-v7-29-0-w7ybpn?file=/src/App.tsx
2. Type into the "first name" input.
3. Click the "second step" button.
4. Type into the "last name" input.
5. The `dirtyFields` updates properly with `shouldUnregister` set to false

### Expected behaviour

`dirtyFields` should update in v6 with the `shouldUnregister` option set to false.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
hey @imtrent, i think you are missing `defaultValues` and what's the chance to upgrade to v7 as well?

https://react-hook-form.com/api/useform/formstate

> Make sure to provide all inputs' defaultValues at the useForm, so hook form can have a single source of truth to compare whether the form is dirty.

**Comment by imtrent** [comment]
> hey @imtrent, i think you are missing `defaultValues` and what's the chance to upgrade to v7 as well?
> 
> https://react-hook-form.com/api/useform/formstate
> 
> > Make sure to provide all inputs' defaultValues at the useForm, so hook form can have a single source of truth to compare whether the form is dirty.

I have updated both of the Codesandbox links to use `defaultValues`. The bug still exists when doing so. 

Upgrading to v7 is something we can do, though it would take some time. We have ~15 forms using RHF.

**Comment by bluebill1049** [comment]
I will take a look at it, but I would recommend upgrading to v7 if possible.

**Comment by bluebill1049** [comment]
you are using the wrong syntax in your example. please refer to the doc for v6 syntax instead: 

https://react-hook-form.com/v6/api

working example: 
https://codesandbox.io/s/vigorous-lake-tc58r4?file=/src/App.js

```tsx
import * as React from "react";
import { TextField } from "@mui/material";
import { useForm } from "react-hook-form";
import Headers from "./Header";
import "./styles.css";

let renderCount = 0;

export default function App() {
  const {
    register,
    handleSubmit,
    formState: { dirtyFields }
  } = useForm({
    shouldUnregister: false,
    defaultValues: {
      firstName: "bill",
      lastName: "luo"
    }
  });
  const onSubmit = (data) => console.log(data);
  renderCount++;

  console.log(dirtyFields);

  return (
    <div>
      <Headers
        renderCount={renderCount}
        description="Performant, flexible and extensible forms with easy-to-use validation."
      />

      <form onSubmit={handleSubmit(onSubmit)}>
        <TextField name="firstName" inputRef={register} />
        <TextField name="lastName" inputRef={register} />
        <input type="submit" />
      </form>
    </div>
  );
}
```
