### ISSUE TITLE
issue: SubmitHandler type error in v7, probably due to UnpackNestedValue type change.

### ISSUE THREAD

**Issue by leochoo** [react-hook-form/react-hook-form#8144]
### Version Number

7.20.5

### Codesandbox
V6: https://codesandbox.io/s/reproduce-v6-j5qnfi?file=/src/DescriptionForm.tsx
V7: https://codesandbox.io/s/reproduce-v7-1j4342?file=/src/DescriptionForm.tsx

## Description

At `DescriptionForm.tsx`, `onSubmit` has a TypeError on v7 (line 39), although it works fine on v6.15.8 (line 34).
Below is the error message on v7.20.5

```
Argument of type '(formProps: DescriptionFormProps) => void' is not assignable to parameter of type 'SubmitHandler<DescriptionFormProps>'.
  Types of parameters 'formProps' and 'data' are incompatible.
    Type '{ content: string; startDate: { clone: {}; isValid: {}; year: {}; month: {}; date: {}; day: {}; hour: {}; minute: {}; second: {}; millisecond: {}; set: {}; get: {}; add: {}; subtract: {}; startOf: {}; endOf: {}; format: {}; ... 12 more ...; locale: {}; } | null; endDate: { ...; } | null; }' is not assignable to type 'DescriptionFormProps'.
      Types of property 'startDate' are incompatible.
        Type '{ clone: {}; isValid: {}; year: {}; month: {}; date: {}; day: {}; hour: {}; minute: {}; second: {}; millisecond: {}; set: {}; get: {}; add: {}; subtract: {}; startOf: {}; endOf: {}; format: {}; diff: {}; valueOf: {}; unix: {}; ... 9 more ...; locale: {}; } | null' is not assignable to type 'MaterialUiPickersDate'.
          Type '{ clone: {}; isValid: {}; year: {}; month: {}; date: {}; day: {}; hour: {}; minute: {}; second: {}; millisecond: {}; set: {}; get: {}; add: {}; subtract: {}; startOf: {}; endOf: {}; format: {}; diff: {}; valueOf: {}; unix: {}; ... 9 more ...; locale: {}; }' is not assignable to type 'MaterialUiPickersDate'.
            Types of property 'clone' are incompatible.
              Type '{}' is not assignable to type '() => Dayjs'.
                Type '{}' provides no match for the signature '(): Dayjs'.ts(2345)
```

After an investigation, it seems that this is caused by the change in type `UnpackNestedValue`.

**We could confirm that manually changing the type of `UnpackNestedValue` to the type in v6 gets rid of the SubmitHandler type error.**

It seems that the future v8 is addressing this issue, but since I was migrating my system from v6 to v7, 
I wanted to open an issue here.

Please have a look. Thank you.

p.s. would you recommend that I wait for the v8 release?
 
v6
```typescript
export declare type UnpackNestedValue<T> = T extends NestedValue<infer U> ? U : T extends Date | FileList ? T : T extends Record<string, unknown> ? {
    [K in keyof T]: UnpackNestedValue<T[K]>;
} : T;
```

v7
```typescript
export declare type UnpackNestedValue<T> = T extends NestedValue<infer U> ? U : T extends Date | FileList | File ? T : T extends object ? {
    [K in keyof T]: UnpackNestedValue<T[K]>;
} : T;
```

### Screenshots
<details>
  <summary><b><u>onSubmit Type on V6 & V7</u></b></summary>
<p>v6</p>
  <img width="300" alt="CleanShot 2022-04-06 at 18 14 35@2x" src="https://user-images.githubusercontent.com/26427048/161943862-e0f2d8e8-315a-4f30-8a8b-a9767bb91d44.png">
<p>v7</p>
<img width="300" alt="CleanShot 2022-04-06 at 18 14 49@2x" src="https://user-images.githubusercontent.com/26427048/161944225-37227327-ae6d-448a-9414-9aab0b5fdb42.png">
 </details>

### Expected behaviour

No type mismatch in SubmitHandler.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
```diff
import type { SubmitHandler } from "react-hook-form"

interface Props {
-  onSubmit: (formProps: DescriptionFormProps) => void;
+  onSubmit: SubmitHandler<DescriptionFormProps>;
}
```

**Comment by leochoo** [comment]
Thanks!

Two questions:
1. Why do I have to import `type` separately?
2. Where in the documentation does it say I need to import the SubmitHandler type separately?

**Comment by leochoo** [comment]
@Moshyfawn @bluebill1049 
This doesn't work actually. 
I should have mentioned it, but this is the first thing I tried and it just passes the same error up to `NewDescriptionForm`. 

https://codesandbox.io/s/reproduce-v7-1j4342?file=/src/NewDescriptionForm.tsx

<img width="755" alt="CleanShot 2022-04-07 at 11 06 22@2x" src="https://user-images.githubusercontent.com/26427048/162105927-93aa45c3-82ba-44b6-bc40-afab8498efba.png">

**Comment by Moshyfawn** [comment]
You want to type your `onSubmit` function with `SubmitHandler<FormValues>` as well

**Comment by leochoo** [comment]
Again, it circles back to the same error. (In fact, I've tried that before as well.)

Could you please actually give it a try on Codesandbox?

I changed my code in `NewDescriptionForm` to the following
```typescript
  const onSubmit = (data: SubmitHandler<DescriptionFormProps>) => {
    console.log("NewDescriptionFormProps:", data);
  };
```
but the below error comes up.
```
Type '(data: SubmitHandler<DescriptionFormProps>) => void' is not assignable to type 'SubmitHandler<DescriptionFormProps>'.
  Types of parameters 'data' and 'data' are incompatible.
    Type '{ content: string; startDate: { clone: {}; isValid: {}; year: {}; month: {}; date: {}; day: {}; hour: {}; minute: {}; second: {}; millisecond: {}; set: {}; get: {}; add: {}; subtract: {}; startOf: {}; endOf: {}; format: {}; ... 12 more ...; locale: {}; } | null; endDate: { ...; } | null; }' is not assignable to type 'SubmitHandler<DescriptionFormProps>'.
      Type '{ content: string; startDate: { clone: {}; isValid: {}; year: {}; month: {}; date: {}; day: {}; hour: {}; minute: {}; second: {}; millisecond: {}; set: {}; get: {}; add: {}; subtract: {}; startOf: {}; endOf: {}; format: {}; ... 12 more ...; locale: {}; } | null; endDate: { ...; } | null; }' provides no match for the signature '(data: { content: string; startDate: { clone: {}; isValid: {}; year: {}; month: {}; date: {}; day: {}; hour: {}; minute: {}; second: {}; millisecond: {}; set: {}; get: {}; add: {}; subtract: {}; startOf: {}; endOf: {}; ... 13 more ...; locale: {}; } | null; endDate: { ...; } | null; }, event?: BaseSyntheticEvent<...> | undefined): any'.ts(2322)
[DescriptionForm.tsx(16, 3): ]()The expected type comes from property 'onSubmit' which is declared here on type 'IntrinsicAttributes & Props'
```

**Comment by leochoo** [comment]
It still does not work. Unfortunately, the same error shows up just at a different place. 
(In fact, I tried this before opening the issue here)

I added the Redux part to my Codesandbox for v7 to demonstrate the problematic part.
https://codesandbox.io/s/reproduce-v7-1j4342?file=/src/NewDescriptionForm.tsx

Below is how I gave `onSubmit` a type.
However, the same error now appears on the `values` parameter of that `onSubmit` function.

> ```diff
> -   const onSubmit = (values: DescriptionFormProps) => {
>   
>     };
> +    const onSubmit: SubmitHandler<DescriptionFormProps> = (values) => {
> +          dispatch(createDescription(values); // values now shows the same error.
>      };
> ```

![CleanShot 2022-04-07 at 20 23 51](https://user-images.githubusercontent.com/26427048/162188545-0bba891e-9cf7-40cc-85eb-fe916cba0e0d.png)

```error
Argument of type '{ content: string; startDate: { clone: {}; isValid: {}; year: {}; month: {}; date: {}; day: {}; hour: {}; minute: {}; second: {}; millisecond: {}; set: {}; get: {}; add: {}; subtract: {}; startOf: {}; endOf: {}; format: {}; ... 19 more ...; isSameOrBefore: {}; } | null; endDate: { ...; } | null; }' is not assignable to parameter of type 'DescriptionFormProps'.
  Types of property 'startDate' are incompatible.
    Type '{ clone: {}; isValid: {}; year: {}; month: {}; date: {}; day: {}; hour: {}; minute: {}; second: {}; millisecond: {}; set: {}; get: {}; add: {}; subtract: {}; startOf: {}; endOf: {}; format: {}; diff: {}; valueOf: {}; unix: {}; ... 16 more ...; isSameOrBefore: {}; } | null' is not assignable to type 'MaterialUiPickersDate'.
      Type '{ clone: {}; isValid: {}; year: {}; month: {}; date: {}; day: {}; hour: {}; minute: {}; second: {}; millisecond: {}; set: {}; get: {}; add: {}; subtract: {}; startOf: {}; endOf: {}; format: {}; diff: {}; valueOf: {}; unix: {}; ... 16 more ...; isSameOrBefore: {}; }' is not assignable to type 'MaterialUiPickersDate'.
        Types of property 'clone' are incompatible.
          Type '{}' is not assignable to type '() => Dayjs'.
            Type '{}' provides no match for the signature '(): Dayjs'.ts(2345)
```

**Comment by Moshyfawn** [comment]
I'm getting an error in your codesandbox:
```console
Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>
```

On thing I can mention is: RHF doesn't support custom classes for an input's value.

[From RHF docs](https://react-hook-form.com/api/useform):
> Avoid including custom object into the `defaultValues`. eg: moment, luxonas those will lead to unexpected result during internal object clone process.

**Comment by Moshyfawn** [comment]
Also, yo have some TS problems with your thunk as well. Maybe the TS issue with `createDescription` is related to this one.

<img width="734" alt="image" src="https://user-images.githubusercontent.com/16290753/162191197-9ac3bde2-6394-4e6b-a8a1-218f73c9865c.png">

**Comment by leochoo** [comment]
I mistakenly deleted this explanation so I added:

Ignore the error on ThunkAction. That part is omitted just for the sake of reproduction.
The original codebase has no error.

**Comment by leochoo** [comment]
Sorry, the original codebase is so complex that it is very hard for me to take out small parts and try to reproduce the error.

**Comment by leochoo** [comment]
> I'm getting an error in your codesandbox:
> 
> ```
> Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>
> ```
> 
> On thing I can mention is: RHF doesn't support custom objects for an input's value.
> 
> ```js
>  defaultValues: {
>    content: "",
> >  startDate: dayjs(),
> >  endDate: dayjs()
>  }
> ```
> 
> [From RHF docs](https://react-hook-form.com/api/useform):
> 
> > Avoid including custom object into the `defaultValues`. eg: moment, luxonas those will lead to unexpected result during internal object clone process.


1. But why did this work on RHF v6?

**Comment by leochoo** [comment]
2.  Did you get to read what I wrote about`UnpackNestedValue` in the OP?

I wonder if there's some kind of a mismatch happening between a JavaScript class instance and a JavaScript plain object?

Because I can see that casting the type seems to take away the error. Do you think this could be related? `dispatch(createDescription(values as DescriptionFormProps));`

**Comment by Moshyfawn** [comment]
> Sorry, the original codebase is so complex that it is very hard for me to take out small parts and try to reproduce the error.

Yeah, I get that, no worries.

Your TS issue with `createDescription` is
```console
Type '{}' is not assignable to type '() => Dayjs'.
```

It goes back to [that RHF rule:](https://react-hook-form.com/api/useform)
> Avoid including custom object into the defaultValues. eg: moment, luxonas those will lead to unexpected result during internal object clone process.

RHF types can't evaluate that "complex" DayJS object correctly.

> But why did this work on RHF v6?

From V6 to V7, RHF became a bit more type-safe. Now, if previously the type was extended from `Record<string, unknown>`, in V7 it's `extends object`.

@bluebill1049, I see that the OP's issue is coming from that change. Is it by design to avoid the use of custom objects?

**Comment by leochoo** [comment]
I sincerely appreciate your help.

> Your TS issue with `createDescription` is
> 
> ```
> Type '{}' is not assignable to type '() => Dayjs'.
> ```

Yes, that is the same error that's been circling around.


> RHF types can't evaluate that "complex" DayJS object correctly.

I see. In that case, what would be your recommendation?



> @bluebill1049, I see that the OP's issue is coming from that change. Is it by design to avoid the use of custom objects?

The thing is, the issue seems to be gone in **V8** (while alpha)
V8 version of Codesandbox: https://codesandbox.io/s/reproduce-v8-6zfhih?file=/src/NewDescriptionForm.tsx

**Comment by bluebill1049** [comment]
> @bluebill1049, I see that the OP's issue is coming from that change. Is it by design to avoid the use of custom objects?

that's correct. v7 is more strict than v6 in terms of type safety, at the same time it does bring some limitations. However, those issues are getting improved on v8. 

@leochoo i would migrate to v8 if that's something blocking you or else you may want to stay for v6. I don't think we will bring much breaking changes into v8, but it's not a promise as its still in alpha version.

**Comment by leochoo** [comment]
@bluebill1049 Thank you for the advice. Any estimate on when v8 might be released? Also, I actually have another issue within that same Codesandbox so I will open the issue tomorrow.

@Moshyfawn Thanks again for your help.

**Comment by bluebill1049** [comment]
No estimate at the moment, just working our way through.

**Comment by bluebill1049** [comment]
The other thing why v6 "works" and not v7 is mostly due to the type of safety introduced on v7 which may be completely missing in v6.

**Comment by Moshyfawn** [comment]
The bottom line is still the fact that RHF tries to embrace the Web API as close as possible to leverage the performance optimizations that come with it, so it's unadvised to use custom objects for the field's value.

**Comment by carlosbaraza** [comment]
@Moshyfawn @bluebill1049 How would you approach using a custom object for a custom complex component like a WYSIWIG editor then?

We are using `yup` + a DraftJS editor, which generates an `EditorState` custom object that will need to be stored in the database. Example of our approach below.

```tsx
const schema = yup.object({
    notes: yup.mixed<EditorState>(),
});

type FormValues = yup.InferType<typeof schema>;

const Form = (props) => {
  const form = useForm<FormValues>({
      defaultValues: props.initialValues,
      // yupResolver has type errors because EditorState is unpacked and the unpacked version is not equal to EditorState
      resolver: yupResolver(validationSchema)
  });

  // editorState is not of type EditorState, but some unpacked version of it
  const editorState = form.getValues().notes;
  
  return <form>
    {/* The name field allows any property of the custom object (more than 100, e.g. toJSON()) */}
    <TextEditor name="notes" control={form.control} /> 
  </form>;
};
```

**Comment by Moshyfawn** [comment]
The suggestion would be to simplify the state you want to store and submit in you form while handle the `Editor`'s state at the field's level.

At the end of the day, you won't be submitting all the methods and `Editor`'s state to you backend. The goal of the `Editor` is to format what is at it's core an input's string with a bunch of markdown, formatting, etc.

**Comment by Moshyfawn** [comment]
Something [like this](https://codesandbox.io/s/sleepy-taussig-66l3lo?file=%2Fsrc%2FApp.tsx). Tho, I know it gets a lot more complex. I haven't had to work with `Draft.js` closely before.

**Comment by carlosbaraza** [comment]
@Moshyfawn But that means I need to serialise on every keystroke, which is really expensive if there is a long piece of content. Also, there is validation on the custom object, which would have to deserialise, and other form components that change depending on what the EditorState is that need to deserialise too (e.g. previews, options for content, etc). I believe that expecting everything to be a string or primitive type is just too limiting. I don't really see why there would be any issues, because I am using the library with custom objects and (except for the types), it seems to work.
