### ISSUE TITLE
Fields Array doesn't work properly

### ISSUE THREAD

**Issue by DisaPadla** [react-hook-form/react-hook-form#815]
Example: [link](https://codesandbox.io/s/react-hook-form-field-array-advanced-with-delete-insert-append-edit-09ynm?fontsize=14&hidenavigation=1&theme=dark)

**Steps to reproduce:** 
1. Append three items
2. Remove first and second item
3. Click on submit

We got "fields" with two items on submit, instead of one. What i do wrong? Thanks

**Comment by DisaPadla** [comment]
Asked on spectrum.

**Comment by bluebill1049** [comment]
hey @DisaPadla try this: https://codesandbox.io/s/react-hook-form-usefieldarray-vy8fv

**Comment by DisaPadla** [comment]
@bluebill1049  Thanks. I didn't find "useFieldArray" in docs. Another solution, i use a nested property of object instead of an array. Like ```template-${id}.someProp```

**Comment by bluebill1049** [comment]
oh yeah @DisaPadla it's still in beta, we will likely to release it next week, i am doing more testing and automation to make sure it's working correctly.
