### ISSUE TITLE
issue: Deleting and adding new nested rows retains the original defaultValues

### ISSUE THREAD

**Issue by readikus** [react-hook-form/react-hook-form#8152]
### Version Number

7.13.0+

### Codesandbox/Expo snack

https://codesandbox.io/s/c34lfk

### Steps to reproduce

1. Delete one or more of the rows shown in the rendered table
2. Add a new row
3. The original values are retained, not the values passed to `append`

### Expected behaviour

The new row uses the data passed to `append`:

https://codesandbox.io/s/83f92l

I have been experiencing some issues with using the form library to deleting then adding new rows in a form that contains an array of arrays. When creating a form based on an initial set of data (i.e. records loaded via an API), deleting a row, then adding a new one appears to retain the original value.

This appears to have been introduced between 7.12.2 and 7.13.0, and remains in subsequent releases. I initially believed it was my misuse of the library, but I have spent quite a few hours trying to try different ways of using it, and have resorted to pinning to an older version. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
![Screen Shot 2022-04-08 at 5 24 05 pm](https://user-images.githubusercontent.com/10513364/162385299-f97447e4-46dc-47be-964e-bde72ed3da82.png)

provide `undefined` will result in a fallback to `defaultvalue`, for useFieldArray action such append/prepend/insert will always require to provide the `defaultValues` for each newly added field.

![Screen Shot 2022-04-08 at 5 24 23 pm](https://user-images.githubusercontent.com/10513364/162385339-9a15bfad-d6d0-4157-8267-91860d1c2093.png)

```diff
append({
-  test: undefined
+ test: ''
})
```

**Comment by readikus** [comment]
@bluebill1049 thank you for the guidance - that makes a lot of sense now.

**Comment by bluebill1049** [comment]
np @readikus
