### ISSUE TITLE
issue: Dual Package Hazard

### ISSUE THREAD

**Issue by smeng9** [react-hook-form/react-hook-form#8154]
### Version Number

7.29.0

### Codesandbox/Expo snack

https://codesandbox.io/s/nervous-microservice-955m3u?file=/src/tags/TagEdit.tsx

### Steps to reproduce

To show the dual package hazard:

Experimental group:
The code is hosted here https://codesandbox.io/s/nervous-microservice-955m3u?file=/src/tags/TagEdit.tsx
I created a component called `<SomethingUseFormContext>` inside a Form
1. Go to https://955m3u.sse.codesandbox.io/#/tags/1
2. No need to click anything 
3. It will throw an error that useFormContext is null

Controlled group:
The code is hosted here https://codesandbox.io/s/ecstatic-breeze-439187?file=/src/tags/TagEdit.tsx:337-386
1. Go to https://439187.sse.codesandbox.io/#/tags/1
2. No need to click anything 
3. The form should render without a problem

The only difference is in https://codesandbox.io/s/nervous-microservice-955m3u?file=/src/tags/TagEdit.tsx it is using `require`
and in https://codesandbox.io/s/ecstatic-breeze-439187?file=/src/tags/TagEdit.tsx:337-386 it is using `import`

Hi @bluebill1049 and @evocateur 
To answer your question in https://github.com/react-hook-form/react-hook-form/pull/8127 :
> The linked roadmap ticket does not seem to indicate this error is being experienced there?

The linked discussion throws the same error as `useFormContext returns null` in experimental group.
I just digged more into this issue and found out the dual package hazard. Now I open an issue with reproducible examples here.

> Where are you actually experiencing this error?

I experience this error because some of the form components (from third party) that requires formContext uses require, while we import that package. Even though all packages listed react-hook-form in `peerDependency` so there are no duplicate packages, but esm and cjs version causes two instance of package. We can't force the third party package to switch from require to import because the problem is not theirs.

> If you're using ESM, you have to use import, or a bundler that understands it correctly.

No matter which format we use, we need to make sure there is only one instance of `react-hook-form` even there are mixed require and import in the code. By default we use esm, but whether use or not use esm in 3rd party library is different story, because there are always some package use esm and some package use cjs. Node.js already provides a way to solve this hazard https://nodejs.org/api/packages.html#writing-dual-packages-while-avoiding-or-minimizing-hazards for a library that is in the deepest chain of dependency.

For your other comments on 
> If we're truly hitting the "dual package hazard" with standard Webpack usage, we should fix the problem correctly, not expose implementation details as "public" API.

I agree @evocateur this fix may be hacky. We should come up with better ways of releasing the package of `react-hook-form`. We need to following the guidelines in Node.js https://nodejs.org/api/packages.html#writing-dual-packages-while-avoiding-or-minimizing-hazards

### Expected behaviour

Expected bahavior is when using require we should also not experiencing any problem.

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
useFormContext() is null


SomethingUseFormContext@https://955m3u.sse.codesandbox.io/index.bundle.js:141096:17
div
./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js/withEmotionCache/<@https://955m3u.sse.codesandbox.io/index.bundle.js:590:66
Stack@https://955m3u.sse.codesandbox.io/index.bundle.js:30448:87
div
./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js/withEmotionCache/<@https://955m3u.sse.codesandbox.io/index.bundle.js:590:66
CardContent@https://955m3u.sse.codesandbox.io/index.bundle.js:11904:82
./node_modules/ra-ui-materialui/dist/esm/index.js/fk<@https://955m3u.sse.codesandbox.io/index.bundle.js:93926:152660
form
./node_modules/ra-core/dist/esm/index.js/Fa<@https://955m3u.sse.codesandbox.io/index.bundle.js:93391:3011
FormProvider@https://955m3u.sse.codesandbox.io/index.bundle.js:145158:35
./node_modules/ra-core/dist/esm/index.js/ue<@https://955m3u.sse.codesandbox.io/index.bundle.js:93368:3431
./node_modules/ra-core/dist/esm/index.js/ua<@https://955m3u.sse.codesandbox.io/index.bundle.js:93368:7006
./node_modules/ra-core/dist/esm/index.js/Gw<@https://955m3u.sse.codesandbox.io/index.bundle.js:93391:7280
./node_modules/ra-ui-materialui/dist/esm/index.js/cp<@https://955m3u.sse.codesandbox.io/index.bundle.js:93926:151285
div
./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js/withEmotionCache/<@https://955m3u.sse.codesandbox.io/index.bundle.js:590:66
Paper@https://955m3u.sse.codesandbox.io/index.bundle.js:26671:82
./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js/withEmotionCache/<@https://955m3u.sse.codesandbox.io/index.bundle.js:590:66
Card@https://955m3u.sse.codesandbox.io/index.bundle.js:11608:82
div
div
./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js/withEmotionCache/<@https://955m3u.sse.codesandbox.io/index.bundle.js:590:66
./node_modules/ra-ui-materialui/dist/esm/index.js/Er<@https://955m3u.sse.codesandbox.io/index.bundle.js:93926:134325
./node_modules/ra-core/dist/esm/index.js/ue<@https://955m3u.sse.codesandbox.io/index.bundle.js:93368:3431
./node_modules/ra-core/dist/esm/index.js/ir<@https://955m3u.sse.codesandbox.io/index.bundle.js:93368:3836
./node_modules/ra-core/dist/esm/index.js/la<@https://955m3u.sse.codesandbox.io/index.bundle.js:93368:7375
./node_modules/ra-ui-materialui/dist/esm/index.js/TL<@https://955m3u.sse.codesandbox.io/index.bundle.js:93926:137666
TagEdit@https://955m3u.sse.codesandbox.io/index.bundle.js:141101:75
Routes@https://955m3u.sse.codesandbox.io/index.bundle.js:129785:7
./node_modules/ra-core/dist/esm/index.js/_t<@https://955m3u.sse.codesandbox.io/index.bundle.js:93361:7339
./node_modules/ra-core/dist/esm/index.js/zn<@https://955m3u.sse.codesandbox.io/index.bundle.js:93361:7523
Routes@https://955m3u.sse.codesandbox.io/index.bundle.js:129785:7
ErrorBoundary@https://955m3u.sse.codesandbox.io/index.bundle.js:122075:37
div
main
div
div
./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js/withEmotionCache/<@https://955m3u.sse.codesandbox.io/index.bundle.js:590:66
./node_modules/ra-ui-materialui/dist/esm/index.js/qc<@https://955m3u.sse.codesandbox.io/index.bundle.js:93924:72609
__WEBPACK_DEFAULT_EXPORT__
div
Routes@https://955m3u.sse.codesandbox.io/index.bundle.js:129785:7
./node_modules/ra-core/dist/esm/index.js/ao<@https://955m3u.sse.codesandbox.io/index.bundle.js:93361:3327
Routes@https://955m3u.sse.codesandbox.io/index.bundle.js:129785:7
./node_modules/ra-core/dist/esm/index.js/Gn<@https://955m3u.sse.codesandbox.io/index.bundle.js:93361:5797
./node_modules/ra-ui-materialui/dist/esm/index.js/mD<@https://955m3u.sse.codesandbox.io/index.bundle.js:93955:7478
InnerThemeProvider@https://955m3u.sse.codesandbox.io/index.bundle.js:40114:70
ThemeProvider@https://955m3u.sse.codesandbox.io/index.bundle.js:39827:7
ThemeProvider@https://955m3u.sse.codesandbox.io/index.bundle.js:40136:7
./node_modules/ra-ui-materialui/dist/esm/index.js/Yc<@https://955m3u.sse.codesandbox.io/index.bundle.js:93924:82555
./node_modules/ra-core/dist/esm/index.js/Un<@https://955m3u.sse.codesandbox.io/index.bundle.js:93360:54787
./node_modules/ra-core/dist/esm/index.js/Yo<@https://955m3u.sse.codesandbox.io/index.bundle.js:93360:8326
./node_modules/ra-core/dist/esm/index.js/It<@https://955m3u.sse.codesandbox.io/index.bundle.js:93360:8900
Router@https://955m3u.sse.codesandbox.io/index.bundle.js:129723:7
Oo@https://955m3u.sse.codesandbox.io/index.bundle.js:93360:771
./node_modules/ra-core/dist/esm/index.js/ps<@https://955m3u.sse.codesandbox.io/index.bundle.js:93360:1830
./node_modules/ra-core/dist/esm/index.js/jo<@https://955m3u.sse.codesandbox.io/index.bundle.js:93360:1260
./node_modules/ra-core/dist/esm/index.js/ko<@https://955m3u.sse.codesandbox.io/index.bundle.js:93360:1397
QueryClientProvider@https://955m3u.sse.codesandbox.io/index.bundle.js:127783:16
./node_modules/ra-core/dist/esm/index.js/Ho<@https://955m3u.sse.codesandbox.io/index.bundle.js:93360:7087
./node_modules/ra-core/dist/esm/index.js/to<@https://955m3u.sse.codesandbox.io/index.bundle.js:93360:55283
./node_modules/ra-ui-materialui/dist/esm/index.js/uD<@https://955m3u.sse.codesandbox.io/index.bundle.js:93955:7914
./node_modules/react-admin/dist/esm/index.js/N<@https://955m3u.sse.codesandbox.io/index.bundle.js:94483:484
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is not an issue related to this library or how it's been bundled, if this is occurring a problem for your build. I suggest you fork the repo and publish your own version to resolve.
