### ISSUE TITLE
issue: using register dep prop as an array re-renders all fields

### ISSUE THREAD

**Issue by Krempelj** [react-hook-form/react-hook-form#8156]
### Version Number

v7

### Codesandbox/Expo snack

https://codesandbox.io/s/zealous-dust-vlp7fk?file=/src/App.tsx

### Steps to reproduce

Hi!

1. Go to Sandbox: https://codesandbox.io/s/zealous-dust-vlp7fk?file=/src/App.tsx
2. Enter some text in either one of the last two fields. On every key stroke all four fields are updated.

### Expected behaviour

There are 4 input fields, 2 on each row component. Fields inside the same row are made dependant with dep prop with the register method (line 92).

The expected behaviour is that fields update only the dependant fields as shown in the sandbox with the first two fields.

The only difference is that the working fields are hooked up with a string dep, the last two are hooked up by an array of one dependency, which I assume should be working the same as the string dep.

Rows are rendered with the help of useFieldArray.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
RHF doesn't do field array related validation optimizations as it would potentially tank down the performance and outweigh the optimization benefits.

See #7831 for more info.
