### ISSUE TITLE
Remote submit

### ISSUE THREAD

**Issue by Fatal1stZ** [react-hook-form/react-hook-form#816]
How to achieve remote submit with react-hook-form? This useful feature from [Redux-form](https://redux-form.com/6.6.3/examples/remotesubmit/)

**Comment by bluebill1049** [comment]
thanks for the suggestion, however i dont see anything new other than use `handleSubmit` to other place. you can achieve this with react-hook-form already.

**Comment by bluebill1049** [comment]
i guess it's similar to this question: https://github.com/react-hook-form/react-hook-form/issues/813

**Comment by bluebill1049** [comment]
close this issue, feel free to ask more question if my answer doesn't solve your question.

**Comment by Fatal1stZ** [comment]
Is it intended only for nested components?
What if I want to remote submit outside the form?

**Comment by bluebill1049** [comment]
> Is it intended only for nested components?

not really.

> What if I want to remote submit outside the form?

as long as you hoist `useForm` high up at your outside form level.
