### ISSUE TITLE
Can we get a `hasValidated` property on `formState`?

### ISSUE THREAD

**Issue by Roryl-c** [react-hook-form/react-hook-form#8176]
**Is your feature request related to a problem? Please describe.**
We're trying to achieve something very simple: build a component that will display its own validation errors or a success message **only after it has validated once**, regardless of the containing form `mode`. That is, the validation result should be hidden initially, then after the field is validated (depending on form `mode` either `onChange`, `onTouch`, etc), it should display a success or error depending on if validation succeeded. Right now there seems to be no way to do this aside from performing checks manually based on the form `mode` passed in as a prop to see when the form has been validated.

**Describe the solution you'd like**
I'd like a new property `hasValidated` on the `formState` API. It should be an object with keys per field in the form, and values "false" initially but "true" after the field has been validated once (whenever react-hook-form does so based on the form mode). 

**Describe alternatives you've considered**
Only viable alternative seems to be to pass the form `mode` additionally to each child component, so it can figure out when the form has actually validated a field or not.

**Comment by LachlanRidley** [comment]
@bluebill1049 is there a recommended pattern for implementing this sort of functionality with the current version of `react-hook-form`? It's a roadblock on our team at the moment because we want to be able to have the functionality described by the OP but without the child components knowing what `mode` the form is using.
