### ISSUE TITLE
issue: typescript error when try to updating array with undefined

### ISSUE THREAD

**Issue by exneval** [react-hook-form/react-hook-form#8178]
### Version Number

7.29

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-5m8jg?file=/src/App.tsx

### Steps to reproduce

1. Try implementing `useFieldArray`
2. Use the update method from the hook
3. Set the value param with `undefined`

### Expected behaviour

Should allow setting `undefined` like `append`.

It's working in 7.27.0 

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> append | (obj: object \| object[], focusOptions) => void | Append input/inputs to the end of your fields and focus. The input value will be registered during this action.

> Important: append data is required and not partial.

<img width="953" alt="Screen Shot 2022-04-13 at 3 46 23 pm" src="https://user-images.githubusercontent.com/10513364/163108696-1c81b0ce-50d7-42ab-bab2-ede98d24bfb5.png">

**Comment by exneval** [comment]
Sorry for the misleading issue, I've updated the title and codesandbox

may you checked it again @bluebill1049

**Comment by bluebill1049** [comment]
no worries, we don't do any thought of deep merge with `update` API, so it's better to supply the entire update object, you can use `getValues()` API.
