### ISSUE TITLE
issue: find index.umd.js has const, not var

### ISSUE THREAD

**Issue by minzhang2** [react-hook-form/react-hook-form#8182]
### Version Number

7.29.0

### Codesandbox/Expo snack

https://github.com/react-hook-form/react-hook-form/releases/tag/v7.29.0

### Steps to reproduce

in index.umd.js

### Expected behaviour
![image](https://user-images.githubusercontent.com/15793061/163174411-a4c0bc8f-e6d0-4850-b813-b5af49a11a61.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we are dropping IE 11 support since the beginning of v7: https://caniuse.com/const
