### ISSUE TITLE
Rename `handleSubmit` to `createSubmitHandler`

### ISSUE THREAD

**Issue by burnmaniac** [react-hook-form/react-hook-form#8193]
**Is your feature request related to a problem? Please describe.**
Yes. In multiple projects, my team and I follow the practice to name all of our callbacks, "answering" to events, with the prefix `handle`. For the form, for example, we would name the callback function `handleSubmit`, and pass that via the `onSubmit` attribute. This practice is in conflict with reserved `handleSubmit`.

**Describe the solution you'd like**
The `handleSubmit` is not the actual handler callback. Instead, it is a function that returns a handler callback. So, naturally, I'd call this one `createSubmitHandler`. This is what we're doing as a workaround at the moment. While destructuring, we rename the `handleSubmit` to `createSubmitHandler` and all works fine, but there is additional code. When we get someone new in the team, that developer misses this, then it becomes a mess...

My main argument for this is that the naming is wrong since `handleSubmit` returned from the `useForm` hook is not handling the submit. It creates another new function that handles the submit.

**Comment by Moshyfawn** [comment]
While, I see your point, consider the fact that `handleSubmit` doesn't only take in an `onSubmit` and `onError` callbacks and executes them, but rather [handles all  the validation logic along with setting the appropriate form states like `isSubmitting`, `errors` etc](https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/createFormControl.ts#L1012-L1069).

```js 
 ​  ​const​ ​handleSubmit​: ​UseFormHandleSubmit​<​TFieldValues​>​ ​= 
 ​    ​(​onValid​,​ ​onInvalid​)​ ​=>​ ​async​ ​(​e​)​ ​=>​ ​{ 
 ​      ​if​ ​(​e​)​ ​{ 
 ​        ​e​.​preventDefault​ ​&&​ ​e​.​preventDefault​(​)​; 
 ​        ​e​.​persist​ ​&&​ ​e​.​persist​(​)​; 
 ​      ​} 
 ​      ​let​ ​hasNoPromiseError​ ​=​ ​true​; 
 ​      ​let​ ​fieldValues​: ​any​ ​=​ ​cloneObject​(​_formValues​)​; 
  
 ​      ​_subjects​.​state​.​next​(​{ 
 ​        ​isSubmitting​: ​true​, 
 ​      ​}​)​; 
  
 ​      ​try​ ​{ 
 ​        ​if​ ​(​_options​.​resolver​)​ ​{ 
 ​          ​const​ ​{​ errors​,​ values ​}​ ​=​ ​await​ ​_executeSchema​(​)​; 
 ​          ​_formState​.​errors​ ​=​ ​errors​ ​as​ ​FieldErrors​<​TFieldValues​>​; 
 ​          ​fieldValues​ ​=​ ​values​; 
 ​        ​}​ ​else​ ​{ 
 ​          ​await​ ​executeBuildInValidation​(​_fields​)​; 
 ​        ​} 
  
 ​        ​if​ ​( 
 ​          ​isEmptyObject​(​_formState​.​errors​)​ ​&& 
 ​          ​Object​.​keys​(​_formState​.​errors​)​.​every​(​(​name​)​ ​=>​ ​get​(​fieldValues​,​ ​name​)​) 
 ​        ​)​ ​{ 
 ​          ​_subjects​.​state​.​next​(​{ 
 ​            ​errors​: ​{​}​ ​as​ ​FieldErrors​<​TFieldValues​>​, 
 ​            ​isSubmitting​: ​true​, 
 ​          ​}​)​; 
 ​          ​await​ ​onValid​(​fieldValues​,​ ​e​)​; 
 ​        ​}​ ​else​ ​{ 
 ​          ​if​ ​(​onInvalid​)​ ​{ 
 ​            ​await​ ​onInvalid​(​{​ ...​_formState​.​errors​ ​}​,​ ​e​)​; 
 ​          ​} 
  
 ​          ​_options​.​shouldFocusError​ ​&& 
 ​            ​focusFieldBy​( 
 ​              ​_fields​, 
 ​              ​(​key​)​ ​=>​ ​get​(​_formState​.​errors​,​ ​key​)​, 
 ​              ​_names​.​mount​, 
 ​            ​)​; 
 ​        ​} 
 ​      ​}​ ​catch​ ​(​err​)​ ​{ 
 ​        ​hasNoPromiseError​ ​=​ ​false​; 
 ​        ​throw​ ​err​; 
 ​      ​}​ ​finally​ ​{ 
 ​        ​_formState​.​isSubmitted​ ​=​ ​true​; 
 ​        ​_subjects​.​state​.​next​(​{ 
 ​          ​isSubmitted​: ​true​, 
 ​          ​isSubmitting​: ​false​, 
 ​          ​isSubmitSuccessful​: 
 ​            ​isEmptyObject​(​_formState​.​errors​)​ ​&&​ ​hasNoPromiseError​, 
 ​          ​submitCount​: ​_formState​.​submitCount​ ​+​ ​1​, 
 ​          ​errors​: ​_formState​.​errors​, 
 ​        ​}​)​; 
 ​      ​} 
 ​    ​}​;
```

So, if anything, I'd say `handleValidation` would be a closer name for the function in question

**Comment by bluebill1049** [comment]
I think the naming was inherited from many form libraries which exist in the react ecosystem, which is definitely one of the reasons why the name was carried over. I understand the concern with onSubmit -> handleSubmit -> onSubmit, a change that will also result in a breaking change to the existing version. We are happy to move into the project board and leave to upvote, but we are most likely not going to change in the next major version. (which is working in progress)

**Comment by Moshyfawn** [comment]
Sounds good!

**Comment by jakobo** [comment]
FWIW should someone else come across this issue, you can remap during destructuring to fit your team's mental model.

```ts
const {
  handleSubmit: createSubmitHandler,
  register,
  formState,
} = useForm<TSFormInterface>({
  // ...
});
```

**Comment by axelboc** [comment]
I'm in the same situation as @burnmaniac. I have to rename RHF's `handleSubmit` to not conflict with my own. Arguably, I could name my handler `handleValidSubmit` or similar but the fact remains that RHF's `handleSubmit` is not itself an event handler -- it returns one. And this returned handler is a submit handler, since (to my knowledge) it is not meant to be used anywhere else than inside an `onSubmit` event handler.

Going further than naming, perhaps another solution would be for users to pass `onValid` and `onInvalid` handlers to `useForm` instead. It would then make sense for `useForm` to return an event handler called `handleSubmit`:

```tsx
function handleValidSubmit() {
  ...
}

const { handleSubmit } = useForm({ onValid: handleValidSubmit });

onSubmit={handleSubmit}
```

Or if the component receives an `onSubmit` prop:

```tsx
const { onSubmit } = props;
const { handleSubmit } = useForm({ onValid: onSubmit });

onSubmit={handleSubmit}
```

If the names `onValid` and `onInvalid` are too vague as properties of `useForm`, one could imagine naming them `onValidSubmit` and `onInvalidSubmit`.

A great benefit of this pattern is that it makes it easier for developers to optimise re-renders if they need to, by making sure that a new submit handler is not recreated/re-registered on every render:

```tsx
const handleValidSubmit = useCallback(() => { ... }, [...]);
const { handleSubmit } = useForm({ onValidSubmit: handleValidSubmit });

onSubmit={handleSubmit}
```

As opposed to what has to be done currently (which I'm not bothering to do since it's too convoluted):

```tsx
const { handleSubmit: createSubmitHandler } = useForm();

const handleValidSubmit = useCallback(() => { ... }, [...]);
const handleSubmit = useMemo(() => createSubmitHandler(handleValidSubmit), [handleValidSubmit]); // linting probably requires adding `createSubmitHandler` to the deps array as well

onSubmit={handleSubmit}
```
