### ISSUE TITLE
issue: dirtyFields behavior with useFIeldArray not the same as changing a field

### ISSUE THREAD

**Issue by StevenDanaCorelight** [react-hook-form/react-hook-form#8194]
### Version Number

7.28.0

### Codesandbox/Expo snack

https://codesandbox.io/s/elegant-saha-6y1xq4?file=/src/App.js

### Steps to reproduce

This may be more of a question than a bug, but it presents a performance challenge in a form I'm working on. This behavior of append was not so in 7.19.5

1. Click "Append Field" button
2. Observe console.log of dirtyFields

### Expected behaviour

- Behavior when changing a text input: only the changed field is reflected in dirtyFields
- Behavior when appending a field: entire form state is reflected in dirtyFields

I expect appending a field to not cause the entire form state to be represented in dirtyFields, but only the fields key to be added. In other words, the behavior when changing a text input.

### Relevant log output

```shell
//Behavior when changing a text input
{
    "fields": [
        {
            "foo": true
        }
    ]
}

//Behavior when appending a field
{
    "a": false,
    "b": false,
    "fields": [
        {
            "foo": true,
            "bar": false
        },
        {
            "foo": true,
            "bar": true
        }
    ]
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Possibly, related #7965

**Comment by StevenDanaCorelight** [comment]
> Possibly, related #7965

Yep, you're right. I'm going to close
