### ISSUE TITLE
Version 4.5.0 WebpackError: ReferenceError: window is not defined during SSR

### ISSUE THREAD

**Issue by ThewBear** [react-hook-form/react-hook-form#821]
**Describe the bug**
Using with gatsby will cause `ReferenceError: window is not defined` during build time.

**To Reproduce**
Use `useForm` hook in gatsby pages.

Here is where the error happens.
https://github.com/react-hook-form/react-hook-form/blob/61d019f308770888f250d54566217ce451df81d2/src/useForm.ts#L92

**Comment by bluebill1049** [comment]
thanks will patch that issue. thanks

**Comment by bluebill1049** [comment]
can you try this beta? react-hook-form@4.5.1-beta.1

**Comment by BarbarConan** [comment]
> can you try this beta? react-hook-form@4.5.1-beta.2

it works for me, thanks!
