### ISSUE TITLE
Inconsistent behavior of ref callback between `useForm.register` and `useController` after resetting form

### ISSUE THREAD

**Issue by RadoslavK** [react-hook-form/react-hook-form#8220]
### Version Number

7.30.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-ref-05njq0

### Steps to reproduce

1. Modify both input fields
2. Click on 'Submit' -> submitted values are rendered
3. Click on 'Reset'
4. Modify both fields again
5. Click on 'Submit' -> the first field value is not submitted properly and breaks

**Context**:

- happens only after resetting the form
- seems like the original ref callback is destroyed
  - which makes optimizations to it impossible (example is simplified to show the point)
  - it still works when the field is registered via `useController`

### Expected behaviour

The form field is still properly connected to the form and its values are available in the submit handler.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Thanks for the issue. We don't have such usage. `register` should call on each render.

**Comment by Moshyfawn** [comment]
If you pass the proper deps to the `useMemo` deps array, it works fine.
<img width="689" alt="image" src="https://user-images.githubusercontent.com/16290753/163992796-3d46cc9e-4841-46c4-8078-ef03a497ed2d.png">

**Comment by bluebill1049** [comment]
thanks, @Moshyfawn either way I don't think we cover such usage in the doc or any test cases. probably not a recommended way of using hook form register in the first place.

**Comment by Moshyfawn** [comment]
> thanks, @Moshyfawn either way I don't think we cover such usage in the doc or any test cases. probably not a recommended way of using hook form register in the first place.

Oh, yea, for sure!

**Comment by RadoslavK** [comment]
I was trying to bend the implementation to achieve a specific result but if this is the desired behavior, I will open a feature request issue.

**Comment by bluebill1049** [comment]
Let us know more detail on the usage and what you try to achieve.
