### ISSUE TITLE
issue: Many re-renders when read formState and use useController

### ISSUE THREAD

**Issue by matheusf31** [react-hook-form/react-hook-form#8222]
### Version Number

7.30.0

### Codesandbox/Expo snack

https://codesandbox.io/s/usecontroller-forked-4pmzqw?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/usecontroller-forked-4pmzqw?file=/src/App.tsx
2. Write anything on input
3. Open and **clear** console
4. Click on submit
6. See console

### Expected behaviour

I think the expected behaviour is not re-render too many times

<details>
  <summary>Before Submit</summary>
  
  ![image](https://user-images.githubusercontent.com/45342938/164025825-f93627f1-8722-4f63-b42d-00abb726a23f.png)
</details>

<details>
  <summary>After Submit</summary>
  
  ![image](https://user-images.githubusercontent.com/45342938/164026869-2e2eac68-87e2-49f9-8304-f9c4e5d5a2e0.png)
</details>

### What browsers are you seeing the problem on?

Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
you are subscribed to the form state.

```
const {
    handleSubmit,
    control,
    formState: { errors } // here the subscription 
} = useForm<FormValues>({
  defaultValues: {
    FirstName: ""
  },
  mode: "onChange"
});
```

if you don't want to subscribe at the root of your app, use `useFormState` instead.

**Comment by matheusf31** [comment]
So it's normal to re-render when I'm subscribed to the errors form state? Using useController and get fieldState have the same behavior, trigger re-render in component.

```
const {
    field: { onBlur, onChange, value, ref },
    fieldState: { error }, // <---
  } = useController(props);
```
