### ISSUE TITLE
issue: useFieldArray values being returned in error object after Update is called

### ISSUE THREAD

**Issue by davetaylor** [react-hook-form/react-hook-form#8225]
### Version Number

7.20.2

### Codesandbox/Expo snack

https://codesandbox.io/s/zealous-hodgkin-31d31f?file=/src/App.tsx

### Steps to reproduce

1. Go to the CodeSandbox
2. Open the console 
3. Enter data into the form
4. See in the console  that the error object contains the field values instead of the {required: true...} object

### Expected behaviour

Errors should be an object with field errors. 

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Can you elaborate? I see the error object contains the nested fields error object
<img width="233" alt="image" src="https://user-images.githubusercontent.com/16290753/164257732-14941d26-ce41-4872-aedb-8b37ac594ba9.png">

**Comment by davetaylor** [comment]
Hi @Moshyfawn - If you 'quantity' and 'unitPrice' to  trigger the update method on blur - the error object  then contains the values:
![Screenshot 2022-04-20 at 15 51 41](https://user-images.githubusercontent.com/1161855/164259208-18cc721f-ed28-4160-8cf3-1ced05f474cd.png)
