### ISSUE TITLE
I want API only reset form state not values

### ISSUE THREAD

**Issue by yaeSakuras** [react-hook-form/react-hook-form#8231]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bluebill1049** [comment]
```
reset({
  ...getValues()
})
```

have you considered the above?

**Comment by yaeSakuras** [comment]
```getValues()```  my data is too big，so we want only reset eg: isDirty, Errors

**Comment by bluebill1049** [comment]
how big is your data?

**Comment by yaeSakuras** [comment]
> how big is your data?

reset must be hold data is slow，I want to update incrementally。

**Comment by bluebill1049** [comment]
```tsx
reset({
  ...getValues(),
})
```

above should reset both `isDirty` and `errors`, but curious about your data size and perhaps you want to provide an example in codesandbox?

**Comment by bluebill1049** [comment]
> reset must be all data is slow，I want to update incrementally。

I think i get what you mean now.

**Comment by yaeSakuras** [comment]
> 

my data about 200kb

**Comment by yaeSakuras** [comment]
> > reset must be all data is slow，I want to update incrementally。
> 
> I think i get what you mean now.

large form

**Comment by bluebill1049** [comment]
```tsx
reset(undefined, {
  keepValues: true
})
```

can you try above?

**Comment by yaeSakuras** [comment]
> 

OK，isDitry can reset?

**Comment by Moshyfawn** [comment]
> > 
> 
> OK，isDitry can reset?

All these form state values are been reset on `reset` method call, unless provided other-wise
![image](https://user-images.githubusercontent.com/16290753/164679562-bac4d278-5e35-4e68-a27e-edcd4871496f.png)

**Comment by bluebill1049** [comment]
`isDirty` would be tricky, because we literally need to know the new `defaultValues` before we can measure the form dirty.

```
reset(undefined, {
  keepValues: true,
  keepDirty: true, // however next keystroke it will measure again your current formValues with defaultValues, which leads dirty to update again.
})
```

**Comment by Moshyfawn** [comment]
Fair

**Comment by bluebill1049** [comment]
If your data is going to be 200kb, i think `keepValues` will make thing goes a bit faster, but without newly provided values, it's not going to work in your favor for a dirty form state, but `errors` will work as well. 

so result 

yes: increase perf 
no:  dirty 
errors reset: yes

**Comment by yaeSakuras** [comment]
> If your data is going to be 200kb, i think `keepValues` will make thing goes a bit faster, but without newly provided values, it's not going to work in your favor for a dirty form state, but `errors` will work as well.
> 
> so result
> 
> yes: increase perf no: dirty errors reset: yes

ok I try it then reply to you

**Comment by yaeSakuras** [comment]
> If your data is going to be 200kb, i think `keepValues` will make thing goes a bit faster, but without newly provided values, it's not going to work in your favor for a dirty form state, but `errors` will work as well.
> 
> so result
> 
> ✅ increase perf `keepValues` ❌ `keepDirty` you can only lie to it once. ✅ errors reset: yes

reset(undefined, {
    keepValues: true,
    keepErrors: false,
    keepDirty: false,
    keepIsSubmitted: false,
    keepTouched: false,
    keepIsValid: false,
    keepSubmitCount: false,
  })

I use above method。

My scene is rather special, my form is large 200kb about, so when I submit the form, I show update some field like apiCode, id form backend, I don't want to modify the whole form，but modify form after want reset form state like ditry,errors

**Comment by bluebill1049** [comment]
```diff
reset(undefined, {
  keepValues: true,
- keepErrors: false,
- keepDirty: false,
- keepIsSubmitted: false,
- keepTouched: false,
- keepIsValid: false,
- keepSubmitCount: false,
})
```

you can remove those they r default to false, is the perf gets better with it?

**Comment by bluebill1049** [comment]
I am going to close this issue, i don't think there is much we can do here to address the dirty issue, but do let us know if the above helps your perf issue.
