### ISSUE TITLE
[Feature] PathFiltered

### ISSUE THREAD

**Issue by maarlo** [react-hook-form/react-hook-form#8235]
In order to split and reuse code, I need to give as a parameter the path to the complex object is instead of the path to the final primitive.

Example:
 ```ts
type A = {
  b: string,
  c: number
}

type D = {
  a1: A
}

type E = {
  a2: A
}

//
const inputsA = (prefix: PathFiltered<UseFormType, A>, data: A): JSX.Element => (
  <>
    // name: Path<UseFormType>
    <button name={`${prefix}.b`} ... />
    <button name={`${prefix}.c`} ... />
  </>
)

const inputsD = () => (
  <>
    {inputsA('a1', data.a1)}
  </>
)

const inputsE = () => (
  <>
    {inputsA('a2', data.a2)}
  </>
)
```

I propose to add the ``PathFiltered`` type in order to solve the problem explained before. As the type will never be primitive, my proposed solution is:

```ts
/**
 * Type which eagerly collects all paths to a type (M) through a type (T).
 * @typeParam T - type which should be introspected
 * @typeParam M - type which should be used to filter the whole path
 * @example
 * ```
 * Path<{foo: {bar: string}},{bar: string}> = 'foo'
 * ```
 */
export type PathFiltered<T, M> = T extends ReadonlyArray<infer V>
    ? IsTuple<T> extends true
    ? {
        [K in TupleKey<T>]-?: PathImplFiltered<K & string, T[K], M>;
    }[TupleKey<T>]
    : PathImplFiltered<ArrayKey, V, M>
    : {
        [K in keyof T]-?: PathImplFiltered<K & string, T[K], M>;
    }[keyof T];

/**
 * Helper type for recursively constructing paths through a type
 * filtering for only those paths which ends in M.
 * @typeParam M - type which should be used to filter the whole path
 *
 * See {@link PathFiltered}
 */
type PathImplFiltered<K extends string | number, V, M> = V extends Primitive
    ? never
    : V extends M
    ? `${K}` | `${K}.${PathFiltered<V, M>}`
    : never;
```

**Comment by bluebill1049** [comment]
hey @maarlo thanks for the feature request, is this similar to this RFC: https://github.com/react-hook-form/react-hook-form/discussions/7354

**Comment by maarlo** [comment]
> hey @maarlo thanks for the feature request, is this similar to this RFC: #7354

Hello @bluebill1049, thank you for your fast response. Yes, it is similar to the RFC but, if ``register`` API is not changed as it is proposed in some comments, probably this solution could be better due to:

- register is not changed
- naming is similar to array  ``a.${index}.b`` 
- Instead of typing with FormValues, it is typed with the useForm type.

**Comment by bluebill1049** [comment]
@felixschorer would this conflict with current v8 type design?

**Comment by felixschorer** [comment]
@bluebill1049 this proposal is suggesting eager path types which leads to perfomance problems for large forms.

@maarlo RFC https://github.com/react-hook-form/react-hook-form/discussions/7354 is implemented in the V8 alpha already. You'll have to use `register(join(prefix, 'a'))`. Template strings are not supported due to lazy path evaluation.

> - Instead of typing with FormValues, it is typed with the useForm type.

I think you are mistaken. The solution proposed in RFC https://github.com/react-hook-form/react-hook-form/discussions/7354 uses the same type arguments.

**Comment by maarlo** [comment]
Hello @bluebill1049 @felixschorer, thank you for your responses. I think we can close this issue.
