### ISSUE TITLE
issue: 

### ISSUE THREAD

**Issue by devo-wm** [react-hook-form/react-hook-form#8245]
### Version Number

7.8.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-fieldsarray-yup-validation-min-length-forked-e5lyrd?file=/src/index.js

### Steps to reproduce

1. spread the register function to an input using the name of an array field (ie questions.${index}.text ) Pass the onChange option
2. The onChange method never seems to fire.

### Expected behaviour

Expected to see an alert during the onChange event of the input in the codesandbox above.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please use the latest version as `onChange` prop is introduced in the later version. https://github.com/react-hook-form/react-hook-form/releases/tag/v7.16.0

**Comment by bluebill1049** [comment]
thanks which example did you fork from on which page?
