### ISSUE TITLE
resetting hidden field not working

### ISSUE THREAD

**Issue by Hendrafoo** [react-hook-form/react-hook-form#825]
**Describe the bug**
When i try to reset() input:hidden, it does not work. but when i change the type="hidden" to type="text". the reset() works.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-get-started-596q6
2. Click on "SET VALUE TO ID"
3. See Console, id now filled
4. Click on "SUBMIT"
5. After call reset(), the id field goes back to previous value

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-get-started-596q6

**Expected behavior**
ID field now should be empty string

**Additional context**
Sorry for bad english :(

**Comment by bluebill1049** [comment]
no worries, i will take a look at it.

**Comment by Hendrafoo** [comment]
currently i solve it with passing {id: ''} to reset()

**Comment by bluebill1049** [comment]
that's strange. i am trying to solve a bug with the lib right now. i will come back to your issue :)

**Comment by bluebill1049** [comment]
Find out the reason why: https://stackoverflow.com/questions/6367793/why-does-the-reset-button-on-html-forms-not-reset-hidden-fields/6449276 you may have to stick to what you did above.
