### ISSUE TITLE
issue: Uncaught TypeError: Cannot read properties of undefined (reading 'substring')

### ISSUE THREAD

**Issue by dwome** [react-hook-form/react-hook-form#8256]
### Version Number

7.30.0

### Codesandbox/Expo snack

not available

### Steps to reproduce

Since the 7.30.0 release we are expecting issues when using the React Hook Form Controller.
When rendering the component the value and the options might be undefined.

This worked in 7.29.0 like a charm so we are downgrading for now.

Any ideas how to resolve this issue?

```
const {
    control,
    formState: { errors },
  } = useFormContext();
  return (
    <Controller
      control={control}
      name={props.name}
      render={({ field }) => (
        <UncontrolledSelect
          {...props}
          isClearable={true}
          inputRef={field.ref}
          options={options}
          onBlur={field.onBlur}
          value={field.value}
          error={errors[props.name]?.message}
          onChange={(v, action) => {
            field.onChange(v);
            props?.onChange && props?.onChange(v, action);
          }}
        />
      )}
    />
  );
```

### Expected behaviour

No crashing and handling undefined values like in 7.29.0

### Relevant log output

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'substring')
    at getNodeParentName (index.esm.mjs?682b:21:1)
    at isNameInFieldArray (index.esm.mjs?682b:23:1)
    at useController (index.esm.mjs?682b:353:1)
    at Controller (index.esm.mjs?682b:465:1)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848
