### ISSUE TITLE
Form validates on every keystroke after calling `reset`

### ISSUE THREAD

**Issue by zingerj** [react-hook-form/react-hook-form#8259]
### Version Number

7.30.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-reset-zurrv8

### Steps to reproduce

1. Enter a valid email and click on submit
2. The input should be cleared automatically
3. Start typing another email into the input
4. You should immediately see an error message

### Expected behaviour

On initial mount, the behavior is such that validation doesn't occur until the first time that the form is submitted. Therefore, a user can enter information (as a "work in progress") and only be alerted to errors once they submit. After calling `reset`, the validation seems to be occurring on each keystroke rather than waiting for the form to be submitted for the first time.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
It's the default behavior that you can change
```ts
interface UseFormOptions {
  reValidateMode: onChange | onBlur | onSubmit = 'onChange'
}
```
Refer to [RHF docs](https://react-hook-form.com/api/useform) to learn more:
> This option allows you to configure validation strategy when inputs with errors get re-validated after a user submits the form (onSubmit event). By default, validation is triggered during the input change event.

**Comment by zingerj** [comment]
But how can I replicate the behavior that the form starts with initially? Shouldn't calling `reset` truly reset the form back to its original state and behavior?

**Comment by Moshyfawn** [comment]
My bad, I read the description wrong, sry. Will take a look

**Comment by zingerj** [comment]
No worries, those docs were helpful! For now, I've set `reValidateMode` to be `onSubmit` to achieve the behavior that I'm looking for, but I would expect that calling `reset` resets the form altogether which should trigger the initial `mode`. Thanks!

**Comment by Moshyfawn** [comment]
@bluebill1049 I've never noticed this behavior before, but it seems like no matter if the form has been `reset` `onValid`, [the form's `isSubmitted` state is set to `true` after the successful submission callback](https://github.com/react-hook-form/react-hook-form/blob/394ae5d89a41f498cd7417a1ffc5fc088b0e8cca/src/logic/createFormControl.ts#L1065-L1073)
```js
finally {
  _formState.isSubmitted = true;
  _subjects.state.next({
    isSubmitted: true,
    ...
  });
}
```

I'm not really sure how deal with the issue; passing an additional parameter would determine whether to `reset` the form or not after the `onValid` would require passing the whole `defaultValues` or even `reset(defaultValues)` into `handleSubmit` like
```js
const handleSubmit = (onValid, onInvalid) => ({ shouldReset: boolean / reset(defaultValues) / smth else }) => async (e) => {}
```

**Comment by bluebill1049** [comment]
```tsx
React.useEffect(() => {
  if (formState.isSubmitSuccessful) {
    reset();
  }
}, [formState, reset]);
```

you want to reset after a successful submission.

**Comment by Moshyfawn** [comment]
Yea, but what's the point of resetting the form inside the `onSubmit` if it's gonna only partially reset the state; the form's validation behavior is gonna be the same as the form was never `reset`. If I remember correctly, it was an actual feature to be able to reset inside `onSubmit` at some point

**Comment by bluebill1049** [comment]
We made it works for form value, but we cannot change the execution order for the API, as reset does sit inside of submit function. We can look for way to get around it, but only if this becomes a larger issue consider there is work around.

**Comment by Moshyfawn** [comment]
I see your point. It still feels like the API is broken, tho.

[We have a comment](https://react-hook-form.com/api/useform/reset#example) in docs saying you can `reset` inside the `onSubmit` handler, but in reality, the result's gonna be different
```js
const onSubmit = (data) => {
  console.log(data);
  // with 7.22.0 you can reset here without useEffect
  // reset({ ...data })
};
```

**Comment by bluebill1049** [comment]
I am going to remove that update in the doc then, indeed execution do matters we can only do so much for the convient, especially for reset.

**Comment by bluebill1049** [comment]
doc updated: https://github.com/react-hook-form/documentation/commit/339747c2a446238843606aafc0a540a9f0a9901c
