### ISSUE TITLE
issue: Ugly error message for number field in yup example

### ISSUE THREAD

**Issue by Mikilll94** [react-hook-form/react-hook-form#8261]
### Version Number

V7 but this a docs bug

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-validationschema-rm35t

### Steps to reproduce

![image](https://user-images.githubusercontent.com/17653648/165634376-458e7e44-ef60-45b1-babc-e352aaa61db1.png)

1. Go to `https://codesandbox.io/s/react-hook-form-v7-validationschema-rm35t`
2. Click "Submit".
3. For "age" field we are receiving the following error: "age must be a number type, but the final value was: NaN (cast from the value `NaN."

### Expected behaviour

Age field should have a nice error like other fields, i.e. "age is a required field"

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This error message is produced by the schema unless we change the schema, but this is just for demonstration purposes. feel free to send a PR if you would like to change that and we can review it.
