### ISSUE TITLE
issue: UseWatch replacing UseEffect: how to use async calls inside the component using UseWatch...

### ISSUE THREAD

**Issue by john-evan08** [react-hook-form/react-hook-form#8264]
### Version Number

7.28.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-usewatch-forked-ojlnkx?file=/src/index.js

### Steps to reproduce

Just modify the lastname quickly

### Expected behaviour

The random value does not rerenders when the promise is resolved.  It is stored for the next call but is not rerendered ... How to rerender it when the promise is over, as for useState and useEffect behavior.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
It's not an issue with RHF, but rather the way React works. You can mutate a var outside a component. React won't detect the change as it's neither the prop nor the state change.

You want to move your `random` var inside a state inside a component.
