### ISSUE TITLE
Is there any side effect method or callback which can be invoked after the validation of input is executed (pass/fail) in case when mode is set to onBlur . Callback need to be specific to each input in form

### ISSUE THREAD

**Issue by kshitiz91** [react-hook-form/react-hook-form#8268]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Moshyfawn** [comment]
Please, don't spam the issues and discussions with the same question as well as follow the issue template if you want to have a productive conversation about your use case.

I'm gonna close this issue, because you've already created the same discussion
