### ISSUE TITLE
Can allow 'empty form' append in 'useFieldArray'?

### ISSUE THREAD

**Issue by tanmen** [react-hook-form/react-hook-form#827]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I want to create an empty form, as in previous versions.
When useFieldArray is used, the contents are required in append, so the behavior like the previous version cannot be performed.

**Describe alternatives you've considered**
Allows empty objects to be append, prepend, and insert.

**Additional context**
Not unique key problem may occur.

**Comment by bluebill1049** [comment]
can you share a codesandbox with this issue @tanmen ?

**Comment by tanmen** [comment]
https://codesandbox.io/s/react-hook-form-usefieldarray-7vdfv
↑Current version issues

https://codesandbox.io/s/react-hook-form-array-fields-s1kfh
↑'Add friend' function I expect

**Comment by bluebill1049** [comment]
can you pass an empty object?

**Comment by tanmen** [comment]
ok! i try it :)
