### ISSUE TITLE
Opt-out from disabled field behavior

### ISSUE THREAD

**Issue by nemonemi** [react-hook-form/react-hook-form#8275]
**Is your feature request related to a problem? Please describe.**
I have an application using Material-UI. Mui doesn't handle the readOnly property well. There are no selectors to apply styles properly.

When I want to have fields that have values but cannot be edited I have either an option to use prop `disabled` and have no value, or suggested prop `readOnly` and have no styles. 

**Describe the solution you'd like**
I would like an option to use the `disabled` property but show the values to users.

**Describe alternatives you've considered**
Hacking the form to update the disabled form fields with default values.

This doesn't quite work because if the form component is refreshed, the fields will become empty again.

**Comment by bluebill1049** [comment]
```tsx
<fieldset disbaled>
  // your input
</fieldset>
```

you can do the above instead.

**Comment by nemonemi** [comment]
I've seen that in the documentation, but that doesn't really help. 

This issue has been resolved by updating the library.

**Comment by bluebill1049** [comment]
seeking for a generic solution for both uncontrolled/controlled component so it would work both for web and react native.

**Comment by josiahwiebe** [comment]
I'd like to visually display some inputs as disabled, but still maintain the defaultValues as provided. This previously worked with RHF6 but now that I've upgraded to v7, it doesn't work. Any thoughts on how I could do this?

❌ `readOnly='true'` - doesn't work for checkboxes
❌ `disabled='true'` - value doesn't get passed to the form
❌ `<fieldset disabled='true'>` - doesn't work for my usecase as there is a list of options in which only some need to be disabled

One workaround I considered was putting each input in a `<fieldset>` and disabling as needed but I'm not sure it's the right approach. Any thoughts @bluebill1049?

**Comment by bluebill1049** [comment]
> One workaround I considered was putting each input in a <fieldset> and disabling as needed but I'm not sure it's the right approach. Any thoughts @bluebill1049?

you can have one <fieldset> for the entire form. also future feature: https://twitter.com/HookForm/status/1577422999560806402
