### ISSUE TITLE
issue: disabled does not register correctly 

### ISSUE THREAD

**Issue by reinertisa** [react-hook-form/react-hook-form#8277]
### Version Number

7.30.0

### Codesandbox/Expo snack

https://codesandbox.io/s/optimistic-haslett-zeglbj?file=/src/App.js

### Steps to reproduce

1. Go to 'codesandbox'
2. Click on 'Submit button'
3. Go to console
4. gender value is not "undefined"

### Expected behaviour

gender value should be undefined. When you comment useEffect and click submit, gender returns undefined but without useEffect, I do not see initial value(Male) on select box. Instead I see Female.  I want to see my initial value(Male) on select box and when I click submit, gender should return undefined. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Why not provide `defaultValue` on the input field or `defaultValues` on `useForm`?

**Comment by reinertisa** [comment]
We are covering both cases. Form level it works as you said but we are also trying field level.

**Comment by Moshyfawn** [comment]
https://codesandbox.io/s/morning-rgb-y0fc6f?from-embed=&file=/src/App.js

**Comment by reinertisa** [comment]
Thank you so much. It worked. @Moshyfawn

**Comment by Moshyfawn** [comment]
Sry for the lack of explanation. I was from my phone :P

I'm glad it helped!
