### ISSUE TITLE
issue: commonjs and esmodule bundles collision

### ISSUE THREAD

**Issue by isRostCompany** [react-hook-form/react-hook-form#8281]
### Version Number

7.30.0

### Codesandbox/Expo snack

https://github.com/isRostCompany/react-hook-form-dependant.git

### Steps to reproduce

- `git clone https://github.com/isRostCompany/react-hook-form-dependant.git bundlesCollision`
- `cd bundlesCollision`
- `npm i`
- `npm test`
- navigate to http://localhost:3001/
- open developer tools
- reload page
- step through both `debugger` statements (F8) and note that:
   - below first `debugger` statement we require `cjs` bundle 
   - above second debugger statement we require `esm` bundle
- take a look at `src/index.ts` and note console statement at `line 6`, then check in browser console if equality holds
- then navigate to `node_modules/@isRostCompany/react-hook-form-dependency/dist/index.js` and check that we do indeed assign value of `useFormContext` to `window.fromReactHookFormDependency`

Additional
- in `tsconfig.json` replace `line 3` with `"module": "CommonJS",`
- `npm test`
- navigate to http://localhost:3001/
- open console
- check if equality holds now

### Expected behaviour

- I would expect that there should be some way for me to ignore how `@isRostCompany/react-hook-form-dependency` requires its peer dependency and not impose any restrictions on how my repo should be written 

- right now we have two separate (meaning completely different objects) `useFormContext` hooks and I am unable to use `@isRostCompany/react-hook-form-dependency` because inside `useFormContext` returns `null` 
- if I want to fix that, I need to change my tsconfig to use `"module": "ESNext"` and that is kind of an issue for current project

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
unless this is a common issue that most users are facing or I prefer to keep it as it is with our current build step for the bundle produce.

**Comment by bluebill1049** [comment]
if more users encounter such issues, feel free to leave this issue but for now, it's won't be changed.
