### ISSUE TITLE
issue: the cloneObject function does not copy the object properly.

### ISSUE THREAD

**Issue by airman5573** [react-hook-form/react-hook-form#8300]
### Version Number

7.30.0

### Codesandbox/Expo snack

https://codesandbox.io/s/condescending-fermi-i9zu3z?file=/src/index.ts:0-1106

### Steps to reproduce

[here](https://github.com/react-hook-form/react-hook-form/blob/553f8d6f3e939c6978a35d9d4c63791d9e2cef94/src/utils/cloneObject.ts#L16)

as you can see, if the `data[key]` is function then `copy = data`;

### Expected behaviour

```
const obj1 = {
  greet: (greet: string) => {
    console.log(greet);
  },
  nested: {
    nestedName: "by"
  },
  name: "yoon"
};

const obj2 = cloneObject(obj1);

obj1.nested.nestedName = "cool";
obj1.name = 'jake';

console.log(obj2);
```
the `obj2.nested.nestedName` should be `by` not `jake`  
the `obj2.name` should be `yoon` not `cool`  

I thinks this code works well !
```
if (isFunction(data[key])) {
    copy[key] = data[key];
    continue;
}
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
would you like to send a PR with some unit test coverage for the above scenario?

**Comment by airman5573** [comment]
> would you like to send a PR with some unit test coverage for the above scenario?

Thanks, I will
