### ISSUE TITLE
issue: input not focused on error inside fieldset

### ISSUE THREAD

**Issue by Moshyfawn** [react-hook-form/react-hook-form#8302]
### Version Number

7.30.0

### Codesandbox/Expo snack

https://codesandbox.io/s/loving-lehmann-4pwl0r?file=%2Fsrc%2FApp.tsx

### Steps to reproduce

1. Go to [CSB](https://codesandbox.io/s/loving-lehmann-4pwl0r?file=%2Fsrc%2FApp.tsx)
2. Click on 'Submit Query'
3. See input field not focused

- Notice, that the `fieldset` has the `disabled` attribute defined
```jsx
<fieldset disabled={isSubmitting} />
```
- `isSubmitting` is always `false`, so the inputs inside it are never `read-only`

### Expected behaviour

The input should be focused `onSubmit`, if the validation fails even inside the `fieldset` element with the `disabled` attribute set

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
@Moshyfawn I think this one is tricky, as the field state remains `isSubmitting` during the invalid callback, and then set isSubmitting to false in the `finally` section. So the input will remain disabled and can't be focused.

**Comment by Moshyfawn** [comment]
Hm.. Bare with me, 'cuz I feel like I'm missing something.

Would it be problematic to, say, pipe the `isSubmitting: false` after the `onInvalid` callback?

Like, currently I'm working around the behavior by setting each input as read-only, which is fine, but disabling a `fieldset` of inputs is much easier to reason about.

And I'm not proposing the change; just trying to see if it would be reasonable and if at all possible to look into supporting this `fieldset` behavior. 'cuz I believe, we've recommended to use `fieldset` like that in the past multiple times.

**Comment by bluebill1049** [comment]
Yea, that's a trigger one, it needs to happen after the next render. see step 5 (not within the onSubmit handler).

**Comment by Moshyfawn** [comment]
Damn, I see the problem. Would be cool to support the behavior, tho..

Oh, well, I guess we can close the issue at this stage

**Comment by Moshyfawn** [comment]
Yep, did the same only to get stuck in the same way you did with the render phase :P
