### ISSUE TITLE
issue: Controller with shouldUnregister: true inside of field array causes value to be lost when form is reset

### ISSUE THREAD

**Issue by ajwootto** [react-hook-form/react-hook-form#8307]
### Version Number

7.30.0

### Codesandbox/Expo snack

https://codesandbox.io/s/snowy-sky-0zuexz?file=/src/App.js

### Steps to reproduce

1. Visit codesandbox
2. Observe that current form state is missing the "name" field from each entry
3. Modify a name, observe that names are now present in the form state
4. Hit "save" on the form
5. Observe that the form state briefly contains the input's values, but is then wiped because the Controllers are unmounted on every form reset (due to the ids of the field array changing)

Basically when shouldUnregister is enabled on these Controller components that are within a FieldArray, resetting the form causes them to get unmounted due to the fact that the ids of the field array entries are reset every time the form is reset. Therefore, even though the data is still initially present in the form state after the reset, it gets wiped when these Controllers unmount and remount themselves.

It can also be seen that the plain "input" field registered to "age" does not exhibit this behaviour despite also using shouldUnregister, and the form state stays consistent for the "age" field through form resets.

### Expected behaviour

I would expect to be able to use a Controller this way without losing the values in form state. My use case is that I have a form which is reset upon submission using the latest data from the server. The form contains a field array. Each entry in the array also has some inputs which appear or disappear depending on certain things. Therefore I would like for those inputs to have "shouldUnregister" so that when they actually disappear from the page, their values are removed. However, in this scenario the values are getting removed from form state every time "reset" is called, even when resetting the form with data that should go in those inputs. The "reset" is causing the field array ids to change, which is causing an unmount and remount of the Controller components.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Why `register` is different from `Controller` in terms of unmounting behavior.

`register`: unmounted input will need to notify at either useForm, or useWatch's useEffect for hook form to verify input is unmounted from the DOM.

<img width="946" alt="Screen Shot 2022-05-05 at 11 04 19 am" src="https://user-images.githubusercontent.com/10513364/166850225-3188307f-8cf7-4852-a7b8-003961c054c7.png">

`Controller` does have its own `useEffect`, as it's a wrapper component

> Input will be unregistered after unmount and defaultValues will be removed as well.

<img width="943" alt="Screen Shot 2022-05-05 at 11 05 32 am" src="https://user-images.githubusercontent.com/10513364/166850292-2eda322d-327d-4b77-997d-de3716e123bf.png">

To get precise `unregsiter` value behavior, I would recommend invoking `unregister` method according to your state update.

**Comment by ajwootto** [comment]
@bluebill1049 thank you for the detailed answer

For my own understanding, I had a couple followup questions

I don't think I'm clear on the point about the "register" input needing to "notify at useForm or useWatch". Does that basically just mean that the component which renders the input that is being unmounted needs to make a call to `useWatch` or `useForm`? I believe in my example that is the case, but just to be sure I also added a "useWatch" to the FieldArrayEntry component and it seems to behave the same.

I am also wondering why the inputs that are controlled by the Controller are not being "cleared" when the form is reset. If they are controlled components shouldn't they be reflective of what's currently in the form state?

Thanks for your time!

**Comment by bluebill1049** [comment]
> I don't think I'm clear on the point about the "register" input needing to "notify at useForm or useWatch". Does that basically just mean that the component which renders the input that is being unmounted needs to make a call to useWatch or useForm?

correct.

> I am also wondering why the inputs that are controlled by the Controller are not being "cleared" when the form is reset. If they are controlled components shouldn't they be reflective of what's currently in the form state?

The correct usage for `shouldUnregister` is when input is completely removed by the render, slot it inside the useFieldArray will cause an issue as u would know each user action will flushed change when id is updated. Hence I suggested you "control" your input mount/unmount and invoke `unregsiter` at your app level.
