### ISSUE TITLE
Ability to control how error scrolling occurs (scroll a bit more up)

### ISSUE THREAD

**Issue by osdiab** [react-hook-form/react-hook-form#8308]
**Is your feature request related to a problem? Please describe.**
When a validation error occurs, it correctly scrolls to the input, but the input is literally exactly aligned to the top of the screen. This isn't great since in our UI we show the label for the input and the actual error above the input itself, so it scrolls you there but you can't see what's going wrong.

**Describe the solution you'd like**
Be able to either scroll to the corresponding label, or have some kind of "buffer" to scroll some pixel amount above the input itself (preferable, honestly I would like it if it scrolled past the errant input a bit).

**Describe alternatives you've considered**
No real ideas besides this

**Additional context**
--

**Comment by bluebill1049** [comment]
until the browser has an API to support the focus position, I don't think there is much we can do in this library without adding a lot more code on top of the native focus event.

**Comment by Moshyfawn** [comment]
Well, I played around with [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView). In theory, we can refactor the `focus` API to use [it](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) and call `.focus` _(or `.select` when needed)_ after.

```ts
const focus = (ref, options?: boolean | ScrollIntoViewOptions) => {
  ref.current?.scrollIntoView(options)
  // INFO: obviously pass in the focus options or whatnot. This is just pseudo-code :P
  ref.current?.focus()
}
```

[scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) has all the API options to control the position, scroll "smoothness" etc.

**Comment by bluebill1049** [comment]
yes, @Moshyfawn which is something we probably could avoid, smooth has its own transition, and then we will have to worry about the duration and etc. we should stick with focus event as it works for both desktop and mobile apps without introducing any other code or workaround.

**Comment by Moshyfawn** [comment]
Oh, I'm not proposing to look into implementing it; just saying there're options.

I'm leaning towards to fact that RHF is **not** a focus management library and it's not out concern really how far to scroll.

That said, we do support text selecting with `.select` and it's not user's fault that they have their UI in a particular way, that doesn't go along with the default `.focus` behavior.

I'm trying to imaging if it's possible to handle the invalid input focus without the help of RHF. I don't have time to experiment ATM :(

Like, disable the focus on error behavior and subscribe to errors to create side-effects handling the input focus like
```js
useEffect(() => {
  errors.fieldName?.ref?.scrollIntoView()
}, [errors])
```

**Comment by bluebill1049** [comment]
Thanks for the feature request, but It's unlikely this gets implemented in the lib. Hope you understand the reasons above.

**Comment by osdiab** [comment]
That's a bummer, didn't really want this library to dictate our design. Guess I can fork it.

**Comment by bluebill1049** [comment]
We are not dictating the design, we are just using the focus event. If this is not desired behavior, yes you can fork it and adjust or just turn off `shouldFocusError: false` and do your own focus behavior. Either way, it works.

**Comment by osdiab** [comment]
ah is the idea that i would use the `ref` in the `errors` object on the `onInvalid()` callback passed to `handleSubmit()` to do this? as `shouldFocusError` does it's magic using the `register` order, is there any way for me to get that same ordering or do i need to implement that kind of logic myself?

**Comment by bluebill1049** [comment]
Pretty much. You can switch the "car" to manual :)

**Comment by osdiab** [comment]
For reference I got it working - this is what I did (in TypeScript; I don't use `CustomElement` as referred to in the `Ref` typing, so I just ignore those):


### the `onSubmit` handler

```tsx
        onSubmit={myForm.handleSubmit(
          (data) => {
            // do stuff on success
          },
          (errors) => {
            const fieldErrors = unwrapErrorsByRef([], errors);
            const sorted = fieldErrors
              .filter((v) => v.message && v.ref !== undefined)
              .map((v) => v.ref)
              .sort((a, b) =>
                a && "compareDocumentPosition" in a
                  ? b && "compareDocumentPosition" in b
                    ? a.compareDocumentPosition(b) ===
                      Node.DOCUMENT_POSITION_PRECEDING
                      ? 1
                      : -1
                    : 0
                  : 0
              );
            const element = sorted.find(
              (elem) => "getBoundingClientRect" in elem
            );
            if (element && "getBoundingClientRect" in element) {
              window.scrollTo({
                top:
                  element.getBoundingClientRect().top +
                  window.scrollY -
                  ERROR_SCROLL_BUFFER,
                behavior: "smooth",
              });
            }
          }
        )}
```

### the helpers:

```ts
// converts deeply nested errors to a flat array of errors
function unwrapErrorsByRef(errors: FieldErrors): FieldError[] {
  return unwrapErrorsByRefRecurse([], errors);
}

function unwrapErrorsByRefRecurse(memo: FieldError[] errors: FieldErrors): FieldError[] {
  for (const value of Object.values(errors)) {
    if ("ref" in value) {
      memo.push(value as FieldError);
      continue;
    }
    unwrapErrorsByRef(memo, value as FieldErrors);
  }
  return memo;
}
const ERROR_SCROLL_BUFFER = 100; // whatever the buffer should be in px
```

**Comment by Axxxx0n** [comment]
@osdiab I implemented the similar thing. The problem is that when you use `<Controller />` ref it dosen't have reference to element and dosen't have `getBoundingClientRect`. This ref has only focus and validation methods. @bluebill1049 The reasons for not implementing this in lib are sure valid and understandable. Maybe the solution would be to make refs in Controller reference the same as regular refs so we could then implement all custom solutions.
