### ISSUE TITLE
isDirty should remain false when using useFieldArray replace

### ISSUE THREAD

**Issue by damien-duignan** [react-hook-form/react-hook-form#8309]
**Is your feature request related to a problem? Please describe.**
When using [useFieldArray](https://react-hook-form.com/api/usefieldarray) `replace` function, `isDirty` is set to true. This is unexpected because the user hasn't interacted with the form yet. We're using `replace` to update the initial state coming from our API. 

**Describe the solution you'd like**
Allow an options object when using `replace`. Similar to [setValue](https://react-hook-form.com/api/useform/setvalue), we could pass `shouldDirty`.
```
replace([{ firstName: 'Damien' }, { firstName: 'John' }], { shouldDirty: false });
```

**Describe alternatives you've considered**
- Using `setValue` to set the values actually solves this issue; `isDirty` remains false. But according to the [setValue](https://react-hook-form.com/api/useform/setvalue) docs, using `replace` is recommended when setting field array values.
- Setting `defaultValues` in `useForm` hook. But setting deeply nested form values is not supported

**Comment by bluebill1049** [comment]
Thanks for the feature request, putting it into the project board.

**Comment by Moshyfawn** [comment]
I guess it's related to that extending of field array methods we wanted to do to include options like `shouldFocus` and such

**Comment by bluebill1049** [comment]
pretty much @Moshyfawn.

**Comment by ShivamJoker** [comment]
@bluebill1049 would be great to have this fixed.

**Comment by Moshyfawn** [comment]
It's not that simple, unfortunately.

Field array methods don't currently support the `should` flags like, say, the `setValue` method does. So, if we want to provide an ability to configure dynamically setting the `isDirty` flag with `replace`, it's actually dealing with the whole set of field array methods and adding the `should` flags to them as well.

**Comment by JongSikLim** [comment]
I need this feature, too

**Comment by kuus** [comment]
hi @bluebill1049 I am not sure I understand what is the status of this issue?
