### ISSUE TITLE
useFieldArray with async-loaded defaultValues

### ISSUE THREAD

**Issue by tomas-c** [react-hook-form/react-hook-form#832]
**Is your feature request related to a problem? Please describe.**
I couldn't see an easy way to use the useFieldArray hook with asynchronously loaded default values. 

Here's my attempt:

https://codesandbox.io/s/react-hook-form-usefieldarray-1j0yg

Pressing "Load Defaults" button in the sandbox does nothing, I assume because useForm does not detect changes in defaultValues.

**Describe the solution you'd like**

Make useForm detect changes in defaulValues and ensure this works with useFieldArray.

**Describe alternatives you've considered**
I could not find an alternative that would work with useFieldArray hook but it's possible not to use useFieldArray and go manual route as in the following example: 

https://codesandbox.io/s/react-hook-form-field-array-advanced-with-delete-insert-append-edit-l19pz

**Comment by tomas-c** [comment]
Just found another alternative: use `reset(newDefaultValues)` to set async-loaded defaults , that seems to work well with useFieldArray

**Comment by bluebill1049** [comment]
oh cool! that you work it out.

**Comment by chrisbag** [comment]
Hello @bluebill1049 
I am also facing a similar issue. I have some FieldArrays which must be set using the results of an async request.

(here is a CSB example : https://codesandbox.io/s/react-hook-form-field-array-pw82j?file=/src/App.js)

setValue only updates the input fields if some initial values are present. 
Is reseting the form values the react-hook-form recommended way of populating fieldArrays ?
How come after reseting the field values with the results of the async request and removing all the fields using the remove button, do the formValues reset themselves to the values set by the async request 

Thanks a lot for your help and this awesome library

**Comment by magalhaespaulo** [comment]
this solve the problem

```ts
const defaultValue = [
  { price: 20, size: 'small' },
  { price: 40, size: 'large' },
]

const { ..., update } = useFieldArray({
  name: 'example',
  control,
})

useEffect(() => {
  defaultValue.forEach((field: { [key: string]: any }, index: number) => {
    Object.keys(field).forEach((key) => {
      update(index, field[key])
    })
  })
}, [defaultValue, update])

```


```html
<input
  ...
  defaultValue={defaultValue?.[index]?.[key]}
/>
```
