### ISSUE TITLE
Calling useFieldArray hook methods does not update formState.dirty value

### ISSUE THREAD

**Issue by tomas-c** [react-hook-form/react-hook-form#833]
**Describe the bug**

Calling useFieldArray hook methods does not update formState.dirty value.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-popep
2. Click on APPEND
3. Observe that formState hasn't changed

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-popep

**Expected behavior**
append, prepend, remove, swap, move, insert should all update dirty state to true

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome Version 79.0.3945.117 (Official Build) (64-bit)
 - Version 4.5.2

**Additional context**

**Comment by bluebill1049** [comment]
hmm that's an interesting one. Should it dirty the form or not? If anyone else reading this issue, let me know your thoughts. 

- dirty / !pristine means the user has made a modification

i guess it kind makes sense that they have added a new field.

**Comment by JeromeDeLeon** [comment]
I think it’s best to think of that way as @tomas-c said.

**Comment by bluebill1049** [comment]
let me know if this beta fix the issue. react-hook-form@4.5.3-beta.2

**Comment by tomas-c** [comment]
That fixed it for me but found one strange case, left a comment about it in #839

**Comment by tomas-c** [comment]
@bluebill1049  still having trouble with 4.5.4

I've updated https://codesandbox.io/s/react-hook-form-usefieldarray-9u12n to use 4.5.4

1. Append a field
2. Observe dirty=true  👍 
2. Click on the appended field and then outside it to trigger onBlur
3. Observe dirty=false 😢 
4. Delete the appended field
5. Observe dirty=true 😢

**Comment by bluebill1049** [comment]
thanks, I will take a look again tmr 👍

**Comment by bluebill1049** [comment]
> Click on the appended field and then outside it to trigger onBlur
> Observe dirty=false 😢

patched

**Comment by tomas-c** [comment]
I've updated https://codesandbox.io/s/react-hook-form-usefieldarray-9u12n to use 4.5.5, seems to still happen

**Comment by bluebill1049** [comment]
> I've updated https://codesandbox.io/s/react-hook-form-usefieldarray-9u12n to use 4.5.5, seems to still happen

i only highlight scenario 2 (the crying face), still working on the last one.

**Comment by bluebill1049** [comment]
updated: https://codesandbox.io/s/react-hook-form-usefieldarray-yikiz @tomas-c if you want to double confirm. we aim to release this during this weekend.

**Comment by tomas-c** [comment]
THere's something weird happening there with 4.5.6-beta4...

1) Reload
2) Press append
3) Observe the state is incorrectly set to dirty=false
4) Press append again
5) Observe the state is correctly set to dirty=false
6) Press inside the last field and then outside it so that onBlur is
triggered
7) Observe the state is incorrectly set to dirty=false again

**Comment by bluebill1049** [comment]
> There's something weird happening there with 4.5.6-beta4... 1) Reload 2) Press append 3) Observe the state is incorrectly set to dirty=false 4) Press append again 5) Observe the state is correctly set to dirty=false 6) Press inside the last field and then outside it so that onBlur is triggered 7) Observe the state is incorrectly set to dirty=false again

thanks for testing. i miss this onBlur part.

**Comment by bluebill1049** [comment]
thanks for testing @tomas-c 

https://codesandbox.io/s/react-hook-form-usefieldarray-yikiz

let me know if the above CSB solve all the issues.

**Comment by tomas-c** [comment]
With 4.5.6-beta5

1. Refresh
2. Append twice
3. Delete middle two
4. onBlur on the first one
5. Observe the state is dirty=false but should be true

**Comment by bluebill1049** [comment]
thanks @tomas-c again https://codesandbox.io/s/react-hook-form-usefieldarray-yikiz patched

**Comment by tomas-c** [comment]
@bluebill1049 I can still reproduce the issue using the same steps as in the previous message

**Comment by bluebill1049** [comment]
> @bluebill1049 I can still reproduce the issue using the same steps as in the previous message

hmmm sorry looks like it's still broken... i will take a look again tonight. thanks for the testing and patient.

**Comment by bluebill1049** [comment]
Try this one: https://codesandbox.io/s/react-hook-form-usefieldarray-yikiz

I have tested your test above, i was try to get aways dirty check with length compare, looks like there is no shortcut. let me know how this one goes. thanks

**Comment by tomas-c** [comment]
Couldn't find any issues with this one, thanks!

**Comment by bluebill1049** [comment]
oh man finally! thank you! merging

**Comment by bluebill1049** [comment]
i found another issue and fixing FYI

**Comment by phuhd-0935** [comment]
@bluebill1049 
Do you have any option for this ?
I want to keep `formState` does not update after `useFieldArray hook methods` was called.
Example, button `Save` will be enable after user change `input` each row. https://codesandbox.io/s/rhf-xicl9?file=/src/App.js:605-610

**Comment by bluebill1049** [comment]
> @bluebill1049
> Do you have any option for this ?
> I want to keep `formState` does not update after `useFieldArray hook methods` was called.
> Example, button `Save` only enable after user change `input` each row. https://codesandbox.io/s/rhf-xicl9?file=/src/App.js:605-610

you mean click `append` affect the `dirtyFields`?

**Comment by phuhd-0935** [comment]
yes 🙇

**Comment by bluebill1049** [comment]
if you take a look at our project board: https://github.com/react-hook-form/react-hook-form/projects/1

it's a pending feature request: https://github.com/react-hook-form/react-hook-form/projects/1 if you need this feature, you can upvote it, then we will consider building into the lib in the future release. 👍
