### ISSUE TITLE
issue: handlesubmit not handling fileLists correctly

### ISSUE THREAD

**Issue by stormmuller** [react-hook-form/react-hook-form#8339]
### Version Number

7.31.0

### Codesandbox/Expo snack

https://codesandbox.io/s/polished-silence-dmq5gx?file=/src/App.js

### Steps to reproduce

1. https://codesandbox.io/s/polished-silence-dmq5gx?file=/src/App.js
2. Fill in the form
3. open the console
4. See type of the file type input
5. Switch to version 7.30.0
2. Fill in the form
3. open the console
4. See type of the file type input

### Expected behaviour

The file type input should be of instance FileType List and not a plain Object

### What browsers are you seeing the problem on?

Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stormmuller** [comment]
This is an issue when using the result to build `FormData` to submit multipart form data to an API

**Comment by bluebill1049** [comment]
fixed thanks.
