### ISSUE TITLE
Triggering validation on input change in a field array causes form to slow down massively

### ISSUE THREAD

**Issue by aquibbaig** [react-hook-form/react-hook-form#8340]
### Version Number

^7.25.0

### Codesandbox/Expo snack

https://codesandbox.io/s/icy-star-k2r86u?file=/src/Form.tsx

### Steps to reproduce

uncomment L81 or L51-55 on `Form.tsx`.

I have a use case where the RHS input of the form should always be unique. I would like to validate that onChange of the input. So, I manually used to call `trigger` on input change. Like this:
<img width="535" alt="Screenshot 2022-05-11 at 11 59 27 AM" src="https://user-images.githubusercontent.com/26324376/167783170-2671082e-8a76-46ab-b7e1-845af4049b1a.png">

But that slows down the typing in the input field massively (which is obvious as other fields are being validated and possibly re-rendered). If I do not do this then the validation kicks in on calling `append` of the field array or form submit.

If I remove onChange validation with trigger then the previous field error doesn't go away.
<img width="530" alt="Screenshot 2022-05-11 at 11 58 33 AM" src="https://user-images.githubusercontent.com/26324376/167783037-c13c9442-7111-4973-8dd6-140cb99d2134.png">

Do we have any workarounds for this use case?

### Expected behaviour

errors should be reflected on change, if field at input at 1st place is "John" and I type John again on input at 20th place, then both the fields(inputs) should show the error state.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
not an issue with this library, it's the result of your large form data and schema validation logic.

**Comment by aquibbaig** [comment]
@bluebill1049 Thanks for the clarification, any tips to tackle the situation?
