### ISSUE TITLE
issue: keepDirtyValues only keeps values if "dirtyFields" is deconstructed from fieldState

### ISSUE THREAD

**Issue by uncvrd** [react-hook-form/react-hook-form#8341]
### Version Number

7.31.1

### Codesandbox/Expo snack

https://codesandbox.io/s/tender-panini-o8to91?file=/src/App.js

### Steps to reproduce

Hey! I've been following the discussion #8233 closely regarding `keepDirtyValues`, thank you for implementing this so quickly. However, I believe I discovered a strange bug while using this feature.

It appears that in order for `keepDirtyValues` to actually "keep" the dirty values, the `dirtyFields` property from `fieldState` must be deconstructed. I've been using the CodeSandbox you had posted in the RFC, and so I've just re-linked that as my reproduction sandbox. But here's a video demo explaining the issue. Important timestamps:

0:00: Form is set up the way you had shared initially with `dirtyFields` deconstructed. Typing in a value and clicking `fetch` **kept my dirty value of `bill!!!`** <-- correct behavior

0:18 I remove the `dirtyFields` from being deconstructed, and refresh. Typing in a value and clicking `fetch` **overrides my dirty value of `bill!!` back to the network state of `bill`** <-- incorrect behavior

https://user-images.githubusercontent.com/25097099/167786626-d16663f6-49de-4755-9ee0-8ad0a5f54b1a.mov

This one really threw me for a loop as I don't understand why a specific property needs to be deconstructed, but this is what I managed to discover. I can also re-create this in my personal project by removing/adding the deconstruction 🤯 

Really hope this helps - let me know if there's anything else I can provide.

### Expected behaviour

I expect to not have to deconstruct `dirtyFields` in order for `keepDirtyFields` to work correctly. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

---
EDIT: Okay, FWIW - the `dirtyFields` doesn't have to be deconstructed, it just needs to be a part of the code somewhere. For example, if you `console.log(fieldState.dirtyFields)`. That will cause it to work correctly

**Comment by bluebill1049** [comment]
expected behavior, dirty fields need to be subscribed because we can identify what fields are dirty.

**Comment by Moshyfawn** [comment]
I believe, it's something got to do with the fact that `formState` is a `Proxy` object. That means that you gotta subscribe to the particular form state in order to see changes.

**Comment by bluebill1049** [comment]
update doc to include the above note.

**Comment by uncvrd** [comment]
@Moshyfawn Thanks for clarifying that this is expected behavior! However I might say that leaving an unused `dirtyFields` deconstructed just to subscribe runs the risk of having another team member see an unused property and simply removing it without knowing that it affects the fields. I'm new the concept of a Proxy in js so maybe I'm thinking about it wrong, is there a more graceful way (on my end) to handle this instead of leaving an unused deconstructed `dirtyFields`?

**Comment by bluebill1049** [comment]
write s test case (so your team member aware this will break and hence reason xxx) if your use case really doesn't use `dirtyFields`, but only wants to keep `dirtyFields` within the `reset`.
