### ISSUE TITLE
issue: useFieldArray only updates errors for the field that was interacted with

### ISSUE THREAD

**Issue by christianlundberg** [react-hook-form/react-hook-form#8344]
### Version Number

7.31.1

### Codesandbox/Expo snack

https://codesandbox.io/s/bold-fast-r8bi6i?file=/src/App.js

### Steps to reproduce

1. Type a string into any of the fields 
2. Type the same thing (duplicate) into a different field
3. The error message only appears for the field you interacted with last

Here you will notice within the schema I logged the amount of errors (2), but in the component when I log the actual errors object, only the last field has an error, which is the last one I interacted with.
![image](https://user-images.githubusercontent.com/29963339/167953544-354873fa-b864-4c5b-88fa-33f122f6a11b.png)

### Expected behaviour

The schema validates that every value in the array must be unique, thus when typing the same thing in two fields you should see the error for both fields. If you update any of the fields so that they're now different, the errors should disappear from both as well.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/useform

> Schema validation focus on the field level for error reporting. Parent level error look is only limited to the direct parent level that is applicable for components such as group checkboxes.

use `trigger` if you want to have form-level error

**Comment by christianlundberg** [comment]
@bluebill1049 `trigger('numbers')` would show errors even for fields that aren't dirty, for example if the fields also had the `required()` validation

**Comment by bluebill1049** [comment]
use `dirtyFields` to conditional show errors instead then?

**Comment by christianlundberg** [comment]
Array fields are always dirty when you append them.
