### ISSUE TITLE
issue: Controller does not maintain referential equality of value.

### ISSUE THREAD

**Issue by cullylarson** [react-hook-form/react-hook-form#8346]
### Version Number

7.31.1

### Codesandbox/Expo snack

https://codesandbox.io/s/beautiful-darkness-n8uvwd?file=/src/App.tsx

### Steps to reproduce

1. Use Controller to change the value of a field to an object.
2. When that Controller renders again, the `value` provided by Controller should now equal the field value (i.e. the two objects should be referentially equal). But they aren't.

### Expected behaviour

When that Controller renders again, the `value` provided by Controller should now equal the field value (i.e. the two objects should be referentially equal).

FYI, this issue doesn't occur in v7.8.4 (I encountered the issue after upgrading from this version).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I am not sure why would you need to check the reference equivalent with what value gets provided by the controller, curious to know the rationale.

**Comment by cullylarson** [comment]
> I am not sure why would you need to check the reference equivalent with what value gets provided by the controller, curious to know the rationale. To be honest, i don't think this would be fixed if was very specific use case.

I have a group of radio inputs. I need to know which one is selected. It's similar to the CodeSandbox example. I.e a component takes a set of options and a `value` (from `Controller`) and marks the selected option as `checked`.

**Comment by bluebill1049** [comment]
Marking the one is checked? shouldn't this be a state issue? a piece of state should derive what's selected rather than checking the value reference equivalent. 

> It seems like this would be a common use case.

I am not sure about this above, I either have encountered such a problem neither any of the test cases cater for such usage.

**Comment by cullylarson** [comment]
> Marking the one is checked? shouldn't this be a state issue? a piece of state should derive what's selected rather than checking the value reference equivalent.
> 
> > It seems like this would be a common use case.
> 
> I am not sure about this above, I either have encountered such a problem neither any of the test cases cater for such usage.

@bluebill1049 This is how [@headlessui/react](https://headlessui.dev/) implements their [RadioGroup](https://headlessui.dev/react/radio-group) and [Listbox](https://headlessui.dev/react/listbox) (uses value equality to determine which option is selected).

**Comment by bluebill1049** [comment]
btw, I am not here to judge how UI should implement their state check for user's selection.

```
function MyListbox() {
  const [selectedPerson, setSelectedPerson] = useState(people[0])

  return (
    <Listbox value={selectedPerson} onChange={setSelectedPerson}>
      <Listbox.Button>{selectedPerson.name}</Listbox.Button>
      <Listbox.Options>
        {people.map((person) => (
          /* Use the `active` state to conditionally style the active option. */
          /* Use the `selected` state to conditionally style the selected option. */
          <Listbox.Option key={person.id} value={person} as={Fragment}>
            {({ active, selected }) => (
              <li
                className={`${
                  active ? 'bg-blue-500 text-white' : 'bg-white text-black'
                }`}
              >
                {selected && <CheckIcon />}
                {person.name}
              </li>
            )}
          </Listbox.Option>
        ))}
      </Listbox.Options>
    </Listbox>
  )
}
```

I see no problem with the above example where the user selection is derived from the state select instead.

**Comment by cullylarson** [comment]
> I see no problem with the above example where the user selection is derived from the state select instead.

@bluebill1049 The problem is that if you use `react-hook-form` to control the state of `selectedPerson`, and use a `Controller` to pass the value into `MyListbox`, then `selected` will never be true.

**Comment by bluebill1049** [comment]
see my updated comment ^

**Comment by cullylarson** [comment]
> If it's an object (reference) check then this library is not going to play nicely, which i am happy to take that as a design limitation.

I mentioned headlessUI in response to your comment, "I either have encountered such a problem," to show that at least one very popular UI library is using that pattern.

Also, FYI, this is seemingly a breaking change (some time since v7.8.4). v7.8.4 maintained referential equality of values. And, just to point out, this seems to only be an issue with `Controller`. `useForm` seems to maintain referential equality (see the CodeSandbox example).

**Comment by bluebill1049** [comment]
I am sorry to hear that it break your stuff, but it's not an intentional breaking change, either it's covered in any of our test cases. `useController` use `useWatch` internally instead `useState`, for an object like or array-like we do apply shallow clone for each value to flush out a new update. I hope you can find a way to do a value check instead of a reference. other than that you can stay with version 7.8.4 as this is not something we would fix or consider rolling back.

**Comment by bluebill1049** [comment]
I am going to update the missing changelog after work as well.
