### ISSUE TITLE
issue: first input radio checkbox not checked in Preact with watch method 

### ISSUE THREAD

**Issue by lucasjuna** [react-hook-form/react-hook-form#8351]
### Version Number

7.3.1.1

### Codesandbox/Expo snack

https://codesandbox.io/s/priceless-moser-566pw5?file=/src/index.js

### Steps to reproduce

With Preact framework checkboxes not working correctly with watch method.
Try to click on first checkbox, it's not checked. But if you comment this line `console.log(watch("radio"));` - issue will disappear.

### Expected behaviour

First checkbox should be checked on click.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is an issue with Preact, could you send an issue at Preact instead: https://codesandbox.io/s/recursing-wood-do38uo?file=/src/index.js

![Screen Shot 2022-05-13 at 9 06 47 am](https://user-images.githubusercontent.com/10513364/168181432-98986f7e-1574-4556-b451-665a49c61ed5.png)

ref callback doesn't guarantee radio input is mounted.

**Comment by JamesWong1999** [comment]
Related issue: https://github.com/preactjs/preact/issues/2341

**Comment by bluebill1049** [comment]
This is something I hope should address in preact end, in the meantime, I am removing the `live` check in the codebase. All tests seem to pass, but if this raises an issue I am going to revert it back and attach unit tests coverage and expect to preact to hopefully address it on their end.

**Comment by bluebill1049** [comment]
nvm, this will cause issues and lead to breaking change. https://github.com/react-hook-form/react-hook-form/pull/8353 we will have to reply on Preact to address this problem 🙏 .

**Comment by bluebill1049** [comment]
forgot to mention workaround: use `useController` or `Controller`
