### ISSUE TITLE
issue: In Preact framework error shown when click on first checkbox after it was hidden

### ISSUE THREAD

**Issue by lucasjuna** [react-hook-form/react-hook-form#8352]
### Version Number

7.3.1.1

### Codesandbox/Expo snack

https://codesandbox.io/s/frosty-violet-xdl673?file=/src/index.js

### Steps to reproduce

1. Click on Submit button
2. Click on Toggle button
3. Click on first checkbox
4. See error text

https://user-images.githubusercontent.com/74837184/168144921-2de85869-4e56-4f0c-85dd-c328155e370c.mp4

### Expected behaviour

Error text should not be shown. In React framework it's working properly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
It looks like this issue is related to the behavior you've described in #8351, so I'm gonna close this one
