### ISSUE TITLE
issue: React 18 - validation not working as expected

### ISSUE THREAD

**Issue by cyberwombat** [react-hook-form/react-hook-form#8354]
### Version Number

7.29.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-smart-form-component-forked-3g3zwg

### Steps to reproduce

I tried to follow the smart component example https://react-hook-form.com/advanced-usage#SmartFormComponent  . After converting my form to this my errors stopped showing - I am not sure where the issue is if it's in the validation or error parr. So I created a sandbox using https://codesandbox.io/s/react-hook-form-smart-form-component-forked-iq89z (which is linked to one of the smart form code samples) and got it working. I then upgraded to React 18 from 16 and my error messages stopped working. On my project - not using the smart form approach - everything works fine with 18 so I think it has to do with how the smart form creates the elements - something gets lost or messed up.  Downgrading the sandbox I provided to 16.x will have it working as expected.

### Expected behaviour

Error message should show up

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please provide steps to produce the issue.

**Comment by cyberwombat** [comment]
Ah after playing around with it I see that I expected validation as I typed as my current form does - not sure why it doesn't when I go to the smart form component approach but will investigate.

**Comment by bluebill1049** [comment]
Let me know if you find any issue with it, happy to look into it.
