### ISSUE TITLE
issue: ref in Controller doesn't have DOM element reference 

### ISSUE THREAD

**Issue by Axxxx0n** [react-hook-form/react-hook-form#8357]
### Version Number

7.11.1

### Codesandbox/Expo snack

https://codesandbox.io/s/clever-fermat-fi0ru9?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/clever-fermat-fi0ru9?file=/src/App.js
2. Click on submit
3. View `lastName` errors in console
4. Ref is not DOM element, it has only focus and validity methods

### Expected behaviour

Expected that ref holds DOM reference so we can do custom things on that element when error occurs. This was true in v7.11.0 and changed in v7.11.1. 

Probably this change introduced it:
https://github.com/react-hook-form/react-hook-form/pull/5937/files#diff-3f5bdfa7d822b4562b8e1c72dd1996197fe93478b039779bb78853ab3ae2a3feL119

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we can't guarantee input ref for custom controlled components and if you want to get hold of the ref object, you can store in your own ref by using `useRef`.
