### ISSUE TITLE
issue: older browsers giving errors such as SyntaxError Unexpected token ...

### ISSUE THREAD

**Issue by msafi** [react-hook-form/react-hook-form#8358]
### Version Number

7.31.1

### Codesandbox/Expo snack

None

### Steps to reproduce

Thanks for this sweet library! I use it in my Next.js project here https://github.com/hollowverse/hollowverse.

I use Sentry to monitor client side errors, and for some reason `react-hook-form` is the only library that seems to be causing older browsers to throw errors. Here are a couple of examples of errors that I'm seeing

```
SyntaxError
Unexpected token ...
```

Link: https://sentry.io/share/issue/710811b9ba0243f3b0e620af474f68ea/

And...

```
Expected identifier, string or number
```

Link: https://sentry.io/share/issue/645a89337c4a4c49b3dc3c289eda21aa/

Any suggestions on how I could prevent these errors from happening?

Thanks!

### Expected behaviour

Older browsers don't get errors.

### What browsers are you seeing the problem on?

Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for the issue report. we have stopped poly filling for spread operators or that old browser such as IE 11. you will have to polyfill at your own app level. for more context check out our tsconfig: https://github.com/react-hook-form/react-hook-form/blob/master/tsconfig.json
