### ISSUE TITLE
issue: Arrays field are flagged as dirty even when not changed

### ISSUE THREAD

**Issue by marcospassos** [react-hook-form/react-hook-form#8366]
### Version Number

8.0.0-alpha.4

### Codesandbox/Expo snack

https://codesandbox.io/s/brave-currying-uheqrl?file=/src/App.tsx

### Steps to reproduce

1. Go to the sandbox
2. Click on the first "Add field" button
3. See error the second `isDirty` is now true, even though we only changed the first field

### Expected behaviour

The second field state should not be affected by changes in other fields.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
appending a new field will result in adding a new value to your form hence comparing with `defaultValues` will result in false.

**Comment by marcospassos** [comment]
But they're two different fields, and I'm checking dirtiness at field level.

**Comment by bluebill1049** [comment]
u can upvote this feature request: https://github.com/react-hook-form/react-hook-form/issues/8309
