### ISSUE TITLE
issue: Field arrays are never marked as touched

### ISSUE THREAD

**Issue by marcospassos** [react-hook-form/react-hook-form#8367]
### Version Number

8.0.0-alpha.4

### Codesandbox/Expo snack

https://codesandbox.io/s/serene-rosalind-jbhsu9?file=/src/App.tsx

### Steps to reproduce

1. Go to the sandbox
2. Click on "Add field"
3. See the `isTouched` is false

### Expected behaviour

Changing the array, even though programmatically (after all, there is no other way to detect that), should mark the field as touched. We have several use cases, where arrays have no fields.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> An object containing all the inputs the user has interacted with.

after onBlur even occurred with each input.
