### ISSUE TITLE
improve documentation on getValues()'s initial render return data

### ISSUE THREAD

**Issue by simmo** [react-hook-form/react-hook-form#837]
**Describe the bug**
`getValues` outputs as nested on initial render

**To Reproduce**
1. Load sandbox
2. In the preview, you can see the values output (via JSON.stringify) as nested
3. In App.js, edit the first item in the array eg `{ name: "0" },` to `{ name: "a" },`
4. The preview now displays getValues as flat

**Codesandbox link**
https://codesandbox.io/s/gifted-rhodes-sbldb

**Expected behavior**
The output to have the same shape.

**Screenshots**
Steps 1-2:
![image](https://user-images.githubusercontent.com/265345/72327101-58c60700-36a8-11ea-8a87-f88ac67b7ca7.png)

Steps 3-4:
![image](https://user-images.githubusercontent.com/265345/72327141-6d0a0400-36a8-11ea-816a-87cd92154e96.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Chrome
 - Version: 79

**Smartphone (please complete the following information):**
N/A

**Additional context**
Briefly mentioned in the react-hook-form/react-hook-form#768

**Comment by bluebill1049** [comment]
no worries, i will take a look today

**Comment by bluebill1049** [comment]
> 2\. getValues output starts as nested as you have mentioned, even though `nest` is explicitly set to `false`

FYI: We don't flat `object` for you. you either use nested: true or stay as default.

**Comment by bluebill1049** [comment]
> The reason I'm exploring this as I have code that uses `getValues()[name]` where the name may be deeper than the first level eg `field[1].property`. The result is that sometimes `undefined` is returned as `getValues()` is nested and sometimes it returns correctly when the return is flat.

I think you can use lodash `get()` function to resolve this?

**Comment by bluebill1049** [comment]
> Notice how the value of getValues() jumps around from nested to flat during the interaction.

why not just use `getValues({ nested: true })` so they are always nested? and combined with lodash `get`

**Comment by simmo** [comment]
> > Notice how the value of getValues() jumps around from nested to flat during the interaction.
> 
> why not just use `getValues({ nested: true })` so they are always nested? and combined with lodash `get`

Ok thanks, I’ll try this. So to confirm the only way to get a consistent return shape is to pass `nested` as `true`?

**Comment by bluebill1049** [comment]
yes

**Comment by bluebill1049** [comment]
i am going to close this issue now :) feel free to follow up with more questions.
