### ISSUE TITLE
issue: After reset, single character value (or pasted in value) is not returned from getValues()

### ISSUE THREAD

**Issue by bryce-by** [react-hook-form/react-hook-form#8376]
### Version Number

7.25.3

### Codesandbox/Expo snack

https://codesandbox.io/s/beautiful-grass-vt7ywo

### Steps to reproduce

Go to our [codesandbox](https://codesandbox.io/s/beautiful-grass-vt7ywo) and fill out the form 1 time (you can just enter "1" for each field). The 2nd time (after calling reset()) is when we are observing unexpected behavior.

When the user fills out the form the 1st time, you can see from the console logs, the getValues() function (which is called either onClick of that section's "Next" button or Enter Keydown). returns the values of the completed inputs as expected.

However, upon filling out the form the 2nd time, the getValues() function does not return a value _IF_ a SINGLE character is entered, _OR_ a value is pasted into the input. This is causing our validation that runs on Enter Keydown or "Next" button click to falsely fail.

### Expected behaviour

I would expect the form to behave the same before and after it has been reset.

### What browsers are you seeing the problem on?

I have only tested this on Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
can you please remove all those additional codes and keep the codesandbox isolated from the problem? also, getValues doesn't subscribe to changes if this is what you intended.  

here is a template you could follow: https://codesandbox.io/s/damp-cloud-80q78f

**Comment by bluebill1049** [comment]
thanks for the update, can you share a video clip on the issue? i still don't get the specific use case.

**Comment by bluebill1049** [comment]
another thing, can you try to call reset at useEffect with isSubmittedSuccesuflly dep?

**Comment by bryce-by** [comment]
https://user-images.githubusercontent.com/87672423/169167933-0b04b16c-5fa1-4c61-b06e-3c2bf31d59db.mp4

I am hitting "Enter" between fields, as described above.

Also, I updated the code to try useEffect with isSubmittedSuccessfully as a dep. Unfortunately, that did not resolve the issue as is evident in the video.  

You can see in the console.log at the bottom of the screen, the value of the first input (BinFrom) is returning an empty string, instead of "1" (the value that is actually in the input).

**Comment by bluebill1049** [comment]
chrome, no tab with enter.

**Comment by bryce-by** [comment]
I tried using setValue() instead of reset() in the useEffect() with the isSubmitSuccessful dep, and now the value of the first input is cleared when I hit enter after the first time filling out the form :

https://codesandbox.io/s/condescending-darkness-o290ec

https://user-images.githubusercontent.com/87672423/169295608-2dc40812-10fd-4895-a4bc-0c6ba4436866.mp4

**Comment by bluebill1049** [comment]
I wouldn't use reset with setValue, reset will remove all input references and registration will need to happen again with re-render. for your use case, you should stick with use setValue only as you only want to clear field value, it's a very specific use case that you have.

**Comment by bryce-by** [comment]
@bluebill1049 We really appreciate your help on this, using setValue did the trick for us.

Our actual form has quite a bit of custom validation that relies on the value of other inputs which is not reflected in the codesandbox & is why we are using setFocus(). I agree, the codesandbox could be simplified in that regard.

Thanks again! Great library!

**Comment by Upinwv** [comment]
Canary Mail
You've received a secure email
***@***.*** has sent you a secure email via Canary Mail.

Read Secure Email (https://secure.canarymail.io/read?obj_id=60334ac6-eec6-4456-8cdb-e96e507ad655&obj_key=K2lMUE5GWFNEQngrZTVycWp2Z25qUT09&thr_id=60334ac6-eec6-4456-8cdb-e96e507ad655)

If you expect to correspond often with ***@***.***, we recommend you download Canary Mail for free.

Download Canary (https://canarymail.io)

Privacy (https://canarymail.io/privacy.html) | Terms (https://canarymail.io/terms.html) | Docs (https://help.canarymail.io/) | Support (https://canarymail.zendesk.com/hc/en-us/requests/new)

Copyright © 2021 Canary Mail, All rights reserved.
