### ISSUE TITLE
issue: Looks like (despite what the doc says) dot-and-bracket notation is actually supported

### ISSUE THREAD

**Issue by maxgabut** [react-hook-form/react-hook-form#8378]
### Version Number

7.29.0

### Codesandbox/Expo snack

https://codesandbox.io/s/dot-and-bracket-notation-actually-works-1gnuix

### Steps to reproduce

1. Go to https://codesandbox.io/s/dot-and-bracket-notation-actually-works-1gnuix
2. Fill both fields
3. Click on submit
4. Check the console
5. Notice that the result contains objects inside an array, the dot-and-bracket notation was actually correctly interpreted

### Expected behaviour

According to the bit of documentation below (that come from [this page](https://react-hook-form.com/api/useform/register))

```
we are using dot syntax only for typescript usage consistency, so bracket [] will not work for array form value.

register('test.0.firstName'); // ✅
register('test[0]firstName'); // ❌
```

this should not work.

If I'm not mistaken, this part of the doc can be changed, as dot-and-bracket notation just works.

(The second line of the doc sample is not correct however, even using dot-and-bracket, it should be `'test[0].firstName'`, with a dot after the closing bracket.)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for the detail issue, but it's not supported, it will cause issues with the field array and typescript support.
