### ISSUE TITLE
issue: SubmitHandler doesn't infer return types from a resolver

### ISSUE THREAD

**Issue by AustinShelby** [react-hook-form/react-hook-form#8382]
### Version Number

7.31.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-type-error-xvg4pm?file=/src/App.tsx

### Steps to reproduce

When transforming the data in a resolver it messes up some types.

`z.infer` actually infers the output type of the schema which is partly correct, except when setting the default values it expects the wrong type.

```ts
import { SubmitHandler, useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";

const FormSchema = z.object({
  name: z.string().transform((val) => 300)
});

type FormSchemaType = z.infer<typeof FormSchema>;

export default function App() {
  const { register, handleSubmit } = useForm<FormSchemaType>({
    resolver: zodResolver(FormSchema),
    defaultValues: {
      name: "1" // Type 'string' is not assignable to type 'number | undefined'.
    }
  });

  const onSubmit: SubmitHandler<FormSchemaType> = async (
    data
  ): Promise<void> => {
    console.log(data);
  };

  return (
    <div className="App">
      <form onSubmit={handleSubmit(onSubmit)}>
        <label htmlFor="name">
          <span>Name</span>
          <input id="name" type="text" {...register("name")} />
        </label>
        <button type="submit">Submit</button>
      </form>
    </div>
  );
}
```

One possible solution I tried is to changing
```ts
type FormSchemaType = z.infer<typeof FormSchema>;
```
to
```ts
type FormSchemaType = z.input<typeof FormSchema>;
```
but this messes the types on onSubmit. It will say that type is `{name: number}` even though it's actually `{name: string}`

These issues will become even more apparent when using a custom resolver that does complex data transformations. Like in this example: [https://codesandbox.io/s/another-react-hook-form-type-error-2jnh0j?file=/src/App.tsx](https://codesandbox.io/s/another-react-hook-form-type-error-2jnh0j?file=/src/App.tsx)

```ts
import { SubmitHandler, useForm, Resolver } from "react-hook-form";

const resolver: Resolver<FormSchemaType> = () => {
  return {
    values: {
      omega: 300
    },
    errors: {}
  };
};

type FormSchemaType = { name: string };

export default function App() {
  const { register, handleSubmit } = useForm<FormSchemaType>({
    resolver: resolver,
    defaultValues: {
      name: "Hey"
    }
  });

  const onSubmit: SubmitHandler<FormSchemaType> = (data): void => {
    console.log(data); // TypeScript says: {name: string} but it's actually {omega: 300}
  };

  return (
    <div className="App">
      <form onSubmit={handleSubmit(onSubmit)}>
        <label htmlFor="name">
          <span>Name</span>
          <input id="name" type="text" {...register("name")} />
        </label>
        <button type="submit">Submit</button>
      </form>
    </div>
  );
}
```

### Expected behaviour

SubmitHandler should properly infer the return type from a resolver.
defaultValues should properly infer the input type of zod schema used in a zod resolver.

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
hey @AustinShelby

This issue is getting improved in v8: https://codesandbox.io/s/another-react-hook-form-type-error-forked-vsz53h?file=/src/App.tsx

**Comment by bluebill1049** [comment]
@AustinShelby are you happy to land on the v8 alpha version first, considering we will move into `beta` phase soon?

**Comment by bluebill1049** [comment]
Going to close this issue as we are addressing this in V8 by remove `unpacked` and `NestedValue` type
