### ISSUE TITLE
issue: types not found when using TypeScript 4.7 in ESM mode

### ISSUE THREAD

**Issue by rossng** [react-hook-form/react-hook-form#8388]
### Version Number

7.31.2

### Codesandbox/Expo snack

https://stackblitz.com/edit/vitejs-vite-tz2hky?file=main.ts

### Steps to reproduce

1. In a TypeScript project using `react-hook-form`, upgrade to TypeScript `4.7.1-rc` and set the following options in `tsconfig.json`:
    ```
     "compilerOptions": {
        "moduleResolution": "NodeNext",
        "module": "NodeNext"
    }
    ```
    This will cause TypeScript to generate pure ESM output (a new feature in 4.7).
2. Observe that imports from `react-hook-form` now cause errors, since TypeScript can no longer find the types corresponding to `index.esm.js`.

You can see this behaviour by running `npm run build` in the linked example project:

### Expected behaviour

`react-hook-form` should specify where TypeScript can find types for the ESM entrypoint, which would prevent this error.

For example, since TypeScript now has support for export maps, I was able to resolve this by patching the following into `react-hook-form`'s `package.json`:

```
"exports": {
    "./package.json": "./package.json",
    ".": {
      "import": {
        "default": "./dist/index.esm.mjs",
        "types": "./dist/index.d.ts"
      },
      "require": {
        "default": "./dist/index.cjs.js",
        "types": "./dist.index.d.ts"
      }
    }
  },
```

### Relevant log output

```shell
main.ts:1:25 - error TS7016: Could not find a declaration file for module 'react-hook-form'. '/home/projects/vitejs-vite-tz2hky/node_modules/react-hook-form/dist/index.cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-hook-form` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-hook-form';`

1 import { useForm } from 'react-hook-form';
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
would you like to send us a PR to address this?

**Comment by rossng** [comment]
Done!
