### ISSUE TITLE
issue: mode changes after submit

### ISSUE THREAD

**Issue by Razinar91** [react-hook-form/react-hook-form#8391]
### Version Number

7.31.1

### Codesandbox/Expo snack

https://codesandbox.io/s/focused-rgb-9hrfif?file=/src/App.tsx

### Steps to reproduce

1. Go to the sandbox
2. write 6 chars in the input, the button is disabled until input lose focus (validation mode is set onBlur)
3. Unfocus
4. submit the form
5. after submit, focus the form again 
6. delete until 3 or 4 chars are there. 
7. You'll see validation happening onChange instead of onBlur

### Expected behaviour

I expected that validation still happens onBlur also after submitting the form

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
This the expected behavior described in [the RHF docs](https://react-hook-form.com/api/useform).

Make sure to configure` reValidateMode: onChange | onBlur | onSubmit = 'onChange'` to whatever suites your needs.
