### ISSUE TITLE
issue: Focus management for controlled inputs

### ISSUE THREAD

**Issue by MomenSherif** [react-hook-form/react-hook-form#8398]
### Version Number

7.31.2

### Codesandbox/Expo snack

https://codesandbox.io/s/cocky-knuth-eh7mgx?file=/src/App.js

### Steps to reproduce

1. Create controlled input with `useController` or `Controller ` and use it as first input in the form.
2. Add normal register for fields that exposes ref.
3. Add validation for both inputs.
4. Submit the form.
5. Focus will go for first normal register field.
6. After filling it with correct value.
7. Submit the form, now focus on controlled input.

### Expected behaviour

Controlled inputs need to be registered in order that has been used to not conflict with focus management.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
@MomenSherif This is expected, we can't guarantee the focus order. It's purely relied on `register` order, as native input with `register` API will always invoke first, that's something we can improve but I would suggest starting with a feature request, and then we can figure out an API proposal for that.

**Comment by bluebill1049** [comment]
Just for your reference, I have been thinking about this problem for a while as well...  It's quite tricky as the layout can shifts, so the developer may have to provide all the input names to align the focus order, which is pretty bad for large forms. If anyone has a great solution or idea, please leave a comment. 👍
