### ISSUE TITLE
issue: `elm.setCustomValidity is not a function` error for MUI Select field when validation is triggered (via `handleSubmit` or `trigger`)

### ISSUE THREAD

**Issue by bogdanailincaipnt** [react-hook-form/react-hook-form#8400]
### Version Number

7.31.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-ts-triggervalidation-forked-4w7yqd?file=/src/index.tsx

### Steps to reproduce

1. Go to [sandbox link](https://codesandbox.io/s/react-hook-form-v7-ts-triggervalidation-forked-4w7yqd?file=/src/index.tsx)
2. Click on 'SUBMIT'
3. See error

This happens when any field has a validation error, however the TypeError is related to the field which uses MUI Select.

### Expected behaviour

There should be no error.

The issue is somehow related to the `shouldUseNativeValidation: true` option.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Uncaught (in promise) TypeError: elm.setCustomValidity is not a function
    at Object.setCustomValidity (useController.ts:135:21)
    at setCustomValidity (validateField.ts:54:16)
    at validateField (validateField.ts:252:3)
    at executeBuildInValidation (createFormControl.ts:427:36)
    at async executeBuildInValidation (createFormControl.ts:454:12)
    at async executeBuildInValidation (createFormControl.ts:454:12)
    at async trigger (createFormControl.ts:785:36)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
not an issue with hook form, this option is only available for native inputs not MUI custom component and mui need to expose actual native select input.

**Comment by bogdanailincaipnt** [comment]
@bluebill1049 a native input is actually used inside the MUI Select component. Note that I'm passing the `inputRef` prop to it. It also supports an `inputProps` prop. I just tested, and if I run `setCustomValidity('error message')` and `reportValidity()` on the input element, the error shows fine.

**Comment by bogdanailincaipnt** [comment]
So it works similarly to their https://mui.com/material-ui/api/input/ component, which also supports the `inputRef` and `inputProps` props. This section is also useful: https://mui.com/material-ui/api/select/#inheritance ("the props of the [OutlinedInput](https://mui.com/material-ui/api/outlined-input/) component are also available on Select)

**Comment by bogdanailincaipnt** [comment]
And the `Input` component works fine with `react-hook-form`.

**Comment by bogdanailincaipnt** [comment]
Ok, after some more investigating, I think the solution might be to modify this function on MUI's end: https://github.com/mui/material-ui/blob/master/packages/mui-material/src/Select/SelectInput.js#L163.
They are returning a fake & incomplete input dom node, which is lacking the `setCustomValidity` function.

**Comment by Moshyfawn** [comment]
Thank you for the investigation and filling out an issue with MUI!
