### ISSUE TITLE
issue: UseFieldArray prepend replacing undefined value with value from forms default

### ISSUE THREAD

**Issue by Daneng66** [react-hook-form/react-hook-form#8410]
### Version Number

7.31.2 (Appears to be introduced in v7.10.0)

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-issue-62v792

### Steps to reproduce

1. Click on Add

The new value that is prepended should be `undefined` but as you can see it takes the value that was at the path of the forms default value.

### Expected behaviour

I would expect the new field at index 0 to be `undefined`.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we do not support `undefined` for the field value. please refer to the doc on each action required to provide field value.

**Comment by Daneng66** [comment]
@bluebill1049 It appears to be working in v7.9.0

**Comment by Moshyfawn** [comment]
Yes, it was changed in [the v7.22.5 release](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.22.5)

**Comment by Daneng66** [comment]
Can a feature request be created to bring back support?

**Comment by Moshyfawn** [comment]
Mmm.. I don't think so. RHF internals heavily rely on this behavior.

That said, let's see what @bluebill1049 has to say about the this

**Comment by bluebill1049** [comment]
unless we drop all the inline `defaultValue`.

- useWatch
- useController
- Controller

we can't support `undefined`, this is from the very beginning of the hook form and if it's working in the specific version then it's a bug that got patched.
