### ISSUE TITLE
need to add defaultErrors and defaultTouched for testing purposes

### ISSUE THREAD

**Issue by KarafiziArtur** [react-hook-form/react-hook-form#8413]
To make testing work correctly, it needs to add defaultErrors and defaultTouched to the useForm props:

```
useForm({
  defaultValue: { "input": 50 },
  defaultErrors: { "input": "any error" },
  defaultTouched: { "input": true },
});
```

**Comment by TrejGun** [comment]
good feature! formik has it but formik is dead now and lack of such features slows down migration

**Comment by bluebill1049** [comment]
> To make testing work correctly, it needs to add defaultErrors and defaultTouched to the useForm props:

This feature request completely lacks context... follow the template.
