### ISSUE TITLE
issue: fields outside arrays, renders when array changes

### ISSUE THREAD

**Issue by uyig** [react-hook-form/react-hook-form#8415]
### Version Number

7.31.3

### Codesandbox/Expo snack

https://codesandbox.io/s/fields-outside-arrays-renders-when-array-changes-d1m0xm?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/fields-outside-arrays-renders-when-array-changes-d1m0xm?file=/src/App.js
2. Click on 'Add element'

### Expected behaviour

"firstName" has one rendering counter. Instead, it increases with each click "Add element".

Is it intended that way or is it a bug ? 

I did a little code research. If the "_updateFieldArray"(createFormControl.ts) function passes "name" to "_subjects.state.next", then checking "shouldSubscribeByName" in "useFormState" returns "false". "firstName" should not be render.

I can do a PR if it's a bug.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
hey @uyig thanks for the issue, this re-render can't be avoided as useFieldArray will need to flush a render to update all the field arrays.

**Comment by uyig** [comment]
Thanks for the quick response. I'll try to do a PR

**Comment by bluebill1049** [comment]
@uyig this may be related to `StrictMode` mode.  https://codesandbox.io/s/fields-outside-arrays-renders-when-array-changes-forked-292frb?file=/src/index.js

**Comment by uyig** [comment]
Yes, this will remove 1 rendering. But note that the "firstName" field is still rerenders, when you click on the "Add Item" button. Although the field is outside the array.

**Comment by bluebill1049** [comment]
<img width="686" alt="Screen Shot 2022-05-29 at 10 45 01 pm" src="https://user-images.githubusercontent.com/10513364/170869187-9226cc4a-e2f9-4ffd-9cc1-f4d91c5221bd.png">

it's actually inside get re-rendered by `useFieldArray` hook.

**Comment by uyig** [comment]
Yes, I made a bad example. I'll double-check the behavior again

**Comment by uyig** [comment]
Apparently I got something mixed up. Thanks for the help. Close the issue

**Comment by bluebill1049** [comment]
no worries @uyig I do appreciate you trying to help and provide a PR as the most developers are here just seek for a solution or fix; much appreciated and have a good one.
