### ISSUE TITLE
feature request: expose internal validation function

### ISSUE THREAD

**Issue by damien-duignan** [react-hook-form/react-hook-form#8422]
**Is your feature request related to a problem? Please describe.**
I'm building a custom resolver which validates the input against JSON schema using [AJV](https://ajv.js.org/). This results in the built-in validators (max, min etc) not triggering their errors. 

Since we are using the built-in validators quite extensively, this would mean writing the validators in the resolver also. This could lead to differences in how we have implemented the built-in validation in the resolver, and how RHF validates.

**Describe the solution you'd like**
I can see two possible options:
1. Export the [validateField.ts](https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/validateField.ts) function from RHF, so it can be imported and used in the custom resolver. Potential usage [in this codesandbox](https://codesandbox.io/s/resolver-in-built-validation-2y2vf6?file=/src/App.tsx:1413-1449).
2. Provide an option in the `useForm()` hook to combine built-in validators errors with the errors returned from resolver.

**Describe alternatives you've considered**
1. I have considered writing the validation logic myself, but this is duplicating existing code that already exists in RHF, and can lead to differences in implementation. See [here in the codesandbox](https://codesandbox.io/s/resolver-in-built-validation-2y2vf6?file=/src/App.tsx:1854-1889).
2. Returning multiple errors from `validate` function. See [relevant discussion here](https://github.com/react-hook-form/react-hook-form/discussions/8362).

**Additional context**
N/A

# Summary

Expose internal validation logic, so the end-user can reuse that logic.

**Comment by bluebill1049** [comment]
We want to avoid this by mixing build-in validation and resolver validation. It can be a convenient thing to add and support both, but once your codebase gets large it's definitely a foot-gun when you have build-in validation somewhere else and conflicting with the resolver validations.

> I'm building a custom resolver which validates the input against JSON schema using [AJV](https://ajv.js.org/). This results in the built-in validators (max, min etc) not triggering their errors.

I would love to see your resolver with AJV as we are currently missing that from the official resolvers.

**Comment by bluebill1049** [comment]
> Do you mean purely from a maintenance point of view? I can see how this could become an issue, but integrating AJV validation without having the built-in validators will make our form unusable. I think it would be good to have the option to use the built-in validation from RHF, even if it's just exporting the [validateField.ts](https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/validateField.ts) function.

both maintainer and user perstive.

> Some inputs in our form will validate using AJV, and some will simply use the built-in ones. Some forms will not use the resolver at all, which would lead to differences in built-in validations if we rewrite the built-in validation ourselves for the resolver.

- so if one is required (resolver) and the other (build-in) which one takes the rule?  
- performance is an aspect now it needs to run both validations too.
- increase lib internal complexity

> The current logic is dependant on some other parts of our codebase, but I'll try to clean it up & make it reusable. I'll post a codesandbox or PR when I'm done 🙂

that would be amazing~!

**Comment by damien-duignan** [comment]
> so if one is required (resolver) and the other (build-in) which one takes the rule?

I've created [this codesandbox](https://codesandbox.io/s/resolvers-and-built-in-validators-f41iv9?file=/src/App.tsx) to show how I plan to implement this. This is a simplified version of what's implemented in our codebase(the resolver is the same, but the `Input` & `Form` components are simplified). 

You can see three versions of how we intend to use forms in our codebase. There's an explanation in the CSB for each version.

My idea was the the resolver would handle the AJV validation. And if built-in validations exist for the input, they would also be applied in this resolver. Both in-built-errors and AJV validation will be returned from the custom resolver. 

[In this line](https://codesandbox.io/s/resolvers-and-built-in-validators-f41iv9?file=/src/utils/trimmed-resolver.ts:1206-1274) you can see the AJV validation happening. 

[Here you can see](https://codesandbox.io/s/resolvers-and-built-in-validators-f41iv9?file=/src/utils/trimmed-resolver.ts:1300-1514) that I'm validating a built-in validator also. All other validator cases would also have to be re-written for built-in validators. This was my point about exporting the `validateField` function, so that we're not duplicating code. We could simply import the function and validate the field in the resolver.

> performance is an aspect now it needs to run both validations too.

I'm not too well informed about how this will affect performance(something I need to look into). If what I've described is very bad for performance, can you suggest an alternative on how to integrate an external validation library while maintaining the built-in validations? I've tried a few approaches and this seems to be the only one that could work well.

**Comment by bluebill1049** [comment]
> My idea was the the resolver would handle the AJV validation. And if built-in validations exist for the input, they would also be applied in this resolver. Both in-built-errors and AJV validation will be returned from the custom resolver.

yea I like this idea, but this sort of implementation creates a discussion path for users and leads to the user asking for different opinions on things behavior, it expands configuration and potentially leads to more confusion. I almost like to reduce the amount of confirmation which we already have.

> I'm not too well informed about how this will affect performance(something I need to look into). If what I've described is very bad for performance, can you suggest an alternative on how to integrate an external validation library while maintaining the built-in validations? I've tried a few approaches and this seems to be the only one that could work well.

What you described is not bad at all, but when you have two (major) sources of validations it's going to add a lot of overhead and quite a lot more code on each part of the validation proceed internally as well.

**Comment by damien-duignan** [comment]
> yea I like this idea, but this sort of implementation creates a discussion path for users and leads to the user asking for different opinions on things behavior, it expands configuration and potentially leads to more confusion. I almost like to reduce the amount of confirmation which we already have.

Fair point, I understand that we don't want to introduce more complexity. 

But at this point I'm a bit stuck. I only see the option of re-writing the built-in validations in my own resolver. What do you think about exporting the `validateField` function? It seems like a decent option as it doesn't seem to introduce more complexity to RHF(correct me if I'm wrong 😄).

Would be happy to investigate other solutions for the combination of `resolver + built-in` validations. But after a long time of working on this I can't seem to find any other suitable solution. Do you know of a better way to solve this?

**Comment by bluebill1049** [comment]
> But at this point I'm a bit stuck. I only see the option of re-writing the built-in validations in my own resolver. What do you think about exporting the validateField function? It seems like a decent option as it doesn't seem to introduce more complexity to RHF(correct me if I'm wrong 😄).

would you mind copying that file into your app to start with before we have a proper potential solution?

> Would be happy to investigate other solutions for the combination of resolver + built-in validations. But after a long time of working on this I can't seem to find any other suitable solution. Do you know of a better way to solve this?

I think that can be the topic of this feature request and we can leave this in the feature board and see how many community users would need such feature, but I do share the same concern which i stated above.

**Comment by damien-duignan** [comment]
> would you mind copying that file into your app to start with before we have a proper potential solution?

Yeah I'll try this out as a first step.

> I think that can be the topic of this feature request and we can leave this in the feature board and see how many community users would need such feature, but I do share the same concern which i stated above.

Sounds good. Thanks for your feedback!

**Comment by bluebill1049** [comment]
no worries, would you like to modify your feature request? We can then move into the project board.

**Comment by getTobiasNielsen** [comment]
> air point, I understand that we don't want to introduce more complexity.

@bluebill1049 I think this isn't about complexity anymore.

Try to imagine someone struggling with ajv or yup and trying to make it work "just right".

In one scenario you either drop all your schemas built on yup (and time saved using it) , and add it to the built in validation in rhf.

In the other, you continue to loose time(potentially a lot) on some silly yup/ajv issue.

Being able to add custom validations at the tail end of a resolver, would mean you could get the benefit from a fast yup schema, and fix the small issues that yup just couldn't do easily for you. (this ofc, all depends on your "yup" skills, but, I could see this being a time saver for a lot of people).

If they are added at the end of the resolver, then that could be the order they are applied.

> Would be happy to investigate other solutions for the combination of resolver + built-in validations. But after a long time of working on this I can't seem to find any other suitable solution. Do you know of a better way to solve this?

This pattern would been the validation logic, logical and collected in one spot. And the `exporting the validateField` would allow for the pattern it looks like @damien-duignan need more, because they try to pass props to control validation in their example.

This could be a good addition, not just because people make messy code, but because it could be a benefit on it's own.

(Also not saying your code is messy @damien-duignan <3)

**Comment by getTobiasNielsen** [comment]
@damien-duignan

On another note, I think your issue is fixed simply by adding a min length of 1 to a string type, to make it required.

Not sure if the example was too simple, and this doesn't just pertain to the required property.

**Comment by damien-duignan** [comment]
@getTobiasNielsen 

> On another note, I think your issue is fixed simply by adding a min length of 1 to a string type, to make it required.

The result of the AJV validation isn't too important in our case, as the contents of the JSON schema is not handled by our frontend.

Just for a bit of context(might have made this problem easier to understand from the beginning): 

We're building a form based on JSON schema, which is coming from our API. We've extended the JSON schema spec with the ability to say that the contents of a textarea should be validated with JSON schema(the schema for that textarea will be a subset of the larger schema/form). 

Here's an example:
![JSONschema](https://user-images.githubusercontent.com/14984081/171740220-f9215f9a-eebc-4187-bdfc-6143addbdc7d.png)

The schema for this form(`values.json` is what's used as the schema for the textarea):
```
{
  properties: {
    values: {
      type: 'object',
      properties: {
        json: {
          description: 'An object with one required parameter.',
          properties: {
            level1: {
              type: 'object',
              properties: {
                level2: {
                  properties: {
                    nestedinstance: {
                      pattern: '^[0-9a-z][0-9a-z-]+[0-9a-z]$',
                      title: 'Nested Parameter',
                      type: 'string',
                    },
                  },
                  required: ['nestedinstance'],
                },
              },
            },
            required_param: {
              pattern: '^[0-9a-z][0-9a-z-]+[0-9a-z]$',
              title: 'Required Parameter',
              type: 'string',
            },
          },
          required: ['required_param', 'level1'],
          title: 'JSON Object',
          type: 'object',
          uiHints: {
            inputType: 'textarea',
          },
        },
        required: {
          type: 'string',
        },
        minimum: {
          type: 'number',
          minimum: 3,
        },
      },
      required: ['required', 'json'],
    },
  },
  type: 'object',
}
```

@bluebill1049 FYI I just saw the [PR for the AJV resolver](https://github.com/react-hook-form/resolvers/pull/408). While this is a great addition, what I'm trying to solve is a bit different as I'm validating raw input from the textarea. All the AJV errors should be displayed for one input in my case. Hopefully my explanation earlier in this comment will help clarify what I'm trying to achieve.

**Comment by bluebill1049** [comment]
@damien-duignan I will update your feature request and pin to the board.

**Comment by damien-duignan** [comment]
> @damien-duignan I will update your feature request and pin to the board.

Thanks for updating.
