### ISSUE TITLE
issue: useFieldArray update API

### ISSUE THREAD

**Issue by omerman** [react-hook-form/react-hook-form#8424]
Hello, I believe I found an issue with the Controller component. It seems to have wrong state when we use useFieldArray to update fields.

Please have a look and tell me your thoughts (Attached codesandbox)

### Version Number

latest

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-6cb38h?file=/src/index.js

### Steps to reproduce

* Open sandbox and see we have 2 rows.
* Press Update and watch only the div update with the right value, but for some reason controller is stuck with invalidated state.

### Expected behaviour

Controller should display the updated value.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
simple mistake: `<li key={item.id}>` thanks for the issue report.

**Comment by omerman** [comment]
Please reopen. The firstname is unique. I can add to the example an id field and it will not change the result.

**Comment by bluebill1049** [comment]
hey @omerman please refer to the doc: 

> useFieldArray automatically generates a unique identifier named id which is used for key prop. For more information why this is required: https://reactjs.org/docs/lists-and-keys.html#keys

https://react-hook-form.com/api/usefieldarray#rules

<img width="966" alt="Screen Shot 2022-05-31 at 3 58 12 pm" src="https://user-images.githubusercontent.com/10513364/171102903-7fa7fbda-fdb3-4b58-86d0-49303fcc2b4c.png">

**Comment by omerman** [comment]
@bluebill1049 Hey, I know that the lib generates an id for each item. But it seems to change the id's once any update to the field array is happening. meaning the DOM under each child will be destroyed and re-created. It is an anti pattern and will result in losing state.

I would expect that I will be able to use a unique key no matter what it is. OR that the gernated id that the react-hook-form generates will not re-generate keys for all the items if only one or some items change.

What do you think?

**Comment by omerman** [comment]
@bluebill1049  Just to be clear since I'm not sure you've seen my Edit to the last comment > 

This is a the same sandbox, it uses the generated "id" field. as you can see the field that changes resulting a lost state for the changed item that is rendered since the key for that item changes.
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-6cb38h?file=/src/index.js

I think it could cause state issues when the generated id regenerates, even if only changed items will re-grenerate id, Please let me know what you think

**Comment by bluebill1049** [comment]
This is expected behavior when updating a specific row of field inputs. I would like to see an example or test case which reproduces this would be an issue. The original issue which posted was stated the field input is not getting updated, which it's working as expected above.

**Comment by bluebill1049** [comment]
> Wait a few seconds after opening example, press the update button, and the entire state of the DOM matching the modified child will be lost( In the example, the counter will start over since the component is destroyed and recreated due to key changed).

That's expected, what issue would that cause? if you are updating the entire section of the field array?

**Comment by omerman** [comment]
@bluebill1049 @icopp Yes, input losing focus is classic issue when DOM is recreated. Bill, how is this expected? Changing react keys means the DOM tree under the changed key element is destroyed and recreated. We must take into consideration that react hook form ia not the only state I could have while I work with useFieldArray. and when DOM is destroyed, the entire state is lost as well, including react's native state such as input focus, page scroll position, or my xustom state, like a counter that increments (like in my example).
This is a real issue 😅

**Comment by bluebill1049** [comment]
As much as I would like to address this issue, I did my own investigation by not changing the key, and this caused other issues and break the test which proves this will cause issues for existing users. So the conclusion is the behavior will stay as it is and has been addressed in the documentation. In addition, I also don't expect users to use `update` on every keystroke, considering all the u`seFieldArray` methods are single-action usage.

## What are the alternatives? 

- use `setValue` API instead
- fork the repo and see if anyone can address this issue and send us a PR

https://github.com/react-hook-form/documentation/commit/410eb6274e2d85be7acb2a85d7ff192455a88f32

**Comment by glenkitchen** [comment]
Until this issue is resolved, I don't think useFieldArray can be used effectively with queried data.
I eventually gave up.

I just use a useState array & standard array mutation operations that mimic the useFieldArray methods. 
Cumbersome, but no issues.

By the way, thanks so much for this library. Much appreciated.

**Comment by glenkitchen** [comment]
@bluebill1049 Yes, but I was still unsuccessful. 

In the absence of an example, 
I just found it easier to an manage an array manually when querying data AND then updating data.
(No issue with create mode). 
 
No stress, just my personal experience, which may be off the mark.

**Comment by bluebill1049** [comment]
thanks for the update @glenkitchen I am keen to see an example (in a codesandbox) Happy to take a look at this issue if you got time to reproduce it.

**Comment by omerman** [comment]
@bluebill1049 I'll try to create a sandbox this weekend
