### ISSUE TITLE
useController is rerendering multiple times while Controller is not. 

### ISSUE THREAD

**Issue by danielweil** [react-hook-form/react-hook-form#8425]
### Version Number

7.31.3

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-sample-gnf6no

### Steps to reproduce

1. Type on first input.
2. Watch as rerender count is not altered.
3. Type on second input.
4. Watch as rerender count goes up as each character is typed.

### Expected behaviour

I expect that useController hook should be optimized to avoid rerenders exactly as does the Controller component. Hooks are more elegant to use, but if it results in more renders it isn't worth it.

I saw people from react hook form in the issues say that both should have same behaviour, as Controller uses useController hook inside it, but that wasn't what happened.

Thanks for the amazing package.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is expected behavior.

- useController will render at the hook level
- controller will render with the `render` callback

**Comment by danielweil** [comment]
Can you explain this description a bit more?

**Comment by bluebill1049** [comment]
sure, @danielweil 

```tsx
const Test = <Controller rendeer={() => {
  // re-render occured here
}} />

function MyField() {
  // re-render occurred here
  useController()
}

function App() {
  return <div>
    <Test />
    <MyField />
  </div>
} 
```

in fact, `Controller` is built by `useController`

```
function Controller() {
  return useController(...)
}
```

when to use, those depend on your usage, personal preference, and project. 

`Controller`: quick and easy use it inline

```tsx
<Controller  render={() => <OtherFieldComponent />} />
```

`useController`: build reusable field component.

```
function BuildMyOwn() {
   const props = useController()
   return <OtherFieldComponent onChange={props.field.onChange} value={props.field.value} />
}

<BuildMyOwn />
```

**Comment by danielweil** [comment]
Thank you. I think I understood it now. I though there was a way to avoid all rerenders, even if using controller, but what does change is the location of the render.
