### ISSUE TITLE
issue: useFieldArray filter out empty strings

### ISSUE THREAD

**Issue by Gallevy** [react-hook-form/react-hook-form#8426]
### Version Number

7.31.3

### Codesandbox/Expo snack

https://codesandbox.io/s/quiet-bush-qc08o6?file=/src/App.js

### Steps to reproduce

1. See the default values used.
2. Run the example and see no input rendered.
3. Edit the defaultValues to be ```phones: [" "]```
4. Run the example again and see a text input is being rendered now

This is useful for the use case when you want to automatically include an empty input field when a user begin to fill the form

### Expected behaviour

For `useFieldArray` to not temper with the `defaultValues`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> Does not support flat field array.

we don't support flat array, please refer to the doc under rules

https://react-hook-form.com/api/usefieldarray#rules

**Comment by Gallevy** [comment]
@bluebill1049 thankks bill for the quick reply. Any reason not to? other than my issue here it seems to work just fine.

**Comment by bluebill1049** [comment]
It depends on your usage, it will encounter issues when shuffling the field array as we need a unique id for each row of data.
