### ISSUE TITLE
setFocus is crashing after reset with React 18

### ISSUE THREAD

**Issue by moroshko** [react-hook-form/react-hook-form#8427]
### Version Number

7.31.3

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-with-react-18-forked-sb5yk1

### Steps to reproduce

1. Click the "Focus input" button in the [CodeSandbox](https://codesandbox.io/s/react-hook-form-with-react-18-forked-sb5yk1).
2. Observe error in the console:
> Could not consume error: Error: Something is *really* wrong.

### Expected behaviour

`setFocus` should focus the field.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I will add a note on this, reset will remove all input references, and calling reset right after will lead to an error. If you want to setFocus consider moving the setFocus into `useEffect`

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/documentation/commits/master

**Comment by moroshko** [comment]
Thanks Bill!
