### ISSUE TITLE
Throw exception when trying to use "rules" when "resolver" present

### ISSUE THREAD

**Issue by simonmallet** [react-hook-form/react-hook-form#8442]
**Is your feature request related to a problem? Please describe.**
I've spent a few hours trying to understand why my "rules" was not working in my controller (it was never reaching the validation function). Then I realized that the form was using a resolver for validation schema, and that maybe it was affecting my rules.

To discover in the docs that you cannot use "rules" when a resolver is present.

**Describe the solution you'd like**
I'd like react-hook-form to throw an exception when "rules" is set but a resolver is present instead of doing nothing silently.
With a simple message like : "Rules prop cannot be set since there is a resolver in use"

**Describe alternatives you've considered**
An alternative would be to allow built-in validators when resolvers are present, however I see that there are a lot of threads related to that subject already. I'm just asking that we get an error thrown instead of doing nothing silently.

**Comment by Moshyfawn** [comment]
Pinning to the features board for trial
