### ISSUE TITLE
option to attach onChange validatation listeners after using the "trigger" function

### ISSUE THREAD

**Issue by MTG2000** [react-hook-form/react-hook-form#8444]
**Is your feature request related to a problem? Please describe.**
So I have a normal form with a submit button, but I also have a "preview" button, that when clicked on, I use the 'trigger' function, then if result valid I show a modal.
but it seems that using trigger validate the inputs but doesn't attach onChange listeners, so when the user go back & fix the error in the field, the error message remains until he press 'preview' again.

**Describe the solution you'd like**
maybe we can add a config option to trigger function that enables attaching onChange listeners the same as if the submit button was clicked.

so what do you think, maybe there is a reason why this option isn't available already ??
is there some concerns or a better alternative to do this ??

thanks guys in advance, I love your work.

**Comment by bluebill1049** [comment]
have you considered attaching `trigger` with `onChange` if there is an error?

```tsx
onChange={(e) => {
  if (error[e.target.name]) {
    trigger(e.target.name)
  }
}}
```

**Comment by MTG2000** [comment]
you mean attaching this event listener to every input in the form ???
while this definitely would work, but I think it would become repetitive & a bit unclean.

**Comment by bluebill1049** [comment]
I hope we don't have to add more config to `trigger` nor change the current `trigger` behavior (as a breaking change). I am ping to this project board and see how many users do want such a feature to be implemented.

**Comment by danielweil** [comment]
Would love this feature! As of now, I am using submitHandle with an empty function inside of it.

**Comment by danielweil** [comment]
> Would love this feature! As of now, I am using submitHandle with an empty function inside of it.

But it would be very helpful in other scenarios.
