### ISSUE TITLE
Add Field Literal tying to UseFormRegisterReturn.name

### ISSUE THREAD

**Issue by mikepricedev** [react-hook-form/react-hook-form#8457]
**Is your feature request related to a problem? Please describe.**

I would like to get the field string literal type from the [`name`](https://github.com/react-hook-form/react-hook-form/blob/5e56b71ea7479bebb6ceb216e79c8b15b9d70a36/src/types/form.ts#L148) property on [`UseFormRegisterReturn`](https://github.com/react-hook-form/react-hook-form/blob/5e56b71ea7479bebb6ceb216e79c8b15b9d70a36/src/types/form.ts#L144) to use other React Form Hook APIs that make use of the field literal type e.g. `getValues`. 

**Describe the solution you'd like**

Modify `UseFormRegisterReturn` into a generic type of the form:
```
type UseFormRegisterReturn<TFieldName extends InternalFieldName = InternalFieldName> = {
    ...
    name: TFieldName;
    ...
};
```
Pass the inferred [`TFieldName` ](https://github.com/react-hook-form/react-hook-form/blob/5e56b71ea7479bebb6ceb216e79c8b15b9d70a36/src/types/form.ts#L194) from [`UseFormRegister`](https://github.com/react-hook-form/react-hook-form/blob/5e56b71ea7479bebb6ceb216e79c8b15b9d70a36/src/types/form.ts#L191) to the new `UseFormRegisterReturn<TFieldName>`

```
type UseFormRegister<TFieldValues extends FieldValues> = <TFieldName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>>(name: TFieldName, options?: RegisterOptions<TFieldValues, TFieldName>) => 
UseFormRegisterReturn< TFieldName >;
```

**Describe alternatives you've considered**

I currently use `as` casting when I use the name property from `UseFormRegisterReturn` with other apis.

**Additional context**

I have a fairly large form, so I've separated out a lot of the logic into custom hooks for maintainability.   Having that field literal attached to the results of a `register` call would avoid `as` casting the name in consumers of the custom hooks.  This is advantageous as the changes will flow to the consumers of the custom hooks without the need to hunt down and modify all the `as` casts.

I noticed that the name on the field result from `useController` is the field literal type.  If that behavior could be implemented with `register` that would be pretty cool.

Respectfully,
MP

**Comment by bluebill1049** [comment]
Moving to project board, i think this PR resolve your feature request: https://github.com/react-hook-form/react-hook-form/pull/8414
