### ISSUE TITLE
Regression: In v7, Controller rules cannot be changed dynamically

### ISSUE THREAD

**Issue by phinch** [react-hook-form/react-hook-form#8460]
### Version Number

7.30.0

### Codesandbox/Expo snack

https://codesandbox.io/s/controller-rules-forked-791u22?file=/src/App.tsx

### Steps to reproduce

1. In the CodeSandbox, there is a button that toggles whether validation should be performed on the input on the form.
2. Submit with and without value in the text input to show that validation works as expected
3. Click the "Skip validation" button to toggle off validation, which removes the `required: true` rule from the input
4. Attempt to submit the form with no value in the form
5. Observe that the input still fails validation, even though we are no longer passing any rules into `rules`
6. In a [v6 sandbox](https://codesandbox.io/s/controller-rules-forked-sbipnl?file=/src/App.tsx), observe that when following the same steps, the input does not fail validation in step 5

### Expected behaviour

I have two CodeSandboxes for this, which attempt to compare the same functionality between v6 and v7. I linked the v7 version in the link above, but for clarity, [here the functionality working in v6](https://codesandbox.io/s/controller-rules-forked-sbipnl?file=/src/App.tsx), and [here it is not working in v7](https://codesandbox.io/s/controller-rules-forked-791u22?file=/src/App.tsx).

Our team's expectation is that changing the rules object dynamically on different renders should change the way validation is performed in the form. We were using that functionality successfully in v6, but when we upgraded from v6.4.1 to v7.30.0, this stopped working. My guess is that this functionality change was introduced in v7, but i'm not 100% sure as I haven't identified the root cause of the change.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> Individual register option can't be removed by undefined or {}. You can update individual attributes instead.

https://react-hook-form.com/api/useform/register

<img width="941" alt="Screen Shot 2022-06-07 at 8 43 15 am" src="https://user-images.githubusercontent.com/10513364/172261283-1ada7fd8-573a-41f7-8865-b0832d99a6ef.png">

**Comment by phinch** [comment]
ah thank you! i hadn't seen that line in the updated docs

**Comment by bluebill1049** [comment]
no worries @phinch It's a trade-off, we saved some bytes without support `undefined` i remember 1-2% of the package size.

**Comment by wilav-dev** [comment]
I'm having same issue, it was working before v7. I'd like to be able to update all the rules dynamically.
For example, rules={validateMinLength ? {required: true, minLength: 8} : {required: true}}

I think it should take into account current value and not old rules. Otherwise, I should take prev state to revert it. Is it possible to take into account current rules as in v6?

**Comment by wilav-dev** [comment]
@bluebill1049 React is called like that because the code reacts to changes, so in my opinion is not intuitive to update an attribute and changes are not being applied. I'd like to know if it can be updated or should I implement a workaround? Thank you for always being maintaining this code!
