### ISSUE TITLE
dirtyFields and touchedFields not getting updated properly on a custom fieldArray with Yup validation

### ISSUE THREAD

**Issue by aquibbaig** [react-hook-form/react-hook-form#8461]
### Version Number

7.25.0

### Codesandbox/Expo snack

https://codesandbox.io/s/busy-cookies-vhgpvq?file=/src/App.tsx

### Steps to reproduce

1. Go to the sandbox
2. Click on Add
3. Scroll down to `dirtyFields`: see it shows true even when they are not manually inserted
4. Add some manual input to any field, see `touchedFields` not getting updated

### Expected behaviour

First of all, thank you for this awesome library, its the best form library I've used so far. The behavious I am expecting is the following: (this is so that, I can use something  like `!!touchedFields.users` to display input error state. Also the autoFocus issue sometimes throws me off as when I lose focus, I see error state even if I havent interacted with it

1. dirtyFields should be updated on user interaction rather than field array append.
2. touchedFields should get updated on user interaction with inputs

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
{"dirtyFields":[{"name":true,"id":true}]}
```
This is always true
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
related feature request: https://github.com/react-hook-form/react-hook-form/issues/8309 when the user appends or prepend, the form value will be updated.

**Comment by aquibbaig** [comment]
@bluebill1049 can we use `setValue` instead of append here?
