### ISSUE TITLE
issue: Trigger validation always updates error subscribers

### ISSUE THREAD

**Issue by iambryanhaney** [react-hook-form/react-hook-form#8462]
### Version Number

7.31.3

### Codesandbox/Expo snack

https://codesandbox.io/s/rhf-trigger-bug-p7ich5

### Steps to reproduce

1. Imperatively trigger validation on a single field using `trigger('fieldName')`
2. Any components subscribed to the formState.errors object will rerender, regardless of the validation result

### Expected behaviour

When the form is in `mode: 'onChange'`, field-level validations run on each key press, but they do not update the errors object / trigger a rerender unless there is a change to the validation result.

The imperative `trigger` helper feels like it should do the same.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for the issue report, we are optimizing for `trigger` as it's once of the level of code inject vs the actual performance impact may not be worth it especially when it comes to triggering an entire form or multiple fields. Instead onChange occurred on every keystroke when the user interacted with the input. Suppose `trigger` behavior impacts your form performance. In that case, I think there may be other issues related to your form. or you can consider sending us a feature request which we will consider if this is a need to implement if the demand is high, for the current state the current behavior with the trigger will stay as it is.

**Comment by iambryanhaney** [comment]
Ah, I see. I assume the optimization you mentioned is to skip the deep compare?

In my use case, once the form has submitted and switched to onChange mode, I'm wrapping multiple fields' onChange handlers to trigger a custom zod validation on their containing object (for errors that are related to the group, not the individual fields).

i.e.:

```
dimensions: {
  length, // These fields are triggering
  width,  // a custom zod validation on
  height, // the dimensions object
}
```

It works great, but because `trigger` behaves as described, every `onChange` event in those individual fields is rerendering the entire form.

**Comment by bluebill1049** [comment]
> Ah, I see. I assume the optimization you mentioned is to skip the deep compare?

yes, we skip the optimization for the `trigger`.

> It works great, but because trigger behaves as described, every onChange event in those individual fields is rerendering the entire form.

maybe it's worth to consider skip trigger if there is errors already present.
