### ISSUE TITLE
How to validate multiple checkboxes using custom register without using `ref` or `<Controller>`?

### ISSUE THREAD

**Issue by beebs93** [react-hook-form/react-hook-form#847]
**Question**
Hi team,

If you have a form with multiple checkboxes as part of an array, how can you validate against the entire array of values (e.g. ensure at least `n` checkboxes are checked) AND surface a single validation error in the `error` object provided by `useForm()` so you can render an error message?

Let's assume you have to manually register each field via `registers` within `useEffect` hook (i.e. you cannot use the `<Controller />` or inline `<input ref={register(...)} />` approach.

I found a [similar question here](https://github.com/react-hook-form/react-hook-form/issues/129), but none of the CSB links work anymore ☹️

**Codesandbox link**
https://codesandbox.io/s/rhf-submitted-question-csb-001-lfofq

**Comment by bluebill1049** [comment]
Question: when do you want to validate them? during onSubmit, onChange or Blur?

**Comment by beebs93** [comment]
> Question: when do you want to validate them? during onSubmit, onChange or Blur?

I would prefer to validate them during `onChange` and `onSubmit`.

**Comment by bluebill1049** [comment]
we can register them with validate function and set mode to `onChange`.

```
useForm({ mode: 'onChange' })
register('test', { validate: xxxx })
``

**Comment by beebs93** [comment]
Ok, but if you look at the code in the provided CSB link, how would you do this if you have to register each checkbox?

```js
register({ name: "myOptions[0]" });
register({ name: "myOptions[1]" });
register({ name: "myOptions[2]" });
```

**Comment by bluebill1049** [comment]
> Ok, but if you look at the code in the provided CSB link, how would you do this if you have to register each checkbox?
> 
> ```js
> register({ name: "myOptions[0]" });
> register({ name: "myOptions[1]" });
> register({ name: "myOptions[2]" });
> ```

https://codesandbox.io/s/rhf-submitted-question-csb-001-g8fqt

have a look what i got above. see if it make sense.

**Comment by bluebill1049** [comment]
> Yup, that makes sense. The `validate` method will be run `n` number of times, though, when you only really need it to be run once so depending on the validation being done, this could be an issue further down the line.

you can only give to one of them as well :)

**Comment by beebs93** [comment]
> > Yup, that makes sense. The `validate` method will be run `n` number of times, though, when you only really need it to be run once so depending on the validation being done, this could be an issue further down the line.
> 
> you can only give to one of them as well :)

Yeah, that would solve the dupe `validate` runs, but then when one of the other checkboxes is changed, the validation method won't trigger, no?

**Comment by bluebill1049** [comment]
> > > Yup, that makes sense. The `validate` method will be run `n` number of times, though, when you only really need it to be run once so depending on the validation being done, this could be an issue further down the line.
> > 
> > 
> > you can only give to one of them as well :)
> 
> Yeah, that would solve the dupe `validate` runs, but then when one of the other checkboxes is changed, the validation method won't trigger, no?

yea true dat. otherwise you can go with validation with a schema. however, I think it should be quite cheap to run those functions.

**Comment by beebs93** [comment]
> * yea true dat. otherwise you can go with validation with a schema. however, I think it should be quite cheap to run those functions.

I haven't used `yup` before, but from my 30sec worth of reading I'm not seeing how you wouldn't also run into the problem of unnecessary dupe custom validation method invocations.

> * you can add onChange with the rest of them to trigger validation of that input have validation

I'm not following what you mean by this. The way I understand (and correct me if I'm wrong, please), you have to include the `validate` function/object when you `register` each the inputs so when the user submits the form, you're still going to invoke each validation method.

---

So to zoom out a bit, it feels like we're getting into more "duct tape and super glue"-type solutions  which is a fun mental exercise, but I feel will not be very intuitive to the other consumers of `react-hook-form`.

How about I come at this from the other direction: would it be possible to custom `register` my checkboxes like the following _without_ needing a PR?

```js
const { register, errors, setValue, setError, clearError, handleSubmit } = useForm();

const validate = () => {
  const { myCheckboxes = [] } = getValues({nest: true});
  const filteredValues = myCheckboxes.filter(v => typeof v === 'string');
  
  if (filteredValues.length >= 2) {
    clearError('myCheckboxes');
  } else {
    setError('myCheckboxes', 'minChecked');
  }
}

const handleChange = e => {
  setValue(e.target.name, e.target.checked ? e.target.value : null);
};

const onSubmit = (data) => {
  console.log('data', data);
}

useEffect(() => {
  register( { name: 'myCheckboxes' }, { validate }); 
}, [register]);

return (
  <form onSubmit={handleSubmit(onSubmit)}>
    <label>Choose at least two options</label>

    <label>
      Foo{" "}
      <input
        type="checkbox"
        name="myCheckboxes[0]"
        value="foo"
        onChange={handleChange}
      />
    </label>

    <label>
      Bar{" "}
      <input
        type="checkbox"
        name="myCheckboxes[1]"
        value="bar"
        onChange={handleChange}
      />
    </label>

    <label>
      Baz{" "}
      <input
        type="checkbox"
        name="myCheckboxes[2]"
        value="baz"
        onChange={handleChange}
      />
    </label>

    { if errors && errors.type === 'minChecked' && <p>Select at least two options</p> }

    <input type="submit" />
  </form>
);
```

Custom `register`s are verbose by nature, but an API like this just seems a bit more idiomatic while still being performant.

Thoughts?

**Comment by bluebill1049** [comment]
> I'm not following what you mean by this. The way I understand (and correct me if I'm wrong, please), you have to include the `validate` function/object when you `register` each the inputs so when the user submits the form, you're still going to invoke each validation method.

I meant like this
```
<inpug name="1" ref={register({ validate })} />
<inpug name="2" ref={register} onChange={() => {
  triggerValidation('1')
}} />
```

**Comment by bluebill1049** [comment]
that's a good solution that you come up with too. 👍

**Comment by beebs93** [comment]
> that's a good solution that you come up with too. 👍

Well, it's theoretical as the APIs don't support such a syntax. My question was whether it was possible in some way to only `register` a single checkbox that references all checkboxes while meeting my initial requirements; doesn't look like it would be.

**Comment by beebs93** [comment]
> > I'm not following what you mean by this. The way I understand (and correct me if I'm wrong, please), you have to include the `validate` function/object when you `register` each the inputs so when the user submits the form, you're still going to invoke each validation method.
> 
> I meant like this
> 
> ```
> <inpug name="1" ref={register({ validate })} />
> <inpug name="2" ref={register} onChange={() => {
>   triggerValidation('1')
> }} />
> ```

Hmm, ok - I see what you mean now - thanks for the clarification.

You would still have to add the manually `setValue` for any manually `register`ed checkboxes, but something like this may work.

**Comment by bluebill1049** [comment]
> > > I'm not following what you mean by this. The way I understand (and correct me if I'm wrong, please), you have to include the `validate` function/object when you `register` each the inputs so when the user submits the form, you're still going to invoke each validation method.
> > 
> > 
> > I meant like this
> > ```
> > <inpug name="1" ref={register({ validate })} />
> > <inpug name="2" ref={register} onChange={() => {
> >   triggerValidation('1')
> > }} />
> > ```
> 
> Hmm, ok - I see what you mean now - thanks for the clarification.
> 
> You would still have to add the manually `setValue` for any manually `register`ed checkboxes, but something like this may work.

Not really with set value all inputs have registered.

**Comment by bluebill1049** [comment]
> > > I'm not following what you mean by this. The way I understand (and correct me if I'm wrong, please), you have to include the `validate` function/object when you `register` each the inputs so when the user submits the form, you're still going to invoke each validation method.
> > 
> > 
> > I meant like this
> > ```
> > <inpug name="1" ref={register({ validate })} />
> > <inpug name="2" ref={register} onChange={() => {
> >   triggerValidation('1')
> > }} />
> > ```
> 
> Hmm, ok - I see what you mean now - thanks for the clarification.
> 
> You would still have to add the manually `setValue` for any manually `register`ed checkboxes, but something like this may work.

Custom register yes. Because there is no reference to the input itself.

**Comment by beebs93** [comment]
I'll play around with this today and see if I can get something working. Will update with results later.

**Comment by beebs93** [comment]
> I meant like this
> ```
> <inpug name="1" ref={register({ validate })} />
> <inpug name="2" ref={register} onChange={() => {
>   triggerValidation('1')
> }} />
> ```

I ended up solving this, but the above solution didn't work the way I wanted as I was having trouble getting the validation trigger when the first checkbox was clicked first as well as getting the submit to properly validate.

I had to resort to your original solution of simply adding the same validation `n` times to each checkbox's `register`.

Working solution: https://codesandbox.io/s/rhf-submitted-question-csb-001-lfofq

If there's a way to do it like you suggested, I'd love to see it, but for now I have a path forward.

Thanks for the quick responses and your assistance - much appreciated! 😀

**Comment by bluebill1049** [comment]
no worries @beebs93 Once i get some free time after solving some of the bugs. i will do an example and see if it's workable 👍

**Comment by bluebill1049** [comment]
you happy to close this issue for now?

**Comment by beebs93** [comment]
> you happy to close this issue for now?

Yup!
