### ISSUE TITLE
issue: incorrect types for form.getFieldState

### ISSUE THREAD

**Issue by luizeboli** [react-hook-form/react-hook-form#8470]
### Version Number

7.31.3

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-type-error-0174wm?file=/src/App.tsx

### Steps to reproduce

1. Create a form with nested fields
2. These nested fields must have any kind of validation
3. Trigger the nested field validation to an error state (click submit button)
4. Use `form.getFieldState`
5. Try to access the nested field property inside fieldState.error object

### Expected behaviour

TS should not throw a `Property does not exist on type ....` error. (Take a look at the `console.log` expression)

The `error` property from `form.getFieldState` is typed as `FieldError`, but sometimes you have nested fields validation, in these cases there will be an upper level in the `error` property, invalidating this type.

![image](https://user-images.githubusercontent.com/13091635/172466729-1f38afc8-2939-4908-a9c3-33fc349729a5.png)

![image](https://user-images.githubusercontent.com/13091635/172466849-ddc7c43b-d250-4506-b27e-bfbd15782646.png)

In my scenario I can't simply call `getFieldState(field.innerProp)` because it's a component that watch dynamic fields.

### What browsers are you seeing the problem on?

Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
It's meant for the retrieved nested field type, not deep object look up.

a nested field type such as react select's error should be at the root level. 

```tsx
type FormValues = {
  field: { innerProp: string; anotherProp: string };
};

register('field')

form.getFieldState("field") // it should return the root error not the object inner
```

if your input is not a nested object you should use the dot notation to look up that field. `field.name` or simply use the errors object.

**Comment by luizeboli** [comment]
hey @bluebill1049 just to make things clear for me.

When the form has nested object fields we must access through `getFieldState(field.name)` instead of `getFieldState(field).name` ?
