### ISSUE TITLE
issue: Nested errors cleared when clearErrors called with field array root

### ISSUE THREAD

**Issue by zach-waggoner** [react-hook-form/react-hook-form#8476]
### Version Number

6.15.8

### Codesandbox/Expo snack

https://codesandbox.io/s/immutable-bush-f2uwhx

### Steps to reproduce

1. Click submit
2. Enter text into Field 0

### Expected behaviour

Error message for Field 1 should not be cleared.

I have server validation that sets an error on the root field array key (because the error applies to all fields taken together). At the same time, I have individual field validation for the fields (such as being required). If the submit handler sets an error at the root of the field array, I would like any change to any of the fields to clear that error, which I accomplish by calling `clearErrors` on the change handler of the field array inputs. This works, but if there are individual field-level errors rather than just a root error, it clears those as well, and I am not sure of any way to clear the root error without clearing the individual field errors.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Thanks for the issue report.

This is expected behavior, if you want to clear individual errors use the full name path instead of the root key name.

```diff
- clearErrors('root')
+ ['item1', 'item2'].forEach(clearErrors(name))
```

**Comment by zach-waggoner** [comment]
To be clear, I do not wish to clear individual errors. I am looking for a way to clear the root key error, _without_ incidentally clearing the individual field errors of the field array.

**Comment by bluebill1049** [comment]
That's exactly what I meant above, it's not supported by the function you will have to pass the input name. to achieve your expected behaviour, the function will need to recursively loop though the entire errors, which is something we don't do and probably will as well.

**Comment by zach-waggoner** [comment]
I’m not sure I understand. The code example in your comment would clear each individual field error one-by-one, which isn’t what I want. Rather, I want to leave the individual field errors, and only remove the one set at the root of the field array. Is there a way to accomplish this?

**Comment by bluebill1049** [comment]
No, we don't, you have to specify the field name.

**Comment by zach-waggoner** [comment]
Okay, I don't think my point is getting across. Please take another look at the Codesandbox. If you hit submit, the errors object looks like:

```
{
  fields: {
    0: { type: "server", message: "Field 0 error." },

fields: Object
0: Object
name: Object
type: "server"
message: "Field 0 error."
ref: 
<input name="fields[0].name"></input>
1: Object
name: Object
type: "server"
message: "Field 1 error."
ref: 
<input name="fields[1].name"></input>
type: "server"
message: "General fields error."
ref: undefined

**Comment by bluebill1049** [comment]
can you flat that server error? otherwise, i don't think it's going to work out.
