### ISSUE TITLE
How to show errors in nested array fields using formcontext

### ISSUE THREAD

**Issue by vivekmpuh** [react-hook-form/react-hook-form#848]
Hi

I am trying to show error message on nested array field, I am able to display the error message but the error message wont remove.

the component structure goes as shown below

```
const [ arrayObject, setarrayObj ] = useState([{ name: 'one', value:'one' },{ name: 'one', value:'two' },{ name: 'one', value:'three' }])

<FormContext {...methods}>
      <form onSubmit={methods.handleSubmit(onSubmit)}>
        <NestedInput  fields={this.state.arrayObject} />
        <input type="submit" />
      </form>
</FormContext>

```

and the **NestedInput** field as shown below

```
const {errors, register, setError} = useFormContext();
const {fields} = props;

<div>
{fields.map((field) => (
    <>
        <input type="text" name={field.name}  ref={register} validate={(value) => { let vaid = myValidationFn(field, setError); return valid }} />
        {errors[field] && errors[field].message && <span>{errors[field]}</span>}
    </>
))}
<div>
```
and I have imported **myValidationFn** which handles validation and error messages using **setError()** function with required information. 

if there is error on the one of the array field, the **NestedInput** fields wont re-render for other nested fields even if there's no error (as the component wont re-render in this case) how can i re-render the **NestedInput** component when there's no error on on one of the array field.

InShort : Every array field should show its own error message, and remove error if there is no error on that field

is there anything i'm missing in this ?

Thanks

**Comment by bluebill1049** [comment]
please follow our issue template and at least supply a codesandbox.

**Comment by bluebill1049** [comment]
Closing for now until more detail supplied
