### ISSUE TITLE
issue: Checkbox array - order matters for the formState.isDirty

### ISSUE THREAD

**Issue by Krelix1** [react-hook-form/react-hook-form#8491]
### Version Number

7.31.3

### Codesandbox/Expo snack

https://codesandbox.io/s/busy-wood-cilm4c?file=/src/App.js

### Steps to reproduce

1. Click `Add checkbox`
2. Click on any checkbox twice
3. isDirty is not working

### Expected behaviour

I have a case similar to that I provided in the Sandbox.
I have an infinity loader in the list of checkboxes. When new checkboxes is fetched, I call reset with new defaultValues. The goal is to keep already checked checkboxes ( to do this I provide a keepValues / keepDirtyValues field ). But as you can see something go wrong and isDirty is breaking. Is this a bug or is there another way to do this?

P.S. Order matters
`              // this is okay
              { checkboxes: ["A", "B"]},
              // this is not
              { checkboxes: ["B", "C"] },
`

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we are doing a deep equal with the current value against your `defaultValues`. This is expected.
