### ISSUE TITLE
Objects used as values lose prototype information when cloned

### ISSUE THREAD

**Issue by monesidn** [react-hook-form/react-hook-form#8495]
### Version Number

7.26 and successive

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-forms-es6-classes-example-cyjyi5

### Steps to reproduce

1. Click any color
2. Click on `submit`
3. See error

The problem is caused by the fact that when a object is copied it loses it's prototype. 
Downgrading the react-hook-forms dependency to 7.25.1 in package.json will result in form starting to work.

### Expected behaviour

The selected color should be reported the horizonal bar. The value objects should retain the prototype when cloned.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Please don't include complex object which contains function, as this will not work correctly during the clone object proper. This is by design to clone objects into the hook.

**Comment by monesidn** [comment]
Ok. I understand that right now it is a design limitation but I think it could easily overcomed with a couple of improvments on the code cloning objects. Does it makes sense to roll down a PR or are we excluding this anyway?

**Comment by bluebill1049** [comment]
Thanks @monesidn it depends on how much code we would like to roll down and how many use cases we would like to cover.

**Comment by monesidn** [comment]
Ok, I can do it. I've read the CONTRIBUTING file and will follow instructions from there. Anyway Is there a document I haven't seen listing all supported use cases?

**Comment by bluebill1049** [comment]
Feel free to send a PR we will take a look at it. thank in advance.
