### ISSUE TITLE
issue: isValid flag has wrong value

### ISSUE THREAD

**Issue by matkrzy** [react-hook-form/react-hook-form#8497]
### Version Number

7.32.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-isvalid-falg-issue-psnelu

### Steps to reproduce

1. Click submit button
2. Then wait for fields error
3. And `isValid` should be false
4. Change the value for one field
5. Then `isValid` is true

### Expected behaviour

The `isValid` flag should equal false if the form has errors

### Additional info
It is working fine with version 7.7.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/useform/seterror

> This method will not persist the associated input error if the input passes register's associated rules.

**Comment by matkrzy** [comment]
@bluebill1049 The behaviour of replacing error messages with validations is clear but I am facing a different issue

```JSON
{
  "isValid": true,
  "errors": {
    "lastName": "Required"
  }
}
```
This is the form state when I change one field value. Form has error but `isValid` flag is true

**Comment by matkrzy** [comment]
The last question, just to be sure. This breaking change between 7.7.1 and 7.8.0 is intended and fine?
![Zrzut ekranu 2022-06-15 o 09 02 37](https://user-images.githubusercontent.com/14991661/173763711-e96858e6-1634-4fac-bccf-5e7f6c702609.png)
![Zrzut ekranu 2022-06-15 o 09 01 32](https://user-images.githubusercontent.com/14991661/173763411-f8e7f2dd-f12d-4740-9832-2a4e495affcc.png)
![Zrzut ekranu 2022-06-15 o 08 58 51](https://user-images.githubusercontent.com/14991661/173763430-d1c1d90b-1bea-4417-8774-7ce1e768ad7b.png)
I need to manually check if form is valid by checking `formState.errors` elements?
Is this behaviour described somewhere?

**Comment by bluebill1049** [comment]
I would refer to the release and check the commit, this should be a bug fix.

**Comment by quicksnap** [comment]
@bluebill1049 I think I am affected by this as well. Should this be reopened?

**Comment by quicksnap** [comment]
It may have to do with this commit, but I am just guessing: https://github.com/react-hook-form/react-hook-form/commit/c26533fc746b9f73b937b3c951a38b7677a9c21f

**Comment by bluebill1049** [comment]
@quicksnap could you share a codesandbox if this is related to the above? `setError` has no effect on `isValid` state

**Comment by quicksnap** [comment]
I'll try and replicate my issue in a sandbox and open a new ticket. Thanks!

**Comment by bluebill1049** [comment]
Basically `isValid` is derived by the entire form validation (registration) rules or scheme to validate the result, with no effect on the article error set by the setError.

**Comment by bluebill1049** [comment]
> I'll try and replicate my issue in a sandbox and open a new ticket. Thanks!

sure, we can ping point the issue and see if we can resolve it.

**Comment by quicksnap** [comment]
Created #8601 with simplified repro for my issue
