### ISSUE TITLE
issue: checkbox arrays do not work with other than string values

### ISSUE THREAD

**Issue by Karolis92** [react-hook-form/react-hook-form#8499]
### Version Number

7.32.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-get-started-forked-mbc1q8?file=/public/index.html

### Steps to reproduce

1. Go to Codesandbox
2. 1 and 2 checkboxes for `strings` are selected, but for `numbers` - not
2. Check on some checkboxes  in `number` and submit
4. Values for numbers field are string, not numbers

### Expected behaviour

`numbers` array should have numbers in it.

Tried `valueAsNumber`, `setValueAs` - none worked

One thing kind of worked was creating custom input with `Controller` where it handles change by taking current field value array and adding or removing value form it and setting it back. But this seems very tedious and now anyone who uses this not only has to work with `register` function but also `controller` depending on the input type (I could get it from context, but we like type safety of `register` fn).

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
register with native checkbox only support string and by following the native HTML value without any extra parsing, if you want to support other custom data types, please build a controlled component and wrapped with the controller.

**Comment by Karolis92** [comment]
can this be reopened as feature request? or are there any reasons to not implement this?

**Comment by bluebill1049** [comment]
for all the native input, we are trying to stay as close as possible with them without introducing extra logic/transform/parsing.  Keep the responsible of registering API small and lean, for any of those custom requirements for data type, I would recommend going with controlled components as that's what they are designed for.

**Comment by Karolis92** [comment]
ok understood, still seems strange that in RHF valueAsNumber and setValueAs works for text inputs, because valueAsNumber does not work in plain html form non number type inputs.

setValueAs seems a good place to do transformations  not only for numbers. That would add flexibility to the lib.

**Comment by bluebill1049** [comment]
Yes, I agree but we try to follow the standard for the native here. you can refer to the spec here: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement It's by design so what you learn with native HTML will cross-work between this library.
