### ISSUE TITLE
Support isValid check for nested objects only within form values

### ISSUE THREAD

**Issue by mcmxcdev** [react-hook-form/react-hook-form#8502]
**Is your feature request related to a problem? Please describe.**

We are working on a form that looks like this (simplified):

```
user: {
  firstName: '',
  lastName: '',
},
spouse: {
  firstName: '',
  lastName: '',
},
dependent: [{
  firstName: '',
  lastName: '',
}]
```

It's visually basically three different forms to fill out and after each one is filled, they should e.g. collapse and change border and get a checkmark.

`isValid` only gives back a boolean and doesn't give me the ability to check if e.g. `user` object is already valid, while spouse and dependent aren't.

**Describe the solution you'd like**
Maybe something like `isValid("user")`, which would check the whole tree of properties.

**Describe alternatives you've considered**
I am currently using a helper method:
`Object.keys(entity).length > 0 &&
    Object.values(entity).every((elem) => elem != '')`
    
But it only covers if string fields have any value and not if they fulfil the yup schema criteria.

**Additional context**
I wonder if this can be achieved with `yup` alone, but was unable to figure out a way.

**Comment by bluebill1049** [comment]
hey @mcmxcdev thanks for the feature request, are you after `validFields` state?

**Comment by mcmxcdev** [comment]
I think I was able to achieve what I wanted with `getFieldState("user").error`

Thank you!

**Comment by bluebill1049** [comment]
awesome 🕺

**Comment by mcmxcdev** [comment]
Well, I was able to resume what I started today, but I wasn't able to make it work as I wanted with `getFieldState()`.

`getFieldState()` only gives me `.invalid` and `.errors` properties → which means filling out a single field inside e.g. spouse form would already mark the form as valid (since it not invalid) when only a single field is filled out, but others are still missing.

I can't use `formState.isValid`, because then I wouldn't be able to have nested valid forms, e.g. form 1 and form 3 could be valid while form 2 is not yet.

I think what I would need here is e.g. `getFieldState("user").isValid` (to know the moment once a nested form has been fully filled out) rather than `getFieldState("user").invalid` (which would only notify me on errors but not if all fields are filled out or not)

**Comment by bluebill1049** [comment]
np, will move into project board, is there any other walk around for now?

**Comment by mcmxcdev** [comment]
Thank you so much for looking into this!

If you need a reproduction repo let me know.

I might be able to achieve something with yup schema.validate in the mean time but will have to check.

**Comment by bluebill1049** [comment]
@mcmxcdev reproduction repo (codesandbox) would be great 👍

**Comment by mcmxcdev** [comment]
> @mcmxcdev reproduction repo (codesandbox) would be great +1

There you go: https://codesandbox.io/s/holy-wave-g2862z
I kept it really basic, hope it explains and illustrates the problem good enough.

**Comment by bluebill1049** [comment]
Thanks for the CSB.

> {isEntityFilledOut("user") && "user was filled out"}

Do you mean the user fields are been all fields and valid?

**Comment by mcmxcdev** [comment]
I want that message only to show once all `user`-related fields are filled out, currently it shows already on any filled out `user` field.

In this case there are only `firstName` and `lastName` fields but in a real world case there would be many more fields. Some might have initial values, other fields might be optional.

**Comment by bluebill1049** [comment]
> user-related fields are filled out

so a group level `touched` state?

**Comment by mcmxcdev** [comment]
No, because some fields can be prefilled while others are empty. 

Fields should not be empty and conform to e.g. `yup` validation requirements on a group level, then it counts as correctly filled out.

**Comment by Upinwv** [comment]
I

--

**Comment by mcmxcdev** [comment]
Any update on this?

**Comment by thiago-ssilva** [comment]
Any update on this²?  Having similar issue

**Comment by Moshyfawn** [comment]
I'd say, there's no other way other than just checking each and every nested field for validity. I can't see how we can ever correctly determine if the object is a field or not for every use-case.
