### ISSUE TITLE
issue: can't register an item in a FieldArray outside of the list

### ISSUE THREAD

**Issue by ddhp** [react-hook-form/react-hook-form#8507]
### Version Number

7.32.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-7odli5?file=/src/index.js

### Steps to reproduce

The codesandbox is forked from the example for `FieldArray`

The feature I want to achieve is to edit items in a FieldArray outside of the list.
So I added two inputs on the page, one is using `register` and `Controller` for the other one,
```js
      <input {...register(`test.${currentIndex}.firstName`)} />
      <Controller
        render={({ field }) => <input {...field} />}
        name={`test.${currentIndex}.firstName`}
        control={control}
      />
```
`currentIndex` is a state telling the index of the item in the fieldArray is currently selected

What I am expecting is: when I select an item, for all three inputs(i.e those 2 inputs above and the one in the fieldArray), registered with `test.${i}.firstName`, should have the latest value and able to edit it. But the behaviour so far seems inconsistent

### Expected behaviour

inputs registered the same name in a fieldArray should be up to date.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is currently not supported, field array input will need to be associated with the fields object and updated with a key associated with each input.
