### ISSUE TITLE
useFieldArray methods do not sync with Controlled components

### ISSUE THREAD

**Issue by hedzerkoolstra** [react-hook-form/react-hook-form#8508]
### Version Number

7.27.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-lvq1e4?file=/src/index.js

### Steps to reproduce

1. Go to Sandbox
2. Click on the remove button in the first row

### Expected behaviour

I expect the first row, with value 1, to be deleted and the second row, with value 7, to remain.
Instead I see the row with value 1 still being there. 
When logging `product.amount` on line 28 I see that the fields property is rendering the expected value .
Apparently the remove function does update fields but the Controller is not updated which causes unexpected behavior and it feels the two are out of sync. 

Not sure if this is a bug or if controlled components are not supposed to work with useFieldArray. Would love to hear what the best approach is here. Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
<img width="1270" alt="Screen Shot 2022-06-16 at 8 44 50 am" src="https://user-images.githubusercontent.com/10513364/173954571-dda8afac-c0fe-4bd8-9396-4deab5fc088b.png">

please fix your codesandbox first.

**Comment by bluebill1049** [comment]
your usage issue: <button onClick={() => append({ amount: false })}>Add</button> please refer to the doc and provide correct append input values.

**Comment by hedzerkoolstra** [comment]
Sorry about that, I think I didn't save the latest version. It should be updated now. 
For some reason Code Sandbox keeps refreshing after click but you can still see the behavior I described.

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-e0xow1?file=/src/index.js
