### ISSUE TITLE
defaultValues Partial / DeepPartial causes unsafe typings

### ISSUE THREAD

**Issue by quicksnap** [react-hook-form/react-hook-form#8510]
**Is your feature request related to a problem? Please describe.**

Consider the following: 
```tsx
interface MyFieldValues {
  name: string;
}

const MyForm = () => {
  const { watch } = useForm<MyFieldValues>({ defaultValues: {} });

  const name = watch('name'); // const name: string;

  name.toUpperCase(); // TypeError! name is undefined
};
```

The type inference for `useForm` is very good, but forcing a partial opens it up to unnecessary runtime errors.

In situations where your form may not have values present, it should instead be typed appropriately: 
```tsx
interface MyFieldValues {
  name: string | undefined;
}
```

**Describe the solution you'd like**

A few approaches come to mind:

* Remove `DeepPartial`. This would be a breaking change and possibly upset developers that do not want strict typing.
* Expose an alias, `useFormStrict` with a strict type definition. It would use the same runtime code as `useForm`
* Extend the generics of `useForm` to be `useForm<TFieldValues, TContext = any, TStrictValues = false>(...)`. The types could leverage `TStrictValues` to conditionally use `DeepPartial`.

**Describe alternatives you've considered**

The current workaround is to strictly define your default values upfront:
```tsx
const MyForm = () => {
  const defaultValues: MyFieldValues = {}; // Error: Property 'name' is .. required in type 'MyFieldValues'
  const { watch } = useForm<MyFieldValues>({ defaultValues });
// ... snip ...
```

This has the "pit of failure" downside--if developers forget to do this, they may encounter runtime errors later.

**Additional context**

Happy to contribute changes here if we want to make an adjustment for current or future version.

**Comment by quicksnap** [comment]
Additionally, in a stricter mode, `defaultValues may want to be required.

**Comment by bluebill1049** [comment]
100% buy-in on this, we are moving away `deepPartial` for `defaultValues` and `reset` API. This is likely to be part of the next major V8, which reset is already been implemented. https://github.com/react-hook-form/react-hook-form/discussions/7433 The sad thing is currently V8 branch is blocked by TS 4.7 update with lazy path check. It's a bumper for sure, we may have to give up on the lazy field path and look up.  https://github.com/react-hook-form/react-hook-form/pull/5941#issuecomment-1149237559 you happy to close this feature request and leave a not in the RFC, let's move forward with this strict type check for `defaultValues`.

**Comment by quicksnap** [comment]
If it's slated for V8, then that's perfect for me! Great to know. I'll leave a note there now.

**Comment by bluebill1049** [comment]
yes, we are definitely going ahead of that, especially since the lazy field path may have to be reverted due to the ts 4.7 change.
