### ISSUE TITLE
issue: handleSubmit crashes on Promise.reject

### ISSUE THREAD

**Issue by VickyKoblinski** [react-hook-form/react-hook-form#8514]
### Version Number

7.31.3

### Codesandbox/Expo snack

https://codesandbox.io/s/ecstatic-pascal-m68fh7?file=/src/App.tsx

### Steps to reproduce

Basically this:

```
const { onSubmit } = useForm();

const onSubmit = () => new Promise((resolve, reject) => { reject("You can't handle me") });

return <form onSubmit={handleSubmit(onSubmit)} />
```

### Expected behaviour

`handleSubmit` accepts a Promise, so I would expect it works if that Promise is rejected.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
index.esm.mjs?b4ba:1972 Uncaught (in promise) hi
eval	@	index.esm.mjs?b4ba:1972
await in eval (async)		
callCallback	@	react-dom.development.js?ac89:4161
invokeGuardedCallbackDev	@	react-dom.development.js?ac89:4210
invokeGuardedCallback	@	react-dom.development.js?ac89:4274
invokeGuardedCallbackAndCatchFirstError	@	react-dom.development.js?ac89:4288
executeDispatch	@	react-dom.development.js?ac89:9038
processDispatchQueueItemsInOrder	@	react-dom.development.js?ac89:9070
processDispatchQueue	@	react-dom.development.js?ac89:9083
dispatchEventsForPlugins	@	react-dom.development.js?ac89:9094
eval	@	react-dom.development.js?ac89:9285
batchedUpdates$1	@	react-dom.development.js?ac89:26096
batchedUpdates	@	react-dom.development.js?ac89:3988
dispatchEventForPluginEventSystem	@	react-dom.development.js?ac89:9284
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay	@	react-dom.development.js?ac89:6462
dispatchEvent	@	react-dom.development.js?ac89:6454
dispatchDiscreteEvent
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks, @JamesWong1999 yes, that's expected we do not swallow errors or promise rejection inside the handler.

**Comment by VickyKoblinski** [comment]
I see, thank you for the link! :D The typing of the form submit onValid prop gives the illusion that you can expect to return a promise and be okay but I see now that handleSubmit has a whole chain of stuff to it. A more helpful error message would be very useful here though for better discoverability, especially since you need to return a promise if you want the loading/submitted states to be set correctly.

**Comment by bluebill1049** [comment]
thanks for the feedback, PR welcome to improve on this topic, for loading state, we do expose `isSubmitting` formState, if that helps.
