### ISSUE TITLE
Validation order follows yep schema rather than jsx field order

### ISSUE THREAD

**Issue by joe4mg** [react-hook-form/react-hook-form#852]
Hi - when validating against a Yup schema the form validates in the order of the schema keys rather than the order of the fields in the JSX.

https://codesandbox.io/s/react-hook-form-validationschema-l3q6q
^ validates the `age` field first

https://codesandbox.io/s/928po918qr
^ validates the `firstName` field first

Is there a way to define a field index/prevent this from happening besides the schema matching the form field order.

The reason I find current behaviour problematic is because I'm merging schemas.

**Comment by bluebill1049** [comment]
We following the order of your yup schema validation. It will be difficult to track as your render component, it can get re-order during render. (if this is what you refer to).
