### ISSUE TITLE
Trigger should also consider ReValidateMode 

### ISSUE THREAD

**Issue by Cafezinho** [react-hook-form/react-hook-form#8539]
### Version Number

7.4.1

### Codesandbox/Expo snack

https://codesandbox.io/s/wandering-thunder-jns2x9?file=/src/App.tsx

### Steps to reproduce

1. Click button Trigger to call trigger method.
2. See required error message.
3. Type anything into input
4. Revalidation should trigger due to onChange and error should disappear.

### Expected behaviour

Good afternoon! Thanks for the awesome package! Really love it and it helps us a lot.

I don't know if it is expected, but it would be awesome and very helpful if useForm's reValidationMode was also considered when triggering validation using trigger method.

The above behavior does not happen, and don't know if this is a bug or a feature request.
So don't mind changing this issue's category.
Is it possible to make this behavior happen?

Thanks!

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Please send a feature request instead, this current behaviour is expected and as documented.
