### ISSUE TITLE
Controller.onBlur should not overwrite value when in onBlur validation mode

### ISSUE THREAD

**Issue by IronSean** [react-hook-form/react-hook-form#854]
**Describe the bug**
I'm running into an issue where an input I'm attempting to wrap (which is a DatePicker) returns a Date from OnChange, but a formatted String from OnBlur. react-hook-form is seemingly saving this String, then passing it back as the `value` which blows up the app as the PropType check fails extecting a Date.

I'm not sure who is truly at fault here. They shouldn't be returning a String on their OnBlur event (and I opened [this issue](https://github.com/telerik/kendo-react/issues/447) about it). But It also seems unintuitive that react-hook-form would be overwriting the saved values in it's controller on a OnBlur, even if it's attempting to re-run the validations then. OnChange seems like the more appropriate method to update the saved value.

**To Reproduce**
1. Wrap a @progress/kendo-react-dateinput DatePicker in a react-hook-library Controller
2. Set validation to OnBlur
3. Interact with the DateInput to trigger a blur event

**Codesandbox link**
https://codesandbox.io/s/broken-thunder-9f4m3

**Expected behavior**
I would expect OnChange to update the values in the Controller, and OnBlur to not modify those values, but just trigger the validations on the already saved values if validations are in OnBlur mode.

**Desktop (please complete the following information):**
 - OS: Windows (and CodeSandbox)
 - Browser Chrome
 - Version 79

**Additional context**
As mentioned, I opened an issue there as well, and the reproduction in the code sandbox is very straightforward.

**Comment by bluebill1049** [comment]
Your codesandbox is broken, also have u tried overwrite on blur?

**Comment by Hendrafoo** [comment]
@bluebill1049 take a look at my sandbox
https://codesandbox.io/s/react-hook-form-get-started-596q6
but this one is with Material UI Autocomplete

**Comment by bluebill1049** [comment]
thanks @Hendrafoo ❤️

**Comment by bluebill1049** [comment]
i have append validation to your example as well @Hendrafoo https://codesandbox.io/s/react-hook-form-get-started-47mhr

**Comment by IronSean** [comment]
Yes, the codesandbox is broken, It wouldn't be reproducing the bug if it worked. The validation itself is not the issue. The issue is that during OnBlur, you are reading the text value of the input instead of the Date value of the input that OnChange returns, then passing it back. The issue is just that in OnBlur mode, the OnBlur action is updating the saved values in the controller then writing them back to the input. 

To me this makes no sense, OnBlur is not a value updating event, it's an input focus event. The controller should still have the latest value from the last OnChange, when it was last changed.

Maybe this one is clearer:
https://codesandbox.io/s/competent-tree-4ydkc

The issue as I see it is for some reason OnBlur is writing a new value before running validations. 

Example 1: Normal OnChange handling. The input fires OnChange events with updated Date value, the Controller takes them, and returns them to the value prop.

Example 2: The OnChange still works normally, but when OnBlur fires the Controller now reads the text contents of the DatePicker rather than the Date object that was returned with OnChange. It passes the text back, and the PropType check fails and crashes the app.

Example 3: Override OnBlur to return a Date. Now the controller works properly, and returns that overridden date. It doesn't crash, but now I need to write a custom function to get the proper date value to return in OnBlur, because the Controller is taking OnBlur values instead of the last OnChange value it was passed. I can do this, but I don't see why OnBlur is being treated like a value updating method instead of just a signal to trigger validations on the already passed values.

**Comment by bluebill1049** [comment]
> Yes, the codesandbox is broken, It wouldn't be reproducing the bug if it worked.

When I open the codesandbox link it was a dead link that's what I was referring to. 

> I'm not sure who is truly at fault here.

Nobody's fault, it's open-source :) people give it for free, they make mistake and get fixed.

> OnBlur is not a value updating event, it's an input focus event. The controller should still have the latest value from the last OnChange, when it was last changed.

This make sense, happy to adjust.

**Comment by IronSean** [comment]
> > Yes, the codesandbox is broken, It wouldn't be reproducing the bug if it worked.
> 
> When I open the codesandbox link it was a dead link that's what I was referring to. (hence tagged need more detail)

Very strange, it still works for me. That was why I was confused. Sorry if my reply was snarky.

> > I'm not sure who is truly at fault here.
> 
> Nobody's fault, it's open-source :) people give it for free, they make mistakes and get fixed.

I moreso I'm not sure if react-hook-form should change how it handles onBlur, or the DatePicker should be changing how it generates blur events.  Possibly both, but wanted to leave things open to discussion if there was a strong arguement for react-hook-form taking values from OnBlur, etc.

> > OnBlur is not a value updating event, it's an input focus event. The controller should still have the latest value from the last OnChange, when it was last changed.
> 
> This makes sense, happy to adjust.

Thank you! We've worked around it for now, but I think that change will be clearer!

**Comment by bluebill1049** [comment]
> Thank you! We've worked around it for now, but I think that change will be clearer!

I think it makes sense not to update value during onBlur. What do you think guys? @JeromeDeLeon @kotarella1110

**Comment by kotarella1110** [comment]
> I think it makes sense not to update value during onBlur.

I think so too.

**Comment by bluebill1049** [comment]
let us know if this beta version `4.5.7-beta.1` resolve your issue. thanks

**Comment by IronSean** [comment]
Yes, that beta seems to resolve the issue. Thanks!

**Comment by bluebill1049** [comment]
merged
