### ISSUE TITLE
Rely on presence of window.HTMLDivElement instead of window.HTMLElement to infer browser environment

### ISSUE THREAD

**Issue by wolthers** [react-hook-form/react-hook-form#8551]
**Is your feature request related to a problem? Please describe.**
Custom elements extend HTMElement (`class MyCustomElement extends HTMLElement`), so when rendering them server-side one needs to shim the presence of HTMLElement. In such an environment react-hook-form will therefore return a false positive, because it infers a browser environment like this in [isWeb.ts](https://github.com/react-hook-form/react-hook-form/blob/111c2b651c876086e264279895425d0556598913/src/utils/isWeb.ts#L2):
```typescript
export default typeof window !== 'undefined' &&
  typeof window.HTMLElement !== 'undefined' &&
  typeof document !== 'undefined';
```

**Describe the solution you'd like**
Instead of relying on presence of window.HTMLElement, I suggest relying on the presence of window.HTMLDivElement, which you do not need to shim when rendering custom elements.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Zneider** [comment]
+1

**Comment by kluplau** [comment]
+1
