### ISSUE TITLE
issue: form submission process is not working on React Native production build

### ISSUE THREAD

**Issue by SalGnt-Dev** [react-hook-form/react-hook-form#8554]
### Version Number

7.32.2

### Codesandbox/Expo snack

https://snack.expo.dev/@salvatore.gentile.musixmatch/react-hook-form---issue-with-rules-prop-in-prod-build

### Steps to reproduce

1. Configure and use the React Hook Form library in a React Native project, using `Controller`.
2. Test the form submission process in debug mode.
3. The form submission works as expected.
4. Build the app and test the same form submission process in production mode.
5. The form submission is not working as expected.

### Expected behaviour

The form submission process fails on React Native production build. Everything works as expected on React Native in debug mode, using Metro, and in both debug mode and production build on web.

The form submission process should always work as expected.

The issue seems related with the `rules` prop. Everything works as expected when using an external schema-based form validation library, with `resolver`, as suggested [here](https://github.com/react-hook-form/react-hook-form/issues/7842#issuecomment-1072835710).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I am sure there are many react native apps currently running with hook form and I would like to resolve this mysterious problem in your application. however, there is very little I can do unless there is something that is reproducible for me.
