### ISSUE TITLE
issue: setFocus with shouldSelect breaks for inputs created with useController

### ISSUE THREAD

**Issue by elstgav** [react-hook-form/react-hook-form#8558]
### Version Number

7.32.2

### Codesandbox/Expo snack

https://codesandbox.io/s/upbeat-moon-h4xcrn?file=/src/App.tsx

### Steps to reproduce

1. Set up an input with `useController`, e.g. `'firstName'`
2. Call `setFocus('firstName', { shouldSelect: true })`

### Expected behaviour

The input should be focused and selected.

### Actual Behavior

A `TypeError` is thrown: `TypeError: s.select is not a function`

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is not an issue with this library, root cause is due to select ref is not provided.

**Comment by elstgav** [comment]
@bluebill1049 I’m not sure I follow—did you check the code sandbox that reproduces the error? If I set up the input incorrectly with `useController` please let me know. I’m not sure what you mean by “select ref is not provided”.

While investigating the issue I noted the following:

`setFocus` expects to be able to call `field.ref.select()`:
https://github.com/react-hook-form/react-hook-form/blob/eb79e4d01c718b7378471e018f904bb12feac8e6/src/logic/createFormControl.ts#L1204-L1208

…but `useController` sets `field.ref` (line 131) to a custom object that’s lacking a `select()` method:

https://github.com/react-hook-form/react-hook-form/blob/96e07fa6337926f5178d620a5a11902f9abf6b54/src/useController.ts#L126-L140

`register` on the other hand has a much more complicated ref callback for setting `field.ref`:

https://github.com/react-hook-form/react-hook-form/blob/96e07fa6337926f5178d620a5a11902f9abf6b54/src/logic/createFormControl.ts#L958-L1009

**Comment by bluebill1049** [comment]
we do not call `select` within the useControoer, just as the name suggested it's `focus` event, so it should be `focus`, if you have supplied the correct input/select reference then `focus` method will be called.

**Comment by bluebill1049** [comment]
nvm, just checked the CSB. this is a bug. will patch it.

**Comment by elstgav** [comment]
Thank you!
