### ISSUE TITLE
setValue isn't worked for useFieldArray

### ISSUE THREAD

**Issue by iamwelk** [react-hook-form/react-hook-form#856]
**Describe the bug**
When I use setValue to set value for props inited by useFieldArray, it's not worked

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-luwnw

**Comment by bluebill1049** [comment]
The usage is incorrect, setValue is made for individual inputs. if you want to clear Field Array use `remove`

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/#useFieldArray

**Comment by iamwelk** [comment]
So is there a wan to combine normal inputs and Field Array in one form?

**Comment by bluebill1049** [comment]
yes. you can. your setValue didn't work, because you are trying to set value for an input that doesn't exist.

there is no input named as `test`;

**Comment by iamwelk** [comment]
All right, thank you~

**Comment by lautin0** [comment]
@bluebill1049 

May I ask if I want to set value from async data to useFieldArray fields. How can I do that? 

From what you said:

> yes. you can. your setValue didn't work, because you are trying to set value for an input that doesn't exist.

> `setValue` is made for individual inputs

So I have tried to first append to the field array and then setValue for each item, but failed. 

Here is a simulation of loading data. I have used useEffect for demo. 

Codesandbox link
[](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-7xnt6)

**Expected:** Showing 4 groups of inputs according to the array
**Result:** Just 2

Could you please help? Thank you very much!

**Comment by jerrywebie** [comment]
thank you , Sir @bluebill1049
