### ISSUE TITLE
A default value for a Controller component isn't considered valid without manually touching the component via UI

### ISSUE THREAD

**Issue by jannekanerva** [react-hook-form/react-hook-form#857]
**Describe the bug**
When using Controller, the default value of the component used with Controller doesn't get recognized by formState.isValid.

Let's say there are two fields on the page: one simple text input using simple ref/register and a custom date picker wrapped with Controller - both are set required=true. If we give a default value to the date picker component via useForm:defaultValues, the value is shown correctly in the component but formState.isValid stays false if we don't touch the date picker manually from the UI.

The weird part is that if we e.g. console.log(formState.isValid) then the problem is fixed and the date picker value is being validated without extra touching.

**To Reproduce**

1. Give the date picker a default value via useForm
2. Add a simple text field with ref={register({required: true})}
3. Wrap a react-date-picker DatePicker in a react-hook-form Controller with rules={{required: true}}
4. Create a <button type="submit" disabled={!formState.dirty || !formState.isValid}>Save</button>
5. Write some text to the text input
6. See the button stay disabled
7. (BONUS) add a console.log(formState.isValid) to render method and the above said behaviour goes away.

**Codesandbox link**
https://codesandbox.io/s/intelligent-goodall-vjvl4

**Expected behavior**
I would expect the submit button to be enabled when I type text to the text field. If I console.log or somehow evaluate the formState.isValid property in the render method, the problem goes away.

**Desktop (please complete the following information):**
- OS: OSX (and CodeSandbox)
- Browser Chrome
- Version 79.0.3945.117

**Comment by bluebill1049** [comment]
hoist the isValid before render. see if that issue goes away.

**Comment by bluebill1049** [comment]
```
const { isValid }  = formState

...before render
```

**Comment by jannekanerva** [comment]
> ```
> const { isValid }  = formState
> 
> ...before render
> ```

Yes, this seems to do the trick! I don't quite understand why but it does. :)

My goal was to write a custom <SubmitButton /> component that takes the formState as a prop so that I could extract the isValid and dirty only inside the SubmitButton component, not in the form render function.

**Comment by bluebill1049** [comment]
> Yes, this seems to do the trick! I don't quite understand why but it does. :)

we use Proxy to detect if you are trying to read `formState` to avoid unnecessary re-render if you are not even reading them.

> My goal was to write a custom component that takes the formState as a prop so that I could extract the isValid and dirty only inside the SubmitButton component, not in the form render function.

you can still pass them as individual props

**Comment by jannekanerva** [comment]
> you can still pass them as individual props

Ok, will do that. I basically always need those props so it's an extra code line for every form but I can live with that. Thanks for your very fast help!

**Comment by risanto** [comment]
I'm still encountering the same issue even after hoisting.
```jsx
const { handleSubmit, control, formState } = useForm<FormValues>();
const { errors, isValid } = formState;
```
It's just like this right? I don't have to use isValid anywhere?

At the moment the value is shown correctly in the component but formState.isValid stays false if I don't change the input manually from the UI.
