### ISSUE TITLE
issue: Inconsistent formState between usecontroller field.value and useForm formState

### ISSUE THREAD

**Issue by akilansengottaiyan** [react-hook-form/react-hook-form#8574]
### Version Number

7.33.0

### Codesandbox/Expo snack

https://codesandbox.io/s/hook-form-query-6jfje0?file=/src/App.js

### Steps to reproduce

1. Open the [codesandbox](https://codesandbox.io/s/hook-form-query-6jfje0?file=/src/App.js) attached above
2. There are two input fields (one with register & another with useController)
3. Click on **Empty input values** button which will reset the fields to undefined & remounts.
4. The **Register input** will populate the `defaultValue` on `useForm` and in sync with `useForm formstate` after remount but in the case of **Controller input**, `field.value` from `useController` is in unsync with the `useForm formState` which is confusing. 
5. We could verify the above statement by clicking on **Submit** button which will validate the form and throws error only on **controlled input** though the input holds the value from `field.value`.

### Expected behaviour

`field.value` from `useController()` should be in sync with `formState` values. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
hook form `useFieldArray` is uncontrolled by default, if you are after a controlled field array, I suggest you check Formik as an alternative solution.
