### ISSUE TITLE
How to find out which submit button has been clicked onSubmit?

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [react-hook-form/react-hook-form#858]
Please consider asking the question at our spectrum channel.

https://spectrum.chat/react-hook-form

**Describe the question?**

Right now my team is discovering on how to find out which submit button has been clicked (when there are multiple submit buttons).

**To Reproduce**

F.e. if you have an invitation form, where you can either submit your party acception or your party declining (acceptButton has value="accept", declineButton has value="decline").

If you use the register method for both buttons, it sends both values (if the buttons have different names).

Is there any best practice, on how to find out which button has been clicked?

**Comment by bluebill1049** [comment]
why are you `register` the button?

**Comment by bluebill1049** [comment]
same question in spectrum. dicuss in spectrum

**Comment by alxvallejo** [comment]
@bluebill1049 That link is not helpful. Can you cite which thread?

**Comment by bluebill1049** [comment]
@alxvallejo you have the same question on which button is clicked?

`onClick={() => { handleSubmit()(); triggerYourAction() }}`
