### ISSUE TITLE
issue: Dirty fields not always updated from within field array

### ISSUE THREAD

**Issue by fkaempfer** [react-hook-form/react-hook-form#8581]
### Version Number

7.33.0

### Codesandbox/Expo snack

https://codesandbox.io/s/calc-forked-xve3hw?file=/src/App.tsx

### Steps to reproduce

1. Open the code sandbox
2. Click on the Inc button
3. Click on the Test values button

### Expected behaviour

The alert should show {cart: [{quantity:true}]} but it instead shows {}

Explanation:
On the first render only, the dirtyFields are not always updated when calling the update method of the field array. If you click on Inc and Test Values a second time, all works fine: The alert includes the cart entry.

Another workaround is to reference dirtyFields from with in the form, for example {JSON.stringify(form.formState.dirtyValues)}

### What browsers are you seeing the problem on?

FF,Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
![Screen Shot 2022-06-27 at 7 09 03 pm](https://user-images.githubusercontent.com/10513364/175903656-8fdf9533-293d-48b2-9be1-7febe3141e25.png)

you are missing `formState` subscription, please refer to the doc:

> formState is wrapped with a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to improve render performance and skip extra logic if specific state is not subscribed to. Therefore make sure you invoke or read it before a render in order to enable the state update.

https://react-hook-form.com/api/useform/formstate#rules

**Comment by fkaempfer** [comment]
Thanks! Adding  an empty `React.useEffect(() => {}, [form.formState.dirtyFields]); ` fixes the issue

**Comment by bluebill1049** [comment]
we may consider exposing this as props, so this is more clear and more declarative to users.

```tsx
useForm({
  subscribe: {
    dirty: true
  }
})
```
