### ISSUE TITLE
issue: FieldErrors Type Can't Handle Optional Properties

### ISSUE THREAD

**Issue by Chaoste** [react-hook-form/react-hook-form#8584]
### Version Number

7.33.0

Typescript: 4.7.4 (also tried 4.8.0-beta and 4.6.4)

### Codesandbox/Expo snack

https://www.typescriptlang.org/play?ts=4.7.4#code/PTAEDECcHsFtUgUwIYGMAuBaAFtaBrTAM2kngDcB2AOgGZbqAGUACiQBsUBnRAE1ABMAFiYA2agMYCBASgBQiAB4AHUulC9EqdsiSh0AT2WJQAWUSQA5ogA8AQQA0oAEIA+UAF5QAbzmh-oADaANKgAJYAdqD4iAbQRKB2oAA+0bHxLgC6APwAXKChSuiIEbxcaXEJSdkFoEUlZRUZzqA1gXYhmU7OnZl1isWl5YHQAEYAVlroTmOTGH015la2HcFdLp3u+at9qT1roNudh7X1Q00JLTX7ffkRiOQWANxyAL4vSqqQ6prauiaGYwQMKIdi8ABqyHYAFdEOUvAAlLSkXg2LjoSCRSxOZARAyuD4qNQaLQ6PSAkzgEFggCikBgkE8Pj8AVgcK4yGseVA6MxEUsL3eCiJ3xJf3JRkp1N4dIZXBsABV+oNGlTQRCobD4cD1ZCYXD3F5fAEgqFIhdQAqcvkFcczo1ZlNWmYLNYbGrafTSE4PTKvZB5ba1q4tjrPQzBS85HIQKAaYpkLBlJxLQBlUCoaCafTQUCjJDIfD6bBS9Wy0hcOQUswGVPFZR62FM40BNDoMLQCL5XlYt5VyU132NuHNln+dGIZRcbl2enIAw2Uy1+vD1x9uSZiLo0DYXG8TjlgNMlgWOX5X2H+VLoeag0yTzuFv+TdcaCcain0gn-1cagTqfZNQgSMDk1Bth2ESAWyXActY8ivNGsYKogSakLoBigAA7qQ+C6NA0KlBunbbrupQHj+ADCpBIBg7AYV435nmGfpyouBg3vqXCuPeHiPmOGbEW+iAfv6LCMRWf71uUyDlBeP5sXWk7DoEmTcYBwGgeBnZQeynKIPBiFgAAMtAqBQnRTgAJJ1I8US7o8OagLAyDKOE6hEGEAbqOguYEfgETQJhUTsGEMTFmElYvuopH7ogl4ACJhEQRAWCU6B0cen4Bue0qXmxHFatxD7MiaL5CSJDJiVlv7-tJ5R+QFQWgDJzF5UuikNreKlqUBIGAVpkHUNBsH6W8QA

### Steps to reproduce

1. Create a form type that contains an optional property which can be an array of objects.
2. Read out the error message for an element deeply hidden in the form type with optional chaining.
3. When trying to read out a specific error message within this array of objects, Typescript can't infer anymore that I'm dealing with a list.
4. For the TS Error, see linked TS playground with copied types from the recent version of the library.

### Expected behaviour

By using optional chaining, I want to get the error message for a deeply nested property without adding user-defined type guards (`as unknown as FieldErrors<...>`)

### Relevant log output

```shell
Element implicitly has an 'any' type because expression of type '0' can't be used to index type 'FieldError'.
  Property '0' does not exist on type 'FieldError'.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Chaoste** [comment]
The error also happens for non-array properties. So it's a more general issue with possibly undefined form properties.
See [this example](https://www.typescriptlang.org/play?ts=4.7.4#code/KYDwDg9gTgLgBAE2AYwDYEMrDjAnmbAWWCgHNgAeAQQBo4AhAPjgF44BvAKDh7gG0A0nACWAOzgBrYLggAzOFTgAfSdLkMAugH4AXHCGgYwUQgDOqmfMVb9cQ8bMX19ODb5VBGuvU8a7IIxNzPggAIwArFBg6MMjkGD8bYjJKDwEvBk9mPTS-FR90uBzPItt7IKd5FxsCvz1RYAA3EgBuTgBfNtBIWEQUDCwcfGwAMWFgVAQANXRUAFdgczYAJRRoBApTGCgxUjp0UVxGLvBoeCQ0TGw8AjgxiYQAUSgoaFYObl4AW0XTdHJdHAtjtRKQ2p1ON0zn1LoMbqNxpNnq8oKYKAAVfyBRz3SYzeaLd646azBamZhsLi8fhCMSVODo7R6dElcqOWJRVxwZLkCjE5HQOj8l7QNEs9KMbJ3RFPEVQcFtTiceHc3DE-Fk95U3iyCAQQHa6k8UKYPTA3afHgQ9pK5AQURbOAACwOCFQwAFqPeAAoSCjTHphf6KIQ1TKNYtGABKVjMQ1wO0OiDugB0fugvrlphTuv1KZNUC0KZ+pj+5CjHU4icdLpM7s9pgAwtAsPFULgfenUYGZQ2Q2GHhHyTGWHHLQn7aZk8A03LvZn-Tm9XB0OYg6KKOw4AWzdtdnB2tGiwWiyWy8AK+0gA).

```ts
type MyFieldValues = {
    foo?: {
        bar: string
    };
}

const handleErrors = (errors: FieldErrors<MyFieldValues>) => {
    console.error(errors.foo?.bar?.message)
}
```

Causes this error:
```bash
Property 'bar' does not exist on type 'FieldError'.
```

And the hotfix is again a user-defined type guard:
```ts
const handleErrorsCorrectly = (errors: FieldErrors<MyFieldValues>) => {
    console.error((errors.foo as FieldErrors<{ bar: string }>)?.bar?.message)
}
```

**Comment by impzero** [comment]
I think this was discussed in #8518

**Comment by Chaoste** [comment]
Hey @impzero , after reading the discussions it sounds to me like it's a different issue. Eventually, the root cause might be the same. But that's unlikely I guess. In my case, I'm not dealing with an `any` type but the new `Merge` construct from v7.33.0 (released after the linked discussion). This `Merge` somehow completely ignores optional properties, as they are not defined at all.

So in my example above, `errors.foo?` should have the type `FieldError | FieldErrors<{ bar: string }> | undefined` but instead it's only `FieldError | undefined`.

**Comment by bluebill1049** [comment]
We are working on it and trying to fix this issue.

**Comment by zandowc** [comment]
@bluebill1049 I've noticed another facet of the same issue as described above https://github.com/react-hook-form/react-hook-form/issues/8584#issuecomment-1167261403

When the nested property is nullable we still get the same error. See [this repro](https://www.typescriptlang.org/play?ts=4.7.4#code/KYDwDg9gTgLgBAE2AYwDYEMrDjAnmbAWWCgHNgAeAQQBo4AhAPjgF44BvAKDh7gG0A0nACWAOzgBrYLggAzOFTgAfSdLkMAugH4AXHCGgYwUQgDOqmfMVb9cQ8bMX19ODb5VBGuvU8a7IIxNzPggAIwArFBg6MMjkGD8bYjJKDwEvBk9mPTS-FR90uBzPItt7IKd5FxsCvz1RYAA3EgBuTgBfNtBIWEQUDCwcfGwAMWFgVAQANXRUAFdgczYAJRRoBApTGCgxUjp0UVxGLvBoeCQ0TGw8AjgxiYQAUSgoaFYObl4AW0XTdHJdHAtjtRKQ2p1OJxumc+pdBjdsAARYDAMCrACOc2EWA2ABVmGwuDxBCJxFJLHBcRoALSA5GojFYnEUXFZcFtKGnXoXAbXYZ3caTZ6vKCmACSXzAqBZ-kCjnukxm80W7wV01mC1MBI+xKEYkqlO0elZhXKjliUU+PCSJHIFDVwugdAdL2g4sl0pNGkYjCtpRdIvZkOhvQRAoejtFMrN5jVSs1qsF6uVWsTEddoolUoon3paOAmOxwDxvuOkM4YcIuDjGpVhL9sggEEBRN4bdCmD0wN2fvayjgojmqFQ4MhyAgoi2cAAFgcEKhgJGlnAABQkEWmPQBt0UKs1lOMACUrGYrZ448nEAXADp19A1xnTNfG83rx2oFprz9TH9yIeOpwF5TrOJgLkuADC0BYPEqC4O8D4bluSZLru1ZJvGixHieOq8EBV7ALeGYrghbrPk2cDoLGyGPhQ7BwO+XbbLscDtEen7vp+36-sA-7tEAA)

```typescript
type MyFieldValues = {
    foo?: {
        bar: string
    } | null;
}

const handleErrors = (errors: FieldErrors<MyFieldValues>) => {
    console.error(errors.foo?.bar?.message)
}
// Property 'bar' does not exist on type 'FieldError'.
```
