### ISSUE TITLE
issue: Typescript error on optional nested fields after upgrading to 7.33.0 

### ISSUE THREAD

**Issue by anark** [react-hook-form/react-hook-form#8589]
### Version Number

7.33.0

### Codesandbox/Expo snack

https://codesandbox.io/s/serverless-night-lm12sl?file=/src/App.tsx

### Steps to reproduce

1. Go to 'https://codesandbox.io/s/serverless-night-lm12sl?file=/src/App.tsx'
2. Investigate typescript error on line 21
3. Revert react hook form version to 7.32.2
4. No more error

### Expected behaviour

There is no typescript error when using the latest version on a nested type that the parent is optional.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
same issue: https://github.com/react-hook-form/react-hook-form/issues/8589

**Comment by anark** [comment]
Duplicate is https://github.com/react-hook-form/react-hook-form/issues/8584

**Comment by bluebill1049** [comment]
sorry tag the wrong issue 🙏 still looking into a fix.
