### ISSUE TITLE
Typescript - Unable to import IE11 supporting code

### ISSUE THREAD

**Issue by stern-shawn** [react-hook-form/react-hook-form#859]
**Describe the bug**
Trying to import the ie11 code as described in the browser support FAQ

```
import { useForm } from 'react-hook-form/dist/react-hook-form.ie11'
```

Results in `Could not find a declaration file for module 'react-hook-form/dist/react-hook-form.ie11'.` error using latest version v.4.5.5 of `react-hook-form`. I see the file if I navigate to node_modules/react-hook-form/dist, but TS doesn't seem to acknowledge that it's there and casts `useForm` to `any`, which breaks my heart.

**To Reproduce**
1. Install react-hook-form@4.5.5
2. Try to `import { useForm } from 'react-hook-form/dist/react-hook-form.ie11'`
3. 😢 (also, because IE11)

**Codesandbox link**
My work blocks codesanbox domain 😢 

**Expected behavior**
Able to import without any TS errors 😄 

**Screenshots**
<img width="1792" alt="Screen Shot 2020-01-17 at 10 31 40 AM" src="https://user-images.githubusercontent.com/10067791/72640552-ef9af980-391c-11ea-880a-563d68d6d55e.png">

**Additional context**
F*** IE 💢

**Comment by stern-shawn** [comment]
I'm able to get around this using the approach in this comment (https://github.com/react-hook-form/react-hook-form/issues/56#issuecomment-538160265), updated for the new `useForm` change where it isn't a default export anymore:

```
declare module "react-hook-form/dist/react-hook-form.ie11" {
  export * from "react-hook-form";
}
```

**Comment by bluebill1049** [comment]
aha cool thanks for sharing the answer too @stern-shawn

**Comment by stern-shawn** [comment]
Could this be included in the repo types so the workaround isn't necessary? I'm happy to do the change myself I just don't have experience adjusting types for a library :)

**Comment by bluebill1049** [comment]
> Could this be included in the repo types so the workaround isn't necessary? I'm happy to do the change myself I just don't have experience adjusting types for a library :)
> 
> Maybe I can noodle around with this over the weekend 🤔

would you like to send a PR in our doc to include this information?

**Comment by bluebill1049** [comment]
include under this section: https://react-hook-form.com/faqs#BrowserSupport

**Comment by bluebill1049** [comment]
eventually we going to deprecate this IE11 version in the near future.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Please don't deprecate IE 11, there are still many companies left where people are using IE 11 due to fixed system configurations.

**Comment by bluebill1049** [comment]
This will be planned and announced before we make a decision. It won't be an overnight or weekend job. It will involve with the community voice.

**Comment by mattjis** [comment]
I can't even build without using the `import { useForm } from 'react-hook-form/dist/index.ie11'` version. I think it has something to do with `uglifyjs-webpack-plugin`. It is crucial!

**Comment by PaoloDiBello** [comment]
> I can't even build without using the `import { useForm } from 'react-hook-form/dist/index.ie11'` version. I think it has something to do with `uglifyjs-webpack-plugin`. This version is crucial!

Use terser-webpack-plugin
