### ISSUE TITLE
issue: Destructuring methods on the provider are causing unnecessary re-renders

### ISSUE THREAD

**Issue by alexandrzavalii** [react-hook-form/react-hook-form#8596]
### Version Number

7.33.0

### Codesandbox/Expo snack

https://codesandbox.io/s/resolver-context-forked-1q82fl?file=/src/App.tsx

### Steps to reproduce

1. Go to ['...'](https://codesandbox.io/s/resolver-context-forked-1q82fl?file=/src/App.tsx)
2. Inspect AppWithProvider and AppWithCustomProvider
3. Look that second field is re-rendering unnecessary 

### Expected behaviour

second field should not be rerendering.
We should not be spreading methods, because it creates a new instance of the object, and causes the rerenders

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I am not sure or clear on the issue that we need to address here, react hook form provider is basically built on top of reach `useContext` API.

**Comment by alexandrzavalii** [comment]
it is a huge concern :) the library should not be destructuring context value every single render

**Comment by alexandrzavalii** [comment]
@bluebill1049 not really, because you are destructuring every render and recreating the array

```
  const props = { children:'c', a: 'a'};
  
  const { children, ...data } = props;
  const { children: children1, ...data1 } = props;
  
  data1 !== data

  ```

**Comment by Moshyfawn** [comment]
I guess, @alexandrzavalii is concerned about doing
```js
const { children, ...data } = props;
```
[in the source code of `useFormContext`](https://github.com/react-hook-form/react-hook-form/blob/8e89fc140157822a06b1833f589765f4b947f950/src/useFormContext.tsx#L75)

**Comment by bluebill1049** [comment]
oh I see thanks @Moshyfawn

**Comment by alexandrzavalii** [comment]
exactly, I passed like you suggested in this codesandbox, it doesnt make a difference

https://codesandbox.io/s/resolver-context-forked-1q82fl?file=/src/AppWithLibraryProvider.tsx

**Comment by alexandrzavalii** [comment]
so I am forced to create a custom provider which will memoize props
```
import { FormProvider as FormProviderFromReactHookForm, UseFormReturn } from 'react-hook-form';

type FormProviderMemoizedProps<T extends Record<string, any>> = {
  methods: UseFormReturn<T>;
  Component: ComponentType<T>;
} & T;

const FormProvider = <T extends Record<string, any>>({
  methods,
  Component,
  ...props
}: FormProviderMemoizedProps<T>) => (
  <FormProviderFromReactHookForm {...methods}>
    <Component {...(props as unknown as T)} />
  </FormProviderFromReactHookForm>
);


export const FormProviderMemoized = memo(FormProvider) as typeof FormProvider;
```

And the usage of it

```
 <FormProviderMemoized
    methods={methods}
    Component={MyForm}
    propForMyForm={propForMyForm}
    />
```
