### ISSUE TITLE
issue: Merge type error with nested values after the latest update

### ISSUE THREAD

**Issue by asalahjawava** [react-hook-form/react-hook-form#8597]
### Version Number

7.33

### Codesandbox/Expo snack

https://codesandbox.io/s/amazing-saha-izugnp?file=/src/App.tsx

### Steps to reproduce

I have an form values with nested values like this:
`attachment: {
    data: string;
    type: string;
}`

later in the errors object, I have a type error in: `errors?.attachment?.type?.message`
Here is a screenshot of it
<img width="830" alt="Screen Shot 2022-06-28 at 3 37 11 PM" src="https://user-images.githubusercontent.com/89516044/176180200-027bf071-2aea-4ff4-a74e-3e6434b560d8.png">

I think this is because of the merge. Now attachment has a type FieldError which has it is own "type" property and that interferes with the "type" property in my form values

### Expected behaviour

"attachment" should not have type FieldError but maybe something like this:
`attachment: {
    data: FieldError;
    type: FieldError;
}`

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we are looking into it: https://github.com/react-hook-form/react-hook-form/issues/8584

**Comment by bluebill1049** [comment]
`type` and `message` are reserved words for error objects type checking please avoid using it.

**Comment by asalahjawava** [comment]
> `type` and `message` are reserved words for error objects type checking please avoid using it.

Yes, but what I mean is that `type` and `message` should  not be in the parent object but in the nest values instead and this is how the real error object look, it is just typescript error.

**Comment by bluebill1049** [comment]
They will always now, this is the only way to support union, optional and nested field values.
