### ISSUE TITLE
`annotation` api

### ISSUE THREAD

**Issue by nyarthan** [react-hook-form/react-hook-form#8611]
**Is your feature request related to a problem? Please describe.**
Maybe I'm missing something but I think there should be a way to add annotations to fields, similar to errors but without invalidating the input field. This could be useful for e.g. password inputs that annotate the strength of the password. Weak passwords could be treated as errors but *ok* passwords could show a hint but not invalidate the field. I don't think this is possible with any builtins right know - but correct me if I'm wrong.

**Describe the solution you'd like**
The API I have in mind for this could look something like this:
```typescript
interface FormValues {
  password: string;
}

const { setAnnotation, formState } = useForm<FormValues>();

// set his annotation e.g. on backend response
React.useEffect(() => {
// ...
setAnnotation('password', { type: 'hint', message: 'password could be stronger' });
}, []);

// then access it via `formState`
const passwordAnnotation = formState.annotations.password?.message;
```

**Describe alternatives you've considered**
The API looks excaclty like the one for errors, so maybe it would be better to integrate it with them and add like a `severity` to not invalidate fields with low severity errors.

**Comment by bluebill1049** [comment]
I would suggest just hosting a `useState` for this and is probably the easiest way to solve the problem, while it's nice to have that API a part of hook form, it surely expands the code base and complexity within, it's best to avoid IMO. I am going to ping this to project board and most likely this will not be implemented as part of the API.
