### ISSUE TITLE
issue: Generic useForm returned control not assignable to type Control<FieldValues, object>

### ISSUE THREAD

**Issue by barneaoren** [react-hook-form/react-hook-form#8618]
### Version Number

7.33.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v6-controller-ts-jwyzw?file=/src/index.tsx

### Steps to reproduce

No steps to reproduce, just the typing issue
```ts
...
const { control } = useForm<FormValues>({ defaultValues });
...
<MuiAutoComplete control={control} />
```

### Expected behaviour

Type 'Control<FormValues, object>' should be assignable to type 'Control<FieldValues, object>'.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
The `Control` type should take in the `FormValues` type as it's generic [in the `MuiAutoComplete` component](https://codesandbox.io/s/react-hook-form-v6-controller-ts-jwyzw?file=%2Fsrc%2FMuiAutoComplete.tsx%3A295-370)
```ts
import type { FieldValues } from "react-hook-form"

function CountrySelect<TFieldValues extends FieldValues>({ control }: { Control<TFieldValues> }) {}
```

**Comment by Moshyfawn** [comment]
In case of [the codesandbox, you've linked](https://codesandbox.io/s/react-hook-form-v6-controller-ts-jwyzw?file=/src/index.tsx), the generic type should be the actual `FormValue`, as the component is not reusable and the `Controller` name is set to `country`
```ts
type FormValues = {}

function CountrySelect ({ control }: { Control<FormValues> }) {}
```

**Comment by Moshyfawn** [comment]
@bluebill1049 I've cleaned up [the codesandbox mentioned in this issue](https://codesandbox.io/s/react-hook-form-v6-controller-ts-jwyzw) from.. well, issues lol

**Comment by bluebill1049** [comment]
Thanks @Moshyfawn 🌟🌟🌟

**Comment by uzikilon** [comment]
We ran into this issue as well.
Technically it is a breaking change we did not expect in a minor version release.

**Comment by IonVillarreal** [comment]
Hi, is it possible to attach an example of a reusable component with the change of Control to generic type ?

With this version my implementation no longer works 😓

**Comment by Moshyfawn** [comment]
> Hi, is it possible to attach an example of a reusable component with the change of Control to generic type ?
> 
> With this version my implementation no longer works 😓

Here's [a basic example codesandbox](https://codesandbox.io/s/kind-wildflower-1kzege?file=%2Fsrc%2FApp.tsx)
