### ISSUE TITLE
issue: API Breakage on FieldErrors

### ISSUE THREAD

**Issue by craigmcc** [react-hook-form/react-hook-form#8619]
### Version Number

7.33.1

### Codesandbox/Expo snack

Compile error, so no code sandbox is available.

### Steps to reproduce

I am building out a set of Typescript React components (based on react-hook-form and react-bootstrap).  The source code for this library is at:

https://github.com/craigmcc/shared-react

With react-hook-form 7.30.0, everything was fine.
With react-hook-form 7.33.1, I get compile errors trying to build the library (see the "Relevant Log Output" section below).

It looks like changes to the FieldErrors definition is what is triggering this.

TO REPRODUCE:
* Download the GItHub module mentioned above.
* Run "npm install" to install the listed dependencies.
* Run "npm install react-hook-form@7.33.1" to get the version that causes the problem.
* Run "npm build" and see the compile errors (shown in the "Relevant log output" section below).

### Expected behaviour

No compile errors.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
COMPILE OUTPUT:
==============

MacBook-Pro:shared-react craigmcc$ npm run build

> @craigmcc/shared-react@1.2.1 build
> tsc -p .

src/SelectField/SelectField.tsx:71:17 - error TS2322: Type 'Merge<FieldError, FieldErrorsImpl<DeepRequired<any>>> | undefined' is not assignable to type 'ReactNode'.
  Type 'Merge<FieldError, FieldErrorsImpl<DeepRequired<any>>>' is not assignable to type 'ReactNode'.
    Type 'Merge<FieldError, FieldErrorsImpl<DeepRequired<any>>>' is missing the following properties from type 'ReactPortal': key, children, type, props

71                 {props.errors[props.name]?.message}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@types/react/index.d.ts:1374:9
    1374         children?: ReactNode | undefined;
                 ~~~~~~~~
    The expected type comes from property 'children' which is declared here on type 'IntrinsicAttributes & Omit<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<...>> & { ...; }, BsPrefixProps<...> & FeedbackProps> & BsPrefixProps<...> & FeedbackProps & { ...; }'

src/TextField/TextField.tsx:66:17 - error TS2322: Type 'Merge<FieldError, FieldErrorsImpl<DeepRequired<any>>> | undefined' is not assignable to type 'ReactNode'.

66                 {props.errors[props.name]?.message}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@types/react/index.d.ts:1374:9
    1374         children?: ReactNode | undefined;
                 ~~~~~~~~
    The expected type comes from property 'children' which is declared here on type 'IntrinsicAttributes & Omit<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<...>> & { ...; }, BsPrefixProps<...> & FeedbackProps> & BsPrefixProps<...> & FeedbackProps & { ...; }'


Found 2 errors in 2 files.

Errors  Files
     1  src/SelectField/SelectField.tsx:71
     1  src/TextField/TextField.tsx:66
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please follow the issue template by providing a codesandbox to reproduce this issue then will reopen and look into it.

**Comment by craigmcc** [comment]
Codesandbox link:  https://codesandbox.io/s/goofy-fast-vdssvf

Although the app runs in the sandbox (it fails for me locally), if you open src/TextField.tsx and src/MyForm.tsx you will see the highlighted errors.

Change the react-hook-form dependency to 7.32 and it makes those errors go away.

**Comment by shamilovtim** [comment]
Same problem. The typedef has some sort of breaking change where it no longer passes a string.

**Comment by quadrifolia** [comment]
Same problem. Something is off with the typedef…

`TS2367: This condition will always return 'false' since the types 'Merge<FieldError, FieldErrorsImpl<DeepRequired<any>>> | undefined' and 'string' have no overlap.
    199 |                                         maxLength: 110,
    200 |                                     }}
  > 201 |                                     error={field?.value?.length === 0 || errorsMeta?.ogTitle?.type === 'required'}
        |                                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    202 |                                 />`

**Comment by bluebill1049** [comment]
> Same problem. Something is off with the typedef… error occurs on: errors?.field?.type === 'required'
> 
> `TS2367: This condition will always return 'false' since the types 'Merge<FieldError, FieldErrorsImpl<DeepRequired>> | undefined' and 'string' have no overlap.

can you provide a codesandbox to reproduce the issue or supply a test case to demonstrate the issue?

![Screen Shot 2022-07-04 at 6 02 15 pm](https://user-images.githubusercontent.com/10513364/177109895-d3c14a67-a934-4785-9a71-66442a891e04.png)

**Comment by quadrifolia** [comment]
happens only with useFormContext, not with useForm –> [https://codesandbox.io/s/sad-allen-tgj0ho?file=/src/FormField.tsx](sandbox)

**Comment by bluebill1049** [comment]
<img width="613" alt="image" src="https://user-images.githubusercontent.com/10513364/177224016-8e646992-47c3-432f-9f6e-cac3905e871d.png">

It's working because there is no type check.

**Comment by RigottiG** [comment]
I'm facing the same error

**Comment by mjnaderi** [comment]
Same issue. I'm going to using `7.32.2`.

**Comment by niemyjski** [comment]
Same
