### ISSUE TITLE
react-hook-form not validated default value issue: 

### ISSUE THREAD

**Issue by arun2git** [react-hook-form/react-hook-form#8637]
### Version Number

v7

### Codesandbox/Expo snack

local

### Steps to reproduce

  <textarea
                      className="form-control"
                      placeholder="Description"
                      defaultValue={provideData.category_description}
                      {...register("category_description", {
                        required: true,
                        maxLength: 100,
                      })}
                    ></textarea>
                    {errors.category_description && (
                      <p className="text-error">Please check the description</p>
                    )}

### Expected behaviour

defaultValue is set on value but form throws a validation error.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Please, provide a **minimal** codesandbox **reproduction** of your issue. We can't debug "local" ;)

**Comment by Blakeinstein** [comment]
Facing a similar issue, react-hook-form doesn't seem to respect default values added to form fields, and require that the state be set with the default value as well.

MRE: https://codesandbox.io/s/react-hook-form-js-forked-ns1bvr

Clicking on submit focusses the form field, then on focus the setValue handler sets the appropriate default value.

The end experience looks like the value exists on the field (albeit only visually) and can by slightly confusing.

**Comment by Moshyfawn** [comment]
> Facing a similar issue, react-hook-form doesn't seem to respect default values added to form fields, and require that the state be set with the default value as well.

Your codesandbox looks fine to me. `textarea` doesn't have any `defaultValue`, hence, it's empty
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/16290753/181000975-826d12ce-dff5-46f0-82eb-06495c66e358.png">

Please, update your codesandbox to reflect the issue you're having

**Comment by Blakeinstein** [comment]
> Your codesandbox looks fine to me. `textarea` doesn't have any `defaultValue`, hence, it's empty 
> 
> Please, update your codesandbox to reflect the issue you're having

Apologies, I didn't clarify as you can see, `firstName` has a default value. And is marked required. If you never click on that field and click submit, the firstName input should be highlighted as a non-filled form

**Comment by Moshyfawn** [comment]
I'm not sure I completely understand your use-case, but I have a couple of thoughts:
- The `required` validation prop is the same as HTML5 `required` attribute: it checks whether or not the input has **a non-empty** value. So, your example works as intended.
- If you want to make sure the user changes the input value, even if it has a non-empty `defaultValue`, your should
  - **either** check if the input is dirty
  - **or** put the `defaultValue` against current input value validation in place

**Comment by Blakeinstein** [comment]
> I'm not sure I completely understand your use-case, but I have a couple of thoughts:
> 
> * The `required` validation prop is the same as HTML5 `required` attribute: it checks whether or not the input has **a non-empty** value. So, your example works as intended.
> * If you want to make sure the user changes the input value, even if it has a non-empty `defaultValue`, your should
>   
>   * **either** check if the input is dirty
>   * **or** put the `defaultValue` against current input value validation in place

The error is raised in the native error validation, the first submit intent will be stopped because the field is effectively empty.
The defaultValue is propogated to the value (the formstate) once the field is focused once by the user.

The resolution I reached was to add the defaultValue to my register options (the defaultValue mapping here is unnecessary)
```jsx
<input ...{register('firstName', { required: true, value: defaultValue })} defaultValue={defaultValue} />
```
