### ISSUE TITLE
Validation not working as expected - no multiple validations/errors

### ISSUE THREAD

**Issue by 72gm** [react-hook-form/react-hook-form#8642]
### Version Number

V7

### Codesandbox/Expo snack

https://codesandbox.io/s/agitated-feistel-xhv0uz?file=/src/App.tsx

### Steps to reproduce

on Sandbox you will see that there is only one error at a time if you are missing both an uppercase letter and a number

### Expected behaviour

I had expected there to be the option to show multiple errors at a time but it only ever checks the validation consecutively, 1 at a time.. and errors.password?.message isn't an array so I wouldn't be able to output this

I would have hoped all validation to be run and reported every time so I can show what has been met and what hasn't? e.g.

- .Your password should contain an upper case letter
- .Your password should contain a number

Is there a way round this? 

Thanks

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
criteriaMode: "firstError",

criteriaModefirstError \| all | When set to firstError (default), only the first error from each field will be gathered.When set to all, all errors from each field will be gathered.


![Screen Shot 2022-07-06 at 9 15 33 pm](https://user-images.githubusercontent.com/10513364/177538091-5bf300ea-fcfc-407f-a9b1-51aaee05efae.png)

**Comment by 72gm** [comment]
Hi @bluebill1049 thanks for the quick answer.

Exactly what I'm looking for... 1 problem is that when using validate then these 'types' are only available at run time (unlike the out the box ones like required etc)

 console.log(errors?.newPassword?.types)
![image](https://user-images.githubusercontent.com/12847881/177549373-e831ba97-2a6e-4fcf-8c0e-1f2f0e4da778.png)

So I am unable to access the validate 'types' at design time as typescript thinks they don't exist.. for example 
![image](https://user-images.githubusercontent.com/12847881/177550204-be978280-7b81-4fab-b32e-f6bed59571f5.png)

What's the best way around this? 

Thanks

**Comment by bluebill1049** [comment]
can you double-check with the latest build?

**Comment by 72gm** [comment]
I'm using the latest release 7.33.1 or do you mean something else?

**Comment by Moshyfawn** [comment]
You won't get an auto-complete for your custom error field as the type of the `MultipleFieldErrors` is
```ts
type MultipleFieldErrors = {
    [K in keyof RegisterOptions]?: ValidateResult;
} & {
    [key: string]: ValidateResult;
};
```
Notice the `& { [key: string]: ValidateResult }` part.

So, you won't get a TS error for a non-existent field once you write out your full error path like `errors.password?.types?.upper`, but the `key` of your custom error field is a `string`, hence no auto-complete options

**Comment by bluebill1049** [comment]
> Important: Typescript ^4.3 above is the recommended version to work with react hook form.

https://react-hook-form.com/ts

**Comment by 72gm** [comment]
Hi @bluebill1049. Yes, I am using 4.6.2
