### ISSUE TITLE
issue: Controlled inputs with useFieldArray not receiving undefined values

### ISSUE THREAD

**Issue by guilhermedalleprane** [react-hook-form/react-hook-form#8643]
### Version Number

7.33.1

### Codesandbox/Expo snack

https://codesandbox.io/s/w1p4g1

### Steps to reproduce

1. Open Codesandbox
2. Click "Log Values" and check console, all values are setted correctly.
3. Click "Clear" and click "Log Values" again. Compare console output to screen inputs.

### Expected behaviour

I need to be able to clear a controlled field inside a `useFieldArray`, just as is possible for other controlled fields. If we use complex data structure with `useFieldArray`, the field cannot be `""`, so we need to set the value to undefined to clear.

When I use `<Controller/>` together with a `useFieldArray`, and I try to set the value of one of the items to `undefined`, the value is not passed to the input. The issue only happens when using controlled inputs together with `useFieldArray`, by my tests.

Controlled inputs out of `useFieldArray` works correctly, even if the input name is for example `item.0`.

Using uncontrolled inputs with `useFieldArray`, also works as expected. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> You need to either set defaultValue at the field-level or useForm's defaultValues. undefined is not a valid value.

please refer to the doc https://react-hook-form.com/api/usecontroller/controller
