### ISSUE TITLE
Several mods of validation for the same form

### ISSUE THREAD

**Issue by s5unanow** [react-hook-form/react-hook-form#8649]
**Is your feature request related to a problem? Please describe.**
From requirements perspective I need to have two fields to be validated using `onChange` approach and the other one is `onBlur`.

**Describe the solution you'd like**
Give possibility to override default form Mode.
For example 
```ts
type FormType = {
  firstName: string;
  secondName: string;
  age: number;
}

const form = useForm<FormType>({
  mode: 'onChange',
  fieldOptions: { firstName: { mode: 'onBlur' } },
});
```

**Describe alternatives you've considered**
As alternative I tried to use `onBlur` prop, checking manually against desired requirement (in my case it's a regexp). And then manually setting error. But it feels a bit cumbersome, because now I have validation in several places.

**Comment by bluebill1049** [comment]
hey @s5unanow have you considered using `trigger` instead?

**Comment by s5unanow** [comment]
Hey @bluebill1049, thanks for your reply!
That was my first take. But in this case should I change form mode to `onBlur` and add `trigger` api to the `onChange` callback for all inputs that should preserve `onChange` validation behaviour?
Because if default form validation will stay `onChange` it will affect my desired only `onBlur` field and it will be validated `onChange` anyway.

**Comment by bluebill1049** [comment]
I would keep mode `onChange` and only change those individual input to fire validation with `trigger` API. In your example, that would be `firstName`

```tsx
// uncontrolled:
const { onChnage, onBlur, name, ref } = register('firstName')
<input onChange={(e) => setValue(e.target.value)}  onBlur={onBlur} ref={ref} nam={name} />

// controlled:
const { onChnage, onBlur, name, ref, value } = useController()
<input onChange={(e) => setValue(e.target.value)}  onBlur={onBlur} ref={ref} nam={name} value={value} />
```

I haven't test the above, but in theory that's the way to go.

**Comment by s5unanow** [comment]
Hey @bluebill1049 , thanks for your explanation.
But to be honest, I am not sure if I understood the idea. :D 
It seem's like I missing some crucial part of the library.
What I understand, like in example you've proposed `onChange` event will fire on the `desired-only-on-blur-field` in any way. I just don't see how we are preventing `onChange` to be happening.

I might extend my current example.
So, I have controlled input

```ts
const FormInput = ({
  name,
  rules,
  ...props
}) => {
  const { field, fieldState } = useController({
    name,
    rules,
  });

  return (
    <FormInputComponent
      onChangeText={field.onChange}
      onBlur={field.onBlur}
      value={field.value}
      errorMessage={fieldState.error?.message}
      {...props}
    />
  );
};
```
 And then I use it like that

```ts
type FormType = {
  firstName: string;
  secondName: string;
  age: number;
}

const SomeCombinedForm = () => {
  const form = useForm<FormType>({
    mode: 'onChange',
    defaultValues: {
      firstName: '',
      secondName: '',
      age: 0,
    }
  });

  return (<FormProvider {...form}>
    <FormInput
      name={Fields.firstName}
      rules={validationRules.firstName}
    />
    <FormInput
      name={Fields.secondName}
      rules={validationRules.secondName}
    />
    <FormInput
      name={Fields.age}
      rules={validationRules.age}
    />
  </FormProvider>
}
```

So what essentially I did to achieve desired is
```ts
  const validateFirstName = () => {
    const isValid = form.getValues('firstName').test(regexp);
    if (isValid) {
      return;
    }
    form.setError('firstName', {
      type: 'manual',
      message: incorrectFirstNameMessage,
    });
  };
....
    <FormInput
      name={Fields.firstName}
      rules={validationRules.firstName}
      onBlur={validateFirstName}
    />
```

**Comment by bluebill1049** [comment]
I would suggest always associating validation with the input or the schema, setError only shows an error not actually have a rule against your input. 

```tsx
// controlled:
useForm({ mode: 'onChange' })
const { onChnage, onBlur, name, ref, value } = useController({
  rules: { required: true }
})
<input 
  // this will only update the input value not trigger validation, using setValue because it will not trigger validation by default
  onChange={(e) => setValue(e.target.value)}    
  onBlur={() =>{ 
    onBlur(); 
    trigger(name)} // this will trigger the validation 
  }
  ref={ref} 
  nam={name} value={value} 
/>
```

hook form is quite flexible in terms of validation, personally, I wouldn't want to expand the API more at this point if the above works for you.

**Comment by bluebill1049** [comment]
Let me know if there is any more question, I may convert this into a GitHub discussion question.

**Comment by s5unanow** [comment]
Hey @bluebill1049 , sorry for the late reply.

Thanks for sharing thoughts on how to solve the problem I've mentioned.
I like the idea you've proposed on not passing `onChange`. 
But in my case it will complicate api, so I probably need to have extra boolean which states wether my `FormInput` will use only `onBlur` validation. 
And at the same time as I understand I need to have locally stored input value somehow. I mean this part`(e) => setValue(e.target.value)`. 
I am assuming form might receive value through `ref`, but I do not use `ref` in my component.
Maybe I've picked up incorrect approach from the beginning. But I decided agains ref because internally I have such structure as `<Wrapper><Wrapper><Wrapper><TextInput /></Wrapper></Wrapper></Wrapper>`. So passing ref to the TextInput is kinda hard work in this case.

**Comment by s5unanow** [comment]
Nevertheless I totally understand your desire to keep api as simple as possible. So I am ok with current solution and enjoying using library ❤️. Just thought it would be not that hard to add functionality I've suggested.

I guess we might close now.

**Comment by bluebill1049** [comment]
thanks for understanding 🙏  @s5unanow I will close the issue until more users report for such API to be reconsidered.
