### ISSUE TITLE
use useFieldArray API like（append remove etc）effect other controller field

### ISSUE THREAD

**Issue by yaeSakuras** [react-hook-form/react-hook-form#8664]
### Version Number

7.33.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-he5n7m?file=/src/index.js:824-830

### Steps to reproduce

1. Click useFieldArray API like（append remove etc）
2. other controller field update

### Expected behaviour

other controller field not update. Guaranteed performance

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yaeSakuras** [comment]
This is very important and affects performance

**Comment by bluebill1049** [comment]
This expected behavior won't be fixed for now.

**Comment by yaeSakuras** [comment]
> This expected behavior won't be fixed for now.

It will cause the form performance to degrade

**Comment by Upinwv** [comment]
I'll
