### ISSUE TITLE
issue: required flag not invalidating NaN values

### ISSUE THREAD

**Issue by th3fallen** [react-hook-form/react-hook-form#8665]
### Version Number

7.32.2

### Codesandbox/Expo snack

https://codesandbox.io/s/lucid-thunder-gmyco0

### Steps to reproduce

1. have an input with a setValueAs of `parseFloat`
2. enter a value, then clear the value and tab
3. observe input is not set as invalid

### Expected behaviour

Required validator should also check against NaN values

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by th3fallen** [comment]
in the mean time as a work around I've added this... `                    setValueAs={ (value: string) => parseFloat(value) || false }`

**Comment by bluebill1049** [comment]
isNaN is not considered as empty value: https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/validateField.ts#L88

**Comment by th3fallen** [comment]
i would argue if my input has a setValueAsNumber or parseFloat etc that NaN absolutely should be considered an empty value.
