### ISSUE TITLE
issue: Unnecessary escaping of characters in a field value.

### ISSUE THREAD

**Issue by BEGEMOT9I** [react-hook-form/react-hook-form#8667]
### Version Number

last

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-basic-6mlii

### Steps to reproduce

1. Type any value in any field with a backward slash (`\`)
2. Press `submit`
3. Look at the duplicated slash (but in the field we have the correct value)

### Expected behaviour

The slash in value must not be escaped.

Question about this issue: https://github.com/react-hook-form/react-hook-form/discussions/8468

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
remove JSON.stringfy and see the log again.

**Comment by Upinwv** [comment]
Closer

--
