### ISSUE TITLE
issue: Controller with shouldUnregister=true is loosing its value in StrictMode

### ISSUE THREAD

**Issue by berdyshev** [react-hook-form/react-hook-form#8669]
### Version Number

7.33.1

### Codesandbox/Expo snack

https://codesandbox.io/s/loving-bush-dg6j4t?file=/src/index.js

### Steps to reproduce

1. App should be wrapped with StrictMode 
2. First field (checkbox in the example) is rendered within Controller with `shouldUnregister = true` and has default value as checked. 
3. Second field (text input) is rendered only when first has TRUE value with `shouldUnregister = true`
4. Provide `defaultValues` for the form: checkbox has `true` value, input has some string (e.g. `foo`)
5. Input is empty on page rendering

### Expected behaviour

Dependant field `subField` should have `foo` value as per `defaultValues`.

The issue is reproduced only in StrictMode having checkbox wrapped with `<Controller shouldUnregister />`. Without StrictMode or using `register()` function for checkbox, the input has initial value on mount. 

_In my real app there are 3 levels of dependant custom select fields (that's why I'm using `<Controller />`)._

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is something we have to address in the next breaking change, with  react 18 strict mode the `useEffect` twice will run twice (including unsubscribe callback), and at the current design useEffect is how we distinguish a component gets `unmount` and calling `unregister`, which also remove the defaultValue from the `defaultValues`

<img width="923" alt="Screen Shot 2022-07-13 at 8 30 20 am" src="https://user-images.githubusercontent.com/10513364/178608388-2d58353d-faf9-4d5a-8255-3d5d9343a13a.png">

## workaround for the current version

https://codesandbox.io/s/relaxed-easley-40vzfy?file=/src/App.js

There could be a chance we have to deprecate `shouldUnreigster` prop altogether in the next major version if this is causing more issues with strict mode, so far this is the first one.
