### ISSUE TITLE
Continue with form submission after validation?

### ISSUE THREAD

**Issue by jamescmartinez** [react-hook-form/react-hook-form#867]
**Is there a way to continue with form submission after validation?**

In my example Codesandbox, when you submit the form it creates an alert but does not continue on to `/contact/thanks` (possible due to `e.preventDefault()` behind the scenes?)

**To Reproduce**
1. Go to the Codesandbox
1. Click `SUBMIT` at the bottom
1. Click `OK` on the alert
* Expected: it continues to the page specified in the action: `/contact/thanks`
* Actual: it does not continue to the page specified in the action

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-basic-4v8r4

**Comment by bluebill1049** [comment]
you can push routes at `handleSubmit` right?
```
onSubmit={(data) => {
  console.log(data);
  props.history.push(); //here
}}
```

**Comment by jamescmartinez** [comment]
I’m looking for the form to be submitted to the specified URL (as HTML-only forms do when not using JavaScript). I don’t have routing set up since this is on a Gatsby project.

**Comment by bluebill1049** [comment]
Gatsby has routing (please look it up) and this lib is made for SPA.

**Comment by bluebill1049** [comment]
there you go: https://www.gatsbyjs.org/docs/routing/

**Comment by jamescmartinez** [comment]
@bluebill1049 I _just_ figured out a solution to my issue right as I saw your reply (what timing!) -- It's different than your suggestion but it might help others who are going down this same path.

```js
<form name="contact" onSubmit={handleSubmit(onSubmit)}>
...
```
in combination with 
```js
function onSubmit() {
  document.forms.contact.submit();
}
```
will submit the form the "old-fashioned" way, but only if validation passes. This is the way that was required for Netlify.

Thanks for your help Bill! Hopefully this helps others if they come around searching. I'll close this issue.
