### ISSUE TITLE
issue: changing name of useWatch doesn't change anything

### ISSUE THREAD

**Issue by nobodywithbody** [react-hook-form/react-hook-form#8670]
### Version Number

7.33.1

### Codesandbox/Expo snack

https://codesandbox.io/s/sparkling-snow-z06xpt?file=/src/App.js

### Steps to reproduce

1. create component with useWatch
2. change name of fields which watch are needed

### Expected behaviour

react-hook-form resubscribe for new fields when name parameter in `useWatch` hook was changed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Expected behavior. The `name` value is used to subscribe to a specific input; it's not dynamic.

You should have multiple subscriptions instead. For optimization purposes you can make use of the `disabled` prop to toggle the subscription depending on your use-case condition

**Comment by nobodywithbody** [comment]
@Moshyfawn  Got it. Thank you for quick  response. But I can’t do this because I don’t know on how many values I should subscribe. It’s also dynamic. In my case I have a list with group property. In each group I should show maximum value. So, I need to subscribe to every field in this group. But I can’t if I understood correctly. Can you suggest how to handle this in proper way with current library?

**Comment by bluebill1049** [comment]
you can have multiple `useWatch` to subscribe to different node levels of fields and disable them by external state. 

So why didn't we make it react to name update, it looks great on paper, however, if we take that as an effect of naming changing, developers will have to memo the dep as well. so the end decision was to make it easy for developers so they (you) don't have to memo the name dep and we cache the name for the subscription. Will we change the current implementation maybe in the future but definitely not within the current version.

**Comment by nobodywithbody** [comment]
> thanks @Moshyfawn's reply, it's correct. ❤️
> 
> you can have multiple `useWatch` to subscribe to different node levels of fields and disable them by external state.
> 
> So why didn't we make it react to name update, it looks great on paper, however, if we take that as an effect of naming changing, developers will have to memo the dep as well. so the end decision was to make it easy for developers so they (you) don't have to memo the name dep and we cache the name for the subscription. Will we change the current implementation maybe in the future but definitely not within the current version.

Thanks for response too! But what if I don't know how many deps will be? So, I can't write this because array length is dynamic.

```js
useWatch({name: `someArray.0.value`}) 
useWatch({name: `someArray.1.value`}) 
```

**Comment by bluebill1049** [comment]
`useWatch({name: 'someArray'})` that's all you need.

**Comment by nobodywithbody** [comment]
> `useWatch({name: 'someArray'})` that's all you need.

I have an array with 100+ elements and 50+ properties in each item. I'm afraid this will be a performance issue. But I need only one field in a bunch of items.

Just suggestion, `useWatch` can provide a `resubscribe` method for this. And developers who need to change name prop will fire effect by themselves. Something like this:

```js

const [deps] = useState(['array.0.value'])
const {value, resubscribe} = useWatch({name: ['array.0.value'], provideResubscribeMethod: true})

useEffect(() => {
   if(deps.length) resubscribe()
}, [])

```

**Comment by bluebill1049** [comment]
thanks for the suggestion, no plan to further increase the API surface.

- virtualise your render with react-window or react-virtual 
- use watch() callback if no re-render is required.

**Comment by nobodywithbody** [comment]
> thanks for the suggestion, no plan to further increase the API surface at the current version.
> 
> * virtualise your render with react-window or react-virtual
> * use watch() callback if no re-render is required.

Thank you for your solution. I guess `watch() callback` is gonna work for a while. BTW, many thanks for this library! You've done great work.
