### ISSUE TITLE
issue: Watch is triggered on mount

### ISSUE THREAD

**Issue by marcospassos** [react-hook-form/react-hook-form#8673]
### Version Number

8.0.0-alpha.4

### Codesandbox/Expo snack

https://codesandbox.io/s/objective-bohr-rx0q89?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/objective-bohr-rx0q89?file=/src/App.tsx
2. Click on "toggle"
3. Open the console
4. Se the watch was triggered

### Expected behaviour

Not trigger watcher since no value changed (default value provided at initialization).

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This one is diffuclt to avoid because users expect each field array action to update the `watch` value, and there is no easy way to detect if the field array is the empty or initial state, so we trigger watch during effect.

**Comment by marcospassos** [comment]
Is there any workaround? In our case, we use a watch to detect changes for auto-saving purposes. 

That's the only thing that blocks from trusting the watcher only. Without a solution, we'd need to keep track of the last value and compare it on every change to avoid spuriously reporting a difference when it never happened.

**Comment by bluebill1049** [comment]
> Not sure if it's related, but another weird behavior is that the field key changes on every mount, even though nothing changes. I've updated the sandbox to illustrate this case.

If you unmount the entire field array, the entire instance will get destoried.

**Comment by bluebill1049** [comment]
> For a workaround, I mean, some way to explicitly tell RHF that this is the initial value.

you may want to do a deepEqual against your defaultValues.

**Comment by marcospassos** [comment]
That's what I'm trying to avoid. In fact, I'd have to keep track of the last value to avoid reporting multiple times.

**Comment by marcospassos** [comment]
> > Not sure if it's related, but another weird behavior is that the field key changes on every mount, even though nothing changes. I've updated the sandbox to illustrate this case.
> 
> If you unmount the entire field array, the entire instance will get destoried.

Is there any way to preserve the key across remounts?

**Comment by bluebill1049** [comment]
> Is there any way to preserve the key across remounts?

you can host your own unique id at your app level.

**Comment by bluebill1049** [comment]
> That's what I'm trying to avoid. In fact, I'd have to keep track of the last value to avoid reporting multiple times.

Unfortunately, this library's watch field array mechanism may not fulfill your requirement.

**Comment by marcospassos** [comment]
This would have a high cost since the form is rendered into tabs. Rendering all tabs even when not visible is something we want to avoid.

**Comment by bluebill1049** [comment]
Perhaps each tab should have its own form rather than host the entire tabs into a giant form, anyway, that's implementation detailed. The current behavior is expected and i will mark it as a design limitation which unfortunately couldn't fulfill your use case above.
