### ISSUE TITLE
Pattern validation is not working correctly for type="number" inputs

### ISSUE THREAD

**Issue by mterczynski** [react-hook-form/react-hook-form#8688]
### Version Number

7.33.1

### Codesandbox/Expo snack

https://codesandbox.io/s/restless-cloud-9lkjhe

### Steps to reproduce

1. Go to [Code Sandbox](https://codesandbox.io/s/restless-cloud-9lkjhe)
2. Click on the input
3. Type in "1e"
4. Notice that there is no error even though the string value doesn't match the pattern

### Expected behaviour

The "invalid number" message is shown

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
use validate function instead, `pattern` are applied to the input string.
