### ISSUE TITLE
issue: ArrayPath is never when passing string[]

### ISSUE THREAD

**Issue by tanmen** [react-hook-form/react-hook-form#8694]
### Version Number

7.33.1

### Codesandbox/Expo snack

https://codesandbox.io/s/hungry-keldysh-bshnz7

### Steps to reproduce

1. create a type containing string[].
2. specify its property in useFieldArray

### Expected behaviour

Not "never" and no error if specified.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Relevant log output

```shell
(property) name: never
Type 'string' is not assignable to type 'never'.ts(2322)
fieldArray.d.ts(7, 5): The expected type comes from property 'name' which is declared here on type 'UseFieldArrayProps<FormValues, never, "id">'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> Does not support flat field array.

https://react-hook-form.com/api/usefieldarray

we do not support flat array structure @tanmen

**Comment by tanmen** [comment]
I did not check.
Thanks for the quick reply X)

**Comment by jones-sam** [comment]
> > Does not support flat field array.
> 
> [react-hook-form.com/api/usefieldarray](https://react-hook-form.com/api/usefieldarray)
> 
> we do not support flat array structure @tanmen

@bluebill1049 any plans to add this in the future? Ran into the same issue as @tanmen, it would be useful. Thanks for the awesome library!

**Comment by Moshyfawn** [comment]
> @bluebill1049 any plans to add this in the future? Ran into the same issue as @tanmen, it would be useful. Thanks for the awesome library!

I don't think so. We need the `object` shape to store the array field id to refer to

**Comment by Upinwv** [comment]
React

--

**Comment by Upinwv** [comment]
Canary Mail
You've received a secure email
***@***.*** has sent you a secure email via Canary Mail.

Read Secure Email (https://secure.canarymail.io/read?obj_id=e122b3f4-508d-49d6-9dd0-e57b940302df&obj_key=dE16QjArZkNyUjJRQ0VtL0NCV3ZnUT09&thr_id=e122b3f4-508d-49d6-9dd0-e57b940302df)

If you expect to correspond often with ***@***.***, we recommend you download Canary Mail for free.

Download Canary (https://canarymail.io)

Privacy (https://canarymail.io/privacy.html) | Terms (https://canarymail.io/terms.html) | Docs (https://help.canarymail.io/) | Support (https://canarymail.zendesk.com/hc/en-us/requests/new)

Copyright © 2021 Canary Mail, All rights reserved.

**Comment by bluebill1049** [comment]
@Moshyfawn is correct ❤️ @jones-sam this is currently its limitation as we will need a unique id for each row since each field array is not re-render the entire field's arrays (fully controlled).
