### ISSUE TITLE
Allow numeric keys for objects

### ISSUE THREAD

**Issue by jaschaio** [react-hook-form/react-hook-form#8705]
**Is your feature request related to a problem? Please describe.**
When using `register()` with dot notation and a numeric key it will always create an array. I currently can't use `react-hook-form` to set the value of an object like this:

```js
{
    "something:" {
        42: {
            "question": "answer",
        },
    },
};
```

If I register the field as `register( 'something.42.question' )` it will create a huge array with `null` values from index 0 to 41 and `"something"` at index 42.

**Describe the solution you'd like**
It would be great if I could either optin to use an object with numeric keys instead of an Array for example with curly braces, e.G. `register( 'something.{42}.question` or had some control over how values get set so I can write my own logic instead. For example something like `setValueAs` but on a form level. 

**Describe alternatives you've considered**
I could transform arrays into objects within the `handleSubmit` handler but this happens to late for me for example because I need to dynamically display things based on the object value

**Additional context**
I tried with `resolver` as well, but that won't transform the data but just validate it. I didn't find any other API I could use instead.

**Comment by bluebill1049** [comment]
Thanks for the feature request, however, This is a limitation of the current implementation of typescript type check, we use number dot notation to differentiate object vs array. So this is most likely not going to implement unless there is some new ts feature that allows us to do a type check against `[]` without relay on dot notation.

**Comment by jaschaio** [comment]
Fair enough, but is there any workaround that doesn't rely on changing the data at the end in handleSubmit?

I noticed that if the initial formState has an object it will set it correctly.

But that's hard to guarantee for all cases, having some escape hatch via the API, for example as a prop passed into useForm would be really helpful. It seems odd that there exists a `setValueAs` API on `register` but nothing similar for the whole form
