### ISSUE TITLE
Should render defaultValue SSR

### ISSUE THREAD

**Issue by tavoyne** [react-hook-form/react-hook-form#8707]
**Is your feature request related to a problem? Please describe.**

Doing SSR or disabling JavaScript cause the default values not to set on the inputs.

**Describe the solution you'd like**

When `defaultValues` is provided to `useForm()`, the `register("...")` method should return the `defaultValue` prop right away.

**Comment by tavoyne** [comment]
Switch to bug

**Comment by bluebill1049** [comment]
thanks for the feature request, unfortunately, default values are injected into the run time, and so does the state. I don't think it's possible to render something into a string on the server with such a combination.

**Comment by tavoyne** [comment]
Just grabbing the default value from `_defaultValues` and returning it from `register` as the `defaultValue` prop should do the trick. No?

Here:
https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/createFormControl.ts#L922

**Comment by bluebill1049** [comment]
Thanks for the reply. Not simple as what you described above, there are uncontrolled, controlled components to be considered and not to mention all those different use cases. However, I am happy to move this into the feature board and waiting for an upvote, but this is something we are unlikely to be implemented.

**Comment by tavoyne** [comment]
I understand, though it doesn't seem to be that much of a big deal. 

And I think it's important. With the advent of Next, Remix, etc., the number of apps implementing SSR increases everyday. People might move away from using this library for small reasons like that. Not mentioning the increasing public interest for progressive enhancement.

Your call.

**Comment by lennerd** [comment]
I'm not quite sure I understand the history of this issue right. Is this still open for upvotes?

**Comment by Moshyfawn** [comment]
It has been removed from community trial state: no longer considered by the RHF team

![image](https://user-images.githubusercontent.com/16290753/183311472-f30b8baa-ed4b-44e7-aeba-72caae0c26ac.png)
