### ISSUE TITLE
Adding validation with useFieldArray

### ISSUE THREAD

**Issue by sterjoski** [react-hook-form/react-hook-form#872]
Please consider asking the question at our spectrum channel.

https://spectrum.chat/react-hook-form

**Describe the question?**
How would you add validation when using useFieldArray?
**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-jdwpm
2. Click on 'SUBMIT'
3. No errors are shown

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-jdwpm

**Comment by bluebill1049** [comment]
attach validation into the register function

**Comment by sterjoski** [comment]
> attach validation into the register function

@bluebill1049  Are there any examples for this?

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#register

**Comment by bluebill1049** [comment]
Closing this issue. Feel free to follow up with questions tho.

**Comment by sterjoski** [comment]
@bluebill1049 I'm still having trouble with this. Could you take a look at this? https://codesandbox.io/s/vigilant-chatterjee-mi4jc?fontsize=14&hidenavigation=1&theme=dark

**Comment by Motoxpro** [comment]
Just wanted to update this issue with an example of yup Validation https://codesandbox.io/s/react-hook-form-usefieldarray-c82kl

**Comment by kancharla-sandeep** [comment]
How to use validation for **Controller** Input. Using rules does not show any validation.

**Comment by bluebill1049** [comment]
It's the same as `register` but through `rules` props

**Comment by Flavien-Pensato** [comment]
@bluebill1049 Why `useFieldArray` doesn't accept rules ? Should it not be like `<Controller />` ?
