### ISSUE TITLE
issue: Select value is not aligning with dynamic options based on other field values

### ISSUE THREAD

**Issue by jcamato** [react-hook-form/react-hook-form#8722]
### Version Number

7.33.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-csb-m5t03g?file=/src/ReactHookForm.tsx

### Steps to reproduce

I tried condensing this down as much as possible. The original functionality has buttons to increment or decrement single episodes, but I believe this is all under the same issue and can be demonstrated solely by the finish button.

1. Select any season other than the last
2. Click on 'finish'

You will see that both the episode value and episode options are correct, but the select is not displaying the correct value. If you are already on the final season, then clicking 'finish' will immediately show the correct value. I know this is happening because we are transitioning from a season with less possible episodes than the one that is being set. If the final season has less than or equal to the number of episode of the current season, then the finish button works properly. 

### Expected behaviour

The `<select>` for `progress_episode` gets its possible values from `watch('progress_season')` to determine the episode count. When using `setValue` to update the inputs outside of the select element, `watch` seems to display the correct values, but the current selection on the input doesn't update.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcamato** [comment]
I also want to say how much I love this library. It is so powerful, thank you!

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report and condensed csb (i can see the effort), would you mind sharing a video on the actual issue as well? It probably would be easier to spot the issues.

also curious about the following code maybe the root cause:

```tsx
const episode_options = getEpisodeOptions(
  progress_options,
  watch("progress_season")
);
```

could you also double-check if the watch itself returns the expected results for you?

**Comment by Moshyfawn** [comment]
> Thanks for the detailed issue report and condensed csb (i can see the effort), would you mind sharing a video on the actual issue as well? It probably would be easier to spot the issues.

If you click the "finish" button, you'll see the `watch("progress_episode")` value get updated from `1` to `13`, but the actual `select` episode input `value` won't reflect it and would stay at `1`

<img width="553" alt="image" src="https://user-images.githubusercontent.com/16290753/180627187-5d7e49c1-5b7c-45ac-b081-a55a5730e4b7.png">

**Comment by bluebill1049** [comment]
thanks, @Moshyfawn got it thanks. coupld issues:

- `valueAsNumber` is not applicable for `select`
- the select only has values up to 6 thence set select 13 is not going to work

![Uploading Screen Shot 2022-07-24 at 10.31.58 am.png…]()

**Comment by jcamato** [comment]
> thanks, @Moshyfawn got it thanks. coupld issues:
> 
> 
> 
> - `valueAsNumber` is not applicable for `select`
> 
> - the select only has values up to `6` hence set select `13` is not going to work
> 
> 
> 
> <img width="421" alt="Screen Shot 2022-07-24 at 10 32 30 am" src="https://user-images.githubusercontent.com/10513364/180627319-c54c834a-cae3-4931-bb67-7a892752d09b.png">
> 
> 
> 
>  

Thank you @Moshyfawn and @bluebill1049 

I can make a video later when I'm home.

@Moshyfawn clarified, and when you click "finish" again then it updates to the correct final episode.

I wonder why there are only 7 options for select when you can see in the image episode_options shows 1-13. Episode_options is what maps the select options.

**Comment by Moshyfawn** [comment]
Feels like some kind of race condition. If you manually set the `progress_episode` value to, say, 7 _(a number that's within the amount of previously available options)_, the `select` is correctly showing displaying "Episode 7".

Basically, the `select` options get updated later than the `select` value

**Comment by jcamato** [comment]
Exactly. If the final season has an episode number that is equal to or less than the season you are currently in, then the button performs correctly.

I have to dynamically update the episode options based on which season is selected so I'm not sure how else to make sure that always renders before the value is set.

**Comment by Moshyfawn** [comment]
Here's a screen-cast confirming the issue

https://user-images.githubusercontent.com/16290753/180627562-79bd8271-f968-44c8-b486-612550f0d944.mp4

**Comment by Moshyfawn** [comment]
> I have to dynamically update the episode options based on which season is selected so I'm not sure how else to make sure that always renders before the value is set.

I'd say, the `progress_episode` input should be controlled instead, because it's more of a React component life-cycle issue at this point. Here's a very crude example; you can optimize it however you want, but the idea is to "control" the input's value outside of it, instead of using the uncontrolled API _(`register`)_ where the input's value source of truth is inside the input and "hoping" value's gonna be updated in time after the "outside" update
```js
<Controller
  control={control}
  name="progress_episode"
  render={({ field }) => (
    <select {...field}>
      {episode_options.map((option) => (
        <option key={option} value={option}>
          Episode {option}
        </option>
      ))}
    </select>
  )}
/>
```

**Comment by Moshyfawn** [comment]
[A working CSB](https://codesandbox.io/s/react-hook-form-csb-forked-34ktoo?file=%2Fsrc%2FReactHookForm.tsx%3A2737-3362)

**Comment by jcamato** [comment]
@Moshyfawn this is super helpful, thank you! I have never worked with Controlled components with React hook Form before so this will be a first for me. I will have to read up on them to understand what is going on better. But your example totally works so that's awesome!

**Comment by Moshyfawn** [comment]
The concept of controlled vs uncontrolled inputs is outside RHF and is about where the input's value is stored. 

You can better learn about this concept and the RHF `Controller` API yourself, but the `TLDR;` is: controlled components are "controlled" with a value from outside, like React's `state`, so, they're being "fed" the value into their `value` prop or whatever. Uncontrolled components on the other hand, are the source of truth of their value, like a plain HTML input without JS; RHF listens for it's `onChange` event and "makes note" of it's value, but never "tells" the input what the value is.

**Comment by jcamato** [comment]
> * `valueAsNumber` is not applicable for `select`

@bluebill1049 I wanted to ask about this. I have another `<select` input that uses the `id` number values of the labels for the value, and if I don't use `valueAsNumber: true` then the validation doesn't pass as a number. Are you saying if I am using number values for `<select>`it would be better for me to not use `valueAsNumber` and then convert to number after validation and before form submission?

**Comment by jcamato** [comment]
> The concept of controlled vs uncontrolled inputs is outside RHF and is about where the input's value is stored.
> 
> You can better learn about this concept and the RHF `Controller` API yourself, but the `TLDR;` is: controlled components are "controlled" with a value from outside, like React's `state`, so, they're being "fed" the value into their `value` prop or whatever. Uncontrolled components on the other hand, are the source of truth of their value, like a plain HTML input without JS; RHF listens for it's `onChange` event and "makes note" of it's value, but never "tells" the input what the value is.

This makes a lot more sense. Thank you for all your help!

**Comment by Moshyfawn** [comment]
If you've never used the `Controller` API before, make note of what the `field` object is and that it has the `value` prop which you can spread into an input along with the other props you can find returned from the `register` method call. But `register` never returns `value`, since it's designed to handle the uncontrolled components

**Comment by Moshyfawn** [comment]
> > * `valueAsNumber` is not applicable for `select`
> 
> @bluebill1049 I wanted to ask about this. I have another `<select>` input that uses the `id` number values of the labels for the value, and if I don't use `valueAsNumber: true` then the validation doesn't pass as a number. Are you saying if I am using number values for `<select>` it would be better for me to not use `valueAsNumber` and then convert to number after validation and before form submission?

`valueAsNumber` can only by applied to date, time based or numeric inputs as per the Web API. RHF uses the native `event.target.valueAsNumber` API under the hood, so it won't work for select. I'd suggest to use the `setValueAs` callback instead

**Comment by jcamato** [comment]
I didn't know that either, that's is really helpful. I use `setValueAs: (v) => parseInt(v)` elsewhere so am familiar with the callback version. I will switch to something like that. Thank you!
