### ISSUE TITLE
issue: prepending a item with undefined results in it having the same value as the previous item at index 0

### ISSUE THREAD

**Issue by stijnvanderlaan** [react-hook-form/react-hook-form#8729]
### Version Number

7.33.1

### Codesandbox/Expo snack

https://codesandbox.io/s/usefieldarray-with-defaultvalue-gghw2s?file=/src/App.tsx

### Steps to reproduce

1. Go to 'https://codesandbox.io/s/usefieldarray-with-defaultvalue-gghw2s?file=/src/App.tsx'
2. Click on 'Prepend'
3. The next items is 3 instead 'Default' the defaultValue provided by the Controller

### Expected behaviour

I expect the new value to be the defaultValue or undefined, not 3.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Expected behavior. The array method call payload is required and should be full.

Check out [the Return section of useFieldArray RHF docs](https://react-hook-form.com/api/usefieldarray) to learn more:
> Important: prepend data is **required** and **not partial**.
