### ISSUE TITLE
Fix inconsistency between API for different ways to set errors,  setError and register

### ISSUE THREAD

**Issue by joejknowles** [react-hook-form/react-hook-form#873]
**Is your feature request related to a problem? Please describe.**
The set error API takes an object to describe the error - `{ name, type, message }` but creating errors with the `register` function is complicated. You can return a string from a function to give a message, and sometimes(?) you can select a type like with validate and nesting a function under a key that represents its type.

**Describe the solution you'd like**
Why not allow returning an object from validate etc. functions in `register` options, which is similar to the setErrors API, like `{ type, message }` ?

**Additional context**
I'm trying to have both a message and an `ID` for each error be available when I'm displaying errors. I don't really understand the motivation behind the "type" field, but I'm using it as an id for the errors.

**Comment by bluebill1049** [comment]
can you please give more detail?

**Comment by bluebill1049** [comment]
i see what do you mean now:

`set('test', 'wrong')`

vs

`set({ type: 'test', message: 'test' })`

you see you type a lot more. that's the reason why i decided to go with option 1, if you are using TS, it should give you type hint as well.

**Comment by bluebill1049** [comment]
for now i don't think we will introduce this breaking change.

**Comment by bluebill1049** [comment]
thanks for your suggestion tho.

**Comment by joejknowles** [comment]
Hi @bluebill1049 

Sorry I wasn't clear, and I made a mistake quoting the `setError` API. I'll copy some of the docs so we're on the same page. 

The `setError` I'm referring to is `setError(ManualFieldError[])`, where ManualFieldError could be `{ name: "age", type: "minimum", message: "You must be over 120" }`

In this case you explicitly set the type and message, whereas in the `register` options, setting a type and message is a bit more complicated, as below. Setting the type is done by the object key (positive/lessThanTen below), and the message can be the return from the function.

```
// from the docs
register({
      validate: {
        positive: value => parseInt(value) > 0 || "Must be greater than zero",
        lessThanTen: value => parseInt(value) < 10
      }
    })
```

And the same with other validators like pattern. Can you even control the "type" here? I think it has to be "pattern" right?

```
// from the docs
<input
  name="test"
  ref={
    register({
      pattern: /[A-Za-z]{3}/
    })
  }
/>
```

So, how about making all of these work the same, by allowing the functions to return an object that's similar to ManualFieldError, but without the field name in there, so something like:

```
register({
      validate: value => parseInt(value) > 0 || {
          message: "Must be greater than zero",
          type: "greaterThan0"
      }
    })
```


Does this make sense?

**Comment by bluebill1049** [comment]
> Hi @bluebill1049
> 
> Sorry I wasn't clear, and I made a mistake quoting the `setError` API. I'll copy some of the docs so we're on the same page.
> 
> The `setError` I'm referring to is `setError(ManualFieldError[])`, where ManualFieldError could be `{ name: "age", type: "minimum", message: "You must be over 120" }`
> 
> In this case you explicitly set the type and message, whereas in the `register` options, setting a type and message is a bit more complicated, as below. Setting the type is done by the object key (positive/lessThanTen below), and the message can be the return from the function.
> 
> ```
> // from the docs
> register({
>       validate: {
>         positive: value => parseInt(value) > 0 || "Must be greater than zero",
>         lessThanTen: value => parseInt(value) < 10
>       }
>     })
> ```
> 
> So, how about making these work the same, by allowing the functions to return an object that's similar to ManualFieldError, but without the field name in there, so something like:
> 
> ```
> register({
>       validate: value => parseInt(value) > 0 || {
>           message: "Must be greater than zero",
>           type: "greaterThan0"
>       }
>     })
> ```
> 
> Does this make sense?

yes make sense. I have noted this down and we will be looking into this in the next major release.
