### ISSUE TITLE
issue: Resolver doesn't fire when trigger() invoked

### ISSUE THREAD

**Issue by ivanovserge** [react-hook-form/react-hook-form#8738]
### Version Number

7.33.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-validationschema-forked-rmzmk5

### Steps to reproduce

1. Click on 'Trigger' button.
2. See error.

### Expected behaviour

'firstName' field must has error just like when clicking on submit button.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
hey @ivanovserge you just need `onClick={() => trigger(undefined, { shouldFocus: true })}` and it's working for me.

https://codesandbox.io/s/react-hook-form-v7-validationschema-forked-pjyq4c

**Comment by ivanovserge** [comment]
> hey @ivanovserge you just need `onClick={() => trigger(undefined, { shouldFocus: true })}` and it's working for me.
Thanks a lot!
