### ISSUE TITLE
Validation is not rendered with antd component

### ISSUE THREAD

**Issue by baeharam** [react-hook-form/react-hook-form#874]
I'm updating `validateStatus` of antd `Input` component using validation process of this package, but it is not properly rendered. Here is codesandbox and what is the problem?

[![Edit antd with react-hook-form](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigorous-dream-zw7ic?fontsize=14&hidenavigation=1&theme=dark)

Thanks

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/antd-with-react-hook-form-vm5dr
Here you go :)

**Comment by baeharam** [comment]
@bluebill1049 Great solution, but I'm getting "Missing name" warning, what is wrong?

**Comment by bluebill1049** [comment]
There is no warning in my example, i think you are register twice in your example.

**Comment by baeharam** [comment]
Umm...Ok I'll check it myself, Thanks!

**Comment by BrianMwas** [comment]
Why am I getting a Missing name @
here's my code
`<Form.Field required>
                        <label>Username</label>
                        <Input 
                        placeholder='Username'
                        name='username'
                        width={8}
                        value={state.username}
                        onChange={onChange}
                        ref={
                            register({
                                required: 'Required',
                                maxLength: {
                                    value: 20,
                                    message: "Username requires a maximum of 20 characters."
                                },
                                minLength: {
                                    value: 3,
                                    message: "Username requires a minimum of 3 characters."
                                },
                            })
                        }
                        type="text" />
                    { errors.username && <small>{ errors.username.message }</small> }
                    </Form.Field>`

**Comment by BrianMwas** [comment]
Am using semantic ui react

**Comment by bluebill1049** [comment]
@BrianMwas semantic ui react probably not expose ref correctly or at all. you may want to use Controller for it.

**Comment by BrianMwas** [comment]
Ooh okay let me try
