### ISSUE TITLE
useFieldArray - changing name does not change fields

### ISSUE THREAD

**Issue by dbousamra** [react-hook-form/react-hook-form#8743]
### Version Number

7.33.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-y46uqy?file=/src/index.js

### Steps to reproduce

1. Increment the step counter
2. Observe the fields length does not change

### Expected behaviour

The fields length to change.

I know I could be using watch here. But this is a simplistic example to reproduce the issue I am seeing.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
name is cached on the initilation, and we don't support dynamic field array names.

**Comment by dbousamra** [comment]
Okay. What do you recommend?

**Comment by Moshyfawn** [comment]
#8715
