### ISSUE TITLE
[FieldError] - unexpected type error for Date property which is not nullable

### ISSUE THREAD

**Issue by I3enito** [react-hook-form/react-hook-form#8749]
### Version Number

7.33.1

### Codesandbox/Expo snack

https://codesandbox.io/s/recursing-jang-9l8kqm?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/recursing-jang-9l8kqm?file=/src/App.tsx
2. Check the `App.tsx` and check the type error for the `mandatoryDateError`

### Expected behaviour

After upgrading to version 7.33.1 I got TS-errors because my `DateInput` expect a `FieldError` regardless if the Date is nullable or not. This is not an urgent issue but I thought it might be a edge case which has been discovered. Or perhaps I just don't understand why this behaviour makes sense. 

Thanks for your work and the awesome library!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for the issure report, type `undefined` is not assignable to `FieldError` https://codesandbox.io/s/focused-noyce-neh1zj?file=/src/App.tsx the latest update eliminated the need to use `NestedValue` to differentiate a nested object input vs a group of inputs.  https://react-hook-form.com/ts#NestedValue This is a huge improvement for some use cases, as developers will no longer to implemented the NestedValue type anymore, however it does bring some limitations,s and moving forward I think it's worth taking those trade-offs, such as discriminating unions and perhaps your specific usage above as well. This will most likely not be reverted and moving forward to bring feature such as `rules` for `useFieldArray`.

**Comment by I3enito** [comment]
Thanks for the response. I honestly cannot completely follow your explanation as I didn't use `NestedValue` but that's fine. I was just surprised that there was another type generated for the error when using a Date. My solution is to just expect this type as well for my `DateInput` component.  
```tsx
interface InputDateProps<T> {
    className?: string
    type: 'date' | 'time'
    register: UseFormRegister<T>
    isDirty?: boolean
    defaultValue?: string
    label: string
    name: Path<T>
    required?: boolean
    error?: Merge<FieldError, FieldErrorsImpl<DeepRequired<Date>>> | FieldError
}
```

**Comment by bluebill1049** [comment]
It's not that you are using `NestedValue`, the change was made so users don't have to use `NestedValue` anymore. related PR: https://github.com/react-hook-form/react-hook-form/pull/8527/files I will take a look at the issue this weekend and see if we can improve or else you will have to use the work around which you have provided above. 🙏
