### ISSUE TITLE
Generic useFieldArray hook

### ISSUE THREAD

**Issue by Blakeinstein** [react-hook-form/react-hook-form#8751]
**Is your feature request related to a problem? Please describe.**
The useFieldArray hook needs to be generic. That allows me to implement an array of structs. For ex:
Consider a formfield of type:
```ts
type Port = {
  name: string,
  port: number,
  protocol: string,
}
type Ports = Port[]
```
Now I want to implement a form field for the same. I initialize a context with 
```ts
const { fields } = useFieldArray({ control, name: 'Ports' })
```
here fields is of type `Record<"id", string>[]` which doesnt make sense to me, since this implies the data looks like
```
fields = {
	id: value
}[]
```

and for this usecase with a generic useFieldArray used something like 
```ts
const { fields } = useFieldArray<Port>({ control, name: 'Ports' })
```
and should yield a fields of type `Port & { id: string }` because that what it looks like when ignoring all ts errors.

**Comment by bluebill1049** [comment]
Putting this request to the feature board, although it's rather difficult to achieve. @felixschorer did try to improve this on the v8, however, it was blocked by ts 4.7 upgrades.
