### ISSUE TITLE
reset is not rendered properly

### ISSUE THREAD

**Issue by baeharam** [react-hook-form/react-hook-form#877]
My intention is clear input fields when user clicks OK button of `Modal` component. But, only value is changed, not rendered properly. How can I fix it?

[![Edit reset is not working](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/crazy-leavitt-bksj7?fontsize=14&hidenavigation=1&theme=dark)

Thanks

**Comment by bluebill1049** [comment]
in terms of reset(), you will have to use `Controller` because Antd input doesn't expose `ref`. 

https://react-hook-form.com/api#Controller

**Comment by bluebill1049** [comment]
in case you didn't know we have a spectrum channel for questions as well. :)

**Comment by baeharam** [comment]
@bluebill1049 But, I'm using `ref` as props of `Input` component. Is it different from what you're saying?

**Comment by bluebill1049** [comment]
Can you console log the ref? And check if it’s really the reference of the input?

Ref={e=> console.log()} I remember it’s an object instead of the actual input ref. You may have to do register inside the callback

**Comment by baeharam** [comment]
I updated, you can see

**Comment by bluebill1049** [comment]
see in your own console. 
<img width="702" alt="Screen Shot 2020-01-21 at 7 09 49 pm" src="https://user-images.githubusercontent.com/10513364/72786407-9c5cda00-3c81-11ea-92a3-030c21f7fd50.png">

`register(e.input)`

**Comment by baeharam** [comment]
You mean `register(e.input)` can be the solution?

**Comment by bluebill1049** [comment]
let me explain what register does: (please read the documentation as well, it's also in Korean)

`register` is register the input reference into the custom hook, in this example `e.input` contains the actually input reference. 

`ref={register}` didn't work for antD input because their ref is an object not actual ref

```
ref={e => {
  register(e.input)
}}
```
will solve the problem. or have a read at Controller, it's an alternative solution too.

**Comment by baeharam** [comment]
I tried all your solutions, but any solution is not working. Controller or callback of ref are not working for my expected behavior. Can you provide solution example for this? or is it bug? Also, document is not intuitive for `Input` component. Why example is for `Select` ? I think `Input` is more general example. Isn't it?

**Comment by bluebill1049** [comment]
> Also, document is not intuitive for `Input` component. Why example is for `Select` ? I think `Input` is more general example. Isn't it?

that's NOT cool. we (all the contributors) spent a lot of time on documentation to make it friendly for developers around the world. There is no way i can fit all the examples.

**Comment by bluebill1049** [comment]
1. read the documentation on reset, this is really unfair saying the documentation is  not intuitive.
<img width="853" alt="Screen Shot 2020-01-21 at 8 48 37 pm" src="https://user-images.githubusercontent.com/10513364/72794034-6aeb0b00-3c8f-11ea-9658-f2cb59fe006c.png">

2. here is a working example contains:
 - native
 - controller
 - custom register
https://codesandbox.io/s/reset-is-not-working-gubrn

**Comment by baeharam** [comment]
@bluebill1049 Sorry for the misunderstanding of my intention, my intention was not ignoring effort of your documentation. Thanks for your detail explanation
