### ISSUE TITLE
issue: FormContext doesn't update field state on touch

### ISSUE THREAD

**Issue by fzaninotto** [react-hook-form/react-hook-form#8786]
### Version Number

7.31.3

### Codesandbox/Expo snack

https://codesandbox.io/s/useformstate-forked-tmt6hw?file=/src/App.js

### Steps to reproduce

1. click inside the name field
2. click outside the name field
3. the Form state properly updates to show the "firstName" field as "touched"
4. the field state doesn't update

<img width="512" alt="image" src="https://user-images.githubusercontent.com/99944/182707528-6bfab0f5-ec18-422b-b967-09fd7e2920b7.png">

### Expected behaviour

I'd expect the results of `formContext.getFieldState` and `useFormState`  to be in sync. 

I need both because there is no simple way to determine is a field was touched using `useFormstate`

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
`getFieldState` is not a subscription but rather a getter. Same difference as with `getValues` and `watch`: the former will update the value on render and the latter will cause a re-render itself due to the value change.

**Comment by Moshyfawn** [comment]
Alright, ignore what I said previously about `getFieldState` and subscribtions _(a long day, sry)_

It's the same subscription mechanism as the `formState` object. You need to subscribe to the value you want to see updated or simply pass the `formState` object into `getFieldState` as the second argument:
```js
formContext.getFieldState(name, formContext.formState)
```

**Comment by Moshyfawn** [comment]
Please, refer to [the Rules section of RHF docs on `getFieldState` method](https://react-hook-form.com/api/useform/getfieldstate/#rules) to learn more about subscriptions:

> 
> `formState` will **need to be subscribed**:
> - You can simply define the required state information when destructuring the returned value of a relevant hook
> - You can pass the entire `formState` from `useForm`, `useFormContext` or `useFormState` directly to `getFieldState`.

**Comment by fzaninotto** [comment]
Thanks a lot for your answer!

I understand that `useForm` and `useFormState` affect the way `getFieldState` works - but `getFieldState` comes from `useFormContext`, so I don't understand why. In other terms, react-hook-form hooks have strong side effects, and it's absolutely not apparent in the documentation. 

A dumb question: why doesn't getFieldState default to using formContext.formState as second argument?

There is only one working example in the `getFieldState` doc, and it's when using `getFieldState` in the same component as `useForm`. Using it from `FormContext` isn't documented, so I had no idea this wouldn't work. I think more working examples would help comprehension.

Finally, I did my best but couldn't understand some sentences in this documentation: 

- "formState: object - When set to true, field error will be retained.". What's "object"? what's "retained"? And now I understand that this argument is required, but the doc doesn't say it. 
- "formState will need to be subscribed" By whom? Where? What's a form state subscription? 
- "You can simply define the required state information when destructuring the returned value of a relevant hook, such as useForm (at global level) or useFormState (at hook level)." The word "simply" here makes me smile, because it's the only thing I understand in the sentence. 

I love react-hook-form, but this particular function make me feel super dumb. Perhaps it could use some love.

**Comment by bluebill1049** [comment]
Thanks for the feedback @fzaninotto 

> react-hook-form hooks have strong side effects, and it's absolutely not apparent in the documentation.

Could you extend on this part which I don't follow?

>A dumb question: why doesn't getFieldState default to using formContext.formState as second argument?

`getFieldState` is a method produced by `useForm`, it wouldn't have context reference such an additional hooks, best example would be `useController` then you can invoke `useFormContext` inside the hook. So that's not possible.

> Finally, I did my best but couldn't understand some sentences in this documentation:

I will look into the bullet points, If you are happy I can tag you on the PR review for the improvements.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/documentation/pull/804#issuecomment-1204564985

I will give some more context on why this is the case here as well, in case others reading this issue:

first thing, you probably don't need this function

## Why such API

This API  was introduced as a convicent way to read field state but it may end up not as convincing as it looks, especially if users are not subscribing/reading form state from each hook. React hook form optional both re-render and computation, subscription/read `formState` is essentially a way communicate with the lib on which state do you want it to compute or send re-render. Demonstration with proxy alike internal structure allows users to simply consume the code and all the subscription stuff is taken care of within the library. however, this may lead to users getting confused "subscribed", which is something we can potentially look into to improve on the API level.

Something in my head, which require more code but it's more declarative: `useForm({ subscribe: ['dirty'] })` but it's just a though unless we are hitting more and more confusing then we will consider an RFC on this topic and moving forward.

**Comment by fzaninotto** [comment]
Thanks for taking the time to look into this.

> react-hook-form hooks have strong side effects, and it's absolutely not apparent in the documentation.

Let me clarify that point. 

```jsx
// let's say the 'name' field is pristine
const { getFieldState } = useFormContext();
// Then the user updates the field
const { isDirty } = getFieldState('name');
console.log(isDirty); // false, which is wrong

// when I use another hook, it affects the subscription in getFieldState
const { dirtyFields } = useFormState();
// same code from then on
const { getFieldState } = useFormContext();
const { isDirty } = getFieldState('name');
console.log(isDirty); // true, which is right

// so useFormState() affects the way useFormContext works??
// useFormState has a side effect on useFormContext. It 'bleeds'.
```

I'll look into your doc PR and see if I can understand better!

**Comment by bluebill1049** [comment]
Thanks for the doc, I will adjust your comments.

```
const { getFieldState } = useFormContext(); // formState subscription is not notified
const { isDirty } = getFieldState('name');
```

vs

```
const { dirtyFields } = useFormState();  // formState `dirtyFields` subscription is notified
const { getFieldState } = useFormContext();
const { isDirty } = getFieldState('name');
```
