### ISSUE TITLE
issue: `watch()` is not typesafe even with resolvers

### ISSUE THREAD

**Issue by ricardo-rp** [react-hook-form/react-hook-form#8792]
### Version Number

7.34.0

### Codesandbox/Expo snack

https://codesandbox.io/s/watch-type-unsafe-3tn498?file=/src/App.tsx

### Steps to reproduce

1. Open the codesandbox
2. Verify that both 'default' and 'current' are of type `number`
3. Change the number in the input
4. Verify that, after changing the input, 'current' is of datatype `string`
5. Click on submit
6. Verify that, on the submit function, yup resolver parses the value to number correctly

### Expected behaviour

`watch` should return the value from `input type='number'` correctly parsed to `number`, or the type signature of watch should resolve the property to "string".

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is something not possible for us to improve as it's runtime parsing.

**Comment by ricardo-rp** [comment]
@bluebill1049  Would it not be an improvement have the properties coming from `watch` be typed as `string`? That's what they currently are. 
Or is this an issue with the yupResolver not parsing when it actually should?

**Comment by ricardo-rp** [comment]
@bluebill1049 I don't think this is related to runtime parsing as the result is the same whether I use a resolver or not:
Typescript tells me the value is a number when in reality it's something else.
I'm not sure where the point of failure is though.

**Comment by bluebill1049** [comment]
native input will always return a string unless invoked with `valueAsNumber`, or external schema validation lib will need to parse the value into `number`.

**Comment by ricardo-rp** [comment]
I see. I was under the misassumption that the value would be parsed with the same resolver used for the `onSubmit` function.
`valueAsNumber` inside register options does solve my issue. Thank you.

Solved codesandbox:
https://codesandbox.io/s/watch-typesafe-n1j9j5?file=/src/App.tsx
