### ISSUE TITLE
Stop "register(field, {onChange})" event handlers from overriding react hook form's logic.

### ISSUE THREAD

**Issue by sgarcia-dev** [react-hook-form/react-hook-form#8795]
**Is your feature request related to a problem? Please describe.**
Assuming the following input:
```

<input type="text" {...register('name')} />
```

But now I need to execute X onChange of this name field. Because providing my own `onChange` breaks react hook form, I'm forced to introduce code like one of the following 2 solutions:
```
const myOnChange = (e) => {
  setValue(e.target.value)
  // my logic
}
<input type="text" {...register('name')} onChange={myOnChange} />
```

And following the [v7.16.0](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.16.0) release:
```
const  nameField = register('name');
<input type="text" {...register('name'), {
  onChange: (e) => {
    nameField.onChange(e)
    myOnChange(e)
  }} />
```

**Describe the solution you'd like**
Allow us to write this code:

```
<input type="text" {...register('name'), { onChange: myOnChange } />
```

This removes unecessary boilerplate when 90% of the time we want react hook form's onChange and our custom one to keep working. While giving us the guarantee that it will not override the original onChange handler. In order to not break backwards compatible code, we could add a flag like:

```
<input type="text" {...register('name'), { keepOriginalHandlers: true, onChange: myOnChange } />
```

**Comment by Moshyfawn** [comment]
Um, my apologies, if I understood your feature request incorrectly, but the way you'd run your "custom" `onChange` callback on input change is
```js
<input {...register("name", { onChange: handleChange })} />
```

So, your proposal is all ready in place.

Please, advise, if I got it wrong.

**Comment by Moshyfawn** [comment]
You don't need to `register` your input multiple times and call `field.onChange` inside the `register` `onChange`

**Comment by bluebill1049** [comment]
Thanks @Moshyfawn yes this is already implmeneted.

**Comment by sgarcia-dev** [comment]
My deepest apologies everyone, I had a strange bug in my current codebase which caused this to not work. I'll be sure to provide an isolated, runnable next time to ensure this doesn't happen again.

**Comment by Moshyfawn** [comment]
No worries, glad it's working for you now!
