### ISSUE TITLE
Could not validate field on Safari with React app production build mode 

### ISSUE THREAD

**Issue by dhhthach** [react-hook-form/react-hook-form#8796]
### Version Number

7.33.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-apply-validation-forked-dyf42f

### Steps to reproduce

1. Have the set up and simple UI like codesandbox
2. Build a bundle with webpack production mode
3. Run it, let the field empty and click on Submit button 

### Expected behaviour

There should be an error message due to an empty field. It works correctly on Chrome but not on Safari. 
The issue seems weird on **validateField** method
`validateField = async (field, inputValue, validateAllFieldCriteria, shouldUseNativeValidation)`
`field` is **undefined** however, the argument is completely okay before being passed to that function. Please take a look at these screenshots

Before calling method

![image](https://user-images.githubusercontent.com/5305853/183006715-c367458c-6850-4b67-be44-4a8d1c6a1d22.png)

Inside method

![image](https://user-images.githubusercontent.com/5305853/183006935-1492ab19-eb15-4209-a86a-e5d82519ee88.png)

### What browsers are you seeing the problem on?

Safari

### Relevant log output

```shell
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'n._f')
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is not something we can fix if this is browser level or certain polyfill is missing, plus more information required such as reproducible repo with prod build, which version and safari and etc. If you can provide more info, I will have a quick test on my end.
