### ISSUE TITLE
TypeError: Type 'Merge<FieldError, FieldErrorsImpl<DeepRequired<any>>> | undefined' is not assignable to type 'ReactNode'.

### ISSUE THREAD

**Issue by meotimdihia** [react-hook-form/react-hook-form#8805]
### Version Number

7.34.0

### Codesandbox/Expo snack

https://stackblitz.com/edit/next-typescript-pokptk-wuiput?file=package.json,pages%2Findex.tsx

### Steps to reproduce

1. Wait for installing
2. Navigate to the file `pages/index.tsx`
3. Error on the line: 
```typescript
{errors.test && <p>{errors.test.message}</p>}
```

### Expected behaviour

No error.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
missing `defaultValues` or type defination.

```
{
  defaultValues: {
    test: 'data'
  }
}
```

or 

useForm<{ test: string }>()

**Comment by dpvdberg** [comment]
Sorry to re-open this issue, but how do I solve this when using a Yup object resolver from [react-hook-form resolvers](https://github.com/react-hook-form/resolvers)?
e.g.

```
const validationSchema = Yup.object().shape({
	email: Yup.string()
		.email(t('email-invalid'))
		.required(t('field-is-required')),
	password: Yup.string()
		.required(t('field-is-required')),
});
const formOptions = {resolver: yupResolver(validationSchema)};
const {
	handleSubmit,
	register,
	formState: {errors, isSubmitting},
} = useForm(formOptions)
```

**Comment by meotimdihia** [comment]
@dpvdberg I still can't solve it yet. Currently, I don't have time. 
I downgraded react-form-hook to `7.32.0`

**Comment by dpvdberg** [comment]
Apparently, adding `useForm<{email: string, password: string}>` in my example did actually work :)
