### ISSUE TITLE
issue: Cannot set Date type defaultValue in useForm by TypeScript

### ISSUE THREAD

**Issue by tomoyukikino** [react-hook-form/react-hook-form#8807]
### Version Number

7.34.0

### Codesandbox/Expo snack

https://codesandbox.io/s/happy-dream-vc0ibe?file=/src/App.tsx

### Steps to reproduce

show codesandbox

### Expected behaviour

The defaultValue in <input> can contain the string type "2021-01-01", but the defaultValue in useFrom cannot contain the string type "2021-01-01".
However, the defaultValue in useFrom cannot contain the string type "2021-01-01".
This is probably a typeScript specific problem...

I would like to be able to set the defaultValue of a Date type form also in defaultValue in useFrom.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
codesandbox line 15: Type 'string' is not assignable to type 'Date | undefined'.
codesandbox line 27: Type 'Date' is not assignable to type 'string | number | readonly string[] | undefined'.
  Type 'Date' is not assignable to type 'number'.ts(2322)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
fixed: https://github.com/react-hook-form/react-hook-form/commit/b41c4401d9924480f678806a9fe0b89ec57c2628 will release in the next patch

**Comment by tomoyukikino** [comment]
@bluebill1049 thank you

**Comment by tomoyukikino** [comment]
@bluebill1049 
hi I changed newest version in [codesandbox](https://codesandbox.io/s/happy-dream-vc0ibe?file=/src/App.tsx).
but It haven't fixed yet.

<img width="1671" alt="Screen Shot 2022-08-17 at 15 37 44" src="https://user-images.githubusercontent.com/45547251/185052157-8f2416e9-353e-4690-b7be-baf94b1c314c.png">

**Comment by bluebill1049** [comment]
```tsx
import React from "react";
import { useForm, SubmitHandler } from "react-hook-form";
import "./styles.css";

type Inputs = {
  exampleDate1: Date;
  exampleDate2: Date;
  exampleDate3: Date | string;
  exampleDate4: Date;
};

export default function App() {
  const { register, handleSubmit } = useForm<Inputs>({
    defaultValues: {
      exampleDate3: "2021-01-01",
      exampleDate4: new Date(2022, 8, 1)
    }
  });

  const onSubmit: SubmitHandler<Inputs> = (data) => console.log(data);

  return (
    /* "handleSubmit" will validate your inputs before invoking "onSubmit" */
    <form onSubmit={handleSubmit(onSubmit)}>
      <input
        type="date"
        defaultValue={"2021-01-01"}
        {...register("exampleDate1")}
      />
      <input
        type="date"
        defaultValue="2021-01-01"
        {...register("exampleDate2")}
      />
      <input type="date" {...register("exampleDate3")} />
      <input type="date" {...register("exampleDate4")} />

      <input type="submit" />
    </form>
  );
}
```

- defaultValue can't use Date object, not related to hook form
- if you need complex parse/transform field level data use a controlled component and wrapped with controller

**Comment by bluebill1049** [comment]
- first issue:

```tsx
<input
  type="date"
  defaultValue={new Date(2022, 8, 1)}
/>
```
<img width="485" alt="Screen Shot 2022-08-17 at 5 03 39 pm" src="https://user-images.githubusercontent.com/10513364/185055813-bf135424-b738-4012-877d-0767c5706d03.png">

not related to hook form

- second issue 

```tsx
exampleDate3: Date | string;

exampleDate3: "2021-01-01",
```

I would prefer to stick with string for native input if you find that's hard to meet your requirement. use controlled component and that's what their strength at and you can be wrapped with `controller/useContorller` to simply collect data.

**Comment by tomoyukikino** [comment]
> first issue

I think you are right.

> second issue

Got it, I understood that defaultValue in HTML <input> element of type="date" cannot set default useForm props of defaultValue.

> I would prefer to stick with string for native input if you find that's hard to meet your requirement. use controlled component and that's what their strength at and you can be wrapped with controller/useContorller to simply collect data.

Thank you.
I could implemented by A as per your comment.

**Comment by tomoyukikino** [comment]
@bluebill1049 
hi, I can displayed useForm props defaultValue by controller.
thanks for your advice.

https://codesandbox.io/s/gallant-feistel-lo9jdm?file=/src/App.tsx
