### ISSUE TITLE
formState.dirty not working with useFieldArray async reset API

### ISSUE THREAD

**Issue by tomas-c** [react-hook-form/react-hook-form#881]
**Describe the bug**
formState.dirty differs depending on whether the data vas initialized via defaultValues or via reset() function.  This makes it difficult to handle async-loaded data.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-fkg1y
2. Append one item
3. Remove the appended item
4. Observe state is incorrectly set to dirty=true

**Expected behavior**
formState.dirty should be false

**Comment by bluebill1049** [comment]
This one is working, take a look : https://codesandbox.io/s/react-hook-form-usefieldarray-1m4b0

it didn't work correctly because in my example there is `math.rand()`

**Comment by bluebill1049** [comment]
i will re-open if you verify this is still an issue.

**Comment by tomas-c** [comment]
Ah, missed the rand() when I copied the codesandbox but it doesn't seem to be the main cause. It happens in the modified sandbox that you posted above so still an issue.

**Comment by bluebill1049** [comment]
I see the error is around append, remove fields right? in terms of onBlur it's working as expected.

**Comment by bluebill1049** [comment]
i think this fixes it: https://codesandbox.io/s/react-hook-form-usefieldarray-1m4b0

**Comment by tomas-c** [comment]
> I see the error is around append, remove fields right? in terms of onBlur it's working as expected.

dirty setting after onBlur works if append/remove is not done

> i think this fixes it: https://codesandbox.io/s/react-hook-form-usefieldarray-1m4b0

yup, the new changes seem to have fixed this

**Comment by bluebill1049** [comment]
> > I see the error is around append, remove fields right? in terms of onBlur it's working as expected.
> 
> dirty setting after onBlur works if append/remove is not done
> 
> > i think this fixes it: https://codesandbox.io/s/react-hook-form-usefieldarray-1m4b0
> 
> yup, the new changes seem to have fixed this

so it's working as expected?

**Comment by tomas-c** [comment]
On 4.6.2 it doesn't work, on the local react-hook-form version from `./src` in https://codesandbox.io/s/react-hook-form-usefieldarray-1m4b0 - it works

**Comment by bluebill1049** [comment]
oh cool, i will patch with what i did in local.

**Comment by bluebill1049** [comment]
made a beta version for the fix: react-hook-form@4.6.3-beta.1
