### ISSUE TITLE
issue: the cloneObject function does not copy the object properly. #2

### ISSUE THREAD

**Issue by jeremy93-2008** [react-hook-form/react-hook-form#8811]
### Version Number

7.34.0

### Codesandbox/Expo snack

https://codesandbox.io/s/morning-brook-xr2vil?file=/src/index.ts

### Steps to reproduce

[cloneObject](https://github.com/react-hook-form/react-hook-form/blob/111c2b651c876086e264279895425d0556598913/src/utils/cloneObject.ts#L5)

cloneObject doesn't take in account Map Object
1. Go to codesandbox
2. Look at the console log, we can see how the cloneObject function behave

### Expected behaviour

When I retrieve data from getValues I expect to get the value that I set on defaultValue.
That probably a regression bug, as when I use the v.6 it's work as expecxted.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for the issue report on this, could you provide your usage? This clone method is mainly used for form-related objects and we are not extending it to be a complete clone method to cover all different types.

**Comment by jeremy93-2008** [comment]
Basically we using it to getValues across different component inside a FormProvider, so in our case one of our fields are a Controller that have as a defaultValue a Map Object, a so when we try to get him outside the Controller, through the getValue we get a empty object instead of a Map object.

**Comment by bluebill1049** [comment]
Thanks for the detail. At the moment `Map` type is not supported, you can consider sending a feature request for that.
