### ISSUE TITLE
`shouldFocusError` feature doesn't work with MUI TextField component 

### ISSUE THREAD

**Issue by AlexKrupko** [react-hook-form/react-hook-form#8812]
### Version Number

7.34.0

### Codesandbox/Expo snack

https://codesandbox.io/s/priceless-https-2npify?file=/src/App.tsx

### Steps to reproduce

The first invalid field is not focused if I use RHF with MUI TextField. However, the inputRef is bound correctly and field is focused when I trigger `focus` method manually from the `error.ref` object. Please take a look at provided CodeSandbox example. 

Could you confirm this is a bug of if I do something wrong? 
Thanks. 

### Expected behaviour

Text input should be focused.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
make sure your component is not getting mount and unmount as this is not an hook form lib issue, working example: https://codesandbox.io/s/damp-water-co2nc2?file=/src/App.tsx

**Comment by Moshyfawn** [comment]
So, here's what's happening: you have the `isSubmitting` state `true` when the form's being submitted, which prevents RHF from focusing your input

**Comment by Moshyfawn** [comment]
@bluebill1049 do you think we can wait for the `isSubmitting` state to be `false` before focusing a faulty input?

Basically, we need [these lines](https://github.com/react-hook-form/react-hook-form/blob/b41c4401d9924480f678806a9fe0b89ec57c2628/src/logic/createFormControl.ts#L1050-L1055) to come after `isSubmitted` becomes `false`

**Comment by bluebill1049** [comment]
@Moshyfawn sure if you want to send a PR on this, but I doubt it would make difference as re-render will flush after the focus event.

**Comment by Moshyfawn** [comment]
> @Moshyfawn sure if you want to send a PR on this, but I doubt it would make difference as re-render will flush after the focus event.

I see what you're saying, @bluebill1049!

I'll think about it for a bit.

Meanwhile, @AlexKrupko, I'd suggest to look into setting your input as `readOnly` or utilizing `disabled` `fieldset` to set a bulk of `TextField`'s to `readOnly`

**Comment by AlexKrupko** [comment]
Hi guys, 
First of all thank you for the quick response. 
Yes, the reason was the input is disabled in the moment when you try to focus it. 
I tried to use `readOnly` instead of `disabled` as you suggested and it works as expected. Of course, it provides a different visual styling but `shouldFocusError` is working. 
Thanks
