### ISSUE TITLE
issue: Breaking changes after migration from 7.28.1 to 7.29.0, defaultValues transform MyClass => Object

### ISSUE THREAD

**Issue by davydspotnana** [react-hook-form/react-hook-form#8817]
### Version Number

`7.29.0+`

### Codesandbox/Expo snack

...see steps...

### Steps to reproduce

When I pass custom class instance as `defaultValues` and then getting in from values i expect to get class instance,  but after update to `v7.29.x` it started to convert instance to `Object` 

```tsx
import React from 'react';
import { render } from '@testing-library/react-native';
import { useForm } from 'react-hook-form';
import { View } from 'react-native';

class MoneyUtil {}

const TestComp = () => {
  const money = new MoneyUtil();

  const { getValues } = useForm({
    defaultValues: {
      money,
    },
  });

  return <View testID="form" constructorName={getValues().money.constructor.name} />;
};

test('should', () => {
  const { getByTestId } = render(<TestComp />);

  // v7.28.1 work well, 
  // BUT v7.29.0 return `Object`
  expect(getByTestId('form').props.constructorName).toBe('MoneyUtil'); 
});
```

### Expected behaviour

The davalut values won't be converted to object as it was in previous versions

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
From [the RHF docs on the `useForm` hook usage](https://react-hook-form.com/api/useform/#props):
> Avoid including custom object into the defaultValues. eg: moment, luxonas those will lead to unexpected result during internal object clone process.

This was a fix to RHF behavior; custom classes are not supported
