### ISSUE TITLE
`shouldFocusError` doesn't work if `shouldUnregister: true`

### ISSUE THREAD

**Issue by AlexKrupko** [react-hook-form/react-hook-form#8825]
### Version Number

7.34.0

### Codesandbox/Expo snack

https://codesandbox.io/s/determined-mcclintock-mej81m?file=/src/App.js

### Steps to reproduce

Focus on first invalid field is not working if `shouldUnregister` option is enabled for the form.  There is the following object in the `error.ref` field instead of reference to input element - `{name: "test"}`. 
Probably it depends to concurrent mode introduced in React 18 because before I didn't noticed that error.

### Expected behaviour

Input should be focused.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is an issue only related to strict mode, `useEffect` gets called twice under `StrictMode` which results in the component being treated as unmounted, we may have to consider removing `shouldUnregister` prop in the next major version, and developers would have to unregister those input manually.
