### ISSUE TITLE
issue: remove function in useFieldArray work incorrectly when using with react-transition-group

### ISSUE THREAD

**Issue by Mikhail1920929** [react-hook-form/react-hook-form#8826]
### Version Number

^7.34.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-q47zj?file=/src/ArrayComponent.js

### Steps to reproduce

1. Go to [https://codesandbox.io/s/react-hook-form-usefieldarray-forked-q47zj](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-q47zj?file=/src/ArrayComponent.js)
2. Click on 'SETVALUE' --> 2 rows will be added
3. Click on 'SUBMIT' --> display alert with 2 rows of data
4. Click on 'REMOVE' at row 2nd (last row) --> row 2nd will be deleted
5. Click on 'SUBMIT' --> display alert with 2 rows of data. The row 2nd is still in the form state

### Expected behaviour

When call remove([last index]), the last item in the array will be deleted in form state. I can't find a way to animate the addition or removal of list items with this or any other library

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
#6075

**Comment by Mikhail1920929** [comment]
> #6075

So what's the bottom line? The problem remains and worries a lot of people. How to animate a list?
