### ISSUE TITLE
issue: Dirty check not working for useFieldArray after calling resetField

### ISSUE THREAD

**Issue by stijnvanderlaan** [react-hook-form/react-hook-form#8827]
### Version Number

7.34.0

### Codesandbox/Expo snack

https://codesandbox.io/s/usefieldarray-dirty-state-m71hdz?file=/src/App.tsx

### Steps to reproduce

1. Go to 'https://codesandbox.io/s/usefieldarray-dirty-state-m71hdz?file=/src/App.tsx'
2. Click on 'resetField("fields")'
3. Update ANY value in input
4. Dirty stays FALSE

### Expected behaviour

I expect the dirty state to be true.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`resetField` only works for an individual field not a group of fields.

**Comment by stijnvanderlaan** [comment]
Oh right I understand, thanks for explaining.
