### ISSUE TITLE
issue: isSubmitting is set to true, when submitting invalid form, isValid ===false

### ISSUE THREAD

**Issue by bryantobing12** [react-hook-form/react-hook-form#8828]
### Version Number

7.34.0

### Codesandbox/Expo snack

https://stackblitz.com/edit/react-ts-c6fkz5?file=App.tsx

### Steps to reproduce

1. Go to 'stackblitz link for reproduction'
2. Open `console` to check `isSubmitting` status 
3. Click submit with all input set empty.

### Expected behaviour

I want to disable all the inputs when `user` submit the form which means `isSubmitting` status,

The issue is since `isSubmitting` is set to true, even when the form is invalid because of the validation,
every input will lose focus.

What I understand is that the form should not be start submitting if there's an error or, `formState: { errors }` object is not empty

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/commit/f17a7a9fd31a5711d6648c27ed5b4bc26656c5bb

**Comment by bryantobing12** [comment]
> [f17a7a9](https://github.com/react-hook-form/react-hook-form/commit/f17a7a9fd31a5711d6648c27ed5b4bc26656c5bb)

how can I test this?

**Comment by bluebill1049** [comment]
revert the fix.

**Comment by bryantobing12** [comment]
Because the fix has reverted, what would be the possible solution for this issue?
