### ISSUE TITLE
issue: useFieldArray change is not applied to dirtyFields

### ISSUE THREAD

**Issue by flo5324** [react-hook-form/react-hook-form#8833]
### Version Number

7.34.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-and-dirtyfields-w1qe7y?file=/src/index.js

### Steps to reproduce

1. Delete the second item
2. Check dirtyFields value

### Expected behaviour

I might misunderstand how dirtyFields work, but when I delete an item, I expect the item to be gone from dirtyFields

### Relevant log output

```shell
fields [{"name":"useFieldArray","price":"1200","id":"15f823d7-6411-49f3-b526-d27fb0c17c16"},{"name":"useFieldArray2","price":"1200","id":"12d258cc-ba81-44e0-942c-5805e2630002"}] 
dirtyFields {} 

*delete*

fields [{"name":"useFieldArray","price":"1200","id":"15f823d7-6411-49f3-b526-d27fb0c17c16"}] 
dirtyFields {"test":[{"name":false,"price":false},{"name":true,"price":true}]}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`dirtyfileds` will always do a deep equal against your default values, so when you delete a row and it's not matching the defaultValues, they are marked as dirty.

**Comment by flo5324** [comment]
Ok so I do have misunderstood how it works
Thank you for your quick response !
