### ISSUE TITLE
issue: setError() causes isValid formState to change to 'false'.  Contrary to docs.

### ISSUE THREAD

**Issue by made-in-nz** [react-hook-form/react-hook-form#8836]
### Version Number

7.34.0

### Codesandbox/Expo snack

https://codesandbox.io/s/seterrors-ib3pit

### Steps to reproduce

Follow the steps in the codesandbox
1. Change select value
2. customChange handler calls setError() setting an error on an unregistered field.
3. isValid formState changes to false. According to https://react-hook-form.com/api/useform/seterror this function has no affect on isValid formState. Therefore isValid at this point should be 'true'.
4. Click 'Clear Errors'. Errors are cleared, isValid formState remains 'false'. Note this is consistent with docs.

### Expected behaviour

Calling setError() should not trigger isValid formState to transition to 'false'.
Once isValid formState is false, how can I get it back to a state of 'true'?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/documentation/commit/c7ba257cf9bbb68aac174783bdfb48f19d6d14d9

**Comment by made-in-nz** [comment]
Thanks for the quick response @bluebill1049 

In my application, I have a custom resolver that sends data to the server for validation.  I am using setErrors() with an unregistered field to handle the situation where an error applies to the form as a whole rather than a specific field on the form.
Once I call setErrors(), I am unable to get the isValid formState back to 'true' even after my registered fields have no errors and the unregistered field's error is cleared with clearErrors().
Any thoughts on how to handle this?

**Comment by bluebill1049** [comment]
you should consider to have that logic inside your schema as well to reflect that "force" set isValid.

**Comment by made-in-nz** [comment]
Thanks @bluebill1049.  Another option, without a resolver, is to register the field to hold form-level error, and use resetField to clear the error.  This triggers revalidation of isValid formState.
