### ISSUE TITLE
Don't require event for handleSubmit

### ISSUE THREAD

**Issue by Motoxpro** [react-hook-form/react-hook-form#884]
When submitting outside of a '< form >' element, it would be nice to not have to carry around an Event to send to handleSubmit. https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L868

From what I can tell we do a check here

    if (e) {
        e.preventDefault();
        e.persist();
      }

and here:

       if (isEmptyObject(fieldErrors)) {
          errorsRef.current = {};
          await callback(transformToNestObject(fieldValues), e);
        } else {

and the signature for 'callback' is

    (callback: OnSubmit<FormValues>)

If we just did:

    e?: React.BaseSyntheticEvent,

instead of

    e: React.BaseSyntheticEvent,

It would allow people who are submiting remotely to not have a typescript error.
I could be totally off here. Just a thought.

Thank you so much for this amazing lib!

**Comment by bluebill1049** [comment]
Sounds good to me. Want to send a PR?

**Comment by bluebill1049** [comment]
Thanks for the PR.

**Comment by Motoxpro** [comment]
Thank you!! Happy for my first Open Source contribution to be on one of my favorite libraries!

**Comment by bluebill1049** [comment]
oh wow that's cool @Motoxpro super happy to hear that and thanks very much for your contribution.
