### ISSUE TITLE
issue: useFormContext() returns null when increasing version

### ISSUE THREAD

**Issue by ziperfal123** [react-hook-form/react-hook-form#8846]
### Version Number

7.34.1

### Codesandbox/Expo snack

-

### Expected behaviour

`useFormContext()` suddenly returns `null` when increasing the version from `7.33.1` to `7.34.1`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Please, provide a minimal reproduction codesandbox. Ignoring the issue template won't get you anything
#2848
