### ISSUE TITLE
Memory leak when use with virtual list.

### ISSUE THREAD

**Issue by Z2Y** [react-hook-form/react-hook-form#8853]
### Version Number

7.34.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-vlist-hook-form-demo-3pfe7e

### Steps to reproduce

1. Click add Item button, add some input fields
2. Scroll up and down, the number of detached input element grows up, not gabage collected.

### Expected behaviour

<img width="1778" alt="WeChat2e257d5d389fac3f7da2f1034f2cf448" src="https://user-images.githubusercontent.com/68933742/184584662-5f7ffd94-caf1-4962-a63f-4ad146639ecd.png">

<img width="1764" alt="WeChat69035f3587e76fb063d0155460953d8c" src="https://user-images.githubusercontent.com/68933742/184584352-6e34441f-c0de-42d5-bb75-114d735d3fc3.png">

The field.ref hold the ref detached input element,  so it can't be gabage collected.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`unregister` method will need to invoke for those inputs moved out of the screen, this is likely not the current scope of hook form and although you can try with `shouldUnregister: true`, it's always safer to use `unregister` to unregister those inputs.

**Comment by Z2Y** [comment]
if i unregister the field , the value will lost when i scroll back. and i can't get complete form value when submit. @bluebill1049

**Comment by bluebill1049** [comment]
if that's the case, then do not register the `ref`, so all the input reference doesn't get stored into your memory.

**Comment by Z2Y** [comment]
That may solve this problem, But i think the scope of ref function is incorrct and need fix.

**Comment by bluebill1049** [comment]
which function and scope? pr welcome.

**Comment by Z2Y** [comment]
https://github.com/react-hook-form/react-hook-form/blob/7bbf277f1762c3de874e88c879cc10eabc4e3acb/src/useController.ts#L132

**Comment by bluebill1049** [comment]
What's the issue such?

**Comment by Z2Y** [comment]
https://github.com/Z2Y/react-hook-form/blob/master/src/useController.ts
the arrow function hold the old field object because it inside a useCallback.

**Comment by bluebill1049** [comment]
can you create a pr and test it if that resolves the issue?

**Comment by Z2Y** [comment]
with  #8855 , https://codesandbox.io/s/react-vlist-hook-form-demo-fix-24f0i3
The number of detached input element keeps as the same number of fields off screen.  and not increace when scroll up and down.
it is possible set the ref to null after input unmount? that will solve the problem totally.

**Comment by bluebill1049** [comment]
Also you can use unregister method with option keepValue, so value will get retained.
