### ISSUE TITLE
issue: Async Validation does not set isValidating to true when pressing a submit button

### ISSUE THREAD

**Issue by vladnicula** [react-hook-form/react-hook-form#8854]
### Version Number

7.34.1

### Codesandbox/Expo snack

https://codesandbox.io/s/serene-smoke-osrluv?file=/src/CrossFieldValidationForm.tsx

### Steps to reproduce

1. Type some text in any field in the code sandbox example 
2. Inspect the console and notice **`isValidating` true** being logged.
3. Notice the submit input also disappearing as a a result of conditional rendering based on isValidating flag
4. Wait a couple of seconds for the async validation to complete
5. Notice the submit input appearing back and the log showing **`isValidating` true**
6. Submit the form
7. Notice that **`isValidating` true** even though the validation is running 

### Expected behaviour

When pressing the submit button, console should show **`isValidating` true** instead of **`isValidating` false** and the button should disappear from the UI until isValidating is back to false again. 

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Thanks for the report, could this issue be solved by using `isSubmitting`? We can easily update `isValiding` state during the submission, almost defeating the purpose of `isSubmtting`.

**Comment by vladnicula** [comment]
Neither`isSubmtting` nor `isValiding` work. I can update the example a bit

**Comment by bluebill1049** [comment]
Thanks for the update, If I am not misunderstanding the issue this is going to work out if the zodResolver is not returning a promise rather the inner function is doing a promise resolve.

what's in side hook form is waiting for the schema validation to be resolve then update `isSubmitting`:

```tsx
update(true)
await resolver();
update(false)
```

**Comment by vladnicula** [comment]
I tried a truly isolated example, without any additional resolver, the issue still persist. 
https://codesandbox.io/s/intelligent-thunder-b0kfut?file=/src/CrossFieldValidationForm.tsx:0-899

Can you confirm please @bluebill1049 that this should be fixed? I could give fixing this a try and come back with an update in a day of two if I succeed or not. 

```
import { useForm } from "react-hook-form";

export const SimpleAsyncValidatonForm = () => {
  const {
    register,
    formState: { isValidating, isSubmitting },
    handleSubmit
  } = useForm({
    defaultValues: {
      test: ""
    },
    resolver: async (data) => {
      await new Promise((resolve) => setTimeout(resolve, 2000));
      return {
        values: data,
        errors: {}
      };
    }
  });

  const onSubmit = (data: unknown) => {
    console.log("ready to submit", data);
  };

  console.log("isValidating", isValidating);
  console.log("isSubmitting", isSubmitting);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <h2>Is submitting? {isSubmitting.toString()}</h2>
      <h2>Is validating? {isValidating.toString()}</h2>
      <label>Test</label>
      <input {...register("test")} />
      {!isValidating ? <input type="submit" /> : null}
    </form>
  );
};
```

**Comment by bluebill1049** [comment]
that's a regression introduced in the last release, i am going to patch it now with `isSubmitting`. sorry about that.

**Comment by bluebill1049** [comment]
related #8828

**Comment by bluebill1049** [comment]
`isSubmitting` is patched: https://codesandbox.io/s/frosty-hill-85wtjr

**Comment by bluebill1049** [comment]
release the (reverted) patch: https://github.com/react-hook-form/react-hook-form/releases/tag/v7.34.2

**Comment by vladnicula** [comment]
Thanks for the quick update. Should we ignore the `isUpdatingFlag` in that case?

**Comment by bluebill1049** [comment]
I think perhaps it's a bit redundant considering the following

- `isSubmitting`: form level
- `isValidating`: field level

thanks for looking into this issue and even providing a PR as well 🙏 we can leave the PR as well if other users have similar demands we can consider merging it in.

**Comment by bluebill1049** [comment]
I am going to close this issue for now unless more users would like to making `isSubmitting` and `isValidating` both get updated to `true` during submission.

**Comment by Yankovsky** [comment]
Hey! I am a bit late for the discussion. I think it is expected behavior to set `isValidating` to `true` whenever validation is in progress. 
Also, @bluebill1049 said that
> `isSubmitting`: form level
> `isValidating`: field level
but as I understand there is no way to get `isValidating` state for individual fields, is that right?
