### ISSUE TITLE
useFieldArray errors empty after remove an item

### ISSUE THREAD

**Issue by goncalolourenco** [react-hook-form/react-hook-form#886]
**To Reproduce**
1. Go to https://codesandbox.io/s/use-field-array-issues-bcygg
2. Click two times on append item
3. Edit the age of all items in the UI to empty ('')
4. Check in the console logs that all fields now have an error associated
5. Click remove one item
6.  The errors field is empty now

**Expected behavior**
I expect the first item to be removed but the other ones to still have an error attached to them.
It seems all error state is being deleted along with the item

**Comment by bluebill1049** [comment]
There is a beta version, feel free to help on testing.

**Comment by bluebill1049** [comment]
The latest minor update have been released :) let me know if this resolves the issue.
