### ISSUE TITLE
issue: isValid (formState) is not  triggered when form is untouched.

### ISSUE THREAD

**Issue by Hasnat150822** [react-hook-form/react-hook-form#8877]
### Version Number

^7.25.0

### Codesandbox/Expo snack

no link

### Steps to reproduce

1. Set form values without touch the fields using setValue() methode.
2. Console isValid status on any click.
Note: Don't touch any form field during this test

### Expected behaviour

isValid form status should work without touching the form fields and should return true if form values exist.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Please, follow the #2848 issue template and provide **a minimal** codessandbox reproduction.
