### ISSUE TITLE
issue: isValidating doesn't work on the initial load with defaultValues

### ISSUE THREAD

**Issue by shuaiey** [react-hook-form/react-hook-form#8882]
### Version Number

7.31.2

### Codesandbox/Expo snack

https://codesandbox.io/s/isvalidating-on-init-93n9lq?file=/src/Form.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/isvalidating-on-init-93n9lq?file=/src/Form.tsx
2. You'll see `isValidating = false` & `isValid = false` on rendered app, and wait 2 seconds
3. You'll see `isValidating = false` & `isValid = true`

### Expected behaviour

First load with defaultValues, I'd expect to see `isValidating = true` & `isValid = false`

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
You don't kick in the RHF validation on first render. RHF doesn't auto-validate your `defaultValues` either. You should call the `triggrer` method on mount to properly run the validation.
```js
const {trigger } = useForm();

useEffect(() => {
  trigger()
}, [trigger])
```

**Comment by Yankovsky** [comment]
Not ideal, because before useEffect callback is executed form is considered to be valid.

**Comment by Moshyfawn** [comment]
> Not ideal, because before useEffect callback is executed form is considered to be valid.

`isValid` is `false` by default
