### ISSUE TITLE
issue: setValue doesn't set value to controlled input

### ISSUE THREAD

**Issue by maxim-ponomarev** [react-hook-form/react-hook-form#8883]
### Version Number

7.4.1

### Codesandbox/Expo snack

https://codesandbox.io/s/lively-sky-gjng7k?file=/src/App.js

### Steps to reproduce

1. Go to [Codesandbox](https://codesandbox.io/s/lively-sky-gjng7k?file=/src/App.js)
2. Click on "setValue"
3. Click on "Submit"
4. See only text input was set (select remain empty)
5. See submitted form data in the console: both `text` and `select` are set.  

### Expected behaviour

Both text and select inputs should be set when using `setValue`

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seMikel** [comment]
I believe you forgot to pass the field value to your Select.

**Comment by Upinwv** [comment]
[]()

**Comment by Moshyfawn** [comment]
You forgot to pass `field.value` to your controlled input
```diff
  <Controller
    name="text"
    control={control}
    render={({ field }) => (
-      <input ref={field.ref} defaultValue="" onChange={field.onChange} />
+      <input ref={field.ref} defaultValue="" onChange={field.onChange} value={field.value} />
    )}
  />
```

**Comment by maxim-ponomarev** [comment]
Thank you guys!
