### ISSUE TITLE
issue: Clone does not preserve prototype of object

### ISSUE THREAD

**Issue by vbudovski** [react-hook-form/react-hook-form#8884]
### Version Number

7.34.2

### Codesandbox/Expo snack

https://codesandbox.io/s/serene-neumann-jkqc86

### Steps to reproduce

Thanks for this fantastic library! This issue is related to #8811. Certain special cases have been added to the clone function, but I believe a more general solution is needed. Perhaps it's worth considering [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) instead?

Edit: turns out one of the limitations of `structuredClone` is that it doesn't copy the prototypes either. I've updated the sandbox to demonstrate it working with Lodash `cloneDeep`.

1. View the sandbox
2. Compare the output of the original and cloned object in the console
3. Notice that the prototype has changed

### Expected behaviour

Objects are cloned in a way that preserves their prototype.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for the issue, at the moment we are not going to cover complex clone as a prototype of the object, in fact, those complex object is best to be avoided as part of the form state. I did make an effort to expose those methods, however, this certainly makes API unintuitive and complex: https://github.com/react-hook-form/react-hook-form/pull/8032 maybe later on the track we will consider introducing that PR to the community.
