### ISSUE TITLE
issue: Zod validation not working with partial/deepPartial in zodResolver

### ISSUE THREAD

**Issue by BertVereecken** [react-hook-form/react-hook-form#8886]
### Version Number

7.34.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-with-zod-y4chnf?file=/src/App.tsx

### Steps to reproduce

My intention is to create a strict schema with Zod which we will use in our backend code.
Eg firstName must have length of 5. This is needed in our API backend.

**But**, we must be able to handle a temporary save of the form. So we will have for example 20 fields and we can only fill in 5 fields and click submit. 

1. Go to 'https://codesandbox.io/s/react-hook-form-with-zod-y4chnf?file=/src/App.tsx'
2. Fill in the **lastName** input field and click '**Submit**'
3. In the logs you will see the error object with 'firstName' in it, because it does not have 5 characters.

### Expected behaviour

The expected behaviour is that the form submission would **not** fail. It should show similar behaviour to ` optionalUserSchema.parse(optionalObject)`.

What am i doing wrong or how can I achieve what I want.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
You can notice, that with the uncontrolled **native web input** it's value is **never `undefined`**, but an `"" <empty string>`, **in case it's empty**. So, the validation schema throwing the `minLength` error in your case is correct: you're passing it an empty `string`, not `undefined`.

**Comment by Moshyfawn** [comment]
What you can do is to use controlled inputs instead. Here's a csb example: [link to csb](https://codesandbox.io/s/react-hook-form-with-zod-forked-ryx0ue?file=%2Fsrc%2FApp.tsx)

**Comment by Moshyfawn** [comment]
Additionally, check out this [Zod](https://github.com/colinhacks/zod) issue for some additional form handling context: colinhacks/zod#310
