### ISSUE TITLE
Can't wait for the yup context

### ISSUE THREAD

**Issue by Vandell63** [react-hook-form/react-hook-form#889]
** Thank i can't wait to use this library **
I'm a bit tired of formik for many things but also for the performance. In a huge forms i was a bit disapointed. Any way i would like to give a try to yours.

**Is your feature request related to a problem? Please describe.**
Yeah i can't inject specific external value into my yup schema to make more complicated conditional validation

**Describe the solution you'd like**
Just add all the missing property that yup can handle like the `context` property

Thanks in advance

**Comment by bluebill1049** [comment]
can you provide some more context on this issue? what do you mean external value into yup schema?

**Comment by Vandell63** [comment]
Thx :) , just there -> https://github.com/jquense/yup#mixedvalidatevalue-any-options-object-promiseany-validationerror
Need these options: 
```
Options = {
  strict: boolean = false;
  abortEarly: boolean = true;
  stripUnknown: boolean = false;
  recursive: boolean = true;
  context?: object;
}
```
Then you should let us add these options in your code 
-> https://github.com/react-hook-form/react-hook-form/blob/065ab57af99eab29eab8164a5686d77c32430978/src/logic/validateWithSchema.ts#L65
->   `values: await validationSchema.validate(data, { abortEarly: false }) `

**Comment by bluebill1049** [comment]
I think we may be going for another approach soon, which is not only support Yup. rather any schema lib. 
https://github.com/react-hook-form/react-hook-form/pull/817 you can have your own config there.

**Comment by Vandell63** [comment]
Yeah i saw this. Let's wait this. Thank you any way ;)

**Comment by bluebill1049** [comment]
cool i will prioritise that until those bugs are resolved.
