### ISSUE TITLE
issue: Enums as value accessors return 'never' TS type on valid paths.

### ISSUE THREAD

**Issue by heythisispaul** [react-hook-form/react-hook-form#8898]
### Version Number

7.34.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-typescript-forked-prolrd?file=/ExampleForm.ts

### Steps to reproduce

In the linked codesandbox, navigate to `ExampleForm.ts` and check the TypeScript error in the `setValue()` call.

### Expected behaviour

Hey there. When using TypeScript enums as keys for objects in the expected form type, valid enums are computed as a type of `never` when using their values as accessors when trying to access nested properties to get/set their values.

I found [issue #5115](https://github.com/react-hook-form/react-hook-form/issues/5115) where it appears a similar issue was found before. I was curious if there were any recommendations or changes since that discussion.

Thanks!

### What browsers are you seeing the problem on?

This is a Typescript/build related question.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for the issue report, just like the original issue, this is a limitation. However, we would be more than happy if anyone could provide a possible solution to this without introducing a breaking change.

**Comment by heythisispaul** [comment]
@bluebill1049 thanks for taking a look. I figured that was the case, just wanted to see if there was any update or recommendation. I appreciate the help.
