### ISSUE TITLE
Dynamic radio list with validation schema breaks on item delete

### ISSUE THREAD

**Issue by chrisdanek** [react-hook-form/react-hook-form#890]
**Describe the bug**
It seems removing one radio field in a list of radio lists with the same name `<input type="radio" name="foo" value="1" />` unregistered all other fields in the list, despite them still being present. 

**To Reproduce**
1. Go to https://codesandbox.io/s/nostalgic-currying-zoi3x
2. Click on 'Add Field' two times
3. Click on first radio button "1"
4. Click on "remove last field"
5. Click "submit"
4. Required field pops up despite radio "1" being selected

**Codesandbox link**
https://codesandbox.io/s/nostalgic-currying-zoi3x

**Expected behavior**
No validation error and value present in `getValues`, since I have an option selected. 

**Screenshots**
![Screenshot 2020-01-22 at 22 36 00](https://user-images.githubusercontent.com/1758834/72936510-9ccfa080-3d67-11ea-8751-c54f48d2cf9a.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.15.2
 - Browser: Chrome
 - Version:  79.0.3945.130

**Comment by bluebill1049** [comment]
maybe consider use array syntax? its pretty tricky to detect which one gets removed with same name.

eg: `name="test[0]"`

**Comment by SuperMartas** [comment]
If I use array syntax as you suggest, I can select all the radio buttons in the list at once which is not desired behavior.

**Comment by bluebill1049** [comment]
> If I use array syntax as you suggest, I can select all the radio buttons in the list at once which is not desired behavior.

what do you mean by that?

**Comment by SuperMartas** [comment]
Code like this:
```html
<input type="radio" name="test[0]" value="0">
<input type="radio" name="test[1]" value="1">
<input type="radio" name="test[2]" value="2">
...
```

...will allow the user to select (check) all the inputs, like this:
![image](https://user-images.githubusercontent.com/7558984/72943837-60a43c00-3d77-11ea-8c96-018406f5c197.png)

But in the example, the inputs are like this:
```html
<input type="radio" name="test" value="0">
<input type="radio" name="test" value="1">
<input type="radio" name="test" value="2">
...
```

...which allows the user to select (check) only one input at the same time, like this:
![image](https://user-images.githubusercontent.com/7558984/72943974-dad4c080-3d77-11ea-8abc-875897666454.png)

**Comment by SuperMartas** [comment]
https://codesandbox.io/s/nifty-colden-vjgro

**Comment by avtarnanrey** [comment]
Same issue here. I'm badly stuck because of this and can't go back from react-hook-form at this stage.

**Comment by bluebill1049** [comment]
I don't have time to looking into this issue for now until bugs on my hands gets resolved (useFieldArray). If anyone can help would be nice, otherwise you will have to wait. I only can do so much at a time.

**Comment by bluebill1049** [comment]
If someone have work around, feel free to submit a temp solution too.

**Comment by bluebill1049** [comment]
@avtarnanrey i will take a look this right after this bug, but at the same time i don't want to delay your project. feel free to use other lib for now to solve your problem. i will ping you once this issue is resolved.

**Comment by bluebill1049** [comment]
fixed: https://codesandbox.io/s/pensive-bouman-v1fzd

**Comment by bluebill1049** [comment]
please verify with this beta version: 4.6.3-beta.4

**Comment by avtarnanrey** [comment]
It is fixed. Thank you for your quick help @bluebill1049

**Comment by chrisdanek** [comment]
Works for me as well, thank you @bluebill1049 ! ❤️
