### ISSUE TITLE
issue: package.json exports field causes webpack to import multiple versions

### ISSUE THREAD

**Issue by giladv** [react-hook-form/react-hook-form#8911]
### Version Number

7.27.1

### Codesandbox/Expo snack

none

### Steps to reproduce

when this package is being used as a peer dependency (same version) on another package webpack will use different library types (esm and cjs) for the main bundle and the peer dependency (bundling multiple versions of this package essentially), which causes contexts to stop working.

### Expected behaviour

a single library type only should be bundled.

### Relevant log output

after much investigation is seems this definition on package.json is causing this behavior for some reason
```
"exports": {
    "./package.json": "./package.json",
    ".": {
      "import": "./dist/index.esm.mjs",
      "require": "./dist/index.cjs.js"
    }
  },
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
The current setup for the library export is correct and working for years, I would investigate your webpack config before we make any change to the build.
