### ISSUE TITLE
issue: old defaultValue is used when resetting form

### ISSUE THREAD

**Issue by schummar** [react-hook-form/react-hook-form#8921]
### Version Number

7.34.2

### Codesandbox/Expo snack

https://codesandbox.io/s/defaultvalue-react-hook-form-7-2pvhgy?file=/src/App.tsx

### Steps to reproduce

1. Change value in input or don't
2. Click "Update and reset"

### Expected behaviour

After reset, the input's value is the new default value ("default+"), but the old one ("default") is used instead.

It worked with v6:
https://codesandbox.io/s/defaultvalue-react-hook-form-6-ux8zcp?file=/src/App.tsx:0-790

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
expected behavior, your external react state has no effect on hook form internal form state values. if you want to update the value of the form, provide values to the reset's argument
