### ISSUE TITLE
issue: TS typings for useWatch() appear to be incorrect/incomplete

### ISSUE THREAD

**Issue by brombal** [react-hook-form/react-hook-form#8922]
### Version Number

7.34.2

### Codesandbox/Expo snack

https://codesandbox.io/s/boring-easley-wm4ijr?file=/src/App.tsx

### Steps to reproduce

Using `useWatch()` without a config parameter appears to allow you to watch the entire form for changes. The documentation for useWatch does not give any examples or mention this, but `useWatch.ts` does has several TS declarations of the `useWatch()` method, two of which are relevant: one in which the `name` key of the `props` argument is excluded; and the other which omits the `props` argument altogether. The comments above these declarations don't seem to adequately describe the differences, and the codesandbox links in the comments only give one example usage of useWatch (for watching a single field).

The *issue* here is that the TS typings appear to be incorrect, as it seems that `useWatch({})` and `useWatch()` both actually function the same way (during run-time), but the TS return typings of `useWatch()` (with no argument) is different from `useWatch({})` (with no `name` key). This causes TS to emit a type error on the returned value of `useWatch()`, preventing destructuring or usage of the form fields. My codesandbox example demonstrates this (you can see the TS error on line 12; but the code functions as intended).

### Expected behaviour

Assuming I haven't misunderstood the difference between `useWatch()` and `useWatch({})`, I believe the typings for useWatch are incorrect and should be fixed to make "no argument" more consistent with "argument with no `name` key."

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leapful** [comment]
Thanks for the patch. The PR is already merged.

**Comment by brombal** [comment]
Thanks, glad to help!
