### ISSUE TITLE
issue: error on array field is not cleared on change after submit when using a resolver 

### ISSUE THREAD

**Issue by slax57** [react-hook-form/react-hook-form#8927]
### Version Number

7.34.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-1d7qq6?file=/src/index.js

### Steps to reproduce

1. Notice form has 2 empty fields: `firstName` and `test.0.firstName`
2. Submit form
3. Notice the "ErrorDebugger" says: `Errors: {"firstName":{"type":"required","message":"This is required."},"test.0.firstName":{"type":"required","message":"firstName is required."}}`
4. Change `firstName` to something, like `'a'`
5. Notice the "ErrorDebugger" is updated right away and says: `Errors: {"test.0.firstName":{"type":"required","message":"firstName is required."}}`
6. Change `test.0.firstName` to something, like `'a'`
7. Notice the "ErrorDebugger" is **not updated right away** and **still says**: `Errors: {"test.0.firstName":{"type":"required","message":"firstName is required."}}`, although the field is now valid

### Expected behaviour

At step 7, I would have expected all errors to be cleared.
To me, the `test.0.firstName` field should behave exactly like the `firstName` field.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
The error object is incorrect data shape, as dot notation should convert to nest object type instead of flat object as indicated in your example.


```
{"test.0.firstName":{"type":"required","message":"firstName is required."}  //❌

{
  test: [{firstName: {....}}] //✅
}
```

**Comment by slax57** [comment]
Indeed when written this way it works perfectly. I probably got confused because of the way you register the array fields and [this part of the docs](https://react-hook-form.com/advanced-usage#ErrorMessages) saying you can access the errors using lodash get.
Btw is this documented somewhere? I tried to search for this info across the docs but I did not find examples of a custom Resolver with array fields. Maybe it could be worth it to add this example to the docs?

In any case, I'm really grateful @bluebill1049 for your answer.
I'll see if I can apply the same logic in our framework.
Cheers

**Comment by bluebill1049** [comment]
> Btw is this documented somewhere? I tried to search for this info across the docs but I did not find examples of a custom Resolver with array fields. Maybe it could be worth it to add this example to the docs?

thanks for the feedback, we can consider beefing up the current custom resolver example to include an array.
