### ISSUE TITLE
Nested form fields validation doesn’t get triggered with triggerValidation or on change

### ISSUE THREAD

**Issue by meverlee** [react-hook-form/react-hook-form#893]
**Describe the bug**
We are using nested form fields (e. g. "person.firstName") in combination with yup validation schemas. The validation gets triggered on onSubmit but it doesn’t work with `triggerValidation(['person.firstName', ...])`. `triggerValidation('person.firstName')` works but the validation doesn’t get triggered when changing the fields input value.

**To Reproduce**
1. Go to https://codesandbox.io/s/bold-murdock-pq8l2
2. Click on the button "triggerValidation(nested)
3. Open the console
4. See `errors` is still an empty object

**Codesandbox link**
https://codesandbox.io/s/bold-murdock-pq8l2

**Expected behavior**
I would expect that triggerValidation works with an array with nested form field names an that onChange triggers a revalidation.

**Comment by bluebill1049** [comment]
i think i may have fixed this last night: https://github.com/react-hook-form/react-hook-form/commit/065ab57af99eab29eab8164a5686d77c32430978

**Comment by bluebill1049** [comment]
can you help on testing if this beta solve the problem: react-hook-form@4.6.3-beta.3

**Comment by jefferson-gaivota** [comment]
It's still not working =/
