### ISSUE TITLE
issue: 

### ISSUE THREAD

**Issue by aruljayaraj** [react-hook-form/react-hook-form#8934]
### Version Number

7.34.2

### Codesandbox/Expo snack

https://codesandbox.io/s/infallible-dream-zgp1hs?file=/src/index.tsx

### Steps to reproduce

1. Go to the given Sandbox link
2. Select the **colors set 2** from the dropdown
3. Check the console on the onChange and onSubmit events.
4. Getting page responsive. (Uncaught Error: Maximum update depth exceeded.)

### Expected behaviour

I've recently upgraded the react-hook-form(latest) and Ionic(6.2.4) React (18.2.0) in my project and also updated the react version too.
I would like to get the selected colors during onChange. Uncaught Error: Maximum update depth exceeded.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Haven't we.. discussed this issue already?.. #7708

**Comment by Moshyfawn** [comment]
ionic-team/ionic-framework#20106
