### ISSUE TITLE
Don't return any as event type in onChange handlers

### ISSUE THREAD

**Issue by stefanpl** [react-hook-form/react-hook-form#8939]
Hello 👋

While the [documentation](https://react-hook-form.com/api/useform/register) states that the argument for the `onChange` and `onBlur` handlers will be `SyntheticEvent`, the type `RegisterOptions` just provides `any` at this point:

```typescript
// useForm.d.ts
export declare type RegisterOptions {
    // ...
    onChange?: (event: any) => void;
    onBlur?: (event: any) => void;
    // ...
}
``` 

**Describe the solution you'd like**
The argument for the event handlers should be typed more precisely. 

**Describe alternatives you've considered**
- Just working on the provided `any` type. Not safe.
- Casting the event to to the appropriate type everytime I use them. Not fun, and not really safe either.

**Comment by hornta** [comment]
> [bluebill1049](https://github.com/bluebill1049) closed this as [completed](https://github.com/react-hook-form/react-hook-form/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [3 days ago](https://github.com/react-hook-form/react-hook-form/issues/8939#event-7282668681)

Is it really completed though? I find myself with the same problem.
