### ISSUE TITLE
issue: isValid set to false and Errors object not updated when zod schema validation fails

### ISSUE THREAD

**Issue by HARAJLI98** [react-hook-form/react-hook-form#8940]
### Version Number

7.34.2

### Codesandbox/Expo snack

https://codesandbox.io/s/jovial-hoover-20bebx?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/jovial-hoover-20bebx?file=/src/App.js
2. Enter a password in the first text field
3. Watch the console as errors are output on input value change
4. Enter a matching password in the second text field
5. Watch errors go away
6. Add an extra character to the first password field
7. Watch console to see isValid set to false again and no errors.

### Expected behaviour

isValid is set to false and errors object is populated with zod schema error

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
The second field is not being checked against the validation schema by default. You need to provide a `deps` value to your field in order to check the dependent fields as well.
```js
{...register("password", { deps: "verifyPassword" })}
```
