### ISSUE TITLE
issue: Field is marked as required after setting value with controller

### ISSUE THREAD

**Issue by dawidurbanski** [react-hook-form/react-hook-form#8947]
### Version Number

7.34.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-value-required-with-controller-21vp6o

### Steps to reproduce

1. Go to https://codesandbox.io/s/react-hook-form-value-required-with-controller-21vp6o
2. Wait 3 seconds for faked api call to load
3. Click submit button
4. See that all three inputs are blocked with validation (required)

### Expected behaviour

Since all fields have value they should pass required validation (ideally the first one).

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
You never set the RHF values _(reset the form values)_. RHF doesn't do any magic to get the input value: you provide the default and the current field values.

In your case, with `async` values, you should [`reset`](https://react-hook-form.com/api/useform/reset) your form values when you get them

```
const { reset } = useForm()

useEffect(() => {
  if (team) {
    reset({
      teamName1: team,
      teamName2: team,
      teamName3: team,
    })
  }
}, [team, reset])
```
