### ISSUE TITLE
setValues does not update formState.touched if formState is not invoked

### ISSUE THREAD

**Issue by TheMeteoRain** [react-hook-form/react-hook-form#895]
Hello, again.

This is continuation on my last issue (https://github.com/react-hook-form/react-hook-form-website/issues/154). This one is similar and fixes itself if I call formState, but I would NOT want to do that until in submitHandler.

Original codesandbox: https://codesandbox.io/s/react-hook-form-set-inputselect-value-c46ly
Edited codesandox: https://codesandbox.io/s/react-hook-form-set-inputselect-value-u8sqi

Click the button that says 'Set all values' and submit and see that the formState.touched is empty. Even though we used setValue function to set those values. The second press of a submit does indeed show formState.touched updated, but it's the same problem, you have to invoke it once and then it understands.

My main problem, just like in the first issue, is that why I have to invoke formState? Can't it just update itself without invoking. This is the fix I would like to see.

**Comment by bluebill1049** [comment]
hey @TheMeteoRain,

thanks for provide the issue. I have updated the documentation to reflect the reason behind, and I don't have any plan right now to change that behaviour.

**Comment by TheMeteoRain** [comment]
That is fine. At least if documented right, it should not matter.

**Comment by bluebill1049** [comment]
Proxy is wrapped around formState, if you are not invoke `formState`, re-render is not necessary.
