### ISSUE TITLE
Request for support ',' sign in nested form value names. 

### ISSUE THREAD

**Issue by cmd030** [react-hook-form/react-hook-form#8955]
**Is your feature request related to a problem? Please describe.**

Field value does not processed when form values are nested and name have the special chart ",", but only when values are nested. Take a look at my examples on codesandbox.io. 

react-hook-form nested form values with complex names - https://codesandbox.io/s/react-hook-form-nested-values-with-complex-names-eye5iq?file=/src/App.tsx

react-hook-form values with complex names. ',' sign is processed fine - https://codesandbox.io/s/react-hook-form-values-with-complex-names-05gdg4?file=/src/App.tsx

**Describe the solution you'd like**
',' sign is processed fine in nested form value names.

**Comment by bluebill1049** [comment]
thanks for the feature request, a unique character such as `,` maybe it's wiser to be avoided and unless there is a robust use case we wouldn't like to further complicates path look get/set.

**Comment by cmd030** [comment]
Actually it is not a feature request, it is a bug report. That character
works is plain form values list, but doesn't in nested. That's it.
