### ISSUE TITLE
issue: FieldArray rules.validate type is overly broad

### ISSUE THREAD

**Issue by IanVS** [react-hook-form/react-hook-form#8969]
### Version Number

7.34.2

### Codesandbox/Expo snack

https://codesandbox.io/s/rhf-fieldarray-validate-sznb1h

### Steps to reproduce

I'm trying to use the new `rules.validate` from 7.34 (🙌 released just when I needed it!).  However, I find that the type of `values` provided to the validate function are very broad, and seem to not only include types from the provided fieldArray name, but other fields as well.  

### Expected behaviour

I expected that the type of the `value` for the validate function would be the same as what I provided to `FormValues`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
I'd move the issue to enhancements board and track the progress there, @bluebill1049

**Comment by bluebill1049** [comment]
I was having lunch, I am looking into this next after the last bug, this may be a limitation as I have entered exceed infinite type check before.

**Comment by Moshyfawn** [comment]
Yep, same. That's why I think we should pin it as enhancement. It's not gonna be easy to fix, I think

**Comment by IanVS** [comment]
I suppose the workaround for now is to use a type assertion through `any` back to what I expect?

**Comment by bluebill1049** [comment]
Let me get back to you @IanVS.

**Comment by Moshyfawn** [comment]
> I suppose the workaround for now is to use a type assertion through `any` back to what I expect?

I'd actually add a check like
```ts
if (Array.isArray(values)) {
  values.map(value => value.name)
                                          ^? { name: string }
}
```

To narrow down the type properly, without introducing `any`

**Comment by bluebill1049** [comment]
@IanVS should be resolved in the next release. Finally, that annoying bug and this type of enhanced resolved. thanks for the help @Moshyfawn have a good weekend guys.
