### ISSUE TITLE
issue: infinite renders with useFieldArray

### ISSUE THREAD

**Issue by LaserUnicorns** [react-hook-form/react-hook-form#8970]
### Version Number

7.34.2

### Codesandbox/Expo snack

https://codesandbox.io/s/naughty-curran-uwsfjm?file=/src/App.tsx

### Steps to reproduce

Open codesandbox and click 'add'

When using useFieldArray's rules field (even empty) + field with validation rules + subsription to form.formState.isValid browser hangs and in console you can see inf render logs
It seems that if I remove either of those 3 things all is working as expected

### Expected behaviour

Item should be added to form

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
It happens whenever you have the same validation fields for both `useFieldArray` and `Controller` rules in one form. In the OP's case, it's the `required` rule defined for both of them..
