### ISSUE TITLE
issue: useWatch triggers when two fields share a name

### ISSUE THREAD

**Issue by beinoriusju** [react-hook-form/react-hook-form#8979]
### Version Number

7.34.2

### Codesandbox/Expo snack

https://codesandbox.io/s/wo34ex

### Steps to reproduce

1. Have two fields **time** and **timetable** in your form. 

```js
const defaultValues =  {
        time: 0,
        timetable: {}
}
const { control, setValue } = useForm({
    defaultValues
})
```
2. Watch both fields independently with `useWatch`

```js
  const time = useWatch({
    control,
    name: "time",
    defaultValue: defaultValues.time
  });

  const timetable = useWatch({
    control,
    name: "timetable",
    defaultValue: defaultValues.timetable
  });
```
3. Count changes with useEffect

```js
  useEffect(() => {
    console.count("time");
  }, [time]);

  useEffect(() => {
    console.count("timetable");
  }, [timetable]);
```
4. Update time with `setValue('time', time + 1)` command.
5. Notice `timetable` updates just because it shares a name with `time`.
6. Notice how changing `timetable` to `xxx` does not trigger updates.

### Expected behaviour

`timetable` should not update just becouse it shares a common prefix with `time`

p.s. this happens only if `timetable` an object

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is expected behavior for how `useWatch` works.
