### ISSUE TITLE
Regression from 3.13.0, comparison between fields / custom errors / form sent with errors

### ISSUE THREAD

**Issue by Romcol** [react-hook-form/react-hook-form#898]
Hi,

Unfortunately I have encountered some regression trying to update the lib to the last version (4.6.2) :cry: .
I have mostly the same problems I had described in this issue (https://github.com/react-hook-form/react-hook-form/issues/99).

This sandbox works : https://codesandbox.io/s/react-hook-form-seterror-fj6ds?fontsize=14 (3.13.1)
this one doesn't : https://codesandbox.io/s/react-hook-form-seterror-fj1uh (4.6.2).

Issues are
- Form not being blocked when submitted.
- Errors reset when clicking out of the field (sort of randomly, happens most after the form has been sent once).

It's unfortunate because I needed that update, with the version 3.13.1 I had problem with watch() not being updated fast enough for comparison purposes, with the last version and the help of the Controller component I was able to do so.

Mainly, I'd like to be able to do comparison between fields or being able to set a global error on the form.

Thank you very much for your help,

**Comment by bluebill1049** [comment]
hey @Romcol i will take a look at this soon.

**Comment by bluebill1049** [comment]
> * Form not being blocked when submitted.

Both forms is blocked during my testing.

**Comment by bluebill1049** [comment]
> * Errors reset when clicking out of the field (sort of randomly, happens most after the form has been sent once).

How can reproduce this?

**Comment by Romcol** [comment]
Simply type something in the first field, something different is the second field and submit the form. (See https://drive.google.com/file/d/17ibeJZqLF_pJilVO3xVFTsn0soyIUmeK/view?usp=sharing). Thank you!

**Comment by bluebill1049** [comment]
thanks @Romcol i did the same, it was fine. i must have miss something here:
```
if (value === passwordConfirm) {
  return setError("passwordConfirm");
}
```

FYI: v4 you should use `clearError` instead

**Comment by Romcol** [comment]
Thanks for checking @bluebill1049, the error is still present with clearError unfortunately.

**Comment by bluebill1049** [comment]
I see the problem now. `setError` is not going to persist the error during submit, it was more of usage during `handleSumbit`. 

eg:
```
onSubmit={async () => {
  // if log in fail set an error use setError
}}
```

It's easier to maintain an error message with validate function in your example above. The reason setError is not persis error, because if I going for that route, then you will need to manually add and remove error with the combination of validating function. It's better to leave a single source of truth at the validating function or schema level. 

However, this also made me realize that the documentation needs to be improved for such behavior. I will update the documentation tonight.

**Comment by bluebill1049** [comment]
another case made me leave setError not persist. eg:

```
<input type="name" ref={register({ required: true })} />
```

then invoke 

```
setError('required', 'test', 'same')
```

then I am running into a question which error should the lib take. so at the end, I realize it's easier to have a single source, while `setError` is more of visual feedback to the user from async validation and ect.

**Comment by Romcol** [comment]
Ok, so we have to use `setError` twice, in the `onChange` for immediate visual feedback and in the handleSubmit. The thing is we also lose the error if we field is focused out (you can try with the second field). It's unfortunable that there is no simple way of comparing two fields... Have you got any recommandation for this ? Thanks

**Comment by bluebill1049** [comment]
use validate function 
```
register({
  validate: (data) => {
     return data !== getValues()['fieldB']
  }
})
```

**Comment by Romcol** [comment]
Ok thank you, it seems to work. Thought the error is not reset when we edit the first field.

(https://codesandbox.io/s/react-hook-form-seterror-fj1uh?fontsize=14&hidenavigation=1&theme=dark)

To reproduce 
- Fill first field
- Fill second field with different password
- Edit first field
=> The error is not reset (if we edit the second field it is reset)

I've tried triggering a validation on the onChange but the value is not updated yet so it doesn't work.
It might seem weird to process that way (editing the first field first instead of the second) but for date pickers it's pretty standard.

Cheers!

**Comment by bluebill1049** [comment]
> Ok thank you, it seems to work. Thought the error is not reset when we edit the first field.
> 
> (https://codesandbox.io/s/react-hook-form-seterror-fj1uh?fontsize=14&hidenavigation=1&theme=dark)
> 
> To reproduce
> 
> * Fill first field
> * Fill second field with different password
> * Edit first field
>   => The error is not reset (if we edit the second field it is reset)
> 
> I've tried triggering a validation on the onChange but the value is not updated yet so it doesn't work.
> It might seem weird to process that way (editing the first field first instead of the second) but for date pickers it's pretty standard.
> 
> Cheers!

your CSB is still using setError not validate function? You may want to use `triggerValidation` if you want to trigger another input's validation.

**Comment by Romcol** [comment]
Sorry, the CSB was not saved, you can try now. The thing is I don't know where I could use `triggerValidation` Thanks

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-seterror-35ii0

**Comment by Romcol** [comment]
Ok thanks, but for the component I'm trying to use (@material-ui/pickers embedded with `Controller`, Textfield with `Controller`) the value is actually changed after the `onChange()` is fired. See https://codesandbox.io/s/react-hook-form-seterror-pq5m2

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-seterror-uty9v

**Comment by Romcol** [comment]
Ok thx, I managed to do it like this https://codesandbox.io/s/react-hook-form-seterror-hkcm7, using validate as such
```
validate: value => {
                triggerValidation('passwordConfirm')
              }
```

**Comment by bluebill1049** [comment]
awesome :)
