### ISSUE TITLE
useForm result is not being memoized causing infinite looping while using useEffect

### ISSUE THREAD

**Issue by alexfgo** [react-hook-form/react-hook-form#899]
**Describe the bug**
When using "useForm" the methods returned appear not being memoized, since they are creating an infinite looping when placed in deps array inside useEffect.

**Comment by bluebill1049** [comment]
which methods?

**Comment by alexfgo** [comment]
Sorry, when I said methods I meant the result of "useForm". 
Let me explain better. 
Consider the following snippet of code:
 ```
const methods = useForm({
    mode: 'onBlur',
    defaultValues: connection,
    validationSchema: validationRules,
  });

const { handleSubmit, formState, setError } = methods;

useEffect(() => {
    if (errors) {
      errors.properties.forEach(item => {
        setError(item.property, 'required', item.message);
      });
    }
  }, [errors, setError]);
```

The "setError" function inside deps array is causing an infinite loop. 
The same occurs with "methods" object itself.

**Comment by bluebill1049** [comment]
I believe the methods object is at your app-level to `memo`, i will double check `setError`, if there is an issue with it, i will patch it :)

**Comment by bluebill1049** [comment]
actually take a closer look, it's not due to setError: useCallback(setError, []), because it's already been memo. it's errors object, which is a nest object and it's not going to work as a dependency. however you can use useDeepUseEffect, I believe there is such custom hook out there.
