### ISSUE TITLE
issue: useFieldArray prepend

### ISSUE THREAD

**Issue by iuvword** [react-hook-form/react-hook-form#8998]
### Version Number

7.34.2

### Codesandbox/Expo snack

Codesandbox

### Steps to reproduce

1. Go to '[Codesandbox](https://codesandbox.io/s/react-hook-form-usefieldarray-rules-forked-yxsbty?file=/src/index.js:2486-2490)'
2. Click on 'PREPEND11'
3. Scroll down to 'Line 90'
4. See error  prepend({}) but get {firstName: 'Bill', lastName: 'Luo'}, Looks like prepend defualtValues.test[0]

### Expected behaviour

prepend({}) get {}

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> Important: prepend data is required and not partial.

![Screen Shot 2022-09-07 at 6 14 20 pm](https://user-images.githubusercontent.com/10513364/188826668-f13c125a-9d14-45c9-88f0-734f08802fdd.png)

**Comment by iuvword** [comment]
why append({}) get {},  different from prepend

**Comment by iuvword** [comment]
![image](https://user-images.githubusercontent.com/24802853/188890540-b601e748-82ce-46a9-8970-38dfaf54521b.png)
look here, when the array changes, its index will also change, part of "name" is index, so the "defaultValue" maybe it's wrong
