### ISSUE TITLE
Message could be a function that takes the error

### ISSUE THREAD

**Issue by Calvein** [react-hook-form/react-hook-form#8999]
**Is your feature request related to a problem? Please describe.**
When validating field, we can add messages but they have to be a string, it would be great if they could also be a function in cases where the message is related to the error. e.g: showing the current length when validation `maxLength`.
We can pass the error to the message but it will be one render prior because of the nature of `register`:

Here's [a codesandbox example](https://codesandbox.io/s/react-hook-form-error-in-message-proposal-dnjlrs?file=/src/App.js):
```jsx
<input
  placeholder="Max 5 chars"
  {...register("example", {
    maxLength: {
      value: 5,
      message: `${errors.example?.ref.value.length}/5`
    }
  })}
/>
{errors.example?.message}
```

**Describe the solution you'd like**
I would like to be able to do this instead:

```jsx
<input
  placeholder="Max 5 chars"
  {...register("example", {
    maxLength: {
      value: 5,
      message: error => `${error.ref.value.length}/5`
    }
  })}
/>
{errors.example?.message}
```

**Describe alternatives you've considered**
It's not a deal breaker since the message can be customized at render but I find it nicer to keep my register & validation at the same spot.
```jsx
<input
  placeholder="Max 5 chars"
  {...register("example", {
    maxLength: 5
  })}
/>
{errors.example && `${errors.example?.ref.value.length}/5`}
```

**Comment by bluebill1049** [comment]
I think this will lead issue with the type check, you can use JSX with JS right now. however, in order to support both JSX(function) and string, users will have to do type assert for the message to determine if it's a string or JSX.

**Comment by bluebill1049** [comment]
Going to close this feature request happy to hear if anyone else has a solution to solve the type check issue which I pointed out above.
