### ISSUE TITLE
issue: `isDirty` not set to true when changing value and triggering `onBlur` (happens only first time)

### ISSUE THREAD

**Issue by jawadsef** [react-hook-form/react-hook-form#9002]
### Version Number

7.34.2

### Codesandbox/Expo snack

https://codesandbox.io/s/frosty-hill-u6tvl8?file=/src/App.js

### Steps to reproduce

1. Use the input element provided in the code-sandbox and change its value
2. Defocus the input to trigger the `onBlur` event
3. Check the dev tools, notice that it says `Nothing changed!`
4. Change the value again
5. Defocus the input to trigger the `onBlur` event
6. Check the dev tools, notice that it says `Something changed, make API request...`

### Expected behaviour

When I first change the value of the input and defocus the input, it should log `Something changed, make API request...` and not `Nothing changed!`.

The `isDirty` property stays `false` even after changing the value.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> formState is wrapped with a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to improve render performance and skip extra logic if specific state is not subscribed to. Therefore make sure you invoke or read it before a render in order to enable the state update.

https://react-hook-form.com/api/useform/formstate

see the commented code below

```tsx
import React from "react";
import { useForm } from "react-hook-form";

export default function App() {
  const {
    register,
    handleSubmit,
    // Read the formState before render to subscribe the form state through the Proxy
    formState: { errors, isDirty, isSubmitting, touchedFields, submitCount },
  } = useForm();
  const onSubmit = (data: FormInputs) => console.log(data);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input {...register("test")} />
      <input type="submit" />
    </form>
  );
}
```
