### ISSUE TITLE
issue: dirtyFields does not detect input type="email" as dirty after spaces insert change

### ISSUE THREAD

**Issue by Git-I985** [react-hook-form/react-hook-form#9018]
### Version Number

7.34.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-bug-09-09-2022-296w0m

### Steps to reproduce

Create default react app, add `react-hook-form` library as dependency, use `RHF` via `useForm` hook, register `<input type="email" .../>`, insert some spaces into input, check `useFormReturn.formState.dirtyFields.companyEmail`, its `undefiend`, dirty fields empty, it doesnt register anything

```js
import { useForm } from "react-hook-form";


export default function App() {
  const useFormReturn = useForm({
    mode: "onChange"
  });

  const { register } = useFormReturn;

  return (
    <div className="App">
      <form>
        <input
          type="email"
          inputMode="email"
          placeholder="type='email'"
          {...register("companyEmail")}
        />
      </form>
    </div>
  );
}

```

### Expected behaviour

`dirtyFields: {companyEmail: true}`

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> Make sure to provide all inputs' defaultValues at the useForm, so hook form can have a single source of truth to compare whether the form is dirty.

https://react-hook-form.com/api/useform/formstate

**Comment by Git-I985** [comment]
Thanks @bluebill1049! I needed to use touched Fields instead of dirty, how could I not notice this) thanks again

**Comment by bluebill1049** [comment]
no worries at all ❤️
