### ISSUE TITLE
issue: FieldPathByValue example has typescript error

### ISSUE THREAD

**Issue by niqqq25** [react-hook-form/react-hook-form#9021]
### Version Number

7.35.0

### Codesandbox/Expo snack

None

### Steps to reproduce

Run this code:

```typescript

import React from "react";
import {
  useForm,
  Control,
  FieldValues,
  FieldPathByValue,
  useController
} from "react-hook-form";

 function CustomFormComponent<
  TFieldValues extends FieldValues,
  Path extends FieldPathByValue<TFieldValues, Date>
>({ control, name }: { control: Control<FieldValues>; name: Path }) {
  const { field } = useController({
    control,
    name,
  });
}

function App() {
  const { control } = useForm<{
    foo: Date;
    baz: string;
  }>();

  return (
    <form>
      <CustomFormComponent control={control} name="foo" /> {/* no error */}
      <CustomFormComponent control={control} name="baz" /> {/*  throw an error since baz is string */}
    </form>
  );
}
```

Error
`Type 'Control<{ foo: Date; baz: string; }, any>' is not assignable to type 'Control<FieldValues, any>'.
  The types of '_options.resolver' are incompatible between these types.
    Type 'Resolver<{ foo: Date; baz: string; }, any>' is not assignable to type 'Resolver<FieldValues, any>'.`

### Expected behaviour

No typescript errors

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/zealous-feistel-r3z7fg?file=/src/App.tsx
