### ISSUE TITLE
issue: update a value by a button within a field array leads to wrong 'isDirty' and 'dirtyFields' form state

### ISSUE THREAD

**Issue by haagOS** [react-hook-form/react-hook-form#9032]
### Version Number

7.35.0

### Codesandbox/Expo snack

https://codesandbox.io/s/vigorous-nobel-15k8t7?file=/src/App.tsx

### Steps to reproduce

1. Go to the code sandbox
2. Click on 'delete' of an item
3. Click on 'undo' of the same item
4. See console output

### Expected behaviour

'isDirty = false' and 'dirtyFields = []'

### What browsers are you seeing the problem on?

Firefox, Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please refer to the `defaultValues` vs updated `values`.

```tsx
defaultValues: {
  data: [
    { name: "Item 1", isDeleted: false },
    { name: "Item 2", isDeleted: false }
  ]
}
```

![Screen Shot 2022-09-14 at 5 48 38 pm](https://user-images.githubusercontent.com/10513364/190093731-3a8996e7-6c98-48c1-b2a8-6bafc28144f2.png)

you can clearly observe the data diff from my screenshot above.

**Comment by haagOS** [comment]
Thanks for the fast response. I totally agree, that there is a diff. The question is: where is the 'id' property coming from and how am I supposed to update the field without 'introducing' the 'id' property, that is obviously causing the 'isDirty' to be 'true'.

As far as I can see, the 'id' originates from the useFieldArray's 'keyName'.

I tried different things, that all did not work
- update by `setValue` instead (see the first button that is commented out)
- update by `update` but omitting the 'id' (see the second button that is commented out)

**Comment by bluebill1049** [comment]
`As far as I can see, the 'id' originates from the useFieldArray's 'keyName'.` because item contains `id`, perhaps you want to omit it.

**Comment by haagOS** [comment]
Updated the codesandbox accordingly. Things seem to get a bit weird now. The 'id' property is gone as expected. However, now the 'name' property is being overwritten with a boolean value. But the 'isDirty' flag is correct despite `defaultValues !== updated values`

![grafik](https://user-images.githubusercontent.com/10416517/190144876-ac0bee9c-fc78-4fba-81cc-de177bac0c10.png)

**Comment by haagOS** [comment]
Ok. I have to take that back. That is how it's considered to be. So yeah it works. Thank you very much.

**Comment by haagOS** [comment]
As a side note: there is a better solution anyway:
Instead of cloning the `item` it is better to retrieve the 'current' data by ```getValues(`data.${index}`)```, otherwise changes made in other inputs may be lost/ out of sync.
Updated the codesandbox accordingly.
