### ISSUE TITLE
Rerendered radio inputs break react-hook-form validation 

### ISSUE THREAD

**Issue by denysonique** [react-hook-form/react-hook-form#9039]
### Version Number

6.15.8

### Codesandbox/Expo snack

https://codesandbox.io/s/fieldrefbug-7ygzhw?file=/index.tsx

### Steps to reproduce

1. Visit the sandbox page.
2. Wait 1s for the form to re-render
3. Click submit (without having a selected any of the radio buttons)
4. Page breaks

The fieldRefs array has empty keys upon re-rendering.
This causes `focusOnErrorField` upon validation to access properties of empty indeces of the array.

Using v7 the problem does not occur.

### Expected behaviour

Form should display an error without throwing an error.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
TypeError
field.options[0] is undefined
focusOnErrorField
https://7ygzhw.csb.app/node_modules/react-hook-form/dist/index.cjs.development.js:108:21
useForm/handleSubmit</<
https://7ygzhw.csb.app/node_modules/react-hook-form/dist/index.cjs.development.js:1249:21
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
This error overlay is powered by `react-error-overlay` used in `create-react-app`.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please consider to migrate to v7 as its already been resolved: https://codesandbox.io/s/fieldrefbug-forked-tcojfl?file=/index.tsx
