### ISSUE TITLE
ErrorMessage renders nothing unless an explicit error message is set

### ISSUE THREAD

**Issue by denizdogan** [react-hook-form/react-hook-form#904]
**Describe the bug**
`ErrorMessage` doesn't display anything when validation fails and no explicit error message has been set.

**To Reproduce**
```jsx
<input name="singleErrorInput" ref={register({ required: true })} />
<ErrorMessage errors={errors} name="singleErrorInput" as="p" />
```

**Codesandbox link**
[![Edit React Hook Form - ErrorMessage](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-hook-form-errormessage-12qjd?fontsize=14&hidenavigation=1&theme=dark)

**Expected behavior**
I expect the component to be rendered with a default error message instead of nothing.

**Screenshots**
![image](https://user-images.githubusercontent.com/50928/73079513-a4f12280-3ec4-11ea-929a-7b9c861c6cf2.png)

**Additional context**
If this is intended behavior, consider updating the documentation to describe this, because I had to debug the code in the browser to realize what the actual problem was.

**Comment by karland** [comment]
I believe, you would need to give it an error message, e.g.:

```JSX
<input name="singleErrorInput" ref={register({ required: "This is required" })} />
```

or in a different context for checking patterns: 

```JSX
<input
  name="singleErrorInput"
  ref={register({
    pattern: {
      value: /^(100|[1-9][0-9]|[0-9])$/i,
      message: "Invalid: number must be between 0-100"
    }
  })}
/>
```

See more examples here: https://react-hook-form.com/api/#register

But, I agree, it is a little tricky to find in the docs, and it also took me a little while to figure it out. But still, `react-hook-form` is great. Maybe some links in the https://react-hook-form.com/api/#ErrorMessage on how to setup error messages would help.

**Comment by denizdogan** [comment]
Yeah, didn't mean to complain about the library at all, more like help it get better since I enjoy it so much :) Thanks

**Comment by bluebill1049** [comment]
thanks @denizdogan next update will allow empty error message :) 

```
<ErrorMessage errors={errors} name="test">
  {() => <p>As long as there is an error</p>}
</ErrorMessage>
```

```
<ErrorMessage errors={errors} name="test" message="As long as there is an error" />
```

FYI @kotarella1110

**Comment by bluebill1049** [comment]
i am going to close this issue, as next release will have this feature above.

**Comment by kotarella1110** [comment]
@bluebill1049 Sorry for the late confirmation, I've been busy. Thanks 🙏

**Comment by bluebill1049** [comment]
no worries @kotarella1110 🙏
