### ISSUE TITLE
Issue: One field's value shows on another field if I render the fields conditionally.

### ISSUE THREAD

**Issue by ahamed** [react-hook-form/react-hook-form#9041]
### Version Number

7.20.5

### Codesandbox/Expo snack

https://codesandbox.io/s/keen-knuth-t6p7zw?file=/src/App.tsx

### Steps to reproduce

Create a form with three fields.
```ts
interface FormValues {
  optionA: string;
  optionB: string;
  track: boolean;
}
```

The two fields `optionA` and `optionB` will be rendering conditionally depending on the `track` value. If `track` value is `true` then the `optionA` will be shown, otherwise the `optionB` will be shown.

For getting the `track` value, I've used `form.watch()`
```ts
const track = form.watch('track');
```

For showing the `optionA` and `optionB` fields I've used `<Controller />` component from RHF. The rendering is okay and also the fields are changing depending on the `track` value.

```tsx
{track ? (
  <div>
    <label className="label">Option A</label>
    <Controller
      control={form.control}
      name="optionA"
      render={({ field, fieldState }) => (
        <input
          value={field.value}
          onChange={(e) => field.onChange(e.target.value)}
        />
      )}
    />
  </div>
) : (
  <div>
    <label className="label">Option B</label>
    <Controller
      control={form.control}
      name="optionB"
      render={({ field, fieldState }) => (
        <input
          value={field.value}
          onChange={(e) => field.onChange(e.target.value)}
        />
      )}
    />
  </div>
)}
```

### The problem
The problem is - if I write something on `optionA` field and then change the `track` field, then the `optionB` field appears but the `optionB` field also shows the values of the `optionA` which I entered earlier.

### Expected behaviour

After conditionally rendering one field, it should not shows another field's value.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please refer to this section in the doc under FAQ: https://react-hook-form.com/faqs#Whyisdefaultvaluenotchangingcorrectlywithternaryoperator
