### ISSUE TITLE
issue: Typescript types doesn't work with Schemas that use enums

### ISSUE THREAD

**Issue by jnavb** [react-hook-form/react-hook-form#9044]
### Version Number

7.35.0

### Codesandbox/Expo snack

https://codesandbox.io/s/cool-grass-z8dhy1?file=/src/App.tsx

### Steps to reproduce

When you use an schema with enums as their keys, the return type of useWatch is not correct

1. Go to the codesandbox
2. See comments for each useWatch

### Expected behaviour

Return type of `useWatch` should be the same in both scenarios

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/8898
