### ISSUE TITLE
How to pass regex rules to `pattern` as variable

### ISSUE THREAD

**Issue by maithuy** [react-hook-form/react-hook-form#905]
What is the correct way to pass regex value as variable in the pattern?

`ref={register({
                              required: "This field is required",
                              pattern: {
                                value: /`${item.regex}`/,
                                message: `${item.errorMessage}`
                              }
                            })}`

Thanks!

**Comment by bluebill1049** [comment]
hey @maithuy you should be able to pass in regex, your example above: you may want to do new `new Regex()` and pass your string

**Comment by maithuy** [comment]
hi @bluebill1049 I have a task to pass regex rule set by the api, if I hard code the regex, it works, but it doesn't work when I pass regex as variable.

**Comment by maithuy** [comment]
This works for me

`
ref={register({
                            required: "This field is required",
                            pattern: {
                              value: new RegExp(item.regex),
                              message: `${item.errorMessage}`
                            }
                          })}
`

Thanks so much! It would be very helpful if this info is available in the documentation.

**Comment by bluebill1049** [comment]
Glad it worked out :) it’s javascript related I think I will leave it out from the documentation. Basically if u want to pass as string you need to use new Regex 👌
