### ISSUE TITLE
useForm defaultValues -> cloneObject breaks Luxon DateTime's toJSON implementation.

### ISSUE THREAD

**Issue by rtmann** [react-hook-form/react-hook-form#9058]
### Version Number

7.35.0

### Codesandbox/Expo snack

https://codesandbox.io/s/intelligent-currying-r9hs5i?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/intelligent-currying-r9hs5i?file=/src/App.tsx
2. Enter a firstname and last name in the form and click submit
3. Look at the console output of codesandbox

As you can see in this code sandbox, when you create a model with some fields on it where one of those fields is a Luxon DateTime, it serializes properly until you bind it to a react hook form via default Values.

Once bound to a form via useForm, submitting the form has turned the DateTime into a plain old javascript object with no methods on it, there for it's toJSON implementation has been stripped off and now when you stringify it, it does not convert to an ISO String as expected.

This causes are date times to post to our API's as complex objects instead of simple ISO Strings, and none of the methods are on the DateTime anymore in the submitted form, so we have to manually recreate the DateTime's from the year/month etc data and then serialize them ourselves which is quite tedious.

I have download the source code and found the problem to be with "cloneObject"  which is located at https://github.com/react-hook-form/react-hook-form/blob/master/src/utils/cloneObject.ts

Reading this function I am not sure what isFunction(data[key]) is supposed to be doing, but that looks like where functions are being dropped off.

### Expected behaviour

I would expect React Hook forms to not modify my object at all when I use defaultValues, I want the object to be left untouched, accept for the fields I actually register.

### Relevant log output

```shell
--form data before serialization 
TestModel {firstName: null, lastName: null, birthDate: DateTime, constructor: Object}
--expected serialization of a date time, becomes an iso string 
{"firstName":null,"lastName":null,"birthDate":"2000-04-12T00:00:00.000-04:00"} 
because RHF cloneObject breaks DateTime, it now serializes to an object 
{"firstName":"sdsd","lastName":"sdsd","birthDate":{"ts":955512000000,"_zone":{},"loc":{"locale":"en-US","numberingSystem":null,"outputCalendar":null,"intl":"en-US","weekdaysCache":{"format":{},"standalone":{}},"monthsCache":{"format":{},"standalone":{}},"meridiemCache":null,"eraCache":{},"specifiedLocale":null,"fastNumbersCached":null},"invalid":null,"weekData":null,"c":{"year":2000,"month":4,"day":12,"hour":0,"minute":0,"second":0,"millisecond":0},"o":-240,"isLuxonDateTime":true}} 
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> Avoid including custom object into the defaultValues. eg: moment, luxonas those will lead to unexpected result during internal object clone process.

https://react-hook-form.com/api/useform

![Screen Shot 2022-09-19 at 4 31 58 pm](https://user-images.githubusercontent.com/10513364/190960999-694b8fee-9a50-4a3f-b004-0b0eb85b48e0.png)

**Comment by rtmann** [comment]
That's rather unfortunate.  I don't think I'm going to do that.  We have a huge project that binds large models to forms all the time.  I would not expect some "internal cloning" process to modify objects I pass to default values.  It's too much for us to fix right now so I guess I'll fork the project and change how cloneObject works.

**Comment by bluebill1049** [comment]
> Especially since I'm not even registering the fields that are being changed....

Then why it the part of the form `defualtValues` in the first place, consider merging data with submitted form values.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/pull/8032
