### ISSUE TITLE
Dynamic TS type for building dynamic form

### ISSUE THREAD

**Issue by maithuy** [react-hook-form/react-hook-form#906]
Hi, 

I'm rendering a form that the fields values are from an api json, what is the best way to create dynamic type?

(https://react-hook-form.com/get-started/#TypeScript)

`
type FormData = {
  firstName: string;
  lastName: string;
};
`

as this needs to be 

`
type FormData = {
  field1: string;
  field2: number;
  ....
  fieldn: any
};
`

Thanks!

**Comment by bluebill1049** [comment]
you will have to declare your form type. we don't support type check at runtime.

**Comment by bluebill1049** [comment]
also please consider asking question at our spectrum channel as some questions can be answered by the community.

**Comment by bluebill1049** [comment]
https://spectrum.chat/react-hook-form

**Comment by maithuy** [comment]
Thanks so much @bluebill1049

**Comment by DarkSouls101** [comment]
No worries 😉

**Comment by maithuy** [comment]
@DarkSouls101 Would you have any suggestions?

**Comment by maithuy** [comment]
@bluebill1049 I've made a CSB https://codesandbox.io/s/react-hook-form-basic-dxcc7

As you can see I populate the form fields based on the api data (UpdateModal.tsx), right now I have the type declared manually and it's not robust. Please let me know if you have any suggestions.

Thank you again.

**Comment by bluebill1049** [comment]
hey @maithuy i don't think there is alternative rather declare those types.
