### ISSUE TITLE
Support multiple validation mode for any field.

### ISSUE THREAD

**Issue by kmfb** [react-hook-form/react-hook-form#9064]
**Is your feature request related to a problem? Please describe.**

Since the react hook form set the Form Validation mode in the useForm's config, it can validate the whole form by the mode. But in some scenes, one of the fields need to be validated by multiple mode or other mode (not like the whole form config).

For example, the phone number can be validated by RE pattern in onChange mode, and it can be validated by calling back end api, which is should be onBlur mode. So I can't find any way to support this scene.

**Describe the solution you'd like**

If the rules props can be a array, that would be easy to add the validateTrigger into the config.
Juse like the [ant design's solution](https://ant.design/components/form/#Rule)

**Describe alternatives you've considered**

**Additional context**

**Comment by bluebill1049** [comment]
thanks for the feature request moved to project board.

**Comment by bluebill1049** [comment]
> For example, the phone number can be validated by RE pattern in onChange mode, and it can be validated by calling back end api, which is should be onBlur mode. So I can't find any way to support this scene.

you can consider the following example, same can be applied for `useController` for controlled component

```tsx
const { ref, name } = register('name')

<input ref={ref} name={name} onChange={(e) => { setValue(name, e.target.lvaue)}} onBlur{() => { trigger(name) }} />
```

**Comment by kmfb** [comment]
> > For example, the phone number can be validated by RE pattern in onChange mode, and it can be validated by calling back end api, which is should be onBlur mode. So I can't find any way to support this scene.
> 
> you can consider the following example, same can be applied for `useController` for controlled component
> 
> ```tsx
> const { ref, name } = register('name')
> 
> <input ref={ref} name={name} onChange={(e) => { setValue(name, e.target.lvaue)}} onBlur{() => { trigger(name) }} />
> ```

Thanks for your reply, the method you mention is also my workaround. By the way, validation with calling server api is not in the rule object, so i need to use the setError in onBlur method, which is different with your method.  

 ```tsx
const { ref, name } = register('name')

<input ref={ref} name={name} onChange={(e) => { setValue(name, e.target.lvaue)}} onBlur{() => { queryApi(url).then(res => {
  if (res.data.msg === 'error') {
   setError('name', { type: 'custom', message: 'custom message' });
}
}) }} />
 ```

**Comment by bluebill1049** [comment]
server error feature request: https://github.com/react-hook-form/react-hook-form/issues/7661

your usage can embed the validation into the validate prop

```tsx
register('test', validate: async() => {})
```

**Comment by kmfb** [comment]
> server error feature request: #7661
> 
> your usage can embed the validation into the validate prop
> 
> ```tsx
> register('test',  { validate: async() => {} })
> ```

But in this config, if the form validation mode is "onChange", it will trigger server error validation by onChange, which will request the server too many times.

**Comment by bluebill1049** [comment]
> > For example, the phone number can be validated by RE pattern in onChange mode, and it can be validated by calling back end api, which is should be onBlur mode. So I can't find any way to support this scene.
> 
> you can consider the following example, same can be applied for `useController` for controlled component
> 
> ```tsx
> const { ref, name } = register('name')
> 
> <input ref={ref} name={name} onChange={(e) => { setValue(name, e.target.lvaue)}} onBlur{() => { trigger(name) }} />
> ```

please refer to the above, setValue without `shouldValidate` won't trigger validation.

**Comment by kmfb** [comment]
> > > For example, the phone number can be validated by RE pattern in onChange mode, and it can be validated by calling back end api, which is should be onBlur mode. So I can't find any way to support this scene.
> > 
> > 
> > you can consider the following example, same can be applied for `useController` for controlled component
> > ```tsx
> > const { ref, name } = register('name')
> > 
> > <input ref={ref} name={name} onChange={(e) => { setValue(name, e.target.lvaue)}} onBlur{() => { trigger(name) }} />
> > ```
> 
> please refer to the above, setValue without `shouldValidate` won't trigger validation.

I got it, your workaround is better than mine, I'll try it in my project, thanks for your help.

**Comment by kmfb** [comment]
> > > For example, the phone number can be validated by RE pattern in onChange mode, and it can be validated by calling back end api, which is should be onBlur mode. So I can't find any way to support this scene.
> > 
> > 
> > you can consider the following example, same can be applied for `useController` for controlled component
> > ```tsx
> > const { ref, name } = register('name')
> > 
> > <input ref={ref} name={name} onChange={(e) => { setValue(name, e.target.lvaue)}} onBlur{() => { trigger(name) }} />
> > ```
> 
> please refer to the above, setValue without `shouldValidate` won't trigger validation.

But I want to validate value in onChange mode by pattern and validate in onBlur by request server's validation. If it use setValue in input's onChange method without triggering validation, which can't validate by pattern in onChange mode.

Just like below code, which the pattern valiation is never triggered in onChange mode, only trigger in onBlur, and I want is that onChange validation and onBlur validation both exist, and serve separately for different purpose(onChange for pattern, onBlur for async request).
```tsx
const { ref, name } = register('name', {
   pattern: {
            value: /\S+@\S+\.\S+/,
            message: "Entered value does not match email format"
   },
  validate: async() => {}
})

<input ref={ref} name={name} onChange={(e) => { setValue(name, e.target.lvaue)}} onBlur{() => { trigger(name) }} />
```

**Comment by kmfb** [comment]
> > > For example, the phone number can be validated by RE pattern in onChange mode, and it can be validated by calling back end api, which is should be onBlur mode. So I can't find any way to support this scene.
> > 
> > 
> > you can consider the following example, same can be applied for `useController` for controlled component
> > ```tsx
> > const { ref, name } = register('name')
> > 
> > <input ref={ref} name={name} onChange={(e) => { setValue(name, e.target.lvaue)}} onBlur{() => { trigger(name) }} />
> > ```
> 
> Thanks for your reply, the method you mention is also my workaround. By the way, validation with calling server api is not in the rule object, so i need to use the setError in onBlur method, which is different with your method.
> 
> ```tsx
> function App() {
>  const { ref, name } = register("name");
>  return (
>    <div className="App">
>      <input
>        ref={ref}
>        name={name}
>        onChange={(e) => {
>          setValue(name, e.target.value);
>        }}
>        onBlur={(e) => {
>          queryApi(url, e.target.value).then((res) => {
>            if (res.data.msg === "error") {
>              setError("name", { type: "custom", message: "custom message" });
>            }
>          });
>        }}
>      />
>    </div>
>  );
> }
> ```

Sorry, this reply's code that i pasted is not like my code. 


My code is like below, it should explain my use case, which i need two validation mode exist.
 ```tsx
 function App() {
  const { ref, name, onChange } = register("name", pattern: {
            value: /\S+@\S+\.\S+/,
            message: "Entered value does not match email format"
   });
  return (
    <div className="App">
      <input
        ref={ref}
        name={name}
        onChange={onChange}
        onBlur={(e) => {
          queryApi(url, e.target.value).then((res) => {
            if (res.data.msg === "error") {
              setError("name", { type: "custom", message: "custom message" });
            }
          });
        }}
      />
    </div>
  );
 }
```
