### ISSUE TITLE
issue: "move" in "useFieldArray" cause unexpected behavior to dirtyFields 

### ISSUE THREAD

**Issue by idanavr** [react-hook-form/react-hook-form#9065]
### Version Number

7.32.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-33bvpn

### Steps to reproduce

1. Click move
2. First item will move to the end (from "a, b, c, d" to "b, c, a, d")
3. See in console that all dirtyFields are true except test[1].checked which was unchecked before we used "move" button.

### Expected behaviour

Get empty dirtyFields since only order was changed.
If needed maybe add "isOrderDirty" field.

### Relevant log output

```shell
{
    "test": [
        {
            "name": true,
            "checked": true
        },
        {
            "name": true,
            "checked": false
        },
        {
            "name": true,
            "checked": true
        },
        {
            "name": false,
            "checked": false
        }
    ]
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Expected behavior as values is changed after the value (compare against defaultValues)
