### ISSUE TITLE
Pass a reset string type for `watch` callbacks

### ISSUE THREAD

**Issue by karbica** [react-hook-form/react-hook-form#9067]
**Is your feature request related to a problem? Please describe.**
When using `watch` there is a `type` parameter in the callback which indicates whether there was a `change` event. When resetting the form, the value is `undefined`. However, when using the `setValue` method to imperatively set a value, its event `type` is also `undefined`. It's not clear from within the scope of the `watch` callback whether the event triggering the callback subscription is from a `setValue` call or `reset` call. There are cases where I handle `reset` and `setValue` events within `watch` differently.

**Describe the solution you'd like**
A simple solution would be to issue a `reset` string as the type within the `watch` callback like is done with the `change` string. This makes it clear and concise that it was a true reset event and can be handled specifically without having to infer anything else.

**Describe alternatives you've considered**
At the moment, I would have to check if `value` and `type` are both `undefined` which I infer as a `reset` event. But this feels like a hack and it's not documented whether that's a reliable solution. And I haven't used this library deep enough to see if there is another case where both values could be undefined beyond resetting the form.

I've also tried setting `shouldTouch` and `shouldDirty` to `false` inside the `setValue` options hoping that it wouldn't trigger the `watch` callback but that wasn't the case. It does trigger the callback despite those options. I believe this is intended.

**Additional context**
I arrived at this feature request because I'm syncing the `form` instance with query parameters from the route. I'm using an effect to deserialize the query string into form state via `setValue`. But when the form changes, I use `watch` to serialize the form state back into the query parameters. But I want to clear the query parameters when the form is reset. This revealed to me that both `setValue` and `reset` pass an `undefined` value as the `type`.

**Comment by bluebill1049** [comment]
If i am understand correctly, you would like a event type provided to the watch callback?

**Comment by karbica** [comment]
Yes, here is an example:

```jsx
function Example() {
  const form = useForm();
  
  useEffect(() => {
    const sub = form.watch((state, { value, type }) => console.log(type));
    return () => sub.unsubscribe();
  }, [form.watch]);

  form.reset();
  // => This logs `undefined`. Could this log `reset` instead?

  form.setValue('a.b.c', 1);
  // => This also logs `undefined`.
}
```

Basically a string as the `type` parameter to indicate that reset occurred to the watch callback, like there is now for `changed`.
