### ISSUE TITLE
issue: formState.isValid true while formState.errors not null

### ISSUE THREAD

**Issue by JunyeongChoi0** [react-hook-form/react-hook-form#9068]
### Version Number

7.35.0

### Codesandbox/Expo snack

https://codesandbox.io/s/little-snow-05v345?file=/src/App.js

### Steps to reproduce

This form has dependent validation at second input. Validation of second input relies on the value of first input.
First input also has its own validation but does not relies on another input.

1. Enter '990228' at first input and '1231236' at second input
- this is random values that passes validation
- if you want to try with another value, enter any YYMMDD date into first input and a string '1XXXXXX(replace X with any number)' at second input. If validation fails, replace last number into another number. There must be a number that satisfies validation.
2. Change second input to '1231237'. (Validation fails)
3. Change first input to '990227'. (Validation still fails)
4. Change second input to original value '1231236'(Still fails, because first input is changed)
5. Change first input to original value '990228'
6. Now, `formState.isValid` is true but `formState.errors` is not null.

### Expected behaviour

`formState.isValid` is true, `formState.errors` is null

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
depend on validation should use `deps` or `trigger`

**Comment by JunyeongChoi0** [comment]
thanks for your answer @bluebill1049 ,
But I am using version 7.0.0. It don't have `deps` feature.
Any solutions?
