### ISSUE TITLE
yup number validation fails when field is not required

### ISSUE THREAD

**Issue by gentleShark** [react-hook-form/react-hook-form#908]
**Describe the bug**
I came across a validation problem for numbers using yup when the field is not required. The problem stems from an empty string being returned from the inputRef instead of null or undefined. The work around was to transform the empty string to "undefined" but it seems like in an ideal world, that transformation shouldn't have to take place. 
 
Validation code like this currently fails:
yup.number()..notRequired().integer().positive();

But transforming the empty string solves the problem:
yup.number().transform((cv, ov) => {
			return ov === '' ? undefined : cv;
		}).nullable().notRequired().integer().positive();

**To Reproduce**

**Codesandbox link**

https://codesandbox.io/s/react-hook-form-validationschema-3o4f5

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bluebill1049** [comment]
> The problem stems from an empty string being returned from the inputRef instead of null or undefined.

Thanks for your issue report. however, It's a false assumpting that the input number will return `null` or `undefined`. react hook form embrace native input and follow HTML input standard here.
