### ISSUE TITLE
issue: type event 'undefined' when call setValue with watch callback

### ISSUE THREAD

**Issue by ldenblyd** [react-hook-form/react-hook-form#9090]
### Version Number

^7.35.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-set-input-select-value-forked-lidjq9?file=/src/index.js

### Steps to reproduce
when i write in the input i have the event type 'change' 
but 
when i put elements with setValue i dont have the event type in my watch callback

EDIT: i dont know mabe is a feature request.

**Comment by bluebill1049** [comment]
`setValue` is not a event type
