### ISSUE TITLE
useFieldArray filtering out 0s from defaultValues

### ISSUE THREAD

**Issue by FedericoDiRosa** [react-hook-form/react-hook-form#9096]
### Version Number

7.36.1

### Codesandbox/Expo snack

https://codesandbox.io/s/long-sea-6iv01k?file=/src/App.js

### Steps to reproduce

See defaultValues and rendered inputs. Last one is omitted.

### Expected behaviour

All four fields rendered

### What browsers are you seeing the problem on?

Not relevant

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/usefieldarray

> Does not support flat field array.
