### ISSUE TITLE
issue: reset does not transform dot notated object to nested object, onChange does

### ISSUE THREAD

**Issue by bykof** [react-hook-form/react-hook-form#9103]
### Version Number

7.36.1

### Codesandbox/Expo snack

https://codesandbox.io/s/sad-http-ifkttc?file=/src/App.tsx

### Steps to reproduce

1. Wait for reset to set the form values
2. Result will be: `{"a.firstName":"Hello","a.lastName":"Test"}`
3. Enter some values into fields
4. Result is: `{"a.firstName":"Hello","a.lastName":"Test","a":{"firstName":"Hellof","lastName":"Test"}}`

### Expected behaviour

Firstly I would expect, that react-hook-form does not change the structure of my object.
It's somehow strange, that it changes dot notation to objects...

Anyway, if I expect, that react-hook-forms only works with nested objects and not dot notated objects, then it should also transform my dot notated object to a nested object when I use reset

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for the issue report, reset is required to supplied with partial form values, it doesn't support dot notation with string paring.

**Comment by bykof** [comment]
Worked, thanks and closed!
