### ISSUE TITLE
Support native validation props without native validation

### ISSUE THREAD

**Issue by rothsandro** [react-hook-form/react-hook-form#9104]
**Is your feature request related to a problem? Please describe.**
Let's say we have a form field with a required input. Validation by the library happens on submit and the user will see a custom error message, connected to the input via `aria-describedby`. Now, to improve both accessibility and UX, I would like to:

- show a "*" after the label text (as a visual indicator only, it will use `aria-hidden="true"`)
- a required attribute on the input element for screen reader users

This helps users to know that the input is required without showing an error message initially.

**Describe the solution you'd like**

**Option 1: New form option**

The `useForm()` options could be extended with a new property that will add the native validation properties to the inputs but will not trigger `reportValidity()`:

```ts
const {} = useForm({
  // Existing property: adds the validation props + triggers native validation
  shouldUseNativeValidation: true,

  // New property: adds the validation props but does not trigger native validation
  shouldAddNativeValidationProps: true,

  // Or something like that?
  shouldUseNativeValidation: true | false | 'propsOnly';
})
```

As an app developer we could check if the `register()` function returns a `required: true` property to know if the field is required (and if we need to add the "*" to the label).

**Option 2: New method to get the field options**

Currently there is no way (AFAIK) to access the field options (validation, ...). If the library would provide a new method to access them we could add the "*" + required attribute. That's a bit more work for app developers then the first option.

```ts
const { register, getField } = useForm();

register('name', { required: true });
getField('name'); // { required: true } // or something similar
```

**Describe alternatives you've considered**

- We can add a `required` attribute on our label component and input component, in addition to the one already provided to the `register` function. But this duplicates the config multiple times which I don't like.
- We can wrap the `useForm()` hook in our custom hook, return a wrapped `register` function that provides the native validation attributes automatically.

**Comment by bluebill1049** [comment]
thanks for detailed feature request, moving to project board.

**Comment by rothsandro** [comment]
@njanssoone Thanks, good idea (though browser support for `has()` is not that good yet) . I didn't know `aria-errormessage`, good to know 👍 

For screen reader users you can hide the "*": 

```css
content: '*' / '';
```

**Comment by njanssoone** [comment]
> For screen reader users you can hide the "*":
> 
> ```css
> content: '*' / '';
> ```

Thanks @rothsandro, I didn't know of this `/` syntax!
