### ISSUE TITLE
issue: `useFieldArray` may throw a focus related error on inputs conditionally rendering

### ISSUE THREAD

**Issue by WiXSL** [react-hook-form/react-hook-form#9105]
### Version Number

7.35.0+

### Codesandbox/Expo snack

https://stackblitz.com/edit/github-xh7glj?file=src%2Fposts%2FPostEdit.tsx,package.json

### Steps to reproduce

**Note**: The Stackblitz project is a copy from `react-admin` simple project (https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple?file=src%2Findex.tsx)

==> I realize this is a very simplistic report, If you need insight in `react-admin` usage of `react-hook-form` I could be of assistance

With version 7.34.2 works fine:

https://user-images.githubusercontent.com/8268610/192804473-e13fdeec-178a-452a-a246-d81d25b19c98.mov

With version 7.36.1 throws an error: (Important to hit ctrl + F5 after changing the dependency):

https://user-images.githubusercontent.com/8268610/192804508-a510fb10-e278-42b4-ad84-846a4a74d6da.mov

1. Go to 'Posts'
2. Click on 'Edit' button (any record)
3. Click on 'Add' button and select an item from the select input.
4. Click on 'Remove' button
5. Click on 'Add' button again
6. See error

### Expected behaviour

No error

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
<img width="1379" alt="Screen Shot 2022-09-29 at 8 36 15 am" src="https://user-images.githubusercontent.com/10513364/192900685-72d5fd3d-ecde-4d7d-bfdc-af9781532c39.png">

code is not related to react hook form, please follow up in react-admin instead.

**Comment by bluebill1049** [comment]
I am going to add a patch on this, in case it's related to `setFocus` method

**Comment by WiXSL** [comment]
Wow, that was fast!
Thank you! 👍
