### ISSUE TITLE
issue: `useWatch` is triggered if another field starting with the same name is changed

### ISSUE THREAD

**Issue by colin-delhalle** [react-hook-form/react-hook-form#9118]
We encountered this bug while using `useWatch` to update a field value based on another one of the form.

Not easy to explain, but the example is pretty straight forward.

If the watched field is named `comment` and the field `other` is updated, everything work as expected.
If the watched field is named `comment` and the field `commentA` (same start) is updated, an error is thrown.

### Version Number

7.36.1

### Codesandbox/Expo snack

https://codesandbox.io/s/optimistic-moser-h3n9gu?file=/src/App.js

### Steps to reproduce

1. Go to sandbox link
2. Uncomment line 16
3. See error

### Expected behaviour

`useWatch` should not be triggered, since the changed field (`commentA`) is not watched.

### What browsers are you seeing the problem on?

Firefox, Edge, not tested in other browsers

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
expected behavior, as in hook form input name support object donation with `.` symbol.
