### ISSUE TITLE
issue: using nested property as a register value for radio input does not work.

### ISSUE THREAD

**Issue by veselinovicdevelopment** [react-hook-form/react-hook-form#9120]
### Version Number

7.33.1

### Codesandbox/Expo snack

https://codesandbox.io/s/lucid-mopsa-wkjejq?file=/src/App.tsx

### Steps to reproduce

Please click one of radio and submit, and check result on console.

### Expected behaviour

it should change.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yonycalsin** [comment]
the problem is because you are overwriting the name of the input, the register function already does it for you.

fixed:

https://codesandbox.io/s/sad-babbage-vfo40m?file=/src/App.tsx

**Comment by bluebill1049** [comment]
thanks @yonycalsin that's correct
