### ISSUE TITLE
issue: Issue when type of the value is set to number

### ISSUE THREAD

**Issue by ravi-sankarp** [react-hook-form/react-hook-form#9124]
### Version Number

^7.35.0

### Codesandbox/Expo snack

https://codesandbox.io/s/stupefied-bush-j4mmk2?file=/src/App.js

### Steps to reproduce

1. Go to ' Go to the codesandbox link '
2. Type a number in input box starting with zero
3. Then click on submit and check the console
4. Check the console.If the first digit is zero it is not printed.

### Expected behaviour

The input should also take zero as a value.But it is not doing so.If the first digit is zero it is not read by react hook form.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
not an issue with hook form, native input will always return string unless `valueAsNumber`.

**Comment by ravi-sankarp** [comment]
But if the first value that we entered is zero it is not shown in the output log.

**Comment by Moshyfawn** [comment]
> But if the first value that we entered is zero it is not shown in the output log.

It's more of a HTML native `type="number"` input limitation. Numbers can't start with `0`. Try entering `012` into a native HTML `type="number"` input and incrementing the input value with up / down input buttons _(or up / down arrow keys)_: `0` will be removed from the input value.


For `OTP` or any other similar "number related" input, I believe, you want to the default `type="text"` input and add `pattern="[0-9]*"` to display the numeric keyboard on mobile device

**Comment by Moshyfawn** [comment]
> But if the first value that we entered is zero it is not shown in the output log.

In JS, numbers don't have leading `0`s. If you want a numeric keyboard on your mobile device for the OTP input, it's better to add `pattern="[0-9]*"` to your native HTML `type="text"` input  + validate it with RHF resovler as a `string`
