### ISSUE TITLE
useFieldArray remove method bug

### ISSUE THREAD

**Issue by michal-demecki-profil-software** [react-hook-form/react-hook-form#913]
**Describe the bug**
When using useForm with useFormArray, there is a bug with removing single element from array by it's index.

**To Reproduce**
1. Go to official useFormArray example sandbox: https://codesandbox.io/s/react-hook-form-usefieldarray-vy8fv
2. Add few elements with any values.
3. Delete any item by it's `Delete` button.
4. See error (all elements rerendered without any values)

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-vy8fv

**Expected behavior**
Other fields (but deleted) should stay unchanged.

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: 4.5.6 and latest(4.7.1)

**Comment by bluebill1049** [comment]
oops, I wasn't using the latest. thanks for the report. updated to the latest version. let me know if you still experience issues.

**Comment by michal-demecki-profil-software** [comment]
Somehow `defaultValue` make it works. Thanks!

**Comment by bluebill1049** [comment]
> Somehow `defaultValue` make it works. Thanks!

i update the version :) that's the real fix.
