### ISSUE TITLE
[Bug]: TypeScript errors type incorrect if value is an Object

### ISSUE THREAD

**Issue by yuvalbl** [react-hook-form/react-hook-form#9131]
### Version Number

7.36.1

### Codesandbox/Expo snack

https://codesandbox.io/s/nifty-tamas-3yrec8?file=/src/App.tsx

I base the reproduction on [#6523](https://github.com/react-hook-form/react-hook-form/issues/6523)
**It is exactly the same issue**, which still exist on v7.36.1
Related issues:
https://github.com/react-hook-form/react-hook-form/issues/6523
https://github.com/react-hook-form/react-hook-form/pull/6605
https://github.com/react-hook-form/react-hook-form/issues/6693

### Steps to reproduce
1. Make a form with 2 fields, a `firstName` (string) and an `amount` (Big Object)
2. extract the errors object from `formState`
3. see `errors.amount` type is nested (`DeepMap<Big, FieldError>`)

To make the issue easier to spot, I've added an "Error" component which should receive an `errors` props of type `Record<string, FieldError>` (which currently works only if "amount" is removed). See code sandbox above

### Expected behaviour

Since it's a leaf it should have a value of `FieldError`. Instead - all object properties have a value of `FieldError`

![image](https://user-images.githubusercontent.com/11487010/193563909-2a12469d-1086-4a5f-b46a-bbd00195de01.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yuvalbl** [comment]
@bluebill1049 
Why did you close this issue?
It has been marked as duplication, but I see no open issues in this regard, and the problem still exists

**Comment by bluebill1049** [comment]
There is impossible to inference the type here with my knowledge with your example, you can consider to use 

```tsx
interface ErrorProps {
  errors: FieldErrors<any>;
}
```
