### ISSUE TITLE
issue: array of checkboxes does not work with `Controller`

### ISSUE THREAD

**Issue by Ploppy3** [react-hook-form/react-hook-form#9133]
### Version Number

7.34.0

### Codesandbox/Expo snack

https://codesandbox.io/s/cranky-cloud-c8gxpe

### Steps to reproduce

Check the 4 checkboxes from top to bottom in the [provided example](https://codesandbox.io/s/cranky-cloud-c8gxpe).

### Expected behaviour

Controller should work just like `register` and not change the array of value to a boolean.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
you shouldn't mix native uncontrolled input with a controlled component, 

- register is applied to the uncontrolled component.
- controller / useController is applied to a controlled component.

If you decided to use controlled component, then consider building a `Checkboxes` component and hosting its own state inside the component and letting the controller collect and validate the input data.

Input Example: https://codesandbox.io/s/usecontroller-own-state-wncet2?file=/src/App.tsx

**Comment by Ploppy3** [comment]
I'm trying to avoid the use of checkboxes component to prevent rerenders. There may be something i'm not aware of though.

**Comment by bluebill1049** [comment]
> you shouldn't mix native uncontrolled input with a controlled component

please refer to my comments above. you should choose either uncontrolled or controlled

**Comment by Ploppy3** [comment]
If I understand, a controlled component will always set the value of the field and there is no way to mimic the uncontrolled checkboxes behavior (array of values) other than using a `Checkboxes` controlled component which if placed at the root of the form (my use case, since the checkboxes are scattered everywhere) will re-render the entire form.

If I'm right, the only solution is to:
- Use uncontrolled checkboxes inputs, but it prevents me from using the checkboxes of Chakra UI since it doesn't work (which may be an issue, I'm not sure, is it supposed to work ? I can create a reoro if needed)
- Change the structure of the data to work around the limitation

**Comment by bluebill1049** [comment]
> If I understand, a controlled component will always set the value of the field and there is no way to mimic the uncontrolled checkboxes behavior (array of values) other than using a Checkboxes controlled component which if placed at the root of the form (my use case, since the checkboxes are scattered everywhere) will re-render the entire form.

no, I don't think so. A controlled component can host an internal form state in whatever shape it wanted.

**Comment by bluebill1049** [comment]
any other questions before I close this issue?

**Comment by Ploppy3** [comment]
The controlled component would re-render the entire form each time a checkbox changes since its internal state would changes.

Basically it would look like this:

```jsx
<FormProvider>
  <form>
    <CheckboxGroup render={({ control }) => (
      <>
        <ControlledCheckbox control={control} name="foo" />
        <input {...register("bar")} />
      </>
    )} />
  </form>
</FormProvider>
```

What do you think ?

**Comment by Ploppy3** [comment]
But I can't afford to do that since my checkboxes are placed everywhere in between the various controls of the form. Is there a solution ?

**Comment by bluebill1049** [comment]
each `useController/Controller` does isolate its re-render, I am not sure what you mean you can't afford.

**Comment by Ploppy3** [comment]
I have to place all of the other controls in between the controlled checkboxes, that's where the issue comes from.

So in your example, since the state of the `Checkboxes` component changes, it will rerender and so will its children. So all the form controls will rerender.

I modified slightly your example:
https://codesandbox.io/s/usecontroller-checkboxes-forked-m0uz6c?file=/src/App.js

As you can see the text input rerenders when a checkbox changes.

**Comment by Ploppy3** [comment]
So the idea is to create a custom controlled `Checkbox` component and use it for every checkbox, it would receive the `value` to toggle into the array of values. this way only the checkboxes would rerender.

example: https://codesandbox.io/s/usecontroller-checkboxes-forked-m0uz6c?file=/src/App.js
