### ISSUE TITLE
issue: Removed fields reappear in form after an other append

### ISSUE THREAD

**Issue by rafael-zilberman** [react-hook-form/react-hook-form#9139]
### Version Number

7.1.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-item-reappear-after-remove-nkcoow

### Steps to reproduce

1. Go to [CodeSandbox example](https://codesandbox.io/s/react-hook-form-usefieldarray-item-reappear-after-remove-nkcoow)
2. Click on Delete on the second item in the list
3. Click on Append
5. Optionally repeat as many times as you like
7. See that the appended item has the same first and last name as the deleted item
8. Also, you may observer at the end of the page that the removed item is not included in the fields array but does included in the watch

### Expected behaviour

remove will *permanently* remove the item and "forget" the fields nested inside

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please update to the latest version instead supply with an issue related to v7 and report v6.
