### ISSUE TITLE
Strange behviour around reset

### ISSUE THREAD

**Issue by NickCullen** [react-hook-form/react-hook-form#914]
**Describe the bug**
We have a scenario where the form can be submitted and values (such as ID's of entities created server side) get populated and returned from the endpoint. For this reason, we change the state of the stored dto and intend to call form.reset(dtoValuesFromServer). 

Though, with our useEffect listening for changes on the dto state, the form becomes completely unresponsive from the get-go but the values being passed into form.reset are sane and expected.

**To Reproduce**
1. App.tsx line 54: form.reset(dto) will cause the form to be unresponsive
2. Commented out line 54
3. form responsive again

**Codesandbox link**
https://codesandbox.io/s/aged-pine-705x7?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
Form to be populated with values at the time of form.reset() and form to be responsive.

**Desktop (please complete the following information):**
-windows
- chrome
- version 79

**Additional context**
I originally started creating this sandbox to demonstrate strange behavior with syncfusion texxtboxcomponent and wanted to eliminate the possibility of the issue originating from the use form library then came across this bug. 
The weird behavior I have seen with this is that the textboxcomponent (syncfusion component) resets back to the first value populated when calling form.reset() but since the latest update with react use form, form.reset() now kills the entire form. 

But that may be a bug for a later date as I can't get to that step to be able to reproduce anymore :)

**Comment by bluebill1049** [comment]
line 54 is an empty line? you mean `form.reset(dto);`?

**Comment by NickCullen** [comment]
Odd, wasn’t empty when I was writing the repo. Steps! But yeah that line!

**Comment by bluebill1049** [comment]
your codesandbox is quite large and complex, i have created another small CSB, can you help on reproducing it here?

https://codesandbox.io/s/lucid-pine-z7nvs

**Comment by NickCullen** [comment]
Unfortunately only been able to get an hour on the laptop this morning I’ll see if I can get on it later but it may be unlikely

**Comment by NickCullen** [comment]
I simplified my solution as I'm used to TS sorry. 

additional steps really is that the first submit is returning an empty object and thereafter the form works. 

Looks like a [recent issue](https://github.com/react-hook-form/react-hook-form/issues/917) (just after mine infact) was raised with similar steps

https://codesandbox.io/s/aged-pine-705x7?fontsize=14&hidenavigation=1&theme=dark

**Comment by bluebill1049** [comment]
problem happened after `reset()`, all inputs reference gets reset. however in your component, they never gets re-registered again.

```
     useEffect(() => {
        console.log('log here')
        form.register({name: props.name});
        
        // return () => form.unregister(props.name);
    }, [form.register]);
```

**Comment by NickCullen** [comment]
How would I trigger a re-register? As the form all works as expected after hitting submit for the second time? (This triggers another form.reset as the state of the dto has changed)

Kind Regards,
Nicholas Cullen

**Comment by bluebill1049** [comment]
if you are using Controller or register using ref then they will get re-register again during re-render. 

if you try the following fix will fix your problem.
```
useEffect(() => {
        console.log('log here')
        form.register({name: props.name});
        
        // return () => form.unregister(props.name);
    });
```

you need to re-register your inputs after reset.

**Comment by NickCullen** [comment]
Sorry if I’m being daft here but that code is already in the custom components I’ve made?

I have the useEffect watching the form.register value - is this incorrect? I’ve seen it stated on the API docs. Like that.

**Comment by bluebill1049** [comment]
```
useEffect(() => {
        console.log('log here')
        form.register({name: props.name});
        
        // return () => form.unregister(props.name);
    });
```

look at my example above, i removed your `register` dependency. it's basically run each render, i am not recommending this, but just showing you why it's working without the dependency. otherwise it will only invoked once despite reset is invoked.

**Comment by bluebill1049** [comment]
Alternatively you can call register after reset

**Comment by NickCullen** [comment]
OK, that did seem to fix the issue but could possibly foresee a few issues:
1. Memory leaks by not returning a cleanup to unregister
2. constant registrations every render is going to cause performance issues on large forms?

It kind of feels like a hacky fix to mask the underlying bug.

But if this is genuinely the intended way to register custom components, then the [API docs for unregister](https://react-hook-form.com/api/#unregister) should be updated to demonstrate this?

**Comment by bluebill1049** [comment]
like i mentioned above, i am not recommending this approach and using Controller is better approach here.

> Memory leaks by not returning a cleanup to unregister
No, register method do check if input already get registered. useForm does clean up during unmount.

> constant registrations every render is going to cause performance issues on large forms?
Yes, definitely.

> It kind of feels like a hacky fix to mask the underlying bug.
There is no underlying bug in this issue as i have explained above, except the usage which is to find a way to re-register your inputs after reset.

> But if this is genuinely the intended way to register custom components, then the API docs for unregister should be updated to demonstrate this?
Feel free to submit a PR if you think anything can be improved, the doc is open sourced too.

**Comment by bluebill1049** [comment]
> Alternatively you can call register after reset

```
useEffect(() => {}, [
  reset()
  register() // re register inputs.
])
```

**Comment by NickCullen** [comment]
Ok thanks for the help!

This may be my lack of react knowledge but do you know of a way making deeply nested custom input components re register themselves gayer a reset?

Would I have to keep refs to them? I was hoping this library would prevent the need for refs.

**Comment by bluebill1049** [comment]
make your component wrapped with `Controller` (i know you heard me mention it 100 times) but i think it will make ur life easier. make sure your component expose `onChange`, because `Controller` will read your component's value via `onChange`.

eg:

```
function MyComponent({ onChange }) {
 return <input onChange={onChange} />
}

<Controller as={MyComponent} />
```

you can read more here: https://react-hook-form.com/api#Controller

**Comment by bluebill1049** [comment]
Thinking about this issue over the night, maybe we shouldn't reset all input reference. because nothing should be removed or added during reset action, which means you won't have to re-register inputs.

**Comment by NickCullen** [comment]
Yeah it does sound like a bug tbh. I would expect the values to reset to the default values passed into useForm or the values passed into the reset method if there were any

I wouldn’t of imagined unregistering the fields was a viable /expected solution to the reset function.

**Comment by NickCullen** [comment]
I don’t know what happened to your comment - perhaps you removed it?

Your comment came through via my email though hence the reply that looks out of context!

Either way, are you still in the same mindset?

**Comment by bluebill1049** [comment]
hey @NickCullen i removed, after testing there are  few issue caused by not reset the refs. remove those inputs reference was the correct decision.

**Comment by NickCullen** [comment]
No worries, is there a possibility of exposing an “on reset” callback or something we can listen for with a useEffect to be able to re-register our inputs upon reset?

**Comment by mikestopcontinues** [comment]
Just came across this problem myself. I have memoized `<Input form={form} />` that handle the registration, so when I call `form.reset()` in the upper component, all of the inputs go blank.

With `reset()`, I expected the default values to be reassigned without requiring the inputs to re-register. After all, the form already has a reference to those components. Why would it need to update them?

**Comment by mikestopcontinues** [comment]
Actually, it doesn't look like the memoization has anything to do with the issue. Devtools suggests `useForm` still sees all of the same fields and values. It even tracks future updates to my now-blank fields.

**Comment by bluebill1049** [comment]
@mikestopcontinues do you have a codesandbox i can take a look?

**Comment by mikestopcontinues** [comment]
Sure! Here's the dead simple version: 
https://codesandbox.io/s/react-hook-form-wizard-form-tj1n7
