### ISSUE TITLE
issue: input is unexpectedly focused when its type is "number"

### ISSUE THREAD

**Issue by yb9255** [react-hook-form/react-hook-form#9140]
### Version Number

7.36.1

### Codesandbox/Expo snack

https://codesandbox.io/s/input-type-number-focus-area-issue-syf92d?file=/src/App.js

### Steps to reproduce

https://user-images.githubusercontent.com/92532339/193754317-a9a31300-ecb8-4373-ad68-6f9725a41765.mov

1. Go to the sandbox
2. Click right side out of the input box. 
3. As you see, it is focused although I click outside of input.

(as far as I've found, it only happens when input type is "number" and browser is Chrome.)

### Expected behaviour

Input should not be focused when you click outside of input

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
not related to this library.
