### ISSUE TITLE
Should the 4.7.0 release have been a major release rather than a minor one?

### ISSUE THREAD

**Issue by kernow** [react-hook-form/react-hook-form#915]
Assuming you are using semantic versioning for this project, should the 4.7.0 release have been 5.0.0?

If I'm reading the changes correctly then

```jsx
<input
  name="test"
  ref={register}
/>
```

Needs to become

```jsx
<input
  name="test"
  ref={register({})}
/>
```

In order to maintain the same functionality.

If this is the case it looks like it's an incompatible API change which does not maintain backwards compatibility and would be more in line with a major release rather than a minor.

Would be great to have this change clarified as well as the versioning system use by this project.

FYI, this docs still mention `register` rather than `register({})`

Thanks

**Comment by bluebill1049** [comment]
it's only for useFieldArray. https://react-hook-form.com/api#useFieldArray 
other usage is not affected, it's not a breaking change as well, we always support `object` as the argument. This change is due to ref callback not going to reinvoked if not pass as a callback.

**Comment by kernow** [comment]
@bluebill1049 thanks for the quick response. We use dependabot to create our PRs for updates which includes a list of changes. I was reading through https://github.com/react-hook-form/react-hook-form/releases/tag/v4.7.0 which had the information.

I can see now it's nested under "😭fix useFieldArray", what threw me was the emoji at the start and I didn't notice it was nested so assumed this was a global change. 🙄 

Thanks for the clarification 👍

**Comment by bluebill1049** [comment]
no worries, thanks @kernow for the heads up for issue like this.  I will go improve the release note as well. thanks
