### ISSUE TITLE
getValues and submitting returns empty object on first click, returns correct values on second click

### ISSUE THREAD

**Issue by asherccohen** [react-hook-form/react-hook-form#917]
This could be a regression that was fixed here https://github.com/react-hook-form/react-hook-form/issues/222. 
I notice the same behaviour: submitting a form or calling getValues returns an empty object the first time, returns the correct values if pressed again.

I have a form which is build dynamically from data fetched externally.
I build my input components mapping them from a fieldType key in the response object.
I'm trying to build a multistep form, so field names SHOULD be different, but COULD be have the same name.
The way I have built my form is following the Smart Component suggestion and I register inputs with formContext.
I have tried using fieldArrays and I get the same result, so that is not a solution.

**Expected behavior**
Submitting or calling getValues() returns form values.

**Screenshots**
<img width="472" alt="Screenshot 2020-01-27 at 16 02 56" src="https://user-images.githubusercontent.com/34692625/73185524-84bca000-411e-11ea-9b96-c8bebaf12fc4.png">

**Desktop (please complete the following information):**
 - OS: MacOS catalina
 - Browser chrome and firefox
 - Version 4.6.2

**Comment by bluebill1049** [comment]
getValues() will always return after render(). it's uncontrolled unless you supply with defaultValues. Can you also provide a CSB with your issue, i can have a play and see if we are on the same page.

**Comment by asherccohen** [comment]
> getValues() will always return after render()

Could you elaborate a bit on this?not sure I'm following.
Will try to create a CSB with details but it's become quite a big set of components.
I'm cloning children here and there to make the form dynamic as the form renders in a "stepper" to handle multi-step questions. I've reduced re-rendering with useMemo, could it be that I'm blocking a render needed to getValues()?

**Comment by bluebill1049** [comment]
try to reproduce a small CSB to reproduce this issue, we can go from there.

**Comment by asherccohen** [comment]
Ok thanks @bluebill1049 so here's the codesanbox:

https://codesandbox.io/s/wizardly-pine-m95in?fontsize=14&hidenavigation=1&theme=dark

Must say, I found the problem but your help is still appreciated.
You will see that the code won't work, to make it work go to the Form component and comment out the <FormContext>

<img width="508" alt="Screenshot 2020-01-28 at 11 46 39" src="https://user-images.githubusercontent.com/34692625/73257342-e4b95200-41c3-11ea-89d0-6ec2e87ce4b0.png">

My guess is that it stopped working when I added <FormContext> to the Step component, why I did this?Because I need the buttons to be able to get partial values and store them in a common object (the stateContext), but the Stepper needs to be generic, never know if I need it somewhere else.

Now the new problem is that I can't submit the form. Taking a step back my design was to have a Form component that would pass the context down to its elements, then handleSubmit at the last step.

So the requirements are:
- generic Stepper that can be used without a form
- Form component that can be composed with dynamic Inputs/Checkboxes/etc..
- Save partial state in a common object that can be submitted at the last step.

Hope it's clear enough, and many thanks.

**Comment by bluebill1049** [comment]
I have made video the other day for building multiple steps funnel just like yours, maybe it's worth to check out.
https://www.youtube.com/watch?v=CeAkxVwsyMU

**Comment by asherccohen** [comment]
Cool, that's what I followed to get inspiration from. 
Things that differ from my approach:
I can't use little-state-machine in my project so I built stateContext which works brilliantly.
I couldn't use routes, therefore I built the Stepper.

Nothing wrong with that I assume, it's more the fact of making the buttons work with the formContext and be able to submit at the end.

Your thoughts?

**Comment by bluebill1049** [comment]
nothing wrong with your approach. as long as it works. I would host each form submitted data into a global context update with handleSubmit instead of using `getValuers()`. Your CSB is huge to review, i would expect a smaller version to reproduce the "issue".

**Comment by asherccohen** [comment]
That is actually a perfect suggestion. I can use submit to partially save the state, I'll find a way to hide the buttons when there's a form inside the step.

Thanks for brainstorming.

**Comment by bluebill1049** [comment]
i am going to close this issue now as it's not really a bug with the API. let me know how did you go with my suggestion too.

**Comment by asherccohen** [comment]
Your suggestion works perfectly, it reduces complexity and avoids having to use the formContext in the Stepper. I just had to find a way to tell the stepper not to show its default buttons but it wasn't too hard.

**Comment by asherccohen** [comment]
Now I can't set default values when I move back to a previous step...but that's another story...

**Comment by bluebill1049** [comment]
keep it simple (why i built RHF as well)
