### ISSUE TITLE
getValues() does not return same data structure as submit when used with fieldArray

### ISSUE THREAD

**Issue by theweiweiway** [react-hook-form/react-hook-form#918]
**Describe the bug**
Calling `getValues()` returns something different than when I submit the form. 

**To Reproduce**
Go to the sandbox link and click `submit`. Then click `get values`. You will see different data structures in the console

**Codesandbox link**
https://codesandbox.io/s/thirsty-dewdney-p20hb?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
They should return the same data structure

**Comment by bluebill1049** [comment]
you want to use `getValues({ nested: true })`

**Comment by theweiweiway** [comment]
Oh. Sorry, thanks! 
works great with
`getValues({nest: true})`

**Comment by codler** [comment]
Thanks @theweiweiway `getValues({nest: true})` is correct, I couldn't find it in the documentation.

**Comment by bluebill1049** [comment]
@codler that's for V5, for v6 is by default now.

**Comment by codler** [comment]
oh 😅 already at v6, im using 3.28.12

**Comment by bluebill1049** [comment]
@codler This doc: https://react-hook-form.com/v5/api should be still relevant.
