### ISSUE TITLE
issue: Validations being applied even if controlled fields are not registered

### ISSUE THREAD

**Issue by santanapaulo** [react-hook-form/react-hook-form#9187]
### Version Number

7.35.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-validationschema-forked-b500j3

### Steps to reproduce

1. Go to the sandbox link provided
2. Fill up the name input
3. Submit the form

### Expected behaviour

I believe we should validate the form since we don't have all the attrs registered, even they were inserted in the resolver schema.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
expected behavior: this is because form values will always submit to your schema to validate.
