### ISSUE TITLE
watch removed field on useFieldArray

### ISSUE THREAD

**Issue by mrasoahaingo** [react-hook-form/react-hook-form#919]
**Describe the bug**
watched values on array fields seemed to be reset to their default value since there is another rendering

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-o61yj
2. Add some amount on the first line
3. Append a new line and another amounts
4. Append a third line
5. Delete any line
6. See the subtotals being reset to 0
7. Change any amount, the subtotals will be recalculated

**Comment by bluebill1049** [comment]
If you want to consistently working the inputs value and fields. I would recommend you to use controlled inputs for such behaviour. 

`watch()` is made for watching inputs change which happens after inputs finished render and user interaction.

**Comment by bluebill1049** [comment]
In the meantime i will try to do a demo with uncontrolled FieldArray with your example, but i think it would be difficult.

**Comment by bluebill1049** [comment]
on top of my head here is an example: https://codesandbox.io/s/bold-sound-7lej4

**Comment by bluebill1049** [comment]
I will update the web documentation around this issue today as well.

**Comment by bluebill1049** [comment]
closing this issue and will continue on #924
