### ISSUE TITLE
Conditional validation

### ISSUE THREAD

**Issue by EkaterinaMozheiko** [react-hook-form/react-hook-form#920]
Is it possible to validate field depending on another field's value? I mean applying different regex patterns like in this example:

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-rhfinput-epkhl?fontsize=14&hidenavigation=1&theme=dark

**To Reproduce**
1. Select the Ten value in Select component
2. Type a text value into TextField component
3. Should be an error in error object but there is no error

**Comment by bluebill1049** [comment]
use `validate` and `getValues()`

**Comment by bluebill1049** [comment]
please consider using our spectrum channel, i believe similar question is asked there as well

**Comment by bluebill1049** [comment]
let me know if the above answer is what you after too.

**Comment by EkaterinaMozheiko** [comment]
Thank you! That's exactly what i was looking for!

**Comment by bluebill1049** [comment]
awesome to hear :)
