### ISSUE TITLE
issue: unable setFocus after reset

### ISSUE THREAD

**Issue by hakuvipz19x** [react-hook-form/react-hook-form#9205]
### Version Number

7.22.5

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-js-forked-o85pgl?file=/src/App.js

### Steps to reproduce

1. Go to codesandbox link
2. Uncomment setFocus('firstName') line
3. See error

### Expected behaviour

Can set focus 'firstName' input after reset data

### What browsers are you seeing the problem on?

Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`reset` will remove all input reference, inputs will only get focusable after the next re-render with all the inputs get re-regsiter again.
