### ISSUE TITLE
issue: generic error function

### ISSUE THREAD

**Issue by TkDodo** [react-hook-form/react-hook-form#9209]
### Version Number

7.37.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-generic-errors-6323w7?file=/src/App.tsx

### Steps to reproduce

You will see a TypeScript error in line 20 of the sandbox.

### Expected behaviour

No TypeScript error, unless I'm doing something wrong. Sorry if that's the case, happy to move this to a discussion.

I also created a [TypeScript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgMWiAyjAhjApnAXzgDMoIQ4AiKXLAYxgFoALCCAa0eLUoG4AofnQgA7AM7wA5rhgBRKGShwAvHAA8AFTi4AHnhEATMXABKuYVANqJUYCMkAaOAFcR7ERADuIgHw+AFPxwJGgAXChomDi4mj4OQXAiWCC44ey4AJ4QxHAa-ACUKj6ICQD0pXCA4NSA8H+Jyfh0WCIe8ABG+M5iuAZwMBBwdga6cAAG3FAgAHS4CtAjcNCj41N9znTM3cjAuAA2RiMJwDn+AIQny9OzUGIA2kkpALpwAGTPcKfnaJOr65vbe7d7rgngAfEEhCaTYBidDOVogYAwPAGfKFBAJYI0GDOKAiCFTGaKQH1B4AfkmKTEYiw0gSBEEmJkOLxriGxDs3QEBAE-HKvQ2cGkIhmwDocGE4hgUCwdng0MSXnFzCa0h6fVM5mgVhsdkccCaGR8gglEkFMnkigATCp1FpdPojBqLNqpbqnAa-IFgstwqgJlE8LF4sEgWlMtlcgUiiVgnyanUUuKmi04O0XF01f1BsMxl8fhsDFtdvtDsczhdCdBiY8Xm8Phd839i9XgXAwfioTC4Qikd1UTHgnAscyO5XrncSeTKdTacF6Qlh7iXIZcOzhQYubwgA) with just the function in question.

Interestingly, if I change the generic constraint:

```diff
- <T extends Record<string, unknown>>
+ <T extends Record<string, any>>
```

`name` can be used to index `errors`, but still cannot be used to index `touchedFields`.

Thank you for your help and this great os project ❤️ 

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
(property) touchedFields: Partial<Readonly<DeepMap<DeepPartial<T>, boolean>>>
Type 'keyof T' cannot be used to index type 'Partial<Readonly<DeepMap<DeepPartial<T>, boolean>>>'.(2536)

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
The field's `name` can be **a nested path**, not only a "simple" `string`. That's why there's a special `FieldPath` type for this case:
```
import type { FormState, FieldPath, FieldValues } from "react-hook-form";

const getError = <TFieldValues extends FieldValues, TFieldName extends FieldPath<TFieldValues>>(
  form: FormState<TFieldValues>,
  name: TFieldName
) => {
  if (!!form.errors[name] && (!!form.touchedFields[name] || form.isSubmitted)) {
    return <span style={{ color: "red" }}>{form.errors[name]?.message}</span>;
  }
};
```

**Comment by TkDodo** [comment]
Thanks so much ❤️ 

Here's also a working [typescript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnA3nAYtEBlGAQxhQBptgUAbAEwAViALcrS2gNUKoFcUBnOAF84AMygQQcAERQUhAMYwAtIwgQA1kpG4pAbgBQ++RAB2feAHMUMAKJRxUOAF44AHgAqrajU49+cFAAPEhMaAS8OLl4+ck82GgA5QhA0IJCwim8GGEYPCJ8o-gA+IoAKfThRXAAubFwCYhQ8+N9ootIKuBNklFq47ySU-QBKZyKMTuAROFKAQlntKBAAOhR7aD4AbW6UgF04ADIDmfnFlZgIbnlGFBp8rZ2UfYAfZ6ql5eA+PG4AIxBgDASDRhqN0J1KrIYNwoCZ3is1g4Hj1dgB+ZYpPh8QhWTqCTpQmFw7ihFAiYAmW76QS6IA) for anyone who stumbles upon this in the future.

**Comment by bluebill1049** [comment]
Thanks, @Moshyfawn, and the detailed issue report @TkDodo
