### ISSUE TITLE
How to set value to array input

### ISSUE THREAD

**Issue by RixBai** [react-hook-form/react-hook-form#921]
How to set value to array input in react hook form?

**Comment by bluebill1049** [comment]
normally i would close issue like this right away. i think you are pretty new, so please follow our issue template, if you have questions ask at our spectrum channel plz.

use this api, you can set value to array input https://react-hook-form.com/api#setValue

**Comment by RixBai** [comment]
I was trying to set the value to custom component I made.
But I found that in react-hook-form we can only set the value to native component.
I solved the problem with using Formik.

**Comment by bluebill1049** [comment]
> But I found that in react-hook-form we can only set the value to native component.

that's actually not true, we have `Controller` for set value for external controlled component while still minimised the amount re-render at form level, but happy for you to find the right solution to solve your problem.

**Comment by B-Esmaili** [comment]
You are so calm, so patient, so helpful. just thank you for the great library.

**Comment by bluebill1049** [comment]
> You are so calm, so patient, so helpful. just thank you for the great library.

You are welcome 🙏
