### ISSUE TITLE
Field array item id is changed when update method is used

### ISSUE THREAD

**Issue by davbrito** [react-hook-form/react-hook-form#9217]
### Version Number

7.37.0

### Codesandbox/Expo snack

https://codesandbox.io/s/cranky-kowalevski-622cst?file=/src/App.tsx

### Steps to reproduce

1. Go to the code sandbox
2. Click on the add button
3. Change the value of the type select
4. See that the component gets remounted indicated by the message on the console.

### Expected behaviour

The key of the array item shouldn't change by the `update` method of the field array.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
expected behavior the update field array will need to unmount and remount, if this is not your desired behaviour, use setVlaue to update each inputs.

**Comment by bluebill1049** [comment]
please refer to the doc as well

![image](https://user-images.githubusercontent.com/10513364/195725047-9654ea0b-2f86-4ba5-88d7-35803f1aa61b.png)

[let ](https://react-hook-form.com/api/usefieldarray)

let me know if you want me to add some more context in the doc as well, closing this issue tho.

**Comment by davbrito** [comment]
Thanks for the quick response. I didn't see that on the docs, so thanks for pointing it out.
I actually was already using `setValue` as a "workaround" to this.
