### ISSUE TITLE
issue: Component is not re-rendered after `setValue`

### ISSUE THREAD

**Issue by QzCurious** [react-hook-form/react-hook-form#9221]
### Version Number

react-hook-form: 7.25.3; react: 17.0.2

### Codesandbox/Expo snack

https://codesandbox.io/s/input-value-out-of-sync-pyxzeh?file=/src/App.tsx

### Steps to reproduce

1. Check the checkbox
2. SimpleInput is **unmounted**
3. `useEffect` is triggered and it `setValue("SimpleInput", "checked")`
4. Click console log button, the stored value for `SimpleInput` is `checked`
5. Uncheck the checkbox
6. SimpleInput is shown with text **checked**
7. The clean up callback of `useEffect` is triggered and it `setValue("SimpleInput", "unchecked")`
8. Click console log button, the stored value for `SimpleInput` is `unchecked`
9. Result: text in SimpleInput is differ from the text store in RHF

### Expected behaviour

After stored data is updated (`setValue`), it should trigger a re-render for the corresponding component (`useController`)

This problem is not occuring on react 16.12.0. It's happened on react 17 as well as react 18.

**NOTE**: Without unmounting `SimpleInput` could solve this problem.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Because you have unmounted `uncontroller`, so does its subscription. The `useEffect` callback will be invoking the subscription without `useController` being mounted and read for the listening. 

** Potentil Work around: **

- You can consider moving that `useEffect` into the child component, so it will guarantee fired after the subscription/useEffect, 
- As you have suggested above, without unmounting the child component

> This problem is not occuring on react 16.12.0. It's happened on react 17 as well as react 18.

I believe the current useEffeect execution is more accurate than v16.

**Comment by QzCurious** [comment]
Thanks for explaining.

Apart from that. Shouldn't `useController` sync with stored data once it is mounted? I'm not setting a `defaultValue` for it.

**Comment by bluebill1049** [comment]
> Apart from that. Shouldn't useController sync with stored data once it is mounted? I'm not setting a defaultValue for it.

it does, but your `setValue` call at useEffect callback/unsubscribe function is get lost because `useController` is not ready with the subscription due to unmount and remount.

eg:

1. unmount
2. serValue: called `useEffect` unsubscribe 
3. remount: called `useEffect` then subscribe ready

**Comment by bluebill1049** [comment]
for your reference why subscription was made at useEffect: https://github.com/react-hook-form/react-hook-form/issues/6830
