### ISSUE TITLE
useController & useWatch -> shallow copy breaks Luxon DateTime's prototype

### ISSUE THREAD

**Issue by doyoueventruck** [react-hook-form/react-hook-form#9222]
### Version Number

7.37.0

### Codesandbox/Expo snack

https://codesandbox.io/s/ancient-star-kqrt5s?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/ancient-star-kqrt5s?file=/src/App.tsx
2. Observe the DateTime printouts via JSON.stringify() at the bottom. The toString() implementation on the prototype calls toISO() for all three.
3. Change the DateTime via the MUI DateTimePicker.
4. Observe the printout again. The bottom two print the object as it's lost the prototype during the a shallow clone of the DateTime object for both `useController` and `useWatch`. The top value from `watch` does _not_ seem to have this problem.

### Expected behaviour

I would expect one of two things:

1. The behavior to be the same across `watch`, `useWatch`, and `useController`.
2. `useController` does not shallow copy the field value for prototyped objects, OR 
3. There is a property with `useController` that allows this to be turned off. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Expected behavior. It's a current package limitation. Refer to [`useForm` docs](https://react-hook-form.com/api/useform/#props):
> It's recommend to avoid including custom object which contains prototype methods as the defaultValues, such as moment, luxon and etc. Those type of an object will not be cloned internally.

We recommend keeping your form values simple

**Comment by doyoueventruck** [comment]
@Moshyfawn The documentation says those types of objects will _not_ be cloned internally.  I would expect that to hold true for `useWatch` and `useController`. However, those objects _are_ being cloned when returned by `useWatch` and `useController`. `watch` does not; this seems inconsistent at best.  Why does the behavior differ?

**Comment by doyoueventruck** [comment]
@bluebill1049 This is in the same vein as [#9058](https://github.com/react-hook-form/react-hook-form/issues/9058).

**Comment by bluebill1049** [comment]
> It's recommend to avoid including custom object which contains prototype methods as the defaultValues, such as moment, luxon and etc. 

Doc update, avoid those custom objects such as luxon or moment.

**Comment by arthurmmedeiros** [comment]
Is there any future plan to fix the integration of this lib with Luxon?

**Comment by bluebill1049** [comment]
@arthurmmedeiros It's better to supply a string of the actual date. with a complex object such as `luxon` or `moment` is almost impossible to measure against the dirtiness of the actual input within this generic library.

**Comment by doyoueventruck** [comment]
For complex objects (e.g. classes) like luxon `DateTime`, it seems like dirtiness could be determined using the object reference, no? Or at the very least optionally determined this way?
