### ISSUE TITLE
material-ui RadioGroup with Controller not updating visually

### ISSUE THREAD

**Issue by sterjoski** [react-hook-form/react-hook-form#923]
**Describe the question?**
Radio buttons with material-ui aren't updating visually, am I doing something incorrectly?
**To Reproduce**
1. Go to https://codesandbox.io/s/vigilant-chatterjee-mi4jc?fontsize=14&hidenavigation=1&theme=dark
2. Click on click on any radio button
3. Click on submit
4. See that the value is changed but the radio button isn't checked (the default value works tho)

**Codesandbox link**
 https://codesandbox.io/s/vigilant-chatterjee-mi4jc?fontsize=14&hidenavigation=1&theme=dark

**Comment by bluebill1049** [comment]
thanks for the issue report.

The problem is you are not matching your data type: string vs number.

`return parseInt(args[0].target.value);`
