### ISSUE TITLE
issue: useFieldArray elements persist after reset but with empty values

### ISSUE THREAD

**Issue by Nureckiy** [react-hook-form/react-hook-form#9257]
### Version Number

7.38.0

### Codesandbox/Expo snack

https://codesandbox.io/s/modest-sutherland-odi2nz?file=/src/App.tsx

### Steps to reproduce

If a default value for an array field is not specified when the form is initialized, the "reset" function clears the existing elements, but their number remains the same. If specify the default value as an empty array, the problem will be solved.

![ezgif-1-b4c6952b97](https://user-images.githubusercontent.com/17616120/197248815-b6b822bd-5abe-4267-9546-72ce6fa80705.gif)

### Expected behaviour

"Reset" should remove array fields

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Field array needs to be a non-flat array _(an array of objects)_ because of the fields ordering mechanism that needs to store an internal field `id` on a field object array. You need to provide a field array value of type array.

You can call it a design limitation.

**Comment by Nureckiy** [comment]
> Field array needs to be a **non-flat array** _(an array of objects)_ because of the fields ordering mechanism that needs to store an internal field `id` on a field object array. You need to provide a field array **value of type array**.
> 
> You can call it a design limitation.

I understand. I used the example from https://react-hook-form.com/api/usefieldarray/ in the codesandbox. The "items" array consists of objects with a "value" field. I've added a submit part that prints the results to the console to make the structure of the elements clearer: https://codesandbox.io/s/elegant-mountain-e3li10
![image](https://user-images.githubusercontent.com/17616120/197483667-568cbfac-c7da-4437-8940-45a12afd9823.png)

**Comment by Nureckiy** [comment]
@Moshyfawn Sorry for the annoying question, but I don't want to create a duplicate issue since this one is now closed. However, I'm afraid this behavior might happen in other cases. In fact, we use reset() function only when the user selects a different element to edit (or selects create mode), so we just call the method with the new default values ​​coming from the server. Since a reset doesn't completely clear the state, but only partially updates it, I am afraid that some data may leak between different unrelated records.

**Comment by bstro** [comment]
I'm also running into the issue @Nureckiy describes
