### ISSUE TITLE
issue: 

### ISSUE THREAD

**Issue by gioragutt** [react-hook-form/react-hook-form#9259]
### Version Number

7.34.1

### Codesandbox/Expo snack

...

### Steps to reproduce

![image](https://user-images.githubusercontent.com/13711224/197403160-a1b0ecc7-2472-47c4-b1de-07b6e809259d.png)

https://github.com/react-hook-form/react-hook-form/blob/a57ab09bcc15c5b0e6c285b1944e5b5e4f2ced59/src/logic/createFormControl.ts#L989

When passing `name=""` (basically empty string for name), we get an exception (we encountered it in a Storybook environment).

I traced it to the `ref` function returned from `useForm().register`, where indeed the `field` value is not checked (unlike in the body of `register` before returning the object).

### Expected behaviour

Invalid input should be handled, by either not throwing an error, or throwing a concrete and traceable error.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
The error is in the image of `Steps to reproduce`.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Please, follow the issue template and provide a minimal reproduction codesandbox. We can't debug an error without your form's code.
