### ISSUE TITLE
Calling reset() in onSubmit to clear the form leaves it in an inoperable state

### ISSUE THREAD

**Issue by rogerchi** [react-hook-form/react-hook-form#926]
**Describe the bug**
Using Yup as the validationSchema, call reset() in the onSubmit function.  The form successfully submits, but is not able to be submitted again if you refill the inputs.

**To Reproduce**
1. Fill in form
2. Submit
3. Fill in form again
4. Attempt to submit

**Codesandbox link**
https://codesandbox.io/s/new-tree-i91ut

**Expected behavior**
You should be able to re-use the form and submit another set of inputs.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by bluebill1049** [comment]
I see the problem now: https://codesandbox.io/s/autumn-paper-fonnt

because you didn't supply a `defaultValues` and reset with empty argument.

inside lib source code: 

`register: useCallback(register, [defaultValuesRef.current]),`.

so change your `reset()` to  `reset({})` will make it work. I will update the doc to reflect this issue too.

**Comment by maithuy** [comment]
@bluebill1049 The reset doesn't take effect if one of the fields has been pre-filled with known value so the users don't have to type in, and therefore there's no change in the defaultValues. Is there a way to reset the form manually? Thank you!

**Comment by bluebill1049** [comment]
@maithuy you have a codesandbox for this problem?

**Comment by maithuy** [comment]
@bluebill1049 I re-used the example above 
[https://codesandbox.io/s/happy-meadow-cq3kd](url)

Thanks.

**Comment by bluebill1049** [comment]
invalid link :(

**Comment by maithuy** [comment]
I've updated the CSB link again. Thanks very much for a prompt reply.

**Comment by bluebill1049** [comment]
```
reset({
      requiredField:''
    });
```

@maithuy
