### ISSUE TITLE
issue: using watch on a field that doesn't yet exist causes unexpected value to be returned

### ISSUE THREAD

**Issue by moseslecce** [react-hook-form/react-hook-form#9271]
### Version Number

7.38

### Codesandbox/Expo snack

https://codesandbox.io/s/trusting-glade-708s8c?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/trusting-glade-708s8c?file=/src/App.tsx
2. Click on the select box labelled "Choose me first" and select the option "Has Field Two"
3. The Field Two select box will now appear and it will have the value "c" selected (from the inline defaultValue attribute)
4. watched Field two value will be undefined, though we would expect to get the current value "c"
5. Pressing the submit button will cause a re-render and update the watched value to the correct option "c"

### Expected behaviour

Upon loading the page it could be reasonable to expect that the watched Field two value would be undefined (since there is no field rendered on the page)
Upon selecting the option "Has Field Two" in the "Choose me first" select box, we would expect that the watched Field two value would match the current selected option "c" in the Field Two select box.

* Although one potential solution would be to specify a defaultValue for field_two in the useForm hook, doing this will cause the field to be submitted with the form data in handleSubmit (when the field is not rendered) which is undesired in our use case.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
It's impossible to return the watch value before renders, it's due to the execution order, which is the reason why the watch is offered with defaultValue. However, I would recommend hosting the default value at the `useForm` level to ease those sorts of execution order problems.

watch wouldn't be able to read inline defaultValue, its job was to subscribe to input change.
