### ISSUE TITLE
Field Array, converts output numbers to string.

### ISSUE THREAD

**Issue by pilotola** [react-hook-form/react-hook-form#928]
Hi

I have a form that contains (among other) this input box:
< input type="number" name={`filterConfigurations[${index}].nthMessage`} className="form-control" ref={register} />

When I submit the form, the value is in a string (and not a number, that is what I expected).

{"filterConfigurations":[{"nthMessage":**"12"**,"timebasedIntervalSeconds":"","whenContentChanges":false}]}

As you can see, a similar setup but for a checkbox gives back a correct boolean

Tested on both version 4.5.5 and 4.7.1

Hopefully this is either a easy fix, or something I have overlooked.

**Comment by bluebill1049** [comment]
this is expected behaviour as native number input does return value as string, unless calling valueAsNumber, however that introduce other issue like NaN. we recommend user to do your own transform over data and native input will consistently return string.

**Comment by bluebill1049** [comment]
closing this :) feel free to follow up with questions.
