### ISSUE TITLE
High level form bulding solution

### ISSUE THREAD

**Issue by valerii15298** [react-hook-form/react-hook-form#9281]
**Is your feature request related to a problem? Please describe.**
Sometimes I wanna have high-level abstraction when building forms. And react-hook-form is great but still it is not as easy as https://github.com/data-driven-forms/react-forms

**Describe the solution you'd like**
I love `react-hook-form`. And I would like to have similar tool to https://github.com/data-driven-forms/react-forms but based on react-hook-form. Data driven forms are based on `react-final-form`. So I thought we can have similar library or solution based on `react-hook-form`

**Additional context**
Inside our company we are gonna switch probably to https://github.com/data-driven-forms/react-forms since it seems more easy to use(though not as flexible as `react-hook-form`).
Maybe there already exist some solutions based on `react-hook-form` if so then I would like to know about them.

**Comment by bluebill1049** [comment]
Thanks for the feature request 🙏  however, I don't think this is not within the scope of this library at least right now with my workload and capacity, but I am more than happy to collaborate with someone else willing to create a such library.
