### ISSUE TITLE
issue: FieldErrors can't handle union type

### ISSUE THREAD

**Issue by joan-saum** [react-hook-form/react-hook-form#9287]
### Version Number

7.38.0

### Codesandbox/Expo snack

https://codesandbox.io/s/nostalgic-butterfly-j84vtt?file=/src/App.tsx

### Steps to reproduce

1. Create a form with a union type. The types used in the union should have a property not in common
2. When trying to access to errors.property, typescript is not happy

### Expected behaviour

The errors object should have the same shape as the FormValues, so in case of union type, we could use a type predicate to correctly infer the type

With
```
type Foo = {
      id: 1;
      foo: string;
    };
type Bar = {
      id: 2;
      bar: string;
    }
type Form = Foo | Bar;
```

We should be able to do:
```
function isFoo(foobar: Foo | Bar): foobar is Foo {
  return foobar.foo !== undefined;
}

if (isFoo(errors)) {
  errors.foo // OK
}
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is a limitation which we have spent quite bit time for a solution but coudln't.
