### ISSUE TITLE
Support server rendering

### ISSUE THREAD

**Issue by sanny-io** [react-hook-form/react-hook-form#9295]
**Is your feature request related to a problem? Please describe.**
Next.js 13 was just released, and is an extremely popular framework for developing web apps with React. It uses server components by default, which is the preferred way to use it.

Trying to use `react-hook-form` in a page rendered as a server component results in this error.

```
TypeError: t.default.createContext is not a function
```

Although developers can resolve this error by rendering the page as a client component (`'use client'` at the top of the page), this sacrifices the perks of server rendering.

Server rendering can play into #9261 

**Describe the solution you'd like**
Supporting server rendering.

**Describe alternatives you've considered**
There doesn't appear to be any other solution from what I've seen.

**Comment by bluebill1049** [comment]
> TypeError: t.default.createContext is not a function

could you share some more detail on this error log? also I think overall server render input defaultValue would be a challenge without inline defaultValue inputs. Although I am not against rendering the form on the server.

**Comment by sanny-io** [comment]
`React.createContext` does not exist on the server, there is only `React.createServerContext`

**Comment by bluebill1049** [comment]
I see, we can looking into it later.

**Comment by bluebill1049** [comment]
https://twitter.com/HookForm/status/1586932087688658946
