### ISSUE TITLE
issue: criteriaMode is not working

### ISSUE THREAD

**Issue by kimgni** [react-hook-form/react-hook-form#9300]
### Version Number

7.1.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v6-errors-validatecriteriamode-all-p9xm6?file=/package.json:229-234

### Steps to reproduce

You will see that the sendbox in the doc is not working.

### Expected behaviour

If I set [criteriaMode] to "all", I think the full error should appear.

However, that feature doesn't work in the example, nor does it work in my project.

I went into the code sandbox from that [https://react-hook-form.com/api/useform#validationResolver].

thank you

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
No log output
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
![Screen Shot 2022-10-31 at 8 46 14 pm](https://user-images.githubusercontent.com/10513364/198979431-37e3f672-5375-4a4c-8fd6-21cee6446d31.png)

it's working as expected with a quick test.
