### ISSUE TITLE
issue: when a field with shouldUnregister unmounts, causes form to re-render

### ISSUE THREAD

**Issue by mmahalwy** [react-hook-form/react-hook-form#9309]
### Version Number

7.39.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-basic-forked-11eb0h?file=/src/index.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/react-hook-form-basic-forked-11eb0h?file=/src/index.js
2. Click on checkbox
3. Notice re-render count is now 2
4. Click on checkbox again, to uncheck it
5. Notice re-render count is now 4, not 3. This is cause by shouldUnregister creating a whole form re-render

### Expected behaviour

When fields unmount with `shouldUnregister`, it should not re-render the whole form

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Yes, this is expected as it's safer to update the entire form state to be associated with, this includes dirty, valid and etc.

**Comment by mmahalwy** [comment]
@bluebill1049 makes sense. is there a way to avoid the re-render? especially for large forms

**Comment by bluebill1049** [comment]
Not at this stage.
