### ISSUE TITLE
Add getErrors

### ISSUE THREAD

**Issue by ThewBear** [react-hook-form/react-hook-form#931]
**Is your feature request related to a problem? Please describe.**
Current `errors` object is nested which is hard to reach when creating a custom form component that accepts the name programmatically.

The following example will not works if `name` use dot/bracket syntax.
```jsx
const Input = ({ name, register, required, errors }) => ( 
  <>
    <input name={label} ref={register({ required })} />
    <span>{errors[name]}</span>
  </>
)
```
**Describe the solution you'd like**
Implements `getErrors` that works like `getValues` but returns the flattened errors.

**Describe alternatives you've considered**
Implements `watchError(name)` that works like `watch(name)` but returns the error of specified name.

**Current solution**
Create a get function similar to the one used by `ErrorMessage`

https://github.com/react-hook-form/react-hook-form/blob/b51f920f5e17173442554261be6aa7aedacca315/src/utils/get.ts#L4-L15

**Comment by bluebill1049** [comment]
thanks for your suggestion and it's been noted. we will be looking into it in the next future release.
