### ISSUE TITLE
Input type email is not working correctly in Safari

### ISSUE THREAD

**Issue by c0d3x** [react-hook-form/react-hook-form#9314]
### Version Number

7.39.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-basic-6mlii

### Steps to reproduce

1. Open Safari
2. Go to [Link](https://codesandbox.io/s/react-hook-form-basic-6mlii)
3. Click on email field
4. Click on email field again to be able to type

### Expected behaviour

Should be able to click or tab 1 time and start writing, now in Safari I need to click 2 times to be able to write.

### What browsers are you seeing the problem on?

Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/199594639-1999e30e-7384-40de-8484-a8fa6c089873.mov

**Comment by c0d3x** [comment]
I am using Safari: Versjon 16.1 (18614.2.9.1.12)

**Comment by c0d3x** [comment]
https://user-images.githubusercontent.com/661911/199599847-92988d0d-a3e5-4beb-8d4e-15d442a6c84f.mov

**Comment by bluebill1049** [comment]
Remove hook form, and see if you can reproduce the same behaviour, as we do not interrupt user input.

**Comment by c0d3x** [comment]
When removing RHF and only having the email typed input without register it works as it should.
So must be something happening with RHF.

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/199647724-844ba410-a547-48ca-a478-041d8f46ff7c.mov

This is not a hook form related issue.

**Comment by Moshyfawn** [comment]
Yea, it's the Mac "Hide my Email" feature stealing focus
<img width="508" alt="image" src="https://user-images.githubusercontent.com/16290753/199766925-bd5e78e9-d690-4fb9-aa16-aef9e091d37f.png">
