### ISSUE TITLE
TypeError property 0 is non-configurable and can't be deleted - Firefox

### ISSUE THREAD

**Issue by codinglabsdev** [react-hook-form/react-hook-form#932]
**Describe the bug**
When using a file type input in Firefox and unmounting a component, the `unsetObject` function (`src/utils/unset.ts, line 26`) tries to delete an element of FileList Array. In Firefox, this object is non-configurable, throwing an error. 

**To Reproduce**
1. Using Firefox, create a form with an input file and register it in react-hook-form
2. Add a file to it
3. Unmount the component

**Codesandbox link**
Will add later

**Expected behavior**
No error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10, macOS Catalina
 - Firefox
 - Version 72.0.2 (macOS)

**Smartphone (please complete the following information):**
- Not tested

**Additional context**
In my app, the input is in a child Materials-UI modal. The input, however, is a native HTML.
After clicking submit, `handleSubmit` execute a function that updates the parent state, closing the modal. Then, the error occurs.

I couldn't use react-hook-form for this input type, however, I still used it with the other form inputs. As a workaround, I set an `onChange` in the file input that sets a state with the file list. Then, at submitting, before sending the form data collected by react-hook-form to the API, I injected the state data.

**Comment by bluebill1049** [comment]
awesome find, please supply with a CSB. I will investigate into the fix.

**Comment by bluebill1049** [comment]
I couldn't reproduce this issue: https://codesandbox.io/s/sparkling-smoke-1q6w6 can you please provide example.

**Comment by bluebill1049** [comment]
wait, i am going to try it out firefox now.

**Comment by bluebill1049** [comment]
no issue as well.

**Comment by codinglabsdev** [comment]
The error happens when the unset function is called. Is it being called? In my app it is called when the component is unmounted. 
I’ll try to provide an example today.

**Comment by bluebill1049** [comment]
yes please.

**Comment by codinglabsdev** [comment]
I forgot to say that the input is nested. So maybe setting the name as something like “files.image”

**Comment by codinglabsdev** [comment]
> yes, please and yes it's been invoked. We still need to find a way to reproduce the issue and fix it accordingly.

More differences from the codebox you provided: you are only removing the input field. In my case the whole component is being removed, including the <form> tag. Maybe making a FormComponent with a file input “name=files.name” and then removing it. 

Also don’t forget to add a file to the input and use Firefox

**Comment by bluebill1049** [comment]
> Also don’t forget to add a file to the input and use Firefox

Did that as well.

**Comment by bluebill1049** [comment]
> tag. Maybe making a FormComponent with a file input “name=files.name” and then removing it.

try above as well: https://codesandbox.io/s/infallible-kapitsa-wrm9v

**Comment by bluebill1049** [comment]
btw I do believe the issue exists, just need to find a way to reproduce this issue. :)

**Comment by codinglabsdev** [comment]
Well, I picked your CSB and added modified the input name from "test" to "file.test" and it instantly produced the error, so it may be related to nested inputs.

```
TypeError
property 0 is non-configurable and can't be deleted
unsetObject
https://wrm9v.csb.app/node_modules/react-hook-form/dist/react-hook-form.js:590:13
unsetObject
https://wrm9v.csb.app/node_modules/react-hook-form/dist/react-hook-form.js:585:24
unset
https://wrm9v.csb.app/node_modules/react-hook-form/dist/react-hook-form.js:599:12
useForm/resetFieldRef<
https://wrm9v.csb.app/node_modules/react-hook-form/dist/react-hook-form.js:874:42
useForm/removeFieldEventListenerAndRef<
https://wrm9v.csb.app/node_modules/react-hook-form/dist/react-hook-form.js:904:22
useForm/</</<
https://wrm9v.csb.app/node_modules/react-hook-form/dist/react-hook-form.js:1196:95
useForm/</<
https://wrm9v.csb.app/node_modules/react-hook-form/dist/react-hook-form.js:1196:46
commitHookEffectList
https://wrm9v.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22023:11
commitPassiveHookEffects
https://wrm9v.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22063:31
callCallback
https://wrm9v.csb.app/node_modules/react-dom/cjs/react-dom.development.js:336:14
invokeGuardedCallbackDev
https://wrm9v.csb.app/node_modules/react-dom/cjs/react-dom.development.js:385:16
invokeGuardedCallback
https://wrm9v.csb.app/node_modules/react-dom/cjs/react-dom.development.js:440:31
flushPassiveEffectsImpl
https://wrm9v.csb.app/node_modules/react-dom/cjs/react-dom.development.js:25392:28
unstable_runWithPriority
https://wrm9v.csb.app/node_modules/scheduler/cjs/scheduler.development.js:697:12
runWithPriority$2
https://wrm9v.csb.app/node_modules/react-dom/cjs/react-dom.development.js:12149:10
flushPassiveEffects
https://wrm9v.csb.app/node_modules/react-dom/cjs/react-dom.development.js:25361:12
commitBeforeMutationEffects/<
https://wrm9v.csb.app/node_modules/react-dom/cjs/react-dom.development.js:25240:11
workLoop
https://wrm9v.csb.app/node_modules/scheduler/cjs/scheduler.development.js:641:42
flushWork
https://wrm9v.csb.app/node_modules/scheduler/cjs/scheduler.development.js:596:16
performWorkUntilDeadline
https://wrm9v.csb.app/node_modules/scheduler/cjs/scheduler.development.js:203:48
```

**Comment by bluebill1049** [comment]
aha cool. yeah that must be it. thanks

**Comment by codinglabsdev** [comment]
Yes, I think it is only when using nested inputs. Did you manage to replicate the error?

I modified the input name, added a file, and clicked remove.

**Comment by bluebill1049** [comment]
yea i did, it's only to do with nested inputs. I will patch that soon.

**Comment by bluebill1049** [comment]
patched: https://codesandbox.io/s/epic-microservice-o6i7d if you can verify, i will merge the fix.

**Comment by codinglabsdev** [comment]
Working Great! Thanks!
