### ISSUE TITLE
issue: useFieldArray does not return all fields for boolean array

### ISSUE THREAD

**Issue by Vikciux** [react-hook-form/react-hook-form#9320]
### Version Number

7.39.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-lxuxv4

### Steps to reproduce

1. Open codesandbox link
2. Wait for page to render
3. Note that field count displays 1, but defaultValues.test is of length two. Second array value is not displayed.

### Expected behaviour

Field count shows 2 and two inputs with values false and true are displayed on page.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
`useFieldArray` does not support flat arrays _(array of `non-object` type)_. Refer to `useFieldArray` docs for more info on the hook's usage: [`useFieldArray` rules docs section](https://react-hook-form.com/api/usefieldarray#rules)
> Does not support flat field array.

**Comment by Moshyfawn** [comment]
Consider updating your `test` array to be an `array` of `object`s like:
```js
const defaultValues = {
  test: [{ checked: false }, { checked: true }]
}
```

**Comment by Vikciux** [comment]
Understood. Thanks for the response. Please consider updating that line of documentation to something like:

> Supports arrays with object elements only.
