### ISSUE TITLE
issue: reValidateMode: onChange call validate function only after submitting form

### ISSUE THREAD

**Issue by Iwans-fn** [react-hook-form/react-hook-form#9330]
### Version Number

7.39.31

### Codesandbox/Expo snack

https://codesandbox.io/s/jolly-voice-i27e29?file=/src/App.js

### Steps to reproduce

1. Open codesandbox link, type something in input
2. click submit button
3. type something again

### Expected behaviour

Validate function should call on input change 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/200091051-5affd249-9a54-43b6-8491-48dea2af5775.mov

revalidate mode is onChange by default, you shouldn't need to config it, and looks like it's working as expected on my testing.
