### ISSUE TITLE
issue: Nested validation is not working as expected

### ISSUE THREAD

**Issue by NarenderSiri** [react-hook-form/react-hook-form#9338]
### Version Number

7

### Codesandbox/Expo snack

https://codesandbox.io/s/nestedfieldserrormessageincomponent-kkfdhz

### Steps to reproduce

1. Go to '[codesandbox](https://codesandbox.io/s/nestedfieldserrormessageincomponent-kkfdhz)'
2. without adding data please do Click on **Submit Button**
3. All Textfields are **Required**
4. First field was validates and throwing error message
5. But other fields was not throwing error message.
 

### Expected behaviour

Without Adding data please submit, first field was throwing error message like (fname is required), but other fields are not throwing error message...
**My Query:** Nested validation is not working..
 **Note:** If any error for my codesandbox **Please Reload**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> criteriaMode: "firstError",

https://react-hook-form.com/api/useform

- When set to firstError (default), only the first error from each field will be gathered.
- When set to all, all errors from each field will be gathered.

**Comment by NarenderSiri** [comment]
1. it's good for working in Formstate, but one thing i.e ===>i'm creates & using Dynamic component for TextField that component name is (InputField.js).
2. And First Field was showing error message but other fields are not showing error message, (But inside the console.log it will be showing).
3. My Expectation is every field below showing error message (Ex: Looks like First TextField)
4. ![Screenshot (37)](https://user-images.githubusercontent.com/48355455/200571227-e0e5a7ee-e197-4265-b7d0-2109443d520c.png)

**Comment by NarenderSiri** [comment]
And I've also getting same error message for **first textfield** but **other textfields are not showing error message**
![Screenshot (38)](https://user-images.githubusercontent.com/48355455/200572542-f7359f30-0796-4954-b135-a255ccde0296.png)
