### ISSUE TITLE
useFieldsArray prepend error

### ISSUE THREAD

**Issue by joelNguyenn1010** [react-hook-form/react-hook-form#934]
I try to prepend value to fields in useFieldsArray and the value got duplicate. For example 
I try to prepend "1" and then "2" and then "3". The result gave me are "1", "1", "3"
Here is my code
![image](https://user-images.githubusercontent.com/38491434/73420715-91880080-4377-11ea-9171-bba6d669091b.png)
![image](https://user-images.githubusercontent.com/38491434/73420733-a5cbfd80-4377-11ea-977f-1277f616f8b0.png)
![image](https://user-images.githubusercontent.com/38491434/73420754-b7150a00-4377-11ea-949a-9232f16f6f22.png)

**Comment by bluebill1049** [comment]
please submit a code sandbox and follow our issue report template.
