### ISSUE TITLE
useFieldArray replacing entire array with invidual objects

### ISSUE THREAD

**Issue by blakecannell** [react-hook-form/react-hook-form#935]
Hi team, first of all thanks for the hook, you've made porting my application over to hooks a pleasure.

I'm having an issue with useFieldArray whereby simply appending an item to the array seems to serialise the array and add each as a seperate value in the parent form.

I've forked your example sandbox and added a `JSON.stringify` to print the form state to illustrate the issue. To reproduce, simple use the `append` button and pay attention to the new state of the form being printed.

https://codesandbox.io/s/react-hook-form-usefieldarray-2hdro

**Expected behavior**
Appending/prepending objects to the array should do exactly that, not add these as individual values of the parent state.

 - OS: macOS High Sierra 10.13.6
 - Chrome 79.0.3945.130

I had a brief look at the source, and the append function looks fine to me. 🤷‍♂ Although, I've not dug too much and my typescript experience is minimal.

Thanks in advance!

**Comment by blakecannell** [comment]
Note: Even more strange, using the `prepend` function in this sandbox with reset the form to it's default state. 😬

**Comment by bluebill1049** [comment]
i think this is a duplicated issue which we are working on. https://github.com/react-hook-form/react-hook-form/issues/924 which i believe involve with watch the field array value.

**Comment by blakecannell** [comment]
Ah, no stress thank you! Apologies for not searching harder before opening a new issue!

**Comment by bluebill1049** [comment]
no worries at all. you can keep monitoring on that issue. we are working hard over a solution for it.

**Comment by blakecannell** [comment]
Actually, that issue seems to be related to `fields`, not the parent form state generated by `getValues`?

**Comment by bluebill1049** [comment]
that issue is related to `watch()` which is return the field array values.
