### ISSUE TITLE
issue: `trigger` and `setValue` break current form validation strategy

### ISSUE THREAD

**Issue by delijah** [react-hook-form/react-hook-form#9351]
### Version Number

7.39.1

### Codesandbox/Expo snack

https://codesandbox.io/s/great-lucy-onywv0

### Steps to reproduce

1. Go to provided Codesandbox link
2. Click on 'SUBMIT'
3. firstName field turns invalid
4. Type 'frank' into firstName field
5. firstName field turns valid
6. Click on 'set invalid value'
7. The field stays valid even though it is not

### Expected behaviour

The firstName field should turn invalid since we've defined the following validation strategy: Validate a field whenever the form has been submitted at least once and the field value has been changed. Of course we could achieve the desired result by setting `shouldValidate` to `true`, but remembering this in a large app with a lot of developers working on it is sheer impossible.

I suggest that the `setValue` function should consider the current `mode` and `reValidateMode` setting in order to determine the default value of `shouldValidate`. Let me provide an example:

```js
const mode = 'onSubmit';
const reValidateMode = 'onChange';
const form = useForm({
    mode,
    reValidateMode,
});

const setValue = (name, value, options) => {
    let shouldValidate;

    if (mode === 'onSubmit' && reValidateMode === 'onChange') {
        shouldValidate = form.formState.isSubmitted;
    }

    form.setValue(name, value, {
        shouldValidate,
        ...options,
    });
};

const trigger = (name, options = {}) => {
    const { force } = options;

    if (!force && mode === 'onSubmit' && !form.formState.isSubmitted) {
        return;
    }

    form.trigger(name, options);
};
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by delijah** [comment]
Oh sorry. Nothing happened there so i've assumed it was the wrong place to get in contact and issues might be the more appropriate spot. Also, in fact, it turned from a question into a real issue for us.

**Comment by bluebill1049** [comment]
send us a feature request if you prefer, we can put those considerations into the next major version release
