### ISSUE TITLE
issue: 7.39.2 crashes with error `setting getter-only property "value"` calling `setValue` on form

### ISSUE THREAD

**Issue by rcbevans** [react-hook-form/react-hook-form#9355]
### Version Number

7.3.9

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-7392-crash-v46921

### Steps to reproduce

This is a regression which broke deployed working code without build errors.

```
type UserProfileForm = {
  name: string;
  timezone?: Timezone;
  preferenceTheme: ThemePreference;
};

  const {
    setValue,
    handleSubmit,
    control,
    reset,
    formState: { isValid, errors },
  } = useForm<UserProfileForm>({
    defaultValues: {
      name: user?.name || auth0User?.name,
      timezone: user?.timezone || defaultTz,
      preferenceTheme: user?.preferenceTheme || 'SYSTEM',
    },
    resolver: yupResolver(formSchema),
    reValidateMode: 'onChange',
    mode: 'onChange',
  });

  useEffect(() => {
    setValue('name', user?.name || auth0User?.name || '');
    setValue('timezone', user?.timezone || defaultTz);
    setValue('preferenceTheme', user?.preferenceTheme || 'SYSTEM');
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user, defaultTz, auth0User?.name]);
```

Uncaught TypeError: setting getter-only property "value"
    setFieldValue createFormControl.ts:565
    setValue createFormControl.ts:641
    WelcomeProfile WelcomeProfile.tsx:97

### Expected behaviour

Set value should successfully set the form value.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Relevant log output

```shell
Uncaught TypeError: setting getter-only property "value"
    setFieldValue createFormControl.ts:565
    setValue createFormControl.ts:641
    WelcomeProfile WelcomeProfile.tsx:97
    React 5
    unstable_runWithPriority scheduler.development.js:468
    React 3
    workLoop scheduler.development.js:417
    flushWork scheduler.development.js:390
    performWorkUntilDeadline scheduler.development.js:157
Caused by: React ErrorBoundary Error: setting getter-only property "value"
    WelcomeProfile WelcomeProfile.tsx:68
    WelcomeWizard WelcomeWizard.tsx:44
    node_modules bundle.js:87376
    node_modules bundle.js:96082
    FocusRectsProvider FocusRectsProvider.tsx:17
    node_modules bundle.js:86674
    Wrapped styled.tsx:92
    FocusRectsProvider FocusRectsProvider.tsx:17
    node_modules bundle.js:90183
    Wrapped styled.tsx:92
    node_modules bundle.js:92408
    Wrapped styled.tsx:92
    FocusRectsProvider FocusRectsProvider.tsx:17
    node_modules bundle.js:101273
    BaseLayout BaseLayout.tsx:23
    App App.tsx:50
    WithAuthenticationRequired with-authentication-required.tsx:99
    RenderedRoute hooks.tsx:550
    Routes components.tsx:374
    ErrorBoundary errorboundary.tsx:68
    Auth0Provider auth0-provider.tsx:257
    Auth0ProviderWithHistory Auth0ProviderWithHistory.tsx:10
    QueryClientProvider QueryClientProvider.js:32
    Router components.tsx:296
    BrowserRouter index.tsx:247
createFormControl.ts:565
    setFieldValue createFormControl.ts:565
    setValue createFormControl.ts:641
    WelcomeProfile WelcomeProfile.tsx:97
    React 5
    unstable_runWithPriority scheduler.development.js:468
    React 3
    workLoop scheduler.development.js:417
    flushWork scheduler.development.js:390
    performWorkUntilDeadline scheduler.development.js:157
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rcbevans** [comment]
Issue seems specifically related to the use of `<Controller/>` with the form

**Comment by getTobiasNielsen** [comment]
Counter offer:
https://codesandbox.io/s/react-hook-form-7392-crash-forked-4piz3x?file=/src/App.tsx
I think it's the component lib? @fluentui/react

**Comment by bluebill1049** [comment]
This is due to MUI ref is a custom object instead the real input reference, i will looking into a solution.

**Comment by getTobiasNielsen** [comment]
Here: 
https://codesandbox.io/s/react-hook-form-7392-crash-forked-4piz3x?file=/src/App.tsx
Source: https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield
![image](https://user-images.githubusercontent.com/54803528/201215500-42791d30-f7e9-4ae6-b5e7-24126f03fe43.png)

In short, MS used a different prop than ref. I guess ref might be a getter only in their code. Who knows.

**Comment by getTobiasNielsen** [comment]
> This is due to MUI ref being a custom object instead of the actual input reference, I will look into a solution. thanks, @getTobiasNielsen for looking into it.

It's actually not MUI this time, but fluentui.

**Comment by bluebill1049** [comment]
> It's actually not MUI this time, but fluentui.

oops dealt with too many MUI issues, similar components give me deja vu haha

**Comment by rcbevans** [comment]
@getTobiasNielsen great suggestion to just avoid setting the ref on the TextField.

I was able to verify by omitting ref, things work as expected, and as before.

**Comment by bluebill1049** [comment]
> @getTobiasNielsen great suggestion to just avoid setting the ref on the TextField.
> 
> I was able to verify by omitting ref, things work as expected, and as before.

Will seek workaround for this issue, as awe are honouring the **real** ref in 7.39.2 and hence caused this issue.

**Comment by bluebill1049** [comment]
Tried varies way but unfortunately due to all those external controlled component's ref forward has different various object shape, we will have to keep the custom ref object just to be compatible with them as well :( I am reverting the original improvement code.

**Comment by bluebill1049** [comment]
reverted: https://github.com/react-hook-form/react-hook-form/commit/2d65383a7b35d0544d954f280c97e64f95fc4d97
