### ISSUE TITLE
className prop support for ErrorMessage component

### ISSUE THREAD

**Issue by orteth01** [react-hook-form/react-hook-form#937]
**Is your feature request related to a problem? Please describe.**
We really like the `ErrorMessage` component but would like to be able to pass `className` to it.

**Describe the solution you'd like**
`ErrorMessage` could accept a `className` prop.

**Describe alternatives you've considered**
We could use the provided render prop and add the className there or wrap the ErrorMessage in another element and add the className there. However, we'd really like to be able to add it directly to ErrorMessage and not have to deal w/ extra elements.

**Additional context**
I poked around the code to see how complicated it would be to add. It looks like we'd only be able to pass it if we also passed the `as` prop, because you can't have className as a prop on React.Fragment. I sort of feel like if the `as` prop is not provided a `span` should be the default element, and if users want to use a fragment they could do `as={React.Fragment}` - i'm interested to hear if you've considered that.

**Comment by bluebill1049** [comment]
Thanks for the detailed feature request.

https://react-hook-form.com/api#ErrorMessage

Check out the doc on the usage, it accept render prop. So you can assign class name or even modify how u want the error message to return.

**Comment by bluebill1049** [comment]
@kotarella1110 what do u think of spread the props?

**Comment by orteth01** [comment]
Thanks for the fast reply! We're aware of the render prop but would love a simpler approach, if possible.

```
<ErrorMessage errors={errors} name="singleErrorInput">
  {({ message }) => <p className="foo">{message}</p>}
</ErrorMessage>
```

vs

```
<ErrorMessage errors={errors} name="singleErrorInput" as="p" className="foo" />
```

it's a bit easier to Grok IMO and less code.

**Comment by bluebill1049** [comment]
I do agree with above :) in terms of `span` as default: I prefer to be less opinionated about what to render, someone will arg `p` tag is better and ect...

**Comment by bluebill1049** [comment]
feel free to send a PR around spread props and @kotarella1110 can review your change as well :)

**Comment by kotarella1110** [comment]
I also agree with this!
If @orteth01 can't send this PR, I will it.

**Comment by orteth01** [comment]
Thanks! I really appreciate it, @kotarella1110. I probably won't have time to tackle this until next week. If you do open a PR, can you tag me on it? I'm not super familiar with typescript and am interested in what your approach will be.

And thanks for an awesome library!

**Comment by bluebill1049** [comment]
awesome work from @kotarella1110 it will be in the next minor update :)
