### ISSUE TITLE
Improve watch performance

### ISSUE THREAD

**Issue by matheusffatg** [react-hook-form/react-hook-form#938]
I've noticed that when we use `watch('field')` it gets the values for all fields in the form before it can actually watch for it.
This is problematic when using `useFieldArray` which could potentially have lots of rows that can be watched.

![image](https://user-images.githubusercontent.com/59067561/73501845-f9404a80-437b-11ea-9550-11b7a07d44bd.png)

here is what the current code looks like: 
```
    function watch(fieldNames, defaultValue) {
        const combinedDefaultValues = isUndefined(defaultValue)
            ? isUndefined(defaultValuesRef.current)
                ? {}
                : defaultValuesRef.current
            : defaultValue;
        // get values of every single field in the form.
        const fieldValues = getFieldsValues(fieldsRef.current);
```
one solution could be to only get the values of the fields that needs to watched.
```
        const fieldValues = getFieldsValues(fieldsRef.current, fieldNames);
```
and then update `getFieldsValues` to something like:

```
var getFieldsValues = (fields, filter) => {
    const values = {};
    Object.values(fields).forEach(({ ref, ref: { name } }) => {
        if (!filter || filter.indexOf(name) > -1) {
            values[name] = getFieldValue(fields, ref);
        }
    });
    return values;
}
```
I'm not sure what other things this could impact but I've seem rendering time dropping from 114ms to 42ms with this change.

**Comment by bluebill1049** [comment]
can you try out this version: react-hook-form@4.7.3-beta.1

**Comment by matheusffatg** [comment]
Thanks for the fast reply @bluebill1049 . yeah it does work when watching for a single field but it doesn't for multiple fields.
```
const watch = watch([`items[${index}].col1`, `items[${index}].col2`])
```
