### ISSUE TITLE
issue: Deleting a fieldArray item does not update the validation state

### ISSUE THREAD

**Issue by ysgk** [react-hook-form/react-hook-form#9383]
### Version Number

7.39.4

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-e1496y?file=/src/index.tsx

### Steps to reproduce

1. Click the "Submit" button. Console logs will be displayed. 😄
2. Click the "APPEND" button.
3. Click the "Submit" button. No console logs will be displayed, but this is intended. 😄
4. Click the "DELETE" button.
5. Click the "Submit" button. Again, no console logs will be displayed (!) 🙁

I also confirmed that if formState.errors or formState.isValid are referenced in the component, console logs are displayed in step 5.

### Expected behaviour

1. Click the "Submit" button. Console logs will be displayed. 😄
2. Click the "APPEND" button.
3. Click the "Submit" button. No console logs will be displayed, but this is intended. 😄
4. Click the "DELETE" button.
5. Click the "Submit" button. Console logs will be displayed. 😄

I'm not sure if this is the intended behavior, is there any way to allow submitting without referencing formState?

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leapful** [comment]
@ysgk 

Thanks for your report. 

Pull request for the fix is here: https://github.com/react-hook-form/react-hook-form/pull/9384

@bluebill1049 : Could you please help to review it ? Thank you.

**Comment by bluebill1049** [comment]
> @ysgk
> 
> Thanks for your report.
> 
> Pull request for the fix is here: #9384
> 
> @bluebill1049 : Could you please help to review it ? Thank you.

Thanks for the quick fix! I have suggested an alternative fix and followed with some explanation.

**Comment by leapful** [comment]
@bluebill1049 

Thanks for the alternative fix, Bill :D 

Shall we close this issue ?

**Comment by bluebill1049** [comment]
@leapful I will patch it in your PR and then close the issue.

**Comment by bluebill1049** [comment]
thanks @leapful 🙏 ❤️

**Comment by ysgk** [comment]
Thank you for your quick fix! 🙏 ❤️
