### ISSUE TITLE
issue: behavior between 7.12.2 -> 7.13.0-next.0+ changed for fieldset

### ISSUE THREAD

**Issue by mike-robertson** [react-hook-form/react-hook-form#9395]
### Version Number

17.13.0+

### Codesandbox/Expo snack

https://codesandbox.io/s/magical-tree-zy1vb5?file=/src/App.tsx

### Steps to reproduce

Codesandbox is set to the last working version (7.12.2).

1. Go to https://codesandbox.io/s/magical-tree-zy1vb5?file=/src/App.tsx
2. Select any radio button
3. Click "submit"
4. See the form value which should be the number corresponding to the radio option you selected

Change the version to 7.13.0 (or 7.13.0-next.0) or any other version after that to see the change in behavior.

1. Now select the "1" radio option and submit
2. notice that it does correctly get that value as "1" both displayed & in the console
3. Now select any other radio option besides the first and submit
4. Notice that nothing is displayed now, and the value output in the console for the field is now `null`

### Expected behaviour

I am not sure if 7.12.2's behavior was expected, but it was very convenient for building radio button groups. I suspect something about this in the release notes is the cause of the change in behavior:
<img width="806" alt="image" src="https://user-images.githubusercontent.com/8756876/202754289-260ae543-0000-4453-801e-c606e7825ef1.png">

So I am not sure if this is something you want to "fix" or not, but figured I would point it out. It is possible to have things working using the `Controller` and putting an `onChange` on the `fieldset`, so it is totally possible to work around it.

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is expected behaviour for non-selected radio input to follow the web standard and we had many round trips to keep native register radio input stable, haven't null has none selected value is the most stable fix. If you need custom results use controlled and build a controlled component for it.

**Comment by mike-robertson** [comment]
@bluebill1049 I'm not sure I'm following your response/how it pertains to my issue report. The issue has to do with the behavior as described and demonstrated in the codesandbox, it doesn't have anything to do with what value a non-selected radio input has.
