### ISSUE TITLE
issue: formState.isValid not sync with formState.error while async validation

### ISSUE THREAD

**Issue by blingblingredstar** [react-hook-form/react-hook-form#9410]
### Version Number

7.39.5

### Codesandbox/Expo snack

https://codesandbox.io/s/peaceful-darkness-9ol27g?file=/src/App.tsx

### Steps to reproduce

1. input two char like 'aa'
2. wait for submit not disabled
3. input another char like 'a', this time input value is 'aaa'
4. show an error message but the button is still available
5. wait for some time, the button change to disabled automatically

### Expected behaviour

If there is an error, the button should be disabled at the same time

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blingblingredstar** [comment]
https://github.com/ArabyZY think this may be caused by this change: https://github.com/react-hook-form/react-hook-form/pull/9286

**Comment by bluebill1049** [comment]
> https://github.com/ArabyZY think this may be caused by this change: #9286

That's correct. `isValid` will need to resolve the entire form validity. so the `errors` state will be updated first, then running the entire form validation to resolve the entire form. Or else we will be blocking the validation logic.

**Comment by bluebill1049** [comment]
Going to close this as it's expected behaviour for large dependency form validity, it's always safer to run the enter form validation.

**Comment by blingblingredstar** [comment]
@bluebill1049 So, how should we disable the submit button if the form is invalid? Currently, it's wired for a user to see an error message with submit button available. I use `Object.keys(errors).length > 0` instead `formState.isValid` now to keep consistent on UI, but it's wired for a developer, the `formState.isValid` is supposed to be the same with errors count.

**Comment by bluebill1049** [comment]
> but it's wired for a developer, the formState.isValid is supposed to be the same with errors count.

I don't have a solution in my head right now, if you think deeper about this problem if input A depends on input B and input C (b and c both async), then it makes sense for isValid to be updated later. Unless we block errors from updating until valid is resolved.

**Comment by blingblingredstar** [comment]
Yes, the async validation is useful and necessary, but I don't think this is an expected behavior, we should keep consistent with isValid and errors, this behavior is wired for a user.

**Comment by bluebill1049** [comment]
Fair enough, maybe we should
