### ISSUE TITLE
issue: Field doesn't become a dirty after setValue(..., ..., { shouldDirty: true } if defaultValues have been assigned through class instance

### ISSUE THREAD

**Issue by RuslanAktaev** [react-hook-form/react-hook-form#9428]
### Version Number

7.39.5

### Codesandbox/Expo snack

https://codesandbox.io/s/bold-currying-3w2lnp?file=/src/App.js

### Steps to reproduce

1. Open a homepage
2. Click on "Change value" button
3. See dirtyFields value on the page:

> dirtyFiels: {}
> touchedFiels: {"avatarID":true}

### Expected behaviour

> dirtyFiels: {"avatarID":true}
> touchedFiels: {"avatarID":true}

on the page

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we do not support class date type, you can consider posting a feature request instead.

https://react-hook-form.com/api/useform

> It's recommend to avoid including custom object which contains prototype methods as the defaultValues, such as moment, luxon and etc.
