### ISSUE TITLE
When using useFieldArray, validation returns an array with empty elements on re-submit

### ISSUE THREAD

**Issue by sofianegargouri** [react-hook-form/react-hook-form#9429]
### Version Number

7.39.5

### Codesandbox/Expo snack

Can't replicate it in a CodeSandbox :(

### Steps to reproduce

1. Created a form with:
  - `name` (required)
  - `code` (required)
  - `values_attributes` (field array):
    - `name` (required & unique)
    - `code` (required & unique)
2. When I set 2 codes from the field array with the same value, I get an error, if I remove it immediately, everything works fine
3. When I submit with the error, correct my error by removing one of the duplicates, and then resubmit, my `isValid` is `false`. Furthermore, the `errors.values_attributes` is equal to `[empty]`

Additional information: we don't have the bug when using only `required: true`

### Expected behaviour

3. When I submit with the error, correct my error by removing one of the duplicates, and then resubmit, my `isValid` is `true`. Furthermore, the `errors.values_attributes` should not exist

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Please try to reproduce the issue in a CSB, otherwise, it's very difficult to us to investigate the root cause of the issue and even supply a fix.

**Comment by sofianegargouri** [comment]
Here is all the information I can give to you:

CodeSandbox (a copy-paste of the file I'm working on): https://codesandbox.io/s/practical-rgb-y6dzmj
My local behavior: https://derniercri.d.pr/i/wgzPiA
The behavior I have on CodeSandbox: https://derniercri.d.pr/i/pJWHkT

**Comment by sofianegargouri** [comment]
Postmortem: we had that issue because our React app is embed in another back-end application that was requiring other javascript libraries. Removing those external imports did fix our issue.
Sorry for the loss of time 😅

**Comment by bluebill1049** [comment]
glad you resolved the issue 👍
