### ISSUE TITLE
Multiple validation sources / validation priority

### ISSUE THREAD

**Issue by mstanielewicz** [react-hook-form/react-hook-form#943]
**Is your feature request related to a problem? Please describe.**
I had a problem with setting both schema validation and field level validation. There could be scenario when a user want to use schema validation, but also have some additional validation for example on backend. Right now if you use schema, field validation function doesn't even run.

**Describe the solution you'd like**
I thought about setting a priority as a setting for useForm hook. There could be schemaFirst and fieldFirst, so first it would validate on schema level and then run field level validation, or the other was so first field level and then schema (I would use schema first as a default).

**Additional context**
I could try to work on that, but I want to know if that's something you would like in react-hook-form.

**Comment by bluebill1049** [comment]
Thanks for the feature request :) as right now I think we will stay as it is. 

If users want to trigger a custom error message, they can use `setError` at `handleSubmit` level.

**Comment by bluebill1049** [comment]
going to close this issue for now, thanks for the suggestion ❤️
