### ISSUE TITLE
issue: { name, type } return in watch() callback is undefined after reset() call

### ISSUE THREAD

**Issue by Kuro091** [react-hook-form/react-hook-form#9438]
### Version Number

7.39.5

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-reset-form-delte-forked-v6q1st?file=/src/index.js

### Steps to reproduce

1. Type on firstName input
2. Type on lastName input
3. Click on reset

### Expected behaviour

Inputs' names get returned as part of the callback function on watch()

Actual: { name, type } are both undefined

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
watch 
{firstName: "World Ending", lastName: ""}
firstName change 
watch 
{firstName: "World Ending", lastName: "Squirrel"}
lastName change 
watch 
{firstName: "test", lastName: "test"}
undefined
undefined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is expected, invoked by `reset`.
