### ISSUE TITLE
Input inside a hoc not work

### ISSUE THREAD

**Issue by gsnunes** [react-hook-form/react-hook-form#945]
**Describe the bug**
I'm using some different components on my form, like reactstrap, datepicker and suggestion.
Then I'm using the controller to manage register and I need to make a HOC where I just pass my input and make my code more clean. But this is not working.
In the sandbox example I just put the input into a HOC and it stops work. Look that I pass the "react-hook-form" props into a config prop just for easy read.

**To Reproduce**
I changed firstName input for use HOC, then type the firstName and age and click on submit.
Look that firstName not works right.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-validationschema-withhoc-t7zxv

**Expected behavior**
firstName would work right like age input.

**Comment by bluebill1049** [comment]
With HOC each re-render will mount and re-mount the child component which is the reason cause this issue, I would recommend to use FormContext instead.
