### ISSUE TITLE
`isDirty` flag is always `true` but `dirtyFields` is an empty object 

### ISSUE THREAD

**Issue by AlexKrupko** [react-hook-form/react-hook-form#9453]
### Version Number

7.39.5

### Codesandbox/Expo snack

https://codesandbox.io/s/recursing-star-mb3quo?file=/src/App.js

### Steps to reproduce

Hi there, 

Starting with 7.39.5 version, `isDirty` flag is always `true` in form state. But the `dirtyFields` is an empty object at the same time. Please refer to the codesandbox link. 

### Expected behaviour

`isDirty` should be `false` until any of form fields is really changed as it was before 7.39.5 version. 

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/useform/formstate

> Make sure to provide all inputs' defaultValues at the useForm, so hook form can have a single source of truth to compare whether the form is dirty.

**Comment by HadiSDev** [comment]
@bluebill1049 I have an edit page where I don't use "defaultValues" but load the form with data using the "reset" function in useEffect once the data is loaded. However, isDirty seems to always be true
