### ISSUE TITLE
Errors no longer updating after field touched in 7.39.6 when using `useFormContext`

### ISSUE THREAD

**Issue by mzeitlin11** [react-hook-form/react-hook-form#9455]
### Version Number

7.39.6

### Codesandbox/Expo snack

https://codesandbox.io/s/clever-khorana-vrjxkt?file=/src/App.tsx

### Steps to reproduce

With `react-hook-form=7.39.5` selected:
1. Click on and off the input box
2. Error is updated and shown "First name is required!"

With `react-hook-form=7.39.6` selected:
1. Click on and off the input box
2. Error is not updated

### Expected behaviour

The behavior should match `7.39.5`, with the `formState` `errors` updating after the `firstName` field is touched.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks reverted will publish another patch today: https://github.com/react-hook-form/react-hook-form/commit/32dda93ecbc6660e7a4a26e3b06d8b521692041d

**Comment by mzeitlin11** [comment]
Thanks for the quick fix!
