### ISSUE TITLE
Ability to retrieve `schema` passed to `resolver`

### ISSUE THREAD

**Issue by michaelhays** [react-hook-form/react-hook-form#9461]
I've been using the following approach to create forms:

```ts
import { zodResolver } from '@hookform/resolvers/zod'
import { useForm } from 'react-hook-form'
import { z } from 'zod'

const mySchema = z.object({
   ...
})

const myForm = useForm<z.infer<typeof mySchema>>({
  resolver: zodResolver(mySchema),
})
```

It would be really convenient to be able to retrieve `mySchema` from the `myForm` object, in order to use that schema to manually parse the form data at different places. But to my knowledge, this isn't currently possible; you can retrieve the `resolver` at `myForm.control._options.resolver`, but not the schema that was passed in.

Currently, I'm extending the form object by adding the schema at `myForm.control._options.resolverSchema`, but it would be great if this (or something similar) were built into the library.

**Comment by bluebill1049** [comment]
thanks for the feature request, is this an option before we move it into the feature board?

```tsx
export const mySchema = z.object({
   ...
})
```

**Comment by michaelhays** [comment]
So basically for my use case, I have a pretty complex `<SaveItem />` component that handles multi-step form validation and custom data serialization, and needs access to the form schema in order to parse the schema directly.

I am able to instantiate that component like this:

```tsx
<SaveItem
  form={myForm}
  schema={mySchema}
  // Lots of other parameters
/>
```

Which isn't _awful_, but it's definitely more convenient and DRY to be able to just call the schema that was passed into the form, since it will always be the exact same as what would be passed to `SaveItem.schema`.

**Comment by bluebill1049** [comment]
If you just export that schema to a const, could you can use it anywhere? (I may missing the context here)

```tsx
<SaveItem
  form={myForm}
  // Lots of other parameters
/>

import schema from './myShcmea';

function SaveItem() {
  useForm({
    resolver: resolver(schema)
  })
}
```

**Comment by michaelhays** [comment]
Yeah the context is kind of hard to provide, but the `<SaveItem />` component is generic, so with that method we'd have to import all 50+ (and growing) schemas into the `<SaveItem />` component.

We also aren't able to create the form within `<SaveItem />`, because we need to pass it around to other components.

Maybe this full (but simplified) example will help paint the picture, which also uses a custom generic `<Input />` component of ours, which requires the `userForm` variable as a parameter:

```tsx
import Input from '@/ui/Input'
import SaveItem from '@/ui/SaveItem'
import { zodResolver } from '@hookform/resolvers/zod'
import { useForm } from 'react-hook-form'
import { z } from 'zod'

export const userSchema = z.object({
  name: z.string().min(1),
  email: z.string().email(),
})

export default function UserSave() {
  const userForm = useForm<z.infer<typeof userSchema>>({
    resolver: zodResolver(userSchema),
  })

  return (
    <SaveItem
      form={userForm}
      steps={[
        {
          name: 'Name',
          component: (
            <Input type="text" form={userForm} field="name" label="Name" />
          ),
        },
        {
          name: 'Email',
          component: (
            <Input type="email" form={userForm} field="email" label="Email" />
          ),
        },
      ]}
    />
  )
}
```

**Comment by bluebill1049** [comment]
Thanks for the context. Moving it into the project board for upvotes.

**Comment by michaelhays** [comment]
Awesome, thanks! And I'm happy to contribute with the implementation if needed!

**Comment by bluebill1049** [comment]
Thanks, @michaelhays will ping you once we have a proposal for the API and see if you are interested to implement.
