### ISSUE TITLE
issue: useFormContext `errrors` prop from formState does not update even when destructured

### ISSUE THREAD

**Issue by Nfinished** [react-hook-form/react-hook-form#9462]
### Version Number

7.39.7

### Codesandbox/Expo snack

https://codesandbox.io/s/useformcontext-issue-31tglo?file=/src/index.jsx

### Steps to reproduce

Hit submit in the codesandbox, you'll see an error in the console from the form component, but the CustomError component does not render text.

### Expected behaviour

the watched `errors` value in CustomError should update to correctly reflect that `amount` is required.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Please refer to your code, the message is not supplied.

![Screenshot 2022-11-29 at 1 47 42 pm](https://user-images.githubusercontent.com/10513364/204426350-9105ded6-76e9-4116-a10f-3a0228914918.png)

**Comment by Nfinished** [comment]
Did I miss that in the docs somewhere? All I saw was that `errors` was a proxy value and needed to be destructured before use.

https://react-hook-form.com/api/useform/formstate

**Comment by bluebill1049** [comment]
Please refer to my comment above, you are missing the validation message, which is empty string and hence not render as text node.

**Comment by Nfinished** [comment]
Ah sorry, I see that I screwed up the example. This doesn't represent the issue in my code, I'll try a better repro.

**Comment by bluebill1049** [comment]
Are you using the latest patch? we had a regression 7.39.6?

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/releases/tag/v7.39.7

**Comment by Nfinished** [comment]
Hah yeah I just realized the same thing. I was one patch version behind in my local environment and that was causing the issue. Thank you!
