### ISSUE TITLE
issue: Validation works wrong when using "required"

### ISSUE THREAD

**Issue by philippmalkov** [react-hook-form/react-hook-form#9463]
### Version Number

7.39.7

### Codesandbox/Expo snack

https://codesandbox.io/s/jovial-engelbart-ddsrj2

### Steps to reproduce

1. Go to [codesandbox](https://codesandbox.io/s/jovial-engelbart-ddsrj2)
2. Under "With required" heading (validation: required and minLength=4):
3. Try to type "s" (validation will say "valid" - incorrect)
4. Try to type "ssss" (validation will still say "valid" - correct)
5. Try to type "sss" (validation will say "invalid" - correct)
6. So as you can see validation says "valid" till the first "really valid" event, but as I understand, it should say invalid as soon as input doesn't have at least 4 chars inside
7. Try to use input under "Without required" heading - you will see that without "required" rule validation works like a charm EXCEPT when the input is empty - it says "valid" - why is it valid that input has 0 chars if validation requirement is at least 4 chars?

### Expected behaviour

Validation triggers on change and shows error when there are less than 4 chars and form can't be submitted till the input has at least 4 chars

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is expected behaviour for `required` and aligned with the native web required attribute, for custom validation behaviour use validate instead.
