### ISSUE TITLE
issue: Fields with apostrophe in their name are not getting registered.

### ISSUE THREAD

**Issue by mohitkhurana1812** [react-hook-form/react-hook-form#9466]
### Version Number

7.31.3

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-handlesubmit-v7-forked-nhjmfo?file=/src/index.jsx:0-1275

### Steps to reproduce

1. Go to sandbox link.
2. Fill the form
3. Click on submit
5. Alert doesn't show first's name data.

### Expected behaviour

Field should get registered.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we don't support such a name path, and try to avoid special characters.

**Comment by mohitkhurana1812** [comment]
Thanks for the quick response.
Was this supported in earlier versions(<v5)??

**Comment by mohitkhurana1812** [comment]
Thankyou for the quick response.
Was this supported in earlier versions (<v5)??
