### ISSUE TITLE
issue:  unregister with flag "keepDefaultValue: true"

### ISSUE THREAD

**Issue by Davi9130** [react-hook-form/react-hook-form#9471]
### Version Number

7.29.0

### Codesandbox/Expo snack

a

### Steps to reproduce

Try to set default values in an useEffect using reset(defaultValues) and after this when call unregister with flag "keepDefaultValue: true" don't replace the field with the defalut value, just delete the fieldArray entirely or the key in object white value.

### Expected behaviour

Restore the default values

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848
