### ISSUE TITLE
issue: isDirty flips to true when used as dependency in useEffect and default value is null

### ISSUE THREAD

**Issue by JoshMart** [react-hook-form/react-hook-form#9473]
### Version Number

7.39.7

### Codesandbox/Expo snack

https://codesandbox.io/s/priceless-hellman-bs8siy

### Steps to reproduce

1. Open codesandbox and observe initial values for Touched and Dirty are empty and isDirty is false in the console. Note different default values have been set for each fields: null and empty string. `useEffect` has been set up with `isDirty` as a dependency.
2. Gain focus on `null default` field via tab or click.
3. Lose focus on the field.
4. Observe `isDirty` has been flipped to true however Dirty still reports an empty array.
5. Refresh the page in codesandbox and verify inital state looks like described in step 1.
6. Gain focus on `empty string default` field via tab or click.
7. Lose focus on the field.
8. Observe no additional logging because `isDirty` remains false has not triggered `useEffect`.

### Expected behaviour

`isDirty` should not change its value if the user has touched the field, but not input any values regardless of the default value.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
native input `defaultValue` is `string` instead of `null`.

**Comment by JoshMart** [comment]
> native input `defaultValue` is `string` instead of `null`.

I'm sorry can you explain this further? The docs allow and recommend null as a default value--which I have set up. The user does not modify the value so the form should not be marked as dirty--only touched.

**Comment by JoshMart** [comment]
Additionally, why does `isDirty` return true but `dirtyFields` is an empty object?

**Comment by bluebill1049** [comment]
That's a valid issue, still, default value with null will cause an issue because the native input returns a string instead of `null` or `undefined`.  which means if you set as `null` it will never go back to prestine.

**Comment by JoshMart** [comment]
> 
I see what you mean. `null` is looking a lot less useful because the user won't be able to set it back to a clean state. 

Just tested the new build and the issue with `null` defaults has gone away. Thanks.
