### ISSUE TITLE
issue: Cannot assign to read only property '0' of object '[object Array]'

### ISSUE THREAD

**Issue by xanxus135** [react-hook-form/react-hook-form#9476]
### Version Number

7.39.7

### Codesandbox/Expo snack

sry, didn’t have

### Steps to reproduce

![image](https://user-images.githubusercontent.com/38207457/204716863-98ac76b3-ed56-41d9-b134-058698af9918.png)
i tried used setValue('list.0.key1','2') change the value
but throw error : Cannot assign to read only property '0' of object '[object Array]'

![image](https://user-images.githubusercontent.com/38207457/204717419-f7cce997-6517-416e-9212-b34a5def11c5.png)
i saw it's this line , failure to assign values
have any solve ideal?

### Expected behaviour

use setValue to set deep path value

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by bluebill1049** [comment]
Just a quick follow up, Did you figure out the issue?

**Comment by xanxus135** [comment]
@bluebill1049 
Yes, i found out was **types.frozen()** of **mobx-state-tree** to frozen the object, it was deep copy of the object from **useForm().getValues()**, i thought it should be run.
But throw that error. then i tried to used **volatile** to save the object into model, and this error was disappeared.
So i close this issue.
Actually, I don't understand why deep copy of the object, it will be affected other code.
