### ISSUE TITLE
Validate individual fields

### ISSUE THREAD

**Issue by SlDo** [react-hook-form/react-hook-form#9482]
**Is your feature request related to a problem? Please describe.**
Hello everybody! Recently I faced the problem of the impossibility of checking individual fields for validity. I have the following case: it is necessary to send a request for each input to one of the 10 fields (there are 15 of them in the form), but only send it when all 10 are valid. 

**Describe the solution you'd like**
It would be better to validate individual fields using the original passed schema or validation parameters

**Describe alternatives you've considered**
Of course, you can check using the errors and IsDirty object, but, for example, we have autofill fields.

**Comment by bluebill1049** [comment]
So you want to keep track of all `valid` fields? A new validFields State?

**Comment by SlDo** [comment]
> So you want to keep track of all `valid` fields? A new validFields State?

yes, as an option, do so

**Comment by bluebill1049** [comment]
ok, thanks moving it into project board, we had `validFields` props before, but it has some difficult and bugs around it, but worth relooking into it again.
