### ISSUE TITLE
focusErrorField while using setError

### ISSUE THREAD

**Issue by falkenhawk** [react-hook-form/react-hook-form#949]
Would it be possible to focus first field with error while using `setError`? The functionality already exists in the code - there is `focusErrorField` being called in the `handleSubmit` function, maybe the same thing could be called inside `setError` function? (possibly as an opt-in feature, triggered by an additional option / argument e.g. `setError([...], { focusErrorField: true })`).

My case:
I am using api-platform with hydra jsonld format as a backend. When I submit a form, I may expect some errors coming from the api. I would like to set the errors to the form and have the first field with an error focused for better UX. Having that handled by `setError` would greatly reduce boilerplate code handling it, especially on large forms. (here I'm referring to handling refs manually for all the fields as per https://github.com/react-hook-form/react-hook-form/issues/230#issuecomment-527685852)

Example:
```typescript
  const onSubmit = async (data: any) => {
    try {
      await axios.post('/api/clients', {
        ...data,
      });
    } catch (error) {
      let message = 'An error occurred';

      const e: AxiosError = error;
      if (e.isAxiosError && e.response?.status && e.response.status < 500) {
        const { data } = e.response;
        message = data['hydra:title'];

        // i am setting possibly multiple errors within one setError call.
        // it would be great if this could focus the first field with an error,
        // e.g. with `setError([...], { focusErrorField: true })`
        setError(
          data?.violations.map((violation: any) => ({
            type: 'api',
            name: violation.propertyPath,
            message: violation.message,
          }))
        );
      } else {
        console.log(e);
      }

      alert(message);
    }
  };

```

PS. thanks for this awesome lib!

**Comment by bluebill1049** [comment]
hey @falkenhawk thanks for this great suggestion. consider the current API is already quite long...

`(name: string | ManualFieldError[], type?: string | Object, message?: string) => void`

if we need to make such a change, we may have to make a breaking change.

```
set({
   ...,
})
```

I will put a tag on this feature request and placed it to my backlog, for now, we can investigate the future when we move to the next major release.

**Comment by falkenhawk** [comment]
@bluebill1049 thanks for the super-fast response! (but it's Sunday, man!)
On second thought, maybe it would not be the best idea to add another argument to `setErrors` function, and complicate it even more, but expose another function in `FormContextValues` - returned from `useForm()` hook? That won't cause a BC break and maybe won't have to wait for a major release, because everything what's necessary is already implemented.

Namely: a `focusErrorField` function - which would use `fieldsRef` and `errorsRef` internally - which would try to focus first field with an error.

then in my case:
```typescript
const { register, handleSubmit, errors, setError, focusErrorField } = useForm();

(...)
        setError(
          data?.violations.map((violation: any) => ({
            type: 'api',
            name: violation.propertyPath,
            message: violation.message,
          }))
        );
        focusErrorField(); // here
```

**Comment by bluebill1049** [comment]
> @bluebill1049 thanks for the super-fast response! (but it's Sunday, man!)
> On second thought, maybe it would not be the best idea to add another argument to `setErrors` function, and complicate it even more, but what about exposing another function in `FormContextValues` - returned from `useForm()` hook? That won't cause a BC break and maybe won't have to wait for a major release, because everything necessary is already implemented.
> 
> Namely: a `focusErrorField` function - which would use `fieldsRef` and `errorsRef` internally - which would try to focus first field with an error.
> 
> then in my case:
> 
> ```ts
> const { register, handleSubmit, errors, setError, focusErrorField } = useForm();
> 
> (...)
>         setError(
>           data?.violations.map((violation: any) => ({
>             type: 'api',
>             name: violation.propertyPath,
>             message: violation.message,
>           }))
>         );
>         focusErrorField(); // here
> ```

yea I did consider to add another method too, the tradeoff is increased the lib's amount of API, which against the simplicity of his lib. less APIs is better for us (developers)

**Comment by Cow258** [comment]
What is the solution before this new feature released?
How do I focus the input manually when `ref` is used by `register`?

**Comment by bluebill1049** [comment]
> What is the solution before this new feature released?
> How do I focus the input manually when `ref` is used by `register`?

you can always get the `ref` object and call focus. 
```
ref={(ref) => {
  ref; // you can store this as reference;
  register(ref);
}}
```

**Comment by Cow258** [comment]
> > What is the solution before this new feature released?
> > How do I focus the input manually when `ref` is used by `register`?
> 
> you can always get the `ref` object and call focus.
> 
> ```
> ref={(ref) => {
>   ref; // you can store this as reference;
>   register(ref);
> }}
> ```

Like this? 👀
 ```js
ref={(ref) => {
  ref; // you can store this as reference;
  register(ref, { required: true, validate: () => {}});
}}
```

**Comment by bluebill1049** [comment]
yes @Cow258

**Comment by bluebill1049** [comment]
perhaps we could have this

`setError('test', { message: 'missing name', type: 'required', shouldFocus: true })`
