### ISSUE TITLE
Persist Multi steps form in Next js

### ISSUE THREAD

**Issue by asimhyff** [react-hook-form/react-hook-form#950]
https://www.youtube.com/watch?v=CeAkxVwsyMU

In this video of multi steps form, we are using push function which is getting from react-router-dom to go to step 2 but in Next js, we use it's next/Link library instead so what we will use to go to step2 in it?

![image](https://user-images.githubusercontent.com/56485049/73612495-12602a00-460e-11ea-9185-0f42b79cbf9c.png)

**Comment by bluebill1049** [comment]
hey, @asimhyff I believe it's the same:

https://nextjs.org/docs/api-reference/next/router

you can use `router.push()`. let me know if you still have other questions.
