### ISSUE TITLE
issue: Property 'message' does not exist on type FieldError for field array item value with key `type`

### ISSUE THREAD

**Issue by adesurirey** [react-hook-form/react-hook-form#9500]
### Version Number

v7.40.0

### Codesandbox/Expo snack

https://stackblitz.com/edit/react-ts-kdaue9?file=App.tsx

### Steps to reproduce

1. Create a field array with `useFieldArray` for a form value of type `T extends { type: any }[]`
2. Get error messages for every `type` in T
4. See TS error on `.message`

### Expected behaviour

It should not raise an error 

### What browsers are you seeing the problem on?

Chrome

### Relevant log output
```
Property 'message' does not exist on type 'FieldError | LiteralUnion<"onBlur" | "onChange" | "shouldUnregister" | "required" | "min" | "max" | "maxLength" | "minLength" | "pattern" | "validate" | "valueAsNumber" | ... 4 more ... | "deps", string>'.
  Property 'message' does not exist on type '"onBlur"'.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`type` is a reserved word for error type. We can consider renaming it in the next major update.

**Comment by adesurirey** [comment]
At least we can access the error message, it's just a TS error: https://stackblitz.com/edit/react-ts-jmc8ku?file=App.tsx,index.tsx
