### ISSUE TITLE
issue: `value` from `WatchObserver` is always undefined 

### ISSUE THREAD

**Issue by nichita-pasecinic** [react-hook-form/react-hook-form#9503]
### Version Number

^7.39.7

### Codesandbox/Expo snack

/

### Steps to reproduce

`value` field return in `info` param from the `watch` callback is always `undefined` (even though the `values` field [first argument] is updated with the actual value)

Pretty simple to reproduce 

```ts
  const formMethods = useForm<AddFormEntityTypeFieldsType>({
    mode: 'onTouched',
    resolver,
    defaultValues,
  });
  const { watch, setValue, reset, getValues } = formMethods;

  // ....

  useEffect(() => {
    const sub = watch((formValues, info) => {
      const { name: fieldName, type: eventType, value } = info;
      console.log(fieldName, ' changed: ', eventType, ', newValue: ', value);
    });
    // unsubscribe from watching fields change
    return () => {
      console.log('will unsubscribe');
      sub.unsubscribe();
    };
  }, [watch]);
```

### Expected behaviour

`value` should be update with every triggered field update

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by nichita-pasecinic** [comment]
@bluebill1049 sorry for not following template, hope [this one](https://github.com/react-hook-form/react-hook-form/issues/9509) follows it!
