### ISSUE TITLE
issue: `useWatch` does not return the initial value when using a dynamic `name`

### ISSUE THREAD

**Issue by andrewmtam** [react-hook-form/react-hook-form#9506]
### Version Number

7.40.0

### Codesandbox/Expo snack

https://codesandbox.io/s/brave-darwin-ssyic4?file=/src/App.tsx:363-429

### Steps to reproduce

1. Go to codesandbox
2. Notice that "Async Value" is not properly getting watching the dynamic field name

### Expected behaviour

When a fieldName is dynamically set into `useWatch`, it should subscribe to the new field and return the value

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

I believe this is the offending code:

https://github.com/react-hook-form/react-hook-form/blob/6beb0eef12e6b194693b7519dc84fbaf5a7a001e/src/useWatch.ts#L186-L192

I think all that needs to happen is that we need to setup a `useEffect` such that when `name` changes, we rerun the initial state logic.

E.g. something to this effect:

```typescript
    React.useEffect(() => {
        updateValue(isUndefined(defaultValue)
            ? control._getWatch(name as InternalFieldName)
            : defaultValue)
    }, [updateValue, name])

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
The current implementation name is cached, you can submit a feature request instead so we can consider supporting a dynamic name.
