### ISSUE TITLE
Support for dynamic `name` parameter in `useWatch` 

### ISSUE THREAD

**Issue by andrewmtam** [react-hook-form/react-hook-form#9507]
**Is your feature request related to a problem? Please describe.**
When supplying a dynamic `name` to `useWatch`, the returned value is not changed when `name` changes.
 
**Describe the solution you'd like**
In `const myValue = useWatch({name: myDynamicFieldName})`, if `myDynamicFieldName` changes, I'd like to see `myValue` change to reflect the value of the new field name.

The use-case is not so much to allow multiple fieldnames, its more so for the scenario where `myDynamicFieldName` goes from undefined/empty string to a known value.

**Describe alternatives you've considered**
* Use `form.watch`, but this is slightly less performant.
* Do the async handling in a component one-level up, so that by the time the component that calls `useWatch` mounts, `myDynamicFieldName` will already have been resolved.

**Additional context**

**Comment by bluebill1049** [comment]
thanks, moving to the feature request board.

**Comment by andrewmtam** [comment]
Thanks, appreciate it!
