### ISSUE TITLE
issue: value from WatchObserver is always undefined

### ISSUE THREAD

**Issue by nichita-pasecinic** [react-hook-form/react-hook-form#9509]
### Version Number

^7.39.7

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-watch1-forked-pwiuwg?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/react-hook-form-watch1-forked-pwiuwg?file=/src/App.js
2. Type something into name input
3. see in console that `value` from `info` parameter is always undefined 

`value` field return in `info` param from the watch callback is always undefined (even though the values field [first argument] is updated with the actual value)

```ts
  const methods = useForm({
    // mode: "onBlur",
    // reValidateMode: "onBlur",
    defaultValues: {
      name: "name"
    }
  });
  const { watch } = methods;

  useEffect(() => {
    // value is allways undefined here
    const sub = watch((data, { name, type, value }) => {
      console.log("field: ", name, " type: ", type, " newValue: ", value);
    });
    return () => sub.unsubscribe();
  }, [watch]);
```

### Expected behaviour

Value to get updated properly on every change.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
From codesandbox:


name field watched from outside:  namesss 
field:  name  type:  change  newValue:  undefined

name field watched from outside:  namessss 
field:  name  type:  change  newValue:  undefined

name field watched from outside:  namesssss 
field:  name  type:  change  newValue:  undefined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks for the updated issue, the callback itself doesn't return value for the particular input instead of the `data` object: https://react-hook-form.com/api/useform/watch (if you refer to the doc)

**Comment by bluebill1049** [comment]
<img width="961" alt="Screenshot 2022-12-03 at 10 06 51 pm" src="https://user-images.githubusercontent.com/10513364/205437821-8c3d6462-35ff-4f3c-9ea2-2eba2efeb9e7.png">

it's a type bug, we actually not supply the value... thanks for the bug report!

**Comment by nichita-pasecinic** [comment]
@bluebill1049 Thx for quick response, so the actual value should be read from firs argument (`data`), yes ?

Also a informative question, there is a lot of possible values for the `type` property (it could be `undefined`, `changed`, ....)
Where I could inform myself under what circumstances is each of them used ?
