### ISSUE TITLE
custom ID with useFieldArray doesn't work

### ISSUE THREAD

**Issue by tomas-c** [react-hook-form/react-hook-form#951]
**Describe the bug**
When using useFieldArray, if an array field has custom ID set then dirty state detection doesn't work.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-dirty-state-with-custom-id-kpq7f
2. Click on append and then remove the appended item
3. Observe that formState.dirty is still false.

**Additional context**
 - Version 4.8.0

This works fine if the code that sets the initial field IDs is removed.

**Comment by bluebill1049** [comment]
hey @tomas-c I don't think we will support this custom id. however, I do see the point of this issue, because `id` could potentially come from your database and it's part of the form. so i would suggest not to use `id` field at this moment. 

here is my proposal:
```
useFieldArray({
  idName: 'id' // deafult and you can rename to others
})
```

**Comment by tomas-c** [comment]
I like the rename option because without it would be difficult to tell apart IDs generated by react-hook-form and IDs from a database. Will TypeScript typings for fields play well with the keyName option?

**Comment by bluebill1049** [comment]
> I like the rename option because otherwise it would be difficult to tell apart IDs generated by react-hook-form and IDs from a database. Will TypeScript typings for fields play well with the keyName option?

Probably just a string type

**Comment by tomas-c** [comment]
Currently, the type for `fields` is defined as `fields: WithFieldId<Partial<FormArrayValues>>[];`. If `keyName` argument is introduced, then we'll have to just use `fields: Partial<FormArrayValues>[];` and expect the user to add the definition of the key field to FormArrayValues. Unless there's some typescript magic to have `WithFieldId` work with configurable id field names... 

Another way could be to have something like:

```
type FieldType { email: string };
const { fields, fieldKeys } = useFieldArray<FieldType>({ populateIds: false });
{fields.map((item, index) => {
   <input key={fieldKeys[index]} defaultValue={field.email} />
});
```

Or to decouple field id and field data:

```
type FieldType { email: string };
const { fields } = useFieldArray<FieldType>({ decouple: true });
{fields.map((item, index) => {
   <input key={fields[index].id} defaultValue={fields[index].data.email}>
});
```

**Comment by bluebill1049** [comment]
Hmmm I see... I will take a closer look at it later on.

**Comment by tomas-c** [comment]
I like decoupling option because we can also have a separate field for the name:

```
type FieldType { email: string };
const { fields } = useFieldArray<FieldType>({ decouple: true });
{fields.map((item, index) => {
   <input key={fields[index].id} name={field[index].name} defaultValue={fields[index].data.email}>
});
```

users would not need to do ``name={`field[${index}.email]`}`` and instead could do a safer type-checked `name={field[index].name}`

**Comment by bluebill1049** [comment]
we definitely need this unique `id`, because we are working with input uncontrolled.

**Comment by tomas-c** [comment]
I think something got mixed up here, not suggesting we get rid of the id. All the examples have it.

**Comment by bluebill1049** [comment]
Oh cop sorry I will read it more closely tonight
