### ISSUE TITLE
Breaking change between `7.22.4` & `7.22.5`

### ISSUE THREAD

**Issue by o-alexandrov** [react-hook-form/react-hook-form#9524]
### Version Number

7.22.5

### Codesandbox/Expo snack

https://codesandbox.io/s/sharp-margulis-wf7myr

### Steps to reproduce

1. Go to provided Codesandbox
2. Use version `7.22.5`
3. Open console
4. Click on `Set name to undefined`
5. Observe the bug: `FieldController` doesn't get an value update (no console)

Go back to step 2, use version `7.22.4`, repeat steps, and see that it correctly updates the value to `undefined` and triggers an update (console statement is invoked)

### Expected behaviour

- `setValue` to `undefined` triggers an update and does update the value to `undefined` (currently it doesn't)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Thanks for the issue report, however, please refer to the doc `undefined` value is not supported. The patch is most likely due to a bug fix,  and you can consider using another type of default value instead.

**Comment by o-alexandrov** [comment]
@bluebill1049 how do you suggest to remove a value from form values?

**Comment by o-alexandrov** [comment]
Btw, the breaking change was introduced in[ this set of change and in this file](https://github.com/react-hook-form/react-hook-form/compare/v7.25.3...v7.26.0#diff-5a85c1643c71f45e050ce584d7c0db2bdf2e56f8a7dae86d74fedf01be2d2cab)

**Comment by o-alexandrov** [comment]
The input exists, the value is removed from a form.
Based on your message and the logic behind removal of a feature to `setValue(fieldName, undefined)`, I guess you believe a user-developer should:
- unregister
- and register again

**Comment by o-alexandrov** [comment]
The really bad part here is:
- `setValue` doesn't complain in the provided code sandbox that `undefined` is not allowed

So many other devs would stumble on this error

**Comment by bluebill1049** [comment]
> setValue doesn't complain in the provided code sandbox that undefined is not allowed

It's a valid point above, I will tighten up the type. Everything else will stay the same.

**Comment by o-alexandrov** [comment]
So there will be no way to remove a value.
No alternative to previous:
setValue(fieldName, undefined)

I hope you will reconsider, as many developers looking at this issue would probably lose trust in this library to be safe  long-term, especially with breaking changes in patch versions.

**Comment by o-alexandrov** [comment]
> > setValue doesn't complain in the provided code sandbox that undefined is not allowed
> 
> It's a valid point above, I will tighten up the type. Everything else will stay the same.

Even if change typings, it won’t help devs in all cases, as `event’s target` in inputs is typed in a way that it’s always truthy.
- as well as it’s naive to think deeply nested fields using useFormContext would be all correctly typed on a possible`undefined` value
