### ISSUE TITLE
issue: cannot share a useFieldArray component with different control and name (TypeScript errors)

### ISSUE THREAD

**Issue by adesurirey** [react-hook-form/react-hook-form#9527]
### Version Number

v7.40.0

### Codesandbox/Expo snack

 https://stackblitz.com/edit/react-ts-drzwwh?file=App.tsx

### Steps to reproduce

- Create 2 forms with a common value but responding to different keys, e.g.: 
```ts
interface Item {
  key: string;
}
interface A {
  items: Item[];
}
interface B {
  data: {
    items: Item[];
  };
}
```

- Create a component to handle `Item` values, using `useFieldArray`
- Use this component in both forms A and B for `items` and `data.items`
- TypeScript errors appear

### Expected behaviour

We should be able to use `useFieldArray` with different control and name values with types like this: 
```ts
interface ItemFormFieldsProps<TControl extends Control<A> | Control<B>> {
  control: TControl;
  name: TControl extends Control<A> ? 'items' : 'data.items';
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is a design limitation with union type. here is some relevant comment from @felixschorer https://github.com/react-hook-form/react-hook-form/issues/8815#issuecomment-1230723876
