### ISSUE TITLE
Ability to perform validation during onSubmit in a modular way

### ISSUE THREAD

**Issue by timkindberg** [react-hook-form/react-hook-form#9533]
**Is your feature request related to a problem? Please describe.**
There has been several times that I've wanted to "intercept" the form submission without having to register a field. For example if I have a cross-field error that needs to take into account multiple fields. Or I may want to modify my own state during submission, to show that a section is done or something. Currently the only way to get some logic to occur during submission is to either:
1. Put that logic into the submit handler at the top of the form
2. Put validation logic into register or useController

Our team HIGHLY prefers keeping all form fields fully modular. We define everything about that field within the nested component: default values, validation, dependencies on other fields using watches, etc. This allows us to plug-n-play our common fields into various forms.

We'd like a way to modularly intercept the submission similar to how validate works, but ONLY during submission explicitly. (I think a similar thing could be useful for intercepting the onError callback as well, but that's a bit out of scope).

**Describe the solution you'd like**
I'd like to be able to register a validation only without an associated field, so something like this where `name` is not needed when calling `register`:
```ts
register({
  validate(allValues) {
    // do some validation here
  }
})
```

**Describe alternatives you've considered**
One alternative is to use `register` and just add a field that I can ignore later during submit, similar to this: 
https://stackblitz.com/edit/react-ts-tv7gkl?file=App.tsx

**Additional context**
In general too I think this ability to tap into the submission just gives more flexibility to the library.

**Comment by bluebill1049** [comment]
I think we can consider adding a type for the `validate` function then, it can potentially give you the flexibility on when to fire the validation.

**Comment by timkindberg** [comment]
😍 thank you!!

**Comment by timkindberg** [comment]
What are your thoughts about the part of this request where we can run a validation that is **not** associated with a particular field?

**Comment by bluebill1049** [comment]
- if it's none related field, you can use `setError` method
```tsx
onChange={() => {
  if (...) {
    // setError()
  }
}}
```

- if it's a global level error at submit, this probably gets resolved with a global error which will come next year. eg
```tsx
onSubmit={() => {
  throw new Error('globalErro') // global error
  await fetch() // fetch error will result global error as well
}}
```

**Comment by bluebill1049** [comment]
Thanks for the feedback and kind words ❤️ 

I am trying to not overextend the API unless 100% needed:

```tsx
// Just some ideas
function SomeNestedField() {
  useFormEvent('submit', (values) => {
    // return a promise will cause submission to wait
    return new Promise(...)
    
    // return undefined will cause no changes
    return undefined
    
    // return an ValidationError will be a validation error
    return new ValidationError('fieldName', 'message')
    
    // return an object, will replace values
    return { ...values, foo: 'some new value for foo' }
    
    // return null prevents submit from proceeding
    return null
  })
}
```

I think I am getting your point now, you want to run some conditional logic before onSubmit but not related to form. i think it's quite simple to achieve in today's world.

```tsx
onSubmit={(e) => {
 // do your validation here before execute the next line 
  handleSumbit(callback)(e)
}}

```

**Comment by timkindberg** [comment]
You are welcome. Yes you are getting my point except the one piece I am looking for is I would like to be able to do validation NOT WITHIN onSubmit. I want to be able to do that logic somewhere deep down nested in a component (see how I named my component "SomeNestedField"?). Thank you again. As long as the idea is conveyed correctly then I am satisfied for now. Thank you @bluebill1049.
