### ISSUE TITLE
[TypeScript] ErrorMessage Component accept no props any more in version 4.8.0

### ISSUE THREAD

**Issue by omarkhatibco** [react-hook-form/react-hook-form#954]
**Describe the bug**
after I updated to v4.8.0 I got this error message from Typescript 
on the `className` and `name` props

```
Type 'string' is not assignable to type 'never'.ts(2322)
```
<img width="607" alt="Screenshot 2020-02-02 at 22 54 16" src="https://user-images.githubusercontent.com/9054278/73616064-1ccef380-460f-11ea-95f2-249025025465.png">

also `errors` prop got this following error

```
Type 'NestDataObject<Record<string, any>>' is not assignable to type 'never'.ts(2322)
```

**Comment by bluebill1049** [comment]
You want to help and take a look this issue @kotarella1110

**Comment by omarkhatibco** [comment]
I tried to revert to v4.7.2 and it's seems also affected.
the last working version is 4.7.1

**Comment by bluebill1049** [comment]
Thanks for the update :) our team member @kotarella1110 should be able to help out on this one.

**Comment by kotarella1110** [comment]
@omarkhatibco we can pass `className` prop only if we also passed the `as` prop, because you can't have `className` as a prop on `React.Fragment`.
It works correctly by passing the `as` prop.

```ts
<ErrorMessage as="p" className="test" name={name} errors={errors} />
```

**Comment by omarkhatibco** [comment]
@kotarella1110  thanks it works !

The problem is `as` prop is not mentioned in the documentation.

**Comment by bluebill1049** [comment]
it's there @omarkhatibco take a look :) 

https://react-hook-form.com/api#ErrorMessage

**Comment by bluebill1049** [comment]
thanks @kotarella1110 🙉

**Comment by omarkhatibco** [comment]
@bluebill1049  but it's required now ?

**Comment by bluebill1049** [comment]
hmmm it shouldn't be required. @kotarella1110 is it required?

**Comment by omarkhatibco** [comment]
@bluebill1049 because if i did not assign `as` props I got the error messages above for both `name` and `errors`

**Comment by bluebill1049** [comment]
i think this maybe an issue here:

```
export type ErrorMessageProps<
  Errors extends FieldErrors<any>,
  Name extends FieldName<FormValuesFromErrors<Errors>>,
  As extends
    | undefined
    | React.ReactElement
    | keyof JSX.IntrinsicElements = undefined
> = {
  as?: As;
  errors?: Errors;
  name: Name;
  message?: string;
  children?: (data: {
    message: string;
    messages: MultipleFieldErrors;
  }) => React.ReactNode;
} & AsProps<As>; // is it due to this @kotarella1110 
```

**Comment by kotarella1110** [comment]
@omarkhatibco not required.

https://codesandbox.io/s/rhf-issues-954-wl42r

<img width="575" alt="スクリーンショット 2020-02-03 17 55 05" src="https://user-images.githubusercontent.com/12913947/73638763-64588c80-46ae-11ea-9450-c4a7ddd1770d.png">

**Comment by bluebill1049** [comment]
@kotarella1110 type error on your last component where as is missing.

**Comment by omarkhatibco** [comment]
@kotarella1110 type of `name` is never when as is missing
![Screenshot 2020-02-03 at 10 01 51](https://user-images.githubusercontent.com/9054278/73639244-4407de00-466c-11ea-9ef3-a84e78e7095d.png)

**Comment by kotarella1110** [comment]
@bluebill1049 the type error is correct! because we can't have className as a prop on `React.Fragment`.

```ts
<React.Fragment className="test" /> // Warning: Invalid prop `className` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.
```

@omarkhatibco plz provide codecodesandbox example.

**Comment by bluebill1049** [comment]
wow type is great! great job @kotarella1110

**Comment by kotarella1110** [comment]
This has not been resolved yet.
Passing the `name` and `errors` prop shouldn't cause type error.

```ts
<ErrorMessage name={name} errors={errors} /> // no type error
```

I will wait for @omarkhatibco to provide codesandbox.

**Comment by omarkhatibco** [comment]
Hi @kotarella1110 
you could check it here 
https://codesandbox.io/s/rhf-issues-954-51g6k

to ease it for you, maybe something is wrong with `tsconfig`

**Comment by kotarella1110** [comment]
I'm busy today, so I wil see it tomorrow.

**Comment by omarkhatibco** [comment]
@kotarella1110 ok, Thanks for you

**Comment by kotarella1110** [comment]
@omarkhatibco Causes this type error when `strict` is disabled(`false`) in Compiler Option(`tsconfig.json`).
I will fix.
