### ISSUE TITLE
Dirty state detection is not working correctly with field arrays

### ISSUE THREAD

**Issue by tomas-c** [react-hook-form/react-hook-form#955]
**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-change-detection-jdkhj
2. Click on the input with "useFieldArray0" value
3. Enter a single character and observe formState.dirty=false
4. Enter a second character and observe formState.dirty=true
5. ~Delete the two characters and observe the state is still formState.dirty=true~

**Expected behavior**

formState.dirty should be true after entering the first character ~and should reset to false when the input value is back to the initial value.~

**Additional context**
This does not happen with non-array fields.

**Comment by bluebill1049** [comment]
strange... consider i even added automation test for this dirty check.... will take a look

**Comment by bluebill1049** [comment]
This issue is not valid: you are not using the id from RHF
```
const defaultValues = {
    singleField: "singleField",
    test: [
      { id: "id0", name: "useFieldArray0" },
      { id: "id1", name: "useFieldArray1" }
    ]
  };
```

**Comment by tomas-c** [comment]
@bluebill1049 I've removed the hardcoded IDs left over from copying the sandbox. Now the formState.dirty correctly resets but I still need to type at least two characters to have it update to true.

**Comment by bluebill1049** [comment]
ok that's a seperate issue then, i will take a look tonight.

**Comment by bluebill1049** [comment]
can you help on replicated on this demo: https://codesandbox.io/s/react-hook-form-usefieldarray-vy8fv? help me nail on what's trigger this issue. thanks a lot

**Comment by bluebill1049** [comment]
nvm i found the bug. patching.
