### ISSUE TITLE
issue: `handleSubmit` and `getValues` data is of invalid type for numbers once value changes

### ISSUE THREAD

**Issue by Aerophite** [react-hook-form/react-hook-form#9556]
### Version Number

7.40.0

### Codesandbox/Expo snack

https://stackblitz.com/edit/react-ts-mvzsqn?file=App.tsx

### Steps to reproduce

1. Make sure the console is open
2. Click on the "Submit" button and you'll see two console logs indicating the data type is "number" (correct)
3. Modify the input's value to a different number
4. Click on the "Submit" button again and you'll now see two console logs indicating the data type is "string" (incorrect)

### Expected behaviour

After modifying a value that is of type "number", the type should _still_ be of type "number" when calling `handleSubmit` or `getValues`.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
In the current RHF API, it's the user's responsibility to set [`register`](https://react-hook-form.com/api/useform/register) `valueAs(Number | Date): true` or `setValueAs: value => convertValue(value)` prop to convert the native input `value` of type `string` to the desired type

```

**Comment by Aerophite** [comment]
Makes sense. Thanks!
