### ISSUE TITLE
React Native: Can't find variable: FileList - "react-hook-form": "^4.8.0",

### ISSUE THREAD

**Issue by cdelcol** [react-hook-form/react-hook-form#956]
**Describe the bug**
An error unrelated to the form occurs after updating a redux store

> Can't find variable: FileList
> - node_modules/react-hook-form/dist/react-hook-form.js:583:4 in <global>
> * http://192.168.2.109:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:171317:132 in unsetObject
> - node_modules/react-hook-form/dist/react-hook-form.js:893:26 in useForm

I updated the following, and everything works as expected:

` node_modules/react-hook-form/dist/react-hook-form.js, Line 583`
from
`var isFileListObject = (data) => data instanceof FileList;`
to
`var isFileListObject = (data) => true`

**Screenshots**
![image](https://user-images.githubusercontent.com/411488/73617070-f7c78a00-45e8-11ea-8da5-20c5c2909a78.png)

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - React Native/expo

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 10

**Comment by bluebill1049** [comment]
oops that was my bad, will adjust that
