### ISSUE TITLE
issue: compare Dates for dirtyFields

### ISSUE THREAD

**Issue by Shchepotin** [react-hook-form/react-hook-form#9562]
### Version Number

6

### Codesandbox/Expo snack

https://codesandbox.io/s/peaceful-pare-f5pyyi?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/peaceful-pare-f5pyyi?file=/src/App.tsx and open console. By default date is `12/09/2022`. `dirtyFields {}`
    <img width="564" alt="image" src="https://user-images.githubusercontent.com/6001723/206672598-055e2626-77e4-465e-bd85-97c843f212f4.png">
1. Click on datepicker and select another date (for example `12/10/2022`). `dirtyFields { date: true }` is OK
    <img width="567" alt="image" src="https://user-images.githubusercontent.com/6001723/206673290-628e171b-e0fb-41c4-bcb9-b253bea5d129.png">
1. Change date back to `12/09/2022`. dirtyFields still `dirtyFields { date: true }` but must be `dirtyFields {}`
<img width="564" alt="image" src="https://user-images.githubusercontent.com/6001723/206673603-4a27f86c-e644-4c73-b265-848e61c97758.png">

### Expected behaviour

Comparing dates must be correct.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Thanks for the PR, I would prefer to make a change V6 as it's deprecated and almost 2 years behind.

**Comment by Shchepotin** [comment]
@bluebill1049 we cannot update version to v7 on our project right now. Also looks like this not a big change, just bug fixing.

These changes will save a lot of time and money for us 🙏

**Comment by bluebill1049** [comment]
I would suggest you fork the repo and just publish a version out of it from v6 instead. V6 will no longer publish new versions.

**Comment by Shchepotin** [comment]
@bluebill1049 got it

**Comment by bluebill1049** [comment]
Thanks for your understanding.
