### ISSUE TITLE
validate number with required

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#9571]
### Version Number

7.40.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-tabs-problems-01-required-numbers-kmy5jp?file=%2Fsrc%2FApp.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/react-hook-form-tabs-problems-01-required-numbers-kmy5jp?file=%2Fsrc%2FApp.tsx
2. Click on submit (without clicking on any other tabs)
3. Look at console log
4. You should see `errors {prop2: Object, prop3: Object}`

### Expected behaviour

Form should submit without any errors since the default values have been provided for all required inputs. The exact same thing but with "text" inputs works as expected and submits the form with all data from `defaultValues` and no errors as can be seen in this sandbox: https://codesandbox.io/s/react-hook-form-tabs-problems-01-required-strings-9btufh?file=%2Fsrc%2FApp.tsx.

### What browsers are you seeing the problem on?

Firefox, Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

_Originally posted by @elieven in https://github.com/react-hook-form/react-hook-form/discussions/9568_

**Comment by elieven** [comment]
Lovely to see the fix. Any idea when a release with it included might be available?

**Comment by bluebill1049** [comment]
next week.
