### ISSUE TITLE
How to unit tess react-hook form with jest and enzyme?

### ISSUE THREAD

**Issue by DhanushkumarSivaji** [react-hook-form/react-hook-form#958]
Is there any working example like form submission or something in jest & enzyme ?

**Comment by bluebill1049** [comment]
Can you please post questions in our spectrum channel and do a search there as well? i think it's been asked before.

**Comment by DhanushkumarSivaji** [comment]
where can i find your spectrum channel ?

**Comment by DarkSouls101** [comment]
https://spectrum.chat/react-hook-form?tab=posts
