### ISSUE TITLE
issue: validate() accepts returning a string[] array but error messages cannot be accessed

### ISSUE THREAD

**Issue by jrmyio** [react-hook-form/react-hook-form#9581]
### Version Number

7.40.0

### Codesandbox/Expo snack

https://codesandbox.io/s/broken-snow-9f00jc?file=/src/App.tsx:835-855

### Steps to reproduce

Return a string[] from a `validate() `function:
validate: () => ["error1", "error2"]

### Expected behaviour

I expect both errors to be accessible in the errors object, but the error[fieldName].message is an empty string.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I will fix this type, we wouldn't support an array of strings, as this would cost a breaking change in order to support.
