### ISSUE TITLE
issue: 'isValidating' state is not updated after triggering validation

### ISSUE THREAD

**Issue by ivanovserge** [react-hook-form/react-hook-form#9582]
### Version Number

7.40.0

### Codesandbox/Expo snack

https://codesandbox.io/s/rhf-bug-with-isvalidating-state-bhym4v

### Steps to reproduce

1. Click on 'Validate'
2. See error

### Expected behaviour

'Validate' button should not be disabled because validation just has been triggered.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
As a quick workaround, you can get the `formState` from `useFormContext` instead of `useFormState` like
```diff
-  const { trigger } = useFormContext()
+  const { trigger, formState } = useFormContext()
-  const { isValidating } = useFormState()
+  const { isValidating } = formState
```

**Comment by bluebill1049** [comment]
Thanks @Moshyfawn 

@ivanovserge This is fixed and will be released this week. https://github.com/react-hook-form/react-hook-form/issues/9521
