### ISSUE TITLE
issue: formState.errors always undefined or empty when using remix.run

### ISSUE THREAD

**Issue by aniravi24** [react-hook-form/react-hook-form#9597]
### Version Number

7.40.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/snowy-monad-o6o647?file=%2Fapp%2Froutes%2Findex.tsx

### Steps to reproduce

1. If you try typing 2 or more characters in the input field (based on the zod validator definition), you'll see the button change color when it's enabled.
2. However, notice that when it's less than 2 characters, no errors are rendered on your screen or in your devtools logs next to the "ERRORS" keyword. It's either empty object or undefined, even when there's an error.
3. "validation result" will show the errors and values specifically.

Some more context:

I used a barebones remix template for the codesandbox instead of the suggested react-hook-form one (should be a bit simpler).

When I use mantine [TextInputs](https://mantine.dev/core/text-input/) instead of the native HTML input, the "ERRORS" log will show undefined instead of empty object. You can also observe the logs as you type to see the log output in your devtools.

There's also a way to ensure that components in Remix render client-side only, and even putting the component in a separate file and enforcing client-side rendering, the same problem persists.

First time using this library, really promising so far compared to other ones I've tried (including homegrown solutions), and hoping this can be fixed!

### Expected behaviour

Errors should be updating correctly in state, instead of showing empty object or undefined regardless of input changes. This happens even if you add more inputs and more validation.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
Having trouble copying the log output from devtools, but you'll see it immediately after following the reproduction steps listed above.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Could you share a codesandbox that can be reproduced with this issue?

**Comment by bluebill1049** [comment]
Thanks for the updated CSB. This is actually expected behaviour, in react hook form errors state will be optimised and reconciled before it pushes to the view. In your use case, it will only be updated with the user's blur action. 

## Why such a design?

We want the validation strategy for each form to be consistent and optimised for rendering and computation, which means you will no longer need to check another state to render errors. 


Other library show errors only when input is touched

```tsx
// need to check each touched state
touched.firstName && errors.firstName?.message
```

**vs**

In react hook form 

```tsx
// set up at the hook level
useForm({ mode: 'onTouched' })

errors.firstName?.message
```

**What if I want to force errors to be shown?**

```tsx
useEffect(() => {
  trigger()
}, [trigger])
```

Hope the above make more sense.

**Comment by aniravi24** [comment]
Oh wow, I'm so sorry for taking up your time, I read the first two sections on [this](https://react-hook-form.com/api/useform/) page of the docs before and I think I misunderstood (or just missed) what it was saying. What you mentioned was the issue, I just didn't set the mode option.

I must've thought it was working when testing with in a different environment cause the `revalidateMode` after form submission changes, so I must've submitted and modified form inputs, and then assumed the default behavior wasn't working the way I intended.

Thank you for your work on this library, looking forward to using it more!

**Comment by bluebill1049** [comment]
no worries @aniravi24 thank you for the kind words! ❤️

**Comment by bluebill1049** [comment]
Hi, @aniravi24 I just received the notification on the donation! Thank you so much for supporting this project! It really meant a to me, the rest of the team and everyone who worked on this project.

Have a great holiday break!
Billy

**Comment by aniravi24** [comment]
Hope you enjoy your holiday break as well! 🎉

**Comment by aniravi24** [comment]
@bluebill1049 hope you enjoy your holiday break as well!
