### ISSUE TITLE
Solution requested for issue that useFieldArray changes make all fields dirtyFields 

### ISSUE THREAD

**Issue by RobSchilderr** [react-hook-form/react-hook-form#9599]
**Is your feature request related to a problem? Please describe.**

Changes in 7.20.3 seem to cause useFieldArray changes to make all fields dirtyFields. In [this issue](https://github.com/react-hook-form/react-hook-form/issues/7197), [Moshyfawn](https://github.com/Moshyfawn) told [dbousamra](https://github.com/dbousamra) to create a feature request for his issue. This has not been done, yet the issue is still there as far as I am aware.

I am having the same issue right now. I want to use useFieldArray and dirtyFields, but whenever useFieldArray (by an append for instance), other fields in my form are marked as 'dirty'.

**Describe the solution you'd like**

Either go back to the behaviour of 7.20.2, but this original behaviour caused another  [issue](https://github.com/react-hook-form/react-hook-form/issues/7109)

 So as of right now, I do not see any way that we can mimic the same behaviour in the newer versions of RHF.

**Describe alternatives you've considered**

I considered downgrading to 7.20.2, yet this creates [another issue](https://github.com/react-hook-form/react-hook-form/discussions/6961) namely that this doesn't work with NextJS 12. Hence, we can not downgrade. 

**Additional context**

The only possible solution for now would be to write our own dirtyFields function, upon submitting, I suppose? Yet this isn't the ideal solution for many people. That's why I think an explanation from the RHF team would be nice. Thank you for maintaining this great package!

**Comment by bluebill1049** [comment]
Thanks for the feature request. I think we will resolve this feature next year by introducing config on each action, so whether fields are dirty or not is not optional.
