### ISSUE TITLE
issue: Valid inputs revalidating on change after form submission

### ISSUE THREAD

**Issue by zach-waggoner** [react-hook-form/react-hook-form#9604]
### Version Number

6.15.8

### Codesandbox/Expo snack

https://codesandbox.io/s/infallible-maria-47ku1g

### Steps to reproduce

1. Type something in the input.
2. Submit the form.
3. Clear the input.
4. See the error message ("ERROR").

### Expected behaviour

According to the V6 docs for `mode = "onSubmit"` (the default):

> Validation will trigger on the submit event and **invalid inputs** will attach onChange event listeners to re-validate them.

Further, the docs for the `reValidateMode` state:

> This option allows you to configure validation strategy when **inputs with errors** get re-validated after a user submits the form (onSubmit event).

Thus, I do not expect this input to get revalidated on change after it is submitted with valid input.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Thanks for the issue report, `handleSubmit` will always re-run will the entire form validation, we currently don't keep valid fields state as it is difficult and troublesome to track dependent validation or any external side effects.

**Comment by zach-waggoner** [comment]
I realize that `handleSubmit` re-runs the entire form validation. I am referring to the fact that a _change_ event on the input revalidates the input that was previously valid when the form was previously submitted, contradicting what is stated in the docs.

**Comment by bluebill1049** [comment]
thanks for the feedback.

> Validation will trigger on the submit event and invalid inputs will attach onChange event listeners to re-validate them.

I will adjust that, all input will be attached with validation, and even a valid input can turn into invalid.

**Comment by zach-waggoner** [comment]
Ok. I thought the documented behavior made pretty good sense—you may not want to revalidate _valid_ inputs on change, since, for example, that could cause a noisy error message if you delete what you typed in a required field in order to type something else. But it makes sense to revalidate _invalid_ inputs on change so that you can immediately see the error go away once you've corrected the value. And of course, even if a valid input turns into invalid, you will see that when you try to submit the form again, which is consistent with how the validation worked previously. Otherwise, the validation mode globally changes to `onChange` (assuming that is the revalidation mode) after the initial form submission, even if all inputs were valid and the form submission was successful. IMO that is unexpected and somewhat inconsistent—if I wanted validation to happen on change in general, I would have made that the validation mode. Just some thoughts about UX. Totally fine if you decide fixing the docs is the best way to resolve too.

**Comment by bluebill1049** [comment]
> Just some thoughts about UX, but all good if you decide fixing the docs is the best way to resolve. Thanks for the helpful library.

Thanks for the detailed explanation and understanding, I have updated the doc to reflect the above.

**Comment by ioev** [comment]
I'm running into the same issue here.  I have a form that populates from the querystring, and then submits, mode is onSubmit, revalidateMode is onSubmit, but the validation behaviour appears to always be onChange.

Is there any way we can have an option that only validates onSubmit, and won't even attach onChange event handlers?  I kind of figured that is what revalidateMode: onSubmit would do, but it doesn't appear to behave this way beyond the first submit.
