### ISSUE TITLE
issue: elm.focus runtime exception

### ISSUE THREAD

**Issue by mazenkhalil** [react-hook-form/react-hook-form#9608]
### Version Number

latest

### Codesandbox/Expo snack

NA

### Steps to reproduce

Runtime exception thrown as side effect from the below commit.

https://github.com/react-hook-form/react-hook-form/pull/9130/commits/a54394a3f8bbd4f1dfe0c5cba1fe99dbb843a483

The exception is related to focus function.
TypeError: e.focus is not a function. (In 'e.focus()', 'e.focus' is undefined)
Unhandled Promise Rejection: TypeError: e.focus is not a function. (In 'e.focus()', 'e.focus' is undefined)

I understand that my component ref doesn't implement focus, but the library shouldn't fail at runtime.

### Expected behaviour

Runtime exception shouldn't be thrown

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I am happy to revert that commit back, could you share your use case and how the error was thrown in the first? If an invalid has been supplied, perhaps throwing an error is a better option instead.

**Comment by mazenkhalil** [comment]
Thank you! I am using patternfly library for UI component alongside with react-hook-form controller `<Controller ... />`.

The components are rendered in the following form `<input {...field} />` but some of patternfly components don't implement focus in their reference causing the runtime exception.

Adding an error or warning would be great. At least the application won't fail at runtime.

**Comment by bluebill1049** [comment]
> Adding an error or warning would be great. At least the application won't fail at runtime.

Thanks for the feedback. I will keep this issue open for a while before reverting back the change (or closing it if not many developers report such an issue), runtime error in the dev environment is not a bad sign for me at the moment. It indicates the developer the missing focus management which leads them to look into the UI component library doc to see an alternative ways to focus that input.

**Comment by mazenkhalil** [comment]
> > Adding an error or warning would be great. At least the application won't fail at runtime.
> 
> Thanks for the feedback. I will keep this issue open for a while before reverting back the change (or closing it if not many developers report such an issue), runtime error in the dev environment is not a bad sign for me at the moment. It indicates the developer the missing focus management which leads them to look into the UI component library doc to see an alternative ways to focus that input. 

Thanks. As a side note, the runtime error is happening in the production environment, causing a blank screen in our application.

**Comment by bluebill1049** [comment]
> Thanks. As a side note, the runtime error is happening in the production environment, causing a blank screen in our application.

Why isn't this picked up in the first place during development?

**Comment by Moshyfawn** [comment]
Honestly, I don't feel like we need to prevent the run-time error, as RHF `ref` callback API expects to receive an element with specific methods available. In case the element doesn't expose the `ref` of an element or exposes a partial / non-standard element `ref`, the RHF `ref` callback shouldn't be passed to the element.

If an element doesn't expose the `focus` / `select` methods, RHF doesn't need it's `ref` as it's the only purpose of this API: to focus element in case `setFocus` method was called or focus-on-error behaviour

**Comment by Moshyfawn** [comment]
Here's [a simple repro](https://codesandbox.io/s/recursing-cerf-bumnt8?file=%2Fsrc%2FApp.tsx) of the issue as well

**Comment by bluebill1049** [comment]
Moving to feature request board for further monitoring
