### ISSUE TITLE
A suggestion to add a new `setNestedValues` method

### ISSUE THREAD

**Issue by pro-nasa** [react-hook-form/react-hook-form#961]
**Additional context**
Suppose we have a specific business case to create a wizard form with auto-fill form fields option.
So, the initial form data are nested and one of the steps looks like this:
```
{
  ...
  company: {
    name: '',
    location: {
      country: '',
      region: '',
      city: '',
      lat: '',
      long: ''
    },
  },
  ...
}
```

The form has an additional button for automatically filling fields from API data based on the `company.name`. Each field name is flattened ("company.name", "comapny.location.lat", etc.)

**Is your feature request related to a problem? Please describe.**
When you want to update the form using a nested object (which you pass to defaultValues and validationSchema before), you realize that there is only the `setValue` method for update one field and to update all or several fields you must flatten the nested form object

**Describe the solution you'd like**
I think it would be good to add a new method to `useForm`. It might look something like this (I don't have enough time and knowledge about the codebase to create PR now):

```js
setValues(nestedFormObject)    /* or */   setNestedValues(nestedFormObject)
```

```ts
interface FlattenedFormField {
  key: string
  value: string
}

function setValues<F = any>(nestedForm: F, shouldValidate: boolean = false) {
  // TODO - find out something like this in lodash or other library for Object
  // TODO - do better typing
  // recursively
  const flatten = (
    partialNestedForm: any,
    parentKey: string = ''
  ): FlattenedFormField[] => {
    return Object.entries(partialNestedForm)
      .map(([key, value]) => {
        const nestedKey = parentKey ? [parentKey, key].join('.') : key
        if (typeof value === 'object') {
          return flatten(value, nestedKey)
        } else {
          return { key: nestedKey, value }
        }
      })
      .flat()
  }

  const flattenedForm = flatten(nestedForm)
  flattenedForm.forEach(({ key, value }) => {
    setValue(key, value, shouldValidate)
  })
}
```

**Comment by pro-nasa** [comment]
or you can add an example in the documentation on how to update the entire nested form using a third-party method (or you can add an internal method to flatten an object instead of setNestedValues)

**Comment by pro-nasa** [comment]
the next thing is update many fields and once update and rendering the form

**Comment by bluebill1049** [comment]
thanks for your suggestion its already on my todo list. If you take a look at the board here: 
https://github.com/react-hook-form/react-hook-form/projects/1

i will link this issue with it.
