### ISSUE TITLE
 TypeError when use React components as yup's error messages in development mode

### ISSUE THREAD

**Issue by rodynenko** [react-hook-form/react-hook-form#962]
**Describe the bug**
I try to use React components as yup's error messages (provide simple version on the codesandbox; there could be react-intl's components in real life)
After you validate empty form on submit and try to fill some required field, you find that field is still invalid and TypeError occurs in console.
This error occurs only on development, on production - everything is alright.

As I see, this could be as a result of [react's freezing the element's object](https://github.com/facebook/react/blob/master/packages/react/src/ReactElement.js#L161) on development, and react-hook-form tries to remove some prop.

**To Reproduce**
1. Click on 'Submit' (form fields are empty)
2. Observe errors for fields: First name and Age
3. Enter any number into Age field
4. See TypeError - Cannot delete property '_store' of `#<Object>`

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-validationschema-rcq9f

**Expected behavior**
remove field's error message, and no error in console

**Desktop (please complete the following information):**
 - OS: macOS 10.15.2
 - Browser: Chrome, Firefox

**Additional context**

**Comment by bluebill1049** [comment]
please use our ErrorMessage component for this and leave your markup at that level.

**Comment by bluebill1049** [comment]
I will close this issue now, feel free to leave more questions, as for now we are not going to support JSX as error message rather using ErrorMessage component.

**Comment by rodynenko** [comment]
Hi, thanks for answer. I try to rewrite my example with ErrorMessage https://codesandbox.io/s/react-hook-form-validationschema-uwu72 . But issues is still valid until I am using JSX as yup's custom error message. When using strings - everything is okay.

As a summary:
Am I right, custom errors in yup config should be only strings, and then all JSX wrapper could be provided into ErrorMessage by `as` props?

**Comment by bluebill1049** [comment]
Yes correct above. We can support JSX but every features leads to more code and I am value the lib to be light weight. If there is simple alternative, I am happy to take the hit and make it as a trade off for the lib.
