### ISSUE TITLE
issue: I can't optimize an array of callbacks when the form consists in array of arrays

### ISSUE THREAD

**Issue by TheGrinch00** [react-hook-form/react-hook-form#9620]
### Version Number

7.29.0

### Codesandbox/Expo snack

https://codesandbox.io/s/rhf-optimizazion-issue-z56j68

### Steps to reproduce

When you have a schema like this one:

```
{
    firstLevelArray: [
        someProp;
        secondLevelArray: []
    ]
}
```

I usually have some buttons in the UI to delete the Nth element of an array and I achieve this by memoizing every callback ahead of time so I don't have to declare something like `() => remove(index)` directly inside my `onClick` Button prop.

For example:
```
const removeAtIndexCallbacks = useMemo(
    () => fields.map((_, index) => () => remove(index)),
    [fields, remove]
  );

.
.
.
.

// Inside map() function
<Button onClick={removeAtIndexCallbacks[index]}> Delete </Button>
```

When trying to do the same kind of optimization for the nested array, I can't do it because whenever I `append()` a new element, there is an issue reguarding both nested array and parent array re-rendering.

### Expected behaviour

When editing the nested array, the UI should not cause these issues
Is there an official way to memoize all callbacks in advance?

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Relevant log output

```shell
Cannot update a component (`MyEditor`) while rendering a different component (`NestedLinksForm`). To locate the bad setState() call inside `NestedLinksForm`, follow the stack trace
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
not very clear on the question itself, can you try to improve your codesandbox with better steps to reproduce?

**Comment by TheGrinch00** [comment]
@bluebill1049 Thanks for the quick response. I'll try to explain better:

When I have an array field in a form I use the `useFieldArray()` API and instead of doing something like

```
{fields.map((field, index) => (
    <div>
        .....
       <button onClick={() => remove(index)}> Delete </button>
    </div>
))}
```

I like to memoize everyone of these remove callbacks in advance to improve performances by doing this

```
// This is my memoized array of callbacks that wont be re-calculated at each render
const allRemoveCallbacks = useMemo(() => {
   return fields.map((_, index) => () => remove(index))
}, [fields, remove])

{fields.map((field, index) => (
    <div>
        .....
       <button onClick={allRemoveCallbacks[index]}> Delete </button>
    </div>
))}
```

This works perfectly but when inside the first array there is another array field and I want to apply the same optimization, it stops working whenever I try editing the inner array because of the inner `allRemoveCallbacks` causing a list re-render at the same time as the parent object rerenders everything.

I could fix the issue by just doing the "unoptimize" version without the `useMemo()` for the inner array but if there was a solution that would allow me to memoize also the inner callbacks it would be better for me because I might have many many elements each with its own callback

I hope this time is clearer

**Comment by bluebill1049** [comment]
thanks for the updated detail, do you measure the performance before this memorisation? Also react hook form already provides a key id to try to avoid extra rerenders, is that good enough?

**Comment by TheGrinch00** [comment]
Yep, I'm aware of the `id` provided by RHF, are you telling me this because that id also avoids the re-declaration of my `onClick={() => remove(index)}` inside the button?

The main reason I use the memoized array of callbacks is because for my usecase it's not as simple as just calling `remove(index)` but some medium-heavy calculation is involved just before removing the element from the array.

What I mainly want to avoid is the re-declaration of that function but if the `id` ensures me this is the case, then I'm fine with that

**Comment by bluebill1049** [comment]
Got you, @TheGrinch00 i would try to isolate that calculation if i can as well, but yes `id` would be persist for most of the field array operations.
