### ISSUE TITLE
Different controller behaviour in v7.41.0

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#9621]
Hi guys,

i just stumbled across some weird behaviour with the new version v7.41.0.
It seems like the defaultValue of the controller can no longer be accessed with the field.value property.

in my project, i have a function, which renders my form fields depending on the settings i get from the database:
```jsx
const ReturnAndRenderSettings = (): ReactNode[] => {
        return availableSettings.map((s) => {
            return (
                <div className={"field"}>
                    <Controller name={s.Name} control={settingsControl}
                                defaultValue={userSettings.find(
                                    us => us.SettingId == s.ID)?.IsEnabled ?? false}
                                render={({field, fieldState}) => (

                                    <Setting name={s.Name}
                                             disabled={inSubmit}
                                             defaultValue={field.value}
                                             onChange={setSettingsValue}/>
                                )}/>
                </div>
            );
        })
    };
```

As you can see here, i´m searching for the matching setting which i get from the server, and then i get the actual value from the ```IsEnabled``` property. As fallback i´m using false.

This code worked fine till v7.41.0 and the result looked like this:
![Screenshot_1](https://user-images.githubusercontent.com/46539758/208323938-08ec0c5e-7457-447e-838e-87afc5f1d3f1.png)

However with the newst version ```field.value``` is always ```undefined```.
The result, as expected, looks like this:
![Screenshot_2](https://user-images.githubusercontent.com/46539758/208324053-df5ef5dc-7225-47eb-8d50-43c354c71cef.png)

It seems like in version <7.41.0 field.value was identical with the controller default value, and since 7.41.0 this is not the case anymore.

I´ve read about the new values and defaultValues things in the new versions but found no connection to the controller, so this makes me wonder if i´m missing something here🤔

_Originally posted by @manuelpoelzl in https://github.com/react-hook-form/react-hook-form/discussions/9613_

**Comment by sofsscosta** [comment]
Second this problem, I have also just encountered this in my repo. Also looking for a solution here

**Comment by Moshyfawn** [comment]
This fix is in and is going to be included in the next release. No ETA
