### ISSUE TITLE
issue: isDirty becomes false on Toggle value

### ISSUE THREAD

**Issue by pdreef-meditools** [react-hook-form/react-hook-form#9626]
### Version Number

v7

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-controller-forked-rdcocr?file=/src/Mui.js

### Steps to reproduce

1: Switch the toggle of MUI or Chakra, change the toggle value to false/true:

The value should be change, but the isDirty value should be in all cases "true" .

![image](https://user-images.githubusercontent.com/61777220/208455893-5f2bb4b8-a979-4532-baf0-ec76bae16f7e.png)

### Expected behaviour

The value isDirty should reflect the status isDirty, after he user has changes the value once.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mini-ghost** [comment]
@pdreef-meditools 

Maybe that's to be expected. The follow is an example of `isDirty` in the documentation of [formState](https://react-hook-form.com/api/useform/formstate)

```ts
const {
  formState: { isDirty, dirtyFields },
  setValue,
} = useForm({ defaultValues: { test: "" } });

// isDirty: true
setValue('test', 'change')
 
// isDirty: false because there getValues() === defaultValues
setValue('test', '') 

```

`isDirty` here indicates whether the current value is equal to the `defaultValue` you set, not whether the value has ever changed.

Although the document here is `formState.isDirty`, I think it has the same logic as `fieldState.isDirty`

**Comment by Moshyfawn** [comment]
This is the expected behaviour, as @Mini-ghost mentioned above. `isDirty` state is determined by comparing the current input / form values to the provided default values.
