### ISSUE TITLE
Add a setValues - method that accept an object of values

### ISSUE THREAD

**Issue by yuritoledo** [react-hook-form/react-hook-form#963]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
a `setValue` that accept an `object` as param, something like: 
```js
  setValues({
    name: 'foo',
    email: 'bar'
  })
```

**Describe alternatives you've considered**
Using a iterable over `setValue`

**Comment by bluebill1049** [comment]
It’s already in our project back log. You can take a look there
