### ISSUE TITLE
issue: useFieldArray generates new Ids whenever values prop change

### ISSUE THREAD

**Issue by sarathkcm** [react-hook-form/react-hook-form#9642]
### Version Number

7.41.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-2n21um?file=/src/index.tsx

### Steps to reproduce

Hello, Thank you for the awesome library. 

I am using it in a project with controlled form inputs, using values argument in useForm({ values }). Form onchange event will keep on updating the values which is stored in a state variable. 

I have a dynamic group of  inputs which uses the useFieldArray hook. Every time the values prop in useForm change, it seems to generate new Ids for each row. Because of this, the whole list of rows get recreated in the DOM and that causes the focus to go out of the input. In a controlled form setup like the one I described above, this happens on every keystroke.

Demo:

1. Go to the code sandbox link
2. Click on add row, or just use the default rows
3. Enter values in any of the text boxes
4. Focus goes out of the text box after each keystroke

### Expected behaviour

I think Ids should not change, and focus should remain in the current text box.

My solution for this issue is to add a hidden input in each row, with id as the value. That will update the initial ID on every row object in the array. It makes sense to have an id field in a list of objects. However even after this the field id seems to change on each keystroke. 

After going though the code I realised that the issue is [here](https://github.com/react-hook-form/react-hook-form/blob/cf5a81f8452d310d7df37157f25cf07b634a5006/src/useFieldArray.ts#L124)

The following modification seems to be solving the issue.
`ids.current = fieldValues.map(f => f.id || generateId());`

I don't know if was intentional to generate the Ids every time, or if I am doing anything wrong. If this was unintentional and if the fix seems OK, I would be happy to raise a PR.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This would be difficult and hard to achieve since `values` will update the entire form.

**Comment by sarathkcm** [comment]
Thanks for the reply. It made me reconsider and I settled for defaultValues instead of controlling the form values on every keystroke.
