### ISSUE TITLE
issue: <Controller /> doesn't get updated after setValue called

### ISSUE THREAD

**Issue by cosiluancosta** [react-hook-form/react-hook-form#9643]
### Version Number

7.25.0

### Codesandbox/Expo snack

https://codesandbox.io/s/recursing-lake-tzn6n0?file=/src/App.js

### Steps to reproduce

Setting a field value through an `setValue` inside an `useEffect` don't trigger updates in controlled components (that uses <Controller />)
 
In the CSB: 
1. First select `leisure` as **travel purpose**
2. check the box **"same info as before"** making the fields to hidden and setting the data into `formValues`.
3. uncheck the checkbox **"same as before"** which will reset the formstate. 
4. select `business` as travel purpose.

### Expected behaviour
Fields to be empty as the formvalues are.

Expected that the props in the `<Controller render={...} />` method (eg: `field.value`) are updated along with the values that `watch` returns when setting a value.

### What browsers are you seeing the problem on?
- Chrome
- Brave
- Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
You have 2 separate controlled inputs: _billingAddress.firstName_ and _billingAddress.lastName_; they're controlled by 2 separate `Controller`s _(you can think if them as 2 local states)_. When you call `setValue("billingAddress", newValue)`, you basically set a value to a `billingAddress` input, which doesn't exist / not registered in your form - hence your "stale input value" issue.

To fix it, you want to set both _billingAddress.firstName_ and _billingAddress.lastName_ input values separately:
```js
setValue("billingAddress.firstName", "Marcos")
setValue("billingAddress.lastName", "Tam")

setValue("billingAddress.lastName", "")
setValue("billingAddress.lastName", "")
```

Here's a working [csb](https://codesandbox.io/s/hardcore-curran-piq7qp?file=%2Fsrc%2FApp.js).

**Comment by Moshyfawn** [comment]
On another note, you probably don't need to created a side-effect _(use `useEffect` and call `setValue` inside on input value change)_. Consider moving your effects into the change event callback of the particular input value instead.

Consider giving a read [here](https://beta.reactjs.org/learn/you-might-not-need-an-effect) as well ;)

**Comment by cosiluancosta** [comment]
Even if I try to set values isolated 
```
setValue("billingAddress.lastName", undefined)
setValue("billingAddress.lastName", undefined)
```

the form values contains `{ billingAddress:  { firstName: undefined, lastName: undefined } }` but the control is not being update, I can't set a empty string. it's not possible to set an undefined value?

**Comment by Moshyfawn** [comment]
> @Moshyfawn  thanks for the reply!!! 
> 
> I changed my implementation in my project to instead of using `watch` + `useEffect` I moved to my radio change cb, 
> which continues with the same problem,  I don't think the issue is in the  `setValue` , bc in the end the form values are being updated, not the controller! 
> 
> Even if I try to set values isolated 
> ```
> setValue("billingAddress.firstName", undefined)
> setValue("billingAddress.lastName", undefined)
> ```
> using `resetField("billingAddress.firstName")` doesn't work
> 
> the form values contains `{ billingAddress:  { firstName: undefined, lastName: undefined } }` but the control is not being update, I can't set a empty string. . it's not possible to set an undefined value?

Yes, it's one of the RHF API design decisions: you must provide non-`undefined` values as your input value

Here's a relevant part of [useForm hook docs](https://react-hook-form.com/api/useform):
> You **should** provide **none** undefined default value, as undefined value is conflicting with controlled component as default state.
