### ISSUE TITLE
issue: 

### ISSUE THREAD

**Issue by ShaikRizwan0343** [react-hook-form/react-hook-form#9652]
### Version Number

^7.41.0

### Codesandbox/Expo snack

import React, { memo } from "react"; import { Controller } from "react-hook-form";  import { View, Text, TextInput, KeyboardAvoidingView } from "react-native"; import { styles } from "@components/styles/TextInputWithLabel"; import { colors, scale } from "@theme/index"; import { ITextInputWithLabelProp } from "@type/index";  const TextInputWithLabel = ({   placeholder,   secureTextEntry = false,   title,   textInputStyle,   titleStyle,   Icon,   multiline = false,   name,   control,   rules = {},   ...props }: ITextInputWithLabelProp) => {   return (     <Controller       control={control}       name={name}       rules={rules}       defaultValue=""       render={({         field: { value, onChange, onBlur },         fieldState: { error },       }) => (         <KeyboardAvoidingView enabled style={styles.container}>           <Text style={[styles.title, titleStyle]}>{title}</Text>           <View style={[styles.IconWrapper]}>             <View>{Icon}</View>             <View style={styles.rightBorder} />             <TextInput               value={value}               onChangeText={onChange}               onBlur={onBlur}               placeholder={placeholder}               placeholderTextColor={colors.placeHolderColor}               style={[                 styles.textInput,                 textInputStyle,                 { fontStyle: value ? "normal" : "italic" },                 multiline                   ? {                       ...styles.multiLine,                     }                   : {},               ]}               secureTextEntry={secureTextEntry}               multiline={multiline}               selectionColor={colors.boderColor}               {...props}             />           </View>           {error && (             <Text style={styles.errorText}>*{error.message || "Invalid"}</Text>           )}         </KeyboardAvoidingView>       )}     />   ); };  export default memo(TextInputWithLabel);

### Steps to reproduce

![image](https://user-images.githubusercontent.com/75979939/209284179-b95332de-9d34-424d-8962-c9a53351e87f.png)
![image](https://user-images.githubusercontent.com/75979939/209284290-e8b1e675-5c44-4c82-9228-d80c7b724826.png)

### Expected behaviour

![image](https://user-images.githubusercontent.com/75979939/209284300-4454dd82-9c28-4a4d-917e-a22992bdd61f.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848
