### ISSUE TITLE
issue: UnExpected behaviour while running the project

### ISSUE THREAD

**Issue by ShaikRizwan0343** [react-hook-form/react-hook-form#9654]
### Version Number

^7.41.0

### Codesandbox/Expo snack

https://snack.expo.dev/Mn-6HKlc3

### Steps to reproduce

Runtime exception thrown 

error: node_modules/react-hook-form/dist/index.cjs.js: /home/web-lp-031/react_native/inno/development/frontend/node_modules/react-hook-form/dist/index.cjs.js: Cannot read properties of null (reading 'scope')
![image](https://user-images.githubusercontent.com/75979939/209288165-f789a72b-213f-4397-8312-266aac7d7373.png)

### Expected behaviour

Runtime exception shouldn't be thrown

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I don't think this is an issue to do with this library, and what you supplied snack expo doesn't reproduce the issue. Please look into your own setup.

**Comment by ShaikRizwan0343** [comment]
Before it was working fine,without making any changes in code facing this error

**Comment by bluebill1049** [comment]
If you change to the old version? which version starts to break? I have project running the latest and also both csb and snack works as expected as well: https://codesandbox.io/s/goofy-maxwell-f1dc0s

**Comment by ShaikRizwan0343** [comment]
it started breaking with the same version,i tried to upgrade and downgrade the version facing same issue!!

**Comment by dikamilio** [comment]
I have the same exact issue with version 7.22.1 and after upgrading yo 7.41.0. I think it started when I removed node_modules folder with lock file and made some fresh install.

**Comment by ShaikRizwan0343** [comment]
> I have the same exact issue with version 7.22.1 and after upgrading yo 7.41.0. I think it started when I removed node_modules folder with lock file and made some fresh install.

i tried deleting node_modules,yarn.lock and did fresh install, still facing issue with 7.41.0

**Comment by dikamilio** [comment]
In my case - it starts to work again after changing import order.

`import {Controller, useForm} from 'react-hook-form';`

I placed this line after all other imports and it started to work.

**Comment by bluebill1049** [comment]
can we have a reproducible repo?

**Comment by ShaikRizwan0343** [comment]
> can we have a reproducible repo? I am using the latest version myself including a lot of testing with vite, nextjs and etc, so it's definitely a bundler config-related issue unless we can reproduce and see if the problem is related to our build step.
Still facing issue in react native and working fine when we uninstall the package
