### ISSUE TITLE
Return field id from methods of useFieldArray hook

### ISSUE THREAD

**Issue by ruiaraujo012** [react-hook-form/react-hook-form#9657]
**Is your feature request related to a problem? Please describe.**
I'm working on an app that uses accordions and each accordion is a field from a useFieldArray hook. I want to open the accordion each time a new item is added (append, prepend or insert). My array object doesn't have any unique key so I can't distinguish what is the one added after inserting a new field.

**Describe the solution you'd like**
The feature that solves this is returning the field id from the append, prepend or insert method.

**Comment by bluebill1049** [comment]
I am not sure about your request request. I thought we already provide id in the `fields`, could you elaborate a bit more?

**Comment by ruiaraujo012** [comment]
> I am not sure about your request request. I thought we already provide id in the `fields`, could you elaborate a bit more?

What I'm looking for is something like this:
```js
const { id } = append(...)
// or
const id = append(...)
```

**Comment by bluebill1049** [comment]
Got it 👍 moving to feature request board.

**Comment by ruiaraujo012** [comment]
> Got it 👍 moving to feature request board.

Thank you 😉
