### ISSUE TITLE
issue: `required` property doesn't work when `valueAsNumber` property is true

### ISSUE THREAD

**Issue by JuandaGarcia** [react-hook-form/react-hook-form#9661]
### Version Number

7.41.1

### Codesandbox/Expo snack

https://codesandbox.io/s/pensive-edison-3kzj0m?file=/src/App.js

### Steps to reproduce

1. Go to [https://codesandbox.io/s/pensive-edison-3kzj0m?file=/src/App.js](https://codesandbox.io/s/pensive-edison-3kzj0m?file=/src/App.js)
2. Click on Submit button
3. See error

```
import { useForm } from "react-hook-form";
import { useState } from "react";

export default function App() {
  const {
    register,
    handleSubmit,
    formState: { errors }
  } = useForm();
  const [data, setData] = useState();

  const onSubmit = handleSubmit((data) => {
    setData(JSON.stringify(data));
  });

  return (
    <>
      <span>{data}</span>
      <form onSubmit={onSubmit}>
        <p>{errors?.price?.message}</p>
        <input
          type="number"
          {...register("price", {
            required: {
              value: true,
              message: "The price is required."
            },
            valueAsNumber: true
          })}
        />
        <button>Submit</button>
      </form>
    </>
  );
}
```
![image](https://user-images.githubusercontent.com/39936759/209415607-b39ec085-28f7-4630-9dc1-93b88dcac0fb.png)

### Expected behaviour

![image](https://user-images.githubusercontent.com/39936759/209415573-e43d35fc-4487-4593-a48d-638a16a7cdfd.png)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ilteoood** [comment]
Hey @bluebill1049 are you planning to release this too?
