### ISSUE TITLE
issue: controller not updated when removing an item with useFieldArray

### ISSUE THREAD

**Issue by karbone4** [react-hook-form/react-hook-form#9676]
### Version Number

7.41.1

### Codesandbox/Expo snack

https://snack.expo.dev/@antoinerouzier/7b2eee

### Steps to reproduce

1. use `useFieldArray` with controlled child component 
2. remove first index
3. see that form values are ok but `useController` not updated with form values → it shows a list with last item removed instead of first item removed

### Expected behaviour

`useController` value should be updated with correct value

### What browsers are you seeing the problem on?

I am using react native

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
<img width="789" alt="Screenshot 2022-12-28 at 9 35 15 pm" src="https://user-images.githubusercontent.com/10513364/209798976-13e51247-f9bc-4a84-8cb3-bcb363a7c1fc.png">

could you make sure to apply the key props for each row?

https://react-hook-form.com/api/usefieldarray

```tsx
function FieldArray() {
  const { control, register } = useForm();
  const { fields, append, prepend, remove, swap, move, insert } = useFieldArray({
    control, // control props comes from useForm (optional: if you are using FormContext)
    name: "test", // unique name for your Field Array
  });

  return (
    {fields.map((field, index) => (
      <input
        key={field.id} // important to include key with field's id
        {...register(`test.${index}.value`)} 
      />
    ))}
  );
}
```

**Comment by karbone4** [comment]
It works 🚀
Sorry, I didn't see the comment in the doc :/
Thanks a lot !
