### ISSUE TITLE
issue: checkbox checked state out of sync with form state when submitting via onChange 

### ISSUE THREAD

**Issue by benfpayne** [react-hook-form/react-hook-form#9679]
### Version Number

7.37

### Codesandbox/Expo snack

https://codesandbox.io/s/morning-surf-4c7qrg?file=/src/App.tsx

### Steps to reproduce

Go to the following Codesandbox link: https://codesandbox.io/s/morning-surf-4c7qrg?file=/src/App.tsx
Click on the checkbox 
- see how form is not submitted each time the checkbox is clicked
- checkbox ui also doesn't toggle with each click

### Expected behaviour

Expected behaviour:
- checkbox ui should toggle on each click from true/false a
- submit function run each time the checkbox is clicked as we're submitting via onChange

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
```tsx
import * as React from "react";
import { useForm } from "./src";
import Headers from "./Header";
import "./styles.css";

type FormValues = {
  firstName: boolean;
};

let renderCount = 0;

export default function App() {
  const { register, handleSubmit } = useForm<FormValues>({
    mode: "onChange"
  });
  const onSubmit = (data: FormValues) => console.log(data);
  renderCount++;

  return (
    <div>
      <Headers
        renderCount={renderCount}
        description="Performant, flexible and extensible forms with easy-to-use validation."
      />

      <form onChange={() => {
        handleSubmit(onSubmit)()
      }}>
        <input
          type="checkbox"
          {...register("firstName", { required: true })}
          placeholder="First Name"
        />
        <input type="submit" />
      </form>
    </div>
  );
}
```

you can work around the issue above, as the original `handleSubmit` API was made for onSubmit callback instead of onChange.
