### ISSUE TITLE
issue: IsValid is false but errors is empty

### ISSUE THREAD

**Issue by ScreamZ** [react-hook-form/react-hook-form#9685]
### Version Number

7.41.2

### Codesandbox/Expo snack

https://codesandbox.io/s/bold-monad-7beuxs?file=/src/App.tsx

### Steps to reproduce

There are two dates: `startDate` and `endDate`. Each date can be moved from 15 minutes up or down thanks to `+` and `-` buttons next to it.

**The purpose is to detect `endDate` going before `startDate`** causing a date overlapping.

- In order to check that we use a `when` validator on the `endDate` that depends on the `startDate` value.
- `react-hook-form` is configured in `onChange` mode.

To trigger this rule I can do one of the two possible actions.
1. Decrement `endDate` for it to be before `startDate`.
2. Increment `startDate` to be after `endDate`.

**There is no issue with the first method, but the second has some.**

- If you change `endDate` (the one with the rule "when" from the yup schema) you can see `isValid` going to `false` and the `errors` object gets updated.
- But if you change `startDate`, you can see that `isValid` goes `false` but the `errors` object is not updated.

### Expected behavior

`isValid` and `errors` are sync no matter if i change `startDate` or `endDate` and rules related to each other get correctly triggered.

How can `{ "isValid": false, "errors": {} }`  be possible? As the validity is determined by if there are errors…

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
You don't return the error message for the `startDate` field like you do for `endDate`
```js
.when(
  "startDate",
  (startDate, currSchema)
    startDate && currSchema.min(addMinutes(startDate, 15), "Overlap error")
```

**Comment by ScreamZ** [comment]
@Moshyfawn I'm sorry but you didn't understand the issue…

The problem is not about `startDate`, I've added a message if you want but we could remove the validation rules for startDate for the example if you prefer.

The problem is that when I edit `endDate` the `when` rule based on `startDate` value get validated and applied.
But when I move `startDate` value, `endDate` rule doesn't seem to be validated as i get no `errors` but `isValid` is correctly changing

**Comment by Moshyfawn** [comment]
I'll take a closer look in a bit, @ScreamZ

**Comment by bluebill1049** [comment]
@ScreamZ have you tried to debug yourself with the validation:

```tsx
resolver: async (data, context, options) => {
  // you can debug your validation schema here
  console.log('formData', data)
  console.log('validation result', await anyResolver(schema)(data, context, options))
  return anyResolver(schema)(data, context, options)
},
```

**Comment by bluebill1049** [comment]
This is dependent validation, react hook form focus on field level validation to optimise performance, if you have dependant validation you will need to use `trigger` API or `register` with `deps` props.

**Comment by ScreamZ** [comment]
> @ScreamZ have you tried to debug yourself with the validation:
> 
> ```tsx
> resolver: async (data, context, options) => {
>   // you can debug your validation schema here
>   console.log('formData', data)
>   console.log('validation result', await anyResolver(schema)(data, context, options))
>   return anyResolver(schema)(data, context, options)
> },
> ```

Hello @bluebill1049, thanks for the feedback.
Error is generated on `endDate` while debugging this way. So `isValid` is coherent.

I wasn't aware of the `deps` field on `register` method, is there any specific paragraph about this use case on the doc ? Seems like I missed it, after searching only found it here https://react-hook-form.com/api/useform/register. Maybe we could add something to the FAQ ?

Also my question is, how would you deal with that using controllers, and more specifically with components like this one : a pattern that I'm used to:
```tsx
export type TimeRangePickerProps<T extends FieldValues> = {
  control: Control<T>;
  name: FieldPathByValue<T, Date>;
  title: string;
  min: string;
  /** In minutes */
  step: 5 | 15 | 30;
  max: string;
  small?: boolean;
  loading: boolean;
};

/**
 * Render time range picker
 * ! Voluntary using this without Timezone for startOfDay and isTomorrow calculation. Doesn't has to be related to a TZ it's only useful for intervals tracking.
 */
export function TimeRangePicker<T extends FieldValues>({
  title,
  control,
  name,
  step,
  small = true,
  min,
  max,
}: TimeRangePickerProps<T>) {
  const {
    field: { onChange, ...field },
    fieldState: { error },
  } = useController({
    control,
    defaultValue: todayUTCAtTime(0, 0) as PathValue<
      UnPackAsyncDefaultValues<T>,
      FieldPathByValue<T, Date>
    >,
    name,
  });

  const value: Date = field.value;

  return (
    <View>
      <SemiBoldText size={18} color="darkBlue">
        {title}
      </SemiBoldText>
      <Wrapper small={small}>
        <FlexBoxView justify="space-between" alignItems="center">
          <MaxMinIndicator small={true} min={min} max={max} />
          <FlexBoxView
            dir="column"
            justify="center"
            alignItems="center"
            shrink={1}>
            <TabularText
              color={error ? 'orangePink' : 'darkBlue'}
              size={40}
              weight={500}>
              {formatTimeUTC(value)}
            </TabularText>
          </FlexBoxView>
          <FlexBoxView dir="column">
            <VariationButton
              onPress={() => {
                let targetDate = addMinutes(value, step);

                // Prevent changing day for difference and range calculation
                onChange(
                  isSameDayUTC(value, targetDate)
                    ? targetDate
                    : todayUTCAtTime(0, 0),
                );
              }}
              type="add"
            />
            <Spacer height={15} />
            <VariationButton
              onPress={() => {
                const targetDate = subMinutes(value, step);

                // Prevent changing day for difference and range calculation
                onChange(
                  isSameDayUTC(value, targetDate)
                    ? targetDate
                    : addDays(targetDate, 1),
                );
              }}
              type="remove"
            />
          </FlexBoxView>
        </FlexBoxView>
      </Wrapper>
    </View>
  );
}
```

**Comment by bluebill1049** [comment]
> I wasn't aware of the deps field on register method, is there any specific paragraph about this use case on the doc ? Seems like I missed it, after searching only found it here https://react-hook-form.com/api/useform/register. Maybe we could add something to the FAQ ?

https://react-hook-form.com/api/useform/register

<img width="959" alt="Screenshot 2023-01-02 at 9 32 32 am" src="https://user-images.githubusercontent.com/10513364/210186418-b82a7335-f77b-4cc9-a694-c56987dd5888.png">

and yes, we can consider adding a FAQ section too. If you have some thoughts on this feel free to suggest or even send us a PR.

> Also my question is, how would you deal with that using controllers, and more specifically with components like this one : a pattern that I'm used to:

You are definitely doing on the right path, one thing I would suggest is maybe to build a component with its own state and then hook it up with `useController`, it would be more flexible in your use case.

https://codesandbox.io/s/usecontroller-own-state-wncet2?file=/src/App.tsx:356-421

**Comment by ScreamZ** [comment]
For now I've workaround using
```tsx
  useEffect(() => {
    trigger(['startDate', 'endDate']);
  }, [trigger, startDate, endDate]);
```

Not perfect but triggers related error from parent (where schema is defined)

**Comment by bluebill1049** [comment]
Instead of `useEffect`, can you move this into the component level?

**Comment by kasparkallas** [comment]
Doesn't `trigger` make all the validations run twice when using `yup`/`zod`/etc validation schemas? This feels redundant to run it twice only to have `react-hook-form` _pick_ the right error from the validation. Especially if there's any heavier asynchronous validation present. In my view, it's quirky behaviour that the error is respected in the sense that it sets the form state invalid, but not respected to actually display the error.

**Comment by kasparkallas** [comment]
> 



> This is dependent validation, react hook form focus on field level validation to optimise performance, if you have dependant validation you will need to use `trigger` API or `register` with `deps` props.

Good to know. To add context, in my application, I've designed the validation to have 2 levels. The first level is essentially sanitization -- dates are dates in valid ranges, numbers are numbers in valid ranges, etc. The second level is higher validation (a.k.a domain validation) where I expect the form data sanitized and can use it for async queries to validate the form data as a whole.

I don't want to move this into `handleSubmit` because I want to display the errors ASAP. I don't want to move this out of `react-hook-form` because I want to keep the validation in one place & one schema.

Any thoughts or recommendations on this approach?

**Comment by ScreamZ** [comment]
I share your thoughts, my solution works, this duplicates, but this works. Not sure it's big deal in terms of performances (while it's truly an aberration)
