### ISSUE TITLE
`validate` for `register` method should get preference over `resolver` | ZOD | YUP etc.

### ISSUE THREAD

**Issue by adiathasan** [react-hook-form/react-hook-form#9689]
Hi, I'm the author of [mui-react-hook-form-plus](https://github.com/adiathasan/mui-react-hook-form-plus)

My schema with `zod` looks like

```tsx
const schema = z.object({
  email: z
    .string({ required_error: "Required" })
    .email("Invalid email address"),
  password: z.string().min(4, "Password must be at least 4 characters"),
  confirmPassword: z.string(),
});

```

I want to match `confirmPassword` & `password`

Hence, I need to validate 

```tsx
const password = useWatch({
    control,
});
```

```tsx
<HookTextField
      {...registerState("confirmPassword")}
      rules={{
          validate: (value) => value === password ? undefined : "Passwords must match",
      }}
/>
```

But for some reason, it's not triggering `validate`. Only `zod` schema is triggering.

Can someone explain this!!

**Comment by Moshyfawn** [comment]
When using **validation schema**, the field level validation rules _(like `validate`, `required` etc.)_ are ignored. From [`useForm` rules docs section](https://react-hook-form.com/api/useform#schema-rules):

> A resolver can not be used with the built-in validators (e.g.: required, min, etc.)

**Comment by adiathasan** [comment]
Any suggestions? how to overcome the situation?
