### ISSUE TITLE
If an array field is initially an empty string then dirty state detection breaks

### ISSUE THREAD

**Issue by tomas-c** [react-hook-form/react-hook-form#969]
**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-dirty-state-with-empty-string-fhlww
2. Click on the empty input field and type something
3. Observe form state is dirty
4. Clear the field value
5. Observe the form state is still dirty but it shouldn't be

**Additional context**
 - Version 4.8.2

This does not happen with non-array fields or when the initial field value is not an empty string

**Comment by bluebill1049** [comment]
thanks a lot for the find @tomas-c
