### ISSUE TITLE
issue: additionalProperties error not returned

### ISSUE THREAD

**Issue by teobmg** [react-hook-form/react-hook-form#9697]
### Version Number

7.41.3

### Codesandbox/Expo snack

https://codesandbox.io/s/goofy-snowflake-684x1g?file=/src/App.tsx

### Steps to reproduce

1. Create a form, creating a schema where `additionalProperties = false`
2. Reset it using a property unknown to the schema
3. `isValid = false`, but `errors = {}`

Overriding the `resolver` function, I think that it is happening because the error has an empty key:

<img width="490" alt="image" src="https://user-images.githubusercontent.com/115801516/210245296-56d40d54-e7ac-4e60-9e1f-502bb0610531.png">

### Expected behaviour

1. Create a form, creating a schema where `additionalProperties = false`
2. Reset it using a property unknown to the schema
3. `isValid = false`, but `errors` should includes a message like `must NOT have additional properties`

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
react hook form validation strategy is field base, which means the error state will only update when the user interacts with such input or programmatically `trigger` by the developer. It's one of the strengths of this library, as we take care of the errors to render and validation strategy, but it won't flush out all errors on each render like other controlled form libraries.

**Comment by teobmg** [comment]
ok, that's clear. It is a little bit tricky because sometimes you see `isValid = false` and `errors` empty but I understand the reasons.

Maybe in the future, you could consider returning them too, just for debugging purposes.

Thanks for the explanation!
