### ISSUE TITLE
issue: useFieldArray remove() marks form dirty

### ISSUE THREAD

**Issue by hedzerkoolstra** [react-hook-form/react-hook-form#9708]
### Version Number

7.27.1

### Codesandbox/Expo snack

https://codesandbox.io/s/getfieldstate-forked-v4ddej?file=/src/App.tsx

### Steps to reproduce

1. Go to codesandbox example
2. Delete the first entry of the form.

### Expected behaviour

I would expect the values that I'm watching with getFieldState to not be marked dirty since I didn't touch them yet. Instead they are marked dirty. I was wondering if I was doing something wrong, or whether this is a bug. Thanks in advance.

Maybe relevant:
- It doesn't mark anything dirty when I remove the last entry. 
- It only marks the last entry dirty when I remove the middle entry.
It seems that the getDirtyFields is not comparing the right entries with each other because the change in order of the array.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`dirtyFields/isDIrty` will always measure against your `defaultValues`, if you remove a row then the diff will occurred.

**Comment by hedzerkoolstra** [comment]
Thanks for your response. So if I understand correctly this is intentional and it won't be addressed? It feels kind of strange to mark a bunch of fields as dirty while you have never touched them right?

**Comment by bluebill1049** [comment]
`touched` is not related to `dirty`, it's a diffuclt/impossible one to track with dynamic fields as such.

**Comment by hedzerkoolstra** [comment]
I know they are different. What I meant was that there are field that are now marked as dirty while they have not been modified. I'd like to visually display to my users which fields have been modified but as I understand it that's not possible with useFieldArray. I will try and look for alternatives, thanks for your explanation.
