### ISSUE TITLE
issue: calling setValue breaks future onChange calls from a Controller

### ISSUE THREAD

**Issue by tkolanko** [react-hook-form/react-hook-form#9709]
### Version Number

7.41.3

It appears this broke in 7.41.2, it works in 7.41.1

### Codesandbox/Expo snack

https://codesandbox.io/s/dawn-glade-g2bibl?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/dawn-glade-g2bibl?file=/src/App.js
2. Change the select dropdown from `one` to `two`
3. Enter a value for the username
4. Submit the form

An error appears that the username is required, however, if you look at the console output username has a value

### Expected behaviour

Calling setValue does not break future onChange calls

if I switch from `setValue` to `reset` then things work as expected, however, we make heavy use of setValue in a number of locations on some complex forms.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
@tkolanko a workaround for now is to downgrade to [7.41.1](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.41.1)
