### ISSUE TITLE
React native picker not updating?

### ISSUE THREAD

**Issue by KDederichs** [react-hook-form/react-hook-form#971]
**Describe the question?**

Hey,
I'm trying to use hook forms with a normal React Native Picker like that:
```
  const { handleSubmit, errors, control } = useForm<FormData>();
  const onChange = (args: any): any => {
    return {
      selectedValue: args,
    };
  };
        <Controller
          as={<Picker>
            <Picker.Item label={'Reason1'} value={'reason1'}/>
            <Picker.Item label={'Reason2'} value={'reason2'}/>
            <Picker.Item label={'Reason3'} value={'reason3'}/>
          </Picker>}
          control={control}
          name="reason"
          onValueChange={onChange}

        />
```

The problem is that the value I select won't be reflected by the rendered Picker element.
Is there some special way to handle those? Or do they don't work in general?

**Comment by joe4mg** [comment]
On the Controller component try setting the `valueName` prop to `"selectedValue"`

**Comment by KDederichs** [comment]
That did the trick, thanks a lot!

**Comment by bluebill1049** [comment]
thank you @joe4mg 🙏

**Comment by fxamauri** [comment]
can you show me how it should be? I tried as follows but I was unsuccessful

```
const onChange = args => {
    return {
      value: args,
    };
  };

<Controller
              as={
                <Picker>
                  <Picker.Item label="Reason1" value="reason1" />
                  <Picker.Item label="Reason2" value="reason2" />
                  <Picker.Item label="Reason3" value="reason3" />
                </Picker>
              }
              control={control}
              name="reason"
              onValueChange={onChange}
              valueName="selectedValue"
 />
```

**Comment by KDederichs** [comment]
Sure,

```
  const onChange = (args: any): any => ({
    value: args[0],
  });

<Controller
          as={
            <Picker>
              <Picker.Item
                label={I18n.t('report.reasons.spam')}
                value={'reason.spam'}
              />
              <Picker.Item
                label={I18n.t('report.reasons.other')}
                value={'reason.other'}
              />
            </Picker>
          }
          control={control}
          name="reason"
          onChange={onChange}
          onChangeName={'onValueChange'}
          valueName={'selectedValue'}
          defaultValue={'reason.spam'}
        />
```

is the final working solution @fxamauri

**Comment by fxamauri** [comment]
> Sure,
> 
> ```
>   const onChange = (args: any): any => ({
>     value: args[0],
>   });
> 
> <Controller
>           as={
>             <Picker>
>               <Picker.Item
>                 label={I18n.t('report.reasons.spam')}
>                 value={'reason.spam'}
>               />
>               <Picker.Item
>                 label={I18n.t('report.reasons.other')}
>                 value={'reason.other'}
>               />
>             </Picker>
>           }
>           control={control}
>           name="reason"
>           onChange={onChange}
>           onChangeName={'onValueChange'}
>           valueName={'selectedValue'}
>           defaultValue={'reason.spam'}
>         />
> ```
> 
> is the final working solution @fxamauri

Thanks, just adding the onChangeName prop.

**Comment by RavisaraDev** [comment]
I tried this as follows. but It still not reflecting on the picker component. 

const onChange = (args: any): any => ({
    value: args[0],
  });

<Controller
        as={
          <Picker>
            <Picker.Item label={'One'} value={'one'} />
            <Picker.Item label={'Two'} value={'two'} />
          </Picker>
        }
        control={control}
        name={name}
        onChange={onChange}
        onChangeName={'onValueChange'}
        valueName={'selectedValue'}
        defaultValue={defaultValue}
      />

**Comment by bluebill1049** [comment]
> I tried this as follows. but It still not reflecting on the picker component.
> 
> ```
> const onChange = (args: any): any => ({
>     value: args[0],
>   });
> 
> 
> <Controller
>         as={
>           <Picker>
>             <Picker.Item label={'One'} value={'one'} />
>             <Picker.Item label={'Two'} value={'two'} />
>           </Picker>
>         }
>         control={control}
>         name={name}
>         onChange={onChange}
>         onChangeName={'onValueChange'}
>         valueName={'selectedValue'}
>         defaultValue={defaultValue}
>       />
> ```

Does `Picker` has `onChange` and `value` props?

**Comment by RavisaraDev** [comment]
> Does `Picker` has `onChange` and `value` props?

No, My whole picker component looks like this

```
export const ItemPicker = ({name, control, defaultValue}) => {
  const onChange = (args: any): any => ({
    value: args[0],
  });

  return (
    <InputContainer>
      <Controller
        as={
          <Picker>
            <Picker.Item label={'One'} value={'one'} />
            <Picker.Item label={'Two'} value={'two'} />
          </Picker>
        }
        control={control}
        name={name}
        onChange={onChange}
        onChangeName={'onValueChange'}
        valueName={'selectedValue'}
        defaultValue={defaultValue}
      />
    </InputContainer>
  );
};


```

**Comment by bluebill1049** [comment]
> > Does `Picker` has `onChange` and `value` props?
> 
> No, My whole picker component looks like this
> 
> ```
> export const ItemPicker = ({name, control, defaultValue}) => {
>   const onChange = (args: any): any => ({
>     value: args[0],
>   });
> 
>   return (
>     <InputContainer>
>       <Controller
>         as={
>           <Picker>
>             <Picker.Item label={'One'} value={'one'} />
>             <Picker.Item label={'Two'} value={'two'} />
>           </Picker>
>         }
>         control={control}
>         name={name}
>         onChange={onChange}
>         onChangeName={'onValueChange'}
>         valueName={'selectedValue'}
>         defaultValue={defaultValue}
>       />
>     </InputContainer>
>   );
> };
> ```

In order for Controller to control that component, the Picker needs to have onChagne or Value props.

we are making it much easier for v6 with render props, so you can assign them easier and more predictable.

`<Controller render={props => <Input {...props}} />`

but the rule remain the same, your Picker component need to wire up with Controller's onChange and value props.

**Comment by RavisaraDev** [comment]
@bluebill1049 Thanks it was realy helpful. Replacing `onChange` to `onValueChange` solve the problem.
