### ISSUE TITLE
error: is not assignable to type FieldError when use sub objects in TypeScript with Yup

### ISSUE THREAD

**Issue by leonidasroberto** [react-hook-form/react-hook-form#9718]
Error when use subobjects to yup error:
Type error: Type 'Merge<FieldError, Merge<FieldError, FieldErrorsImpl<{ some object here }>>[]>' is not assignable to type 'FieldError'.

Solution/Sugestion:
on errors.ts change line 14 to: type?: LiteralUnion<keyof RegisterOptions, string>;

**Comment by Moshyfawn** [comment]
Please, do not duplicate your feature requests in both discussions and issues

**Comment by leonidasroberto** [comment]
Sorry my friend.

**Comment by Moshyfawn** [comment]
No worries! Just letting you know that we see both discussions and issues. We just don't have enough time to get to everyone ASAP

**Comment by kwakky1** [comment]
What if I need to fix it in the code before updating?
