### ISSUE TITLE
issue: useWatch doesn't react to name property change

### ISSUE THREAD

**Issue by delyan-peev** [react-hook-form/react-hook-form#9727]
### Version Number

7.41.5

### Codesandbox/Expo snack

https://codesandbox.io/s/winter-voice-bnpmd6

### Steps to reproduce

1. Open the CSB
2. Click on 'Change'

`useWatch` is not detecting the new index and still returning the values for the one that was first passed to it.

### Expected behaviour

`useWatch` should detect when an index in a deep path has changed and subscribe to changes for the changed index.

Upfront apologies if I'm not doing something correctly. :/

Great library nevertheless!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
The `name` property of `useWatch` is set once on initial hook render. Updating `idx` value won't reflect which value update `useWatch` is subscribed to

**Comment by delyan-peev** [comment]
So what's the workaround here? I have a tabbed view where each tab is a different step in a process and I need to subscribe to the elements of the respective tab.

**Comment by bluebill1049** [comment]
This is something we can consider supporting with a feature request, for now, you can use the `key` prop to remount the component and reset the useWatch subscription.

**Comment by Moshyfawn** [comment]
> This is something we can consider supporting with a feature request, for now, you can use the `key` prop to remount the component and reset the useWatch subscription.

Was just typing that :D

Example:
```jsx

function Comp ({ idx }) {
  useWatch({ name: `fields.${index}.prop` })
}

function Form ({ idx }) {
  const [idx] = useState(1)

  return <Comp key={idx} />
}

**Comment by bluebill1049** [comment]
> Do you have an estimation of when this can be considered for implementation, if ever?

No estimate, you can submit a feature request to start with.

**Comment by delyan-peev** [comment]
> > Do you have an estimation of when this can be considered for implementation, if ever?
> 
> No estimate, you can submit a feature request to start with.

Will do tomorrow, thanks.

**Comment by leapful** [comment]
@delyan-peev 

While waiting for up-vote, it would be worth to use custom hook by using `watch` method, something like this:

```
const useCustomWatch = ({ name }: { name: string }) => {
  const { watch } = useFormContext();

  return watch(name);
};
```

Working demo: https://codesandbox.io/s/quizzical-worker-y0t94k?file=/src/App.tsx

**Comment by delyan-peev** [comment]
> @delyan-peev
> 
> While waiting for up-vote, it would be worth to use custom hook by using `watch` method, something like this:
> 
> ```
> const useCustomWatch = ({ name }: { name: string }) => {
>   const { watch } = useFormContext();
> 
>   return watch(name);
> };
> ```
> 
> Working demo: https://codesandbox.io/s/quizzical-worker-y0t94k?file=/src/App.tsx

Wow, that's awesome and saves sooo much headache. Thanks! Would appreciate an upvote on the original one though as I still think `watch` from `useFormContext` and `useWatch` should work the same way, right?

**Comment by leapful** [comment]
@delyan-peev 

Yes, `watch` method and `useWatch` hook are using same internal API to watch on value of target field name.

**Comment by delyan-peev** [comment]
> @delyan-peev
> 
> Yes, `watch` method and `useWatch` hook are using same internal API to watch on value of target field name.

Then why is it that they do not work the same? 😕

**Comment by leapful** [comment]
@delyan-peev 

The implementation between them are different, one is a plain method, the other is a React hook which is depends on mutation phase of React Fiber node. Using same internal API of react-hook-form cannot make sure the same behavior.

**Comment by delyan-peev** [comment]
> @delyan-peev
> 
> The implementation between them are different, one is a plain method, the other is a React hook which is depends on mutation phase of React Fiber node. Using same internal API of react-hook-form cannot make sure the same behavior.

Turns out that the suggested `useCustomWatch` (using the `watch` method instead of `useWatch`) turned out to be a huge performance killer as it rerenders the whole form on every change, so I would not suggest it. Currently looking for a different way to achieve what the OP was about.
