### ISSUE TITLE
useWatch to react to name property change

### ISSUE THREAD

**Issue by delyan-peev** [react-hook-form/react-hook-form#9732]
**Is your feature request related to a problem? Please describe.**

`useWatch` and `useFieldArray` are not reacting to name property change. That is, the name they receive on mount is the one they are subscribed to throughout the lifetime of the component. The issue was originally discussed [here](https://github.com/react-hook-form/react-hook-form/issues/9727). You can also check [this CSB](https://codesandbox.io/s/winter-voice-bnpmd6).

Remounting the child component based on `key` works fine, but it's particularly frustrating when you don't want the parent component to rerender in case of changes that would otherwise concern the child only. For such cases we use `jotai` and use the `atom` from `jotai` in the child only, so only it is subscribed to changes in the atom, which results in the parent not rerendering. Sure, you can wrap the child in another component (which is what we did), but I still feel this is unnecessary friction and noise in the code.

**Describe the solution you'd like**

`useWatch` and `useFieldArray` to react to changes in the `name` property.

**Describe alternatives you've considered**

Wrapping the `useWatch`-dependent component in another one and remounting the latter with `key` from the original parent.

Using `useFieldArray` which results in the same result.

Strangely to me (I haven't delved into the RHF code), if I do this, it works fine:

```javascript
const Comp: React.FC<{ idx: number }> = ({ idx }) => {
  const values = useWatch<FormData, `steps.${number}.elements`>({ name: `steps.${idx}.elements` });
  const arrayValues = useFieldArray<FormData, `steps.${number}.elements`>({ name: `steps.${idx}.elements` });

  return <p>{JSON.stringify(values)}</p>;
};
```

However, removing the `useFieldArray` subscription or printing the values received from it (`<p>{JSON.stringify(arrayValues)}</p>`), with or without `useWatch` still does not work as one would expect.

**Additional context**

[This CSB](https://codesandbox.io/s/winter-voice-bnpmd6) illustrates it. In order to make it work, you need to change this:

```javascript
      <Comp idx={idx} />
```
to
```javascript
      <Comp key={idx} idx={idx} />
```

**Comment by bluebill1049** [comment]
thanks for moving to the feature board for upvotes. https://github.com/react-hook-form/react-hook-form/projects/1
