### ISSUE TITLE
issue: `useForm` `resetOptions` should persist on each call to `reset` on control

### ISSUE THREAD

**Issue by cdbattags** [react-hook-form/react-hook-form#9736]
### Version Number

7.41.5

### Codesandbox/Expo snack

see reproduction plz

### Steps to reproduce

```ts
const { reset } = useForm({
  resetOptions: { keepValues: true, keepDefaultValues: true },
  defaultValues,
  resolver: yupResolver(validationSchema),
})

reset() // should use the same resetOptions
```

### Expected behaviour

My expectation is that later calls to the control's reset would use the same `resetOptions` defined previously.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Thanks for the issue report. They are not associated, the reset option at `useForm` is only applicable for `defaultValues` and `values` props reset behaviour.

**Comment by cdbattags** [comment]
Hmmm, why is this the case though? So I get this is a feature that I would be asking for but I only ever use `setValue` and `reset` and this seems like an amazing quality of life improvement, no?

**Comment by bluebill1049** [comment]
Not at this stage.
