### ISSUE TITLE
using `append`, `remove` functions in `useFieldArray` automatically submits the form

### ISSUE THREAD

**Issue by siamekanto19** [react-hook-form/react-hook-form#9741]
### Version Number

7.41.1

### Codesandbox/Expo snack

https://codesandbox.io/s/lucid-knuth-t3dw8p

### Steps to reproduce

1. Go to the form
2. Click on `append` button to add a new entry in the Field Array `sports`
3. Check the console to see that the form submit function (it console logs the values as example) has been called upon clicking the `append` button
4. Form gets submitted everytime we call the `append` function to add a new entry to the array.

### Expected behaviour

The `append` and `remove` functions should add a new entry to the Fields Array, not submit the entire form. We might need to add multiple items to the array and keep that in the Form State and only submit the entire form when to reach the end and click the Submit button.

### What browsers are you seeing the problem on?

Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
An expected behaviour [as the default HTML button element `type`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type) is `submit`.

Set the button type to "button" to prevent the default browser behaviour.
