### ISSUE TITLE
Allow us to opt out of setting values to `undefined` when fields are disabled

### ISSUE THREAD

**Issue by Aerophite** [react-hook-form/react-hook-form#9743]
**Is your feature request related to a problem? Please describe.**
Yes. When using the `disabled` attribute, `react-hook-form` removes the data from `getValues()` and I do not want it to. I understand that this is on purpose and that the standard response is to use `readOnly`...but browsers are inconsistent on how this works and a lot of packages don't really support it.

A perfect example is when using a Checkbox. In this instance, setting it to `readOnly` does not actually make it readOnly, nor does it add disabled styling. I understand that one solution is to use `<fieldset disabled><input type="checkbox" /></fieldset>` but this still does not add disabled styling _and_ fieldset has default styling that is undesirable...and when removing the styling, still causes weird undesired styling issues. This issue is compounded when you use a package such as MUI.

**Describe the solution you'd like**
I would like to make it where, when creating the form, I can specify whether I want disabled fields to still return their values. 

OR

Change the functionality entirely to never set values to `undefined`, regardless of disabled state. However, I believe you will not want to do this since it's 1) breaking and 2) non-standard to HTML form submission.

**Describe alternatives you've considered**
I've considered obscuring and creating my own logic to make readOnly work for fields with the correct styling...but since I am using packages (MUI in particular) that handle all the styling for me, I don't want to recreate the wheel for adding in the disabled styling and then have to maintain it.

**Additional context**
It's worth mentioning that this behavior is also inconsistent. When I use the `disabled` attribute on a text field, the value does _not_ get removed from the `getValues` response. However, when using it on a checkbox, it does.

In the below screenshot, `isAgency` is used to check the "Agency" checkbox, while `name` is used for the value of the "Customer" textbox. note that on render, both `name` and `isAgency` have values. Both fields are disabled, but on the initial render, `name` keeps its value while `isAgency` loses its value.

![image](https://user-images.githubusercontent.com/6826088/211368730-4a8a848a-2dd0-4614-8cad-20a8b3c11e69.png)

Additionally, changing the value to `undefined` causes errors where my checkbox component is going from a controlled to an uncontrolled state, which is not desired.

Aaannnddd...setting the value to `undefined` goes against your rules for `defaultValues` and submitted values in your [`useForm` documentation](https://react-hook-form.com/api/useform/)

![image](https://user-images.githubusercontent.com/6826088/211370443-46d8cd15-e6dc-4fcd-a956-b34c66649346.png)
![image](https://user-images.githubusercontent.com/6826088/211370516-e378ffc1-824f-4446-acd7-d0278ddf2b84.png)

---

I know this is not a new feature request but all the others are closed without any real resolution.

**Comment by bluebill1049** [comment]
This is a design limitation that we couldn't support.
