### ISSUE TITLE
console.debug field values and errors on submit

### ISSUE THREAD

**Issue by ybelenko** [react-hook-form/react-hook-form#9747]
**Is your feature request related to a problem? Please describe.**
I checked project board and issues, didn't find anything similar. I do know about `@hookform/devtools`, but

1. I don't want to add extra code in each form like `<DevTool control={control} />` because I already have dozens of them 
2. I work on 13" laptop so DevTool takes off too much space on the screen. Usually I have Safari Web Inspector open because it obviously give more information comparing to small tool or extension. So Web Inspector with open console already takes 1/3 of the screen.
3. Not sure about performance. VSCode with TypeScript checking on already feels laggy on my laptop, watching each input with instant rerender might be heavy.

**Describe the solution you'd like**
As temp workaround I wrote my own submit wrapper. It basically just pass callback arguments to `console.debug`. It looks like:
```ts
import { FieldErrors, FieldValues, SubmitErrorHandler, SubmitHandler, UseFormHandleSubmit } from 'react-hook-form';

interface FormSubmitHandlerProps<TFieldValues extends FieldValues> {
  handleSubmit: UseFormHandleSubmit<TFieldValues>;
  onSubmit?: SubmitHandler<TFieldValues>;
  onSubmitError?: SubmitErrorHandler<TFieldValues>;
}

/* eslint-disable no-console */
export const formSubmitHandler = <T extends FieldValues>({
  handleSubmit,
  onSubmit,
  onSubmitError,
}: FormSubmitHandlerProps<T>) => {
  if (process.env.NODE_ENV === 'development') {
    const logger = (arg: SubmitHandler<T> | SubmitErrorHandler<T>) => {
      if (typeof arg === 'function') {
        return async (data: T | FieldErrors<T>, e?: React.SyntheticEvent): Promise<any> => {
          console.debug(data, e);
          await arg(data);
          return null;
        };
      }

      console.debug(arg);
    };
    return handleSubmit(
      typeof onSubmit === 'function' ? logger(onSubmit) : logger,
      typeof onSubmitError === 'function' ? logger(onSubmitError) : logger,
    );
  }

  return handleSubmit(
    typeof onSubmit === 'function' ? onSubmit : () => null,
    typeof onSubmitError === 'function' ? onSubmitError : undefined,
  );
};
/* eslint-enable no-console */
```
It would be great to add an option in hook form constructor to log field values and errors during development.
```js
const { register, handleSubmit } = useForm({
  defaultValues: { name: '' },
  /** of course I don't insist to call these params exactly that way */
  consoleDebugValuesOnSubmit: process.env.NODE_ENV === 'development',
  consoleDebugErrorsOnSubmit: process.env.NODE_ENV === 'development',
});
```

**Describe alternatives you've considered**
Don't have something particular on my mind right now.

**Comment by bluebill1049** [comment]
thanks for the feature request, moving into the project board for up votes.
