### ISSUE TITLE
request: path name assertor or generator to match Path<T>

### ISSUE THREAD

**Issue by harish-prakash** [react-hook-form/react-hook-form#9748]
**Is your feature request related to a problem? Please describe.**
Creating re-usable components that work with `useFieldArray` is almost impossible.

**Describe alternatives you've considered**
Fundamentally this comes down to the `name`. I can create a complex type on the re-usable component like such:
```ts
interface InputProps<
  T extends FieldValues,
  N extends FieldArrayPath<T>
> {
  name: UnpackNestedValue<PathValue<T, N>> extends Data[] ? N : never
  register: UseFormRegister<T>
  control: Control<T>
}
```

However, registering the field property `${name}.0.prop` causes the following compile time error
```
Argument of type '`${UnpackNestedValue<PathValue<T, N>> extends Data[] ? N : never}.0.prop`' is not assignable to parameter of type 'Path<T>'.
  Type '`${string}.0.prop`' is not assignable to type 'Path<T>'
```
This is because the type information is stripped off during execution therefore TS compiler does not maintain this argument-truth in the function-body.

I tried to replicate the type operations from `Path<T>` and the related `PathImpl<T>` and almost succeeded when I realized that I do not have the original object 🤦‍♂️

**Describe the solution you'd like**
Now, if there was a function I could `getPath<T>`, then I can just create a `const propName: Path<T> | undefined = getPath('${name}.0.prop')`. If **`propName`** is `undefined`, I can handle it in the UI

**Comment by Moshyfawn** [comment]
Is #7354 what you're after?

**Comment by bluebill1049** [comment]
> I tried to replicate the type operations from Path<T> and the related PathImpl<T> and almost succeeded when I realized that I do not have the original object 🤦‍♂️

can you provide some more detail on this?

> However, registering the field property ${name}.0.prop causes the following compile time error

any chance you can share a codesandbox on this? I think there will be some sort of assertion that is diffuclt to avoid.

**Comment by bluebill1049** [comment]
Moving to the project board, please keep the feedback above coming.
