### ISSUE TITLE
issue: reference types added in `dirtyFields` when form is updated via `useFieldArray.append` method

### ISSUE THREAD

**Issue by fbolcic** [react-hook-form/react-hook-form#9749]
### Version Number

7.41.5

### Codesandbox/Expo snack

https://codesandbox.io/s/mhwhcq

### Steps to reproduce

A form is added with controllers for updating fields in the left section of the screen. On the right there is a form values and dirty fields spy. The form is initialized with `defaultValues`.

Some form fields control primitive values (eg. `firstName`, `lastName`) while others control reference types (eg. `colors`, `favoriteChild`, `sons`, `daughters`). 
The `sons` and `daughters` fields are controlled with a `useFieldArray`, and `append` function is used to add new data.

When you update fields the `dirtyFields` state works as expected. But when you add new data with the `useFieldArray.append` method, all the other reference type fields (eg. `favoriteChild` and `colors`) are also added to the `dirtyFields` object (even though they are not flagged as true).

This makes checking `dirtyFields` unreliable.

1. Go to _sons_ field in the form
2. Click on _Add_ button
3. On the right section, _Dirty Fields_ will contain all of the reference type fields from the form, even though only the _sons_ field changed (`colors`, `favoriteChild`, `sons`, `daughters`)

### Expected behaviour

`dirtyFields` should contain only the updated form fields. 
In this scenario I would expect something like this:
```
{
 "sons": [
    {},
    {
      "firstName": true,
      "lastName": true
    }
  ],
}
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is expected behaviour at this moment, as we are updating append items with defaultValues, and each input default value is **required instead of partial**. If you don't want to change any of the dirty fields with each action, you can upvote this feature request instead: https://github.com/react-hook-form/react-hook-form/issues/8309

**Comment by fbolcic** [comment]
Thanks for your quick reply. 
unfortunately I do not understand your explanation completely, but since this is the expected behaviour there is not much we can do but build our own `dirtyFields` logic by comparing `formValues` with `defaultValues`.

I don't think that the feature you linked will solve our issue since we still need to flag the array field as dirty. The problem is in the other fields' state which should remain untouched.
Anyway, thank you for your time and for an amazing library 😄.

**Comment by bluebill1049** [comment]
> unfortunately I do not understand your explanation completely, but since this is the expected behaviour there is not much we can do but build our own dirtyFields logic by comparing formValues with defaultValues.

Sorry, if my words are not clear. (It was in the early morning)

basically is the following:

```tsx
defaultValues: {
  test: [{ firstName: '' , lastName: '' }]
}

// if you execute append

append({
  firstName: '',
  lastName: ''
})

// then the dirty Fields for the new append fields will be both true, it's only doing the deep equal inside.
```

The feature request may resolve some of the issue

eg

```
append({
  firstName: '',
  lastName: ''
}, {
   shouldDirty: true // then both field will not be marked as dirty 
})
```

Hope the above make some more sense.

**Comment by fbolcic** [comment]
This makes sense for that exact field which is changed. Our problem is related to the other fields on the form which are also reference types. 
In my example above, appending on the `sons` field will result in other reference type fields ending up in the `dirtyFields` object:
```
{
  'colors',
  'favoriteChild', 
  'sons',
  'daughters'
}
```

**Comment by bluebill1049** [comment]
I see for your use case probably easier to write a custom comparison logic for now until we have the other feature released then you can achieve the above a bit easier:

```tsx
append({
  firstName: '',
  lastName: ''
}, {
   shouldDirty: false
})
setValue(`test.${index}.lastName`, 'son', { shouldDirty: true })
```

**Comment by fbolcic** [comment]
Ok, that is exactly what we were also thinking. Thank you again!

**Comment by bluebill1049** [comment]
closing this issue for now, for everyone else who encounter this issue please upvote this feature request: https://github.com/react-hook-form/react-hook-form/issues/8309
