### ISSUE TITLE
Data storing issue with little-state-machine in Nextjs

### ISSUE THREAD

**Issue by asimhyff** [react-hook-form/react-hook-form#975]
video tutorial:  https://www.youtube.com/watch?v=CeAkxVwsyMU 
i have done almost all the parts , done in MultiStep persist form video tutorial , but data is not storing at the end , pls tell what mistakes had i done ...?!
routing etc...every thing is working fine except it.

![image](https://user-images.githubusercontent.com/56485049/73836054-4adf4e00-4830-11ea-9efb-727888b7f13e.png)

**Comment by bluebill1049** [comment]
more than happy to help? what's not working for you?

**Comment by bluebill1049** [comment]
let's chat there: https://spectrum.chat/react-hook-form?tab=posts

**Comment by bluebill1049** [comment]
console.log the state, see what's in there on each step as well. but leave that question in spectrum we can chat there.
