### ISSUE TITLE
issue: Cannot debounce onChange when using Controllers with MUI

### ISSUE THREAD

**Issue by kroussea** [react-hook-form/react-hook-form#9756]
### Version Number

7.41.5

### Codesandbox/Expo snack

https://codesandbox.io/s/affectionate-james-8jhtq2

### Steps to reproduce

1. Open the sandbox
2. Enter text into the Debounced field
3. Notice in the console that the value hasn't changed for the field

### Expected behaviour

The debounced field does not change the value when its onChange is debounced within a Controller.

It is pretty common to debounce inputs to prevent unnecessary re-renders. The sandbox I built is pretty basic, but when having a bigger application where the form reacts based on which field is filled or not, it can quickly create unnecessary re-renders, and therefore create lag when the user type in the input.

Is there any way I can debounce fields like Textfields of setting their value in React Hook Form?

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
You're using a **controlled** component: you're passing the `value` stored by RHF form the `field.onChange` handler. Debouncing `field.onChange` just means that you don't update the RHF field value state.

Consider either:
- either storing both `value` and `denouncedValue` as separate states
- or utilizing a hook to debounce the field value state from RHF that's passed into your request / other method etc.

It's not specific to RHF, but how controlled inputs are handled.

**Comment by kroussea** [comment]
@Moshyfawn Do you have examples of your considerations?
I think I have a pretty common scenario here, where the data comes from a Database, is being set as defaultValues in useForm, then whenever I submit the form, the data is saved in the DB. You suggest I intercept the value change where exactly?
I can't do it in the controller as you said, so where could I do that?

**Comment by kroussea** [comment]
Nvm actually, found [this](https://codesandbox.io/s/elastic-merkle-2gwfvu) which clearly shows what you suggested.
Thanks for the info!
