### ISSUE TITLE
issue: useWatch gives the old input value

### ISSUE THREAD

**Issue by giedoka** [react-hook-form/react-hook-form#9761]
### Version Number

7.41.5

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-register-with-error-messages-forked-hhtxhr

### Steps to reproduce

1. Open the [Code Sandbox](https://codesandbox.io/s/react-hook-form-register-with-error-messages-forked-hhtxhr)
2. Open the console
3. Start typing in the first input (firstName input).
4. Type something which causes an input error. There is a validation for maximum 2 characters, so type for example `test` and then remove `st`. Error will disappear but in the console you will see that error still exists.

Short video:
https://user-images.githubusercontent.com/16230007/212047201-5f38f43a-6839-4016-b474-9eaeb69ef70f.mov

### Expected behaviour

I am using `useWatch` to watch form values changes. As I can see useWatch gives me the old value of an input. Previously I was using `7.4.0` version of react-hook-form and it was working properly. Now I switched to the newest one and noticed this problem.
I checked when this problem occurred for the first time and it was after [7.14.1](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.14.1) release.

I am not sure if this is an issue or if I am doing something wrong but it would be nice to have this feature working the same as before the 7.14.1 version.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Here is the fix for your use case:

```tsx
useEffect(() => {
  console.log(formValues[0], formState.errors.firstName);
}, [formValues, formState]);
```

> formState is updated in batch. If you want to subscribe to formState via useEffect, make sure that you place the entire formState in the optional array.

https://react-hook-form.com/api/useform/formstate

**Comment by Moshyfawn** [comment]
Looks like it has been resolved in [the sandbox](https://codesandbox.io/s/react-hook-form-register-with-error-messages-forked-hhtxhr)

**Comment by giedoka** [comment]
oh, thanks!
