### ISSUE TITLE
issue: 

### ISSUE THREAD

**Issue by nsit8919** [react-hook-form/react-hook-form#9762]
### Version Number

latest

### Codesandbox/Expo snack

NA

### Steps to reproduce

NA

### Expected behaviour

I am using react hook form for my demo. I am following this package to create my component
https://github.com/adiathasan/mui-react-hook-form-plus

here is package demo link :
https://mui-react-hook-form-plus.vercel.app/?path=/docs/hookautocomplete-%E2%8C%A8--asynchronous-%F0%9F%8F%83

I am using autocomplete component with async task.I want if user type "abc" it will hit API with "abc" text. but issue I am not able to get what user is typing .I already tried to override onchange listener but nothing works for me

 <HookAutoComplete
          {...registerState("movie")}
          autocompleteProps={{
            options,
            autoHighlight: true,
            isOptionEqualToValue: ({ label }, value) => label === value.label,
            loading,
            open,
            onOpen: () => {
              setOpen(true);
            },
            onClose: () => {
              setOpen(false);
            },
            onChange: (e, v) => {
              console.log(e, v);
            }
          }}
          textFieldProps={{
            label: "Movie",
            placeholder: "The...",
            InputProps: {
              endAdornment: (
                <>
                  {loading ? (
                    <CircularProgress color="inherit" size={20} />
                  ) : null}
                </>
              )
            },
            onChange: (e) => {
              console.log(e, "pppp");
            }
          }}
          gridProps={{
            xs: 12
          }}
          rules={{
            required: {
              message: "Required",
              value: true
            }
          }}
        />

here is my code
https://codesandbox.io/s/priceless-kowalevski-c0qjmh?file=/src/App.tsx:1924-3059

Expected output . when user type any text example "abc" it fire a aync request (dummy request with "abc" text only .

dummy request

React.useEffect(() => {
    let active = true;

    if (!loading) {
      return undefined;
    }

    (async () => {
      await sleep(1e3); // For demo purposes.
      // need to get what user type
      // if (active) {
      // 	setOptions([...top100Films]);
      // }
    })();

    return () => {
      active = false;
    };
  }, [loading]);

### Relevant log output

```shell
NA
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848
