### ISSUE TITLE
Unable to persist state when unregistering/registering fields

### ISSUE THREAD

**Issue by joe4mg** [react-hook-form/react-hook-form#977]
Hi Bill,

Following on from https://github.com/react-hook-form/react-hook-form/issues/970 I have some further questions/requests.

I would like to persist a field value between a Controller getting unmounted and then mounted (sharing the same field key).

I can save state within the form and pass down an object (e.g. `{ [fieldKey]: fieldValue }`) that is then passed to each matching `Controller`s `defaultValue` prop. Unfortunately these are then ignored if the form has been instantiated with the same keys in the `defaultValues` prop (as explained in issue 970).

I could save state outside of the form and then re instantiate the form with updated `defaultValues` but I don't want to do that (i'm building a component that builds fields to use within a form).

I have tried manually keep track of the field values in state and then updating via `setValue` but keeping the field state is tricky as `const watchSomething = watch("something")` will change to the form default value when the field is unregistered.

The best I have come up with it to check if there is a defaultValue prop and if so aborting the unregister: https://codesandbox.io/s/react-hook-form-controller-kboxt

This feels quite hacky - I'd love to know if there was a cleaner way to do it (without holding state outside a form) or using an approach like the above.

**Comment by bluebill1049** [comment]
Thanks for the detailed question above. RHF embraces native input and so does how native form 
works.

```
<form>
 //inputs...
</form>
```

RHF just work as a native form in HTML, which is collect inputs within the tag and submit the data. That's the difference between controlled form, which inputs and input data is hosted in local state, hence even when you remove the input and data still persist and it's up to you clear it. There are pros and cons at the same time. Personally I prefer native form behavior for the obvious reasons why I build such a tool. However, I do see your pain and frustration as you are dealing with a tradeoff which this lib is not intended for. few options on top of my head

1. custom register without unregister, so register during the `useEffect`
2. calling `setValue` when your component is mounted again.
3. make your input visibility hidden.

**Comment by bluebill1049** [comment]
closing this issue, feel free to reply and ask more questions
