### ISSUE TITLE
issue: does not work reValidateMode when updating 7.41.5 to 7.42.0

### ISSUE THREAD

**Issue by Bookman0001** [react-hook-form/react-hook-form#9773]
### Version Number

 7.42.0

### Codesandbox/Expo snack

[code link](https://github.com/Bookman0001/nagato/blob/master/src/components/organisms/receptionForm/ReceptionForm.tsx)

### Expected behaviour

RevalidateMode does work as well as v 7.41.5.

#### Detail Info
I'm using zodResolver, but revalidateMode doesn't work when updating it to v7.42.0.

```
const { register, handleSubmit, control } = useForm<FormInput>({
    resolver: zodResolver(schema),
    // Now, it can not change "reValidateMode"  behaviour, it depends on "mode" API behaviour,
    reValidateMode: 'onChange',
  })
```

### What browsers are you seeing the problem on?

Safari 16.2

### Relevant log output

No log content

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/weathered-sunset-ybtld6?file=/src/App.tsx https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by Bookman0001** [comment]
@bluebill1049 Thank you!

 I edited the code based on your link.
Please review the revalidateMode behaviour. 🙏

https://codesandbox.io/embed/angry-dust-j76j1h?fontsize=14&hidenavigation=1&theme=dark

**Comment by bluebill1049** [comment]
thanks for the update. I will look into it.
