### ISSUE TITLE
Allow user to disable e.preventDefaut call inside handleSubmit 

### ISSUE THREAD

**Issue by ankit-kumar-jat** [react-hook-form/react-hook-form#9774]
**Is your feature request related to a problem? Please describe.**
I am using [remix web framework](https://remix.run/). remix allows you to define an `action`(runs on server) that will be called by forms( form submission). They provided a Form component that does form submission for you, `actions` also works with default HTML form submission. The issues is react-hook-form calls `e.preventDefault()`  inside [handleSubmit](https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/createFormControl.ts#L1030) , that prevents Form component to do form submission.

**Describe the solution you'd like**
We can add it in configuration of `useForm` hook, we can name it `shouldPreventDefault` (boolean type). By default it would be `true` so it will not break apps.
if user sets `shouldPreventDefault` to `false`, In that case `handleSubmit()` will only call `e.preventDefault()` in case of form validation error before calling `SubmitErrorHandler`. and if there is not validation error `e.preventDefault()` will not be called and form will be submitted by browser. user can still call `e.preventDefault()` inside `SubmitHandler` and prevent form from default submission.

**Describe alternatives you've considered**
I am doing form submission manually using useSubmit hook provided by remix ( basically recreating remix's `Form` component )

**Comment by bluebill1049** [comment]
Thanks for the feature request you can do this for now `onSubmit={() => handleSubmit()()}`

`handleSubmit((), (), { shouldPreventDefault: false })` perhaps we can have the third option for the API. I am moving this into the project board, this could be the API same for the "potential" new Fom component.
