### ISSUE TITLE
issue: any button calls onSubmit of the form

### ISSUE THREAD

**Issue by lucy2329** [react-hook-form/react-hook-form#9779]
### Version Number

7.29.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-form-context-forked-3ktsz9?file=/src/index.js

### Steps to reproduce

1. Create react hook form
2. Add a <button> element within the <form> ... </form> tag
3. Clicking this button automatically triggers onSubmit of the form.

### Expected behaviour

Not sure if every button is expected to call onSubmit.  I have added the change in the official code sandbox example from here: [React Hook Form Docs](https://react-hook-form.com/api/useformcontext)

You can find the sandbox [here](https://codesandbox.io/s/react-hook-form-v7-form-context-forked-3ktsz9?file=/src/index.js)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> type = submit|button|reset [CI]
> This attribute declares the type of the button. Possible values:
> submit: Creates a submit button. This is the default value.

http://www.w3.org/TR/html401/interact/forms.html#h-17.5

This is default browser behaviour and you can follow the spec above
