### ISSUE TITLE
Access form's `context` propery from `useFormContext`

### ISSUE THREAD

**Issue by gerrod** [react-hook-form/react-hook-form#9787]
## Is your feature request related to a problem? Please describe.

When a form is created, we can pass an optional `context` property. There is not a lot of documentation around this `context` property, and at the moment it seems to only be used for hooking up to a resolver.

```tsx
type MyFormContext = { someProperty: string };

const myControl = () => {
  const context = { someProperty: 'someValue' };
  const form = useFormContext<FieldVaules, MyFormContext>();

  return (
    <FormProvider {...form}>
      <form {/* ... */}>
      </form>
    </FormProvider>
  );
};
```

Once the form is created, there's no easy way to get the context back again. The `context` property passed to the form does not get returned with `useFormContext` and there's no custom hook that can be used to retrieve it either:

```tsx
const SomeComponent = () => {
  const { context } = useFormContext<unknown, NameFormCustomisation>();  // ERROR - no such property
};
```

We are in the process of using RHF to build reusable forms, where the consumers can customise various parts of those forms based on a "customisation" object. As a contrived example, we are building something along the lines of:

```tsx
interface NameFormValues {
  firstName: string;
}

interface NameFormCustomisation {
  firstName?: {
    label?: string;
  }
}

interface NameFormProps {
  customisation?: NameFormCustomisation;
}

const NameForm = ({ customisation }: NameFormProps) => {
  const form = useForm<NameFormValues, NameFormCustomisation>({ context: customisation });
  const { register, handleSubmit } = form;
  
  // ----- 8< -----

  return (
    <FormProvider {...form}>
      <form onSubmit={handleSubmit(onSubmit)}>
        <FirstNameField />
        
        <input type="submit" />
      </form>
    </FormProvider>
  );
}
```

So in `FirstNameField`, we'd like to get the `customisation` via the form's `context` property, but the only way to do that is via a hacky feeling work-around:

```tsx
const FirstNameField = () => {
  // It would be nice to be able to do this:
  // const { context } = useFormContext<unknown, NameFormCustomisation>();

  // Hacky work-around
  const { control } = useFormContext();
  const { context } = control._options;

  return (
    <input
      {...register("firstName")} 
      placeholder={context?.firstName?.label ?? 'First name'} 
    />
  );
};
```

## Describe the solution you'd like
Add the form's `context` property to the return type of `UseFormReturn`:

```ts
export type UseFormReturn<
  TFieldValues extends FieldValues = FieldValues,
  TContext = any,
> = {
  context?: TContext;
  // ...
};
```

`createFormControl` would also need to add this to it's return - but it already has access to the context via `props` -
```ts
export function createFormControl<
  TFieldValues extends FieldValues = FieldValues,
  TContext = any,
>(
  props: UseFormProps<TFieldValues, TContext> = {},
  flushRootRender: () => void,
) => {
  // ----- 8< -----

  return {
    context: props.context,
    // ...
  };
};
```

## Describe alternatives you've considered
The alternative here would be to create our own context via `React.useContext(...)` and then wrap our forms in that. But, given that the `FormProvider` is already doing this for us, it would be nice to be able to use that one instead.

**Comment by bluebill1049** [comment]
Thanks for the detailed feature request. Have you considered storing this in a state management library? such as zustand, xstate, redux, jotai and etc?

**Comment by gerrod** [comment]
Yep, for sure - we use redux toolkit (RTK) on the project too, so we could put it there - but I don't like this solution because the context for the form is very specific to that form; where-as we use RTK more for "global" state (like notifications, global preferences, etc).

If we can't go via the form's `context` property then we'll likely use a react context (as mentioned above) so that the state can be controlled entirely within the consuming component. When that component unmounts, the extra context would also be removed (rather than living on indefinitely in the RTK store).

I still think the form's `context` property is overall the best since the form already has a `context` property - which means we're already "paying the cost" (so to speak) for the property to exist, I figured we may as well just make it easier to access.

Thanks for the reply @bluebill1049 !
