### ISSUE TITLE
issue: Can't get dirtyFields to work with Ionic Inputs 

### ISSUE THREAD

**Issue by SaroGFX** [react-hook-form/react-hook-form#9788]
### Version Number

7.42.1

### Codesandbox/Expo snack

https://codesandbox.io/s/defaultvalues-5uusrq?file=/src/Form.tsx

### Steps to reproduce

1. Create Ionic React 6.0 and build form with defaultValues
3. Log out the dirtyFields 

### Expected behaviour

When changing the inputs, I would expect the useEffect to console.log the `isDirty` and `dirtyFields` with the correct values. For some reason I can't get the `dirtyFields` to work with Ionic Inputs. 

Other reports always point to the missing DefaultValues, which have been added in my [reproduction](https://codesandbox.io/s/defaultvalues-5uusrq?file=/src/Form.tsx) so I am eager to learn what is causing this and if there are workarounds. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
hey, @SaroGFX I think this is not an issue related to hook form, could you try it out with `Controller` https://react-hook-form.com/api/usecontroller/controller? because the Ionic component may not support uncontrolled `register` API.

**Comment by SaroGFX** [comment]
Hi @bluebill1049 

Thank you for the reply. I have changed the reproduction [Codesandbox to use Controller](https://codesandbox.io/s/defaultvalues-5uusrq?file=/src/Form.tsx) but it has the same results unfortunately. 

It is indeed not so much an issue with Hook Form as it's more a compatibility issue with Ionic and it's shadow DOM inputs. Should I open a ticket as a question instead?

**Comment by bluebill1049** [comment]
You had an incorrect usage, please refer below and the doc

```
<Controller
  render={({ field }) => <IonInput value={field.value} onChange={field.onChange} onBlur={field.onBlur} />}
  name="firstName"
  control={control}
/>
```

**Comment by bluebill1049** [comment]
also please remove the useEffect in your example as well

```diff
- useEffect(() => {
  console.log("isDirty", isDirty);
  console.log("dirtyFields", dirtyFields);
  console.log("getValues()", getValues());
- });
```

**Comment by SaroGFX** [comment]
Thank you very much, that makes it work. Do you think it's also achievable without the <Controller /> ?

**Comment by bluebill1049** [comment]
Awesome to hear! Unless those components support uncontrolled.

**Comment by SaroGFX** [comment]
Awesome indeed, thanks for the help! 
Yea, we build the whole app without using the <Controller /> so far, but had to find some workarounds on some issues. I was looking into using `dirtyFields` but that was one thing not working.

Weirdly enough, `isDirty` does work correctly (but defaultValues are required for all fields, which is not the case it seems when using <Controller>

**Comment by bluebill1049** [comment]
> Weirdly enough, isDirty does work correctly without the (if defaultValues are provided for all fields, which doesn't seem to be required when using ).

can you share a csb? it's just a deep equal against your form values with defaultValues (internally).

**Comment by SaroGFX** [comment]
Hmm, cannot seem to reproduce it in csb. Both isDirty and dirtyFields do not work. Also tried in our repo, and while isDirty get set to true, it already happens when focussing an input and never goes back to false. Not sure what triggers it to be set to true there, but its a pretty complex project with many useEffects, so who knows 🤷‍♂️ .

**Comment by SaroGFX** [comment]
Sorry, It does work perfectly with the `<Controller>`.  I meant that without the controller, I had an instance where the isDirty kind of worked, but the dirtyFields didn't. I cannot reproduce it though. Without the `controller`, neither of them work. 

For some reason GitHub removed the word `<Controller`>  from my previous comment so it's not making much sense anymore, i've put it back with `.

**Comment by bluebill1049** [comment]
I think `@ionic/react` only supports controlled component so you should use `Controller` instead of `register`
