### ISSUE TITLE
Calling setValue on a list has no effect

### ISSUE THREAD

**Issue by Betree** [react-hook-form/react-hook-form#979]
**Describe the bug**
Hello there, I'm currently building a dynamic form and facing some issues with `setValue`. The general idea is this:

- The form is managing a dynamic list of friends (firstName, lastName)
- I'm retrieving the list of friends with `watch('friends')`
- The inputs for firstName/lastName are using `register`:

```jsx
<input ref={register} name={`friend[${index}].firstName`} />
```

- I have a special button that sets the value of `firstName` to `toto`, this one uses `setValue`:

```jsx
<button type="button" onClick={() => setValue(`friend[${index}].firstName`, "toto")}>
  Set first name to "Toto"
</button>
```

- Finally, the code to add or remove friends looks like this:

```jsx
<button type="button" onClick={() => setValue('friends', [...friends, {}])}>
  Add friend
</button>
```

The code above works for editing, but adding or removing items doesn't work (setValue has no effect). The only difference in this one is that I'm calling `setEffect` with the root field `friends` instead of `friends[0]`.

**Codesandbox link**
See https://codesandbox.io/s/react-hook-form-problem-with-array-fields-sh7y3

**Expected behavior**
`setValues` should work with nested fields.

**Screenshots**
![Peek 05-02-2020 18-57](https://user-images.githubusercontent.com/1556356/73868791-686ce180-4849-11ea-98b1-6cce08bba6ed.gif)

---

This issue seems close to https://github.com/react-hook-form/react-hook-form/issues/256 and https://github.com/react-hook-form/react-hook-form/issues/640. However I didn't see any actionable on these and having this would really help me to move forward. I'd be happy to help with the implementation.

**Comment by bluebill1049** [comment]
hey @Betree 

Thanks for the detailed issue report. I will have a closer look tonight. Have you considered to use our new custom hook `useFieldArray`?

https://react-hook-form.com/api/#useFieldArray

I took a brief look at it, it looks like that custom hook may do the job.

**Comment by bluebill1049** [comment]
`setValue('friends', [...friends, {}])`

yes we don't support this syntax at the moment. it's on my backlog.

**Comment by bluebill1049** [comment]
same feature requested here as well: https://github.com/react-hook-form/react-hook-form/issues/961

**Comment by Betree** [comment]
Awesome, `useFieldArray` did the job. Thanks @bluebill1049!

The `setNestedValues` proposed in #961 sounds good to me.

I personally think that it's useful to keep issues open until they're addressed (so either implemented, marked as invalid or wontfix). Closing an issue means "we're done with it", I and certainly other contributors don't pay as much attentions to closed issues when reporting bugs or proposing features because they are supposed to be completed items. I'm just offering some different perspective, of course it's up to you to choose whatever is easier for you to manage as a maintainer.

**Comment by bluebill1049** [comment]
Thanks, @Betree for your suggestion. I like to keep issues for only "issues". features requests and enhancement all end up in my backlog.  That way its easier for me to manage. I will tackle setValue with nested data once my current plate is clear.
