### ISSUE TITLE
Unable to type INVALID state of the form (potential design flaw)

### ISSUE THREAD

**Issue by peter-goodfill** [react-hook-form/react-hook-form#9798]
### Version Number

7.41.5

### Codesandbox/Expo snack

https://codesandbox.io/s/inspiring-artem-iicsf4?file=/src/App.tsx

### Steps to reproduce

1. create component with a typed state
2. initialize with empty default state
3. **value in the field is typed as type from state, but in reality its `undefined`**

### Expected behaviour

React Hook Form should somehow distinguish between two types of a state

1. Type of the state that is **IN REALITY** in the form (can be invalid from a perspective of the form validation)
2. Type for valid form, this is the type that is inferred from the validation scheme and this state us guaranteed in the `onSubmit()` function

### More context

Here is a code from the sandbox
![image](https://user-images.githubusercontent.com/91760307/213259231-09fcf242-2e34-473f-95ea-1a01ce5dfb39.png)

You can see that react produces warning, because `<input/> component was in the invalid state.
```
Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen.
```

### Maybe relevant issues and discussions:

1. Those buys are hitting the same issue I believe but in more complicated context: 
   - https://github.com/react-hook-form/react-hook-form/issues/8046#issuecomment-1074054273
   - and https://github.com/react-hook-form/react-hook-form/issues/8046#issuecomment-1104612796
 2. Not sure if I understand this issue but maybe it talks about same problem https://github.com/react-hook-form/react-hook-form/issues/9600
 3. This discussion seems to cover similar topic: https://github.com/react-hook-form/react-hook-form/discussions/8496

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Thank you for looking into this in depth.

Currently, the type-definition for `defaultValues` is just `Partial` `FieldValues` which does create the type discrepancy you are noticing your example.

https://github.com/react-hook-form/react-hook-form/issues/9600#issuecomment-1374281441 kinda addresses it. Please, take a look and potentially provide your feedback.

I, personally, am yet to find a sufficient enough and type-safe solution to this problem, but there're multiple talks in RHF about this, including the issues you've kindly linked.

**Comment by bluebill1049** [comment]
We will consider changing the type in the next major and removing the deep partial.

**Comment by peter-goodfill** [comment]
I understand that `defaultValues` are `Partial` of the `Schema` type. But this is exactly reason why this bug is there. And I really believe it is a bug.

`<input` is quite benevolent component, it will take the `undefined` and will (with warning) work.

However imagine some strict (custom) form component that requires `string|null` and if `undefined is provided it will fail horribly.  But in the `zod` scheme, I validate the string something. 

Here is the codebox example: https://codesandbox.io/s/thirsty-villani-htovis?file=/src/App.tsx

I am now in unsolvable situation, where

- I cannot relax `zod scheme, because `null` is not valid
- I have to provide default value `null` otherwise the component fails, but it produces type error
- Plus I still have the problem that `field.value` is typed as `string` because `zod` scheme, but in reality it can be `string|null`


-------------------------


I don't see any other proper solution to this problem, then to separate the **valid** form state type (zod infered Scheme) from the actual state type of the form.

Formally: The validated form type is the *product* of the validation function configured by `schema` from the state of the form, which type is defined differently, and **allows for different values** to represent all the situations where user is in the process off filling the form, but it is not valid yet according to the `Scheme`

**Comment by peter-goodfill** [comment]
Another problematic example is the `setValue`. It required the **VALID** value according to the `Scheme`. But there are many cases where it is not possible to provide it.

Here is again the codebox example: https://codesandbox.io/s/funny-cloud-2hxzg6?file=/src/App.tsx

If I want to conditionally show address and validate that country is required, but I don't want to present user with empty select box to choose (not preselect country) it is not possible without type error on `setValue`
