### ISSUE TITLE
Option to pass disabled and readOnly to useForm.

### ISSUE THREAD

**Issue by nitedani** [react-hook-form/react-hook-form#9806]
**Is your feature request related to a problem? Please describe.**
Right now if I want to disable a field I need to pass `disabled: true` to `register()`. If I have many fields this becomes repetitive.
Also `register()` doesn't support the `readOnly` prop.

For context:
In my application there are two levels of access to the form: "read" and "edit". I would like to set the whole form to read-only(not greyed out) if the access is "read".
In my UI kit, I'm using the `readOnly` prop to set an input field readOnly, but not greyed out.
I'm using the `disabled` prop to grey out the field(in addition of being read-only, of course).

**Describe the solution you'd like**
I would like to pass `disabled: true`/`readOnly: true` to useForm. This would `disable`/`readOnly` all of the fields.
I would like `register()` to return the `readOnly`/`disabled` prop, defaulting to the `readOnly`/`disabled` option passed to `useForm`. (`disabled` and `readOnly` are two separate props, used for a different purpose in my use case. Would you consider adding the additional `readOnly` prop to `register()`s return value? )

Example:
```ts
const { register } = useForm({ disabled: true , ... })
...
<input {...register("name")} /> this input is disabled
<input {...register("email")} /> this input is disabled
```

```ts
const { register } = useForm({ readOnly: true , ... })
...
<input {...register("name")} /> this input is readOnly
<input {...register("email")} /> this input is readOnly
```

**Alternatives**
A way to disable/readOnly the whole form, setting a single option.
In the meantime, I solved this by patching `methods.register` to return what I want.

**Comment by bluebill1049** [comment]
This is already under work you can refer to this PR. https://github.com/react-hook-form/react-hook-form/pull/9115 The api is not stable in the API but will get there, my current proposal is going to be an enum.

`disabled: boolean | 'onSubmit'`

**Comment by bluebill1049** [comment]
moving to the project and under proposal.
