### ISSUE TITLE
issue: ref is intercepting errors from useForm and it forces other input to be error also

### ISSUE THREAD

**Issue by leonelcaroc** [react-hook-form/react-hook-form#9807]
### Version Number

7.32.2

### Codesandbox/Expo snack

N/A

### Steps to reproduce

1. Create react hook form
2. Make some required input fields like first name and last name
3. Make an element that if you click on it, it will focus on input element.

### Expected behaviour

useForm errors must not intercept ref props so that I can use useRef focus without triggering any errors.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Please, provide a repo sandbox
#2848
