### ISSUE TITLE
issue: Required field validation is not working on inputs type="hidden"

### ISSUE THREAD

**Issue by SYugel** [react-hook-form/react-hook-form#9814]
### Version Number

7.42.1

### Codesandbox/Expo snack

https://codesandbox.io/s/async-framework-s2mp7e?file=/src/App.js

### Steps to reproduce

1. Open the code sandbox.
2. There are four inputs in the form. 
  - One is the name it is input type="text" and has a value and defaultValue both set to undefined. This is the only visible input on the form.
  - One is a hidden input with no value or default value set.
  - One is a hidden input with a value set to undefined.
  - One is a hidden input with a default value set to undefined.
 3.  Click the Submit button.
   -  You should see errors show up in a list near the top of the form. One error for each of the four fields since they are all required.
  4. Type some text into the Name text input.
    - You will see the required error go away for this input.
  5. Click the button "Set Hidden Input Values" This calls setValue for each of the hidden inputs and sets there value to be "1".
    - You will see the required error go away for all the hidden inputs. 
  6.  Now click the "Submit" button again.
    - Uh-Oh the required validation fails on the hidden inputs. The one that passes undefined as a value and the one that passes undefined as a defaultValue. 

### Expected behaviour

Hidden inputs should properly validate when required and they have been set via the setValue function even when the defaultValue or value is passed in as undefined. This is the behavior that worked before.  It is also the behavior that works on other inputs that don't have type="hidden".

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SYugel** [comment]
Some more information I have figured out.

The problem appears to be in the [validateField function](https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/validateField.ts#L72) where the ```ref.value === ''``` is checked. For the hidden inputs with the value or default value set they appear to have an empty string here. However this validation passes when we initially set those field via the setValue. So they seem to have a different ref.value when you click the submit button. 

Prior to  ```ref.value``` being introduced to the ```isEmpty``` check in the validateField function this all worked because the inputValue is not set to an empty string. However the ```ref.value``` is still an empty string. So if you go back to version 7.41.1 the field validation works as expected but not because ref.value is properly set. Just because its not part of the ```isEmpty``` check.

**Comment by bluebill1049** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required

our validation API is trying to align with the native constraint API, so this is not the case that we are trying to cover there.

> The attribute is not supported or relevant to [range](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range) and [color](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color), as both have default values. It is also not supported on [hidden](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/hidden) as it can not be expected that a user to fill out a form that is hidden. Nor is it supported on any of the button types, including image.
