### ISSUE TITLE
issue: Field error stays displayed even when form is valid

### ISSUE THREAD

**Issue by Mikoz93** [react-hook-form/react-hook-form#9819]
### Version Number

7.42.1

### Codesandbox/Expo snack

https://codesandbox.io/s/floral-field-bmd27w?file=/src/App.js

### Steps to reproduce

1. Enter `qwe@gma.com` into the `Email` field
2. Enter `qwe@gmail.com` into the `Confirm email` field
3. An error message for the `Confirm email` field should be displayed at this point ('Email addresses do not match')
4. Change the value of `Email` field to `qwe@gmail.com`
5. The `Is valid` message should now say `valid`
6. Blur the `Email` field
7. The error message under the `Confirm email` field remains on screen.

### Expected behaviour

Given that the form correctly recognises that it's valid after the value in the `Email` field is corrected, I would expect the error message for the `Confirm email` field to no longer be returned.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mikoz93** [comment]
Hi, this is a strange one. I've tried different `mode`s but no luck. This seems like a fairly common use case, where a user miss-types one of the input values and goes back to edit it. At this point I'd like the error message to disappear as to not confuse the user. It seems that the form revalidates the input and correctly reports that it's not longer invalid, but the error message is still being returned for that particular field.

**Comment by Moshyfawn** [comment]
This is an expected behaviour.

The validation happens on the field that's manipulated _(blurred, changed etc.)_.

You can provide a `deps` props specifying the dependant field validation.

```js
useController({ deps: ["confirm_email"] })
```

Here's [a working sandbox](https://codesandbox.io/s/modest-kowalevski-7dxepq)

**Comment by Mikoz93** [comment]
@Moshyfawn Oh interesting. I couldn't find this under the `useController` documentation. It seems that it's only documented under the `register` function. In my original project, where I'm using typescript, I'm getting a type error when attempting to add `deps` to the `useController` call:

<img width="807" alt="image" src="https://user-images.githubusercontent.com/16376504/213943684-ddc53fb5-76d8-45ea-a33b-4a219dccc7bb.png">

Do you know if adding this to the docs and potentially expanding the typescript types is on a current roadmap?

**Comment by Moshyfawn** [comment]
> @Moshyfawn Oh interesting. I couldn't find this under the `useController` documentation. It seems that it's only documented under the `register` function. In my original project, where I'm using typescript, I'm getting a type error when attempting to add `deps` to the `useController` call:
> 
> Edit: Ignore the previous message regarding the typescript issue, I've just noticed that the `deps` need to be placed under `rules`. Thanks for your help :)

There's a not so prominent mention of the rules API on [the `useController` page](https://react-hook-form.com/api/usecontroller), pointing at the `register` options
![image](https://user-images.githubusercontent.com/16290753/213945609-8e32180e-b0fd-442d-9c9a-afccaaced18a.png)
