### ISSUE TITLE
Integrate `eslint-plugin-simple-import-sort`

### ISSUE THREAD

**Issue by iamdevlinph** [react-hook-form/react-hook-form#982]
@bluebill1049 I read on this [comment](https://github.com/react-hook-form/react-hook-form/pull/925#discussion_r372128557) that you might apply an organize import to the repo.

[eslint-plugin-simple-import-sort](https://www.npmjs.com/package/eslint-plugin-simple-import-sort) might be a good solution since it is an eslint plugin and can work with the precommit hook.

This is how the imports will look like. The relative imports will  be separated.
```js
import get from 'lodash/get';
import React, { KeyboardEvent, useState } from 'react';
import { Controller, useFormContext } from 'react-hook-form';
import { Form, Icon, InputProps } from 'semantic-ui-react';
import { createGlobalStyle } from 'styled-components';

import { CustomErrors, FormError, StyleProps } from '../form-error';
```

I can do a PR for this one if needed.

**Comment by bluebill1049** [comment]
yes please @iamdevlinph if you have time :) much appreciated 🙏

**Comment by bluebill1049** [comment]
nvm, I think we can leave without it :) one less package to install too.
