### ISSUE TITLE
issue: 7.42.x – isSubmitting remains to true after error in submit function

### ISSUE THREAD

**Issue by marcalexiei** [react-hook-form/react-hook-form#9821]
### Version Number

7.42.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-7-42-1-issubmitting-stuck-after-error-jp817h?file=/src/index.js

### Steps to reproduce

1. Go to the [sandbox example](https://codesandbox.io/s/react-hook-form-7-42-1-issubmitting-stuck-after-error-jp817h?file=/src/index.js)
3. Click on 'Submit'
4. Wait 2 seconds
5. A js runtime error is thrown and the `isSubmitting` flag remains to `true`

### Expected behaviour

`isSubmitting` flag return to false after an error occurred during validation function.
Prior to version 7.42.0 (tried with 7.41.5), the flag value was reset to `false` after an error occurred.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marcalexiei** [comment]
I think the issue has been introduced with this [commit](https://github.com/react-hook-form/react-hook-form/pull/9688/files#diff-5a85c1643c71f45e050ce584d7c0db2bdf2e56f8a7dae86d74fedf01be2d2cab) from #9688

**Comment by Moshyfawn** [comment]
I don't think we're supporting throwing errors in the `onSubmit` callback

cc: @bluebill1049

**Comment by marcalexiei** [comment]
To better clarify my use case:
In my app the error is thrown by an API request ([we use `react-query` and error are handled by mutation callbacks](https://tanstack.com/query/v4/docs/react/guides/mutations#mutation-side-effects)). 

With version 7.42.1 I end up in a scenario where I see the error message but the Submit button is disabled due to the `isSubmitting ` still set to `true` after the error. 

---

> I don't think we support throwing errors in the onSubmit callback

To fix the issue I have to wrap each function in a try-catch myself.
This action wasn't required in 7.41.5 version, where there was a `try catch` inside  `createFormControl#handleSubmit` which was wrapping the validation execution.

Now if this  is expected behaviour I think you should consider to add this modification to the changelog.
Maybe also mention this in the documentation (I can create a PR if you wish).

**Comment by bluebill1049** [comment]
the changelog was added: https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md feel free to send a PR on the doc as well.

**Comment by amalitsky** [comment]
@bluebill1049, it is certainly the right thing **not to** swallow unhanded exceptions but `isSubmitting` flag is controlled by the library and has be set to `false` on failure. Otherwise state is out of sync with reality.

Potentially you could `catch` the _user-code-caused_ exception, do the cleanup and [re-throw the original error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw#rethrow_an_exception)?

cc @giovannipiller

For the reference [code that is responsible for handling submission](https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/createFormControl.ts#L1046-L1065).

**Comment by bluebill1049** [comment]
We have a better plan for such a use case in the coming update.

```
<Form
  action="/api/test"
  method="post"
  reject={() => {
    // you can sort out the catch here
  }} 
/>
```

**Comment by amalitsky** [comment]
@bluebill1049, I don't have a problem sorting out the exception honestly. But:
- it seems to be an artificially imposed restriction that my `onValid` callback can't return a rejected promise (I know that unhandled exceptions is not a good engineering practice, but IMO it should be user's responsibility/choice still). What if the same callback is used elsewhere in my code, where I _can_ add another `.catch` listener?
- No matter what we add in docs section and how good our intentions are, we can't assume that everyone will follow instructions and do the right thing. We can't use **their** mistake as an excuse **for us** to bail out of form state consistency.

**Comment by bluebill1049** [comment]
It's generally best practice to catch errors with any async callback and especially `fetch`. At this stage, I personally don't want to go to the route of re-throw error inside.

**Comment by amalitsky** [comment]
My last argument is that the only way to handle the submission error **and** maintain the form state consistency is to use `setError`, which implies that I want to handle submission errors the same (or similar) way as form validation errors.

Which is not always the case - from UX and code implementation perspectives.

I can certainly do anything I want in my callback, but have to notify the library even if I won't use that custom error. Not sure if library itself has any use for those errors either.

**Comment by bluebill1049** [comment]
>I can certainly do anything I want in my callback, but have to notify the library even if I won't need that custom error. Not sure if library itself has any use for those (request related) errors unless I'm printing them out.

What do you mean by that? So you don't want to catch that error in your app and result in runtime error?

**Comment by bluebill1049** [comment]
> My last argument is that the only way to handle the submission error and maintain the form state consistency is to use setError, which implies that I want to handle submission errors the same (or similar) way as form validation errors.

Also, don't make this an argument, let's discuss it here and find a potential solution.

**Comment by bluebill1049** [comment]
PR try to address this issue: https://github.com/react-hook-form/react-hook-form/pull/9849
