### ISSUE TITLE
issue:  Using allowClear function of antd select components does not reset field.value

### ISSUE THREAD

**Issue by SugaKaori** [react-hook-form/react-hook-form#9825]
### Version Number

7.42.1

### Codesandbox/Expo snack

https://codesandbox.io/s/basic-usage-antd-4-24-7-forked-v38mt9?file=/demo.tsx

### Steps to reproduce

1. Set defaultValue
2. Click on clearbtn in Select
3. See error

### Expected behaviour

field.value is updated with undefined

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alvinlys** [comment]
i guess you need to declare custom onClick clear function.  
can refer here: https://stackoverflow.com/questions/74229536/can-i-custom-allowclear-function-on-antd-form
