### ISSUE TITLE
issue: async defaultValues incorrect return type

### ISSUE THREAD

**Issue by krystofrezac** [react-hook-form/react-hook-form#9833]
### Version Number

7.42.1

### Codesandbox/Expo snack

https://codesandbox.io/s/modest-northcutt-of7yon?file=/src/App.tsx

### Steps to reproduce

Pass async function to `defaultValues` that return partial `TFieldValues`

### Expected behaviour

It shouldn't cause TS error

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krystofrezac** [comment]
I think it could be easily fixed with this change in `src/types/form.ts`
```diff
-export type AsyncDefaultValues<TFieldValues> = (payload?: unknown) => Promise<TFieldValues>;
+export type AsyncDefaultValues<TFieldValues> = (payload?: unknown) => Promise<DeepPartial<TFieldValues>>;
```

**Comment by bluebill1049** [comment]
Thanks for the issue report, we are trying to move away from deep partial, in fact, this is going to be removed in the next major version release.

**Comment by krystofrezac** [comment]
Oh ok. So there will be no way how to set only some `defaultValues` in the future? Is there any other way how to do this or should I use `reset` for this use case?

**Comment by bluebill1049** [comment]
> Oh ok. So there will be no way how to set only some defaultValues in the future? Is there any other way how to do this or should I use reset for this use case?

You can use reset now, but we want to move away from `deepPartial` all together.

**Comment by krystofrezac** [comment]
👍 Thanks
