### ISSUE TITLE
issue: Switch value not being set by React-Hook-Form

### ISSUE THREAD

**Issue by ThyagoMC** [react-hook-form/react-hook-form#9836]
### Version Number

7.42.1

### Codesandbox/Expo snack

https://codesandbox.io/s/chakra-ui-react-hook-form-switch-forked-zizlwy?file=/package.json:515-521

### Steps to reproduce

When using Chakra UI with react hook form, I am able to control the input fields as expected. However, when using a Switch component, the reset() action is not able to reset the value of the component

The reset only work if isn't passed any value to it and only to uncheck the Switch. 
If a defaultValue is provided for the Switch as checked  it will be shown as expected on the first render but the reset function will only uncheck the Switch.
If some value is passed to the reset function it will not affect any Switch  component.

I wonder if there is a potential to revise the integration of this component?

1. Go to ['codesandbox'](https://codesandbox.io/s/chakra-ui-react-hook-form-switch-forked-zizlwy?file=/src/HookForm.js)
2. Change the name field to another value
3. Click on switch component to make it deactive
4. Click on reset button.
The name field is reset correctly, but the switch remains unchanged

### Expected behaviour

When using the reset with an value for the Switch this value should be used.

When using the reset without an value for the Switch the defaultValues should be used.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`Switch` is a controlled component, please use Controller instead. Take a look at this CSB in the doc: https://codesandbox.io/s/chakra-ui-5mp8g

https://react-hook-form.com/api/usecontroller/controller

![Screenshot 2023-01-28 at 9 33 11 am](https://user-images.githubusercontent.com/10513364/215218842-cc23cdd5-ebd0-40c0-9525-43a205f4bc54.png)
