### ISSUE TITLE
useFieldArray append functionality duplicates items in v4.8.2

### ISSUE THREAD

**Issue by DiogoBatista** [react-hook-form/react-hook-form#984]
**Describe the bug**
when using the latest version of the library, 4.8.2. The `useFieldArray` seems to duplicate the fields when you remove all of the fields using the append function.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-f5z6l?fontsize=14&hidenavigation=1&theme=dark
2. Click on the "Delete" button in the input "useFieldArray"
3. Verify that there is no input visible
4. Click on the "Append" button below
5. Check that we have 2 fields showing up 

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-f5z6l?

**Expected behavior**
Upon clearing all the inputs with delete, the append should only populate with one field not two.

**Screenshots**
![image](https://user-images.githubusercontent.com/8352927/73941524-baffd980-48ed-11ea-9efd-27501d01df39.png)
![image](https://user-images.githubusercontent.com/8352927/73941535-bf2bf700-48ed-11ea-88bb-01a6d8174ac0.png)
![image](https://user-images.githubusercontent.com/8352927/73941579-cf43d680-48ed-11ea-9a8a-263771174a19.png)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: chrome
 - Version: 79.0.3945.130

**Additional context**
I noticed that this only happens in the 4.8.2 version If I downgrade to the 4.7.2, that is the one that is being used in the example in the documentation, everything is fine so it should be something that was introduced in the latest releases.

**Comment by bluebill1049** [comment]
looks like this issue is already solved on master.: https://codesandbox.io/s/react-hook-form-usefieldarray-fix-6w5iu

**Comment by bluebill1049** [comment]
fix will be released on the next patch

**Comment by bluebill1049** [comment]
thanks for report this issue, i am going to close this one as it will be patched in the next release. Feel free to verify with the CSB above and feedback welcome.

**Comment by DiogoBatista** [comment]
Awesome!! I verified and it's working!! 👏🙌 Thank you for the fast reply and continue with the nice work, love the tool!!

**Comment by bluebill1049** [comment]
thank you @DiogoBatista for the update. my pleasure
