### ISSUE TITLE
issue:  clearErrors type error with root.* keys

### ISSUE THREAD

**Issue by aksdevac** [react-hook-form/react-hook-form#9842]
### Version Number

7.43.0

### Codesandbox/Expo snack

NA

### Steps to reproduce

try calling method like `clearErrors('root')`

Here it is missing `root.${string}` in type. 
https://github.com/react-hook-form/react-hook-form/blob/af094a2a466b518c2fb0eb33d2e85380a95eaa01/src/types/form.ts#L473-L478 

### Expected behaviour

it should not give type error.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
NA
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Would like you send a PR to address that?
