### ISSUE TITLE
Allow setting of formState.isSubmitted, formState.isSubmitSuccessful

### ISSUE THREAD

**Issue by craig-o-curtis** [react-hook-form/react-hook-form#9844]
**Is your feature request related to a problem? Please describe.**
This is a continuation of [https://github.com/react-hook-form/react-hook-form/issues/2859](https://github.com/react-hook-form/react-hook-form/issues/2859). onSubmit automatically sets the `isSubmitted`, `isSubmitSuccessful`, but we need control over these.
Using v7.40.0

**Describe the solution you'd like**
We need a way to programmatically specify `formState.isSubmitted` and `formState.isSubmitSuccessful` if we have things like confirmation prompts and they are cancelled.

The `formState.isSubmitted` flag should also be optionally controlled - if we don't want it set to `true` if a user goes back to the form and continues filling it out.

**Describe alternatives you've considered**
In this [forked codepen](https://codesandbox.io/s/react-hook-form-handlesubmit-v6-forked-wvry6b?file=/src/index.jsx) I am able to set `formState.isSubmitSuccessful` for example, but this directly on the object, whereas we should have an exported `setFormState` method to set what we need.

**Comment by bluebill1049** [comment]
We should be able to have better control once the Form component's API is getting stable: 

```tsx
<Form
  onSubmit={() => {
    throw new Error('run time error') // isSubmitted or isSubmitSuccessful will be false
  }}
  reject={() => {
    // callback here
  }}
/>

```
