### ISSUE TITLE
issue: inconsistent values provided by useWatch and by Controller

### ISSUE THREAD

**Issue by iwannafly0** [react-hook-form/react-hook-form#9845]
### Version Number

7.41.0 (7.43.0 as well)

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-inconsistent-values-provided-by-usewatch-and-by-controller-qvnl5z?file=/src/index.js

### Steps to reproduce

1. Go to sandbox
2. Fill smth into text input
3. Choose another option in the select
4. Look at console logs

### Expected behaviour

Expecting value provided by useWatch and value provided by Controller to be the same

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
You are overlaying the field path, and I think you could build a controlled component wrap with a single controller.

```tsx
name="common"
name="common.value"
```

**Comment by iwannafly0** [comment]
I mean, the example provided is super simplified, my actual form has about 10 fields (and could be more) so wrapping everything in one controller will make an absolute mess.
Especially if you have some nested complicated subgroup of fields with kinda a similar structure when some fields could affect others ones.

And such an approach could make it very complicated or even impossible to make those nested components to be reusable and encapsulate their logic inside them.

**Comment by bluebill1049** [comment]
> Especially if you have some nested complicated subgroup of fields with kinda a similar structure when some fields could affect others ones.

That's how you structure your form fields and it's up to you, but the field path shouldn't or must not be overwritten as what you provided above, this would cause more issues along the line. Your root level and sub-level would easily become inconsistent if you do not merge the correct value to be updated.

**Comment by iwannafly0** [comment]
> but the field path shouldn't or must not be overwritten
I got your point.

If don't see it as an issue, please close the ticket.
But it's kinda disappointing that the only way to handle such cases is to build a monstrous top-level Controller. I believe it could be a better way. :)

Anyway, thank you for the great library!

**Comment by bluebill1049** [comment]
> But it's kinda disappointing that the only way to handle such cases is to build a monstrous top-level Controller. I believe it could be a better way. :)

Let me investigate the issue a bit more and will let you know if this can be addressed within the lib.

**Comment by bluebill1049** [comment]
After close investigation, this behaviour is by purpose

Check out this line:
https://github.com/react-hook-form/react-hook-form/blob/master/src/useController.ts#L62 

`useController` also uses `useWatch` except its prop set to exact, which it made so its re-render is isolated, I believe you can work around this issue with `setValue('common.value', 'valueToUpdate')`, this will indicate to hook form that the field is the exact match for the update. Hope this will resolve your issue.
