### ISSUE TITLE
After type to invalid input I get error when is page translated by google translator

### ISSUE THREAD

**Issue by Davidoseq** [react-hook-form/react-hook-form#985]
**Describe the bug**
**Translate page to another language by google translator** in chrome with use **register with validation with custom error message**. After click on submit with empty inputs which they are required, try type anything to the input and you got error.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-errors-with-google-translate-d3he7
2. Click on open in new window (https://prnt.sc/qygchd) 
3. Translate page by google to another language. (https://prnt.sc/qygfdc)
4. Don't fill inpust and click on Submit button and try type to input. I get error: _NotFoundError
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node._

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-errors-with-google-translate-d3he7

**Video**
https://streamable.com/n0p17

**Desktop (please complete the following information):**
Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by bluebill1049** [comment]
I don't have a clue for this one since the page is translated by google.

**Comment by ninooorendain** [comment]
Do we have solution on this I also have the same problem

**Comment by SE-SalamAQuran** [comment]
I also have the same problem, any solutions yet?
