### ISSUE TITLE
issue: 

### ISSUE THREAD

**Issue by KieraDOG** [react-hook-form/react-hook-form#9855]
### Version Number

7.41.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-get-started-forked-o0g47j?file=/src/index.js

### Steps to reproduce

1. go the codesandbox
2. only change the input with a single character
3. the input is ditry and is valid
4. the button is still disabled

if you look on this line which revert the sequence `formState.isDitry` and `formState.isValid`, and it works as expected...

### Expected behaviour

the button is enabled as the form is passing the validation and the input is dirty (with only 1 character changes)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
[`formState` ](https://react-hook-form.com/api/useform/formstate)uses the JS `Proxy` object for perfomance optimisation.

You need to "subscribe" to the states you want to watch before they "react" to changes.
