### ISSUE TITLE
issue: Not able to clear the value for custom number input field

### ISSUE THREAD

**Issue by ziishaned** [react-hook-form/react-hook-form#9861]
### Version Number

7.43.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/sweet-parm-lo24br

### Steps to reproduce

1. Click on the age input field
2. Select all text `Command + A`
3. Enter backspace to clear the value. The value will be cleared
4. Now lets input `30000` and try to clear the value you will end up with value `30` which was the default value.
5. You have to select the text twice in order to clear the value

![2023-02-03 at 13 17 12](https://user-images.githubusercontent.com/16267321/216560807-2949af75-d692-47fb-9379-42bfacc80322.gif)

### Expected behaviour

The custom number input field should be cleared at the first try but I have to perform the same action twice.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
hey, @ziishaned happy new year! It's been a while, I think this issue could be related to the controlled component with the number input. Would you like to wrap it with a Controller and see if this resolves the issue?

**Comment by ziishaned** [comment]
> hey, @ziishaned happy new year! It's been a while, I think this issue could be related to the controlled component with the number input. Would you like to wrap it with a `Controller` and see if this resolves the issue?

@bluebill1049 Happy New Year to you too! Wishing you a fantastic new year. I tried wrapping the input with the Controller, but unfortunately, it didn't work.

![2023-02-03 at 15 15 23](https://user-images.githubusercontent.com/16267321/216591648-bc2f39e1-d82f-4b05-a210-5d46fe36cf4c.gif)

```jsx
export function NumberInput(props: NumberInputProps) {
  const { name, control } = props;

  return (
    <FormControl>
      <FormLabel>Age</FormLabel>
      <Controller
        name={name}
        control={control}
        render={({ field: { value, onChange } }) => (
          <Input
            value={value}
            as={NumericFormat}
            thousandSeparator=","
            onValueChange={(data: NumberFormatValues) =>
              onChange(data.floatValue)
            }
          />
        )}
      />
    </FormControl>
  );
}
```

**Comment by bluebill1049** [comment]
Found the root cause: 

`onChange(isUndefined(data.floatValue) ? '' : data.floatValue)`

**Comment by ziishaned** [comment]
@bluebill1049 Thank you very much! it did the trick.

**Comment by bluebill1049** [comment]
Just FYI `undefined` is used internally to fallback to defaultValue, hence the issue occurred.
