### ISSUE TITLE
issue: Removing an item from array revalidates all items

### ISSUE THREAD

**Issue by marcospassos** [react-hook-form/react-hook-form#9868]
### Version Number

7.43.0/8-next.4

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-array-fields-with-validation-yup-forked-wjl0nd?file=/src/index.js

### Steps to reproduce

1. Click on "Remove friend"
2. See an error on all items

https://user-images.githubusercontent.com/943036/216793058-4a50ff1c-5b11-4f0d-8da0-44c790b75899.mov

### Expected behaviour

No revalidation on unrelated items.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marcospassos** [comment]
@bluebill1049, I don't think it's related to #9867. The problem is that revalidation at the array level triggers revalidation on all nested fields. This serious UX issue makes this library unusable for these cases. Imagine what happens on an array field with only two subfields. Adding or removing an item makes all these fields yell an error.

It affects any array field with validation rules at the array field level (like min, max).

**Comment by bluebill1049** [comment]
That's expected behaviour and the same issue you were reporting on the other issue, validation is returned by your schema and then returned to the field array.

**Comment by marcospassos** [comment]
This is not the point. 

If you look at the example I gave, the schema returns an error ("firstName" must not be empty) since the first item was added, as it should. However, RHF shows no errors at this point, which is expected. The unexpected behavior is that, only for the list, if an error appears on the parent level, it shows the errors for all nested items. For every new item, it revalidate and show errors for all others.

It has nothing to do with the schema itself but that the RHF behavior for the list is entirely different from how it behaves for objects, for example.

**Comment by bluebill1049** [comment]
Each action will return the field array level of error, react hook form is not possible to cherry-pick when and how to show those errors when each action is performed. If this is your UX requirement, you can consider combining it with other `formState` such as `touchedFields` or `dirtyFields`

- action performed
- revalidate the schema (you may be able to do a custom resolver here, to resolve your error, so meet your UX logic)
- pick up the errors by field array key
- return the errors

If that still does not meet your desired DX or UX, please consider using another library or perhaps rolling your own custom solution.
