### ISSUE TITLE
Typescript: The property 'message' doesn't exists in 'FieldError | FieldErrors<any>[]'

### ISSUE THREAD

**Issue by cargallo** [react-hook-form/react-hook-form#987]
**Describe the bug**

The property 'message' doesn't exists in 'FieldError | FieldErrors<any>[]'.
The property 'message' doesn't exists in type 'FieldErrors<any>[]'.ts(2339)

This happens in typescript when trying to access errors messages from Autocomplete component from yup validation schema

**Codesandbox link**

Look at line 48!!!

https://codesandbox.io/s/material-demo-o15mc

**Screenshots**

![image](https://user-images.githubusercontent.com/13320290/73969895-f94fc580-48fa-11ea-8f3f-2ae6054faf47.png)

**Comment by fabiodcorreia** [comment]
I also have the same problem, but if I do console.log(errors.name) the message property is there. I think it's just something with the typescript validation.

**Comment by bluebill1049** [comment]
when you have sometimes, can you please take a look @kotarella1110 🙏

**Comment by cargallo** [comment]
In the meantime a temporary workarround could be:

helperText={errors.multiple && (errors.multiple as any).message}

**Comment by fabiodcorreia** [comment]
Works for me, here is a smaller version.
```typescript
{(errors.nameInput as any)?.message}
```

**Comment by kotarella1110** [comment]
@fabiodcorreia How is this?

```ts
interface IServicio {
  multiple: unknown;
}
```

**Comment by fabiodcorreia** [comment]
I think that's for @cargallo, I my case I don't have that interface or Material UI :)

> @fabiodcorreia How is this?
> 
> ```diff
> interface IServicio {
> -  multiple: any[];
> +  multiple: unknown;
> }
> ```

**Comment by cargallo** [comment]
> @fabiodcorreia How is this?
> 
> ```diff
> interface IServicio {
> -  multiple: any[];
> +  multiple: unknown;
> }
> ```

@kotarella1110 That works, but I still think that there is a problem in the errors object handling in typescript, I had troubles with yup nested objects too. I used any[] to show that neither in that case the code was working, but it should be a custom object array.

**Comment by kotarella1110** [comment]
@bluebill1049 How should this be fixed? Do you have any suggestions?

**Comment by bluebill1049** [comment]
no worries @kotarella1110 i will take a closer look at this over the weekend.

**Comment by bluebill1049** [comment]
@cargallo did you updated the CSB? I don't see the error line now.

**Comment by cargallo** [comment]
Hi bluebill I simply updated the version of RHF. It doesn't appear anymore, do not now why, perhaps some change in new version made it work? However I just checked it and there is a strange behavior. Not related to this issue but I take this opportunity to let you know of it's existence. If you delete the "watch" in line 23, the form seems to not re-rendering when submitting. It does not show the error message! but putting the watch again makes it work, the watch is not used in the code I just put it because it wasn't showing the errors, so I though that using watch could do the trick

Back to the related issue, the typescript part of the library still has errors with yup nested objects. Today I reviewed the code of the types of the library because I believe that the problem is in the way that NestedDataObject<FormValues> is defined. But I did not completely understood how the library is treating errors. 

This is where I think that the problem resides: 

https://github.com/react-hook-form/react-hook-form/blob/master/src/types.ts#L115

**Comment by cargallo** [comment]
@bluebill1049 I realized that I made a little change in the code. Sorry! The change is that I defined multiple as unknown, but now I changed to any[] so you can test the issue. Now the error appears again!

```JSX
multiple: any[];
```

Here is the Sandbox to be used:  https://codesandbox.io/s/material-demo-wts5f

**Comment by bluebill1049** [comment]
thanks @cargallo i will take a look at it.

**Comment by bluebill1049** [comment]
i think the problem is because 
`multiple: any[];`

so the error message will have to be

`errors.multiple[0].message`

maybe using `unknown` is the work around here, unless anyone else have better suggestion or solution.

FYI @kotarella1110 @stramel

**Comment by cargallo** [comment]
I don't think so @bluebill1049, in fact the code of the library is working OK just as it is. If you access errors.multiple.message with (errors.multiple as any).message it works, so the message property is there where it has to be. The problem is that typescript definition of NestedDataObject is not reflecting what you are doing at "javascript" level.

**Comment by kotarella1110** [comment]
I understand what @cargallo say but this probrem is hard to fix in TypeScript.

**Comment by olup** [comment]
Have this too, `message` property or even `type` property is not properly types on errors fields

**Comment by cargallo** [comment]
@kotarella1110 could you explain to me the idea of NestDataObject so I can try to figure out a solution? I think that the idea is to retrieve FieldError or FieldError[] (I don't understand why retrieving FieldError[]). I think (if it is posible) that the idea has to be to retrieve FieldError only for basic types and Array of them. But I think that the actual problem is that it is hard to diferentiate between arrays of basic types from arrays of objects that need more iterations. It's hard for me to explain this in english, hope this has sense to you.

**Comment by stramel** [comment]
The underlying structure is correct however the typing for the errors object is not properly inferring the typing. I believe this is along the same line as #953 [point 2](https://github.com/react-hook-form/react-hook-form/issues/953#issuecomment-585047076) that I identified there. @bluebill1049 I'm going to mark this as a bug.

**Comment by stramel** [comment]
So a few different cases to cover here since we closed the other related tickets in favor of a single issue. 

These scenarios cause incorrect `errors` typing:

- any[]
- unknown
- object[]
- no typing passed

**Comment by barrymay** [comment]
Chiming in on this:

Changing IServicio to use unknown[] appears to improve the output, as it makes the Fields recognize they have a type.  The important difference between unknown and any is that unknown has greater recognition with type-safety.

interface IServicio {
  multiple: unknown[];
}
https://codesandbox.io/s/material-demo-uk2vi

When plugged in instead of any[] (too wide) or object (a narrow definition of simply {}) it appears to improve things, since unknown is still an array so it makes the condition type make the underlying types array-based as well.

My bigger issue here (and I'm new to the nested errors collection of RHF 4) is that I don't get what we're trying to achieve with it, and will it work properly with frameworks like yup.  Is it overcomplicating things?  Do you need more than one error per field?

**Comment by Motoxpro** [comment]
I'm not sure how to help fix this, but this is what I am doing at the moment. 

    {((errors?.password as unknown) as FieldError)?.message}

**Comment by cargallo** [comment]
I want to give some feedback about my research of this issue. As I commented few days ago, I think the problem is in the definition of NestedDataObject and the solution could be to do it like [the suggested type definition for JSON data](https://github.com/microsoft/TypeScript/issues/3496#issuecomment-128553540)
but I'm not sure of the scope of this since I think that FieldError must be redefined 
and I still can't assess the consequences of such change. I hope this can help someone else so that we can solve this issue. Reggards!

**Comment by kotarella1110** [comment]
My idea is to provide a utility type (such as `FormValue`) to define the value type of generic parameter (`FormValues`) passed to useForm.

utilty type:

```ts
declare const $Value: unique symbol;
export type FormValue<Value> = { [$Value]?: Value };

export type NestDataObject<FormValues> = {
  [Key in keyof FormValues]?: FormValues[Key] extends { [$Value]?: any }
    ? FieldError
    : FormValues[Key] extends any[]
    ? FieldErrors<FormValues[Key][number]>[]
    : FieldErrors<FormValues[Key]>
};
```

usage:

```ts
import { FormValue } from "react-hook-form";

interface IServicio {
  multiple: FormValue<any[]>;
}
```

simple demo is below: 
https://codesandbox.io/s/cranky-napier-ebmw6

Note: I only did as much fixing as was necessary.

**Comment by bluebill1049** [comment]
> My bigger issue here (and I'm new to the nested errors collection of RHF 4) is that I don't get what we're trying to achieve with it, and will it work properly with frameworks like yup. Is it overcomplicating things?

@barrymay Personally I prefer the flat error objects, but there are many ppl requests for errors object type support for nested object and array. This lead to this breaking change and it does make type more complicated.

Thanks a lot @kotarella1110 for your suggestion, ideally lib is more developer-friendly without the need of import external type for typing. 

and thanks for looking it up @cargallo. Unfortunately, I am stuck on this one, and need some TS expert to help this out :(

**Comment by anthonyferreol** [comment]
Still not working for array of strings like so :

```
{
  field: string[]
}
```

**Comment by bluebill1049** [comment]
FYI @kotarella1110 above.

**Comment by kotarella1110** [comment]
@anthonyferreol If the value of input is a premitive array such as `string[]`, you must use `any` or `any []`.

```ts
{
  field: any
}
// or
{
  field: any[]
}
```

**Comment by zeing** [comment]
> Still not working for arrays, for example strings like so :
> 
> ```
> {
>   field: string[]
> }
> ```

I am at this situation

**Comment by kotarella1110** [comment]
@zeing you can use `NestedValue` type.

```ts
import { NestedValue } from 'react-hook-form';

type FormValues = {
  field: NestedValue<string[]>
}
```

**Comment by bluebill1049** [comment]
👆🏻refer to the doc as well: https://react-hook-form.com/ts#NestedValue

**Comment by zeing** [comment]
Do you know how to create schema  If I create type via **YUP**


> @zeing you can use `NestedValue` type.
> 
> ```ts
> import { NestedValue } from 'react-hook-form';
> 
> type FormValues = {
>   field: NestedValue<string[]>
> }
> ```

**Comment by smaven** [comment]
The `append` method of the `useFieldArray` complains about `Type never[] is not assignable to type 'NestedValue<string[]>'`.

![image](https://user-images.githubusercontent.com/36948032/103240594-9338ba80-4972-11eb-968f-de6eaa0d9e14.png)

I'm guessing this has something to do with the nested fields not being unpacked?
Type Definition of the append function:
![image](https://user-images.githubusercontent.com/36948032/103240799-22de6900-4973-11eb-9bdc-23afa281aaa1.png)

**Comment by bluebill1049** [comment]
@smaven send  a pr please, we will take a look at it.

**Comment by nathanhannig** [comment]
why closed?

**Comment by Moshyfawn** [comment]
@nathanhannig, https://github.com/react-hook-form/react-hook-form/issues/8036#issuecomment-1070966732

**Comment by xiaotiandada** [comment]
in react-hook-form + class-validator

I "hide" error    (

```tsx
(formErrors?.screenshots as unknown as FieldError)?.message
```
