### ISSUE TITLE
issue: `dirtyFields` will have unexpected keys when modifying array

### ISSUE THREAD

**Issue by tu4mo** [react-hook-form/react-hook-form#9877]
### Version Number

7.43

### Codesandbox/Expo snack

https://codesandbox.io/s/useformstate-forked-1xyd5z?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/useformstate-forked-1xyd5z?file=/src/App.js
2. Click on `Remove`
3. `dirtyFields` contains `"firstName":{}`

### Expected behaviour

`dirtyFields` does not contain `"firstName":{}`

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
It's quite diffuclt to clean up those keys recursively especially when the field array is several levels deep without sacrificing huge performance lost, for now, `dirtyFields` would only be made to check if individual fields are dirty. such as `dirtyFields.test.deep.field`
