### ISSUE TITLE
issue: useFieldArray can miss changes made prior to its subscription effect firing

### ISSUE THREAD

**Issue by nathggns** [react-hook-form/react-hook-form#9878]
### Version Number

7.43

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-late-subscription-8t9qr5?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-late-subscription-8t9qr5?file=/src/App.tsx
2. Wait for the setTimeout to trigger (simulating a network request), which updates some state
3. See loading disappear, but the list of random numbers not appear 
4. Click "Add"
5. See 4 list items now, with the original 3 now appearing

### Expected behaviour

The initial 3 list items should appear once reset is called, and shouldn't be hidden until you click "Add". 

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nathggns** [comment]
This bug is caused by a timing issue. Because `reset` is called by `useLayoutEffect`, it is called before `useFieldArray` subscribes to changes (in a `useEffect`). This could be fixed by changing `useLayoutEffect` to `useEffect`, but you could still imagine a timing issue where effects fire in the wrong order for whatever reason. This may be fixed more reliably by calling the useFieldArray subscription callback once at subscription time, just to ensure any changes to the value between when `useState` is called and when the `useEffect` which is subscribing is called are taken into account.

**Comment by nathggns** [comment]
You may also watch to update `useSubscribe` to `useLayoutEffect`, to ensure it doesn't miss changes made in `useLayoutEffect` within the same component which calls `useFieldArray`

**Comment by nathggns** [comment]
This patch fixed the version of the bug in our project https://github.com/hashintel/hash/pull/2012/files#diff-8ca52b8bf1e8eee20788ca2365eead4bb36dee228d8f0c991bfaf65e65aab52a

**Comment by bluebill1049** [comment]
We can consider switching from `useEffect` to `useLayoutEffect` as we don't need having the concern about running stuff on the server perhaps not those additional code: https://github.com/hashintel/hash/pull/2012/files#diff-8ca52b8bf1e8eee20788ca2365eead4bb36dee228d8f0c991bfaf65e65aab52aR18-R24

**Comment by bluebill1049** [comment]
I am going to park this into feature board for now.
