### ISSUE TITLE
useFieldArray hook Yup array validation not invalidating Form

### ISSUE THREAD

**Issue by diogo-batista** [react-hook-form/react-hook-form#988]
**Describe the bug**
When using the useFieldArray hook alongside with Yup array validation the form is always valid although the validation specifies otherwise.

**To Reproduce**
1. Go to the codesandbox link (https://codesandbox.io/s/react-hook-form-usefieldarray-uhoxs)
2. Toggle the console
3. Delete the initial Field
4. The form is now valid when Yup validation specifies min of 1 record in the array

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-uhoxs

**Expected behavior**
uppon building a validation such as 
```
const formSchema = {
  name: yup.string().required("form.required_message")
};

const fieldsSchema = yup.object().shape({
  test: yup
    .array()
    .of(yup.object().shape(formSchema))
    .required("Must have fields")
    .min(1, "Minimum of 1 field")
});
```
If the form doesn't have at least one object inside test array it should return `formState.isValid = false`

**Screenshots**
![image](https://user-images.githubusercontent.com/59829922/73974882-7f810180-4925-11ea-8f32-2e4275dcf051.png)
![image](https://user-images.githubusercontent.com/59829922/73974908-8b6cc380-4925-11ea-8e11-d6e788b9c934.png)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser chrome
 - Version 79.0.3945.130
- react-hook-form version: v4.8.2

**Additional context**
Im not sure why this is happening, as you can see im using the combination of  `mode: "onChange"` in the `useForm` hook to actually trigger the validation. Maybe I'm using it wrongly or even constructing the yup badly, but it seemed a bug in the yup validation functionality. Let me know if there is a way or if im actually setting it up wrongly, help would be much appreciated. Thank you.
Keep the nice work :)

**Comment by bluebill1049** [comment]
thanks very much for the issue report :)

here is a fixed version, if you can verify.

https://codesandbox.io/s/react-hook-form-usefieldarray-c82kl

**Comment by DiogoBatista** [comment]
Awesome!! I verified and it's working!! 👏🙌 Thank you for the fast reply and continue with the nice work, love the tool!!

**Comment by felipecorredor** [comment]
**React Hook Form v7**

** yup with dynamic fields react hook form - useFieldArray**

`import { string, object, array } from 'yup';`

```
const formSchema = {
  name: string().required("Name is required").min(7, 'Message'),
};

const schema = object({
  yourUseField: array()
  .of(object().shape(formSchema))
});

export default schema;
```

```
  const methods = useForm({
    resolver: yupResolver(schema),
  });
```
