### ISSUE TITLE
Allow Controller components to be disabled

### ISSUE THREAD

**Issue by cjsilva-umich** [react-hook-form/react-hook-form#9880]
**Is your feature request related to a problem? Please describe.**
Would like to be able to disable a Controller component.

**Describe the solution you'd like**
Controller components should accept a "disabled" prop

**Additional context**
#2826 [Here is a link to an issue](https://github.com/react-hook-form/react-hook-form/issues/2826) that was opened about this subject but was closed and locked even though there was interest in pursuing.

If this has been incorporated, I can't find any documentation or PR's related to it.

**Comment by AmitNeuhaus** [comment]
Hey couldn't understand, is there any news or workaround recommendations about this feature? 
How can I display the value of input without submitting it using useController?

*Without filtering on the submit handler?
