### ISSUE TITLE
disabled useController

### ISSUE THREAD

**Issue by AmitNeuhaus** [react-hook-form/react-hook-form#9883]
Possible duplicate of 
[#2826](https://github.com/react-hook-form/react-hook-form/issues/2826)
[#2655](https://github.com/react-hook-form/react-hook-form/issues/2655)

**Describe the solution you'd like**
Trying to find a way to avoid input with UseController to be submitted even if mounted.
Similarly to the "disabled" rule for the register api as in uncontrolled inputs. 

**Describe alternatives you've considered**
 1. Setting the form as shouldUnregister:True (or unregister in useEffect) and render an input component without connecting it to useForm using control. 
- this seems like a patch. it is removing the ability to save the value on undisabling again.
 
 2. Setting` rule: disabled` on the useController  
 - this currently doesn't behave like register disabled. it is making the input's as undefined but still appear in the submitting data.
 - currently rule:disabled on useController causing ts error.
 
3. as @bluebill1049 mentioned, this should be handled in the Controlled component itself' but i don't understand how without using (1). 
 
Can you explain if there is another option, and is this issue #2826 is closed or is on upvote mode? 
i couldn't find it anywhere. and didn't understand where i can comment elsewhere.
Thank you.

**Comment by bluebill1049** [comment]
The original feature request has been unlocked, we will get to it.
