### ISSUE TITLE
issue: Possible race condition between reset and resetField

### ISSUE THREAD

**Issue by ConnorLanglois** [react-hook-form/react-hook-form#9888]
### Version Number

7.43.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-reset-resetfield-race-condition-grxhn8?file=/src/index.js

### Steps to reproduce

1. Go to the [codesandbox link](https://codesandbox.io/s/react-hook-form-reset-resetfield-race-condition-grxhn8?file=/src/index.js)
2. See how code has a form with one input field `query`
3. Also see how `useEffect` is calling `reset` to set the text field to `test 1`, and then immediately after calls `resetField` to set the text field to `test 2`.
4. Watch how the input field is not actually updated to `test 2`, but instead its final state is `test 1`.

If you comment out the `reset` function call, the `resetField` works as expected.

I've also added a commented code block with `resetField` being run inside a `setTimeout`. If you uncomment it, it fixes the issue here, leading me to believe this is a race condition.

My guess here is that `reset` is doing something asynchronously and happens to actually set field values after some X amount of time, but by then the `resetField` already completed, and so it overwrites what `resetField` did.

### Expected behaviour

Calling `resetField` after `reset` should result in the final state of the text field being `test 2`.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ConnorLanglois** [comment]
Just realized that you don't even need 1000 ms for the setTimeout, just doing 0 will work. So perhaps it is something to do with JS event loop ordering, if react-hook-form itself is using functions like setTimeout and setImmediate or some other async thing is happening.

**Comment by bluebill1049** [comment]
hmmm i think this is troublesome when you combine `reset` and `resetField` together, what's the use case? why calling reset is not enough? in fact, reset will remove all input references, and calling `resetField` again is almost incorrect.

**Comment by ConnorLanglois** [comment]
When query params in url change, I need to reset all fields to those new query param values. So I use `reset` for that. But a couple of the query params I need to reach out to server to get string value, so I am awaiting the server response and then using `resetField` for those. Sometimes, the server request will finish quickly enough that whatever it called `resetField` with is then somehow overwritten by the previously called `reset` (due to race condition?)

**Comment by bluebill1049** [comment]
> and also clear isSubmitted

maybe you can leverage `isSubmitSuccessful`? It's updated until the promise is resolved.

> Just wanted to bring this issue up since it seems like undocumented behavior / violates principle of least surprise

Yes, we can add a note to that.
