### ISSUE TITLE
why initial value is not set in select ? 

### ISSUE THREAD

**Issue by naveennsit** [react-hook-form/react-hook-form#989]
Hi
I am trying to set initial value of `Autocomplete` select (Material UI) .But it is not set why ?

here is my code
https://codesandbox.io/s/react-hook-form-get-started-v24jk

const { register, handleSubmit, setValue } = useForm({
    defaultValues: {
      resolutionCode: 1993
    }
  });

  React.useEffect(() => {
    register({ name: "resolutionCode" });
  });
  const onSubmit = data => {
    console.log(data);
  };

**Comment by bluebill1049** [comment]
you are using custom register, which RHF doesn't hold any reference of the input. try to use Controller for external component https://react-hook-form.com/api#Controller

**Comment by naveennsit** [comment]
it would be great if you change my codesandbox .I am new in react and hook-form.I will try

**Comment by naveennsit** [comment]
https://codesandbox.io/s/react-hook-form-rhfinput-mi22f

**Comment by naveennsit** [comment]
currently giving error

**Comment by bluebill1049** [comment]
please ask questions at our spectrum channel and try to search for similar questions as well, chances are someone already have similar questions: 

check out this link below, i think it's what you after.

https://spectrum.chat/react-hook-form/help/how-to-connect-to-autocomplete-in-material-ui~e8c40a4a-fee0-4d0b-8651-44111f973d9c
