### ISSUE TITLE
issue: Async validate, fieldState.isValidating is always undefined

### ISSUE THREAD

**Issue by zfha** [react-hook-form/react-hook-form#9897]
### Version Number

7.0.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-get-started-forked-rwfn6s?file=/src/index.js

### Steps to reproduce

input name

### Expected behaviour

Validate is async, so we support fieldState.isValidating is true, but is undefined.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
```tsx
export type ControllerFieldState = {
  invalid: boolean;
  isTouched: boolean;
  isDirty: boolean;
  error?: FieldError;
};
```

**Comment by zfha** [comment]
> 
tks， how to know field validating state?

**Comment by bluebill1049** [comment]
yes, at this current scope.
