### ISSUE TITLE
issue: `useFieldArray` has errors during validation with empty array on re-submit, but empty errors object

### ISSUE THREAD

**Issue by wbobeirne** [react-hook-form/react-hook-form#9902]
### Version Number

7.41.0

### Codesandbox/Expo snack

See #9429

### Steps to reproduce

I'm seeing an issue identical to #9429 on people who are embedding a form on Squarespace sites. I have confirmed that the issue seems to happen on any Squarespace site. Unfortunately @sofianegargouri didn't say which library he removed to fix the issue, but given that this issue seems to happen with Squarespace's core set of scripts, this seems like something worth investigating more thoroughly as I imagine it'll happen to a good number of folks.

Sorry for the poor issue information, I would have liked to comment on the original issue but since it's locked I'm opening a fresh one. I'll continue to investigate and see if I can narrow down which library is conflicting here, but ideally `useFieldArray` wouldn't be affected by any external scripts at all.

### Expected behaviour

I would expect forms with no validation errors to be valid. When logging the validation errors, I get the following:

<img width="246" alt="Screen Shot 2023-02-09 at 1 00 56 PM" src="https://user-images.githubusercontent.com/649992/217918141-e502906f-b5e7-4c30-8e38-d9fec054edc4.png">

There's no missing output there, the array is just empty. This is identical to if you do
```ts
const errors = new Array()
errors.length = 1
console.log(errors) // [empty]
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wbobeirne** [comment]
I added a handler to the error case of `handleSubmit` that calls `clearErrors()` and re-submits to clear out the `[empty]` array and that's fixing my issue for now. I'll keep digging in to see if I can find the root cause. That code looks something like this:
```ts
const methods = useForm();
const handleSubmit = (redirectPath: string, retry = false) => {
  return methods.handleSubmit(
    (data) => {
      // regular submit case...
    },
    (errors, ev) => {
      // Handle weird react-hook-form bug where error arrays can be empty
      const { participants: participantsErrors } = errors;
      if (
        !retry &&
        Array.isArray(participantsErrors) &&
        !participantsErrors.find((err) => !!err)
      ) {
        methods.clearErrors();
        handleSubmit(redirectPath, true)(ev);
      }
    },
  );
};
```
not a generic solution, just wanted to share what fixed my case

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848
