### ISSUE TITLE
issue: `watch`'s typing does not match the actual value when using schema-based validation `transform` methods

### ISSUE THREAD

**Issue by bradenbiz** [react-hook-form/react-hook-form#9903]
### Version Number

7.43.0

### Codesandbox/Expo snack

https://codesandbox.io/s/damp-star-627umg?file=/src/App.tsx

### Steps to reproduce

1. Go to `App.tsx`
2. Hover over `watchMathNotes`
3. Notice that its type is 
`{
    noteText: string;
}[]`
because of the `.transform()` _Zod_ method in `notesSchema`
4. Open the **Console**.
5. Click inside the `textarea` in the form and start entering values.
6. Notice that the output of the `console.log` on line `51` is a string.
7. Notice that the counter in the form of "_ Math notes" is tracking the length of the entered string.

### Expected behaviour

Since the type of `watchMathNotes` indicates that it is an array of objects, I would expect the output of that value would match that, rather than the raw value of the input.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Runtime transformation is not covered in the current scope and duplicated issue as the following: https://github.com/react-hook-form/react-hook-form/issues/9600 however, we are looking for a way to potential solve it.
