### ISSUE TITLE
issue: AsyncDefaultValues resolved type differs from DefaultValues type

### ISSUE THREAD

**Issue by masnen** [react-hook-form/react-hook-form#9915]
### Version Number

7.43.1

### Codesandbox/Expo snack

https://codesandbox.io/s/runtime-tree-pm42ft?file=/src/App.tsx

### Steps to reproduce

1. Go to [codesandbox](https://codesandbox.io/s/runtime-tree-pm42ft?file=/src/App.tsx)
2. Open `App.tsx`
3. See `TSError` when loading `defaultValues` asynchronously, even if it resolves to same object (`defaultEntity`)

### Expected behaviour

That `AsyncDefaultValues` and `DefaultValues` accept the same resolved type. Could be fixed by having `AsyncDefaultValues` also wrap the `TFieldValues` with the `DeepPartial` utility type.

### Relevant log output

```shell
Type '() => Promise<{ id?: number | undefined; name?: string | undefined; }>' has no properties in common with type '{ id?: number | undefined; name?: string | undefined; }'.ts(2559)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
We want to move away from deep partial, as this creates a lot of nosy and unexpected issues over the year.  Is it possible for you to provide full default values instead of partial?

**Comment by masnen** [comment]
> We want to move away from deep partial, as this creates a lot of nosy and unexpected issues over the year. Is it possible for you to provide full default values instead of partial?

Yes, that would be possible. Thanks for the clarification!

**Comment by bluebill1049** [comment]
Thanks for understanding, I think overall we want our DX to be better, avoiding deep partial would help a lot of developers to reduce the confusion that it may introduce in certain use cases.
