### ISSUE TITLE
Don't use DeepPartial for the value parameter of WatchObserver

### ISSUE THREAD

**Issue by angryzor** [react-hook-form/react-hook-form#9919]
**Is your feature request related to a problem? Please describe.**
Currently when using the callback version of the `watch` function in TypeScript, the `value` parameter of this callback is defined as `DeepPartial<TFieldValues>`: https://github.com/react-hook-form/react-hook-form/blob/47537f2c44af639b3e08fbec1e602f1d27cc2b4b/src/types/form.ts#L772

I believe this is in error, as the callback always recieves the full form values object:

When looking at the definition of the `watch` function, it can be seen that it calls `_getWatch` with 2 parameters: https://github.com/react-hook-form/react-hook-form/blob/47537f2c44af639b3e08fbec1e602f1d27cc2b4b/src/logic/createFormControl.ts#L878

This function will then call `generateWatchOutput` with `undefined` as its first parameter: https://github.com/react-hook-form/react-hook-form/blob/47537f2c44af639b3e08fbec1e602f1d27cc2b4b/src/logic/createFormControl.ts#L490

Which according to the definition of `generateWatchOutput` will always return the full `formValues` (there also typed as `FieldValues`): https://github.com/react-hook-form/react-hook-form/blob/47537f2c44af639b3e08fbec1e602f1d27cc2b4b/src/logic/generateWatchOutput.ts

This (imo) incorrect typing constantly causes me trouble when working with the value provided by the `WatchObserver` callback, where I have to cast the incoming object back to the original (un-DeepPartial'ed) `FieldValues` type, even though it is actually always sending the full `FieldValues` type. Even when the fields haven't been touched yet it sends an empty string for text fields or null for radio fields.

**Describe the solution you'd like**
I would like for the type of the `value` parameter of `WatchObserver` to be changed to `TFieldValues`.

**Describe alternatives you've considered**
Writing casts everywhere in my own codebase.

**Additional context**

**Comment by bluebill1049** [comment]
Yes, in fact, we want to move away from deepPartail (https://github.com/react-hook-form/react-hook-form/issues/9915)

**Comment by bluebill1049** [comment]
I am moving to pending, but this would most likely be the next breaking change (the next major version).
