### ISSUE TITLE
Should setValue accept a null value, or should there be an unsetValue?

### ISSUE THREAD

**Issue by rsslldnphy** [react-hook-form/react-hook-form#992]
**Describe the question?**

I need to be able to clear the value of a controlled input, but typescript complains if I try to pass `null` or `undefined` as a value to `setValue`, and there doesn't appear to be an equivalent `unsetValue` function. Working around the typescript complaint using `any` seems to work fine, so I suspect all that needs to happen is to make `value` a nullable argument here: https://github.com/react-hook-form/react-hook-form/blob/41444acf961590186d94f098aba8495e5b0103a6/src/types.ts#L214-L218

And optionally add an `unsetValue` helper function too. Happy to put a pull request together if so.

**To Reproduce**

<img width="231" alt="image" src="https://user-images.githubusercontent.com/1231200/74032520-10022500-49ac-11ea-9c82-34ea4e9e7ca3.png">

**Workaround**

<img width="299" alt="image" src="https://user-images.githubusercontent.com/1231200/74032559-2314f500-49ac-11ea-88ca-256682ef7014.png">

I'm not sure how to get typescript errors showing in code sandbox so hopefully the above is enough to make sense. I'm calling `useForm` with a type parameter where the field i'm trying to set has a type that looks like this: `name?: string | null`.

Thanks!

**Comment by bluebill1049** [comment]
personally I don't think we need another API to set the value to `null/undefined`, the reason I didn't add null/undefined is that the behavior of native input, but I think it makes sense for the external controlled component to support null/undefined. feel free to send a PR, if you got time too.
