### ISSUE TITLE
Accept an isSubmitting predicate in useForm

### ISSUE THREAD

**Issue by iambryanhaney** [react-hook-form/react-hook-form#9927]
**Is your feature request related to a problem? Please describe.**

**The problem source:**
- When submitting with an async `onValid`, RHF's `formState.isSubmitting` is tied to the `onValid` promise settling.
- For a synchronous `onValid`, isSubmitting has no such promise and will be false at the end of the event loop.

**The problem context:**
- React Query has two forms of mutations - `mutate` and `mutateAsync`. The latter, `mutateAsync` throws on data errors and thus requires boilerplate error handling:

```tsx
const createPost = useMutation({ ... });
const form = useForm{( ... });

const handleSubmit = form.handleSubmit(async (data) => {
  try {
    const post = createPost.mutateAsync(data);
    console.log('created post:', post);
  } catch (err) {
    if (axios.isAxiosError(err)) {
      // The error is network / response related; it will be available on
      // createPost.error on the next render. This is a noop.
      return;
    }
    
    // This must be an actual JS error; re-throw
    throw err;
  }
});

<input disabled={form.isSubmitting} type="submit" />      
```

The synchronous `mutate` swallows response errors internally, eliminating the try/catch boilerplate. However, that comes with the price of RHF's `isSubmitting` no longer being a valid source of truth.

```tsx
const createPost = useMutation({ ... });
const form = useForm{( ... });

const handleSubmit = form.handleSubmit((data) => {
  createPost.mutate(data, {
    onSuccess: (post) => {
      console.log('created post:', post);      
    },
  }); 

<input disabled={createPost.isLoading} type="submit" />      
```

That behavior isn't problematic in a trivial example, but it becomes a problem when trying to compose with smarter components:

```tsx
const SubmitButton = (control) => {
  const { isSubmitting } = useFormState({ control });
  // ^ this is no longer a dependable source of truth 
  //    with synchronous submission

  return <input disabled={isSubmitting} type="submit" />;
};
```

**Describe the solution you'd like**
I would like `useForm` to accept an `isSubmitting` predicate that is OR'd with the internal `isSubmitting` logic.

```tsx
const createPost = useMutation({ ... });

const form = useForm{(
  isSubmitting: createPost.isLoading,
});

const handleSubmit = form.handleSubmit((data) => {
  createPost.mutate(data, {
    onSuccess: (post) => {
      console.log('created post:', post);
    }
  });
});

// SubmitButton.tsx
const SubmitButton = (control) => {
  const { isSubmitting } = useFormState({ control });
  // ^ ✅  takes the predicate into account
  return <input disabled={isSubmitting} type="submit" />;
};
```

**Describe alternatives you've considered**
Manually passing the `isSubmitting` predicate to each custom field component, themselves OR'ing RHF's `formState.isSubmitting` with the source of truth. This is unwieldy and would be problematic for components / effects relying on RHF's various submission cycle data.

**Comment by bluebill1049** [comment]
thanks for the feature request, moving to the project board for pending request.
