### ISSUE TITLE
issue: when append the item in usefieldarray   shouldDirty: false is not working

### ISSUE THREAD

**Issue by NarenderDhamarlapally** [react-hook-form/react-hook-form#9928]
### Version Number

7.41.5

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-kij8qg?file=/src/index.tsx:1899-1919

### Expected behaviour

1.go to sandbox
2.click on append button 
3.see the console .....dirtyFields are true.
4.but i want dirty fields are false when append

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
we don't have a such prop.
