### ISSUE TITLE
issue: submit triggers both forms on same page

### ISSUE THREAD

**Issue by markwoon** [react-hook-form/react-hook-form#9931]
### Version Number

7.43.1

### Codesandbox/Expo snack

https://codesandbox.io/s/rhf-2-forms-fgvi4d

### Steps to reproduce

I have a case where I open a modal form in the middle of the primary form.  When I submit the modal form, I'm seeing that the primary form also gets submitted.

To reproduce:

1. Go to https://codesandbox.io/s/rhf-2-forms-fgvi4d
2. Click on "open form"
3. Click on "submit modal"
4. Check console

Notice that both form1 and form2 were submitted when submitting modal form (form2).

Is there a way to prevent this behavior?

### Expected behaviour

Only form2 should be submitted.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Thanks for the issue report, but this is not a react hook form related issue.
