### ISSUE TITLE
issue: dirty fields not cleaned properly after being removed from useFieldArray

### ISSUE THREAD

**Issue by Hodosov** [react-hook-form/react-hook-form#9932]
### Version Number

7.43.1

### Codesandbox/Expo snack

https://codesandbox.io/s/serene-swirles-b87rtw?file=/src/App.js

### Steps to reproduce

1. append field
2. remove field
3. inspect console

### Expected behaviour

dirtyFields must be an empty object, but it contains arrayField name

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
The current approach is probably the most efficient way of doing field array dirty fields, by just simply marking dirty ones as `true` or `false`. In order, to clean and remove all the nodes within the field array it would require more recursion within the function which is going to take much more runtime consumption as the field array gets deeper. At this stage, I am not planning to go in that direction just yet: https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/getDirtyFields.ts however, happy to see if anyone else has better way without impact too much of the perf and bundle size.

**Comment by Hodosov** [comment]
Thanks for the quick response and your time. After experimenting with the versions, I found that this behavior appeared after version 7.20. And in the example that I attached, after adding and deleting the field and manually setting the default value, the state returns to its original form. And I'm sorry for my English, I'm just learning

**Comment by vladly** [comment]
I have the same problem...
Perhaps this change has affected the current behavior: https://github.com/react-hook-form/react-hook-form/pull/9156/files#diff-97693b2fde4994ca4d0fa7075b33313bdb23155006399958b9c703d699bb93b4

**Comment by bluebill1049** [comment]
What issue has this caused? I am happy to revert it back.

**Comment by Hodosov** [comment]
We are using arrayFields and one field is rendered initially. In version 7.19.5, if you add another field and then delete it, the formState.dirtyFields object will be empty. And in version 7.43.1, the formState.dirtyFields object will contain the key of the first field

7.19.5: https://codesandbox.io/s/react-hook-form-7-19-5-jlwktt?file=/src/App.js

7.43.1: https://codesandbox.io/s/react-hook-form-7-43-1-qk4uxs?file=/src/App.js

**Comment by Hodosov** [comment]
Did you look at the examples?

**Comment by bluebill1049** [comment]
@Hodosov i will revert the change soon.

**Comment by omer-shlifka** [comment]
Hi,
I noticed another side effect of this issue:
If I `setValue` for some field (not the array field), the field will get dirty as a result of any operation on an array field such as replace, append and remove.

Please see these code sandboxes (I based them on @Hodosov 's, thanks !)
7.19.5: https://codesandbox.io/s/react-hook-form-7-43-1-forked-chn8sd?file=/src/App.js

7.43.1: https://codesandbox.io/s/react-hook-form-7-19-5-forked-25eow8?file=/src/App.js

(click the "foo=lalala" and then on the "append" buttons, you will see `"foo": true` in the dirty fields)
