### ISSUE TITLE
issue: formState.isLoading always returns true

### ISSUE THREAD

**Issue by crashtech** [react-hook-form/react-hook-form#9934]
### Version Number

7.43.1

### Codesandbox/Expo snack

https://codesandbox.io/s/nice-gould-tzmvfo?file=/src/App.js

### Steps to reproduce

1. Just load the page
2. Using `FormProvider` makes `isLoading` always return true
3. Even trying to override using `<FormProvider {...hook} formState={{ ...hook.formState, isLoading: false }}>` doesn't work

### Expected behaviour

The default value for `isLoading` should be false, especially if `defaultValues` hasn't been provided, or if it hasn't been assigned to a Promise.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Your sandbox link contains the default RHF template; no reproduction. Please update your sandbox with the reproduction code

**Comment by crashtech** [comment]
Done!

**Comment by Moshyfawn** [comment]
I'm a bit rusty with how the change to the `formState` due to the new async `defaultvalues`, but there's something going with [how the default `isLoading: true`](https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/createFormControl.ts#L1231) and it's never handled if `defaultValues` are not async.

@bluebill1049, I might need your help on this one

**Comment by bluebill1049** [comment]
thanks @Moshyfawn i will look into this one.

**Comment by bluebill1049** [comment]
@crashtech If you are not using async defaultValues, what's the use case for subscribing to `isLoding`?

**Comment by Moshyfawn** [comment]
> @crashtech If you are not using async defaultValues, what's the use case for subscribing to `isLoding`?

That's a good question, actually. I guess, it feels like `isSubmitting`?

**Comment by bluebill1049** [comment]
Yea, if you are providing static `defaultValues`, then you don't need `isLoading`, and we can save the extra byte in the lib to skip the logic check.

**Comment by crashtech** [comment]
I'm connecting react hook forms with Semantic UI, so I'm forwarding this prop to the UI component. It should be consistent, regardless of using asynchronous default values.

Plus, a form here doesn't have default values, but select options are loaded asynchronously.

**Comment by Moshyfawn** [comment]
> Plus, a form here doesn't have default values, but select options are loaded asynchronously.

Select options loading don't have anything to do with `isLoading` unless they're a part of `defaultValues`

**Comment by crashtech** [comment]
Well, I assume "the form is loading if it can't be used yet". But regardless the reason, it should be undefined, or false at least.

The state is wrong, regardless of the motivation about using it.

**Comment by bluebill1049** [comment]
I think this argument is going in a loop, the point is you don't need isLoading in the first place, whether we return the correct state for your UI or not is our responsibility. Yes, we can fix that, but you shouldn't use that in the first place. So I would suggest fixing your app logic first, while we patch this later on.

**Comment by bluebill1049** [comment]
> The idea is to use the state to disable inputs while options are still loading.

But you are not using async `defaultValues`, so the loading is not the valid usecase.

**Comment by crashtech** [comment]
So you should mention that is loading is a exclusive prop when using async default values. Or even rename it to make it clear that is not the form that is loading, is just the default props.

In order to add an external support to that, I would have to add an exclusive provider just so it can be captured down the tree.

Not even the override on the FormProvider works.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/documentation/commit/132a5ec86541d2db797782a13932cc82e78c8a21
