### ISSUE TITLE
[control] incompatibility of specified type and expected 

### ISSUE THREAD

**Issue by Freiii21** [react-hook-form/react-hook-form#9943]
### Version Number

7.43.1

### Codesandbox/Expo snack

https://codesandbox.io/s/kind-cray-fliuni?file=/src/ChildComponent.tsx

### Steps to reproduce

1. Open the "ChildComponent" in the Codesandbox
2. See the typescript error for the "control" property of the "Controller":

_Type 'Control<FormValues, any>' is not assignable to type 'Control<FieldValues, any>'.
The types of 'options.resolver' are incompatible between these types.
Type 'Resolver<FormValues, any>' is not assignable to type 'Resolver<FieldValues, any>'._
![image](https://user-images.githubusercontent.com/80419645/219142940-e6e77661-753e-4a78-ac01-4ee7f89a420b.png)

### Expected behaviour

**Expected:** There is no typescript error.

**Additional information:**
There is no typescript error in the versions 7.37.0 - 7.41.5.
But starting from version 7.42.0, the described problem occurred, which also manifests itself in the latest released version 7.43.1.

**P.S.**: if you set "control: Control<any'>" in the ChildComponent props, then the error disappeared, but this detracts from the value of the typescript.
**P.P.S:** if you remove property "rules" from the Controller, then the error will also disappear, but the validation is necessary.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
please update your csb to reflect the issue.

**Comment by Freiii21** [comment]
> please update your csb to reflect the issue.

I guess csb doesn't display all the errors that are in the real IDE...
But when in my IDE, without changing the components, I just change the versions of the library - the problem appears and disappears, depending on the versions indicated in the bug. 

**P.S.:** In the csb, I provided the most simplified example of using the library, which shows the problem.

**Comment by Freiii21** [comment]
Hi @bluebill1049 , I found the reason for which the error was not reproduced in the csb. It was in the "strict" option in the tsconfig.json, the value must be "false" for the error to be reproduced. Now the error can be seen in csb.

**Comment by bluebill1049** [comment]
Please turn on strict, without breaks infer type with `validate` function.

**Comment by DrewLandgraveCbsi** [comment]
I have strict on and I am getting the same error
