### ISSUE TITLE
Add Vertical Offset when called setFocus('textinputField')

### ISSUE THREAD

**Issue by Sumit2202** [react-hook-form/react-hook-form#9944]
**Is your feature request related to a problem? Please describe.**
My use case is to focus on the first field with an error on click of submit button, setFocus works and I am able to get the scroll to that particular field along with focus to work. The only problem is since I am building a mobile app with react native, I have field Name and a text input field in 2 seperate rows, so Field Name is on top of TextInputField, now when the scrolling happens since the ref is passed to text input component it only scrolls up until that, at this point the user is not able to see the actual field Name to know what exactly to fill in this field, and they have to scroll up which disables the focus and now they have to click again for keyboard to appear and start filling it.
If setFocusOptions would have vertical offset which we could pass, then the setFocus would scroll according to the offset, bringing both the field Name and input field in view.

**Comment by bluebill1049** [comment]
thanks for your feature request, moving into pending requests for upvotes in the project board.
