### ISSUE TITLE
issue: Submission state no longer reset on handleSubmit error.

### ISSUE THREAD

**Issue by adriantrunzo** [react-hook-form/react-hook-form#9945]
### Version Number

7.43.1

### Codesandbox/Expo snack

https://codesandbox.io/s/submit-form-state-tef0l3?file=/src/App.tsx

### Steps to reproduce

The 7.42.0 release introduced a regression by [removing a try/catch/finally block](https://github.com/react-hook-form/react-hook-form/pull/9603/files#diff-5a85c1643c71f45e050ce584d7c0db2bdf2e56f8a7dae86d74fedf01be2d2cabL1065) in the definition of `handleSubmit`. The call to `_subjects.state.next` in the finally block ensured that the form submission state (eg `isSubmitting` etc) was reset if the `onValid` handler encountered an error. Starting in 7.42.0, if the `onValid` handler throws an error, such as from a bad API request, the form incorrectly remains in the submitting state and does not update `isSubmitting`, `submitCount`, etc.

To reproduce, take a look at the attached CodeSandbox:
1. Verify that the text `isSubmitting: false, submitCount: 0` appears above the input. This shows the initial form state.
2. Click the submit button.
3. You should see the form state text above the input change to `isSubmitting: true, submitCount: 0`.
4. Wait for the error to be thrown/promise rejected.
5. Verify that the submit button remains disabled (because `isSubmitting` isn't reset to `false`).
6. Verify that the form state text continues to show `isSubmitting: true, submitCount: 0`.

### Expected behaviour

The form state should be updated no matter if the `onValid` handler throws an error or not. If you fork the CodeSandbox and change the installed version of RHF to 7.41.5, you will see the correct behavior: `isSubmitting` is updated to false, `submitCount` incremented, and the submit button no longer disabled.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Expected behaviour from #9688.

Instead of swallowing user-land errors like promise rejections, RHF let's you handle your errors now.

**Comment by Moshyfawn** [comment]
@bluebill1049 people seem to be reporting this one quite a bit 🤔

**Comment by Moshyfawn** [comment]
The way to handle promise rejections: https://github.com/react-hook-form/react-hook-form/pull/9940#issuecomment-1431585324

**Comment by bluebill1049** [comment]
Yea, @Moshyfawn I will update the documentation to clarify this. I belive we shouldn't swallow error in the first place, it was a bad design decision.

**Comment by Moshyfawn** [comment]
I feel the same way.

It made devs forget to handle their promises lol

**Comment by bluebill1049** [comment]
yes, it's already in the doc

> handleSubmit function will not swallow errors that occurred inside your onSubmit callback, so we recommend you to try and catch inside async requests and handle those errors gracefully for your customers.

![image](https://user-images.githubusercontent.com/10513364/219203407-1ef9ec64-1897-4774-aaa8-fdfb8e16f153.png)

**Comment by adriantrunzo** [comment]
@Moshyfawn @bluebill1049 

Thanks for the quick response. I think this regression is an unexpected breaking change that is not documented in the release notes. 

> I belive we shouldn't swallow error in the first place, it was a bad design decision.

Whether or not it was a good decision, the behavior has been around for a while and a fair number of folks depended on it.

> It made devs forget to handle their promises lol

You are making an unfair assumption. I use React Query with React Hook Form, and the previous behavior allowed me to link the mutation state to the form state. For example:

See https://github.com/react-hook-form/react-hook-form/discussions/6574

I handle the promises and errors in the React Query hooks, but want `isSubmitting`, `isSubmitSuccessful`, etc to reflect the state of the mutation.

**Comment by Moshyfawn** [comment]
> You are making an unfair assumption.

Sorry, @adriantrunzo, I was just joking. Didn't mean to call anyone out

**Comment by adriantrunzo** [comment]
> yes, it's already in the doc

What about the documentation of `isSubmitSuccessful`?

![Screenshot 2023-02-15 at 3 39 42 PM](https://user-images.githubusercontent.com/1218900/219204471-56fd4968-627d-45e3-ae23-29b720f5deef.png)

`isSubmitSuccessful` is much less useful now, because if you always catch the error in the `handleSubmit` callback, `isSubmitSuccessful` will always be true, even for failed submits.

**Comment by Moshyfawn** [comment]
> Thanks for the quick response. I think this regression is an unexpected breaking change that is not documented in the release notes.

As to the changelog, [here it is](https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md#changed)

**Comment by adriantrunzo** [comment]
> As to the changelog, [here it is](https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md#changed)

Thanks, I did not see that file. I bet that I am not the only one who only looks at https://github.com/react-hook-form/react-hook-form/releases and not the changelog file. For example: https://github.com/react-hook-form/react-hook-form/releases/tag/v7.42.0. The new behavior isn't mentioned there.

**Comment by bluebill1049** [comment]
> isSubmitSuccessful



> > yes, it's already in the doc
> 
> What about the documentation of `isSubmitSuccessful`?
> 
> ![Screenshot 2023-02-15 at 3 39 42 PM](https://user-images.githubusercontent.com/1218900/219204471-56fd4968-627d-45e3-ae23-29b720f5deef.png)
> 
> `isSubmitSuccessful` is much less useful now, because if you always catch the error in the `handleSubmit` callback, `isSubmitSuccessful` will always be true, even for failed submits.

yes, I will update the doc on that. We will find a better way to resolve this issue.

**Comment by bluebill1049** [comment]
> isSubmitSuccessful is much less useful now, because if you always catch the error in the handleSubmit callback, isSubmitSuccessful will always be true, even for failed submits.

not sure if this has too much to do with try and catch with your promise, as long as the request is responded is still a successful call (even 400/500), unless runtime error.

**Comment by bluebill1049** [comment]
I would recommend doing the following instead, this gives you much better control instead of RHF swallowing the error and response with submitting successfully or not.

```tsx
onSubmit={handleSubmit(async () => {
  try {
    const response = await fetch()

    if (response.status > 200) {
      setError('root.request', {
        type: 'requestStatusError,
        message: 'your message here',
      })
    }
  } catch (e) {
    setError('root.request', {
      type: 'requestRuntimeError,
      message: 'your message here',
    })
  }
})}
```

**Comment by adriantrunzo** [comment]
> as long as the request is responded is still a successful call (even 400/500)

Yeah, I see what you are saying, but I don't think a lot of applications are structured to think of any response as a success. It most cases a non-200 API response is a failure and it is more helpful to have the form state reflect that failure.

> I would recommend doing the following instead, this gives you much better control instead of RHF swallowing the error and response with submitting successfully or not.

Thanks, that is a clear explanation of the recommended pattern. In my case, I rely on a combination of `isSubmitting` and `isSubmitSuccesful` to control various parts of the UI, for example disabling the submit button. With React Query, it has been great to pass the promise to `handleSubmit` so the the form state is aligned with the mutation, but handle any request errors in the mutation code, not `handleSubmit`.

I appreciate the responsiveness here and the ongoing maintenance of this library. For now, I can revert to 7.41.5 until I find a better pattern for using RHF with libraries like React Query and can update my code.

**Comment by Svish** [comment]
@adriantrunzo Found a good workaround yet?

Discovered this issue in our code-base too now, basically by accident. Not super happy that `react-hook-form` snuck a big change like that in without a big BREAKING in the release notes... 😕

**Comment by bluebill1049** [comment]
@Svish I wouldn't say this is a breaking change and it's in the release note & change note. Your code should always handle runtime errors from the on submit, react hook form shouldn't swallow any runtime error. However, I do respect everyone's opinion, so I will create a PR to not just swallow the error but provide a callback. This will not get merge and released right away, you should still deal with runtime error gracefully at your app level.

**Comment by Svish** [comment]
I guess I just don't see why this change was necessary. Resetting for example `isSubmitting` and increasing the submit count when submit is no longer running, regardless the reason, feels like a sensible choice to me.

And you have always been able to handle promise failures, you've anyways been able to add a try-catch to the submit-handler, no?

We used to show a message to the user if the mutation itself failed, which worked great. But now we suddenly have to add a try-catch to every submit-handler, otherwise the form will never stop "submitting", which is not good since we use that flag to disable the submit-button.

So, after this change, it feels like the submit-handler is less flexible, less ways to do things 🫤

**Comment by bluebill1049** [comment]
@Svish I hear you, would you like to review the proposal above in the PR?

**Comment by adriantrunzo** [comment]
@Svish The change we have made has been to subscribe to the mutation state and coalesce the form state and the mutation state (instead of awaiting the promise from mutateAsync in the handleSubmit onValid function). Here's a simplified example:

```
const {
  mutate,
  isError: isMutationError,
  isLoading: isMutationLoading,
  isSuccess: isMutationSuccess
} = useMutation(...)

const {
  control,
  register,
  handleSubmit,
  formState: { isSubmitting },
} = useForm(...)

const isFormSubmitting = isSubmitting || isMutationLoading

const handleFormSubmit = handleSubmit(
  (values) => mutate(values),
  () => console.log('invalid values')
)
```

Basically, just use the `isSubmitting` from RHF to handle the form submission state before the mutation is called (which is just validation really), and then use the mutation state for everything else. Ignore `formState.isSubmitSuccessful` as it doesn't contribute any useful information in this scenario. If you need to reset the form, show a notification, etc when the mutation finishes, do those actions in `onSuccess` and `onError` passed to the `mutate` function or, better yet, `useEffect` hooks that test `isError` and `isSuccess` from the mutation state. You'll need to use `useEffect` anyway if the post-submit action would cause your component to unmount. Otherwise, you will very likely run into a state update on unmounted component error.

You could absolutely use the suggested approach from @bluebill1049 above with mutateAsync:

```
const handleFormSubmit = handleSubmit(
  async (values) => {
    try {
      await mutateAsync(values)
    } catch {
      // Do nothing, error is handled in mutation callbacks.
    }
  },
  () => console.log('invalid values')
)
```

This approach would allow you to keep using `isSubmitting` as one boolean for the entire lifecycle of the form submission, but I don't think the verbosity is worth it. An empty catch statement is deceiving, anyway.

**Comment by Svish** [comment]
@adriantrunzo Thanks for sharing!

@bluebill1049 Not sure I understand what the PR does, what the result of it would/should be, or what the impact would be for others, so I don't feel comfortable doing that, sorry 😬
