### ISSUE TITLE
issue: Can not get the real field type

### ISSUE THREAD

**Issue by PeterChen1997** [react-hook-form/react-hook-form#9946]
Discussion：https://github.com/react-hook-form/react-hook-form/discussions/9939

### Version Number

latest

### Codesandbox/Expo snack

like this: https://codesandbox.io/s/react-hook-form-apply-validation-ts-forked-qq6w87?file=/src/index.tsx

### Steps to reproduce

1. See error

### Expected behaviour

1. declare field Option is optional, and the watch value is optional
2. but I want the submit value type is required, if I set the required rule in validation 🤔

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`defaultValues` are deepPartial which is what is returned by the watch, this is expected. We are moving away to the next major version with deep partial.

**Comment by PeterChen1997** [comment]
Ok, that means we will fix this problem in next version?

Another problem I found is that will we cause TS compiler performance problems with many deepPartial？

I found that after our ts server get stuck after upgrade to the latest version, it need 2 minutes to check the ts type 😂

![image](https://user-images.githubusercontent.com/21072589/219261629-f8daef71-4e08-40ef-9eda-1b25727e866c.png)

**Comment by bluebill1049** [comment]
yes, want to move away from deepPartail in the next major version update. it will be a breaking change.
