### ISSUE TITLE
issue: The validation result of nested object is not applied

### ISSUE THREAD

**Issue by yukukotani** [react-hook-form/react-hook-form#9948]
### Version Number

7.43.1

### Codesandbox/Expo snack

https://codesandbox.io/s/gracious-sinoussi-7y2vlc?file=/src/App.tsx

### Steps to reproduce

1. Input `2` to max
2. Input `3` to min
4. Console shows `error detected!`. This means `validate` function returns an error on L21
5. `errors.values.message` is still empty

### Expected behaviour

`errors.values.message` should be filled with the result of `validate` function

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I don't think I have documented such usage in the doc, and it wouldn't surprise me if it's not working as expected, especially dealing with when path overwrites. I would suggest using API such as `trigger` to resolve dependency validation.

**Comment by yukukotani** [comment]
@bluebill1049 Yeah it's not wrong that you don't expect that this undocumented code to work.

But one weird thing is that only the `errors` value is broken even though `validate` is executed and `isValid` is updated correctly. Maybe it will be better if there is consistency on this.

**Comment by bluebill1049** [comment]
could we do this instead?

```
const validate = (value, { min, max }) => {
  console.log("run validation");
  if (max < min) {
    console.log("error detected!");
    return "max should be greater than min";
  }
  return;
}

{...register("values.max", { required: "required", valdiate })}
{...register("values.min", { required: "required", valdiate })}
```

**Comment by yukukotani** [comment]
@bluebill1049 It works, but potentially `errors.values.max` and `errors.values.min` have the same error. This makes it complex to determine which errors to show, especially if `values.max` and `values.min` have other different validations.

This works well.

```ts
register("values", {
  validate({ min, max }) {
    console.log("run validation");
    if (max < min) {
      console.log("error detected!");
      return "max should be greater than min";
    }
    return;   
  }
});

const triggerValidation = () => trigger("values");

{...register("values.max", { required: "required", onChange: triggerValidation, onBlur: triggerValidation })}
{...register("values.min", { required: "required", onChange: triggerValidation, onBlur: triggerValidation })}
```

**Comment by bluebill1049** [comment]
I see, maybe you can have two validate functions for each input instead of extra `register` and `trigger`?

**Comment by bluebill1049** [comment]
I am going to close this issue for now.
