### ISSUE TITLE
Change on values option makes the form dirty

### ISSUE THREAD

**Issue by davbrito** [react-hook-form/react-hook-form#9955]
### Version Number

react-hook-form@7.43.1

### Codesandbox/Expo snack

https://codesandbox.io/s/gifted-river-tjkm58?file=/src/App.tsx

### Steps to reproduce

1. Go to the Codesandbox
2. Click on update values
3. See how isDirty becomes true

I've seen that this behavior happens when there is an array of items and those are controlled inputs.

### Expected behaviour

The expected behavior is that the form remains not dirty since it is reseting the data with the new values.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
You set `keepDirtyValues: true` which indicates RHF to keep the new `values`, which makes the form dirty
