### ISSUE TITLE
issue: Radio is not checked by default if `Controller` is used for form control.

### ISSUE THREAD

**Issue by kaguya3222** [react-hook-form/react-hook-form#9956]
### Version Number

7.43.1

### Codesandbox/Expo snack

https://codesandbox.io/s/cranky-hooks-9dosyj?file=/src/App.js

### Steps to reproduce

1. Go to Codesanbox
2. Look at radio inputs and make sure that `light` radio is not selected by default, despite the fact that `light` is default value for form.

### Expected behaviour

`light` radio group should be checked by default as it checked in [this](https://codesandbox.io/s/unruffled-swirles-snnil6?file=/src/App.js) version, where `register` is used for form control

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
I'm pretty sure you need to do `checked={field.value === 'dark'}` as the `value` prop doesn't indicate `radio` input is checked.

**Comment by kaguya3222** [comment]
@Moshyfawn I've already done this as a fix, but I'm confused why [this](https://codesandbox.io/s/unruffled-swirles-snnil6?file=/src/App.js) version works without `checked` prop 🤔

**Comment by Moshyfawn** [comment]
> @Moshyfawn I've already done this as a fix, but I'm confused why [this](https://codesandbox.io/s/unruffled-swirles-snnil6?file=/src/App.js) version works without `checked` prop 🤔

In [the example you provided](https://codesandbox.io/s/unruffled-swirles-snnil6?file=/src/App.js), the radio inputs are uncontrolled _(use `register` / don't have value "fed" into them)_.

In case of uncontrolled input, RHF takes the input's `ref` and manually sets the `checked` property to set input's default value.

**Comment by kaguya3222** [comment]
@Moshyfawn 🤔 I thought that when we use `register` we also get a controlled field. Seems that I don't understand the difference between `register` and `control`.

As I understand everything works as expected, so I need to read docs I think.

**Comment by Moshyfawn** [comment]
You should definitely check out the docs, but TLDR is: with `register`, you're spreading the field name and the event handlers like `onChange`, `onBlur` etc into the input + "registering" input's ref with RHF. There's no `value` returned from the `register` method; the source of truth for the input's value is the input - the uncontrolled input. We don't "feed" value into it. It reduces the amount of re-renders as we don't subscribe to the RHF field state.

With `Controller` / `useController`, it returns all the even handlers + **the field `value`**, subscribing to RHF field value of that specific field. This allows for more fine-grained user-defined behaviour and you are in control of how your input "consumes" the value and the handlers. You can still register the input's `ref` with `Controller` / `useController` but RHF won't update the input internally. You need to handle it yourself.

**Comment by kaguya3222** [comment]
@Moshyfawn Thank you for the such nice feedback! I think it can be closed
