### ISSUE TITLE
issue: Undesired focus on error field after revalidation while using 'watch'

### ISSUE THREAD

**Issue by ivanovserge** [react-hook-form/react-hook-form#9972]
### Version Number

7.43.1

### Codesandbox/Expo snack

https://codesandbox.io/s/rhf-bug-with-focus-on-error-field-after-revalidation-1q19nv

### Steps to reproduce

1. Click on 'Submit' button.
2. See validation error on both text inputs.
3. Fill the second input.
4. See error.

### Expected behaviour

The first text input shouldn't be focused after the second one is filled. When 'watch' is not used there's no error.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
I already mentioned it in #9973, this behaviour is due to the `InputField` defined inside another component.

> As a side note, avoid defining React components inside other components to avoid re-initialization on each parent component render and potentially ref issues (input's ref will be different on each render)

https://github.com/react-hook-form/react-hook-form/issues/9973#issuecomment-1438573634

**Comment by ivanovserge** [comment]
@Moshyfawn I've just update my codesandbox and move `InputField` into a separate file and the error still occurs.

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/220454191-cc54b1ef-3bfb-4263-a0af-bbba78bf6953.mov

I couldn't reproduce the issue.

**Comment by Moshyfawn** [comment]
> I couldn't reproduce the issue.

Submit -> Edit **2nd** input

**Comment by Moshyfawn** [comment]
Sry, I'm currently at work

**Comment by bluebill1049** [comment]
no worries, i will look into it.

**Comment by bluebill1049** [comment]
This is somewhat related to MUI text filed, I don't think it's a root cause of react hook form. I have switched to a native input and the issue go away, and rmeove `const refCallback = useMergeRefs([ref, propRef]);` resolve the issue as well.

**Comment by Moshyfawn** [comment]
> This is somewhat related to MUI text filed, I don't think it's a root cause of react hook form. I have switched to a native input and the issue go away, and rmeove `const refCallback = useMergeRefs([ref, propRef]);` resolve the issue as well.

I was able to repro excluding both MUI & `forwardRef`: [sandbox](https://codesandbox.io/s/rhf-bug-with-focus-on-error-field-after-revalidation-forked-ubis6c?file=%2Fsrc%2FApp.js).

Seem like the behaviour is induced by `mode: "all"`: after the first submission the focus is stolen by every erroneous input in order of appearance. Doesn't happen before the submission.

**Comment by bluebill1049** [comment]
thanks a lot @Moshyfawn i will patch it now
