### ISSUE TITLE
onTouched form mode. Don't validate for empty field. Reset to untouched.

### ISSUE THREAD

**Issue by fluidnotions** [react-hook-form/react-hook-form#9981]
**Is your feature request related to a problem? Please describe.**
Using onTouched form mode. Don't validate for empty field. Reset to untoched (doesn't seem to be possible)

**Describe the solution you'd like**
Lets consider 2 inputs. We’ll call them input1 & input2. These are both required fields.

Current Behavior:
A user enters invalid data in input1 & switches focus to input2.
The user now sees a validation error on input1, they have not entered any values in input2, they switch focus to input1
Now that they have switched focus to input1, input2 since it is required, shows a validation message

Expected Behavior:
When step 3 occurs, input2 should not show a required validation message, although focus has been set there has been no change.

**Describe alternatives you've considered**
I've looked at the source code. Besides using a dynamic form to get arround this. I couldn't find any way to achieve this, it makes sense because they are required. But apparently from a UX point of view having 2 validation errors in confusing. ie: the one revealed on blur from input 1, the blur being focus on input2 & on return to input1, required field shows a validation error. Now the user has 2 validation erros drawing attention to differrent fields.

**Additional context**
example implementation https://app.theydo.com/register

**Comment by bluebill1049** [comment]
I am not sure we should apply such an exception for touched. Perhaps having a manual method or alternative API is more suitable.

**Comment by bluebill1049** [comment]
Moving to the project board, this is something we probably won't change right now. Instead maybe introduce function such as `setTouched`
