### ISSUE TITLE
Ability for `setError('root')` do not change form `isValid` state

### ISSUE THREAD

**Issue by peakercope** [react-hook-form/react-hook-form#9982]
**Is your feature request related to a problem? Please describe.**
New `setError('root')` feature provides a better developer experience for handling global form error (server errors). 
But setting root error changes `isValid` state to false. 
There is a case when by business logic of application it is required to disable submit button until all fields are valid.
So there is a case, when form receives error from server (e.g. "server is temporary unavailable, please try few few minutes later"), sets root error type and submit button becomes disabled so user unable to retry form submission.

**Describe the solution you'd like**
Maybe is't possible to add some parameter to `setError()` to tell do not change `isValid` state to false. 
Or add new method like `setWarning()` which sets another formState called `warnings`.

**Describe alternatives you've considered**
For now I'm using regular react state for saving error messages which should not affect `isValid` state.
```js
const [error, setError] = useState('');
```

**Comment by bluebill1049** [comment]
API-wise perhaps the following:

`setError('root', { type: 'error' }, { keepIsValid: true } )`

**Comment by bluebill1049** [comment]
Moving into the project board.

**Comment by peakercope** [comment]
@bluebill1049 
As I see from documentation `setError` doesn't have `keepIsValid` option
https://react-hook-form.com/api/useform/seterror

```js
setError:(name: string, error: FieldError, { shouldFocus?: boolean }) => void
```

**Comment by bluebill1049** [comment]
That was my proposal.
