### ISSUE TITLE
How to handle server responses not related to any field?

### ISSUE THREAD

**Issue by outerlook** [react-hook-form/react-hook-form#999]
Hi! 

Is there a proper way to retrieve an error from server (general error, not related to a field) on submission and then show it to users, using the library?

Example: login form with only email and password fields:

form is submitted, but some network error happens on server. I would like to, elegantly, do something like setError("server", "Oh oh! Something went wrong. Please try again later.")

or maybe an "status" object on FormContext, which the user itself could manage. Would this bring performance issues? 

If possible it could be  type safe too. 

with:
useForm<FormValues,FormStatus>()

Just asking, as I don't understand if this implementation would bring unnecessary re-renders, which is one of the biggest pro's of this library. Thanks!

**Comment by bluebill1049** [comment]
`setError("server", "serverError", "Oh oh! Something went wrong. Please try again later.")`

it's exactly what you had above. you can invoke that in the `handleSubmit` after your request

**Comment by outerlook** [comment]
I can do that, but wouldn't later typescript complain about me trying to access errors.server, if server isn't a field at all?

**Comment by bluebill1049** [comment]
you can type that external `serverError` as a field? alternative maybe just use `useState` then.

**Comment by outerlook** [comment]
yes, that would solve it. Feels a little like a workaround, I don't know, but it is simple enough. I know it's hard to say if the library should do something specific for this case, unless it is really really common on other forms. Thanks for your time, @bluebill1049 , that was fast and kind.

**Comment by bluebill1049** [comment]
no worries :) @outerlook 🙏 We had people suggest to return from handleSubmit and treat them as errors, but it's bit weird at the same time... :(

**Comment by outerlook** [comment]
Agree!
