### ISSUE TITLE
issue: valueAsNumber, submit without changes

### ISSUE THREAD

**Issue by sshmyg** [react-hook-form/react-hook-form#9990]
### Version Number

7.43.2

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-validation-valueasnumber-forked-731mvr?file=/src/App.jsx

### Steps to reproduce

1. Go to '/src/App.jsx'
2. Click on 'Submit button without any changes'
4. Open console log, and will see `{age: isNaN}`

### Expected behaviour

`valueAsNumber` without changes should return not `isNaN`. 
Maybe perform `setValueAs`  not only on change, but on submit or any others actions.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
`valueAsNumber` is the native Web **input** API specific to inputs **only** of 
- Date types
- `number`
- `range`

Additionally, calling `target.valueAsNumber` on an input with `value` `"" _(empty string)_` returns `NaN` and RHF API is aligned this API.

You can read more on the `valueAsNumber` specs [here](https://www.w3.org/TR/2011/WD-html5-20110525/common-input-element-attributes.html#dom-input-valueasnumber)
