### ISSUE TITLE
issue: Accessing isValid from useFormState() causing wrong output from getValues() method

### ISSUE THREAD

**Issue by Shamanth-kalyan** [react-hook-form/react-hook-form#9997]
### Version Number

7.43.2

### Codesandbox/Expo snack

https://codesandbox.io/s/infallible-surf-pwt1bz?file=/src/App.tsx

### Steps to reproduce

1. Go to code sandbox link
2. Check the console log
3. When "isValid" is accessed from "useFormState" the "getValues()" initially return "defaultValues" instead of "values"

### Expected behaviour

When "isValid" is accessed from "useFormState" the "getValues()" should return "values" initially

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I think this is due to 

```
resetOptions: {
  keepDefaultValues: true
}
```

**Comment by Shamanth-kalyan** [comment]
Yes, but if I don't subscribe to "isValid" key from "useFormState" then it works fine.

Expected behaviour should be when we pass "keepDefaultValues": true the form should keep the defaultValues as it is. And when I call "getValues()" it should return the values I passed to useForm not the defaultValues.

right?

**Comment by bluebill1049** [comment]
If you set to `keepDefaultValues: true`, that means do not update `defaultValues`, so when you subscribed to `isValid` a `formState` update will be flushed and hence `defaultValues` gets cached.
